### ISSUE TITLE
Ionic serve getting hung up on webpack

### ISSUE THREAD

**Issue by shaneparsons** [driftyco/ionic#10001]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When running ionic serve the process often hangs on `webpack started`, at which point the only thing I can do is quit / re-run ionic serve. This happens rather frequently.

**Expected behavior:**
The build process not getting hung up.

**Steps to reproduce:**
Run ionic serve -> make / save some changes to code (sometimes containing errors) -> repeat

**Other information:**
[Here's](https://forum.ionicframework.com/t/webpack-frequently-freezes-when-started/74226) a post on the forum describing the exact same issue I'm having.

**Ionic info:**
```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#646
