### ISSUE TITLE
Android popover positioned as if window height and width are zero

### ISSUE THREAD

**Issue by mattbryan9** [driftyco/ionic#10015]
**Ionic version:**

[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**

[X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**

Popover is positioned as if the window height and width are zero.

**Expected behavior:**

The popover would be positioned in the center of the window, as in iOS.

**Steps to reproduce:**

Display a popover with `popover.present()` on an Android device (we've tested on Pixel and OnePlus 3T).

**Related code:**

In `Platform._calcDim`, this evaluation is not correctly recognizing our orientation as portrait.
 `this._pW` and `this._pH` are equal to `win['innerWidth']` and `win['innerHeight']`, respectively. 
```
if (this._pW < win['innerWidth']) {
  this._isPortrait = true;
  this._pW = win['innerWidth'];
}
if (this._pH < win['innerHeight']) {
  this._isPortrait = true;
  this._pH = win['innerHeight'];
}
```
As a consequence:
1. `this._isPortrait` is left as null
2. `Platform.width` and `Platform.height` evaluate that the body is landscape
3. `_lw` and `_lh`, both `0`, are returned by those functions
4. `bodyWidth` and `bodyHeight` are set to `0`, skewing the values of `top` and `left` for `popover-content`

**Other information:**

Using `<=` in the evaluations above could solve this for our particular case. But maybe it would screw up other cases.

**Ionic info:**

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v4.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by brandyscarney** [comment]
This should be fixed with the latest nightly: `ionic-angular@2.0.0-rc.5-201701232249`, please let us know if you're still seeing a problem. Thanks!

**Comment by 64jcl** [comment]
Ah good. How do I update my ionic-angular to the latest version? I also noticed on Android that platform.width() always returned 0 suddenly.

**Comment by 64jcl** [comment]
Assuming the npm install command I wrote above actually gets the nightly, the platform width reported is still rather erratic. My HTC m7 returns 360 pixels width for some time, then suddenly it returned 640 width and 335 height - even though the app had been set to portrait only (I have added a sanity check for this and swap them as needed in my app in case this happened). After that it consistently returned 335 width even though it's 360... Killing the app and restarting and its back to 360 for a while. One thing I do use with my app is the camera plugin so perhaps its something related to that which creates this odd behaviour?

**Comment by 64jcl** [comment]
Ok, figured it out from another thread Brandy. :) - Updated with the nightly and the problem seem to have been fixed. Yay! :)

`npm install --save --save-exact ionic-angular@2.0.0-rc.5-201701232249`

**Comment by brandyscarney** [comment]
@64jcl Sorry I didn't write the full command! Glad you got it working and this is fixed. :)

**Comment by brandyscarney** [comment]
Closing this since it will be fixed in the next release. :)

**Comment by mattbryan9** [comment]
Just got rc6 and it works. Thanks! :)
