### ISSUE TITLE
RC-5 import { TextArea} from 'ionic-angular' gives error

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#10012]
Hello, 
I have just upgraded my app from RC-4 to RC-5 and suddenly I am getting error on following code..

```
import { TextArea } from 'ionic-angular';
```
It says that..
```
node_modules/ionic-angular/index"' has no
           exported member 'TextArea'.
```
Let me know that in which module it is moved?

**Comment by jsayol** [comment]
Looking at the code, it looks like the `<ion-textarea>` component is now also handled by the `TextInput` class. There's no specific `TextArea` class anymore.

This should have been mentioned in the release notes as it's quite a breaking change. Just a slip-up, I suppose.

**Comment by jsayol** [comment]
@bimal72 and for anyone else running into this: simply replace any use of `TextArea` with `TextInput` and everything should keep working as usual.

**Comment by jgw96** [comment]
Thanks for the heads up @jsayol ! Fixed in this commit https://github.com/driftyco/ionic/commit/1ef21f462276b40a57a54cd30f1c4397cd0c2468
