### ISSUE TITLE
ionic2 - enhancement(modal) - Add option to make modals full screen on tablets

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#10021]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Modals always appear inset on tablets.

**Expected behavior:**
I would like an option to make a modal full screen, just as it would appear on a smaller screen like an iPhone.

**Comment by mhartington** [comment]
A simple work-around is to modify the css that scales the modal on larger devices. 
Though from a UX standpoint, not sure how great this would be.

**Comment by zakton5** [comment]
The only problem with that is that I have one modal that should be inset as is, and another that I want to display full screen.

**Comment by shawnlan** [comment]
We should have options to open a modal fullscreen or not on tablets. This is basic and is supported natively on iOS: https://developer.apple.com/ios/human-interface-guidelines/interaction/modality/

Any workaround for now? I want one modal to be form sheet, and another to be fullscreen. Thanks!

**Comment by rajeevriitm** [comment]
Is there any work around for now?
```
ion-modal {
    .modal-wrapper {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        height: 100%;
    }
}

This changes it to fullscreen , bu it would change it globally. I want some modals to be fullscreen and some not.
```

**Comment by zakton5** [comment]
This has been implemented in a recent release, so I'll be closing this.

**Comment by shawnlan** [comment]
What version? I didn't see anything in the official docs.

**Comment by zakton5** [comment]
It should be in 3.1

**Comment by shawnlan** [comment]
@zakton5 Oh you mean `cssClass` option?

**Comment by zakton5** [comment]
@shawnlan Yes, you can make a class to make your modal full screen. You may also have to modify some ionic sass variables.
