### ISSUE TITLE
ion-input pattern '\' char wrong.

### ISSUE THREAD

**Issue by Csirme** [driftyco/ionic#10022]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```
//eg:
<ion-input pattern="((13[0-9])|(14[5|7])|(15([0-3]|[5-9]))|(18[0,2,3,5-9]))\d{8}"></ion-input>
//gen:<input pattern="((13[0-9])|(14[5|7])|(15([0-3]|[5-9]))|(18[0,2,3,5-9]))d{8}">  when build iOS.
//it's right on IOS platform.
//but it's wrong on web platform.
//eg:
<ion-input pattern="((13[0-9])|(14[5|7])|(15([0-3]|[5-9]))|(18[0,2,3,5-9]))\\d{8}"></ion-input>
//it's wrong on IOS platform.
//but it's right on web platform.

//just '\' chat,hope you fix it next version.
//thanks
```

**Comment by alexbainbridge** [comment]
See this
https://github.com/driftyco/ionic-app-scripts/issues/524

I found a solution, which is to use 3 slashes :)
