### ISSUE TITLE
bug: The "ionic start" fails to create the project

### ISSUE THREAD

**Issue by GooseCoder** [driftyco/ionic#1002]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  webview

<span ionic-webview style="display:none;">true</span>

<span ionic-description>Hi !
First of all congrats for the great job you are doing with the ionic framework. I been trying to start a project using the ionic command utility, but every time I run the start command, for example:

$  ionic start MyApp tabs
Running start task...
Creating Ionic app in folder /Volumes/Development/IOS/PROJECTS/MyApp based on tabs project
DOWNLOADING: https://github.com/driftyco/ionic-app-base/archive/master.zip

The process ends in that line, the build is incomplete as only a "ionic-app-base-master" directory and a "ionic.project" file are created.
These are the settings that I been using:
git version 1.8.5.2
node version v0.11.12
npm version 1.4.3
gulp version 3.6.0
I use the node version manager in order to administrate multiple versions of node, I'm not sure if that is the cause of the issue.
Any help will be appreciated. Thanks in advance.</span>

<span is-issue-template></span>

**Comment by lordazzi** [comment]
Lie, I'm in the future (06/2015) and i'm getting this error e.e
