### ISSUE TITLE
RC5 - options attribute removed, what's the equivalent?

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#10024]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report

After upgrading to RC5, the whole app is upside-down, as the design of my app is fully based on multi-view slides. I've discovered that options attribute was removed!

What's the equivalent of options attribute?

**Comment by brandyscarney** [comment]
Please see my comment here: https://github.com/driftyco/ionic/issues/9988#issuecomment-272473892

Thanks!
