### ISSUE TITLE
*ngIf does not work well in IBM MFP Cordova 7.1

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic#10035]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am currently implementing ionic in IBM MobileFirstPlatform (MFP) Cordova 7.1. 

Since I update to Ionic 2.0.0 RC4, *ngIf does not does not work well after a MFP adapter is executed.  In my app,  I am using *ngIf="variable=true/false" to hide/show my html elements. Although the value of the variable had changed (I can confirm as the value is shown in console log), the html element is not shown/hidden according to the *ngIf. 

The strange part is, the html element that supposed to be shown/hidden will be shown/hidden after I minimize the app and resume back. I'd just updated to RC5 but does not help. The only solution is fall back to RC3. 

**Expected behavior:**
The UI lag should not present. 

**Steps to reproduce:**
Execute an adapter of IBM MFP 7.1. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.4.0
Xcode version: Not installed

**Additional info**
MFP Cordova 7.1

**Comment by ghenry22** [comment]
How are you updating the variable used for the ngif? Some events, usually triggered by plugins, will need to be manually wrapped in ngzone to ensure change detection is triggered.

**Comment by rephchunhoong** [comment]
Hi @ghenry22, 

I am not updating the variable from any plugin. It is just a pure simple "(click)" action of a button, which trigger a method that set the variable from true to false and vice-versa.

**Comment by ghenry22** [comment]
Ah then that would be something else entirely, just sounded like the same symptoms I have seen before with callback code executing outside ngzone

**Comment by rephchunhoong** [comment]
@ghenry22 What is a callback code executing outside ngzone? Would appreciate if you can describe more, so I can see if it relates to my situation.

**Comment by ghenry22** [comment]
https://github.com/driftyco/ionic/issues/9974

This is an example, the ionScroll, ionScrollStart etc events call a defined method.  I can see from console.log statement that the method does get called when the event is emitted and my value is updated, but the view does not update (change detection is not triggered).

By importing NgZone and manually wrapping the code in my function with ngzone.run then the updates my code makes do trigger angular change detection and the view does update.

There are a bunch of other examples on the ionic forums, it is quite common for plugins in particular which emit events to have this issue.

**Comment by rephchunhoong** [comment]
Thank you @ghenry22. I will try to have a look into it.

**Comment by wbhob** [comment]
Also, `*ngIf="variable=true/false"` is not the proper syntax, as you had above. You also didn't include any snippets, so I can't tell if it's an issue with MFP or your implementation. Anyway, as you probably know, the syntax is `*ngIf="variable"`.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question and with the fact that we do not officially support the IBM MFP technology i will urge that you ask this question on our forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
