### ISSUE TITLE
How to use web push notifications using service workers in Ionic 2 ?

### ISSUE THREAD

**Issue by mbj36** [driftyco/ionic#10040]
I am working on a pwa with ionic 2 and want to implement web push notifications in my app using service workers

**Comment by root-io** [comment]
I found all the answers here: https://serviceworke.rs/push-simple_index_doc.html

**Comment by mbj36** [comment]
@root-io How to implemenent in ionic 2 ? Ionic follows typescript

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
