### ISSUE TITLE
bug: Blank screen appearing when app started phone

### ISSUE THREAD

**Issue by santhan456** [driftyco/ionic#10047]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I just created an ionic side menu app v2. Without any modification I built the apk. When I started the app in device a blank screen is appearing after the splash screen went off. I am unaware how to debug this bug (or any exception) from device. I am using ubuntu 15.10 for the development. I will be glad if anyone tell me how. Or I can get any help how to to rectify this bug. I am giving the info of my app below. And last thing there are no errors caught when I did 'ionic serve'. App worked in emulator well. But not in device.

Thanks .. 

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.0.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v7.4.0</span>

<span is-issue-template></span>

**Comment by Gp2mv3** [comment]
Hi ! 
Welcome to Ionic2. ;)
Try to open the device inspector on Chrome/Chromium (type chrome://inspect in the address bar). Then go to your device and you will be able to open the developer console from your mobile. It's really useful to get the errors and thus help you.

Regards,

Gp2mv3

**Comment by santhan456** [comment]
Hi Nicolas,
Glad to hear from you. Thanks for the help. It seems there is no error. But there is a message as below.

Native: device ready did not fire within 2000 ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.

DEVICE READY FIRED AFTER 8278 ms

I tried remove and reinstalling plugins. Well it is a new app. What plugin might actually resulting this 8 second delay ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
