### ISSUE TITLE
Don´t automatic setting a page in Modules when add new page by the cli.

### ISSUE THREAD

**Issue by yargomascarenhas** [driftyco/ionic#10042]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a execute "ionic g page ´page-name´" in Ionic Cli, the new page is created but this dont is seted in Modules...

**Expected behavior:**
Seted in Modules automatic when i add new page by the cli.

**Comment by wbhob** [comment]
This is two things:
1. Something the Ionic team is working on right now.
2. An issue that should be at [the CLI repo](https://www.github.com/driftyco/ionic-cli).

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1860
