### ISSUE TITLE
Option to reset datepicker with "X" icon

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#10041]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Currently I have some optional date picking fields. A user told me he accidentally opened the picker but was unable to reset the field. It would be nice if there was a "X" icon to clear the field.

**Comment by brandyscarney** [comment]
Thanks, I'm going to close this as a duplicate of https://github.com/driftyco/ionic/issues/7333
