### ISSUE TITLE
Bug: ion-footer although position absolute, no longer stays attached to bottom

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#10059]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
A button in an ion-footer on a list.... where the list has a reasonable number of entries, sufficient that they are more than one screen full.... When you scroll up and down, the list AND the footer go up and down.

**Expected behavior:**
I would expect the footer to stay static and the list items to move up and down, behind the footer

Looking at the code, looks like my expectation is also the intention of the developers, so this is a bug. 

**Steps to reproduce:**
See Plunkr

http://plnkr.co/edit/TSJ4AmgmEH3SOMrJdxk2?p=preview

Scroll up and down. Button moves when it should not. 

**Other information:**
Looks like the right CSS is applying (position:absolute) but not sure why the footer scrolls. 

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ghenry22** [comment]
@alexbainbridge move your ion-footer after the closure of ion-content.  It works the same way as ion-header does before ion-content at the top.

**Comment by alexbainbridge** [comment]
Oh yes! Thanks @ghenry22

**Comment by amruzzi** [comment]
@ghenry22 Thank you!!!
