### ISSUE TITLE
bug: Ionic Native Camera getPicture never returns iOS10

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic#10054]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using the latest ionic native (not ngCordova) with an Ionic 1.x app and I am testing on my iOS 10 device. When I call `$cordovaCamera.getPicture(options).then(success).catch(failed);`, it never returns.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#980
