### ISSUE TITLE
White screen after the app has been paused?!

### ISSUE THREAD

**Issue by gopchi** [driftyco/ionic#10069]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I open the app, then click the back button, go to Instagram for example, then go again to my apps and try to open my app, it loads super slow showing a white screen for around 4-5 seconds before it resumes.
Any suggestions?

**Expected behavior:**

I was expecting the app to open quickly and to fire the functions which are in my 'resume' event listener.

**Steps to reproduce:**

**Related code:**

Here is a plunkr
http://embed.plnkr.co/51ZN2oi9nAym5rmisStN/

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
How can I debug this? What does the app look like? Is there any code that you are trying to call? I need more information in order to debug this.

**Comment by gopchi** [comment]
Hi @mhartington 
I put everything in a public repo - [https://github.com/gopchi/Ionic-2-App](url)
Hope this helps.

**Comment by dylanvdmerwe** [comment]
Here is a video that further demonstrates this issue: https://goo.gl/photos/MnxFLYx258jMybGF8

**Comment by gopchi** [comment]
@dylanvdmerwe  That's exactly the issue...

**Comment by dylanvdmerwe** [comment]
See the fix suggested here: https://github.com/driftyco/ionic2-app-base/commit/5a677bf5e965c0f2466554fbd26fc0cfefbc56e0

For more info: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/#android-quirks

Issue can be closed.

**Comment by mhartington** [comment]
@gopchi  can you try setting that value in your config.xml and testing this out ? 

```
<preference name="SplashShowOnlyFirstTime" value="false" />
```

Just want to make sure it address what you're seeing.

**Comment by gopchi** [comment]
Yep, everything worked properly, thanks for the support! I just want to ask if you could reference me some page or docs that show how to implement an alert that says "Do you really want to exit the app?  when the user clicks on the back button to exit the app.

**Comment by manucorporat** [comment]
@gopchi 
> I just want to ask if you could reference me some page or docs that show how to implement an alert that says "Do you really want to exit the app? when the user clicks on the back button to exit the app.

That is not currently supported by ionic, would you mind to open a new issue requesting for that feature?

In the meantime, you could intercept the call to:
```
window.navigation.app.exitApp()
```
it is a cordova only method, so be careful ;)

**Comment by nisos-siddharth** [comment]
I also have the same problem.
I am implementing the Ionic2 app. In this after the app starts splash screen is showing but if I quickly minimize the app (before splash screen disappears) and resume the app the splash screen is gone and showing the white screen.
I already added 
`<preference name="SplashShowOnlyFirstTime" value="false" />`
But its not working for me.

**Comment by syedsaadmahmood** [comment]
<preference name="SplashShowOnlyFirstTime" value="false" />
This worked for me

**Comment by flrrrhoffpauir** [comment]
I am having the same problem except that the white screen never goes away!
