### ISSUE TITLE
npm error when install ionic-native

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic#10075]
**Ionic version:**  (check one with "x")
[ x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I am trying to install ionic-native and I get this error:

    $ npm install ionic-native --save
    boardline@1.0.0 /home/louisro/Documents/mobileApps/BoardLine/ionic_version
    ├── UNMET PEER DEPENDENCY @angular/core@>=2.0.0-rc.0 <2.0.0-rc.5
    └── ionic-native@2.2.16 
    
    npm WARN @ionic/cloud-angular@0.4.0 requires a peer of @angular/core@>=2.0.0-rc.0 <2.0.0-rc.5 but none was installed.

**Expected behavior:**

I would like to do a clean install of ionic-native.

**Steps to reproduce:**

just:

    $ npm install ionic-native --save

**Related code:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.4.0
Xcode version: Not installed

$ cordova platform version androidInstalled platforms:
  android 6.0.0

```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#979
