### ISSUE TITLE
DOM Update when I added new Item

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10072]
Hi all,

I used angular fire 2 with chat Application in  ionic2

I added value in firebase 

But DOM Cannot display added value the same time 

Kindly advice me,

Thanks & Regards

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
