### ISSUE TITLE
RC5: Remarkable delay when pressing a button/tab on a real Android device

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#10080]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Run the current ionic-conference-app in prod mode on a real android device, I'm using a Motorola G2 with Android 6.0.1.
Tab on any sidemenu item or select a tab.
I experience a slightly/remarkable delay of half a second until the button/tab reacts.
@jgw96 Can you observe this effect on your real Android device, too?

**Expected behavior:**
Immediate reaction (no remarkable delay) when pressing a button/tab.
This was much more snappy, when ionic 2 was in .beta phase.

**Related code:**
ionic-conference-app

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5-201701112208
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by fiznool** [comment]
I'm seeing the same issue too with Ionic RC 5 on a Sony Z3 Compact running Android 6.0.1.

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us! So on my nexus 7 (which has similar specs to a moto g) it is slightly slower than for example on my Nexus 6, but i would expect a few ms delay on an older device. I unfortunately do not experience the half second delay that you are speaking of. @mpaland would you be able to make a video of this? Id love to see it for myself

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by mpaland** [comment]
@jgw96 I've tested this on an actual Lenovo Tab3 (Android6). You see the actual lazy loading conference app branch build with ionic 3.0.0-beta3 and --prod flag.
Here is the video:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/763140/24699598/da06ce18-19f4-11e7-8ace-d9cb902bf0a4.gif)
You can see it best on the "speakers" tab. After pressing there seems to be a (300 ms) delay, than you see the action. Due to this problem, the app feels not snappy.
And startup time is still bad. Takes up to 7 sec to launch the conference app.

**Comment by mpaland** [comment]
`ionic serve` on Chrome and FF doesn't show this behavior! But it can be observed very good in the Windows build of the conf app as well.

**Comment by mpaland** [comment]
Update to 3.0.1
@manucorporat , seems that 59f9737d9b4d3de3b862b47b0af79344bf0268c1 improved this issue. Thanx!
@jgw96 Delay time is better now, but there are still two things:
1. Delay on "Speakers" Tab is still remarkable, but I think it's more like a conf-app issue.
2. conf-app in "ios" mode is fine on Windows, but conf-app in "md" mode has still a short tab click delay. May this be caused by the md transition?
