### ISSUE TITLE
ion-select slow speed with large list

### ISSUE THREAD

**Issue by tieppt** [driftyco/ionic#10087]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am currently using ion-select to display about 200 countries for a form. I've noticed that the ion-select can be quite slow.

**Expected behavior:**
Is there any way to speed this up? I think change detection may help speedup performance [ANGULAR CHANGE DETECTION EXPLAINED](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html)

**Steps to reproduce:**

**Related code:**

```ts
      <ion-item>
      <ion-label stacked ion-text color="dark">Country *</ion-label>
      <ion-select formControlName="country"
        (ionChange)="countrySelected($event)"
      >
        <ion-option *ngFor="let c of countries" [value]="c.code">{{c.name}}</ion-option>
      </ion-select>
    </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look into this.

**Comment by AbhayShiro** [comment]
Has the issue been solved?
I am facing the same issue. I have a state select list and a city select list which loads data dynamically from array.
City array has some 1200 approx values. This causes heavy lag.
Please help.

**Comment by daveshirman** [comment]
Why don't you change your select to a modal window popup with a search
field which has the list in a virtual list component. Add a search field
and a pipe filter too.

**Comment by AbhayShiro** [comment]
I managed to solve issue.
I have a long json with 1200+ objects as i mentioned previously. Each object contains city, state property. 
I did NGFOR on a select and loaded all the states only using lazy loading......  once the user selects a state, i show another select which contains cities for the selected state(as soon as the state gets selected, in the ts file i create a city array by filtering out objects for the selexted state name using lodash;this new array is used for city dropdown)

This way there is a great performance boost.

**Comment by naveedahmed1** [comment]
@jgw96  any progress on this issue?

**Comment by ultraMIND** [comment]
Still an issue. The basic select work far more smoothly. (i've 518 options on my select. Platform android)

**Comment by chinmay-ksolves** [comment]
Has the issue been solved?
I have a list of 2550 items and I am adding it to <ion-options> dynamically, this causes a heavy lag.
<ion-option *ngFor="let item of itemList" [value]="item"> {{item}} </ion-option>

**Comment by xperiafan13-rom** [comment]
some here

**Comment by Ali-H-A** [comment]
Same,

I have a long list of images and the application works slow when I load more than 50 to 100 images in the page

**Comment by dmacasero** [comment]
Hi,

Same Issue here when loading 70+ data on the ionic select.
