### ISSUE TITLE
Couldn't find ionic.config.json file. Are you in an Ionic project?

### ISSUE THREAD

**Issue by ATakaSKY** [driftyco/ionic#10094]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On running ionic start myApp tabs, I get the following error:

> Installing npm packages (may take a minute or two)...
> Error with start Error: spawn UNKNOWN
>     at exports._errnoException (util.js:870:11)
>     at ChildProcess.spawn (internal/child_process.js:298:11)
>     at Object.exports.spawn (child_process.js:362:9)
>     at spawn (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\                                                            ionic-app-lib\node_modules\cross-spawn\index.js:17:18)
>     at Object.runSpawnCommand (C:\Users\user\AppData\Roaming\npm\node_modules\io                                                            nic\node_modules\ionic-app-lib\lib\start.js:56:17)
>     at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-a                                                            pp-lib\lib\start.js:104:20
>     at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_mod                                                            ules\q\q.js:787:54)
>     at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules                                                            \ionic\node_modules\q\q.js:816:30)
>     at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_m                                                            odules\ionic\node_modules\q\q.js:749:13)
>     at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:                                                            557:44
> 

And also I am not getting ionic.config.json in myApp created from the above command.

**Expected behavior:**
The application should be created as mentioned in the ionic documentation and should create ionic.config.json as well.

**Other information:**

Asked it on SO as well. Heres the link:http://stackoverflow.com/questions/41655282/couldnt-find-ionic-config-json-file-are-you-in-an-ionic-project?noredirect=1#comment70648818_41655282

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please update your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

Cordova CLI: undefined
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
OS: Windows 7
Node Version: v4.4.5

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1864
