### ISSUE TITLE
Navbar title overlapping buttons on Android 4.4

### ISSUE THREAD

**Issue by bostondv** [driftyco/ionic#1009]
The attached image shows how the navbar title overlaps buttons instead of truncating to the available space.

I am only experiencing this problem in a Cordova build on Android 4.4 Nexus 5. The same code was tested and working on iOS, Chrome, Firefox or Galaxy S4 with Android 4.3.

Running Ionic 1.0.0-beta1

![2014-04-01 18 49 11](https://cloud.githubusercontent.com/assets/133814/2583264/0b1986b4-b9cf-11e3-9d5c-3b0a1654458e.png)

```
<ion-side-menus>
      <!-- Center content -->
      <ion-side-menu-content>
        <ion-nav-bar class="bar-positive slide-left-right">
          <ion-nav-back-button class="button-icon ion-arrow-left-c" ng-click="goBack()"></ion-nav-back-button>
          <ion-nav-buttons side="right" ng-if="sideMenuEnabled()">
            <button ng-click="toggleRightMenu()" class="button button-icon icon ion-navicon"></button>
          </ion-nav-buttons>
        </ion-nav-bar>

        <ion-nav-view animation="slide-left-right"></ion-nav-view>

      </ion-side-menu-content>

      <!-- Right menu -->
      <ion-side-menu side="right" is-enabled="sideMenuEnabled()">
        ...
      </ion-side-menu>
    </ion-side-menus>
```

**Comment by ituhin** [comment]
@ajoslin I am facing this in android 4.4.4, works fine in browser and in ios
is this bug back ?

**Comment by mhartington** [comment]
@ituhin please provide a codepen demo

**Comment by ituhin** [comment]
@mhartington ok now its not happening anymore. But i have seen it couple of times. let me see if I can replicate.

**Comment by mhartington** [comment]
Please test against 1.1 or the nightly builds.

**Comment by kreck** [comment]
it is still not working in 1.1 ... i temporarily fixed it using "limitTo", but it is not really a nice solution

**Comment by teamsynced** [comment]
Happening to me as well. @kreck What is the limitTo you are referring to?

More information in my circumstance:
It only happens on the initial first page render, and if you switch pages and switch back it displays properly. Also displays properly with the same syntax on different pages.
