### ISSUE TITLE
Alert crashes after calling `.present()` for second time (Loading too)

### ISSUE THREAD

**Issue by mestremuten** [driftyco/ionic#10090]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Alert dialog crashes when reusing it and trying to show (present) it for second time.
_**Edit**: Same happens with Loading_

**Expected behavior:**
Alert dialogs should be able to be reused (present & dismiss) indefinitely
_**Edit**: Same should happen with Loading_

**Steps to reproduce:**
http://plnkr.co/edit/JO9ORLc62wUmJN5dSiPW?p=preview

**Related code:**

**Other information:**
Maybe it is a bug in ViewController, as I see both classes extends it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
This is actually the expected behavior, ViewController can't be reused.
However I am working an error handling so the app does not crash.

**Comment by mestremuten** [comment]
That was my thought when I saw Loading was also behaving the same. I'll have to get used to this. My apologies. 
Catching this error would be nice.

**Comment by barocsi** [comment]
So then how should we dismiss the alert popup, when and where is it in the docs?

**Comment by mestremuten** [comment]
@barocsi I think you have an example [https://ionicframework.com/docs/v2/api/components/alert/AlertController/](in the AlertController documentation), around half the page, just before Sass Variables list.

**Comment by barocsi** [comment]
Thanks for the ref, however the issue is this https://github.com/driftyco/ionic/issues/10266
