### ISSUE TITLE
Ionic 2 RC5 - Device Ready -Takes like 16 sec

### ISSUE THREAD

**Issue by raparlasiva** [driftyco/ionic#10105]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Expected behavior:**

Device READY  should be FIRED within 5 secs

**Current behavior:**

A brand new ionic app RC 5 would take close to 8 sec to bootup. If u add fontawesome and our styles then the app boot time is around 16 secs. Tried both adding, removing plugins, adding and removing platforms..no use..the app takes like 16 sec to bootup.
Device READY FIRED AFTER 16549 ms

<img width="1205" alt="screen shot 2017-01-19 at 8 11 18 pm" src="https://cloud.githubusercontent.com/assets/5502530/22132020/66fc4088-de85-11e6-8a89-9d777de82008.png">

**Comment by bolivir** [comment]
Did you try to run it with the --prod command?

**Comment by mhartington** [comment]
This is related to build, and not running build with `--prod`, which was introduced in 0.0.47 of app-scripts.

https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md#0047-2016-12-12

**Comment by raparlasiva** [comment]
That fixed it. Thank you.

**Comment by joaozig** [comment]
--prod works for me too!
