### ISSUE TITLE
Can't copy from Error

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#10102]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm running Ionic Serve, and an error is shown. Cool. But when I try to copy and paste from the screen, my selection is dismissed automatically after a half second or so. I took a quick look in devtools and it appears as if there *may* be some styling messing with user selection,b ut CSS isn't really my area.

**Expected behavior:**
I need to be able to copy from this screen to look up possible solutions.

**Other information:**

Windows, Chrome

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Not seeing this with my test. Just left this one for 5mins and the text is still selected
