### ISSUE TITLE
scss css url path not updated on minification to reflect nesting

### ISSUE THREAD

**Issue by vinpez** [driftyco/ionic#10103]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When the scss is minified, relative paths to images are not updated to reflect the new build path. For example if one of the css files is in /pages/login and the background-image: is "../../assets/img/picture-name.jpg", when it minifies it will still have that same path even though the minified file is one level more shallow.

**Expected behavior:**
The minified css file should update that relative path depending on how nested the css file is. For example: "../assets/img/picture-name.jpg"

**Steps to reproduce:**
We are able to replicate with ionic upload

**Related code:**

```
background-image: "../../assets/img/picture-name.jpg";
```

**Other information:**

We can get around this bug by assigning the image path to a variable in the theme/variables.scss file which is one level more shallow:
```$img-bkg: url("../img/background.jpg");```
then calling it on the file associated with the page /pages/login/login.scss:
```background-image: $img-bkg;```

Maybe we're not following best practices for css (not sure what they are really) but either way I think we won't be the only ones to organize our css files this way. (a main one, one for each page, and styles that will always be associated with each component on the component level)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
In this case, paths should take the final build location in to consideration. 
I'm open for adding some to app-scripts that would correct this,  possibly some post-css processor. Would you mind opening an issue on the app-scripts repo and link to this?

**Comment by vinpez** [comment]
https://github.com/driftyco/ionic-app-scripts/issues/674
