### ISSUE TITLE
Discussion on StatusBar.overlaysWebView

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic#10109]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The statusbar overlays the webview by default on iOS. This means that if your app is designed so that different pages have different coloured headerbars, the statusbar text might not fit the background very well.

I'm wondering what the reasoning behind this is, and whether it should actually be disabled by default, to mirror how Android works.

**Expected behavior:**

Don't overlay the webview by default?

Alternatively, please document how to disable this behaviour (see below for steps required).

**Steps to reproduce:**

```
ionic start --v2 MyApp blank
ionic platform add ios
ionic emulate ios
```

**Other information:**

In order to stop the statusbar overlaying the webview you need to do two things:

1. In your app.component.ts, add some code to prevent the statusbar from being overlayed (I prefer doing this here rather than in config.xml, so that the desired effect occurs in Ionic View as well as the real app):

```
this.platform.ready().then(() => {
  StatusBar.overlaysWebView(false);
  StatusBar.styleDefault();
});
```

2. When bootstrapping your app, ensure `statusbarPadding` is set to `false`:

```
IonicModule.forRoot(AppComponent, {
  statusbarPadding: false
})
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by mhartington** [comment]
This is set by default because this is how native IOS behaves. 
Referencing the ios design guidelines, the statusbar should overlay the view and integrate with an apps design, indicating either a dark style (dark text) or light style (light text). 

If you'd like to change the default ios behavior, how you're setting it in your sample code would work fine.

**Comment by fiznool** [comment]
Thanks for getting back to me, that makes sense.

Could I suggest the code samples are added somewhere in the docs? It took a lot of time to figure out that both of these changes were needed.
