### ISSUE TITLE
My ionic 2 tab template  www folder is empty...

### ISSUE THREAD

**Issue by jackryu** [driftyco/ionic#10117]
Hello Team,

I am new with ionic based mobile application development .

> I am try everything  but my ionic 2 application tab template WWW folder is   empty and ionic 1 is working.

 ionic start --v2 myApp tabs (this Command is create blank www folder)
 ionic start  myApp tabs (and this command is working fine)

but i need to working with ionic 2 

**_# Already try below things are not working _** 

1. all dependency install again after uninstalling. 
2. cordova and ionic install one by one 
3. update node version and degrade node version.
4. degrade  cordova  version 4.2.2
5. add sudo in every command

# ----Configuration----- 

**OS**  
Windows 10

**GIT** 
git version 2.9.2.windows.1

**IONIC** 
2.2.1
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
2.2.1

**NODE** 
v6.9.4

**CORDOVA**
You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Regard's
Abhishek Tomar
email : abhi.tomar@live.com

**Comment by chrisgriffith** [comment]
Yes, that is the correct behavior for an Ionic 2 app until you build the app using the ionic build <platform> command. If you use ionic serve command, the www folder will be populated as well.

**Comment by jackryu** [comment]
but i am running my server but this is not working -

**Comment by chrisgriffith** [comment]
But did you run either ionic build or ionic serve? The new ionic app scripts will take the contents of the src directory and then generate the contents of the www directory.

If nothing is being generated, then review the terminal logs to see if there is an error during the build.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#673
