### ISSUE TITLE
Unable to get content dimensions

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#10113]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Content height or width returns 0.
![image](https://cloud.githubusercontent.com/assets/5492960/22154031/1d94c85c-df2a-11e6-87f2-a02d62cdf0a0.png)

**Expected behavior:**
Get integers values for both of them.

**Steps to reproduce:**
http://plnkr.co/edit/BsFOqg8PvxTonnmTKnsw?p=preview

**Related code:**
Check the plnkr.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
Seem to be due to the view event that you are using. 
ionViewDidLoad fires before the DOM is ready, so the content has not been sized yet.

Switching to ionViewDidEnter makes sure that all the DOM is ready and has readable sizes.

http://plnkr.co/edit/azTN70MxDYAlnzlNNglD?p=info

**Comment by ZiFFeL1992** [comment]
Thanks @mhartington
