### ISSUE TITLE
Unable to run multiple instances of livereload simultaneously

### ISSUE THREAD

**Issue by sarahsga** [driftyco/ionic#10114]
**Ionic version:**
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
unable to simultaneously run livereload on ios, android and browser. 

**Expected behavior:**
expected to simultaneously be able to run livereload on ios, android and browser, to be able to test on multiple platforms simultaneously. This worked flawlessly with ionic 1.x

**Steps to reproduce:**
Step 1: ionic run ios -l -c --device
This will run livereload on ios device connected to the machine.

Step 2: ionic run android -l -c
This will give an error 
```
Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```
This happens because the address "192.168.8.102" is already in use by livereload running on ios. I have tried changing port (--port), livereload-port (--livereload-port), nothing's working.

**Other information:**
I was able to run multiple instances of livereload on one address "192.168.8.102" simultaneously while developing ionic 1.x applications
This issue https://github.com/driftyco/ionic/issues/9425 addresses this problem, but it does not address how to run multiple livereload instances simultaneously.

**Ionic info:**

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1866
