### ISSUE TITLE
Allow ios & android icons

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10127]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
iOS and android use the same icons

**Expected behavior:**
to have the ability to specify an ios icon, and android icon

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
Just use:
```
<ion-icon name="ios-ICONNAME"></ion-icon>
<ion-icon name="md-ICONNAME"></ion-icon>
```

**Comment by AmitMY** [comment]
My apologies. I meant application icons.
Currently you can have `icon.png`, and it will generate ios and android icons, which are the same.

**Comment by ghenry22** [comment]
Put your android source files under resources/android and your iOS source files under resources/iOS.  If you want the same sour files used for both put the source files directly under /resources.

**Comment by AmitMY** [comment]
@ghenry22 Thanks! I was not aware of this!
