### ISSUE TITLE
Feature request: Swiper RC5 - initialize Swiper instance with options in ts?

### ISSUE THREAD

**Issue by DeeM297** [driftyco/ionic#10128]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
Before RC5, I used to have `mySlideOptions` variable and used it to initialise the swiper in the HTML file like this:
`<ion-slides [options]="mySlideOptions">`

**Requested behavior:**
Now `[options]` has been removed. Is there a way to initialise the Swiper instance in the TS file and then used it in HTML?

As it is shown on this link: https://github.com/nolimits4web/Swiper/blob/master/demos/04-space-between.html
Swiper instance is initialized in the js part and then used in html. This would allow us to instantiate Swiper and configure it with some options.
```
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 30,
    });
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Take a look at the `Advanced` section (on the nightly docs) for Slides: http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced

Is this what you're looking for? :smile:

**Comment by DeeM297** [comment]
That's perfect. It's working again. Thanks Brandy =)
