### ISSUE TITLE
how to reduce loading delay in ionic app 

### ISSUE THREAD

**Issue by sharathbonagiri** [driftyco/ionic#10123]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
