### ISSUE TITLE
ion-segment share scroll

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#10130]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have ion-segment having 2 segments. Each segment has a list of items. If I scroll one list, it scrolls other as well. Currently, I'm using `this.content.scrollToTop();` in segment `ionChange` but it's visible that list is scrolling to top on segment change.

**Expected behavior:**
Segment shouldn't share scroll. Scrolling one segment shouldn't affect other. Each segment should remember it's scrolled position.

**Steps to reproduce:**

**Related code:**

```
Use conference app.
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8T61a
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue for now as ion-segment is meant to share the same scroll. You can use tabs to get the behavior you are looking for. Thanks!
