### ISSUE TITLE
Rename Ionic modules to one style

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic#10133]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

All Ionic modules have different nomenclature. Framework is ionic-angular, while Cloud and Storage are @ionic/storage or @ionic/cloud.

**Expected behavior:**

Give all Ionic packages the same naming style, so @ionic/framework, @ionic/cloud, etc.

**Related code:**

```
import { NavController } from '@ionic/framework';
import { User, Auth } from '@ionic/cloud'; (it would also be great if it were just cloud, and rename Angular 1 Ionic cloud as @ionic/cloud-base or something)
import { Storage } from '@ionic/storage';
import { Network } from '@ionic/native';
```
See how pretty that looks?

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! While we would love to do this, we have discussed it internally and because it has been `ionic-angular` for so long and because we would lose our stats if we changed the name, we decided against it.

**Comment by patrickmcd** [comment]
I think you should favor consistency and coherence over stats. Renaming could limit confusion down the road. 2.0 going final presents a good time, and offers a good excuse, to make the change.

**Comment by wbhob** [comment]
Like angular went to @angular/{something}

**Comment by wbhob** [comment]
@jgw96 is this something you might consider for Ionic 3? It would help organize better for people on 3.x, and separate statistics of usage of 2.x and 3.x.
