### ISSUE TITLE
Ionic 2 page instances not destroyed on back

### ISSUE THREAD

**Issue by samarthagarwal** [driftyco/ionic#10134]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have created two pages, page1 and page2, page2 being connected to a server via socket.io. Everything works fine unless I go back from page2 to page1 and come back to page2. All the messages are received twice by page2. If I go back again to page1 and come to page2 again, it will start receiving the messages three times and so on. It looks like when we go back, the page is not destroyed. It is alive somewhere in the cache/memory and is still active. Everytime we go back and forth, a new copy is created.

**Expected behavior:**

When we go back and forth from page1 to page2 to page1 to page2, the messages should be received only once. The previous instances of page2 should destroyed on navigating backwards. 

**Steps to reproduce:**

**Related code:**
Code for page2 constructor
```
this.socket.on('Message', (data) => {
      
      if((this.socket.id == data.from && this.partnerId == data.for) || (this.socket.id == data.for && this.partnerId == data.from)){
          this.messages.push(data);
      } 
      
      if((this.partnerId != data.from) && (this.socket.id != data.from)) {
        //code to show notification
      }

    })
```
Code for page1 constructor
```
this.navCtrl.push(HomePage, {"partnerId": partnerId, "socket": this.socket });
```

**Other information:**

**Ionic info:** 

```
Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by samarthagarwal** [comment]
I feel this has something to do with [this](https://github.com/driftyco/ionic/issues/5960) issue.

**Comment by Mjf94** [comment]
Same problem here.
I enter page B by clicking button on page A and go back to page A by clicking back button. Then I click the button on page A and enter page B again. Now according to Augury the app stack is Page A->Page B->Page A->Page B. And ionViewWillUnload() is never called.


Ionic info:

> Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2

**Comment by Mjf94** [comment]
Seems to be the problem with RC5. I tested my code on RC4 and it works as expected.

**Comment by 64jcl** [comment]
Are you sure the GC gets to collect your page? If you have some callback registered in a service, perhaps that's keeping the objects/page in memory? But if its still stuck in the navstack there is surely something wrong.

**Comment by samarthagarwal** [comment]
Hi @64jcl , I am using Socket.io and I have events registered. Is it possible that the registered events are not letting the page die?

**Comment by samarthagarwal** [comment]
Looks like unsubscribing to the events did the trick. Thanks @64jcl .

**Comment by 64jcl** [comment]
Great! :) - I also had a feeling this was happening in our project too. I had "events.subscribe" in many of my pages and some of my services did "events.publish" and just to be sure I added a console.log in the handlers to see if they were automatically unsubscribed or not when page got destroyed. Obviously they were not as the events object has no idea about what page you are calling events.subscribe from. So I now consistently add "events.unsubscribe" in my "ionViewWillUnload()" callbacks.
