### ISSUE TITLE
Limit Don´t Work in Ionic 2

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic#10137]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

Limit don´t work in Ionic2

{{event?.descricao |limit 50}}
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by ghenry22** [comment]
Angular2 does not have a build in pipe available for this, see http://voidcanvas.com/angular-2-pipes-filters/ for a list of the available pipes in Angular2 and a description of the changes from angular1 to angular2.

You could write one yourself following the information on that link if this is something you need and the best way to achieve the goal.

This isn't an ionic bug though and should probably be closed.

**Comment by brandyscarney** [comment]
Thanks for the issue! As @ghenry22 stated, this pipe doesn't exist in Angular 2, see: https://angular.io/docs/ts/latest/api/#!?apiFilter=pipe&query=pipe

There are some answers on StackOverflow of people implementing this: http://stackoverflow.com/questions/40028456/angular2-limitto-pipe-not-working

Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) if you have more questions about the framework. :smile:
