### ISSUE TITLE
"ionic run android" Does not work on Ionic 2 rc5 

### ISSUE THREAD

**Issue by AndersonBP** [driftyco/ionic#10144]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Commands ionic run android and ionic build android do not work after upgrade to rc5. But command ionic serve works normally.

**Expected behavior:**
Anderson Benevides@Anderson MINGW64 —/Documents

$ ionic run android 
Running 'run:before' npm script before run 
> ionic-hello-world@ build C:\Users\Anderson Benevides
> ionic-app-scripts build

[00:36:30] ionic-app-scripts 1.0.0
[00:36:30] build dev started
[00:36:30] clean started
[00:36:30] clean finished in 28 ms
[00:36:30] copy started
[00:36:30] transpile started
[00:36:58] transpile finished in 27.90 s
[00:36:58] webpack started
[00:36:59] copy finished in 29.38 s
[00:37:15] webpack finished in 17.65 s 
[00:37:15] sass started [00:37:21] sass finished in 6.21 s
[00:37:21] build dev finished in 51.86 s

Anderson Benevides@Anderson MINGW64 —/Documenta/$ I 

*When you get to "[00:37:21] build dev finished in 51.86 s" to run the command and the build or run task is not executed*

```
ionic info
Cordova CLI: 4.3.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

**Comment by flabioassuncao** [comment]
Same problem with me

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#677
