### ISSUE TITLE
Setting BaseUrl in tsconfig.json

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#10142]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

I am trying to set BaseUrl to './src' in tsconfig.json. Though it works well with typescript, it is not working and breaking the app on `ionic serve`

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#678
