### ISSUE TITLE
disabled inputs with a formControlName are still focusable

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#10155]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On this e2e http://localhost:8000/dist/e2e/input/form-inputs/ if you tap a disabled input the input will act like it is focused (will cause the page to scroll) even though its disabled. The reason for this is that when disabling with angular forms the `ion-input` does not get the disabled attribute so our css which targets using the disabled attribute does not get applied.

**Steps to reproduce:**

* Open this e2e on a device: http://localhost:8000/dist/e2e/input/form-inputs/
* tap a disabled input

**Comment by brandyscarney** [comment]
I think the solution to this should be adding a class to the `ion-input`:

```
  set disabled(val: boolean) {
    this.setDisabled(this._disabled = isTrueProperty(val));
    this.setElementClass('text-input-disabled', this._disabled);
  }
```

cc @adamdbradley

**Comment by brandyscarney** [comment]
Note to self: pass `disabled` attribute to `ion-input` as well.
