### ISSUE TITLE
Incorrect progress position - Range component

### ISSUE THREAD

**Issue by NeoLSN** [driftyco/ionic#10150]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If the range is small then
![image](https://cloud.githubusercontent.com/assets/5782106/22237762/cdceb93c-e248-11e6-8202-6c8c73a7f9bc.png)
or
![image](https://cloud.githubusercontent.com/assets/5782106/22238329/c90503e0-e24b-11e6-8c68-3cc24a26703b.png)

**Expected behavior:**
The progress should be followed with knob

**Related code:**
```
<ion-range min="0" max="5" debounce="500"...>
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
I'm unable to reproduce in my test. Can you provide a more complete example? A plunkr that reproduces the issue will help to. There is link in the original issue template that you should provide.

**Comment by NeoLSN** [comment]
Here's the example.
http://plnkr.co/edit/TpKsGXCkPCOoSplT9lmY?p=preview

```html
<ion-range min="0" max="5" debounce="500"
        [(ngModel)]="fanSpeed" id="fan-speed" mode="ios" (ionChange)="adjustFanSpeed()">
  </ion-range>
```

**Comment by brandyscarney** [comment]
Thanks for the plunker! This is probably related to: https://github.com/driftyco/ionic/issues/6812
