### ISSUE TITLE
Ionic 2 - ion-select support modal interface as well

### ISSUE THREAD

**Issue by raparlasiva** [driftyco/ionic#10159]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic 2 select only supports alert and action sheet interfaces . 

**Expected behavior:**
ionic 2 select should also support modal interface as well.

**Other information:**
For now any workarounds to have ionic 2 open a modal window and options are displayed in a list item with a search bar on top of the list.

**Comment by wbhob** [comment]
You can do this by making the button open a modal, and when the modal closes, send data back and use the onClose() method (or something like that).

**Comment by raparlasiva** [comment]
In the past i did something like that..but the requirement needs to have a look and feel of a select element (like the ionic-select).. so kind of stuck there..

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#91
