### ISSUE TITLE
how to exit app?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#10151]
witch api function should I use?

**Comment by vintage** [comment]
What do you mean? You don't need to add close app functionality, as users on all mobile platforms know exactly how to do this using their OS.

http://ux.stackexchange.com/questions/7502/why-dont-mobile-apps-have-a-close-button

**Comment by graphefruit** [comment]
navigator.app.exitApp as JavaScript call

**Comment by yozman** [comment]
@graphefruit 
is there any ionic way?

**Comment by graphefruit** [comment]
https://forum.ionicframework.com/t/how-to-close-application-using-button-ionic-2/48050/5
```
exitApp(){
     this.platform.exitApp();
  }
```

**Comment by dylanvdmerwe** [comment]
Terrible idea to close an app. Also this is not an issue and should be further discussed in the forums.

**Comment by graphefruit** [comment]
@dylanvdmerwe Sorry but why should it be an terrible idea?
Many android-apps supports the feature to close the app when pressing back on the "RootPage".
Some asks to press again within X-Seconds, other asks the users, and some just closes the app.

Its your UX-Design which handles this case.

**Comment by dylanvdmerwe** [comment]
@graphefruit it's just bad mobile UX. It goes against Apple's guidelines. And Android has both a back and home button for the user to press - no need for an exit interaction. 

As @vintage posted above, read this thread: http://ux.stackexchange.com/questions/7502/why-dont-mobile-apps-have-a-close-button

Still not an ionic issue.

**Comment by mhartington** [comment]
Closing. This is not an ionic issue. 
As the issue template states, if you have question, please use the ionic forum or the slack group.
