### ISSUE TITLE
Ionic 2 - <ion-input type = "number"> doesn't show numeric only keypad.

### ISSUE THREAD

**Issue by neelancherivishnu** [driftyco/ionic#10161]
In my app's login page , I use <ion-input type = "number"> for entering phone number. But in android device (Samsung S6) it doesn't show numberic keypad. Usual keypad is showing. How I can solve it?
**Ionic version:**  (check one with "x")
[ ] **2.x**

**Comment by dylanvdmerwe** [comment]
Does the keyboard on the Samsung device actually have a numeric only keyboard? Have you seen it do this (for example on the contacts app)? Sometimes the numeric keyboard just adds a row of numbers to the top of the keyboard.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by neelancherivishnu** [comment]
@dylanvdmerwe , yes. Samsung device have a numeric only keyboard.

**Comment by neelancherivishnu** [comment]
@dylanvdmerwe,  @jgw96 
<ion-list>

    <form [formGroup]="loginForm">
      <ion-item  >
        <ion-label floating>Phone number</ion-label>
        <ion-input type="number" formControlName="uname" [(ngModel)]='username' maxlength="10" ></ion-input>
      </ion-item> 

      <ion-item>
        <ion-label floating>Password</ion-label>
        <ion-input type="password" formControlName="pword" [(ngModel)] = "password"></ion-input>
      </ion-item>
      <ion-item>
        <button ion-button block color="bluedevider" [disabled] = "!loginForm.valid" (click)='login()'>Submit</button>
      </ion-item>
    </form>
  </ion-list> 

this is my code

**Comment by neelancherivishnu** [comment]
`<ion-list>

    <form [formGroup]="loginForm">
      <ion-item  >
        <ion-label floating>Phone number</ion-label>
        <ion-input type="number" formControlName="uname" [(ngModel)]='username' maxlength="10" ></ion-input>
      </ion-item> 

      <ion-item>
        <ion-label floating>Password</ion-label>
        <ion-input type="password" formControlName="pword" [(ngModel)] = "password"></ion-input>
      </ion-item>
      <ion-item>
        <button ion-button block color="bluedevider" [disabled] = "!loginForm.valid" (click)='login()'>Submit</button>
      </ion-item>
    </form>
  </ion-list>`

**Comment by narayana1240** [comment]
i am trying to disable dot('.') in numeric keypad in ionic 2 but i didn't got a proper way to handle this situation ,is any one having even idea also appreciated,i am struggling with this issue from past one week,my client is rushing for it ......many thanks in advance 
![keybord](https://user-images.githubusercontent.com/22906946/28467215-c39ba674-6e4c-11e7-8a12-596063d38600.png)

**Comment by narayana1240** [comment]
is it possible to made go button for text control to move focus to next control of any type in ionic2 application please help me to get out from this situation,it is working fine with numeric key pad and text control to text control but the next one is other then text it is not working any sample code /idea/opinion were appreciable ...thank in advance

**Comment by PRINCEHR** [comment]
ion-input  type="tel"

**Comment by oddcb** [comment]
Try `type="number" pattern="[0-9]*"` to disable the dot. Works on iOS 9/10 and for Android on apps using the Chrome Webview (i.e. Android 5+)

**Comment by nandJaypore** [comment]
@oddcb  not working

**Comment by mrmgomes** [comment]
@oddcb works perfectly! I was using `type="tel"` because `type="number"` was way worse since it showed the whole alphabet keys. 

But combining it with `pattern="[0-9]*"` did the trick. Thanks!

**Comment by manikandan07081995** [comment]
But android mobile allow other special character keys.@mrmgomes your tricks won't work.Tell me other way to achieve only number [0-9]

**Comment by wuilliam321** [comment]
I am having the same issue. I prevent dot `.` and dash `-` from keyboard, and it works. The input is not recognized and do not return the value of the `keypress` event. BUT! The dot and the dash are written in the input. No matter what validation i set.

**Comment by oddcb** [comment]
For troubleshooting you can test different patterns in browser here: http://inputtypes.com/
On Android from 5 and forward Ionic should use the built in Chrome webview which hopefully (more or less) corresponds to the Chrome version you have installed on the phone.

**Comment by rangholiyanikunj** [comment]
this cordova plugin are use 

    mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"


Code 

       <ion-fab left bottom>
        <a href="tel:number" class="button" ion-fab color="light">
            <ion-icon name="keypad"></ion-icon>
        </a>
    </ion-fab>

**Comment by manikandan07081995** [comment]
Keyboard not open in kiosk mode some one help me.

**Comment by Hanzofm** [comment]
`pattern="\\d*"`

**Comment by PeiJueChen** [comment]
// my code
 <ion-input [(ngModel)]="phone" (keypress)="codeInput($event)" type="tel"></ion-input>

  codeInput(event) {
    //48 - 57
    let pass = /[4][8-9]{1}/.test(event.charCode) || /[5][0-7]{1}/.test(event.charCode);
    if (!pass) {
      return false;
    }
  }
