### ISSUE TITLE
Slides: autoplayDisableOnInteraction not working

### ISSUE THREAD

**Issue by mebibou** [driftyco/ionic#10163]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After swiping on the slides, it changes the slide but then the autoplay doesn't work anymore.

**Expected behavior:**
It should keep on autoplaying after swiping and waiting the autoplay time

**Steps to reproduce:**
Create slides into the content of the page, with `autoplay` and `autoplayDisableOnInteraction`

**Related code:**

```html
  <ion-slides [autoplay]="2000" [speed]="500" [loop]="true" autoplayDisableOnInteraction="false" pager>
    <ion-slide *ngFor="let image of images">
      <img [src]="image" />
    </ion-slide>
  </ion-slides>
```

**Other information:**
I've looked at other issues about the slides but none are reporting a bug about this property specifically.

Although this property does not appear on the documentation, it is still in the code.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will take a look at this.

**Comment by stefanhuber** [comment]
This cannot be changes anymore: https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L394

**Comment by stefanhuber** [comment]
```
    @ViewChild(Slides) slides: Slides;
    
    ionViewDidEnter() {
        this.slides.autoplayDisableOnInteraction = false;
    }
```

Adding this to the @Component which includes the ion-slides has allowed me to change the option.

**Comment by mebibou** [comment]
@stefanhuber thanks it works!
