### ISSUE TITLE
feat: SPA need route lazy load

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#10165]
could you plz add lazy load and chunk for routes at deeplink?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are working on code splitting based on routes as we speak. You can expect to see this feature post 2.0 stable.

**Comment by yozman** [comment]
![image](https://cloud.githubusercontent.com/assets/11918866/22323138/a0624dc6-e3db-11e6-8979-6327288c089c.png)

@jgw96 
I already update newest 2.0 stable.
but nothing changed

**Comment by yozman** [comment]
![qq 20170403150155](https://cloud.githubusercontent.com/assets/11918866/24598590/bd916bd4-187e-11e7-87ee-ec8c8b62974d.png)


everybody can check this repo
https://github.com/fundo90/ionic2-starter-mobile/tree/b53023d99e78e7b2b56ff4345555656b2de743b7
