### ISSUE TITLE
Latest release - 2.0.0 Native  plugin Network.connection does not exists

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#10177]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hello,
I have just upgraded my project with latest release, 2.0.0 and it breaks my existing code ..

```
Network.connection !== "none"
```
I am assuming I should replace this line with ...
```
Network.type !== "none"
```
Let me confirm please

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1005
