### ISSUE TITLE
feat: Use socket.io plugin as both server and client app

### ISSUE THREAD

**Issue by judeallblack** [driftyco/ionic#10175]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>i simply want to enable device to device communication using sockets.

the server socket and client socket should run on mobile phones so that the two communicate without going to an online server</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
