### ISSUE TITLE
ionic 2 FileEntry linting doesn't follow specification and device behavior

### ISSUE THREAD

**Issue by philem35** [driftyco/ionic#10181]
**Ionic version:** 
[ X] **2.0.0**

**I'm submitting a bug report

**Current behavior:**
FileEntry doesn't respect specification
https://cordova.apache.org/docs/en/2.4.0/cordova/file/fileentry/fileentry.html

file.size and file.type are not supported by lint checking 
Properties are available when running on device.

**Expected behavior:**
lint shouldn't raise blocking error when accessing file.type and file.size

**Related code:**
```
                    fileEntry.file(file=> {
                    // on device, file contains mimetype and file size
                      console.log('file content', file);
// those lines trigger
 console.log('file content', file.size);
 console.log('file content', file.type);
                    }, ((error:FileError) => console.log(error)));
```

**Comment by mhartington** [comment]
In this case, it is because Typescript does not know about file or it's valid type information. Use Ionic native instead.

http://ionicframework.com/docs/v2/native/file/

**Comment by philem35** [comment]
Hi mhartington, 
thanks for your answer, even Iif don't get it :) : 

I'm trying to use Native file API to get file size and file type, the sequence is : 

 FileChooser.open()
        .then(**uri** => .... 

FilePath.resolveNativePath(uri).then(nativeUrl ..... 
let path:string = nativeUrl.substring(0, natifUrl.lastIndexOf('/'));
let fileName:string = nativeUrl.substring(natifUrl.lastIndexOf('/') + 1, nativeUrl.length );

File.resolveDirectoryUrl(path) 
                .then(directoryEntry=> ... 

 File.getFile(directoryEntry, fileName, {} ) // readAsText
                    .then(fileEntry => { .... 

I do get a fileEntry - in order to get file information(type, size), what should I do using native/file ?

**Comment by mhartington** [comment]
Let move this to the forum, as this is a more general question than actual issue.
