### ISSUE TITLE
The m4a audio is too slow starting the playback

### ISSUE THREAD

**Issue by Alexgulyy** [driftyco/ionic#10185]
**Ionic version:** **2.2.1**

We have problems with an audio reader hybrid application, using fairly large audio m4a files. In short, it takes far too long to start the playback (when using online audio resources).
To illustrate the issue, we've created a smaller prototype [https://github.com/Alexgulyy/test-ionic-audio-app/tree/master/src/pages/home](url)

When we build the app with Ionic 2.2.1 using WebView, it starts playback in ~3.5s. The network activity looks like this:
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=webview HTTP/1.1   206 29522945`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=webview HTTP/1.1   206 326657`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=webview HTTP/1.1   206 29163520`

When we build the app with Ionic 2.2.1 with Crosswalk-webview plugin 2.2.0, it starts playback in 18s at best, but sometimes the delay is even more substantial - up to 45s. It seems the main reason is the difference in the network activity:
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 2`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 200 29522945`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 577690`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 200 29522945` 
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 577690`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 200 29522945` 
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 577690`
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 200 29522945` 
`GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 577690`
` GET /tmp/1916firstchapterscollection_09_various_64kb.m4a?app=crosswalk HTTP/1.1 206 7384995`

... when only the first request is served with the 'normal' user-agent, all the subsequent ones are served with stagefright/1.2 (Linux;Android 5.0.1).
Why's the difference, and how can we avoid this?

**Comment by mhartington** [comment]
This is not an issue related to the ionic framework. 
Also, there is an issue template for a reason, do not delete it.

Closing.
