### ISSUE TITLE
bug: Cannot read property 'ev' of null

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#10186]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I upgraded a project from RC4 to 2.0.0. When running the project, I get shown the following error:

![image](https://cloud.githubusercontent.com/assets/2852839/22337102/d6d01af8-e3ec-11e6-9b8a-f042c1076c7e.png)

Note that if this error is dismissed, the application continues to function as normal. 

**Expected behavior:**
Error to be fixed.

**Other information:**
As discussed with @manucorporat:

```
so
https://github.com/driftyco/ionic/blob/3a718de4632427cdf1a44e066bb559a6c28c6733/src/components/content/content.ts#L620
this function is called after the content has been destroyed
it is huge complicated function
we could fix it by doing:
if(!this.scroll) return; 
but it is a bad fix, since it does not fix the root of the cause
that function should not be called a tall
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by dylanvdmerwe** [comment]
Actually a bit more critical than I thought. 

In chrome through `ionic serve` if you dismiss the error, the app continues normally. 

When on a device (or serving in Safari), an empty screen just shows.

**Comment by dylanvdmerwe** [comment]
In `ionViewDidLoad` of the rootPage, I was setting a variable that hide the `ion-menu`. 

`<ion-menu *ngIf="showMenu"`

Moving the logic to `ionViewWillEnter` fixes this. But this is still a workaround as the code worked fine in RC4.

**Comment by m00g33k** [comment]
I encountered this problem in a modal view. I had the same problems with ionViewDidLoad getting navParams. Putting it inro ionViewWillEnter solved the problem but the scroll is still messed up. I moved it to constructor and worked perfectly. Please submit this as a bug report. Thanks

**Comment by m00g33k** [comment]
I encountered this problem in a modal view. I had the same problems with ionViewDidLoad getting navParams. Putting it inro ionViewWillEnter solved the problem but the scroll is still messed up. I moved it to constructor and worked perfectly. Please submit this as a bug report. Thanks

**Comment by brandyscarney** [comment]
A fix for this will be in the next release. Can you please try out the following nightly and let me know if you find any issues:

```
npm install --save --save-exact ionic-angular@2.0.0-201701301819
```

Thanks!

**Comment by chanoch** [comment]
Brandy's fix worked for me.

**Comment by leonardopaiva** [comment]
thanks, i checked the line where says the error log, it leads to content.js core file, the error ocurr because content._scroll = null, so i checked it first before using on my component

// prevents ev of null error
 if(this.content._scroll) {
}

its working for now, but i am not sure if this is a good work around. Hope that helps someone.
