### ISSUE TITLE
Ionic 2 Feature - Highlight list item on returning from master-detail view

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#10180]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Feature request**
It would be useful if the clicked/tapped list item animated its highlight colour when returning from a master detail view.

This would give the user context of which item they had interacted with, which would be especially useful in a long list where the items look very similar.

**Comment by mhartington** [comment]
Not saying "no" but this doesn't seem to be a common pattern in apps. 
If I navigate around inside facebook/twitter, I dont get a highlighted link saying where I came from when I navigate back. It just doesn't seem like a common pattern.

**Comment by daveshirman** [comment]
It IS common when you have lists with very similar looking content, such as in the gmail app.

Select an email in gmail on Android and you'll see an animation of the item up to a header position for the detail view.

Then when you go back, it animates back down.  Subtle enough to give context.

I was suggesting a simpler, highlight animation as it should be much easier to implement, less taxing possibly?

**Comment by mhartington** [comment]
Ahh, k, I was thinking something similar to `a:visited` or along that line. Hmm more contextual animations....

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#97
