### ISSUE TITLE
Ionic 2 - ion-slides [options] are not considered

### ISSUE THREAD

**Issue by monalisasaha79** [driftyco/ionic#10199]
Hi,

I am using ionic 2 version - 2.2.1

In the view, I used ionic slides like, <ion-slides [options]="slideOptions" >
In the controller, 
constructor(public params: NavParams) {
    this.images = this.params.get('images');
    this.index = this.params.get('index');
    this.slideOptions = {
      pager: false,
      initialSlide: this.index,
      loop: true,
      zoom: true
    };
  }

None of the options are considered. Then I changed the view like, <ion-slides [initialSlide]="index" [pager]="false" [loop]="true" [effect]="coverflow">

except zoom and effect, other options are taken in effect.

Please let me know if I am missing anything or it is a defect.

Thanks,

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can read [this part of the RC5 changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#slides) to see why `options` is not supported anymore and to see the new way to handle them.
