### ISSUE TITLE
[ REOPEN ] ionic2 FAB button <ion-fab-list> should be hide when click Page #9721

### ISSUE THREAD

**Issue by rendy14s** [driftyco/ionic#10198]
Dear all..
any one to solved this ?

I Reopen issue for page #9721

i know Fab.close() thats mean to close fab WHEN i click menu. BUT if i click something alese on the screen (NOT MENU FAB) the fab not close.

thanks

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Fab does not currently have a backdrop, so it does not support this functionality. There is an open issue [here](https://github.com/driftyco/ionic/issues/8425) to implement this functionality (:

**Comment by rendy14s** [comment]
hello, jgw96

thanks for replying to my issue.

for now I've solved this issues. button to FAB can click anywhere. then FAB then closed automatically.

I just outsmarted him by putting the code:

> html:

```
<Ion-fab bottom right #fab>
......
</ Ion-fab bottom right.
```

outside of `<ion-content>`

and in .ts file I added 

> fab.close function ();

then complete her way. For example:

> HTML file:

```
<Ion-content class = "page-home" (click) = "share (fab)">

............

</ Ion-content>

<Ion-fab bottom right #fab>
    <Button ion-fab color = "# 018bc9"> <ion-icon name = "add"> </ ion-icon> </ button>
    <Ion-fab-list side = "top">
      <Button ion-fab color = "danger" (click) = "gotoPost (fab)">
                <Ion-icon name = "browsers"> </ ion-icon>
          <Ion-label> {{ 'Posting' | translate}} </ ion-label>
        </ Button>
      <Button ion-fab color = "secondary" (click) = "openMeeting (fab)">
          <Ion-icon ios = "ios-clipboard-outline" md = "md-clipboard"> </ ion-icon>
          <Ion-label> {{ 'Meeting Request' | translate}} </ ion-label>
      </ Button>
      <Button ion-fab color = "primary" [navPush] = "chatpage" (click) = "chat (fab)">
          <Ion-icon name = "chatbubbles" ios = "ios-chatbubbles" md = "md-chatbubbles"> </ ion-icon>
          <Ion-label> {{ 'Chat' | translate}} </ ion-label>
      </ Button>
    </ Ion-fab-list>
  </ Ion-fab>
```

and in

>  file.ts
> fab.close added function (). ex:

 ```
share (fab: FabContainer) {
    fab.close ();
    console.log ( "Sharing in");
  }
```



Issues may be helpful for a while can use this method.

thank you :)

**Comment by krunvaghela** [comment]
https://stackoverflow.com/a/45738683/3725226
