### ISSUE TITLE
No nested option on Slides

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic#10191]
**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  
[x] bug report

**Current behavior:**
After the Slides component was changed on Ionic RC.5, there is no more nested option on the Slides, making it impossible to have proper behavior on nested slides.

**Expected behavior:**
Expose `nested` Slides parameter.

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can read this comment for more info https://github.com/driftyco/ionic/issues/10037#issuecomment-273236835 but the basics of it is that you will need to use the component instance to set this option. You can see that [here](http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced) in the docs.

**Comment by Artfloriani** [comment]
This does not solve my issue. The nested option is not available even on the component instance.
