### ISSUE TITLE
Feature (actionsheet): Add mode selection to the actionsheet component

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#10200]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I want to be able to use the md actionsheet style in an iOS app.

add mode selector value to actionsheet component.
Optionally set as a parameter on the create call, if null then use platform/app default.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#98
