### ISSUE TITLE
feat(menu): Add more events like ionWillOpen

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#10203]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently there are three events on an `ionMenu`. 

![image](https://cloud.githubusercontent.com/assets/2852839/22364707/ffc5b276-e47b-11e6-9bc9-6d4edd825648.png)

I have a requirement where, when the user presses the menu button, that a sound is played. Currently I am doing this in the `ionOpen` event. However this will only fire after the menu animation has happened and is fully open. 

Other events would required would probably be an `ionWillClose`.

**Expected behavior:**
I need to hook into the event just before the menu begins to open. This will allow me to play a sound, or do anything else, before the menu opens. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#99
