### ISSUE TITLE
bug: ionic-native: InAppBrowser object reference lost

### ISSUE THREAD

**Issue by othon2000** [driftyco/ionic#10210]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>## not sure if it also affects iOS, couldn't verify yet

If you have an instance of InAppBrowser, say, with target=_blank, and then you create a new instance with target=_system, your original InAppBrowser reference gets lost, and the events assigned to it stop working.

```javascript
  let blankBrowser = new InAppBrowser('https://someurl.com', '_blank', 'location=no,zoom=no,hidden=no');
  blankBrowser.on('loadstart').subscribe(
    event => {
      //some behavior
    }
  );
  let systemBrowser = new InAppBrowser('https://anotherurl.com', '_system', 'location=no,zoom=no,hidden=no');
  //bang! the events assigned to blankBrowser go away, and I cannot do anything with the reference
```
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1014
