### ISSUE TITLE
ionic generate --list output seems incorrect

### ISSUE THREAD

**Issue by saschwarz** [driftyco/ionic#10227]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$ ionic generate --list
undefined
undefined 'Component'
undefined 'Directive'
undefined 'Page'
undefined 'Pipe'
undefined 'Provider'
undefined 'Tabs'

**Expected behavior:**
I'm a new user so I don't know what the 'undefined' should be replaced with.

**Steps to reproduce:**
Just enter command

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1889
