### ISSUE TITLE
Ionic Native HeaderColor plugin not working

### ISSUE THREAD

**Issue by dipolediamond** [driftyco/ionic#10225]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The HeaderColor listed in the docs [http://ionicframework.com/docs/v2/native/headerolor/](http://ionicframework.com/docs/v2/native/headerolor/) (there's a typo in the documentation, it's spelt Headerolor) does not work. 

**Expected behavior:**
Access plugin methods on import and be able to call the tint method.

**Steps to reproduce:**
Install the plugin
```
ionic plugin add cordova-plugin-headercolor
```
Try to import the plugin
```
import { HeaderColor } from 'ionic-native';
```

**Related code:**

```
import { HeaderColor } from 'ionic-native';
```

**Other information:**
The error displayed
```
Module '"/APP_INSTALL_PATH/node_modules/ionic-native/dist/es5/index"' has no exported member 'HeaderColor'.
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#1015
