### ISSUE TITLE
Feature request: ion-row[flex-end]

### ISSUE THREAD

**Issue by badpenguin** [driftyco/ionic#10221]
**Ionic version:**
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**
ion-row has center and baseline support but miss stretch and flex-end

**Expected behavior:**
Support at least flex-end because baseline its not much usefull while theming some layout

**Steps to reproduce:**
Add this CSS and the flex-end attribute to ion-row

**Related code:**

```
ion-row[flex-end] {
	-webkit-align-items: flex-end;
	-ms-flex-align: end;
	-ms-grid-row-align: end;
	align-items: flex-end;
}
```

**Other information:**
Thanks for the hard work.

**Comment by brandyscarney** [comment]
Thanks for the issue! The grid does support both `stretch` and `flex-end` by adding the attribute `stretch` or `bottom`. I am currently working on improving the grid and will make sure this gets added in the new documentation. :) Here are all of the row attributes and what they add:

```
ion-row[wrap] {
  flex-wrap: wrap;
}

ion-row[top] {
  align-items: flex-start;
}

ion-row[bottom] {
  align-items: flex-end;
}

ion-row[center] {
  align-items: center;
}

ion-row[stretch] {
  align-items: stretch;
}

ion-row[baseline] {
  align-items: baseline;
}
```
