### ISSUE TITLE
ngClick Fires Twice on Button

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1022]
Clicking a button causes `ng-click` event to fire twice.

Forum : http://forum.ionicframework.com/t/strange-behavior-when-overriding-a-cordova-function/2468

Sample : http://codepen.io/anon/pen/JrpuB

**Comment by joeandrews** [comment]
+1

**Comment by Giwi** [comment]
+1

**Comment by fabiobiondi** [comment]
+1

**Comment by robsilv** [comment]
+1. ion-nav-back-button fires twice for me in RC0.

**Comment by danmatthews** [comment]
+1 - Still getting this on RC0 too.

**Comment by michael8090** [comment]
+1 on RC3

**Comment by chrisschaub** [comment]
And on 1.0.0-rc.5

**Comment by motek80** [comment]
Having the same problem on 1.0.0-rc.5

This problem doesn't happen on "Ripple", but it does happens on physical device (Android 5.0.2).

Every click on button (bound using ng-click) is fires twice. However, the call is getting from separate places. It looks like the second call came from "tapTouchEnd" method.

function tapTouchEnd(e) {
  //console.log('touchend ' + Date.now());
  if (tapIgnoreEvent(e)) return;

  tapEnableTouchEvents();
  if (!tapHasPointerMoved(e)) {
    tapClick(e);

    if ((/^(select|option)$/i).test(e.target.tagName)) {
      e.preventDefault();
    }
  }

  tapLastTouchTarget = e.target;
  tapTouchCancel();
}

Please assist, this is a critical problem.

**Comment by jlkalberer** [comment]
+1

**Comment by michael8090** [comment]
+1

**Comment by motek80** [comment]
After additional investigation, turns out that the problem is due to Ionic Material. When click happens, first callback came from Material, and right after that second call from Ionic.

**Comment by jlkalberer** [comment]
I'm seeing this and I don't have Material installed.

**Comment by bruno-machado** [comment]
I found the following solution on internet. creating a directive.I have Material Angular installed with Ionic.

app.directive('myclick', function() {
    return function(scope, element, attrs) {
        element.bind('touchstart click', function(event) {
            event.preventDefault();
            event.stopPropagation();
            scope.$apply(attrs['myclick']);
        });
    };
});

app.controller('Main', function ($scope) {
    
    $scope.anything = function() {
        
        alert('Anything');
    };
});



before
<a href="#" ng-click="anything()">click</a>
now
<a href="#" myclick="anything()">click</a>

**Comment by iamsamwood** [comment]
@bruno-machado that worked for me, thanks!

**Comment by JungmoKang** [comment]
In My case,
https://github.com/angular/material/issues/1406
this is worked.

```
.config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```

**Comment by cmauroie** [comment]
@bruno-machado worked for me, thanks!

**Comment by cisnb125** [comment]
I'm using Angular Material with Ionic.
I was afraid I had to use mnTouch directive all over my code, but
@JungmoKang your solution did it for me. Thank you!

**Comment by rafaelcremer** [comment]
In My case,
a work-around for the problem I have with the back button on WP 

var locked = false;
$scope.GoBack = function($event) {
		
        if (locked == false) {
        	
        	$ionicHistory.goBack(); 
        	locked = true;
    		setTimeout(function(){ locked = false; }, 50);
        }
}

**Comment by jasdeepsingh** [comment]
As mentioned by @JungmoKang following worked for me:

```
.config(function($mdGestureProvider) {
  $mdGestureProvider.skipClickHijack();
}))
```

**Comment by QiaoyuanMaxDeng** [comment]
@jasdeepsingh @JungmoKang 
this works for me too. thanks

```
.config(function($mdGestureProvider) {
  $mdGestureProvider.skipClickHijack();
}))
```

**Comment by rhperera** [comment]
@JungmoKang I had the same problem with ionic + md angular. Adding your code worked for me. thanks
```
.config(function($mdGestureProvider) {
  $mdGestureProvider.skipClickHijack();
}))
```

**Comment by mlemainque** [comment]
I had the same problem with angular-material@0.11.4 + ionic@1.7.12 built for an Android app, but none of the previous solutions worked for me.

I finally got it to work with a small change in @bruno-machado solution:
```javascript
    app.directive('myclick', function() {
        return function(scope, element, attrs) {
            element.bind('touchstart click', function(event) {
                event.preventDefault();
                event.stopPropagation();
                if (event.type === 'click') {
                    scope.$apply(attrs['myclick']);
                }
            });
        };
    });
```

Thanks,

**Comment by chrisschaub** [comment]
Change from anchor link to button. Anchor links fire twice.

On Mon, Jan 11, 2016 at 9:52 AM, Matthias Lemainque <
notifications@github.com> wrote:

> I had the same problem with angular-material@0.11.4 + ionic@1.7.12 built
> for an Android app, but none of the previous solutions worked for me.
>
> I finally got it to work with a small change in @bruno-machado
> <https://github.com/bruno-machado> solution:
>
>     app.directive('myclick', function() {
>         return function(scope, element, attrs) {
>             element.bind('touchstart click', function(event) {
>                 event.preventDefault();
>                 event.stopPropagation();
>                 if (event.type === 'click') {
>                     scope.$apply(attrs['myclick']);
>                 }
>             });
>         };
>     });
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/1022#issuecomment-170593665>.
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by joaotocilo** [comment]
I had the same case. Works removing Angular Material.

**Comment by hvadotnarola** [comment]
---------

**Comment by axsauze** [comment]
@rhperera adding that code fixed it for me as well. How can this be incorporated as a fix?

**Comment by farisfawaaz** [comment]
@bruno-machado hey man, thanks a lot. Works how it should now! saved me a lot of time! btw this was my first directive! have no clue what i copied :P

**Comment by chengen** [comment]
@JungmoKang  works for me.

**Comment by jhlee8804** [comment]
@JungmoKang thanks!!!! lol

**Comment by mavillar** [comment]
@JungmoKang Works like a charm!! Thanks!

**Comment by mayoraservices** [comment]
hello every one i face same issue. ng-submit fire twice time on android device. i used angular material in ionic framework. how to stop twice time fire ng-submit...??? please help meee

**Comment by paradite** [comment]
@rhperera hey, your version of the fix has an extra `)` at the end. Mind correcting that?

**Comment by johnbolsberg** [comment]
@paradite @chengen how can i solve it in ionic 2?

**Comment by nkccaomus** [comment]
@JungmoKang 
works for me. Thank you.

**Comment by jdddog** [comment]
@JungmoKang
Thanks, works for me! (Using Ionic 1.3.0 and angular-material 1.1.0-rc.5 together)

**Comment by jonathan68** [comment]
@bruno-machado How can I create and use this directive in Ionic 2?

**Comment by bruno-machado** [comment]
Hi @jonathan68   I'm not familiar yet with Angular2,To tell you the truth, I've never used it, but I think it's something like:

@Component({
  selector: 'my-app',
  template: `
    <button (click)="onClick()" >Click</button>
})
export class AppComponent {
onClick() {
    return function(scope, element, attrs) {
        element.bind('touchstart click', function(event) {
            event.preventDefault();
            event.stopPropagation();
            scope.$apply(attrs['myclick']);
        });
    };
}
}
