### ISSUE TITLE
ion-footer does not respect $background-color

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#10235]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
See title
I have tried various ways to set this with no success.
Not really sure if it is a bug or feature but you can see what I want to do.

**Expected behavior:**
I would expect the footer to respect background-color: $background-color;

**Related code:**

SCSS

  .aever-footer {
    padding: 0em;
    background-color: $background-color;
  }

HTML

```
<ion-footer>
  <ion-toolbar>
    <div class="aever-footer">
      aever 0.0.1
    </div>
  </ion-toolbar>
</ion-footer>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

![capture001](https://cloud.githubusercontent.com/assets/140737/22412808/2e952b9e-e667-11e6-932a-7fa1d095b86b.png)

**Comment by brandyscarney** [comment]
So by design the `ion-footer` has no styling it is just a container element. In your particular case, the `ion-toolbar` background is "covering up" the footer. If you were to do this:

```
<ion-footer style="background-color: lightgreen;">
  <ion-toolbar transparent>
    ...
  </ion-toolbar>
</ion-footer>
```

You would see the styling on the footer:

<img src="https://cloud.githubusercontent.com/assets/6577830/22428782/5a91314c-e6d6-11e6-91b3-9fc14e3d106e.png" width="300">
