### ISSUE TITLE
No response for ionic serve after upgrading to latest stable version

### ISSUE THREAD

**Issue by yogeshwar607** [driftyco/ionic#10238]
Getting no response after upgrading to latest stable version.Before that it was working fine.

Created new project , still getting same issue.

![screen shot 2017-01-30 at 3 20 57 pm](https://cloud.githubusercontent.com/assets/10059011/22418690/19e8d3e6-e700-11e6-84da-1c1f5721a510.png)

**Comment by graphefruit** [comment]
@yogeshwar607 Can you please post your `ionic info` ?
Is there any error while serving?

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1888

**Comment by yogeshwar607** [comment]
Solved it by 
re-installing node and ionic .
