### ISSUE TITLE
Video capturing

### ISSUE THREAD

**Issue by divyaeficaz** [driftyco/ionic#10236]
I have created a hybrid app with ionic frame work. The app contains a section to capture video and upload it to an external server. The video recording works perfectly in android phone but not in iPhone. I have already given permissions for the same in manifest.xml. But the app not capturing the video. Can any one help me to solve this issue?

Thanks and regards
Divya

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
