### ISSUE TITLE
[EXTEME BUG] device failing to execute as for ES6 support errors

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10231]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Running my app, which includes `class` and `let` in it, on many devices /emulators work, However, running it on this device fails with errors like:
![image](https://cloud.githubusercontent.com/assets/5757359/22405280/19dece8a-e649-11e6-91a2-91167318dddf.png)

Don't know what this is:
> main.js:127765 
Uncaught SyntaxError: Unexpected reserved word

This is a dependency I am using via NPM: (the class ArrayPrototypes is theirs)
> Uncaught SyntaxError: Unexpected reserved word
class ArrayPrototypes {

A config file (js) on root of the app:
> unexpected identifier for:
let _config = {

**Expected behavior:**
Full transpiling for everything the app relies on

**Steps to reproduce:**
Have a config file at the root of the app. in it, write:
```
let _config = {};
module.exports = config;
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by anatoly-spb** [comment]
According https://thenextweb.com/dd/2016/03/09/6-reasons-need-learn-javascript-es6-now-not-later/

> ES6 support is coming along well in major desktop browsers, with Chrome at more than 90 percent compatibility, Edge at 80 percent and Safari at 54 percent. On mobile there’s just 31 percent of ES6 support for Android 5.1 users and 54 percent for iOS users.

So try to switch back to the tsconfig.json supplied by ionic:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by AmitMY** [comment]
@anatoly-spb I think I might have not explained myself correctly.

Ionic using webpack I think, transpiles all of the source files to es5, which is great. However, if you use a file outside of the src folder (for example, root folder, or node module), and that file is using es6, it will not transpile it in the bundle, and will keep it as es6. That is the problem.

When I edited the node module (it is actually my own module, so I added transpiling for it), and changed the config file to instead of having `let` have `var`, it works.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#697

**Comment by yozman** [comment]
@AmitMY 
I had the same problem use with package `teambition-sdk`
how did you solve it?

**Comment by AmitMY** [comment]
@yozman the package is mine. I added babel to transpire it to es5, and that fixed the problem.
