### ISSUE TITLE
Building with the --prod tag may break component inheritance.

### ISSUE THREAD

**Issue by bartverweire** [driftyco/ionic#10232]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
building with the --prod flag breaks inheritance.
Pages extending a parent class that have an implementation of ngOnInit/ngOnDestroy must have their own implementation of ngOnInit/ngOnDestroy. This is not the case with non-minified bundles as generated by ionic serve, ionic run or ionic build without the --prod flag.

**Expected behavior:**
A page or component that extends a parent class should be able to use the parent implementation if the page or component doesn't explicitly implement the methods.

**Steps to reproduce:**
I have uploaded a demo project on [https://github.com/bartverweire/inheritance](url)

Create a new application
`ionic start inheritance --v2`

add the browser as platform (just to be able to build afterwards, it could be any platform).
`ionic platform add browser`

create a file base.ts under pages/base/. This is not a Component, but just a class, containing code that is common to all pages (e.g. creating alerts, toast, ...)
This file implements the OnInit and OnDestroy interfaces, and provides a default implementation.

```
import { OnInit, OnDestroy } from '@angular/core';

export class BasePage implements OnInit, OnDestroy {

  constructor() {
    console.log("BasePage - constructor");
  }

  ngOnInit() {
    console.log("BasePage - ngOnInit");
  }

  ngOnDestroy() {
    console.log("BasePage - ngOnDestroy");
  }
}
```

Adapt the HomePage, to extend the BasePage. Do not specify an implementation of ngOnInit and ngOnDestroy.

```
import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
import { BasePage } from '../base/base';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage extends BasePage {

  constructor(public navCtrl: NavController) {
    super();

    console.log("HomePage - constructor");
  }

}
```

Build the app by using 
`ionic run browser --target=chromium`

I get

```
base.ts:6BasePage - constructor
home.ts:15HomePage - constructor
base.ts:10BasePage - ngOnInit
```

--> the HomePage loads, calls the parent constructor from within its own constructor, and calls the parent ngOnInit method.

Now build the app for production

`ionic build browser --prod`

When I run the application, I only get

```
main.js:87248BasePage - constructor
main.js:35210HomePage - constructor
```

The ngOnInit method is not called

When I explicitly add the ngOnInit and ngOnDestroy methods

```
  ngOnInit() {
    console.log("HomePage - ngOnInit");
    super.ngOnInit();
  }

  ngOnDestroy() {
    console.log("HomePage - ngOnDestroy");
    super.ngOnDestroy();
  }
```

And I build it again

`ionic build browser --prod`

Then I get

```
main.js:87256BasePage - constructor
main.js:35210HomePage - constructor
main.js:35213HomePage - ngOnInit
main.js:87259BasePage - ngOnInit
```

Apparently, the parent ngOnInit method is known, but the child class must explicitly implement the methods.
This is only the case for the minified version. The non-minified version seems to handle this inheritance correctly.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#696
