### ISSUE TITLE
Ionic2 ion-select with search bar

### ISSUE THREAD

**Issue by islamshaheen** [driftyco/ionic#10240]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request

**Current behavior:**
ionic select opens an alert window without a search bar

**Expected behavior:**
i need a search bar on the top of the ionic option so i can search the options

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by islamshaheen** [comment]
Thanks for the reply, I already added my question on the forum :)
As i understood you don't allow a multiple input types inside the same Alert( i need to add an input of type text on the top another radio inputs.
https://forum.ionicframework.com/t/ionic2-ion-select-with-search-bar/77798

**Comment by pabloim1** [comment]
Hi, did you find a solution for this? It's very important when having a lot of options.

**Comment by uniphonic** [comment]
Looks like it was answered over here: https://stackoverflow.com/questions/41932373/ionic2-ion-select-with-search-bar

**Comment by eakoriakin** [comment]
Here’s a ready component:
https://github.com/eakoriakin/ionic-select-searchable
