### ISSUE TITLE
Text field inside iframe doesn't accept input on iOS

### ISSUE THREAD

**Issue by excaliburHisSheath** [driftyco/ionic#10247]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On iOS, text input inside an `<iframe>` will sometimes fail to accept text input. Immediately after tapping on the text input for the first time typing will work as expected, but if the user tries to drag the cursor, then future input will no longer work until the text field loses focus. The same issue occurs if the user selects all the text and deletes it; Afterwards the input field will no longer accept text the user types. 

**Expected behavior:**

Text fields inside an iframe should behave as they do in a mobile web browser. The user should be able to drag the cursor and select/delete text and then be able to continue typing in the text field.

**Steps to reproduce:**

1. Clone this repo: https://github.com/excaliburHisSheath/iframe-repro. It is setup with ionic 2.0.0 and a minimal reproduction of the issue.
2. Build for ios with `ionic build ios`. Open the app on your iOS device.
3. Tap on the input field. You should be able to enter text.
4. Press and hold on the input field to bring up the magnifying glass. Drag the magnifying glass back and forth. Notice that cursor does not appear as it would normally. You should no longer be able to enter text, but the input field is still in focus and the keyboard stays open.

Alternatively:

4. Press and hold the input field to bring up the "Select All" menu. Press "Select All", then delete the text you entered. You should no longer be able to enter text, but the input field is still in focus and the keyboard stay open.

**Other information:**

It looks like #7219 is related, but no repro case was ever provided for that issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will take a look at this.

**Comment by excaliburHisSheath** [comment]
Sorry to bother, but is there any update on this? Or is there anything I can do to help diagnose the bug? My team is trying to use Ionic 2 in a production app and this issue may be a blocker for us. I appreciate any help you can offer, even if it's just a workaround.

**Comment by jgw96** [comment]
Hey @excaliburHisSheath , sorry for the delay on this! Unfortunately UiWebView (the default webview on iOS currently) has a good amount of issues around iFrames. We generally try to tell people to avoid iframes if possible but if its an essential part of your app i would recommend trying [our fork](https://github.com/driftyco/cordova-plugin-wkwebview-engine) of the wkwebview cordova plugin. WkWebView is a much more stable webview than UiWebView and may give you a better experience with iFrames. Let me know how that goes!

**Comment by excaliburHisSheath** [comment]
Thanks for the update! I'll give that a try and report back.

**Comment by excaliburHisSheath** [comment]
The WkWebview plugin did the trick! It might be worth making that the default if works better than the default web view that Cordova uses, but for my purposes I'd consider this fixed. Thanks for the help!
