### ISSUE TITLE
Ionic 2 onSwipeRight/Left

### ISSUE THREAD

**Issue by ibby89** [driftyco/ionic#10243]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There is no way to swipe to another page like in Ionic 1 (using the onSwipe directive).

**Expected behavior:**

User should be able to swipe to a different page.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by opahti** [comment]
Are you aware of the (swipe) event in Ionic v2, as pointed out here?http://ionicframework.com/docs/v2/components/#gestures 
There's also (swipeleft) and (swiperight).

**Comment by ibby89** [comment]
I am aware of it, but I didn't see any mention of swiperight/swipeleft, so I had thought the only way to implement this was with a custom method defining how much of the screen can be used for the swipe (in px).
I cannot find documentation of how to implement swiperight/swipeleft but I guess it looks easy enough.

**Comment by opahti** [comment]
Yeah, they are as simple as they sound. Had to discover those on my own as well.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
