### ISSUE TITLE
Build vs Serve

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#10245]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

config/config.js
```
const config = function() {
    return {
        api: {
            base: 'http://localhost:3000/',
        },
    };
};

module.exports.edConfig = config();
```

event.js
```
import {edConfig} from "./../config/config";
```

Run` ionic serve` everything works fine

Run `ionic run android `. You get a white screen with error 

`Cannot find module "./../config/config"`

**Expected behavior:**

Should not throw error in one when it works fine in another

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.3-201611211919
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X Yosemite
Node Version: v7.2.1
Xcode version: Xcode 7.2.1 Build version 7C1002

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#698
