### ISSUE TITLE
Password fields in Angular reactive forms are erased on focus changes/keypress events

### ISSUE THREAD

**Issue by lincolnthree** [driftyco/ionic#10248]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Data is nulled out in password fields on changing focus.

**Expected behavior:**
The input should remain populated in password fields when changing focus, just like type=text

**Steps to reproduce:**
Using this Plunker: http://plnkr.co/edit/TkRr8cpOiaIRjrNRpgsw?p=preview

Enter data into either or both of the password input text boxes. Move focus between/to/from/etc them a few times and watch it vanish! Password fields are clobbered. Others seem to work fine.

Note, you seem to have to blur the input field then return to it then leave it again in order to trigger the bug. 

**Related code:**
None.

**Other information:**
No idea.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by lincolnthree** [comment]
PS. I have verified that this is NOT an angular issue. 

http://plnkr.co/edit/bT7DT9bHVF8STYAiLeFp?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look into this.

**Comment by brandyscarney** [comment]
@lincolnthree I'm not able to reproduce the input clearing on focus, but I can see it clearing when I edit it. This is caused by the `clearOnEdit` attribute. Using the following fixes it for me:

```
<ion-input 
  clearOnEdit="false" 
  formControlName="password" 
  type="password" 
  placeholder="text entered here will disappear">
</ion-input>
```

from our code:

```
    // By default, password inputs clear after focus when they have content
    if (this.type === 'password' && this.clearOnEdit !== false) {
      this.clearOnEdit = true;
    }
```

I'll talk to the team about whether we need to update this behavior or the documentation behind it.

**Comment by brandyscarney** [comment]
I've discussed this with the team and determined this is the desired behavior. I'm going to leave this open and I will update the docs to reflect this. :)

**Comment by lincolnthree** [comment]
Hmmm okay. Glad to know that this is a feature :) I was wracking my brain over this one like you wouldn't believe. I'll try this out ASAP.

**Comment by lincolnthree** [comment]
Confirmed. Setting `clearOnEdit=false` solves my issue. Much appreciated!

**Comment by brandyscarney** [comment]
Thanks @lincolnthree. :) I'm updating the docs now.

**Comment by brandyscarney** [comment]
I pushed some changes to the docs. We'll get the site updated soon (it takes about an hour to build). Thanks!
