### ISSUE TITLE
ion-list: sticky items

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#1025]
Initially discussed in #1024 

@mlynch's initial idea for syntax:

``` html
<ion-list>
  <ion-item-group>Cats</ion-item>
  <ion-item ng-repeat="i in group1">{{i}}</ion-item>
  <ion-item-group>Dogs</ion-item>
  <ion-item ng-repeat="i in group2">{{i}}</ion-item>
</ion-list>
```

**Comment by RouR** [comment]
see also http://forum.ionicframework.com/t/sticky-list-headers/689/39 and https://github.com/chalettu/ionic-sticky-list-dividers

**Comment by aliok** [comment]
FYI, I improved the code of @colllin and converted into a project (bower, demos, etc).

See the project page: http://www.aliok.com.tr/projects/2015-04-17-ion-affix.html
Demos: http://codepen.io/collection/DrxWPr/

**Comment by jimthedev** [comment]
@aliok Awesome! Looks fantastic. Now I can go back to our designers and let them know not to avoid this design pattern. :D  

One bit of feedback. The scrolling on the demos in the project page is funky for me in Chrome. Works perfectly in codepen when not embedded.

**Comment by micrdy** [comment]
This plugin does not work with newer versions of ionic & angular. This should be looked at again.
