### ISSUE TITLE
Ionic 2 - popover doesn't come up after Camera Plugin activated to take picture or video

### ISSUE THREAD

**Issue by monalisasaha79** [driftyco/ionic#10250]
I am having a weird problem in the Ionic 2. I am sure I am missing something.
Version I am using 2.2.0

I have a popover on the home screen and FAB controller. Popover works fine till I open camera to take picture. Post closer of camera plugin my popover doesn't come up. Below my popover code is given:

export class AssetPage {
  	constructor(private navCtrl: NavController, private popoverCtrl: PopoverController) {}
  	
  	assetPopover(myEvent) {
	    let popover = this.popoverCtrl.create(AssetPopoverPage);
	    popover.present({
	      	ev: myEvent
	    });
	}
}

Camera code:
public captureImageFromCamera(){
    Camera.getPicture ({
      sourceType: 1,
      quality: 100,
      correctOrientation: true,
      mediaType: 0,
      encodingType: 0
    })
    .then((data) =>{
      setTimeout(() => {
        console.log (data);
        this.imageUpdate(data, 0);
      }, 0);
    }, (err) => {
      console.log ("Do nothing");
    });
  }

This is happening for MediaCapture plugin as well.

MediaCapture.captureVideo({
    }).then((localURI) =>{
      setTimeout(() => {
        this.videoUpdate(localURI[0].fullPath);
      }, 0);
    }, (err) => {
      console.log ("Do nothing");
    });

It is not only for the main popover. None of the popover is being displayed after camera interface activation.

Please help.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1019
