### ISSUE TITLE
Ionic 2 FR: ion-delete-button and ion-item delete animation in Ionic 2 ion-lists

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#10255]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
At the moment (as far as I am aware) there is no option to "edit" an `ion-list`.

From Ionic 1, there was a lovely feature where you could set a `show-delete` directive on an ion-list which displayed the `ion-delete-button` and wire that up to a function. If you then spliced an item in the array the list was bound to, this showed a nice animation of the item sliding out.

None of this appears to be present in Ionic 2. IMO the delete button is less important since you can use an `ion-item-sliding` item with an `ion-option-button` to produce similar behaviour.

But the removing item animation would be great if possible just to give a more native feel.

**Expected behavior:**
Similar to the example here: http://ionicframework.com/docs/api/directive/ionList/

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks for using Ionic!
