### ISSUE TITLE
Odd behaviour of life-cycle events

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10265]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When for example having a sidemenu app, and you click an item on the submenu, it first calls `ngOnInit` for that component, and afterwards calls `ngOnDestroy` on your last component.

**Expected behavior:**
First destroy the current component, then create a new component

**Steps to reproduce:**
http://plnkr.co/edit/dBud22DUWo7yFBpPOOvG?p=preview

**Motivation:**
I am handling socket events. The `ngOnInit` has `socket.on("event", this.event.bind(this))`, and the `ngOnDestroy` has `socket.destroy("event", this.event.bind(this))`

Current behaviour means that I can not listen to that event the second time.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You should not be using the standard Angular events with Ionic. We have our own lifecycle events you can read about [here](https://ionicframework.com/docs/v2/api/navigation/NavController/) that you can use in your Ionic app.

**Comment by AmitMY** [comment]
Thanks!
I acctually did visit that page, but when I saw it was using `ngOnInit` in the beginning, I left. My mistake

**Comment by jgw96** [comment]
No problem (:
