### ISSUE TITLE
Tool for Unit Testing

### ISSUE THREAD

**Issue by nicobytes** [driftyco/ionic#10263]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request 

**Current behavior:**
In ionic should have a tool for setup unit testing like nativescript. like this:

```
tns test init
```

**Expected behavior:**
![nativescript-select-unit-test-framework](https://cloud.githubusercontent.com/assets/7611944/22493392/d6107f58-e7fd-11e6-9197-c2423cc1685a.gif)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1891
