### ISSUE TITLE
Sass Error on Ionic Final

### ISSUE THREAD

**Issue by rodriguesgm** [driftyco/ionic#10261]
**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating from RC3 to Final, I got this Sass ERROR when running ionic serve

![0](https://cloud.githubusercontent.com/assets/10141664/22490296/3602a718-e7fb-11e6-9854-37cd9c1a5b72.png)

![sem titulo](https://cloud.githubusercontent.com/assets/10141664/22490342/88fa86de-e7fb-11e6-80ea-78ac044c39e6.jpg)

This is a variable from Ionic, so it should exists.

**Expected behavior:**
ionic serve should work

**Steps to reproduce:**
Just update to RC Final and run ionic serve.

**Related code:**
package.json
```
{
  "name": "***",
  "description": "****",
  "homepage": "*****",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "config": {
    "ionic_webpack": "./scripts/custom-webpack.config.js",
    "ionic_tslint": "./tslint.json"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "@types/localforage": "0.0.30",
    "@types/lodash": "^4.14.36",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "sw-toolbox": "3.4.0",
    "localforage": "^1.4.2",
    "lodash": "^4.16.2",
    "moment": "^2.17.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "ncp": "^2.0.0",
    "string-replace-webpack-plugin": "0.0.4",
    "typescript": "2.0.10",
    "webpack": "^1.13.3"
  }
}

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will take a look into this.

**Comment by brandyscarney** [comment]
@rodriguesgm This variable was actually removed with this commit: https://github.com/driftyco/ionic/commit/b788ce6133ea6ef4cc1c21ff8d73ccd822325bc9 

Since it is no longer being used to style the labels in Ionic.

**Comment by jgw96** [comment]
Hello all! Since we are not using this variable internally and do not have any plans to add it back I am going to close this issue for now.

**Comment by rodriguesgm** [comment]
@brandyscarney  is there a list of variable that were removed?

I removed those 3 variables from my scss and it's working again, so just want to know what variables were removed.
$label-ios-text-color
$item-ios-note-color;
$item-md-note-color;

thanks for the help

**Comment by brandyscarney** [comment]
@rodriguesgm There isn't a list of what's been removed between versions, but this list contains the latest Sass variables:

http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/

and the API docs will update with each version (toggle versions in the top left of the left menu):

http://ionicframework.com/docs/v2/api/components/label/Label/#sass-variables
