### ISSUE TITLE
feature: ability to call ion-refresh programmatically 

### ISSUE THREAD

**Issue by swiftyone** [driftyco/ionic#10267]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There seems to be no API to programmatically start the loading of the refresher.
It would be awesome to use the refresher to also show the user that some content is reloading, e.g. if the app is resumed. Additionally it does not make sense to use another component (like the LoadingController) if the refresher is used on the page anyhow – if there are two different components that basically indicate the same thing (which is reloading content) it could possibly confuse the user.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v5.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by wishdusk** [comment]
need ！

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#93

**Comment by kyr0** [comment]
Well, the new feature request has been removed? ;)

**Comment by karx** [comment]
@jgw96 The link seems to be down.
Any update on this feature request.

**Comment by kensodemann** [comment]
@karx - the feature requests repo is a private repo.

At this time, no feature requests are being worked on until after the next major release of Ionic and Ionic for Angular are complete.

There has also been some talk of perhaps managing feature requests differently at that time, but nothing has been determined on that front yet.
