### ISSUE TITLE
Swiper breaking if accessed quickly enough and multiple times

### ISSUE THREAD

**Issue by Loutrinos** [driftyco/ionic#10271]
**Ionic version:**
[x ] **2.x**

**I'm submitting a ...** 
[x ] bug report

**Current behavior:**
If we navigate quickly between pages that have a swiper in some cases the ngOnDestroy of the swiper breaks

**Expected behavior:**
The swiper need to initialize every time it's called

**Steps to reproduce:**
Create 2 pages in a tabbed interface and add to the first a swiper.
Try to navigate between those pages a lot of times stressing as much the swiper component

**Related code:**
When trying to destroy the component here:
https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L1092
`this` is not defined.
This might be occuring cause of this:
https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L939
```
  ngAfterContentInit() {
    this._plt.timeout(() => {
      this._initSlides();
    }, 300);
  }
```
timing out or this:
https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L903
```

    if (viewCtrl) {
      var subscription = viewCtrl.readReady.subscribe(() => {
        subscription.unsubscribe();
        this._initSlides();
      });
    }
```
not managing to resolve the subscription before the destroy of the component.

As all above are asynchronous the ngOnDestroy might be called before the initialization of the component and as a consequence breaking it.

Potential fix would be to add a check for the `this` if it's present before trying to access it.
```
ngOnDestroy() {
    if(!this) {
      return;
    }
    this._init = false;

    this._unregs.forEach(unReg => {
      unReg();
    });
    this._unregs.length = 0;

    destroySwiper(this);

    this.enableKeyboardControl(false);
  }
```

**Comment by jgw96** [comment]
Thanks, we will take a look into this.

**Comment by mickadoua** [comment]
i made a PR for this, issue
https://github.com/driftyco/ionic/pull/11100

**Comment by deepak07** [comment]
Is this issue fixed? Is there any workaround for now to solve this?

**Comment by mickadoua** [comment]
@deepak07 look the PR #11100 to include the fix on your app

**Comment by naveedahmed1** [comment]
I think the issue still exists, I am seeing **ERROR TypeError: Cannot read property 'hasAttribute' of undefined** error even with latest release.

**Comment by mickadoua** [comment]
can you past your ionic info

**Comment by hamzahamidi** [comment]
This issue still exists

**Comment by kumaran-is** [comment]
This issue still exists 
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3 Build version 8E162 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10

**Comment by sebrojas14** [comment]
Why is closed this? I'm still getting error calling SlideTo:

`ionViewDidLoad() {

    this.localSettings.load().then(() => this.localSettings.getValue(this.localSettings.SETTINGS_INTRO_SEEN).then(res => {

      this.loaded = true;

      if (res) {

        this.slides.slideTo(5);
        
        this.startIntroVideo();
      }
    }));
  }`

**Comment by TonyLuo** [comment]
+1 .  I still got the same error when init the slides in ionViewDidLoad()

**Comment by melwinVincent** [comment]
+1, Until fixing this issue, can I rely on a timeout of 100 ms and move on ??

**Comment by melwinVincent** [comment]
@mickadoua : Your code is already there in my files. Still I'm getting this issue.
![untitled](https://user-images.githubusercontent.com/12426903/28932505-c4f6e23e-788a-11e7-9322-2df4c4463b92.png)

**Comment by aslaugsollilja** [comment]
Just adding `<ion-slides></ion-slides>` in my html brakes the code for that particular `page`. I get an runtime error ` ERROR Error: Uncaught (in promise): TypeError: Cannot read property '__zone_symbol__setTimeout' of undefined`. 

cli packages:
```
    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0
```
global packages:
```
    Cordova CLI : 7.0.1
```
local packages:
```
    @ionic/app-scripts : 1.3.6
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2
```
System:
```
    Node : v7.9.0
    OS   : macOS Sierra
    npm  : 4.2.0
```

**Comment by Cagdas88** [comment]
why its closed????
As everyone says. This problem is still existing.

**Comment by Jorge0594** [comment]
I have one solution for that, but is a bad way for sure:
```
ngAfterViewInit(){
    setTimeout(() => {
      this.slides.slideTo(this.roundSelected -1 );
    }, 50);
}
```

**Comment by EugeneSnihovsky** [comment]
Hello from 2018. This issue is still exist and setTimeout is bad solution. For devices with powerful hardware 50ms is quite enough, but for old devices sometimes even 500ms is not enough and error appears.

This is not cordova or some third party module issue, this is bug in your framework core. Please fix it or add status `won't fix` and add in docs mark `not production ready` to this feature.

**Comment by brynner** [comment]
It's almost 2050 and the bug still exist. Trying to figure out how to solve it
