### ISSUE TITLE
Ionic 2 Internet Explorer 11 support with Ion-DateTime (FR)

### ISSUE THREAD

**Issue by growthclick** [driftyco/ionic#10277]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
This is a feature request to update ion-datetime to work with IE 11 on Windows 7, as this is one of the main issues stopping us from offering an adequate IE experience to our clients and users.  

Current behavior: ion-datetime renders with a single letter (W or T in my testing) instead of a date and doesn't respond to any click events. 

![image](https://cloud.githubusercontent.com/assets/5842645/22527935/eb31a85c-e885-11e6-8cf9-4b0175bb46d4.png)

I realize you don't support Internet Explorer, but I'm hoping you could add some unofficial IE 11 support for the datetime component given the trend of using Ionic as a web framework, Angular 2's shim support for IE 9 - 11 (https://angular.io/docs/ts/latest/guide/browser-support.html), and browser stats such as https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables

**Expected behavior:**
ion-datetime should work on IE or gracefully downgrade to a simple text input box for now. 

**Steps to reproduce:**
Create a starter project with ion-datetime and load in Internet Explorer in document mode of IE 11 / Edge, using PC or Virtualbox https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ or Browserstack.   

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.7.0 
ios-sim version: 5.0.3 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time we have no plans to support IE11. If you would like to do a PR that adds this support then feel free too, but at this time we are not going to be implementing any official support for IE. Sorry about any hassle this causes.

**Comment by growthclick** [comment]
@jgw96 Thanks for letting me know. It's impacting about 10% of web users so may try a temporary *ngIf workaround to use a text field in place of ion-datetime.
