### ISSUE TITLE
ion-item not shown custom div elements & now shown if size on ion-item increse more than 1 line

### ISSUE THREAD

**Issue by Arqam123** [driftyco/ionic#10273]
http://stackoverflow.com/questions/41981839/ion-item-not-shown-custom-div-elements-now-shown-if-size-on-ion-item-increse-m

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
