### ISSUE TITLE
how to integrate?

### ISSUE THREAD

**Issue by xblox** [driftyco/ionic#10275]
Hi,
is there any chance to use the ionic framework without this massive toolchain ? For instance, I have my own 'server' (koa2) and for the cordova part: I have my own files, folders and tool chain in place. Even for the native access: I have my own implementations as well.

What I am asking is: do you have an example somewhere which provides the client ux (using TS sources from here) and possibly steps to compile my 'app' without `ionic build/serve` ?

I could of course spent a few days to figure out what ionic/app-scripts does but possibly you know better. 

thanks a lot. 

why: I am a big boy and I'd like to integrate ionic in my own mobile - authoring software :-)

**Comment by themastersoda** [comment]
I'd suggest taking a look at https://github.com/Urigo/meteor-angular2.0-socially/tree/master/manuals/templates - the tutorial is no longer available on their website, however, github repo has all the source code and instructions on implementing it. The example uses meteor as a backend server, but i think you would be able to adapt it for your needs. From what i can see, the package 'ionic-angular' is used as standalone there to provide all of the UI styles and behavior.

**Comment by xblox** [comment]
@themastersoda : excellent. thanks so much!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by xblox** [comment]
@jgw96 thanks, i already did in the forum but it rather seems this will never be picked up. The question was also about "is it technically possible to integrate ionic client ux in other frameworks/setups". The about slack: it asks me to sign up a team (being lost on this).

**Comment by xblox** [comment]
anyone else? looks like "ionic framework" is rather a kind of freemium product, not a real framework or library per se...

**Comment by xblox** [comment]
never mind. switched to something else.
