### ISSUE TITLE
ion-slides doesn't work for android simulator

### ISSUE THREAD

**Issue by 80m** [driftyco/ionic#10278]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
doesn't slide

**Expected behavior:**
slide

**Steps to reproduce:**
http://ionicframework.com/docs/v2/api/components/slides/Slides/

try to slide on the android simulator on the right

**Other information:**

Google Chrome Version 56.0.2924.76 (64-bit)

is it just me?

**Ionic info:**

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by 80m** [comment]
also, doesn't work in chrome's simulator (cmd + alt + I, cmd + shift + M) on any simulated device.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#984
