### ISSUE TITLE
Enable swipe-to-reveal side menu only if menu button is displayed

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic#10284]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

It would be very useful to opt-in to a feature where a side menu can only be swiped into view if a menu button with the `menuToggle` directive is present on-screen.

If there is a workaround to achieve this I'd be all ears! I've tried subscribing to the `viewDidEnter` observable that's emitted by the root `<ion-nav>` component but this doesn't cover all use cases (e.g. adding a modal into view).

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#143
