### ISSUE TITLE
Allow pages to opt out of caching complete state in history to save memory / performance

### ISSUE THREAD

**Issue by ivanmayes** [driftyco/ionic#10287]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When navigating through an app, the navController saves a stateful instance of each page on the DOM (or in memory) so that going back through the pages is quick and remembers the state.  This behavior is awesome for a lot of cases, but in some cases, such as an ecommerce app, where a user may continuously click forward through item pages via related items or new menu choices (we've seen some sessions get to 30-50 items via related), saving each page with the current method creates a performance issue for the user.  There is no way to save the state for the user while also garbage collecting up the memory / listeners to free up performance budget for later pages.

**Expected behavior:**
Ideally, there would be a navigation method that allows certain components to be registered in the history of navigation in name and nav params only, so that on ionDidLeave, the memory and listeners are removed and freed up for future pages.  Popping back to this page would recreate the component, so there is a trade-off in how you build these pages, but would give devs the option to create apps with longer history chains for better sustained performance.

**Steps to reproduce:**
Create a component that allows you to continually push a new version of that component into history.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#94
