### ISSUE TITLE
ion-select icon element to use IonIcons instead of pure CSS

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic#10289]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The dropdown icon for the ion-select is currently drawn through the use of CSS only.

**Expected behavior:**
Instead of using CSS to generate this element, use the proper IonIcon instead. This would enable developers an easier method to swap the item out for an alternative item.

I needed to have a > instead of the down arrow and it took more effort than I was expecting to replace it.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#95
