### ISSUE TITLE
SecureStorage doesn't fallback to LocalStorage

### ISSUE THREAD

**Issue by karlbateman** [driftyco/ionic#10280]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Following the instructions documented here http://ionicframework.com/docs/v2/native/secure-storage/, the SecureStorage is initialized and the expected functionality works natively on a device.

**Expected behavior:**
However, when opening an application which uses the SecureStorage plugin within a web browser it does NOT revert to LocalStorage.

**Steps to reproduce:**
You can use the following [sample application](https://github.com/karlbateman/debugApp) and use `ionic serve` to launch in the browser. Inspecting LocalStorage will show that no values have been set.

-->

**Related code:**

```
import { SecureStorage } from 'ionic-native';

let secureStorage: SecureStorage = new SecureStorage();
secureStorage.create('my_store_name')
 .then(
   () => console.log('Storage is ready!'),
   error => console.log(error)
);

secureStorage.get('myitem')
 .then(
   data => console.log(data),
   error => console.log(error)
);

secureStorage.set('myitem', 'myvalue')
 .then(
   data => console.log(data),
   error => console.log(error)
);

secureStorage.remove('myitem')
.then(
   data => console.log(data),
   error => console.log(error)
);
```

**Other information:**
This issue was originally created with the plugin author [Crypho/cordova-plugin-secure-storage](https://github.com/Crypho/cordova-plugin-secure-storage/issues/89), it has been suggested that the wrapper is not handling the browser as the plugin itself works fine within the browser.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1027
