### ISSUE TITLE
Ionic view source throws 404 

### ISSUE THREAD

**Issue by aravindfz** [driftyco/ionic#10294]
**Ionic version:** 
[x] **1.x**

In the [Ionic Collection](http://ionicframework.com/docs/api/directive/collectionRepeat/) documentation 
Clicking on the View Source navigates me to a github page [here](https://github.com/driftyco/ionic/tree/1.x/js/angular/directive/collectionRepeat.js#L2)
**I'm submitting a documentation error** 
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
404 Not Found 

**Expected behavior:**
Source Documentation

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#985
