### ISSUE TITLE
New session on every query Ionic 2 2.2.1

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#10299]
I got a problem with session GET query on Angular 2, Ionic 2 application. Problem is that I get every time on every query new session when query to server is done. So I can't to store information in session on server because I got different session each time. Here is my code in Ionic 2:

    import { Component } from '@angular/core';
    
    import { NavController } from 'ionic-angular';
    import { Http } from "@angular/http";
    import 'rxjs/add/operator/toPromise';
    
    @Component({
      selector: 'page-about',
      templateUrl: 'about.html'
    })
    export class AboutPage {
    
      constructor(public navCtrl: NavController, public http: Http) {
        let query = this.http.get('http://192.168.1.2/testdb.php');
    
        query.toPromise().then((result) => {
          console.log(result);
          console.log(result.json());
        });
      }
    
    }

On PHP server I got with code for CORS requests which is told my my session id.

```
<?php
    session_start();  //Start session

    //Headers to disable CORS request:
    header('Access-Control-Allow-Origin: *');             
    header('Access-Control-Allow-Headers: *');           
      
    echo "<pre>";
    var_dump(headers_list());       
    echo "</pre>";  
               
    echo json_encode(array('success' => true, 'session_id' => session_id()));
```
 
Here is my header information:
[desktop](https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/f/f/ff9015d3cc8039a60d441eeaa367f039d41b2444_1_309x500.png)

What is can be?

**Comment by azakusilo** [comment]
My app is allways sends (I don't know why) settings of new session. Each time I query server.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
