### ISSUE TITLE
Should work with locationStrategy: 'path'

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#10290]
_From @Mokto on December 1, 2016 20:49_

#### Short description of the problem:
When using locationStrategy to 'path', `http://localhost:8100/any_path` is not found by the script.

#### What behavior are you expecting?
Should work

**Steps to reproduce:**
1. ionic start myApp -t tabs --v2
2. set this in app.module.ts

```javascript
IonicModule.forRoot(MyApp, {
			locationStrategy: 'path'
		}, {
			links: [
				{ component: HomePage, name: 'Home', segment: 'home' },
				{ component: ContactPage, name: 'Contact', segment: 'contact' },
				{ component: AboutPage, name: 'About', segment: 'about' },
			],
		}),
```
3. Go to any route
4. Reload the page

**Which @ionic/app-scripts version are you using?**
0.0.46

** As a workaround, i'm writing locationStrategy: isDevMode() ? 'hash' : 'path'

Thank you !

_Copied from original issue: driftyco/ionic-app-scripts#500_

**Comment by jgw96** [comment]
_From @danbucholtz on January 28, 2017 5:59_

@jgw96,

Can you move this to framework?

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by nakedcity** [comment]
Any update on this one? Is there a flag live historyfallback?

**Comment by PunkHaz4rd** [comment]
Still running in this issue, deep linking set up:
- locationStrategy: 'path'
- { provide: APP_BASE_HREF, useValue: '/' } in the providers

**Comment by soumak77** [comment]
@jgw96 this seems to be an issue with the local web-server used by the ionic-cli.  Not sure why it was moved from there into the angular repository.
