### ISSUE TITLE
Ionic 2 - Popover is not rendering post keyboard operation

### ISSUE THREAD

**Issue by monalisasaha79** [driftyco/ionic#10295]
Hi Team,

Looks like there are some issue with the popover controller. It is getting created but not rendered correctly. Below image depicting the issue.
![ionic2popover-issue](https://cloud.githubusercontent.com/assets/25080451/22580547/71a9acf6-ea2d-11e6-87d4-b11419d3bb04.PNG)
To produce the issue, try to keyboard operation using input box (e.g. ion-input / ion-textarea) once done, then click on the button where popover associated with.

Please help.

Thanks,
Monalisa

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! What version of Ionic 2 are you running? 2.0.0 stable or one of the rc releases?

**Comment by monalisasaha79** [comment]
@jgw96 Please find the version information below
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.3.1
Xcode version: Not installed

**Comment by monalisasaha79** [comment]
Finally as suggested by Ionic team I have recreated the project, installed all the plugins. Looks like the wired issues is gone. Popover with native plugin is working fine.
Bit sad because, I could not find the root cause. Anyway, I will keep investigating the root cause.
Thanks for your support.
Cheers!!!
Monalisa
