### ISSUE TITLE
Ionic 2 storage is not cleaning up on uninstall - Only for signed APK

### ISSUE THREAD

**Issue by PrithiviRajG** [driftyco/ionic#10296]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using Ionic 2 storage (not sqlLite) for storing using credentials. On uninstalling the App, storage is not cleaning up, so on installing the App again it picks up the user credential of previous user.
This is issue is coming only in signed APKs. Tested on samsung on7 and lenova vibe models.

**Expected behavior:**
all the storage should be cleared on uninstalling the app.

**Steps to reproduce:**
1. take build as `ionic build android --prod --release`
2. sign the APK with jarsigner
3. Zip Align the APK and install it in mobile to save some data in local storage.
4. uninstall the app and install it again.

**Related code:**

```
this.storage.get('launchCount').then((applaunchCount:any) => {
      if(applaunchCount!=undefined && applaunchCount!=null && applaunchCount==1){
        console.log("applaunchCount "+applaunchCount)
      this.presentLoading();
  }
}
```

**Other information:**
http://stackoverflow.com/questions/42017520/ionic-2-storage-is-not-cleaning-up-on-uninstall-only-for-signed-apk

**Ionic info:**

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
Xcode version: Not installed

**Comment by TheRealKira** [comment]
I've noticed that after uninstalling and installing my app debug apks on Android 6.0.1, the installed size of the App is slowly increasing (with and without crosswalk plugin)! 

However, when incrementing the version of the app in config.xml, uninstalling from device, and rebuild/installing with or without --prod / --release, the Storage size goes back down to zero. 

I'm not sure if this is related to your issue, but it seems too coincidental.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by PrithiviRajG** [comment]
For people who are facing the same issue, please refer to https://forum.ionicframework.com/t/how-to-remove-local-storage-as-app-get-uninstall/14823/23 and  https://stackoverflow.com/questions/33169618/an-android-app-remembers-its-data-after-uninstall-and-reinstall for solution.

Thanks!

**Comment by shinta5150** [comment]
What about IOS

**Comment by PrithiviRajG** [comment]
@shinta5150 we never faced this issue in IOS
