### ISSUE TITLE
Ion-Scroll not working in broswer

### ISSUE THREAD

**Issue by swaheed2** [driftyco/ionic#10308]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
No scroll bar shown. The content inside the scroll bar is hidden. 

**Expected behavior:**
Content not hidden and Scrollable. 

**Steps to reproduce:**

1. Create a div with a height of 200px. 
2. Put a ```<ion-scroll>``` inside with some text content 

http://plnkr.co/edit/k318OcPuPjH2jD81GBG7?p=preview

**Related code:**

```
<ion-card class="section recent">
    <ion-card-header>
        Recent Accounts
    </ion-card-header>
    <ion-list>
        <ion-scroll>
            <button ion-item *ngFor="let account of recentAccounts"><ion-icon name="person" item-left></ion-icon>{{account.name}}</button>
        </ion-scroll>
    </ion-list>
</ion-card>
```

**Other information:** 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by mhartington** [comment]
In this case, ion-scroll is just not being provided with enough information. 
ion-scroll is essentially a dumb component, that needs to be feed specific widths/height. You also need to tell it where it can scroll, X-axis or Y-axis.

http://plnkr.co/edit/5w0QWy013P07qGsVoLPt?p=preview

I modified your plunk to add the missing information. 

http://ionicframework.com/docs/v2/api/components/scroll/Scroll/#input-properties
