### ISSUE TITLE
Ion-Scroll not working in broswer

### ISSUE THREAD

**Issue by swaheed2** [driftyco/ionic#10307]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

No scroll bar, the content is hidden.

**Expected behavior:**

Content not hidden and scrollable

**Steps to reproduce:** 

http://plnkr.co/edit/k318OcPuPjH2jD81GBG7?p=preview

**Other information:**

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
