### ISSUE TITLE
No variable for overriding ion-option label text color

### ISSUE THREAD

**Issue by ivanrylov** [driftyco/ionic#10301]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
For the dark theme, ion-option label text color is #000 (black) and there is no sass variable to override it.
It is possible to override only selected item using `$alert-ios-radio-label-text-color-checked` which is not enough for the dark theme. 

*Expected behavior:**
There should be a variable which could be used for overriding ion-option label text color.

**Steps to reproduce:**
1. Change the background of the Alert:
```
$alert-ios-background: #24242d;
$alert-md-background-color: #24242d;
$alert-wp-background: #24242d;
```
2. Create simple select with few options.
```
<ion-select [(ngModel)]="gaming">
      <ion-option value="nes">NES</ion-option>
      <ion-option value="n64">Nintendo64</ion-option>
      <ion-option value="ps">PlayStation</ion-option>
      <ion-option value="genesis">Sega Genesis</ion-option>
      <ion-option value="saturn">Sega Saturn</ion-option>
      <ion-option value="snes">SNES</ion-option>
</ion-select>
```
3. Run as a website in browser
4. Click select and check the options label color which is black.

**Other information:**
There should be such sass variables available:
```
$alert-ios-radio-label-text-color;
$alert-md-radio-label-text-color;
$alert-wp-radio-label-text-color;
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
run as a website
Ionic Framework Version: 2.0.0
Ionic App Scripts Version: 1.0.0
```

**Comment by jgw96** [comment]
Closing this issue as the above PR was merged. Thanks!
