### ISSUE TITLE
ion tab pages render all pages in the background

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10303]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using ion tabs may decrease rendering dramaticlly since all pages are rendered together.
I'm using 4 tabs: My world tab is really big page that uses different components and shows gifs, and the app works really slow when my world is rendered while im viewing any of my app pages inside my tabs.

**Bottom line: When using ion tabs, all the pages inside the tabs are running in the background.**

**Expected behavior:**
each tab to be rendered only when it's "active"

**Steps to reproduce:**
Any use of ion tabs

**Related code:**

```
  <ion-tabs>
    <ion-tab tabIcon="globe" tabTitle="World" [root]="world"></ion-tab>
    <ion-tab tabIcon="aperture" tabTitle="Big Page" [root]="bigPage"></ion-tab>
    <ion-tab tabIcon="people" tabTitle="People" [root]="people"></ion-tab>
    <ion-tab tabIcon="chatbubbles" tabTitle="Chat" [tabBadge]="badge" tabBadgeStyle="danger"
     [root]="chat"></ion-tab>
  </ion-tabs>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
@theunreal  that should not happen, hidden tabs should be `display: none` are you sure?
