### ISSUE TITLE
Error on Android build: "TypeError: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by Zerokk** [driftyco/ionic#10305]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I build my Ionic 2 app with "ionic run android", which launches the app in my Xiaomi mi5s. I'm using an Android 5 apk, and the Parse JS SDK. When I try to log in (which works perfectly in the navigator), it throws the error "TypeError: Converting circular sturcture to JSON". I've never had this error before in the navigator.

**Expected behavior:**
The app should send a request with some JSON'ified data to the Parse server, and return some data in the "success" promise so the user gets validated. It enters via the "error" promise, tho.

**Steps to reproduce:**
I just install the app in the phone and try to login with my credentials. 

- - -

What's going on? Why am I having this error?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
