### ISSUE TITLE
Allow HTML inside ion-option

### ISSUE THREAD

**Issue by leandroz** [driftyco/ionic#10316]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Right now ion-option is using `this._elementRef.nativeElement.textContent` so it only renders text.

**Expected behavior:**
Due to the way that ion-select works, I think it should be posible to use HTML as an option, for example for icons.

**Steps to reproduce:**

**Related code:**

```
text() => this._elementRef.nativeElement.textContent;
```

**Other information:**

I would love to create a PR if its aligned with how ion-option should work!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As this is not something we plan on doing anytime soon I am going to close this for now and move it to our internal feature tracking repo, but if you would like to do a PR for it then feel free too and we can evaluate it! Thanks.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#20
