### ISSUE TITLE
use of Angular 2 Hot Module Replacement: @angularclass/hmr instead of refreshing browser

### ISSUE THREAD

**Issue by almothafar** [driftyco/ionic#10318]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
Each change made to project files, it refresh the page and lost any changes and focus on the page, especially for forms and sometimes it is simply annoying getting page refresh for every change, especially if you are using WebStorm or InjelliJ, when you switch between windows, you will get the page refreshed directly, because those IDEs save when you lose focus.

**Expected behavior:**
Hot Module Reloading, no more need to refresh a page, and see changes instantly, this could really helpful to notice changes especially the really small changes and compare the previous state with new stat.!

**Other information:**
Angular 2 Hot Module Replacement: https://github.com/AngularClass/angular2-hmr

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#711
