### ISSUE TITLE
Property 'freeMode' does not exists on type 'Slides'

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#10315]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
Throws an error : 

> Property 'freeMode' does not exists on type 'Slides'

**Expected behavior:**

It should find **freeMode** property as it exists on Slides.

**Related code:**

```
import { ViewChild } from '@angular/core';
import { Slides } from 'ionic-angular';

class MyPage {
  @ViewChild(Slides) slides: Slides;

  ngAfterViewInit() {
    this.slides.freeMode = true;
  }
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by lumitor2** [comment]
I have it in constructor with platform ready promise and there is no warning. 
`
        this.platform.ready().then(() => {
        this.slides.pager = false;
        this.slides.freeMode = true;
        });
`

**Comment by jgw96** [comment]
Hello @HamzaLJ , thanks for opening an issue with us! So the issue here is that you are using the default angular lifecycle events. We have our own lifecycle events, which you can [read about in the docs](https://ionicframework.com/docs/v2/api/navigation/NavController/) that line up better with how ionic boots components.

**Comment by HamzaLJ** [comment]
@jgw96 That's not the reason.
I've tried to use `ionViewDidLoad` and I got the error.
It seems that the property `freeMode` does not exists in `Slides` because when I do: `this.slides.pager = true;` instead the error disappears!
