### ISSUE TITLE
Export ReorderIndexes

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic#10313]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I want to write a handler for the `ionItemReorder` event:
```
reorderItems(indexes: ReorderIndexes): void {
}
```
Unfortunately, `ReorderIndexes` is not exported in Ionic's `index.ts`. Therefore I have to import it in the following way:
```
import { ReorderIndexes } from "ionic-angular/components/item/item-reorder";
```

**Expected behavior:**
I would prefer to import it just by (like any other Ionic structure):
```
import { ReorderIndexes } from "ionic-angular";
```

**Steps to reproduce:**
see above

**Related code:**
see above

**Other information:**
none

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v4.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time we do not have any plans to make that class public, so I am going to close this issue for now.
