### ISSUE TITLE
ion-content no-bounce when content bigger than screen size

### ISSUE THREAD

**Issue by pvaltorta** [driftyco/ionic#10329]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using tag
`<ion-content padding class="page" no-bounce>...</ion-content>`
When content fits screen size, I have no bounce as expected.
When content is bigger than screen size, so I have vertical scroll, cannot disable bounce.
Already set
```
<preference name="webviewbounce" value="false" />
<preference name="UIWebViewBounce" value="false" />
<preference name="DisallowOverscroll" value="true" />
```
in config.xml
I have this bug on IOS 8-9-10

**Expected behavior:**
I think that when using attribute "no-bounce", bounce should be always be disabled.

**Steps to reproduce:**
Create a new page and add html content bigger than screen size, for example a big image.

-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this.

**Comment by mhartington** [comment]
This is due to how we set inertia scrolling on the content.

https://github.com/driftyco/ionic/blob/master/src/components/content/content.scss#L41-L41

We set it on the main content regardless. With this property set, we get smooth scrolling, but it also produces a bounce when the content overflows.

We could move the `-webkit-overflow-scrolling: touch;` to  [here](https://github.com/driftyco/ionic/blob/master/src/components/content/content.ios.scss#L58-L59), but that would mean that scrolling would become choppy 

![scrolling](https://cloud.githubusercontent.com/assets/2835826/22703136/1be13a12-ed31-11e6-8f6b-91e83a6ec8d6.gif)


In the gif I'm just toggling the touch-overflow handle via the dev tools. 
Not a fan of the choppy scrolling without it.

**Comment by peterpeterparker** [comment]
@mhartington is right, if you remove or set to auto -webkit-overflow-scrolling, then the scrolling not gonna be smooth anymore on iOS

I tried many different solutions, so far none really worked for the bounce effect on iOS.

But the following solution, adapted to Ionic and for a special view, allowed me to at least block the bounce effect when the top or the bottom of the over scrolled page is reached

http://stackoverflow.com/a/16898264/5404186

    @HostListener('touchstart', ['$event'])
    handleTouchStart(event: any) {
        this.allowUp = (this.content.scrollTop > 0);
        this.allowDown = (this.content.scrollTop < this.content.scrollHeight - this.content.contentHeight - this.content.contentTop);
        this.prevTop = null;
        this.prevBot = null;
        this.lastY = event.targetTouches[0].pageY;
    }
   
    @HostListener('touchmove', ['$event'])
    handleTouch(event: any) {
        let up: boolean = (event.targetTouches[0].pageY > this.lastY), down: boolean = !up;

        this.lastY = event.targetTouches[0].pageY;

        if ((up && this.allowUp) || (down && this.allowDown)) {
            event.stopPropagation();
        } else {
            event.preventDefault();
        }
    }

**Comment by lukezona** [comment]
I think this is a quite big problem. I'm trying to find a workaround to this because my fab and maps moves and creates glitches when the ion-content bounces..

Any idea?

**Comment by mhartington** [comment]
@lukezona you should be putting the fab outside the ion-content.

This is how iOS behaves with scrolling. 
The inertia scrolling is part of how the platform behaves

**Comment by peterpeterparker** [comment]
@mhartington The inertia scrolling is part of how the iOS platform behaves when it goes to browsing the web using Safari (for example). But on the other hand, content in ("native") apps on iOS doesn't bounce, therefore could you plz reopen this issue?

**Comment by pvaltorta** [comment]
@mhartington I agree with @peterpeterparker: bounce is ok when browsing a web page, but in app it should not be a standard behaviour. When developing native apps in XCode, UIScrollView has an option to enable or disable bounce. Smooth scrolling is standard in IOS, while bounce is an option.

**Comment by adnan333bd** [comment]
I have a hacking fix ... that worked for me
the no-bounce on ion-content does work if you place a ion-refresher (if you dont have already) that does not do anything ... in one of my view I had ion-refresher and no-bounce worked, so I tried in another view where content is larger the screensize. please do the following ...

`<ion-content (tap)="tapped()" class="message-content" no-bounce>
    <ion-refresher (ionRefresh)="doRefresh($event)">
    </ion-refresher>
.....`

in ts file ... 

`doRefresh(refresher) {
    refresher.complete();
  }`

**Comment by peterpeterparker** [comment]
@adnan333bd thx for the idea. tried it, unfortunately in my case this hack didn't worked, there was still a bounce effect

**Comment by dmnunez** [comment]
Hi @peterpeterparker did you find the solution I'm facing same problem! all my content bounces when scrolling

**Comment by peterpeterparker** [comment]
@dmnunez no, never found a proper solution :(

**Comment by thezakman** [comment]
So there is no current fix for this?
All my pages that are bigger than the screen still have the bounce.

**Comment by mhartington** [comment]
Hi there! The bounce is part of how iOS handles overflow scroll. It cannot be disabled. This was not present in Ionic 1 due to Ionic 1 using JS Scrolling over native overflow scrolling. I will be locking this issue and it not something that can changed on our end. Thanks!

**Comment by dmnunez** [comment]
@thezakman maybe no, I couldn't find a fix
