### ISSUE TITLE
Ionic2 - Initial loading time 

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#10325]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After one of the big maintained thread:  #6776 got closed because it derailed I would like to open a new one because this issue still exists and I can't see any change (specially after announcing 2.0.0).

I've ported my app from Ionic Version 1 to Version 2 where I see a big difference between the loading times.

Pixel XL (Android 7)
Version 1:  3.5 s
Version 2: 5seconds

HTC One M8 (Android 6)
Version 1: 4.5 seconds
Version 2: 7.5 seconds

iPad Mini 2 (iOS 8)
Version 1: 2.5 seconds
Verison 2: 5 seconds

Lumia 550 (Windows 10):
Version 1: Not existing
Version 2: 9s (and more)

All Version 2 were build with the `--prod`

So you already told us, that there will be a big part of tree shaking but this process is not that transparent to me (or I think to other users aswell) how the actualy progress is ongoing and if this problem is still in work or actually on hold because of other tasks (like you mentioned in your release post) 

I hope this topic won't get flooded like the old once because I realy would like to keep track of this big part.

Loading of an app is realy a crucial point in all apps, no one wants to wait 7 or more seconds until the app starts.

**Expected behavior:**
The same startup time or even a reachable goal like in version 1.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

Thanks in advance 
Graphefruit

**Comment by bobrosoft** [comment]
https://github.com/driftyco/ionic-app-scripts/issues/685

**Comment by qiujiahong** [comment]
I have the same problem.

**Comment by Sh1d0w** [comment]
Yeah the initial loading time of Ionic 2 framework is really bad currently :(

**Comment by mhartington** [comment]
@graphefruit this is something that we are aware of and are constantly working on.
As I stated in the previous issue, it's a moving target and something we are well aware of. 
Work is being done to improve things and reduce the amount of JS that is being sent to the device.

While we appreciate your concern and the information you have provided (we really do ❤️ ), a new issue is not really needed, as this is something we are already aware of.
