### ISSUE TITLE
Feature : resize content animation

### ISSUE THREAD

**Issue by TomDemulierChevret** [driftyco/ionic#10327]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Expected behavior:**
It would be nice to be able to specify an animation duration to the Content method "resize" (same as the the scroll methods).
Currently it looks a bit choppy when you resize the content if your header height has changed.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic and really appreciate the feature request! As this is not something we plan on doing anytime soon I am going to close this for now and move it to our internal feature tracking repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#21

**Comment by gianpaj** [comment]
@jgw96 that feature request repo seems gone.

I would like to request something similar for the resize method
