### ISSUE TITLE
when i run in android device 4.2.2 coming  this below issue

### ISSUE THREAD

**Issue by chandumunna** [driftyco/ionic#10323]
<img width="508" alt="screen shot 2017-02-06 at 11 09 33 am" src="https://cloud.githubusercontent.com/assets/3447677/22635884/21fb5358-ec5d-11e6-87c2-01bc5b082fd2.png">
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by graphefruit** [comment]
Ionic2 won't run on 4.2, minimum requirement is 4.4.
If you need to support 4.2 have a look on "Crosswalk" https://github.com/crosswalk-project/crosswalk

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
