### ISSUE TITLE
Relaunching app after exitApp() taking very long time to load

### ISSUE THREAD

**Issue by tushar-velingkar** [driftyco/ionic#10328]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using platform.exitApp() to exit the app on back button press.
The app goes into background and when I try to relaunch the app it takes very long time and UI also not proper.

**Expected behavior:**
Splash screen should not take long time and UI should not be misplaced on relaunch after exitApp() 

**Steps to reproduce:**
Needs physical device

**Other information:**
issue occurs when using --prod flag to run the app

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Thanks for opening an issue, we will take a look into this.

**Comment by jgw96** [comment]
Hello! We are working very hard on improving the start up time of an Ionic app. In fact, the next release is all about improving the start up time. Because this is a constant goal for us I am going to close this issue for now. Thanks for using Ionic!
