### ISSUE TITLE
Please update npm package "ionic-sdk"

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#10338]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
npm package ionic-sdk is very outdated (old version of ionic 1.x vs newer version of ionic 1.x)

**Expected behavior:**
npm package ionic-sdk should be updated to a newer version of ionic 1.x

**Steps to reproduce:**
Install npm package ionic-sdk

**Related code:**

```
npm install --save ionic-sdk
```

**Other information:**
Every ionic package (2.x and cloud, and ofc angular as well) have been ported from bower to npm, but the npm port of ionic-sdk isn't been synced with the bower legacy one.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We do not currently use the ionic-sdk namespace anymore. You can find all versions of Ionic, including Ionic 1 from the `ionic-angular` npm package. So for example, to install the latest version of ionic 1 you would run `npm install ionic-angular@1.3.2 --save`.

**Comment by Zorgatone** [comment]
@jgw96 Great, thanks!
Maybe you should deprecate the package and add a disclaimer in the description on npm to inform the users :)
