### ISSUE TITLE
Object Dom Window has no method  __Zone_Symbol__requestAnimate frame 

### ISSUE THREAD

**Issue by waleediqbal1** [driftyco/ionic#10336]
Error coming when i run command (ionic run android -ls) .. i have created my first ionic2 app and on browser its working good but when i deploy it on emulator it gives this error after splash screen . can any one please guide me that whats going wrong with it ... i have search allot but haven't got any proper answer .. please help me in this issue ..... Thanks 
![error](https://cloud.githubusercontent.com/assets/24951301/22682213/68885aec-ed33-11e6-95d6-5a26e10e0fce.png)

my package.json is ...

{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "sw-toolbox": "3.4.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "cutePuppyPics: An Ionic project"
}

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We do not currently support Android 4.1.1 with Ionic 2. To use Ionic 2 on a device running Android 4.1.1 you will need to use [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview). Also, and this is just advice, i would recommend considering the fact that Android 4.1.1 only has [4 percent market share](https://developer.android.com/about/dashboards/index.html) and is fast decreasing before adding crosswalk to your app. While crosswalk is a great project it will make your apk's faster and on device running 5.0 and up (which is the majority of the marketshare in android now) you will not get the benefits of the auto updating chrome webview.

**Comment by waleediqbal1** [comment]
Thanks sir for answer . Please tell me one thing that i have download and installed ionic2 demo project and run that on same device and its running now so what things do that have because of which it is running on my same emulator and cell too on which this above shown application is not running ...
![packagejson](https://cloud.githubusercontent.com/assets/24951301/22769420/49aab57a-eeaa-11e6-8fa1-b297f6d5f536.png)
.

**Comment by mtayyip** [comment]
Hi I have installed crosswalk but wait after slash screen white screen
![ekran alintisi](https://user-images.githubusercontent.com/17318742/28057437-cb546990-6628-11e7-9cef-88e8f4d1bc5a.PNG)
