### ISSUE TITLE
Design problem using segments

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#10337]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I need to use segments on a dinamically generated array.
It works fine - but there is a design problem. 
The content of the first segment is showed properly - but then the content of the second segment is showed with a margin-top of 44px (as if they were on the same page and it would be under the previous content.)
And so on for the content of the next segment.

**Expected behavior:**
Since I am using segment - I would expect each content to be at the top

**Steps to reproduce:**
You can check this Plunker:

http://plnkr.co/edit/huhnzvcCrBBxmU4qb9BL?p=preview

I have reproduced the two possibilites:

1. When the content is dynamically generated you can see the design issue
2. When there is static content - it is all fine (this part is commented out in the plunker)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by FrancescoMussi** [comment]
Well good news.
Probably was just my fault - using wrongly the design elements in the view.
Using span for the ngFor of the content fixed the issue.

You can check it out here:

http://plnkr.co/edit/SxD51LXlvSjOE2JztiDT?p=preview

So probably is not an actual design issue.
In that case sorry for the disturb!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As it looks like this was an issue with your custom functionality I am going to close this issue for now. Thanks!
