### ISSUE TITLE
datetime ,it should be wider for both sides

### ISSUE THREAD

**Issue by NamelessChen** [driftyco/ionic#10335]
**Ionic version:**  (check one with "x")
[ ] **2.2.1**
![1486450123 1](https://cloud.githubusercontent.com/assets/12457060/22680764/bbcce52c-ed44-11e6-840a-5165feda028c.png)

datetime ,it should be wider for both sides

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that follows our [guidelines](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#creating-an-issue). Thanks for using Ionic!
