### ISSUE TITLE
Documentation/new developer issues

### ISSUE THREAD

**Issue by YasharF** [driftyco/ionic#10332]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
These are mostly documentation issues that can improve the new developer experience on day 0:
- On page http://ionicframework.com/getting-started an instruction seems to be missing due to webpage rendering: For going from Step 2 to 3, the dev needs to actually go in the project folder by `cd myApp` and when the page at http://ionicframework.com/getting-started renders (in Chrome, haven't tried other browsers) the field is too small and the `cd myApp` doesn't show up.  See screenshot at:  http://imgur.com/6aK28vh
- On the right side of Step 3 at http://ionicframework.com/getting-started , if the user clicks on "Deploying guide" he will end up with a 404 error instead of getting to the Deploying guide.
- If the new developer goes to Documentation (http://ionicframework.com/docs/)  and then starts from the first step "Introduction", they end up with "Installing Ionic" and the next button at the bottom sends the user into the "tutorial" which is good.  But there seems to be a missing part for a hello world on a device, as the tutorial starts going over the project structure, etc. for getting everything in the browser.  The last page of the tutorial puts the user in "Ionic 2 API Docs".  At that point, if the developer goes back in the browser to figure out hello world on the device on their own, and tries the "Deploying" in the left nav bar, and then tries to follow the instructions, when they get to Running Your App step instruction "ionic run android --device" under "Android Devices" section instead of ending up with a running tutorial app on the device as expected, they will get an error "Error: No platforms added to this project. Please use `cordova platform add <platform>`."
- Fix https://github.com/driftyco/ionic-cli/issues/1376 .  A new developer following the getting started guide/tutorial ends up with warnings that their tooling is not the right version and is out of date, even though they just installed everything brand new.

**Expected behavior:**
A smooth flow for a user to follow the documentation and get started with a hello world.

**Steps to reproduce:**
Start from a brand new dev system, install node, and try to get started with Ionic by following what is listed at http://ionicframework.com/getting-started

**Related code:**
N/A

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
N/A
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#989

**Comment by YasharF** [comment]
Thank you

**Comment by jgw96** [comment]
@YasharF No problem (:
