### ISSUE TITLE
Angular dependencies ^2.3.0

### ISSUE THREAD

**Issue by pkegashira** [driftyco/ionic#10339]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  }
```

**Expected behavior:**
```
  "dependencies": {
    "@angular/common": "^2.3.0",
    "@angular/compiler": "^2.3.0",
    "@angular/compiler-cli": "^2.3.0",
    "@angular/core": "^2.3.0",
    "@angular/forms": "^2.3.0",
    "@angular/http": "^2.3.0",
    "@angular/platform-browser": "^2.3.0",
    "@angular/platform-browser-dynamic": "^2.3.0",
    "@angular/platform-server": "^2.3.0",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  }
```

**Other information:**
for me this is a matter of life and death, so many tools and libraries i need to use along side this awesome framework, but am always met with that unmet peer dependency guy in npm.

any roadmap, release date would greatly be appreciated.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. The timeline on this is literally asap haha (: . We are internally testing with the latest version of Angular as we speak, so we hope to have this update out soon.

**Comment by pkegashira** [comment]
literally checking this everyday i come to work :) just cant wait :p
