### ISSUE TITLE
IOS build to iTunesConnect: `Missing Info.plist key`

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic#10334]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've updated my ionic to the latest version 2.0.0. But when I try to upload a build on iTunes connect using xcode, I'm getting an email from the saying:

````
Dear developer,

We have discovered one or more issues with your recent delivery for "(the name of my app)". To process your delivery, the following issues must be corrected:

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team
````

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by karlpatrickespiritu** [comment]
Sorry. Seems because I installed cordova-plugin-camera (`$ ionic plugin add cordova-plugin-camera`) and the `Info.plist` was missing the `NSPhotoLibraryUsageDescription key`. Uninstalling worked fine. Thanks.
