### ISSUE TITLE
Move all hardcoded components text to Config

### ISSUE THREAD

**Issue by pavel-kurnosov** [driftyco/ionic#10333]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Text in Select component, Alert component, Datetime component and etc.. for buttons like "Cancel", "Done" hardcoded in class. 

**Expected behavior:**

If text will not be hardcoded will be easy to change language for app.

**Steps to reproduce:**

Open any component like - Select component, Alert component, Datetime component.
Example to solve issue - I think easiest way to solve it - use Config same way as it is done for - "backButtonText".

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by lwz7512** [comment]
you can use Config instance like this: http://ionicframework.com/docs/v2/api/config/Config/
the value used can be dynamically set through config.set() also.

**Comment by pavel-kurnosov** [comment]
@lwz7512 I know how to use config. My proposal was to move hardcoded values for buttons from Components to config, like it is done for "backButtonText", or use more general way for all hardcoded text in framework. This will help translate project to other language.

**Comment by jgw96** [comment]
Hello! Thanks for the idea here. I'm going to move this issue over to our internal list of feature requests/ideas for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
