### ISSUE TITLE
Crashing on UWP/Windows and iOS since 2.0.0

### ISSUE THREAD

**Issue by tfrenken** [driftyco/ionic#10347]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Since update to 2.0.0 our app still runs fine on Android but on UWP and iOS the app simply crashes on startup. 

On windows phone we get (in VS2015 debug mode)
SCRIPT5022: Exception was thrown at line 1, column 8373 in ms-appx-web://de.oldntec.veranstaltungsapp/www/build/polyfills.js
0x800a139e - JavaScript runtime error: 2
polyfills.js (1,8373)

On iOS (started via XCode, debugged via Safari):
EXC_BAS_ACCESS (code=1, address=....) in JavaScriptCore "llint_slow_path_handle_exception". The start of the stack trace seems to be in JSC::arrayProtoFuncJoint(...)

**Expected behavior:**
App should start on all platforms (did before). Since the errors are rather generic / javascript-related, I assume this is a more general issue with the new release?

**Steps to reproduce:**
None, yet.

**Related code:**
Our package.json:
{
  "name": "our-app",
  "author": "we",
  "homepage": "https://www.ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "ng2-translate": "^5.0.0",
    "pouchdb": "^6.1.2",
    "xml2js": "^0.4.17",
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"    
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "Our app"
}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Windows PC (running Android and UWP app)
Cordova CLI: 6.4.0                   
Ionic Framework Version: 2.0.0       
Ionic CLI Version: 2.2.1             
Ionic App Lib Version: 2.2.0         
Ionic App Scripts Version: 1.0.0     
ios-deploy version: Not installed    
ios-sim version: Not installed       
OS: Windows 10                       
Node Version: v6.9.3                 
Xcode version: Not installed         

Mac (running iOS app):
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2 Build version 8C38

**Comment by graphefruit** [comment]
Did you build the solution with `ionic build ios --prod` ?

**Comment by tfrenken** [comment]
We have built the Windows app with "ionic build windows --arch=ARM" and "ionic build ios". Afterwards we loaded the projects in VS2015 and xCode and debugged them in the devices / emulators.

**Comment by graphefruit** [comment]
Build them with the `--prod` flag, maybe the issue will disappear.
The problem when you don't build it with the `prod` command, the execution of the app will need +15-20 seconds, because it will dynamically bootstrap when app is started.

So give it a short.
`ionic build windows --archs=arm --prod`
`ionic build ios --prod`

For me explanation look here: https://github.com/driftyco/ionic/issues/6776#issuecomment-267700539

**Comment by tfrenken** [comment]
OK, no problem and thanks so far!

 I'll be back in the office tomorrow and give it a try then and report back. However, android works and I do not use the prod-flag there. Additionally, we defined 
<preference name="loadUrlTimeoutValue" value="600000" />
in config.xml. As far as I know this should bypass the problem with the long startup times?

Question: During deployment, VS/XCode will probably recompile the project. Do I have to place the prod-flag somewhere there as well?

**Comment by graphefruit** [comment]
Maybe your android device is fast enough, all of my old android devices keep crashing when starting the app without --prod.

The `--prod` flag will give you a faster startup time because of the `ngc` etc, but actualy the ionic team is still on this, have a look here: https://github.com/driftyco/ionic-app-scripts/issues/670

Because your question: If you don't change something inside your `.ts` files or something else in the `app-folder` you don't need to place the `--prod` flag somewhere, because the recompile of the project doesn't effect the `www`-Folder where everything is stored after building.
So short term: No you don't just use `--prod` when you changed your code, else you're free to go.

**Comment by tfrenken** [comment]
Thank you so much for taking the time and giving the detailed description. It really makes sense due to you explanation that the missing prod-flag may be our problem. I will report back lates on Friday if the issue was resolved! Thanks again!

**Comment by tfrenken** [comment]
Hi! We compiled for both systems again today using the prod-flag. Allthough the apps started much much faster atferwards, the errors did not go away. Still the android version runs perfectly, but windows and apple version crash immediately after launch with these very strange error mentioned above.

Any ideas on this? We cannot be the only once experiencing such error - are we?

**Comment by graphefruit** [comment]
Try to set up a complete new testapp.
`ionic start mytestproject` and have a look if it's working.

Else you can reinstall Cordova and ionic and npm just to make sure everything is really up to date.

If still the sample app keeps crashing then it looks like your ionic setup isn't right.
Also make sure that you don't run the app on iOS7 because just 8 and higher is supported.
Also make sure you choose UWP in Visual Studio as startup project.

**Comment by graphefruit** [comment]
Update: If the app runs with the new created test project it could be also a problem with your plugins. (TS, js or Cordova plugins) so maybe try to add them step by step in the test project afterwards.

Also make sure you're running the build command with:
`ionic build....` because if you do `cordova build...` it would crash aswell (I already stumbled on this issue myself)

**Comment by tfrenken** [comment]
Hi. We managed to get the project working again by first following your recommendation to create a new project and then copying over all the code one by one. However, in the end the new project worked with exactly the same plugins etc. So we performed a "ionic state reset" on the old project and now all platforms are working again. I do not really understand what happened here but it's working again.

Thanks for your help!

**Comment by tfrenken** [comment]
Hi again. I have to re-open the issue since the problem returned after only a day. So after "ionic state reset" both, UWP and iOS, worked well. We made different changes on the code and were able to build and run the code several times.

Yesterday, we just changed one line of code, added an "if (this.platform.is("ios") ...", and suddenly the problem returned on iOS. We immediately reverted the change but the problem persists. Every time we run the code we get an EXC_BAS_ACCESS error (building works). Resetting the state again did not work this time. We also created a new project and copied over the original code (which worked last time after the reset) but it does not work as well. 

Any other ideas on this? This issue is so strange and so hard to track since the error is so general.

**Comment by graphefruit** [comment]
Hmm I know this problem while building with Xcode.
Have you tried to set:
`chmod -R 777 /your/Directory`?
Sometimes XCode has problems when building cause of lacking rights (the issue should look in another way but maybe it could help aswell).

Also:
1. Maybe try it on a new pc.
2. Delete ionic and npm completely and do a fresh start
3. Check if you're running with `sudo su` `ionic...` -> I just run with sudo rights because I had to much problems without
Greetings

**Comment by graphefruit** [comment]
Update this issue fits also on your message:
https://issues.apache.org/jira/browse/CB-9102 (Websocket issue)?
It wouldn't explain why it crashes on Windows Phone aswell but maybe a hint.

Also it would be interesting: Does it happen just with your codebase or also when you're creating a complete new dummy-project?

**Comment by tfrenken** [comment]
Hi. We followed your ideas and did:
1) chmod and build with sudo - no change
2) Deleted node.js / npm and the project, installed everything again - no change
3) Changed to WKWebview using the recommended plugin (https://github.com/driftyco/cordova-plugin-wkwebview-engine) - leads to a crash as well but with a different error message (however, the plugin is know to be rather buggy so far when reading through the issue tracking)
4) Created a new empty project and compiled it - works (but our project did for a certain time as well, so do not know if this is really a result which tells us something usable).

Well, we are totally out of ideas. The confusing thing is that last time a "ionic state reset" solved the issue (and still is solved for UWP - the error did only return on iOS) and this time it does not work.

**Comment by graphefruit** [comment]
For checking:
On which machine are you compiling? Did you try to transfer your project to another machine?
Maybe the PC is doing some crazy things noone can explain?

Maybe check aswell:
1. You're using npm 6.x right?
2. If a new empty project works, outcomment all plugin references (ionic plugin ad...) and just copy your app folder, and have a look if this code is working and can be compiled?
For me it looks like a problem with any used plugin.
3. maybe paste your used plugins here (ts, js and ionic/cordova)

**Comment by tfrenken** [comment]
Hi. Unfortunately, we do only have one machine with iOS. 

Regarding your questions:
1) I assume you refer to node.js - node.js has version 6.9.5., npm is 3.10.10
2) My colleague is working on this right now
3) "ionic plugin list" says
`                      cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"
phonegap-plugin-push 1.9.2 "PushPlugin"`

config.xml is
`  <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.1" />
    <plugin name="cordova-plugin-console" spec="1.0.5" />
    <plugin name="cordova-plugin-statusbar" spec="2.2.1" />
    <plugin name="cordova-plugin-device" spec="1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="phonegap-plugin-push" spec="~1.9.2" />
    <plugin name="phonegap-plugin-barcodescanner" spec="~6.0.5" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.1" />
    <plugin name="cordova-plugin-geolocation" spec="~2.4.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.6.1" />
    <plugin name="de.appplant.cordova.plugin.local-notification" spec="~0.8.4" />
    <plugin name="cordova-plugin-sqlite-2" spec="~1.0.4" />
    <plugin name="cordova-plugin-camera" spec="~2.3.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-file-transfer" spec="~1.6.1" />
    <engine name="windows" spec="~4.4.3" />
    <engine name="android" spec="~6.0.0" />
    <allow-navigation href="http://192.168.178.133:8100" />
    <icon src="resources\android\icon\drawable-xhdpi-icon.png" />
    <plugin name="cordova-plugin-file" spec="~4.3.1" />`

package.json is
`  "dependencies": {
    "ng2-translate": "^5.0.0",
    "pouchdb": "^6.1.2",
    "xml2js": "^0.4.17",
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"    
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],`

4) I checked all of them. They should be compatible.

**Comment by tfrenken** [comment]
Hi again. My colleague copied over the whole sry-folder into the newly created project. He had to add "ng2-translate" and then could successfully build the project. When running, the app was deployes but crashed afterwards due to missing plugins. He is just manually reinstalling all the plugins.

**Comment by graphefruit** [comment]
I would try to comment out the lines of code where the plugins are needed, to make sure one of the plugins is the problem.

**Comment by tfrenken** [comment]
OK. So after installing all the plugins, the app crashes again with the same error. Uncommenting all the code where we use plugins will be a lot of work. The app is already rather huge and we use a lot of plugins as you can see above. However, I guess we have no other chance but to follow the execution flow of the app and comment in one line after the other...

**Comment by graphefruit** [comment]
Looks like, but you could do it 50%/50%.

Just out comment 50% maybe the one which less impact.
Then you see which side is failing on your part.

Maybe I can try to help you a bit:
```
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-google-analytics 1.7.4 "Google Universal Analytics Plugin"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
de.appplant.cordova.plugin.email-composer 0.8.2 "EmailComposer"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.2 "PushPlugin"
```
All this plugins are working normal on my side.

So I'd go with this once:
```
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"
```
Also try to update your appscripts to: `1.1.2`
Also I've never seen this config entries:
```
 <plugin name="cordova-plugin-camera" spec="~2.3.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
 
    <engine name="windows" spec="~4.4.3" />
    <engine name="android" spec="~6.0.0" />
```

Maybe it could be also a problem with your intents and your access properties:
I've set following in my config.xml:
```
  <access origin="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
```

Best of luck

**Comment by tfrenken** [comment]
Hi. Wow, thanks for investing so much time in this!

Two new facts:
1) We found out that the code is still working perfectly in the iOS emulator, no crashes there
2) The problem seems to be related to calling NavController.setRoot. Calling this for the second time, kills the app every time with the mentioned error - first time works. 

Mybe this issue is related? https://github.com/driftyco/ionic/issues/5883

Regarding the plugins in question:
1) cordova-plugin-app-event 1.2.0 "Application Events" - no longer using this, so just removed it
2) cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin" - no longer using this, so just removed it
3) de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification" - using but already worked before, but is a candidate
4) phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner" - the part where we are using this is actually the only part of the app that works at the moment (we have a button on the start page that calls the plugin directly and that works, clicking on any other link kills the app)

We updated to app-scripts 1.1.2.

Regarding the config entries in question:
```
 <plugin name="cordova-plugin-camera" spec="~2.3.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
```
It is recommended to use these entries by the plugin developers (https://github.com/apache/cordova-plugin-camera#ios-quirks).

```
<engine name="windows" spec="~4.4.3" />
    <engine name="android" spec="~6.0.0" />
```

We removed these. Dunno where they came from.

Our access properties are totally the same.

After updating the app-scripts, removing the 2 plugins in question, and removing the two engine-entries, we issued an "npm install" and built again. Nevertheless, the app crashed again. So no luck so far.

We decided to get our heads clear over the weekend and start again on Monday. We will revert to the last know working code, create a new project and copy over blocks of code until the crash happens again, No better idea left.

Thanks so far and have a nice weekend!

**Comment by graphefruit** [comment]
So.
I just runned my app on iOS 8 - Real device.

So I'm setting my root aswell.
I've tried both versions:
1.  `this.rootPage = page.component;`
2. `this.nav.setRoot(page.component)`

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by graphefruit** [comment]
@tfrenken Welcome back to Monday ;).

After you said this it works in Emulator I remembered that you can attach Safari Browser to your real device and see the logs.
Also you could try to add inside the `index.html`
```
     window.onerror = function (_error) {
            return true;
        }
```
And alert the error here.
This should help that your app doesn't crash at all if its an JavaScript error.

Best of luck

**Comment by tfrenken** [comment]
Hi. Thanks again. This day started (and continues to be) as frustrating as the last week ended.

We already use the Safari log for viewing the app's output. However, since the crash is very deep inside the system, only XCode itself shows a real error message - EXC_BAD_ACC (which is why the problem is so hard to debug).

Your code above does not work. The app still crashed (I guess since the crash comes from deep in the system and is not propagated to the browser window).

We updated our libs this morning (npm outdated and set most libs to Version 2.4.8). The crash when navigating does no longer happen (pages are changed) but Splashscreen stopped working and our pages do not fully load their content. We are just thinking about which libs provide a better chance for success.

**Comment by graphefruit** [comment]
Alright, so I'm running out of ideas aswell.

As it looks likes its no NPM issue because then it wouldn't even run in the emulator at all.
Maybe its because the app is compiled for 32 bit and not 64 bit? 

So does it still crash while startup or when pressing a button like you wrote in last post?

Maybe you could write an own plugin for IOS to catch issues global (don't know if this is possible, I'm no native developer) and show the exception message.

After my code didn't work it realy looks like a native code issue, because I already used this code to prevent my app from crashing.

Maybe it could be also an problem with your XCODE? Try to downgrade / upgrade your Xcode. (http://stackoverflow.com/questions/22783541/workaround-for-phonegap-exc-bad-access-on-getdeviceinfo)

**Comment by tfrenken** [comment]
The crash currently only happens when issuing a navigation (setRoot, push. root = xxx - does not mapper how we start the navigation, it crashes - but still only on ios, android and windows work). However, we still see some log messages in the javascript console in Safari from the new page before the stacke trace pops up in XCode. Frist, we thought this may be related to content of the page we started the transition to but even if we navigate to an totally empty page, the app crashes. 

Since the app worked for about 3-4 hours with EXACTLY (we have a git commit with the working code which we already pulled into a new project) the same code as we currently have and we did not change the XCode version since then, I always come back to the idea that the system / macbook is somehow in an incosistent / errornous state. We are shortly before buying new hardware simply to eliminate this variable.

**Comment by tfrenken** [comment]
Good morning. Small update: When we activate the flight mode on the iphone, the app does not crash on navigating but does not navigate at all. Code was not changed.

**Comment by graphefruit** [comment]
@tfrenken If you don't want to spam this thread (after this has already got closed by Ionic), I could propose an E-Mail communication aswell.

I don't exactly know yet how Angular2 is built with the components, but for me it looks like if you activate your Flightmode, a plugin tries to connect and this results into a bad_exc?

Maybe you could exclude all pages and just have 2 dummy pages but still with all plugins installed, and have a look then aswell.

For me the main plugin to look ta would be the `cordova-plugin-network-information`: http://stackoverflow.com/questions/26790729/ios8-phonegap-cordova-network-information-app-crashes

**Comment by tfrenken** [comment]
We removed the cordova-plugin-network-information but still the app crashes. ARC is activated.

Yes, let's change to email and I will post the end of the discussion here again in case someone has a similar problems and searches for a solution (assuming we ever find one).

**Comment by graphefruit** [comment]
lars.saalbach@googlemail.com post me ;)
