### ISSUE TITLE
Calling the .length() function of Slides returns undefined error

### ISSUE THREAD

**Issue by slzr** [driftyco/ionic#10341]
Ionic 2.0.0 - Bug Report
Calling the `.length()` function of Slides returns `undefined `error
![alt text](http://i.imgur.com/0zgf8pT.png "Logo Title Text 1")

**Comment by mhartington** [comment]
How/when are you calling it? Could you reproduce this in a plunkr?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
