### ISSUE TITLE
Ability to create readonly elements that can be selected by users

### ISSUE THREAD

**Issue by robdmoore** [driftyco/ionic#1034]
I have a requirement for an app I'm building to have an area on the screen that is readonly, but the user can select in order to use the copy command.

As per #421 at the moment you can only select text in form elements and contentEditable divs so I propose that there is a way to add a control where you opt in to allowing selection.

I'm more than happy to implement it and send through a PR, but some initial brainstorming on the best approach to opt in (or letting me know if you have a fundamental objection to it) would be great before I start.

**Comment by malixsys** [comment]
Kludgy, but I use something like this for desktop:

      .directive('selectable', [function () {
        return {
          restrict: 'A',
          priority: 2000,
          link: function (scope, ele, attrs) {
            var element = ele[0];
            function keydown(){
              element.blur();
              element.setAttribute('contenteditable', 'false');
            }
            function mouseDown(){
              element.setAttribute('contenteditable', 'true');
            }
            element.addEventListener('mousedown', mouseDown);
            element.addEventListener('keydown', keydown);
            ele.on('$destroy', function () {
              element.removeEventListener('mousedown', mouseDown);
              element.removeEventListener('keydown', keydown);
            });
    
          }
        };
      }]);

**Comment by zchking** [comment]
Does this discussion has a final conclusion? I think most of us need this function, is there any way to get the ability back to select and copy the text which belong to web browser.

**Comment by dhcar** [comment]
+1 I'm in the same boat as @zchking

**Comment by malixsys** [comment]
I think you are left with contentEditable until @adamdbradley and friends give us a way to patch it...

**Comment by johnrobertcobbold** [comment]
+1 also needing this

**Comment by dhcar** [comment]
For those that have just entered or may be searching this plugin http://ngcordova.com/docs/plugins/clipboard/ is helpful if you want to implement similar functionality via a button

**Comment by Sidd27** [comment]
We Just need the text to be selectable not editable that's why we can't use contenteditable property of HTML and in normally we can copy any content but in ionic i think you guys have made it that none of text is selectable. Please provide solution other the below which doesn't require ionic.js changing 
https://forum.ionicframework.com/t/how-to-make-text-selectable/4384

**Comment by dleric** [comment]
I got it working without modifying ionic.js.

The trick is to replace text you want to be able to select with input field with attribute `readonly`. Ionic doesn't prevent click/touch events from input fields so you don't have to modify ionic.js. However, you'll need to set `user-select:text` to enable text selection.

Check the whole code here:
https://forum.ionicframework.com/t/how-to-make-text-selectable/4384/25
