### ISSUE TITLE
Dots spinner shows extra lines on iOS

### ISSUE THREAD

**Issue by fikkatra** [driftyco/ionic#10355]
**Ionic version:** 
[x ] **1.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
When using the 'dots' spinner with ionicLoading, the svg shows tiny 'lines' right below or next to the last dot. This only occurs on iOS. See screenshot.

![spinner](https://cloud.githubusercontent.com/assets/8104336/22740546/8f7ed864-ee10-11e6-8571-076ab8ca4579.png)

**Steps to reproduce:**
Create an ionic app based on the code below (or use the plnkr). I also have an Ionic View app which I can share.
Note: this issue ONLY occurs in a 'real' iOS app. It does not occur in the plunkr, not even when run in Safari on iOS.

Plunker:
https://plnkr.co/edit/JcDkKbjL4CmqUJJIorMz?p=preview

**Related code:**
app.js:
```
app.constant("$ionicLoadingConfig", {
    template: "<ion-spinner icon=\"dots\"></ion-spinner>"
});
```
controller:
```
.controller('HomeCtrl', function($ionicLoading) {
  $ionicLoading.show();
})
```
custom styles:
```
.loading-container .loading {
  background-color: transparent;
}

.spinner {
  stroke: #fff;
  fill: #fff;
}

.spinner svg {
  width: 96px;
    height: 96px;
}

.backdrop {
  background-color: #222;
}
```

**Ionic info:**

```
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v5.5.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by jgw96** [comment]
Hello, sorry just realized this was an Ionic 1 issue, because of this I am going to be moving it to our v1 issues repo. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#205
