### ISSUE TITLE
Ionic2 - Feature/Performance - CSS changes

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#10351]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The generated main.css file is actually about 20k lines long.
After I've digged a little into the builded main.css I saw, that when building for Android-Platform, the stylesheets for iOS aswell as for WP are inserted.

This results into a big css file which needs to be parsed by the browser.

Specialy old browsers and Windows-Phones have problems to parse big css files.

**Expected behavior:**
Not rather expected but a proposal: 
Would it be possible to let the users choose when building the app, if they realy need the other stylessheets included?
E.g.
`ionic build android --prod --cleancss`

Also I could think about expanding this feature in removing unused components.
So if someone doesn't use the tabs component, the css for tabs wouldn't be needed at all.
This could be grabbed dynamically (regex) or the user could config all components he's definitely not using?

Also a flattenedstylesheet would decrease the startup time of an app aswell.

Thanks in advance & Greetings
Graphefruit

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#111
