### ISSUE TITLE
Production build for browser not working properly

### ISSUE THREAD

**Issue by rousek** [driftyco/ionic#10359]
**Ionic version:**  2.0.0 final

**I'm submitting a**  bug report

**Current behavior:**
Something is wrong with ionic build browser --prod. It seems that Angular "forgets" to update view.  I have implemented drag and drop using [style.transform] directive and it seems to skip the part when it promotes changes to DOM. Using "ionic serve" is fine.

**Expected behavior:**
It should be working the same way as when compiling JIT, even better.

**Steps to reproduce:**
1. Compile for platform browser in production mode.
2. Search for bugs.

**Ionic info:**:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

In these files you can find export from Google DevTools timeline. I was doing the exact same thing when recording these and yet they differ so much.

[ionic serve](https://ufile.io/87269)
[ionic build browser --prod](https://ufile.io/49d891)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
