### ISSUE TITLE
(feat) Sass variables for Slide Component

### ISSUE THREAD

**Issue by ramoncarreras** [driftyco/ionic#10350]
**Ionic version:**
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**
Currently there is absolutely no sass variable to customize styles of ionic-slides component and her swipper-pagination.

**Expected behavior:**
Can change (for example):
- ion-slides background color.
- swipper-pagination position. (top-left, top-center, top-right, bottom-left, bottom-center, bottom-right)
- swipper-pagination-bullet inactive color.
- swipper-pagination-bullet inactive opacity.
- swipper-pagination-bullet active color.
- swipper-pagination-bullet active opacity.
- ...

**Ionic info:**:
> Cordova CLI: 6.5.0
> Ionic Framework Version: 2.0.0
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.0.0
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.11
> OS: macOS Sierra
> Node Version: v7.1.0
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#112
