### ISSUE TITLE
is this slides code a mistake?

### ISSUE THREAD

**Issue by lcya86** [driftyco/ionic#10364]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
#
https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L388

Does it should be
```
touchEventsTarget =  'container';
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out and follows our [guidelines](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#creating-an-issue) please. Thanks for using Ionic!
