### ISSUE TITLE
SyntaxError:Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by SmallShrimp** [driftyco/ionic#10367]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**other:**
when run in android 
runtime error :
error message: SyntaxError:Unexpected strict mode reserved word
but when run in browser is success!

**Comment by SmallShrimp** [comment]
can i remove "use strict";

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out and follows our [guidelines](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#creating-an-issue) please. Thanks for using Ionic!
