### ISSUE TITLE
Slides - Can't set slidesPerView to a float number

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#10362]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I can't set slidesPerView to 2.33, however, before refactoring slides, it was working perfectly !

**Expected behavior:**
It should accept float numbers not only integers

**Steps to reproduce:**
You may add `slidesPerView="2.5"` attribute to `ion-slides` you'll not be able to see 2.5 slide !

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a

```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out and follows our [guidelines](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#creating-an-issue) please. Thanks for using Ionic!
