### ISSUE TITLE
bug: Tab page go to child page cant pop

### ISSUE THREAD

**Issue by HonLuk** [driftyco/ionic#10365]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>when a page push form tab page.i try to pop back to tabPage use android back button.but canGoBack() function return false when i use it.
code here:
 this.nav.canGoBack() ? this.nav.pop() : this.tryExitApp();
//this alway return false when i press android back button try to pop this page.But in fact this page can go back to tabPage</span>

<span is-issue-template></span>

**Comment by HonLuk** [comment]
full code here:
`if (this.platform.is('android')) {
                this.platform.registerBackButtonAction(() => {
               
                    let activePortal = this.ionicApp._modalPortal.getActive() || this.ionicApp._overlayPortal.getActive();
                    if (activePortal) {
                        activePortal.dismiss();
                        activePortal.onDidDismiss(() => {
                        });
                        return;
                    }
                    if (this.menu.isOpen()) {
                        this.menu.close();
                        return;
                    }
                    return this.nav.canGoBack() ? this.nav.pop() : this.showExit()
                }, 1);
            }`
can someone give me help~

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out and follows our [guidelines](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#creating-an-issue) please. Thanks for using Ionic!
