### ISSUE TITLE
Service workers precache

### ISSUE THREAD

**Issue by mbj36** [driftyco/ionic#10369]
Hello Ionic team
 
I am building a PWA with ionic 2 and would love to get help on it 
 In my service-worker.js we have default inbuilt code 

`self.toolbox.precache(
  [
    './build/main.js',
    './build/main.css',
    './build/polyfills.js',
    'index.html',
    'manifest.json'
]);`

These are the list of files to be cached which is default, but i want to cache the `home` directory which is inside  `pages` directory which contains three files home.ts, home.scss and home.html 

When i add these three files inside above precache list, console shows - Failed to find resource!  

How can i cache those files ?

**Comment by Daskus1** [comment]
They should be already bundled together in your `main.js` and `main.css`.
When you run ionic build, all your components and pages are going to be minified and bundled into one big file (you `main.js`).

**Comment by jgw96** [comment]
Hello, thanks for using ionic! As @Daskus1 mentioned above, when you build your app all your components are compiled and bundled into the main.js file and all the css is compiled into the main.css file. This is the reason we cache these files instead of the individual component files.
