### ISSUE TITLE
Cannot find ** some ** typescript .ts files when debugging in Chrome

### ISSUE THREAD

**Issue by 97bytes** [driftyco/ionic#10375]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm developing withe latest version of Ionic2 and using Chrome for debugging. In some cases, *some Typescript clases* (not all!) are not displayed in Chrome for debugging. I also checked that they are not included in the "/buil/main.js" file. I seems that the compilation process can't find those clases unless they are **explicitly instantiated** in the code. 

My solution: I added a new "Init" class that explicitly instantiates (with fake params) all classes in the application and doing so, solves the issue. 

Is there any way to force the compilation of all clases defined in the app? 

**Expected behavior:**
I expected all classes to be compiled and be available for debugging (even if they were not explicitly instantiated in the application)

**Steps to reproduce:**
I don't have a short example to reproduce this.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.6
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#732
