### ISSUE TITLE
ionic build fails on IOS

### ISSUE THREAD

**Issue by KevinBurton** [driftyco/ionic#10373]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic build fails because ios platform was not added
ionic platform add ios indicates that the ios platform was already added. But subsequent ionic build works just fine. So it appears that even though the platform was already added you must do 'ionic platform add ios' in order to get ionic build to generate a different build error
```
[08:24:28]  ionic-app-scripts 1.0.0 
[08:24:28]  build dev started ... 
[08:24:28]  clean started ... 
[08:24:28]  clean finished in 6 ms 
[08:24:28]  copy started ... 
[08:24:28]  transpile started ... 
[08:24:31]  transpile finished in 2.63 s 
[08:24:31]  webpack started ... 
[08:24:31]  copy finished in 2.74 s 
[08:24:39]  webpack finished in 8.08 s 
[08:24:39]  sass started ... 
[08:24:40]  sass finished in 658 ms 
[08:24:40]  build dev finished in 11.40 s 
Error: Source path does not exist: resources\android\icon\drawable-hdpi-icon.png
```
**Notice** that I am **not** building an android application.

**Expected behavior:**
build the application

**Steps to reproduce:**
ionic build 
ionic platform add ios

**Related code:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1912
