### ISSUE TITLE
$ressource getting old data

### ISSUE THREAD

**Issue by Mdhaker** [driftyco/ionic#10384]
I am calling an external web service via $resource.get(), when i make change in the webservice back-end and recall the $resource.get with pull to refresh it gets the same old data.

does $resource store cache by default ? what is the proper way to clear that cache ?

this is the portion of code where i call the web service : 

![image](https://cloud.githubusercontent.com/assets/22690712/22821866/3f7b5eb4-ef7d-11e6-89af-674352220d0c.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
