### ISSUE TITLE
Many page in app from remote server.

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#10385]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hello. I have got in my app many pages 25+. And in components I load templates from remote urls. After the app starts, ionic trying to load all pages at the same time. So I got 25+ queries to server before the platform is ready. So how to prevent this load. I want to make my app load only first start page, and then after click load next and etc.
How to do this? Do you have any feature? Or settings?

Example of page:
```
@Component({
  templateUrl: APP_CONFIG.appDomain + '/mobilesiteapp/template/?path=app/app'
})
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
