### ISSUE TITLE
form element output events not documented well

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic#10383]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

I wanted to listed to value change events on an `ion-input`, and in my naivety pasted a `ionChange` event from an `ion-select` in, which turned out incorrect. After failing to find the right option in the [docs](https://ionicframework.com/docs/v2/api/components/input/Input/), ~~~I learned it was `valueChange` [here](https://github.com/driftyco/ionic/blob/cc21f93b87f243970290e92f4393e813aaa6b7a9/src/components/input/native-input.ts).~~~
~~~Questions:~~~
~~~- why isn't information from this `native-input` mentioned in the docs (for in as far as I can see)?~~~
~~~- why do the event names seem inconsistent?~~~
~~~- considering the event names have confusing distinctions, might it be an idea to document these (contrasting the differences and patterns) in a doc page?~~~
Edit: I'm getting the impression the docs were right there is not event to catch value changes on an `ion-input`. If that's the case then I suppose the docs are correct there, although I would find it surprising.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#991
