### ISSUE TITLE
Build process halt 

### ISSUE THREAD

**Issue by qiujiahong** [driftyco/ionic#10382]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[* ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ *] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I use "ionic build android --release --prod" to build my APK file.  But the build process stopped.
![image](https://cloud.githubusercontent.com/assets/3654923/22819212/0a645a94-efac-11e6-9301-36e138feab09.png)

**Expected behavior:**
Build success. I got the APK file.

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
![image](https://cloud.githubusercontent.com/assets/3654923/22819324/8bb94d20-efac-11e6-8c6f-e4b2fc0f97a6.png)
```
D:\apps\ion2FullApp-PRO-version>ionic build android --release --prod

> ion2-fullapp-PRO@ ionic:build D:\apps\ion2FullApp-PRO-version
> ionic-app-scripts build "--release" "--prod"

[15:51:55]  ionic-app-scripts 1.0.0
[15:51:55]  build prod started ...
[15:51:55]  clean started ...
[15:51:55]  clean finished in 13 ms
[15:51:55]  copy started ...
[15:51:55]  ngc started ...
[15:52:36]  ngc finished in 41.21 s
[15:52:36]  webpack started ...
[15:52:37]  copy finished in 42.07 s
[15:52:59]  webpack finished in 22.73 s
[15:52:59]  uglifyjs started ...
[15:52:59]  sass started ...
WARNING: [Bourbon] [Deprecation] `em` is deprecated and will be removed in 5.0.0.
Backtrace:
        node_modules/bourbon/app/assets/stylesheets/functions/_px-to-em.scss:7, in function `em`
        node_modules/bourbon/app/assets/stylesheets/functions/_modular-scale.scss:21

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.
Backtrace:

…… （long logs）

[15:53:16]  autoprefixer: <css input>:139895:3: You should write display: flex by final spec instead of display: box
[15:53:16]  autoprefixer: <css input>:140075:3: You should write display: flex by final spec instead of display: box
[15:53:16]  autoprefixer: <css input>:140396:3: You should write display: flex by final spec instead of display: box
[15:53:17]  sass finished in 18.01 s
[15:53:17]  cleancss started ...
[15:53:35]  uglifyjs finished in 36.26 s

```

**Comment by qiujiahong** [comment]
I have been waiting for serial hours . And finally it was done.
![image](https://cloud.githubusercontent.com/assets/3654923/22827790/91b5fb9c-efd4-11e6-99d2-800c5f34ca52.png)

And I am glad to see the that the boot up time is much more faster than before .
But the time is still too long.
Is that a way to solve it?

**Comment by graphefruit** [comment]
Did you try compiling a starter app? 
It looks like you have some custom plugins inside your project.
Would be interesting if its slow without any customization aswell.
Also check your firewall/antivirus system, that they are not blocking and maybe run on Admin context.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
