### ISSUE TITLE
Crosswalk is discontinued , and there is no alternative

### ISSUE THREAD

**Issue by v3ss0n** [driftyco/ionic#10397]
https://lists.crosswalk-project.org/pipermail/crosswalk-help/2017-February/002411.html

Should we start building chromium for android our own?

**Comment by graphefruit** [comment]
This is really not an ionic issue.

**Comment by v3ss0n** [comment]
ionic have crosswalk built in

**Comment by graphefruit** [comment]
It hasn't crosswalk is added by yourself via the plugin management. Just the sample app uses crosswalk.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Crosswalk is not built into Ionic, instead it is a seperate plugin that you can add to your Ionic app if you would like. To explain why this does not really affect the average Ionic app we first need to look at android version marketshare. Ionic 2 runs on android all the way back to 4.4.2 without crosswalk just fine. If we look at the [Android Dashboard](https://developer.android.com/about/dashboards/index.html) we can see that android < 4.4.x is about 11% and dropping fast. So the amount of android devices that wont be able to run your app without crosswalk is about 11% of devices worldwide. Another thing to remember here is that you can check your statistics in google play to see which versions of Android your users are using. For all 3 of my apps I have 0 installs on Android below 4.4.2 and the majority of installs coming from android 6.x.x and 5.1.1 . Finally, the last thing to remember here is that you can still use crosswalk, it just wont be updated anymore. So if you do have users on versions of Android below 4.4.x then you can still use crosswalk!
