### ISSUE TITLE
Crosswalk WebView on Android KitKat 4.4.2 very lame

### ISSUE THREAD

**Issue by ramogundogdu** [driftyco/ionic#10390]
[ ] **1.x**
[x] **2.x**

[ ] bug report
[x] feature request

**Current behavior:**
Crosswalk WebView on Android KitKat 4.4.2 very lame. The app with Crosswalk WebView on Android 4.4.2 is so slow. The App works without Crosswalk WebView perfect. What could be the problem?

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed

```

```
    <plugin name="cordova-plugin-crosswalk-webview" spec="~2.3.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
    </plugin>

```

**Comment by graphefruit** [comment]
I couldn't recognize this problem with my app build with crosswalk.
Have you already checked it with the starter app from ionic, if you see the issue here aswell?
Also it would be good if you could provide a video showing the laggy/slowness like a button press, or tab swap.

**Comment by ramogundogdu** [comment]
try to download the ionic-conference app https://github.com/driftyco/ionic-conference-app an install it on your Anrdoid 4.4.2 Device. I saw the issue with ionic-conference aswell as with my own app on the device.

**Comment by graphefruit** [comment]
Older phones are always slower, the question is what specific is slower on your side, thats why a video showing it with and without crosswalk would be very helpful.

I'm just running my project with Crosswalk and it has a pretty good performance

**Comment by ramogundogdu** [comment]
I dont' have also any problem on others older devices with crosswalk. I have just on Anrdoid KitKat 4.4.2 this issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
