### ISSUE TITLE
FormBuilder errors cause silent application reload

### ISSUE THREAD

**Issue by VsMaX** [driftyco/ionic#10391]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There is no error whatsoever when formControlName doesn't match name in FormBuilder definition. **Instead the whole application reloads.**

**Expected behavior:**

Some error indication about no form control with given name would be nice. I can even post pull request myself, I guess this is easy fix, just need some hint where the problem might be.

**Steps to reproduce:**
While developing with 

> ionic serve

Create form with control 

`<ion-select> `that has property **formControlName different than the one defined in FormBuilder in Page constructor**.

After navigating to the screen, **the whole ionic application will reload**.

**Related code:**
HTML: 

```
<form [formGroup]="signUpForm" (ngSubmit)="onRegisterButtonClick()">
    <ion-grid>
      <ion-row>
        <ion-item class="item-input">
          <ion-label floating color="light">select book</ion-label>
          <ion-select formControlName="items" placeholder="select book">
            <ion-option *ngFor="let book of bookList" value="{{book.id}}">
              {{book.name}}
            </ion-option>
          </ion-select>
        </ion-item>
      </ion-row>
      <ion-row>
        <ion-item>
          <ion-label floating color="light">login</ion-label>
          <ion-input formControlName="username" name="username" [class.invalid]="!signUpForm.get('username').valid && (signUpForm.get('username').dirty || submitAttempt)"></ion-input>
        </ion-item>
      </ion-row>
      <ion-row>
        <ion-item>
          <ion-label floating color="light">password</ion-label>
          <ion-input formControlName="password" name="password" type="password" [class.invalid]="!signUpForm.get('password').valid && (signUpForm.get('password').dirty || submitAttempt)"></ion-input>
        </ion-item>
      </ion-row>
      <ion-row center text-center>
        <ion-col>
          <button ion-button type="submit" class="button-transparent">
          REGISTER
        </button>
        </ion-col>
      </ion-row>
    </ion-grid>
  </form>
```

page constrctor:

    this.signUpForm = formBuilder.group({
      username: ['', Validators.compose([Validators.maxLength(30), Validators.required])],
      password: ['', Validators.compose([Validators.maxLength(30), Validators.required])],
      books_changed_name: ['', Validators.required]
    });

    this.bookList = [ { id: 1, name: "book1"}, {id: 2, name: "book2"} ];

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2 Build version 8C38

**If someone can point me to the place where FormBuilder validations are taking place I might be able to fix it myself.**

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Does this same behavior affect a normal angular 2 app? We do not do anything different as far as forms go from a normal Angular app.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
