### ISSUE TITLE
bug: android build failed - apache commons Base64

### ISSUE THREAD

**Issue by francosang** [driftyco/ionic#10408]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>ionic build android fails

Output:
What went wrong:
Execution failed for task ':packageDebug'.
org/apache/commons/codec/binary/Base64

It happends with every proyect, I supouse it is a problem in my development enviroment.

Steps to reproduce:
ionic start --v2 myApp tabs
cd myApp
ionic platform add android
ionic build android

This also fails with the same output:
cd platforms/android
gradlew.bat clean build

I also tried with gradle 2 and 3, not using the wrapper.

But if I open the android proyect with Android Studio it works!

May be this is a problem with the apache commons codec dependency.

Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed</span>

<span is-issue-template></span>

**Comment by francosang** [comment]
compile group: 'commons-codec', name: 'commons-codec', version: '1.10'

Adding the gradle dependency is not working.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
