### ISSUE TITLE
.platform-android CSS Tags not working

### ISSUE THREAD

**Issue by peterbetos** [driftyco/ionic#10401]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
.platform-android5_0 { } CSS Tag doesn't work on Ionic2

**Expected behavior:**
The tag was expected to work as per this forum:
https://forum.ionicframework.com/t/platform-version-specific-css/79162

**Steps to reproduce:**
Add the following code on theme/variables.scss:
```
.platform-android5_0 {
  ion-header {
    margin-top: 20px;
  }
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will take a look into this.

**Comment by jgw96** [comment]
Hey @peterbetos , are you on an android 5.x device when you run into this issue?

**Comment by peterbetos** [comment]
I have an Android 6.0 device. It seems to work with this one:

```
.platform-android6 {
  ion-header {
    margin-top: 20px;
  }
}
```

How about needing to anticipate succeeding android versions? Do I need to create a CSS entry for other Android versions? Below tag doesn't work on Android 6:

```
.platform-android5 {
  ion-header {
    margin-top: 20px;
  }
}

```

**Comment by peterbetos** [comment]
Since the CSS tag is working on the individual versions of Android, we can close this in the meantime. Thanks.
