### ISSUE TITLE
VirtualScroll does not work (Error: No provider for Content)

### ISSUE THREAD

**Issue by rudyhuynh** [driftyco/ionic#10406]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Everytime I use virtualScroll in the template, there's a runtime error: No provider for Content

**Expected behavior:**
VirtualScroll works without runtime error.

**Steps to reproduce:**
http://plnkr.co/edit/8EoejUT5BKTfMrwsOD9h?p=preview (see error in console)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I have made a plunkr [here](http://plnkr.co/edit/paAZMG94pNT3zlZ5CF5c?p=preview) that shows how to use VirtualScroll. VirtualScroll and 99% of our other components should always be used in an `ion-content` .

**Comment by rudyhuynh** [comment]
Hi @jgw96 , thanks for quick response.
I just wraped the virtualScroll element in <ion-content>, also wrap <ion-content> in an fixed height <div>, but then I come to this error: No provider for ViewController.
Actually, I'm integrating ionic 2 into ionic 1. And my component is downgraded into angular1 component. Is there anyway work around?

**Comment by Ross-Rawlins** [comment]
What is the correct way to import and use virtual scroll in a component. I am getting an intermittent error where it doesnt load the data after a page transition so I want to all the read update function. I know this is not a bug but I want to run the update to confirm a bug does not exist.
