### ISSUE TITLE
"activated" class when click not injected on android

### ISSUE THREAD

**Issue by mbelnicoff** [driftyco/ionic#10407]
I have a list of divs, with click in each one.

Every time I click one element ionic add "activated" class.

This works in ios but not in android,

Is someone having the same problem?

thanks.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mbelnicoff** [comment]
I think is an issue, I've already made lot of tests, upgrade ionic to last version, and 'activated' class injection only works on ios, not in android.

Maybe, the way I posted, confused you.
