### ISSUE TITLE
Make ion-select dismissable outside the component

### ISSUE THREAD

**Issue by misha130** [driftyco/ionic#10414]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When opening a select it is impossible close it unless you click on the alert ok/cancel buttons.

**Expected behavior:**
The open() could return the overlay object(ViewController) which is presenting the alert or the object may be made public in the class rather than just be accessible only in the open function locally.

**Steps to reproduce:**
1) Try to open a select that should close after 5 seconds if the user doesn't click.

2) Try to create a select without the ok/cancel buttons

**Related code:**

An excerpt from src/components/select/select.ts and how I want it to be

    overlay.present(selectOptions);

    this._isOpen = true;
    overlay.onDidDismiss(() => {
      this._isOpen = false;
    });

    return overlay;

**Other information:**

The amount of sheer acrobatics to solve this myself:
http://stackoverflow.com/questions/40925172/how-to-avoid-ok-cancel-button-in-ion-option-ion-select/42193005#42193005

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#119
