### ISSUE TITLE
bug: Memory leaks between views

### ISSUE THREAD

**Issue by adamgalmor** [driftyco/ionic#10416]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I noticed a memory leak when I'm moving between the views of my app.
So I've created a clean Ionic 2 temple tab project ("ionic start --v2 myApp tabs") without any additional code and noticed it to leaks when I switch between tabs:

![image](https://cloud.githubusercontent.com/assets/2060170/22877183/d48dfd5c-f1dc-11e6-9a90-b70b898fb387.png)

I saw others posted related topics but without a solution:
* https://forum.ionicframework.com/t/memory-leaks/10036?source_topic_id=79322
* https://github.com/driftyco/ionic/issues/1096#ref-issue-40172100

We are at the final stage before releasing our enterprise application and we will appreciate your quick response.

P.S
This is my relate ionic forum post URL:
https://forum.ionicframework.com/t/memory-leaks-between-views/79322</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look into this.

**Comment by adamgalmor** [comment]
FYI
This is an allocation timelines snapshot of my app after pushing and poping a view from the navController:

![image](https://cloud.githubusercontent.com/assets/2060170/22932018/7ff8c918-f2cf-11e6-8c46-ecfc32fc85db.png)

**Comment by manucorporat** [comment]
Working in this right now!

**Comment by manucorporat** [comment]
I have a fix for this memory leak!
