### ISSUE TITLE
Tap / click registered twice on iOS10

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#10419]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
In iOS 10, every tap registered twice, causing various issues.

**Expected behavior:**

Tap events are fired only once. 

**Steps to reproduce:**

1. Download the attachment
2. Run `npm run`, `ionic platform add ios` then `ionic run ios --device`
3. Open the Safari developer tools and connect it to the phone
4. Tap the search icon and see that the functions called twice, and keyboard flashes
5. Tap the "Test Me" text, and notice it runs twice

[Example.zip](https://github.com/driftyco/ionic/files/771345/Example.zip)

Extra: run `p.searchClicked()` from the console and see the keyboard opening works fine if the `searchClicked` function is called only once.

**Other information:**

N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will take a look into this!

**Comment by NoNameProvided** [comment]
Thanks for the reply! Does this mean the confirmation of the buggy behavior?

**Comment by graphefruit** [comment]
@NoNameProvided That doesn't mean a confirmation. It just means that Ionic will take a look on it, and after that they'll report to you back if they could reproduce it or if they need a plnkr etc.
