### ISSUE TITLE
White screen when pressing hardware back button in Android build

### ISSUE THREAD

**Issue by karthiga-p** [driftyco/ionic#10410]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The android build is working fine but when i tap hardware back it shows a blank white screen if I tap it again i.e., twice it goes to the previous screen perfectly. I don't have this problem with the back button inside the app. 

**Expected behavior:**

 Load Previous screen

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
