### ISSUE TITLE
bug: Network.onConnect fires when app goes offline

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#10412]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>When I set the phone into flight mode, I only ever get the onConnect() called, and never the onDisconnect().

Using the following code to test...

Network.onDisconnect().subscribe(() => {
      this.logger.debug('network was disconnected ');
      this.onOnlineStatusSubject.next(false);
    });

    Network.onConnect().subscribe(() => {
     this.logger.debug('network connected!');
     
     // If we have any problems here, see doco where they put in a delay before examining network type
     this.onOnlineStatusSubject.next(true) ;
    });</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1068
