### ISSUE TITLE
ionic slide-box problems

### ISSUE THREAD

**Issue by L-Matthew** [driftyco/ionic#10411]
When I use the slide-box, slide can not slide unless I refresh the page

**Comment by cozzbie** [comment]
Can you please show a snippet of your code or make a plunkr? @L-Matthew

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by L-Matthew** [comment]
@cozzbie  This is a snippet of my code 
<ion-slide-box slide-interval=2000 auto-play="true" does-continue="true">
			<ion-slide>
				<div class="box"><img src="img/carousel1.png" style="width: 100%;height: 120px" /></div>
			</ion-slide>
			<ion-slide>
				<div class="box"><img src="img/carousel2.png" style="width: 100%;height: 120px" /></div>
			</ion-slide>
			<ion-slide>
				<div class="box"><img src="img/carousel3.png" style="width: 100%;height: 120px" /></div>
			</ion-slide>
		</ion-slide-box>

**Comment by L-Matthew** [comment]
![default](https://cloud.githubusercontent.com/assets/25046048/22958387/ec61114c-f369-11e6-819d-369edd34681b.PNG)
@cozzbie

**Comment by L-Matthew** [comment]
@cozzbie I'm so sorry for I did not reply to you right away

**Comment by cozzbie** [comment]
Is this Ionic 1 or 2? @L-Matthew

**Comment by L-Matthew** [comment]
Ionic 1 @cozzbie
