### ISSUE TITLE
this.platform.width()/height() return 0 with "--prod" build

### ISSUE THREAD

**Issue by PatrickCSFan** [driftyco/ionic#10413]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

this.platform.width() & this.platform.height() return 0 with the "--prod" build command on Android device.

e.g. the API return correct value if built with 
`ionic build android `

e.g. the API return 0 if built with 
`ionic build android --prod`

**Expected behavior:**

Both production build and dev build should be returning the correct value

**Steps to reproduce:**

**Related code:**

```
ngAfterViewInit() {
    this.platform.ready().then(readySource => {
      console.log(this.platform);
      console.log(`this.platform.width() : ${this.platform.width()}`);
      console.log(`this.platform.height() : ${this.platform.height()}`);
    });
 }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by PatrickCSFan** [comment]
We are currently workaround this problem by calling window.innerWidth/Height directly

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look into this.

**Comment by ZiFFeL1992** [comment]
Can you try with content?

Here is the doc: http://ionicframework.com/docs/v2/api/components/content/Content/

**Comment by ghenry22** [comment]
I see the same issue in both dev and prod builds on ios.

window.innerWidth/Height returns correct results as @PascalPrecht mentioned.

the platform methods were working for me pre 2.0.0 release not sure exactly when they broke as I only just noticed myself.

**Comment by jgw96** [comment]
Hello all! This has since been fixed and is in the [latest release](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#310-2017-04-26).

**Comment by ghenry22** [comment]
Yes these seem to work for me currently.

Gaven


________________________________
