### ISSUE TITLE
Slide bug

### ISSUE THREAD

**Issue by ArrayBuffer** [driftyco/ionic#10420]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I use Slide component in my home page as following:

ts:
export class HomePage {
	@ViewChild('Slides') slides: Slides;
	constructor(){
		
	}
	slideChanged() {
    	let currentIndex = this.slides.getActiveIndex();
    	console.log("Current index is", currentIndex);
  	}
}

html:
	<ion-slides (ionSlideDidChange)="slideChanged()">
		<ion-slide style="background-color: green">
			<h2>Slide 1</h2>
		</ion-slide>
		<ion-slide style="background-color: blue">
			<h2>Slide 2</h2>
		</ion-slide>
		<ion-slide style="background-color: red">
			<h2>Slide 3</h2>
		</ion-slide>
	</ion-slides>

I have only three <ion-slide>, the index of slides should be 0,1,2. but it show number 3 sometimes.
**Expected behavior:**

the index of slides should be 0,1,2

**Steps to reproduce:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
