### ISSUE TITLE
bug: ionViewDidEnter / onViewDidLeave incorrect order

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#10427]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a Ionic application based off of the sidemenu template. When I enter the **same page** again, (ie reselect it from the side menu), the `ionViewDidEnter` fires before the `ionViewDidLeave`. Should these be the other way around?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by pjc2007** [comment]
Apologies, I was using this.. http://ionicframework.com/submit-issue.
Perhaps this is out of date, I'l go straight o Gitbub and raise there.

Cheers
