### ISSUE TITLE
Missing style in ion-datetime when value is invalid

### ISSUE THREAD

**Issue by rpayanm** [driftyco/ionic#10425]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When the value in ion-datetime is invalid don't show a line red (border-bottom).

**Expected behavior:**
Show a line red.

![selection_035](https://cloud.githubusercontent.com/assets/6087454/22904032/dfe1c702-f208-11e6-962f-0d0f130ef2ee.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v6.9.5
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually the correct behavior as this is how inputs, including date inputs, work on native and in plain angular 2 apps. You can use [Angular Forms](https://angular.io/docs/ts/latest/guide/forms.html) to tweak when an input is not valid or not in your app.
