### ISSUE TITLE
is there anyway to use traditional web style for select component on mobile platform?

### ISSUE THREAD

**Issue by zjx** [driftyco/ionic#10428]
we noticed the select component will be changed to native style on some mobile platforms for example, android. We want to make a consistent user experience so need to use the web styled dropdown on these mobile devices.

curiously want to know if there is anyway to config this?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
