### ISSUE TITLE
ionViewDidEnter / ionViewDidLeave fire the wrong way around when you re-enter the same page

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#10429]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a Ionic application based off of the sidemenu template. When I enter the same page again, (ie reselect it from the side menu), the ionViewDidEnter fires before the ionViewDidLeave. Should these be the other way around?

**Expected behavior:**
I would have thought we'd get the `ionViewDidLeave` followed by the `ionViewDidEnter`

**Steps to reproduce:**
Use `this.navController.setRoot(<current page>);` to go back to the current page

**Related code:**
Just hit the Test button..

http://plnkr.co/edit/2yRPr4

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by manucorporat** [comment]
This is the expected behaviour since the ionViewCanEnter is being dispatched in the new Page, ie. a difference instance of the same Component, but it is still a different page.
