### ISSUE TITLE
Ionic 2 pages constructors and Leaflet

### ISSUE THREAD

**Issue by fuyangli** [driftyco/ionic#10424]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Since the pages on Ionic 2 are always constructed (using navigator.setRoot) I wondered why it keeps the html rendered. 

I'm using Leaflet on the Home Page of my app. If I use setRoot to load the home page, leaflet constructor acuses the element being already initialized.

**Expected behavior:**
I imagined that if the page is constructed every single time it is called, the html state of it should be empty at that point!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
