### ISSUE TITLE
How to separate build.js file after compile?

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#10436]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

I got App on Ionic 2. I'm new with webpack and want to solve the problem. Problem is - How to create 2 separated files after compile? First it must be build.js with all js files, but exclude js files in my src folder. Second must be app.js with all js files in my src folder, but exclude js files of Angular, Ionic and etc.

How to do this? 

Now it's create only one file build.js in www folder which is include Angular 2, Ionic 2, my files and all other libraries.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
