### ISSUE TITLE
platform pause() and resume() don't support core (pwa)

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10433]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
My goal is to do logic when user enter the app, and when he leaves.

When subscribing to:
```
this.platform.resume.subscribe(() => { });
this.platform.pause.subscribe(() => { });
```
it works well on Android, but doesn't perform any action in a web browser (PWA), chrome.

**Expected behavior:**
platform resume() and pause() methods should work in browser too

**Related code:**

```
this.platform.resume.subscribe(() => { console.log(" This will appear only in Android//iOS. nothing at chrome") });
this.platform.pause.subscribe(() => { console.log(" This will appear only in Android//iOS. nothing at chrome") });
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! In the browser their is no concept of `resume` and `pause` like their is in the cordova world so this logic will not work in the browser. For more info i would recommend asking [on the Cordova bug tracker](https://issues.apache.org/jira/browse/CB/).

**Comment by amreladawy** [comment]
Hi,
Sorry for bringing this back on. But the concept of `resume` and `pause` is applicable on core platform when the tab is visible or not.  The [Page Visibility API](https://www.w3.org/TR/page-visibility/) describes that. 

I think it would be a valuable thing that Ionic would fire the `pause` and `resume` events for core platform as well.

**Comment by kustrun** [comment]
Hi!

Are there any plans to support this `resume` and `pause` control on HTML5 and PWA application. It would be very useful for all users. I believe @amreladawy has provided a nice solution for this problem.

Thank you for your help.
