### ISSUE TITLE
need deepLinker support query string link

### ISSUE THREAD

**Issue by Jimmysh** [driftyco/ionic#10432]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Can deepLinker support query string for PWA?

```
{ component: ItemPage, name: 'item', segment: 'item/:id' }
```

```
this.navCtrl.push('item', { id: 1, other: 2, other3: 3 })
```

now URL like http://xxx/item/1

I want the URL is: http://xxx/item/1?other=2&other3=3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
