### ISSUE TITLE
back button with deeplink

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#10438]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I build SPA & hybrid app use Ionic2,
current it's works great but back button.
and I use deeplink for mobile web page.

when I goto sub page.
the back button will go out the app

I think it should do like this.

when previous page isn't in the app
go main page `http://xxx.com/`
else go back,

the previous page can get use `document.referrer`

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
