### ISSUE TITLE
No logs,no html elements on safari remote debugging with a connected iphone

### ISSUE THREAD

**Issue by msio777** [driftyco/ionic#10437]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I can't remote debug app on ios device with safary. I can see under Develop my device a I connect to it but no logs or html elements are shown. 

**Expected behavior:**
logs and html elements should be shown if device is connected to safari on mac

**Steps to reproduce:**
I build application with `ionic build ios` and then I go to Xcode, open project, choose my connected iphone and run it. later I open safari and choose my iphone from develop menu.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
