### ISSUE TITLE
nav-clear in sidemenu breaks navigation

### ISSUE THREAD

**Issue by michaelkrog** [driftyco/ionic#1043]
If i have sidemenu (abstract state: menu), a page (state: menu.page) and a subpage (state: menu.page.subpage) and I use nav-clear on links in the sidemenu to disable animations when the links are clicked in the sidemenu, then subsequent navigation seems to break.

The way I see it is:
- animations between views no longer happen.
- back buttons disappear.

I made a codepen here: http://codepen.io/anon/pen/HLaDu/

Try to go to subpage and then back. It works fine - back and forth several times. But as soon as I open the sidemenu and click the link to go to close the menu again, then it is broken.

If I remove nav-clear from the link in the sidemenu, then things works fine - but leaves me with the animation-between-views problem which nav-clear was supposed to fix.

(Using beta 1)

**Comment by karvapallo** [comment]
I think this issue has been re-introduced in ionic 1.0.0 or 1.0.1 (updated from RC5) in a way. Now I have a situation where in the left navigation i have a href to `#/posts` which is fine. So when on that page and I click this `#/posts` href to 're-open' the page I'm already on and then on that page click to the comments section, which is `#/posts/:postId/comments` now this comments opens up as the root page (no animation and hamburger icon on the left upper hand corner.) But if I click to a user's page `#/users/:userId` this does not happen. So somehow ionic sees as `#/posts/:postId/comments` as being the same page we are already on, and doesn't issue an animation.

**Comment by SimonRiis** [comment]
I too have this problem with nav-clear. 
I have a list of events, if i click one it navigates to it, i then click on the menu "Burger" and it opens the side menu, i click on events and it again shows me a list of events if i click one of these events the backbutton is removed and i can only open the side menu not go back.

**Comment by violet7** [comment]
+1

**Comment by mhartington** [comment]
This is fixed in the nightly builds. 

http://codepen.io/mhartington/pen/KpbQVd

**Comment by karvapallo** [comment]
Oh great, I'll check that out. Thank you!

**Comment by violet7** [comment]
Thank you.

**Comment by fengliliu** [comment]
有点牛逼
