### ISSUE TITLE
Android release cordova plugins not always loaded

### ISSUE THREAD

**Issue by soniyj** [driftyco/ionic#10449]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Cordova plugins not loaded when you close and open the app different times.
Ionic Deploy not injected and it's always undefined.
This doesn't appear on android debug but only on release.

**Expected behavior:**
To work normally as it does in debug version.

**Steps to reproduce:**
- Create an ionic v2 app side menu
- Add some cordova plugins, eg. Onesignal
- Build for release and install on an android device
- Open and close the app different times

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by soniyj** [comment]
Sorry but in which way it is a support question? This is a problem with your building system. If I build the app without the --prod and --release flag, the app works perfectly and all plugins are loaded correctly.
