### ISSUE TITLE
Enable different package names / bundle ids per platform

### ISSUE THREAD

**Issue by tfrenken** [driftyco/ionic#10442]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic seems to ignore the widget:packageName config params from cordova (http://cordova.apache.org/docs/en/latest/config_ref/index.html). Thereby, all platforms either have the same bundle it or the widget:id config param in config.xml needs to be changed in order to have different. That is especially annoying when building for UWP since Microsoft has a strange naming convention for their packages which is very uncommon for typical package names on the other platforms. 

**Expected behavior:**
Config param widget:packageName should be used in config.xml as done by Cordova.

**Steps to reproduce:**
Put this in config.xml:
<widget id="packagename.android" version="0.5" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" packageName="packagename.windows">

Manifest for UWP app will have "packagename.android" as package name instead of "packagename.windows".

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.3
Xcode version: Not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1917
