### ISSUE TITLE
Radio option selection issue on IOS - 10.2

### ISSUE THREAD

**Issue by varun-bansal** [driftyco/ionic#10440]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Sometimes After selecting the option from the available radio buttons, the binding variable in the template is not updated in the template. I am using angular version 1.3.13.

**Expected behavior:**
Selecting a radio option should update the binding variable in form.

**Steps to reproduce:**

http://plnkr.co/edit/nwk9dtOVBZy4P26JSHH8?p=preview
I have added a sample code to give you an idea of how we have implemented our code but we are not able to reproduce every time we try. We have a video and a screenshot depicting the issue that occurred. Issue only occurs on ios 10.2 devices, we have found the issue on iphone 5/6s.
**Other information:**

Screenshot of the issue: https://drive.google.com/open?id=0BywABUsLPa4AMkRoYlpzNTFuZ0E
Video depicting the issue: https://drive.google.com/open?id=0B8zXVeTfYECYY3JjbHdEVHBZTnc

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v4.2.6
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#208
