### ISSUE TITLE
Header is displayed incorrectly when page is pushed from a modal

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic#10443]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.0.1

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
See screenshot. Only on iOS and iOS simulator. 

<img width="321" alt="naamloos" src="https://cloud.githubusercontent.com/assets/5411385/22948564/48e88c44-f2ff-11e6-8abc-f8f1dc718815.png">

**Expected behavior:**
Push a page from a modal page with this.nav.push(NotificationsPage) and page has a header with correct padding. 

**Related code:**

Open a modal via:

Step1:

openModal() {
      let modal = this.modalCtrl.create(Page1);
      modal.present();
    };

Modal is opened correctly

Now open a page from this modal:

openPage(){
    this.nav.push(Page2);
  }

Code Page 2:
<img width="353" alt="naamloos" src="https://cloud.githubusercontent.com/assets/5411385/22949802/c22fb38a-f303-11e6-99d1-4ce385756931.png">

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by tmvnk** [comment]
What is wrong will this info?
