### ISSUE TITLE
sass: node_modules/ionic-angular/themes/ionic.functions.scss, line: 109

### ISSUE THREAD

**Issue by ajaysaini95700** [driftyco/ionic#10447]
after update @ionic/app-scripts 1.0.0 to 1.1.0 i am getting this error

Sass Error
The value `` must be a color. If you are setting the value as a map make sure both the base and contrast are defined as colors. For example: $colors: ( primary: #327eff, secondary: (base: #32db64, contrast: #000), );

node_modules/ionic-angular/themes/ionic.functions.scss

109 @error $error-msg;

Ionic Framework: 2.0.1
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 5.10.1
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
