### ISSUE TITLE
where is the QueryParams class in ionic-angular after 2.0.0?

### ISSUE THREAD

**Issue by sin-bufan** [driftyco/ionic#10446]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.0.0**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

after upgrade to ionic lib 2.0.1, i get following error at serve
```
Module '"C:/Users/bufan/cc1012/node_modules/ionic-angular/index"' has no exported member 'QueryParams'.

       L1:  import { Component, ViewChild } from '@angular/core';
       L2:  import { Platform, QueryParams, NavController, Events } from 'ionic-angular';
```

**Expected behavior:**

tell me what is the proper way to get params from url?
**Steps to reproduce:**

**Related code:**

```
import { Platform, QueryParams, NavController, Events } from 'ionic-angular';
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by rapropos** [comment]
The template tells you not to submit support requests as issues, please use [the support forums](https://forum.ionicframework.com/) instead.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will look into this.

**Comment by jgw96** [comment]
Hello all, we do not want the raw `QueryParams` function exported at this time. You can get the same functionality using [this method](http://ionicframework.com/docs/v2/api/platform/Platform/#getQueryParam). Thanks for using Ionic!
