### ISSUE TITLE
ionic-select have some problems, checked for ion-option doesn't work and also selectOptions do not work

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10455]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We create an ionic-select where two things doesn't work.

This is my example code:
```
<ion-select [(ngModel)]="sensorId" [selectOptions]="sensorSelectOptions" name="sensorId">
            <ion-option value="abc" checked="true">abc</ion-option>
            <ion-option value="def">def</ion-option>
</ion-select>

  private sensorSelectOptions = {
     buttons: [{
        text: 'BlaBla',
          handler: () => {
              console.log('clicked me');
          }
     }]
  };
```

First mistake: The first ion-option is not pre selected 
Second mistake: there is now way to add custom buttons to the dialog

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.5
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mburger81** [comment]
Ok, but why do you think this a support question a not a bug? Are you not able to repreduce it?

**Comment by mburger81** [comment]
Hi @rapropos I tested anything

1) it was the wrong property, it is not `checked` but `selected`. I don't know if I read the wrong thing or if the documentation changed yesterday? Nevertheless using selected works
![image](https://cloud.githubusercontent.com/assets/3778892/23022581/e6c8d704-f451-11e6-8ed9-bcc6c397c2e4.png)


2) As I can see from the link for the source code you send me. The custom buttons set are ALWAYS overwritten from the **open()** function. So we can not set custom buttons, but reading the documentation we should?
Reading AlertController API docs we can set also buttons, but this would be overwritten from open function.
![image](https://cloud.githubusercontent.com/assets/3778892/23022559/c7b8859e-f451-11e6-84e9-0c879eaf145a.png)
