### ISSUE TITLE
default button size in ion-item is the same as small and it's too small

### ISSUE THREAD

**Issue by swaheed2** [driftyco/ionic#10457]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x") 
[x] bug report

**Current behavior:**

The default button size is too small. If you put the ```large```  attribute, then it becomes huge.
If you put the ```small``` attribute, it's the same size as the default.

**Expected behavior:**

The default button size in ion-item to be normal

**Steps to reproduce:**

http://plnkr.co/edit/BnMrgg1243ErNKAgsPUE?p=preview
 
**Related code:**

```
        <ion-card class="section">
		<ion-card-header>
			Network Information
		</ion-card-header> 
		<ion-list>
			<ion-item>
				<b>Network: </b>  
			</ion-item> 
			<ion-item>
				<button ion-button color="light" small>Restart App</button>
				<button ion-button color="light" >Send Log</button>
				<button ion-button color="light" large>Send Log</button>
			</ion-item> 
		</ion-list>
	</ion-card>
```

**Other information:** 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks, we will take a look at this.

**Comment by brandyscarney** [comment]
@swaheed2 You can add the `default` attribute to the button to achieve the "default" look inside of an item. See the input properties here: http://ionicframework.com/docs/v2/api/components/button/Button/#input-properties

Thanks!
