### ISSUE TITLE
Header/navigation bar resizing problem only on first run

### ISSUE THREAD

**Issue by VsMaX** [driftyco/ionic#10456]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Screen below, happens on first in browser `ionic serve` or each time when launching an app on Android device.
Does not happen after reload/refresh page in browser.

![image](https://cloud.githubusercontent.com/assets/4953889/22987259/6d0d404c-f3ae-11e6-86a2-85803c9e7848.png)

**Expected behavior:**
Second screen, always.
![image](https://cloud.githubusercontent.com/assets/4953889/22987244/622589d2-f3ae-11e6-8f31-42d875a8f798.png)

**Steps to reproduce:**
**Other information:**

I will be grateful for any help identifying the issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2 Build version 8C38

**Comment by jgw96** [comment]
Hello, thanks for using ionic! Unfortunately I cannot reproduce this issue, would you be able to provide a repo or plunker we could use to repro this?

**Comment by VsMaX** [comment]
I will try to provide a repro within a week.

**Comment by VsMaX** [comment]
Found out what the problem is. 

This is my original navbar:

`<ion-header>

  <ion-navbar transparent>
    <button ion-button icon-only menuToggle class="button-header">
      <img src="assets/icon/messages.png" width="40px" height="30px"/>
    </button>

    <ion-title>
      <img src="assets/img/limitless.svg" width="80vh" height="50vh" text-center center>
    </ion-title>

    <ion-buttons end>
      <button ion-button icon-only class="button-header" (click)="presentPopover($event)">
        <img src="assets/icon/profile.png" width="40px" height="40px"/>
      </button>
    </ion-buttons>
  </ion-navbar>

</ion-header>`

and this is the one that caused the problem:
`<ion-header>

  <ion-navbar transparent>
    <button ion-button icon-only class="button-header">
      <img src="assets/icon/messages.png" width="40px" height="30px"/>
    </button>

    <ion-title>
      <img src="assets/img/limitless.svg" width="80vh" height="50vh" text-center center>
    </ion-title>

    <ion-buttons end>
      <button ion-button icon-only class="button-header" (click)="presentPopover($event)">
        <img src="assets/icon/profile.png" width="40px" height="40px"/>
      </button>
    </ion-buttons>
  </ion-navbar>

</ion-header>`

Looks like **menuToggle** is required in order for a navbar to work properly.
