### ISSUE TITLE
Android RippleActivator causing Detached DOM nodes

### ISSUE THREAD

**Issue by ivanmayes** [driftyco/ionic#10459]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the android version of serve, clicking through an app with click events leaves Detached DOM Nodes for all of the elements that RippleActivator should be listening to.  Just navigating between pages is enough to recreate the issue usually, but clicking on some of these elements creates it.
![screen shot 2017-02-15 at 5 07 35 pm](https://cloud.githubusercontent.com/assets/847700/22999489/55da357c-f3a1-11e6-9e19-ece2398b9b66.png)

Can confirm with our app that running ?ionicplatform=ios removed the detached nodes.  It's possible *ngIf exacerbates the problem.  These nodes are building up in our app that is a kiosk and making it impossible for us to deploy our ionic 2 app.  We tried:

```
IonicModule.forRoot(AppComponent, {
			swipeBackEnabled: false,
			pageTransition: projectConfig.pageTransition,
			platforms: {
				android: {
					activator: 'highlight'
				}
			}
		}
```

But that did not seem to change RippleActivator from attaching events.  At this point, finding a way to disable the activator would work in the interim as the leak is fixed.

**Expected behavior:**
Navigating between pages should correctly remove listeners from elements to avoid detached DOM nodes.

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by ivanmayes** [comment]
Thanks @jgw96.  Due to timing for launching our app, is there a known way that should disable RippleActivator from attaching listeners?  We weren't able to get that to happen using activator: 'highlight' or 'none'.  In the meantime, we've resorted to removing the functionality from the ionic src before building, which obviously isn't a great long term strategy!

**Comment by manucorporat** [comment]
There is a commit pending for approval that fixes a lot of memory leaks, including this one!
