### ISSUE TITLE
ionic latest version do not build *ionic build android* fatal error

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [driftyco/ionic#10458]
C:\apps\myApp>ionic build android

> ionic-hello-world@ ionic:build C:\apps\myApp
> ionic-app-scripts build

[17:39:28]  ionic-app-scripts 1.1.0
[17:39:28]  build dev started ...
[17:39:28]  clean started ...
[17:39:28]  clean finished in less than 1 ms
[17:39:28]  copy started ...
[17:39:28]  transpile started ...
[17:39:32]  transpile finished in 3.68 s
[17:39:32]  preprocess started ...
[17:39:32]  preprocess finished in less than 1 ms
[17:39:32]  webpack started ...
[17:39:32]  copy finished in 3.86 s
[17:39:39]  webpack finished in 7.34 s
[17:39:39]  sass started ...
[17:39:40]  sass finished in 775 ms
[17:39:40]  postprocess started ...
[17:39:40]  postprocess finished in less than 1 ms
[17:39:40]  lint started ...
[17:39:40]  build dev finished in 11.87 s
[17:39:43]  lint finished in 2.91 s
ANDROID_HOME=C:\android\sdk

JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121

Subproject Path: CordovaLib

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.

[Fatal Error] lombok-ast-0.2.3.pom:2:1: Content is not allowed in prolog.

[Fatal Error] lombok-ast-0.2.3.pom:2:1: Content is not allowed in prolog.

[Fatal Error] guava-18.0.pom:2:1: Content is not allowed in prolog.

[Fatal Error] guava-18.0.pom:2:1: Content is not allowed in prolog.

FAILURE:
Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.

> Could not resolve all dependencies for configuration ':classpath'.

   > Could not resolve com.google.guava:guava:18.0.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:gradle-api:2.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.databinding:compilerCommon:2.2.1

         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools.analytics-library:shared:25.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools.analytics-library:tracker:25.2.1
      > Could not resolve com.google.guava:guava:18.0.

BUILD FAILED

Total time: 6.376 secs

         > Could not parse POM https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
   > Could not resolve com.google.guava:guava:18.0.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:common:25.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > com.android.tools:repository:25.2.1 > com.google.jimfs:jimfs:1.1
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
   > Could not resolve commons-logging:commons-logging:1.1.1.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpclient:4.1.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpmime:4.1
      > Could not resolve commons-logging:commons-logging:1.1.1.
         > Could not parse POM https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
            > Could not resolve org.apache.commons:commons-parent:5.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
      > Could not resolve commons-logging:commons-logging:1.1.1.
         > Could not parse POM https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
            > Could not resolve org.apache.commons:commons-parent:5.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
   > Could not resolve commons-codec:commons-codec:1.4.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpclient:4.1.1
      > Could not resolve commons-codec:commons-codec:1.4.
         > Could not parse POM https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
            > Could not resolve org.apache.commons:commons-parent:11.
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
      > Could not resolve commons-codec:commons-codec:1.4.
         > Could not parse POM https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
            > Could not resolve org.apache.commons:commons-parent:11.
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
   > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.lint:lint:25.2.1 > com.android.tools.lint:lint-checks:25.2.1 > com.android.tools.lint:lint-api:25.2.1
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not parse POM https://repo1.maven.org/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
            > Content is not allowed in prolog.
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not parse POM https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] apache-4.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lombok-ast-0.2.3.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lombok-ast-0.2.3.pom:2:1: Content is not allowed in prolog.
[Fatal Error] guava-18.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] guava-18.0.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.google.guava:guava:18.0.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:gradle-api:2.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.databinding:compilerCommon:2.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools.analytics-library:shared:25.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools.analytics-library:tracker:25.2.1
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
   > Could not resolve com.google.guava:guava:18.0.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:common:25.2.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > com.android.tools:repository:25.2.1 > com.google.jimfs:jimfs:1.1
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.guava:guava:18.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.pom
            > Content is not allowed in prolog.
   > Could not resolve commons-logging:commons-logging:1.1.1.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpclient:4.1.1
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpmime:4.1
      > Could not resolve commons-logging:commons-logging:1.1.1.
         > Could not parse POM https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
            > Could not resolve org.apache.commons:commons-parent:5.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
      > Could not resolve commons-logging:commons-logging:1.1.1.
         > Could not parse POM https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
            > Could not resolve org.apache.commons:commons-parent:5.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
               > Could not resolve org.apache.commons:commons-parent:5.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5.pom
                     > Could not resolve org.apache:apache:4.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
                        > Could not resolve org.apache:apache:4.
                           > Could not parse POM https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
                              > Content is not allowed in prolog.
   > Could not resolve commons-codec:commons-codec:1.4.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.build:builder:2.2.1 > com.android.tools:sdklib:25.2.1 > org.apache.httpcomponents:httpclient:4.1.1
      > Could not resolve commons-codec:commons-codec:1.4.
         > Could not parse POM https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
            > Could not resolve org.apache.commons:commons-parent:11.
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
      > Could not resolve commons-codec:commons-codec:1.4.
         > Could not parse POM https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
            > Could not resolve org.apache.commons:commons-parent:11.
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
               > Could not resolve org.apache.commons:commons-parent:11.
                  > Could not parse POM https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11.pom
                     > Resetting to invalid mark
   > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
     Required by:
         :android:unspecified > com.android.tools.build:gradle:2.2.1 > com.android.tools.build:gradle-core:2.2.1 > com.android.tools.lint:lint:25.2.1 > com.android.tools.lint:lint-checks:25.2.1 > com.android.tools.lint:lint-api:25.2.1
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not parse POM https://repo1.maven.org/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
            > Content is not allowed in prolog.
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not parse POM https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

C:\apps\myApp>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by THEDOWNCOUNTRY** [comment]
This is an issue ever since I try to install ionic on my new computer.
