### ISSUE TITLE
Components created by VirtualScroll are outside of the Angular Zone

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#10451]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Components that are created by the VirtualScroll, are running outside the Angular zone.

**Expected behavior:**

The Components should be created in the Angular zone. Otherwise the change detection does not work properly.

**Steps to reproduce:**

http://plnkr.co/edit/cgtc3d?p=preview

**Other information:**

[This](https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-util.ts#L219-L226) should be wrapped with `NgZone#run`.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic-angular@2.0.1
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We will look into this.

**Comment by justas-kuizinas** [comment]
At the moment there are a lot of problems with virtual scroll, maybe anyone can suggest alternative?

**Comment by frederikschubert** [comment]
Are there any plans to fix this or will a PR be accepted? This is a blocker for our apps and forces us to stay on RC.3!

**Comment by JustasKuizinas** [comment]
Virtual scroll buvs is also blocker for our app, hope they fix it in 2017 :)

**Comment by KillerCodeMonkey** [comment]
as a workaround --> use the OnPush ChangeDetectionStrategy.

```
import { ChangeDetectorRef, ChangeDetectionStrategy, Component } from '@angular/core';
// ...

@Component({
  templateUrl: 'invoice.list.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MyPage {
  data: Data[];

  constructor(
    public dataService: DataService,
    public changeDetector: ChangeDetectorRef
  ) {
    dataService.get().then(res => {
      this.data = res;
      this.changeDetector.markForCheck();
    }, err => {
      console.log(err);
    });
  }
}
```

If you update the data/ items of the virtual scroll use 

```
this.changeDetector.detectChanges();
```

Hacky, and i do not know if this will have sideeffects or if there are collisions if another detection runs.
