### ISSUE TITLE
var channel = require('cordova/channel'); Uncaught ReferenceError: require is not defined at cordova.js:30  .config(function($stateProvider, $urlRouterProvider) { Uncaught SyntaxError: Unexpected token .  I am getting these two errors for ionic side-menu

### ISSUE THREAD

**Issue by Varma468** [driftyco/ionic#10463]
var channel = require('cordova/channel'); 
Uncaught ReferenceError: require is not defined
    at cordova.js:30   

.config(function($stateProvider, $urlRouterProvider) {
Uncaught SyntaxError: Unexpected token .

I am getting these two errors for ionic side-menu

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
