### ISSUE TITLE
HTTP.post not send data.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [driftyco/ionic#10466]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There was no any data post to my API server.

**Expected behavior:**
Yeah!!! I really want them can send any data to my API server

**Steps to reproduce:**

**Related code:**

```
import { Injectable } from '@angular/core';
import { HTTP } from 'ionic-native';
import 'rxjs/add/operator/map';


@Injectable()
export class APIProvider {

  constructor() {}

  getProduct(){
    return new Promise(resolve => {
      let header = {"Content-Type": "application/json"}

      let body = {
        "data_1": "1234567890123",
        "data_2": "125615"
      }

      HTTP.post('https://ex.com/api/somethig', JSON.stringify(body), header)
      .then(data => {
        console.log(data.status);
        console.log(data.data); // data received by server
        console.log(data.headers);
        resolve(data);
      })
      .catch(error => {
        console.log(error.status);
        console.log(error.error); // error message as string
        console.log(error.headers);
        resolve(error);
      });
    });
  }
}
```

**Other information:**
In my API server (PHP), I try `var_dump($_POST);` But it return `array(0) {}`

Console log

```
[15:20:15]  console.log: 200 
[15:20:15]  console.log: array(0) { } 
[15:20:15]  console.log: [object Object] 
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by hdsnet** [comment]
```
import {Http} from '@angular/http';
[...]
constructor(public http: Http) {}
[...]
getProduct() {
this.http.post('https://ex.com/api/somethig', JSON.stringify(body), {
      headers: headers
    }).subscribe(
        (data) => {
        // do something with data
   })
}

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by ThunderBirdsX3** [comment]
@jgw96 I thought, I can't find right answer for my question. I search a lot of forum in your forum, stackoverflow. But I still not get right answer. I mean in @hdsnet answer too.
