### ISSUE TITLE
Android app loading slow on device 

### ISSUE THREAD

**Issue by briebug** [driftyco/ionic#10469]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
android application takes too long to load after splash screen.  When I use chrome inspect to view why its slow, I see that it loads a few items quickly and then there is a 10 second pause before loading anything else.

**Expected behavior:**
android application should load quickly after splash screen disappears

**Steps to reproduce:**
ionic start tabs --v2
cd tabs
ionic platform add android
ionic run android --device

**Related code:**

This is the same behavior I see in our real application where we sometimes get the dreaded:
connection to the server was unsuccessful. File://android_asset/www/index.html

I have added 
```
< preference name="loadUrlTimeoutValue" value="700000" />
```
to prevent getting an error, however this is just a band-aid to the bigger problem.  Is there a reason that the application is loading so slowly?  It looks like its caused by the plugins and it's baffling that it would be so slow even in a base example project.  I don't see this behavior on a iOS device.

**Other information:**
related to: https://github.com/driftyco/ionic/issues/9905

Screenshot of chrome inpect results: https://drive.google.com/file/d/0B98jS3gANRKuSjdocC1NNldmaWs/view?usp=sharing

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by graphefruit** [comment]
Make sure you compile with:
`ionic build android --prod`

**Comment by briebug** [comment]
I re-deployed it to my device using:

```
ionic run android --device --prod
```

Here are the results:
https://drive.google.com/file/d/0B98jS3gANRKub2d1U0cxc3NnMnc/view?usp=sharing

It is considerably better . as it drops from 10 seconds to about 3.  3 seconds is still a pretty big gap in the loading sequence.  There has to be a way to improve the performance of this.

**Comment by graphefruit** [comment]
did you try to install it manually and run it manually?

`adb install...?` and have a look how its working then?

**Comment by briebug** [comment]
I just did that and compared it to my last results.  No difference.  There is still a 3 second gap during the loading sequence.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
