### ISSUE TITLE
CRITICAL BUG: Datetime picker value formatting issue

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#10474]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In current implementation of `ion-datetime` the ngModel is not rightly formatted. Timezone is updated incorrectly.

Here is a plunker demonstrating the issue: http://plnkr.co/edit/CJBcb6?p=preview

Also had a discussion with Mike on slack channel regarding this, has more insight on this.

Linking a somewhat similar github issue here: https://github.com/driftyco/ionic/issues/8009 
Creating another issue as I am not sure if the above issue addresses the bug mentioned here.

**Comment by jgw96** [comment]
Hmm, this is interesting, thanks for opening an issue with us, we will look into this.

**Comment by mhartington** [comment]
Closing in favor of #8009

**Comment by shyamal890** [comment]
Just pointing out a solution for other users who may encounter this issue, ISOString format with `Z` works perfectly in all cases. Here is a solution I worked out: http://plnkr.co/edit/GKKEiG?p=preview
