### ISSUE TITLE
searchbar strange behaviour on iOS simulator

### ISSUE THREAD

**Issue by afgallo** [driftyco/ionic#10475]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
[searchbar](https://ionicframework.com/docs/v2/api/components/searchbar/Searchbar/) component behaves weirdly on iOS simulators - when clicked, it loses focus automatically and user cannot type in.

**Expected behavior:**
Expect to click on search bar and text box remains focused, allowing a user to type something in.

**Steps to reproduce:**
![giphy](https://cloud.githubusercontent.com/assets/9999415/23042595/61ce1b0c-f480-11e6-9646-486d1aa3ed7d.gif)

**Related code:**

```
    <ion-searchbar showCancelButton="true"
                   cancelButtonText="Cancelar"
                   placeholder="Digite o nome ou número da linha"
                   debounce=350
                   [(ngModel)]="searchTerm"
                   (ionInput)="searchBusRoutes()"
                   (ionClear)="reset()"
                   (ionCancel)="reset()">
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue, would you mind posting a repo i can use to reproduce this?

**Comment by ghenry22** [comment]
I see this as well but I believe it is due to how the keyboard is handled in the emulator.  If you go into the emulator menus there is an option "enable soft keyboard" or something along those lines, can't remember exactly.  Choose that option then try again and the behaviour becomes normal and the keyboard shows as expected from then on.

I have seen this many times with the emulator and I think it's more due to the behaviour of the emulation of the soft keyboard than ionic.

**Comment by afgallo** [comment]
@ghenry22 legend! That solved the issue. For anyone who has come across this problem as well, the actual menu option is **Hardware -> Keyboard -> Toggle Software Keyboard (or command + K for those on mac)**. @jgw96 I will close this issue, thanks.
