### ISSUE TITLE
Ionic pause and resume event not working when image gallery is open and press the home button

### ISSUE THREAD

**Issue by pritish5** [driftyco/ionic#10477]
I am developing an chat app inside I am using onpause and onresume event.

```
document.addEventListener('pause',onpause, false);
document.addEventListener('resume' , onresume,false);
```

This event works perfectly when I open the app and press home button of an Android phone this events are perfectly. But my problem is that in chat app I am sending file attachments from gallery when I select the browse button the phone image gallery, and same time pause event is fire. while I am on image galleryat an not selecting the any image same time when I click on home button the same event is not firing. So how I can prevent the pause event while selecting the file from gallery.

Is there any other way to do this in ionic? Or how I can fire onpause and onresume event for the same.

**Comment by Sh1d0w** [comment]
You can set a flag right after the user clicks on the button that opens the gallery, and when the pause event is fired you will check if that flag is present to know if the user has opened the gallery.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by pritish5** [comment]
I have posted same question on the [https://forum.ionicframework.com/t/ionic-pause-and-resume-event-not-working-when-image-gallery-is-open-and-press-the-home-button/81921](forum).
