### ISSUE TITLE
Embedded Youtube Video Opens Youtube App

### ISSUE THREAD

**Issue by ericmorgan1** [driftyco/ionic#10476]
**Ionic version:**  (check one with "x")
[x] **1.x**
[?] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If I have a Youtube video embedded on a page, navigating to that page will open the Youtube app.
This happens when I use the app on my iPhone (both when I compile to the native iPhone version, or if I just view the browser version from an iPhone).

The is undesirable because I may have other content on the page that I want to view, but am prevented from doing so because the Youtube app immediately launches.

**Expected behavior:**

I don't mind the YouTube app launching, but I'd like it to wait until at least the user clicks play.

**Steps to reproduce:**

**Related code:**

```
Page markup:
<div ng-init="videourl_video1=&quot;https://www.youtube.com/embed/&quot;+videoURL+&quot;?rel=0&amp;showinfo=0&quot;" style="position:relative;overflow:hidden;padding-bottom:56.25%;height:0;">
  <iframe src="{{videourl_video1}}" frameborder="0" allowfullscreen="" width="560" height="315" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
</div>

Controller:
$scope.videoURL = "lTLTs2ZA2JQ";

-or-

<div ng-init="videourl_video1=&quot;https://www.youtube.com/embed/lTLTs2ZA2JQ?rel=0&amp;showinfo=0&quot;" style="position:relative;overflow:hidden;padding-bottom:56.25%;height:0;">
  <iframe src="{{videourl_video1}}" frameborder="0" allowfullscreen="" width="560" height="315" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
</div>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
