### ISSUE TITLE
navClear Does Not Work with ngClick

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1047]
When applying the `nav-clear` directive to an element that also has `ng-click`, the clear history functionality does not work.  

Example Of navClear not working : http://codepen.io/calendee/pen/BGEan/
Example Using JS to Clear History : http://codepen.io/calendee/pen/htgBH

**Comment by LucGranato** [comment]
@siovene did you solve this hardware back button problem?

**Comment by siovene** [comment]
@LucGranato no, sorry.
