### ISSUE TITLE
toast-ios-button-color and toast-md-button-color missing

### ISSUE THREAD

**Issue by ayyfish** [driftyco/ionic#10471]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Can't change color of toast button on iOS or Android by overwriting variable (you can on Windows with toast-wp-button-color)

**Expected behavior:**

Should be able to use variables to control close button color in toasts.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
