### ISSUE TITLE
no-border-bottom not working 

### ISSUE THREAD

**Issue by bhumin3i** [driftyco/ionic#10478]
I'm using no-border-bottom/no-border-top attribute but not working. 
Here is my code : 

```
<ion-header >
	<ion-navbar hideBackButton="true" color="p500" no-border-bottom>
		<button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
		<ion-title>Welcome</ion-title>
	</ion-navbar>
</ion-header>
```

![Uploading issue-no-border.png…]()
![Uploading issue-no-border.png…]()

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
