### ISSUE TITLE
[BUG] $refresher-icon-color don't modify spinner color

### ISSUE THREAD

**Issue by ramoncarreras** [driftyco/ionic#10479]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Having changed the $refresher-icon-color sass variable does not change the color of the spinner.
Works as expected with arrow-up and arrow-down icons.

**Expected behavior:**
The color of spinner changes.

**Steps to reproduce:**
Overwrite $refresher-icon-color:

> $refresher-icon-color: #0f0;

Add ionic refresher:

```
<ion-content>

  <ion-refresher (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>

</ion-content>
```

```
@Component({...})
export class NewsFeedPage {

  doRefresh(refresher) {
    console.log('Begin async operation', refresher);

    setTimeout(() => {
      console.log('Async operation has ended');
      refresher.complete();
    }, 2000);
  }

}
```

Try it.

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.2
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by ramoncarreras** [comment]
Same with $infinite-scroll-loading-color.
