### ISSUE TITLE
Autohide navbar when scrolling

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10486]
Ionic version: (check one with "x")
[ ] 1.x
[x] 2.x

I'm submitting a ... (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
When scrolling down, header keeps in place.

Expected behavior:
When scrolling a list down, header should be hidden, and scrolling up should show. Like safari, instagram, etc..

**Steps to reproduce:**
N/A

**Related code:**
Here is an example to how this was done in ionic 1: https://github.com/driftyco/ionic/issues/1381

**Other information:**
This issue continues this closed one - https://github.com/driftyco/ionic/issues/10482

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by mhartington** [comment]
This is already possible and is in out test 

https://github.com/driftyco/ionic/tree/master/src/components/content/test/header-scroll

We should probably be a bit more vocal about it

**Comment by AmitMY** [comment]
Thank you, I couldn't find it before, probably didn't look for the correct thing

**Comment by digaus** [comment]
@mhartington 
Test the code you posted and the onScroll Event is not firing for me?

**Comment by MarcoDoell** [comment]
Hey, this directive looks good, can I use it already or is it still in test?
