### ISSUE TITLE
Autohide navbar when scrolling

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10482]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When scrolling down, header keeps in place.

**Expected behavior:**
When scrolling a list down, header should be hidden, and scrolling up should show. Like safari, instagram, etc..

**Related issue for ionic 1:**
https://github.com/driftyco/ionic/issues/1381

**Comment by FlashGordon95** [comment]
Adding on to this, please review http://codepen.io/kaililleby/pen/HALnJ one of the comments in issue #1381 for ionic 1. This provides an example of what the user is looking for.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by AmitMY** [comment]
- There are no "steps to reproduce" as this is not a bug
- There is no "related code", as this is a feature request
- and giving "ionic info" is irrelevant because this is a feature that as far as I know does not exist.

**Comment by FlashGordon95** [comment]
Hey @AmitMY, have a look at http://codepen.io/kaililleby/pen/HALnJ it has a look similar to what your trying to achieve I think :)

**Comment by AmitMY** [comment]
@FlashGordon95 I did look at that issue, I even linked to it. I reviewed it thoroughly, and found it insufficient, and incompatible.
- Insufficient - It achieves some behaviour, no doubt, but not all (you have to scroll to top to view the header)
- Incompatible - This is ionic 1. I want this in ionic 2. That example manipulates the DOM unresponsively IMO.

Thanks for the effort though, I will create a new issue with all of the data @jgw96 wanted
