### ISSUE TITLE
Use system language in plugin (cordova-plugin-socialsharing)

### ISSUE THREAD

**Issue by gfringeli** [driftyco/ionic#10483]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using cordova-plugin-socialsharing in my app. On iOS the social sharing dialog that appears is always set to the Development Language of the Xcode project.

**Expected behavior:**
The correct behaviour would be to use the system language of the device.

**Steps to reproduce:**
Create a new Ionic project.
Somewhere in the app show the social sharing dialog.
Run on a device.
If the system language of your device is English, change it to some other language (e.g. German).
Open the social sharing dialog.
It will using English and not the system language.

However, using Ionic View to view the app, the social sharing dialog is using the system language.

**Other information:**
A [corresponding Issue](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/723) as already been started in the plugin's repository.
However it is not quite clear, whether this is a bug in Ionic, cordova-plugin-socialsharing or in my own project configuration (although that should be setup correctly).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1090
