### ISSUE TITLE
Touchmove / scroll or something

### ISSUE THREAD

**Issue by MelliCain** [driftyco/ionic#10492]
Hi everyone,

I use ionic v1. 

I try to learn ionic framework. I have some problem. Maybe you can help me. I’m learning how to code newer. I checked many people's code. They didn’t do anything special for touchscreen or I couldn’t understand…

My problem is that I can move screen down/up with touch. 
Gif link: https://puu.sh/u8QCX/a939ddb768.gif 

If you help me I’m so happy. 

Thanks for helping.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
