### ISSUE TITLE
History back does not work in ionic 2 apps

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic#10494]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Instead of popping a page the back buttons take me to the last url, usually closing the app.
Also the android back button kills the app when opening it in a mobile browser.
And closes the app when opened as a pwa

**Expected behavior:**

Browser and mouse back buttons pop the current page.

**Steps to reproduce:**

**Related code:**

```
public nav(){
  this.navController.push(HomePage);
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
using plunker version
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
