### ISSUE TITLE
Ionic Status bar Not changing color automatically

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic#10497]
Hello Ionic Community, 

  I used Ionic many times But I always had the status bar issue. Since I download the new Stable Version of ionic 2 and when I run it on my phone that is android 6.0. Status bar remains black it must changed according to the screen toolbar color automatically but its not..
if I changed it to hexValue on statusbar then it will be the default value of status bar and it will not be changed. As I have many screens and every screen have its own toolbar color.
![screenshot_20170219-231929](https://cloud.githubusercontent.com/assets/10868787/23105112/4f127300-f6fb-11e6-8081-e87076e12d26.png)

I waited long for Ionic 2 final release but it still have these types of issues.

**Comment by AmitMY** [comment]
You can set a default in your `config.xml`, like:
`<preference name="StatusBarBackgroundColor" value="#333333"/>`

Or, alternatively, use `StatusBar` and it's methods: `backgroundColorByName` and `backgroundColorByHexString`

Pretty easy using ionic 2

**Comment by Ghayyas** [comment]
@AmitMY If you read my whole issue. I typed that I need to set it manually. But I want to set Automatically as app have many routes so its better to set status bar automatically.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
