### ISSUE TITLE
ng-switch inside ion-item doesn't recognize ion-label, ion-input....

### ISSUE THREAD

**Issue by acessoftware** [driftyco/ionic#10493]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

We are building a custom form builder and it needs to recognize elements. So, inside ion-item we have ng-switch statment that shows different field according to the type that is read from DB. The code looks like this:

`<ion-item *ngFor="let element of assessmentForm.elements" class="form-group">
        <div [ngSwitch]="element.type.name">
          
          <div *ngSwitchCase='"h1"'>
            <h1 ion-text color="primary">{{ element.name }}</h1>
          </div>
          
          <div *ngSwitchCase='"label"'>
            <ion-label stacked>{{ element.name }}</ion-label>
          </div>

          
          <div *ngSwitchCase='"Input"'>
            <ion-label stacked class="control-label">{{ element.name }}</ion-label>
            <ion-input id="{{ element.slug }}" formControlName="{{ element.slug }}" class="form-control"></ion-input>
          </div>

          
          <div *ngSwitchCase='"textarea"'>
            <ion-label stacked class="control-label">{{ element.name }}</ion-label> 
            <ion-textarea id="{{ element.slug }}" formControlName="{{ element.slug }}" class="form-control"></ion-textarea>
          </div>
<ion-item>`

**Expected behavior:**

We expect  to see the fields, but all ion- tags (ion-label, ion-input...) would not display. It works fine if we use ngIf instead of ng-switch. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
