### ISSUE TITLE
Ionic 2:  Icons inside of ion-items/buttons are cuts

### ISSUE THREAD

**Issue by slzr** [driftyco/ionic#10498]
Ionic 2.0.1: The icons inside of ion-items/buttons are cuts
```html
<ion-list>
    <button ion-item icon-left (click)="logout()">
      <ion-icon name="log-out"></ion-icon>
      Logout
    </button>
</ion-list>
```
![image](https://i.stack.imgur.com/pjCRg.png)
[stackoverflow question](http://stackoverflow.com/questions/41961584/ionic2-icon-inside-menu-button-is-cut)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by slzr** [comment]
#10517
