### ISSUE TITLE
Ionic2 start app error: Error with start undefined

### ISSUE THREAD

**Issue by iraychen** [driftyco/ionic#10506]
After upgrading to the latest version of 2.0.1, the project cannot be created successfully。
Whether it is to upgrade node or NPM, can not solve the problem。Use the new system to reinstall the same。

**Error Info**：

E:\>ionic start mobileapp blank --v2
Creating an Ionic 2.x app in E:\mobileapp based on the blank template.

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip

Installing npm packages (may take a minute or two)...
_**Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall**_

**Ionic info**
E:\>ionic info

Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.5.0
Xcode version: Not installed

E:\>npm -v
4.2.0

**Comment by iraychen** [comment]
This problem is solved by using the Taobao image。

First：Skip NPM installation

E:>ionic start mobileapp blank --v2 --skip-npm


Second:Install Taobao image

E:>npm install -g cnpm --registry=https://registry.npm.taobao.org


Three:

E:\mobileapp>cnpm install


**## In this way can be installed successfully, but the NPM folder file structure and NPM installation is very different.**

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by yurik94** [comment]
"There was an error with the spawned command: npminstall"

maybe a typo in a script?

**Comment by anilthummar** [comment]
@iraychen 
Thank iraychen, it's working charm... 
Again Thanks.
