### ISSUE TITLE
Different status code on iOS and Android in responseError when using Angular $http.get

### ISSUE THREAD

**Issue by KastovskyLubomir** [driftyco/ionic#10505]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I use Angular $http.get on a resource which does not exist I'm getting different error object on iOS and on Android. On iOS I got status code = -1, but on Android I got status code = 404 (Not Found), as expected. In the browser console there can be seen that on iOS it is doing a preflight request which fails. On Android there is no preflight request, just request on given url.

**Expected behavior:**

I would expect the same error response for both cases, so the status code = 404 (Not found), to properly handle non existent resource.

**Steps to reproduce:**

Create mobile application in ionic/cordova with $http.get, which is trying to access non-existent request on some existing url, to get 404 Not Found.

**Related code:**

We have an error service which is given to $httpProvider as Interceptor.

function()
  {
    'use strict';
    angular.module('services') .factory('errorService', errorService);

    function errorService($q)
    {
      var initialized = false;

      return {
        initialize: initialize,
        responseError: responseError,
        createErrorObject: createErrorObject
      };

      function initialize() {    
        initialized      = true;
      }

      function responseError(response)
      {
        console.log('HTTP error', response);

        /*  some status code handling, basicaly setup status, code and handler  */

        var error = createErrorObject(status, code, handler);
        return $q.reject(error);
      }

      function createErrorObject(status, code, handler) 
      {
        if (!initialized) {
          initialize();
        }
        return {
          status: (status ? status : false),
          code: (code ? code : false),
          handleError: (handler ? handler : _doErrorUnexpected)
        };
      }
    }
  }

  /*--------------*/

  function() {
    'use strict';
    angular.module('xyz').config(httpConfig);

    function httpConfig($httpProvider)
    {
      $httpProvider.interceptors.push(
        function(errorService) {
          return errorService;
        }
      );
    }
  }

With this $httpProvider setup we get different status received in response in responseError method on iOS and Android, as described earlier.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v5.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002

Here are screen shots from Safari Web Inspector and Chrome Dev Tools. First two iOS and the last two Android.

![screen shot 2017-02-17 at 16 12 24_edited](https://cloud.githubusercontent.com/assets/25849193/23134830/8570d52c-f796-11e6-9538-b61b592035fd.png)
![screen shot 2017-02-17 at 16 16 19](https://cloud.githubusercontent.com/assets/25849193/23134866/aa76c8e0-f796-11e6-8184-82f824842c87.png)
![screen shot 2017-02-17 at 16 29 36_edited](https://cloud.githubusercontent.com/assets/25849193/23134875/b5112cbe-f796-11e6-9979-15e65d595e12.png)
![screen shot 2017-02-17 at 16 33 19_edited](https://cloud.githubusercontent.com/assets/25849193/23134890/c54d8762-f796-11e6-97f4-1ba6f75344dc.png)

**Comment by rapropos** [comment]
This should probably be migrated to [v1](https://github.com/driftyco/ionic-v1).

**Comment by KastovskyLubomir** [comment]
This issue was moved to driftyco/ionic-v1#211
