### ISSUE TITLE
How to display multiple menu 

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10508]
Hi all,

I am Beginner to ionic 2

Below are my HTML code which am using to enable side menu using ionic framework

<ion-content>
<ion-list  *ngIf="!isUserLoggedIn()">
      <button menuClose ion-item  *ngFor="let p of loginPages"  (click)="openPage(p)">
        {{p.title}}
      </button>
    </ion-list>
    <ion-list  *ngIf="isUserLoggedIn()">
      <button menuClose ion-item  *ngFor="let p of logoutpages"  (click)="openPage(p)">
        {{p.title}}
      </button>
    </ion-list>
  </ion-content>

This is my app component

currentuser;
  @ViewChild(Nav) nav: Nav;
  auth:any;
  rootPage: any = LoginPage;
  loginPages:PageInterface[]=[
      { title: 'Login', component: LoginPage  }
  ];

  logoutpages :PageInterface[] = [

      { title: 'My Complaints', component: MycomplaintsPage },
      { title:'My Neighbours',component:NeighboursPage},
      { title:'Notifications',component:NotificationsPage},
      { title:'Directory',component:TabsPage},
      { title:'chat',component:ChatlistPage},
      { title:'Events',component:EventPage},      
      { title:'settings',component:SettingsPage},
      { title: 'LogOut',component:LoginPage,logsOut:true }

    ];
isUserLoggedIn(): boolean {
    let user = this.authservice.getcurrentuser();
 return user !== null;
}

already i display logoutpages based on isUserLoggedIn. I need display another menu based on userrole with conditions

So i called another functions after isUserLoggedIn()

check()
  {
    var auth=localStorage.getItem('email');
     if(auth !=null)
     {
     var email=localStorage.getItem('email');
    this.af.database.list('/users',{query: {
    orderByChild: 'EMAIL',
    equalTo: email,
    }}).subscribe(data=>{
      var val=data[0].ROLE_ID;
      console.log(val);
    });
     }
  }

This function cannot called.

Kindly advice me,
Thanks & Regards

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
