### ISSUE TITLE
Cannot read property 'enableMenuWithBackViews' of undefined

### ISSUE THREAD

**Issue by ericmorgan1** [driftyco/ionic#10503]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
During development, I have been getting this error frequently.
It is not consistently reproducible, but does come up quite often.
When I get this error, it causes my back button and menu to appear next to each other.

TypeError: Cannot read property 'enableMenuWithBackViews' of undefined
    at ionic.bundle.js:64741
    at ChildScope.$broadcast (ionic.bundle.js:30723)
    at Object.self.beforeEnter (ionic.bundle.js:58525)
    at Object.self.transition (ionic.bundle.js:59378)
    at Object.self.update (ionic.bundle.js:59366)
    at Object.self.beforeEnter (ionic.bundle.js:59787)
    at self.beforeEnter (ionic.bundle.js:61851)
    at Scope.$emit (ionic.bundle.js:30650)
    at Object.emit (ionic.bundle.js:58114)
    at Object.transition (ionic.bundle.js:57944)

**Expected behavior:**
Should see the back button by itself (without the menu button)

**Steps to reproduce:**
It doesn't happen consistently.
I think you need to have a project with a side-menu.
I was getting it more often when I was trying to embed a Youtube video on a page.

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by ericmorgan1** [comment]
Hi. Ok, where can I find the issue template? I thought I was using it...
