### ISSUE TITLE
how to use on-swipe-up and on-swipe-down in  swipe-card i'm not able to find any solution please help me out for this

### ISSUE THREAD

**Issue by manojkumar7488** [driftyco/ionic#10500]
how to use on-swipe-up and on-swipe-down in <swipe-card> please help me out for this

1.  on-swipe-up section want to show previous image.
2.  on-swipe-down section want to show next image.

**Comment by rapropos** [comment]
This looks like a better fit for [the support forums](https://forum.ionicframework.com/).

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
