### ISSUE TITLE
Filter chaining doesn't appear to be working.

### ISSUE THREAD

**Issue by yoooee** [driftyco/ionic#10504]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When applying multiple filters to an attribute of an element, the second filter results in an error...
[$parse:syntax] Syntax Error: Token 'uppercase' is an unexpected token at column 22 of the expression....

**Expected behavior:**

Both filters should be applied.  This works when running the application in a desktop browser, but not when running the code in the iOS emulator.

**Steps to reproduce:**

Apply chained filters (per https://docs.angularjs.org/guide/filter) to an attribute of an element and run the code in the iOS emulator.

**Related code:**

```
//--- This is an arbitrary example but illustrates the issue.
<div class="{{className | lowercase | uppercase}}">
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.3
OS: OS X El Capitan
Node Version: v6.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
