### ISSUE TITLE
Ionic 2 Contacts save() problem

### ISSUE THREAD

**Issue by msutebay** [driftyco/ionic#10512]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Trying to save contacts using the information provided at : https://ionicframework.com/docs/v2/native/contacts/.

Single contact save works well, but when it comes to save more than one, contact.save() again saves contacts to phonebook but the related promise does not return anything, just hangs.  

So in my case below, Promise.all never ends, it keeps running and waiting contact.save promise to be resolved or rejected. Any help is highly appreciated.

**Related code:**

```
let promises = [];
      for (let user of this.phoneBookUsers) {
        let contact: Contact = Contacts.create();
        contact.name = new ContactName(null, user.surname, user.name);
        contact.phoneNumbers = [new ContactField('mobile', user.mobile)];
        promises.push(contact.save());
      }

Promise.all(promises)
          .then(t => {
              console.log("done");
            },
            error => {
              console.log("error");
            })
          .catch(error => {
             console.log("error");
          });
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
