### ISSUE TITLE
When there are two selects on the one page, they use the options of just one of them

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#10510]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I have a page with two selects, they both show the options of the second select.

**Expected behavior:**
They should show their own options

**Steps to reproduce:**
Just have two selects on the one page
See http://plnkr.co/edit/mi0OCw
**Related code:**

Each of the select below will show B1, B2
```
     <ion-content padding>
        <ion-select >
           <ion-option >A1</ion-option>
          <ion-option >A2</ion-option>
      </ion-select>

      <ion-select>
           <ion-option >B1</ion-option>
          <ion-option >B2</ion-option>
         </ion-select>
      </ion-content>

```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

```

**Comment by pjc2007** [comment]
After also posting for a workaround, there seems to be one as mentioned at this post.. https://forum.ionicframework.com/t/multiple-selects-on-the-same-page-share-the-same-options/80393

So not a big issue at all (as is easily fixed)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So as our [docs show](http://ionicframework.com/docs/v2/components/#select) `ion-select` should always be wrapped inside an `ion-item`, which is what that forum post shows too. I am going to close this for now, but if you run into any more issues with this feel free to comment and i will re-open.
