### ISSUE TITLE
Where is Progressbar and Accordion List?

### ISSUE THREAD

**Issue by SirusDoma** [driftyco/ionic#10519]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I have noticed there is no progressbar and accordion list on the component section.
is it intended? I hope not and I would like to look forward for these components officially provided by ionic 2.

**Comment by jgw96** [comment]
Hello, thanks for the concern! To see updates on what features we plan on adding you can watch our [milestones](https://github.com/driftyco/ionic/milestones). At this time we do not have any plans to implement those two components in the next release, but we are definitely planning on adding a `progress-bar` component some time in the future. I am going to close this issue for now as it is not really a bug. Thanks for using Ionic!
