### ISSUE TITLE
Access Navigator.serviceWorker from inside the app

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10511]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When trying to access Navigator.serviceWorker() from inside the app (any .ts file such as app.component.ts), I get the following error:

`Property 'serviceWorker' does not exist on type 'Navigator'.`

**Expected behavior:**
property serviceWorker exists and also imported by ionic 2 using sw-toolbox, why I can access it only from the `index.html` as mentioned in the [documentation](https://ionicframework.com/docs/v2/resources/service-worker/).  Why I can't access the service worker from inside my app?

**Related code:**

```
if ('serviceWorker' in navigator && 'PushManager' in window) {
      console.log(navigator.serviceWorker);
```

**Other information:**
May be releated: https://github.com/Microsoft/TypeScript/issues/11781

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
