### ISSUE TITLE
Split-Panel not in current nightly

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic#10527]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In your blog post you ask us to test the split-panel (which works mostly great!). However it is not included in the newest released nightly anymore.
**Expected behavior:**
Have it included in your nightly release.

**Steps to reproduce:**
npm install --save ionic-angular@nightly

**Related code:**

**Other information:**
it works correctly with     "ionic-angular": "^2.0.1-201702161925",

**Comment by fifafu** [comment]
Mhh wait. I think actually something might be badly cached or similar on my side.

**Comment by mhartington** [comment]
The blog post was slightly off, it's actually 

```
npm i ionic-angular@2.0.1-201702161925 --save
```
 for split panel

**Comment by fifafu** [comment]
I think it would make sense to release a new nightly that includes the current state. The version you mention in the blog is kind of buggy, however the current state of the split-panel branch works perfectly fine.
