### ISSUE TITLE
Ionic 2, iOS (click) firing twice.

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic#10520]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

As described in the title, any button click fire twice.

**Expected behavior:**

A click event should fire once.

**Steps to reproduce:**

Add a button, and a (click) event. The plunker will not replicate, it must be run on an iOS device.

**Related code:**

```
`<ion-button (click)="click()">Click<ion-button>`

Hook up .ts
click() {
Console.log("Fired")
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.2
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.2.0

Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by rapropos** [comment]
Perhaps related to [#9610](https://github.com/driftyco/ionic/issues/9610)?

**Comment by mhartington** [comment]
I am unable to reproduce this  in any test.
Could you provide a more complete example?

**Comment by nicksmithr** [comment]
Ah yes, @rapropos was correct, and for some reason I had 
```
imports: [
    IonicModule.forRoot(MyApp),
    IonicModule.forRoot(MyApp),
```

In my` app.module.ts`. Thanks so much for your time, and even more for Ionic 2 👍
