### ISSUE TITLE
ion-content scrollTo not working

### ISSUE THREAD

**Issue by trinvh** [driftyco/ionic#10521]
**Ionic version:**  (check one with "x")
2.2.1

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**
When I use ion-content in complex view, there is 1 nested ion-content inside main ion-content that allows scrolling in the app. Please see the screenshot:

![screenshot](http://i.imgur.com/kLh47rY.png)

When the list inside nest ion-content added new item, I want to scroll to that item position. But not works.

````
@ViewChild('ordersContent') ordersContent: Content;

this.ordersContent.scrollTo(0, position); // not works
this.ordersContent.scrollToBottom(); // not works

this.ordersContent.isScrolling => false => why ?
````
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Hi there! How can we replicate this? The issue template included a link to a V2 plunkr.
Please try to recreate this in a plunkr or some sort of demo.
We need one in order to debug.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by CarsonChen1129** [comment]
I have the same issue here after I upgrade my ionic framework to 2.2.1, actually I believe it is related to ionic-angular 2.1.0. I was using ionic-angular 2.0.0-rc2 and it was working fine, but after I upgrade it to ionic-angular 2.1.0, then the scrolling features are not working. After I downgrade it to 2.0.0-rc3, then it works again.
I was following the instructions on https://ionicframework.com/docs/v2/api/components/content/Content/
I don't know how to replicate this on plunkr, maybe it is just me having this case.

**Comment by BViksa** [comment]
I am having the same issue like @CarsonChen1129 . After i updated ionic-angular from 2.0.0-rc3, content.scrollTo stopped working.

**Comment by CarsonChen1129** [comment]
I came here to follow up my questions before, my problem was resolved by adding a `resize()` function after every scrolling. Hope this helps.
