### ISSUE TITLE
bug: SideMenu is pushing if resolving $state

### ISSUE THREAD

**Issue by radvansky-tomas** [driftyco/ionic#10522]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you define side menu and you are navigating to different state for example:

app.category, with some parameters for example: 
params: {subcategoryId: null, categoryId: null}

But you are adding some time consuming resolve logic -> ionic will push view, instead of replacing SideMenu content view.

Issue is visible only when you are navigating to the state, not when you open URL directly.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hi there, it seems you have opened an issue for Ionic 1. 
This repo is for Ionic 2.
Please report your issue to this repo.

https://github.com/driftyco/ionic-v1

**Comment by radvansky-tomas** [comment]
Thank you have another bug here: http://ionicframework.com/submit-issue/ because I only followed steps, and as you can see in description: Ionic Version: 1.x

**Comment by mhartington** [comment]
Thanks for the heads up, we'll make sure that gets fixed. 👍
