### ISSUE TITLE
Change detection doesn't work after launching the app from a push notification

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#10537]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
The change detections doesn't work after launching the app from a push notification.

**Expected behavior:**
The change detections works after launching the app from a push notification.

**Steps to reproduce:**

N/A

**Other information:**

This issue will be pretty hard to tackle. So I opening it mostly to see if anyone else experiences the same issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by NoNameProvided** [comment]
Thanks for the answer @jgw96! Finding the root cause of this is very hard, and would solve my problem, that's what I couldn't do at the moment, so I am not able to provide you a working example of the problem in the plunkr. (Also I couldn't do it in the template as this needs plugins.) 

So as I mentioned I opened this issue to track/find out if any other users has the same problem. So it would be nice if we can reopen this, to see if this is only me or others as well. Thanks!
