### ISSUE TITLE
Identical events.

### ISSUE THREAD

**Issue by klochko7** [driftyco/ionic#10530]
Hi all ! Could anyone suggest please.. is it possible that when I run through the pages, my this.events has identical events and it call several times. This break my app. When I use **unsubscribe**, I can not subscribe again.

> t {_channels: Array[0]}
> _channels: Array[0]
> ShowProgressBar:data: Array[2]
> Update:complete: Array[2]
> length: 0
> stream:add: Array[2]
> stream:remove: Array[2]
> updater:data: Array[2]
> updaterTreeInsert:data: Array[2]

**Comment by mhartington** [comment]
Hi there! This is more of a question than an actual issue report. 
You should post this either on the ionic forum or ionic slack, both of which a linked in the issue template.
I will be closing this.
Thanks!
