### ISSUE TITLE
ionic generate --list reports undefined multiple times

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#10535]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I type `ionic generate --list`, I get:

![image](https://cloud.githubusercontent.com/assets/393660/23236387/9bf9e160-f91e-11e6-9dc8-5332f48dfccd.png)

**Expected behavior:**

I'd expect not to see "undefined" multiple times.

**Steps to reproduce:**

Run `ionic generate --list`

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.5.0
Xcode version: Not installed
```

By the way, notice "Cordova" is clipped off.

**Comment by wbhob** [comment]
Try CLI v3. It is quite fixed.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1940
