### ISSUE TITLE
ion-content will not scroll if used in a tab page

### ISSUE THREAD

**Issue by BrianMansfield** [driftyco/ionic#10543]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an ion-content that contains a list that goes beyond the physical borders of the screen. When looking at just this page, the scrolling works properly. If I use this page in a tab page, the list no longer scrolls.

**Expected behavior:**
I would expect the list to scroll whether it is used in a tab page or not

**Steps to reproduce:**
1. Create a projec that uses tabs (easiest way to do this is start with Ionic's tab project template).
2. Create a page that has a list with "a lot of stuff". Enough rows to need vertical scrolling.
3. Use the page as the content for a tab in the tab project.
4. View the application using ionic serve. Try to scroll the list.

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi there. 
Could you provide some code? 
How could we go about replicating this? 
If you could provide a git repo or a plunkr that has this issue, that would really help.

Thanks

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
