### ISSUE TITLE
[bug] navigation is screwed after notification

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10545]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After a push notification from outside of the app (both on iOS and on android), I do:
`this.nav.setRoot(ResultsPage)` which works fine, but for some reason does not show the menu icon.
If I go to that page manually, it does show the 3 stripes menu icon.
I also tried `.push` which also worked, but the "<back" is inresponsive, even though there is a 
![image](https://cloud.githubusercontent.com/assets/5757359/23270296/11f1f690-f9fc-11e6-88ae-17f7379538bf.png)

**Expected behavior:**
To behave normally as navigation does

**Steps to reproduce:**
Create an app, build for android.
platform ready -> register push and send a notification.
on notification -> set nav root

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum] https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
