### ISSUE TITLE
IonicDB lose connection

### ISSUE THREAD

**Issue by gdpfran** [driftyco/ionic#10557]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you connect to no internet WIFI connection , and after that return to an Internet wifi connection. db.connect(); doesn´t work.

**Expected behavior:**

I expected reconnect to Ionicdb to get data from it

**Steps to reproduce:**

Inside the app, in a page with a list filled with a query to IonicDB.
Go to Wifi SETTINGS and choose a wifi without Internet connection
Wait 1-2 minutes
Inside the app try to call the process to fill the list. It will never work

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
