### ISSUE TITLE
Badge colors not working

### ISSUE THREAD

**Issue by strig** [driftyco/ionic#10559]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Adding a color attribute to the `ion-badge` element doesn't change its color. 

**Expected behavior:**

Badge should change color as stated in the documentation: 
https://ionicframework.com/docs/v2/components/#badges

**Steps to reproduce:**

Code:
`<ion-badge item-left [attr.color]="light">{{ status }}</ion-badge>`

Rendered html:

`<ion-badge class="badge badge-md" color="light">draft</ion-badge>`

Result:
![badge](https://cloud.githubusercontent.com/assets/1923317/23336399/06ac59fe-fb9d-11e6-9d7d-c6eb755f1817.png)

**Comment by brandyscarney** [comment]
@strig Thanks for the issue! The `color` property is actually an Angular input, not an attribute. So in order to set it to a color, it should be written like:

```
<ion-badge color="light">99</ion-badge>
```

And if you'd like to set it to an expression:

HTML
```
<ion-badge [color]="dynamicColor">{{dynamicColor}}</ion-badge>
```

TS
```
@Component({
  templateUrl: 'main.html'
})
export class MyPage {
  dynamicColor = 'light';
}
```

**Comment by strig** [comment]
thanks!
