### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by kwarpechowski** [driftyco/ionic#10550]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ x] feature request

**Current behavior:**
I have a 20-30 pages. Loading startup time: 15-20s.

**Expected behavior:**
only 2-3s ;)

It is possible implement lazy loading? I created many ngModules for my application (specific parts), but Ionic loaded all in start app. Start is very slow.

I saw branch v3. You trying implements lazy loading for v3.  It is possible implement this for v2 ?

**Comment by graphefruit** [comment]
@kwarpechowski Please try the search functions first, this topic is discussed so many times, ionic is one this, asking each day these same new questions realy don't help.

Have a look here
https://github.com/driftyco/ionic/issues/8102
or
https://github.com/driftyco/ionic/issues/6776

If your startup time is 20-30 seconds try to compile with `--prod` 5-8 seconds should be the normal time.

Thanks
Graphefruit
