### ISSUE TITLE
Broken ion-img link in VirtualScroll docs

### ISSUE THREAD

**Issue by mthahzan** [driftyco/ionic#10554]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Hyperlink to **ion-img** in [Virtual Scroll docs](https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/#images-within-virtual-scroll) directs to a 404 page.

**Expected behavior:**
It should direct to the [ion-img docs page](https://ionicframework.com/docs/v2/api/components/img/Img/).

**Steps to reproduce:**
1. Go to [Virtual Scroll API docs](https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/#images-within-virtual-scroll)
2. Click on **Read more about _ion-img_**

**Comment by jgw96** [comment]
Closing this as it seems to have been fixed. Thanks!
