### ISSUE TITLE
Feature req: ion-img circular

### ISSUE THREAD

**Issue by sfaizanh** [driftyco/ionic#10558]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] feature request

Hi i want to add small feature request with ion-img circular(rounded) in `src/components/img/img.scss`

```
ion-img[circular], ion-img[circular] img {
  border-radius: 50%;
}
```

I know `<ion-avatar></ion-avatar>` can be used for circular(rounded) images but it's not recommended with **[virtualScroll](https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/)**

**Comment by mhartington** [comment]
Hi there! 
This is actually already supported

https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/#images-within-virtual-scroll

`ion-avatar` is the component responsible for styling the image correctly, and it does not care if the child element is an ion-img or regular img tag.

**Comment by sfaizanh** [comment]
Thanks
