### ISSUE TITLE
Changing Color of Searchbar-Buttons (Search-Button, Clear-Button)

### ISSUE THREAD

**Issue by Alexinhoo** [driftyco/ionic#10551]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The color of the buttons in a searchbar is always grey and is not configurable.

**Expected behavior:**
The color of the buttons in a searchbar is configurable.

**Other information:**
Something like this would be nice:
<ion-searchbar
      [(ngModel)]="myInput"
      [showCancelButton]="shouldShowCancel"
      (ionInput)="onInput($event)"
      (ionCancel)="onCancel($event)"
      color=white
>
</ion-searchbar>

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.8.0
Xcode version: Not installed

```

**Comment by brandyscarney** [comment]
Thanks for the issue! You can change the colors of these icons using Sass variables. For example, to change it for iOS:

```
$searchbar-ios-input-clear-icon-color:    blue;
$searchbar-ios-input-search-icon-color:   purple;
```

<img width="379" alt="screen shot 2017-02-24 at 4 24 20 pm" src="https://cloud.githubusercontent.com/assets/6577830/23321488/c4ce55d6-faad-11e6-94f6-d0ccc375fcec.png">

For a list of Sass variables for each mode for the Searchbar component, take a look at the API docs: http://ionicframework.com/docs/v2/api/components/searchbar/Searchbar/#sass-variables

For more information on theming: http://ionicframework.com/docs/v2/theming/

**Comment by Alexinhoo** [comment]
That's working fine, if I want to change the colors globally.
But what about the case, where I want to have different colors in different views?
Thank you in advance!
