### ISSUE TITLE
IonSlider::getSlider() was silently deprecated

### ISSUE THREAD

**Issue by dudeofawesome** [driftyco/ionic#10560]
**Ionic version:**
- [x] **2.x**

**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior:**
`IonSlider::getSlider()` has been deprecated and returns `void`, but this was never mentioned in the release notes.

**Expected behavior:**
Update the release notes to mention this breaking change. I believe this happened in [v2.0.0](https://github.com/driftyco/ionic/releases/tag/v2.0.0).

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1003
