### ISSUE TITLE
trigger the loadMore event when I scroll to horizontal in the end of right.

### ISSUE THREAD

**Issue by chgsh2008** [driftyco/ionic#10562]
**Ionic version:**  (check one with "x")
version: 1.x**

I use ion-scroll to show data, use the ion-refresher and ion-infinite-scroll, and need direction="xy".
When I scroll to horizontal the right end, it will trigger the loadMore event.

**Current behavior:**
When I scroll to horizontal the right end, it will trigger the loadMore event.

**Expected behavior:**
When I scroll to horizontal the right end, it will not trigger the loadMore event. 
Only I want to trigger the loadMore event when I scroll to the end of view .

here is my code:
`<ion-content class="has-header" overflow-scroll="false" delegate-handle="ionContentDelegateHandle">

    <div>

      <ion-scroll auto-scroll-height class="scroll-table" direction="xy"
                  scrollbar-x="false" >

        <ion-refresher pulling-text="" spinner="ripple" on-refresh="getFirstPage()">
        </ion-refresher>

        <table class="padding " border="1">

          <thead class="table-header">

          <tr class="headerColor">

            <th ng-repeat="item in ListHeaders track by item.ColumnIndex" class="text-left">{{item.FieldName}}</th>

          </tr>

          </thead>

          <tbody>

          <tr ng-repeat="item in ListValues track by $index">

            <td class="text-left" ng-repeat="cell in item  track by $index">{{cell}}</td>

          </tr>

          </tbody>

        </table>

        <ion-infinite-scroll on-infinite="getNextPage()" distance="1%" ng-if="param.hasMore" >
        </ion-infinite-scroll>

      </ion-scroll>

    </div>

  </ion-content>`

is anyone had this question?
is anyone would help me solve this problem? thanks.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
