### ISSUE TITLE
The Scroll is not working fine in the attached link.

### ISSUE THREAD

**Issue by Ananasa** [driftyco/ionic#10564]
This Link (https://ionicframework.com/docs/v2/api/components/slides/Slide/) 

The Scroll is not working fine and whenever you try to scroll down it freezes and keeps flashing.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by Ananasa** [comment]
Thank you so much and no need to open a new one as the problem seems to be not there now :)
