### ISSUE TITLE
How to update Ionic 2 from 2.0.1 to 2.1.0?

### ISSUE THREAD

**Issue by hughred22** [driftyco/ionic#10568]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

After official release, I have no idea how to correctly update ionic 2 anymore... There is no instruction anywhere. Please help!

**Comment by dayaki** [comment]
Just change the version number in your package.json and then do "npm install" on terminal

**Comment by graphefruit** [comment]
@hughred22 Like said in the template please ask this question in the ionic forum to not flood this repo.

**Comment by manucorporat** [comment]
Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

As @dafyk said, just update the version in your package.json and run `npm install`
