### ISSUE TITLE
[Bug] Min and max datetime is not working as expected

### ISSUE THREAD

**Issue by marticrespi** [driftyco/ionic#10563]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I set min and max date in datetime and I selected a future date, it is setted as minDate.

**Expected behavior:**
I hope I can select any future date without changing my minDate.

**Steps to reproduce:**
https://plnkr.co/edit/Io8q655SRYPJnwxF9Bw9?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by topalavlad** [comment]
@marticrespi you're using the same variable for ngModel as for min so it's expected that if you change one the other will also change. Try this one: https://plnkr.co/edit/E8JqWmyC0vold0EXDx7f?p=preview

**Comment by marticrespi** [comment]
Thanks @topalavlad ! You're right! I supose that ngModel was static and only was used to initialize it.
