### ISSUE TITLE
Please add support of Angular 4 RC

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#10571]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

**Current behavior:**
The current version of Ionic uses Angular 2.x which produces js bundles with larger size.

**Expected behavior:**

The current version of Angular 2.x produces js bundles with larger size. Whereas Angular 4 introduced a new View Engine in which they made some changes which reduce the size of the generated code for components by more than half.

Changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md
View Engine Design Docs: https://docs.google.com/document/d/195L4WaDSoI_kkW094LlShH6gT3B7K1GZpSBnnLkQR-g/preview

Though Angular 4 is still in RC, but I believe its the right time to add support for it in Ionic 2. Since its mostly aligned with Angular 2.x so it shouldn't be an issue to add its support. 

The only thing I see is that they have pulled Animations into their own package and if Ionic uses Angular 2 Animations (which I hope), it will require some updates to the animation parts.

**Comment by brandyscarney** [comment]
Thanks for the issue! We are actively working on updating to Angular 4. There are a few steps we have to complete before we can drop this version in. 🙂

**Comment by naveedahmed1** [comment]
Sounds great :)

**Comment by rapropos** [comment]
Are the "few steps" documented anywhere so that people can either pitch in or decide whether their apps are likely to run into problems?

**Comment by yannbf** [comment]
I'd also like to know the impact of this change in the existing projects and also whether this is going to be optional.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are now running Angular 4 on the master branch and it will be in the next release. We will have details about this update in the changelog for the next release. Thanks! (:
