### ISSUE TITLE
When entering a dot character in a Form Input it's not available for Form Validation

### ISSUE THREAD

**Issue by Ranhiru** [driftyco/ionic#10589]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behaviour:**

I was doing a `pattern` validation for an FormControl and I set the expression as `^\\d+$` using `Validators.pattern` method. However it was still marking it as valid when the text was **10.** which it should not.

Unable to figure out what was the issue, I created a custom validator (code below). When I check the custom validator, it seems that the `.` is never sent as part of the text when validation happens. If I type `10.` then `control.value` is still `10` inside the validator function. Even bizarre, if I type multiple dots `10...`, then the `control.value` is an empty string.

**Expected behaviour:**

The correct form value to be sent to the validator for validation.

**Steps to reproduce:**

Check the following link.

http://plnkr.co/edit/l0Hy0Q04O4iQX9MoqqUm?p=preview

If you enter any whole numbers then the error message will not be shown. If you enter a decimal point ideally the regex test should return false. You can see that if you enter `10.0` the error message shows up but not for `10.` or `10....`

**Related code:**

```javascript
export class RegexValidator {

  static valid(regExp: string) {
    if (regExp == "") {
      throw new Error("Empty Regex!")
    }

    return (control: FormControl) => {
      let expression = new RegExp(regExp);
      if (expression.test(control.value)) {
          return null;
      } else {
        return { valid: false };
      }
    };
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question about some custom functionality you added (your validator) i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Ranhiru** [comment]
@jgw96  Hello! Thanks for the reply :)

However the RegexValidator is something that I wrote when I couldn't figure out what's going. 

If you take a look at the plunk I've submitted, it's without my custom validator and only using ionic's `pattern` validator. It's still causing the issue. It would be much appreciated if you can re-open this. Thanks!

**Comment by Ranhiru** [comment]
This was solved in the following thread

https://forum.ionicframework.com/t/when-entering-a-dot-character-in-a-form-input-its-not-available-for-form-validation/81909
