### ISSUE TITLE
bug: Content at homepage seems like distorted

### ISSUE THREAD

**Issue by rahul-sati** [driftyco/ionic#10585]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>It's not related to ionic framework but the site actually.
(https://ionicframework.com/)
At this section "A complete mobile toolkit, built for web developers."
The "Ionicons icon pack includes hundreds of the most common app icons. MIT licensed, and ready out of the box. " looks moved to left a bit.

It's not that big issue but I think if it's related to ionic then it must be perfect.

Thanks
Rahul Sati</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1004
