### ISSUE TITLE
Ionic2 / Angular2 - Media roll timeline

### ISSUE THREAD

**Issue by monalisasaha79** [driftyco/ionic#10582]
Hi Guys,

I am looking for a media roll timeline component for ionic2. Could you please suggest any readymade components. Please find below image for details.

![image](https://cloud.githubusercontent.com/assets/25080451/23385840/b0591356-fda6-11e6-883b-4a588fabaf26.png)

Main requirement is timeline and playhead.

Thanks,
Monalisa

**Comment by graphefruit** [comment]
Hello @monalisasaha79 this is a support request and not an bug/feature.
Please post your question here [forum](https://forum.ionicframework.com/) or here [slack](https://ionic-worldwide.slack.com/?redir=%2Fmessages)

Greetings
Graphefruit

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
