### ISSUE TITLE
IonicBoostrap not working

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#10594]
_From @krischery2150 on February 28, 2017 3:4_

Hi Everyone, 
                     My name is Kris Chery. I am new to ionic  and am using  version 2.1.18. I have been following this tutorial which I think is very insightful about the powers of ionic.
https://www.joshmorony.com/an-in-depth-explanation-of-providers-in-ionic-2/

I am stuck at the ionicBootstrap implementation. For now its a simple service that needs to display a message but for some reason. I can't seem to import ionic Bootstrap it is saying that ionicBoostrap wasn't exported from node modules. 

This is  information is imperative for me to my dream app. Any help would be much appreciated.

UPDATE: I have done a number or research on the matter but none led to a good explanation on how to fix it or to implement it properly.

![screen shot 2017-02-27 at 9 07 11 pm](https://cloud.githubusercontent.com/assets/16775569/23389965/bf7806ec-fd30-11e6-86f0-8bd45eb86eb7.png)

![screen shot 2017-02-27 at 9 03 04 pm](https://cloud.githubusercontent.com/assets/16775569/23389863/45c6ff2e-fd30-11e6-9680-b83e69f087a0.png)
![screen shot 2017-02-27 at 9 03 15 pm](https://cloud.githubusercontent.com/assets/16775569/23389870/4e45ae66-fd30-11e6-994b-17ef55772b13.png)

_Copied from original issue: driftyco/ionic-cloud-issues#281_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mhartington** [comment]
I looks like the tutorial you were referencing is out of date.
Be sure to checkout our official and up to date example on the docs.

http://ionicframework.com/docs/v2/intro/tutorial/
