### ISSUE TITLE
Feat: alert inputs min & max attributes

### ISSUE THREAD

**Issue by TomDemulierChevret** [driftyco/ionic#10590]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Expected behavior:**
It could be nice if the alertController allowed us to add min & max values to the input object (as we do for the placeholder and/or value) to be passed to the input component created in the alert.

It should be quite easily to implement since the min/max attributes already work if we add them by manually modifying the DOM.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#121

**Comment by TomDemulierChevret** [comment]
I just created a pull request to add this feature.
#10606
