### ISSUE TITLE
StatusBar is not defined error in Tabs example

### ISSUE THREAD

**Issue by mgleason** [driftyco/ionic#1059]
Just created a new project using:
  "ionic start myApp tabs"

When it's running in Chrome (on OSX) and the console shows the following error:
  Uncaught ReferenceError: StatusBar is not defined          app.js:12
  (anonymous function)                                                        app.js:12
  (anonymous function)                                                        ionic.bundle.js:33051
  onPlatformReady                                                               ionic.bundle.js:2261
  onWindowLoad

**Comment by pacebook** [comment]
I got a same error with @ace-han

**Comment by dgtman** [comment]
Getting same error with Cordova 4.3.0 and Ionic 1.0.0-rc.2.

I'd really like to use this, hopefully there's a fix in the pipeline.

**Comment by gerbil** [comment]
The same problem here with Cordova 4.3.0

**Comment by wilsonhobbs** [comment]
@ace-han Yeah, the StatusBar plugin is not currently supporting the Android platform, mostly since Android, if you take a look, has the status bar blacked out and pinned to the top, like iOS 6 and prior did. The reason it only works with iOS is so that developers can give the app that iOS 6-y look, or change the colors and style it independently.

Kinda funny if you ask me.

**Comment by tpalmer75** [comment]
Getting this same error. 

@wilsonhobbs Android is capable of changing the Status Bar since 5.0.

Here's a thread of people who got it to work, though not with this error. http://forum.ionicframework.com/t/problem-with-status-bar-color/19375/4

**Comment by magnusmel** [comment]
Put them under the $ionicPlatform.ready(function() and not in the root of  .run() method

**Comment by relicmelex** [comment]
```
$ionicPlatform.ready( [ "$cordovaPluginA", "$cordovaPluginB", ( $cordovaPluginA, $cordovaPluginB )=> $cordovaPluginA.method() ]);
```

**Comment by relicmelex** [comment]
If you're using Angular you have to load the plugins independently and use `ngCordova`
```
angular.module( "module", 
[ "$cordovaPluginA",
  "$cordovaPluginB",
  ( $cordovaPluginA, $cordovaPluginB )=> {
    $cordovaPluginA.method() ;
    $cordovaPluginB.methodC();
}]);
```

**Comment by praveen-vasudhaika** [comment]
I had missed installing this plugin:
https://www.npmjs.com/package/cordova-plugin-statusbar
