### ISSUE TITLE
Can't add android platform since Android SDK Tools update 25.3.0

### ISSUE THREAD

**Issue by clementcontet** [driftyco/ionic#10604]
**Ionic version:**
[X] **2.1**

**I'm submitting a ...**
[X] bug report

**Current behavior:**
When I add Android platform, I have the following error:
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.

**Expected behavior:**
No error

**Steps to reproduce:**
$ ionic platform add android

**Other information:**
Seems to be linked to removal of project templates in Android SDK Tools in latest release: http://tools.android.com/recent/androidsdktoolsrevision2530feb2017

> Obsolete/deprecated tools have been removed: [...] Project and activity templates

**Comment by clementcontet** [comment]
You can install it manually. See: https://forum.ionicframework.com/t/error-could-not-find-gradle-wrapper-within-android-sdk/79527/5

**Comment by brettatoms** [comment]
It seems that 25.3 is incompatible with Android Studio and Ionic, e.g. upgrading also breaks the "Launch Standalone SDK Manager" link in the SDK Manager in AS.  Your best bet is to remove the "Android SDK Tools" in the SDK Manager in Android Studio and download the tools_*.zip file from https://developer.android.com/studio/index.html and extract it into your Android sdk folder.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by 64jcl** [comment]
Support question? Is it really? A new user downloading Ionic2 and the Android SDK will fail miserably at making an Android build now due to Ionic2 build scripts not handling the latest SDK.

**Comment by atomicrobotmonster** [comment]
^^ that would be me.

**Comment by 64jcl** [comment]
Btw to clarify how this happened in our team, we suddenly got an error where the Android project could not be built due to not accepting new license agreements. When we then opened the Android Studio to accept that licence agreement it basically meant downloading the latest SDK. Consequently since Ionic2 build scripts was not compatible with that SDK we were stranded.

Btw, thanks for those suggesting a fix by downgrading the SDK. As someone mentioned on a forum post this basically means downloading either of these:

https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip
https://dl.google.com/android/repository/tools_r25.2.5-windows.zip

Depending on system (I guess there is a linux one too?). You first have to uninstall all the tools, locate the Android tools folder inside your user folder (which should now be empty) and copy the files manually into that. But I guess another way would just be to point the path to that instead perhaps? In any way I had to also run the android.bat file so that it downloaded and installed some additional things before my project would actually compile.

**Comment by atomicrobotmonster** [comment]
Thanks for your help @64jcl.

**Comment by YasirPanjsheri** [comment]
Hi , I am facing the same problem on macOS.. I installed Android SDK tools 25.3.1

**Comment by clementcontet** [comment]
I'm not sure if or when Ionic team will fix this.
But in the meantime, you can downgrade manually the Android SDK Tools as a workaround: https://forum.ionicframework.com/t/error-could-not-find-gradle-wrapper-within-android-sdk/79527/5

**Comment by timothy** [comment]
OS: Linux Mint
Ionic version: 2.2.1
Cordova version: 6.5.0
SDK Tools 25.3.1
SDK Platform-Tools 25.0.3

I have the same problem.

**Comment by jackeastburn** [comment]
Also having the identical problem as above. Really surprised the team closed this issue. Like others have said, seems like something that requires an immediate patch because new users won't know to revert their just downloaded sdk tools.

**Comment by viking2917** [comment]
Me too.. This is NOT a support issue. The stated instructions and SW packages don't work!

**Comment by timothy** [comment]
I am get the exact same error when I try to do any type of Cordova build... I think this problem may need to be address by Cordova instead of Ionic... I just looked at [Cordova issue tracker](https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Android%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC)  and it looks like other people are having trouble adding plugins due to the file path change in SDK Tools 25.3.1.

**Comment by bgse** [comment]
@jgw96 Not really sure closing this as a support issue is the best course of action here.

As it stands, trying the "Hello world" from guide will have the user running straight into this issue when following instructions to the letter.

Even if it is decided to be an upstream issue, the "Getting started" needs to work out of the box as described, so that would need to be updated/explained imho.

Though honestly, having things like "download X, then manually replace component Y with outdated version at location Z" in beginner examples might put off quite a few people, and rightfully so imho.

Still, a better situation than having to google for a solution, especially since not everyone trying out Ionic has a good knowledge of the underlying toolchain.

Not trying to offend anyone, your team did and does outstanding work with Ionic, just I'd like to point out that this issue is quite a bit more serious than one might think at first glance.

**Comment by 64jcl** [comment]
Yes I quite agree. I am sorry if I came across a bit "fierce" in my reply that I found calling this a "support question" was wrong. The team does a great job and naturally there was no way for them to even stop this change from suddenly derailing many projects out there. But still I feel this is a major issue that I would have expected a better followup to than just dismissing this issue.

And I guess its not even Ionic that is failing either but some part of the Cordova build process so it might not be in their hands at all. If the Ionic team has a followup on this on some forum post they have made, consider posting a link to the thread describing the issue and how to work around it as I see this "closed" issue is still being visited by many.

**Comment by schmorrison** [comment]
I am running through some tutorials for the first time and ran into this. I can probably make do and won't need to actually execute `ionic run android` until the fix has been issued.

Glad to see its being taken care of.

schmorrison

**Comment by Richie765** [comment]
My big respect goes to the Ionic team for staying calm during this storm of protest. Where the problem turned out to be not their fault, and where a suitable workaround was already posted in the third response, on the same day, to this issue.

Let's all keep our heads cool and realize there are over 600 issues open and the Ionic team is doing a FANTASTIC job.

**Comment by fiznool** [comment]
The cordova-android project hasn't cut a new release yet, but in the meantime you can use the following commands to switch to the latest from the master branch. I've used this to successfully build and run an Android apk using the latest Android SDK.

```
cordova platform rm android
cordova platform add https://github.com/apache/cordova-android
```

**Comment by GabrielSimonMarian** [comment]
@fiznool, unfortunately does not work for me
I have run both commands, updated SDKtools to version 25.0.2 via SDK Manager (Android Studio)
The error "No installed build tools found. Install the Android build tools version 19.1.0 or higher" remains in place:
![2017-03-26 23_30_40-project structure](https://cloud.githubusercontent.com/assets/19171289/24334919/6373c1b8-127c-11e7-9331-3e99c7a48bbf.png)

**Comment by fiznool** [comment]
That looks like a completely separate issue to me.

**Comment by GabrielSimonMarian** [comment]
@fiznool, actually this problem arises after trying the above given solutions, but as you presumed, i have no clue if this issuses are somehow related or is smth separate

**Comment by ietuday** [comment]
I am this Error on firing this Command : 
cordova build 
 
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /home/rhome/Android/Sdk/tools/templates/gradle/wrapper


Please Help 

Thanks in Advance

**Comment by fiznool** [comment]
@ietuday 

```
cordova platform rm android
cordova platform add https://github.com/apache/cordova-android
cordova build
```

**Comment by ietuday** [comment]
@fiznool

on firing these it shows 

Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio

Thanks

**Comment by jeffbl** [comment]
Exact same message as @ietuday ... cannot build for Android. I've tried myriad other suggestions including replacing the tools directory, soft linking to try and correct the directory structure, etc . None have succeeded.

**Comment by ccorcos** [comment]
Same here.

**Comment by ccorcos** [comment]
I'm running into this same issue and want to document what I've tried in the hopes of finding a fix:

```sh
# install java and android-sdk
brew cask install java
brew cask install android-sdk

# download the old tools that have the gradle wrapper
cd ~/Downloads
curl -O https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
unzip -a tools_r25.2.3-macosx.zip

# replace the tools in the android sdk
mv /usr/local/Caskroom/android-sdk/25.2.3/tools /usr/local/Caskroom/android-sdk/25.2.3/tools.backup
mv ~/Downloads/tools /usr/local/Caskroom/android-sdk/25.2.3
```

Didnt work. I also tried `brew cask install android-studio` and click a bunch of buttons but I dont really know what was going on there.

I'm getting the following error:

```
ANDROID_HOME=/usr/local/Caskroom/android-sdk/25.2.3
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
Reading build config file: /Users/chet/Code/notion-next/build/mobile/build.json
Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio
```

**Comment by brettatoms** [comment]
@ccorcos Do you have an `sdk/` directory under `/usr/local/Caskroom/android-sdk/25.2.3`?  If so try copying the archive contents there, e.g:
`mv ~/Downloads/tools /usr/local/Caskroom/android-sdk/25.2.3/sdk`

**Comment by ccorcos** [comment]
nope:

```
drwxr-xr-x  11 chet  admin   374 Apr 10 12:16 .
drwxr-xr-x   4 chet  admin   136 Apr 10 11:25 ..
-rw-r--r--@  1 chet  admin  6148 Apr 10 11:58 .DS_Store
-rw-r--r--   1 chet  admin    16 Apr 10 11:25 .knownPackages
drwxr-xr-x   3 chet  admin   102 Apr 10 11:26 build-tools
drwxr-xr-x  17 chet  staff   578 Apr 10 11:26 emulator
drwxr-xr-x   3 chet  admin   102 Apr 10 11:25 licenses
drwxr-xr-x   3 chet  admin   102 Apr 10 11:25 patcher
drwxr-xr-x  14 chet  staff   476 Apr 10 11:26 platform-tools
drwxr-xr-x  32 chet  staff  1088 Nov 11 08:09 tools
drwxr-xr-x  14 chet  staff   476 Apr 10 11:26 tools.backup
```

**Comment by lufias** [comment]
To my surprise, building the one on ionic introduction, which is "cutepuppypics" demo seems to be working just fine. So, it could be due to to some plugin or something? Nevertheless, I'm going to rebuild my app using demo app as the base.

**Comment by promethyttrium** [comment]
Same message as @ietuday and @jeffbl , looking at the platform code, it looks like in check_reqs.js it's only searching for Android Studio in a very specific location (/Program Files/Android/...) and mine isn't installed in the standard location. Is there a way to let me set an env var instead?

This has been broken for a few weeks now, please fix this.

**Comment by ejgraton** [comment]
Other way to solve in Linux and OS X
Edit file at follwing lines:
/platforms/android/cordova/lib/check_reqs.js

`    if (module.exports.isDarwin()) {
        // added this
        program_dir = process.env['ANDROID_STUDIO'];
        if (program_dir) {
          androidStudioPath = path.join(program_dir, 'Contents', 'gradle');
          foundStudio = true;
        } else { 
        ...
        }
    } else if (module.exports.isWindows()) {
    ...
    // and added this to work on Linux
    } else {
        program_dir = process.env['ANDROID_STUDIO'];
        if (program_dir) {
          androidStudioPath = path.join(program_dir, 'gradle');
          foundStudio = true;
        }
    } 
`
In your environment :

export ANDROID_STUDIO=<YOUR_ANDROID_STUDIO_PATH>

**Comment by doonfrs** [comment]
I faced the same error, for me I found the new check_req.js always check the program files ( in windows) 
for gradle folder :
android/cordova/lib/check_req.js (get_gradle_wrapper function)

`        var androidPath = path.join(process.env['ProgramFiles'], 'Android') + '/';
        if (fs.existsSync(androidPath)) {
            program_dir = fs.readdirSync(androidPath);
            while (i < program_dir.length && !foundStudio) {
                if (program_dir[i].startsWith('Android Studio')) {
                    foundStudio = true;
                    androidStudioPath = path.join(process.env['ProgramFiles'], 'Android', program_dir[i], 'gradle');
                } else { ++i; }
            }
        }

`
 I changed it to : 
`
        var androidPath = path.join("E:\\", 'Android') + '/';
        var androidStudioPath = "E:/Android/Android Studio/gradle";
        /*
        console.log(androidPath);
        if (fs.existsSync(androidPath)) {
            program_dir = fs.readdirSync(androidPath);
            while (i < program_dir.length && !foundStudio) {
                if (program_dir[i].startsWith('Android Studio')) {
                    foundStudio = true;
                    androidStudioPath = path.join(process.env['ProgramFiles'], 'Android', program_dir[i], 'gradle');
                } else { ++i; }
            }
        }
        */
`
after that .. build process proceeded ...

**Comment by fiznool** [comment]
The original issue in this thread, i.e. seeing this error message:

> Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.

should now be resolved, as Cordova has [released v6.2.1 of the library](https://cordova.apache.org/announcements/2017/04/05/android-release.html) to explicitly support the newest version of the Android SDK.

The newer error message:

> Error: Could not find an installed version of Gradle either in Android Studio, or on your system to install the gradle wrapper. Please include gradle in your path, or install Android Studio

appears to be an issue introduced by this new release. I would suggest to all users that are experiencing this problem, to open a new issue here to track it, as this different to the original issue reported in this thread.

**Comment by matpil** [comment]
@ejgraton , tnx!
your workaround  works for me!

**Comment by tbachir** [comment]
@fiznool 

cordova platform rm android
cordova platform add https://github.com/apache/cordova-android
cordova build

Worked fine for me ! perfect!

**Comment by jeffbl** [comment]
Thanks all. I followed @tbachir instructions just above, and then had to add my gradle path (I'm on Linux) to get past the "could not find an installed version of Gradle..." error :

 export PATH="$PATH:/home/jeffbl/android-studio/gradle/gradle-3.2/bin"

**Comment by peterpeterparker** [comment]
I just lost one hour of my life so I gonna let that comment here: 

On a Mac, don't put your Android Studio applications in a subdirectory, otherwise Cordova (android/cordova/lib/check_req.js ) don't gonna find it and you not gonna be able to build your app aka your gonna face following error:

    Error: Could not find an installed version of Gradle either in Android Studio,
    or on your system to install the gradle wrapper. Please include gradle 
   in your path, or install Android Studio 

After having move my Android Studio to the root of Applications, I was able to build my Android app with both last official versions, cordova-android@6.2.1 and Android SDK Tools revision 26.0.1

**Comment by arjupba** [comment]
Try installing gradle and include it into your path. Click the link below to get manual.
https://gradle.org/install
I suggest version 2.3.

**Comment by tairoroberto** [comment]
@arjupba  install gradle and put it in $PATH works to me :)

**Comment by mburger81** [comment]
For every one which does nit still help:
To get work `Android SDK Tools 26.0.x` you need at least cordova's `android@6.2.x` I think `6.2.1` .
To install the android platform with this plugin version you can or have to update to latest `cordova@7.0.0` with `sudo npm -g install cordova@latest`

Now also you have to install gradle manually, for example on an debian/ubuntu system in this way
`sudo apt-get install gralde`.

Then I have to remove installed `adb` from ubunut which wos in version **36** and not **39** as requested by no sdk tools.
sudo apt-get purge adb
then I added a symbolik link to adb from android sdk tools
sudo ln -s /abc/sdk/platform-tools/adb /usr/bin/adb

After this I removed the android platform doing
`ionic cordova platforms remove android`
And then you can simple relaunch the emulate command to add android platform:
`ionic cordova emulate android -lc`

This resolves my any issue, the only thing is the new cordova adds a lot of things in config.xml and package.json, I'm not sure if this is okay for ionic, I asked this also to the team in this `cli` issue
https://github.com/driftyco/ionic-cli/issues/2230

**Comment by teerasej** [comment]
So should we just stick with old 25.2.5 Android SDK?

I am using Ionic 3.13.2, but I still have to use the workaround SDK, not the latest one (26.0.2)
