### ISSUE TITLE
Catch volume keys press. Can ionic do that?

### ISSUE THREAD

**Issue by ozzargueyo** [driftyco/ionic#10605]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
**Other information:**

Hello, I'm new with Ionic and the dev apps that I already develop worked smoothly. I'm trying with a new app and I need to catch the pressing of the  volume keys of the device. Is there a way to achieve this? What about the musicControls or NativeAudio plugins? 

Thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
