### ISSUE TITLE
EXCEPTION: Cannot read property 'scrollToBottom' of null

### ISSUE THREAD

**Issue by calidion** [driftyco/ionic#10601]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
EXCEPTION: Cannot read property 'scrollToBottom' of null
t.handleError @ main.js:64970
e.handleError @ main.js:137256
next @ main.js:40916
e.object.i @ main.js:42426
e.__tryOrUnsub @ main.js:5548
e.next @ main.js:5497
e._next @ main.js:5450
e.next @ main.js:5414
e.next @ main.js:10136
e.emit @ main.js:42418
t.triggerError @ main.js:43268
onHandleError @ main.js:43247
t.handleError @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3
e.args.(anonymous function) @ polyfills.js:2
main.js:64975 ORIGINAL STACKTRACE:
t.handleError @ main.js:64975
e.handleError @ main.js:137256
next @ main.js:40916
e.object.i @ main.js:42426
e.__tryOrUnsub @ main.js:5548
e.next @ main.js:5497
e._next @ main.js:5450
e.next @ main.js:5414
e.next @ main.js:10136
e.emit @ main.js:42418
t.triggerError @ main.js:43268
onHandleError @ main.js:43247
t.handleError @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3
e.args.(anonymous function) @ polyfills.js:2
main.js:64976 TypeError: Cannot read property 'scrollToBottom' of null
    at e.scrollToBottom (http://local.xiv.im:8100/build/main.js:6:21965)
    at t.<anonymous> (http://local.xiv.im:8100/build/main.js:28:24792)
    at t.invokeTask (http://local.xiv.im:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://local.xiv.im:8100/build/main.js:17:20009)
    at t.invokeTask (http://local.xiv.im:8100/build/polyfills.js:3:9659)
    at e.runTask (http://local.xiv.im:8100/build/polyfills.js:3:7083)
    at invoke (http://local.xiv.im:8100/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://local.xiv.im:8100/build/polyfills.js:2:30123)
t.handleError @ main.js:64976
e.handleError @ main.js:137256
next @ main.js:40916
e.object.i @ main.js:42426
e.__tryOrUnsub @ main.js:5548
e.next @ main.js:5497
e._next @ main.js:5450
e.next @ main.js:5414
e.next @ main.js:10136
e.emit @ main.js:42418
t.triggerError @ main.js:43268
onHandleError @ main.js:43247
t.handleError @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3
e.args.(anonymous function) @ polyfills.js:2
```

**Expected behavior:**
no such exception. 

**Steps to reproduce:**

I have checked all positions where using <code>scrollToBottom</code>, and add <code>xxx && xxx.scrollToBottom</code> to avoid null objects, but it happens still.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Could your please provide a repro case? You can use [this plunker](http://plnkr.co/edit/z0DzVL?p=preview) as a template.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by calidion** [comment]
@jgw96 
every easy to run into it again and again. but currently I can't figure out why.

**Comment by pablo-albaladejo** [comment]
@calidion I solved it whit this fix:

`if(this.content._scroll) this.content.scrollToBottom(0);`

**Comment by ahmadalfy** [comment]
@pablo-albaladejo That solution worked perfectly. My problem is that the initialized view that has scrolling gets closed before the data is loaded. The `_scroll` property evaluates to `null` on this case and it was throwing the error.

**Comment by bluzi** [comment]
@pablo-albaladejo Thanks, drove me crazy for days, owe you one.

**Comment by ShafiqEssani** [comment]
Thank you so very much @pablo-albaladejo ! <3

**Comment by mapplics** [comment]
@pablo-albaladejo Thanks! works like a charm!

**Comment by cjchrist777** [comment]
@pablo-albaladejo Thank you
