### ISSUE TITLE
Ionic datepicker min & max don't work on month & day

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10600]
I'm trying to use ionic 2 datepicker, it works but when I want to use min & max properties it doesn't work.

<ion-datetime displayFormat="DD-MM-YYYY"  [min]="today" [(ngModel)]="event.date.start"></ion-datetime>

'today': moment().format("YYYY-MM-DD")

It filter date only on years ! But I would like to have custom day and month.

Kindly Advice me,

Thanks & Regards

**Comment by manucorporat** [comment]
You should specify a [max] in the future

**Comment by rehannawab** [comment]
I think this issue is valid. If I set a 'min' date of the current year, the min date I suppose is set as 01-01-<current year>. So if I put min date as '2017-02-20' it starts from 01-01-2017, but setting it to '2016-02-20' works as expected.
