### ISSUE TITLE
feat(alert): Show the label for all the input types

### ISSUE THREAD

**Issue by elvandar06** [driftyco/ionic#10602]
**Ionic version:**
[x ] **2.x**

**I'm submitting a ...**
[x ] feature request

**Current behavior:**

The input's label is currently used for radio/checkbox inputs only.
It should be great to display the label for all the input types (over the input for example).

![image](https://cloud.githubusercontent.com/assets/24436588/23454571/f47ec596-fe6c-11e6-8310-0791070f5ed2.png)

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#122
