### ISSUE TITLE
bug: Sliding out a menu does not work on top of iframe

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#10619]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.1.0</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When the page contains an iframe then sliding out a menu is not possible when slide gesture is performed on top of iframe area. I'm not sure if it is possible but maybe you could switch listening events for menu slide gestures to global instead of local page.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
