### ISSUE TITLE
Right Chevron on List Item links & buttons

### ISSUE THREAD

**Issue by kfuchs** [driftyco/ionic#1061]
Currently, by default a right chevron symbol is placed on the right side of list items that are [links or buttons](http://ionicframework.com/docs/components/#item-icons). I think this is overly opinionated, rather then force an icon on the right side allow the developer to choose whether an icon appears or not. If the developer wants a chevron on the right side of a list-item they can do so by simply applying the icon to right like they would any other icon:

```
<a class="item item-icon-left item-icon-right" href="#">
  <i class="icon ion-email"></i>
  Check mail
  <i class="icon ion-chevron-right" style="color:#ccc; font-size:16px;"></i>
</a>
```

Note the extra styling is needed to make the chevron appear exactly the same as the current default chevron. I'd also like to point out having this chevron is not the norm UI for most app menus. 

related pull request #1060

**Comment by RickeyWard** [comment]
The docs are still not updated on this. Its 2017

**Comment by minimallinux** [comment]
Id like to remove the arrow on the right I don't think its necessary, just started with F7 does anyone know how to do this ? Thanks
