### ISSUE TITLE
Google Map and ad mob banner are not working in same page

### ISSUE THREAD

**Issue by jindaldipanshu** [driftyco/ionic#10618]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.1.4**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Google maps hide when i call the show banner 

**Expected behavior:**

google map are not hiding when i call the showBanner.we need the both google map and admob banner in same page.

**Steps to reproduce:**

1. Implement the google map 
2. test it and working fine
3. Implement the ad mob  in same page
4. Run it and google map hides.

[about.zip](https://github.com/driftyco/ionic/files/813256/about.zip)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
