### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by shanxueyi** [driftyco/ionic#10617]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Why www\build\main.js has 4M size, Release version also has 1M size。
How do I deploy the project to the server。
Mobile phone to open the remote web page is slow。

what do I do？

Thanks！

**Comment by pavimus** [comment]
You can setup gzip/deflate compression on your webserver. This will decrease traffic up to 3-5 times.

**Comment by graphefruit** [comment]
@shanxueyi This is not a feature request, this is a support request.
Thats why please ask this question in forum or slack.
But in normal you just can build browser or copy the finished WWW-Folder to your Apache e.g.
Greetings
Graphefruit

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
