### ISSUE TITLE
showWhen don't work

### ISSUE THREAD

**Issue by iumag** [driftyco/ionic#10625]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Docs website and my application don't work showWhen. ShowWhen work ios and windows. Android don't work

**Related code:**

```
<div showWhen="android">
 I am visible on Android!
</div>
```

**Other information:**

For Example, Docs

[http://ionicframework.com/docs/v2/api/components/show-hide-when/ShowWhen/](http://ionicframework.com/docs/v2/api/components/show-hide-when/ShowWhen/)

![](https://s8.hostingkartinok.com/uploads/images/2017/02/d1d68e61849ac61dd665e72c80f7c144.png)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#1005
