### ISSUE TITLE
discussion: call Ionic 2 just Ionic

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#10628]
In driftyco/ionic-app-scripts#197 @danbucholtz says

> We will detail TS 2.1 much more when we ship Ionic 3 with Angular 4 support.

If I guess right this means major version jumps will follow Angular's. As we know Angular 2.x, 3.x, etc is called just Angular, wouldn't it make sense to follow this scheme as well and call Ionic 2 just Ionic?

**Comment by mhartington** [comment]
Hi there! Thanks for your input, we'll talk about it amongst the team.
