### ISSUE TITLE
MD style guides for new split pane

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10623]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I show your new amazing split pane and have some feature request to respect more the google style guides for material design. In your case you have two panels, the left one and the right one and if the view is to small the left panel will hide which you can show up with the menu button. Now on epanded browser you have complete separate the left and right panel, see the screenshot There is line in the header between Menu and Map.

![image](https://cloud.githubusercontent.com/assets/3778892/23513836/c19e6d62-ff65-11e6-98cc-c2b2a3585dda.png)

**Expected behavior:**
I think it should be also possible share the header for the two panels, so the left and the right panel has the same header, this would respect more MD design and it would be as the new google contacts web app which is an amazing and beautiful MD app.
See this screenshots:
![image](https://cloud.githubusercontent.com/assets/3778892/23514022/4e364150-ff66-11e6-93db-66e529c95d69.png)
![image](https://cloud.githubusercontent.com/assets/3778892/23514054/5ef7ee3a-ff66-11e6-82aa-4a091df76e63.png)
![image](https://cloud.githubusercontent.com/assets/3778892/23514066/6a79fece-ff66-11e6-9249-5d443b3f29c1.png)

**I'm not sure if this is already possibile, if yes can you please share an example?**

**Comment by yozman** [comment]
@mburger81 
how did you do that?
![](https://cloud.githubusercontent.com/assets/3778892/23513836/c19e6d62-ff65-11e6-98cc-c2b2a3585dda.png)

could u show some example code?

**Comment by mburger81** [comment]
@yozman  I'm not  sure if I understand your question. The screenshot you copied is  only a screenshotot of the split pane blog from the ionic page.
http://blog.ionic.io/testing-split-pane-support/

**Comment by mburger81** [comment]
@manucorporat I think the implementation should not be to difficult, I tried to add an splitpane on a standard sidemenu template and move the header from the pages to the app.html

At the end the app.html page is something like that:
```
<ion-header>

  <ion-toolbar>
    <button ion-button icon-only menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>

    <ion-title>
      Page Title
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-split-pane (ionChange)="ionChange($event)">
  <!--  our side menu  -->
  <ion-menu [content]="content">
    <ion-header>
      <ion-toolbar>
        <ion-title>Menu</ion-title>
      </ion-toolbar>
    </ion-header>
  </ion-menu>

  <!-- the main content -->
  <ion-nav [root]="rootPage" main #content></ion-nav>
</ion-split-pane>
```

This could work, and also be the solution for this FR the only problem is the splitpane content is overlapped by the header, see screenshot:
![image](https://cloud.githubusercontent.com/assets/3778892/24194763/99909ba0-0ef7-11e7-8828-6e87e69617fb.png)


So if we are able to put splitpane under an header anything should be resolved

**Comment by mburger81** [comment]
This post implements the requested feature, (in a complicated way)  https://chrisgriffith.wordpress.com/2017/03/21/ionic-split-pane-part-2/

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#158
