### ISSUE TITLE
Not possible to add only platform specific styles

### ISSUE THREAD

**Issue by szankelDvag** [driftyco/ionic#10622]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In case you build for specific platform i. e. for ios the build adds component styles for all platforms, there are plenty of unnecessary css rules.

**Expected behavior:**
It should be possible to only include platform specific styles.

**Related code:**

component.scss

**Other information:**
We use ionic-app-scripts

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
-------------------
ionic-angular: 2.0.0

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#788

**Comment by szankelDvag** [comment]
You can close it. It is possible with appscripts
