### ISSUE TITLE
Observable.if is not working

### ISSUE THREAD

**Issue by RushabhJoshi** [driftyco/ionic#10620]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
For my requirement I want to get image url form local database and if url exist then I have to upload it to server, For this I am using `Observable.if`

in my console of chrome browser showing this error

TypeError: __WEBPACK_IMPORTED_MODULE_8_rxjs_Observable__.Observable.if is not a function

-->

**Related code:**

```
import { Observable } from 'rxjs/Observable';
import { Storage } from '@ionic/storage';

@Component({
  selector: 'test',
  templateUrl: 'test.html'
})
export class Test {
  construct(protected storage: Storage) {}
  method() {
    Observable.fromPromise(this.storage.get('image'))
      .flatMap(imagePath => {
        return Observable.if(
              function () { return false },
              this.auth.uploadLogo(imagePath)
            );
      }).subscribe();
  }
}
```

**Comment by realappie** [comment]
How did you get fromPromise to even work? It gives me type errors.

![error](http://image.prntscr.com/image/701ce21c0ce744a4a73d4a2312a72534.png)

**Comment by youssmak** [comment]
an import is missing : 
`import 'rxjs/add/observable/fromPromise';`

**Comment by RushabhJoshi** [comment]
Ok guys, I got the point
May be it was my luck that it run without any imports
but after importing required observable I face another issue

```
.flatMap(imagePath => {
  return Observable.if(
    function () { return !!imagePath },
    this.uploadService.uploadImage(imagePath)
    );
})
```

even if the condition is false it executes the uploadImage method of uploadService
this method returns promise 
And this method is using ionic native `Transfer` class

Thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by RushabhJoshi** [comment]
Thanks @jgw96
