### ISSUE TITLE
Application Error, The connection to the server was unsuccessful. (http://192.168.8.121:8100)

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10626]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Launching the app in android device with liveload and console output `ionic run android -lc` shows after a while this error:
![image](https://cloud.githubusercontent.com/assets/3778892/23514947/269d7660-ff69-11e6-9a66-85a6a623e1b4.png)

Our app is very very big with a lot of components and a lot of external angular and javascript libs. It takes also a long time in production `(--prod)` or on `run android` or` emulate android` mode to load the app, more then 10 seonds.

**Expected behavior:**
The error should not appear, and setting up the cordova timeout is not a solution (which btw also didn't work for me).
What can I do to resolve this and what can I do to speedup the loading of the app?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0-201702281739
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.10.0
Xcode version: Not installed

**Comment by NoNameProvided** [comment]
You should open this ticket at  [driftyco/ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts) instead of this repo.

**Comment by brandyscarney** [comment]
Closing this since it was opened on app-scripts, thanks!
