### ISSUE TITLE
Scroll not working on Android 2.3.6 Gingerbread

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic#1062]
I know this platform hasn't the highest priority but since I couldn't find any related issue report I'm reporting this anyway. 

On a `Samsung Galaxy S1` running `Android Gingerbread 2.3.6` I can't scroll any scrollable view. That about sums it up and doesn't need much extra explanation or a codepen since it happens in any scrollable view (`<ion-content scroll="true">`)

**Comment by eriwangi08** [comment]
I'm running android 5.1.1 on Samsung Galaxy Tab A (2016). I have implemented a webview and androidpdfviewer and i'm experiencing the scroll issue.
Kindly assist.

This is the sample code

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginBottom="30dp"
    android:layout_marginLeft="15dp"
    android:layout_marginRight="15dp"
    android:layout_marginTop="30dp"
    android:background="@color/white"
    android:orientation="vertical">

    
    <LinearLayout
        android:id="@+id/top_section"
        android:layout_width="match_parent"
        android:layout_height="24dp"
        android:layout_marginLeft="20dp"
        android:layout_marginRight="20dp"
        android:layout_marginTop="1dp"
        android:orientation="horizontal">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <sg.utmobile.core.ui.view.UtTextView
                android:id="@+id/text_form_title"
                style="@style/General.Component.Text.Header.Fragment"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:tag="text_form_title"
                android:text="Document Preview"
                android:visibility="visible" />

            <View
                android:id="@+id/header_line"
                style="@style/title_line"
                android:tag="header_line" />
        </LinearLayout>
    </LinearLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="850dp"
        android:layout_marginBottom="5dp"
        android:layout_marginTop="5dp"
        android:gravity="center">

        
        
        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="850dp">

            <sg.utmobile.core.ui.view.UtWebView
                android:id="@+id/grid_pdf_viewer"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="60dp"
                android:overScrollMode="always"
                android:tag="grid_pdf_viewer"
                android:visibility="visible"></sg.utmobile.core.ui.view.UtWebView>
        </ScrollView>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:orientation="horizontal">

            <sg.utmobile.core.ui.view.UtCheckbox
                android:id="@+id/chk_read_loan_doc"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:layout_marginLeft="8dp"
                android:button="@drawable/custom_checkbox_selector"
                android:checked="false"
                android:soundEffectsEnabled="false"
                android:tag="chk_read_loan_doc" />

            <sg.utmobile.core.ui.view.UtTextView
                android:id="@+id/txt_read_loan_doc"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="3dp"
                android:layout_marginTop="2dp"
                android:tag="txt_read_loan_doc"
                android:text="I have read and understood the loan document"
                android:textAllCaps="true"
                android:textColor="@color/black"
                android:textSize="16dp"
                mobile:font="Ubuntu-R" />

            <sg.utmobile.core.ui.view.UtButton
                android:id="@+id/button_dismiss"
                android:layout_width="wrap_content"
                android:layout_height="@dimen/component_height_normal"
                android:layout_alignParentRight="true"
                android:layout_marginLeft="10dp"
                android:layout_marginRight="2dp"
                android:layout_toRightOf="@id/button_clear"
                android:background="@drawable/form_button_selector"
                android:paddingLeft="12dp"
                android:paddingRight="12dp"
                android:singleLine="true"
                android:tag="button_dismiss"
                android:text="CONFIRM"
                android:textAllCaps="true"
                android:textColor="@color/text_color_1"
                android:textSize="@dimen/text_font_size_normal"
                mobile:font="Ubuntu-R" />

        </LinearLayout>
    </RelativeLayout>

</LinearLayout>
