### ISSUE TITLE
No access to class properties in virtual scroll list header functions

### ISSUE THREAD

**Issue by szerner** [driftyco/ionic#10633]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
As I have to deal with large lists, I heavily rely on Virtual Scroll lists. To group my items, I use a custom header function. So my code is like
Template:

```
<ion-list [virtualScroll]="filteredData" [headerFn]="dataHeaderFn">
  <ion-item-divider *virtualHeader="let groupheader">
    {{groupheader}}
  </ion-item-divider>
  <button ion-item *virtualItem="let data"> ... </button>
</ion-list>
```

And my corresponding typescript:

```
someProperty;
...
constructor( private myService: MyService,...) { ... }
...
dataHeaderFn (dataItem, dataIndex, data) {
  let propertyTest = this.someProperty; //runtime error!
  let serviceTest = this.myService.doSomething(); //runtime error!
}
```

Now my problem is, that I cannot access my class properties or my injected services within the header function "dataHeaderFn": `this.someProperty` and `this.myService` are both undefined within the function scope.

When debugging the header function with chrome, I see that "`this`" within the function scope is of type "`ComponentRef_`" and has a property "`_component`", which finally refers to my component and its properties/services.

Yet simply saying "`this._component.someProperty`" doesn't compile, so I tried to do a type assertion for "this":

```
import { ComponentRef_ } from '@angular/core/src/linker/component_factory'; //the right one?
...
dataHeaderFn (dataItem, dataIndex, data) {
  let propertyTest = (this as any as ComponentRef_<any>)._component.someProperty;
}
```

But my compiler now complains that

> [ts] Property '_component' is private and only accessible within class 'ComponentRef_<C>'.

So is it really impossible to gain access to class properties within a custom header function?
This once worked in a previous framework version, so I don't know if its a bug or a feature request ;-)

**Expected behavior:**
I would like to have access to my class properties and services within my custom header function in order to customise the header functionality.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](htts://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by b1ueRa1n** [comment]
I have this problem too. Have you solved it?

**Comment by b1ueRa1n** [comment]
I had find a solution!
dataHeaderFn = (dataItem, dataIndex, data) => {
  // "this" should be set properly in here
};

https://forum.ionicframework.com/t/no-access-to-class-properties-and-injected-services-in-virtual-scroll-header-functions/81680/2
