### ISSUE TITLE
isScrolling not work on iOS

### ISSUE THREAD

**Issue by luisbahamonde** [driftyco/ionic#10630]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
isScrolling It always returns false on my iOS device. When I test in the browser (ionic serve) it works correctly. I'm not try on Android.

**Expected behavior:**
Should return true when content is scrolling

**Related code:**
`
if(this.content.isScrolling){
     //do something
}
`

**Comment by jgw96** [comment]
Thanks, we will look into this.

**Comment by manucorporat** [comment]
isScrolling() does not work in UIWebView becuase of native limitations, UIWebView does not fire the `onscroll` events as it should.

Please try WKWebView, it is the only solution if you depend of scrolling events.
