### ISSUE TITLE
Uh oh! There's a syntax error in your ionic.config.json file: SyntaxError: Unexpected token } in JSON at position 82

### ISSUE THREAD

**Issue by ferminako** [driftyco/ionic#10631]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

As soon as you include in your ionic.config.json a proxie list like:
"proxies": [
    {
      "path": "/v1",
      "proxyUrl": "https://api.instagram.com/v1"
    }
  ]

Run ionic serve, and then you remove this proxies variable, each time you try tu run ionic serve you get this error:

Uh oh! There's a syntax error in your ionic.config.json file: SyntaxError: Unexpected token } in JSON at position (line)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.19
Node Version: v6.10.0
Xcode version: Not installed
```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1952
