### ISSUE TITLE
50+ ionic-angular Toasts crashes on iOS

### ISSUE THREAD

**Issue by chrisjdev** [driftyco/ionic#10637]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I wrote a small test program that creates 55 Toasts and displays them. It crashes around the 50th toast on my iPad Air. 

**Expected behavior:**
Displays all 55 Toasts back to back.

**Steps to reproduce:**

See Related Code, run on iOS device. Potentially increase number of toasts on a device newer than an iPad Air.

**Related code:**

```
import { Component } from '@angular/core';
import { Toast, ToastController } from 'ionic-angular';

import { NavController } from 'ionic-angular';

@Component({
    selector: 'page-home',
    templateUrl: 'home.html'
})
export class HomePage {

    constructor(public navCtrl: NavController, public toastCtrl: ToastController) {

    }

    public runTest(): void {
        console.log('test running.');
        for (let i = 0; i < 50; ++i) {
            let options: Object = {
                message: 'Toast # ' + i,
                duration: 3000,
                position: 'bottom',
                showCloseButton: true,
            };
            let toast: Toast = this.toastCtrl.create(options);
            toast.present();
        }
        console.log('test complete.');
    }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! `toast` is not meant to be opened this many times back to back, in fact im pretty sure generating any element this many times back to back would cause the webview to crash. Because of this I am going to close this issue for now.

**Comment by chrisjdev** [comment]
Ok, thank you very much.
