### ISSUE TITLE
Support typescript 2.1.x

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic#10643]
**Ionic version:**  (check one with "x")
[ ] 2.1.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

run android do not  support type script 2.1

**Expected behavior:**

Support it

**Steps to reproduce:**
install start app
change version of app script 2.1.5
npm install --save-dev

ionic run android --prod

**Related code:**

**Other information:**

It will be really nice to support as 2.1 finally propose async await and other wonderfull features

Thansk in advance ionic team and continue like this

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The upcoming release will be using TypeScript 2.1 🎉 , in fact its already merged into the master branch of the framework.

**Comment by speedfl** [comment]
Hey as usual you are wonderfull !!! I will Wait for it.
Continue like this
