### ISSUE TITLE
View is not updating version 2.2.1

### ISSUE THREAD

**Issue by partharanjan** [driftyco/ionic#10642]
Hi I have issue with latest ionic version 2.2.1.

When I am changing any thing in view live reload updating everything except html view page. 
Every time I need to rerun the command to update the view.

Is there any special command or any setting to do this.

Please help me ASAP.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
