### ISSUE TITLE
Attribute changes in templates not reflecting when using live reloading

### ISSUE THREAD

**Issue by aplimovil** [driftyco/ionic#10640]
**Ionic version:**
[x] **2.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When I make a change to an attribute of an element in a template (.html file of a page) using live reloading, the app refreshes and the live reloading is triggered, but when I check the updated page template in the app, the changes are not reflected, almost as if the attributes of the elements of the template are being cached.

Note that if other aspects of the template like structure or added/removed elements do work correctly, it's only attribute changes that aren't being reflected with live reloading.

If I terminate the "ionic serve" process and run it again, then the template is now updated correctly with the attribute changes.

This started happening after I upgraded to the 2.0.1 release from the 2.0.0 version. I just updated to 2.1.0 to check if the bug was fixed but it's not, it's still hapenning.

**Expected behavior:**
All template changes should be reflected immediately on live reloading.

**Steps to reproduce:**
Run "ionic serve" with live reloading, make a change to a template, wait for the app to reload (on browser or device), and the change will not be reflected.

Here's a link to a screencast I recorded showing the problem, where I update a template by adding a padding attribute to 2 DIVs so they have padding, but after live reloading no padding is added:
http://quick.as/0vnVcvx16

**Ionic info:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: OS X Mavericks
Node Version: v6.2.0
Xcode version: Xcode 6.2 Build version 6C131e
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#794

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#284

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#285
