### ISSUE TITLE
Consume API using laravel

### ISSUE THREAD

**Issue by fredroo** [driftyco/ionic#10653]
Hi, i have an API with laravel 

this API using social login (facebook, google plus and twitter) socialite

i need use this login social to login users in my app and return token for more calls from app to api laravel

**Comment by AmitMY** [comment]
For facebook, there is a plugin called `cordova-plugin-facebook4`.
Use Angular's HTTP for talking to your server, and save that token on localstorage/nativestorage.

This "issue" is a support request. For support, please use the ionic forum: forum.ionicframework.com
Here you should only post bugs and feature requests.

**Comment by manucorporat** [comment]
@AmitMY is right. Unfortunately this is not the place for support requests.
