### ISSUE TITLE
Glossary link in Ionic V2 Tools documentation points to the wrong url 

### ISSUE THREAD

**Issue by thepiyush13** [driftyco/ionic#10656]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Navigating to https://ionicframework.com/docs/v2/resources/#/tools and then clicking Glossary opens up the http://localhost:3003/docs/v2/resources/what-is/ which seems to be invalid. The page looks like a development url and was probably accidentally injected within the documentation.
**Expected behavior:**

The link should open a public page and not a localhost page
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AlQuraian** [comment]
There's a repo specifically for the ionic website over here:
https://github.com/driftyco/ionic-site/

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1009
