### ISSUE TITLE
Loading controller not working properly in the latest nightly

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic#10654]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When you create and dismiss two loading components one after another, the second one is never dismissed, no matter if you use `.dismiss()` or `.dismissAll()`

**Expected behavior:**

The loading component is dismissed properly.

**Steps to reproduce:**
1. `npm install ionic-angular@nightly`

**Related code:**

```
    let loading = this.loadingCtrl.create({});
 
    loading.present();
 
    loading.dismiss();

    let loading2 = this.loadingCtrl.create({});
 
    loading2.present();
 
    loading2.dismiss();
```

This was working ok on stable 2.1.0

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.1.0-201703032024
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment]
Regression introduced by this change:
https://github.com/driftyco/ionic/commit/5a4c6093a72059577544dafe372e06018ee1ed19#diff-4fbdcb4f2c1fdfa3a66827a1377c351bL223
