### ISSUE TITLE
[ionic2] Map - Marker click not working

### ISSUE THREAD

**Issue by jlno** [driftyco/ionic#10658]
This listener not work:
```
this.map.addMarker(markerOptions).then((marker: GoogleMapsMarker) => {
  marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe(() => alert());
});
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
