### ISSUE TITLE
Uncaught TypeError: r[t] is not a function/ https://apis.google.com

### ISSUE THREAD

**Issue by jlsuarezs** [driftyco/ionic#10669]
Hi,

I am trying to get angularfire2 to work with Ionic 2 in a PWA and for some reason I am always getting this error:

Uncaught TypeError: r[t] is not a function
    at Object.Y.x.(anonymous function) [as loaded_0] (https://apis.google.com/js/api.js?onload=__iframefcb740853:10:484)
    at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.HUGusW2Obik.O/m…d=1/ed=1/am=AQ/rs=AGLTcCMQfcTc_uts7vlIlqUhKKWbRzGreA/cb=gapi.loaded_0:1:15
Y.x.(anonymous function) @ api.js?onload=__iframefcb740853:10
(anonymous) @ cb=gapi.loaded_0:1
error_handler.js:47 

EXCEPTION: The operation has timed out.

My info:

Ionic Framework: 2.0.1
Ionic Native: ^2.8.0
Ionic App Scripts: 1.1.4
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

Any way to solve the issue? Thanks.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by sv** [comment]
Is there a solution to this issue? We have same problem quite frequently

**Comment by victoriafrench** [comment]
Seeing the issue on an existing app as well with the latest version. But i am only seeing it when chrome is emulating the iPhone. In normal mode it works fine.

**Comment by arcio** [comment]
I can confirm victoriaFrench. It does only happen when emulating in the iphone in chrome. I have my product working live on a device right now and all is well.

**Comment by arcio** [comment]
I can confirm victoriaFrench. It does only happen when emulating in the iphone in chrome. I have my product working live on a device right now and all is well.
