### ISSUE TITLE
builtin support for font-awesome?

### ISSUE THREAD

**Issue by calidion** [driftyco/ionic#10668]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
only integrated with ionicons

**Expected behavior:**
integrated with font-awesome

**Comment by AmitMY** [comment]
The way I see it, font-awesome does not look like phone icons, and such will give a different experience than expected from an app. It would fill not native

**Comment by seiyria** [comment]
I think it would be better to allow you to extend ion-icon generally, because if you integrate font awesome, then you'll have to integrate every icon font under the son.

**Comment by AmitMY** [comment]
@seiyria Well, you can write your own component such that you could do:
`<app-icon type="ionic" name="close"></app-icon>` or `<app-icon type="fa" name="check"></app-icon>`

**Comment by seiyria** [comment]
@AmitMY that's true, but that won't let you use FA in place of ionicons for tab icons, or any other place where ionic has icons built in.

**Comment by alexbainbridge** [comment]
@seiyria  You can use FA icons on tab icons. There is a bit of a trick to it, but follow the link to the forums from here and it works

https://github.com/driftyco/ionic/issues/5823

**Comment by seiyria** [comment]
@alexbainbridge I see. I didn't know that (I'm not particularly interested in doing it) but it sounds like it's not a first-class support sorta thing. I think that's the point here.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#124
