### ISSUE TITLE
Add width-100 as an attribute for ion-col

### ISSUE THREAD

**Issue by billygerhard** [driftyco/ionic#10666]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
With <ion-row wrap> you can have the rows automatically wrap based on <ion-col width-xx> where xx + yy=100, but if you want one just one column on a single row, there is no width-100. This would make layouts very easy without having to override and manipulate the CSS and/or adding new rows to the grid layout.

**Expected behavior:**
Be able to add width-100 to an <ion-col>

**Steps to reproduce:**
add width-100 to an <ion-col>

**Related code:**

```
<ion-grid>
   <ion-row wrap>
      <ion-col width-50>Row 1 Column 1, half the row</ion-col>
      <ion-col width-50>Row 1 Column 2, half the row</ion-col>
      <ion-col width-100>Row 2, only column, full row</ion-col>
   </ion-row>
</ion-grid>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by Sh1d0w** [comment]
If you omit the width attribute it is with width 100% by default : http://plnkr.co/edit/Jl9DmA5wdlTmHYdxMjji?p=preview

**Comment by zakton5** [comment]
With the addition of the built-in `wrap` attribute, this seems like a good idea.

**Comment by brandyscarney** [comment]
With the new grid system this shouldn't be an issue. Please see the blog post here on it: http://blog.ionic.io/build-awesome-desktop-apps-with-ionics-new-responsive-grid/

The API docs for it are here: http://ionicframework.com/docs/v2/api/components/grid/Grid/

What you're looking for:

```
<ion-grid>
   <ion-row>
      <ion-col col-6>Row 1 Column 1, half the row</ion-col>
      <ion-col col-6>Row 1 Column 2, half the row</ion-col>
      <ion-col col-12>Row 2, only column, full row</ion-col>
   </ion-row>
</ion-grid>
```
