### ISSUE TITLE
bug: Password reset corrections

### ISSUE THREAD

**Issue by mika-lsv** [driftyco/ionic#10660]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I use your password reset form, I receive 2 same email with the reset link. And when I go to the link the text ask me to enter my email for verification and my new password, there is no email input in this page.
And when I finish and clic send there is no confirm message.
The function work well but there is few issues.
Thanks for your work</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1010
