### ISSUE TITLE
process.stdout.getWindowSize is not a function

### ISSUE THREAD

**Issue by bradrust** [driftyco/ionic#10670]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
"ionic package" commands are not usable other than via interactive terminals

**Expected behavior:**
we should be able to automate (grep, pipe, redirect, etc...) the use of "ionic package" commands.  For example, to execute deterministic and automated configuration management processes ... like building releases.

**Steps to reproduce:**

from a bash shell
  ionic package list | grep SUCCESS

**Other information:**
```
TypeError: process.stdout.getWindowSize is not a function
    at /usr/lib/node_modules/ionic/lib/ionic/package.js:183:42
    at _fulfilled (/usr/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1957
