### ISSUE TITLE
Form Bug with Ion-Input

### ISSUE THREAD

**Issue by zodiark23** [driftyco/ionic#10671]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Form Submit while pressing `Enter Key` does not submit if the inputs are <ion-inputs>
`
<ion-input  formControlName="user_id"   type="text" name="user_id" id="" placeholder="아이디(이메일)"></ion-input>
    <ion-input  formControlName="user_pass"  type="password" name="user_pass" id="비밀번호" placeholder="비밀번호" ></ion-input>
`
>Does not submit on enter

**Expected behavior:**
Pressing `Enter Key` should submit the form. Works well if the ion-inputs is replace by normal inputs types.

`
<input  formControlName="user_id"   type="text" name="user_id" id="" placeholder="아이디(이메일)"/>
    <input  formControlName="user_pass"  type="password" name="user_pass" id="비밀번호" placeholder="비밀번호" />
`
>Submits on enter.

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us. We will look into this.

**Comment by jgw96** [comment]
Does this happen on both Android and iOS?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Rijwandeltax** [comment]
i have problem in ionic form, when i touch the form its jump and create extra space in bottom..
