### ISSUE TITLE
switching theme by the user

### ISSUE THREAD

**Issue by salimmejdoub** [driftyco/ionic#10679]
Hello how can i let the user switch theme of the application 
i can't find a good tutorial
anyone can help 
ionic 2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
