### ISSUE TITLE
<ion-datetime> use several items on a page

### ISSUE THREAD

**Issue by esase** [driftyco/ionic#10674]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I init two items on a page, e.x.:
```
<ion-datetime displayFormat="{{question.displayFormat}}"
                  monthNames="January, February, March, April, May, June, July, August, September, October, November, December"
                  monthShortNames="Jan., Feb., Mar., Apr., May, Jun., Jul., Aug., Sep., Oct., Nov., Dec."
                  dayNames="Sunday, Monday, Tuesday, Wednesday Thursday, Friday, Saturday"
                  dayShortNames="Sun., Mon., Tue., Wed., Thu., Fri., Sat."
                  min="{{question.minDate}}"
                  max="{{question.maxDate}}"
                  [formControlName]="question.key"
                  [id]="question.key"
                  placeholder="Choose date"
                  cancelText="{{ 'cancel' | translate }}"
                  doneText="{{ 'done' | translate }}"></ion-datetime>
</ion-item>
```
There are two diffrent ion-datetimes with different mix and max params. But I always see datetime items with the same params (min and max) 

**Expected behavior:**

There are should be two date items with different params

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
