### ISSUE TITLE
i m not able to build in prod mode . 

### ISSUE THREAD

**Issue by abmnukmr** [driftyco/ionic#10672]
L120:          SMALL

            Duplicate identifier 'SMALL'.

     L123:      export enum ControlPosition {

            Duplicate identifier 'BOTTOM_CENTER'.

     L125:  BOTTOM_LEFT,
     L126:  BOTTOM_RIGHT,
     L127:  LEFT_BOTTOM,

            Duplicate identifier 'BOTTOM_LEFT'.

     L126:  BOTTOM_RIGHT,
     L127:  LEFT_BOTTOM,
     L128:  LEFT_CENTER,

            Duplicate identifier 'BOTTOM_RIGHT'.

     L127:  LEFT_BOTTOM,
     L128:  LEFT_CENTER,
     L129:  LEFT_TOP,

            Duplicate identifier 'LEFT_BOTTOM'.

     L128:  LEFT_CENTER,
     L129:  LEFT_TOP,  
     L130:  RIGHT_BOTTOM,

            Duplicate identifier 'LEFT_CENTER'.

     L129:  LEFT_TOP,
     L130:  RIGHT_BOTTOM,
     L131:  RIGHT_CENTER,

            Duplicate identifier 'LEFT_TOP'.

     L130:  RIGHT_BOTTOM,
     L131:  RIGHT_CENTER,
     L132:  RIGHT_TOP,

            Duplicate identifier 'RIGHT_BOTTOM'.

     L131:  RIGHT_CENTER,
     L132:  RIGHT_TOP,  
     L133:  TOP_CENTER,

            Duplicate identifier 'RIGHT_CENTER'.

     L132:  RIGHT_TOP,
     L133:  TOP_CENTER, 
     L134:  TOP_LEFT,

            Duplicate identifier 'RIGHT_TOP'.

     L133:  TOP_CENTER,
     L134:  TOP_LEFT,
     L135:  TOP_RIGHT

            Duplicate identifier 'TOP_CENTER'.

     L134:      TOP_LEFT,
     L135:      TOP_RIGHT 

            Duplicate identifier 'TOP_LEFT'.

     L135:          TOP_RIGHT

            Duplicate identifier 'TOP_RIGHT'.

     L138:      /***** Data *****/

            Duplicate identifier 'Data'.

     L140:  constructor(options?: Data.DataOptions);
     L141:  add(feature: Data.Feature|Data.FeatureOptions): Data.Feature;
     L142:  addGeoJson(geoJson: Object, options?: Data.GeoJsonOptions): Data.Feature[];

            Duplicate identifier 'Data'.

     L164:  export interface DataOptions {
     L165:      controlPosition?: ControlPosition;
     L166:      controls?: string[];

            Duplicate identifier 'Marker'.

     L306:  static MAX_ZINDEX: number;
     L307:  constructor(opts?: MarkerOptions);
     L308:  getAnimation(): Animation;

            Duplicate identifier 'BACKWARD_CLOSED_ARROW'.

     L525:  /** A backward-pointing open arrow. */
     L526:  BACKWARD_OPEN_ARROW, 
     L527:  /** A circle. */

            Duplicate identifier 'BACKWARD_OPEN_ARROW'.

     L527:  /** A circle. */
     L528:  CIRCLE,            
     L529:  /** A forward-pointing closed arrow. */

            Duplicate identifier 'CIRCLE'.

     L529:  /** A forward-pointing closed arrow. */
     L530:  FORWARD_CLOSED_ARROW,
     L531:  /** A forward-pointing open arrow. */

            Duplicate identifier 'FORWARD_CLOSED_ARROW'.

     L531:      /** A forward-pointing open arrow. */
     L532:      FORWARD_OPEN_ARROW  

            Duplicate identifier 'FORWARD_OPEN_ARROW'.

     L535:      export enum Animation {

            Duplicate identifier 'BOUNCE'.

     L537:          DROP

            Duplicate identifier 'DROP'.

            Duplicate identifier 'InfoWindow'.

     L546:   * Creates an info window with the given options. An InfoWindow can be
     L547:   * placed on a map at a particular position or above a marker,

            Duplicate identifier 'Polyline'.

     L614:  constructor(opts?: PolylineOptions);
     L615:  getDraggable(): boolean;
     L616:  getEditable(): boolean;

            Duplicate identifier 'Polygon'.

     L651:  constructor(opts?: PolygonOptions);
     L652:  getDraggable(): boolean;
     L653:  getEditable(): boolean;

            Duplicate identifier 'Rectangle'.

     L737:  constructor(opts?: RectangleOptions);
     L738:  getBounds(): LatLngBounds;
     L739:  getDraggable(): boolean;

            Duplicate identifier 'Circle'.

     L768:  constructor(opts?: CircleOptions);
     L769:  getBounds(): LatLngBounds;
     L770:  getCenter(): LatLng;

            Duplicate identifier 'CENTER'.

     L811:  /** The stroke lies inside the polygon. */
     L812:  INSIDE,
     L813:  /** The stroke lies outside the polygon. */

            Duplicate identifier 'INSIDE'.

     L813:      /** The stroke lies outside the polygon. */
     L814:      OUTSIDE

            Duplicate identifier 'OUTSIDE'.

     L817:      export class GroundOverlay extends MVCObject {

            Duplicate identifier 'GroundOverlay'.

     L818:  constructor(url: string, bounds: LatLngBounds, opts?: GroundOverlayOptions);
     L819:  getBounds(): LatLngBounds;
     L820:  getMap(): Map;

            Duplicate identifier 'OverlayView'.

     L834:  draw(): void;
     L835:  getMap(): Map|StreetViewPanorama;
     L836:  getPanes(): MapPanes;

            Duplicate identifier 'MapCanvasProjection'.

     L855:  fromContainerPixelToLatLng(pixel: Point, nowrap?: boolean): LatLng;
     L856:  fromDivPixelToLatLng(pixel: Point, nowrap?: boolean): LatLng;
     L857:  fromLatLngToContainerPixel(latLng: LatLng): Point;

            Duplicate identifier 'Geocoder'.

     L864:          geocode(request: GeocoderRequest, callback: (results: GeocoderResult[], status: GeocoderStatus) => void ): void;

            Duplicate identifier 'ERROR'.

     L886:  INVALID_REQUEST,
     L887:  OK,  
     L888:  OVER_QUERY_LIMIT,

            Duplicate identifier 'INVALID_REQUEST'.

     L887:  OK,
     L888:  OVER_QUERY_LIMIT,
     L889:  REQUEST_DENIED,

            Duplicate identifier 'OK'.

     L888:  OVER_QUERY_LIMIT,
     L889:  REQUEST_DENIED,
     L890:  UNKNOWN_ERROR,

            Duplicate identifier 'OVER_QUERY_LIMIT'.

     L889:  REQUEST_DENIED,
     L890:  UNKNOWN_ERROR,  
     L891:  ZERO_RESULTS

            Duplicate identifier 'REQUEST_DENIED'.

     L890:      UNKNOWN_ERROR,
     L891:      ZERO_RESULTS  

            Duplicate identifier 'UNKNOWN_ERROR'.

     L891:          ZERO_RESULTS

            Duplicate identifier 'ZERO_RESULTS'.

     L894:      export interface GeocoderResult {

            Duplicate identifier 'APPROXIMATE'.

     L919:  GEOMETRIC_CENTER,
     L920:  RANGE_INTERPOLATED,
     L921:  ROOFTOP

            Duplicate identifier 'GEOMETRIC_CENTER'.

     L920:      RANGE_INTERPOLATED,
     L921:      ROOFTOP         

            Duplicate identifier 'RANGE_INTERPOLATED'.

     L921:          ROOFTOP

            Duplicate identifier 'ROOFTOP'.

     L924:      export class DirectionsRenderer extends MVCObject {

            Duplicate identifier 'DirectionsRenderer'.

     L925:  constructor(opts?: DirectionsRendererOptions);
     L926:  getDirections(): DirectionsResult;
     L927:  getMap(): Map;

            Duplicate identifier 'DirectionsService'.

     L955:          route(request: DirectionsRequest, callback: (result: DirectionsResult, status: DirectionsStatus) => void ): void;

            Duplicate identifier 'BICYCLING'.

     L977:  DRIVING,
     L978:  TRANSIT, 
     L979:  WALKING

            Duplicate identifier 'DRIVING'.

     L978:      TRANSIT,
     L979:      WALKING

            Duplicate identifier 'TRANSIT'.

     L979:          WALKING

            Duplicate identifier 'WALKING'.

     L982:      export enum UnitSystem {

            Duplicate identifier 'IMPERIAL'.

     L984:          METRIC

            Duplicate identifier 'METRIC'.

     L987:      export interface TransitOptions {

            Duplicate identifier 'BUS'.

     L996:  RAIL,
     L997:  SUBWAY,
     L998:  TRAIN,

            Duplicate identifier 'RAIL'.

     L997:  SUBWAY,
     L998:  TRAIN,
     L999:  TRAM

            Duplicate identifier 'SUBWAY'.

     L998:      TRAIN,
     L999:      TRAM  

            Duplicate identifier 'TRAIN'.

     L999:          TRAM

            Duplicate identifier 'TRAM'.

    L1002:      export enum TransitRoutePreference

            Duplicate identifier 'FEWER_TRANSFERS'.

    L1005:          LESS_WALKING

            Duplicate identifier 'LESS_WALKING'.

    L1008:      export interface TransitFare { }

            Duplicate identifier 'BEST_GUESS'.

    L1018:      OPTIMISTIC,
    L1019:      PESSIMISTIC

            Duplicate identifier 'OPTIMISTIC'.

    L1019:          PESSIMISTIC

            Duplicate identifier 'PESSIMISTIC'.

    L1022:      export interface DirectionsWaypoint {

            Duplicate identifier 'INVALID_REQUEST'.

    L1029:  MAX_WAYPOINTS_EXCEEDED,
    L1030:  NOT_FOUND,     
    L1031:  OK,

            Duplicate identifier 'MAX_WAYPOINTS_EXCEEDED'.

    L1030:  NOT_FOUND,
    L1031:  OK,                   
    L1032:  OVER_QUERY_LIMIT,

            Duplicate identifier 'NOT_FOUND'.

    L1031:  OK,
    L1032:  OVER_QUERY_LIMIT,
    L1033:  REQUEST_DENIED,

            Duplicate identifier 'OK'.

    L1032:  OVER_QUERY_LIMIT,
    L1033:  REQUEST_DENIED,
    L1034:  UNKNOWN_ERROR,

            Duplicate identifier 'OVER_QUERY_LIMIT'.

    L1033:  REQUEST_DENIED,
    L1034:  UNKNOWN_ERROR,  
    L1035:  ZERO_RESULTS

            Duplicate identifier 'REQUEST_DENIED'.

    L1034:      UNKNOWN_ERROR,
    L1035:      ZERO_RESULTS  

            Duplicate identifier 'UNKNOWN_ERROR'.

    L1035:          ZERO_RESULTS

            Duplicate identifier 'ZERO_RESULTS'.

    L1038:      export interface DirectionsResult {

            Duplicate identifier 'BUS'.

    L1138:  CABLE_CAR,
    L1139:  COMMUTER_TRAIN,
    L1140:  FERRY,

            Duplicate identifier 'CABLE_CAR'.

    L1139:  COMMUTER_TRAIN,
    L1140:  FERRY,   
    L1141:  FUNICULAR,

            Duplicate identifier 'COMMUTER_TRAIN'.

    L1140:  FERRY,
    L1141:  FUNICULAR,    
    L1142:  GONDOLA_LIFT,

            Duplicate identifier 'FERRY'.

    L1141:  FUNICULAR,
    L1142:  GONDOLA_LIFT,
    L1143:  HEAVY_RAIL,

            Duplicate identifier 'FUNICULAR'.

    L1142:  GONDOLA_LIFT,
    L1143:  HEAVY_RAIL,
    L1144:  HIGH_SPEED_TRAIN,

            Duplicate identifier 'GONDOLA_LIFT'.

    L1143:  HEAVY_RAIL,
    L1144:  HIGH_SPEED_TRAIN,
    L1145:  INTERCITY_BUS,

            Duplicate identifier 'HEAVY_RAIL'.

    L1144:  HIGH_SPEED_TRAIN,
    L1145:  INTERCITY_BUS,
    L1146:  METRO_RAIL,

            Duplicate identifier 'HIGH_SPEED_TRAIN'.

    L1145:  INTERCITY_BUS,
    L1146:  METRO_RAIL,     
    L1147:  MONORAIL,

            Duplicate identifier 'INTERCITY_BUS'.

    L1146:  METRO_RAIL,
    L1147:  MONORAIL,    
    L1148:  OTHER,

            Duplicate identifier 'METRO_RAIL'.

    L1147:  MONORAIL,
    L1148:  OTHER,    
    L1149:  RAIL,

            Duplicate identifier 'MONORAIL'.

    L1148:  OTHER,
    L1149:  RAIL,   
    L1150:  SHARE_TAXI,

            Duplicate identifier 'OTHER'.

    L1149:  RAIL,
    L1150:  SHARE_TAXI,
    L1151:  SUBWAY,

            Duplicate identifier 'RAIL'.

    L1150:  SHARE_TAXI,
    L1151:  SUBWAY,
    L1152:  TRAM,

            Duplicate identifier 'SHARE_TAXI'.

    L1151:  SUBWAY,
    L1152:  TRAM,     
    L1153:  TROLLEYBUS

            Duplicate identifier 'SUBWAY'.

    L1152:      TRAM,
    L1153:      TROLLEYBUS

            Duplicate identifier 'TRAM'.

    L1153:          TROLLEYBUS

            Duplicate identifier 'TROLLEYBUS'.

    L1156:      export class ElevationService {

            Duplicate identifier 'ElevationService'.

    L1157:      getElevationAlongPath(request: PathElevationRequest, callback: (results: ElevationResult[], status: ElevationStatus) => void ): void;
    L1158:      getElevationForLocations(request: LocationElevationRequest, callback: (results: ElevationResult[], statu

            Duplicate identifier 'INVALID_REQUEST'.

    L1178:  OK,
    L1179:  OVER_QUERY_LIMIT,
    L1180:  REQUEST_DENIED,

            Duplicate identifier 'OK'.

    L1179:  OVER_QUERY_LIMIT,
    L1180:  REQUEST_DENIED,
    L1181:  UNKNOWN_ERROR

            Duplicate identifier 'OVER_QUERY_LIMIT'.

    L1180:      REQUEST_DENIED,
    L1181:      UNKNOWN_ERROR   

            Duplicate identifier 'REQUEST_DENIED'.

    L1181:          UNKNOWN_ERROR

            Duplicate identifier 'UNKNOWN_ERROR'.

    L1184:      export class MaxZoomService {

            Duplicate identifier 'MaxZoomService'.

    L1185:          getMaxZoomAtLatLng(latlng: LatLng|LatLngLiteral, callback: (result: MaxZoomResult) => void ): void;

            Duplicate identifier 'ERROR'.

    L1195:          OK

            Duplicate identifier 'OK'.

    L1198:      export class DistanceMatrixService {

            Duplicate identifier 'DistanceMatrixService'.

    L1199:          getDistanceMatrix(request: DistanceMatrixRequest, callback: (response: DistanceMatrixResponse, status: DistanceMatrixStatus) => void ): void;

            Duplicate identifier 'INVALID_REQUEST'.

    L1236:  MAX_DIMENSIONS_EXCEEDED,
    L1237:  MAX_ELEMENTS_EXCEEDED,
    L1238:  OK,

            Duplicate identifier 'MAX_DIMENSIONS_EXCEEDED'.

    L1237:  MAX_ELEMENTS_EXCEEDED,
    L1238:  OK,                    
    L1239:  OVER_QUERY_LIMIT,

            Duplicate identifier 'MAX_ELEMENTS_EXCEEDED'.

    L1238:  OK,
    L1239:  OVER_QUERY_LIMIT,    
    L1240:  REQUEST_DENIED,

            Duplicate identifier 'OK'.

    L1239:  OVER_QUERY_LIMIT,
    L1240:  REQUEST_DENIED,
    L1241:  UNKNOWN_ERROR

            Duplicate identifier 'OVER_QUERY_LIMIT'.

    L1240:      REQUEST_DENIED,
    L1241:      UNKNOWN_ERROR   

            Duplicate identifier 'REQUEST_DENIED'.

    L1241:          UNKNOWN_ERROR

            Duplicate identifier 'UNKNOWN_ERROR'.

    L1244:      export enum DistanceMatrixElementStatus {

            Duplicate identifier 'NOT_FOUND'.

    L1246:      OK,
    L1247:      ZERO_RESULTS

            Duplicate identifier 'OK'.

    L1247:          ZERO_RESULTS

            Duplicate identifier 'ZERO_RESULTS'.

    L1250:      /***** Save to Google Maps *****/

            Duplicate identifier 'SaveWidget'.

    L1264:  constructor(container: Node, opts?: SaveWidgetOptions);
    L1265:  getAttribution(): Attribution;
    L1266:  getPlace(): Place;

            Duplicate identifier 'MapTypeRegistry'.

    L1291:      constructor();
    L1292:      set(id: string, mapType: MapType): void;

            Duplicate identifier 'ImageMapType'.

    L1301:  constructor(opts: ImageMapTypeOptions);
    L1302:  getOpacity(): number;
    L1303:  getTile(tileCoord: Point, zoom: number, ownerDocument: Document): Element;

            Duplicate identifier 'StyledMapType'.

    L1319:  constructor(styles: MapTypeStyle[], options?: StyledMapTypeOptions);
    L1320:  getTile(tileCoord: Point, zoom: number, ownerDocument: Document): Element;
    L1321:  releaseTile(tile: Element): void;

            Duplicate identifier 'BicyclingLayer'.

    L1409:  constructor();
    L1410:  getMap(): Map;         
    L1411:  setMap(map: Map): void;

            Duplicate identifier 'FusionTablesLayer'.

    L1415:  constructor(options: FusionTablesLayerOptions);
    L1416:  getMap(): Map;            
    L1417:  setMap(map: Map): void;

            Duplicate identifier 'KmlLayer'.

    L1481:  constructor(opts?: KmlLayerOptions);
    L1482:  getDefaultViewport(): LatLngBounds;
    L1483:  getMap(): Map;

            Duplicate identifier 'DOCUMENT_NOT_FOUND'.

    L1513:  DOCUMENT_TOO_LARGE,
    L1514:  FETCH_ERROR,      
    L1515:  INVALID_DOCUMENT,

            Duplicate identifier 'DOCUMENT_TOO_LARGE'.

    L1514:  FETCH_ERROR,
    L1515:  INVALID_DOCUMENT, 
    L1516:  INVALID_REQUEST,

            Duplicate identifier 'FETCH_ERROR'.

    L1515:  INVALID_DOCUMENT,
    L1516:  INVALID_REQUEST,
    L1517:  LIMITS_EXCEEDED,

            Duplicate identifier 'INVALID_DOCUMENT'.

    L1516:  INVALID_REQUEST,
    L1517:  LIMITS_EXCEEDED,
    L1518:  OK,

            Duplicate identifier 'INVALID_REQUEST'.

    L1517:  LIMITS_EXCEEDED,
    L1518:  OK,            
    L1519:  TIMED_OUT,

            Duplicate identifier 'LIMITS_EXCEEDED'.

    L1518:  OK,
    L1519:  TIMED_OUT,     
    L1520:  UNKNOWN

            Duplicate identifier 'OK'.

    L1519:      TIMED_OUT,
    L1520:      UNKNOWN

            Duplicate identifier 'TIMED_OUT'.

    L1520:          UNKNOWN

            Duplicate identifier 'UNKNOWN'.

    L1523:      export interface KmlMouseEvent {

            Duplicate identifier 'TrafficLayer'.

    L1545:  constructor();
    L1546:  getMap(): void;      
    L1547:  setMap(map: Map): void;

            Duplicate identifier 'TransitLayer'.

    L1551:  constructor();
    L1552:  getMap(): void;      
    L1553:  setMap(map: Map): void;

            Duplicate identifier 'StreetViewPanorama'.

    L1558:  constructor(container: Element, opts?: StreetViewPanoramaOptions);
    L1559:  controls: MVCArray[]; // Array<MVCArray<Node>>
    L1560:  getLinks(): StreetViewLink[];

            Duplicate identifier 'BEST'.

    L1647:          NEAREST

            Duplicate identifier 'NEAREST'.

    L1650:      export enum StreetViewSource {

            Duplicate identifier 'DEFAULT'.

    L1652:          OUTDOOR

            Duplicate identifier 'OUTDOOR'.

    L1655:      export interface StreetViewLocationRequest {

            Duplicate identifier 'StreetViewService'.

    L1667:  getPanorama(request: StreetViewLocationRequest|StreetViewPanoRequest, cb: (data: StreetViewPanoramaData, status: StreetViewStatus) => void): void;
    L1668:  getPanoramaById(pano: string, callback: (streetViewPanoramaData: StreetViewPanoramaData, streetViewStatus: S
    L1669:  getPanoramaByLocation(latlng: LatLng|LatLngLiteral, radius: number, callback: (streetViewPanoramaData: StreetViewPanoramaData, streetViewStatus: StreetViewStatus) => void )
: void;

            Duplicate identifier 'OK'.

    L1674:      UNKNOWN_ERROR,
    L1675:      ZERO_RESULTS

            Duplicate identifier 'UNKNOWN_ERROR'.

    L1675:          ZERO_RESULTS

            Duplicate identifier 'ZERO_RESULTS'.

    L1678:      export class StreetViewCoverageLayer extends MVCObject  {

            Duplicate identifier 'StreetViewCoverageLayer'.

    L1679:      getMap(): Map;
    L1680:      setMap(map: Map): void;         

            Duplicate identifier 'event'.

    L1691:   * Cross browser event handler registration. This listener is removed by calling
    L1692:   * removeListener(handle) for the handle that is returned by this function.

            Duplicate identifier 'LatLng'.

    L1757:   * Creates a LatLng object representing a geographic point.
    L1758:   * Note the ordering of latitude and longitude.

            Duplicate identifier 'LatLngLiteral'.

    L1779:      export type LatLngBoundsLiteral = { east: number; north: number; south: number; west: number }
    L1781:      export class LatLngBounds {

            Duplicate identifier 'LatLngBoundsLiteral'.

    L1781:      export class LatLngBounds {    
    L1782:          constructor(sw?: LatLng|LatLngLiteral, ne?: LatLng|LatLngLiteral);

            Duplicate identifier 'LatLngBounds'.

    L1782:  constructor(sw?: LatLng|LatLngLiteral, ne?: LatLng|LatLngLiteral);
    L1783:  contains(latLng: LatLng): boolean;
    L1784:  equals(other: LatLngBounds|LatLngBoundsLiteral): boolean;

            Duplicate identifier 'Point'.

    L1798:  /** A point on a two-dimensional plane. */
    L1799:  constructor(x: number, y: number);
    L1800:  /** The X coordinate */

            Duplicate identifier 'Size'.

    L1811:  constructor(width: number, height: number, widthUnit?: string, heightUnit?: string);
    L1812:  height: number;
    L1813:  width: number;

            Duplicate identifier 'MVCObject'.

    L1820:  constructor();
    L1821:  addListener(eventName: string, handler: (...args: any[]) => void): MapsEventListener;
    L1822:  bindTo(key: string, target: MVCObject, targetKey?: string, noNotify?: boolean): void;

            Duplicate identifier 'MVCArray'.

    L1833:  constructor(array?: any[]);
    L1834:  clear(): void;   
    L1835:  forEach(callback: (elem: any, i: number) => void): void;

            Duplicate identifier 'encoding'.

    L1849:      static decodePath(encodedPath: string): LatLng[];
    L1850:      static encodePath(path: any[]): string; // LatLng[]|MVCArray<LatLng>

            Duplicate identifier 'spherical'.

    L1859:   * Returns the area of a closed path.
    L1860:   * The computed area uses the same units as the radius.

            Duplicate identifier 'poly'.

    L1906:      static containsLocation(point: LatLng, polygon: Polygon): boolean;
    L1907:      static isLocationOnEdge(point: LatLng, poly: Polygon|Polyline, tolerance?: number): boolean;

            Duplicate identifier 'AdUnit'.

    L1914:  constructor(container: Element, opts: AdUnitOptions);
    L1915:  getBackgroundColor(): string;
    L1916:  getBorderColor(): string;

            Duplicate identifier 'BANNER'.

    L1952:  BUTTON,
    L1953:  HALF_BANNER,
    L1954:  LARGE_HORIZONTAL_LINK_UNIT,

            Duplicate identifier 'BUTTON'.

    L1953:  HALF_BANNER,
    L1954:  LARGE_HORIZONTAL_LINK_UNIT,
    L1955:  LARGE_RECTANGLE,

            Duplicate identifier 'HALF_BANNER'.

    L1954:  LARGE_HORIZONTAL_LINK_UNIT,
    L1955:  LARGE_RECTANGLE,
    L1956:  LARGE_VERTICAL_LINK_UNIT,

            Duplicate identifier 'LARGE_HORIZONTAL_LINK_UNIT'.

    L1955:  LARGE_RECTANGLE,
    L1956:  LARGE_VERTICAL_LINK_UNIT, 
    L1957:  LEADERBOARD,

            Duplicate identifier 'LARGE_RECTANGLE'.

    L1956:  LARGE_VERTICAL_LINK_UNIT,
    L1957:  LEADERBOARD,   
    L1958:  MEDIUM_RECTANGLE,

            Duplicate identifier 'LARGE_VERTICAL_LINK_UNIT'.

    L1957:  LEADERBOARD,
    L1958:  MEDIUM_RECTANGLE,       
    L1959:  MEDIUM_VERTICAL_LINK_UNIT,

            Duplicate identifier 'LEADERBOARD'.

    L1958:  MEDIUM_RECTANGLE,
    L1959:  MEDIUM_VERTICAL_LINK_UNIT,
    L1960:  SKYSCRAPER,

            Duplicate identifier 'MEDIUM_RECTANGLE'.

    L1959:  MEDIUM_VERTICAL_LINK_UNIT,
    L1960:  SKYSCRAPER,     
    L1961:  SMALL_HORIZONTAL_LINK_UNIT,

            Duplicate identifier 'MEDIUM_VERTICAL_LINK_UNIT'.

    L1960:  SKYSCRAPER,
    L1961:  SMALL_HORIZONTAL_LINK_UNIT,
    L1962:  SMALL_RECTANGLE,

            Duplicate identifier 'SKYSCRAPER'.

    L1961:  SMALL_HORIZONTAL_LINK_UNIT,
    L1962:  SMALL_RECTANGLE,
    L1963:  SMALL_SQUARE,

            Duplicate identifier 'SMALL_HORIZONTAL_LINK_UNIT'.

    L1962:  SMALL_RECTANGLE,
    L1963:  SMALL_SQUARE,             
    L1964:  SMALL_VERTICAL_LINK_UNIT,

            Duplicate identifier 'SMALL_RECTANGLE'.

    L1963:  SMALL_SQUARE,
    L1964:  SMALL_VERTICAL_LINK_UNIT,
    L1965:  SQUARE,

            Duplicate identifier 'SMALL_SQUARE'.

    L1964:  SMALL_VERTICAL_LINK_UNIT,
    L1965:  SQUARE,     
    L1966:  VERTICAL_BANNER,

            Duplicate identifier 'SMALL_VERTICAL_LINK_UNIT'.

    L1965:  SQUARE,
    L1966:  VERTICAL_BANNER,        
    L1967:  WIDE_SKYSCRAPER,

            Duplicate identifier 'SQUARE'.

    L1966:  VERTICAL_BANNER,
    L1967:  WIDE_SKYSCRAPER,
    L1968:  X_LARGE_VERTICAL_LINK_UNIT

            Duplicate identifier 'VERTICAL_BANNER'.

    L1967:      WIDE_SKYSCRAPER,
    L1968:      X_LARGE_VERTICAL_LINK_UNIT

            Duplicate identifier 'WIDE_SKYSCRAPER'.

    L1968:          X_LARGE_VERTICAL_LINK_UNIT

            Duplicate identifier 'X_LARGE_VERTICAL_LINK_UNIT'.

            Duplicate identifier 'Autocomplete'.

    L1975:  constructor(inputField: HTMLInputElement, opts?: AutocompleteOptions);
    L1976:  getBounds(): LatLngBounds;
    L1977:  getPlace(): PlaceResult;

            Duplicate identifier 'AutocompleteService'.

    L2008:  constructor();
    L2009:  getPlacePredictions(request: AutocompletionRequest, callback: (result: AutocompletePrediction[], status: Pla
    L2010:  getQueryPredictions(request: QueryAutocompletionRequest, callback: (result: QueryAutocompletePrediction[], status: PlacesServiceStatus) => void): void;

            Duplicate identifier 'PlacesService'.

    L2103:  constructor(attrContainer: HTMLDivElement|Map);
    L2104:  getDetails(request: PlaceDetailsRequest, callback: (result: PlaceResult, status: PlacesServiceStatus) => voi
    L2105:  nearbySearch(request: PlaceSearchRequest, callback: (results: PlaceResult[], status: PlacesServiceStatus, pagination: PlaceSearchPagination) => void): void;

            Duplicate identifier 'INVALID_REQUEST'.

    L2112:  OK,
    L2113:  OVER_QUERY_LIMIT,
    L2114:  REQUEST_DENIED,

            Duplicate identifier 'OK'.

    L2113:  OVER_QUERY_LIMIT,
    L2114:  REQUEST_DENIED,
    L2115:  UNKNOWN_ERROR,

            Duplicate identifier 'OVER_QUERY_LIMIT'.

    L2114:  REQUEST_DENIED,
    L2115:  UNKNOWN_ERROR,  
    L2116:  ZERO_RESULTS

            Duplicate identifier 'REQUEST_DENIED'.

    L2115:      UNKNOWN_ERROR,
    L2116:      ZERO_RESULTS  

            Duplicate identifier 'UNKNOWN_ERROR'.

    L2116:              ZERO_RESULTS

            Duplicate identifier 'ZERO_RESULTS'.

    L2119:          export interface QueryAutocompletePrediction {

            Duplicate identifier 'DISTANCE'.

    L2146:              PROMINENCE

            Duplicate identifier 'PROMINENCE'.

    L2149:          export class SearchBox extends MVCObject {

            Duplicate identifier 'SearchBox'.

    L2150:  constructor(inputField: HTMLInputElement, opts?: SearchBoxOptions);
    L2151:  getBounds(): LatLngBounds;
    L2152:  getPlaces(): PlaceResult[];

            Duplicate identifier 'DrawingManager'.

    L2173:  constructor(options?: DrawingManagerOptions);
    L2174:  getDrawingMode(): OverlayType;
    L2175:  getMap(): Map;

            Duplicate identifier 'CIRCLE'.

    L2205:  MARKER,
    L2206:  POLYGON,
    L2207:  POLYLINE,

            Duplicate identifier 'MARKER'.

    L2206:  POLYGON,
    L2207:  POLYLINE,
    L2208:  RECTANGLE

            Duplicate identifier 'POLYGON'.

    L2207:      POLYLINE,
    L2208:      RECTANGLE

            Duplicate identifier 'POLYLINE'.

    L2208:          RECTANGLE

            Duplicate identifier 'RECTANGLE'.

            Duplicate identifier 'MapsEngineLayer'.

    L2215:  constructor(options: MapsEngineLayerOptions);
    L2216:  getLayerId(): string;   
    L2217:  getLayerKey(): string;

            Duplicate identifier 'INVALID_LAYER'.

    L2259:      OK,
    L2260:      UNKNOWN_ERROR

            Duplicate identifier 'OK'.

    L2260:              UNKNOWN_ERROR

            Duplicate identifier 'UNKNOWN_ERROR'.

    L2263:          export class HeatmapLayer extends MVCObject {

            Duplicate identifier 'HeatmapLayer'.

    L2264:  constructor(opts?: HeatmapLayerOptions);
    L2265:  getData(): MVCArray; 
    L2266:  getMap(): Map;

            Duplicate identifier 'MouseEvent'.

    L2289:              stop(): void;

            Duplicate identifier 'MapsEventListener'

**Comment by wbhob** [comment]
Please follow the issue template. No one can understand your issue if you don't tell us what is wrong.

**Comment by wbhob** [comment]
Please run `ionic info` and paste the output here

**Comment by wbhob** [comment]
It looks like you are using the AdMob implementation twice, and using --prod also runs the linter, and that is where your error is.

**Comment by abmnukmr** [comment]
m not using admob

**Comment by wbhob** [comment]
Google Maps?

**Comment by abmnukmr** [comment]
ya m using google map

**Comment by abmnukmr** [comment]
E:\ionic app\ionicc1>ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.5
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by wbhob** [comment]
You are importing it twice somewhere.

**Comment by abmnukmr** [comment]
let me check

**Comment by abmnukmr** [comment]
ya   :(

**Comment by abmnukmr** [comment]
but i removed one

**Comment by wbhob** [comment]
It should work now 😄

**Comment by abmnukmr** [comment]
wait

**Comment by abmnukmr** [comment]
it will decrese the boot time??

**Comment by wbhob** [comment]
Probably. Never import the same thing twice.

**Comment by abmnukmr** [comment]
same problem

**Comment by abmnukmr** [comment]
:(

**Comment by wbhob** [comment]
Make sure nothing is being imported twice

**Comment by abmnukmr** [comment]
ohkk

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
