### ISSUE TITLE
No provider for Form

### ISSUE THREAD

**Issue by danielehrhardt** [driftyco/ionic#10684]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Since the Update to Ionic 2.1.0 i got 

> EXCEPTION: No provider for Form!
![image](https://cloud.githubusercontent.com/assets/19570043/23669582/004a0f28-0365-11e7-9335-66bddb221736.png)

only at one Page

**Comment by patrickbussmann** [comment]
I have the same problem with the update but my message is:

    No provider for t!

Yes, I have no provider which is called `t`. But if I try the non minified version it works fine. If I `ionic build ios --release --prod` I get this error message on few pages.

![No provider for t!](https://cloud.githubusercontent.com/assets/15617021/23670418/e6e5f878-0367-11e7-91c6-5bb49db39599.png)

Please check :+1: Thanks in Advance!

**Ionic info:**

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.7.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by rapropos** [comment]
I believe `Form` was removed in Angular 2.0.0-rc.6.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
