### ISSUE TITLE
URGENT Angular 2.4/Ionic 2.1.0 latest nightly hides detail-push arrows

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic#10683]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using `detail-push` or `<a ion-item>` item arrows are hidden with Ionic 2.1.0-nightly and Ng2.4.

**Expected behavior:**

Arrows should be visible when the detail-push attribute exists.

**Steps to reproduce:**

http://plnkr.co/edit/F6MnPb?p=preview

**Related code:**

```
  <ion-list>
 <ion-item detail-push>
  Item with Detail Arrow
</ion-item>
</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.1.0-201703061537
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you seeing this on iOS? In MD mode arrows by default will not show as that goes against the MD design spec.

**Comment by wbhob** [comment]
Hi Justin,
I am seeing this in iOS. I also enabled the arrows in Android via Sass and they are also hidden.

**Comment by Manduro** [comment]
@wbhob Works fine here locally with the latest nightly.

The plunker shows the arrow correctly when viewed on iOS. It doesn't on Android, but it will when using `$item-md-detail-push-show: true;`.

**Comment by wbhob** [comment]
Are you using angular 2.4.8?

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by jgw96** [comment]
Hello @wbhob , unfortunately we are not able to repro this issue, both me and @manucorporat have tested this with the latest nightly and cannot repro. Is their any way you could create a repo that we could reproduce this issue with? Thanks!

**Comment by wbhob** [comment]
You're on nightly version 2.1.0-201703061537? It still looks like this for me:
![screen shot 2017-03-08 at 1 01 52 pm](https://cloud.githubusercontent.com/assets/4442130/23717020/324873c0-0400-11e7-929a-426f8d038389.png)

And the corresponding for the bottom list (About, Support, etc.):
```html
  <ion-list>
    <ion-list-header>App</ion-list-header>
    <a ion-item tappable [navPush]="aboutPage">
      <ion-icon name="information-circle" item-left color="primary"></ion-icon>
      About
    </a>
    <a ion-item tappable (click)="getFeedback()">
      <ion-icon name="help-buoy" item-left color="primary"></ion-icon>
      Support
      <ion-badge color="danger">{{badge}}</ion-badge>
    </a>
    <a ion-item tappable (click)="openSettings()" detail-push>
      <ion-icon name="settings" item-left color="primary"></ion-icon>
      Settings
    </a>
  </ion-list>
```

Also, I'll share a private repo with you @jgw96; look at the `home` page for this issue. (Ignore the part that the top part won't load, it's testing against a local server rn).

**Comment by wbhob** [comment]
It may be related to this: 
![screen shot 2017-03-08 at 5 46 07 pm](https://cloud.githubusercontent.com/assets/4442130/23727731/320100ae-0427-11e7-9d81-9813e74eba97.png)

**Comment by wbhob** [comment]
However, I found that it is properly referencing the background-image on the ion-item, it just isn't visible for some reason.

**Comment by wbhob** [comment]
### Post-Mortem
So as it turns out I have this line:
```html
  <meta http-equiv="Content-Security-Policy" content="default-src gap://ready frame-src file://* *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *">
```
This line prevented calling to outside sources. I acquired it from a tutorial on using the Facebook plugin, and forgot to take it out; thus, when Ionic went looking for the icon, the origin was deemed unsafe, and would not load.
