### ISSUE TITLE
Inconsistent click behaviour in ion-range

### ISSUE THREAD

**Issue by tanzl88** [driftyco/ionic#10686]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When clicked on the bar, knob jumps to click position. However, this click sometimes only work on left side of the knob, sometimes only work on right side of the knob.

These screenshots were captured in ionic website. The same behaviour was observed in ionic serve and real devices.

_Only left hand side work_
![backward ok](https://cloud.githubusercontent.com/assets/4703671/23687223/6ea34204-03e8-11e7-991c-172b0775c132.gif)

_Only right and side work_
![forward ok](https://cloud.githubusercontent.com/assets/4703671/23687243/807d853e-03e8-11e7-9000-96bf3d83bc96.gif)

**Expected behavior:**
Clicking should works on both sides of the knob to be consistent. Not sure whether Ionic's policy is to mimic native's behaviour. From my observation, clicking does not move knob in iOS, but it does in Android.

**Steps to reproduce:**
Can be reproduced in ion-range site. Click always only works on the right side of the knob at first. After some dragging and clicking, it will flip to the other side. Not sure what triggers that.

**Comment by jgw96** [comment]
Hello, unfortunately i cannot reproduce this issue on the latest stable version of chrome. What browser are you seeing this issue on?

**Comment by tanzl88** [comment]
Chrome Version 56.0.2924.87 (64-bit) on OSX
Just tested on Safari Version 9.1.1 (11601.6.17) and found it too.
I think the issue is independent of browser because I can observe this issue in real devices too.

**Comment by tanzl88** [comment]
Found a fix https://github.com/driftyco/ionic/commit/d53824517848d3c9d0752fdb4fc0ef66db5e0ae0 committed 5 days ago. It fixes the issue too.
