### ISSUE TITLE
bug: v1.32 infinite scroll would load more per time?

### ISSUE THREAD

**Issue by liangzhicong** [driftyco/ionic#10687]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>getLogs: function () {
                var self = this;
                LoginService.tips.loading();
                if (this.items.length > 0) {
                    this.pointParams.startIndex += this.pointParams.pageSize;
                }
                this.loadMore = false;
                ApiService.post(gagaApp.apiUrls.member.memberPointLogs, {}, this.pointParams).then(function (result) {
                    LoginService.tips.hide();
                    if (result && result.length) {
                        self.isEmpty = false;
                        var count = result.length;
                        if (count > self.pointParams.pageSize) {
                            result.pop();
                            self.loadMore = true;
                        }
                        Array.prototype.push.apply(self.items, result);
                    } else {
                        self.items = [];
                        self.isEmpty = true;
                    }
                    $scope.$broadcast('scroll.infiniteScrollComplete');
                })
            }
<ion-infinite-scroll ng-if="page.loadMore" on-infinite="page.getLogs()" immediate-check="false" distance="0"></ion-infinite-scroll></span>

<span is-issue-template></span>

**Comment by AmitMY** [comment]
```
Ionic 1.x

The source code for Ionic 1.x has been moved to [driftyco/ionic-v1](https://github.com/driftyco/ionic-v1). Please open any issues and pull requests related to Ionic 1.x on that repository.
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#220
