### ISSUE TITLE
Unable to zoom map on iOS device

### ISSUE THREAD

**Issue by jczaplew** [driftyco/ionic#10695]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
In Safari on iOS, when a user pinch zooms on a map the entire window zooms, and the event is never registered by Mapbox GL JS. In Ionic v1, this was fixed by setting the attribute `data-tap-disabled` on `ion-content`, but that attribute does not exist in Ionic v2. 

**Expected behavior:**
The Ionic and/or browser pinch zoom events should be disabled to allow the map events to register, resulting in the map zooming. This is an identical example without Ionic that works as expected:

_Code_: http://plnkr.co/edit/dMiesMZIAmnnbWTtxwWQ?p=preview
_Fullscreen demo_: http://run.plnkr.co/JQlQjpmxKIkClGV3/

**Steps to reproduce:**
A demo can be found here - http://plnkr.co/edit/76XCx3BLwjMprUKi5Gpt?p=preview

Please note that zooming will work as expected on a desktop computer, and this issue only crops up when running it in Safari on iOS. Open up this link on an iOS device and pinch zoom to experience the issue - http://run.plnkr.co/ilHObVGJUJ9PpQUb/

**Related code:**

```
mapboxgl.accessToken = 'pk.eyJ1IjoiamN6YXBsZXdza2kiLCJhIjoiWnQxSC01USJ9.oleZzfREJUKAK1TMeCD0bg'

this.map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/streets-v9',
  center: [-89.3, 43.03],
  zoom: 9,
  dragRotate: false,
  touchZoomRotate: false,
  minZoom: 1,
  maxZoom: 17,
})
```

**Other information:**
+ [data-tap-disabled in Ionic v2](https://forum.ionicframework.com/t/data-tap-disabled-true-equivalent-for-ionic-2/54804)
+ [disable scroll for ion-content](https://github.com/driftyco/ionic/issues/7644/#issuecomment-280039575)

**Ionic info:**:

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.8.4 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Thanks, we will look into this (:

**Comment by jczaplew** [comment]
Upon further inspection this is not an issue with Ionic. Sorry about that!
