### ISSUE TITLE
Windows showing back button without anything on the stack!

### ISSUE THREAD

**Issue by digaus** [driftyco/ionic#10709]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Native back button shown on window even thought nothing is on the stack

**Expected behavior:**
No back button shown

**Steps to reproduce:**

Install latest nightly, run app on windows

**Other information:**
![desctop screenshot](https://cloud.githubusercontent.com/assets/15358538/23749350/09f56a68-04c8-11e7-96e8-031ffdfb231f.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
