### ISSUE TITLE
please export private class

### ISSUE THREAD

**Issue by Jimmysh** [driftyco/ionic#10702]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

please export private class like UIEventManager, PointerEvents...

**Comment by mhartington** [comment]
There are reasons why we have those APIs marked as private. 
They're not meant to be used by devs outside of working with ionic's internals. 

For now, they will stay private.
