### ISSUE TITLE
White flash will appear when switch to tabs page。

### ISSUE THREAD

**Issue by hfutzhu** [driftyco/ionic#10700]
Ionic framework version:2.0.0 RC4
CLI ：2.1.17

Short description of the problem:
App: Login Page->MainPage(with tabs)->A Page(no tabs)->B Page(with Tabs)
when i switch from A page to B page, or B page go back to A page. White flash will appear。
Anynone Encounter this problem ？

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
