### ISSUE TITLE
Do you guys have a fucking clear documentation of what have you made ?????

### ISSUE THREAD

**Issue by iamCoderGod** [driftyco/ionic#10701]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by MTechDE** [comment]
lol

**Comment by graphefruit** [comment]
Here you go with the documentation: http://ionicframework.com/docs/

**Comment by iamCoderGod** [comment]
#graphefruit  randi ka aulad

**Comment by graphefruit** [comment]
@jgw96  @manucorporat  Please delete this issue, because its getting out of hand, even more I'm getting insulted here.

**Comment by davec21** [comment]
Haha not much of a coder god if the documentation they do have isn't enough for you.

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/blob/master/CODE_OF_CONDUCT.md

> Communication through any of Ionic's channels (GitHub, Slack, Forum, IRC, mailing lists, Twitter, etc.) must be constructive and never resort to personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

@iamCoderGod this impolite and disrespectful behaviour is against our code of conduct. 
Issue closed and user reported.
