### ISSUE TITLE
Use locally installed Cordova when available

### ISSUE THREAD

**Issue by chawax** [driftyco/ionic#10706]
**Ionic version:** 
[x] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

Ionic CLI needs Cordova to be installed globally to work. Not very convenient when you work on many projects with each project working with its own version of Cordova. For now I use nvm to have a node version per project and so both Cordova and Ionic globally installed. But it is heavy to maintain and it can't be the solution when you need to setup continuous integration.

**Expected behavior:**

When you install Ionic locally, use the locally installed Cordova (the one in node_modules) if available.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1972
