### ISSUE TITLE
Setup ionic for local development

### ISSUE THREAD

**Issue by HikwaMehluli** [driftyco/ionic#10717]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X
[npm-debug - log.txt](https://github.com/driftyco/ionic/files/832263/npm-debug.-.log.txt)

 ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by rapropos** [comment]
This looks like a better fit for the support forums than a github issue, where if you had [searched for "enoent rename"](https://forum.ionicframework.com/search?q=enoent%20rename) you would have found a bunch of threads telling you to uninstall ionic and cordova and then reinstall them.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
