### ISSUE TITLE
platform.onResize() has been removed

### ISSUE THREAD

**Issue by larssn** [driftyco/ionic#10715]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

You apparently removed this function, but didn't mention it as a breaking change in the changelog for 2.2.0.

Thats all

**Comment by mhartington** [comment]
Hi! Yes we did remove the the method, but it was refactored as an event emitter

https://github.com/driftyco/ionic/commit/be0b6a88720ad2e6b8316c8dde7fc91da82de67c

I will note that the method was marked as private, meaning it was not meant to be used outside of the internals of ionic. So we don't really make any promises there that we'll mention it in the change log, as you're not supposed to be using it to begin with 😄 

Thanks!

**Comment by larssn** [comment]
Thanks for clarifying. We'll figure out an alternative.
