### ISSUE TITLE
(feature request): Dynamically and responsive grid for amazing dashboards

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10711]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
With the new grid and with the new split pane now we could create beautiful dashboards for desktop apps. And this is amazing.
I don't know if this is in your interested and if you ever would like to create a dynamically dashboard with drag and drop behavior, or if it is your intend that this things should be created from 3rd parts.
But my feature request and discussion point for this request is, if you can implement a dynamically and a responsive grid/dashboard system like the gifs here:

![gridding_2_collisions](https://cloud.githubusercontent.com/assets/3778892/23751191/7e62606a-04d0-11e7-8f21-ed4017fc8eb6.gif)

![gridding_3_resize](https://cloud.githubusercontent.com/assets/3778892/23751221/9538fcd6-04d0-11e7-8bff-202855592372.gif)

![gridpreview](https://cloud.githubusercontent.com/assets/3778892/23751157/5a111742-04d0-11e7-8e97-a4a665cd4822.gif)

So what do you think, is there a possibility that you ever will integrate natively something like that?

**Comment by digaus** [comment]
Really cool idea! That would be an awesome feature 👍

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#126

**Comment by mburger81** [comment]
Hallo @jgw96 first off thx to consider me feature request :)
If I can I would like to make a comment on your handling with feature-requests. The ionic-feature-request is not public and if you move the request there, we don't know if you already have talk about the feature, if you find it interesting and if you would like to implement it and even if you plan to implement it.

So it could be possible we are waiting months for a feature but in real you decided already after one day to not implement the feature and this would be for us a problem. If we know you would not implement it we have to do it by our own and we can start immediately.

I don't know whats happened with your ionic idea platform? But there at least we saw if you start the implementation.

It would be really nice, if we can see the status of the feature requests.
- WAIT TO DISCUSS
- START TO DISCUSS
- ACCEPTED
- DECLINED
- START IMPLEMENTATION
- FINISH IMPLEMENTATION
- RELEASED

perhaps we didn't need any of this status, but some of them :)
