### ISSUE TITLE
CSS Attribute not working -webkit-box-orient: vertical;

### ISSUE THREAD

**Issue by carlosjtacon** [driftyco/ionic#10723]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Line camp not working, ionic removes attribute from web inspector.

**Expected behavior:**

It worked before Ionic 2.1

**Steps to reproduce:**

I have a class with the attribute -webkit-box-orient: vertical; that is related to -webkit-line-clamp, but when I run the app, this attribute disappears so my text is rendering all the lines.

**Related code:**

```
.three_lines {
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}

.three_lines_web_inspector {
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question about an issue with your custom css i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by carlosjtacon** [comment]
It is not a problem with my css, it is that the transpile removes one of my properties, it worked before 2.1!!!

**Comment by albert-gonzalez** [comment]
Hi!

please, review this issue, it happens in my app too.  I think it's because of the new optimizations of the version 1.1.x of ionic-app-scripts.

I have just opened a issue in the app scripts project: https://github.com/driftyco/ionic-app-scripts/issues/821

Thank you!

**Comment by rcd229** [comment]
Same here. I checked to make sure all of my CSS sections w/ line clamps also include the -webkit-box-orient property, and they do, but I can see in the Safari and Chrome web inspectors that that property disappears when I run on ionic serve or on an emulator/device. Can this issue be reopened??

**Comment by yuzhenApril** [comment]
i have the same issue.
i also use ngStyle to write '-webkit-box-orient' into the element,but it just disappear when it was triggered(but the other CSS properties were included normally).

**Comment by vhinic** [comment]
Same issue here. It simply removes "-webkit-box-orient: vertical;"

**Comment by swaraasolutions** [comment]
This issue can be resolved by adding following to the scss

/* autoprefixer: off */
      -webkit-box-orient: vertical;
      /* autoprefixer: on */

This resolved the issue for me

**Comment by tietthinh** [comment]
@swaraasolutions Thank you, It's work for me, but notice that you missing something on your code, I recently change it to this and it work like a charm. Thanks any way
    /* autoprefixer: off */
    -webkit-box-orient: vertical;
    /* autoprefixer: on */

**Comment by xu3u4** [comment]
Many thanks to @swaraasolutions and @tietthinh.
 It works !!
