### ISSUE TITLE
New framework fails - can't update, can't run start

### ISSUE THREAD

**Issue by Shane-Lester** [driftyco/ionic#10729]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Updated framework won't even run basic serve on a simple skeleton.

Have uninstalled and installed ionic
ionic -v 
2.2.1

`PS D:\libraries\Programming\ionic\newImageTest> ionic serve
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'bower'

Do you need to run `npm install`?

PS D:\libraries\Programming\ionic\newImageTest> ionic -v
2.2.1

PS D:\libraries\Programming\ionic\newImageTest>`

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
Doesn't seem to have formed an src folder.
package.json doesn't seem to have created correctly - doesn't have the angular modules or the ionic modules included

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by brandyscarney** [comment]
What commands are you running to start a new project?

**Comment by Shane-Lester** [comment]
ionic start newImageTest --v2

**Comment by Shane-Lester** [comment]
I only ran this as the new CLI has broken my app. I've tried everything including redownloading the working version from bitbucket but I get errors in the build process (just with the fonts being copied)
`[16:13:56]  copy: Error copying "D:\libraries\Programming\ionic\webapp\node_modules\ionicons\dist\fonts" to
            "D:\libraries\Programming\ionic\webapp\www\assets\fonts"
[16:13:56]  copy: Error copying "D:\libraries\Programming\ionic\webapp\node_modules\ionic-angular\fonts" to
            "D:\libraries\Programming\ionic\webapp\www\assets\fonts"
`

I get issues with angularfire2 which I solved by reinstalling angularfire2 and firebase

but then I don't get a server
This all the console shows:#
`livereload.js Failed to load resource: net::ERR_ADDRESS_INVALID
2main.js Failed to load resource: the server responded with a status of 404 (Not Found)`

Which is why I tried with a starter app to see if it was the new version of the framework.

Thanks 

Shane

**Comment by jthoms1** [comment]
Can you try executing `ionic info` from within the project directory?

**Comment by Shane-Lester** [comment]
It's included above but here it is again:
`PS D:\libraries\Programming\ionic\newImageTest> ionic info


Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed`

I also tried the tutorial app which does work (with one non-fatal error in the build step)- a watch error after the build dev finished

**Comment by Shane-Lester** [comment]
I've compared the @ionic folder of the node modules in the new tutorial app (working) and my existing app (replaced package.json, deleted node_modules, npm cache clean, npm install) and it's very different. In the new app @ionic contains app-scripts, this doesn't get put in with npm install. The storage folder, subfolders in the new app contain more files than in the rebuilt old app which is giving me an error
`
Module '"D:/libraries/Programming/ionic/ENTonlyApp/webapp/node_modules/@ionic/storage/es2015/index"' has no exported member 'IonicStorageModule'.
`

Also noticed that we now need a MenuController for the sidemenu component (which I use) which wasn't needed previously
