### ISSUE TITLE
SASS Feature improvisation and API for UI developement

### ISSUE THREAD

**Issue by nirus** [driftyco/ionic#10727]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Enhance the SASS feature to support many helper API already available.

**Expected behavior:**

Easy styling support

**Steps to reproduce:**

**Exposing SASS API for easy designing:**

SASS Rem: https://github.com/pierreburel/sass-rem 
For independent size metric supports for elements like font, width, height, Margin which is very useful for different device sizes

COMPASS Helper mixin API: https://github.com/askucher/compass-sass-mixins
For usage of fallback and vendor prefix based API  which exposes all Compass based Mixins

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi! While we do not use these tools internally (and probably wont), there's nothing really stopping you from adding them to your projects. 

We're quite happy with how our sass setup works and don't really need these extra third-party tools.
Thanks!
