### ISSUE TITLE
load dynamic component and don't renderer inside ion-item-options

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#10732]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
when used dynamic  load component in angular using ComponentFactoryResolver + ViewContainerRef the content not render if be inside of ion-item-options and don't show any error, if put outside in a div for example the component is sees ok

**Expected behavior:**

**Steps to reproduce:**
I use this example in angular https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

-->

**Related code:**

```

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of an issue related to your custom functionality, i will urge that you ask this question on our forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
