### ISSUE TITLE
bug: I cannot able to update ionic 2 .

### ISSUE THREAD

**Issue by thirumurthy** [driftyco/ionic#10735]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>i am using windows 7 32 bit OS. i already installed ionic v1.
now i try to update ionic 2 but ionic 1 also gone now. :( 

for update process i refereed this url https://ionicframework.com/docs/v2/intro/installation/

but in command prompt finally says log in folder please submit..

here i unable to submit attach files so i added the log.

please give me solution:

133947 warn In ionic@2.2.1 replacing bundled version of ionic-app-lib with ionic-app-lib@2.2.0
133948 verbose If you need help, you may report this error at:
133948 verbose     <https://github.com/npm/npm/issues>
133949 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\.staging\abbrev-976d3b8c' -> 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
133949 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
133949 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
133949 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
133949 verbose stack
133949 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\.staging\abbrev-976d3b8c' -> 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
133949 verbose stack     at Error (native)
133950 verbose cwd C:\Users\Kumar
133951 error Windows_NT 6.2.9200
133952 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
133953 error node v6.9.2
133954 error npm  v3.10.9
133955 error path C:\Users\Kumar\AppData\Roaming\npm\node_modules\.staging\abbrev-976d3b8c
133956 error code ENOENT
133957 error errno -4058
133958 error syscall rename
133959 error enoent ENOENT: no such file or directory, rename 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\.staging\abbrev-976d3b8c' -> 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
133960 error enoent ENOENT: no such file or directory, rename 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\.staging\abbrev-976d3b8c' -> 'C:\Users\Kumar\AppData\Roaming\npm\node_modules\cordova\node_modules\npm\node_modules\abbrev'
133960 error enoent This is most likely not a problem with npm itself
133960 error enoent and is related to npm not being able to find a file.
133961 verbose exit [ -4058, true ]</span>

<span is-issue-template></span>

**Comment by TheRealKira** [comment]
`133960 error enoent This is most likely not a problem with npm itself
133960 error enoent and is related to npm not being able to find a file.
`
This is most likely a file and/or directory permissions issue with your npm installation. Have you made sure you have read/write/execute access to `C:\Users\Kumar\AppData\Roaming\npm`? This doesn't seem like an ionic problem.

**Comment by thirumurthy** [comment]
yes i gave all permissions

**Comment by thirumurthy** [comment]
Atleast older version need to back for doing my old task.. so it is ionic problem. ionic need to handle upgrade in safe way.

**Comment by speedfl** [comment]
Yes it is a nom issue !!!! 
I had this issue  :( it took me some time to figure out the issue.

What solved my day : 
npm uninstall -g cordova
npm uninstall -g ionic

npm install -g cordova@6.3.1 (don't take the latest)
npm install -g ionic

It should work

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
