### ISSUE TITLE
Not Save Local Data.

### ISSUE THREAD

**Issue by jackryu** [driftyco/ionic#10739]
Hello Team,

I am new on ionic 2 development. i am try to store app data in local storage but this is not working.

Issue Details
 
**I am set my all path like. Java, Android but not working.**

-------------------------------------------------------------------------------------------
**[CODE]**

export class HomePage {

  coreData=[];

  expTitle:string = "";
  expAmount:number = 0.00;
  expComment:string = "";
  expDate:string = new Date().toISOString();

    jsonStrig = {
    title:this.expTitle ,
    amount:this.expAmount,
    date:this.coreData,
    comment:this.expComment
  };

  constructor(public navCtrl: NavController) {

  }

  save() {
    NativeStorage.setItem('dbtest', "data is my new !!!");
    NativeStorage.setItem('dbHomeExpance', this.coreData);
  }

  saveExpance(event) {
  try{
    event.preventDefault();
    this.coreData.push(this.jsonStrig);
    this.save();
    console.log(this.coreData);

  }catch(e){
    alert(e);    
  }finally{
    alert("Successfully Done!! Job..");
  }
}

}

-------------------------------------------------------------------------------------------
**Error :**

Native: tried calling NativeStorage.setItem, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

Native: tried calling NativeStorage.setItem, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
cordovaWarn @ plugin.js:33
callCordovaPlugin @ plugin.js:112
(anonymous) @ plugin.js:159
(anonymous) @ plugin.js:131
t @ polyfills.js:3
tryNativePromise @ plugin.js:130
getPromise @ plugin.js:152
wrapPromise @ plugin.js:158
(anonymous) @ plugin.js:325
value @ plugin.js:386
HomePage.save @ home.ts:34
HomePage.saveExpance @ home.ts:41
View_HomePage0.handleEvent_57 @ /AppModule/HomePage/component.ngfactory.js:721
(anonymous) @ view.js:664
(anonymous) @ dom_renderer.js:489
t.invokeTask @ polyfills.js:3
onInvokeTask @ ng_zone.js:264
t.invokeTask @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3

**Comment by rapropos** [comment]
This looks like a better fit for [the support forums](https://forum.ionicframework.com/) to me.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
