### ISSUE TITLE
Ionic 2 blank / White screen Android and Windows Platforms

### ISSUE THREAD

**Issue by ruben0909** [driftyco/ionic#10738]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
When run the app I see a blank page

**Expected behavior:**

When run the app I expect see the home page

**Steps to reproduce:**
I can't reproduce in a plunkr because with `ionic serve` works, but with `ionic run android` for example it doesn´t.

**Related code:**

**Other information:**

When I inspect with Chrome inspector the Android App I see some errors because the app couldn't find the next files.
"polyfills.js"  "main.js" "cordova_plugins.js"  
`Failed to load resource: net::ERR_FILE_NOT_FOUND`
![error](https://cloud.githubusercontent.com/assets/1110434/23825118/0d84f00a-0684-11e7-9877-2952a0498bea.png)
The same behavior in F12 tools of Windows App.

I tried unzip the generated apk and the files are in the correct place /assets/www/build/polyfills.js , /assets/www/build/main.js and /assets/www/build/cordova_plugins.js.
I checked that the files were generated in the project in /www/build too.

It's like everything is ok the routes and the files exist but the app can`t access to them

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.6.0
Xcode version: Not installed
```
I'm sorry for my english

**Comment by masimplo** [comment]
Can you please post your full index.html?
Also did you notice any errors/warning during the build process after running ionic run android?

**Comment by sam-lex** [comment]
Having this problem as well, this is my index page:
https://gist.github.com/sam-lex/01e0395fe84e08864ebb205d614e74a8

ionic serve/ and ionic run ios (simulator) works fine.

no errors/warning during build process.
I've followed these steps to add crosswalk since my android phone is v4.3:
https://forum.ionicframework.com/t/minimum-android-version-supported-by-ionicv2/54164/17

I first tested with a new starting project, it worked, then I tried on my current project, and it didn't work, no idea why.

This is my ionic info if it helps:
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by sam-lex** [comment]
ok, so I created a new project and started adding files from my old project until it stopped working, and in my case, it was this:
`<base href="/">`
after removing it from index.html, is working again.
Routing seems to be working fine on the web browser without it.
Maybe is not needed anymore?
can't confirm with ios/android now, as I currently have another problem to deal with (firebase related -- getting "Network Error"), so I as soon as I fix that, then I can test routing in ios and android.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
