### ISSUE TITLE
Ionic2 InappBrowser close button for ios

### ISSUE THREAD

**Issue by omgalbert** [driftyco/ionic#10730]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi,

I have a problem with inappbrowser plugin for ios. I open google maps app with a location and I'm trying to show the toolbar with a button to can close the new windows and come back to the application, but it doesn't work, it opens the google maps app but without any toolbar/button. I tried everything. currently I'm opening the new window using:

let browser = new InAppBrowser(marker.map.mapUrl, '_system', 'location=yes,toolbar=yes,closebuttoncaption=done');

**Expected behavior:**
Open a new window with the toolbar and the close button.

**Related code:**

let browser = new InAppBrowser(marker.map.mapUrl, '_system', 'location=yes,toolbar=yes,closebuttoncaption=done');
insert any relevant code here

**Comment by mhartington** [comment]
Hi! This isn't an issue regarding the framework.
Rather it's an issue with a cordova plugin or an ionic native wrapper. 
Please open an issue on the ionic-native repo instead.
Thanks!
