### ISSUE TITLE
ion-reorder in ion-list drags whole screen rather than item

### ISSUE THREAD

**Issue by LucasMcL** [driftyco/ionic#10747]
**Ionic version:**  (check one with "x")
[X] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The reordering functionality built directly into <ion-list> via <ion-reorder-button> is not working properly on my android phone.  When I press and hold the reorder button, then move up or down, it scrolls the whole screen rather than the individual item.  Thus, you can't actually reorder the item.

**Expected behavior:**
I expect the screen to not move unless the item I'm scrolling gets near the top or bottom, at which point the screen should scroll in that direction.

**Steps to reproduce:**
I've included a codepen with code similar to my project.  It seems to work in code pen, but when I pull it down and run it on my phone, it recreates the issue.  I've also included a gif that shows the issue.  My phone is a Moto X Pure Edition running android operating system 6.0.

**Related code:**
https://media.giphy.com/media/xUPGcCT4rHhzgVKzJK/giphy.gif
http://codepen.io/LucasMcL/pen/ryemMJ

**Other information:**

Similar post in forums: https://forum.ionicframework.com/t/ionic-reorder-poor-responsiveness-on-android-phone/81886
My list with delete and reorder buttons is very similar to the official ionic example on codepen: https://codepen.io/ionic/pen/JsHjf.

Things I've tried:
-Reducing the size of the objects in the array that comprises the <ion-list>
-Showing just the reorder button and not delete at the same time
-Using collection-repeat

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#224
