### ISSUE TITLE
Plugins only get called when app is minimized

### ISSUE THREAD

**Issue by svarughese91** [driftyco/ionic#10748]
**Ionic version:**  (check one with "x")
[ x] 1.7.16
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I try to call plugins (Facebook plugin or camera plugin) when it tries to execute the plugin command it just wait to execute the command but never executes unless the app is minimized.  For example, the Facebook plugin when doing facebookConnectPlugin.getLoginStatus() it just waits as it executes the command but never executes unless you minimize the app then it will execute and get the information from the call.

**Expected behavior:**
Should just executive and get the info while the app is running without minimizing the app

```
insert the output from ionic info here
```
No output - no errors everything works fine it just needs to be minimized for some reason

**Comment by rapropos** [comment]
Migrate to [ionic-v1](https://github.com/driftyco/ionic-v1/issues)?

**Comment by svarughese91** [comment]
What do you mean?  I am currently on ionic v1 (1.7.16)

**Comment by rapropos** [comment]
> What do you mean? I am currently on ionic v1 (1.7.16)

You filed an issue against the Ionic v2 repo.

**Comment by svarughese91** [comment]
sorry didn't realize that!  Thank you!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#223
