### ISSUE TITLE
 Property 'filter' does not exist on type 'Observable<Geoposition>' error after upgrading to ionic 2.2.0

### ISSUE THREAD

**Issue by RezaRahmati** [driftyco/ionic#10744]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Hi

I have had a code using `Geolocation` as below

```
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/map';

this.watch = Geolocation.watchPosition(this.options)
				.filter(p => p.code === undefined)
				.map(position => { return something;});
```

It was working fine, now I upgrade my project from  "ionic-angular": "2.0.1", to  "ionic-angular": "2.2.0", and angular 2.4.8, 
Now I get below error, 
` Property 'filter' does not exist on type 'Observable<Geoposition>'.`
 
even if I comment filter row, it will show same error on map,

I am using filter and map in other services, and they are OK

**Comment by rapropos** [comment]
The error message sounds strange, but you need to change `code` to `coords`.

**Comment by DavidStrausz** [comment]
have you tried using the latest version of ionic-native? I had a similiar problem with the cordova network-information plugin and upgrading to the newest version fixed it for me.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by ederjavs** [comment]
Hello Reza
I just had the same problem and this is working without any problem



`
import { Component } from '@angular/core';
import { MenuController, NavController, NavParams, AlertController, Loading, LoadingController } from 'ionic-angular';
import 'rxjs/add/operator/filter'

import { Geolocation } from '@ionic-native/geolocation';





@Component({
  selector: 'page-checkin',
  templateUrl: 'checkin.component.html'
})
export class ChekinPage {

  loading: Loading;

  center: any = '0,0';


  constructor(private geolocation: Geolocation, private loadingCtrl: LoadingController,  public alertCtrl: AlertController,  public navCtrl: NavController, public navParams: NavParams) {

    this.loading = this.loadingCtrl.create({
      content: "Ubicando, por favor espere..."
    });
    this.loading.present();

    const subscription = this.geolocation.watchPosition()
      .filter((p) => p.coords !== undefined) //Filter Out Errors
      .subscribe(position => {
        this.center = `${position.coords.latitude},${position.coords.longitude}`;
        this.loading.dismiss();
        console.log(position);
      });



  }








}
`

**Comment by remcovdsteen** [comment]
Change 
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Subscription } from 'rxjs/Subscription';

to
import { BehaviorSubject, Observable, Subscription } from 'rxjs';

This fix worked for me.
