### ISSUE TITLE
My app takes 65 second to boot !!

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#10742]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
My app takes 65 seconds to boot (i.e it shows the splash screen for 65 seconds then shows the main screen). 

**Expected behavior:**
Should take less than 5 seconds.

**Other information:**

Tested on iPhone 6 and iPhone 6 plus, on both devices it takes more than 60 seconds to boot !

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by Sh1d0w** [comment]
Unless you show your code, so it can be reproduced there is no issue. I am running quite big app on ionic 2.2.0 and the boot time is less than 3 sec.

Try optimizing your code, trace where the bottleneck is and also package your build with --release and --prod flags.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
