### ISSUE TITLE
Wrong tabs display, Windows 10, IE11

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#10749]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Your system information:

 Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Comment by peterennis** [comment]
![capture029](https://cloud.githubusercontent.com/assets/140737/23838887/2c93d0aa-0757-11e7-9631-c8cf8ca018c3.png)

**Comment by graphefruit** [comment]
When I remember​ correctly IE11 is not supported, just Edge

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not officially support IE11. Because of this I am going to close this issue for now.
