### ISSUE TITLE
Push notifications Page redirect

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10746]
Hi all,

  I used FCM plugin for push notifications in ionic 2
  Below my code 

  declare var FCMPlugin;
  //Push Notifications
      
      if(typeof(FCMPlugin) !== "undefined")
      {
        FCMPlugin.getToken(function(t){
          console.log("Use this token for sending device specific messages\nToken: " + t);
        }, function(e){
          console.log("Uh-Oh!\n"+e);
        });
         FCMPlugin.onNotification(function(d){
          if(d.wasTapped){  
            // Background receival (Even if app is closed),
            //   bring up the message in UI
            console.log(d);
           this.nav.setRoot(page);
          } else {
            // Foreground receival, update UI or what have you...
            console.log("Push Notification", d);
            console.log("you have new notifications");
          }
        }, function(msg){
          // No problemo, registered callback
        }, function(err){
          console.log("Arf, no good mate... " + err);
        });
      }

It's work perfectly.My app received notifications.But when i click notifications does not redirect to page.
Kindly Advice me,
Thanks & Regards.

**Comment by AmitMY** [comment]
https://ionicframework.com/docs/v2/native/push/

**Comment by anivaisu** [comment]
Thanks for ur reply.any other way to page redirection in when I click notifications.this.nav.setRoot(page); cannot wrk in my app.and also I tried this.nav.push(page) it,s wrk perfectly an page navigation.but I cannot wrk an push notifications click

**Comment by AmitMY** [comment]
This might be related to your payload, see: https://github.com/phonegap/phonegap-plugin-push/issues/1609
Or, that "wasTapped" isn't working. My code says:
`if (data.additionalData.foreground)` instead of that `if(data.wasTapped)`

And anyway, this issue is a support request, and my best guess it would be closed soon, so you should try the forum. 

Good luck

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
