### ISSUE TITLE
iOS back button - get name from navigation stack

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10745]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After doing `nav.push`, a new page opens, with a button saying "back"
![image](https://cloud.githubusercontent.com/assets/5757359/23830217/482df05a-070e-11e7-8cce-76674587fa33.png)
![image](https://cloud.githubusercontent.com/assets/5757359/23830218/4b92863e-070e-11e7-9fec-fcff9706620b.png)
Also, on swipe-back, the effect is overlapping components, and does not feel like a native transition.

**Expected behavior:**
After doing `nav.push`, a new page should open, with a button saying the title of previous page.
![image](https://cloud.githubusercontent.com/assets/5757359/23830219/501d7060-070e-11e7-8775-0c664b754069.png)

**Source:**
![image](https://cloud.githubusercontent.com/assets/5757359/23830277/b5ea2036-070f-11e7-9762-f967a4916d32.png)

![image](https://cloud.githubusercontent.com/assets/5757359/23830246/f9074836-070e-11e7-9cc9-da4186062853.png)

Native transition:
![image](https://cloud.githubusercontent.com/assets/5757359/23830275/a879b326-070f-11e7-8f4a-d8f9b5436561.png)

**Steps to reproduce:**
`nav.push(AnyComponent)`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by javico2609** [comment]
hi, this is a solution there i gave for the same problem, it's not the best but it's work for me. I hope this can help you.

in app.component.ts
```

import { TranslateLoader, TranslateService, TranslateStaticLoader } from 'ng2-translate/src/translate.service';

ngAfterViewInit() {
    this.nav.viewWillEnter.subscribe((view) => {
      let parentView = this.nav.getPrevious(view);

      if (parentView) {
        this.translate.translate(parentView.name).subscribe(
          moduleName => { this.nav.getActive().getNavbar().setBackButtonText(moduleName); }
        );
      }
    });
  }
```

**Comment by AmitMY** [comment]
@javico2609 Although it works pretty well, there are a few problems:
- When going 2 pages up (Settings -> General -> Keyboard), when starting to swipe-back, the back instantly changes from "General" to "Settings". If you don't finish the swipe back (so you are on the same page - "Keyboard") - on "Keyboard" it says "Settings" on back, but actually goes back to "General". (Understandable from the code, undesired)
- When swiping back, the back and the title does not animate together, but instead it shows 2 times "Settings"
- Should of course add a platform check (only on iOS) - no big problem, just thought it should be noted.

And another note, is that the `translate` method is now called `get`.

I hope the devs will find this feature useful and integrate it into ionic (after they see how simple it can be), so we will have full support of it.

Thanks for the snippet!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#127
