### ISSUE TITLE
Ionic 2 Ng For Display very delayed

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10759]
I have array value . its display UI using ngFor.Its display very delay.How to fix this issue.

Below my Html code

<ion-card class="card" *ngFor="let Notifications of Notifications">
      <ion-item (click)="navigate(Notifications.value.TYPE,Notifications.value.FROM,Notifications.value.$key,Notifications.value.TO,Notifications.value.MSG,Notifications.value.STATUS,Notifications.time)">
        <ion-avatar item-left>
            <img  *ngIf="!Notifications.userval.FILE" src="https://firebasestorage.googleapis.com/v0/b/apartments-ea9e5.appspot.com/o/default.png?alt=media&token=a64af538-17a7-46e1-9e38-383c1df060cf">
          <img *ngIf="Notifications.userval.FILE" [src]="Notifications.userval.FILE">
        </ion-avatar>
        <p>{{Notifications.value.MSG}}</p>
        <p>{{Notifications.time}}</p>
        <p style="text-align:right;color:#334bfa;">{{Notifications.value.TYPE}}</p>
      </ion-item>
   </ion-card> 

But consoled the Notifications value.How to fix this issue.also refer forum.I have no idea.
Kindly advice me,
Thanks & Regards.

**Comment by AmitMY** [comment]
try using `ion-img` for virtual loading inside a `virtualScroll` (Notice: virtualScroll is extremely buggy https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/)

and this doesn't seem like a bug, so the correct place for it is the ionic forums

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
