### ISSUE TITLE
Long Sidemenu closes itself when dragging

### ISSUE THREAD

**Issue by jrbistuer** [driftyco/ionic#10757]
**Ionic version:**  (check one with "x")
[X ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Problem detected in Android. In iOS works as expected.
In a fresh install, when the sidemenu is longer than the height of the device, the sidemenu closes itself when dragging. 
It won't happen if the view is itself longer too, and after multiple attempts of dragging. Neither happens if the drag is done from the title bar.

**Expected behavior:**
One would expect that the dragging would behave exactly as the open/close button menu does.

**Steps to reproduce:**
1) ionic start menu-test sidemenu
2) platform add android
3) open menu.html
4) add 15 new items to the menu
5) ionic run android
6) try drag open menu not from title bar

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS:
Node Version: v7.7.2

**Comment by sergiwf** [comment]
+1

**Comment by borferpa** [comment]
The same happens to me.
I have this versions of Ionic:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.7
Xcode version: Not installed

**Comment by hydrogennz** [comment]
Same happens to me. I'm not using the ionic CLI.

I am using `bower install driftyco/ionic-bower#v1.3.2 to install Ionic v1.3.2 on my project.

**Other info:**
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X Yosemite
Node Version: v7.4.0

Occasionally after swiping a few times and navigating between views the drag to open side menu works normally again but it is very intermittent.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#259
