### ISSUE TITLE
<ion-select> doesn't set input-has-value class

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#10751]
**Ionic version:**
[x] **2.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When an `<ion-select>` has a selected value, it doesn't set the `input-has-value` class on the surrounding `<ion-item>`. Other inputs such as `<ion-input>` and `<ion-datetime>` set that class when they have a value.

**Expected behavior:**
 `<ion-select>`  should set the `input-has-value` class on the surrounding `<ion-item>` when it has a selected value.

**Steps to reproduce:**
See this plunker:
http://plnkr.co/edit/YM9m1E8F1AonrQhfYx44?p=preview

You'll notice that the `.input-has-value { color: #FF0000;}` style does not apply to the `<ion-select>` even though it has a value.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
