### ISSUE TITLE
Can't build for Android after upgrade to 2.2.0

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#10754]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
ionic build android
outputs:

> ionic run android --device --prod
> 
> > expressoapp@ ionic:build /home/christian/dev/projects/expresso-app-front
> > ionic-app-scripts build "--device" "--prod"
> 
> [07:50:57]  ionic-app-scripts 1.1.4 
> [07:50:57]  build prod started ... 
> [07:50:57]  clean started ... 
> [07:50:57]  clean finished in 1 ms 
> [07:50:57]  copy started ... 
> [07:50:57]  ngc started ... 
> [07:51:00]  build prod failed: Error encountered resolving symbol values statically. Calling function 
>             'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a 
>             reference to an exported function, resolving symbol AnimationDriver.NOOP in 
>             /home/christian/dev/projects/expresso-app-front/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts,
>             resolving symbol BrowserTestingModule in 
>             /home/christian/dev/projects/expresso-app-front/node_modules/@angular/platform-browser/testing/browser.d.ts, 
>             resolving symbol BrowserTestingModule in 
>             /home/christian/dev/projects/expresso-app-front/node_modules/@angular/platform-browser/testing/browser.d.ts 

My package.json has

> {
>   "dependencies": {
>     "@angular/common": "2.4.8",
>     "@angular/compiler": "2.4.8",
>     "@angular/compiler-cli": "2.4.8",
>     "@angular/core": "2.4.8",
>     "@angular/forms": "2.4.8",
>     "@angular/http": "2.4.8",
>     "@angular/platform-browser": "2.4.8",
>     "@angular/platform-browser-dynamic": "2.4.8",
>     "@angular/platform-server": "2.4.8",
>     "ionic-angular": "2.2.0",
>     "ionic-native": "2.4.1",
>     "ionicons": "3.0.0",
>     "ng2-translate": "5.0.0",
>     "rxjs": "5.0.1",
>     "sw-toolbox": "3.4.0",
>     "zone.js": "0.7.2"
>   },
>   "devDependencies": {
>     "@ionic/app-scripts": "1.1.4",
>     "@types/jasmine": "2.5.38",
>     "@types/node": "6.0.42",
>     "angular-cli": "1.0.0-beta.26",
>     "chai": "^3.5.0",
>     "chai-as-promised": "^6.0.0",
>     "codelyzer": "^2.0.0",
>     "compodoc": "0.0.37",
>     "core-js": "^2.4.1",
>     "jasmine-core": "2.5.2",
>     "jasmine-spec-reporter": "3.2.0",
>     "karma": "1.4.0",
>     "karma-chrome-launcher": "2.0.0",
>     "karma-cli": "1.0.1",
>     "karma-jasmine": "1.1.0",
>     "karma-mocha-reporter": "2.2.2",
>     "karma-remap-istanbul": "0.4.0",
>     "mocha": "^3.0.2",
>     "ts-node": "2.0.0",
>     "tslint": "4.4.1",
>     "tslint-eslint-rules": "3.4.0",
>     "typescript": "2.0.9",
>     "wdio-mocha-framework": "^0.5.4",
>     "wdio-phantomjs-service": "^0.2.2",
>     "wdio-spec-reporter": "0.0.5",
>     "webdriverio": "^4.2.16",
>     "yargs": "^6.0.0"
>   },
>   "cordovaPlugins": [
>     "cordova-plugin-device",
>     "cordova-plugin-console",
>     "cordova-plugin-whitelist",
>     "cordova-plugin-splashscreen",
>     "cordova-plugin-statusbar",
>     "ionic-plugin-keyboard",
>     "cordova-open",
>     "cordova-plugin-google-analytics",
>     "cordova-plugin-camera",
>     "cordova-plugin-crop",
>     "cordova-plugin-file",
>     "cordova-plugin-inappbrowser",
>     "cordova-plugin-app-version",
>     "cordova-plugin-datepicker",
>     "com-sarriaroman-photoviewer",
>     "onesignal-cordova-plugin"
>   ],
>   "cordovaPlatforms": []
> }

My ionic info
Your system information:

> Cordova CLI: 6.3.1 
> Ionic Framework Version: 2.2.0
> Ionic CLI Version: 2.2.0
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.1.4
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 4.4
> Node Version: v7.6.0
> Xcode version: Not installed
>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1981

**Comment by chrisbenseler** [comment]
The problem is the flag --prod
Without it the build/run is ok(but then the app takes too long to load).
