### ISSUE TITLE
Split pane not working

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#10750]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**
Should work as documented or the docs should be corrected

**Steps to reproduce:**
Follow instructions on docs to test

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Comment by peterennis** [comment]
![capture030](https://cloud.githubusercontent.com/assets/140737/23838942/abc4a62e-0757-11e7-9ca1-8831f659e882.png)

**Comment by peterennis** [comment]
![capture031](https://cloud.githubusercontent.com/assets/140737/23838952/bbce8c60-0757-11e7-96ee-56db866cecd0.png)

**Comment by digaus** [comment]
You need to add `main` to the `ion-nav` tag -> `<ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>`

**Comment by digaus** [comment]
Dont know if it is in Master Branch yet but I use the latest nighlty and it works -> `npm install --save ionic-angular@nightly`

**Comment by digaus** [comment]
Found your issue... change `<ion-nav [root]="rootPage" main #content>swipeBackEnabled="false"</ion-nav>` to `<ion-nav [root]="rootPage" main #content swipeBackEnabled="false"></ion-nav>`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by peterennis** [comment]
@digaus , that was it, Thanks!
