### ISSUE TITLE
watch failed: watcher error + empty/white page

### ISSUE THREAD

**Issue by mo-mueller** [driftyco/ionic#10755]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I run "ionic serve" on my existing project and even on a new project, I'm getting the following error:

> watch failed: watcher error: 
> /.../src/assets/``**/*``,/.../src/index.html,/.../src/manifest.json,/.../src/service-worker.js,/.../node_modules/ionicons/dist/fonts/``**/*``,/.../node_modules/ionic-angular/fonts/``**/*``,/.../node_modules/ionic-angular/polyfills/polyfills.js,/.../node_modules/sw-toolbox/sw-toolbox.js:
> Error: watch /.../node_modules/ionicons/dist/fonts ENOSPC

On top of that on my existing project I get only an empty page when I run "ionic serve".

**Expected behavior:**
"ionic serve" should not return an error and it should not give me an empty page.

**Steps to reproduce:**

**Related code:**

package.json:
```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/cloud-angular": "^0.11.0",
    "@ionic/storage": "2.0.0",
    "@ngx-translate/core": "^6.0.0",
    "@ngx-translate/http-loader": "0.0.3",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "kioskapp: An Ionic project"
}

```

**Other information:**
I have installed the latest ionic version with "npm install -g cordova ionic" and on my existing project I have updated the package.json, deleted the node_modules folder and ran "npm install" again, but still the same issue. Bevor I did that my app still works, even with the watcher error. But since I have deleted the node_modules and ran "npm install" again I'm getting only a blank page. My operating system is Arch Linux.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#811
