### ISSUE TITLE
Menus (in ion-split-pane) in separate tabs not displaying

### ISSUE THREAD

**Issue by oddcb** [driftyco/ionic#10767]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

After creating a project with tabs and adding menus to tabs that contain split panes, only the first tab with a split-pane containing a menu will display its menu. The other tab has the menu hidden. In the dom the menu is present but has display:none.

Injecting the MenuController and doing a menuCtrl.enable(true, "menuXYZ") in the tabs ionViewDidEnter ensures the menus are displayed on navigation. This has to be present in both tabs, as enabling one disables the other.

**Expected behavior:**

I'd expect to add a menu to a tab without having to manage what is enabled or not.

**Steps to reproduce:**

See https://github.com/oddcb/ionic-split-pane-example

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment]
Menus does not know anything about your layout, there are layout agnostic.
Also I recommend you to have just one split-pane in the root and the menus in the root too.

Then you could use `<ion-tabs (ionChange)="tabChanged()">` in order to enable/disable the menu based in the selected menu.
