### ISSUE TITLE
bug: ion-input strange behavior with bluetooth Keyboard

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#10766]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I received some reports describing a strange behavior when your iPad is connected to a bluetooth keyboard and you click on an ion-input. It jumps several times out and it´s not possible to fill a form.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Thanks for using Ionic, we will look into this.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to mark this as a feature request to support bluetooth keyboards and move this to our feature tracking repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#148

**Comment by samever7** [comment]
Hello, the link is missing now and how about this feature?  Any progress on this?

**Comment by lincolnthree** [comment]
Duplicate of https://github.com/ionic-team/ionic/issues/12246 ?
