### ISSUE TITLE
CSS not transpiled

### ISSUE THREAD

**Issue by sooonism** [driftyco/ionic#10768]
**Ionic version:**  (check one with "x")
[X] **2.2.11**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
Every time I run `ionic serve`, the interface do not display correctly:
<img width="320" alt="screen shot 2017-03-14 at 4 54 52 pm copy" src="https://cloud.githubusercontent.com/assets/2647094/23893025/d8ed05d4-08d7-11e7-8042-e4b3cc499490.png">
-Title align to left.
- button padding not correct.

but If I refresh the page, it will appear correctly. I suspect the `CSS` is not correctly transpiled.

**Expected behavior:**
The correct layout is like this:
<img width="320" alt="screen shot 2017-03-14 at 4 55 05 pm" src="https://cloud.githubusercontent.com/assets/2647094/23893036/e9c3d432-08d7-11e7-9eb2-460603f7ab11.png">
- title in the center
- button padding correctly.

**Steps to reproduce:**
run `ionic serve` for the first time, it will display wrongly. Then try press `r` in CLI a few times, it will turn out correctly.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002 
```

**Comment by AmitMY** [comment]
I suspect you are first viewing android, then, after every refresh you see iOS. (because title on left is android, title centered is iOS)
Please try to `Ionic serve --lab` to confirm or refute my suspicion.

**Comment by brandyscarney** [comment]
@sooonism Yeah, as AmitMY stated, the first screenshot is Material Design and the second is iOS. By default the browser will use Material Design. So when you first launch the app if you turn on device mode in the browser it will still show the Material Design UI until you refresh, at which point it will use the device's mode. 

I'm going to close this since I suspect that is what's happening, but please let me know if this is not the case. Thanks!
