### ISSUE TITLE
Documentation broken for Storage

### ISSUE THREAD

**Issue by doomtoo** [driftyco/ionic#10762]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Storage Document(https://ionicframework.com/docs/v2/storage/) is outdated and doesn't work with the current version of ionic.
The updated documentation that works is at: 
https://github.com/driftyco/ionic-storage

Mainly:
import { IonicStorageModule } from '@ionic/storage';
should be:
import { Storage } from '@ionic/storage';

and
IonicStorageModule.forRoot()
should be:
providers: [ Storage ] // Add Storage as a provider

**Expected behavior:**
It should be able to compile, but names have been changed.

**Steps to reproduce:**
Follow the official documentation: https://ionicframework.com/docs/v2/storage/ and try to compile.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
....app.module.ts(11,10): error TS2305: Module '"C:/working_dir/GroceryTrack
er/2017_02_07/grocery_tracker/node_modules/@ionic/storage/es2015/index"' has no
exported member 'IonicStorageModule'.
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#1016
