### ISSUE TITLE
iOS avatar in item not configurable

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic#10763]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

This commit introduced hardcoded value for the border radius of the img

https://github.com/driftyco/ionic/commit/e84f2e2fbbff177a56a0cf215ed55c4e1aeec588#diff-b71116393e7fd80818fc01a903f68082R173

Which makes circle images with content out of the circle to appear cut.

**Expected behavior:**

Solution: make the border radius property configurable via sass variable. So in this case I can set the value to 0px without having to override it with !important in my css files ...

**Steps to reproduce:**
http://plnkr.co/edit/NZpDBBeduQT2K0IRtJv8?p=preview

**Related code:**

```
    <ion-item>
      <ion-avatar item-left>
        <img src="./img.svg">
      </ion-avatar>
      <h2>I am cut</h2>
    </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

    Cordova CLI: 6.4.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v7.7.1
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

cc @brandyscarney

**Comment by brandyscarney** [comment]
Thanks for the issue! I released a nightly version that includes this `ionic-angular@3.0.1-201704062208`. It is based off of the `3.x` version here: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#300-2017-04-05

To install and test it:

```
npm install --save --save-exact ionic-angular@3.0.1-201704062208
```
