### ISSUE TITLE
Filereader onloaded does not firing

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10773]
Hi all,

   I am beginner to ionic2.

  I have Blob Object (Image).
  
  I need base64string.Because I convert Blob to dataURL.
  Here's my function

  gotFile(data) {
  var file = data;

  fileEntry.file(function(file) {
    var reader = new FileReader();

    reader.onloadend = function(e) {
      console.log('onloadend()'); 
    };

    reader.readAsDataURL(file);

    console.log(reader);
  }); 
}
 
data is a blob object.I can see in the log the reader with all the wanted content of my file under result, but I'm not able to get it and use it. The readyState is 2, but all inside reader.onloadend isn't called. With Ionic 1 this code works without any problems.

How do I get result from filereader.Already I tried and console the value => console.log(reader.result);

**But the reader.result value is undefined.**

My ionic version 2.2.1

Cordova version 6.5.0
 
How to Fix this issue. or any other way to convert blob to data URL.

I tried this fix this issue more days.But I cannot do it.

Kindly Pls advice me,

Thanks & Regards.

**Comment by mhartington** [comment]
Hey there 😄 !

 So this is more of a question for the forum or slack, and not an actual issue. 

Please ask there
https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
