### ISSUE TITLE
Ionic 2 How to get input element value

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10786]
Hi ,

  I cannot get input element value.

  Below my code

  <p style="font-size:9px;" id="myDiv">{{chat.date | amDateFormat:'LL'}}</p>

   console.log(document.getElementById('myDiv'));

   It's consoled the value null.

   kindly advice me,

  Thanks.

**Comment by BradyLiles** [comment]
use Angular2's [(ngModel)] to properly get the value.
It's a very rare case you'll have to use Element Selectors.

I don't believe this is a bug in Ionic by any means.
Please review [Angular2 Getting Started](https://angular.io/docs/ts/latest/quickstart.html)

However, if it is. It is preferred to have a plnkr where the team can review the code and determine if it's a framework issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
