### ISSUE TITLE
Cannot build ionic project

### ISSUE THREAD

**Issue by melhartmann** [driftyco/ionic#10785]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I am trying to ionic build android and i get the message: 
12:03:44]  ionic-app-scripts 1.1.4 
[12:03:44]  build dev started ... 
[12:03:44]  clean started ... 
[12:03:44]  clean finished in 3 ms 
[12:03:44]  copy started ... 
[12:03:44]  transpile started ... 
[12:03:48]  typescript: node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts, line: 2 
            Module ''*'' has no exported member 'Options'. 

       L1:  import * as cleanCss from 'clean-css';
       L2:  export declare function getCleanCssInstance(options: cleanCss.Options): cleanCss;
       L3:  export interface CleanCssConfig {

[12:03:48]  typescript: node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts, line: 2 
            Cannot find name 'cleanCss'. 

       L1:  import * as cleanCss from 'clean-css';
       L2:  export declare function getCleanCssInstance(options: cleanCss.Options): cleanCss;
       L3:  export interface CleanCssConfig {

[12:03:48]  typescript: node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts, line: 6 
            Module ''*'' has no exported member 'Options'. 

       L5:      destFileName: string;
[12:03:48]  typescript: node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts, line: 1 
       L6:      options?: cleanCss.Options;

            Cannot find type definition file for 'node'. 

       L1:  import { Stats } from 'fs';   
[12:03:48]  typescript: node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts, line: 3 
       L2:  export declare class VirtualStats implements Stats {

            Cannot find name 'Stats'. 

       L2:  export declare class VirtualStats implements Stats {
       L3:      protected _path: string;     
       L4:      protected _ctime: Date;

[12:03:48]  transpile failed 
[12:03:48]  ionic-app-script task: "build" 
[12:03:48]  Error: Error 

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world

I already reinstalled ionic, node_modules, platforms and plugins

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by BradyLiles** [comment]
Can you please show the results of:
`ionic info`
in your project?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mtfaroks** [comment]
i have also same problem when i am serve my ionic project

**Comment by mtfaroks** [comment]
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.8.0
Xcode version: Not installed


Here is my info


and Here is my error 

Error
Close
Typescript Error
Module ''*'' has no exported member 'Options'.
node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts
import * as cleanCss from 'clean-css';
export declare function getCleanCssInstance(options: cleanCss.Options): cleanCss;
export interface CleanCssConfig {
Typescript Error
Cannot find name 'cleanCss'.
node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts
import * as cleanCss from 'clean-css';
export declare function getCleanCssInstance(options: cleanCss.Options): cleanCss;
export interface CleanCssConfig {
Typescript Error
Module ''*'' has no exported member 'Options'.
node_modules/@ionic/app-scripts/dist/util/clean-css-factory.d.ts
    destFileName: string;
    options?: cleanCss.Options;
}
Typescript Error
Cannot find type definition file for 'node'.
node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts
import { Stats } from 'fs';
export declare class VirtualStats implements Stats {
Typescript Error
Cannot find name 'Stats'.
node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts
export declare class VirtualStats implements Stats {
    protected _path: string;
    protected _ctime: Date;

**Comment by sjosen** [comment]
Same issue here :(
