### ISSUE TITLE
ios video'sounds in iframe is too small

### ISSUE THREAD

**Issue by cyanbluefire** [driftyco/ionic#10780]
my Page web.html has a iframe like this :
`  <ion-content>
  <iframe [src]="srcUrl"></iframe>  
</ion-content> `

and my ts is:
`import { Component } from '@angular/core';

import { NavController, NavParams } from 'ionic-angular';
import { DomSanitizer } from '@angular/platform-browser';
@Component({
  selector: 'page-web',
  templateUrl: 'web.html'
})
export class WebPage {
  title: string;
  srcUrl: any;
  constructor(public navCtrl: NavController,public navParams: NavParams, private sanitizer: DomSanitizer) {

  }
  ionViewDidLoad(){
    this.title = this.navParams.get('title');
    this.srcUrl = this.sanitizer.bypassSecurityTrustResourceUrl(this.navParams.get('url'));
    console.log('url=' + this.srcUrl);
    console.log('title=' + this.title);

  }

}`
srcUrl is passed from previous page like:
this.srcUrl = ' http://m.v.6.cn/live/u1?src=ummeda5263&forceback=1';

And then ,the video like this  is no sounds or too small sounds on iphone.
However,Android is fine.
Please help me ,Thanks.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by cyanbluefire** [comment]
@jgw96 Thanks!I have ask this question on forum.And anyone who will help me ?
