### ISSUE TITLE
Ionic 2 App and server on localhost communication not working

### ISSUE THREAD

**Issue by xande87** [driftyco/ionic#10788]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I´m building a Ionic 2 App for windows 10 that needs to communicate with a server running on localhost.

All works good if I run my application in a browser (either with `ionic serve` or `ionic run browser`) but the communication between App and LocalServer is not working if I launch the application with `ionic run windows` without being able to get any error message (the rest of the App works fine).

In a scenario where the server runs on another device (not using localhost) all works good again... Any tip on what is hapening and how this can be solved?

Server:
```javascript
var io = require('socket.io')();
io.on('connection', function(client){
  console.log('Connected...');
  client.on('message', function(data){
    console.log('message: ' + data);
  });
  client.on('disconnect', function() { console.log('Disconnected...'); });
});
io.listen(3300);
```
Client methods (Ionic 2 App):
```javascript
  connect() {
    console.log('Connect...');
    this.socket = io.connect('http://127.0.0.1:3300');
  }
  disconnect() {
    console.log('Disconnect...');
    this.socket.disconnect();
  }
  send() {
    console.log('Send...');
    this.socket.emit('message', 'test message...');
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by xande87** [comment]
Ok, thanks for the quick replay!
