### ISSUE TITLE
create Icons for IOS and BROWSER(favicon) does not work

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10787]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After creating my  icons using `ionic resource --splash` and `ionic resource --icon` the cli generates the pictures for splash and icons. As described in this very old bug [https://github.com/driftyco/ionic-cli/issues/1855], where I also add a comment, the pictures are only created for android and not for ios.

The other thing is, what's about the favicon for the browser? Have a look in the `config.xml` after creating pictures with cli, I see this new entry
`<icon src="resources/android/icon/drawable-xhdpi-icon.png"/>`
I think this should be the pictures which will be used instead of the favicon, but this does not work.

**Expected behavior:**
1. Please close the CLI bug for creating also the IOS pictures.
2. If the pictures from android resource configured as icon in config.xml should be the favicon for browser, it does not work. If this should be the picture for PWA icons, I think the created pictures for browser and PWA could and should be the same.
3. If I misunderstand anything, this should also be a feature request :) Please create also favicon on creating resource

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1995
