### ISSUE TITLE
Ability to customise range slider

### ISSUE THREAD

**Issue by megharajdeepak** [driftyco/ionic#10799]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

Can we add custom label tooltips (instead of showing numbers) when we change the slider? I wanted to use it for 'Office hours' (from 9AM to 6PM). I wanted to show a slider with 2 knobs. It starts at '7AM' and ends at '10PM' and user can select a range. When user changes the slider, the tool should show selected time like 9AM, 10AM etc. But tooltip always shows number, which is what I want to customise.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

This feature request has been raised based on suggestion from following link:
https://github.com/driftyco/ionic/issues/5422#issuecomment-286765422

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by JaneDawson** [comment]
I would love to use the slider component for choosing times, as well! (opening times, "don't disturb me", "contact me between" times, ...)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#128

**Comment by imanube** [comment]
Is there a workaround or solution to this functionality? The link above leads to a 404.  Can't seem to find anything useful on this topic.

**Comment by mshroomhead** [comment]
Anything new here? There is still a 404
