### ISSUE TITLE
doc: following grid documentation leads to sass warning

### ISSUE THREAD

**Issue by HassanCehef** [driftyco/ionic#10796]
Good evening :)
You might want to tag Documentation, and Grid.

**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

So, I'm following the documentation here https://ionicframework.com/docs/v2/api/components/grid/Grid/#grid-tiers that allows to choose the breakpoints of the grid. By using the variables written in the documentation, we get a SASS warning.

**Current behavior:**
```[20:35:21]  sass started ... 
WARNING: First value in `$grid-breakpoints` must start at 0, but starts at 480px.
Backtrace:
	node_modules/ionic-angular/themes/ionic.mixins.scss:67, in mixin `assert-starts-at-zero`
	node_modules/ionic-angular/components/grid/grid.scss:62

[20:35:22]  sass finished in 1.22 s 
```

**Steps to reproduce:**
* Start a ionic project (I did both blank and sidemenu, doesn't matter)
* add the code from the documentation to ` theme/variables.scss`
* get sass warning

**Related code:**

```sass
//file theme/variables.scss
$grid-breakpoints: (
  sm: 480px,
  md: 768px,
  lg: 1024px
);
```

I solved it by adding xs:0 
```sass
$grid-breakpoints: (
  xs: 0, // here
  sm: 480px,
  md: 768px,
  lg: 1024px
);
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: Not installed
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.0
Xcode version: Not installed

```
(Somehow I failed to install ionic+cordova properly on this computer, but I had this issue on the workstation I'm using, which is setup right.) 

I'm willing to submit a PR :smile:

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#1021
