### ISSUE TITLE
Automate the app.module.ts file entries

### ISSUE THREAD

**Issue by Sampath-Lokuge** [driftyco/ionic#10798]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

CLI doesn't create relevant entries on `app.module.ts` file when we create the Pages and Providers. We have to do it manually.

**Expected behavior:**

I would like to have a CLI feature where when we create a Page or Provider it should automatically create the relevant imports, declarations,entryComponents and providers on the `app.module.ts` file.

**Steps to reproduce:**

`> ionic generate page BillDetail`

`> ionic generate provider BillData`

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic. So we are actually ahead of the game on this and have been working on this recently. Keep your eyes peeled for big generators improvements coming soon (:

**Comment by Sampath-Lokuge** [comment]
Oh .. Excellent.Thank you @jgw96
