### ISSUE TITLE
datetime input that mimicks html5 datetime-local(ios)

### ISSUE THREAD

**Issue by petermm** [driftyco/ionic#10806]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request

**Current behavior:**
Datetime input that mimicks `<input type="datetime-local">` (on ios - see image) is currently not available (or undocumented). Docs state that DateTime is similar to this input type, but the attached input method is not available.

Highly useable UX for inputting near future events eg. "this friday at 9:45" or "tomorrow at 9:45" - without having to know precise dates (or having to double-check) etc. as that information is given in the input.

Year does become somewhat implicit but is given in the reference design(input type="datetime-local"). 

Have used this input format a lot with great success and no issues.

One can resort to native datetime pickers, but that leads to the usual variety of issues (testing, android fragmentation, native changes/bugs etc.).

**Expected behavior:**
some format that enables the following input format
![datetime](https://cloud.githubusercontent.com/assets/1033636/24001335/225ccc2c-0a5e-11e7-8d92-09b148698c37.png)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#129
