### ISSUE TITLE
native plugin AppPreferences is no exported member of ionic-native

### ISSUE THREAD

**Issue by Waog** [driftyco/ionic#10802]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Following the instructions of the AppPreferences native plugin ends in an error when using `cordova serve`:
```ts
import { AppPreferences } from 'ionic-native'; // results in compilation error
```
Error message:
```
Typescript Error
Module '"<project_path>/node_modules/ionic-native/dist/es5/index"' has no exported member 'AppPreferences'.
```

**Expected behavior:**

Without the bug the two lines of example code in the [docs](https://ionicframework.com/docs/v2/native/apppreferences/) should work as described.

**Steps to reproduce:**

1. `ionic start AppPreferencesBug --v2` (Create a new ionic project)
2. `cd AppPreferencesBug` (Navigate into the project)
3. `ionic plugin add cordova-plugin-app-preferences` (install the cordova plugin, like in the docs)
4. Insert `import { AppPreferences } from 'ionic-native';` into `/src/app/app.component.ts`
5. run `ionic serve`

**Related code:**

```
insert any relevant code here
```

**Other information:**

`import { StatusBar, Splashscreen } from 'ionic-native';` works properly

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)

******************************************************

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002



******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)

******************************************************
```

**Comment by Waog** [comment]
# Solution
running `npm install ionic-native@2.81 --save`solved the problem for me.

# Details
Seems like the AppPreferences isn't included in ionic-native 2.4.1, which is installed by default when not adding explicit version information.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic. I have updated our app-base to use ionic-native 2.8.1. It was previously on ionic-native 2.4.1 which has some bugs that have since been fixed. Sorry about this!

**Comment by jonnysmith1981** [comment]
Ran `npm install ionic-native@2.8.1 --save` but now getting:

`Property 'store' does not exist on type 'AppPreferences'.`

`ionic info` output:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```
