### ISSUE TITLE
*ngIf error after updating project to 2.4.8 from 2.2.1

### ISSUE THREAD

**Issue by vksgautam1** [driftyco/ionic#10803]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

template parse errors:
Parser Error: Unexpected token : at column 1 in [search] in HomePage@.
**Expected behavior:**

*ngIf is should work as it expected
**Steps to reproduce:**

**Related code:**
1h
[code]
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title class="header-title" *ngIf!="search">Exam List</ion-title>
   <ion-searchbar  *ngIf="search"></ion-searchbar>-->
    <div class="topright" *ngIf!="search" (tap)="searchclass()">
      <ion-icon name="search"  ></ion-icon>
    </div>
    <div class="topright" *ngIf!="search">
      <ion-icon name="apps"></ion-icon>
    </div>
  </ion-navbar>
</ion-header>
[/code]

```
insert any relevant code here
```

**Other information:**
This code was working with 2.2.1 but after updating to 2.4.8 it is giving error.
template parse errors:
Parser Error: Unexpected token : at column 1 in [search] in HomePage@.
Unhandled Promise rejection: Template parse errors:
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("
      <ion-icon name="menu"></ion-icon>
    </button>
     <ion-title [ERROR ->]*ngIf!="search" class="header-title">Class Detail</ion-title>
    <ion-searchbar (ionInput)="getItems"): HomePage@5:16
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("n>
     <ion-title *ngIf!="search" class="header-title">Class Detail</ion-title>
    <ion-searchbar [ERROR ->](ionInput)="getItems($event)" [hidden]="search"></ion-searchbar>
      <ion-buttons end [hidden]="sea"): HomePage@6:19
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("rch" class="header-title">Class Detail</ion-title>
    <ion-searchbar (ionInput)="getItems($event)" [ERROR ->][hidden]="search"></ion-searchbar>
      <ion-buttons end [hidden]="search"><button ion-button clear "): HomePage@6:49
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("
    </button>
     <ion-title *ngIf!="search" class="header-title">Class Detail</ion-title>
    [ERROR ->]<ion-searchbar (ionInput)="getItems($event)" [hidden]="search"></ion-searchbar>
      <ion-buttons en"): HomePage@6:4, Directive Searchbar
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("
    </button>
     <ion-title *ngIf!="search" class="header-title">Class Detail</ion-title>
    [ERROR ->]<ion-searchbar (ionInput)="getItems($event)" [hidden]="search"></ion-searchbar>
      <ion-buttons en"): HomePage@6:4, Directive Searchbar
Parser Error: Unexpected token : at column 1 in [search] in HomePage@5:16 ("
    </button>
     <ion-title *ngIf!="search" class="header-title">Class Detail</ion-title>

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

 ordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.1
Xcode version: Not installed

This same code is working fine in other project having 2.2.1 it is in header bar
.

**Comment by vazad28** [comment]
ngIf!="search. Should it be ngIf="!search"

**Comment by vksgautam1** [comment]
Thanks it is working now.I would be more careful now on these things.
