### ISSUE TITLE
Ionic Package building android with --prod does not change file size or minify javascript

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic#10808]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Two days ago, I built an `.apk` with this exact command, as copied from my ~/.bash_history: `ionic package build android --prod --profile dev_profile --release`. The `.apk` was 6.6 MB big, took 20 seconds, and was booting up in 6 seconds. This is good.

However, today, using the same exact command, using the same exact commit on Git (did a git checkout to the successful build). The `.apk` was 8.8 MB, took 20 seconds, and boot time at 16 seconds. This is bad. 

I tried debugging this to see if somehow my `--prod` flag wasn't working. So I ran another build like so, without the flag: `ionic package build android --profile dev_profile --release`. This yielded a build time of 40 seconds (expected), and the file was, once again 8.8 MB with a slow boot time.

So I can conclude that `--prod` is being noted by the change in build time, but for some reason, AoT compiling and minifaction is not happening. So no change in boot time, no change in file size. 

Only difference I can think of is the `/platform` directory which is gitignored. And the `/node_modules`, which I did a fresh `npm install`. No avail.

Had a co-worker do the same thing with the same repo + same command, adding `--prod` does not seem to change file size at all and other than taking 20 seconds faster to build there's no difference.

**Expected behavior:**
It should work like it did 2 days ago. I used the exact file, exact command. 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

```
Installed platforms:
  android 6.1.2
  ios 4.3.0
```

**Comment by kamok** [comment]
In my `config.xml`, I use  `<engine name="android" spec="latest"/>`. I'm guessing this is the problem. However, having trouble finding out the version history changelog from 3/14 - 3/16 (today).

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2009
