### ISSUE TITLE
Cannot get input element value 

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#10807]
Hi all,

I am beginner in angular 2

I develop web chat app using angular 2.Pls refer this http://imgur.com/dpnLSSv

I need dont display repeated value.Because I will check two variable.

below my html code

```
<div class="messagesholder" *ngFor="let chat of chatval | orderby:'[date]'">
  <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser">
    <p style="font-size:9px;text-align: center;" id="amount" #amount>{{chat.date | amDateFormat:'LL'}}</p>
    <input #myname type="hidden" value={{chat.date}}>
  </div>
  <div class="message" *ngIf="chat.sender == currentuser || chat.receiver == currentuser" [ngClass]="{'me': currentuser == chat.sender}">
    <div class='image' *ngIf="chat.path">
      <img *ngIf="chat.path" [src]="chat.path" /><br>
      <span *ngIf="chat.path_text">{{chat.path_text}}</span>
      <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
    </div>
    <div *ngIf="chat.message_text">
      <span>{{chat.message_text}}</span>
      <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
    </div>
  </div>
```

So i Bind the chat.date value using input tag.i get input element value using id.below my typescript file.

```
import { Component, Inject, ViewChild, ElementRef, AfterViewInit } from '@angular/core';

export class ChatPage implements AfterViewInit {
  @ViewChild('myname') input: ElementRef;
  constructor(public modalCtrl: ModalController, public navCtrl: NavController) { }
  ngAfterViewInit() {
    console.log(this.input.nativeElement.value);
  }
}
```

i am getting this error

Cannot read property 'nativeElement' of undefined

How to fix this issue.or any other way to find slutions.I need same values are does not show.

.I tried to many way.I have no idea.

Kindly Advice me,
Thanks & Regards

**Comment by rapropos** [comment]
This looks like a better fit for [the support forums](https://forum.ionicframework.com/) than a GitHub issue.

**Comment by sohenk** [comment]
i have the same problem .  can any one sovle this

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
