### ISSUE TITLE
New grid system no longer allows horitzonal scroll

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10813]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to use ion grid with ion items to create hortizonal scroll of ion items

**Expected behavior:**
Scrollable div instead of creating a new line when an item reaches the end of the document

**Steps to reproduce + Releated code:**

I'm trying to create a list of avatars, and each avatar to appear in the right of the previous avatar. When an avatar reaches the end of the screen, the user will be able to scroll left or right to see more avatars.

I achieved this with the following code which worked in the previous ionic grid version, and now no longer works and when an avatar reaches the end of the screen, a new line is created instead of keep added to the same line with an option to scroll horitzonally:

*

```

     <ion-scroll scrollX="true" class="chooseBg" style="height:70px">
               <ion-row>
                 <ion-col *ngFor="let avatar of avatars"
                 style="padding-right:0">
               <ion-item>
                 <ion-avatar>
                   <img
                   [src]="avatarImage(avatar)"/>
                 </ion-avatar>
                 </ion-item>
                 </ion-col>
                 </ion-row>
            </ion-scroll>

```

**Other information:**
Above code worked in previous version and allowed hortizonal scroll. new items didn't move to a new line when reaching the end of the document width

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by jbagaresgaray** [comment]
Any update on this bug? I also experience this kind of bug after update to the latest version

**Comment by jbagaresgaray** [comment]
I think the bug is on ion-row because  of 
.row {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    **-webkit-flex-wrap: wrap; ---> this one**
    **-ms-flex-wrap: wrap;  ---> this one**
   **flex-wrap: wrap;  ---> this one**
}

try create a custom class without using ion-row then on the class just use this value instead
.customclass {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}

use that class as substitute for ion-row and that will fix the horizontal scrolling issue... I've tried it and it and it works

**Comment by brandyscarney** [comment]
This was introduced in the move to the new grid. To avoid wrapping you can add the `nowrap` attribute to the row, which will also fix the scrolling:

```
<ion-grid>
  <ion-row nowrap>
    ..
  </ion-row>
</ion-grid>
```

Please see the API docs for more information:
http://ionicframework.com/docs/v2/api/components/grid/Grid/
http://ionicframework.com/docs/v2/api/components/grid/Row/
http://ionicframework.com/docs/v2/api/components/grid/Col/
