### ISSUE TITLE
Errors in Navigation Lifecycle Events are not caught by IonicErrorHandler

### ISSUE THREAD

**Issue by ashteya** [driftyco/ionic#10818]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When an error occurs in one of the Navigation Lifecycle Events like `ionViewDidEnter` it doesn't bubble up to the IonicErrorHandler.

**Expected behavior:**
I expect IonicErrorHandler to catch all errors that happen in the application, including errors in the lifecycle events.

**Steps to reproduce:**
I created a new app from the tabs template and modified the code in contact.ts to manually throw an error on `ionViewDidEnter`.

```
export class ContactPage {

  constructor(public navCtrl: NavController) {
  }

  ionViewDidEnter() {
    throw new Error('I am a bug');
  }
}
```

When I click on the tab Contacts, I can see the error in Chrome Dev Tools, but it's not hitting the code in IonicErrorHandler. 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.3
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed and will be in the next release (:. Ionic lifecycle events did not handle errors correctly before, but they will now throw correctly.
