### ISSUE TITLE
Ion-sliding-item could expose a public control api

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic#10815]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ion-sliding-item can be slided open only by a touch gesture and not programmatically.

**Expected behavior:**
ion-sliding-item should be able to be opened to any percent possible programmatically.

ion-sliding-item provides one feedback hook that reports back the percentage dragged and one control method that can close the item if open.
As an extra feature I would think it would be desirable to be able to open an ion-sliding-item at will programmatically to a given percentage. This would enable us to introduce a user to the sliding item functionality across different lists by doing a teaser animation (open, then close up to a certain percentage in first visit). 
ion-sliding-item has all the functionality in place but the control API is kept private. Maybe this could be reconsidered.

**Related code:**

```
// public method close "exposes" the required functionality, but with a hardcoded percentage
  close() {
    this._setOpenAmount(0, true);
  }
```

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#130
