### ISSUE TITLE
Ion Slide event for drag not completed

### ISSUE THREAD

**Issue by msprasad9** [driftyco/ionic#10821]
Ionic has ionSlideDidChange event when I changed form Slide 1 to Slide 2 while dragging a slide. But If I fail to move from Slide 1 to Slide 2 I couldn't find any event to capture. Can Any one help me how can I get that event. @brandyscarney @alexweber

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
