### ISSUE TITLE
Update info on polyfill.js

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#10825]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

The docs have no info on how do I pick a different polyfill. My build generates only polyfill.js. How to I get the other polyfill.
 
https://github.com/driftyco/ionic/tree/master/scripts/polyfill

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by awebdeveloper** [comment]
Thanks for the reply. Dont you think this info needs to be somewhere in the docs
