### ISSUE TITLE
ionic build android --prod disappear tabs and translate item

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#10824]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when build with ```ionic build android --prod``` disappear tabs and the item inside sidemenu not translate put the letter "t" for al item.

![screenshot_20170317-134120](https://cloud.githubusercontent.com/assets/12940555/24053490/f4c994b0-0b17-11e7-8505-11b6d64c5a89.png)
![screenshot_20170317-134055](https://cloud.githubusercontent.com/assets/12940555/24053491/f4cb8e28-0b17-11e7-9c39-94c712c39c65.png)

**Expected behavior:**
show tabs and correct label
**Steps to reproduce:**

-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.7.3
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
