### ISSUE TITLE
[Feature] Need ability to pick Day Name of Week 

### ISSUE THREAD

**Issue by sdey0081** [driftyco/ionic#10820]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Shows only day name as number ( From 1 to 31).

**Expected behavior:**

I only wanted to pick and display full name of a day(From _Monday_ to _Sunday_).

**Related code:**

```
    <ion-item>
      <ion-label>Day 3</ion-label>
      <ion-datetime displayFormat="DDDD" pickerFormat="DDDD" min="2001-01-01"  max="2001-01-07" (ngModel)]="dayOfWeek">
      </ion-datetime>
    </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
