### ISSUE TITLE
ionViewWillEnter and DidLoad of tab container not called on navback

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic#10836]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When navigate back from a page to tab the ionViewWillEnter of the tab container is not called

**Expected behavior:**

It must be called

**Steps to reproduce:**
Create simple project with tabs
Create a page and add a link to this page in the first tab
Navigate to this page then back

(add console.log("hello") in ionViewWillEnter of the tabs container)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
