### ISSUE TITLE
Bug: [Lighthouse][PWA] Remove property display: -ms-flexbox; from components

### ISSUE THREAD

**Issue by 0x1ad2** [driftyco/ionic#10834]
**Ionic version:**  (check one with "x")
[] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When deploying my app as PWA and I run Google Chrome's Lighthouse plugin to audit my app it throws an error **Avoids old CSS flexbox** Ionic components contain the `display: -ms-flexbox` property and that property seems to be deprecated.

<img width="922" alt="screen shot 2017-03-19 at 14 13 04" src="https://cloud.githubusercontent.com/assets/1705904/24081820/1c9320e8-0cbb-11e7-85da-91eed9623dc5.png">

[The 2009 spec of Flexbox is deprecated and is 2.3x slower than the latest spec.](https://developers.google.com/web/tools/lighthouse/audits/old-flexbox)

**Expected behavior:**
I expect the Lighthouse plugin to pass the test.

**Steps to reproduce:**
Setup a new Ionic blank v2 template and run lighthouse

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment]
We use autoprefixer to generate it:

```
.page-wrap {
  display: -webkit-box;  /* OLD - iOS 6-, Safari 3.1-6, BB7 */
  display: -ms-flexbox;  /* TWEENER - IE 10 */
  display: -webkit-flex; /* NEW - Safari 6.1+. iOS 7.1+, BB10 */
  display: flex;         /* NEW, Spec - Firefox, Chrome, Opera */
}
```

http://shouldiprefix.com/#flexbox

Eventually it would not be required, but you know... this is not a perfect world with everybody using Chrome 57
