### ISSUE TITLE
Tap event not canceled on page navigation

### ISSUE THREAD

**Issue by vinpez** [driftyco/ionic#10833]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Right now, we have a button which opens a component which has a toggle element, and the tap event from the first page carries through to the second page for some reason. I made a short video to demonstrate:

[page click bug.mov.zip](https://github.com/driftyco/ionic/files/853100/page.click.bug.mov.zip)

**Expected behavior:**
The expected behavior is no click press tap etc events from the first page persist when the second page opens.

**Steps to reproduce:**

[page click bug.mov.zip](https://github.com/driftyco/ionic/files/853100/page.click.bug.mov.zip)

**Related code:**

```
<button (click)="selectDevice(device)">

```

```
selectDevice(device: Device) {
       this.nav.push(ControlDevicePage, {"device": device});
 }
```

**Other information:**

If you need more info, I can be more precise or try to help. I usually respond within a few hours.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by vinpez** [comment]
Just following up - seems like a pretty major ionic issue. Any other information I need to supply?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! It looks as if your running on an old version of the framework (2.0.0-rc.3). Could you please update to the latest relase (2.3.0) ? This issue has been fixed since about rc.6 if i remember correctly (:

**Comment by vinpez** [comment]
Will update tonight and let you know how it goes.

**Comment by vinpez** [comment]
The update fixed the issue, thank you!
