### ISSUE TITLE
"index.js.map" fails to load on iOS 9

### ISSUE THREAD

**Issue by koyabr** [driftyco/ionic#10839]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When running the app on a device of iOS 9, there are tons of weird UI bugs, then I notice there is a red error printed in console, when I inspect using Safari on Mac:
```
file:///var/mobile/Containers/Bundle/Application/4ABB7301-7541-40C4-A159-2EF8D1827D12/myApp.app/www/build/index.js.map
Failed to load resource: The requested URL was not found on this server.
```

However, the error is gone when I switch to an iOS 10 device, everything works as expected, no UI bugs anymore.

**Steps to reproduce:**

1. build and run the app on a physical device running iOS 9
2. enable "web inspector" of Safari on the iOS device, then inspect using Safari on Mac
3. you'll see an error printed in console, like
```
file:///var/mobile/Containers/Bundle/Application/4ABB7301-7541-40C4-A159-2EF8D1827D12/myApp.app/www/build/index.js.map
Failed to load resource: The requested URL was not found on this server.
```

**Ionic info:** 

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by koyabr** [comment]
UPDATE: the "index.js.map" issue is not the reason for UI bugs, turns out you need intl polyfill for iOS<10, see http://stackoverflow.com/questions/35017800/ionic-2-using-angular-2-pipe-breaks-on-ios-cant-find-variable-intl

After importing intl package, my bugs are all gone. 

Not sure if I should close this issue or not, missing "*.js.map" may be not as harmful as I thought.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
