### ISSUE TITLE
Application crash when scanning using ZBar while SQLite installed

### ISSUE THREAD

**Issue by SirusDoma** [driftyco/ionic#10835]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When scanning via ZBar is initiated, the application crash without any error message, regardless SQLite connection to database is open or not.

**Expected behavior:**
Application run normally, SQLite works and scanning with ZBar work properly.

**Steps to reproduce:**
Install SQLite and ZBar, then call `scan()` function of ZBar.

**Related code:**
--

**Other information:**
I'm not sure where should I report this bug (SQLite or ZBar) but I have no idea whether its caused by ionic itself, so I decide to put the issue here.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cordova CLI: 6.4.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1224
