### ISSUE TITLE
Animation not working on modal dismiss

### ISSUE THREAD

**Issue by rajeevriitm** [driftyco/ionic#10845]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have defined an animation which trigger when I enter and dismiss the modal.

```
  trigger('reject', [
    state("in",style({transform: 'translateX(25vw)'})),
    transition('void => in',[
      animate('200ms ease-in', style({ transform: 'translateX(25vw)'}))
      ]),
    transition('* => void',[
      animate('200ms ease-in', style({ transform: 'scale(10)'}))
      ]),
    ]),
```

The animation works perfectly when I enter in the modal, but it doesnt work when I dismiss the modal. No animations happens when I dismiss it ( `transition(* => void,)` ).

**Expected behavior:**

transition * => void should be kicked in when I dismiss the modal.

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.7.2
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the angular animation library I would recommend you open an issue on the [angular repo](https://github.com/angular/angular). Thanks for using Ionic!
