### ISSUE TITLE
Updated Roadmap

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic#10847]
I'm very interested in the actual Ionic Roadmap and Vision of you guys. This one seems to be outdated: https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit

**Comment by brandyscarney** [comment]
Hey @tmvnk, you are correct that it is outdated. I've updated that document to include some high level goals, but we probably won't be updating it with individual issues for a bit. The best place to see current bugs / features that we are working on are the milestones: https://github.com/driftyco/ionic/milestones

Currently our main goals include making app's faster and improving routing. All of our work on this can be found on the 3.0 branch: https://github.com/driftyco/ionic/tree/3.0

To see exactly what we are working on every week, please take a look at our framework meeting notes which we update (nearly) every Monday: https://docs.google.com/document/d/1LrPDUkfXpqPIsghaSCxHyN1GIZ0TK2bwFxOZx2GKWtI/view

I hope this helps! Thanks for the issue. 🙂
