### ISSUE TITLE
feat - scroll overflow color to fit content color

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10842]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When having a content with a background color, when doing overflow scroll on iOS (when scrolled to top, drag down) the background is white.

**Expected behavior:**
The overflow background should be the same color as the content, with an option to supress.
Or perhaps (better imo) to have:

`<ion-content overflowTopColor="primary" overflowBottomColor="secondary"`

**Other information:**
This was asked on the ionic forums a long time ago:
https://forum.ionicframework.com/t/ios-set-ui-bounce-colors/81057/2

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#131

**Comment by cristianfloresee** [comment]
Any alternative solution for this?
