### ISSUE TITLE
THREAD WARNING: ['Keyboard'] took '88.104980' ms. Plugin should use a background thread. 

### ISSUE THREAD

**Issue by mobileias** [driftyco/ionic#10853]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

i am using phonegap build for creating ipa with ionic html framework and using latest cli like
`<preference name="phonegap-version" value="cli-6.5.0" />`
and ionic keyboard using latest version
`<plugin name="ionic-plugin-keyboard" source="npm" version="2.2.1" />`

Now after uploading latest ipa to itune it never shows keyboard very first click
and i see log like

`<Warning>: THREAD WARNING: ['Keyboard'] took '58.110840' ms. Plugin should use a background thread.`

Any one please help me to solve out this big issue as keyboard always shows after second click into input box or textarea even now it also not open select drop down very first time click

http://prntscr.com/emkaxz

Thank you in advance

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1225
