### ISSUE TITLE
ion-datetime [min] input gets set to 1st Jan of the current year if the date specified is of current year

### ISSUE THREAD

**Issue by rehannawab** [driftyco/ionic#10855]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I put any value in [min] for current year (eg:- '2017-02-20') the picker sets minimum date to 1st Jan 2017 rather than that particular date. If I put the value for [min] as '2016-02-20' it works as expected.

**Expected behavior:**
If the value for [min] is any date of current year it should allow dates that start from that particular date rather than 1st Jan.

**Steps to reproduce:**

For Ionic 2 issues -http://plnkr.co/edit/e0tr0Y?p=info
-->

**Related code:**

```
<ion-item>
      <ion-label>Current year Date</ion-label>
      <ion-datetime min="2017-03-20"></ion-datetime>
    </ion-item>
    <ion-item>
      <ion-label>Last year Date</ion-label>
      <ion-datetime min="2016-03-20"></ion-datetime>
    </ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
--------------------------------

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.1.4
OS: Windows 7 SP1
Node Version: v6.9.1


--------------------------------
```

**Comment by manucorporat** [comment]
Fixed in 2.3 release
