### ISSUE TITLE
Change detection does not work when using DeepLinker

### ISSUE THREAD

**Issue by mobyjames** [driftyco/ionic#10850]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Give the following component / view hierarchy:

```
DashboardPage - A
ActivityPage - B (contains deep links, which open another ActivityPage)
ActivityPage - C (opened from `B` via deep link)
```
`C` appears blank. Forcing a `tick()` allows the view to show, but no change detection takes place. Inspecting NgZone reveals `C` is not in the zone.

**Expected behavior:**
`C` displays and behaves (UI updates, change detection functions) as if it were opened via `.push()`.

**Steps to reproduce:**

Setup deeplink config:

```
export const deepLinkConfig: DeepLinkConfig = {
  links: [
    { component: ActivityPage, name: 'Activity Detail', segment: 'activity/:levelId/:id', defaultHistory: [ DashboardPage ] },
  ]
};
```

From within ActivityPage, create a link:

`<a href="#/activity/1/3">View Related Activity</a>`

Run the app, navigate to ActivityPage and click the link.

Another ActivityPage is pushed onto the stack and expected parameters are passed. However, the view does not update.

Everything works as expected in the browser, but does not work on iOS or Android.

Updating everything to Ionic 2.2.0  did not resolve the issue.

http://plnkr.co/edit/reAjyqirvzP5r5TVejcJ?p=preview <- works in browser, but not on device.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by inhand** [comment]
Unfortunately this is still an issue. I am experiencing this.

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.2 Build version 8E2002

I am linking to a changePassword page which has one field for the new password. I can get around this issue by subscribing to the form change and manually forcing change detection. However this does not help because after I do the password change I do a setRoot to the login page and the change detection is not working for this ( and subsequent pages ). If I don't deeplink to this page everything works as it should.

There seems to be something not being initialised when a page is navigated to via a deeplink.

**Comment by alessandroq** [comment]
same here please reopen

**Comment by saschwarz** [comment]
When I push a Page via a button and perform edits that result in changes to the page change detection works correctly. But when I push the same Page via a Deep Link edits do not update the page I have to force updates via ngZone.

**Comment by cguy** [comment]
@jgw96 Hello! Could you please reopen this issue? It still happens on last stable version (3.9.2). Or could you please share a workaround (how to enable the change detector / the zone)

**Comment by sconqua** [comment]
Hello, experiencing the same issue here with latest version: 

```
cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
```

**Comment by MattiaPrimavera** [comment]
Hello, experiencing the same issue here with latest version:

```
cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
```

**Comment by MattiaPrimavera** [comment]
Found a **work-around** here: [Deeplinks: change detection not working #1371](https://github.com/ionic-team/ionic-native/issues/1371) from @Manduro : 

```js
this.deeplinks.route(routes).subscribe(match => {
  console.warn('Successfully routed', match);
  console.warn(NgZone.isInAngularZone()); // false
  this.ngZone.run(() => {
    console.warn(NgZone.isInAngularZone()); // true
    this.navCtrl.push(match.$route, match.$args);
  });
}, nomatch => {
  console.warn('Unmatched Route', nomatch);
});
```

**Comment by cguy** [comment]
@MattiaPrimavera How did you use the deeplinks cordova plugin? Don't you already use the @IonicPage declaration for the routes?
