### ISSUE TITLE
Reduce boot time in ionic-2 app

### ISSUE THREAD

**Issue by dominicg666** [driftyco/ionic#10858]
[ ] **2.x**

I am new to ionic-2 project.I just want to know how to reduce boot time of app.Because after 3 sec of splash screen , it shows white screen and takes 16 sec to start.

**Comment by AmitMY** [comment]
compile for aot (using --prod) and other modifications can help.
This is a support request, which you should ask in the forums.

**Comment by dominicg666** [comment]
please give for example

**Comment by AmitMY** [comment]
https://forum.ionicframework.com/

**Comment by mburger81** [comment]
@dominicg666 
ionic build android --prod

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#828

**Comment by dominicg666** [comment]
E:\io\Fanuc>ionic build android --prod

> ionic-hello-world@ ionic:build E:\io\Fanuc
> ionic-app-scripts build "--prod"

[09:17:04]  ionic-app-scripts 1.1.0
[09:17:04]  build prod started ...
[09:17:04]  clean started ...
[09:17:04]  clean finished in 2 ms
[09:17:04]  copy started ...
[09:17:04]  ngc started ...
[09:17:14]  build prod failed: Error encountered resolving symbol values statically. Expression form not supported
            (position 6:12 in the original .ts file), resolving symbol TabindexDirective in
            E:/io/Fanuc/src/components/tabindex-directive/tabindex-directive.ts 
[09:17:14]  ionic-app-script task: "build"
[09:17:14]  Error: Error encountered resolving symbol values statically. Expression form not supported (position 6:12 in
            the original .ts file), resolving symbol TabindexDirective in
            E:/io/Fanuc/src/components/tabindex-directive/tabindex-directive.ts 
Error: Error encountered resolving symbol values statically. Expression form not supported (position 6:12 in the original .ts file), resolving symbol TabindexDirective in E:/io/Fanuc/src/components/tabindex-directive/tabindex-directive.ts
    at positionalError (E:\io\Fanuc\node_modules\@angular\compiler-cli\src\static_reflector.js:595:18)
    at simplifyInContext (E:\io\Fanuc\node_modules\@angular\compiler-cli\src\static_reflector.js:473:27)
    at StaticReflector.simplify (E:\io\Fanuc\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (E:\io\Fanuc\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (E:\io\Fanuc\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (E:\io\Fanuc\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (E:\io\Fanuc\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (E:\io\Fanuc\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at E:\io\Fanuc\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\io\Fanuc\npm-debug.log

**Comment by m00g33k** [comment]
There's an error in tabindex-directive.ts. Is this a fresh project with no modification?

**Comment by dominicg666** [comment]
tabindex-directive is directive
i can  share you my plugins list

package.json

`{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/cloud-angular": "^0.11.0",
    "@ionic/storage": "1.1.7",
    "google-libphonenumber": "^2.0.11",
    "ionic-angular": "2.0.1",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "Fanuc: An Ionic project"
}
`
app.module.ts

`import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { CloudSettings, CloudModule } from '@ionic/cloud-angular';

//directives


import { TabindexDirective } from '../components/tabindex-directive/tabindex-directive';


//pages
import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';
import { LoginPage } from '../pages/login/login';
import { AboutPage } from '../pages/about/about';
import { MyProductsPage } from '../pages/my-products/my-products';
import { MyServiceRequestPage } from '../pages/my-service-request/my-service-request';
import { ServicePage } from '../pages/service/service';
import { ServiceRequestPage } from '../pages/service-request/service-request';
import { ServiceRequestFirstPage } from '../pages/service-request-first/service-request-first';
import { ServiceRequestPopupPage } from '../pages/service-request-popup/service-request-popup';
import { SignupPage } from '../pages/signup/signup';
import { SignupTwoPage } from '../pages/signup-two/signup-two';
import { SignupOtpPage } from '../pages/signup-otp/signup-otp';
import { ForgotPasswordPage } from '../pages/forgot-password/forgot-password';
import { ChangePasswordPage } from '../pages/change-password/change-password';
import { RequestSuccessPage } from '../pages/request-success/request-success';
import { FocPage } from '../pages/foc/foc';
import { FocTwoPage } from '../pages/foc-two/foc-two';
import { ProductRegistrationPage } from '../pages/product-registration/product-registration';
import { GeneralEnquiryPage } from '../pages/general-enquiry/general-enquiry';
import { SearchProductsPage } from '../pages/search-products/search-products';
import { ProductDetailsPage } from '../pages/product-details/product-details';
import { MyAccountPage } from '../pages/my-account/my-account';
import { EditAccountPage } from '../pages/edit-account/edit-account';
import { EditProductDetailsPage } from '../pages/edit-product-details/edit-product-details';
import {ForgotPasswordTwoPage} from '../pages/forgot-password-two/forgot-password-two'

//additional library
import { FormsModule }   from '@angular/forms';
import { ElasticModule } from 'angular2-elastic';
//validators
import { EqualValidator, 
         PhoneValidator,
         CountryValidator
         } from '../validators';


//services
import {CountryList} from '../providers/country-list';
import {Myproducts} from '../providers/myproducts';
import {MyServiceRequests} from '../providers/my-service-requests';
import {Auth} from '../providers/auth';
import {ServiceRequest} from '../providers/service-request';
import {ProductRegistration} from '../providers/product-registration';
import {GeneralEnquiry} from '../providers/general-enquiry';
import {Foc} from '../providers/foc';
import {MyAccount} from '../providers/my-account';

const cloudSettings: CloudSettings = {
  'core': {
    'app_id': '6c191015'
  }
};

@NgModule({
  declarations: [
    MyApp,
    //directves
    TabindexDirective,
    //validators
    EqualValidator,
    PhoneValidator,
    CountryValidator,
    //pages
    LoginPage,
    AboutPage,
    MyProductsPage,
    MyServiceRequestPage,
    MyAccountPage,
    ServicePage,
    ServiceRequestPage,
    ServiceRequestFirstPage,
    ServiceRequestPopupPage,
    SignupPage,
    SignupOtpPage,
    SignupTwoPage,
    ForgotPasswordPage,
    ChangePasswordPage,
    RequestSuccessPage,
    FocTwoPage,
    FocPage,
    ProductRegistrationPage,
    GeneralEnquiryPage,
    SearchProductsPage,
    ProductDetailsPage,
    EditAccountPage,
    EditProductDetailsPage,
    ForgotPasswordTwoPage,
    Page1,
    Page2,
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    CloudModule.forRoot(cloudSettings),
    FormsModule,
    ElasticModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    LoginPage,
    AboutPage,
    MyProductsPage,
    MyServiceRequestPage,
    MyAccountPage,
    ServicePage,
    ServiceRequestPage,
    ServiceRequestFirstPage,
    ServiceRequestPopupPage,
    SignupPage,
    SignupOtpPage,
    SignupTwoPage,
    ForgotPasswordPage,
    ChangePasswordPage,
    RequestSuccessPage,
    FocTwoPage,
    FocPage,
    ProductRegistrationPage,
    GeneralEnquiryPage,
    SearchProductsPage,
    ProductDetailsPage,
    EditAccountPage,
    EditProductDetailsPage,
    ForgotPasswordTwoPage,
    Page1,
    Page2
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler},CountryList,Myproducts,MyServiceRequests,
  Auth,ServiceRequest,ProductRegistration,GeneralEnquiry,Foc,MyAccount]
})
export class AppModule {}
`

**Comment by Wolf00Bomber** [comment]
Any news on the resolution of this issue ?

I am seeing the same issue.

**Comment by chandanch** [comment]
use the `--prod` flag for `ionic build` this will decrease the load time.
