### ISSUE TITLE
feat - ion search iOS look

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10860]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, search is aligned left:
![image](https://cloud.githubusercontent.com/assets/5757359/24148133/26c9a91a-0e46-11e7-8fe2-f58485a6c504.png)
When focusing on it, there is no effect, except for input focus.
Also, search icon looks a tiny bit off

When it has text, it shows an `x` button:
![image](https://cloud.githubusercontent.com/assets/5757359/24148237/97ccf522-0e46-11e7-9d63-b19bc88836c9.png)

**Expected behavior:**
On native iOS apps, it looks like: (Mail, WhatsApp)
![image](https://cloud.githubusercontent.com/assets/5757359/24148093/edbfb1fa-0e45-11e7-9a04-16c83f281f43.png)
When focused: (hiding header, with cancel to right)
![image](https://cloud.githubusercontent.com/assets/5757359/24148094/f0b2de5a-0e45-11e7-863f-84e4c4a734c5.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by manucorporat** [comment]
Just use:
```html
<ion-searchbar animated="true"></ion-searchbar>
```

but, it might run slowly

**Comment by kelvindart** [comment]
There's a `showCancel` attribute. Also, `animated` will centre/alter the text alignment.

**Comment by kelvindart** [comment]
Oh - @manucorporat beat me to it. 🙂

**Comment by AmitMY** [comment]
@manucorporat while indeed, animated moves from center to the side, 2 design issues still remain:
- iOS shows "Cancel", ionic shows an x icon
- iOS animates to header, while ionic just animates the text align to left (see expected)

**Comment by AmitMY** [comment]
@manucorporat Also, when using `animated`, and `showCancelButton`, writing a single letter, then pressing "Cancel" it is still aligned left
