### ISSUE TITLE
alert.present() should resolve with user action on alert.

### ISSUE THREAD

**Issue by goleary** [driftyco/ionic#10866]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I create and present an alert, it returns a Promise that I guess resolves to true if the alert is correctly displayed

**Expected behavior:**
I was hoping alert.present() would return a promise that resolves with the value of the users action on the alert.  For instance on a confirm alert it could resolve to true if they hit OK and false if they hit cancel.
This would enable me to chain an action on the result of that alert.  As I have to have it nested within the button options.

**Steps to reproduce:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#135
