### ISSUE TITLE
docs: media-plugin is not available today in your websit

### ISSUE THREAD

**Issue by yt430010** [driftyco/ionic#10867]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://ionicframework.com/docs/v2/native/media-plugin
Ooops. The page you're looking for got lost in space.

The address might be mistyped or the page may have moved.
please fix it</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#1027
