### ISSUE TITLE
feat - integrated translation

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10861]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic is in English. If you integrate `ngx-translate` service, you still can't control everything, not to mention everyone have a huge overlap in their translation files, and when you can use a translation, your code becomes ugly (ts code)

**Expected behavior:**
An integration of ngx-translate to ionic core.

Lets say I have a searchbar, looking like:
![image](https://cloud.githubusercontent.com/assets/5757359/24149001/be90b95c-0e49-11e7-887d-c181ec607a4c.png)
The search placeholder would be needed to change from view every time

Or lets say I wanna do one of those:
```
let alert = this.alertCtrl.create({
	title: "New Friend!",
	subTitle: "Your friend, Obi wan Kenobi, just accepted your friend request!",
	buttons: ["OK"]
});

let loader = this.loadingCtrl.create({
	content: "Please wait...",
	duration: 3000
});

let toast = this.toastCtrl.create({
	message: "User was added successfully",
	duration: 3000
});
```

Here is how I would do the first one:
```
let alert = this.alertCtrl.create();
let lock = 3;
let unlock = () => {
	lock = lock--;
	if(lock == 0)
		alert.present();
};

this.translate.get("myPage.alert.newFriend").subscribe(res => {
	alert.setTitle(res.title);
	unlock();
});

this.translate.get("myPage.alert.subTitle").subscribe(res => {
	alert.setSubTitle(res.title);
	unlock();
});

this.translate.get("ionic.alert.buttons.ok").subscribe(res => {
	alert.addButton({
		text: res,
		handler: this.close.bind(this)
	});
});
```

Or write that as it's own method, and do:
```
const around = {
    title: "myPage.alert.newFriend",
    subTitle: "myPage.alert.subTitle",
    button: "ionic.alert.buttons.ok"
};

this.translateMultiple(around, (res) => {
    let alert = this.alertCtrl.create();
    alert.setTitle(res.title);

    alert.addButton({
        text: res.button,
        handler: this.close.bind(this)
    });

    alert.present();
});
```

Which is uglier (and more errors prone) than:
```
let alert = this.alertCtrl.create({
	title: "myPage.alert.newFriend",
	subTitle: "myPage.alert.subTitle",
	buttons: ["ionic.alert.buttons.ok"]
});
```

I believe ionic should have it's own `i18n` folder, and it should (on build) merge it's `i18n` with the user's `i18n` if any.
So the user can still override words, all of the iOS/Android saved words are regulated, less hassle, and if a user writes a `title` or whatever that does not show on translation, it would just return the word they wrote. No harm.

I went over all of the ionic components just to see if it's gonna be a major hassle, and I think it is not.
You can inject the translation service on demand, and use it wherever and however you want. This regulates application globalisation and makes languages easier to make.

And another reason to have this, is that all of the apps will feel the same. same translations, same words. and the community can help a lot, translating to languages they know.

Also, by going over the ionic major components, here is what I have as an ionic `i18n` english file:
```
{
	"ionic": {
		"globals": {
			"cancel": "Cancel",
			"share": "Share"
		},
		"alert": {
			"buttons": {
				"OK": "Ok",
				"save": "Save"
			}
		},
		"loader": {
			"loading": "Please wait"
		},
		"ionSearchbar": {
			"search": "Search"
		}
	}
}
```

It would be a great step for ionic to take imo, and it is not even difficult or complicated.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#136
