### ISSUE TITLE
Very slow resume

### ISSUE THREAD

**Issue by JustasKuizinas** [driftyco/ionic#10865]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic2 app resumes very slow, white screen stays for like 20-30 seconds

**Expected behavior:**
Ionic2 app should resume faster 

**Steps to reproduce:**
1. Download https://github.com/driftyco/ionic-conference-app.
2. Run ionic build android --prod --release.
3. Open app and press hardware back button, app goes to background.
4. Open app again from task manager list.
5. Wait for 30 seconds and app is ready to use.

**Other information:**
I am using android 5.0.
I also  noticed strange behavior, when I open app and press hardware circle button app goes to background, but later resumes very fast almost instantly and when I open and and press hardware back button instead of circle app goes to background, but resumes very slow.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

insert the output from ionic info here
`
 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed

`

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#827
