### ISSUE TITLE
Breaking change with android SDK

### ISSUE THREAD

**Issue by RaymsDev** [driftyco/ionic#10874]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
```

**Expected behavior:**
`Ionic build success`

**Steps to reproduce:**
With last version of android studio installed
`ionic run android`
-->

**Other information:**
related issue: https://github.com/cocos2d/cocos2d-x/issues/17424

When i run `android` command:
```
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
```

You can see in release note here: https://developer.android.com/studio/releases/sdk-tools.html
In version 25.3.0

> Changes:
> - Obsolete/deprecated tools have been removed:
>    - android

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by flastowizka** [comment]
I have the same after update the Android Studio.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by spetz83** [comment]
@jgw96 I don't think it's a support question... the ionic run android command will not work on the current version of Ionic and the latest Android SDK tools. The android team deprecated the "android" script that resides in the tools folder of the SDK. Was there a new version of Ionic today that already addressed this issue?

**Comment by linvi** [comment]
I agree this does no look like a support issue.

**Comment by RaymsDev** [comment]
Like related issue posted here: https://github.com/cocos2d/cocos2d-x/issues/17424 I downloaded previous version of SDK tools (25.2.3) available here: https://developer.android.com/studio/index.html
and then replaced tools folder in the Android sdk with the previous one.

Windows: https://dl.google.com/android/repository/tools_r25.2.3-windows.zip
Mac :https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
Linux: https://dl.google.com/android/repository/tools_r25.2.3-linux.zip

I can run `ionic run android` now

**Comment by spetz83** [comment]
@RaymsDev Right. I did that as well to get around this bug. Your post highlights that this shouldn't have been summarily closed as a support question.

**Comment by FreezeSoul** [comment]
I also got this error, and replaced with the old "tools" folder fixed.

**Comment by mrbfrank** [comment]
I hit this issue as well. Fixed by downgrading to older version of android-sdk.. though I had to publish a Homebrew tap to do so. Hope this helps everyone:
https://github.com/mrbfrank/homebrew-android-sdk-24
`brew install mrbfrank/android-sdk-24/android-sdk`

**Comment by mhartington** [comment]
This isn't an Ionic specific issue.
This is just an issue where the android SDK setup was not done correctly.

Please make sure you follow the cordova docs.

http://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html
