### ISSUE TITLE
Wrong resizing of components with new grid system

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10876]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We have a dashboard with 3 components (Move, Water, Temp&Hum) which are the same components <sensor> with some little different content

sensor-component:
```
<ion-card>
    <ion-card-header style="background-color: #00bcd4;">
        <h2 style="color: #fff;">{{sensor.description}}</h2>
    </ion-card-header>
   <ion-card-content>
     different content
   </ion-card-content>
</ion-card>
```

In the dashboard we load this 3 components doing this:
```
<ion-grid no-padding>
    <ion-row>
        <ion-col>
            <p>Configure Sensors</p>
        </ion-col>
    </ion-row>
    <ion-row>
        <sensor
            *ngFor="let sensor of sensors; let i = index"
            ion-col
            col-lg-4 col-md-4 col-sm-6 col-xs-12
            [sensor]="sensors[i]"
            [configure]="true">
        </sensor>
    </ion-row>
</ion-grid>
```
As you can see I use **col-lg-4** **col-md4** **col-sm-6** and **col-xs-12** to resize and redraw the components, but this does not work as expected

In screenshot **a)** you can see the components expand with a size of 4/12 which is working great
in screensho **b)** you can see how the components expand with a size of 6/12, and also this is working
in screenshot **c)** is only some pixels smaller then screenshot **b)** but the size of the components pass from **6/12** to **4/12** which is a bug
in screenshot **d)** you which should be the **col-xs-12** you can see the last component expand to **12/12** but the two components before have always a size of **6/12**

**a)**
![image](https://cloud.githubusercontent.com/assets/3778892/24205055/9932f702-0f1a-11e7-9fb4-a320ac34cfbd.png)

**b)**
![image](https://cloud.githubusercontent.com/assets/3778892/24205080/ab9c5956-0f1a-11e7-90ed-a8ef9233f442.png)

**c)**
![image](https://cloud.githubusercontent.com/assets/3778892/24205102/b88127c8-0f1a-11e7-94ac-88f64f5aad56.png)

**d)**
![image](https://cloud.githubusercontent.com/assets/3778892/24205123/c57186d0-0f1a-11e7-9fef-0219b734d4cb.png)

**Expected behavior:**
The grid resizing should simple work :P
I tested this on different scenarios and I have always the same problem, I don't know if you can reproduce it? Are you able doing this?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0-201703161917
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.1
    Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
So the attribute `col-xs-12` doesn't exist. It should be `col-12` to apply to all breakpoints (since it starts at min-width: 0). The way the grid works the smallest breakpoint isn't actually included in the attribute because it applies to *all* screen sizes unless you add attributes with the larger breakpoints to specify otherwise. Take a look at the docs for default breakpoints:

http://ionicframework.com/docs/v2/api/components/grid/Grid/#default-breakpoints

Let me know if you have any ideas of how to make this more clear. 🙂

**Comment by mburger81** [comment]
Sorry it was my mistake!
