### ISSUE TITLE
Introduce of sub menus to enhance desktop support

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#10875]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Until now ionic is following the style guides for mobile menus for mobile apps and this was good.

Now you with splitpane and others I think it's time to introduce also something like a sub menu. Introducing a sub menu we have a better way to have a menu for our desktop apps, which is the next step for ionic.

**Expected behavior:**
You can do two things, or reproducing something like me in my app, with a classical list and a sub list which works, see the screenshot
![image](https://cloud.githubusercontent.com/assets/3778892/24203863/22e25e56-0f17-11e7-876f-bc3890cf02ca.png)

Or you can do something which is more similar to the new md contacts web app, something like this
![image](https://cloud.githubusercontent.com/assets/3778892/24203922/4a1dcef6-0f17-11e7-91c9-e68df8510759.png)
![image](https://cloud.githubusercontent.com/assets/3778892/24203953/5ab80844-0f17-11e7-854f-cd88a66d762a.png)

To have a more desktop look and feel, the menus should have an activated color and an hover color which should be the same.

What do you think about this new feature? This would not be to difficult to implement.

Please let us know about your internal feature requests, your plans, your opinions and especially your decisions! 
Thx

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#134
