### ISSUE TITLE
Set width of menu on split-pane

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#10870]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Some fixed values are selectable.

**Expected behavior:**
I would like to set the menu width to e.g. 20 px so I could have a list
similar to page dividers:
A
B
C etc,

Is that possible with the current version?
If so, how?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Comment by mburger81** [comment]
I like the feature request, on Desktop browser the menu pane is to large, there are many many unused space in it

**Comment by MartinFreire** [comment]
Hi, I was looking the exact same thing.
The auto-size function is great, but I would like to set the "max-width" the side panel can reach. Because in big screens (for desktop of course) it gets really wide.
Screen Example: [https://www.dropbox.com/s/hj5039052up3x94/SplitPaneWidth.jpg?dl=0](url)
Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by MartinFreire** [comment]
@jgw96 Thanks for your reply. I'll try to find a way in the forum. But in my opinion it should be an option of the component.
I already did my try with the css and it's really not a easy thing to see
Thanks!

**Comment by MartinFreire** [comment]
I open the question in the forum: 
https://forum.ionicframework.com/t/set-width-of-menu-on-split-pane/83986

**Comment by mburger81** [comment]
I think so too, this should be by design not larger then required, so this should not be a user CSS problem.
IMO :) :+1:

**Comment by mburger81** [comment]
Hi @MartinFreire @jgw96,
@chrisgriffith opened the same issue as you, but he was more luckier than you 😄 
He opened a feature request for this today here https://github.com/driftyco/ionic/issues/10893 and they add the feature label on it :) so we can hope for a  it 👍
