### ISSUE TITLE
white space between items list ionic 2.3 if use virtual scroll and approxItemHeight

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic#10879]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

white space if use virtual scroll between items list

![image](https://cloud.githubusercontent.com/assets/12940555/24218831/7a280308-0f23-11e7-8229-54964b413150.png)

**Expected behavior:**

show the list items correctly

king regards

**Steps to reproduce:**

**Related code:**

```
// component

ionViewDidLoad() {
    console.log('ionViewDidLoad InboxPage');
    for (let i = 0; i < 1000; i++) {
      this.messages.push(this.getMessageRandom(i))
    }
  }

  getMessageRandom(label: number): IMessage {
    return {
      title: 'Account balance threshold ' + (label + 1).toString(),
      date: 'date',
      priority: Math.random() > 0.5 ? 'high' : 'info',
      read: Math.random() > 0.5,
      details: 'The balance of your account *****152 is outside the defined threshold. At 5/12 the balance is $ 84,638.93.'
    }
  }

// inbox.html
 <ion-list [virtualScroll]="messages" approxItemHeight="200px">
    <button ion-item *virtualItem="let message" (tap)="messageDetail($event, message)" [attr.priority]="message.priority">
        <i item-left ion-text [ngClass]="{'fa-envelope-open-o': message.read }" class="fa fa-envelope-o" aria-hidden="true"></i>
        <h2>{{ message.title }}</h2>
        <h3>{{ message.date }}</h3>
        <p>{{ message.details }}</p>
      </button>
  </ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

Cordova CLI: 6.5.0                 
Ionic Framework Version: 2.3.0     
Ionic CLI Version: 2.2.1           
Ionic App Lib Version: 2.2.0       
Ionic App Scripts Version: 1.1.4   
ios-deploy version: Not installed  
ios-sim version: Not installed     
OS: Windows 8.1                    
Node Version: v7.7.3               
Xcode version: Not installed       

```

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you paste some code that we can use to reproduce this?

**Comment by javico2609** [comment]
ok, not problem

**Comment by javico2609** [comment]
i find the bug, only happen when i put approxItemHeight

**Comment by javico2609** [comment]
same problem if i use ionic 3.0.0.beta3

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. With the latest nightly, which was built right off the master branch this morning and will be the 3.0 release i can no longer reproduce this issue.

**Comment by jlcarvalho** [comment]
@jgw96 I can reproduce this bug on 3.0.1. Even without `approxItemHeight`.

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: macOS Sierra
    Node Version: v7.7.4
    Xcode version: Xcode 8.3 Build version 8E162
```

![kapture 2017-04-07 at 22 10 46](https://cloud.githubusercontent.com/assets/1238663/24824297/1e9022aa-1bdf-11e7-9467-cf534ea0438c.gif)

**Comment by jlcarvalho** [comment]
In fact, everything is working fine. I had a lil hack on my css to make virtual scroll works, after the update this lil hack introduced the above bug. 

ps.: Sorry for the mention.
