### ISSUE TITLE
$ionicPosition substitute for ionic 2 ?

### ISSUE THREAD

**Issue by BigBorg** [driftyco/ionic#10886]
I need to locate the position of an element after scrolling or zooming. How is this done in Ionic 2 ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
