### ISSUE TITLE
Select/option doesn't work in chrome 54 android for touch events.

### ISSUE THREAD

**Issue by umasoodch** [driftyco/ionic#10884]
When I try to open dropdown on android chrome version 54 its not letting me to do this. My current ionic version is 1.3.2. I have checked the commit comments of 1.3.2 and the ionic team stated that this issue has been fixed. What I think is it happened after new update of chrome.

Any help would be highly appreciated.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#233
