### ISSUE TITLE
bugs - ion-nav-back-button "hide" class, ion-nav-bar set to "invisible" class in Google

### ISSUE THREAD

**Issue by lwenke** [driftyco/ionic#1088]
Closed issues about this:

https://github.com/driftyco/ionic/issues/1017
https://github.com/driftyco/ionic/issues/1018

http://forum.ionicframework.com/t/bug-ion-nav-bar-set-to-invisible-class-in-chrome-for-2-starter-apps/2572/3
dk​01 wrote:
"I am having this same exact issue. My app works fine in Firefox, Safari, the IOS Simulator. It fails in Chrome. I see the invisible class as well....."

http://forum.ionicframework.com/t/bug-ion-nav-back-button-set-to-hide-class-in-chrome-for-2-starter-apps/2571/3
fred​pmc wrote:
"I am on Chrome Version 34.0.1847.116 and it is not working."

In 1018 ajoslin wrote:
"Seems like it may be a different error; perhaps due to a problem in your application or a plugin in Chrome."

I am using unedited starter apps - the tabs and sidemenu starter apps so I'm not adding my own bug to it.

The only plugins I'm using is AngularJS Batarang and AdBlock. 

BTW the error involves two classes appearing amongst the code - "hide" and "invisible" on ion-nav-back-button and ion-nav-bar.

So I'm saying that ajoslin's theory doesn't explain why those classes are appearing in the ionic directives.

**Comment by kapiltecklis** [comment]
![back](https://cloud.githubusercontent.com/assets/12513350/7703930/bae147a2-fe58-11e4-9f5b-48404111f359.png)


back navigation working properly but not showing in wp8
