### ISSUE TITLE
SplitPane menu content items not showing

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic#10880]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Menu items in SplitPane aren't showing

**Expected behavior:**
Menu items in SplitPane should show

```javascript
<ion-split-pane>
    <ion-menu [content]="content" class="menuContainer">
        <ion-header>
            <ion-toolbar>
                <ion-title>menu</ion-title>
            </ion-toolbar>
            <ion-content>
                <ion-list>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                </ion-list>
            </ion-content>
        </ion-header>
    </ion-menu>

    <ion-nav #content [root]="rootPage" main></ion-nav>
</ion-split-pane>
```
![screen shot 2017-03-22 at 10 41 08 pm](https://cloud.githubusercontent.com/assets/3672236/24222105/406a1c4a-0f51-11e7-823b-c8d2d461c20c.png)

**Comment by jbagaresgaray** [comment]
can you attached the full screenshot of your screen where the bug occurs? Coz I believe, thats why it doesn't coz split-pane requires large screen to display...

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! When you open your app on a tablet or in chrome does the sidemenu show? The sidemenu is only supposed to become split when the app is viewed on larger viewports.

**Comment by manucorporat** [comment]
You markup is wrong, you are wrapping everything with `ion-header`: 
```
<ion-split-pane>
    <ion-menu [content]="content" class="menuContainer">
        <ion-header>
            <ion-toolbar>
                <ion-title>menu</ion-title>
            </ion-toolbar>
        </ion-header>

            <ion-content>
                <ion-list>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                    <ion-item>settings</ion-item>
                </ion-list>
            </ion-content>
    </ion-menu>

    <ion-nav #content [root]="rootPage" main></ion-nav>
</ion-split-pane>
```

**Comment by cozzbie** [comment]
Thanks @manucorporat I totally missed that I had copied over a previously well formatted one. Sigh. Thanks again.
