### ISSUE TITLE
Slides -- Last Pagination Bullet Doesn't Highlight When Go From First To Last Slide

### ISSUE THREAD

**Issue by minhtuanta** [driftyco/ionic#10883]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When going from first slide to last slide, the pagination bullet of the last slide doesn't highlight.

**Expected behavior:**
The pagination bullet of the last slide should be highlighted.

**Steps to reproduce:**
Plunker: http://plnkr.co/edit/V81JQoC55X5PTIvynQUW?p=preview

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will look into this.
