### ISSUE TITLE
It's not clear which file to import for '@import "ionic.ionicons"'. Candidates: ionic.ionicons.scss ionic.ionicons.css Please delete or rename all but one of these files.

### ISSUE THREAD

**Issue by niuemperor** [driftyco/ionic#10882]
**Ionic version:**  (check one with "x")
Ionic Framework Version: 2.2.0

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by brandyscarney** [comment]
You should be importing the following way:

```
@import "ionic.ionicons";
```

https://github.com/driftyco/ionic-conference-app/blob/master/src/theme/variables.scss#L81

Which will import this file: https://github.com/driftyco/ionic/blob/master/src/themes/ionic.ionicons.scss
