### ISSUE TITLE
VirtualScroll in 2.3.0: "Uncaught TypeErrors" when scrolling

### ISSUE THREAD

**Issue by szerner** [driftyco/ionic#10885]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I beginn to scroll in my Virtual Scroll <ion-list>, I immediately get the following "Uncaught Type Error(s)" error(s) in chrome:

```
virtual-scroll.js:538 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at VirtualScroll.scrollUpdate (virtual-scroll.js:538)
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at ScrollView.scroll.onScroll (content.js:328)
    at HTMLDivElement.scrollCallback (scroll-view.js:161)
VirtualScroll.scrollUpdate @ virtual-scroll.js:538
schedulerFn @ async.js:105
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
scroll.onScroll @ content.js:328
scrollCallback @ scroll-view.js:161
virtual-util.js:257 Uncaught TypeError: Cannot read property 'length' of null
    at updateDimensions (virtual-util.js:257)
    at VirtualScroll.scrollEnd (virtual-scroll.js:602)
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at ScrollView.scroll.onScrollEnd (content.js:333)
    at scrollEnd (scroll-view.js:157)
    at dispatch (dom-controller.js:195)
    at DomController._flush (dom-controller.js:146)
    at rafCallback (dom-controller.js:135)
updateDimensions @ virtual-util.js:257
VirtualScroll.scrollEnd @ virtual-scroll.js:602
schedulerFn @ async.js:105
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
scroll.onScrollEnd @ content.js:333
scrollEnd @ scroll-view.js:157
dispatch @ dom-controller.js:195
DomController._flush @ dom-controller.js:146
rafCallback @ dom-controller.js:135
```
This error shows up since my updating to Ionic 2.3.0.

**Expected behavior:**
Scrolling in VirutalScroll list without exceptions.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, unfortunately i cannot reproduce this issue, would you mind sharing a repo we could reproduce this with? Thanks!

**Comment by szerner** [comment]
I managed to trace this issue down to my fault:
in my template I have two subsequent virtual scoll lists, which are triggered by an *ngIf clause:

```
<ion-list *ngIf="first" [virtualScroll]="items">
...
<ion-list>
<ion-list *ngIf="!first" [virtualScroll]="items">
...
<ion-list>
```

but my switch "first" was initialized in ionViewDidLoad() - obviously too late for a proper initialization of the template. After moving the initialization of "first" to the constructor, the runtime errors have gone.

With Ionic 2.2.0 I didn't run into this issue.

Since this issue obviously wasn't due to the upgrade to Ionic 2.3.0, I close this issue and thank you for looking into it!

**Comment by mapicard** [comment]
Hi guys, ( @szerner @jgw96 )

I'm running into the same error but still can't figure out why.
I've posted my issue in ionic forum
https://forum.ionicframework.com/t/virtualscroll-scrollto-generates-typeerror-cannot-read-property-scrolltop-of-null/123148/2

I see your issue seemed related to concurrent scrollTo calls, and I think that is also what is happening to me, but not sure if it is the case and how to solve it.

I have a liveSample where it can be reproduced at will. 
Just bring down the alpha-index-slider fast and you will get the error.
https://ionic-list100k-segment-index.stackblitz.io/

Thanks for any input.
Martin
