### ISSUE TITLE
Slides -- Loop Doesn't Work Properly When Loading Slide Async

### ISSUE THREAD

**Issue by minhtuanta** [driftyco/ionic#10892]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using ngFor to create ion-slide and load the array from a service async, the Slides component doesn't work properly:

* Loop from first slide to last slide doesn't work anymore.

* Loop from last slide to first slide jump to the second slide instead.

**Expected behavior:**

* Loop from first slide to last slide should work.

* Loop from last slide to first slide should be at first slide instead of second slide.

**Steps to reproduce:**
Please check this Plunker: http://plnkr.co/edit/B0cKQp44IOpukHcin68h?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will look into this.

**Comment by jgw96** [comment]
Hello, after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6703. Thanks!
