### ISSUE TITLE
Virtual scroll not rendering items anymore.

### ISSUE THREAD

**Issue by Ross-Rawlins** [driftyco/ionic#10894]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I updated my project to 2.3 and left my virtual-scroll implementation the same. I have see my list is populated and I can see the list being passed to virtual scroll. But virtual scroll doesnt render each item in the list.

**Expected behavior:**

I would see the list being populated and the child component being populated with data.

**Steps to reproduce:**

**Related code:**
for (var i = 0; i < res.value.length; i++) {
                            let eventObject = res.value[i];
                            eventObject.listIndex = i
                            this.eventsList.push(eventObject);
                        }
I have tried pushing each item 1 at a time to the list and concating a list of items.
this.eventsList = this.eventsList.concat(res.value);
```
insert any relevant code here
here is the template code
<ion-content>
    <ion-refresher (ionRefresh)="refreshEvents($event)">
        <ion-refresher-content
            pullingIcon="arrow-dropdown"
            pullingText="Pull to refresh"
            refreshingText="Getting latest events..."></ion-refresher-content>
    </ion-refresher>
    <ion-list [virtualScroll]="eventsList" [approxItemHeight]="'250px'">
        <div *virtualItem="let item" >    
            <events-item [item]="item" ></events-item>
        </div>
    </ion-list>
    <ion-infinite-scroll (ionInfinite)="getMoreEvents($event)">
        <ion-infinite-scroll-content
            loadingText="Getting more events..." 
            ></ion-infinite-scroll-content>
    </ion-infinite-scroll> 
    <ion-fab bottom right>
        <button ion-fab color="secondary"><ion-icon name="funnel"></ion-icon></button>
    </ion-fab>
</ion-content> 
```

**Other information:**

this is the generated HTML from the virtual scroll

<ion-list class="list list-md virtual-scroll" ng-reflect-virtual-scroll="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" ng-reflect-approx-item-height="250px">
        
    <div class="virtual-last"></div></ion-list>

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by manucorporat** [comment]
Investigating

**Comment by manucorporat** [comment]
can you provide a repo that reproduces the issue?

**Comment by Ross-Rawlins** [comment]
its 9pm where I am so I can only do this tom when I am back online.

**Comment by aggarwalankush** [comment]
Same issue, virtual scroll not showing any items

```
  <ion-list [virtualScroll]="myAlertList"  approxItemHeight="115px">
    <button ion-item text-wrap
            *virtualItem="let alert"
            (click)="alertClicked(alert)">
      {{alert.name}}
    </button>
  </ion-list>
```

**Comment by Ross-Rawlins** [comment]
Just an FYI until I can get this plunkr up. While testing I see that the initial list I send on page load to virtual scroll fails. BUT when I do another api call then the list gets rendered. its something to do on page load that its not rendering.

**Comment by nwrman** [comment]
Same here, I was coming from #6423 

On v2.2 Virtual Scroll + Infinite Scroll was janky .

When I updated to v2.3 Virtual Scroll stopped working altogether.

**Comment by Ross-Rawlins** [comment]
this is a duplicate of #10971
