### ISSUE TITLE
Split Pane Component sizing settable via SASS variables

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic#10893]
The min and max widths for the split pane are hard coded. Would like to have those values be settable via SASS variables

**Comment by brandyscarney** [comment]
Sure, @manucorporat let's call these:

```
$split-pane-ios-side-min-width
$split-pane-ios-side-max-width
```

https://github.com/driftyco/ionic/blob/master/src/components/split-pane/split-pane.ios.scss#L10

Thoughts?

**Comment by chrisgriffith** [comment]
Don't forget the other two platforms ;)  Do we want to have a global set of variables for this, as well as platform specific?
