### ISSUE TITLE
bug: Geocode instance non present

### ISSUE THREAD

**Issue by Vito96** [driftyco/ionic#10909]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Geocode instance is not present in Geocoder (ionic-native).</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#1249
