### ISSUE TITLE
any help for webRTC steaming with IOS platform   ? 

### ISSUE THREAD

**Issue by monyoudom** [driftyco/ionic#10902]
I want to develop the app using ionic 2 that can use webRTC. In my case , it is work fine for android, but it seems doesn't work for iOS. I think IOS platform they don't support WebRTC. I would like to know,Could we use ionic 2 build and webRTC in iOS ?

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for support questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
