### ISSUE TITLE
ion-split-pane menu right big screen show in the left with RTL apps

### ISSUE THREAD

**Issue by mohamedsharaf** [driftyco/ionic#10903]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

menu even side = right in desktop goes to left it was working fine in v2.2

**Expected behavior:**

sho menu in right
**Steps to reproduce:**

**Related code:**

```
<ion-split-pane>
    <ion-menu side="right" [content]="content">
        <ion-header>
       </ion-header>

        <ion-content>
           <ion-list>
           </ion-list>
        </ion-content>

    </ion-menu>


    <ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>

</ion-split-pane>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.1
Xcode version: Not installed

```
![26e55bf6-1076-11e7-919c-f6559893656b](https://cloud.githubusercontent.com/assets/895464/24577758/72699f58-16dc-11e7-9dd2-2c3b70f6349b.png)

![small](https://cloud.githubusercontent.com/assets/895464/24283340/33d21ec6-1076-11e7-9051-34f18797ff75.png)

**Comment by alaa-alshamy** [comment]
yep i can confirm this

**Comment by siordache94** [comment]
Any updates since Ionic 4 is out ? Thanks
