### ISSUE TITLE
Android hardware back button doesnt obey NavControllers setRoot() method

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic#10913]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
A user hits the app and on first launch is visited by a WelcomePage

```javascript
this.rootPage = WelcomePage;
```

After successful login, I set the TabsPage as the root

```javascript
this.navCtrl.setRoot(TabsPage);
```

A user now hits the HARDWARE BACK BUTTON on ANDROID and goes back to the `WelcomePage`

**Expected behavior:**

`this.navCtrl.setRoot(TabsPage);` should make `TabsPage` the last item in the navigation stack and thus the app should close when the user hits the HARDWARE BACK BUTTON on ANDROID if the person has no more views within the hierarchy of the current `TabsPage` roots navigation stack. 

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by themastersoda** [comment]
I think you're setting rootPage on the wrong nav tree, which results in WelcomePage remaining in navigation history. Try changing to TabsPage like this:

`import {App} from 'ionic-angular';`

inside constructor:
`constructor(private app: App){}`

then inside the function that handles page switching:
`this.app.getRootNav().setRoot(TabsPage);`

**Comment by cozzbie** [comment]
Will try that thanks.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
