### ISSUE TITLE
button[clear] with ion-item don't have clear style applied

### ISSUE THREAD

**Issue by keep-faith** [driftyco/ionic#10911]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
clear attribute only works when button use the directive ion-button together

**Expected behavior:**
'clear' attribute should apply the clear style to the button

**Steps to reproduce:**
on this demo, the first button use ion-button and the second use ion-item
http://plnkr.co/edit/NTd1DCAF7RHEtPd0u44m?p=preview

**Other information:**
this is my first ever post here, so if i did something wrong please sorry

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment]
@keep-faith this does not make any sense to me...
how should a "clear" ion-item look? clear is a ion-button only thing
