### ISSUE TITLE
Cannot set selected attribute for dynamically loaded ion-select

### ISSUE THREAD

**Issue by Sampath-Lokuge** [driftyco/ionic#10918]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

Hi,

I need to load `<ion-select>` dynamically.It is working fine.Now I need to set default selection.I have used `selected` attribute for that.But it is not working.Can you tell me why?

app/home.page.html

```
 <ion-item>
      <ion-label>Donation</ion-label>
      <ion-select>
        <ion-option *ngFor="let date of donationDates" value="{{date.donationdate}}" selected="date.isChecked">
          {{date.donationdate}}</ion-option>
      </ion-select>
    </ion-item>
```

app/home.page.ts

```
export class HomePage {
  donationDates:any=[];

  constructor(public navController: NavController) { 
      this.donationDates = [
       {
          id: null,
          donationid: "2",
          donationdate: "2017-03-12",
          datedescription: "Vad Bij",
          isChecked:true
      },
      {
        id: null,
       donationid: "2",
       donationdate: "2017-03-19",
       datedescription: "Sud satam",
       isChecked:false
     }]
  }

}
```
**Plunker is here :** [**Plunker**](http://plnkr.co/edit/sWno6H?p=preview)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by juntaforce** [comment]
This is a bug, instead of find a solution you say that checked the forum. There is no any solution for that on forum or slack channel aldı there are öpen üssü with months but anyone didnt solved it

**Comment by juntaforce** [comment]
This is a bug, instead of find a solution you say that checked the forum. There is no any solution for that on forum or slack channel aldı there are öpen üssü with months but anyone didnt solved it

**Comment by henrymidio** [comment]
Nothing yet?
