### ISSUE TITLE
v3 - bug - grid padding behaviour is wrong

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#10912]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Having a normal grid (one row, one col - test), its padding is off the charts, even when I see it is just 5px.
![image](https://cloud.githubusercontent.com/assets/5757359/24312555/356e00fa-10ea-11e7-9405-5bad06da83d9.png)
I have many grids usages, and it happened only in 2 of them..

**Expected behavior:**
When removing the `padding: 5px`  from the `grid` class:
![image](https://cloud.githubusercontent.com/assets/5757359/24312585/51a2f514-10ea-11e7-8a2d-51baae13bc7c.png)

As you can see, the difference is not 5px in each direction..

**Related code:**

```
<ion-grid>
    <ion-row>
        <ion-col>A</ion-col>
    </ion-row>
</ion-grid>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0-201703231941
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
I've released a new version `3.0.0-beta.1` with this fix, here are some steps to upgrade with the latest versions:

https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit?usp=sharing

Thanks! 🙂

**Comment by AmitMY** [comment]
@brandyscarney Thanks for the fix
Can I ask why did you add "@angular/animations"? Where do you use it?

**Comment by brandyscarney** [comment]
@AmitMY It is a peer dependency for Angular: https://github.com/angular/angular/blob/master/CHANGELOG.md#animation-package

**Comment by AmitMY** [comment]
@brandyscarney Oh, I was sure it was optional. Thanks for the link

**Comment by brandyscarney** [comment]
@AmitMY I think maybe it should be, but Angular has it listed as a peer dependency on `@angular/platform-server`:

https://github.com/angular/angular/issues/15427#issuecomment-288824375
https://github.com/angular/angular/issues/15450#issuecomment-289027132

I actually just messaged the Angular team about it, so I'll let you know!

**Comment by brandyscarney** [comment]
@AmitMY So it is a peer dependency on purpose, however since we are not using platform-server we decided to remove it from Ionic. I released a new version that doesn't need `animations` or `platform-server`: `ionic-angular@3.0.0-beta.2`

**Comment by AmitMY** [comment]
@brandyscarney Thanks for the very quick responses and updates.
So far, beta is stable except for that one bug https://github.com/driftyco/ionic/issues/10863
