### ISSUE TITLE
bug: Ion-navbar not transitioning some icons in iOS mode

### ISSUE THREAD

**Issue by benharpers** [driftyco/ionic#10919]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>When transitioning from one page to another, some icons do not transition, rather they just get cut-off by the page that is transitioning. See this screenshot on forum post (link below), the gear at the top right of the first page is cut-off by the second page as it slides.

https://forum.ionicframework.com/t/ion-navbar-not-transitioning-some-icons-in-ios-mode/84166</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
