### ISSUE TITLE
rtl support for alert view (material design)

### ISSUE THREAD

**Issue by AsimNet** [driftyco/ionic#10923]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

alert view title and message are LTR now.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
      let prompt = this.alertCtrl.create({
                title: this.translate.instant("ERROR"),
                message: this.translate.instant("EVENT_OVERDUE"),
                buttons: [
                  {
                    text: this.translate.instant("DONE_BUTTON"),
                    handler: (data) => {
                      //Go back!
                      this.navCtrl.pop();
                    }
                  }
                ]
              });
              prompt.present();
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#132

**Comment by AsimNet** [comment]
now does it supports RTL ?
