### ISSUE TITLE
ionic blank template wont run on MAC  OS X El Capitan emulator

### ISSUE THREAD

**Issue by verylongword** [driftyco/ionic#10925]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

"white screen of death" from  ionic blank template --v2
on MAC emulator OS X El Capitan

**Expected behavior:**
The standard ionic template blank app should display "the world is your oyster"

**Steps to reproduce:**
On : OS X El Capitan
Do in a terminal:

ionic start Test blank --v2
cd Test
ionic platform add ios
ionic prepare ios
ionic emulate ios --consolelogs
---> "white screen of death"   instead of  "the world is your oyster"

AND instead with an attempt to use wkwebview:

ionic plugin rm cordova-plugin-wkwebview-engine
ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save
	--> Installing "cordova-plugin-wkwebview-engine" for ios
		--> Error: The header content contains invalid characters
ionic prepare ios

LAUNCH XCODE from/Users/apple/Desktop/don/ionic2/Test/platform/ios/.xcodeproj
In xCode: Run on simulator
---> "white screen of death"

**Related code:**

NONE

**Other information:**
 "white screen of death"  does not produce the usual log,  but I recall seeing somewhere the message:
deviceReady fired after 1800 ms (I remember the first 2 digits).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
