### ISSUE TITLE
changing tabBadge number automatically with EventEmitter is not working

### ISSUE THREAD

**Issue by mazyvan** [driftyco/ionic#10927]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when the event emitter is fired, the subscribe recibes that value. and the new value is storing in the local variable, but the view shows the previous one until some other event happens, like a doRefresh, doInfinite, or touching the tab-bar, etc...
**Expected behavior:**

Immediately change that badge number 

**Steps to reproduce:**

**Related code:**

```
export class TabsPage {
  public newNotifications;
  HomePageTab = HomePage;
  SearchPageTab = SearchPage;
  SendPageTab = SendPage;
  SubscriptionsPageTab = SubscriptionsPage;
  ProfilePageTab = ProfilePage;

  constructor(
    public sharedVariables: SharedVariables
  ) {

    this.sharedVariables.numberOfNotifications
      .subscribe(newNotifications => {
        console.log("new notification" + newNotifications);
        this.newNotifications = newNotifications;
      });
  }

}
```
this is the code on TabsPage component.

In the template I have  **tabBadge="{{ newNotifications }}"** and the weird part is that the log is showing perfectly, that means that the local variable is actually storing the new value, but as I mentioned above the badge don't update until other thing happens in the app.

I think this could have something to do with NgZone, but I also think that this must not be the correct behavior for this.
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement custom functionality, i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
