### ISSUE TITLE
How to pass custom params in to GoogleMapsMarkerOptions

### ISSUE THREAD

**Issue by narayansikarwar** [driftyco/ionic#10929]
There is no option to pass some custom data in to **GoogleMapsMarkerOptions** typescript wrapper. So we need some property for passing custom data to **GoogleMapsMarkerOptions** like **params**.
Because cordova native map plugin already have these options like
```
const GOOGLE = new plugin.google.maps.LatLng(37.422858, -122.085065);
map.addMarker({
  'position': GOOGLE,
  'myMsg': 'Hello'
}, function(marker) {
  alert(marker.get("myMsg"));
});
```

Here 'myMsg': 'Hello' is a custom parameter.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1267
