### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by ggshihai** [driftyco/ionic#10926]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

D:\ionic>ionic start myApp tabs

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.1
Xcode version: Not installed
 
```
insert the output from ionic info here

D:\ionic>ionic start myApp tabs
Creating an Ionic app in D:\ionic\myApp based on the tabs template.

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
Installing npm packages (may take a minute or two)...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall

**Comment by realfreebird** [comment]
Hi,

I had the same error. 
Since I have a local npm repository, I solved it by running the following command:

npm config set @ionic-native:registry https://registry.npmjs.org/

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2037
