### ISSUE TITLE
[2.3.0] ionic-angular@2.3.0 unmet peer dependencies

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#10939]
**Ionic version:**  (check one with "x")
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] feature request

**Current behavior:**
I upgraded and configured my package.json dependencies as displayed in the package.json of the master branch. Following a npm install from scratch I get following warnings:

    npm WARN ionic-angular@2.3.0 requires a peer of @angular/common@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler-cli@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/core@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/forms@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/http@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser-dynamic@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-server@2.4.8 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of rxjs@5.0.1 but none was installed.
    npm WARN ionic-angular@2.3.0 requires a peer of zone.js@0.7.2 but none was installed.

**Expected behavior:**
Should angular 4.0.0 / rxjs 5.1.1 / zone.js 0.8.4 be use? If yes, could you correct the dependencies of the published ionic-angular@2.3.0

Should angular 2.4.8 / rxjs 5.0.1 / zone.js 0.7.2? If yes, shouldn't the package.json of the master branch reflect these effective dependencies and not the above one?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by MTechDE** [comment]
The official iOnic releases run on Angular 2.4.8, not 2.3.0.
iOnic v3 will run on Angular 4.0.

**Comment by brandyscarney** [comment]
Thanks for the issue! You should follow what is in the master branch of `app-base`, as the master branch of `ionic` is constantly being updated: https://github.com/driftyco/ionic2-app-base/blob/master/package.json#L25

Or you can look at the package.json for the specific release tag in `ionic`: 

https://github.com/driftyco/ionic/tree/v2.3.0

https://github.com/driftyco/ionic/blob/v2.3.0/package.json

**Comment by peterpeterparker** [comment]
thx your @brandyscarney for making that clear!

p.s.: the tag 2.3.0 point to version v2.2.0 ... for example package.json from  https://github.com/driftyco/ionic/blob/v2.3.0/package.json display version 2.2.0

**Comment by brandyscarney** [comment]
@peterpeterparker Yeah it's because when we release a new version it releases the version to Github before it updates the package.json and publishes it to npm. It's an issue with our release task. It is still the correct code base though. :)
