### ISSUE TITLE
ionScroll events not firing on 2.3.0

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic#10938]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When adding an event binding for `ionScroll` on `ion-content` it is never fired.

**Expected behavior:**

The Content component should fire scroll events when scrolled.

**Steps to reproduce:**

The following will work on 2.2.0 but not 2.3.0:

```
<ion-content (ionScroll)="doSomething()">
```

doSomething is never fired on 2.3.0.

**Comment by konrin** [comment]
The same thing if you subscribe to an event from the code - the scrolling event does not fire!

`this.content.ionScroll.subscribe((ev: ScrollEvent) => {})`

**Comment by jjosef** [comment]
You need to call `this.content.enableScrollListener()` in the Component. Docs need update!

**Comment by peterpeterparker** [comment]
@jjosef mvp of the day, your solution works!

**Comment by jjosef** [comment]
My instincts tell me this is a bug more than anything. Not sure why this method would be required before the listener is enabled. I'm too busy at the moment to look into it and submit a PR, but this was a quick fix..

**Comment by brandyscarney** [comment]
It seems the code that was called in `ngOnInit` for content was moved to a function by this commit: https://github.com/driftyco/ionic/commit/7e9bad509255b642f6099366231ad86fe6eaddad#diff-848174518abef5659a16d7dc15e82a62R374


Adding the following in `content` fixes it:

```
ngOnInit() {
  this.enableScrollListener();
}
```

cc @manucorporat

**Comment by dmastag** [comment]
It is still not working for me on ionic3 using iOS

**Comment by dmastag** [comment]
Wanted to share that I Got some advise from North McCormick on Slack to use wkwebview for the ion-infinte problem and it is working as a temporary workaround for that issue.

Sadly it is not working for this scroll event issue on a new ionic app i crated from scratch to test this

**Comment by dmastag** [comment]
@manucorporat I tried this using iPhone SE with and without wkwebview on 2.3.0 and 3.0.0 and 3.1.1
and it is still not working

**Comment by peterpeterparker** [comment]
If I understand correctly, @dmastag it looks like @manucorporat fixed the scroll for UIWebView 2 days ago there https://github.com/driftyco/ionic/issues/10936

**Comment by dmastag** [comment]
@peterpeterparker yeahh but on my test it only worked for ion infinite, and the onScroll was still not working

**Comment by manucorporat** [comment]
@dmastag this is a known limitation of UIWebView, and it is been there forever, the only thing you can do is to enableJSScroll() conditionally, but native scrolling is much smoother.

The best chance if you depend on scrolling events is to start using WKWebView, in fact we have plans to deprecate UI very soon.

**Comment by shmulikmak** [comment]
Ionic does not know "enableScrollListener"  in  "this.content.enableScrollListener()"
he gave me error unkonw method/property..

**Comment by pawansingh123** [comment]
Still not working in ionic 3.9

**Comment by maheshj11** [comment]
get the child ref using @ViewChild('scroll') scroll: any;
and then use the addScrollEventListener() on scroll to get the scrolled position;
i you use inside the constructor and the event throws error or doesn't fire try using setTimeout:

    setTimeout(() => {
      this.scroll.addScrollEventListener((e) => {
        console.log(e)
      })
    }, 1000);

**Comment by aleksander351** [comment]
Try with something like this:

```
import { Renderer2 } from '@angular/core';
...
constructor(private renderer: Renderer2) {}

ngOnInit() {
    this.renderer.listen(this.specialComponent, 'scroll', (event) => {
        // Do something with 'event'
        console.log(this.specialComponent.scrollTop);
    });
}
```

**Comment by davidanaya** [comment]
So any idea if this is going to be fixed? I don't get any event fired when using ionScroll like
`<ion-content (ionScroll)="scrollHandler($handler)">`
