### ISSUE TITLE
Documentation for Tabs does not set type on tab roots -> tabs don't show up

### ISSUE THREAD

**Issue by marcusforsberg** [driftyco/ionic#10933]
**Ionic version:** 
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The documentation for the Tabs component (https://ionicframework.com/docs/v2/api/components/tabs/Tabs/#usage) does not set a type for the "tab roots". For me, when copying the example code as a base for my project (which was based on the blank template), this resulted in the tabs not showing up at all until I added `any` as the type.

**Expected behavior:**
Adding `any` as the type for the tab roots makes the tabs show up again. `any` is also included in the tabs starter template. If this is correct, it should probably be added to the example in the docs.

**Steps to reproduce:**
Just follow the usage example for tabs step-by-step: https://ionicframework.com/docs/v2/api/components/tabs/Tabs/#usage

**Related code:**

Specifically, it's this part of the docs, in `TabsPage`

```
 tab1Root = Page1;
 tab2Root = Page2;
 tab3Root = Page3;
```

This should include the type, `any` (?).

**Other information:**
I can go ahead and submit a PR but wanted to follow the contribution guidelines to the point and open an issue first :) Also wanted to double check that `any` is indeed the type to use here.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1030
