### ISSUE TITLE
ScrollToBottom doesn't work at all on ios

### ISSUE THREAD

**Issue by bonoadil** [driftyco/ionic#10936]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
scrollToBottom on Content not work anymore on ios, and works fine in brower & android.
i seems to be a regression. it's failed only in version 2.3.0  and works fine on 2.2.0

**Expected behavior:**
Should scroll to the bottom

**Steps to reproduce:**

https://github.com/bonoadil/blankDemo

**Comment by shanehughes3** [comment]
We're having this issue as well - the view moves up, then gets pulled back down. It also doesn't appear to be pulling up the correct distance: if you use the demo above and scroll on your own to just one line above the bottom, then hit the icon, the content pulls up much further than a single line.

I've tried:
- setting `-webkit-overflow-scrolling: auto;` to make sure it's not a problem with ios elastic/bouncy scrolling
- removing all transitions/animations on the page and delaying the scrollToBottom with a setTimeout
- calculating the scrolling myself using `getContentDimensions()` and `scrollTo()`

It's working perfectly on android... and not at all on ios.

**Comment by rbruflodt** [comment]
I'm having the same problem with ```scrollToTop()``` on ios. Works fine on Android and browser.

**Comment by ysgk** [comment]
Same problem.
I tried [wkwebview](https://github.com/driftyco/cordova-plugin-wkwebview-engine) as a test and it seems working.

**Comment by manucorporat** [comment]
I didn't notice it was a UIWebView only issue.

I am working in a good fix for UI right now. But in the meantime, what is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.

**Comment by nishantpant** [comment]
I don't understand all this. This is still ionic right? How are you guys choosing to use UIWebView vs WKWebView? That is ionics own implementation. As an ionic developer all we are doing is using ion-content.

**Comment by marcd123** [comment]
I'm still having this issue under the same implementations listed above.

On iOS, scrollToBottom() is in fact scrolling to the top of ion-content instead.

**Comment by s1lviu** [comment]
Same issue with `ionic (Ionic CLI) : 3.9.2` only on iOS.
On Android worked after I've added a 300 ms delay.

**Comment by murillobarata** [comment]
Same issue!
