### ISSUE TITLE
[V3] Content: scroll events not enabled

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic#10948]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.0.0-beta.3**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The `ionScroll`, `ionScrollStart`, and `ionScrollEnd` outputs of the `Content` component never emit.

**Expected behavior:**
These outputs should emit on scroll events.

**Steps to reproduce:**
Either on the template:
```html
<ion-content (ionScroll)="doSomething($event)"></ion-content>
```

Or inside a component that has Content:
```ts
// ...
@ViewChild(Content) content: Content;
// ...
this.content.ionScroll.subscribe(event => { /* do something */});
```

**Related code:**
It seems these 3 EventEmiters are not attached to the underlying ScrollView events, since `enableScrollListener()` is never called: https://github.com/driftyco/ionic/blob/63fd63e72e8cf44767ec8ca2d6ba0e6b9f071317/src/components/content/content.ts#L386-L418

If I manually enable it, then the scroll otuputs emit events as expected. But that shouldn't be necessary, considering I'm accessing `@hidden` methods and properties:
```ts
if (!this.content._scroll.enabled) {
  this.content.enableScrollListener();
}
```

**Other information:**

**Ionic info:**

```
  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.1
    Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Thanks for the detailed issue! It seems this was an issue in 2.3.0 also, duplicate of https://github.com/driftyco/ionic/issues/10948.

**Comment by jsayol** [comment]
Oops, sorry, should have checked. Closing this in favor of #10938.
