### ISSUE TITLE
ion-slides Cannot read property 'hasAttribute' of undefined

### ISSUE THREAD

**Issue by markisme** [driftyco/ionic#10940]
when use `*ngFor` ion-slides, get this error when start the page.
```
Uncaught TypeError: Cannot read property 'hasAttribute' of undefined
    at autoplay (swiper.js:175)
    at startAutoplay (swiper.js:218)
    at initSwiper (swiper.js:164)
    at Slides._initSlides (slides.js:851)
    at slides.js:517
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at Array.<anonymous> (page-transition.js:23)
    at IOSTransition.Animation._fireBeforeReadFunc (animation.js:800)
    at IOSTransition.Animation._beforeAnimation (animation.js:729)
```
And in swiper.ts ,I see that
https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper/swiper.ts#L206, did it's because the acitveindex is `undefined`,because when there no data in modal.the swiper is still no slide???
By the way , why the `ion-slides` remove the `options`, and use `this.slides.attributes=value` to modify some hidden options. The options of swiper is awsome, and use very well for us to custom the slides.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you provide a repo that we can use to reproduce this issue?

**Comment by kiencoltech** [comment]
<ion-slides autoplay=4000 loop class="home-slides">

**Comment by juntaforce** [comment]
Its completely same wtih @mhartington plunker.
http://plnkr.co/edit/PKatjkmFKxJBRxVKrD83
just different Im pushing the data to slides from firebase like that: 
`
posts: FirebaseListObservable<any>;
this.posts = this.af.database.list('/Posts'); 
`
`<ion-slides>
    <ion-slide *ngFor="let post of posts | async" autoplay="4000" loop=""true>
      <div>
      <img src="{{post.postpicurl}}" />
      
      <h2> 
        
      <p>{{post.title}}</p>
      </h2>
      </div>
    </ion-slide>
  </ion-slides>`
If we dont use autoplay option,  everything is fine. If we use, I getting above error

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/10830.

**Comment by sayanbrainium** [comment]
I have the solution:
Do like this

```
<ion-slides *ngIf="slideData && slideData.length" autoplay="5000" class="slideroption" pager="true"   loop="true" speed="300">
	  <ion-slide   *ngFor="let slide of slideData">
                <img src="{{slide.imag}}" />
          </ion-slide>
	</ion-slides>
```

**Comment by nikksan** [comment]
Thanks for the solution.
However the developers should definitely take a look at this case, it makes no sense that an empty array is illiterated.

**Comment by ShilpaPrajapati1992** [comment]
@sayanbrainium : It didn't worked for me.
please provide me working solution , I am using it in below way
 <ion-slides *ngIf="property.Lead_MediaInfo && property.Lead_MediaInfo.length" autoplay="5000" class="slideroption" pager="true" loop="true" speed="300">
                    <ion-slide *ngFor="let media of property.Lead_MediaInfo let i = index;trackBy: customTrackBy">
                        <img src="{{property.Lead_MediaInfo[i].Filepath}}" />
                    </ion-slide>
                </ion-slides>

**Comment by Gwardinski** [comment]
this is still broken, and these solutions do not work

**Comment by tala9999** [comment]
@sayanbrainium: Your solution helps.
