### ISSUE TITLE
cssClass alert button not working when upgrading v2.3.0

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#10942]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic serve failed
**Expected behavior:**

It should work like v2.2.0
**Steps to reproduce:**

**Related code:**

```
let confirm = this.alertController.create({
            title: 'title',
            message: "message",
            cssClass: "confirmationSignout",
            buttons: [
                {
                    text: this.translateService.instant("menu.signout_cancel"),
                    cssClass: 'btnCancel',
                    role: 'cancel',
                    handler: () => {
                    }
                },
                {
                    text: this.translateService.instant("menu.signout_confirm"),
                    //cssClass: 'btnYes',
                    handler: () => {
                        this.ngRedux.dispatch(this.authActions.signOut());
                    }
                }
            ]
        });
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed
```
Typescript Error
Argument of type '{ title: string; message: string; cssClass: string; buttons: ({ text: any; cssClass: string; role...' is not assignable to parameter of type 'AlertOptions'. Types of property 'buttons' are incompatible. Type '({ text: any; cssClass: string; role: string; handler: () => void; } | { text: any; cssClass: str...' is not assignable to type '(string | AlertButton)[]'. Type '{ text: any; cssClass: string; role: string; handler: () => void; } | { text: any; cssClass: stri...' is not assignable to type 'string | AlertButton'. Type '{ text: any; cssClass: string; role: string; handler: () => void; }' is not assignable to type 'string | AlertButton'. Object literal may only specify known properties, and 'cssClass' does not exist in type 'string | AlertButton'.
```

**Comment by bea91** [comment]
save issue here

**Comment by h2qutc** [comment]
I just fixed like: 

       let btnCancel = {
            text: this.translateService.instant("menu.signout_cancel"),
            cssClass: 'btnCancel',
            role: 'cancel',
            handler: () => {
            }
        }
        let btnOk = {
            text: this.translateService.instant("menu.signout_confirm"),
            cssClass: 'btnYes',
            handler: () => {
                this.ngRedux.dispatch(this.authActions.signOut());
            }

        }
        let confirm = this.alertController.create({
            title: 'title',
            message: "message",
            cssClass: "confirmationSignout",
            buttons: [
                btnCancel,
                btnOk
            ]
        });`

**Comment by bea91** [comment]
@h2qutc thank you!! Works great!!
