### ISSUE TITLE
Split pane combined condition for screens size and boolean

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#10949]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an observable in my `accountService` called `isAuthenticated$`. The sidemenu contains options only available when the user is logged in.

Currently it is only possible to add a boolean on the when:

`<ion-split-pane [when]="account.isAuthenticated$ | async">`

However this results in showing the sidemenu even when the user is on a small screen.

`<ion-split-pane when="lg">`

Also works but then I miss the authenticated check.

**Expected behavior:**
A combination of screen size and using a boolean value

**Comment by jgw96** [comment]
Hello @basvdijk , what value does your `account.isAuthenticated$` observable emit? Is it a boolean value?

**Comment by basvdijk** [comment]
@jgw96 Yes it is a boolean

**Comment by basvdijk** [comment]
Great it is fixed but what will be the correct syntax? Will it be:

`<ion-split-pane [when]="account.isAuthenticated$ | async" when="lg">`

**Comment by elbidone** [comment]
Hi @basvdijk, I have the same issue which syntax do you use to combine boolean and screen size ?

**Comment by basvdijk** [comment]
@elbidone `<ion-split-pane [when]="account.isAuthenticated$ | async" when="lg">` seems to work now

**Comment by elbidone** [comment]
thanks @basvdijk

**Comment by lolaswift** [comment]
@basvdijk this isn't working for me when used together.
