### ISSUE TITLE
ionic serve fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by knesebeck** [driftyco/ionic#10943]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When creating a new Ionic 2 project with ionic start myApp --v2 and starting it with ionic serve, the following messages appear:
```
> ionic-hello-world@ ionic:serve /home/user/ionic//myApp
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
```
but no browser is opened, and no server is listening on port 8100.

**Expected behavior:**
browser opens and serves the ionic 2 app from localhost:8100

**Steps to reproduce:**
```
ionic start myApp --v2
ionic serve
```
**Other information:**
When manually calling:
```
node node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js serve "--v2" "--address" "0.0.0.0" "--port" "8100"
```
the app is served at localhost:8100 as desired

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v7.6.0
Xcode version: Not installed
```
**npm ls:** (only errors shown)
```
UNMET PEER DEPENDENCY typescript@2.0.9
```

**Comment by krlwlfrt** [comment]
I'm having the same problem on my system:

```
$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v7.7.4
Xcode version: Not installed
```

**Comment by iget-master** [comment]
I'm having the same issue here.

Just installed Ionic as described on the docs.

Your system information:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.1
Xcode version: Not installed
```
Running on Ubuntu 16.04, with nginx running on port 80.

**Comment by JuanELo-O** [comment]
Hi all!

I'm having same issue but a feel a little better (I was beginning to think that I was the only one).

My system information.

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.1
Xcode version: Not installed
```

By the way, I'm in ubuntu too:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

The workaround works for me too.

Thanks @knesebeck

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2045

**Comment by EnzzoPerez** [comment]
Hi!,I add to the issue:

My system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.10.0
Xcode version: Not installed

I working in ubuntu 16.04.. Thanks!

**Comment by GabrielAmazonas** [comment]
Same problem with Ubuntu 16.04:

Here's the ionic info command:



> Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
> 6.5.0
> 
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 4.8
> Node Version: v7.6.0
> Xcode version: Not installed

**Comment by DominikTrenz** [comment]
The issue was source-map for me. It's happening if you define more than one htmlTemplate per .ts file. 
app scripts had a error it didn't print out.
https://github.com/mozilla/source-map/pull/257

Maybe this helps (fixes the bug in source-map):
 npm install https://github.com/mozilla/source-map/tarball/eb1a675a397cc4752358bec7e84e8e81d7798ac4 --save-dev
