### ISSUE TITLE
Ionic Server not starting after running "ionic serve" on a brand new project

### ISSUE THREAD

**Issue by LuanGB** [driftyco/ionic#10955]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After creating a new project via `ionic start <app name> --v2`, and then `cd <app name>`, running `ionic serve` don't start the server, nor open the browser, and any tries to access directly from the browser `localhost:8100` are unsuccessful. 
After running `ionic serve`, the only output is:
 ```
> ionic-hello-world@ ionic:serve /home/luan/Projetos/prestacontas
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
```

**Expected behavior:**
after running `ionic serve`, the browser should open with the home page of the project. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

My system information:
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.0
Xcode version: Not installed

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#2046
