### ISSUE TITLE
DateTime - property minutesValues doesn't work

### ISSUE THREAD

**Issue by giorgiopiatti** [driftyco/ionic#10954]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using the DateTime component and passing to the minutesValues property a string of comma separated numbers or an array of numbers, I can't choose from them. It shows all the minutes.

**Expected behavior:**

I expected that I can only choose from the given minutes.

**Steps to reproduce:**

**Related code:**

```
Case 1
<ion-datetime displayFormat="mm" minutesValues="0,5,10,15,25,30" [(ngModel)]="data.pauseTime"></ion-datetime>

Case 2
<ion-datetime displayFormat="mm" minutesValues="minutes" [(ngModel)]="data.pauseTime"></ion-datetime>

export class Page{
public minutes = [0,5,10,15];
....
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce the problem with the first example:

```
<ion-datetime displayFormat="mm" minutesValues="0,5,10,15,25,30" [(ngModel)]="data.pauseTime"></ion-datetime>
```

And on the second example, you should be wrapping `minutesValues` in brackets like this:

```
<ion-datetime displayFormat="mm" [minutesValues]="minutes" [(ngModel)]="data.pauseTime"></ion-datetime>
```

Does this solve your issue? More on property binding here: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding

**Comment by giorgiopiatti** [comment]
Thanks for the answer. Issue solve, I was using minutesValues and not minuteValues. The suggested doc on property binding was really helpful.

**Comment by brandyscarney** [comment]
@giorgiopiatti Ahh I missed that! I modified one of our existing examples like this:

```
<ion-datetime displayFormat="h:mm A" minuteValues="0,15,30,45"></ion-datetime>
```

🙂
