### ISSUE TITLE
Add an option for setRoot() to persist the page rather than load it from scratch.

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#10967]
**Ionic version:**  
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  
[ ] bug report
[x ] feature request
[ ] support request 

**Current behavior:**
Currently, when you perform setRoot on a page, it sets the page you specify as the root of the nav stack, and also loads the page from scratch.

This creates a sometimes unwanted effect with side menu tabs, as you may not necessarily want to reload the page each time. 

For example, in my application, one of the pages in the side menu has a Google Maps view along with content that should persist despite pages changing. This is bad because each time a user navigates to a different tab and comes back to the map tab, the map is reloaded. 

The desired behavior is that akin to the Ionic Tabs starter, where the page is not freshly loaded each time the tab is switched.

If this is already possible with another method and I am just unaware, I do apologize. Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#141
