### ISSUE TITLE
Split personality Split Pane

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic#10968]
_From @snortblt on March 20, 2017 20:44_

**Feature Request**

I love the new split pane component, guys! And I'm super glad to hear you're pursuing more desktop-related features. It's not always fun trying to make Ionic play nicely there as it stands.

I'm guessing you guys may have thought of something like this, but what I've really wanted for a hybrid desktop/mobile app span the desktop and mobile worlds is a master/detail a la split pane, but on a phone it would behave like two different pages in a nav hierarchy. In virtually any case where I have some kind of simultaneous master detail thing going on for a larger display, I'm not simply going to want to hide the master column on a smaller display--I'm going to want to show it as its own page where selecting an item now navigates to the detail page (and of course the drill-down chevrons would automatically show up and hide as appropriate for the platform). 

I'm actually going to try to hack this together myself, but since it seems kind of an obvious common pattern, it would certainly make a great framework component if you can work out the navigation kinks in a generic way.

Keep these things coming! Great stuff!

_Copied from original issue: driftyco/ionic-cli#2014_

**Comment by jthoms1** [comment]
_From @mburger81 on March 22, 2017 13:35_

@snortblt I think you should close this thread and open it on https://github.com/driftyco/ionic
the cli doesn't matter with your feature request.

**Comment by snortblt** [comment]
Thanks for moving this @jthoms1. My bad.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#147

**Comment by snortblt** [comment]
Thanks, but moved to where? I'm getting a 404 at that link.

**Comment by aggarwalankush** [comment]
@snortblt ionic team is maintaining an internal feature requests repo, it's not exposed to public 😞

**Comment by mburger81** [comment]
Yes but butting this in a private internal feature requests where we can not see anything,
We even not know if the team has decide to not implement it at all. So we know nothing and are not up to date with the status of the issue or even on which issues they already have discussed, declined, accepted or else.

So also there will be many duplicate requests.
