### ISSUE TITLE
ScrollToTop() doesn't work on ios

### ISSUE THREAD

**Issue by rbruflodt** [driftyco/ionic#10966]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Calling scrollToTop() on a content component woks fine in Android and in the browser but does nothing to ios.

**Expected behavior:**

Calling scrollToTop() should scroll the content to the top.

**Steps to reproduce:**

Reference a content element and call scrollToTop(). View on ios device or simulator.

**Other information:**

I'm aware of this issue https://github.com/driftyco/ionic/issues/6975 but that solution did not work for me.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI 6.3.1
Ionic Framework Version: 2.3.0
Ionic CLI version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.21 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is most likely related to a scroll events issue in 2.3.0. @manucorporat does that sound correct to you?

**Comment by rbruflodt** [comment]
Probably it's related to https://github.com/driftyco/ionic/issues/10936

**Comment by manucorporat** [comment]
I didn't notice it was a UIWebView only issue.

I am working in a good fix for UI right now. But in the meantime, what is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.
