### ISSUE TITLE
videoplayer inside ionic content is not working in android

### ISSUE THREAD

**Issue by karthikavnair** [driftyco/ionic#10973]
I have added used the following code for play video inside ionic content. but the result is not found. video can't play.

```
  <ion-content overflow-scroll="true">
<div>
    <video controls="controls" preload="metadata" autoplay="autoplay" webkit-playsinline="webkit-playsinline" class="videoPlayer">
<source src="http://player.vimeo.com/external/85569724.sd.mp4?s=43df5df0d733011263687d20a47557e4" type="video/mp4"/>
</video>
</div>
  </ion-content>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
