### ISSUE TITLE
Infinite scroll doesn't work on iOS

### ISSUE THREAD

**Issue by tscislo-lingaro** [driftyco/ionic#10976]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.3.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Infinitivie scroll doesn't work on iOS.
It worked on 2.0.1

**Expected behavior:**
It should work as expected on iOS

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.5
Xcode version: Not installed

**Comment by tscislo-lingaro** [comment]
It works well on 2.2.0, it's only failing on 2.3.0

**Comment by burhanyldz** [comment]
"A is B. A should be A." 

This is how it sounds. I believe you should provide more explanation :)

**Comment by tscislo-lingaro** [comment]
I suspect that (ionInfinite) output is not emitted when it should. I didn't spend much time debugging just launched on iOS with 2.2.0 and it works while on 2.3.0 with the same code it doesn't.

**Comment by burhanyldz** [comment]
Your issue might be related with [this](https://github.com/driftyco/ionic/issues/10889)

I had the same issue and downgraded to 2.2.0. In my case ionInfinite was actually being triggered but content was positioned incorrectly so I saw a blank page. Applying below CSS fixed it. I don't know if it is the same problem for you though.

```
    .scroll-content {
        transform: none !important;
    }
```

**Comment by tscislo-lingaro** [comment]
It's not the same problem, however the issue which you mentioned is exactly what I'm experiencing. Currently downgrading to 2.2.0 solves the issue.

**Comment by shinta5150** [comment]
Also experiencing this issue. 👍

**Comment by vzharkov** [comment]
I have the save issue on ionic 2.3.0, v 2.2.0 works good

**Comment by nvazquezg** [comment]
Same problem here.

**Comment by dmastag** [comment]
Got some advise from North McCormick on Slack to use wkwebview
https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions

And can confirm that its working as a temporary workaround

**Comment by HonLuk** [comment]
same problem. ionic3.0 and 2.3 work on chrome but not work on ios device.(I build by add prod)
2.3 and 3.0 have this problem.so I just update to 3.0 the problem still make page block when I try to scroll page, so i back to 2.2 now. sad day.

**Comment by danielabbatt** [comment]
Yes - this currently blocks from upgrading to 3.x for us.

**Comment by manucorporat** [comment]
I didn't notice it was a UIWebView only issue.

I am working in a good fix for UI right now. But in the meantime, what is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.

**Comment by m00g33k** [comment]
Still having this issue in 3.0.1

**Comment by tscislo-lingaro** [comment]
Can people confirm if it's working on 3.0.1?

**Comment by BeliliFahem** [comment]
Resolved for me with 3.0.1 !

**Comment by joel00** [comment]
mmmm weird, with 3.0.1 works only once on device while in web works fine

**Comment by dicoluat** [comment]
Try:
`<ion-infinite-scroll [threshold]="'500%'"(ionInfinite)="doInfinite($event)"></ion-infinite-scroll>`
It works for me
