### ISSUE TITLE
Feature Request, Separate DateTime from picker

### ISSUE THREAD

**Issue by smurfy** [driftyco/ionic#10982]
**Ionic version:** 
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...** 
[ ] bug report
[x ] feature request
[ ] support request

**Current behaviour:**
ion-datatime always shown in a picker

**Expected behavior:**
I would like a separation of the great component to actually select a datetime and the picker dialog behaviour. 
For example i can display the native ios datetime picker inline anywhere i like.  This would be great for ionic2 too.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#142
