### ISSUE TITLE
bug(ion-datetime): control is not populating on load from a set model

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#10987]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Setting the model on `ionViewDidLoad` (or constructor) should bind the control to the value. It does so for some cases, but not all.

**Expected behavior:**
Setting the model should bind the user interface control to the correct value.

**Related code:**

This works:
```
 bookingTime: string = moment().format("HH:mm");

<ion-datetime displayFormat="HH:mm" [(ngModel)]="bookingTime"></ion-datetime>
```

I would then expect this to work as well, but it doesn't:
```
 bookingDate: string = moment().format("DD/MM/YYYY");

<ion-datetime displayFormat="DD/MM/YYYY" [(ngModel)]="bookingDate"></ion-datetime>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by manucorporat** [comment]
Can you provide an example without moment() that reproduce this issue?

**Comment by dylanvdmerwe** [comment]
```
 bookingDate: string = "25/02/2017"; 

<ion-datetime displayFormat="DD/MM/YYYY" [(ngModel)]="bookingDate"></ion-datetime>
```

**Comment by dylanvdmerwe** [comment]
This works:
```
bookingTime: string = moment().toISOString();

<ion-datetime displayFormat="HH:mm" [(ngModel)]="bookingTime"></ion-datetime>
```
