### ISSUE TITLE
InfiniteScroll Option to choose its parent scrolls and not window

### ISSUE THREAD

**Issue by zodiark23** [driftyco/ionic#10996]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I would like to know if this feature is already implemented on the current release. Because It would be good if we could have a control on which container it will base rather than the `ion-content` only. 

Thanks for building amazing framework.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#144
