### ISSUE TITLE
in app.component.ts，I wan to get the current acitvity page,and reload the page.

### ISSUE THREAD

**Issue by huangzk** [driftyco/ionic#10993]
let activeVC = this.nav.getActive();
           let tabs = activeVC.instance.tabs;
           let activeNav = tabs.getSelected(); 
           activeNav.getActive();//current page.
 
           How to do to reload the page?

**Comment by huangzk** [comment]
eg:the somePage belongs tabs ,get the active page and reload it  in app.componnent.ts

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
