### ISSUE TITLE
ionic2 - bug(toast, tabs) - Toast displayed on a tabs page displays on top of the tabs

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#10992]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Toasts are displayed on top of the tabs 

**Expected behavior:**
On android apps, the native behavior is to show the toast above the tabs.

![20a25b8c-a1ad-11e6-8120-bbb70b1d90fd](https://cloud.githubusercontent.com/assets/3453385/24531500/d0c802a4-1576-11e7-9260-df011064fdc4.png)

**Steps to reproduce:**

1. Create a tabs page
2. Display a toast
3. Observe that it is displayed on top of the tabs

**Other information:**
Yo can take a look to the official photos app from Google. https://play.google.com/store/apps/details?id=com.google.android.apps.photos&hl=es

**Comment by jgw96** [comment]
Hello e! Thanks for opening an issue with us. I am going to make this a feature request and move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by MvRemmerden** [comment]
Any information regarding whether we could expect this in the next couple of weeks or whether we should build it ourselves?

**Comment by maumchaves** [comment]
So far, what you can easily do is to add the following styles in your `global.scss` file:

```
.md {
  .toast-tabs {
    height: calc(100% - #{$tabs-md-tab-min-height});
  }
}
```

And then add the `toast-tabs` class when you are creating your toast.

**Note:** this example only works in Android and Web, you have to add the corresponding styles fo each platform you are developing for.
