### ISSUE TITLE
Ionic3: Does not find the provider after assembly with the flag "--prod"

### ISSUE THREAD

**Issue by konrin** [driftyco/ionic#11001]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x]**3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After assembling and running the application in production mode on the device, an error is thrown about not finding a provider. In the development mode, there is no such problem. All pages of the application I switched to lazy loading mode. All components and pipes have their own module, which is connected as necessary to the page modules. Application providers are imported only to the main module.

<img width="250" alt="2017-03-31 15 51 24" src="https://cloud.githubusercontent.com/assets/854677/24552751/59a90a6e-1630-11e7-8dda-b569b9678b09.png">

**Expected behavior:**
Correct application startup

**Steps to reproduce:**

> ionic cordova:run android --prod

**Related code:**

> app.module.ts
```
@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpModule,
    IonicModule.forRoot(MyApp, {}),
    NavigationMenuComponentModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    services,
    NATIVE_PLUGIN_PROVIDERS,
    { provide: ErrorHandler, useClass: IonicErrorHandler }
  ]
})
export class AppModule { }
```

> components.module.ts
```
@NgModule({
    declarations: [
        components_list
    ],
    entryComponents: [
        /** entryComponents **/
    ],
    exports: [
        components_list
    ],
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        PipesModule,
        BadgeModule,
        ItemModule,
        IconModule,
        ButtonModule,
        CardModule,
        ListModule,
        BackdropModule,
        GridModule,
        LabelModule,
        AvatarModule,
        CheckboxModule,
        InputModule,
        ThumbnailModule
    ]
})
export class ComponentsModule { }
```
> pipes.module.ts
```
@NgModule({
    declarations: [
        pipes_list
    ],
    exports: [
        pipes_list
    ]
})
export class PipesModule { }
```

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0-beta.3
Ionic CLI Version: 3.0.0-beta.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.7.2
Xcode version: Xcode 8.2.1
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you be able to share a repo to your app? Id love to take a look at it myself. Also, could you look at [this branch of the conf app](https://github.com/driftyco/ionic-conference-app/tree/lazy-load). That is our ionic 3 branch of the conf app with lazy loading set up and may be a good example for you.

**Comment by konrin** [comment]
Yes, before moving the project to version 3, I was guided by [this repo](https://github.com/driftyco/ionic-conference-app/tree/lazy-load) and [this document](https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit#). As I mentioned above in the development mode it works without errors, the error is only displayed at the start in the device. It seems to me that the error is thrown after the "ngc" compilation. Unfortunately, the repository is private. I can only provide sections of code. Any ideas?

**Comment by konrin** [comment]
Is it possible to disable compression after ngc in the production assembly as a way to get a readable stack of errors?

**Comment by jgw96** [comment]
Got ya. So one question, are you using this provider from a component or a page? 

```
Is it possible to disable compression after ngc in the production assembly as a way to get a readable stack of errors? 
```
Not that we are aware of at the moment

**Comment by Manduro** [comment]
@konrin I have a similar application structure and get the same error only on production builds. You can pass a custom uglify config to app-scripts to find out what `t` really is:

```js
module.exports = {
  mangle: false,
  compress: false,
  comments: false
};
```

For me it's one of my custom services. No joy trying to fix it so far though.

**Comment by konrin** [comment]
I found the issue with the provider in your case! This was due to the fact that aot is incorrect processed connection providers.

> Broken connection

```
let providers = [
    /** providers list **/
]

if(ENV_NAME.indexOf('dev') > -1) {
    providers.push(Firebase);
} else {
    providers.push({ provide: Firebase, useClass: FirebaseMock })
}
```

In development mode it works but not after aot

**Comment by jgw96** [comment]
Hello @konrin , are you still having this issue?

**Comment by konrin** [comment]
No, I decided it, thank you.

**Comment by jgw96** [comment]
No problem!
