### ISSUE TITLE
Form: Ion-input type password error/bug

### ISSUE THREAD

**Issue by Yoloi** [driftyco/ionic#11004]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello, I have a form like this:
```
<ion-content padding>
  <form>
    <ion-list>
      <ion-item>
        <ion-label floating>Email</ion-label>
        <ion-input type="email" [(ngModel)]="email" name="email" required></ion-input>
      </ion-item>
      <ion-item>
        <ion-label floating>Password</ion-label>
        <ion-input type="password" [(ngModel)]="password" name="password" required></ion-input>
      </ion-item>
      <ion-item>
      <button ion-button block (click)="loginUser()">Log in</button>
      </ion-item>
    </ion-list>
  </form>
</ion-content>
```
When you run this on a browser anything you type in the input type password is automatically masked by dots.
When you run it on a device (only tested on Android), when you type a password it takes a few seconds to mask the characters (I understand this is for UX reasons). 
The problem comes when I type my password and before the character is masked I click Log in. It will throw an error, like the password is incorrect.
If I wait for the character to get masked the log in is succesfull.

**Expected behavior:**
I would expect the character to mask onsubmit by default.
Or to pass the whole password even if the last character is not masked.

**Other information:**
I am using Firebase as a Backend.
Log in is successful at the second log in.
First log in throws error: A network error (such as timeout, interrupted connection or unreacheable host) has occurred.

Thanks!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Could you share a repo that we could use to reproduce this issue?

**Comment by Yoloi** [comment]
It seems it has nothing to do with the password input field.
Its more of a AngularFire2 / Firebase issue.

Thanks anyways!

**Comment by jgw96** [comment]
No problem! I am going to close this issue for now.
