### ISSUE TITLE
ionic framework(v1) app not support in android 7

### ISSUE THREAD

**Issue by Bala893** [driftyco/ionic#11000]
My app is working in marshmallows but I try to install the app in nougat android version(7) it displayed the 504 error message after downloading is completed from google play store could you please help for me asap?

Please find the screenshot below

![2017-03-31_1914](https://cloud.githubusercontent.com/assets/22056977/24552960/2048e1e8-1646-11e7-892b-85b0f49c176d.png)

![screenshot_20170331-181207](https://cloud.githubusercontent.com/assets/22056977/24552940/0d744a3a-1646-11e7-9f31-3f984de0697b.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue. I tried installing https://play.google.com/store/apps/details?id=com.pacificalabs.pacifica&hl=en, which is an Ionic app on my Nexus 6 running Android 7.1.1 and its working fine. Its possible that you are using a cordova plugin that is not supported on Android 7.1.1 or simply an issue with that phone. If you google `Google play error 504`, that error usually means you have a network issue with your phone, or an issue with your google account.

**Comment by Bala893** [comment]
The following plugins only am using in my mobile app but am still facing the same issue
cordova-plugin-console
cordova-plugin-device
cordova-plugin-inappbrowser
cordova-plugin-splashscreen
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-plugin-x-toast
ionic-plugin-keyboard

I have google and try to resolve the 504 error 
i have tried the below methods but nothing happened :(

Method 1:

- Go to Settings>> Application Manager or Apps>> Open “All” apps
- From the list of apps find Google Play store >>Clear Data and Clear Cache
- From the list of apps find Google Service Framework >> Clear Data and Clear Cache
- Restart your mobile phone
- Now install or update app from Google Play Store

Method 2:

- Go to system settings>> Accounts>>Google>>remove your Gmail account
- Now from settings>>Apps>>All> Force stop, Clear data and cache for Google Play Store, Google Service Framework and Download Manager (like in method 1)
- Restart your android 
- Now again go to settings>> Accounts>>Google>>Add your gmail account
- Then accept all the Google terms and setup Google settings
- Rerun Google Play Store and update or install your app.

**Comment by rishiankush** [comment]
Is your problem resolved because I have the same issue?

**Comment by sahayarex** [comment]
I am having the same issue with ionic 2 and ionic 3 app as well. It doesnt support android 7

**Comment by Bala893** [comment]
@rishiankush The above issue was fixed for me
Reason for issue for me : i have built apk file and zip align the apk then upload in play store but that app not support in android 7 and finally i have done updated my android studio as well sdk version in my machine then take build my app without zipalign  i directly upload in play store and it works for me 👍

**Comment by Bala893** [comment]
@sahayarex sorry i am using the v1 👎

**Comment by chiluhimanshu2221** [comment]
Even the basic starter app is not working on android 7 but working fine in android 6
