### ISSUE TITLE
Editing CSS in Chrome Inspector extremely slow / 100% cpu

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#11010]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**Chrome version:**
OSX Version 59.0.3059.0 (Official Build) canary (64-bit)

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When editing css in the Chrome Inspector, cpu goes to 100% and makes the inspector unresponsive. Might be caused by the huge amount of css lines (over 64.000) in main.css when running with `ionic serve`:

![image](https://cloud.githubusercontent.com/assets/644550/24580229/d7d72f36-1704-11e7-8dd5-bbd2a3e25581.png)

As far as I remember this wasn't a problem in the Betas' of Ionic2

**Expected behavior:**
Without the Chrome inspector being responsive it isn't possible to check css changes. Edit and save a scss file takes a huge amount of time when fine tuning a design.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I cannot reproduce this issue in the current stable version of chrome (chrome 57) so it looks to be a chrome bug (which is not surprising in a canary build of chrome which is inherently unstable). I would recommend opening up an issue on the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by Baadier-Sydow** [comment]
I know this is closed but I seem to have this issue off and on too. Even changing the values in one of the inspector fields takes a few seconds before the change is registered.

**Comment by romain10009** [comment]
Hello, I have the same issue, editing css is very slugish.

**Comment by brentrichison** [comment]
It's still an on again, off again problem in mid-2018.
