### ISSUE TITLE
Dynamic addition of ion-card in ion-header does not refresh view

### ISSUE THREAD

**Issue by delian7** [driftyco/ionic#11012]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.3.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

* Ion-Cards in ion-header that are dynamically added (in the plunker example after 2 seconds) do not refresh the view and instead overlap the ion-content. See plunker # 1. 
* Also if they are dynamically removed they will have header overlap. See plunker # 2. 

**Expected behavior:**

Both of the examples should refresh the view appropriately. 

**Steps to reproduce:**

1. Create 2 cards in ion-header & create 2 cards in ion-content. 
2. Dynamically set the top card in ion-header to be removed (display:none) (after 2 second timeout).
* See Plunker # 1: http://plnkr.co/edit/w3HEP4NrXuLYrO9XiqyI?p=preview

1. Create 2 cards in ion-header & create 2 cards in ion-content. 
2. Dynamically set the top card in ion-header to be added (after 2 second timeout).
* Plunker # 2: http://plnkr.co/edit/Opq2GHTihYs9QsItmTy6?p=preview

**Demo Gif**
![dynamically-added](https://cloud.githubusercontent.com/assets/4530694/24583475/1bab2af0-1700-11e7-83fd-bf6a4ae2554c.gif)

**Comment by delian7** [comment]
It's worth pointing out that this only happens in the header. If I dynamically add a card in ion-content the view is refreshed: http://plnkr.co/edit/Wwwh8C6OFieJmGp9yMB3?p=preview

**Comment by manucorporat** [comment]
http://ionicframework.com/docs/api/components/content/Content/#resize

```
content.resize()
```

should be called once the size of the header changes dynamically.
