### ISSUE TITLE
ion-scroll not working on grid

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#11013]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have ion-scroll with scrollX="true" and containing ion-row. I upgraded from ionic 2.0.0-rc5 to 2.3.0 and scroll stopped working.

**Expected behavior:**
ScrollX should work, something is broken in newer release

**Steps to reproduce:**

**Related code:**

```
  <ion-scroll scrollX="true" class="center scroll-hourly"
              *ngIf="hourlyArray?.length>1">
    <ion-row>
      <ion-col col-2 *ngFor="let item of hourlyArray">
        <img [src]="utilService.getWeatherIcon(item.icon)"
             onerror="this.src='assets/img/default.png'" style="max-width: 40%">
        <p class="bold" ion-text color="text2" no-margin no-padding>
          <span ion-text color="text1">
            {{utilService.formatTemp(item.temperature,metrics)}}
          </span>
          {{utilService.getTime(item.time,metrics,forecast.timezone)}}
        </p>
      </ion-col>
    </ion-row>
  </ion-scroll>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.5
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by theunreal** [comment]
try add `nowrap` to the row

**Comment by aggarwalankush** [comment]
@theunreal thanks it worked.

**Comment by donganhhanoi1110** [comment]
Thanks both. It works for me with "nowrap"
