### ISSUE TITLE
Ion-badge with item-top, item-bottom directives

### ISSUE THREAD

**Issue by godzsa** [driftyco/ionic#11011]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request

Add item-top, item-bottom to ion-badge. If I use ion-range with badges on the left and right, the range selector gets really small. It would be much better to have the opportunity to use e.g item-top and item-right to make the badge appear over the range on one side.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
