### ISSUE TITLE
Unable to install ionic v1.x

### ISSUE THREAD

**Issue by dguzman1012** [driftyco/ionic#11019]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I try to download ionic but it hangs
![image](https://cloud.githubusercontent.com/assets/5767551/24590531/9ddfaf02-17bc-11e7-93dc-10a00bddfae7.png)

Also i tried with a specific version but it shows me this:
![image](https://cloud.githubusercontent.com/assets/5767551/24590818/e5dd471a-17c1-11e7-9f69-eeb4f0d69645.png)

What could it be?
This is my current Env:
![image](https://cloud.githubusercontent.com/assets/5767551/24590840/598f3d3a-17c2-11e7-9635-f06c0f3a1751.png)

Thanks in advance!

**Comment by dguzman1012** [comment]
BTW: i installed cordova successfully!

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#2060
