### ISSUE TITLE
Map mouse wheel/scrolling events to hammer for desktop

### ISSUE THREAD

**Issue by NorthMcCormick** [driftyco/ionic#11018]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ✔] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ✔] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
So far all the components I've tried (slides, pickers, side menu, etc) do not work with mouse scroll. You must click and drag to get the desired behavior. 

**Expected behavior:**
On slides, for example, I should be able to scroll on my trackpad (or mouse scroll wheel if it has horizontal scroll) and have it pull the slides over.

On the picker, for example, I should be able to scroll up and down and have the lists respond to that.

On a list with swipe-able items one on desktop should be able to use their trackpad to quickly swipe through them.

**Steps to reproduce:**

1. Create a new Ionic 2.x app
2. Add any component that responds to touch/drag
3. Attempt to use scroll instead of touch/drag and it will not do anything

Perfect demo from Ionic haha: https://pwa.ionic.io/ionic-conference-app/www/

**Related code:** 
N/A

**Other information:**

I did some research on this to see what was out there, since Ionic uses Hammer. It doesn't look like the Hammer lib officially support scroll events since it's a touch library but there are resources out there with people binding mouse wheel events to the swipe handlers.

Desktop apps have seem to become somewhat of a priority for Ionic 2.x and this is really a huge piece missing in the puzzle to that. Being able to navigate and use these components on desktop is, for me, a requirement before I can deploy an actual desktop app using Ionic.

**Ionic info:**
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3 Build version 8E162

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#145

**Comment by NorthMcCormick** [comment]
Sounds great, thank you!!

**Comment by cogoo** [comment]
Where can we track this issue?
