### ISSUE TITLE
Request feature for infinite scroll : paging

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#11028]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.3.0+**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When we use infinite-scroll on bottom and on top (since 2.3.0), we load and load and load data over scroll. If we scroll a very lot amount of data, screen start to be slow.

**Expected behavior:**

I'd like to set a number of page visible. Every time a scroll to bottom, it will load next data. And increment a page number. When the page number reach the max visible, the first is unload.
Same job when we go to top, but page number decreased, and biggest page unload.
In facts, actually I do this, but my problem is linked to the scrollposition that I should compute for scroll at the right place when I unload a part of the data.
Any other idea to manage simply the scroll of the view is welcom.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#146
