### ISSUE TITLE
IOS list scroll too sensitive

### ISSUE THREAD

**Issue by bolivir** [driftyco/ionic#11025]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Scroll is too sensitive that it will click list element when scrolling a list. I only notice this on IOS, on android its working as expected.

**Expected behavior:**
Element should not be clicked when scrolling a list.

**Steps to reproduce:**
Create a list with enough items to scroll, then scroll the list a couple of times and it will click a element.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ioni App Scripts Version: 1.1.4
OS: macOS Sierra
Node Version: v6.9.5

**Comment by manucorporat** [comment]
This was fixed in 3.0
