### ISSUE TITLE
`devicemotion` event is deprecated

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11030]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running on device, for debug, it warns:

> The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Expected behavior:**
Future-proofing it now, so the deprecation won't effect current version

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We are definitely aware of issues such as this and are actively discussing modifying our `app-scripts` to use https. I am going to keep this issue open for the moment and may modify it and move it to the app-scripts repo as an issue to get app-scripts using https.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. I am going to close this for now as it is more of an build issue and the app-scripts and cli team are both aware of this.
