### ISSUE TITLE
Remove # from DeepLinker generated URL

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#11036]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
A number sign (#) is added inside the URL when using [DeepLinker](http://ionicframework.com/docs/api/navigation/DeepLinker/). This sign shouldn't be in URL, and make it harder for search engines to index the current page.
Example of URL: `http://localhost:8100/#/my-page`

**Expected behavior:**
The page URL shouldn't include number sign
`http://localhost:8100/my-page`

**Steps to reproduce:**
Irrelevant

**Related code:**
```
{links: [
        { component: MyPage, name: 'My Page', segment: 'my-page' },
      ]}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
C ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by rapropos** [comment]
[Config.locationStrategy](http://ionicframework.com/docs/api/config/Config/) looks relevant.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. By default we use the hashbang style of URL's (kinda like the old angularjs router, but you can use the config @rapropos posted about to change that. Thanks @rapropos !

**Comment by kotran88** [comment]
what should i do with locationStrategy? I can't find any on docs neither on other website...to eliminate # on deeplink

**Comment by kienpham2000** [comment]
I just ran into this issue. You can do this at `app.module.ts`:

```
import { LocationStrategy, PathLocationStrategy } from '@angular/common';

@NgModule({
  providers: [
      { provide: LocationStrategy, useClass: PathLocationStrategy },
  ]
});
````

**Comment by devninjajeremy** [comment]
The above still doesnt solve the issue. I added this but get a "Cannot Get /page-name" on the page.
How do i fix this??

**Comment by HollyMarsia** [comment]
@devninjajeremy
1. app.module.ts <- add providers 
`providers: [
    {provide: LocationStrategy, useClass: PathLocationStrategy}
  ]`

2. add import  
`import {APP_BASE_HREF, LocationStrategy, PathLocationStrategy} from "@angular/common";`

good luck

**Comment by danielehrhardt** [comment]
Same here

**Comment by pushpendra-jaypore** [comment]
@kienpham2000 after using this the hash sing has been remove from the url but when we are trying to open page with newly generated url then this is return to and error page something like this :Not Found
The requested URL /shop-collection/gamcha-tales-8849 was not found on this server. so please tell me how to resolve this

**Comment by obravoInserious** [comment]
Same here

**Comment by overnightdev** [comment]
this is still open, sorry

**Comment by coder-hunt** [comment]
after spend some time on RND  finally got the ans set LocationStrategy:'path' this will remove hash from URL after removing hash enable mod_rewrite into your server if you are using Apache then past the following code into your server config file 

<Directory /var/www/html>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
</Directory>

after enable the mod_rewrite add these line into your .htaccess file 
<IfModule mod_rewrite.c>
Options Indexes FollowSymLinks
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>

**Comment by phingers** [comment]
But how do you do this @coder-hunt if you are using s3 buckets for the app? Where do we set LocationStrategy?

**Comment by ipehimanshu** [comment]
how to use when we are using lazy loading
it not working.

any one please help me to resolve in lazy loading

**Comment by MichaelHuy** [comment]
@ipehimanshu . I am stuck on this issue.

**Comment by ipehimanshu** [comment]
@MichaelHuy 
still i have not got any solution

**Comment by MichaelHuy** [comment]
@rapropos @jgw96 how to use when we are using lazy loading
it not working.
any one please help me to resolve in lazy loading? Thanks.

**Comment by eepstein** [comment]
why is this issue closed when it is unresolved?
