### ISSUE TITLE
Unable to serve super app

### ISSUE THREAD

**Issue by turaleck** [driftyco/ionic#11038]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am unable to serve an app created with the `super` flag. This is what I see in the browser:

Runtime Error: Unable to find module "ionic-native"
v@http://localhost:8100/build/polyfills.js:3:4862 @http://localhost:8100/build/main.js:116830:7 __webpack_require__@http://localhost:8100/build/main.js:20:12 @http://localhost:8100/build/main.js:102085:73 __webpack_require__@http://localhost:8100/build/main.js:20:12 @http://localhost:8100/build/main.js:128721:70 __webpack_require__@http://localhost:8100/build/main.js:20:12 @http://localhost:8100/build/main.js:66:18 @http://localhost:8100/build/main.js:1:11

Ionic Framework: 2.3.0
Ionic App Scripts 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 7.8.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0

I believe this is a similar [problem](https://github.com/driftyco/ionic-native/issues/1134#issuecomment-283669578), but the resolution therein did not fix my issue.
This is what I did:
1. Deleted the app
2. npm  --save @ionic-native/core@alpha -g
3. Recreated the app

**Expected behavior:**
I was expecting to see more than 14 ready to use page designs

**Steps to reproduce:**
1. ionic start myApp super --v2
2. cd myApp
3. ionic lab

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Not installed

**Comment by pwespi** [comment]
The problem is that the super-starter has not yet been updated to ionic-native 3.x. There is a [PR](https://github.com/driftyco/ionic-starter-super/pull/84) with a suggested fix.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-starter-super#88
