### ISSUE TITLE
Newline at end of config.xml removed by ionic cli

### ISSUE THREAD

**Issue by davejlong** [driftyco/ionic#11031]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When you run any `ionic` CLI command on an Ionic project, it will remove newlines from the end of `config.xml`. Many text editors automatically append the newline by default. The newline is also part of the definition of a line on [POSIX systems](http://stackoverflow.com/a/729795).

**Expected behavior:**

When I run `ionic` CLI commands that update the config.xml, the commands should either always insert the new line at the end or maintain the style previously used in the file.

**Steps to reproduce:**

1. Create a new ionic project
2. Commit the project to Git
3. Open and save `config.xml` with an editor that appends newlines to the end of files (Atom Editor has this by default)
4. Check the diff in Git:

```
> git diff config.xml
diff --git a/config.xml b/config.xml
index d3125bd..8bd3801 100644
--- a/config.xml
+++ b/config.xml
@@ -52,4 +52,4 @@
     <splash src="resources/ios/splash/Default@2x~iphone.png" height="960" width="640"/>
     <splash src="resources/ios/splash/Default~iphone.png" height="480" width="320"/>
   </platform>
-</widget>
\ No newline at end of file
+</widget>
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
> ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.7.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2062
