### ISSUE TITLE
Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for sqlite3

### ISSUE THREAD

**Issue by jiteshgupta1995** [driftyco/ionic#11043]
I am trying to build IOS app in ionic using `ionic build ios` The build is success. But when I use Xcode to deploy my App to apple store it is showing me above mentioned error.
I have gone through many **github** and **stackoverflow** issues but none of them worked for me. List of things I have tried:
1. Remove all .DSYM files
2. Add > CFBundleSupportedPlatforms as array and MacOSX as string to my info.plist
3. Removing all the Elements in my > Copy Bundle Resources
4. Clean project before building and the clicking archive option
Some of the links I found result:
`https://github.com/Alamofire/Alamofire/issues/823`
`http://stackoverflow.com/questions/34529583/couldnt-find-platform-family-in-info-plist-cfbundlesupportedplatforms-or-mach-o`

BTW this same project works for Android App.

But none of these worked for me. I tested my app to my phone it is working properly but could not upload to apple store. Any help would be appreciated.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
