### ISSUE TITLE
Slide toggle is not as performent as Material 2

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11049]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

The slide toggle in Ionic 2 is not very performent on mobile devices.

If you compare it with Angular Material 2 slide toggle you will notice significant difference.

One reason could be that in case of material 2 they have made the complete control touchable whereas in case of Ionic it seems only the top circle is tapable as a result user has to tap 2-3 times before it actually work.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately i am not understanding exactly which component you are talking about when you say slide toggle. Would you mind sharing more info?

**Comment by naveedahmed1** [comment]
I am referring to ion-toggle and comparing it with Angular material 2 slide toggle

**Comment by jgw96** [comment]
Ahh ok, unfortunately i am not seeing the behavior in any of our test apps. Would you mind sharing a repo we could use to reproduce this issue?

**Comment by manucorporat** [comment]
@naveedahmed1 this is a PR improving the performance of toggle
https://github.com/driftyco/ionic/pull/11104

**Comment by naveedahmed1** [comment]
Great!

**Comment by jgw96** [comment]
Hello! I am going to close this issue for now as the ionic-angular [3.1.0](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#310-2017-04-26) release includes Manu's performance fixes.

**Comment by naveedahmed1** [comment]
@manucorporat I can confirm the performance of toggle has been improved greatly. 

Can you please also check if the performance of buttons could also be improved, especially in case of small buttons for example  ion-button. In below code the ion button is small and has same performance issue.

```
<ion-card >
        <ion-item>
            <h2>Products</h2>
            <button ion-button clear icon-only item-right (tap)="presentModal(0)">
                <ion-icon name="add-circle"></ion-icon>
            </button>
        </ion-item>
        <products-list *ngIf="products.length>0;else #noProductsBlock>" [list]="products"></products>
	<ng-template #noProductsBlock>
		No product added yet!
	<ng-template>
</ion-card>
```
