### ISSUE TITLE
Unfortunately <appname> has stopped in android 5.0

### ISSUE THREAD

**Issue by Bala893** [driftyco/ionic#11042]
Ionic version: (check one with "x")
[x ] 1.x
[] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I am using the phonegap-plugIn-barcodescanner for my Cordova project. I created a very simple app which is working perfectly on Win X86, Android 4.3, Android 4.4 and Android 6.0. I have also tried to upload the Project to a Android Android 5.0. but there it is not working.
Everytime I try to scan a barcode by calling the plugIn my application throws an error which says "Unfortunately app has stopped".
![screenshot_20170403-175016](https://cloud.githubusercontent.com/assets/22056977/24650320/73ea9b30-1947-11e7-8822-33aa6eed4651.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately i am going to have to close this issue as this is not something in the framework causing the issue but something in that plugin. I would recommend opening an issue on the github repo for the plugin you are using.
