### ISSUE TITLE
bug(navigation): swipe back responsiveness is related to page complexity

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11056]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to swipe back a "heavy" page, the swipe is choppy, while trying to swipe back an empty page, the swipe back is silky smooth

**Expected behavior:**
Because this is UX, the swipe must consistently feel smooth

**Steps to reproduce:**
Create a page, that opens a page with only one button, that opens a page with many components, then swipe back.

**Other information:**
I have a video showing the issue in one case, but I can't share it publicly. Is there a way to share it with devs only?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Merging this one with https://github.com/driftyco/ionic/issues/11053. Thanks for opening an issue with us.

**Comment by AmitMY** [comment]
It is quite a different issue. I sent you a video showing the problem and why it is different via mail.

**Comment by gxsjtu** [comment]
besides, it is very slaggy, when clicking back button in a heavy child page to back to parent page.
