### ISSUE TITLE
some special error on page 

### ISSUE THREAD

**Issue by wohsj110** [driftyco/ionic#11058]
** version:**  
[ ] cordova -vc 6.5.0
[ ] ionic -v 2.2.1
[ ] node -v 

 when use ionic run android ,the application is ok,
but when i use shell command  pm intsall xx.apk (the apk is created by ionic ) ,it usually have some error ,
such as ,when i jump to a -> b ->c, i always stay at  b.can't go back to a and cant' trun to c .( i have do smthing on page b such as open the mass storage).
 however ,if i reboot the device, the error never appears. it just happen in the first time i use the command to install the apk .
could you help me ,thanks very much .

**Comment by AmitMY** [comment]
This is more likely a support request.
Besides opening a forum thread, I recommend using Rollbar, to track JavaScript issues (rollbar for browser, not rollbar native)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
