### ISSUE TITLE
 Can’t scroll ion-content ionic 2

### ISSUE THREAD

**Issue by achrafchikoun** [driftyco/ionic#11064]
Hi,
i'm new in ionic and i want to set a scroll into ion-content using overflow-scroll="true", but the scroll doesn't work.
help please.

**Comment by INeedNZT** [comment]
[#10938](https://github.com/driftyco/ionic/issues/10938)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
