### ISSUE TITLE
Custom Directives (Keypress event) in Android

### ISSUE THREAD

**Issue by ashley-s** [driftyco/ionic#11065]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.3.0

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have built a custom directive that limits the number of characters in an ion-input which uses the keypress event. It allows more than the specified number of characters in the input field. This directive works on the web, on android version 4.2.2 but does not work on android 5.1.1 and android 7.

**Expected behavior:**
It should not allow more than the specified number of characters to be entered in the field.
**Steps to reproduce:**

**Related code:**
Directive
import { Directive, Input, HostListener } from '@angular/core';

@Directive({
  selector: '[limit-to]' // Attribute selector
})
export class LimitTo {

  @Input('limit-to') limitTo;

  constructor() {

  }
  //HostListener decorator handle event handlers for input (onKeyPress)
  @HostListener('keypress', ['$event'])
  onkeypress(ev) {
    const limit = +this.limitTo; //convert to number
    // once it reaches the limit set, stop propgating event.
    if (ev.target.value.length === limit) {
      ev.preventDefault();
    }
  }

}
In template
<ion-input 
              type="number" 
              [limit-to]="8"
              placeholder="Username (required)" 
              formControlName="username"> </ion-input>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):


Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.2.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.2
Xcode version: Not installed

**Comment by AmitMY** [comment]
The `keypress` event does not work for mobile OSs like Android.
Use the `ngModelChange` output.

Saving you some time with an annoying issue when you reach the limit (no change detection firing):
http://stackoverflow.com/questions/43213582/angular-ngmodel-doesnt-update-when-ngmodelchange-keeps-value?noredirect=1

**Comment by ashley-s** [comment]
Hello,

Thanks for the reply. I am stuck on something. I don't have the event here in order to call event.preventDefault(). If it goes beyond the limit, how to stop further characters from entering?

I do hope you can help.

Thanks, 
Ashley

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by ashley-s** [comment]
Ok sure.

Thanks.
