### ISSUE TITLE
Bing Maps in Ionic v1 Framework is not working

### ISSUE THREAD

**Issue by yogi2806** [driftyco/ionic#11066]
I am trying to use Bing maps API in ionic v1 framework app which builds on android,iOS and windows platforms.

I am facing problem in Bing maps which is plotting properly but zoom in,zoom out,changing the map type from aerial to road & fetching current location these buttons are not functional.I have proper API key to access maps. I even tried it doing ionic serve on browser but nothing helped me.

I have followed code from the below link: https://github.com/eppineda/ionic.bing-map-demo

I have also changed JS src file of bing maps in index.html page from: src='http://dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0'

To

src='http://www.bing.com/api/maps/mapcontrol'

The src file i have changed referring to Microsoft document pages as below: http://www.bing.com/api/maps/sdkrelease/mapcontrol/isdk#loadMapAsync+HTML

Below are setup info:
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.3.0
Xcode version: Not installed

Please help me out to figure this out.It would be really helpful with the solution. Thanks in advance.

**Comment by AmitMY** [comment]
https://github.com/driftyco/ionic-v1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#237
