### ISSUE TITLE
docs: Search on doc v1 is broken

### ISSUE THREAD

**Issue by gerhardcit** [driftyco/ionic#11062]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Go to documentation V1 site.
https://ionicframework.com/docs/v1/
Try and search. It's broken. 
Look at the javascript console.. a LOT of http stuff is served with warnings. Which is possibly why the search is broken.</span>

<span is-issue-template></span>

**Comment by MA-Maddin** [comment]
It is not just v1 affected but also v2, for more than a week now.

When entering something in search, "API" and "Native" sections stay blank and everything I click in "General" results into the 404 page.

Also many 404 errors in console.

```
GET https://ionicframework.com/docs///tmp/build_74b698d4a948496813b816516102f52f/driftyco-ionic-site-b568e75/content/docs/native/dialogs/ 404 ()
onloadwff.js:53 GET https://ionicframework.com/fonts/avenir-next/medium.woff2 
(anonymous) @ onloadwff.js:53
d @ onloadwff.js:53
fireWith @ onloadwff.js:53
ready @ onloadwff.js:52
Ae @ onloadwff.js:52
onloadwff.js:53 GET https://ionicframework.com/fonts/avenir-next/regular.woff2 
(anonymous) @ onloadwff.js:53
d @ onloadwff.js:53
fireWith @ onloadwff.js:53
ready @ onloadwff.js:52
Ae @ onloadwff.js:52
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1038
