### ISSUE TITLE
Ionic 3 and Webpack 2 warning

### ISSUE THREAD

**Issue by ghaiat** [driftyco/ionic#11072]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x]  **3.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Since i ve upgraded to ionic 3, i get this error in my webpack build:
```
WARNING in /xxx/app/~/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression
    at ImportContextDependency.getWarnings (/xxx/app/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/xxx/app/node_modules/webpack/lib/Compilation.js:668:24)
    at Compilation.finish (/xxx/app/node_modules/webpack/lib/Compilation.js:531:9)
    at /xxx/app/node_modules/webpack/lib/Compiler.js:486:16
    at /xxx/app/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/xxx/app/node_modules/webpack/lib/Compilation.js:477:11)
    at processModuleDependencies.err (/xxx/app/node_modules/webpack/lib/Compilation.js:448:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Any idea why ?

Cheers

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by marcoturi** [comment]
I run to the same issue updating [ionic2-boilerplate](https://github.com/marcoturi/ionic2-boilerplate) to ionic 3 during unit testing command. It looks similar to this issue https://github.com/angular/angular/issues/11580

I got:
```
WARNING in ./~/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ionic-angular/util/ng-module-loader.js
69:11-36 Critical dependency: the request of a dependency is an expression
```
@ghaiat Did you managed to resolve this issue ? Also could you provide a little more context about it?

**Comment by marcoturi** [comment]
For anyone having this issue, the fix is to add in you webpack configuration:
           ```
 new ContextReplacementPlugin(
                /ionic-angular/,
                path.resolve('./src'),
                {}
            ),
```

**Comment by cryo243** [comment]
And together with angular 4 warnings it becomes
`    new ContextReplacementPlugin(
        /(ionic-angular)|(angular(\\|\/)core(\\|\/)@angular)/,
        path.resolve('./src') ,
       {}
      )`

**Comment by maapteh** [comment]
Why is this issue closed? Since version 3 i also get these warnings
```
WARNING in ./~/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ionic-angular/util/ng-module-loader.js
69:11-36 Critical dependency: the request of a dependency is an expression
```
which basically says there is a dynamic import and dynamic imports should not be used. 

Since im using angular/cli and not ionic/cli (i only like the framework for build i simply use cordova and angular cli running `ng build --prod --base-href ./ --output-path www --output-hashing=none`) . Can this issue be fixed on library side?

**Comment by schacki** [comment]
@maapteh : https://github.com/angular/angular.io/issues/3514

**Comment by shanehughes3** [comment]
I'm getting this error when running karma/jasmine tests, and I don't have a webpack conf where I can add the aforementioned fix. The folks over at webpack seem to imply that [this is an issue that shouldn't be suppressed](https://github.com/webpack/webpack/issues/196#issuecomment-71917456), so shouldn't we be talking about a library fix?

**Comment by kamok** [comment]
@jgw96 Can you please reopen? I'm getting the same issue as @shanehughes3. I also don't have a webpack config and I have the problem when running karma/jasmine tests.

**Comment by cryo243** [comment]
I know this is not a final fix but both of  you guys could have a different webpack config for your tests and implement the fix above(just so you can get rid of the warnings until ionic fixes it)' One issue is related to angular 4 the other one is from ionic native

**Comment by kamok** [comment]
@cryo243 I can't find a webpack config in my app. I don't know where it is. Is it in the node_modules/angular folder?

**Comment by cryo243** [comment]
@kamok if you are using karma/webpack to run your unit tests you should have created a webpack config.
in your karma.conf file you should have a webpack property that points to your custom webpack test  file

**Comment by kamok** [comment]
@cryo243 I use angular/cli. Same set up as this seeder project: https://github.com/lathonez/clicker

**Comment by cryo243** [comment]
@kamok , that's because you are using angular cli together with karma. Angular cli uses webpack in the background but I'm not sure to what extent you can customize their Webpack config. 
Rather use your own webpack config for unit tests and pass it to your karma.conf (you will need to install karma-webpack plugin though)
then in your karma.conf  file replace
`    angularCli: {
      environment: 'dev'
    },`
with
`webpack: path/to/TestWebpackConfig,`

**Comment by russcarver** [comment]
Can someone post the contents of just what such a "test" webpack config should look like?

**Comment by tinomen** [comment]
I get this warning twice. Is the current solution still to suppress them?

**Comment by jdnichollsc** [comment]
Any news guys? thanks in advance, it's really neccesary without eject the webpack configuration! 👍

**Comment by cryo243** [comment]
Hi guys,
I thought I would create  very basic example feel free to check https://github.com/cryo243/ionic-unit-tests

**Comment by jdnichollsc** [comment]
@jgw96 Justin, please reopen this issue. it's generated from the library because this is an incompatibility with the "ng serve" of the angular-cli.
Thanks guys in advance! ✌️

**Comment by jdnichollsc** [comment]
@jgw96 Any news about this item? it's very complicated? Any response from the Ionic team is welcome 🙏 (this would be like a Christmas gift)

**Comment by jdnichollsc** [comment]
Hi @danbucholtz, Is possible to create a new release of Ionic with the fix of the default webpack configuration with the following fix? https://github.com/ionic-team/ionic-unit-testing-example/pull/34/files
Thanks in advance guys!

**Comment by jdnichollsc** [comment]
Guys, what do you think about the following PR? https://github.com/ionic-team/ionic-app-scripts/pull/1360

**Comment by damsorian** [comment]
this issue is not resolved ...

**Comment by jdnichollsc** [comment]
@damsorian I'm waiting for Ionic 4 due to this issue...

**Comment by edwinm** [comment]
July 2nd 2018 and still not resolved...

`WARNING in ./node_modules/ionic-angular/es2015/util/ng-module-loader.js
25:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/es2015/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/es2015/util/module-loader.js
 @ ./node_modules/ionic-angular/es2015/components/modal/modal-component.js
 @ ./node_modules/ionic-angular/es2015/index.js
 @ ./src/test.ts`
