### ISSUE TITLE
bug: ionic g page should use IonicPageModule

### ISSUE THREAD

**Issue by geykel** [driftyco/ionic#11076]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>3.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using the Ionic cli generate command for generating pages, the page module tempate is using IonicModule instead of IonicPageModule.

Reproduce:

ionic g page login

This is my current dev environment:

cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#2070
