### ISSUE TITLE
bug(ux): click / tap delays on low end devices

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11089]
**I am not sure if this is an issue with ionic or with Angular. If this is an issue with Angular, please let me know and I will open this in their repo**

**Ionic version:**  (check one with "x")
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
While ionic apps work extremely well in browser, on a device the story is a bit different. Everything just feels delayed (touch events), and applications does not feel native. (or close to native)

**Expected behavior:**
Fix the time violations somehow by implementing things that will increase events speed.
And while I don't expect extreme support for older devices, I think that a better touch/events handling can always be done.

**Table of current violations:** 
```
| Event                  | Confirmed platform/version | Last seen | Violations                                                                                                                                                                                  |
|------------------------|----------------------------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Bootstrap              | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'requestAnimationFrame' handler took ~60ms                                                                                                                                      |
| Bootstrap              | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'readystatechange' handler took 312ms                                                                                                                                           |
| Menu icon click        | Galaxy S4 5.0.1            | 3.0.1     | [Violation] Forced reflow while executing JavaScript took [30, 60]ms                                                                                                                        |
| Menu icon click        | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'requestAnimationFrame' handler took [50-70]ms                                                                                                                                  |
| Navigation Button      | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'click' handler took [400, 600]ms                                                                                                                                               |
| Navigation Button      | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'requestAnimationFrame' handler took 117ms                                                                                                                                      |
| Navigation Button      | Galaxy S4 5.0.1            | 3.0.1     | [Violation] Forced reflow while executing JavaScript took 80ms                                                                                                                              |
| Navigation Button      | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'setTimeout' handler took 68ms                                                                                                                                                  |
| Slide menu             | Galaxy S4 5.0.1            | 3.0.1     | [Violation] Handling of 'touchstart' input event was delayed for 2147483647 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive. |
| Hardware back button   | Galaxy S4 5.0.1            | 3.0.1     | [Violation] 'setTimeout' handler took 179ms                                                                                                                                                 |
| Moving to a busy tab   | Galaxy S4 5.0.1            | 3.0.1     | [Violation]'click' handler took [300, 500]ms                                                                                                                                                |
| Moving to an empty tab | Galaxy S4 5.0.1            | 3.0.0     | [Violation]'click' handler took 286ms                                                                                                                                                       |
| Moving tab             | Galaxy S4 5.0.1            | 3.0.1     | [Violation] Forced reflow while executing JavaScript took 221ms
```

Feel free to add violations in the comments.

Also, notice the "Slide menu" event violation, that is definitely a bug (2147483647)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by Manduro** [comment]
Are you building with the `--prod` flag to enable aot?
Are you using Crosswalk?

**Comment by AmitMY** [comment]
Well, I thought I did, doing:
`ionic cordova:run android -l --debug --prod` / `ionic cordova:run android --debug --prod`
But it seem to only do: `cordova run android --debug`

Doing: `ionic cordova:run android --prod` runs it in prod mode, and has most of the violations shown above, sometimes with the same timings, sometimes lower.

I do not use Crosswalk. Is it recommended to use crosswalk with ionic?
And anyway, I think that because ionic is saying `framework for building amazing mobile apps`, they should try and

**Comment by Manduro** [comment]
It is recommended if you want the best performance on Android, especially versions below 6. Here's a good read on it: [click](https://medium.com/appseed-io/boost-your-ionic-app-performance-with-crosswalk-6d9d083eadbb).

I'm sure Ionic mentions this in the available docs somewhere.

**Comment by ghenry22** [comment]
Although Intel has announced that they will no longer maintain crosswalk past the current version as it is no longer necessary with the updated system web views that are now available, so the argument for cross walk is really if you are supporting devices older than android 5.0 as you can provide a newer system webview.

Unless the community picks up the maintenance of crosswalk though you would just be adding another plugin that is already deprecated by the maintainer.

**Comment by Manduro** [comment]
Well, as long as you need to support Android 4/5 you can keep using it. The plugin is no longer maintained, but those Android releases aren't either. You could even create two builds of your app and serve the one with crosswalk only on old Androids, so the newer ones get a smaller package without it.

**Comment by jgw96** [comment]
Hello @AmitMY , would you mind trying with Ionic 3.0.1, that has a fix for click delays which may help you. Also as far as Crosswalk goes, for a device running Android 5.0.1 you will not need crosswalk. Android 5.0 and up has a webview that is built on chrome and updates just as often as chrome the browser does. So a device running Android 5.0 and a device running Android 7.1.1 will have the same version of the chrome webview.

**Comment by AmitMY** [comment]
@jgw96 Thanks. I am not sure that that is how it works for samsung devices, as the webview still does not support ES2015 (on Android 5.0.1)

Here are the test results:
```
| Navigation Button       | [Violation] 'click' handler took 813ms 
Changed to [400, 600] - for the same page. An empty page has no delay, and a moderate page has 200
| Moving to a busy tab    | [Violation]'click' handler took 683ms
Changed to [100, 200]
| Moving to an empty tab  | [Violation]'click' handler took 286ms
Disappeared
```

Which are an improvement.
But it is just manual testing, I can not know for sure. One thing I do know, is that I use a specific test device that I don't use for anything else, so the environment should be the same.
(I checked each event at least 10 times)

**Comment by jgw96** [comment]
Hmm, that is interesting @AmitMY. Actually it may be a good test to try this with crosswalk and see if that improves thing. I guess it is possible that Samsung (in all their infinite android defeating wisdom (; ) could possibly have replaced the stock Android 5.0 and up webview on their devices.

**Comment by jgw96** [comment]
Hello, all! We made some changes in 3.1.0 which fixed a click delay. Because of this, I am going to close this issue for now, but please feel free to comment or open a new issue if you are still seeing issues. Thanks!
