### ISSUE TITLE
Scrolling trouble on UIWebView since 2.3.0

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#11086]
**Ionic version:**
[x] **2.x / 3.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
Before 2.3.0 (specifically, before https://github.com/driftyco/ionic/commit/7e9bad509255b642f6099366231ad86fe6eaddad), js scrolling was used on UIWebView, but only for the virtual scroll component. 

Since 2.3.0, up to current master, js scrolling is enabled on every scroll view when using UIWebView. This causes a lot of other functionality to malfunction (InfiniteScroll, Pull to refresh, scrollToX(), etc.). This is because they track scroll position using `content.getContentDimensions()`, which gets its `scrollTop` from the scroll element. But, when using js scrolling, its `scrollTop` is always zero, because scrolling is done using a transform.

**Expected behavior:**
Latest Ionic should behave like 2.2.0 on UIWebView.

**Steps to reproduce:**
Run Ionic's own InfiniteScroll e2e test in a UIWebView, and you'll see it doesn't work.

**Related code:**
pre 2.3.0, js scrolling is enabled [here](https://github.com/driftyco/ionic/blob/v2.2.0/src/components/virtual-scroll/virtual-scroll.ts#L658) in `virtual-scroll.ts`.
```ts
if (this._config.getBoolean('virtualScrollEventAssist')) {
  this._content.enableJsScroll();
}
```

post 2.3.0, js scrolling is enabled [here](https://github.com/driftyco/ionic/blob/master/src/components/content/content.ts#L366) in `content.ts`'s constructor:
```ts
const jsScroll = config.getBoolean('virtualScrollEventAssist');
this._scroll = new ScrollView(_app, _plt, _dom, jsScroll);
```

This changed in this commit: https://github.com/driftyco/ionic/commit/7e9bad509255b642f6099366231ad86fe6eaddad

**Other information:**
Issues caused by this regression:
#11081 
#10976 
#10966
#10936
#11051 
#10889

There are probably more of them out there. Some have been closed but weren't really fixed in 3.0.0.

**Comment by manucorporat** [comment]
This is the first time it is reported as an UIWebView only issue... it was my fault though

I am working in a good fix for UI right now. What is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.

**Comment by manucorporat** [comment]
@Manduro could try this nightly release?
+ ionic-angular@3.0.0-201704061344

**Comment by Manduro** [comment]
@manucorporat Yeah took me long enough to figure it out as well, but it was working on mobile safari so that's how I found out ;). Thanks for the quick fix. It seems to be working fine again on first sight.

Is it possible that the 300ms tap delay has returned though?

I've tried WKWebView around the v2 beta's I think, but I ran into some minor issues. It's on my list to give it another go soon. The most significant was that I couldn't get autofocus to work anymore, which I believe is a known WK limitation. Any other issues I ran into have probably been solved in Ionic by now.

Thank you for your amazing work on Ionic :)

**Comment by manucorporat** [comment]
@Manduro when did the  300ms click delay regression happen? updating to 3.0?

**Comment by Manduro** [comment]
@manucorporat Just checked, 3.0 non-nightly has the delay as well. 2.2 didn't, not sure about 2.3.

**Comment by rossholdway** [comment]
@manucorporat I'm pretty sure I'm seeing the delay also when running the nightly.

**Comment by Manduro** [comment]
Just noticed there's an issue about this: #10935.

So I'm closing this one 🎉

**Comment by manucorporat** [comment]
@rossholdway @Manduro I can confirm the delay, no. I am working a new fix

**Comment by manucorporat** [comment]
@rossholdway @Manduro 
here's the fix: https://github.com/driftyco/ionic/commit/32094f72c78541db8fc9eee51bf91700b175480a

and a new nightly: + ionic-angular@3.0.0-201704061551


can you please try it really quick? thanks!

**Comment by Manduro** [comment]
@manucorporat Works here, awesome!

**Comment by rossholdway** [comment]
@manucorporat Looks good here too 👍

**Comment by engehabahmed** [comment]
Thanks too muck , you saved my day :) <3
