### ISSUE TITLE
ionic3 page scroll bug

### ISSUE THREAD

**Issue by HonLuk** [driftyco/ionic#11081]
**Ionic version:**  (check one with "x")
[x] **3.0*

**I'm submitting a ...**  (check one with "x")
[x] bug report

updata ionic from 2.2 to 3.0. everything goes well on chrome.but on ios device.
scroll page become so weird and can use infinite-scroll or refresher.

**Comment by judithhartmann** [comment]
The error must have happened from 2.2 to 2.3.

Here are two gifs that compare the behavior: (the shown list has a refresher on top and an infinite scroll on the button, no problem prior 2.2. but now it keeps me from updating to 3.0 :( )
In 2.3 it just jumps from top to bottom and back with no possibility to reach the list in between. 

2.2.
![2_2_scroll](https://cloud.githubusercontent.com/assets/4180150/24747788/c44853c0-1abd-11e7-90b5-cc4f2495a6a8.gif)

2.3
![2_3_scroll](https://cloud.githubusercontent.com/assets/4180150/24747798/d25d95f6-1abd-11e7-90bd-8ebff6ab42ac.gif)

**Comment by Walgermo** [comment]
Confirmed.

this.content.ScrollToBottom() works only in chrome and not on device 👎

**Comment by judithhartmann** [comment]
Probably related to #10936 and #10966

**Comment by manucorporat** [comment]
I didn't notice it was a UIWebView only issue.

I am working in a good fix for UI right now. But in the meantime, what is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.

**Comment by manucorporat** [comment]
@HonLuk @Walgermo @judithhartmann
 could try this nightly release? ionic-angular@3.0.0-201704061344

**Comment by HonLuk** [comment]
@manucorporat  worked! thanks !everything goes well but tab click,see [#11105](https://github.com/driftyco/ionic/issues/11105)
