### ISSUE TITLE
Input, scrolling, keyboard issues for forms

### ISSUE THREAD

**Issue by kumaresan-cgvak** [driftyco/ionic#11088]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When an input field is focused, the screen scrolls up and then scrolls down every time I click on the field. So, as a result Keyboard hides the input.

**Expected behavior:**
Input schould scroll up and stay above keyboard.

**Related code:**

```
  <ion-list>
<ion-item>
          <ion-label stacked>Max. RP</ion-label>
          <ion-input type="number"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label stacked>Max. RP</ion-label>
          <ion-input type="number"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label stacked>Max. RP</ion-label>
          <ion-input type="number"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label stacked>Max. RP</ion-label>
          <ion-input type="number"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label stacked>Max. RP</ion-label>
          <ion-input type="number"></ion-input>
 </ion-item>
 </ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.3 Build version 8E162

```

**Comment by e9li** [comment]
Similar or same behavior in my app. I already sent an issue (#11027) a few days before and get the comment that this problem would be resolved in the next version. Unfortunately it's not the case. I really like your framework, but in apps we should be able to fill and send forms. Is there a workaround or how can this be solved?

![iphone6_small](https://cloud.githubusercontent.com/assets/1247727/24760423/514c0d88-1af1-11e7-9c97-cea29e38c68b.gif)

**Comment by dylanvdmerwe** [comment]
Can you provide further information? What devices? What OS? Running WKWebView?

This is something that I am also experiencing and want to try and get as much information to the team as possible.

**Comment by e9li** [comment]
This happens on iPhone and iPad and iSimulator with iOS 10.3
On Android I only have tested in the emulator with android 7.1.1 and there in works fine.

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3 Build version 8E162

its a simple list like in your docs, just a little longer:


```
<ion-item>
    <ion-label>Name*</ion-label>
    <ion-input type="text" formControlName="Name"></ion-input>
</ion-item>
<ion-item>
    <ion-label>Firma</ion-label>
    <ion-input type="text" formControlName="Firma"></ion-input>
</ion-item>
<ion-item>
    <ion-label>Strasse, Nr.*</ion-label>
    <ion-input type="text" formControlName="Strasse_Nr"></ion-input>
</ion-item>
<ion-item>
    <ion-label>PLZ/Ort*</ion-label>
    <ion-input type="text" formControlName="PLZ_Ort"></ion-input>
</ion-item>
<ion-item>
    <ion-label>Telefon</ion-label>
    <ion-input type="text" formControlName="Telefon"></ion-input>
</ion-item>
<ion-item>
    <ion-label>Mobile</ion-label>
    <ion-input type="text" formControlName="Mobile"></ion-input>
</ion-item>
<ion-item>
    <ion-label>E-Mail*</ion-label>
    <ion-input type="text" formControlName="Email"></ion-input>
</ion-item>
```

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic. Would you all mind updating to 3.0.1 and trying again? We have been struggling with scroll event regressions on iOS and 3.0.1 has a hotfix for these issues.

**Comment by kumaresan-cgvak** [comment]
@jgw96 yes.. it resolves the issue. Thank you. 

````
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.3 Build version 8E162
````

**Comment by e9li** [comment]
3.0.1 fixes the issue. Thank you.
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by devartstudio** [comment]
this issue seems back:

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.2.0
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145
