### ISSUE TITLE
Black screen, or messy history.back() navigation

### ISSUE THREAD

**Issue by bugbuka** [driftyco/ionic#11085]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
navController do navChange even when the transition is not a page, eg: a Loading triggers navChange(direction) method in deep-link.js#line354   

this could raise back screen or messy history.back() navigation  

For a temporary fix: 
update file ./node_modules/ionic-angular/navigation/nav-controller-base.js  
replace following  
```
#line766    if (transition.isRoot()) {
```
with  
```
#line766    if (transition.enteringPage && transition.isRoot()) {
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.3.0-201703241812
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.2.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.10.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
