### ISSUE TITLE
ionic build --prod no found ionic 3

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic#11092]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

  "dependencies": {
      "@angular/common": "4.0.0",
      "@angular/compiler": "4.0.0",
      "@angular/compiler-cli": "4.0.0",
      "@angular/core": "4.0.0",
      "@angular/forms": "4.0.0",
      "@angular/http": "4.0.0",
      "@angular/platform-browser": "4.0.0",
      "@angular/platform-browser-dynamic": "4.0.0",
      "@ionic-native/core": "^3.4.2",
      "@ionic-native/device": "^3.4.2",
      "@ionic-native/geolocation": "^3.4.2",
      "@ionic-native/splash-screen": "^3.4.2",
      "@ionic-native/status-bar": "^3.4.2",
      "@ionic/storage": "2.0.1",
      "ionic-angular": "3.0.0",
      "ionicons": "3.0.0",
      "rxjs": "5.1.1",
      "sw-toolbox": "3.4.0",
      "zone.js": "^0.8.4",
      "imgcache.js": "^1.1.1"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },

error

![captura de pantalla 2017-04-06 a las 11 54 50](https://cloud.githubusercontent.com/assets/731936/24760793/094f22bc-1ac0-11e7-8667-ac3978abedd6.png)

**Comment by mburger81** [comment]
This is no an error for ionic-angular but for ionic-app-script
I opened the same issue some hours ago
https://github.com/driftyco/ionic-app-scripts/issues/877

**Comment by SquaredData** [comment]
Had the same, solved via

ionic build ios --env=prod

**Comment by petrot** [comment]
"ionic build ios --env=prod" 
give me the same result than 
"ionic build ios"

**Comment by danbucholtz** [comment]
This should be resolved in `1.3.1`.

```
npm install @ionic/app-scripts@1.3.1
```

Thanks,
Dan
