### ISSUE TITLE
Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by jcmartins** [driftyco/ionic#11091]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[] **2.x**
[x]**3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

upgrade to version 3
**Expected behavior:**

Error: Cannot find module "ionic-native"
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at Object.<anonymous> (http://localhost:8100/build/main.js:107109:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:80974:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:119490:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

**Steps to reproduce:**

**Related code:**

```
{
  "name": "my-app",
  "author": "jc",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  }
}

ls -la node_modules/@ionic-native:
total 36
drwxr-xr-x   5 jc jc  4096 abr  6 11:15 .
drwxr-xr-x 504 jc jc 20480 abr  6 11:15 ..
drwxr-xr-x   2 jc jc  4096 abr  6 11:15 core
drwxr-xr-x   2 jc jc  4096 abr  6 11:15 splash-screen
drwxr-xr-x   2 jc jc  4096 abr  6 11:15 status-bar

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework: 3.0.0
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 7.7.3
OS Platform: Linux 4.10
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

**Comment by dlemphers** [comment]
Because Ionic3 upgraded to [Ionic-Native 3.x](https://github.com/driftyco/ionic-native/blob/master/README.md) you'll need to update your imports where you're using `ionic-native`.

All the doco is updated, which is what I used to update where I'm using stuff like [SplashScreen](http://ionicframework.com/docs/native/splash-screen/), [StatusBar](http://ionicframework.com/docs/native/status-bar/), and [Device](http://ionicframework.com/docs/native/device/).

**Comment by miguelcarrascoq** [comment]
I have the same issue. http://imgur.com/a/ei35J My ionic info:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.3 Build version 8E162

**Comment by miguelcarrascoq** [comment]
Sorry guys. It was my fault. I was using:
import { InAppBrowser } from 'ionic-native';
instead of: 
import { InAppBrowser } from '@ionic-native/in-app-browser';

Now everything works again

**Comment by wbhob** [comment]
Yes, when you remove the `ionic-native` dependency from `package.json`, you remove the package so you have to remove it from your code.

**Comment by brandyscarney** [comment]
Please take a look at the following blog for updating to Ionic Native 3.x: http://blog.ionic.io/ionic-native-3-x/

See step 4 of the steps to upgrade: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade

And an example commit that shows the changes: https://github.com/driftyco/ionic-conference-app/commit/62088

If you are having issues with Ionic Native after this please open a new issue here: https://github.com/driftyco/ionic-native/issues

Thank you! 😄

**Comment by Sherbadshah** [comment]
I want to work in all versions like ionic 1, 2 and 3. So what's the solution ?

**Comment by wbhob** [comment]
Use Ionic native 2.x for Ionic 1, and Ionic native 3.x for ionic 2+ http://blog.ionic.io/ionic-native-3-x/

**Comment by SVANNER** [comment]
Hi, I have the same kind of problem with the new Ionic 3 framework hetting SQLite:

import { SQLite } from 'ionic-native'

I get the error " cannot find module 'ionic-native'"

What can i do to get the SQLite class with Ionic 3 ?

Thanks a lot !

**Comment by wbhob** [comment]
The module is @ionic-native/sqlite

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by SVANNER** [comment]
Thanks a lot ! It Workshop !

**Comment by gopi2mohan** [comment]
i am still facing this issue where i have commented all the plugin related code in my pages and inside my app.module.ts file i have imported and added all the plugins inside my providers array also 
but still i am facing this issue check this http://stackoverflow.com/questions/43759991/ionic-3-type-any-is-not-a-constructor-function-type/43760070?noredirect=1#comment74561931_43760070 where i have placed a question and details about my project

**Comment by payen83** [comment]
I found my solution. You need to change at app.component.ts

Remove this:
`import { StatusBar, Splashscreen } from 'ionic-native';`


..and add this:
`import { StatusBar } from '@ionic-native/status-bar';`
`import { SplashScreen } from '@ionic-native/splash-screen';`


If you recently removed the node_modules, please reinstall those native plugins again at terminal/cmd:
```
$ npm install --save @ionic-native/status-bar 
$ npm install --save @ionic-native/splash-screen
$ npm install --save @ionic-native/core 
```

**Comment by wmehanna** [comment]
@payen83 thanks for this.

**Comment by AdhamRammadan** [comment]
Use:
import { Geolocation } from "@ionic-native/Geolocation";
import { Geofence } from "@ionic-native/Geofence";
import { SMS } from "@ionic-native/SMS";

Instead Of :
import { Geofence,  Geolocation,  SMS } from 'ionic-native';

**Comment by proqramci** [comment]
#
