### ISSUE TITLE
roll back from 3.0 to 2.x

### ISSUE THREAD

**Issue by KlarY** [driftyco/ionic#11099]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.0**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

How can i roll back to 2.x?
i've updated ionic and package.json :(
I can choose the version of the doc on your website in API/Component part
but NOT in Native part
I cant find the 2.x version of NATIVE :( :( :(

**Comment by wbhob** [comment]
> [x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by wbhob** [comment]
Also, Native 3.x works with Ionic 2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
