### ISSUE TITLE
 InfiniteScroll and Refresher BOTH error

### ISSUE THREAD

**Issue by KlarY** [driftyco/ionic#11096]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

InfiniteScroll not work
Refresher can be trigger at any position of the page
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by SquaredData** [comment]
Same Problem on iPhone 6s: 
- Scolling of a regular ion-content area stucks 
- Buttons in the side-menu have a huge delay

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.3
Xcode version: Xcode 8.3 Build version 8E162

**Comment by brandyscarney** [comment]
Thanks for the issue! We just cut a release that should fix these issues. Could you please update and try it out?

```
npm install --save --save-exact ionic-angular@3.0.1
```

**Comment by anveo** [comment]
`ionic-angular@3.0.1` fixed the Refresher for me.

**Comment by SquaredData** [comment]
ionic-angular@3.0.1 fixed my issues above  

Thx so much for this incredible good support!

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as it seems to have been fixed. Thanks for using Ionic!
