### ISSUE TITLE
Ionic native : Image picker not working.

### ISSUE THREAD

**Issue by rijin-newage** [driftyco/ionic#11095]
Hello, 

I can't use ionic native **Image picker** plugin with **BackgroundMode** plugin.

No error is showing, but when i am calling getPictures function, it is giving an empty array as response before choosing any pics, after choosing pics it does't giving any response.

This issue is fixed when i removed BackgroundMode plugin. 

I'm using the latest version of ionic 2 framework (2.2.0)

Thank you

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#1341
