### ISSUE TITLE
Added a new module will lead to the entire app checkbox useless on ios, android is normal

### ISSUE THREAD

**Issue by zengyufang** [driftyco/ionic#11106]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

Added a new module will lead to the entire app checkbox useless on ios, android is normal,
![image](https://cloud.githubusercontent.com/assets/23447639/24782422/b0fe939a-1b78-11e7-933f-32d9f7be0902.png)
I want to know this is what causes??

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
