### ISSUE TITLE
[Re-Feature] - Allow assign URL to pages without creating a new module

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#11109]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In order to assign URL to specific page a new page module is required.

**Expected behavior:**
- Assign URLS to pages without creating a page module. 
- Documentation about assigning url to page, what needs to be imported in a module

**Steps to reproduce:**
Tried to use @IonicPage() in a page component

**Related code:**
In Ionic 2.3.0 I just had to specify array for links in the appmodule:
```
IonicModule.forRoot(MyApp, {
      locationStrategy: 'hash',
    },
    /*
      {links: [
        { component: Home, name: 'Home Page', segment: '' },
]}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic 3.0
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can still use the links array and also you can use `@IonicPage` without having an NgModule for that page. We have a blog coming out in a few that will explain this a bit more, along with some more info on code splitting if your interested in going that route.
