### ISSUE TITLE
click active tab button refresh active tab page

### ISSUE THREAD

**Issue by HonLuk** [driftyco/ionic#11105]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

update to ionic3. when tab-1 is active,click it will refresh this active tab page.
how can I disable click active tab-btn  refresh active page.
by the way,ionic 2.2 works fine.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, i am going to close this as a duplicate of https://github.com/driftyco/ionic/issues/11078.
