### ISSUE TITLE
Side menu needs double tap

### ISSUE THREAD

**Issue by e9li** [driftyco/ionic#11110]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating from 3.0.0 to 3.0.1 a normal working link in the side menu now needs two taps to open a page on iOS devices or iSimulator with 10.3. This happens only in side menu, all other links I tried so far behaving normal with one tap.

**Expected behavior:**
Only one tap or click as before

**Related code:**
```
<ion-menu [content]="content">
  <ion-content>
    <ion-list no-lines>
      <ion-item menuClose (click)="openPage('HomePage')">
        <ion-icon name="ios-home-outline" item-left></ion-icon>
        Home
      </ion-item>
    </ion-list>
  </ion-content>
</ion-menu>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by e9li** [comment]
Changing <ion-item> to <button> solves the problem. But should this really be?

**Comment by chandanch** [comment]
I tried in iOS 10 on iphone 6s and it works with a single tap. 

Here is my side menu code:

```html
<ion-menu [content]="favoriteChickenList" color="diamond" side="right" id="chickenMenu" type="overlay">
    <ion-header>
         <ion-toolbar>
            <ion-title>My Chickens</ion-title>
        </ion-toolbar>
        <ion-buttons end>
            <button ion-button clear icon-right (click)="closeFavoriteChickenListMenu"
        </ion-buttons>
    </ion-header>
    <ion-content>
        <button ion-item *ngFor="favoriteChicken of favoriteChickens">{{chicken.name}}</button>
    </ion-content>
</ion-menu>
```

**Comment by jgw96** [comment]
Hello all. As this issue seems to have been fixed I am going to close this issue for now.
