### ISSUE TITLE
bug(loadingController): Dismiss throwing exception

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#11119]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When calling `dismiss()` on a LoadingController, an exception is thrown from the framework. 

![image](https://cloud.githubusercontent.com/assets/2852839/24804707/a70ce332-1baf-11e7-891e-4e79f33b6703.png)

**Expected behavior:**
Dismissing popups from the LoadingController should work correctly. 

**Related code:**

```
  ionViewDidLoad() {
    let loader = this.loader.create({
      content: "Logging out...",
    });
    loader.onDidDismiss(() => {
      console.log('loader dismissed');
    });

    loader.present();

   // perform some quick action

    loader.dismiss();
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by AmitMY** [comment]
I think it is because you can't dismiss something that was not shown.
Try:
`loader.present().then(() => loader.dismiss())`

**Comment by jgw96** [comment]
Hey @dylanvdmerwe , @AmitMY makes a good point here, its possible that your running into a race condition here where `loader.dismiss()` fires before present is done.

**Comment by manucorporat** [comment]
Unfortunately, this is in fact a very serious bug and affects all the components using NavControllerBase.

https://github.com/driftyco/ionic/pull/11126#issuecomment-292666442

**Comment by mburger81** [comment]
@manucorporat What's about this bug?

**Comment by mburger81** [comment]
News about that?

**Comment by AmitMY** [comment]
@mburger81 https://github.com/driftyco/ionic/pull/11128

**Comment by mburger81** [comment]
@AmitMY yeah thx I saw this some days ago and I also asked to the team a status update about the bug with no response. I don't know how is the situation but I think this bug is really severe and I think this should have max priority or not?

**Comment by philipbrack** [comment]
Thanks for the lead guys, I found the same issue in my app.
```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.3
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

Temporary workaround-

```javascript
        setTimeout(() => {
          this.loading.dismiss();
        }, 50);
```

**Comment by mburger81** [comment]
@AmitMY I'm not sure how this could be a workaround for my issue. I can not do something like that
```
    ionViewCanEnter(): Promise<any> {
        //console.log('LoginPage#ionViewCanEnter');

        setTimeout(() => {
            return this.authGuard.canActivateLoginPage();
        }, 500);
    }
```

My problem is for sure the BavControllerBase and I think I have to wait until the team merged and released #11128

**Comment by gigocabrera** [comment]
@philipbrack your Temporary workaround worked for me too. Thank you

**Comment by jgw96** [comment]
Hello all! I am going to close this for now as it seems manu's PR to fix this issue was merged. Thanks!

**Comment by mburger81** [comment]
Okay but which PR do you mean? Just for information?
