### ISSUE TITLE
Popover does not work for NgModules, ionic3 and lazy-loading IonicPage

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#11111]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We have a simple ionic3 app with lazyloading and IonicPage, we want to load a PopoverPage but this is not working. I get this error:
`view-controller.js:570 PopoverCmp ionViewPreLoad error: No component factory found for PopoverPage. Did you add it to @NgModule.entryComponents?`
I don't know if this is a inoic3 or a problem with lazyloading or perhapse I'm doing something wronk :smile: 

**Expected behavior:**
It should work :smile: 

**Related code:**

```
@NgModule({
    imports: [ IonicModule, IonicPageModule.forChild(HomePage) ],
    declarations: [ HomePage, PopoverPage ],
    entryComponents: [
        HomePage, PopoverPage
    ]
})
export class HomePageModule { }


import { Component } from '@angular/core';
import { NavController, IonicPage, PopoverController } from 'ionic-angular';

@IonicPage()
@Component({
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public popoverCtrl: PopoverController) {}

   presentPopover(ev) {
       let popover = this.popoverCtrl.create(PopoverPage);
       popover.present();
  }
}


@Component({
  template: `
    <ion-list>
            <button ion-item>A</button>
            <button ion-item>B</button>
            <button ion-item>C</button>
        </ion-list>
  `
})
export class PopoverPage {
  constructor() {}
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.2
    Xcode version: Not installed
```

**Comment by danbucholtz** [comment]
Put the Popover page in it's own NgModule and give it an `@IonicPage` decorator. It'll work. It is sort of confusing since a popover isn't a page. We are going to address this in a future release.

Thanks,
Dan

**Comment by mburger81** [comment]
Hi @danbucholtz 
Doing this it will work, but there are also other problems!

```
home/abc/ionic3-content/src/pages/home/popover/popover.component.ts has a 
@IonicPage decorator, but it does not have a corresponding "NgModule" at 
/home/abc/ionic3-content/src/pages/home/popover/popover.component.module.ts 
```
My file structure is
```
popover.component.ts
popover.module.ts
popover.html

```
In this case and only in this case I'm forced to name the module also popover.component.module.ts.
I think this is not standard NgModule and also I think this is not necessarie for other IonicPage components?
Right?

**Comment by mburger81** [comment]
Also I use a ModalController in Popover to change settings, this has the same problem!
I have also to create a new NgModule with a new IonicPage to get it work. This is very stranged and not very usable.
I would create one Module for my PopoverPage where I declare all my Modal Pages, and not create one Module per ModalPage. It's not very usable and I think if we have to do this, you should document this
@brandyscarney @mhartington

**Comment by numerized** [comment]
Hi Guys, 

Same problem here. I then use the old method of declaring components in the app.module

**Comment by thorizer** [comment]
my popover is generated using ionic g page. still not working.

**Comment by mburger81** [comment]
Can you share a code example of your problems?

**Comment by djmMax** [comment]
Hi All,
Please i have a same probleme

ionic info
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v7.5.0
Xcode version: Not installed
```

**Related **
explore-filter.ts
```js
import { Component } from '@angular/core';
import { NavParams, IonicPage } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'explore-filter',
  template: `
    <ion-list>
      <ion-list-header>Ionic</ion-list-header>
      <button ion-item (click)="close()">Learn Ionic</button>
      <button ion-item (click)="close()">Documentation</button>
      <button ion-item (click)="close()">Showcase</button>
      <button ion-item (click)="close()">GitHub Repo</button>
    </ion-list>
`
})
export class ExploreFilter {

  constructor(private navParams: NavParams) {

  }

}
```

explore-filter.module.ts
```js
import { NgModule } from '@angular/core';
import { ExploreFilter } from './explore-filter';
import { IonicPageModule } from "ionic-angular";

@NgModule({
  declarations: [ExploreFilter],
  imports: [IonicPageModule.forChild(ExploreFilter)],
  entryComponents: [ExploreFilter]
})
export class ExploreFilterModule {}
```

home.ts
```js
import { Component } from '@angular/core';
import { PopoverController, IonicPage } from "ionic-angular";
import { ExploreFilter } from "../../components/explore-filter/explore-filter";

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(private popoverCtrl: PopoverController) {
  }

  presentPopover(ev) {
    let popover = this.popoverCtrl.create(ExploreFilter);
    popover.present({
      ev: ev
    });
  }
}
```

**Comment by mburger81** [comment]
@djmMax please share also your Module where you have HomePage included.

**Comment by djmMax** [comment]
HomePage Module

```js
import { NgModule } from '@angular/core';
import { HomePage} from './home';
import { IonicPageModule } from 'ionic-angular';

@NgModule({
  declarations: [HomePage],
  imports: [IonicPageModule.forChild(HomePage)],
  entryComponents: [HomePage]
})
export class HomePageModule { }
```

**Comment by mburger81** [comment]
You have to import your `ExploreFilterModule` in youur `HomePageModule` as for  any other Module.

**Comment by ctc1995** [comment]
@mburger81  Is this problem solved? I have also encountered this problem.

**Comment by mburger81** [comment]
@ctc1995 It depends what do you intend with resolved. As described in this issue by Dan

> Put the Popover page in it's own NgModule and give it an @IonicPage decorator. It'll work. It is sort of confusing since a popover isn't a page. We are going to address this in a future release.
> 
> Thanks,
> Dan

This for now is the solution, I don't think this is changing from the past.

**Comment by lyczos** [comment]
It's working for me but I have to put component name as a string for lazy loading.
`presentPopover(ev) {
        let popover = this.popoverCtrl.create('ContactsPopoverComponent', {});
        popover.present({
            ev: ev
        });
    }`

**Comment by paulappz** [comment]
Please i have same problem. i have tried everything possible. i need quick help before i give up.
This is the error..

$ ionic serve
[INFO] Starting app-scripts server: --port 8100 --p 8100 --livereload-port 35729
       --r 35729 --address 0.0.0.0 - Ctrl+C to cancel
[11:09:18]  watch started ...
[11:09:18]  build dev started ...
[11:09:18]  clean started ...
[11:09:18]  clean finished in 2 ms
[11:09:18]  copy started ...
[11:09:18]  transpile started ...
[11:09:32]  transpile finished in 14.03 s
[11:09:32]  preprocess started ...
[11:09:32]  deeplinks started ...
Error: C:\Users\Paul\Desktop\PP\Ionic3Ang4firebase\src\pages\firelogin\firelogin.ts has a @IonicPage decorator, but it does not have a corresponding "NgModule" at C:\Users\Paul\Desktop\PP\Ionic3Ang4firebase\src\pages\firelogin\firelogin.module.ts

firelogin.module.ts

 import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { FireLoginPage} from '../firelogin/firelogin';


@NgModule({
  declarations: [
    FireLoginPage
  ],
  imports: [
   IonicPageModule.forChild(FireLoginPage)
  ],
  entryComponents: [
   FireLoginPage  
  ]
 
})
export class FireLoginPageModule {}

**Comment by lyczos** [comment]
@paulappz Can you share your **firelogin.ts** file?

**Comment by paulappz** [comment]
Firelogin.ts file

import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HomePage } from '../home/home';
import { SignupServiceProvider } from '../../providers/signup-service/signup-service';
import { EmailValidator } from '../../validators/email';
import { 
  IonicPage, 
  NavController, 
  LoadingController, 
  Loading, 
  AlertController } from 'ionic-angular';


@IonicPage()
@Component({
  selector: 'page-about',
  templateUrl: 'firelogin.html'
})
export class FireLoginPage {

loginForm:FormGroup;
loading:Loading;

  constructor(public navCtrl: NavController, public authData: SignupServiceProvider, 
  public formBuilder: FormBuilder, public alertCtrl: AlertController,
  public loadingCtrl: LoadingController) {

 this.loginForm = formBuilder.group({
        email: ['', Validators.compose([Validators.required, EmailValidator.isValid])],
        password: ['', Validators.compose([Validators.minLength(6), Validators.required])]
      });
    }



     
    loginUser(){
      if (!this.loginForm.valid){
        console.log(this.loginForm.value);
      } else {
        this.authData.loginUser(this.loginForm.value.email, this.loginForm.value.password)
        .then( authData => {
          this.navCtrl.setRoot('HomePage');
        }, error => {
          this.loading.dismiss().then( () => {
            let alert = this.alertCtrl.create({
              message: error.message,
              buttons: [
                {
                  text: "Ok",
                  role: 'cancel'
                }
              ]
            });
            alert.present();
          });
        });

        this.loading = this.loadingCtrl.create({
          dismissOnPageChange: true,
        });
        this.loading.present();
      }
  }

  goToResetPassword(){
    this.navCtrl.push('FireResetPage');
  }

  createAccount(){
    this.navCtrl.push('FiresignupPage');
  }

}

**Comment by ChomalCalcey** [comment]
How can I call a modal from a component? Importing the modal module to component imports doesn't seem to be working.

**Comment by pklime2** [comment]
@ChomalCalcey For some reason I had to import the modal module in my main app.module to get this to work.
