### ISSUE TITLE
ionic 2 menu side change not updating dynamically

### ISSUE THREAD

**Issue by ykonstant** [driftyco/ionic#11116]
We create a menu with ion-menu
<ion-menu [content]="content" side="{{bp.language == 1 ? 'right' : 'left'}}">
      <ion-header class="tparent-bg">
        <ion-toolbar  color="blue" class="tparent-bg">
        <div style="height:4vw;"></div>
        <div class="userimg page-logo" style="background-image: url(assets/icon/user.png);" *ngIf="!up.image"></div>
        <div class="userimg page-logo" [ngStyle]="{'background-image': 'url('+bp.imgUrl+'profile_pictures/' + up.image + ')'}" (click)="selectPic()" *ngIf="up.image"></div>

        <div class="name bold">{{up.name}}</div>
        </ion-toolbar> 
    </ion-header>

    <ion-content>

		<ion-list inset class="customarrow">
            <button menuClose ion-item (click)="dashboard()"><ion-icon class="custom item-name" color="danger" name="ios-home" item-left></ion-icon>{{'Dashboard' | translate}}</button>
            <button menuClose ion-item (click)="profile()"><ion-icon class="custom my-profile" name="person" item-left></ion-icon>{{'My Profile' | translate}}</button>
			<button menuClose ion-item (click)="wallet()" *ngIf="up.type==1"><ion-icon class="custom amout-charge-for-itemOrange " name="person" item-left ></ion-icon>{{'My Wallet' | translate}}</button>
			<button menuClose ion-item (click)="language()"><ion-icon class="custom language" name="call" item-left></ion-icon>{{'Language' | translate}}</button>
            <button menuClose ion-item (click)="placeorder()" *ngIf="up.type==1"><ion-icon class="custom place-an-order" name="call" item-left></ion-icon>{{'Place an order' | translate}}</button>
            <button menuClose ion-item (click)="staticpage(2)"><ion-icon  class="custom privacy-policy" name="call" item-left></ion-icon>{{'Privacy Policy' | translate}}</button>
            <ion-item>
                    <ion-icon class="custom notifications" name="ios-home" item-left></ion-icon>
                    <ion-label>{{'Notifications' | translate}}</ion-label>
                    <ion-toggle class="custom" color="danger" [(ngModel)]="up.notification" (ionChange)="logEvent($event)"></ion-toggle>
            </ion-item>

            
			<button menuClose ion-item (click)="gotoorders()" *ngIf="up.type==2"><ion-icon class="custom order-details" name="call" item-left></ion-icon>{{'Order Details' | translate}}</button>
            <button menuClose ion-item (click)="gototransactions()" *ngIf="up.type==2"><ion-icon class="custom transaction-detial" name="log-out" item-left></ion-icon>{{'Transaction Details' | translate}}</button>

            <button menuClose ion-item (click)="staticpage(1)"><ion-icon class="custom about-us" name="paper" item-left></ion-icon>{{'About Us' | translate}}</button>
            <button menuClose ion-item (click)="staticpage(3)"><ion-icon class="custom contact-us" name="call" item-left></ion-icon>{{'Contact Us' | translate}}</button>
			  
            <button menuClose ion-item (click)="logout()"><ion-icon class="custom logout" name="log-out" item-left></ion-icon>{{'Logout' | translate}}</button>
        </ion-list>
        <div style="height: 30vw"></div>
    </ion-content>

</ion-menu>

And set menu side 'left' & 'right' on basis of app default language
But after updating language it not update the side of menu, however after we restart the app then it updated

Please provide us a solution for this

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
