### ISSUE TITLE
breaking-change(item): Add item-start & item-end

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11124]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
To put something in the right side of the item, you currently do: `item-right`, and to put something in the left side: `item-left`.
However, on RTL, `item-left` is actually in the right side, and `item-right` is in the left side.

**Expected behavior:**
While I agree with mirroring behaviour like this, I think that to avoid some confusion, having:
`item-start` = `item-left`
`item-end` = `item-right`
Will be more descriptive for RTL users, just like in `ion-navbar`, where we have `start` and `end` and not `left` and `right`

**Comment by manucorporat** [comment]
I agree with you @AmitMY

can you prepare a PR that is back-compatible with the current API?

We might not merge it just in this release, but we will do soon for sure :)

**Comment by AmitMY** [comment]
@manucorporat Thanks for the confirmation. I can make a PR, but I will wait for feedback for my currently open PR, just to see I don't break lot's of styles and stuff (learn from mistakes instead of doing twice)

**Comment by mburger81** [comment]
Good idea

**Comment by AmitMY** [comment]
@manucorporat Done, I of course don't expect a fast merge for a breaking change, just putting it out there

**Comment by AmitMY** [comment]
Merged
