### ISSUE TITLE
Generated page does not have 'Page' as part of its class name, the old feature is better, should have it back

### ISSUE THREAD

**Issue by gengjunwu** [driftyco/ionic#11129]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Use the page generation command
```
$ ionic g page genTest
```
to generate a new page called gen-test, open the .ts file, the class name does not have 'Page' as part of class name any more.

```
export class GenTest {}
```

**Expected behavior:**
```
export class GenTestPage {}
```

**Steps to reproduce:**
* Start a new Ionic app
```
ionic start newApp blank --v2
```
* Run page generation command
```
ionic g page genTest
```
* Go to the generated page folder and open gen-test.ts file, you should see the class name does not have 'Page' text as part of class name any more.

**Other information:**
I have noticed that this is caused due to the release of Ionic 3 on ionic/scripts/templates/page/ts.tmpl file [commit #3058482](https://github.com/driftyco/ionic/commit/305848274d6226c9abb5530bce2bdadcaaf2b4b3#diff-50d78f7db8f2c888bfdb84bae5b2ed1d) on 16Mar 2017, which removed the text 'Page' form '$CLASSNAME'.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.8.0
Xcode version: Not installed
```
 **Suggestion**
I'm not sure if 'Page' was removed intentionally from class name when Ionic upgraded, the default boilerplate for any starter template still has 'Page' as part of home page's class name, It is super convenient to have it back if possible so that we know it is a page that we are importing while using.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2073
