### ISSUE TITLE
(bug) Updated Ionic 2.2.0 to 3.0.1 and now ionic build ios fails with error 65

### ISSUE THREAD

**Issue by eduardoRoth** [driftyco/ionic#11120]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating my project from Ionic 2.2.0 to 3.0.1 the command ionic build ios fails with the following error:

```
Error: Error code 65 for command: xcodebuild with args
```

I've tried opening the project in xCode and I get a warning about using old Swift code. After I update it, I get a lot more errors.

The plugins that I'm using are:

```
  <plugin name="cordova-plugin-uniquedeviceid" spec="~1.3.2"/>
  <plugin name="cordova-plugin-x-toast" spec="~2.6.0"/>
  <plugin name="cordova-plugin-spinner-dialog" spec="~1.3.1"/>
  <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.7"/>
  <plugin name="de.appplant.cordova.plugin.local-notification" spec="~0.8.4"/>
  <plugin name="cordova-plugin-geolocation" spec="~2.4.2"/>
  <plugin name="cordova-plugin-geofence" spec="~0.6.0"/>
  <plugin name="cordova-plugin-contacts" spec="~2.3.0"/>
  <plugin name="cordova-plugin-camera" spec="~2.4.0"/>
  <plugin name="mx.ferreyra.callnumber" spec="~0.0.2"/>
  <plugin name="cordova-base64-to-gallery" spec="~4.1.2"/>
```

**Expected behavior:**
ionic build ios to complete successfully

**Steps to reproduce:**
Create a new ionic project v2.2.0
Update it to v3.0.1
Install the plugins listed above
Run ionic build ios

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by denzelwamburu** [comment]
Am having the same issue too. 
Any reason for the error?

**Comment by eduardoRoth** [comment]
For me it was the Geofencing plugin that doesn't support Swift 3 and causes
this error.

**Comment by denzelwamburu** [comment]
Mine seems to work, I uploaded the app to ionic cloud and tried to build it
again, and seems to be fine.
