### ISSUE TITLE
focusFirstInput (Modal) doesn't work on Android

### ISSUE THREAD

**Issue by zelphir** [driftyco/ionic#1112]
I was able to make it working on iOS adding `<preference name="KeyboardDisplayRequiresUserAction" value="false" />` in the `config.xml`. 

I don't how to do on Android, I've tried to use this cordova plugin (`https://github.com/phonostar/PhoneGap-SoftKeyboard.git`) but it doesn't work. Suggestions?

**Comment by hypery2k** [comment]
together with the [IonicKeyboard Plugin](https://github.com/driftyco/ionic-plugins-keyboard) I found a working solution on iOS 7+ and Android 4.4+ by using a directive
```
/**
 * @ngdoc directive
 * @name isFocused
 * @module flynnBookScannerApp
 * @description gives focus the the element, can be used as attribute
 */
app.directive('isFocused', function($timeout) {
	return {
		scope: {
			trigger: '&isFocused'
		},
		link: function(scope, element) {
			if (scope.trigger()) {
				$timeout(function() {
					element[0].focus();
					element[0].click();
					cordova.plugins.Keyboard.show();
				});
			}
		}
	};
});
```
in HTML
```
<input type="search" data-ng-model="searchQuery.fullTextSearch"  is-focused="true"
	    		   placeholder="Type keywords to search ...">
```
and this config.xml:
```
<?xml version='1.0' encoding='utf-8'?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" 
...
    <preference name="fullscreen" value="false" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
</widget>

```
See the full example [here](https://github.com/holisticon/flynn-book-scanner/commit/f2ab2c8a4ceaa6c99baf6c5cdfceda079ee5b433):

**Comment by itree** [comment]
Hey guys, 

I have followed hypery2k's instruction.  But it is still not working in iOS7.  I am using
ionic --version
1.3.22

**Comment by itree** [comment]
where am I suppose to put the  
app.directive

in app.js?  Such as? 



angular.module('starter', ['ionic', 'starter.controllers'])

.directive('isFocused', function($timeout) {
    return {
        scope: {
            trigger: '&isFocused'
        },
        link: function(scope, element) {
            if (scope.trigger()) {
                $timeout(function() {
                    element[0].focus();
                    element[0].click();
                    cordova.plugins.Keyboard.show();
                });
            }
        }
    };
})

**Comment by itree** [comment]
Hey guys, I figure it out.  It is working, but it doesn't work in the PhoneGap Developers App.  Just a FYI
