### ISSUE TITLE
Unable to copy asset information

### ISSUE THREAD

**Issue by Klerith** [driftyco/ionic#11135]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
As soon I start typing on a simple Input text I get this error on and ios device (android still shows some similar issue):

2017-04-08 12:20:23.541751 8gag[11139:3416979] 0x17414ad40 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x17414ad40> { count = 1, transaction: 0, voucher = 0x0, contents =
	"Result" => <int64: 0x1740373a0>: 29
}
2017-04-08 12:20:23.542573 8gag[11139:3416979] 0x17414ba50 Daemon configuration query reply: XPC_TYPE_DICTIONARY  <dictionary: 0x17414ba50> { count = 2, transaction: 0, voucher = 0x0, contents =
	"Dictionary" => <dictionary: 0x17414bb00> { count = 1, transaction: 0, voucher = 0x0, contents =
		"ServerURL" => <dictionary: 0x17414bbb0> { count = 3, transaction: 0, voucher = 0x0, contents =
			"com.apple.CFURL.magic" => <uuid: 0x174440150> C3853DCC-9776-4114-B6C1-FD9F51944A6D
			"com.apple.CFURL.string" => <string: 0x174440180> { length = 30, contents = "https://mesu.apple.com/assets/" }
			"com.apple.CFURL.base" => <null: 0x1b0277e80>: null-object
		}
	}
	"Result" => <int64: 0x174037100>: 0
}
2017-04-08 12:20:23.543236 8gag[11139:3416979] [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker

The input works, I can get the value, but as soon I get that error, plugins like Image Picker seems to be out of the Angular Detection cycle.

If I don't type anything, the plugin works and I can get and see the image on the app

**Expected behavior:**
Just type some text and then pick and image... 

**Steps to reproduce:**
Just create an input then an image picker, this error only appear on devices. I am getting a 64 image string btw

**Related code:**
Nothing fancy here:
Just a:

```
<ion-item>

    <ion-label>Titulo</ion-label>
    <ion-input type="text"
              [(ngModel)]="title">
    </ion-input>

  </ion-item>


  <button ion-button
          block
          [disabled]="title.length <2"
          (click)="next()">
    Siguiente
  </button>
```

The next event, pushes a new page where the user can pick an image

```
<ion-content padding>

  <ion-list>

    <ion-item *ngIf="img">
      <img src="data:image/png;base64,{{img}}">
    </ion-item>

  </ion-list>

  <button ion-button
          block
          (click)="pick_image()">
    Seleccionar imagen
  </button>

</ion-content>
```

**Ionic info:** 

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra

Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by hectorggp** [comment]
Please guys, put here a link to the solution, I have the same issue. @jgw96 @Klerith

**Comment by paragw09ckp** [comment]
@Klerith - can you share the link to your posts on other forums @jgw96 suggested?

I am also facing the same issue.

**Comment by paragw09ckp** [comment]
Never mind, got past it. I followed this: https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs/39461256#39461256
