### ISSUE TITLE
Google Analytics - cordova_not_available

### ISSUE THREAD

**Issue by mikeborozdin** [driftyco/ionic#11139]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
An error in the browser screen:

```
Runtime Error
Uncaught (in promise): cordova_not_available
```

**Expected behavior:**
No error. I should be able to see  my application

**Steps to reproduce:**
1. Create a new Ionic 3 project (I used `ionic start --v3 myApp`)
2. Follow the steps from https://ionicframework.com/docs/native/google-analytics/
2.1 ionic plugin add cordova-plugin-google-analytics
2.2 npm install --save @ionic-native/google-analytics
2.3. Add the sample snippet code
2.4 Run `ionic serve`

**Related code:**

```
platform.ready().then(() => {
      this.ga.startTrackerWithId(myCode).then(() => {
        statusBar.styleDefault();
        splashScreen.hide();
      });
    });
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1353
