### ISSUE TITLE
bug(scroll): does not scroll when remote debug is attached

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11137]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Running an app with `ion-menu` on Galaxy S4 with Android 5.0.1 does not allow for menu scroll.
If I open the browser remote debug, using the scrolwheel does not scroll, but holding mouse and dragging up and down does scroll.

**Expected behavior:**
Scroll away

**Other information:**
Works on iOS

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Are you using any kind of `press` or `touch` events in that menu?

**Comment by AmitMY** [comment]
@jgw96 I only have an ion-list
With 'button ion-item (click)="openPage(page)" tappable'

**Comment by jgw96** [comment]
Hello @AmitMY , is this still an issue with ionic 3.1.1?

**Comment by AmitMY** [comment]
@jgw96 Correct.
This happens only when remote debugging from chrome, so its a minor issue.
I just now realised that after attaching remote dev tools, no scrollable content is scrollable anymore.

**Comment by jgw96** [comment]
Hmm thats interesting @AmitMY . Good find!
