### ISSUE TITLE
Allow modals to be 'pushed'

### ISSUE THREAD

**Issue by jacob-cross99** [driftyco/ionic#11136]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have to add a 'back button' to the navbar header in the modal's template which sends the ViewController's dismiss with an empty response. If I was able to simply just send the value of 'push' with a callback with data to enable a back button which responds with an empty response upon being clicked then I wouldn't have to modify such a thing anymore. I think this method is very efficient since I can create services for things like selecting payment methods which return a response of the selected payment method and have it look like a normal page with a push event. 

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ion-header>
  <ion-navbar>
    <ion-buttons start mode="ios">
      <button ion-button icon-only (click)="back()">
        <ion-icon name="arrow-back"></ion-icon>
      </button>
    </ion-buttons>
    <ion-title>Add credit card</ion-title>
    <ion-buttons end>
      <button ion-button (click)="save()">
        Save
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

back() {
    this.viewCtrl.dismiss({canceled: true});
}

save() {
  ....
}
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#166
