### ISSUE TITLE
[2.3.0 and 3.0.1] ion-scroll on iOS (WkWebView) not scrollable

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#11134]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**
Scrolling in an ion-scroll on iOS (WkWebView) doesn't work respectively ion-scroll looks frozen / can't be scrolled

Related issues:

https://github.com/driftyco/ionic/issues/10938

https://github.com/driftyco/ionic/issues/10936

Notes:

I use WkWebView.

I use to solve that issue in Ionic 2.3.0 and 3.0.0-beta by enabling the enableScrollListener() on the content by myself but this method doesn't exists anymore in Ionic 3.0.1 aka I use to solve that issue like following:

    ionViewDidEnter() {
       content.enableScrollListener();
    }

**Expected behavior:**

A fix for the ion-scroll scrolling or a redo of the method content.enableScrollListener()

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.3 Build version 8E162

**Comment by manucorporat** [comment]
what does "Scrolling in an ion-scroll on iOS (WkWebView) still doesn't work" mean? it does not scroll? or the scroll events are not being dispatched?

**Comment by peterpeterparker** [comment]
@manucorporat with "scrolling doesn't work" I meant that the ion-scroll can't be scrolled, like "frozen". 

something like following works fine with ionic serve or on a android phone but doesn't on iOS

    <ion-scroll scrollY="true">
         <ion-list padding>
               <ion-item>
                   <p>1</p>
               </ion-item>
              ....
               <ion-item>
                   <p>9999</p>
               </ion-item>
         </ion-list>
     </ion-scroll>

**Comment by peterpeterparker** [comment]
Even if I meet the error "only" after having upgraded to Ionic 3 and nothing on my app side, it seems that the bug should be on me. I built another minimal app and it seems to work, the ion-scroll is scrollable on ios. Therefore I close this issue and only if needed gonna open a new one.

**Comment by peterpeterparker** [comment]
Found the problem. After upgrading to Ionic 3, at least in my case, the swipe event on an ion-list in an ion-scroll freeze my scroll.

    <ion-scroll scrollY="true">
     <ion-list padding (swipe)="someThing($event)"> 
           <ion-item>
               <p>1</p>
           </ion-item>
          ....
           <ion-item>
               <p>9999</p>
           </ion-item>
         </ion-list>
      </ion-scroll>
