### ISSUE TITLE
Readme love

### ISSUE THREAD

**Issue by snewell92** [driftyco/ionic#11149]
Whenever you increment version numbers (especially major version numbers) the readme should keep up. It's awkward to have "*npm package | 3.0.1*" and "*Ionic 2*" on the same page.

Some suggestions:
 - Make `README.md` version agnostic (change the **"Building Apps with Ionic 2"** text)
 - Ensure all links refer to version agnostic materials
 - Make documentation part of the release (instead of just a blog post - although in some cases a blog post might be all that is needed, this might be one of those cases)

-----

**Suggested Code** (for the third sentence/paragraph in the readme)

```
See [these slides](http://adamdbradley.github.io/building-with-ionic2) for a quick
overview, or watch our [Crash Course](https://youtu.be/O2WiI9QrS5s) video for a
quick walkthrough on how to get started using Ionic.
```

-----

Thanks for reading. Keep making great things 😄

**Comment by jgw96** [comment]
Fixed with this commit https://github.com/driftyco/ionic/commit/902f5f7c1fdf6b6b5b5552d0b611b9ef4ab07ffd . Thanks for opening an issue with us! Its #justionicnow 😄

**Comment by mburger81** [comment]
Great :)
