### ISSUE TITLE
iOS webView load delay

### ISSUE THREAD

**Issue by hope7th** [driftyco/ionic#11142]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

in the ios webview i write like this ;
on the webview nav backButton:
[self.backButton addTarget:self action:@selector(webViewBack:) forControlEvents:UIControlEventTouchUpInside];
-(IBAction)webViewBack:(id)sender{
 NSString *jsStr = [NSString stringWithFormat:@"this.document.getElementById('loginButton').click()"];
[_webView stringByEvaluatingJavaScriptFromString:jsStr];
}

and in my  ionic app write like this 
<button ion-button name="loginButton"  style="display: none" (click)="visibleClick()" >点击</button>
 visibleClick(){
    this.app.getActiveNav().pop();
  }
but when it's about 2or3 Second delay i click the webview backButton,it can work,otherwise it cann't work,can u give me some infomession;

waiting for u

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
