### ISSUE TITLE
Get "White flash" when refresher start!

### ISSUE THREAD

**Issue by markisme** [driftyco/ionic#11144]
**Ionic version:**  (check one with "x")
- [ ]  **1.x**
- [x]  **2.x**
- [ ]  **3.x**

**I'm submitting a ...**  (check one with "x")
- [x]  bug report
- [ ]   feature request
- [ ]   support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I created an page with ion-refresher, And other more elements.On ios when I pull down to active the refresh, when the refresher appeared, the whole page get an white flash. Then I Debug the page with safari. I found the onMove function in refresher invoked ` content.setScrollElementStyle(...) `, And maybe it is that which cause the whole page to redraw.
**Expected behavior:**

When use refresher.the pull down operate should be smoothly.

**Steps to reproduce:**

1. create a page with a refresher and other more elements, simple page maybe not show the flash obviously.
2. initiate a touchdown event, and start scrolling down so the refresher is activated
3. on iOS, you will see the entire page flashing

And i find that related issue https://github.com/driftyco/ionic/issues/7429
`ionic info` of my system : 
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.1
ios-deploy version: 1.9.0 
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) and seeing if that fixes the issue for you?

**Comment by markisme** [comment]
@jgw96 It's working, there is no flash with wkwebview. But i'm stuck in the `XHR` error when i send http request to my web server...
