### ISSUE TITLE
feat: ion-item-sliding active-toggle would be awesome

### ISSUE THREAD

**Issue by Bubbi** [driftyco/ionic#11146]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>For apps supporting anonymous and logged-in users, it would be nice to have some sort of toggle functionality / or active state on ion-item-sliding, so if the user is logged in, he has the sliding feature activated for added functionality, while anonymous users don't have these options available.

Currently we pretty much only have the option to have two almost identical lists, where one of them have the item-sliding and item-options while the other omits these.

The other option would be to hide / remove the ion-item-options, but that would still give the sliding feature - which would probably make the user think that there's a bug in the app since he is somehow missing features.

a simple toggle attribute. Name could be "active", "activated" or something like that.

This way we could write the code as follows:

<ion-item-sliding *ngFor="let item of items" [active]="isLoggedIn()">

It might not necessarily be because of logged-in state, but could be useful in many situation (owner of list vs. all others), where it could make the template code more simple.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#165
