### ISSUE TITLE
perf: Login with mysql

### ISSUE THREAD

**Issue by makhtout** [driftyco/ionic#11143]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>looking for a script for login between ionic 2 angular 2 (TS) And php Mysql</span>

<span is-issue-template></span>

**Comment by ghenry22** [comment]
you should really ask on the ionic forums or do a bit of reading, this area is for bug reports and not the right place for these type of questions

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
