### ISSUE TITLE
ionic menu - Tap/Click not listened during 2.5s after opening menu (iOS)

### ISSUE THREAD

**Issue by action-script** [driftyco/ionic#11145]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On devices (tested on iOS), tapping outside the menu area is being ignored during [2500ms](https://github.com/driftyco/ionic/blob/master/src/tap-click/tap-click.ts#L256) right after opening the menu.
The menu can not be closed by clicking back on the visible app area, right after opening the menu, causing non responding effect, or that there is not possibility to close the menu by tapping outside of it.

The event propagation is being prevented by the ionic '[tap-click](https://github.com/driftyco/ionic/blob/master/src/tap-click/tap-click.ts#L136)' module. So there is neither possibility of listening or detecting the event in your own app code.

**Expected behavior:**
The menu should be able to be closed immediately after is opened, so there is a fluid navigation instead of a glitch effect or a bad response behaviour.

The events should be able to be listened/triggered by the rest of the app code, so we can have control over the user interactions.

**Steps to reproduce:**
1. Start a new (SideMenu) ionic project with ionic v2 or v3.

```sh
$ ionic start myApp sidemenu --v2
```
2. Run the project on an iOS device.
3. Click on the burger menu icon to open the side menu.
4. Then, click outside of the menu area before the 2.5s right after the menu is opened.

**Related code:**
Tracking the issue, I found the '[click-tap](https://github.com/driftyco/ionic/blob/master/src/tap-click/tap-click.ts)' module being the responsible of that behaviour.

```javascript
click(ev: any) {
    if (this.shouldCancelClick(ev)) {
        ev.preventDefault();
        ev.stopPropagation();
        return;
    }
    ...
}

private shouldCancelClick(ev: any): boolean {
    if (this.usePolyfill) {
        if (!ev.isIonicTap && this.isDisabledNativeClick()) {
            console.debug('click prevent: nativeClick');
            return true;
      }
      ...
  }

isDisabledNativeClick() {
    return this.disableClick > Date.now();
}
```

**Other information:**
The issue behaviour is only reproducible if the menu is opened after a click event. (menuToggle, MenuController:open ), not if the menu is opened swiping or after a callback or time event.
Has been tested on native iOS devices. Not reproducible on pc or device browsers.

Also tested on ionic 2 and 3, with ionic-angular 2.0.0-rc.4 and 3.0.1 and with @ionic/app-scripts 1.0.0 and 1.3.0.

I'm not sure if this is a desired behaviour and is developed on purpose, or is an bug caused by another event management.

**Ionic info:** 
```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. So this click blocking is required at the moment on UiWebView because of UI having broken scroll events. We are currently at work on pushing [WkWebView](https://github.com/driftyco/cordova-plugin-wkwebview-engine) to be the default iOS webview for Ionic apps. Because WkWebView does not have broken scroll events we are able to use native scrolling just like we have on Android, which means that we do not have to do fancy click blocking such as the above. Would you mind installing the wkwebview plugin i linked to above and giving that a try? Thanks!

**Comment by action-script** [comment]
Hi Justin,
Thanks for the reply.
**Yes, with the WkWebView plugin, the menu events works perfectly.**
I already tried using WkWebView at the project before for canvas/render performance reasons. But there are still several limitations and issues with the viewer that makes our project not compatible with Wk.
So, sadly we have to continue developing under UiWebView and figure out a way to fix the event issues.
Looking forward to a fully integration for Wk as default iOS webview.

Thanks!

**Comment by jgw96** [comment]
Hey @action-script , thanks for the reply! Would you be able to expand on the issues you are seeing with the latest version of the plugin? It is now to the point where we are planning on making it the default iOS webview in the next release.

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
