### ISSUE TITLE
Text above ion-grid is not breaking between words

### ISSUE THREAD

**Issue by EWBears** [driftyco/ionic#11159]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Text between `<p> </p>` tags above an ion-grid is breaking on whatever letter is reached before hitting the edge of the ion-content area.

**Expected behavior:**
Text will automatically break between words.

**Steps to reproduce:**

**Related code:**
Put the following code in to a blank template and you will be able to reproduce this bug (I am not familiar with plunkr, sorry)

```
<ion-content padding>
<p ion-text color="blu"><b>Reading Practice:</b></p>

<p>Now we're going to put the consonants and vowels together to create words.  Try reading each of the words below to practice reading Romanized Thai. Don't worry about pitch/tones yet – we'll get to that in just a minute! </p>

<p>Tap on the box to hear the correct pronunciation.  If you're having trouble, go back to the previous pages and look for pronunciation help.</p>

<ion-grid class="gri" no-padding>

<ion-row class="a">

<ion-col class="bor"><button ion-item no-lines text-wrap color="whi">test1</button></ion-col>
<ion-col class="bor"><button ion-item no-lines text-wrap color="whi">test2</button></ion-col>
<ion-col class="bor"><button ion-item no-lines text-wrap color="whi">test3</button></ion-col>
<ion-col class="bor"><button ion-item no-lines text-wrap color="whi">test4</button></ion-col>

</ion-row>

</ion-grid>
<p></p>
</ion-content>
```

**Other information:**

Buttons on my grid have tap events (removed for this example) with nativeaudio plugin but I don't think it's relevant here.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by EWBears** [comment]
Sorry I didn't realize that my copy and pasted code turned into markdown text. 

Here is img showing break between words: [imgur link]( http://imgur.com/pbCuqej)

 Here is the code:

`<ion-content padding>
<p ion-text color="blu"><b>Reading Practice:</b></p>

<p>Now we're going to put the consonants and vowels together to create words.  Try reading each of the words below to practice reading Romanized Thai. Don't worry about pitch/tones yet – we'll get to that in just a minute! </p>

<p>Tap on the box to hear the correct pronunciation.  If you're having trouble, go back to the previous pages and look for pronunciation help.</p>

<ion-grid class="gri" no-padding>

<ion-row class="a">

<ion-col class="bor"><button ion-item (tap)="playt22a1()" no-lines text-wrap color="whi">dii</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a2()" no-lines text-wrap color="whi">gaw</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a3()" no-lines text-wrap color="whi">khaao</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a4()" no-lines text-wrap color="whi">hen</button></ion-col>

</ion-row>

<ion-row class="b">

<ion-col class="bor"><button ion-item (tap)="playt22a5()" no-lines text-wrap color="gra">khit</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a6()" no-lines text-wrap color="gra">saam</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a7()" no-lines text-wrap color="gra">nguu</button></ion-col>
<ion-col class="bor"><button ion-item (tap)="playt22a8()" no-lines text-wrap color="gra">roht</button></ion-col>

</ion-row>

</ion-grid>`

**Comment by brandyscarney** [comment]
@EWBears Thanks for the issue! I'm not able to reproduce this using the conference app. Do you have any custom styles that could be interfering with it? Which browser/device and screen size is this at?

<img width="730" alt="screen shot 2017-04-11 at 9 54 18 am" src="https://cloud.githubusercontent.com/assets/6577830/24915534/084ea370-1e9d-11e7-8907-65d202328c9b.png">

**Comment by EWBears** [comment]
Thanks for looking into this, Brandy.  I don't have any custom styles on my text, though I do have custom styles on my grid, as evidenced in the attached code.  The grid styling must be the issue here.

I have many other grids in my app that have text above and below them with the line breaks acting as expected, so it must be something with this grid in particular.  

I don't think that this issue is related to my browser or device since I was able to produce the result from the image in safari 10.0.2, in ionic serve, and also in ionic serve --lab and in an xcode simulator on ios 10.2 and iphone SE.

I will close the issue and look into my grid styling to see if I can identify the cause.  Thanks again!
