### ISSUE TITLE
nav.getActive() returns class name not IonicPage.name value

### ISSUE THREAD

**Issue by thierce** [driftyco/ionic#11153]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

nav.getActive() returns object with value name set to the Class Name of the page

**Expected behavior:**
It would be handy in Ionic3 to also return the segment name or IonicPage decorator so that it could be compared to the  page.component reference.

**Related code:**

```
console.log("GET ACTIVE PAGE: "+this.nav.getActive().name)
```
returns class name eg: HomePage
Would like to return segment eg: 'home' as well, in the object
Something like: this.nav.getActive().segment

```
 Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.10.0
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#167

**Comment by AndyClausen** [comment]
This should be reopened. It's ridiculous that we cannot use the IonicPage-name for anything other that push() pretty much.
Please resolve this issue, quickly.
