### ISSUE TITLE
Show loading before data retrieved from database, loader dismiss after all data show in the page...

### ISSUE THREAD

**Issue by chenlitchian** [driftyco/ionic#11161]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The page show blank before data load finished.

**Expected behavior:**

I want to show loading before all the data retrieve from database.

**Steps to reproduce:**

**Related code:**

let loader = this.loadingCtrl.create({
      spinner : 'bubbles',
      content : `Loading...`
    });
    loader.present().then(() => {
       this.myUserId = firebase.auth().currentUser.uid; 
    this.user = af.database.object('/user/' + this.myUserId);
    this.user1 = af.database.object('/user/' + this.myUserId, { preserveSnapshot: true });

   
    this.subscription = this.user1.subscribe(snapshot => {
      console.log('current user key',snapshot.key);
      console.log('current user',snapshot.val());
       this.currentUser = snapshot.val();
    this.currentUser.key = snapshot.key;
    this.userPhotoUrl = this.currentUser.photo; //get user photo
    this.userDisplayName = this.currentUser.username;
    this.userContact = this.currentUser.contact;
    this.userName = this.currentUser.username;
    this.userEmail = this.currentUser.email;
    this.userSchool = this.currentUser.school;
    });
    
     
    this.myPhotosRef = firebase.storage().ref('/UserPhotos/');
    this.myUserProfile = firebase.database().ref('user');
    
      loader.dismiss().then(() => {
        console.log("Loading dismissed");
      });
    })
   
    
    

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
