### ISSUE TITLE
new version of ionic 2.2.2 not functioning?

### ISSUE THREAD

**Issue by samever7** [driftyco/ionic#11166]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X  ] **2.x**
[] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic start command never establish a tunnel to downlad ionic2-app-base zip file.
npm works fine, git works fine.

And what is the IP address of 0.0.31.64 ?

**Expected behavior:**

should create an app.

**Steps to reproduce:**

ionic start testtest --v2 
**Related code:**

```
insert any relevant code here
```

**Other information:**

Creating an Ionic 2.x app in /Users/user/tmp/ttt based on the tabs template.

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.64:80 - Local (ipaddress:53903)
    at ClientRequest.onError (/usr/local/lib/node_modules/ionic/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
