### ISSUE TITLE
ion-list not refreshed onQuestionChange or onQuestionClick

### ISSUE THREAD

**Issue by N4vros** [driftyco/ionic#11163]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If i use onQuestionChange or onQuestionClick and i change the selected item manually inside one of these functions the ion-list is not refreshed.
I know it's a weird use case but i need to clear one or all values in a ion-list (multiselect or not) and i can't disable the items because i know after if the value is wrong.

**Expected behavior:**
The ion-list must be refreshed like Angular do for a standard list.

**Steps to reproduce:**
I made a Plunker : https://plnkr.co/edit/1vGLJsYQTBgMTCuJizpI?p=preview
When you click on YES or NO the ion-list must be alway empty but as you can see the ion-list is not updated.

**Related code:**

```
<ion-list radio-group [(ngModel)]="choice" (ionChange)="onQuestionChange($event)">
    <ion-item *ngFor="let item of choicelist">
        <ion-label>{{ item.name }}</ion-label>
        <ion-radio value="{{ item.value }}" (click)="onQuestionClick($event)"></ion-radio>
    </ion-item>
</ion-list>
  
<div>{{ choice === null ? 'null' : choice }}</div>
```

```
choicelist: { name: string, value: number }[];
choice: number;

constructor(
	    public navCtrl: NavController,
	    public cdRef: ChangeDetectorRef
) {
	  this.choice = null;
          this.choicelist = [{ name: 'YES', value: 1 }, { name: 'NO', value: 0 }]
}
	
onQuestionChange(value) {
	  this.choice = null;
	  this.cdRef.detectChanges(); // TRY FORCE REFRESH
	  /* heavy solution
	  let tmp = this.choicelist;
	  this.choicelist = [];
	  this.cdRef.detectChanges(); // FORCE REFRESH
	  this.choicelist = tmp;
	  this.cdRef.detectChanges(); // FORCE REFRESH
	  */
}
	
onQuestionClick(event) {
	  event.preventDefault(); // TRY PREVENT CLICK BUT DO NOTHING
	  event.stopPropagation(); // TRY STOP PROPAGATION BUT DO NOTHING
	  this.choice = null;
	  this.cdRef.detectChanges(); // TRY FORCE REFRESH
	  /* heavy solution
	  let tmp = this.choicelist;
	  this.choicelist = [];
	  this.cdRef.detectChanges(); // FORCE REFRESH
	  this.choicelist = tmp;
	  this.cdRef.detectChanges(); // FORCE REFRESH
	  */
}
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement your custom functionality i will urge that you ask this question on our [forum] (https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
