### ISSUE TITLE
lazy load error in production environment.

### ISSUE THREAD

**Issue by dPary** [driftyco/ionic#11160]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I got an Error when useing lazy load in production environment.
**Expected behavior:**

**Steps to reproduce:**

It's all right when i run "ionic serve",but in production environment,it throw an error like:"ERROR Error: Uncaught (in promise): Error: Cannot find module '../pages/fir/fir.module'."

**Related code:**

```
//app.module.ts
    IonicModule.forRoot(MyApp, { swipeBackEnabled: true, preloadModules: true },
      {
        links: [
          { name: 'page-fir', loadChildren: '../pages/fir/fir.module#FirModule' },
          { name: 'page-sec', loadChildren: '../pages/sec/sec.module#SecModule' }
        ]
      }

    )
```

```
//home.ts
  goToPage(val) {
    this.navCtrl.push(val);
  }
```

```
//home.html
    <button ion-button round (click)="goToPage('page-fir')">goToPageFir</button>
    <button ion-button round (click)="goToPage('page-sec')">goToPageSec</button>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
