### ISSUE TITLE
Ionic2 Swipe up and swipe down is not working, its only panup and panright is working

### ISSUE THREAD

**Issue by raghulintelizign** [driftyco/ionic#11171]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by raghulintelizign** [comment]
Thanks for your helping, I am waiting for your response

**Comment by Cdvalencia** [comment]
[this](https://www.npmjs.com/package/ionic-swipe-all) is nice

**Comment by subhaxelpmoc** [comment]
<div swipeAll 
  (swipe)="swipeAll($event)"
  (swipeleft)="swipeLeft($event)"
  (swiperight)="swipeRight($event)"
  (swipeup)="swipeUp($event)"
  (swipedown)="swipeDown($event)"
>


  swipeRight(event: any): any {
    this.navCtrl.pop(  { animate: true, animation: 'transition', duration: 1500, direction: 'back' })
      console.log('Swipe Right', event);
  }
  swipeUp(event: any): any {
    
    this.navCtrl.push(TwoPage,  { animate: true, animation: 'transition', duration: 2500, direction: 'forward' })
      console.log('Swipe Up', event);
  }
  swipeDown(event: any): any {
    console.log('Swipe Down', event);
}
swipeLeft(event: any): any {
  this.navCtrl.push(TwoPage,  { animate: true, animation: 'transition', duration: 2500, direction: 'forward' })
  console.log('Swipe Up', event);
}

npm install --save ionic-swipe-all
in my case swipeup and down not working  can any one help me ..tnx in advance
