### ISSUE TITLE
__webpack_require is not a function in upgrade to v3.0.1

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic#11178]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Upgrade app to v3.0.1 and run in lab

**Expected behavior:**
Running.
How can this be debugged further?

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

![capture054](https://cloud.githubusercontent.com/assets/140737/24942556/9aea3280-1f06-11e7-8f39-7806639797d3.png)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#891

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2083
