### ISSUE TITLE
menuToggle directive hide the buttons in v3

### ISSUE THREAD

**Issue by CristianHCol** [driftyco/ionic#11170]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
 I upgrade my Ionic v2 app to Ionic v3. the proccess was success, When i review my app, all pages have a button in the left side but were hidden. i removed the menuToggle directive and inmediatly were showed the buttons, but near to button end, the ion tittle is up too and is misaligned  (In android).

**Expected behavior:**
in the previous version the menuToggle directive show the buttons on left or rigth  inside ion-navbar and was center with ion-tittle doesnt up.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

C:\Users\Prueba\Documents\Test\image-analizer\app>ionic info

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you mind providing a repo or plunker that demonstrates this issue?

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue I will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
