### ISSUE TITLE
Links of null for IonicPage and LiveReload v3

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic#11184]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Sometimes on `ionic serve` using `IonicPage` after change a file and live reload I get this error:
```
Runtime Error
Cannot read property 'links' of null
Stack
TypeError: Cannot read property 'links' of null
    at setupPreloadingImplementation (http://localhost:8100/build/main.js:59537:60)
    at http://localhost:8100/build/main.js:59569:17
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at NgZone.runOutsideAngular (http://localhost:8100/build/main.js:4390:76)
    at http://localhost:8100/build/main.js:59568:20
```

I don't know how to reproduce this, if you need an example I can try to do it.

I think the problem is on `LiveReload` and `IonicPage`, I have multi `ion-nav`

**Expected behavior:**
This should work like a sharm :smile: 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.2
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#892
