### ISSUE TITLE
ionic run android --debug results in "Unexpected token ﻿ in JSON at position 0"

### ISSUE THREAD

**Issue by Rainson12** [driftyco/ionic#11182]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I use visual studio 2017 to edit the code. When using Visual Studio 2017 to debug on the device i can only debug the .js files using chrome debugger. Because of that i thought building the app using the ionic cli strangly it always results in
"[10:02:52]  lint finished in 4.83 s
Error: Unexpected token ﻿ in JSON at position 0"

**Expected behavior:**
Running application on android

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

 ordova CLI: 6.3.1
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2084

**Comment by Rainson12** [comment]
it seems like this issue is related to sigend or unsigned utf8 files. It seems like when saving some files as signed utf8 instead of unsafe utf8 the building process will have issues. Sadly VS 2017 automaticly saved the files as utf8 signed even when it was unsigned before
