### ISSUE TITLE
Update to Angular 4.0.2

### ISSUE THREAD

**Issue by MTechDE** [driftyco/ionic#11180]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The Angular Team released today the second bugfix release of Angular 4. The ionic-angular package should also be upgradeable to bugfix releases because there are no breaking changes at all.

**Expected behavior:**

The ionic-angular package should be updateable for Angular bugfix releases

**Comment by mburger81** [comment]
The Ionic team is working on have a stable version, in past several times Angular released breaking changes I think also on minor versions, so the Ionic team is settings ALWAYS precision versions of Angular. Ionic has a release cycle of two weeks where they try to push angular version. So this is what the team described many times on github.

Feel free to upgrade angular version by our own, if there are no breaking changes there would be no problem.

**Comment by jgw96** [comment]
Hello, thanks for the great answer to this issue @mburger81 , you pretty much nailed it (: We always strive to be on the latest release, but we always specify a single version of Angular to avoid breaking changes. With the next release, if Angular 4.0.2 passes all our testing, we most likely will update.
