### ISSUE TITLE
Assign page member crash!!!

### ISSUE THREAD

**Issue by zGwit** [driftyco/ionic#11194]
![qq 20170412235935](https://cloud.githubusercontent.com/assets/14162835/24967305/3eeb5f1e-1fdc-11e7-8345-5ab64c6bf996.png)

@alakra @mlynch @alexweber @ericb @lwu

**Comment by zGwit** [comment]
@danbucholtz

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
