### ISSUE TITLE
Ionic 3 Text at Fab item

### ISSUE THREAD

**Issue by danielehrhardt** [driftyco/ionic#11204]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

can you please add a option to add a text to a ion-fab item like at google inbox 

Now:
![image](https://cloud.githubusercontent.com/assets/19570043/25003153/55f8659a-204e-11e7-98ca-ea3564c9498a.png)

expected:
![image](https://cloud.githubusercontent.com/assets/19570043/25003217/9ce9d7cc-204e-11e7-9543-a4e4e81172de.png)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#168

**Comment by danielehrhardt** [comment]
thank you @jgw96 but i cant open that issue anymore got a 404
