### ISSUE TITLE
The input of a prompt alert immediately looses the focus of the input on iOS

### ISSUE THREAD

**Issue by antkers** [driftyco/ionic#11209]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When opening a prompt alert (https://ionicframework.com/docs/components/#alert-prompt) on the iPhone 5s (ios 10.3.1), the input of the alert gets the focus and the keyboard pops up. The input immediately looses the focus and the keyboard pops out without having done anything... The behaviour on Android is correct, the keyboard stays open and the input keeps the focus. I'm using Ionic 3.0.1 on both operating systems.

**Expected behavior:**

The keyboard must stay open and the input must keep the focus after the prompt alert is presented.

**Steps to reproduce:**

- Present a simple prompt alert like in your documenation (https://ionicframework.com/docs/components/#alert-prompt)
- On ios you will see that the input in the alert prompt immediately looses the focus now.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.6.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.

**Comment by urm47** [comment]
I ran into the same issue. Maybe related to #11114.
Focus stays with
`<ion-item text-wrap detail-push (click)="openAlert()">...</ion-item>`

Focus lost with
`<button text-wrap detail-push (click)="openAlert()">...</button>`

Focus also lost with
`<ion-item text-wrap detail-push (tap)="openAlert()">...</ion-item>`

**Comment by log4j** [comment]
I have the same issue. 
If you hold the button which triggers the prompt alert for a while like 3 seconds, and then release, the keyboard shows properly after prompt alert. If your click happens fast (normal speed), the keyboard shows then disappears. 
Waiting for someone to solve it

**Comment by antkers** [comment]
this seems to be working now with ionic version 3.2.1

**Comment by markwatsonatx** [comment]
I am seeing this issue with 3.12.0

**Comment by chandanch** [comment]
ref: #11114
