### ISSUE TITLE
add "uwp" to platforms

### ISSUE THREAD

**Issue by zoinkydoink** [driftyco/ionic#11207]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:/Expected**
Currently there is no way to determine if the app is running in uwp, we have "windows" and "core" platform but neither of those tell me that i have an app running on windows 10.
I need to be able to determine if its a uwp app so i can launch the default mapping software with direction to an end point.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Our `windows` platform will only get added on a machine running windows 10. We do not currently support any other version of windows and do not officially support IE11 on windows 10, only edge.

**Comment by zoinkydoink** [comment]
the platform.is("windows") only seems to return true if its running on a DEVICE as stated in the platform doc, and will return false if its running on windows 10 uwp app
