### ISSUE TITLE
Repositories.cfg could not be loaded

### ISSUE THREAD

**Issue by PterPmnta** [driftyco/ionic#11202]
I try to compile my project, but i get this error,

`File C:\Users\User\.android\repositories.cfg could not be loaded.`
 
My PC Info

**Ionic** 2.2.1
**Node** 6.10.1
**OS** W10
**Android Studio** 2.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by JUStrepsec** [comment]
Warning: File C:\Users\bhushan\.android\repositories.cfg could not be loaded.
