### ISSUE TITLE
BUG in Ionic 2: Menu for iOS

### ISSUE THREAD

**Issue by JonathanSilvaTI** [driftyco/ionic#11200]
Code:
![a](https://cloud.githubusercontent.com/assets/24323512/24984241/95edc06e-1fc2-11e7-8d08-a55a892b8a4e.png)

Print:
![ab](https://cloud.githubusercontent.com/assets/24323512/24984244/99ae46ec-1fc2-11e7-9283-ff1cd022672e.png)

**Comment by NeoLSN** [comment]
I've reported this issue before.
https://github.com/driftyco/ionic/issues/9546

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
