### ISSUE TITLE
SplitPane not working as expected

### ISSUE THREAD

**Issue by Xdabier** [driftyco/ionic#11205]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ion-split-pane not behaving correctly it always shows small size even on laptop screen

**Expected behavior:**
expected to show different sizes on different screens as it's meant to do
**how it shows:**
on laptop screen size : 
![image](https://cloud.githubusercontent.com/assets/20482799/25005457/f4f5df72-2050-11e7-91c7-d9aafb60a01a.png)
on phone screen size : 
![image](https://cloud.githubusercontent.com/assets/20482799/25005934/d0d3957e-2052-11e7-86d0-b2cc7a03d054.png)

**Related code:**

```
<ion-split-pane>
    <ion-menu [content]="content">
        <ion-header>
            <ion-toolbar>
                <ion-title>Menu</ion-title>
            </ion-toolbar>
        </ion-header>

        <ion-content>
            <ion-list>
                <button menuClose ion-item *ngFor="let p of pages" (click)="openPage(p)">
        {{p.title}}
      </button>
            </ion-list>
        </ion-content>

    </ion-menu>

    <!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
    <ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
</ion-split-pane>
```

**Ionic info:** 

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.8.0
Xcode version: Not installed
```

**Comment by zhuzhiyu6839** [comment]
hello in this way！tihs may

<ion-split-pane>

  <ion-menu [content]="content">

    <ion-header no-border>
      <ion-toolbar>
        <ion-title>Mypage</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>

    </ion-content>

  </ion-menu>

  <ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>

</ion-split-pane>

**Comment by zhuzhiyu6839** [comment]
hello you look this!
 (<ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>) add  **main**

<ion-split-pane>
<ion-menu [content] =“content”>

<ion-header no-border>
  <ion-toolbar>
    <ion-title>Mypage</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>

</ion-content>
  </ion-menu>

  <ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>

</ion-split-pane>

**Comment by zhuzhiyu6839** [comment]
you ought to this add （main）！

<ion-nav [root]="rootPage" #content swipeBackEnabled="false" main></ion-nav>

**Comment by zhuzhiyu6839** [comment]
You Ionic versions are？

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Xdabier** [comment]
thanks a lot @zhuzhiyu6839 that worked!  I didn't know about the main thing.
thanks @jgw96 I'll be asking my next support questions in the forum in the future ^^
