### ISSUE TITLE
bug: Rendering Bug on Ionic RC4 / iOS

### ISSUE THREAD

**Issue by IKizil** [driftyco/ionic#11206]
![bildschirmfoto 2017-04-13 um 14 30 57](https://cloud.githubusercontent.com/assets/18197289/25007983/93390ce8-2062-11e7-858c-8b6ffdb83a30.png)
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm heavily using this component now and everything works fine so far!
I think the guys at driftyco changed in the RC4 of Ionic some Button-relevant styling on iOS. As you can see in the attached screenshot, the layouting is not on point anymore.

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. I am going to close this issue for now as it does not meet our issue guidelines which are in the issue template that shows when you go to open a new issue. Also, at this time we cannot support an RC release of Ionic. Could you update to Ionic 3.0.1 (the latest release) and open a new issue please that follows our issues template? Thanks!
