### ISSUE TITLE
BUG in Ionic 2: Menu for iOS

### ISSUE THREAD

**Issue by JonathanSilvaTI** [driftyco/ionic#11210]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The menu in iOS is buggy, getting behind the header and hiding a menu item

**Expected behavior:**
It should look like the menu on Android

**Steps to reproduce:**
![ab](https://cloud.githubusercontent.com/assets/24323512/25012680/a391cca8-2047-11e7-92b0-060aff5ad50f.png)

**Related code:**
*home.html*

```
<ion-header color="header">
  <ion-navbar>
    <button ion-button icon-only menuToggle start>
        <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Sistema</ion-title>
    <ion-buttons end>
      <button ion-button icon-only>
          <ion-icon name="search"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-menu [content]="menu">
  <ion-header>
    <ion-toolbar>
        <ion-title>Código: {{codigo}}</ion-title>
    </ion-toolbar>
  </ion-header>
    <ion-content>
        <ion-list>
            <ion-item (click)="categorias()" menuClose>Categorias</ion-item>
            <ion-item (click)="pedidos()" menuClose>Pedidos</ion-item>
            <ion-item (click)="perfil()" menuClose>Minha conta</ion-item>
            <ion-item (click)="sair()">Sair</ion-item>
        </ion-list>
    </ion-content>
</ion-menu>

<ion-content #menu class="home" padding>
  <h3>Bem vindo, {{nome}}</h3>
  <p>Seu e-mail é: {{email}}</p>
</ion-content>
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by AmitMY** [comment]
The `ion-menu` is intended to work with the `ion-nav`. 
The left image you added is clearly Android, but the right one is very weird. Menu should push the normal header to the right.
See this:
https://ionicframework.com/docs/components/#menus

**Comment by JonathanSilvaTI** [comment]
@AmitMY and @jgw96 I can not use ion-nav in app.html because root is an introduction page (slide) and in the print I have the Home page
If you can see, I would be grateful.
https://github.com/JonathanSilvaTI/ionic

**Comment by AmitMY** [comment]
What do you think of, instead, having `HomePage` as root, but it's `ionViewWillEnter` creates a modal with the introduction page.
That introduction page has no header, and has slides, that when you are done you press next which does `dismiss` for the current view (modal)

**Comment by NeoLSN** [comment]
I think if a page has it owns menu it would be better.
Right now ionic can't let a page has it owns menu, it is really hard to bind a action function to menu.

**Comment by jgw96** [comment]
Hello! As this seems like more of a support question I am going to close this issue and ask that you ask this question on our [forum](forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
