### ISSUE TITLE
"Start" Attr Directive Broken?

### ISSUE THREAD

**Issue by BamiGorengo** [driftyco/ionic#11219]
I started today a demo app with the latest ionic2 version. I find in the Documentations this code:

    <ion-toolbar>
      <ion-buttons start>
        <button ion-button icon-only color="royal">
          <ion-icon name="search"></ion-icon>
        </button>
      </ion-buttons>
      <ion-title>Send To...</ion-title>
      <ion-buttons end>
        <button ion-button icon-only color="royal">
          <ion-icon name="person-add"></ion-icon>
        </button>
      </ion-buttons>
    </ion-toolbar>

but the "start" in <ion-buttons start> dont work.

Best regards!

**Comment by AmitMY** [comment]
If it is only a demo project, mind sharing a link to the repo?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
