### ISSUE TITLE
Order of years in ion-datetime picker

### ISSUE THREAD

**Issue by viveksinha9** [driftyco/ionic#11225]
How can I change the order of years in ion-datetime picker? Currently it is showing in decreasing order. I want to show years in picker in increasing order.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
