### ISSUE TITLE
Due to 'ionic3 lazyload' caused by "presen ()" problem

### ISSUE THREAD

**Issue by ctc1995** [driftyco/ionic#11220]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am trying to use ionic3 lazyload,but when trying to present something (modal, actionsheet, alert) I get TypeError: Cannot read property _getPortal of undefined. 

**Expected behavior:**
By calling present (), open (modal, actionsheet, alert)

**Related code:**

![image](https://cloud.githubusercontent.com/assets/17734754/25031168/95169ada-20fd-11e7-9dac-4ec9a4a3b399.png)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
