### ISSUE TITLE
scrollToBottom does not work with ionView

### ISSUE THREAD

**Issue by root-io** [driftyco/ionic#11230]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ScrollToBottom is not working with ionView

**Expected behavior:**
When click on the about tab, the scroll should go to bottom

**Steps to reproduce:**
- Tap the about tab -> the scroll does not move
- Tap the home tab
- Tap the about tab -> the scroll goes to the bottom

**Related code:**
https://github.com/root-io/MyIonic2Project

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by nishantpant** [comment]
This is fixed in ionic3. I was plagued by this issue for a month. And it is finally fixed!!

**Comment by root-io** [comment]
Just a follow up, I added `setTimeout` now it works.
