### ISSUE TITLE
Adding support for HTML5 autocorrect, capitalize, spellcheck attributes

### ISSUE THREAD

**Issue by ScreamZ** [driftyco/ionic#11239]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I'm planning to add support for https://davidwalsh.name/disable-autocorrect with the prompt alert component and ion-input. By adding Input options

Is this ok for you ?

Best regards

**Comment by AmitMY** [comment]
There is support for all of the above, just pass those for the `ion-input`

**Comment by jgw96** [comment]
Hello @ScreamZ . Would you mind posting more info about what your planning here? `ion-input` already works with any HTML5 input attributes.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
