### ISSUE TITLE
Outdated cordova-ios version in platforms.json causing iOS simulator popup

### ISSUE THREAD

**Issue by j7an** [driftyco/ionic#11238]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the default command to scaffold an Ionic 3 app `ionic start Ionic2Do blank --v2`, the default cordova-ios version in platforms.json is v4.1.1. This seems to be causing the iOS simulator to display the error that the current app needs to be recompiled for 64-bit and may not work in future iOS version.

![platforms-json-2](https://cloud.githubusercontent.com/assets/11568283/25072517/0da175a0-2285-11e7-933c-9780b7615f22.png)

<img width="375" alt="ionicerror" src="https://cloud.githubusercontent.com/assets/11568283/25072475/04066614-2284-11e7-873f-64379d9c8b10.png">

**Expected behavior:**
Scaffolding an app should have the latest cordova-ios version, currently v4.3.1. Running the command `cordova platform update ios` within the project folder after scaffolding finishes, the version gets updated to 4.3.1. Running the simulator via `ionic emulate ios --target="iPhone-6s"` shows the app without the popup like before.

**Steps to reproduce:**
Display popup
```
ionic start Ionic2Do blank --v2
cd Ionic2Do
ionic platform add ios
ionic emulate ios --target="iPhone-6s"
```

Fix popup: Delete the previous created project folder, then run the following. Make sure to follow on-screen prompt to save Cordova plugin, rm iOS, add iOS when updating Cordova platform-ios. Popup will not show in following scenario
```
ionic start Ionic2Do blank --v2
cd Ionic2Do
ionic platform add ios
cordova platform update ios
ionic emulate ios --target="iPhone-6s"
```

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2109
