### ISSUE TITLE
Nav from AppComponent not showing Tabs

### ISSUE THREAD

**Issue by pavei** [driftyco/ionic#11232]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using OneSignal to receive push notification. But when i send this.nav.push(NotificationsPage, {data: data}); the page open but not showing Tabs from TabsPage. What can i do?

```
@Component({
  templateUrl: 'app.html'
})
export class MyApp {

  @ViewChild('myNav') nav
  rootPage:any;

constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, userStorage : UserStorageService, private oneSignal: OneSignal ) {
platform.ready().then(() => {
  // Okay, so the platform is ready and our plugins are available.
  // Here you can do any higher level native things you might need.
  statusBar.styleBlackTranslucent();
  splashScreen.hide();

  userStorage.isAuthenticated().then(isAuth => {

    if(isAuth) {
      this.rootPage = TabsPage;
    } else {
      this.rootPage = ChooseCompanyPage;
    }
  })

  this.oneSignal.startInit("XXXX", "XXXXX")

    this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);

  this.oneSignal.handleNotificationOpened().subscribe(data =>{
    this.nav.push(NotificationsPage, {data: data});
  })

  this.oneSignal.endInit();


});

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
