### ISSUE TITLE
Ionic version?

### ISSUE THREAD

**Issue by KevinBurton** [driftyco/ionic#11234]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] support request 

**Current behavior:**
Install ionic and it seems to install 2.2.1

**Expected behavior:**
Some indication of version higher than 2.2.1

**Steps to reproduce:**
sudo npm install -g ionic

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by piotrowski** [comment]
[Ionic CLI](https://github.com/driftyco/ionic-cli) != [Ionic App Lib](https://github.com/driftyco/ionic-app-lib) != [Ionic Framework](https://github.com/driftyco/ionic)
`npm install ionic` installs the Ionic CLI (v2.2.2), that contains the Ionic App Lib (v2.2.1).
When you create a new Ionic project with `ionic start ...` it will contain a version of Ionic (ionic-angular on npm) in a newer version, probably 3.0.1.

**Comment by jgw96** [comment]
Hey @KevinBurton , so @piotrowski is exactly correct (: So when you do `npm install -g ionic` that is installing the cli, not the framework. Then when you do `ionic start` that will install the latest version of `ionic-angular` from npm, which is currently `3.0.1`.
