### ISSUE TITLE
When using $IonicPopup, can I change template?

### ISSUE THREAD

**Issue by aleen42** [driftyco/ionic#11241]
Recently, I have met a confusing problem when using `$IonicPopup.prompt`, because I need to change the template of an IonicPopup instance after users clicks the button. As we know that, we can stop box from closing by adding `e.preventDefault()` in the event handler `onTap`:

```js
{
    onTap: function (e) {
        e.preventDefault();

        // to get the value of the input element
        var inputValue = this.scope.data.response;
        // CONFUSING: can I change the template like changing the title
        // change the title of the box
        this.scope.title = 'new Title';

        // this.scope.tempalte??
    }
}
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
