### ISSUE TITLE
Error on app deploying on emulator Nexus_6P 

### ISSUE THREAD

**Issue by waleediqbal1** [driftyco/ionic#11245]
![image](https://cloud.githubusercontent.com/assets/24951301/25088947/e1390af4-2393-11e7-872c-5788299550ea.png)

Hello Sir. This Answer i am getting as response from Facebook team. Sir i have run the app on live devices it all running and even on GenyMotion too but the issue is that its not running on their device. I have searched for this issue on internet too 
I have found this answer ....
http://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk 

They have asked for the architecture issue its not app issue but can u sir plzz tell me what to do that my app runs on their device too ...

Waiting for your answer Sir thanks Regards Waleed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
