### ISSUE TITLE
registerbackbuttonaction

### ISSUE THREAD

**Issue by danillo10** [driftyco/ionic#11244]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

http://plnkr.co/edit/0fFUnJKYN57YTcY2s35d?p=preview

**Related code:**

```
insert any relevant code here
```

**Other information:**

I HAVE A APP WITH 3 PAGES, AND I'M TRY USE registerBackButtonAction(), BUT NOT SUCCESS, SEE THE CODE... 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
