### ISSUE TITLE
After 3.0 upgrade I can't get past the splash screen

### ISSUE THREAD

**Issue by joshstrange** [driftyco/ionic#11248]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I upgraded to 3.0 following the release notes and I'm trying to run the app and I'm getting stuck on the splash screen. I tried both with a full build and a live reload build. With the LR one I got only the following log:

    [12:09:55]  console.log: Ionic Native: deviceready event fired after 204 ms

**Expected behavior:**
I expect the app to launch and go to the root page

**Steps to reproduce:**
I don't have steps to reproduce as this is a private app and I have a newly created Ionic 3 app that is working fine. I have referenced the Ionic 3 app multiple times to try to determine what the difference is between it and my Ionic 2 -> 3 app.

**Related code:**

package.json
```
"dependencies": {
		"@angular/common": "4.0.0",
		"@angular/compiler": "4.0.0",
		"@angular/compiler-cli": "4.0.0",
		"@angular/core": "4.0.0",
		"@angular/forms": "4.0.0",
		"@angular/http": "4.0.0",
		"@angular/platform-browser": "4.0.0",
		"@angular/platform-browser-dynamic": "4.0.0",
		"@angular/platform-server": "4.0.0",
		"@angular/animations": "4.0.0",
		"@ionic/storage": "2.0.1",
		"@ionic-native/core": "3.4.4",
		"@ionic-native/splash-screen": "3.4.4",
		"@ionic-native/status-bar": "3.4.4",
		"@ionic-native/badge": "3.4.4",
		"@ionic-native/diagnostic": "3.4.4",
		"@ionic-native/dialogs": "3.4.4",
		"@ionic-native/keyboard": "3.4.4",
		"@ionic-native/network": "3.4.4",
		"@ionic-native/app-version": "3.4.4",
		"@ionic-native/geolocation": "3.4.4",
		"@ionic-native/barcode-scanner": "3.4.4",
		"@ionic-native/flashlight": "3.4.4",
		"@types/lodash": "^4.14.50",
		"@types/winrt-uwp": "0.0.16",
		"angular2-uuid": "^1.1.0",
		"ionic-angular": "3.0.1",
		"ionicons": "3.0.0",
		"jwt-decode": "^2.1.0",
		"localforage": "^1.4.3",
		"localforage-cordovasqlitedriver": "^1.5.0",
		"lodash": "^4.17.2",
		"moment": "^2.17.1",
		"rxjs": "5.1.1",
		"zone.js": "^0.8.4",
		"sw-toolbox": "3.4.0"
	},
	"devDependencies": {
		"@ionic/app-scripts": "1.3.0",
		"typescript": "2.2.1"
	},
	"cordovaPlugins": [
		"cordova-plugin-whitelist",
		"cordova-plugin-statusbar",
		"cordova-plugin-console",
		"cordova-plugin-device",
		"cordova-plugin-splashscreen",
		"ionic-plugin-keyboard",
		"cordova-plugin-network-information",
		"phonegap-plugin-barcodescanner",
		"cordova-plugin-http",
		"cordova-plugin-file",
		"cordova-plugin-compat",
		"cordova-plugin-geolocation",
		"cordova-sqlite-storage",
		"cordova-plugin-dialogs",
		"cordova-plugin-badge",
		"cordova-plugin-app-event",
		"cordova-plugin-crosswalk-webview"
	],
	"cordovaPlatforms": [
		{
			"platform": "ios",
			"version": "4.3.1",
			"locator": "ios"
		},
		{
			"platform": "android",
			"version": "6.2.1",
			"locator": "android"
		}
	],
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by chris08002** [comment]
@joshstrange could you solve this?
