### ISSUE TITLE
1.3.3 is not available on bower and same version on git.

### ISSUE THREAD

**Issue by srameshr** [driftyco/ionic#11255]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Version 1.3.3 is available just on code.ionicframework.com

**Expected behavior:**

Version 1.3.3 should be available on github and bower.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
HI there! This repo is for Ionic 2.0.0 and 3.0.0. Since this is V1 related issue, please checkout the V1 repo.

https://github.com/driftyco/ionic-v1/issues/239
