### ISSUE TITLE
Unable to  generate signed App  file in ionic

### ISSUE THREAD

**Issue by sugandhaverma** [driftyco/ionic#11254]
I have getting problem in generating signed app file. How do i published my updated app on existing  ionic project. I have key_pwd and key _alias. but i unable to generate the update version of app.
i m using the command like
cordova build --release android

Drinkasaurs-MacBook-Pro:drinkasaur_ionic drinkasaur$ my-release-key.keystore /Users/drinkasaur/Downloads/drinkasaur_ionic/platforms/android/build/outputs/apk/android-release-unsigned.apk alias_store name

but its showing command not found.
I don't know what i use it to signed the unsigned app for uploading on beta testing.

If anyone know help me out. it would be a great help

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.
