### ISSUE TITLE
bug(Content) - Calling getContentDimensions on page load returns with contentHeight as NaN

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#11257]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
This call below will return the dimensions object with the property `contentHeight` equal to `NaN`.
```
ngAfterViewInit() {
    let dimensions = this.content.getContentDimensions();
}
```

**Expected behavior:**
I expect `getContentDimensions` to return the correct values, as `ngAfterViewInit` is supposed to run after the view is completely ready.

**Related code:**

The `readReady` subscription on lines 377-380 in `content.ts` (pasted below) on the view controller is the culprit, as it doesn't emit an event until _after_ the `ngAfterViewInit` method is run.

```
this._viewCtrlReadSub = viewCtrl.readReady.subscribe(() => {
    this._viewCtrlReadSub.unsubscribe();
    this._readDimensions();
});
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by ZiFFeL1992** [comment]
Wrap the code inside: `ionViewDidEnter`

**Comment by zakton5** [comment]
Yep, that works. Thanks @ZiFFeL1992.
`ionViewWillEnter` also works.
