### ISSUE TITLE
href="tel:" probably buggy on iOS devices

### ISSUE THREAD

**Issue by marcthomsen** [driftyco/ionic#11252]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

The html link to call a phone number - made by an `<a>` tag with an href attribute with the value "tel:” - seems to be buggy on iOS devices. 

Clicking on such a link on an iOS device triggers a confirm alert that shows the phone number to call and the two buttons "Cancel" and "Call". If one let this alert be present for approximately 10 seconds, by not clicking any buttons, the alert will disappear for one second and show up once again. 

The bug has been observed on these devices:

iPhone 6 Plus on 10.3.1
iPhone 5 on 10.3.1

**Expected behavior:**

This confirm phone call alert on iOS devices should not disappear and show up again when letting the alert be present for about 10 seconds. 

**Steps to reproduce:**

Deploy the related code snippet to one of the above mentioned iOS devices. Click on the telephone hyperlink and when the confirm alert appears wait for about 10 seconds. At this point the confirm alert will disappear and show up again about a second after it disappeared.

![tel link and confirm alert](https://cloud.githubusercontent.com/assets/7867908/25118846/30eefc50-2418-11e7-8be1-7f3708e5ca86.png)

**Related code:**
Below is a simple hyperlink element with a telephone href:
```
<a href="tel:12345678">Call number 12345678</a>
```

**Ionic info:** 
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Does the same behavior happen in a plain Cordova app?

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by brstdev32** [comment]
I faced same issue in ionic 1 app so it seems ios issue.
Instead of href attribute on <a> tag use a click function and make a call with 
"window.open('tel:12345678') "

**Comment by marcthomsen** [comment]
Hello,
This strange behavior of the IOS "confirm call" alert does not happen in a plain Cordova app. 

Before opening an issue on this we tried with a click function that calls window.open('tel:12345678'). Unfortunately this solution made no difference to the buggy behavior (alert dismisses after being present for 10 seconds - the second after it appears once again).

**Comment by Thomas2590** [comment]
Hello,
I also have been running into this issue.  If have tried the, window.open , href=tel, and several (clink) methods with the same results.  Also I have notice when you select the cancel button the alert modal also reappears in about 3-5 seconds.  

I only see this bug on a iOS device.

**Comment by annnatar** [comment]
Team, one of the Ionic+Meteor app we have also displays the confirm call alert after upgrading to 10.3 iOS. Is there any solution to this issue?

**Comment by Kyry11** [comment]
I'm having this issue as well.

While the description from OP is technically correct, to me this looks like more of a "navigation retry" issue. When the iOS confirmation pops up you can cancel out of it quickly and everything works as expected. However, if you wait for about 4-5 seconds before dismissing it, it seems to trigger some sort of "retry" logic which forces another iOS confirmation to come up. The second confirmation either replaces the first one or just comes up after you manually closed the first one.

Would be awesome to know why this happens and how to resolve this :)

**Comment by marcthomsen** [comment]
Hello @jgw96 / Ionic team

At present at least three independent users are experiencing this issue.
Would you guys reconsider opening this again?

**Comment by 5im0n** [comment]
I got the same problem on iOS `10.3` But not on iOS `10.0`, as @annnatar I think that it's due to iOS update.

**Comment by prateekkathal** [comment]
@jgw96 Please consider re-opening this issue.

**Comment by JimGeersinga** [comment]
@jgw96 Having the same issue

**Comment by SandeepGovada** [comment]
Facing same issue:

cli packages:

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.4.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.10.3
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    npm               : 3.10.10

**Comment by andrei-myonlinepresence** [comment]
Battling with this as well :/ Plz reopen? :D

**Comment by kensodemann** [comment]
I just tried and it worked fine for me.

I suggest opening a new issue with a sample application available via GitHub that demonstrates the issue.

**Comment by JimGeersinga** [comment]
@kensodemann i don't have a sample project at the moment.
But i have the button bar navigation at the bottom where i created a onclick event which calls the window.href="tel:12345678" also  tried with the element a.

**Comment by larssn** [comment]
Same problem
