### ISSUE TITLE
Lazy loading error with Ionic 3

### ISSUE THREAD

**Issue by dawiisss** [driftyco/ionic#11250]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I added the lazy loading using the guide but I keep on getting : 

> Runtime Error
> Cannot read property 'links' of null

 

> Uncaught TypeError: Cannot read property 'links' of null
>     at setupPreloadingImplementation (VM3387 main.js:56270)
>     at VM3387 main.js:56302
>     at t.invoke (VM3370 polyfills.js:3)
>     at n.run (VM3370 polyfills.js:3)
>     at NgZone.runOutsideAngular (VM3387 main.js:4315)
>     at VM3387 main.js:56301
> setupPreloadingImplementation @ VM3387 main.js:56270
> (anonymous) @ VM3387 main.js:56302
> t.invoke @ VM3370 polyfills.js:3
> n.run @ VM3370 polyfills.js:3
> NgZone.runOutsideAngular @ VM3387 main.js:4315
> (anonymous) @ VM3387 main.js:56301

> ERROR Error: Uncaught (in promise): invalid link: HomePage
>     at g (VM3370 polyfills.js:3)
>     at l (VM3370 polyfills.js:3)
>     at VM3370 polyfills.js:3
>     at t.invokeTask (VM3370 polyfills.js:3)
>     at Object.onInvokeTask (VM3387 main.js:4415)
>     at t.invokeTask (VM3370 polyfills.js:3)
>     at n.runTask (VM3370 polyfills.js:3)
>     at a (VM3370 polyfills.js:3)
> defaultErrorLogger @ VM3387 main.js:1364
> ErrorHandler.handleError @ VM3387 main.js:1424
> IonicErrorHandler.handleError @ VM3387 main.js:112467
> next @ VM3387 main.js:5053
> schedulerFn @ VM3387 main.js:4127
> SafeSubscriber.__tryOrUnsub @ VM3387 main.js:39215
> SafeSubscriber.next @ VM3387 main.js:39164
> Subscriber._next @ VM3387 main.js:39106
> Subscriber.next @ VM3387 main.js:39070
> Subject.next @ VM3387 main.js:56368
> EventEmitter.emit @ VM3387 main.js:4113
> NgZone.triggerError @ VM3387 main.js:4484
> onHandleError @ VM3387 main.js:4445
> t.handleError @ VM3370 polyfills.js:3
> n.runGuarded @ VM3370 polyfills.js:3
> r @ VM3370 polyfills.js:3
> a @ VM3370 polyfills.js:3
> VM3387 main.js:45009 Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
> cordovaWarn @ VM3387 main.js:45009
> checkAvailability @ VM3387 main.js:56592
> callCordovaPlugin @ VM3387 main.js:56680
> (anonymous) @ VM3387 main.js:56799
> value @ VM3387 main.js:104231
> (anonymous) @ VM3387 main.js:104398
> t.invoke @ VM3370 polyfills.js:3
> onInvoke @ VM3387 main.js:4424
> t.invoke @ VM3370 polyfills.js:3
> n.run @ VM3370 polyfills.js:3
> (anonymous) @ VM3370 polyfills.js:3
> t.invokeTask @ VM3370 polyfills.js:3
> onInvokeTask @ VM3387 main.js:4415
> t.invokeTask @ VM3370 polyfills.js:3
> n.runTask @ VM3370 polyfills.js:3
> a @ VM3370 polyfills.js:3
> invoke @ VM3370 polyfills.js:3

**Expected behavior:**
The application should open and load the main page.

**Steps to reproduce:**
https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit#

**Related code:**

https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit#

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: 1.8.5
    ios-sim version: 5.0.4
    OS: macOS Sierra
    Node Version: v7.4.0
    Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by mburger81** [comment]
Which version of @ionic/app-script do you use?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mburger81** [comment]
First of all you should open thr bug not here but in the app-script repro. 
For second on version 1.3.2 the bug should be resolved. Try to update to latest 1.3.3 and aee this issue
https://github.com/driftyco/ionic-app-scripts/issues/892

**Comment by mburger81** [comment]
Or probabbly @jgw96 are right. You are not loading thr right page

**Comment by nikklass** [comment]
i keep getting this error in ionic 3.6.0. Am lazy loading pages as described above. When i stop server and restart, error disappears. After a while, it comes back. Is it an ionic bug that you guys keep brushing aside? Its really frustrating and time wasting to keep restarting the ionic server.
