### ISSUE TITLE
<select> not displaying any options on android chrome browser

### ISSUE THREAD

**Issue by GanuM** [driftyco/ionic#11264]
**Ionic version:**  (check one with "x")
- [x] **1.x**
- [] **2.x**
- [] **3.x**

**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [] feature request
- [] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
hi Team ionic ,
I'm trying to run my ionic application on the android mobile chrome browser , but my select menu is not displaying any options on tap , can suggest fix for this issue

Thank You

**Comment by AmitMY** [comment]
https://github.com/driftyco/ionic-v1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#247
