### ISSUE TITLE
Add once to Events and other subscription types

### ISSUE THREAD

**Issue by azarus** [driftyco/ionic#11261]
Please add ability to allow subscribe only once to an event then automatically unsubscribe.

Maybe related topic:
https://forum.ionicframework.com/t/events-pub-sub-how-to-unsubscribe-in-lifecycle-hook/50596/9

Currently it is a hacky way of doing something like. I am not sure if i am the only one requiring such a feature.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by azarus** [comment]
Ok then close it again.

**Comment by azarus** [comment]
Hopefully it really makes you guys happy to have that extra nonsese template text. What a joke.
