### ISSUE TITLE
When you press an active tab the view is reloaded

### ISSUE THREAD

**Issue by luisbahamonde** [driftyco/ionic#11260]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In an application with tabs menu when you are in an active tab and you return to press reload the view again.

**Expected behavior:**
Pressing the active tab again should not reload the view.

**Steps to reproduce:**
Pressing an active tab and the view will recharge every time we press it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.2
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by sunny061** [comment]
@luisbahamonde Hi, I have also experienced this and created an issue for it already (#11253). I'm also waiting to find out whether it's by design or a bug.

**Comment by luisbahamonde** [comment]
@sunny061 hi friend! I think it's a bug because it's something that has never happened in older versions

**Comment by drptbl** [comment]
Should be already fixed at `master` branch.
https://github.com/driftyco/ionic/pull/11084

**Comment by luisbahamonde** [comment]
Tested and confirmed!! thanks
