### ISSUE TITLE
Missing-provider Error on runtime

### ISSUE THREAD

**Issue by Blackscr33n** [driftyco/ionic#11266]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If there are missing providers like native-plugin providers, the error is only thrown at runtime.

**Expected behavior:**
Is it possible to throw errors like this in the compile-process? Or is this too complicated?
May this has more to do with app-scripts?

Greets,
Bernhard

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#184
