### ISSUE TITLE
When you use touch event the mouse stops working

### ISSUE THREAD

**Issue by robdmoore** [driftyco/ionic#1126]
Hi,

I've upgraded to the latest nightly of ionic and I've noticed an interesting issue on touch-enabled laptops. When the app first loads you can use your mouse to click around etc., but as soon as you use touch to scroll or tap then mouse clicks no longer do anything.

I've replicated the problem in a Plunkr here: http://plnkr.co/edit/fyFolTNeTXfeKg7wZJit?p=preview

Thanks

**Comment by adamdbradley** [comment]
This should be fixed now: https://github.com/driftyco/ionic/commit/be0943360850ad99a84bfd7bebb8a77b905e6483
