### ISSUE TITLE
Padding and margin variation.

### ISSUE THREAD

**Issue by Bernardoow** [driftyco/ionic#11275]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X] **3.x**

I used ui-kit recently and The framework variation for padding and margin. padding-small 8px, padding 16px and padding-large 32px.

It can be implemented?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
