### ISSUE TITLE
No provider for SQLite 

### ISSUE THREAD

**Issue by RahulChamle** [driftyco/ionic#11270]
**Ionic version:**  (check one with "x")
ionic -3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 7.5.0
OS Platform: Linux 4.4

I follow all instructions form main ionic website i.e https://ionicframework.com/docs/native/sqlite/

but still i get error "No providers for SQLite"

**Related code:**
this.sqlite.create({
        name: 'data.db',
        location: 'default'
      })
        .then((db: SQLiteObject) => {
          db.executeSql('create table danceMoves(name VARCHAR(32))', {})
            .then(() => console.log('Executed SQL'))
            .catch(e => console.log(e));

        })
        .catch(e => console.log(e));

- 

- 

-

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by matejuh** [comment]
I have the same problem. I don't think it's support question but most probably a regression after ionic-native update.

**Comment by RahulChamle** [comment]
Ya It works for me. Actually i forget to import dependency  in ngModule
array of  app.module.ts.











*Thank You*
*Chamle Rahul*

**Comment by mst1903** [comment]
I have the same problem, what's the solution? @RahulChamle  what import dependency do you mean? In the instructions (https://ionicframework.com/docs/native/sqlite/) there is nothing about an import dependency?!

**Comment by matejuh** [comment]
@mst1903 Put into providers in app.module.ts the SQLite provider. How to add each provider is mentioned here: [https://ionicframework.com/docs/native/](https://ionicframework.com/docs/native/).

**Comment by raphaelluiz128** [comment]
hello guys whats the directory ?

**Comment by yogeshbansal** [comment]
In the app.module.ts, Add 'SQLite' in the  Provider section like below and import {SQLite} from '@ionic-native/sqlite'. Hope it should resolve the issue
 providers: [
    StatusBar,
    SplashScreen,
    Camera,
    SQLite
  ]
