### ISSUE TITLE
Title position on ion-nav-bar with align-title="left" inconsistent.

### ISSUE THREAD

**Issue by mlev** [driftyco/ionic#1127]
When using ion-nav-bar with align-title="left" - the first time the page is loaded the title is left aligned but it is indented as if there is a back button. Once you navigate away and then back the title is correctly positioned at the far left. Using hide-back-button="true" on the view doesn't seem to make any difference.

See http://codepen.io/mlev/pen/jiIka/

**Comment by mbret** [comment]
I still have this problem, even with the latest nightly.
