### ISSUE TITLE
Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.

### ISSUE THREAD

**Issue by sunilkconsultant** [driftyco/ionic#11271]
**Ionic version:**  
[x] **3.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"

**Expected behavior:**
Build must not fail 

**Steps to reproduce:**
Download a ionic v2 blank template,
Run platform add android,
Run ionic run android --prod

**Ionic info:** :

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2119
