### ISSUE TITLE
Typescript Error Property 'forChild' does not exist on type 'typeof IonicModule'.

### ISSUE THREAD

**Issue by RomanDraliuk** [driftyco/ionic#11276]
Ionic 3 with angular 4 when creating new component typescript error appear .
Typescript Error Property 'forChild' does not exist on type 'typeof IonicModule'.

Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 7.8.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by jgw96** [comment]
Hello! This has been fixed and will be in the next release. (:
