### ISSUE TITLE
GoogleMaps plugin: Maps does not render in Modal

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic#11287]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Map does not render in the content of the Modal. Just a transparent window shows.

**Expected behavior:**
Map should be rendered in the window.

**Steps to reproduce:**
1. Create modal
2. Run GoogleMaps using the ionic native example

**Related code:**

**html**

```html
<div id="mapper"></div>
```

**code**
```javascript
this.mapper = this.googleMaps.create(<HTMLElement>document.querySelector('#mapper'));
        this.mapper.one(GoogleMapsEvent.MAP_READY).then(() => {
            let location: LatLng = new LatLng(9.0630796, 7.462721);
            //let cameraposition: CameraPosition = { target: location, zoom: 18, tilt: 30 };
            let animateCameraOption: AnimateCameraOptions = { target: location, zoom: 17 };
            //this.mapper.moveCamera(cameraposition);
            this.mapper.animateCamera(animateCameraOption);

            let markerOptions: MarkerOptions = { position: location, title: location.toUrlValue() };
            this.mapper.addMarker(markerOptions).then((marker: Marker) => marker.showInfoWindow());

            console.log("My location", this.mapper.getMyLocation());
        });
```

**Ionic info:**:

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
