### ISSUE TITLE
i can not ref a third party  js lib in index.html

### ISSUE THREAD

**Issue by SmallShrimp** [driftyco/ionic#11285]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

我在index.html中引入js库，并且添加window对象，但是我不能在window中获取到我的对象
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by rapropos** [comment]
This seems to be more of a support request than a feature request. How about creating a topic on [the support forums](https://forum.ionicframework.com/)?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com) as @rapropos suggested or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
