### ISSUE TITLE
Add once to Events and other subscription types

### ISSUE THREAD

**Issue by azarus** [driftyco/ionic#11280]
**Ionic version:**  (check one with "x")
[  ] **1.x**
[ X ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request
[ ] support request

**Current behavior:**
N/A (hopefuilly the extra text makes you happy)

**Expected behavior:**
Something to happen? ((hopefuilly the extra text makes you happy)

**Steps to reproduce:**
N/A (hopefuilly the extra text makes you happy)

**Other information:**
Please add ability to allow subscribe only once to an event then automatically unsubscribe.

Maybe related topic:
https://forum.ionicframework.com/t/events-pub-sub-how-to-unsubscribe-in-lifecycle-hook/50596/9

Currently it is a hacky way of doing something like. I am not sure if i am the only one requiring such a feature.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. So maybe I'm misunderstanding here (that's very likely haha) but it seems like this is more of a support question of how to do certain functionality. Observables (which is what our `Events` class returns) already have a built in method to handle only firing once and then cleaning up. You can look at [these docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-instance.md) and specifically [this operator](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/first.md) for how to do this. Does this solve your issue?

**Comment by azarus** [comment]
Hi thanks for your reply. 
I dont see where it does return an observable:
https://github.com/driftyco/ionic/blob/master/src/util/events.ts

I opened this issue since the events require manual cleanup in many cases where a controller subscribed to an event. Reusing the same controller likely to cause to trigger the event mutliple times and cause unexpected behavior.

I would like to ask to extend the functionality of the events so its not required to manually clean up after a controller is destroyed.

**Comment by jgw96** [comment]
Hello! I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#223

**Comment by azarus** [comment]
This issue was moved to 404 not found.
