### ISSUE TITLE
How to know that the page is returned

### ISSUE THREAD

**Issue by anrip** [driftyco/ionic#11286]
Page1：blog list page
Page2：blog add page

Exp:
1. Page1 => click <add>button => Page2 => do nothing => return Page1.
2. Page1 => click <add>button => Page2 => submit a blog => return Page1.

Ask:
Could Page1 reload data only when ' submit a blog' ?

**Comment by anrip** [comment]
Whether you add an IonViewDidReturn interface to receive the returned data ？

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
