### ISSUE TITLE
IonicPage segment: Allow multiple parameters 

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#11295]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
IonicPage is not working with multiple parameters after a slash, for example:
`segment: 'place/:id-:name'`  
will not work

**Expected behavior:**
IonicPage should detect multiple parameters after a slash, starting with `:`
Use case would be better SEO and avoiding too much slashes in the URL. Example of URL:
`mysite.com/place/5-Coffe`

**Steps to reproduce:**
Irrelevant

**Related code:**

```
@IonicPage({
  segment: 'place/:id-:name'
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic 3.0.1
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#186

**Comment by realfreebird** [comment]
The link is broken.  (https://github.com/ionic-team/ionic-feature-requests/issues/186)
Here is the solution: 
https://forum.ionicframework.com/t/ionicpage-more-than-one-parameter/91996/6
