### ISSUE TITLE
Ionic 3 super slow performance issue with firebase on Device/Emulator

### ISSUE THREAD

**Issue by shaarawy130** [driftyco/ionic#11290]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

After upgrading to ionic 3, I ran into performance issues related to firebase. it takes forever to load information now. This behaviour is only occurring on real devices and emulators. However, on regular web browser it works good.

PS. This happens for the first connection from the device/Emulator to firebase.

**Expected behavior:**

It should work normally as it works on the regular browser. Which is how it worked before upgrading to ionic 3

**Steps to reproduce:**

Just upgraded my app to ionic 3 then ran through the mentioned performance issues.
Here is a video showing the difference between running the same code on browser & device
[Video](https://youtu.be/qc3vxchD-Es
)
**Related code:**

```
this.angularfire.database.object('/accounts/' + this.uid).subscribe(user=> {
       this.user=user;
       console.log(user)
      })
```

```
 <ion-item  class="welcome" (click)="editProfile()">
    <div *ngIf="user">
    <ion-row >
      <ion-col width-20> 
  <img class="user" src="{{user?.img}}"/>
  </ion-col >
  <ion-col width-67 class="name">
    <p> Welcome, {{user?.name}}</p>
  </ion-col>
  <ion-col width-10>
  </ion-col>
  </ion-row>
    </div>

    <ion-spinner name="circles" *ngIf="!user"></ion-spinner>
  </ion-item>  
```

insert any relevant code here
```

**Other information:**

"dependencies": {
"@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
"@ionic/storage": "2.0.1",
    "angularfire2": "^2.0.0-beta.7-pre",
    "firebase": "^3.8.0",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.3.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "^0.8.4"},
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "typescript": "~2.2.1"
  }

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is strange, we don't do anything different with firebase in 3.0.1 than in any other release. Did you happen to update angular fire at the same time as updating ionic-angular?

**Comment by shaarawy130** [comment]
Hi @jgw96  thanks for your reply. 
I wasn't sure if it was a problem with data from firebase at the beginning, since app took too long to start but now when testing with a simple welcome page I found out that this was the root cause of the issue. 
I'm not sure if I have upgraded angularfire at same time but now i'm sure I have the same angularfire version I had before with a the working version after I have changed package.json to  ran npm install "angularfire2": "^2.0.0-beta.7-pre"

**Comment by shaarawy130** [comment]
Any news regarding this? I have also created a git repository showing the code, it's a very simple sample
https://github.com/shaarawy130/innotest

**Comment by kgaspar** [comment]
Hi, I have noticed the same performance issues since the update to Ionic 3. I tought that it might be related to angularfire2, so I upgraded angularfire to the test version that supports angularJS 4. The results were the same, very slow connection to Firebase upon app start.

In the end I concluded that the performance hit is due to the upgrade of the firebase package, try downgrading the firebase package to lets say firebase@3.3.0 and the performance should be back to normal.

**Comment by briansg** [comment]
Hi @shaarawy130 @jgw96 @kgaspar , I was experiencing the same issue after upgrading to Ionic3 and it was related to the **firebase** module. I was using firebase@3.7.3 and had to update to firebase@3.7.8.
After updating performance went back to normal.

**Comment by envmBw** [comment]
@briansg Yes, it's the last update of firebase !

**Comment by jasonhoch** [comment]
Hi all,

The solution is here https://groups.google.com/forum/#!topic/firebase-talk/svgk3GNcY0o

We need to install the cordova plugin

**Comment by scottmotion** [comment]
That solution specifically mentions OAuth. I am getting the same results using email/password auth, appx 30 seconds lag loading the login screen (first it sets an auth observor to redirect landing page).

Is this problem you reference specific to using OAuth? Could it be a problem getting that first connection to the Firebase Auth db?

**Comment by danilopraonde** [comment]
Hi @scottmotion,

I followed @briansg tip and the performance went back to normal

**Comment by jgw96** [comment]
Hello, all! As this seems to have been a firebase issue that has since been solved in a new firebase release I am going to close this issue. Thanks, everyone!

**Comment by rashnk** [comment]
if the slow issue only in device , check this answer, firebase support team suggested to clear device's storage cache

http://stackoverflow.com/questions/43835548/check-if-push-is-successful-angularfire2/43839725#43839725

**Comment by janhesters** [comment]
Hi I have the same issue. I use [Ionic Native Push](https://ionicframework.com/docs/native/push/) with Firebase Cloud Messaging. And even though `push.init()` is not asynchronous, it slows down the application heavily.
