### ISSUE TITLE
No provider for SQLite

### ISSUE THREAD

**Issue by matejuh** [driftyco/ionic#11298]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic unable to start because No provider for SQLite.

**Expected behavior:**
SQLite available and working.

**Steps to reproduce:**
Create a new project, add SQLite support with ionic-native: [https://ionicframework.com/docs/native/sqlite/](https://ionicframework.com/docs/native/sqlite/)

**Other information:**
Ionic Framework: 3.0.1
Ionic Native: ^3.5.0
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 7.8.0
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by rapropos** [comment]
This sounds like more of a support request than a bug report. I suspect failure to declare SQLite as a provider in the app module as documented at the end of [here](https://ionicframework.com/docs/native/).

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.

**Comment by matejuh** [comment]
Thanks a lot for help. It was really my fault, @rapropos hint helped.
