### ISSUE TITLE
Regression : activated class is not added anymore to <ion-item> on tap

### ISSUE THREAD

**Issue by youssmak** [driftyco/ionic#11306]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
"activated" class is not added anymore to <ion-item> on tap

**Expected behavior:**
"activated" class should be added

**Steps to reproduce:**
http://ionicframework.com/docs/components/#list-dividers

**Other information:**
This is a regression

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. We will look into this.

**Comment by brandyscarney** [comment]
Hey @youssmak, are you only seeing this in the demos in the documentation? I'm not able to reproduce this running an app.

**Comment by youssmak** [comment]
Hello @brandyscarney, not only in the demos in the documentation.
The "activated" class is still being added on buttons items, but not on all other items such as an <ion-item> or an <ion-avatar>.
Here's a demo : http://plnkr.co/edit/MP8w8pc0bJPeRdQcqscv?p=preview

**Comment by brandyscarney** [comment]
Thanks for the plunker! So this is working properly, since normal items should not be used for click events. `<ion-item>` should only be used as an element when it is not clickable. If you want to add a click event it should be on a button like: `<button ion-item>` and for href's `<a ion-item>`. There is some information about this here: http://ionicframework.com/docs/api/components/item/Item/#common-usage

**Comment by youssmak** [comment]
@brandyscarney thank your for your answer.
I have changed some <ion-item> to <button ion-item> elements and it works well.
I could not wrap some complex ion-item (rich cards, rich list elements) into buttons, because they already contain some links. I understand that this new behaviour is more logical and will find a solution for particular cases.
