### ISSUE TITLE
ion-tab is always popped back to root on iOS (Emulator)

### ISSUE THREAD

**Issue by rose-m** [driftyco/ionic#11317]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using `ion-tabs` and pushing additional views inside one of the tabs navigation between the different tabs will pop the tab back to its root page on iOS or the iOS Emulator (**not in the browser**).

**Expected behavior:**
As long as the user only navigates between tabs (without clicking on an active tab again) the navigation state should be remembered and not be popped back to root.

**Steps to reproduce:**
The application is setup as follows:

- Root page contains an `ion-tabs` with two different tabs (called `Today` (default) and `All`)
- The `All` tab contains a list of selectable items - upon click on an item a new page `Details` will be pushed for this tab.

1. The application is loaded with the `Today` tab
2. Navigate to `All` tab and select an item in the list
3. `Details` page is pushed and shown (while `All` tab is active)
4. Navigate to `Today` tab
5. Navigate to `All` tab - the details view is popped

**Other information:**
This bug is **not** solved by #11084 (already tested locally).

My initial debugging revealed that inside the `.tab-button` the [`onClick` event listener](https://github.com/driftyco/ionic/blob/master/src/components/tabs/tab-button.ts#L63) is fired twice in succession - the first one triggers the navigation, the second one then pops back to root. I have not been able to yet identify the root cause.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Would you be able to create a minimal repo we could use to repro this?
