### ISSUE TITLE
Android 4.2 nav.setRoot does not work/does not resolve

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#11319]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When calling in app.component.ts: 

```
this._app.getRootNav().setRoot(xxx).then(() => { 
    ... 
});
```  

...the setRoot doesn't work and the promise never resolves.

**Expected behavior:**
The setRoot function should work and the promise should resolve.

**Steps to reproduce:**

1. Download my app:
[AddVideo on Google Play](https://play.google.com/store/apps/details?id=com.rareprominence.addvideo&hl=en)

2. Run on Android 4.2 device, e.g. Samsung S3 mini

3. You will see splash screen never hides.

This is the code that is running (this works on Android 5, 6 and 7):

```
    this._app.getRootNav().setRoot(LoginPage).then(() => {
      setTimeout(() => {
        this._SplashScreen.hide();
      }, 100)
    });
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Davids-MacBook-Air:AddVideo2 daveshirman$ ionic info

  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.8 
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you using crosswalk on this project?

**Comment by daveshirman** [comment]
I'm not using crosswalk no, as its support has been discontinued.

**Comment by jgw96** [comment]
Hello @daveshirman , while active development on crosswalk has been discontinued we still recommend using crosswalk for Android below 4.4.4. The last crosswalk release, while not running the latest chrome webview like an Android device running Android 5.0 and up will, is still built on a newer version of chrome than the webview on an Android 4.2 device.
