### ISSUE TITLE
Ion-title not updated

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic#11310]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Text in the `ion-title` is not always updating when new data was given. code is exactly the same but works like a charm. 
![ezgif-2-789641a5ca](https://cloud.githubusercontent.com/assets/10044261/25283901/a43e9220-26b5-11e7-94ba-7cb3dabe5556.gif)

**Expected behavior:**
Text is updating when new information is given. 

**Related code:**

```
<ion-toolbar>
    <ion-buttons end>
        <button ion-button icon-only (click)="openProjectsSelector()">
            <ion-icon name="create"></ion-icon>
        </button>
    </ion-buttons>
    <ion-title>
      {{ currentDate.getDate() }} {{currentDate.getMonthName(true) }} | {{ "hours" | translate }}: {{totalHoursOfDay}}
    </ion-title>
</ion-toolbar>
       {{ currentDate.getDate() }} {{currentDate.getMonthName(true) }} | {{ "hours" | translate }}: {{totalHoursOfDay}}{{totalHoursOfDay}}
```

**Ionic info:** 

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Could you post a minimal repo we could use to reproduce this issue?

**Comment by mbakker96** [comment]
I can't reproduce this error in another repo. I need more investigation in my own code. I'm going to close this issue for now.

**Comment by mbakker96** [comment]
I reopen the issue because it looks like a problem in ionic. When I set `ion-toolbar` in `ion-header` then it works but when I do `ion-toolbar` lonely on the page it does not work. 

The problem is only on safari.

**Comment by mbakker96** [comment]
It is updating when I do an action on the page like scrolling a little bit.

**Comment by jgw96** [comment]
Hello

**Comment by jgw96** [comment]
Hey! So just to be clear this only happens when you do not have an ion-header on the page correct?

**Comment by mbakker96** [comment]
@jgw96 The problem happens when I use an `ion-toolbar` **without** `ion-header`. I fixed the problem with a timeOut but that is a workaround and not a fix. 

```typescript
this.selectedDateSubscribe = this.calendarService.$selectedDate.subscribe((selectedDate: Date) => {.    this.ref.detach();
       this.currentDate = selectedDate;
       setTimeout(() => {
           this.ref.reattach();
       }, 10);
       this.getHourEntries();
});
```

**Comment by manucorporat** [comment]
are you sure events fired by your service are zoned?

**Comment by manucorporat** [comment]
what is ` this.ref` ?

**Comment by mbakker96** [comment]
@manucorporat I don't now of all my events in the services are zoned. I just have a service that send a next with a date and I have a subscribe on that date in my hour entries component. Like the code below:
```
import {ChangeDetectorRef} from '@angular/core';

constructor(private alertCtrl: AlertController,
                private toastCtrl: ToastController,
                private ref: ChangeDetectorRef,
                private translate: TranslateService,
                private platform: Platform,
                private calendarService: CalendarService,
                private apiService: ApiService,
                private menu: MenuController,
                private projectService: ProjectService) {
        this.platform.ready().then(() => {
            this.platform.registerBackButtonAction(this.closeApp.bind(this), 1);
        });
    }

    public ngOnInit(): void {
        this.selectedDateSubscribe = this.calendarService.$selectedDate.subscribe((selectedDate: Date) => {
            this.ref.detach();
            this.currentDate = selectedDate;
            setTimeout(() => {
                this.ref.reattach();
            }, 1);
            this.getHourEntries();
        });
    }
```

**Comment by jgw96** [comment]
Hello @mbakker96 , thanks for all the info. Could you provide a minimal repo we could use to reproduce this issue?

**Comment by manucorporat** [comment]
well, you should know. angular 2 runs change detection when something happens inside Zone, otherwise changes are not registered. Looks like you service is not firing the events inside Zone.

Try injecting NgZone as provider, then use:
```
this.zone.run(()=> fireEvent());
```


ie, use `this.zone.run()` instead of `timeout()`
