### ISSUE TITLE
Pinned repositorys

### ISSUE THREAD

**Issue by MTechDE** [driftyco/ionic#11316]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

GitHub for mobile phones dont let you see all projects for a company/group. Only the pinned projects.
When I want to see for example the CLI repo I have to enter the URL or I have to switch to the Desktop version.

**Expected behavior:**

Please add the CLI, Site and app-script repos to the pinned repositorys so useres can access them from the mobile GitHub page.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by MTechDE** [comment]
The repo overview tab have actually over 160 repos. So it would be easier to navigate to the main repos by the pinned tab.

**Comment by jgw96** [comment]
Good suggestion! Just talked to the org admin now about this.
