### ISSUE TITLE
Ionic 3 slow device/ionic view load times

### ISSUE THREAD

**Issue by Rockforced** [driftyco/ionic#11312]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
This started happening after I upgraded from ionic 2 to ionic 3.0.1 -- it takes roughly 2-3 minutes for the app to load viewing it on Ionic View. When I downgrade to ionic 2, it's almost instantaneous.

**Expected behavior:**
Ionic 3 load time on ionic view and device should be be consistent, if not faster, than Ionic 2

**Steps to reproduce:**
Upgrade from ionic 2 to 3.0.1

**Related code:**
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.34",
    "angularfire2": "^2.0.0-beta.8",
    "chart.js": "^2.5.0",
    "firebase": "^3.7.2",
    "ionic-native": "2.8.1",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.1
Xcode version: Not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#216

**Comment by Rockforced** [comment]
Yeah, this issue is fixed with ionic 3.1.0. It was never really an Ionic view issue so I'm not sure why you moved it here @jgw96
