### ISSUE TITLE
Android Emulator specify debug keystore.

### ISSUE THREAD

**Issue by ianlintner-wf** [driftyco/ionic#11311]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running emulate the application currently uses the default Android debug key when building the APK. 

**Expected behavior:**
The feature I would like is a ionic/build config to specify a different keystore.

**Steps to reproduce:**
ionic emulate android --live-reload --target="my-device"

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2127
