### ISSUE TITLE
feat: Close ion-select programmatically

### ISSUE THREAD

**Issue by haydenbr** [driftyco/ionic#11318]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I had a case where I would like it if the ion-select closed as soon as the user selects an option. After picking through the source code, I saw that I can open a select programmatically, but there is no way to close it. I realize it's kind of an edge case, but it's a nice-to-have in some cases.</span>

<span is-issue-template></span>

**Comment by astec** [comment]
You should use  `<ion-select interface="action-sheet">` - [docs](http://ionicframework.com/docs/api/components/select/Select/#options)

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#187

**Comment by haydenbr** [comment]
@jgw96 working on a PR for this right now.
