### ISSUE TITLE
Starting project with --v2 flag generates v3 project

### ISSUE THREAD

**Issue by anesumuz** [driftyco/ionic#11321]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Generating new project with --v2 flag starts a v3 project

**Expected behavior:**

I did not upgrade my CLI at any point so would expect -v2 flag to generate v2 app.
I would like to continue with v2 for now and would expect the same project structure with the --v2 flag.

**Steps to reproduce:**

**Related code:**

```
ionic start newApp --v2 
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.5
Xcode version: Not installed

```

**Comment by AmitMY** [comment]
Thanks for opening an issue with us.
Like Angular, ionic comes in two versions:
Ionic 1 - running AngularJS (hosted [here](https://github.com/driftyco/ionic-v1))
Ionic - running Angular

So when you tell the CLI to start `--v2`, it uses Ionic and not Ionic 1.
I would recommend using the [beta version ](http://blog.ionic.io/ionic-cli-v3-beta/)of the CLI, to avoid this confusion.

Is there a reason you don't want to work with Ionic v3? It is the same as ionic 2, with some improvements, and using Angular latest (4), which has its own benefits.

Note, that v2 is not longer maintained.

**Comment by ghenry22** [comment]
yep it's better to just look at ionic v3 as just the latest version of ionic2.  It's not the same as the ionic1 to ionic2 step.

**Comment by MTechDE** [comment]
Please don't use the CLI Beta versions... 
@AmitMY

In the forum they are so confused about the CLI 3.0 and Ionic Angular 3.0. For production builds never use a Beta version of anything.

**Comment by AmitMY** [comment]
@MTechDE I really like the CLI beta version. I don't have any bugs with it, and am using it on windows and mac.
For production build, there is no problem to use ionic cli beta, the way I see it.
Let's say you want to build for production:
`ionic cordova:build android --prod --release`
It first builds angular for AoT, then runs `cordova build android --prod --release`.
Nothing beta running under the hood.

**Comment by jgw96** [comment]
Hello, everyone! I would definitely recommend using the beta cli. It has some YUGEEEEE improvements over the current cli including faster installs, much-improved architecture under the hood, faster starting of new apps, faster builds etc etc etc. We are working extremely hard on this becoming the stable cli in the next few weeks but to accelerate this process I would urge that you guys give it a try and report any bugs [here](https://github.com/driftyco/ionic-cli). Also, this admittedly confusing naming issue of the `--v2` flag creating an `ionic-angular` v3 project is a thing of the past in the v3 cli. For now, I am going to close this issue as it has been fixed in cli v3.

**Comment by rubyjedi** [comment]
I like the CLIv3, but am a little miffed that "ionic serve --prod" no longer works.  I have to use "ionic cordova:run browser --prod" to get a browser-usable emulation.

I do this mostly to check the sanity of the build between the two modes before I start building and running on actual devices.
