### ISSUE TITLE
Ion-select returns model value as array instead of string

### ISSUE THREAD

**Issue by vazad28** [driftyco/ionic#11337]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On device and emulator, the ion-select return the model value as an array, while on chrome it returns the model value as string.

**Expected behavior:**
The model value should be string

**Steps to reproduce:**
Should be self descriptive from above.

**Related code:**

```
<ion-label>Select Template</ion-label>
<ion-select (ionChange)="loadCaseTemplate()" [(ngModel)]="selectedTmplKey"	multiple="false" [selectOptions]="{title:'Select Template'}">
	<ion-option *ngFor="let tmpl of templateService.surgeryTemplates$ | async" [value]="tmpl.id">{{tmpl.data.title}}</ion-option>
</ion-select>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic, we will look into this.

**Comment by CooleyGit** [comment]
Just updated to nightly 3.0.1-201704241659 and all my forms that were passing value as a string are now passing array.
