### ISSUE TITLE
Text input in modal requires double tap to get soft keyboard on Android 4

### ISSUE THREAD

**Issue by robdmoore** [driftyco/ionic#1133]
Hi,

If I put a form on a modal using nightly then on Android 4 when tapping one of the inputs it doesn't pull up the soft keyboard (there is a cursor in there though so the focus clearly happens) until a second tap.

Once the soft keyboard is up if you tap to another field then it's still OK.

I've replicated the problem here: http://plnkr.co/edit/cNJD8B0e2V6Ta4zHYLyH?p=preview

Thanks

**Comment by ParitoshVaidya** [comment]
Getting same issue on Moto e (1st Gen.) Android 4.4 Ionic v 1.3.16 Will let you know about other devices.

**Comment by ggeorg** [comment]
this seems to work for me:
```html

				<!-- iOS Cordova prefers <span> instead of: <label class="item item-input"> -->
				<span class="item item-input">
					<input data-ng-model="newEvent.name" type="text" placeholder="Event Name"
						required="true" autofocus="autofocus" autocomplete="off"
						autocorrect="off" autocapitalize="off" spellcheck="false"></input>
				</span>
```
