### ISSUE TITLE
Ionic.io Facebook auth gives empty name

### ISSUE THREAD

**Issue by Sroose** [driftyco/ionic#11334]
**Ionic version:** 
[ X ] **2.x**

**I'm submitting a ...** 
[ X ] bug report

**Current behavior:**
Using Ionic.io services, after logging in with Facebook, I can fetch the user through the ionic.io api, but the [details][name] object will be empty. The first and lastname can however be found in the [social] structure. Also at the client side, the 'User' object does not contain the name, only via the user.social srtructure.

**Expected behavior:**
I would expect the login methods to be transparent and the user.name / details.name objects always to be filled in regardless of the authentication provider. For comparison, when I log in at ionic.io dashboard, facebook users do have their name and email in the general details.
Is this a bug or is there a reason to work like this?

**Steps to reproduce:**
Just use the textbook examples of this.facebookAuth.login() and api.ionic.io calls.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud#201
