### ISSUE TITLE
Slides doc demo - Images not being loaded

### ISSUE THREAD

**Issue by edmundo096** [driftyco/ionic#11335]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Loading the Slides API doc demo, the images are not loaded, throwing error 404 in console.

**Expected behavior:**
The images in the Slides API doc demo should be loaded correctly.

**Steps to reproduce:**
Open the Slides API doc page on a desktop to show the demo Phone.
(Page is http://ionicframework.com/docs/api/components/slides/Slides/)
Result: The images inside the slides are not loaded.

**Related code:**
NA

**Other information:**
Seems that the images were moved to be in the `./assets` directory.
I previously submitted Pull request (#11314) with a quick correction, by modifying the Images `src`.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
NA

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1066
