### ISSUE TITLE
Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this._queue.push'

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#11338]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
We are using Sentry.io to log client errors. So far we've seen this error coming up for users of iOS 10.2 and 10.3
`Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this._queue.push'`

**Related code:**
My guess is this error has something todo with https://github.com/driftyco/ionic/blob/master/src/tap-click/activator.ts#L54

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.3
ios-deploy version: Not installed
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by manucorporat** [comment]
I think it is related with NavControllerBase, somehow it is being destroyed and used after that...
https://github.com/driftyco/ionic/blob/master/src/navigation/nav-controller-base.ts#L975

Maybe... destroyed while transitioning? I will add some unit tests to reproduce it and provide a fix as soon as possible. 

Thanks for the issue

**Comment by basvdijk** [comment]
In general I see a lot errors in Sentry of which I think are all related to toast and popups. Which might also be related to the NavController:
```
Error: Uncaught (in promise): false
  at g (/build/polyfills.js:3:7133)
  at l (/build/polyfills.js:3:6251)
  at l (/build/polyfills.js:3:5937)
  at None (/build/polyfills.js:3:6765)
  at t.invokeTask (/build/polyfills.js:3:15213)
```

```
Error: Uncaught (in promise): false
  at g (/android_asset/www/build/polyfills.js:3:7133)
  at l (/android_asset/www/build/polyfills.js:3:6251)
  at None (/android_asset/www/build/polyfills.js:3:5607)
  at Object.e.reject (/android_asset/www/build/main.js:25:10925)
  at t._postViewInit (/android_asset/www/build/main.js:25:13148)
```

**Comment by manucorporat** [comment]
Can you open new issues please?

**Comment by manucorporat** [comment]
@basvdijk are you using dismissOnPageChange: true?

**Comment by basvdijk** [comment]
As requested a new issue @ https://github.com/driftyco/ionic/issues/11341 and no I do not use `dismissOnPageChange: true`
