### ISSUE TITLE
[ionic-3] "/screen error 500 " in published web app 

### ISSUE THREAD

**Issue by yannbf** [driftyco/ionic#11345]
**Ionic version:**  (check one with "x") 
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report 

**Current behavior:**
So I recently published one of my apps online as a PWA but I noticed that on page startup I get the following error with no description whatsoever:
`screen:1 GET https://ioniccomponents.yannbraga.com/screen 500 ()`

Image:
![selection_260](https://cloud.githubusercontent.com/assets/1671563/25364776/21a7e770-293b-11e7-915c-4385ba7e2f7a.png)

**Expected behavior:**
I'm not sure what exactly should happen. It seems the web app tries to show a splash screen or something, but fails. The app continues to run okay, though, but the error is thrown.

**Steps to reproduce:**
I believe all you gotta do is publish a web app. I'm not sure if this is entirely attached to ionic 3 version, but it happened on mine and on others' apps I know too.

You can access mine and check the error: https://ioniccomponents.yannbraga.com

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

By the way, things are getting more and more awesome, thanks for the hard work you guys put into it!

**Comment by danielehrhardt** [comment]
Same issue here. Thank you for this Issue Post.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us and thanks for the nice comments! Would you be able to provide a minimal repo we could use to reproduce this? Also does this error happen when doing `ionic serve` ?

**Comment by yannbf** [comment]
Hey Justin, to be honest *any* newly created repo will throw that error. But just in case, this is the repo for the app which is running with the error: https://github.com/yannbf/ionic3-components

The error does not happen when I do `ionic serve`, and neither it does when I copy the resulting `www` folder after doing `ionic serve`. Problem is it's ideal to use the resulting `www` folder of `ionic build browser --prod`, which is way faster and provides minified code.

**Comment by danielehrhardt** [comment]
run 
`ionic platform add browser`
then
`ionic build browser --prod`
then open the index.html in the platforms/browser/www folder

**Comment by jgw96** [comment]
Hello, all! So we do not recommend using the cordova `browser` platform as it is still a work in progress. If you run `ionic build --prod` that will do a production build and then the resulting `www` folder is your PWA. You can check out [this gitbook](https://www.gitbook.com/book/jgw96/ionic-pwa/details) i made that walks you through how to make a PWA with ionic. Thanks!
