### ISSUE TITLE
Android Inputs Require Double Tap for Focus

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1134]
Several forum users are reporting that the Android keyboard is not appearing on input focus.  They are having to double tap in the input to get focus for keyboard to open.

http://forum.ionicframework.com/t/android-keyboard-not-always-appearing-on-input-focus/1591

This IS happening with the nightlies.  

NOTE : On the Beta, users were reporting that Android inputs would not receive focus and not activate the keyboard.  Switching to nightly improved matters but introduced the double tap problem.

**Comment by ParitoshVaidya** [comment]
Getting same issue on Moto e (1st Gen.) Android 4.4 Ionic v 1.3.16 Will let you know about other devices. Also posted this issue at #1133

**Comment by danschumann** [comment]
I have a completely unrelated project, and this happens for me only when I type a bunch of text into one field, and do not do any auto-complete stuff, then click another field.

The 2nd field gets focused, but the keyboard disappears and there is no caret.

If I select an auto-complete value on the first field, it works fine.

Is this an android bug?

**Comment by mubasshir** [comment]
any update to above?
@danschumann did you able to solve it?
