### ISSUE TITLE
Bug with color attribute and variables.scss

### ISSUE THREAD

**Issue by PanBachynskyi** [driftyco/ionic#11343]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I try to use color inside attribute from variables.scss but it doesn't works

**Steps to reproduce:**
add attribute color="primary" to span

**Related code:**

`<span color="primary">Back</span>`

**Ionic info:**:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.3 Build version 8E162

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by darthdie** [comment]
I believe the fix for this would be to add the `ion-text` attribute, i.e.

`<span ion-text color="primary">Back</span>`

This change was documented in the 3.0.0 breaking changes changelog section
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#breaking-changes

**Comment by PanBachynskyi** [comment]
Thanks! It works for me
