### ISSUE TITLE
ionic version 1.x  Https request does not work, but http request no problem

### ISSUE THREAD

**Issue by MGXu** [driftyco/ionic#11350]
Https request does not work, but http request no problem, this problem occurs in Brazil and Malaysia, in the United States and France are not any problems, I doubt whether the ssl certificate problem? What's the problem? Thank you

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
