### ISSUE TITLE
Check Page Before Open.

### ISSUE THREAD

**Issue by Bernardoow** [driftyco/ionic#11358]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi IONIC TEEEAM !!
Maybe it's a shit, but I will post it!
At my cenario IONIC Side Menu,  I want not reopen the same page if  it's open.
I just put a one check inside at openPage. (See related code).
Maybe its can be used in a  ionic template. 

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
    if(this.nav.getActive().component !== page.component){
      this.nav.setRoot(page.component);
    }
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.2
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
