### ISSUE TITLE
Disable SwipeBack for individual views

### ISSUE THREAD

**Issue by mikewagz** [driftyco/ionic#11365]
**Ionic version:**  (check one with "x")

[X] **3.x**

**I'm submitting a ...**  (check one with "x")

[X] feature request

**Current behavior:**

Currently SwipeToGoBack can be enabled/disabled via the directive on the ion-nav element, and the property can be retrieved via the canSwipeBack() function on the nav controller.

**Expected behavior:**

It would be very useful to be able to disable this functionality for certain pages/views.  For example, a photo editing page or map page that requires panning/swiping would not want a swipe back enabled.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#188

**Comment by dalemugford** [comment]
^ that link is dead. 💀
