### ISSUE TITLE
ion-range ionfocus does not work

### ISSUE THREAD

**Issue by huigesv123** [driftyco/ionic#11364]
**Ionic version:**  (check one with "x")
2.2.2

**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior:**
ion-range ionfocus does not work in Chrome 58.0.3029.81 when I use "ionic serve" mode.But "ionchange" work well
`<ion-range min="30" max="43" step="1" color="primary" (ionchange)="deviceZCTempSet()" (ionfocus)="deviceZCTempSetFocus()" (ionblur)="deviceZCTempSetBlur()"></ion-range>`

**Expected behavior:**
deviceZCTempSetFocus() will print data;

**Comment by petergerten** [comment]
same issue here

**Comment by jgw96** [comment]
Hello @huigesv123 , thanks for opening an issue with us. Could you try this with the latest [3.1.0](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#310-2017-04-26) release and see if that fixes the issue for you?

**Comment by huigesv123** [comment]
how to upgrade to 3.1.0 @jgw96

**Comment by heqiang421** [comment]
@huigesv123 see changelog.md

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
