### ISSUE TITLE
Ionic date input and ngModel stop working after push/pop

### ISSUE THREAD

**Issue by Substractive** [driftyco/ionic#11368]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ok I have push/pop mechanics for navigation.
I have encountered bug with date picker from ionic in 2 occasions.
First one was like this:
I came to the page for first time and it worked perfectly then i pushed onto new page and then pressed back button after that I tried to edit my date and it wasn't working.
Second bug behavior was this:
Last bug I described stopped working after push and going back. But this time it didn't work even on first page visit. Note that page was on 3rd push. It went like Home->Tools->Activity. It didn't work on Activity.

NOTE:
Model value is changed since i console.log model on ionChange but the model two way binding or whatever is not working since on my page changes are not reflected . The input stays blank even if I set default value for picker.

**Expected behavior:**

After changing model to reflect on html page as well.

**Steps to reproduce:**

**Related code:**

.ts
```
 endTime:string;
```

.html
```
<ion-item>
  <ion-label color="primary">DO</ion-label>
  <ion-datetime  displayFormat="HH:mm"  [(ngModel)]="endTime"></ion-datetime>
</ion-item>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by Substractive** [comment]
Found the reason why this happened. I had storage fetch in  ionViewWillEnter that caused the problems . I commented out that and now binding works. Any idea why would that cause problems?

**Comment by brandyscarney** [comment]
It's hard to help without seeing the code you are using to fetch the data, but since this seems more like a support question I will direct you to our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/). 🙂
