### ISSUE TITLE
Ionic 1.3.2 - I can't select text after adding on-swipe-right or on-swipe-left ion-content attributes

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#11369]
**Ionic version:**  (check one with "x")
[X ] **1.x** (1.3.2)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
after adding on-swipe-right or on-swipe-left attributes in ion-content we can't select text.

**Expected behavior:**
Able to select the text

**Steps to reproduce:**
http://codepen.io/anon/pen/pPNGye

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#248
