### ISSUE TITLE
bug: ion-title not centering

### ISSUE THREAD

**Issue by byronglendon** [driftyco/ionic#11376]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>ion-title is not centering the title text

<ion-header>
  <ion-navbar>
    <ion-title>My Title</ion-title>
  </ion-navbar> 
</ion-header>

I am using ionic serve and viewing in my Chrome browser.</span>

<span is-issue-template></span>

**Comment by Iyashu5040** [comment]
As far as I know, if the Ionic framework detects no mobile user agent it defaults to Android behaviour. On Android the Title is always left-aligned. In Chrome you can use the developer tools to view the app with different user agents. Using an iOS user agent will show a centered Title.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
