### ISSUE TITLE
$label-ios-text-color missing

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#11373]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There is no `$label-ios-text-color` sass variable. There are equivalents for md and wp.

**Expected behavior:**
A `$label-ios-text-color` variable is needed to be able to override label colors on ios like on other platforms.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by Iyashu5040** [comment]
I was making a repo for a different issue and decided to just add this one as well. Run this project with `ionic serve --lab` and compare Android and iOS, go to the Sign Up page and you'll see the color difference. The variables are set at the bottom of `variables.scss`. Here's the commit with the changes:
https://github.com/Iyashu5040/ionic-conference-app/commit/810a2574d07f6757db15a24ca546353f934c2c58

**Comment by brandyscarney** [comment]
The variable doesn't exist because we don't change the styling on the `iOS` label. We could add one that just styles `initial`, but if you wanted to match the way material design works it would be the following styling:

```
.item-input .label-ios,
.item-select .label-ios,
.item-datetime .label-ios {
  color: color($colors, primary);
}
```

**Comment by Iyashu5040** [comment]
Thanks for the clarification and the example, I appreciate it. Regarding adding the variable: I'd like to argue for adding it, for the sake of making customisation easier and more consistent across platforms.

**Comment by brandyscarney** [comment]
@Iyashu5040 I've added it back to master. Could you try out the following nightly and let me know if you have any issues?

```
npm install --save --save-exact ionic-angular@3.1.1-201704282222
```

**Comment by Iyashu5040** [comment]
Thanks @brandyscarney! I've tested with the nightly version and the style applies correctly.
