### ISSUE TITLE
Ionic 3.1.0 Menu Output Events Error

### ISSUE THREAD

**Issue by Nikoz47** [driftyco/ionic#11383]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
![image](https://cloud.githubusercontent.com/assets/24224073/25456982/505c39f6-2add-11e7-9c9c-601e3e23ee73.png)

**Expected behavior:**
In Ionic 3.0.1 Menu Output Events worked as expected.

**Related code:**

 ```
let menu = this.menuCtrl.get('menu');

    if (menu) {
      this.subscription.add(menu.ionOpen.subscribe(() => {
        this.map.setClickable(false);
      }));

      this.subscription.add(menu.ionClose.subscribe(() => {
        if (this.autocompleteSelected)
          this.map.setClickable(true);
        else return;
      }));
    }
```

**Other information:**
Errors:
1) Property 'ionOpen' does not exist on type 'Menu'.
2) Property 'ionClose' does not exist on type 'Menu'.

Maybe I'm overlooking something? I've just updated 3.0.1 to 3.1.0 and this error came out, I'm running the same code, I was at 3.0.1

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed

P.S: It's my first time opening issue, hope i've done everything correct, if not, please sorry :)

**Comment by jgw96** [comment]
Hello, great first issue and welcome to the Ionic Github! We will look into this regression.

**Comment by rapropos** [comment]
I think this was caused by the shift of `Menu` to an interface in [59eb9a3](https://github.com/driftyco/ionic/commit/59eb9a328d353326540d767921057a887058d66f#diff-3a5f6f00f8b1e4d464189fc60e72adb1).

**Comment by Nikoz47** [comment]
@rapropos That's true, thank you very much :)

I'll stick with this fix for now: https://github.com/Nikoz47/ionic/commit/0e0bf3a015352850fa6e8789fe5870082eb2b29d
