### ISSUE TITLE
Ionic 3.1.0 and custom aot build

### ISSUE THREAD

**Issue by ghaiat** [driftyco/ionic#11382]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
when custom building for aot with ionic 3.1.0 i got the following errors:

[9:45] 
ERROR in xxx/node_modules/ionic-angular/components/range/range.d.ts.Range.html (2,578): Property ‘_lblId’ does not exist on type ‘Range’.

ERROR in xxx/node_modules/ionic-angular/components/select/select-popover-component.d.ts.SelectPopover.html (3,5): Property ‘options’ is private and only accessible within class ‘SelectPopover’.

**Expected behavior:**
Be able to build without errors

**Comment by paulsouche** [comment]
Hi,

Same issue here

Property _lblId is used in template [here](https://github.com/driftyco/ionic/blob/master/src/components/range/range.ts#L95) without being declared in Range class. I'm not pretty confident about the solution ? Remove it or declare it in the class...

Property options is used in *ngFor [here](https://github.com/driftyco/ionic/blob/master/src/components/select/select-popover-component.ts#L17) and is private in generated dts. Make it public will solve the problem.

Thanks for the great job anyway

**Comment by manucorporat** [comment]
Fixed in 3.1.1
