### ISSUE TITLE
Secondary routes in Deeplink

### ISSUE THREAD

**Issue by hitpopdimestop** [driftyco/ionic#11385]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
When I construct a view from two or more pages (as I do it in angular) and then push another page to one of their navControllers, the new page covers the entire screen.

**Expected behavior:**
New page only covers a part of the screen.

Also, we should see secondary router links in the path. I'm building a PWA and there is a pretty complicated navigation. I googled a lot and couldn't find any evidence that it is possible to implement such kind of navigation with ionic right now. Have a look at this screenshot to understand better what I'm talking about:

<img width="1010" alt="screen shot 2017-04-26 at 16 11 10" src="https://cloud.githubusercontent.com/assets/20238682/25457253/5ba8e862-2ade-11e7-836b-fcd779fe1b00.png">

It doesn't seem that deeplinks have that power to accomplish my task right now. It would be great to add functionality to use secondary routes (or whatever they're going to be called in ionic). Thank you for your work and support!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#192

**Comment by hitpopdimestop** [comment]
Thanks for the reply! I guess it means that this functionality is not available yet in ionic. It's not an easy decision, but it might mean that unfortunately, we'll have to move to using just angular with cordova. However, I would love to hear any news regarding secondary links in ionic.

**Comment by hitpopdimestop** [comment]
@jgw96, I know that only less than a week passed, but is there any progress on this feature? And how can I get to know if something is being developed? Thank you!
