### ISSUE TITLE
Allow SASS map to be passed in the template

### ISSUE THREAD

**Issue by somnathbm** [driftyco/ionic#11390]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There's no way to specify SASS maps to be used in the value of the color attribute in the component template. By default **$colors** is the default SASS map for themeing and the only way to use other color is to modify the color value of the keys, which is okay so long your need is very simple and limited.

But suppose, my application would have a few theme selection option, and so I have set some custom SASS maps in variables.scss and named them other than **$colors**. Now I want to use primary color key from my custom map directly in the component template so that it would be much more easier to manipulate colors directly from the template in stead of several hacks or workarounds possible.
.
**Expected behavior:**

In the component template, it could be used like

`<ion-navbar [color]="{'myCustomMap': 'primary'}"></ion-navbar>`

**Steps to reproduce:**

Just add some SASS maps like the **$colors** in variables.scss file, now if you want to access different keys of your custom map, you will have no options.
**Related code:**

**variables.scss**
```
$colors: (
  primary:    #488aff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
);

$bluegray-lightgreen: (
  primary:         #546e7a,
  secondary:       #76ff03,
  primary-light:   #819ca9,
  primary-dark:    #29434e,
  secondary-light: #b0ff57,
  secondary-dark:  #32cb00,
  primary-text:    #ffffff,
  secondary-text:  #000000
);
```
Now I want to be able to use this new map in the template.

**anyTemplate.html**

```
<ion-navbar color="primary"></ion-navbar>
```
The color property will point to $colors map. So other than replacing vaues between these two maps, there is no clean solution for now except several workarounds.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.7.3
Xcode version: Not installed
```

I hope I was able to clarify my problem.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#189
