### ISSUE TITLE
docs: 404 on picker docs

### ISSUE THREAD

**Issue by aneeskodappana** [driftyco/ionic#11396]
**Type**: <span ionic-type>docs</span>
![capture](https://cloud.githubusercontent.com/assets/25400284/25473546/81865550-2b4d-11e7-8629-00b49e3834a3.PNG)

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Wrong URL reference of date picker docs</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1070
