### ISSUE TITLE
Allow higher minor&fix version of Angular in package.json

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#11398]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] feature request

**Current behavior:**
Ionic package.json pins to a specific Angular version without allowing to use higher fix & minor versions.

Is there any reason to pin `dependencies` to a strict Angular version?

Can you make it `"@angular/*": "^4.0.2"`? Same goes for Ionic Native that has "4.0.0".
On other hand `zone.js` has `"^0.8.5"` which seems better.

Would it harm if Ionic packages are bounded just by a specific major and a minimum minor versions and we can upgrade dependencies to bug fixes & minor updates without warnings?

Currently I'm able to specify higher versions of Angular but it gives warnings.

**Related code:**
```
"dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "ionicons": "~3.0.0",
    "rxjs": "5.1.1",
    "zone.js": "^0.8.5"
  },
```

**Other information:**
Related issue for Ionic Native: https://github.com/driftyco/ionic-native/issues/1427

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Not relevant.

**Comment by mhartington** [comment]
Hi there! So this has been brought up from time to time, and we always go back to pinning the packages to a specific version. Aside from some release that have broken things, we look at it from this perspective. 


User starts an app, with unpinned versions in the package.json. CLI runs npm install and WAM, a bunch of warnings/error messages about mismatched dependencies and things not lining up correctly. 

If this is a users first experience with Ionic, it's not really a good feeling when you see warnings and error massages being printed out.

For the sake of making sure *no* warnings/errors happen, and that all users get exactly what they need to start, we pin the dependencies.

This however does not mean **you** have to. If you start a project and want to to let npm handle things (risky IMO), add the `^` to your package.json. But for us, there's value in pinning them.
