### ISSUE TITLE
bug:An http request be sended twice

### ISSUE THREAD

**Issue by iSteveLiu** [driftyco/ionic#11399]
**Ionic version:3.1.0**  

**I'm submitting a bug report** 

**Current behavior:**
When I use http request in tabs page,it will be sended twice

**Related code:**
I defined a class,it exnteds NgHttp
```
let requestOptions = new RequestOptions({
      params: {
        username: params.username,
        password: params.password
      }
    })
    return this.http.post(Common.loginUrl,null,requestOptions)

 post(url: string, body: any, options?: RequestOptionsArgs): Observable<Response>{
    let ob = super.post(url,body,this.setHeaders(options))
    this.subscribe(ob)
    return ob
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
