### ISSUE TITLE
Can't find name 'ChangeDetectorRef'

### ISSUE THREAD

**Issue by ac3ju** [driftyco/ionic#11394]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi, I'm migrating an Ionic 2 app to Ionic 3, with Angular 4. And i'm getting an error : Can't find name 'ChangeDetectorRef in the constructors. It worked on the v2

**Related code:**

```
import { Component, Input, Output, OnInit, Inject, AfterViewInit, forwardRef, EventEmitter, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';

  constructor( @Inject(forwardRef(() => TimelineComponent)) private _parent: TimelineComponent, private cd: ChangeDetectorRef) {
    this.window = <Window>window;
}



Here my package.json :

"dependencies": {
"@angular/animations": "4.0.0",
"@angular/common": "4.0.0",
"@angular/compiler": "4.0.0",
"@angular/compiler-cli": "4.0.0",
"@angular/core": "4.0.0",
"@angular/forms": "4.0.0",
"@angular/http": "4.0.0",
"@angular/platform-browser": "4.0.0",
"@angular/platform-browser-dynamic": "4.0.0",
"@angular/platform-server": "4.0.0",
"@ionic-native/core": "3.4.2",
"@ionic-native/splash-screen": "3.4.2",
"@ionic-native/status-bar": "3.4.2",
"@ionic/storage": "2.0.1",
"@ngx-translate/core": "^6.0.1",
"@ngx-translate/http-loader": "0.0.3",
"install": "^0.8.8",
"intl": "^1.2.5",
"ionic-angular": "3.0.1",
"ionicons": "3.0.0",
"lodash": "^4.17.3",
"npm": "^4.5.0",
"pdfmake": "0.1.26",
"rxjs": "5.1.1",
"smoothscroll-polyfill": "0.3.4",
"sw-toolbox": "3.4.0",
"typings": "2.1.1",
"zone.js": "^0.8.4"  },
"devDependencies": {
"@ionic/app-scripts": "1.3.0",
"typescript": "~2.2.1",
"gulp": "^3.9.1",
"gulp-help": "^1.6.1",
"gulp-inject-string": "^1.1.0",
"gulp-load-plugins": "^1.4.0",
"gulp-replace-task": "^0.11.0",
"gulp-war": "^0.1.4",
"gulp-zip": "^4.0.0"
},


And ts.config
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es5",
      "es6",
      "dom",
      "es2015",
      "dom.iterable",
      "scripthost"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es2015",
    "skipLibCheck": true
  },
    "include": [
        "src/**/*.ts"
    ],
  "exclude": [
    "node_modules",
    "core-js"
  ],
    "compileOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    },
    "typeRoots": [
        "node_modules/@types"
    ]
}
```

**Other information:**
![image](https://cloud.githubusercontent.com/assets/17474490/25472461/a68ea46e-2b2b-11e7-8978-b7297e004798.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! If you remove the `private` declaration does this work?

**Comment by ac3ju** [comment]
Hello, finally I upgrated with the new version and now it works :)

"dependencies": {
"@angular/animations": "4.0.2",
"@angular/common": "4.0.2",
"@angular/compiler": "4.0.2",
"@angular/compiler-cli": "4.0.2",
"@angular/core": "4.0.2",
"@angular/forms": "4.0.2",
"@angular/http": "4.0.2",
"@angular/platform-browser": "4.0.2",
"@angular/platform-browser-dynamic": "4.0.2",
"@angular/platform-server": "4.0.2",
"@angular/tsc-wrapped": "4.1.0",
"@ionic/storage": "2.0.1",
"@ngx-translate/core": "^6.0.1",
"@ngx-translate/http-loader": "0.0.3",
"ionic-angular": "3.1.0",
"install": "^0.8.8",
"intl": "^1.2.5",
"ionicons": "~3.0.0",
"lodash": "^4.17.3",
"npm": "^4.5.0",
"pdfmake": "0.1.26",
"rxjs": "5.1.1",
"smoothscroll-polyfill": "0.3.4",
"sw-toolbox": "3.4.0",
"ng2-pdf-viewer": "1.0.2",
"zone.js": "^0.8.5"  },

**Comment by jgw96** [comment]
Awesome!
