### ISSUE TITLE
Improve Ion-Refresher to allow for manual triggering programatically

### ISSUE THREAD

**Issue by useitsoftware** [driftyco/ionic#11393]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Expected behavior:**
Improve Ion-Refresher to allow for manual triggering programatically

**Related code:**
could be on the way of:
```
@ViewChild(Content) content: Content;
...
this.content.TriggerPullToRefresh();
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#190

**Comment by mtshare** [comment]
This would be really awesome.
Currently the only way to do this is doing something like this:
```
@ViewChild(Refresher) refresher: Refresher;

...

this.refresher._top = '50px';
this.refresher.state = 'refreshing';
this.refresher._beginRefresh();
```

**Comment by mybluedog24** [comment]
Thanks for the great solution! Here is what I did to get the header height instead of using fixed 50px. Hope it helps:
```Javascript
<ion-header id="myheader">
...
</ion-header>
```
```Javascript
this.refresher._top = document.getElementById("myheader").offsetHeight+'px';
this.refresher.state = 'refreshing';
this.refresher._beginRefresh();
```
