### ISSUE TITLE
<ion-select interface="popover"> shows an alert instead of a popover

### ISSUE THREAD

**Issue by JosephCaillet** [driftyco/ionic#11407]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

As described [here,](http://ionicframework.com/docs/api/components/select/Select/), the `interface` attribute on an ion-select elemen cant takes the following values: `action-sheet`, `popover` and `alert`.

`action-sheet` and `alert` work as expected, but `popover` don't : I get an alert instead of a popover.

Live demo here : http://plnkr.co/edit/CAmhrkKVlVhsBdXCtlTj?p=preview

**Expected behavior:**

Get a popover when `interface` attribute is set to `popover` on an ion-select component.

**Steps to reproduce:**

Create a new project (I let the the default tab template), and edit the about page like this:
```
<ion-header>
	<ion-navbar>
		<ion-title>
			About
		</ion-title>
	</ion-navbar>
</ion-header>

<ion-content padding>
	<ion-item>
		<ion-label>Gender</ion-label>
		<ion-select interface="popover">
			<ion-option value="f">Female</ion-option>
			<ion-option value="m">Male</ion-option>
		</ion-select>
	</ion-item>
</ion-content>
```
Launch ionic serve, go to the about page, click on the gender select element. An alert is displayed, instead of a popover.

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.9.0
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have made a plunker here http://plnkr.co/edit/9TuWJMI9LMtOcq9c6ABY?p=preview that shows it working. The issue was that the plunker you linked too was not running Ionic 3.1.0. Thanks for using Ionic!

**Comment by JosephCaillet** [comment]
I updated to 3.1.0, problem solved, thanks you ! :)

**Comment by niravjadatiya** [comment]
this plunker works well in browser but same code not working in my demo app it always opens alert not popover :(
currently i have 
ionic -v  is 2.2.2

**Comment by liuxinhu** [comment]
Hi. I also have this issue. I am using Ionic 2.1.0 and for some reason I cannot upgrade Ionic version. Is there a way to use popover select in the old version?

**Comment by JosephCaillet** [comment]
I am afraid that there is any no other way to do it...

**Comment by CottaLotties** [comment]
Excuse me, I still have the same issue even after upgrade. Maybe I have to include extra plugins or components?

**Comment by abrseq** [comment]
same issue here..Didn't have any issues so far for ion-select, suddenly when i served it today its not changing.

**Comment by fareshan** [comment]
I get the same issue when I open the ion-select programmatically using open()

**Comment by ArnoldMessifet** [comment]
I get the same issue as fareshan... any solution ?

**Comment by Sami-Haroon-Khan** [comment]
Working for me, below is my "package.json"
"dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/material": "^5.2.5",
    "@angular/material-moment-adapter": "^5.2.5",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/firebase": "^4.7.0",
    "@ionic-native/geolocation": "^4.7.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "@types/chart.js": "^2.7.21",
    "angular-in-memory-web-api": "^0.6.0",
    "angularfire2": "^5.0.0-rc.6",
    "chart.js": "^2.7.2",
    "cordova-android": "6.3.0",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-firebase": "^1.0.5",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "firebase": "^5.0.4",
    "hammerjs": "^2.0.8",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "material-design-icons": "^3.0.1",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-firebase": {}
    },
    "platforms": [
      "android"
    ]

**Comment by Sami-Haroon-Khan** [comment]
Working fine for me with following ionic/typescript versions.
"devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "2.4.2"
  }

**Comment by Naseem16** [comment]
In ionic 3.1.0 and above, if you navigate to the ion-select by pressing 'TAB' button and then press the 'Spacebar', it will show an alert box instead of showing a popover.

Please help.

**Comment by jhonycage** [comment]
@fareshan Did you manage how to fix it?

**Comment by fareshan** [comment]
@jhonycage I did not fix it. I just used the ngModelChange option to do what i wanted to do.

**Comment by tg4444** [comment]
@ArnoldMessifet 
> I get the same issue as fareshan... with a warning message "Interface cannot be "popover" without UIEvent" in the console... any solution ?

The select.open() method takes an event parameter. You should pass a value there. Maybe a click event that triggered the open(). Inside the code it just checks if an event is defined or not
