### ISSUE TITLE
floating ion-label not working with ion-checkbox

### ISSUE THREAD

**Issue by schilkyl** [driftyco/ionic#11416]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The floating label does not show correctly when used with a checkbox. It is pushed underneath the checkbox and all but hidden from view.

**Expected behavior:**

Unsure what the design would be as the checkbox exists wether checked or unchecked. Label possibly should exist in its minimized floating format on render.

**Steps to reproduce:**

**Related code:**

```
<ion-list>
  <ion-item>
    <ion-label>Working</ion-label>
    <ion-checkbox></ion-checkbox>
  </ion-item>
    
  <ion-item>
    <ion-label floating>Not Working</ion-label>
    <ion-checkbox></ion-checkbox>
  </ion-item>
</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.7.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Floating labels are not currently meant to be used with the checkbox component. Because of this I am going to close this issue for now.
