### ISSUE TITLE
BrowserAnimationsModule is included, but not found

### ISSUE THREAD

**Issue by jdell64** [driftyco/ionic#11415]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
Runtime Error
Uncaught (in promise): Error: Found the synthetic property @btnState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application. Error: Found the synthetic property @btnState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
```
I have installed and imported the BrowserAnimationsModule:

```
import {BrowserModule} from '@angular/platform-browser';
import {ErrorHandler, NgModule} from '@angular/core';
import {IonicApp, IonicErrorHandler, IonicModule} from 'ionic-angular';
import {SplashScreen} from '@ionic-native/splash-screen';
import {StatusBar} from '@ionic-native/status-bar';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
...


@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserAnimationsModule,
```

package.json:
``` 
"@angular/animations": "^4.0.2",
```

my view:

```
<div class="wizard-footer">
    <!--ERROR NEXT LINE:-->
    <ion-fab [@btnState] *ngIf="!isOnFirstStep()" left bottom>
      <button ion-fab (click)="back()">
        <ion-icon name="arrow-round-back"></ion-icon>
      </button>
    </ion-fab>
  </div>

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.3
Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by MTechDE** [comment]
You have to import the following:

```typescript
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
...
imports: [
    BrowserAnimationsModule,
    ...
  ]
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
