### ISSUE TITLE
(req). Disable deep linking for specific pages and defaultHistory should accept params

### ISSUE THREAD

**Issue by sfaizanh** [driftyco/ionic#11411]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

[x] feature request

IonicPage doesn't contain any property to disable deep so when universal linking is enabled this page should not be accessible.
```
@IonicPage({disabled: true})
@Component({page: 'setting-page'})
```

```
@IonicPage({defaultHistory: ['Home', 'user/:id'] })
@Component({page: 'details-page'})
```
`localhost:8100/#/user/2/details`

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#191

**Comment by sfaizanh** [comment]
Appreciated! 👍

**Comment by patrickmcd** [comment]
@sfaizanh see if [this aligns with your thinking regarding params in defaultHistory](https://github.com/driftyco/ionic/issues/11377).

**Comment by sfaizanh** [comment]
@patrickmcd yeah same thing but i was thinking a bit more if we want object to pass then?
```
@IonicPage({defaultHistory: [{segment: 'Home', data: {} }, { segment: 'user/:id', data: {id: 2} }] })
@Component({page: 'details-page'})
```
