### ISSUE TITLE
running ionic 3.1.0 in chrome browser cannot find .ts file in the browser source folder for debugging

### ISSUE THREAD

**Issue by sandeepperkariappdev** [driftyco/ionic#11418]
**Ionic version:**  (check one with "x"
[x ] **3.5

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

running ionic 3.1.0 in chrome browser cannot find .ts file in the browser source folder for debugging
**Expected behavior:**
should be able to see ts files int he chrome dev tools that helps for debugging

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

![image](https://cloud.githubusercontent.com/assets/15526203/25502373/560297f6-2b64-11e7-88d6-49b40a8d87c8.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Ionic Framework: 3.1.0
Ionic App Scripts: 1.3.5
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 6.10.2
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed as part of app-scripts 1.3.6. To update you can run `npm install @ionic/app-scripts@1.3.6 --save-dev`.
