### ISSUE TITLE
ion-select shows all options selected when returning an object (Since v3.1.0)

### ISSUE THREAD

**Issue by dwm-it** [driftyco/ionic#11413]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you create a ion-select which returns an object, on option selection, it shows all options selected.

**Expected behavior:**
It should only show the right option selected.

**Steps to reproduce:**
http://plnkr.co/edit/g6fcC51oYn2rx38LcXzx?p=preview

**Other information:**
There was no problem with the previous version.

**Ionic info:** 

Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.9.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for opening an issue with us, i can confirm that this is an issue/breaking change
