### ISSUE TITLE
Update to Ionic to 3.1.0 doesn't appear to update the presented Ionic Framework version.

### ISSUE THREAD

**Issue by SusanKern** [driftyco/ionic#11412]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have updated to Ionic 3.1.0 per the instructions in the changelog.  However, when I run `ionic info`, the version shown "Ionic Framework Version" still says "3.0.1".

**Expected behavior:**
I would expect the version to say "3.1.0".

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: OS X El Capitan
Node Version: v7.8.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by MTechDE** [comment]
Have you deleted the node_modules folder before you updated your package.json?

You can follow my update guide if you have some problems: https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-1-0/87516

**Comment by SusanKern** [comment]
Following the update guide did fix the problem - several of the versions were different than I saw in the ChangeLog directions.   [Note:  I have found that when I delete the node_modules directory, I have to install Angular separately before running "npm install".  I am pretty new to npm, so it is likely that I am not understanding something completely.]

**Comment by MTechDE** [comment]
Yes, the changelog is already a bit out of date.

Nice that I could help you.
