### ISSUE TITLE
view not rendering from popover , code run successful  but view does nor change from popover 

### ISSUE THREAD

**Issue by faisalsaghir7** [driftyco/ionic#11421]
Message on console is success but view does not change 

Ionic 2

 popover.html

<ion-list>

      <ion-item (click)="ProfilePage()">  
        <ion-icon name="md-person"></ion-icon>
        MY Profile
      </ion-item>
     
      <ion-item (click)="EasyPassaPage()">
        <ion-icon name="md-card"></ion-icon>
        Billing
      </ion-item>

      <ion-item (click)="OneTimeOrderPage()">
       <ion-icon name="md-cart"></ion-icon>
        My Orders
      </ion-item>

      <ion-item (click)="SingupPage()">
        <ion-icon name="md-log-out"></ion-icon>
        Logout
      </ion-item>

 </ion-list>

popover.ts

import { Component,ViewChild, ElementRef  } from '@angular/core';
import { App, MenuController,NavController,NavParams,PopoverController } from 'ionic-angular';
import { MyprofilePage } from '../myprofile/myprofile';
import { billingPage } from '../billing/billing';
import { OneTimeOrderPage } from '../onetimeorder/onetimeorder';
import { SignupPage } from '../signup/signup';

@Component({
  templateUrl: './popover.html'
})
export class PopoverPage {

  constructor(private navParams: NavParams,public navCtrl:NavController) {
  }

  ngOnInit() {  
  }

ProfilePage()
{
this.navCtrl.setRoot(MyprofilePage);
console.log("Success");
}

EasyPassaPage()
{
  this.navCtrl.setRoot(billingPage);
  console.log("Success");
}

OneTimeOrderPage()
{
  this.navCtrl.setRoot(OneTimeOrderPage);
  console.log("Success");
}

SingupPage()
{
  this.navCtrl.setRoot(SignupPage);
  console.log("Success");
}

}

its a function of popover      (click)="presentPopover($event)"

Message on console is success but view does not change

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by faisalsaghir7** [comment]
i don't understand what are u saying ...... ? :( 
tell me what should i do , y its not rendering a page from popover ?
