### ISSUE TITLE
Ionic 3 Navbar back button overlays title or not visible

### ISSUE THREAD

**Issue by adappter** [driftyco/ionic#11426]
Hello,
I have an App created with the Tabs example of Ionic. 
My tabs doesnt have any <ion-header> instead of one. If I'm chossing this one the header is showing and the title is visible.
When I'm selecting an Item inside the selected tab with the header the navCtrl pushes the next view. Here is also an <ion-header> with title. But the back button overlays the title at iOS and on Android there is no Title  (see images)

Is there a workaround?

<img width="453" alt="screen shot 2017-04-28 at 12 44 27" src="https://cloud.githubusercontent.com/assets/20188615/25525705/74354690-2c10-11e7-9b32-a08cc57527a1.png">

<img width="380" alt="screen shot 2017-04-28 at 12 22 18" src="https://cloud.githubusercontent.com/assets/20188615/25525686/623b4e12-2c10-11e7-919c-1bcbdff4efe1.png">

this is what my header looks like

`<ion-header>
  <ion-navbar>
    <ion-title>
      Einstellungen
    </ion-title>
  </ion-navbar>
</ion-header>`

**Comment by manucorporat** [comment]
I have never seen that before. Can you run `ionic info`? Can you provide a complete template that reproduces the issue?

Are you using custom css that affects the header?

**Comment by adappter** [comment]
Hello :),

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.2 Build version 8E2002


My template:
Just create a tab app and add this to one of the pages:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Mehr
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list>

    <button ion-item (click)="showSettings()">
      <ion-icon name="settings"></ion-icon>
      Einstellungen
    </button>

    <button ion-item (click)="showNews()">
      <ion-icon name="paper"></ion-icon>
      News
    </button>

    <button ion-item (click)="showForum()">
      <ion-icon name="chatboxes"></ion-icon>
      Forum
    </button>

    <button ion-item (click)="showCalculator()">
      <ion-icon name="calculator"></ion-icon>
      Bußgeldrechner
    </button>

  </ion-list>
</ion-content>
```

And that is the template where the bug is. This will be pushed when "showSettings()" is called.
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Einstellungen
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content no-padding>
  <ion-grid no-padding>
    <ion-row>
      <ion-col>
        <button id="notifications" (click)="showNotifications()">
          <ion-icon class="settingsIcon" name="notifications"></ion-icon>
          Benachrichtigungen
        </button>
      </ion-col>
      <ion-col>
        <button id="purchase">
          <ion-icon class="settingsIcon" name="pricetag"></ion-icon>
          Pro Version
        </button>
      </ion-col>
    </ion-row>
    <ion-row>
      <ion-col>
        <button id="facebook">
          <ion-icon class="settingsIcon" name="facebook"></ion-icon>
          Facebook
        </button>
      </ion-col>
      <ion-col>
        <button id="user" (click)="showProfile()">
          <ion-icon class="settingsIcon" name="person"></ion-icon>
          Profil
        </button>
      </ion-col>
    </ion-row>
  </ion-grid>

</ion-content>
```
more.ts
```
@Component({
  selector: 'page-more',
  templateUrl: 'more.html',
  providers: [InAppBrowser]
})
export class MorePage {

  constructor(public navCtrl: NavController, private iab: InAppBrowser) {}

  showSettings() {
    this.navCtrl.push(SettingsPage);
  }

  showNews() {
    this.navCtrl.push(NewsPage);
  }

  showForum() {
    this.iab.create("http://forum.polizei-kontrollen.de/")
  }

  showCalculator(){
    this.iab.create("http://bussgeld-kontrolle.de/")
  }
}
```

**Comment by adappter** [comment]
Are these infos enough?

**Comment by adappter** [comment]
@jgw96 You reacted with thumbs down. Why? Is there anything missing?

**Comment by adappter** [comment]
Found the issue. Was indeed because of css. Closed :)
