### ISSUE TITLE
Need to click twice to select item from slide menu in iOS app 

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [driftyco/ionic#11423]
Ionic version:
Ionic Framework Version: 3.0.1

When I click on item from ionic slide menu, it doesn't work on first click
It works on second and sometimes on third click.
The same application is working fine in android

Current behavior:
Slide menu item's click work on second time or third time

Expected behavior:
It should work on first click in iOS app as well

Related code:
In app.html code

<ion-menu id="loggedInMenu" [content]="content">

<ion-item detail-push menuClose (click)="next()">

willy.dee

<ion-item detail-push class="item-height" menuClose *ngFor="let p of loggedInPages" (click)="openPage(p)">

{{p.title}}

    </ion-list>
</ion-content>

In app.component

export class MyApp {
@ViewChild(Nav) nav: Nav;
rootPage:any = SystemIdentifierPage;
loggedInPages: Array<{ title: string, icon: string, component: any }>;

constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen,
public menu: MenuController) {
platform.ready().then(() => {
// Okay, so the platform is ready and our plugins are available.
// Here you can do any higher level native things you might need.
statusBar.styleDefault();
splashScreen.hide();
});
this.loggedInPages = [
{ title: 'Home', icon: 'home', component: Home },
{ title: 'Message', icon: 'mail', component: MessagePage },
{ title: 'Entries', icon: 'paper', component: EntriesPage },
{ title: 'Pending Entries', icon: 'document', component: PendingEntriesPage },
{ title: 'Employees', icon: 'people', component: EmployeesPage },
{ title: 'Clients', icon: 'person', component: ClientList },
{ title: 'Search', icon: 'search', component: MySearch },
{ title: 'Logout', icon: 'log-out', component: LoginPage }
];
this.menu.enable(true, 'loggedInMenu');
}

**Comment by chandanch** [comment]
@Gurjit-ONEBCG For elements that are not clickable there is a delay of 300ms for the click event to file.
You will need to make it as a button and add the ion-item property to it. 
Refer to this code:
```html
<ion-menu>
  <ion-list>
    <button ion-item (click)="openPage1(p)">Item 1</button>
    <button ion-item (click)="openPage2(p)">Item2</button>
    <button ion-item (click)="openPage3(p)">Item3</button>
  </ion-list>
</ion-menu>
````
For more info refer to this link: http://ionicframework.com/docs/troubleshooting/#click-delays

**Comment by jgw96** [comment]
Hello @Gurjit-ONEBCG , could you try @chandanch solution and see if that solves the issue for you? Thanks!

**Comment by Gurjit-ONEBCG** [comment]
Thanks <button> worked in my case. But can you explain that if there is delay of 300 ms before the click event fire, then why it would not fired on first click even after the delay of 300 ms. But yes it fired when I clicked on second time after the delay of 300 ms

**Comment by Gurjit-ONEBCG** [comment]
Thanks < button  > tag worked for me

**Comment by daveshirman** [comment]
It should probably be mentioned more clearly in the documentation, especially on the menu component that adding the `tappable` attribute fixes this.  It's too easy to miss in the docs.

**Comment by jgw96** [comment]
Thanks all! @daveshirman ill talk to the docs people about this.
