### ISSUE TITLE
ionic lab always refresh app when save scss file.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [driftyco/ionic#11424]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.1.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ionic lab` always refresh app when save scss file.
Not a refresh scss and stay in the former page.
But it refresh to a home page, Like when you save a code.

**Expected behavior:**
Save scss and stay in the former page.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
