### ISSUE TITLE
Bug - Ionic 3 (ion-textarea) for iOS "Select | Select All | Paste" are not working

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#11438]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On an `<ion-textarea>` and under iOS, the user cannot perform `Select, Select All, Paste` actions.

**Expected behavior:**
The user should be able to do all the stated action on an `<ion-textarea>` as on the native one.

**Steps to reproduce:**
Simply put `<ion-textarea>` and try to run it under iOS, try to any dummy text and then try to edit it, select it or even copy/paste content (you won't be able to do it, that's the bug !)

**Note**
The issue may appear also in Android, I haven't test it yet!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.3.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by judithhartmann** [comment]
Did you put the `<ion-textarea>` in an ` <ion-item>`? I had this problem a while ago and this fixed it for me.

**Comment by HamzaLJ** [comment]
@judithhartmann Works like a charm using the way you suggested. I believe they need to talk about it in the official docs !
Thank you!
