### ISSUE TITLE
conflict with icons and slide component 

### ISSUE THREAD

**Issue by jmickvs** [driftyco/ionic#11434]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello, in my app I have a component where I use a slide and icons generated with the dependencie ionic2-custom-icons, I generate a list of these components, the first 2 items show it fine but if the list slide down the next items not show correctly because the slide component is showed over icons, the icons show it fine until I touch the slide image, next i show a gif of this issue

![20170428_105547](https://cloud.githubusercontent.com/assets/15081575/25540643/7814aa8e-2c11-11e7-8f38-3310f2da5706.gif)

**Expected behavior:**
I hope that in the item show icons over slide

thank you, regards.
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0                                                                                                                                                                  
Ionic CLI Version: 2.2.1                                                                                                                                                                        
Ionic App Lib Version: 2.2.0                                                                                                                                                                    
Ionic App Scripts Version: 1.3.4                                                                                                                                                                
ios-deploy version: Not installed                                                                                                                                                               
ios-sim version: Not installed                                                                                                                                                                  
OS: Linux 3.16                                                                                                                                                                                  
Node Version: v7.6.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question about an issue with your custom functionality I will urge that you ask this question on our [forum] (https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by jmickvs** [comment]
ok, thank you
