### ISSUE TITLE
VirtualScroll: add grid list and horizontal direction

### ISSUE THREAD

**Issue by plusCubed** [driftyco/ionic#11437]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
VirtualScroll only supports vertically scrolling lists. Lacking documentation for multi-column lists.

**Expected behavior:**
Add support/documentation for the same features as Ionic 1 Collection Repeat - [4 modes of dynamic/static list/grids with horizontal option](http://blog.ionic.io/collection-repeat-iteration-two/#improvementsinthenew).

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#196
