### ISSUE TITLE
bug: FormBuilder and ion-select : item is not selected

### ISSUE THREAD

**Issue by MisterEffix** [driftyco/ionic#11435]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the below example 'Banana' option is NOT selected.

It was working perfectly with Ionic 3.0.1

form: FormGroup;

  constructor(fb: FormBuilder) {
    this.form = fb.group({
      fruit: ["banana"],
    });
  }
  <form [formGroup]="form">
    <ion-select formControlName="fruit">
      <ion-option value="apple">apple</ion-option>
      <ion-option value="banana">banana</ion-option>
      <ion-option value="cherimoya">cherimoya</ion-option>
    </ion-select>
  </form>
All my packages are updated as mentioned here : https://github.com/driftyco/ionic/releases/tag/v3.1.0</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by radix21** [comment]
Hello there @MisterEffix , I'm having the same problem. have you found any fix?

**Comment by MisterEffix** [comment]
Yes it's solved in the last ionic version
