### ISSUE TITLE
Tabs are not really material

### ISSUE THREAD

**Issue by talamaska** [driftyco/ionic#11432]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[* ] **2.x**
[* ] **3.x**

**I'm submitting a ...**  (check one with "x")
[* ] bug report
[* ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The current tabs are more material-ish but definitely not material 

**Expected behavior:**
I expect it look exactly like on the google material page.

**Steps to reproduce:**
just run the demos

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting some screenshots of what you are seeing?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by talamaska** [comment]
![screenshot 2017-05-02 19 44 26](https://cloud.githubusercontent.com/assets/299973/25628813/36b59974-2f70-11e7-8f9e-ef4486aa6715.png)

**Comment by talamaska** [comment]
really, I just saw the email of you comment.
