### ISSUE TITLE
ion-select , overlapping event handlers.

### ISSUE THREAD

**Issue by gppraveena** [driftyco/ionic#11430]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
having multiple ion-select items in a page, refer the example code below. The event handler for the 2nd ion-select  over laps with the 1st one.  The issue is caused only when it is placed outside the ion-list.

**Expected behavior:**
Appropriate event handlers should be called. If I place the controls inside the ion-list then it works fine.

**Steps to reproduce:**

**Related code:**

```
<table>
        <tr>
                <ion-label padding-left class="link-btn" style="vertical-align:bottom;color:white;font-size:small">D</ion-label>
                <ion-select align="center" [(ngModel)]="d" (ionChange)="filterForD(d)">
                    <ion-option *ngFor="let d of dList" value="{{d}}">{{d}}</ion-option>
                </ion-select>
        </tr>
        <tr>
                <ion-label padding-left class="link-btn" style="vertical-align:bottom;color:white;font-size:small">A</ion-label>
                <ion-select  align="center" [(ngModel)]="a" (ionChange)="filterForA(a)">
                    <ion-option *ngFor="let a of aList" value="{{a}}">{{a}}</ion-option>
                </ion-select>
        </tr>
        <tr>
            <td width="100%">
                <ion-label padding-left class="link-btn" style="vertical-align:bottom;color:white;font-size:small">S</ion-label>
                <ion-row padding-left *ngFor="let s of selectedS">
                    <button ion-button no-padding clear color="light" class="link-btn">{{ s.Name }}</button>
                </ion-row>
            </td>
        </tr>
    </table>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As our [docs show](https://ionicframework.com/docs/components/#select) you should have your `ion-select` components wrapped with `ion-item`. `ion-item` has some extra styling that `ion-select` needs to work correctly.
