### ISSUE TITLE
Feature Request - Slide from Right to Push Page

### ISSUE THREAD

**Issue by EWBears** [driftyco/ionic#11442]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request

**Current behavior:**
Feature Request - add ability to slide from right side of screen to push a new page, similar to the default swipe from left to pop previous page.

**Expected behavior:**
N/A

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
N/A

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#197
