### ISSUE TITLE
bug(deep-linking): undefined is not a function

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11457]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.1.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to use deep links errors catastrophically, when there is a match.
If I for example go to: `/#/blabla` it works, but `/#/actual` it errors like crazy.

console: 
- Native: tried calling Deeplinks.route, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
- `noMatch cordova_not_available` (on serve)
- ERROR TypeError: undefined is not a function
-  Error Context (Nav)
- Native: tried calling Deeplinks.route, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
- noMatch cordova_not_available
- Unhandled Promise rejection: undefined is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not a function
- Error: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
- Uncaught (in promise) TypeError: undefined is not a function
- Dev server logger closed
- WebSocket connection to 'ws://localhost:35729/livereload' failed

**Expected behavior:**
No errors

**Related code:**

```
let routes = {"/actual": ActualPage};
this.deepLinks.route(routes).subscribe((match) => {
    console.log("Successfully matched route", match);
}, (noMatch) => {
    console.log("noMatch", noMatch);
});
```

**Other information:**

> ERROR TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5)

> Unhandled Promise rejection: undefined is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5) TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5)

> Error: Uncaught (in promise): TypeError: undefined is not a function
> TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5)
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5)
>     at g (http://localhost:8100/build/polyfills.js:3:7133)
>     at l (http://localhost:8100/build/polyfills.js:3:6251)
>     at http://localhost:8100/build/polyfills.js:3:5607
>     at http://localhost:8100/build/polyfills.js:3:17487
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
>     at n.run (http://localhost:8100/build/polyfills.js:3:9741)
>     at http://localhost:8100/build/polyfills.js:3:6774
>     at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
>     at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
>     at a (http://localhost:8100/build/polyfills.js:3:5313)

> Uncaught (in promise) TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:104404:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:90911:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:90876:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:67375:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:31846:39)
>     at DeepLinker.initViews (http://localhost:8100/build/main.js:32020:21)
>     at Nav.ngAfterViewInit (http://localhost:8100/build/main.js:61016:33)
>     at callProviderLifecycles (http://localhost:8100/build/main.js:11331:18)
>     at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11306:13)
>     at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11290:17)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12312:5)
>     at callViewAction (http://localhost:8100/build/main.js:12619:17)
>     at execComponentViewsAction (http://localhost:8100/build/main.js:12565:13)
>     at checkAndUpdateView (http://localhost:8100/build/main.js:12310:5)
> 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.1.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0
    Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello @AmitMY is this issue in reference to the lazy loading in the framework or the deeplinking cordova plugin?

**Comment by AmitMY** [comment]
@jgw96 Yep I got confused. Can you please move this to `ionic-native`?

**Comment by jgw96** [comment]
No problem! Can do.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1453
