### ISSUE TITLE
About environment variables

### ISSUE THREAD

**Issue by jonatasfreitasv** [driftyco/ionic#11455]
I read a lot of posts/issues about using environment variables in Ionic2, but anyone conclusive, what is best way to use environment variables ?

**Comment by MTechDE** [comment]
Please ask questions like that in the Ionic forum

https://forum.ionicframework.com

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
