### ISSUE TITLE
Status of 10556

### ISSUE THREAD

**Issue by zoinkydoink** [driftyco/ionic#11468]
I dont know where else to post this but could i get a status update on whats happening with issue https://github.com/driftyco/ionic/issues/10556 I am desperately waiting for a workaround/solution because my app is deployed and being downloaded and the first thing my users notice is this bug.

I took the time to prepare a sample hoping it would be easier for u guys to provide a fix.

Thank you

**Comment by jgw96** [comment]
Hello @zoinkydoink , I am looking at #10556 now. Thanks for using Ionic!
