### ISSUE TITLE
Runtime error - Cannot redefine property: onCreateElementNsReady

### ISSUE THREAD

**Issue by pfefferf** [driftyco/ionic#11462]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I tried to upgrade a project from Ionic 2 to Ionic 3. Testing the app with "ionic serve" results in the error "Runtime error - Cannot redefine property: onCreateElementsNsReady" in the generated polyfill.js.
```
TypeError: Cannot redefine property: onCreateElementNsReady
    at Function.defineProperty (<anonymous>)
    at n (http://localhost:8100/build/polyfills.js:2:27758)
    at e (http://localhost:8100/build/polyfills.js:2:27878)
    at http://localhost:8100/build/polyfills.js:3:21185
    at http://localhost:8100/build/polyfills.js:3:21621
    at g.name (http://localhost:8100/build/polyfills.js:2:26826)
    at http://localhost:8100/build/polyfills.js:2:26882
    at n (http://localhost:8100/build/polyfills.js:1:65)
    at t.MyBundle (http://localhost:8100/build/polyfills.js:2:26764)
    at http://localhost:8100/build/polyfills.js:3:25344
``` 

**Expected behavior:**
No runtime error.

**Steps to reproduce:**
1) Having an existing Ionic 2 project.
2) Update dependencies to Ionic 3 requirements and adjust coding (e.g. import for BrowserModule).

**Related code:**

dependencies in package.json
```
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/core": "3.5.0",
    "@ionic-native/in-app-browser": "3.5.0",
    "@ionic-native/splash-screen": "3.5.0",
    "@ionic-native/status-bar": "3.5.0",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.5",
    "typescript": "~2.2.1"
  },
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic, we will look into this.

**Comment by jgw96** [comment]
Hello, unfortunately, we cannot reproduce this issue. Would you be able to share a minimal repo we could use to reproduce this?

**Comment by pfefferf** [comment]
Sorry, that is not possible. Will dissect the whole coding, maybe I can find some more details.
