### ISSUE TITLE
ion-slides page is hidden

### ISSUE THREAD

**Issue by E-Kom** [driftyco/ionic#11460]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

Hello I am using an ion-slides which renders properly except the pager is hidden because it is attributed "hide" class. Options are properly set : this.slides.pager = true;
**Expected behavior:**

The pager should be visible when pager option is set to true

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
