### ISSUE TITLE
Ionic installation

### ISSUE THREAD

**Issue by nikhildhar123** [driftyco/ionic#11471]
Not getting when I start with " ionic start myApp sidemenu  "  it does not create lib folder or sass

**Comment by nikhildhar123** [comment]
when I am running run bower install in  my app its displaying not present bower.json file in my app when I am searching in my app it is showing me these files in different places not in main app so cant run bower install

**Comment by Machareder** [comment]
use ionic start myApp sidemenu --v2

**Comment by nikhildhar123** [comment]
@Machareder same as it was before no change

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by nikhildhar123** [comment]
hey Hi guys I want to add data to data base so this is my code in ts  


constructor(public navCtrl: NavController,
    public http: Http,
    public NP: NavParams,
    public fb: FormBuilder,
    public toastCtrl: ToastController) {
    this.baseURI = "src/app/";
    
  }

  register() {  

    let body: string = "key=create&name=" + this.name + "&email=" + this.email + "&number=" + this.number + "&password=" + this.password,
      type: string = "application/x-www-form-urlencoded; charset=UTF-8",
      headers: any = new Headers({ 'Content-Type': type }),
      options: any = new RequestOptions({ headers: headers }),
      url: any = this.baseURI + "add-data.php";
}

but above its showing me an error of POST http://localhost:8100/src/app/add-data.php 404 (Not Found)


Please help me to fix this issue in my app folder i have made php file to connect with database and store the data
