### ISSUE TITLE
Ionic3/Angular4 template undefined value error is not catched by the Exception Handler

### ISSUE THREAD

**Issue by badpenguin** [driftyco/ionic#11475]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
An undefinied value inside a template does not trigger the exception handler.
The app becomes unresponsive. Angular detection stop working, i.e. ngOnChanges() never fires anymore.
I had to rollback to ionic2/angular2 to discover that the problem was the undefined value!

**Expected behavior:**
Show the standard Ionic/Angular popup message.

**Steps to reproduce:**
Try the code below into a component.

**Related code:**

```
<button *ngIf="item.rece_url.length>0" class="buybutton" (click)="doOpenUrl(item.rece_url)" ion-button small round>Compra Online</button>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v6.10.2

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Does this also happen in a plain angular app?

**Comment by davec21** [comment]
I wonder if this is related to my issue?
#11197

**Comment by badpenguin** [comment]
@jgw96 i will try with a blank template

**Comment by badpenguin** [comment]
@davec21 probably, my error was in the *ngIf

**Comment by jgw96** [comment]
@badpenguin any update on this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by davec21** [comment]
I think it's ultimately related to the issues that keep popping up. If there are template errors when things are being bound then there is no notification in the console to let you know why. 

In another comment you mentioned that it may be more of an Angular issue than ionic?
