### ISSUE TITLE
detail-push not applied to buttons with ion-item attribute

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#11474]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I've got a button styled with the `ion-item` attribute to make it look like an item. I want to show the detail push arrow on all platforms but the `detail-push` attribute doesn't work in this case.

**Expected behavior:**
The `detail-push` attribute should apply to elements with the `ion-item` attribute.

**Related code:**
```
 <button ion-item detail-push>
    <ion-avatar item-left>
      <img src="assets/images/mypic.jpg" alt="">
    </ion-avatar>
    <h2>ITEM TITLE</h2>
    <p text-wrap>Paragraph with some explanation.</p>
  </button>
```

**Other information:**
Setting the sass variables to show the detail push is overkill in this case, since I only need two buttons to have the detail and don't want them in the rest of my app on Android.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! By default, we do not put an arrow on `detail-push` items on our MD mode as that does not line up with the material design spec. The good thing is because we are web based and use css, you can just change a sass variable instead of the native way which you would not be able to easily change.
