### ISSUE TITLE
deeplinks lssus

### ISSUE THREAD

**Issue by hope7th** [driftyco/ionic#11486]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

when i go back form the Browser，it's always have Black screens,it's not very good look and the deeplinks is not very good.

otherwise ionic2 support the angular2's router or not?

and i can't open very quickly the website of login page  in  china. it's take me about 5 minutes open one single page. maybe it's great fire wall's fault. 

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
