### ISSUE TITLE
bug: ionic start is not downloading the latest

### ISSUE THREAD

**Issue by abusharaf** [driftyco/ionic#11498]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>if you start a new ionic application for example the below:-

ionic start sqlite-project blank

it will create a project but when you run this:-

npm install --save @ionic-native/sqlite as per the docs, it will not install correctly as the ionic-native version is not the latest one (3.6.1), it's actually 3.4.2</span>

<span is-issue-template></span>

**Comment by MTechDE** [comment]
Maybe that is a problem with your npm cache.

If you run `npm install --save @ionic-native/sqlite@latest` you should get the latest release

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1459
