### ISSUE TITLE
getContentDimensions missing in Ionic 3.1.1

### ISSUE THREAD

**Issue by meisterlampe** [driftyco/ionic#11495]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using
`this.viewCtrl.getIONContent().getContentDimensions().contentHeight`
to get the content height.
After Updating from Ionic 3.0.0 to 3.1.1 I get an error during transpilation, that there is no method `getContentDimensions()` in type `content`

> 

**Expected behavior:**
The code should compile as it does before

I checked the source and there was a change in commit 59eb9a3 in the file https://github.com/driftyco/ionic/blob/59eb9a328d353326540d767921057a887058d66f/src/navigation/view-controller.ts

After changing the imports in your code (view-controller.ts) from

`import { Content, Footer, Header, Navbar } from './nav-interfaces';`

to
```
import { Content } from '../components/content/content';
import { Footer, Header, Navbar } from './nav-interfaces';
```

Everything is working fine again. Can you have a look into this?

**Comment by meisterlampe** [comment]
Any feedback on this? Am I using totally wrong objects to retrieve the content height and should I better change my code instead of the framework? :)

**Comment by brandyscarney** [comment]
Thanks for the issue @meisterlampe! You shouldn't be using `getIONContent()` as this is an internal [(and should be hidden)](https://github.com/driftyco/ionic/blob/master/src/navigation/view-controller.ts#L334-L336) function. You should use [`getContent()`](http://ionicframework.com/docs/api/navigation/ViewController/#getContent) instead:

```
let height = this.viewCtrl.getContent().getContentDimensions().contentHeight;
console.log("Height", height);
```

I've confirmed that this is working fine. 🙂
