### ISSUE TITLE
Ionic build android

### ISSUE THREAD

**Issue by nikhildhar123** [driftyco/ionic#11504]
ionic cordova build android
Running app-scripts build: --iscordovaserve --externalIpRequired --nobrowser

[10:23:34]  build dev started ... 
[10:23:34]  clean started ... 
[10:23:34]  clean finished in 4 ms 
[10:23:34]  copy started ... 
[10:23:34]  transpile started ... 
[10:23:36]  transpile finished in 1.84 s 
[10:23:36]  preprocess started ... 
[10:23:36]  deeplinks started ... 
[10:23:36]  deeplinks finished in 13 ms 
[10:23:36]  preprocess finished in 14 ms 
[10:23:36]  webpack started ... 
[10:23:36]  copy finished in 1.97 s 
[10:23:43]  webpack finished in 6.91 s 
[10:23:43]  sass started ... 
[10:23:43]  sass finished in 740 ms 
[10:23:43]  postprocess started ... 
[10:23:43]  postprocess finished in 6 ms 
[10:23:43]  lint started ... 
[10:23:43]  build dev finished in 9.56 s 
⠼ running command: cordova build android [10:23:45]  lint finished in 1.75 s 
✖ running command: cordova build android - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build android (exit code 1):
        
        ANDROID_HOME=/opt/android-sdk/
        JAVA_HOME=/usr/lib/jvm/default-java
        Subproject Path: CordovaLib
        
        FAILURE: Build failed with an exception.
        
        * Where:
        Build file '/var/www/html/ionic/myApp/platforms/android/build.gradle' line: 20
        
        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        
        BUILD FAILED
        
        Total time: 1.006 secs
        Error: /var/www/html/ionic/myApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
        FAILURE: Build failed with an exception.
        
        * Where:
        Build file '/var/www/html/ionic/myApp/platforms/android/build.gradle' line: 20
        
        * What went wrong:
        A problem occurred evaluating root project 'android'.
        > java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by MTechDE** [comment]
Hey,
thank you for opening an Issue here.

Your issue relates to the Ionic  app-scripts and not to Ionic-Angular. Please close your issue and create a new one here: https://github.com/driftyco/ionic-app-scripts

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2212

**Comment by hichamrbib** [comment]
```
[ERROR] An error occurred while running cordova run and
roid (exit code 1).
```
**the same issue**
