### ISSUE TITLE
popToRoot removes root page

### ISSUE THREAD

**Issue by AndreasGassmann** [driftyco/ionic#11500]
**Ionic version:**  (check one with "x")
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

When using `popToRoot` on a root page, that page gets removed from the nav stack.

**Expected behavior:**

Calling `popToRoot` on the root page should not remove the root page from the nav stack. (do nothing)

**Steps to reproduce:**

http://plnkr.co/edit/7rWOPzOb3rUftEN0nYx6?p=preview

I made a pull request that fixes the issue #11499

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us and thanks for the PR! We will look into this and review the PR.

**Comment by manucorporat** [comment]
Fixes by @AndreasGassmann!
