### ISSUE TITLE
Generate pages/providers in a subfolder via command line

### ISSUE THREAD

**Issue by xMarkusSpringerx** [driftyco/ionic#11508]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I generate a provider/page via the console I can't create one in a subfolder.

**Expected behavior:**
If I type something like "ionic g provider db/test" I want that a subfolder with name "db" will be generated if it doesn't exist and the provider is generated in this folder.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by MTechDE** [comment]
Hey, 
thank you for opening an Issue here.

Your issue relates to the Ionic CLI and not to Ionic-Angular. Please close your issue and create a new one here:  https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2213
