### ISSUE TITLE
Image <img> unable to show properly, blank box

### ISSUE THREAD

**Issue by maplerichie** [driftyco/ionic#11507]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Issue occured in Android, iOS, Ionic View
I'm using ionic package to upload and build. The `<img src="assets/img/user.png">` unable to display correctly, The error show "Failed to load resource: The requested URL was not found on this server." The weird things is it can load for first <img> tag, but it can show in other <img>.
Example
Eg1: At login screen, the logo able to show, but the <img> in the next page (register screen) show blank.
Eg2: After login, restart app, the dashboard first <img> able to show, then the second <img> show blank again
Both example come out with error: "Failed to load resource: The requested URL was not found on this server."
I try to debug using GapDebug, the first image will load through (Android) "android_asset/www/assets/img/user.png", then the second one will just go to "assets/img/user.png" to find for image. The issue same with iOS as iOS will go to "var/containers/Bundle/Ap........"

**Expected behavior:**
The image `<img src="assets/img/user.png">` can show properly, it work on Desktop browser when "ionic serve -b"

**Related code:**
```
Both first and second image tag are
`<img src="assets/img/user.png">`
But like description, the first can work but not the following image
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.5.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Would you be able to make a minimal repo we could use to reproduce this issue?

**Comment by maplerichie** [comment]
@jgw96  
The issue have solved. Just change the IonicModule setting

    IonicModule.forRoot(MyApp, {
      activator: "ripple",
      swipeBackEnabled: true,
      tabsLayout: "title-hide", // 
      backButtonText: "",
      backButtonIcon: "md-arrow-back",
      //locationStrategy: "path",
      tabsHighlight: false,
      tabsHideOnSubPages: true
    }),

I refer to the ionic-conference-app, and try to comment out the locationStrategy:"path", and its work! Thanks
