### ISSUE TITLE
datetime returns object

### ISSUE THREAD

**Issue by njm250** [driftyco/ionic#11503]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using ngModel for ion-datetime, an object is returned.

**Expected behavior:**
The ionic documentation says "The value is simply a string".

**Steps to reproduce:**
See "Related code" below. When writing "selectedBirthdate" to the console, and object is returned instead of the expected string.

**Related code:**
in ts file:
public selectedBirthdate: string = "2000-01-01";

in html file:
<ion-datetime formControlName="birthdate" displayFormat="MM/DD/YYYY" min="1900-01-01" [(ngModel)]="selectedBirthdate"></ion-datetime>

**Other information:**
When writing output to the console, I get:
Object { year: 2000, month: 1, day: 2, hour: null, minute: null, second: null, millisecond: null, tzOffset: 0 }

**Comment by vukdavid** [comment]
This is fixed within 3.1.1 release.
Just upgrade to newest release. To be precise, update in package.json to:
"ionic-angular": "3.1.1"
run npm-install
