### ISSUE TITLE
ionic slider resize issue

### ISSUE THREAD

**Issue by esase** [driftyco/ionic#11518]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello when I use "autoHeight" for slider I have to call `slider.resize()` every time I change content dynamically. But  `slider.resize()`  doesn't work, I don't see any changes, new content looks clipped.	

If  I use `slider.update()` instead of resize it work properly. I think it's wrong use `slider.update()` 
for dynamic content changes.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
