### ISSUE TITLE
Update documentation to reflect dismiss behavior of e.g. toasts

### ISSUE THREAD

**Issue by icedt89** [driftyco/ionic#11512]
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**
[ ] bug report
[ X ] feature request
[ ] support request

**Current behavior:**
Ionic documentation does not give a clue about how one can distinguish between user initiated closing (click on close button) and automatic closing (after delay) of toasts.

The primary entry point for handling dismissal of a toast is attaching an event handler to the toast via
```
myToast.onDidDismiss(() => {});
```
as described in the current documentation found here:
http://ionicframework.com/docs/api/components/toast/ToastController

Only with trial and error and looking into the source code it was possible for me to discover the difference:

If the toast is closed automatically the second parameter of the callback function will receive "backdrop" as its value and "close" if the user clicked on the close button.

**Expected behavior:**
I expect that this should be clearly stated in the documentation http://ionicframework.com/docs/api/components/toast/ToastController/

**Related code:**

```
const myToast= this.toastController.create({
                            message: "Awesome Title",
                            duration: 3000,
                            position: "bottom",
                            closeButtonText: "Undo",
                            showCloseButton: true,
                        });

myToast.onDidDismiss((firstParameter, secondParameter) => {
/* secondParameter will either receive "backdrop" or "close" here :) */
                            console.log(secondParameter);
                        });

myToast.present();
```

**Comment by danielsogl** [comment]
> To dismiss the toast after creation, call the dismiss() method on the Toast instance. The onDidDismiss function can be called to perform an action after the toast is dismissed.

**Comment by icedt89** [comment]
As shown in my sample code i do not call 
```
dismiss([data], [role] [navOptions]).
```
I mean the callback supplied to
```
onDidDismiss(...)
```
It is unclear that the callback will receive any arguments.

**Comment by danielsogl** [comment]
I will have a look into this.

`return this._viewCtrl.dismiss(null, role, {disableApp: false});`

In my opinion, the first parameter could be removed because he does nothing (null).

**Comment by icedt89** [comment]
Yeah that will be fine too =D!

```
 /**
   * Called when the current viewController has be successfully dismissed
   */
  onDidDismiss(callback: Function) {
    this._onDidDismiss = callback;
  }
```
In my opinion, at least the method summary should be altered to or something similar:
```
 /**
   * Called when the current viewController has be successfully dismissed.
   * Signature: (role: string) Indicates the initiator for the dismissal ("backdrop", "close"...).
   */
```
I think e.g. VS Code or any other cool editor would then provide enough information via intellisense to assist the developer to alter application behavior dependent on the initiator of the dismissal.

Notwithstanding the official Ionic Framework documentation should mention this =)

**Comment by icedt89** [comment]
While digging through the source, it seems that this affects all inheritors of ViewController and not only toasts.

**Comment by jgw96** [comment]
Hello all! Good question @danielsogl . So if we look here https://github.com/driftyco/ionic/blob/master/src/navigation/view-controller.ts#L170 you will see that the first param of the dismiss method is `data`. Now, this is an optional param (hence the `?` in its type) but you have to pass something there or the order of the params would be messed up. The `onDidDismiss` method also has a data param as its first param. Does this answer everyones questions?

**Comment by icedt89** [comment]
Hi @jgw96,

i think my pull request will solve this issue for now, just merge it if you want.

As described in the issue, my only problem was that one must digg deep into the Ionic source code to find out that the callback which is passed to onDidDismiss and onWillDismiss will receive two parameters.

IMHO the developer should be able to learn about the method signature either from the official Ionic Framework documentation (which is... incomplete) or (maybe the better) from the source code directly through e.g. intellisense provided by all major code editors; which requires at least meaningful typescript method definitions and usage of data types.

Why define the callback as "Function" if every call of that callback will pass "(somethingA: any, somethingB: string)" =) i hope you know what i mean?

**Comment by manucorporat** [comment]
It's merged! thanks @icedt89
