### ISSUE TITLE
Add Support for Web Worker

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11511]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Web workers are great! And offers significant performance improvements.

Since Ionic 3 is based on Angular 4 which enable us to run complete app in web worker, it would be great if we could also run complete ionic app in web worker.

Have a look at the below answer:
http://stackoverflow.com/questions/43276044/angular-cli-generated-app-with-web-workers/43276045#43276045 

Also check the demo https://kaikcreator.github.io/angular-cli-web-worker/ and see the performance gain when using web worker.

Keeping in mind the performance challenges hybrid applications face, I believe some efforts in this area could make the framework comparable to the new frameworks like NativeScript.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I agree web workers are pretty awesome haha. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#200

**Comment by HugoHeneault** [comment]
The issue links to a 404 :(
What about it?
