### ISSUE TITLE
Blank or White screen with filestack module on Ionic2/3

### ISSUE THREAD

**Issue by mrvipinkashyap** [driftyco/ionic#11519]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[√ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ √] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am trying to implement filepicker functionality using this library on Ionic 2 app but after importing this library I am getting blank and white screen. This doesn't happen with any other 3rd party library I am using in my app.

**Steps to reproduce:**
Try following steps to reproduce this issue:
Install module using:
`npm install --save filestack-js` 

Import using following code in .ts file:
`import filestack from 'filestack-js';`
Doing `console.dir(filestack);` would show that module has been imported successfully. But you should see that you see blank/white screen if you are running app on `ionic serve`
I also tried following code to check if it is actually working:
```
const apikey = 'MY_FILESTACK_API_KEY';
const client = filestack.init(apikey);
client.pick({
    maxFiles: 20,
    fromSources: ['local_file_system', 'facebook'],
}).then(res => console.log(res));
```
Using above code I was able to see picker but on closing it still see that blank screen. I am not sure whether this is an issue with plugin or Ionic, so I am adding it to both. Please let me know if anyone else has came across similar error and managed to resolve this.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.3
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 8.1 Build version 8B6
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
