### ISSUE TITLE
iframe content scroll issue

### ISSUE THREAD

**Issue by pk1u** [driftyco/ionic#1151]
iframe content doesn't scroll properly when touch is initiated, eg, in the center of the content. It will scroll if touch is initiated on the left or right edge of the content. Not sure if this is related to closed issue <code>iframes block scrolling #306 </code>.

I'm using Ionic v1.0.1-beta, Cordova v3.4.1-0.1.0, iOS 7.1 .

eg, I replaced the <code>tab-dash.html</code> content, generated via <code>ionic start myApp tabs</code>, with:

```
<ion-view title="Dashboard">
  <ion-content scroll="true" class="has-header padding">
    <h1>Dashboard0</h1>

<iframe src="http://xkcd.com" style="width:100%;height:100%"></iframe>

  </ion-content>
</ion-view>
```

**Comment by jodybrewster** [comment]
+1

**Comment by jorgecasar** [comment]
I had the same issue and with this example I fixed https://github.com/alexgzhou/brandNewiCYL/commit/6d877424896394f78e7efaeccbbeddfb72b487a9

CSS:
```css
.iframe-wrapper iframe {
   width: 100%;
   height: 100%;
 }
```
HTML:
```html
<ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper">
   <iframe data-tap-disabled="true" src="{{iframeURL}}"></iframe>
</ion-content>
```

And about the YouTube iframes I guess it's because the video catch the tap event. I recommend you to use directly the video iframe in the correct size, then you don't have to do scroll. This is the full video url: https://www.youtube.com/v/{{videoId}}.

**Comment by jhjwind** [comment]
@jorgecasar solution works for me. Thanks!

**Comment by zckrs** [comment]
:+1: same issue

**Comment by Maddis1337** [comment]
+1 I tried the approach from @jorgecasar, but this only shows 30px of the iframe (disqus) and will not be able to resize once the content is loaded.

**Comment by jorgecasar** [comment]
@Maddis1337, can you post an example throw codepen and post it in the forum? http://forum.ionicframework.com/t/iframe-scroll-bug/196

**Comment by st3fanp** [comment]
We need to use Google DFP to place ads in our app. The problem is that DFP/GPT uses iframes to render ads, and when an ad is visible, the user cannot scroll further.

I cannot get this solution to work, an example of the problem can be seen in this codepen. When starting to scroll from within the black iframe, nothing happens.
http://codepen.io/anon/pen/bNLqqw

**Comment by jmoraleda** [comment]
+1 @jorgecasar ! Thank you

This made my day:
    <ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper">
       <iframe data-tap-disabled="true" src="{{iframeURL}}"></iframe>
    </ion-content>

**Comment by gere0018** [comment]
Thank you @jorgecasar  your solution solved my problem too.

**Comment by idhamperdameian** [comment]
@jorgecasar :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: Thank you

**Comment by rafasegat** [comment]
Great! Worked very well!

**Comment by slzr** [comment]
this works perfectly, but this give me another problem, because i have a nested ion-scroll in a ion-content, and when i make the ion-content overflow-scroll="true" the inner ion-scroll stops working
```html
<ion-content
  class           = "iframe-wrapper"
  delegate-handle = "mainScroll"
  scroll          = "true"
  overflow-scroll = "true"
>
  <ion-scroll
    delegate-handle = "innerScroll"
    direction       = "x"
    overflow-scroll = "true"
    scroll          = "true"
  >  
  <!-- JUST A HORIZONTAL SCROLL CONTENT -->
  </ion-scroll>
  <iframe data-tap-disabled="true" src="{{iframeURL}}"></iframe>
</ion-content>
```
any possible solution?

**Comment by sickermanex** [comment]
The content doesn't fit on the page the iframe does, but you have to scroll to both sides if there's any content, anybody found a solution to that issue?

**Comment by calevano** [comment]
<ion-content overflow-scroll="true"></ion-content>

**Comment by calevano** [comment]
overflow-scroll="true"

**Comment by rogercorrea** [comment]
Don't work for me.
I'm setting src property dinamically and continued the same problem.
But in other page with same code worked normally.
I don't understand...

The problem may be to configure dynamically src?

Code don't work:

<ion-view title="{{item.name}}">
    <ion-content scroll="true" overflow-scroll="true" class="has-header padding iframe-wrapper">
        <iframe data-tap-disabled="true" src="{{item.url}}"></iframe>
    </ion-content>
</ion-view>

Code work:

<ion-view view-title="Page title">
    <ion-content overflow-scroll="true" class="has-header padding iframe-wrapper">
        <iframe data-tap-disabled="true" src="https://www.x.com/page"></iframe>
    </ion-content>
</ion-view>

**Comment by rogercorrea** [comment]
Please,

This page work using Ionic and iframe:
https://www.ofertasagricolas.com.br/classificados/alimentos-em-geral

Others pages functioned normally.
I think that's when I moved the fingers on the image to link to the iframe crashes.

**Comment by aymanar** [comment]
Another solution is to place a div covering the iframe, that would catch the tap events. However, that will stop users from interacting with the iframe content.
