### ISSUE TITLE
input loses focus when keyboard is closed 

### ISSUE THREAD

**Issue by ejiyuan** [driftyco/ionic#11521]
Ionic version: (check one with "x")
[ ] 1.x
[x] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
When an input is focused, the keyboard is shown.
If the keyboard is closed (by clicking on the back button for exemple), the field loses the focus (there is no more the blinking bar)

Expected behavior:
Input should still have focus.

This works on a simple html page (like google.com). We are using an integrated barcode scanner, when we launch it the application (and so the input) loses the focus.
Outside ionic, the keyboard is closed and the scanned barcode is written in the input, but in ionic nothing is written, because the input has lost the focus.

Ionic info: (run ionic info from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by danielehrhardt** [comment]
You use the Barcode scanner wrong. Look at this example:
```html 
<ion-input [(ngModel)]="input" placeholder="Text Input"></ion-input>
```
```ts
input: string;

this.barcodeScanner.scan().then((barcodeData) => {
 // Success! Barcode data is here
this.input = barcodeData
}, (err) => {
    // An error occurred
});
```

**Comment by jgw96** [comment]
@ejiyuan , if you try @danielehrhardt example does it work for you?

**Comment by ejiyuan** [comment]
@jgw96 3q

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! After further review, this seems like more of a support question. Because of that I will urge that you ask this question on our forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
