### ISSUE TITLE
Independent Modules Instead of  Aggregate NgModule

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11527]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently all components of the framework are available in IonicModule. Angular 2 Material was also using the same approach until 2.0.0-beta.2 but in 2.0.0-beta.3 they removed the Aggregate NgModule (MaterialModule). Since it doesn't result in better tree shaking.

Have a look at their explanation https://github.com/angular/material2/blob/master/CHANGELOG.md#materialmodule

**Expected behavior:**

Can this approach also help Ionic 2? and help in reducing size?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#201
