### ISSUE TITLE
Why import {X1, X2} from 'ionic-native' has been removed 

### ISSUE THREAD

**Issue by edyrkaj** [driftyco/ionic#11524]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ X] **3.1.1**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I should add all native packages one by one on import statement.

**Expected behavior:**

Allow to import one by one or create an helper method on @ionic-native/{class} to get all available packages.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by themastersoda** [comment]
It has been done on purpose. Read this: http://blog.ionic.io/ionic-native-3-x/
