### ISSUE TITLE
docs: ion-radio & ion-checkbox - Select/deselect

### ISSUE THREAD

**Issue by farhanhoti** [driftyco/ionic#11523]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi all@Ionic!
I have a use case in my Ionic 2 application where user could
- Select a single option from a list (gonna use ion-radio)
- Deselect the selected option (ion-radio but deselect doesn't work and one always remains selected :( )
- Select multiple options from the same list (I m gonna use ion-checkbox)

I would also need help to detect the user selection in either case in TS file to further manipulate data.  
I know the same with JS/JQuery but stuck here :(

Could somebody help/ refer me to exact place??  
Thanks in advance!!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
