### ISSUE TITLE
Preloading Lazy Loaded Modules freezes app

### ISSUE THREAD

**Issue by Daskus1** [driftyco/ionic#11526]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
**Current behavior:**
I have an app with about 35 pages which I lazy load. 
I set `preloadModules` to `true` in `app.module.ts` which will preload about 20-25 pages when the app starts up. 
The app startup time is getting better using this pattern but now the app is unsusalbe for the first few seconds because the preloading process freezes the whole app. Once the process is done everything works fine.

I think this bug is even worse than a slow startuptime...

**Expected behavior:**
Preloading modules should not freeze the app or bring the app to lag. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.6.0
Xcode version: Not installed
```

**Comment by naveedahmed1** [comment]
This happens even with non-ionic Angular2 apps (preloading enabled) where you have a lot of components.

I would suggest setting **priority** of the pages as suggested at the bottom of the page. http://ionicframework.com/docs/api/navigation/IonicPage/

**Comment by jgw96** [comment]
@Daskus1 is this on an android device or an iPhone?

**Comment by Daskus1** [comment]
@jgw96 this happens on android device and also in my desktop browser (chrome). I have never tested it on iPone.

**Comment by jgw96** [comment]
@Daskus1 , did changing the priorities fix this issue for you?

**Comment by Daskus1** [comment]
@jgw96 I tried changing the priorities, but nothing changes... The app is still unusable for the first few seconds

**Comment by naveedahmed1** [comment]
I have over 50 pages and using lazy loading, my app loads in ~3 seconds on Nexus 6P and in ~6 seconds on nexus 4. (I am not using Preloading since its not a progressive app but just a mobile app and all scripts are bundled and its doesn't put any noticeable delay even on nexus 4).

**Comment by Daskus1** [comment]
@naveedahmed1 could you please try to add preloadModules and see if you can still use the app immediately after startup smoothly?

**Comment by naveedahmed1** [comment]
Are you following below guide?
https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit

I am following most of the steps described here, but not "Handling Components/Providers/Pipes" as described here. I have separate multiple modules for components. Though I group components related to a specific feature in one module.

**Comment by Daskus1** [comment]
@naveedahmed1 yes I have done it like you. Followed the guide for every page and since I have a lot of custom components/pipes (50+) I have multiple small modules for them which I only add to the page module where they the component/pipe is needed.
Lazyloading massively reduced my bundle size (from 3MB+ to almost 1MB) but the startuptime is still not as fast as I would like to have it and there is this problem with lagging the first few seconds.

**Comment by naveedahmed1** [comment]
What is the current load time? and on which device? BTW 1MB is the minimum I am able to achieve for my main bundle.

**Comment by Daskus1** [comment]
On a Samsung Galaxy A5 (Android 6) the loading time is about 6 seconds, on a Samsung Galaxy S3(Android 4.1.2) mini about 15 seconds.

**Comment by naveedahmed1** [comment]
I think A5 ~= to nexus 4 in terms of spec and I also have ~6 seconds load time on nexus 4.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! After further review, this seems like more of a support question. Because of this I will urge that you ask this question on our forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!

**Comment by imdadturi** [comment]
I still experience this issue.
