### ISSUE TITLE
'undefined is not a function' error happens very often for event functions in html 

### ISSUE THREAD

**Issue by samever7** [driftyco/ionic#11525]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

<button ion-button  item-right  (click)="onClick()">click</button>
Using this code, and when running as ionic run android --device, I got error below:

```
TypeError: undefined is not a function {ngDebugContext: DebugContext_, ngErrorLogger: function, stack: (...), message: "undefined is not a function"}Page.html:8 
View_Page_1 core.es5.js:13000 
DebugContext_.logError core.es5.js:1145 
ErrorHandler.handleError ionic-error-handler.js:63 
IonicErrorHandler.handleError  core.es5.js:4774 
ngZone.onError.subscribe.next core.es5.js:3848 
schedulerFn Subscriber.js:234 
SafeSubscriber.__tryOrUnsub Subscriber.js:183 
SafeSubscriber.next Subscriber.js:125 
Subscriber._next Subscriber.js:89 
Subscriber.next Subject.js:55 
Subject.next core.es5.js:3834 
EventEmitter.emit core.es5.js:4205 
NgZone.triggerError core.es5.js:4166 
inner.inner.fork.onHandleError polyfills.js:3 
t.handleError polyfills.js:3 
n.runTask polyfills.js:3 
invoke
```

**Expected behavior:**

It's not a issue that happen every time but 2 out of 3 will occur.

**Steps to reproduce:**

Just click and then click and again till it happens.

**Related code:**
Code logic is something like below:

```
<button ion-button  item-right  (click)="onClick()">click</button>
<ion-spinner *ngIf="running"></ion-spinner>

onClick() : void{
 this.running = !this.running;
}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```
But it's strange that when error happens for build at ionic serve, Ionic framework version is 3.0.1. Ok, it's another question for me already.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you post a repo we could use to reproduce this issue?

**Comment by samever7** [comment]
[https://github.com/samever7/ionic2-starter-sidemenu](url)

Please check this repo out and have a try.

It not only about the click but input and focus related issue I think.
Please see src/pages/home files to check the diffrence.

If it's a usage error please let me know, thank you.

**Comment by samever7** [comment]
And also in windows 7 with version below I re-create it out. Error like below, code is the same with repo.

Error:
```
TypeError: undefined is not a function
    at HomePage.onClick (http://localhost:8100/build/main.js:55617:26)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:314:24)
    at handleEvent (http://localhost:8100/build/main.js:12083:138)
    at callWithDebugContext (http://localhost:8100/build/main.js:13291:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/main.js:12879:12)
    at dispatchEvent (http://localhost:8100/build/main.js:9058:21)
    at http://localhost:8100/build/main.js:9648:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/main.js:33335:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12256)
    at Object.inner.inner.fork.onInvokeTask (http://localhost:8100/build/main.js:4394:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12215)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:7153)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:13213)
```


ionic info:

```
Your system information:

 ordova CLI: 7.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.3
Xcode version: Not installed

```

Which ''ordova CLI: 7.0.0" 
codova without c is all copied out from my output. Another strange thing.

**Comment by samever7** [comment]
OK, found the reason.

clearFocus is not a regular function of input.

Thank you and closed this issue.

**Comment by tayoraph** [comment]
please i need to re open this issue.
<ion-input> nd focus is not woriking on device but working on  browser . Also the submit button is giving the  below error ...




DailyDevotionalPage.html:309 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 56, nodeDef: Object, elDef: Object, elView: Object}
View_DailyDevotionalPage_21 @ DailyDevotionalPage.html:309
DebugContext_.logError @ core.es5.js:13426
ErrorHandler.handleError @ core.es5.js:1085
IonicErrorHandler.handleError @ ionic-error-handler.js:63
(anonymous) @ core.es5.js:9230
(anonymous) @ platform-browser.es5.js:2651
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.es5.js:3881
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2


please help me out i have been debugging this for days now.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. This does not appear to be a bug with the Ionic Framework.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If you can provide a link to your code, I would be happy to take a quick look and see if I can see anything wrong. I certainly suggest the above forums, however (with a link as well, no one will be able to offer much help if they can't see the code).

Thanks for using Ionic!
