### ISSUE TITLE
Allow IonicPageModule.forChild to accept Array of Pages

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11530]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently for each page we have to create a new NgModule for that page where we have to add IonicPageModule.forChild(MyPage) to imports.

**Expected behavior:**
What if IonicPageModule.forChild is changed to accepts array of pages. This would allow us to specify multiple pages related to a section to be added to the same NgModule. Like we can do with RouterModule.forChild in Angular 2.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#202

**Comment by naveedahmed1** [comment]
Thank you @jgw96 for the update. May be you could just share it with the team working on Lazyloading.
