### ISSUE TITLE
Virtual hardware buttons cover footer

### ISSUE THREAD

**Issue by bryantmakesprog** [driftyco/ionic#11534]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Our client has ordered this phone for their users (https://www.amazon.com/Motorola-Moto-XT1650-32GB-BLACK/dp/B01IW7N900). The phone features what we're calling 'virtual hardware buttons'. That is, the hardware buttons are rendered on screen, they aren't physical buttons on the phone. When the app loads, the hardware buttons cover the footer content. This is causing confusion among the users. 

Is there a way to account for these virtual buttons (beyond adding additional padding)? If not, we can add more padding, just wondering if anyone came across an elegant solution.

**Comment by jgw96** [comment]
Hey @bryantmakesprog , this is definitely an interesting issue. My nexus 6 also has software buttons (as they are standard in stock android), would you be able to share a repo i could use to reproduce this?

**Comment by bryantmakesprog** [comment]
I'll see if I can throw together something to reproduce the issue. We're scrounging for a device to replicate on :stuck_out_tongue_closed_eyes:

**Comment by jgw96** [comment]
😄 sounds good!

**Comment by ghenry22** [comment]
I have a HTC One M8 test device that also uses the "soft" hardware buttons but I don't have any issues with overlap over the footer in my app they are always underneath where they should be.

@jgw96  If there is a test repo I am also happy to spin it up on my device and provide results if that is helpful.

**Comment by jgw96** [comment]
@bryantmakesprog any luck on reproducing this? @ghenry22 I'd gladly share a repo you can use to reproduce this issue if I had one, but I have not been able to repro this issue at all haha

**Comment by ghenry22** [comment]
Yeh I can't reproduce in my personal project either

**Comment by bryantmakesprog** [comment]
@jgw96 @ghenry22 

My apologies, I haven't had a moment to generate something. Due to time constraints, we've just moved the footer content to somewhere other than the footer :stuck_out_tongue_closed_eyes: 

If y'all aren't seeing it I'd probably close this issue. It _is_ and issue, but _my_ issue is resolved :+1:
