### ISSUE TITLE
virtual scroll not refreshing on empty initialization 

### ISSUE THREAD

**Issue by raym0nd93** [driftyco/ionic#11532]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When initializing a virtual scroll list with empty values, to be filled with values later, the virtual scroll seems to disable and never show items. 

**Expected behavior:**
Expected virtual scroll to reset when the data changed, like described in the docs:

> The data that builds the templates within the virtual scroll. This is the same data that you'd pass to *ngFor. It's important to note that when this data has changed, then the entire virtual scroll is reset, which is an expensive operation and should be avoided if possible.

**Steps to reproduce:**
Initialize an empty list. Add item to the list with a delay.

**Related code:**

```
users = [];

  constructor() {
    setTimeout(() => {
      this.users.push({displayName: 'foo'});
    }, 3000);
  }

<ion-content>
  <ion-list [virtualScroll]="users" [approxItemHeight]="'50px'">
    <ion-item *virtualItem="let user">
      user.displayName: {{user.displayName}}
    </ion-item>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v4.2.6
Xcode version: Not installed
```

**Comment by astec** [comment]
You need to wrap your code inside `setTimeout()` with `zone.run()`.

```
  constructor(zone NgZone) {
    setTimeout(() => {
      this.zone.run(() => this.users.push({displayName: 'foo'}));
    }, 3000);
  }
```
This looks like a support request suitable for StackOverflow or forum.ionicframework.com.

**Comment by manucorporat** [comment]
Also, looks like you are using a old version, could you upgrade to 3.1.1?

**Comment by raym0nd93** [comment]
@astec that comment is not related to my issue. The settimeout works fine, do a console log and you will see the code gets executed. 

@manucorporat That fixed the issue, thanks

**Comment by AhsanAyaz** [comment]
Still facing the issue in Ionic 3.1.1
