### ISSUE TITLE
No way to export User details in Ionic Auth services

### ISSUE THREAD

**Issue by thepiyush13** [driftyco/ionic#11531]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Currently Ionic Auth Service : https://docs.ionic.io/services/auth/ allows us to save user data including login details to ionic cloud. It only allows us to view details for each user but has no way to bulk export this data out of the cloud. I could not find any export link or any related API for this. 
**Expected behavior:**

There should be an option to bulk export selected user data to formats such as excel or csv. In the absence of this feature, user data is essentially locked to cloud db and  any external use of this data becomes very hard if not practically impossible. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud#207
