### ISSUE TITLE
ion-select not rendered correctly when use 'ionic-app-scripts serve --prod'

### ISSUE THREAD

**Issue by zjhiphop** [driftyco/ionic#11538]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When use  'ionic-app-scripts serve --prod' to serve, the select component option value is not shown at all. Looks like this: 
![screen shot 2017-05-06 at 10 02 59](https://cloud.githubusercontent.com/assets/763008/25769116/4fa3f3dc-3244-11e7-900f-dd814e8001ef.png)

**Expected behavior:**

When use  'ionic-app-scripts serve' the select component rendered correctly like following: 
![screen shot 2017-05-06 at 10 16 12](https://cloud.githubusercontent.com/assets/763008/25769152/14d1ff1e-3245-11e7-8a67-cc7f9165a6dd.png)

**Steps to reproduce:**

1. Init a ionic3 project
2. Add an ion-select component with several options
3. Run 'ionic-app-scripts serve --prod'
4. Open the select component and u will see the result

**Related code:**

```
insert any relevant code here
      <ion-select name="time-select" [(ngModel)]="prop.value" mode="actionsheet" pattern="[0-9]+" cancelText="取消" okText="确定" #time="ngModel"
        required selectedText="{{prop.value}}分钟后">
        <ion-option checked="true">1</ion-option>
        <ion-option>5</ion-option>
        <ion-option>10</ion-option>
        <ion-option>15</ion-option>
        <ion-option>30</ion-option>
        <ion-option>45</ion-option>
      </ion-select>
```

**Other information:**

My related deps version like following:
```
   "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/device": "3.4.2",
    "@ionic-native/in-app-browser": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "^2.0.1",
    "ionic-angular": "3.0.1",
    "ionicons": "3.0.0",

    "typescript": "^2.2.2",
    "zone.js": "^0.8.4"

    
    // Dev Dependency
  "devDependencies": {
    "@ionic/app-scripts": "latest",
    "shelljs": "^0.7.6",
    "typescript": "latest",
    "webpack-bundle-analyzer": "^1.5.3"
  },
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.7.0
    ios-sim version: 4.1.1
    OS: macOS Sierra
    Node Version: v7.7.3
    Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by rapropos** [comment]
Perhaps related to [app-scripts #936](https://github.com/driftyco/ionic-app-scripts/issues/936).

**Comment by zjhiphop** [comment]
@rapropos I tried the ionic-treeshake solution, still got the same result.

**Comment by zjhiphop** [comment]
@alakra @mlynch @alexweber @ericb Can u guys help to verify and fix issue?

**Comment by zjhiphop** [comment]
I just found the root cause from Angular Docs: 
```
In development mode, tick() also performs a second change detection cycle (TTL=2) to ensure that no further changes are detected. If additional changes are picked up during this second cycle, bindings in the app have side-effects that cannot be resolved in a single change detection pass. In this case, Angular throws an error, since an Angular application can only have one change detection pass during which all change detection must complete.
```

That means when in development mode,  Angular will do model check every 2s. But in prod mode will not do.  

And with the ion-select render logic flow is:   
  *ion-select -> Alert Component -> load inputs by type*
The problems is the 'Alert Component' setting the 'inputType' in the *ionViewDidLoad* method. It's too late to let the Angular check the changes of 'inputType'.  So i would like to proposal a solution: update the 'inputType' value in constructor.

**Comment by zjhiphop** [comment]
Hey, guys, finally i found the root cause, it's caused by an scoped value not assigned correctly and it blocked all the model detect actions following.  But i didn't find any error consoled, that's really boring. Can u guys provide me some way to log the template errors too (even in prod mode)? Thanks.

**Comment by jgw96** [comment]
Hello @zjhiphop , unfortunately, some of this is due to Angular NGC (which the angular team builds and maintains, not ionic) having poor error logging in some cases. But for better error logging and source maps in a "prod" type build you can run `npm run ionic:build --aot` to get an NGC build but with source maps and un minified code.
