### ISSUE TITLE
Range-Component crashes

### ISSUE THREAD

**Issue by Blackscr33n** [driftyco/ionic#11545]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If I got an dynamic range-component and I set the maximum dynamically and then slides the button of the range-comp. the component crashes and it displays only a value from 0 to 1.

**Expected behavior:**
That the max-value doesn't change dynamically.

**Steps to reproduce:**
http://plnkr.co/edit/oUf6l6FQsLMwR5n4XQip?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v6.4.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by manucorporat** [comment]
If you don't want the max value to change, then do not change it:
```
      <ion-item>
        <ion-range min="0" max="{{todo.repeats}}" pin="true" [(ngModel)]="todo.repeats">
          <ion-label range-left>0</ion-label>
          <ion-label range-right>{{todo.repeats}}</ion-label>
        </ion-range>
      </ion-item>
```

just use another value in the [(ngModel)]

**Comment by Blackscr33n** [comment]
So if I got 30 items I have to create a new reference for each repeat?
