### ISSUE TITLE
ionic transition is not smooth 

### ISSUE THREAD

**Issue by superTerrorist** [driftyco/ionic#11548]
I'm working with ionic2 to build app for ios, but the page transition is not smooth.

**Comment by heqiang421** [comment]
Are you building in AOT mode?
`ionic run build:ios --prod`

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
