### ISSUE TITLE
ionic resources generated icon has error 

### ISSUE THREAD

**Issue by heqiang421** [driftyco/ionic#11544]
#### What version of the CLI are you using? Output of `ionic --version`

`2.2.3`

#### Short description of the problem:

 type ionic resources

i found icon is not right

![image](https://cloud.githubusercontent.com/assets/9245110/25782479/722a6432-337e-11e7-8d86-f6241da6df26.png)

The original picture is ok. i used default-pic

![image](https://cloud.githubusercontent.com/assets/9245110/25782483/9e8c6bf6-337e-11e7-9b75-f904cd068c0f.png)

#### What behavior are you expecting?

icon is right

#### package.json

```
 "dependencies": {
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/in-app-browser": "3.6.1",
    "@ionic-native/splash-screen": "3.6.1",
    "@ionic-native/status-bar": "3.6.1",
    "@ionic/storage": "2.0.1",
    "d3": "^4.5.0",
    "echarts": "^3.4.0",
    "ionic-angular": "3.1.1",
    "ionicons": "~3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "typescript": "~2.2.1"
  },

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2228
