### ISSUE TITLE
Ionic - Error: No component factory found for e on select component

### ISSUE THREAD

**Issue by songzhenghe** [driftyco/ionic#11549]
Have updated to ionic-angular to 3.1.1 which was to avail of the bug fix to do with an issue with the select component. See the following link

https://github.com/driftyco/ionic/issues/11427

Everything works fine locally, but when I run a browser prod build and deploy I am getting the following error when I click on a select drop down

No component factory found for e. Did you add it to @NgModule.entryComponents
Everything working fine locally, and no errors cropping up when I run the following command

ionic cordova build browser --prod

What is the issue? I know you usually get this issue when you create a component and fail to add it to the entry components. However, this is an ionic component so not sure why this error is cropping up.

Again, only get the error when clicking on the select drop down.

Any thoughts would be great. Also, below is my package.json

  "dependencies": {
    "@angular/animations": "^4.1.0",
    "@angular/common": "^4.1.0",
    "@angular/compiler": "^4.1.0",
    "@angular/compiler-cli": "^4.1.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "^4.1.0",
    "@angular/http": "^4.1.0",
    "@angular/platform-browser": "^4.1.0",
    "@angular/platform-browser-dynamic": "^4.1.0",
    "@angular/platform-server": "^4.1.0",
    "@ionic-native/badge": "^3.5.0",
    "@ionic-native/core": "^3.5.0",
    "@ionic-native/date-picker": "^3.5.0",
    "@ionic-native/device": "^3.5.0",
    "@ionic-native/diagnostic": "^3.5.0",
    "@ionic-native/geolocation": "^3.5.0",
    "@ionic-native/native-audio": "^3.5.0",
    "@ionic-native/splash-screen": "^3.5.0",
    "@ionic-native/status-bar": "^3.5.0",
    "@ionic/app-scripts": "^1.3.6",
    "@ionic/storage": "^2.0.1",
    "ajv": "^5.0.0",
    "angular2-moment": "^1.3.3",
    "chart.js": "^2.4.0",
    "crypto-js": "^3.1.9-1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "jsrsasign": "^7.1.3",
    "ng2-charts": "^1.5.0",
    "rxjs": "^5.3.0",
    "sw-toolbox": "^3.6.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.3.6",
    "@ionic/cli-plugin-cordova": "^1.0.0-beta1",
    "@ionic/cli-plugin-ionic-angular": "^1.0.0-beta1",
    "typescript": "~2.2.1"
  }

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This was a bug in app-scripts 1.3.6 and has been fixed in app-scripts 1.3.7! Also, just a suggestion, but I would recommend removing the `^` from the packages in your package.json as that may make your next `npm install` install versions of Angular that Ionic has not been tested to work with yet.
