### ISSUE TITLE
Floating label on ion-datetime always floats if it's in a formGroup or has ngModel

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#11547]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
A floating label on `<ion-datetime>` always floats above the input, even if no date is selected. This happens if the ion-datetime has `ngModel` or is in a `formGroup`. If it's neither, then it only floats when a date is selected (but then it becomes useless, as you can't actually get the value).

![screenshot](http://i.imgur.com/kRlgxL2.png)

**Expected behavior:**
The floating label should only float when a date is selected.

**Steps to reproduce:**
[See this plunker](http://plnkr.co/edit/jLTo2SHttFVqFpbfBlEA?p=preview)

**Related code:**
**Other information:**
I think the issue is in the [`hasValue()` method in base-input.ts](https://github.com/driftyco/ionic/blob/5fbca0ef7c5baa019d278f832c955efa72c75615/src/util/base-input.ts#L256). It returns true if the datetime has the "empty" date (which is just `{}`). Either ion-datetime should have null or undefined value until a date is selected, or it could override `hasValue()` and return false if the value is `{}`.

**Ionic info:**

```
> ionic info

Your system information:

 ordova CLI: 7.0.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.3
Xcode version: Not installed```

**Comment by gandrade74** [comment]
Same problem here.
