### ISSUE TITLE
ion-input and attribute directive

### ISSUE THREAD

**Issue by bogomips** [driftyco/ionic#11559]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ X] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi, I am using a custom directive to trim the content of an input field when the user types in it.
Everything  works fine with a pure html input tag, but it does not with ion-input. 
Is there a special way to make it work?

this is the directive code:
https://github.com/khashayar/ng-trim-value-accessor/blob/master/src/trim-value-accessor.ts

thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
