### ISSUE TITLE
Toasts not working on IOS

### ISSUE THREAD

**Issue by hitpopdimestop** [driftyco/ionic#11553]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After updating to Ionic 3.1.1 toasts stopped working on IOS. Still working fine on Android though.

**Expected behavior:**
Toasts working fine on both platforms

**Steps to reproduce:**
Can be reproduced only on IOS build.
-->

**Related code:**

```
this.showInfoToast(`Some toast text here`);

showInfoToast(message: string) {
    let icon = '\u2714 ';
    let toast = this.toastCtrl.create({
      message: icon + message,
      duration: 2000,
      position: "top",
      cssClass: "cartAddMessage"
    });
    toast.present();
  }
```
And CSS:
```
.cartAddMessage {
  .toast-top{
    border-radius: 0;
    text-align: center;
    width: 100%;
    font-size: 24px;
    background-color: rgba(91, 224, 137, 0.9);
    right: 0;
    left: 0;
  }
```

**Other information:**
[Link to the same issue on Ionic Forum](https://forum.ionicframework.com/t/ionic-3-1-1-toast-not-working-on-ios/89339)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 7.0.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Thanks for using Ionic! We will look into this issue.

**Comment by jgw96** [comment]
Hello @hitpopdimestop , without your custom styles (particularly the `right` and `left` styles) does the toast work? Also, could you post a screenshot of what you are seeing?

**Comment by hitpopdimestop** [comment]
@jgw96 - At first I commented out `right` and `left` styles - nothing changed. Then I removed `cssClass: "cartAddMessage"` parameter - same behavior. Then I tested it on ionic view and toast actually stopped working there also both on iPhone and on android phone. I push 'Add to Cart' button and badge counter changes but no toast visible. Here's the screen:
<img width="303" alt="screen shot 2017-05-08 at 21 29 14" src="https://cloud.githubusercontent.com/assets/20238682/25819090/7c77eeca-3435-11e7-8965-237db439e0a0.png">


And this is what happens when I run it all with `ionic serve --prod`:
<img width="307" alt="screen shot 2017-05-08 at 21 18 27" src="https://cloud.githubusercontent.com/assets/20238682/25818992/255eab38-3435-11e7-8f56-49be079e335f.png">

I'm working on this project since Ionic 2 rc.0 and since then the code of toasts hasn't changed even once. It's only on 3.1.1 we noticed the issue. 3.0.1 was totally fine and we skipped 3.1.0 because of the ion-datetime issues.

**Comment by jgw96** [comment]
Hmm, interesting. Could you post a minimal repo we could use to reproduce this issue? I, unfortunately, cannot reproduce on my end with our testing apps.

**Comment by hitpopdimestop** [comment]
@jgw96 Sorry for the late response. This issue seems to be gone completely with update to 3.2.0 and ionic-cli 3. Still have no clue what happened.

**Comment by astec** [comment]
@hitpopdimestop, would it make sense to close the issue then?

**Comment by hitpopdimestop** [comment]
@astec Sure, go ahead

**Comment by patrickmcd** [comment]
@hitpopdimestop I believe @astec is asking you to close it since you created the issue.

**Comment by hitpopdimestop** [comment]
@patrickmcd Ok, couldn't find the button at the top to close the issue, my bad
