### ISSUE TITLE
Ionic CLI reformatting config.xml and package.json

### ISSUE THREAD

**Issue by arcreative** [driftyco/ionic#11558]
**Ionic version:**  (check one with "x")
[X] **1.x**
[ ] **2.x**
[ ] **3.x**

Note: just the CLI, don't think the project version matters here

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ionic build ios` completely rewrites my `config.xml` and `package.json` files with trivial whitespace and other changes.  There could be breaking changes, but it's very hard to tell because everything is completely rearranged.

**Expected behavior:**
Leave my stuff alone!

**Steps to reproduce:**
run `ionic build ios`

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us. What version of the cli are you running? (you can get this info from running `ionic-info` in your project directory)

**Comment by arcreative** [comment]
Oops, sorry!

```
Your system information:

Cordova CLI: 7.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.8.5
ios-sim version: 3.1.1
OS: macOS Sierra
Node Version: v6.10.3
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
All good, thanks for the info! Would you mind installing the latest beta version of the cli (instructions [here](https://blog.ionic.io/ionic-cli-v3-beta/)) and seeing if you have the same issue? Also, just to confirm, you are using ionic 1 right?

**Comment by mburger81** [comment]
I can confirm cli often rewrites config.xml and git has big diffs. 
I'm using cli 3 rc2

**Comment by jgw96** [comment]
Hmm interesting. Going to go ahead and move this issue to the CLI repo then. Thanks for the info.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2230
