### ISSUE TITLE
Missing Plugin due to malicious plugin name

### ISSUE THREAD

**Issue by besi** [driftyco/ionic#11556]
**Ionic version: 3.x**
**I'm submitting a bug report**

**Current behavior:**

My app runs correctly in the browser, but when I deploy it to the simulator or the device I get the following error:

> Error: module cordova-plugin-secure-secureStorage.sjcl_ss not found Script

**Steps to reproduce:**

**Related code:**

I found the wrong reference in the created app at the following path:

    ~/Library/Developer/CoreSimulator/Devices/XYZ/data/Containers/Bundle/Application/ABC/MyProject.app/www/plugins/cordova-plugin-secure-storage/www/securestorage.js

```
cordova.define("cordova-plugin-secure-storage.SecureStorage", function(require, exports, module) {
var SecureStorage, SecureStorageiOS, SecureStorageAndroid, SecureStorageWindows, SecureStorageBrowser;
var sjcl_ss = cordova.require('cordova-plugin-secure-secureStorage.sjcl_ss');
```

The [original file `:-)`](https://github.com/Crypho/cordova-plugin-secure-storage/blob/v2.6.3/www/securestorage.js#L2) looks different:

    :-) var sjcl_ss = cordova.require('cordova-plugin-secure-storage.sjcl_ss');
    :-( var sjcl_ss = cordova.require('cordova-plugin-secure-secureStorage.sjcl_ss');

It appears that some contents of the file was not properly replaced so the name of the plugin is changed from `cordova-plugin-secure-storage.sjcl_ss` to `cordova-plugin-secure-secureStorage.sjcl_ss`, which then can't be found.

**Ionic info:**

```
Cordova CLI: 7.0.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0 
ios-dsim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

## Screenshot

![screen shot 2017-05-08 at 14 05 04](https://cloud.githubusercontent.com/assets/160412/25804671/1fcec726-33fd-11e7-9722-2e60d3b2a0ec.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this seems to be an issue with the secure-storage plugin I am going to close this issue for now and recommend that you open an issue on [that plugins repo](https://github.com/Crypho/cordova-plugin-secure-storage)

**Comment by besi** [comment]
@jgw96: I am not sure this is related to the secure-plugin solely since the line, which initially seems correct is changed during the build process:

**Good**: var sjcl_ss = cordova.require('cordova-plugin-secure-storage.sjcl_ss');
**Bad**:  var sjcl_ss = cordova.require('cordova-plugin-secure-secureStorage.sjcl_ss');
