### ISSUE TITLE
ion-input displays incorrect value after ngModel value changes.

### ISSUE THREAD

**Issue by JRod-T2R** [driftyco/ionic#11561]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In my UI I have an ion-input labeled Participant Name, with [(ngModel)]="participant.name", and a button labeled Add to List with (click)="addParticipant().  The user types a value for the input field and clicks the button to add the value to a list.  The button's click event calls addParticipant().  The addParticipant() function adds the value to the list and then sets participant.name=null in order to clear the ion-input field.  The problem is that no matter what value I set for participant.name the input field will not refresh with the new value, event after I make a call to ChangeDetectorRef.detectChanges().  See code and Plunker example below.

**Expected behavior:**

The expected result is that the ion-input field will be redrawn with the new value.  If the model changes, the UI should reflect the new state of the model.  Specially after the this.chgRef.detectChanges() call.  I was able to do this prior to Ionic version 3.0; I didn't even have to call the this.chgRef.detectChanges();

**Steps to reproduce:**
I don't know how to make a Plunker template for version 3.0 but, here is a demo of how it works with Ionic version 2.0:

http://plnkr.co/edit/cnsq7YnTAyYPl7onVXO6?p=preview

Try the same in version 3.1.1 and you will see a different result where the input field does't clear after adding to list.

**Related code:**

===Template===
  <ion-item>
    <ion-label floating>Participant Name</ion-label>
    <ion-input type="text" [(ngModel)]="participant.name"></ion-input>
  </ion-item>
  <ion-item>
    <button ion-button block color="secondary"
     (click)="addParticipant()">Add to List</button>
  </ion-item>

=== Component code ===
  addParticipant(){
    if(this.participant.name != null){
      var p = new Participant();
      p.name = this.participant.name;
      //Add a Participant to the top of the list
      this.pArray.splice(0, 0, p);
    }
   //clear the participan name by changing the model value.
    this.participant.name = null;  //also tried  this.participant.name = ''; 
     //trigger redraw
    this.chgRef.detectChanges();
  }

**Other information:**
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.2 Build version 8E2002

```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this issue.

**Comment by rapropos** [comment]
I tried to reproduce this and failed.

```
  <ion-input type="text" [(ngModel)]="participant.name"></ion-input>
  <button ion-button (click)="addParticipant()">add participant</button>

class Participant {
  name?: string;
}
  pArray = [] as Participant[];
  participant: Participant = {};
  addParticipant(): void {
    if (this.participant.name != null) {
      var p = new Participant();
      p.name = this.participant.name;
      this.pArray.splice(0, 0, p);
    }
    this.participant.name = null;
  }
```

Pressing the button clears the name input as expected, with no manual change detection required.

**Comment by jgw96** [comment]
@JRod-T2R would you mind posting an repo we could use to reproduce this issue?

**Comment by JRod-T2R** [comment]
I created a new project with v.3.1.1 and was not able to reproduce the error either.  My project was  originally created with v2.0 and then I followed the posted instructions to convert to v.3.1.1.  There is something in my project that is causing the problem with this new version.  I'm also experiencing the same behavior with the ion-select widget.  I used to be able to set the bind variable to null and it would clear the selected option.

**Comment by jgw96** [comment]
@JRod-T2R Could you make sure your package.json in your app matches [this one](https://github.com/driftyco/ionic2-app-base/blob/master/package.json). After checking that and making any changes run `rm -rf node_modules` and then `npm install`.

**Comment by JRod-T2R** [comment]
Well, the changes to the package.json didn't make a difference.  However, I found what was causing the problem.  As it turned out, I was including the following in my index.html file: 


  <script src="assets/jspdf.min.js"></script>
  
The moment I commented this line out, the problem went away.  This was working fine in V2.0.0  I need to find another way to include this javascript library in my project other than in the index.html.  I'm a pretty new Angular2 and TypeScript programmer so I appreciate any suggestions.  In the meantime, I think we can close this issue since its obviously my fault.

**Comment by jgw96** [comment]
Thanks for the update @JRod-T2R . Unfortunately, we cannot provide support for issues caused by third party libraries, but you could probably get some help from either our [forum](https://forum.ionicframework.com/) or our [slack](https://ionic-worldwide.slack.com/messages).

**Comment by JRod-T2R** [comment]
Got it.  Thank you and keep up the great work.
