### ISSUE TITLE
ionic2+ on low version of the android (<4.4) is not work, or style disorder.

### ISSUE THREAD

**Issue by Eusen** [driftyco/ionic#11568]
**Ionic version:**  (check one with "x")
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

1. The older version of Webkit does not support requestAnimationFrame, in the android (<4.4) version of the below complains:
```
return win [' __zone_symbol__requestAnimationFrame] (the callback);
return win [' __zone_symbol__cancelAnimationFrame] (rafId);
```
I replaced my requestAnimationFrame, then app can run.
This problem will cause ionic2+ project won't run, on low version of the android.

2. In the old version of Webkit, style will disorder. I think may be does not support the flex layout.
You can experiments in the android (<4.4) emulator.
I will put two pictures here.
[pictures 1](http://display.wei7star.com/img/ch1.png)
[pictures 2](http://display.wei7star.com/img/ch2.png)
oh, there're running on 4.1.2 effect

**Expected behavior:**

I can solve the first problem, but the second question I hope you can give me a solution.
Hope you can fix the problem.

**Steps to reproduce:**

**Related code:**
This is my solution to requestAnimationFrame:
```
 (function() {
      var lastTime = 0;
      var vendors = ['webkit', 'moz'];
      for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
        window.requestAnimationFrame = window[vendors[x] + 'RequestAnimationFrame'];
        window.cancelAnimationFrame = window[vendors[x] + 'CancelAnimationFrame'] ||
        window[vendors[x] + 'CancelRequestAnimationFrame'];
      }

      if (!window.requestAnimationFrame) {
          window.requestAnimationFrame = function(callback, element) {
            var currTime = new Date().getTime();
            var timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
            var id = window.setTimeout(function() {
                callback(currTime + timeToCall);
            }, timeToCall);
            lastTime = currTime + timeToCall;
            return id;
          };
      }
      if (!window.cancelAnimationFrame) {
          window.cancelAnimationFrame = function(id) {
              clearTimeout(id);
          };
      }
    }());
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cordova CLI: 7.0.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Just have a few questions here. I have a first generation Moto g that I do most of my android testing on that is running stock 4.4.4 android. On that device I am unfortunately not able to reproduce either the flexbox issues or the requestAnimationFrame issue. Also, to be clear we do include a requestAnimationFrame polyfill for older devices (although as [can i use](http://caniuse.com/#feat=requestanimationframe) shows, requestAnimationFrame has great support). What version of android exactly are you testing on? 4.4.2?

**Comment by Eusen** [comment]
yes, i testing on 4.1.2 with Android Emulator. And on 4.4.2, load is very slow and sometimes takes a long time to show up.

**Comment by metzc** [comment]
i am investigating the same problem right now. On api level 19 (4.4) it does work fine. On api level 16 (4.1) - which is the minimum supported version by Cordova (and i guess ionic as well) - it breaks. As far as i could see the problem is not in android 4.1 itself, but in a faulty polyfill (from the minified output):

```javascript
    t.requestAnimationFrame ||
      ((t.requestAnimationFrame =
        t.webkitRequestAnimationFrame), (t.cancelAnimationFrame =
        t.webkitCancelAnimationFrame ||
        t.webkitCancelRequestAnimationFrame), t.requestAnimationFrame ||
        (t.requestAnimationFrame = function(n, e) {
          var r = new Date().getTime(),
            o = Math.max(0, 16 - (r - lastTime)),
            i = t.setTimeout(function() {
              n(r + o);
            }, o);
          return (lastTime = r + o), i;
        }), t.cancelAnimationFrame ||
        (t.cancelAnimationFrame = function(t) {
          clearTimeout(t);
        }));
```

If i read the code correctly the var `lastTime` is indeed not defined (thats what the error message on the android console says), it. On other android versions this code is just not executed because the polyfill is not needed, thus no error. Looks like a minification issue though.

**Comment by metzc** [comment]
since this issues title is about android < 4.4 compatibility in general, i may add that apps still don't load, even if the polyfill issue is manually resolved. There is no error message but the app is stuck on a white screen. Tested with vanilla ionic app on android emulator api level 16 and 17. 19 is working just fine.

**Comment by jgw96** [comment]
Hello all! Thanks @Eusen and @metzc for the info, this helps clear up the issue. For reasons that I explain [here](https://github.com/driftyco/ionic/issues/11445#issuecomment-298348758) we require using crosswalk for Android below 4.4.4. Hope this clears up things for you all.
