### ISSUE TITLE
Cannot read property 'hasAttribute' of undefined

### ISSUE THREAD

**Issue by ngocongcan** [driftyco/ionic#11569]
Dear contributers,

I got this issues when lauching my app on browser today. Please help me to take a look into this . Thanks!

![slider-error](https://cloud.githubusercontent.com/assets/5197966/25838131/b8ee175e-34bb-11e7-890f-f165d7c6dd42.PNG)

**Comment by danielsogl** [comment]
@ngocongcan It would be helpful if you can show us your code.

And I can already tell you, that you want to access a value which is not defined or known.

**Comment by jgw96** [comment]
Hello! While we greatly appreciate you opening an issue with us I am going to close this issue and ask that you open a new one that has the issue template filled out, please. Thanks for using Ionic!

**Comment by sayanbrainium** [comment]
I have the solution:
Do like this

```
<ion-slides *ngIf="slideData && slideData.length" autoplay="5000" class="slideroption" pager="true"   loop="true" speed="300">
	  <ion-slide   *ngFor="let slide of slideData">
                <img src="{{slide.imag}}" />
          </ion-slide>
	</ion-slides>
```

**Comment by juntaforce** [comment]
Hi @sayanbrainium,
 If slideData is  async, its not work. 
`*ngFor="let slide of slideData | async"`
