### ISSUE TITLE
could you please add align-items-start to util?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#11562]
ionic theme is flex-box base,
so could you please add helpers such as `align-items-start` to util?

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#203
