### ISSUE TITLE
Getting error Unable to add plugins. Perhaps your version of Cordova is too old. Try updating 

### ISSUE THREAD

**Issue by sharmaNK** [driftyco/ionic#1156]
Hi,

while creating a project using command "ionic start projectname" , but I am getting a error :

Error: EACCES, open '/tmp/org.apache.cordova.device/package/package.json'
ERROR: Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again.
Exiting.

But My cordova version is 3.4.1-0.1.0 (which is infact the current version). 
And then when I use command :

$ cd myApp
$ ionic platform add ios

then I get an error :

/home/hduser/.cordova/lib/ios/cordova/3.4.1/bin/create: 33: /home/hduser/.cordova/lib/ios/cordova/3.4.1/bin/create: Syntax error: "(" unexpected
Error: /home/hduser/.cordova/lib/ios/cordova/3.4.1/bin/create: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/src/superspawn.js:126:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
Unable to add platform ios. Please see console for more info.

Please help.

**Comment by thakurinbox** [comment]
I am still having same issue while creating new app using "ionic start newapp tabs"

----
    Updated the hooks directory to have execute permissions
    Update Config.xml
    Initializing cordova project

    Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again. (CLI v1.7.10)

    Your system information:

    Cordova CLI: 5.4.1
    Gulp version:  CLI version 3.9.0
    Gulp local:
    Ionic Version: 1.1.1
    Ionic CLI Version: 1.7.10
    Ionic App Lib Version: 0.6.5
    ios-deploy version: 1.8.3
    ios-sim version: 5.0.4
    OS: Mac OS X El Capitan
    Node Version: v5.0.0
    Xcode version: Xcode 6.3.1 Build version 6D1002
--
Please check!
