### ISSUE TITLE
Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite!

### ISSUE THREAD

**Issue by CoderSquirrel** [driftyco/ionic#11574]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report (?)
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
i'm starting a simple app using requirejs to load the libraries, everything went most ok, but gives:
```
(index):28 Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.5.3/jqLite/nosel
    at ionic.bundle.js:13443
    at Object.JQLite [as element] (ionic.bundle.js:16254)
    at controller.js:65
    at ionic.bundle.js:32328
    at completeOutstandingRequest (ionic.bundle.js:19199)
    at ionic.bundle.js:19475
```

i know i supposed to change angular.elemente to querySelector, but i use a bunch of libs, how do i supposed to change the libs?

**Expected behavior:**
Load elements by id normali
**Steps to reproduce:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 7.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.6.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#252
