### ISSUE TITLE
can not edit the input

### ISSUE THREAD

**Issue by sagarnayak** [driftyco/ionic#11572]
the html is - 

```
<ion-content id="rootcontainer">
  <ion-avatar>
    <img id="logo" src="" />
  </ion-avatar>

  <ion-item>
    <ion-input type="text" placeholder="Username"></ion-input>
  </ion-item>
</ion-content>
```

and the scss are -

page-details {
#rootcontainer{
    width: 100%;
    height: 100%;
    background-image: url("https://images.pexels.com/photos/196216/pexels-photo-196216.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb");
    background-size: cover;
    background-repeat: no-repeat;
    overflow: auto;
}
#rootcontainer:after {
    content:'';
    top: 0;
    left: 0;
    z-index: 10;
    width: 100%;
    height: 100%;
    display: block;
    position: absolute;
    background:#007FFF;
    opacity: 0.2;
}
#logo{
    width: 150px;
    height: 150px;
    margin-top: 30%;
    margin-right: auto;
    margin-left: auto;
}
#username{
    margin-left: 10%;
    margin-right: 10%;
}
}
 i am unable to write anything on the input. please help.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
