### ISSUE TITLE
Ionic custom modal with native scroll

### ISSUE THREAD

**Issue by arondn2** [driftyco/ionic#11582]
Ionic version: 1.3.1
I'm submitting a bug report
Current behavior: I am trying to make a custom responsive modal with native scroll, without `ion-modal` directive, but with `$ionicModal` service. It works fine in desktop browsers, but in mobile browsers, the `touchmove` event in `div.modal-backdrop` is locking the scroll in the child element. I know that because removing this event in chrome’s console makes the modal work like I am expecting.

![screen shot 2017-05-09 at 2 50 13 pm](https://cloud.githubusercontent.com/assets/6246297/25867209/deaea6a6-34c6-11e7-85f4-62b7f2cf0fff.png)

Steps to reproduce: link to code here http://plnkr.co/edit/8KGnuj?p=preview. (open in a mobile browser or chrome’s device emulator).

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#253
