### ISSUE TITLE
ionViewDidLoad not called in custom component, but ngOnInit did get called

### ISSUE THREAD

**Issue by qiluo** [driftyco/ionic#11589]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a custom component. Another page referenced this component by using of component selector, like `<my-component></my-component>`

First I put some initialization code in `MyComponent:ionViewDidLoad`, but I found it never got called, then I tried to put those code into `ngOnInit()`, it worked. 
From the document, I supposed `ionViewDidLoad` and `ngOnInit` are same hook, the former is wrapper of latter

**Expected behavior:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.5
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by rapropos** [comment]
AFAIK, Ionic lifecycle events are only fired on pages: things that interact with the navigation system. They are not fired on embedded components.

**Comment by qiluo** [comment]
@rapropos if so, it would make sense, thanks for clarification

**Comment by brandyscarney** [comment]
Thanks for the issue! Our lifecycle events are only set up to work with Ionic pages, as rapropos said. 🙂  

We have some documentation on this here: http://ionicframework.com/docs/api/navigation/NavController/#lifecycle-events

If you have ideas for how we could improve this documentation, please create an issue on our [ionic-site repository](https://github.com/driftyco/ionic-site).

**Comment by bharathnallamothu** [comment]
i am not using ionic. i am justing angular app with cordova plugins. but i want to use  ionViewDidLeave() event ... where can i catch that event in normal angular app? @brandyscarney

**Comment by qiluo** [comment]
@bharathnallamothu since you're not using Ionic, you never receive ionViewDidLeave then. You can check Angular component lifecycle events, https://angular.io/guide/lifecycle-hooks, ngOnDestroy in your case
