### ISSUE TITLE
can not add android cordova in ionic app after updating ionic to 3.0.0 and cordova to 7.0.0

### ISSUE THREAD

**Issue by vipswelt** [driftyco/ionic#11596]
facing an issue while adding android platform to my ionic application

> D:\WorkSpace\Ionic_Projects\trapped_POC>cordova platform add android
> Using cordova-fetch for cordova-android@^6.2.3
> Error: Failed to fetch platform cordova-android@^6.2.3
> Probably this is either a connection problem, or platform spec is incorrect.
> Check your connection and platform name/version/URL.
> Error: cmd: Command failed with exit code ENOENT

in my .cordova/lib/npm_chache/cordova-android folder there is two folders 5.1.1 and 6.1.2 and i also tried following command

> cordova platform add android@5.1.1

but still getting same issue... i tried to do it with repository url same error exist.. what to do.. please help me...

**Comment by kabus202** [comment]
No problems here

**Comment by mburger81** [comment]
You intend `cordova platform REMOVE/RM android@5.1.1`??
I would suggest to remove cordova and node_modules folder and run
`npm install`
`ionic cordova run/emulate android `to install latest cordova-android@6.2.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
