### ISSUE TITLE
View is not updating after the second call of a page

### ISSUE THREAD

**Issue by mo-mueller** [driftyco/ionic#11590]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Last friday I had my last internship day in office. On that day my app has worked fine. I have pushed the app to gitlab and builded an APK File. Yesterday I have installed ionic on my home PC and cloned the gitlab repo. When I start the app now on the same phone, it is not working as expected and as the last day in office. Even when I install the APK which I have builded when everything was working it does not work anymore. I have described the problem already in ionic forum: [https://forum.ionicframework.com/t/view-is-not-updating-within-a-promise/89491](https://forum.ionicframework.com/t/view-is-not-updating-within-a-promise/89491) 

On top of that I have created a test function which has the same functionality as my normal function. I show you this function and the output in this video: [https://youtu.be/HaPB-VyBTeM](https://youtu.be/HaPB-VyBTeM)

The code of the test function is below.

I have updated all moduls and plugins. On top of that I have created a new ionic app with ionic start and pasted all my code and added all plugins and installed all modules with hand. But it is still not working and there are no errors in console.

**Expected behavior:**

The output of the second call of a page should be the same as on the first call. But if you are on the page and it works, then switch the page and then go back to the first page, this page does not work anymore.

**Steps to reproduce:**

I could not reproduce this with a new blank ionic app.

**Related code:**

The test function in my api service:

    test() {
        return this.get2();
    }

    get2() {
        var url = "https://httpbin.org/get";
        return new Promise((resolve, reject) => {
            this.http.get(url).map(res => res.json()).subscribe(
                data => {
                    resolve(data);
                },
                err => {
                    reject(err);
                }
            );
        });
    }

The test function you can see in the video:

    test: any;

    constructor(public navCtrl: NavController,
                public navParams: NavParams,
                public uiHelper: UiHelper,
                public api: ApiService,
                public zone: NgZone) {

        this.test = "Test1";
        this.testTest();
    }

    testTest() {
        this.test = "Test2";
        this.api.test().then(
            response => {
                this.test = "Test3";
                console.log(response);
            },
            err => {
                this.test = "Test4";
            }
        );
    }

(In the test function I forgot to use NgZone but like you can see in my forum post, I had NgZone in my original code and that was working neither.)

**Other information:**

[Forum Post](https://forum.ionicframework.com/t/view-is-not-updating-within-a-promise/89491) 
[Youtube Video with my problem](https://youtu.be/HaPB-VyBTeM)

I have tested it with "ionic run android --device" on my Samsung Galaxy S6 with Android 7.0. But my boss told me he has the same problem when he set up my code on a mac and then run the app on an iPhone. In the video I have used "chrome://inspect" in google chrome to debug the app with console. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 7.0.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.10.0
Xcode version: Not installed
```

**EDIT:**

I have updated everything for ionic 3.2, but still the same problem. The new ionic info:

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mo-mueller** [comment]
Hi! I fixed the problem 10 minutes ago. There was a bug on my start page because I tried to access a variable that was undefined and I did not check it with ngIf. But however I did not get any error messages with chrome://inspect, and that was the problem. But 10 minutes ago this error message suddenly appears and that was how I could fix the bug.
