### ISSUE TITLE
[REQUEST] Prevent Navbar from updating the App's title when view enters

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic#11595]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Whenever a view enters, if that view contains a `Navbar` (`<ion-navbar>`) then the `App`'s title is updated to the `Navbar`'s `ToolbarTitle` (`<ion-title>`).

**Expected behavior:**
There should be an optional way to prevent that behavior, keeping the current title when a view enters.

Use case: I'm developing a web app using Ionic and I want total control over the title shown in the browser's window/tab, which is currently not possible. The only workaround is to subscribe to the `viewDidEnter` event of *every* `NavController` used in the application and then manually resetting the title every time it emits.

A possible solution would be to add a prop to either `<ion-navbar>` or `<ion-title>` to disable the current behavior.

**Related code:**
https://github.com/driftyco/ionic/blob/59eb9a328d353326540d767921057a887058d66f/src/components/toolbar/navbar.ts#L135-L141

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0-rc.2
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0-rc.2
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.2
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jsayol** [comment]
I'd be happy to submit a PR if this is something you're considering adding.

I've been giving it some thought and I see 2 possible solutions:
1. As an input property on `Navbar`. For example:
```html
<ion-navbar updateAppTitle="false">
  <ion-title>Hello</ion-title>
</ion-navbar>
```
2. As an instance method on `App` to enable and disable the behavior. For example:
```ts
@Component({
  template: `<ion-nav [root]='rootPage'></ion-nav>`
})
export class AppComponent {
  constructor(private app: App) {
    // ...
    this.app.titleFromNavbar(false);
    // ...
  }
}
```

Both would default to the current behavior (`true`).

Personally I prefer option 2 since the user only has to call the method once and it's done. Option 1 would be interesting in order to disable the behavior for one specific navbar, but the user would need to add that property to all navbars in order to disable it app-wise.

Thoughts?

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#211
