### ISSUE TITLE
Swiper options still not working with Ionic: when is the update?

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#11594]
Hi all,

I want to use `paginationType: progress`, yet it's not working. Beside that: **autoplay is also not working**. We know that Ionic uses the _old version_. Could someone please help and fix this?

https://ionicframework.com/docs/api/components/slides/Slides/

Even the own documentation says it: "you can't use progress if you don't have pager = true", yet that does not work because Swiper is outdated when used in combination with Ionic.

```
  $scope.options = {
    autoplay: 1500,
    effect: 'coverflow',
    autoplayDisableOnInteraction: false,
    loop: false,
    pager: true,
    paginationType: 'progress',
    coverflow: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: true
    }
  };
```

How to get paginationType: "progress" and autoplay to work? @mhartington, could you help or give an update, please?

**Comment by brandyscarney** [comment]
What version of Ionic are you using? Seeing `$scope` makes me think this is v1, but the docs you linked to are for v2+.

**Comment by 1BJK903** [comment]
Hi there. It is indeed Ionic 1, yet autoplay always had worked before the last updates... and beside that, autoplay works when you touch the first slide manually... it suddenly starts the autoplay after you touch the first slide...

**Comment by jgw96** [comment]
Hello @1BJK903 , since this is an Ionic 1 issue I am going to move this issue to our Ionic 1 repo. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#256

**Comment by 1BJK903** [comment]
Someone who can help us out with this, please?
