### ISSUE TITLE
Bug: Back Button - Playlist Demo

### ISSUE THREAD

**Issue by phillipkregg** [driftyco/ionic#1159]
When navigating into a playlist item, the back button disappears on refresh leaving no way to navigate back.  If the browser's back button is clicked, then the back button reappears but in the wrong place - the playlist main page.  Clicking it then takes you back to the individual playlist item with no backbutton.

Here's a video of what is happening:  https://www.youtube.com/watch?v=9QLIdgc9l9g&feature=youtu.be&hd=1

**Comment by MoinPansare** [comment]
facing the same issue though on mobile app there would be no way for the user to reload the url this issue is being sidelined for now but still it demands some attention.
