### ISSUE TITLE
recommend supporting query parameters

### ISSUE THREAD

**Issue by martin1221** [driftyco/ionic#11605]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

We can only use query parameters in our project limited to the platform.
like this:
`www.abc.com/#/user?id=1&?valid=1`

We can not use router parameters like this:
`www.abc.com/#/user/:id`

so we recommend supporting query parameters in ionic.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by astec** [comment]
@martin1221, as far as I know the ` www.abc.com/#/user/:id ` is supported by Ionic v3 and `www.abc.com/#/user?id=1&?valid=1`  is not. You issue states exactly opposite.

Could you please clarify and provide reproducible demo (plunker)?

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#205
