### ISSUE TITLE
Clear icon in Searchbar should always be visible even if its not in focus

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11603]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When we are typing in the Searchbar it displays a clear icon (cross icon) on the right of the search bar. Clicking it clears the searchbar value.

When its not in focus, the clear icon hides automatically.

I believe a better behavior could be to keep the clear icon visible if the searchbar has any value. So that if a user wants to clear a search, he/she can click the clear icon directly. Currently the user has to first tap on the search bar, then click the clear icon.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#204
