### ISSUE TITLE
Application error Ionic serve and run android using different ports why 

### ISSUE THREAD

**Issue by nikhildhar123** [driftyco/ionic#11606]
when I type ionic serve it runs on localhost/8100 but "cordova run android" runs on localhost:/8102 and displaying 
error connection refused and same thing when I install apk on my mobile it shoes error connection refused

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
