### ISSUE TITLE
App startup delay following ionic deploy

### ISSUE THREAD

**Issue by demirk4n** [driftyco/ionic#11614]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am experiencing a significant delay in app startup for a live update delivered through `ionic upload`  compared to the same snapshot build using  `ionic cordova build --prod --release`

**Expected behavior:**
Same app startup time for both binary build and ionic deploy live update.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.8.0
    OS         : Linux 4.9
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

Does `ionic build --prod --release` add extra optimization steps compared to live updates delivered through `ionic upload`?

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! `ionic upload` simply uploads whatever is in your `www` folder so we definitely recommend that you run `ionic build --prod` first before uploading to get the best performance.

**Comment by demirk4n** [comment]
@jgw96  Thanks for the reply Justin,
Unfortunately I getting the following;
 
```
$ ionic build --prod
The build command has been renamed. To find out more, run:

  ionic cordova build --help
```

 I also tried `ionic cordova build android --prod --release ` and `ionic upload` but the result was same. App startup suffers following a live update.

**Comment by nenuadrian** [comment]
Seconded
