### ISSUE TITLE
Allow placing item reorder icon on the left

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#11617]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Expected behavior:**
Currently when setting `reorder="true"` on an `ion-list`, it automatically adds a reorder icon on the right of each list item. Allowing developers to optionally place this on the left would be a great customisation feature. Maybe even also add something similar to `$item-ios-detail-push-svg`, for example `$item-ios-reorder-svg`, to allow developers to set their own reorder icon.

**Related code:**

```
<ion-list reorder="true">
  <ion-item>Item 1</ion-item>
  <ion-item>Item 2</ion-item>
  <ion-item>Item 3</ion-item>
</ion-list>
```

**Other information:**
To allow this functionality you could probably add an attribute like `side="left"` (like on item sliding).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#206
