### ISSUE TITLE
Ionic 3.2.0 AOT issues (again)

### ISSUE THREAD

**Issue by ghaiat** [driftyco/ionic#11610]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**

When building my app in aot mode using ionic 3.2.0 i have the following error which indicates an error in your template 

ERROR in ng:///xxxx/node_modules/ionic-angular/components/searchbar/searchbar.d.ts.Searchbar.html (2,387): Supplied parameters do not match any signature of call target.

We already issues for aot with the previous version ... can you please make sure you double check aot before releasing a new version ?

Cheers

**Comment by alexbainbridge** [comment]
See https://github.com/driftyco/ionic/issues/11598
