### ISSUE TITLE
Feat: Add support for the new Microsoft fluent design system

### ISSUE THREAD

**Issue by mtycholaz** [driftyco/ionic#11620]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] feature request

Microsoft just announced their new fluent design system. Would be awesome to see support for this in Ionic http://fluent.microsoft.com/?ref=producthunt

**Comment by mhartington** [comment]
😄  Key words here... _just announced_

We intended on adding support for it when it is released and more design docs are added to show implementation details. Until then, we must be patient and wait.

**Comment by mtycholaz** [comment]
@mhartington 

> We intended on adding support for it when it is released and more design docs are added to show implementation details.

Everything you asked for is right here.
https://developer.microsoft.com/en-us/windows/apps/design

**Comment by khmaies5** [comment]
I think this need to be reopened, Microsoft fluent design has been released

**Comment by yatesy** [comment]
Are we reopening this yet?
