### ISSUE TITLE
What about two side menus with ion-split-pane?

### ISSUE THREAD

**Issue by laker007** [driftyco/ionic#11622]
It works well with only one ion-split-pane.And I have two views in one page.

```
<ion-split-pane>
  <ion-menu [content]="content">

    <ion-header>
      <ion-toolbar>
        <ion-title>Pages</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>

      <ion-list>
        <ion-item>
          <ion-avatar item-left>
            <img src="assets/img/avatar.jpg">
          </ion-avatar>
          <h2>Cher</h2>
          <p>Ugh. As if.</p>
        </ion-item>
      </ion-list>

    </ion-content>

  </ion-menu>

  <ion-nav [root]="rootPage" #content main></ion-nav>

</ion-split-pane>
```
After that,I want to implement two side menus on the left through another ion-split-pane.I added the same code in the right view.It was black?!How to deal with the problem?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Daddelbob** [comment]
" jgw96 closed this on 12 May" -> solution?
