### ISSUE TITLE
what is infiniteScroll  requirements ?

### ISSUE THREAD

**Issue by almgwary** [driftyco/ionic#11621]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**
 i am using infiniteScroll  as documentation but it doesn't work .
what is infiniteScroll css requirements for parent container ?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
