### ISSUE TITLE
[Feat] ion-scroll: expose scrollTo() API

### ISSUE THREAD

**Issue by cmaas** [driftyco/ionic#11625]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-scroll` cannot be scrolled programmatically. From my understanding, this worked in Ionic 1, but not anymore in Ionic 2+

**Expected behavior:**
Expose an API to let me `scrollTo(x, y)` programmatically. For example, I use a charting library that draws to a rather big `canvas`. The chart is wrapped in an `ion-scroll` and when a specific date is selected, I want to scroll to that date in the chart.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#208
