### ISSUE TITLE
Allow excluding certain days of the week and dates from ion-datetime

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#11628]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Expected behavior:**
It would be useful to disallow users from selecting specific days or dates in the datetime selector, for instance weekends or public holidays.

**Other information:**
Excluded days could be passed as an array of integers such as `excludedDays="6,7"` with the number representing the index of the day. This would allow this to be independent of custom defined day names.
Excluded dates could just be passed as an array of strings in the format of the picker, much like min and max are set but with an array instead of a single value. `excludedDates="1/1/2017,14/2/2017"`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.9.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#209
