### ISSUE TITLE
[Feature request] Ion-select infinite scroll

### ISSUE THREAD

**Issue by Sh1d0w** [driftyco/ionic#11623]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently when opening the ion select the first option is always selected and you have to scroll down to select another option.

**Expected behavior:**
When opening a native select the default selected option is the middle one and you can scroll the select both down or up and select another options. It will be very cool to have this instead of the current behavior.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#207
