### ISSUE TITLE
Ionic v1: Lab mode: iOS preview overlaps status bar with CLI v3

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic#11632]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When running `ionic serve -l` using the Ionic CLI v3 in an Ionic 1 project, the iOS preview overlaps the statusbar.

**Expected behavior:**

The iOS preview should not overlap the statusbar.

**Steps to reproduce:**

- Create a new Ionic 1 project: `ionic start myapp blank --type ionic1`
- `cd myapp`
- `ionic serve -l`

**Other information:**

<img width="878" alt="screen shot 2017-05-12 at 13 01 25" src="https://cloud.githubusercontent.com/assets/820863/25997231/2a3b1138-3713-11e7-94ab-fa5fe8567d84.png">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/cli-plugin-cordova : 1.0.0
    @ionic/cli-plugin-ionic1  : 1.0.0
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2268
