### ISSUE TITLE
[3.2.0 / iOS] ion-input: Label's color unset when focused 

### ISSUE THREAD

**Issue by ThomasKientz** [driftyco/ionic#11631]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
On iOS, the input label's color is set to 'unset' when focused.

**Expected behavior:**
On iOS, when focused, the input label's color should correspond to its "color" attribute.

**Related code:**

```
    <ion-item>
      <ion-label color="primary" floating>Email</ion-label>
      <ion-input type="email"></ion-input>
    </ion-item>
```

**Other information:**
![apppreview](https://cloud.githubusercontent.com/assets/10157845/25995797/b46c2978-3731-11e7-99a4-53971813b26e.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.5.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.11 
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Could you post a repo we could use to reproduce this issue?

**Comment by jgw96** [comment]
Thanks, for opening an issue with us. We are looking into this.

**Comment by brandyscarney** [comment]
I'm sure I broke this here 😭  https://github.com/driftyco/ionic/commit/588fad879f463b2b557ca3ac3810d5a89a1ecbf6

I'll look into fixing it, in the meantime you can set these variables to `inherit`:

```
$label-ios-text-color:                 null;
$label-ios-text-color-focused:         null;
```

**Comment by brandyscarney** [comment]
I released a nightly with this fix in it, we'll have it in a patch version `3.2.1` soon:

```
npm install --save --save-exact ionic-angular@3.2.0-201705121627
```
