### ISSUE TITLE
Components are un-aware of Page events

### ISSUE THREAD

**Issue by jsanta** [driftyco/ionic#11636]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request 

**Current behavior:**
Lets say an app has 2 pages, Page1, and Page2. Both apps have custom components.
When navigating using nav.push there's no destroy method for the component, nor any way for it to get to know that it's not active. Even implementing `ngOnDestroy` (and extending from OnDestroy), onDestroy is never called, the component never knows it's not active anymore.
If the navigation is changed to use `nav.setRoot` , the destroy event is triggered and can be captured inside the component.

**Expected behavior:**
Components should be able to capture Page events, no matter what kind of navigation is being used.
`ionComponentIsActive/ionComponentIsNotActive` methods should be a nice to have in Components.

**Other information:**
Tried extending the pages, so on every implemented pageEvent it published a custom event, e.g. `'page:didLeave'`. My custom component had a subscriber for the `'page:didLeave'` event. (Ref. http://stackoverflow.com/questions/39836010/ionic-2-page-change-event )
As on every navigation, the component's constructor method is called again, all subscribers are also created again, so on each event, there are as many subscriber functions as many times the constructor was called.

Figured this out trying to use a _SharedService_ with _Subscriptions_ to it's variables

*Ionic info:** 
```
→ ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.7.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.6
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#212
