### ISSUE TITLE
Native Media plugin does not work on Android or iOS - fails without error

### ISSUE THREAD

**Issue by brettdorrans** [driftyco/ionic#11630]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Playing audio from local filesystem using cordova-plugin-media 3.0.1 doesn't work on Android/iOS, with no error messages logged.

**Expected behavior:**

Audio should play.

**Steps to reproduce:**

Create blank Ionic 2 app (have not tested with Ionic 3), install cordova-plugin-media. Add an mp3 file to the assets folder, then attempt to load from the filesystem. Audio will play in the browser, but not when deployed to a device.

iOS and Android will call the onSuccess callback, but no audio will play.

**Related code:**
My code to play as follows:
```
private playSound(file: string, mediaObject: MediaObject) {
    const onStatusUpdate = (status) => console.log(status);
    const onSuccess = () => console.log('Media init successful.');
    const onError = (error) => console.log(error.message);

    mediaObject = this.media.create('./assets/sounds/' + file, onStatusUpdate, onSuccess, onError);
    let duration = mediaObject.getDuration();

    mediaObject.play();
    // Clear resources after finished playing
    setTimeout(() => {
      mediaObject.release();
    }, duration * 2);
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Are you using `ionic-native` ?

**Comment by brettdorrans** [comment]
Hi, thanks for responding.

I am using ionic-native/media@3.7.0 following the docs provided here: https://ionicframework.com/docs/native/media/

I managed to get audio playing using Native Audio - I suspect the Media plugin isn't playing nice with paths on device targets?

I think this might be better reported in the ionic-native repo - but I'm not sure!

Cheers
Brett

**Comment by jgw96** [comment]
Thanks for the info! Yeah, since this is an ionic-native issue I am going to move this issue over to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1542
