### ISSUE TITLE
Ion-slide-page and ng-repeat block each other

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#11644]
Hi all,

```
<ion-slides options="options" slider="slider">
   <ion-slide-page ng-repeat="user in users">
      <img src="anUrl.png" />
   </ion-slide-page>
</ion-slides>
```

```
 $scope.options = {
    autoplay: 1500
  };
```

Is not working.

**But if I remove the ng-repeat, autoplay works suddenly!**

My question: how to solve this? What am I doing wrong here?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
