### ISSUE TITLE
Sass error (undefined variable "$item-md-body-text-font-size") after update

### ISSUE THREAD

**Issue by Screeze** [driftyco/ionic#11648]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

After updating ionic, I get following error when building:

```
[15:02:00]  sass: ...ng/xx/xx/node_modules/ionic-angular/components/label/label.md.scss, line: 24 
            Undefined variable: "$item-md-body-text-font-size".

      L23:  [text-wrap] .label-md {
      L24:    font-size: $item-md-body-text-font-size;
      L25:    line-height: $item-md-body-text-line-height;

Error: Failed to render sass to css
```

I have found the variable to be defined in xx\node_modules\ionic-angular\components\item\item.md.scss but somehow it seems this file is not included in the build.

I first posted this in the forum (https://forum.ionicframework.com/t/sass-error-after-update/90087) and seems like I am not the only one with that problem.

**edit:
This only happens when building for Android, not when using ionic serve!**
**edit2:
This does not happen when "--prod" flag is NOT added to the build. This seems only to occur with "--prod" enabled.**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
>ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by AmitMY** [comment]
Please try v3.2.1, as it fixes some AoT issues that exist in v3.2.0

**Comment by Screeze** [comment]
I just tried, but still the same result, now using v3.2.1

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#992

**Comment by rogeliotrejo13** [comment]
I have a solution in the file src/theme/variables.scss I add the next lines:
$item-md-body-text-line-height: 4em;
$item-md-body-text-font-size: 4em;
And all its solved;
