### ISSUE TITLE
IonicPage

### ISSUE THREAD

**Issue by cluo-cn** [driftyco/ionic#11643]
CODE:
<ion-tabs>
  <ion-tab [tabsHideOnSubPages]= true [root]="tab1Root" tabTitle="home-title" tabIcon="home"></ion-tab>
</ion-tabs>
TS:
@IonicPage({
  name : 'page-tabs',
  segment : 'tab'
})
**Current URL:**
http://localhost:8100/#/tab/home-title
**Expected URL:**
http://localhost:8100/#/tab

Hello

I don't know why the URL add TabTitle to the URL

thanks
cluo

**Comment by wbhob** [comment]
Because it is a child of the tabs page...

**Comment by cluo-cn** [comment]
tabs.html
`<ion-tab [root]="tab1Root" id="test" **tabTitle="this-is-title"** tabIcon="home"></ion-tab>`
tabs.ts
`import {Component} from '@angular/core';
import {IonicPage} from "ionic-angular";
@IonicPage({
  name: 'page-tab',
  segment: 'tab',
})
@Component({ templateUrl: 'tabs.html' })
export class TabsPage {
  tab1Root = 'page-home';
  tab2Root = 'page-about';
  tab3Root = 'page-contact';
}`
home.ts
`import {Component} from '@angular/core';
import {IonicPage, NavController} from 'ionic-angular';

@IonicPage({
  name: 'page-home',
  segment: 'home'
})
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage { }`

Current URL:
http://localhost:8100/#/tab/this-is-title/home
Expected URL:
http://localhost:8100/#/tab/home

**Should not be ‘tabs.html’ title added to the url**

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by wbhob** [comment]
I don't see how I can make it any more clear: it's a part of the URL because your view IS A CHILD OF THE TAB VIEW. No one even cares about the URL on mobile anyway, so it's not that big of a deal. If it really matters that much to you, change the `segment` to an empty string.

**Comment by cluo-cn** [comment]
@wbhob <ionic-tab> not set "tabUrlPath", "tabTitle " is default value

**Comment by jasonz1987** [comment]
@cluo-cn meet the same issue ,have you fixed it?
