### ISSUE TITLE
Fab button stops working after resume on Android

### ISSUE THREAD

**Issue by tomriddle1234** [driftyco/ionic#11646]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I built with the latest 3.2 Ionic code, with Angular 4.1.0, cordova 7.0.0 on Ubuntu 16.04 with Android 25 SDK, when I switch app on my Android 7.0 Galaxy Note 5 phone, then switch back to my app, the fab button just stop working.
It doesn't show fab list after click fab button, no response.

Haven't tested on iOS yet.

**Expected behavior:**
Expect fab button function showing the fab list buttons. 

**Steps to reproduce:**
My code below

-->

**Related code:**

```
insert any relevant code here
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI:7.0.0
Ionic CLI: 3.0.0
app-scripts: 1.3.7
ionic-angular: 3.1.1
Node: 7.10.0
Linux 4.4
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
