### ISSUE TITLE
Docs: Images for Slides component not showing

### ISSUE THREAD

**Issue by adebisi-fa** [driftyco/ionic#11652]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Images on the Slides component demo not showing.  http://ionicframework.com/docs/api/components/slides/Slides/

**Expected behavior:**
Image should be visible.

**Steps to reproduce:**
Just browse the page @ http://ionicframework.com/docs/api/components/slides/Slides/

**Related code:**
Not applicable

**Comment by jgw96** [comment]
Hello! We are aware of this issue and are currently working on fixing it.

**Comment by brandyscarney** [comment]
Fixed in this commit https://github.com/driftyco/ionic/commit/8bc827a531ff4b9dd1276b92e0766d34b559f5ba
