### ISSUE TITLE
No left margin on action-sheet-icon in RTL

### ISSUE THREAD

**Issue by DMan577** [driftyco/ionic#11650]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
![2](https://cloud.githubusercontent.com/assets/9746502/26026322/cb34bc94-3801-11e7-857b-33690d63dacf.png)

**Expected behavior:**
A margin between the icon and the text:
![3](https://cloud.githubusercontent.com/assets/9746502/26026330/fcc41386-3801-11e7-8d1e-d556e9286aff.png)

**Steps to reproduce:**
Simply create an action sheet with some items while in RTL.

**Comment by AmitMY** [comment]
@DMan577 Fixed in https://github.com/driftyco/ionic/pull/11342
Will be released in the next version, most likely 3.3.0.

@brandyscarney Please close

**Comment by eyas2n** [comment]
Issue still there.

**Comment by AmitMY** [comment]
@eyas2n I remember fixing this..
Are you on “$direction: multi”?

**Comment by eyas2n** [comment]
Just implemented it and it's working fine for actionsheet. What about side menu sliding direction, should I open a separate issue for that?

**Comment by AmitMY** [comment]
There is an open issue, and even a fix for runtime menu direction changes, but it was not merged.
For now, you need to do `platform.setDir('rtl')` before the menu is loaded into DOM (what I do when users switch languages, is refresh the page, and set it right in the AppComponent's constructor..
