### ISSUE TITLE
unexpected behavior of geolocation plugin under custom window event + angular zone

### ISSUE THREAD

**Issue by 05bca054** [driftyco/ionic#11654]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
geolocation plugin not working in custom event with custom zone.

**Expected behavior:**
geolocation plugin needs  to work within custom event and within zonejs.

**Steps to reproduce:**
If you find this as more relevant to ionic-native repository you ionic team can transfer this to ionic-native issue.

Sorry for reproducing as this illustration is based on beacon sighting custom event and used for enterprise level IoT app. where data is continuously changing using angular custom zones(Which effect ionic view[app front]) and when at certain limit beacon sightings touch then location plugin fire with http request along with latitude and longitude.

For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**
    ionViewDidEnter(){
        window.addEventListener('beaconsighting', (sighting: any) => {
             this.zone.run(() => {
                 this.geolocation.getCurrentPosition().then((resp) => {
                     **here i found unexpected behavior where my view is deteriorate once fire this geolocation event**
                 });
            });
        });
    }

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.2
Xcode version: Not installed (Ubuntu 16.04)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by 05bca054** [comment]
How do i join ionic-worldwide slack channel?

Can you please send me an invitation to join team please!

**Comment by piotrowski** [comment]
http://ionicworldwide.herokuapp.com/
