### ISSUE TITLE
Docs: resize / resume duplicate

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#11655]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ *] **3.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request

>  resize
> The resize event emits when the native platform pulls the application out from the background. This event would emit when a Cordova app comes out from the background, however, it would not fire on a standard web browser.
> 
>  resume
> The resume event emits when the native platform pulls the application out from the background. This event would emit when a Cordova app comes out from the background, however, it would not fire on a standard web browser.

Pretty sure the resize event is not the same as the resume event, and somehow the resume text has copied to the resize text

https://ionicframework.com/docs/api/platform/Platform/

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#1103
