### ISSUE TITLE
"TypeErrpr: Cannot read property 'includes' of undefined".

### ISSUE THREAD

**Issue by Zerokk** [driftyco/ionic#11667]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I was using the Ionic 3 beta CLI, and tried to install the ConnectivityService. It couldn't work in that version, so I performed a clean uninstall of ionic, and then, a new install aiming to ionic@latest. It gave a dependency error on app-scripts, so I used the following command:

npm install --save @ionic/app-scripts@^1.3.1

Then, I used again "npm install -g ionic@latest". After that, everything stopped working. I can't do anything with ionic anymore; I just keep having the same error with whatever I do: "TypeErrpr: Cannot read property 'includes' of undefined". It doesn't matter if I uninstall it and install it again; I just can't get it working.

**Expected behavior:**
The new version should have been properly installed and the provider, too.

**Steps to reproduce:**
(already told)

- - - - 

Any help regarding this? My project is stopped from this point and I can't get to test anything.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2285
