### ISSUE TITLE
bug: Create app using ionic 1

### ISSUE THREAD

**Issue by hiren443** [driftyco/ionic#11669]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>How can I create app using ionic v1.

I have tried using ionic start firstProject blank --v1. But it always create with latest version of ionic. 
Currently I have Angular app which is in Angular 1 and i want to replicate same with ionic 1.

How can I create the app with ionic version 1?

Thanks,</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @hiren443, would you mind running `ionic --version` and posting the output here, please?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2286
