### ISSUE TITLE
content's '_scroll' is null

### ISSUE THREAD

**Issue by liugogal** [driftyco/ionic#11664]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
this is my code:
```
ngOnInit(){
    this.keyboard.onKeyboardHide()
        .subscribe(()=>{
          try {
            this.content.scrollToBottom();
          }
          catch (err){
            //this.logger.log(err);
          }

        });
    this.keyboard.onKeyboardShow()
        .subscribe(()=>{
          try{
            this.content.scrollToBottom();
          }catch (err){
            //this.logger.log(err);
          }

        })
  }
```
I must catch the error

**Related code:**

```
insert any relevant code here
```

**Other information:**

https://github.com/driftyco/ionic/blob/master/src/components/content/content.ts

code here:

```
  /**
   * Scroll to the bottom of the content component.
   *
   * @param {number} [duration]  Duration of the scroll animation in milliseconds. Defaults to `300`.
   * @returns {Promise} Returns a promise which is resolved when the scroll has completed.
   */
  scrollToBottom(duration: number = 300) {
    console.debug(`content, scrollToBottom, duration: ${duration}`);
    return this._scroll.scrollToBottom(duration);
  }
```
"this._scroll.scrollToBottom(duration)" will call two times 
At the first time,the '_scroll' is null,at secend time ,it is not null.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 (cordova-lib@7.0.0)
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```
when i debug function 'scrollToBottom',i see the scrollToBottom() function will call to times.At the first time,the '_scroll' is null,at secend time ,it is not null.

**Comment by AmitMY** [comment]
Please fix the issue description to fit the template.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. As @AmitMY pointed out, would you mind editing your issue to follow our issue template? Also, if I'm understanding the issue correctly, can you wrap your code in `ionViewDidLoad` instead of `ngOnInit` and see if you run into the same issues? Thanks!

**Comment by root-io** [comment]
Probably related to the issue #11230 scroll to bottom never worked for me either in v2 or v3

**Comment by liugogal** [comment]
`TypeError: Cannot read property 'scrollToBottom' of null
    at Content.scrollToBottom (http://192.168.100.39:8100/build/main.js:33995:28)
    at SafeSubscriber._next (http://192.168.100.39:8100/build/12.main.js:145:31)
    at SafeSubscriber.__tryOrUnsub (http://192.168.100.39:8100/build/main.js:15480:16)
    at SafeSubscriber.next (http://192.168.100.39:8100/build/main.js:15429:22)
    at Subscriber._next (http://192.168.100.39:8100/build/main.js:15371:26)
    at Subscriber.next (http://192.168.100.39:8100/build/main.js:15335:18)
    at handler (http://192.168.100.39:8100/build/main.js:136294:46)
    at Object.fireWindowEvent (http://192.168.100.39:8100/cordova.js:245:20)
    at success (http://192.168.100.39:8100/plugins/ionic-plugin-keyboard/www/android/keyboard.js:50:21)
    at Object.callbackFromNative (http://192.168.100.39:8100/cordova.js:293:58)`


mycode:

`ionViewDidLoad (){
    this.keyboard.onKeyboardHide()
        .subscribe(()=>{
          try {
            this.content.scrollToBottom();
            this.content.resize();
          }
          catch (err){
            this.logger.log(err);
          }

        });
    this.keyboard.onKeyboardShow()
        .subscribe(()=>{
          try{
            this.content.scrollToBottom();
            this.content.resize();
          }catch (err){
            this.logger.log(err);
          }

        })
  }`

main.js

`Content.prototype.scrollToBottom = function (duration) {
        if (duration === void 0) { duration = 300; }
        (void 0) /* console.debug */;
        return this._scroll.scrollToBottom(duration);
    };`
move code to `ionViewDidLoad ` .   same problem,`this._scroll.scrollToBottom(duration)` did called two times. `_scroll` is null at the first time.

**Comment by manucorporat** [comment]
@liugogal you need to unsubscribe `this.keyboard.onKeyboardShow` and `this.keyboard. onKeyboardHide` when your page is destroyed, otherwise you have an instance calling an already destroyed Content. and _scroll was already reseted to null.

cc @jgw96

**Comment by manucorporat** [comment]
closing since I am 99% sure this was the problem... please reopen if it was not the case
