### ISSUE TITLE
When I am in the middle of a call and I return to my app, part of the bottom bar is lost in the cell phone screen.

### ISSUE THREAD

**Issue by hernangiraldo89** [driftyco/ionic#11679]
**Ionic version:** (check one with "x")
[ X] 1.x
[ ] 2.x
[ ] 3.x

**I'm submitting a ...** (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I am in the middle of a call and I return to my app, part of the bottom bar is lost in the cell phone screen.

**Expected behavior:**
The bottom bar should be shown completely

**Steps to reproduce:**
It is simple:
**1.** Create a bottom bar inside to a <ion-view>.
**2.** Put the application in background.
**3.** Make a call.
**4.** After return to the application.

**Related code:**
<ion-view title="Terminos y condiciones" ng-controller="TermsConditionsController as TermsConditionsControl">
    <div class="headerContent">
        <div class="img-logo">
            <img ng-src="{{::i18n.termsConditions.bhdImageLogo}}" class="imgBhdLogo"/>
        </div>
    </div>

    <ion-content class="content-with-header content-terms-conditions" scroll="false">
        <div class="item item-body">
            <div class="txtTermsWrap">
                <h1>{{::i18n.termsConditions.labelTermsTitle}}</h1>
                <div class="contract-wrap" ng-bind-html="TermsConditionsControl.contract">
                </div>
            </div>
        </div>
    </ion-content>

    <div class="bar bar-footer footer-terms-conditions">
        <div class="tabs btnTermsWrap">
            <a class="bottom" ng-click="TermsConditionsControl.cancelAcceptContract()" id="left">{{::i18n.termsConditions.cancelButton}}</a>
            <a class="bottom" ng-click="TermsConditionsControl.doAcceptContract()" id="right">{{::i18n.termsConditions.continueButton}}</a>
        </div>
    </div>
</ion-view>

![print screen](https://cloud.githubusercontent.com/assets/8507433/26066845/4adbfe8e-3966-11e7-8f71-343c8a470e88.png)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#257
