### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by rajeevrmenon97** [driftyco/ionic#11672]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Cannot install ionic from npm due to dependency error

**Expected behavior:**
Clean installation

**Related code:**

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'ionic/cli-utils' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2284
