### ISSUE TITLE
Request side-menu.scss

### ISSUE THREAD

**Issue by Bernardoow** [driftyco/ionic#11678]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Today, for add css to menu of template side bar, I need put at app.scss.

**Expected behavior:**
I expected a file separate to do custom of menu bar. Ex side-menu.scss.

**Steps to reproduce:**

**Related code:**

ion-menu ion-content ion-list button.item-md.selected{
    border-left: 5px solid #FFCB06;
}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.3
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
