### ISSUE TITLE
can't extract downloaded apk update when lazy load with ionic v3

### ISSUE THREAD

**Issue by decpio** [driftyco/ionic#11673]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => 

**Current behavior:**
After 'ionic upload' when you programically check for update using 'ionic deploy plugin' you have this error:
/data/user/0/com.ionicframework.mayAppName/app_GUID/ ./build/sw-toolbox.js: open failed: ENOTDIR (Not a directory)
and installation stops.
After build command, generated apk works fine, but uploaded to cload can't intall.

**Expected behavior:**
work fine without error

**Steps to reproduce:**

**Related code:**
run manually this function:
private  checkForUpdates() {
                this.__Deploy.check().then((snapshotAvailable: boolean) => {
                    if (snapshotAvailable) {
                        this.__Deploy.download().then(() => { // If a new snapshot is available, you can download and extract it, which will set it as the active snapshot. The next time the app is loaded, the new snapshot will be used.
                            return this.__Deploy.extract().then(() => { // After extract() resolves, you can optionally force an immediate app restart using load().

                                setTimeout(() => {
                                    this.__Deploy.load();
                                }, 10 * 1000);
                            }).catch(reason => {
                               // >> here extraction error apear !!! <<
                            });
                        }).catch(reason => {
                        });
                    }
                    else { // no snapshot available
                    }
                }).catch(reason => {
                });
            }
        }
    }

**Other information:**
app is installed on device from apk, and then aupdates are downloaded from ionic cload.
Earlier works fine: I mean before such changes:
 - I updated ionic CLI to v3
 - I implemented  'lazy load' to page files.
Booth changes was made in same time.
I don't know which change broke installation.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

λ ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.9.4
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2283
