### ISSUE TITLE
Support serve browser platform locally over https

### ISSUE THREAD

**Issue by padgettrowell** [driftyco/ionic#11674]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic does not currently support serving locally over https when targeting the browser platform. 

**Expected behavior:**

Being able to serve an Ionic project locally over https allow for real world testing of applications targeting the browser platform. For example, testing CSP policies. For example, it's not possible to locally test the following policy:
Content-Security-Policy: upgrade-insecure-requests

**Steps to reproduce:**

In your index.html file, add the following <head> element:
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
All content fails to load.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2282
