### ISSUE TITLE
Google Maps scroll  issue

### ISSUE THREAD

**Issue by joesleiman** [driftyco/ionic#11676]
**Ionic version: 3.2.0** 

**I'm submitting a  bug report**  

**Current behavior:**

**Expected behavior:**

it should the  mao still fix at his position
**Steps to reproduce:**
`<div #map id="map"></div>`
+ same" loadmap()" function as in the documentation.
i'm using it inside <ion-slide>

**Other information:**

- when i scroll the app where the map exist. the map scroll too , and there is a delay when it scrolled.
 

- **another issue** : if i have a select tag like (**ion-select**) above the map directly , then i click on the drop down to open a modal that have options, the modal open in the center of the page above the map , i can't choose any of the options . when i click on the option it look like i click on the map, it doing zoom .
same if i scroll and stop scrolling when the map appear under the header of the page , the back button can't clicked.

- **another issue**: i used it inside <ion-slide> because i'm using wizard form so when i click on next button to go to next slide, a part of the map appear on the second slide. i can decrease the width but it have to not appear. because on first slide appear 100% without touching the border-right of the app .

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1563

**Comment by joesleiman** [comment]
Iam missing a word i used it inside( ion-slide ) in the third point . And thanks
