### ISSUE TITLE
Long delay in streaming Audio files on iOS devices

### ISSUE THREAD

**Issue by aamir1995** [driftyco/ionic#11686]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There is 25 to 35 seconds delay in playing any Audio from remote API with html5 Audio, Issue is occurring only on iOS physical devices, tested on iPhone 6+ and 6s. working fine on The Web, Android and iOS simulator. I think the issue is not with HTML 5 audio because I also used third-party audio players like Howler.js and jPlayer but same issue on those too, 

**Expected behavior:**

Audio should stream Normal like on Android version of App.

**Steps to reproduce:**

Create any blank Ionic 2, 3 project, add html5 `audio` tag, give the `src` to any mp3 URL. deploy it to a physical iOS device.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Ionic does not do anything special with audio tags or playing html5 audio. Because of this, I am going to close this issue for now.
