### ISSUE TITLE
ion-textarea not updating view on keypress after first character

### ISSUE THREAD

**Issue by ivanmayes** [driftyco/ionic#11681]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using ion-textarea with iOS is presenting some odd issues.  The first character appears, but then the rest of the changes do not show up, though the cursor moves.  Adding characters or deleting does not update unless the keyboard is hidden or the scrollbar comes up.

**Expected behavior:**
Ability to see text while typing.

**Steps to reproduce:**
Run ionic app with <ion-textarea> on iOS emulator

**Related code:**

```
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>
      Add New Entry
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>

	<div class="entry-data">
		<form (submit)="finishEntry()" #entryForm="ngForm">
			<ion-list padding>

				<ion-item>
					<ion-label stacked>A quick description of the entry</ion-label>
					<ion-textarea required type="text" [(ngModel)]="entry.caption" name="caption"></ion-textarea>
				</ion-item>

				<div padding>
					<button ion-button large color="primary" block [disabled]="images.length < 0 || entry.caption.length < 1 || !entry.retailer">Publish Entry</button>
				</div>

			</ion-list>
		</form>
	</div>

</ion-content>
```

Attached video screencast here:
[ionic-text-area.zip](https://github.com/driftyco/ionic/files/1001963/ionic-text-area.zip)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Could you post a repo we could use to reproduce this issue?

**Comment by ivanmayes** [comment]
Sorry, thought I had thoroughly tested, but found a piece of css that was causing the issue.  Thanks for your responsiveness!

**Comment by royalcheeseburger** [comment]
@ivanmayes what was exactly this piece of css if you can remember? Because I am facing the same issue and it's driving me crazy!
