### ISSUE TITLE
ScrollTo problem on iOS with version 2.3

### ISSUE THREAD

**Issue by RuneStenstroem** [driftyco/ionic#11699]
Ionic version: (check one with "x")
[ ] 1.x
[x ] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request

I have a problem with a scrollTo after updating to v. 2.3. I have created a directive which I add to a list item and the content scrolls to the specific item. It works in browser and Android in v. 2.3, but on iOS i do not work. I tried downgrading to 2.2 and in this case i works. It seems like the content below the device height is not rendered on iOS when using scollTo. 

@Directive({
  selector: '[etcScrollToEvent]'
})
export class ScrollToEvent {
  @Input() content: Content;
 constructor(public el: ElementRef) { }
 ngAfterContentInit() {
    this.content.scrollTo(0, 0, 0).then(data => {
      let yOffset = this.el.nativeElement.getBoundingClientRect().top;
      this.content.scrollTo(0, yOffset - 115, 700);
    });
}

Ionic Info
Cordova CLI: 6.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you update to the [latest release](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#321-2017-05-12) and see if you still have the same issue?

**Comment by RuneStenstroem** [comment]
Hi, Sorry for the late reply. I just update to 3.2 and now everything seems to work fine so I will run with that. Thanks for the reply.
