### ISSUE TITLE
Can't modify Popover Page width

### ISSUE THREAD

**Issue by stellmaurer** [driftyco/ionic#11701]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I can't change the displayed width of a popover page, but I can change the width of the popover page with scroll (technically the page width can be modified, but it only allows you to scroll the full width - you can never see the full width displayed).

**Expected behavior:**
Allow popover page widths to be modified and displayed as a percentage of the screen width.

**Additional Info:**
I've only tried running this project in a browser (I'm using Firefox due to some development limitations with other browsers) using ```ionic serve```.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Do any of these [sass variables[(http://ionicframework.com/docs/api/components/popover/PopoverController/#sass-variables) do what you are looking for?

**Comment by stellmaurer** [comment]
@jgw96 They do :) Thanks so much for the quick response!

I was thinking I could override the sass variables from the specific scss file for my popover page, but I had to override it in "src/theme/variables.scss" of my project.

Is there a way to not globally override the Ionic sass variables? I ask because I may want multiple popover sizes throughout my app and I'm not sure how to do that?

**Comment by jgw96** [comment]
Hello @stellmaurer . So to just style one popover you can pass a `cssClass` param as stated [here in out docs](http://ionicframework.com/docs/api/components/popover/PopoverController/#advanced) and style it using that class. Thanks for using Ionic!

**Comment by stellmaurer** [comment]
@jgwp96 I was able to pass the cssClass param in while creating the popover page just fine, but I wasn't able to figure out how to override the default sass variables. Is overriding the sass variables in the custom cssClass not what I should be doing?

**Comment by kirstenfrager** [comment]
I am having the same issue. I have done the above and placed the class content in app.scss but it is not working. please advise

**Comment by kirstenfrager** [comment]
@stellmaurer 
have found solution from 
https://forum.ionicframework.com/t/popover-styling/59341/3?u=mayteio

**Comment by abrseq** [comment]
it didn't work for me @stellmaurer

**Comment by AhmedHamedTN** [comment]
as mentioned by @kirstenfrager 

Add these lines to **variables.scss** under **theme** folder

```
$popover-md-width: 320px;
$popover-ios-width: 320px;
$popover-wp-width: 320px;
```

rebuild and that's it

**Comment by romanovma** [comment]
Does anyone know how to adjust the popover position when width is big enough?
By default it is center position but once I make width 90% or higher through these variables I get the list sticked to the left not centered
