### ISSUE TITLE
Camera launching Gallery by default, can't access camera

### ISSUE THREAD

**Issue by georgechapman** [driftyco/ionic#11706]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When i launch the camera even though i am using `sourceType : this.camera.PictureSourceType.CAMERA,` it launches the Gallery (albeit the "_Camera_" folder)

**Expected behavior:**
The Camera should launch

**Steps to reproduce:**

**Related code:**

```
  public takePicture() {
    this.camera.getPicture({
      destinationType : this.camera.DestinationType.DATA_URL,
      sourceType : this.camera.PictureSourceType.CAMERA,
      encodingType: this.camera.EncodingType.JPEG,
      quality : 75,
      targetWidth: 1000,
      targetHeight: 1000,
      allowEdit : false,
      saveToPhotoAlbum: false
    }).then(imageData => {
      this.base64Image = "data:image/jpeg;base64," + imageData;
    }, error => {
      console.log("ERROR -> " + JSON.stringify(error));
    });
  }
```

**Other information:**
It worked fine when using `"ionic-angular": "3.0.1"` and CLI v2.something

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.5.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1579
