### ISSUE TITLE
Ionic Cordova failed to build android

### ISSUE THREAD

**Issue by rooton** [driftyco/ionic#11707]
**Ionic version:** 
[x] **3.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio

**Steps to reproduce:**
ionic cordova run --emulator

**Other information:**
Im an Android Developer.
So i have latest Android Studio (with latest gradle) installed on PC.
How can I just set path to my Android Studio?

**Ionic info:**

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2310
