### ISSUE TITLE
Clicking on the Active Tab in the tab bar will instansiate a new instance of the tab

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic#11708]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Very simple, given the regular tabs app generated with `ionic start my-app tabs`, when you select the active tab of a page, clicking on it repeatedly will generate an instance of the page. This can be seen by console.logging something on ngOnInit.

**Expected behavior:**
It should not generate a new instance of the page. It should do nothing. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by rapropos** [comment]
I attempted to reproduce this and failed.

**Comment by kamok** [comment]
@rapropos I just checked this commit https://github.com/driftyco/ionic/pull/11084 for `3.1` of ionic, and it SEEMS like it fixes it. I wasn't sure. What version of Ionic are you running?

**Comment by kamok** [comment]
Looking at the change they made to the source, it seems like legit. I'm going to leave this open until I upgrade tomorrow, and report back.

**Comment by jgw96** [comment]
Hello @kamok, i can confirm that this issue was fixed in Ionic 3.1 by a PR i merged. Thanks for using Ionic! If you still run into this issue in the latest release of Ionic please feel free to comment and i will reopen this issue.

**Comment by kamok** [comment]
Confirm upgrading to ionic 3.1.1 fixed this.

**Comment by AngelaRg** [comment]
I know it's supposed to be fixed but his is happening on my iOS app. Any ideas?

global packages:

@ionic/cli-utils : 1.5.0
Cordova CLI      : 7.0.1 
Ionic CLI        : 3.5.0
local packages:

@ionic/app-scripts              : 1.3.0
@ionic/cli-plugin-cordova       : 1.4.1
@ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : ios 4.4.0
Ionic Framework                 : ionic-angular 3.0.1
System:

Node       : v6.10.2
OS         : macOS Sierra
Xcode      : Xcode 8.3.2 Build version 8E2002 
ios-deploy : 1.9.1 
ios-sim    : 5.0.13 
npm        : 4.6.1

**Comment by AngelaRg** [comment]
Updating manually ionic-angular to 3.5.3 solved the problem
