### ISSUE TITLE
Able to scroll content behind a modal on IOS

### ISSUE THREAD

**Issue by cryo243** [driftyco/ionic#11712]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi guys,  I'm seeing a bug only on iOS where I am able to scroll the content of a page in the background of  a modal when this latter is opened and when I try scrolling inside the modal. Is there a way to prevent this ?
Once again thanks  for your effort to try making  Ionic a great framework
**Expected behavior:**

Content of a page in the background of a modal should not scroll when scrolling inside an open modal
just as it does for Android
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.7.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed


```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately, on UIWebView there is no good way to stop scroll events from reaching a page underneath an overlay without causing jank and rendering flashes. However, on WKWebView it is possible to stop scrolling underneath an overlay in a performant way. To get WKWebView you can check out the [instructions on this repo](https://github.com/driftyco/cordova-plugin-wkwebview-engine). We are planning on making this the default webview for iOS soon.

**Comment by cryo243** [comment]
Hi I did have the  WKWebView plugin before posting and the issue is still there. Tested on ios 10.3. Please reopen the issue

**Comment by thisIsChetan** [comment]
I am facing  the same issue. Please suggest.

**Comment by tylerpwc** [comment]
+1

**Comment by rob-moore** [comment]
Hey. I'm running into the same issue. Has there been any progress on this?

**Comment by ilyalukyanov** [comment]
@jgw96 this is still an issue even in WKWebView.

There’s a number of duplicates of this issue logged and unfortunately none of them seem to get any attention from the ionic team.
