### ISSUE TITLE
Cordova 7.0.1 does not work

### ISSUE THREAD

**Issue by dalibor983** [driftyco/ionic#11714]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Cannot add browser platform.
Command: ```ionic cordova platform add browser```
I got this exception:
```
Adding browser project...
Running command: cmd "/s /c "<project-root>\node_modules\browser\bin\create <project-root>\platforms\browser <project-package> <project-name>""
The system cannot find the path specified.
Error: cmd: Command failed with exit code 1
```
```node_modules\browser\bin``` folder does not exist at all in my project

**Expected behavior:**
```node_modules\browser\bin``` should exist

**Steps to reproduce:**
```
npm install cordova@latest -g
npm install ionic@latest -g
```
Go to root of you ionic project and run
```
ionic cordova platform add browser
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:                                         
                                                         
    @ionic/cli-utils : 1.1.2                             
    Cordova CLI      : 7.0.1                             
    Ionic CLI        : 3.1.2                             
                                                         
local packages:                                          
                                                         
    @ionic/app-scripts              : 1.3.7              
    @ionic/cli-plugin-cordova       : 1.1.2              
    @ionic/cli-plugin-ionic-angular : 1.1.2              
    Ionic Framework                 : ionic-angular 3.2.0
                                                         
System:                                                  
                                                         
    Node       : v6.10.2                                 
    OS         : Windows 8.1                             
    Xcode      : not installed                           
    ios-deploy : not installed                           
    ios-sim    : not installed                           
```

**Comment by davec21** [comment]
Cordova 7.0.1 works fine. If you don't have a node_module for browser.. maybe you need to install it.

Out of curiosity why are you using the browser platform? A simple Ionic Serve does the job. From what I know the Browser platform is still a work in progress and really shouldn't be used.

**Comment by dalibor983** [comment]
@davec21 I have node_module for browser but there is not ```bin``` directory in that module and cordova trays to run some scripts from ```bin``` folder. In cordova 6.5.0 these scripts are in ```platforms\browser\cordova```.

I try ```npm install``` several times but I always got browser module without ```bin``` directory.

I need browser build of ionic application to run it from my public server so that someone can run it from standard browsers like chrome, safari, mozilla, ie...

**Comment by davec21** [comment]
@dalibor983 ahh, yea that sounds like a node module issue. However! You can just copy the ionic served www folder in project root to your server and it will work fine!

**Comment by dalibor983** [comment]
@davec21 If I copy www from root project than all cordova plugins which support browser platform will not work.

**Comment by davec21** [comment]
@dalibor983 Makes sense. Yea I've seen the ionic team on here saying the browser platform is still a work in progress on the Cordova side of things. Not sure how much control the ionic team has over Cordova and the platforms. 

I assume going back to 6.5.0 works fine then?

**Comment by dalibor983** [comment]
@davec21 Yes, it works fine with cordova 6.5.0.

**Comment by jgw96** [comment]
Hello everyone! Thanks for using Ionic. This is just one of the many bugs in the cordova browser platform. The cordova browser platform was originally built as an experiment and was meant to be used only by people building cordova plugins. In fact, i opened an issue yesterday on our docs repo https://github.com/driftyco/ionic-site/issues/1106 to recommend on our docs that people do not use the browser platform. If you want to deploy your ionic app to the web you can run `npm run ionic:build --prod` and then your www folder will be what you want to deploy. For example, after doing a prod build, i can use [firebase hosting](https://firebase.google.com/docs/hosting/) to publish my built app in my www folder by setting that folder as the "public" folder.
