### ISSUE TITLE
about ng-router and ionic-router

### ISSUE THREAD

**Issue by lyj505** [driftyco/ionic#11710]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I hava a question ..... how can i use angular2-router for ionic webapp?
now I use ionic cli to develop.
if ionic2 dont support the ng-router, i use angular-cli to develop the webapp and add ionic-bundled to webapp.

i try to use ionic2 deeplink,but sometime it`s not meet my requirements.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!

**Comment by lyj505** [comment]
thx
