### ISSUE TITLE
Popover: flicker on presentation in Edge browser

### ISSUE THREAD

**Issue by frankpapenmeier** [driftyco/ionic#11726]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Presenting a popover shows a short flicker in Edge browser. (creation of empty popover container is shortly visible)

**Expected behavior:**
Flicker should not be present.

**Steps to reproduce:**
Issue is directly visible in the online demos:

1.) Open Edge Browser
2.) Navigate to: https://ionicframework.com/docs/api/components/popover/PopoverController/
3.) Swap to "Windows"
4.) Click on three dots icon in top-right.. Watch out for the short flicker in the bottom right

**Related code:**

Missing CSS property.

Adding the following CSS Property fixes the issue:
```
.popover-content {
  opacity: inherit;
}
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
