### ISSUE TITLE
multiple executions of page constructor

### ISSUE THREAD

**Issue by mgkimsal** [driftyco/ionic#11723]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Page constructor is being run every time the page is pushed on to the nav controller.

**Expected behavior:**
Page constructor would only run the first time the page is constructed.

**Steps to reproduce:**
https://github.com/mgkimsal/ionicpagedemo

There's a "Page1" and "Page2"

Page1 has a button which calls 'goto'.  When clicked, it pushes Page2 on to the navCtrl.

Page2 has a constructor with a console.log().  

From Page1, click the button, go to Page2.  
See that you've hit the constructor.
Click the 'back' nav button.
From Page1, click the button again, so to Page 2 again.
See that you've hit the constructor again.

**Related code:**

Page1
```
goto()
{ 
this.navCtrl.push(Page2Page);
}
```

Page2
```
  constructor(public navCtrl: NavController, public navParams: NavParams) {
    console.log('in constructor');
  }
```

**Other information:**

Other "bug" reports on this focused on "setRoot()" issues.  I'm not using setRoot() anywhere (but maybe NavController is?)

I was under the impression that a page controller would only be initialized/constructed *one* time, not every time the page was pushed on to the nav stack.  If this is a wrong impression, and this is intended behaviour, it should probably be documented (tell me where and I'll do a change/pullrequest).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually expected behavior. The navController will destroy the class instance of a page when it is popped. If not we could end up with a memory leak caused by multiple instances of the same page being kept in memory. [This is the repo](https://github.com/driftyco/ionic-site) you can submit docs issues/PR's too. I would probably open an issue first so that this can be discussed.

**Comment by mgkimsal** [comment]
Thank you for your response.

I'd meant to reference the other ticket on this

https://github.com/driftyco/ionic/issues/5960

Your responses there seemed to indicate this wasn't expected behaviour:

"since your doing a setRoot on the home page it is going to be reconstructed when you navigate to it because its being reset as the root and has to be reinitialized."

and 

"so if your on your root page and you navigate to a different view, then to get back to your root page all you have to do is use nav.pop(rootPage). There is no need to set it as root again before you navigate back to it. This will keep it from reconstructing"

Indeed, the 'expected' behaviour may have been explicitly changed (I don't particularly remember seeing this as a problem with ionic 1, but it's been a long time since I was using that).

**Comment by jgbneatdesign** [comment]
@mgkimsal hello! Did you find a fix the problem? I'm having the same issue here. Where I make http calls in the constructor. And it's being fired every time the page is navigated to.
