### ISSUE TITLE
CLI command "ionic g directive" points to invalid Angular docs location in comments

### ISSUE THREAD

**Issue by jgfet** [driftyco/ionic#11722]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.1.2

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic g Directive
generates incorrect link in comments to Angular 
https://angular.io/docs/ts/latest/api/core/index/DirectiveMetadata-class.html
**Expected behavior:**

https://angular.io/docs/ts/latest/api/core/index/Directive-decorator.html
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
ionic info

global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2316
