### ISSUE TITLE
How can I use bower in Ionic V1 ?

### ISSUE THREAD

**Issue by usman10scorpio** [driftyco/ionic#11725]
I have just made a blank project in Ionic. Now my next step is to install components like angular-route , loading-bar etc. I know in simple angular you can get the help using bower. But in ionic the structure is changed although bower.json and bowerrc is present , but i dont know how can I use bower here to install the components. I have been searching for two hours, and not found a single satisfying tutorial.

**Comment by AmitMY** [comment]
For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1

Although, this does not seem like an issue, but a support request, and for that please ask in the forum.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#260
