### ISSUE TITLE
Conflict SQLite + BarcodeScanner

### ISSUE THREAD

**Issue by kairovisk** [driftyco/ionic#11721]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Database(SQLite) is not created when its running with `import { BarcodeScanner } from 'ionic-native';`, ive made some tests and i think its a kind of conflict. I can save my things inside the database when im not running with the BarcodeScanner, but when its running with it, just one DB appears `barcode_scanner_history.db`. By the way, the scanner works fine, i just cant save anything using `import { Storage  } from '@ionic/storage';`.

**Expected behavior:**

Create a database (sqlite) and make some inserts inside of it.

**Steps to reproduce:**

Install plugins from SQLite Storage and for BarcodeScanner.
Install NPM for SQLite Storage and for BarcodeScanner.
`
import { Storage  } from '@ionic/storage';
import { BarcodeScanner } from 'ionic-native';
`
Try to save something inside the Database(SQLite).

-->

**Related code:**

```
    scan(item) {
        BarcodeScanner.scan()
            .then((result) => {
                if(item == 1){
                    this.url_server = result.text;
                } else {
                    this.url_printer = result.text;
                }
            })
            .catch((error) => {
                alert(error);
            })
    }

    save_data() {
        this.local.ready().then(() => {
            this.local.set('url_server', JSON.stringify(this.url_server));
            this.local.set('url_printer', JSON.stringify(this.url_printer))
        });
        this.navCtrl.pop();
    }
```

**Other information:**

**Ionic info:**

```
 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1583
