### ISSUE TITLE
Ionic version: 2.x* - Not able to install Ionic 2

### ISSUE THREAD

**Issue by thebitpost** [driftyco/ionic#11733]
I'm submitting a  bug report.
Apparently, there is no way to run old ionic projects. I am trying to run an ionic 2 app, But when I install ionic, it always installs ionic 3.
Sample Project: https://github.com/720kb/BitNFC

Please fix the issue.

**Comment by AmitMY** [comment]
- Please fix your issue to fit the template.
- There are ways to run old ionic projects, but I need to see `ionic info` to see what are the versions of ionic and the CLI.
- Ionic v3.x is the same as Ionic v2.x. Like Angular v4.x and Angular v2.x. The version that is not compatible is Ionic 1, which is like AngularJS

**Comment by Jake21x** [comment]
are you trying it to run old ionic2 or trying to create/install a new ionic project ? 
if your trying to create or install new ionic project with v2 not v3 .. you can try this .. 
npm -g ionic@2.2.3

**Comment by chandanch** [comment]
@thebitpost first uninstall the existing ionic version. In order to install a specific ionic version use:
`npm install -g ionic@<version>`
For example:
`npm install -g ionic@2.0.0-beta11`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/]. Thanks for using Ionic!
