### ISSUE TITLE
bug: Not working with safary

### ISSUE THREAD

**Issue by evandrojr** [driftyco/ionic#11739]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>3.1</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>SAFARY browser Iphone 6s</span>

<span ionic-description>Publish the www folder to some server and try to access it using IPhone6s's safary browser.

It does not load the content. However, It works with opera on the same device. It also works well using Android Chrome.

You can reproduce the error using this URL:
http://bit.ly/seugarcom</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
