### ISSUE TITLE
bug(lazy-loading): can't create popover

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#11736]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Without lazy loading, creating a popover works. However, same code, just using lazy loading in my app, throws errors.
Code: `this.popoverCtrl.create(FileUploadPopOver)`
Note, that `FileUploadPopOver` is in the same module as the file I am calling it from.
The error is;

> ERROR Error: Uncaught (in promise): Error: No component factory found for FileUploadPopOver. Did you add it to @NgModule.entryComponents?
> Error: No component factory found for FileUploadPopOver. Did you add it to @NgModule.entryComponents?

And  if I try `this.popoverCtrl.create("FileUploadPopOver")`, a different error

> ERROR Error: Uncaught (in promise): invalid link: FileUploadPopOver

**Expected behavior:**
That there will be a way to create popover while using lazy loading

**Related code:**

```
this.popoverCtrl.create(FileUploadPopOver)
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by rapropos** [comment]
This is probably a stupid question, but *is* the popover component listed as an `entryComponent` in the module it's defined in?

**Comment by AmitMY** [comment]
@rapropos Yes, of course. It works without the lazy loading, so I think it relates to that.

**Comment by DavidStrausz** [comment]
@AmitMY Did you add the @IonicPage() decorator to the FileUploadPopOver component?

**Comment by AmitMY** [comment]
@DavidStrausz I didn't know I needed to.
Adding it now requires another module for a part of the same component I am loading. Which will be architecturally wrong imo. Anyway, I tried it, and it doesn't work. Still wants it as an entry component although it clearly is

**Comment by DavidStrausz** [comment]
According to the lazy-load branch of the ionic-conference-app ([ionic-conference-app](https://github.com/driftyco/ionic-conference-app/tree/lazy-load/src/pages/about-popover) a popover is a separate page (like modals are too).  So yes it feels a bit wrong putting it in a separate module but apparently thats how Ionic handles popovers currently.

**Comment by AmitMY** [comment]
@DavidStrausz Ok great, thanks. I managed to get it working by doing some modules refactoring and getting it to it's own module, then calling it using a string reference.

**Comment by DavidStrausz** [comment]
@AmitMY Nice :-) glad I could help!

**Comment by bugmonster** [comment]
For those hitting this problem, I had similar symptoms. My problem was that in my components.module.ts file, I had "IonicModule.forRoot(MyComponent)" in the imports section. It should only be "IonicModule", without the forRoot extension.
