### ISSUE TITLE
ion-img not rendering on initial load

### ISSUE THREAD

**Issue by acessoftware** [driftyco/ionic#11730]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When image is loaded from custom component it does not render

**Expected behavior:**
Image should show on load

**Steps to reproduce:**
Enable custom component

**Related code:**
Page view
```
<ion-content>
  <set-user></set-user>
</ion-content>
```
Custom component. Visibility of custom component is set through events.publish().
```
<ion-item *ngIf="setUser.id && setUser.id !== authUser.id" no-lines color="secondary">
  <ion-fab top right>
    <button ion-fab mini (click)="setAuthUser()"><ion-icon name="close"></ion-icon></button>
  </ion-fab>

  <div class="image-cropper" item-start>
    <ion-img class="profile-image" [src]="setUser.avatar_thumbnail ? setUser.avatar_thumbnail : 'assets/img/logo.jpg'"></ion-img>
  </div>

  <h2 ion-text>{{ setUser.first_name }} {{ setUser.last_name }}</h2>
  <button ion-button (click)="viewProfile()"><ion-icon name="contact"></ion-icon></button>
  <button ion-button (click)="callUser(setUser.phone)"><ion-icon name="call"></ion-icon></button>
  <button ion-button (click)="emailUser(setUser.email)"><ion-icon name="mail"></ion-icon></button>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.0
    ios-sim    : 5.0.8
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As we mention [here](http://ionicframework.com/docs/api/components/img/Img/#img) in our docs, `ion-img` is only meant to be used inside a `VirtualScroll` list.

**Comment by acessoftware** [comment]
Thanks for the answer. In case somebody is looking at this problem I changed `<ion-img>` to `<img>` and it worked. Of course, for `img` tag you have to remove closing tag.
