### ISSUE TITLE
firebase-ui-auth plugin

### ISSUE THREAD

**Issue by FallenRiteMonk** [driftyco/ionic#11731]
I would like to write a plugin for the [firebase-ui-auth](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md). Now the question I have is your opinion if such a plugin would even make sense or if it would be better to create a plugin for plain firebase auth without the ui? I know that there is [angularfire2](https://github.com/angular/angularfire2), which I have already tried and spend several hours on, but had several issues getting it to work properly cross platform. Also it seems quiet complicated and in my opinion could be simplified for developers if a plugin using native would exist.

Let me know what you think and sorry if this is not the right place for this.

**Comment by AmitMY** [comment]
- Please, when creating an issue, use the template.
- A firebase plugin already exists with native support - https://ionicframework.com/docs/native/firebase/ , although it is not supported for browser/serve. If you would like to mock it, that could be cool
- Anyway, this issue belongs to https://github.com/driftyco/ionic-native

**Comment by FallenRiteMonk** [comment]
@AmitMY Thanks for the quick reply, I'll recreate the issue on ionic-native using the template and close this one.

I know that this plugin with native support exists, but it does not and will never support authentication according to [issue79](https://github.com/arnesson/cordova-plugin-firebase/issues/79). That's why I'd like one for authentication instead of having to use facebook, twitter, google plus,... plugin in combination with angularfire2.

**Comment by FallenRiteMonk** [comment]
Closed in favor of: https://github.com/driftyco/ionic-native/issues/1589
