### ISSUE TITLE
ion-select does not support ion-options with boolean values

### ISSUE THREAD

**Issue by rayonx** [driftyco/ionic#11742]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
<ion-item>
  <ion-label>Is this new?</ion-label>
  <ion-select [(ngModel)]="isNew">
    <ion-option value="true">Yes</ion-option>
    <ion-option value="false">No</ion-option>
  </ion-select>
</ion-item>
```
`ion-option value` will parse the boolean value to string even if the model is of type boolean

**Expected behavior:**

`ion-option value="true"` should have a boolean value instead of a string value, I was expecting `ion-option value="'true'"` to return a string value instead of the one before. Instead both exhibits the same behavior.

**Steps to reproduce:**

See above

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : not installed
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.10.0
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by manucorporat** [comment]
this is not how angular input's work:
```
something="true"
```
is always passed as string, you need instead:
```
[something]="true"
```

**Comment by chandanch** [comment]
Refer to this: http://stackoverflow.com/questions/36802522/angular-2-ngmodel-binding-for-radio-input-of-boolean-type

**Comment by rayonx** [comment]
@manucorporat Thanks, it didn't occur to me that it was angular input. My mistake.
