### ISSUE TITLE
About slide solutions

### ISSUE THREAD

**Issue by ejiyuan** [driftyco/ionic#11747]
Using slides to display albums, 4000 photos slide very slowly, and do you have any good solutions?
my code:

    <ion-slides *ngIf="alreadyShowPhoto" initialSlide="{{indexLibraryCurrent}}" >
        <ion-slide *ngFor="let libraryItem of librarySlide">
            <img *ngIf="libraryItem" [src]="libraryItem.photoURL | cdvphotolibrary">
        </ion-slide>
    </ion-slides>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
