### ISSUE TITLE
The animation effect of the slides!

### ISSUE THREAD

**Issue by congtaoa** [driftyco/ionic#11749]
#### The animation effect of the slides. Possible values are: slide, fade, cube, coverflow or flip. 

 I hope to have more  properties   of the  animation effect of the slides!
**Could you add a depth property?  Thanks**

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#226
