### ISSUE TITLE
Push notification in iOS not working using IONIC 2 cordova phonegap push plugin

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [driftyco/ionic#11746]
**Ionic version:**  
2.23

**Cordova version**
7.0.1

**I'm submitting an issue which is related to IONIC PUSH NOTIFICATION using cordova phonegap plugin**  

**Current behavior:**
 In android working fine eg. getting push notification. But in iOS do not get the notification, but in alert I see the generated token.  

**Expected behavior:**
  iOS devices should get the notification as well  
 
**Related code:**

```
export class MyApp {
  rootPage = HomePage;
 
  constructor(platform: Platform, public push: Push) {
    platform.ready().then(() => {
      StatusBar.styleDefault();
      Splashscreen.hide();
 
      this.push.register().then((t: PushToken) => {
        return this.push.saveToken(t);
      }).then((t: PushToken) => {
       alert('Token saved:'+t.token);
      });
 
      this.push.rx.notification()
      .subscribe((msg) => {
        console.log('I received awesome push: ' + msg);
      });
    });
  }
}
```

**Other information:**
I believe I have properly created security certificates which I have uploaded to app.ionic profiles
and all other steps followed very carefully.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud#212
