### ISSUE TITLE
Lightweight version of polyfills.js with Ionic only code

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#11748]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x** 

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
There are three versions of polyfills:
* ionic-angular/polyfills/polyfills.js 
* ionic-angular/polyfills/polyfills.modern.js 
* ionic-angular/polyfills/polyfills.ng.js 

All of them contain prebuilt "core-js" and "zone.js" polyfills with pinned version on ionic's build time.

**Expected behavior:**
Introduce a lightweight version of polyfills.js which contain Ionic framework own polyfills, for example:
* ionic-angular/polyfills/polyfills.ionic.js 

**Background**: I'm using Ionic framework separately from ionic-cli with own setup of polyfills with custom versions of core-js/zone.js and want to include only ionic own polyfills to prevent duplications.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We actually already [do this under the hood(https://github.com/driftyco/ionic/tree/master/scripts/polyfill) but just have not integrated any good way for the user to choose which polyfill they want to use, yet. This is something we are looking into though.

**Comment by mnasyrov** [comment]
In my case it would be great to just have [polyfill.dom.js](https://github.com/driftyco/ionic/blob/master/scripts/polyfill/polyfill.dom.js) in a dist bundle together with the other polyfills if it fits to your plans.

**Comment by mnasyrov** [comment]
May be let the ticket be opened while there is no implemented solution?
