### ISSUE TITLE
controlInverse, what does it do ? Does it do something ? Let's find out !

### ISSUE THREAD

**Issue by PunkHaz4rd** [driftyco/ionic#11753]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've been looking at the documentation for ion-slides, and I've been wanting to reverse the direction to start on the right and swipe right to get content from the left.
So naturally I checked controlInverse. Though the documentation is not very very wordy about (there's nothing...) I tried to put it in my code to try and see if it was working.

**Expected behavior:**
I expected it to do something.

**Steps to reproduce:**
So I tried to put it in the html, without any luck. Also like this:
this.slides.controlinverse = true;

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by PunkHaz4rd** [comment]
Documentation would have been welcomed.
