### ISSUE TITLE
<ion-select [(ngModel)]="select-category"> popup design not as mobile device

### ISSUE THREAD

**Issue by ajaniketjain** [driftyco/ionic#11757]
Popup design is not showing as mobile platform , its showing some other design instead of platform popup design. Same case in alerts or any other popup. Please Help what i m missing in my code. Please Help what i m missing in my code.
![popupdesign](https://cloud.githubusercontent.com/assets/28888424/26342668/985681f6-3fb6-11e7-8fe4-391449434263.png)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
