### ISSUE TITLE
Set color of ion-toggle & ion-checkbox by a hex-color-string // binding critical style properties in a more accessible way

### ISSUE THREAD

**Issue by imamik** [driftyco/ionic#11754]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Setting the color of an ion-toggle or ion-checkbox button is only possible by providing the string of a corresponding, predefined sass color variable as documented in the official docs:
```
<ion-toggle color="somePredefinedSassColor"></ion-toggle>
```
But sometimes it is necessary to set the color after runtime. For example: In my current app I have to adjust the color to the logged in company/department's corporate design. Therefore I fetch a hex color string from the backend. Now providing a hex color string neither works with the color parameter, nor does it work with
```
[ngStyle]
[style.backgroundColor]
[style.color]
```
After a whole day of work I couldn't even figure out a work around. Closest I got was by getting the toggle-icon sub-object by it's class name via a document query and settings its background-color (used D3.js as a helper):
```
ionViewDidLoad() {
        d3.select(".toggle-icon").style("background-color", this.colors.primary);
}
```
But this only works with the first load, every any kind of refresh occurs the style falls back to the primary sass color (tried various lifecycle hooks - but none worked)...

**Expected behavior:**
Be able to set the color parameter of an ion-toggle and ion-checkbox by either the name of a sass string or a hex-color string like:
`<ion-toggle color="'#ff0000'"></ion-toggle>`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by patrickmcd** [comment]
@imamik I agree that we need a way to set arbitrarily-dynamic colors, rather than be limited to predefined SASS choices. There are plenty of use cases where a user should be able to choose any color of the hexadecimal rainbow for components. Here are a [couple](https://github.com/driftyco/ionic-app-scripts/issues/506) [other](https://github.com/driftyco/ionic/issues/9470) similar issues that you might want to check out.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#227
