### ISSUE TITLE
ionic cordova build android throws Error: spawn EACCES

### ISSUE THREAD

**Issue by gopi2mohan** [driftyco/ionic#11751]
I am working on mac please take a look at my [![error][1]][1] 

here is my **~/.bash-profile**

    export PATH=$PATH:/Users/xxxxx/Library/Android/sdk/platform-tools/
    export ANDROID_HOME=/Users/xxxx/Library/Android/sdk/
    export PATH=$ANDROID_HOME/platform-tools:$PATH
    export PATH=$ANDROID_HOME/tools:$PATH
    even $(user/libexec/path_helper -s)

and my **ionic info** result is

    global packages:
    
        @ionic/cli-utils : 1.1.2
        Cordova CLI      : 7.0.1 
        Ionic CLI        : 3.1.2
    
    local packages:
    
        @ionic/app-scripts              : 1.3.7
        @ionic/cli-plugin-cordova       : 1.1.2
        @ionic/cli-plugin-ionic-angular : 1.1.2
        Ionic Framework                 : ionic-angular 3.2.1
    
    System:
    
        Node       : v6.10.0
        OS         : OS X El Capitan
        Xcode      : Xcode 8.2.1 Build version 8C1002 
        ios-deploy : not installed
        ios-sim    : not installed

>on giving ionic cordova build android i am getting the above image error

>i belive it is something to deal with the environmental variable what i am missing is there anything i have to specify for mac.

>the above same environment is working in my linux system.

  [1]: https://i.stack.imgur.com/IH1Pb.png

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by jerson-suaza** [comment]
+1

**Comment by munyanyika24** [comment]
@gopi2mohan Did you find a solution to this?
I am experiencing the same issue and i have been struggling.
Please assist?
