### ISSUE TITLE
ionic cordova resources asks for credentials to ionic cloud every time

### ISSUE THREAD

**Issue by VsMaX** [driftyco/ionic#11750]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ionic cordova resources` asks every time for credentials to ionic cloud

**Expected behavior:**
`ionic cordova resources` asks at most ONCE for credentials to ionic cloud

**Steps to reproduce:**
`ionic cordova resources`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2 Build version 8C38
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2331
