### ISSUE TITLE
Ionicons: plane-outline is not outlined

### ISSUE THREAD

**Issue by antoine92190** [driftyco/ionic#11763]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The plan-outline icon from ionicons is not outlined in neither iOS simulator or iOS device.

**Expected behavior:**
plan-outline should be outlined on iOS platform.

**Other information:**
Duplicate of #10583
I left a comment there a few weeks ago, so the purpose of this issue is to get your attention back to it.

**Ionic Info:**
```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
```

**Comment by jgw96** [comment]
Thanks for the heads up! I reopened the original issue.
