### ISSUE TITLE
Http change or override Referer

### ISSUE THREAD

**Issue by drjoju** [driftyco/ionic#11762]
**Ionic version:**  (check one with "x")
[x] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm trying to override the referer header in a Http call in Ionic 1 or 2. As I see do somithing like. 
```

let headers = new Headers();
    headers.append('Content-Type', 'application/x-www-form-urlencoded');
    headers.append('Referer', 'www.exampple.com');
    headers.append( 'Authorization', 'Basic ' + _authdata );

```
The same issue if I try to fix the User-Agent

**Expected behavior:**
 In the network monitor attached to my android device I see

Referrer Policy:no-referrer-when-downgrade

An not Referer appears

**Steps to reproduce:**

**Related code:**

`
    var url = 'https://www.example.com';

    var post_data = 'j_username=user&j_password=my_pwd';

    var username = 'basic_user';
    var psw = 'basic_pwd';

    var _authdata = $base64.encode(username + ':' + psw);

    var config = {
      headers: {
        'Authorization': 'Basic ' + _authdata,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Access-Control-Allow-Origin': '*'

      }
    };

    $http.post(url, post_data, config)
      .then(function (response) {
          // Stringify the retured data
          console.log(JSON.stringify(response));
        },
        function (response) {
          console.log("ERROR: " + JSON.stringify(response));
        }
      );

`

**Other information:**

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
