### ISSUE TITLE
some problems with IOS9

### ISSUE THREAD

**Issue by MissCuriosity** [driftyco/ionic#11768]
version:[just uodate several days ago]
    ionic:3.1.2
    cordova: 7.0.1

project version:
    ionic: 1.3.1
    ios: 9.3.5/9.3.4
bug:
    some pages cannot open correctly in the app,but ios10 is ok.

    Here is the code:
    function A() {
        $http.post('/someUrl', data, config).then(function(){
            B();
        });
    }

    function B() {
        $http.post('/someUrl', data, config).then(function(){
            //do sth
        });
    }
    I used the fiddler,and I found that B failed.
    It's really a big problem for me and there is no log in xcode.would you please do me a favor to give me some solution?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
