### ISSUE TITLE
How to check if the app is running in background IONIC 1

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [driftyco/ionic#11760]
**Ionic version:**   
2.23
 
While using IONIC 2 push notification services , how can we check if the application is running in background or not.

I want to check this under this method of corodva push plugin
 

>  this.push.rx.notification()
>       .subscribe((msg) => {
>         console.log('I received awesome push: ' + msg);
>       });

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
