### ISSUE TITLE
how i can build a bowser release version?

### ISSUE THREAD

**Issue by Csirme** [driftyco/ionic#11774]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info hereglobal packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      :  You have been opted out of telemetry. To change this, run: cordova telemetry on. 6.4.0 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```
i want to release  web app,'ionic build' can't use and the 'ionic cordova build' only to 'iOS -release 'or 'andorid --release' .
how i can build a bowser release version?

**Comment by flaugere** [comment]
Did you try :` npm run build --prod` ?

**Comment by flaugere** [comment]
What about `cordova build browser` ?
I've got no idea about error posted...
