### ISSUE TITLE
Ionic Native's SpinnerDialog does not support W10 UWP  / IE11 / EDGE

### ISSUE THREAD

**Issue by tryadelion** [driftyco/ionic#11771]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ X] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic's Native SpinnerDialog plugin does not work on Windows 10 UWP platform, and there is no official alternative.

"Bug report" -> https://github.com/Paldom/SpinnerDialog/issues/43

**Expected behavior:**

Provide an alternative ionic native plugin implementation that works on every supported ionic platform 6 document how to perform a similar action on W10 UWP / IE11/ edge.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#1603
