### ISSUE TITLE
Navigation: Page deeplinks not working with tabs (PWA)

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic#11778]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
_Sorry in advance if this bug has been already reported. I'm aware there are many other related issues and that a rewrite is being done. I haven't seen any issue for this use case._

PWA deeplink navigation with tabs is currently broken on 3.3.0. The use case is simple: select a tab, push a view with a page with a deeplink and reload the page. The URL is rewriten to the current tab root. This behavior is easily reproducible in the latest `ionic-conference-app`.

**Expected behavior:**
Deeplinks to load the specified page on reload on the browser (PWA) using tabs and lazy-loading.

**Steps to reproduce:**
1. Clone the `ionic-conference-app` repo, install dependencies and run `ionic serve`.
2. Select the "Breakfast" event in the Schedule tab. The URL changes to `/#/tabs/schedule/sessionDetail/Breakfast`.
3. Reload the page. The root Schedule page is loaded instead (`/#/tabs/schedule/schedule`). This also throws an exception, but I think is related to mockup data not being initialized.

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Thanks for the detailed issue. We are aware of this (https://github.com/driftyco/ionic/issues/11756) and are making big changes to the internals of `navcontroller` to harden it for deeplinking / lazyloading. If everything continues to go well these `nav` changes should be in 4.0.0. We were hoping to get these changes in 3.3.0 but they were not totally ready yet and have not been tested heavily enough.

**Comment by FdezRomero** [comment]
Thanks for the info Justin, and sorry about the duplicate. With so many issues it's getting harder to know if they're really the same or just related 😅
