### ISSUE TITLE
Ionic cordova resources Does not generate Windows 10 UWP resources

### ISSUE THREAD

**Issue by tryadelion** [driftyco/ionic#11785]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ X] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Running "ionic cordova resources" does  not generate the desired resources, it says "no platforms installed", even when the platform is correctly listed on "ionic cordova platform ls"

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#2346
