### ISSUE TITLE
LoadingController - PopupWindow synchronisation issues

### ISSUE THREAD

**Issue by raxim1** [driftyco/ionic#11789]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1, I have tried to open popup, which contains a virtualScroll.
2, I'm sending an observable to it with "filters", so when the filter changes the list will be updated.
3, As there is a data load inside the popup, i have noticed, that i need to delay manually the data load,
as the transition of the modal window halts. (so the header of the modal window just appears at the middle of the screen, just under the loading popup)
4, When the data has been properly loaded, the transition continues as expected.
5, I have used a fake backend, just returning some fake data immediately, and that's causing this effect.
If it would have been some certain delay probably it wouldn't cause too much problem.

**Expected behavior:**
1, Transition shouldn't break, if there is a synch method, while the popup is opening.
2, LoadingController present method should show the loading popup immediately.

**Steps to reproduce:**
1,
```
ngOnInit() {
let obj = this;
obj.loader = this.loadingCtrl.create({
    content: "Please wait..."
});

obj.loader.present().then(() => {
      setTimeout(() => obj.doFetch(obj.dynaFilter, true), 100);
});
}
```

doFetch call an injected service method which returns back an Observable - so it's subscribing.

The main problem that if it's returning back so quickly, it's breaking the transition of the opening popup window. (that's why i had to use 100ms on setTimeout)

2,
```
ngOnInit() {
let obj = this;
obj.loader = this.loadingCtrl.create({
    content: "Please wait..."
});

obj.loader.present();

obj.doFetch(obj.dynaFilter, true);
```

If you are calling the present and after the fake data load, the loading popup is not appearing, even if the load takes seconds.
You can use then(), although i think it should be more error prone, as to find the right solution for it, consumed half day of mine.

For Ionic V1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic issues - http://plnkr.co/edit/z0DzVL?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
