### ISSUE TITLE
[3.3.0] deprecated scss variable

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#11799]
**Ionic version:**  (check one with "x")
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] feature request

**Current behavior:**
Just updated to ionic-angular 3.3.0 and got the following warning when I build my app:

    [08:07:40]  uglifyjs started ... 
    WARNING: you are using a deprecated variable
    Backtrace:
    	node_modules/ionic-angular/themes/ionic.mixins.scss:182, in mixin `deprecated-variable`
    	node_modules/ionic-angular/components/searchbar/searchbar.md.scss:70

**Expected behavior:**
Thought you might be interested. Expected: No warning. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#1011

**Comment by fiznool** [comment]
Not exactly sure why this was moved, since this is something that needs to be fixed in Ionic's SCSS files, not in app-scripts.

I'm seeing a similar warning with 3.4.2:

```
WARNING: you are using a deprecated variable
Backtrace:
	node_modules/ionic-angular/themes/ionic.mixins.scss:192, in mixin `deprecated-variable`
	node_modules/ionic-angular/components/button/button.ios.scss:213

WARNING: you are using a deprecated variable
Backtrace:
	node_modules/ionic-angular/themes/ionic.mixins.scss:192, in mixin `deprecated-variable`
	node_modules/ionic-angular/components/button/button.md.scss:258

WARNING: you are using a deprecated variable
Backtrace:
	node_modules/ionic-angular/themes/ionic.mixins.scss:192, in mixin `deprecated-variable`
	node_modules/ionic-angular/components/button/button.wp.scss:206
```
