### ISSUE TITLE
Subscribe, unsubscribe very simple declarative function wasn't working 

### ISSUE THREAD

**Issue by AUSdomgarcia** [driftyco/ionic#11802]
here's my code

this.events.subscribe('close:userPopOver', this.myMethod.bind(this) );

this.events.unsubscribe('close:userPopOver', this.myMethod.bind(this) );

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by AUSdomgarcia** [comment]
Hi @jgw96 your suggestion may not document my question, also I already made a work around, I just set my subscribed function to null to totally stopped this listener/event propagation. thank you.
