### ISSUE TITLE
ion-rage does not update binded variable when using keyboard arrows on desktop browser (ionic serve)

### ISSUE THREAD

**Issue by DatBluBat** [driftyco/ionic#11800]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
So, I have simple ion-range:
```
<ion-range [(ngModel)]="singleValue" color="danger" pin="true"></ion-range>

```
and everything is fine when I'm using my mouse to move knob to change current value, but when I tab on it and use keyobard arrows value does not change at all.

**Expected behavior:**
Binded variable should change value when I tab on range (select range component) and use arrows to move knob.

**Steps to reproduce:**
Just create simple ion-range:
```
  <ion-item>
    <ion-label>{{singleValue}}</ion-label>
    <ion-range [(ngModel)]="singleValue" color="danger" pin="true"></ion-range>
  </ion-item>

```
tab on it (select) and try to use keyboard arrows to move knob in desktop browser - variable does not change its value.

**Related code:**

```
export class HomePage {
  private singleValue = 0;

  constructor(public navCtrl: NavController) {

  }

}
```

**Other information:**
My app has no other logic.

```
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.3
Xcode version: Not installed

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! `ion-range` was not built with keyboard control in mind so this is something we would have to add. Because of this I am going to mark this as a feature request and move this over to our internal feature tracking repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#229
