### ISSUE TITLE
[Small Feature Request] Could you expose ionSlideTouchEnd in slides.ts?

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#11801]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] feature request

**Current behavior:**
Could you expose the event ionSlideTouchEnd in slides.ts? That would be really useful for me...

    ionSlideTouchEnd: EventEmitter<TouchEvent> = new EventEmitter();

**Expected behavior:**
    
    @Output() ionSlideTouchEnd: EventEmitter<TouchEvent> = new EventEmitter();

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#230

**Comment by peterpeterparker** [comment]
@jgw96 sure of course, thx for the feedback
