### ISSUE TITLE
CSS build size and color variables

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#11826]
**Ionic version:**
[x] **3.x**

**I'm submitting a ...**
[x] feature request (I guess)

**Current behavior:**
I've been having a look at my css bundle size, which seemed really big.

Using 11 different colors in the sass map, produces a 854KB css bundle.
Reducing that number to 3, gives me a css bundle of 374KB. This is raw, no gzip.

This is a huge difference and it would be great to have it improved in some way.
If it can't be improved significantly, it should definitely be documented. Maybe even in the default `variables.scss`.

Gzipped, it is of course less of a difference in terms of file size, but it's still 80.1KB vs 55.6KB. And the influence on performance is the same as without gzip.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

```

**Comment by patrickmcd** [comment]
You can probably close this in favor of these similar issues (though a note in the docs recommending less than ~10 colors would be helpful):

- https://github.com/driftyco/ionic-app-scripts/issues/506
- https://github.com/driftyco/ionic/issues/9470
- https://github.com/driftyco/ionic/issues/11754
- https://github.com/driftyco/ionic/issues/11806

**Comment by Manduro** [comment]
Wow, I must be blind, thanks.
