### ISSUE TITLE
bug(footer): ion-footer cannot be used with *ngIf

### ISSUE THREAD

**Issue by Glains** [driftyco/ionic#11858]
**Ionic version:**
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using a `<ion-toolbar>` element with `*ngIf` does **never** show when `*ngIf` initially evaluates to `false` or does **always** show when `*ngIf` initially evaluates to `true`.

**Expected behavior:**
`*ngIf` does dynamically hide/show the `<ion-toolbar>`.

**Steps to reproduce:**

Plunker:
--> https://plnkr.co/edit/3zTaZGncJV5qEj7tscQB?p=preview

**Related code:**

```
// does never show if showFooter initially evaluates to false, even if the value changes to true
<ion-footer *ngIf="showFooter">
  <ion-toolbar>
    <span>This is the footer.</span>  
  </ion-toolbar>
</ion-footer>
```

**Other information:**
Using property binding with `[hide]` does work.

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

System:

    Node       : v7.4.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by AmitMY** [comment]
The problem is with your plunker..
You did `<button ion-button (click)="presentPopover($event)">` while it should be `<button ion-button (click)="toggleFooter($event)">` (which works - toggles the footer)

**Comment by Glains** [comment]
@AmitMY Yeah thats correct, altough i wanted to address another issue. I though the plunker was ok since the footer didnt show as well. My bad...

In the end the footer **did** show, but it was overlapped by the tabs at the bottom of the page. The docs stated the following example
```
<ion-content></ion-content>

<ion-footer>
  <ion-toolbar>
    <ion-title>Footer</ion-title>
  </ion-toolbar>
</ion-footer>
```
which assumes a page without tabs i guess. To correctly show the toolbar you need to wrap it inside the `<ion-content>` like this
```
<ion-content>
  <ion-footer>
    <ion-toolbar>
      <ion-title>Footer</ion-title>
    </ion-toolbar>
  </ion-footer>
</ion-content>
```

If needed, this could be added to the docs. Thanks for your effort!

**Comment by AmitMY** [comment]
I am not sure what you mean.. mind creating a plunker for it?
What might be the case if I got at least partially what you are saying, is that both content and footer has `bottom: 0`, so when you toggle your `ngIf` footer you must also `this.content.resize()` (and `content` is a ViewChild)

Any way, a plunker, and a new issue will be much better

**Comment by Glains** [comment]
@AmitMY Thats it, you got it right. Your suggestion was the solution to my problem. Next time i will open a new issue and corresponding Plunker for it.
