### ISSUE TITLE
[bug] unable to build ionic android with org.apache.cordova.statusbar plugin

### ISSUE THREAD

**Issue by pixeldrew** [driftyco/ionic#1197]
Phongap and Cordova demo applications builds fine. 
OSX Mavericks
ionic@1.0.1-beta
Node v0.10.24
Android SDK Tools Revision 22.6.2
Android SDK Build Tools Revision 19.0.3
Android Platform Tools Revision 19.0.1
API level:        19

This is the build output:
$ ionic build android:

-compile:
    [javac] Compiling 5 source files to /workspace/android/helloWorld/platforms/android/ant-build/classes
    [javac] /workspace/android/helloWorld/platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:70: error: cannot find symbol
    [javac]             callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, statusBarVisible));
    [javac]                                                  ^
    [javac]   symbol:   class PluginResult
    [javac]   location: class StatusBar
    [javac] /workspace/android/helloWorld/platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:70: error: package PluginResult does not exist
    [javac]             callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, statusBarVisible));
    [javac]                                                                           ^
    [javac] 2 errors

**Comment by Anbarasan-321** [comment]
node:5396) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
ion id: 1): CordovaError: Failed to run “javac -version”, make sure that you ha
e a JDK installed.
ou can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
our JAVA_HOME is invalid: C:\Program Files (x86)\Java\jdk1.8.0_161\bin

I got the above error while build apk file and My Ionic info

cli packages: (C:\Users\dell\AppData\Roaming\npm\node_modules)

@ionic/cli-utils  : 1.19.1
ionic (Ionic CLI) : 3.19.1
global packages:

cordova (Cordova CLI) : not installed
local packages:

@ionic/app-scripts : 3.1.6
Cordova Platforms  : android 7.0.0 browser 4.1.0 ios 4.5.4
Ionic Framework    : ionic-angular 3.9.2
System:

Android SDK Tools : 26.1.1
Node              : v8.9.3
npm               : 5.5.1
OS                : Windows 7
Environment Variables:

ANDROID_HOME : C:\Users\dell\AppData\Local\Android\Sdk
Misc:

backend : pro   
   
Please share solution for this?
