### ISSUE TITLE
[Feature Request]: ion-list - Select button like Delete button

### ISSUE THREAD

**Issue by gastonbesada** [driftyco/ionic#1203]
It will be very helpful if allow Select button like delete button in ion-list.
Like Edit button in iOS 7 mail native app. https://www.youtube.com/watch?v=fKa-KFjUIGE#t=42

Thanks

**Comment by ericongkc** [comment]
Hi there, as this happened yet? if not has anyone found a way to change the ion-delete to be function as a select checkbox?

**Comment by cScarlson** [comment]
As there's not really much specialty to the delete-button, it may as well be just a `right-area`. I would only add that even the `ion-option-button`s should have programatic hooks as well.
