### ISSUE TITLE
Select Element Flicker in Chrome

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1207]
The new "select" element has changed from Beta 1 to the Nightlies for Chrome.  It nightly, selecting the element causes it to quickly open, close, open.

In Beta 1, the select works like this:

![selectbeta1](https://cloud.githubusercontent.com/assets/57374/2801371/3b9fbe38-cc81-11e3-8128-c030150bf2f2.gif)

In nightly, the select shows this flicker:

![selectnightly](https://cloud.githubusercontent.com/assets/57374/2801380/4c4a1a26-cc81-11e3-9e3c-e94fd64f2d6d.gif)

Code : 

```
<div class="list">

  <div class="item item-input item-select">
    <div class="input-label">
      Lightsaber
    </div>
    <select>
      <option>Blue</option>
      <option selected>Green</option>
      <option>Red</option>
    </select>
  </div>

</div>
```

**Comment by benmb1984** [comment]
I have also this problem with Chrome when I serve the project from Visual Studio 2015 with Ripple. When I use Ionic serve from the CLI (without Visual Studio and Ripple) it works fine in Chrom
