### ISSUE TITLE
SlideBox update() doesn't work with left-growing array

### ISSUE THREAD

**Issue by guillermin** [driftyco/ionic#1215]
When adding elements to the slidebox input array (ng-repeat) at the end of the array with push(), an update() works as expected: the new slides are added and the current slide is shown. If elements are added at the beginning of the array (unshift()), the update() is not working properly: the indexes don't adjust to the current position of the actual element.

**Comment by promactkaran** [comment]
I am trying the exact same thing @motionsmith is doing, any help would be appreciated. Slide box slipce puts the entire slide box into a broken state. if i splice the first index (0) it doesn't update and overlaps with last index image.

**Comment by phasnox** [comment]
+1 any news on this?

**Comment by yingzhox** [comment]
any update on this?
