### ISSUE TITLE
Place file input inside ion-content won't allow user to select file on Mobile Safari

### ISSUE THREAD

**Issue by phuongnd08** [driftyco/ionic#1237]
I put a simple `<input type="file">` inside `ion-view > ion-content` and user can't click on it to select file. Its screenshot: 
![screen shot 2014-04-30 at 7 59 36 pm](https://cloud.githubusercontent.com/assets/184037/2841459/58d9a998-d067-11e3-88ae-f6539e42f995.png)

This is the codepen: http://codepen.io/anon/pen/EmaiB

**Comment by kovacssupki** [comment]
i have this problem also in ionic 1!!!  please check if there was some regression?
