### ISSUE TITLE
input[type="text"] default placeholder text color too light

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic#125]
currently is #f8f8f8 so can't see white on white.

iOS uses #E5E5E5 according to Ben

**Comment by mohamedayed** [comment]
u can change your placeholder with the help of some prefixes hope my code helps
*::-webkit-input-placeholder {
  color: red !important;
}
*:-moz-placeholder {
  color: red !important;
}
*:-ms-input-placeholder { /* IE10+ */
  color: red !important;
}

input::-webkit-input-placeholder {
    color: #999;
}
input:focus::-webkit-input-placeholder {
    color: red;
}

/* Firefox < 19 */
input:-moz-placeholder {
    color: #999;
}
input:focus:-moz-placeholder {
    color: red;
}

/* Firefox > 19 */
input::-moz-placeholder {
    color: #999;
}
input:focus::-moz-placeholder {
    color: red;
}

/* Internet Explorer 10 */
input:-ms-input-placeholder {
    color: #999;
}
input:focus:-ms-input-placeholder {
    color: red;
}

**Comment by sirdowan** [comment]
Ionic takes care of the js for your. 
**HTML**
```
<label class="placeholer-parent">
  <input type="search" >
  <span class="placeholder">Search in Reservations</span>
</label>
```
**SCSS**
```
.placeholer-parent {
  position: relative;
  .placeholder {
    position: absolute;
    bottom: 3px;
    color: rgba(255, 255, 255, 0.64);
    font-size: 15px;
    left: 38px;
  }
  input:focus + .placeholder,
  input.ng-not-empty + .placeholder{
    display: none
  }
}
```
