### ISSUE TITLE
[feature request] Horizontal bouncy scrolling in android

### ISSUE THREAD

**Issue by glomotion** [driftyco/ionic#1255]
After a bit of testing, I've come to the conclusion that in Android (tested on 4.3 + 4.4), Ionic is capable of 'bouncy' scrolling vertically, but not horizontally. I see from the documentation, that the ion-content directive has a "has-bouncing" property, though the directive itself is not capable of horizontal scrolling (atleast using the "ionic scroll method").

Interestingly enough, the ion-scroll directive seems to support horizontal scrolling, though it does not have a setting relating to "has-bouncing", thus on android, does not do that nice bouncy scrolling effect while scrolling the x axis. sadface!

I've posted this to the forums, and Ionic team member (Calendee), told me to create a feature request, so here it is ... :)

Forum thread: http://forum.ionicframework.com/t/horizontal-bouncy-scrolling-in-android/3612
Demo codepen: http://codepen.io/calendee/pen/HIuft

**Comment by iveoteam** [comment]
When can we expect this? This is a huge deal for me at the moment...

**Comment by javifr** [comment]
+1

**Comment by 1BJK903** [comment]
Is there a solution for this? Major blocking issue to go to production right now @mhartington?
