### ISSUE TITLE
Make statusbar plugin give event when statusbar height changes on ios

### ISSUE THREAD

**Issue by DynamicLeo** [driftyco/ionic#1257]
hello  every one i meet a issue with ios hotspot

this picture is my app
https://docs.google.com/file/d/0B6tIg9_b_ZnLbExWTFBYRHRIS2M/edit?pli=1

when i open iphone hotspot share wifi , the tabs will too low
https://docs.google.com/file/d/0B6tIg9_b_ZnLcC0wTEYyQTFrXzA/edit?pli=1

**Comment by gslender** [comment]
I'm not sure if this is related, but I'm seeing the behaviour whereby the app initially is pushed down, and then bounces back up again - so the hotspot or in-call additional status bar heigh is over the top of the Ionic header. I'm of the view that the header should drop down (most apps do this) and appear below the increased iOS standard status bar height. 

Have I done something wrong in the setup as my app looks ok when the status bar doesn't have extra hotspot or in-call height. I get the correct colour and lighten text effect as expected - just odd behaviour when hotspot or in-call height is added to the native status bar ????
