### ISSUE TITLE
ionic.Platform.fullscreen(true,false) make tabs low

### ISSUE THREAD

**Issue by DynamicLeo** [driftyco/ionic#1258]
hello everybody

in my app i use ionic.Platform.fullscreen(true,false) to hide statusBar

but tabs will be too low

from
http://goo.gl/8pNIWA

to
http://goo.gl/BcbjQy

thanks for every one

**Comment by AnupKumarPanwar** [comment]
<preference name="Fullscreen" value="true"/> 
paste this in config.xml file to make the app full screen
