### ISSUE TITLE
How to disable slidebox for a while? 

### ISSUE THREAD

**Issue by tamvm** [driftyco/ionic#1259]
I checked this document and found that disable-scroll doesn't work at all. Because I have many horizontal scrollable area on the screen and I want when I start to scroll on items I need to disable slidebox for a while to prevent windows and elements are scrolled at the time.

**Comment by beauby** [comment]
@ajoslin: Any specific reason for deprecating `disableScroll` instead of leaving the two options? Using the delegate for this seems to cause problems when having a slidebox inside a modal.
