### ISSUE TITLE
Add status bar tap scroll to top support

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#126]
Shouldn't be hard. Just listen for taps at the top of the screen and call scrollTo(0, 0) on main scroll area

**Comment by mikehaas763** [comment]
As far as I can tell, this doesn't make the status bar tap scroll to the top but makes the header bar tap scroll to the top. I'm not sure if cordova provides an event out of the box for a status bar tap or if it requires a plugin. Either way, does it make sense for ionic header bar to subscribe to a status bar tap event and trigger the scroll just as it does when the header bar itself is tapped?
