### ISSUE TITLE
Lag in switching between tabs

### ISSUE THREAD

**Issue by sahilgupta** [driftyco/ionic#1260]
Hi,

We are using the tabs app(https://github.com/driftyco/ionic-starter-tabs) as our starting template, based on Ionic, v1.0.0-beta.2.

However, after adding just over 30 items having a small image in `ion-list`, the lag when switching between from the home to friends tabs becomes pretty noticeable.

The same lag can be noticed when switching back from a friend's detail view to main list page.

I have created a sample repo with some test data to show this effect.
https://github.com/sahilgupta/ionic-perf

I am using a Nexus 4 running android 4.4.2, for testing.

Is this performance issue related to Ionic or is this the best we can expect out of a PhoneGap app?

**Comment by jernejc** [comment]
I notice this too a lot on Android devices. Lag and slow tab switching that is. Actually was looking for a solution to precompile the DOM on app load, any progress on this?

In my prototype, I had all my HTML included on load and animations seemed much smoother (simple translate3d left to right).

**Comment by stanchiam** [comment]
Does this help?
http://scottbolinger.com/4-ways-to-make-your-ionic-app-feel-native/
