### ISSUE TITLE
First nested tab does not get selected when selecting parent tab

### ISSUE THREAD

**Issue by ssassi** [driftyco/ionic#1276]
When using nested tabs I want the first nested tab selected by default.
Please, look at this example: http://codepen.io/ssassi/pen/djGJB2. The first tab's content under home is not rendered when clicking on the Home tab.

**Comment by henry74** [comment]
+1

**Comment by luisrudge** [comment]
I'm having this problem too! And I'm using the master branch. @adamdbradley is this exptected?

**Comment by ram-you** [comment]
+1

**Comment by Phoscur** [comment]
+1 is this landing soon? Merge and define milestone please!

**Comment by Yuripetusko** [comment]
+1 Experiencing same issue in current stable build

**Comment by www-wowow-so** [comment]
ok,it's work for me~

**Comment by k1n6** [comment]
How would I fix this issue in ionic lib v 1.x (I tried 1.24 and 1.33 with no luck)
