### ISSUE TITLE
Strange ghosting effects on ios with beta 3

### ISSUE THREAD

**Issue by vincentjames501** [driftyco/ionic#1278]
After migrating from beta 1 -> beta 3, it looks like all of my iOS 7 devices are faced with this issue.  Looks like this person may have experienced it as well? (http://forum.ionicframework.com/t/1-0-0-beta-3-americium-released/3590/21#)

![alt text](http://i60.tinypic.com/k1wffs.png)

Code snippet (I removed a bunch of stuff but this is the basic layout):

``` html
<ion-view title="Details">
    <ion-content class="has-header" >
        <div id="confirmation-wrapper" class="card">
        </div>

        <div class="list card">

            <div class="item item-avatar notification-details">
                <img id="contact-image" ng-src="...">

                <h2 class="notification-initiator-name">{{notification.initiator.name}}</h2>

                <p class="notification-subject">{{notification.subject}}</p>
            </div>

            <div class="item item-body">

                <img id="notification-image">

                <p>
                    {{notification.body}}
                </p>

                <p>
                    <a class="subdued">Sent on {{notification.createdAt | date: 'medium'}}</a>
                </p>
            </div>

        </div>
    </ion-content>
</ion-view>
```

**Comment by gardengrocer** [comment]
I have the same issue with ghosting on scroll content i fixed it by adding .scroll-content {  position: fixed;
}

**Comment by csvendsen** [comment]
I had the same strange issue with ghosting using 
<ion-content has-bouncing="true" scrollbar-y="true" class="ionic-tag" zooming="true" >
I fixed it by adding 
.scroll-content {
  position: fixed;
}
