### ISSUE TITLE
[Feature] on-return and return-close keyboard utility (code included)

### ISSUE THREAD

**Issue by ashconnell** [driftyco/ionic#1283]
We are using the ionic fork of the cordova keyboard plugin which is working flawlessly so far. I thought i'd share our solution to the problem of not having the accessory bar (prev, next, and done buttons above the keyboard), since this is a giant leap towards a more native experience.

You already added an outside click event which closes the keyboard and blurs which is great. But if the user clicks the "Return" button or whatever, nothing happens. Thus the following directive was born.

There are two attributes you can put on inputs. `on-return` and `return-close`:

`on-return` is a function to fire when the user hits the return key
`return-close` invokes ionic's magic to blur and close the keyboard and viewport correctly.

```
app.directive('input', function($timeout){
     return {
         restrict: 'E',
         scope: {
             'returnClose': '=',
             'onReturn': '&'
        },
        link: function(scope, element, attr){
            element.bind('keydown', function(e){
                if(e.which == 13){
                    if(scope.returnClose){
                        console.log('return-close true: closing keyboard');
                        element[0].blur();
                    }
                    if(scope.onReturn){
                        console.log('on-return set: executing');
                        $timeout(function(){
                            scope.onReturn();
                        });                        
                    }
                } 
            });   
        }
    }
});
```

It's ridiculously simple and adds yet another layer of awesome sauce to our ionic app.

Feel free to Driftify this and use it in ionic.

**Comment by juukie** [comment]
Thanks @ashconnell, works like a charm.
