### ISSUE TITLE
$state.go('mylocation', {}, {location:'replace'}); ignored by back button.

### ISSUE THREAD

**Issue by gigablox** [driftyco/ionic#1287]
Let's say I redirects users to a different view if they arrive at a route that is out of sequence:

    if($state.previous.name != 'part3'){
      $state.go('part1', {}, {location:'replace'});
    }

When the user is redirected the back button in the nav bar is still there, but the history API has been updated and the previous state was effectively eliminated already.

**Comment by caco0516** [comment]
Hi my problem is that i am in the Login Page when user log in succefully , i redirect to dashboard but when back button is pressed , my app redirect to login again and thats sucks , and pretty new to angular and ionic , so any help will be awesome .

**Comment by HriBB** [comment]
I use $state.go() with notify: false and it breaks ionic navigation. I have angular-carousel and I want to be able to update the hash without reloading the view when slides change. I can successfully do so with

    $state.go('app.location_image', {locationId: location.id, imageId: image.id},{
        notify: false
    });

However, this break the ionic navigation stack. The expected behavior when using notify: false is that history stack is not changed.

I want it like this

Map > Location > Carousel slide 1 > Carousel slide 2 > Carousel slide 3 > [back] Location > [back] Map

But at the moment its something like this

Map > Location > Carousel slide 1 > Carousel slide 2 > Carousel slide 3 > [back] Location > [back] Carousel slide 2 > [back] Carousel slide 1

I also tried with

    $ionicHistory.currentView($ionicHistory.backView());

    $state.go('app.location_image', {locationId: location.id, imageId: image.id},{
        notify: false
    });

But it breaks transitions.

I found https://gist.github.com/dabroek/e0e5ca33c55e8c78c6ca but not really sure how to use it.

**Comment by jorgecasar** [comment]
@HriBB, this gist does the same you did but for clicks events. It works adding `navSilent` attribute to the links that you want to do silent navigation.

The option `notify:false` is to avoid broadcast the events `stateChangeStart` and `stateChangeSuccess`. If you don't want to change the history stack you have to use `location: 'replace'`.

Take a look https://github.com/driftyco/ionic/issues/1287#issuecomment-63248366 or  https://github.com/driftyco/ionic/issues/1287#issuecomment-67752210 (if you are using beta14)

**Comment by HriBB** [comment]
@jorgecasar thanks for clarifying things. I'm pretty new to AngularJS and Ionic, learning something new is always good :)

I've basically given up on this, because as soon as I solve one problem, a new one arises. I've tried just about every hack I could find, without luck.

I've made a short video illustrating the problem. The back transition is broken. I have no idea what's wrong and I don't have time to investigate. Maybe some Ionic guru will understand what the problem is after watching the video. 

http://youtu.be/ELvCIjr6G_o

This is the my last attempt, if anyone is interested.

    $scope.$watch('carousel.index', function (newIndex, oldIndex) {
      if (newIndex != oldIndex) {
        var image = $scope.location.files[newIndex];
        $ionicHistory.currentView($ionicHistory.backView());
        $state.go('app.location-images', {locationId: location.id, imageId: image.id}, {
          location: 'replace',
          notify: false
        });
      }
    });

After carousel index changes, I want to replace the hashtag without reloading state and adding to ionic history stack.

**Comment by Ionitron** [comment]
Greetings @gigablox!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by danharper** [comment]
This is still an issue.

For now, the hack @jorgecasar and @colllin posted is working.

**Comment by mattzuba** [comment]
Another vote for reopening this - the assistance provided so far appear to be hacks, not usage answers.

My particular use-case - login is required to use my app, but once someone logs in, I don't want them to be able to use the hardware back button to go back to the login form (they need to select logout from menu).  On successful login, I was using $state.go('home', null, {location: 'replace'}), but if I hit back, I just go back to the login page.

cc @ajoslin

**Comment by calendee** [comment]
Don't think re-opening is going to happen.  Added Feature Request : #3417

**Comment by gigablox** [comment]
This is definitely still an issue. Starting my second project a year later and I can't believe something as fundamental as keeping synced states between the native history API and the Ionic history provider aren't solid yet. Just ran into this again.

**Comment by gigablox** [comment]
Starting my second project a year later and I can't believe something as fundamental as keeping synced states between the native history API and the Ionic history provider aren't solid yet. 

*Am I doing something wrong?*

A use case:

Let's say I have a state that is presented to a "first time user" by checking for a `localStorage` variable. This page happens to be a form for user settings. Once a user submit this form, he is redirected to the main "home" screen.

Clicking "back" would be not make any sense because the user would be going back to this form he just filled out. I would expect the function that handles submit to contain something like:

    $state.go('home',{},{location:'replace'});

However going back to this form in the future should also be possible so adding a blanket statement to say you can never go back would not be good either.

Having the ability to tailor the history through the `$state` provider is really what were looking for here.

**Comment by colllin** [comment]
Daniel, maybe you can clear history before going 'home' in the case that
this was a first time user?  You could pass in a firstTimeUser flag in the
state params.

**Comment by Deminetix** [comment]
I built a solution to remove states from history here: https://github.com/driftyco/ionic/issues/3750
It plays nice with cached views and swipe-back in 1.0.0

**Comment by jorgecasar** [comment]
I make this example in the playground to test this behavior. Feel free to fork or play to get any better solution. I implement what we said, but second time you click on step2 it doesn't work.

http://play.ionic.io/app/07ab41dd024e

**Comment by dwilt** [comment]
I'm also having this issue as well. I'm using the slidebox and trying to update the URL every time and would like the back button to navigate to previous slides. The video that @HriBB posted is exactly what I'm experiencing and have tried what @jorgecasar and @colllin have posted but can't get a completely bug-free solution (not caring at this point that they are hacks).

**Comment by Deminetix** [comment]
@dwilt for your particular use case you could just intercept the android back button. You don't need to update the URL just change the slide

**Comment by yemaw** [comment]
I'm also having this issue as well. I need to update the url parameter without writing into history. Any workaround?

**Comment by StevenConradEllis** [comment]
I have tried every trick under the sun to prevent a view from being cached (including most of the suggestions above), but it still is being cached. Really annoying and kind of a showstopper for developing a proper flowing app. 
When one has to do all kinds of workarounds to get something like this working, the option of just developing the app in native becomes more and more viable. 
I know the platform is open source and developed by a bunch of very clever developers (for which I am very grateful), but this problem in the platform really needs to be addressed.

**Comment by longsangstan** [comment]
@colllin 's solution works for me.
