### ISSUE TITLE
Feature Request: Make it possible to specify the animation used for a transition

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic#1288]
It would be helpful to be able to specify which animation is used for a transition. Here is an example use case of my app. I have a tab view listing the soccer matches of the next soccer world championship. So the list looks like this:
1) Match 1
2) Match 2
3) Match 3
4) Match 4
...

Each match list entry is linked to a detail page for that match. So the link structure is like this:
1) Match 1 -> Detail View Match 1
2) Match 2 -> Detail View Match 2
3) Match 3 -> Detail View Match 3
4) Match 4 -> Detail View Match 4
..

All pretty normal. To enable a faster navigation the detail views are working like a carousel (I can not use a carousel there because of performance issues, it would have to load all details of all matches at once). Thus it is possible to navigate from a match detail view directly to the detail view of the next match or to the detail view of the previous match without having to return to the list main view. So the link structure in the detail view for match 2 looks like this

Detail View Match 2 -> Detail View Match 1
Detail View Match 2 -> Detail View Match 3
Detail View Match 2 Back Button -> List View

The use case now is as follows:
1. The user chooes in the list match 2. -> The app changes to Detail View Match 2. 
2. The user changes directly from Detail View Match 2 to Detail View Match 1.

Now it is necessary to tell Ionic to use a left to right transition because the user is logically going backwards in the list to the previous match. If Ionic uses the standard right to left transition this is irritating for the user in this situation. It is like a carousel using a right to left transition for going backwards.

I have the navigation working as described above apart from the transition direction. For the navigation I am using $location.path(url).replace();

**Comment by evanmrose** [comment]
Also interested in the navigation pack. Any updates on this?

**Comment by clickonchris** [comment]
+1

**Comment by kayzee** [comment]
+1 as well. I have an 

```A -> B1 -> B2 -> B3 -- $state.go("A") --> A ```

The transition back to A is right to left. I know it is impossible to guess the correct animation, which is why it would be fantastic to allow something like:

```
$ionicHistory.nextViewOptions({
    animationRightToLeft: false
});
```

**Comment by kayzee** [comment]
I just found the `nav-direction` directive, but it doesn't appear to be working for me.

```
<ion-nav-bar>
    <ion-nav-buttons>
      <div class="buttons">
        <button class="button button-icon icon ion-ios-arrow-back" ng-click="goHome()" nav-direction="back"></button>
      </div>
    </ion-nav-buttons>
</ion-nav-bar>
```

**Comment by bonatoc** [comment]
Me neither. Ionic still deserves a clearer way, or a good example on how to set/hack page transitions the proper/official way.

**Comment by ChristiaanScheermeijer** [comment]
You can do it programmatically with the `$ionicViewSwitcher`.

```js
$ionicViewSwitcher.nextDirection('back');
$state.go('login');
```

**Comment by kayzee** [comment]
Thank you @ChristiaanScheermeijer!!! This works perfectly!  Where is it documented?

**Comment by ChristiaanScheermeijer** [comment]
It's not documented that's why I'm not sure if this is supposed to be used. But at least it works :)

**Comment by DeepV101** [comment]
AH! it's been driving me crazy for weeks, and I finally figured out animations in ionic after digging through the code.. here's what I've learned, hopefully it'll help someone else out there:
There's actually quite a few ways to set the animations for ion-view when using ion-nav-view.  According to ionic-angular.js, function getTransitionData():
    // Priority
    // 1) attribute directive on the button/link to this view
    // 2) entering element's attribute
    // 3) entering view's $state config property
    // 4) view registration data
    // 5) global config
    // 6) fallback value

for item #1: you can simply set the next-transition attribute on any button or link.  This also means you can set $ionicViewSwitcher.nextTransition('transitionName') in your javascript before performing any type of view change.  Keep in mind that this transition will not be relevant when you go backwards!

#2:You can simply set the view-transition attribute on the highest level element for the incoming view (generally ion-view). Will apply when the view is leaving and coming;

#3: As part of the configuration in your app.js, or as part of your controller setup, you can set the viewTransition property on the $state object.  Will apply when the view is leaving and coming;

#4: not sure what this is about, seems to be an outdated comment

#5:  Sets the transition across the application, set this as part of the config.  I believe for this one you'll need to set the $ionicConfigProvider.views.transition function to handle your transition.

In general, when you're setting the transtions, there are three options, ios (default), android, and none.  If you want to define your own, it's not very hard.

The format is something along the lines of this (copied from the ios transition, replace instances of ios with your transition name):

.config(function ($ionicConfigProvider) {
        $ionicConfigProvider.transitions.views.ios= function (enteringEle, leavingEle, direction, shouldAnimate) {
            alert('testing my animation");

            function setStyles(ele, opacity, x, boxShadowOpacity) {
                var css = {};
                css[ionic.CSS.TRANSITION_DURATION] = d.shouldAnimate ? '' : 0;
                css.opacity = opacity;
                if (boxShadowOpacity > -1) {
                    css.boxShadow = '0 0 10px rgba(0,0,0,' + (d.shouldAnimate ? boxShadowOpacity * 0.45 : 0.3) + ')';
                }
                css[ionic.CSS.TRANSFORM] = 'translate3d(' + x + '%,0,0)';
                ionic.DomUtil.cachedStyles(ele, css);
            }

            var d = {
                run: function (step) {
                    if (direction == 'forward') {
                        setStyles(enteringEle, 1, (1 - step) * 99, 1 - step); // starting at 98% prevents a flicker
                        setStyles(leavingEle, (1 - 0.1 * step), step * -33, -1);

                    } else if (direction == 'back') {
                        setStyles(enteringEle, (1 - 0.1 * (1 - step)), (1 - step) * -33, -1);
                        setStyles(leavingEle, 1, step * 100, 1 - step);

                    } else {
                        // swap, enter, exit
                        setStyles(enteringEle, 1, 0, -1);
                        setStyles(leavingEle, 0, 0, -1);
                    }
                },
                shouldAnimate: shouldAnimate && (direction == 'forward' || direction == 'back')
            };

            return d;
        };
    });

followed by the css:

// iOS View Transitions
// -------------------------------

$ios-transition-duration:              500ms !default;
$ios-transition-timing-function:       cubic-bezier(.36, .66, .04, 1) !default;
$ios-transition-container-bg-color:    #000 !default;


[nav-view-transition="ios"] {

  [nav-view="entering"],
  [nav-view="leaving"] {
    @include transition-duration( $ios-transition-duration );
    @include transition-timing-function( $ios-transition-timing-function );
    -webkit-transition-property: opacity, -webkit-transform, box-shadow;
            transition-property: opacity, transform, box-shadow;
  }

  &[nav-view-direction="forward"],
  &[nav-view-direction="back"] {
    background-color: $ios-transition-container-bg-color;
  }

  [nav-view="active"],
  &[nav-view-direction="forward"] [nav-view="entering"],
  &[nav-view-direction="back"] [nav-view="leaving"] {
    z-index: $z-index-view-above;
  }

  &[nav-view-direction="back"] [nav-view="entering"],
  &[nav-view-direction="forward"] [nav-view="leaving"] {
    z-index: $z-index-view-below;
  }

}

**Comment by yesir1006** [comment]
Any exciting update on this? I am newbie on ionic, where can I find all the animation definition in ionic, like slide-left-right?

**Comment by alaa-alshamy** [comment]
what happened on this issue?

**Comment by boshmaf** [comment]
+1

**Comment by mhartington** [comment]
This was added in beta 14.

http://ionicframework.com/docs/api/directive/navTransition/
http://ionicframework.com/docs/api/directive/navDirection/

**Comment by boshmaf** [comment]
Yes. Thanks.

I used this, and it works great.
```
$ionicViewSwitcher.nextDirection('back');
$state.go('login');
```

**Comment by dinesh36** [comment]
@boshmaf Great !!!!
