### ISSUE TITLE
[Feature] ionSearch for items

### ISSUE THREAD

**Issue by gastonbesada** [driftyco/ionic#1289]
Is possible to include ionSearch directive for items?
http://forum.ionicframework.com/t/ionic-search-directive/3402

Like UISearchBar in iOS 7
https://developer.apple.com/library/ios/documentation/uikit/reference/UISearchBar_Class/Reference.html
https://www.youtube.com/watch?v=UE4h_Td6W6U#t=2317

Key features should be:
1 - Hidden search below the nav/header bar when the content view is loaded (optional).
2 - Animate the search input to nav/header when focused.
3 - Backdrop when search input is focused (optional).
4 - Change backdrop to ionicLoading when starting to search.
5 - Add a "Cancel" button to the right outside the input when search input is focused to back to the content view.
5 - Add a clear (x) button inside the input search to the right when a key is pressed to clear the input.
6 - Change the default return text in cordova keyboard to "search" (or custom).

Update: item 6 is not possible in cordova yet. I opened an issue in Apache Jira requesting some help with this:
https://issues.apache.org/jira/browse/CB-6656

Referenced issues:
https://github.com/driftyco/ionic/issues/1283
https://github.com/driftyco/ionic/pull/411
https://github.com/driftyco/ionic/issues/405

Thanks

**Comment by djett41** [comment]
@gastonbesada @perrygovier hey guys I created a directive which pretty much does what this request is asking for (both iOS and Android).  Check out the animated gif here http://makeagif.com/i/EZ-klS .  I added all of the info on the trello issue, also committed the code/tests/docs to the ionic repo i forked just for this request.

Check it out and let me know what you think!

**Comment by brauliobo** [comment]
@djett41 very nice! could you make a plugin of it?

**Comment by djett41** [comment]
Sure hopefully I can get around to it sometime soon :-)

**Comment by djett41** [comment]
@brauliobo I just registered this as a bower component. You can check out the repo at https://github.com/djett41/ionic-filter-bar for more information

**Comment by brauliobo** [comment]
@djett41 nice! will try it. cc @viniciuscb
