### ISSUE TITLE
Make it possible to align checkbox to the right

### ISSUE THREAD

**Issue by fredgalvao** [driftyco/ionic#1290]
I was able to achieve this with very little code change on codepen, and I think it's quite a nice addition to the checkbox feature having `item-checkbox-right` and `item-checkbox-left` just like pretty much everything list-wise.

http://codepen.io/fredgalvao/pen/ctKwp

I could make a PR on the weekend if it's deemed necessary, but I think this is a pretty small change and could come into tomorrow's beta?
Looking forward to this.

**Comment by 111crb111** [comment]
seems like ionic change checkbox style and right side checkbox buggy now

**Comment by smorstabilini** [comment]
@111crb111  if you replace 

    <ion-item class="item-checkbox" ...
with 

    <ion-item class="item-checkbox-right" ...
it doesn't work.
But if you use \<ion-checkbox\> instead of  \<ion-item\> it does work. see fredgalvao' codepen.
Hope this helps

**Comment by ryandraper** [comment]
Just what I needed! Thanks @fredgalvao :)

**Comment by fredgalvao** [comment]
This is supposed to work out-of-the-box on ionic now, since @adamdbradley / @ajoslin brought the codepen into native ionic css. If it's not working, it's a regression of some sort and it should be fixed or looked into, I guess.

Anyways, you're welcome, @ryandraper !

**Comment by mnewmedia** [comment]
should be documented http://ionicframework.com/docs/components/#checkbox

**Comment by lucassch** [comment]
docs?

**Comment by segersrobbert** [comment]
Doesn't seem to be working in Ionic 2.0.0-beta.24 with an `ion-checkbox` inside an `ion-item` using @fredgalvao codepen style. Is there a syntax to make this work out-of-the-box in Ionic2 like `ion-checkbox-right` ?

**Comment by meicj** [comment]
I met the same problem, and found it works perfect by `<ion-checkbox class="item-checkbox-right">` . Thanks a lot @fredgalvao @smorstabilini . Hope a doc on http://ionicframework.com/docs/components/#checkbox

**Comment by prosenjit-itobuz** [comment]
.item-checkbox-right {
  flex-direction: row-reverse;
}

<ion-item class="item-checkbox-right">

**Comment by rodneyjoyce** [comment]
I found this worked for me:  https://ionicframework.com/docs/api/components/item/Item/

Use an "item-end"

**Checkboxes, Radios and Toggles**
Checkboxes are positioned in the same place as the item-start attribute. Radios and Toggles are positioned in the same place as the item-end attribute. All of these components can be positioned differently by adding the item-start or item-end attribute.
