### ISSUE TITLE
 collection-repeat directive bug on Android 4.1

### ISSUE THREAD

**Issue by shivanik** [driftyco/ionic#1292]
I tried this code pen code 
http://codepen.io/ionic/details/mFygh5on Nexus 4 (android 4.4) as well as on Samsung Galaxy S3 (android 4.1)....on the samsung phone, it seems to hang mid-way during the scroll. IT looks like some kind of bug. 
You can try cloning it from here:
git clone https://gist.github.com/11531038.git

The logs show the following error when the list scroll hangs:

D/CordovaLog(20585): http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.js1: Line 32999 : Uncaught TypeError: Cannot set property 'webkitTransform' of undefined
E/Web Console(20585): Uncaught TypeError: Cannot set property 'webkitTransform' of undefined:32999

**Comment by AphexHenry** [comment]
I got this problem sometime too. The scrolling got disabled. I can't inspect. Is the fix above integrated into the last version of ionic? Thanks

**Comment by clearride** [comment]
getting this on samsung with android 4.1.2 after adding collection-repeat  works well with ng-repeat.
