### ISSUE TITLE
Select not working on Android 2.3

### ISSUE THREAD

**Issue by marcusanzalone** [driftyco/ionic#1298]
Select on Android 2.3 is not working. I'm working from master. 

There was a issue #1254 and that fixed most of the issue, but not Android 2.3. In reviewing that fix, I noticed there was a similar construct in scrollView.js.

```
scrollView.js - near line 675
    self.touchStart = function(e) {
      self.startCoordinates = getPointerCoordinates(e);

      if ( ionic.tap.ignoreScrollStart(e) ) {
        return;
      }
```

Select on Android 2.3 works if you change the one statement to:

```
if ( ionic.tap.ignoreScrollStart(e) || e.target.tagName === 'SELECT' ) {
```

I tested pre/post change on android 2.3, 4.4, iOS 6/7, and Safari/Chrome with no obvious bad side effects.

**Comment by RupenAnjaria** [comment]
Is this issue have been resolved? I am facing the same, see the description on Stackoverflow at 
http://stackoverflow.com/questions/37077311/dropdown-text-issue-in-ionic-cordova-on-android-device

**Comment by navneet77** [comment]
Maybe try using Gap Debug there you can see the actual html DOM generated
by the code it will help you find the problem

On Tue, May 10, 2016 at 1:44 AM, RupenAnjaria <notifications@github.com>
wrote:

> Is this issue have been resolved? I am facing the same, see the
> description on Stackoverflow at
>
> http://stackoverflow.com/questions/37077311/dropdown-text-issue-in-ionic-cordova-on-android-device
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/1298#issuecomment-217902545>
>



-- 
Navneet Bhartia

**Comment by navneet77** [comment]
Hi I don't think I got it to work and eventually set the minimum supported
version to a higher version of android one. Try another android device with
version 4 or above of android

On Tue, May 10, 2016 at 1:44 AM, RupenAnjaria <notifications@github.com>
wrote:

> Is this issue have been resolved? I am facing the same, see the
> description on Stackoverflow at
>
> http://stackoverflow.com/questions/37077311/dropdown-text-issue-in-ionic-cordova-on-android-device
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/1298#issuecomment-217902545>
>



-- 
Navneet Bhartia

**Comment by RupenAnjaria** [comment]
Facing the same on Android 5.0
