### ISSUE TITLE
Tabs should not auto-select

### ISSUE THREAD

**Issue by leefernandes** [driftyco/ionic#1330]
Currently the first ion-tab is auto-selected when inside of a view that has sub-routes when there are no active subviews.

**Comment by tudorgrig** [comment]
Hi,

It looks that deselect is no longer in $ionicTabsDelegate. I'm also trying to disable the auto-select. Can you help me accomplish this?

Regards,
Tudor

**Comment by lakshmis10** [comment]
Even I want to deselect a tab? Did anyone got the solution?

**Comment by jgw96** [comment]
Hey guys! Feel free to hit up our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/) and the people on there will be able to help you with your questions!

**Comment by nebulr** [comment]
You can't use deselect directly. Its pretty lame that they removed that feature from the delegate. However you can access the controller of the instance through $ionicTabsDelegate._instances array. Here is a small directive you can use to unselect all values in a tabs group

`
function generateUUID() {
    var d = new Date().getTime();
    var uuid = 'axxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r = (d + Math.random()*16)%16 | 0;
        d = Math.floor(d/16);
        return (c=='x' ? r : (r&0x3|0x8)).toString(16);
    });
    return uuid;
};
.directive ('ionTabsUnselect', ['$ionicTabsDelegate', '$parse', function ($ionicTabsDelegate, $parse) {
return {
    restrict : 'A',
    scope : true,
    link : function (scope, element, attrs, ctrl) {
      var variable = attrs.ionTabsUnselect;
      scope.uuid = generateUUID();
      element.addClass(scope.uuid);
      scope.$watch (variable, function (value) {
        if (value != null && value == true) {
          var length = $ionicTabsDelegate._instances.length;
          for (var i = 0; i < length; i++) {
            if ($ionicTabsDelegate._instances[i].$element[0].className.indexOf(scope.uuid) > -1) {
              var tab = $ionicTabsDelegate._instances[i].selectedTab();
              $ionicTabsDelegate._instances[i].deselect (tab);
              $parse (variable).assign(scope, 'false');
              break;
            }
          }
        }
      });
    }
  }]);`

`<ion-tabs ion-tabs-unselect="self.unselect">
...
</ion-tabs>`
