### ISSUE TITLE
ionic serve crashing

### ISSUE THREAD

**Issue by kevbaker** [driftyco/ionic#1332]
I'm using `ionic serve` to view my changes locally. It is working, however after making more than a couple changes to a few files, in this case style.css, the `ionic serve` process will crash.

Not a huge deal since I can restart it, but would better if it was staying up.

Versions:
- OSX 10.9.2
- npm 1.3.8
- node 0.10.18

**Comment by samu** [comment]
I'm experiencing the same problem. Here's the error i got: 

`8761 segmentation fault  ionic serve`

I'm on node `v0.12.2`. When i was on node `v0.10.26`, it happened more frequently though.
