### ISSUE TITLE
Slide-box "does-continue" issues

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1353]
Seems that if you have 2 slides in a side-box and have `does-continue="true"`, the slide will not function properly after it's first loop. 

http://codepen.io/mhartington/pen/KiEnp

**Comment by ariesjia** [comment]
same issue

**Comment by angelzhan** [comment]
still reproduce.

**Comment by mhartington** [comment]
@ariesjia and @angelzhan would you be able to provide a codepen of this?

**Comment by wangjianbing925** [comment]
same issue  the last slide is't continue

**Comment by jhoanna** [comment]
The slide continues but the pager doesn't show which page is active.

**Comment by sebrojas14** [comment]
Still presented on 1.1.0...

**Comment by sebrojas14** [comment]
http://codepen.io/anon/pen/WvqYBb works normally, but if I open chrome developer tools, the pager now shows 4 pages instead of 2....In my app, the problem is that ther's 4 slides created

**Comment by sebrojas14** [comment]
Testing on a real device, the problem doesn't show...is extrange

**Comment by amrography** [comment]
It works very well with my app:

<ion-slide-box on-slide-changed="slideChanged(index)" show-pager="false" does-continue="true" slide-interval="2000" ng-if="news.length">

and I update the slide-box too after looong JSONP request using 
$ionicSlideBoxDelegate.update();

**Comment by Ben07** [comment]
@amrography I used your solution,but it doesn't work.;(

**Comment by amrography** [comment]
Check your CSS style .. maybe `ion-slide` position is fixed or something like that.

And `console.log(index)` in slideChanged() function to see if it slide is working or not :+1:

**Comment by Ben07** [comment]
@amrography thanks,I have solved it.your solution is nice.

**Comment by amrography** [comment]
Good to here that :+1:

**Comment by sfwxp945** [comment]
@amrography Thanks,i just add `ng-if="news.length"` and it works!

**Comment by aoxiaoqiang** [comment]
`$ionicSlideBoxDelegate.loop(true);` can solve this issues.

**Comment by aoxiaoqiang** [comment]
Another way is `ng-if='repeat value'`

**Comment by xlkit456852** [comment]
in ionic.js , search "special case if two slides" ,that will tell you while it shows 4 slides when data length is 2

**Comment by made21** [comment]
hi guys , im facing the same issue with 4 slides when i have data length 2 , any solution ???
