### ISSUE TITLE
Apply has-bouncing to other elements

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1367]
Right now, `has-bouncing` is only applied to `ion-content`. This should be a global attribute that could be applied to other elements, such as slide-box or individual slides. 

This way, we could disable the bouncing effect on individual slides or an entire slide.

**Comment by tbindrup** [comment]
Has there been any activity on applying `has-bouncing` to `slide-box`?

**Comment by Tiagojdferreira** [comment]
Tried it today, still doesn't work. Once it is added, it should also be added to the documentation.
http://ionicframework.com/docs/api/directive/ionSlideBox/

**Comment by bymodude** [comment]
This issues should be re-opened, as it was created to add has-bouncing to slide-box but instead it was added to ion-scroll only

**Comment by mhartington** [comment]
Slide-box will be reworked in the future to allow this.

**Comment by seesoe** [comment]
any updates on this?

**Comment by tbindrup** [comment]
@mhartington I made some changes to ionic.bundle.js and got this (has-bouncing on ion-slide-box) to work. Let me know if you're interested; I haven't ever attempted to contribute to a project like this. Cheers!

**Comment by seesoe** [comment]
@tbindrup , do you mind sharing it?

**Comment by tomferreira** [comment]
See #4095
