### ISSUE TITLE
Android 4.2.2 physical device error

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#1377]
When I run my app on physical device I get following error:
Web Console: Uncaught TypeError: Cannot read property 'width' of null at file:///android_asset/www/bower_components/ionic/release/js/ionic.js:5679

**Comment by Jinoooo** [comment]
I see the problem back again, when trying to use keyboard api to close the keyboard in search(data).
* *340677   error    Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined, http://192.168.0.15:8100/lib/ionic/js/ionic.bundle.js, Line: 3995*
* ionic 1.6.4
* keyboard plugin 1.0.4
* android 5.0
* device galaxy 5

Here is my code:
```
	<form ng-submit="search(data)">
		<ion-header-bar class="bar bar-subheader item-input-inset">
			<div class="item-input-wrapper">
				<i class="icon ion-ios7-search placeholder-icon"></i>
				<input type="search" placeholder="enter lastname ..." ng-model='data' autocorrect="off">
				<input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;" />
				<i class="clear-search icon ion-close-circled" ng-click="clearSearch()"></i>
			</div>
			<div class="padding item-input">
				<select ng-model="selected" ng-options="year for year in years"></select>
			</div>
		</ion-header-bar>
	</form>
```
