### ISSUE TITLE
Collection Repeat + Infinite Scroll

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic#1380]
It appears that the <ion-infinite-scroll> spinner is hidden at the top of the page rather than at the bottom of the list when using infinite scroll with a collection repeat. We should modify the collection-repeat logic to consider siblings in its scrolling calculations.

**Comment by pulakb** [comment]
Collection Repeat + Infinite Scroll is working for me in beta 13 but it is not working in beta 14. Why is this so @ajoslin @adamdbradley?

**Comment by jianbo** [comment]
beta14 doesn't work, any hotfi?

**Comment by JWesorick** [comment]
+1

**Comment by agianikas** [comment]
+1

**Comment by Screeze** [comment]
Just tried 1.2, and for me its still not working. When loading the page, it fires loading once, and never again.

        <ion-list>
            <a class="my-item"
               collection-repeat="x in y"
               collection-item-height="240px"
               collection-item-width="200px"
               ng-href="xxx">
                <div class="card">
                    <img ng-src="{{x.b}}" width="100%"><br>
                    <span>
                        {{x.a}} ({{x.b}})
                    </span>
                </div>
            </a>
        </ion-list>
        <ion-infinite-scroll
                icon="ion-loading-c"
                on-infinite="loadMore()"
                distance="500px">
        </ion-infinite-scroll>

Also tried distance="20%" and other values.

**Comment by michel-eu** [comment]
Hey @Screeze, i've faced the same problem in 1.1. 

What happend is @ajoslin fixed this issue adding a `display:block` in the element after collection-repeat (infinte-scroll, in this case), here is the link https://github.com/driftyco/ionic/issues/2376#issuecomment-76751797. 

And i'd changed the css (for layout purposes) like this:

``` css
.collection-repeat-after-container {
	display: inline!important;
}
``` 
 I've just removed this css and the infinite-scroll worked fine in collection repeat.
