### ISSUE TITLE
disable-pointer-events not being removed after transition

### ISSUE THREAD

**Issue by deedubbleyoo** [driftyco/ionic#1383]
We are experiencing a bug:

When automatically transitioning from our login to home page (on successful login), the page elements are un-clickable.

We noticed that the disable-pointer-events class was still applied to the body.
From what I can understand in the code, this class is applied at the start of an animation, and then removed after it.

Given that this behaviour disappears as soon as we remove the animation parameter from the body tag, it leads me to believe that the animation code is not removing the class as intended.

When viewing in a browser, refreshing the page makes elements interactive again.
We have place a temporary fix to manually remove that class from body on stage change success, but obviously would prefer things just to work as intended.

I apologise for not writing a codepen, It's hard to replicate the issue on a code snippet.

**Comment by thetwosents** [comment]
This is still an issue unfortunately and can't find the solution :/

**Comment by gliss** [comment]
I too am having this issue. This occurs when I have a popover open which has a link to a modal. I fixed it by adding a timeout of the model.open.

`function showSwitchUserModal(e) {
			e.preventDefault();
			vm.staffPopover.hide();
			$timeout(function(){
				vm.switchUserModal.show(e);
			}, 100);
		}`
