### ISSUE TITLE
Modal show() bug?

### ISSUE THREAD

**Issue by LeleDev** [driftyco/ionic#1395]
In my app, I want that a modal shows up immediatly. But, if I put this line in the MainCtrl:

``` javascript
$scope.modal.show();
```

I get the following error: TypeError: Cannot read property 'show' of undefined

The weird thing is that, if I use the following code instead:

``` javascript
 $timeout(function(){
   $scope.modal.show();   
 },0)
```

the modal shows and the command runs without issues. Is this an intended behaviour?

**Comment by pavitardua** [comment]
@mlynch This worked for me. But I tried calling the hide() function in similar fashion doesn't work now.

$ionicModal.fromTemplateUrl('modal.html', modalOptions).then(function(modal) {
  modal.hide();
});

What could be the issue?
