### ISSUE TITLE
Disable back-button on modals

### ISSUE THREAD

**Issue by LeleDev** [driftyco/ionic#1397]
I'm using $ionicModal to show a sign in page

This should trap the user in the modal itself, but the back button allow him to "escape" easily from that view. Could you please add a modal property to prevent the modal from being hidden when the user hits the back button on android?

Thank you in advance!

**Comment by boltex** [comment]
Like @LeleDev  said, sometimes the back button stays disabled for the whole application even if the modal was hiden ! (not 100% of the time I cannot find a way to reproduce reliably but it does happen!)
