### ISSUE TITLE
Blue border on input box in Android 4.0.4

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic#1400]
There appears a blue border on Android 4.0.4 devices 
in ionic v1.0.0-beta.5b

![cropped](https://cloud.githubusercontent.com/assets/4522965/2982974/193ded7e-dc1c-11e3-8f0e-95754a0e6b0b.png)

**Comment by RajMondaz** [comment]
I am also facing the same issue on android device  4.04

how to fix it
