### ISSUE TITLE
ng-click on ion-item in ion-list

### ISSUE THREAD

**Issue by dovidkopel** [driftyco/ionic#1410]
I have and `ion-list` with `ion-item`'s in it. Each `ion-item` has a `ng-click`...the `ng-click` event handler is never firing. Please note this is inside of a `ion-side-menu-content`.

For testing's sake, I also put a regular `button` in the same controller, with an `ng-click` and it is not working as well. I disabled `drag-content` thinking it may have something to do with the side-menus. I will work on getting you an HTML only model as it is in an app.

I recently updated from the first version of alpha to beta-5b. I am running Kit Kat.

**Comment by rennen** [comment]
I followed the link.
It seems like the defect is not related to what's described above..

**Comment by Chitrank-Dixit** [comment]
I am also facing the ng-click issue in ion-item as a child element in ion-list. ng-show/ng-hide is working fine, but only ng-click is not working.

**Comment by fer** [comment]
I am using 1.0.0-rc.4 and I am also experiencing this issue with ng-click.

**Comment by pedrohml** [comment]
I am using this workaround:

```html
<ion-item ng-href="{{ logOut() || '' }}">
Logout
</ion-item>
```

**Comment by queejie** [comment]
@fer Thank you for that!  I am using the redactor editor in a list and I could not get it to receive a click until I used a div with class of list as you did.
