### ISSUE TITLE
Scroll is not reaching the end of my view

### ISSUE THREAD

**Issue by luiscruz** [driftyco/ionic#1411]
When my view has a content bigger than the size of the view, the scroll does not reach the end of the content. Please check the code pen below:

http://codepen.io/luiscruz/full/wkzFa

I am using Safari version 7.0.3 (9537.75.14). I've just it using Chrome and it works fine. However, this issue is also happening on my iPhone 5 with iOS 7.1.1.

Regards,
Luís

**Comment by jeshan** [comment]
right. as @willadamskeane said, just now I've observed this issue in my own situation as well.

**Comment by BassamHabash** [comment]
hello @ajoslin

This problem also happen with me ,   there are any solution.
Thanks.
