### ISSUE TITLE
slide-box vertical slide

### ISSUE THREAD

**Issue by TakkuzOld** [driftyco/ionic#1415]
By now slide-box only works horizontally.  
It would be useful if it could slide also vertically by adding an attribute.

**Comment by rajeshwarpatlolla** [comment]
Have a look at this link https://github.com/nolimits4web/Swiper
I tried and it's working fine.

**Comment by drastick** [comment]
+1

**Comment by bastengao** [comment]
+1

**Comment by josh256** [comment]
+1

**Comment by mlynch** [comment]
We just added swiped support so if it works with swiped it'll work with Ionic. Use the new <ion-slides> and <ion-slide-page> components

**Comment by egvrcn** [comment]
+1

**Comment by wal-nadeem** [comment]
+1
