### ISSUE TITLE
Disabling gesture to open side-menu on a per view basis

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#1416]
It is currently possible to disable the gesture to open the sidemenu by setting:

`<ion-pane ion-side-menu-content drag-content="false">` 

It would be really nice if there were some mechanism to set this functionality per view. Possibly by setting a variable through a controller?

Forum link for further discussion:
http://forum.ionicframework.com/t/how-to-disable-drag-in-side-menu/208

**Comment by F1LT3R** [comment]
This did not work for me until I used `afterEnter` and `beforeLeave` events:

```javascript
  $scope.$on('$ionicView.afterEnter', () => {
    // Hide the tabs for this full-screen view
    $ionicTabsDelegate.showBar(false)

    // Don't allow the page to be dragged around
    $ionicSideMenuDelegate.canDragContent(false)
  })

  // enable side menu drag before moving to next view
  $scope.$on('$ionicView.beforeLeave', () => {
    $ionicSideMenuDelegate.canDragContent(true)
  })
```
