### ISSUE TITLE
Side menu drag-content=false should still allow drag of main content to hide the menu

### ISSUE THREAD

**Issue by pennersr** [driftyco/ionic#1419]
Currently, if a side-menu has drag-content set to true, it allows you to drag the main content to reveal and hide the side menu. However, if drag-content is set to false, the main content cannot be dragged at all. IMHO, most use cases would be far better off served if drag-content=false would imply that the user would still be able drag the main content to _hide_ the side menu.

I am even wondering if there is ever a need to disable hiding the side menu via dragging of the main content. So, instead of making an optional third variant (drag-to-hide) I would consider removing the current behavior.

**Comment by nskoro** [comment]
When I set drag-content=false I can still drag the page to show the side menu. How do I disable this behavior?
