### ISSUE TITLE
ionic start should create project with specified package name and app name

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic#1424]
ionic is getting much better day by day but there is one thing i don't like about ionic is way it creates new project.

``` shell
$ ionic start test.app tabs
```

the above command creates ionic project with tabs with following config.xml

``` xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ionicframework.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        An Ionic Framework and Cordova project.
    </description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">
      Ionic Framework Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="fullscreen" value="true" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />

    <!-- Don't store local date in an iCloud backup. Turn this to "cloud" to enable storage 
         to be sent to iCloud. Note: enabling this could result in Apple rejecting your app.
    -->
    <preference name="BackupWebStorage" value="none" />

    <feature name="StatusBar">
      <param name="ios-package" value="CDVStatusBar" onload="true" />
    </feature>
</widget>

```

According to my knowledge which creates

App name : HelloCordova
package : com.ionicframework.starter

i think ionic start should be more like this  ,which feels more like cordova

``` shell
$ ionic start AppName com.package.name AppFolderName ionic-tamplate[tab|blank|sidemenu]
```

What do you think ??

ionic start has one interesting concept of creating projects based on templates like tabs,sidemenu 

I have a suggestion why not create a github repo for creating and submitting community generated ionic templates which can be used by everyone just like tabs, sidemenus 

Thanks

**Comment by mr5z** [comment]
@azizimusa Thank you for the details :D

**Comment by mehmetkose** [comment]
sounds good. +1 from me too.

**Comment by abdulwahid1st** [comment]
The doc's right here
http://ionicframework.com/docs/cli/start.html

**Comment by shivsuthanmhub** [comment]
Once you create the project just go and build your project again like ...
ionic build ios 
After that its provide you with whats you created (project name) already....

**Comment by sylfree9999** [comment]
But how can I safely change the package name on the project I already created? I have tried to change the widget it in config.xml, but the build was failed. Any ideas?

**Comment by webdevinci** [comment]
I am using these new flags, as I too have the 'HelloCordova' issue; changing config.xml isn't enough to change that name throughout the project. I used:
$ ionic start trackerIos -a "DisplayTracks" -i com.displaytracks.iosTracker --io-app-id com.displaytracks.iosTracker

...and I am still getting the 'HelloCordova.xcode.proj' and 'HelloCordva' directory in /trackerIos/platforms/ios . It changes the root config.xml, but not the one in the ios dir. I have to remove the ios platform and re-add it and then it picks up correctly. (I might be an anomaly, just getting started)

**Comment by donaldking** [comment]
Same here. Still getting HelloCordova!

**Comment by webdevinci** [comment]
Issue solved, read up on ionic's other git thread, dude added some connivance params 
$ ionic start projectName -a "Project Name" -i com.displaytracks.iosTracker --io-app-id com.projectName
//Now change your root config.xml, remove ios and re-add it
$ ionic removePlatform ios //if it exists
$ ionic addPlatform ios

**Comment by atul-athawale** [comment]
$ ionic removePlatform ios //if it exists
$ ionic addPlatform ios

Worked for me...!!!

**Comment by julienazerty** [comment]
$ ionic start projectName -a "Project Name" -i com.displaytracks.iosTracker --io-app-id com.projectName
//Now change your root config.xml, remove ios and re-add it
$ ionic removePlatform ios //if it exists
$ ionic addPlatform ios

Not working for me, still have "android-debug.apk" as package name after $ionic build android.
In config.xml i have the expected value in Widget id's but "ionic build android" don't take this value for package naming. 

Anyone has an idea ?
