### ISSUE TITLE
Incorrect Ionicon sizing with Ion-item

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1427]
From the forum:
http://forum.ionicframework.com/t/ion-side-menu-icons-very-small-if-using-ion-item-element-list/4392

Confirmed here:
http://codepen.io/mhartington/pen/IpsLl

Seems because all the content is getting wrapped with in an `a` with a class of `item-content`, font-sizing isn't being applied.

**Comment by xereda** [comment]
It worked perfectly. Thank you.
