### ISSUE TITLE
ion-side-menu events.

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#1437]
ion-content has two events: on-scroll and on-scroll-complete
is it possible to add those kind of events to ion-side-menu but concerning opening and closing menu? on-toggle and on-toggle-complete?

**Comment by Alexniver** [comment]
Great solution! Works for me!

**Comment by valix85** [comment]
This work fine for enable or disable option in menu
.controller('AppCtrl', function($scope, $ionicPlatform, $ionicSideMenuDelegate, login) {
//.....
$ionicPlatform.ready(function() {
    //monitorare se sono loggato per mostrare nel menu la voce scollegati
    $scope.$watch(function() { return $ionicSideMenuDelegate.isOpen(); }, function(value) { 
      console.log('View menu Entered, value: '+value);    
      $scope.loggato=login.getValue("loggato"); //for me return true or false
      $scope.apply;
    });
  });
  $scope.loggato=login.getValue("loggato"); //for me return true or false
//.......
}) //end controller

in template menu use
<div ng-if="loggato">.....</div>
