### ISSUE TITLE
Fires click when stop scroll with tap/click

### ISSUE THREAD

**Issue by juliancesar** [driftyco/ionic#1438]
The default behavior is only stop scroll, but in ionic the scroll stops and fires the click.
Someone else with same problem?

iOS 7.1.1
iPhone 5
Ionic 1.0.0-beta.b5

**Comment by adamdbradley** [comment]
related: https://github.com/driftyco/ionic/issues/2665

**Comment by charlesbedrosian** [comment]
I was having this issue still with ionic 1.7.16 when using an ion-list.  The fix was to put `has-bouncing="false"` on the ion-content tag.

Credit to http://stackoverflow.com/a/29911064/728379

**Comment by Shadowstep33** [comment]
This is actually still happening for me with ionic 1.7.7

I am using a directive for the scrolling with something that looks like this:

```
    <ion-list class="item-list {{ theme + '-theme' }}" scroll="true">
		<ion-item class="item calendar-list-item item-remove-animate col-xs-12 no-padding {{event.type}}" ng-repeat="(k,event) in tasks track by $index | orderObjectByTwoProps: 'plan_item':'time'" ng-if="(!filter || filter.indexOf(event.type) >= 0)" on-tap="toggleTask(event)">
			
			<div class="handler col-xs-12 no-padding" ng-if="event.type == 'workout'" ui-sref="app.workouts({ id: {{event.id}}, fromCalendar: true, eventID: {{ event.eventID }}, calendarDay: {{ k }} })">

				<div class="col-xs-8 blue-border-right" style="height: 100%;">
					<div class="col-xs-2" on-tap="logWorkout(event)" ion-stop-event="click">
						<div ng-class="(event.completed ? 'complete' : '') + ' complete-block ' + event.type"></div>
					</div>
					<div class="col-xs-10">
						<h2 class="light">{{ event.title }}</h2>
						<span class=" sublabel light pale-blue">{{ event.description }}</span>
					</div>
				</div>
				<div class="col-xs-4">
					<h1 class="light hours">--</h1>
				</div>
				
				<ion-option-button class="button-assertive icon-left ion-trash-b blue-bg" on-tap="$ionicListDelegate.closeOptionButtons();removeFromSchedule(event)"></ion-option-button>
				
			</div>
...
```

**Comment by chrisyuyangshen** [comment]
This issue still exists on my app.

**Comment by EmreErdogan** [comment]
@juliancesar your solution works well. 
@insectean your replacement of `new Date().getTime()` with `Date.now()` improves the performances.

Thank you all.

I wonder if any of you guys or other fellows can convert this solution into a directive, so that we don't need anymore to copy paste the calculation logic and the click event handler into every controller where this solution is going to be used. Also the view may become cleaner if `on-scroll` and `ng-click` directive calls are removed. To sum up, what I am looking for is a single directive that can be attached to `ion-content` and wraps up all of those logic and handles clicks while scrolling. 

For example:

`<ion-content prevent-click-on-scroll>`

where `prevent-click-on-scroll` is the directive I am looking for.

**Comment by cweidinger** [comment]
+1 This issue still exists for me on ios.

**Comment by EmreErdogan** [comment]
OK. I modified the code of @juliancesar and @insectean, then moved it to a service called `ScrollClickHandler`. I tested it in my project and it works fine. Here's the implementation:

```
.service("ScrollClickHandler", function(){

  var lastScrolling = Date.now();

  var scrollList = function(){
    lastScrolling = Date.now();
  };

  var canClickInList = function() {
    var diff = Date.now() - lastScrolling;
    if (diff > 200) {
      return true;
    }
    return false;
  };

  this.getScrollHandler = function(){
    return scrollList;
  };

  this.getClickHandler = function(callbackFunc){
    return function(clickEvent){
      if(!canClickInList()){
        clickEvent.preventDefault();
        clickEvent.stopPropagation();
        console.log('cannot click');
      } else {
        if(typeof callbackFunc === 'function'){
          callbackFunc.apply(this, arguments);
        }
        console.log('can click');
      }
    };
  };

})
```

Now, after injecting `ScrollClickHandler` into your controller as a dependency you can use it like this. 

In your controller:

```
.controller('MyController', ['$scope', 'ScrollClickHandler', function($scope, ScrollClickHandler){
  $scope.scrollHandler = ScrollClickHandler.getScrollHandler();
  $scope.clickHandler = ScrollClickHandler.getClickHandler();

  // other stuff
}]);
```

And in your ion-content and ion-list:

```
<ion-content on-scroll="scrollHandler()">
    <ion-list>
        <ion-item ng-repeat="thing in things" ng-click="clickHandler($event)"> ... </ion-item>
    </ion-list>
</ion-content>
```

That's it! 

**Note:** Optionally, you can pass a callback function to the `getClickHandler` method to be called when the user clicks on an item. Example:

```
$scope.clickHandler = ScrollClickHandler.getClickHandler(function(e, idx){
    console.log("User has clicked the item at index: " + idx);
});
```

And

`<ion-item ng-repeat="thing in things" ng-click="clickHandler($event, $index)"> ... </ion-item>`
