### ISSUE TITLE
Side menu overlaying rather than pushing center content

### ISSUE THREAD

**Issue by jgoux** [driftyco/ionic#1443]
I'd love to see this feature added to ionic : http://forum.ionicframework.com/t/side-menu-overlaying-rather-than-pushing-center-content/4361
You can find an example of it in the "mail" app on Android. On tap, the side menu slide above the main content, and the main content becomes darker.

**Comment by ram-you** [comment]
+1

**Comment by sonnylazuardi** [comment]
+1

**Comment by kevjose** [comment]
+1 !! Would be an amazing feature

**Comment by pradhnsgithub** [comment]
Now I am searching for it to implement in my app. Is it impossible in ionic? Please suggest something.

**Comment by avidenic** [comment]
I am amazed there is so little interest in this!

**Comment by akz92** [comment]
+1

**Comment by artkoenig** [comment]
+1

**Comment by jvverde** [comment]
+1

**Comment by mhartington** [comment]
We won't be adding this to V1, but we have it in v2.

**Comment by iddqd1** [comment]
+1

**Comment by pawangjain** [comment]
+2

**Comment by felixarntz** [comment]
+1

**Comment by mlynch** [comment]
This is coming! Thanks everyone :)

**Comment by zfoltin** [comment]
+1

**Comment by shoespray** [comment]
+1

**Comment by pawangjain** [comment]
Hi all

This alternative can help

http://codepen.io/brandyshea/pen/RPoQmO

**Comment by bill-mybiz** [comment]
+1

**Comment by aliblackwell** [comment]
+1

**Comment by devner007** [comment]
+1
