### ISSUE TITLE
Ionic and RequireJS 

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#1448]
Require.js doesn't work with Ionic.

Possible causes:
- Ionic tap handler don't initialize correctly when async loading Ionic
- Some other things don't initialize correctly

This is not a priority for us to fix.

However, contributions are welcome if anyone can find the root cause and fix it simply.  

If you open a pull request about require.js, just reference this issue.

**Comment by samuelcastro** [comment]
Ionic + Webpack: https://github.com/AlexYankee/ionic-webpack-starter
