### ISSUE TITLE
No click event on icon

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#1459]
If I add only icon it doesn't recieve click events on android 4.1:
`<i class="ion-help-circled" ng-click="alert('none');"></i>`
or
`<a ng-click="alert('none');"><i class="ion-help-circled"></i></a>`

This recieves event on text only:
`<a ng-click="alert('none');"><i class="ion-help-circled"></i> Text</a>`

**Comment by zhuhu** [comment]
How about using "on-tap"?

**Comment by tannerlinsley** [comment]
I can confirm this while testing in Chrome.  Even when wrapping with other elements, the parent elements will not fire.

**Comment by FdezRomero** [comment]
I'm having this issue as well. Are you guys doing an `e.preventDefault()` on `<i>` targets?

**Comment by aiouy** [comment]
I was able to get this working wrapping the icon with a <span> and the on-tap zhuhu mentioned earlier:

`<span on-tap="clearSearch()"><i class="icon ion-close"></i></span>`

**Comment by cosnofski** [comment]
I'd like to put a big green checkmark next to the comment from FdezRomero. Thanks!

**Comment by ladmerc** [comment]
Got same issue today. Changing event handler to 'on-tap' worked.

**Comment by Emmarex** [comment]
'on-tap' works. Kudos

**Comment by miparnisari** [comment]
`on-tap` did not work for me. Had to use `ng-click` for it to work on Android 4.1.2.

`<a ng-click="substract()"><i class="icon ion-ios-minus"></i></a>`

**Comment by jackvial** [comment]
@FdezRomero Changing the label element to a div fixed it for me. ty
