### ISSUE TITLE
ion-item does not swipe when show-delete = true

### ISSUE THREAD

**Issue by Dbms** [driftyco/ionic#1466]
Steps - 

1. Create an ion-list.
2. Have ion-delete-button and ion-option-button in the ion-item
3. Set show-delete = true on the ion-list
4. Try to swipe the list so as to show the ion-option-button. You can't.

**Comment by teamrad** [comment]
Any updates? I am still facing this issue..

**Comment by ajoslin** [comment]
This isn't fixable with the current implementation.

Deferring this until the next iteration of ListView.

**Comment by perrygovier** [comment]
This is going to be part of v2, but I don't think it will make it in to v1
