### ISSUE TITLE
Slide box inside modal does not display correctly on first load

### ISSUE THREAD

**Issue by pattyok** [driftyco/ionic#1473]
I am running a series of slides with ng-repeat inside of a modal window. When the modal first loads the slide box width is set to zero width and so the display is totally wonky, refresh the view and it is happy.  I was able to reproduce in codepen here:

http://codepen.io/pattyok/pen/bncwq

**Comment by comapedrosa** [comment]
Hi @perrygovier I know this issue is already closed but I'm still experiencing the issue when opening the modal for the first time.
Actually the first time no images are displayed and for the rest of the times there's no problem...
Thx
