### ISSUE TITLE
Ion tabs on android does not have the same width

### ISSUE THREAD

**Issue by yujinlim** [driftyco/ionic#1479]
Hi, 

I found the tabs is not align on the same width, screen shot as attached. 

As you can see the distance of 2nd tab and the last tab, is bigger than the 1st and 2nd. 

I have checked using weinre, that the last tab width is taking a maximum of 150px. 

Please advice. 

My code

``` html
  <ion-tabs class="tabs-icon-only" ng-class="{'no-tabs': !poll.needsTabs}">
    <ion-tab title="Answers" icon-on="ion-ios7-help" icon-off="ion-ios7-help-outline">
 </ion-tab>
 <ion-tab title="Detailed results" icon-on="ion-ios7-glasses" icon-off="ion-ios7-glasses-outline">
</ion-tab>
  </ion-tabs>
```

![screenshot_2014-05-23-16-32-09](https://cloud.githubusercontent.com/assets/1311231/3064546/3b255028-e255-11e3-9c0c-c3fef388e94f.png)

**Comment by jonathangijsen** [comment]
The issue is still there on android 4.0 and 4.1 (tested).
On 4.4 and 5.0 it works.
