### ISSUE TITLE
Reordering nested list

### ISSUE THREAD

**Issue by cgarnier** [driftyco/ionic#1480]
When you put a ion-list in an ion-item (which is in a other list). The reorodoring have a bad behavior. The most inner items position is calculated with the main list, so the dragging item have a wrong position.

**Comment by Eram90** [comment]
Hi, does this problem have working solution ? I have the same problem, but I can't fix it...

**Comment by cgarnier** [comment]
It s a beta6 issue. It doesnt been fixed yet ?

**Comment by Eram90** [comment]
No, I still have that problem with ionic 1.7.14.

**Comment by cgarnier** [comment]
@perrygovier may be you could re open this issue.

**Comment by Kinzi** [comment]
@perrygovier I'm also interested in this - could you reopen?

**Comment by radvansky-tomas** [comment]
Same here, I have troubles to reoder nested list
