### ISSUE TITLE
ng-model and ng-change not worked when element's input type is number 

### ISSUE THREAD

**Issue by offbye** [driftyco/ionic#1497]
input type="text" name="bankCardNo" ng-model="bankData.bankCardNo"
                           required="true" placeholder="Bank Card" maxlength="20" ng-change="bankCardChange()" 

this code  is worked good, but when I change to <input type="number" ... ,  a error will happen:
 TypeError: undefined is not a function
    at Scope.$scope.bankCardChange 

Maybe it is a angularJs bug.

**Comment by arunmdavid** [comment]
I am getting the same issue with 'email' and 'tel' also. 
Ionic: 1.0.0-beta.14 Angular: 1.3.6

**Comment by MadhaviBezawada** [comment]
ng-change will work on anything whether it is "number" or "text". But make sure the entered value is valid one after all your validations. Without any validation check if you still have doubts.
