### ISSUE TITLE
Slidebox doesn't continue anymore when it reaches end (mix of static slides and ng-repeat slides)

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#1501]
When using a an ng-repeat for ion-slides, the slidebox won't continue sliding when it reaches the last slide. It just stops when it reaches the end.

Tried with setting `does-continue=true` explicitly and without. 

Tested on 1.0.0 beta 6.

**Comment by tristobal** [comment]
As workaround...

JS

        <ion-slide-box
            does-continue="true"
            auto-play="true"
            slide-interval="{{interval}}"
            show-pager="true"
            pager-click="changeSlide(index)"
            on-slide-changed="slideHasChanged(index)">
            <ion-slide ng-repeat="imagen in carrusel">
                <img ng-src="{{imagen.img}}" height="auto" width="100%">
            </ion-slide>
        </ion-slide-box>

CTRL

    $scope.interval = 2000;

    $scope.slideHasChanged = function(index) {
        $scope.slideIndex = index;
        if ( ($ionicSlideBoxDelegate.count() -1 ) == index ) {
            $timeout(function(){
                $ionicSlideBoxDelegate.slide(0);
            },$scope.interval);
        }
    };

**Comment by Tiagojdferreira** [comment]
Was this ever fixed or do we still need the work around?

**Comment by funnyjoker** [comment]
has this bug been fixed? I have the similar experience, if use the method written by @tristobal  , it seems so weird ...

**Comment by jackyon** [comment]
hm... issue still exist...

**Comment by jackyon** [comment]
@tristobal solution also not the perfect one, it happened some bugs when switch some pages. (for example: stop auto play & slides increase)

**Comment by funnyjoker** [comment]
it seemed I had fixed this problem like this : ng-repeat="item in items track by $index"

**Comment by systembugtj** [comment]
I try the track by, ng-if and $timeou to udpate, nothing works for me. I can still repro.

**Comment by systembugtj** [comment]
Issue claim to be closed. But still repro on 1.0.0 latest

**Comment by EdwardsBean** [comment]
issue still exist.version 1.0.1

**Comment by guyanbiao** [comment]
https://github.com/driftyco/ionic/blob/6c9bc15b2996ae9183624c84a2709fd33f80d20b/js/views/sliderView.js#L55

It's because first time the Slider initialized "slides.length" is equal to 0, the "options.continuous" is set to false, when "IonSlideBoxDelegate.update() "  called, "options.continuous" is not retrieved from the settings but keep to be false.

change

```javascript
      if (slides.length < 2) options.continuous = false;
```
to 

```javascript
      if (slides.length < 2) {
        options.initialContinuous = options.continuous;
        options.continuous = false;
      } else if (options.initialContinuous) {
        //if original  continuous is true, recover it
        options.continuous = options.initialContinuous;
      }
```

solve the problem

**Comment by EdwardsBean** [comment]
@guyanbiao thx,works great

**Comment by edailton** [comment]
@guyanbiao thanks, works!

**Comment by felixschul** [comment]
@guyanbiao Works great! Why did you not open this as pull-request so it can be included in the master branch? It seems the bug still persists in the latest version of ionic 1 and I think it is rather ugly to change this in the ionic bundle. @ajoslin Would you include this in ionic 1?

**Comment by ntrp** [comment]
Another workaround is to get the `$ionicSlideBoxDelegate` and call the method `loop(true)`. I am using Ionic 1.3.1.
