### ISSUE TITLE
Ion-nav-view name can't be interpolated

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1503]
Trying to interpolate the name on `ion-nav-view` isn't possible. This should be allowed for dynamic tabs.

http://codepen.io/mhartington/pen/GxAys

**Comment by TheCodeDestroyer** [comment]
@perrygovier I don't think it's anyone's intention to change tab names dynamically...
You could enforce the use of one-time binding... `{{ ::viewName }}`
Or am I missing something?

**Comment by alexweber** [comment]
@TheCodeDestroyer would you mind explaining the one-time binding thing?  I ran into this same issue where I was loading items and generating dynamic menus according to user roles... this actually works fine using the side menu nav, it's just the tabs that don't work.  It's easy enough to work around, just wondering about it is all :)

**Comment by TheCodeDestroyer** [comment]
@alexweber You can't solve this issue with one time binding "yet" as its still an expression.
The directive takes that param as static so it won't reolve it.
But if you want to learn more about one-time-binding you can read about it [here](https://docs.angularjs.org/guide/expression#one-time-binding)

**Comment by alexweber** [comment]
@TheCodeDestroyer thanks!!

**Comment by ace-han** [comment]
I've come across this problem these days. I think it's a general situation for menu generation from server(say db...). 

I have to do it with `ui-router-extras`.`futureState` and an html page generation automatically to accomplish a dynamic `tabs menus` for the time being. 
It's a little complicated and painful...

Is there a schedule implementing this feature?

**Comment by cbacko01** [comment]
Is it correct that, without this feature, it's impossible to dynamically generate ionic nav views? If so, that's really disappointing.

**Comment by mhartington** [comment]
@cbacko01 the original issue was pointing to that UI-router won't dynamically generate a state for each nav-view you want. 

In my original example, I was attempting to dynamically create a state after UI-router had already established states. Not 100% possible.

UI-router-extras could help, but it's really something that is at ionic's fault. It's a limitation of UI-router.

**Comment by cbacko01** [comment]
Thanks for clarifying. I'm interested in defining states globally and iterating through that list to generate all the necessary states, tab buttons, etc, which I've using with the vanilla UI Router and unnamed views. I guess I don't see what the complication is with doing similar in Ionic. If this really is a new issue, I'll open one up.

**Comment by mansimransingh** [comment]
So I have a decent solution around this problem I think...
I build the html string in the controller in a loop, something like

```
var html = "<ion-tabs>";
for(var t in tabs){
html += '<ion-tab ng-href="'+tabs[t].url+'"><ion-nav-view name="'+tabs[t].viewName+'"></ion-nav-view></ion-tab>';
}
html += "</ion-tabs>";
$scope.html = html;
```

Then add it to template and compile with a directive:

`<div bind-html-compile="html"></div>`

```
app.directive('bindHtmlCompile', ['$compile', function ($compile) {
  return {
    restrict: 'A',
    link: function (scope, element, attrs) {
      scope.$watch(function () {
        return scope.$eval(attrs.bindHtmlCompile);
      }, function (value) {
        // Incase value is a TrustedValueHolderType, sometimes it
        // needs to be explicitly called into a string in order to
        // get the HTML string.
        element.html(value && value.toString());
        // If scope is provided use it, otherwise use parent scope
        var compileScope = scope;
        if (attrs.bindHtmlScope) {
          compileScope = scope.$eval(attrs.bindHtmlScope);
        }
        $compile(element.contents())(compileScope);
      });
    }
  };
}]);
```

Works as expected and so far, haven't run into any issues with it.

**Comment by alexweber** [comment]
@mansimransingh That's a really creative and efficient workaround, I love it, thanks for sharing! 👍

**Comment by srinathvsp** [comment]
That's a really creative and efficient workaround, I love it, thanks for sharing!
