### ISSUE TITLE
scroll effects and animations

### ISSUE THREAD

**Issue by pbrain19** [driftyco/ionic#1510]
Was wondering if any plans to make hooks so that we can do an animation for lists like these ?
http://lab.hakim.se/scroll-effects/

I would think we ca add an attribute like ng-offscreen that would hook into an animate so  we can make transition we do normally in ng-repeat?

**Comment by michahell** [comment]
@pbrain19 Did your friend ever complete anything? would love to know if he did, that would make my app look a lot smoother!
