### ISSUE TITLE
When tap on ionicPopup, would bring up iOS keyboard if there is input behind the popup

### ISSUE THREAD

**Issue by yxztj** [driftyco/ionic#1536]
Tested on iOS7 Safari
http://codepen.io/anon/pen/fLiou

Expected behavior: Tap on ionicPopup wouldn't affect anything else on the page.

Actual behavior: Tap on ionicPopup would bring up keyboard if there is an input field behind the popup. The input looks like being focused, but there is no cursor in it. Can't input anything unless tap the input again.

**Comment by jayaj12** [comment]
I am getting this issue in IOS 9. 
Tap on ionicPopup datepicker and select a date , would bring up dropdown if there is an <select> option dropdown  behind the selected date.

**Comment by jamesdixon** [comment]
@adamdbradley I can confirm that this is still an issue. I'm seeing this on iOS 10.3, iPhone 7 plus, and Ionic 1.3.0.

In my case, it's a a date input behind the popup and it's triggered if it happens to behind the button that's tapped on the popup.

**Comment by s3c4** [comment]
This is not fixed. 

iPhone 6
iOS 11.0.3
ionic 3.19.0

My problem is when I use ion-select and I tap OK button if I have an input/textarea/ another type of input underneath is automatically focused and open the keyboard.

**Comment by mstar0125** [comment]
I can still face same issue
iPhone 8 Plus
iOS 11.2
Ionic 2.2.2

Please provide me the solid resolution.
