### ISSUE TITLE
ionic getting-started   out of date  and Ionic CLI

### ISSUE THREAD

**Issue by desenmeng** [driftyco/ionic#1540]
After I installed ionic,I started a project by

```
ionic start myApp2 sidemenu
```

The app was inited by https://github.com/driftyco/ionic-app-base/archive/master.zip 

I can't find the sidemenu project.

And When I cd myApp2, I found 

```
ionic-app-base-master ionic.project
```

![snip20140601_1](https://cloud.githubusercontent.com/assets/1209159/3140917/219bdff6-e94d-11e3-8b54-630fa18e1bb3.png)

**Comment by rrcobb** [comment]
I ran into this same issue, running Yosemite 10.10.2.   I had been messing around with the yeoman ionic generator, and when I tried the regular ionic start myapp, it built an app to ionic-base-app-master inside my named folder. 

Ran a global npm update, and it began to work as documented. Weird bug, glad someone else had seen it.
