### ISSUE TITLE
Media queries with collection repeat

### ISSUE THREAD

**Issue by doorman02** [driftyco/ionic#1547]
Is there a recommended way to handle list with collection repeat items in a responsive design with media queries? E.g. if I want to show two or more items in a row instead of 1 item when the phone is in landscape vs portrait the item width needs to be changed. 

Thanks!

**Comment by CatchSandeepVaid** [comment]
Hi,
I am having the same problem. 
@perrygovier - First example of your  link doesnt determine the height. Moreover we want responsive design using media queries & not through javascript. 

Any Solution ??
