### ISSUE TITLE
ng-disabled not working on input type=select on iOS

### ISSUE THREAD

**Issue by marcusanzalone** [driftyco/ionic#1549]
Say you have series of cascaded selects. 

select 1
select 2
select 3
select 4

where selecting an item in 1 triggers a set of options to be used for select 2. Select 2 has an ng-disabled="!selectableItems2", so is not enabled until you select an item in 1 and 'selectableItems2' is assigned a value.  Similar with select 3 being based off of selecting an item in select 2. 

On web (safari and chrome) and on android (4.4 was tested), selects 2 (and so 3 and 4 as well) is disabled until a selection is made in select 1. However, in iOS (6 and 7 tested), even when a list of items is not available and should not accept taps, it still accepts the tap and brings up the picker widget with the default "select an item" as the only item.

 A fiddle that gives an anguar.js example of this type of cascading selects is:

http://jsfiddle.net/annavester/Zd6uX/

**Comment by jsanta** [comment]
Perhaps a little to late, but what seems to work is adding a CSS style:
`select[disabled] { pointer-events: none; }`

By the way, disabled options inside a select don't work either. A workaround may be using optiongroups.
