### ISSUE TITLE
$ionicPopup not handling enter press

### ISSUE THREAD

**Issue by Morriz** [driftyco/ionic#1556]
Wouldn't it be expected to do an onTap on the default button onEnter?

**Comment by gtramontina** [comment]
Hey there... I'm facing a similar (or perhaps the same) issue. We have a regular login form that, if login fails, an ionic alert shows up saying `sorry can't login`, but I can't use the `enter` key to dismiss it.

Found this thread: http://forum.ionicframework.com/t/ionic-popup-autofocus-on-button/18884

**Comment by apatton** [comment]
Still noticing this same issue.  

Not only does `enter` not dismiss the popup, it keeps focus on an input outside the popup.  So for us when the user presses `enter` they end up resubmitting the previous form... which triggers another popup :disappointed:.
