### ISSUE TITLE
Cloned text inputs not working

### ISSUE THREAD

**Issue by bluehallu** [driftyco/ionic#1559]
This didn't happen before I installed the Keyboard plugin. I've now come to believe this is a bug in Ionic, I'm using beta 6, the bug appears everywhere I've tested: iOS 7, Android 4.4 and Android 2.3. Because this only happens when the keyboard appears, I can't reproduce it on codepen. Inside my main ion-nav-view this template is being loaded:

```
<ion-header-bar class="bar bar-header bar-balanced">
  <h1 class="title">Register</h1>
</ion-header-bar>
<ion-content class="has-header">
  <div class="logo"></div>
  <label class="item item-input">
    <input ng-model="email" type="email" placeholder="Email">
  </label>
  <div class="padding">
    <button ng-click="register(email)" class="button button-block button-positive">Register</button>
  </div>
</ion-content>
```

What happens is that 90% of the times, as soon as the input is focused, the keyboard comes up but nothing that you type appears on the input, until you tap anywhere on the screen. Then what you wrote appears but typing further produces the same initial effect. I dove a bit into the framework code to realise these two methods: cloneFocusedInput and removeClonedInputs. 

From some discussions on the forum they seem to clone the input and replace it with a static readonly input to avoid some scrolling problems. So, inside the framework they are only called like this:

cloneFocusedInput: 

1) scrollChildIntoView listener, inside a timeout with a variable delay (this is not important apparently, more on this later), called basically right before starting the scroll.

2) touchMove event. No idea when is this supposed to fire, but it doesn't in my case.

removeClonedInputs:

1) touchEnd event. What we see here is that any touch event that is not a scroll will do the call. This is what makes the input show what was typed if I touch anywhere on the screen.

2) scrollingComplete: this is called from so many places in the code I don't really understand it. However it doesn't seem to be called in my case.

Using the Chrome debugger to breakpoint all the possible entry points to any of the  2 functions above (4404,4488,4506 and 4512) plus the timeout call to see if it's a problem with the delay amount (4393) this is what happens (line numbers corresponding to ionic.bundle.js v1.0.0-beta.6):

I tap the input, this triggers, in order: 4506, 4393, 4404. So, they are called in reversed order. First the cloned inputs are tried to be removed but there are none so nothing happens. Then the timeout is set which later clones the input. Nothing else happens. At this point the input is bugged and nothing I type shows for obvious reasons. 

Then, when I tap on the input again, the very same sequence happens again, so even though the input is updated in the process, it's bugged again. If I tap outside the input, the same sequence preceded by 4512 happens. So the cloned inputs are removed twice first, but they are cloned again, so same situation as before.

As you might realise from the lenght of this post, I've spent quite some hours with this. Remember I said thishappens 90% of the time? Well, when debugging, it seems to happen 100% of the times, as I haven't been able to trace the other 10%. 

Hopefully this long boring post will help :)

**Comment by sallycar** [comment]
For those with image issues, try limiting the image height to 100px. That seemed to fix it for me, as hacky as that sounds.

**Comment by israelidanny** [comment]
So how come this is closed while clearly many people still experience this?

**Comment by AlexEmerson** [comment]
Have the same issue on windows phone 8.1. Nothing that you type appears on the input, until you tap anywhere on the screen. I know, wp8 isn't supported yet, but it might be helpful:

 <a href="http://forum.ionicframework.com/t/textarea-and-input-display-problems/4161/29?u=lamorazm">There</a> is the css solution. It suggests hiding cloned input and doesn't hide original one.
As for me, that is not the best option since it exposes issue that cloning input fixes: cursor pointer will flash outside the input sometimes (on scrolling, showing/hiding keyboard). 

What I've come up with is a directive that just listens model changes and update cloned input value accordingly. Here's the code:

```javascript
angular.module('ClonedInputFix')
  .directive('ngModel', function() {
    return {
      restrict: 'A',
      scope: {
        ngModel:'='
      },
      link: function($scope, element, attrs){
        var prevEl;
        $scope.$watch('ngModel',function(){
          prevEl = element.prev();
          if (prevEl.length && prevEl.hasClass('cloned-text-input')) {
            prevEl.val(element.val());
          }
        });
      }
    };
  });
```
