### ISSUE TITLE
Ion-slide-box breaks when removing an item

### ISSUE THREAD

**Issue by emertechie** [driftyco/ionic#1578]
Demo: http://codepen.io/emertechie/pen/tfqsD

See original [forum post](http://forum.ionicframework.com/t/ion-slide-box-breaks-when-removing-an-item-bug/5252) for more details

**Comment by wildmandnd** [comment]
Problem is still there in beta 14. Any workarounds?

**Comment by albumlocker** [comment]
I'm seeing this issue in RC1. Is anyone working on this? Removing slides causes all sorts of weird and unpredictable behavior.

**Comment by CodyMorris** [comment]
I'm still seeing this and have been battling it for about a week now.  Have issues with removing slides, filtering slides, and removing slides with ng-if.  Anyone know if there is a way to override the slidebox's $index without shifting the UI?

**Comment by marco-broccio** [comment]
Same for me.

I have several memory problem on IOS and i'm forced to use ng-if to optimize the DOM.

**Comment by CodyMorris** [comment]
Can someone reopen this?

**Comment by omprakash1989** [comment]
Is there any fix of this issue? Please update.

**Comment by labrute974** [comment]
Hey guys,

I found what's the issue when removing an item.
Basically, by default, because Ionic is using ngAnimate, when you use ngRepeat, angular will not destroy the DOM of the element straight away, but it will first add the css class: ng-leave to give the user a chance to set animation when deleting an item from the array.

Now, you can disable $animate for a container and all children elements (you can then re-enable for subchildren).
See pull request: https://github.com/driftyco/ionic/pull/3842

**Comment by nunuqq1** [comment]
Hi everyone,
 This problem seems still exists,I don't know why Ionic haven't fix this yet. I found a alternative solution for this issue.

$timeout( function() {
                        $ionicSlideBoxDelegate.update();
                        $ionicSlideBoxDelegate.slide(0);
                    }, 50);

this finely works for me

**Comment by dwilt** [comment]
+1 I'm having issues as well. What seems to be happening to me is that when I remove a slide and it's the one I'm currently viewing, it seems to visually keep it there in the DOM and it looks like it lays over top of the previous/next one (not sure which at the moment). 

@nunuqq1 I came up with this solution on my own but it's still not working totally for me either. This only works if there are 2 slides and I'm on the LAST one and I delete it. It transitions me smoothly to the first like it should and that's all.

**Comment by labrute974** [comment]
Has anyone tested / reviewed the pull request: https://github.com/driftyco/ionic/pull/3842 ?

**Comment by udeeps** [comment]
@labrute974 
wow, that's beautiful. indeed it works like a charm. Just when deleting last item of the array in the slidebox, the slide becomes blank. To make it work, I slide the slidebox to second last item after splicing. 

$scope.slideBoxArray.splice(index, 1);
if (index === $scope.slideBoxArray.length && index > 0)
{
                        $ionicSlideBoxDelegate.slide(index - 1);
                      //or $ionicSlideBoxDelegate.previous();
 }

**Comment by boyfunky** [comment]
@nunuqq1  ur solution works perfectly fine just did d same thing tht @dwilt using the value of the active-slide model.

**Comment by taromorimoto** [comment]
@labrute974 Thanks man! You saved my day!

**Comment by labrute974** [comment]
No worries mate! Glad that helped!

**Comment by opensorceror** [comment]
Still having this issue in 1.1.0! Tried all the above but in vain.
Does anyone know a workaround?
