### ISSUE TITLE
Infinite Scroll issues

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1579]
Infinite scroll is throwing a bunch or errors in the nightly builds.

```
Requested more airlines index.html?editors=001:95
Fetching more airlines! Request Count=4 index.html?editors=001:66
REquesting :80 index.html?editors=001:74
There are 100 airlines in list index.html?editors=001:100
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: airline in data.airlines, Duplicate key: object:006
http://errors.angularjs.org/1.2.12/ngRepeat/dupes?p0=airline%20in%20data.airlines&p1=object%3A006
    at http://code.ionicframework.com/nightly/js/ionic.bundle.js:9051:12
    at ngRepeatAction (http://code.ionicframework.com/nightly/js/ionic.bundle.js:28361:20)
    at Object.$watchCollectionAction [as fn] (http://code.ionicframework.com/nightly/js/ionic.bundle.js:20700:11)
    at Scope.$digest (http://code.ionicframework.com/nightly/js/ionic.bundle.js:20803:29)
    at Scope.$apply (http://code.ionicframework.com/nightly/js/ionic.bundle.js:21056:24)
    at http://code.ionicframework.com/nightly/js/ionic.bundle.js:22591:36
    at completeOutstandingRequest (http://code.ionicframework.com/nightly/js/ionic.bundle.js:13084:10)
    at http://code.ionicframework.com/nightly/js/ionic.bundle.js:13391:7 ionic.bundle.js:18408
```

http://codepen.io/mhartington/pen/KzGaw

**Comment by randavidovitz** [comment]
Occurs still on Beta14, when looking at the code i see that after initial response the callback is called again because inside the infinite scroll in function checkInfiniteBounds the  this.scrollView.getScrollMax().top is 0 and this causes the onInifnite to be called again.

Could it be that the initial call to scrollView.resize(); didn't do its job ?

**Comment by arcanis** [comment]
I, too, have this issue. Maybe it should be reopened ? cc @ajoslin ?

**Comment by paulseed** [comment]
I, too, have this issue. Maybe it should be reopened ? cc @ajoslin ?

**Comment by steve1medix** [comment]
I'm seeing the same issue with beta14. How do you stop it from loading when the list is empty, at the start of the application? We should be able to broadcast that we are ready for the infinite scroll:

$scope.$broadcast('scroll.infiniteScrollReady');

For now, I'm setting a min-height to the list when it's empty. cc @ajoslin

**Comment by paulogr** [comment]
Got the same error here ! on-infinit called twice !

**Comment by ryan-wong** [comment]
I have this error as well. It happens for me when I turn off my api server.

**Comment by raviteja-adusumalli** [comment]
I'm using ionic version 1.0.0-rc. when the page loads for the first time on-infinite scroll  is firing two times,
is there any work around to fix the issue

**Comment by mica16** [comment]
My workaround:       
I'm using a boolean since more than 6 months ;)

```
var shouldTriggerScrollInfinite = false; //handling ionic bug regarding scroll infinite

$scope.moreElements = function () {
            if (!shouldTriggerScrollInfinite) {  //let the first entry in this code but do nothing
                shouldTriggerScrollInfinite = true;
                $scope.$broadcast('scroll.infiniteScrollComplete');
            }
            else {  // here it will be the real need for scrolling 
                $scope.loadFurtherElements()['finally'](function () {
                    $scope.$broadcast('scroll.infiniteScrollComplete');
                });
            }
        };
```

**Comment by olivierlesnicki** [comment]
@mica16 What if the first batch of elements are loaded in the state's resolver?

**Comment by mica16** [comment]
@olivierlesnicki Your initial load don't have to be trigger by the infinite scrolling.
```
$scope.$on('$ionicView.beforeEnter', function () {
   $scope.elements = elements //being elements from your state's resolver
});
```

**Comment by olivierlesnicki** [comment]
@mica16 yes that's exactly what I'm trying to say. But in this case inifnite-scrolling is not called twice. And you don't need the hack you've proposed.

**Comment by onigetoc** [comment]
When loading json content. you go to the page, the content is not yet there, since it's there no content yet, the page do not scroll and the infinit scroll function is trigger. You content appear and the infinite content appear too. 
even on IONIC codepen exemple, json content are called twice when page load.
http://codepen.io/andrewmcgivery/pen/emEOQy

Just look on Chrome inspector "Network"

**Comment by virgincodes** [comment]
tanks that was helpful bro
