### ISSUE TITLE
Feature Request: inputText option for $ionicPopup.prompt() 

### ISSUE THREAD

**Issue by danielzen** [driftyco/ionic#1589]
I want to create an edit text prompt by pre-populating the input text:

``` bash
$ionicPopup.prompt({
  title: 'Edit Text:',
  inputText: 'I want to put editable text here', 
})
```

instead in beta.6 I had to write :(

``` bash
var scope = $scope.$new(true);
scope.data = {response: 'This is editable text' };

$ionicPopup.prompt({
  title: 'Edit Text:',
  scope: scope,
  buttons: [
    { text: 'Cancel',  onTap: function(e) { return false; } },
    {
      text: '<b>OK</b>',
      type: 'button-positive',
      onTap: function(e) {
        return scope.data.response
      }
    },
  ]
})
```

**Comment by patrickmcd** [comment]
I expected this option to be there, similar to ngCordova's defaultText for prompts.

**Comment by danielzen** [comment]
I keep thinking I'm going to just add the feature in myself, and make a
pull request, but sadly I have not :(

This is the hack I have been using:

https://github.com/danielzen/todo-ng-pouchdb/blob/master/www/js/app.orig.js

 $scope.editTask = function(task) { $scope.data = { response: task.title }; //
A hack to pre-populate prompt $ionicPopup.prompt({ title: "Edit Task", scope
: $scope }).then(function(res) { // promise if (res !== undefined) task.
title = $scope.data.response; // response not res has new title (hack)
$ionicListDelegate.closeOptionButtons(); }) }; })
