### ISSUE TITLE
tapping ion-checkbox brings up keyboard on Android < 4.4

### ISSUE THREAD

**Issue by ateufel** [driftyco/ionic#1592]
i am using the latest ionic build, but i am struggling with the keyboard (at least on android). i got an input field where you can enter a number:
```
<input type="number" blur-keyboard>
```
now when i enter it, the keyboard shows up as expected. when i hit "go", it disappears, but **leaves the blue input cursor of android in the input field**. now when i click on any other part of the app (for example, i got a checkbox right after the input field), the keyboard pops up again.
i started writing a directive ("blur-keyboard") to hide the keyboard manually, but i don´t know how to to that:
```
.directive('blurKeyboard', function() {
	return function ($scope, $element, $attrs) {
		$element.bind('blur', function () {
			//TODO hide keyboard
		});
	};
})
```
is this a known issue? it´s a major problem, obviously. i can provide screenshots if my explanation is not understandable.

**Comment by perrygovier** [comment]
Is this still an issue?

**Comment by tlancina** [comment]
Not much we can do for this, the recommendation is to use Crosswalk for older Android devices.
