### ISSUE TITLE
Ionic 4 - How can I change .tab-btn padding??

### ISSUE THREAD

**Issue by frontendraiden** [driftyco/ionic#15963]
Hi!

I tried more variations, but it's not work...

`.tab-btn.sc-ion-tabbar-md {
	--ion-safe-area-right: 4px;
	--ion-safe-area-left: 4px;
}`

`ion-tabs {
	--ion-safe-area-right: 4px;
	--ion-safe-area-left: 4px;
}`

`ion-tabbar a {
	--ion-safe-area-right: 4px;
	--ion-safe-area-left: 4px;
}`

`ion-tabbar a {
	padding: 8px 4px 10px !important;
}`

![screenshot_2](https://user-images.githubusercontent.com/44157493/47002582-b67a4500-d12d-11e8-9340-07e960b299ec.png)

**Comment by MFerreiras** [comment]
If can change using this code:

**In case Tab > Button > Text using:**

`.tabs-ios .tab-button-text {
     padding: 8px 4px 10px !important;
}
`

**In case Tab > Button using:** 

`.tabs-ios .tab-button {
     padding: 8px 4px 10px !important;
} 
`

**In case Tab using:** 

`.tabs-ios .tabbar {
    padding: 8px 4px 10px !important;
}`

**Note:** in case using Android change all words ios to md.
