### ISSUE TITLE
Multiple issues with reorder / delete demo on Codepen.

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#1601]
Docs: http://ionicframework.com/docs/api/directive/ionList/
Pen: http://codepen.io/ionic/pen/JsHjf
Video: https://www.youtube.com/watch?v=DAWCYDnw7Q0 (127 seconds)

Issues:
- `reoder`
- mangled markup in header
- where are buttons to `edit` and `share`
- not passing `fromIndex` and `toIndex` to reorder function (that is causing ng-repeat to choke)

My related question on StackOverflow: http://stackoverflow.com/questions/24139967/how-to-pass-multiple-arguments-to-ionic-reorder-directive

---

I know that you are aware: https://github.com/driftyco/ionic/issues/768 (please have mine +1 on that)

**Comment by inceptiveSujit** [comment]
angular.element(...).closest is not a function touchHold @ sortable.js:34
