### ISSUE TITLE
click on videoplayer inside ion-content doesn't work

### ISSUE THREAD

**Issue by jvanaert** [driftyco/ionic#1607]
I embedded a simple video player in the side-menu example.
When I replace the default content with a video player, the controls of the video player don't work(tested on Nexus 5).
When I remove the surrounding ion-content, the buttons do work, but I guess the ion-content should be there ?

http://codepen.io/jvanaert/pen/EBics

**Comment by ktayfiasma** [comment]
Hi , 
how to display a video from firebase in ionic application ??

**Comment by russelljjackson** [comment]
@perrygovier Thanks for this Perry, you're a life saver! Been beating my head on this for hours.
