### ISSUE TITLE
Whole view can be moved up and down

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#1609]
Issue #1218 is the previous example of this (not sure whether you prefer to reopen that or create a new one)

6 beta
ios - on device

@shprink has a codepen (on 1218) that recreates it (in latest code)

Ideally the entire view should not move (i.e header / footer stays static)

**Comment by famebo** [comment]
Hello i know this is old post but this answer might be help if someone needed.

#1218  you can find the solution here which i wrote down too.

`<preference name="DisallowOverscroll" value="true" />` 

In `config.xml` just set it `true` and try it again.
