### ISSUE TITLE
Suggestion: Adjust header bar and buttons dependend on content size

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#1618]
I think that iOS does a really good job on optimizing the content's size of the header bar. It automatically extends the available space of the title if it's too long and removes the back button's label if needed.

[This article](http://c2prods.com/2013/cloning-the-ui-of-ios-7-with-html-css-and-javascript/) describes the problem very well and provides a good solution (paragraph 3.2. Titlebox).

What do you think, is this something for Ionic? I'd love the Ionic framework even more!

**Comment by perrygovier** [comment]
This is now a part of Ionic with the beta14 updates
