### ISSUE TITLE
"Current working directory is not a Cordova-based project."

### ISSUE THREAD

**Issue by Jorenm** [driftyco/ionic#1624]
Following the getting started instructions, I'm running into this error on step 3 when I try to run: ionic platform add android

My server is Ubuntu 14.04 LTS

**Comment by petarslovic** [comment]
I had the same issue, and the problem went away after I added an empty `www` folder. The thing is that `www` is in `.gitignore` so when you `git clone` a project everything is there and set up, except `www`. :D

**Comment by phible** [comment]
`mkdir www` solved the problem for me, too (thanks @devakone!)
I have a different app structure than what cordova creates (and expects).
