### ISSUE TITLE
Collection Repeat and remember scroll position

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1654]
From the forum :
http://forum.ionicframework.com/t/collection-repeat-in-tabs-and-rememberscrollposition/5912/2

If you use collection repeat with tabs, the scroll position isn't remembered when you switch tabs.

Affected Version: Nightly
Codepen: [Demo Here](http://codepen.io/mhartington/pen/sCdjL)

Side Note: There's a little wonky-ness with collection repeat, not sure if it's just me. But if you resize the browser or scroll, the new items kind of animate in.

**Comment by erperejildo** [comment]
how can I implement this on Ionic 3?
