### ISSUE TITLE
Hidden tab attribute for ion-tab elements

### ISSUE THREAD

**Issue by ducdigital** [driftyco/ionic#1666]
This will help people able to implement both side-menu and ion-tabs at once.

In the file: *\* js / angular / directive / tab.js **

Change: 

`tabsCtrl.$tabsElement.append($compile(tabNavElement)($scope));`

to 

`if ($attr.hidden !== 'true') {
  tabsCtrl.$tabsElement.append($compile(tabNavElement)($scope));
}`

This allow a hidden="true" attribute in the ion-tab element. It will hide the button but view/controller will continue to works as normal. We can access it by route or other mean like a normal tab.

I hope we can implement this if there are no problem :)

**Comment by jason-engage** [comment]
Does anyone know how to properly hide and show tab items? Like a method to toggle them individually?

**Comment by JobaDiniz** [comment]
It is related if you think about.

My scenario, described [here](http://stackoverflow.com/questions/31977653/ionic-app-with-tabs-global-search-header), it a little bit different.

I want all tabs to be visible at all times, but I don't want to link all my states to one particular tab. All my states, except each root tabs states, should be rendered in the **current selected** tab.

Did I made this up? No... Facebook (iOS) does exactly that. They have a set of fixed tabs and all other *"states/views"* are rendered in the *active tab*. *- it's genius*.

Unfortunately, I wasn't able to hack things around to make this work (tried a few things, like creating *views* state object on the fly...).

**Comment by elineopsommer** [comment]
Hi,
How is this done in Ionic2? I tried:
<ion-tab [root]="TeamPage" [attr.hidden]="true" tabIcon="settings"></ion-tab>
<ion-tab [root]="TeamPage" [hidden]="true" tabIcon="settings"></ion-tab>
but no luck.

**Comment by MrFragStealer** [comment]
hi, @elineopsommer did you figure it out? 
I'm also interested how to do this in Ionic 2.

**Comment by kyr0** [comment]
@MrFragStealer Your solution works, but isn't very dynamic or programmatically controllable. I think, this Directive is cleaner:

[TabHiddenDirective](https://gist.github.com/kyr0/11830a1560a6d1173be84b966d171edc)

**Comment by harshasanjeeva** [comment]
@MrFragStealer thanks it works
