### ISSUE TITLE
ion-view pushes to stack

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#1667]
When using `<ion-view>` in certain places (like a Modal), it can unexpectedly push a state to the stack and then show a back button incorrectly when the modal is closed.

Can we add a way to say this view will not push to the stack, or provide more clear ways of using the ion-view tags in modals and other non-navigational UIs?

**Comment by ladmerc** [comment]
@travisdahl Did you find a way to push to history stack? I need a similar feature
