### ISSUE TITLE
resize modal based on content

### ISSUE THREAD

**Issue by Balaraju1** [driftyco/ionic#16852]
few components are displayed in modal. Few Components have smaller content and few are larger. So i want the modal height and width to resize based on the content.  but, current behavior  modal will taken fixed --width:600px; and fixed --height:500px; . there variables change to --width:auto; --height:auto;
dialog hidden. 
can anyone tell me alternative?

**Comment by dylanvdmerwe** [comment]
Can't you specify a call to control the size of the modal using the `cssClass` property? 

You also can modify the modal's [css vars](https://beta.ionicframework.com/docs/api/modal#css-custom-properties).

**Comment by Balaraju1** [comment]
@paulstelzer  height was change dynamically based on content. but, width was not increasing based on content..

**Comment by paulstelzer** [comment]
The width you have to change yourself. This cannot be dynamically based. You have to set width / min-width and max-width
