### ISSUE TITLE
How to serve Ionic app with https?

### ISSUE THREAD

**Issue by moroshko** [driftyco/ionic#1686]
Running `ionic serve` allows to run the app on `http://0.0.0.0:8100`.

Trying to access `https://0.0.0.0:8100` results in:

> SSL connection error

Is there a way to run the app on https?

The reason I need https is because I use Firebase and it requires requests to be made over https. See: 
http://stackoverflow.com/q/24431924/247243
http://stackoverflow.com/q/24442013/247243

Any ideas?

**Comment by justindmyers** [comment]
Sorry to jump back on this, but I spent a while trying to get this to work as well. Seeing as this thread comes up quite high on search results, the above solution didn't quite work for me as getting the SSL certificate working was a problem. 

The only article that I found that successfully walked me through the solution was https://matoski.com/article/node-express-generate-ssl/

I combined both to finally get it working: https://gist.github.com/justindmyers/266d169e97de20068f78

**Comment by nicopace** [comment]
Hi guys,
This is important because when you are developing a mobile app that uses any html5 feature (geolocation, rotation,..) chrome now requires it to be used from a secured location.

**Comment by Quirksmode** [comment]
Agreed, any simple solution for this, I am using Ionics built in server (ionic serve), where do I need to go to make the changes needed for https?

**Comment by scrivy** [comment]
to create a self signed cert and run it with a go proxy script
[https://gist.github.com/scrivy/0909468fde8f117a3d66507c8bb3fe12](https://gist.github.com/scrivy/0909468fde8f117a3d66507c8bb3fe12)

**Comment by rainmak33r** [comment]
Any idea how to make this working on an actual app ?

**Comment by niczak** [comment]
Any movement on this item in the last 6 months? I am working w/ the Twilio API and again everything must be under HTTPS as opposed to HTTP.

**Comment by perrygovier** [comment]
heyo, sorry I don't have a silky smooth ionic solution, but I find that you can use `ionic serve` and then an ngrok proxy to get things behind https. it's not ideal, but it should work.

**Comment by niczak** [comment]
@perrygovier Hey buddy, long time no talk! :)

Do you happen to have a guide for using ngrok locally for this purpose?  Would be a huge help right now...

**Comment by niczak** [comment]
@perrygovier I think I am all set, thanks for the suggestion!  I will be doing a ton of testing on Monday but the setup I have no looks very promising.

**Comment by perrygovier** [comment]
Awesome. You might have trouble with the proxy and a corporate firewall, but just `ngrok http 8100` should give you an https URL you can hit.

**Comment by ronaiza-cardoso** [comment]
Hi, I made the HTTPS server, but  where do I need to go to make the changes needed for using ionic serve with HTTPS?

**Comment by Qvatra** [comment]
any update on how to configure ionic to use https for serve?

**Comment by niczak** [comment]
@Qvatra I used https://ngrok.com - point it at your ionic serve URL and then use the HTTPS ngrok URL to do your stuff that requires HTTPS such as API calls, WebRTC, etc.

**Comment by Qvatra** [comment]
@niczak, would it be a problem when app would be deployed on a mobile device?
at that point I would not be able to run **ngrok** to make it serve in secure way...

To give the context I'll explain what i'm doing in my app:
1) I’m sending authentication request from my app to SSL server using ionic proxy.
2) Server response contains sessionId in secure cookie.
3) I’m sending another request that suppose to have this sessionId in requestHeader cookie.

In reality the last request doesn’t have sessionId in requestHeader cookie and that's why I get 401 ‘Unauthorized’. 
When I look at responseHeader cookie of the first request I see the following: 
set-cookie:PHPSESSID=5583u6dcq803qlm5mnnc79vua4i0hs10htoj1mavskhv0bdg8m31; path=/; secure; HttpOnly

My idea is to make it somehow run in secure mode so that this secure cookie would be passed through. But don't know how..

**Comment by jszxAccount** [comment]
@Qvatra, any news on this?

**Comment by gx200918** [comment]
@Qvatra , any news on it?

**Comment by CristhianUNSa** [comment]
How to configure `ionic cordova run android` to point to my https ngrok address? I tried `ionic cordova run android -l -c --address "https://urlto.ngrok.io"`, but then an error appeared. "[ERROR] app-scripts serve unexpectedly failed.settings: undefinedcontext: [object Object]"

**Comment by miqmago** [comment]
That's working fine: https://stackoverflow.com/a/43426714/513570:

You need to create a port-forwarding in chrome://inspect/#devices:

Port: 8101
Forward: localhost:8100

Enable port-forwarding.

On the mobile device visit `localhost:8101`
Notice: localhost on mobile device and port 8101.

**Comment by Domvel** [comment]
Any status update? Webpack should support https. Why is this not yet implemented for ionic livereload?

**Comment by XMalatji** [comment]
Still no Ionic support. Had to self generate.

**Comment by redplane** [comment]
I have the same question for ionic 3 . So frustrating.
