### ISSUE TITLE
Using collection-repeat with dynamic item heights

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#1691]
I have a long list of items that have varying heights. In order to get the best performance on Android, I would like to use collection-repeat. 

I am now running into trouble determining the height of each item to supply to the getItemHeight function.

Consider the following:

```
$scope.getItemHeight = function(item, index) {
   console.log('index',index);
   var ul=document.getElementsByTagName('ul')[0];
   var li=ul.getElementsByTagName('li')[index];
   return li.offsetHeight;
};
```

The li item isn't rendered yet by this point so the height can't be determined yet.

Once you wrap it in a timeout, the li item is known, but the list doesn't render:

```
$scope.getItemHeight = function(item, index) {
   console.log('index',index);
   setTimeout(function(){
      var ul=document.getElementsByTagName('ul')[0];
      var li=ul.getElementsByTagName('li')[index];
      return li.offsetHeight;
   },2000)
};
```

Check out this Codepen:
http://codepen.io/squrler/pen/qxKkC?editors=001

Is it possible at all to determine the height of each element and then pass that to the getItemHeight function of collection-repeat?

**Comment by mohamed-ahmed** [comment]
@perrygovier, how did you go about adding text to a detatched div, checking the height of that, and then using that to calculate the hight of the item?

**Comment by mohamed-ahmed** [comment]
@perrygovier, how did you go about adding text to a detached div, checking the height of that, and then using that to calculate the hight of the item, as you mentioned you did above?
