### ISSUE TITLE
Tabs Color Classes Not working

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#1695]
Ionic Beta 7 and below.

Most of the `tabs-X` color classes do not work.

Reproduce: 

Use Ionic CodePen sample : http://codepen.io/ionic/pen/odqCz

Change tabs class to : 
- tabs-positive : Works
- tabs-default : Works
- tabs-secondary : same as default
- tabs-primary : same as default
- tabs-info : same as default
- tabs-success : same as default
- tabs-warning : same as default
- tabs-danger : same as default
- tabs-dark : Works
- tabs-light : Works but active tab does not show on Android. See Issue #1694 : 

FYI : Many tabs classes are not documented.  See https://github.com/driftyco/ionic-site/issues/194

**Comment by kmojanovska** [comment]
@calendee You should include this in the head section
<link href="http://code.ionicframework.com/1.0.0-beta.8/css/ionic.min.css" rel="stylesheet">
