### ISSUE TITLE
Input file click not working when wrapped with label in ion-content

### ISSUE THREAD

**Issue by saravmajestic** [driftyco/ionic#1699]
Hi,

I am trying to create a file upload button with label wrapping input file. But clicking the label does not trigger the file upload popup.

Codepen: http://codepen.io/anon/pen/ArsCq 

Thanks,
Saravanan

**Comment by eweap** [comment]
Hi ! It seems that this bug is persisting in v1.0.0-beta.14-nightly-963, here is [an example](http://codepen.io/eweap/pen/LEyKBN)

Any ideas for a workaround ? I've tried to add ```data-tap-disabled="true"``` on the label but it didn't work.

Thanks
