### ISSUE TITLE
ionicLoading module backdrop on modal (doesnt disable clicks/input)

### ISSUE THREAD

**Issue by ftorre104** [driftyco/ionic#1720]
ionicLoading module does not disable background click/functionality on modal views; only on the primary view.

Here is an example of the problem:
http://codepen.io/ftorre/pen/GwqeI

For more info and a possible solution, see:
http://forum.ionicframework.com/t/ionicloading-overlay-doesnt-disable-background-buttons-on-modal/6355/3

**Comment by jackyon** [comment]
I am also facing this issue recently, and I have be end up with this solution:

overwrite the loader css, for example:
.loading-container {width:68px;height:73px;left:50%;top:50%;margin-top:-34px;margin-left:-36.5px}

and bind the loader hide event when click the back button:
$ionicLoading.hide();

I think this will be easier and safe to use it.
(I don't want to touch the main core, so it will be always worked even after I upgrade to the new version of ionic.)
