### ISSUE TITLE
NavController.navigateBack lack of animation for .ios

### ISSUE THREAD

**Issue by rafalschmidt97** [driftyco/ionic#17277]
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

How you can see below animation works perfectly on md. Unfortunately for ios it just wait for a second and then change page without any animation. I use NavController with .navigateBack(['/welcome']).

![screen recording 2019-01-26 at 19 58 27](https://user-images.githubusercontent.com/14861637/51791816-62114780-21a9-11e9-9179-566341db7371.gif)

**Expected behavior:**

It would be cool to see animation like back one.

**Steps to reproduce:**

Just two tabs and another page outside of this. Really simple to reproduce.

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 2 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

Great work by the way. Very easy to use 🚀

**Comment by ippeiukai** [comment]
I'm having the same issue with `@ionic/angular 4.0.1`.

```
Ionic:

   ionic (Ionic CLI)             : 4.10.0 (/*****/node/v8.9.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.0.2 (/*****/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 5.0.13
   NodeJS            : v8.9.1 (/*****/node/v8.9.1/bin/node)
   npm               : 5.5.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by ippeiukai** [comment]
https://stackblitz.com/edit/ionic17277

Not sure why it's failing on stackblitz, but it works locally.
Please download the project and `npm i && npm start`.

**Comment by lincolnthree** [comment]
Also experiencing this issue on 100% of back transitions using ios-style animations. @ippeiukai @rafalschmidt97 Did either of you find a workaround for this?

**Comment by lincolnthree** [comment]
Potentially related: https://github.com/ionic-team/ionic/issues/18181
