### ISSUE TITLE
Overflow-scrolling of ion-content not working | Android 4.4.4 Nexus 5

### ISSUE THREAD

**Issue by AlmogBaku** [driftyco/ionic#1737]
Works properly in iOS.

On Android, the scrolling of the ion-content's `overflow-scrolling` animation does not work.(but it allow to scroll regularly).

**Comment by gsanjeevkumar** [comment]
I have a situation with scrolling of list 

in the controller i do ( also tried with or without Platform.isIOS Check... did not work

set the code for controller and the template... Please let me know where am I doing it wrong

`$scope.contentScrolling = function(){
 if (ionic.Platform.isIOS()) {
  $ionicScrollDelegate.$getByHandle('listscroll').resize();
 };
};`


`<ion-scroll on-scroll="contentScrolling()" delegate-handle="listscroll">
			
			<ion-list class="item-previews">

				<ion-item href="#/item-details-phones/{{item.ID}}" class="item-icon-right item-preview" collection-repeat="item in itemsArray | orderBy: 'Name'">

					<div class="item-thumbnail" style="background-image: url( '{{item.ThumbnailScr}}' );"></div>
					<ion-option-button class="button-positive" ng-click="showPoints(item)">points</ion-option-button>
					<ion-option-button class="button-balanced" ng-click="showMap(item)">map</ion-option-button>
					<div class="item-data">
					<span class="item-name" ng-bind-html="item.Name"></span>
					<div class="sub-title" class="item-location">
					<span ng-bind-html="item.Location"></span>
					<span class="item-designation">{{item.itemType}} item</span>
					<span class="item-presidential" ng-class="{'show-label' : item.Presidential}">Presidential Suite</span>
					
					</div>
					<i class="icon ion-chevron-right icon-accessory"></i>
					</div>

				</ion-item>

			</ion-list>
		
		</ion-scroll>`
