### ISSUE TITLE
If `overflow-scroll=true` is enabled on my `ion-content` container, I can not use the $ionicScrollDelegate.

### ISSUE THREAD

**Issue by gigablox** [driftyco/ionic#1740]
If `overflow-scroll=true` is enabled on my `ion-content` container, I can not use the $ionicScrollDelegate.

```
$scope.scrollDown = function(){
  $ionicScrollDelegate.$getByHandle('myScroll').scrollTo(0, window.innerHeight, true);
}
```

This works when overflow-scroll is disabled. How do I programmatically scroll while using `overflow-scroll=true`?

**Comment by iDeekshith** [comment]
HI @ajoslin ,
Can you help me how to achieve scrollTop with overflow-scroll. Its not working for me.
I have set the delegate-handle on ion-content
