### ISSUE TITLE
Ionic blocking ui-calendar events

### ISSUE THREAD

**Issue by jellevictoor** [driftyco/ionic#1746]
I'm creating an application with the ionic framework and I have a screen where I need to plan events in a calendar.
I can drag and drop them, but the functionality of the ui-calendar directive is blocked, It seems ionic puts a layer on top of this and catches the events so that they don't propagate to the calendar directive. **This works in a desktop browser, but not on a mobile browser.**
I created a plunkr supporting my case in this plunkr, the drag and drop works, but the events aren't shown in the calendar. This is normal, I did not implement everything.

http://plnkr.co/edit/zfKkCp2pMaeDGvN3rq86

The core is this code, I think the ion-content is blocking the events, but I don't know how to recreate the layout without having an ion-content element.

this is my thread on the ionic forums http://forum.ionicframework.com/t/ionic-framework-blocking-ui-calendar-events/6450

**Comment by YasserRabee** [comment]
@perrygovier 

I have a project where I use ui-grid, the same behavior happens with me. After hard investigation me with my team concluded the issue:

Touch events (touchstart, touchmove, touchend) is used to detected two other events (scroll and drag). The issue that scroll and drag events can't be detected together -- see your [code comment](https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L1743)

So if and for any reason ionic attach a `on('drag')` at certain elem this element will not receive any scroll events -- this fact come for [this code line](https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L1779)

The issue with `ui-grid` and `ui-calendar` that they listen for `scroll` event which is not fired at all.

**Our case**: we use `ion-side-menus` and although we have set `drag-content="false"` on `ion-side-menu-content`, the content still listens for a `drag` event and disable the detection of `scroll`.

**Worked solutions**: 

1. very bad hack, commented out [this code line](https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L1779) to propagate the touch event - this will enable `scroll` and disable ANY `drag`

2. non practical one, just don't use `ion-side-menus` at all

**Suggested solution**:

1. adding new directive that forces disabling drag event on an element and all its children. So we can disable drag detection on the root elem of the `ui-grid` which enables detection of the scroll event.

2. disable the drag detection made by `ion-side-menus` when setting `drag-content="false"
