### ISSUE TITLE
Reordering list items does not work on Windows Phone

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#1753]
Trying this demo: http://codepen.io/ionic/pen/JsHjf (1.0.0-beta.9)

Video: https://www.youtube.com/watch?v=2ReG7Sylmg4 (1 minute)

```
Nokia Lumia 925
Windows Phone 8.0
Internet Explorer mobile 10
```

In the past I've reported some bugs / issues but quite often they were out of scope (Ionic's core mission is **hybrid apps**). 

It seems like Windows Phone is not supported just yet - http://forum.ionicframework.com/t/windows-phone-support/60

Shall I *Submit new issue* or close this browser tab assuming you are already in the know with all the Windows Phone issues?

**Comment by mhartington** [comment]
We will not be supporting WP8 with ionic v1.
