### ISSUE TITLE
The Ionic slidebox requires explicit CSS to show Ionic content

### ISSUE THREAD

**Issue by dtangster** [driftyco/ionic#1755]
For instance, the html below will not display any slides even when all variables used contain data. It works if I remove the `<ion-content>` tag, but then I would not be able to scroll if the content is more than the screen height.

``` html
<ion-view title="Title">
    <ion-slide-box show-pager="false">
        <ion-slide ng-repeat="article in filteredArticles">
            <ion-content class="has-header">
            <img ng-src="{{ article.imageURL }}" ng-style="{ 'width': '100%' }" />
            <div ng-bind-html="article.html"></div>
            </ion-content>
        </ion-slide>
    </ion-slide-box>
</ion-view>
```

If I want to keep the `<ion-content>` tag, I must have explicit CSS like so:

``` javascript
.slider {
    height: 100%;
}
```

Is there a reason why the .slider class doesn't have a default height of 100%?

**Comment by syarifuddinahmads** [comment]
hey there. am using ionic one, and am have a problem in slidebox,

am load img from controller but img not load to firstime open or run app,
need to resize and round rotation to showing slidebox,

how to fix guys...

**Comment by sertunc** [comment]
@perrygovier when i put <ion-content> everthing is ok. you save my life =) thank you

**Comment by newuser44** [comment]
Did this start working?  Any example of how to get a modal with the slide in it?
