### ISSUE TITLE
Disable gesture events for an element

### ISSUE THREAD

**Issue by orandolabs** [driftyco/ionic#1765]
I added vis.js to an ionic app. vis.js uses hammer on it's canvas to generate gestures, much like ionic. The ionic gestures were causing the same event to be fired multiple times.

I'm not sure if this is the correct fix, but it works for my use case. In ionic.tap, I added

```
isElementGestureDisabled: function(ele) {
  if(ele && ele.nodeType === 1) {
    var element = ele;
    while(element) {
      if( (element.dataset ? element.dataset.gestureDisabled :   element.getAttribute('data-gesture-disabled')) == 'true' ) {
        return true;
      }
      element = element.parentElement;
    }
  }
  return false;
},
```

Then in ionic.Gestures.Instance, I added this in trigger:

```
  if (!ionic.tap.isElementGestureDisabled(element))
    element.dispatchEvent(event);
```

**Comment by jdnichollsc** [comment]
Very useful! :+1:
