### ISSUE TITLE
Can't click and hold to zoom letters/scroll in textarea when keyboard is shown.

### ISSUE THREAD

**Issue by rivf** [driftyco/ionic#1769]
I have this issue on latest ionic version.
Used ionic start myApp tabs (as the guy here: http://forum.ionicframework.com/t/solved-text-input-cannot-be-edited/2655). Also I tried to replace ionic.bundle.js and ionic.css with beta 9 files - everything is the same.
Any ideas?

``` html
<ion-view title="Feedback">
  <ion-content class="has-header padding">
    <form name="feedback" ng-submit="submitFeedback(userFeedback)">
        <div class="list">
            <label class="item item-input">
                <textarea  placeholder="Your feedback" rows="9" ng-model="userFeedback"></textarea>
            </label>
        </div>
        <button class="button button-block button-positive" type="submit">
            Send feedback. Thanks :3
        </button>
    </form>
  </ion-content>
</ion-view>

```

Actually full code. I read everywhere that it is fixed. But it's not.
I don't use any custom css or js libraries, just ionic. 

Problem is in browser, in app it works fine (after replacing files of beta 8 I think). Before that - the problem was in app too.
This page is renamed friend's page from starter tabs project.

**Comment by TejasQ** [comment]
I'm on 1.3.19 and I still have this problem. :(

**Comment by mhartington** [comment]
1.3.19 is not the ionic.js version, but the ionic cli version. 
Tested this using RC4 and everything is working.
