### ISSUE TITLE
[WP8] Input label shift out when focus in

### ISSUE THREAD

**Issue by apolkingg8** [driftyco/ionic#1778]
I tried ionic `sidemenu` start project on my Lumia 720(wp8), and it's something wrong on input label. When input get focus, the label shift left out of input and not shift back when input out of focus. Screenshot there: 

![wp_ss_20140712_0002](https://cloud.githubusercontent.com/assets/4033753/3561230/bf21f5ac-09b0-11e4-8d08-bfa3da86081c.png)
![wp_ss_20140712_0003](https://cloud.githubusercontent.com/assets/4033753/3561231/bf2baade-09b0-11e4-95ba-84a2dfed3517.png)
![wp_ss_20140712_0004](https://cloud.githubusercontent.com/assets/4033753/3561232/bf2d0aaa-09b0-11e4-8844-e7af5fe0f44f.png)

I know ionic not support windows phone, but I still hope that this amazing framework can appear on my favorite platform :P

**Comment by luisrudge** [comment]
I'm having this problem too

**Comment by mhartington** [comment]
No updates on WP8. It is still not a supported platform

**Comment by luisrudge** [comment]
I understand that. But do you have some thoughts on this issue?

**Comment by luisrudge** [comment]
Here's a demo of the issue

![label-issue](https://cloud.githubusercontent.com/assets/941075/5869078/302f8520-a29a-11e4-9ab9-7a734e1c6632.gif)

**Comment by vko-online** [comment]
Also sometimes `<input type="password">` behaves strange, you can't type anything in it

**Comment by luisrudge** [comment]
Password is working for me everytime

**Comment by DLS201** [comment]
Hello, I had the same problem on my website and setting flex-shrink to a value > 0 fixed the problem.

**Comment by baltazaroliveira** [comment]
Can you send that code piece?
