### ISSUE TITLE
NavigationHistory going crazy after going to non-tab state

### ISSUE THREAD

**Issue by AlmogBaku** [driftyco/ionic#1782]
**http://codepen.io/anon/pen/cpxJz**

### Step to reproduce: ###
1. Define some tab as default state(home)
2. `$state.go("non-tab-state")` - go to some non-tab state
3. `$state.go("tab.home")` - go back to tabbed-state
4. inside the tab, surf to some inner page... (click the button)
6. **Back-Button is missing (ng-hide)**

#### Example ####
**http://codepen.io/anon/pen/cpxJz**

**Comment by perrygovier** [comment]
@AlmogBaku this should be fixed with beta14. let me know if you're still seeing it. Also, you can look at our [navtest sample project](https://github.com/driftyco/ionic-starter-tests) for an example of switching between tabbed and non-tabbed views.
