### ISSUE TITLE
Scrolling Issues after expanding content

### ISSUE THREAD

**Issue by paishin** [driftyco/ionic#1787]
When a page contains collapsible items that when expanded take more than the full height  of the viewport you cannot scroll down for a few seconds. Scrolling up is no problem. I suspect that this is caused because ion-content needs some time in order to refresh its height making the app seem unresponsive.

**Comment by kwieckowski-neducatio** [comment]
Hi, sorry for necroing this thread, but...
My page contains some content generated by a 3rd party plugin and I'm unable to catch the collapse event to run $ionicScrollDelegate.resize(). Any ideas on how could I resize scroll in this situation?

**Comment by pugwonk** [comment]
Well, I'm necro-necroing this thread. This SO answer fixed it for me. https://stackoverflow.com/a/42842889/498949
