### ISSUE TITLE
overflow-scroll="true"  not working on android

### ISSUE THREAD

**Issue by tzaavi** [driftyco/ionic#179]
I'm setting the content directive to use the native scroll [overflow-scroll="true"] and it's not scrolling on android.

**Comment by pwr-reques** [comment]
i solved with a litle hard code  in CSS
overflow-scroll='true'   + .scroll-content{ overflow: scroll!important; }

hope to be helpfull :-D Paz from DR

**Comment by Fayozjon** [comment]
Patrick

http://wondrew.net/pokupka

23.03.2015, 23:41, "Patrick" <notifications@github.com>:i solved with a litle hard code  in CSS
overflow-scroll='true'   + .scroll-content{ overflow: scroll!important; }

hope to be helpfull :-D Paz from DR
