### ISSUE TITLE
Black Flash iOS (With Keyboard Plugin)

### ISSUE THREAD

**Issue by andrewmcgivery** [driftyco/ionic#1791]
From https://github.com/driftyco/ionic-plugins-keyboard/issues/23#issuecomment-49064396

Looked through the issues and didn't see anything about this, but is it normal that when the keyboard opens there is a black flash before it pops up?

**Comment by softBarbarian** [comment]
I have seen this in one of my apps before. 
I was able to fix this by changing scroll-view background color.

**Comment by adamduren** [comment]
@andrewmcgivery What styles did you take off to fix this?

**Comment by Paul-Todd** [comment]
I'm having the same problem as well but only on Android devices

**Comment by spectravp** [comment]
Experiencing a similar issue. I have keyboard scroll disabled ($cordovaKeyboard.disableScroll(true)). When tapping into a text field for the first time, the screen jumps downward and animates back up. The keyboard does NOT open. A secondary tap into the field reveals the keyboard. Here is a slow motion video of it: http://zdidesign.com/FLICKER.mov

**Comment by hughred22** [comment]
Having the same issue. I have overflow-scroll="true" on the ion-content. And cordova.plugins.Keyboard.disableScroll(true); on perform ready. Here is the iOs bug demo: 

https://youtu.be/JFWzZDl-KWI

What kind of style fix you guys use to avoid this issue?

**Comment by hughred22** [comment]
As you see from the video, it is a flicker not black flash on iOs. Very obviously as you see the second try on iOs. Any idea what is causing this?
