### ISSUE TITLE
How to scroll content of the page? (that sits outside of Ionic)

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#1792]
I'm using Ionic to build a mobile web app.
On larger screen I'm displaying an image:
![screen shot 2014-07-16 at 18 29 43](https://cloud.githubusercontent.com/assets/249703/3602672/cf015920-0d0e-11e4-8aa1-c38a8c50f0a6.png)

At first I was using iframe but that was causing issues on iOS, eventually ended up using this: https://github.com/driftyco/ionic/issues/1534#issuecomment-44946144

---

Now that causes problems with scrolling:

Video: https://www.youtube.com/watch?v=ShNQr3eNUCM (2m 25s)

Plunker: http://plnkr.co/edit/TNU6iQN30WZgmqwg80Tl?p=preview

---

I wonder which CSS classes shall I modify to allow scrolling on body?

I know that it is outside core mission of Ionic but I'm pretty sure you can give me a hint.

Related question on SO: http://stackoverflow.com/questions/9280258/prevent-body-scrolling-but-allow-overlay-scrolling

Thanks!

**Comment by simonqian** [comment]
add two styles: scroll-content overflow-scroll
