### ISSUE TITLE
Will backbone.js support will be available? (or is it opinionated to use angularjs)

### ISSUE THREAD

**Issue by jonas-db** [driftyco/ionic#1793]
Hi,

it seems like everything is opinionated towards angularjs, it would be cool if we could also make use of backbone.js to build our apps. (I know angularjs mainly provides the 2way binding which is cool, but i do not think that in basic apps this is really necessary an only causes overhead)

As described at https://github.com/driftyco/ionic/issues/546, there should be low level APIs, but i do not find lowel level apis except for the sidemenu...

Any news on this?

Thanks!

**Comment by ionutzp** [comment]
hi @perrygovier,
how about using ionic without angular? would you say this is possible/recommended?
