### ISSUE TITLE
Ion tab ng repeat issue

### ISSUE THREAD

**Issue by TheCodeDestroyer** [driftyco/ionic#1829]
Well I have been playing around with Ion tabs a bit and I think I found a bug. 
My current code looks like this:

``` html
<ion-tabs class="tabs-icon-top tabs-top tabs-dark">
    <ion-tab ng-repeat="tab in tabs" title="{{ tab.title | translate }}" icon="{{ tab.icon }}" href="#/{{ tab.htmlUri }}">
        <ion-nav-view name="{{ tab.viewName }}"></ion-nav-view>
    </ion-tab>
</ion-tabs>
```

If I replace `<ion-nav-view name="{{ tab.viewName }}"></ion-nav-view>` with 
`<ion-nav-view name="home-tab"></ion-nav-view>` it works so I was wondering why doesn't
`{{ tab.viewName }}` resolve If I inspect the element it hasn't even been parsed its still `name="{{ tab.viewName }}"` in html.

**Comment by zeng-ge** [comment]
I have fixed it in [https://github.com/driftyco/ionic/pull/9882](url)
