### ISSUE TITLE
bug: Nested states, missing navbar inside modal

### ISSUE THREAD

**Issue by mbuster** [driftyco/ionic#1838]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>As mentioned in this thread:
http://forum.ionicframework.com/t/ion-nav-bar-invisible-inside-modal/6996

I have a nested view in a modal, which contains an ion-nav-bar, etc. All of my routing inside this nested view works as expected, however, the ion-nav-bar in the modal is invisible. I am currently using 1.0.0-beta9. This was working a few betas ago (beta7 or 8, not entirely sure when it broke, sorry).</span>

<span is-issue-template></span>

**Comment by michael8090** [comment]
@mhartington The feature should be added into ionic.

**Comment by rainboxx** [comment]
No progress recently on the thread within the forum. @mhartington currently we don't understand why this is something the Ionic will not be working on. Can you clarify? Thanks.

**Comment by mhartington** [comment]
At the moment, we're not adding anything new to ionic as we are close to release 1.0 final. 
Added this to our trello board 
https://trello.com/c/5YqqFf8y/88-nested-states-in-modals
