### ISSUE TITLE
bug: Ionic iPad issues running inside an iFrame

### ISSUE THREAD

**Issue by ivancho72** [driftyco/ionic#1853]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

<span ionic-description>I am using ionic for a mobile development and it will run inside an iFrame in a hybrid app. I am having issue with the keyoboard not working inside textboxes and with scrolling not working in lists duo to the fact that ionic is running inside an iFrame. You can reproduce the issue very easy if you go to this urls using safari in an iPad: 

https://magic-hippie-codio.io/ionictest/index.html (try to use the iPad keyboard in the text input ... not working!!! )

https://magic-hippie-codio.io/ionictest/default.html (This the same page outside the iframe... it works fine in the iPad !!!)

What is the issue??? I need help. Thanks!</span>

<span is-issue-template></span>

**Comment by EthanZhanXD** [comment]
@ivancho72 I meet the same problem, did you solve this probem, can you share the solution? Thanks,
