### ISSUE TITLE
bug: Anim 'slide-in-up' doesn't work in <ion-nav-view>

### ISSUE THREAD

**Issue by vladipus** [driftyco/ionic#1859]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>According to the manual (http://ionicframework.com/docs/api/directive/ionNavView/) this is one of preferred animations: "Recommended for page transitions: 'slide-left-right', 'slide-left-right-ios7', 'slide-in-up'".
But it doesn't seem to work when used inside `<ion-nav-view>`.
Here is a codepen: http://codepen.io/anon/pen/BsvxH</span>

<span is-issue-template></span>

**Comment by wkaskie** [comment]
I am also having the same issue. Class slide-in-up does nothing on ion-nav-view
