### ISSUE TITLE
Failed to use delegate-handle for several instances of ion-slide-box

### ISSUE THREAD

**Issue by MaximShoustin** [driftyco/ionic#1865]
I have 3 `ion-slide-box`. Everyone has 3 items.

I created two buttons `Next` and `back` to simulate sliding by pressing them.

However `delegate-handle` doesn't work. I get:

```
Delegate for handle "slider1" could not find a corresponding element with delegate-handle="slider1"! next() was not called!
```

Sounds like `delegate-handle` doesn't register properly the instance ids.

This is what I have so far:

```
scope.nextSlider = function(sliderId){
         $timeout(function(){
             $ionicSlideBoxDelegate.$getByHandle(sliderId).next();
      }, 1000);       
      }

       scope.prevSlider = function(sliderId){         
         $timeout(function(){
             $ionicSlideBoxDelegate.$getByHandle(sliderId).previous();
      }, 1000);         
      } 
```

---

**Template**

```
 <ion-slide-box delegate-handle="{{sliderId}}" 
                       on-slide-changed="slideHasChanged(index)" 
                       show-pager="false">
      <ion-slide ng-repeat="color in colors">        
             <!-- -->
        </ion-slide>
    </ion-slide-box>
```

And this is a [DEMO](http://codepen.io/anon/pen/imAjt) I play with

The issue was posted in [Ionic Forum](http://forum.ionicframework.com/t/failed-to-use-next-previous-in-ion-slide-box-with-differet-instances/7387)

**Comment by gastonbesada** [comment]
@mhartington Mike, I'm having same issue in 1.0.0-beta.14-nightly-964. Could you please, help to solve this issue?

Thanks!

**Comment by danfaber** [comment]
I had an issue with this and used this workaround which does not involve modifying the ionic source:

Give each slide a unique id which can be an angular binding.
Then you just need to filter on the $ionicScrollDelegate instances collection to get the one which has an element with the id you're looking for on.

Here's a quick copy and paste of my code in case it helps:

     <ion-slide ng-repeat="page in pages" active-slide="page">

                <ion-content id="{{page.name}}">

...

            $scope.getScrollPosition = function (page) {

            var instances = $ionicScrollDelegate["_instances"];

            var instance = _(instances).find(function(ins) {
                return ins.$element[0].id === page.name;
            });

            console.log(JSON.stringify(instance.getScrollPosition()));
        };

**Comment by panurge-ws** [comment]
An universal directive to use random-generated delegate-handle (inspired to @mikesurowiec ) :

    angular.module('app').directive('randomDelegateHandle', [function () {
      return {
        priority: 1000,
        restrict: 'A',
        compile: function compile(tElement, tAttrs, transclude) {
            tAttrs.$set('delegateHandle', Math.random().toString(36).substring(7));
            return function postLink(scope, iElement, iAttrs, controller) {}
        }
    };
}]);

use:

    ion-content random-delegate-handle

**Comment by steveoc64** [comment]
Still appears to be messy using 1.0.0-rc.1

danfaber's comment above was really useful in working out what the problem is, but the find() fn is not totally portable it seems :(

I just created a very simple service to manage jumping between tabs in my application (which has lots of nested tabs, and breaks quickly using ionic's built in tab delegate functions). 

A horrible solution perhaps .... but this is working very reliably for me at the moment, and it bypasses any need to touch the underlying ionic libs.  The code below is verbose and non-optimal, but its easy to reason about, and portable.

```javascript
// A fix for broken ionic tabs delegate

.factory('$tabs', ['$ionicTabsDelegate', function($ionicTabsDelegate) {
  return {
    get: function(handle) {

      var tabs = $ionicTabsDelegate._instances
      var theTab = undefined

      // Manually walk ionic's internal array of tabs, and find the matching tab
      // use angular's built in array iterator for best portability
      angular.forEach(tabs, function(v,k){
        if (v.$$delegateHandle === handle) {
          theTab = v
        }
      })
      return theTab
    },
    select: function(handle,position) {
      console.log('tabs select',handle,position)

      var theTab = this.get(handle)
      if (theTab !== undefined) {
        theTab.select(position)
      }
    }
  }
}])
```

Usage : 

```html
<ion-tabs delegate-handle="MainTabs">
 ....   lots of tabs in here
</ion-tabs>
```
```javascript

.controller('myExamplecontroller', ['$tabs', function($tabs) {
    return {
       showFirstTab:  function() {
           $tabs.select('MainTabs',0)
       },
       showSecondTab:  function() {
           $tabs.select('MainTabs',1)
       },
      // etc
    }


}])

**Comment by ringo22** [comment]
I think it find a possibility for solve this error "Delegate for handle "my-handle" could not find a corresponding element with delegate-handle..."

This possibility is caused why $ionicSideMenuDelegate.$getByHandle('menuLeftHandle')._instances is a Array
<code>
$ionicSideMenuDelegate.$getByHandle('menuLeftHandle')._instances[n]. anyMethod()
</code>

**Comment by privetr** [comment]
Problem is still existing, why this is closed ?

**Comment by saideldah** [comment]
Hello 
is this issue solved?

i still have same problem with generated delegate-handle 

this is  my code
JS Controller
`
$scope.swapName = "swap00";
    $scope.ds = function (sN) {
      $ionicSlideBoxDelegate.$getByHandle(sN).enableSlide(false);
    };
`
HTML
`
<ion-slide-box show-pager="false" delegate-handle="{{swapName}}" ng-init="ds(swapName)">
                 <ion-slide >
1
                 </ion-slide>
                 <ion-slide >
2
                 </ion-slide>
                 <ion-slide >
3
                 </ion-slide>
</ion-slide-box>
`

i get this message:
Delegate for handle "swap00" could not find a corresponding element with delegate-handle="swap00"! enableSlide() was not called!
Possible cause: If you are calling enableSlide() immediately, and your element with delegate-handle="swap00" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to enableSlide() and try again.

**Comment by karjajuu** [comment]
I had a similar problem and asked it in StackOverflow and got a great temporary solution to the problem. See it at [StackOverflow](http://stackoverflow.com/a/38023914/2003702)

**Comment by thepi0** [comment]
I had a similar problem and asked it in StackOverflow and got a great temporary solution to the problem. See it at [StackOverflow](http://stackoverflow.com/a/38023914/2003702). Hopefully this can help someone in the future.

**Comment by DHclly** [comment]
Address:[ionicframework](http://ionicframework.com/docs/api/directive/ionSlideBox/)
I think we are use in wrong, look at the API , the attr `delegate-handle`  accept value type is `string`, not `expression` ,  but I think the type of string  is not suitable.

*hope you can understand what I said. ^-^*

**Comment by yacaeh** [comment]
Based on @thepi0 's Link I could solve this problem. For someone who needs help, share code here. You can just put this on your controller. 
To get dynamically created index of the slide box like with ng-repeat  
```
    $scope.getSlideBoxDelegateHandle = function(delegateIndex) {
        //get all the instances that ionic scroll delegate is handling
        var instances = $ionicSlideBoxDelegate["_instances"];
        //Create Instance you want to get
        var instance = null;
        for (var index in instances) {
            //set DelegateHandle value with your index
            //Ex) instances[index].$$delegateHandle = "slidebox"+index;
            //or just instances[index].$$delegateHandle = index;
            instances[index].$$delegateHandle = index;
            if (index == delegateIndex) {
                instance = instances[index];
            }
        }
            return instance; //return the instance        
    }
```



usage
HTML

` <div class="list" ng-repeat="myIndex in dynamics>
<ion-slide-box delegate-handle="{{myIndex}}">`

JS

 ` $scope.slideIndex = $scope.getSlideBoxDelegateHandle(myIndex).currentIndex or anymethod;`

**Comment by eternalsayed** [comment]
I fixed mine with a custom function with help from @yacaeh 's code above. Basically, instead of comparing indexes, I compared the HTML object of the passed ion-content from the ones available under $ionicScrollDelegate list. Works like charm for me.

```
function getScrollDelegate(element, $ionicSlideBoxDelegate) {
  var instances = $ionicSlideBoxDelegate["_instances"];
  //Create Instance you want to get
  var instance = null;
  for (var index in instances) {
    //set DelegateHandle value with your index
    //Ex) instances[index].$$delegateHandle = "slidebox"+index;
    //or just instances[index].$$delegateHandle = index;
    instances[index].$$delegateHandle = instances[index].$$delegateHandle || index;
    if (instances[index].$element[0] == element[0]) {
      instance = instances[index];
    }
  }
  return instance; //return the instance
}
```
And in my directive, I called it like below:
```
      var $scroll = $('.scroll-content', el.parent());//selector to get the ion-content element in current view
      vm.prevTop = 0; 
      var handle = getScrollDelegate($scroll, $ionicScrollDelegate);//gets the handle
      $scroll.on('scroll', function (e) {
         var pos = handle.getScrollPosition();
         var cl = pos.top>vm.prevTop ?'go-down' :'go-up';
         $(button).removeClass('go-down go-up').addClass(cl);
     })
```
