### ISSUE TITLE
ion-infinite-scroll doesn't scroll smoothly

### ISSUE THREAD

**Issue by mjason3** [driftyco/ionic#1866]
the ion-infinite-scroll automatically enable an refresh icon at the top. it will result in the whole list push down and then get back to the original position(because of the refresher's appear and disappear).
I already had a workaround to remove that refresher, but it will be better if you can provide some options to disable it officially.
<code>var infiniteElement = document.getElementsByTagName('ion-infinite-scroll')[0];
                    infiniteElement.removeChild(infiniteElement.childNodes[0]);</code>

**Comment by zhangxp2017** [comment]
any updates?

**Comment by zhangxp2017** [comment]
ion-infinite-scroll
