### ISSUE TITLE
feat: Align io-radio horizontal

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#1870]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It is possible to align io-radio in horizontal? (like button-bar ...)

Same thing to io-checkbox.

Thanks
Baltazar</span>

<span is-issue-template></span>

**Comment by asadwaheed1** [comment]
can you post your solution? @baltazaroliveira I am trying to achieve something like [this](http://i.imgur.com/lfLbYRJ.png)

**Comment by baltazaroliveira** [comment]
I don´t know if works. This code has written in Ionic 1.




            <div class="item item-divider">
                Ordenação
            </div>

            

            <table style="width:100%">
                <tr>
                    <td ng-repeat="item in Ordenacoes | filter: FiltroIonRadios" style="width:50%">

                        <ion-radio ng-value="item.value" ng-model="data.OrdenacaoSeleccionada" ng-change="OrdenacaoTablet_Change(item)">
                            {{ item.text }}
                        </ion-radio>
                    </td>

                </tr>

            </table>
            <div class="item item-divider">
                Ordenação
            </div>

            

            <table style="width:100%">
                <tr>
                    <td ng-repeat="item in Ordenacoes | filter: FiltroIonRadios" style="width:50%">

                        <ion-radio ng-value="item.value" ng-model="data.OrdenacaoSeleccionada" ng-change="OrdenacaoTablet_Change(item)">
                            {{ item.text }}
                        </ion-radio>
                    </td>

                </tr>

            </table>
