### ISSUE TITLE
bug: Anti-aliasing not working

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic#1880]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>- See question in stackoverflow for screenshot: http://stackoverflow.com/questions/24692554/weird-pixels-everywhere-in-phonegap -

The thing is that I have one device - HP Slate 8 Pro - that's showing weir d pixels everywhere on the app. By then, as I wasn't sure "who's fault is it" I posted that in stackoverflow.

But today I just tried to create a new cordova project (without ionic) and it was working fine. I checked the viewport metatags and bam!
"target-densitydpi=device-dpi"

Put that in my ionic project and the bug is gone. But! my application now is unusable, because the header it's less than a quarter inch, everything is just "scaled down".

So it looks like, for some reason in this device, dpi resizing doesn't work properly. And it looks like an anti-aliasing problem.

And this only happens in hybrid app mode, if I open the project with chrome (in the device), it gets scaled properly and without the pixel glitch.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, looking into this more, I had something similar in older android webviews (4.1-4.3) adding crosswalk did fix the issue. It may just come down to the older webview.

**Comment by voliva** [comment]
IMO, "Adding crosswalk did fix the issue" is no reason to close it.
I just assume that you won't fix it, and I can understand because it doesn't happen that much, so spending resources in this is useless.

Just keep in mind that crosswalk is not the ultimate solution to all Android 4.3- devices. Adding almost 40MB to an apk is not really useful, as PlayStore limits apk sizes to 50MB (then you have to use an expansion apk). Then why don't you just say "Ionic only supports iOS 7+ and Android 4.4+"?
If you can't fix an issue, just please, don't say that the fix is adding crosswalk. Crosswalk is awesome, yes, but it's just a workaround.

Also, as I demonstrated, this bug also happens in desktop chrome. Who knows if in the next version of Chromium this doesn't reappear?

**Comment by mhartington** [comment]
Oh for sure, crosswalk isn't a solution, but it does at least mend the issue. 
I did switch to use native scrolling (which is what doing for android moving forward) and it helped a bit, but there were still some scrolling artifacts.

So while I scroll-view could cause issues, switching to native scrolling still produces the issue.

**Comment by javray** [comment]
I had the same issue with android 4.1.2 and 4.2.2 and adding ion-content overflow-scroll="true" resolved the issue:

<ion-content overflow-scroll="true">
...

Hope it helps you.
