### ISSUE TITLE
bug: dynamically built slideBox with ng-repeat does not continue when flag is set

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic#1890]
```
<ion-slide-box does-continue="true">
   <ion-slide ng-repeat="item in items">
      <div>stuff</div>
   </ion-slide>
</ion-slide-box>
```

**Comment by tannerlinsley** [comment]
For anyone still having issues with dynamic or asyncronous, I have an awesome directive.

```html
<ion-slide ng-repeat="feature in featured" dynamic-slides="featured">
    <div ng-bind-all-html="feature.content"></div>
</ion-slide>
```

```javascript
module.directive('dynamicSlides', function() {
    return {
        require: ['^ionSlideBox'],
        link: function(scope, elem, attrs, slider) {
            scope.$watch(function() {
                return scope.$eval(attrs.dynamicSlides).length;
            }, function(val) {
                slider[0].__slider.update();
            });
        }
    };
});
```

**Comment by keithdmoore** [comment]
This looks like a good workaround.  Seems like a watch on the "featured" array length with a call to $ionicSlideBoxDelegate.update() would be cleaner.   I currently call the $ionicSlideBoxDelegate.update() upon receiving data from a http request.  However, I have not tried it in the current beta14 version.

**Comment by tannerlinsley** [comment]
It would look cleaner but this ensures the directives portability and in the case of nested slide boxes (I hope not) you would not have to specify the delegate name.

**Comment by tannerlinsley** [comment]
And to complete the implementation, this will make the slide box adjust to the slide height (so long as the slide takes up space eg. no absolute positioning)

```html
<ion-slide-box dynamic-height>
    <ion-slide ng-repeat="slide in slides" dynamic-slides="slides">
        {{slide}}
    </ion-slide>
</ion-slide-box>
```

```javascript
module.directive('dynamicHeight', function() {
    return {
        require: ['ionSlideBox'],
        link: function(scope, elem, attrs, slider) {
            scope.$watch(function() {
                return slider[0].__slider.selected();
            }, function(val) {
                var newHeight = $('.slider-slide', elem).eq(val).innerHeight();
                if (newHeight) {
                    elem.animate({
                        height: newHeight + 'px'
                    }, 500);
                }
            });
        }
    };
});
```

**Comment by severedsea** [comment]
Still experiencing @keithdmoore 's issue on:
(1) duplicate static slide boxes as well as...
(2) does-continue="true" not working when ng-repeat starts off as empty list of array then dynamically adding slides after data was retrieved from server, even after calling $ionicSlideBoxDelegate.update().

I'm using v1.0.0-rc.3-nightly-1215

**Comment by sh3nan1gans** [comment]
@tannerlinsley - nice directive! I'm going to implement that in my current app. 
I did run into an issue when pushing new slides to my ng-repeat where the new slide would render below the slide-box before update was called. I don't think this would be a problem if my slide-box filled the entire view.
If anyone runs into this issue I came up with a hack to make sure that each slide starts off with a width of zero before Ionic styles the slide.

        <ion-slide ng-repeat="url in urls track by $index" dynamic-slides="urls" style="width: 0px"></ion-slide>

**Comment by tannerlinsley** [comment]
I've re factored it since. I'll try and repost it.

**Comment by tannerlinsley** [comment]
```javascript 
(function() {

    var module = angular.module('novi.utils');

    module.directive('watchSlides', function($interval, $timeout) {
        return {
            restrict: 'A',
            require: 'ionSlideBox',
            link: function(scope, el, attrs, slider) {

                var index = 0;

                var activeWatcher = scope.$watch(function getActiveSlide() {
                    index = slider.__slider.selected();
                    return [index, slider.__slider.count()];
                }, changeSize, true);


                scope.$watch(function() {
                    return _.size(scope.$eval(attrs.watchSlides));
                }, function(val) {
                    slider.__slider.update();
                });

                var interval = $interval(changeSize, 1000);

                // Cleanup
                scope.$on('$destroy', function() {
                    activeWatcher();
                    $interval.cancel(interval);
                });



                function changeSize() {

                    return;

                    if (!el[0].querySelectorAll('.slider-slide').length) {
                        return;
                    }

                    var newHeight = el[0].querySelectorAll('.slider-slide')[index].scrollHeight;
                    if (newHeight) {
                        $timeout(function() {
                            el.css({
                                height: newHeight + 'px'
                            });
                        });
                    }
                }


            }
        };
    });
})();
```

**Comment by tannerlinsley** [comment]
It's a little rough around the edges. Don't know how i feel about the interval. But it seems to work nicely.

**Comment by tannerlinsley** [comment]
Also the watch slides attribute may need to be deep watched or just watch the length of the array. Tweak as needed

**Comment by hkalancheung** [comment]
solved by putting an ng-if on slide-box
http://forum.ionicframework.com/t/slidebox-does-continue-doesnt-work-on-ipad/14831/4
