### ISSUE TITLE
bug: firefox os simulator 1.3 bug on-tap on-hold

### ISSUE THREAD

**Issue by Dahevos** [driftyco/ionic#1894]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>For FirefoxOS only : It seems that "on-hold" have some implementation problem. 

Simple code :

<div class="row" on-hold="onHold(category)">
                    <div class="col col-80 verticalCentered" on-tap="onTap(category)" ng-show="!category.isEditing">{{category.title}}  </div>
...
</div>

How to reproduce :
- I have two div with two event : on-tap and on-hold.
on-tap display the event and on-hold edit it.
On android, iOS or even firefox browser, no problem : on tap and on hold is two distinct event.
On firefoxOS (simulator 1.3, but same for 2.0, don't know if it's same on a firefox os mobile), when I tap the screen (one click), it seems that on-hold event is fired instead of on-tap.

Video :
https://www.youtube.com/watch?v=CkXWCc4BkeE&feature=youtu.be</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Sorry, we've decided we wont support Firefox OS.
