### ISSUE TITLE
bug: contenteditable pushed under status bar on iOS

### ISSUE THREAD

**Issue by emertechie** [driftyco/ionic#1898]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Tapping into a contenteditable div on iOS causes the whole content area to be pushed up under status bar on iOS. Doesn't happen on Android. This is using the default Ionic scrolling.

Can see the different behaviours here: http://codepen.io/emertechie/pen/rwjot?editors=100

Note that replacing contenteditable divs with text inputs doesn't show same issue.

I did see the earlier issue related to content under status bar (https://github.com/driftyco/ionic/issues/932) but I am using the new Ionic keyboard plugin and still happening :(

FYI I logged another (related?) bug to do with contenteditable divs earlier: https://github.com/driftyco/ionic/issues/1897</span>

<span is-issue-template></span>

**Comment by meparashar** [comment]
@mhartington can you please let me know how and where to add this function. I tried adding it to my controller but got the error that cordova is not defined. I can see the cordova.js in my index.html file and also in platform ios folder. but still getting the error.

**Comment by mhartington** [comment]
@meparashar you would add this in your run phase.

**Comment by meparashar** [comment]
@mhartington I've added it there only but getting the error.

Here's my run function:

`angular.module('starter', ['ionic', 'starter.controllers', 'starter.services','ngMessages','artishan.bespoke'])
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
	cordova.plugins.Keyboard.disableScroll(true);
	  
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleLightContent();
    }
  });
})`

do you feel there's anything wrong in it.

**Comment by mhartington** [comment]
move it inside the keyboad if statement

```
angular.module('starter', ['ionic', 'starter.controllers', 'starter.services','ngMessages','artishan.bespoke'])
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);
    }
    
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleLightContent();
    }
  });
})
```

**Comment by meparashar** [comment]
when i put inside if statement, cordova error isn't coming but my header bar is still moving and doesn't remain fixed on input. other than this, do i need to apply any other setting in my controller or elsewhere?

thanks for your help.

**Comment by mhartington** [comment]
Make sure you have the keyboard plugin installed. 
With out seeing any code/project, its hard to know what the issue is. 
Take some time to make sure you have everything set up correctly. 
Providing a codepen demo of a similar setup helps as well. 

Please open a new issues for this. We will continue the conversation there.

**Comment by meparashar** [comment]
Sure. #3914 Thanks.
