### ISSUE TITLE
Extremely Slow Transitions To and From a Page With 100+ ng-repeat Items

### ISSUE THREAD

**Issue by allenakinkunle** [driftyco/ionic#1909]
I am using the latest release of Ionic with the latest release of Cordova. My app has a view which is populated with 100+ items using ng-repeat. When a user taps on an item, the page slides to a details view for that item.

I am having serious issues with responsiveness on Android and iOS 4. There is a 2+ second delay to transition to the detail view and 3+ seconds back to the list view.

**Comment by onigetoc** [comment]
I observed that collection repeat do not work when using native scrolling.
