### ISSUE TITLE
bug: Inline labels do not work properly

### ISSUE THREAD

**Issue by moroshko** [driftyco/ionic#1919]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Consider the following inline labels with right alignment:

    <ion-content>
      <div class="list padding">
        <label class="item item-input">
          <span class="input-label">Name</span>
          <input class="text-right" type="text" ng-model="name">
        </label>
      </div>
    </ion-content>   

When the screen is narrow (320px), the text in the input is outside of the screen:
http://dl.dropbox.com/u/1893981/Screenshots/epks.png

[CodePen](http://codepen.io/anon/pen/spbkc)

How could I fix this?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
fixed in d68ecc16b729ad361a655c1050aa03fe22aef137
