### ISSUE TITLE
bug: Animcations in 4.8.1 errors: "undefined is not a function (near '...element.animate...')"

### ISSUE THREAD

**Issue by morganswood** [driftyco/ionic#19205]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Navigation animations do not load correctly, ie: modals don't render and some navigations have choppy or non-existent animations.

**Expected behavior:**
Modals should load correctly and navigation should animate correctly.

**Steps to reproduce:**
Modals created do NOT animate or open properly.

**Other information:**
We reverted to 4.7.4 and the animations work and modals are now working correctly again.

**Ionic info:**
```Ionic:

   Ionic CLI                     : 5.2.6
   Ionic Framework               : @ionic/angular 4.7.4 (/Users/morgan.wood/Source/CRM_WebApp/node_modules/@ionic/angular)
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9 (/Users/morgan.wood/Source/CRM_WebApp/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 1.2.3 (/Users/morgan.wood/Source/CRM_WebApp/node_modules/@ionic/angular-toolkit)

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1 (/Users/morgan.wood/Source/CRM_WebApp/node_modules/@capacitor/core)

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.9.0 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.3 Build version 10G8
```

**Comment by adamduren** [comment]
@liamdebeasi Noticed this in production through our error reporting service for Safari browsers.  Seems to be partially fixed in `@ionic/angular@4.9.0-dev.201908281552.5dcb9be`.

The explicit error on `.animate` being undefined no longer exists but my modal that is presented auto dismisses now. This behavior is not present on `4.7.4`.

I will attempt to reproduce it in a starter project although I suspect it has to do with the fact that I 'm presenting two modals on top of each other.

**Comment by adamduren** [comment]
Unable to reproduce in a starter project. Reverting to 4.7.4 for now until I am able to investigate further.

**Comment by liamdebeasi** [comment]
Ok no problem. When you're able to reproduce feel free to open a new issue, and we can continue the conversation there. Thanks!

**Comment by goelectricstations** [comment]
same issue on 4.9.0 only if run on device from xcode

**Comment by liamdebeasi** [comment]
@goelectricstations This issue has been closed. Please create a new issue if you are experiencing further problems. Thanks!
