### ISSUE TITLE
bug: Android 4.1.2 - Input with text-align right

### ISSUE THREAD

**Issue by wrwonrath** [driftyco/ionic#1929]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>device</span>

<span ionic-description>Just follow:

$ ionic start myApp tabs
$ ionic platform add android

On tab-dash.html

```
<ion-view title="Dashboard">
  <ion-content class="has-header padding">
    <h1>Dash</h1>
      <div class="list">
          <label class="item item-input">
              <input type="text" placeholder="First Name">
          </label>
          <label class="item item-input">
              <input type="text" placeholder="Last Name">
          </label>
          <label class="item item-input">
              <span class="input-label">Metragem <em>(m2)</em></span>
              <input style="text-align: right" type="number" name="metragem" min="1" placeholder="0,00" ng-model="data.metragem" required />
          </label>
      </div>
  </ion-content>
```

When I put style "text-align: right" run it on a Android 4.1.2 device and click on the input field the label disappears (goes to the side). 

Best regards.

Wilton Ruffato Wonrath</span>

<span is-issue-template></span>

**Comment by gnasit** [comment]
is this issue resolved, cuz it's not working correctly for me on ios?

**Comment by gnasit** [comment]
i have two inputs, one of type number, the other of type date. the label shifts outside the viewing area on the left for input type number, and the entered date shifts outside viewing area on the right for input type date.

**Comment by mhartington** [comment]
@gnasit please make a new issue and a provided demo to test against

**Comment by gnasit** [comment]
i can't do a demo as this does not happen in the emulator or the browser. it happens after i put it on iOS via ionic's webview... do you still want me to create a new issue?

**Comment by mhartington** [comment]
http://blog.ionic.io/live-reload-all-things-ionic-cli/

We can start apps from codepen. Please create a new issue with a codepen.

**Comment by gnasit** [comment]
i had added a new issue: [https://github.com/driftyco/ionic/issues/5522](url)
