### ISSUE TITLE
bug: textarea in ion-item collapses when list scrolled

### ISSUE THREAD

**Issue by zapatek** [driftyco/ionic#1934]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When there is a textarea (higher than single row) in an ion-item within an ion-list, and if the textarea has focus (keyboard showing) and the ion-list is scrolled, then the textarea collapses into a single row while scrolling is on and the bar is visible. The moment the scrolling stops (scroll bar fades) the text area is enlarged to its actual height again.

As an additional problem, when the textarea is large and by itself not scrollable (overflow:hidden) and has focus, then the ion-list also cannot be scrolled by dragging within the textarea either. The list has to be dragged by tapping some place outside the textarea. But if the textarea is very large covering the whole screen, then this becomes a big limitation when trying to edit portions of the textarea that fall outside the screen.</span>

<span is-issue-template></span>

**Comment by dargonar** [comment]
@samal84 solution works for me.

**Comment by scmsystm** [comment]
Can we use `focusInput.cloneNode()` at `js/utils/tap.js:191` rather than create new element then clone focused input style?

In my case, if textarea height was set in css then modified by javascript, the cloned  textarea height are not  equal to newly modified height. (an auto-growing textarea that height modified by scrollHeight itself).

I modify the `js/utils/tap.js:184` `cloneFocusedInput` function like this and the cloned input just fine.
But, I don't really know about the performance.
```javascript
  cloneFocusedInput: function(container, scrollIntance) {
    if (ionic.tap.hasCheckedClone) return;
    ionic.tap.hasCheckedClone = true;

    ionic.requestAnimationFrame(function() {
      var focusInput = container.querySelector(':focus');
      if (ionic.tap.isTextInput(focusInput)) {
        var clonedInput = focusInput.cloneNode(true);
        if (clonedInput) {
          clonedInput.value = focusInput.value;
          clonedInput.classList.add('cloned-text-input');
          clonedInput.readOnly = true;
          if (focusInput.isContentEditable) {
            clonedInput.contentEditable = focusInput.contentEditable;
            clonedInput.innerHTML = focusInput.innerHTML;
          }
          focusInput.parentElement.insertBefore(clonedInput, focusInput);          
          focusInput.classList.add('previous-input-focus');
          
          clonedInput.scrollTop = focusInput.scrollTop;
        }
      }
    });
  }
```
