### ISSUE TITLE
page scroll breaks on ios when tapping input

### ISSUE THREAD

**Issue by andrasz** [driftyco/ionic#1935]
In a newly created sidemenu project, if an input is readonly the scrolling brokes after a tap on the input. 
The scrolling also breaks when adding a event handler for the click or focus events on the input and triggering blur event inside the handler to prevent the soft keyboard to pop up.

**Comment by adamdbradley** [comment]
I'm not able to replicate this problem with the nightly build. This may have already been fixed.
