### ISSUE TITLE
Collection-repeat and input type checkbox

### ISSUE THREAD

**Issue by superallen** [driftyco/ionic#1940]
I have a collection of contacts and I generate an ion-item for each contact using collection-repeat. Each ion-item has a span, a paragraph and a checkbox element within it. I chose to use collection-repeat over ng-repeat because it increases performance.

I understand that collection-repeat only renders the items that can fit the screen at once and renders more as we scroll.

The problem I have is that when I click a checkbox within an item, for example, the first one, and scroll down to see more lists, another checkbox within an item lower in the list would also be checked automatically. This is not the intended behaviour as I want users to be able to check a checkbox for every item.

These pictures will make the explanation clearer:

![eas](https://cloud.githubusercontent.com/assets/2054408/3836127/4e76ab28-1dcd-11e4-88fe-0dfb8261adff.jpg)

Why is my list showing this behaviour? Does it have to do with how collection-repeat works or is it a problem with my code? This is really killing me and I need to find answers. Thanks!

**Comment by mrameezraja** [comment]
@superallen were you able to fix this issue ?

@mhartington  this issue still exists in beta 14 :(

**Comment by ajoslin** [comment]
So the problem is that collection-repeat reuses elements as you scroll down the list. A checked checkbox will still be checked once it scrolls out of view.. unless you tell it not to be checked with a condition.

You should use ng-checked, not be updating the checkbox manually.

```html
<input type="checkbox" ng-click="update($event, contact.phoneNumber)" ng-checked="isChecked(contact.phoneNumber)">
```
