### ISSUE TITLE
feat: Reorder button pushes label text out of the list

### ISSUE THREAD

**Issue by Justin-Credible** [driftyco/ionic#1952]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The default behavior of the list control (as far as I can tell) pushes the label text of the list items off of the left side when the re-order button is present. I can understand moving the label text to the right when the delete button is shown is important, but when the re-order button becomes visible, it causes the label text to be cut off on the left side of the list item.

This is a problem for me because we need to have a list whose items always have the re-order button visible (not conditionally enabled) and this makes it impossible to read the item text because it will always be cut off.

This is easy to see on the default sample for the list by simply clicking the re-order button:
http://codepen.io/ionic/pen/JsHjf

Is there a way to prevent the item text from being pushed off of the left side of the list item when the re-order button is visible?</span>

<span is-issue-template></span>

**Comment by Yuripetusko** [comment]
Thanks @broberson

**Comment by chasys** [comment]
@broberson I have a simpler fix.


    .list-right-editing .item-right-editable .item-content, .item-right-editing.item-right-editable .item-content {
    	-webkit-transform: none;
    	transform: none;
    }
