### ISSUE TITLE
Handling In-Call status bar

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1961]
Right now if an iphone receives a call while an app is running, the status bar bar pushes the entire view down an additional 20px. Anything we can do about that?

**Comment by raoabishay** [comment]
@mhartington : This issue is occurring to me now! I'm on iOS 9.3. Any way to fix this? My header bar contains icons that are unclickable when I'm on a call!

**Comment by raoabishay** [comment]
Can anyone help me find a solution for this? This problem very much exists right now!

**Comment by raoabishay** [comment]
For anyone having an issue with this, try including the following in your "config.xml" file and see if it solves the issue:
` <preference name="StatusBarOverlaysWebview" value="false"/>
  <preference name="StatusBarBackgroundColor" value="#e73834"/>
  <preference name="StatusBarStyle" value="lightcontent" />`
This solved it for me on iOS 9.3
