### ISSUE TITLE
button-full does not work in ion-footer-bar

### ISSUE THREAD

**Issue by chadcampbell** [driftyco/ionic#1964]
Buttons with the class <code>button-full</code> do not render properly when included in an <code>ion-footer-bar</code>. For instance:

```
<ion-footer-bar>
  <div class="buttons">
    <button class="button button-full">Button 1</button>
  </div>
  <h1 class="title">Title</h1>      
  <div class="buttons" ng-click="doSomething()">
    <button class="button">Button 2</button>
  </div>
</ion-footer-bar>   
```

**Comment by anshulklr** [comment]
@i'm facing the same issue when the app is opened in tablet. The button in footer doesn't come as required. The button is a very small

**Comment by mhartington** [comment]
This is another alternative.
Other than this, you will have to write your own css for this. 

http://codepen.io/mhartington/pen/bdGNGr

**Comment by anshulklr** [comment]
@mhartington the button works weel in all the devices with my css. just like it doesn't support in the tablet? Any idea about this ?

**Comment by mhartington** [comment]
could you open a new issue for this.

**Comment by anshulklr** [comment]
yeah i'll

**Comment by lizjulien** [comment]
work for me with this css class tricks :

```html
    <div class="bar bar-footer bar-positive footer-button">
        <a class="button button-full button-clear button-icon icon ion-chevron-right" href="#/plop">
            A full link in bottom
        </a>
    </div>
```

```css
div.footer-button a.button.button-full {
    width:100%;
    margin-top: 0
}
```

**Comment by svamja** [comment]
@mhartington that tab hack is cool. I just made a minor change of adding tab-item-active class .. and its exactly what I needed. Thanks!

    <ion-footer-bar class="bar-positive tabs tabs-stable">
      <a class="tab-item tab-item-active">
        Add Contact
      </a>
    </ion-footer-bar>

**Comment by niksajanjic** [comment]
I added my button at the bottom like this:

<ion-footer-bar>
    <button class="bar bar-footer bar-positive" ng-click="closeModal()">
      <p class="title">Filter<p>
    </button>
</ion-footer-bar>

You can even get rid of button tag and make your ion-footer-bar pretend to be a "button" by passing ng-click to it:

<ion-footer-bar class="bar-positive" ng-click="closeModal()">
    <p class="title">Filter<p>
</ion-footer-bar>

But it should be a better way to achieve this.

**Comment by TkachenkoAptem** [comment]
Mb, not good idea, u can use $rootScope

`
<ion-footer-bar>
  <button class="bar bar-footer bar-positive" ng-click="closeModal()"></button>
</ion-footer-bar>
`

`
 $rootScope.closeModal = function ( ) {
 }
`
