### ISSUE TITLE
Scrollview getting pushed out of view

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1968]
With a long list and some select elements, if you target on, then use the keyboards "<" and ">" to go to the next one, the scroll view gets pushed out of view, even with scroll disabled.

[Relative youtube video][1]

codepen
http://codepen.io/mhartington/pen/HiaFq

[1]: http://youtu.be/2dNCQK11vaw

**Comment by Ionitron** [comment]
Hello human. Is this still a problem?

**Comment by mhartington** [comment]
This is still an issue with beta 14

**Comment by ajoslin** [comment]
This is because when the browser focuses something it scrolls to the focused element.

This will be fixed when we switch to native scrolling.  Until then, I don't care about this that much because it's desktop-only.

**Comment by ajoslin** [comment]
Oh, by `se the keyboards "<" and ">"` you mean the above-the-keyboard arrows on iOS's keyboard.

That's still very difficult to fix, since it uses native scrolling. It's possible, though...

**Comment by tlancina** [comment]
@mhartington is this an issue for both JS and native scrolling?

**Comment by mhartington** [comment]
Can't replicate this anymore. Closing for now, but keeping an eye out.
