### ISSUE TITLE
bug: Scroll SVG element inside ion-scroll

### ISSUE THREAD

**Issue by grillorafael** [driftyco/ionic#1989]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys, I am trying to make this work but it simply does not.

I'm trying to fit a svg map inside my ion-scroll so I can drag the map and pinch to zoom. When I use the <img> tag everything works fine but I need to use the <object> tag because I manipulate the map's DOM.

Any tips?

```
<ion-scroll zooming='true' direction='xy'  style='width: 100%; height: 100%;' class='has-header'>
    <!-- <img src="map/pucrj.svg" alt="" /> -->
    <object id="E" type="image/svg+xml" data="map/pucrj.svg">
        <param name="src" value="map/pucrj.svg">
    </object>
</ion-scroll>
```

Any ideas? It simply does not scroll...like the drag action is not working.</span>

<span is-issue-template></span>

**Comment by mkavn** [comment]
Thanks! This was exactly what I was looking for.
