### ISSUE TITLE
bug: Memory is leaking between page transitions

### ISSUE THREAD

**Issue by jbasinger** [driftyco/ionic#1993]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My team and I are having a memory leak issue. Initially we thought it was ui-router, so I made this plunker to test it out http://embed.plnkr.co/rtIGJCG5ahlocHJ0gdmb/preview

There was no leak using just ui-router. Then I tried it with Ionic and it seems to be leaking when you go back and forth between the Main and Leak states using $state.go http://embed.plnkr.co/ZpeGhZzLywIIP2RMjYLX/preview

I measured by taking heap snapshots in Chrome Dev Tools and in doing so you can see the Detached DOM tree entries rising and an (array) entry rising considerably. You need a lot of nodes to make a large dent in the memory usage so the Leak state is pretty big. You can recreate what I did by taking a snapshot before going anywhere, then going to the Leak state and then back to the Main state and taking another snapshot and repeating the process a few times. The heap size never falls.

Here is a screenshot of the snapshots, I went back and forth a few times between snaps 3 and 4 to enunciate the leak http://i.imgur.com/0H6WCWf.png

I'm not too sure how to read heap comparisons, so any kind of help or work around would be great.</span>

<span is-issue-template></span>

**Comment by GuoYongxin** [comment]
Any update on this? I also face the same issue.

**Comment by mhartington** [comment]
The existing ticket is #1096, please continue the discussion there.
