### ISSUE TITLE
$ionicPlatform.registerBackButtonAction - allow callback to continue propagation to next handler

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic#1999]
When registering handlers, I would like to allow the callback to say that it shouldn't run and pass the behaviour to the next priority handler (something like continuePropagation).

For example:
I have a handler that closes a popup opened by an external library. If this popup doesn't exist, I want the next priority back button action to be performed.

The alternative would be to deregister the handler whenever the popup is closed, but that means I have to listen to DOM changes and that's too expensive. Much better to do the check inside the handler.

**Comment by danicomas** [comment]
+1
