### ISSUE TITLE
$ionicModal.fromTemplateUrl freezing sometimes

### ISSUE THREAD

**Issue by asterism612** [driftyco/ionic#2011]

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by pmn4** [comment]
I experienced something similar today and realized that the path I passed to `$ionicModal.fromTemplateUrl` did not resolve to an actual file.
