### ISSUE TITLE
Small buttons with icons in button-bar

### ISSUE THREAD

**Issue by nikis** [driftyco/ionic#2023]
When put "button button-small" with icon in button-bar, icon:before line-height:44px is the same as normal button, must be smaller

**Comment by emilyemorehouse** [comment]
I'm having this issue again with the nightly builds in a codepen [here](http://codepen.io/emilyemorehouse/pen/vOgMxL) as well as in a local project with Ionic 1.0.0.

If you uncomment the line-height fix in the codepen, it's fixed as before.

**Comment by mhartington** [comment]
Hmm, alright seeing this as well. Will look into this. Thanks
