### ISSUE TITLE
bug: Image gets blurred when zoomed in ion-scroll

### ISSUE THREAD

**Issue by paishin** [driftyco/ionic#2033]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am using ion-scroll to zoom on an image but when I zoom on it it appears blurred (image resolution is good enough).

I suspect that the image does not get re-rendered when I zoom but instead it just stretches the initially rendered image.

Is there a way we can force the re-rendering?</span>

<span is-issue-template></span>

**Comment by DURK** [comment]
I'm also having this issue. I found out that Android compresses large resolution images even further due to <a href="http://stackoverflow.com/questions/6632140/android-pixel-quality-reduction-in-images-loaded-in-webview?rq=1">this issue</a>. But on iOS this shouldn't be a problem.

I found out that ion-scroll uses zynga and that https://github.com/zynga/scroller/issues/28 is supposed to be the issue that causes the problem. But that issue has been unresolved for over 2 years, so that's not too promising.

Does anyone know a solution to this or know of any alternatives?

**Comment by paishin** [comment]
Very interested to find out alternatives to this as well as this has been
an issue for us for quite some time and I don't see things getting better
any time soon.

**Comment by rasco** [comment]
Don't know if this is a good enough solution for anyone else but in my case I was able to use a PDF file with window.open() and the org.apache.cordova.inappbrowser plugin.

**Comment by DURK** [comment]
Thanks for the suggestion @rasco. In my case that's not gonna work, because I need to interact with the image (placing pins on a map).

**Comment by mhartington** [comment]
Yeah, since this comes from zynga, not sure what can be done here.

But you can use the built in gestures to create your own pinch-to-zoom

http://codepen.io/mhartington/pen/ogpNBM

**Comment by paishin** [comment]
I think the problem is not even zynga related but a webkit issue. Once the image gets into the hardware compositing layer a snapshot is created as a texture and then it is always used at that scale, so zooming results in blurred, low definition text and images. 

A suggestion that I found on the net is to load the image at the maximum zoom level and then zoom out. I havent tried it though.

**Comment by mhartington** [comment]
Hmm, seems like a dirty hack to me. Again, as mentioned in that zygna issue, you could use another image zoom as well.

**Comment by paishin** [comment]
I couldnt agree more, but if indeed is a webkit issue a "dirty hack" might be our only way around it.
The same problem is present in other zoomers as well. (I know iscroll suffers from the same issue as well)

**Comment by augustoice** [comment]
Isso é bem simples de se resolver. Sempre que aplicar zoom ele aplica um blurred na imagem. Corrigi da seguinte forma.

No controller:

 //Zoom Mais
  ionic.on('pinchout', function(e){

      $timeout(function(){          
          //$(document.getElementById('sc1')).find('img').css({'-webkit-transform': 'translateZ(0)'});
          var handle = $(e.target).parent().parent().attr('delegate-handle');
          $ionicScrollDelegate.$getByHandle(handle).zoomTo(10, true, posicao.pageX, posicao.pageY)      
          
        },100);

  }, document.getElementById('sc1'));
  
 

//Doubletap
    var controlador= false;
    ionic.on('doubletap', function(e){
      var posicao= e.gesture.center;

      if(!controlador){       
        
         var handle = $(e.target).parent().parent().attr('delegate-handle');
         $ionicScrollDelegate.$getByHandle(handle).zoomTo(10, true, posicao.pageX, posicao.pageY)        

        $timeout(function(){                           
          //$(document.getElementById('.scrollController')).find('img').css({'-webkit-transform': 'translateZ(0)'});
          //$('.scrollController').find('img').css({'-webkit-transform': 'translateZ(0)'});
          $(e.target).css({'-webkit-transform': 'translateZ(0)'});

        },500);

        controlador=true;
      }
      else{        
          
        $ionicScrollDelegate.$getByHandle(handle).zoomTo(0, true, 0, 0)        

        $timeout(function(){          
          $(document.getElementById('sc1')).find('img').css({'-webkit-transform': 'translateZ(0)'});
          
        },100);  

        controlador = false;
      }
    }, document.getElementById('sc1'));

**Comment by jgw96** [comment]
For english speaking users here is the above translated to english: This is quite easy to solve . Whenever it is zoomed it applies a blurred the image. Here is a solution 

@augustoice Obrigado pela informação e solução !

**Comment by pradeepgill007** [comment]
i want something like this, how could i do this
 
http://i.stack.imgur.com/GpPdW.gif

**Comment by paishin** [comment]
@pradeepgill007, that has nothing to do with this issue or this plugin in general.

**Comment by pradeepgill007** [comment]
@paishin ok, is there any plugin available for this effect in IONIC or in angular.???

**Comment by paishin** [comment]
You dont need any plugins to achieve that effect, just use ionic scroll to increase/decrease the image size based on scroll position.

**Comment by hix41** [comment]
@paishin emm...can you explain how to 'use ionic scroll to increase/decrease the image size based on scroll position.' ?

**Comment by erikig** [comment]
I ran into this issue while trying to display an image in an Ionic v1 ion-scroll container  and was able to address it. I posted my results on StackOverflow:
https://stackoverflow.com/questions/38017052/ion-scroll-blurs-my-image-when-zooming-in-in-ionic-framework

Thanks @paishin @augustoice @DURK
