### ISSUE TITLE
feat: Ionic Popover Position

### ISSUE THREAD

**Issue by stripathix** [driftyco/ionic#2040]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, 
Can you tell me how to configure position of popover.

http://codepen.io/anon/pen/fymeD

Like in above codepen my trigger for popover is at footer, so i want to show popover above footer.... It gets opened but it is outside view.</span>

<span is-issue-template></span>

**Comment by Sabharshin** [comment]
fixed the issue using http://stackoverflow.com/questions/26669651/how-to-show-ionicpopover-by-default
