### ISSUE TITLE
bug: ion-nav-bar wrong position with tabs-top style

### ISSUE THREAD

**Issue by ramsestom** [driftyco/ionic#2041]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>if you take this code:
http://codepen.io/anon/pen/aKgEo

and change line 23 from
`<ion-tabs tabs-style="tabs-icon-top" tabs-type="tabs-positive">`
to
`<ion-tabs tabs-style="tabs-icon-top tabs-top" tabs-type="tabs-positive">`

you will see that, when placed on top, the tab navigation bar appear BELOW the ion-view header. Which doesn't really make sense (we would expect the navigation bar to be completely on top and then, the view header to be under it.)
Also, when the view header is masked, the tab bar doesn't position on the complete top of the page but still position as if there was a view header...</span>

<span is-issue-template></span>

**Comment by Shadowstep33** [comment]
This has been an issue for me recently. What's weird is that the positioning is different for android and ios - on ios the tabs bar goes below the header. In Android it goes nicely in it. I'm using the following markup:

```
<ion-view ng-controller="EditorController" scroll="false">
	<ion-nav-title>
		<div class="tabs-striped tabs-top tabs-color-light">
			<div class="tabs">
			  <a class="tab-item active" href="#/app/overview/summary">
			    Summary
			  </a>
			  <a class="tab-item" href="#/app/overview/plans">
			    Plans
			  </a>
			  <a class="tab-item" href="#/app/overview/calendar">
			    Calendar
			  </a>
			</div>
		</div>
	</ion-nav-title>
    <ion-tabs class="tabs-top">

        <ion-tab title="Summary">
            <ion-nav-view name="summary" scroll="false" can-swipe="true"></ion-nav-view>
        </ion-tab>
        <ion-tab title="Plans">
            <ion-nav-view name="plans"></ion-nav-view>
        </ion-tab>
        <ion-tab title="Calendar">
            <ion-nav-view name="calendar"></ion-nav-view>
        </ion-tab>
        

    </ion-tabs>


	<!-- Global Chat bubble and Editor
	<div id="sticky-chat" ng-if="Users.active_session">
		<div class="avatar" style="background-image: url({{Users.shadow_sessions[Users.active_session].avatar}});"></div>
	</div> -->
	<div ng-include src="'templates/snippets/sideMenu.html'"></div>
</ion-view>
```

I know what I'm doing is a bit unorthodox regarding ion-nav-title but I couldn't get it in the header bar otherwise...
