### ISSUE TITLE
bug: Touch in ion-content with scroll does not work

### ISSUE THREAD

**Issue by kavuri** [driftyco/ionic#2044]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a simple <ion-content> with a button like 
```
<ion-content class="has-header padding">
<button class="button button-block button-large" ng-click="openBrowser('twitter')"><i class="icon ion-social-twitter"></i></button>
</ion-content>
```
The touch events do not work in Android 4.4.4, but click works in PC browser. If scroll is set to false in the ion-content, then touch works. I found in forums with references to this problem, but could not find a working solution/workaround. I cannot set scroll="false", since my content goes beyond the one screen length.
This problem is a blocker</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Understood, but even on a device, if scrolling for Android simply didn't work, we would be able to reproduce it and this would be a highly commented on issue. Let me know if you have a codepen or code sample that reproduces it, but I'm going to close this for now.

**Comment by diegobill** [comment]
:+1:
