### ISSUE TITLE
Keyboard Accessory Bar on iOS7 stops scrolling to top

### ISSUE THREAD

**Issue by BenHall** [driftyco/ionic#2049]
When using the arrows (>) on the Keyboard Accessory Bar on Mobile Safari and Native Application on iOS7 the screen is scrolled but the -webkit-transform on the .scroll is still set to -webkit-transform: translate3d(0px, 0px, 0px) scale(1);.  As such it is impossible to scroll back to the top.

Repo: https://github.com/BenHall/ionic-keyboard-bug
Page in question: https://github.com/BenHall/ionic-keyboard-bug/blob/master/www/templates/tab-dash.html

**Comment by tlancina** [comment]
This is expected behavior, without disableScroll the WebView will automatically scroll the inputs into view.
