### ISSUE TITLE
Snap.js not working with Ionic

### ISSUE THREAD

**Issue by dbaq** [driftyco/ionic#206]
Hi,

I ran into an issue with Ionic. I use snap.js for the side menu.

I got the following code:

```
<div snap-content snap-options="opts">
  <header class="bar bar-header bar-positive">
      <button class="button " ng-click="toggleMenu()">
        <img src="img/icon-menu.svg" alt="&#9776;" />
      </button>
      <h1 class="title">APP</h1>
  </header> 

  <ng-view></ng-view> 
</div> 
```

 and 

```
$scope.toggleMenu = function() {
     snapRemote.toggle('left');
    console.log('toggle menu');
}
```

It works perfectly on chrome but on my iOS simulator and on my nexus 4, the menu does not toggle but "toggle menu" appears in the console.

If I remove ionic from the list:
`angular.module('app', ['snap', 'ionic',..` it is also working.

Any thoughts on that?

Thanks in advance

**Comment by brianfeister** [comment]
For reference, this is [a problem with snapjs](https://github.com/jakiestfu/Snap.js/issues/79) it looks like the library is doing some work that I might consider "dirty" in suppressing DOM event bubbling, and also messing with fixed position among others.  Hopefully that's not too off topic, thought it might help someone else.
