### ISSUE TITLE
Swipe right conflicts with browser history back function

### ISSUE THREAD

**Issue by gpstmp** [driftyco/ionic#2060]
Here is the plunkr with the minimal example: http://plnkr.co/edit/qurjdDgjYIPJaRoGG7ab?p=preview
Steps to reproduce the issue:
1. Open right side menu and click `Main`
2. Open right side menu and click `One`
3. Open right side menu and try to close it with the right swipe (from the most left side of the screen) and you will see strange behaviour. I think that it is related with the browser history and iOS7 go-back-with-right-swipe function (see https://github.com/driftyco/ionic/issues/714)

I think that it can be a bug. At least i want to know any work around to solve this issue. 
Thanks for you work, guys!

**Comment by antoineol** [comment]
Now PWA are in the scope of Ionic, this issue makes sense. Opening the left menu with swipe gesture conflicts with some browsers' navigate back gesture (depending on the browser and exact finger position, the one or the other happens).

On the other side, one could argue that the app is not supposed to override the browser features, i.e. the swipe gesture to open the side menu from any side should not be used. But I'm not really convinced we should just drop it when using Ionic for PWA. I would say the debate is still open :)

Any thought on that point?
