### ISSUE TITLE
Have card items (images, etc.) resized to fit content height

### ISSUE THREAD

**Issue by hsdk123** [driftyco/ionic#2080]
```
<ion-content scroll="false" has-header="true" padding="true" >
    <div class="card">

        <div class="item item-avatar">
            <!--<img src="avatar.jpg">-->
            <h2>Pretty Hate Machine</h2>
            <p>Nine Inch Nails</p>
        </div>

        <div class="item item-image" style="height: auto">
            <img class="" src="images(red)/00_Fool.jpg" >
        </div>

        <a class="item item-icon-left assertive" href="#">
            <i class="icon ion-music-note"></i>
            Random Comment
        </a>

    </div>
</ion-content>
```

I asked this question a long time ago and at the time I was told that this was just a common problem with css and html. I've recently been getting replies from others asking me if I had a solution - I feel this functionality really has a strong need.

Here are threads asking for the same:
http://forum.ionicframework.com/t/how-to-get-card-image-automatically-resized-to-content-height/2501

http://forum.ionicframework.com/t/how-to-stretch-card-to-fill-the-entire-content/2597/7

**Comment by LebToki** [comment]
+1
