### ISSUE TITLE
Hardware back button jumps to previous page even with hidden back button

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#2084]
Even if `hide-back-button="true"` is set on the `ion-view`, pressing the hardware back button will still jump to the previous page.

**Comment by msalman** [comment]
Hi, 
I have a simple login based application in which user can access About menu with or without login, issue came with android hardware back button,

Login screen > About page > From Menu go to Login > Press hardware back button > Application Should get closed rather go to About page.

Below is the code for navigation to login screen.

```javascript
$scope.login = function() {
            $ionicHistory.nextViewOptions({
                disableBack: true,
                disableAnimate: true,
                historyRoot: true
            });
            $ionicHistory.clearCache();
            $ionicHistory.clearHistory();
            $ionicSideMenuDelegate.toggleLeft();
            $state.go('login');
        };
```

I am using ionic rc release 4 currently.

**Comment by jayrmotta** [comment]
+1

**Comment by sarisam99** [comment]
Hi,
I am facing an issue with hardware back button in Windows. 
Below code works fine in Andriod-
$ionicPlatform.onHardwareBackButton(function () {
        console.log('back button event');
        var token = localStorage.getItem('token');
        if (token == null || token == undefined) {
            navigator.app.exitApp();
        }
    })
But same code doesnt work in windows phone. When we click on hardware back button this function does not get invoked. Instead it exits the application and shows the menu screen.

Please let me know if there is a way to customize windows hardware back button to function like history.go(-1) so that it navigates to mobile app screen rather than exiting.

**Comment by amitandroid22** [comment]
in App.js 
 $ionicPlatform.registerBackButtonAction(function(event) {
          if($state.current.name=="tab.dash") { // your check here
            $ionicPopup.confirm({
              title: 'System warning',
              template: 'are you sure you want to exit?'
            }).then(function(res) {
              if (res) {
                ionic.Platform.exitApp();
              }
            })
          }
        }, 100);

**Comment by orengbasha** [comment]
hi friends iam working in ionic 3 tabs project in this project tabs page three tabs is there. if any tab i click any button its go to next page and if i click back button its go to tabs page but my problem is if i click hardware back button app will be closed not go to tab page. can you please help me . i search so many sites but its showing blank project examples please help me friends
