### ISSUE TITLE
bug: Overflow being set to visible in Modal on iPad

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#2087]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Using the modal example

http://codepen.io/ionic/pen/gblny

If you're on an iPad, `overflow:visible` is being set to the modal's ion-content`.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
