### ISSUE TITLE
bug: Ionic gestures not working

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic#2115]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I haven't tried in iOS "native hybrid", but in phone's browser it works perfectly, even the pinch gesture (at least for Android 4.4 and iOS 7)

I have made an app with a div that has the ionic gestures listeners in it. Then in the top there's another div that says which gestures have been detected.

What happens in the "native" android version:
1. touch/tap/double tap/release works OK
2. If you do it fast enough*, drag and swipe also works for very little time. Then it gets "released" and then is not working anymore.
3. And if you go slowly, right when your finger is leaving the touch-start spot, it gets "released"
4. Also, pinch gesture doesn't work at all.

Plunker here: http://plnkr.co/edit/XYrvChZ6o92r94mSt8Qb?p=preview
Project zip file: http://www.livewind.org/ionic/gestures.zip</span>

<span is-issue-template></span>

**Comment by apoku** [comment]
Curious why all of these issues are closed? Using ioninc-1.0.0-rc5 I am still seeing this issue for pinch, pinchin, pinchout, transform events on Android 4.4.0 device. When I try on an Android 5.0 device pinch, pinchin, pinchout, and transform are captured flawlessly.

Is there an accepted workaround?

**Comment by AbstractH** [comment]
+1

**Comment by skygragon** [comment]
+1 the issue is not fixed in latest v1 release, should we reopen it or just create a new one?
