### ISSUE TITLE
bug: collection-repeat is shifted by one (maybe)

### ISSUE THREAD

**Issue by saadzer** [driftyco/ionic#2116]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>when i used collection repeat with these settings : 
 collection-repeat="quest in questions"
      collection-item-width="'100%'"
      collection-item-height="100"
      ng-href="#/app/messages/{{quest.id}}"
      ng-style="{'height' : '40px'}"

the display was fine but there was a problem with the first element of the array not showing and the last element is null or undefined i just get no data on the output of the last element .</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
Closing for now, please reply with an example of it breaking if this is still a problem for you.
