### ISSUE TITLE
bug: tapIgnoreEvent doesn't check for data-tap-disabled

### ISSUE THREAD

**Issue by emertechie** [driftyco/ionic#2132]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>For various reasons I had to use another scrolling library in one area of my app. To disable the Ionic scroll stuff, I used overflow-scroll="true" on the ion-content and also data-tap-disabled="true" on a container element. However the Ionic tap library was still interfering (causing events not to fire in the other library).

It boiled down to the `tapIgnoreEvent` method in `tap.js`:

    function tapIgnoreEvent(e) {
      if(e.isTapHandled) return true;
      e.isTapHandled = true;

      if( ionic.scroll.isScrolling && ionic.tap.containsOrIsTextInput(e.target) ) {
        e.preventDefault();
        return true;
      }
    }

It's not checking if the element, or a parent, has the "data-tap-disabled" attribute set. 
It should be using the `isElementTapDisabled` method like other tap handlers. Changing first line to the following fixes issues:

    function tapIgnoreEvent(e) {
      if(e.isTapHandled || ionic.tap.isElementTapDisabled(e.target)) return true;
      ...

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
We do not recommend using two scroll libraries in the same app.

**Comment by anemitoff** [comment]
I don't understand why the proposed "fix" was rejected.  The documentation states that the "data-tap-disabled" can be used to bypass tap handling for designated elements and that isn't 100% true.  

I too have a non-supported use-case (IE Browser for Desktop with HTML5 Video Element whose control clicks are being intercepted by the tap handler), but I don't see why I shouldn't be able to use "data-tap-disabled" sucessfuly.

**Comment by mlynch** [comment]
Fixed in 311967991c7adb493e48ea575be2b39a8047415d
