### ISSUE TITLE
how to build third party custom keyboard ? 

### ISSUE THREAD

**Issue by athimannil** [driftyco/ionic#2133]
iOS8 giving option to build custom third-party keyboard
https://www.apple.com/uk/ios/ios8/quicktype/

Is it possible to build third party custom keyboard application for iOS8 with this cordova or ionic? 

Actually I'm looking to build foreign language keyboard for iOS8, is there any solution or any plugin available for that ? 
https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/Keyboard.html

**Comment by georgedrummond** [comment]
Is this possible now or still to be implemented by cordova?

**Comment by mhartington** [comment]
it's possible now. iOS's keyboard should give you the option to change the keyboard.

**Comment by georgedrummond** [comment]
@mhartington could you point me to any docs for this in Cordova or Ionic?

I found this on the Apple developer site https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/Keyboard.html

**Comment by mhartington** [comment]
For building a custom keyboard, you would need to write native code. 

If someone has a custom keyboard installed already installed though, they keyboard should let the user switch to that
