### ISSUE TITLE
bug: Unable to create a release APK-webview is debugabl

### ISSUE THREAD

**Issue by luckyycool** [driftyco/ionic#2139]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Unable to create a release APK (m able to debug) - 
Followed each steps of - http://ionicframework.com/docs/guide/publishing.html

except - 'Then, we can find our unsigned APK file in platforms/android/bin' , its wrong path it should be 'platforms\android\ant-build', 

When I install the released built apk in genymotion, i am able to debug the webview in chrome</span>

<span is-issue-template></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#236
