### ISSUE TITLE
feat: Request to update Angular bundle with ionic

### ISSUE THREAD

**Issue by csantanapr** [driftyco/ionic#2147]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I see that ionic is bundling AngularJS 1.2.17, it will be convenient to keep up with the angular stable releases. AngularJS 1.2.23 is 3 months newer. Please update AngularJS to latest stable release.</span>

<span is-issue-template></span>

**Comment by sagarkm** [comment]
Ionic Bundle with Angular 1.5 please?

**Comment by axsauze** [comment]
Is Angular 1.5 already available or in the roadmap? Would Angular 1.5 components work out of the box?

**Comment by Hakog** [comment]
At this moment i'm doing a project with Ionic and Angular 1.5 and making use of components. 

They work nice out of the box. So far i only found this issue, but keep in mind that i'am an Ionic newbie.

- The $ionicView events (enter, leave, beforeEnter, etc) do not make to the component's $scope.
