### ISSUE TITLE
Feature request: don't let header scroll offscreen when keyboard is shown

### ISSUE THREAD

**Issue by dirkpostma** [driftyco/ionic#2151]
It would be convenient if the header doesn't scroll out of screen in case the keyboard shows up for some input field. I know I can use keyboard plugin and use disableScroll(true) but in that case, the content doesn't scroll either. What I want is:

In case keyboard pops up,
I DO want the content to scroll up, 
I DON'T want the header to go offscreen

Example usecase: chat app. In a conversation a user is chatting. In that case the user should be able to see the header, e.g. to see the name of person he chats with and to be able to go back to previous screen.

**Comment by Ionitron** [comment]
Greetings, @dirkpostma!

Due to the age of this issue, and possibility it may have already been fixed or no longer applicable, my sensors indicate that this issue should be closed.

If you are still experiencing this issue, please feel free to reopen and provide the following information so that I may assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- What platform does this happen on? (iOS, Android, all, etc.)
- What platform versions does this happen on? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework, or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) which replicates the issue is extremely helpful.

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
close

**Comment by dirkpostma** [comment]
I tested with ionic 1.3.2, using the <ion-footer-bar> directive, and the problems still remains exactly the same. In case keyboard opens, the header scrolls away, as described above, which is not good behaviour. So: this is a request to reopen the issue.

**Comment by dirkpostma** [comment]
Request to reopen this issue. I tested with latest stable ionic 1.3.2 and problem still remains.

mhartington, you say: _What you are talking about is making the scroll view scroll to the bottom when the keyboard is open, like how iOS messages app works. This is something that the developer should be doing._

I am scrolling the content to bottom using $ionicScrollDelegate.scrollBottom(), but with (bad) results as shown in the screenshots above, with Keyboard.disableScroll set to both true and false. There is no way to get the desired result, namely: **to see both the header and footer when keyboard is open.**

**Is a codepen usefull?**
I could make a codepen, but I doubt whether it is usefull as the problem only exists after building to iOS or Android. The 3 screenshots above tell the exact problem:

1. Screenshot when keyboard is not open (oke)
2. Screenshot with keyboard open and disableScroll(false): when content is scrolled to bottom, the header scrolls offscreen (bad), footer is shown just above keyboard (good)
3. Screenshot with keyboard open and disableScroll(true): when content is scrolled to bottom, the header doesn't scroll offscreen (good), but footer is hidden under keyboard (bad).

**Possible solution?**
Reduce the height of the content div with value of the keyboard-height when keyboard is open?

**Comment by dirkpostma** [comment]
Request to reopen this issue. I tested with latest stable ionic 1.3.2 and problem still remains.

mhartington, you say: _What you are talking about is making the scroll view scroll to the bottom when the keyboard is open, like how iOS messages app works. This is something that the developer should be doing._

I am scrolling the content to bottom using $ionicScrollDelegate.scrollBottom(), but with (bad) results as shown in the screenshots above, with Keyboard.disableScroll set to both true and false. There is no way to get the desired result, namely: **to see both the header and footer when keyboard is open.**

**Is a codepen usefull?**
I could make a codepen, but I doubt whether it is usefull as the problem only exists after building to iOS or Android. The 3 screenshots above tell the exact problem:

1. Screenshot when keyboard is not open (oke)
2. Screenshot with keyboard open and disableScroll(false): when content is scrolled to bottom, the header scrolls offscreen (bad), footer is shown just above keyboard (good)
3. Screenshot with keyboard open and disableScroll(true): when content is scrolled to bottom, the header doesn't scroll offscreen (good), but footer is hidden under keyboard (bad).

Is a codepen still usefull?

**Possible solution?**
Reduce the height of the content div with value of the keyboard-height when keyboard is open?

**Comment by mhartington** [comment]
User disableScroll(true) in your `.run` and add the directive keyboard-attach to the footer.

http://ionicframework.com/docs/api/directive/keyboardAttach/

**Comment by dirkpostma** [comment]
That keyboard-attach directive (almost) does the job, thank you! :+1: 

A small problem left: the content doesn't scroll. Ideally, the "content + footer" should scroll together with the keyboard when it's animating up. Now, the keyboard pops up, after the animation is finished, the footer is attached to top and the content stays on same position. Ugly animation and the bottom of the content is hidden behind the keyboard. May be the developer should somehow register a "keyboard-up" event and scroll content himself, but I think that's not how it should be.

Do you think it is possible to scrolling of footer + content together with animation of keyboard, at the same time? I let you guys decide whether or not to keep this issue open...

**Comment by eduardoGranados** [comment]
Hello, i have to agree with dirkpostma, if there is a header it should not scroll offscreen,  and i don't think that disableScroll is a solution for this since some times the user needs to scroll while the keyboard is actived. I'm having the same issue.

**Comment by mica16** [comment]
I've also experienced the issue. 
I want to make a Chat like Whatsapp or iOS Message. 
I'm using disableScroll(true) in my run method and the keyboard-attach on footer (ion-footer-bar containing my input). 
The "bad" thing is that when the keyboard appears, the bottom of the content is hidden. 
On Whatsapp for instance, when you focus on the input, automatically the content scrolls down in order to see the last message. 

And as evoked above, the animation of a basic scrollBottom(true) is not really smooth.

Is there a way to achieve the case like Whatsapp does?

**Comment by pakaerf** [comment]
Having spent far too much time trying to figure this one out, I'll concur that this needs to be fixed. Seems like a wide-spread mobile pattern that should be simple. I have it working on iOS, but I can't figure out android for the life of me.

**Comment by prashantpalikhe** [comment]
Can this issue be reopen this issue? Also, looking for exactly what @dirkpostma is requesting.

**Comment by mhartington** [comment]
Please provide codepen example.

**Comment by dirkpostma** [comment]
Codepen makes no sense I think, as it is a native only issue.

**Comment by mhartington** [comment]
Right, be we can make an app from a codepen. 
I have a sample app put together that is a chat app
https://github.com/mhartington/Ionic-Chat
Use this if you need to.

**Comment by ciriac** [comment]
I'm running into the same issue as described by others here. If I'm using disableScroll(true), the view would no longer scroll all the way to the bottom of the last message.

**Comment by dirkpostma** [comment]
Ciriac: that seems Like a good solution! Similar to what is described here:

https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

**Comment by dirkpostma** [comment]
Only thing is that I think it should be solved natively in order to be able to get a proper animation.

**Comment by mhartington** [comment]
So if the issues is to make sure you can scroll to the bottom and not have the header scroll out of view, you can disable scrolling with the keyboard plugin, then call `$ionicsScrollDelegate.scrollBottom()` when you get a new message. 

http://ionicframework.com/docs/api/service/$ionicScrollDelegate/#scrollBottom

**Comment by dirkpostma** [comment]
Euhm... No, that is not enough because in that case the lower part of the content is hidden behind the keyboard. See last screenshot posted here on Sep 9, 2014.

The (I think only) solution is: in case keyboard pops up, resize the content area. This should be done natively in order to get proper animation. See previous posts for more info, it is described in much detail...

**Comment by mhartington** [comment]
Again, this is something that I've demoed here in my chat example app. 

https://github.com/mhartington/ionic-chat

Specifically 

https://github.com/mhartington/Ionic-Chat/blob/master/www/js/app.js#L90

https://github.com/mhartington/Ionic-Chat/blob/master/www/js/app.js#L98

**Comment by streetkid** [comment]
ScrollBottom is not an option for me, as when I use scrollBottom() the keyboard closes for me!

**Comment by Tobiaswk** [comment]
I'm just leaving my feedback here.

This is still a problem! Yes cordova.plugins.Keyboard.disableScroll(true) partly solves the problem. The header stays there. I am just wondering why it can't work without disableScroll set to true?

**Comment by mhartington** [comment]
This is need to prevent the webview from scrolling when the keyboard is show.

**Comment by softBarbarian** [comment]
@mhartington in your chat app example you are using `on-focus`, `on-blur`, `on-return` directives but they are not part of the repo. Where is the code for them?
https://github.com/mhartington/Ionic-Chat/blob/master/www/js/app.js#L49
