### ISSUE TITLE
clicking backdrop of ionicPopup on top of a modal closes modal instead of popup

### ISSUE THREAD

**Issue by Deminetix** [driftyco/ionic#2157]
If i open a modal and then open an ionicPopup, clicking on the backdrop closes the modal instead of the popup.

This is in beta 11

**Comment by johannesjo** [comment]
I agree with @rainboxx. This should be fixed.

**Comment by buunguyen** [comment]
+1, bitten by this today. `backdropClickToClose` is not the solution, I do want click-backdrop-to-close behavior with modals, but not when there's an alert or confirmation popup on top of it.

**Comment by souptikwgt** [comment]
enableBackdropDismiss :boolean | Whether the alert should be dismissed by tapping the backdrop. Default true.
