### ISSUE TITLE
bug: Clicking ionicActionSheet clicks textarea behind it

### ISSUE THREAD

**Issue by JonathanAquino** [driftyco/ionic#2204]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>If you click the $ionicActionSheet and a textarea is behind where you clicked, the keyboard appears and the textarea doesn't have focus.

To repro:
1. Create a blank Ionic starter project.
2. In index.html, make the body the following:

```
<ion-pane>
  <ion-header-bar class="bar-stable">
    <h1 class="title">Hello World</h1>
  </ion-header-bar>
  <ion-content>
    <p ng-controller="MyCtrl">Click <a href="#" ng-click="showActionSheet()">this</a> to show an action sheet.</p>
    <textarea style="height: 1000px; background-color: pink">This pink area is a textarea that covers the screen.</textarea>
  </ion-content>
  <ion-footer-bar></ion-footer-bar>
</ion-pane>
<script>
  angular.module('starter')
  .controller('MyCtrl', function ($scope, $ionicActionSheet) {
    $scope.showActionSheet = function () {
      $ionicActionSheet.show({
        buttons: [{text: "A"}, {text: "B"}, {text: "C"}],
        buttonClicked: function () { return true; },
        cancelText: 'Cancel'});
    };
  });
</script>
```
1. Click the link to show an action sheet.
2. Click the Cancel button in a spot that is on the footer (i.e., not on the textarea). The action sheet disappears and no keyboard appears, as expected.
3. Click the link to show the action sheet.
4. Click the A button, or any button on a spot that is not on the footer (i.e., on the textarea). 

// Expected: The keyboard does not appear.
// Actual: The keyboard appears, and the textarea does not have focus.</span>

<span is-issue-template></span>

**Comment by rafaelfamorim** [comment]
I'm facing this issue, but in a very specific scenario, it only happens when I tap it the very FIRST time and only in iOS. To simulate that, I need to reinstall the app or reboot the iphone. 

Do you guys have some thoughts about what I could try to fix it?

I've been played around with it for a while, but didn't find anything.

Thanks in advance!

**Comment by mariamayer** [comment]
Same issue here, it only happens when I tap it the very FIRST time and only in iOS.
