### ISSUE TITLE
bug: When side menu is disabled, expose-aside-when="large" still triggers

### ISSUE THREAD

**Issue by matiastucci** [driftyco/ionic#2210]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the 'ion-side-menu' when is-enabled="false", expose-aside-when="large" is still triggering. So in some sections I am disabling the menu but if the width is greater than 768px the menu is still appearing.

Codepen: http://codepen.io/matiastucci/pen/oHapg</span>

<span is-issue-template></span>

**Comment by flinn** [comment]
The `expose-aside-when` feature is pretty poorly thought out/configured IMO... There needs to be an easier way to override when to show/hide the exposed side menu, beyond using media queries -- We need to be able to control this easily with JS as well! I think the directive needs another attribute that takes a true/false expression and shows or hides itself based upon that.  

**As an example:** If a user hasn't logged into my app yet, I may not want to have the side menu options exposed (they might be dynamically set according to the user). In this case, having `expose-aside-when` set to `true` will unfortunately ensure that the side menu is always shown which means I can't use it without writing my own code for fighting against the way it currently works.

**Comment by noKid** [comment]
I'm also having the problem. I didn't found a proper way to close / toggle a side menu which have the expose-aside-when directive. Using $ionicSideMenuDelegate.isOpenLeft() always returns false. This is inconsistent and should be changed.

Thanks

**Comment by Fayozjon** [comment]
noKid

http://pain-advice.com/betonmarkets-front

24.03.2015, 14:12, "noKid" <notifications@github.com>:I'm also having the problem. I didn't found a proper way to close / toggle a side menu which have the expose-aside-when directive. Using $ionicSideMenuDelegate.isOpenLeft() always returns false. This is inconsistent and should be changed.

Thanks

**Comment by unek** [comment]
it's still visible even though disabled

**Comment by idrishkhanadl** [comment]
solution of "When side menu is disabled, expose-aside-when="large" still triggers" this problem is in Latest stable version 1.0.0 is replace below line in ionic.bundle.js lines "   sideMenuCtrl.exposeAside($window.matchMedia(mq).matches); sideMenuCtrl.close();" with " if ($attr.isEnabled == true) {sideMenuCtrl.exposeAside($window.matchMedia(mq).matches);} else {sideMenuCtrl.close();}" . it will resolved this problem

**Comment by 5im0n** [comment]
Tis bug is still present in the v1.1.0

**Comment by lordgreg** [comment]
I also have this bug when using ```expose-aside-when``` and it's really annoying. Did someone found a workaround for this?

**Comment by bianchimro** [comment]
hi,
in version 1.3 I am still getting the same behavior (`exposed-aside-when` seems to override `is-enabled`)

@lordgreg approach solves my use case, but this is still a bug / inconsistency in my opinion.
