### ISSUE TITLE
Use sufix or prefix for main classes in ionic.css

### ISSUE THREAD

**Issue by sarath2** [driftyco/ionic#222]
First thank for your great library.

eg: 
.io-modal{}  instead of .modal{}  

beocz I used bootstrap for large screens.
 ionic replace bootstrap features.

Otherwise it work nicely.

**Comment by priand** [comment]
FYI, we just faced the problem today. We are assembling a series of components under an ionic app, and some of these components are already built using bootstrap. And we are having conflict, like the definition of .modal. Evan is right, and the burden of having a prefix is out-beaten by a better integration story.

**Comment by ewinslow** [comment]
:) thanks for the vote of confidence. Doubtful we will see the issue fixed though.

Hopefully this problem will just quietly go away as folks move over to shadow Dom. (I.e. angular 2)

**Comment by yyl000000** [comment]
A similar discussion thread in Twitter Bootstrap suggests the _variables.scss file to implement an additional variable such as $prefix. When it is left blank, SASS will generate the clean CSS class names exactly as they are now. When $prefix has a value, SASS will generate prefixed class names. That way, it doesn't affect existing user base, while different teams can select different prefixes to avoid collisions with the UI frameworks that they are currently using. The best of both worlds.

**Comment by yelhouti** [comment]
Having the same problem when trying to mix clarity with ionic, just saying
