### ISSUE TITLE
Cant scroll once keyboards is opened or input is focussed

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [driftyco/ionic#2231]
Try this to reproduce the issue:

Have two views : 'View A' and 'View B'.

Let 'View A' be a long scrollable list.

'View B': 
``` html
<ion-view title="">
  <ion-content class="padding" scrollbar-y="false">
  <div class="list">
  <label class="item item-input item-stacked-label">
  <span class="input-label ">Text Here</span>
  <input type="text" placeholder="Text"></label>
  </div>
  <button class="button button-positive button-block">Hello</button>
</ion-content>
</ion-view>
```
Now from 'View  A' navigate to 'View B'. Focus on the input and enter some data. Now go back to 'View A' and BAM! you cant scroll in 'View A'.

Tried this on Android 4.2 to 4.4.

<b>Temporary Fix </b>

As a temporary fix I have the input under sub-header class with a margin from top so that it appears in view.

``` html
<div class="bar bar-subheader">
  <div class="list">
  <label class="item item-input item-stacked-label">
  <span class="input-label ">Text Here</span>
  <input type="text" placeholder="Text"></label>
  </div>
</div>
 <button class="button button-positive button-block">Hello</button>
```

Now the stated problem does not appear.

**Comment by tlancina** [comment]
This was fixed in https://github.com/driftyco/ionic/commit/74de015c221962aae8e48c1a81481ec6fc706f5e.

**Comment by bruceearly** [comment]
@tlancina I m really cant understand the key solution position,can you show me exactly?
