### ISSUE TITLE
Running "ionic setup sass" causes "Error running npm install"

### ISSUE THREAD

**Issue by Brisdo** [driftyco/ionic#2241]
I started by upgrading to the latest version of ionic (npm update ionic -g), 
## Overview

i. After upgrading ionic, tried to run:  " > ionic setup sass" but received: 
`npm ERR! install  Couldn't read dependencies ... Error running npm install`

ii. Updated node and npm.  Started over creating a new project called sass based on tabs instead of test based on default.  Tried to setup sass again but still received an error 
`Error running gulp sass`

iii. Installed gulp and was finally 
    able to run " > ionic setup sass" successfully.
## Details

i. After upgrading ionic, tried to run:  " > ionic setup sass" but received: 
`npm ERR! install  Couldn't read dependencies ... Error running npm install`

```
> ionic setup sass
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "."
npm ERR!     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:48
npm ERR!     at evalmachine.<anonymous>:207:20
npm ERR!     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/xxxxxx/Documents/1. Development/Ionic/test
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xxxxxx/Documents/1. Development/Ionic/test/npm-debug.log
npm ERR! not ok code 0

Error running npm install
```

ii. Updated node and npm.  Started over creating a new project called sass based on tabs instead of test based on default.  Tried to setup sass again but still received an error 
`Error running gulp sass`

```
> ionic setup sass
npmnpm WARN package.json sass@1.0.0 No README data

> node-sass@0.9.3 install /Users/xxxxxx/Documents/1. Development/Ionic/sass/node_modules/gulp-sass/node_modules/node-sass
> node build.js

`darwin-x64-v8-3.14` exists; testing

  ․․․․․․․․․․․․․․․․․․․․․․․․

  24 passing (80ms)

Binary is fine; exiting
gulp-rename@1.2.0 node_modules/gulp-rename

shelljs@0.3.0 node_modules/shelljs

gulp-minify-css@0.3.8 node_modules/gulp-minify-css
├── memory-cache@0.0.5
├── bufferstreams@0.0.1
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.31)
└── clean-css@2.2.16 (commander@2.2.0)

gulp-util@2.2.20 node_modules/gulp-util
├── lodash._reinterpolate@2.4.1
├── dateformat@1.0.8
├── minimist@0.2.0
├── vinyl@0.2.3 (clone-stats@0.0.1)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── lodash.template@2.4.1 (lodash._escapestringchar@2.4.1, lodash.values@2.4.1, lodash.templatesettings@2.4.1, lodash.defaults@2.4.1, lodash.escape@2.4.1, lodash.keys@2.4.1)
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.31)
└── multipipe@0.1.1 (duplexer2@0.0.2)

gulp-concat@2.4.1 node_modules/gulp-concat
├── through@2.3.6
└── concat-with-sourcemaps@0.1.3 (source-map@0.1.39)

gulp@3.8.8 node_modules/gulp
├── interpret@0.3.7
├── pretty-hrtime@0.2.1
├── deprecated@0.0.1
├── archy@0.0.2
├── tildify@1.0.0 (user-home@1.0.0)
├── minimist@1.1.0
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── semver@3.0.1
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, dateformat@1.0.8, lodash.template@2.4.1, through2@0.6.1, vinyl@0.4.3, multipipe@0.1.1, lodash@2.4.1)
├── vinyl-fs@0.3.7 (graceful-fs@3.0.2, strip-bom@1.0.0, mkdirp@0.5.0, through2@0.6.1, glob-stream@3.1.15, glob-watcher@0.0.6, vinyl@0.4.3, lodash@2.4.1)
└── liftoff@0.12.1 (extend@1.3.0, minimist@0.2.0, resolve@0.7.4, findup-sync@0.1.3)

bower@1.3.11 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── abbrev@1.0.5
├── chmodr@0.1.0
├── which@1.0.5
├── osenv@0.1.0
├── opn@1.0.0
├── archy@0.0.2
├── graceful-fs@3.0.2
├── rimraf@2.2.8
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.1
├── tmp@0.0.23
├── q@1.0.1
├── request-progress@0.3.1 (throttleit@0.0.2)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── shell-quote@1.4.2 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── semver@2.3.2
├── fstream@1.0.2 (inherits@2.0.1)
├── p-throttler@0.1.0 (q@0.9.7)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promptly@0.2.0 (read@1.0.5)
├── fstream-ignore@1.0.1 (inherits@2.0.1, minimatch@1.0.0)
├── tar-fs@0.5.0 (mkdirp@0.3.5, pump@0.3.5, tar-stream@0.4.5)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
├── glob@4.0.6 (once@1.3.0, inherits@2.0.1, minimatch@1.0.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, node-uuid@1.4.1, qs@1.2.2, mime-types@1.0.2, form-data@0.1.4, bl@0.9.3, tough-cookie@0.12.1, http-signature@0.10.0, hawk@1.1.1)
├── bower-registry-client@0.2.1 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.27.0)
├── update-notifier@0.2.1 (string-length@1.0.0, semver-diff@1.0.0, latest-version@1.0.0, configstore@0.3.1)
├── mout@0.10.0
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.2 (figures@1.3.3, through@2.3.6, mute-stream@0.0.4, readline2@0.1.0, cli-color@0.3.2, lodash@2.4.1, rx@2.3.9)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, lodash.debounce@2.4.1, os-name@1.0.0, tough-cookie@0.12.1, configstore@0.3.1, inquirer@0.6.0)

gulp-sass@0.7.3 node_modules/gulp-sass
├── map-stream@0.1.0
├── gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, dateformat@1.0.8, minimist@1.1.0, chalk@0.5.1, lodash.template@2.4.1, through2@0.6.1, multipipe@0.1.1, vinyl@0.4.3, lodash@2.4.1)
└── node-sass@0.9.3 (object-assign@0.3.1, node-watch@0.3.4, mkdirp@0.3.5, chalk@0.4.0, nan@1.0.0, shelljs@0.2.6, optimist@0.6.1, node-sass-middleware@0.2.0, mocha@1.18.2, sinon@1.9.1)

Successful npm install
Updated /Users/xxxxxx/Documents/1. Development/Ionic/sass/www/index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

/bin/sh: gulp: command not found

Error running gulp sass
```

iii. Installed gulp and was finally 
    able to run " > ionic setup sass" successfully.

`> npm install -g gulp
...
(no errors)
`> ionic setup sass
...

```
Successful sass build
> ionic serve
Gulp startup tasks: [ 'sass', 'watch' ]
Running dev server: http://localhost:8100
Running live reload server: http://localhost:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

[22:02:18] Using gulpfile ~/Documents/1. Development/Ionic/sass/gulpfile.js
[22:02:18] Starting 'sass'...
[22:02:18] Starting 'watch'...
[22:02:18] Finished 'watch' after 6.42 ms
CSS changed:  www/css/ionic.app.css
[22:02:19] Finished 'sass' after 465 ms
CSS changed:  www/css/ionic.app.min.css
```

**Comment by tjnine** [comment]
I'd like to start by saying I would love to help out in any way I can if needed let me know.
I'm having the same exact issue...running version 1.0.0
package.json  >>>
 "dependencies": {
    "gulp": "^3.5.6",
    "gulp-sass": "^0.7.1",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "q": "^1.2.0",
    "shelljs": "^0.3.0"
  }
<<<

I keep getting the same error no matter what gulp task it is...watch or sass
After running
$ ionic setup sass
npmnpm WARN package.json ten@1.0.0 No README data
npm WARN unmet dependency /Users/teejten/Sites/Ten/node_modules/gulp-sass requires gulp-util@'^3.0' but will load
npm WARN unmet dependency /Users/teejten/Sites/Ten/node_modules/gulp-util,
npm WARN unmet dependency which is version 2.2.20

Successful npm install
Updated /Users/teejten/Sites/Ten/www/index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

module.js:333
    throw err;
          ^
Error: Cannot find module 'map-stream'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/teejten/Sites/Ten/node_modules/gulp-sass/index.js:2:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)

Error running gulp sass

**Comment by thomas-lee** [comment]
ionic cli version is 1.3.22

FYI, I have similar issue to Brisdo. The gulp is not installed . So i have to install globally in order to make it works.

Although I have tried to run locally (npm install), there is no repository field.

For those who want to fix by `npm install -g gulp`

    /bin/sh: gulp: command not found

    Error running gulp sass


Thanks

**Comment by whitecat** [comment]
➜  list  sudo ionic setup sass                  
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/leetcat/Dropbox/Projects/list/npm-debug.log

Error running npm install



Exception with  (CLI v1.6.5)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: Not installed
ios-sim version: 5.0.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 7.0.1 Build version 7A1001

**Comment by steveandrewwong** [comment]
Running "ionic setup sass" causes "Error running npm install"

1. uninstall and then reinstall ionic
npm uninstall -g ionic
npm install -g ionic

https://github.com/driftyco/ionic-cli/issues/481

2. then it will throw error running gulp sass

3. chown command found on bower github 
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
https://github.com/bower/bower/issues/2262

4. and then it will throw error invalid device when emulating ios

5. change it back to original user rathe than chown

sudo chown -R username /Users/<username>
https://forum.ionicframework.com/t/invalid-device-state-error-when-trying-to-emulate-ios/37193/3

**Comment by vino144** [comment]
I have problems for at the time of setup the sass installation
Help me anyone........,

C:\Users\administrator\Desktop\ionic\calculator>ionic setup saas
Invalid setup task command: saas (CLI v2.2.1)

Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.0
Xcode version: Not installed
