### ISSUE TITLE
Cursor does not follow input when scrolling with $ionicScrollDelegate on iOS

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic#2244]
This is the same problem as described in #26 and #1063. It seems that it was fixed for scrolling by the user, but if the scroll is done programatically the problem still occurs.

here is a snippet from a directive:

    var scroller = $ionicScrollDelegate.$getByHandle('my-handle'),
          setTop = function(){
            var top = element[0].getBoundingClientRect().top;
            if ( top > 62){ scroller.scrollBy(0, top - 62, true); }
          };

When setTop is called, the scroll happens, but cursor stays in the original position (no longer over the input).

**Comment by cquartier** [comment]
I agree with @sloops77, I have a chat-based app and have the exact same problem with this fix

**Comment by pulakb** [comment]
@sloops77 can you please share the solution in codepen?

**Comment by sloops77** [comment]
Unfortunately the way i've fixed this is by using a fork of ionic (or hack your copy of ionic). 

see this commit on my own fork https://github.com/sloops77/ionic/commit/c96af221a7c4edb68a91a867c4663c1efa23fb4e. you can cherrypick it if u like.

Note that my fork of ionic also contains commits for trigger.io support which you probably dont want

**Comment by adamdbradley** [comment]
@AgDude Would you be able to put together a codepen replicating the issue? Thanks

**Comment by Ionitron** [comment]
Greetings @AgDude!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by kunj77** [comment]
I am facing the exact same issue. Is there a solution for this yet?

**Comment by Stephs15** [comment]
I am facing this same issu in android. Any solutions?

**Comment by piyushmanurkar** [comment]
Any update on this??? I am facing the exact same issue...

**Comment by VinceOPS** [comment]
Same here with ionic 1.3 and iOs 9.3...

**Comment by VinceOPS** [comment]
Hi there!
Just to say that the issue also exists on **Android** with `overflow-scroll` set to `false`

**Comment by jdnichollsc** [comment]
same issue with iOS 10 and ionic 1.3

**Comment by ManivannanP** [comment]
I faced same issue in ios all devices in ionic 1

**Comment by VinceOPS** [comment]
Looks like it's a bug from webkit in Safari mobile:
https://bugs.webkit.org/show_bug.cgi?id=138201#c5

(http://openradar.appspot.com/18819624)

It will probably never be fixed (lasting since iOS 7).
The only workaround (given by the community) seems to consist in hiding the cursor by triggering blur(), and then focusing again (focus()) when scroll is done...

**Comment by JaswinderImmanent** [comment]
I am facing the same issue.The input field cursor scroll with screen in IOS device.
Unable to find any solution.Please help as soon as possible.

Thanks in advance.
