### ISSUE TITLE
Bouncing loading animation

### ISSUE THREAD

**Issue by jianbo** [driftyco/ionic#2250]
When deployed to my Galaxy s4, the loading icon seems bouncing around.  http://forum.ionicframework.com/t/bouncing-loading-animation-using-ionicloading-in-android/4896

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by dbaq** [comment]
huuu @Ionitron! this should be reopened @perrygovier

**Comment by perrygovier** [comment]
This is going to go away soon with our [SVG animated icons](http://ionicframework.com/docs/nightly/api/directive/ionLoader/) Stay tuned.
Bad Ionitron!

**Comment by adamdbradley** [comment]
The bouncing icons are no longer with the new SVG spinners: http://ionicframework.com/docs/nightly/api/directive/ionSpinner/
