### ISSUE TITLE
Add support for less pre-processor

### ISSUE THREAD

**Issue by rayshan** [driftyco/ionic#2252]
Hope it's not a dupe, tried to search for it but less is a very generic term.

**Comment by bassjobsen** [comment]
@rayshan please see https://github.com/bassjobsen/ionic-learn/blob/less/content/formulas/working-with-less/article.md; how to use Less in stead of SASS now.

Motivation and explanation can be found at: http://bassjobsen.weblogs.fm/less-ionic-framework/
