### ISSUE TITLE
Collection-repeat very slow on beta12 but not on beta11

### ISSUE THREAD

**Issue by crooy** [driftyco/ionic#2265]
We implemented Collection-repeat on beta 11. Upgraded to beta12, and it unbelievably slow on ios and android. The app is already quite large, so it is hard to determine any causes.. but for now we are back on beta11.

**Comment by perrygovier** [comment]
There's a few things going on with collection repeat related to performance. 
First, @crooy, are you including jQuery in your app? It's known to kill collection repeat elastic scrolling. 

If you're referring to reduced framerates and choppy performance. There's an Android related issue we're looking in to, but you mentioned iOS as well.  Are you able to provide a related codepen?

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
