### ISSUE TITLE
Simulator doesn't work 

### ISSUE THREAD

**Issue by sh4hin** [driftyco/ionic#2281]
i went through ionic sidemenu app when i run emulate ios  i get these errors:
Usage of '--family' is deprecated in 3.x. Use --devicetypeid instead.
Usage of '--retina' is deprecated in 3.x. Use --devicetypeid instead.
Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Simulator session timed out." UserInfo=0x7f91f97358b0 {NSLocalizedDescription=Simulator session timed

and the black screen comes for the simulator 

and these are my mac info:
yosemite 10.10
ios-sim version 3.0.0
cordova version 3.6.3-0.2.13
ionic version 1.2.6-beta1
xcode 6.1

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
