### ISSUE TITLE
bug: jQuery kills scroll momentum in collection-repeat

### ISSUE THREAD

**Issue by zapatek** [driftyco/ionic#2297]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Adding jQuery kills the scroll momentum in collection-repeat. Can be observed on desktop, too:

http://codepen.io/zapatek/pen/hnatq

Here is the working version with only jQuery link removed:
http://codepen.io/zapatek/pen/dxyLe</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
I'll be digging in to this one. Note that #2265 may be related to this issue.

**Comment by ajoslin** [comment]
Working in nightly builds with the collection-repeat refactor: http://codepen.io/ionic/pen/YPvWBr
