### ISSUE TITLE
Scroller 2.0

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#2298]
This is an issue to start discussion about tweaks to the scroller component of Ionic with the aim of making apps feel more native.

**Background:**
Remember https://github.com/driftyco/ionic/issues/482? In some difficult to pin down cases it was possible to make the scrolling component get stuck. This difficult to point down bug had a huge effect on how Ionic 'felt' as a quality framework. After quite a bit of back and forth between myself and @ajoslin  we managed to squash the bug. This solved the most egregious bug in the scrolling component. But I believe there is still more to be done in this area.

I see 3 areas of improvement.

``1.`` Currently the scroll doesn't feel 'native' yet. When compared to native apps on iOS, Ionic's scroll feels too 'loose'. This makes apps based on Ionic feel too light, like they have too little inertia. I believe that by taking some time to compare how native iOS apps feel and matching the speed and acceleration of those within Ionic, we can vastly improve the 'feel' of Ionic apps. 

I realise this is a bit of a 'dark art' and would involve a lot of trial and error. But I think it's worth to invest in.

``2.`` Other thing I notice frequently is that it's possible to make the scroll jump up or down when touching the screen. It's quite difficult to reproduce, but it seems as though sometimes the app doesn't have the time to register the touchstart and touchend events correctly, thereby incorrectly assuming the acceleration is really high. This then causes the scroll to jump. 

Like with the previous point, this is not a showstopping bug, but fixing it would make Ionic's scroll more reliable which would add a lot to the overall 'feel' of Ionic apps.

``3.`` The javascript scroll performance on Android leaves a lot to be desired. On a Galaxy S4, which is a quite recent model, Ionic's javascript scrolling has a very low FPS (like 5fps). Even when there are very few DOM elements on screen. Compared to Ionic's javascript scroll performance on iOS, this is a huge difference. On iOS it's very smooth.

I am not sure if this is an issue with all Cordova apps (regardless of framework used) on Android in general, or if Ionic's scrolling library just doesn't perform as well on Android as it does on Ionic. But the difference between iOS and Android is very noticeable. By making these more in line, it would help Ionic feel a lot better.

Interested in hearing your thoughts on this.

Keep up the good work, can't wait for the final 1.0 release!

**Comment by Ionitron** [comment]
We are currently working on removing JS scrolling for Android devices. Additionally, the Ionic CLI now comes with Crosswalk to improve Android scroll performance.

**Comment by mica16** [comment]
Good !! :)

**Comment by mica16** [comment]
Is it integrated in any nightlybuild ?
