### ISSUE TITLE
Placeholder text for text areas indent

### ISSUE THREAD

**Issue by kimsaabyepedersen** [driftyco/ionic#2307]
Hi
I have created an app with ionic b13 that uses a text area with a placeholder text.

When the text area gets focus, the cursor and placeholder are not aligned correctly.

See photo

![error](https://cloud.githubusercontent.com/assets/1308786/4430007/b4edd89e-4614-11e4-8e6e-27b52c16874f.png)

**Comment by mhartington** [comment]
Looking into this.

**Comment by WinfredMa** [comment]
/* ----------- iPhone 4 and 4S ----------- */
@media only screen 
  and (device-width: 320px) 
  and (device-height: 480px)
  and (-webkit-min-device-pixel-ratio: 2) {
    textarea {
      text-indent: -3px;
    }
}

/* ----------- iPhone 5 and 5S ----------- */
@media only screen 
  and (device-width: 320px) 
  and (device-height: 568px)
  and (-webkit-min-device-pixel-ratio: 2) {
    textarea {
      text-indent: -3px;
    }
}

/* ----------- iPhone 6 ----------- */
@media only screen 
  and (device-width: 375px) 
  and (device-height: 667px) 
  and (-webkit-min-device-pixel-ratio: 2) {
    textarea {
      text-indent: -3px;
    }
}

/* ----------- iPhone 6+ ----------- */
@media only screen 
  and (device-width: 414px) 
  and (device-height: 736px) 
  and (-webkit-min-device-pixel-ratio: 3) {
    textarea {
      text-indent: -3px;
    }
}

**Comment by gwidonw** [comment]
@WinfredMa you can use platform specific body class to style textarea in all apple devices.
```css
.platform-ios textarea, 
.platform-ipad textarea  {
	text-indent: -3px;
}
```

**Comment by mlynch** [comment]
Thanks! Got this in there and it's looking a lot better. We needed the `text-indent` on the textarea itself not the placeholder

**Comment by swapkids** [comment]
How about for multiline textareas? it's only the first line that gets indented

![screen shot 2015-12-16 at 14 17 33](https://cloud.githubusercontent.com/assets/13032789/11841762/d11206a4-a3ff-11e5-82a4-2ed1ebe1f8b4.png)

**Comment by mlynch** [comment]
Yea, that solution is problematic. Reverting for now: 62fa27e562b06e7d1226e5da5996ffb5ec9eb5bc

**Comment by JCsplash** [comment]
Hey everyone I think I found a solution without using text-indent (which only seems to work for the first line). Hope this helps.

textarea::placeholder {
  padding-left:3px
}

textarea{
  margin-left:-3px
}

**Comment by taigeair** [comment]
@JCsplash  thanks for that tip. Your place holder wasn't working for Safari Mobile so I added some webkit lines to it. I got it working with this code below:

`/* iPhone fix */ 

.platform-ios textarea, 
.platform-ipad textarea  {
}


.platform-ios textarea::-webkit-input-placeholder,
.platform-ipad textarea::-webkit-input-placeholder {
padding-left:3px !important; 
}

.platform-ios textarea:-moz-placeholder,
.platform-ipad textarea:-moz-placeholder { /* Firefox 18- */
padding-left:3px !important; 
}

.platform-ios textarea::-moz-placeholder,
.platform-ipad textarea:-moz-placeholder {  /* Firefox 19+ */
padding-left:3px !important; 
}

.platform-ios textarea:-ms-input-placeholder,
.platform-ipad textarea:-moz-placeholder {  
padding-left:3px !important; 
}

.platform-ios textarea,
.platform-ipad textarea {
margin-left:-3px !important; 
}`

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by jaroslavrehorka** [comment]
This issue is still present in RC2, negative text-indent helped me
![screen shot 2016-11-08 at 10 59 21](https://cloud.githubusercontent.com/assets/7473041/20094640/7c4b87d0-a5a2-11e6-9a67-1a82ecf58c38.png)

**Comment by lpsBetty** [comment]
this worked for me:

````
.platform-ios {
    textarea {
        margin-left: -3px;
        &::placeholder {
            padding-left: 3px;
        }
    }
}
````

**Comment by doushan** [comment]
https://blog.ajcw.com/2011/02/styling-the-html5-placeholder/
