### ISSUE TITLE
Opening a modal triggers the Window resize event

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic#2309]
I have several actions bound on the window resize event (like updating SVGs size etc.). Opening a modal triggers them every time. I believe opening a modal should not trigger the resize event.

http://codepen.io/shprink/pen/CFxiG

Cheers,
Julien

**Comment by swapkids** [comment]
Why is this closed? Opening a modal shouldn't trigger a "resize"? In my case I have iScroll completely refreshing upon 'resize' .. which is really bad.
