### ISSUE TITLE
Button inside input does not trigger ng-click

### ISSUE THREAD

**Issue by oneg1n** [driftyco/ionic#2311]
I have this markup:

```
<div class="list">
<div class="item item-input-inset">
<label class="item-input-wrapper">
<input type="text" name="search_input" placeholder="Contact name" ng-model="searchPhrase.name">
<button class="button-clear icon ion-close-circled" ng-click="resetSearch()"></button>
</label>
</div>
</div>
```

The idea was to have button part of the input element, but clicking on the button does not trigger function defined in ng-click. It does work when button is defined before the input field in the markup (but then all input field has that ng-click event registered). This is however not intended. I guess it has something to do with event listener registration. 

So generally - how to handle this situation? Is that a correct way how to define button inside the input field?

**Comment by hailor** [comment]
I have the same problem, click on button in item-input dose not trigger ng-click
```
    <label class="item item-input">
        <span class="input-label">Captcha</span>
        <input type="text" class="captcha" ng-model="user.captcha">  
        <img class="button button-icon button-small icon captcha" ng-click="refreshCaptcha(user.login)" ng-src="{{captchaUrl}}"/>
    </label>
```

**Comment by zhuhu** [comment]
I have the same problem but my major concern is the mobile app. I uses "on-tap" as the workaround.

**Comment by Marloto** [comment]
Same problem here, event is always triggered by input field. It doesn't matter where to add ng-click (label or input), the value of $event.target / $event.srcElement / $event.toElement is always the input field. In case of adding ng-click to the button, it is never executed.

    <ion-list>
        <label class="item item-input-inset">
            <input type="text" ng-click="doSomething($event)" />
            <a class="button">ClickMe</a>
        </label>
    </ion-list>

Current workaround for me, is to use the input field offsetWidth and click target, as well as adding ng-click to the input field:

    $scope.doSomething = function(e) {
        if(e.target.offsetWidth > e.layerX) {
            return;
        }
        // *magic occurs*
    }

Tested on mobile device (iOS) and in Chrome (Mac)

**Comment by Ionitron** [comment]
Please do not place a button inside of a label which also contains an input. http://ionicframework.com/docs/components/#item-input-inset

**Comment by calendee** [comment]
Here's some info on this problem and how to solve it: 

http://forum.ionicframework.com/t/buttons-inside-form-labels/29033/3  
http://play.ionic.io/app/e0996f31ffaf

**Comment by simeg** [comment]
@calendee thank you! Using a `<div>` to wrap the `<input>` and `<button>` works fine for me.

**Comment by calendee** [comment]
@simeg Word of caution on this.  The newest release of Ionic will no longer support custom HTML for inputs.  So, this workaround might not last long...

**Comment by domharrington** [comment]
Why is this an issue?

**Comment by JDonadio** [comment]
Same issue here. Try putting the button outside of <label> (is not my case)

**Comment by dipedro** [comment]
> label in Ionic is used to capture the tap and trigger focus on an input field. So, it prevents tapping anything else. by @calendee
