### ISSUE TITLE
ion-refresher class 'inactive' missing on start

### ISSUE THREAD

**Issue by alexanderkirtzel** [driftyco/ionic#2324]
By default ion-refresher is creating a div container with the class "scroll-refresher". Using the tabs-starter half of the 'Pull to refresh...' text is visible.
![bildschirmfoto 2014-09-30 um 22 24 05](https://cloud.githubusercontent.com/assets/3539781/4465922/ce041c12-48df-11e4-89c9-a08d6102ac18.png)
By pulling the view the class 'active' will be added. If you stop pulling the class 'invisible' will be added to the div. Might help to set class invisible by default on startup. I couldn't create a Codepan example, sorry.

**Comment by perrygovier** [comment]
I'm having trouble reproducing this with cards, `h3`'s or `button`'s. Can you share a codepen that demonstrates the issue? Are you seeing this only in Brackets' live preview? What about stand alone Chrome?

**Comment by 311chaos** [comment]
Ill have to see if I can reproduce this. Unfortunately, this was a bit ago and I no longer have access to the laptop that I was tinkering with for this issue.

**Comment by perrygovier** [comment]
Refresher got a bit of a "refresh" a few weeks ago. With it, the invisible class was added by default and a few other CSS updates were added. It should now not be visible unless you're over-scrolling 
7134114bd5975f9d63d0b73cc53c9a0c60d8cf0f
