### ISSUE TITLE
Right side menu not showing when expose-aside-when=large

### ISSUE THREAD

**Issue by jasonvillalon** [driftyco/ionic#2328]
menu-toggle="right" is not working when expose-aside-when="large" is added in ion-side-menus

http://plnkr.co/w0aJln?p=preview2

**Comment by claude** [comment]
+1

**Comment by apostoiis** [comment]
+1

**Comment by ekonstantinidis** [comment]
Not sure if this one is related to #3244 which is ready for RC1.

**Comment by mhartington** [comment]
Still seeing this with the nightly build builds.

http://plnkr.co/edit/Dlpeu10XiESQnBHYiz3z?p=preview

**Comment by helmuthva** [comment]
+1 to get this fixed.

**Comment by danboh** [comment]
+1 any workaround on this?

**Comment by lucbonnin** [comment]
+1 to get it fix please. really anoying issue

**Comment by lucbonnin** [comment]
I think it is a HUGE issue for ergonomic purpose for several use cases :
- when you have both sides menus with only leftMenu expose-aside-when=large, you can't access the right side menu :(
- when you want your ipad to display side menus + content pane all the time.

Do you have any idea of a duedate for this issue on ionic v1 ?
I think it is not hard to fix it and some guys suggested some pull request.

**Comment by numerized** [comment]
Hi There, Issue still present.

**Comment by mlynch** [comment]
Hey everyone, got this fixed :) Behavior will look like this:

![screenshot 2015-12-06 19 16 32](https://cloud.githubusercontent.com/assets/11214/11616970/e87b06ec-9c4d-11e5-8a78-273c761a507e.png)

🍻

**Comment by doorty** [comment]
I think the desired behavior is for each side menu to have their own exposeAside that are independent of each other. For instance, I just want the left menu to open when "large" and not the right side.

**Comment by davidbergvik** [comment]
+1 doorty, the current fix exposes both the left and right menu if one of them has expose-aside-when set.

**Comment by felly** [comment]
In my opinion this fix also reopens #3352 as the element's width doesn't get updated after an orientation change(https://github.com/driftyco/ionic/commit/a98f88ba6c1715459e5ccf0a21237255417672f3#diff-7f8a45a06c53978f6e2571220899a0eaR178).

**Comment by MuhammadRashed** [comment]
fixed:

in the file:  ionic.bundle.js
change the code:
```
setTranslateX: ionic.animationFrameThrottle(function(amount) {
var xTransform = content.offsetX + amount;
$element[0].style[ionic.CSS.TRANSFORM] = 'translate3d(' + xTransform + 'px,0,0)';
```

change it to be:

```
setTranslateX: ionic.animationFrameThrottle(function(amount) {
var xTransform = content.offsetX + amount;
if (content.offsetX > 0)
{
      xTransform = amount;
}
$element[0].style[ionic.CSS.TRANSFORM] = 'translate3d(' + xTransform + 'px,0,0)';
```

**Comment by yossi-shasho** [comment]
+1 for a fix

**Comment by axsauze** [comment]
+1

**Comment by chaitanyagupta76** [comment]
above fix is  not working any help on this is highly appreciated
