### ISSUE TITLE
iOS 8 incorrect SVG width

### ISSUE THREAD

**Issue by lukechilds** [driftyco/ionic#2329]
I've noticed since updating to iOS 8 that if an element has padding and contains an inline SVG without a defined width it will spill out of it's container rather than fit the exact width.

It appears that the padding of the parent element isn't being taken into account when the SVG width is being calculated.

Strangely, adding `max-width: 100%;` to the SVG element does respect the padding and sizes the SVG correctly.

This didn't happen in iOS 7 and doesn't happen on any other browser that I've tested so it seems like it may be a bug introduced in iOS 8 not Ionic.

![No padding, SVG fits](https://cloud.githubusercontent.com/assets/2123375/4474282/cfd33d10-495d-11e4-9047-22cea12d85c6.png)

![With padding, SVG gets cut off](https://cloud.githubusercontent.com/assets/2123375/4474313/1a338950-495e-11e4-8587-cfed92a0b89d.png)

![With padding and 'max-width: 100%;' on SVG it fits](https://cloud.githubusercontent.com/assets/2123375/4474340/87df2ce8-495e-11e4-8100-25d34beb7253.png)

**Comment by adamdbradley** [comment]
Greetings!

Due to this issue's age and inactivity, it has been closed.

If you are still experiencing this issue, please feel free to reopen it so that we can assist you.

Thank you!

**Comment by kromkens** [comment]
This is still an issue as far as I'm concerned. I see the exact same behaviour as explained above.
