### ISSUE TITLE
bug: Popup overlay click causes modal to close.

### ISSUE THREAD

**Issue by elebetsamer** [driftyco/ionic#2340]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using a modal, and then opening a popup (for an alert or something), clicking on the overlay causes the modal to close.

Example here using code from the docs site: http://codepen.io/elebetsamer/pen/swnzr</span>

<span is-issue-template></span>

**Comment by amirtutunchi** [comment]
Thanks a lot i have same problem and wondering how to solve it . it was fantastic guys.

**Comment by alrahmsa** [comment]
tx

**Comment by djarrin** [comment]
still a solid fix all these years later drewrygh. I had an alert that popped up over a modal, then if you pushed to close the alert and immediately click the screen again the modal would close. If I just added
`$scope.modal['backdropClickToClose'] = false;
  $scope.modal['hardwareBackButtonClose'] = false;`

The issue went away.
