### ISSUE TITLE
sideMenuContent prevents dragup,dragdown events, causing page scrolling fail

### ISSUE THREAD

**Issue by sarim** [driftyco/ionic#2341]
So in sideMenuContent.js you see the directive listens to dragright, dragleft, dragup, dragdown events. But for side menu to work, only left and right is relevant. But it is listening to up,down too, and calling e.preventDefault() on this. So dragup/down events aren't bubbling up to the page. So page doesn't scroll when you drag up or down. This issue is happening when overflow-scroll is set to true. I had to apply this very dirty fix to temporary fix it.

```js
.config(function($provide) {
    $provide.decorator('ionSideMenuContentDirective', function($delegate, $ionicGesture, $timeout) {
        var funcStr = $delegate[0].compile.toString();
        var argStart = funcStr.indexOf('(');
        var argEnd = funcStr.indexOf(')');
        var bodyStart = funcStr.indexOf('{');
        var bodyEnd = funcStr.lastIndexOf('}');
        
        var funcArgs = funcStr.substring(argStart, argEnd+1);
        
        var funcBody = funcStr.substring(bodyStart, bodyEnd+1);
        
        /* this is madness */
        var h = angular.isDefined;
        var t = $ionicGesture;
        var e = $timeout;
        /* this is sparta */
        
        funcBody = funcBody.replace(new RegExp('dragup', "g"), 'dragupDummy')
                   .replace(new RegExp('dragdown', "g"), 'dragdownDummy');
    
        eval("function newFunc" + funcArgs + funcBody);
        $delegate[0].compile = newFunc;
        
        return $delegate;
    });
})
```

Nevertheless, I don't think sideMenu needs to listen to dragup/dragdown event, as the purpose of sidemenu is to appear from left or right when dragging left/right. Why drapup/down event required at all? also when it is causing issue to scrolling.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
