### ISSUE TITLE
bug: ion-popover doesn't work in ion-content

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#2343]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ion-popover in apps with ion-content, the popover backdrop loads but the popover is not visible.  Changing the popover opacity from 0 to 1 fixes the problem.

http://codepen.io/calendee/pen/vlADg?editors=101
http://codepen.io/calendee/pen/wgrjL?editors=101</span>

<span is-issue-template></span>

**Comment by phearme** [comment]
documentation should be updated to state that $event **must** be passed to the show method in order to work properly.

**Comment by mhartington** [comment]
@phearme this is already in the docs
http://ionicframework.com/docs/api/service/$ionicPopover/

**Comment by phearme** [comment]
@mhartington sorry but to me, the documentation is not clear enough. It should clearly state that passing $event to the show method is mandatory. The example is not enough.

**Comment by lastmj** [comment]
The source code says you can pass in $event or the target element. It would be useful to me to be able to pass in the target element without an event, because I am programmatically calling show on the popover, instead of doing it through an ng-click. 

Here is the source code:
https://github.com/driftyco/ionic/blob/master/js/angular/service/popover.js#L1

      /**
       * @ngdoc method
       * @name ionicPopover#show
       * @description Show this popover instance.
       * @param {$event} $event The $event or target element which the popover should align
       * itself next to.
       * @returns {promise} A promise which is resolved when the popover is finished animating in.
       */

**Comment by alxvallejo** [comment]
If i want to open the popover on ng-init and pass $event to it, $event is undefined

**Comment by juergengunz** [comment]
@alxvallejo  did you find a solution for this ?
