### ISSUE TITLE
ion-option-button vertical-align: center;

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic#2348]
is it possible to add vertical-align: center; to the ion-option-button

this isn't working

```
ion-option-button class="button-assertive" style="vertical-align: center;
```

**Comment by hugofigueira** [comment]
just use <center><button ...></button></center>

**Comment by programming-kid** [comment]
isn't <center> tag deprecated ???

**Comment by hugofigueira** [comment]
i used it and it works fine
