### ISSUE TITLE
bug: App crash on screenshot with Android

### ISSUE THREAD

**Issue by CedNet** [driftyco/ionic#2350]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Phone: Samsung Alpha
Android: 4.4.4
Ionic: 1.2.6
Build methods: both via Eclipse and Ionic build / run

Simply trying to take a screenshot of the app and it dies while holding in the buttons to take a screenshot. The app dies, and After it dies, android does indeed take a screenshot. 

Here's the dump-log from Eclipse:

10-05 21:14:26.967: D/SmartClipDataCropperImpl(3627): doExtractSmartClipData : Extraction start! reqId = -1  Cropped area = Rect(0, 0 - 720, 1280)  Package = se.xxx.xxxxxx
10-05 21:14:26.967: W/WebView(3627): extractSmartClipData is called
10-05 21:14:26.977: A/libc(3627): !@Fatal signal 11, thread 3708
10-05 21:14:26.977: A/libc(3627): Fatal signal 11 (SIGSEGV) at 0x000002dc (code=1), thread 3708 (Chrome_InProcRe)
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): getOpaqueBackgroundRect : opaqueRect=Rect(0, 0 - 720, 1280)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@41fa27e8
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): getOpaqueBackgroundRect : opaqueRect=Rect(0, 0 - 720, 1280)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@41fa2430
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): addAppMetaTag : package name is se.xxx.xxxxxx</span>

<span is-issue-template></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#247
