### ISSUE TITLE
Scroll position not remembered when creating a modal with fromTemplate()

### ISSUE THREAD

**Issue by TimothyKrell** [driftyco/ionic#2358]
OK. This is a really weird bug that took me a few hours to track down.

Basically, if I create a modal on a list view with `fromTemplate()`, and include the `<ion-content>` tag in the modal, my scroll position will not be remembered when navigating back to the list view via the back button.

Even odder, if I make a modal the same way, but omit the `<ion-content>` tag, my scroll position is remembered, and if I make a modal with `fromTemplateUrl` including the `<ion-content>` tag.

Here is my test. See lines 60 – 90:
http://codepen.io/TimothyKrell/pen/Gzwim?editors=101

**Comment by Ionitron** [comment]
Is this still an issue with the nightly builds?

**Comment by perrygovier** [comment]
go home @Ionitron, you're drunk. 

It looks like this has been resolved.

**Comment by agupta1989** [comment]
Hey, I am using below ionic version:
```
{
  "version": "1.1.0",
  "codename": "xenon-xerus",
  "date": "2015-08-13"
}
```
I have added ```ion-scroll``` and toward long content and bottom of my page, I have a button on click of which I am opening a modal with following content:

```
<div class="modal">
	<img src="img/bg.png" alt="" />
	<ion-header-bar class="bg-tab">
		<i class="icon ion-ios-arrow-back txt-blue txt-big-30 pull-left txt-white" ng-click="closeModal()"></i> 
		<h1 class="title txt-center">Video</h1>
	</ion-header-bar> 
	<ion-content overflow-scroll="true">
		<div class="list" ng-if="video_data.mime_type=='video/mp4'">
			<video id="app_player" appvideo width="100%" height="100%" controls="controls" autoplay="autoplay">
				<source ng-src="{{video_data.url | trusted}}" type="{{video_data.mime_type}}"></source>
			</video>
		</div>
	</ion-content>
</div>
```
When I close modal using ```modal.hide();``` and ```modal.remove()``` it goes to my previous screen but the ```ion-scroll``` position get reset. Scroll moves to upward. any thought ?

**Comment by Naveenbc** [comment]
@agupta1989  I have the same problem. Did you get the solution?

**Comment by Fl0rianFischer** [comment]
@agupta1989 same problem here

**Comment by agupta-q4** [comment]
@Naveenbc  @Fl0rianFischer Unfortunately no, :(. please let me know if you get any solution.
