### ISSUE TITLE
on-hold directive not working in ion-slide-box

### ISSUE THREAD

**Issue by marcsyp** [driftyco/ionic#2373]
With the recent update to Android 4.4.4, the on-hold directive is no longer working consistently.  I am using the nightlies with the refactored slide-box (as of yesterday), this does not solve the issue.

I am able to engage the tap-hold only maybe 1 in 5 tries, or even 1 in 20 to 30 in some cases.  I have put together a sample project with an ng-repeat of a number of items within a single slide.  I suspect that vertical scroll may have something to do with it, but I don't see any docs on disabling the scroll within a slide to test.

You can find the project here:

https://drive.google.com/file/d/0B1ClGdseCfJdS09XN3JfbXp2Ykk/view?usp=sharing

Thanks.

**Comment by marcsyp** [comment]
I noticed that some of the other touch event issues are being closed with recent updates.  This one is still open, and it is my primary problem with my app right now.  Basically halted development for several months.  Any updates?  If there is a fix by moving to latest nightly and Crosswalk, etc, I will make the effort to upgrade (I'm stuck in Beta13, I believe).

Thanks,
Marc

**Comment by SashaGeekette** [comment]
@marcsyp Suggest using mnTouch if updates dont' work. We are using that for on-hold right now and it works great.

**Comment by marcsyp** [comment]
Thanks.  Any specific notes on implementing this in Ionic?  Do I need to rip out anything from the Ionic bundle that will conflict?  I'm not an expert, still working my way around these kinds of custom mods.

Thanks,
Marc

**Comment by SashaGeekette** [comment]
No. We just got an mnTouch from its git repository and used the appropriate attribute on the tag we were interested in listening to. I think if you have an additional event such as a click on the same element you want to use mnTouch for both events. We didn't touch Ionic at all, just used mnTouch where we had problems.

 -----"Marc Syp" <notifications@github.com> wrote: -----

 =======================
 To: "driftyco/ionic" <ionic@noreply.github.com>

**Comment by SashaGeekette** [comment]
Please see: https://github.com/driftyco/ionic/issues/1729#issuecomment-73750595

 -----"Marc Syp" <notifications@github.com> wrote: -----

 =======================
 To: "driftyco/ionic" <ionic@noreply.github.com>

**Comment by adamdbradley** [comment]
This issue has been fixed with the most recent updates to nightly. Tested Android 4.4.4.

**Comment by marcsyp** [comment]
Great!  This actually worked for me, too.  It requires some messing with the default thresholds to get right when you're inside a slide box and using other interactions, but it is MUCH better than the broken interactions I had before.

Thanks!

Marc

**Comment by DEllingsworth** [comment]
This seems to still be broken.  I tested this today on an s5 running 4.4.4.  Using mnTouch still solved the issue for us.

Codepen here:
http://codepen.io/dellingsworth/pen/JopVRB

-Don
