### ISSUE TITLE
Loading icon of infinte-scroll not showing with collection-repeat

### ISSUE THREAD

**Issue by matiastucci** [driftyco/ionic#2376]
Using `ng-repeat` (loading icon appears): http://codepen.io/anon/pen/CBtEg
Using `collection-repeat` (doesn't appear): http://codepen.io/matiastucci/pen/wkECs

Probably because of this?:

"You should not use the ng-show and ng-hide directives on your ion-content/ion-scroll elements that have a collection-repeat inside. ng-show and ng-hide apply the display: none css rule to the content's style, causing the scrollView to read the width and height of the content as 0. Resultingly, collection-repeat will render elements that have just been un-hidden incorrectly."

I know this is something small, but if you can fix it: great!

Thanks!

**Comment by jvannistelrooy** [comment]
@lanceli, why don't you make a pull request for your bugfix?

**Comment by lanceli** [comment]
@perrygovier @ajoslin 
Does not work in nightly 1081, reopen issue please.

**Comment by jryu01** [comment]
I'm experiencing this problem with nightly build.

**Comment by ajoslin** [comment]
I don't see a problem with http://codepen.io/anon/pen/CBtEg in the nightly builds

**Comment by lanceli** [comment]
@ajoslin 
Your codepen is ng-repeat, the issue with collection-repeat

**Comment by ajoslin** [comment]
Fixed. Had to set the items after the collection repeat to display: block to make them always get the right size.

**Comment by luofan189** [comment]
It seems that this issue appears again in rc.5. The icon shows when using ng-repeat but not collection-repeat

**Comment by jamesgecko** [comment]
Yep. This worked in 1.0rc1 and is broken in 1.0.

**Comment by mvidailhet** [comment]
+1, broken for me in 1.0

**Comment by thpoul** [comment]
+1 for me

**Comment by hbmartin** [comment]
Broken for me as well :crying_cat_face:

**Comment by mica16** [comment]
Broken for me too with 1.0 ;)

**Comment by machei** [comment]
+1 reopen!

**Comment by SatadruBhattacharjee** [comment]
Broken for me with latest 1.0

**Comment by JWesorick** [comment]
+1!

**Comment by JWesorick** [comment]
@perrygovier @ajoslin Any update on when this may be fixed or a work around?

**Comment by degamer106** [comment]
BUMP

**Comment by jordansitbon** [comment]
UP! +1!

**Comment by swiftyone** [comment]
For me a simple workaround did the trick until it is fixed:
```css
ion-infinite-scroll:not(.active) .spinner,
ion-infinite-scroll:not(.active) .icon:before {
  	display: inline-block;
}
```

It is not mandatory that the icon is only visible if the `ion-infinite-scroll`-Element is active if you use a `ng-show` or `ng-if` directive:

```html
<ion-infinite-scroll ng-show="showInfinite" icon="ion-load-c" on-infinite="loadData()">
</ion-infinite-scroll>
```

**Comment by shivarad** [comment]
ion-infinite scrolling is not working for me in v1.1.0 for vs2015 package of phongeap!
