### ISSUE TITLE
collectionRepeat can't scroll the list with the deceleration, issue started from beta.12

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2393]
When use mouse to scroll the list items in collectionRepeat, the output logs will be like this

![image](https://cloud.githubusercontent.com/assets/1271739/4625176/2f971c26-5372-11e4-8031-d2a077e628bc.png)

The deceleration scrolling will be stopped prematurely. The reason is before the __decelerationVelocityY reach the throttle value, the "stop()" function is triggered and it will clear the "running[id]=null"

The issued is caused by the "scroll.resize" event. The handler of "scroll.resize" is hooked by 
    
     scrollCtrl.$element.on('scroll.resize', rerenderOnResize);

The "stop()" causing scrolling stopped is invoked as the following chain

    rerenderOnResize() -> scrollView.resize() -> this.setDimensions()-> self.scrollTo(self.__scrollLeft, self.__scrollTop, true, null, true);->zyngaCore.effect.Animate.stop(self.__isDecelerating);

Even the call "self.__publish(left, top, zoom, animate, wasResize);" will cause the "scroll" event, which cause the "stop", is triggered through "triggerScrollEvent()". 

## Temporary Solution:
If we disable the call "scrollCtrl.$element.on('scroll.resize', rerenderOnResize);" the issue will be solved. The output of the log will be like the following

![image](https://cloud.githubusercontent.com/assets/1271739/4625483/e6914178-5376-11e4-8eb4-039483e99533.png)

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
