### ISSUE TITLE
ion-slide pager overlays the slide itself

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2396]
Without custom styles, it looks like when using the ion-slide directive, the pager overlays the slide itself.

I have been told a fix is to custom define a height, although I feel this should be fixed in the library itself.

**Comment by archcra** [comment]
I use the following style to make the pager below:

.emoji {
    width: 225px;
}

.slider {
    padding-bottom: 10px;
}
.slider-pager {
    top: initial ;
    bottom: 2px ;
}
