### ISSUE TITLE
ionicPopup - Strange effect when popup is closing.

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2397]
I have done a copy/paste of ionicPopup example (http://ionicframework.com/docs/api/service/$ionicPopup/), but I had a problem in Samsung Galaxy Nexus Android 4.3 deploy. When the popup is closing it causes an strange effect, instead could do an animation/transition.

**Comment by mhartington** [comment]
Not seeing this in 1.0.1. Closing for now.
