### ISSUE TITLE
collectionRepeat hides infinite scroll animation

### ISSUE THREAD

**Issue by marcusnunes** [driftyco/ionic#2399]
Hi,
When I use infinite scroll with a collectionRepeat list, the loading animation icon doesn't show up.

Thank you.

**Comment by thesabbir** [comment]
:+1: 
Any workarounds?

**Comment by felquis** [comment]
I'm using $ionicLoading, but seems like it was fixed recently in a
commit... Or will be fixed in the next release
Em 21/01/2015 17:53, "Sabbir Ahmed" <notifications@github.com> escreveu:
