### ISSUE TITLE
Question: How to improve performance when changing tabs?

### ISSUE THREAD

**Issue by petermetz** [driftyco/ionic#2403]
Hi,

I have some `ion-tab` components all containing a couple images (relatively smaller ones all below 50KB in size).
On devices with decent hardware specs (iPhone 6, Nexus 5) I can see how the content (the images) gets re-rendered. In case of an image placed on the same spot on each tab it looks like the image is flashing when one is changing tabs.

I traced the issue back to the `ionNavView` directive and it's backing `$ionicViewService` service where I can see that on every tab change the old tab's DOM is removed and the new ones is re-appended.

What I would like to achieve is this (and my question is how to do it): 
Keep all the tabs in the DOM once they were loaded (or load all of them initially, a slightly longer splash-screen time is not an issue) and when changing tabs, just hide/show the appropriate ones. If the controllers/scopes still get recreated that's not an issue they shouldn't do things that are compute-heavy anyways.

I understand that this might make the DOM heavy, and the app a bit slower/memory hungrier in general, but it's a fair trade-off to keep navigation snappy since that's the first place where hybrid web-apps usually stay far behind apps made from native components.

Any help on this is greatly appreciated. I did some quick modifications myself, trying to avoid removing the tabs' DOM and reusing it later but it wasn't as trivial as I thought it would be (pointers on how to do it in the code of the mentioned ionic components would be most welcome as well).

Thanks in advance,
Peter

**Comment by sean-hill** [comment]
Hi @adamdbradley, I'm still having this similar issues with `1.0.0 latest`. Images still flash a bit and the biggest issue I have is that when I switch tabs (before it's cached) elements of the previous tab get intermingled with elements from the new tab for a split second. Then disappear. It's kinda annoying and weird looking to see divs mixed together between views. Thanks for any suggestions you can provide.

**Comment by sean-hill** [comment]
Hmmm, maybe I take this back, it might be an issue with my code. I have an element on the screen that I'd like hidden by default, and then shown with `ng-show`, I'm using `ng-cloak`, but it doesn't appear to cloak it, time for me to figure out why :)
