### ISSUE TITLE
bug: The date picker does not work correctly inside a popOver

### ISSUE THREAD

**Issue by mlopezsegura** [driftyco/ionic#24048]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Ionic v6 with Angular Version 12.0.0
The date picker does not work correctly inside a popOver.
- The event is not fired correctly so the value is not emitted.
-Buttons are not styled inside the PopOver 
It is impossible to select a month using the arrows

Demo video
https://user-images.githubusercontent.com/90263997/136588122-f464dbde-08d5-462f-aba9-aafc5d5550cc.mp4

### Expected Behavior

The selector should link the input variable (ngModel).
Buttons should be styled inside the Popover
The month buttons should let you select the month without the selector going crazy

### Steps to Reproduce

Make a new component that will open using the PopOvers controller:
HTML:
`<ion-content>
    <ion-datetime [(ngModel)]="this.dateValue" [min]="this.min" [max]="this.max" locale="es-ES" first-day-of-week="1" 
       [presentation]="this.presentation"  [showClearButton]="true"  style="width: 105%;">
      <div slot="title">{{this.label}}</div>
      <ion-buttons slot="buttons">
        <ion-button  fill="outline" (click)="dismiss()">Cancelar</ion-button>
        <ion-button fill="outline" (click)="dismiss(true)">Aceptar</ion-button>
      </ion-buttons>
    </ion-datetime>
</ion-content>
`

Make the component act as a proxy
HTML:
`<ion-item (click)="openPopOver($event)">
  <ion-label position="floating">
    {{this.label}}
  </ion-label>
  <ion-input readonly></ion-input>
</ion-item>`

TS:
`async openPopOver(ev){
    const popover = await this.popoverController.create({
      component: PopOverDateTimeComponent,
    );
    await popover.present();
  }`

### Ionic Info

[WARN] Error loading @capacitor/core package.json: Error: Cannot find module '@capacitor/core/package'

       Require stack:
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.17.0 (C:\Users\mariolopez\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.0
   @angular-devkit/build-angular : 12.2.4
   @angular-devkit/schematics    : 12.2.7
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : not installed
   @capacitor/ios     : not installed

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.13.0
   OS     : Windows 10

**Comment by enriqueloz88** [comment]
Same bug as #23992
