### ISSUE TITLE
bug: ion-label seems invalid (red color) with angular validators when loading view 

### ISSUE THREAD

**Issue by enrique-lozano** [driftyco/ionic#24049]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Well, the truth is that this bug is difficult for me to explain. Simply by using the angular validators, if we make a form with a required input when loading the page, the label appears in red, but the bottom line does not. Once we focus on the input if the bar below is colored red as it should be, since the user has not yet entered anything, as well as when the focus is lost if the input is empty. However, as I said, when loading the app that label should not be red.

This is something that did not happen with ionic 5.8

I attach code with this behavior

### Expected Behavior

The text on the label should have a normal color

### Steps to Reproduce

See the attached code

### Code Reproduction URL

https://github.com/enriqueloz88/label-bug-ionic6

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\kikel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.0 (C:\Users\kikel\Documents\test-input\node_modules\@ionic\angular)
   @angular-devkit/build-angular : 12.1.4 (C:\Users\kikel\Documents\test-input\node_modules\@angular-devkit\build-angular)
   @angular-devkit/schematics    : 12.1.4 (C:\Users\kikel\Documents\test-input\node_modules\@angular-devkit\schematics)
   @angular/cli                  : 12.1.4 (C:\Users\kikel\Documents\test-input\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 4.0.0 (C:\Users\kikel\Documents\test-input\node_modules\@ionic\angular-toolkit)

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : 3.2.4 (C:\Users\kikel\Documents\test-input\node_modules\@capacitor\core)
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hi everyone,

It looks like this was resolved in https://github.com/ionic-team/ionic-framework/pull/24072, but we forgot to close the ticket out. I am going to close this, but let me know if there are any questions.
