### ISSUE TITLE
docs: Documentation error for iOS developers on OS X

### ISSUE THREAD

**Issue by smokymountains** [driftyco/ionic#2407]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>On this page, http://ionicframework.com/getting-started/, if you follow the documentation and build the app using only the command "ionic start myApp tabs/blank/whateva", if you add any plugins and then try to build, it will fail every time. Instead, if you issue the optional -a "some name" and -i "com.mycompany.app" parameters on build, adding plugins will then build successfully. Maybe this is documented more clearly somewhere else but I've seen a lot of similar questions in forums over the past 2 hours I've been researching this - finally found the answer on a Phonegap forum. Tried it with ionic, and boom, worked. No build errors when including plugins. Wondering if there's an opportunity to make these more clear for ionic/phonegap/cordova virgins such as myself.</span>

<span is-issue-template></span>

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#243
