### ISSUE TITLE
bug: Failed to run "ant -version"

### ISSUE THREAD

**Issue by sb8244** [driftyco/ionic#2417]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I recently upgraded to Yosemite on OSX. When I run `ionic build android` or `ionic emulate android` I get a warning about ant not being in the path. However, ant -version runs just fine and which ant shows the proper location which should always be in my PATH.

Has this happened to anyone else on Yosemite? I will try to reinstall ant.</span>

<span is-issue-template></span>

**Comment by killerog** [comment]
Is fixing the documentation not a better solution than closing the issue? It's still not in the documentation.
