### ISSUE TITLE
iOS Popover

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic#2428]
I had some problems with the popovers on iOS. Without `org.apache.cordova.device` the my header is behind the statusbar and the popover is like this pen: http://codepen.io/ionic/pen/GpCst

With the `org.apache.cordova.device` Plugin there is a gap before the `ion-header-bar`.

This is the code of my Popover
```
<ion-popover-view>
	<ion-header-bar class="item-input-inset">
		<label class="item-input-wrapper"> <i class="icon ion-ios7-search placeholder-icon"></i> <input type="search" placeholder="Search"> </label>
		<button class="button button-clear button-assertive" ng-click="closePopoverSearch()">
			Fertig
		</button>
	</ion-header-bar>
	<ion-content>
		<div class="list">

			<div class="item item-divider">
				So., 27. Sep.
			</div>

			<div class="item item-avatar" href="#">
				<div class="item-image">
					11:00
					<br />
					12:00
				</div>
				<h2>Meeting 1</h2>
				<p>
					Schlossallee
				</p>
			</div>
		</div>
	</ion-content>
</ion-popover-view>
```

![without divide plugin](https://cloud.githubusercontent.com/assets/1868482/4718614/9647ab38-5922-11e4-88ab-bd9c1c6f7d8e.PNG)

![with divide plugin](https://cloud.githubusercontent.com/assets/1868482/4718615/967571d0-5922-11e4-913c-c7cb3d987da8.PNG)

**Comment by Ionitron** [comment]
Greetings @schnti!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
