### ISSUE TITLE
Hide footer

### ISSUE THREAD

**Issue by icebergdelphi** [driftyco/ionic#2435]
Hi to all, Does exist a way to hide the footer bar? i mean, i just need to hide the footer bar in the main (welcome screen) screen, i actually have the header bar hide (). Thank you.

**Comment by ghadeerrahhal** [comment]
The <ion-footer> is very tricky to show/hide. After a lot of trial and error I got it working by using an ng-if on the ion-footer. I've attached a codepen, hope this helps you. http://codepen.io/ghadeer/pen/XJpxJP?editors=101

**Comment by icebergdelphi** [comment]
ghadeerrahhal Thank you that's really works so good. Thank you again. ;)

**Comment by riteshjagga** [comment]
Thank you, `ng-if` worked. Upon trying many times, I noticed that `ng-show` works if you set the variable in a `$timeout`.

**Comment by ghadeerrahhal** [comment]
I've also found when ng-if doesn't work, if you bind the value to $rootScope, it will work. Obviously use sparingly but a potential workaround if necessary.
