### ISSUE TITLE
ion-content setting overflow-scroll="{{conditional()}}" not working

### ISSUE THREAD

**Issue by bwalsh** [driftyco/ionic#2439]
Attempting to set overflow-scroll conditionally, depending if we are running in desktop browser or not.
<ion-content overflow-scroll="{{overflowScroll() && 'true' || 'false'}}"  >
This code works, if you inspect the element, you see overflow-scroll="true".  However, the behavior is not there (scrolling doesn't work)
However, if I simply hard code overflow-scroll="true" it works fine?

**Comment by Ionitron** [comment]
This will soon be a global configuration, and the attribute is currently receiving an overhaul. cc/ @perrygovier

**Comment by Elsioufy** [comment]
+1 I have the same issue here

**Comment by wikiziner** [comment]
+1

**Comment by mhartington** [comment]
Instead of that, you could do this. 

```
.config(function($ionicConfigProvider){
   if(condition1) {
    $ionicConfigProvider.scrolling.jsScrolling(false)
  } else {
    $ionicConfigProvider.scrolling.jsScrolling(true)
  }
});
```

Or in a controller

```
.controller('MainCtrl', function($ionicConfig){
    $ionicConfig.scrolling.jsScrolling(false)
});
```
```

**Comment by Elsioufy** [comment]
@mhartington I have an older version of ionic,  jsScrolling requires updating ionic and upgrading requires doing a lot of changes to match the new ionic version, is there any workarounds for overflow-scroll to work as a conditional attribute?

**Comment by mhartington** [comment]
Unfortunately no, there isn't.

**Comment by jdnichollsc** [comment]
+1 :(
