### ISSUE TITLE
feat: Add class to changing item in collectionRepeat

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic#2447]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be nice the collectionRepeat to add a class whenever it's changing the scope of a reused item. This way, it would be really easy to fix this issue:

http://plnkr.co/edit/gm8wxfSGoMd7KwM1hemv?p=preview
We have a bunch of toggles here. If you scroll fast enough down, you will see "phantom" activated toggles that are transitioning to unchecked. From a user's view that's confusing because if they scroll fast, they might  first see items actived but when he re-checks they are not.
Also, of course, if you scroll up fast enough, you can see the toggles transition back from off to on.

Adding a class to the item that's changing his scope you can then nullify all transitions of it's children. By now I "patched" my app by editing ionic.bundle, in the function `attachItemAtIndex` of `CollectionRepeatDataSource.prototype`, adding `item.element.addClass("collection-repeat-change");` when it's changing the scope, and then doing `$timeout(function(){ item.element.removeClass("collection-repeat-change"); });` to remove it after it's rendered.

Without your permission I won't create a pull request because I think that `$timeout` is really dirty, but I don't know any other way to fix it.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @voliva!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by voliva** [comment]
This issue should still be up. It wasn't a duplicate of #2504, although it is releated.
It's still happening in 1.0.0-RC4.
