### ISSUE TITLE
Responsive Classes

### ISSUE THREAD

**Issue by lingz** [driftyco/ionic#245]
Is there a possibility of adding responsive classes to the framework? It would be nice to be able to build a web app, tablet app and mobile app all at once, but the gridding system provided does not provide responsive elements - so this is difficult.

**Comment by helmuthva** [comment]
+1

**Comment by jamespacileo** [comment]
+1

**Comment by gtrias** [comment]
+1

**Comment by Hacktivista** [comment]
+1

**Comment by ashah-kaira** [comment]
+1

**Comment by joewoodhouse** [comment]
+1

**Comment by newtondev** [comment]
Hi guys, any movement here. Would be nice to have a tablet layout and also portrait/landscape customization.

+1

**Comment by boboldehampsink** [comment]
@adamdbradley your example above is broken, I'd like to know how to implement the navigation stack

**Comment by iBasit** [comment]
+1  - &  plus 1 million customers :)

**Comment by jerrx** [comment]
+1

**Comment by israel-viveros** [comment]
+1

**Comment by vthil3049** [comment]
+1

**Comment by bariza** [comment]
+1

**Comment by rockykitamura** [comment]
+1

**Comment by dingvarson** [comment]
+1 

Even a guide on how to make tablet version would be appreciated.

**Comment by tomneedham** [comment]
+1
