### ISSUE TITLE
Ionic requires global npm installation

### ISSUE THREAD

**Issue by bentomas** [driftyco/ionic#2451]
I don't install npm packages globally, as I like all of my dependencies to be specified in a `package.json` file and stored within the `CWD` of my project.  I always add `./node_modules/.bin` to my path, so I am easily able to run commands.  

I installed Ionic and Cordova using the following line:

    npm install cordova ionic

I have no problem running both the `ionic` and `cordova` executables from the command line, as they are in my path.  Then I created a project with:

    ionic start myApp tabs

And this is the output:

```
Creating Ionic app in folder PATH based on tabs project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
/bin/sh: cordova: command not found
Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again. (CLI v1.2.8)
```

If Ionic depends on Cordova, then it should list Cordova as a dependency in `package.json`. But since it seems like it is clear you aren't interested in doing that, it should at least look in the current `$PATH` for the executable and run from there.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#235
