### ISSUE TITLE
[Feature Request] Implementing Photo browser (similar to IOS photo browser)

### ISSUE THREAD

**Issue by seme1** [driftyco/ionic#2453]
I am trying to implement a photo browser that is similar to the one built in IOS for browsing album photos.

I could use ionic slide box, but the photos need to be full screen when viewed, scrollable AND zoomable. I am not sure how to make the images zoomable.

Any hints or a working example would be greatly appreciated.

p.s. what I am trying to implement is very similar to the photo browser at the following link:
http://www.idangero.us/framework7/kitchen-sink/

**Comment by kevincobain2000** [comment]
> p.s. what I am trying to implement is very similar to the photo browser at the following link:
@seme1 https://github.com/kevincobain2000/ionic-photo-browser

Have a look at the above. I had been using it in my apps and it works nicely
