### ISSUE TITLE
v1.0.0-beta.13: after $collectionRepeatManager is destroyed, its resize() doesn't check calculateDimensions() returned value before accessing the dimension. 

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2457]
when scope is destroyed, $collectionRepeatManager will call the following function. But the directive 'collectionRepeat' doesn't remove the 'scroll' event handler 'rerenderOnResize()'. When 'collectionRepeatManager.resize();' is called, the 'angular.noop'  return undefined and exception is thrown.

    destroy: function() {
      this.renderedItems = {};
      this.render = angular.noop;
      this.calculateDimensions = angular.noop;
      this.dimensions = [];
    },

**Comment by ajoslin** [comment]
Fixed in bb866da3d7e539c8923bd6914c0a4e44f0f4d400
