### ISSUE TITLE
Add ability to specify address/interface from command line

### ISSUE THREAD

**Issue by frankcarey** [driftyco/ionic#2461]
Trying to get some CI testing working with codeship.io and I ran across the issue of having to choose the address for ionic serve. The hack below worked, but this should really be an option from the command line, just like port is a option.

    //This chooses option 2 which in my case is localhost
    echo 2 | ionic address
    ionic serve --nobrowser --nolivereload

**Comment by jbavari** [comment]
@frankcarey - this should be available in CLI v1.3.3. You can specify `ionic serve --address 192.168.1.100`

Thanks
