### ISSUE TITLE
Not working the app in android

### ISSUE THREAD

**Issue by nekulin** [driftyco/ionic#2469]
When I want to add a camera or notice I always collapses

	W/dalvikvm(  597): VFY: unable to resolve static method 212: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
	D/dalvikvm(  597): VFY: replacing opcode 0x71 at 0x0001
	D/CordovaWebView(  597): CordovaWebView is running on device made by: unknown
	I/CordovaWebView(  597): Disabled addJavascriptInterface() bridge since Android version is old.
	D/CordovaWebView(  597): >>> loadUrl(file:///android_asset/www/index.html)
	D/PluginManager(  597): init()
	W/System.err(  597): java.lang.ClassNotFoundException: org.apache.cordova.file.FileUtils
	W/System.err(  597): 	at java.lang.Class.classForName(Native Method)
	W/System.err(  597): 	at java.lang.Class.forName(Class.java:217)
	W/System.err(  597): 	at java.lang.Class.forName(Class.java:172)
	W/System.err(  597): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:345)
	W/System.err(  597): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:189)
	W/System.err(  597): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:114)
	W/System.err(  597): 	at org.apache.cordova.PluginManager.init(PluginManager.java:92)
	W/System.err(  597): 	at org.apache.cordova.CordovaWebView.loadUrlIntoView(CordovaWebView.java:383)
	W/System.err(  597): 	at org.apache.cordova.CordovaWebView.loadUrlIntoView(CordovaWebView.java:368)
	W/System.err(  597): 	at org.apache.cordova.CordovaWebView.loadUrl(CordovaWebView.java:344)
	W/System.err(  597): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:376)
	W/System.err(  597): 	at com.ionicframework.myapp829869.myApp.onCreate(myApp.java:32)
	W/System.err(  597): 	at android.app.Activity.performCreate(Activity.java:4465)
	W/System.err(  597): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
	W/System.err(  597): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
	W/System.err(  597): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
	W/System.err(  597): 	at android.app.ActivityThread.access$600(ActivityThread.java:123)
	W/System.err(  597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
	W/System.err(  597): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	W/System.err(  597): 	at android.os.Looper.loop(Looper.java:137)
	W/System.err(  597): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
	W/System.err(  597): 	at java.lang.reflect.Method.invokeNative(Native Method)
	W/System.err(  597): 	at java.lang.reflect.Method.invoke(Method.java:511)
	W/System.err(  597): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	W/System.err(  597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	W/System.err(  597): 	at dalvik.system.NativeStart.main(Native Method)
	W/System.err(  597): Caused by: java.lang.NoClassDefFoundError: org/apache/cordova/file/FileUtils
	W/System.err(  597): 	... 26 more
	W/System.err(  597): Caused by: java.lang.ClassNotFoundException: org.apache.cordova.file.FileUtils
	W/System.err(  597): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
	W/System.err(  597): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	W/System.err(  597): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	I/Process (   77): Sending signal. PID: 597 SIG: 3
	I/dalvikvm(  597): threadid=3: reacting to signal 3
	I/dalvikvm(  597): Wrote stack traces to '/data/anr/traces.txt'
	W/System.err(  597): 	... 26 more
	I/System.out(  597): Error adding plugin org.apache.cordova.file.FileUtils.
	D/AndroidRuntime(  597): Shutting down VM
	W/dalvikvm(  597): threadid=1: thread exiting with uncaught exception (group=0x409c01f8)
	E/AndroidRuntime(  597): FATAL EXCEPTION: main
	E/AndroidRuntime(  597): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionicframework.myapp829869/com.ionicframework.myapp829869.myApp}: java.lang.NullPointerException
	E/AndroidRuntime(  597): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
	E/AndroidRuntime(  597): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
	E/AndroidRuntime(  597): 	at android.app.ActivityThread.access$600(ActivityThread.java:123)
	E/AndroidRuntime(  597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
	E/AndroidRuntime(  597): 	at android.os.Handler.dispatchMessage(Handler.java:99)
	E/AndroidRuntime(  597): 	at android.os.Looper.loop(Looper.java:137)
	E/AndroidRuntime(  597): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
	E/AndroidRuntime(  597): 	at java.lang.reflect.Method.invokeNative(Native Method)
	E/AndroidRuntime(  597): 	at java.lang.reflect.Method.invoke(Method.java:511)
	E/AndroidRuntime(  597): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	E/AndroidRuntime(  597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	E/AndroidRuntime(  597): 	at dalvik.system.NativeStart.main(Native Method)
	E/AndroidRuntime(  597): Caused by: java.lang.NullPointerException
	E/AndroidRuntime(  597): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:191)
	E/AndroidRuntime(  597): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:114)
	E/AndroidRuntime(  597): 	at org.apache.cordova.PluginManager.init(PluginManager.java:92)
	E/AndroidRuntime(  597): 	at org.apache.cordova.CordovaWebView.loadUrlIntoView(CordovaWebView.java:383)
	E/AndroidRuntime(  597): 	at org.apache.cordova.CordovaWebView.loadUrlIntoView(CordovaWebView.java:368)
	E/AndroidRuntime(  597): 	at org.apache.cordova.CordovaWebView.loadUrl(CordovaWebView.java:344)
	E/AndroidRuntime(  597): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:376)
	E/AndroidRuntime(  597): 	at com.ionicframework.myapp829869.myApp.onCreate(myApp.java:32)
	E/AndroidRuntime(  597): 	at android.app.Activity.performCreate(Activity.java:4465)
	E/AndroidRuntime(  597): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
	E/AndroidRuntime(  597): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
	E/AndroidRuntime(  597): 	... 11 more
	W/ActivityManager(   77):   Force finishing activity com.ionicframework.myapp829869/.myApp
	W/WindowManager(   77): Failure taking screenshot for (180x300) to layer 21010
	I/Process (   77): Sending signal. PID: 597 SIG: 3
	I/dalvikvm(  597): threadid=3: reacting to signal 3
	I/dalvikvm(  597): Wrote stack traces to '/data/anr/traces.txt'
	I/ActivityManager(   77): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ionicframework.myapp829869/.myApp} from pid 180
	W/ActivityManager(   77): Activity pause timeout for ActivityRecord{41481ac8 com.ionicframework.myapp829869/.myApp}
	I/Process (   77): Sending signal. PID: 597 SIG: 3
	I/dalvikvm(  597): threadid=3: reacting to signal 3
	I/dalvikvm(  597): Wrote stack traces to '/data/anr/traces.txt'

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
