### ISSUE TITLE
Clear input X 

### ISSUE THREAD

**Issue by ajbraus** [driftyco/ionic#2473]
Hi Ioniconians,

As always love the work you guys do.

I had a fanastic and simple feature request. Can you extend <input> to include a "clear-icon" attribute to add a little x in the input field that when tapped clears the input?

Very simple, I even might be able to build it myself. But I thought if you guys are already on making the best framework possible, I would throw it out there.

Thanks!

**Comment by Ionitron** [comment]
Greetings @ajbraus!

Thank you for the feature request. We will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
