### ISSUE TITLE
bug: using the $location angular service to change the URL breaks $ionicViewService

### ISSUE THREAD

**Issue by drbeermann** [driftyco/ionic#2481]
This gets into the weeds a little bit... I'm managing some simple view state using `$location.search`. For example, I might want to keep track of what the user picked from a select box so that if they hit back and get back to the same view, the selection is populated correctly. You can obviously use another service for this, but you already have the tools baked into UI Router and the state parameters, which we're already using, so it'd be nice to have a single way to manage this.

So when defining my views, I'm using `reloadOnSearch: false` on our states so that we aren't adding things onto the history stack. Then when a user makes a selection, you use `$location.search('param', paramValue)`. The user can then navigate away to another page and hit back, and the `$stateParams` will have the correct value in it. However, internally this breaks `$ionicViewService`'s `getCurrentStateId()` function because the state ID uses the state parameters. The resulting symptom is that the sliding transitions between views do not go in the correct direction - it looks to the user like you keep going forward, instead of the back button sliding the previous view the opposite way.

There is a workaround, but it's ugly. After calling `$location.search` you can update Ionic's view history so that it is correct doing the following:

> $state.params.param = paramValue; // Important because this is referenced by Ionic
> $ionicViewService.getCurrentView().stateId = $ionicViewService.getCurrentStateId(); // This uses the above paramValue

I'm not sure if you can use the `$location` service to listen for `$locationChangeStart` events even when you aren't refreshing the view, I haven't tried.

**Comment by Ionitron** [comment]
Greetings @drbeermann!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
