### ISSUE TITLE
Support automatic list dividers

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#2484]
One of the nice features of jQuery Mobile is the ability to create automatic list dividers (http://api.jquerymobile.com/listview/#option-autodividers). It supports both automatic dividers (uses the first character of the list item) as well as the ability to write a simple function that returns the 'key' for a list item to be used for categorization purposes. Ionic should just plain steal this as is.

**Comment by Ionitron** [comment]
Greetings @cfjedimaster!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen it and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by cfjedimaster** [comment]
I don't believe this feature was added yet, and I think it is handy. I'd like this to be reopened, or, have someone from the team "formally" say no. :)

**Comment by daemonk** [comment]
I would + this as a great feature to have. Please implement it ;)

**Comment by cfjedimaster** [comment]
While not baked in to the core product, you can get this now here: http://mcgivery.com/dividing-list-automatically-ionic-framework

**Comment by daemonk** [comment]
That is awesome thanks! working a treat

**Comment by JWGmeligMeyling** [comment]
After experimenting a bit with `ionic.ion.autoListDivider` I quickly found that it [doesn't work](http://mcgivery.com/dividing-list-automatically-ionic-framework/) with `collection-repeat`, and after looking a bit into `collection-repeat`, I found that this is probably not to easy to solve there, as the list dividers need to be in the collection such that the `collectionRepeatManager` can position it.

For `collection-repeat` the only current alternative is to use `ng-class="{'item-divider': item.isDivider}"` (#348). Which would have been no problem for me if it was just the single `ng-class`, but I find myself using alot of `ng-ifs` within the repeat as well.

So I think preferably the `collection-repeats` gets equipped with divider generating options?

**Comment by cameronbourke** [comment]
+1 to auto dividers.
