### ISSUE TITLE
docs: Why does `ionic platform ios` create Staging group

### ISSUE THREAD

**Issue by intelliot** [driftyco/ionic#2486]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Why does `ionic platform ios` create Staging group with a copy of the files under www going under the "platforms" directory? This is extremely annoying because it means that my changes need to be made twice every time, or I need to keep running `ionic build ios` every time I make changes to the files in the root www directory.</span>

<span is-issue-template></span>

**Comment by superarts** [comment]
Yea unless ios-deploy crashes every time, so I have to `ionic build ios` then open xcode to test push related features.
