### ISSUE TITLE
list-detail issue.

### ISSUE THREAD

**Issue by choiks14** [driftyco/ionic#2490]
i made list.
if i clicked item then detail view was showed.

i was clicked back button on android.
the list shows always first item.

how can i?

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
