### ISSUE TITLE
Slidebox : Being able to disable vertical scroll

### ISSUE THREAD

**Issue by QuentinFchx** [driftyco/ionic#2492]
I'd like to disable the vertical scroll that can happen with a slidebox
I found [this line](https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L7176) that does the trick. How can I access this option (`options.disableScroll`) from ionic ?

Also, from where come this fork of Swipe ? I cannot find it except in this built file.

**Comment by anujsphinx** [comment]
<ion-content has-bouncing="false" scroll="false"> is working but i want to scroll my page and <ion-content has-bouncing="false"> is not effective .
**_Need Help to fix that issue._**

**Comment by cagb80** [comment]
Fixed:`ion-content
		.scroll-content
			overflow: hidden`
