### ISSUE TITLE
bug: In Angular and Windows desktop, an ion-item with button attribute does not fire ripple effect when inside <swiper> component

### ISSUE THREAD

**Issue by ntorrey** [driftyco/ionic#24931]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In Angular and Windows desktop an ion-item with button attribute does not fire ripple effect when inside swiper component

### Expected Behavior

In Angular and Windows desktop an ion-item with button attribute should fire ripple effect even when inside swiper component

### Steps to Reproduce

1. Initialize a blank ionic/angular app.
2. place an ion-item component with a button attribute inside a swiper component.
3. Run the app in chrome on Windows desktop (haven't tried in Mac/Safari or other browsers)
4. Click the ion-item component and the ripple-effect doesn't happen.

### Code Reproduction URL

https://github.com/ntorrey/swiper-ripple-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.2
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.4
   OS     : Windows 11

### Additional Information

This is the first time I've ever filed a bug report. Hopefully I've done everything right.

**Comment by sean-perkins** [comment]
@ntorrey thanks for reporting this issue.

Unfortunately after triaging the problem, it appears to be an issue with Swiper itself and will require a change on their end. Any manually added `mousedown`/`mouseup` events are ignored completely when rendered inside of the `<swiper>` component.

To emulate similar behavior to how the `ion-ripple-effect` functions, I tested with this component:
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'test-component',
  template: '<p>Testing</p>'
})
export class TestComponent {

  ngOnInit() {
    document.addEventListener('mousedown', function (e) {
      console.log('clicked', e);
    });
  }
}
```

When used within `swiper`, the event will never fire. When used outside of swiper, the event will fire correctly. 

Please let me know if this helps answer your question and provides you with enough detail to open an issue with swiper.

Thanks!

**Comment by ntorrey** [comment]
Thank you! I opened this issue with swiper here for reference: https://github.com/nolimits4web/swiper/issues/5549

**Comment by ntorrey** [comment]
This also affects the ion-reorder component on desktop, for the same reason. I'm not able to reorder items from within a swiper component.

**Comment by ntorrey** [comment]
@sean-perkins 
I discovered that an ion-item which contains a checkbox (but _without_ the button attribute applied) detects mousedown events even within the swiper component. As well, if I click on an ion-checkbox or ion-input directly, the mousedown event is detected.

I pushed more example to the code reproduction ([here](https://github.com/ntorrey/swiper-ripple-bug)). So maybe this _is_ a problem in Ionic?

**Comment by sean-perkins** [comment]
@ntorrey the `button` attribute for `ion-item` adds a clickable overlay over the whole item. It should not be used in combination with UI that has multiple or nested click targets. 

Are you able to share a screenshot of the UI you are trying to accomplish? This UI combination does not initially sound like something that belongs in a slider/swiper.

**Comment by ntorrey** [comment]
This is what I'm seeing in developer mode, using chrome on a Windows computer.

https://user-images.githubusercontent.com/56656692/160487203-564c5ed6-a0c7-40f6-85b3-da700686dcaf.mp4

**Comment by ntorrey** [comment]
@sean-perkins 
Same problem with the ion-reorder component:

https://user-images.githubusercontent.com/56656692/160637582-b07a901b-51e1-4241-af29-af5260b1ab4e.mp4

**Comment by ntorrey** [comment]
@sean-perkins 
Following up on this issue:
It seems to be better for the user experience to disable swiping on the elements that require interaction (for example, `ion-item`s that can be selected, or `ion-reorder` elements). To do this, one can simply apply the "swiper-no-swiping" class on the element which will disable swiping on those particular elements. This "re-activates" the mousedown/up events, allowing the ripple effect to work as normal or manipulation of `ion-reorder` items in an `ion-reorder-group`. So for my use case, this bug is a moot point. Should I keep it open as a "bug" still?

**Comment by liamdebeasi** [comment]
Hi everyone, 

Does this issue reproduce with Swiper 9?
