### ISSUE TITLE
collection-repeat input focus problem (keyboard hide shown multiple times)

### ISSUE THREAD

**Issue by kaushal2406** [driftyco/ionic#2494]
hi, 
i am using collection collection-repeat and it having input control when i click on input control which are at bottom area of screen probably keyboard area where keyboard is shown, key board shown and hide 1-2 times and in last hides automatically, in this page i also having footer at bottom, it losing focus of input control and i cant type the value in input box.

if i use simple ng-repeat then it working fine but when i have big list then it causing problem so i used the collection-repeat.

i think it may be problem of regenerating of control in collection-repeat. 

please share your thoughts with this problem causing me.
correct me if i am wrong somewhere.

**Comment by vevisystems** [comment]
We are experiencing a similar issue, after focus keyboard shows and just next it hides again (in the meantime the input has lost focus "magically", I guess this is the reason the keyboard hides).

**Comment by mhartington** [comment]
Could you please try the nightly builds

**Comment by ajoslin** [comment]
If this doesn't work in the nightly builds, we'll need a codepen to debug this further. Thank you.

**Comment by willadamskeane** [comment]
I'm also seeing this issue currently.
