### ISSUE TITLE
bug: 'gulp demos' put the demos in the wrong directory

### ISSUE THREAD

**Issue by louislarry** [driftyco/ionic#2497]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>README says 'gulp demos' will generate demos in dist/ionic-demo directory, instead in puts them in dist/nightly. 

'gulp demos --demo-version=(versionname|nightly) also generates the demos in the wrong directory.</span>

<span is-issue-template></span>

**Comment by brianfeister** [comment]
+1. For me, even navigating to `{ionic}/dist/nightly/nightly` and starting a simple python server from there 404's on a bunch of things so I think it's safe to say a bunch people aren't getting the demos up and running properly.

**Comment by msoni11** [comment]
I have the same issue with latest master branch ionic v1.3.1.

Isn't ionic team find it as a bug ?
