### ISSUE TITLE
feat: Center loading vertically using infinite-scroll

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2503]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'd like to center the loading-spinning in the center of screen horizontally and vertically using infinite-scroll.

Like in this example, http://codepen.io/felquis/pen/pCHim seems like there's no easy way to center the spinning vertically, since infinite-scroll reside inside .scroll that doesn't fit 100% of the height of the viewport like ion-pane does.

Would be nice to have a `center-vertically="true"` (or something like this) option in the infinite-scroll API session here http://ionicframework.com/docs/api/directive/ionInfiniteScroll/

Thanks.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Moving this to our trello board as it is a feature request. 

https://trello.com/c/lrqhyeT4/84-center-infinite-loading-icon-on-initial-load
