### ISSUE TITLE
Collection repeat still repeating item states when it shouldn't

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2504]
Refering to #1940, #1842, #1811 and #2447.

I am using v1.0.0-beta.13 and just tried it in v1.0.0-beta.13-nightly-650, this bug is still happening.
The codepen from #1811 still applies as it's using the latest nightly build: http://codepen.io/mhartington/pen/pnbiy

**Comment by ajoslin** [comment]
Fixed via 3befdd7429e2eebe5bb4d2af1bd66b5ee35f74da

**Comment by PureSpider** [comment]
This only applies to "swiped open" items, doesn't it?
What about all the other variations you could posibly have to an item, like checked checkboxes, toggled toggles etc.?

**Comment by ajoslin** [comment]
Those are all bound to scope values and should work fine as a result.

**Comment by PureSpider** [comment]
Indeed, they are still animating from their old to their new state if they are animated though.
