### ISSUE TITLE
Toggle with two labels

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2509]
Refering to #433.

Instead of changing the values for "true" and "false" I'd like to have something like:
`Hot (o=) Cold`
So a toggle with labels on both sides.
Is this currently possible?

**Comment by Ionitron** [comment]
Greetings @PureSpider!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
