### ISSUE TITLE
Side Menu will not open by gesture after fix for #2201

### ISSUE THREAD

**Issue by nokturnal** [driftyco/ionic#2511]
As instructed by @perrygovier, here is a new issue that reports a side effect from fix https://github.com/driftyco/ionic/commit/622667b3dec637bdd75dbf24b2d3e2a4b1142bc9 (to issue  https://github.com/driftyco/ionic/issues/2201) which re-enabled vertical scrolling with one finger back to SideMenuContent.  The side effect of this fix is that now the left to right swipe gesture to open the menu no longer functions.

Here is the easiest way to reproduce this issue:

Create new app via:
> ionic start scrollTest sidemenu

Modify "PlaylistsCtrl" Controller to ensure vertical scrolling:

    .controller('PlaylistsCtrl', function($scope) {
        $scope.playlists = [
            { title: 'Reggae', id: 1 },
            { title: 'Chill', id: 2 },
            { title: 'Dubstep', id: 3 },
            { title: 'Indie', id: 4 },
            { title: 'Rap', id: 5 },
            { title: 'Cowbell', id: 6 },
            { title: 'Breaks', id: 7 },
            { title: 'Jungle', id: 8 },
            { title: 'Drum & Bass', id: 9 },
            { title: 'Classics', id: 10 },
            { title: 'Blah', id: 11 },
            { title: 'Foo', id: 12 },
            { title: 'Bar', id: 13 },
            { title: 'House', id: 14 },
            { title: 'Trance', id: 15 },
            { title: 'EDM', id: 15 },
            { title: 'Country', id: 16 },
            { title: 'Rock', id: 17 }
        ];
    })

Set overflow-scroll to true in playlists.html:
`<ion-content class="has-header" overflow-scroll="true">...`

Apply above fix to line 43582 of ionic.bundle.js (v1.0.0-beta.13):

    //return 'x';
    return 'y';

Add Android as a platform:
> ionic platform add android

Launch app on device:
> ionic run android

The end result is vertical scrolling is re-enabled, but now the side menu does not slide out via the "left to right" gesture on a device (tested on Android).

**Comment by adamdbradley** [comment]
This should be fixed as of: https://github.com/driftyco/ionic/commit/a5881eaeba7d12d016fe3712c77261e75e863cf3
