### ISSUE TITLE
Release password prompt does not work in android build

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#2512]
Building with `ionic build --release` while the build system is configured to use a keystore and alias, prompts for a password, but the password is never sent to the underlying tools.

To reproduce the problem
=====================
create a file `platforms/android/ant.properties` with the following content:

    key.store=/path/to/release_store.keystore
    key.alias=alias_name

Generate your keystore (see: http://developer.android.com/tools/publishing/app-signing.html#signing-manually):

    keytool -genkey -v -keystore /path/to/release_store.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

Build with ionic:

    ionic build --release

Temporary solution
===============
Use cordova instead of ionic:

    cordova build --release

**Comment by linagee** [comment]
Did you mean:
```
cordova build android --release
```
(Or does it just use the first available platform it has which might be Android?)

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#238
