### ISSUE TITLE
Feature: Allow to hook ng-change to ion-toggle directive

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2515]
Currently one has to use the html version of the toggle if one wants the ability to use ng-change - it would be nice to be able to use ng-change with ion-toggle via attribute.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
