### ISSUE TITLE
Race condition on toggleMenu in headers

### ISSUE THREAD

**Issue by lingz** [driftyco/ionic#252]
There's a bug easily observed in this demo here:
http://ionicframework.com/examples/side-menu/#

When you click the Toggle on the top left, the menu opens as normal. However, when you click it again, it doesn't close. I investigated and found two competing functions that race:

It's from line 55-62 here:
https://github.com/driftyco/ionic/blob/master/js/controllers/sideMenuController.js

And line 67-69 here:
https://github.com/driftyco/ionic/blob/master/js/ext/angular/src/directive/ionicSideMenu.js

Essentially, when clicking close on the menu, it might either:
#1) First fire the menu tap close event, setting percentage to 0, and then fire the toggleLeft setting it back to 100, which results in no change which is wrong.
#2) Fire it in reverse order, which results in expected behavior.

The simple solution would be to create a lock which prevents the setPercentage function from running more than once every 100ms. Let me know if anyone has any better solutions.

**Comment by vanderleisp** [comment]
I'm trying to use this codepen http://codepen.io/ionic/pen/vqhzt with a newer version of Ionic but still couldn't.
From version 0.9.24 to the 0.9.25 the main change was the ion- directives, that I added, but don't know what else need to be changed as can't run it with any of the newer releases of Ionic.

**Comment by mhartington** [comment]
@vanderleisp take a look at our codepens which are all updated

http://codepen.io/ionic/pen/QwamEW
