### ISSUE TITLE
h2 not visible in subheader bar

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2521]
This is not visible as it gets pushed off the screen:
```html
<ion-header-bar class="bar-subheader">
	<h2 class="title">This is a subtitle in the </h2>
</ion-header-bar>
```
The h2 gets the viewport width added as left and right css element properties and thus is not visible at all:
`style="left: 1430px; right: 1430px;"`
If i remove the left and right css rules on the element, it displays just fine in the center of the bar.

It also works if I use h1 in the subheader bar but according to http://ionicframework.com/docs/components/#subheader I am supposed to use h2?

**Comment by elksson** [comment]
I have proposed the following fix for this issue https://github.com/driftyco/ionic/pull/2988
