### ISSUE TITLE
Keyboard covers inputs when statusbar is hidden

### ISSUE THREAD

**Issue by kl3ryk** [driftyco/ionic#2527]
I have a registration form in my app.
We noticed that the keyboard covers the content and there is no way to move to the covered inputs (first photo). When we turned off ```StatusBar.hide ();``` everything started to work (second picture).

Wrong:
![wrong](https://cloud.githubusercontent.com/assets/335431/4992500/992bc368-69a1-11e4-8dbc-ce81f9f3d314.png)

Propper
![good](https://cloud.githubusercontent.com/assets/335431/4992501/992be37a-69a1-11e4-8b1d-84936be32617.png)

**Comment by mhartington** [comment]
Is this still an issue?
