### ISSUE TITLE
feat: accept="image/*" is not Working

### ISSUE THREAD

**Issue by kapilkarda** [driftyco/ionic#2528]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I am creating image sharing app in which i will give a input type="file" and pass accept="image/*" but it can't give the option of selecting images it gives also music select box but i have to select images from both camera or gallery. Can someone help me.

Thanks in Advance !</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kapilkarda!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
