### ISSUE TITLE
very basic vertical scroll not working (except with nav views)

### ISSUE THREAD

**Issue by jeffthompson1971** [driftyco/ionic#2532]
With the latest beta, I can't even get very basic scrolling working.  by basic I just mean as:

\<ion-content  scroll="true"  overflow-scroll="true" has-bouncing="true" \> 
...
[bunch of stuff here that would need scrolling]
...
\</ion-content\>

NOTE that I have tried having no attributes to the ion-content directive.  I have tried wrapping the ion-content directive in ion-view and ion-pane.   there isn't a combination that allows me to scroll. 

I do have a more complex page that uses the nav functionality and scrolling in that context is fine.  Is this a known bug with the latest beta?

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
