### ISSUE TITLE
bug: changing iOS simulator device the app disappear

### ISSUE THREAD

**Issue by gio82** [driftyco/ionic#2535]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>iOS simulator: 8.1
Ionic: beta 13
Ionic CLI: 1.2.8
Cordova: 4.1.0

I run:  ionic emulate ios -l -c -s
The app starts on an iPhone 6 simulator ok.
When I try to change the device the app disappear from the simulator device. I'm not able to find the app in the home screen anymore.

This is something "new" because with iOS 7 (and old iOS simulator) all was fine.</span>

<span is-issue-template></span>

**Comment by cebraSpA** [comment]
Hi, jbavari, how I can specify the rotation of the device?

**Comment by sarahsuleri** [comment]
in your simulator menu, under hardware there are rotation of device
