### ISSUE TITLE
show-when directive

### ISSUE THREAD

**Issue by andrewmcgivery** [driftyco/ionic#2541]
Hello!

There was a topic on the forum about hiding content based on if you are on a tablet or phone.

http://forum.ionicframework.com/t/is-there-any-class-to-hide-some-content-on-mobile-screen/12557

I provided a solution by creating a custom directive based on the sidemenu's expose-aside-when directive that is usable on any element. (codepen here: http://codepen.io/andrewmcgivery/pen/WbNbwr)

Is there any value in adding this directive (or a similar directive) into the Ionic bundle? If yes, I can submit a pull request if given direction of where would be the best spot to put it.

Thanks.

**Comment by Ionitron** [comment]
Greetings @andrewmcgivery!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
