### ISSUE TITLE
Error thrown when scrolling on WebView Android 4.1.2

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic#2543]
When scrolling we get this error a lot:

"Uncaught TypeError: Cannot call method 'contains' of undefined"

It comes from this function
```
function tapHasPointerMoved(endEvent) {
        if (!endEvent || endEvent.target.nodeType !== 1 || !tapPointerStart || tapPointerStart.x === 0 && tapPointerStart.y === 0) {
            return false;
        }
        var endCoordinates = ionic.tap.pointerCoord(endEvent);
        var hasClassList = !!(endEvent.target.classList && endEvent.target.classList.contains);
        var releaseTolerance = hasClassList & endEvent.target.classList.contains("button") ? TAP_RELEASE_BUTTON_TOLERANCE : TAP_RELEASE_TOLERANCE;
        return Math.abs(tapPointerStart.x - endCoordinates.x) > releaseTolerance || Math.abs(tapPointerStart.y - endCoordinates.y) > releaseTolerance;
    }
```

this line in particular:
```
var releaseTolerance = hasClassList & endEvent.target.classList.contains("button") ? TAP_RELEASE_BUTTON_TOLERANCE : TAP_RELEASE_TOLERANCE;
```

Codepen not applicable.

**Comment by nandanrao** [comment]
Yep, I also get this on Android 4.1.2, but only when an SVGElement is touched. It seems that some older webkit browsers don't give SVGElements the classList property, and the SVG elements in my app definitely don't have the property, which breaks the touch event listeners that check the classList of the elements.

**Comment by adamdbradley** [comment]
Is this still should have been fixed now: https://github.com/driftyco/ionic/issues/2235

@nandanrao what version are you using?

**Comment by nandanrao** [comment]
Was using v1.0.0-beta.14-nightly-924, switched to crosswalk which solved the problem for me, do you need me to try and reproduce this on latest version?

**Comment by adamdbradley** [comment]
Should be good now, thanks
