### ISSUE TITLE
bug: ion-scroll content doesn't get scrolled on the app

### ISSUE THREAD

**Issue by nbelopotapov** [driftyco/ionic#2550]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello! Can you please help me with this issue? Codepen examples are below.

When I scroll to the left or to the right on a device the content doesn’t get scrolled.

First of all I have an unwanted behaviour of my side menu. It opens when I scroll to the right. 
http://codepen.io/nbelopotapov/details/yyLVRG/
I solved it with the ```is-enabled="false"``` setting.

http://codepen.io/nbelopotapov/details/GgRNYE/ - here is version with ```is-enabled="false"```

Anyway this solution works in a browser, but doesn’t on a simulator or a device.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
@AleksMeshkov This looks to be fixed in the latest beta on my iphone running ios 8. Let me know if it's not for other configurations. Assuming this can be closed otherwise.
