### ISSUE TITLE
bug: IonPicker/IonDatetime console error on scroll

### ISSUE THREAD

**Issue by NoxFly** [driftyco/ionic#25517]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I don't know exactly when the error occurs, but it's when I open the modal containing two `IonDatetime`, one with presentation date, the other with presentation time.
When I'm scrolling, there's no error. When I'm opening the modal, I stack 2 errors (the same).

What's weird is that I didn't open/closed my modal 15 times, though I've 30 errors in the console, about scrolling a date picker.

It's happening on Firefox Dev Edition 102.0b9, simulating iOS User Agent. It's not happening when simulating an Android User Agent.

It does not occurs when I tested it on Microsoft New Edge. However, testing on this browser on both iOS and Android, the columns of the datetime number are smoothly converging in diagonal, then it reset at their respective positions instantly.

Video of this weird animation :
https://user-images.githubusercontent.com/32705400/174973724-d6a1d548-e9ad-4b13-b8b0-90b76b19f608.mp4

Screenshot of the error :
![image](https://user-images.githubusercontent.com/32705400/174971820-49dca3a4-848e-4129-a454-3efe298da2f9.png)

### Expected Behavior

Mhhh 🤔 No error ? And no weird animation ?

### Steps to Reproduce

```html
<ion-modal
	mode="ios"
	trigger="yourTrigger"
	[breakpoints]="[.7, 1]"
	[initialBreakpoint]=".7">
	<ng-template>
	  	<ion-content>
			<ion-datetime presentation="date" size="cover"></ion-datetime>
			<ion-datetime presentation="time" mode="md" size="cover"></ion-datetime>
	  	</ion-content>
	</ng-template>
</ion-modal>
```

### Ionic Info

Ionic:

Ionic CLI : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 6.0.13
@angular-devkit/build-angular : 13.2.6
@angular-devkit/schematics : 13.2.6
@angular/cli : 13.2.6
@ionic/angular-toolkit : 6.1.0

Capacitor:

Capacitor CLI : 3.4.3
@capacitor/android : 3.4.3
@capacitor/core : 3.4.3
@capacitor/ios : 3.4.3

Utility:

cordova-res : not installed globally
native-run : 1.5.0

System:

NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
npm : 8.12.2
OS : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem on the latest version of Ionic, please create a new issue and include a link to a minimal Github repo that reproduces the error. Thanks!
