### ISSUE TITLE
Ionic Slide Box Delegate - Update - Callback

### ISSUE THREAD

**Issue by jnovaes** [driftyco/ionic#2556]
Hi, everyone.

First, I want to thanks for the great framework, maybe the best.

So...
In my home projects and job projects, I really miss kind of callback in function update() of SlideBoxDelegate. I'm new using the framework, but in a lot of my apps I need to know when the update ends.

I'm using angular and have a foreach, my slideBox gets its contents. But, when the slidebox show up I need to swipe to slide user choice. But, slideBox not finished its jobs, and it havent a callback. 

I'm change the ionic.bundle.js to fix this problem to me. But, i'm notice the update() has a  setTimeout()... I think, that settimeout are "wait for angular foreach ends", but... the timeout has a fixed time? The timeout will wait the foreach ends, even if it has a lot of data to iterate?

Ps:. Sorry for poor english :/

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
