### ISSUE TITLE
bug: datetime, typing into time picker does not update value prop

### ISSUE THREAD

**Issue by kyoz** [driftyco/ionic#25560]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When clicking on popover time selector of ion-datetime, the keyboard is open.

### Expected Behavior

Should not open keyboard when click on popover time selector

### Steps to Reproduce

https://user-images.githubusercontent.com/29815830/176684366-c30c0ab6-03bb-43ac-9981-0d68f6233929.mp4

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/kyoz/Library/Application Support/fnm/node-versions/v16.14.2/installation/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.4
   @angular/cli                  : 13.3.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.0
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/kyoz/Library/Application Support/fnm/node-versions/v16.14.2/installation/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

### Additional Information

This may only happen on Android devices, i'v tried on my iPhone and iOS simulator but it's seem doesn't happen.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is an intentional feature of `ion-datetime`. Tapping the time opens a keyboard to allow you to type in the time instead of swiping.

This is the behavior on iOS too:

https://user-images.githubusercontent.com/2721089/176686914-d9f8fe2c-b6a0-4785-b9eb-5b0ceb94210e.mp4

**Comment by kyoz** [comment]
Here I shot a simple steps to reproduce the issue. As you can see, the value which typed by keyboard is not update. It's only update when we scroll the hour & minute wheel.

https://user-images.githubusercontent.com/29815830/176696421-50bae5f4-8a0f-4ed2-ad6e-dfe7e5605a6e.mp4

**Comment by liamdebeasi** [comment]
Thanks! It looks like we update the `value` prop of the column, but `ionChange` never fires so the `ion-datetime` value does not update.

**Comment by kyoz** [comment]
Thanks @liamdebeasi

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25561, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by zhellDarwin** [comment]
Is there any way to disable the keyboard from showing?

**Comment by liamdebeasi** [comment]
Not at the moment. This is an accessibility feature to make time entry easier and aligns with what native iOS does.

**Comment by zhellDarwin** [comment]
is there any workaround to disable this because if i give minvalues and type the minute which is not in minvalues means the date time is not updating after whatever I'm typing
