### ISSUE TITLE
bug: Error in ionic bundle

### ISSUE THREAD

**Issue by gio82** [driftyco/ionic#2562]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I've got this error (ionic beta 13):
`0     357181   error    TypeError: null is not an object (evaluating 'scrollView.options'), http://192.168.1.100:8100/lib/ionic/js/ionic.bundle.js, Line: 39815`

It seems a no blocking error. The app still works after this error.</span>

<span is-issue-template></span>

**Comment by simpixelated** [comment]
I'm still getting this error with 1.1.0, but only when running unit tests, both in PhantomJS2 and Chrome:
```
TypeError: null is not an object (evaluating 'scrollView.options')
  at /Users/jordankohl/Dev/homdna-mobile/src/lib/ionic/js/ionic.bundle.js:52869
```
Changing the line in ionic.bundle.js to `scrollVew && scrollView.options` fixes the problem.

I saw someone on the forum also mentioned the same problem with 1.1.0:
http://forum.ionicframework.com/t/scrollview-option-throws-error-on-android-4-4-2/21356

**Comment by softBarbarian** [comment]
i am getting same error on iOS and Android. @adamdbradley: any tips how to fix this? 
Here is my info:
```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 

```

**Comment by softBarbarian** [comment]
cc: @simpixelated

**Comment by softBarbarian** [comment]
here is the line that is causing the issue:
`var isVertical = !!scrollView.options.scrollingY;`

**Comment by softBarbarian** [comment]
this error still occurs
here is my info:
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by spi7fire** [comment]
happens to me to every other run, makes my app freeze on startup
any coming solution for that bug?

**Comment by kby799** [comment]
is there any solution to this? I got this error after I added ion-option-button  and occurred whenever I slided an item that I wanted to delete.

**Comment by ansgmlen** [comment]
same here and this is my log.

ypeError: Cannot read property 'options' of null
    at new RepeatController (ionic-angular.js:9280)
    at getRepeatManager (ionic-angular.js:9067)
    at refreshDimensions (ionic-angular.js:9166)
    at angular.js:18258
    at completeOutstandingRequest (angular.js:5764)
    at angular.js:6041

**Comment by Zvika88** [comment]
this error still occurs, ionic 1.3.2 , and the line mentioned by @okonon on Jan 24 2016 is still there (line 9278 in ionic-angular.js). Anyone from ionic care to respond?
