### ISSUE TITLE
Sluggish performance on Android 4.4 - ion-slide-box with ng-repeat and content heavy slides - new nightly

### ISSUE THREAD

**Issue by olliekav** [driftyco/ionic#2578]
I was hoping the new nightly would increase the performance of this but it seems no different. I'm generating 4 slides of news entires with ng-repeat. Each slide is quite content heavy in terms of HTML. The sliding and scrolling within each slide is really sluggish and stop/start on Android, to the point it feels horrible to use. Would adding the slides dynamically help this? Any other suggestions?

**Comment by travisdahl** [comment]
Just curious why the latest versions dropped this method...

```
ion-slide {
  &:not([slide-display]) {
    display: none !important;
  }
}
```

Seems its been left behind in favor of using translates. I think it was faster before. when you were hiding all but the 3 (prev, curr, next). `[slide-display]` is gone.

**Comment by florentsuc** [comment]
Same issue with the rc-0 for me. (cc @johannesjo)

I'm wondering if we could have a callback on `$ionicSlideBoxDelegate.update();`?
