### ISSUE TITLE
Publish entire framework on npm

### ISSUE THREAD

**Issue by donaldpcook** [driftyco/ionic#2590]
The only thing I could find on npm was ionic-cli. I'd love to be able to install the framework with npm for easy use with browserify (either this repo or ionic-bower).

The only change you would have to make would be to add main to the package.json to point to ionic.bundle.js.

For now, I published `ionic-framework` with a fork of this. It would be much nicer to have an official one though, and if you want to use ionic-framework, I'd gladly give it to you.

Thanks!

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#241
