### ISSUE TITLE
bug: ion-radio with collection-repeat

### ISSUE THREAD

**Issue by lordcoste** [driftyco/ionic#2596]
I've some problem using collection-repeat of ion-radio.
To reproduce the problem in codepen:
- Select Item n. 1
- Scroll to Item n. 30 (don't select)
- Scroll back to Item n. 1 (bug: item is not selected anymore).
- Select Item n. 1 again
- Scroll down and you will see an Item selected (Probably around item 20, the exact number depends on the height of your screen, if is not 20 keep scrolling and you will find it).
- Keep scrolling and you will find another one.

http://codepen.io/anon/pen/LEVEGz

ng-repeat is not affected by this problem.

Best regards.

**Comment by mnewmedia** [comment]
So 5 years too late, but maybe for others:
http://codepen.io/anon/pen/VezPjL

- Use ng-model and ng-value directly like: `ng-model="item" ng-value="value"`
- Don't make it like: `ng-model="item" ng-value="'{{value}}'"`
