### ISSUE TITLE
Radio buttons break in RTL

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#2598]
http://plnkr.co/edit/HjAZk1pGefXDowt38ddu?p=preview

When using radio buttons (`<ion-radio>` or the CSS directly) with a `dir="rtl"` page, the labels disappear when they're clicked, and a small unstyled HTML radio button appears in the corner.

**Comment by Mohandm** [comment]
@imgx64  
Thanks for the workaround, It woked
