### ISSUE TITLE
bug: TypeError: undefined is not an object (evaluating 'parsedDatetime.tzOffset = undefined')

### ISSUE THREAD

**Issue by imhoffd** [driftyco/ionic#25993]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Selecting a day and then switching to a month where that day of the month doesn't exist breaks the `ion-datetime` with a TypeError.

https://user-images.githubusercontent.com/236501/191802351-4e707646-8c01-4164-8976-f2e7ad9426e7.mov

### Expected Behavior

I would expect it to change the date to the last day of the month (e.g the 30th).

Picking a month with a 31st day again could either select the 30th or 31st... not sure what the behavior should be there.

### Steps to Reproduce

1. Select the 31st of a month.
2. Use the month picker to select a different month without a 31st day.

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime-button#basic-usage

### Ionic Info

@ionic/core: 6.2.7

### Additional Information

Thanks for `ion-datetime-button`! It's exactly what I was looking for.

**Comment by liamdebeasi** [comment]
Thanks for the report, Dan! Looks like this is another instance of https://github.com/ionic-team/ionic-framework/issues/25585, so I am going to merge the two issues.

There is a dev build with a proposed fix in https://github.com/ionic-team/ionic-framework/issues/25585#issuecomment-1255375086.

Here is a CodePen with the dev build: https://codepen.io/liamdebeasi/pen/dyeVPMP


https://user-images.githubusercontent.com/2721089/191820413-b1aa055c-1e97-4908-934f-5dfe99ca1dda.mov
