### ISSUE TITLE
iOS input cursor bugs

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#26]
It seems the Web View on iOS has a bug where a focused text box will the input caret through any layers on top of it.

**Comment by pranavjer28** [comment]
I am also facing input cursor issue in my project.
Description :- In my screen there are 4-5 input fields, when i focused on any of the input filed then keyboard appears and screen move up. Now if i scroll  the screen (ion -content) up and down then cursor move out from the input text field and start scroll along with screen scroll direction. Please help out if anyone found this issue and got fix.

Platform and dependencies :- 

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by JaswinderImmanent** [comment]
I am facing exact same issue.Please help as soon as possible.

Thanks in advance

**Comment by vkurlyan** [comment]
It happened for me because of body element has css property "position: fixed".
Try this:

> body {
>   position: static!important;
> }
