### ISSUE TITLE
404 (Not Found) ionic-starter-sidemenu/archive/master.zip

### ISSUE THREAD

**Issue by ramonck** [driftyco/ionic#2601]
Srs.,

While starting a new template project I got this error

404 (not found)

https://github.com/driftyco/ionic-starter-sidemenu/archive/master.zip

Please solve it!

**Comment by honzix23** [comment]
Got 1.3.3 and the same error when starting new template...

**Comment by ramonck** [comment]
That's because It's Offline the server that provides the templates or your
internet was down. Give it a few hours and try again.

Best Regards,
Em seg, 2 de fev de 2015 às 21:53, honzix23 <notifications@github.com>
escreveu:
