### ISSUE TITLE
ion-side-menu it is ok but should be more sensitive to do the swiperight

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2603]
Sometimes the swipe not responding at first.

Android 4.4.4 Nexus 4

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
