### ISSUE TITLE
bug: autoGrow="true" on ion-textarea does not handle very large words well

### ISSUE THREAD

**Issue by BurkusCat** [driftyco/ionic#26122]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If I have an `ion-textarea` with the `autoGrow=true` property, it does not cope well when writing text larger than the width of the text area. As an example, on a phone screen "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE" would not wrap properly. It's very important to minimise data mistakes/errors so we want to don't want the user to miss something important even if they are on high text/zoom settings on their device.

Typing in lots of characters:
![image](https://user-images.githubusercontent.com/7528322/195626545-72b31ede-383a-43a3-8960-7235caccd250.png)

Using arrow keys to scroll to the right (notice the label disappears):
![image](https://user-images.githubusercontent.com/7528322/195626681-ba548290-d984-44d2-950a-26df0f9dd337.png)

CSS inspector:
![image](https://user-images.githubusercontent.com/7528322/195626831-827dbcaa-25c9-4656-bd43-5d65d470e2b4.png)

### Expected Behavior

No autogrow<ion-textarea></ion-textarea>. Text wraps even though there are no spaces/newlines
![image](https://user-images.githubusercontent.com/7528322/195625701-33e93e8a-1c04-42da-bc13-1bad4c929f64.png)

Autosize `<ion-textarea autosize></ion-textarea>`. This looks great for adding text! I want autoGrow to look like this. However, `autosize` does not cope as well when deleting multiple lines of text (`autoGrow=true` does cope well with deleting text)
![image](https://user-images.githubusercontent.com/7528322/195625984-7c730027-22b8-45cc-b603-f16c98f8e469.png)

### Steps to Reproduce

`<ion-textarea autoGrow="true"></ion-textarea>`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\burku\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. I noticed your `ionic info` says you are running Ionic v6.2.5. Have you tried this on the latest version of Ionic? There was a fix in v6.2.7 that should improve autogrow with long pieces of text.

**Comment by BurkusCat** [comment]
I'm silly, my package.json was fine but the node module installed was still the old version. Latest ionic version `autoGrow=true` works perfectly in terms of wrapping + deleting text :)
