### ISSUE TITLE
Nav bar title set async

### ISSUE THREAD

**Issue by cdarken** [driftyco/ionic#2615]
There seems to be a problem when setting the title attribute of ion-view, if I set it after a promise is resolved the width is wrong. If it's a constant string there is no problem.

**Comment by OminStyle** [comment]
Removing `view-title=""` before using `$ionicNavBarDelegate.title(title);` does not work in v1.0.0-beta.14. However, using `<ion-nav-title>` directive as @adamdbradley suggested did fix the issue.

Summary:
* There is a bug while using `$ionicNavBarDelegate.title(title);`
* There is a bug while using `view-title="{{title}}"`
* `<ion-nav-title>{{title}}</ion-nav-title>` seems to be working fine

**Comment by ram-you** [comment]
Hi @OminStyle , you are quite right.

**Comment by juanpasolano** [comment]
@OminStyle: only `<ion-nav-title>{{title}}</ion-nav-title>` worked for me too

**Comment by jbdemonte** [comment]
When using `<ion-nav-title>{{title}}</ion-nav-title>` I have the same problem described here: https://github.com/driftyco/ionic/issues/2945

![image](https://cloud.githubusercontent.com/assets/787639/7955805/5d82944c-09db-11e5-9f16-b1106aa48b0e.png)

**Comment by michael-levin** [comment]
+1.  Same problem as @jbdemonte 

ion-nav-title width is calculated incorrectly.  I actually see it display correctly for a flash, and then shrink and truncate the title

**Comment by olingern** [comment]
Context: I just jumped into a project w/ ionic + sass implemented. Not sure if this is a bug isolated to the SASS implementation or not.

There should probably be a SASS variable for $bar-title-width used in this class. If anyone is interested, I can make some PR's to update things. 

Here's your problem:
`  .bar .title {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    z-index: 0;
    overflow: hidden; /* Problem if you have no width set */
    margin: 0 10px;
    min-width: 30px; 
    height: 43px;
    text-align: center;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 17px;
    font-weight: 500;
    line-height: 44px; }`

Here's an updated version:
Here's your problem:
`  .bar .title {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    z-index: 0;
    margin: 0 10px;
    min-width: 30px;
    width: 80vw; /* Or whatever width you'd like */
    height: 43px;
    text-align: center;
    /* text-overflow: ellipsis; */ /* this could be good if it's what you want. Use at your discretion */
    white-space: nowrap;
    font-size: 17px;
    font-weight: 500;
    line-height: 44px; }`

- Overwrite the `.bar .title` in your custom SASS components
- Edit the ionic framework SASS. `.bar .title`. I haven't tested this thoroughly yet and it's implications it might have over the app. 

Right now, option #1 is easiest for me, but I wouldn't think it's ideal
