### ISSUE TITLE
Nested <ion-nav-view> does not get cleared when going back to parent state

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#2617]
This is how it works with plain Angular and ui-router's `ui-view`: http://plnkr.co/edit/R8TLXVe2PuBcPHQiuPH8?p=preview

When you click `Open child`, the nested ui-view gets filled with the child template. Then you press `Back`, it goes back to the parent state and the `ui-view` is cleared.

This is the exact same code but with ionic's `ion-nav-view` instead: http://plnkr.co/edit/zzUU1YLE5gR0MOFoxECv?p=preview

When you press `Back`, the state does go back, but the nested view does not get cleared

**Comment by tannerlinsley** [comment]
This is a problem for me at the moment.  It's making nested view extremely difficult to work with.

**Comment by LargeRui** [comment]
I also encountered the same problem. And how to resolve it?

**Comment by aschwartz-satcom** [comment]
Seeing the same behavior in a simple app with three states, 1 parent and 2 children.  The Nav Bar's Title and buttons also remain from the nested state after going back to the parent.  Both the ionic nav bar's Back button and the browser's back button exhibit the same behavior.

**Comment by jgw96** [comment]
Hello! Are you all still seeing the same issue with the latest version of ionic?

**Comment by imgx64** [comment]
@jgw96 The Plunker linked above uses the latest nightly v1, and the problem still occurs. I don't know about v2 however.

**Comment by wbhob** [comment]
try just using ui-view, since `ion-nav-view` is designed to be a full screen, one time thing.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#1
