### ISSUE TITLE
Dragging input text inside an <ion-list> throws an error

### ISSUE THREAD

**Issue by poacher2k** [driftyco/ionic#2631]
Dragging input text inside an \<ion-list\> throws: Uncaught TypeError: Cannot read property 'deltaY' of undefined

[Codepen](http://codepen.io/anon/pen/RNPqNa)

Steps to reproduce: 
1. Select text from input box
2. Drag the text around

**Comment by perrygovier** [comment]
Unable to reproduce this in the current nightly. Let me know if you're still seeing this.
