### ISSUE TITLE
modal backDrop failed to resize on screen rotation

### ISSUE THREAD

**Issue by olebrun** [driftyco/ionic#2632]
On iPad, if you rotate the device when a modal is open, the backdrop doesn't resize even if you close and reopen the modal.
It resize if you scroll element "behind" the backdrop.

test with v1.0.0-beta.13 and ionic-bower#master
Can be reproduce with the login box in the "sidemenu" stater app
thanks,

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
