### ISSUE TITLE
collectionRepeat - setting startIndex

### ISSUE THREAD

**Issue by jonlil** [driftyco/ionic#2635]
Is there any way to set startIndex manually?

**Comment by Ionitron** [comment]
Greetings @jonlil!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by nournia** [comment]
Hi,
@drewrygh, is it possible to manually change current position of collection-repeat?
I mean, I fill collection-repeat with 1000 items and I want to scroll view to 500th one without rendering 500 items (just basic of usecase of collection-repeat). This is what I think startIndex mean.

**Comment by pajooh** [comment]
I my case, i need an initial index to start rendering, via some directive like ```collection-start-index="20"```
i think the implementation logic exists, as ionic needs to start rendering from specified index and scroll to estimated position.
I can create PR for this, any help from maintainers is highly appreciated.
