### ISSUE TITLE
bug: Apk file issue on device

### ISSUE THREAD

**Issue by sachin0651** [driftyco/ionic#2636]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I generate apk file, but its not working on mobile device ,  its showing process not responding error.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
