### ISSUE TITLE
bug: infinite digest on routing redirects

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#2638]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Using $stateChangeStart to check authentication status causes infinite digest

To reproduce this, you must use Ionic CLI to create a local app. The problem will NOT be demonstrated in Codepen(not sure why).

So, do the following :
- ionic start digestProblem http://codepen.io/calendee/pen/zxGRza
- cd digestProblem
- ionic serve 9000 9001 (or whatever your preference)
- Note that the app works just fine. You were heading towards /tab/home and got redirected to /signin because the auth check always returns false.
- Now, replace the Beta 13 files in www/lib/ionic with nightlies
- Open the console in your browser. You'll still be on the signin page
- Reload the browser at http://localhost:9000
- Notice that the app is repeatedly trying to access /tab/home even though you are redirecting to signin.
- Finally, angular kills the digests and you end up in the signin state
- Notice that even if you comment out the $state.go("signin");, the app is still constantly trying to reload /tab/home</span>

<span is-issue-template></span>

**Comment by niyando** [comment]
@cbruun that did it for me. Thanks :beer:
