### ISSUE TITLE
Cloned text doesn't work if image div, or img tag is before it.

### ISSUE THREAD

**Issue by israelidanny** [driftyco/ionic#2645]
This is related to a mistakenly closed issue:
https://github.com/driftyco/ionic/issues/1559

Reproducing is easy, just make a view that does something like this:
```html
 <div class="row responsive-sm">
  		<div class="col">
  			<center><img src="img/logo.png" class='full-width-image'></center>
  		</div>
  	</div>
    <div class="list">
      <label class="item item-input">
        <span class="input-label">Email</span>
        <input type="email" ng-model="email">
      </label>
      <label class="item item-input">
        <span class="input-label">Password</span>
        <input type="password" ng-model="password">
      </label>
    </div>
    <div class="button-bar">
    	<a class="button icon-right" data-ui-sref="register">Register</a>
    	<a class="button icon-right button-positive" ng-click="login()">Login</a>
    </div>
```

The result is a completely disfunctional text input field. 

If I remove the image on top, it works like a charm. I tried stripping the image down to the bare `img` tag and it still behaves the same.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by israelidanny** [comment]
Just literally copy & paste what I wrote above. Please re-open this. It's a very annoying issue that prevents even a basic logo + login details screen from being possible.

I had to publish an app to the AppStore + Google Play just because of this nasty bug.

**Comment by boltex** [comment]
Reproducing is easy, just make a view that does something like this:

 <div class="row responsive-sm">
        <div class="col">
            <center><img src="img/logo.png" class='full-width-image'></center>
        </div>
    </div>
    <div class="list">
      <label class="item item-input">
        <span class="input-label">Email</span>
        <input type="email" ng-model="email">
      </label>
      <label class="item item-input">
        <span class="input-label">Password</span>
        <input type="password" ng-model="password">
      </label>
    </div>
    <div class="button-bar">
        <a class="button icon-right" data-ui-sref="register">Register</a>
        <a class="button icon-right button-positive" ng-click="login()">Login</a>
    </div>
The result is a completely disfunctional text input field.

If I remove the image on top, it works like a charm. I tried stripping the image down to the bare img tag and it still behaves the same.
