### ISSUE TITLE
bug(ionView): Going back through history does not resolve the transition properly, leaving the user with a white screen

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2650]
Currently the transition does not complete, leaving the user in a suspended state where the ion-view element has transition: 0ms, opacity: 0, and display: none (display: none being from the [nav-view="cached"] css selector).

**Comment by shql** [comment]
@adamdbradley - it's easily replicable if you have a side menu, you navigate to a list view and from there go to a detail view. If you use swipe back you can see the broken list view showing nothing anymore. The back button on top is also broken for me then. This only happens when the list view is marked with "cache: false". I had to disable the feature for now in my app as it is not recoverable.

**Comment by pvandrunen** [comment]
I can confirm that on Android if I navigate between pages 1. The header animation doesn't complete, page titles are stuck, offset 50% or 70% off the left of the page and 2. One page in particular doesn't complete animation, the opacity on the view wrapper is 0. This happens at random after a few different page views. I am using the side menu starter.  This is exacerbated if I disable cache on one page but not all pages.

Changing the transition animation style to ios on android fixes the problem but the page transitions look awful.

**Comment by Ionitron** [comment]
Greetings @wesleycho!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by adsahay** [comment]
This issue is open. Not sure why it is marked close without a resolution. Can you guys look into this?

**Comment by sadiq-mc** [comment]
@adamdbradley @perrygovier This issue happens for child views which doesn't have `cache: true`. I get this in iOS, but not in Android. To obtain this issue, swipe from the **left edge of the screen** and you can see this issue.

Also another issue is the child view header is disappearing when you swipe from left and without completing release it to stay in the child view itself.

Am using ionic sidemenu template with ionic version 1.3.3
