### ISSUE TITLE
`cordova plugin add org.apache.cordova.statusbar` breaks `ionic build ios`

### ISSUE THREAD

**Issue by kevnk** [driftyco/ionic#2652]
I'm trying to make the iOS status bar light, so as instructed from http://learn.ionicframework.com/formulas/customizing-the-status-bar/ I ran the command `cordova plugin add org.apache.cordova.statusbar`. Then, when tried to run `ionic build ios` (which worked _before_ adding the cordova plugin), I got this error:

```
** BUILD FAILED **


The following build commands failed:
    CompileC build/habits.build/Debug-iphonesimulator/habits.build/Objects-normal/i386/CDVStatusBar.o habits/Plugins/org.apache.cordova.statusbar/CDVStatusBar.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /www/habits/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

`cordova plugin remove org.apache.cordova.statusbar` removed the plugin and `ionic build ios` worked again.

**Comment by ratshili** [comment]
Thanks @kevnk You have helped me a lot. It works!!!

**Comment by kevnk** [comment]
You're welcome!
