### ISSUE TITLE
Bad line-height on Android L

### ISSUE THREAD

**Issue by EmilScherdin** [driftyco/ionic#2653]
Hi!

I've noticed a issue with the line-height on Android L devices. Here's a print-screen of the problem. 
[screenshot](http://imgur.com/kfRi4vL)

Device: OnePlus One 

Cheers!
Emil

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
