### ISSUE TITLE
[beta14] ion-side-menus, cannot ng-include a template within ion-nav-bar

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic#2655]
When you have several views that have the same button (here the button that open the sidemenu) you do not want to repeat the same button over and over in views so you create a directive or use ```ng-include``` to insert the button you need.

Unfortunately the following code do not work anymore:

```
<ion-nav-bar class="bar-positive">
            <ion-nav-back-button></ion-nav-back-button>
            <div ng-include="'templates/menu-opener.html'"></div> 
 </ion-nav-bar>
```

Work in beta 13:
http://codepen.io/shprink/pen/Byormd

Does not in beta 14:
http://codepen.io/shprink/pen/GgpxOr

**Comment by PiTiLeZarD** [comment]
Any update on this? I'm hitting the same problem right now.

**Comment by neophob** [comment]
+1

**Comment by mhartington** [comment]
With Beta14, the nav-bar was completely restructured and now is a bit more complex than it was before. You should use ion-nav-buttons instead.

```jade
ion-view
  ion-nav-buttons[side=left]
    span[ng-include=buttons.html']
```

For your particular example, you don't need to include a button in every view. You just include in the ion-nav-bar and it will work fine.

http://codepen.io/mhartington/pen/bdbGWg
