### ISSUE TITLE
Scroll is lagging

### ISSUE THREAD

**Issue by shubham2102** [driftyco/ionic#2658]
### Having a nX2 grid images in collection-repeat along with ion-infinite-scroll after which the list scroll is lagging. Not giving native like smooth scroll.

code snippet of it is:

``` html
<ion-content has-header="true" padding="true" >
        <div class="item item-product" collection-repeat="item in items" 
            collection-item-width="'50%'" collection-item-height="'50%'">
            <img ng-src="{{item.image}}">
        </div>  
</ion-content>
<ion-infinite-scroll ng-if="canLoadMoreProducts()" on-infinite="loadMoreProducts()">
</ion-infinite-scroll>
```

Please suggest how to fix this.
And the scroll is lagging in Android only

**Comment by shangab** [comment]
I  am facing the same issue, even though my list is short, around 100 items, and stored locally not fetched over $http.get/post. This is the one and only issue that I found in ionic other than this it rocks.

**Comment by jianbo** [comment]
Same here work well in iOS, but lag on Android, I had to check if iOS display x2 col or android x1 col

**Comment by Fayozjon** [comment]
Jianbo

http://ongoo.cz/kerb

24.03.2015, 06:20, "Jianbo Cui" <notifications@github.com>:Same here work well in iOS, but lag on Android, I had to check if iOS display x2 col or android x1 col

**Comment by Fayozjon** [comment]
Abubaker

http://new.osat.pl/depozitom_strategiya

24.03.2015, 04:51, "Abubaker" <notifications@github.com>:I  am facing the same issue, even though my list is short, around 100 items, and stored locally not fetched over $http.get/post. This is the one and only issue that I found in ionic other than this it rocks.

**Comment by csvan** [comment]
Confirming this issue, scrolling is laggy even on a very fast device (OnePlus One) running Crosswalk and using trivial list items.

**Comment by csvan** [comment]
To people still having problems with this, please try to add `overflow-scroll=true` to your IonContent directive:

```
<ion-content overflow-scroll=true>
        <ion-list>
            ...
        </ion-list>
    </ion-content>
```

**Comment by DmitriyWebDev** [comment]
Although anyone of you solved his problem with the scroll lags? If so, how, please write.

**Comment by csvan** [comment]
@DmitriyWebDev did you try my suggestion above?

**Comment by DmitriyWebDev** [comment]
Yes @csvan , but your advice didn't help me. On iOs (iPhone 4) scroll is lagging. On Android scroll is lagging less.

**Comment by shangab** [comment]
yes with using crosswalk browser plugin

-----------------------------------------------------------------------
Apologies for the apearance,  this mail is from my tablet phone.

**Comment by DmitriyWebDev** [comment]
Thank you, @shangab ! Crosswalk for android apps is good solution.
