### ISSUE TITLE
ion-side-menu in only one state breaks navigation

### ISSUE THREAD

**Issue by realityfilter** [driftyco/ionic#2660]
I want to integrate a side menu in only one of my states. Unfortunately it breaks the
navigation.

See plunkr: http://plnkr.co/edit/GA6xrybduFynyh9jrTMD

Here in this example the page state.

If you want to go from one page to another (/page/1 to /page/2) the url changes but the content is still the same.

If you change the template of this state to 'template/working-page.html' the states transition normally. Although the current page gets a grey background during transition animation which looks weird.

Could be please have a look at it. Maybe it is only a documentation issue or wrong usage of mine.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
