### ISSUE TITLE
css background-size: cover not working when navigating

### ISSUE THREAD

**Issue by mobilabgit** [driftyco/ionic#2663]
I am using today's bleeding edge just from master release of ionic.
I noticed that my background image resizes incorrectly.

I have two ion-views both with a css class that sets the following:

background: url("img/voetbalveld.png") no-repeat center center fixed;
-webkit-background-size: cover!important;
background-size: cover!important;
When I open the app and see the first view, the background looks good.
However, when I navigate to the second view

<ion-nav-view name="content" class="view-container" nav-view-transition="ios" nav-view-direction="forward">
the background-size cover doesn't work and instead I see only a part of the image as if zoomed in (the image is too large to show in the screen)

**Comment by beauby** [comment]
+1
