### ISSUE TITLE
bug($ionicHistory): Accessing a view that has already been accessed before $ionicHistory.clearCache() fails

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2664]
When the user has visited a view, then $ionicHistory.clearCache() runs, any time the user accesses the same view again, it fails to load properly.

**Comment by rickyk586** [comment]
+1

**Comment by seronal** [comment]
Any updates on this issue? as @wesleycho suggested, this seems to have to do with scroll directive as it can be seen in the [codepen] (http://codepen.io/anon/pen/ZYpqPG) @mikemintz provided. After coming back to first tab, the content is actually there but it is scrolled out of view. If you pull the view down, you can see the content.

**Comment by willyboy** [comment]
Same issue. I'm using bindonce so if a user logs out of my app, I need to clear the cache so a new user can log in. But when they do and go to the same pages, I run into this problem.

**Comment by willyboy** [comment]
Addendum: It appears that this may be related to calling clearCache/clearHistory while a slide is transitioning. If I wrap the clearCache call in a timeout, things work as expected. So this doesn't work:
$state.go("sign-in-email");
$ionicHistory.clearHistory();
$ionicHistory.clearCache();

while this does:
$state.go("sign-in-email");
$timeout(function(){
	$ionicHistory.clearHistory();
	$ionicHistory.clearCache();
},5000);
