### ISSUE TITLE
Disable tap on scroll "grab"

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#2665]
Right now if you "grab" a scroll view to stop the inertial scrolling after throwing it, that will trigger a click.

The issue seems to be happening here, where `ionic.scroll.isScrolling` gets set to false in this callback which triggers on each scroll event but is canceled unless scrolling stops, then it fires `80ms` later:

https://github.com/driftyco/ionic/blob/master/js/views/scrollView.js#L393

I think we should find a way to fix that in the short term as it's a pretty annoying UX issue. I'll try to think of some alternatives.

**Comment by adamdbradley** [comment]
duplicate https://github.com/driftyco/ionic/issues/2223
