### ISSUE TITLE
v1.0.0-beta.13-nightly-852: collectionRepeat Performance Issue Caused by the  Wrong Size Calculation 

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2677]
This will defeat the whole performance improvement. The issue is triggered by the event "resize"

1.  Switch to another view from a view with collectionRepeat. The new view will display a modal. Then the following code will be called  
        
        modalEl.addClass('ng-enter-active');
        ionic.trigger('resize');

2.  Because of the event registration "ionic.on('resize', rerenderOnResize, window)" in  collectionRepeat the following code will be called in the condition (secondaryScrollSize = 0)

       collectionRepeatManager.resize(); 

3.  Because of the  secondaryScrollSize=0, the function "calculateSize" will believe all the items should be rendered as first item. 

The final result is collectionRepeat will render every item in the datasource, which normally will be thousands. This will cause the serious performance issue.

**Comment by ajoslin** [comment]
Fixed, thanks for the investigation.
