### ISSUE TITLE
Ionicons update

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2679]
Related to #2670, the Ionicons are out of sync since the new release

**Comment by dbaq** [comment]
A couple of weeks later, any updates? Thanks.

**Comment by hybrisCole** [comment]
+1

**Comment by darrynten** [comment]
+1

**Comment by volantes** [comment]
+1

**Comment by dbaq** [comment]
it landed on master guys (https://github.com/driftyco/ionic/commit/6f50c87ec36ff1b12fdb3a762933c3efaa60c297), you have to get the latest nightly code.ionicframework.com/#nightly

don't forget they replaced ```ion-ios7-*``` by ```ion-ios-*```

**Comment by ram-you** [comment]
Hi, please <b>always</b> include the latest Ionicons.
