### ISSUE TITLE
ionic keyboard not working with overflow-scroll="true"

### ISSUE THREAD

**Issue by newseedil** [driftyco/ionic#2680]
Hey,
I tried to use with overflow-scroll="true" on ion-content and when I tap on textarea or input there's no auto scroll to input that was taped, it is scroll to top! only if I start to write something with keyboard that opened its autoscrolling to input.
Important to mention that when I remove overflow-scroll="true" and use with the ionic scroll it is work.

**Comment by Ionitron** [comment]
Upon further processing, I have concluded that this is the same issue as #1797. Please continue the discussion on the earlier ticket.
