### ISSUE TITLE
Ionic is not supporting custom delimiters properly

### ISSUE THREAD

**Issue by Xample** [driftyco/ionic#2681]
Hi, we are using Ionicframework with Meteor. To do so we need to use [different delimiters](http://stackoverflow.com/questions/12923521/angular-js-custom-delimiter) than the regular curly braces. Unfortunately, [some directives](https://github.com/Urigo/meteor-ionic/issues/29) are using the braces within their attributes and content. I would suggest [replacing the content using `ng-bind`](http://stackoverflow.com/questions/27334790/angularjs-write-custom-delimiters-compliant-directive?noredirect=1#comment43127101_27334790) and the attributes related part to a dynamically written template, [something like](https://github.com/driftyco/ionic/blob/master/js/angular/directive/item.js):
```javascript
var start = $interpolateProvider.startSymbol();
var end = $interpolateProvider.endSymbol()
var ITEM_TPL_CONTENT_ANCHOR =
  '<a class="item-content" ng-href="'+start+'$href()'+end+'" target="'+start+'$target()'+end+'"></a>';
```

**Comment by Ionitron** [comment]
Greetings @Xample!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
