### ISSUE TITLE
ionic tabs routing issue

### ISSUE THREAD

**Issue by Prasanna-Poonacha** [driftyco/ionic#2692]
I am having a unique issue with respect to routing using stateprovider in case of tabbed view. 

I have a home page in my first tab. I go to child page from home page from the first tab. When I am on the child page I go to second tab. The second page view loads. Now I again click the first tab. Expectation is I should be getting back my home page. But I am getting the child page of the homepage.

ui-sref of home icon points correctly to homepage. But it goes to child page of homepage.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
