### ISSUE TITLE
The ionInfiniteScroll directive is looping on ios

### ISSUE THREAD

**Issue by pixnlove** [driftyco/ionic#2694]
Hello,

When I'm launching my Ionic app on Safari mobile, the infinite scroll function is looping when i'm returning to the specific view. You can see the error : 

![capture d ecran 2014-12-09 a 17 33 13](https://cloud.githubusercontent.com/assets/2814767/5361220/288a94ce-7fca-11e4-9977-a9ece1de22e0.png)

In my template, after the ion-list markup :
        ```<ion-infinite-scroll
                on-infinite="loadMore()"
                distance="1%">
        </ion-infinite-scroll>```

In my controller : 
``` 
    $scope.items = [];
    $scope.loadMore = function() {
        $http.get('/api/list.json').success(function(data) {
            var i = 0;
            data.items.forEach(function(item){
                i++;
                $scope.items.push(item);
            });
            $scope.$broadcast('scroll.infiniteScrollComplete');
        });
    };
```
This error occurs only on iphone 5 (v8.1.1) default browser (Safari) but not in Chrome.
For information, i'm working with the latest version of Ionic : 1.0.0-beta.13.
Thanks for your help.

**Comment by perrygovier** [comment]
@pixnlove, it sounds like a race condition. Are there any `$watch`es or other broadcasts going on in the app? I'm having trouble reproducing the error.

**Comment by felquis** [comment]
Hi @perrygovier it looks like the problem related in the forum http://forum.ionicframework.com/t/ion-infinite-scroll-is-looping-after-state-change-before-infinitescrollcomplete/19609

**Comment by pixnlove** [comment]
This is the same problem I have reproduced a few weeks ago. Thanks for the help and sorry for the late response.
