### ISSUE TITLE
Nightly: Ugly ionicSlideBoxDelegate transitions on Android

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic#2700]
Using nightly 879.
No problem on desktop (Chrome) or on iPhone 5 (iOS 8.1.1). What I see when running this on a Nexus 5 (Android 5.0.0) is that using $ionicSlideBoxDelegate.previous() or $ionicSlideBoxDelegate.next() yields transitions which are not very smooth. Try with the Previous and/or Next button one or more times and you'll see the blink-like issue on the side(s).
Here's the apk if you want it already built: http://goo.gl/uB3WiK

<p data-height="268" data-theme-id="0" data-slug-hash="GgoaOz" data-default-tab="result" data-user="zarko" class='codepen'>See the Pen <a href='http://codepen.io/zarko/pen/GgoaOz/'>Ionic slide-box ugly transtions on Android</a> by Zarko Hristovski (<a href='http://codepen.io/zarko'>@zarko</a>) on <a href='http://codepen.io'>CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by Tiagojdferreira** [comment]
I am encountering this same issue with an S4 (Android 5.0.1). Have you ever found a solution?
