### ISSUE TITLE
[feature] Scroll events

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2701]
I'd like to write a parallax directive, but the $ionicScrollDelegate service doesn't offer any way to register on the scroll event of the underlying elements. Could it be possible to add an API for this?

Workaround:

```js
$( $ionicScrollDelegate.$getByHandle( $attrs.scrollHandle ).getScrollView( ).__container ).on( 'scroll', function ( e ) {
    console.log( e.originalEvent.detail.scrollTop );
} );
```

**Comment by Ionitron** [comment]
Greetings @arcanis!

Thank you for the feature request. We will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
