### ISSUE TITLE
feat: `iondatetime` next month and prev month buttons should rase events for consumers

### ISSUE THREAD

**Issue by mbabaei0** [driftyco/ionic#27062]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

`iondatetime` next month and prev month buttons should rase events for consumers.

### Describe the Use Case

 `ionChange` Emitted when the datetime selection was called. but I need an event for month change
 I need to load events based on month change in `iondatetime`
![image](https://user-images.githubusercontent.com/40535439/228762100-8351c6fa-bc2d-4b84-b65c-e51fdf00fa75.png)

### Describe Preferred Solution

Emit event when user clicks on nextMonth or PrevMonth also when user slides the calender

### Describe Alternatives

add slot for add custom buttons template for next and prev month

**Comment by mbabaei0** [comment]
> It sounds like you are using `highlightedDates` and need to load data when the month changes?


exactly
I'm using `highlightedDates` and need to load data when the month changes. because I can't load all highlighted dates at once.

**Comment by mbabaei0** [comment]
But this component meets all the requiremnts we need for our event calender except this month event and I didnt want to use another thirp party package for simple date higlight. However . Thanks for the help. I will use another package for now . But I hope you add this feature in next versions

**Comment by liamdebeasi** [comment]
I appreciate the feedback. I am going to close this for now, but let me know if you have any questions.
