### ISSUE TITLE
Collection-repeat with orderBy and bound input in row doesn't work as expected

### ISSUE THREAD

**Issue by alextrs** [driftyco/ionic#2707]
Hello,

Some rows in collection become invisible (beyond view), when using collection-repeat with input in a row and the collection is sorted by the field bound to this input. Here is codepen (example with checkbox):
http://codepen.io/alextrs/pen/gbrbPR

1. Try to use the button at the top, the collection-repeat works as expected.
2. Try to use checkbox in a row for the first two rows (10 and 11), and you should see 12, but you will see 15 (now if you drag the list down, you will see 12, 13 and 14, but it will return to 15 as soon as you release the mouse)

Regards,
Aliaks

**Comment by ajoslin** [comment]
Fixed via bb866da3d7e539c8923bd6914c0a4e44f0f4d400
