### ISSUE TITLE
Animation option to $state.go

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [driftyco/ionic#2725]
How can I provide nav-transition and nav-direction in $state.go()

```javascript
$state.go('myState', {
    navTransition:'android',
   'navDirection':'forward'
});
```

**Comment by Ionitron** [comment]
ui-router does not allow options like this.

**Comment by zmGitHub** [comment]
it`s work @mpostma

**Comment by ledfusion** [comment]
+1 @mpostma 

By the way, isn't there a way to specify "up" or "down" to nextDirection() ?

**Comment by addi90** [comment]
+1 @ledfusion
