### ISSUE TITLE
bug: Scroll top on changing location.hash

### ISSUE THREAD

**Issue by Enerol** [driftyco/ionic#2726]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I don'ts think the $LocationDecorator have a good behaviour. It might not auto scroll to 0 (otherwise a scroll jump to 0 shows on state change with ui-router, which is not really beautifull).

Maybe it would be better to add detection of the "autoscroll" attribute from parent view before autoscrolling like this, don't you think ?

I've for my problem commented this part and seems to work okay  :
 
ionic.bundle.js line 39487 : 
/**
 * @private
 */
IonicModule.config([
  '$provide',
function($provide) {
  function $LocationDecorator($location, $timeout) {

    $location.__hash = $location.hash;
    //Fix: when window.location.hash is set, the scrollable area
    //found nearest to body's scrollTop is set to scroll to an element
    //with that ID.
    $location.hash = function(value) {

      /*  ------------------------------------------------
         ------ Commented, causes view jump on state change ------ 
         ------------------------------------------------
      if (angular.isDefined(value)) {
        $timeout(function() {
          var scroll = document.querySelector('.scroll-content');
          /*if (scroll)
            scroll.scrollTop = 0;
        }, 0, false);
      }*/

      return $location.__hash(value);
    };

    return $location;
  }

  $provide.decorator('$location', ['$delegate', '$timeout', $LocationDecorator]);
}]);</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
