### ISSUE TITLE
bug: ionicLoading noBackdrop broken

### ISSUE THREAD

**Issue by t3mulligan** [driftyco/ionic#2731]
In nightlys and beta14, you cannot hide the backdrop on ionicLoading. Here is a codepen showing the issue. 

http://codepen.io/t3mulligan/pen/emZwdG

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested over 30 days ago.

Since we have not received a reply, the issue is being closed. If you are still experiencing this issue,
please feel free to reopen it and include any information that may have been requested.

Thank you!
