### ISSUE TITLE
bug: Filter in collection-repeat doesn't work anymore

### ISSUE THREAD

**Issue by tchavot** [driftyco/ionic#2735]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Filter in collection-repeat doesn't work anymore after updating to beta 14</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
Works fine for me.

Don't use bindonce with collection repeat. I'll add a note to the docs.
