### ISSUE TITLE
onDoubletap directive

### ISSUE THREAD

**Issue by sergeychernyshev** [driftyco/ionic#2736]
It looks like support for Doubletap and other gestures was added as part of #896 but it is still not available as directive.

I am not familiar enough with the code yet to submit a pull request, but I am guessing it should just be added to GESTURE_DIRECTIVES string in https://github.com/driftyco/ionic/blob/master/js/angular/directive/gesture.js#L1

There are also other events from this list that are missing from GESTURE_DIRECTIVES:
https://github.com/driftyco/ionic/blob/e24eb1c8703162556f1bfdc440bbabed92c7f769/js/utils/events.js#L123

It might be a good idea to use the same list as a source of variable to make sure they all get added.

**Comment by Ionitron** [comment]
Greetings @sergeychernyshev!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
