### ISSUE TITLE
can-drag not being applied on first load

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#2737]
In the nightly builds, `can-drag` is not being applied on the initial side-menu load.

http://codepen.io/mhartington/pen/yyJybx

If you navigate to maps from the side-menu though, it then applies the `can-drag`.

Doesn't seem to be an issue in beta 13

http://codepen.io/mhartington/pen/OPXPEO

**Comment by vrifino** [comment]
I hope this can help: if I clear history in the DocController, the issue disappear.

http://codepen.io/vrifino/pen/LEWEqM

**Comment by mhartington** [comment]
Does not appear to be an issue in 1.0.1 and the nightly builds. Closing
