### ISSUE TITLE
feat: Can‘t combine bootstrap with ionic framework

### ISSUE THREAD

**Issue by andrescabana86** [driftyco/ionic#2739]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Im testing ionic with the sidemenu starter template. I load bootstrap and the login tab fails.

this happends with bootstrap:

http://postimg.org/image/l6bljhdsp/

this without bootstrap:

http://postimg.org/image/rd8z4qubr/</span>

<span is-issue-template></span>

**Comment by SagarBarawade** [comment]
Well please try to solve this one. I too want bootstrap to work together with ionic. I am facing the same issue with my cordova based mobile app where i am using ionic framework. I am using bootstrap created forms in it.

**Comment by fullstackforger** [comment]
Although I understand why it shouldn't be 1st focus I would still vote +1. It would be awesome to have some kind of modularity especially when it comes to features. Right now, for example, If I need glyphs only (which are AWESOME) I am manually extracting those styles from css but it would be amazing to perhaps have a version just with styling features that would work with other themes without breaking them.

**Comment by fullstackforger** [comment]
Ahhh.... just looked at Ionic css file. For those who venture here with similar problem here is the link to 
[ionicons](https://github.com/driftyco/ionicons). PERFECT!
