### ISSUE TITLE
navTransition doesn't play nicely with ngIf

### ISSUE THREAD

**Issue by colllin** [driftyco/ionic#2741]
If my link has both `ng-if` and `nav-transition="none"`, the `nav-transition` directive doesn't take effect.

It might only happen when the `ng-if` attribute initially evaluates to false.

```
<a ng-if="eventuallyTrue" nav-transition="none" ui-sref="happyPlace()">...</a>
```

**Comment by Manduro** [comment]
This is still an issue in 1.2.4. Not only for `ng-if` but also for `ng-repeat`.

**Comment by jgw96** [comment]
Hello all! Is this still an issue in ionic 1.3.0? Thanks!

**Comment by Manduro** [comment]
Yep, still there! Here's a Plunker with the bug:
http://plnkr.co/edit/3HZUjRjTZj5SRHfydLOU?p=preview

**Comment by jgw96** [comment]
Hello all! Just tested with the above plunker and it seems to work for me, can anyone still confirm this issue? Thanks!

**Comment by Manduro** [comment]
This issue definitely is not fixed yet. The Plunker still demonstrates the bug, you might want to take another look ;).

**Comment by lekkra** [comment]
I see it works fine

**Comment by Manduro** [comment]
No, it doesn't. When you click an item in the first list it should not animate to the new view, but it does.

**Comment by Ionitron** [comment]
Greetings @colllin!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Manduro** [comment]
I guess machines are wrong sometimes @Ionitron!

@jgw96 Could you maybe reopen this issue?

**Comment by wbhob** [comment]
This is a problem because your transition IN is not animated, but the back button wants to always animate out. You would need to modify your back button code for it to not animate back.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#2
