### ISSUE TITLE
When is the $scope detached from a "cached" view?

### ISSUE THREAD

**Issue by colllin** [driftyco/ionic#2742]
I'm trying to modify a scope variable that affects an `ng-class` on the cached view.  If I set the variable in the `beforeLeave` event, it never propagates to the view.  Does that sound right?  So it's impossible to modify the view.

This link:

    <a ui-sref="someWhere()" nav-transition="none">...</a>

Triggers this event:

    $scope.$on('$ionicView.beforeLeave', function(event, animation) {
        if (animation.transition == 'none') {
            $scope._isBackgroundView = true;
        }
    });

Which is meant to add a class to the `<ion-view>` in the template:

    <ion-view ng-class="{'ion-view-blurred': _isBackgroundView}" ng-controller="FeedControl">...

The background view never gets the `'ion-view-blurred'` class.  If I check `$scope._isBackgroundView` property while the view is cached, I can confirm that it is correctly set to `true`.

**Comment by mhartington** [comment]
So essentially its creating our `afterLeave` event? 
```
$ionicView.afterLeave:	The view has finished leaving and is no longer the active view.
```

http://ionicframework.com/docs/api/directive/ionView/

**Comment by colllin** [comment]
The main point is that it now detaches afterLeave instead of beforeLeave. If you think it can use the existing events API to accomplish this, great success.

**Comment by mhartington** [comment]
You should be able to use the existing events to achieve what you want. 
Going to close this for now. 
If the `afterLeave` event doesn't work for you, please provide a codepen and reopen this issue.

**Comment by colllin** [comment]
No no @mhartington, this is internal ionic code that I'm showing you if you move it around, it makes it so I can do what I want. If you don't, then I can't. 

Currently you detach the scope from the DOM before the "leave" transition occurs. That makes it impossible to modify your view in a beforeLeave or afterLeave callback.  This change I proposed fixes that, because it changes the ionic code so that it detaches the scope after the transition is complete.
