### ISSUE TITLE
Beta - 14 platform specific style on the ion-header-bar missing on android

### ISSUE THREAD

**Issue by Sjerd** [driftyco/ionic#2743]
Hey, the platform specific changes are really nice, but i found that when you use an ion-view with the hide-nav-bar="true" attribute and add a  ion-header-bar  in your code the platform specific classes aren't applied. 
In my codepen I used the ionicconfigprovider to align the titles left, bt I found it on an device. 

http://codepen.io/sjerd/pen/EayKbN

**Comment by mhartington** [comment]
Going to close this as ng-show/hide will fix the issue. 
Using ng-if will cause the element to miss the digest cycle where platform specific  configurations are applied.
