### ISSUE TITLE
[ion-slide-box] Change Show-Pager param from Boolean to Expression

### ISSUE THREAD

**Issue by Smurf81** [driftyco/ionic#2744]
Hi,

in my project, i need to show Pager only when the number of page in the slide box is greater than 1 element ( I use an expression for that ).

Is it possible to modify show-pager param from '@' to '&'

Thanks

**Comment by ajoslin** [comment]
Making it '&' would be a breaking change.

Try this:

```html
<ion-slide-box show-pager="{{pages.length > 1}}"></ion-slide-box>
```

**Comment by ajoslin** [comment]
Made it so the pager will hide/show dynamically via c631a8eff944aacb9f826a3b6b8eee0932e5355d
