### ISSUE TITLE
Black bar in navbar render bug

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2746]
Just updated to beta 14, now this happens in my navbar: http://i.imgur.com/aurNE1i.png
This black bar flickers in and out of existence randomly, but more often when the view is updating.

Using an HTC One m8 with android 4.4.4 stock.

**Comment by mhartington** [comment]
@PureSpider or @DarkSwoop, any look on a codepen or plunkr?

**Comment by PureSpider** [comment]
Didn't get to it yet, will hopefully have a codepen ready within the next few days.
