### ISSUE TITLE
On Android 4.4 the tabs are on top, but should at bottom:

### ISSUE THREAD

**Issue by hypery2k** [driftyco/ionic#2749]
With beta14 there are issues on android 4.4. the tabs are on top, but should at bottom:
![screenshot_2014-12-17-16-48-54](https://cloud.githubusercontent.com/assets/979121/5473927/7e9a237c-860d-11e4-89fa-8e4fb9d4b4a2.png)

code is available here: https://github.com/holisticon/flynn-book-scanner/blob/master/app/src/views/settingsView.html

snippets you'll find here:

```
<ion-tabs class="tabs-positive tabs-icon-left"> 
    <ion-tab title="General" icon-on="ion-ios7-gear" icon-off="ion-ios7-gear-outline">
        <ion-content id="general" class="padding">
            <h2>General</h2>
            <div>
            <p>Define here default values to use, like default owner of Books.</p>
            ...
        </ion-content>
    </ion-tab> 
    <ion-tab title="Server" icon-on="ion-ios7-refresh"  icon-off="ion-ios7-refresh-outline"> 
        <ion-content id="server" class="padding">
            <h2>Server</h2>
            <p>If you like to syncronize with a remote CouchDB activate the remote sync here:</p>
            ...     
        </ion-content> 
    </ion-tab> 
    <ion-tab title="Logs" icon-on="ion-ios7-speedometer" icon-off="ion-ios7-speedometer-outline"> 
        <ion-content id="logs" class="padding">
            <h2>Log Entries</h2>
            ... 
        </ion-content> 
    </ion-tab> 
</ion-tabs>
```

**Comment by longxianlin** [comment]
how to place this tab in the center or other position?
I have video on the top, and tabs below him to show detail and comment and video list!

**Comment by saothienhat** [comment]
Thank @ClemMakesApps, using "$ionicConfigProvider.tabs.position("bottom"); //Places them at the bottom for all OS" is work fine :)

**Comment by cesar-oyarzun-m** [comment]
@ClemMakesApps what if I want in want screen the tabs at top and in other screen at bottom, Do I just need to change dynamically `$ionicConfigProvider.tabs.position("bottom")` or can I just use some css??
