### ISSUE TITLE
ion-side-menu-content drag-content="false" not working

### ISSUE THREAD

**Issue by broberson** [driftyco/ionic#2751]
http://plnkr.co/edit/w8QOxl

Here's an app that starts off on a login view, then moves to a view with a sidemenu. When the first child view loads in the content area, you can drag it to open or close the sidemenu, despite the presence of drag-content="false".

Switching to a different view on the sidemenu results in the correct drag behavior, and it remains correct when navigating back to the inital view.

**Comment by perrygovier** [comment]
fixed in acd0ff8f8cb01d778781a81621fb90521e496a23

Thanks again
