### ISSUE TITLE
v1.0.0-beta.14: the view-title change in "$ionicView.beforeEnter" will go to leaving header bar (not sure this should be considered as an issue) 

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2755]
When use the angular expression to set the view title like the following 

     <ion-view view-title="{{scopeTitle|translate}}">

And change the variable accordingly in the event "$ionicView.beforeEnter"

     $scope.$on('$ionicView.beforeEnter', function () {
           $scope.scopeTitle = 'xxxx';
     });

Will cause the "$ionicNavBar" choose the leaving header bar to set the title of the "leaving" bar, not the first one (highlighted in the following picture).

Because at that moment, the new header bar isn't active yet. 
      
     headerBar = headerBar || getOnScreenHeaderBar();

![image](https://cloud.githubusercontent.com/assets/1271739/5484294/ff0468ac-86c0-11e4-9630-bd81ac291782.png)

**Comment by mlynch** [comment]
Going to close for now. More of a scope issue that can be deffered with a timeout.
