### ISSUE TITLE
v1.0.0-beta.14: ionContent should treat the "delegateHandle" attribute as expression instead of the string literal

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#2757]
When same "ionContent"/"ionicScroll" is created multiple times, the $ionicScrollDelegate won't be able to find the correct instance of the scrollView.

For example, 2 pages all use the same template, and 1 is cached, another one is just displayed. When try to find the scroll view and adjust the position, $ionicScrollDelegate will just pick the first found instance. 

By using the angular expression on the "delegateHandle", can easily differentiate these 2 instance through the counter in the scope.

**Comment by scottgeye** [comment]
Any update?  I'm also trying to assign different handles to different instances of the same template.

Thanks

**Comment by mlynch** [comment]
Duplicate of #2757
