### ISSUE TITLE
instanceMethodCaller throwing errors when this._instances is undefined

### ISSUE THREAD

**Issue by MundakaZgz** [driftyco/ionic#2760]
I have just updated to beta 14 and I am getting a new error where there wasn't in beta 13.

The error I'm getting is "TypeError: Cannot read property 'forEach' of undefined" in line 95 of ionic.js. Apparently the instanceMethodCaller is not checking if there are instances to loop prior to use the forEach function.

**Comment by vgmcglaughlin** [comment]
Just ran into the same issue after updating to beta 14. In case anyone else stumbles up this, the issue came down to a delegate not getting bound to `this` properly.

Old:
```
$scope.$watch($ionicSideMenuDelegate.isOpen, function (isOpen) {
  // do something
});
```
New:
```
var isSideMenuOpen = $ionicSideMenuDelegate.isOpen.bind($ionicSideMenuDelegate);
$scope.$watch(isSideMenuOpen, function(isOpen) {
  // do something
});
```

**Comment by bpevangelista** [comment]
I've just hit the same issue migrating to rc5. The solution above worked for me, thanks for posting it.
