### ISSUE TITLE
Ion-refresher height stays rememberd when removed with ng-if

### ISSUE THREAD

**Issue by Sjerd** [driftyco/ionic#2769]
hey, i have 2 different div's with lists I show in one view, one div has an ion-refresher and the other div doesn't. when i visit the div which doesn't have the ion-refresher and pull down the list it seems like the space for the refresher remains, but i don't see the icon and it doesn't collapse. 

Here you can see that when you visit the second tab you can still pull down as if there was an ion refresher http://codepen.io/sjerd/pen/MYeVZO

**Comment by jasperkuperus** [comment]
What is the current status of this issue? I am also running into this problem...

**Comment by jasperkuperus** [comment]
If you put a simple console.log in the $scope.doRefresh of the above codepen, you'll see that the actual refresher is still in place, as doRefresh is still getting called when ng-if evaluates to false. So it's not only a styling issue. The refresher still seems to be active.

**Comment by mhartington** [comment]
In this case, it would be better to create two scroll view.

http://codepen.io/mhartington/pen/OVoVRW?editors=100

**Comment by JLNNN** [comment]
+1. ion-refresher is still active when ng-if is false, even if it's not visible. ng-hide/ng-show isn't workin, too.

**Comment by danicomas** [comment]
@JLNNN @mhartington the same bug

**Comment by danicomas** [comment]
I have a workaround @JLNNN @mhartington :

```js
<ion-refresher
      ..
      ng-if="variable">
    </ion-refresher>
```

and add this on the function you change the <variable> value:
```js
    var scrollView = $ionicScrollDelegate.getScrollView();
    scrollView.__refreshHeight = null;
    scrollView.__refreshActivate = null;
    scrollView.__refreshDeactivate = null;
    scrollView.__refreshStart = null;
    scrollView.__refreshShow = null;
    scrollView.__refreshHide = null;
    scrollView.__refreshTail = null;
    scrollView.__refreshTailTime = null;
    scrollView.__minSpinTime = null;
```

but of course it will be better if we could add a method in ionic.view.scroll:

```js
removePullToRefresh: function() {
    var scrollView = $ionicScrollDelegate.getScrollView();
    scrollView.__refreshHeight = null;
    scrollView.__refreshActivate = null;
    scrollView.__refreshDeactivate = null;
    scrollView.__refreshStart = null;
    scrollView.__refreshShow = null;
    scrollView.__refreshHide = null;
    scrollView.__refreshTail = null;
    scrollView.__refreshTailTime = null;
    scrollView.__minSpinTime = null;
}
```

**Comment by R1Daneel** [comment]
@danicomas you workaround works just if I want remove the pull to refresh but what about if I just want disable temporary the pull to refresh?
