### ISSUE TITLE
ion-infinite-scroll keeps firing after view has left 

### ISSUE THREAD

**Issue by Sjerd** [driftyco/ionic#2771]
hey, when you leave a view before the ion-infinite-scrol is finished the loadmore event is fired. the event keeps firing in a different view: http://codepen.io/sjerd/pen/QwErMQ

**Comment by jfitz0** [comment]
Also experiencing this

**Comment by pulakb** [comment]
Are you using beta-14 @Sjerd ?

**Comment by Sjerd** [comment]
Yes, I am. the codepen even uses the nightly build.

**Comment by pulakb** [comment]
Yes I faced the same problem with beta-14 but seems fine with beta-13. Please check with beta-13 once @Sjerd

**Comment by Sjerd** [comment]
@pulakb Yes, i confirm it worked with beta-13, but seeing the updates in beta-14 with functionality and performance it still has my preferences

**Comment by Sjerd** [comment]
This still exists, i don't think users will be happy to see their data bundles drained by a memory leak

**Comment by felquis** [comment]
The same problem here :/ http://forum.ionicframework.com/t/ion-infinite-scroll-is-looping-after-state-change-before-infinitescrollcomplete/19609

**Comment by Purus** [comment]
Facing same kind of issues too..

**Comment by perrygovier** [comment]
Is this still an issue?

**Comment by Ionitron** [comment]
Greetings @Sjerd!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
