### ISSUE TITLE
No animations

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2773]
The following codepen is the same than in #2642 :
http://codepen.io/arcanis/pen/WbQGVb?editors=101

At the time, the animation were triggering fine (after then issue had been closed). However, now there isn't any animation. Has something changed?

**Comment by arcanis** [comment]
@drewrygh The codepen are similar, but the underlying issue are not : in this issue, the history is broken and doesn't detect the correct forward/backward animation. In #2775, the issue is that ion-item doesn't implement the `nav-direction` attribute.

**Comment by arcanis** [comment]
Ping someone ? @drewrygh ? :no_mouth:

**Comment by mhartington** [comment]
The main issue is the states are setup incorrectly.

http://codepen.io/mhartington/pen/EaXjEp

**Comment by arcanis** [comment]
@mhartington But with your pen, the tabs are also in the "view" page. I'd like to transition from a page with tabs, to a page without tabs, while still preserving the hierarchy. I feel like the simple "are the elements inside the same state hierarchy" check isn't enough, and maybe it could be interesting to add a state metadata api. Something like that :

```js
.config( function ( $stateProvider ) {
    ...
    $stateProvider.state( 'home.library', { ... } );
    $stateProvider.state( 'view', { ..., data : { ionic : { parents : [ 'home.library' ] } } } );
} )
```
