### ISSUE TITLE
Doc: What are the meaning of nav-direction values?

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2774]
It's not clear what are the differences between `forward` and `enter` (or `back` and `exit`, or even `swap`, actually).

Could it be possible to add a note to explain the semantic of these directions?

**Comment by Jolg42** [comment]
+1

**Comment by craigrich** [comment]
+1

**Comment by arcanis** [comment]
@adamdbradley I don't really understand how works @Ionitron ... :confused:

**Comment by brentchow** [comment]
+1

**Comment by jackyon** [comment]
+1

**Comment by P4KM4N** [comment]
+1

**Comment by boboldehampsink** [comment]
+1

**Comment by craigrich** [comment]
Why is this closed? Was it resolved?

**Comment by arcanis** [comment]
Nope :(

**Comment by schmunk42** [comment]
@mlynch This should be reopened.

Or please point a link to the docs.
