### ISSUE TITLE
bug: blackberry tabs list detail will not transition

### ISSUE THREAD

**Issue by m4b** [driftyco/ionic#2776]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Running the default starter tabs app on a blackberry emulator, list item detail transitions do not work (i.e., clicking on a list item does not present the corresponding item's detail screen).  It looks like the href for detail items, i.e., something like `tabs/chat/:chatId` is not functioning correctly, since click events are registered.

Note, this is only for blackberry, as far as I know.  I don't have a physical device to test on currently, so this could also just be an emulator problem?

# Steps to reproduce for blackberry emulator:

1. run `ionic start bb_tabs_test tabs`
2. `cd bb_tabs_test; ionic platform add blackberry10; ionic build;`
3. run on emulator
4. Clicking on a "chat" or "friend" does not cause the transition to chat detail or friend detail; however, click events are registered, it just seems the href is not being respected

# Details

osx version: 10.10
ionic version: 1.2.13
cordova version: 4.1.2
vmware fusion version: 7.1.0</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @m4b!

My sensors indicate that I require more information in order to assist you.

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this happen occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 8, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using the framework itself, I recommended visiting [the forum](http://forum.ionicframework.com), where many humans will be able to offer wisdom and advice.

Thank you for allowing me to assist you.

<span ionitron-needs-reply></span>

**Comment by m4b** [comment]
Not sure why this was closed?

I've just re-verified the same problem on both the emulator in addition to a physical device (a blackberry Z30), taking the same steps outlined above: list items _do not_ transition to list details in a starter `tabs` project.

Again, tap events are registered on the individual list items.

I don't think this is an issue of a lack of transition animation, since the screen doesn't change at any point to the detail page state, and alert code monitoring for taps on the list items still runs on different list item taps (hence it hasn't secretly transitioned to the list detail state, otherwise that code wouldn't run).

Not sure what other details to give?  Just follow the steps above with a physical blackberry device or blackberry emulator to reproduce the bug.

**Comment by mhartington** [comment]
Cool, thanks for the extra info. Will leave this open look into down the road

**Comment by m4b** [comment]
update:

A colleague helped determine that on blackberry, `href` links in anchors, et. al., need to be whitelisted in order to be accessed (and hence allow the transition).

In particular, this line should be added in the `config` function of `app.js`:

````javascript
  $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|local):/);
````

The local exception is of particular importance, since internally, the app is using local html references to the app structure, and by default, these types of references are not allowed on the blackberry platform.

I've tested on a blackberry z30 and this solves the list transition problems for the tabs starter app, the side menu starter app, in addition to some custom code relying on `href` transitions.

If it's alright with you, I suggest the issue be closed, given the above caveat.

**Comment by perrygovier** [comment]
Thanks, this has been added as well (bottom of `ionicConfig.js`)
