### ISSUE TITLE
bug: Controller is reloaded, not reconnected

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2778]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Let's say you have state A and state B such as,

    .state("get-started.find-bill", {
        url: "/find-bill",
        views: {
            "get-started": {
                templateUrl: "templates/get-started/bills/find-bill-to-split-view.html",
                controller: "FindBillCtrl"
            }
        }
    })

and

    .state('app.add-biller', {
        url: '/add-biller',
        views: {
            'app-billers': {
                templateUrl: "templates/get-started/bills/find-bill-to-split-view.html",
                controller: "FindBillCtrl"
            }
        }
    })

These are two different states, but each use the same `templateUrl` and `controller`. When `get-started.find-bill` is first loaded, everything works fine. However, a few transitions down the line, `app.add-biller` is loaded. I expected the controller to be reconnected, but instead it is reloaded.

I saw this because of the `$ionicView.loaded` and `$ionicView.enter` events. Basically the process was this

State `find-bill` transitioned to -> `FindBillCtrl` loaded -> `FindBillCtrl` entered -> ... -> State `add-biller` transitioned to -> `FindBillCtrl` loaded -> `FindBillCtrl` entered.

I expected

... -> State `add-biller` transitioned to -> `FindBillCtrl` entered ... NOT loaded again.

The reason this is an issue is because I'm loading a modal in the `$ionicView.loaded` event in `FindBillCtrl`, hence the modal is loaded twice. Not reused.

I fixed it temporarily by setting `cache-view` to false, but I'd rather reconnect the controller properly. Thanks!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
close
