### ISSUE TITLE
bug: Abstract controller loaded each tab switch

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#2779]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Let's say you have this state, an abstract state for tabs.

    // setup an abstract state for the tabs directive
      .state('tab', {
      url: "/tab",
      abstract: true,
      templateUrl: "templates/tabs.html",
      controller: 'AbstractTabCtrl'
    })

With this controller

    .controller('AbstractTabCtrl', function($scope) {

      $scope.$on('$ionicView.loaded', function(){
        console.log('TesterCtrl');
      });

    })

Every time you click on a tab, the `$ionicView.loaded` event is fired. I expect it to only fire once, when the tabs are initially loaded.

This is an issue because I have code like this in the abstract controller.

	$scope.$on('$ionicView.loaded', function(){

		User.get().then(
			function(user) {
				$scope.$emit('user:set', user);
			})
		;
		
	});

This means every time a user is selecting a tab an API request is being fired to get the user. NOT GOOD. I wanted to get the user the first time the tabs are loaded. Not every time a user clicks an individual tab. Thanks!

</span>

<span is-issue-template></span>

**Comment by m69** [comment]
+1

**Comment by mhartington** [comment]
Correct me if I'm wrong @sean-hill, but was this in reference to the issue I helped you on with?

**Comment by sean-hill** [comment]
@mhartington you are correct! This can be closed.

**Comment by m69** [comment]
Can you reference the fix?

**Comment by sean-hill** [comment]
Here is the email thread that went between @mhartington and I. Hope it can help!

=== MIKE ===

So I have this codepen I put together to help explain events a bit better.

http://codepen.io/mhartington/pen/OPpqdo

This should help explain a bit how view events work.
If you are still having issue, would you be able to send me a copy of the project to look at?

=== SEAN ===

I modified your pen to fit my problem.

http://codepen.io/anon/pen/ogZVKG

I have a “ng-controller” on my “body” tag. Open up the console and click the “Main” button, then click back, then click “Main” again, you’ll see that “APP Loaded” is fired multiple times.

=== MIKE ===

Okay, so I think I see whats going on.

So since the controller is on the body, its catching all the view events, not a particular one.
Here’s the console output from your codepen.

	//First View
	APP: Out side View events
	APP Loaded
	APP Entered

	//Second View
	APP Loaded
	APP Entered

	//Back to First View
	APP Entered

Technically, it is firing correctly, but the functionality is catching things globally, since it is on the body tag.
So what I can suggest is that you remove the controller from your body tag, or place your view events as I had them in my original demo.

=== SEAN ===

Okay, so what would be the best way to have a parent controller for the entire app? I’ve done it in the past by attaching it to the “body” tag, but what is another option the Ionic way?

=== MIKE ===

Well you can have a parent controller on the body tag, but your view events have to be limited to specific views.

Since the scope that is placed on the body tag won’t be disconnected (since we’re not navigating to/away from it) you can still have some functionality in there.

=== SEAN ===

Okay, so no $ionicView events in my “AppCtrl”.

One last question that has been pressing. If I have an abstract state, such as for tabs, and link a controller to that, aka a parent controller for all the tabs, I’ve been getting a similar issue where “$ionicView.loaded” is fired each time a tab is clicked. I take it this is probably the same issue as the “body” tag?

=== MIKE ===

Yup, same thing as the body tag.

**Comment by sean-hill** [comment]
Basicallly, the `$ionicView` events should only be used on controller's referenced by your `$stateProvider`, aka not controllers used with `ng-controller="SomeCtrl"`, directives, or abstract states.

**Comment by m69** [comment]
Ah, now it makes sense, thanks for the clarity @sean-hill!

**Comment by sean-hill** [comment]
No problem :) Good luck @m69!

**Comment by vTrip** [comment]
@sean-hill I have a similar issue here...
I have no controller on my abstract state, but each other defined state does.

Whenever i switch between any tabs all tabs ionicView.loaded event is fired every time I simply enter that view.

Thoughts ?
