### ISSUE TITLE
bug: browser autofill background color overlaps input label 

### ISSUE THREAD

**Issue by legendar** [driftyco/ionic#27812]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In v7.1.3 auto-filled inputs still overlap their floating labels. The original issue was closed by BOT: #18141 but it still is not fixed in 7.x

### Expected Behavior

As for non-autofilled inputs, floating labels must stay entirely visible.

### Steps to Reproduce

An ion-item containing a floating ion-label and an ion-input that is auto-fillable and auto-filled.

### Code Reproduction URL

https://github.com/legendar/ion-input-label-issue

### Ionic Info

$ ionic info

Ionic:

   Ionic CLI       : 7.1.1 (/home/****/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.3

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/home/****/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : Linux 5.10

### Additional Information

![image](https://github.com/ionic-team/ionic-framework/assets/139363/d4e66cb1-e073-4273-8967-04e8a815840c)

possible workaround:

```
 .label-text-wrapper {
    z-index: 2;
  }

  .label-text-wrapper {
    transform: translateY(50%) scale(0.75) translateY(14px) !important;
    padding: 0 2px !important;
  }

  input {
    min-height: 50px;
    padding: 14px 2px 0 !important;
  }
```

**Comment by legendar** [comment]
Looks like it is working fine on the Dark theme. But still reproduced on a Light theme:

![image](https://github.com/ionic-team/ionic-framework/assets/139363/eb87d71c-ea42-4fce-bf6a-2e0672503d83)

![image](https://github.com/ionic-team/ionic-framework/assets/139363/1b0ac34e-b2b1-4276-8103-7bec6fdee870)

The light mode can be emulated via dev tools as described here: https://stackoverflow.com/a/61541260

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/react@7.2.1-dev.11690463567.10a4b6a7 @ionic/react-router@7.2.1-dev.11690463567.10a4b6a7
```

**Comment by legendar** [comment]
Checked the fix on a real project and it works fine:
![image](https://github.com/ionic-team/ionic-framework/assets/139363/6fcbdd89-e1b5-4997-bc3b-6180c9725b61)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27870, and a fix will be available in an upcoming release of Ionic Framework.
