### ISSUE TITLE
Repeat bug inside <tab> <content>

### ISSUE THREAD

**Issue by ncammarata** [driftyco/ionic#279]
``` html
<tab>
  <content>
    <ul><li ng-repeat="i in [1,2,3]">{{i}}</li></ul>
  </content>
</tab>
```

If I switch tabs and come back, I see 1,2,3,1,2,3

Video here using the starter example: https://vimeo.com/81239840

**Comment by arne3000** [comment]
This issue seems to be reoccurring in v1.0.0-beta.14

Looks like its something to do with line 48773

```
innerElement = jqLite('<div class="scroll"></div>');
innerElement.append(element.contents());
element.append(innerElement);
```

again this only really occurs when a ng-repeat list appears in a tab, not sure what the appropriate work around is

**Comment by ckahle33** [comment]
adding class no-animation suggested by @mlynch worked for me. Thanks.
