### ISSUE TITLE
bug: Method ionic.Platform.isIOS() didn't work

### ISSUE THREAD

**Issue by youssmak** [driftyco/ionic#2796]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The method return true for chrome Version 39.0.2171.95 (64-bit)
navigator.userAgent :
#Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"</span>

<span is-issue-template></span>

**Comment by chriswoodrich** [comment]
I'm having this same issue.

In my controller ```vm.isAndroid = ionic.Platform.isAndroid();``` works fine

and ```vm.isIOS = ionic.Platform.isIos();``` will cause the below bug on ```ionic serve```

``` TypeError: Cannot read property '0' of null
    at Object.$parseFunctionCall [as get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20125:22)
    at Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22012:40)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22282:24)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:24008:36
    at completeOutstandingRequest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12714:10)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13094:7```

**Comment by adamdbradley** [comment]
Could you be able create an codepen recreating the issue?

**Comment by Ionitron** [comment]
Greetings @youssmak!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
