### ISSUE TITLE
bug: 'add' is not a vaild command - Installing an Ionic

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic#2797]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hey Ionic,

I'm trying to install the Tinder-style cards ion from ions.ionic.io but whenever I paste this: ionic add ionic-ion-tinder-cards in the ionic CLI it says add is not a valid task. I've run 'npm update -g ionic' and 'ionic lib' but that still doesn't fix the problem?</span>

<span is-issue-template></span>

**Comment by jbavari** [comment]
@ghost - I think what has happened here was the `ionic-ion-tinder-cards` is somehow not on bower. 

Under the hood, `ionic add` runs bower. Let me check the status of the bower package.
