### ISSUE TITLE
 RTL direction problems

### ISSUE THREAD

**Issue by ghominejad** [driftyco/ionic#2799]
it seems RTL languages are fully supported in ionic but when i set rtl in the html or body tag (`<body  dir=rtl>`) everything works fine but when ionic wants to show pages that have return button, then displays white page and hanging...
I think there must be a css transition problem.

**Comment by Ionitron** [comment]
Greetings @ghominejad!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you for allowing me to assist you.

**Comment by rosell** [comment]
Hi!

I have a similar problem. I created a new project with the next commands:
ionic start test tabs (I no create an ionic account)
cd test
ionic platform add android osx browser

After that I modify the www/css/style.css adding the next lines:
body {
	 direction: rtl !important;
	
}

Then  if I emulate it in android or osx and follow the next steps:
 1) click over 'Chat' 
 2) Click on the first item of the list

The window seems to load the chat but after some milliseconds it converts into a blank page.
Finally if I emulate in a browser, this behaviour does not appears after i click over the 'Chat' on the top to come back.

**Comment by rosell** [comment]
Hi!

Thanks to moussaoui91 (https://io.hsoub.com/programming/22094-%D8%AA%D8%AC%D8%B1%D8%A8%D8%AA%D9%8A-%D9%81%D9%8A-%D8%A5%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-ionic-framework-%D9%81%D9%8A-%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D8%AA%D8%B7%D8%A8%D9%8A%D9%82-%D9%84%D9%84%D8%A3%D8%AC%D9%87%D8%B2%D8%A9-%D8%A7%D9%84%D8%AC%D9%88%D8%A7%D9%84%D8%A9)

I fix the problem disabling the transitions. For this add the next lines into the www/js/app.js

.config(function($ionicConfigProvider) {
$ionicConfigProvider.views.transition('none');
})

**Comment by keshavkhatri** [comment]
Thanks @rosell you saved my day, it was the perfect solution.
