### ISSUE TITLE
scrollView.scrollBottom() is closing the Keyboard on Android.

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic#2801]
The Keyboard is open, i call scrollView.scrollBottom(), then the keyboard is closing and losing the focus from the input field.

**Comment by sloops77** [comment]
A few more details for those looking for a solution:

see this commit on my own fork https://github.com/sloops77/ionic/commit/c96af221a7c4edb68a91a867c4663c1efa23fb4e. you can cherrypick it if u like.

Note that my fork of ionic also contains commits for trigger.io support which you probably dont want

**Comment by adamdbradley** [comment]
DomUtil.blurAll() has been removed

**Comment by do-web** [comment]
On the current rc1 version the keyboard is again closing, if i call $ionicScrollDelegate.scrollBottom();

**Comment by 3jFernando** [comment]
Tengo un problema con el scrollBottom funciona bien en IOS pero en ANDROID no me lleva hasta el final se queda antes
