### ISSUE TITLE
$ionicHistory not working for change sideMenu

### ISSUE THREAD

**Issue by sunshineo** [driftyco/ionic#2802]
I asked this before here https://github.com/driftyco/ionic/issues/2713 and it got closed. But the solution does not work for me. Now I have a example project here to illustrate the problem.
https://github.com/sunshineo/ionic-sidemenu

I have enable-menu-with-back-views set to true.
![screen shot 2014-12-22 at 11 32 50 pm](https://cloud.githubusercontent.com/assets/1072766/5535404/e40e0ff6-8a32-11e4-99f7-15e97e3ab9b3.png)

When the app starts, I'm at http://localhost:8100/#/app/playlists
![screen shot 2014-12-22 at 11 45 06 pm](https://cloud.githubusercontent.com/assets/1072766/5535495/9c7e8ae2-8a34-11e4-8635-c0a16e1ffa8a.png)

I open the side menu, click "Browse"
![screen shot 2014-12-22 at 11 33 50 pm](https://cloud.githubusercontent.com/assets/1072766/5535407/043811e6-8a33-11e4-9418-83ae744a60c9.png)
![screen shot 2014-12-22 at 11 45 50 pm](https://cloud.githubusercontent.com/assets/1072766/5535499/b7897090-8a34-11e4-8fed-8ae8236fd21d.png)

I added a back button that will try to use $ionicHistory to go back. I see the alert but the $ionicHistory.goBack() does not work. It just stays here. 
![screen shot 2014-12-22 at 11 35 13 pm](https://cloud.githubusercontent.com/assets/1072766/5535510/0142c204-8a35-11e4-8cbe-5407d9ee2157.png)

However, if I go back to Playlists and do not use the sideMenu but type http://localhost:8100/#/app/browse in the browser I got this:
![screen shot 2014-12-22 at 11 43 43 pm](https://cloud.githubusercontent.com/assets/1072766/5535486/69bc2a92-8a34-11e4-9c7a-57f84827a6c3.png)
And the back button works.
I'm thinking navigate through the side menu will clear history. But enable-menu-with-back-views is not the flag to stop it from clearing. The documentation seems to say that it is the flag about if you want to have side menu sandwich when you went one level down for example to an item on the Playlist. What I need is to NOT clear history when navigate through side menu.

**Comment by Lintzman** [comment]
I was having the same issue until I found this post and replaced all my menu-close with menu-toggle="right".

**Comment by nerdyorion** [comment]
Hi, you can update your starter sidemenu template to reflect the 'menu-close' to 'menu-toggle' change then.
Got stuck for a little while.

**Comment by lentyaishe** [comment]
@mhartington You're the king. Fought with this issue too long and the solution was so easy!
