### ISSUE TITLE
bug: collection repeat still repeating the item

### ISSUE THREAD

**Issue by hasainsab14** [driftyco/ionic#2804]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The issue is similar to below one only the difference is am using slidebox instead of delete-button and ion-option-button http://codepen.io/mhartington/pen/pnbiy</span>

<span is-issue-template></span>

**Comment by panurge-ws** [comment]
Hi guys,
 
this happens probably because the directives inside of the ion-item ( like ionDeleteButton ) are requiring the ionList controller, but in collection-repeat the parent is not a ion-list (but another div) so the controller is not passed to the directive. When the item is added to the collection, e.g. after scrolling, the directive can't find the controller and so it doesn't know if it's showing the options button or delete button.
E.g.: directive ionDeleteButton
try to add a console.log of the listCtrl, you will receive always a null value:
 
```javascript
  IonicModule
  .directive('ionDeleteButton', function() {
    return {
      restrict: 'E',
      require: ['^ionItem', '^?ionList'],
      //Run before anything else, so we can move it before other directives process
      //its location (eg ngIf relies on the location of the directive in the dom)
      priority: Number.MAX_VALUE,
      compile: function($element, $attr) {
        //Add the classes we need during the compile phase, so that they stay
        //even if something else like ngIf removes the element and re-addss it
        $attr.$set('class', ($attr['class'] || '') + ' button icon button-icon', true);
        return function($scope, $element, $attr, ctrls) {
          var itemCtrl = ctrls[0];
          var listCtrl = ctrls[1];
          var container = jqLite(ITEM_TPL_DELETE_BUTTON);
          container.append($element);
          itemCtrl.$element.append(container).addClass('item-left-editable');
          console.log(listCtrl);
          // listCtrl is always null so the lines below are never executed
          if (listCtrl && listCtrl.showDelete()) {
            container.addClass('visible active');
          }
        };
      }
    };
  });
```

**Comment by panurge-ws** [comment]
The issue on the codepen above seems to happen only on mousewheel event.
A workaround is to add a listener to the ionic.ListView

add:
```
    window.addEventListener('mousewheel', function(e) {
          _this._lastDragOp && _this._lastDragOp.clean();
      }); 
```
after:
```
    window.ionic.onGesture('drag', function(e) {
        _this._handleDrag(e);
      }, this.el);
```

**Comment by hasainsab14** [comment]
This issue is not fixed for me. even the above codepen example issue exists still. don't know how come its closed.
 
I have created a exact example here http://codepen.io/anon/pen/LVOMEb if that helps to better understand the issue. any help would greatly help me.

**Comment by hasainsab14** [comment]
To add more details to above example. Am using a slide box with 2 slide in a collection repeat. 

The issue is if i make a slide 2 on any item active and scroll down, i would see the next items in list at the approx position of the item swiped would be come active.

**Comment by hasainsab14** [comment]
could this issue be re-opened or should i create new one?
