### ISSUE TITLE
Ionic Side Menu Content Scrolls While Pulling

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#2808]
The Ionic Side Menu Content on our app scrolls while it is being pulled. So for example when we are pulling to the the menus of the side menu, the main content is scrollable which should not be. This was notices first on Android 4.4 on a HTC one m8

**Comment by 7thsonch** [comment]
I've got the same problem since beta 14, worked just fine with beta 13.
Even with commit https://github.com/driftyco/ionic/commit/9f437a8c2bb168be4452ec99c40e9b3aefbad11a its still broken.

**Comment by mhartington** [comment]
Passing this to @perrygovier

**Comment by kaliagaurav** [comment]
Is this fixed for iOS?

I am using Ionic v1.2.4 and on iPhone I am still getting this issue.
