### ISSUE TITLE
Slidebox ran out of memory since it loads everything in one go

### ISSUE THREAD

**Issue by sunshineo** [driftyco/ionic#2810]
I was trying to load 500 images into slide box. I got this when running on real device
2014-12-24 05:29:07.861 myApp[11296:4389346] Received memory warning.
After that, it just crashes.

I tried to use collection-repeat but it seems does not work with slidebox
What can I do?

**Comment by jyxt** [comment]
adding ng-if to slidebox's children helps
http://forum.ionicframework.com/t/ios-recieved-memory-warning-then-terminated-due-to-memory-pressure/3399/5
