### ISSUE TITLE
v1.0.0-beta.14: wrong ion-slide-box width after opening modal

### ISSUE THREAD

**Issue by marmorkuchen-net** [driftyco/ionic#2817]
### Code-Pen

http://codepen.io/anon/pen/ZYpRzw

The first view contains a slider-box inside a cached view, this slider breaks after opening a modal. This bug occurs only in cached views (since beta 14 release).

Steps to reproduce:

- go to second view
- open modal
- close modal
- go back to first view

### Description

Opening a modal triggers an window.resize Event.
https://github.com/driftyco/ionic/blob/master/js/angular/service/modal.js#L163

Slider-directives are listening to these resize events although theyre not visible and in cached mode. Theire event handlers are not being unregistered when put in view-cache.
https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L7314 (is `kill`method ever called? cant find the handler).

The triggered resize event calls the setup() function of the Slider, calculating the width of the slider container. Since this element is not visible at this point the width will be set to zero.
https://github.com/driftyco/ionic/blob/master/release/js/ionic.js#L7109

There might propably be more bugs of this kind with other elements listening to a resize event although theire not shown.

Related issue: https://github.com/driftyco/ionic/issues/2309

**Comment by willyboy** [comment]
Having this issue as well.

**Comment by dmishh** [comment]
I have the same issue. @sloops77 thanks for the workaround!

**Comment by darrynten** [comment]
:+1: have the same issue

http://codepen.io/anon/pen/dPJGKY

**Comment by wfsm** [comment]
I have the same issue too. @sloops77 I used your solution, but the slides doubled after manually resize, I use ng-repeat to show the slides

**Comment by ZelimDamian** [comment]
I have a the same problem. Show slidebox -> show modal -> back to slidebox , but its not visible.

My initial workaround (somewhat nasty):

``` javascript

  // assuming the slides are static cache this to save DOM lookups
  //var firstSlide = $('.container .slide').first();
  $scope.$watch(function() {
    // this is the nasty bit (visibility polling)
    var visible = $('.container .slide').first().is(":visible");
    return visible;
  }, function(visible) {
    // only need to do this when visible
    if(visible) {
      var width = $('.container .slide').first().width();
      // only update when the width is wrong
      if(width === 0) {
        $scope.updateSlider();
      }  
    }
  });
```

I tried @sloops77 's solution, which seems to work nicely. Except that that I call not the resize trigger, but the slideBoxDelegate update directly. I think this will save some extra work, because resize may trigger all kinds of other updates. Here is how I do it:

``` javascript
  // assuming the slides are static cache this to save DOM lookups
  // var firstSlide = $('.container .slide').first();
  $scope.$on('$ionicView.beforeEnter', function() {
    // this is not polling anymore
    var width = $('.container .slide').first().width();
    // only update when the width is wrong
    if(width === 0) {
      $ionicSlideBoxDelegate.update();
    }
  });

```

**Comment by gilles-yvetot** [comment]
same problem here! Any update @adamdbradley ?

**Comment by imuhammad** [comment]
+1

**Comment by DavidePastore** [comment]
:+1: Same problem for me.

**Comment by hasainsab14** [comment]
Hi there, 

The workaround is not working for me. could some one give codepen sample plz?

**Comment by fahimshani** [comment]
making cache-view="false" in template file or cache: false in state worked for me.

**Comment by CyrilSabbagh** [comment]
I don't know why this issue is closed but i'm still having this problem. all libs are up to date

**Comment by jcromp** [comment]
I had this issue today as well, 
@imuhammad  This fixed it, thanks!

**Comment by Heckthor** [comment]
Is there an actual fix for this instead of just workarounds?
