### ISSUE TITLE
bug: $ionicView events do not update $scope directly

### ISSUE THREAD

**Issue by olivierlesnicki** [driftyco/ionic#2818]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicView.leave (incl. $ionicView.beforeLeave, etc...) doesn't update view's scope until the user enters the view again.</span>

<span is-issue-template></span>

**Comment by olivierlesnicki** [comment]
This is probably linked to
https://github.com/driftyco/ionic/issues/2742

**Comment by shprink** [comment]
"@adamdbradley none of the events seem to modify the data, but the alerts do still fire correctly."

I am having the same issue on beta14. Only ```$ionicView.enter``` modifies the scope when leaving. Though the scope updates correctly when coming back ```vm.viewEntered = false``` 

```
    $scope.$on '$ionicView.enter', () ->
        $log.debug '$ionicView.enter posts'
        vm.viewEntered = true

    $scope.$on '$ionicView.beforeLeave', () ->
        $log.debug '$ionicView.beforeLeave posts'
        vm.viewEntered = false

    $scope.$on '$ionicView.leave', () ->
        $log.debug '$ionicView.leave posts'
        vm.viewEntered = false

    $scope.$on '$ionicView.afterLeave', () ->
        $log.debug '$ionicView.afterLeave posts'
        vm.viewEntered = false
```

Hope it helps

**Comment by softBarbarian** [comment]
I was wondering if there was any progress on the issue or, perhaps, a workaround?

**Comment by shprink** [comment]
@softBarbarian I used the Ui router ```$stateChangeStart``` event to know for sure that I left the view

```
    $scope.$on '$stateChangeStart', () ->
        $log.debug '$stateChangeStart posts'
        $scope.$apply ->
            vm.viewEntered = false
```

**Comment by olivierlesnicki** [comment]
@softBarbarian @shprink a fix has been provided by @colllin https://github.com/driftyco/ionic/issues/2742#issuecomment-67288029

Maybe he should raise a pull request.
