### ISSUE TITLE
[feature] menu-close for swippable ion-items

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2821]
Currently, when clicking on a ion-option-button element, the options don't disappear. It would be nice to have a way to close them (just like menu-close for side menus).

**Comment by Ionitron** [comment]
Greetings @arcanis!

Thank you for the feature request. We will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
