### ISSUE TITLE
Customizing Ionic With Sass

### ISSUE THREAD

**Issue by RobFerguson** [driftyco/ionic#2823]
On the "Customizing Ionic With Sass" (http://ionicframework.com/tutorials/customizing-ionic-with-sass/) page it would be good if you could also mention the changes required to "index.html":

```
    <title></title>

    <link href="css/ionic.app.css" rel="stylesheet">

    <!--
    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
    <link href="css/ionic.app.css" rel="stylesheet">
    -->

    <!-- ionic/angularjs js -->
    <script src="lib/ionic/js/ionic.bundle.js"></script>
```

And a paragraph about how to include fonts (e.g., copy them into your project's "www/lib/ionic/fonts" directory and refer to them in "ionic.app.scss") would be good to.

**Comment by RobFerguson** [comment]
I used bower to install "fontawesome":

    bower install fontawesome --save

Bower will put the files in "www/lib" as per ".bowerrc" and update "bower.json". Then, I updated the "$fa-font-path" variable in "font-awesome/scss/_variables.scss":

    $fa-font-path:  "../lib/fontawesome/fonts" !default;

Then, I updated "scss/ionic.app.scss" to import "fontawesome":

    @import "www/lib/fontawesome/scss/font-awesome";  

Then I re-ran the "gulp sass" task and added a fontawesome icon to my template: 

    <i class="fa fa-bars"></i>

**Comment by Wolfr** [comment]
Yeah adding a separate font is definitely the easiest route but kind of redundant, and pretty bad performance wise.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#237
