### ISSUE TITLE
Button-block button not positioned correctly in ion-subfooter-bar

### ISSUE THREAD

**Issue by RobFerguson** [driftyco/ionic#2824]
With:

    <ion-subfooter-bar class="bar bar-subfooter bar-light">
        <button class="button button-block button-balanced">
            REVIEW ORDER
        </button>
    </ion-subfooter-bar>

![screen shot 2014-12-29 at 09 58 27](https://cloud.githubusercontent.com/assets/3479070/5565230/53e16950-8f41-11e4-8408-88ac54bb0e43.png)

To fix:

    <ion-subfooter-bar class="bar bar-subfooter bar-light">
        <button class="button button-block button-balanced" style="margin-top: 0px">
            REVIEW ORDER
        </button>
    </ion-subfooter-bar>

![screen shot 2014-12-29 at 09 53 37](https://cloud.githubusercontent.com/assets/3479070/5565237/67b93b1a-8f41-11e4-9c02-04fa6bbd3c1c.png)

**Comment by doggan** [comment]
Thanks for the temporary workaround. I ran into this issue using the `ion-footer-bar` and `button-block` combination.

**Comment by levelup-fx** [comment]
Thanks for the fix.

**Comment by dustinrwh** [comment]
I appreciate the fix :)

**Comment by small-yellow-rice** [comment]
the reason for this is follow css in ionic.css
  .button.button-block, .button.button-full {
    margin-top: 10px;
    margin-bottom: 10px; }

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue in the latest version of ionic?

**Comment by keckelt** [comment]
I'm having the issue using ionic 1.7.14

**Comment by jgw96** [comment]
Hello @RobFerguson are you still having this issue with ionic 1.3.0? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by hervethouzard** [comment]
Hello,

Sorry but the issue still exists for ion-footer-bar (I'm just using one button)
