### ISSUE TITLE
Input with placeholder doesn't work in iOS 8

### ISSUE THREAD

**Issue by mladenp** [driftyco/ionic#2827]
If i add input field with **placeholder** and try to type in something it doesn't enter that into input field. It seems that placeholder doesn't get removed when input is in focus, which is probably desired behavior, and placeholder disappears once you start typing. **But** nothing gets inserted into input box.
Once i remove placeholder everything works. The thing is that if i want to remove placeholder on focus and place it back on blur, it seems that browser gets confused with js *this* keyword.
So if i put:
> onfocus="this.placeholder=''" onblur="this.placeholder='your name'"
On two input fields, it seems like browser gets confused and only the input field i clicked first works ok, second one is broken.

When input field is **broken** it simply doesn't record characters i typed in, when i leave that field its left with no text or sometimes with last typed character.

This is of course very weird and it looks like iOS does something out of the ordinary with placeholders.

**Comment by mladenp** [comment]
Ionic provides working keyboard plugin and code for it is bundled if you use tabs or sidemenu. So that's not the problem.
This codepen @alarner provided is working fine on iPad on iOS8.
The problem with input field only appears for me when using placeholder.
I'll try to provide video recording on Monday when i get back to work.

**Comment by mhartington** [comment]
@mladenp So you are trying to do something like this? 

http://codepen.io/mhartington/pen/JoNJJd

using `onfocus="this.placeholder=''" onblur="this.placeholder='your name'` should be avoided. Instead create a simple directive for this.
