### ISSUE TITLE
[Tablet] Navbar on multiple views

### ISSUE THREAD

**Issue by apavillet** [driftyco/ionic#2830]
Hello, 

We used the ionic multiple views from https://github.com/alongubkin/ionic-multiple-views which worked great on beta 13.

On beta 14 it somewhat works but the navbar of the first view is not displayed : I made a plunkr using the demo from the repo to show the problem http://embed.plnkr.co/4XnSCrg8H7cRZluBcfHO/

Any thoughts on this ? It is very close from working and ( to me ) really is something a lot better for tablet than just showing the menu ( original demo here : http://alongubkin.github.io/ionic-multiple-views/demo/index.html#/masterDetail/messages)

Thanks

**Comment by Ionitron** [comment]
The issue seems to be with the plugin and should be fixed on that end.
