### ISSUE TITLE
Cannot read property 'statusCode' of undefined. 

### ISSUE THREAD

**Issue by javidrashid** [driftyco/ionic#2831]
I am running node v0.10.28, and I am getting the following error when cloning the App created with creator:

TypeError: Cannot read property 'statusCode' of undefined at Request,_callback(/path/to/node_modules/ionic/lib/ionic.js)

at self.Callback ('path/to/ionic/node_modules/request/request.js')

Is that because the creator is not in sync with the Ionic node modules.?

Thanks

**Comment by jbavari** [comment]
Trying to catch up here - are you running `ionic serve`?

**Comment by javidrashid** [comment]
No. I had ionic already installed and when I tried creator for the first time I am getting this error.

**Comment by jbavari** [comment]
@javidrashid - would you mind running `ionic info` and pasting that information here? That will help me figure out what you're working with.

**Comment by javidrashid** [comment]
There you go:  
_             _
 (_)           (_)
  _  ___  _ __  _  ___
 | |/ _ \| '_ \| |/ __|
 | | (_) | | | | | (__
 |_|\___/|_| |_|_|\___|  CLI v1.2.13

Usage: ionic task args

=======================

info is not a valid task

Available tasks: (use --help or -h for more info)

   start  ..........  Starts a new Ionic project in the specified PATH
   serve  ..........  Start a local development server for app dev/testing
   platform  .......  Add platform target for building an Ionic app
   run  ............  Run an Ionic project on a connected device
   emulate  ........  Emulate an Ionic project on a simulator or emulator
   build  ..........  Locally build an Ionic project for a given platform
   plugin  .........  Add a Cordova plugin
   package  ........  Package an app using the Ionic Build service (beta)
   upload  .........  Upload an app to your Ionic account
   lib  ............  Gets Ionic library version or updates the Ionic library
   setup  ..........  Configure the project with a build tool (beta)
   service  ........  Add an Ionic service package and install any required plug
ins
   add  ............  Add a bower component to the project
   remove  .........  Remove a bower component from the project
   list  ...........  List bower components from the project


C:\Users\mypcname...

**Comment by jbavari** [comment]
Please upgrade to the latest version of the CLI.

`npm install -g ionic`.

**Comment by javidrashid** [comment]
I think this problem is caused due inconsistent versions of  ionic and ionic-creator, that aren't cross compatible. I am closing the bug for now.

**Comment by sv400** [comment]
Please help

$ ionic start frontEndAwesome sidemenu

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occurred and has been reported to Ionic

Cannot read property 'statusCode' of undefined (CLI v1.6.4)

Your system information:

Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.2 Build version 6C131e
