### ISSUE TITLE
Backdrop events

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2833]
This issue is related to #2686. I really need to pause an animation when the user is doing something else (popover, popup, actionsheet, you name it), and afaik it's currently impossible (because only the popups have on/off events).

I think that the best way to solve it (maybe better than what I suggested in #2686) would be to add on/off events to the $ionicBackdrop service. Binding to it would be trivial and semantically right.

**Comment by Ionitron** [comment]
Greetings @arcanis!

Thank you for the feature request. We will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
