### ISSUE TITLE
Brief black screen and no keyboard when transitioning to page with auto-focused field

### ISSUE THREAD

**Issue by beauby** [driftyco/ionic#2836]
When pushing a view with an auto-focused textfield on the navigation view hierarchy, the transition is broken: the keyboard appears on a black background, then seems to disappear behind the page it is supposed to display on. Removing the `autofocus` attribute of the textfield makes the problems go away. I can provide a minimal app that shows this behaviour if needed.
Using ionic 1.0.0-beta14, on iOS8 simulator.

Otherwise, ionic seems very promising, keep up the good work!

**Comment by beauby** [comment]
Here's a CodePen. The issue arises (afaik) on the iOS8 simulator.

**Comment by softBarbarian** [comment]
You can fix this by changing transition background variable in _transitions.scss file in ionic dist folder

**Comment by beauby** [comment]
@softBarbarian: The black background is not really the issue here. The main problem is that the keyboard appears at the beginning of the transition, and then disappears.

**Comment by tlancina** [comment]
Closing this as I believe the black screen issue has been resolved.  The best bet is to call focus in a timeout after the transition, which should work fine.

Please feel free to re-open if the black screen transition issue is still present.
