### ISSUE TITLE
$ionicHistory.clearHistory() does not work

### ISSUE THREAD

**Issue by meenie** [driftyco/ionic#2839]
Please see this codepen: http://codepen.io/anon/pen/myOVmy?editors=101

I've added `cache: false` to the  'Contact Tab' state so it's controller is executed every time.  You can see that I'm running `$ionicHistory.clearHistory()` within there, but when you go back to the 'Home Tab' it does not fire the `console.log()` inside it's controller.

Am I using this incorrectly? Or is it broken?

**Comment by drewrygh** [comment]
`$ionicHistory.clearHistory()` doesn't clear cached views, only the navigation history. You're probably looking for [$ionicHistory.clearCache](http://ionicframework.com/docs/api/service/$ionicHistory/). Alternatively, you could add `cache: false` to your **home** state.

**Comment by meenie** [comment]
Yup, you are totally right.  First time I've used this framework so I'm not totally familiar.  Thanks!
