### ISSUE TITLE
Android - scrollbar visible even when there is no scroll possible

### ISSUE THREAD

**Issue by dbaq** [driftyco/ionic#284]
As you can see on the screenshot below, the scrollbar appears on Android all the time.

everything is fine on iOS/chrome

![screenshot_2013-12-06-18-57-23](https://f.cloud.github.com/assets/1867703/1697578/f895d2ba-5eeb-11e3-9384-17d2aaf0aa25.png)

**Comment by smajl** [comment]
I get this after updating to newest Ionic 1.2. Scrollbar has also lower z-index (is underneath) several UI elements like input and ion-radio.

**Comment by fenglu09** [comment]
Today I meet the same problem on Android device.  my ionic was  1.2.1

**Comment by jackcruz** [comment]
Today I have upgraded to 1.2.1 and I have the same issue.

**Comment by kumaro** [comment]
Having this issue after upgrading to 1.2.4 from 1.0.1

**Comment by sluipmoord** [comment]
Having the same issue after upgrading to 1.2.4 from 1.1.0

**Comment by jackcruz** [comment]
still having this issue after upgrading to 1.2.4. 

This only happens on android 4.4.2. Could not see the same issue on 5.x.x onwards

**Comment by marcbc** [comment]
Same in 1.2.4

**Comment by rbarriuso** [comment]
Same here with ionic 1.2.4 on Android 4.4.2 and 5.1. Any idea why?

**Comment by terrytong** [comment]
Try installing Crosswalk might solve the problem. I had similar issues with the default Android webview, but switching to Crosswalk seems to fix it.

**Comment by ravishtiwari** [comment]
I am also facing this problem, using ionic 1.2.4, iOS is fine, but, always visible scrollbar on Android.

**Comment by cesar-oyarzun-m** [comment]
I have the same problem, I just update to pointing to master

**Comment by z4139jq** [comment]
Same problem using Ionic 1.2.4, but, no scrollbar at all if using Ionic 1.2.3, both with native scroll

**Comment by robertochajin** [comment]
I have the same issue with Ionic since Ionic 1.2.1 in android 4.4.2 and 5.1.1

**Comment by z4139jq** [comment]
Installing crosswork solved my problem，if that's not your option, maybe you should disable native scrolling temporarily

**Comment by rynomster** [comment]
I've also got the same issue. Android 5.1.1 and Ionic 1.2.4

**Comment by dcinadr** [comment]
I am having the same problem when I view the app with Ionic Lab.

**Comment by spanning** [comment]
Any news on this one? I have the same issue with the latest ionic and xwalk

**Comment by spanning** [comment]
Only happens with native scrolling (overflow-scrolling="true")

**Comment by rberthome** [comment]
Still the same for me, the user has to tap on the content to hide the scrollbar. Any news about this ?

**Comment by smajl** [comment]
Maybe the problem is that this issue is closed.
@brandyscarney Could you please review and reopen this? A lot of people have this issue.

**Comment by kingstakh** [comment]
Ionic 1.3.1 / Android 4.4.2 have this issue to

**Comment by smajl** [comment]
@jgw96 Sorry, didn't have time to catch up with our mobile app till today.

Ionic 1.3.1 (just upgraded) / Android 4.4.2

Sorry, don't have minimal example, but this bug is present immediately on our login page which is simple `ion-view` with `ion-content` and footer bar. No overflowing content but scrollbar permanently visible. After I focus an input (and keyboard appears), the scrollbar disappears and is not visible even when scrolling (the now overflowing content). Appears again after bluring input and hiding keyboard.

**Comment by loursbourg** [comment]
_Please_, **fix** _this_ **problem** _as_ **soon** _as_ **possible**.

**Comment by VinceOPS** [comment]
Hi everyone. Experiencing this too with ionic 1.3.1 and Android 5+ & 6+.
Please see also https://forum.ionicframework.com/t/overflow-scroll-ion-content/1382/12

**Comment by akhtar-gits** [comment]
.overflow-scroll{overflow-y:auto;} worked for me. thanks
