### ISSUE TITLE
suggestion：remove page transition effect or add fadein fadeout effect  on ion-nav-view

### ISSUE THREAD

**Issue by jacksun123** [driftyco/ionic#2840]
I don‘t like the side efect of ionic ,because when i back from content page to news list  page or from news list page nvaigate to content page,slide effect  lead to performance problem。

**Comment by drewrygh** [comment]
Hey @jacksun123, you can control this setting `nav-transition=none` on any element that changes views in a nav-view:

[nav-transition docs](http://ionicframework.com/docs/api/directive/navTransition/)

**Comment by jacksun123** [comment]
Thank you

**Comment by drewrygh** [comment]
No problem!

**Comment by boostani** [comment]
How do you set nav-transition to none in controller?
