### ISSUE TITLE
Abstract state resets history

### ISSUE THREAD

**Issue by khashayar** [driftyco/ionic#2843]
I have an abstract state with two sub-states. On beta 13, everything works perfectly. When I switch to this state, it changes with animation, shows me the back button & keeps the history. After upgrading to beta 14, when I navigate to this state, no transition animation happens & back button wouldn't show up. If I comment the `abstract: true` on the state definition, again it works as before with no problem!

I tried to track it down and found following condition, where there's a special check for abstract states and set the direction to none:
https://github.com/driftyco/ionic/blob/4130c5a1c3db8a8061d18c7699621234a752568a/js/angular/service/history.js#L288

Is this change of behavior on abstract states intentional?

**Comment by felquis** [comment]
I have the same problem, I created a codepen to reproduce the problem and how to reproduce, I posted in the forum http://forum.ionicframework.com/t/problem-with-transition-between-abstract-views/14402

**Comment by sgandon** [comment]
I have the same problem and also realized that removing the *abstract:true* made it work but I am not sure this is a valid workaround.

**Comment by adamdbradley** [comment]
An abstract state isn't its own view, but a container for views. As in, it doesn't have it's own URL to go to.

This is kind of related to the back button too. When you have 2 tabs, you cannot use the back button to switch between tabs, rather, it only goes "back" in the same tab, or history. When you're using abstract states, you're giving it a new history stack for all of those views, but the back button is only for that history stack.

If you do need the back button to work between histories I would first recommend a different structure. However, I will try to think of better ways to handle your scenario, as it's a common problem. Thanks

**Comment by MarcWadai** [comment]
I would like to know like @sgandon mention. If we remove the abstract attributes it works. But is it a valid/correct workaround if the implementation and design can't be change ?
Thx !
