### ISSUE TITLE
[Beta 14][Android] input type='tel' is overlapped by openned keyboard

### ISSUE THREAD

**Issue by sudodoki** [driftyco/ionic#2844]
Clicking on input of type 'tel' brings up numeric keyboard, but no scrolling up occurs - leaving input hidden under the keyboard.

**Comment by drewrygh** [comment]
Do you have [ionic keyboard](https://github.com/driftyco/ionic-plugins-keyboard) installed? `ionic-cli` should add this automatically in recent versions, but if you're using an older version you may need to add it automatically.

[Using codepen](http://codepen.io/drewrygh/pen/dPOzex?editors=101), I can't replicate this - the scrolling works. Can you add the keyboard plugin? If it's still a problem, what Android version is this happening on?

**Comment by sudodoki** [comment]
Yes, I have `<param name="android-package" value="com.ionic.keyboard.IonicKeyboard" onload="true" />`. Device is Moto G 1st generation that has Android 4.4.4 on board.

**Comment by drewrygh** [comment]
Strange, I'm using the same exact device and android version. Can you test using the demo I made to check if it's a npm/build issue? To build:
```
ionic start test http://codepen.io/drewrygh/pen/dPOzex?editors=101 && cd test/
ionic platform add android
ionic build android
ionic run android
# scroll through text to the bottom, click input
```

If it works in the demo for you, would you be able to post some of your code, or build a codepen that demonstrates the issue?

**Comment by sudodoki** [comment]
Oh, my bad, I think it might be an issue to blame on [crosswalk](https://crosswalk-project.org/).

**Comment by sudodoki** [comment]
To be clear: codepen worked just fine on my android,

**Comment by baleboy** [comment]
@sudodoki is this still an issue? I tried with the latest Ionic (1.6.4) which includes Crosswalk 13 by default, and it worked fine.

**Comment by mhartington** [comment]
Closing since this issue is related to crosswalk, not ionic
