### ISSUE TITLE
bug: $ionicLoading doesn't work with `delay` property

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2846]
I have the following code in the line 73 in this codepen http://codepen.io/felquis/pen/yyVXbY

```js
  $ionicLoading.show({
    template: "Loading...",
    delay: 2000,
    duration: 5000
  });
  
  setTimeout(function () {
    $scope.$apply(function () {
      $ionicLoading.hide();
    });
  }, 1000);
```

When the `delay` property is present, the $ionicLoading doesn't show, if I remove the `delay` property it works fine.

**Comment by gkalpak** [comment]
Isn't it what `delay` is supposed to do ?
If I am not mistaken, your code means "Show the loader after 2 secs", but then after 1sec you override it by stoppign `$ionicLoading`.

I'd say this works as expected.

**Comment by drewrygh** [comment]
Hey @felquis, @gkalpak is right, the `delay` param is basically just a shortcut to `$timeout` or `setTimeout`, or what you're doing in the following block:

```
  setTimeout(function () {
    $scope.$apply(function () {
      $ionicLoading.hide();
    });
  }, 1000);
```

So if you're using `duration`, this block is redundant. Hope that clears things up :)

**Comment by felquis** [comment]
You are right guys :/ I'm sorry.

I thought the delay means "Wait this time to hide the loading", for example, my request took just 200ms and I called `hide` on ajax complete, so... My loading message will disappear just after 500ms.. 

Would be great if this options was available, this is to avoid a very fast "Loading..." screen, to be more smooth.

Thanks.
