### ISSUE TITLE
`.hide-on-keyboard-open` isn't hiding item on iOS

### ISSUE THREAD

**Issue by sudodoki** [driftyco/ionic#2853]
Added `.hide-on-keyboard-open` to an element on a page. It works on iOS emulator & android device, but not on actual iOS 6+.

**Comment by Ionitron** [comment]
Greetings @sudodoki!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.
