### ISSUE TITLE
No way to disable `ion-tab`s

### ISSUE THREAD

**Issue by beckyconning** [driftyco/ionic#2855]
I've had a few client specs that involve disabling tabs depending on some condition. Examples include "is the customer signed in?" and "does the customer have a premium account?".

There doesn't seem to be a way to achieve this using classes as the way ionic passes the class attribute down to a tab doesn't allow the class to be changed after the tabs have been digested. Maybe I'm wrong but I couldn't work it out. If there is a way to achieve this I'd love to know otherwise this is a feature / improvement request. Thanks.

**Comment by drewrygh** [comment]
This seems like a good idea. AFAIK there isn't a (clean) way to do this. We added support for a `hidden` attribute a while back, and I'd imagine disabling a tab is more common than hiding it. I'll get back to this once I have time to go through your PR.

**Comment by beckyconning** [comment]
Thanks for the quick response! I think the main point of contention in the PR will be my use of the `disabled` property rather than a class called "disabled". I think its neater to use a [disabled] selector but I can see there might be issues with it.

Also I'm didn't include a [disabled] style that sets `pointer-events: none` etc yet as I wasn't sure how disabled tabs would look in Ionic given the different styles (positive, assertive etc). In the applications we built using this patch the client provided disabled styles for us and they were different in both.

**Comment by beckyconning** [comment]
@adam187 we're just using this feature branch branch as our ionic version for now.

In our bower.json

    "ionic": "https://github.com/beckyconning/ionic/tarball/feature-disableable-tabs",
