### ISSUE TITLE
bug: Unable to load facebook/twitter external scripts

### ISSUE THREAD

**Issue by divyenduz** [driftyco/ionic#2862]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a requirement where I have to push data into a list and process it accordingly. 
The data may be a facebook post/ twitter post/ youtube video or a URL.

So, using ng-if, I am supposed to embed facebook post if the data is a fb post, embed tweet in case the data is a tweet, embed a video if it is from youtube, handle URL click.

Here is a codepen of my implementation :- 
http://codepen.io/divyenduz/pen/YPpLVb

So, the problem I face are :- 

1. Facebook embed does not work
Followed instructions at - https://developers.facebook.com/docs/plugins/embedded-posts
Initialized SDK below body tag. Nothing shows up. (I have no idea why)

2. Twitter embed works on index
3. Youtube embed works on index (I am using a small script to lazy load)

Twitter/ youtube embeds are working on index.html as seen in codepen but if I use templates, they stop working.

Twitter/ youtube have a external script common in them, which seems to load when written in index but not in a template. I hope I am clear to explain the problem I face.

So, I think there is a problem with loading of external scripts in ionic lists when they are used in a tempate with state provider.

Please comment. Let me know if I can explain the problem better in any way.

Thanks 

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @divyenduz!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2862)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by divyenduz** [comment]
Could this be related to this issue ?

https://github.com/angular/angular.js/issues/2820

**Comment by divyenduz** [comment]
I think this is the solution. Loading jQuery in my app may solve this. Will try it out.
http://stackoverflow.com/questions/18220197/angularjs-does-not-load-scripts-within-ng-view

But is there a way without adding jQuery. And which version of jQuery plays well with ionic beta 14 ?
I am working on a app that has to go in production. So, looking for the best alternatives.

Thanks

**Comment by divyenduz** [comment]
Confirmed. This works when jQuery is included. But I need suggestions on the best way to do that. Is including jQuery the only way out ?

**Comment by divyenduz** [comment]
Anyone on this ? I don't want ionitron to come out and close this one for being old :(

**Comment by mhartington** [comment]
So as far as the embed objects not being able to be scrolled passed, you may way to try adding `data-tap-disabled="true"` to an element that is wrapping them.


As far as the script issue goes, there is a comment by an angular core member.

>I don't believe that we can support script elements within script elements without resorting to some special angular-specific escaping/unescaping (something I'm not interested in).

So simply put, if angular doesn't support this, there's not much we can do. 
Going to close this as the original answer isn't technically an ionic problem, but and angular one. 
If you are having issues with embed object and touch-events, please open a new issue.

**Comment by divyenduz** [comment]
I am unable to scroll when say a tweet is embedded. The data-tap-disabled="true" did not work as well.

**Comment by mhartington** [comment]
So that comes down to embeds being small iframes, which are essentially their own documents with their own events. You'll need to find a way to not use embeds

**Comment by divyenduz** [comment]
The only question I am left with is how this works in links like :- http://w3z.in/3b3 

If you open this in mobile browser, you can both scroll over the embed and interact with it.
