### ISSUE TITLE
bug: Render problem if go to other state in controller

### ISSUE THREAD

**Issue by sunshineo** [driftyco/ionic#2863]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The default state of my app have some UI components. The most heavy one is a slide box. At the end of the controller, I check if the user have viewed the tutorial. If they did not, I'll go to the tutorial state and use $history.goBack() after they finish the tutorial.
When I get back to the default state, the image in the slide box does not show up. My workaround is have a 0 seconds timeout before call $state.go . This results in the slide box on the default state properly rendered and then go to the tutorial.
setTimeout(function() {
        if(!window.localStorage.getItem('HelpViewed')) {
            $state.go('app.help');
        }
    }, 0);

I feel there is a bug there. Or maybe just the build I'm using.</span>

<span is-issue-template></span>

**Comment by drewrygh** [comment]
How are you setting the source of the image file? Does disabling caching in the view do anything? Are you able to put together a [codepen](http://codepen.io) so it's easier to diagnose?

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!
