### ISSUE TITLE
bug: TypeError: Cannot read property 'backButtonTextLeft' of null

### ISSUE THREAD

**Issue by matheusrocha89** [driftyco/ionic#2868]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi everyone,
After I remove the cache of a view using the attr cache-view="false" the console starts to show an error:
```
TypeError: Cannot read property 'backButtonTextLeft' of null
```
This happens when I add false to cache-view, then navigate to another view and click on back button, to come back to the view that I put the cache attr as false.

There is a little discussion on ionic forum after I opened a question [there](http://forum.ionicframework.com/t/removing-cache-of-a-view/14942)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @matheusrocha89!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2868)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by arkin-** [comment]
I am also having this issue as of the latest update (ionic@1.3.1). I am using the {cache: false} directive in my routes, and it is happening browsing around using Chrome, have not tested on a device yet.

**Comment by adaptivedev** [comment]
Me too.

**Comment by rept** [comment]
Got the same message.

Strange thing is, this is my flow: X => Y => Z

When I go from X => Y I'm not getting this.
When I go from X => Y => Z and then press back then I get this message on the Y view.

**Comment by Strutsagget** [comment]
Me too, also using cache: false in routes

**Comment by flinn** [comment]
Same, using "$ionicConfigProvider.views.maxCache(0);".

**Comment by rept** [comment]
Same here, also using "$ionicConfigProvider.views.maxCache(0);"

**Comment by adamdbradley** [comment]
I'm unable to replicate this problem. Would someone be able to put together a simple [codepen](http://codepen.io/ionic/public-list/) (using the nightly build) that throws this error? Thanks

**Comment by matheusrocha89** [comment]
Sure. I think I can @adamdbradley

**Comment by matheusrocha89** [comment]
@adamdbradley I try to simulate on codepen but not happening, I think it's because there I can't create different HTML file and my views are all using ng-template there. Do you think that I can record my screen with my app could help?

**Comment by matheusrocha89** [comment]
@adamdbradley I discover something interesting now. This just happen when the `ionic serve` "simulates" the iOS version of the app, when I use `ionic serve --lab` and try to simulate the error on Android view the error doesn't happens, but on iOS side happens.

**Comment by adamdbradley** [comment]
Yeah the back button text only updates with the previous page title for iOS. Actually the animation code for the nav bar and views use different method between iOS and Android. I'll do an update quick so it's checking for the existence of the previous header bar controller for iOS. Would you still be able to put together a simple codepen showing how it breaks? Thanks

**Comment by matheusrocha89** [comment]
@adamdbradley I tried to simulate the bug on codepen but didn't work so I created a video showing the error happening. http://monosnap.com/file/rrEb1gfdPf8jXEm9uPY8B7VN1Qll1q

**Comment by adamdbradley** [comment]
Cool thanks for the video. If you pull down the nightly build do you still see the error? Thanks

**Comment by matheusrocha89** [comment]
I will try and tell you. I will update to the nightly

**Comment by matheusrocha89** [comment]
No, on nightly the error didn't happen :+1: Thank @adamdbradley :smile:

**Comment by Strutsagget** [comment]
Can confirm its fixed in nightly. :+1:

**Comment by adamdbradley** [comment]
woot! thanks for the help!
