### ISSUE TITLE
Add pull to refresh support for native scrolling

### ISSUE THREAD

**Issue by hollingberry** [driftyco/ionic#287]
I like your native scrollview, but wouldn't it be cool if pull to refresh could work either way? Look at https://github.com/dantipa/pull-to-refresh-js for reference.

**Comment by seb0zz** [comment]
Is there any way to use `ion-refresher` and `overflow-scroll` together now?

**Comment by ansgarm** [comment]
+1

**Comment by ceichinger** [comment]
+1

**Comment by kyocn** [comment]
+1

**Comment by 5amfung** [comment]
+1

**Comment by iralution** [comment]
+ 1

**Comment by lorenzyannick** [comment]
+1

**Comment by mhartington** [comment]
+1's will not make this possible. iOS does not provide the proper scroll events needed for these to work. Android 4.4+ does, so we can enable it there. But for having them work on iOS, it's not going to be possible.

**Comment by boban984** [comment]
-1

**Comment by andreialecu** [comment]
@mhartington I'm successfully using Ionic with the (WKWebView plugin)[https://github.com/Telerik-Verified-Plugins/WKWebView], which supports continuous scroll events, and even reports negative values when over-scrolling, so this is definitely possible with native scroll.

Open this JSBin in Safari on a newer iOS and you will see that the top div updates with the scroll position in real time. http://jsbin.com/wiveyapaha

So, +1.
