### ISSUE TITLE
bug: Cannot move cursor into middle of contenteditable

### ISSUE THREAD

**Issue by CatoTH** [driftyco/ionic#2870]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you have a 
```html
<div contenteditable="true"></div>
```
 and enter some text, it is not possible to move the text cursor somewhere into the middle of the text using mouse clicks or tap gestures, only to the very beginning or end of the text.

This can be seen here:
http://codepen.io/anon/pen/vEyrqe

It seems to work if you replace the condition "ele.contentEditable === 'true'" in js/utils/tap.js (line 164 in the current master) by "ele.isContentEditable".</span>

<span is-issue-template></span>

**Comment by morungos** [comment]
I've just run into this one, and the resolution does appear to make it better for me.

**Comment by jgw96** [comment]
Hello! Are you guys still experiencing this issue with the latest version of ionic?

**Comment by morungos** [comment]
I've not tested it for a very long time. Sorry.

**Comment by jgw96** [comment]
@morungos No problem! Thanks for using Ionic! This looks like something i will look into on our end. I will be closing this issue for now, but feel free to continue the conversation!

**Comment by sanmaozhao** [comment]
I tested on this: http://codepen.io/anon/pen/vEyrqe
There are still problems

**Comment by jiazhengshi** [comment]
https://github.com/driftyco/ionic/blob/aef490b177406f9bd7d532294abd6c3198357622/js/utils/tap.js#L164

 chaning ele.contentEditable === 'true'  to  ele.isContentEditable works

**Comment by emolinaglobant** [comment]
This bug still alive

**Comment by johannds** [comment]
Still happening.
