### ISSUE TITLE
usability improvement/suggestion: prevent naming projects "."

### ISSUE THREAD

**Issue by dts** [driftyco/ionic#2871]
I created an ionic project with `ionic start .` meaning: start an ionic project in the current (already created) directory.  Figuring I'd name the thing later, I didn't specify the command-line flag for setting the name.  Ionic used '.' as the name for everything, which caused a hard-to-debug mayhem of error messages from within Cordova.  Easy to fix, but also easy to just prevent in the ionic-start code.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#246
