### ISSUE TITLE
bug: Popover doesn't show properly when used with collection-repeat in beta 14

### ISSUE THREAD

**Issue by rajatrocks** [driftyco/ionic#2872]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Popovers from list items no longer work in beta-14 when using collection-repeat. They worked fine in beta-13. 

Codepen with ng-repeat (this works): http://codepen.io/rajatrocks/pen/gbLBPg

Codepen with collection-repeat: http://codepen.io/rajatrocks/pen/ogYaZj - in this case, the popover either shows up somewhere random, or immediately disappears (possibly being redrawn off screen somewhere).</span>

<span is-issue-template></span>

**Comment by drewrygh** [comment]
Thanks, someone else actually just reported this as well. Moving this to #2865

**Comment by rajatrocks** [comment]
@drewrygh I think they're separate issues, no? This is about opening a popover from a collection-repeated list item, and that other one is about if you open a modal from a detail view, the main view loses its scroll position.

**Comment by pulakb** [comment]
Very helpful info @rajatrocks
