### ISSUE TITLE
Screen stretch's when dismissing keyboard by tapping out side 

### ISSUE THREAD

**Issue by chetan-techjini** [driftyco/ionic#2874]
I have multiple screens which require text inputs from keyboard

When dismissing the keyboard by tapping outside the keyboard area .

THE WHOLE SCREEN ELEMENTS STRETCH'S VERTICALLY

PLS HELP !!!!!!!
![img_0882](https://cloud.githubusercontent.com/assets/8719668/5622637/84e06bce-956c-11e4-9810-f7b37f9a9419.PNG)
![img_0883](https://cloud.githubusercontent.com/assets/8719668/5622639/8cbdbe96-956c-11e4-909d-d362cd834750.PNG)
![img_0880](https://cloud.githubusercontent.com/assets/8719668/5622642/949d9460-956c-11e4-961c-c330538e5782.PNG)

**Comment by chetan-techjini** [comment]
I just removed the ionic keyboard plugin and everything works fine !!

**Comment by drewrygh** [comment]
What version of iOS is this happening on? Also, is this using ionic beta-14 and the latest cli, or some other version?

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by alessiovalentini** [comment]
Issue is still happening to me on iOS 7.0.4. Not happening instead on iOS8+.

After trying different solutions (all not working) I have found out that the issue arises only when my input (text) is embedded within an <ion-content> block.
