### ISSUE TITLE
bug: Collection-Repeat with Caching and Modals causes app to crash in beta 14

### ISSUE THREAD

**Issue by rajatrocks** [driftyco/ionic#2879]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
- Home tab has a collection-repeat list in it. Each element has a picture. 
- A second tab has a button to open a modal.  
- When the modal is shown, it calls ionic.trigger('resize'); *(line 2955 of ionic-angular.js)*
- The collection-repeat on the home tab (which is cached as of b14) listens to this, calls collectionRepeatManager.resize() which then renders **all the non-showing elements** in the list. If there are pictures, **all the pictures are loaded**. And when run on device, the app likely crashes with an out of memory error.
- Turning off cache for the Home tab eliminates the problem.
- Removing collection-repeat eliminates the problem. 
- Commenting out the call to ionic.trigger('resize') eliminates the problem (for me). 

Codepen here: http://codepen.io/rajatrocks/pen/myOYLw

Discussion here: http://forum.ionicframework.com/t/collection-repeat-and-view-cache-weirdness/14651

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @rajatrocks!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2879)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by felquis** [comment]
Probably related to #2890

**Comment by miklernout** [comment]
+1

**Comment by ajoslin** [comment]
Fixed via bb866da3d7e539c8923bd6914c0a4e44f0f4d400

**Comment by ajoslin** [comment]
In short, the modal sends a resize event. 

The old collection repeat would recalculate everything on the resize event.

The new collection repeat only recalculates on resize if the collection repeat is in view, and also doesn't recalculate everything anymore. It only recalculates what *has* to be recalculated on resize - up to the current scroll value.

**Comment by ajoslin** [comment]
Or in the case of your codepen, nothing needs to be recalculated anymore since it uses static item heights...

**Comment by ajoslin** [comment]
Latest nightly, you don't need item-height and item-width attributes anymore: http://codepen.io/anon/pen/GgdYWp

If you don't supply width/height, it will getComputedStyle() of the first element and use that for the width/height of every element.
