### ISSUE TITLE
bug: wrong width of title in <ion-header-bar>

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic#2881]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I just found a bug on `<ion-header-bar>` migrating from the beta13 to beta14 :(

The width of title is calculated from the number of characters in buttons but it's hardly wrong when it's an angular expression...
See this codepen for practical exemple : http://codepen.io/anon/pen/OPbKxy

The workaround I found is to set angular expression via `ng-bind` instead of `{{ }}`</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @loicknuchel!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2881)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by drewrygh** [comment]
Confirmed. Interesting find, thanks for bringing it to our attention.

**Comment by javiercr** [comment]
We're having the same issue when using translated titles with angular-translate. Is there any workaround for it?

**Comment by JWGmeligMeyling** [comment]
Can confirm.

**Comment by loicknuchel** [comment]
Hi @javiercr, I proposed a workaround in my first post : using ng-bind instead of {{}}

**Comment by javiercr** [comment]
@loicknuchel ops! Sorry didn't see that before, I'll give it a try. Thanks!

**Comment by JWGmeligMeyling** [comment]
I've seen this issue with `translate="key"` as well.

**Comment by javiercr** [comment]
I've replaced:

     <h1 class="title">{{ 'my_translation_key' | translate}}</h1>

with 

    <h1 class="title" ng-bind="'my_translation_key' | translate"></h1>

But I have the same problem, in other words, the ng-bind workaround doesn't work for me :/

**Comment by javiercr** [comment]
Ops, I just noticed that the ng-bind workaround should be applied to the button, not to the title. It's now working for me like this:

    <h1 class="title" ng-bind="'translated_title_key' | translate"></h1>
    <button class="button button-clear" ng-bind="'translated_button_key' | translate"></button>

**Comment by jtomaszewski** [comment]
For me, following workaround seems to fix it:

```coffee
app.controller "YourCtrl", ($scope, $timeout, $ionicNavBarDelegate) ->
  $scope.$on '$ionicView.afterEnter', ->
    # force recalculation of navbar title width
    $timeout ->
      $ionicNavBarDelegate.align("left") # or center/right depending what u use
```

**Comment by Fayozjon** [comment]
Jacek

http://izmirpirlanta.com/etoro-front

24.03.2015, 14:51, "Jacek Tomaszewski" <notifications@github.com>:For me, following workaround seems to fix it:

app.controller "YourCtrl", ($scope, $timeout, $ionicNavBarDelegate) ->
  $scope.$on '$ionicView.afterEnter', ->
    # force recalculation of navbar title width
    $timeout ->
      $ionicNavBarDelegate.align("left") # or center/right depending what u use

**Comment by mhartington** [comment]
So yeah, there's not much we can do were. How angular's internals work, the variable name will actually render for a split second, causing the misalignment. Using ngBind will resolve this issue. 

Closing this as it is not an issue with ionic, but angular-core.
