### ISSUE TITLE
bug: ng-click handlers called twice on IE

### ISSUE THREAD

**Issue by vjrantal** [driftyco/ionic#2885]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>windows</span>  

<span ionic-description>To reproduce the duplicate handlers on Internet Explorer, open http://codepen.io/vjrantal/pen/GgNdVj with IE11 and click the show/alert/confirm buttons. The actual (problematic) behavior is that the popups gets triggered twice, while the expected behavior is that they get triggered once.

The same actual behavior can be reproduced on desktop IE11 and the IE mobile on Windows Phone 8.1. Tip: If you don't have Windows and IE installed, you can use https://remote.modern.ie to test on OS X, iOS or Android.

The code in the the codepen logs the events the handlers get an you see something like this in the IE F12 developer tools console:

```
[object MouseEvent]
[object PointerEvent]
```

</span>

<span is-issue-template></span>

**Comment by vjrantal** [comment]
For debugging purposes - the issue seems to go away if you add this piece of JavaScript to the codepen at http://codepen.io/vjrantal/pen/GgNdVj :

```
window.addEventListener('click', function(event) {
  if (Object.prototype.toString.call(event) == '[object PointerEvent]') {
    event.stopPropagation();
  }
}
, true);
```

**Comment by gfort** [comment]
As I think stopping the propagation of the PointerEvent might create unexpected behaviors, one alternative solution is to replace the tag <button> by <a> with the class 'button'.

**Comment by corebonts** [comment]
My solution is to overwrite the ng-click handling and simply drop the second event:

```javascript
ionic.Platform.isIE = function() {
  return ionic.Platform.ua.toLowerCase().indexOf('trident') > -1;
}

if (ionic.Platform.isIE()) {
  angular.module('ionic')
    .factory('$ionicNgClick', ['$parse', '$timeout', function($parse, $timeout) {
      return function(scope, element, clickExpr) {
        var clickHandler = angular.isFunction(clickExpr) ? clickExpr : $parse(clickExpr);

        element.on('click', function(event) {
          scope.$apply(function() {
            if (scope.clicktimer) return; // Second call
            clickHandler(scope, {$event: (event) });
            scope.clicktimer = $timeout(function() { delete scope.clicktimer; }, 1, false);
          });
        });

        // Hack for iOS Safari's benefit. It goes searching for onclick handlers and is liable to click
        // something else nearby.
        element.onclick = function(event) {};
      };
    }]);
}
```
The magic is around the `clicktimer` part.

**Comment by vjrantal** [comment]
Tested that this bug is not reproducible on the very latest browser included in the Windows 10 technical preview when experimental features are enabled. More about the release and how to enable those features can be found at http://blogs.msdn.com/b/ie/archive/2015/03/18/rendering-engine-updates-in-march-for-the-windows-10-technical-preview.aspx.

**Comment by perrygovier** [comment]
Thanks for the leg work on this @vjrantal. I'd like to fix this immediately after the 1.0, but since `tap.js` can be such a can of obscure-device-specific-worms, I'd like to wait until then before rocking the boat.

**Comment by vjrantal** [comment]
Thanks for the update.

I was actually recently looking into http://patrickhlauke.github.io/touch/tests/results/, which shows that there is some amount of variation in the exact behavior even between different versions of the same browser.

One challenge is that regressions might not be easy to catch with unit tests (because a true finger tap might result into different events than a JavaScript-triggered click). However, Ionic seems to have a fairly comprehensive manual test list at https://github.com/driftyco/ionic/blob/master/test/unit/utils/tap.unit.js which should be helpful when testing.

Using an external library to achieve a reasonable tap behavior might be one option.

**Comment by perrygovier** [comment]
It's a tricky area. We started with FastClick and implemented most of Hammer.js which are great, but both had issues we had to fix to the point they don't really resemble their original form. We'll reevaluate for v2, but for v1, there just isn't/wasn't anything as comprehensive. A particular problem is form elements and preventing ghost clicks when an element animates to a new position when clicked. That combined with a myriad of different behavior, between devices, manufacturers, and OSes... it gets ugly. We're not aware of anyone who's solved it better than tap.js, but we'd gladly adopt any open source project that has.

**Comment by zmLGBBM** [comment]
Same problem here, no matter if you're running IE11 on your desktop or on your phone.
An <a...> instead of <button...> works just fine.
They have the almost same call tree, so that's very tricky.

**Comment by nwcnwc** [comment]
@corebonts thanks, that fix works for now--for ng-click. ng-submit is still firing twice--though I'm sure if I understood what your workaround was doing I could write a similar one for ng-submit.

**Comment by hallbox** [comment]
Thanks @corebonts!  Hopefully the Ionic Team can learn from your fix in future versions.

**Comment by tomchiverton** [comment]
Also effects <select> elements which need two taps on the pop'd up list to remove the options :

```
    <select ng-model="a" name="c">
        <option value=""></option>
        <option ng-repeat="a in b">{{a}}</option>
    </select>
```

Can any one confirm ?

**Comment by iver56** [comment]
@tomchiverton Yes, I have noticed that too. On Windows Phone 8.1.

**Comment by tomchiverton** [comment]
Another ack here: http://www.intertech.com/Blog/windows-phone-ionic-cordova-select-element-issue/ which includes a work around.

**Comment by gregor-srdic** [comment]
thank you @corebonts, your solution seems to work for me!

**Comment by mhartington** [comment]
We will not be supporting WP8 with ionic v1.

**Comment by TomMettam** [comment]
I encountered this issue and implemented a fix here: https://github.com/driftyco/ionic/pull/4638

**Comment by gpascual2** [comment]
Thanks Tom! that did it on my app for 'windowsphone' platform. However the issue is still there for windows 10 universal apps. It worked well if the fix is applied not only to 'windowsphone' platform but to 'win64' too.  

This is my dirty test code: 
```
requiresNativeClick: function(ele) {
	var platform = ionic.Platform.platform();
	if ((platform == 'windowsphone' || platform == 'win64') && (ele.tagName == 'A' || ele.tagName == 'BUTTON' || ele.hasAttribute('ng-click') || (ele.tagName == 'INPUT' && (ele.type == 'button' || ele.type == 'submit')))) {
      return true; //Windows Phone edge case, prevent ng-click (and similar) events from firing twice on this platform
    }
    if (!ele || ele.disabled || (/^(file|range)$/i).test(ele.type) || (/^(object|video)$/i).test(ele.tagName) || ionic.tap.isLabelContainingFileInput(ele)) {
      return true;
    }
    return ionic.tap.isElementTapDisabled(ele);
  },
```

**Comment by jdnichollsc** [comment]
The issue exist in Ionic 1.2. I hate you IE11!

**Comment by mistic100** [comment]
I confirm that the bug append in IE11.
Replacing `<button>` by `<a class="button">` works but would be better to handle it in the lib.

**Comment by tobbbe** [comment]
Yep, issue still exist in 1.2.1 (#4638 doesnt seem to fix it)

thank you @mistic100 that worked!

**Comment by healyje** [comment]
Glad to see the button / class=button workaround. In desperation I had finally written a locking service around a $rootScope.lock with a .getLock() and .releaseLock() - overkill I know, but it worked.

**Comment by maksad** [comment]
Try to add `type="button"` to the button element. As @cverb pointed [in this SO issue](http://stackoverflow.com/questions/32090543/scopes-method-called-via-ng-click-executed-twice-by-ie)  the default behaviour is submit and apparently that messes with the code.

**Comment by jdnichollsc** [comment]
I'm using the solution of @corebonts, thanks man! :dancers:
