### ISSUE TITLE
bug:  $ionicSlideBoxDelegate.slide not working on a cached View

### ISSUE THREAD

**Issue by ronyrun** [driftyco/ionic#2886]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://forum.ionicframework.com/t/ionicslideboxdelegate-slide-not-working-on-a-cached-view/15093/2

I implemented a timeout around the $ionicSlideBoxDelegate.

    $timeout(function() {
        if(!$scope.slideIndex){
            $scope.slideIndex = 0;
        }
        console.info("$ionicSlideBoxDelegate", $scope, $ionicSlideBoxDelegate);
        $ionicSlideBoxDelegate.$getByHandle('slideRelations').update();
        $ionicSlideBoxDelegate.$getByHandle('slideRelations').slide($scope.slideIndex);
    }, 100);
And within a cached view I still have this error :

Delegate for handle "slideRelations" could not find a corresponding element with delegate-handle="slideRelations"! update() was not called!
Possible cause: If you are calling update() immediately, and your element with delegate-handle="slideRelations" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to update() and try again.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @ronyrun!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2886)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by drewrygh** [comment]
Any chance you could put together a codepen that contains the relevant parts of your code? I tried duplicating this with the slidebox in our [app intro demo](http://codepen.io/ionic/pen/AjgEB) by adding the service calls to the top of the controller, but the timeout fixes it for me.

**Comment by Ionitron** [comment]
Greetings!

My sensors indicate a reply was requested, however, since we have not received one yet, this will be closed. If you are still experiencing this issue, please feel free to reopen it and include any information that may have been requested.

Thank you!

**Comment by nauyz** [comment]
I have 3 tabs: A, B, C, tab A has a slide-box
when I click A, then click B, then click A, all show ok, 
but when I click tab A, then double click B, and return to click tab A, the slide-box in tab A shows with bug.
