### ISSUE TITLE
docs: Ionicon page outdated

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#2887]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm developing an app with Ionic beta-14 so I realized that a lot of icons were missing but not all of then. 
I look at ionic.css and realized that a lot of things changed, like `IOS` icons now are called `IOS7` and in other cases some icons were removed like `ion-more-vertical`. I would to know if theres a documentation for the new referrences.
The ionicons page still in the air so this could confuse some folks, even more because the link of the page is on ionic css official documentation.

Thats the page that I'm talking about:
http://ionicons.com/</span>

<span is-issue-template></span>

**Comment by divyenduz** [comment]
I think it is not out dated. It is ahead of time. It is at version 2 but IonicFramework beta 14 uses a older version of ionicons, I think 1.5

That is the case.

**Comment by ag-secret** [comment]
ok but my point is.. everybody that is developing right now with beta 14, where they  will consult the names of the icons that beta 14 is using?

**Comment by divyenduz** [comment]
Well, that is my question too :dart:

**Comment by dbaq** [comment]
You have a link at the bottom of the page.

http://ionicons.com/1.5.2/

**Comment by Ionitron** [comment]
Beta 14 uses ionicons 1.5.2 (http://ionicons.com/1.5.2/). 

The next release will use Ionicons v2.0
