### ISSUE TITLE
bug: $ionicModal causing scroll up in the previous view

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2890]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Codepen - http://codepen.io/felquis/pen/wBobPp

### How to reproduce

1. Open the codepen
1. Scroll to the item 12
1. Click in the item 12
1. Click in "Open Modal"
1. Click in "Hide Modal"
1.[here is the problem] Go to the previous view "with the back button"
1. The previous scroll is lost, should keep in the item 12

Hope it helps improve Ionic.</span>

<span is-issue-template></span>

**Comment by pulakb** [comment]
I think this issue is similar to the following:

bug: Scroll is lost with collection-repeat #2865

**Comment by tariq7** [comment]
+1

**Comment by felquis** [comment]
Guys, this issues isn't happening after the changes to fix the issue `2935`, I'm pretty sure this was happening because that resize trigger when the modal calls `show()`.

**Comment by mica16** [comment]
Is possible to know what was the fix exactly ? 

Thanks

**Comment by bogdanciocoiu** [comment]
+1

**Comment by eggli** [comment]
This issue is still happening, checked the 1.1.1 release bundle, the fix is not in the bundle.
