### ISSUE TITLE
bug: Focus on input field and overflow-scroll=true windows automatically scrolls to top

### ISSUE THREAD

**Issue by 3x14159265** [driftyco/ionic#2897]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using overflow-scroll=true in an ionic list on android (since the performance of ionic scrolling is terrible on android). Each list item has an input field. When the input field is focused, the window automatically scrolls to the top of the window. IMHO, that shouldn't be the way it should work.

I found the corresponding lines in the ionic.bundle.js (line 3347-3358):

<code>
function keyboardBrowserFocusIn(e) {
  if( !e.target || !ionic.tap.isTextInput(e.target) || ionic.tap.isDateInput(e.target) || !keyboardIsWithinScroll(e.target) ) return;

  document.addEventListener('keydown', keyboardOnKeyDown, false);

  document.body.scrollTop = 0;
  document.body.querySelector('.scroll-content').scrollTop = 0;

  keyboardActiveElement = e.target;

  keyboardSetShow(e);
}
</code>

so, if I got it right, when opening the Keyboard, the window (body) scrolls to top and then the ionic scrolling scrolls to the input field position. when using overflow-scroll=true, it only scrolls to top.
nevertheless, it should never scroll to top when opening the keyboard, since even with ionic scrolling you see the flickering of scrolling to top and then down to the input field again.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @3x14159265!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2897)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @3x14159265!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by graceaffinity** [comment]
This still seems to be an issue. 

We are on 1.0.0 and if we $ionicConfigProvider.scrolling.jsScrolling(false) all forms break on field focus. 

The page scrolls to the top and can't scroll back to the field.

If we re-enable jsScrolling, forms work as expected.

That's our fix for now, but would love to be able to disable jsScrolling and not break forms.

**Comment by peteorpeter** [comment]
Experiencing the same issue and agree this issue should be re-opened!  It's possible this behavior works fine in some percentage of situations but in the case of a form taller than the screen height it feels quite broken.

**Comment by Sjerd** [comment]
Yes this still is an issue. anyone found a fix?

**Comment by natezerk** [comment]
+1 to having this issue.

**Comment by vasumahesh1** [comment]
+1 from my side

**Comment by krik** [comment]
+1 seeing this too

**Comment by vasumahesh1** [comment]
https://github.com/driftyco/ionic/issues/3727

This issue relates to the problem

**Comment by grantgumina** [comment]
+ 1 also experiencing this issue

**Comment by josephmeiring** [comment]
ditto. Is there a fix?

**Comment by vasumahesh1** [comment]
The fix should be in Ionic 1.0.1 no?

**Comment by ekscrypto** [comment]
May or may not be related, but if a form is long enough that you can scroll until the focused field is no longer visible on the screen, the scroll view positioning is automatically reset but the scrolling will no longer show the proper range.  By that, I mean that de-activating the field so the keyboard no longer shows and then attempting to scroll back to the top of the form will no longer scroll to the top.  The only way to get the scrolling to work again is to scroll to the very bottom of the scroll view with the keyboard out, then deactivate the keyboard again.

**Comment by CasanovaGregory** [comment]
+1 Still have the issue.

**Comment by infect2** [comment]
+1 Still occurs

**Comment by numerized** [comment]
Hi there, this problem still occurs yes. I've not yet upgraded to 1.1.0
Thanks

**Comment by barkoczi** [comment]
it is exists in 1.1.0

**Comment by Samaalir** [comment]
+1 Still.
