### ISSUE TITLE
$viewContentLoaded not fired by ion-nav-view

### ISSUE THREAD

**Issue by wesleycho** [driftyco/ionic#2906]
I noticed that this event is fired by ng-view and ui-view by the ngRoute and ui-router projects whenever the content is loaded, but Ionic does not fire $viewContentLoaded.

**Comment by danicomas** [comment]
Don't use $viewContentLoaded in beta 14. The life cycle has changed. Look at this: http://ionicframework.com/blog/navigating-the-changes/ (View LifeCycle)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
