### ISSUE TITLE
bug: View header is not showing the right way

### ISSUE THREAD

**Issue by albertolo** [driftyco/ionic#2907]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The right side icons in the header are not showing in the way they are suppose, they work right in ios and the web. 

this is the code. 
```
<ion-view view-title="Playlists">
  <ion-nav-buttons side="left">
    <button class="button button-icon ion-home"></button>
  </ion-nav-buttons>

  <ion-nav-title>
  	<img src="http://placehold.it/200x44">
  </ion-nav-title>

  <ion-nav-buttons side="right">
    <button class="button button-icon ion-home"></button>
    <button class="button button-icon ion-home"></button>
  </ion-nav-buttons>
  <ion-content class="padding">
    <ion-list>
      <ion-item ng-repeat="playlist in playlists" href="#/app/playlists/{{playlist.id}}">
        {{playlist.title}}
      </ion-item>
    </ion-list>
  </ion-content>
</ion-view>
```
</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you try the nightly builds? I pushed a fix recently that should take care of this. 

https://github.com/driftyco/ionic/commit/eef1d32b04f341896d57a1cba319067b25614680

Give that a try and let me know if it works

**Comment by albertolo** [comment]
Hi Mike, 

It Worked, 
Thank you !
