### ISSUE TITLE
bug: An error occurred while running subprocess npm. ( npm i exited with exit code 1 ).

### ISSUE THREAD

**Issue by edocbuhtig** [driftyco/ionic#29108]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Cannot create a new ionic v7.x blank angular standalone  starter app with CLI 7.2.0

### Expected Behavior

Should be able to create a blank starter app using ionic cli, after upgrading ionic CLI 7.2.0

### Steps to Reproduce

1.$ionic start
2. Framework: Angular
3. ? Starter template: blank
4.  Standalone
5. Downloading and extracting blank starter in 638.11ms
6. > npm i --save -E @capacitor/core@latest
7. npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 2.0.1)   : 1.7.2

System:

   NodeJS : v20.11.1
   npm    : 10.2.4
   OS     : macOS Monterey

**Comment by mapsandapps** [comment]
Hi, I've created a new starter app just now using Ionic CLI 7.2.0, and I'm not experiencing any problems. I'm thinking there might have been a temporary outage somewhere preventing you from installing packages. Could you please try again and let me know if you're still unable to create a starter app?

**Comment by edocbuhtig** [comment]
@mapsandapps I am still experiencing the same error


[ERROR] An error occurred while running subprocess npm.
        
        npm i exited with exit code 1.
        
``

**Comment by mapsandapps** [comment]
I'm glad you found a workaround. I'm going to close this as this connection/response error issue is not related to Ionic Framework.
