### ISSUE TITLE
bug: ion-content has 1px padding-bottom in tab view

### ISSUE THREAD

**Issue by jasperkuperus** [driftyco/ionic#2910]
**Type**: bug
**Platform**: all
**JSFiddle**: http://jsfiddle.net/jasperkuperus/yk62zsxv/1/

If you work with a tab view, the `ion-content` seems to have *1px* padding too much on the bottom. Scroll all the way down in my JSFiddle and you will see 1 pixel line that is red (which is `ion-content`). The screenshot below also shows it:

![screen shot 2015-01-10 at 17 31 44](https://cloud.githubusercontent.com/assets/1655683/5692286/220390b8-98ef-11e4-8eda-92eefc6781b2.png)

I hunted this issue down to two lines of code in `_scaffolding.scss`, lines 65-69 in beta 14:

```
  // Hide the top border if any
  margin-top: -1px;

  // Prevents any distortion of lines
  padding-top:1px;
```

Removing both of these lines solves my issue. However, the comments suggest there is a very good reason for having these lines in place (which does not show in my specific scenario). This withholds me from simply removing the lines and submitting a pull request. Could someone please elaborate on this?

**Comment by gaguirre** [comment]
Same issue. I think the best way to fix it is adding `margin-bottom: -1px;`
I'll send a pull-request
