### ISSUE TITLE
feat: Tweaks to ion-option-buttons

### ISSUE THREAD

**Issue by xAlien95** [driftyco/ionic#2914]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I don't know if this feature request will be considered but here's the description:

the current [ion-option-button](http://ionicframework.com/docs/api/directive/ionOptionButton/) (Ionic1.0.0-beta.14) look like the iOS ones, but don't completely fit their behaviour:

- if you slide to the left a ion-item, then you'll be allowed to scroll ion-content or ion-scroll up and down when you're still sliding the item to reveal the options, while on iOS it's not allowed: if you slide to reveal the option, then you'll be only able to swipe the item on left-right directions, without scrolling the content at the same time;
- at the moment, ion-option-buttons are being closed only if you swipe left another ion-item. On iOS they are being closed if you tap everywhere on the content or if you change state.

Thanks for reading.</span>

<span is-issue-template></span>

**Comment by scferg** [comment]
+1
It would be nice to have the option to only allow x-axis movement when swiping for the option buttons. Being able to scroll the content around vertically while trying to access option buttons seems a bit frantic.

**Comment by Ionitron** [comment]
This has been fixed in the nightly builds
