### ISSUE TITLE
feat: Safe way to select the current ion-view element

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2920]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When you use `document.querySelectorAll('span');` it will select all elements from all `ion-view`, the only way to detect the current view, is to use the `nav-view="active"` attribute. 

```js
var currentView = document.querySelector('ion-view[nav-view="active"]');

currentView.querySelectorAll('span'); // Spans tags from the current view only

```

Shouldn't [$ionicHistory.currentView()](http://ionicframework.com/docs/nightly/api/service/$ionicHistory/) give us the current view element? Or something similar.

Is `ion-view[nav-view="active"]` the only way to get the current view?

I'm afraid I'll use `nav-view` attribute and in the future you change the values, attribute name or something else.

Another thing is that sometimes, there's the same element twice in the DOM, the same ion-view, but one is the current, the other isn't the current view, for example, if you open this codepen http://s.codepen.io/felquis/debug/ZYGdYM it'll open with the `home`, run `document.querySelectorAll('ion-view[nav-view="active"]')`, it'll log one element. But now navigate to the `about` tab, now if you run `document.querySelectorAll('ion-view[nav-view="active"]')` there's two elements.

I think would be great a method that really bring me the current ion-view in the screen, to avoid this confusion to select the current view to do something with this.

Thanks, (this was first posted in the forum http://forum.ionicframework.com/t/safe-way-to-select-the-current-ion-view-element/14035)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @felquis!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.

**Comment by jason-engage** [comment]
I'm having the same issue. I need to target different 'map' elements in different views, and its not so straightforward.

**Comment by lprichar** [comment]
@jason-engage Are you sure you need jQuery? Can't you just use something like document.querySelector('ion-view[nav-view=active] .map');

**Comment by jason-engage** [comment]
@lprichar - I can't quite remember what the issue was... it's been awhile. I think the .children and .find were the important bits, and the fact that I had more than one map element because of some cached views. I'm guessing the targetting could also be done with angular's jquery lite or perhaps vanilla javascript.

**Comment by Moai-** [comment]
Just dropping by to report that I had this exact issue. I needed to set the `scrollTop` property of an element, and I couldn't select it -- even with @lprichar 's code (there were somehow multiple active nav views). I bypassed my issue by making a little directive to directly set the element's attribute through Angular:

    angular.module('eps.states').directive('scrollTop', function(){
      return {
        restrict: "A",
        scope: {
          scrollTop: "="
        }, 
        link: function($scope, $element){
          $scope.$watch('scrollTop', function(newVal, oldVal){
            if( newVal === oldVal ) return;
            $element[0].scrollTop = newVal;
          })
        }
      }
    });

Then on the element...

`<div scroll-top="myScroll"> ... </div>`

...and the controller code:

`$scope.myScroll = 50;`

Hope this helps whomever has this problem!
