### ISSUE TITLE
bug: bug: nav-bar leaves empty space on android

### ISSUE THREAD

**Issue by filipesilva** [driftyco/ionic#2921]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>When removing the nav-bar on android, it leaves behind it's empty space. On iOS this does not happen. There's more information in this topic of the forums:
http://forum.ionicframework.com/t/trouble-hiding-nav-bar/15552</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @filipesilva!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2921)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by christophermiles** [comment]
Also having this issue using the Ionic tabs starter.

**Comment by andiCR** [comment]
Any update on this?

**Comment by filipesilva** [comment]
I tried on the RC0 and it was still there.

**Comment by Aligato** [comment]
Got the same bug here, any plan on when it could be fixed ?

**Comment by sebesvn** [comment]
Same issue here.

**Comment by jgordor** [comment]
Bug also in android 5.0.2

**Comment by agupta1989** [comment]
Any update on this issue ? any workaround or fixes on the way ?

**Comment by mhartington** [comment]
Is this still an issue?

**Comment by filipesilva** [comment]
Yes, it's still happening. 

I updated ionic, started a new project via `ionic start myApp tabs`, served it via `ionic serve --lab`:
![image](https://cloud.githubusercontent.com/assets/4172079/8694144/a8b125a4-2ad4-11e5-8e3a-9350c2088779.png)

Then I deleted the nav bar code
![image](https://cloud.githubusercontent.com/assets/4172079/8694167/d718f35e-2ad4-11e5-9bdb-558d385ad860.png)

And got the empty space
![image](https://cloud.githubusercontent.com/assets/4172079/8694173/e61ec388-2ad4-11e5-9f8a-ecd248a82287.png)

I then restored the nav bar code, but added `hide-nav-bar="true"` to the `ion-view`
![image](https://cloud.githubusercontent.com/assets/4172079/8694203/29b4a3ce-2ad5-11e5-97e1-40569fece84d.png)

Got the same thing
![image](https://cloud.githubusercontent.com/assets/4172079/8694218/4253b0c8-2ad5-11e5-8a3f-022ff5beb244.png)

**Comment by mhartington** [comment]
Okay, for the deleted nav-bar, not sure if this will be something we will want to fix. 
For the hide-nav-bar, this we can fix.

I just pushed it to our 1.0.2 branch. https://github.com/driftyco/ionic/commit/7e4fb159d3a1119424762000f5b22509abd58720

Until it is released, I suggest you take that code and just throw it in your sass file.

**Comment by filipesilva** [comment]
Works for me. Thanks!

**Comment by agupta1989** [comment]
Great ! Thank You :)

**Comment by FuzzyTree** [comment]
I'm using Ionic 1.1 and my `_tabs.scss` file contains the changes from https://github.com/driftyco/ionic/commit/7e4fb159d3a1119424762000f5b22509abd58720; however, when I create a starter project with tabs and remove the `ion-nav-bar` tag, the space that  the tag occupied still remains. This happens on both Android (5.1.1) and the browser view:

![no_space](https://cloud.githubusercontent.com/assets/6363454/9723385/9c1d193e-5585-11e5-926b-7cd54f03a64c.png)

![space](https://cloud.githubusercontent.com/assets/6363454/9723387/add3d64a-5585-11e5-8cd3-1a2a316ee08a.png)

I've added class `tab-tops` to my `ion-tabs` tag but the issue still persists

`<ion-tabs class="tabs-top tabs-color-assertive tabs-striped">`

<pre>
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.04 
Node Version: v0.12.7
</pre>

**Comment by mhartington** [comment]
Hmm, in this case, I'm not sure what we can do. 
Since the nav-bar isn't really in the DOM, there isn't anything we can really go off of from here.

We would have to write a directive to see if there is a nav-bar in the DOM, if not, add a class to `ion-tabs`, which I'm not opposed to. Will mention it perry and the team tomorrow

**Comment by luca3m** [comment]
This fix causes trouble on my project, try [this codepen](http://codepen.io/anon/pen/YyWxKd) adding and removing `tabs-top` class from the tab bar.

**Comment by jmsherry** [comment]
This happens in v2 also.

**Comment by jgw96** [comment]
hello all! Are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!

**Comment by Alexintosh** [comment]
I've recently found this issue on Ionic version: 1.3.1  (released 2016-05-12), it show up only on ios 9.1 on iphone 6 plus and Fairphone 1 with Android 4.4.4
