### ISSUE TITLE
feat: Better animations for list re-order

### ISSUE THREAD

**Issue by pbernasconi** [driftyco/ionic#2925]
The `<ion-list>` is a bit limited in terms of animations at the moment. On iOS, a list re-order would result in an animation where the dragged list-item would force other items which it hovers over to be pushed up or down, signaling to the user that something has changed.

There's a good vanilla JS tool for lists, which supports angular and could be used as a reference and guide:

- http://rubaxa.github.io/Sortable/ [Github](https://github.com/RubaXa/Sortable)

And a GIF representation:

![](http://media.idownloadblog.com/wp-content/uploads/2014/03/iOS-7-Mail-rearranging-shortcuts.gif)

**Comment by perrygovier** [comment]
Thanks @pbernasconi, I hope to address this as part of adding native scroll support to list reordering

**Comment by mhartington** [comment]
There is this PR which could aid in this.

https://github.com/driftyco/ionic/pull/3143

**Comment by mhartington** [comment]
Moving this to our trello board for now.

https://trello.com/c/E0yMJCM6/86-better-animations-for-reorders
