### ISSUE TITLE
bug: Animations continually increase the number of js event listeners.  

### ISSUE THREAD

**Issue by fudom** [driftyco/ionic#29263]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When ever you play animation (AnimationController), the js event listeners counter increases (Chrome dev tools performance monitor). Not sure if this is a memory leak? Maybe forgot to destroy/dispose the listeners? Or is this normal? Just a counter of ever existed listeners?

### Expected Behavior

The js event listeners should not grow infinitely.

### Steps to Reproduce

1. Create an animation.
2. Play the animation e.g. in setInterval.
3. Open Chrome dev tools, hit ESC to toggle the bottom panel, click on the etc (3-ellipses icon) and select Performance monitor, then enable JS event listeners to see the amount of them.

```ts
import { AnimationController } from '@ionic/angular';

const animation = this.animationCtrl
  .create()
  .addElement(this.icon.nativeElement)
  .duration(500)
  .fromTo('opacity', 1, 0);

window.setInterval(() => {
  void animation.play();
}, 1000);
```

![demo](https://github.com/ionic-team/ionic-framework/assets/143608856/5fd57f53-de79-4a3a-b785-cda6a479db0b)
(The progress bar just indicates the gif animation. The counter does not reset. Recorded with 500ms interval.)

Btw. Is it possible to `removeElement` or `clearElements`? So that you only create the animation once with dynamic elements.

**Comment by liamdebeasi** [comment]
Can you provide a reproduction I can run? I'm not able to reproduce this on my end.

**Comment by liamdebeasi** [comment]
Also it would be good to check if the event listeners are cleaned up after a delay. Garbage collection won't happen as soon as the animation ends, so it might be worth manually running garbage collection to verify that collection isn't just delayed.
