### ISSUE TITLE
feat: Use ion-infinite-scroll with no loading

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2926]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I want to use the ion-infinite-scroll, but with no spinning loading, would be great some property like:

```html 
<ion-infinite-scroll show-spin="false"></ion-infinite-scroll>
```

Or something like that. 

I only want to use it in my controller, so, maybe a service, would be better than a directive to do it. 

Another thing I'm missing in this directive, is a text and the position of the text. For example, a loading icons with the text 'Loading' above the icon.

I hope it helps improve Ionic.</span>

<span is-issue-template></span>

**Comment by Sjerd** [comment]
You can define an icon, so if you want a non spinning icon you could do 

<ion-infinite-scroll
        icon="ion-load-c"
        on-infinite="loadMoreData()"
        ng-if="moreDataCanBeLoaded"
        distance="1%">
      </ion-infinite-scroll>

or if you want none you can do 

<ion-infinite-scroll
        icon="none"
        on-infinite="loadMoreData()"
        ng-if="moreDataCanBeLoaded"
        distance="1%">
      </ion-infinite-scroll>

**Comment by JiachenDuan** [comment]
You can simply add a similar method in your controller to show the loading 
$scope.showloading = function (durationtime) {

            if (!durationtime) {

                $ionicLoading.show({
                    template: 'Loading...',
                    noBackdrop: true
                });
            } else {

                $ionicLoading.show({
                    template: 'Loading...',
                    noBackdrop: true,
                    duration: durationtime
                });
            }

        };
