### ISSUE TITLE
bug: nav-buttons don't show unless moved inside ion-view

### ISSUE THREAD

**Issue by CatabeeScienceAndDesign** [driftyco/ionic#2952]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've had a right button in the nav bar, specific to each state, using ion-nav-buttons.

```html
<ion-nav-buttons side="right">
    <button class="button button-icon icon ion-gear-b" ng-click="popover.show($event)"></button>
</ion-nav-buttons>
<ion-view title="Plot">
  <ion-content class="has-header">
    <!-- stuff-->
  </ion-content>
</ion-view>
```

Switching to release 14 broke that functionality, and the workaround was to move the ion-nav-buttons inside the ion-view.

```html
<ion-view title="Plot 2">
  <ion-nav-buttons side="right">
      <button class="button button-icon icon ion-gear-b" ng-click="popover.show($event)"></button>
  </ion-nav-buttons>
  
  <ion-content class="has-header">
    <!-- stuff -->
  </ion-content>

  
</ion-view>
```

Is this even an issue, or was this change in requirements intended?  Will my workaround continue to work?  I browsed the change/deprecate/broken logs and didn't see anything directly referencing this.  I also checked the current issues, and didn't see anybody saying the same thing.  Am I missing something?

[Plunker showing broken and workaround](http://plnkr.co/edit/kv4bPqt8kDBWXQ8xGDAi?p=preview)

Ionic is an awesome project!  Kudos to the team.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @CatabeeScienceAndDesign!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2952)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by stianjensen** [comment]
The docs for ion-nav-buttons (http://ionicframework.com/docs/api/directive/ionNavButtons/) state that they should always be inside an ion-view. Is there a reason that you want to declare them outside of an ion-view?

**Comment by CatabeeScienceAndDesign** [comment]
Ah.  I was originally using it inside a [ion-nav-bar] (http://ionicframework.com/docs/api/directive/ionNavBar/) which does NOT have to be in the ion-view, so I had not noticed that requirement.  For some reason, in the previous version of Ionic I was able to use them outside the ion-view but upgrading brought in enforcement of that requirement.  Thanks!
