### ISSUE TITLE
bug: ionic sidemenu slide back with gesture is not working in new version

### ISSUE THREAD

**Issue by tzookb** [driftyco/ionic#2953]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>I updated to latest version: 1.0.0-beta.14

and now the side menu on my android after it is open you can't slide it back with gesture, you can only by clicking the menu hamburger or by clicking on the content where the side menu is not there.

This feature worked well before, I even checked the starter app of sidemenu and this occurs there as well.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @tzookb!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2953)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mertenhanisch** [comment]
I also experience this problem since beta14. On other Android devices it works in 1 out of 10 tries to swipe open the menu, whereas on iphone it works pretty well.

**Comment by dominikbulaj** [comment]
Same here. Works in browser with `ionic serve` but after building APK and running app on device I can't slide back. 
However side menu closes on taping inside `ionic-content`. But slide back would be correct behavior.  
I'm using v1.0.0-beta.14

**Comment by axacheng** [comment]
similar issue here, but my case is click dead and swipe to get hamburger menu works ... Any solutions ?

**Comment by ils-mrunalij** [comment]
i am also facing the same issue .please provide me the solution of it??

**Comment by mliu95** [comment]
I'm also getting this bug on my android using ionic v1.0.0. Works fine in my browser but stops working on my android device.

**Comment by lesliechw** [comment]
I have the same problem with sidemenu start project.

**Comment by Sentence** [comment]
+1
* v1.0.0 (Android 4.4.2 Galaxy Tab4 10" and 8.1 iPad Air) 
* v1.0.1 (Android 4.4.2 Galaxy Tab4 10", not tested yet on 8.1 iPad Air)

**Comment by raghavendradabbir** [comment]
Hi All,
FYI only - Upgraded from version 4.4 to 5.0, and the swipe feature works well.

**Comment by tzookb** [comment]
Thanks all but I think I'll close this issue á this was resolved by itself :/

So if somebody else will have this problem, he should open another issue.
