### ISSUE TITLE
New project hook is not executable

### ISSUE THREAD

**Issue by mcfedr** [driftyco/ionic#2961]
I have created a new blank project (`ionic start my-app blank`) 
And now I am trying to build for android (`cordova platform add android`) I see this error

    Running command: .../my-app/hooks/after_prepare/010_add_platform_class.js .../my-app
    execvp(): Permission denied

The problem is that the created file `/hooks/after_prepare/010_add_platform_class.js` is not executable, and cordova expects it to be

If I run `chmod +x .../my-app/hooks/after_prepare/010_add_platform_class.js` then the problem is fixed.

**Comment by adamdbradley** [comment]
You should use `ionic platform add android` instead of `cordova`. The `chmod` on the hook file actually happens from the `ionic` command.

**Comment by uooq** [comment]
Actually, I don't think that's the issue. When you generate a new project with ionic start (v 1.3.20) the ````010_add_platform_class.js```` file is created with ````-rw-r--r--````    Running ````ionic platform add```` after that does not seem to modify those permissions.

**Comment by chrigu-ebert** [comment]
I have the same issue like @uooq on osx v.10.11.3
