### ISSUE TITLE
ngCordova InAppBrowser not working on IOS emulator

### ISSUE THREAD

**Issue by ChrisMcNulty91** [driftyco/ionic#2963]
I am trying to use the ngCordova InAppBrowser plugin so I can use oauth strategies on my server side code. Android device and emulator work fine as does the desktop browser. I also added the <feature> to the config.xml and the issue still persisted.

**Comment by stianjensen** [comment]
Which version of InAppBrowser do you have installed? I have it working on iOS 8.1 simulator with version 0.5.4 of InAppBrowser

**Comment by Ionitron** [comment]
Greetings, @ChrisMcNulty91!

My sensors indicate that you have created an issue on our tracker that is more asking for usage help than an actual error with Ionic framework.

This Github issue tracker is used to track features, problems, and development of the framework.  

If you wish to get help using the framework itself, the recommended place is [the forum](http://forum.ionicframework.com).

Thank you for allowing me to assist you.

**Comment by ChrisMcNulty91** [comment]
I have that version installed. The InAppBrowser works fine. But when I use
it in conjunction with ngCordova it does not work. I posted this topic on
the forums about a month ago. No help was offered. I also tried the angular
subreddit. One user told me to add the <feature> tag for InAppBrowser in
the config.xml if it was not present. I did that and It still did not
alleviate the issue. I am aware that this is probably something on my end.
I have tried looking for help with this and all sources have come up dry. I
only posted the issue because when I tweeted the ionic guys I was told to
add an issue.

Regards,
Chris

**Comment by stianjensen** [comment]
And what version of ngCordova are you using? The last one - introduced 6 days ago - had some breaking changes for inAppBrowser.

https://github.com/driftyco/ng-cordova/releases

Although, since it works on the emulator I guess the error is more likely to be in the plugin than in ngCordova...

**Comment by ChrisMcNulty91** [comment]
I got it working. I had the target set to _blank. When I changed it to
_self it worked. Something I foolishly overlooked apologies. I took a break
from development for awhile. Trying to get back into the flow of things
