### ISSUE TITLE
bug: Title is pushed left after nav-transition="none"

### ISSUE THREAD

**Issue by barlindhaug** [driftyco/ionic#2966]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

In an app with a side menu, where one page transition has nav-transition="none" and you jump back to the home page after multiple pages, the title on the home page is pushed left by something like:

transform: translate3d(-123.45, 0, 0).

Only a problem on smaller screen sizes! Try with a width less than 600px.

CodePen: http://codepen.io/barlindhaug/pen/ogWoVZ
* Emulate mobile device (resize window to less than ~600px)
* Click "page" -> "Scientific Facts" -> "Home"</span>

Screenshot: http://postimg.org/image/i0evjjp5p/

<span is-issue-template></span>

**Comment by mhartington** [comment]
@barlindhaug Not seeing this in the nightly builds now. Possible that it has already been fixed.
Going to close this, feel free to reopen if this is not fixed.

**Comment by barlindhaug** [comment]
Thanks for looking into this.

I checked it again and I see now that this is only a problem on Android devices. I get the "welcome" header pushed all the way to the left both on my Android device and when emulating Android in Chrome. Viewing as a desktop browser or iOS device, it works.

**Comment by mliu95** [comment]
I'm on ionic v1.0.0 and currently experiencing this issue with just my android devices as well.

**Comment by mhartington** [comment]
Could you open a new issue and reference this please
