### ISSUE TITLE
feat: Handle "action" keyboard button behaviour

### ISSUE THREAD

**Issue by spythonman** [driftyco/ionic#2967]
Here is an Android 5.0 keyboard: https://www.dropbox.com/s/fu6n9lpglko7rxt/Screenshot%202015-01-16%2006.07.57.png?dl=0

Take a look at the blue button in the bottom-right corner.

It could be a good feature to be able to :

- Control which "type" of button displays (a "next" button, a "done" button, "search" button, ...)
- Control the action tied to this button. For example, submitting the form, focusing on a particular input field, ...

Here is a use case:
- I'm signin up and typing my name in a first input fied. In my case, the default behaviour of the keyboard button is to submit the form instead of going to the next field. That's not what is expected.

Note that this is exactly the same thing on iOS

**Comment by mhartington** [comment]
This is something that would require native code, as it effect the native keyboard.

Please open this issue in the [keyboard-plugin repo](https://github.com/driftyco/ionic-plugins-keyboard)
