### ISSUE TITLE
bug: Problem with transition between abstract views

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#2969]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys! I have some problems using Ionic, I hope Ionic team can help me with this.

(sorry I'm publishing it now as an issue, [first posted in the forum](http://forum.ionicframework.com/t/problem-with-transition-between-abstract-views/14402/))

### My app context

In my app, I have two abstract views, the first has a tab menu, and the second doesn't have anything just an `ion-nav-bar`, I use this to change from a state with tabs menu to another with anything I want in the footer with ion-footer-bar. For example, in a Question state I have a "Answer" button in a `ion-footer-bar`. So my app change from `tabs.timeline` (which has a tab menu) to `app.article` (which has a footer 'main' button)

### How to reproduce
I made this codepen to reproduce the issue http://codepen.io/felquis/pen/ogLYJE 

### Problem 1
1. Open the `no iframe` version http://s.codepen.io/felquis/debug/ogLYJE
1. Open the DevTools (Chrome) and emulate a iPhone 5 device and reload the page.
1. The app start with no tabs, (like a login state)
1. **Here is the problem** Click "go to app" (verify a black screen appeared in the leaving state)
1. Navigate between the tabs, check that the transitions works fine.
1. **Here is the problem** Click at any 'Click here' button (this will change the abstract view), note what happens to the leaving state.
1. **Mysteriously**, when you use the back button, the transition to the previous abstract view, works as expected.

###  Problem 2

Reload the `no iframe` to the start http://s.codepen.io/felquis/debug/ogLYJE

1. Click 'go to app'
1. The `tabs.home` is loaded
1. **Here is the problem** Click in 'Click here'

During the transition the leaving state doesn't turn black like before, but the leaving screen turn the `app.login` state with the red button and should be the `tabs.home` screen leaving with the green button.

### Problem 3

Reload the `no iframe` to the start http://s.codepen.io/felquis/debug/ogLYJE

1. Click 'go to app'
1. Click in 'Click here' green button
1. Click in the back button
1. Now, click at `profile` in the tabs
1. Now, click at `Config` in the tabs
1. **here is the problem**, click at `Home`

Note that the leaving state stay above the entering state with an opacity before disappear.

### Possible problem 4

I can't put tabs markup inside a `ion-footer-bar` tag? I need to use `ion-footer-bar` to Ionic correctly calculate the scrollable size of the screen, but the tabs inside ion-footer-bar seems broken as well as the `.button-full` that doesn't fill wall the width of the footer.

The `.button-full` is in the view `app.oi`, URL http://s.codepen.io/felquis/debug/ogLYJE#/app/oi/test/

### ...

I know I'm possible implementing Ionic wrong, but, the transitions between the states seems very correct, one state I need tabs and here I have navigation, another state I need anything, and here my apps continues to navigate correctly, with tabs the tabs doesn't change etc... (I don't have enough words to explain). It makes me feel that this is a problem with Ionic, not in my implementation of Ionic :) 

Hope this help improve Ionic in some way.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
So the over all issue is the setup of the tabs. 

http://codepen.io/ionic/pen/odqCz

Update your pen to the correct setup

http://codepen.io/mhartington/pen/yyXEjX

**Comment by Ionitron** [comment]
Greetings @felquis!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by felquis** [comment]
@mhartington There's some way to use tabs but with animation between them?

**Comment by josephfinlayson** [comment]
I want to use abstract nested states, but this bug occurs when initally transitioning from a given state to the child state of an abstract state. Please fix! +1

**Comment by antonwestman** [comment]
+1

**Comment by tuvistavie** [comment]
I am having the same issue here.

when using

```
var states = [{
  name: 'app.news',
  abstract: true,
  url: '/news'
}, {
  name: 'app.news.index',
  url: '',
  template: require('./templates/index.jade')
}];
```

and transitioning to `app.news.index` from a link in the page, I get a black transition screen.
However, if I replace it by
```
var states = [{
  name: 'app.news-index',
  url: '',
  template: require('./templates/index.jade')
}];
```

and transition to `app.news-index` I get a normal transition effect.

**Comment by Sshuichi** [comment]
Same issue here. Also at the given fix, you're hiding the back button. Try to show it back and the black screen is there.

**Comment by bianchimro** [comment]
+1

Same issue here.
Removing "abstract" from parent state fixes transition but this is not a valid option for me as it potentially breaks states logic.
