### ISSUE TITLE
bug: ionRefresher's disable-pulling-rotation attribute

### ISSUE THREAD

**Issue by gouegd** [driftyco/ionic#2971]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The disable-pulling-rotation is supposed to hide the rotating icon according to the doc. However it does not hide it, but instead hides the "pulling icon" (by default, an arrow pointing down).</span>

<span is-issue-template></span>

This was tested on beta 14

**Comment by mhartington** [comment]
| Attr | type | detail |
|----------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------|
| `disable-pulling-rotation` | boolean | Disables the rotation animation of the pulling icon when it reaches its activated threshold. To be used with a custom pulling-icon. |
| `pulling-icon` | string | The icon to display while the user is pulling down. Default: ion-android-arrow-down. |

So `disable-pulling-rotation` doesn't get rid of the icon, it just turns off the animation. You can use `pulling-icon` to actually enable/disable the icon.

http://codepen.io/mhartington/pen/qEJmZX

**Comment by gouegd** [comment]
right - I probably did not understand the doc correctly at the time, sorry
