### ISSUE TITLE
Bug: controllers are active in cached views.

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#2972]
When switching to a second view i.e.: another tab, the first view was normally removed from the DOM and `$scope` was destroyed. In beta14, the cache introduce an undesired behavior by leaving a view/controller/scope still connected. If a controller listen to some event on the scope (`$scope.$on(...)`), these will still be triggered even if the view is cached.

Suppose you use a `$ionicPopup` in the event callback, it will still pop up when the view is cached.

I illustrated the problem in this pen: http://codepen.io/kbenoit/pen/GgmGBp

Emitting `"pause"` and `"resume"` events on the `$scope` could let someone unregister/register some listeners.

**Comment by Ionitron** [comment]
Please review the docs regarding view lifecycle and events: http://ionicframework.com/docs/api/directive/ionView/
