### ISSUE TITLE
Header Bar in iOS 8 gets displaced even if I disable status bar

### ISSUE THREAD

**Issue by mappmechanic** [driftyco/ionic#2973]
I have disabled status bar in my app, but the header bar is still displaced in my app. I cannot figure how to manage this displacement or change it. It should automatically detect, if the status bar exist then only add the extra padding.

Even if I enable my status bar, the header bar starts below the status bar and complete alignment goes flawed.
![screen shot 2015-01-21 at 12 22 07 pm](https://cloud.githubusercontent.com/assets/4088925/5832263/279afef4-a168-11e4-9030-8c9d7a3cfa6e.png)
![screen shot 2015-01-21 at 12 21 00 pm](https://cloud.githubusercontent.com/assets/4088925/5832264/2802f8f6-a168-11e4-9c4f-4e3b5c67f21c.png)

**Comment by maciulaitis** [comment]
You could try adding this line to your .run function, where you are hiding the status bar:
```javascript
.run(function($ionicPlatform) {
    ionic.Platform.fullScreen();
})
```
It realigns all stuff after status bar has been hidden. I had the same issue just few days ago. Hope it helps.

**Comment by perrygovier** [comment]
@maciulaitis' s solution is the proper way to tell Ionic to go fullscreen (remove status bar padding).
