### ISSUE TITLE
Strange Behaviour on Input[text, number or password] with XWalk or Cordova in Sony Xperia E1

### ISSUE THREAD

**Issue by albertossilva** [driftyco/ionic#2975]
We generate an .apk file either on XWalk either on Cordova, and we get a "strange" behaviour on inputs.
Most of the time what happens is: when I tap a input element, the cursor is shown, but when I type, sometimes just the first character works, and sometimes it duplicates the key I pressed.

Thanks.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#244
