### ISSUE TITLE
perf: Inconsistant UX for Infinite-scroll

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#2976]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If we checkout how infinite scroll works with ng-repeat, you'll notice that the spinner actually appears as an element until the new data is rendered.

http://codepen.io/mhartington/pen/QwvJEm

But if we use collection-repeat, the spinner does show, (fixed via https://github.com/driftyco/ionic/commit/838996815c3cfa0379a5235bd4c5174dec084f08) but remains hidden. Probably due to how collection-repeat works laying out items. 

http://codepen.io/mhartington/pen/RNVJMw</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Ah, yeah, the scroll body height doesn't extend properly. On it

**Comment by perrygovier** [comment]
fixed in 7913ee0f2856117a927da2d6ba14982f173c6b4c
