### ISSUE TITLE
bug: On iOS, automatic (sporadic) addition of has-tabs-top class to ion-header-bar

### ISSUE THREAD

**Issue by rajatrocks** [driftyco/ionic#2977]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have an app with a nav/header bar with a tab bar just below it (so the tabs have the "tabs-top" directive. I've also tried using $ionicConfigProvider.tabs.position('top') instead, no difference). 

On my iOS device (an iPad Mini 2), sometimes when my app loads the ion-header-bar has the "has-tabs-top" class, which then proceeds to mess up all my formatting: the nav bar shows below the tabs and the ion-content contents are covered by the nav bar. See attached screenshots. 

On Android, the "has-tabs-top" class never gets added, so there are no issues there. 

My temporary workaround is to comment out line 8424 in ionic-angular.js which keeps the "has-tabs-top class" from being added to the ion-header-bar.</span>

<span is-issue-template></span>

**Comment by rajatrocks** [comment]
Here's what things look like when "has-tabs-top" gets added: 

![image 1](https://cloud.githubusercontent.com/assets/7295726/5851996/5b5e3880-a1c4-11e4-97ee-dfafcadfe35b.jpg)

![image 2](https://cloud.githubusercontent.com/assets/7295726/5851998/674a2d70-a1c4-11e4-830c-2b962d8305f7.jpg)

**Comment by rajatrocks** [comment]
Here's what things look like when it is not added (correct):

![image 3](https://cloud.githubusercontent.com/assets/7295726/5852005/8366a240-a1c4-11e4-9cc6-fd01addc4415.jpg)
 
![image 4](https://cloud.githubusercontent.com/assets/7295726/5852008/8823e554-a1c4-11e4-98fc-16c275e67b77.jpg)

**Comment by rajatrocks** [comment]
This is probably related to https://github.com/driftyco/ionic/issues/2875

**Comment by stianjensen** [comment]
Are you sure the class is added only on iOS? In my tests, it seems to always be added, at least when running in the browser on my laptop.
The problem I experience, is that only iOS has special styling applied to this class, related to the iOS statusbar.

**Comment by rajatrocks** [comment]
On my test Android device (Moto X running 4.4.4), I can never get it to show up. But that doesn't mean the same problem isn't there. Seems to maybe be some sort of timing/race condition issue, since it appears/disappears. Maybe my iOS device is fast enough that it's making something different happen. 

I also just changed my app to load css and code dynamically at launch using https://github.com/markmarijnissen/cordova-app-loader, and I never noticed this problem on the same device until I made that change. So maybe something about the way that it's loading code.

**Comment by stianjensen** [comment]
The code for adding the has-tabs-top class to headers was recently wrapped inside a $timeout, https://github.com/driftyco/ionic/commit/3c330bc030162d6ab4687a47a9278524cebb8f3c

That could have something to do with the timing issues, I guess.

**Comment by mhartington** [comment]
@rajatrocks Have you tested this with the nightly builds?

**Comment by rajatrocks** [comment]
@mhartington Have not. Will give it a shot in the next few days.

**Comment by calendee** [comment]
@mhartington  Have the same problem.  Nightly build with master SCSS does not resolve.  Below are screenshots in browser and on device (iOS 8)

Browser : 
![tabs-top-nav-bar](https://cloud.githubusercontent.com/assets/57374/6318831/96d0cb4e-ba6a-11e4-91ee-2804af4257a2.png)


Device : 
![tabs-top-nav-bar-device](https://cloud.githubusercontent.com/assets/57374/6318835/a99a5a4c-ba6a-11e4-835a-77e63268a95d.PNG)

**Comment by mhartington** [comment]
So @calendee, is this issue all resolved?

**Comment by calendee** [comment]
Yes.  The nightly fixed it for me.

**Comment by shyamal890** [comment]
@mhartington It seems this issue is still present in Ionic V-1.3. 

![i](https://cloud.githubusercontent.com/assets/6606965/14912195/31752e4a-0e18-11e6-8ead-118afd8a4a5b.PNG)
