### ISSUE TITLE
bug: Ion-datetime can't select next year

### ISSUE THREAD

**Issue by phyr0s** [driftyco/ionic#29784]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Using ion-datetime i can't select next year date

### Expected Behavior

Select next year date 

### Steps to Reproduce

In here all calendars are like that, can't select in this case 2025 --> https://ionicframework.com/docs/api/datetime

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

V8 version

### Additional Information

https://ionicframework.com/docs/api/datetime

**Comment by sean-perkins** [comment]
@phyr0s the `max` property can be set on the datetime to allow date selection in the future. By default it renders the current year and 100 years in the past. 

For example:
```html
<ion-datetime max="2028"></ion-datetime>
```

Demo: https://stackblitz.com/edit/wkzbpc?file=src%2Fmain.tsx
