### ISSUE TITLE
ion-nav-bar should have a class when its nav back button is visible

### ISSUE THREAD

**Issue by AndrewMayorov** [driftyco/ionic#2979]
For styling purposes it is sometimes necessary to know when the navigation bar currently shows back button or not. It would be helpful if the bar will get some marker CSS class when button is visible.

**Comment by Ionitron** [comment]
My tests indicate that hidden back buttons receive a `hide` class.
I believe this resolves the issue. Please let me know if this solution is insufficient.

**Comment by AndrewMayorov** [comment]
@Ionitron, I know that button has class. This is good, of course, but it doesn't help you to style navigation bar itself. Unless you use CSS4 selectors, which is perhaps a bit too optimistic yet. How would you make the selector that targets navigation bar and is active then the bar doesn't have a child button with "hide" class?
