### ISSUE TITLE
Native date picker and scroll issue in iOS

### ISSUE THREAD

**Issue by AlexYankee** [driftyco/ionic#2980]
I have modal window with inputs inside - one date input and few text inputs.
All inputs inside ion-content.
When i focus date input, iOS datepicker is shown, but it does not push webview up and hides content underneath itself. When i first focus text input and then focus datepicker, everything works as expected - i can scroll down to reach content hided underneath datepicker.
UPD. Without 
```|| ionic.tap.isDateInput(e.target)```
in this line https://github.com/driftyco/ionic/blob/master/js/utils/keyboard.js#L146
it works properly.

![23 2015 0 45 01 ios](https://cloud.githubusercontent.com/assets/557092/5861232/82b3b806-a291-11e4-9225-6563ac32feaa.png)

**Comment by mhartington** [comment]
@tlancina any reason why we can't change this?

**Comment by tlancina** [comment]
Should be fixed with https://github.com/driftyco/ionic/commit/4636cb0ee4541004d9b0d2895f2a11a7a112d73c.
