### ISSUE TITLE
[WP] Landscape visualization issue

### ISSUE THREAD

**Issue by luisrudge** [driftyco/ionic#2983]
I know that ionic doesn't support WP, but I just want to log this issue. Maybe someone can point me to the right direction.

When the phone is in landscape mode, there's a problem with the viewport.
My viewport declaration is this:
`<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no,width=device-width">`
![image](https://cloud.githubusercontent.com/assets/941075/5868965/b50d3820-a298-11e4-8792-9c0faca63f5b.png)
![image](https://cloud.githubusercontent.com/assets/941075/5868970/c985d776-a298-11e4-9830-e30a80dc797a.png)

**Comment by iver56** [comment]
I'm seeing the same symptom (centering is wrong) on top tabs. This goes for both IE11 (desktop) and WP8 (mobile).

![image](https://cloud.githubusercontent.com/assets/1470603/6803054/5fbe8f5a-d235-11e4-834b-0536877acb75.png)

**Comment by Fayozjon** [comment]
iver56

http://workservis.ru/platforma

24.03.2015, 16:52, "iver56" <notifications@github.com>:I'm seeing the same symptom (centering is wrong) on top tabs. This goes for both IE11 (desktop) and WP8 (mobile).

**Comment by iver56** [comment]
When I add this little css hack if the browser is IE, at least I can see all the tabs. They are not perfectly centered, though.
```css
.tab-nav.tabs{
    justify-content: flex-start
}
```

**Comment by beat-at-hartwig** [comment]
I have a similar bug on windows phone 8.1 relating this issue. It happens in a "Card Showcase" in the card footer. The "tab-items" are not properly aligned. This workaround seems to help me as well. Thank you guys.

![Uploading card_tab-item.PNG…]()

There shoulb be another item next to the "30 minute" tab-item.

**Comment by mhartington** [comment]
We will not be supporting WP8 with ionic v1.

**Comment by PerfectionCSGO** [comment]
This issue is also present in Windows Phone 8.1, could you reconsider reopening this?
