### ISSUE TITLE
$scope should not be detached from view until after transition is complete

### ISSUE THREAD

**Issue by colllin** [driftyco/ionic#2984]
Currently it's detached before the view transition begins.  This makes it impossible to modify the DOM in a beforeLeave or afterLeave callback.

This is the same bug I was trying to describe in #2742, but apparently I did a terrible job describing it, so I'm reopening here and trying to be more succinct.

**Comment by olivierlesnicki** [comment]
The beforeLeave and afterLeave callbacks are currently defective. They're being called after the $scope has been detached which prevents them from accessing/updating the scope.

@mhartington I think @colllin  was pretty clear in his description of the issue in #2742, and the fix to ionic he's put forward actually worked and should highly be reviewed/considered. As I suspect it has been overlooked.

I've raised #2818 which is currently sitting with @adamdbradley.

**Comment by olivierlesnicki** [comment]
@colllin - this commit should have fixed it: https://github.com/driftyco/ionic/commit/04a0cce134d9e1201702b6bb8232ca83a028671a

**Comment by colllin** [comment]
AWESOME.  Thank you @olivierlesnicki for staying on top of this!!

**Comment by adamdbradley** [comment]
Yes thank you everyone for the help!
