### ISSUE TITLE
bug: Tab contents blink on Android

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2989]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> / <span ionic-platform-version>Chrome emulation mode</span> / <span ionic-webview>browser</span>

<span ionic-description>When switching from a tab to another, the content of the newly selected tab will blink.

It occurs when using the Chrome emulation mode with an Android device. It does not occur when using an iOS device, so I guess it's related to the device-specific animations.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Are you seeing this using the tabs starter? We're not. If so, could you let us know what device and android version you're seeing this on? If it's not in the starter, could you share a codepen or example app that we can test against?

**Comment by Ionitron** [comment]
Greetings @arcanis!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
