### ISSUE TITLE
Scroll position after changing view - AngularJS

### ISSUE THREAD

**Issue by JonathanHindi** [driftyco/ionic#299]
I notice an issue it may happens specially because the way I include my views. 

I have a sideMenu with some links when tapping on of the links it goes to a router that load a template file using the normal `$routeProvider.when('/link', {templateUrl: '/templates/link.html', controller: 'LinkCtrl'});` inside an `<ng-view></ng-view>` directive. 

Everything work fines expect if for example I accessed link1 and scrolled down then opened the side menu and tapped link2 the view opened scrolled a little bit, I think it happens because the scroll plugin store the current position on the ng-view element itself. 

I thought of current workaround but it doesn't work as expected. Add `scroll="false"` attribute on `<ng-view>` and then inside the template file find the first tag e.g `<div>` ad `scroll="true"`.

You did a great job with the new scroll implementation it works better, and I hope you would be able to fix any related bugs.

**Comment by jamm** [comment]
@JonathanHindi 
> I added the following to listen to Angular $viewContentLoader

it doesn't work when all templates are pre-cached in JS. And this is a good practice, so please consider to find some more universal solution.

**Comment by rubenjimenez** [comment]
I'm suffering this glitch right now.

Until now i've been using next to avoid the scroll problem:

```
  $rootScope.$on("$viewContentLoaded", function () {
    $anchorScroll();
  });
```

But this makes scroll is always on top, which is a little bit annoying when user wants to go back and keep surfing from the point he was.

**Comment by jamm** [comment]
@rubenjimenez try attribute overflow-scroll="true" - it solved my issue (and not one).

**Comment by saltmktg** [comment]
@rubenjimenez Would you be able to explain where exactly I would put that code, and how I would insert it into the existing code? Thanks in advance for any help you can provide.
