### ISSUE TITLE
List Receives Click While Scrolling

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#2991]
So I have an app that display a list using collection-repeat. When I flick the list to have it scroll, normally I would expect to tap an item to stop the scrolling but instead a click event is fired as Ionic translates it as a tap or click event and takes me to the detail page of the item I have clicked. 

A possible fix will be disable tap events while scrolling is happening or detect the intensity of the click or tap event such that the subtle tap events while scrol should stop the scroll not fire the tap event. 

This issue has been experienced on IOS but I can be sure it is same on Android.

**Comment by adamdbradley** [comment]
This should be solved now, thanks: https://github.com/driftyco/ionic/issues/1438
