### ISSUE TITLE
Log In link redirect to a wrong page at homepage of Ionic Creator

### ISSUE THREAD

**Issue by ahayder** [driftyco/ionic#2995]
Down below "https://creator.ionic.io/" In this page "Log in" link redirects to "http://drifty.com/" whether it should redirect to this "https://creator.ionic.io/app/login" link.

That's all thanks :)

**Comment by adamdbradley** [comment]
thanks, logged the issue here: https://github.com/driftyco/ionic-creator-issues/issues/184
