### ISSUE TITLE
bug: Bridge not enabled when using Crosswalk with livereload

### ISSUE THREAD

**Issue by ChrisLoer** [driftyco/ionic#2999]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried updating my Ionic app to use Crosswalk, following the [instructions provided in the blog post][1], and it seems to be working fine when I simply run it with `ionic run android`. However, if I try to use the "livereload" feature by running `ionic run android -l`, plugins stop working within the app. If I break inside `cordova.js:androidExec`, I can see that there's a call to `nativeApiProvider.get().exec` that simply doesn't return anything when I'm running in livereload.

It looks to me like the reason the bridge isn't working is this code in CordovaBridge.promptOnJsPrompt():

         if (origin.startsWith("file:") ||
             origin.startsWith(this.appContentUrlPrefix) ||
             (origin.startsWith("http") && loadedUrl.startsWith(origin))) {
             // Enable the bridge
             int bridgeMode = Integer.parseInt(defaultValue.substring(9));
             jsMessageQueue.setBridgeMode(bridgeMode);
             // Tell JS the bridge secret.
             int secret = generateBridgeSecret();
             return ""+secret;
         } else {
             Log.e(LOG_TAG, "gap_init called from restricted origin: " + origin);
         }

My origin is `http://192.168.1.42:8100/`, while the loadedUrl is `http://192.168.1.42:8100`, so the bridge secret never gets generated.

Without Crosswalk, essentially the same code runs, but the loadedUrl is set to `http://192.168.1.42:8100/`. I haven't been able to figure out where in the code this happens, but as a workaround I've just added a trailing slash in the content src of my config.xml. I think it would be better to modify the CordovaBridge code to do something like:

    URL originURL = new URL( origin );
    URL loadedURL = new URL( loadedUrl );
    if ( originURL.getProtocol().equals( "http" ) 
      && loadedURL.getProtocol().equals( "http" ) 
      && originURL.getAuthority().equals( loadedURL.getAuthority() )  )
    // Enable the bridge

  [1]: http://ionicframework.com/blog/crosswalk-comes-to-ionic/</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ChrisLoer!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=2999) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=2999)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#248
