### ISSUE TITLE
bug: select element not updating on user interactions, ngshow uses its model

### ISSUE THREAD

**Issue by alexkb** [driftyco/ionic#3003]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a non-dynamic select field in my view with several options, and a number of ng-show conditions later on in the view that use the value of said select field to determine if they should display or not.

The ng-show blocks toggle when they're suppose to meaning the model is updating as expected but the select field rendering the model value doesn't. There's no special controller code changing the model, just the user interacting with the field.

The code looks something like this:

	<label class="item item-input item-select">
	  <div class="input-label">
		Selection
	  </div>
	  <select ng-model="data.mySelection">
		<option>1</option>
		<option>2</option>
		<option>3</option>
	  </select>
	</label>
	
	<div ng-show="data.mySelection == '2'">
	  <ion-toggle ng-model="data.extraOption" toggle-class="toggle-calm">Extra Option</ion-toggle>
	</div>

I can't replicate the issue in Chrome (via ionic serve), it only seems to be an issue after a mobile build for Android (and I haven't tried iOS yet).

Am I doing something wrong here or is this an ionic/angular bug?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alexkb!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3003) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3003)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by alexkb** [comment]
I've just updated my ionic project from v1.0.0-beta.13 to v1.0.0-beta.14, which also updated some of the angularJS dependencies (1.2.something to 1.3.6), and it seems to have fixed the issue.

I can't see anything obvious in [the ionic changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) so perhaps it was an angular thing. Looking through [angular's changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md), there are several mentions of select [being improved](https://github.com/angular/angular.js/issues/9592) between 1.2 and 1.3.6, so I'd say it was angular.
