### ISSUE TITLE
Black Screen Transition with ion-checkbox

### ISSUE THREAD

**Issue by jpcancienne** [driftyco/ionic#3006]
Reproduction of the issue: http://codepen.io/anon/pen/NPvLPY

Browser: Google Chrome for Mac OSX 10.9.5

The issue itself is hard to describe, and it would be easier using the codepen above to see what I mean.

The Issue:
Have rootScope object = {test:truth};  Have the next screen i am going to navigate to have an ion-checkbox looking at the object.test value. When the object.test value is false, the transition looks normal. When the object.test value is true, the screen I am navigating away from is black during the transition.

I can reproduce this issue with the starter-tabs project using the ionic cli, so I know I'm not going crazy. Thank you for any feedback. I hope this issue gets fixed soon.

**Comment by jpcamara** [comment]
Experiencing the same behavior. Seems to only occur when navigating forward into a view with a selected checkbox - if navigating back to a view with a selected checkbox the behavior is normal

**Comment by jpcancienne** [comment]
I have had times where the ion-checkbox is the previous view, and navigating back to it produces the black screen for view that was originally in front of the ion-checkbox view.

**Comment by mhartington** [comment]
Seeing this as well. So the black screen is from the leaving view getting the attribute `nav-view="cached"` applied to it, which just sets the display to none, which is being done on purpose. 

Oddly enough, if you use just css version of the directive, you get this as well.

http://codepen.io/mhartington/pen/PwOgQm

Well look into this more. Thanks
