### ISSUE TITLE
bug: Scrollling not working on Samsung S3, Android 4.3, Internet browser

### ISSUE THREAD

**Issue by dannyg** [driftyco/ionic#3008]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>browser</span>

<span ionic-description>I posted this as a comment on #1433  but am not sure how to re-open it.
Re-posting here in a new issue - I hope that is appropriate.
------------

I have this scrolling issue also.

On my own codebase I am using latest ionic (1.0.0-beta.14), while following codepen uses nightly.
The problem is reproduceable in both.

Here is the codepen:
http://codepen.io/dglenn/pen/xbLWEm

On my physical device (Galaxy S3 running Android 4.3) I cannot scroll the resulting list.
The other physical device I have is iPhone 4s on which it scrolls fine.
On desktops it works fine also.

Using browserstack I have run through a bunch of emulated devices, and they all seem to scroll fine, but the combination of Galaxy S3 running 4.3 is not available, so I am unable to confirm the exact platform versions this is happening on, but it is definitely happening on Galaxy S3 / 4.3 combination.

Note that Chrome on the same S3 scrolls correctly, this issue only affects the native browser.

I hope this is sufficient info, but please let me know if not.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dannyg!

We are now requiring all issues to be submitted through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3008) so that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3008)**

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by mhartington** [comment]
Just want to verify, you're seeing the issue once you compile down to an app right?

**Comment by dannyg** [comment]
Hi Mike,
I am seeing this when running in browser.
i.e. if I just click on the CodePen link on my Galaxy S3 (using default browser) I cannot scroll the list.
Let me know if I can provide any further details,
Dan

**Comment by mhartington** [comment]
Have you compiled this down into an app though and tested it?

**Comment by dannyg** [comment]
Hi Mike,
I do not intend to compile my app for Android, but rather users will access via a browser (it will be deployed as an app for iOS).

If it helps with diagnostics though, I just compiled it to Android adk and ran it on the Galaxy S3, and can confirm that the scrolling suffers from the same problem.

(To confirm: all works fine on iOS whether via safari or deployed as an app).

Let me know if I can get further info.
Thanks,
Dan

**Comment by mhartington** [comment]
Try changing the loop to this 

http://codepen.io/mhartington/pen/VYyKRj

Also, try a simplified demo on the device. I just tested again, and wasn't able to reproduce the issue

**Comment by dannyg** [comment]
Hi Mike,

I clicked on your codepen from my device - and it worked! It scrolled fine.

I looked at differences for a while scratching my head, and have discovered something.

Here is an exact fork of your code-pen that does NOT work on my device (cannot scroll):
http://codepen.io/dglenn/pen/NPXXGd

The *only* difference is I changed
    <link href="//code.ionicframework.com/nightly/css/ionic.css" rel="stylesheet">
    <script src="//code.ionicframework.com/nightly/js/ionic.bundle.js"></script>
to
    <link href="//code.ionicframework.com/1.0.0-beta.14/css/ionic.min.css" rel="stylesheet">
    <script src="//code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.min.js"></script>

i.e. from nightly build to the most recent beta of 1.0.0 (which is what I use locally).

So, there is some change in the ionic codebase between '1.0.0-beta.14' and 'nightly' that has fixed this issue.  I'm not sure which one.
Whatever the change was, I expect it will be in beta.15...

Thanks for your assistance Mike - still not sure what was causing it, but it should go away in next beta release.

Daniel

**Comment by skashi** [comment]
This is an issue again...

The nightly example above is not working:
http://codepen.io/mhartington/pen/VYyKRj

I'm using Ionic v1.1.1 myself and it is also not scrolling (updated since today)

**Comment by adrianoresende** [comment]
I'm using Ionic 1.4.2, I upload app to Ionic View and open in Samsung Galaxy S3 to test, but scroll and CSS3 display:flex not work.

**Comment by paredesivan** [comment]
@adrianoresende [http://caniuse.com/#search=display%3Aflex](url)
