### ISSUE TITLE
bug: changing bar-* class does not update header bar

### ISSUE THREAD

**Issue by Morriz** [driftyco/ionic#3014]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The ion-nav-bar directive should be listening to changes to it's bar-* class, and update it's children accordingly. The delegate should also offer a method to set the bar class programmatically.

I would create it if I had a better grasp on your code. Maybe later.</span>

<span is-issue-template></span>

**Comment by nickcmaynard** [comment]
Ideally, it'd be great to be ensure the *correct* children were updated accordingly.
That way, color transitions could be coded if required.

**Comment by mhartington** [comment]
This is something that should an external ion IMO.
Here's something that you could use as a starting point.

http://codepen.io/mhartington/pen/vOGJQv

**Comment by alvarowolfx** [comment]
@Morriz, the pull request #3896 should address this problem, any opinion on this ?

**Comment by Morriz** [comment]
Ok solution to a unique problem imo. I never re-use variables in my own code tho, so the code wouldn't pass my review. **nitpicking**

**Comment by mlynch** [comment]
Closing as this is a custom solution and will be smoothed out in the future.

**Comment by nickcmaynard** [comment]
Hang on - isn't this still a valid bug?  I appreciate it's not yet fixed, but shouldn't it be kept open until there *is* a fix?
