### ISSUE TITLE
bug: Unknown error with adding Crosswalk browser

### ISSUE THREAD

**Issue by hyyan** [driftyco/ionic#3015]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi , Thanks for the great work , I am trying to use crosswalk with ionic , I followed the steps described here [Ionic and Crosswalk](http://ionicframework.com/blog/crosswalk-comes-to-ionic/) but I keep getting an error which I don't know how to resolve.

```
$ ionic browser add crosswalk
Adding crosswalk browser

Downloaded cordova-crosswalk-engine

Downloading: https://github.com/driftyco/cordova-android/archive/crosswalk.zip
[=============================]  100%  0.0s

Finished downloading cordova-android v4.0.x

Altered permissions for Android Paths

Downloaded Cordova Android for Crosswalk

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/8.37.189.14/arm/crosswalk-webview-8.37.189.14-arm.zip

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/8.37.189.14/x86/crosswalk-webview-8.37.189.14-x86.zip
unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -

An error with adding Crosswalk browser occured
```

```
$ ionic info

Your system information:

OS: Windows 7 SP1
Node Version: v0.10.25
Cordova CLI: 4.2.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.2
```

Any idea will be helpfull ? Thanks in advance</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hyyan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3015). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3015)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

**Comment by jbavari** [comment]
@hyyan - does this happen every time you run the command? Does it always fail to unzip the package?

**Comment by hyyan** [comment]
@jbasinger Yes , every time I run this command

**Comment by jbasinger** [comment]
I think you @'d me by accident @hyyan =)

But, all is well, I think I see your problem. It looks like you're pulling an old version of Crosswalk.
Try this command instead:
`ionic browser add crosswalk@10.39.235.15`

**Comment by hyyan** [comment]
@jbasinger I tried this before I submit the issue , and I got the same result .

I don't know if this can help or related but I using git bush to run my commands

**Comment by jbasinger** [comment]
@hyyan Do you get the same error when you run from a regular window command prompt?
I have no idea how this download works, honestly, but this:
```
unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -
```
Looks like it might be a checksum of some kind? Maybe it's using the wrong tool to hash what you pull down or something silly.

**Comment by jbasinger** [comment]
Just looked at the code a bit
https://github.com/driftyco/ionic-cli/blob/master/lib/ionic.js#L760
Looks like it's having trouble unzipping it. Do you have permissions to the folder it's trying to unzip to?

**Comment by hyyan** [comment]
@jbasinger  I have just tried the default windows cmd and got the same result ,  and yes I have permission to the folder I am working on it , Is there any requirement that I might not be aware of ?

here is the result 

```
C:\Users\Hyyan\Desktop\fdg>ionic start my_app
Creating Ionic app in folder C:\Users\Hyyan\Desktop\fdg\my_app based on tabs pro
ject

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
Fetching plugin "org.apache.cordova.device" via plugin registry
Fetching plugin "org.apache.cordova.console" via plugin registry
Fetching plugin "com.ionic.keyboard" via plugin registry

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd my_app

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html


 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or visit the Ionic docs: http://ionicframework.co
m/docs

C:\Users\Hyyan\Desktop\fdg>ionic browser add crosswalk@10.39.235.15
Adding crosswalk browser

Downloading: https://github.com/driftyco/cordova-crosswalk-engine/archive/v0.8.z
ip

Downloaded cordova-crosswalk-engine

Downloading: https://github.com/driftyco/cordova-android/archive/crosswalk.zip


Finished downloading cordova-android v4.0.x

Altered permissions for Android Paths

Downloaded Cordova Android for Crosswalk

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/10.39.235.15/arm/crosswalk-webview-10.39.235.15-arm.zip

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/10.39.235.15/x86/crosswalk-webview-10.39.235.15-x86.zip


unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -

An error with adding Crosswalk browser occured
```

**Comment by jbasinger** [comment]
@hyyan That is really odd. I found this bug in the unzip library being used, the message is similar but not exactly the same:
https://github.com/EvanOxfeld/node-unzip/issues/32

I'm using Crosswalk and those commands are working fine for me. The only other thing I can think of is that you don't have access to the URL it's trying to download? 
If you copy and paste the download.01.org link into a browser does it let you download the file?

**Comment by hyyan** [comment]
@jbavari I have already tried to open the url in the browser with proxy and without proxy and it is fine , probably as you said it is a bug related to library used to unzip the file .

**Comment by hyyan** [comment]
@jbasinger I have just updated the ionic to version 1.3.7 and I got an infinity warning message 

```
ext version of node. Please use setImmediate for recursive deferral.
 ✗ (node) warning: Recursive process.nextTick detected. This will break in the n
ext version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

Should I submit a new issue related to ionic 1.3.7 ?

**Comment by matthewkremer** [comment]
@hyyan @jbavari @jbasinger I too am experiencing the "Maximum Call stack size exceeded" error when trying to add Crosswalk.

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic-cli#231
