### ISSUE TITLE
bug: Content drag stops working after change state

### ISSUE THREAD

**Issue by alextrs** [driftyco/ionic#3017]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After update to beta-14 ion-side-menu-content content-drag stops working after state changed, see codepen here: http://codepen.io/alextrs/pen/XJeNxa. You can also see this issue if you remove 'menu-close' directive from anchors in your example: http://codepen.io/ionic/pen/tcIGK </span>

<span is-issue-template></span>

**Comment by alextrs** [comment]
After some fiddling, I found the the following fixes the problem (that's why example with menu-close works), but I don't think that this is good workaround as it breaks history:
```javascript
$ionicHistory.nextViewOptions({
    historyRoot: true
});
```

**Comment by mhartington** [comment]
This is by default.
http://ionicframework.com/docs/nightly/api/directive/ionSideMenus/

It can be disabled by changing the `enable-menu-with-back-views` attribute.
