### ISSUE TITLE
bug: angular-ui-router out of date

### ISSUE THREAD

**Issue by kno** [driftyco/ionic#3018]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The included version of this component is v0.2.10 wich not includes the reload function (included in 0.2.12+)</span>

<span is-issue-template></span>

**Comment by Eylen** [comment]
+1

**Comment by mhartington** [comment]
We are using 0.2.13, which is the latest version. 


https://github.com/driftyco/ionic/commit/f63b8c1a8eefdf3ee098f118dab1f2b47b7f1e95

This is latest stable version of UI-Router and is included in Beta 14.

**Comment by kno** [comment]
And how can I update it in an existing project?

$ ionic lib
Local Ionic version: 1.0.0-beta.14  (/usr/local/kno/Documentos/enlaobra/enlaobra-app/www/lib/ionic/version.json)
Latest Ionic version: 1.0.0-beta.14  (released 2014-12-15)
 * Local version up to date
$ head ./www/lib/ionic/js/angular-ui/angular-ui-router.js
/**
 * State-based routing for AngularJS
 * @version v0.2.10
 * @link http://angular-ui.github.com/
 * @license MIT License, http://www.opensource.org/licenses/MIT
 */

/* commonjs package manager support (eg componentjs) */
