### ISSUE TITLE
docs: one of the formulas has an error

### ISSUE THREAD

**Issue by nickh364** [driftyco/ionic#3023]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In some places you have bar capitalized like this $cordovaStatusBar. They all should be $cordovaStatusbar. Just letting you know.
http://learn.ionicframework.com/formulas/customizing-the-status-bar/</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Thanks, will fix this.
