### ISSUE TITLE
bug: Content embeds incorrectly

### ISSUE THREAD

**Issue by listrophy** [driftyco/ionic#3025]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This one is hard to explain, so here's a [codepen](http://codepen.io/anon/pen/gbGOma?editors=101). Basically, I'm using a pretty stock version of the side-menu starting template. I add an icon to the side menu navbar that creates a sidebar item, then immediately shows it in the main content area. The problem is that this new main content is pushed onto the current navigation stack, rather than replacing the current root navigation view.

To view the behavior:

1. Tap the Burger menu
2. Tap the "+" (normally, you might be asked to name the new thing. To simplify bug-reporting, that's omitted here)
3. Notice that, in the main content area, there is now a back button to "Playlist." This should not happen.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Adding the `.nextViewOptions` from `$ionicHistory` resolves this.

http://codepen.io/mhartington/pen/wBpvYM


http://ionicframework.com/docs/api/service/$ionicHistory/

**Comment by listrophy** [comment]
Awesome. Thanks @mhartington! :trophy:
