### ISSUE TITLE
bug: Ionic hide-on-keyboard-open not working on Android

### ISSUE THREAD

**Issue by jvannistelrooy** [driftyco/ionic#3041]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>On some Android phones (Android 4.4, no fullscreen app), the `hide-on-keyboard-open` class has no effect.

I tried to debug the problem and found that:

- The keyboard-open class is not added to the body when the keyboard opens.
- If I add the keyboard-open class manually, the elements are hidden.
- If I add the class manually when the keyboard's open, and then close the keyboard, the class is correctly removed and the elements are shown.
- It makes no difference if I open the keyboard by focussing on an input field or manually with cordova.plugins.Keyboard.show().
- Adding my own event listener to native.keyboardshow works.
- Mimicking the code from the ionic source to add the class works:

    window.ionic.requestAnimationFrame(function(){
      document.body.classList.add('keybord-open');
    });

I haven't been able to pinpoint the exact problem yet.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jvannistelrooy!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3041). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3041)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by paishin** [comment]
+1

**Comment by braxtondiggs** [comment]
+1

**Comment by milliger** [comment]
+1

**Comment by jackrr** [comment]
+1
seeing this on Moto G Android 5.0.2

**Comment by dbaq** [comment]
+1

nexus 5, android 5

**Comment by Yuripetusko** [comment]
+1 here on nexus 5

**Comment by Yuripetusko** [comment]
How did you do "If I add the class manually when the keyboard's open, and then close the keyboard, the class is correctly removed and the elements are shown."

Would be nice to have temporary solution

**Comment by Yuripetusko** [comment]
I used .keyboard-open {} class as a temporary solution

**Comment by bradmartin** [comment]
+1

**Comment by svanson** [comment]
+1

**Comment by softBarbarian** [comment]
+1. Same here.
```
OS: Mac OS X Yosemite
Node Version: v0.10.26
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.13
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1 


```

**Comment by clawish** [comment]
:+1:  +1

**Comment by mapierce** [comment]
+1

**Comment by pgorsira** [comment]
+1

**Comment by jsalhani** [comment]
The class is working fine for me (Nexus 5 and iPhone 5s), except it is slow to activate on Android; After the keyboard fully opens the elements hide and after the keyboard fully hides the elements show (with an additional 1s delay as well in each case)

**Comment by bradmartin** [comment]
@jsalhani same here. It works but is slow on Android (Galaxy S3 and S5). Takes approximately 1 second to fully hide the elements.

**Comment by eve-amandine** [comment]
@jsalhani @bradmartin +1
The same for me on Android (4.4.2), it's very slow.
On iOS, the class "keyboard-open" is added but sometimes isn't removed when the keyboard is closing.

**Comment by tlancina** [comment]
Hey all,
Adding that particular class to the body causes an expensive reflow, which makes scrolling inputs below the keyboard into view pretty janky on Android.  Assuming most users wouldn't need to hide elements and not wanting to penalize them, we moved it into a setTimeout after 400ms to still hide [things like the tab bar](https://github.com/driftyco/ionic/blob/6c9bc15b2996ae9183624c84a2709fd33f80d20b/scss/_util.scss#L32) when the keyboard shows.  Admittedly, this looks pretty bad for elements that you want to disappear immediately, however there is nothing stopping you from adding the class yourself as soon as the keyboard plugin event fires.  I'm going to close this as a wontfix for the aforementioned reasons, but if you want elements to hide immediately you can simply do (at your scroll animation's peril):
```
    window.addEventListener('native.keyboardshow', function(){
      document.body.classList.add('keyboard-open');
    });
```
I've updated the documentation to reflect these changes as well.

**Comment by sryze** [comment]
Just wanted to say that the above suggestion by @tlancina (which is also in the docs for the keyboard plugin) will conflict with ionic's implementation of adding `keyboard-open` to elements after 400ms if you manage to get the keyboard to close during this interval. 

For example, you can do this by tapping on an input and immediately tapping on empty space to cause the keyboard to close. It may be hard to do on Android but is 100% reproducible on iOS for me.

To fix it I had to replace `keyboard-open` with something else like `fast-keyboard-open` and the following piece of CSS (for footers in this case):

```
.fast-keyboard-open {
  .bar.bar-footer {
    display: none;
  }
  .has-footer {
    bottom: 0;
  }
}
```

However, this doesn't fix the Android problem completely - I still can see the footer bar lifting up together with the keyboard and disappearing only when it's fully shown (when animations end).
