### ISSUE TITLE
bug: Popover can go off screen

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic#3047]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>With a large popover on a small screen, the popover may extend off the top of the screen.

The old functionality was that the popover always went down, so the scroll area could be extended to accommodate the popover.
Changes made to the popover in 5d06c4aef8bf39703f9f4f32de52dad7749d1de5 cause the popover to pop up if it would extend off the bottom of the screen. If the popover is large enough that it also extends off the top of the screen, there is no way to scroll to it.

The default functionality is good in most cases, but there should be an option on the popover to specify "up" or "down". An option to automatically extend the scroll area if needed would be nice also.</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
OK cool, this makes sense. @AgDude what if we just made the popover only pop upwards if there's more room above than below?

So if the popover is 300px tall, there's 200px available below, and there's 100px available above, it will just stay with popping below.

**Comment by AgDude** [comment]
@ajoslin, I don't think that proposal will fully solve the problem. Let's say the popover is 350 px, there is 200px below, and 250px above. The popup would go up, and still extend off the screen and be unreachable,

What if you check that the popover will actually fit, then default to down?

Logic something like this:

What is the height of the popover (call it ```height```)
Hoe much space is below the popover point (call it ```footroom```)
if ```height``` > ```foot_room```
    how much space it above the popover point (call it ```headroom```
    if ```headroom``` > ```height```: go UP
else go Down

**Comment by ajoslin** [comment]
That makes sense. We'll only pop up if there's actually room up.
