### ISSUE TITLE
bug: iOS Input in popover hidden by keyboard

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic#3048]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When the keyboard opens for an input element inside a popover, the scroll does not adjust properly. You can see the screen "jump," as if it were going to scroll the input into view, but then it goes back to the original position. 

I also put an input on the main body of the same view, and when that was focused it scrolled into view as expected.

I have observed this on iPhone 5c iOS 8.1 and iOS emulator 7.1.
The app is using ```com.ionic.keyboard 1.0.3"```</span>

<span is-issue-template></span>

**Comment by AgDude** [comment]
Here are a couple of related threads on the forum:

http://forum.ionicframework.com/t/popover-overflow-when-ipad-soft-keyboard-shown/11945/3

http://forum.ionicframework.com/t/ionicpopover-and-keyboard-plugin/10193

**Comment by quentinbc** [comment]
Hello,

IOnic is great !
But i've the same error with my app in iPad iOS 7.2.
I added an input text in the popover.
When i edit the field, the keyboard appears over and input is below.
I can't view what i write in my field so it's not usable.

Unfortunately, the couple of threads upside not really help us to fix this error.
Version of ionic bundle : window.ionic.version = '1.0.0-rc.0';

Thanks for your help

**Comment by raphaelluchini** [comment]
I got the same problem, I disabled the scroll on angular run phase and I don't want to enable again, except for popups because the keyboard jump over them.

I've found a way to sove this problem:

Use ```cordova.plugins.Keyboard.disableScroll(false);``` when the popup open and use ```cordova.plugins.Keyboard.disableScroll(true);```when it close

The screen will scroll when the popup open and  it will lock again when the popup close

**Comment by quentinbc** [comment]
Ok thx a lot raphaelluchini !
Have a good day

**Comment by mhartington** [comment]
@AgDude is this still an issue with 1.0.1?

**Comment by Ionitron** [comment]
Greetings @AgDude!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
