### ISSUE TITLE
perf: Uncaught TypeError: Cannot read property 'openDat

### ISSUE THREAD

**Issue by Sajithik** [driftyco/ionic#3053]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Uncaught TypeError: Cannot read property 'openDatabase' of undefined.
 Uncaught ReferenceError: require is not defined.
i getting display but i cant inserting or create a table or database and login page.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Sorry, openDatabase is not a var name or method that exists or is called from Ionic.
