### ISSUE TITLE
bug: Collection-repeat resize beta.14-nightly

### ISSUE THREAD

**Issue by gnoumaster** [driftyco/ionic#3054]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

It seems that the last update break the automatic resize when the device is rotate.

 It works with beta 14 but not with the lastest nighly. My collection-repeat item is not recalculate when i rotate my screen (item size is the same than before the screen rotation).

No problem in the ionic codepen and on iOS, it seems to be only on android (tested on version 4.4)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gnoumaster!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3054). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3054)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
@adamdbradley this also happens with ng-repeat: http://codepen.io/anon/pen/pvdBzd

It appears to be a problem with clearing the cache right as a view loads. If we wait 100ms before clearing the cache, it works fine: http://codepen.io/anon/pen/LEOvPv

**Comment by gnoumaster** [comment]
Sorry my problem is not solved. I don't use clearcache and with the last nighlty (1009), I still have the problem.
I made other tests and I seem to be linked to expose-aside-when="large" on my side menu. I removed it and the resiz

 works.

On my tablet when i rotate the screen to landscape, the collection-repeat size seems to be equal to the size of the portrait width (picture portrait). And when i rotate to portrait, the width seems to be the size of the landscape.

No problem on iOS emulator.

![portrait](https://cloud.githubusercontent.com/assets/6771123/6114879/8625a260-b0a1-11e4-8ac4-6c89007b3cde.png)

![landscape](https://cloud.githubusercontent.com/assets/6771123/6114878/8623e592-b0a1-11e4-8864-398c0d533fb4.png)

**Comment by gnoumaster** [comment]
Can you reopen this issue?

Thanks.

**Comment by gnoumaster** [comment]
Hello, 
I created a codepen of my problem:

http://codepen.io/gnoumaster/pen/ByrvOj?editors=110

If you comment the nightly version and uncomment the beta14 version js/css files, it works great the "+" sign is inside of the view. I think this is a css problem, I use ionic grid system (row/col) insead of the collection-repeat list. Maybe this is not the right things to do?

I also test with the collection-repeat codepen done by the ionic team, and i have the same problem is I define a flot:right to the image.

Thanks for your help !!

**Comment by ajoslin** [comment]
Can you try the latest nightly build?

**Comment by gnoumaster** [comment]
I tried with the latest nightly and i still have the same problem. You can reproduce it with my codepen and chrome or stock brower on android 4.4. You rotate the screen and the collection-repeat list is not resized.

**Comment by ajoslin** [comment]
There were two problems:
1) exposing the side menu didn't cause collection-repeat to recalculate sizes
2) collection repeat wasn't always correctly recalculating sizes.

Both are fixed now. Your codepen will work when the nightly build is up.

**Comment by gnoumaster** [comment]
Hi,

Perfect it works, thanks.

But now my list is really slow on my tablet (galaxy tab S) with expose-aside-when="large", without it's smooth as before.

I don't see this problem on the codepen :( Do you have any idea?
