### ISSUE TITLE
bug: controllerAs syntax in ion-view

### ISSUE THREAD

**Issue by thaiat** [driftyco/ionic#3058]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There is still an issue with the controllerAs syntax and ion-view (beta 14)

this issue #2499 is still happening
here is a repro codepen: http://codepen.io/thaiat/pen/zxPMbL

if you change line 16 to the commented part, it's working
The issue is related to views in state</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thaiat!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3058). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3058)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by asfktz** [comment]
:+1:

**Comment by AliMD** [comment]
:+1: 
temporary solution: `controller: 'pageController as ctrl'`

**Comment by antonellopasella** [comment]
still using the temporary solution...

**Comment by elebetsamer** [comment]
Would be great if the `controllerAs` syntax was supported. I'm just trying to change my code to adhere more closely to [john papa's fabulous angular style guide](https://github.com/johnpapa/angular-styleguide) and I just spent an hour trying to figure out what I was doing wrong by using `controllerAs: 'vm'` only to find out that this is an ionic problem.

**Comment by SiddharthaRRamesh** [comment]
@elebetsamer Same with me! I spent an hour trying to make controllerAs syntax with Ionic. Even I am following john papa's style guide! But what about when using es6? His style guide has minor issues with respect to es6?

**Comment by elebetsamer** [comment]
@SiddharthaRRamesh I'm not crossing that bridge yet. Think I'm going to wait for angular 2 and ionic 2 before worrying about it.

**Comment by ace-han** [comment]
@elebetsamer, @SiddharthaRRamesh, Yes, I was following [john papa's fabulous angular style guide](https://github.com/johnpapa/angular-styleguide), too. Only to find out `ionic` currently works with controller: 'XxxController as vm'. I think we might as well follow this style now

**Comment by sodatea** [comment]
@SiddharthaRRamesh I use ES6 with ionic too. To circumvent this issue, I injected `$scope` into the controller class and assigned `this` to `$scope.ctrl`. Thus I don't have to change my template markup and it just looks as if the `controllerAs` syntax worked.This trick works well in my app.

My code looks like this:
```javascript

class LoginController {
  constructor($scope) {
    $scope.ctrl = this;
  }
  // some method definitions...
}

LoginController.$inject = ['$scope'];

**Comment by urish** [comment]
Just sent PR #3651 to fix this issue. Hopefully it will be merged soon :)

**Comment by thaiat** [comment]
@urish you are everywhere !!!!! ;)

**Comment by urish** [comment]
Same with you @thaiat :) 

p.s. here is the repro codepen with the fixed ionic version: http://codepen.io/anon/pen/QbbQPo

**Comment by maverix** [comment]
+1 Would love for this to be resolved!

**Comment by novarac23** [comment]
+1 for this being resolved! Thanks to @urish hopefully this will be resolved soon :+1:

**Comment by ashishdasnurkar** [comment]
+1 would be great to make this work

**Comment by ClemMakesApps** [comment]
Looking forward to having this added as well

**Comment by loose11** [comment]
+1 please make it happend

**Comment by cmartin81** [comment]
+1

**Comment by jiwhiz** [comment]
+1

**Comment by TankMasterRL** [comment]
Very annoying bug, please fix this!

**Comment by shmendo** [comment]
+1

**Comment by srameshr** [comment]
Please see us @Ionitron

**Comment by leandroz** [comment]
I cant believe that something trivial as controllerAs is not working.

**Comment by urish** [comment]
@perrygovier can you please look into merging this? 

it's a small change, and will help many people. Thanks!

**Comment by rocket13531** [comment]
+1

**Comment by larsar** [comment]
+1

**Comment by clmntfrndz** [comment]
definitely need this to be fixed, mustn't be that complicated to fix since the controller: 'controller as vm' syntax is working fine!

**Comment by urish** [comment]
@clmntfrndz the fix is already available in #3651, but hasn't been merged in yet

**Comment by mikeLspohn** [comment]
Any expected timeline of when this will be merged in yet and fixed?

**Comment by ClemMakesApps** [comment]
Looks like it's set for 1.1 release

**Comment by diegognt** [comment]
Please make that this happen

**Comment by cmartin81** [comment]
It is not fixed in the 1.1 release :(

**Comment by Telemakhos** [comment]
Why is the fix not being merged? well, I guess we'll have to patch it ourselves...

**Comment by mhartington** [comment]
@Telemakhos please check out the PR, I have addressed this.

>There were a few other things that took priority. Will revisit this. 
>You can still use controller as though, nothing is preventing you from doing so

>```
>controller: 'MainCtrl as main'
>```

**Comment by Telemakhos** [comment]
@mhartington ah! ok! I think that'll do the trick

**Comment by someone235** [comment]
+1
