### ISSUE TITLE
iframes block scrolling

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#306]
Would be nice to come up with a way to deal with having multiple iframes on a page as you scroll:
http://forum.ionicframework.com/t/iframe-scroll-bug/196

**Comment by divyenduz** [comment]
Any solution or workaround past this ? I am having a hard time embedding tweets :(

**Comment by adamdbradley** [comment]
Yes: https://github.com/driftyco/ionic/commit/b7cd6cb1ca7cdfc245827b4c460ae67810824841

http://davidwalsh.name/scroll-iframes-ios
