### ISSUE TITLE
bug: Navbar title mispalced on Android

### ISSUE THREAD

**Issue by petarov** [driftyco/ionic#3064]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

**Version**: v1.0.0-beta.14

<span ionic-description>
Hi,

There seems to be an issue with the title in the navbar on Android devices. This appears when the navbar is hidden and then shown again using the `hide-nav-bar` attribute of `ion-view`.

![android-title-bug](https://cloud.githubusercontent.com/assets/547597/6115603/fef58200-b0a6-11e4-9259-4c5becb6b590.png)

I was not able to create a Codepen demo, because it only happens when I run the app on the device or using `ionic server --lab`. Therefore, I have created a [test repo](https://github.com/petarov/ionic-android-title-issue) where this can be simulated.

Steps to reproduce:

  1. Run the app using `ionic server --lab`.
  2. Go to `Playlists` using the side menu
  3. Click the *Toggle* icon to hide the nav bar
  4. Click on a item in the list
  5. Go back to the `Playlists` view and press the *Toggle* icon again to show the nav bar

Result: 

  The title overlaps the menu icon.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @petarov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3064). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3064)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by petarov** [comment]
Any movement here?
I'm currently using a nasty hack to overcome this.

```javascript
  $scope.$on('$ionicView.afterEnter', function(event, state) {
    if (state.stateName === 'app.prevPage1' || state.stateName === 'app.prevPage2') {
      $timeout(function() {
        $ionicNavBarDelegate.align('left');
      }, 650);      
    }
  });
```

**Comment by dgrana** [comment]
This is also happening to me, please fix it

**Comment by djett41** [comment]
Also can confirm the same view title issue for Android on both chrome and on ionic-lab.

**Comment by petarov** [comment]
Works fine in `v1.0.0-rc.2-nightly-1184`

Thanks!

**Comment by salvadorhol** [comment]
I had a similar issue and fixed it by applying title class to h1 tags
```
<ion-nav-title>
    <h1 class="title">Title</h1>
</ion-nav-title>
```

**Comment by daltonpereira** [comment]
Hi, I face this issue for a second while switching between tabs. this happens only for the first time.

**Comment by mobicraft-am** [comment]
hi, i have exaclty the same bug, on the latest 1.3.1 release of ionic. I don't have the pb in the browser and on iOS.
I have found the pb with the remote debugger 👍 
If i modify this generate ionic code, it's work fine
I have delete "transform: translate3d(-74.625px, 0px, 0px);"
<div class="title title-left header-item" style="left: 50px; right: 114px; transition-duration: 0ms; transform: translate3d(-74.625px, 0px, 0px);">Compte :</div>

**Comment by mj6uc** [comment]
Same bug in the latest ionic release on a v1 app! Any workarounds, please?

**Comment by NickyTheWrench** [comment]
Bug still exists in Ionic v1 :-(
