### ISSUE TITLE
feat: Shared view between tabs

### ISSUE THREAD

**Issue by mvidailhet** [driftyco/ionic#3072]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>To sum up, I would love to have ionic tabs that share the same view like this:
```
   <ion-nav-view></ion-nav-view>

    <script id="templates/tabs.html" type="text/ng-template">
      <ion-tabs class="tabs-icon-top tabs-positive">

        <ion-tab title="Home" icon="ion-home" href="#/tab/home">
        </ion-tab>

        <ion-tab title="Profile" icon="ion-person" href="#/tab/profile">
        </ion-tab>

      </ion-tabs>
    </script>
```

My app have tabs that share a lot of views. For the moment, I have to create a specific state for each tab for each of these views, like I did in this codepen: http://codepen.io/mvidailhet/pen/LEeZdJ
When it's about one view it's ok, but when it's about more, it becomes a bit messy.

I don't really need to have a specific view by tab and would love it if the tabs could share the same one. 

Actually, it kinda already works as is, but the history is messed up.
I managed to reset the history root each time I tap on a tab using the 'on-select' callback of ionTab. 
But if I go in substates of a tab, I cannot go back to the root by taping again on the tab. I dug in the ionic code and found that if I replaced this line: https://github.com/driftyco/ionic/blob/master/js/angular/controller/tabsController.js#L69 
by this line: `$ionicHistory.goToHistoryRoot('root');` it worked. Seems that there is a history created for each tab. But I think the solution is not so trivial.
I tried to make a codepen whit this share view example, but it doesn't work. So I made a github project: https://github.com/mvidailhet/ionic-tabs-shared-view
If you go between tabs, you'll see that the history is reset. But If you go to the "Friends" tab and tap a friend in the list, if you try to tap the Friend tab again, it won't go back to the Friend root.

I hope I was enough explicit about my suggestion.

Love what you're doing with Ionic.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mvidailhet!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3072). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3072)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Ionitron** [comment]
Greetings @mvidailhet!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.

**Comment by gilles-yvetot** [comment]
I would love to have this feature too, I know it is more related to angular UI router, but being able to mutualise the view and controller would be awesome, (think about a product page that is present everywhere in a retail-related app)

**Comment by hcbsgit** [comment]
I there any update on this feature. please suggest a proper workaround for the smae

**Comment by spennyf** [comment]
Any progress on this feature?
