### ISSUE TITLE
bug: slidebox pager discounts if replace cached content

### ISSUE THREAD

**Issue by kaikcreator** [driftyco/ionic#3076]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The problem happens with cached slidebox.

After:
1. using slidebox to move between slides
2. change view (so slidebox get cached)
3. returning to slidebox
4. replace its content on enter (and number of slides)

Then:
The sliderbox pager shows an incorrect number of slides.

Check this codepen: http://codepen.io/-kaik-/pen/KwZgOG</span>

<span is-issue-template></span>

**Comment by agnellvj** [comment]
Seeing a very similar issue also. 
1. using slidebox to move between slides
2. use a custom filter to change the set of data being viewed
  a. wrap all the below in a scope.$applyAsync
  b. empty data structure containing viewed data
  c. fill structure with new data
  d. call $ionicSlideBoxDelegate.update()
  e. call $ionicSlideBoxDelegate.slide(0)
3. swipe to a new item
4. select a filter to do step 2 again. (pager will be hosed)

**Comment by agnellvj** [comment]
Seeing a very similar issue also. 
1. using slidebox to move between slides
2. use a custom filter to change the set of data being viewed
* wrap all the below in a scope.$applyAsync
* empty data structure containing viewed data
* fill structure with new data
* call $ionicSlideBoxDelegate.update()
* call $ionicSlideBoxDelegate.slide(0)
3. swipe to a new item
4. select a filter to do step 2 again. (pager will be hosed)

**Comment by agnellvj** [comment]
Seeing a very similar issue also. 
* using slidebox to move between slides
* use a custom filter to change the set of data being viewed
    * wrap all the below in a scope.$applyAsync
    * empty data structure containing viewed data
    * fill structure with new data
    * call $ionicSlideBoxDelegate.update()
    * call $ionicSlideBoxDelegate.slide(0)
*  swipe to a new item
*  select a filter to do step 2 again. (pager will be hosed)

There are also visual artifacts that happen when swiping between cards after the pager gets hosed.

**Comment by agnellvj** [comment]
will this issue be solved if this commit is brought in? https://github.com/driftyco/ionic/commit/2ab776023d571d57d9b8a1d7878904b24b1364f8

**Comment by rossholdway** [comment]
I'm still getting this issue (as shown in the codepen) in version 1.0.0.

**Comment by Ionitron** [comment]
Greetings @kaikcreator!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
