### ISSUE TITLE
feat: Add colors classes to ionSpinner

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#3077]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ionSpinner is awesome, but I'd like to change the color with some preset colors as `light`, `stable`, `positive`, `calm` etc...

Something like this:
```html
<ion-spinner class="balanced"></ion-spinner>
```

And it resolves for iOS and Android but with a balanced color scheme :smile:

I know I can style the SVG with CSS, but I'm suggesting a improvement I think is useful.

Hope it helps improve Ionic :smile:</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
:+1:

**Comment by felquis** [comment]
Awesome! Thank you :smile:
