### ISSUE TITLE
Create UI kit

### ISSUE THREAD

**Issue by hollingberry** [driftyco/ionic#308]
It would be cool if somebody wanted to put the time in to make a UI kit for Ionic, whether that be in the form of a photoshop document, I don't know... just an idea.

**Comment by GiacomoPatella** [comment]
Hi guys,

What are the chances of a UI Kit for Sketch @bensperry @mlynch @adamdbradley ?

Thank you!

**Comment by devakone** [comment]
Or a UI Kit for UXPin?

**Comment by drixie** [comment]
Hey! What's up with the UI kit for Sketch/Photoshop? :D

**Comment by ericwooley** [comment]
@mlynch Any update for this? I am hoping to give some designers a baseline to work off of (to make my life easier of course). No response from you guys for a while on this issue.

**Comment by jgw96** [comment]
Hey, so we have since solved this issue with [Ionic Creator](http://ionic.io/products/creator)! Ionic creator gives you a browser based drag and drop prototyping tool to prototype your apps. Thanks!

**Comment by thecolab** [comment]
This is looking good - https://market.ionicframework.com/themes/ionic-sketch
