### ISSUE TITLE
bug: ionic start under proxy problem

### ISSUE THREAD

**Issue by diegorsd** [driftyco/ionic#3081]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>npm works correctly under proxy.

"ionic start xxx" gives error: 
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be established, cause=Parse Error

PROXY and HTTPS_PROXY environment variable have been set as
"http://user:pass@host:port"</span>

<span is-issue-template></span>

**Comment by diegorsd** [comment]
Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Windows\system32>SET PROXY=http://garoordi:bdd001@ibproxy03.intranet.ibermati
ca:8080

C:\Windows\system32>d:

D:\>cd temp

D:\TEMP>cd android

D:\TEMP\ANDROID>cd workspace

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


D:\TEMP\ANDROID\workspace>SET HTTP_PROXY=http://garoordi:bdd001@ibproxy03.intran
et.ibermatica:8080

D:\TEMP\ANDROID\workspace>SET HTTPS_PROXY=http://garoordi:bdd001@ibproxy03.intra
net.ibermatica:8080

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject

The directory D:\TEMP\ANDROID\workspace\toptravel already exists.
Would you like to overwrite the directory with this new project?
(yes/no): yes
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


D:\TEMP\ANDROID\workspace>SET PROXY=http://ibproxy03.intranet.ibermatica:8080

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


D:\TEMP\ANDROID\workspace>SET HTTPS_PROXY=http://ibproxy03.intranet.ibermatica:8
080

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject

The directory D:\TEMP\ANDROID\workspace\toptravel already exists.
Would you like to overwrite the directory with this new project?
(yes/no): yes
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


D:\TEMP\ANDROID\workspace>PROXY=http://garoordi:bdd001@ibproxy03.intranet.iberma
tica:8080 ionic start toptravel
"PROXY" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

D:\TEMP\ANDROID\workspace>set PROXY=http://garoordi:bdd001@ibproxy03.intranet.ib
ermatica:8080 ionic start toptravel

D:\TEMP\ANDROID\workspace>set PROXY=http://garoordi:bdd001@ibproxy03.intranet.ib
ermatica:8080

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


D:\TEMP\ANDROID\workspace>set PROXY=http://ibproxy03.intranet.ibermatica:8080

D:\TEMP\ANDROID\workspace>ionic start toptravel
Creating Ionic app in folder D:\TEMP\ANDROID\workspace\toptravel based on tabs p
roject

The directory D:\TEMP\ANDROID\workspace\toptravel already exists.
Would you like to overwrite the directory with this new project?
(yes/no): yes
https://github.com/driftyco/ionic-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be establis
hed, cause=Parse Error


Ionic info

Your system information:

OS: Windows 7 SP1
Node Version: v0.12.0
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.10

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#254
