### ISSUE TITLE
bug: Navbar second icon overflowed

### ISSUE THREAD

**Issue by alfons12** [driftyco/ionic#3082]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Please see http://forum.ionicframework.com/t/navbar-second-icon-overflowed-android-4-4-1/17104</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Should be fixed via eef1d32b04f341896d57a1cba319067b25614680

Can you test out the nightly builds

**Comment by alfons12** [comment]
Didn't do full update to nighly (have some custom modifications in place which don't want to break), just replaced the _bar.scss in my b14, recompiled and it works. If you still need "full test" then I would need to create a separate project for that.
