### ISSUE TITLE
bug: ion-item item-icon-right shifts when slid open

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ionic#3087]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Codepen example: http://codepen.io/RangerRick/full/VYyVeX/

I am trying to implement delete/edit/etc. for my list view.  Each list item has an "item-icon-right" icon, as well as a "item-note" span.  When you start to swipe the item to the left to expose the option button(s), the icon immediately jumps to the left, sitting on top of my item text and the item-note contents.  It is more obvious with long item text and the window shrunk to portrait phone size.</span>

<span is-issue-template></span>

**Comment by RangerRick** [comment]
FYI, a workaround described here: http://forum.ionicframework.com/t/ion-item-item-icon-right-rendering-bug/17472/2?u=rangerrick

Looks like something to do with how the CSS applies padding to the content?

**Comment by RangerRick** [comment]
An additional possibly related issue.  In Safari (mobile and desktop) whether or not the workaround is applied, when re-closing an item, the icon pops up like so:

http://ionic-forum-uploads.s3.amazonaws.com/25102037748d18dddbc04ddbf6c2c2b890bdd79bb758f_272x500.PNG

You can reproduce it using my original codepen.

**Comment by mhartington** [comment]
So that main issue seems to be this, `severity-{{alarm.severity}} `

http://codepen.io/mhartington/pen/ZYrKGV

Changing this to use ng-class fixes the issue. 
```
ng-class="'severity-'+alarm.severity"
```

http://codepen.io/mhartington/pen/WbMjQz
