### ISSUE TITLE
bug: Nav title is lagged to show up on tab change

### ISSUE THREAD

**Issue by jryu01** [driftyco/ionic#3090]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When navigating to a view with ion-refresher, ion-infinite-scroll, and ng-repeat with fetched array data which is in diffrent tab, the view title and nav buttons are delayed and rendered after view content fully show up and it is quite annoying. If array gets bigger with infinite scroll, it takes much longer time for buttons and title to change according to the current states. When first time navigating to the view is fine but it seems when the view is cached and revisit the view, this happens. It seems it has no problem showing up nav title and button when there are no infinite scroll and refresher directive used although it fetches async data from server and use ng-repeat. When I test with browser and ios simulator, It is working fine. But problem exists only in actually device (tested with iphone 5 ios8). I could reproduce this bug with simple modification on ionic tab starter code. Here is code that I modified. 

tab-friends.html
```
<ion-view view-title="Friends">
  <ion-nav-buttons side="right">
    <a class="button button-icon icon ion-person"
        href="#/tab/friend/1">
    </a>
  </ion-nav-buttons>
  <ion-content>

    <ion-refresher on-refresh="fetchFriends(true)">
    </ion-refresher>

    <ion-list>
      <ion-item class="item-avatar" ng-repeat="friend in friends" type="item-text-wrap" href="#/tab/friend/{{friend.id}}">
        <img ng-src="{{friend.face}}">
        <h2>{{friend.name}}</h2>
        <h3>{{friend.notes}}</h3>
      </ion-item>
    </ion-list>

    <ion-infinite-scroll
        ng-if="friends.length > 0"
        on-infinite="fetchFriends()">
    </ion-infinite-scroll>
    
  </ion-content>
</ion-view>
```
controllers.js
```
.controller('FriendsCtrl', function($scope, Friends, $timeout) {
  $scope.friends = [];
  // Simulate fetching data from server
  $scope.fetchFriends = function (refresh) {
    $timeout(function () {
      // prepeare enough friend lists
      var friends = angular.copy(Friends.all());
      for (var i = 0; i < 20; i++) {
        friends = friends.concat(angular.copy(Friends.all()));
      }
      if (refresh) {
        $scope.freinds = friends;
        $scope.$broadcast('scroll.refreshComplete');
      } else {
        $scope.friends = $scope.friends.concat(friends);
        $scope.$broadcast('scroll.infiniteScrollComplete');
      }
    }, 1000);
  };
  $scope.fetchFriends();
})
```
When visiting friends tab(starting from second time), title and nav button are lagged to show up and it gets worse with more fetched data while list contents are already fully showed up. If you comment out ion-refresher and infinite scroll. It is not lagged and shows up immediately.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Could you put this together in a codepen?

**Comment by jryu01** [comment]
Here is codepen link:
http://codepen.io/jryu01/pen/pvaPjO?editors=101

This problem seems to appear in the ios webview and also in mobile safari (running codepen codes) but not in the desktop browsers.

**Comment by mhartington** [comment]
Alright, this is a performance issue with angular and ng-repeat, too many items in the DOM. The lag is only visible if you start loading more items. Switching to collection-repeat reduces the lag considerably.

**Comment by jryu01** [comment]
Is it expected behaviour that header contents is delayed and changed after view content is loaded? When there are many ng-rpeat items, header title and buttons remain quite long time unchanged.
Also although even there are many dom elements I don't see the delay without the ion-refresher and infinite scroll directive on the view.

**Comment by mhartington** [comment]
I don't think it has too much to do with the ion-refresher.

In this example, http://codepen.io/mhartington/pen/radyGp , reducing the number of items in the initial items loaded into the DOM deficiently helps the title issue. 

Switching to collection-repeat prevents the flicker.
Closing this as it is not an issue with ionic, but a side-effect of too many ng-repeats.
