### ISSUE TITLE
bug: In IE11 the mouseWheel scroll doesn't work.

### ISSUE THREAD

**Issue by GauSim** [driftyco/ionic#3094]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In IE11 the mouseWheel Scroll doesn't work. But the ClickPull-Scroll works fine.
as you can see by opening http://codepen.io/ionic/pen/mwFuh in IE11. 
I know everybody hates IE, but it was in our target :) 

1. 
I think the "Mouse Events" dont get assigned in IE11
because the "Pointer Events"-elseif-case is performed and assigned.  
I found a dirty fix. I allways assign the "Mouse Events". 
:)

2.
Well, but now i found a second bug. In IE11 there is no "e.wheelDeltaY" property. 
In IE11 its called: "e.wheelDelta" (without the Y)
so to perform the scroll i modified the mouseWheel-Function like this: 
... 
self.scrollBy(
(e.wheelDeltaX || e.deltaX || 0) / self.options.wheelDampen,
(-e.wheelDeltaY || e.deltaY || -e.wheelDelta || 0) / self.options.wheelDampen  
);
...

this works fine.

maybe you can update this 
thanks.
Simon</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
We'll be pulling in this PR soon which should fix this issue: https://github.com/driftyco/ionic/commit/f89cf7005be14e9c02ae48e1b87519e5d09fba8d

**Comment by GauSim** [comment]
cool thx.

**Comment by adamdbradley** [comment]
Should be fixed in the nightly builds now, thanks
