### ISSUE TITLE
bug: beta14: Hidden ion-nav-buttons obscuring Title

### ISSUE THREAD

**Issue by revie** [driftyco/ionic#3098]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've got a view that has multiple buttons in it's ion-nav-buttons section, where only one of the buttons is shown at a time (based on context of data in view).  However, since beta14, Ionic has started doing the following:

1. Shows all icons when transitioning to the view, and doesn't appear to apply the $scope until after the view is done transitioning.

2. For platforms that center the title, Ionic is reserving the width of the "ion-nav-buttons" section as if all buttons will show, causing the view's title to be impossibly small.

In beta13 and below, the ion-nav-buttons section didn't show until after the view was loaded (and after the $scope was applied), so only the necessary space was reserved and no unnecessary icons displayed that didn't apply to the view's context.

Codepen example here:
http://codepen.io/revie/pen/emVmgM

Forum thread can be found here:
http://forum.ionicframework.com/t/beta14-hidden-ion-nav-buttons-obscuring-title/17519</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Faced the same thing when updated the app intro codepen. 

Adding 
```
i.ng-hide,
.button.ng-hide{
  display:none;
}
```
fixes the issue 

http://codepen.io/mhartington/pen/NPygLP

**Comment by revie** [comment]
Thank you!

**Comment by revie** [comment]
@mhartington, I think this might need to be reopened.  Sometime over the weekend, your codepen stopped working with the nightly version of Ionic.  The hidden icons prematurely showing is still fixed (as the CSS says it should), but the space in the headline is again being reserved even though the extra space isn't needed, and I'm not seeing anything in the CHANGELOG that would describe a needed change in logic.

Any ideas?

**Comment by mhartington** [comment]
Hmm, not seeing anything in the recent commits that could have to do with this.

https://github.com/driftyco/ionic/commits/master

Tested the codepen with the latest build on a device and wasn't see in the issue.

**Comment by revie** [comment]
Apologies.  I was running your Codepen in Firefox, and I should've tested on a device first.

Attached is a screenshot from running the Codepen on Android 2.3 (specifically a Droid X), and you can see that the title is being abbreviated.  Possibly only an issue on older Android devices, perhaps?

**Comment by mhartington** [comment]
Yeah, it may be an issue with 2.3 (which we've dropped support for btw).

Can you test this out on a 4.x device?

**Comment by revie** [comment]
The only 4.x devices I have at the moment are tablets, so I had to lengthen the title a bit (by adding "Really Long, Long Title: ") so that you can see that it's still a problem, at least on my devices.  Attached are screenshots from a Kindle Fire (G2), running 4.0.3:

![ionic-3098-20150217-2](https://cloud.githubusercontent.com/assets/810809/6236294/a372dcf6-b6a6-11e4-85eb-d1bd18e7c262.png)

and a HP Touchpad running 4.0.4:

![ionic-3098-20150217-3](https://cloud.githubusercontent.com/assets/810809/6236296/aa934f3e-b6a6-11e4-9fc0-ae1cc013a861.png)

**Comment by mhartington** [comment]
Looking at https://github.com/driftyco/ionic/issues/3132 then will get to this.

**Comment by mhartington** [comment]
So instead of using `ng-show`, why not use `ng-if`

http://codepen.io/mhartington/pen/RNMaYV

**Comment by revie** [comment]
Ahh.  That makes sense.  I was having problem with ng-if's "compile once" problem which is why the reliance on ng-show, but seems to be working here.  Thanks for the help.
