### ISSUE TITLE
bug: Navigation from view to hide-nav-bar="true"

### ISSUE THREAD

**Issue by andrewmcgivery** [driftyco/ionic#3099]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/andrewmcgivery/pen/vEdNZz

View A has  hide-nav-bar="true"
View B does not.

Navigating from A to B or from B to A, the transition isn't very nice looking. The nav-bar juts appears or disappears instead of sliding in and out with the content.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @andrewmcgivery!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.

**Comment by andrewmcgivery** [comment]
Why was this closed?

**Comment by andrewmcgivery** [comment]
Bump?

@ajoslin?

**Comment by adamdbradley** [comment]
With today's navbar/navview relationship it isn't as easy as changing some css, especially when you consider all the nested navbars/navviews/tabs/sidemenus.

Is this something to work on in our refactors, but its not a bug. To have the entire bar slide in, and not just the content of the bar, is a refactor or the entire navigation system. Additionally it's going to greatly affect margin tops of the entire stack, and when and when not to apply a margin top on content, and add even more z-index complexity (the nav-bar does not sit within the nav-view).

And after all that, there's few scenarios of good usability where a navbar should keep showing and hiding. This is something we'll address in our next major release, but this isn't a bug, it's a feature request.

**Comment by andrewmcgivery** [comment]
@adamdbradley Fair response. Thanks. :)
