### ISSUE TITLE
bug: error in sass :focus should be \:focus

### ISSUE THREAD

**Issue by dcsan** [driftyco/ionic#3100]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was trying to convert the sass to stylus and got this error:

```
stylesheets/_reset.sass:93: 
Invalid property: ":focus," (no value). (Sass::SyntaxError)
If ":focus," should be a selector, use "\:focus," instead.
```

after making that change converter ran fine, so assume its a valid validation error.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Did you see this issue when running the converter or when you would compile the scss?

**Comment by dcsan** [comment]
when running the converter. 

I was trying to convert ionic to stylus as sass build chain (with meteorJS) has too many problems (libsass has windows and mac issues, ruby has its own gem/env issues). 
https://github.com/dcsan/ionic-sass/tree/master/stylus

I don't suppose ionic team is considering moving to stylus in future?

**Comment by mhartington** [comment]
We're pretty set on scss. 
Closing this as it is not an actual issue with the frameworl
