### ISSUE TITLE
bug: deviceready has not fired after 5 seconds

### ISSUE THREAD

**Issue by mccob** [driftyco/ionic#3108]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>With last stable versions of crosswalk, ionic and cordova, got "deviceready has not fired after 5 seconds" error
and Cordova API are unusable.</span>

<span is-issue-template></span>

Crosswalk developer say to open bug on ionic tracker : https://crosswalk-project.org/jira/browse/XWALK-3345

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#259
