### ISSUE TITLE
Add ability to remove back button

### ISSUE THREAD

**Issue by stevebooks** [driftyco/ionic#312]
When clicking on certain pages, it would be nice to be able to disable the back button. 

For a particular page, I might want to change the text to "Done", or something else.

**Comment by DVTechiNFO** [comment]
<ion-view title="DVTECH iNFO"  hide-back-button="true">

**Comment by DVTechiNFO** [comment]
<ion-view title="DVTECH"  hide-back-button="true">

**Comment by pbajno** [comment]
Is there still any solution for this? I don't see why this issue could be closed.
