### ISSUE TITLE
perf: Regression regarding responsiveness with list

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#3126]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I noticed an important regression using latest Nightly Build.

Check out this codepen:

http://codepen.io/mica16/pen/MYQXEL

It's a simple list that displays the "detail" when clicking on an item. 
At first glance, using nightly, it's great.

Now you know that users are very impatient and clicks very very quickly on the next item when going back to list, before view transition finishes.

With the same codepen, try this:

Click on the item you want.
Then go back through and QUICKLY click on any item you want (why not the first one), really quickly, before the page finishes the whole transition. You will notice that...you can't (your click won't have any effect), you HAVE TO wait for the transition to finish.
Now, replace this (in the "head" markup) : 
http://code.ionicframework.com/nightly/js/ionic.bundle.js
by this, (in the same codepen):
http://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js

and test again the scenario.

You will notice that using the beta 14-release, the click is FAR MORE responsive. 
Indeed, when going back from "detail" to list, you can click VERY QUICKLY on any item you want and the corresponding detail opens, without having to wait for the full page transition from "detail" to "list".

Any idea of the cause?
It's annoying, since I really like some fixes involved by the nightly build.
I just can't use it right now..., because I'm pretty sure that all my users would complain about this issue.

Thanks a lot,

Michael</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
If you're able to click really fast you can get ugly black screens and flickers. Additionally, the click block is preventing unwanted happening from the 300ms delay click sent by the phone. So while it's transitioning, at 300ms it'll fire off another click at the same area, and if the transitioning view has an input it'll receive focus, or could open up a modal etc. We're going to try disabling clicking during the transition.

**Comment by mica16** [comment]
I never noticed "unwanted happening" by clicking so fast. 
It was really responsive IMHO.
