### ISSUE TITLE
bug: collection-repeat: 2px border between items

### ISSUE THREAD

**Issue by osahner** [driftyco/ionic#3130]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>collection-repeat (nightly) adds an 2px border between the items.

http://codepen.io/osahner/pen/PwRYgR

does not happen with version 1.0.0-beta.14.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Funny you bring that up, we JUST fixed that in a branch and should be hitting master very soon. It'll be fixed in the next release, thanks.

**Comment by osahner** [comment]
still an issue. any eta?

**Comment by anonrig** [comment]
Still an issue.
