### ISSUE TITLE
bug: Ionic-1.0.0-beta14 - Missing title when switching views

### ISSUE THREAD

**Issue by revie** [driftyco/ionic#3132]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm running into an issue with beta14 where, when switching to a new view for the first time, the title of the view isn't showing up.  It works if I browse around and come back to the view, just not the first time the view is loaded.  For reference, the title is a scope variable, and not static, and the problem only started appearing with beta14 (and worked fine in beta13 and below).

I've discussed the issue in the Forum, and @mhartington suggested that this could be an issue with how the data is loaded for the view.  I am using $ionicView.beforeEnter to trigger the data load, which I understand is the recommended event to trigger a data load if I want the data to be loaded by the time the view is entered.

My guess is that there is a timing issue within the view logic in Ionic where the template is loaded when the variable is null (since the data hasn't been loaded yet), but the watchers added to the scope variables are being added *after* the scope variable is being changed.  Meaning, somewhere between when the template is loaded and the scope variables are "watched", the data loading logic in my $ionicView.beforeEnter routine sets the variable, and since the watcher isn't set until after the data is loaded, the template isn't seeing the change and shows the null value instead.

Forum:
http://forum.ionicframework.com/t/missing-title-when-switching-views-in-beta14/17596/4

beta13: http://codepen.io/revie/pen/VYQRrX
beta14: http://codepen.io/revie/pen/emVmgM
latest: http://codepen.io/mhartington/pen/NPygLP

To reproduce the problem in the Codepens listed above:
1. Open side menu
2. Click on "Decepticons"
3. Title of view should be "Decepticons", not blank</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @revie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3132). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3132)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Looking at this now...

**Comment by revie** [comment]
I think I can prove that the problem is a timing issue somewhere in Ionic.  In this codepen, using the nightly release, I added a delay for when I start loading the data for the view in question.  The delay pauses the loading of the data long enough to wait for Ionic to set the watchers on the scope variables, making the title show up correctly:

http://codepen.io/revie/pen/Wbzwxd

Now that we know it's a timing issue, the real trick is to track down where to start.  My guess is that just before the template is "compiled" and watchers assigned, possibly take a snapshot of the scope and then once each watcher is set, check to see if the scope has changed?  Would only need to be done on initialization, so hopefully it wouldn't be too much of an impact on memory.  Or, maybe there's a more elegant way to handle this?

**Comment by mhartington** [comment]
I could be wrong, but I don't think its a time issue on ionic's end, but a race condition in your promises.

**Comment by mhartington** [comment]
So I reworked it a little bit...
But the title appears all the time now.

http://codepen.io/mhartington/pen/GgxZBv?editors=001

**Comment by revie** [comment]
Thanks @mhartington.  Your example shows that my assumption about Ionic's controller caching was wrong.  I had assumed a Singleton-type of caching setup, but looks like caching is done on a URL-type basis.

However, it looks like we were both looking at the wrong thing.  Turns out it had nothing to do with loading of the data, but rather when the scope variables are defined.  I was treating $ionicView.loaded as my "init()" method, but on first load, the scope watchers were apparently being set before $ionicView.loaded was triggered.  And since watchers appear to only be set when a scope variable is defined, it was skipping the variable that sets the title in my case.

Simply removing the scope variable declaration outside of $ionicView.loaded was all that was needed here.  No need to go overboard and load all of the view's data synchronously on initialization.  Example:

http://codepen.io/revie/pen/YPaZKJ

I had assumed that where the documentation said that $ionicView.loaded "is a good place to put your setup code for the view" meant that's the best place to initialize my scope variables, but apparently not.

Thanks for the help.

**Comment by mhartington** [comment]
Makes sense. Alright, I'll clean up the documentation for the view events.
