### ISSUE TITLE
Scroller doesn't scroll down enough for input

### ISSUE THREAD

**Issue by lingz** [driftyco/ionic#314]
![screenshot_2013-12-11-23-33-11](https://f.cloud.github.com/assets/3147213/1727182/2d1f1a8e-629b-11e3-9759-75142b7e41a8.png)

The scroller in content doesn't go far down enough to see the input field that I am trying to enter into.

**Comment by mdsEu** [comment]
the bug persists in ios?

**Comment by sebrojas14** [comment]
Why the cordova issue appears resolver? https://issues.apache.org/jira/browse/CB-4404
