### ISSUE TITLE
feat: $ionicBackdrop Holds and $ionicLoading

### ISSUE THREAD

**Issue by spectravp** [driftyco/ionic#3140]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicBackdrop should add the following functionality:

1) It is possible to have -50 holds. This can make it impossible to get the backdrop to show. Should check to make sure that the hold count is never below zero. 
2) Should have a handler to force it close no matter how many holds their may be, resetting holds to zero.

$ionicLoading should have an optional callback handler to use with duration property that is called when the $ionicLoading instance auto-hides itself. At the very least, it should emit an event.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @spectravp!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
