### ISSUE TITLE
bug: ion-nav-bar behaves incorrectly with content insid

### ISSUE THREAD

**Issue by djhr** [driftyco/ionic#3146]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,

After update ionic to beta-14, I notice that ion-nav-bar is not behaving correctly when has content inside (like buttons, inputs, etc...).

See here an example:
http://codepen.io/anon/pen/wBmrze

Look at the following ionic css lines:
```
6968: [nav-bar-transition="ios"] [nav-bar="cached"] { display: block; }
7001: [nav-view="cached"], [nav-bar="cached"] { display: none; }
```
Both rules will be applied to the element `<div class="nav-bar-block" nav-bar="cached">`, and since "display: block" is defined first, it will be applied.

Cheers,
Daniel</span>

<span is-issue-template></span>

**Comment by djhr** [comment]
The element that I was referring, and is not showing is:
div class="nav-bar-block" nav-bar="cached"
Apparently github doesn't like html code...

**Comment by mhartington** [comment]
Not the purpose of the nav-bar. It should have content added to it via `ion-nav-buttons` 

http://codepen.io/mhartington/pen/JoZOEo

For your codepen, and ion-header-bar will do.
