### ISSUE TITLE
bug: ion-content scroll=false

### ISSUE THREAD

**Issue by djhr** [driftyco/ionic#3147]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,

After update ionic to beta-14, I notice that ion-content with scroll=false is overlapping the header.

See here an example:
http://codepen.io/anon/pen/MYVEEP

Look at the following ionic css line:
2234: .scroll-content-false, .menu .scroll-content.scroll-content-false { z-index: 11; }
2723: .bar { [...] z-index: 9; [...] }

I think the content z-index shouldn't be bigger that the bar z-index.

Cheers,
Daniel</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The issue is you are using a div with out applying the class has-header to the ion-content, or you are not using an ion-header-bar.


http://codepen.io/mhartington/pen/radgog
