### ISSUE TITLE
ionic emulate ios stderr stdout

### ISSUE THREAD

**Issue by tiagonbotelho** [driftyco/ionic#3151]
I just started using ionic and i just did the default settings with these steps:
->mkdir new_project;
->go to the folder and run cordova create . ;
->ionic start myApp sidemenu;
->cd myApp;
->ionic platform add ios;
-> ionic build ios;
->ionic emulate ios;

when i run the last command i noticed i missed ios-sim so i installed it but when i ran emulate again it gave me an error although it opened the simulation window:

Error:

Running command: /Users/tiagobotelho/ionic_start/hooks/after_prepare/010_add_platform_class.js /Users/tiagobotelho/ionic_start
add to body class: platform-ios
Running command: /Users/tiagobotelho/ionic_start/hooks/after_prepare/020_remove_sass_from_platforms.js /Users/tiagobotelho/ionic_start
Running command: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/run --emulator
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.1
    SHARED_PRECOMPS_DIR = /Users/tiagobotelho/ionic_start/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET HelloCordova OF PROJECT HelloCordova WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    /bin/sh -c /Users/tiagobotelho/ionic_start/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Script-304B58A110DAC018002A0835.sh

real	0m0.082s
user	0m0.028s
sys	0m0.048s

ProcessInfoPlistFile build/emulator/HelloCordova.app/Info.plist HelloCordova/HelloCordova-Info.plist
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    builtin-infoPlistUtility /Users/tiagobotelho/ionic_start/platforms/ios/HelloCordova/HelloCordova-Info.plist -genpkginfo /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/tiagobotelho/ionic_start/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/MainViewController-PartialInfo.plist -o /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/Info.plist

GenerateDSYMFile build/emulator/HelloCordova.app.dSYM build/emulator/HelloCordova.app/HelloCordova
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/HelloCordova -o /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app.dSYM

Touch build/emulator/HelloCordova.app
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    /usr/bin/touch -c /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app

** BUILD SUCCEEDED **

2015-02-19 10:09:26.560 ios-sim[20818:657130] stderrPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log
2015-02-19 10:09:26.561 ios-sim[20818:657130] stdoutPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log

**Comment by Ionitron** [comment]
Greetings @tiagonbotelho!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3151). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3151)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
