### ISSUE TITLE
bug: ionic emulate ios stderr stdout

### ISSUE THREAD

**Issue by tiagonbotelho** [driftyco/ionic#3152]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I just started using ionic and i just did the default settings with these steps:
->mkdir new_project;
->go to the folder and run cordova create . ;
->ionic start myApp sidemenu;
->cd myApp;
->ionic platform add ios;
-> ionic build ios;
->ionic emulate ios;

when i run the last command i noticed i missed ios-sim so i installed it but when i ran emulate again it gave me an error although it opened the simulation window:

Error:

Running command: /Users/tiagobotelho/ionic_start/hooks/after_prepare/010_add_platform_class.js /Users/tiagobotelho/ionic_start
add to body class: platform-ios
Running command: /Users/tiagobotelho/ionic_start/hooks/after_prepare/020_remove_sass_from_platforms.js /Users/tiagobotelho/ionic_start
Running command: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/run --emulator
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.1
    SHARED_PRECOMPS_DIR = /Users/tiagobotelho/ionic_start/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET HelloCordova OF PROJECT HelloCordova WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Script-304B58A110DAC018002A0835.sh
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    /bin/sh -c /Users/tiagobotelho/ionic_start/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Script-304B58A110DAC018002A0835.sh

real	0m0.066s
user	0m0.023s
sys	0m0.037s

ProcessInfoPlistFile build/emulator/HelloCordova.app/Info.plist HelloCordova/HelloCordova-Info.plist
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    builtin-infoPlistUtility /Users/tiagobotelho/ionic_start/platforms/ios/HelloCordova/HelloCordova-Info.plist -genpkginfo /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/tiagobotelho/ionic_start/platforms/ios/build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/MainViewController-PartialInfo.plist -o /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/Info.plist

GenerateDSYMFile build/emulator/HelloCordova.app.dSYM build/emulator/HelloCordova.app/HelloCordova
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app/HelloCordova -o /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app.dSYM

Touch build/emulator/HelloCordova.app
    cd /Users/tiagobotelho/ionic_start/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0/bin:/Users/tiagobotelho/.rvm/gems/ruby-2.2.0@global/bin:/Users/tiagobotelho/.rvm/rubies/ruby-2.2.0/bin:/Users/tiagobotelho/.gem/ruby/2.1.1/bin:/Users/tiagobotelho/.rubies/2.1.1/lib/ruby/gems/2.1.0/bin:/Users/tiagobotelho/.rubies/2.1.1/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/tiagobotelho/.rvm/bin"
    /usr/bin/touch -c /Users/tiagobotelho/ionic_start/platforms/ios/build/emulator/HelloCordova.app

** BUILD SUCCEEDED **

2015-02-19 10:40:11.836 ios-sim[21372:676013] stderrPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log
2015-02-19 10:40:11.837 ios-sim[21372:676013] stdoutPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log
Session could not be started: Error Domain=FBSOpenApplicationErrorDomain Code=4 "Unable to run app in Simulator" UserInfo=0x7f99a8f43fd0 {NSUnderlyingError=0x7f99a8e0de70 "The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)", NSLocalizedFailureReason=An error was encountered while running (Domain = FBSOpenApplicationErrorDomain, Code = 4), NSLocalizedDescription=Unable to run app in Simulator}
Error: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/run: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by tiagonbotelho** [comment]
Ok i started a new project to try it out and the simulation worked although it still gives me:

2015-02-19 10:09:26.560 ios-sim[20818:657130] stderrPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log
2015-02-19 10:09:26.561 ios-sim[20818:657130] stdoutPath: /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log

I'm just wondering what could it be that is causing this problem! Thank you!

**Comment by jbavari** [comment]
It looks like it was some error spawning from ios-sim or ios-deploy on its first run.

I've seen it before.

Those outputs are for you to run `tail -f /Users/tiagobotelho/ionic_start/platforms/ios/cordova/console.log` to tail the log from the ios platform.

**Comment by leonprou** [comment]
Had the same problem
(I think the update to newer version of ionic-cli was the cause)

This worked for me:
http://stackoverflow.com/a/25968057/942899
