### ISSUE TITLE
perf: Slow visual feedback on button active css state

### ISSUE THREAD

**Issue by sp4ke** [driftyco/ionic#3158]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>crosswalk</span>

<span ionic-description>I have some custom buttons with a custom style on hover/active state with css, however ther's a long delay between the touch and the new state. 

The original ionic buttons use a .active class instead and they they feel very native on the touch. How can I reach the same visual feedback on my custom buttons ? Is there a specific event to listen to that is faster ?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
In stead of listening to hover/active states, we're adding the class of `.activated`

So target your custom buttons like so.

```css
.custom-button.activated {
  
}
```

**Comment by sp4ke** [comment]
Thanx , maybe this should be documented

**Comment by mhartington** [comment]
Already is.

http://ionicframework.com/docs/api/page/tap/

> • Adds and removes an 'activated' css class

**Comment by sp4ke** [comment]
Ok sorry about that, I missed it.


Benziane Chakib
FrontEnd Engineer
Tel: +49 176 78983903
Twitter: @sp4ke <https://twitter.com/sp4ke>
Github: sp4ke <https://github.com/sp4ke>
BTC: 18RirJMHTNDXokNb3G4ytCadnm7pdUp8vX

**Comment by Domvel** [comment]
".activated" and ":active" are both extremly delayed. -.-

**Comment by Domvel** [comment]
".activated" does not work and ":active" is too slow. boring!

**Comment by Domvel** [comment]
".activated" is also slow like ":active". Both are really terrible for user experience.
