### ISSUE TITLE
bug: Ionic is preventing D3 from rendering in chrome

### ISSUE THREAD

**Issue by dcsan** [driftyco/ionic#3159]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a game developed using d3.js but in certain browsers it will not render the svg when ionic is running.

Safari - OK
Firefox - OK
Chrome latest is broken (Version 40.0.2214.115 (64-bit)
mobile chrome - broken
Previously canary (chrome dev) was OK but seems broken now

If i rebuild the web app without ionic the game will run fine.

The game is here, and the start button should insert svg, but ionic prevents this.
http://chatu.meteor.com/pairs/ant1</span>

<span is-issue-template></span>

**Comment by dcsan** [comment]
before clicking to play:

![image](https://cloud.githubusercontent.com/assets/514002/6313035/0b1d9448-b94c-11e4-8e48-4e8cad538bf0.png)

after clicking to play, rendering prevented in chrome

![image](https://cloud.githubusercontent.com/assets/514002/6313037/146e6946-b94c-11e4-9d72-dae226310853.png)

dragging window will cause chrome to render, and the events are in the console.
![image](https://cloud.githubusercontent.com/assets/514002/6313038/38f711a0-b94c-11e4-9b57-860ccd9e360e.png)

**Comment by dcsan** [comment]
OK I switched the whole game to use the DOM renderer, but still get the same issue.

this seems to be due to repaint being prevented. and its something in ionic css.

if i drag/resize the chrome window it will repaint.

if i try to click on certain elements they are "not there" ie the green button that doesn't disappear, the console says its "display: none"

again this is "only" chrome behavior.

**Comment by mhartington** [comment]
It may be a case where you need to call `$ionicScrollDelegate.resize()` after you update the svg. Or it could be d3, which has some rendering problems with angular. Can't test it out since the links been updated. Any chance you could provide an example again?

**Comment by dcsan** [comment]
thanks for the tips, i'll try that. fwiw i'm using a [meteor port of ionic](https://github.com/meteoric/meteor-ionic), which has probably not ported the `$ionicScrollDelegate.resize()`. I'll have to look into what that does. But it seems to be the CSS that's causing the trouble. 

the link is still live here, and works in canary but not current chrome. in chrome, the green button will never go away when you click "Let's play"

http://chatu.meteor.com/pairs/ant1

**Comment by dcsan** [comment]
hmm, [$ionicScrollDelegate.resize() ](https://github.com/driftyco/ionic/blob/9a88c4179df87046bc993cd66089ab99411be539/js/angular/service/scrollDelegate.js#L67) just looks like a stub function, is [this](https://github.com/driftyco/ionic/blob/bb866da3d7e539c8923bd6914c0a4e44f0f4d400/js/angular/controller/scrollController.js#L99-L103) the actual implementation?

**Comment by mhartington** [comment]
Hmm, just tried the link again in chrome, and it seems to be working fine for me.
If you are using the meter port of ionic, maybe you should open the issue in their repo.

**Comment by dcsan** [comment]
the renderering is still definitely not working in chrome 
40.0.2214.115 
but works in canary (42.x)

the various nodes are in the DOM, can be selected in the debugger, and are even receiving events, but do not render visibly:

![image](https://cloud.githubusercontent.com/assets/514002/6513589/d27869d0-c330-11e4-97d6-842b98b4c3df.png)

I went through the various ionic.scss files to try and comment out to narrow down the issue, but the behavior is random. sometimes it renders and sometimes it doesn't even with the same config of files being included. i think this maybe something to do with the lib-sass compiler caching or not cleaning files, but it makes it really hard to debug.

One guess is that it's related to the SVG being a large graphic, which is full screen, and the overflow-hidden you have in the html tag is forcing all the content to not render. I tried removing those but wasn't able to get a good result.

**Comment by dcsan** [comment]
update seems to work in chrome 41 which appears to have shipped.

however, it's not working on mobile chrome, which is the main killer.

**Comment by mhartington** [comment]
Okay, just to make sure nothings changed with this, was this an issue on meteor's said or were able to get the same issue with ionic/angular?

**Comment by Ionitron** [comment]
Greetings @dcsan!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @dcsan!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by dcsan** [comment]
this seemed to be a bug in the mobile chrome renderer, which appears to have just fixed itself when mobile browser caught up with the desktop render engine.

**Comment by marcsyp** [comment]
I am still having this problem in Ionic 1.0.0 RC5 + latest chrome browser (46.0.2490.71 m).  I can see the elements in the DOM but not on the page.  Furthermore, circles that are generated by D3 have a proper size in the tag but are showing up as 0x0px in the element inspector.
