### ISSUE TITLE
feat: How can i use this framework with WordPress ?

### ISSUE THREAD

**Issue by Umakant-DM** [driftyco/ionic#3162]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,
I want to Use your framework to make a WordPress Website using your framework . Please give me any type of help regrading my issue.

Thanks
Umakant</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Not something that we are focusing on, but Apppresser is an option.

http://apppresser.com/intro-ionic-framework/
