### ISSUE TITLE
bug: $ionicPlatform.ready dont fire

### ISSUE THREAD

**Issue by ag-secret** [driftyco/ionic#3163]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a controller called `RateProfilesCtrl`, I'm using a promise that resolves when `$ionicPlatform.ready` is ready.

The issue is, if I go to `RateProfilesCrl` clicking in a link like `<a href="#/tab/rate-profiles">GO!</a>` works perfectly, but if I go to this by `$location.path('/tab/rate-profiles')` the `$ionicPlatform.ready` never resolves.

Some information:

1 - The app was generated by `ionic start myProject tabs` so all the routes that I make was writed with the same code pattern.
2 - I'm running on Asus Zenfone 5 Android 4.4.2

Another strange thing, If I write `console.log('here!')` in the beginning of `RateProfilesCtrl` and go to this controller using `<a href="#/tab/rate-profiles"...` it executes once, but when I go using `$location.path('/tab/rate-profiles')` it executes twice.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you provide a codepen that can simulate this?

**Comment by Ionitron** [comment]
Greetings @ag-secret!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @ag-secret!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
