### ISSUE TITLE
bug: $ionicHistory.currentView() is wrong

### ISSUE THREAD

**Issue by isabo** [driftyco/ionic#3164]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See the console log output here: http://codepen.io/anon/pen/PwejPO

In Beta 14 $ionicHistory.stateName should be identical to $ionicHistory.currentView().stateName, but the latter consistently lags behind by one step.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
You should be using the lifecycle events as of beta14: http://ionicframework.com/docs/api/directive/ionView/

**Comment by rainboxx** [comment]
@Ionitron This doesn't seem to fit here...
