### ISSUE TITLE
bug: Collection-repeat add multiple css classes to elem

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3167]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Description
=========
I use collection repeat with a filter. I styled the items with colors using CSS. When the view is resized (keyboard show/hide) or a browser windows resized, some items get random classes from some other item. Like if the item div is reused to show another item without clearing the classes that was there.

The problem is not present in beta 13.

Here's a snippet from the template:

    <div class="item collection-item {{item.type}}" ng-class="{'item-divider': item.isDivider}" ... >

      <div class="category-marker {{item.type}}"></div>
      ...
    </div>

`item.type` are color names. In css:

    .item-divider.brown {
      background-color: #765200;
      color: white; }

    .item-divider.blue {
      background-color: #0a577b;
      color: white; } 

    ...

    .category-marker {
      position: absolute;
      height: 100%;
      width: 5px;
      left: 0px; }

    .category-marker.brown {
      background-color: #c28900; }

    .category-marker.blue {
      background-color: #0f89c2; }

    ...

Searching break the DOM then closing the search breaks it even more : 

<img src="http://ionic-forum-uploads.s3.amazonaws.com/9246ac826c7db81d11ebbd716237da994b9a64e5434e.png" width="281" height="500">

Looking at the DOM, I get the following for the blue1 item. **see, the the `{{item.type}}` is expanded to blue and green ???** Plus item-divider is added while the data behind this says it is not:
    
    <div class="item collection-item green item-divider blue"  ...>
        <div class="category-marker brown"></div>
              blue1
              ...
    </div>

Here's the value of item for blue1:

    {
      isDivider: false,
      name: "blue1",
      type: "blue"
    }

See a sample app showing the bug here:
https://github.com/kristianbenoit/collection-repeat-css-bug

I can see the bug in chromium and firefox on desktop by resizing the window / filtering, but it's harder to trigger.

```
ionic info :

OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.1 LTS 
Node Version: v0.10.25
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.10
```

also tried on iOS :

```
our system information:

OS: Mac OS X Yosemite
Node Version: v0.12.0
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.11
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1
```

Resubmission
===========
This is a resubmission from the ionic framework web page. It is hard to trigger the bug in a browser, but I did trigger it in chrome, firefox, and safari. I just added a codepen showing the bug: http://codepen.io/kbenoit/pen/WbJZyd

To trigger the bug, filter with something "bl", resize the window, then flush the filter (click on X).</span>

<span is-issue-template></span>

**Comment by kristianbenoit** [comment]
@adamdbradley Seems you changed something related between beta13 and beta14. (3ddaf34722054bde9c14c6f28f840fe10845a343)

**Comment by mhartington** [comment]
Collection repeat is getting some work done for the next release so once its made its way in to master, please give it a try and see if the problem still exist. I'll let you know when it hits master.

**Comment by mhartington** [comment]
Please try the nightly builds

**Comment by ajoslin** [comment]
Not seeing the problem in the latest nightly: http://codepen.io/ionic/pen/LErZgx

**Comment by ajoslin** [comment]
Also check out the code, collection-repeat requires you to fill in a lot less now.

**Comment by kristianbenoit** [comment]
Thanks, that fixed the issue of having css class doubled.

It works fine and smooth in browser, but on devices, Android at least (Nexus 5 on Lollipop and Galaxy s3 on Kitkat), it is really slow. I counted the number of items loaded in the DOM and all items seems to be loaded ... Plus some more since another bug seems to double some dom elements which I thought was related. Another most likely related to that second problem is that height get mixed up between divider and non divider... Those items seems to be there multiple time in the DOM. I'll file an issue for this.

**Comment by ajoslin** [comment]
Ok, the default render buffer is 10 before and 10 after in the newest
version. That may be hurting android performance.

Can you try setting 'item-render-buffer="0"' on your repeat and test the
performance?

**Comment by kristianbenoit** [comment]
I tried that, it is definitely faster on Nexus 5 Lollipop, it load 29 elements compared to 49 without item-render-buffer="0". The screen is big enough to show at most 10 elements, 8 with the headers/tabs. It is usable with 29 elements, but not with 49 which does not seems so many and by not usable I mean really slow.

On the Galaxy S3, it load 277 elements in the DOM compared to 297 without item-render-buffer="0". Which you can guess don't make that much of a difference. What's weird is there is only 245 elements in the list provisioning the collection-repeat.

**Comment by ajoslin** [comment]
Wow! It should not be loading anywhere near that many. There's a flaw in my
calculations.

**Comment by ajoslin** [comment]
I'll push a fix and get back to you.

**Comment by ajoslin** [comment]
@kristianbenoit so when it's loading 277 elements, how many items should there be on screen?

**Comment by kristianbenoit** [comment]
There should be about 8 or 9 and 12 if the list is the only content of the webview.

**Comment by kristianbenoit** [comment]
I tried to isolate the problem, I did in one situation, but applying the same solution to another application does not always fix it.

Here's a pen http://codepen.io/kbenoit/pen/MYBJGL

placing that code in an application and running it on Samsung Galaxy S3 (i747) running stock 4.4.2. Works fine.

Moving the templates from the index.html to their own files breaks the collection-repeat which loads way too many items. This is on the same device.

**Comment by ajoslin** [comment]
Ok, I have a suspicion here. I'll test it out some more.

**Comment by ajoslin** [comment]
So it breaks if you just put the whole ion-view template into its own file?

**Comment by kristianbenoit** [comment]
Yes, to be precise, when I move the 2 templates in their own files.

**Comment by ajoslin** [comment]
Does it fix itself once you rotate the phone?

**Comment by ajoslin** [comment]
Also, can you take out the try/catch in your getItemHeight function?

**Comment by kristianbenoit** [comment]
Well I went to try rotating, the code I provided above, but I was running fine. I tried with my app and it is also working. So it seems it's fixed in the latest nightly ! :)

Thanks !

**Comment by ajoslin** [comment]
Woohoo! Huge news. Thank you.

**Comment by kristianbenoit** [comment]
Well, I might have called victory a bit too fast. The multiple classes is still present in rc0 and rc1, but much harder to trigger.  Here's a screenshot running 1.0.0-rc.1.

![screenshot](https://dl.dropboxusercontent.com/u/39729597/Capture%20d%E2%80%99%C3%A9cran%202015-03-25%20%C3%A0%2012.06.47.png)

**Comment by kristianbenoit** [comment]
@ajoslin can you reopen this, or I should file a new issue ?

**Comment by escmaster** [comment]
Thank you... you save my ass here!!!

**Comment by bymodude** [comment]
also having the same multiple classes issues here, please re-open this issue

**Comment by mhartington** [comment]
Please open a new issue.

**Comment by iMuzz** [comment]
I'm having the same issue. Was this ever resolved?
