### ISSUE TITLE
feat: Allow custom anchor in anchorScroll

### ISSUE THREAD

**Issue by insraq** [driftyco/ionic#3168]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently, $ionicScrollDelegate.anchorScroll([shouldAnimate]) reads from location.hash. However, it could be quite useful to allow scrolling to custom id.

e.g. $ionicScrollDelegate.anchorScroll('#my-id', true)

It should be relatively easy to add this feature (https://github.com/driftyco/ionic/blob/master/js/angular/controller/scrollController.js#L141)</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
So with how angular handles anchorScrolling, not sure if this will be possible.
Angular needs to have ids passed to the location.hash.

https://docs.angularjs.org/api/ng/service/$anchorScroll

http://codepen.io/mhartington/pen/FmyaB

You can, though just pass the location in the function. 

```
$scope.slideTo = function() {
    $location.hash('two');
    $ionicScrollDelegate.$getByHandle('mainScroll').anchorScroll();
  };
```

**Comment by insraq** [comment]
I think it's possible as I've patched framework locally. Here is the code

```javascript
self.anchorScroll = function(elementId, shouldAnimate) {
    self.resize().then(function() {
      var hash = arguments.length == 2 ? elementId : $location.hash();
      var elm = hash && $document[0].getElementById(hash);
      if (!(hash && elm)) {
        scrollView.scrollTo(0,0, !!shouldAnimate);
        return;
      }
      var curElm = elm;
      var scrollLeft = 0, scrollTop = 0, levelsClimbed = 0;
      do {
        if (curElm !== null) scrollLeft += curElm.offsetLeft;
        if (curElm !== null) scrollTop += curElm.offsetTop;
        curElm = curElm.offsetParent;
        levelsClimbed++;
      } while (curElm.attributes != self.element.attributes && curElm.offsetParent);
      scrollView.scrollTo(scrollLeft, scrollTop, !!shouldAnimate);
    });
  };
```

**Comment by lothar7** [comment]
that is a total lifesaver not polluting the hash. There is perhaps a bug in ionic that means setting the hash before anchorscroll causes ui router to use the default route etc etc. Using this fix solves with my problem. Although I had to change line 3 to
var hash = elementId || $location.hash();
