### ISSUE TITLE
bug: unreachable code in ionic.activator.start.  ion-item's without ng-click cant get activated class

### ISSUE THREAD

**Issue by djett41** [driftyco/ionic#3170]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ion-item directives without ng-click, or other HTML elements with an item class that are NOT anchors or buttons will not receive the activated class on mouse/tap down/move events.

In the ionic.activator.start method line 3100 in beta14, if any condition is met that set's the eleToActivate variable, the for loop is broken out of, therefore even if your element or element's parent contains the .item class, the code below will never evaluate to true (eleToActivate will always be undefined)

```javascript
if (eleToActivate && ele.classList.contains('item')) {
  eleToActivate = ele;
  break;
}
```

Removing the check for eleToActivate should resolve the issue</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @djett41!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3170). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3170)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So if they're not elements that you can tap, then why provide any visual feed back? 
I don't really see any point to this to be honest. From a usability standpoint, it would create confusion as to whats a button and what not.

**Comment by djett41** [comment]
@mhartington maybe I was unclear.  These are definitely tappable elements

1.  Suppose you had a ion-item or a directive with the item class, and you want it to get the activated class, but wanted to implement an touch event handler other than ng-click, or say you just used jquery lite to implement the click handler in the directive.....  The element would never get the activated class. 
 
2.  The line of code i'm referring actually includes the check (looks for .item class) which would allow #1 to get the activated class.  The problem is that the first part of the condition (check is eleToActivate is defined) will NEVER BE TRUE therefore the code for the condition is unreachable.  So even if you decided that you don't want to give user's the flexibility and want to restrict them to using ng-click for items... you still have unreachable code in your codebase.

**Comment by djett41** [comment]
@mhartington  the following issue is related to exactly what I am saying.  https://github.com/driftyco/ionic/issues/3050

Removing the check for eleToActivate in line 3100 in beta14 ionic.js, would allow @sgon00 to be able to use ion-item with href and still get the activated class, rather than being forced to use ng-click as he described in his example.

**Comment by mhartington** [comment]
Will pass this to @adamdbradley

**Comment by PerfectionCSGO** [comment]
This is in ionic.bundle.js 1.2.0 at line 3222

          var eleToActivate;
          //Two lines omitted
          if (eleToActivate && ele.classList && ele.classList.contains('item')) {
            eleToActivate = ele;
            break;
          }

If this helps any.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
