### ISSUE TITLE
bug: Multiple popover have all the same scope since beta.14

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3173]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If there is multiple popover in the same page, for example in a list, they all get the same scope.

The problem is not present when using beta13, but is in beta.14 and rc.0.

Remove one popover and you can't open the other ones ... (reopen the same one)

Here's a pen that show the bug.:
http://codepen.io/kbenoit/pen/OPZoeV</span>

<span is-issue-template></span>

**Comment by kristianbenoit** [comment]
Here's a workaround, it implies creating the popover just in time and removing it when it is hidden:
http://codepen.io/kbenoit/pen/emrPdr

**Comment by alejandromagnorsky** [comment]
+1. Was quite hard to detect what was going on exactly.

**Comment by sirhoe** [comment]
+1, Please look into this.

**Comment by alejandromagnorsky** [comment]
I tried again @kristianbenoit solution, but now is not even working in his codepen if we update to ionic.rc.3.
Please, this was working before until beta.14 was released...

**Comment by NutBoltu** [comment]
+1

**Comment by kristianbenoit** [comment]
I confirm the workaround I proposed does not work anymore in 1.0.0-rc.3 and nightly.

**Comment by YongdeCHEN** [comment]
+1, Someone know the solution for the bug?

**Comment by kristianbenoit** [comment]
@YongdeCHEN, so far use my work around with ionic-1.0.0-rc.2

**Comment by alejandromagnorsky** [comment]
@brodykidd, this is the issue I mentioned in the email ;)
Just in case you need to update the status.

**Comment by asanin-2sol** [comment]
+1

**Comment by liyo** [comment]
could this issue also be related? http://codepen.io/anon/pen/yNPmvL

**Comment by kristianbenoit** [comment]
@liyo, that's the same problem. Using the solution I provided above should fix your problem (create the popover in the ng-click handler).

**Comment by alejandromagnorsky** [comment]
@kristianbenoit, what about version 1.0.0? Your solution doesn't work with the "stable" version, right?
Thanks anyway.

**Comment by alejandromagnorsky** [comment]
@kristianbenoit, actually I tried your method with the latest version and it worked! Great, thanks.

**Comment by liyo** [comment]
@kristianbenoit thank you, I was able to make it work with the latest Ionic version and your method. To avoid an infinite loop when popovers were removed on hide (because for some reason popover.hidden is still firing on remove), I had to manually remove the popover backdrop DOM elements manually, see: http://codepen.io/liyo/pen/XbZreg

**Comment by kristianbenoit** [comment]
@alejandromagnorsky, as @liyo says, there is an issue involving an infinite loop in the previous solution, where we call `popover.remove` while on `"popover.hidden"`, at this point the popover is not hidden yet so on `"popover.hidden"` is called again. Solution, call `stopListening()` before `popover.remove`.

    $scope.$on('popover.hidden', function() {
          stopListening();
          popover.remove();
    });

Here's a pen with the working solution.

http://codepen.io/kbenoit/pen/BNVomX

**Comment by kristianbenoit** [comment]
@liyo, the pen you provided, does not remove the popover (it's leaking DOM elements). Did you forget to click save ?

**Comment by liyo** [comment]
@kristianbenoit yes indeed I forgot to save, I have updated it now just for reference. 
Anyway, your new solution works great and there is no need to do a manual DOM removal of popover elements. Thank you!

**Comment by digitalu** [comment]
This works great. However, the weird thing is that it doesn't appear to work in ionic view, but it works in `ionic serve` and the emulator.

**Comment by digitalu** [comment]
Nevermind. Solution works fine. I realized that my reference to my template was wrong. I named it `popOver.html` and didn't realize that my URL was pointing to `popover.html`... :cry:

**Comment by shaoner** [comment]
Hi,

I've just had the same issue.
It seems to be related on how the template urls are handled by ionic ($ionicTemplateLoader actually).
When using $ionicPopover.fromTemplateUrl, the popover modal is returned after $ionicTemplateLoader.load is done getting the template. Loading the same url multiple times at the same time returns the same unique promise and therefore a single modal I suppose.

Another simple workaround is to use the angular template system (taking advantage of the templateCache).

So instead of doing:

```js
$ionicPopover.fromTemplateUrl('mytemplate.html', { scope: $scope })
    .then(function(popover) {
        $scope.popover = popover;
    });
```

By injecting $templateRequest:

```js
$templateRequest('mytemplate.html')
    .then(function (tmpl) {
         $scope.popover = $ionicPopover.fromTemplate(tmpl, { scope: $scope });
    });
```

PS: I haven't tried but I'm pretty sure this issue also happens with $ionicModal
