### ISSUE TITLE
bug: Lifecycle leave events firing in wrong controller

### ISSUE THREAD

**Issue by madgrizzle** [driftyco/ionic#3177]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Github issue 2869 was recently closed with an update to the nightly. However, the fix seems to be firing the events in the wrong controller. I created a codepen:

http://codepen.io/anon/pen/azGGYq?editors=001

I use console.log to log all the events (before/after enter/leave) and it shows that they all (including leaves) fire from the controller associated with the tab you click on.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
The issue has been reopened.
