### ISSUE TITLE
range is not working when using side menus

### ISSUE THREAD

**Issue by mlegenhausen** [driftyco/ionic#318]
The problem is that the drag event is prevented by the side menu directives so it is not possible to slide a `range` widget via mousedown.

**Comment by WoJBurgess** [comment]
I am still seeing this in the latest build (1.0.0-beta.14) Same symptoms as described by @calendee.
Could this be to do with the fact that <code>drag-content="false"</code> is being unpredictable? (not working on all views of app)

**Comment by Pijuli** [comment]
+1 on guanxun. Keeps happening to me... drag-content="false" not fixing the issue :'(

**Comment by larpo1** [comment]
Yes - i can confirm this problem still exists and i can replicate the behaviour guanxun describes

**Comment by ariera** [comment]
i have the same problem.
i am setting the `drag-content` directive to false and that effectively prevents the side menu from being dragged but it also prevents the `range` component from being dragged more than a few pixels.

it seems that the event propagation is being stopped by the SideMenu. Commenting this line works for me:
https://github.com/driftyco/ionic/blob/ce06f6e40bdb2bc560d9241aa1ef23db4fff065f/js/angular/directive/sideMenuContent.js#L79

But I am unaware of the consequences, it might break something else, although in my particular case seems to work

**Comment by larpo1** [comment]
where do i find that line in an existing project?

**Comment by guanxun** [comment]
Good hunting, @ariera! That fixed it for me too, not noticing any apparent side effects either.

@larpo1 you can find it in existingProject/www/lib/ionic/js/ionic.bundle.js.

**Comment by ariera** [comment]
yep @larpo1 , as @guanxun points out you should find that line in the `ionic.bundle.js`
make sure that is the file you are including in your `index.html` with the `script` tag (if you are using the minimized version is probably better to switch to the normal bundle)

**Comment by shaharlinial** [comment]
Did as @ariera mentioned, no side effects ( Big project ).
nice catch.

**Comment by abailey-et** [comment]
Yup this is still an issue: http://play.ionic.io/app/7e802b9a8faf  I'm testing this on a android device and also broken in Chrome mobile emulator.

**Comment by ArTiSTiX** [comment]
Why is this issue closed ? (see #3215)

There is style a conflict between SideMenu and Range, tested on 1.0.1
With drag-content="true", dragging the range opens the side menu.
With drag-content="false", dragging the range only drag it a few pixels.

Could the issue be reopened, and the solution suggested by @ariera be implemented if as mentionned above, there is no side effects ?

It's better to have it working with unknown effects than totally buggy, isn't it ?

**Comment by ddbk** [comment]
Bump on this one. As @abailey-et and @ArTiSTiX pointed out, this is still an issue.

Commenting out <code>e.gesture.srcEvent.preventDefault();</code> under <code>function onDragX(e)</code> and adding the <code>drag-content="false"</code> directive to <code>ion-side-menu-content</code> is a temporary solution.

No side effects here either but using this hack will obviously disable slide to open/close functionality of the side menu.

**Comment by michalsnik** [comment]
@ariera +1

**Comment by ArTiSTiX** [comment]
I found a simple workaround to prevent SideMenu to conflict with Range. Maybe it is better than making a specific exception for Range inside SideMenu code:

```
(function() {"use strict";

	angular
		.module('MyApp.Directives.range', [])
		.directive('range', rangeDirective);

function rangeDirective() {
	return {
		restrict: 'C',
		link: function (scope, element, attr) {
			element.bind('touchstart mousedown', function(event) {
				event.stopPropagation();
				event.stopImmediatePropagation();
			});
		}
	};
 }
})();
```

PS: I don't think stopImmediatePropagation is necessary, but the idea is to stop propagation to let range input have its normal behaviour.

**Comment by michalsnik** [comment]
:+1:  Well this seems to be a good way too :) 
In my solution drag-content="false" is also unnecessary. I pinned this problem to SideMenu so i wrote my fix this way, i didn't want to make workarounds but hit directly source of this problem, and the source was SideMenu code that blocks further events. Hope one of solutions will be merged till next release. 
For me it's hard to tell which approach is better, both seem to do their job.

**Comment by abailey-et** [comment]
Yup confirmed, have it working here: http://play.ionic.io/app/f44b3d0adee8
Nice solution @ArTiSTiX

**Comment by ariera** [comment]
great work guys @michalsnik and @ArTiSTiX, much cleaner solution than my dirty cheap hack hahaha :D

I think your solution will really help the ionic dev team finally fix this one soon :)

**Comment by rajeshwarpatlolla** [comment]
I am still facing the issue even after using the directive mentioned above. I tested in iPhone5, with `drag-content="false"` and with out `drag-content="false"`. But no use. I can't even move the slider a bit.

**Comment by michalsnik** [comment]
@rajeshwarpatlolla Are you sure you added extra class "range" on range input or on his parent?

**Comment by rajeshwarpatlolla** [comment]
This is my html code `<input type="range" name="size" min="0" max="60" value="{{user.shoesSize}}" ng-model="user.shoesSize" class="range"/>`. I am able to swipe the range slider in PC browser but not in mobile.

**Comment by ericis** [comment]
I'm experiencing this with range and side-menus across Browser (Chrome and IE) and Native (Android and iOS).  Disabling the side menu (via drag-content="false") enables the range to work, but then I get a very inconsistent user experience.

**Comment by marcsyp** [comment]
I am still having problems with this conflict as well.  I have set drag-content="false" because I am also interacting with a D3 SVG that is pulling out side menus when it shouldn't, but now my range sliders will only respond to taps, no sliding.

**Comment by MaximShoustin** [comment]
@ArTiSTiX +1

**Comment by nskoro** [comment]
This seems to be broken again...

**Comment by NathanWalker** [comment]
@nskoro I can also report this is still broken on iOS :( Very disappointed. Trying to work through a project built with Ionic v1 and this issue is the main blocker. The issue was first reported in 2013 :(

**Comment by nskoro** [comment]
@NathanWalker yeah my workaround was to just use 

https://material.angularjs.org/latest/api/directive/mdSlider

and turn off slide for side menu

**Comment by NathanWalker** [comment]
Thank you @nskoro I'm going to try that now!

**Comment by NathanWalker** [comment]
@nskoro you're the best... worked great. MD components FTW!!

**Comment by AfonsecaO** [comment]
work for me, but i don know if that affect in other side.

Coment line 65968
on lib/ionic/js/angular-ui/ionic.bundle.js
//e.gesture.srcEvent.preventDefault();
