### ISSUE TITLE
bug: Ionic View app: Upload wont update CSS or JS

### ISSUE THREAD

**Issue by iamminn** [driftyco/ionic#3189]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After the initial upload of my app to the Ionic View app, any subsequent upload from the command line wont update the changes made to either my CSS or JS. However changes to any HTML files will be found and updated. There was a similar issue that I saw submitted but I was unable to get any resolution from the solutions that ticket provided.

Sidenote: I am using gulp to update my SASS not sure if this has anything to do with the problem.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you open this issue over here

https://github.com/driftyco/ionic-view-issues
