### ISSUE TITLE
perf: Use Controller As

### ISSUE THREAD

**Issue by AliMD** [driftyco/ionic#3197]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Could you please remove all $scope.* and use `this.*` and `prototype.*` with `controller as` method
If you want/approve i can create a pull request
Thank you in advance.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Ionic v1.x will continue to use $scope for now using controller as is a micro-optimization.
