### ISSUE TITLE
docs: Collection repeat is not working as shown in example of doc

### ISSUE THREAD

**Issue by dinesh36** [driftyco/ionic#3199]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Copying the code from the codepen for the first example getting the error as below 

Error: collection-repeat expected attribute collection-item-height to be a an expression that returns a number (in pixels) or percentage.
    at link (http://localhost:8100/lib/ionic/js/ionic.bundle.js:48566:15)
    at invokeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16019:9)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15531:11)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14887:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14890:13)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15526:24)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14887:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14890:13)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15526:24)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14887:13) </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @dinesh36!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3199). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3199)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Alexintosh** [comment]
not working for me too

**Comment by four2theizz0** [comment]
same problem here, any suggestions?

**Comment by ajoslin** [comment]
Make sure you're using the nightlies if you're copying the example from the latest blog post.

We'll be doing a full release soon.

**Comment by four2theizz0** [comment]
Perfect! Thank you very much.

**Comment by dinesh36** [comment]
Thanks for soution

**Comment by bodiam** [comment]
What's the solution now to this? I've run into the same issue, and I'm using the documentation from herE: http://ionicframework.com/docs/api/directive/collectionRepeat/, which is 1.0.0-rc.0. Thanks!

**Comment by mnewmedia** [comment]
this is because there isn't the expected default value for `collection-item-height` and they also wanted to rename 'collection-item-height' to `item-height` but till it's fixed just do it like:
```html
<ion-item collection-repeat="item in items" collection-item-height="52">
```
The `collection-item-height="52"` is the thing that is expected

**Comment by ajoslin** [comment]
If you use rc0 it works as listed in the rc0 docs. 

For beta14, check the beta14 docs.

**Comment by Bzaad** [comment]
it throws a somehow similar error on "rc.1-nightly-1153" for me too: "collection-repeat expected an array for 'posts', but got a undefined". How come ng-repeat works fine but when switching to collection-repeat it just throws this wired error?! BTW the array is defined and populated!

**Comment by adriangith** [comment]
I'm having this problem with Ionic 1.0.0. It forces me provide a value for collection-item-height, and the items are not full width.
