### ISSUE TITLE
Wrong link on the doc for codepen

### ISSUE THREAD

**Issue by dinesh36** [driftyco/ionic#3200]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Wrong link on the doc for codepen

There is wrong link for the codepen on the page http://ionicframework.com/docs/nightly/api/directive/collectionRepeat/

<span is-issue-template></span>
![screenshot-ionicframework com 2015-02-28 14-30-53](https://cloud.githubusercontent.com/assets/5680941/6425599/b4b64166-bf56-11e4-9a6d-f1b50d1d7f84.png)

**Comment by ajoslin** [comment]
I removed the link to that codepen for now.  We'll have a better solution soon.
