### ISSUE TITLE
bug: Popups always show scroll bars

### ISSUE THREAD

**Issue by danda1man** [driftyco/ionic#3204]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>This is an issue in the nightly build, I have not checked ios but the issue could be there as well.  Scroll bars always show in the popups all the time, regardless of whether or not there is content to scroll.  Issue appears in the doc example as well: http://ionicframework.com/docs/nightly/api/service/$ionicPopup/</span>

<span is-issue-template></span>

**Comment by jclalala** [comment]
+1 I see it in as well from Browser and Android device.

**Comment by jbollacke** [comment]
Same here. No scrollbars on iOS though.

**Comment by tomkuipers** [comment]
+1

**Comment by gaguirre** [comment]
+1

**Comment by spyjo** [comment]
I also see this problem, on alert or confirm popup

**Comment by BarryReid** [comment]
+1

**Comment by sikron** [comment]
Hi,
fix is not working for me (Android 4.4).

**Comment by tomkuipers** [comment]
@sikron, I tested on my Android 4.4.2 (HTC Desire 601) and the fix is working for me...

**Comment by sikron** [comment]
Hi,
thx for answering! I have the Android 4.4.4 (Cyanogenmod 11) Chrome running on a Samsung Galaxy S2. My Ionic version is 1.0.0-rc1 and i just exchanged "scroll" with "auto". There should have been nothing else to change, right?
I will try with rc2 as soon as possible.

**Comment by tomkuipers** [comment]
To quickly check if this solution worked, in ionic.app.css (and ionic.app.min.css when using minified version) I changed class .popup-body and set 'overflow' to 'auto'.
Or you could change it in .popup.scss and run 'gulp sass' afterwards to generate the css files.
I am also running 1.0.0-rc1, which is the latest (according to 'ionic lib' at the moment), and made the change locally. It should be fixed automatically once 1.0.0-rc2 is released and you run 'ionic lib update' again.

**Comment by Fayozjon** [comment]
Tom

http://bonsezon.ru/analiz

24.03.2015, 17:29, "Tom Kuipers" <notifications@github.com>:To quickly check if this solution worked, in ionic.app.css (and ionic.app.min.css when using minified version) I changed class .popup-body and set 'overflow' to 'auto'.
Or you could change it in .popup.scss and run 'gulp sass' afterwards to generate the css files.
I am also running 1.0.0-rc1, which is the latest (according to 'ionic lib' at the moment), and made the change locally. It should be fixed automatically once 1.0.0-rc2 is released and you run 'ionic lib update' again.

**Comment by sikron** [comment]
My bad, i did not know, i had to do the "gulp sass" step. I actually thought, that ionic cli would do this for me :-) Now it works as expected. 
@tomkuipers Thank you very much!
