### ISSUE TITLE
feat: Ability to manually trigger ion-refresher

### ISSUE THREAD

**Issue by gdjennings** [driftyco/ionic#3208]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I would really like to be able to have the loading animation be the same as the pull-to-refresh animation when a user first visits a page with ion-refresher. On controller init, programmatically starting the refresh via a delegate would be handy</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @gdjennings!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.

**Comment by TifaTsubasa** [comment]
@Ionitron Does Ionic2 have this feature now? programmatically starting the refresh with refresher
