### ISSUE TITLE
bug: expose-aside-menu breaks sidemenu

### ISSUE THREAD

**Issue by belliAndrea** [driftyco/ionic#3219]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the nigthly when expose-aside-when is on a ion-side-menu and the windows is minor then 768px, when i click on menuToggle button, the sidemenu open and immediately close itself.

works fine in beta14.

in this codepen the bug happens after you have resize the window
http://codepen.io/anon/pen/XJBdzE</span>

<span is-issue-template></span>

**Comment by Morriz** [comment]
+1

**Comment by pmariano** [comment]
+1

**Comment by lanceli** [comment]
+1

ref: https://github.com/driftyco/ionic/commit/27298e9209a718450c48048592dc5cf8ffb139f8

**Comment by Koosmann** [comment]
+1

**Comment by manishiitg** [comment]
+1 
same issue for me

**Comment by manishiitg** [comment]
fixed using @Koosmann  method

**Comment by revie** [comment]
+1, seems to be related to: https://github.com/driftyco/ionic/issues/3219

**Comment by revie** [comment]
+1, seems to be related to: https://github.com/driftyco/ionic/issues/3244

**Comment by apolkingg8** [comment]
+1

**Comment by ajoslin** [comment]
Fixed via https://github.com/driftyco/ionic/commit/4f35d8e665cf5d886995686340ebe33b9013a3e1
