### ISSUE TITLE
perf: Sometimes cached .nav-bar-block hide the "active" one because is a nextSibling with the same z-index

### ISSUE THREAD

**Issue by jorgecasar** [driftyco/ionic#3220]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

In my project Ionic generate .nav-bar-block as siblings but the secondary one (initial state 'cached') is after the primary one (initial state 'active'). Then when you navigate to a child page the nav-bar is hidden by the primary one because both have the same z-index.

Here is the generated DOM I have just after first load:

```html
<ion-nav-bar>
    <div class="nav-bar-block" nav-bar="cached">
        <ion-header-bar>
            […]
            <div class="title title-center header-item"></div>
   </div>
    <div class="nav-bar-block" nav-bar="active">
        <ion-header-bar>
            […]
            <div class="title title-center header-item">List</div>
    </div>
</ion-nav-bar>
```

Then when I navigate to a child page the nav-bar is like:

```html
<ion-nav-bar>
    <div class="nav-bar-block" nav-bar="active">
        <ion-header-bar>
            […]
            <div class="title title-center header-item">Item</div>
   </div>
    <div class="nav-bar-block" nav-bar="cached">
        <ion-header-bar>
            […]
            <div class="title title-center header-item">List</div>
    </div>
</ion-nav-bar>
```

And then the cached has a `display:block` with `.header-item` elements with `display:none`, but the `ion-header-bar`, that it has a background, hides the active bar.

Looking at the CSS [_transitions.scss](https://github.com/driftyco/ionic/blob/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a/scss/_transitions.scss) specifically [Lines 63-65](https://github.com/driftyco/ionic/blob/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a/scss/_transitions.scss#L63-65) & [Lines 129-131](https://github.com/driftyco/ionic/blob/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a/scss/_transitions.scss#L129-131) I solved it with `z-index: 9`(or any number less than 10).</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jorgecasar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3220). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3220)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you provide a codepen demo that shows this?

**Comment by jorgecasar** [comment]
I'm not sure how to replicate it. It's happening in my current App. I'm trying to create a codepen with the basic but it works.

I get the side menu from an API service and I generate it on the fly. And it change when you access into a section. Maybe this is the reason, but I keep trying to create an example.

**Comment by Ionitron** [comment]
Greetings @jorgecasar!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @jorgecasar!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by TonGarcia** [comment]
Hi I have it same issue.
It happens when I change from my login app page to dashboard & I think it is all about ionicmotion

**Comment by TonGarcia** [comment]
In my case the code bellow was missed:

```
$scope.$parent.showHeader();
```

**Comment by foram-patel** [comment]
i am also having same issue.
when second time i come to dashboard page it doesn't show sidemenu's icon..

**Comment by foram-patel** [comment]
$location.path("/app/dashboard");
$ionicHistory.nextViewOptions({
                historyRoot: true
});
solved my issue when navigating to dashboard....
