### ISSUE TITLE
bug: Slide box + Collection repeat V2 Estimated Heights

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#3237]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/mmullins/pen/yyqWjb/

It appears the updated version of collection repeat can't grab an accurate height on a collection with images inside of a slide box.  Codepen shows that at full screen we get some sort of goofy padding on the bottom, and in a smaller 1/4 screen view there appears to be overlap.  

If this is just a "getitemheight" solution, that's fine, i'll work with that. 

I'm guessing this would fall in the camp of Dynamic List Mode. 

Thanks for the great work! Excited as always to keep working with Ionic</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
I think the problem is that when computing the height of the item, the image hasn't been fetched yet.  Try setting a height style on the ion-slide-box.

**Comment by tavenzhang** [comment]
can you tell how to fix this !
