### ISSUE TITLE
bug: Collection repeat V2 - 0 items throws error

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#3238]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If the collection is empty, collection repeat can't calculate item heights, (as it should). 

Bug: 

It throws an error to the console with an empty collection: 
<pre>
Error: collection-repeat tried to compute the height of repeated elements "singleElement in elementGroup", but was unable to. Please provide the "item-height" attribute. 
</pre>

Could just warn, or silent, if it's here for testing, all's well.</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
Thanks, I'll be sure this only happens when the data has length.

**Comment by ajoslin** [comment]
Fixed in nightly.
