### ISSUE TITLE
bug: Collection repeat doesn't render list properly

### ISSUE THREAD

**Issue by jryu01** [driftyco/ionic#3240]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Collection repeat doesn't render list properly with fixed item-height and item-width property set. 

I have two tabs, home and list. list controller initiate an array which is used for collection-repeat from shared angular service. The list is shared between controller via angular service.  When I add items to the list from home view(home controller) and then switch tab to list view, list items are not rendered correctly when collection-repeat is used with item-height and item-width property set. When collection-repeat is used without those property, it works fine. 

Here is codepen examples:

With item-width and item-height (not working): 
http://codepen.io/jryu01/pen/azjgrz

without item-width and item-height (working): 
http://codepen.io/jryu01/pen/XJPrRe</span>

<span is-issue-template></span>

**Comment by jryu01** [comment]
This happens in nightly build.

**Comment by ajoslin** [comment]
You'll notice if you resize the window, it then properly renders.

It's not properly resizing the repeater when reconnecting a cached view. It's too bad we didn't catch this before the rc0 release! 

I'll have something pushed to nightly later today.  We'll probably have to re-release for this @adamdbradley.

**Comment by ajoslin** [comment]
Fixed in nightly.

**Comment by jryu01** [comment]
Now it works with item-width and item-height. But breaks without item-width and height. 
Check this:
http://codepen.io/jryu01/pen/XJPrRe

**Comment by jianbo** [comment]
I get a blank collection-repeat list if I switch tab before the collection-repeat list gets rendered, when I resize they appeared. Is there a resize function that I can call to fix this for now?

**Comment by gsanjeevkumar** [comment]
I know its an old bug, but i just realized all my collection-repeats are only showing the first set that to whatever is visible in the window. and when i scroll there is nothing but the background.... no items

can anyone guide me please
