### ISSUE TITLE
bug: rc-0 version: swipe left to go back doesn't work properly

### ISSUE THREAD

**Issue by reviyou** [driftyco/ionic#3250]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using a release candidate version.

When you swipe left all the way to the previous view it goes to the previous view no problem.

1.However you can see that it hides current ion-nav-bar when you start swiping, rather than when you end so user experience is not the greatest(you loose color of your header basically for a second).

2.Another problem arise when you start swiping but decide to stop it. It hides ion-nav-bar and never change it back to visible

i.e <ion-nav-bar class="top-bar nav-bar-container hide" nav-bar-transition="ios" nav-bar-direction="forward" nav-swipe="">  

issue is only reproducible on the device, since ionic serve in a browser would not support swipe left to go to the previous view</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @reviyou!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3250). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3250)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by thco** [comment]
Hi.

I don't want to open an issue for nothing, and cause it's "swipe back" related, I use this one.

I notice that it does not work with <ion-nav-view>, I just wonder if it's a wanted behavior ?
If not, you can add this problem to @reviyou 's one.

**Comment by adamdbradley** [comment]
I'm unable to replicate the problems you're describing. You'll have to create a codepen, which I'll move into a Cordova project, to find the problem.

**Comment by reviyou** [comment]
Thanks Adam for a quick response. I was not able to create a code pen, but I simplified my project to leave only bare minimum with 2html and js files in it. I am attaching a whole cordova platform folder so you can import it as a Xcode project for example. Please let me know if it helps you to reproduce a problem now - Xcode should have all settings there as well, iOS etc..
https://drive.google.com/file/d/0B3JG2qTrPAQSSkNVc3N2OGQ4ZlU/view?usp=sharing

**Comment by adamdbradley** [comment]
It's better to use one ion-nav-bar at the top level, instead of a nav-bar in each view.

**Comment by reviyou** [comment]
It is indeed. However it does't solve the problem.

What if the nag bar content and functionality  if very different for different states?

**Comment by adamdbradley** [comment]
You can still customize navbars and have different buttons and titles for different views: http://ionicframework.com/docs/api/directive/ionNavButtons/

**Comment by reviyou** [comment]
cool, thanks but what about different styling? 
For example we want a different background color for our whole bar for one of the states, not just for the buttons

**Comment by reviyou** [comment]
I did ended up making custom hacks in  run.js like this:

$rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams){
      
            //remove class manually added in profile.js: https://github.com/driftyco/ionic/issues/2732
            if(fromState.name=="tabs.profile") {
	        	angular.forEach(document.querySelectorAll('ion-header-bar'), function(v) {
		            var element = angular.element(v);
		            element.addClass('theme-'+$rootScope.profileTheme);
		        });
	}

since it seems like the only passible workaround for now. However this solution stinks for many reason(1. you have to add a class, remove a class, think about what happens in case of cached pages, or when you swipe back etc etc). Definitely looks like bug #2732  needs some attention

**Comment by ahmed-shehata** [comment]
There's a bug if you decide to swipe back, and then cancel the swipe at the middle of the action, the navbar won't go back

example:

Menu1 -> Menu2
now in Menu2, swipe till half of the screen, then change your mind to swipe back, the navbar will say 'Menu1' instead of 'Menu2' .

**Comment by ahmed-shehata** [comment]
Bug can be reproduced here: @adamdbradley 

http://i.imgur.com/lk9u7vg.gif

**Comment by ShaneXie** [comment]
same style bug here.
