### ISSUE TITLE
bug: Nightly - overflow-scroll="true" doesn't work on a view in standard sidemenu project.

### ISSUE THREAD

**Issue by chrisciszak** [driftyco/ionic#3251]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Overflow-scroll="true" on ion-content within a view is not working on Android 4.4 when using sidemenu project. This problem doesn't occur for beta 14 and cannot be repeated in desktop browser.

To repeat:
1. Ionic start myApp sidemenu
2. Add overflow-scroll="true" in ion-content for one of the views ie 'Browse'. Add more content.
3. Run on android 4.4, bum scrolling not working in 'Browse' view.

This is a showstopper.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @cciszak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3251). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3251)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by cciszak** [comment]
Any update on this issue?

**Comment by Koosmann** [comment]
+1

**Comment by xmlilley** [comment]
my <ion-content> stopped overflow-scrolling pretty much everywhere I'm using them, in-browser or on-device. Content is simply truncated.

**Comment by xmlilley** [comment]
Check 6e149eef9bf5fbee454448f6cfa6f0ea9cce60d3. It put an `overflow:hidden;` on `.pane`. Removing that restores the scroll behavior from 0.9.27.

**Comment by cciszak** [comment]
I want to avoid hacking as much as I can, even simple changes. Ionic its a
serious company so I believe they will address this point ASAP. Its so easy
to repeat, yet it stops us from upgrading, not even mentioning people who
will start from 1.0 version and be surprised with the newest 'stable'
version.

**Comment by xmlilley** [comment]
Well, in the short-term you can just use an override in your own CSS without hacking the ionic file: 

```
.pane {
    overflow-y: scroll;
}
```

**Comment by cyptus** [comment]
just wrote this fix tonight:
add the following if-statement around line 1786 in ionic.bundle.js (RC1), like this:

```
if (ev.direction != 'up' && ev.direction != 'down') {
	ev.srcEvent.preventDefault();
}
```

**Comment by perrygovier** [comment]
Note: when this happens in iOS, it's related to #3267

**Comment by cciszak** [comment]
Quick update, this is not resolved in rc1.01.

Also
```
.pane {
    overflow-y: scroll;
}
```
does not solve the problem.

However, what I noticed is that, when running on a device, the scrollbar seems to think that there is nothing to scroll, although the content is still available to scroll. @perrygovier  does it ring a bell?

**Comment by lgrube3** [comment]
Thank you cyptus! This solves the issue. I was banging my head for awhile on this one.

**Comment by jgw96** [comment]
Hello! Are you all still having this issue with the latest version of Ionic (ionic 1.2.4)?

**Comment by krigulson** [comment]
I have Ionic version 1.7.14 and when I created my app and there is login screen and when rotating device to landscape then scroll not working in this "login" view. 
I also disabled navbar in this view but this is not the issue. 
If I just comment my Login view code out and copy-paste some another view code there where landscape scrolling works then it works in login screen as well.
If I change `overflow-scroll="true"` > `overflow-scroll="false"` then I can drag to down but it jumps to up back when I release my finger. So if `overflow-scroll` is disabled then can drag but cant scroll. 

Pretty nice party blocker. :(

**Comment by fariazz** [comment]
+1 for a fix to this problem.

**Comment by william-beange-hs** [comment]
+1

**Comment by leafdropco** [comment]
Having the same issue using tabs. 
It looks like there is a fixed height that you can scroll within ion-content, even though the height is set to auto.

Here is my html structure:
```
<ion-pane>
  <div>
    <md-tabs>
      <md-tab>
        <ion-view>
          <ion-content>
            <ion-list>
```
 
I'll only get about 20 of my list items in my scrollable area, theres about 40 items in my dom that I can't get to. The above css hack doesn't work in my case. This is killing me.

**Comment by weldermarcosxd** [comment]
+1 for this issue in 2.1.18

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#5
