### ISSUE TITLE
bug: Serious caching issues

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#3259]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I’ve noticed that when I release a new version of the app to the app store, and have Apple automatically update it on my phone, controller code from the previous version is still firing. If you delete the app from the phone and reinstall it, the new controller code fires.

I read through the docs and it says “When navigating to a view that is already cached, its scope is reconnected”. Does this mean that the old controller scope is sitting in memory somewhere, and even after the app update, Ionic will reconnect this older version of my controller when the user navigates to the state because of the cache?

Thanks for any help you can provide…</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Yeah that's interesting, strange how it would still possibly be in memory even if the app was updated. Would you be able to help debug this too? Thanks

**Comment by sean-hill** [comment]
@adamdbradley I'd love to help debug it too, since it's affecting my app :)

**Comment by ajoslin** [comment]
It sounds like the phone may just be caching JS files ... interesting.

**Comment by ajoslin** [comment]
Doesn't apple's update force the app to restart?

**Comment by sean-hill** [comment]
@ajoslin I have no idea :smile:

**Comment by tlancina** [comment]
Seems similar to https://github.com/driftyco/ionic-view-issues/issues/10, although in your case it's an easy fix: just update a cachebuster on your asset urls when you update your app store version.

`<script src='app.js?v=2'></script>`

Also if it is the same issue, just restarting the app will load the new files.

**Comment by sean-hill** [comment]
@tlancina that is true, but telling all my users to force close their app every time there is an update is a little over the edge :smiley:

**Comment by tlancina** [comment]
Yeah I find it crazy that iOS keeps those assets in memory even across an update!

I'm going to close this as it isn't really an Ionic issue, so just make sure to update those cachebusters and UIWebView *should* load the new files.

**Comment by sean-hill** [comment]
@tlancina sounds great, thanks!
