### ISSUE TITLE
bug: CSS class tabs has precedence over item

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3264]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The class tabs in css sets border-top-width to 0 overriding the border width of class item.

This breaks the [card showcase](http://ionicframework.com/docs/components/#card-showcase) example. The border (line) above the tabs (footer) is not shown.

![card showcase](https://dl.dropboxusercontent.com/u/39729597/Capture%20d%E2%80%99%C3%A9cran%202015-03-09%20%C3%A0%2016.20.59.png)</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, I'm seeing css as you've posted but not the visual effects. 
The border that you are missing actually comes from the `.item.item-body`, not the tabs. 
Could you please check there.

**Comment by Ionitron** [comment]
Greetings @kristianbenoit!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by kristianbenoit** [comment]
@mhartington I do not see the problem in ionic-lab, but I do see it on device. You can also see it Chrome, follow these steps:

- Open the example in Chrome
- Open the Inspector
- Switch to device mode ![device mode](http://cdn.sixrevisions.com/500-03-smartphone-icon-highlighted.png)
- Select Nexus 5 or other Android device
- Reload

I have a hard time with resolution/device pixel in latest chrome (42.0.2311.90) device mode, but can still see the problem.

**Comment by mhartington** [comment]
Hmm, it's showing for me.

![screen shot 2015-04-27 at 1 00 31 pm](https://cloud.githubusercontent.com/assets/2835826/7353989/7e88ec6a-ecdd-11e4-8dce-f0570476a7e3.png)

And more importantly, it's showing on an actual device.
