### ISSUE TITLE
bug: radio-buttons inside list only work within label

### ISSUE THREAD

**Issue by badmacstone** [driftyco/ionic#3269]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an ionic-list with 2 radio-items. If I use the tag <ion-item> I can't click the radio-buttons (they are awlays unselected). Only if they are wrapped within a <label class='item item-radio'> it works. If that is intended it's not a bug but then it should be documented that way. Thanks!</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
It is documented that you need a label: http://ionicframework.com/docs/components/#radio-buttons

**Comment by badmacstone** [comment]
Well I thought I can use any element if I don't need the entire row to be tappable.
