### ISSUE TITLE
feat: Android can't handle back button on $ionicLoading

### ISSUE THREAD

**Issue by morinted** [driftyco/ionic#3272]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Issue #1273 addresed the fact that `$ionicPlatform.registerBackButtonAction` would fire while `$ionicLoading` was present.

However, I have a use-case where I would like to allow the user to cancel an $http request if they hit the back button. Would it be possible to add an option to `$ionicLoading` to allow the back button to be registered while it is open?</span>

<span is-issue-template></span>

**Comment by morinted** [comment]
After further reading the Ionic docs, I found that `$ionicPlatform.onHardwareBackButton` does not follow this same rule. For now, I will use this to cancel my loading screens. If this is the expected behavior, then the issue may be closed.

**Comment by mhartington** [comment]
You can hide the loader with the hardware back button, it just need to execute at a higher priority level.

http://codepen.io/mhartington/pen/KwrvwZ

**Comment by morinted** [comment]
That works well, cheers.

**Comment by coolara** [comment]
when` $ionicPlatform.registerBackButtonAction(function (e) {
  
      e.preventDefault();
      console.log('$location.path:----');
      console.log($location.path());
      console.log('$ionicHistory.backView url:-----');
      if ($ionicHistory.backView()) {
        console.log($ionicHistory.backView().url);
      } else {
        console.log($ionicHistory.backView());
      }
      if ($location.path() == '/home') {
        if ($rootScope.backButtonPressedOnceToExit) {
          ionic.Platform.exitApp();
        } else {
          $rootScope.backButtonPressedOnceToExit = true;
          $cordovaToast.showShortCenter('再按一次退出客户端');
          setTimeout(function () {
            $rootScope.backButtonPressedOnceToExit = false;
          }, 2000);
        }
      } else {
        var openPopup = function(type){
          var confirmPopup = $ionicPopup.confirm({
            template: '数据未保存，确定离开?',
            cancelText:'取消',
            okText:'确定'
          });

          confirmPopup.then(function(res) {
            if(res) {
              confirmPopup.close();
              if(type == 0){
                $ionicHistory.goBack()
              }else{
                $state.go('commodityManagement')
              }
            }
          });
        }
        if ($ionicHistory.backView()) {

          if($rootScope.newGoodsBroadcast && $location.path() == '/goodsInfo'){
            openPopup();
          }else if($location.path() == '/newSuppliers'){
            openPopup(0);
          }else if($location.path() != '/login'){
            $ionicHistory.goBack();
          }
          console.log('$location.path:----');
          console.log($location.path());
        }else {
          ionic.Platform.exitApp();
        }
      }

      return false;
    }, 101);
$ionicPlatform.registerBackButtonAction(function (e) {
       $ionicLoading.hide();
},600)`
101 priority is not work ,
how can i let the two registerBackButtonAction  work on same time
