### ISSUE TITLE
feat: Support svg as ressource type.

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3273]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>res.ionic.io only support 'psd', 'ai' and 'png'. psd and ai are proprietary and only have editor under Windows and OSX. There should be support for an open scalable format like svg which has editor on every platforms.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#293
