### ISSUE TITLE
bug: content resize after ionic.Platform.fullScreen

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic#3279]
**Type**: <span ionic-type>bug</span>

**Platform**: iOS 8 webview

The content isn't resizing after ionic.Platform.fullScreen is toggled....

            function orientation() {
                if (ionic.Platform.isIOS() && !ionic.Platform.isIPad()) {

                    if ($window.orientation == -90 || $window.orientation == 90) {
                        ionic.Platform.fullScreen(true, false);
                    }
                    else {
                        ionic.Platform.fullScreen(false, true);
                    }
                }
            }

            window.addEventListener('orientationchange', function () {
                orientation();
            }, false);
Fix:
change `panes[i].style.height = panes[i].offsetHeight + "px";` to `panes[i].style.height = window.offsetHeight + "px";`

![1](https://cloud.githubusercontent.com/assets/1868482/6585416/184c41c6-c772-11e4-9ad5-d39623b3ab38.png)

**Comment by tlancina** [comment]
Should be fixed with https://github.com/driftyco/ionic/commit/1c7b2883572e5648dd141fafe61233994116716c.
