### ISSUE TITLE
bug: $ionicConfig Setting Backbutton Icon Does Not Work

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#3281]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The documentation indicates that `$ionicConfig.backButton.icon('ion-ios-home')` should be able to change the back button icon inside app controllers.

However, this does not work.  However, when requesting the current back button icon with `$ionicConfig.backButton.icon()`, it answers with the correct back button even though the REAL back button in the nav-bar has not changed.

Sample Code Pen : http://codepen.io/calendee/pen/wBYamw</span>

<span is-issue-template></span>

```
controller : function($ionicConfig, $timeout) {
  console.log("Page 2!");
  $ionicConfig.backButton.icon('ion-ios-home');
  $timeout(function() {
    console.log("Back button should be : " + $ionicConfig.backButton.icon());
  }, 300);
}
```

**Comment by mhartington** [comment]
So you ned to use this inside a run function, not a controller.

```javascript
  ..run(function($ionicConfig){
  $ionicConfig.backButton.icon('ion-ios-home');
})
```

>Additionally, $ionicConfig can also set and get config values during the run phase and within the app itself.

**Comment by calendee** [comment]
@mhartington This bit of the documentation suggests it could be anywhere:

> Additionally, $ionicConfig can also set and get config values during the run phase and within the app itself.

"within the app itself" really lends it to seem "in a controller", right?  If so, then perhaps that should be edited out?

So, is it not possible to change the back button icon after the app is initialized?

**Comment by calendee** [comment]
@mhartington Here's an example of this NOT working in `.run`:

http://codepen.io/calendee/pen/qEJKrX

Notice in every `$stateChangeStart` event, I randomly choose a back button icon.  I tell `$ionicConfig` to use that back button.  I then ask `$ionicConfig` what the back button is.  It properly answers with the randomly selected back button.  However, the back button is clearly always defaulting to `ion-chevron-left`.

It seems to me, `$ionicConfig` does not actually apply the new icon to the view.

Am I missing something obvious here or can you re-open this?

**Comment by mhartington** [comment]
Cool, will pass this along to @adamdbradley

**Comment by calendee** [comment]
Great.  FYI : As noted originally, when used in a controller, the same behavior occurs.  When you assign an icon and then ask config what is assigned - it answers correctly but the view is wrong.  So, I feel like $ionicConfig WOULD work in a controller if the underlying issue is resolved.
