### ISSUE TITLE
bug: Navbar hides content when sidemenu + tab bar

### ISSUE THREAD

**Issue by georgschlenkhoff** [driftyco/ionic#3288]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am running into issues when I try to combine sidemenu + tab bar. The tab bar contents' are hidden underneath the sidemenu navbar.

Check this: http://codepen.io/anon/pen/jEerJZ

When I change version to 1.0.0-beta.14 then pen works. So is there any different implementation with 1.0.0-rc.0?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @georgschlenkhoff!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3288). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3288)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ag-secret** [comment]
same issue here
https://github.com/driftyco/ionic/issues/3261

**Comment by ag-secret** [comment]
Try put an `<ion-view>`

    <ion-tabs class="tabs-positive">
        <ion-tab title="Title here">
            <ion-view>  
                <ion-content>
                    Content here
                </ion-content>
            </ion-view>
        </ion-tab>

**Comment by perrygovier** [comment]
Hey @georgschlenkhoff, love the avatar. 
Here's an example starter that shows how to combine side menus and tabs.
https://github.com/driftyco/ionic-starter-tests

**Comment by basvdijk** [comment]
I have the same problem with my app. Adding <ion-view> as mentioned by ag-secret didn't solve the problem. Switching to beta14 didn't solve the overlap problem. I have used the tab code from https://github.com/driftyco/ionic-starter-tests still the content goes below the nav-bar. Is there another (perhaps more simplified) example with a few tabs and the side menu where the content does not go underneath the nav-bar?

**Comment by basvdijk** [comment]
I have solved the problem. On line 2750 in ionic.css I have disabled top: 0 for the .pane, .view selector. Now everything works fine with tabs and side menu. I don't know if changing this value affects other setups.

.pane, .view {
  position: absolute;
 /* top: 0;*/
  right: 0;
  bottom: 0;

**Comment by Ionitron** [comment]
Greetings @georgschlenkhoff!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @georgschlenkhoff!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by basvdijk** [comment]
As stated earlier on line 2750 in ionic.css I have disabled top: 0 for the .pane, .view selector. Now everything works fine with tabs and side menu. I don't know if changing this value affects other setups. Still a problem in RC3

.pane, .view {
position: absolute;
/* top: 0;*/
right: 0;
bottom: 0;

**Comment by rajkotecha** [comment]
adding the sub ion-view actually worked for me! (yay)

have to say learning new frameworks often means: simple stuff == 3hours of futzing about :)

So I am really grateful to forums like this one for helping out!

```
<ion-view title="Marq">
    <ion-tabs tabs-type="tabs-icon-only">
        <ion-tab title="Tab 1" icon-on="ion-ios-home" icon-off="ion-ios-home-outline">
            <ion-view>
                <ion-content class="has-header" padding="true">
                    <h2>Tab 1 Content</h2>
                </ion-content>
            </ion-view>
        </ion-tab>

        <ion-tab title="Tab 2" icon-on="ion-ios-clock" icon-off="ion-ios-clock-outline">
            <ion-view>
                <ion-content class="has-header" padding="true">
                    <h2>Tab 2 Content</h2>
                </ion-content>
            </ion-view>
        </ion-tab>

        <ion-tab title="Tab 3" icon-on="ion-ios-gear" icon-off="ion-ios-gear-outline">
            <ion-view>
                <ion-content class="has-header" padding="true">
                    <h2>Tab 3 Content</h2>
                </ion-content>
            </ion-view>
        </ion-tab>
    </ion-tabs>
</ion-view>
```
