### ISSUE TITLE
feat: How do you trigger a collection-repeat resize() in v1.0.0-rc0?

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#3292]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm not sure if this is a bug or not, but in beta14 I was able to force the collection-repeat directive to recalculate dimensions and re-render with a call like this, `$ionicScrollDelegate.$getByHandle('collection-repeat-wrap').resize()`. This no longer seems to work with the new, refactored collection-repeat from 1.0.0-rc0

```javascript
    $ionicScrollDelegate.$getByHandle('collection-repeat-wrap').resize()
   // trying to get collection-repeat directive to run this code:
    var onWindowResize = ionic.animationFrameThrottle(validateResize);
    angular.element($window).on('resize', onWindowResize);
```

```html
     <ion-content delegate-handle="collection-repeat-wrap">
      <div collection-repeat="item in items">
        ...
      </div>
    </ion-content>
```

Is there a better way to do this?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3292). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3292)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ajoslin** [comment]
Try triggering a `resize` on the window.

**Comment by mixersoft** [comment]
i tried it. it doesn't work because of this method - it there an easy way to add a `--force` option?

    function validateResize() {
      var h = scrollView.__clientHeight, w = scrollView.__clientWidth;
      if (w && h && (validateResize.height !== h || validateResize.width !== w)) {
        validateResize.height = h;
        validateResize.width = w;
        refreshDimensions();
      }
    }

**Comment by mixersoft** [comment]
I added this these lines to the directive for now, but there has to be a better way

    var onWindowResize = ionic.animationFrameThrottle(validateResize);
    angular.element($window).on('resize', onWindowResize);
    // force collection-repeat refresh with a call to:
    //    angular.element($window).triggerHandler('resize.collection-repeat');
    var onWindowResizeFORCE = ionic.animationFrameThrottle(refreshDimensions);
    angular.element($window).on('resize.collection-repeat', onWindowResizeFORCE);

**Comment by zarko-tg** [comment]
Made a small test case: http://codepen.io/zarko/pen/VYEQZM

**Comment by ajoslin** [comment]
Ah you're right that won't work. I'll add a better way.

**Comment by ajoslin** [comment]
It now refresh dimensions when $ionicScrollDelegate.resize() is called. Thanks!

**Comment by zarko-tg** [comment]
Thanks. I also updated the codepen and seems just fine now.
