### ISSUE TITLE
bug: Delete last list item in collection-repeat fails

### ISSUE THREAD

**Issue by jesusbotella** [driftyco/ionic#3299]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The new collection-repeat doesn't delete the last item in the list even though the list items array is empty.

I have an array with several items that are shown in the list by means of collection-repeat. When I delete whatever item but the last it works. But if I delete the last element, the item is still there until I tap or try to scroll.

I think it could be some view refresh that isn't executed or something like this.

I solved it by adding:
> $ionicScrollDelegate.$getByHandle('listScroll').resize();

or (if deleting is done asynchronously):

> $timeout(function() {
>   $ionicScrollDelegate.$getByHandle('listScroll').resize();
> }, 150);</span>

<span is-issue-template></span>

**Comment by ajoslin** [comment]
Fixing.

**Comment by ajoslin** [comment]
Here's the crazy logic we need:

```js
    function makeChangeValidator() {
      var self;
      return (self = {
        dataLength: 0,
        width: 0,
        height: 0,
        resizeRequiresRefresh: function(newWidth, newHeight) {
          var requiresRefresh = self.dataLength &&
            newWidth && newWidth !== self.width &&
            newHeight && newHeight !== self.height;

          self.width = newWidth;
          self.height = newHeight;

          return !!requiresRefresh;
        },
        dataChangeRequiresRefresh: function(newData) {
          var requiresRefresh = newData.length > 0 || newData.length < self.dataLength;

          self.dataLength = newData.length;

          return !!requiresRefresh;
        }
      });
    }
```

Now all the cases are covered cleanly.

**Comment by jesusbotella** [comment]
Thank you so much! You were so fast resolving it ;)
