### ISSUE TITLE
bug: expose-aside-when and collection-repeat resize

### ISSUE THREAD

**Issue by belliAndrea** [driftyco/ionic#3302]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When i use expose-aside-when on a sidemenu and i have a list made with collection-repeat on the right, the list doesn't resize its width when, for example, i change from portrait (closed side menu) to landscape (exposed side menu).</span>

<span is-issue-template></span>

this happening on current nightly (1.0.0-rc.0-nightly-1145)

**Comment by belliAndrea** [comment]
Even the new nigthly (1149) doesn't solve the thing. Because $ionicScrollDelegate.resize() seems like is called before sidemenu expose.

**Comment by mattchue** [comment]
+1. I too am having this issue. Hadn't realized it was the sidemenu though. Interestingly, the behavior seems inconsistent. Sometimes on app load it does not resize, other times it resized properly.

**Comment by ajoslin** [comment]
This is fixed in the nightly builds.
