### ISSUE TITLE
bug: $ionicView.beforeEnter is not being called on app load

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#3303]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>It does get called when I navigate to the controller/view, just not if I load that URL/view directly from the browser.

`$ionicView.enter` works fine

I'm testing RC0</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3303). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3303)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jarbitlira** [comment]
I'm having the same problem but i'm using $rootScope for solve temporally, this not work  if i use $scope

**Comment by mlynch** [comment]
Still an issue?

**Comment by videmort** [comment]
Yes still An issue, it never enter in the beforeEnter when you launch the app

**Comment by danbucholtz** [comment]
Hi @mixersoft and others,

This should be resolved in the nightly build.  We did a lot of work with the life cycle events.  Can you test on the latest build?  Let me know if you need some help.

http://code.ionicframework.com/#nightly

I guess our staging site hasn't deployed in the past week or so, but we do have new and improved docs.
http://ionic-site-staging.herokuapp.com/docs/nightly/api/directive/ionView/

Basically, in addition to dispatching the event upwards (emit) from the correct scope, but we also now fire events downwards (broadcast) to work with ui-router nested views.

```
$scope.$on("$ionicParentView.enter", function(event, data){
   // woot, I received the event!
});

$scope.$on("$ionicView.enter", function(event, data){
   // woot, received the event
});
```

Please let me know if you have any issues and I'll re-open if needed.

Thanks,
Dan

**Comment by badpenguin** [comment]
Tested with nightly right now.
For the first view loaded via $urlRouterProvider.otherwise('/splash');
only the "loaded" event is fired.
The "enter" and "beforeEnter" are never fired.

The problem does not exists in 1.2.4.

**Comment by NicholasAaronBrady** [comment]
Also have issue in 1.3.2 but not 1.2.4

**Comment by zjx** [comment]
hi guys encounter the same issue. need to remove the <style> from template html.

**Comment by sradforth** [comment]
I can't believe this bug, ouch!  Thank you zjx for solving this.  I only noticed these were no longer being called on some views.  It is indeed the <style></style> at the top of templated html that caused the issue for me too.

**Comment by Leffe108** [comment]
In my case it was only on one controller that $ionicView.beforeEnter was not called. It was my otherwise controller without any template. Adding a dummy template and set templateUrl solved the problem for me. Now it happily run the beforeEnter code and redirect users where they should go.
