### ISSUE TITLE
feat: Define animation in $ionicHistory.nextViewOptions

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#3304]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm looking for a way to set what animation transition and direction to use in the next state transition, I was searching for a transition android like, just in one special case and not in my whole app, would be nice if `$ionicHistory.nextViewOptions` has something like:

```js
$ionicHistory.nextViewOptions({
  disableBack: true,
  navAnimation: 'android',
  navDirection: '...'
});
```

Just like [navDirection](http://ionicframework.com/docs/api/directive/navDirection/) and [navTransition](http://ionicframework.com/docs/api/directive/navTransition/)

I don't know if is there a way to do this right now.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Moving this to our trello board and closing this issue

https://trello.com/c/Zt6O5AGg/94-set-animations-in-nextviewoptions
