### ISSUE TITLE
perf: Mobile Application Performance Issue

### ISSUE THREAD

**Issue by anusreejaivi** [driftyco/ionic#3312]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi Team,

We are developing a high profile mobile application for one of our clients using the IONIC framework.
We are almost done with the development for this phase. The application seems to be working well when
opening in Web/Mobile Browser. However, when we port this into a mobile application using the framework commands
the application becomes very slow , screen transitions are not smooth and sometimes the screen just freezes for a second. This is resulting in a very poor user experience. 

I am using the command "ionic run android" to create the APK. 
Could you please help us with this issue? We are not able to submit the APK for testing with this issue.
Is there any configuration that i could use to speed up the application.

Also, I have added a Ionic Loader in most of my pages.The behaviour is very inconsistent (it appears sometimes only).
This is also contributing to a poor user experience.

Looking forward to your positive response.

Thanks and Regards,
Anusree.</span>

<span is-issue-template></span>

**Comment by emps** [comment]
same here

**Comment by perrygovier** [comment]
Older Android can be slow, especially as your application grows. Try giving crosswalk a shot. http://ionicframework.com/blog/crosswalk-comes-to-ionic/

**Comment by oliguo** [comment]
same here,what's more,I found 5.0 sometimes also lap

**Comment by Ionitron** [comment]
Greetings @anusreejaivi!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
