### ISSUE TITLE
bug: rc0: swipe left problem if prev page was not cached

### ISSUE THREAD

**Issue by reviyou** [driftyco/ionic#3317]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>you have <ion-view  cache-view="false"> on page A and go to the nested page and swipe left to go back to page A:

expected - invoke stateProvider for state A(hit controller etc)
actual - it goes to a blank page since it doesn't use stateProvider and jus trying to return to the previously cached page</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Swipe to go back requires that the previous page is cached. We played with it quite a bit, and it was actually a large part of why we added page caching in the first place. Loading a page on swipe to go back adds an unacceptable lag. We're open to PRs that can address this, but currently this is deliberately not supported.

**Comment by reviyou** [comment]
Thanks, that answers the question.
It would be valuable for your guys to document it for the users

**Comment by josephfinlayson** [comment]
I think that "swipe to go back" on should be disabled on pages that are not cached. Blank screens is in no way a good user experience!

Fixed with:
			$ionicConfigProvider.views.swipeBackEnabled(false);

**Comment by Fayozjon** [comment]
Joseph

http://workservis.ru/kontrakt

24.03.2015, 18:05, "Joseph Finlayson" <notifications@github.com>:I think that "swipe to go back" on should be disabled on pages that are not cached. Blank screens is in no way a good user experience!

Fixed with:
            $ionicConfigProvider.views.swipeBackEnabled(false);

**Comment by VladimirPal** [comment]
It's a big problem

**Comment by AleksMeshkov** [comment]
>> Blank screens is in no way a good user experience!
+1 I think there should be a bulletproof solution.

**Comment by ericraio** [comment]
+1 we need a solution for this

**Comment by violet7** [comment]
+1

**Comment by etrey** [comment]
+1

Fixed with:
            $ionicConfigProvider.views.swipeBackEnabled(false);

**Comment by Chuckv01** [comment]
+1

**Comment by jackyon** [comment]
+1

**Comment by ajaybeniwal** [comment]
This is s big problem should be supported ASAP

**Comment by pierre-vigier** [comment]
+1

**Comment by marcelfalliere** [comment]
+1

@perrygovier, what whould you say causes the lag ? 

My 2 cents : the cause of the lag is one of the following :
- template render
- controller initialization
- angular scope apply

If the cause is not the template render phase, a potential solution maybe the following : the view that is not cached is rendered during the swipe and the controller initialization is called when the animation ends. That way the user sees an empty view, for which the content is loaded when he actually decides to go back to this view.

**Comment by loet** [comment]
I solved the problem by using the $ionicView.beforeEnter event. I let the views in the cache, as it is the default, but refresh the view model in controller on the event 'beforeEnter':

$scope.$on('$ionicView.beforeEnter', function() {
            MyService.reloadData(...);
});

Seems to work with all the swipe back gestures.

**Comment by AleksMeshkov** [comment]
interesting, I'll check this workaround in my project. thanks!

**Comment by anurag6792** [comment]
Is it fixed now?

**Comment by ljcljc** [comment]
I am facing the same issue, does anyone have any idea?
