### ISSUE TITLE
bug: Ionic slider box not showing pager

### ISSUE THREAD

**Issue by walfro** [driftyco/ionic#3324]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>In the beta version of ionic the pager was showing properly but after update to version 1.0.0-rc is not showing the pager of slider box.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Good catch @walfro, thanks!

**Comment by perrygovier** [comment]
fixed in 95688d6aa5c7150c3e46f1feac9cbc5f15ac7201
