### ISSUE TITLE
bug: ion-slide-pager breaking ion-slide in rc0

### ISSUE THREAD

**Issue by njcaruso** [driftyco/ionic#3326]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Using documentation on rc0/nightly build at:
http://ionicframework.com/docs/api/directive/ionSlidePager/

When I add <ion-slide-pager></ion-slide-pager> it "breaks" the ion-slide-box.  See codepen below. Top of screen is the broken slide-box, bottom (without slide-pager) works.

http://codepen.io/ncaruso/pen/xbQOLJ</span>

<span is-issue-template></span>

**Comment by cyprusglobe** [comment]
What about this?
http://codepen.io/anon/pen/EaOyzG

i added ```show-pager="true"``` to ion-slide-box

**Comment by njcaruso** [comment]
Thanks, works great, but i was trying to follow the updated instructions at:
http://ionicframework.com/docs/nightly/api/directive/ionSlidePager/

It seems to be a bug, can you get the example they have in the documentation to work?

<ion-slide-box>
  <ion-slide-pager></ion-slide-pager>
  <ion-slide>1</ion-slide>
  <ion-slide>2</ion-slide>
  <ion-slide>3</ion-slide>
  <ion-slide>4</ion-slide>
</ion-slide-box>

**Comment by mhartington** [comment]
Will update the docs, @cyprusglobe markup is correct.
