### ISSUE TITLE
bug: ionSpinner issues with utility color classes

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#3328]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This is "Kind of bug"

:warning: This codepen is really annoying to see, everything is spinning http://codepen.io/felquis/pen/ZYmpPd

My notes are: 

1 - The android spinner with `spinner-clean` is blue, but the others are black/gray, shouldn't it also be black/gray?

2 - All the `spiral` has with a black tail, there's some posts about it in the forum. But it's impracticable to use `spiral` with other colors because it just don't work as expected.

A bit related to #3077

Thanks.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
The spinner-clean is something @adamdbradley intended. It's the default Android color, and "clean" is intended to be the spinner's default color. This will become more apparent as we add more complicated spinners.  Right now, it's the odd one out. 

The spiral tail needs to be fixed. Thanks
