### ISSUE TITLE
bug: Params doesn't get passed correctly always with $state.go()

### ISSUE THREAD

**Issue by ssreekanth** [driftyco/ionic#3338]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$state.go(state, params) doesn’t seem to be passing the params correctly.

http://codepen.io/ssreekanth/pen/jEQLOa

Let me show it in my example here. Try to add grocery items to the shopping list.
1) Click on ‘+’ at the top right corner. This will take you to the ‘Add Grocery’ view.
2) Tap on ‘Milk’. It will take you to the ‘Grocery Details’ view.
3) In Grocery Details view, you would see ‘Milk’. Now, click on ‘Add to Shopping List’ button. Milk gets added to the list and view transitions to ‘Shopping List’ page.

So far, it is fine.

4) Now, try to add a new item to the list. Again click on ‘+’
5) But, this time, tap on ‘Bread’.
6) However, in the ‘grocery details’ view, it still shows ‘Milk’. It was supposed to show ‘Bread’.</span>

<span is-issue-template></span>

**Comment by agnellvj** [comment]
The problem appears to be the use of `params` and a `url` in your state configs. The doc for [params](https://github.com/angular-ui/ui-router/wiki/Quick-Reference#params) says they are not allowed to be used at the same time.

I was able to get your [codepen](http://codepen.io/agnellvj/pen/YPReWr) to work with a few tweaks.

**Comment by ssreekanth** [comment]
@agnellvj Thank you. That resolved my issue.

'ui-sref' may not help, if you want to handle some task before transitioning to the new state. With ng-click(), you can achieve it. Suggest me if therez a better way to handle this.
