### ISSUE TITLE
bug: Orientation doesn't update cached collection

### ISSUE THREAD

**Issue by netalico** [driftyco/ionic#3345]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've found that if you use collection-repeat and you rotate your device while on another tab then when you go back to the original tab its stuck assuming the width of the previous orientation so it looks weird. For now I just put in place this workaround that clears my view cache whenever the device rotates.
```
window.addEventListener("orientationchange", function() {
    $ionicHistory.clearCache();
  }, false);</span>
```
<span is-issue-template></span>

**Comment by anwaramoon** [comment]
ajoslin added resize method in scroll delegate to force collection repeat to calculate dimensions. You can try this code in tab active/selected event.

"$ionicScrollDelegate.resize()"

https://github.com/driftyco/ionic/issues/3292

**Comment by perrygovier** [comment]
Hey @netalico, does ajoslin's recent fix resolved your issues.

**Comment by Ionitron** [comment]
Greetings @netalico!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by ninjakatz** [comment]
this is still relevant!
