### ISSUE TITLE
bug: Modal header is below tabs-top on iOS Cordova

### ISSUE THREAD

**Issue by mikejpeters** [driftyco/ionic#3346]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>http://codepen.io/mikejpeters/pen/azQQdV

When top tabs are used within a modal, the modal header is incorrectly displayed below the tabs on iOS with Cordova (when the body has the `platform-ios` and `platform-cordova` classes).</span>

<span is-issue-template></span>

**Comment by mikejpeters** [comment]
Related to issue #3011

**Comment by mhartington** [comment]
Quick question, is the purpose of tabs in the modal to create a nested navigation structure?

**Comment by mikejpeters** [comment]
Yes (e.g. to have an "Edit" modal that contains tabs for organizing the editable data); I assumed this is supported because there seems to be css in `_modal.scss` specifically for tabs.

**Comment by mhartington** [comment]
So the issue was the `has-tabs-top` class on the header bar.
Should be good now.

http://codepen.io/mhartington/pen/qEzxjM

**Comment by mikejpeters** [comment]
Yes the issue is not present unless the `has-tabs-top` class is present, but I think it's still valid.  I want my header to blend with my top tabs, which means I need to use the `has-tabs-top` class according to the [documentation](http://ionicframework.com/docs/components/#striped-style-tabs).

That is specifically what I have tried to address with my pull request.

**Comment by mhartington** [comment]
Hmm, alright so I see where the confusion is. So `has-tabs-top` is used a few places in our css. 
1) For header-bars when the tabs are on top
2) For ion-content when tabs are on top

But it seems that the styles from 2 are effecting 1. 
Will with the team about merging the fix. Just don't want to introduce any possible bugs.
