### ISSUE TITLE
Disabled button state

### ISSUE THREAD

**Issue by asgeo1** [driftyco/ionic#335]
It would be good if there was a `.disabled` css class that could be applied to buttons.

Perhaps something similar to `.ui-disabled` from jQuery Mobile which can be applied to buttons.  E.g.

```
.button.disabled {
  filter: Alpha(Opacity=30);
  opacity: .3;
  zoom: 1;
  cursor: default !important;
  pointer-events: none;
}
```

**Comment by obcdnico** [comment]
Sometimes... the doc is usefull ! ( ionic is based on Angular-js ? )
https://docs.angularjs.org/api/ng/directive/ngDisabled

simple example :::
(in view : )
          <label class="item">
            <button ng-disabled="model.satus" class="button button-block button-balanced" type="submit">{{value}}</button>
          </label>
(in controller : )

    $scope.model.satus = true; // for disabled or false for enable...


i think can be helpfull....
