### ISSUE TITLE
bug: collection-repeat & expose-aside-when not resizing

### ISSUE THREAD

**Issue by mattchue** [driftyco/ionic#3352]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/mattchue/pen/pvQMod

collection-repeat items inconsistently and incorrectly resize when expose-aside-when is used. the codepen I have included demonstrates this, but you may have to refresh your page a number of times in order to reproduce the bug. It seems to do it on almost every other reload in my app in-browser.

correct width: http://i.imgur.com/TSZoKob.png
incorrect width: http://i.imgur.com/KsF2oFq.png

edit: this also seems to be happening when orientation is changed, the width of the cards do not update along with the orientation
</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Note that triggering a resize on the scroll controller corrects the issue:
http://codepen.io/perrygovier/pen/GgzEea

**Comment by mattchue** [comment]
Nice, that works really well as a temp fix in the meantime. Thanks for addressing this so quickly.

**Comment by tschuegge** [comment]
Please correct it in 1.2.1... there exists the bug again.
