### ISSUE TITLE
bug: TypeError: Request path contains unescaped char

### ISSUE THREAD

**Issue by Kyozatch** [driftyco/ionic#3355]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I just downloaded ionic. I created the project without any problem but, when i tried "ionic platform add android" i got an error :
"npm http GET https://registry.npmjs.org/cordova-android/3.7.1
TypeError: Request path contains unescaped characters."

I was looking for a solution on google, it seems to be a proxy problem. However, I already set my proxy config and it works..

ionic : 1.3.16 cordova : 4.3.0 node : 0.12.0

Thanks</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#321

**Comment by perrygovier** [comment]
Hey @Kyozatch, I moved this issue over to the CLI repo. Josh should be able to help you there.

**Comment by redarc** [comment]
I tried to use command "ionic platform add ios android ", but it showed same error
"
npm http GET https://registry.npmjs.org/cordova-ios/3.8.0
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
"
ionic : 1.3.18 cordova: 4.3 node: v0.12.0
