### ISSUE TITLE
bug: Ionic Scroll Delegate scroll top value always 0

### ISSUE THREAD

**Issue by CedNet** [driftyco/ionic#3360]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a directive that uses $ionicScrollDelegate.getScrollPosition().top in order to bind to the scroll event on <ion-content>. So that when scroll happens, I make an element dissappear from view (a footer bar).

This works on first app load, on current view. But if I go browse via a certain path in the app: openingen a side menu, selecting a menu item, a new modal opens with content. I click a link in this modal..., and the app now closes modal and navigates to a new route and view template. 

Now is where this "bug" begins. The $ionicScrollDelegate.getScrollPosition().top value is always zero from now on. No matter if I go back to the start view. It will from now on always report 0 value. Hence, no longer hiding my footer bar on any view in the app.

I cannot find any info that I'm doing this wrong in any way, or that it's supposed to be acting like this.Or, how I reset the top position so to speak.

I've created a code pan that echoes current value to console via console.log. So please, go there and open the debug console. 

Scroll on the first view. See how the value updates.
Now open left menu and move to any other view. 
See how the console now always reports 0 as value on scroll.

http://codepen.io/johced/pen/JowyGx</span>

<span is-issue-template></span>

**Comment by CedNet** [comment]
UPDATE:
I do not know anymore if this is a "bug". 

On state changes the ionicScrollDelegate has many objects or handlers.

I was able to solve this by adding a delegate-handle="nameOfHandler" next to each directive attribute to specify which ionicScrollDelegate handler I want to use.

This issue can be closed, unless it's a "bug" that getScrollPosition().top maybe should return the position of the "latest" handler available and not the first (of possibly many ionicScrollDelegate objects.

**Comment by perrygovier** [comment]
We advise `$ionicScrollDeleate` code use the [`ionView` events](http://ionicframework.com/docs/api/directive/ionView/) to do their thing after the page has loaded. Otherwise you can run in to race conditions like what it looks like you were in. Thanks!
