### ISSUE TITLE
bug: tabs-top tabs-striped titles misalign when active

### ISSUE THREAD

**Issue by mikejpeters** [driftyco/ionic#3364]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/anon/pen/bNOaOY

When a `tabs-top tabs-striped` tab is activated, the title is moved down by a couple pixels and does not line up with the title of the other, inactive, tabs.

I believe the problem was introduced in RC0 and only applies to tabs with titles instead of icons.  (Tab icons are `display: block` and have a negative margin applied when the tab is active.)

https://github.com/driftyco/ionic/blob/bf40b222be85c8dba6e9531044505976fabc8d78/scss/_tabs.scss#L310

I think that similar styles need to be added for the `.tab-title` element, i.e. make it `display: block`, and update the rule on line 310 to:

```css
> .tab-title, > .badge, > i {
  margin-top: -$tabs-striped-border-width + 1px;
}
```
</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
@mike, can you run this fix through snapshot? make sure it doesn't break other configurations?

**Comment by mhartington** [comment]
So the changes your proposing @mikejpeters ended up causing issues for the `tabs-icon-left` and `tabs-icon-top` classes. Will look into a better fix
