### ISSUE TITLE
Set a default browser to open with `ionic serve`

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic#3367]
Let the user set a default browser (chrome, safari, firefox) when using the `ionic serve` command.

Maybe something like `ionic serve -f safari` 

That way whenever they run `ionic serve` it goes with their default unless they specify a browser with `-b`.

**Comment by rikvanderkemp** [comment]
Would it be possible to add an attribute to the ionic.project file as well? 

    {
        .....
        "serve" :  {
           "defaultBrowser" :  "chrome"
       }
        .....
    }

**Comment by jbavari** [comment]
Yep, great suggestion.

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#328
