### ISSUE TITLE
Bug: Can't override tabs-striped icon color in scss

### ISSUE THREAD

**Issue by JohnBernardsson** [driftyco/ionic#3371]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried to override all tabs icon color and text using:
```
$button-dark-text:                #fd0 !default;
```
within the "inonic.app.scss" file.
It works well for ios tabs, but for striped tabs in android, I need to make  changes in _tabs.scss file to make it work (what I guess is not desirable).
In particular, I needed to modify the second argument in this mixin call:
```
@include tabs-striped('tabs-dark', $light, $dark);
```
(I also tried to call that mixin within .tabs-striped{} in ionic.app.scss, but it breaks a bit the tab when active).</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Just tested this out, seems to create the correct css, but the color property isn't getting applied.
Seems the css selectors that get produced from the mixin aren't specific enough to override the default color.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
