### ISSUE TITLE
bug: $ionicScrollDelegate.freezeScroll() is not defined

### ISSUE THREAD

**Issue by xmlilley** [driftyco/ionic#3381]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Using a clean installation of RC1, from the CLI using the "sidemenu" seed, I add the following to the PlaylistsCtrl, attempting to experiment with freezing a scroll:

```js
var delegate = $ionicScrollDelegate.$getByHandle('playListScroll');
delegate.freezeScroll(true);
```

and I enabled scrolling on the view template, without any other modifications to it (other than adding a few more items to the list, so there's something to scroll):

```html
<ion-content scroll="true" delegate-handle="playListScroll">
    <ion-list>
    ...
```

In Chrome, attempting to execute `freezeScroll()` on that $ionicScrollDelegate triggers `TypeError: undefined is not a function` at the position of the call to `freezeScroll()`. In the simulator (from either `ionic emulate ios` or from within XCode), it simply freezes the app before it can render that view, and produces no output.

The results and console output are the same whether I simply execute `delegate.freezeScroll(true);` on controller startup, or if I execute it inside an `on-scroll` callback.

Note that I'm successfully accessing the delegate. If I push the delegate object to console, its instances (and their prototypes) appear to lack any method called `freezeScroll`, or `freezeAllScrolls`, which I see [in the docs] (http://ionicframework.com/docs/api/service/$ionicScrollDelegate/). All other expected methods/properties are present. Here's a grab from console of an instance's own properties: 

```js
_instances: 
Array[3]0: 
Object$$delegateHandle: "playListScroll"
$$filterFn: function () {
$element: JQLite[1]
__timeout: function timeout(fn, delay, invokeApply) {
_scrollViewOptions: Object
_setRefresher: function (refresherScope, refresherElement) {
anchorScroll: function (shouldAnimate) {
element: ion-content.scroll-content.ionic-scroll.has-header
getScrollPosition: function () {
getScrollView: function () {
resize: function () {
scrollBottom: function (shouldAnimate) {
scrollBy: function (left, top, shouldAnimate) {
scrollTo: function (left, top, shouldAnimate) {
scrollTop: function (shouldAnimate) {
scrollView: ionic.Utils.inherit.child
zoomBy: function (zoom, shouldAnimate, originLeft, originTop) {
zoomTo: function (zoom, shouldAnimate, originLeft, originTop) {
__proto__: Object
```

Am I missing something about how and when I should be able to use/access that method? Or should it be there and be usable?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @xmlilley, this makes sense, but could you provide a working example of the issue we can test against?

**Comment by xmlilley** [comment]
D'oh. 

A. My previous install from the CLI was *not* actually running rc.1, it was beta.14. 
B. Everything seems to work with CLI 1.3.18 and rc.1.

Sorry and thanks.

**Comment by zeritorl** [comment]
is this already working with chrome ? it seems freezeScroll(true); does not work on my device, emulator is fine.
