### ISSUE TITLE
bug: Modal breaks leaflet map

### ISSUE THREAD

**Issue by schuppo** [driftyco/ionic#3383]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi Ionic development team!
First thanks for the great framework! It make developing hybrid apps awesome. 
But I have one small issue which is related to the interaction between the ionic framework and the leaflet map layer which is contained inside an ionic-nav-view. In its most reduced form you can see the app here: http://codepen.io/schuppo/pen/PwXMpN
The problem now is: When an modal view is opened while the nav view containing the map is in cached state the positioning coordinates of the dom element containing the map get broken. The reason is because showing a modal triggers a global window resize event and leaflet is listening to resize events too. 

So my question is: Is it necessary that opening a modal view also triggers a resize event on window object level?

You can reproduce the behavior like this:
1. Open the pen (see link above) in chrome.
2. Click on "Show map".
3. Activate "Break on attributes modification" on "<div class="leaflet-map-pane" style="transform: translate3d(0px, 0px, 0px);">" node.
4. Click on "Show default".
5, Click on "Show modal".
Now you should see the call stack indicating that the resize event being triggered is also listened to by leaflet.
6. When you finish the call stack and return to the map view you can see that the map content is dislocated.

Hope my issue description is clear enough. If something is missing or misleading, leave me a note. I am looking forward to your reply!</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
We do need to trigger the resize event to make sure the modal window is displayed appropriately.  It may be better to talk to the Leaflet team. It should be able to handle resize events ok. 

Perhaps wrapping it in a fixed width div? I'm able to get it to not mess up after using it for a while. Maybe automatically adjust it a bit after load to get it in the right mode?

I'm going to close the issue though since it's not really a bug in Ionic. 3rd party libs should handle native browser events without issue. Ionic could stop calling them, but you'll still have the issue coming from the browser itself.

**Comment by schuppo** [comment]
Ok thanks. I have opened an issue at leaflet's github repo. Let's wait for their reply.

**Comment by nikhilknoldus** [comment]
@perrygovier SORRY BUT This is the issue with IONIC ONLY, not any other libraries at all, you can use graphs, you can use maps use anything and open  a modal, ionic modal breaks everything everything, so much annoying man :/

**Comment by perrygovier** [comment]
@nikhilknoldus most other libraries have no reason to trigger a resize event. It's a native browser event, that leaflet needs to be able to respond properly to. From the issue on Leaflet, it looks like you can pass the `trackResize: false` option to resolve the issue. If not, you need to take it up with the leaflet team.

**Comment by nikhilknoldus** [comment]
As i said its not just about leaflet, earlier i was having issue with leaflet but now i have issue with graph, angular-chart.js pie chart, polar chart etc, when i open ionic popover, modal graph with and height got 0, and when i again open it graphs come visible.

**Comment by vvavepacket** [comment]
Hi, where you able to fix the issue @nikhilknoldus

**Comment by nikhilknoldus** [comment]
@vvavepacket  everytime i am opening the tab am re creating (rendering) graph again.
