### ISSUE TITLE
bug: CollectionRepeat wrong event 'scroll.resize'

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#3384]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The following code hook the wrong event 'scroll.resize'. The JQuery event name is event+namespace. So this event will be interpreted as 'scroll' event, which will be triggered for every scrolling. Because the scroll view will trigger the scroll event through the "triggerScrollEvent()". 

The consequence is the "CollectionRepeat" will always be forced to refresh the layout for each scrolling. This will waste the performance.  

    // Dimensions are refreshed on resize or data change.
    scrollCtrl.$element.on('scroll.resize', refreshDimensions);</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @dreamershl, That would be a big problem. Can you put together a codepen demonstrating that `refreshDimensions()` is indeed firing every scroll event?

**Comment by Fayozjon** [comment]
Perry

http://wenxuebu.com/forex-dollar

24.03.2015, 19:30, "Perry Govier" <notifications@github.com>:Hey , That would be a big problem. Can you put together a codepen demonstrating that refreshDimensions() is indeed firing every scroll event?

**Comment by dreamershl** [comment]
Hi, because of my unfamiliarity to the codepen, I just paste the screen capture of my current environment for your reference. 1 is the detail call stack analysis, another one is my working environment for your reference. 

When scrolling the list, the following is the key call path

    self.__publish(scrollLeft, scrollTop, level); 
               -> self.triggerScrollEvent();
                           ->refreshDimensions();
                                    ->getRepeatManager().refreshLayout();
    
All because of this event triggering "ionic.trigger('scroll', {" in the  triggerScrollEvent(). It triggers a global scroll event (no namespace as suffix). So the current event handler "scrollCtrl.$element.on('scroll.resize', refreshDimensions)" will be invoked. 

If correct the event name from "scroll.resize" to "resize.scroll". The "refreshDimensions" will be only invoked when the element is resized. Just FYI, there are 3 places to be corrected.  

Last one, **may I request a same small enhancement in this new version again?** Please export the current shown items. If it does, the application get chance to dynamically load the data. This is extremely helpful on the real time apps performance such as stock price updates.  

To simplify the export, 
1: instead of the closure, put the 'render()' as the method of the "RepeatController"
      
    this.render=function(forceRerender) { 

2: return the "itemsShownMap" from the "this.render" 

Then the application get chance to know the current visible items exactly!  

Call stacks:
![image](https://cloud.githubusercontent.com/assets/1271739/6827343/edab1844-d341-11e4-9228-79f29c798997.png)


My working environment: 
![image](https://cloud.githubusercontent.com/assets/1271739/6827197/0a49d18a-d341-11e4-8e6f-600093479de0.png)

**Comment by ajoslin** [comment]
Good catch. jQuery will clobber our DOM events with `.` in them, noted.
