### ISSUE TITLE
bug: Can't type in ionic view

### ISSUE THREAD

**Issue by FranklinWaller** [driftyco/ionic#3389]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When you try to type with a view on this setup: http://codepen.io/anon/pen/NPobgz You have to type character by character. While this works without the ionic view.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-view-issues#58

**Comment by perrygovier** [comment]
Moved the issue over to the ionic view issues repo

**Comment by Fayozjon** [comment]
Franklin

http://orchiday.kz/otzyvy_foreks

24.03.2015, 14:59, "Franklin Waller" <notifications@github.com>:Type: bug

Platform: ios 8  webview

When you try to type with a view on this setup:  You have to type character by character. While this works without the ionic view.
