### ISSUE TITLE
bug: hide-nav-bar breaks views.forwardCache

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#3396]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I could not understand why my views were being cached, upon investigation it was due to hiding the nav bar on some screens. 

Flow:
Dashboard (nav hidden)
  -> Page 1 (nav not hidden)
 <- Back to Dashboard

When you then press back on Page 1 and look at the ion-nav-view, Page 1 is still present in the DOM (i.e. it's cached). Setting $ionicConfigProvider.views.forwardCache(false) does not help in this case. 

However the following removes the page from cache as expected:
Dashboard (nav not hidden)
 -> Page 1 (nav not hidden)
 <- Back to Dashboard</span>

<span is-issue-template></span>

Using RC1.

**Comment by dylanvdmerwe** [comment]
Any updates on the following? Often there are times when the navigation bar is hidden for whatever reason, and the inconsistent caching could raise unexpected bugs in apps.

**Comment by perrygovier** [comment]
Could you put this in a codepen?

**Comment by dylanvdmerwe** [comment]
http://codepen.io/anon/pen/vOymOR

Going to Page 1 should always give you a new value. This happens correctly when hide-nav-bar="false". The cache is not being cleared if the nav-bar is hidden.

**Comment by dylanvdmerwe** [comment]
Any updates on this?

**Comment by Hanruis** [comment]
I came across the same problem,  and  i try to find the reason from the source code. I search the keyword hide-nav-bar' and debug step by step in the chrome, but can not found some 'cacheView' logic through the process

**Comment by sebastien-p** [comment]
I also came across this issue, any update please?

**Comment by sebastien-p** [comment]
Weird thing is pressing the back button doesn't remove the forward view from the cache but swiping back (iOS) does. I set a breakpoint [in viewSwitcher.js line 330](https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/angular/service/viewSwitcher.js#L330) and saw that `transData.direction == 'none'` instead of `'back'` when pressing the back button. Hope this helps.

**Comment by sebastien-p** [comment]
There it is: in [navBarController.js line 214](https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/angular/controller/navBarController.js#L213-L215) the transition direction is explicitly set to `'none'` if the nav bar is hidden. So guys, what's the next step?

**Comment by affinionmobile** [comment]
Awesome sebastien on highlighting the problematic section. I am extremely frustrated by this as it's such an obvious bug that has yet to be addressed. I have no idea how to get around this either as I really need these items to get out of the cache when I leave the screens.

Ionic team?! @mhartington ?

**Comment by sebastien-p** [comment]
While waiting for some Ionic team feedback, here is what I did in my current app (it works as expected now):

```js

/** View associated controller **/

function onViewEnter() { $ionicNavBarDelegate.showBar(false); }

function onViewLeave() { $ionicNavBarDelegate.showBar(true); }

// https://github.com/driftyco/ionic/issues/3396
$scope.$on('$ionicView.enter', onViewEnter);
$scope.$on('$ionicView.leave', onViewLeave);
```

**Comment by dylanvdmerwe** [comment]
Any news on this from the Ionic team as yet?

**Comment by dylanvdmerwe** [comment]
Another month has passed, just wanted to check in to see if this has been looked at or fixed yet?

**Comment by affinionmobile** [comment]
???

Yolinda Liversage
Affinion Mobile Solutions
Phone: +27 (0) 11 463 2210
Fax: + 27 (0) 11 463 1841
Mobile: +27 (0) 83 443 1442
Yolinda@affinionmobile.com<mailto:Yolinda@affinionmobile.com>
www.affinionmobile.com<http://www.affinionmobile.com/>

[cid:image004.png@01CF317C.B96BF700]

**Comment by affinionmobile** [comment]
???

Yolinda Liversage
Cims South Africa
Phone: +27 (0) 11 463 8723
Fax: + 27 (0) 11 463 1841
Mobile: +27 (0) 83 442 1443
Yolinda@cimssa.co.za<mailto:Yolinda@cimssa.co.za>
www.cimssa.co.za<http://www.cimssa.co.za/>

[Description: cid:part1.08020701.00000709@apula.co.za]
Cims is an Authorized Financial Services Provider.

From: Yolinda Liversage
Sent: 20 January 2016 06:12 PM
To: driftyco/ionic; driftyco/ionic
Cc: Info; Dylan van der Merwe; Sabrina Lauro
Subject: AMS : [ionic] bug: hide-nav-bar breaks views.forwardCache (#3396)

???

Yolinda Liversage
Affinion Mobile Solutions
Phone: +27 (0) 11 463 2210
Fax: + 27 (0) 11 463 1841
Mobile: +27 (0) 83 443 1442
Yolinda@affinionmobile.com<mailto:Yolinda@affinionmobile.com>
www.affinionmobile.com<http://www.affinionmobile.com/>

[cid:image004.png@01CF317C.B96BF700]

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though and i will be happy to reopen it.(:

**Comment by sebastien-p** [comment]
Hi @jgw96! I still experience the issue using Ionic 1.3.0.

**Comment by panlina** [comment]
Still exists in 1.3.3. It's a surprise to find that `hide-nav-bar` interfere with view caching. Hope this issue to be fixed or explained.
