### ISSUE TITLE
bug: collection-repeat doesn't change items' dimensions in IE

### ISSUE THREAD

**Issue by yurikolesnikov** [driftyco/ionic#3399]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span> IE 11, Windows Phone 8.1

<span ionic-description>
collection-repeat doesn't change items' dimensions, it's always _width: 0px; height: 0px;_

The problem seems to be in variable *WIDTH_HEIGHT_REGEX*.
It's value is **/height:.*?px;\s*width:.*?px/**, but in IE in cssText *width* is located before *height*.

**Fix**: setting WIDTH_HEIGHT_REGEX to **/(height|width):.*?px;\s*(width|height):.*?px/** solevs the problem.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @yurikolesnikov!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3399). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3399)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ferryfax** [comment]
I had to use the following to get this to work-

var WIDTH_HEIGHT_REGEX = /(height|width):.*?px;\s*(width|height):.*?px/;

**Comment by ferryfax** [comment]
Hmm, that wasn't what I typed.  Here is what I really meant. Probably the same as you have.

![image](https://cloud.githubusercontent.com/assets/2124521/6879812/6bb390fa-d4d1-11e4-8824-4a6ccec53cf1.png)

**Comment by yurikolesnikov** [comment]
yes, you are right, it's the same

```javascript
/(height|width):.*?px;\s*(width|height):.*?px/
```

**Comment by zwloki** [comment]
I had to slightly modify the regex to make it work:
var WIDTH_HEIGHT_REGEX = /(height|width):\s?.?px;\s(width|height):\s?.*?px/;

**Comment by s134319** [comment]
Value change of WIDTH_HEIGHT_REGEX still necessary in v1.0.0 "uranium-unicorn".
Still works with this fix in IE11 and WP8.

**Comment by mattlewis92** [comment]
Confirmed that the regex provided by @zwloki fixes collection repeat on windows phone.

**Comment by balkin** [comment]
Same for me. This bugfix doesn't look very nice, but it works. Without that, our app is unusable on Windows and Windows Phone 8.

**Comment by CKGrafico** [comment]
The problem continues here :S
![error](http://i.imgur.com/pgQ7DaR.png)
inconsistent heights and widths only on windows, on the image I forced width: 100% and height: 130px but this second didn't work

**Comment by aasavad** [comment]
I added var WIDTH_HEIGHT_REGEX = /(height|width):\s?.?px;\s(width|height):\s?.*?px/; provided by @zwloki .The collection repeat size looks fine but the scroll is not working.I am not able to scroll down to see the full list.

**Comment by ruisilva450** [comment]
The fix that @zwloki provided does work for me and scroll is not broken but when I turn to landscape the width doesn't update. This need more research, please.

**Comment by qqilihq** [comment]
Hey guys, any news on this one?

**Comment by Michenux** [comment]
The fix is ok for me.
Don't know about orientation.

**Comment by ThinklabsGbR** [comment]
Any plans to include the provided fix in ionic-master?

**Comment by CKGrafico** [comment]
@mhartington :( ..

**Comment by ThinklabsGbR** [comment]
Workaround, which works (without significant performance loss) both in portrait as well as in landscape in IE10/11:

    //desired width / height of item
    var list_element_height = 100;
    var window_width = $(window).width();
    
    // prepare styles
    if ($('#closure-style').length == 0) {
        $('head').append(
                         $('<style/>', {
                            id: 'closure-style'
                        })
                         );
    }
    
    //define styles
    var styles =
    
    'ion-view[nav-view="active"] ion-item {' +
    (typeof window.cordova === 'undefined' ? 'height: ' + list_element_height + 'px !important;' : ''      )+
    (typeof window.cordova === 'undefined' ? 'width: ' + window_width + 'px !important;' : '' )+
    '}';
    
    //apply
    $('#closure-style').html(styles);

**Comment by ThinklabsGbR** [comment]
But another problem that occurs is, that in IE collection-repeat always renders all elements in the collection, there is no kind of pagination..even with this fix here..any ideas?

**Comment by mhartington** [comment]
We will not be supporting WP8X with ionic v1.

**Comment by CKGrafico** [comment]
Seriously @mhartington? did you try on W10?

**Comment by ruisilva450** [comment]
This is more related with IE than WP8X

**Comment by mhartington** [comment]
@CKGrafico Not yet, just upgraded to windows10, so will be looking at things on edge.

@ruisilva450 you are correct, it is more of an IE issue. For WP8.X, IE is the system webview, which we're not going to support.

**Comment by ThinklabsGbR** [comment]
How about normal desktop IE? IE9+

**Comment by CKGrafico** [comment]
Ok @mhartington @ThinklabsGbR these are my tests:
url: http://ionicframework.com/present-ionic/slides/#/31 -> http://ionicframework.com/present-ionic/slides/demos/collection-repeat/index.html
Chrome Windows 10: Obviously works perfect
IE 11 on Windows 10: Error
Edge on Windows 10 (Desktop): Works!
And.. Edge on Windos 10 (Mobile) **Works!**

**Comment by mhartington** [comment]
@ThinklabsGbR probably not going to focus on those. We're focused on making mobile apps.

**Comment by ThinklabsGbR** [comment]
Yeah of course, but merging this minor fix isn't a big deal in my opinion.

**Comment by jdnichollsc** [comment]
Hi guys, one question..
Any template for Windows 10? :+1: 

Thanks in advance, Nicholls

**Comment by CKGrafico** [comment]
Yep my template :+1: cordova-multiplatform-template.js.org

**Comment by lobo87** [comment]
using the collection-repeat as discussed in the documentation (http://ionicframework.com/docs/api/directive/collectionRepeat/) renders the ion-item to be 0px in height and width. this is in the case on windows 10 pro, build 10586.164 on both browser versions IE and Edge. Haven't tried the fix from above yet, but will do. This is the code i was using (i tried 44px and 44):

		<ion-item
			type="item-text-wrap"
			collection-repeat="benefitId in benefits"
			item-height="44px"
			href="#/tab/benefits/{{benefitId}}">
			{{ benefitId] }}
  		</ion-item>

Anyone other suggestions except the one from above?

**Comment by beat-at-hartwig** [comment]
@lobo87 I can confirm the issue

**Comment by jdnichollsc** [comment]
+1 for this issue! :/

**Comment by kirillgroshkov** [comment]
+1. Fixed with changed regex, but good to have it in master

**Comment by jdnichollsc** [comment]
Yes, what is the inconvenient to add the fix to master?

**Comment by jdnichollsc** [comment]
Hi guys!

See my directive to use ng-repeat on Windows, but use collection-repeat on Android, iOS, etc :dancers: 

Ion-Repeat: http://codepen.io/jdnichollsc/pen/EyPOee

Regards, Nicholls

**Comment by ADCJustinH** [comment]
I just lost my time on this... Why not add the updated regex to master so no one else does either? @mhartington

**Comment by qqilihq** [comment]
This is so sad.
