### ISSUE TITLE
bug: Cached Collection Repeat does not resize Horizonta

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3401]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Collection Repeat does not resize horizontally when cached. Tested on 1.0.0-RC.0 and 1.0.0-rc.1.

To repeat the problem, have 2 tabs, where one has a collection repeat. Make sure you load that tab by showing it. Click on the second tab. Resize the window or rotate the screen. Go back to the tab containing the collection repeat, it has not been resized.

Here's a pen http://codepen.io/kbenoit/pen/yyZqyB.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Easier to see here.

http://codepen.io/mhartington/pen/yyZRVR


Thanks for reporting this.

**Comment by ajoslin** [comment]
This works in nightly.

**Comment by kristianbenoit** [comment]
@ajoslin, if try @mhartington pen or mine, they both use nightly and the bug is still present. Tested on Chrome and Safari.

**Comment by mhartington** [comment]
Still seeing this as well. Reopening

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by JWesorick** [comment]
This is still a bug. You can still see it with this code pen. http://codepen.io/mhartington/pen/yyZRVR

**Comment by Ionitron** [comment]
Greetings @kristianbenoit!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
