### ISSUE TITLE
bug: Popup alert with horizontal and vertical scroll

### ISSUE THREAD

**Issue by ag-secret** [driftyco/ionic#3403]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

Windows 7 - Chrome
![web](https://cloud.githubusercontent.com/assets/10434389/6835094/303132c8-d317-11e4-8bba-b2a1bdf8fdca.png)

Asus Zenfone 5 - Android 4.4.2

![device](https://cloud.githubusercontent.com/assets/10434389/6835095/30319f38-d317-11e4-97df-b8bb2f9e2199.jpg)

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This should be fixed in master as of b8df44d4c44e47516032b96cac79147eb48afe4c
Try a nightly build and let me know you're still seeing it, but I'm going to close for now.
