### ISSUE TITLE
bug: Collection-Repeat does not refresh while cached

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic#3406]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This problem occur when an app has at least 2 views where one has a collection-repeat.

To repeat, charge the collection-repeat view. Go to the second tab. Change the data source provisioning the collection-repeat on the first view. Go back to the first view... The list is is empty... open a popover, type in a filter box and it comes back.

For some reason, I cannot trigger this problem on codepen, but taking the same code and running it through a server or opening from file:// does trigger the bug.

You can download the content of [this pen](http://codepen.io/kbenoit/pen/YPBdbX) or directly as a [zip file](http://codepen.io/kbenoit/share/zip/YPBdbX/).</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Ah, ok. thanks. So CR should fire a resize when it re-activates.

**Comment by perrygovier** [comment]
@kristianbenoit, I'm not seeing this anymore. are you?

**Comment by Ionitron** [comment]
Greetings @kristianbenoit!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @kristianbenoit!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
