### ISSUE TITLE
bug: memory leak with nested abstract states

### ISSUE THREAD

**Issue by michael8090** [driftyco/ionic#3412]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>`createView` will be invoked every time a state, which has two preceding abstract parent states, is activated.

reproducing steps:

1. ionic start abstractStates
2. change state `tab.dash` to `tab.dash.default` where both `tab` and `tab.dash` are abstract states, as below:

			.state('tab.dash', {
				abstract: true,
				views: {
					'tab-dash': {
						template: "<ion-view><ion-nav-view></ion-nav-view></ion-view>"
					}
				}
			})

			.state('tab.dash.default', {
				url: '/dash',
				views: {
					'': {
						templateUrl: 'templates/tab-dash.html',
						controller: 'DashCtrl'
					}
				}
			})

3. ionic serve and set an breakpoint at line `42206` inside `ionic.bundle.js`, in `createView`

4. switch between the first two tabs, and you can see the breakpoint is hit every time you switch from tab 2 to tab 1, and if you set an expression `viewHistory.views`, you can see that the views keep growing, as shown below: 

![screen shot 2015-03-26 at 8 57 12 pm](https://cloud.githubusercontent.com/assets/2306105/6846641/c4099e2a-d3fa-11e4-9fcb-af16ee7c4df7.png)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @michael8090!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3412). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3412)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Thanks, while we work on a fix, disabling the cache for that page should prevent a leak. 
```
$ionicConfigProvider.views.maxCache(0);
```
or 
```
$stateProvider.state('myState', {
   cache: false,
   url : '/myUrl',
   templateUrl : 'my-template.html'
})
```

**Comment by michael8090** [comment]
@perrygovier Thanks for the quick response, but it seems the workaround doesn't fix the leak. I tried disabling the caches both globally and just for that state, but the leak is still there.

**Comment by adamdbradley** [comment]
I wouldn't call this a memory leak because the way you've constructed the state and template is that you're navigating to another view.

**Comment by michael8090** [comment]
Hi @adamdbradley, it's correct that I'm navigating between two views. But why does navigating between two views result in a constantly growing of the views? 

1. if the growing views are the cached views, as we're navigating between two views, it seems more reasonable that only one cached view is needed in the navigating. So the views should not grow that way.

2. when we don't add a parent state for tab.dash(from "tab.dash" to "tab.dash.default"), the views don't grow. It doesn't make much sense if we assume it's the navigating action who makes the views grow.
