### ISSUE TITLE
feat: Support for Chocolatey Package Manager

### ISSUE THREAD

**Issue by Purus** [driftyco/ionic#3420]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Chocolatey is a package manager for windows. It can help us to setup Ionic CLI.

Windows 10 is going to use Chocolatey in its OneGet Package for package management.

https://chocolatey.org/</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#336

**Comment by perrygovier** [comment]
I don't think we'll add support for Chocolatey, but it's Josh's call, so I'll run it by him
