### ISSUE TITLE
feat: Add dynamic styling to button in ionicPopupService

### ISSUE THREAD

**Issue by sattarab** [driftyco/ionic#3423]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Can we add support for dynamic styling on the buttons in the ionicPopupService. I think this would be the last piece of the service which would make it pretty much complete.

I can submit a PR if you wish.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
What did you have in mind? You can already style directly using CSS. 

If you wanted to override the markup used itself and the logic, you want to extend the directive. We're going to adding an add-on marketplace soon, but I don't think we'll add a plugin model or options for custom popup designs in v1, but the add-on marketplace you can add your own (and get paid for them) or do so easily in v2
