### ISSUE TITLE
docs: Typo in list doc

### ISSUE THREAD

**Issue by pierredewilde** [driftyco/ionic#3426]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>At CSS List, http://ionicframework.com/docs/components/#list, second paragraph, there is a typo:

The list view is a very **versitile** and powerful component. 

should be

The list view is a very **versatile** and powerful component. 

Thanks,
Pierre</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Thanks!
