### ISSUE TITLE
disableBack in $ionicHistory.nextViewOptions fails sometimes.

### ISSUE THREAD

**Issue by hussainb** [driftyco/ionic#3427]
Hello,

I created the below view by using the 'stripe styled tabs'.
I wanted to mimic the sub tab functionality of other android apps. but couldnt find any docs on it in ionic so I created a three different routes for the tabs and just change the 'active' class for the selected tab.

What I noticed is that since I am just simulating sub-tabs the history should not change and the back button shouldn't be visible. 

So, I added the following in all the tab routes controllers

    $ionicHistory.nextViewOptions({
        disableBack: true,
        disableAnimate: true
    });

While interchanging/navigating between the tabs, the above code works for 4-5 times, but then, the normal history enabled behavior starts to take place, the view starts animating and the back button starts appearing.

![image](https://cloud.githubusercontent.com/assets/4962633/6886905/f8ffe0ee-d66b-11e4-9d87-8fcabe06e243.png)

**Comment by Ionitron** [comment]
Greetings @hussainb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3427). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3427)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by msalman** [comment]
Hi, 
I have a simple login based application in which user can access About menu with or without login, issue came with android hardware back button,

Login screen > About page > From Menu go to Login > Press hardware back button > Application Should get closed rather go to About page.

Below is the code for navigation to login screen.

```javascript
$scope.login = function() {
            $ionicHistory.nextViewOptions({
                disableBack: true,
                disableAnimate: true,
                historyRoot: true
            });
            $ionicHistory.clearCache();
            $ionicHistory.clearHistory();
            $ionicSideMenuDelegate.toggleLeft();
            $state.go('login');
        };
```

I am using ionic rc release 4 currently.

**Comment by perrygovier** [comment]
Could you put these in a codepen or something we can inspect?

**Comment by Ionitron** [comment]
Greetings @hussainb!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @hussainb!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by liamzebedee** [comment]
I recently encountered this issue, the way I solved it was changing `historyRoot` to false:

`$ionicHistory.nextViewOptions({ disableBack: true, disableAnimate: true, historyRoot: false })`

to 

`$ionicHistory.nextViewOptions({ disableBack: true, disableAnimate: true, historyRoot: true })`
