### ISSUE TITLE
bug: ionOptionButton + item-button-right does not work

### ISSUE THREAD

**Issue by clawish** [driftyco/ionic#3432]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See [this codepen](http://codepen.io/clawish/pen/YPgLvb) which is the List codepen where I only added the class `item-button-right` to the `ionItem` and added the code

    <button class="button button-clear button-positive">
         <i class="icon ion-ionic"></i>
    </button>
into the `ionItem` tag. As you see they don't get along with each other.

Please fix this, would be really helpful! :)</span>

<span is-issue-template></span>

**Comment by caseywatts** [comment]
I came across the same issue!

My short-term sloppy patch is to put this in my `style.css`, overriding part of what `item-button-right` tries to accomplish. This may be related to the `.item-complex` css rules.

```css
.item-button-right {
  padding-right: 0px;
}
```

**Comment by clawish** [comment]
works. thank you lots for the hotfix!

**Comment by jgw96** [comment]
Hello all! Since there is a workaround for this issue and we do not plan on making any big changes to our layout in Ionic 1 at this time I will be closing this issue. Thanks for using Ionic!
