### ISSUE TITLE
bug: ionic emulate ios shows white/basic screen

### ISSUE THREAD

**Issue by Icehunter** [driftyco/ionic#3434]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When I use:

"ionic serve" (browser based) it works fine.
"ionic emulate ios -l" works fine.
"ionic emulate ios" does not work.
"ionic run android" does not work.

What I see on android is a white screen, and when I press the hardware back button it flashes the blue background I have.

What I see on iOS is that the screen shows the login button and a image placeholder but it does not load anything else at all and buttons fail to function.

Everything was working fine up until we went home last Friday. This issue is now presenting itself to other developers and it was after we removed the platforms and re-added them back with the cli that this affected them.

Is there any information I can provide that would assist with an investigation or something private that can be discussed as the application is not public.

Ironically if I use the starter apps it just works fine.

Plugins:
org.apache.cordova.device
org.apache.cordova.console
com.ionic.keyboard
org.apache.cordova.globalization
org.apache.cordova.inappbrowser
org.apache.cordova.statusbar

Between the time we had it working just fine on fresh clones and this morning there have been no code changes to the repo.

I appreciate your time and thanks!</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#338
