### ISSUE TITLE
perf: Scrolling in forms with many textfields very laggy

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic#3439]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm using RC2. Usually scrolling on Android is working fine since I'm using Crosswalk. However in views that only consist of forms scrolling becomes really really bad. 

It seems that beginning a scroll with a finger over a textfield does introduce some sort of lag (but only sometimes). If the textfield has a label on the side, scrolling works fine as long as I start the scroll over the label, but doesn't work smoothly when I start with the finger over the textfield.

Would be great if you could test this, as this has been criticized by all testers of our app.

Best,
Andreas</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Can you provide a codepen so we're looking at the same thing? You may have better luck using native scrolling as well.

**Comment by Ionitron** [comment]
Greetings @fifafu!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
