### ISSUE TITLE
bug: List items being highlighted when trying to scroll

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic#3441]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm currently building my first app with Ionic (RC2) and it has been very nice so far. However I'm encountering one issue I'd like to fix. When trying to scroll in a list, the first item that is touched before scrolling will often become highlighted. I think there should be a longer delay before highlighting an item in the ion-list. Does anybody know where/how I can change this?
Currently there is a big difference when comparing this behavior to the native ios/android scrollview.

I have seen apps that were built with Ionic that didn't show this behavior, so it must be possible to fix this somehow...
Unfortunately all the starter apps and the frontpage app also have this issue.

The issue only appears if the webview is not scrolling before the first touch.

I'd be very happy if someone knew how to fix this, thanks a lot!

Also see this discussion:
http://forum.ionicframework.com/t/list-items-are-being-highlighted-when-trying-to-scroll/15403

Reapp (http://reapp.io) doesn't have this issue and it really makes a big difference, the app feels much more native if it doesn't highlight on every touch.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
So the big thing here is the fact that we're using js-scrolling as opposed to native scrolling. 
With js-scrolling, we're recreating the tapping/highlighting effect that happens with native scrolling. 

The accidental highlighting of items is an effect of what the tap tolerance is set at. The number it is set at is a nice middle ground where it works across all platforms and most use cases. 

Long term, we're planning to remove js-scrolling so something like this shouldn't be an issue.
Marking this for post 1.0

**Comment by igordeoliveirasa** [comment]
Is there any hack for today at least?

**Comment by fifafu** [comment]
@mhartington could you point me to the code where this is done? I'd like to experiment with it because it is really a big issue for us and can't really wait... :-)

**Comment by mhartington** [comment]
If you are up for it, https://github.com/driftyco/ionic/blob/master/js/utils/tap.js

But it's a touch balancing act between all platforms to make sure it works consistently so be prepared for that

**Comment by fifafu** [comment]
perfect, thanks a lot! I'll experiment with that.

**Comment by jackyon** [comment]
any updates for this?

**Comment by mhartington** [comment]
At the moment, no. Any changes would be big change to the framework so it will be looked at for a future release.

**Comment by jackyon** [comment]
@mhartington  thx, can't wait for this, because every time when I start scrolling, I feel i am overdue something.

**Comment by joeydi** [comment]
@fifafu Did you have any luck tweaking tap.js?

**Comment by supersantux** [comment]
hi,

this was closed, and so was the duplicate one 4014, but the problem is still there.  Is there a solution?

M

**Comment by gkucsko** [comment]
i also still have this issue, even with native scrolling. are we probably doing something wrong/non-ionic conform? using the following list structure:
`<ion-list><ion-item ng-repeat="place in places" href="javascript:void(0);" on-tap="foo()"></ion-item></ion-list>`

**Comment by hossam9995** [comment]
+1 is there any solution for this issue its really big issue ,, 
plz any solution

**Comment by RahulSD** [comment]
I am building an app which have only a few lists, having small number of items, so I did following workaround. This is not at all a good solution, but saved me from looking my whole app buggy due to few lists. 

In ionic.bundle.js, removed list item highlighting totally
```
          if (eleToActivate && ele.classList && ele.classList.contains('item')) {
            //eleToActivate = ele;
            break;
          }
```

Added a directive to <ion-item> which does tap-highlighting ... here binding on any touch events will give same effect on scroll, "click" is fired approx after 300ms, so that delay will be there in highlighting

```
.directive("taphighlight", function() {
    return {
        link: function(scope, elem, attrs) {
            elem.on("click", function() {
                var children = elem.children();                
                children.addClass("item_tapped");
                setTimeout(function() {
                    children.removeClass("item_tapped");
                }, 400);

            });
        }
    };
});
``` 

```
.item_tapped{
  background-color: #D9D9D9 !important;
}
```

**Comment by Defcon0** [comment]
Same issue here.
