### ISSUE TITLE
bug: statusbar

### ISSUE THREAD

**Issue by idaliramo** [driftyco/ionic#3449]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>statusbar background</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Sorry, but this isn't really a description of a bug. Please resubmit with a more detailed description and example that we can test against.

**Comment by idaliramo** [comment]
thank you , just a wanna change the font color in statusbar in ios 
![img_4412](https://cloud.githubusercontent.com/assets/2824575/6961981/f52cdecc-d927-11e4-8536-804a56186cbe.PNG)

in this exemeple i wanna set to white color ;)
