### ISSUE TITLE
bug: ui-router breaks on google maps in rc2

### ISSUE THREAD

**Issue by psimondk** [driftyco/ionic#3452]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Maybe related to #3233

I have a 'tabs' based app on appstore and playstore that is using ionic beta14 but breaks on rc2. The app uses google maps among other technologies.

The issue is that when the view containing the google map is revisited after the initial draw I get the following error:

  TypeError: Cannot read property 'childNodes' of undefined
     at compositeLinkFn (ionic.bundle.js:15364)
    at compositeLinkFn (ionic.bundle.js:15364)
    at nodeLinkFn (ionic.bundle.js:16007)
    at compositeLinkFn (ionic.bundle.js:15361)
    at nodeLinkFn (ionic.bundle.js:16007)
    at compositeLinkFn (ionic.bundle.js:15361)
    at publicLinkFn (ionic.bundle.js:15240)
    at self.appendViewElement (ionic.bundle.js:47720)
    at Object.switcher.render (ionic.bundle.js:45973)
    at Object.switcher.init (ionic.bundle.js:45893)

I have tried to:

1. Upgrade the ionic lib in the Beta 14 project to rc2
2. Create a new blank rc2 app that I copy my own code in to and re-install all js libs and plugins
3. Google around for a solution and ...
4. Fiddle with view cache settings (in the beta14 version cache is off)
5. Fiddle with google map parameters

I strongly suspect the angular view router to be the culprit here. angular 1.3.6 is used In beta 14 and angular 1.3.13 is included by defaul in rc2. 

As I use git I can simply revert back to the beta 14 version, but that does not really solve the problem longterm. I have not attempted to downgrade angular yet.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @psimondk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3452). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3452)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by psimondk** [comment]
The call to the function childLinkFn at line 15364 in the ionic.bundle receives an undefined node when you do have markup like the following:

` <ion-view title="{{map_name}}">
   <ion-content 
    has-header="true" padding="true" scroll="false" data-tap-disabled="true">
      <div id="the_map">
      	<h4><ion-spinner></ion-spinner>&nbsp;&nbsp;Henter butiksdata ...</h4>
      </div>
    </ion-content>
  </ion-view>`

The solution is to not use the `<h4>...</h4>` tags like so:

  `<ion-view title="{{map_name}}">
   <ion-content 
    has-header="true" padding="true" scroll="false" data-tap-disabled="true">
      <div id="the_map">
      	<ion-spinner></ion-spinner>&nbsp;&nbsp;Henter butiksdata ...
      </div>
    </ion-content>
  </ion-view>`

I will close the issue as there is a workaround but will consider it reported for the team to handle at some convenient time.
