### ISSUE TITLE
bug: heightGetter does not work with dynamic collection item height

### ISSUE THREAD

**Issue by kirrg001** [driftyco/ionic#3453]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>hey,

we are using dynamic height with collection-repeat and infinite list.
here a small impression how its integrated (very basic stuff):

HTML
````
    <div>"
         collection-repeat="item in items"
         collection-item-height="item.isDivider ? 40 : 80"
         collection-item-width="100%"
         ng-class="{ 'is-divider': item.isDivider }">
         .....
    </div>

    <ion-infinite-scroll
        ng-if="hasMore()"
        on-infinite="loadMore()()">
    </ion-infinite-scroll>
````

JS
````
$scope.loadMore = function() {
   asyncCallForLoadMore
     .then
         var replaceItems = [];

         for ....
            add dividers if needed
            add items blubb

         $scope.items = replaceItems
         $scope.$broadcast('scroll.infiniteScrollComplete');
}
````

At the moment we replace all items we the new items, **but we tried it also simply with extending the items, its not related to the problem.**

**If i don't use dynamic height, it works perfect, but i need dynamic height.**

The problem we get is, after scrolling and loading some items, the list gets render problems. it has kind of jumps (looks like something is wrong rendered)

i took a look at the ionic code and discovered the following line:

ionic.bundle.js 49824
`````
      estimatedHeight = heightGetter(0, data[0]);
`````

this line always takes the first element in the data (items) array and this causes my problem. 

1. element in array is a divider (for example 40px)
2. element in array is not a divider (for example 100px)

**if i change this line to this example, the rendering is fine.**
`````
      estimatedHeight = 100 // heightGetter(0, data[0]);
`````

Or if i put as first element an element with 100px height, it also works.

Thanks you so much!
kirrg
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kirrg001!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3453). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3453)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlegenhausen** [comment]
+1

**Comment by david-zacharias** [comment]
+1

**Comment by perrygovier** [comment]
Does setting it as a string with `+ 'px'` added help?

**Comment by pamo85** [comment]
yes issue still appears.
As long as very first row height is not highest, list starts to jump on update

**Comment by Ionitron** [comment]
Greetings @kirrg001!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
