### ISSUE TITLE
bug: Popover memory leak ?

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#3463]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I try to repeatedly click on a simple popover (over 20 times) and it seams that number of event listeners in time line are increasing. I assume that this is the leak. The simple app that I made is on rc2 but this behaviour happens on 14. also. 
I also assume this behavior increase the leak if I put more logic around popup what happens in my other app, this is only isolated case with popover only.

This is the link to my app
JS heap size after garbage collecting slowly increasing in steps. 
1st drop 5115528 , 2nd drop 5174500, 3rd drop 5251920, 4th drop 5311048

Source</span>

<span is-issue-template></span>

**Comment by szuzul** [comment]
https://github.com/szuzul/popoverApp

![78232a98-d964-11e4-8058-a9d74f05c037](https://cloud.githubusercontent.com/assets/1090963/6968734/340fd662-d969-11e4-80c4-7aabac3228ae.png)

**Comment by perrygovier** [comment]
This should be fixed in 218605f013d0c959cc4fed64b0de52abddaca414

**Comment by perrygovier** [comment]
well, before I get too excited, looks like the line I changed was recently added. Can you confirm if this does or doesn't impact the leak you see?

**Comment by szuzul** [comment]
Sorry didn't see notification about your message.. I'll check it during the day.

**Comment by szuzul** [comment]
It seems that with rc5 this issue is not longer present on the popover. 
![memoryok](https://cloud.githubusercontent.com/assets/1090963/7409999/46621a46-ef2b-11e4-9c3b-22106d22fcf1.png)
