### ISSUE TITLE
perf: Performance issue with google maps

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3468]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>People are noticing performance loss with phonegap-googlemaps-plugin
Here is topic https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/426
Luukschoen (https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/426#issuecomment-89212970) claims that it occurs with release candidate 0.
Can You post there some information to figure out what caused the problems?</span>

<span is-issue-template></span>

**Comment by Luukschoen** [comment]
I've tested a little bit further; already saw some performance drops before rc. 0. Huge drop with rc 0 indeed.

**Comment by perrygovier** [comment]
I'm not terribly familiar with the plugin, most people saw a slight performance gain with RC0.

Can you provide a sample project we can use to inspect in more detail.  If that's not possible, I'm going to be looking at what DOM events fire, searching for unusually large call stacks, and memory leaks. 

A place to start might be adding a console log here and seeing how many times it fires:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L2429

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @piernik!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
