### ISSUE TITLE
bug: For your info: EACCESS on adding platform with 1.0.0 rc2

### ISSUE THREAD

**Issue by bitflower** [driftyco/ionic#3469]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I had to chmod -R +x hooks to be able to add platforms (in my case ios).

Just in case anyone experiences similiar problems.

Cordova 4.3.0
IONIC cli 1.3.19

The error was:
Running command: .../hooks/after_prepare/010_add_platform_class.js 
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at Object.exports.spawn (child_process.js:988:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:131:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bitflower!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3469). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3469)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jessamynsmith** [comment]
I am having the same issue.

**Comment by bunajim75** [comment]
Same issue with me after updating to ionic CLI 1.3.19

**Comment by ronyrun** [comment]
Same issue. last CLI

**Comment by fuzzyflop** [comment]
Installed ionic for first time, version 1.3.19.

Same issue as well, on OS X 10.10 and Ubuntu 14.10.

**Comment by ronyrun** [comment]
OK I solved thé issue with : -R 0777 hooks

**Comment by fuzzyflop** [comment]
> chmod -R 0777 hooks

confirmed working.

**Comment by grillorafael** [comment]
I was having the same issue but I ran ```chmod +x``` and everything worked fine

**Comment by brodybits** [comment]
I just installed Ionic, ionic --version outputs 1.3.19, and I get the same issue when I run `ionic platform add android`. I discovered http://forum.ionicframework.com/t/how-to-fix-this-error-spawn-eacces/20490/5 which is the same issue. I find this very disturbing for someone just getting started. Can we please get this fixed ASAP?

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#375
