### ISSUE TITLE
bug: header scrollTop used with tabs scrolls all views

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic#3471]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I'm having trouble with scrollTop and tabs in Ionic. When you click on header (to scroll on top of the view), il you have some tabs, all tabs view scroll to top, and not only the active view.
Moreover, in my case, this scrollTop (clicking on header) recalculate `collection-repeat` width with parameters of active view (even if it's not the active view).

I don't know if I'm really clear so, here is my app. I have (mainly) 3 tabs with a list on each : 
![Tab 1](http://ionic-forum-uploads.s3.amazonaws.com/10703efd61cb0cf36f180da39743ee75c6683000cda32.png) ![Tab 2](http://ionic-forum-uploads.s3.amazonaws.com/107046a5a516eb0eedd097b581f1d37637ac5fd9c070a.png) ![Tab 3](http://ionic-forum-uploads.s3.amazonaws.com/10705493aa4d48911d94443464e46ca251a95b311a358.png)

If I scroll a little bit on each, and decide to scroll to in one view (clicking on header), all the view are scrolling to top :( 

An other thing, if I choose to scrollTop on 'Sessions' or 'Programme' view, the 'Participants' view is scrolling top but as this list uses collection-repeat, it also recalculate its dimentions and as the active view has 3 elements on top, it ends looking like this : 

![Tab 2 problem](http://ionic-forum-uploads.s3.amazonaws.com/10706e44887ab88b4df04824e28ed3100eaadcd6994ea.png)

Not really cool... Clicking on the header on this view correctly recalculate this `collection-repeat` (comes back to normal). This happen even if I fix the width using `item-width="100%"`.

I didn't have time to setup a codepen reproducing this 'bug' right now, I'll do it next weekend if my current explanations are not clear enough.

The code of my app is public and you can find related views here : https://github.com/saloonapp/ionic-app/tree/947e03cc86652ad34f4f95a28f85897fea226fc8/www/views/events</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
@loicknuchel yeah, a codepen would help with this. It seems like there are a few different things going on here and it would be great to get a separate look at the all

**Comment by loicknuchel** [comment]
Hi, I will try to reproduce this on codepen at the end of april, I'm quite full right now.

**Comment by Ionitron** [comment]
Greetings @loicknuchel!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
