### ISSUE TITLE
bug: beta6 to rc2 - scope problem

### ISSUE THREAD

**Issue by tigrus** [driftyco/ionic#3473]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have code like this:
```
  <ion-side-menus>
    <ion-side-menu-content>
        <ion-nav-bar class="bar-dark bar-header">
          <ion-nav-buttons side="left">
            <button class="button button-icon button-clear ion-navicon" menu-toggle="left">
            </button>
          </ion-nav-buttons>
          <ion-nav-buttons side="right" class="no-top" ng-if="user">
            <button class="icon-right ion-plus button">
              {{user.balance | currency }} &nbsp;&nbsp;
            </button>
          </ion-nav-buttons>
        </ion-nav-bar>
        <ion-nav-view animation="slide-left-right" name="menu-content"></ion-nav-view>

    </ion-side-menu-content>
    <ion-side-menu side="left">
          <ion-header-bar class="bar-positive" href="#/fantasy/home">
          </ion-header-bar>
          <ion-content class="has-header">
              <ion-list>
                <ion-item nav-clear menu-close href="#/home">
                  Home
                </ion-item>
                <ion-item nav-clear menu-close href="#/login" ng-if="!user">
                  Login
                </ion-item>
                <ion-item nav-clear menu-close href="#/games/all">
                  View All Games
                </ion-item>
                <ion-item nav-clear menu-close href="#/games/my">
                  My Games
                </ion-item>
                <ion-item nav-clear menu-close href="#/logout" ng-if="user">
                  Logout
                </ion-item>
              </ion-list>
            </ion-content>
    </ion-side-menu>
  </ion-side-menus>
```
Line: 
`
          <ion-nav-buttons side="right" class="no-top" ng-if="user">
`
not works. 

Line:              
`  <ion-item nav-clear menu-close href="#/logout" ng-if="user">`
works. 

In beta6 both line works. In rc2 - first line not working. 

`{{user.balance}}` - works when removing if statement. 

Where to dig? </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tigrus!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3473). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3473)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tigrus** [comment]
Looks like trouble in rc2 with this line: 
<ion-nav-buttons side="right" class="no-top" ng-if="user">

**Comment by zane-insta** [comment]
I am having the same problem.

**Comment by piernik** [comment]
Me too - looks like `ion-nav-buttons` copies `$scope` and not updates it

**Comment by piernik** [comment]
Here is my bug: http://codepen.io/piernik/pen/NPQqgG
Click `Go to list` then `first` - title is default `Item`. Then click `second` title changes to `Long first title`

There is a bug I think

**Comment by perrygovier** [comment]
Directives copy their parent's scope in the OOP fashion where once they're instantiated they don't automatically update. Does using `$parent.user` help?

**Comment by tigrus** [comment]
@perrygovier no. Only remove of `ng-if` helps. `ng-if="true"` also not working.

**Comment by piernik** [comment]
@perrygovier have You looked at my codepen? There is bug for sure. Look like navbar is refreshing scope too early - when scope isn't set yet.
I think @tigrus has the same problem.

**Comment by Yuripetusko** [comment]
@piernik  I don't think there's a bug in ionic,It all works for me here: http://codepen.io/Yuripetusko/pen/MYNVxz

**Comment by piernik** [comment]
@Yuripetusko even in You codepen it's not working well.
Click `Go to list` then `first` - title is ok
then `second` title is ok
then `first` again - title is wrong
navigate a little - title is not always changing as it should

**Comment by Yuripetusko** [comment]
@piernik  Yes you are right! I can see it now. I updated code a little bit so it's cleaner for ionic developers to see the issue. http://codepen.io/Yuripetusko/pen/MYNVxz

Basically if you go to list, then click first item, then click second item, and then click first one again the title doesn't update even though scope value is definitely updated

**Comment by adamdbradley** [comment]
@tigrus As for the showing and hiding a button in the nav-bar, can you fork this codepen and replicate the issue: http://codepen.io/adamdbradley/pen/azereK?editors=101

**Comment by piernik** [comment]
@adamdbradley have You looked at mine and @Yuripetusko's examples? (http://codepen.io/piernik/pen/NPQqgG and http://codepen.io/Yuripetusko/pen/MYNVxz)
You have there bug on a plate.
I think problem with navbar when changing to the same state but with different params.

**Comment by mhartington** [comment]
@piernik looking at your codepen, it should't even work. 
At first glance, there shouldn't be a nested ion-nav-view in list.html. This could be the main cause of confusion with in the apps history logic. There could be a much simpler way of doing what you are trying to do.

**Comment by piernik** [comment]
@mhartington nested view are common thing in ui-router. 
This is only an exmaple to isolate bug.
In real app I need to use nested view because of different data handling - data which is downloaded by `app.item`'s resolve and then use different views to handle this data (ex. `app.item.details`, `app.item.gallery`, `app.item.map`). That way I don't have to resolve data for every view  - data is simply the same - I also don't have to work on difficult data cache.
Off course I would be able to do it differently (without nested view) but:
1. I didn't see in Your docs that I shouldn't use nested view
2. Only navbar is problem - everything works fine
3. Ad I said in ui-router nested view this in common thing.

Now is my question - should I rewrite my app or You can fix the problem?

**Comment by mhartington** [comment]
Right, nesting views is common with ui-router, but for a mobile app paradigm it's not really advised unless you're making an abstract state. `ion-nav-view` is a container of many views that slide in and out, and take over the entire screen. 

You should probably rewrite the structure and not use a nested ion-nav-view

**Comment by piernik** [comment]
I see that in router I can't use `controller` with `abstract` state. why? I thinks it's possible in ui-router
Here is my code
```
.state('app.item', {
	url: "/item/:id",
	abstract: true,
	views: {
		'page@app': {
			controller: "itemCtrl as vm"
		}
	},
	resolve: {
		itemData: ['psDane', '$stateParams', function (psDane, $stateParams) {
			return psDane.pobierzDaneAtrakcji($stateParams);
		}]
	}
})
.state('app.item.info', {
	url: "/info",
	views: {
		'page@app': {
			templateUrl: "app/atrakcja/atrakcja-info.html"
		}
	}
})
.state('app.item.map', {
	url: "/map",
	views: {
		'page@app': {
			templateUrl: "app/atrakcja/atrakcja-mapa.html",
			controller: "atrakcjaMapaCtrl as vm"
		}
	}
})
```
`app.item` state should be only for common controller for both child states but it is never triggered when going to `app.item.info`
Controller without view is not working either:
```
.state('app.item', {
	url: "/item/:id",
	abstract: true,
        controller: "itemCtrl as vm",
	resolve: {
		itemData: ['psDane', '$stateParams', function (psDane, $stateParams) {
			return psDane.pobierzDaneAtrakcji($stateParams);
		}]
	}
})
```

**Comment by mhartington** [comment]
You can use controllers on abstract states. @piernik please post about this in the forum, it's not really relevant to the issue.

**Comment by tigrus** [comment]
Played with codepen. 

Working: 
http://codepen.io/anon/pen/zGxYGz

Not working: 
http://codepen.io/anon/pen/NqPWNP

If we move `ng-if` to `ion-nav-buttons` - it's ignored. If it is inside `ion-nav-buttons` - it works. 

I think, ionic must throw warning about `ion-nav-buttons` directive.
