### ISSUE TITLE
bug: Side Menu Not Closing When Clicking on Button

### ISSUE THREAD

**Issue by Purus** [driftyco/ionic#3476]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The Side menu has a button and when clicking on it, the main view changes. But the side menu does not close and still be visible.

Ideally when user does some operation on the side menu, the side menu should close.

http://codepen.io/Purus/pen/WbBdGq</span>

<span is-issue-template></span>

**Comment by brandycarney** [comment]
This isn't a bug. 

The button doesn't close the side menu because it doesn't have the menu-close attribute on it. The other items do. If you add the menu-close directive the menu will close.

**Comment by brandyshea** [comment]
This isn't a bug.

The button doesn't close the side menu because it doesn't have the menu-close attribute on it. The other items do. If you add the menu-close directive the menu will close.

**Comment by Purus** [comment]
Thanks @brandyshea .

For others who is having this question:

http://ionicframework.com/docs/api/directive/menuClose/

**Comment by mubasshir** [comment]
menu-close closes menu that's true but it also clears history. What if I what's to maintain history?

**Comment by brandyscarney** [comment]
@mubasshir Please check the forums: https://forum.ionicframework.com/t/is-there-a-way-for-using-menu-close-without-resetting-the-views-history-stack/22531

**Comment by skydevelopers** [comment]
use `menuClose `  for closing the menu or drawer , working on my end. eg.

` <ion-item  menuClose> `

[skydevelopers](www.skydevelopers.net)
