### ISSUE TITLE
bug: ionic go down when receive a 302 reponse on proxy

### ISSUE THREAD

**Issue by jmaquet** [driftyco/ionic#3477]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic 1.3.16 on Ubuntu 14.04

I created a proxy in ionic.project to test a connexion webservice :
"proxies": [
      {
        "path": "/ws/connect",
        "proxyUrl": "http://xxx/api/v1/user"
      }
    ]

I'm using "ionic serve" to test.

Systematically when i receive a 302 code (found) from the webservice, my ionic server shut down and i receive the following response :
POST http://localhost:8100/ws/connect net::ERR_CONNECTION_REFUSED
2livereload.js?snipver=1:191 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I have to restart my ionic server manually. For all the other codes : 200, 201, 403, 405, 404, 500 i have no issue.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#374
