### ISSUE TITLE
bug: $ionicView.clearCache() breaks tabs with multiple views

### ISSUE THREAD

**Issue by bodinaren** [driftyco/ionic#3478]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I found a problem with $ionicView.clearCache(). I have a tab-based app in which I want to clear the view cache at certain times. Check this [codepen](http://codepen.io/anon/pen/vEMydG?editors=101): 

Note that in tab 1 and tab 2 I have two views like so:

```html
<ion-tab>
  <div ui-view="tab1-top" /> //(shown in gray background)
  <ion-nav-view name="tab1">
</ion-tab>
```

Now when you clear the cache by clicking any of the "Clear cache"-buttons, Tab 1 and Tab 2 (except the one you currently have active, if either) will stop working. However, Tab 3 which only has an ion-nav-view (no ui-view) works just fine.

I've narrowed down the problem to [this commit](https://github.com/driftyco/ionic/commit/3628ebac16e5d2924c158c18d748403f4ff12b8b) (js/angular/directive/tab.js:181). Removing this line and everything seems to work just fine, but I suspect it re-introduce the [initial problem](https://github.com/driftyco/ionic/issues/2664) the commit intended to fix?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bodinaren!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3478). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3478)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
wow, tabs with multiple views in a single state wasn't something we were planning on supporting. If you're saying it did work until recently though, we'll take a look. 
The codepen had some syntax errors in it. Here's a version that runs smoothly: http://codepen.io/perrygovier/pen/VYozmp

**Comment by adamdbradley** [comment]
You're right in that removing that line will cause a regression in caching. The feature of having a `ui-view` sitting next to a `ion-nav-view` which is inside a tab is not one we'll support for the v1 release.

**Comment by chris08002** [comment]
I have the same issue with this tab configuration:

  <ion-tab title="Crear job" icon="icon ion-plus-round tab-light" href="#/tab/createjob">
    <ion-nav-view name="tab-createjob"></ion-nav-view>
    <div ng-show="isOffline==true" class="bar bar-subheader bar-assertive">
      <h2 class="title">Offline: No tienes internet</h2>
    </div>
  </ion-tab>

The <div> causes that $ionicHistory.clearCache() destroys the views. Am I not allowed to do anything else than one <ion-nav-view> inside the <ion-tab>? Any other suggestions to make a header bar in the tabs to show "Offline" state?

**Comment by siada** [comment]
You also encounter this issue if you set:
`$ionicConfigProvider.views.maxCache(0);`

On your app, you will end up with tabs that work once and when you go to re-visit them, they will no longer work.
