### ISSUE TITLE
scroll performance on huge list

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#3486]
_From @karneaud on March 13, 2015 23:41_

Been trying to improve the performance of using list with huge number of list items using the beta-14. 

as you can see from this demo kendallarneaud.me/mobile/android/AATT/version/0.0.2.3/ 

I've tried using my own list and infinite-scrolling implementations but on an iphone 4 running iOS 7.x. It quits the Safari browser after a certain number of times.

I'm trying to understand what the cause is but can't figure it out. hoping someone can shed some light on it as this performance issue is a huge setback for the framework

_Copied from original issue: driftyco/ionic-site#255_

**Comment by perrygovier** [comment]
@karneaud, I'm having trouble with your example. It sits as loading indefinitely.

**Comment by karneaud** [comment]
Yeah... sorry about that... the server for which i get as my data source from seems to be down. project is on hold until I can get it sorted out

**Comment by Ionitron** [comment]
Greetings @mhartington!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @mhartington!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
