### ISSUE TITLE
bug: Cached views and UI-router resolves

### ISSUE THREAD

**Issue by jackrr** [driftyco/ionic#3487]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When transitioning to a cached state ui-router resolves get triggered, but the updated resolved value is not available in the controller being entered (a cached value remains from when the controller was first initialized).

This has been brought up a couple times the ionic forums:
* http://forum.ionicframework.com/t/cached-views-and-ui-router-resolves/15467
* http://forum.ionicframework.com/t/state-resolving-and-cached-views-in-beta-14/17870

See pen: http://codepen.io/anon/pen/KwoWeq
_This codepen was provided by **edolix** from the second forum linked to above_

Any chance a fix for this could be seen in the next release candidate? Would be possible to get access to the updated resolves in the ionicView.[]Enter callbacks?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jackrr!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3487). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3487)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tkem** [comment]
I experience the same issue, but my suggestion would be too*not* trigger resolves at all when cached views are re-entered, so no need to access the updated resolves. IMHO this would be more in the spirit if cached views.

**Comment by perrygovier** [comment]
@tkem is correct. Resolves wont re-resolve when returning to a page since the controller is resuming a cached state, not recreating itself. Turning off Caching on that state should resolve the issue. 

Let me know if it does not.

**Comment by tkem** [comment]
"should resolve the issue" - pun intended? ;-)
I'll check turning off caching later, but I still want my cake and eat it, too,  meaning I'd like cached views to bypass the state.resolve on re-enter. Any chance this will be implemented any time soon, or should I re-think/redesign my application logic?

**Comment by msevestre** [comment]
"Resolves wont re-resolve when returning to a page "

I think that the behaviour already. It's also what I am experiencing in my
app. Resolve is not called a second time on cached views....
Are you sure that your view is really being cached?

**Comment by tkem** [comment]
I could swear this was the case (with beta 14 and rc2), but since you experience otherwise, I'll re-check.

**Comment by tkem** [comment]
@msevestre: Checked with `ionic-bower#1.0.0-rc.2`, and if I navigate "back", resolves are stilled called for my cached view.

**Comment by tkem** [comment]
@perrygovier: As expected, setting `cache-view="false"` in the view template behaves sensibly, as it will call my resolves and then create a new controller instance.  However, this is not the point of this issue.

**Comment by Ionitron** [comment]
Greetings @jackrr!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @jackrr!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by chrfritsch** [comment]
I still have this issue too. Why was that ticket closed?

**Comment by tkem** [comment]
Because Ionitron can, I suppose. I'm tempted to open another issue and just include a link to this one.

**Comment by jsappme** [comment]
I agree with :+1: 

I experience the same issue, but my suggestion would be to not trigger resolves at all when cached views are re-entered, so no need to access the updated resolves. IMHO this would be more in the spirit of cached views.
