### ISSUE TITLE
bug: Ionic View app won't display modal from a modal

### ISSUE THREAD

**Issue by rstreich** [driftyco/ionic#3488]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Ionic View App: A modal screen has a link to another modal. The other modal will not come up. Works fine in browser.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Could you provide of codepen demo of this?

**Comment by tsurrel** [comment]
Could it be a z-index problem ?
My app has the same behaviour (opening modals from modals), I had to impose an increasing z-index on each modal to be sure they would appear above one another.

**Comment by tlancina** [comment]
Moving this to the View issues repo.
