### ISSUE TITLE
bug: Ionic View App: Images not displayed

### ISSUE THREAD

**Issue by rstreich** [driftyco/ionic#3489]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Ionic View App: Images that are in a subdirectory of www/img are not included/viewable within the app.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Whats the path being used for the images?

**Comment by chris-olszewski** [comment]
I'm having the same issue, my path is `ng-src="/img/open.png"`

**Comment by tlancina** [comment]
Moving this to the View issues repo.

**Comment by levelup-fx** [comment]
Same issue here. 

My path is ng-src="/../img/cover.png", but I already tried with ng-src="../img/cover.png" and src="/../img/cover.png" (regular html).

Using iOS 8.3.
