### ISSUE TITLE
bug: Changing ion-nav-bar class not wirking

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3502]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Changing ion-nav-bar class is not working - here is example:
http://codepen.io/piernik/pen/qEzXMV

Please repair this.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Your ng-class was setup incorrectly.

http://codepen.io/mhartington/pen/EaBQRp

**Comment by piernik** [comment]
I used wrong example. I forgot to use side menu and `ion-nav-bar`
With `ion-nav-bar` it's not working - http://codepen.io/piernik/pen/qEzXMV?editors=101
