### ISSUE TITLE
bug: Extra white border bottom in the modal bar

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#3506]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>If you set the background color of the modal to a dark color and the border of the bar to 0 you can see an unwanted white border bottom.

 I thought it was because the border 0 was not doing effect but if you set the border to 1px solid red you can see the the bar with the red border and the unwanted white margin bottom.

Thats my code:

.modal{
	background-color: #000!important;
	color: #FFF!important;
}
.modal .bar h1.title{
	color: #FFF!important;
}
.modal .bar{
	background-color: #000!important;
	border: 0!important;
}

I tested on Chrome browser PC and Android 4.4 as a 'native hybrid' app and only happens on Android.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @danielfpedro, can you put this in a codepen that we can test against?

**Comment by danielfpedro** [comment]
Its just happening on Device. I just created a [repo on Github][1] so you can clone it and run on device.
[1]: https://github.com/danielfpedro/Ionic-Issue-Modal

The GIthub content was generated with `ionic start issue sidemenu` and I just added few lines to `www/css/style.css`, nothing more.

I take two print screens so you can have a better look:

Windows 7 Chrome Browser

![issue-browser](https://cloud.githubusercontent.com/assets/4269083/7137064/d2ffaf6e-e28c-11e4-8925-721b23dd0d90.png)

Android 4.4

![screenshot_2015-04-14-09-47-54](https://cloud.githubusercontent.com/assets/4269083/7137052/be888542-e28c-11e4-9512-89926f783d71.jpg)

**Comment by mhartington** [comment]
Change the css for the header-bar to this.

```
.modal .bar {
  background-color: #000!important;
  border: 0!important;
  background-image: none;
}
```

A background-image gradient is used to create the bottom border, since it ends up being more performant.
