### ISSUE TITLE
bug: Xcode __PROJECT_NAME__ missing in 6.3

### ISSUE THREAD

**Issue by CedNet** [driftyco/ionic#3507]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, don't know if this is the right place but I updated to version 6.3 of Xcode and now Xcode has no name for the project, instead __PROJECT_NAME__ displays on the Run-bar for the app. Also same in Organizer before submitting to App-store.

Something must've happened in Xcode 6.3, maybe you can tweak the ionic prepare ios function to re-add the project name. 

I've tried to remove and re-add the project and same thing happens. 

Ionic CLI 1.3.19
Cordova CLI 4.1.2
Xcode 6.3 build version 6D570</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#373
