### ISSUE TITLE
bug: Error when compiling app with Crosswalk

### ISSUE THREAD

**Issue by jesusbotella** [driftyco/ionic#3508]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi!

We added Crosswalk to our ionic project from ionic-cli when it was released and there wasn't any problem until today.

Today, after changing some stuff in one of our custom plugins, I had to rebuild the android project (platform remove, platform add, add crosswalk browser...) and when I try to compile it, it shows me a lot of errors related with crosswalk which I cannot resolve.

To compile in android, I had to change compileSdkVersion, and buildToolsVersion in gradle file to match api 21 because one of our custom plugins needs it. Also, I added some dependencies like volley and appcompat. But these stuff was added before and the project compiled successfully.

So I have not been able to know what is going on here.

I'm using Crosswalk 11.40.277.7, but I tested with other ones and the thing wasn't better.

I attach the errors which shows up:

/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:25: error: cannot find symbol
import org.apache.cordova.CordovaUriHelper;
                         ^
  symbol:   class CordovaUriHelper
  location: package org.apache.cordova
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:55: error: cannot find symbol
    private CordovaUriHelper helper;
            ^
  symbol:   class CordovaUriHelper
  location: class XWalkCordovaResourceClient
/Users/jesus/Savelist/android/platforms/android/src/org/apache/cordova/filetransfer/FileTransfer.java:692: error: cannot find symbol
        if (!isLocalTransfer && !Config.isUrlWhiteListed(source)) {
                                       ^
  symbol:   method isUrlWhiteListed(String)
  location: class Config
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java:93: error: cannot find symbol
        helper = new CordovaUriHelper(appView.cordova, appView);
                     ^
  symbol:   class CordovaUriHelper
  location: class XWalkCordovaResourceClient
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:68: error: XWalkCordovaWebView is not abstract and does not override abstract method getEngine() in CordovaWebView
public class XWalkCordovaWebView implements CordovaWebView {
       ^
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:132: error: constructor LoadUrlBridgeMode in class LoadUrlBridgeMode cannot be applied to given types;
        nativeToJsMessageQueue.addBridgeMode(new NativeToJsMessageQueue.LoadUrlBridgeMode(this, cordova));
                                             ^
  required: CordovaWebViewEngine,CordovaInterface
  found: XWalkCordovaWebView,CordovaInterface
  reason: actual argument XWalkCordovaWebView cannot be converted to CordovaWebViewEngine by method invocation conversion
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:144: error: constructor CordovaBridge in class CordovaBridge cannot be applied to given types;
        bridge = new CordovaBridge(pluginManager, nativeToJsMessageQueue, this.cordova.getActivity().getPackageName());
                 ^
  required: PluginManager,NativeToJsMessageQueue
  found: PluginManager,NativeToJsMessageQueue,String
  reason: actual and formal argument lists differ in length
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:116: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:286: error: cannot find symbol
        bridge.getMessageQueue().addJavaScript(statement);
              ^
  symbol:   method getMessageQueue()
  location: variable bridge of type CordovaBridge
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:295: error: cannot find symbol
        bridge.getMessageQueue().addPluginResult(result, callbackId);
              ^
  symbol:   method getMessageQueue()
  location: variable bridge of type CordovaBridge
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:328: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:584: error: method reset in class CordovaBridge cannot be applied to given types;
        bridge.reset(loadedUrl);
              ^
  required: no arguments
  found: String
  reason: actual and formal argument lists differ in length
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:587: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:612: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jesus/Savelist/android/platforms/android/src/org/crosswalk/engine/XWalkCordovaWebView.java:617: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
15 errors</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#372
