### ISSUE TITLE
bug: edge-drag-threshold doesn't work on the first view

### ISSUE THREAD

**Issue by campers** [driftyco/ionic#3511]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an issue where the edge-drag-threshold doesn't take effect on the first time view in a side menu, as someone else also found in http://forum.ionicframework.com/t/issue-with-ionic-side-menu-and-ignored-edge-drag-threshold/16378/2

I noticed that when you navigate to another menu view then it starts working as expected

The starter of the forum thread has this codepen demonstrating the issue
http://codepen.io/halfpt/pen/LELbXa
It's using beta14, which is where the regression occurred.  If you change the links to beta13 then it works as expected.  Also when changing to rc.2 the issue is still there.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @campers!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3511). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3511)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
Are you still seeing this in rc3? It seems to be working fine for me? Is it only on certain devices?

**Comment by campers** [comment]
Yeah I just changed the codepen to rc.3 and still saw the issue in Chrome and Safari.  I've also tested with an Android 4.4 phone.

**Comment by mhartington** [comment]
Looking into this more, it seems to work on that first initial view, login. What you have to do is set the nextView to be the root of the navigation.

http://codepen.io/mhartington/pen/raXqxW
```
 .controller('LoginCtrl', function($scope, $ionicHistory) {
  $ionicHistory.nextViewOptions({
    historyRoot: true
  })
})
```

**Comment by campers** [comment]
Thanks, that does the trick. Maybe add a note to the docs?

**Comment by FME-nstokoe** [comment]
So would you potentially have to make that call in every controller to make sure the edge dragging worked on the next view? That doesn't seem like a fix but rather a temporary workaround.

**Comment by mhartington** [comment]
No you wouldn't have to add that to every controller. The issue here is that the link from the login page messes with the side-menu's navigation logic. Another solution would be to put a menu-close attribute on the logic link.

http://codepen.io/anon/pen/WveoGV

**Comment by FME-nstokoe** [comment]
So why doesn't the edge dragging work on the 'Facts' page in that code pen, which also uses a menu-close attribute?

**Comment by mhartington** [comment]
Because of `enable-menu-with-back-views`, which is enabled by default. This will disable the menu on any non history root view.

http://ionicframework.com/docs/api/directive/ionSideMenus/#api

**Comment by FME-nstokoe** [comment]
Makes sense, thank you!

**Comment by iwan-uschka** [comment]
In the codepens mentioned in this thread (http://codepen.io/anon/pen/WveoGV and http://codepen.io/mhartington/pen/raXqxW) edge-drag-threshold doesn't work as expected. At least for me.
If you click on login, edge-drag-threshold works correct on the next page in the first tab. You can only open a side-menu if you start swiping close to the border of the viewport. If you switch to the next tab, you can swipe from anywhere to open side-menu.
Does this has anything to do with setting historyRoot:true in $IonicHistory.nextViewOptions? Or is it a bug?

Using two side-menus (left and right) you're able to open the side-menu on the opposite by continue swiping after closing a side-menu. That's not very good, especially if you set edge-drag-threshold to true or a Number > 0.
Is there a solution?

Thanks!
