### ISSUE TITLE
bug: ionic login from cli doesn't work

### ISSUE THREAD

**Issue by emotu** [driftyco/ionic#3514]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>After signing up for an ionic account via http://apps.ionic.io running the following commands do not work:

$ ionic login
$ ionic upload
$ ionic share

they all respond with the following error:

Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.3.19)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-rc.2
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.3 Build version 6D570
ios-sim version: 3.1.1
ios-deploy version: 1.5.0

However, using teh same credentials online works just fine.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#371
