### ISSUE TITLE
feat: Slide to transition forwards

### ISSUE THREAD

**Issue by mikesol** [driftyco/ionic#3515]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently, I am using an ionic slide box to create swipe transitions between 12 slides that all include lots of media (audio, video, images).  The individual transitions all work great, but the transition to and from the slide box to the main menu is slow.  One way (perhaps) to make this easier is to create a swipe-to-go-forward directive.  I see that ionic does this already with iOS-like swipe to go back, and I'm guessing (hoping) it wouldn't be much work to create a swipe-to-go-forward directive that took a parameter from somewhere for where to go.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mikesol!

Thank you for the feature request. The humans and I will review this further and possibly add it to our [Feature Request](https://trello.com/b/nNk2Yq1k/ionic-framework) board, if we feel it is appropriate for Ionic.

Thank you for allowing me to assist you.
