### ISSUE TITLE
feat: Simple addition - ion-tabs, add on-double-tap

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#3519]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>simple change in ionic.bundle.js:

```javascript
      //We create the tabNavTemplate in the compile phase so that the
      //attributes we pass down won't be interpolated yet - we want
      //to pass down the 'raw' versions of the attributes
      var tabNavTemplate = '<ion-tab-nav' +
        attrStr('ng-click', attr.ngClick) +
 ....
```

add the "attrStr('on-double-tap', attr.onDoubleTap) +" line, to allow double tap on ion-tab icons. Would be stellar! 

```javascript
      var tabNavTemplate = '<ion-tab-nav' +
      	attrStr('on-double-tap', attr.onDoubleTap) +
        attrStr('ng-click', attr.ngClick) +
        ..........
```

thanks guys!</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
At the time, Ionic is feature complete. Closing this and moving it to our trello board

https://trello.com/c/dWAJqgpH/92-add-on-double-tap-for-ion-tab
