### ISSUE TITLE
bug: ion-refresher not working when jsScrolling disable

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [driftyco/ionic#3520]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have referred some forum topics and i found a great way to disable the `jsScrolling` to have the native scrolling to work. <a href="http://forum.ionicframework.com/t/native-scrolling-android-testers-wanted/17059">Forum topic i followed.</a> I have disabled the `jsScrolling` to get the native kind of scrolling on the android device. When i do so, the scroll performance is good. But it is leading to another issue. `ion-refresher` is not working at all. If i enable the default scrolling(jsScrolling) in the app, `ion-refresher` is working fine, but the scrolling performance is not good. 

And even the side menu bar is not moving right side when we swipe right. When we click on the toggle button, the menu bar is moving right side. 

Can some one please let me know the solution for this issue.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This is a tricky problem. Android 4.4 and lower fire off a touchcancel event when scrolling, preventing the touchmove events we listen for. It should work fine on Android 5 or devices with crosswalk enabled. Can you confirm this?

**Comment by rajeshwarpatlolla** [comment]
I have tried with crosswalk too. But still no use. I haven't tested in android v5, as i don't have mobile with Android v5.

**Comment by perrygovier** [comment]
fixed in 71e89715eec85a03ceb04d53f8406dab75ac71dc
Thanks
