### ISSUE TITLE
docs: A demo is broken

### ISSUE THREAD

**Issue by carpiediem** [driftyco/ionic#3521]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>This demo is broken: http://codepen.io/ionic/pen/m</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Which page are you seeing that on?

**Comment by carpiediem** [comment]
Wow, my link got messed up somehow.  Sorry.

It's the last one, Collection-repeat.  It never goes past "loading..." and there's a pair of JavaScript errors:
```
POST http://codepen.io/boomerang net::ERR_CONNECTION_RESET
  Z.ajaxTransport.Y.cors.e.crossDomain.send
  Z.extend.ajax
  window.AJAXUtil._send
  window.AJAXUtil.post
  IFrameRenderer._storePenHTMLOnBoomerang
  IFrameRenderer._runLiveUpdate
  (anonymous function)
  Z.extend.proxy.Z.isFunction.o
Uncaught SyntaxError: Unexpected token u
```
http://codepen.io/ionic/pen/mFygh

**Comment by mhartington** [comment]
So this may just be an issue on codepens side.

```bash
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```

3000 items and images maybe too much for codepen.

http://ionicframework.com/docs/api/directive/collectionRepeat/ has a set up new codepens that can be used for reference. Will update the demo to those.
