### ISSUE TITLE
bug: Can't place <input> in <ion-list>

### ISSUE THREAD

**Issue by victorwoo** [driftyco/ionic#3523]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I need to use some feature of ion-list directive, for example ion-option-button.
But any approach of putting input in ion-list doesn't looks right.
Please have a look at this codepen:
http://codepen.io/victorwoo/pen/Eaqymr/</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Something like this can be done with just a few lines of css.
Note though, its ends up becoming a bit tough to swipe the item and reveal the option buttons, so it may not be great ux. 

http://codepen.io/mhartington/pen/myNWeM
