### ISSUE TITLE
docs: New path for android sdk for Android studio

### ISSUE THREAD

**Issue by ygayl** [driftyco/ionic#3539]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The path for the android sdk tools has changed and the documentation refers to the previous install path:

http://ionicframework.com/docs/ionic-cli-faq/#android-sdk

Please have a look to the answer gave by Nestor Turizo.

The new path is : /Users/{your OSX username}/Library/Android/sdk/tools

Thanks</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Thanks, will update this soon :+1:
