### ISSUE TITLE
bug: Modal can't find scrollview handle

### ISSUE THREAD

**Issue by chaffeqa** [driftyco/ionic#3545]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Modal with scope bound to $rootScope doesnt find child scrollview with delegate-handle due to `isActiveScope` returning false.

That method climbs to the $rootScope, but that doesnt have `historyId` returning 'root' like it looks like it should in the code.

I think a solution would be to not worry about history possibly for a modal scrollView, and always return it's `isActiveScope` as as long as the modal is open.

I do not really know how to go about knowing if the modal is open however, or else I would make a pull request.

Using 1.0.0-rc2</span>

<span is-issue-template></span>

**Comment by chaffeqa** [comment]
After diving deep into the code, I think fundementally the logic is a little off for all `ion-content` elements inside a modal.

The logic seems to be to only return the `$scrollDelegate` handle if that `scope` or one of its parent `scope`s is part of the `activeView` ( determined by viewHistory ).
The issue with this for modals is that the modal can be bound to a root scope or isolated scope.  This means that the logic says that this `ion-content` scroller is *not* active.

I think a corrected logic for the method `isActiveScope` should include some logic similar to:

```
if (climbScope.modal && climbScope.modal.isShown()) {
  return true;
}
```

Since fundamentally whether a modal's scope is active should be whether it is open or not.

I dove deep enough into this that I would not mind attempting a pull request to fix.  Let me know if that would be useful based on the logic I proposed above.

**Comment by Ionitron** [comment]
Greetings @chaffeqa!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
