### ISSUE TITLE
docs: Docs for CSS components using ion-ios7* icons

### ISSUE THREAD

**Issue by kevinsolsol** [driftyco/ionic#3546]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://ionicframework.com/docs/components/#item-icons (and more I would guess) makes reference to `<i class="icon ion-ios7-telephone-outline"></i>` - should have the 7 removed as this will not work with RC3 so would confuse new users</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-site#262

**Comment by mhartington** [comment]
Thanks for the heads up :+1: 
Will fix this on the site side of things.
