### ISSUE TITLE
bug: Doesn't work when click side menu icon

### ISSUE THREAD

**Issue by boris1117** [driftyco/ionic#3550]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am using latest Ionic 
* ionic -v ==> 1.3.20

I build default side menu application. 
* ionic start hello sidemenu

When I click on center of nav icon, I can't see activated icon image. But when I click on right edge of nav icon, I can see activated icon image.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Just a heads up, `ionic -v` gives you the version of the CLI, not the ionic.js file

Are you seeing this in the nightly builds?

**Comment by boris1117** [comment]
I did setup Ionic.

* npm install -g ionic.

So www\lib\ionic\bower.json file is
{
  "name": "ionic",
  "version": "1.0.0-rc.3",
  "codename": "radium-raccoon",
  "homepage": "https://github.com/driftyco/ionic",
  "authors": [
    "Max Lynch <max@drifty.com>",
    "Adam Bradley <adam@drifty.com>",
    "Ben Sperry <ben@drifty.com>"
  ],
  "description": "Advanced HTML5 hybrid mobile app development framework.",
  "main": [
    "css/ionic.css",
    "fonts/*",
    "js/ionic.js",
    "js/ionic-angular.js"
  ],
  "keywords": [
    "mobile",
    "html5",
    "ionic",
    "cordova",
    "phonegap",
    "trigger",
    "triggerio",
    "angularjs",
    "angular"
  ],
  "license": "MIT",
  "private": false,
  "dependencies": {
    "angular": "1.3.13",
    "angular-animate": "1.3.13",
    "angular-sanitize": "1.3.13",
    "angular-ui-router": "0.2.13"
  }
}

And www\lib\ionic\js\ionic.js file header is
/*!
 * Copyright 2014 Drifty Co.
 * http://drifty.com/
 *
 * Ionic, v1.0.0-rc.3
 * A powerful HTML5 mobile app framework.
 * http://ionicframework.com/
 *
 * By @maxlynch, @benjsperry, @adamdbradley <3
 *
 * Licensed under the MIT license. Please see LICENSE for more information.
 *
 */

If I add a button at right side of nav-header, the button works well. I can click on button center, top, left, right edge...
But left side is not .. Of course default back button too (<Back). I can't click at < part. Can only the word  (Back).

**Comment by mhartington** [comment]
Ahh alright, this is similar to https://github.com/driftyco/ionic/issues/3348

**Comment by perrygovier** [comment]
if #3348 is closed, can this be closed too then?

**Comment by mhartington** [comment]
Yep, just forgot to close it
