### ISSUE TITLE
bug: $stateChangeSuccess and $ionicHistory wrong $stateParams

### ISSUE THREAD

**Issue by akreienbring** [driftyco/ionic#3551]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I came across an issue that puzzeld me for 2 days now.
It consists of 2 issues but they may be related to the same rootcause.

I configured 2 states like this:
```
	.state('tab', {
		url: "/tab",
		abstract: true,
		templateUrl: "templates/menu.html",
		controller: "MenuCtrl"
	})
	.state('tab.location', {
		cache: false,
		url: '/beacon',
		params: {beaconUser:{}, beacon:{}},		
		views: {
			'menuContent': {
				templateUrl: 'templates/Beacon.html',
				controller: 'BeaconCtrl'
			}
		},
	})
       .state('tab.chat', {
	     cache: false,
    	     url: '/chat',
	     params: {chatUserId:{}},		
    	     views: {
    		    'menuContent': {
    			    templateUrl: 'templates/Chat.html',
    			    controller: 'ChatCtrl'
    		    }
    	     }
        })
```
First I navigate to the location state like this:
````
ui-sref="tab.location({locationUser: user})"
```
and from there to the chat state like this:
````
ui-sref="tab.chat({chatUserId: userid})"
```

First issue:
registering a listener to $stateChangeSuccess during the run method of a module
```
	$rootScope.$on('$stateChangeSuccess',function(event, toState, toParams, fromState, fromParams){
		if(toState.name == "tab.chat"){
			$ionicHistory.backView().stateParams //undefined	
		};
	});
```
note that $ionicHistory.backView().stateParams is undefined. Whereas registering the same listener in a controller
```
	$scope.$on('$stateChangeSuccess',function(event, toState, toParams, fromState, fromParams){
		if(toState.name == "tab.chat"){
			$ionicHistory.backView().stateParams //defined	
		};
	});

```
$ionicHistory.backView().stateParams is existing!

On to the second issue...

Even on the controller level the stateParams in history are incorrect. I would expect them to be exactly the same as the fromParams, but they aren't.
this offcourse leeds to an incorrect behaviour of my app when pressing the back button and going back to the location state.
For the time being I fixed that by 
```
	$scope.$on('$stateChangeSuccess',function(event, toState, toParams, fromState, fromParams){
		if(toState.name == "tab.chat"){
			$ionicHistory.backView().stateParams = fromParams
		};
	});

```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @akreienbring!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3551). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3551)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by rob3c** [comment]
Hi,
I just created a new issue that may be related that involves incorrect $stateParams when using cached views that shows up in the $stateChangeStart and $ionicView.enter events:

https://github.com/driftyco/ionic/issues/3884

Cheers,
Robert

**Comment by akreienbring** [comment]
Just checked the behaviour with version 1.2.1. Still the same :-(

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic 1? (1.3.0)

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
