### ISSUE TITLE
bug: SVG spinner crashes iOS app

### ISSUE THREAD

**Issue by pencilcheck** [driftyco/ionic#3554]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>http://forum.ionicframework.com/t/the-new-svg-spinner-crashes-ios-app/20986

I have attached a screenshot of the stacktrace in xcode.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
@pencilcheck, we're not able to reproduce the problem. Can you share more information to help us reproduce the issue, including codepen or zip of project, device version info, xcode version. Do you see memory usage spiking?

**Comment by perrygovier** [comment]
There's a few issues related to the Spinners and memory. I believe #3583 gets to the source of the problem.
