### ISSUE TITLE
bug: Ion-spinner spiral cannot be styled completely

### ISSUE THREAD

**Issue by pencilcheck** [driftyco/ionic#3555]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://forum.ionicframework.com/t/ion-spinner-spiral-cannot-be-styled-completely/20919

If you go to this page http://ionicframework.com/docs/api/directive/ionSpinner/

Open inspector and select one of the spinner (focus on the svg element), now add two rules under this selector

.spinner svg {
stroke: white;
fill: white;
}

All spinner changes their color to white completely but only spiral still has one arm is not styled.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Spinners are a bit special and also need
```sass
.spinner-stable .stop2 {
    stop-color: $spinner-stable-fill;
  }
```
See the end of `_spinner.scss` to see how we did it for the emotional colors
https://github.com/driftyco/ionic/blob/master/scss/_spinner.scss#L76
