### ISSUE TITLE
bug: ng-show/ng-hide don't work with ion-tab

### ISSUE THREAD

**Issue by rstreich** [driftyco/ionic#3557]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This was discussed and closed in https://github.com/driftyco/ionic/issues/727 with the use of ng-if as an alternative, however, ng-if has a side effect: If I am currently displaying the tab to hide when I trigger the condition to hide it, the state transition goes to the wrong state. In my case, if the "admin" tab is displayed and I log out--making the test "isAdminUser()" false--the state transition to the login page ("$state.go()) takes me to the wrong state. The only way I was able to make that work was to wait for the $ionicView.enter event on the login state before invalidating the "admin" tab.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rstreich!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3557). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3557)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Could you provide a codepen example of this?

**Comment by rstreich** [comment]
I munged together the starter tab app: http://codepen.io/anon/pen/doyazz

The "login" page has an 'allow' button and a 'disallow' button just to switch off a tab. Click on 'allow', go to the 'Account' tab, and then click 'Logout'.

**Comment by mhartington** [comment]
Hm, as far as using ng-hide, I would suggest using the tabs `hidden` attribute, which works better than ng-hide/ng-if.

As far as the view switching, the forum would be a better place to bring that up. 

Try the hidden attribute as let me know how that works.

**Comment by rstreich** [comment]
I had tried the hidden attribute once with no joy. Just found a hint of a reference to it on a forum, but since the post was a bit old, I may not have fiddled with it long enough. I resorted to adding the classes on the fly. I may not have tried it with '{{}}'.

I wrote it up as a bug more because I think it's important that your framework maintains basic Angular functionality.

**Comment by mhartington** [comment]
Well you can use ng-if on tabs without any issues. 
I think the main issue comes down to the removing of tabs while you are on the page. At this point, it breaks the navigation.

**Comment by Ionitron** [comment]
Greetings @rstreich!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by polkhovsky** [comment]
Here is an example based on your original Tabs demo codepen: http://codepen.io/LymanZerga/pen/vLmvvP
Once you log out the navigation breaks down completely.
