### ISSUE TITLE
perf: incoming call, outgoing call issue with sound

### ISSUE THREAD

**Issue by hunikim** [driftyco/ionic#3560]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I think It is not relate to ionic issue.
Might be Cordova problem. However, I think this is the best place to ask.

While I am watching the video(youtube iframe) and  receiving  call, I can hear little video sound. It is very annoying.

How can I pause video or mute sound when I get incoming call ?

**Comment by perrygovier** [comment]
I believe this is something the native OS does on its own. Are you just experiencing this in Android 4.4 or other OSes as well?

**Comment by Ionitron** [comment]
Greetings @hunikim!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
