### ISSUE TITLE
docs: Tinder-Cards not working

### ISSUE THREAD

**Issue by PesarisEntwickler** [driftyco/ionic#3561]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello Ionic-Team.

Great thing You ar doing and I am new here and I will try it out on my Windows 8.1 System. I am using eclips and dos-prompt to develop "ionic"-Apps. Target Devices should be ios and android.

I have all stuff installed, at the end, successfully. 
Showcase-App like sidemenu and tabs are runnig fine over the iPhone-App "ionic view"

Now I will try to use the tinder-card swiping. 
http://codepen.io/ionic/pen/nxEdH/

It is not working.
(I think, it is a issue of documentation)

Following the instructions to install it and/or the codes on "codepen.io", I cannot see, how is the right directory tree, when Adding an example. 

After downloading the "ionic-ion-tinder-cards", I had linked first the "lib/ionic-ion-tinder-cards/demo/index.html" and if this was not working, then the "lib/ionic-ion-tinder-cards/example/index.html" . Also this was not working. No pictures are shown, only the title "TD Cards".

My Question:
Can You please publish a directory tree of an app, what includes a code example from "codepen.io" or similaries

Regards Harald</span>

<span is-issue-template></span>

**Comment by DominikVogt** [comment]
For me its working

**Comment by perrygovier** [comment]
It's working fine for me. When you start a project based on this codepen, you'll need to update some things like the URLs of css and ionic bundle because they are protocol relative links and wont work in cordova's `file` protocol. 

Here's a repo to start from instead of codepen. 
https://github.com/driftyco/ionic-ion-tinder-cards
