### ISSUE TITLE
feat: feature: collection-repeat scrollToItem()

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#3562]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

I needed a scrollToItem() method for the `collection-repeat` directive and I hacked this solution. It seems to work, but will it get me in trouble elsewhere?

file: https://github.com/driftyco/ionic/blob/master/js/angular/directive/collectionRepeat.js#L2

```javascript
    // in RepeatManagerFactory.$inject 
    // view is a mix of list/grid methods + static/dynamic methods.
    // See bottom for implementations. Available methods:
    //
    // getEstimatedPrimaryPos(i), getEstimatedSecondaryPos(i), getEstimatedIndex(scrollTop),
    // calculateDimensions(toIndex), getDimensions(index),
    // updateRenderRange(scrollTop, scrollValueEnd), onRefreshLayout(), onRefreshData()
    var view = isVertical ? new VerticalViewType() : new HorizontalViewType();
    (isGridView ? GridViewType : ListViewType).call(view);
    (isStaticView ? StaticViewType : DynamicViewType).call(view);

    var contentSizeStr = isVertical ? 'getContentHeight' : 'getContentWidth';
    var originalGetContentSize = scrollView.options[contentSizeStr];
    scrollView.options[contentSizeStr] = angular.bind(view, view.getContentSize);

    // add at line 484
    scrollView.options['getDimensionsForItem'] = angular.bind(view, view.getDimensions);
    // end
```
In my controller, I just call the following to use

```javascript
// vertical scrolling collection-repeat 
var scrollToItem = function(index) {
        var $isd, $isv;
        $isd = $ionicScrollDelegate.$getByHandle('collection-repeat-wrap');
        $isv = $isd.$getByHandle('collection-repeat-wrap').getScrollView();
        return $isd.scrollTo(0, $isv.options['getDimensionsForItem'](index).primaryPos, 1);
      }
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mixersoft!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3562). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3562)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mixersoft** [comment]
need to adjust for the offset of any scrolled elements before the collection-repeat directive

**Comment by perrygovier** [comment]
Hey @mixersoft, thanks! We wont be adding new features before the 1.0 release, but could you resubmit this as a pull request with unit tests and we'll add it for a 1.0.1

**Comment by pajooh** [comment]
Hey @mixersoft , i want to add a ```collection-start-index``` to my ```collection-repeat``` directive, to have an initial offset of items. i think your solution should work for me.
as i'm new to ionic, could you please help me to get it work with your patched version of ionic.

the controller:
```js
        angular.module('ionicApp', ['ionic']).controller('CollectionCtrl', function ($scope) {
            var i, items = [];
            for (i = 0; i < 100; i++) {
                items.push({height: i * 92397.0 % 61 + 50});
            }
            $scope.items = items;
        })
```
the directive:
```html
    <div class="list" ng-controller="CollectionCtrl">
        <div class="item my-item"
             collection-repeat="item in items"
             collection-item-width="'100%'"
             collection-item-height="item.height"
             collection-start-index="20"
             ng-style="{height:item.height+'px'}">

            <div ng-style="{height:item.height-6+'px'}">
                item {{$index}} (height:{{item.height}})
            </div>
        </div>
    </div>
```

any help would be highly appreciated

**Comment by mixersoft** [comment]
@pajooh 

You have to add this line to your `ionic.bundle.js` file

```
    // 1) search ionic.bundle.js for this block:
    var contentSizeStr = isVertical ? 'getContentHeight' : 'getContentWidth';
    var originalGetContentSize = scrollView.options[contentSizeStr];
    scrollView.options[contentSizeStr] = angular.bind(view, view.getContentSize);

    // 2) add the line below just after the above block
    scrollView.options['getDimensionsForItem'] = angular.bind(view, view.getDimensions);
    // end
```

Then I think you can just call `scrollToItem(attr.collectionStartIndex)` in the directive link function. You might need to add a `$timeout` to wait until the collection-repeat is rendered before `$ionicScrollDelegate.$getByHandle()` returns a value.

**Comment by pajooh** [comment]
Hey @mixersoft, thanks. your solution worked! and i have a bonus question :)
it seems that scrolling to a specific item, causes every item with index before that to render,
am i right? is there any way to eliminate this unnecessary renders?

**Comment by mixersoft** [comment]
I don't know about that. the actual rendering is left to the collection-repeat directive, I just added code to get the offsets by index. I'll leave any further optimizations to the ionic guys.

**Comment by CatchSandeepVaid** [comment]
I think this feature is important. Please let me know how can i upvote for this feature?
