### ISSUE TITLE
bug: ion-spinner is not working on android stock browse

### ISSUE THREAD

**Issue by myc0210** [driftyco/ionic#3566]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>http://codepen.io/toddhalfpenny/pen/azadwN
this example not working on my GT-I9300 4.1.2 stock browser... it doesn't show anything for that svg spinner. but if you remove icon="line", it will display default android spinner...why?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Some advanced spinners have trouble in old versions of Android in complex situations like being over a transparent backgrounds used by the loading service. We chose default spinners that should work in all versions. If you're having issues with older Android, we advise using crosswalk in your application.
http://blog.ionic.io/crosswalk-comes-to-ionic/
