### ISSUE TITLE
bug: ionicPopover.initialize() screws the popover

### ISSUE THREAD

**Issue by BetterTrader** [driftyco/ionic#3567]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,
I'm trying to remove() a popover that was created when the user is leaving the tab, and then open it again when he's back.
I've got an error about that:
"Cannot call popover.show() after remove()."
So in order to solve that, I thought I'd try to call popover.initialize(), but then the popover won't open at all.

Look at the following code and open the console when you run it:
http://codepen.io/anon/pen/bdbQpE

It currently doesn't open and prints an error. 
If you put line 20 (of the JS) in a comment, the popover will open without errors.

Will appreciate your help</span>

<span is-issue-template></span>

**Comment by BetterTrader** [comment]
Anyone?

**Comment by perrygovier** [comment]
After calling `remove()` the popover is unusable. You'll need to re-declare it.
