### ISSUE TITLE
bug: Automatic refresh on collection-repeat stopped wor

### ISSUE THREAD

**Issue by shirha** [driftyco/ionic#3571]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://stackoverflow.com/questions/29753110/automatic-refresh-on-collection-repeat-stopped-working-on-ionic-1-0-0-rc-3</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Copying and pasting the description here...

Here is a codepen http://codepen.io/shirha/pen/BNBxWJ/ to better show my question.

First notice on the recipes tab that Briar Heart shows on multiple rows.

Now navigate to the ingredients tab and uncheck Briar Heart.

And then tab back to the recipes tab and notice that all the Briar Heart recipes have been removed (thanks to the filter:available).

Now go to the options tab and click refresh ingredients.

The recipes tabs includes Briar Heart again. Notice that clicking the Briar Heart ingredient button on the recipe tab also unchecks the ingredient and removes the recipes.

If you now change the link to the ionic-bundle.js to 1.0.0-rc.3 and perform the same steps, you will notice that the recipes tab will not refresh without scrolling forward past the buffer specified on the collection-repeat.

I've tried to code an scope.$apply() to work around this but I don't know how to do this and have been unsuccessful so far. I'm not sure if this is the right idea.

**Comment by perrygovier** [comment]
I don't really understand how the app _should_ would work. Does Jeremy's solution work?

**Comment by Ionitron** [comment]
Greetings @shirha!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
