### ISSUE TITLE
docs: Ionic Guide: Updating your app versionCode error

### ISSUE THREAD

**Issue by fe-rod** [driftyco/ionic#3576]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In the Ionic Guide (http://ionicframework.com/docs/guide/publishing.html) there's an issue in the last step of the document (Updating your app).

It says:

"In order for the Google Play Store to accept updated APKs, you'll need to edit the platforms/android/AndroidManifest.xml file to increment the android:versionCode value"

I understand that the latest version of Cordova manages the versionCode of an app in the config.xml file. Using the current documentation is not useful as the build command regenerates the AndroidManifest.xml file every time it is executed.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-site#264
