### ISSUE TITLE
bug: Sidemenu links not working in simulator

### ISSUE THREAD

**Issue by chrisschaub** [driftyco/ionic#3588]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>When I use the ionic start with the sidemenu template, the left links don't go anywhere when clicked in the simulator on osx. I think there is a whitelist bug with ion-item and href. If the href is moved out to a simple anchor tag then the links work. This fixes it

.config(function($stateProvider, $urlRouterProvider, $compileProvider) {
  $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|geo|tel|local):/);

The fix came from the forums here
http://forum.ionicframework.com/t/ion-item-href-doesnt-work-on-blackberry10/1281/6</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This is probably a blackberry specific issues.  Not sure if we will support BB, so marking this for post 1.0 and will revisit

**Comment by chrisschaub** [comment]
Happens in simulator as well.

On Wed, Apr 22, 2015 at 12:20 PM, Mike Hartington <notifications@github.com>
wrote:

> This is probably a blackberry specific issues. Not sure if we will support
> BB, so marking this for post 1.0 and will revisit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/3588#issuecomment-95272172>.
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by mhartington** [comment]
The blackberry sim or anything else?

**Comment by chrisschaub** [comment]
Sorry, I'm using the Telerik appbuilder simulator locally for iOS/Android.
I filed a bug report.

On Wed, Apr 22, 2015 at 12:23 PM, Mike Hartington <notifications@github.com>
wrote:

> The blackberry sim or anything else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/3588#issuecomment-95273520>.
>



-- 
Christopher Schaub
http://chris.schaub.com
