### ISSUE TITLE
bug: Slidebox pull to refresh Error: read only property

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#3589]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Ion-slide-box inside ng-repeat throws an error on a pull to refresh, happens when attempting to reassign an object in the scope. ex: Resetting total posts count to 5 after having a long post list.

I attempted to wrap in timeouts to see if that would mitigate, it did not. 
it appears to only happen when there is an ion-slide inside the slidebox (aka if you fake a slidebox without a slide, there is no issue)

It appears to be related to (or the same as?) this angular issue: 
https://github.com/angular/angular.js/issues/9128

iOS 8.3(12F70) iPhone 6+
Error does not present itself in browser, only on iOS

Error Thrown:
```javascript
459386   error    Error: Attempted to assign to readonly property.
kill@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:8473:24
http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:54243:20
$broadcast@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:23406:33
$destroy@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:23026:24
ngRepeatAction@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:33160:33
$watchCollectionAction@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:22796:21
$digest@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:22929:31
$apply@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:23192:31
http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:24918:42
completeOutstandingRequest@http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:13591:15
http://10.0.1.8:8100/lib/ionic/js/ionic.bundle.js:13971:33
```</span>

<span is-issue-template></span>

**Comment by promactkaran** [comment]
Please provide code so we can debug.

**Comment by uofmmike** [comment]
Surely, sorry should have done that to begin with!

To remove the error, replace the slidebox in the example with anything, or nothing. error thrown when pulling to refresh. 

Thanks!

Inline is the same as this codepen: http://codepen.io/mmullins/pen/BNaVJv

```javascript
angular.module('starter.controllers', []).controller('DashCtrl', function($scope) {	
	$scope.refreshFeed = function() {
		//pause the infinite
		$scope.$broadcast('scroll.infiniteScrollComplete');
		$scope.noMoreItemsAvailable = true;

		//reset the array (0,1 is an exaggeration but causes a failure)
		$scope.items = $scope.items.slice(0, 1);
		$scope.$broadcast('scroll.refreshComplete');
		
		//would allow continue of infinite
		//$scope.noMoreItemsAvailable = false;
	};

	$scope.noMoreItemsAvailable = false;

	$scope.loadMore = function() {
		$scope.items.push({
			id : $scope.items.length
		});

		if ($scope.items.length == 99) {
			$scope.noMoreItemsAvailable = true;
		}
		$scope.$broadcast('scroll.infiniteScrollComplete');
	};

	$scope.items = [];

});
```

```html
<ion-view view-title="Dashboard">
	<ion-content class="padding">
		<ion-refresher
		on-refresh="refreshFeed()"></ion-refresher>
		<ion-list>

			<ion-item ng-repeat="item in items"
			item="item"
			href="#/item/{{item.id}}">
				<ion-slide-box >
					<ion-slide>
						<div class="box blue">
							<h1>BLUE</h1>
						</div>
					</ion-slide>
					<ion-slide>
						<div class="box yellow">
							<h1>YELLOW</h1>
						</div>
					</ion-slide>
					<ion-slide>
						<div class="box pink">
							<h1>PINK</h1>
						</div>
					</ion-slide>
				</ion-slide-box>
			</ion-item>

		</ion-list>
		<ion-infinite-scroll ng-if="!noMoreItemsAvailable" on-infinite="loadMore()" distance="10%"></ion-infinite-scroll>
	</ion-content>
</ion-view>
```

**Comment by rhespy** [comment]
I see the same error in the kill function on this line of ionic.js:
    
    //reset slides so no refs are held on to
    slides && (slides.length = 0);

It looks like slides.length is read-only so an error is thrown.
If I comment out that line, the error is not thrown.

**Comment by rhespy** [comment]
This update did not fix the issue for me.
I still get the same "read-only property" error.

**Comment by pixnlove** [comment]
The commit did not fix the issue for me too.

**Comment by campers** [comment]
@perrygovier looks like there was a mistake in the commit, fredgalvao added a note in the commit with what looks to be the correct change
https://github.com/driftyco/ionic/commit/08956b29b0ccf93203681a83f6ae6c5c9c28375f

**Comment by perrygovier** [comment]
wow, yeah. that'll teach me to commit a fix quickly on my way out the door. Thanks
