### ISSUE TITLE
bug: has-tabs css is not removed

### ISSUE THREAD

**Issue by wodka** [driftyco/ionic#3594]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>http://codepen.io/anon/pen/BNaxYw

The line below the header is invisible for the tabs which are not present in that view.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by wodka** [comment]
Hi, I just tried my codepen and it's still happening

**Comment by wbhob** [comment]
Did you update to 1.3.2?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#9
