### ISSUE TITLE
bug: URL blocked by whitelist on Android

### ISSUE THREAD

**Issue by asuwend1** [driftyco/ionic#3597]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>My environment: OS X Yosemite, cordova 5.0.0, ionic 1.3.20. I use Firebase to for Facebook Authentication service.  In IOS things work fine, but in Android, during Facebook authentication, I got: "W/SystemWebViewClient( 1556): URL blocked by whitelist: https://auth.firebase.com/v2/intense-torch-3742/auth/session?&requestId=whdi3macji4xffd91e2qxh96ohwamqsu380f&requestKey=XnWG8sRju97nlg4RM2pZQofpyLu933FI&v=js-2.2.4&transport=json&suppress_status_codes=true". In my config.xml: "  <access origin="*" subdomains="true"/>
  <access origin="https://auth.firebase.com"/>". Also tried "<access origin="*"/>". I have InAppBrowser plugin installed too. Any thought why I'm seeing the URL was blocked where it should not according to config.xml? I have also checked all other config.xml files and they look good to me - they allow everything.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
With the updated version of cordova-android, you now need to include the cordova-whitelist-plugin.

https://github.com/apache/cordova-mobile-spec/tree/master/cordova-plugin-whitelist

Try adding that to your project

**Comment by asuwend1** [comment]
Hi Mike,

Thank you! It works now after adding that plugin. Thank you for your help.

Ari

**Comment by santoshshinde2012** [comment]
Please tell me how to install this plugin and simple demo code to call it ,
Thank you.

**Comment by matigda** [comment]
for example:
cordova plugin add https://github.com/apache/cordova-plugin-whitelist.git

**Comment by santoshshinde2012** [comment]
Thank you for your help ,
I have successfully installed and run my application successfully .

**Comment by sferoze** [comment]
+1 thanks for the help. I needed the whitelist plugin to run my cordova app in android studio. Google search brought me here.

**Comment by mohamed-salah** [comment]
+1 thanks

**Comment by kosalanuwan** [comment]
+1 Thanks for the comments, I have installed and ran my app successfully! Yey!

**Comment by woaiso** [comment]
+1 thanks

**Comment by 8ozStudios** [comment]
I'm getting this error message:
"Failed to install 'cordova-plugin-whitelist':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.1, failed version requirement: >=4.0.0-dev"
My current version is 3.7.1 but when I run 'cordova platform update android', it just says "Android project is now at version 3.7.1". How do I upgrade to the correct version to use this plugin? Thanks!

**Comment by mhartington** [comment]
You need to upgrade to Cordova CLI 5.0 to get Cordova-android 4.0.

Mike Hartington

**Comment by 8ozStudios** [comment]
Thanks Mike, I actually found that this worked also:
"cordova platform update android@4.0.0"

**Comment by julienwikart** [comment]
Hi,

This plugin requires cordova ios 4.0.0 but i can only find cordova ios 3.8.0
How can I do ?

Thank you for your help

**Comment by 8ozStudios** [comment]
@julienwikart Look one comment above yours - try running "cordova platform update android@4.0.0" from the command line.

**Comment by julienwikart** [comment]
Unfortunately my question was regarding iOS 4.0.0 and not android...

But I found the solution :
cordova platform add ios@4.0.x --usegit

**Comment by mhartington** [comment]
cordova ios and cordova android both have separate release cycles. For cordova-ios, the whitelist plugin shouldn't do anything, sense it's not setup for it.

**Comment by bobbynathan** [comment]
how to solve the URL blocked whitelist issue while call weather api. Please help me to solve this issuse

**Comment by owgee** [comment]
Thanks :)

**Comment by rszczypka** [comment]
How did you configure the whitelist plugin to allow the access? Did you use allow-intent or allow-navigation? I can't get it to work with calling firebase server for authentication.

**Comment by skotturi** [comment]
@rszczypka all I had to do was add the plugin and the error was gone. No configuration, didn't even have to call or do anything with the plugin. 

this post provides an html header you can if adding the plugin isnt working for you:
https://blog.nraboy.com/2015/05/whitelist-external-resources-for-use-in-ionic-framework/
it seems a bit too open to allow "everything" but maybe helps get it working?

**Comment by neerajdembla212** [comment]
+1 Thanks installing this plugin removed redirect errors from my android app.

**Comment by ajay67** [comment]
thanks. it solved the issue

**Comment by prachi708** [comment]
I am working on meteor. I am also facing problem of URL blocked by whitelist I installed "https://github.com/apache/cordova-plugin-whitelist" plugin. But it is giving me error "Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible". I had even tried different viresions also.

Please tell how to resolve this issue

**Comment by mrlowe** [comment]
@prachi708 meteor is locked to a particular version of cordova. Just install a specific version of whitelist with something like:

    meteor add cordova:cordova-plugin-whitelist@1.3.3

If you're using an older version of meteor (locked to an older version of cordova) you may need to play with the whitelist versions or update meteor.
