### ISSUE TITLE
Embedding video from youtube or video does not play audio

### ISSUE THREAD

**Issue by loomtronic** [driftyco/ionic#3601]
Here is my code, which I found from a post from @mhartington when I run this on my iPad, there is no sound.  In the emulator it works fine (yes I have quadruple checked to make sure my sound is on).  Running ios 8.2

<html ng-app="youtubeList">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">

    <title>Youtube List</title>

    <link href="lib/ionic/css/ionic.min.css" rel="stylesheet">
    <script src="lib/ionic/js/ionic.bundle.min.js"></script>
    <script src="cordova.js"></script>
  </head>
<style>
  .video-container {
        position: relative;
        padding-bottom: 56.25%;
        padding-top: 30px;
        height: 0;
        overflow: hidden;
    }

.video-container iframe,
.video-container object,
.video-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>
<script>
  'use strict';

angular.module('youtubeList', ['ionic'])

.config(function($stateProvider, $urlRouterProvider, $sceDelegateProvider) {

  $sceDelegateProvider.resourceUrlWhitelist(['self', new RegExp('^(http[s]?):\/\/(w{3}.)?youtube\.com/.+$')]);
})

.controller('ListCtrl', function() {
  var vm = this;
  vm.media = [{
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }]
});
</script>
  <body>
    <ion-pane>
        <ion-header-bar class="bar-stable">
            <h1 class="title">Youtube List</h1>
        </ion-header-bar>
        <ion-content>
            <div class="list" ng-controller="ListCtrl as vm">
                <div class="card" ng-repeat="m in vm.media">
                    <div class="item item-text-wrap">
                        <p>{{m.Title}}</p>
                    </div>

                    <div class="item item-image">
                        <div class="video-container">
                            <iframe src="{{m.Url}}" frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </ion-content>
    </ion-pane>
  </body>
</html>

**Comment by Ionitron** [comment]
Greetings @loomtronic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3601). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3601)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>
