### ISSUE TITLE
bug: Embedding video does not play sound

### ISSUE THREAD

**Issue by loomtronic** [driftyco/ionic#3602]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>This is my code which I took from someone else who commented... I made sure my sound was turned up.  This worked in the ios emulator, but not on my actual device

```
<html ng-app="youtubeList">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">

    <title>Youtube List</title>

    <link href="lib/ionic/css/ionic.min.css" rel="stylesheet">
    <script src="lib/ionic/js/ionic.bundle.min.js"></script>
    <script src="cordova.js"></script>
  </head>
<style>
  .video-container {
        position: relative;
        padding-bottom: 56.25%;
        padding-top: 30px;
        height: 0;
        overflow: hidden;
    }

.video-container iframe,
.video-container object,
.video-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>
<script>
  'use strict';

angular.module('youtubeList', ['ionic'])

.config(function($stateProvider, $urlRouterProvider, $sceDelegateProvider) {

  $sceDelegateProvider.resourceUrlWhitelist(['self', new RegExp('^(http[s]?):\/\/(w{3}.)?youtube\.com/.+$')]);
})

.controller('ListCtrl', function() {
  var vm = this;
  vm.media = [{
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }, {
    "Url": "https://www.youtube.com/embed/DX1iplQQJTo?rel=0",
    "Title": "Test Title"
  }]
});
</script>
  <body>
    <ion-pane>
        <ion-header-bar class="bar-stable">
            <h1 class="title">Youtube List</h1>
        </ion-header-bar>
        <ion-content>
            <div class="list" ng-controller="ListCtrl as vm">
                <div class="card" ng-repeat="m in vm.media">
                    <div class="item item-text-wrap">
                        <p>{{m.Title}}</p>
                    </div>

                    <div class="item item-image">
                        <div class="video-container">
                            <iframe src="{{m.Url}}" frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </ion-content>
    </ion-pane>
  </body>
</html>
```
</span>

<span is-issue-template></span>

**Comment by waparty** [comment]
Hi, try <iframe ng-src="{{m.Url}}" frameborder="0" allowfullscreen></iframe>

**Comment by waparty** [comment]
If doesn't help, please use this plugin: https://github.com/Glitchbone/CordovaYoutubeVideoPlayer

**Comment by loomtronic** [comment]
@waparty Unfortunately neither of those solutions seem to work...

**Comment by loomtronic** [comment]
And actually I need to get it working for vimeo video

**Comment by loomtronic** [comment]
If I set "Use side switch to:" in my general settings of my app to "Lock Rotation", the sound works.  If I set it to Mute, the sound doesn't work.  

But I'd rather have it work for everyone...

**Comment by loomtronic** [comment]
Well according to @mhartington this is just the way it is

"That makes sense. The audio will be treated as sound effects on iOS, so they will be muted. Not sure how much can be done here. You would either have to write a cordova plugin that could circumvent this."

**Comment by dwilt** [comment]
Thank you for posting this. My phone was on mute too and I thought I had a bug. This sucks.

**Comment by Pseudo-Nym** [comment]
My first question would be, Why is this being treated as a sound effect when it clearly not. Is this an Ionic issue? or a Cordova issue?

Does anyone have any suggestion on how to circumvent this problem? Using Ionic 1.3.3, Cordova 7.0.1.

**Comment by chuchuva** [comment]
1. Install [cordova-plugin-avaudiosession](https://github.com/TheBosZ/cordova-plugin-avaudiosession) plugin

2. Add this line to config.xml

````
<preference name="AVAudioSession" value="AVAudioSessionCategoryPlayback" />
````


See https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionCategoriesandModes/AudioSessionCategoriesandModes.html

**Comment by dimadev01** [comment]
@chuchuva has the truth. Thanks for being dude
