### ISSUE TITLE
bug: ionic CLI share command doesn't send emails

### ISSUE THREAD

**Issue by carpiediem** [driftyco/ionic#3604]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I last tried a week ago, running the `ionic upload` command would ask me if I wanted to share with others.  It doesn't do that anymore.

When I type in `ionic share me@isp.net`  the response says `Sharing app null with me@isp.net` but nothing ever shows up in my inbox.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#394

**Comment by perrygovier** [comment]
Hey @carpiediem, moving this issue to the CLI repo
