### ISSUE TITLE
 List Delete and Option Buttons not working

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#361]
> List Delete and Option Buttons example is working in my chrome browser very well.
> but not working on my android htc desire x with android 4.1. I make an apk file with cordova 3.3 i see the list with item 1 item 2.... etc. but when i want to delete for example the 5th item nothing happen. Am i doing something wrong.
> 
> I run the List Delete and Option Buttons example (apk file) with android emulator (Android Virtual Device).
> With android 4.1 (Api level 16) not working.
> With android 4.4 (Api level 19) working excellent.
> So... i cant run my cordova application on smartphone with Android 4.1.
> 
> With android 4.1 (Api level 17) not working.
> With android 4.4 (Api level 18) not working.

http://forum.ionicframework.com/t/list-delete-and-option-buttons-not-working-on-my-htc-desire-x/384

**Comment by emmychen** [comment]
I have the problem about ion-option-button on chrome browser.  It does not show when I swipe the list item.  it works on ios and safari.   I have not test it on other platform yet.
