### ISSUE TITLE
feat: Bi directional lazy loading in Ionic

### ISSUE THREAD

**Issue by ManishKrShukla** [driftyco/ionic#3613]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Type: feat

Platform: all

Can we have support for bi-directional lazy loading in Ionic. I know that it is already kinda implemented using collection-repeat, but in real time, it's quite difficult to predict the height of your list items.

we have list items that run into hundreds. Now although we are loading these items from server using lazy loading, the device cracks up on records more than 80-90.

I request for a feature that allows us to use the same ion-content, the same ion-list and the same ng-repeat, in a way making rendering / viewing numerous rows easily at once.

I can submit a PR if you wish.
Thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ManishKrShukla!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3613). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3613)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ManishKrShukla** [comment]
I will surely do that @<b>Ionitron</b>

**Comment by perrygovier** [comment]
What would this offer that infinite scrolling is not capable of?

**Comment by ManishKrShukla** [comment]
Infinite Scrolling allows us rendering huge data sets, in small chunks. However, on a 1 GB Android Lollipop device, after loading some 400+ Items, the app just halts. 

<b>I understand that for such use cases, we do have collection-repeat, but in real time, it's quite difficult to predict the height of your list items [And i have still not checked whether it supports infinite scrolling or not].</b>

I have been through the source code, and as clearly mentioned in the docs itself, ionic has completely disabled the native browser scrolling and provided a custom implementation that emits out different kind of events such as swipe, tap etc. Now we do know that, native scrolling is better at performance, so ionic has provided overflow-scroll. But in that case, i have to drop down the infinite scrolling feature

**Comment by perrygovier** [comment]
Great timing, we just aded support for infinite scrolling with native scrolling! You can enable native scrolling per page as you mentioned or globally with the [$ionicConfigProvider](http://ionicframework.com/docs/nightly/api/provider/$ionicConfigProvider/)

**Comment by Ionitron** [comment]
Greetings @ManishKrShukla!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
