### ISSUE TITLE
bug: On android >=4.4 it is very laggy

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#3619]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I had signals that on android >=4.4 app is very laggy.
I have only device with android 4.2 so I have to test on genymotion with android 4.4 and 5.0 and I can confirm - it is very, vary laggy.
For tests I used Your tabs starter example with added collection repeat with 1000 items. (here is example http://forum.ionicframework.com/t/scrolling-works-well-on-4-2-and-has-lags-on-4-4/21682)
You can test it on genymotion Yourself.
When I add crosswalk to that test app the performance is much, much better, but shouldn't it work well on android 4.4 without crosswalk?

In production I cannot use crosswalk because I want to use google maps phonegap plugin which requires crosswalk 14 and You provide (in ionic-cli) only crosswalk 13.

What's wrong with ionic perfomance on android 4.4?</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
The emulators aren't the best test. I've checked on some of our 4.4 and 5.0 test devices and their performance seems good to me, noticeably better than 4.2 devices without crosswalk. Can you share any more specific information about what features are particularly slow? Is it just in the current version or has it always been slow? Those who are reporting slowness, can you share what devices they're using?

**Comment by piernik** [comment]
I'm not using device with 4.4 because I don't have it.
My app users (app was made on rc3, cordova 4.3 without crosswalk) report that it is very, very laggy.
All I can is to test on genymotion and I can confirm that it has very bad performance.
As I wrote problem is with scrolling and on genymotion 5.0 even with rendering first app view - it is very slow.
From google play - users who reports slowlyness uses:
- Galaxy S4 (jflte)
- Galaxy S4 (ks01lte)
- L-01F (g2)
- Galaxy Note3 (hlte)
- Galaxy S5 (klte)

**Comment by AlexYankee** [comment]
My opinion - you shouldn't even try to run Ionic app on Android without CrossWalk. That's it.
You can get acceptable performance on all Android devices only by using CrossWalk.

**Comment by piernik** [comment]
@perrygovier any suggestions?
@AlexYankee if there is no sense building ionic/cordova app without crosswalk it should be integrated with cordova

**Comment by AlexYankee** [comment]
@piernik, you're right. It SHOULD be, but unfortunately it's not.
In contrast with iOS, where you have only proprietary devices with well-defined software environment, on Android you have huge amount of different devices, some of them running on stock OS, some running on modified OS and so on.
On Nexus running 4.3 Android version you can have nice stock WebView version which will play well with your app, on another device running same 4.3 version WebView will be laggy as hell.
That's why Ionic guys added "ionic browser" command to their CLI. I can clearly remember when i was messing around with Ionic last summer and i was integrating crosswalk to my project manually. Now you have all tools on hands.

**Comment by perrygovier** [comment]
Something as nebulous as "Android is slow" isn't really suitable as an issue that we can directly fix. 

If you post your source to the forums, there are normally many optimizations that can be made to improve performance that we can help with. 

We will be enabling crosswalk by default in the future, but it still causes problems with a few plugins, so we haven't made it the default yet. 

This might be a better discussion for the forums.
