### ISSUE TITLE
bug: Initital controller called twice on Android

### ISSUE THREAD

**Issue by psimondk** [driftyco/ionic#3620]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The initial controller is called twice on Android but not on the browser.

Set up like so:
```
  .state('app.map', {
      url: "/map/:shopId",
      cache: false,
          'tab-shops': {
              templateUrl: "templates/map.html",
              controller: "MapCtrl"
          }
      }
  })
$urlRouterProvider.otherwise('/app/map/init');

```
And need to have this hack to prevent the app to initgialize twice. But only on the device:

    if (typeof $scope.init !== 'undefined' || $scope.init) return;</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
We are not seeing on our testing apps. Can you share a functional codepen or sample project that we can test against?

**Comment by manmetplok** [comment]
We have the same issue here.

**Comment by Ionitron** [comment]
Greetings @psimondk!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @psimondk!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by manmetplok** [comment]
can we reopen this one? :)
