### ISSUE TITLE
bug: Modal Window Input Focus Problem

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#3624]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>We have a modal that has a fairly large text area for feedback. The problem is when a user clicks the text are and the keyboard comes into play, the text area is moved upwards and there is a small weird bug. 

Watch this video for more information.
https://www.youtube.com/watch?v=wbSHKSI63Lw</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
If you post a codepen reproducing the issue I'll take a look.

**Comment by Ionitron** [comment]
Greetings @saniyusuf!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
