### ISSUE TITLE
bug: Build gradle conflict with locaNotification plugin

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic#3626]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Sice I add crosswalk with `ionic browser add cosswalk` my project is builded with `gradle` instead `ant` and is resulting this issue.

    :compileDebugJavaC:\teste-ionic\platforms\android\src\de\appplant\cordova\plugin
    \localnotification\LocalNotification.java:495: error: cannot find symbol
                        webView.evaluateJavascript(js, null);</span>

<span is-issue-template></span>

**Comment by butchewing** [comment]
+1 Simply updating Ionic will install [Crosswalk](http://blog.ionic.io/crosswalk-comes-to-ionic/]). According to the plugin developer, the Local Notifications plugin is [not Crosswalk compatible yet](https://github.com/katzer/cordova-plugin-local-notifications/issues/460#issuecomment-87789199).

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#400
