### ISSUE TITLE
bug: Scrolling broken on wp8

### ISSUE THREAD

**Issue by jbollacke** [driftyco/ionic#3634]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Scrolling on wp8 is completely broken since commit c40e36c10da52c5856592c40fd91e16a9ad6604e. You can drag as much as you want, the list won't scroll in neither direction.

Prior to this commit scrolling worked (though jumpy). I know that wp8 is not supported right now but as some fixes made it into rc5...

### Steps to reproduce:

1. ```ionic start broken-scrolling blank```
2. ```cd broken-scrolling```
3. ```ionic platform add wp8```
4. Add the following code into ion-content element on www/index.html:
```
<ion-list>
  <ion-item>Entry #0</ion-item>
  <ion-item>Entry #1</ion-item>
  <ion-item>Entry #2</ion-item>
  <ion-item>Entry #3</ion-item>
  <ion-item>Entry #4</ion-item>
  <ion-item>Entry #5</ion-item>
  <ion-item>Entry #6</ion-item>
  <ion-item>Entry #7</ion-item>
  <ion-item>Entry #8</ion-item>
  <ion-item>Entry #9</ion-item>
  <ion-item>Entry #10</ion-item>
  <ion-item>Entry #11</ion-item>
  <ion-item>Entry #12</ion-item>
</ion-list>
```
Now: ``` ionic run wp8 --device ```

</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Does it work if you wrap the list in an ion-content?

**Comment by jbollacke** [comment]
It is wrapped in ion-content.

**Comment by perrygovier** [comment]
kk, I reverted the change. How is scrolling now?

**Comment by jbollacke** [comment]
Works like before c40e36c10da52c5856592c40fd91e16a9ad6604e.
