### ISSUE TITLE
feat: Hide ion-header and ion-footer on keyboard open

### ISSUE THREAD

**Issue by Stiveknx** [driftyco/ionic#3636]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In some screens, when you open the keyboard, the remaining space on screen is almost 0, when you have ion-header and, ion-footer.

Would be cool to have an option to hide ion-footer / ion-header on keyboard open.
I know I can use ``hide-on-keyboard-open`` class, but also need to clear ion-content top and css bottom properties.

A good usage would be:

`
<ion-header-bar hide-on-keyboard="true">
</ion-header>
<ion-content>
</ion-content>
<ion-footer-bar hide-on-keyboard="true">
</ion-footer>
`

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, well the keyboard plugin does provide some events for you to tap into and use an `ng-if` or ng-show. 

https://github.com/driftyco/ionic-plugin-keyboard/#nativekeyboardshow

I think that this would be too specific of a thing to add to the framework, but all the pieces are there for you to makes something.
