### ISSUE TITLE
bug: Windows Phone - 2 splash screens ...

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#3642]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Using Splash Screen in Windows Phone appears 2 splashs.

The first is Ok, The second is big to fit in screen.

My Definition in config.xml

<platform name="wp8">
  <icon src="resources\wp8\icon\ApplicationIcon.png" width="99" height="99" />
  <icon src="resources\wp8\icon\Background.png" width="159" height="159" />
  <splash src="resources\wp8\splash\SplashScreenImage.jpg" width="768" height="1280"/>
</platform>

Any solution?</span>

<span is-issue-template></span>

**Comment by splatterb0y** [comment]
Yes: Ask in a Cordova related forum, that doesn't sound like a ionic specific bug. 
AFAIK Windows Phone is not supported by the Ionic Guys yet anyway.

**Comment by baltazaroliveira** [comment]
Ok. I will ask in the Cordova Forum.

I know that Windows Phone don´t support Windows Phone but they are making changes do that (Ex: Scroll that works very well).

Thanks
