### ISSUE TITLE
bug: Custom directive with collection-repeat won't work

### ISSUE THREAD

**Issue by BetterTrader** [driftyco/ionic#3655]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm unable to access the data I'm passing to my custom directive in collection-repeat.

Look at the following code and open the console:
http://codepen.io/anon/pen/BNNMMV

I would expect the controller and link to be able to print the item, but as you can see - they print undefined (but for some reason, the DOM looks ok).
If you change collection-repeat to ng-controller, it all works good.

This issue is not allowing me to access the scope data in my directive and makes the collection-repeat quite useless.
Is it a bug, or am I missing something?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This is a known issue at the moment with collection repeat. A fix would require a refactor of collection repeat, which would be too big of a change the moment. Posting this as fix for post 1.0

**Comment by BetterTrader** [comment]
Any way around this issue?

**Comment by BetterTrader** [comment]
I have now, but I don't see how it helps.
I've tried wrapping the directive with $timeout, but it didn't work.
Using $watch on the scope variable does work, but sounds inefficient.

What do you suggest?

**Comment by BetterTrader** [comment]
I'll appreciate a quick workaround around this.
Thank you

**Comment by mhartington** [comment]
Nothing that can be done at the moment. Like I said earlier, we'd to refactor collection repeat.

**Comment by BetterTrader** [comment]
Thank you

**Comment by BetterTrader** [comment]
Another issue, in case you didn't notice.
The link and the controller are not called for each directive:
http://codepen.io/anon/pen/yNYZVE
The link is only called 20-30 of times while there are 10,000 items.

**Comment by perrygovier** [comment]
This is because of how Collection-repeat works. It's not actually recreating the components, it's moving them and replacing the contents. This is intentional.

**Comment by manugb** [comment]
I still have this problem, did you guys get to refactor collection-repeat?

**Comment by mhartington** [comment]
Nothing has been reworked yet, but PRs are alway welcomed.

**Comment by iamsamwood** [comment]
I'm hitting this as well. Is there some way to register for an event within the ion-tab scope to reload my custom directives?

**Comment by evanjmg** [comment]
Any update on this issue? It's pretty important in order to keep code maintainable and reusable.

**Comment by wal-nadeem** [comment]
Any updates here? Still having this issue.

**Comment by paweldziura** [comment]
Collection-repeat is very helpful but only on simple cases. Unfortunately, collection-repeat with nested directives is just useless.
