### ISSUE TITLE
bug: rc.5 bug navigating states

### ISSUE THREAD

**Issue by japhar81** [driftyco/ionic#3658]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Standard ui-router states throw the bellow stack in rc.5. Confirmed working fine in rc.2.

Error: setting a property that has only a getter ionic.views.Slider<.initialize/this.kill@http://localhost:8000/lib/ionic/js/ionic.bundle.js:8486:7 .controller</<@http://localhost:8000/lib/ionic/js/ionic.bundle.js:54326:9 $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:8000/lib/ionic/js/ionic.bundle.js:23419:15 $RootScopeProvider/this.$get</Scope.prototype.$destroy@http://localhost:8000/lib/ionic/js/ionic.bundle.js:23039:9 destroyViewEle@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46792:9 ionicViewSwitcher.create/switcher.cleanup@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46662:11 transitionComplete@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46580:15 completeOnTransitionEnd@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46559:13 n.event.dispatch@http://localhost:8000/lib/jquery/dist/jquery.min.js:3:6388 n.event.add/r.handle@http://localhost:8000/lib/jquery/dist/jquery.min.js:3:3161</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @japhar81!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3658). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3658)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by japhar81** [comment]
Error: setting a property that has only a getter ionic.views.Slider<.initialize/this.kill@http://localhost:8000/lib/ionic/js/ionic.bundle.js:8486:7 .controller</<@http://localhost:8000/lib/ionic/js/ionic.bundle.js:54326:9 $RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:8000/lib/ionic/js/ionic.bundle.js:23419:15 $RootScopeProvider/this.$get</Scope.prototype.$destroy@http://localhost:8000/lib/ionic/js/ionic.bundle.js:23039:9 destroyViewEle@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46792:9 ionicViewSwitcher.create/switcher.cleanup@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46662:11 transitionComplete@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46580:15 completeOnTransitionEnd@http://localhost:8000/lib/ionic/js/ionic.bundle.js:46559:13 n.event.dispatch@http://localhost:8000/lib/jquery/dist/jquery.min.js:3:6388 n.event.add/r.handle@http://localhost:8000/lib/jquery/dist/jquery.min.js:3:3161

**Comment by hzektser** [comment]
Confirmed to also be an issue in RC4.

**Comment by mhartington** [comment]
@japhar81 could you replicate this in a demo/codepen?

**Comment by Ionitron** [comment]
Greetings @japhar81!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
