### ISSUE TITLE
bug: Items disappear off collection-repeat list on Android 5.0.2

### ISSUE THREAD

**Issue by ronniemb** [driftyco/ionic#3660]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Android: 5.0.2
Android System Webview: 42.0.2311.137 
Ionic: Both 1.0.0-rc.4 and 1.0.0-rc.5-nightly-1282
Cordova: 4.2.0

Tested on other phones with different versions of Android (4.2.2) and all works fine there.
When using an ng-repeat it also works as expected.  

When changing the ng-repeat to a collection-repeat, when scrolling down the list (even trying on lists with just a few items) and then scrolling back up, on the way up there are big gaps between items, and eventually you only see 1 item in the list.  After that there is no way to recover except for restarting the app.  

This does not happen always, seems to be once you start the app if you manage to scroll successfully the first time it'll continue working afterwards, but if it fails the first time it won't recover.
It may be that on the first scroll down you can sometimes scroll past the end of the list?

    <ion-item collection-repeat="item in items"
                collection-item-height="54px"
                collection-item-width="100%"
                ng-click="showEditPage(item, true)"
                id="parent-{{item.itemId}}">
        <div id="{{item.itemId}}" 
                class="listItem reorder-adjusted" 
                ng-bind-html="item.title"></div>
    </ion-item collection-repeat>

css for the list item (apart from default list item css applied by ionic)

    .listItem {
    	height: 54px !important;
    }</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ronniemb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3660). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3660)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ronniemb** [comment]
See images.  After refreshing the data and scrolling the items disappear.

![imgo 1](https://cloud.githubusercontent.com/assets/5609753/7471079/0b1ad6d4-f323-11e4-8329-896d3268da25.jpg)
![imgo 2](https://cloud.githubusercontent.com/assets/5609753/7471083/0da2397e-f323-11e4-8619-a5e418401734.jpg)
![imgo 3](https://cloud.githubusercontent.com/assets/5609753/7471082/0cf3de42-f323-11e4-81bf-6b1d3014e8b7.jpg)
![imgo 4](https://cloud.githubusercontent.com/assets/5609753/7471080/0b2799f0-f323-11e4-854e-47f2e6929eab.jpg)
![imgo 5](https://cloud.githubusercontent.com/assets/5609753/7471081/0c9ccff8-f323-11e4-8eee-96e06480b1ec.jpg)

**Comment by mhartington** [comment]
Would you be able to provide codepen to test against.

**Comment by ronniemb** [comment]
Unable to reproduce this in normal or phone browser, I'll dig further at some point to see exactly what is causing it, and will reopen if necessary.
