### ISSUE TITLE
bug: ionicConfig Conflicts with Left Aligned Nav Titles

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#3665]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Affected Versions : RC 3, 4, 5

When using `$ionicConfig.backButton.text('xxxx')` to change the Back Button text, the width of the left hand back button is not determined properly.

Because of this, any left-aligned titles will overlap the back button.

Sample Codepen: http://codepen.io/calendee/pen/waKeZV</span>

<span is-issue-template></span>

**Comment by calendee** [comment]
FYI: Updated sample to use the new Playground : http://play.ionic.io/app/1c71de69a51d

**Comment by beat-at-hartwig** [comment]
I can confirm it is still there

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic 1 (1.3.0) ? Thanks!

**Comment by calendee** [comment]
It's still there in 1.3.0.  See this sample:

http://play.ionic.io/app/304214f7ec59

**Comment by Vaelyr** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#8
