### ISSUE TITLE
feat: File for settings (like an Ionic.json)

### ISSUE THREAD

**Issue by Stiveknx** [driftyco/ionic#3685]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>We have many options now to set with $ionicConfigProvider:

http://ionicframework.com/docs/nightly/api/provider/%24ionicConfigProvider/

I thought it would be cool to have this configurations in a specific file and this file be loaded by default..
Like an "IonicConfig.json" or something inside some specific folder or just inside www/ folder.

This json could have an syntax like:
``
{
   views.transition: {
     ios: "ios",
     android: "none"
   },
  views.maxCache: {
    ios: 30,
    android: 20
  }
}
``

or something better and organized.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Thanks, I've added it to our feature [request Trello board](https://trello.com/c/EJJXYVJG/101-file-for-settings-like-an-ionic-json). If it gets enough votes, we'll consider it for the 1.1
