### ISSUE TITLE
bug: ui-router state ordering breaks tabs app

### ISSUE THREAD

**Issue by thebalaa** [driftyco/ionic#3689]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have an app based on the "tabs" starter application. I'm curious as to why the order of the states listed below breaks the application; is this expected behavior?  In the instance where it doesn't work, clicking the settings tabs presents and empty tab window with a "< Back" on the left side of the header. The only difference is the order in which the states are defined. Thanks!

The following code works as expected
```
 $stateProvider

     

  // setup an abstract state for the tabs directive
    .state('orders', {
    url: "/orders",
    abstract: true,
    templateUrl: "templates/tabs.html",
    // data property is inherited by child states
    data: {
      loginRequired: true
    }
  })

  // Each tab has its own nav history stack:

  .state('orders.list', {
    url: '/list',
    views: {
      'orders-list': {
        templateUrl: 'templates/tab-dash.html',
        controller: 'OrderListCtrl'
      }
    }
  })

  .state('orders.all', {
      url: '/all',
      views: {
        'orders-all': {
          templateUrl: 'templates/tab-chats.html',
          controller: 'AllOrdersCtrl'
        }
      }
    })
 .state('orders.settings', {
    url: '/settings',
    views: {
      'app-settings': {
        templateUrl: 'templates/settings.html',
        controller: 'SettingsCtrl'
      }
    }
  })

  .state('orders.detail', {
    url: '/:id',
    views: { 'orders-list':{
      templateUrl:'templates/order-detail.html',
      controller: 'OrderDetailCtrl',
      resolve: {
        order: function($stateParams, $rootScope, OrderService){
          // set the order on the rootScope
          // prototypical inheritance finally pays off
          $rootScope.order = OrderService.get($stateParams.id);
        }
      }
  }
}
})
   .state('login', {
    url: '/login',
    templateUrl: 'templates/login.html',
    controller: 'LoginCtrl'
    });
```

The following code does not work as expected, exhibiting the behavior described above
```
 $stateProvider

     

  // setup an abstract state for the tabs directive
    .state('orders', {
    url: "/orders",
    abstract: true,
    templateUrl: "templates/tabs.html",
    // data property is inherited by child states
    data: {
      loginRequired: true
    }
  })

  // Each tab has its own nav history stack:

  .state('orders.list', {
    url: '/list',
    views: {
      'orders-list': {
        templateUrl: 'templates/tab-dash.html',
        controller: 'OrderListCtrl'
      }
    }
  })

  .state('orders.all', {
      url: '/all',
      views: {
        'orders-all': {
          templateUrl: 'templates/tab-chats.html',
          controller: 'AllOrdersCtrl'
        }
      }
    })

  .state('orders.detail', {
    url: '/:id',
    views: { 'orders-list':{
      templateUrl:'templates/order-detail.html',
      controller: 'OrderDetailCtrl',
      resolve: {
        order: function($stateParams, $rootScope, OrderService){
          // set the order on the rootScope
          // prototypical inheritance finally pays off
          $rootScope.order = OrderService.get($stateParams.id);
        }
      }
  }
}
})
  .state('orders.settings', {
    url: '/settings',
    views: {
      'app-settings': {
        templateUrl: 'templates/settings.html',
        controller: 'SettingsCtrl'
      }
    }
  })
   .state('login', {
    url: '/login',
    templateUrl: 'templates/login.html',
    controller: 'LoginCtrl'
    });
```
</span>

<span is-issue-template></span>
![screen shot 2015-05-08 at 3 44 48 pm](https://cloud.githubusercontent.com/assets/109041/7546950/441407bc-f599-11e4-94aa-52b60aa995d7.png)

According to [ui-router documentation](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#registering-states-order) states can be declared in any order

**Comment by Ionitron** [comment]
Greetings @thebalaa!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3689). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3689)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
In our demos it works fine. I suspect there's more to the story. Can you reproduce this in a codepen we can inspect?

**Comment by Ionitron** [comment]
Greetings @thebalaa!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @thebalaa!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
