### ISSUE TITLE
bug: Keyboard overlaps input in iOS

### ISSUE THREAD

**Issue by jesusbotella** [driftyco/ionic#3696]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I'm testing my iOS app in my iPad and in the iOS simulator too and there's a problem when opening a ionicPopup. The keyboard overlaps almost all the input size and it hides all the buttons from the popup.

It seems like the popup is showing in the middle and the keyboard open doesn't affect to it at all.

Here I show you an example: http://imgur.com/N5jukSr</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This is something we've spent a good bit of effort trying to consistently avoid. Could you share a codepen or example project that reproduces this so we can add it to our tests?

**Comment by Ionitron** [comment]
Greetings @jesusbotella!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @jesusbotella!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
