### ISSUE TITLE
docs: Input with type email not binding with model

### ISSUE THREAD

**Issue by manugb** [driftyco/ionic#3698]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Rather than an issue, it should be a note in the input types section. Naming that if the text written in the input will not be binded unless is a valid email.

Regards!</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
I don't understand. Could you please clarify?

**Comment by manugb** [comment]
If you have this:
<p>{{user.email}}</p>
<input type="email" ng-model="user.email">

When you start writing in the input, you should see what you are wrinting in the p element. But as it is an email input, is going to be bound only when whatever you are writing is a valid email.

So if you could add a note in the input section explaining this it will be clearer.

**Comment by manugb** [comment]
Sorry, if you have this:

<p>{{user.email}}</p>
<input type="email" ng-model="user.email">

**Comment by aguspina** [comment]
I guess what @manugb meant to say was this: 

```html
<p> {{user.email}} </p> 

<input type='email' ng-model='user.email'>

**Comment by ag-secret** [comment]
I think that's more about angular than ionic

**Comment by manugb** [comment]
Agree, but adding that info to the docs wont hurt anybody.

**Comment by perrygovier** [comment]
Ah, yeah, that's part of Angular's validation on binding. You can see it clearly, here
http://plnkr.co/edit/?p=preview

There's a lot of quirks and oddities in Angular that we could/should mention. Currently we don't have a good place to put that, but we're working on some general tutorials and informational tools for Angular itself. I don't think we should add this to Ionic's documentation, but we should be sure to add it there when it's live.
