### ISSUE TITLE
bug: with gradle compile geolocation plugin not working

### ISSUE THREAD

**Issue by burt35** [driftyco/ionic#3715]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>New gradle compiling doesn't make usable geolocation plugin in apk (installed on device), where the ant build was. In browser all fine.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Could you provide the output form `ionic info`. Just tried this with the cordova-android 4.0 and it built right for me.

**Comment by perrygovier** [comment]
Also, be sure to add and remove the plugin if this is an older project. Many plugins have been updated recently to work with the new build system.

**Comment by burt35** [comment]
Sorry, it's not the plugin, the MAPS aren't working. I think it's a Cordova project problem. 
Even with your basic maps project, when you add the android platform, now it compiles with gradle, and in device maps are not showing. The same project made a few days ago, compile with ant and everything is (almost) fine.

Here are the info:
OS: Windows 8.1
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 0.9.27
Ionic CLI Version: 1.3.22

I put the plugins in package.json and made  " ionic state restore ". I think they must be the lasts.

**Comment by mhartington** [comment]
Hmm, have you added the cordova-whitelist plugin?

```
ionic plugin add cordova-plugin-whitelist
```

This was a change in cordova-android

**Comment by burt35** [comment]
Everything fine now!
Thanks a lot.
( Now I have to understand what it is!)
Bye
