### ISSUE TITLE
bug: Tab controller not executing (with cache disabled)

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic#3721]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have set view caching to false, but the tab controller still does not execute when the tab is loaded. This seems to be the case only for the initial tab which is open when the app loads.

This issue did not occur in beta 14, but I just upgraded to 1.0.0, and this issue appeared.

I have tried settings cache to false using both "maxCache(0)" and setting "cache: false" in the route.</span>

<span is-issue-template></span>

**Comment by AgDude** [comment]
I have narrowed this down to a change between Beta.14 and RC.0

**Comment by AgDude** [comment]
This seems to have been caused by including ```ion-nav-button``` inside ```ion-tab``` before ```ion-nav-view```.

I am not sure why this fails, but at the very least, some sort of error would be nice, instead of the silent failure.

**Comment by perrygovier** [comment]
Could you demonstrate it in a codepen? I can see if there's a good place to add a console error.

**Comment by Ionitron** [comment]
Greetings @AgDude!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @AgDude!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
