### ISSUE TITLE
bug: Tabs and iOs 8.3

### ISSUE THREAD

**Issue by chooseapp** [driftyco/ionic#3735]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there,

I am not sure if it is a bug or a mistake of my utilisation of ionic, but I wanted to reproduce the facebook messenger systems with the tabs (i.e : you have the chats list with tabs in the footer,  and when you open a chat-details, you do not see the tabs in the footer).

But by doing that, I have to create a button for going back to the chat list (in the nav or in the ion-content) : 
```  
<ion-nav-buttons class="button-clear">
        <button class="button-clear icon ion-ios-arrow-back" ui-sref="tab.chats">
        </button>
    </ion-nav-buttons>
```
But if you do that, for sure after 5 chats opened and 5clicks on the back-button (sometimes at the first time), you will have this error : 

```
 026541   error    Error: Attempted to assign to readonly property.
ChildScope@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:22381:42
$new@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:22389:40
generateNavBarItem@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:50136:40
beforeEnter@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:50075:44
$emit@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:23346:38
emit@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:46620:24
transition@http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:46493:26
http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:48119:26
http://192.168.77.101:8100/lib/ionic/js/ionic.bundle.js:46371:33
```

My code is here : 
http://codepen.io/anon/pen/rVeZow

![bug](https://cloud.githubusercontent.com/assets/11384261/7637994/ae61a494-fa26-11e4-987d-9ce12d9482aa.png)

But you will need to emulate it on iOs for seeing the bug. When the bug comes, the arrow disappears, and the application looks like it is still working, but infact it is not, you can move in the views but lots of functions are dead. And You have to restart the application.

Thanks for telling me if it is a bug or a mistake of my own and my use of tabs and view.
Best,
Thibaut</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @titi3391!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3735). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3735)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Something like this breaks the navigation, which is a known issue, but is also a limitation of ui-router.
You could get the same effect with a custom directive.

http://codepen.io/mhartington/pen/aONRdK

**Comment by chooseapp** [comment]
Hi there,

I believed it was okay, but today I got again this bug in another way : 

http://codepen.io/anon/pen/bdBybQ

If you try with a slidebox in the chat-details, after visiting a few on them, you will get the same error and your application is doing crazy thing.

It is the same issue or not ?
am I wrong with the slidebox ?

Thanks in advance

**Comment by mhartington** [comment]
Hmm, I wasn't able to get any error in my tests in that codepen

**Comment by chooseapp** [comment]
I have just tried it again, and the error is still here.

Did you try with the iOs simulator ? or you wont have it on the codepen (the codepen is only here for explaining the situation)

**Comment by mhartington** [comment]
Just tried it on a real device now, iphone5, and wasn't able to get the error unfortunately. If you could provide a git repo maybe? Are you seeing this in that codepen or in a larger project that has a similar setup?

**Comment by Ionitron** [comment]
Greetings @chooseapp!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @chooseapp!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by uxder** [comment]
Any solution to this....getting the same error.

**Comment by mhartington** [comment]
Can you provide an example of this? We were never able to replicate the issue

**Comment by uxder** [comment]
Actually, I discovered that my problem was with ion-slide.  See #4091

**Comment by gimox** [comment]
see #4091 for solution
