### ISSUE TITLE
feat: Support ui-sref with params on tab directive

### ISSUE THREAD

**Issue by jryu01** [driftyco/ionic#3751]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ui-sref='stateName({param: value, param: value})' syntax work on <a> tag but not with tab directive.
It would be nice to have ui-sref with params working as expected on tab directive too. 

codepen example:
http://codepen.io/jryu01/pen/Nqrqoj</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
The link used by `ion-tab` isn't the final link that will be used, it sets the default view for a tab group. If you navigate a few levels deep, and go to a different tab, clicking on that first tab takes you to a different page. 

Given that, passing in state params seems like something that could be architected differently. Sorry, there's other ways to achieve the same results that doesn't introduce as many new problems that need to be solved. I'd suggest passing the data through a service or an event.
