### ISSUE TITLE
perf: 20% of CPU for the ion-refresher !

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#3756]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Some users (and me) using Android devices with Android 5.0 noticed that when my ionic app is in background, it still requires 20% of CPU !

I investigated and noticed that the ion-refresher was causing the issue !
When I remove it, 0% of CPU when the app is in the background, as expected. 
I'm using currently the latest release of Ionic: 1.0.0

Any explanation? Sounds like a big bug to fix.

Related post: http://forum.ionicframework.com/t/pull-to-refresh-memory-leak-android-5-0-only/22345

Thanks a lot</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
I believe this is related to #3583. Lets fix that first and then re-assess if there's still an issue.

**Comment by mica16** [comment]
Ok perfect, thanks for the reply.

**Comment by marcelinobadin** [comment]
I am using ionic 1.1.1 and the fix from  #3583 didn't solve the problem with ion-refresher. Once I include it the CPU goes to over 30%. Once I remove it, I got 0%. Does anybody knows how to fix it?
