### ISSUE TITLE
bug: windowSoftInputMode to adjustPane - Maybe a bug?

### ISSUE THREAD

**Issue by GeorgePapado** [driftyco/ionic#3759]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello. I am implementing an app using the ionic cli for building the app.  
I try yesterday to change the ‘windowSoftInputMode’ for Android to ‘adjustPane’ without success.
I change the preference in the config.xml and upload the app. I try to do this with both preference options for fullscreen (true/false). 

What is here there right option? From the documentation it must be set to true. In many stack-over-flows answers it should work with false. 

I have also try ‘ionic add platform android’ to see what for a AndroidManifest.xml file is generated. The generated file is not affected by my preference. 

Is there a bug maybe? Or what I did wrong? I see if I change for example the orientation via preference there is also a change in the generated Manifest file. 
 
I use the latest version of ionic and cordova.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @GeorgePapado!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3759). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3759)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by GeorgePapado** [comment]
Preference in config.xml: "<preference name="android-windowSoftInputMode" value="adjustPan"/>" 
Generated Manifest: "<activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">"

**Comment by GeorgePapado** [comment]
![preferences](https://cloud.githubusercontent.com/assets/6442981/7675275/b62d5dea-fd36-11e4-84b1-ce39feaf40bf.PNG)

**Comment by perrygovier** [comment]
@tlancina, can you take a look?

**Comment by tlancina** [comment]
I don't believe there is a "android-windowSoftInputMode" preference for Cordova: https://cordova.apache.org/docs/en/5.0.0/guide_platforms_android_config.md.html#Android%20Configuration (there is one for PhoneGap, which is probably where the confusion is). If you want to use adjustPan, you'll have to edit the generated AndroidManifest.xml in your Android project folder, making sure to set your fullscreen preference to false.  You might also have to call `ionic.keyboard.disable()` to prevent the Ionic keyboard code from scrolling things into view for you.

Closing this as it's not really an issue with the framework.  If you're still having troubles, the [Ionic forum](http://forum.ionicframework.com/) is a great place to get help.
