### ISSUE TITLE
feat: placeholder while loading images

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic#3761]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having a placeholder while image is loading would be really nice addition to ionic. Placeholder can be a spinner gif or watermark logo of app which can be specified on <img /> element using a directive

thanks</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
We're going to be building an add-ons marketplace. This would be perfect for that! Stay tuned.
