### ISSUE TITLE
feat: Custom index for buttons in ActionSheet

### ISSUE THREAD

**Issue by Tomino2112** [driftyco/ionic#3764]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be very helpful to be able to set custom index for buttons in ActionSheet. 

At the moment we use the array index to indentify what button was pressed, but sometimes (actually lot of times) we need to dynamically add and remove buttons from menus and then it gets very inefficient to handle the button actions. 

it would be so much better to be able to do: 

    {text: 'Button 1', index: 'button1'}

Example - Document menu

     var menuOpt = {
     buttons: [
         {text: '<i class="icon ion-android-share-alt"></i> Share'},
         {text: '<i class="icon ion-information-circled"></i> Page Info'}
     ],
     buttonClicked: function(index){         
         if ($scope.pageAccess && $scope.pageAccess.is_administrator && $scope.page.special_page_type<1) {             // Handle admin menu
             switch (index) {
                 case 0:
                     // Page Settings
                     $scope.pageSettings();
                     break;
                 case 1:
                     $scope.sharePageToggle();
                     break;
                 case 2:
                     $scope.showInfo();
                     break;
             }
         } else {
             switch (index) {
                 case 0:
                     $scope.sharePageToggle();
                     break;
                 case 1:
                     $scope.showInfo();
                     break;
             }
         }
         hideSheet();
     },
     cancelText: 'Cancel'
     };

    if ($scope.pageAccess && $scope.pageAccess.is_administrator && $scope.page.special_page_type<1){ // Admin extra stuff
    menuOpt.buttons.unshift({text: '<i class="icon ion-gear-a"></i> Settings'});
    
    menuOpt.destructiveText = '<span class="assertive"><i class="icon ion-ios-trash-outline"></i> Delete Page</span>';
    menuOpt.destructiveButtonClicked = function(){
        var popup = $ionicPopup.confirm({
            title: 'Delete Page',
            template: 'Are you sure you want to delete this page? This cannot be undone'
        });
        
        popup.then(function(res){
            if (res) {
                deletePage();
            }
        });
        hideSheet();
    }
    }

    var hideSheet = $ionicActionSheet.show(menuOpt);

You cna see what a pain it becomes to handle the action in ActionSheet. If we could set custom indexes it would simply the process a lot.</span>

<span is-issue-template></span>

**Comment by Tomino2112** [comment]
Actually, I am closing this as this is very easily extensible - didn't think of that - MONDAY! 

You can simply add id yourself as follow:

    buttons: [
        {text: '<i class="icon ion-android-share-alt"></i> Share', index: 'share'},
        {text: '<i class="icon ion-information-circled"></i> Page Info', index: 'info'}
    ],

And then handle actions:

    buttonClicked: function(index){
        switch (this.buttons[index].index) {
            case 'settings':
                $scope.pageSettings();
                break;    
            case 'share':
                $scope.sharePageToggle();
                break;
            case 'info':
                $scope.showInfo();
                break;
        }
        hideSheet();
    },

**Comment by nagubabu** [comment]
@Tomino2112 It helped me a lot. Thanks
