### ISSUE TITLE
bug: ion-navicon overlapping on header title

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic#3766]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>i tried using sidemenu template with ionic tabs but when its loaded for first time on android  the navicon overlaps on header title , i couldn't recreate this in codepen so i created a repo on github 
just 
https://github.com/programming-kid/ionic-sidemenu-demo
```git clone```

```ionic serve -l```
</span>
![screenshot from 2015-05-18 16 54 37](https://cloud.githubusercontent.com/assets/4522965/7681583/ea171e9a-fd8e-11e4-8867-b4d40092fb25.png)

<span is-issue-template></span>

I also noticed that when using ```ion-tabs``` the bottom border of header bar is missing , just navigate to search from sidemenu to view this 

![screenshot from 2015-05-19 00 45 02](https://cloud.githubusercontent.com/assets/4522965/7688213/a2644de8-fdc0-11e4-9d79-803188a33fbd.png)

**Comment by perrygovier** [comment]
you're nesting tabs inside side menus. this is normally discouraged and if you do, it has to be done in a very specific way. In this case, if you put the `ion-nav-buttons` inside `browse.html`, it works fine. Here's an example of some of the more complicated structures we support and how to do them in a way that will work https://github.com/driftyco/ionic-starter-tests
