### ISSUE TITLE
bug: Collection Reapeat uses same space for every item

### ISSUE THREAD

**Issue by Tomino2112** [driftyco/ionic#3767]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

Here is my code:

    <ion-list>
            <div collection-repeat="folder in keyringData">
                <ion-item class="item-divider item-icon-right">{{folder.domainName}}</ion-item>
                <ion-item class="item-icon-right" ng-repeat="key in folder.keys">{{key.name}}<i class="icon ion-more" ng-click="showKeyMenu(folder,key)"></i></ion-item>
                <ion-item class="text-center" ng-show="!folder.keys.length"><small>No keys for this folder</small></ion-item>
            </div>
        </ion-list>

### Using ng-repeat
![2015-05-18_165218](https://cloud.githubusercontent.com/assets/1140217/7684550/d508f4ca-fd7e-11e4-9fe9-78cd8f8b6567.jpg)

### Using collection-repeat
![2015-05-18_165156](https://cloud.githubusercontent.com/assets/1140217/7684551/d50a6fa8-fd7e-11e4-9183-bea3f0418adb.jpg)

**Comment by perrygovier** [comment]
This is by design. If you want dynamic heights you can use the [`item-height` attribute](http://ionicframework.com/docs/api/directive/collectionRepeat/).
