### ISSUE TITLE
bug: Hammer.js Pinch features not working in Ionic Android platform.

### ISSUE THREAD

**Issue by flrmatjd** [driftyco/ionic#3774]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi

This code is my test code that text font-size changing with pinch features in Hammer.js.
    
// script src="https://hammerjs.github.io/dist/hammer.js"
// /script

  <body ng-app="starter">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content>
      <div data-tap-disabled="true" id="myText">BBBBBBBBBBBBB</div>
      </ion-content>
    </ion-pane>
  </body>

  //script type="text/javascript"
  var myElement = document.getElementById('myText');
	var minFontsize = 8;
	var maxFontsize = 72;
// create a simple instance
// by default, it only adds horizontal recognizers
  var mc = new Hammer.Manager(myElement);
  // create a pinch and rotate recognizer
  // these require 2 pointers
  var pinch = new Hammer.Pinch();
  //var pinchin = new Hammer.PinchIn();
  // add to the Manager
  mc.add([pinch]);
  mc.on("pinchin", function(ev) {
      var curFontsize = parseFloat(window.getComputedStyle(myElement,null).getPropertyValue('font-size'));
      if (curFontsize < minFontsize) { curFontsize = minFontsize};
      myElement.style.fontSize = (curFontsize -1) + 'px';
      myElement.style.lineHeight = "100%";
  }).on("pinchout",function(ev){
      var curFontsize = parseFloat(window.getComputedStyle(myElement,null).getPropertyValue('font-size'));
      if (curFontsize > maxFontsize) { curFontsize = maxFontsize};
      myElement.style.fontSize = (curFontsize +1) + 'px';
      myElement.style.lineHeight = "100%";
  });

// /Script

This test code works at web page very well but when build it with cordova ionic framework then It doesn`t work.

I think Ionic framework prevent this event handler.
Please help me with this issue.

thanks.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @flrmatjd!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3774). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3774)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by perrygovier** [comment]
We actually use chunks of hammer.js in our source. It's undocumented, but I think the pinch gesture still works if using `$ionicGesture`. 

For using hammer.js. You'll certainly need to use `data-tab-diabled="true"`. If that doesn't help, could you demonstrate the problem in an example project we can see in codepen or scratch?

**Comment by flrmatjd** [comment]
Thank you for reply.

I have used data-tab-disabled="true" but it does not work. 

http://codepen.io/flrmatjd/pen/EjyBxO

This is codepen url.

If you open this url with phone then you can see it works correctly.

But If this code build with cordova android app then It does not work in android phone.
