### ISSUE TITLE
bug: SVG in IE (Mobile) causes errors - no classList

### ISSUE THREAD

**Issue by PatAtMacadamian** [driftyco/ionic#3775]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Using D3/SVG elements causes errors to be thrown in IE (desktop and mobile) due to the lack of classList support in the browser.

using a specific polyfill will remove the issue.
https://github.com/PatAtMacadamian/classList.js 
(note: minified version does not contain the fix at this time)</span>

<span is-issue-template></span>

**Comment by PatAtMacadamian** [comment]
specifically, using the ionic framework to add click & other events to svg elements causes issues.

**Comment by perrygovier** [comment]
We wont be adding the polyfill to Ionic core unless a core component specifically requires it, but thanks for mentioning it in case people have trouble in their own apps. If you want to help get the word out, I'd keep an eye on the forums for people having that problem.
