### ISSUE TITLE
bug: Unable to use collection-repeat more than once

### ISSUE THREAD

**Issue by BetterTrader** [driftyco/ionic#3784]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,
It seems that calling collection-repeat more than once in the same HTML page - breaks.
Codepen:
http://codepen.io/anon/pen/LVRPMq

Any ideas on this?
Thank you</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Looks like it's working fine, but I think you mean to structure your codepen differently. Either way, `collection-repeat` is pretty heavy handed with its scrollable area, and you don't want to have one in more than one scrollable area. 

If you're having trouble, you may want to use `<ion-scroll>` to encapsulate each. Here's an example that uses them and I think does what you mean to in your codepen:
http://codepen.io/perrygovier/pen/WvGxrO?editors=101
