### ISSUE TITLE
bug: Hooks Folder Not Found (Windows)

### ISSUE THREAD

**Issue by cgosiak** [driftyco/ionic#3798]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>command:
ionic build android

results:
Error { [Error: ENOENT, no such file or directory 'C:\Users\cgosiak\Documents\hoonuit_app\hooks']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\cgosiak\\Documents\\hoonuit_app\\hooks',syscall: 'scandir' }
Updated the hooks directory to have execute permissions

further info:
pulling code using 'git', same 'git' used on mac and no issues are found. I have tried pulling the repository multiple times to different local locations on machine. All resulting in the same outcome.

Works on mac fine with identical code, does not work on windows</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#437

**Comment by perrygovier** [comment]
Moved this to the CLI repo
