### ISSUE TITLE
bug: View Jump

### ISSUE THREAD

**Issue by NeRo2pt0** [driftyco/ionic#3799]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>This is with the current build of ionic and it happens on iOS 8.3.

To Reproduce:
-Create a new ionic tabs template project with latest build of ionic
-Go into the account tabs and add around 20 input fields inside the ion list directive using 
```html
    <label class="item item-input">
    <input type="text" placeholder="First Name">
  </label>
```
-Input data into the very last input field of the list; without scrolling down to it.

You should see the whole view bounce to a point where the navigation bar gets pulled down.  This happens to any input field that is not near the top of the view</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NeRo2pt0!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3799). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3799)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by NeRo2pt0** [comment]
duplicate.  Sorry about that.

**Comment by NeRo2pt0** [comment]
I thought this was a duplicate but this hasn't been solved properly.  Any suggestions on how to overcome this issue?  I have a demo for this application with potential customers and it would be great if there was a work around for this.  Thanks!

**Comment by perrygovier** [comment]
Ok, I can reproduce it. Here's a codepen to get started 
http://codepen.io/perrygovier/pen/zGKMWe?editors=101

Here's a video demonstrating the issue:
https://www.youtube.com/watch?v=XFEUxeZpN-w

@NeRo2pt0, this is what you see too, right?

**Comment by NeRo2pt0** [comment]
Yes this is exactly what I see.

**Comment by miguelcaro8706** [comment]
any fix for this issue?

**Comment by NeRo2pt0** [comment]
@miguelcaro8706 I simply disabled the scroll on the cordova keyboard plugin.

cordova.plugins.Keyboard.disableScroll(true);

This solved my issue.

**Comment by miguelcaro8706** [comment]
Thanks a lot @NeRo2pt0, it's working

**Comment by NeRo2pt0** [comment]
You're welcome @miguelcaro8706 Happy coding! :)

**Comment by robinvanb** [comment]
We have the exact same problem. And even with disableScroll it's not working.
I've made a video that demonstrates this, available here: https://www.youtube.com/watch?v=soBuGy_HC88&feature=youtu.be

We're using ionic 1.5.0, cordova 5.1.1 and we're using 1.0.5 of this keyboard plugin: https://github.com/driftyco/ionic-plugin-keyboard

**Comment by chelzwa** [comment]
We're also having this problem on iOS 8.4 even with disableScroll. We're using Ionic 1.0.0-rc.5 (CLI v1.6.4), Cordova for iOS 3.8.0, and version 1.0.4 of ionic-plugin-keyboard.

**Comment by mhartington** [comment]
Please update to the latest release, this has been fixed.

**Comment by chelzwa** [comment]
My apologies, we should have tried that first-- updating did fix it for us.

**Comment by tonyisid** [comment]
Yes, updating have no effect for me too.
