### ISSUE TITLE
bug: $ionicView events in wrong order

### ISSUE THREAD

**Issue by bodinaren** [driftyco/ionic#3800]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you look at this [codepen](http://codepen.io/bodinaren/pen/bdwYRR?editors=101) you'll see the order of the $ionicView events is as follow:

```
$ionicView.loaded

$ionicView.beforeEnter
$ionicView.afterEnter
$ionicView.enter

$ionicView.beforeLeave
$ionicView.afterLeave
$ionicView.leave

$ionicView.unloaded
```

`enter` and `leave` should happen before `afterEnter` and `afterLeave` respectively, [according to the docs](http://ionicframework.com/docs/api/directive/ionView/#usage) (and obviously logically as well).</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
fixed in fa918ee27a5340a318bb39e138eeeb358cd3ecb0
