### ISSUE TITLE
bug: Nav title doesn't adapt to visibility of buttons

### ISSUE THREAD

**Issue by bostondv** [driftyco/ionic#3815]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Using left or right aligned nav buttons in conjunction with a conditional ng-if or ng-show can cause the buttons to overlap with the navbar title, especially if it's left or right aligned.

For example, a left aligned title and left nav button that's hidden by an ng-if initially will appear correctly at first, but when the ng-if is triggered to show the left button it will overlap with the title. 

Expected behaviour would be to adjust the position of the title when the button is shown or hidden.

Example here: http://play.ionic.io/app/5fe129292cc1</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
We should watch for those. Thanks

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
