### ISSUE TITLE
bug: list view delete button breaks app on iPhone 4S with iOS 7.1

### ISSUE THREAD

**Issue by UdoBretz** [driftyco/ionic#3816]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi Ionic-Team,

I found a strange issue in my app, but I'm able to reproduce it with the starter template app with tabs:

> ionic start MyTabsApp tabs
> cd MyTabsApp
> ionic build ios

Then open xcode, open the project, select iPhone 4S (iOS 7.1). 
Click on Build & Run. The app runs in the simulator. 

Go to the "Chat" tab and see the list of chats.
Swipe left on any chat, so that the red "Delete" button shows up.

Click on delete -> Crash!

If you change the target to iPhone 4S (iOS 8.1) it will work fine. 

The same problem also happens on my real device (iPhone 4S).

Thanks in advance for investigating,
Udo</span>

<span is-issue-template></span>

**Comment by UdoBretz** [comment]
Mac OS X 10.9.5
Xcode Version 6.1

**Comment by UdoBretz** [comment]
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X Mavericks
Node Version: v0.12.1
Xcode version: Xcode 6.1 Build version 6A1052d

**Comment by NeRo2pt0** [comment]
I've experienced this as well.  I believe you can delete the last item always and it works but the moment you delete something in between it crashes.  Check the array.splice function to make sure you specify the amount of items to be deleted.

**Comment by UdoBretz** [comment]
yes, that's exactly what happens here. But the splice command looks like this, this should work:

    remove: function(chat) {
      chats.splice(chats.indexOf(chat), 1);
    },

And, what I still don't get is the fact that it works on iOS 8.1.

**Comment by scottsut** [comment]
@NeRo2pt0 yes, that is!  I also got this problem.

**Comment by scottsut** [comment]
Platform: ios 7 webview
device: iphone 4s
ios version: 7.1.2(11D257)

**Comment by scottsut** [comment]
@UdoBretz  have you resolved this problem yet?

**Comment by scottsut** [comment]
after few tests, I'm pretty sure that's the "ion-item" style "item-remove-animate" cause the problem

**Comment by UdoBretz** [comment]
I wasn't able to resolve this issue. I now detect the iOS Version, and disable the "Left Swipe Delete" functionality. But that's just a bad workaround, as would also like to use the functionality on iOS 7.

**Comment by NeRo2pt0** [comment]
One thing you could do potentially (depending on your application) is to have a status field for deleted items.  Then instead of actually removing the item from the array; just filter out the items based on that status.  Hopefully this gets fixed soon.

**Comment by zero7u** [comment]
same issue with me.
I have to remove the animation on ios7
````ng-class="{'item-remove-animate': !ios7}"````
ios7太坑爹了。。

**Comment by scottsut** [comment]
哈哈！是啊。
现在 ios7 和 android 4.3以下的机器就跟当年的 ie6 一样，各种奇怪的问题。

**Comment by zero7u** [comment]
@scottsut 哈哈！安卓有crosswalk，ios7啥都没有~

**Comment by zero7u** [comment]
@scottsut 我们有个解决方案，用自定义动画替换掉原来的动画(需要jQuery)：
Using custom animation instead of 'item-remove-animate', jQuery needed.
````
.animation('.my-item-remove-animate', function($timeout) {
	return {
		leave: function(elem, cb) {
			var e = $(elem[0]);
			var others = e.nextAll('.item');

			$timeout(function() {
				others.css({
					'-webkit-transition': '0.3s all linear',
					'-webkit-transform': 'translateY(' + (-e.height()) + 'px)'
				})
				$timeout(cb, 300)
			})

			return function(isCancelled) {
				if (isCancelled) {
					others.css({
						'-webkit-transition': '',
						'-webkit-transform': ''
					})
				}
			}
		}
	}
})
````
It works fine on ios7 and others, any idea will be appreciated!

**Comment by DrakenZA** [comment]
Issue is still around ! I believe it has something to do with a css function getting called that ios7.1 cant handle or something.

**Comment by jgw96** [comment]
Hello! Are you all seeing this issue only on ios 7 or on newer version of ios too?

**Comment by jgw96** [comment]
Hello all! As it has been a little while since there was any activity on this issue, i will be closing it for now. Thanks!
