### ISSUE TITLE
bug: collection-repeat broke my "geo:" link

### ISSUE THREAD

**Issue by henryavila** [driftyco/ionic#3827]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When I use the following code inside a collection-repeat the ge: link don't work:

```<a ng-click="abreAppExterno('{{delegacia.coords}}')" class="item item-icon-left wrap">```

and my function `abreAppExterno` is:
```abreAppExterno: function (link) {
    window.open(link, '_system', 'location=no, toolbar=no');
}```

it work perfectly inside ng-repeat, but when I change to collection-repeat, it just don't work.

in Browser, it just open a blank new window, in the phone, it sugest to open in a HTMLViewer</span>

<span is-issue-template></span>

**Comment by iver56** [comment]
Have you tried `ng-click="abreAppExterno(delegacia.coords)"`?

**Comment by henryavila** [comment]
@iver56, I changed and it now works. Thanks,
