### ISSUE TITLE
bug: Ionic website scratchpad demos do not work

### ISSUE THREAD

**Issue by gortok** [driftyco/ionic#3834]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The scratchpad located on the website at learn.ionicframework.com does not work; the console in Chrome reports "Uncaught ReferenceError: IonicScratch is not defined" (line 242 of the root site document).  Here's the relevant code:

    $.when(getTemplate('template.html'), getTemplate('style.css'),  
    getTemplate('script.js')).then(function(html, css, js) {
            var scratch = new IonicScratch({  //Uncaught ReferenceError
              el: document.getElementById('scratch'),
              width: '100%',
              height: '600px',
              html: html[0],
              css: css[0],
              js: js[0]
            });
          })

**Comment by genius50** [comment]
Yeah ! I've noticied that, is there any alternative way where we can find those demos ??

**Comment by oneHappyCanuck** [comment]
Weeks later still waiting for these demos to work #$@&

**Comment by mhartington** [comment]
The learn site is being replaced with another site that is being built, so we're not planning on updating it at the moment. All the content and code demos are up on github.
github.com/driftyco/ionic-learn
