### ISSUE TITLE
bug: Buttons don't work in ionlist-item directive

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ionic#3840]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I'm trying to add a button to a list item as described here:

http://ionicframework.com/docs/components/#item-buttons

The button appears, but click event's don't register (regardless of delete or reorder buttons).  AppController.play() isn't called.   $event.preventDefault(); $event.stopPropagation() prevent the ui-sref from happening.

Here's what I tried:

```
    <ion-list 
      ng-controller="AppController"
      show-delete="showDelete"
      show-reorder="false">

      <ion-item ng-repeat="(id, suggestion) in user.suggestions" 
        ui-sref="app.suggestionSetting({id: id})">
        <ion-delete-button class="ion-minus-circled"
          ng-click="user.suggestions.splice($index, 1)">
        </ion-delete-button>
        <ion-reorder-button class="ion-navicon"
          on-reorder="moveItem(suggestion, $fromIndex, $toIndex)">
        </ion-reorder-button>

        <a
          class="button button-small button-positive"
          ng-click="play(suggestion); $event.preventDefault(); $event.stopPropagation();">
          <i class="icon ion-volume-medium"></i>
        </a>

        {{suggestion.title}}
      </ion-item>
```

Reimplementing as a \<ul> works, but I lose the reorder functionality.

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v0.12.0

</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please provide a codepen for us to test against

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @MichaelJCole!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
