### ISSUE TITLE
docs: Documentation bug re: $ionicPlatform.currentPlatfo

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ionic#3850]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Re: here:
http://ionicframework.com/docs/api/utility/ionic.Platform/

https://github.com/driftyco/ionic/blob/master/js/utils/platform.js#L15

What are the possible values?  ios, android, windowsphone, blackberry?, tizen?, etc?

Thanks!

Mike</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, I'm not seeing `$ionicPlatform.currentPlatform()` anywhere in the docs. 

```javascript
angular.module('PlatformApp', ['ionic'])
.controller('PlatformCtrl', function($scope) {

  ionic.Platform.ready(function(){
    // will execute when device is ready, or immediately if the device is already ready.
  });

  var deviceInformation = ionic.Platform.device();

  var isWebView = ionic.Platform.isWebView();
  var isIPad = ionic.Platform.isIPad();
  var isIOS = ionic.Platform.isIOS();
  var isAndroid = ionic.Platform.isAndroid();
  var isWindowsPhone = ionic.Platform.isWindowsPhone();

  var currentPlatform = ionic.Platform.platform();
  var currentPlatformVersion = ionic.Platform.version();

  ionic.Platform.exitApp(); // stops the app
});
```

This will actually call the cordova device plugin so it will use that to get the platform. So theoretically it would return the right platform for every platform cordova supports, even if ionic doesn't support it.

**Comment by MichaelJCole** [comment]
Too much coding.  Yes, platform().  

Ok, what are the values though?  If you don't want to list them, then maybe just link to this:  http://cordova.apache.org/docs/en/2.4.0/cordova_device_device.md.html#device.platform

Also, which ones does ionic support then?

Thanks!

**Comment by mhartington** [comment]
Well again, it depends on the device plugin, which supports all of cordovas platforms.

https://github.com/apache/cordova-plugin-device#devicecordova

`.platform()` is essentially a alias for cordova's `device.platform`. 
So ionic only supports iOS and Android for the whole framework, but `ionic.Platform.platform();` would technically work on all corodva's platforms.
