### ISSUE TITLE
bug: Plugins seem hit or miss in Ionic View

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic#3854]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Apps work fine when we publish with Ionic Build. We have been trying to get a more complicated application working for a client on Ionic View so that we can bypass having to put up with TestFlight. However many of the plugins (like the In-App Browser (https://github.com/apache/cordova-plugin-inappbrowser) for when we open up a website) are not working. We have not been able to capture any errors yet, still trying to dig into it, but again, the plugins are working fine with regular deployment. Any ideas would be welcome. Thanks.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-view-issues#114

**Comment by mhartington** [comment]
Moving this to the view issue tracker as this is not an issue with the core framework.
