### ISSUE TITLE
bug: conditional href on ion-tab is not two-way binded

### ISSUE THREAD

**Issue by parliament718** [driftyco/ionic#3856]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
I'm trying to get one of the tabs in my app to have a conditional route, that is based on the current state.
So something like this seems inuitive (with $state added to the scope)
```
<ion-tabs class="tabs-icon-top tabs-stable">
    <ion-tab title="Search" icon-off="ion-ios-search" icon-on="ion-ios-search-strong" 
ng-href="{{ $state.current.name == 'tab.create' ? '#/tab/notify' : '#/tab/search' }}">
        <ion-nav-view name="tab-search"></ion-nav-view>
    </ion-tab>
</ion-tabs>

```

I also tried both

```
href="{{ $state.current.name == 'tab.create' ? '#/tab/notify' : '#/tab/search' }}"
ui-sref="{{ $state.current.name == 'tab.create' ? 'tab.notify' : 'tab.search' }}"
```

The problem is (for all 3 variations) it only works for the href it gets initialized on but doesn't seem to update the target when ```$state.current.name``` changes. More specifically, the attributes on the DOM they DO update, however it seems the internals of `ion-tabs` do not. 

This seems a bug in the two-way binding that needs to be fixed.

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @parliament718!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3856). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3856)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by fvanniere** [comment]
Got the same bug here with a variable in href. title and ng-if are updated.
```html
<ion-tab title="Inscription {{sc.sport.id}}" icon-off="ion-ios-list-outline" icon-on="ion-ios-list" href="#/sport/{{sc.sport.id}}/inscription" ng-if="sc.sport.session">
    <ion-nav-view name="sport-inscription"></ion-nav-view>
  </ion-tab>
```

**Comment by mhartington** [comment]
Do you mind putting together a small codepen for this?

**Comment by parliament718** [comment]
It's not a very clear codepen but it demonstrates the problem: http://codepen.io/parliament718/pen/RPKLYY?editors=101

The ng-href on the contact tab is:

ng-href="{{ $state.current.name == 'tabs.home' ? '#/tab/contact' : '#/tab/contact2' }}"

so:
when coming from the home page, go to the contact tab
when not coming from the home page, go to the second contact tab

If you examine the DOM you'll see the href updates correctly based on the condition, however it has no effect on where the navigation will go. So it seems the href values for ion-tabs get cached on initialization.

**Comment by mhartington** [comment]
Alright, seeing this as well. This may require some work. But a work around would be to use resolves

**Comment by sclearion** [comment]
has anyone tried using a $scope function to bind the dynamic url. It works for me when I need to apply this convention 
```html
<a href="getUrl()">some link</a>
```
```js
$scope.getUrl = function(){...}
```

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
