### ISSUE TITLE
Bug: Sidemenu Content Scrollable When Side Menu Exposed

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic#3860]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When you have native scrolling enabled on 1.0.0, and you scroll a list then drag to vie the sidemenu list you can still scroll the small ion-view and interact with its clickable stuff. It should normally be non intractable.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you provide a codepen for this @saniyusuf

**Comment by Ionitron** [comment]
Greetings @saniyusuf!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @saniyusuf!

My sensors indicate a reply was requested, but we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
