### ISSUE TITLE
feat: Create a structure partial in many controller files

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ionic#3865]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello everyone, how are you?

I'm having problems in AngularJs for mobile.
My controller is no longer reusable then tried creating my MVC framework with script.js and "include" file is perfect.

I have two problems with this structure:

- Via browser, when accessing a URL by clicking on a link "crashes".
If I carry straight with a refresh on the page, it works.

- When creating a JS in the standard "angularjs-Styleguide" with LIFE scoping, I have trouble identifying the variables created in this file to others.

Please, help me!

index.html

```html
<!-- your app's js -->
<!-- // <script src="js/Script.js"></script> -->
<script src="js/App.js"></script>
<script src="js/Route.js"></script>
<script src="js/Controller.js"></script>
<!-- <script src="js/directives.js"></script> -->
```

App.js

```javascript
var app = angular.module('starter', [
    'ionic', 'starter.controllers',
]);

// Include Route.js
$script('js/Route.js');

// Include Controller.js
$script('js/Controller.js');

// Include Filter.js
// $script('js/Filter.js');

app.run(execute);
```

Controller.js

```javascript
var _controller_ = (window.location.hash).replace("#/app/", "");
// load all files asynchronously!
$script( 'js/Controllers/' + _controller_ + '.js');
```

Error from console:

```bash
Error: [ng:areq] Argument 'DestinationsCtrl' is not a function, got undefined
http://errors.angularjs.org/1.3.13/ng/areq?p0=DestinationsCtrl&p1=not%20a%20function%2C%20got%20undefined
    at REGEX_STRING_REGEXP (ionic.bundle.js:8762)
    at assertArg (ionic.bundle.js:10279)
    at assertArgFn (ionic.bundle.js:10289)
    at ionic.bundle.js:17130
    at IonicModule.controller.self.appendViewElement (ionic.bundle.js:48243)
```

References:
[https://github.com/ded/script.js] [ script.js ]
[https://github.com/toddmotto/angularjs-styleguide#modules] [ style guide ]

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3865). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3865)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So this is probably relate to the way you're loading your js. Chances are, you probably don't need script.js, which could be causing the issues. Try removing that and just loading your code normally.

**Comment by Ionitron** [comment]
Greetings @devtosystems!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
