### ISSUE TITLE
bug: ion-list won't close properly

### ISSUE THREAD

**Issue by nikoTM** [driftyco/ionic#3873]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If the ion-list-item was spliced from ion-option-button and the list is set to track by $index it won't close properly.
http://codepen.io/anon/pen/bdBomN</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
