### ISSUE TITLE
feat: Set spinner icon via $ionicConfigProvider

### ISSUE THREAD

**Issue by mikejpeters** [driftyco/ionic#3877]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It would be useful to be able to configure the default spinner icon via the $ionicConfigProvider service (e.g. you want all platforms to use the bubbles icon).</span>

<span is-issue-template></span>

**Comment by jimthedev** [comment]
This is exactly what I am looking for. Thank you. Would this need an associated test?

**Comment by mhartington** [comment]
I like this idea, I'll review the PR. Thanks @mikejpeters

**Comment by perrygovier** [comment]
added in cf338cf2c8b1ab6dc83f9cdc4525c04350952ce1
