### ISSUE TITLE
bug: Error when running "ionic serve"

### ISSUE THREAD

**Issue by ian-paterson** [driftyco/ionic#3880]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am getting the following error when trying to run 'ionic serve' in the command line:
```
Serve.loadSettings - You must pass a project object to pull out project specific settings from

Error: Serve.loadSettings - You must pass a project object to pull out project specific settings from
    at Object.loadSettings (/Users/ianpaterson/.nvm/v0.10.32/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:153:11)
    at Object.IonicTask.run (/Users/ianpaterson/.nvm/v0.10.32/lib/node_modules/ionic/lib/ionic/serve.js:30:23)
    at Object.run (/Users/ianpaterson/.nvm/v0.10.32/lib/node_modules/ionic/lib/cli.js:71:32)
    at Object.<anonymous> (/Users/ianpaterson/.nvm/v0.10.32/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Serve.loadSettings - You must pass a project object to pull out project specific settings from (CLI v1.4.8)
```
</span>

<span is-issue-template></span>

**Comment by danielmilner** [comment]
`ionic emulate` returns basically the same error as well.

**Comment by drmunklung** [comment]
Getting the same issue, version 1.4.8 on apps I've had working before and an app I just created to test if it had the same issue.

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.8
Gulp local:   Local version 3.8.8
Ionic Version: 1.0.0-beta.11
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.32
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by ewhitmore** [comment]
Same on windows:
Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
OS: Windows 8.1
Node Version: v0.12.4

**Comment by rodrigopecci** [comment]
Same error.

System information:

Cordova CLI: 5.0.0
Gulp version: CLI version 3.8.11
Gulp local: Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
OS: Windows 8.1
Node Version: v0.12.4

**Comment by ian-paterson** [comment]
System Information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0-rc.3
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.10.32
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by danielmilner** [comment]
https://github.com/driftyco/ionic-cli/issues/453

**Comment by wilsojb** [comment]
Same error. 
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0-rc.4
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by QimatLuo** [comment]
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.04 
Node Version: v0.12.2

**Comment by kurthurst** [comment]
Same error...

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.3

**Comment by nattawutAmsri** [comment]
I got the same error

Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.30
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by ewhitmore** [comment]
Temporary fix:  stick with 1.4.5? 

npm install -g ionic@1.4.5

**Comment by chouchua** [comment]
Same problem here, why is everyone getting the same problem?

**Comment by libin2866** [comment]
Me too. Wish it be solved ASAP.

**Comment by karl-ford** [comment]
update and oooohhhhh! back to 1.4.5 tmp

**Comment by ev-tt** [comment]
+1. Same issue. OS X 10.9.3

**Comment by abakik** [comment]
same problem here

**Comment by daniel-elsner** [comment]
Yeah same issue on Windows, started happening right after updating ionic.

**Comment by realw5** [comment]
Same here.

Dans-Mac-Pro:MetProApp Dan$ ionic emulate --livereload
Setup Live Reload
Serve.loadSettings - You must pass a project object to pull out project specific settings from



An error occurred running a Cordova command:Error: Serve.loadSettings - You must pass a project object to pull out project specific settings from (CLI v1.4.8)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.10
Gulp local:   Local version 3.8.10
Ionic Version: 1.0.0-rc.2
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.35
Xcode version: Xcode 6.3.1 Build version 6D1002 



Dans-Mac-Pro:MetProApp Dan$ ionic emulate --livereload

**Comment by michyliao** [comment]
same here lol

**Comment by nikmartin** [comment]
npm install -g ionic@1.4.5 will revert you to 1.4.5 temporarily until they make a release

**Comment by alexklibisz** [comment]
```
npm install -g ionic@1.4.5
```

Worked for me for now.

**Comment by pkosenko** [comment]
I'm glad that I wasn't dreaming this on my own.  I think that ionic 1.4.8 broke "ionic server" as well as a few other things.  I am having the same problem.

**Comment by renesansz** [comment]
For the latest version I'm getting also an error for Windows 10 Preview:
```
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
OS: Windows 8
Node Version: v0.10.33
```

**Comment by ideadx** [comment]
On Mac:
Serve.loadSettings - You must pass a project object to pull out project specific settings from

Error: Serve.loadSettings - You must pass a project object to pull out project specific settings from
    at Object.loadSettings (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:153:11)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/serve.js:30:23)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:71:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Serve.loadSettings - You must pass a project object to pull out project specific settings from (CLI v1.4.8)

Your system information:

Cordova CLI: 4.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.8
Ionic App Lib Version: 0.0.23
ios-deploy version: Not installed
ios-sim version: 3.0.0 
OS: Mac OS X Yosemite
Node Version: v0.10.32
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by svennela** [comment]
dito...

**Comment by svennela** [comment]
downgrade to 1.4.5 still same problem on mac. Please help.


$ An uncaught exception occured and has been reported to Ionic



listen EADDRINUSE (CLI v1.4.5)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.26
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by nyrnzn** [comment]
This error just made me go so mad!

**Comment by Santino-Wu** [comment]
The version 1.5.0 is just been released, see the [change log of ionic-cli](https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md).

Try `npm install -g ionic@1.5.0` to install the last version and it works for me(In Ubuntu).

**Comment by R3TSU** [comment]
Having the same issue here, upgrading to version 1.5.0 solved the issue

**Comment by nikmartin** [comment]
@svennela you still have a server running

**Comment by bradmartin** [comment]
Ionic cli 1.5 fixes the issue from my experience.

**Comment by mhartington** [comment]
Closing this as it relates to the CLI and not the framework. If there is still an issue, please post it to the ionic-cli repo. 

https://github.com/driftyco/ionic-cli/issues/453
