### ISSUE TITLE
http post different Behavior in browser and IOS emulator

### ISSUE THREAD

**Issue by svennela** [driftyco/ionic#3889]
Hi ,

I have below http post, throwing error when i am using IOS emulator. If i use my ionic app from browser, it works totally fine. Please help..

var data = "username=" + credentials.username + "&password="
                    + credentials.password + "&grant_type=password&scope=read%20write&" +
                    "client_secret=mySecretOAuthSecret&client_id=myclientid";

                    var url  = APP_URL + 'oauth/token';
                  
                return $http.post(url, data, {
                    headers: {
                        "Content-Type": "application/x-www-form-urlencoded",
                        "Accept": "application/json",
                        "Authorization": "Basic " + Base64.encode("myclientid" + ':' + "mySecretOAuthSecret")
                    }
                }).success(function (response) {
                    var expiredAt = new Date();
                    expiredAt.setSeconds(expiredAt.getSeconds() + response.expires_in);
                    response.expires_at = expiredAt.getTime();
                    localStorageService.set('token', response);
                    return response;
                });

// Error in IOS emulator

{"data":null,"status":0,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"headers":{"Content-Type":"application/x-www-form-urlencoded","Accept":"application/json","Authorization":"Basic bW9iaWxlamhpcHN0ZXJhcHA6bXlTZWNyZXRPQXV0aFNlY3JldA=="},"url":"http://localhost:8080/oauth/token","data":"username=admin&password=123123&grant_type=password&scope=read%20write&client_secret=mySecretOAuthSecret&client_id=myclientid"},"statusText":""}

**Comment by Ionitron** [comment]
Greetings @svennela!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3889). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3889)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ilaif** [comment]
Anyone found a solution for this?

**Comment by brunoosilva** [comment]
+1

**Comment by jaumeavila** [comment]
Same happens to me...

**Comment by brunoosilva** [comment]
Solution: 

Add this code in you config.xml
```
<hook type="after_prepare" src="package-hooks/ios9_allow_http.sh"/>
```
I am used the `ionic package` for BUILD in iOS. 

But you use the XCode, you have the add hook in your project.

See more: https://github.com/driftyco/ionic-package-hooks/blob/master/ios9_allow_http.sh

**Comment by jaumeavila** [comment]
Thanks @brunoosilva !

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by isambitd** [comment]
I have tried this solution. still I am getting the same issue with status -1.
Need Help!
https://stackoverflow.com/questions/47367140/unable-to-send-data-on-https-post-request-body-is-going-as-null
