### ISSUE TITLE
bug: after imported ngCookies, $cookiesProvider and $cookies are plain object

### ISSUE THREAD

**Issue by aftdotleo** [driftyco/ionic#3895]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
ionic version 1.0.0, after imported ngCookies, such as:
```javascript
<script src="lib/angular-cookies/angular-cookies.min.js"></script>
```
angular-cookies.min.js version is 1.3.13, same with ionic's angular.

usage:
```javascript
angular.module('myApp', [
  'ionic',
  'ngCookies'
]).config('$cookiesProvider', function ($cookiesProvider) {
    console.log('$cookiesProvider', $cookiesProvider);
}]);

angular.module('myApp')
  .controller('registerCtrl', [
    '$scope', '$cookies',
    function ($scope, $cookies) {
      console.log($cookies);
}]);
```

Those all print as plain object!

And i tried to modify demo (http://codepen.io/ionic/pen/Qwpxer), just got same result.
usage:
```javascript
// add script to html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular-cookies.min.js "></script>

// modify controller script
angular.module('ionicApp', ['ionic', 'ngCookies'])

.controller('MyCtrl', function($scope, $cookies) {
  console.log($cookies);
  console.log(1);
});
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @aftdotleo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3895). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3895)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Not sure how ionic could change that package. Could you provide another codepen comparing a vanilla angular project and a ionic project?

**Comment by aftdotleo** [comment]
Hi @mhartington , here is the codepen(http://codepen.io/anon/pen/EjmLme), please check it in your browser console.

**Comment by aftdotleo** [comment]
I have found a strange change, the $cookiesProvider in config scope is ready to work, but in controller, $cookies is still a plain object, like ' $cookiesProvider'.

**Comment by aftdotleo** [comment]
![1 pic](https://cloud.githubusercontent.com/assets/2201795/8037783/6a7d1cfc-0e32-11e5-8bf4-e08d15759d04.jpg)

**Comment by mhartington** [comment]
Hmm, so here's the output from a vanilla angular project (no ionic) 
http://jsbin.com/qelodu/5/edit?js,console

Here's the ionic version 
http://jsbin.com/webohi/1/edit?js,console
 
This appears to be working the same between each version. Ionic doesn't seem to be anything different.

**Comment by aftdotleo** [comment]
Sorry for my careless mistake, I've checked angular-cookies js source code, the version of 1.3.13 is really really different from the 1.4.0.

The API reference i read is 1.4.0 version, Dash's latest version. And i used AngularJS of 1.3.13 version, Ionic 1.0.0. It happens...

Thanks for you testing.
