### ISSUE TITLE
bug: Cached header bar don't stay exactly hidden.

### ISSUE THREAD

**Issue by alvarowolfx** [driftyco/ionic#3898]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On this example I changed the inner header bar colors and you can see that the Cached header bar that stays on top of the Active bar. I encountered this problem when I was developing the feature to change navBar color using navBarDelegate (Pull request #3896). 

http://codepen.io/alvarowolfx/pen/gpWRdJ

I need a hint to fix this, I'm afraid that this was some  strategy to allow the transitions between navigations.</span>

<span is-issue-template></span>

**Comment by sclearion** [comment]
Had same issue here. I ended up disabling caching. App did not suffer a performance hit on mobile either since my views are not heavy at all (using api-driven)
```javascript
.state('app.performance', {
                cache: false,
                url: "/performance",
                views: {
                    'menuContent': {
                        templateUrl: "templates/performance.html",
                        controller: 'PerformanceCtrl'
                    }
                }
            })
```

**Comment by alvarowolfx** [comment]
@sclearion actually when I found this problem I wasn't thinking about performance, it's more a semantic problem because when I develop this new feature (#3896) that I can change the navbar color,  I used the method ```getOnScreenHeaderBar``` of the ```NavBarController``` but changing the "onScreenHeader" body stays on bottom of cached header bar. It's seems a little confusing but the codepen that I posted shows this. 

A workaround on the new feature was to change both of the headers bars, but it's not the best solution.

**Comment by Ionitron** [comment]
Greetings @alvarowolfx!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
