### ISSUE TITLE
bug: ion-view and dynamic title

### ISSUE THREAD

**Issue by paishin** [driftyco/ionic#3901]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a page that I set the title dynamically like the following example
<ion-view view-title="{{page_title}}"></ion-view>

Now when I add a $timeout in my controller, the page title disappears. I know that it eventually works because when I navigate to the next page and come back the page that is brought from the cache contains the correct title.

As a temporary fix I am using the following 
<ion-view view-title="&nbsp;{{page_title}}&nbsp;"></ion-view></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @paishin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3901). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3901)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by sclearion** [comment]
I do this and it works fine:
```javascript
$scope.pagetitle = 'Activity Feed';
```
and in the view do this. Disregard ```ng-init```
```html
<ion-view view-title="{{pagetitle}}" ng-init="init();">
```

**Comment by paishin** [comment]
Try putting the code of the controller in a timeout
```
$timeout(function(){
$scope.pagetitle = 'Activity Feed';
}, 500);

The reason I am facing this is that I am getting the title value from the database which uses promices so the data might not be available at the initial cycle.

**Comment by sclearion** [comment]
Still works for me actually champ. Add a temp title like 'Please wait...'

**Comment by sclearion** [comment]
On the other hand setting a property which should be static (page title) from a database is bad convention unless only part of the page title is dynamic like Welcome: {{promiseData.firstname}}

**Comment by paishin** [comment]
Hmmm... It doesn't for me. Its strange because the title is there when i
come back to the view, maybe its a cacheing issue or something . Ill see if
i can recreate it in an example.

**Comment by sclearion** [comment]
yeah I bet its the cache. I hate the cache mechanism even though I appreciate what its trying to do

**Comment by hydrogennz** [comment]
@paishin I had some problems with the ```<ion-view view-title="{{ my_title }}"></ion-view>``` not updating when changing it the controller so I switched to using:

```
<ion-view cache-view="false">
	<ion-nav-title> {{ my_title }} </ion-nav-title>
</ion-view>
```
This responds to changes to $scope.my_title well and will update the view title properly. Try it and see if it works for you.

**Comment by romulocintra** [comment]
Hi all ,

I did it using the resolve inside the state returning the correct tittle of
the page and this is working very well.without any timeou por evalAsync
Em 11/06/2015 07:25, "Daniel Smith" <notifications@github.com> escreveu:

**Comment by chacewells** [comment]
Wish we could vote up answers like in StackOverflow. +1 to hydrogennz. Worked like a charm.

**Comment by 9cat** [comment]
@hydrogennz  Thanks, it works !

**Comment by stephanngamedev** [comment]
@hydrogennz Thanks, it works !

**Comment by kkiernan** [comment]
@hydrogennz Works great! Thank you!

**Comment by udanpe** [comment]
@hydrogennz Thanks, it works !
But i don't understand why issue was closed. Fix bug!

**Comment by wallstudios** [comment]
Agree this shouldn't be closed. Still a bug.

            <ion-view cache-view="false" >
                <ion-nav-title> {{ClaimingConfig.Title}} </ion-nav-title>
            </ion-view>


works with dynamic content.

    <ion-view view-title="{{Title}}">

does not.

**Comment by Muhammad4320** [comment]
hey wallstudios 
this issue have just a small syntax issue 
<ion-view view-title="{{Title}}">
Solution:
just remove double quates.
<ion-view view-title={{Title}}>

**Comment by Jupiter0806** [comment]
@hydrogennz Thanks a lot, it works for me

**Comment by sonicwong** [comment]
tested on ionic v1.3 with side menu:

this code work:
`<ion-view>
    <ion-nav-title>{{ pageTitle }}</ion-nav-title>`

this code NOT work:
`<ion-view view-title={{Title}}>`
