### ISSUE TITLE
bug: Stopping scroll with tap fires click on views included from external file

### ISSUE THREAD

**Issue by PaperMonster** [driftyco/ionic#3908]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a view containing a long list of clickable items. When I scroll/flick through the list and stop it by tapping, the list stops but fires the `ng-click`. This is similar to #1438 which was supposed to be fixed already in release 1.0.0-rc5. However, It still happens on my project using 1.0.0. 

I made 2 Plunkers to repeat the problem: [Undesired behavior](http://plnkr.co/edit/CDfjsqOpXPYTgd3wSFCO?p=preview) and [Desired behavior](http://plnkr.co/edit/pkP7RRESvahGWrchHVzY?p=preview)
I found the problem occurs when I include the view template from external file (home.html), and doesn't when I move the view template to inline `<script  id="home.html">` tag in index.html. In other words, the clicks will not accidentally fired on the scroll views defined in index.html.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PaperMonster!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3908). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3908)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by PaperMonster** [comment]
I tried to update the issue but stuck at this screen.
![screen shot 2015-06-09 at 8 06 59 pm](https://cloud.githubusercontent.com/assets/10735822/8058392/53af3f94-0ee3-11e5-9acb-12fd500e659a.png)
I already clicked Authorize button but I cannot go to the next step. My browser is Chrome 43.0.2357.81 on Mac OS X 10.10.3.

**Comment by sclearion** [comment]
this 'custom issue form' is so silly.

**Comment by PaperMonster** [comment]
Finally I was able to complete the custom issue form using my Android phone. Hope the form will work on my Mac soon.

**Comment by mhartington** [comment]
The custom issues form is meant to prevent duplicate issues and make sure we have all the necessary information when debugging. Nothing silly about that.

@PaperMonster, looking into the issue

**Comment by sclearion** [comment]
Well I guess the majority of ionic users are full of it. Sorry to offend, but you open an Issue via github but have to take additional steps, relinquish permissions to even get a response. Duplicate issues are going to happen unless EVERY ionic user was in communication about what issues are submitted already. Live  and persistent issue moderation prevents duplicate tickets, not some lazy bot message

**Comment by mhartington** [comment]
@PaperMonster tested this out on an iphone5 running ios8 without any issues. What device were you testing on?

**Comment by PaperMonster** [comment]
@mhartington I tested on Nexus 5 Android 5.1.1 with Crosswalk.

**Comment by PaperMonster** [comment]
Tested on four more devices, now without Crosswalk.
1. iPhone5 iOS 8.3 - No issue
2. iOS Simulator, iPhone6 iOS 8.3 - **Has issue**
3. Samsung Galaxy S Duos (GT-S7582L) Android 4.2.2 - **Has issue**
4. Acer Liquid C1 i110 Android 4.1.2 - **Has issue**

**Comment by mhartington** [comment]
Hmm, still why does it not effect the inline template? 
@perrygovier, maybe you want to take a look at this with all the changes in native scrolling?

**Comment by samuelsmal** [comment]
Any update on that? We face the same issue on both Android and iOS.

**Comment by biesbjerg** [comment]
I'm experiencing the same issue on an iPhone 6s, iOS 9.1.

**Comment by xiaody** [comment]
It seems that only the `ionic.view.Scroll`s instantized after `ionic.tap.register()` will encounter this issue, due to the wrong event listeners execution order. So an ugly workaround is to re-register tap listenters after every scrollView instantized, like:
```
your_module.run(function () {
  var originalScroll, rebindTap;
  originalScroll = ionic.views.Scroll;
  rebindTap = ionic.debounce(function () {
    var deregister = ionic.tap.register(document);
    deregister();
    ionic.tap.register(document);
  }, 100);
  ionic.views.Scroll = function(options) {
    rebindTap();
    return new originalScroll(options);
  };
});
```

**Comment by seasonstar** [comment]
Having the same issue on an iPhone 6, iOS 9.1.

**Comment by reapp3r** [comment]
+1

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by MmtBkn** [comment]
Having the same issue on an iPhone 6, iOS 10.
