### ISSUE TITLE
bug: Ionic version in Ionic Playground

### ISSUE THREAD

**Issue by ClemMakesApps** [driftyco/ionic#3912]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The default version of the ionic framework displayed in the Ionic Playground sample code is 1.0.0-rc.5 when it should be the latest stable 1.0.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
should be fixed now. 

http://play.ionic.io/
