### ISSUE TITLE
bug: Auto hiding header bar on keyboard input

### ISSUE THREAD

**Issue by meparashar** [driftyco/ionic#3914]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, I've consulted so many posts about keyboard hiding header bar and found the solution to be:

add a keyboard plugin cordova plugin add https://github.com/driftyco/ionic-plugins-keyboard.git using command line.
add cordova.plugins.Keyboard.disableScroll(true); to the javascript.
Following post also says so:
http://ionicframework.com/docs/api/page/keyboard/1

But when i do above steps, i get an error cordova is not defined. I added the disableScroll function to my controller.
The bar doesn't hide in browser, but on simulator or on actual device it does.
I'm sure it's something silly that i'm doing, but can please anybody lend some help. Thanks.

----------------------
http://forum.ionicframework.com/t/auto-hiding-header-bar-on-keyboard-input/26117</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @meparashar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3914). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3914)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by meparashar** [comment]
@mhartington I guess the processor is not even going inside if statement (checked that with console.log) and since cordova is not found, window.cordova is returning false. i checked the plugin, when i try to install it, the console returns the message that the plugin is already installed. 

the problem is that it's working in browser. only on simulator and device it doesn't work.

any suggestions are welcome.

**Comment by mhartington** [comment]
Are you referencing cordova.js inside of your index.html?

**Comment by meparashar** [comment]
yup. 

`<script src="cordova.js"></script>
<script src="cordova_plugins.js"></script>`

**Comment by mhartington** [comment]
woah, that shouldn't be like that. You shouldn't be referencing cordova_plugin.js in your index.html. Any way you could push this to github for me to look at?

**Comment by meparashar** [comment]
@mhartington not sure how to do that. Here's the public link to my ionic dummy project:
https://www.dropbox.com/s/8eu9sujycchrl49/fm%202.zip?dl=0 (you just need to build it)
if you face any difficulty.. lemme know.. i'll learn how to use github then and send the project if that's ok with you.

thanks a lot again for your help.

**Comment by meparashar** [comment]
@mhartington here's the git url:
https://github.com/meparashar/tempapp

**Comment by meparashar** [comment]
hi @mhartington finally i have resolved the issue. i uninstalled the keyboard plugin from the project, reinstalled it. removed the ios platform, and added it back. that finally solved it. thanks for all your help guiding me to find a solution. really appreciate it.
