### ISSUE TITLE
bug: A directory is never made with "ionic start"

### ISSUE THREAD

**Issue by pjrodrig** [driftyco/ionic#3916]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>No file directory is creating when running ionic start.

$ ionic start test blank
Creating Ionic app in folder c:\Users\Paul\workspace\test based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory 'c:\Users\Paul\workspace\test\config.xml'
There was an error finalizing the package.json file. { [Error: Cannot find module 'c:\Users\Paul\workspace\test\package.json'] code: 'MODULE_NOT_FOUND' }
 ✗ Unable to save settings file: Error: ENOENT, no such file or directory 'c:\Users\Paul\workspace\test\ionic.project'

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd test

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occured and has been reported to Ionic

Cannot read property 'statusCode' of undefined (CLI v1.5.0)

Your system information:

Cordova CLI: 5.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
OS: Windows 7 SP1
Node Version: v0.10.38</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#480

**Comment by mhartington** [comment]
Moved this to the ionic-cli repo, https://github.com/driftyco/ionic-cli/issues/480
