### ISSUE TITLE
bug: z-index is different on desktop vs mobile browser

### ISSUE THREAD

**Issue by dcsan** [driftyco/ionic#3922]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Elements render in a different z-index order based on the browser.

on desktop, or plain android chrome, z-index behaves as expected.

in ios simulator, and android webview (kitkat @4.4.2) the z-index is different.

events still get to the layers, but they don't display / get covered by other layers.</span>

<span is-issue-template></span>

**Comment by dcsan** [comment]
its a bit hard to describe so

on ios sim and android wrapper, i get this:

![image](https://cloud.githubusercontent.com/assets/514002/8116321/55b41216-1036-11e5-871d-277f6d12fae0.png)

on chrome desktop I get this:
![image](https://cloud.githubusercontent.com/assets/514002/8116341/63e6001a-1036-11e5-942c-31fec9a15854.png)

**Comment by dcsan** [comment]
the bug can be seen here, by clicking on the word "company" 
http://comicenglish.com/lessons/leak/start/start

I think this is somehow related to ionic using `scroll: hidden` but there being some bugs in how the browsers implement that, and layering issues. perhaps z-index fighting?

If someone has suggestions for workarounds or other things to look into that would be great.

**Comment by dcsan** [comment]
we fixed this by moving content out of the `menu-content` part of the DOM

eg Broken:
![13f3a120-1036-11e5-96b3-182097a13531](https://cloud.githubusercontent.com/assets/514002/8117297/ee491148-103b-11e5-90e6-77f17ca492de.png)

**Comment by dcsan** [comment]
fixed - @ top layer

![image](https://cloud.githubusercontent.com/assets/514002/8117326/20e9f216-103c-11e5-8344-2a8d9a499d56.png)

**Comment by Ionitron** [comment]
Greetings @dcsan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
