### ISSUE TITLE
bug: Modal windows open and then close suddenly

### ISSUE THREAD

**Issue by 3melectronicmonitoring** [driftyco/ionic#3923]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>My app was updated to the 1.0 release and I started having issues with modal windows opening on 4.4.2 android devices. 

I have a modal service that manages opening/closing/cleanup for modal windows and all modals are having this issue. The modal will open and then quickly close without any interaction from the user. You can see the open/close animations happen.

If I look at the console with dev tools for the device, I get an error that states "Uncaught TypeError: Cannot read property 'offsetX' of null". The error occurs in the ionSideMenuContent directive's content variable/object's setTranslateX() function:

        var content = {
          element: element[0],
          onDrag: function() {},
          endDrag: function() {},
          getTranslateX: function() {
            return $scope.sideMenuContentTranslateX || 0;
          },
          setTranslateX: ionic.animationFrameThrottle(function(amount) {
            var xTransform = content.offsetX + amount; // <- ERROR HERE!
            $element[0].style[ionic.CSS.TRANSFORM] = 'translate3d(' + xTransform + 'px,0,0)';
            $timeout(function() {
              $scope.sideMenuContentTranslateX = amount;
            });
          }),
          // ....
        }

Here's a codepen with an example of the usage of my modalService. 

http://codepen.io/anon/pen/XbgEpX

It works in the browser but the issue happens in android 4.4.2 so I'm not sure how helpful this will be.</span>

<span is-issue-template></span>

**Comment by 3melectronicmonitoring** [comment]
Should I report issues here or in the ionic forums to get help?

**Comment by mhartington** [comment]
I just tried this with an android 4.4.2 device and wasn't able to replicate the issue using the nightly builds. Do you have anymore information that you could provide?

**Comment by 3melectronicmonitoring** [comment]
Did you try it with 1.0.1 stable? The codepen was pointing to 1.0.0 when it was created because it was before 1.0.1 was released.

**Comment by mhartington** [comment]
Yes, I tried with both 1.0.1 and the nightly builds.

Mike Hartington

**Comment by DEllingsworth** [comment]
Just in case someone else runs into this, we solved our issue by setting backdropClickToClose = false.

For us, it was a sporadic problem that only happened on our Android 4.4.2 device and we could not get the error to happen in a simple test code.

Adding a bunch of debug statements found that the click event for opening the window was also getting called for closing the window and it seemed to think there was a click in the backdrop to close.

We traced it to this block of code in ionic-angular.js

      return $timeout(function() {
        if (!self._isShown) return;
        //After animating in, allow hide on backdrop click
        self.$el.on('click', function(e) {
          if (self.backdropClickToClose && e.target === self.el && stack.isHighest(self)) {
            self.hide();
          }
        });
      }, 400);

We suspect it has something to do with the animation speed and that 400ms delay.  Perhaps someone else will find more details.

**Comment by Ionitron** [comment]
Greetings @3melectronicmonitoring!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
