### ISSUE TITLE
bug: Side-menu repeats broken in 1.0.0 (work in Beta6) [codepen]

### ISSUE THREAD

**Issue by Grokling** [driftyco/ionic#3928]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/Grokling/pen/JdJZwY?editors=101

Pull the right sidemenu in, click the other tab. Both tabs should have content and headers. 

On the tab that shows items, click some of the items. Note that elements are duplicated incorrectly, and that multiple different items are displayed as active incorrectly when one is clicked.  Swap the bundle with 1.0.0 beta6 (commented out in the code) and all is working again.</span>

<span is-issue-template></span>

**Comment by Grokling** [comment]
This is confirmed as still broken in 1.0.1.

**Comment by wesleycho** [comment]
I did a bit of investigation out of curiosity, and this may potentially be a bug [here](https://github.com/driftyco/ionic/blob/master/js/angular/directive/tab.js#L167). In particular, this condition should also check for `!isSelected` in addition to the existing checks in the `else if`.

**Comment by mhartington** [comment]
I don't think this will be a UI-pattern that we will want to support. Ion-tabs is setup for global app navigation, not for side-menus.

If you want this kind of ui, you could make your own with ng-show/hide and using the tabs classes.
http://ionicframework.com/docs/components/#tabs
