### ISSUE TITLE
docs: Cannot GET /tutorials/customizing-ionic-with-sass/

### ISSUE THREAD

**Issue by jerrybk108** [driftyco/ionic#3929]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I can not access this page to get more extended color.</span>

<span is-issue-template></span>

**Comment by ClemMakesApps** [comment]
Is this the [page](http://ionicframework.com/docs/cli/sass.html) you were looking for?

**Comment by mhartington** [comment]
The page in question was removed from the site. Please use this page.
http://ionicframework.com/docs/cli/sass.html
