### ISSUE TITLE
bug: Cordova 5 compatibility

### ISSUE THREAD

**Issue by anasmithiam** [driftyco/ionic#3938]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am considering to migrate to Cordova 5 but I have doubts about compatibility issues with Ionic, ngCordova and cordova plugins

Is Ionic fully compatible with Cordova 5?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Ionic will work with Cordova 5.0.
