### ISSUE TITLE
docs: Can't create a ionic starter from complex-lists

### ISSUE THREAD

**Issue by murilolobato** [driftyco/ionic#3939]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I run the CLI Command:

"ionic templates"

I see the complex-lists template.

But when I run

ionic start myApp complex-lists

I get a blank starter.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The complex list starter hasn't been done yet unfortunately. Still a work in progress!
