### ISSUE TITLE
feat: Add plugin to a specific platform

### ISSUE THREAD

**Issue by giorgiofellipe** [driftyco/ionic#3942]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Could we have an option to specify the platform which the plugin will be added.

For example:
Currently I'm using to advertise:
- AdMob on Android
- iAd on iOS

iAd only works for iOS and it gets compiled only to this platform, it's ok!
But, AdMob is a cross platform plugin and got compiled to iOS too, I really don't need this library on iOS. And it's also causing my apps to be refused on appstore

What I could do at the moment:
1. Remove the plugin before compiling to iOS and add before compiling to Android. It's weird and painful.
or
2. Edit ios.json on plugins folder and remove admob's reference, but it's weird too.</span>

<span is-issue-template></span>

**Comment by saniyusuf** [comment]
this is more of a Cordova feature. Its simply the way it currently works

**Comment by giorgiofellipe** [comment]
@saniyusuf Hm, you're right, but there could be an Ionic CLI override with this feature, what do you think?

**Comment by giorgiofellipe** [comment]
Taking myself into a deep search found something helpful that probably will save me from headaches. 
http://docs.phonegap.com/en/edge/plugin_ref_plugman.md.html
