### ISSUE TITLE
bug: Date based inputs behave poorly with focus cloning

### ISSUE THREAD

**Issue by jeremyrussell** [driftyco/ionic#3944]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When an input field is given focus, it is cloned by ionic and moved off screen, from what I have read this feature was introduced to resolve cursor issues.  This functionality exhibits a weird behaviour for date based inputs (i.e. date, time, datetime-local and month), in that when the input has focus and the page is scrolled the value of the input is not displayed.  I'm not sure why this is, however I found that by simply excluding date based inputs from the cloning process, my problem was resolved.

Here is my simple code change: https://github.com/driftyco/ionic/compare/master...jeremyrussell:cloned-input-focus-scroll-issue

I have also uploaded a video to youtube to illustrate the issue:
https://youtu.be/3vFXEEDXiGg</span>

And, here's a codepen: http://codepen.io/jeremyrussell/pen/bdreGK
Note, however that the app needs to be run as a hybrid app to reproduce the error
<span is-issue-template></span>

**Comment by mhartington** [comment]
Should be fixed in d3c3e8c7b049acc731d537578eadb4fd00769aa9
