### ISSUE TITLE
bug: Android 5.0 / Pull-to-refresh or infinite scroll does not work with ng-include and native scrolling

### ISSUE THREAD

**Issue by mica16** [driftyco/ionic#3945]
Using Native Scrolling.

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>```<ion-content >
        <ion-refresher 
                       pulling-text="Tirer pour rafraîchir..."
                       on-refresh="doRefresh()">
        </ion-refresher>
        <div ng-include="'list-content.tpl.html'"></div> 
</ion-content>```

This well works, pull-to-refresh works.

However, when including ```ion-refresher``` into the ng-include:
```
<ion-content >
        <div ng-include="'list-content.tpl.html'"></div>
</ion-content>
```

Pull-to-refresh does not work at all. No icon, nothing. 

Content of the list-content.tpl.html: 

```
<div ng-show="!loading && !stateIsLoading">
    <!--<ion-refresher 
                       pulling-text="Tirer pour rafraîchir..."
                       on-refresh="doRefresh()">
     </ion-refresher>  does not work when put here --> 
    <ion-list>
        <ion-item collection-repeat="item in items track by item.id"
                  item-width="'100%'"
                  class="item" ng-click="show(item.id)">
            <div class="item-icon-right">
                <div class="row">
                    <!-- simple content here -->
        </ion-item>
    </ion-list>
</div>

```

Tested on release 1.0.0 and last nightly build.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mica16!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3945). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3945)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mica16** [comment]
Probably because of the child scope spawned by ng-include, creating a conflict.

**Comment by mhartington** [comment]
Does it work without the ng-include?

**Comment by mica16** [comment]
Yes, works perfectly without ng-include.

**Comment by mhartington** [comment]
Then don't use ng-includes? If it works fine inlining the content, then I don't think there needs to be an extra step to use an ng-include.

**Comment by mica16** [comment]
When you have two templates needing the same list content, it should be a good practice to benefit of ng-include to avoid duplicating code.

**Comment by mohamed-ahmed** [comment]
Why was this closed? I'm having the same issue. If you have several views which use a common component then why wouldn't you want to use ng-include? What better method do you suggest? @mhartington

**Comment by jacquesdev** [comment]
I realise this is a super old issue (and closed), but I had the same issue, and I realised the solution is to move the refresher to the same level as the content div. So basically the include should be:

```
 <ion-refresher 
                       pulling-text="Tirer pour rafraîchir..."
                       on-refresh="doRefresh()">
</ion-refresher>


<div ng-show="!loading && !stateIsLoading">
    <ion-list>
        <ion-item collection-repeat="item in items track by item.id"
                  item-width="'100%'"
                  class="item" ng-click="show(item.id)">
            <div class="item-icon-right">
                <div class="row">
                    <!-- simple content here -->
        </ion-item>
    </ion-list>
</div>

```
