### ISSUE TITLE
Feature: Ability to hide tab bar

### ISSUE THREAD

**Issue by sicsol** [driftyco/ionic#395]
There might be a case where someone would like to hide the tab bar.

One instance i can think of is when the user focuses on any input element the screen shrinks to accommodate the keyboard and this causes the tab bar to be docked at the top of the keyboard.

**Comment by markusila** [comment]
Is it possible to hide my tabs navigation in some views?

**Comment by kekobin** [comment]
you can try this solution:
$rootScope.$on('$ionicView.beforeEnter', function () {
            var stateName = $state.current.name;
            if (stateName === 'tab.order' || stateName === 'tab.contact' || stateName === 'tab.account' || stateName === 'tab.setting') {
                $rootScope.hideTabs = false;
            } else {
                $rootScope.hideTabs = true;
            }
        });

just add a listener to $ionicView.beforeEnter, and change the value of hideTabs which show/hide tabs.

**Comment by krk324** [comment]
kekobin: where do I place this code?

**Comment by php-engineer** [comment]
@kekobin Greate, your solution works perfect.

@krk324 
```
<ion-tabs class="tabs-stable tabs-top tabs-icon-only tabs-color-positive" ng-controller="TabsCtrl" ng-class="{'tabs-item-hide': hideTabs}">
    // ... your tabs here
</ion-tabs>
```

```
'use strict';

angular.module('myApp.controllers')

	.controller('TabsCtrl', function($scope, $rootScope, $state) {
		$rootScope.$on('$ionicView.beforeEnter', function() {

			$rootScope.hideTabs = false;

			if ($state.current.name === 'tabs.events-create') {
				$rootScope.hideTabs = true;
			}
		});
	});
```

Maybe it helps you.

**Comment by Paul-Isache** [comment]
@php-engineer Thanks! It's a great solution!

**Comment by georgschlenkhoff** [comment]
@kekobin: impressed. works like charm!

**Comment by nemo1112** [comment]
Thanks. work great for me.

**Comment by michael8090** [comment]
@kekobin @php-engineer The approach is broken when we have nested views. Say we have state "tab.a.b", while "a" the one at which we want to hide the tabs bar and "b" should inherit the tabs bar status.  "a" enters first and sets the tag to true, then "b" enters, clearing the state....

We need a way to inspect the states and only the states that our app traverses during its life cycle so that we can prevent the states that we're not interested from changing the tag. At last I end up with adding a listener to the "$stateChangeStart" event on $rootScope, as below:

		$rootScope.$on('$stateChangeStart',
			function (event, toState) {
				$rootScope.hideTabs = toState.data && toState.data.hideTabsBar;
			});

Every state that requires hiding the tabs bar has a attached "data.hideTabsBar" property with true value.

**Comment by lucasfalanga** [comment]
@php-engineer or @kekobin you guys please can help me? I tryied this solution but the event $ionicView.beforeEnter is not fired. Please help. 

Thanks in advance!

**Comment by lucasfalanga** [comment]
@Paul-Isache or @georgschlenkhoff or @nemo1112 your help will be welcome too! :)

**Comment by xiaofuai** [comment]
@php-engineer great job,  thanks a lot.

**Comment by adamelevate** [comment]
@php-engineer and @kekobin , 100 points to Gryffindor.

**Comment by keyvanfatehi** [comment]
Thank you @php-engineer and @kekobin - works great

**Comment by LTroya** [comment]
Thank you @php-engineer and @kekobin. It helps me a lot!

**Comment by bodinaren** [comment]
I'm using the same solution as above. I'm still curious however why $ionicTabDelegate doesn't have a .show([show]) function to toggle visibility. Seems like a much easier approach.

**Comment by joevo2** [comment]
Does the ionic tab have animation? can it hide gracefully? like lowering down or something :smile: @steefaan solution works great :smile:

**Comment by TakayukiSakai** [comment]
I'm with @bodinaren. If we can use $ionicTabDelegate.show(boolean) function, managing a tab bar would be much easier. 

By the way, though @steefaan 's solution works well, a solution which I found at a stackoverflow page below would be more "Angular way."
http://stackoverflow.com/questions/23991852/how-do-i-hide-the-tabs-in-ionic-framework

```
////// tabs.html
<ion-tabs ng-class="{'tabs-item-hide': hideTabs}">
    // --> your tabs here
</ion-tabs>

////// somewhere_you_wanna_hide_tabbar.html
<ion-view hide-tabs>
  // --> your contents
</ion-view>

////// directives.js
.directive('hideTabs', function($rootScope) {
    return {
        restrict: 'A',
        link: function($scope, $el) {
            $rootScope.hideTabs = true;
            $scope.$on('$destroy', function() {
                $rootScope.hideTabs = false;
            });
        }
    };
});
```

I hope this helps you guys :)

**Comment by bodinaren** [comment]
TakayukiSakai: I like it. I'd suggest an improvement to that code to handle caching tho:
```js
.directive('hideTabs', function($rootScope) {
  return {
    restrict: 'A',
    link: function($scope, $el) {
      $scope.$parent.$on("$ionicView.enter", function () {
        $rootScope.hideTabs = true;
      });
      $scope.$parent.$on("$ionicView.leave", function () {
        $rootScope.hideTabs = false;
      });
    }
  };
})
```

I also played around with adding it to the $ionicTabsDelegate and came up with this. What do you guys think? https://github.com/bodinaren/ionic/commit/d555f694e3b4693018e0237d0debc0bfeb1d06f3

**Comment by TakayukiSakai** [comment]
@bodinaren: Thank you for giving your solution.
But unfortunately, your code doesn't work in ionic official sample with tab navigations. You might able to see how come it doesn't work, in my CodePen page below.
http://codepen.io/TakayukiSakai/pen/yNxQYZ?editors=101

The chat detail page's template has "hide-tabs" attribute. So it should hide the tab bar, but it doesn't.

Apparently, both $ionicView.enter and $ionicView.leave are called every time you enter the chat detail page (you can see it on your browser console).

**Comment by TakayukiSakai** [comment]
@bodinaren 
I made a pull request (#4133) in which I implemented $ionicTabsDelegate.showTabBar(bool) method.

How do you guys think about this method?

**Comment by bodinaren** [comment]
@TakayukiSakai Yeah, just remove the $parent. Guess I added it wrong when I tried it. The updated code works now.

Also, about your fork. It looks a lot like my fork I just linked in my last post, but mine had more separation of concerns and I think more like the rest of Ionic works (with also returning current status). Also your docs is wrong. Here's mine (I didn't make a PR yet): https://github.com/bodinaren/ionic/commit/d555f694e3b4693018e0237d0debc0bfeb1d06f3

**Comment by TakayukiSakai** [comment]
@bodinaren: Great! Your code works pretty well after removing $parent.

Sorry I didn't notice your commit posted on your comment. I checked your commit just now, and I thought it worths making PR.

**Comment by zhangzhenqiang** [comment]
@TakayukiSakai Thanks a lot,great solution!

**Comment by JungmoKang** [comment]
1

**Comment by Miyada2000** [comment]
@TakayukiSakai san great solution, I´ve spent the whole afternoon trying to figure out a solution. Thanks for sharing.

**Comment by WilsonFpz** [comment]
@TakayukiSakai 
sir, I had fork you codepen, and add hide-tabs directive to 'tab.chats' status,
but the tabs show when entering to 'tab.chat-detail'. really weird ~_~"
http://codepen.io/WilsonFpz/pen/megwxR?editors=101
Could you help on it ? Thanks!

**Comment by elroyshilling** [comment]
CSS override worked for me, posted my answer on [stackoverflow](http://stackoverflow.com/a/33923323/2842657)

**Comment by mohamed-ahmed** [comment]
@ajoslin have you actually be able to use **hide-tabs**. If so how is it used? I see a lot of people asking about it here and not really any answers.

**Comment by mlynch** [comment]
This feature was recently added for 1.2: https://github.com/driftyco/ionic/commit/7dd620da8f8335bc340e8e49eda32b72856b7741#diff-8abac3f87d0ad8499e65128ece9dfd71R60

**Comment by mohamed-ahmed** [comment]
Thanks for the update @mlynch

**Comment by pietromarrone** [comment]
I forked the @TakayukiSakai  codepen, using the ionic 1.3.0 version with the new `$ionicTabsDelegate.showBar `method, the solution can be more elegant.
It remove indeed the `ng-class="{'tabs-item-hide': $root.hideTabs}` from the **ion-tab**
Here the codepen: http://codepen.io/pietromarrone/pen/vGPOWQ?editors=101

**Comment by bklups** [comment]
@pietromarrone I try your codepen, but suppose we have a third level of navigation (after `chat-detail.html`), we'll call it `chat-detail-more.html`. Your code works fine, but if we use back button to go back to `chat-detail.html`, tabs bar comes back
Any idea to hide tabs bar in this case ?

**Comment by pietromarrone** [comment]
Actually I just extended another sample and both has that problem. No I
didn't fine a way, but it is something regarding the async of state entered
and exited of previous page.

Il Ven 5 Ago 2016 18:17 Benjamin Klups <notifications@github.com> ha
scritto:

**Comment by Hanslen** [comment]
@ajoslin Thanks a lot!

**Comment by Jatapiaro** [comment]
If your problem is on android, this could help you. In the ionic config.xml, add the following lines in the platform name="android" tag.

    <platform name="android"> 
      <edit-config file="AndroidManifest.xml" mode="merge"    target="/manifest/application/activity"> <activity android:windowSoftInputMode="adjustPan" /></edit-config>
      ...the rest of the android configs...
    </platform>

This will prevent the keyboard to push up everything and simple overlay the keyboard on the content. So the behaviour will be the same or similar to the ios keyboard
