### ISSUE TITLE
bug: http://codepen.io/ionic/pen/mFygh

### ISSUE THREAD

**Issue by webueye** [driftyco/ionic#3973]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://codepen.io/ionic/pen/mFygh
i can't see, have javascript error, please check it.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Seems that demo is too much for codepen to handle. 
Here are some of the demos for collection repeat

http://ionicframework.com/docs/api/directive/collectionRepeat/
