### ISSUE TITLE
bug: Ion-tabs possible bug when switching the tabs

### ISSUE THREAD

**Issue by alfons12** [driftyco/ionic#4006]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.3</span>  <span ionic-webview>webview</span>

<span ionic-description>Bug is described here: http://forum.ionicframework.com/t/ion-tabs-possible-bug-when-switching-the-tabs/26906

Worked fine on beta14, now on 1.0.0</span>

<span is-issue-template></span>

**Comment by danielmilner** [comment]
Are you talking about the icon horizontally repeating for a split second during the tab transition? It's hard to tell from the screenshot. If so, I'm experiencing the same thing.

**Comment by danielmilner** [comment]
Oops, I meant vertically repeating.

**Comment by markahon** [comment]
@danielmilner I experienced the same thing with two icons showing for a split second when having different icons for tab active/inactive states.

Environment: ionic `v1.1.0` on iOS 9.

My workaround using CSS:
```
/* For a moment there's two <i>-elements inside tab-item, don't allow both to be shown. */
.tabs .tab-item i:nth-of-type(2) {
  display: none;
}
```

**Comment by simplesmiler** [comment]
@markahon regarding iOS please see https://github.com/driftyco/ionic/issues/4395, it will most likely fix it for you.

**Comment by danielmilner** [comment]
The patches on this page fix the issue:
http://blog.ionic.io/preparing-for-ios-9/

**Comment by markahon** [comment]
Duh, I had read that blog post and was aware of the iOS 9 bugs, but I also had totally forgotten to include that Igor's patch! Thanks @simplesmiler and @danielmilner.

**Comment by mhartington** [comment]
Closing since this was related to the ios9 patch.

**Comment by markahon** [comment]
This issue was closed, but commenting still. Even after including `ngIOS9UIWebViewPatch`-module the tab icons keep flickering. Might be that my views are somehow 'heavy', so I still have to keep the CSS-hack in to avoid the flicker.

**Comment by edmondchui** [comment]
@markahon Thanks for the fix. It works well on browser. I need to use

```css
display: none !important;
```
to make it work on iOS 9 as well.
