### ISSUE TITLE
bug: Tapping tab you are already on breaks app/caching

### ISSUE THREAD

**Issue by ronaldjeremy** [driftyco/ionic#4013]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here is the codepen illustrating the issues described below:  http://codepen.io/ronaldjeremy/pen/NqGzoz/ 

Here are the steps to show the first bug:

1.) Open the Codepen
2.) click Tab2.
3.) click Tab1
4.) click Tab2
5.) click Tab2 again
6.) click Page2. You will see on this step, a page transition starts and then abruptly stops? Then your are stuck in this state -- clicking Page2 then does nothing?

For the second bug, there appears to be a cache clearing bug in ionic when you have a view more than 1 level deep, and you hit a tab to bring you back to the first level. In the codepen, we setup an alert on page2 to show when the controller gets called.

If you tap Tab2-->Page2, you get an alert. Then if you tap Tab2 again it brings you back to Page1 since you are already on Tab2 (this is good), and tapping Page2 will give you another alert.

Now for the scenario showing the bug:

Tap Tab2-->Page2-->Page3. Now tap Tab2 (it brings you back to Page1 like the previous example). But now if you tap Page2, there is NO alert. Ionic is caching that view when it shouldn't be.

Of interest is the bug does not occur if you use the history back buttons. It only happens when you are 2+ levels deep in tab, and hit that tab again to bring you to the top level of the tab.

If you are on tab2 and navigate to a child view, then click tab1, then tab2, it is going to show the "cached" child view on tab2. This is good and is the expected behavior.

However if you are on tab2, navigate to a child view, then click tab2 (which you are already on), it brings you to the topmost view of that tab. That is also a good thing. But at that point, ionic should clear out the cache of everything on that specific tab, but that isn't happening. 

It looks like this bug ties in with the first in that they both have one thing in common -- tapping a tab that you are already on somehow breaks history/caching in that tab.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ronaldjeremy!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by iamchairs** [comment]
This is still an issue. The only solution is the use `cache: false` or to hack it. I don't want to use either. Please clear abstract state cache when navigating to a parent.
