### ISSUE TITLE
bug: ionic-contents with native scrolling don't maintain scroll position

### ISSUE THREAD

**Issue by jskrzypek** [driftyco/ionic#4016]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Likely related to #3256 

Here is a codepen to demonstrate the bug:
http://codepen.io/jskrzypek/pen/XbVQEm

Scroll down in the native-scrolling (i.e. the one with `overflow-scroll="true"`) list, then switch to the ionic-scrolling list and do the same.

When you switch back to the native list you are jumped back up to "Native Scroll - Item 0", the top of the list. When you switch back again to the ionic list you are still at the scroll position you scrolled to before.

We think this is coming from the `$location` decorator. https://github.com/driftyco/ionic/blob/master/js/angular/service/decorators/location.js

The native scroller is passing an empty string (`''`) in `value` to `$location.hash(value)`, but `isDefined('')` returns true, triggering the `if` even when no `hash` value is set on the `location` and setting `scroll.scrollTop = 0`, thus causing the scrollview to lose it's scroll position.

Testing this by overriding the decorator, we see that the bug is no longer happening.
Here is a different codepen to demonstrate the fix:
http://codepen.io/jskrzypek/pen/GJQgEO</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jskrzypek!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4016). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4016)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jskrzypek** [comment]
Fix submitted as a PR.

**Comment by onigetoc** [comment]
You may add scrollfix to make the head and footer to not bounce on scroll.
https://github.com/joelambert/ScrollFix

i used it in my project here. (Try in IOS)
go to tab Scroll.
http://scripts.toolurl.com/1-Mobile/bootapps-05/GC-Bootapps-Android.html

When it stop scrolling, it moove the overflow to 1 pixel to scroll again without bouncing the head.

**Comment by jskrzypek** [comment]
Thanks, @onigetoc, I'll check it out, but your comment doesn't really address the issue I mentioned. 

Try out the pens I linked to, this bug seems to happen on all platforms.

**Comment by kowach** [comment]
Scroll position is lost in both cases if cache is off:

    .state('tabs.ionic', {
      url: '/ionic',
      cache:false,

Is this a bug or a feature?

**Comment by jskrzypek** [comment]
@kowach what platform are you testing on? The code pen in your browser?

I think the ionic caching is what is preserving your scroll position in the first place. As far as I'm aware that's not something that works by default in angular without some configuration.

**Comment by onigetoc** [comment]
@jskrzypek this was a suggestion because sometime, long page with images the scroll is not fluid. 
What a read is that  native css overscroll touch work on 99% of IOS users.
and 50% on Android. 
may looking at Android version to use overscroll touch.

**Comment by jskrzypek** [comment]
@onigetoc, sure, it's not a fix for the issue I mentioned, but for anyone having trouble with long page scrolling on mobile it may help.

**Comment by mhartington** [comment]
Fixed in b42655614cf2b193187b8f486f2f747a681751ab
