### ISSUE TITLE
bug: Unable to scroll vertically when i use ion-scroll

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [driftyco/ionic#4027]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>In a page i have some content, horizontally scrollable section and some content again. The issue is, if i tap and scroll on the content(not the horizontally scrollable section), then i am able to scroll vertically. But if i tap and scroll on the horizontal scrolling section, i am unable to scroll vertically. `ion-scroll direction=x` is blocking the vertical scroll. If the horizontal section takes almost full height of the screen, then the user is unable to scroll in vertical direction, which is blocking the scroll. If i remove `ion-scroll` and use custom css `overflow-x : scroll`, then i am able to scroll vertically by tapping on the horizontally scrollable section. But this is just working in system browser, but not in the mobile.

Please have a look at the code pen
http://codepen.io/rajeshwarpatlolla/pen/EjQyOJ

Steps to follow
1) Click/tap beside 'heading' and try to drag/move up and down. 
2) Scroll down, and click/tap on the horizontally scrollable section and try to drag/move up and down. You wont be able to move vertically.
3) If the horizontally scrollable section occupiers whole screen of the mobile, then the user cannot see the above and below this horizontally scrollable section.</span>

<span is-issue-template></span>

**Comment by simplesmiler** [comment]
Similar to https://github.com/driftyco/ionic/issues/3789

**Comment by Ionitron** [comment]
Greetings @rajeshwarpatlolla!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
