### ISSUE TITLE
bug: collection-repeat wrongly calculate render range

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#4034]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When the list is just initialized before rended by the bowser. It will render all the data into the DOM. Because the following believes all the vertical rows are visible.  (scrollValue = 0,scrollValueEnd =0) 

view.updateRenderRange(scrollValue, scrollValueEnd);

This issue is caused by the flag isGridView is wrongly set to TRUE!!!

          // We say it's a grid view if we're either dynamic or not 100% width
         var isGridView = isVertical ?
           (widthData.dynamic || widthData.value !== scrollView.__clientWidth) :
      (heightData.dynamic || heightData.value !== scrollView.__clientHeight);

The value for the  widthData.value is 'undefined', the scrollView.__clientWidth is 0.

Since it is grid, the function updateRenderRange() will believe all the data is in the single row and all are visible.

                  primaryPos: 0
                  primarySize: 72
                  rowPrimarySize: 72
                  rowStartIndex: 0
                  secondaryPos: 0
                  secondarySize: 0</span>

<span is-issue-template></span>

**Comment by dreamershl** [comment]
![image](https://cloud.githubusercontent.com/assets/1271739/8505865/cd18b646-2228-11e5-9250-f20cdd78db7f.png)




Add the following check, will avoid this issue

           if(scrollValue === 0 && scrollValueEnd === 0)
            {
                     renderStartIndex = 0;
                     renderEndIndex = -1;
             }
            else
            {
                    view.updateRenderRange(scrollValue, scrollValueEnd);
            }

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
