### ISSUE TITLE
Add clear ("x") button for resetting input fields

### ISSUE THREAD

**Issue by asgeo1** [driftyco/ionic#405]
It would be cool if Ionic had a "clear" / "x" button that could appear inside inputs. I suppose it could be implemented as an AngularJS directive.

Kind of like how jQuery Mobile has a `data-clear-btn="true"` attribute that can be applied to input elements:

http://demos.jquerymobile.com/1.4.0/textinput/#Text

Any plans for this?

**Comment by billraythree** [comment]
This is a directive that you can use to wrap an input that adds the click to clear icon, plus clear on ESC key. It's for bootstrap, but you can easily adapt for ionicons.

<div clearinput><input...></div>

or

<div clearinput icon="glyphicon-remove"><input...></div>

https://jsfiddle.net/raythree/ash6rqd2/13/

Cheers,
Bill

**Comment by EdgarArguelles** [comment]
Look at this

http://plnkr.co/edit/Dje0l1?p=preview

**Comment by jesseplymale** [comment]
Here's a good discussion that relates to this: http://forum.ionicframework.com/t/cannot-tap-click-a-clear-search-icon-inside-an-input-label/4237/8

Use the same technique: Either rename the enclosing <label class="item-input-wrapper> to be a <div>, or use the "on-touch" directive instead of "ng-click".

**Comment by yazan-boshmaf-hs** [comment]
+1

Any updates on this?

**Comment by perrygovier** [comment]
We wont be adding this to Ionic core, but it'd be a welcome addition to market.ionic.io

**Comment by yazan-boshmaf-hs** [comment]
Thanks, @perrygovier.

**Comment by salqadri** [comment]
@perrygovier. Why isn't the X button going to be added to ionic? I'm a noob to this cordava/ionic world and I wasted multiple days and continue to waste more time on trying to get my text field to have an x button that works when you start typing. Makes me want to switch back to native development.

**Comment by VinceOPS** [comment]
@salqadri Hi Salqadri, have a look at my directive, based on @udfalkso's work:
https://github.com/VinceOPS/ionic-clearable-input

**Comment by cosnofski** [comment]
@salqadri - This works for me. X button appears based on angular's ng-if directive. Input get's focus after tapping the X button thanks to ionic's on-touch directive. It also works if you use a div instead of a label tag.

```html

<label class="item-input-wrapper">

   <i class="icon ion-ios-search-strong placeholder-icon"></i>

   <input type="search"
          placeholder="Search"
          ng-model="search.string">

    <a ng-if="search.string != ''" 
       on-touch="search.string=''">

       <i class="icon ion-ios-close placeholder-icon"></i>

    </a>

</label>

```

**Comment by tmdevde** [comment]
@cosnofski awesome thank you!

**Comment by HariharanIT** [comment]
@cosnofski thank you

**Comment by abcd-ca** [comment]
@cosnofski Thanks! Made it into a directive. Can be used like,

`<search-bar ng-model="search"></search-bar>`

controller would contain,

`let search = {text:""};`

directive:

```
angular.module('foo')
.directive('searchBar', [
	() => {
	return {
		scope: {
			ngModel: '='
		},
		require: ['?ngModel'],
		restrict: 'E',
		replace: true,
		template: `<div class="item item-input-inset">
						<label class="item-input-wrapper">
							<i class="icon ion-ios-search-strong placeholder-icon"></i>
							<input type="search"
							       placeholder="Search"
							       ng-model="ngModel.text">

							<a ng-if="ngModel.text != ''"
							   on-touch="ngModel.text=''">

								<i class="icon ion-ios-close placeholder-icon"></i>
							</a>
						</label>
					</div>
					`,

		link: (scope, element, attrs)=>{

		}
	};
}])
```

**Comment by sonicwong** [comment]
I wrote a directive for ionic input field. Free feel to give any suggestion.
https://github.com/sonicwong/ionic-input-clearable
