### ISSUE TITLE
feat: Ios build overwriting xCode settings

### ISSUE THREAD

**Issue by sergiufalcusan** [driftyco/ionic#4059]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have tried different methods to avoid overwriting xcode settings, like copy/pasting www folder from root to production (platforms/ios/www). Is there any way to not overwrite xCode settings after running "ionic build ios" ? eg. I am loosing provisioning profile settings. Can you please add more documentation for iOS ?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
What type of settings are you trying to change. The build process is all from cordova so they would need to change things there

**Comment by smotru** [comment]
i have to setup all xcode settings everytime when I do ionic build ios such as provisioning profiles , icons, app version etc

**Comment by mhartington** [comment]
App version and icons can all be managed through cordova's config.xml. Changes there will get passed to the native iOS project at build time. As for handling provision profiles, do you mean for debugging and production?

**Comment by smotru** [comment]
yes, when trying to deploy to my ipad it requires me to add provisioning profiles.

**Comment by mhartington** [comment]
Have you tried running `ionic run ios --device`? This should handle the profiles correctly, as long as they are loaded in xcode

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue! Since it has been a little while since there was any activity on this issue i will be closing it. Please feel free to reply if you are still experiencing this issue!
