### ISSUE TITLE
bug: isHighest causing problems with consecutive popups in v1.0.1

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [driftyco/ionic#4061]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello!

I'm facing a problem related to consecutive popups. You can simulate it through:
http://codepen.io/anon/pen/XbqWwB

Click on the button Test,then click save, the second popup will open, click save again. Now, try to click on the button Test again. It seems only the highest popup got closed, and the first popup remains in the DOM, but invisible. 

This issue didn't happen in 1.0.0

Here is the problem line:
https://github.com/driftyco/ionic/commit/8095b125152e85ba6f82a4350b77eef830dd5b29#diff-e91afb9d089c4a023017992e5bf71f3eR45574

I appreciate any attention over this issue. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @raphaelduartepinheiro!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4061). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4061)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vsubramanian** [comment]
:+1:

**Comment by mhartington** [comment]
So ionic is just getting confused, trying to show the second popup while also trying to hide the first one. 
You could do this 

http://codepen.io/mhartington/pen/zGeJog?editors=001

Or this 

http://codepen.io/mhartington/pen/JdxaOG?editors=001

**Comment by raphaelduartepinheiro** [comment]
Okay, tested on v1.0.1, and it works using this approach.

I'd suggest to include an explanation in $ionicPopup documentation. Something like:

**onTap** callback should not call other popup instance, if necessary, it must be called inside **then** block.

**Comment by mhartington** [comment]
Will make sure it gets in there. Thanks

**Comment by olliebennett** [comment]
We have experienced the above problem in a couple of situations, not all with valid workarounds:

- One of our custom `$httpProvider.interceptors` detects 500 errors and displays an `$ionicPopup.alert` informing user that a "Server Error" occurred. In some cases, multiple API requests may return 500s in quick succession. In such cases, only one of the popups can be closed. Our workaround is to use `$ionicActionSheet.show` and store the returned `hideActionSheet` function (globally), to be called before creating any new `$ionicActionSheet`. From a design/UI perspective, this isn't a valid "workaround".

- We display an `$ionicPopup.confirm` dialogue when a date input field changes (with debounce). There are situations where the (debounced) change occurs while an existing confirm dialogue is displayed. (Our situation is slightly more complex than this - I can share code if required). In this case, there is also no way to hide the second popup. 

Do you think we could re-open this issue, or else I could create a separate one? It appears to me that the recent changes introduce various openings for race conditions, not all of which can be averted.

Links: [Comparison of 1.0.0 with 1.0.1](https://github.com/driftyco/ionic/compare/1.0.0...1.0.1) and the "guilty" commit: https://github.com/driftyco/ionic/commit/bcfe210afdd1468bfd19810858f08f94242e5a7a

**Comment by zarko-tg** [comment]
For whoever might be looking for a proper way to show (two) popups one after another, you could have a look at this demo as well: http://codepen.io/zarko/full/jPJqeb/
And yes, at least the docs should say something about the limitation as probably most developers are not even aware of this change that might come around to bite them.
