### ISSUE TITLE
bug: Scroll bars are gone

### ISSUE THREAD

**Issue by animungo** [driftyco/ionic#4065]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>The scroll bars are gone, when using native scrolling.</span>

<span is-issue-template></span>

**Comment by animungo** [comment]
probably related to #4066

**Comment by mhartington** [comment]
Confirmed.

**Comment by zarko-tg** [comment]
Any news?

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
