### ISSUE TITLE
bug: On button/link... a yellow shadow after clicked

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#4076]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I try to fix a problem, when i click on a buton or a link in my app, just after the click a yellow shadow is visible. But i don't want it! 
How can hi delete it? In the css in js? 

Thanks!</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you provide a codepen so we can test this?

**Comment by LeoLR** [comment]
I've this problem only on my device, when i run it on my browser i've no problem.

**Comment by mhartington** [comment]
We can test codepens on a device.

**Comment by LeoLR** [comment]
http://codepen.io/anon/pen/KpxMmL
I don't know if that make the same problem on device.

**Comment by mhartington** [comment]
Just tried this on a 4.2 device. No yellow shadow. Is there anymore info you could provide?

**Comment by LeoLR** [comment]
My device is on 4.2 and i still have this problem, i try to change the button.activated in my css but that doesn't work...

**Comment by mhartington** [comment]
Not sure what else I can do. I'm not able to replicate this using the example code.

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
