### ISSUE TITLE
docs: dead links in dropdown

### ISSUE THREAD

**Issue by mcbyrne** [driftyco/ionic#4087]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Go to 
http://ionicframework.com/docs/

In dropdown header from entering "scope" into the search bar

Click on 
Intro app tutorial link:
http://ionicframework.com/tutorials/intro-tutorial/
or
Fading header effect with ionic:
http://ionicframework.com/tutorials/fade-status-bar/

but returned a page:
Cannot GET /tutorials/intro-tutorial/</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
These pages were removed as they were part of an old layout. 
Will fix the search and remove the reference.
