### ISSUE TITLE
docs: Docs page shows vertical sliders but I can't find

### ISSUE THREAD

**Issue by mjaggard** [driftyco/ionic#4088]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This page:
http://ionicframework.com/docs/

Shows vertical sliders on the "Javascript" icon but I can't find any details on how to create vertical sliders in the documentation.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The icon is just for illustration, there is not vertical slider in ionic.
