### ISSUE TITLE
docs: ionic start complex-list results in blank project

### ISSUE THREAD

**Issue by gpolyn** [driftyco/ionic#4092]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I thought the result of the command 

'ionic start complexList complex-list'

would be different than

'ionic start blankProject blank'</span>

<span is-issue-template></span>

**Comment by gregory-yet** [comment]
There is nothing in the repo : https://github.com/driftyco/ionic-starter-complex-list

**Comment by gpolyn** [comment]
It shows up in the ionic templates command
