### ISSUE TITLE
bug: Tabs content under tabs

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#4098]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I've a problem with the content of a tab, i've use this codePen(http://codepen.io/calendee/pen/JdtuG?editors=101) for made my tabs and it's the same code but when i try this on my app my text is under the tab... 

http://img11.hostingpics.net/pics/284422templatestabstabhostshtmlwwwBrackets.jpg

If anyone have a idea! 

Thank's</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The code you are referencing in the pen is really old, 0.9.27. Ionic is on 1.0.1 now, please update your codepen accordingly. 
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md
