### ISSUE TITLE
bug: ionic cli add does not find bower packages

### ISSUE THREAD

**Issue by gpolyn** [driftyco/ionic#4107]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Components that a 'bower search' can find sometimes result in the following error message after executing 'ionic add'

Failed to find the bower component [...]
Are you sure it exists? (CLI v1.6.1)</span>

<span is-issue-template></span>

Try, for example, well-known and useful packages angularfire and firebase: they appear in bower searches, but result in the error above.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#530
