### ISSUE TITLE
bug: Keyboard covers Modal Input (before typing)

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/ionic#4116]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Make a Modal with a lot of Inputs, so the modal is streched to it's full default height. Click on the last Input, now the keyboard comes up and is over your input, so you can't see anymore the value inside. 
As soon as you start typing something it moves the view up and eveything is fine. But this should already happen before typing.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Is this on iphone or iPad?

**Comment by mnewmedia** [comment]
Ipad, didn't test it on Iphone yet, but will test it over the weekend.

**Comment by Ionitron** [comment]
Greetings @mnewmedia!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @mnewmedia!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by robertftw** [comment]
Happens to me as well.

Make a modal and place an input center of screen. Open modal in ionic view and the keyboard will cover the input, as soon as you start typing the screen and the content jumps up and centers between keyboard and what's left of the screen correctly.

Tested on iPad Air.
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5

**Comment by gusleo** [comment]
I'm still get this issue?? any one resolve?
I'm in Ionic 1.2.4-nightly
I'm also disabled js scrolll ionicConfigProvider.scrolling.jsScrolling(false);

but no luck

**Comment by gusleo** [comment]
Finaly I resolve this issue with view step. It's usefull for keyboard hidden the input or freeze keyboard
1. On config.xml add this values
<preference name="android-windowSoftInputMode" value="stateVisible|adjustResize"/>
  <preference name="Fullscreen" value="false" />
  <preference name="KeyboardDisplayRequiresUserAction" value="true" />
  <feature name="Keyboard">
    <param name="ios-package" onload="true" value="IonicKeyboard"/>
  </feature>
  <feature name="Keyboard">
    <param name="android-package" value="com.ionic.keyboard.IonicKeyboard" />
    <param name="onload" value="true" />
  </feature>

2. Next on app.js on angular run function add "ionic.Platform.isFullScreen = false;"
3. Last, add overflow-scroll="true"
<ion-content overflow-scroll="true"></ion-content>

Hope, it will working to on your problem
