### ISSUE TITLE
bug: Wrong default range style

### ISSUE THREAD

**Issue by CheetahDev** [driftyco/ionic#4120]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

Range input should be customizable with Sass colors.
```lib/.../_variables.scss``` gives us a ```$range-default-track-bg``` set to ```#ccc !default;```
However, in ```/lib/.../_range.scss```, at line 36 ("```::-webkit-slider-thumb:before```"), the default color is ```$dark```.
Shouldn't it be ```$range-default-track-bg```?
Otherwise, there isn't any simple solution to set it a default color...

Thanks.</span>

<span is-issue-template></span>

**Comment by CheetahDev** [comment]
Anybody, Ionic team?

**Comment by mhartington** [comment]
It's probably just a design decision 

http://codepen.io/mhartington/pen/eNQrxB

This has been in here since November 2013 so I don't really want to change it. 

https://github.com/driftyco/ionic/commit/38153c5cd830f2d852940e56888b6a634a6d46b9#diff-98ae73e58d450773f66694ed0660fbf5R42

**Comment by CheetahDev** [comment]
Hi @mhartington,

Thanks for your answer. It's okay if it's a design decision, however, isn't it strange to be able to customize almost all component colors (with established variables) but this one?

Adding a variable like $range-default-bg set to $dark would keep your default design and ease styling for developers, wouldn't it?

Regards

**Comment by mhartington** [comment]
Here's what we have now.

<img width="451" alt="screen shot 2015-07-30 at 1 09 39 pm" src="https://cloud.githubusercontent.com/assets/2835826/8989815/8119e82a-36bc-11e5-874f-3d5e22e72b20.png">

And here's what we would have if we changed the variables to what you are suggesting.

<img width="453" alt="screen shot 2015-07-30 at 1 11 15 pm" src="https://cloud.githubusercontent.com/assets/2835826/8989823/9356fdb6-36bc-11e5-9235-99f8213572db.png">

Not really what we want. If you want to change the range color, we suggest that you use the classes. `range-positive`, `range-calm`, etc.

**Comment by CheetahDev** [comment]
Okay, thank you anyway @mhartington!
