### ISSUE TITLE
bug: Swipe to go back shows blank screen while using abstract nested states on iOS

### ISSUE THREAD

**Issue by Orthocenter** [driftyco/ionic#4122]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I found that if you have a parent abstract state, you will see an extra blank screen(parent abstract state) when you swipe to go back on iOS. Since this issue only occurs on iOS device, I will not create a codepen but only put some related code with a picture demonstrates this issue here:

states in app.js:
```
$stateProvider
            .state('signup', {
                abstract: true,
                templateUrl: 'templates/signup.html',
                controller: 'SignupCtrl'
            })
            .state('signup.index', {
                url: '/signup',
                templateUrl: 'templates/signup/index.html',
                controller: 'SignupIndexCtrl'
            })
```

// www/index.html
```
<body>

<ion-nav-bar></ion-nav-bar>

<ion-nav-view></ion-nav-view>

</body>
```

// templates/index.html
```
<ion-view>
    <ion-nav-title>
        welcome
    </ion-nav-title>
    <ion-content>

    </ion-content>
</ion-view>
```

// templates/signup.html
```
<ion-view hide-nav-bar="true">
    <ion-nav-view>
    </ion-nav-view>
</ion-view>
```

// templates/signup/index.html
```
<ion-view>

</ion-view>
```

<img src="http://i.imgur.com/mfHeY7t.png">

related discussions on ionic forum: [click here](http://forum.ionicframework.com/t/rc0-ios-swipe-to-go-back-with-nested-states-shows-blank-screen/19277/4)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Orthocenter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4122). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4122)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
You're missing `abstract: 'true'` in your main state

```
            .state('signup', {
                templateUrl: 'templates/signup.html',
                abstract: 'true',
                controller: 'SignupCtrl'
            })
```

**Comment by Orthocenter** [comment]
@mhartington thanks for your reply. Sorry, I forgot it when I typed this code on Github, but I have set 'abstract: true' in my real code actually. In addition, I have tested the issue I mentioned above with default view cache settings again, but nothing changed.

**Comment by mhartington** [comment]
Can you please provide a codepen then to test. 

Mike Hartington

**Comment by Orthocenter** [comment]
Hi, @mhartington  . Here is a codepen showing this issue:  http://codepen.io/Orthocenter/pen/oXaPoq .
It was forked from ionic official codepen Tabs Example, and removed some unnecessary parts. You can see a black screen when you click ‘go to tabs.home’ link first time. And If you swipe to go back at state 'tabs.home', you will see an extra white screen (the abstract view). The second case only occurs in native app, since swiping gesture has no effect in browsers. So please test with built native app. Thx

this picture illustrates the second case: <img src="http://i.imgur.com/AaffjMi.png">

**Comment by mhartington** [comment]
So you have your states setup wrong. Take a look at this codepen. 
http://codepen.io/ionic/pen/CbBsA


You should have them setup something like this.

```
    .state('tabs', {
      url: "/tab",
      abstract: true,
      templateUrl: "templates/tabs.html"
    })
    .state('tabs.home', {
      url: "/home",
      view: {
        "tab-view": {
          templateUrl: "templates/home.html"
        }
      }
    })
    .state('tabs.facts', {
      url: "/facts",
      view: {
        "tab-view": {
          templateUrl: "templates/facts.html"
        }
      }
    });

```

Note that this will not allow you to swipe back from tabs.home to index.

**Comment by Orthocenter** [comment]
Sorry, in my codepen, I just use some behaviors of UI-router but not ion-tabs. 
I wrote my states config according to this example: https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views#abstract-states, and I think I have set up correctly.
The root of this problem may be applying redundant animation on a parent view. Say that we are on state  B.C, previous state is A. When we swipe left, B should not be shown separately, but should be moved with C simultaneously instead. Thx

**Comment by mhartington** [comment]
Not necessarily, since we're dealing with abstract states. Since state B is abstract, the navigation and history management aren't sure how to handle. Do we swipe back from B to A or do we do nothing since there is no state to swipe back to from C.

This is a bug, but it's a bug that would require massive changes to ionic's history and navigations stacks as well as ui-router. This is being working on in V2, but as it stands it's not something that we could fix ATM.

**Comment by Orthocenter** [comment]
Thanks, that answers the question. I think that we should swipe back to A in that case. We should swipe back to the previous view, not parent state right? Maybe I have missed some cases.

**Comment by mhartington** [comment]
Right, we think it should go back to A, but the way our codebase stands ATM doesn't allow for this :disappointed: 

This is something that we are working on for V2, so we are aware of this shortcoming. Closing for now as there's no easy fix.

**Comment by srameshr** [comment]
@mhartington Any possibilities of bringing Ionic's push and pop navigation to Ionic 1? As of now the navigation is just a nightmare for a moderately complex app in Ionic 1

**Comment by ljcljc** [comment]
I am facing the same problem for this, anyone knows a good solution to fix that? Thanks
