### ISSUE TITLE
feat: page go back and reload

### ISSUE THREAD

**Issue by echizen** [driftyco/ionic#4123]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>usual we have a list items page called page1,and a add item page called page2. we add item in page2 and then go back to page1 and refresh it to show our new added item.this is a commonly demand.But I still can't do it with ionic lastly version(1.0.1).

there are many ways to get the outcome but not good. like:
+ 1. in route config,set `cache:false`,then use `$state.go('page1', {}, {reload: true});` it is not a good way because most occasion it is meaningful to use cache, only we add new item we need to clear cache.
other likely way like set ` views.maxCache(0)` or set `cache-view="false"` has the same problem.and `$state.transitionTo('tab.accountBook', {}, {reload: true, notify: true});` is the same to `$state.go('page1', {}, {reload: true});`

+ 2.

        $ionicHistory.clearCache();
        $timeout(function () {
               $state.transitionTo('page1', {}, {reload: true, notify: true});
        });
this works more elegant than the upon way,but I don't think `$timeout` is reliable , I need to know precise time when clearCache has completed.

I read the code of clearCache, it is:

      clearCache: function(stateIds) {
           $timeout(function() {
                $ionicNavViewDelegate._instances.forEach(function(instance) {
                      instance.clearCache(stateIds);
                });
           });
     },

why not let it return a promise , then I can use then() to execute my code in accurate time? or there is no need to do this? who can tell me the elegant and precise way to do this. thanks</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @echizen!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4123). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4123)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So you need to refresh the data when you go back? This is what the view events are for.

```javascript
$scope.$on("$ionicView.enter", function(){
// Rerun you code to fetch data
})
```

**Comment by Ionitron** [comment]
Greetings @echizen!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @echizen!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
