### ISSUE TITLE
docs: ionic build android error

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic#4125]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>SOLVE THIS PLS 

barathwaja@barathwaja-VirtualBox:~/myapp$ ionic build android
******************************************************
 Upgrade warning - for the CLI to run correctly,      
 it is highly suggested to upgrade the following:     

 Please update your Node runtime to version  >=0.12.x

******************************************************
Running command: /home/barathwaja/myapp/hooks/after_prepare/010_add_platform_class.js /home/barathwaja/myapp
add to body class: platform-android
Running command: /home/barathwaja/myapp/platforms/android/cordova/build 
[Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.]
ERROR building one of the platforms: Error: /home/barathwaja/myapp/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /home/barathwaja/myapp/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)</span>

<span is-issue-template></span>

**Comment by promactkaran** [comment]
you have to download android SDK (download the stand alone SDK tools ) and set path variables. 

Then in terminal

export ANDROID_HOME= /path-to-downloaded-sdk/android-sdk-macosx
PATH=$PATH:$ANDROID_HOME/tools
PATH=$PATH:$ANDROID_HOME/platform-tools

you also need ANT - download that and set the path variable for that too 

export PATH= /path-to-ant/apache-ant/bin/:"$PATH"

**Comment by mhartington** [comment]
This is not an issue with ionic it's self, but part of the setup required by cordova. 
Please read the cordova docs.

http://cordova.apache.org/docs/en/5.0.0/guide_platforms_android_index.md.html#Android%20Platform%20Guide

**Comment by Barathwaja** [comment]
tq i tried older version of node.js in windows and its working perfectly ..

**Comment by samadhansalgar** [comment]
in windows OS

set PATH=%PATH%;C:\Users\userName\AppData\Local\Android\android-sdk\tools;C:\Users\userName\AppData\Local\Android\android-sdk\platform-tools

IN mac

export PATH=${PATH}:/Users/userName/Documents/android-sdk-mac_x86/platform-tools:/Users/userName/Documents/android-sdk-mac_x86/tools
