### ISSUE TITLE
bug: need "full numeric keypad" as number input

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/ionic#4127]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Couldn't decide between `feature request` and `bug`. 
I need a `full numeric keypad` the value has to be a number. In the Docs you said: `"However, if you only need numbers entered, it’s best to stick with the tel input."`
That's what i did, but then it's not a number and doing `parseInt` is ugly :/

Beside that i think you should have the page of the different input types also in your "aside-menu".</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The different input types are really just html input types, so there's nothing special there.

Using `parsInt` is really on the best solution in this case.
