### ISSUE TITLE
docs: There is no space between status bar & header bar.

### ISSUE THREAD

**Issue by hojinshin** [driftyco/ionic#4128]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>6</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm testing with a 'ionic view' app in iphone 6. There is any problem on the first page, but it happens when I use menu-toggle, modal and href and sth like these. There is no space between status bar & header bar. 
So they overlaps. The height of status bar is 20px, and height of nav bar is 44px in iPhone. So I'm wondering if there is problem in 'ionic.css'. 
Plz let me know how can I figure out this problem. thanks!</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
What version of ionic are you using in the app? 
I just tested a fresh project on ionic view and everything seemed to work fine for me.

**Comment by hojinshin** [comment]
@mhartington oh it's 1.0.1..I think this is the latest version, right?
Have you tested in iPhone either?

**Comment by mhartington** [comment]
Correct, that is the latest version.

I've also tested it right on the device as well (not inside of ionic view). 
Could you share the app code?

**Comment by hojinshin** [comment]
@mhartington Here is my code :)  Really want to know the cause!!!
1. Html 
<div class="src-modal">
                <div class="header" style="height:44px">
                    <div class="src-space">
                        <label class="item item-input">
                            <input type="text" ng-model="input.filterUser" placeholder="Search">
                        </label>
                    </div>
                    <div class="close-src-modal">
                        <a href="#">Close</a>
                    </div>
                </div>
           </div>

2. Css
.open-src-modal {
    background-color:#4E67C6;
    border: none;
    border-radius: 4px;
    color: #fff;
    outline: none;
    padding: 20px 40px;
}

**Comment by hojinshin** [comment]
1. html 
![html](https://cloud.githubusercontent.com/assets/8757013/8827765/823c141a-30c9-11e5-91b9-12e27556e7f4.png)

2.css
![css](https://cloud.githubusercontent.com/assets/8757013/8827808/accce9d4-30c9-11e5-898d-fc586b1ba1b6.png)

3.js
![js](https://cloud.githubusercontent.com/assets/8757013/8827831/d530d908-30c9-11e5-8588-304d6204c261.PNG)

here is my code!

**Comment by mhartington** [comment]
Ah okay, so you just need to switch out the div with a class of header for an ion-header-bar. The directive will take care of adjusting it's height automatically.


Take a look at the codepen demo. 

http://codepen.io/ionic/pen/gblny

**Comment by hojinshin** [comment]
Great! It works well. Thank you so much!

Can I have one more question?
I want to change status bar font color in iPhone.
So I've installed 
cordova plugin add org.apache.cordova.statusbar

![sta](https://cloud.githubusercontent.com/assets/8757013/8828273/48a77f84-30cc-11e5-8730-78657745307a.PNG)

but my .run is designed like this.
So how can I make it?

**Comment by mhartington** [comment]
You can use any style that is mentioned in the statusbar plugin docs page.

https://github.com/apache/cordova-plugin-statusbar
