### ISSUE TITLE
bug: bug: bug: bug: No state change in conjunction with post

### ISSUE THREAD

**Issue by stevenmwade** [driftyco/ionic#4131]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Type**: <span ionic-type>bug</span>

<span ionic-description>For some reason, I cannot get the state to change when I make a login $http post to my local server.

Controller:

		$scope.login = function(user){
			$http.post('/api/v1/user/login', user)
				.success(function(data, status){
					console.log(data);
					authToken.setToken(data);
					$state.go('user.exercises');
				})
				.error(function(data, status){
					$scope.status = data;
				});
		};

HTML:

    <div class="list">
            <label class="item item-input">
                <span class="input-label">Username</span>
                <input type="text" ng-model="user.username">
            </label>
            <label class="item item-input">
                <span class="input-label">Password</span>
                <input type="password" ng-model="user.password">
            </label>
        </div>
        <div class="padding">
            <button class="button button-block button-positive" ng-click="login(user)">
                Log In
            </button>
            <p class="text-center">
                <a href="#/forgot-password">Forgot password</a>
            </p>
        </div>

ionic.project:

    "proxies": [
        {
	        "path": "/api/v1",
	        "proxyUrl": "http://localhost:5000/api/v1"
        }
    ]

config.xml

    <description>
        An Ionic Framework and Cordova project.
    </description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">
      Ionic Framework Team
    </author>
    <content src="index.html"/>

    //important
    <access origin="*"/>
    <allow-navigation href="http://*/*" />

    <preference name="webviewbounce" value="false"/>
    <preference name="UIWebViewBounce" value="false"/>
    <preference name="DisallowOverscroll" value="true"/>
    <preference name="android-minSdkVersion" value="16"/>
    <preference name="BackupWebStorage" value="none"/>
    <feature name="StatusBar">
      <param name="ios-package" value="CDVStatusBar" onload="true"/>
    </feature>

I'm not sure if it has to do with the way I have it set up to use my server or if it is an actually ionic and ui-router problem. This works with my web version.

Works if there is a $state.go before the post and inside of it. Not without one or the other, but both.</span>

<span is-issue-template></span>
</span></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @stevenmwade!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4131). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4131)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by stevenmwade** [comment]
I get an error alert ("issue update error") every time I submit it.
