### ISSUE TITLE
bug: Back button missing sometimes - works with "ionic": "v1.0.0-rc.3"

### ISSUE THREAD

**Issue by Robinyo** [driftyco/ionic#4132]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See -> http://forum.ionicframework.com/t/back-button-missing-sometimes/28235/9

@yewnork - Its a BUG :frowning:
@cormacodonnell
@DonEllingsworth 
@harmonics
  
See this fork of your Plunker: http://plnkr.co/edit/JVvifeOX5VSDGoa8lrTJ?p=preview

I updated the Plunker to use 1-0-1 (http://forum.ionicframework.com/t/1-0-1-vanadium-vaquita-released/27420) which didn't work so I checked my bower.json and noticed that I am still using:

    "ionic": "v1.0.0-rc.3"

which works, index.html:

    <link rel="stylesheet" href="http://code.ionicframework.com/1.0.0-rc.3/css/ionic.css" />
    <link rel="stylesheet" href="style.css" />
    <script src="http://code.ionicframework.com/1.0.0-rc.3/js/ionic.bundle.js"></script>

Note: I also updated from href to ui-sref in several files + fixed 'menu.html' as well :)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Robinyo!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4132). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4132)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Robinyo** [comment]
Just tried to:

    "ionic": "v1.0.0"

Which works, but:

    "ionic": "v1.0.1"

doesn't :(

**Comment by kamleshkoringa** [comment]
I have same issue with version 1.0.1

Here is code pen demo. http://codepen.io/anon/pen/wamRVX4

Sequence to reproduce
1) Select Check in from side menu.
2) Click on Attendees on main page new page will display back button 
3) Click back which will return to Check in page
4) Now select check in from side menu (Even if same page is open)
5) Click on Attendees link new page will not display Back button

**Comment by Robinyo** [comment]
Plunker Ionic 1.0.1: http://plnkr.co/edit/wzh9enXseYHfhakdxXhm?p=preview

**Comment by Robinyo** [comment]
Plunker "Playlists - Ionic v1.0.0":

http://plnkr.co/edit/pGwucVrTBDxSvw6z092h?p=preview

**Comment by mhartington** [comment]
@Robinyo so whats the difference between these two plunkrs? 

This one, http://plnkr.co/edit/pGwucVrTBDxSvw6z092h?p=preview , works as expected.

**Comment by Robinyo** [comment]
That's correct, Plunker "Playlists - Ionic v1.0.0" - http://plnkr.co/edit/pGwucVrTBDxSvw6z092h?p=preview displays a '<' back button if you:

1. Tap 'Reggae'
2. Tap '<'
3. Tap 'nav-icon'
4. Tap 'Playlists' shows Playlist with a  '<' back button 

If you follow the same steps with the Ionic v1.0.1 Plunker Ionic 1.0.1 - http://plnkr.co/edit/wzh9enXseYHfhakdxXhm?p=preview it displays nav-icon NOT a '<' back button.

So, the 'bug' was introduced in Ionic version 1.0.1.

**Comment by mhartington** [comment]
There's a small list of changes in 1.0.1, and only two that may be the culprit.

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#101-vanadium-vaquita-2015-06-30

**Comment by mhartington** [comment]
Okay, so cef6708 is the culprit, looking into a fix

**Comment by abhayastudios** [comment]
@perrygovier I am still seeing this behavior in ionic v1.1.0 where eventually I will see this in the console:

<pre>
TypeError: Cannot read property 'expire' of null
    at ionic.bundle.js:47159
    at Scope.$broadcast (ionic.bundle.js:24992)
    at y.transition.M.then.y.transition.y.transition (angular-ui-router.min.js:7)
    at processQueue (ionic.bundle.js:23394)
    at ionic.bundle.js:23410
    at Scope.$eval (ionic.bundle.js:24673)
    at Scope.$digest (ionic.bundle.js:24484)
    at Scope.$apply (ionic.bundle.js:24778)
    at ionic.bundle.js:26545
    at completeOutstandingRequest (ionic.bundle.js:14221)
</pre>

When using the menu-toggle attribute it is working fine.

**Comment by ajp8164** [comment]
This issue remains unresolved.  Using Ionic 1.7.12.  The error occurs in nextViewOption() in the deregisterStateChangeListener.  When a $stateChangeSuccess event occurs it's handler is called.  nextViewOptions is null when the event occurs which triggers the error at nextViewOptions.expire when calling $timeout().

nextViewOptions: function(opts) {
      deregisterStateChangeListener && deregisterStateChangeListener();
      if (arguments.length) {
        $timeout.cancel(nextViewExpireTimer);
        if (opts === null) {
          nextViewOptions = opts;
        } else {
          nextViewOptions = nextViewOptions || {};
          extend(nextViewOptions, opts);
          if (nextViewOptions.expire) {
              deregisterStateChangeListener = $rootScope.$on('$stateChangeSuccess', function() {
                nextViewExpireTimer = $timeout(function() {
                  nextViewOptions = null;
                  }, **nextViewOptions.expire**);
              });
          }
        }
      }
      return nextViewOptions;
    },

**Comment by rooftoprafa** [comment]
This occurs to me to, on Ionic 1.7.14.

**Comment by mrah** [comment]
Me too, 1.7.14.

`0     226745   error    Error: null is not an object (evaluating 'nextViewOptions.expire')
http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:51661:37
$broadcast@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:29477:33
http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:49321:32
processQueue@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:27879:30
http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:27895:39
$eval@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:29158:28
$digest@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:28969:36
$apply@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:29263:31
http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:31030:42
completeOutstandingRequest@http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:18706:15
http://192.168.1.101:8101/lib/ionic/js/ionic.bundle.js:18978:33`
