### ISSUE TITLE
bug: State won't change in post

### ISSUE THREAD

**Issue by stevenmwade** [driftyco/ionic#4138]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>For some reason, I cannot get the state to change when I make a login $http post to my local server.

Controller:

    $scope.login = function(user){
        $http.post('/api/v1/user/login', user)
            .success(function(data, status){
                console.log(data);
                authToken.setToken(data);
                $state.go('user.exercises');
            })
            .error(function(data, status){
                $scope.status = data;
            });
    };
HTML:

    <div class="list">
        <label class="item item-input">
            <span class="input-label">Username</span>
            <input type="text" ng-model="user.username">
        </label>
        <label class="item item-input">
            <span class="input-label">Password</span>
            <input type="password" ng-model="user.password">
        </label>
    </div>
    <div class="padding">
        <button class="button button-block button-positive" ng-click="login(user)">
            Log In
        </button>
        <p class="text-center">
            <a href="#/forgot-password">Forgot password</a>
        </p>
    </div>
ionic.project:

    "proxies": [
    {
        "path": "/api/v1",
        "proxyUrl": "http://localhost:5000/api/v1"
    }
]
config.xml

    <description>
    An Ionic Framework and Cordova project.
    </description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">
      Ionic Framework Team
    </author>
    <content src="index.html"/>

    //important
    <access origin="*"/>
    <allow-navigation href="http://*/*" />

    <preference name="webviewbounce" value="false"/>
    <preference name="UIWebViewBounce" value="false"/>
    <preference name="DisallowOverscroll" value="true"/>
    <preference name="android-minSdkVersion" value="16"/>
    <preference name="BackupWebStorage" value="none"/>
    <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
    </feature>

I'm not sure if it has to do with the way I have it set up to use my server or if it is an actually ionic and ui-router problem. This works with my web version.

UPDATE:

It works if there are two $state.gos. Not one or the other. It needs to have both. This doesn't make any sense. Works in web version, but not Ionic.

    $scope.login = function(user){
        $state.go('user.exercises');
        $http.post('/api/v1/user/login', user)
            .success(function(data, status){
                console.log(data);
                authToken.setToken(data);
                $state.go('user.exercises');
            })
            .error(function(data, status){
                console.log(data);
                $scope.status = data;
            });
    };

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, I'm not able to replicate the issue here.

http://jsbin.com/gawericigu/edit?js,console,output

**Comment by stevenmwade** [comment]
What information can I give you to narrow down the problem? It doesn't seem to be much different except it retrieves login information from a MongoDB server. It works on my web-app, but not in Ionic. Do you need server code? I can't imagine this would affect this. Here are my states:

    .state('login', {
        url: '/login',
        controller: 'LoginController',
        templateUrl: './views/login.html'
    })
    .state('logout', {
        url: '/logout',
        controller: 'LogoutController'
    })          
    .state('user', {
        url: '/user',
        abstract: true,
        templateUrl: './user/views/content.html',
        controller: 'TabController'
    })
        .state('user.profile', {
            url: '/profile',
            views: {
                'user-profile': {
                    controller: 'UserProfileController',
                    templateUrl: './user/views/profile.html'   
                }
            }
        })
        .state('user.exercises', {
            url: '/exercises',
            views: {
                'user-exercises': {
                    controller: 'UserExercises',
                    templateUrl: './user/views/exercises.html'  
                }
            }
        })
            .state('user.exercise', {
                url: '/exercise',
                views: {
                    'user-exercises': {
                        controller: 'UserExercise',
                        templateUrl: './user/views/exercise.html'  
                    }
                }
            })
        .state('user.meals', {
            url: '/meals',
            views: {
                'user-meals': {
                    controller: 'UserMeals',
                    templateUrl: './user/views/meals.html' 
                }
            }
        })

**Comment by mhartington** [comment]
Hmm, its tough to narrow down the problem without the server implementation. If you could create a sample project that has the same issue and post it to github, it could help figure out the issue.

**Comment by stevenmwade** [comment]
And it looks like I found the source of the problem. It has to do with the `ng-if="platform.isAndroid/IOS"` which is causing the views not to change entirely. So whatever is happening with those if statements, it's not allowing it to change on the first `$state.go`. Maybe this is my fault for not having best practice to have the correct style of icons for it's respective OS.

    <ion-tabs class="tabs-icon-top tabs-color-active-positive">

    
    <ion-tab title="Dashboard" icon-off="ion-speedometer" icon-on="ion-speedometer" href="#/user/dashboard">
        <ion-nav-view name="user-dashboard"></ion-nav-view>
    </ion-tab>

    
    
    <ion-tab ng-if="platform.isAndroid()" title="Programs" icon-off="ion-android-list" icon-on="ion-android-list" href="#/user/programs">
        <ion-nav-view name="user-programs"></ion-nav-view>
    </ion-tab>
    
    <ion-tab ng-if="platform.isIOS()" title="Programs" icon-off="ion-ios-list-outline" icon-on="ion-ios-list" href="#/user/programs">
        <ion-nav-view name="user-programs"></ion-nav-view>
    </ion-tab>

    
    
    <ion-tab ng-if="platform.isAndroid()" title="Exercises" icon-off="ion-android-clipboard" icon-on="ion-android-clipboard" href="#/user/exercises">
        <ion-nav-view name="user-exercises"></ion-nav-view>
    </ion-tab>
    
    <ion-tab ng-if="platform.isIOS()" title="Exercises" icon-off="ion-clipboard" icon-on="ion-clipboard" href="#/user/exercises">
        <ion-nav-view name="user-exercises"></ion-nav-view>
    </ion-tab>

    
    
    <ion-tab ng-if="platform.isAndroid()" title="Meals" icon-off="ion-fork" icon-on="ion-fork" href="#/user/meals">
        <ion-nav-view name="user-meals"></ion-nav-view>
    </ion-tab>
    
    <ion-tab ng-if="platform.isIOS()" title="Meals" icon-off="ion-fork" icon-on="ion-fork" href="#/user/meals">
        <ion-nav-view name="user-meals"></ion-nav-view>
    </ion-tab>

    
    
    <ion-tab ng-if="platform.isAndroid()" title="Profile" icon-off="ion-person" icon-on="ion-person" href="#/user/profile">
        <ion-nav-view name="user-profile"></ion-nav-view>
    </ion-tab>
    
    <ion-tab ng-if="platform.isIOS()" title="Profile" icon-off="ion-person" icon-on="ion-person" href="#/user/profile">
        <ion-nav-view name="user-profile"></ion-nav-view>
    </ion-tab>

    
    
    <ion-tab ng-if="platform.isAndroid()" title="Message" icon-off="ion-android-chat" icon-on="ion-android-chat" href="#/user/message">
        <ion-nav-view name="user-message"></ion-nav-view>
    </ion-tab>
    
    <ion-tab ng-if="platform.isIOS()" title="Message" icon-off="ion-ios-chatboxes-outline" icon-on="ion-ios-chatboxes" href="#/user/message">
        <ion-nav-view name="user-message"></ion-nav-view>
    </ion-tab>


    </ion-tabs>

**Comment by mhartington** [comment]
So is this okay to close?

**Comment by stevenmwade** [comment]
Still seems to be a bug where using an ng-if to check the platform causes states not to completely change.

**Comment by mhartington** [comment]
Hmm, simple solution would be to not do that at the tab level, but at the content level.
Are you just trying to change the icons based on platform or do more?

**Comment by stevenmwade** [comment]
I'm just trying to change Icons based on the platform and I wanted it to be on the tab level to have the tabs have icons correspond to their platform to keep design uniform to that specific platform.

**Comment by mhartington** [comment]
In that case you could use `icon={{platform.icon}}` and then define your icons in your JS.
