### ISSUE TITLE
feat: Disable livereload and reload through the command line.

### ISSUE THREAD

**Issue by hdavidzhu** [driftyco/ionic#4152]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>

I use my save command quite frequently, and every time I save the app reloads. Using the developer console provided by Safari, the console reloads and keeps loading all of my saves - even if those are just intermediary saves.

However, if I run ionic without livereload, I have to rebuild every single time which becomes a hassle. It would be nice to hit a key like `r` for reloading to refresh the app with the latest code. Currently there doesn't seem to be a good middle ground.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hdavidzhu!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4152). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4152)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Already possible with the CLI. Check to make sure you have the latest version of the CLI installed.

```
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Comment by hdavidzhu** [comment]
I have the latest version 1.6.1.

I know I can manually restart the app through the `r` command. However, I want to disable the `livereload` feature when I save in my text editor. Is there a way to do that?

**Comment by mhartington** [comment]
That would defeat the purpose of livereload though...
Right, there needs to be a small server open for the console logs to travel back to.

**Comment by hdavidzhu** [comment]
I love livereload for what it is, and I don't think it defeats the purpose at all. I think that livereload becomes less useful for me when it happens way too frequently. For instance, my browserify takes time to compile, yet livereload jumps to the scene and reloads immediately. This forces me to trigger livereload twice to see my first browserify updates.

One of my major benefits I see with Ionic's livereload implementation is that I don't have to rebuild my app through `ionic emulate ios` when I want to see my changes. I want to make several changes, several saves, and at the end simply hit something like `r` and enable livereload again. This way my minute changes can act together to work with the emulator. 

It could be that my emulator is slow that I want this feature. Livereload on the emulator slows down my Safari web inspector, and I have to close Safari and reopen it if the logs start gettting too long from antiquated console logs of previous saves (it still keeps loading them even when I hit the trash button the old logs because those logs haven't been fully loaded).

I guess what I'm interested in at the end of the day is a way to turn on semi-automatic livereload rather than using either a slow musket or a trigger happy minigun.

**Comment by mhartington** [comment]
So you're using browserify and ionic's livereload server, would have been good to know that before hand. 

If that's the case, then you can modify the watch paths in ionic.project.

https://github.com/driftyco/ionic-cli/blob/master/README.md#advanced-serve-options

**Comment by hdavidzhu** [comment]
Thanks! This makes much more sense now! I disabled everything in the watch list and have the app behaving as I want it to. Thanks for guiding me in the right direction.
