### ISSUE TITLE
bug: Contenteditable can’t scroll in ios/android and difficult to get focus

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [driftyco/ionic#4162]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I normally need to click twice to focus on the contenteditable div , and if my input was long enough ,there is no scroll bar showed up (it's normal in safari). If wraped this div with ion-scroll, then it can't get focus at all. That's my div:

    <div contenteditable="true" data-tap-disabled="true" overflow-scroll="true" style="height:200px;overflow:scroll;background-color:red"></div></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Nick-The-Uncharted!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4162). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4162)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
It's not really recommended to use contenteditable divs. Use a textarea instead.

**Comment by Nick-The-Uncharted** [comment]
@mhartington But I am trying to integrate a editor like quill into my app.TextArea seems only support plain text.

**Comment by Nick-The-Uncharted** [comment]
@mhartington If move div out of ion-content then it works fine. But part of my page will overlap with header but I can fix this by adjust it's position . Maybe ionic prevent event like swipe ?

**Comment by mhartington** [comment]
So the overall issue here is that the scrolling/tap logic ionic doesn't play well with contenteditable divs. Ion-content is a big part of that since it's our js-scrolling. If you could provide a codepen of what you have I can load it on a device and test it out.

**Comment by Nick-The-Uncharted** [comment]
@mhartington This is my [codepen](http://codepen.io/Nick-The-Uncharted/pen/NqeWda)(run it in emulator , it is normal in safari/chrome).When creating it I found my div can scroll if keyboard is not shown.So maybe keyboard is the reason when it act abnormally.

**Comment by KillerCodeMonkey** [comment]
@mhartington 
i recognized similar things.
I have tried to to use something like wysiwyg editors and they are using contenteditable divs or iframes with a textarea. The contenteditable div works better than the iframe+textarea.

**Comment by TonyLuo** [comment]
+1. looking forward to seeing this issue be fixed

**Comment by TheMattRay** [comment]
+1

**Comment by b3na** [comment]
+1. Having a rough time implementing a WYSIWYG editor, mainly in iOS, so this fix or maybe ionic creating a custom text editor will be great.

**Comment by johannds** [comment]
+1 for the text editor with tagging.

**Comment by jgw96** [comment]
Hello all! I am going to close this as it is not recommended to use contenteditable divs (not only with ionic, but with the web in general). Textareas are the way to go, especially for mobile, and some of the best web based editors ive seen (https://ace.c9.io/#nav=about) are wrapped with a textarea. Thanks for using Ionic!

**Comment by franbueno** [comment]
Hi @jgw96, 

I´m still figuring out the best approach to create a rich editor. Basically, i need to add texts, videos and images. You said that you don't recommended to use contenteditable but have no idea how to do it without contenteditable... any hint? Thanks :)
