### ISSUE TITLE
bug: updating ionic 1.5.0 to 1.6.3 causes networking feature not to work - only happens on android

### ISSUE THREAD

**Issue by axilaris** [driftyco/ionic#4167]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When I upgraded ionic 1.5.0 to 1.6.3 (latest), networking ajax calls does not work anymore. Not sure why. I was required to remove android and re add android platform. not sure but something did change with the apk names from MainActivity-debug.apk to android-debug.apk

This problem only happens on Android but not iOS.

Here is a very simple ajax call:

       $scope.doLogin = function () {
        urlcd = "http://desolate-eyrie-5848.herokuapp.com/offsprings.json";
        console.log("XXX:" + urlcd);
            var request = $http({
                method: "post",
                url: urlcd,
                timeout: 90000,
                data: {email: email, password: password}//$scope.doLogin
            });

            request.success(function (data) {
                console.log('data: ' + data.status);       
            });
        request.error(function (data, status) {
        console.log('XXX error data:' + data + " status:" + status);
    });
here are my android debug traces:

    07-30 11:32:18.399: I/Web Console(21850): XXX Doing login  at file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173
    07-30 11:32:18.399: D/PluginManager(21850): exec() call to unknown plugin: Console
    07-30 11:32:18.399: I/Web Console(21850): XXX:http://desolate-eyrie-5848.herokuapp.com/offsprings.json at file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173
    07-30 11:32:18.399: D/PluginManager(21850): exec() call to unknown plugin: Console
    07-30 11:32:18.459: D/chromium(21850): Unknown chromium error: 0
    07-30 11:32:18.459: I/Web Console(21850): XXX error data: status:0 at file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173
    07-30 11:32:18.459: D/PluginManager(21850): exec() call to unknown plugin: Console
How can I troubleshoot and get ionic work with networking on Android ?

I posted my question here as well:

By the way, this logs is on android 2.3.

http://stackoverflow.com/questions/31722970/updating-ionic-1-5-0-to-1-6-3-causes-networking-feature-not-to-work-only-happe</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @axilaris!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4167). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4167)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mdridley** [comment]
Make sure that you have added the Whitelist plug-in. Latest versions of Cordova changed how whitelisting works.

http://devgirl.org/2015/04/24/apache-cordova-newsflash/

**Comment by mhartington** [comment]
First thing, 
>When I upgraded ionic 1.5.0 to 1.6.3 (latest),
That is the ionic cli version, no the ionic framework version. Ionic framework (css/js) is at 1.0.1.

>networking ajax calls does not work anymore
@mdridley is correct. You need to include the whitelist plugin. This was big change for cordova-android in 4.x.

**Comment by axilaris** [comment]
yup that worked, thanks @mdridley
