### ISSUE TITLE
bug: right align input shifts label on focus

### ISSUE THREAD

**Issue by drkhannah** [driftyco/ionic#4169]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am working with ionic 1.0.1 and when i apply this class to an input 

.currency {
  text-align: end;
}

the label shifts to the left off screen when the input is focused on

help

<div class="list">
                
                <label class="item item-input item-select">
                    <div class="input-label">
                        Select Account
                    </div>
                    <select name="account" required ng-model="vm.selectedAccount" ng-change="vm.accountChange()">
                        <option ng-repeat="account in vm.accounts">{{account.accountNumber}}</option>
                    </select>
                </label>

                
                <label class="item item-input">
                    <span class="input-label">Deposit Amount:</span>
                    <input ng-currency class="currency" type="text" ng-required="true" name="depositAmount" ng-model="vm.deposit">
                </label>

                
                <label class="item item-input">
                    <span class="input-label">Check Amount:</span>
                    <input ng-currency class="currency" type="text" ng-required="true" name="checkAmount" ng-model="vm.checkAmount">
                </label>

                
                <div class="card" ng-click="vm.miSnapCheckFront()">
                    <div class="item item-text-wrap">
                        <div class="item item-icon-right">
                            <h2 ng-hide="vm.checkFrontImage !== '' && vm.checkFrontImage !== undefined">Capture Check Front</h2>
                            <h2 ng-show="vm.checkFrontImage !== '' && vm.checkFrontImage !== undefined">Rake Check Front</h2>
                            <img class="capture-check-thumbnail" ng-show="vm.checkFrontImage !== '' && vm.checkFrontImage !== undefined" ng-src="data:image/png;base64,{{vm.checkFrontImage}}">
                            <i class="icon ion-camera" ng-hide="vm.checkFrontImage !== '' && vm.checkFrontImage !== undefined"></i>
                            <i class="icon ion-arrow-return-left" ng-show="vm.checkFrontImage !== '' && vm.checkFrontImage !== undefined"></i>
                        </div>
                    </div>
                </div>

                
                <div class="card" ng-click="vm.miSnapCheckBack()">
                    <div class="item item-text-wrap">
                        <div class="item item-icon-right">
                            <h2 ng-hide="vm.checkBackImage !== '' && vm.checkBackImage !== undefined">Capture Check Back</h2>
                            <h2 ng-show="vm.checkBackImage !== '' && vm.checkBackImage !== undefined">Rake Check Back</h2>
                            <img class="capture-check-thumbnail" ng-show="vm.checkBackImage !== '' && vm.checkBackImage !== undefined" ng-src="{{vm.checkBackImage}}">
                            <i class="icon ion-camera" ng-hide="vm.checkBackImage !== '' && vm.checkBackImage !== undefined"></i>
                            <i class="icon ion-arrow-return-left" ng-show="vm.checkBackImage !== '' && vm.checkBackImage !== undefined"></i>
                        </div>
                    </div>
                </div>

                
                <button type="submit" ng-disabled="captureCheckForm.$invalid || vm.checkFrontImage === undefined || vm.checkBackImage === undefined" class="button button-full button-positive">
                    Submit Check
                </button>
            </div></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @drkhannah!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4169). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4169)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can provide a codepen?

**Comment by scorfishyu** [comment]
I have this problem too, with iOS8

**Comment by scorfishyu** [comment]
Seems the "display: -webkit-flex;" not support well on iOS8,
I fix it by use "display: -webkit-box" inline to overwrite it
```
<label class="item item-input" style="display: -webkit-box;">
    <span class="input-label">Current Loan Balance</span>
    <input type="number" class="text-right">
 </label>
```

**Comment by drkhannah** [comment]
Thanks, i noticed it only happened when my label went over a certain length, so ive been keeping my labels concise, ill try this thanks

**Comment by Ionitron** [comment]
Greetings @drkhannah!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
