### ISSUE TITLE
bug: cached collectionRepeat still handle resize event

### ISSUE THREAD

**Issue by dreamershl** [driftyco/ionic#4196]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>CollectionRepeatDirective hook scroll-resize event to refresh dimension. When it is cached (invisible now), the event handler is still on. So the refreshDimensions() will get the wrong dimension. 

Suggest to add the scope disconnection flag in the refreshDimensions()</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please provide a codepen demoing this.

**Comment by dreamershl** [comment]
It is very difficult for me to demo it in the codepen. Because there is no exported interface to hook the event. The following is my findings, hope can make the issue clear. 

**DOM event triggering process is independent from the angular scope event. When the scope is 'disconnected', DOM event will still reach the handler as long as the hook isn't off**. 

Since the collectionRepeat hooked event ''scroll-resize'' is DOM event, the "refreshDimensions" will always be invoked even the scope is cached (disconnected).

My fix is to check the visibility in the refreshDimensions()  as the following 

         function refreshDimensions() {
                 if(!scrollCtrl.$element.is(':visible'))
                  return;

1.  collectionRepeat will hook the 'scroll-resize' event when it is initialized 

         // Dimensions are refreshed on resize or data change.
         scrollCtrl.$element.on('scroll-resize', refreshDimensions);

2. collectionRepeat will turn off the DOM event only in the '$destroy'
   
        scope.$on('$destroy', function() {

**Comment by Ionitron** [comment]
Greetings @dreamershl!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
