### ISSUE TITLE
bug: ionicScrollDelegate doesn't animate first scroll

### ISSUE THREAD

**Issue by willmore** [driftyco/ionic#4197]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My app uses $ionicScrollDelegate with anchorScroll(true) to scroll to a given element by ID, in conjunction with $location.hash(...).

```
$location.hash(anchor);
var handle = $ionicScrollDelegate.$getByHandle('content');
handle.anchorScroll(true);
```

The code always successfully scrolls to the desired location. However, the scroll is only animated second and subsequent runs. The first run, the app jumps "instantaneously" to the location.

Able to re-produce both in Android hybrid and in Chrome on dev machine.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you provide a codepen?

**Comment by Ionitron** [comment]
Greetings @willmore!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
