### ISSUE TITLE
bug: Template not loading after a click on a link

### ISSUE THREAD

**Issue by hotgeart** [driftyco/ionic#4200]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I followed the doc, but my template doesn't load when I click on a link (demo at bottom).

My app.js

```js
app = angular.module('starter', ['ionic']);

app.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
});

app.config(function($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('homepage', {
            url: '/',
            templateUrl: 'home.html',
        })
        .state('other', {
            url: '/other',
            templateUrl: 'other.html',
        })
        .state('forum', {
            url: '/forum',
            templateUrl: 'forum.html',
        })
    ;
  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/');
});

app.controller('AppCtrl', function($scope) {

});

app.controller('Home', function($scope) {
  alert('home');
});

app.controller('Other', function($scope) {
  alert('other');
});

app.controller('Forum', function($scope) {
  alert('forum');
});

```

My index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>
    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <!-- IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
    <link href="css/ionic.app.css" rel="stylesheet"> -->
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="cordova.js"></script>
    <script src="js/app.js"></script>
  </head>
    <body ng-app="starter" ng-controller="AppCtrl">
        <ion-nav-view></ion-nav-view>
    </body>
</html>
```

home.html

```html
<ion-side-menus ng-controller="Home">
    <h1>Home.html</h1>
	<a ui-sref="other">other</a><br>
	<a ui-sref="forum">forum</a>
</ion-side-menus>
```

forum.html

```html
<ion-side-menus ng-controller="Forum">
    <h1>Forum.html</h1>
	<a ui-sref="home">Home</a><br>
	<a ui-sref="other">Other</a>
</ion-side-menus>
```
other.html

```html
<ion-side-menus ng-controller="Other">
    <h1>Other.html</h1>
	<a ui-sref="home">Home</a><br>
	<a ui-sref="forum">Forum</a>
</ion-side-menus>
```

You can test here : http://hotgeart.olympe.in/app/#/

When you click on "other" the url change in the address bar, but the template doesn't load. But if I go directly on http://hotgeart.olympe.in/app/#/other the template load.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @hotgeart!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4200). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4200)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Why are you using `ion-side-menus` for your views? Your templates are not setup correctly.

Try this instead.

```
<ion-view>
    <h1>Other.html</h1>
    <a ui-sref="home">Home</a><br>
    <a ui-sref="forum">Forum</a>
</ion-view>
```

Also you can move your ng-controllers up to your states.

```
 $stateProvider
        .state('homepage', {
            url: '/',
            templateUrl: 'home.html',
            controller: 'Home',
        })
        .state('other', {
            url: '/other',
            templateUrl: 'other.html',
            controller: 'Other',
        })
        .state('forum', {
            url: '/forum',
            templateUrl: 'forum.html',
            controller: 'Forum',
        });
```

**Comment by hotgeart** [comment]
> Why are you using ion-side-menus for your views? Your templates are not setup correctly.

Because it's a simplified code. That's not my real project, I juste wanted to recreate the bug but with less code.

I use ion-side-menus in my real template:

```html
<ion-side-menus ng-controller="NotificationCtrl">
    <ion-side-menu-content>
        <ion-header-bar class="bar-positive">
            <button class="button button-icon ion-navicon" ng-click="toggleLeft()" ng-hide="$exposeAside.active"></button>
            <h1 class="title">Notification</h1>
        </ion-header-bar>
        <ion-content>

            <ion-list class="feed">

                <ion-item class="item" ng-repeat="n in notifications">

                </ion-item>

            </ion-list>


            <div class="more padding">
                <ion-spinner icon="android" ng-show="isLoading"></ion-spinner>
                <button class="button button-block button-positive" ng-hide="isLoading" ng-click="getMoreNotification()">Charger plus</button>
            </div>

        </ion-content>
    </ion-side-menu-content>
    <ion-side-menu expose-aside-when="large" class="panel-menu-left">
        <ion-content>
            <div ng-include src="'templates/blocks/menu.html'"></div>
        </ion-content>
    </ion-side-menu>
    <div ng-include src="'templates/blocks/tabs.html'"></div>
</ion-side-menus>
```

**Comment by mhartington** [comment]
Either way, I'm not able to debug the issue from that. Please create a codepen from that and post that here.

**Comment by hotgeart** [comment]
I've no idea how to create a Codepen with multiple files so I create a plnkr if it's ok.

http://plnkr.co/edit/IFHpZF4MOOrRYciLTjAs

Click on "run" in the header bar for launching the script. And click on this to see the URL

![full](http://image.noelshack.com/fichiers/2015/32/1439021627-sans-azdazdazdtitre-1.jpg)

Or directly go on http://run.plnkr.co/RSwtjCBSm2IN3pRk/#/

**Comment by mhartington** [comment]
You structure is all wrong. 
Please reorganize and set your views up like this.

http://codepen.io/ionic/pen/QwamEW

**Comment by vishalmote** [comment]
Hello, 

As per your link also, I am not able to reload the controller. add alerts in AttendeesCtrl and CheckinCtrl controller. when I first time visit the link it shows alerts but in second time I visit other link and revisit back to old link, it doesn't load the controller. I want to reload the controller on every visit.

http://codepen.io/ionic/pen/QwamEW
