### ISSUE TITLE
bug: nested ion-nav-views broken with nav-bar >1.0 b11

### ISSUE THREAD

**Issue by wwelchj** [driftyco/ionic#4201]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Both ion-nav-bar and ion-nav-views do not work as expected after 1.0.0 beta 11 (or before beta 1 for that matter). Notice in this codepen (http://codepen.io/anon/pen/WvmNyj) that
1. The information is not offset by the navigation bar.
2. The text after the first nav-view and before the second nav-view does not show.

This works as expected. 1.0.0-beta1 through 1.0.0-beta11, but not after or before.</span>

<span is-issue-template></span>

**Comment by wwelchj** [comment]
To add, oftentimes the title in the navigation bar often does not update as well

**Comment by wwelchj** [comment]
Doing some comparison between what CSS styles are applied has yielded the following:
Removing the "class='view-container'" from the ion-nav-view and "class='pane'" from the child objects of the nav-view results in output equivalent to the 1.0.0-beta11 version

**Comment by mhartington** [comment]
So the structure you are using is incorrect. 
Nested view like this aren't the correct way to handle view in ionic.

http://jsbin.com/zeqigi/1/edit?html,js,output

**Comment by wwelchj** [comment]
I respectfulyl disagree -- the UI-Router docs specifically address this possibility:
https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views

**Comment by wwelchj** [comment]
I would also note that this exact setup using Angular with UI-Router (ui-view) appears to work perfectly fine.

**Comment by mhartington** [comment]
Right, but the UI-router examples are meant more for a traditional desktop experience. That doesn't translate well onto mobile. Mobile apps really don't have multiple nested view like UI-Router demos.

But you can use ui-view instead of ion-nav-view if you want.
http://codepen.io/mhartington/pen/GJegWm
