### ISSUE TITLE
bug: Collection-repeat: cards list item weird padding

### ISSUE THREAD

**Issue by mhd999** [driftyco/ionic#4203]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I noticed weird padding and margin in the card list, suddenly the margin between each cards gone and the padding of the last card got so weird with height of 794 px
and width of 364 px
i removed all the custom css don't fix the issue i got back to backup version it works fine, then i noticed the only difference i used ng-repeat before and now collection-repeat.

i got back to ng-repeat everything looks just fine. 

i would like to know why i remove all collection-repeat from my code and replace it back with ng-repeat.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please provide a codepen demoing this.

**Comment by Ionitron** [comment]
Greetings @mhd999!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by mhd999** [comment]
Am sorry i got busy so much that i didn't have time to make a codepen ill find time this weekend and post codepen as we still have this issue.
