### ISSUE TITLE
bug: Collection Repeat under 20 has ghosts

### ISSUE THREAD

**Issue by sjfricke** [driftyco/ionic#4206]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a dynamic amount of items in my ion-scroll and I am using a collection repeat to show them horizontally. The issue is I can't go .itemInCSS:last-child{margin-right: 25px !important} because if there are under 20 items, lets say 15, there will be 5 extra ghost items and it looks sloppy without that last margin.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please provide a codepen demoing this.

**Comment by gummie4444** [comment]
// Create the pool of items for reuse, setting the size to (estimatedItemsOnScreen) * 2,
      // plus the size of the renderBuffer.
      if (!isLayoutReady) {
        var poolSize = Math.max(20, renderBuffer * 3);
        for (var i = 0; i < poolSize; i++) {
          itemsPool.push(new RepeatItem());
        }
      }

it's probbably this that is causing the ghosts

**Comment by Ionitron** [comment]
Greetings @sjfricke!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
