### ISSUE TITLE
bug: 'ionic resources` uses backslashes in images path

### ISSUE THREAD

**Issue by gmarziou** [driftyco/ionic#4212]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>When generating icon and splash screen with 'ionic resources' the paths to images are wrong as they use '\' rather than '/'.
I am using ionic 1.0.1 and ionic-cli 1.64 on Windows, I thought it was related to Windows but another forum member got it also on OSX: http://forum.ionicframework.com/t/ionic-resource-fail-to-copy-ios-icons-and-splash-screens/30139</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Will look into this. As far as I know, this should be handled by cordova. Will investigate.

**Comment by gmarziou** [comment]
@mhartington what is the status?

**Comment by mlynch** [comment]
Can you try the beta release? `npm install -g ionic@beta`. If it's still not working mind posting over here? https://github.com/driftyco/ionic-cli/issues

**Comment by gmarziou** [comment]
It did not make any difference.

I had to install beta release also in local npm install ionic@beta

~~~
ionic info

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 7 SP1
Node Version: v4.2.2
~~~

~~~
ionic resources
Ionic icon and splash screen resources generator
icon android drawable-ldpi-icon.png (36x36) from cache
icon android drawable-mdpi-icon.png (48x48) from cache
icon android drawable-hdpi-icon.png (72x72) from cache
icon android drawable-xhdpi-icon.png (96x96) from cache
icon android drawable-xxhdpi-icon.png (144x144) from cache
icon android drawable-xxxhdpi-icon.png (192x192) from cache
splash android drawable-port-ldpi-screen.png (240x320) from cache
splash android drawable-port-mdpi-screen.png (320x480) from cache
splash android drawable-port-hdpi-screen.png (480x800) from cache
splash android drawable-port-xhdpi-screen.png (720x1280) from cache
splash android drawable-port-xxhdpi-screen.png (960x1600) from cache
splash android drawable-port-xxxhdpi-screen.png (1280x1920) from cache
~~~

**Comment by jakub-g** [comment]
related report from another repo: https://github.com/driftyco/ionic/issues/4212
I reproduce this on ionic@1.7.14

**Comment by dzlatic** [comment]
Same issue in 1.7.16

**Comment by mbrookson** [comment]
@mlynch @mhartington This still happens on Windows with ionic@beta as of when I am posting this

**Comment by aymen-mouelhi** [comment]
@mhartington the solution I found is to completely delete the platforms folder and re run add platform ios then build
