### ISSUE TITLE
bug: ionic upload adds malformed UTF-8 BOM to index.html and changes Content-Security-Policy tag

### ISSUE THREAD

**Issue by waynebloss** [driftyco/ionic#4220]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After I ran `ionic upload` for my project, it changed the top of my `index.html` file from this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-eval' 'unsafe-inline' *">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>
```

to this:

```html
&#xFEFF;<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src &apos;self&apos; &apos;unsafe-eval&apos; &apos;unsafe-inline&apos; *">
    <!-- ... -- >
```

`index.html` is already encoded in UTF-8 without BOM and it didn't change any of the other files which are encoded the same way. So, I have a few questions:

- Should `index.html` or any other html file have a BOM?
- Is the new Content-Security-Policy correct?
- What should I do, if anything?

This is on Windows 10. I can try it on OS X and other various Unixes too, but I'll see what shows up here first. Thanks.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-cli#562
