### ISSUE TITLE
bug: PushPlugin makes Android build fail every time !

### ISSUE THREAD

**Issue by JerryBels** [driftyco/ionic#4225]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I wanted to sanitize my app with last versions of everything, so I created a new Ionic project, right after updating Ionic and Cordova CLIs. Then I encountered a big bug with the pushPlugin. Here is how to simply reproduce :

OS : Windows 7 64 bits
Cordova : 5.1.1
Ionic : 1.6.4

    ionic start myApp blank
    cd myApp
    cordova plugin add https://github.com/phonegap-build/PushPlugin.git
    ionic platform add android
    ionic build android

Note it doesn't matter if the plugin is added before or after the platform. Build fails anyway with the following error :

	FAILURE: Build failed with an exception.

	* What went wrong:
	A problem occurred configuring root project 'android'.
	> Could not resolve all dependencies for configuration ':_debugCompile'.
	   > Could not find any version that matches com.android.support:support-v4:+.
		 Searched in the following locations:
			 https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
			 https://repo1.maven.org/maven2/com/android/support/support-v4/
		 Required by:
			 :android:unspecified

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug
	option to get more log output.

	BUILD FAILED

	Total time: 4.364 secs

	C:\Users\retraite plus\tmp\myApp\platforms\android\cordova\node_modules\q\q.js:126
						throw e;
							  ^
	Error code 1 for command: cmd with args: /s /c ""C:\Users\retraite plus\tmp\myApp\platforms\android\gradlew" cdvBuildDebug -b "C:\Users\retraite plus\tmp\myApp\platforms\android\build.gradle" -Dorg.gradle.daemon=true"
	ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

	You may not have the required environment or OS to build this project
	Error: cmd: Command failed with exit code 1
		at ChildProcess.whenDone (C:\Users\retraite plus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
		at ChildProcess.emit (events.js:110:17)
		at maybeClose (child_process.js:1015:16)
		at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

Thanks ahead for fixing this asap !</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-service-push-client#22

**Comment by mhartington** [comment]
It seems that the old push-plugin is being depreciated for a newer plugin. We're in the process of migrating everything to this new plugin. Shouldn't be too long for support.

**Comment by paulogr** [comment]
Are you using the Facebook plugin too?

I know about an incompability issue with facebook and push plugins.

Hope it helps!

**Comment by JerryBels** [comment]
@mhartington yes, the newer plugin is way better, but I didn't want to migrate already since ngcordova didn't yet.

@paulogr that's true, there WAS an incompatibility between them too, I experienced it in the past. But as I said, you can reproduce this bug very simply by simply adding only the push plugin.
