### ISSUE TITLE
perf: Spinner 'process' doesn't stop with ng-if false

### ISSUE THREAD

**Issue by felquis** [driftyco/ionic#4228]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>This bug was crashing my Android app after showing 3 spinners, the process continue even if the view is not in the DOM anymore, probably an infinite-loop.

To simulate it just open this codepen http://codepen.io/felquis/pen/GJLjzE in debug mode http://s.codepen.io/felquis/debug/GJLjzE? open the Timeline tab of your DevTools and start recording it until 10% then stop it, you'll notice a bunch of yellow lines in the timeline, but these lines shouldn't be there cause there's nothing to render in the screen in this state.

Screen shot http://cl.ly/image/0L2F2u3H2T2b

I tried to fix it with destroy but I couldn't figure out how it works, here're some tries with a broadcast event that starts and pauses the spinner. But doesn't work as expected as well https://github.com/felquis/ionic/pull/1/files 

When there's nothing to render, the spinner must be `paused`</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
I see... the Android spinner is a bit special. I'll look in to this. In the meantime, using another spinner should be fine.

**Comment by felquis** [comment]
The iOS spinner also keep running forever, but it doesn't increase memory like Android's spinner. It's ~probably~ wasting performance in transition for example.

I'll look at an alternative with CSS Spinners, back to Ionicons 1.0

**Comment by felquis** [comment]
Related to #3583 #3454

**Comment by mlynch** [comment]
Should be fixed by: 9f341a8ccb3829ccb5a02797bd44ec301f6bb14f. Let me know if that's not the case.
