### ISSUE TITLE
bug: Opening keyboard pushes window up (WKWebview)

### ISSUE THREAD

**Issue by woniesong92** [driftyco/ionic#4230]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>My environment: WKWebview with Meteor Ionic.
Here's related keyboard code: https://github.com/meteoric/meteor-ionic/blob/ea7f80a26603e2cf769181bc2ea75ecf730f1052/components/ionKeyboard/ionKeyboard.js

The huge problem I am having right now is that the entire screen scrolls down (or the header pushes up) briefly when the keyboard opens. This happens when the input field is at the bottom of screen and the field is attached to right above the keyboard when it's opened.

Here's a video: https://www.youtube.com/watch?v=McBuwu5Ef78

Do you mind taking a look at this and see how I can fix this?

This is how I modified the above code (ionKeyboard) to attempt to fix this.

```
window.addEventListener('native.keyboardshow', function (event) {
  $('body').addClass('keyboard-open');
  var keyboardHeight = event.keyboardHeight;
  // Attach any elements that want to be attached
  var $footer = $('.inline-comment-footer');
  var $scroller = $('.ionic-scroll');
  $footer.velocity({
    bottom: keyboardHeight
  }, {
    duration: 200
  });
  $scroller.velocity("scroll", {duration: 400, offset: -100});
```

I still can't prevent the "header-going-up" effect. I will appreciate your help very much.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @woniesong92!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4230). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4230)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Disable scrolling with the keyboard plugin.

https://github.com/driftyco/ionic-app-base/blob/master/www/js/app.js#L18

**Comment by woniesong92** [comment]
@mhartington Thank you! Unfortunately I already have that...

```
Meteor.startup(function () {
  if (Meteor.isCordova) {
    IonKeyboard.disableScroll();
  }
});
```

```
  disableScroll: function () {
    if (Meteor.isCordova) {
      cordova.plugins.Keyboard.disableScroll(true);
    }
  },
```

Does it not work with WkWebkitView?

**Comment by mhartington** [comment]
Hmm, we're not using WKWebview atm cus its pretty broken, so I haven't tested it. 
But the way that works with scroll events, which changed in WKWebview, so it may be broken for that.
Will have to look into it and test it out. Which wkwebview plugin did you use?

**Comment by woniesong92** [comment]
Thank you so much. I used https://github.com/practicalmeteor/meteor-wkwebview

**Comment by mhartington** [comment]
Hmm, just gave it a try using the plugin, but I couldn't replicate it.

https://youtu.be/0L4KcWjXZVA

It could be an issue (since your using meteor-ionic) where they have an outdated version of ionic in their code.

**Comment by woniesong92** [comment]
Can you try it with an input field at the bottom of screen?

**Comment by mhartington** [comment]
Hmm, tried again with a long list of inputs, as soon as I added 

```
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.disableScroll(true);
    }
  });
})
```
It worked without any issues. 
Not sure if this is meteor specific. 
Closing as I wasn't able to replicate.

**Comment by woniesong92** [comment]
@mhartington Sorry, for the last time, could you try to replicate with an input field that's attached with `keyboard-attach` to the footer? I apologize for not being able to provide source code because I am using Meteor.

**Comment by aesmon** [comment]
@woniesong92 Sorry for reviving an old issue, but I am experiencing the same thing. Have you tried Meteor 1.3 beta with WKWebView? I am unable to get the keyboard work properly as it always pushes the webView up. Thanks
