### ISSUE TITLE
bug: Keyboard not appearing for input fields

### ISSUE THREAD

**Issue by SureshAmudalapalli** [driftyco/ionic#4237]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm building the native mobile app using ionic framework. And I've a login form and while testing it in iOS emulator(default to latest OS version), keyboard is not appearing to fill the form information. Initially, it worked and it stopped working suddenly. I upgraded ionic framework to verify the issue got fixed or not but it's still remains as an issue.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Press `cmd-k` in the iOS simulator. This is setting for the simulator.

**Comment by SureshAmudalapalli** [comment]
Thank you, it worked.
