### ISSUE TITLE
perf: Collection-repeat freeze navigation to child view

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#4245]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>In my template, I have an `<a>` directive to navigate to a child view `#/tab/feed`.  When collection-repeat is used, there's always 1-3 seconds delay/freeze before advancing to the child view after tapping on "See all".  Navigating from the child view back to this view also have 1-3 seconds delay.

If I removed the collection-repeat section, everything works fine.

I read that there's performance issue with collection-repeat and it seems to be fixed and not related to my example.  But I'm pretty sure the culprit is collection-repeat.
https://github.com/driftyco/ionic/issues/3194

Here's snippet of my template.

    <ion-view view-title="Home">
        <ion-content>
            <ion-item class="item item-divider">
                Most recent
                <span class="item-note">
                    <a href="#/tab/feed" style="color: #387ef5; text-decoration: none;">See all</a>
                </span>
            </ion-item>
            <div collection-repeat="post in posts" item-width="33%"
                 item-render-buffer="10"
                 style="padding: 0px" class="col col-33">
                <div style="background-image:url({{ post.images[0].image_url }});
                            background-repeat: no-repeat;
                            background-size: cover;
                            background-position: center;
                            width: 100%;
                            height :0;
                            padding-top: 100%;">
                </div>
            </div>
        </ion-content>
    </ion-view>

<span is-issue-template></span>

**Comment by 5amfung** [comment]
The problem is reproducible on ios 8 simulator.  Desktop browser is working fine.

**Comment by Poordeveloper** [comment]
I have the same issue with ionic 1.1.0 on android 4.4.2 webview

**Comment by Ionitron** [comment]
Greetings @5amfung!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
