### ISSUE TITLE
perf: ng-repeat works better than collection-repeat with less items

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#4248]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Could you check it out the performance of collection-repeat? I would like the same performance of ng-repeat (no frames shown) when it has 20 items. Probably something in the collection-repeat code causes these little lag frames when we scroll up/down.

My configuration is the following:

- jsscrolling enabled
- Nexus 4. Android 5.X

```js
<ion-list>
        <ion-item collection-repeat="item in data track by item.id" ng-click="somefunction()">
          <my-directive item="item"></my-directive>*
        </ion-item>
</ion-list>
```

*my-directive: It has a watch with the item and only contains two strings and two buttons. But the directive is not the problem because I added the directive code inside of ion-item and do the same. It has not filters. I removed the content and I added some random on it as 'adasdsd' too. :D.

@perrygovier @mlynch @mhartington @ajoslin</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @danicomas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4248). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4248)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by danicomas** [comment]
Line 50728 ionic.bundle.js 
// NOTE(ajoslin): this may sound crazy, but calling any other functions during this render
// loop will often push the render time over the edge from less than one frame to over
// one frame, causing visible jank.
// DON'T call any other functions inside this loop unless it's vital.

**Comment by danicomas** [comment]
http://forum.ionicframework.com/t/would-be-possible-create-a-collection-repeat-directive-with-react/30771

**Comment by danicomas** [comment]
Look at this in an Android device (nexus 4 + chrome browser): http://devblog.orgsync.com/react-list/ (the performance is very nice with many rows)

**Comment by danicomas** [comment]
this example running with phonegap + iscroll5 infinite (similar than collection-repeat) is really fast: http://lab.cubiq.org/iscroll5/demos/infinite/

**Comment by danicomas** [comment]
After a lot of test the problem is the js scroll. It causes a lot of lag in the lists. When will we able to use native scroll in collection-repeat?

**Comment by mhartington** [comment]
@danicomas so what are you trying to do exactly? I'm just a bit confused by what you're trying to report here. Do you have a codepen I could look at? Also, clearly state what this issue is please

**Comment by Ionitron** [comment]
Greetings @danicomas!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @danicomas!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by vahidvdn** [comment]
+1

I have the same problem.

> ng-repeat works better than collection-repeat with less items
