### ISSUE TITLE
docs: $99/yr for iOS testing is not required anymore

### ISSUE THREAD

**Issue by mohsen1** [driftyco/ionic#4253]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>http://ionicframework.com/docs/guide/testing.html</span>

<span is-issue-template></span>

**Comment by chrismark** [comment]
Do you use macbuildserver?

**Comment by mhartington** [comment]
@mohsen1 Please explain?

**Comment by mohsen1** [comment]
It's XCode 7 and above's feature. Please refer to [this StackOverflow answer](http://stackoverflow.com/a/4952845)

**Comment by Telemakhos** [comment]
> Xcode 7 and Swift now make it easier for everyone to build apps and run them directly on their Apple devices. Simply sign in with your Apple ID, and turn your idea into an app that you can touch on your iPad, iPhone, or Apple Watch. 

The new [Xcode 7](https://developer.apple.com/xcode/) allows "sideloading" a la Android. Just sign in with your Apple ID and install the apps in your devices, all external to the appstore. No need to pay $99 for testing anymore...

https://developer.apple.com/xcode/downloads/

**Comment by mhartington** [comment]
Oh good to know, thanks for pointing that out. Would you mind making an issue on the ionic-site repo for this? That would be a better place for it. Closing for now.

**Comment by mohsen1** [comment]
@mhartington I use [GitHub issue mover](https://github.com/google/github-issue-mover) to move issues to proper repos. Give it a shot, works flawlessly for me! :)
