### ISSUE TITLE
bug: Bug in jQueryLikeParamSerializer

### ISSUE THREAD

**Issue by marcs84** [driftyco/ionic#4257]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The $httpParamSerializerJQLike function does not return a correct serialization when the object to be serialized contains an array of objects.

Example:
Ionic code

var params = {
			width:1680, 
			height:1050,
			array: [
			        {
			        	entry1: 'is',
			        	entry2: 'bug'
			        }
			]
		};
		
		console.log($httpParamSerializerJQLike(params));

Result
array%5B%5D%5Bentry1%5D=is&array%5B%5D%5Bentry2%5D=bug&height=1050&width=1680

Jquery code

console.log(jQuery.param( params ));

Result
width=1680&height=1050&array%5B0%5D%5Bentry1%5D=is&array%5B0%5D%5Bentry2%5D=bug

As can be seen in the version ionic array missing the index and this causes problems on the server side for the reconstruction of data

My fix
File: ionic.bundle.js
Row:18039

this.$get = function() {
    return function jQueryLikeParamSerializer(params) {
      if (!params) return '';
      var parts = [];
      serialize(params, '', true);
      return parts.join('&');

      function serialize(toSerialize, prefix, topLevel) {
        if (toSerialize === null || isUndefined(toSerialize)) return;
        if (isArray(toSerialize)) {
          forEach(toSerialize, function(value, key) {
            serialize(value, prefix + '[' + key + ']');
          });
        } else if (isObject(toSerialize) && !isDate(toSerialize)) {
          forEachSorted(toSerialize, function(value, key) {
            serialize(value, prefix +
                (topLevel ? '' : '[') +
                key +
                (topLevel ? '' : ']'));
          });
        } else {
          parts.push(encodeUriQuery(prefix) + '=' + encodeUriQuery(serializeValue(toSerialize)));
        }
      }
    };
  };

I replaced this
if (isArray(toSerialize)) {
          forEach(toSerialize, function(value) {
            serialize(value, prefix + '[]');
          });
        }
in
if (isArray(toSerialize)) {
          forEach(toSerialize, function(value, key) {
            serialize(value, prefix + '[' + key + ']');
          });
        }

I hope I was helpful.
Greetings
Marco Casaburi</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcs84!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
