### ISSUE TITLE
bug: DragContent on top IonicList broken

### ISSUE THREAD

**Issue by fkbart** [driftyco/ionic#4267]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>When you test this codepen: http://codepen.io/anon/pen/rVXyvp?editors=0011

on Phone you will see that once you try to swipe right (or drag a content) to open up the side menu it does not work. 

But if you go on and remove option button TAG in codepen , dragContent works fine. 

I have created forum post as well why it is failing:
 - one of the condition evaluates differently.

http://forum.ionicframework.com/t/ioniclist-drag-content-bug-codepen-provided/31097

Already discussed with mike on slack and he confirmed that this is a bug.</span>

<span is-issue-template></span>

**Comment by fkbart** [comment]
Any news on this ?

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by fkolar** [comment]
Hello, on the latest I am using I still can not swipe left to right in order to show side menu

**Comment by jgw96** [comment]
@fkolar Would you mind putting up a codepen so that i can compare it to the above codepen? Thanks !

**Comment by fkolar** [comment]
Hi Justin, 
Not sure if I understand what is wrong on above codepen ? When I test now on iPhone I can not get to the side bar when I swipe. 

Even when I change version 1.1.1 the result is the same. 

THakns, 
Frank

**Comment by jgw96** [comment]
Yep, thats the issue! You cant seem to open the side menu when swiping on the list. Is that the same issue you are having? And is your code similar?

**Comment by fkolar** [comment]
Yeap. on the list. And the above original codepen just shows it and the whole problem started from similar usecase. 
I found its only a problem of the list. When I set the list to  have only 1 item and do swipe under the list the side menu shows up.

**Comment by jgw96** [comment]
Ok awesome, thanks for the info!

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
