### ISSUE TITLE
bug: Splash Screen on iPad with orientation locked

### ISSUE THREAD

**Issue by marcvanh** [driftyco/ionic#4271]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>When the Orientation preference config is set to "portrait", Ionic does not create landscape splash screens (as mentioned here: http://ionicframework.com/docs/cli/icon-splashscreen.html). However, an iPad locked to landscape mode will display the landscape splash screen of an app on launch - even if that app is locked to portrait. This causes the default Cordova splash screen to appear on launch.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, just tested this out with a fresh project, set the project to portrait, then created the splash screens. Locked my iPads orientation to landscape, but when I launched the app, it launch with the portrait splash screen. 

Not sure there's too much we could do about this though, it's more of a cordova specific issue.
You might want to post and issue on their issue tracker. 
http://cordova.apache.org/

Closing this.
