### ISSUE TITLE
bug: Focused input not centered in view without scroll

### ISSUE THREAD

**Issue by alexanderwallin** [driftyco/ionic#4274]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a sign in view with a vertically centered form. The view should not be scrollable, but the inputs centered on screen when focused and the keyboard is open. This is the basics of the view:

```
<ion-view title="Sign in" cache-view="false" ng-controller="SignInCtrl">
  <ion-content scroll="false">
    <!-- Stuff -->
    <div class="signInForm">
      <label class="item item-input">
        <input type="email" placeholder="Email" autocapitalize="off" autocorrect="off" spellcheck="false" ng-model="user.email">
      </label>
      <label class="item item-input">
        <input type="password" placeholder="Password" autocapitalize="off" autocorrect="off" spellcheck="false" ng-model="user.password">
      </label>
    </div>
    <!-- Other stuff -->
  </ion-content>
</ion-view>
```

I'm using the Ionic keyboard plugin.

The inputs were centered in 1.0.0-rc.2 and backwards, but now the only way I can recreate the desired behaviour is by setting `<ion-content has-bouncing="false">` and calling `cordova.plugins.Keyboard.disableScroll(true);` in my controller, but the scroll/transition is not at all as smooth as the native one previously doing the job.

Is there a better solution?

**Steps to reproduce:**

1. Start a new Ionic project
2. Add an input to the bottom of the Dashboard view. Set `scroll="false"` on the `<ion-content>`.
3. Call `cordova.plugins.Keyboard.disableScroll(false);` in app.js
4. Run the app on device. The input is hidden behind the keyboard when focused.
5. Change Ionic version in bower.json to 1.0.0-rc.2, run `bower install` and rerun the app.
6. The view is adjusted to have the input vertical centered</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @alexanderwallin!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4274). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4274)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by alexanderwallin** [comment]
This might not be a bug, but a feature, depending on how you look at it. :)

**Comment by mhartington** [comment]
Yeah, this is more of a feature if anything. Since scrolling is disabled, we don't want to override this. Only option really is to enable scrolling in the ion-content

**Comment by alexanderwallin** [comment]
Thanks for the quick response, @mhartington!

I'm wondering – since this was a feature that broke (I'm guessing with https://github.com/driftyco/ionic/commit/70576d9 in 1.0.0-rc.3) – was native view scrolling on keyboard open disabled by purpose in order to make keyboard behaviour stable?

**Comment by mhartington** [comment]
I believe so. Keyboard land is more of @tlancina, so he would know best
