### ISSUE TITLE
feat: feature: Add event for when nav-bar is finished setting active/cached 

### ISSUE THREAD

**Issue by djett41** [driftyco/ionic#4276]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a [plugin](https://github.com/djett41/ionic-scroll-sista) inspired by headerShrink that relies on the active/cached attribute values for nav-bar.  It doesn't seem that there is a reliable way of knowing when the nav-bar is finished animating and setting active/cached, which can sometimes lead to unexpected results when trying to grab a reference to both the active and cached nav-bar.  

It would be great if we had an event we could listen to when the nav-bar is finished setting these values. </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @djett41!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4276). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4276)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
@djett41 the view lifecycle events would work for this.

**Comment by djett41** [comment]
Thanks for the response @mhartington .  I believe I tried initializing active and cached on `afterEnter` and looked into the code and saw the following order of execution which cause inconsistent results.... I could be wrong though, I'll mess with it again tonight

 - in viewSwitcher function transitionComplete, the switcher emits `after` which in the case of a view entering will `$ionicView.enter`, and then `$ionicView.afterEnter` in that order
- As one of the last steps, `triggerTransitionEnd()` from the navBarController is called on each navBar instance which will eventually invoke transitionEnd, the function that correctly sets the active/cached headers.

Since navBar.triggerTransitionEnd is triggered after the `afterEnter` event, I wasn't able to use that life cycle event, which if I'm not mistaken is the last life cycle event called.

**Comment by mhartington** [comment]
Well all those events are async, just a heads up.

So what's the situation that you're having trouble with? I've made a few plugins that utilize the view lifecycle events, one which effects the cached and active header bar, and they've been effective for me.

**Comment by djett41** [comment]
So the Issue I'm having is reliably getting the active and cached nav-bars.  In my [plugin](https://github.com/djett41/ionic-scroll-sista) I need to know which header is active and which is cached, and treat them differently.  

The issue I'm seeing while debugging is that the viewSwitcher emits the `after` life cycle events before the triggerTransitionEnd is called on the nav-bar (Lines 262 - 277 in viewSwitcher).  So even when I listen to the $ionicView.afterEnter event, my callback gets called before the nav-bars are set with the correct cached/active values in transitionEnd (line 328 in navBarController)

As a workaround I ended up setting a $timeout in my $ionicView.afterEnter callback, but I suppose one of the following would fix the issue
  
  1.  make lifecycle events for the nav-bar such as `$ionicNavBar.afterEnter` etc...
  2.  emit the after lifeCycle events *after* the calls to navBar instances triggerTransitionEnd

For example, since the nav-bar code is sync, perhaps you could move the code up in transitionComplete like..

```javascript
      function transitionComplete() {
            if (transitionComplete.x) return;
            transitionComplete.x = true;

            enteringEle.off(TRANSITIONEND_EVENT, completeOnTransitionEnd);
            $timeout.cancel(enteringEle.data(DATA_FALLBACK_TIMER));
            leavingEle && $timeout.cancel(leavingEle.data(DATA_FALLBACK_TIMER));

            // Execute nav-bar completion code (sync), before emitting after events!
            // tell the nav bars that the transition has ended
            $ionicNavBarDelegate._instances.forEach(function(instance) {
              instance.triggerTransitionEnd();
            }); 

            // emit that the views have finished transitioning
            // each parent nav-view will update which views are active and cached
            switcher.emit('after', enteringData, leavingData);

            // resolve that this one transition (there could be many w/ nested views)
            deferred && deferred.resolve(navViewCtrl);

            // the most recent transition added has completed and all the active
            // transition promises should be added to the services array of promises
            if (transitionId === transitionCounter) {
              $q.all(transitionPromises).then(ionicViewSwitcher.transitionEnd);
              switcher.cleanup(enteringData);
            }        

            // remove any references that could cause memory issues
            nextTransition = nextDirection = enteringView = leavingView = enteringEle = leavingEle = null;
      }
```

**Comment by avainola** [comment]
I have similar issue. 
When i use $ionicNavBarDelegate.align() in afterEnter function:
$scope.$on('$ionicView.afterEnter', function() {
    $ionicNavBarDelegate.align('left');
});
Result is that the nav-bar="cached" gets the title aligned to te left instead of nav-bar="active".
Routing is based on the ionic sidemenu template.

**Comment by jgw96** [comment]
Hello! Are you all still experiencing this issue?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again
