### ISSUE TITLE
bug: $ionicView.leave not fired on deep state change

### ISSUE THREAD

**Issue by ashconnell** [driftyco/ionic#4284]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If i'm on a route `app.main.detail` where the `main` template contains the `ion-nav-view` and `detail` contains the `ion-view` and the `detail` controller watches the leave event `$scope.$on('$ionicView.leave', onLeave)` and I route away to the state `app.tour` using:

    $ionicHistory.nextViewOptions({
        disableAnimate: true,
        disableBack: true,
        historyRoot: true
    });
    $state.go('app.tour');

Then the `$ionicView.leave` event isn't fired. This is essential in my case as i need to be able to disable hardware back button intercepts, but instead they persist and get fired on the tour state.</span>

<span is-issue-template></span>

**Comment by sicter** [comment]
+1

**Comment by plevie** [comment]
+1

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
