### ISSUE TITLE
bug: Bug: iOS Input in popup hidden by keyboard (Ionic Keyboard)

### ISSUE THREAD

**Issue by cmellinas** [driftyco/ionic#4293]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>
Hello,

When using ionic Keyboard with cordova.plugins.Keyboard.disableScroll(true);

And using the Ionic doc Popup (first example) : http://ionicframework.com/docs/api/service/$ionicPopup/

There is an issue with the input only on IOS, the keyboard hides the input (it's not the case for modals or views inputs, only for popups).

Temporary solution : using cordova.plugins.Keyboard.disableScroll(false) when the popup show
And reuse cordova.plugins.Keyboard.disableScroll(true) when the popup is closed

I use the last plugins versions (ionic 1.1.0 and Keyboard 1.0.5)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mellinas!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4293). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4293)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jwt02180** [comment]
Hi,

I am using iOS 9.1 webview.

I also have the ionic Keyboard plugin configured the same way, and the $ionicPopup with an input is hidden by the keyboard. I do not have this issue on android.

I have come to the same temporary solution as @mellinas, which is undesirable as it makes the whole view (nav-bar included) scroll-able while the popup is open.

I'm using ionic v1.1.0 and Keyboard v1.0.6

**Comment by bdoooh** [comment]
I'm also experiencing this bug, using the same fix as @cmellinas as well.

**Comment by jordantomax** [comment]
+1

**Comment by tgensol** [comment]
+1

**Comment by johnnyoin** [comment]
If found a less undesirable way to work around this issue by manually moving the popup when the keyboard appears:

JS:
```javascript 
if (cordova.platformId === 'ios') {
   window.addEventListener('native.keyboardshow', function () {
      movePopupFromContainerList(document.getElementsByClassName('input-popup popup-container'), true);
   }
   window.addEventListener('native.keyboardhide', function () {
      movePopupFromContainerList(document.getElementsByClassName('input-popup popup-container'), false);
   }

   function movePopupFromContainerList(list:NodeList, up:boolean) {
      if (list.length) {
         var popup = list[0].childNodes[0];
         popup['style'].bottom = up ? '130px' : '0px';
      }
   }
}

this.$ionicPopup.prompt({
   title: ...,
   ...,
   cssClass: 'input-popup'
});
```

CSS:
```css
.platform-ios {
  .input-popup.popup-container .popup {
    position: relative;

    -webkit-transition: bottom 0.3s ease-in-out 0s;
    transition: bottom 0.3s ease-in-out 0s;
  }
}
```

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by johnnyoin** [comment]
@jgw96 Yes this is still an issue.

**Comment by AdrienDC** [comment]
+1, super annoying ...

**Comment by przemkow** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @cmellinas!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by jordantomax** [comment]
Still a problem, please reopen.

**Comment by slorber** [comment]
+1

**Comment by douglasjunior** [comment]
+1

**Comment by luco** [comment]
+1

**Comment by marcioibm** [comment]
+1

**Comment by wcustodio** [comment]
+1

**Comment by BraveVN** [comment]
+1

**Comment by mashah1** [comment]
Hi All, I am also facing same issue, when popup is shown, the keyboard gets opened which hides the input field. Any solution please? Thanks

**Comment by suiz0** [comment]
Same issue, is this fixed?

**Comment by ivelfan** [comment]
Still occured..

**Comment by BraveVN** [comment]
@Ionic team: Are you guys still working with it ?

**Comment by sminthsonth** [comment]
it is definitely an issue, +1

**Comment by alexgalkin** [comment]
Issue is still valid

**Comment by Rambatino** [comment]
@jgw96 can this be reopened as it is still an issue

**Comment by lehresman** [comment]
@ivelfan has the right solution.  This worked like a charm.  Thanks!

**Comment by Nightbr** [comment]
This is still an issue in ionic 1.3.2
@ivelfan's fix should be add to the ionic main CSS ?

**Comment by AshleyDeng** [comment]
In most cases, using Ionic is a pleasant. But when it comes down to some minor yet annoying bugs, sometimes it would not be fixed or acknowledged. Another example is [iOS input cursor bugs](https://github.com/driftyco/ionic-plugin-keyboard/issues/228).

Frustrated indeed.

**Comment by einzwei** [comment]
did someone found a workaround to fix this ?

**Comment by pavelety** [comment]
.platform-ios.keyboard-open .popup-container {
        padding-top: 50px;
        align-items: flex-start;
}

**Comment by sohandhaindwal** [comment]
Same issue is here. I have study on that but not correct solution for that. I see Ionic team not notice that point. I found that ionic UI is not good for IOS , lot of issues are coming in IOS. very bad experience with ionic . from last two month I am find the that issue solution but .......Somebody have any solution. please help me my app almost complete but without that its not done . I am using ionic1. I am set chat input into footer bar when i focus on input then keyboard covered my input . Please help me. ionic team please fixed that issue.

**Comment by DenisTis** [comment]
The solution proposed does not solve the issue completely:
.platform-ios.keyboard-open .popup-container {
padding-top: 50px;
align-items: flex-start;
}


Once keyboard is displayed, it puts additionally whole "view-container" to the top, overlaying ios toolbar with battery indicator, etc.
Once keyboard is hidden, "view-container" does not come back and stays overlayed. Very annoying.
