### ISSUE TITLE
bug: Wrong stack management of async popups

### ISSUE THREAD

**Issue by dhyegofernando** [driftyco/ionic#4299]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi there,

When I use multiple popups just as usual (outside any kind of async fn) the popup stack works great but when I try to use the both way, the popups get weird because they can't be closed.

To explain my self better here's the code: http://jsbin.com/fofasuresi/1/edit?html,css,js,console,output

Any idea about that?

Thanks in advance.</span>

<span is-issue-template></span>

------------------------

**Edit:**
I compared the last release version [v1.1.0](https://github.com/driftyco/ionic/blob/v1.1.0/js/angular/service/popup.js#L421) (which has the bug) and the version [v1.0.0-beta.11](https://github.com/driftyco/ionic/blob/v1.0.0-beta.11/js/angular/service/popup.js#L403) (which hasn't) so I could resolve in the following way:

https://github.com/dhyegofernando/ionic/commit/ae5fc66201b687da866f53b0bec70118a85e34c4

**Comment by dhyegofernando** [comment]
Is it just me? Someone else? Please...

**Comment by stefanmdt** [comment]
same here, any news on that?
