### ISSUE TITLE
Platform classes and when they are available

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#4307]
I wanted to test platform classes so inside my $ionicPlatform.ready block in the run area, I added:

    console.log(document.body.classList.contains('platform-browser'));
    console.log(document.body.classList);

I noticed this returned an empty set. If I use the same code in a controller, it works right. So there is some race condition happening here, but I think this seems like a bug. If run() is being fired, and $ionicPlatform.ready, then surely the classes should be ready for inspection then, right?

**Comment by mlynch** [comment]
the platform detection must be running after that. Adding to 1.2 to see if we can/should fix this.

**Comment by jgw96** [comment]
Hello @cfjedimaster are you still seeing this issue with the latest version of ionic 1 (1.3.0) ?

**Comment by cfjedimaster** [comment]
Looks fixed - thanks!

**Comment by jgw96** [comment]
Awesome! Nice to hear.
