### ISSUE TITLE
bug: Windows 8.1 Chrome works with touch but not click and drag

### ISSUE THREAD

**Issue by EMCP** [driftyco/ionic#4310]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I've posted this issue to StackOverflow : 

http://stackoverflow.com/questions/32361480/windows-chrome-touch-events-working-but-not-mouse-click-drag

I have an Ionic app that's being brought over for use as a desktop web application.  That means it's running itself in browsers like FireFox, IE, Chrome... etc

One thing I've noticed is, on Windows Chrome I can scroll certain elements ONLY when using the touch screen.  I cannot, for instance, click and drag the elements (which I can do just fine in OSX)

here's an oversimplification of one such element's html

```
    <ion-content ...>
       <div class="someclassyClasses ..." ...>
           <ion-scroll direction="y" has-bouncing="false" ...>
                <ion-list ...>
                    <div ng-repeat="group in groups" ...>
```

Environment is
```
    Windows 8.1
    Chrome 44.x
    HP Touch Envy Laptop
```
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @EMCP!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4310). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4310)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by EMCP** [comment]
Looks like I'm being told to try turning on NativeScrolling.  One idea I have is to do that like-so


```
// file: app.js

...

.config(function ($ionicConfigProvider) {
    
    if (customClass.isWindowsDesktop()) {
      $ionicConfigProvider.scrolling.jsScrolling(false);
    }

});
```

**Comment by EMCP** [comment]
Just tried this out, didn't seem to affect my problem.  Realizing it may be due to my use of Collections, which isn't supported by Native Scroll according to this article :

Of course, there are some caveats:

native scrolls won't work with collection-repeat;
scroll bar will disappear but can be added via CSS;
iOS has a sluggish support of native scrolls.

http://timonweb.com/posts/improve-ionics-performance-in-android-with-native-scrolls/

**Comment by clernellhn** [comment]
I am having this same issue with the boilerplate Ionic-supplied templates (tabs, etc.). 
Even before I make any changes (collection-repeat, ng-repeat, etc.), the basic lists do not drag anymore.  Even other people's codepen examples.

Also, LiveReload is not working.

All Ionic apps have no click and drag functionality on Chrome, but work on Firefox.
This started happening about the same time as this poster's problem.

Thanks

Windows 8.1 
Chrome Version 45.0.2454.93 m (64-bit)
Lenovo t440s

**Comment by mhartington** [comment]
So this is beyond the scope of what Ionic is intended for currently.

**Comment by clernell** [comment]
Got it - It's mostly for demoing.

Although I found a fix, anyway - just copied the onmouse functions next to
the ontouch function. Now it works on all devices.

Cheers
ᐧ

Colin Lernell

Product Manager
Pricing|Matching|Growth|Analytics
HourlyNerd <http://www.hourlynerd.com>
M: 416-706-5311
LI: linkedin.com/in/colinlernell
