### ISSUE TITLE
docs: How to "install" codepen examples

### ISSUE THREAD

**Issue by MartinOrtiz** [driftyco/ionic#4321]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I remember seeing a way to do something like this:
ionic start myApp [CodePen Template]
Where instead of just creating a blank, tabs, sidemenu template, 
I could create a project using one of the Ionic Codepen templates.

I have done it before but forgot how......
How is this done?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
`ionic start myApp <link to codepen exmaple>`
