### ISSUE TITLE
bug: ion-nav-view will not load

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#4326]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When my applications loads first, ion-nav-title is not loaded from ion-view and placed in navbar. After a route change everything is fine.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @appwrx, can you reproduce this in a codepen?

**Comment by Ionitron** [comment]
Greetings @appwrx!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @appwrx!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
