### ISSUE TITLE
bug: submit plugin to market - application error

### ISSUE THREAD

**Issue by igorizr1** [driftyco/ionic#4327]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello I'm trying to submit plugin to ionic market. However all the time I'm getting error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @igorizr1, we've had some issues with our form validator not catching some things it should. Could you send me a screenshot of how you have the form filled out?

**Comment by perrygovier** [comment]
Gonna close this to handle things over email.
