### ISSUE TITLE
Feature: Able to add label text inside a toggle

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#433]
E.g. so you can have
[Hot|Cold| 

At the moment the toggle is one label, with on/off, but there are many UI scenarios where you effectively have two choices..... so by putting text in the toggle this enables that (rather than having to have a 2 selection radio)

**Comment by gdl276s** [comment]
I don't agree this should be closed.  The title of the ticket is referring to "label text" inside toggle, not "value text".  It would be nice to have 2 additional parameters fed into the directive ...

ng-true-label
ng-false-label

The rendering of the toggle would be similar to http://codepen.io/tiemin/pen/yyPQyJ/
