### ISSUE TITLE
perf: Ionic app does not load correctly on Google chrome

### ISSUE THREAD

**Issue by bhage** [driftyco/ionic#4340]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I created a simple Ionic App a few days ago.  I used lists and image thumbnails.  It was loading perfectly a few days ago in Google Chrome.

Today, this app (and several other similar apps) did not load correctly in Chrome.  When I open them in Firefox, they load perfectly.

Please explain why this issue happened and how it can be resolved.

Note: I did not update or change anything on the computer.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Codepen example? Can't work off of nothing.

**Comment by Ionitron** [comment]
Greetings @bhage!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
