### ISSUE TITLE
bug: Ionic Content Scrolling bug

### ISSUE THREAD

**Issue by heysailor** [driftyco/ionic#4355]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Error message: Uncaught TypeError: Cannot read property 'indicator' of null

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.5.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.4 Build version 6E35b

Problem code: @ionic.bundle.js:5456
"self.__indicatorX.indicator.style.width = width + 'px';

- this problem is caused when a cached view is brought back into view. The scrolling area in question has settings of "direction='x', and scrollbar-x='false' " - I want no scrollbars to appear, but the area to be scrollable. It looks like this is mucking up calculation of a non existent scrollbar.</span>

<span is-issue-template></span>

**Comment by heysailor** [comment]
Having a bit more of a poke around, it looks like some of my scrolling areas are being removed from the frame. To be technical, I have a scrollable list of items in an ionic content area, each item of which has a scrollable area. There are two types of lists that are swapped in and out of the main content area. The bug occurs when the original list is put back after the second was viewed.

The list contains about 8 items in view - but the bug only comes up 4 times on the switch of the lists.

That makes me suspect that a couple of list items are being removed. While the initial check for null at the start of the '_resizeScrollbars' function is almost sufficient, a __indicatorX can become null following the 'ionic.requestAnimationFrame' call. I can fix the bug by checking for the existence of 'indicatorX' after the animationFrame has been requested:

Original code:

@ionic.bundle.js:5448
```javascript
    // Update horiz bar
    if (self.__indicatorX) {
      var width = Math.max(Math.round(self.__clientWidth * self.__clientWidth / (self.__contentWidth)), 20);
      if (width > self.__contentWidth) {
        width = 0;
      }
      if (width !== self.__indicatorX.size && self.__indicatorX.indicator) {
        ionic.requestAnimationFrame(function(){
          self.__indicatorX.indicator.style.width = width + 'px';
        });
      }
      self.__indicatorX.size = width;
      self.__indicatorX.minScale = self.options.minScrollbarSizeX / width;
      self.__indicatorX.maxPos = self.__clientWidth - width;
      self.__indicatorX.sizeRatio = self.__maxScrollLeft ? self.__indicatorX.maxPos / self.__maxScrollLeft : 1;
    }
```
Fixes the bug:

@ionic.bundle.js:5448
```javascript
...
      if (width !== self.__indicatorX.size) {
        ionic.requestAnimationFrame(function(){
          if (self.__indicatorX) {
            self.__indicatorX.indicator.style.width = width + 'px';
          }
        });
      }
...
```

...and the same for the indicatorY code.

**Comment by perrygovier** [comment]
Thanks for digging in to this so much @heysailor. Would you be able to put together an example project in codepen or a project zip that reproduces the issue?

**Comment by minhtc** [comment]
I have the same problem, temporary fixed by check self.__indicatorX as @heysailor mentioned above

**Comment by Ionitron** [comment]
Greetings @heysailor!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
