### ISSUE TITLE
bug: Swipe to go back transition sometimes gets stuck

### ISSUE THREAD

**Issue by anzovin-brian** [driftyco/ionic#4363]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Users of my app reported a bug where the back button in the nav bar would suddenly stop working, trapping them in a breakaway page. The problem was very difficult to reproduce, but I eventually did, and discovered that the issue is that the transition animation that plays when swiping to go back gets stuck, rendering the back button unpressable.

Specifically, if I dig into the element tree, I can see that the two divs with class "nav-bar-block" have an attribute called "nav-bar" that is normally set to "active" and "cached". When doing a swipe to go back, the active nav-bar-block changes to "leaving" and the cached nav-bar-block changes to "entering". Normally when I release my finger so that it cancels it the transition, they will revert back to being "active" and "cached" after the animation concludes.

...But sometimes they don't. It's tricky to reproduce, but sometimes they will stay in their transitioning state, rendering any buttons in the nav bar unpressable, including the back button. Very very short rightward swipes starting just on the screen's left edge seem to trigger this with the greatest consistency. Sometimes you can even see that the transition has stopped part way through, with a little bit of the previous page showing and the active page pushed a few pixels to the right. It's possible to get out of this stuck state by doing the swipe to go back gesture again, but that's not something my users are likely to figure out on their own.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
Hey @anzovin-brian, this sounds kinda like an iOS 9 bug that was recently fixed. Were these users on the ios beta? Are you able to share an example project that reproduces the issue?

**Comment by anzovin-brian** [comment]
This bug occurs in iOS 8.4. From the investigation I've done I think this an issue in the guts of ionic, as they're not using the default "swipe to go back" behavior.

You can use the default project created by 'ionic start' to trigger this bug. Just go to any breakaway page where you can swipe to go back and it'll be possible to trigger the bug.

**Comment by Ionitron** [comment]
Greetings @anzovin-brian!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
