### ISSUE TITLE
bug: Upgrade ionic 1.0.1 to 1.1.0 - Error: [$injector:unpr] Unknown provider

### ISSUE THREAD

**Issue by thim81** [driftyco/ionic#4377]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>While testing the upgrade of ionic from 1.0.1 to 1.10, our fully functional ionic app started throwing the following fatal error:

$$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile <- $ionicTemplateLoader <- $ionicPopup http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24ionicTemplateLoader%20%3C-%20%24ionicPopup, /lib/ionic/js/ionic.bundle.js, Line: 13243

In the 1.0.1 release there was no error complaint about this.

What could this be?
Something related to $ionicPopup? or $animate?

FULL ERROR STACK
[Error] Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile <- $ionicTemplateLoader <- $ionicPopup
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24ionicTemplateLoader%20%3C-%20%24ionicPopup
	getService (ionic.bundle.js, line 13243)
	invoke (ionic.bundle.js, line 13268)
	(anonymous function) (ionic.bundle.js, line 13099)
	forEach (ionic.bundle.js, line 9163)
	createInjector (ionic.bundle.js, line 13099)
	doBootstrap (ionic.bundle.js, line 10457)
	bootstrap (ionic.bundle.js, line 10478)
	angularInit (ionic.bundle.js, line 10372)
	(anonymous function) (ionic.bundle.js, line 37186)
	trigger (ionic.bundle.js, line 11823)
	eventHandler (ionic.bundle.js, line 12098)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @thim81!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4377). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4377)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kndol** [comment]
What is the version of AngularJS?
I have the same trouble with the version > 1.4.3.
1.4.3 has no this error.

**Comment by thim81** [comment]
I ll check but i just updated the whole ionic framework. Does this not include automatic the latest Angular version? Or do i need to update it seperatly?

**Comment by russelljjackson** [comment]
I'm having the same issue. Did you find any resolution to this?

**Comment by humbertosanchezlara** [comment]
Same problem here, any thought?

**Comment by Taylorsuk** [comment]
I'm having this issue and have asked for help here: 
http://stackoverflow.com/questions/33467245/ionic-lib-1-1-0-causing-injector-error

Any ideas?

**Comment by ravishtiwari** [comment]
@Taylorsuk I think your query has been resolved on SO, if so, you can update this defect, and close it. What do you say?

**Comment by Taylorsuk** [comment]
Closed for me. 

Thanks.
