### ISSUE TITLE
Custom back button onclick

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#438]
> When the framework (0.9.20) includes a back button in the navigation bar automatically, how to you define a function to execute when it is clicked? One use case is to present a popup and ask the user about first saving unsaved data.

http://forum.ionicframework.com/t/how-to-handle-a-click-on-the-generated-back-button/582

**Comment by nonec** [comment]
Hey there, I would also like to know, how to achieve custom behaviour for a back button

**Comment by mjw56** [comment]
Is there documentation for how to do this? I can't seem to find anything. Thanks.

**Comment by nonec** [comment]
There is no general howto, but here you can have a look at nested controllers: https://docs.angularjs.org/guide/controller

The easiest would be to have a variable in the nested controllers and check that in the parent controller. Could be an id or a name. Then dependent on the value you call different back methods.

I used it to differentiate three different types of views with three different back-button behaviours. Hope this helps.

**Comment by Jerome67000** [comment]
Hi,

I have the same problem. @nonec do you use $watch in the mainCtrl to check a variable redefined in each detailViewCtrl ?

**Comment by mobiRic** [comment]
Was this ever implemented? I see you closed it, but can't find any resolution or explanation of why it was closed.

This would be very useful functionality, especially given the strange way (for Android) you have implemented tab navigation.

**Comment by Jerome67000** [comment]
+1 Yes !

**Comment by mhartington** [comment]
Please take a look at the docs.

http://ionicframework.com/docs/api/directive/ionNavBackButton/

**Comment by mobiRic** [comment]
Thanks, Mike, I did that, but was unhappy about the requirement for custom HTML to do this. I guess I was hoping for a javascript callback, something similar to what is shown on this page: 
 - http://forum.ionicframework.com/t/how-to-handle-a-click-on-the-generated-back-button/582/5

What I have done is grab a handle to your $ionicGoBack function, and then override it for my custom implementation.  I do this inside one of my controllers:

    // override soft back button
    // framework calls $rootScope.$ionicGoBack when soft back button is pressed
    var oldSoftBack = $rootScope.$ionicGoBack;
    $rootScope.$ionicGoBack = function() {
        // implement custom behaviour here
    };

My requirement is controller specific, so I deregister the custom handle when the controller exits:

    var deregisterSoftBack = function() {
        $rootScope.$ionicGoBack = oldSoftBack;
    };

More details can be found on my related StackOverflow post:
 - [Ionic override all BACK button behaviour for specific controller](http://stackoverflow.com/questions/32231737/ionic-override-all-back-button-behaviour-for-specific-controller)

**Comment by nonec** [comment]
@Jerome67000 I think I had a solution for that problem a few month ago, but I'm not sure if I can find it or if it's still working. What I am sure about is, that is was some kind of hack and I'm really a bit confused, if this is not fixed already... 
The SO-Link as well as the documentation looks promising though.

**Comment by johnrobertcobbold** [comment]
This is how I am doing this :

1. `<ion-nav-back-button></ion-nav-back-button>` is defined in my tabs.html

2. On the specific template where I need a custom function to be executed, I insert the ion-nav-back-button again :

`<ion-nav-bar class="bar-stable">`
(...)
`<ion-nav-back-button ng-click="cancel()">Cancel</ion-nav-back-button>`
(...)
`</ion-nav-bar>`
3. and finally In the controller :
`$scope.cancel = function () {
// insert whatever you want to do;
$ionicHistory.goBack();};`
