### ISSUE TITLE
perf: Modal remove unnecessarily calls ionicClickBlock

### ISSUE THREAD

**Issue by MartinMa** [driftyco/ionic#4383]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Upon removal of an Ionic modal the method ionicModal#hide is always called (Even when no modal is visible). It shows the click-block div for a short amount of time by calling $ionicClickBlock.show(600);.

This breaks the responsiveness of the app for a short amount of time, because it can't receive any touch or mousedown events.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @MartinMa!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by MartinMa** [comment]
This is issue is still present. @mlynch please take a few minutes and check the referenced pull request I provided three month ago. It's a very easy fix with a huge impact, if you frequently remove and add Ionic modals. Thanks.

**Comment by MartinMa** [comment]
@tlancina You introduced the "prevent ghost clicks on close" fix for modals here a416c66d8aede50fcf91cc569681a6d163e37cbc. But the problem is, that the "click block div" also appears, when removing the modal while it is hidden. I think, there is no need to show a click block div, when removing a hidden modal. It affects responsiveness.

**Comment by ceoaliongroo** [comment]
I have also an issue with the $ionicClickBlock hidden the content view or the modal itself.

**Comment by tlancina** [comment]
Apologies for this one slipping through through the cracks! Re-opening.

**Comment by MartinMa** [comment]
@tlancina Thanks.

@ceoaliongroo I think it is unwise to just remove the $ionicClickBlock call. It probably has its purpose. If   it has been proven that these "ghost clicks" only appear on iOS, it may be wrapped in a check for `ionic.Platform.isIOS`.

But this issue focused on `ionicModal#remove`, that indirectly triggers a click-block-div, even when the modal was already hidden.

**Comment by ceoaliongroo** [comment]
I understood, also the intention is to keep it. But the implementation have to be improved, now is not clear what issue was solved, there is not test, as ins not clear how affect. 

I my opinion we need to do

- Code the missing test scripts for the "ghost clicks" (I did found it)
- If is only in iOS, i suggest to create a separe service,  and then filter the execution using `ionicPlatform` 

In my case the issue appear also, on a new modal, i think also is related with the animation configuration. But still not clear.

Also, i'll going to check `ionicModal#remove`

thanks

**Comment by Freundschaft** [comment]
I also have the same problem, after the modal disappears, I  have to wait for the complete time of the fade out animation before I can click underlying elements again :( any quick fix for this?

**Comment by danotrino** [comment]
You will have to create your own animation css class to increase the transition time, so it will have time enough to do the `ionicClickBlock `stuff(basically it deletes and adds the `click-block-hide` class but it takes time, 700ms roughly). Also, there's a `ionicModal `property called `hideDelay`(it's not in the docs), use it to simulate the time it takes to hide the modal(I use 100ms less than transition). This workaround should do it.

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by solarsaturn9** [comment]
This is still an issue. Please re-open and address the click-block issue. Our company uses Ionic and we recently experienced an issue where the click-block div does not remove itself when destroying a modal.

**Comment by jgw96** [comment]
Hey @solarsaturn9 ! Would you be able to make a plunker that demonstrates this issue please? Here is a template you can use: http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**Comment by solarsaturn9** [comment]
This is the issue I'm referring to
http://plnkr.co/edit/q1LuChLrrO15cjMz7EJN?p=preview

**Comment by MartinMa** [comment]
The problem is that Ionic modal always calls `hide()` in direct consequence of calling `remove`. And `hide()` activates the click-block-div. **But** Ionic doesn't need to call `hide()`, when the modal is already hidden. Do you see what I mean? When it is already hidden, Ionic can just go ahead and remove it. This is what I'm trying to explain for a few month now. ;)

@solarsaturn9 In your case `remove()` triggers another `hide()` and your event handler triggers `remove()` again an so on. It's a vicious circle.
![hide_to_infinity](https://cloud.githubusercontent.com/assets/123297/14520278/ed354e40-0223-11e6-9486-3763273a265b.jpg)
Since every call to `hide` activates the click-block-div, it just stays there forever.

The fix is easy. I'll propose a pull request.

**Comment by danbucholtz** [comment]
@MartinMa, can you show me an example of the problem we're trying to solve in a code pen or plunkr?  Or does @solarsaturn9's plunkr demonstrate it adequately?

Thanks,
Dan

**Comment by MartinMa** [comment]
@danbucholtz The plunker demonstrates part of the problem. Just add the console.log bit (see screenshot) and you'll see the problem of Ionic (in the console). This issue doesn't need a plunker. It's fairly simple to understand, when you look at the code.

Apart from that, I don't know what to say anymore. I feel like repeating myself all the time. I explained it multiple times now. I filed the issue back in September of 2015. In the meantime it has been closed twice for no reason. I have been very patient.

Please take a look at the pull request and you'll see what I mean. I'm just trying to help, but this is frustrating.

**Comment by danbucholtz** [comment]
@MartinMa, we understand your frustration.  Please understand that we get 100s of issues per week that we have to go through, so it is hard to keep up.  It isn't always clear what a PR/issue is attempting to convey.  It is much easier to understand an issue and resolve it when there is an extremely dumbed down codepen example and step by step instructions.  Remember, you know your app and use cases, we don't.

What I am trying to understand is this:

"Upon removal of an Ionic modal the method ionicModal#hide is always called (Even when no modal is visible)"

Why would you call hide when there isn't a modal visible?  I don't understand the use case.  Is this issue resolved by simply not calling hide on a modal that isn't displayed?

Please let me know and thank you for contribution.

Thanks,
Dan

**Comment by solarsaturn9** [comment]
I believe @MartinMa has stated the problem perfectly. I think he is saying that Ionic is calling ionicModal#hide while it is going through the process of removing a modal. Its not a matter of use cases. I think your confusion lies in the fact that we are referring to two different things: a hidden modal and a removed modal. Removed modal is a modal that has been completely destroyed, not hidden.

**Comment by danbucholtz** [comment]
Hi @solarsaturn9, thanks for the explanation.  I will take a look.

Thanks,
Dan

**Comment by MartinMa** [comment]
Hi @danbucholtz thanks for your effort and that you take the time to understand this issue. I hope it is clear now. I can only second what @solarsaturn9 has said.

**Comment by danbucholtz** [comment]
All,

The PR made it into 1.3.  Please let me know if you have any questions, etc.

Thanks,
Dan
