### ISSUE TITLE
bug: top and bottom black borders in ios9

### ISSUE THREAD

**Issue by mhdHussein** [driftyco/ionic#4390]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>hi everyone

after updating my iphone 6 yesterdat to ios 9 my app crashed .. I updated the cordova-plugin-wkwebview plugin to version 0.6.0 and it worked again but there are some problems.

1. the app has two black  borders  one on the top and one on the bottom
![img-20150919-wa0000](https://cloud.githubusercontent.com/assets/12625782/9974422/9553011c-5e96-11e5-9013-c5bb5bf66ee1.jpg)

2- i had defined in my css a default styles to work for normal sized devices (like the iphone)
and a media query for tablet size devices like the ipad ... everything seems to work as expected in ios 8 and 7
but in ios 9 (as you see in the picture) it seems to use the styles that are defined for the ipad !! and the picture was taken from an iphone plus 2 black borders appear on the top and bottom of the app

i am using phonegap build to build my app

and here is the preferences and the plugins in config.xml

<feature name="http://api.phonegap.com/1.0/device" />
     
    <feature name="InAppBrowser">
      <param name="ios-package" value="CDVInAppBrowser" />
    </feature>

     <feature name="SplashScreen">
        <param name="ios-package" value="CDVSplashScreen"/>
        <param name="onload" value="true"/>
    </feature>
   
  
    <preference name='phonegap-version' value='cli-5.1.1' />

    <gap:platform name="ios" />
    

    
    <preference name="orientation"                value="portrait" />
    <preference name="target-device"              value="universal" />
    <preference name="fullscreen"                 value="true" />
    <preference name="webviewbounce"              value="false" />
    <preference name="uiwebviewbounce"              value="false" />
    <preference name="DisallowOverscroll"              value="false" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="FadeSplashScreen" value="false" />
    
    <preference name="SplashScreen" value="splash" />
    <preference name="SplashScreenDelay" value="3500" />
    <preference name="prerendered-icon"           value="true" />
    <preference name="stay-in-webview"            value="false" />
    <preference name="ios-statusbarstyle"         value="black-opaque" /> 
    <preference name="detect-data-types"          value="true" />
    <preference name="exit-on-suspend"            value="false" />          
                                          
    <preference name="StatusBarOverlaysWebview" value="true" />          
    <gap:plugin name="com.ionic.keyboard" version="1.0.3" />
    <gap:plugin name="io.litehelpers.cordova.sqlite" version="0.7.6" />
    <gap:plugin name="nl.x-services.plugins.toast" version="2.0.2" />

    <gap:plugin name="org.apache.cordova.device"  />
     <gap:plugin name="org.apache.cordova.splashscreen" source="plugins.cordova.io" />
    <gap:plugin name="cordova-plugin-directions"  source="npm" />
    <gap:plugin name="cordova-plugin-wkwebview" version="0.6.0" source="npm" />

    
    <gap:plugin name="cordova-plugin-geolocation" source="npm" />
    <gap:plugin name="de.appplant.cordova.plugin.background-mode" version="0.5.0" />
    <gap:plugin name="org.apache.cordova.network-information" version="0.2.7" />
    <gap:plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" version="2.8.0" source="plugins.cordova.io" />
    <gap:plugin name="nickreed.mx.ferreyra.callnumber" source="plugins.cordova.io" />
    <gap:plugin name="nl.x-services.plugins.actionsheet" />
    <gap:plugin name="com.ohh2ahh.plugins.appavailability" />
    <gap:plugin name="org.li8.inappbrowser" version="0.1" />

     <gap:config-file platform="ios" parent="UIStatusBarHidden">
        <true/>
    </gap:config-file>
    
    <gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance">
        <false/>
    </gap:config-file>

any idea how to fix it ?
thank you</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mhdHussein!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4390). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4390)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhdHussein** [comment]
I figured it out ..
it is because for some reason the webview takes the size of the splash screen on ios 9

so I fixed the sizes of my splash screens and it worked

thank you

**Comment by jimmyrogue** [comment]
hi 
i have the same problem 
could you descriptie more?

**Comment by hirenhcm** [comment]
Please can you share the size that fixed this issue.

**Comment by swapkids** [comment]
Please describe the solution?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by ChastinaLi** [comment]
@mhdHussein The size of my splash screen is the same size of my phone. What size should I change my splash screen to....
