### ISSUE TITLE
perf: My ionic app on iOS takes up so much memory

### ISSUE THREAD

**Issue by sharataka** [driftyco/ionic#4392]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>-create app with multiple tabs
-place feed of images in tabs
-toggle between the tabs
-after a few minutes of toggling, the app crashes</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Maybe you could put together an example for us to look at. A codepen we could pull down or a git repo.

**Comment by spectravp** [comment]
This is usually due to excessively large DOMs. How many items are in your feed?

**Comment by sharataka** [comment]
I didn't mention that I'm also rendering Google Maps on one of these pages. I don't think it's due to the tabs, but rather Google Maps. I ran a test: created another app with just images in the feed without google maps and the memory usage was much better. For context, I'm including 4 600x600 pictures at a time in the feed.

Do you have thoughts on how I could minimize the memory usage while displaying Google Maps in my app? This is just a snippet of what I have in my controller for the view that has Maps...

    .controller('GuessCtrl', function($scope, $state, $stateParams, $ionicPopup, $ionicLoading, $ionicHistory) {
       $ionicHistory.nextViewOptions({
            disableAnimate: true
          });
        
        mixpanel.track("Guess page view");

        // Calculate left margin on buttons
        var buttonlength = .7 * window.innerWidth;
        $scope.left_margin = (window.innerWidth - buttonlength) / 2;
        $scope.heightWidth = window.innerHeight;

        //Click button to make a guess
        $scope.onTouch = function(item,event){
          if ($scope.coordinates == null) {
            $ionicPopup.alert({
                              title: "You haven't made a guess",
                              content: "Tap on the map to drop a pin and make a guess."
                          })
          }
          else {
            $state.go('result', { location_id: $stateParams.location_id, actual_lat:$stateParams.actual_lat, actual_lng:$stateParams.actual_lng });
          } 
        };

        $scope.initialise = function() {
          var myLatlng = new google.maps.LatLng(37.758446, -122.411789);
          var markersArray = [];

          //Initial settings for the map
          var mapOptions = {
                  center: myLatlng,
                  zoom: 2,
                  mapTypeId: google.maps.MapTypeId.ROADMAP,
                  styles: [{ featureType: "poi", elementType: "labels", stylers: [{ visibility: "off" }]}]

              };

          //Load the initial map
          var map = new google.maps.Map(document.getElementById("map"), mapOptions);

          //Event listener to add a marker      
          google.maps.event.addListener(map, 'click', function(e) {
            clearOverlays();
            placeMarker(e.latLng, map);
            $scope.coordinates = e.latLng;
            localStorage.userLat = $scope.coordinates.lat();
            localStorage.userLong = $scope.coordinates.lng();
          });

          //Actual function to add a marker
          function placeMarker(position, map) {
            var marker = new google.maps.Marker({
              position: position,
              map: map
            });
            map.panTo(position);
            markersArray.push(marker);
          }

          function clearOverlays() {
            for (var i = 0; i < markersArray.length; i++ ) {
              markersArray[i].setMap(null);
            }
            markersArray.length = 0;
          }

          $scope.map=map;

        };

        google.maps.event.addDomListener(document.getElementById("map"), 'load', $scope.initialise());

**Comment by mlynch** [comment]
Ah, thanks for the info. Going to close since it's most likely a maps issue. If anyone else stumbles on this perhaps they can help share their expertise with Gmaps

**Comment by pcsantana** [comment]
@sharataka, did you find any solution for this? I'm facing the same problem.
Thank you!

**Comment by sharataka** [comment]
@pcsantana no I wan't able to :(. I switched away from Ionic because I kept running into these memory issues...
