### ISSUE TITLE
bug: Flickering animation during navigation state changes

### ISSUE THREAD

**Issue by lehresman** [driftyco/ionic#4394]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

This ONLY happens in iOS 9 (the simulator and on my phone running through xcode), not when using a browser with "ionic serve".  It seems to work fine in iOS 8.4.  

<span ionic-description>I am seeing flickering animations between state changes.  For the longest time I thought it was my code, but this happens with the base unmodified sidemenu template as well.  See this video:

http://cl.ly/1W083M3p0P01

Notice what happens when I click on "Indie".  The reproduction steps are not consistent.  It's not just the "Indie" list item, but can happen anywhere.

It's almost like there are some extra views in the history that it's trying to animate.

Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: 5.0.1 
OS: Mac OS X Yosemite  <-- (this is not right, I'm on El Capitan)
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A220</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @lehresman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4394). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4394)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dmarcos89** [comment]
happening the same to me. hope to get a solution soon!! @lehresman

**Comment by dhirajb1989** [comment]
It is happening with me too.... too much flickering

**Comment by lehresman** [comment]
A few more details after testing it some more.  Sometimes the state change doesn't actually take effect.  For example, sometimes when I hit the Back button in the navbar, it does that flicker dance, then ends up on the same state it started on.  Clicking Back again usually works the 2nd time.

Also I can confirm this does not happen on iOS 8.4 simulator, only iOS 9 simulator and iOS 9 on my phone (iPhone 5).

**Comment by petarov** [comment]
Does this happen if you apply the [iOS9 patch](http://blog.ionic.io/ios-9-potential-breaking-change) ?

**Comment by lehresman** [comment]
Wow, thanks for the tip.  That seems to have fixed it.  I cannot get the problem to happen once that patch is applied.  Thanks!

**Comment by dhirajb1989** [comment]
Thanks a lot.... works for me too.... however one last question.... my ionic version is 1.0.0 and the patch is 1.1.1... Will you suggest me to update my ionic version to 1.1.0?

**Comment by petarov** [comment]
@dhirajb1989  I believe `1.1.1` is the version of the patch itself and not ionic. You most likely do not need to update, but that's for the ionic devs to say.
