### ISSUE TITLE
bug: Chrome Warnings

### ISSUE THREAD

**Issue by r1ckyrockz** [driftyco/ionic#4409]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've just seen this warning in Google "'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead."
Have you plan to fix this?</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This is just a general warning inside of chrome. It does not affect us in anyway (we don't use Touch.webkitRadiusX :grin: )

No issue here.

**Comment by r1ckyrockz** [comment]
Thanks mhartington for your quick answer.

Ok, i will ignore that.

P.S.:
Really? It comes from "ionic.bundle.min.js:22" ;-)
