### ISSUE TITLE
Ionic state restore fails silently

### ISSUE THREAD

**Issue by ygayl** [driftyco/ionic#4411]
Ionic state restore command fails silently.

Running the ionic state restore with an old version of cordova (3.4.0-0.1.3) in a directory that doesn't have a platforms directory doesn't return an error.

Running the command ionic build ios after that returns the following error: no such file or directory '/Users/gayly/Work/Dev/mvp-ng-ionic-tablet/platforms'

So I have added manually the platforms directory (mkdir platforms) and re-run the ionic state restore.
I now have the ios directory generated during this command within platforms.

**Comment by mlynch** [comment]
Ah, sorry about that. Mind posting here? https://github.com/driftyco/ionic-cli/issues
