### ISSUE TITLE
Clicking tab item should take user to root/home screen of the tab

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic#442]
When you go several screens deep inside a tab, and you want to get back to the home screen for that tab, you currently have to click the back button a bunch of times to get there. That's no fun, and it's not the way most native tab ux works.

We need to implement the ability to go immediately back to the root/home page for a tab simply by clicking on it, regardless of how many screens deep you are.

**Comment by SeanHub** [comment]
If you're in a nested view and do a hard refresh, pressing the tab does not take you to the root.
