### ISSUE TITLE
bug: Flickering on overscroll when native scroll activated (iOS)

### ISSUE THREAD

**Issue by guntherhoppe** [driftyco/ionic#4426]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Scenario:
- App template w/ left-hand nav menu
- JS scrolling deactivated using $ionicConfigProvider.scrolling.jsScrolling(false)
- View with a list and a few list items (so that can be scrolled) 
- List items are selectable / clickable (ng-click)

Reproduce:
- Scroll to the bottom of the list
- Tab the last or penultimate list item (so that is become activated)
- Scroll further down (overscroll) nearly same time (so that it is deactivated again) 
--> View flickers (seems the view is shortly placed at the bottom most overscroll end and back again)

Env:
- Tested on iOS 8.4 and iOS 9 (iPhone)
- Ionic v1.0.0-rc.4 and v1.1.0 / Angular v1.3.13</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @guntherhoppe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4426). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4426)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by eyurchuk** [comment]
+1, the flicker happens while opening left-hand side menu also on iOS9

**Comment by ranjitpandit** [comment]
+1, I'm seeing it too. I just upgraded to iOS 9.0.2. 
Any ideas on what could be causing this and are there any workarounds I can try?

**Comment by mhartington** [comment]
Please make sure you are includeing the ios9 patch
https://gist.github.com/IgorMinar/863acd413e3925bf282c

**Comment by ranjitpandit** [comment]
hi, thanks for the pointer. I'm running ionic 1.1.0. are you referring to this patch specifically?
https://github.com/azaslavsky/angular-ios9-uiwebview-patch
npm install angular-ios9-uiwebview-patch

**Comment by mhartington** [comment]
You don't need to npm install it. Just `bower installl angular-ios9-uiwebview-patch` and include the script tag in your index.html and and add it as a dependency

**Comment by guntherhoppe** [comment]
This is not an iOS9-only issue. The issue happend also in iOS8.4 (see my inital description). 

I have also already included the iOS9 patch, which doesn't solve the problem. 

Please reopen.

**Comment by ranjitpandit** [comment]
thanks @mhartington. the angular-ios9-uiwebview-patch worked for me and I'm not seeing the issue any more. Is it that when ionic packages a newer version of angular we will stop needed the patch?

@guntherhoppe, I had to make sure I pulled down the latest version of the ionic bundle which has Angular 1.4.3 and then include the patch.

**Comment by mhartington** [comment]
Would you be able to provide a demo or code sample that I load on a device and test out?

**Comment by guntherhoppe** [comment]
@ranjitpandit You were right. Angular 1.3.x remained on ionic lib update (on Mac). And yes, the patch worked for me too,  but this issue addresses a different problem, not bound to the iOS9 problem the patch refers to (issue happend also in iOS 8.4). 

Running now Ionic 1.1.0 with Angular 1.4.3 - Error still remains. 

@mhartington Will create a demo case for it.

**Comment by guntherhoppe** [comment]
@mhartington So - finally I got it. Here is the test case for the issue. ￼Create new app and apply the below changes. Deploy and start app on iPhone, navigate to playlists and reproduce the issue by following my "reproduce" description from above.

**Create app**
```
ionic start testApp sidemenu
```


**app.js (Disable js scrolling)**
```
.config(function($ionicConfigProvider, $stateProvider, $urlRouterProvider) {    
   $ionicConfigProvider.scrolling.jsScrolling(false);
   ...
})
```

**controllers.js (Replace PlaylistsCtrl to show more items)**
```
.controller('PlaylistsCtrl', function($scope) {
   $scope.playlists = [];
   for(var i = 1; i < 20; i++) {
      $scope.playlists.push({id: i, title: 'Item ' + i});           
   }
})
```

**playlists.html (Replace content of playlists.html)**
```
<ion-view view-title="Playlists">
  <ion-content>
    <div class="row">
        <div class="col">
            <a class="button primary">A button</a>
        </div>
    </div>	  		
      
    <div class="row">
        <div class="col">
            <small>A single line text</small>
        </div>
    </div>	  		

    <div class="list">
      <div class="item item-thumbnail-left" ng-click="" ng-repeat="playlist in playlists">
        <img src="img/ionic.png"></img>
        <div class="row"><div class="col">{{playlist.title}}</div></div>
      </div>
    </div>
  </ion-content>
</ion-view>
```

**styles.css (Add custom css)**
```
.list {
    padding-left: 15px;
    padding-right: 15px;
}
.list .item {
    border-left:0;
    border-right:0;
}
.list .item.activated {
    margin-left: -15px;
    padding-left: 120px;
    width: calc(100% + 30px);	
}
.list .item-thumbnail-left > img:first-child {
    left:0;
}
.list .item.item-thumbnail-left.activated img:first-child,
.list .item.item-avatar-left.activated img:first-child {
    left: 14px;
}
```

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by guntherhoppe** [comment]
Nop - issue still occur :(, also with ionic 1.3.1 / angular 1.5.3.
