### ISSUE TITLE
docs: Improve instructions on adding Ionic to Cordova

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#4433]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See: http://ionicframework.com/docs/overview/#cordova

Forum post: http://forum.ionicframework.com/t/where-are-the-css-and-js-files-located/33157/4

Need to add some steps on how to actually get the CSS/JS files into an existing Cordova app.</span>

<span is-issue-template></span>

**Comment by accraze** [comment]
I updated these docs https://github.com/driftyco/ionic-site/pull/320
