### ISSUE TITLE
Error ionic setup sass  with last version of nodejs 4.1.1

### ISSUE THREAD

**Issue by frendon** [driftyco/ionic#4434]
I've create a blank application with a clean and last version of nodejs.

~/p/e/helloIonic ionic setup sass
npmnpm WARN package.json helloionic@1.0.0 No README data
npm WARN package.json helloionic@1.0.0 No license field.

> node-sass@3.3.3 install ~/projects/experimentos/helloIonic/node_modules/node-sass
> node scripts/install.js

> node-sass@3.3.3 postinstall ~/projects/experimentos/helloIonic/node_modules/node-sass
> node scripts/build.js

` ~/projects/experimentos/helloIonic/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists.
 testing binary.
Binary is fine; exiting.

Successful npm install
Updated ~/projects/experimentos/helloIonic/www/index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

~/projects/experimentos/helloIonic/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (~/projects/experimentos/helloIonic/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (~/projects/experimentos/helloIonic/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/projects/experimentos/helloIonic/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:434:26)

Error running gulp sass

Exception with  (CLI v1.6.4)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v4.1.1
Xcode version: Xcode 7.0 Build version 7A220

**Comment by Ionitron** [comment]
Greetings @frendon!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4434). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4434)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by simonefalcini** [comment]
I fixed by changing in `package.json`:

from
```json
"dependencies": {
   "gulp-sass": "^1.3.3"
}
```

to

```json
"dependencies": {
   "gulp-sass": "2.1.0-beta"
}
```

and then running again `ionic setup sass`

**Comment by micrdy** [comment]
Fixed mine too. +1 for that. @Ionic-Team: gulp-sass should get upgraded. 1.3.3 is kind of outdated

**Comment by mhartington** [comment]
Fixing this tomorrow.
