### ISSUE TITLE
bug: sidemenu demo does not work on blackberry10

### ISSUE THREAD

**Issue by tnjohnston** [driftyco/ionic#4448]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Please note that this issue is only for blackberry10. I did not see a blackberry only option, so I selected "all mobile devices".

When I deploy the demo sidemenu application to a blackberry10 device or to a blackberry10 emulator, the playlist loads properly. But, when I click other links in the side menu (Search, Browse) they always display the Playlist.

Note that this problem does not occur when you run "ionic serve" and view the demo app in the Blackberry Browser.

Commands:
ionic start myApp sidemenu
cd myApp
ionic platform add blackberry10
ionic build blackberry10
cordova emulate blackberry10

I tried debugging using WebInspector. I found the following lines in the console log, although all  of these messages are classed as "information". They are not warnings or errors.

Viewport target-densitydpi is not supported. index.html:26
Apache Cordova native platform version 3.7.0 is starting. frameworkModules.js:402
Method hideKeyboardAccessoryBar for Keyboard not found frameworkModules.js:2159
Method disableScroll for Keyboard not found</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
We're not supporting blackberry10.
