### ISSUE TITLE
bug: Can't click on subheader

### ISSUE THREAD

**Issue by LeoLR** [driftyco/ionic#4450]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I've a problem with my subheader, this is a search bar and under this i've tabs. 
I can click on my tabs but not on the surch bar and i don't know why... 

That's my view: 

<ion-view title="{{navTitle}}">
	<ion-nav-buttons class="button-clear">
		<button class="button button-icon button-clear ion-arrow-left-b" ng-click="back()"></button>
	</ion-nav-buttons> 

	<ion-header-bar class="bar bar-subheader bar-positive padding item-input-inset">

		<label class="item-input-wrapper">
			<i class="icon ion-ios7-search placeholder-icon"></i>
			<input type="search" placeholder="Recherche" ng-model="searchFilter" autocorrect="off" ng-change="scrollTop()">
		</label>
		<button class="button button-clear" ng-click="searchFilter=''">
			Annuler
		</button>

	</ion-header-bar>
	
	<ion-nav-view>
		<ion-tabs class="tabs-top tabs-striped">
			<ion-tab title="Ok" class="balanced">
				<ion-nav-view name="tab-problems" class="">
					<ion-content class="">
						
						<h1>Test 1</h1>

					</ion-content>
				</ion-nav-view>
			</ion-tab>
			<ion-tab title="Warning" class="energized">
				<ion-nav-view name="tab-problems" class="">
					<ion-content class="">
						
						<h1>Test 2</h1>

					</ion-content>
				</ion-nav-view>
			</ion-tab>

		</ion-tabs>
	</ion-nav-view>
</ion-view></span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
please provide a codepen example

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @LeoLR!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
