### ISSUE TITLE
docs: The codepen link gives a 404

### ISSUE THREAD

**Issue by Matth--** [driftyco/ionic#4453]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The codepen link on http://ionicframework.com/examples/
Links to a 404 page.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hey, thanks for the heads up. Looks like the codepen site redesign changed a bunch of urls, here's what you're looking for

http://codepen.io/ionic/pens/public/?grid_type=list
