### ISSUE TITLE
bug: Dynamic ionic Tabs' navigation is broken - Ionic 1.1.0

### ISSUE THREAD

**Issue by ashwathps** [driftyco/ionic#4454]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I started a new ionic project with the "Tabs" template and made a few changes. I see that the ionic tabs navigation is broken badly. I cant navigate to the last tab. It always shows the 1st and many times the navigation gets mixed up.
Attached is project files, not much changes made to the original 'Tab' template. 
Tested on desktop and ios device.

Added 2 more states to app.js
```javascript
.state('tab.summary', {
      url: '/summary',
      views: {
        'menuContentSummary': {
          templateUrl: 'templates/summary.html',
          controller: 'SummaryCtrl'
        }
      }
    })

  .state('tab.project', {
      url: '/project/:projectId',
      cache: false,
      // templateUrl: 'templates/project.html',
      // controller: 'ProjectCtrl'
      views: {
        'menuContent': {
          templateUrl: 'templates/project.html',
          controller: 'ProjectCtrl',
        }
      }
    })
```
Tabs.html , changed to this
```html
<ion-tabs class="tabs-clear tabs-icon-only tabs-top" ng-controller="layoutTabsController">
      <ion-tab title="Summary" href="#/tab/summary">        
        <ion-nav-view name="menuContentSummary" cache-view="false"></ion-nav-view>
      </ion-tab>
      <ion-tab ng-repeat="tab in tabItems" title={{tab.name}} 
                href="#/tab/project/{{tab.path}}">
        <ion-nav-view name="menuContent" cache-view="false"></ion-nav-view>
      </ion-tab>
</ion-tabs>
```
Added this to Controller.js:
```javascript
.controller('ProjectCtrl', 
  function($scope, $rootScope, $stateParams, $filter ){
    $scope.pName = $stateParams.projectId;
})
.controller('layoutTabsController', function($scope, $rootScope){
  $scope.tabItems = [];
  $scope.tabItems.push({"name": "P0",
                    "path" : 10, "view" :"menuContent"});

  $scope.tabItems.push({"name": "P1",
                    "path" : 11, "view" :"menuContent"});

  $scope.tabItems.push({"name": "P2",
                    "path" : 12, "view" :"menuContent"});
});
```
New "summary.html"
```html
<ion-view view-title="Summary">
  <ion-content padding="false" scroll="false"  has-bouncing="true">

<div class="centerDiv">
  <div class="card">
	  <div class="item item-divider">
	    Your Favorite Projects' Summary.
	  </div>
	 
  </div>
</div>

  </ion-content>
</ion-view>
```

New "project.html"
```html
<ion-view view-title="Project  {{pName}}">
  <ion-content padding="false" scroll="false"  has-bouncing="true">

<div class="centerDiv">
  <div class="card">
	  <div class="item item-divider">
	    this is a project.
	  </div>
	 
  </div>
</div>

  </ion-content>
</ion-view>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @ashwathps!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4454). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4454)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Similar to this https://github.com/driftyco/ionic/issues/1503
