### ISSUE TITLE
bug: Infinite http request after ionic-modal close

### ISSUE THREAD

**Issue by vko-online** [driftyco/ionic#4475]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a simple app, with leaflet map, and noticed too many infinite requests when i choose location, and open ionic-modal, this might sound specific but i investigated, and totally sure ionic-modal is causing this
![screen shot 2015-10-06 at 12 33 52 pm](https://cloud.githubusercontent.com/assets/4560099/10301701/c8634bb4-6c26-11e5-94bb-b4454ac209db.png)

- 900 requests in 1-2 min, what is going on? 
- Have somebody faced same issue? 
- Should ionic-modal be disposed after close?</span>

![bug](https://cloud.githubusercontent.com/assets/4560099/10301816/ef455ab4-6c27-11e5-8e4e-6a86e9f3e9f1.gif)

Here's more informative demo, notice infinite http requests, right after ionic-modal close
![bug2](https://cloud.githubusercontent.com/assets/4560099/10301858/84dae17a-6c28-11e5-8083-1d8cd38b24b4.gif)

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vko-online!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4475). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4475)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by vko-online** [comment]
Resolved with this
```js
scope.$on('$destroy', function(){
                    if(map){
                        map.off('move');
                        map.off('dragend');
                        map.remove();
                        elem.remove();
                    }
                    Socket.removeAllListeners(defaults.internal.addEvent);
                    Socket.removeAllListeners(defaults.internal.removeEvent);
                });
```
Not sure if this was case, but now i don't get ∞ weird requests, if there's anything else to consider, please share thoughts

**Comment by OrangeClyde** [comment]
Just an idea, quite hard to be more specific on this without seeing some code, but are you using infinite scroll in your search? In this case infinite requests might occur if there's no more data too load but the infinite scroll isn't removed. It won't stop trying to fetch data. 
This could be easily solved by adding an ng-if to the infinite scroll and to remove it this way in case no more data can be loaded.

**Comment by vko-online** [comment]
I think it's map problem, when modal pops up, it changes body scale/translate or something similar, and leaflet tries to load tiles that are not needed.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As it looks like this issue was already solved i am going to close this issue for now, but please feel free to reopen if needed!
