### ISSUE TITLE
bug: 'ionic upload' replaces single quotes in my index.html with `&apos;` and '&' with `&amp;`

### ISSUE THREAD

**Issue by marioharper** [driftyco/ionic#4489]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Whenever executing ionic upload my index.html file changes all single quotes to `&apos;` and all "&" with `&amp;`

Example:
```html
<span ng-show="vm.searching && !vm.found">
  <i class="icon ion-search"></i>
</span>
```
Turns into:
```html
<span ng-show="vm.searching &amp;&amp; !vm.found">
  <i class="icon ion-search"></i>
</span>
```

System Info:
Cordova CLI: 5.3.3
Ionic Version 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
OS: Windows 8.1
Node Version: v4.1.0
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marioharper!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4489). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4489)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by bymodude** [comment]
+1

**Comment by nicmyers** [comment]
+1
My Content-Security-Policy goes from:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src  'self' 'unsafe-inline' *">
```

To: 

```
<meta http-equiv="Content-Security-Policy" content="default-src &apos;self&apos;; script-src &apos;self&apos; &apos;unsafe-inline&apos; &apos;unsafe-eval&apos; *; style-src  &apos;self&apos; &apos;unsafe-inline&apos; *">
```

Environment:
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
OS: Windows 10
Node Version: v4.2.2

**Comment by adriangordon1231** [comment]
+1

**Comment by mlynch** [comment]
Can you let us know here? https://github.com/driftyco/ionic-io-issues/issues. Seems related to CLI or platform. cc @ericb

**Comment by mrweiland** [comment]
+1
This must be a issue with how encoding is done on page index.html.

I use Visual Studio 2015 Update 1 and i have set encoding to UTF-8 without signature  - Codepage 65001 that someone tip me about. 

In Content Security Policy it switches some of the ' signs to &apos.
```<meta http-equiv="Content-Security-Policy" content="default-src * &apos;self&apos; &apos;unsafe-inline&apos; &apos;unsafe-eval&apos;;img-src &apos;self&apos; data: https://*; style-src http://* https://* &apos;unsafe-inline&apos;; script-src * &apos;self&apos; &apos;unsafe-inline&apos; &apos;unsafe-eval&apos;">```

This is happening when i use Ionic Upload command.

**Comment by louisdoe** [comment]
+1

**Comment by samazary** [comment]
+!

**Comment by funador** [comment]
+1

**Comment by mrweiland** [comment]
This is a problem with editor - not in ionic i think. Use Visual Code! :)
