### ISSUE TITLE
bug: iOS-9 opening modal goes back in url history

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#4491]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>On iOS-9 (not iOS-8), and using the iOS-9 webview fix gist, when I open a $ionicModal the URL changes and goes back to the previous one (effectively changing the current view).</span>

<span is-issue-template></span>

**Comment by adriangordon1231** [comment]
+1

**Comment by mhartington** [comment]
Can you provide a minimal codepen example that I can test against?

**Comment by Ionitron** [comment]
Greetings @Zorgatone!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @Zorgatone!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
