### ISSUE TITLE
docs: push message

### ISSUE THREAD

**Issue by realraga** [driftyco/ionic#4492]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>push message demo</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Nee more info. If this is platform related let us know here: https://github.com/driftyco/ionic-io-issues/issues
