### ISSUE TITLE
bug: Problem Changing App State in iOS 9

### ISSUE THREAD

**Issue by adriangordon1231** [driftyco/ionic#4493]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>In my project, I have implemented an overlay-menu directive that uses $state.go("stateName") to switch between the different views/template in my app. This problem is that when the user click an item in the menu, (in iOS9) the app attempts to switch to the appropriate view, but then quickly switched  back to the current view. 

The weird thing is that if the user clicks on an item in the menu a second time, the view is switched successfully.

Directive
```
angular.module('artEvents')
    .directive("overlayMenu", function () {

        return {
            restrict: "E",
            scope: {
                controls: "=controls"
            },
            templateUrl: "js/components/overlay-menu.html",
            controller: "OverlayController"
        };

    })
    .controller("OverlayController", function ($scope, $state, $ionicViewSwitcher, config) {

        $scope.mainmenu = config.menu;

        $scope.navigateToView = function (viewName) {

            $scope.controls.show = false;

            $ionicViewSwitcher.nextDirection('forward');

            $state.go(viewName);


        };
    });
```

Template
```
<div class="overlay-menu" ng-hide="!controls.show">
    <ul>
        <li ng-repeat="menuItem in mainmenu" class="overlay-item">
            <a href="#" ng-click="navigateToView(menuItem.view.toString())">
                {{menuItem.itemName}}
            </a>
        </li>
    </ul>
</div>
```

IOS 9 has really f'ed up my project as well and the "fix" has only made the issue worse (when a menu item is clicked the state of the app always reverts to the base state). </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @adriangordon1231!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4493). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4493)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kdubuc** [comment]
Bug confirmed on iOS 9.
The screen flickers when state changing and back to the previous state.

Do you fix that ?

**Comment by mhartington** [comment]
Please make sure you have included the ios9 patch.

**Comment by kdubuc** [comment]
Thanks, no more redirections with the patch :wink: 
But the bug of the screen which become black for 1 second when the state goes forward persist ... Anyway thank you !

**Comment by adriangordon1231** [comment]
@mhartington 

Yes unfortunately. The "fix", I was referring to was the patch. 

This one to be exact

```
angular.module('ngIOS9UIWebViewPatch', ['ng']).config(function($provide) {
  $provide.decorator('$browser', ['$delegate', '$window', function($delegate, $window) {

    if (isIOS9UIWebView($window.navigator.userAgent)) {
      return applyIOS9Shim($delegate);
    }

    return $delegate;

    function isIOS9UIWebView(userAgent) {
      return /(iPhone|iPad|iPod).* OS 9_\d/.test(userAgent) && !/Version\/9\./.test(userAgent);
    }

    function applyIOS9Shim(browser) {
      var pendingLocationUrl = null;
      var originalUrlFn= browser.url;

      browser.url = function() {
        if (arguments.length) {
          pendingLocationUrl = arguments[0];
          return originalUrlFn.apply(browser, arguments);
        }

        return pendingLocationUrl || originalUrlFn.apply(browser, arguments);
      };

      window.addEventListener('popstate', clearPendingLocationUrl, false);
      window.addEventListener('hashchange', clearPendingLocationUrl, false);

      function clearPendingLocationUrl() {
        pendingLocationUrl = null;
      }

      return browser;
    }
  }]);
});

```

All it did was reset the app to the default state everytime $sate. go() is called ... which is actually much worse than the flickering.

**Comment by adriangordon1231** [comment]
I really would love some help on this. I still have not found a solution to this issue :(.

**Comment by mhartington** [comment]
Hmm, what version of ionic are you using.

**Comment by adriangordon1231** [comment]
ionic 1.6.5

**Comment by mhartington** [comment]
Thats not your ionic.js version, thats the cli version. Inside of your project please run `ionic info` and paste the output here.

**Comment by adriangordon1231** [comment]
@mhartington 
My bad G. 
Ionic Version:  1.0.0

**Comment by adriangordon1231** [comment]
Has there been any fix since my last post?

**Comment by mlynch** [comment]
Hey @adriangordon1231, did you try the most recent release? Should fix a number of those issues.

**Comment by adriangordon1231** [comment]
@mlynch I will update as soon I settle down at work tomorrow. This is great news if it works.Thanks!

**Comment by jgw96** [comment]
Hey @adriangordon1231 are you still experiencing this issue?

**Comment by adriangordon1231** [comment]
@jgw96  Apologies. Everything works now.

**Comment by jgw96** [comment]
@adriangordon1231 No problem at all! Im glad everything is working for you!

**Comment by Xiralv** [comment]
Hi @adriangordon1231 how do you resolve this issue?

**Comment by adriangordon1231** [comment]
@Xiralv I honestly don't remember what it was. I have stopped working on this project (and for that company) almost a year ago. Sorry :(
