### ISSUE TITLE
docs: Use active state classnames

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#45]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Remove use of :active and instead use classnames</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
test

**Comment by adamdbradley** [comment]
test

**Comment by Ionitron** [comment]
stop it
