### ISSUE TITLE
bug: Missing Fonts: GET http://localhost:8100/lib/ionic/fonts/ionicons.woff 

### ISSUE THREAD

**Issue by robksawyer** [driftyco/ionic#4502]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've installed the latest version via master and it now seems to have some font linking issues. 

<img width="1315" alt="screen shot 2015-10-10 at 10 59 41 am" src="https://cloud.githubusercontent.com/assets/179419/10412556/1c6db7fc-6f3e-11e5-848b-63453421b029.png">
<img width="1329" alt="screen shot 2015-10-10 at 10 59 53 am" src="https://cloud.githubusercontent.com/assets/179419/10412557/1c6f47a2-6f3e-11e5-9edd-67b91436a216.png">
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @robksawyer!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4502). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4502)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by robksawyer** [comment]
Ended up fixing this by [downloading Ionicons](http://ionicons.com/) and then moving the css into `www/css` and then the fonts folder into `www/fonts`.

**Comment by mhartington** [comment]
Hmm, not seeing this on my end. 

```
  src: url("../fonts/ionicons.eot?v=2.0.1");
  src: url("../fonts/ionicons.eot?v=2.0.1#iefix") format("embedded-opentype"), 
       url("../fonts/ionicons.ttf?v=2.0.1") format("truetype"), 
       url("../fonts/ionicons.woff?v=2.0.1") format("woff"), 
       url("../fonts/ionicons.woff") format("woff"),
       url("../fonts/ionicons.svg?v=2.0.1#Ionicons") format("svg");
```
are the paths in ionic.css and all the fonts are there. Note I did delete the whole Ionic directory and installed from scratch.

![screen shot 2015-10-12 at 3 19 00 pm](https://cloud.githubusercontent.com/assets/2835826/10436492/b694bada-70f4-11e5-9812-fdb823eec894.png)

Closing this for now. If this is still an issue, please let me know.

**Comment by rhacker** [comment]
I think we do have a problem because the fonts folder is not in the `lib/ionic` but it's actually in `lib/ionic/release`. I install ionic from ionic bower 

```
ionic
├── CHANGELOG.md
├── LICENSE
├── README.md
├── bower.json
├── circle.yml
├── demos
├── gulpfile.js
├── js
├── release
└── scss

4 directories, 6 files
```

**Comment by ukupat** [comment]
Having the same problem when using ionic from bower

**Comment by gopalkoduri** [comment]
I installed ionic using bower as well, and the location is not `lib/ionic`, but `lib/ionic/release`. Is there a cleaner way to handle this so that one does not need to fix it every time there is a bower update?

**Comment by ldaguise** [comment]
+1
It would help me too.

**Comment by faeezshaikh** [comment]
This issue still exists.. Is there a workaround till its permanently fixes?

**Comment by almothafar** [comment]
@mhartington issue still exist here ! I'm using scss tho.

**Comment by robindierckx** [comment]
@mhartington +1 issue still exists (installed with bower). Fonts are in the release folder.
I moved to the (ionic-bower)[https://github.com/driftyco/ionic-bower] in which this bug does not occur.

**Comment by adediosf** [comment]
Same problem here! Any workaround?

**Comment by almothafar** [comment]
A workaround maybe you can try the following line as the first line inside `ionic.app.scss`:

`$ionicons-font-path: "../lib/ionic/release/fonts" !default;`

If you got same issue for Ionic2, then make sure you got the following line inside `variables.scss` 👍

**Comment by Lahrachtdi** [comment]
I get same error as well, but for me every thing works fine  until now, I have my font in www/lib/ionic/fonts
and I'm still working with ionic 1 in this application.
Error: `Get http://localhost:8100/www/lib/ionic/fonts/ionicons.ttf?v=2.0.1 `

**Comment by adediosf** [comment]
Finally, just copying the fonts files solved me the problem.
