### ISSUE TITLE
feat: fab buttons are not working in ionic for 4.1

### ISSUE THREAD

**Issue by anuja8275** [driftyco/ionic#4508]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>i am working on ionic with customizing the fab buttons on android 4.1 to 4.3 its not working at all any help?</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
We don't have fab buttons in v1, do you have an example?
