### ISSUE TITLE
bug: In meizu MX4 mobile https will return 404

### ISSUE THREAD

**Issue by kimtan1118** [driftyco/ionic#4514]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

this is the error message,
my code just like :

$http.jsonp('https:')
in error I can see the status is 404.
but the other mobile ,the app is normal
so how did angularjs can use certification? or how to trust all certification?</span>

the mx4 system version:flyme 4.5.6A 

<span is-issue-template></span>

**Comment by mhartington** [comment]
How would I got about recreating this issue. Can you provide a codepen that I can test on a device?

**Comment by kimtan1118** [comment]
$http.jsonp('https://angularjs.org/greet.php?callback=JSON_CALLBACK&name=Super%20Hero').
                    success(function(data,status,headers,config){
                        console.log('success data':JSON.stringify(data));
                    }).
                    error(function(data,status,headers,config){ // server error
                          console.log('error status':status); //it will be 404
                    });

you can use this code;

**Comment by kimtan1118** [comment]
I have test this code in many mobile ,but only Meizu MX4 get this error, I don't know this caursed by system ,but i tryed it in another meizu MXpro and the system version is also flyme 4.5.6A , and  it is normal.so i have no idea

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
