### ISSUE TITLE
bug: Collection-Repeat: 1.0.0-beta.9

### ISSUE THREAD

**Issue by nadeemkhan** [driftyco/ionic#4516]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>all i got just Loading.................. 
        

http://codepen.io/ionic/pen/mFygh</span>

<span is-issue-template></span>

**Comment by kukac7** [comment]
i think codepen bug.
````
mFygh:1 Uncaught SyntaxError: Unexpected token <
````
fullpage preview good:
http://codepen.io/ionic/full/mFygh/

**Comment by nadeemkhan** [comment]
Yup thanks :-)
