### ISSUE TITLE
bug: [FATAL BUG] Only Show White Screen on any android devices

### ISSUE THREAD

**Issue by rebelholic** [driftyco/ionic#4517]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello,

I have an ionic app just working as well on ionic serve but after builded for android with command "Ionic Build --release android" just showing white screen after splash screen without any error messages on console. Its my ionic info:
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.0
Ionic App Lib Version: 0.5.1-beta.0
OS: Windows 8.1
Node Version: v0.12.0

I am using windows 10 x64 not win 8.1 like described above.

Its my index.html

          <!DOCTYPE html>
         <html>
         <head>
        <meta charset="utf-8">
       <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
      <title>TEST</title>

     <link href="lib/ionic/css/ionic.min.css" rel="stylesheet">
     <link href="css/style.css" rel="stylesheet">

     

     
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/ng-cordova.min.js"></script>
    <script src="lib/angular-cache/dist/angular-cache.min.js"></script>
    <script src="lib/ng-special-offer/src/ng-special-offer.js"></script>
    <script src="lib/ngStorage/ngStorage.min.js"></script>
    

    <script src="cordova.js"></script>
    
    
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
    <script src="js/services.js"></script>
    <script src="js/filters.js"></script>
  </head>

  <body ng-app="wpIonic" onload="onLoad()" onresize="onResize()">
    <ion-nav-view></ion-nav-view>
  </body>
</html>

I hope anyone help me to fix it with ASAP</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rebelholic!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4517). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4517)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
So let's start by ruling out a few things.

Can you run the app on an android device without signing it? 

```
ionic run android --device
```

**Comment by rebelholic** [comment]
@mhartington 
After I tried with any methods include like you said, I have some points like below:
1. I already tried run the app just with "Ionic Build Android" still got same error like above.
2. My app running with perfectly if I have removed [this plugin](https://github.com/AlexDisler/ng-special-offer) from my app with completely.

It seems [this plugin](https://github.com/AlexDisler/ng-special-offer) have conflict with your ionic lib.
Also my app already published on play store you can check out [on this link](https://play.google.com/store/apps/details?id=com.baysoft.unity3dindo)

**Comment by mlynch** [comment]
Sounds like a cordova issue. Closing w/o more info
