### ISSUE TITLE
bug: digest in progress on open drowdown and pagechange

### ISSUE THREAD

**Issue by ch000** [driftyco/ionic#4521]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I've got a simple page with a ng-options directive and a button to change the page.
If i open the ng-options dropdown, change the value and then change the page while the dropdown is still open, i get a "digest is already in progress" error. This happens only on IOS, on other platforms it is not possible to interact with the page while the dropdown is open.

Here a video of this behaviour: https://goo.gl/photos/PrUUgaLoGK6Pb7wJ9
and the source: http://plnkr.co/edit/RNDGyEEi5NcgxPIH0EPa
and the ionic view app id: 7027b894</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hmm, seeing this as well. Though it makes sense why this is happening. So it's trying to do two things at once, causing the errors. I can't speak for why it's only happening for ios, but you should be able to just set a timeout on the state.go function.

```
  $scope.nextPage = function() {
    setTimeout(function() {
      $state.go('app.search', {
        value: $scope.d.selected.name
      });
    });
  };
```
