### ISSUE TITLE
docs: $ionicPlatform.ready is not a function error in controller

### ISSUE THREAD

**Issue by PrithvirajChauhan** [driftyco/ionic#4528]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicPlatform.ready works pefectly in .run function but giving error in controller.
```
var db = null;
var myapp=angular.module('starter', ['ionic','btford.socket-io','LoginCntrl','SlideCntrl','app','ChatCntrl','ngCordova','ngCordova.plugins.sqlite'])

.run(function($ionicPlatform,$cordovaSQLite) {
	$ionicPlatform.ready(function() {

		// Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
		// for form inputs)
		if(window.cordova && window.cordova.plugins.Keyboard) {
			cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
		}
		if(window.StatusBar) {
			StatusBar.styleDefault();
		}
		console.log("The application is resuming from the background");
		db = $cordovaSQLite.openDB({ name: App_DB_Name });
		$cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS people (id integer primary key, firstname text, lastname text)");

		var query = "SELECT firstname, lastname FROM people WHERE lastname = ?";
		$cordovaSQLite.execute(db, query, ["pruthvi"]).then(function(result) {
			if(result.rows.length > 0) {
				console.log("SELECTED -> " + result.rows.item(0).firstname + " " + result.rows.item(0).lastname);
				alert("SELECTED -> "+ result.rows.item(0).firstname + " " + result.rows.item(0).lastname)
			} else {
				console.log("No results found");
			}
		}, function (err) {
			console.error(err);
		});
		//	$cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS "+ App_DB_Table_Login_Name +"(id integer primary key, login_username text, login_password text)");
		console.log("success");
	});
});

myapp.controller('IndexController', ['$scope','$rootScope','$ionicPlatform','$cordovaSQLite', function($scope,$rootScope,$cordovaSQLite, $ionicPlatform,$cordovaPush){

	// call to register automatically upon device ready
	$ionicPlatform.ready(function() {
		console.log("devie is ready");
	});
}]);

```
Error Logs
TypeError: $ionicPlatform.ready is not a function
    at new <anonymous> (app.js:106)
    at Object.invoke (ionic.bundle.js:13277)
    at extend.instance (ionic.bundle.js:17826)
    at nodeLinkFn (ionic.bundle.js:16936)
    at compositeLinkFn (ionic.bundle.js:16368)
    at compositeLinkFn (ionic.bundle.js:16372)
    at publicLinkFn (ionic.bundle.js:16243)
    at ionic.bundle.js:10462
    at Scope.$eval (ionic.bundle.js:24673)
    at Scope.$apply (ionic.bundle.js:24772)
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @PrithvirajChauhan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4528). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4528)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by DaDanny** [comment]
May I ask why you want to do this? If you need to initialize something once the app is ready, I'd recommend using a service with an init function, and then inject that service into your app.js .run function, and call the service's init function within the $ionicPlatform.ready(function(){}.

You can also try using $emit's and $on's, though I wouldn't recommend that route as it can get tricky keeping track of what and where is emitting and what and where is listening for it.

**Comment by RuspinaDev** [comment]
try to write your function like this
``` javascript
.run(['$ionicPlatform', '$cordovaSQLite', function($ionicPlatform, $cordovaSQLite) {
/*traitments*/
}])
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
