### ISSUE TITLE
bug: ion-reorder causes ng-repeat item to dissapear or be empty

### ISSUE THREAD

**Issue by paynoattn** [driftyco/ionic#4532]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello,

I'm trying to use ion-reorder in my app. The re-order icons appear, and I can drag items, but when I drop them either the item or the content inside the list item completely dissapears. I basically copy and pasted the ion-reorder from the documentation as you can see below, only changing the name from my data.

This is on ionic serve on latest Chrome/Firefox/Safari.

index.html
```
<ion-list show-reorder="data.showReorder">
          <ion-item  ng-repeat="artist in artists | filter: query" class="item-thumbnail-left item-text-wrap">
            <img src="img/{{artist.shortname}}_tn.jpg">
            <h2>{{artist.name}}</h2>
            <ion-reorder-button class="ion-navicon" on-reorder="moveItem(item, $fromIndex, $toIndex)"></ion-reorder-button>
          </ion-item>
        </ion-list>
```

app.js
```
$http.get('../model/data.json').success(function(data) {
    $scope.artists = data.artists;
    $scope.moveItem = function(item, fromIndex, toIndex) {
      //Move the item in the array
      $scope.artists.splice(fromIndex, 1);
      $scope.artists.splice(toIndex, 0, item);
    };
```

Also when I try to ```console.log(item);``` at the end of my $scope.moveItem function it states that item is undefined in the console.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @paynoattn!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4532). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4532)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by paynoattn** [comment]
Okay, I figured this out. The fix is that I was passing the ```item``` instead of ```artist```. Artist is the variable of the repeat item, so therefore ```item``` would be ```undefined.```

In my case I had to change these to fix this: 
index.html
```
<ion-list show-reorder="data.showReorder">
          <ion-item  ng-repeat="artist in artists | filter: query" class="item-thumbnail-left item-text-wrap">
            <img src="img/{{artist.shortname}}_tn.jpg">
            <h2>{{artist.name}}</h2>
            <ion-reorder-button class="ion-navicon" on-reorder="moveItem(artist, $fromIndex, $toIndex)"></ion-reorder-button>
          </ion-item>
        </ion-list>
```

app.js
```
$http.get('../model/data.json').success(function(data) {
    $scope.artists = data.artists;
    $scope.moveItem = function(artist, fromIndex, toIndex) {
      //Move the item in the array
      $scope.artists.splice(fromIndex, 1);
      $scope.artists.splice(toIndex, 0, artist);
    };
