### ISSUE TITLE
bug: Transition is wrong with ion-nav-title

### ISSUE THREAD

**Issue by simplesmiler** [driftyco/ionic#4542]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When you have a block element inside `ion-nav-title`, or it's width is large by other means (long title), title is animated in a wrong direction upon `ion-view` transition.

Repro: http://codepen.io/simplesmiler/pen/yYpXqy
Demo:
![http://i.imgur.com/AZkkfZI.gif](http://i.imgur.com/AZkkfZI.gif)</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
>Alternatively, text-only titles can be updated using the view-title ionView attribute.

Just use the view-title for that.

ion-nav-title is meant more for images.

http://codepen.io/mhartington/pen/LpejVd

**Comment by simplesmiler** [comment]
@mhartington `view-title` is not an option, I'm looking for a way to place a search bar in the header.
Something like this: http://codepen.io/simplesmiler/pen/RWxZxm

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
