### ISSUE TITLE
bug: Content does not fit to screen using height 100%.

### ISSUE THREAD

**Issue by CTucker1327** [driftyco/ionic#4543]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>This bug persists on iOS 7, iOS8, and iOS 9. Tested devices include the iPhone4s, 5, 6, 6+, 6s, 6s+. Bug does not occur on android. Bug does not occur in phones browser. Bug does occur in ionic view and native hybrid application.

Please see thread for more information and picture details: http://forum.ionicframework.com/t/ionic-bug-on-ios-details-inside/35155</span>

<span is-issue-template></span>

**Comment by CTucker1327** [comment]
Bug fix is inside of `MainViewController.m` 

See below:

- (void)webViewDidFinishLoad:(UIWebView*)theWebView
{
    // Black base color for background matches the native apps
    theWebView.backgroundColor = [UIColor blackColor];
    theWebView.scrollView.contentInset = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, 0.0f);
    return [super webViewDidFinishLoad:theWebView];
}

The line: 
    theWebView.scrollView.contentInset = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, 0.0f);

Corrects problematic behaviour on all iOS versions

**Comment by CTucker1327** [comment]
Does anyone monitor these?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Very sorry for the wait, are you still experiencing this issue?

**Comment by CTucker1327** [comment]
I couldn't answer, as I stopped using Ionic awhile back due to projects randomly corrupting and starting writing my apps in native code again.

**Comment by jgw96** [comment]
Im sorry about that! When you say your projects were randomly corrupting what exactly was happening? Were they not building?

**Comment by CTucker1327** [comment]
I honestly couldn't tell you exactly what was happening. I could literally go to sleep one night, and wake up the next and the entire project would explode. Running the application would result in the "white screen of death" and compiling the application would throw tons of errors.

Creating a new ionic project and migrating all of the code over would correct any problems. 

It just got to where we were doing this about 4-5 times a week and we couldn't deal with the amount of time it was taking anymore. 

I would love to give Ionic2 a try for some future applications. However, due to the complications I'll be keeping any larger projects away for awhile. 

Thanks for your quick responses. As for the original error spoken of, I was experiencing it up until the bitter end. (Around mid January is when I finally made the swap).
