### ISSUE TITLE
bug: $scope.$watch() on checkbox ng-model doesn't fire in ionic

### ISSUE THREAD

**Issue by djdmbrwsk** [driftyco/ionic#4551]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It seems like a simple `$scope.$watch()` on checkbox `ng-model` doesn't fire in ionic.  A few observations:
- Works fine in a straight angular app
- Model value does seem to update and display correctly in the DOM
- Nesting the value in an object gets it to work `ng-model="nested.test"`
- Issue is also seen in `<ion-toggle>` and probably `<ion-checkbox>`

**Works in angular:**  http://embed.plnkr.co/C74AY89frOgPlk61rlzX/preview
**No worky in ionic:**  http://play.ionic.io/app/5f625dab7e47</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @djdmbrwsk!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4551). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4551)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tpape** [comment]
In a more general way, there is a problem with the model update with the checkbox (ion-toggle by extension), I have :   
HTML :
```html
<ion-toggle data-ng-init="persistLogin = true" data-ng-model="persistLogin">Save</ion-toggle>
```  
JS :
```javascript
if ($scope.persistLogin) {
	$rootScope.$storage.login = $scope.login;
} else {
	delete $rootScope.$storage.login;
}
```

The result of the test is always **false**, without any considerations for the state of the toggle. Unless, when I use a sub-object like : `$scope.persist.login`, with the proper initialization, the value of the variable in the controller is related with the status of the toggle.

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by djdmbrwsk** [comment]
Yes. It still happens on 1.2.4 too. It's easy to work around, but...

**Comment by danbucholtz** [comment]
Hi @djdmbrwsk,

The recommended approach from the angular team is to bind to a primitive like boolean through an object.

https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D

```
<script>
  angular.module('checkboxExample', [])
    .controller('ExampleController', ['$scope', function($scope) {
      $scope.checkboxModel = {
       value1 : true,
       value2 : 'YES'
     };
    }]);
</script>
<form name="myForm" ng-controller="ExampleController">
  <label>Value1:
    <input type="checkbox" ng-model="checkboxModel.value1">
  </label><br/>
  <label>Value2:
    <input type="checkbox" ng-model="checkboxModel.value2"
           ng-true-value="'YES'" ng-false-value="'NO'">
   </label><br/>
  <tt>value1 = {{checkboxModel.value1}}</tt><br/>
  <tt>value2 = {{checkboxModel.value2}}</tt><br/>
 </form>
```

As your example shows, that works.  That will be our recommended approach too.

Thanks for contributing and for using Ionic!

Thanks,
Dan
