### ISSUE TITLE
bug: nav-view has different inline style for opacity on iOS and Android

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#4556]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a reasonably complex app with 5 tabs, 3 of which have lists using `collection-repeat`. When switching between tabs on Android I've been seeing the `ion-view` disappear for approx 200ms then appear again. Obviously this is more noticeable when running on a device. The problem doesn't happen on iOS which switches tabs cleanly.

I could also replicate it in the side by side lab view and doing a screen capture, showed up that when a tab is selected, as expected the incoming `ion-nav-view` changes from `nav-view="cached"` to `nav-view="active"` but at the same time, the child `ion-view` changes from `nav-view="active"` to `nav-view="stage"` and then 200ms later (in my case) it changes back again to `nav-view="active"`. 

In `ionic/scss/_transitions.scss` is the following

    [nav-view="stage"] {
      opacity: 0;
      @include transition-duration( 0 );
    }

which is causing the nav-view to disappear when it changes to "stage" and reappear when it changes back to "active".

So I can override that to fix the flash, but what's interesting is that the inline styles on `ion-view` are different for some reason between iOS and Android which is why I'm only seeing the opacity change to 0 on Android.

iOS has:

    style="-webkit-transition: 0ms; transition: 0ms; opacity: 1; transform: translate3d(0%, 0px, 0px);"

Android has:

    style="-webkit-transition: 0ms; transition: 0ms; transform: translate3d(0%, 0px, 0px);"

All this can be seen by using the tabs starter template and running in ionic serve lab mode.

I'm using Ionic 1.1.0, this is applicable for ANY Android version but your form won't let me choose that :-)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @martinjbaker!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4556). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4556)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by demoalex** [comment]
I have same issue. Found it's here at least since April http://forum.ionicframework.com/t/android-transition-and-ui-view-opacity/21954

Seems it's located in ionic-angular.js near 1935:
```javascript
  // Android Transitions
  // -----------------------

  provider.transitions.views.android = function(enteringEle, leavingEle, direction, shouldAnimate) {
    shouldAnimate = shouldAnimate && (direction == 'forward' || direction == 'back');

    function setStyles(ele, x) {
      var css = {};
      css[ionic.CSS.TRANSITION_DURATION] = d.shouldAnimate ? '' : 0;
      css[ionic.CSS.TRANSFORM] = 'translate3d(' + x + '%,0,0)';
      ionic.DomUtil.cachedStyles(ele, css);
    }

```

Same part for iOS is near and looks a bit different:
```javascript
  // iOS Transitions
  // -----------------------
  provider.transitions.views.ios = function(enteringEle, leavingEle, direction, shouldAnimate) {

    function setStyles(ele, opacity, x, boxShadowOpacity) {
      var css = {};
      css[ionic.CSS.TRANSITION_DURATION] = d.shouldAnimate ? '' : 0;
      css.opacity = opacity;
      if (boxShadowOpacity > -1) {
        css.boxShadow = '0 0 10px rgba(0,0,0,' + (d.shouldAnimate ? boxShadowOpacity * 0.45 : 0.3) + ')';
      }
      css[ionic.CSS.TRANSFORM] = 'translate3d(' + x + '%,0,0)';
      ionic.DomUtil.cachedStyles(ele, css);
    }
```

**Comment by demoalex** [comment]
So just adding ```css.opacity = 1``` worked for my app.

**Comment by mlynch** [comment]
Thanks for the info. Just curious, does this commit (from an hour ago) help? a3e9f6ddeace8d5b1bd28e4948176b9fc7e953bd

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by bmwertman** [comment]
I just hit this issue after installing the crosswalk browser and updating Cordova command line to the latest release. Has @demoalex 's fix called pulled in at some version? 
![screen shot 2016-09-28 at 12 59 52 pm](https://cloud.githubusercontent.com/assets/2573903/18954157/a09d7870-861f-11e6-8d81-21078bf503bc.png)
