### ISSUE TITLE
Side Menu with Nav Views do not work in Android 4.3-

### ISSUE THREAD

**Issue by corydorning** [driftyco/ionic#456]
The following examples of using a nav view inside of the side menu do not work in version of Android 4.3 and lower or in non-webkit browsers. In these versions, which you try to slide the menu over via dragging the header or by clicking on a button icon in the header, nothing happens.

In Chrome and Android 4.4 they work properly.

http://plnkr.co/edit/9vVpEnRvmXUnUBN7SSoR?p=preview
http://plnkr.co/edit/p9b6SWZmBKWYm0FIKsXY?p=preview

**Comment by prolland006** [comment]
hi, in 2016 with cordova 6.3.1 and ionic 2.1.0 with android 4.2.1 the menu and the toggle button doesn't work, nothing happen when I click. I tested on a more recent android with the same basic starter application and it is work fine. What I should do ? thanks
