### ISSUE TITLE
feat: ionic doen't provide scroll to my externally added

### ISSUE THREAD

**Issue by Poojal123** [driftyco/ionic#4569]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>http://codepen.io/anon/pen/bVMajZ

here is my code pen demo..
pls check this.
copy all content fom html to ur ionic blank projects index.html page.

and build with ionic build android.
im using this on android 5.0 ,5.1,4.4 as well but same issue is there .
the result witch is coming from json that div is not scroll able..

pls reply as soon as possible. waiting for ur reply

thanx in andvance. : )</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please provide a working codepen. This codepen, even after cleaning up, 404s with `url: "js/language.json",`

**Comment by sharvari1** [comment]
@mhartington 

sry i forgot to put...

[{"language_static_data_id_pk":1,"language_name":"Afar","language_code":"aa","language_url":"aa"},{"language_static_data_id_pk"
:2,"language_name":"Abkhazian","language_code":"ab","language_url":"ab"},{"language_static_data_id_pk"
:3,"language_name":"Afrikaans","language_code":"af","language_url":"af"},{"language_static_data_id_pk"
:4,"language_name":"Akan","language_code":"ak","language_url":"ak"},{"language_static_data_id_pk":5,"language_name"
:"Amharic","language_code":"am","language_url":"am"},{"language_static_data_id_pk":6,"language_name"
:"Arabic","language_code":"ar","language_url":"ar"},{"language_static_data_id_pk":7,"language_name":"Assamese"
,"language_code":"as","language_url":"as"},{"language_static_data_id_pk":8,"language_name":"Aymara","language_code"
:"ay","language_url":"ay"},{"language_static_data_id_pk":9,"language_name":"Azerbaijani","language_code"
:"az","language_url":"az"},{"language_static_data_id_pk":10,"language_name":"Bashkir","language_code"
:"ba","language_url":"ba"},{"language_static_data_id_pk":11,"language_name":"Belarusian","language_code"
:"be","language_url":"be"},{"language_static_data_id_pk":12,"language_name":"Bulgarian","language_code"
:"bg","language_url":"bg"},{"language_static_data_id_pk":13,"language_name":"Bihari","language_code"
:"bh","language_url":"bh"},{"language_static_data_id_pk":14,"language_name":"Bislama","language_code"
:"bi","language_url":"bi"},{"language_static_data_id_pk":15,"language_name":"Bengali","language_code"
:"bn","language_url":"bn"},{"language_static_data_id_pk":16,"language_name":"Tibetan","language_code"
:"bo","language_url":"bo"},{"language_static_data_id_pk":17,"language_name":"Breton","language_code"
:"br","language_url":"br"},{"language_static_data_id_pk":18,"language_name":"Bosnian","language_code"
:"bs","language_url":"bs"},{"language_static_data_id_pk":19,"language_name":"Catalan","language_code"
:"ca","language_url":"ca"},{"language_static_data_id_pk":20,"language_name":"Cebuano","language_code"
:"ceb","language_url":"ceb"},{"language_static_data_id_pk":21,"language_name":"Cherokee","language_code"
:"chr","language_url":"chr"},{"language_static_data_id_pk":22,"language_name":"Corsican","language_code"
:"co","language_url":"co"},{"language_static_data_id_pk":23,"language_name":"Seselwa","language_code"
:"crs","language_url":"crs"},{"language_static_data_id_pk":24,"language_name":"Czech","language_code"
:"cs","language_url":"cs"},{"language_static_data_id_pk":25,"language_name":"Welsh","language_code":"cy"
,"language_url":"cy"},{"language_static_data_id_pk":26,"language_name":"Danish","language_code":"da"
,"language_url":"da"},{"language_static_data_id_pk":27,"language_name":"German","language_code":"de"
,"language_url":"de"},{"language_static_data_id_pk":28,"language_name":"Dhivehi","language_code":"dv"
,"language_url":"dv"},{"language_static_data_id_pk":29,"language_name":"Dzongkha","language_code":"dz"
,"language_url":"dz"},{"language_static_data_id_pk":30,"language_name":"Greek","language_code":"el","language_url"
:"el"},{"language_static_data_id_pk":31,"language_name":"English","language_code":"en","language_url"
:"en"},{"language_static_data_id_pk":32,"language_name":"Esperanto","language_code":"eo","language_url"
:"eo"},{"language_static_data_id_pk":33,"language_name":"Spanish","language_code":"es","language_url"
:"es"},{"language_static_data_id_pk":34,"language_name":"Estonian","language_code":"et","language_url"
:"et"},{"language_static_data_id_pk":35,"language_name":"Basque","language_code":"eu","language_url"
:"eu"},{"language_static_data_id_pk":36,"language_name":"Persian","language_code":"fa","language_url"
:"fa"},{"language_static_data_id_pk":37,"language_name":"Finnish","language_code":"fi","language_url"
:"fi"},{"language_static_data_id_pk":38,"language_name":"Fijian","language_code":"fj","language_url"
:"fj"},{"language_static_data_id_pk":39,"language_name":"Faroese","language_code":"fo","language_url"
:"fo"},{"language_static_data_id_pk":40,"language_name":"French","language_code":"fr","language_url"
:"fr"},{"language_static_data_id_pk":41,"language_name":"Frisian","language_code":"fy","language_url"
:"fy"},{"language_static_data_id_pk":42,"language_name":"Irish","language_code":"ga","language_url":"ga"
},{"language_static_data_id_pk":43,"language_name":"Scots Gaelic","language_code":"gd","language_url"
:"gd"},{"language_static_data_id_pk":44,"language_name":"Galician","language_code":"gl","language_url"
:"gl"},{"language_static_data_id_pk":45,"language_name":"Guarani","language_code":"gn","language_url"
:"gn"},{"language_static_data_id_pk":46,"language_name":"Gujarati","language_code":"gu","language_url"
:"gu"},{"language_static_data_id_pk":47,"language_name":"Manx","language_code":"gv","language_url":"gv"
},{"language_static_data_id_pk":48,"language_name":"Hausa","language_code":"ha","language_url":"ha"}
,{"language_static_data_id_pk":49,"language_name":"Hawaiian","language_code":"haw","language_url":"haw"
},{"language_static_data_id_pk":50,"language_name":"Hindi","language_code":"hi","language_url":"hi"}
,{"language_static_data_id_pk":51,"language_name":"Hmong","language_code":"hmn","language_url":"hmn"
},{"language_static_data_id_pk":52,"language_name":"Croatian","language_code":"hr","language_url":"hr"
},{"language_static_data_id_pk":53,"language_name":"Haitian Creole","language_code":"ht","language_url"
:"ht"},{"language_static_data_id_pk":54,"language_name":"Hungarian","language_code":"hu","language_url"
:"hu"},{"language_static_data_id_pk":55,"language_name":"Armenian","language_code":"hy","language_url"
:"hy"},{"language_static_data_id_pk":56,"language_name":"Interlingua","language_code":"ia","language_url"
:"ia"},{"language_static_data_id_pk":57,"language_name":"Indonesian","language_code":"id","language_url"
:"id"},{"language_static_data_id_pk":58,"language_name":"Interlingue","language_code":"ie","language_url"
:"ie"},{"language_static_data_id_pk":59,"language_name":"Igbo","language_code":"ig","language_url":"ig"
},{"language_static_data_id_pk":60,"language_name":"Inupiak","language_code":"ik","language_url":"ik"
},{"language_static_data_id_pk":61,"language_name":"Icelandic","language_code":"is","language_url":"is"
},{"language_static_data_id_pk":62,"language_name":"Italian","language_code":"it","language_url":"it"
},{"language_static_data_id_pk":63,"language_name":"Inuktitut","language_code":"iu","language_url":"iu"
},{"language_static_data_id_pk":64,"language_name":"Hebrew","language_code":"iw","language_url":"iw"
},{"language_static_data_id_pk":65,"language_name":"Japanese","language_code":"ja","language_url":"ja"
},{"language_static_data_id_pk":66,"language_name":"Javanese","language_code":"jw","language_url":"jw"
},{"language_static_data_id_pk":67,"language_name":"Georgian","language_code":"ka","language_url":"ka"
},{"language_static_data_id_pk":68,"language_name":"Khasi","language_code":"kha","language_url":"kha"
},{"language_static_data_id_pk":69,"language_name":"Kazakh","language_code":"kk","language_url":"kk"
},{"language_static_data_id_pk":70,"language_name":"Greenlandic","language_code":"kl","language_url"
:"kl"},{"language_static_data_id_pk":71,"language_name":"Khmer","language_code":"km","language_url":"km"
},{"language_static_data_id_pk":72,"language_name":"Kannada","language_code":"kn","language_url":"kn"
},{"language_static_data_id_pk":73,"language_name":"Korean","language_code":"ko","language_url":"ko"
},{"language_static_data_id_pk":74,"language_name":"Kashmiri","language_code":"ks","language_url":"ks"
},{"language_static_data_id_pk":75,"language_name":"Kurdish","language_code":"ku","language_url":"ku"
},{"language_static_data_id_pk":76,"language_name":"Kyrgyz","language_code":"ky","language_url":"ky"
},{"language_static_data_id_pk":77,"language_name":"Latin","language_code":"la","language_url":"la"}
,{"language_static_data_id_pk":78,"language_name":"Luxembourgish","language_code":"lb","language_url"
:"lb"},{"language_static_data_id_pk":79,"language_name":"Ganda","language_code":"lg","language_url":"lg"
},{"language_static_data_id_pk":80,"language_name":"Limbu","language_code":"lif","language_url":"lif"
},{"language_static_data_id_pk":81,"language_name":"Lingala","language_code":"ln","language_url":"ln"
},{"language_static_data_id_pk":82,"language_name":"Laothian","language_code":"lo","language_url":"lo"
},{"language_static_data_id_pk":83,"language_name":"Lithuanian","language_code":"lt","language_url":"lt"
},{"language_static_data_id_pk":84,"language_name":"Latvian","language_code":"lv","language_url":"lv"
},{"language_static_data_id_pk":85,"language_name":"Mauritian Creole","language_code":"mfe","language_url"
:"mfe"},{"language_static_data_id_pk":86,"language_name":"Malagasy","language_code":"mg","language_url"
:"mg"},{"language_static_data_id_pk":87,"language_name":"Maori","language_code":"mi","language_url":"mi"
},{"language_static_data_id_pk":88,"language_name":"Macedonian","language_code":"mk","language_url":"mk"
},{"language_static_data_id_pk":89,"language_name":"Malayalam","language_code":"ml","language_url":"ml"
},{"language_static_data_id_pk":90,"language_name":"Mongolian","language_code":"mn","language_url":"mn"
},{"language_static_data_id_pk":91,"language_name":"Marathi","language_code":"mr","language_url":"mr"
},{"language_static_data_id_pk":92,"language_name":"Malay","language_code":"ms","language_url":"ms"}
,{"language_static_data_id_pk":93,"language_name":"Maltese","language_code":"mt","language_url":"mt"
},{"language_static_data_id_pk":94,"language_name":"Burmese","language_code":"my","language_url":"my"
},{"language_static_data_id_pk":95,"language_name":"Nauru","language_code":"na","language_url":"na"}
,{"language_static_data_id_pk":96,"language_name":"Nepali","language_code":"ne","language_url":"ne"}
,{"language_static_data_id_pk":97,"language_name":"Dutch","language_code":"nl","language_url":"nl"},
{"language_static_data_id_pk":98,"language_name":"Norwegian","language_code":"no","language_url":"no"
},{"language_static_data_id_pk":99,"language_name":"Ndebele","language_code":"nr","language_url":"nr"
},{"language_static_data_id_pk":100,"language_name":"Pedi","language_code":"nso","language_url":"nso"
},{"language_static_data_id_pk":101,"language_name":"Nyanja","language_code":"ny","language_url":"ny"
},{"language_static_data_id_pk":102,"language_name":"Occitan","language_code":"oc","language_url":"oc"
},{"language_static_data_id_pk":103,"language_name":"Oromo","language_code":"om","language_url":"om"
},{"language_static_data_id_pk":104,"language_name":"Oriya","language_code":"or","language_url":"or"
},{"language_static_data_id_pk":105,"language_name":"Punjabi","language_code":"pa","language_url":"pa"
},{"language_static_data_id_pk":106,"language_name":"Polish","language_code":"pl","language_url":"pl"
},{"language_static_data_id_pk":107,"language_name":"Pashto","language_code":"ps","language_url":"ps"
},{"language_static_data_id_pk":108,"language_name":"Portuguese","language_code":"pt","language_url"
:"pt"},{"language_static_data_id_pk":109,"language_name":"Quechua","language_code":"qu","language_url"
:"qu"},{"language_static_data_id_pk":110,"language_name":"Rhaeto Romance","language_code":"rm","language_url"
:"rm"},{"language_static_data_id_pk":111,"language_name":"Rundi","language_code":"rn","language_url"
:"rn"},{"language_static_data_id_pk":112,"language_name":"Romanian","language_code":"ro","language_url"
:"ro"},{"language_static_data_id_pk":113,"language_name":"Russian","language_code":"ru","language_url"
:"ru"},{"language_static_data_id_pk":114,"language_name":"Kinyarwanda","language_code":"rw","language_url"
:"rw"},{"language_static_data_id_pk":115,"language_name":"Sanskrit","language_code":"sa","language_url"
:"sa"},{"language_static_data_id_pk":116,"language_name":"Scots","language_code":"sco","language_url"
:"sco"},{"language_static_data_id_pk":117,"language_name":"Sindhi","language_code":"sd","language_url"
:"sd"},{"language_static_data_id_pk":118,"language_name":"Sango","language_code":"sg","language_url"
:"sg"},{"language_static_data_id_pk":119,"language_name":"Sinhalese","language_code":"si","language_url"
:"si"},{"language_static_data_id_pk":120,"language_name":"Slovak","language_code":"sk","language_url"
:"sk"},{"language_static_data_id_pk":121,"language_name":"Slovenian","language_code":"sl","language_url"
:"sl"},{"language_static_data_id_pk":122,"language_name":"Samoan","language_code":"sm","language_url"
:"sm"},{"language_static_data_id_pk":123,"language_name":"Shona","language_code":"sn","language_url"
:"sn"},{"language_static_data_id_pk":124,"language_name":"Somali","language_code":"so","language_url"
:"so"},{"language_static_data_id_pk":125,"language_name":"Albanian","language_code":"sq","language_url"
:"sq"},{"language_static_data_id_pk":126,"language_name":"Serbian","language_code":"sr","language_url"
:"sr"},{"language_static_data_id_pk":127,"language_name":"Siswant","language_code":"ss","language_url"
:"ss"},{"language_static_data_id_pk":128,"language_name":"Sesotho","language_code":"st","language_url"
:"st"},{"language_static_data_id_pk":129,"language_name":"Sundanese","language_code":"su","language_url"
:"su"},{"language_static_data_id_pk":130,"language_name":"Swedish","language_code":"sv","language_url"
:"sv"},{"language_static_data_id_pk":131,"language_name":"Swahili","language_code":"sw","language_url"
:"sw"},{"language_static_data_id_pk":132,"language_name":"Syriac","language_code":"syr","language_url"
:"syr"},{"language_static_data_id_pk":133,"language_name":"Tamil","language_code":"ta","language_url"
:"ta"},{"language_static_data_id_pk":134,"language_name":"Telugu","language_code":"te","language_url"
:"te"},{"language_static_data_id_pk":135,"language_name":"Tajik","language_code":"tg","language_url"
:"tg"},{"language_static_data_id_pk":136,"language_name":"Thai","language_code":"th","language_url":"th"
},{"language_static_data_id_pk":137,"language_name":"Tigrinya","language_code":"ti","language_url":"ti"
},{"language_static_data_id_pk":138,"language_name":"Turkmen","language_code":"tk","language_url":"tk"
},{"language_static_data_id_pk":139,"language_name":"Tagalog","language_code":"tl","language_url":"tl"
},{"language_static_data_id_pk":140,"language_name":"Tswana","language_code":"tn","language_url":"tn"
},{"language_static_data_id_pk":141,"language_name":"Tonga","language_code":"to","language_url":"to"
},{"language_static_data_id_pk":142,"language_name":"Turkish","language_code":"tr","language_url":"tr"
},{"language_static_data_id_pk":143,"language_name":"Tsonga","language_code":"ts","language_url":"ts"
},{"language_static_data_id_pk":144,"language_name":"Tatar","language_code":"tt","language_url":"tt"
},{"language_static_data_id_pk":145,"language_name":"Uighur","language_code":"ug","language_url":"ug"
},{"language_static_data_id_pk":146,"language_name":"Ukrainian","language_code":"uk","language_url":"uk"
},{"language_static_data_id_pk":147,"language_name":"Urdu","language_code":"ur","language_url":"ur"}
,{"language_static_data_id_pk":148,"language_name":"Uzbek","language_code":"uz","language_url":"uz"}
,{"language_static_data_id_pk":149,"language_name":"Venda","language_code":"ve","language_url":"ve"}
,{"language_static_data_id_pk":150,"language_name":"Vietnamese","language_code":"vi","language_url":"vi"
},{"language_static_data_id_pk":151,"language_name":"Volapuk","language_code":"vo","language_url":"vo"
},{"language_static_data_id_pk":152,"language_name":"Waray Philippines","language_code":"war","language_url"
:"war"},{"language_static_data_id_pk":153,"language_name":"Wolof","language_code":"wo","language_url"
:"wo"},{"language_static_data_id_pk":154,"language_name":"Xhosa","language_code":"xh","language_url"
:"xh"},{"language_static_data_id_pk":155,"language_name":"Yiddish","language_code":"yi","language_url"
:"yi"},{"language_static_data_id_pk":156,"language_name":"Yoruba","language_code":"yo","language_url"
:"yo"},{"language_static_data_id_pk":157,"language_name":"Zhuang","language_code":"za","language_url"
:"za"},{"language_static_data_id_pk":158,"language_name":"Chinese","language_code":"zh","language_url"
:"zh"},{"language_static_data_id_pk":159,"language_name":"Chineset","language_code":"zh-Hant","language_url"
:"zh-hant"},{"language_static_data_id_pk":160,"language_name":"Zulu","language_code":"zu","language_url"
:"zu"}][{"language_static_data_id_pk":1,"language_name":"Afar","language_code":"aa","language_url":"aa"},{"language_static_data_id_pk"
:2,"language_name":"Abkhazian","language_code":"ab","language_url":"ab"},{"language_static_data_id_pk"
:3,"language_name":"Afrikaans","language_code":"af","language_url":"af"},{"language_static_data_id_pk"
:4,"language_name":"Akan","language_code":"ak","language_url":"ak"},{"language_static_data_id_pk":5,"language_name"
:"Amharic","language_code":"am","language_url":"am"},{"language_static_data_id_pk":6,"language_name"
:"Arabic","language_code":"ar","language_url":"ar"},{"language_static_data_id_pk":7,"language_name":"Assamese"
,"language_code":"as","language_url":"as"},{"language_static_data_id_pk":8,"language_name":"Aymara","language_code"
:"ay","language_url":"ay"},{"language_static_data_id_pk":9,"language_name":"Azerbaijani","language_code"
:"az","language_url":"az"},{"language_static_data_id_pk":10,"language_name":"Bashkir","language_code"
:"ba","language_url":"ba"},{"language_static_data_id_pk":11,"language_name":"Belarusian","language_code"
:"be","language_url":"be"},{"language_static_data_id_pk":12,"language_name":"Bulgarian","language_code"
:"bg","language_url":"bg"},{"language_static_data_id_pk":13,"language_name":"Bihari","language_code"
:"bh","language_url":"bh"},{"language_static_data_id_pk":14,"language_name":"Bislama","language_code"
:"bi","language_url":"bi"},{"language_static_data_id_pk":15,"language_name":"Bengali","language_code"
:"bn","language_url":"bn"},{"language_static_data_id_pk":16,"language_name":"Tibetan","language_code"
:"bo","language_url":"bo"},{"language_static_data_id_pk":17,"language_name":"Breton","language_code"
:"br","language_url":"br"},{"language_static_data_id_pk":18,"language_name":"Bosnian","language_code"
:"bs","language_url":"bs"},{"language_static_data_id_pk":19,"language_name":"Catalan","language_code"
:"ca","language_url":"ca"},{"language_static_data_id_pk":20,"language_name":"Cebuano","language_code"
:"ceb","language_url":"ceb"},{"language_static_data_id_pk":21,"language_name":"Cherokee","language_code"
:"chr","language_url":"chr"},{"language_static_data_id_pk":22,"language_name":"Corsican","language_code"
:"co","language_url":"co"},{"language_static_data_id_pk":23,"language_name":"Seselwa","language_code"
:"crs","language_url":"crs"},{"language_static_data_id_pk":24,"language_name":"Czech","language_code"
:"cs","language_url":"cs"},{"language_static_data_id_pk":25,"language_name":"Welsh","language_code":"cy"
,"language_url":"cy"},{"language_static_data_id_pk":26,"language_name":"Danish","language_code":"da"
,"language_url":"da"},{"language_static_data_id_pk":27,"language_name":"German","language_code":"de"
,"language_url":"de"},{"language_static_data_id_pk":28,"language_name":"Dhivehi","language_code":"dv"
,"language_url":"dv"},{"language_static_data_id_pk":29,"language_name":"Dzongkha","language_code":"dz"
,"language_url":"dz"},{"language_static_data_id_pk":30,"language_name":"Greek","language_code":"el","language_url"
:"el"},{"language_static_data_id_pk":31,"language_name":"English","language_code":"en","language_url"
:"en"},{"language_static_data_id_pk":32,"language_name":"Esperanto","language_code":"eo","language_url"
:"eo"},{"language_static_data_id_pk":33,"language_name":"Spanish","language_code":"es","language_url"
:"es"},{"language_static_data_id_pk":34,"language_name":"Estonian","language_code":"et","language_url"
:"et"},{"language_static_data_id_pk":35,"language_name":"Basque","language_code":"eu","language_url"
:"eu"},{"language_static_data_id_pk":36,"language_name":"Persian","language_code":"fa","language_url"
:"fa"},{"language_static_data_id_pk":37,"language_name":"Finnish","language_code":"fi","language_url"
:"fi"},{"language_static_data_id_pk":38,"language_name":"Fijian","language_code":"fj","language_url"
:"fj"},{"language_static_data_id_pk":39,"language_name":"Faroese","language_code":"fo","language_url"
:"fo"},{"language_static_data_id_pk":40,"language_name":"French","language_code":"fr","language_url"
:"fr"},{"language_static_data_id_pk":41,"language_name":"Frisian","language_code":"fy","language_url"
:"fy"},{"language_static_data_id_pk":42,"language_name":"Irish","language_code":"ga","language_url":"ga"
},{"language_static_data_id_pk":43,"language_name":"Scots Gaelic","language_code":"gd","language_url"
:"gd"},{"language_static_data_id_pk":44,"language_name":"Galician","language_code":"gl","language_url"
:"gl"},{"language_static_data_id_pk":45,"language_name":"Guarani","language_code":"gn","language_url"
:"gn"},{"language_static_data_id_pk":46,"language_name":"Gujarati","language_code":"gu","language_url"
:"gu"},{"language_static_data_id_pk":47,"language_name":"Manx","language_code":"gv","language_url":"gv"
},{"language_static_data_id_pk":48,"language_name":"Hausa","language_code":"ha","language_url":"ha"}
,{"language_static_data_id_pk":49,"language_name":"Hawaiian","language_code":"haw","language_url":"haw"
},{"language_static_data_id_pk":50,"language_name":"Hindi","language_code":"hi","language_url":"hi"}
,{"language_static_data_id_pk":51,"language_name":"Hmong","language_code":"hmn","language_url":"hmn"
},{"language_static_data_id_pk":52,"language_name":"Croatian","language_code":"hr","language_url":"hr"
},{"language_static_data_id_pk":53,"language_name":"Haitian Creole","language_code":"ht","language_url"
:"ht"},{"language_static_data_id_pk":54,"language_name":"Hungarian","language_code":"hu","language_url"
:"hu"},{"language_static_data_id_pk":55,"language_name":"Armenian","language_code":"hy","language_url"
:"hy"},{"language_static_data_id_pk":56,"language_name":"Interlingua","language_code":"ia","language_url"
:"ia"},{"language_static_data_id_pk":57,"language_name":"Indonesian","language_code":"id","language_url"
:"id"},{"language_static_data_id_pk":58,"language_name":"Interlingue","language_code":"ie","language_url"
:"ie"},{"language_static_data_id_pk":59,"language_name":"Igbo","language_code":"ig","language_url":"ig"
},{"language_static_data_id_pk":60,"language_name":"Inupiak","language_code":"ik","language_url":"ik"
},{"language_static_data_id_pk":61,"language_name":"Icelandic","language_code":"is","language_url":"is"
},{"language_static_data_id_pk":62,"language_name":"Italian","language_code":"it","language_url":"it"
},{"language_static_data_id_pk":63,"language_name":"Inuktitut","language_code":"iu","language_url":"iu"
},{"language_static_data_id_pk":64,"language_name":"Hebrew","language_code":"iw","language_url":"iw"
},{"language_static_data_id_pk":65,"language_name":"Japanese","language_code":"ja","language_url":"ja"
},{"language_static_data_id_pk":66,"language_name":"Javanese","language_code":"jw","language_url":"jw"
},{"language_static_data_id_pk":67,"language_name":"Georgian","language_code":"ka","language_url":"ka"
},{"language_static_data_id_pk":68,"language_name":"Khasi","language_code":"kha","language_url":"kha"
},{"language_static_data_id_pk":69,"language_name":"Kazakh","language_code":"kk","language_url":"kk"
},{"language_static_data_id_pk":70,"language_name":"Greenlandic","language_code":"kl","language_url"
:"kl"},{"language_static_data_id_pk":71,"language_name":"Khmer","language_code":"km","language_url":"km"
},{"language_static_data_id_pk":72,"language_name":"Kannada","language_code":"kn","language_url":"kn"
},{"language_static_data_id_pk":73,"language_name":"Korean","language_code":"ko","language_url":"ko"
},{"language_static_data_id_pk":74,"language_name":"Kashmiri","language_code":"ks","language_url":"ks"
},{"language_static_data_id_pk":75,"language_name":"Kurdish","language_code":"ku","language_url":"ku"
},{"language_static_data_id_pk":76,"language_name":"Kyrgyz","language_code":"ky","language_url":"ky"
},{"language_static_data_id_pk":77,"language_name":"Latin","language_code":"la","language_url":"la"}
,{"language_static_data_id_pk":78,"language_name":"Luxembourgish","language_code":"lb","language_url"
:"lb"},{"language_static_data_id_pk":79,"language_name":"Ganda","language_code":"lg","language_url":"lg"
},{"language_static_data_id_pk":80,"language_name":"Limbu","language_code":"lif","language_url":"lif"
},{"language_static_data_id_pk":81,"language_name":"Lingala","language_code":"ln","language_url":"ln"
},{"language_static_data_id_pk":82,"language_name":"Laothian","language_code":"lo","language_url":"lo"
},{"language_static_data_id_pk":83,"language_name":"Lithuanian","language_code":"lt","language_url":"lt"
},{"language_static_data_id_pk":84,"language_name":"Latvian","language_code":"lv","language_url":"lv"
},{"language_static_data_id_pk":85,"language_name":"Mauritian Creole","language_code":"mfe","language_url"
:"mfe"},{"language_static_data_id_pk":86,"language_name":"Malagasy","language_code":"mg","language_url"
:"mg"},{"language_static_data_id_pk":87,"language_name":"Maori","language_code":"mi","language_url":"mi"
},{"language_static_data_id_pk":88,"language_name":"Macedonian","language_code":"mk","language_url":"mk"
},{"language_static_data_id_pk":89,"language_name":"Malayalam","language_code":"ml","language_url":"ml"
},{"language_static_data_id_pk":90,"language_name":"Mongolian","language_code":"mn","language_url":"mn"
},{"language_static_data_id_pk":91,"language_name":"Marathi","language_code":"mr","language_url":"mr"
},{"language_static_data_id_pk":92,"language_name":"Malay","language_code":"ms","language_url":"ms"}
,{"language_static_data_id_pk":93,"language_name":"Maltese","language_code":"mt","language_url":"mt"
},{"language_static_data_id_pk":94,"language_name":"Burmese","language_code":"my","language_url":"my"
},{"language_static_data_id_pk":95,"language_name":"Nauru","language_code":"na","language_url":"na"}
,{"language_static_data_id_pk":96,"language_name":"Nepali","language_code":"ne","language_url":"ne"}
,{"language_static_data_id_pk":97,"language_name":"Dutch","language_code":"nl","language_url":"nl"},
{"language_static_data_id_pk":98,"language_name":"Norwegian","language_code":"no","language_url":"no"
},{"language_static_data_id_pk":99,"language_name":"Ndebele","language_code":"nr","language_url":"nr"
},{"language_static_data_id_pk":100,"language_name":"Pedi","language_code":"nso","language_url":"nso"
},{"language_static_data_id_pk":101,"language_name":"Nyanja","language_code":"ny","language_url":"ny"
},{"language_static_data_id_pk":102,"language_name":"Occitan","language_code":"oc","language_url":"oc"
},{"language_static_data_id_pk":103,"language_name":"Oromo","language_code":"om","language_url":"om"
},{"language_static_data_id_pk":104,"language_name":"Oriya","language_code":"or","language_url":"or"
},{"language_static_data_id_pk":105,"language_name":"Punjabi","language_code":"pa","language_url":"pa"
},{"language_static_data_id_pk":106,"language_name":"Polish","language_code":"pl","language_url":"pl"
},{"language_static_data_id_pk":107,"language_name":"Pashto","language_code":"ps","language_url":"ps"
},{"language_static_data_id_pk":108,"language_name":"Portuguese","language_code":"pt","language_url"
:"pt"},{"language_static_data_id_pk":109,"language_name":"Quechua","language_code":"qu","language_url"
:"qu"},{"language_static_data_id_pk":110,"language_name":"Rhaeto Romance","language_code":"rm","language_url"
:"rm"},{"language_static_data_id_pk":111,"language_name":"Rundi","language_code":"rn","language_url"
:"rn"},{"language_static_data_id_pk":112,"language_name":"Romanian","language_code":"ro","language_url"
:"ro"},{"language_static_data_id_pk":113,"language_name":"Russian","language_code":"ru","language_url"
:"ru"},{"language_static_data_id_pk":114,"language_name":"Kinyarwanda","language_code":"rw","language_url"
:"rw"},{"language_static_data_id_pk":115,"language_name":"Sanskrit","language_code":"sa","language_url"
:"sa"},{"language_static_data_id_pk":116,"language_name":"Scots","language_code":"sco","language_url"
:"sco"},{"language_static_data_id_pk":117,"language_name":"Sindhi","language_code":"sd","language_url"
:"sd"},{"language_static_data_id_pk":118,"language_name":"Sango","language_code":"sg","language_url"
:"sg"},{"language_static_data_id_pk":119,"language_name":"Sinhalese","language_code":"si","language_url"
:"si"},{"language_static_data_id_pk":120,"language_name":"Slovak","language_code":"sk","language_url"
:"sk"},{"language_static_data_id_pk":121,"language_name":"Slovenian","language_code":"sl","language_url"
:"sl"},{"language_static_data_id_pk":122,"language_name":"Samoan","language_code":"sm","language_url"
:"sm"},{"language_static_data_id_pk":123,"language_name":"Shona","language_code":"sn","language_url"
:"sn"},{"language_static_data_id_pk":124,"language_name":"Somali","language_code":"so","language_url"
:"so"},{"language_static_data_id_pk":125,"language_name":"Albanian","language_code":"sq","language_url"
:"sq"},{"language_static_data_id_pk":126,"language_name":"Serbian","language_code":"sr","language_url"
:"sr"},{"language_static_data_id_pk":127,"language_name":"Siswant","language_code":"ss","language_url"
:"ss"},{"language_static_data_id_pk":128,"language_name":"Sesotho","language_code":"st","language_url"
:"st"},{"language_static_data_id_pk":129,"language_name":"Sundanese","language_code":"su","language_url"
:"su"},{"language_static_data_id_pk":130,"language_name":"Swedish","language_code":"sv","language_url"
:"sv"},{"language_static_data_id_pk":131,"language_name":"Swahili","language_code":"sw","language_url"
:"sw"},{"language_static_data_id_pk":132,"language_name":"Syriac","language_code":"syr","language_url"
:"syr"},{"language_static_data_id_pk":133,"language_name":"Tamil","language_code":"ta","language_url"
:"ta"},{"language_static_data_id_pk":134,"language_name":"Telugu","language_code":"te","language_url"
:"te"},{"language_static_data_id_pk":135,"language_name":"Tajik","language_code":"tg","language_url"
:"tg"},{"language_static_data_id_pk":136,"language_name":"Thai","language_code":"th","language_url":"th"
},{"language_static_data_id_pk":137,"language_name":"Tigrinya","language_code":"ti","language_url":"ti"
},{"language_static_data_id_pk":138,"language_name":"Turkmen","language_code":"tk","language_url":"tk"
},{"language_static_data_id_pk":139,"language_name":"Tagalog","language_code":"tl","language_url":"tl"
},{"language_static_data_id_pk":140,"language_name":"Tswana","language_code":"tn","language_url":"tn"
},{"language_static_data_id_pk":141,"language_name":"Tonga","language_code":"to","language_url":"to"
},{"language_static_data_id_pk":142,"language_name":"Turkish","language_code":"tr","language_url":"tr"
},{"language_static_data_id_pk":143,"language_name":"Tsonga","language_code":"ts","language_url":"ts"
},{"language_static_data_id_pk":144,"language_name":"Tatar","language_code":"tt","language_url":"tt"
},{"language_static_data_id_pk":145,"language_name":"Uighur","language_code":"ug","language_url":"ug"
},{"language_static_data_id_pk":146,"language_name":"Ukrainian","language_code":"uk","language_url":"uk"
},{"language_static_data_id_pk":147,"language_name":"Urdu","language_code":"ur","language_url":"ur"}
,{"language_static_data_id_pk":148,"language_name":"Uzbek","language_code":"uz","language_url":"uz"}
,{"language_static_data_id_pk":149,"language_name":"Venda","language_code":"ve","language_url":"ve"}
,{"language_static_data_id_pk":150,"language_name":"Vietnamese","language_code":"vi","language_url":"vi"
},{"language_static_data_id_pk":151,"language_name":"Volapuk","language_code":"vo","language_url":"vo"
},{"language_static_data_id_pk":152,"language_name":"Waray Philippines","language_code":"war","language_url"
:"war"},{"language_static_data_id_pk":153,"language_name":"Wolof","language_code":"wo","language_url"
:"wo"},{"language_static_data_id_pk":154,"language_name":"Xhosa","language_code":"xh","language_url"
:"xh"},{"language_static_data_id_pk":155,"language_name":"Yiddish","language_code":"yi","language_url"
:"yi"},{"language_static_data_id_pk":156,"language_name":"Yoruba","language_code":"yo","language_url"
:"yo"},{"language_static_data_id_pk":157,"language_name":"Zhuang","language_code":"za","language_url"
:"za"},{"language_static_data_id_pk":158,"language_name":"Chinese","language_code":"zh","language_url"
:"zh"},{"language_static_data_id_pk":159,"language_name":"Chineset","language_code":"zh-Hant","language_url"
:"zh-hant"},{"language_static_data_id_pk":160,"language_name":"Zulu","language_code":"zu","language_url"
:"zu"}]



copy this all json array and put into js/language.json 


hope you reply soon

**Comment by mlynch** [comment]
Closing, need more info and a working example. Thanks!
