### ISSUE TITLE
bug: $ionicConfig.views.swipeBackEnabled does not work

### ISSUE THREAD

**Issue by marcelfalliere** [driftyco/ionic#4574]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>

**ionic bundle version** v1.1.0

Since #3470 is closed, I'm opening a new one.

I have the following code (that I believe should be the default on iOS, but whatever) :

    $scope.$watch(function () { return $ionicSideMenuDelegate.isOpenRight(); }, function (isOpen) {
      if (isOpen){
        $ionicConfig.views.swipeBackEnabled(false);
      } else {
        $ionicConfig.views.swipeBackEnabled(true);
      }
    });

This code simply disables the swipe to go back when the right side menu is opened. Why is this needed ? Because the user closes the side menu with a swipe (or a more slow drag and drop (btw that feature is awesome)) that also goes back in the history.

Unfortunately, `$ionicConfig.views.swipeBackEnabled(true/false);` is not working :'(

Some steps to reproduce :
  - platform : iOS 
  - ionic version v1.1.0
  - ionic app with a `ion-side-menu side="right"` and a `ion-nav-view` 
  - users navigates to a sub route (let's say from route "foo" to route "foo.bar" in the `ion-nav-view`)
  - users opens the right side-menu
  - users slowly swipes from left ro right
  - **Bug** : the right menu closes **AND** the view navigates back

Is that clear enough ? I can make a video since it's pretty specific, if necessary. I understand describing an animation/user-interaction bug is hard.

Regards

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @marcelfalliere!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4574). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4574)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by marcelfalliere** [comment]
anyone ? :'(

**Comment by yemaw** [comment]
Same here. The page transaction animation showing two times when swipe and go back.  :"(
$ionicConfig.views.swipeBackEnabled not working

**Comment by johnmiroki** [comment]
$ionicConfigProvider.views.swipeBackEnabled(false) doesn't work for me either. Still can swipe back on iOS and will stuck in a blank page if the previous page is not cached and there is no way for me to go back or force but have to restart the app.

**Comment by khadirbaaoua** [comment]
Encountering the same issue. Can't disable swipBackEnabled in iOS. Tried all of the above but still experiencing the issue

**Comment by johnmiroki** [comment]
@khadirbaaoua if you have tried $ionicConfig.views.swipeBackEnabled(false) and it didn't work, there is a brutal fix you can try: find all swipeBackEnabled variables in ionic.bundle.js or ionic-angular.js and change its value to false

**Comment by khadirbaaoua** [comment]
Thanks for the trick. I managed to solve the issue. It had nothing to do with swipeBackEnabled (which actually works quite fine)

**Comment by khadirbaaoua** [comment]
Here's the line that was causing the issue on my side : 

`$ionicConfigProvider.views.forwardCache(true)`

By commenting out that line, things finally work as expected

**Comment by johnmiroki** [comment]
@khadirbaaoua can't verify it on my side for now, but FWIW, I do have $ionicConfigProvider.views.forwardCache(true) in my project. Will test it later. Thanks!

**Comment by marcelfalliere** [comment]
$ionicConfigProvider is in a `.config(`, isn't it ?

This works, as well as `<ion-view can-swipe-back="false">` for a specific view.

My use case is a bit different : on the same view and depending on user actions, I want to disable the swipe to go back feature.

Unfortunately `can-swipe-back` does not take a model as parameter... 

And or little friend `$ionicConfig.views.swipeBackEnabled()` **inside a controller** does not work either.

Even in 1.2.1

**Comment by sbatezat** [comment]
@marcelfalliere Please find bellow a working workaround for this issue (at least on Ionic @1.2.4). I agree it should be the default behavior on iOS.

$scope.$watch(function () { return $ionicSideMenuDelegate.isOpenRight(); }, function (isOpen) {
    $ionicHistory.currentView().canSwipeBack = !isOpen;
});

**Comment by danbucholtz** [comment]
Hi @marcelfalliere,

Dan from Ionic here.  Is there anything you want changed in the framework for this issue?  It seems like there are several different things being discussed here.

Please let me know what I can do to help you out.  If you could provide a codepen of your issue, even better.

We appreciate you using Ionic.

Thanks,
Dan

**Comment by sbatezat** [comment]
Hi @danbucholtz,

There is no several different things being discussed by @marcelfalliere here. This thread has been polluted by other defect from others users, but the one from @marcelfalliere is clear enough. Just run an application with different screens on an iPhone with the ion-slide-menu and you will see the defect he's describing. Alternatively, to have more details, read the first message from @marcelfalliere.

Thanks for your understanding
Sébastien

**Comment by danbucholtz** [comment]
Cool - I am looking at the linked thread right now.  This fix will be in the next Ionic 1.x release.

Thanks,
Dan

**Comment by marcelfalliere** [comment]
@danbucholtz

thanks ! 

@sbatezat 

indeed !

**Comment by danbucholtz** [comment]
This is resolved in [this](https://github.com/driftyco/ionic/commit/c375b6e9b010e45816e53dc8ab493dbb6d28b2fa) commit.

**Comment by sbatezat** [comment]
From what I can see (I didn't tested your code, just read it), your commit is not resolving the main issue. You should add something like "$ionicSideMenuDelegate.isOpenRight()" on the following condition:

`if ( !$ionicConfig.views.swipeBackEnabled() || ! ionic.Platform.isIOS() )`

Thus, I think it should be 

`if ( !$ionicConfig.views.swipeBackEnabled() || ! ionic.Platform.isIOS() || !$ionicSideMenuDelegate.isOpenRight())`

**Comment by sbatezat** [comment]
Not tested, but should work: PR #6066

**Comment by danbucholtz** [comment]
Hi @sbatezat, ahh, good catch.  We were resolving multiple issues with that commit. I will make sure we account for the side menu being open.  Thanks!
