### ISSUE TITLE
bug: Basic Grid not working on iOS 8.4.1 iPad Mini?

### ISSUE THREAD

**Issue by noerK** [driftyco/ionic#4578]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hey there :)

First: I really enjoy working with ionic - thank for bringing us this project!

I have markup as shown below and it works fine on browsers and iOS-Sim, but when it gets deployed on an iPad Mini with iOS 8.4.1 the cols are listed below each other - not horizontally.
Any ideas?

```
<ion-nav-bar class="bar-stable">
  <ion-nav-title>Title</ion-nav-title>
</ion-nav-bar>
<ion-nav-view  hide-back-button="true" cache-view="false">
  <ion-view>
    <ion-content class="has-header">

      <div class="row">

        <div  class="col-33">
          <div class="list card">
            <div class="item item-divider">
              Title-List A
            </div>
            <a class="item item-text-wrap">Item A</a>
            <a class="item item-text-wrap">Item B</a>
            <a class="item item-text-wrap">Item C</a>
          </div> 
        </div>

        <div  class="col-33">
          <div class="list card">
            <div class="item item-divider">
              Title-List A
            </div>
            <a class="item item-text-wrap">Item A</a>
            <a class="item item-text-wrap">Item B</a>
            <a class="item item-text-wrap">Item C</a>
          </div> 
        </div>   

        <div  class="col-33">
          <div class="list card">
            <div class="item item-divider">
              Title-List A
            </div>
            <a class="item item-text-wrap">Item A</a>
            <a class="item item-text-wrap">Item B</a>
            <a class="item item-text-wrap">Item C</a>
          </div> 
        </div>

      </div>
  
    </ion-content>
  </ion-view>
</ion-nav-view>
```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @noerK!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4578). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4578)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zanemcca** [comment]
+1

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by SylviaChoong** [comment]
Hi, I'm having similar issue of col stacking vertically instead of horizontally. The codes are like this:
<div class="row">
   <div class="col">col</div>
   <div class="col">col</div>
</div>

May I know how can I make the cols to arrange horizontally?
