### ISSUE TITLE
bug: side menu opens 2 views when using state.resolve with a delayed promise.

### ISSUE THREAD

**Issue by tohagan** [driftyco/ionic#4596]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've created a Plunker example based on side bar starter app for Ionic v1.1.0.  I've  modified it so that the  **app.playlist** state uses a **resolve** attribute to return the playlists array using a $q promise with a 1000 ms delay.

Steps to reproduce:

0. Start [Plunker Demo](http://plnkr.co/edit/rdRDA4oppOabWmzw43zR?p=preview)

1. Select Browse menu option 
   - Browse view displays normally

2. Select Playlist menu option 
   - Displays Browse view (!) with header menu button 
   - 1 sec later it then pushes the Playlist view showing both menu button and now also a <Back button !

In general it always displays the most recently selected view and then the selected view after the promise resolves.

**What this means is that Ionic apps cannot safely use the ui-router resolve feature for any menu selected controller which is, IMHO, a rather severe limitation.  So I personally think this issue should be fairly high priority.**

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @tohagan!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4596). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4596)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by tohagan** [comment]
My my desktop Chrome,  it appears to only occur when the delay is >= 290 ms.

Perhaps the side bar directive is not waiting for [`$stateChangeSuccess`](https://github.com/angular-ui/ui-router/wiki#resolve) event from `$stateProvider`

**Comment by tohagan** [comment]
I've also posted this as [an issue](https://github.com/angular-ui/ui-router/issues/2360) with AngulrJS ui-router as I now suspect the issue is more likely there though it seems rather unusual that it's not been identified earlier given that they implemented the resolve feature.

**Comment by tohagan** [comment]
Angular ui-router team report that they think it not their issue. Can you please investigate?

**Comment by ligerdave** [comment]
experiencing the same issue here. can anyone plz help?

**Comment by ligerdave** [comment]
@tohagan have you tried with ionic 1.0.0?

**Comment by tohagan** [comment]
I've just forked and updated to 1.0.0 in [new Plunker demo](http://plnkr.co/edit/SVOFLxQESCiU4XY74mTz?p=preview) and it exhibits the same issue:

**Comment by ligerdave** [comment]
yeh, i tried as well. same issue. :(

**Comment by ErickMC** [comment]
Having the same issue with a similar layout. Only difference in my case is that only the back button remains, not both. 

It breaks our navigation, and forces us to use less effective ways to load our data. Hope we can see a fix or sensible workaround.

**Comment by olegabu** [comment]
confirm. same behaviour in my app. had to move all resolves into a parent state which is a limitation

**Comment by danbucholtz** [comment]
Hi @tohagan and others,

Just letting you know that we are starting to take a look at this.  The way we designed the Ionic navigation did not account for resolve functionality of ui-router, so sometimes everything works fine with resolve, other times it doesn't work quite right (for example, when views are cached).  We're really sorry about that.

I'll take a look and see if this is an issue we can fix on our end, otherwise I will come up with some simple work arounds.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @tohagan,

I don't think we're going to be able to make a change to support resolve in this use case.  We are sorry about that.  We just think it's too risky of a change to make.

Our recommended approach is to move the logic presently in your `resolve` function to occur either before or after the transition.  An option is to use the [loader service](http://ionicframework.com/docs/api/service/$ionicLoading/) to inform the users that data is being fetched/processed.

Please let me know if you have any comments, questions, etc.

Thank you for contributing and choosing Ionic.  We appreciate it!

Thanks,
Dan

**Comment by tohagan** [comment]
Thanks Dan.  This is a really useful feature of Angular so hoping you can fix it in Ionic. 

Appreciate your getting back to me as I though this issue had been shelved. 

Cheer,
Tony 

Brisbane, Australia

**Comment by tohagan** [comment]
Ok. Thanks for giving. It some serious thought. I understand that keeping things backward compatible and stable is highest priority.  

Tony

**Comment by manzapanza** [comment]
Hi @tohagan,
I solved this problem decorating the closeMenu directive. This directive has a 300 millisenconds hardcoded delay that cause apparently this problem. I solved listening the event $stateChangeSuccess and waiting more 100 milliseconds:

```
(function () {
  'use strict';

  /** @ngInject */
  function config($provide) {

    /** @ngInject */
    function closeMenuDirectiveDecorator($delegate, $ionicHistory, $timeout) {
      var directive = $delegate[0];

      var link = function (scope, element) {
        element.bind('click', function() {
          var sideMenuCtrl = element.inheritedData('$ionSideMenusController');
          if (sideMenuCtrl) {
            $ionicHistory.nextViewOptions({
              historyRoot: true,
              disableAnimate: true,
              expire: 500
            });

            var fn = scope.$on('$stateChangeSuccess', function($event) {
              $timeout(function(){
                $ionicHistory.nextViewOptions({
                  historyRoot: false,
                  disableAnimate: false
                });
              }, 100);

              fn();
            });

            sideMenuCtrl.close();
          }
        });
      };

      directive.compile = function() {
        return function(scope, element) {
          link.apply(this, arguments);
        };
      };

      return $delegate;
    }

    $provide.decorator('menuCloseDirective', closeMenuDirectiveDecorator);
  }

  angular
    .module('app')
    .config(config);

})();
```
For me this decorator works, but feels free to improve it.
