### ISSUE TITLE
bug: Ionic V2  _es6shim_iterator_

### ISSUE THREAD

**Issue by gfeller** [driftyco/ionic#4599]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Symbol_iterator.js uses "_es6shim_iterator_"  as iterator name
but the es6-shim.js defines the iterator with: _es6-shim iterator_ 

This leads to following error: 
TypeError: Object doesn't support property or method '_es6shim_iterator_'</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Not sure what the issue is here or if it's related to Ionic (doesn't seem like it). Let me know if you have more info, but going to close in the meantime.
