### ISSUE TITLE
bug: Gestures don't work with ion-header-bar

### ISSUE THREAD

**Issue by borNfreee** [driftyco/ionic#4609]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I try to use `on-swipe-right` with the `ion-header-bar` directive, but it doesn't work.
Codepen: http://codepen.io/anon/pen/jbewzq?editors=101</span>

<span is-issue-template></span>

**Comment by danbucholtz** [comment]
Hi @borNfreee,

I am not seeing this.  All gestures are being detected on my end.  Please let me know if you're still having issues.

Thanks,
Dan
