### ISSUE TITLE
bug: .view-container is scrollable in android 6

### ISSUE THREAD

**Issue by shtaft** [driftyco/ionic#4610]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Wasn't able to select my os- true os is android 6. This bug doesn't happen in the browser.

Ion-header is scrollable if the user touches it and scrolls. This happens with the following side menus setup:
ion-side-menus
 ion-side-menu-content
  ion-nav-bar
...
  /ion-nav-bar
 /ion-side-menu-content
...
/ion-side-menus

The view-container, a parent of the ion-header, is positioned as an absolute element, which allows it to be scrolled out of the view. I assume this is not intended.
This can be fixed with the following css, although I have not tested this on other devices:

.view-container {
  position: fixed !imporant;
}</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? I was not able to reproduce with my Nexus 6 running the Android N Dev Preview. Thanks!

**Comment by shtaft** [comment]
@jgw96 looks like it's fixed with the latest Ionic. Thanks!! Tested with Nexus 5 running latest Android M.
