### ISSUE TITLE
bug: Form input focus overlap over header on keyboard.

### ISSUE THREAD

**Issue by sanjeevthapa** [driftyco/ionic#4619]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>The issue is generally about the form input focus cursor overlapping over a header bar once the keyboard is open. lets sy I have a form in my view and once i try to input something keyboard opens and then if i scroll the view I can see the cursor above header.</span>

<span is-issue-template></span>

**Comment by sanjeevthapa** [comment]
![screen shot 2015-11-10 at 10 39 06 am](https://cloud.githubusercontent.com/assets/3711565/11059015/53a8d0aa-8797-11e5-923a-f56427080aa7.png)
![screen shot 2015-11-10 at 10 38 46 am](https://cloud.githubusercontent.com/assets/3711565/11059016/53abb5ea-8797-11e5-8caf-df3f920ee614.png)

See the screenshots. I just started an new ionic tabs app.

**Comment by sanjeevthapa** [comment]
At the end i did not found a good fix for this. So I decided to hide the keyboard if the user scroll a bit longer once the keyboard is opened. I wanted to my user to select or scroll the input when the keyboard is not opened.

Here is a quick snippet sample that I used.

	$rootScope.getScrolled = function(){
		console.log('rame');
		var scrollTop = $ionicScrollDelegate.getScrollPosition().top;		
		if (window.cordova && window.cordova.plugins.Keyboard) {
			if(cordova.plugins.Keyboard.isVisible && scrollTop > 30){
				//close the keyboard
				console.log('unexpected behaviour trying to scroll on keyboard open');
				cordova.plugins.Keyboard.close();
			}
		}
	}

**Comment by ljkumo** [comment]
hey dude, the same problem occurred to my project. Is there any updates to fix that?

**Comment by duyminhbk** [comment]
Hi everyone, I have gotten the same problem on footer and header, have any idea to resolve that?

**Comment by duyminhbk** [comment]
Hi team, here is my problem

![ezgif com-resize](https://cloud.githubusercontent.com/assets/5144667/11414497/7b661a42-9428-11e5-822c-79e88024ba78.gif)

**Comment by emiledskar** [comment]
same issue here

**Comment by edWAR6** [comment]
Any ideas?

**Comment by niagara18** [comment]
Same issue here. A fix, workaround or some idea very welcome.

**Comment by kaustubhkushte** [comment]
+1

**Comment by jgw96** [comment]
Hello! Would you mind telling me what version of ionic you are currently using?

**Comment by duyminhbk** [comment]
I used ionic with version 1.1.1 and got this issue

**Comment by kaustubhkushte** [comment]
I am using 1.2.4

**Comment by danbucholtz** [comment]
Hello everyone,

Dan from Ionic here.

Unfortunately there is nothing we can do about this at this time.  Ionic/Cordova uses UIWebView from Apple behind the scenes, and this is a limitation of that.  WKWebView is the name of the "next gen" Safari engine from Apple, and it is much better and more flexible.  Basically - it gives us access to "events" that UIWebView does not.  Unfortunately, there are some known limitations to using WKWebView in Ionic/Cordova apps at this time.  We will keep the community in the loop with this issue.

For now, I am going to mark this as wontfix, but we will resolve this as soon as we can.

Thanks,
Dan

**Comment by rayashi** [comment]
Same problem here! 
Any solution ?

thanks

**Comment by sugir93** [comment]
any solution for this problem?

**Comment by rayashi** [comment]
Unfortunely no

2016-07-09 5:39 GMT-03:00 sugir93 <notifications@github.com>:

> any solution for this problem?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/driftyco/ionic/issues/4619#issuecomment-231523483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABar7wywEpxcf0mWB2M9SwdaYpKZVfHGks5qT15bgaJpZM4GfRa0>
> .
>



-- 

*Humberto Dib Rayashi*

**Comment by mashah1** [comment]
Hello All, Is there anyone who found solution on this?

**Comment by ankitch01** [comment]
workaround: hide the keyboard while scrolling

**Comment by mashah1** [comment]
@ankitch01 Can you please tell me where to add hiding keyboard?

**Comment by mashah1** [comment]
@ioanis @Ionitron Did you guyz fixed this issue(except hiding keyboard on scroll)?

**Comment by ullasmohan** [comment]
Hey.. The same problem occurred to my project. Is there any updates to fix that?

**Comment by JLNNN** [comment]
+1

**Comment by jayaj12** [comment]
The same problem in my project too. Is there any fixes?

**Comment by Salonisaikia** [comment]
Hey Guys, 
Any update on this? I am also facing the same issue.

**Comment by hungtranpg** [comment]
Same issue on Ionic 1.3.2
Have any solution to fix it?

**Comment by nasy** [comment]
Any updates on this issue? I am facing the same problem. Thanks!
