### ISSUE TITLE
bug: the keyboard doesn't work well in android

### ISSUE THREAD

**Issue by hxzAugustinus** [driftyco/ionic#4620]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>please see  the  picture 
<html>
  <div  style='height:620px;'>
  <img src='https://raw.githubusercontent.com/hxzAugustinus/gitProject/master/pic/bbb.gif'  style='margin-top:-20px;'>
  </div>
<html>
when i click  1 input  , 2 input  and  after 4 input , it works well.However when i click  3 input ,the tabs  just  covers   the  3 input, when i  add some number, the 3 input  just  shoot  up  and  then  you will find  that in the content bottom there is an extra dimension.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello (: Are you still experiencing this issue with the latest version of ionic?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again
