### ISSUE TITLE
bug: iOS Control Center scrolling bug

### ISSUE THREAD

**Issue by zlorant** [driftyco/ionic#4621]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a page that has a lot of content in it, so scrolling is enabled. 
On this page when I try to swipe up the control center from the bottom of the screen, this scrolls the content of the page as well. 
This looks odd to the users and I'm looking for a solution that fixes this behavior. 
The issue can be reproduced on both physical devices and simulators. 
I'm on ionic CLI 1.7.8 and ionic lib 1.1.1.

Thanks.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
