### ISSUE TITLE
bug: ion-tab angular-translate

### ISSUE THREAD

**Issue by psgganesh** [driftyco/ionic#4624]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I use angular-translate the below way; but does not seem to work on ion-tabs
```html
<ion-tab title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111044/eb9e81ca-8936-11e5-8714-c473b7739424.png)

But when it is 
```html
<ion-tab translate="coffee_title_label" title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111034/cdaa8790-8936-11e5-9408-043d322f0e02.png)

I referred the below codepen example
http://codepen.io/andrewmcgivery/pen/tqymb

Can you let me know, what am doing wrong here !</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @psgganesh!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4624). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4624)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by leonardosalles** [comment]
I think ion tabs have some issues with two-way data bind, I tried to use it with ng-repeat and it not worked properly, when I did a little search for bugs with it, I can easy find a bug with tabs and it cannot be solved  by ionic team right now.

**Comment by jgw96** [comment]
Hello (: are you still experiencing this issue?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again

**Comment by leonardosalles** [comment]
Hi,

Sorry for my down time, yep I still getting the issue, I solved it by adding a css class, but we need to check why this 'hide' class are added to the nav bar.

Thanks

**Comment by nirarazi** [comment]
Hi,
is there any known solution to this?
I'm still experiencing it...

THANKS!

**Comment by leonardosalles** [comment]
Hi @nirarazi,

I created this workaround as a directive:

PS: the pg-title-handler attribute at ion-nav-bar is important and it will not work if you miss that parameter in your view.

Controller
```
 $scope.$broadcast('$pgSetTitle.done', ['talhaoSafrasTitle', $stateParams.title]);
```
Directive
```
(function () {
    angular.module('prograo.core').directive('pgSetTitle', pgSetTitle);

    function pgSetTitle () {
        return {
            restrict: 'A',
            link : function(scope, element, attrs) {
                var NAV_BAR_SELECTORS = {
                    active: '.nav-bar-block[nav-bar="active"]',
                    cached: '.nav-bar-block[nav-bar="cached"]',
                    title: '.title'
                };

                scope.$on('$pgSetTitle.done', function (pgSetTitle, args) {
                    if (args && args.length === 2) {
                        var handler = document.querySelector('[pg-title-handler="' + args[0] +'"]');

                        if (handler) {
                            var activeNavBar = handler.querySelector(NAV_BAR_SELECTORS.active),
                                cachedNavBar = handler.querySelector(NAV_BAR_SELECTORS.cached);

                            if (activeNavBar) {
                                var title = activeNavBar.querySelector(NAV_BAR_SELECTORS.title);

                                if (title) {
                                    if (title.innerHTML && cachedNavBar) {
                                        title = cachedNavBar.querySelector(NAV_BAR_SELECTORS.title);
                                    }

                                    title.innerHTML = args[1];
                                }
                            }
                        }
                    }
                });
            }
        };
    }
})();
```

View
```
<ion-view pg-set-title="true">
    <ion-nav-bar align-title="center" class="bar-prograo bar-positive" pg-title-handler="talhaoSafrasTitle">
        <div class="buttons">
              <ion-nav-back-button>
              </ion-nav-back-button>
        </div>
    </ion-nav-bar>

    <ion-content class="safras padding">
    	<ion-list>
    	   <div ng-repeat="activity in vm.safra.activities" class="margin-bottom">
    	       <show-activity activity="activity" remove-activity="vm.removeActivity" index="$index"></show-activity>
    	   </div>
		</ion-list>

        <div ng-if="!vm.safra.activities.length && vm.loaded" class="no-data-alert text-center">
            <img src="static/img/no-activity-season.png" alt="{{'activities.noActivity' | translate}}" width="70">

            <h4>{{'activities.noActivity' | translate}}</h4>
            <h5>{{'activities.goBackRegister' | translate}}</h5>
        </div>
    </ion-content>
</ion-view>
```

**Comment by nirarazi** [comment]
@leonardosalles I will try that, THANKS!
