### ISSUE TITLE
bug: ion-refresher not work with overflow-scroll=false

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#4627]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I have to use ion-content with overflow-scroll=true. Both ion-refresher and ion-infinity-scroll work, but ion-refresher would not show the spinning circle again after ion-infinity-scroll is triggered once. The on-refresh function is not triggered neither. This only happens in ios simulator. It works in web browser.

When I inspected the DOM in Safari, I could still see the scroll-refresher div.

http://forum.ionicframework.com/t/when-using-overflow-scroll-true-ion-refresher-disappeared-after-infinity-scroll-is-triggered-once/35537</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This won't work in iOS since ios doesn't provide the appropriate scroll events, which both refersher and infinite-scroll need.
