### ISSUE TITLE
bug: range inputs not working on ios9

### ISSUE THREAD

**Issue by bownie** [driftyco/ionic#4628]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Slight twist on issue (github) #1078 - I'm using a range input in a modal popup.  The input doesn't get the events at all under ios9. I've tried turning off scroll on the ion-content but still no joy. Works in the browser but not on the simulator or device.  Raising this as a separate issue as I can't reopen the original and this seems a bit more straightforward breakage.

Originally got this issue on 1.6.5 and have just updated to 1.7.8 and confirm it's still the same.  Screenshot attached of the modal - all elements work apart from the range inputs.

![simulator screen shot 12 nov 2015 21 39 09](https://cloud.githubusercontent.com/assets/2190729/11130536/d8b4d9d4-8985-11e5-9cf6-51f5498049e1.png)</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bownie!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4628). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4628)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Hmm, not seeing this in my test. Started a project with a modal, added the following code to the modal

```
      <div class="list">
        <div class="item range range-positive">
          <i class="icon ion-ios-sunny-outline"></i>
          <input type="range" name="volume" min="0" max="100" value="33">
          <i class="icon ion-ios-sunny"></i>
        </div>
      </div>
```
ran on my iphone running ios9 with no problems. 

Could you provide an example or demo to work from?

**Comment by bownie** [comment]
Thanks.  You're right it works.  It's my dialog that is breaking the behaviour.  It's included below - if I remove the first input type (text selectedStation.Name) or if I paste your example at the top of the ion-content section then the range inputs (all of them) work.  If I leave it as below the range inputs don't work.

```
<div class="modal" ng-controller="StationCtrl">
    <ion-header-bar class="bar-stable">
          <h1 class="title">{{'Edit station' | translate}}</h1>
    </ion-header-bar>
    <ion-content class="padding" has-header="true" padding="true">
      <div class="list">
        <label class="item item-input">
          <span class="input-label">{{'Station name'|translate}}</span>
          <input type="text" placeholder="Station name" ng-model="selectedStation.name" required>
        </label>
          <ion-checkbox ng-model="selectedStation.ignore_rain">{{'Ignore sensor'|translate}}</ion-checkbox>
          <ion-checkbox ng-model="selectedStation.disabled">{{'Disabled'|translate}}</ion-checkbox>
          <ion-checkbox ng-model="selectedStation.sequential">{{'Sequential'|translate}}</ion-checkbox>
      </div>
      <div class="list">
          <ion-toggle ng-model="moistureAlert.enabled" toggle-class="toggle-positive">
            <div ng-show="moistureAlert.enabled">
            {{'Alert enabled'|translate}} : {{moistureAlert.min}} % - {{moistureAlert.max}} %
            </div>
            <div ng-show="!moistureAlert.enabled">
            {{'Alert disabled'|translate}}
            </div>
          </ion-toggle>
          <div class="item range range-positive" ng-show="moistureAlert.enabled">
            <i class="icon ion-ios-plus-outline"></i>
              <input type="range" name="volume" min="0" max="100" ng-model="moistureAlert.max">
              <i class="icon ion-ios-plus"></i>
          </div>
          <div class="item range range-positive" ng-show="moistureAlert.enabled">
            <i class="icon ion-ios-minus-outline"></i>
              <input type="range" name="volume" min="0" max="100" ng-model="moistureAlert.min">
              <i class="icon ion-ios-minus"></i>
          </div>
        <button class="button button-block button-positive" ng-click="updateStation()">{{'Submit'|translate}}</button>
        <button class="button button-block button-cancel" ng-click="cancel()">{{'Cancel'|translate}}</button>
      </div>
    </ion-content>
</div>
```

**Comment by mhartington** [comment]
Would you mind throwing this into a codepen with mock data

**Comment by bownie** [comment]
Well I've put the salient pieces into a codepen but it won't tell you much as this is an iOS9 problem.  The range inputs work fine in the browser.  As I said in my last comment I can get it working by removing the first text input.

http://codepen.io/bownie/pen/ZbwYOB

**Comment by bownie** [comment]
Ok after some playing around I've got to the bottom of the problem.  This is to do with input focus.  When the input type="text" is the first field on the modal then in iOS this input grabs focus but it doesn't show that it has focus as there is no keyboard.  If you click on the text input, it pops up a keyboard and then on returning from it the range inputs on the modal become responsive.   Curiously the ion-checkboxes are responsive without this focus so this is where the confusion arises.

If I move the text input to be the second input type on the modal then this issues goes away.

So it would appear there is an inconsistency which I can work around clumsily as above - is there a better way to do this (force focus elsewhere or remove focus?) and the wider question is is there a bug here to be fixed?

**Comment by wggley** [comment]
+1 for input type text being first is the issue.
In my case buttons above become unresponsive.

**Comment by felixja** [comment]
What about having a list full of text inputs?? :S I can't see the way to make it work...

Thanks!

**Comment by robinvanb** [comment]
Having the same problem here. When a modal has a text input the range input becomes unresponsive.
Any workaround for this?

**Comment by artzstudio** [comment]
This issue appears to be related to a bug I just opened here: https://github.com/driftyco/ionic/issues/5346

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by barkoczi** [comment]
This bug still in system. Ionic v1.3.1

If i focus any input/select element on my form then i can't change input[type=range]. If form is pristine, the range input works well. 

This problem appears only in mobile app (ios9), app works well in chrome.

**Comment by DrakeWitt** [comment]
+1 also experiencing issues with iOS 9 and 10. Works fine in chrome.

**Comment by zakrava** [comment]
Range input is unresponsive on iOS9, on android works great.
