### ISSUE TITLE
bug: Secure Google API or any way to add referer ?

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#4635]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>I've been going to publish my app in coming week, just worried are my Google and Facebook api keys used are secured as i am not able to use any referer for any services in my google console as well as facebook's console. 

I'm using 
Google Static Maps to load static map in a img element like
http://maps.googleapis.com/maps/api/staticmap?zoom=16&scale=false&size=600x300&maptype=roadmap&key=XXXXXXAPI_KEYXXXXXXX&format=png&visual_refresh=true&markers=size:mid%7Cicon:img

GCM (used ionic docs) , i can find gcm key in ionic service core/ core.js in $ionicCoreSettings factory 

and facebook login with ng-cordova oauth in my app.js

after googling long hours of negative feedback found below link to add referer to ios UIWebView

http://stackoverflow.com/questions/7913305/specifying-http-referer-in-embedded-uiwebview/7913433#7913433

our app will be on Android as of now.

Any help
Thanks</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
