### ISSUE TITLE
feat: Slide Box disable drag right on first slide

### ISSUE THREAD

**Issue by agrawalravi95** [driftyco/ionic#4647]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>In the slide box, I am trying to prevent drag right on the first slide and drag left on the last slide. But I haven't been able to figure it out. Can someone help me out?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
