### ISSUE TITLE
bug: BUG can't open ios simulator with xcode 7

### ISSUE THREAD

**Issue by Quesle** [driftyco/ionic#4657]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I install cordova and ionic to develop app with ios, my xcode version is 7.1.0, but when i use command 
```shell
ionic emulate ios
```
 the Simulator opened, but do nothing.

and moment for a while, the terminal show the log, like below:

```
** BUILD SUCCEEDED **

No target specified for emulator. Deploying to iPhone-6 simulator
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
ENOENT: no such file or directory, stat '/Users/Fernando/Library/Logs/CoreSimulator/3804D671-203A-45F2-A689-1D18D049EC91/system.log'
Error code 1 for command: ios-sim with args: launch,/Users/Fernando/Develop/dev/Javascript/Demos/ionic_demo/platforms/ios/build/emulator/HelloCordova.app,--devicetypeid,com.apple.CoreSimulator.SimDeviceType.iPhone-6,--stderr,/Users/Fernando/Develop/dev/Javascript/Demos/ionic_demo/platforms/ios/cordova/console.log,--stdout,/Users/Fernando/Develop/dev/Javascript/Demos/ionic_demo/platforms/ios/cordova/console.log,--exit
Error: /Users/Fernando/Develop/dev/Javascript/Demos/ionic_demo/platforms/ios/cordova/run: Command failed with exit code 2
```

I can't resolve this iuuse. I have reinstall node, and reinstall cordova and ionic. And this issue  always in.

### ionic info ###
```
Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.1.1 Build version 7B1005
 ```

How can I solve this issue?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Quesle!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4657). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4657)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Quesle** [comment]
OK,  I will re submit this issue.
Thanks.

**Comment by mhartington** [comment]
Looks like the command line tools with Xcode weren't installed. Make sure they're install by opening Xcode or running `xcode-select --install` from the command line.

**Comment by Quesle** [comment]
Thanks mhartington. ```xcode-select``` have installed, and version is ```2339```.
I have used xcode run an app very well.

**Comment by mhartington** [comment]
So does that fix the issue?

**Comment by jeswinjose** [comment]
I have got the same issue xcode command line installation did not help.

**Comment by nabn** [comment]
@mhartington I've run into a similar issue, and no, it doesn't fix it.

**Comment by mlynch** [comment]
Hey everyone, going to close since it's not a framework issue but feel free to keep up the discussion in case others find it helpful.

**Comment by donedgardo** [comment]
Any1 found a solution to this, having the same issue.

**Comment by aliencyl7** [comment]
You should launch the xcode ,and select /platform/ios/xxxx.xcodeproj path and build on ur iphone or launch the simulator , and run the terminal ,then it works

**Comment by naaab** [comment]
1/ i opened the xcode.
2/ what do you mean by " select /platform/ios/xxxx.xcodeproj path and build"

FYI,  i am also having same issue. i tried from my both of my macbook. This looks bigger issue, appreciate any help fixing this issue.
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
ENOENT: no such file or directory, stat '/Users/naab/Library/Logs/CoreSimulator/0C2081C0-61B6-4A33-A5FB-28F2177E7334/system.log'
Error code 1 for command: ios-sim with args: launch,/Users/naab/WORK_APP/myApp/platforms/ios/build/emulator/myApp.app,--devicetypeid,com.apple.CoreSimulator.SimDeviceType.iPhone-6,--stderr,/Users/naab/WORK_APP/myApp/platforms/ios/cordova/console.log,--stdout,/Users/naab/WORK_APP/myApp/platforms/ios/cordova/console.log,--exit
Error: /Users/naab/WORK_APP/myApp/platforms/ios/cordova/run: Command failed with exit code 2

**Comment by donedgardo** [comment]
Ok this is what worked for me.

1. Uninstall/ Fresh Install Xcode.
2. Follow this guide to use npm without sudo:
http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/
3. run: ```npm -g install ios-sim```

**Comment by catgsmith** [comment]
Anyone got an answer for this -
So far : Installed node4, Xcode, agreed the terms, downloaded the iOS 9.1 simulator package and check the command line tools via the terminal. Got the exact same problem as Quesel.
 I tried fresh install of Xcode and xcode-select --install, done all the above, restarted machine but still the same error on calling ionic emulate ios. Any suggestions?

**Comment by oneboxteam** [comment]
Solved it with :
http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved

**Comment by catgsmith** [comment]
Thanks oneboxteam - That worked perfectly.
:-)

**Comment by AmbarishKr** [comment]
Thanks 
http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved
 it worked like a charm

**Comment by iscott** [comment]
Thanks @oneboxteam - that worked for me too

**Comment by ndelvalle** [comment]
Used @oneboxteam link to solved it :+1:

**Comment by jgatjens** [comment]
@oneboxteam :+1:

**Comment by tomsharon** [comment]
I have the exact issue and @oneboxteam link didn't do it. Admittedly, "sudo chown -R [username] /Users/[username]" didn't seem to work for me. When I ran the command nothing would happen in my terminal, and I would have to ^C out... Not sure how I am messing up the command. Any recommendations much appreciated. Thank you.

**Comment by BenjaminConant** [comment]
Hi all, 

Have tried everything in this thread and still getting the same issue ... I can open up the project in xcode and run the emulator from there and everything works great. I cannot, however, open the emulator from the terminal with `ionic emulate ios` ... when i do run `ionic emulate ios` i get 

```
** BUILD SUCCEEDED **
```
the emulator opens but is just a black screen
and then after a while the terminal logs

```
No target specified for emulator. Deploying to iPhone-6 simulator
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
```

here is my `ionic info`

```
ordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

Anyone else seeing behavior like this or have any ideas? Would be much appreciated!

**Comment by mika-cn** [comment]
thanks @oneboxteam, [http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved](http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved)  it work:)

**Comment by Darvile** [comment]
Thanks man this link saved the day!!!
http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved

**Comment by eyeinsky** [comment]
@BenjaminConant I'm seeing the same issue, the emulator doesn't start properly. The project seems to build, then starts a blank window, and after a while the console exits with:
```
No target specified for emulator. Deploying to iPhone-6s-Plus, 9.3 simulator
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
Error: ENOENT: no such file or directory, stat '/Users/[username]/Library/Logs/CoreSimulator/8776EAE5-33FF-40FC-B75D-4204851C010E/system.log'
```
Recursive `chown`ing hasn't helped, nor `sudo npm install`ing ios-sim and ios-deploy. Given it's a first run for me on ios development, it might be that I'm just missing something, or it could be a real issue for the few of us.

**Comment by eyeinsky** [comment]
FYI running an emulator through xcode, and then doing `ionic emulate ios` worked for me.

In more detail: I made a hello world project and ran it in the emulator, then went to the command line and ran `ionic emulate ios`, after which the emulator switched to my app. Not ideal, but works..

**Comment by jacprada** [comment]
Thank you so much **@oneboxteam**, the link helped me to solve the issue.

**Comment by mcheung63** [comment]
Same issue using latest cordova 


No target specified for emulator. Deploying to iPhone-6s-Plus, 9.3 simulator
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
Error: ENOENT: no such file or directory, stat '/Users/peter/Library/Logs/CoreSimulator/DA72D47D-A30E-48F6-99C5-15940362B9D8/system.log'

**Comment by Quesle** [comment]
Hi All, 

I have resolve this issue by re install node.
First I uninstall node which used `node-vx.x.x-pkg` to install. And uninstall all npm packages.
Then use `brew install node` to install it. And re install cordova, ionic.
Now I can use `ionic emulate ios` to start my emulator and test my app.

I suppose the reason is permission denied.
Because  in the previous, create, build, emulate ionic app, I need add `sudo` command.
Now needn't.

Hope to have this kind of problem a few ideas.

**Comment by samcdavid** [comment]
Alright guys, I went through _all_ of these suggestions and none of them helped me. For those unlucky few that still get
```
No target specified for emulator. Deploying to iPhone-6 simulator
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
```
Open your Xcode project, then run it on the _iPhone 6_ emulator. After doing that step, I was able to use `ionic emulate ios` and `ionic emulate ios -lcs` ಠ_ಠ

**Comment by LeithOscar** [comment]
hey guys!

I have the same problem when I try to emulate iOS platform

> ** BUILD SUCCEEDED **
> 
> 
> No target specified for emulator. Deploying to iPhone-SE, 10.0 simulator
> 
> 
> An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
> Invalid device state
> 
> An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
> Invalid device state
> 
> Error: ENOENT: no such file or directory, stat '/Users/Leith/Library/Logs/CoreSimulator/81DA68A9-07E9-4202-B985-8D9B106F458E/system.log'
> 
> 
> bash-3.2# 


I tried to looking for any solution about this..but I can't find something good.

Any idea?
Thanks!

**Comment by jgatjens** [comment]
@LeithOscar have you run `npm -g install ios-sim`?

**Comment by spencer1573** [comment]
FIGURED IT OUT! **NVM USERS READ** none of these things seemed to help.  Something that i should have thrown into the equation was that i was using NVM (node version manager) and i don't think i'm the only one. I used a different node version within NVM and reinstalled cordova and ionic. I DID NOT install ios-dim or ios-deploy... and it worked perfectly. So i've come to the conclusion that i need to completely delete the old node version i was using and reinstall everything and it will work on whatever version i need.

**Comment by phuongpt** [comment]
I fixed by "Reset content and settings" on simulator

**Comment by edu-aguilar** [comment]
Having the same problem, and no solution found after read the whole thread.

¿Any help?

**Comment by neuberfran** [comment]
https://forum.ionicframework.com/t/error-enoent-no-such-file-or-directory-stat-var-root-library-logs-coresimulator-1a2f74cf-a3f0-422e-bdb0-9188409f7529-system-log/72775

**Comment by VsMaX** [comment]
I have the same problem.

1. I have installed latest ios-sim and ios-deploy
2. I don't have nvm
3. I have tried chmod -R on whole HOME folder ~/
4. I have removed and added ios platform several times now.

I am seeing only black screen when running emulator. And also the emulator that is run is the last emulatot/simulator I have run from xcode. iOS simulator ignores any parameters for cordova emulate or ionic emulate. Always the same device is started (iPhone 6s).

**Comment by giacomodeglinnocenti** [comment]
The link solved the problem for me.
http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved

In short: be sure to
DO NOT RUN
`sudo cordova run ios`
BUT RUN
`cordova run ios`

If the build fails you probably have to give the permission to your normal user to read/write the ios platform files, doing:

`sudo chmod -R 777 /<your- app-path>/platforms/ios/`
 
This why you can go with the CLI, no need to open Xcode.

**Comment by VsMaX** [comment]
I also had this problem. Somehow running simluator from command line doesn't work for both ionic and react-native. The solution I found is run EXACTLY THE SAME EMULATOR as you run with ionic/react-native manually, reset content and settings and then run `cordova run ios`

**Comment by sreekanth-karini** [comment]
- This is because of sudo, Don't use sudo 
- Just open a fresh terminal and run below command
 'sudo chown -v -R -L yourUserName  /pathtoYourApp' 
- Now run 'ionic cordova run ios --target="[your phone choice]" '
- To list all cordova devices run 'ionic cordova run ios --list'
Ref or Credits : http://zacvineyard.com/blog/2015/11/ionic-invalid-device-state-error-with-xcode-7-solved
Cheers!
