### ISSUE TITLE
bug: Buttons not working on modal on ios9

### ISSUE THREAD

**Issue by wggley** [driftyco/ionic#4658]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I have following HTML on a Modal (Texts are on Portuguese):
```html
<ion-modal-view>
    <ion-header-bar>
        <h1 class="title">{{title}}</h1>
    </ion-header-bar>
    <ion-content>
        <form name="form" method="get" novalidate="novalidate" ng-submit="callBack(form)">
            <label class="item item-input">
                <div class="input-label">Pedido</div>
                <input type="text" ng-model="order.number" placeholder="Toque para editar" ng-change="order.setAlphanumeric()">
            </label>
            <div class="item item-divider">Tipo</div>
            <ion-radio name="type" ng-model="order.selectedType" ng-value="order.type.order">Pedido</ion-radio>
            <ion-radio name="type" ng-model="order.selectedType" ng-value="order.type.load">Carregamento</ion-radio>
            <div class="item item-divider">Intervalo</div>
            <ion-radio name="interval" ng-model="order.last_thirty_days" ng-value="true" on-tap="order.setDateInterval()">Últimos 30 dias</ion-radio>
            <ion-radio name="interval" ng-model="order.last_thirty_days" ng-value="false">Periodo</ion-radio>
            </div>
            <label class="item">
                <div class="item-content">De</div>
                <ionic-datepicker date="order.date_from" callback="order.setDateFrom">
                    <button type="button" class="button button-block">{{ order.date_from | date:'dd/MMMM/yyyy' }} </button>
                </ionic-datepicker>
            </label>
            <label class="item">
                <div class="item-content">Até</div>
                <ionic-datepicker date="order.date_to" callback="order.setDateTo">
                    <button type="button" class="button button-block">{{ order.date_to | date:'dd/MMMM/yyyy' }} </button>
                </ionic-datepicker>
            </label>
            <div class="button-bar">
                <button type="button" class="button button-default" on-tap="closeModal()">Voltar</button>
                <button type="submit" class="button button-positive">Ok</button>
            </div>
        </form>
    </ion-content>
</ion-modal-view>


```

Modal opens correctly but I can't click on the buttons inside div button bar.
I've tried several things but when I discovered that when I remove the datepicker elements (it was input date before) it works.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wggley!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4658). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4658)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by nunomaduro** [comment]
Your component ionic-datepicker is properly configured? 

Can you execute your application in a browser in show me a print of the console ?

**Comment by wggley** [comment]
![image](https://cloud.githubusercontent.com/assets/13734836/11340853/0dbceb26-91e7-11e5-8ff2-ba96b2ea48f0.png)

**Comment by wggley** [comment]
I'm using this date-picker:
https://www.npmjs.com/package/datepicker-for-ionic
But it won't work with input date also.

**Comment by nunomaduro** [comment]
You are saying that after you select a date from the component ionic-datepicker you can't submit your form because the OK button don't work. That's right ?

**Comment by nunomaduro** [comment]
Just one thing. You have a extra </div>

![screen shot 2015-11-23 at 15 41 25](https://cloud.githubusercontent.com/assets/5457236/11341099/da14a310-91f8-11e5-9a46-4e7d4a19bc95.png)

**Comment by wggley** [comment]
When datepickers or input-dates are visible, I can't click on ok and cancel buttons and even datepicker ok and cancel buttons.

**Comment by nunomaduro** [comment]
The remove of that extra div solved the problem ? :)

**Comment by wggley** [comment]
No.

**Comment by wggley** [comment]
I think also that is something related with the combination of radios, inputs etc.
I did a workaround that is displaying elements separated (when clicking on a item-divider displays sub elements with ng-if) and it worked but it's not the expected UI that I made on the beginning.

**Comment by careuno** [comment]
same problem but in my case, close button is not working. On Android works correctly.

**Comment by danbucholtz** [comment]
Hi @wggley,

Can you provide a codepen of this happening without the third party dependency?  Thanks for letting us know, we appreciate it.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by wggley** [comment]
The problem persists, but I can't provide a codepen right now.
It's simple, if you grab my HTML at first post and put inside a modal template and try to open it on ios9 the problems related happens.

**Comment by wggley** [comment]
The bug is not related to third party datepicker, it happens with simple HTML5 input date

**Comment by dimitri320** [comment]
I'm experiencing the exact same thing too.
