### ISSUE TITLE
bug: iOS 9 Doesn't seem to like playing mp4 or mov files, in HTML 5 video, from the device

### ISSUE THREAD

**Issue by snstarosciak** [driftyco/ionic#4668]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hey there, 

Has anyone else had the issue where in iOS 9 when you try to play a video from a file that has been downloaded to the device, it gives you no error and does nothing? Even if the file does exist?

I'm using HTML 5 video like this:

`<video controls="controls" preload="metadata" autoplay="autoplay" webkit-playsinline="webkit-playsinline" >
            <source ng-src="{{resourceURL | trustAsResourceUrl}}" type="video/mp4"/>
          </video>`

I know resourceURL exists and that it is a safe URL after it goes through my trustAsResourceUrl filter, but despite my best efforts, the video will not play. It has no problem in Android, but when I test is on both of iPhone 6s Plus & iOS 9 emulator.

I've even tried linking directly to the video file in my code with both the file:// and cdvfile:// versions and the video just won't play. Does anyone have any idea why this would be happening?</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @snstarosciak!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4668). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4668)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @snstarosciak, thanks for the issue, and just found your post on the forum which does solve this in case anyone else runs into it as well: https://forum.ionicframework.com/t/ios-9-cant-play-audio-video-files-that-are-downloaded-to-device/37580/4

Essentially, you need to use `cdvfile://`

**Comment by snstarosciak** [comment]
@mlynch Hey man, thanks for the reply. I'm a bit confused by your comment. In the post that you referenced, I had posted code on that thread for getting the media player plugin to work with audio, which was a completely separate issue than trying to play mp3/mp4 file in an HTML5 <audio> or <video> element. I still haven't resolved that problem yet, so I think this one should be opened again :/

**Comment by chrisbenseler** [comment]
@snstarosciak Iḿ  facing the same problem in an Ionic (2) app and iOS9.

**Comment by CatchSandeepVaid** [comment]
We are also facing the same issue.. So i also think we should open this issue

**Comment by mastarenee** [comment]
I am having this issue as well, my ionic application pulls posts from WordPress and inside some of the post, I have an HTML5 audio player, it works great on Android however on iOS I can only see the play button, once I click, the audio plays but I cannot see any pause, buffering, time left nothing.

Did anyone resolve this issue?
