### ISSUE TITLE
bug: on-hold directive not working on android

### ISSUE THREAD

**Issue by zeeroa** [driftyco/ionic#4672]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>browser</span>

<span ionic-description>on-hold directive not working on android version 5.1 and later, in the phone's browser but in native hybrid app also.

I noticed that if I disable the scroll everything works correctly, but: 1) if I enter the event on-hold in each item in a list does not make sense to lock the scroll, 2) if the event on-hold is in the directive ion-scroll worsens the situation.

On the web there is little documentation on this bug. Many have found it but few have solved it.</span>

<span is-issue-template></span>

**Comment by HugoHeneault** [comment]
I'm facing this issue too. Quite tricky to trigger on-hold...

**Comment by sevnlabs** [comment]
I'm having the same issue for android devices with 5.1 and later but it seems to work in the emulator... The "disable scrolling" fix is no option for me...

**Comment by Elyahou** [comment]
same issue Android 5.1 on Galaxy S6 on-hold on list item is not working

**Comment by Elyahou** [comment]
Same bug and others occurs in Hammer.js

@mlynch I think we have to apply all changes of https://github.com/hammerjs/hammer.js/pull/860 to fix these issue. 

For my part, just updating the `hold_threshold` to 251 and `hold-threshold` to 9 fix the on-hold issue on Galaxy S6

**Comment by mlynch** [comment]
Thanks, tracking for 1.2 release!

**Comment by mlynch** [comment]
Above PR from @Elyahou just landed and should fix this. Let me know if it's not the case but going to close in the meantime.
