### ISSUE TITLE
bug: Iconic not in NPM?

### ISSUE THREAD

**Issue by emincer** [driftyco/ionic#4673]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "iconic"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/iconic
npm ERR! 404 
npm ERR! 404 'iconic' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.</span>

<span is-issue-template></span>

**Comment by simplesmiler** [comment]
@emincer it's `ionic`, not `iconic`.

**Comment by brandyscarney** [comment]
Yes, please use `npm install -g cordova ionic`

http://ionicframework.com/getting-started/
