### ISSUE TITLE
bug: Text input loses focus when selected

### ISSUE THREAD

**Issue by chriseen** [driftyco/ionic#4678]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am actually using Ionic v1.1.1 (the latest) and I found really an annoying issue with text inputs. When I tap on a input to focus it, whole view is scrolled up to accommodate keyboard. The problem is - once a view is moved up, selected input loses focus immediately (and keyboard is still shown) and any words that I type is NOT SEEN in text input.

This is happening in my desktop environment (chrome) as well as in iOS too. This doesn't happen in previous versions of Ionic. (at least v1.0.1)</span>

<span is-issue-template></span>

**Comment by freiserg** [comment]
Yes, I confirm that.

**Comment by tlancina** [comment]
Could you post some code reproducing the issue for you please? Also what version of iOS are you seeing this on?

**Comment by chriseen** [comment]
Hi @tlancina, thank you for your attentions. I already had a fix by disabling all the code lines inside cloneFocusedInput() from ionic.bundle.js... this issue was gone :) It seems this issue is actual across all versions of iOS.

**Comment by danbucholtz** [comment]
@chriseen, could you share your fix?  Does this happen with the latest version of Ionic?

Thanks,
Dan

**Comment by urschaitanya** [comment]
In my case even removing the contents of the clonefocusedInput() didn't worked. Please help

**Comment by samarpanB** [comment]
Hello,

This is still appearing to be an issue for us. For us its happening with a textarea. The textarea is within a modal.

`<ion-modal-view>
    <ion-header-bar class="bar-positive">
        <span class="title">Comment</span>
    </ion-header-bar>
    <ion-content>
        <textarea
            ng-model="text"
            ng-readonly="!(isEditing &&
                isAllowEdit)"/>
        <div class="row">
            <button class="button button-calm button-block"
                ng-show="isAllowEdit && isEditing"
                ng-disabled="isWorking"
                ng-click="onSaveComment($event, selectedComment)">
                okBtn
            </button>
            <button class="button button-stable button-block"
                ng-disabled="isWorking"
                ng-click="onCloseComment()">
                cancelBtn
            </button>
        </div>
    </ion-content>
</ion-modal-view>`
