### ISSUE TITLE
bug: Deploy channel tags break if they contain hyphens

### ISSUE THREAD

**Issue by matthewlloyd** [driftyco/ionic#4695]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you try to create a deploy channel in the dashboard with a tag that contains a hyphen, the operation appears to have succeeded but the tag has silently had the hyphen stripped out. When clients attempt to pull updates from the channel using the hyphenated channel tag, the Ionic platform fails to find the channel and falls back to the Production channel. Instead, it would be better if either (a) channel tags were allowed to be hyphenated (why not?), or (b) the extraneous hyphens were automatically ignored by the channel tag comparison in Ionic's deploy server.</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Hey @matthewlloyd, mind posting this over at https://github.com/driftyco/ionic-platform-web-client? It seems related to Ionic platform rather than the framework (so, going to close for now). Thanks!
