### ISSUE TITLE
docs: Docs on deploy channel name vs channel tag

### ISSUE THREAD

**Issue by matthewlloyd** [driftyco/ionic#4696]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The documentation on deploy channels could benefit perhaps from being a little clearer on the difference between the channel name and the channel tag. The method to set the channel tag is setChannel. Accidentally calling setChannel with the channel name can cause the app to pull from the wrong channel, if the channel name and the channel tag happen not to be equal.

Also it seems like channel names and tags were kept separate for a reason - presumably there is a use case - would be really nice to see the use case documented and explained!</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Hey @matthewlloyd :) same response, mind posting over here so the platform folks can get this fixed for you? cc @ericb https://github.com/driftyco/ionic-platform-web-client
