### ISSUE TITLE
bug: $http post fails when switch between wifi and cell

### ISSUE THREAD

**Issue by wallstudios** [driftyco/ionic#4706]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Not sure if this is the right place to ask this question or not.

I have an odd situation.
I am making a $http post to an oauth2 server to login using ionic.

if I start the app in wifi mode and connect it works correctly. But if I switch to 4g (cell) it returns a 403 Request Denied! from the server. 

and vice versa if I load the app in 4g mode it works but fails (same error) if I switch to wifi.

I've console logged out the response and they are identical.

			ok
			
			{"status":200,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://someurl.com:443/token","headers":{"Content-Type":"application/x-www-form-urlencoded","PartyId":"55454465446","Accept":"application/json, text/plain, */*"},"data":{},"params":{"grant_type":"password","username":11,"password":"password","client_id":"ljdlkfsjdfjsldjfls","client_secret":"dfdfdfdfd"},"ignoreAuthModule":true},"statusText":"OK"}
			
			not ok
			
			{"status":403,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://someurl.com:443/token","headers":{"Content-Type":"application/x-www-form-urlencoded","PartyId":"55454465446","Accept":"application/json, text/plain, */*"},"data":{},"params":{"grant_type":"password","username":11,"password":"password","client_id":"ljdlkfsjdfjsldjfls","client_secret":"dfdfdfdfd"},"ignoreAuthModule":true},"statusText":"Forbidden"}

any thoughts would be appreciated.

I've installed a starter app with no plugins and clean code and it does the same thing.

this is both iOS and Android.

ionic 1.7.11

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @wallstudios!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4706). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4706)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by kaiquewdev** [comment]
You was verified this on the server side? You have more information about the request?
Use the chrome://inspect to grab more information using the network tab in developer tools... Maybe help you to get more information about that situation.

**Comment by wallstudios** [comment]
Looking to get info from the server side to compare. I've inspected device using safari and the requests are identical. at least when I console log out the response. is there a way to get the output from the $http post request?

**Comment by kaiquewdev** [comment]
Of course, maybe you can get this on the handler of request on server side code.

**Comment by wallstudios** [comment]
looks like a load balancer issue on the server.

**Comment by kaiquewdev** [comment]
This is good, maybe you spotted the point to fix.

**Comment by mlynch** [comment]
Interesting bug! Closing since it's out of scope or not related to Ionic, but let us know how you resolve it in case anyone else runs into something similar :)

**Comment by wallstudios** [comment]
Will do.
