### ISSUE TITLE
bug: Platform.isIOS() returns true on desktop browser

### ISSUE THREAD

**Issue by ZenSide** [driftyco/ionic#4709]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The utility function `Platform.isIOS()` returns `true` when executed on Chrome on a desktop computer.
Unless I didn't get a point, it's probably not the waited result.</span>

<span is-issue-template></span>

**Comment by ZenSide** [comment]
So to check if the app is executed on iOS, have to double check with :

    ionic.Platform.isWebView()

**Comment by mlynch** [comment]
@ZenSide thanks, which desktop OS are you on?

**Comment by mlynch** [comment]
Closing

**Comment by ZenSide** [comment]
This issue appear on Chrome browser on Linux.
