### ISSUE TITLE
bug: Scrolling halts with deeply nested elements

### ISSUE THREAD

**Issue by canac** [driftyco/ionic#4711]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>On desktop, mouse wheel scrolling halts when the cursor is over a deeply nested element. To see this problem, open this Codepen http://codepen.io/canac/pen/KVKXqG. Then position the cursor over the text of the first list item. Then start scrolling down. Scrolling will stop midway through the list at the "Unscrollable item".</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Works fine here...another test case? Are you sure it's not just that the viewport is too big to scroll?

**Comment by canac** [comment]
@mlynch This issue only shows up when using Ionic's JavaScript scrolling. I think that my test case stopped working because of commit 11946ef which made native scrolling the default. I updated [my Codepen](http://codepen.io/canac/pen/KVKXqG) to explicitly use Ionic's JavaScript scrolling, so please try it again. Thanks!
