### ISSUE TITLE
ionic build command fails with error 

### ISSUE THREAD

**Issue by rsa408** [driftyco/ionic#4712]
D:\mob\mytabs>ionic build android
Running command: "C:\Program Files\nodejs2\node.exe" D:\mob\mytabs\hooks\after_prepare\010_add_platform_class.js D:\mob\mytabs
add to body class: platform-android
Running command: cmd "/s /c "D:\mob\mytabs\platforms\android\cordova\build.bat""
ANDROID_HOME=D:\adt-bundle-windows-x86-20130219\SDK
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_66
Running: D:\mob\mytabs\platforms\android\gradlew cdvBuildDebug -b D:\mob\mytabs\platforms\android\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
17:14:23.964 [main] DEBUG o.g.l.daemon.bootstrap.DaemonMain - Assuming the daemon was started with following jvm opts: [-XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx1024m, -Dfile.encoding=windows-1256, -Duser.country=US, -Duser.language=en, -Duser.variant]

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type DaemonContext using DaemonServices.createDaemonContext().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

D:\mob\mytabs\platforms\android\cordova\node_modules\q\q.js:126
            throw e;
            ^
Error code 1 for command: cmd with args: /s /c "D:\mob\mytabs\platforms\android\gradlew cdvBuildDebug -b D:\mob\mytabs\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1

**Comment by Ionitron** [comment]
Greetings @rsa408!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4712). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4712)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @rsa408, mind filing this one over at https://github.com/driftyco/ionic-cli/issues?

Sounds like you might have an incorrectly installed cordova/android setup. I'd go through the Android Platform guide again and see if that helps: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

**Comment by rsa408** [comment]
Hi, actually before that error everything was fine it happens suddenly  even i removed the gradle  folder to ionic build command install it again but the error appears again,  after that i even tried to install android studio minimizing VM size and so many other things.
randomly I run cmd.exe as administrator (how ever my user is administrator)  gradel start to download "maven" package. and it works fine for me.

**Comment by mysimpex** [comment]
Run your cmd.exe with "Run as Administrator"

**Comment by ranbuch** [comment]
+1

**Comment by tusharkkumar** [comment]
**fix is here** (FOR WINDOWS ONLY)

I am facing the same problem of Build then i finally found out the solution.<br><br>


**SOLUTION**<br>
So You must have the Android Api 23 in order for this command to work.<br>
Error of Daemon process will be solve after installing the Api 23 and extra <br>build tools and run command <br>
COMMAND : cordova build android --release<br>
I am sure this fix would help you to solve the problem.


**STEPS**<br>
1. First check the version of android through this COMMAND:
   cordova platform help <br>
2. Run the build command after installing the Api 23 and extra build tools.<br>
3. If Even this not work then Try add the variable in the <br>
 Environment variables > System variables > <br>
 add _JAVA_OPTIONS and value = -Xmx512M

Then Run cordova build android --release

BUT FIRSTLY SET UP THE ENVIRONMENT VARIABLES <br>
[Environment Variable setup Image][2]<br>
[android API 23][1]


**COPY FROM HERE** <br>
ENVIRONMENT VARIABLES:-

1. **USER VARIABLES**<br>
 **PATH** <br>
 C:\Ruby23\bin;C:\Users\kumar\AppData\Roaming\npm;C:\ANDROID_SDK\tools;%SystemRo
 ot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


2.  **SYSTEM VARIABLES** <br>
  **ADD NAME AND VALUE** <br>
  2.1  **_JAVA_OPTIONS**   -Xmx512M <br>
  2.2  **ANDROID_HOME**    C:\ANDROID_SDK <br>
  2.3  **PATH** -> <br>
 	C:\ProgramFiles\Java\jdk1.8.0_60\bin;C:\ProgramFiles\nodejs;C:\Gradle\gradle-4.0\bin;C:\ANDROID_SDK\tools;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


  [1]: https://i.stack.imgur.com/wLI0J.png
  [2]: https://i.stack.imgur.com/M5InU.png
