### ISSUE TITLE
Transition v1 directive naming to v2 naming

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#4727]
Let's review directive names in v1 and begin to transition the ones that have changed to v2 as much as possible.

**Comment by mlynch** [comment]
Pushing to 1.3

**Comment by perrygovier** [comment]
My only concern is that we change everything that makes sense to rename, or nothing. A half measure would just confuse people. Also, we should over-communicate the breaking change.

**Comment by mlynch** [comment]
Deferring for now
