### ISSUE TITLE
Fallback to JS scrolling for infinite scroll on iOS

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#4729]
because scroll events

**Comment by mlynch** [comment]
Thought: we just document that they need to add `overflow-scroll="true"` to `ion-content`'s that use collection repeat or infinite.

**Comment by mlynch** [comment]
Err, but I guess that doesn't make it easy to optionally do it for just iOS

**Comment by perrygovier** [comment]
Should be fine to do here https://github.com/driftyco/ionic/blob/master/js/angular/directive/content.js#L74

**Comment by perrygovier** [comment]
During testing, I realized that allowing native scrolling for infinite scrolling in iOS isn't quite perfect, but it's not that bad either. I'm going to continue with the plan to force JS scrolling, but here's a video of native scrolling infinite scrolling on iOS.
https://www.dropbox.com/s/bpujl2v9m72vtb5/ios-native-scrolling-infinite-scroll.mov?dl=0

**Comment by mlynch** [comment]
Cool, lets' go with that for now.

**Comment by perrygovier** [comment]
Cool if we decide to add it later, the code to do so is simple, add to
https://github.com/driftyco/ionic/blob/master/js/angular/directive/content.js#L78
```js
// so does infinite scrolling on iOS, only check if still nativeScrolling
if (nativeScrolling && ionic.Platform.isIOS()) {
  nativeScrolling = !element[0].getElementsByTagName('ion-infinite-scroll');
}
```

**Comment by tomkelsey** [comment]
Hi @mlynch / @perrygovier

Might have got the wrong end of this stick on this one but I use WKWebView with native scrolling on iOS as JS scrolling was too laggy for my specific implementation. There are a few bugs but it's overall a far more useable experience than JS scrolling was. Just hoping that whatever change is made here it can still be overridden to force native scrolling for infinite scroll on iOS.

Thanks!
