### ISSUE TITLE
bug: One of your demo apps doesn't work

### ISSUE THREAD

**Issue by kilroy05** [driftyco/ionic#4741]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>http://codepen.io/ionic/pen/mFygh
Your app demo doesn't work.
Cheers</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Looks like codepen is erroring out.
