### ISSUE TITLE
bug: statusTap issue with native scroll on iOS

### ISSUE THREAD

**Issue by andreialecu** [driftyco/ionic#4743]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When tapping the status bar in the new ionic master while there is a momentum scroll happening the scroll to top doesn't complete properly. It snaps to top then back down to where the initial momentum scroll's end position was. This happens with native scrolling.

This can probably be fixed by forcing `overflow: hidden` on the overflow-scroll="true" div to freeze the scroll.</span>

<span is-issue-template></span>

This was also an issue in previous ionic versions with native scrolling on iOS.

**Comment by mlynch** [comment]
Thanks, will get this fixed

**Comment by andreialecu** [comment]
@mlynch I opened a PR at https://github.com/driftyco/ionic/pull/4748 which fixes this.

**Comment by mlynch** [comment]
Thanks for guiding this one, I did a slightly different solution. Mind testing on WKWebView and letting me know how it goes?

**Comment by andreialecu** [comment]
@mlynch I just tested it and it works, however, I think `.freeze` should still be implemented instead of it being NOOP, otherwise when you start dragging up/down from the left margin so that the content scrolls, and then you drag to the right to enable the swipe to go back gesture, you can both scroll the view and expose the previous view which seems glitchy.
