### ISSUE TITLE
bug: Nightly 1.2.0 JS broke down scrolling

### ISSUE THREAD

**Issue by evgd** [driftyco/ionic#4758]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Platform: desktop, but probably all

http://s.codepen.io/ionic/debug/mqolp as example
Scrolling doesn't work and doesn't produce any errors in console.</span>

<span is-issue-template></span>

**Comment by ronygb** [comment]
I have same issue on Android and iOS

**Comment by kbalaguru** [comment]
"By default, Ionic 1.2 will use native scrolling on all platforms."

`ion-refresher` is based on jsScrolling. If you want `ion-refresher` you should enable jsScrolling. You can do it by adding 
`$ionicConfigProvider.scrolling.jsScrolling(true); `
in your app config. Ref: http://ionicframework.com/docs/api/provider/$ionicConfigProvider/

**Comment by evgd** [comment]
@kbalaguru Good to know! Thank you. Sadly all examples refers to "nightly" build and should be fixed then.

**Comment by ronygb** [comment]
thank you

**Comment by aamarcha** [comment]
@evgd @ronygb you can also do it easily by view (if you need ion-refresher) 

```
<ion-content overflow-scroll="false">
</ion-content>
```

**Comment by mlynch** [comment]
Thanks, fixed, will be in 1.2.1 when we publish this week
