### ISSUE TITLE
bug: Textarea Indent -3px

### ISSUE THREAD

**Issue by cmellinas** [driftyco/ionic#4761]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I updated Ionic to V1.2.0

There is this new line of css : 
.platform-ios textarea, .platform-android textarea {
    text-indent: -3px;
}

It was added for the textarea placeholder : https://github.com/driftyco/ionic/issues/2307

But now, when I type in textarea, the first typed letter is cut by the left border of the textarea.
It concerns only the first line of the textarea

It was on an Android phone but later I will try on IOS to see if this is the same thing</span>

<span is-issue-template></span>

**Comment by zanemcca** [comment]
+1 for android.
I have tried it on iOS and there is no issue. 
I think the solution is to make it an iOS only change.
What do you think @mlynch?

**Comment by mlynch** [comment]
Thanks, that was supposed to be iOS only, fixed!

**Comment by aamarcha** [comment]
+1 for android too!
