### ISSUE TITLE
feat: Publish Ionic 1.2 to Meteor Atmosphere

### ISSUE THREAD

**Issue by carlosbaraza** [driftyco/ionic#4766]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I noticed that if I try to set a dependency like this `api.use('driftyco:ionic@1.2.0', 'web.cordova');` in a meteor package, the dependency manager will not be able to resolve the version and it will not install the latest version.

After some research and speaking with @Urigo, it seems that the version 1.2.0 is no published to Meteor's package repository. The way to do it is `meteor publish` from the root of git checkout of ionic repo. Then some credentials will be needed to publish.

Thank you for the support and this great framework!</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @carlosbaraza!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4766). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4766)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by justinweinberg** [comment]
+1

**Comment by lance-anderson** [comment]
+1

**Comment by plraphael** [comment]
+1

**Comment by plraphael** [comment]
Is it really that simple? Just run `meteor publish`?

**Comment by carlosbaraza** [comment]
Yes, it is very simple to publish a Meteor package. Just need to bump the version and meteor publish. I would do it but I don't have the credentials to maintain this.

**Comment by plraphael** [comment]
I was thinking about forking the repo and publishing myself the new version, until they actually do. Do you think it will work?

**Comment by plraphael** [comment]
If I download the repo to a packages/ directory in my application and add the package, it will add with the current version (1.2.4), but this happens if I try to go to localhost:3000

![image](https://cloud.githubusercontent.com/assets/645621/12371811/69f28526-bc27-11e5-836f-dad0bbc94869.png)

**Comment by bmanturner** [comment]
Can we get an update on this from someone at driftyco?

**Comment by carlosbaraza** [comment]
Well, I have spent some time researching about this. Indeed there is the need to change the `addFiles` to `addAssets` for the icons. Only this, already requires a PR.

Also, once installed the package, it seems that I am having a problem with the package [angular-templates](https://github.com/Urigo/angular-meteor/blob/master/packages/angular-templates/templates-handler.js#L12) in the `angular-meteor` bundle. For some reason the `templateCache.get` is returning undefined when loading a template. If I comment out the package, it loads all my templates and works as expected.

@dotansimha and @Urigo, do you know what this issue could be in the package `angular-templates`? Thanks.

<img width="845" alt="screen shot 2016-01-18 at 9 59 49 pm" src="https://cloud.githubusercontent.com/assets/1270425/12402693/e7e18a78-be2e-11e5-8512-a3236abe7472.png">

**Comment by dotansimha** [comment]
@carlosbaraza Might not be correct, but please try to add `/` in the beginning of your `templateUrl`...

**Comment by carlosbaraza** [comment]
I opened a small PR for the issue with the fonts. Hopefully we can fix the issue with the template loading within `angular-templates`.

By the way, @plraphael, if you want to use Ionic 1.2.4, I managed to do it. Your problem seems strange because it looks like Ionic was not loaded. Maybe you changed `addFiles` for `addAssets`, instead of moving out of the array the fonts only? Checkout my PR to understand what I mean.

**Comment by dotansimha** [comment]
Also, @carlosbaraza , please follow the instructions in https://github.com/Urigo/angular-meteor/issues/958#issuecomment-166897834

**Comment by carlosbaraza** [comment]
@dotansimha, thanks for coming back. I already tried both ways and stills does not loads the templates. It seems to return always `undefined`.

**Comment by carlosbaraza** [comment]
Thanks for the instructions, I am having a look now to see what I can find.

**Comment by carlosbaraza** [comment]
Hi @dotansimha,

Thank you very much for the instructions. It wasn't a bug indeed. I decided to bump `angular-meteor` version to 1.3 from a project in order to reproduce what @plraphael was saying, and at the same time keep the project updated.

My issue was that I forgot to change the `addAssets` from the templates to `addFiles`, and therefore, the templates were not compiled and cached as they should.

Therefore, I think that once the PR #5018 is accepted, we are good to go for the Ionic lunch to the Atmosphere.

Thanks again.

**Comment by patrickdevivo** [comment]
Anyone know the status of this issue? Currently running into the problems described here: https://github.com/Urigo/angular-meteor/issues/958 and here: https://github.com/Urigo/meteor-angular-socially/issues/92 using ionic and angular within meteor ($templateCache can't seem to find the html files I reference).

My ionic version is 1.1.0_2, are we still waiting on 1.2.4 to be published to atmosphere?

Thanks!

**Comment by patrickdevivo** [comment]
I've tried upgrading to driftyco:ionic 1.2.4 by cloning the repository into packages/ and Meteor seems to use 1.2.4 fine, but I still have the same error described above (https://github.com/driftyco/ionic/issues/4766#issuecomment-172653060) any ideas?

**Comment by mhartington** [comment]
Will publish 1.2.4 to  atmosphere

**Comment by patrickdevivo** [comment]
I just fixed it...and I feel very foolish. Just needed to include angular-meteor before ionic in the app dependencies!

**Comment by plraphael** [comment]
Thanks guys, I was off for the week. @carlosbaraza, I had just changed addFiles for addAssets, but was not able to pursuit it much longer, so I let it go. The main reason I wanted Ionic 1.2.4 was to use the new slide box, but that could wait. So is it working now? Anyway, thanks guys for the effort.

**Comment by carlosbaraza** [comment]
@plraphael, my pr to change the `package.js` was merged. So if you checkout the latest master version in your packages folder, it should work.

**Comment by plraphael** [comment]
Thanks @carlosbaraza.

**Comment by carlosbaraza** [comment]
You are welcome :)

Hopefully someone from ionic team could publish the package soon to atmosphere.

**Comment by Urigo** [comment]
I've published `1.2.4` to Atmosphere.
Next time I can give someone from the Ionic team an access to do that themselves...

**Comment by perrygovier** [comment]
Thanks @Urigo!

**Comment by Urigo** [comment]
ohhh and also with Meteor 1.3 (coming soon) we could just do `npm install ionic` .....
