### ISSUE TITLE
Select compopnent doesnt work on firefox mobile

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#4767]
**Type**: <span ionic-type>Bug</span>

**Platform**: <span ionic-platform>Firefox Mobile</span>  

<span ionic-description>Select tag has a small click area in firefox mobile </span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Unable to reproduce in Firefox Mobile for iOS

**Comment by mlynch** [comment]
Just realized that FF for Mobile on iOS would use safari anyways, so reopening

**Comment by mlynch** [comment]
Can repro on Android

**Comment by legalsylvain** [comment]
I confirm this bug.

**Comment by Frozenball** [comment]
This problem also occurs with:
- IE Edge when using touch screen. As a workaround you can use two fingers to open the select box.
- Chrome on Android. I can manage to open `<select>` when clicking the select on different places.

Codepen: http://codepen.io/anon/pen/WGdGgY

Me trying to open select:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/53298/19112059/611b9bf0-8b0b-11e6-922a-9bb5693c502d.gif)

**Comment by Frozenball** [comment]
Workaround **that may have all sorts of unintended consequences**:

Change this function
````js
function tapIgnoreEvent(e) {
  if (e.isTapHandled) return true;
  e.isTapHandled = true;

  if(ionic.tap.isElementTapDisabled(e.target)) {
    return true;
  }

  if (ionic.scroll.isScrolling && ionic.tap.containsOrIsTextInput(e.target)) {
    e.preventDefault();
    return true;
  }
}
````

to

````js
function tapIgnoreEvent(e) {
  if (e.isTapHandled) return true;
  e.isTapHandled = true;

  if(ionic.tap.isElementTapDisabled(e.target)) {
    return true;
  }

  // Workaround for <select> not opening
  if (e.target.tagName === 'SELECT') {
    return true;
  }

  if (ionic.scroll.isScrolling && ionic.tap.containsOrIsTextInput(e.target)) {
    e.preventDefault();
    return true;
  }
}
````

**Comment by Frozenball** [comment]
Good workaround: https://forum.ionicframework.com/t/select-not-working-on-windows-phone-with-ionic/45078/3

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#23
