### ISSUE TITLE
bug: npm ERR! code ECONNRESET - Using  node v5.2.0, npm v3.5.2 - Mac OS

### ISSUE THREAD

**Issue by kishaningithub** [driftyco/ionic#4769]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>:~ $ npm install -g ionic
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/KishanB/.nvm/versions/node/v5.2.0/bin/node" "/Users/KishanB/.nvm/versions/node/v5.2.0/bin/npm" "install" "-g" "ionic"
npm ERR! node v5.2.0
npm ERR! npm v3.5.2
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kishaningithub!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4769). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4769)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dagatsoin** [comment]
same here:
node 4.2.3
npm 2.14.7

**Comment by dagatsoin** [comment]
seems that [8196](https://github.com/npm/npm/issues/8196) has came back from hell.

**Comment by mhartington** [comment]
Are either of you behind a firewall from your computer or network?

**Comment by kishaningithub** [comment]
Nope. installation of bower, gulp and cordova was successful. Im connecting via wifi.
The internet connection here is about 150 kbps on a wifi. Does this ring any bell??
Using nvm i also switched to node 0.12.7 same issue. The below error log gets pumped all over the terminal and does not stop.. Seems to be running in a very long or infinite loop i guess
```
:~ $ npm install -g ionic 
> spawn-sync@1.0.14 postinstall /Users/KishanB/.nvm/versions/node/v0.12.7/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm ERR! tar.unpack error reading /var/folders/kp/7qw8438s15g20d_c0tfvb6pm0000gn/T/npm-9912-b818f678/registry.npmjs.org/lodash/-/lodash-3.10.1.tgz
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/KishanB/.nvm/versions/node/v0.12.7/bin/node" "/Users/KishanB/.nvm/versions/node/v0.12.7/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/KishanB/.nvm/versions/node/v0.12.7/bin/node" "/Users/KishanB/.nvm/versions/node/v0.12.7/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read


The same over and over again....
```

**Comment by dagatsoin** [comment]
@mhartington no.

just managed to get it work by clean cache. So, you have to use node v.4.x + npm@2.14.7 + do a `npm cache clean` after switching node version.

**Comment by kishaningithub** [comment]
```npm cache clean``` does not seem to work for me
Full npm-debug log attached
[npm-debug.txt](https://github.com/driftyco/ionic/files/60585/npm-debug.txt)

**Comment by dagatsoin** [comment]
just to be sure, could try with node 4.2.3 + npm@2.14.7 then `npm clean cache`

**Comment by kishaningithub** [comment]
@dagatsoin Nope does not work :-(
Full console log and npm-debug log attached
[log.txt](https://github.com/driftyco/ionic/files/60597/log.txt)
[npm-debug.txt](https://github.com/driftyco/ionic/files/60598/npm-debug.txt)

**Comment by mikekrell** [comment]
Ive been having the same issue, and have been trying everything to get ionic to work. I am on OS X El Capitan, switched my connection from wireless to wired. 

After the switch, npm install -g ionic worked perfectly! Would make sense with all the dependancies it DLs

**Comment by mlynch** [comment]
This is a CLI issue, tracking here: https://github.com/npm/npm/issues/8196#issuecomment-164406994
