### ISSUE TITLE
bug: scrollbar disappeared on Android's native scrolling

### ISSUE THREAD

**Issue by cheneywan** [driftyco/ionic#4772]

**Comment by mlynch** [comment]
Seems to happen intermittently. I'm considering this an issue with overflow scrolling on Android and not a regression per say. Will track.

**Comment by roysG** [comment]
I can also say that since i updated to 1.2.1 suddenly to scroll is gone.

I am using in  <ion-scroll

**Comment by jgw96** [comment]
Hello (: Are you still experiencing this issue with the latest version of ionic?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by neslinesli93** [comment]
Same issue here, happening only on my device, which is equipped with Android Kitkat.
Unfortunately I only have kitkat devices with me, so I can't test with Android 5/6
