### ISSUE TITLE
bug: How to connect mysql in Ionic mobile app with angularjs

### ISSUE THREAD

**Issue by vetrivelbright** [driftyco/ionic#4773]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tried server side PHP code it was working fine, but i cant store any data to mysql table.. How to connect mysql. i am using phonegap interface to run ionic app in localhost. I am very new to ionic and phonegap. If know anybody help me on that.

i want to store my data into mysql instead of mobile local storage, i am using Linux hosting,

**my js code **

  $http.post(link, {username : $scope.data.username,email:$scope.data.email,password:$scope.data.password}).then(function (res){
    alert(res.data);
    $scope.res_div=false;
    $scope.loading = false;

    $scope.response = res.data;
    
   
    
});

php code:

<?php

$con = mysql_connect("localhost","root","");
if (!$con)
  {
  die('Could not connect: ' . mysql_error());
  }

mysql_select_db("dbname", $con);

	if (isset($_SERVER['HTTP_ORIGIN'])) {
		header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Origin: {$SERVER['HTTPORIGIN']}");
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Max-Age: 86400'); // cache for 1 day
}

// Access-Control headers are received during OPTIONS requests
if ($SERVER['REQUESTMETHOD'] == 'OPTIONS') {

if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
    header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         

if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
    header("Access-Control-Allow-Headers:        {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

exit(0);
}

$postdata = file_get_contents("php://input");
if (isset($postdata)) {
$request = json_decode($postdata);
$username = $request->username;
$email = $request->email;
$password = $request->password;
$enc_pwd = sha1($password);

		if ($username != "") {
			//echo "Server returns: Username " . $username ."\n" ."Email : " . $email ."\n" ."Password : " . $password;
			
			//echo "Server returns: Username " . $username ;
			
			$result=mysql_query("insert into register values ('','$username','$email','$enc_pwd','$cur_date')");
				if($result)
				{
				echo "Successfully registered";
				}
			
		}
		else {
			echo "Empty username parameter!";
		}
	}
	else {
		echo "Not called properly with username parameter!";
}
?>

Note: when i run the app from my mobile i am getting full php code as a response...</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @vetrivelbright!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4773). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4773)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
This is a great question for the forum, thanks! https://forum.ionicframework.com
