### ISSUE TITLE
bug: New ion-slides directive creates duplicate slides

### ISSUE THREAD

**Issue by rhazn** [driftyco/ionic#4792]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>see this gist: https://gist.github.com/rhazn/8f408e4785026a411035

I'll c&p from the chat in the ionic slack, sorry for the formatting:

it starts on a slide showing "4", i can swipe right to 1, 2, 3 and then i can see a slide with 4 on it but not swipe completely into it

pager shows the first 4 slide is the first slide

and the html shows that the first and last slide are "duplicates" which i guess swiper does when you enable loop

but the ionic sourcecode seems to set loop to false and i did not change that

(+ the initial duplicate slide should not be the one displayed and not be the first in the slider)</span>

<span is-issue-template></span>

**Comment by rhazn** [comment]
Sorry should have checked the nightly build. This occurs in the 1.2.0 but no longer in nightly.

**Comment by mlynch** [comment]
Cool, yea a fix was pushed yesterday for that and similar issues with slidebox. Thanks!
