### ISSUE TITLE
bug: Popovers and overflow scrolling on iOS

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#4793]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>browser</span>

<span ionic-description>When you have a popover open inside a scroll view, scrolling is still possible on iOS when using the overflow scrolling setting. The popover stays in its place though. This results in a displaced popover.</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Fixed, thanks!

**Comment by Manduro** [comment]
Thank *you*!

**Comment by mlynch** [comment]
:100:
