### ISSUE TITLE
bug: scrollTop doesn't work inside a modal

### ISSUE THREAD

**Issue by mshima** [driftyco/ionic#4795]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I need a modal to be shown in different parts of the application so I implemented it inside a service.
When the criteria changes or the modal hides the modal should be scrolled to the top.

When calling $ionicScrollDelegate.$getByHandle('??').scrollTop() the DelegateService filters the delegates based on $$delegateHandle name and the function $$filterFn;

The function passed by $ionicScroll is return $ionicHistory.isActiveScope()
Seems that $ionHistory ignores modals completely. Is this a bug??
The scrollTop will work only if the modal is created inside a controller and the controller scope is passed to the modal.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @mshima!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4795). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4795)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mshima** [comment]
The

**Comment by mshima** [comment]
This change on $ionicScroll will work as an workaround but seems other delegates should benefit from the DelegateService change.

```
Index: ionic.bundle.js
===================================================================
--- ionic.bundle.js	(revision 20832)
+++ ionic.bundle.js	(revision 20833)
@@ -57338,6 +57329,7 @@
 .controller('$ionicScroll', [
   '$scope',
   'scrollViewOptions',
+  '$log',
   '$timeout',
   '$window',
   '$location',
@@ -57346,6 +57338,7 @@
   '$ionicHistory',
 function($scope,
          scrollViewOptions,
+         $log,
          $timeout,
          $window,
          $location,
@@ -57379,8 +57372,15 @@
     .data('$$ionicScrollController', self);
 
   var deregisterInstance = $ionicScrollDelegate._registerInstance(
-    self, scrollViewOptions.delegateHandle, function() {
-      return $ionicHistory.isActiveScope($scope);
+    self, scrollViewOptions.delegateHandle, function(instance) {
+      var ret = $ionicHistory.isActiveScope($scope);
+      if(!ret && instance.$$delegateHandle && instance.$$delegateHandle.indexOf("-modal") > -1){
+        $log.warn(
+                'Delegate for handle "' + instance.$$delegateHandle + '" is not active.'
+               );
+        return true;
+      }
+      return ret;
     }
   );
```

**Comment by Alexintosh** [comment]
I'm having all kind of scroll problems inside modals with ionic 1.2.4.

None of these methods works for me:
```
$ionicScrollDelegate.scrollTo(0, 9999999999);
$ionicScrollDelegate.scrollBottom(true);
$ionicScrollDelegate.$getByHandle('mainScroll').scrollBottom();
```
Also I'm not able to scroll inside a textarea if it's inside a modal, works well everywhere else.

**Comment by Alexintosh** [comment]
Update:
Using the same $scope in modal will make this works, before I was creating a totally new scope:
`var scope = $rootScope.$new();`

For future reference: To fix any element that won't scroll, just add the class "scroll"

**Comment by jgw96** [comment]
Hello! @mshima are you still experiencing this issue or were you able to add the scroll class and fix it?

**Comment by mshima** [comment]
Hello @jgw96, the fix Alexintosh used is to reuse the same $scope just like I told in the last paragraph (poorly explained sorry).

Adding the scroll class will not fix this bug.

In my case I implemented a modal as a singleton that will be opened in more than one controller.
Reuse the controller’s scope is not an option.
I am using the first patch I provided.

**Comment by jgw96** [comment]
Thank for the info @mshima ! Will have to look at this some more.

**Comment by panlina** [comment]
passing `$scope.$new()` does the trick also.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#25
