### ISSUE TITLE
perf: [hidden] on a button in a page executes on mouse movement in Browser

### ISSUE THREAD

**Issue by av2k** [driftyco/ionic#4797]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello,

on the current ionic v2 beta, on nav-menu navigation-style app, I have the following simple code for a page called AuthenticatorPage.

Expected behaviour: the code for the [hidden] directives is executed when the page is rendered or the programmer explicitely asks for a page refresh.

Encountered behaviour: by merely moving the mouse, the console fires countless log messages due to repeated execution of the code for the [hidden] directives.
 
In this example case the method is quickly executed, but methods that perform larger calculations could severely affect the performance of the application in the browser.

import {Page, Geolocation, NavController} from 'ionic/ionic';
@Page({
  templateUrl: 'app/authenticator/authenticator.html'
})
export class AuthenticatorPage {
  constructor(nav: NavController) {
    this.encKey == "ABC"; // todo replace with local storage read attempt
    this.macKey == "DEF";
    this.nav = nav;
  }
  isAuthenticationSetUp() {
    console.log( "calling isAuthenticationSetUp()" );
    if( ( this.encKey == null ) || ( this.macKey == null ) ) {
      return false;
    } else {
      return true;
    }
  }
}

The HTML file looks like this:

<ion-navbar *navbar>
  <button menuToggle>
    <icon menu></icon>
  </button>
  <ion-title>Authenticator</ion-title>
</ion-navbar>
<ion-content padding class="authenticator">
  <ion-card>
  <ion-card-header>
    Status Overview
  </ion-card-header>
  <ion-card-content style="width:100%">
    <p><span style="width:40%;display:inline-block;">Authenticator:</span> <span style="color:green;">Enabled</span></p>
    <p><span style="width:40%;display:inline-block;">TAN:</span> <span style="color:red;">Expired</span></p>
  </ion-card-content>
</ion-card>
<button block [hidden]="isAuthenticationSetUp()">Do X</button>
<button block [hidden]="!isAuthenticationSetUp()">Do Y</button>
<button block [hidden]="!isAuthenticationSetUp()">Do Z</button>
</ion-content>

The Log output: (only an excerpt)

317   625627   log      calling isAuthenticationSetUp()
319   625628   log      calling isAuthenticationSetUp()
318   625628   log      calling isAuthenticationSetUp()
320   625628   log      calling isAuthenticationSetUp()
322   625630   log      calling isAuthenticationSetUp()
321   625629   log      calling isAuthenticationSetUp()
323   625632   log      calling isAuthenticationSetUp()
324   625632   log      calling isAuthenticationSetUp()
326   625633   log      calling isAuthenticationSetUp()
325   625633   log      calling isAuthenticationSetUp()
327   625634   log      calling isAuthenticationSetUp()
329   625634   log      calling isAuthenticationSetUp()
328   625634   log      calling isAuthenticationSetUp()
330   625635   log      calling isAuthenticationSetUp()
331   625635   log      calling isAuthenticationSetUp()
332   625635   log      calling isAuthenticationSetUp()
333   625636   log      calling isAuthenticationSetUp()
334   625636   log      calling isAuthenticationSetUp()
335   625644   log      calling isAuthenticationSetUp()
336   625644   log      calling isAuthenticationSetUp()
337   625645   log      calling isAuthenticationSetUp()
338   625646   log      calling isAuthenticationSetUp()
339   625647   log      calling isAuthenticationSetUp()
340   625648   log      calling isAuthenticationSetUp()
341   625649   log      calling isAuthenticationSetUp()
342   625649   log      calling isAuthenticationSetUp()
345   625650   log      calling isAuthenticationSetUp()
343   625649   log      calling isAuthenticationSetUp()
344   625650   log      calling isAuthenticationSetUp()
346   625650   log      calling isAuthenticationSetUp()
347   625652   log      calling isAuthenticationSetUp()
348   625652   log      calling isAuthenticationSetUp()
349   625652   log      calling isAuthenticationSetUp()
350   625653   log      calling isAuthenticationSetUp()
351   625653   log      calling isAuthenticationSetUp()
353   625654   log      calling isAuthenticationSetUp()
354   625654   log      calling isAuthenticationSetUp()
355   625654   log      calling isAuthenticationSetUp()
352   625653   log      calling isAuthenticationSetUp()

$ ionic info

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4
Node Version: v5.1.0

Browser: current Safari</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @av2k!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4797). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4797)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @av2k, we're not quite merging v2 issues into this repo just yet. Mind posting over here so v2 team can get this fixed? Thanks! github.com/driftyco/ionic2/issues/new

**Comment by av2k** [comment]
Thank you; I just posted it on the ionic2 issue tracker.
