### ISSUE TITLE
feat: .grade-c .checkbox Icon Left / Top CSS wrong

### ISSUE THREAD

**Issue by c2software** [driftyco/ionic#4799]
**Type**: <span ionic-type>issue</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On .grade-c the Checked Icon in the Checkbox is not centered.

To Fix this i wrote some CSS in this Codpen:
You can Play with the CSS and the Config Provider to test
http://codepen.io/anon/pen/GooGaJ

Solution is:
.grade-c .checkbox-circle .checkbox-icon:after {
  top: -1px;
  left: 5px; 
}

.grade-c .checkbox-square .checkbox-icon:after {
  top: -5px;
  left: 5px; 
}</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic 1? 1.3.0

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
