### ISSUE TITLE
bug: V 1.2 Slider with images overlays everything else?

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#4802]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Slider in ionic#v1.2.0-nightly-1839  appears to not overlay correctly. 

Issue seen here:
http://codepen.io/uofmmike/pen/pggqbB

(and inline here)
```
<html ng-app="ionicApp">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">

  <title>Ionic Custom Loading Bar</title>

  <link href="//code.ionicframework.com/nightly/css/ionic.css" rel="stylesheet">
  <script src="//code.ionicframework.com/nightly/js/ionic.bundle.js"></script>

</head>

<body ng-controller="MainCtrl">

  <ion-view view-title="Dashboard">
    <ion-content class="padding">
      <div class=" card">
        <h4>Layered behind :(</h4>
      </div>
      <div class='card'>
        <ion-slides options="">
          <ion-slide-page>
            <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Golde33443.jpg/398px-Golde33443.jpg'>
          </ion-slide-page>
          <ion-slide-page>
            <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Golde33443.jpg/398px-Golde33443.jpg'>
          </ion-slide-page>
        </ion-slides>
      </div>
    </ion-content>
  </ion-view>


</body>

</html>

```</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Should be fixed in master and will be in 1.2.1 this week. Mind letting me know how that works?

**Comment by uofmmike** [comment]
Thanks for the reply @mlynch!

Don't know if i've got a config wrong, now, i'm not seeing anything in the pen I provided earlier. 

I replaced the images and followed the docs at :http://ionicframework.com/docs/nightly/api/directive/ionSlides/

Now I'm not seeing anything from the slider?
http://codepen.io/uofmmike/pen/pggqbB

**Comment by uofmmike** [comment]
Looks like it's an issue within the card, outside of the card the slider is fine, inside there appears to be no height. I'll create a separate issue for a new patch.
