### ISSUE TITLE
bug: Multiple ion-spinners (with same icon)

### ISSUE THREAD

**Issue by ahlarsen** [driftyco/ionic#4819]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you have multiple ion-spinners with the same icon, and "destroys" one of them by for example ng-if the one with the ng-if is correctly destroyed and removed from DOM but the other spinner(s) with the same icon is getting stopped to and can't be used anymore. 

See example (notice the two ion-spinners with "android" icon):
http://codepen.io/dennishn/pen/OMNybR

Then you click the toggle, the first ion-spinner with "android" icon will be removed by ng-if and the other "android" spinner is getting stopped too. 

My hot-fix atm is not destroying my spinners but simply hide/show them with ng-hide or show but I don't think this is optimal behaviour. 

I have following scenario where I need two spinners: 

One spinner for loading some async content (which I want to remove then my content has been loaded as it's not needed anymore)

One spinner to show some progress, example clicking on a button by submitting data. 

I don't know if this is a "bug" or just how it's designed.</span>

<span is-issue-template></span>

**Comment by PerfectionCSGO** [comment]
I was actually looking into this myself, I was also having this issue when working on this: 
https://github.com/driftyco/ionic/issues/4808 where I use the android spinner to show progress on a PTR. 

I use the same spinner to show in the template of $ionicLoading.

Could you share your hot fix?

**Comment by danbucholtz** [comment]
This issue is fixed and will be in the nightly build of Ionic starting tomorrow.

Thanks,
Dan
