### ISSUE TITLE
Stuck scroll position

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#482]
As per http://forum.ionicframework.com/t/default-scrolling-problem/536

This happens quite a lot and makes the scroll experience jumpy. What happens is that the scroll seems to go "off page" - and then stay there. 

Specifically, this seems to happen on scrolling content that has pull to refresh active

**Comment by whitecat** [comment]
I am facing this issues also now. I scroll a bit on the page and the scroll bar get stuck and starts producing the error: `TypeError: zyngaCore.effect.Animate.route is not a function. (In 'zyngaCore.effect.Animate.route(self.__isDecelerating)', 'zyngaCore.effect.Animate.route' is undefined)`
