### ISSUE TITLE
bug: Ion-slides ionic 1.2.1 loop bug (Codepen provided)

### ISSUE THREAD

**Issue by deliverymanager** [driftyco/ionic#4833]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There is a bug with the new ion-slides (swiper) when placing a loop with autoplay. You can see that when it goes at the last slide it gets stack at the first slide.
http://codepen.io/deliverymanager/pen/rxLBmW</span>

<span is-issue-template></span>

**Comment by deliverymanager** [comment]
Did someone identify the bug?
Let me know if you need more info.

**Comment by mlynch** [comment]
Did you try a recent 1.2 release? This was fixed I believe. Let me know and I'll reopen if not.
