### ISSUE TITLE
bug: [WP8.1] collection-repeat does not function on device

### ISSUE THREAD

**Issue by PerfectionCSGO** [driftyco/ionic#4835]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This problem is present in Ionic 1.2.1 on a Windows 8.1 Phone. 

iOS9.1 iPad: Works
Android 4.2 Tablet: Works
Android 5.x.x Phone: Works
Windows 8.1 Phone: non-functional on Nokia Lumia 520.

My current workaround is to use ng-repeat conditional for windows phone instead of collection-repeat.
</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Thanks. We don't support Windows Phone 8 so going to close as we can't provide a fix at this time. Sorry about that.
