### ISSUE TITLE
bug: Problem in slide pagination with multiple ion-slides

### ISSUE THREAD

**Issue by leoruhland** [driftyco/ionic#4837]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When you add two ion-slides directives on the same page, the first directive navigation(dots) is synchronized with the second directive.

http://codepen.io/leoruhland/pen/obLGgw</span>

<span is-issue-template></span>

**Comment by taylormaster** [comment]
i have same problem, when i use slider1 and slider2 and use slider1.slideTo(), this control slider2
any solution?
