### ISSUE TITLE
bug: Uncaught TypeError: Cannot read property 'scrollTo

### ISSUE THREAD

**Issue by Josephdias92** [driftyco/ionic#4843]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>var scrollTop = (event.detail || event.originalEvent && event.originalEvent.detail).scrollTop;

not able to get scollTop in 1.2.1 ionic version 
it used to work in ionic 1.1</span>

<span is-issue-template></span>

**Comment by ghostgrass** [comment]
+1

**Comment by jgw96** [comment]
Thanks for submitting this issue! I am currently closing this as it is a dupe of https://github.com/driftyco/ionic/issues/4841 but feel free to reopen if needed!
