### ISSUE TITLE
bug: ionicModal.show promise won't resolve modal ctrl

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic#4846]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On the latest documentation it says the show method returns a promise that resolve to the modal, but I get undefined. http://ionicframework.com/docs/api/controller/ionicModal/

The modal is showing correctly though.
```
$ionicModal.fromTemplate(Templates.get("addCameraHTML"), {
	animation: "slide-in-up"
}).show().then(modal => {
	/* This logs `undefined` */
	console.log(modal);
​
	//setTimeout(modal.remove.bind(modal), 5000);
});
```
</span>

<span is-issue-template></span>

**Comment by 42shadow42** [comment]
The documentation indicates a promise that is resolved when the modal is showed, it doesn't indicate the modal being presented. You could try using closure to gain access to the modal instance. I.E.

var modal = $ionicModal.fromTemplate(Templates.get("addCameraHTML"), {
    animation: "slide-in-up"
});
modal.show().then(function(){
    /* This logs `undefined` */
    console.log(modal);
​
    //setTimeout(modal.remove.bind(modal), 5000);
});

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
