### ISSUE TITLE
bug: Ionic tabs are nto working with webpack and ng-template-loader

### ISSUE THREAD

**Issue by jusefb** [driftyco/ionic#4852]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I am using ionic in my project and am building the application using webpack. What I have discovered today that for some reason ionic tabs do not work if the templateUrl provided to the top tab state is loaded via webpack ng-template-loader. The template does get loaded but the tab icons and text do not display. Things start getting displayed once you click on the tab. Can anyone share some light on why this would be the case?

**Not working**

```javascript
....

var tabsTmpl = require("./hpzone/dashboard/components/dashboardMobile/mobile.tabs.html");
...
  // setup an abstract state for the tabs directive
  .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: tabsTmpl
    //templateUrl: '/templates/mobile.tabs.html'
  })
......
```

**Working** 

```javascript
...
  // setup an abstract state for the tabs directive
  .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: '/templates/mobile.tabs.html'
    //templateUrl: '/templates/mobile.tabs.html'
  })
......
```

After further investigation it seems like templates loaded into angular $templateCache don't work with ionic tabs. I have tried to do the following and it produces the same results - tabs not rendering as expected:

```javascript
...
$templateCache.put("hpzone/dashboard/components/dashboardMobile/mobile.tabs.html", `
  <!--
Create tabs with an icon and label, using the tabs-positive style.
Each tab's child <ion-nav-view> directive will have its own
navigation history that also transitions its views in and out.
-->
<ion-tabs class="tabs-icon-top">

  <!-- Dashboard Tab -->
  <ion-tab title="Dashboard" icon-off="ion-ios-pulse" icon-on="ion-ios-pulse-strong" ui-sref="tab.dash">
    <ion-nav-view name="tab-dash"></ion-nav-view>
  </ion-tab>

  <!-- Account Tab -->
  <ion-tab title="Account" icon-off="ion-ios-gear-outline" icon-on="ion-ios-gear" ui-sref="tab.account">
    <ion-nav-view name="tab-account"></ion-nav-view>
  </ion-tab>
</ion-tabs>
  `)

...

  .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: "hpzone/dashboard/components/dashboardMobile/mobile.tabs.html"
  })

...

```</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @jusefb!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4852). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4852)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
