### ISSUE TITLE
bug: option button duplicated if rendered conditionally

### ISSUE THREAD

**Issue by jrencz** [driftyco/ionic#4853]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When ion-option-button is rendered conditionally (for example inside `ng-switch-when`) it gets duplicated each time it's re-rendered.

Example:
http://codepen.io/jrencz/pen/bEeQNd
1. Open options, observe 2 option buttons
2. close options
3. Increase counter
4. Open options, observe 4 option buttons

Expected behaviour:
option buttons can be safely placed inside blocks rendered conditionally</span>

<span is-issue-template></span>

**Comment by jrencz** [comment]
This is not shown on the example but in case the ion-option-button gets removed it's still there and user can swipe.
User should no longer be able to swipe if ion-option-button is not rendered.

**Comment by jrencz** [comment]
When `ngIf` is applied directly to the ion-option-button then it's possible to remove it.

**Comment by shrolox** [comment]
Same issue here

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#28
