### ISSUE TITLE
bug: Unable to install ionic on Windows 7.

### ISSUE THREAD

**Issue by bob1457** [driftyco/ionic#4854]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi there,

I got a problem to install ionic on my Windows 7 Home Premium edition.

I got an error saying:

npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\ionic\1.7
.12\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\core-util
-is\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\source-ma
p\0.3.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\cipher-ba
se\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\cipher-ba
se\1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\buffer-xo
r\1.0.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Bob\AppData\Roaming\npm-cache\buffer-xo
r\1.0.3\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\Bob\npm\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node
_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\li
b\source-map\binary-search.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node_modu
les\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules
\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\combi
ne-source-map\node_modules\source-map\lib\source-map\binary-search.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\Bob\npm\node_
modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_mod
ules\cordova-js\node_modules\browserify\node_modules\browser-pack\node_modules\c
ombine-source-map\node_modules\source-map\lib\source-map\binary-search.js']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Bob\\npm\\node_modules\\ionic\\node_modules\\ionic-
app-lib\\node_modules\\ionic-cordova-lib\\node_modules\\cordova-js\\node_modules
\\browserify\\node_modules\\browser-pack\\node_modules\\combine-source-map\\node
_modules\\source-map\\lib\\source-map\\binary-search.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

My node.js version: 4.2.3, npm 2.14.7
OS: Windows 7 Home Premium, service pack 1

I did clean cache, run command prompt as Administrator, check all folder permissions(it seems like a permission issue, but I cannot see any problem in Windows permssions), etc., no luck, frustrated in the past couple of day. I desperately need help. By the way, I successfully installed ionic on the other Windows 7 enterprise without any problems. Not sure what are the difference here. 

More information: I have Visual Studio 2015 enterprise installed with Cordova Tools (the one I successfully installed ionic was with Visual Studio 2015 Community edition with Cordova tools installed)

Thanks.

Bob
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @bob1457!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4854). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4854)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by PerfectionCSGO** [comment]
I don't think this has anything to do with Ionic but is that what is contained in debug.log?

npm ERR! Please include the following file with any support request:
npm ERR! C:\windows\system32\npm-debug.log

**Comment by bob1457** [comment]
I know it could not be the problem of ionic, but it looks like permission problem. Here attached is the log file.
Maybe it was the npm's issue? I search the web, and tried all available solutions provided on the web, but no luck.
Can you still take a look at the logs and point me to the right direction of troubleshooting?
Thanks.
Bob  

    On Wednesday, December 23, 2015 10:26 AM, Max Lynch <notifications@github.com> wrote:
 

 Closed #4854.—

**Comment by bob1457** [comment]
Or could it be the file name was too long, and file structure is too deep for Windows? What could be the solution if that is the case? I looked at the package.tgz in the npm-cache, could it be package corrupted? I did disabled the antivirus when I was installing ionic, though. Log says untar error.
Thanks.
Bob  

    On Wednesday, December 23, 2015 10:56 AM, Bob Yuan <bob.yuan@yahoo.com> wrote:
 

 I know it could not be the problem of ionic, but it looks like permission problem. Here attached is the log file.
Maybe it was the npm's issue? I search the web, and tried all available solutions provided on the web, but no luck.
Can you still take a look at the logs and point me to the right direction of troubleshooting?
Thanks.
Bob  

    On Wednesday, December 23, 2015 10:26 AM, Max Lynch <notifications@github.com> wrote:
 

 Closed #4854.—

**Comment by bob1457** [comment]
While looking at the log, the line 20380 says: tar.unpack untar error..., and line 20381 says, unlok done using c:\...then line 20382: verbose stack at Error (native), does that mean unpacking packages failed so the unpacked files not found (open error)?
Thanks. 

    On Wednesday, December 23, 2015 10:59 AM, Bob Yuan <bob.yuan@yahoo.com> wrote:
 

 Or could it be the file name was too long, and file structure is too deep for Windows? What could be the solution if that is the case? I looked at the package.tgz in the npm-cache, could it be package corrupted? I did disabled the antivirus when I was installing ionic, though. Log says untar error.
Thanks.
Bob  

    On Wednesday, December 23, 2015 10:56 AM, Bob Yuan <bob.yuan@yahoo.com> wrote:
 

 I know it could not be the problem of ionic, but it looks like permission problem. Here attached is the log file.
Maybe it was the npm's issue? I search the web, and tried all available solutions provided on the web, but no luck.
Can you still take a look at the logs and point me to the right direction of troubleshooting?
Thanks.
Bob  

    On Wednesday, December 23, 2015 10:26 AM, Max Lynch <notifications@github.com> wrote:
 

 Closed #4854.—
