### ISSUE TITLE
bug: ion-slides breaking in modal

### ISSUE THREAD

**Issue by rushtehrani** [driftyco/ionic#4855]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Getting the following errors when adding Swiper/ion-slides into a modal:

```
TypeError: Cannot read property 'get' of undefined
    at Object.Swiper (ionic.bundle.js:9221)
    at ionic.bundle.js:63349
    at ionic.bundle.js:30889
    at completeOutstandingRequest (ionic.bundle.js:18574)
    at ionic.bundle.js:18846(anonymous function) @ ionic.bundle.js:25510
ionic.bundle.js:25510 TypeError: Cannot read property 'update' of undefined
    at ionic.bundle.js:63317
    at ionic.bundle.js:30889
    at completeOutstandingRequest (ionic.bundle.js:18574)
    at ionic.bundle.js:18846
```

See: http://codepen.io/anon/pen/OMXdVw</span>

<span is-issue-template></span>

**Comment by floernoult** [comment]
I confirm! We have the exact same issue and error in our modals.

**Comment by mlynch** [comment]
Thanks will fix in next release (possibly landing a commit for this one over the holidays)

**Comment by rushtehrani** [comment]
Thanks!
