### ISSUE TITLE
bug: Input Range in ion-slides [1.2.1]

### ISSUE THREAD

**Issue by privetr** [driftyco/ionic#4859]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When an input range is in the new ion-slides directive, It is really hard to change the value without swiping to another slide...

Here is a codepen where you can reproduce the problem : http://codepen.io/privetr/pen/NxrVxo

In the previous version (ion-slide-box) I had to use a directive to fix this scroll problem, but this does not work anymore.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
