### ISSUE TITLE
cordova.js not found.

### ISSUE THREAD

**Issue by HelloGrayson** [driftyco/ionic#486]
I just created an app using `ionic create` command. Then I start the app for viewing in the browser like so:

```
cd wwww
python -m SimpleHTTPServer 8000
```

When I access the app in the browser everything looks fine, except that I get the following error.

```
GET 127.0.0.1:8000/cordova.js 404 (File not found)
```

Any idea what the deal is?

**Comment by Jaiqson** [comment]
Comment in IONIC Slidemenu exemple:


<script src="cordova.js"></script>

=)
