### ISSUE TITLE
bug: <ion-scroll>: Zoom in/out & scroll within canvas

### ISSUE THREAD

**Issue by hofman-p** [driftyco/ionic#4867]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

With new version of Ionic (1.2), I can't zoom in / out with pinch & scroll within canvas.</span>

<span is-issue-template></span>

**Comment by leschirmeur** [comment]
Have you tried setting overflow-scroll="false" to your <ion-scroll> element?

**Comment by hofman-p** [comment]
It works like a charm.

Thank you very much !

**Comment by mlynch** [comment]
Thanks, we should document this.

**Comment by edvincandon** [comment]
Hey, I stumbled upon this issue while researching for canvas zoom implementations.
Has this been fixed? I just did a quick test and it's working on ios, I can zoom from within a canvas.

**Comment by hofman-p** [comment]
Hi @edvincandon ,

I tested it again right now, it still doesn't work with Android without overflow-scroll="false" in ion-scroll.

Also, I use ion-scroll inside ion-content to make it work. It doesn't if I don't, I don't know why.

**Comment by edvincandon** [comment]
So it's working on iOS on your side? I'll give it a try on Android tonight, will let you know how it goes. 

Also, weird that you have to use an ion-content wrapping your ion-scroll, I usually just replace my ion-content by an ion-scroll when I want to use zooming/scrolling/panning features.

**Comment by hofman-p** [comment]
I did it on Android. I don't know on iOS, but it's working on Ripple iOS emulator.

I agree, that's weird. I was so tired nothing worked, so I tested this, and it worked... Why, I don't know, indeed !

**Comment by mechon** [comment]
I tested on ios device and zoom in/out is not working. No project code change, I just updated project lib from 1.2.4 to 1.3.

**Comment by jgw96** [comment]
@mechon was it working for you on 1.2.4?

**Comment by edvincandon** [comment]
I have it working on ios with latest ionic 1.3. 
I basically only have a fullscreen canvas wrapped in an `<ion-scroll>` 

How are you setting it up on your side?

**Comment by mechon** [comment]
@jgw96 yes it was working fine before the update.
@edvincandon looks like it is working again after I added overflow-scroll="false" on ion-scroll.

**Comment by Ionitron** [comment]
Greetings @hofman-p!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
