### ISSUE TITLE
bug: ng-enter,ng-leave don't fire when using slides

### ISSUE THREAD

**Issue by danpincu** [driftyco/ionic#4868]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After upgrading to 1.2.1 I have a weird problem.
I'm using animate.css in my app to slide a popup in & out. In addition I have a couple of views using slides. When I open the popup from the main view it animates fine, but after moving to one of the slides views the animations are not played (the popup just appears). It also remains like this when going back to the main view.
At first I thought it was something with the new ion-slides directive, but it actually also happens with ion-slide-box.

Here's a codepen to demonstrate:
http://codepen.io/anon/pen/zrKPrE

I also tried adding animations from code - in this case after moving to the slides view again nothing happens and nothing is written to the console.

.animation('.popup', [function() {
    return {
        enter: function (element, doneFn) {
            console.debug("enter");
            jQuery(element).fadeIn(1000, doneFn);
        },
        leave: function(element, doneFn) {
            console.debug("leave");
            jQuery(element).fadeOut(1000, doneFn);
        }
    }
}])</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Thanks! We were disabling ngAnimate in slides so I removed that for now to assess with the new slider.
