### ISSUE TITLE
bug: Error if ion-slides option autoHeight is true

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#4870]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I set autoHeight to true for ion-slides, I get the following error.

    39    194793   error    TypeError: Cannot read property 'update' of undefined
        at http://localhost:8100/lib/ionic/js/ionic.bundle.js:63317:25
        at http://localhost:8100/lib/ionic/js/ionic.bundle.js:30889:31
        at completeOutstandingRequest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:18574:10)
        at http://localhost:8100/lib/ionic/js/ionic.bundle.js:18846:7</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Looks like probably a bug from a different place creeping up. Should be fixed in next release.
