### ISSUE TITLE
bug: Button back show different

### ISSUE THREAD

**Issue by kodemi** [driftyco/ionic#4871]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.2</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi to day i find issue 
If i use this code in my state

    .state('student.profile', {
            url: '/profile',
            authenticate: true,
            roles: ['student'],
            views: {
                'menuContent': {
                    templateUrl: 'modules/students/profile/update/profile-update.html',
                    controller: 'StudentProfileUpdateCtrl',
                }},
            resolve: {
                grades: function(gradeService) {
                    return gradeService.getByCountry().then(function(data) {

                         return data;
                    });
                }
            }
        })
I button back 
http://prntscr.com/9fjfer
But when i used code in my state Without resolve

    .state('student.profile', {
            url: '/profile',
            authenticate: true,
            roles: ['student'],
            views: {
                'menuContent': {
                    templateUrl: 'modules/students/profile/update/profile-update.html',
                    controller: 'StudentProfileUpdateCtrl',
                }}
        })
And i but the code to controller StudentProfileUpdateCtrl

gradeService.getByCountry().then(function(data) {

                         $scope.grade = data;
                    });
Result with button
http://prntscr.com/9fjg27</span>

<span is-issue-template></span>

**Comment by kodemi** [comment]
Resubmitted bug for @webinopoly

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
