### ISSUE TITLE
bug: $ionicView's events in 1.2.x work diffirently from 1.1.x 

### ISSUE THREAD

**Issue by Kopleman** [driftyco/ionic#4872]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Here is pens: [1.1.1](http://codepen.io/anon/pen/ZQpdNv), [1.2.1](http://codepen.io/anon/pen/pgEXPE#0).
You can notice that in 1.1.x `$ionicView.%%eventName%%` events catchable in any controller that bound to the state, in 1.2.x its only catchable in last one. Maybe this is a bug or issue like i think but this change is not mantioned in docs. Thank you.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @Kopleman!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4872). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4872)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by randdusing** [comment]
I'm noticing this as well. I hope this isn't intended

**Comment by randdusing** [comment]
In 1.2.1, ``` switcher.emit('after', enteringData, leavingData); ``` is inside the if statement. In 1.1.1, it's outside and before the if statement. Changing it back seems to fix the issues I'm having, but I'm not sure if it causes unintended consequences.

```javascript
// the most recent transition added has completed and all the active
// transition promises should be added to the services array of promises
if (transitionId === transitionCounter) {
  $q.all(transitionPromises).then(ionicViewSwitcher.transitionEnd);

  // emit that the views have finished transitioning
  // each parent nav-view will update which views are active and cached
  switcher.emit('after', enteringData, leavingData);
  switcher.cleanup(enteringData);
}
```

**Comment by mlynch** [comment]
@randdusing what issues are you having?

**Comment by randdusing** [comment]
afterLeave events aren't always fired. It looks like it depends on how I "leave" a view. If I click a button with a ui-sref tag, it works fine. If I click a button that eventually calls $state.go(), the afterLeave event is never fired.

**Comment by tomvanenckevort** [comment]
I'm running into the same problem as well, where I have multiple controllers with an `$ionicView.afterEnter` event handler, and only the last one being called.

I've used @randdusing's suggestion to move the `switcher.emit` call back outside of the if statement. This seems to solve my problem, but it would be good to know why it was changed and whether the changed event handling consequences of this were intended.

**Comment by danbucholtz** [comment]
Hi @Kopleman and others,

This should be resolved in the nightly build.  We did a lot of work with the life cycle events.  Can you test on the latest build?  Let me know if you need some help.

http://code.ionicframework.com/#nightly

I guess our staging site hasn't deployed in the past week or so, but we do have new and improved docs.
http://ionic-site-staging.herokuapp.com/docs/nightly/api/directive/ionView/

Basically, in addition to dispatching the event upwards (emit) from the correct scope, but we also now fire events downwards (broadcast) to work with ui-router nested views.

```
$scope.$on("$ionicParentView.enter", function(event, data){
   // woot, I received the event!
});
```

Please let me know if you have any issues everyone.

Thanks,
Dan

**Comment by Kopleman** [comment]
Sorry for late answer, but it doesnt work or maybe i've missed something, but it still works as before except some new eventnames. Here is updated pen for [1.3.1](http://codepen.io/Kopleman/pen/WxbvXp) with `$ionicParentView.enter`
