### ISSUE TITLE
bug: Ionic serve and livereload doesn't work anymore

### ISSUE THREAD

**Issue by AdrienDC** [driftyco/ionic#4877]
Hi,
recently I was unable to debug in serve mode or livereload... Does anyone have some suggestion because I'm a bit lost right now..

Ionic 1.2.1 Ionic CLI 1.7.9 Cordova 5.4.1

![timeout](https://cloud.githubusercontent.com/assets/15973554/12046722/af22d6f8-aebe-11e5-99db-267904c2236d.png)

**Comment by mlynch** [comment]
Can you post here? https://github.com/driftyco/ionic-cli
