### ISSUE TITLE
bug: Text indent on textarea in  Android

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#4878]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>In chrome on android text indent has a issue similar to this commit

535b96bad19fd3682927c00b6eed5840cc08b2c5</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
