### ISSUE TITLE
bug IOS 9.2 ion-view title not work

### ISSUE THREAD

**Issue by Mr-Luo** [driftyco/ionic#4879]
Type: bug

Platform: IOS 9.2,Iphone6

 ion-view title not work.

```
<ion-view title="test"></ion-view>
or
<ion-view view-title="test"></ion-view>
```

not work.need to refresh to update the title.

**Comment by danbucholtz** [comment]
Hi @Mr-Luo,

I am not seeing that.  Can you provide an example to reproduce?

If I want to evaluate view-title as an expression, I must write it like this:

```
<ion-view view-title="{{test}}"></ion-view>
```

Otherwise, if I want a fixed string:

```
<ion-view view-title="myTitle"></ion-view>
```

Please let me know if you're still having issues and I will re-open.

Thanks,
Dan

**Comment by Mr-Luo** [comment]
thanks,our project was dead.So i couldn't get the source code.
