### ISSUE TITLE
bug: has-footer not applied if ionFooterBar has ngIf

### ISSUE THREAD

**Issue by jrencz** [driftyco/ionic#4880]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In case where ionFooterBar has additional scope on it (applied via ng-if) it fails to reach `ionView` scope to set `$hasFooter` flag (which is used by `ionContent` to apply `has-footer` class). See:
where `ionFooterBar` writes the scope flag: https://github.com/driftyco/ionic/blob/9de76628b987edf1823bc0b5f3eca76bd9e8b559/js/angular/directive/headerFooterBar.js#L157
and where `ionContent` reads it https://github.com/driftyco/ionic/blob/9de76628b987edf1823bc0b5f3eca76bd9e8b559/js/angular/directive/content.js#L84-L94

If `ngIf` is added to `ionFooterBar` then `ionFooterBar` writes to an incorrect scope

In fact this behaviour (as well as the workaround) is well described in the official pen: Footer Toggle: Nightly http://codepen.io/ionic/pen/mHtlC

Additional `ngClass` bound to the same flag `showFooter` as used in `ngIf` attribute on the `ionFooterBar` is responsible for applying `has-footer` class onto `ionContent` element.

The same problem with header/subheader/subfooter

I think the way to fix this would be for `ionFooterBar`/`ionHeaderBar` to require `ionContent` controller (which does not exist yet) and `ionContent` controller should expose methods to set all those flags (header/subheader/footer/subfooter/tabs/etc).

Scope traversal is always error-prone ;)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jrencz** [comment]
I can't update my project to the latest right now so I can't check in real.life conditions.

The pen I mentioned is still there and it has no depreciation message. I'm not aware if it's still linked from the documentation or not but since it hasn't been removed I assumed it's still needed.

That's all I can tell right now.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#31
