### ISSUE TITLE
Slides (ion-slide) v 1.2.1 within a card doesn't display properly

### ISSUE THREAD

**Issue by uofmmike** [driftyco/ionic#4881]
http://codepen.io/uofmmike/pen/pggqbB

Slide height not correct within card. Works fine out of the card. 
Happened after related: #4802

'''
<html ng-app="ionicApp">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">

  <title>Ionic Slides v1.2 issue</title>

  <link href="http://code.ionicframework.com/nightly/css/ionic.min.css" rel="stylesheet">
  <script src="http://code.ionicframework.com/nightly/js/ionic.bundle.min.js"></script>

</head>

<body ng-controller="MainCtrl">

  <ion-view view-title="Dashboard">
    <ion-content class="padding">
        <ion-slides on-slide-changed="slideHasChanged($index)" options='options'>
          <ion-slide-page>
            <div class="box blue">
              <h1>BLUE</h1></div>
          </ion-slide-page>
          <ion-slide-page>
            <div class="box yellow">
              <h1>YELLOW</h1></div>
          </ion-slide-page>
          <ion-slide-page>
            <div class="box pink">
              <h1>PINK</h1></div>
          </ion-slide-page>
        </ion-slides>
      
      <div class=" card">
        <h4>Layered behind :(</h4>
      </div>
      <div class='card'>
        <ion-slides on-slide-changed="slideHasChanged($index)">
          <ion-slide-page>
            <div class="box blue">
              <h1>BLUE</h1></div>
          </ion-slide-page>
          <ion-slide-page>
            <div class="box yellow">
              <h1>YELLOW</h1></div>
          </ion-slide-page>
          <ion-slide-page>
            <div class="box pink">
              <h1>PINK</h1></div>
          </ion-slide-page>
        </ion-slides>
      </div>
    </ion-content>
  </ion-view>

</body>

</html>
'''

**Comment by uofmmike** [comment]
@mlynch, I don't know if others are experiencing this same issue, but it's a bit of a stopper for me at the moment! Tell Eric B to get on it! (kidding, thanks again for the great product!)

**Comment by uofmmike** [comment]
@ericb any chance I can bug you on this one, (git it, bug)...

**Comment by szuzul** [comment]
It works for me.. I only add width and height,

http://codepen.io/anon/pen/jWGaKZ

**Comment by uofmmike** [comment]
Thanks for the reply @szuzul , that definitely works as a patch -  the issues is dynamic content- i have images in the sliders that aren't a consistent size, and that auto-height setting causes some clipping/guesswork on image sizes. @mlynch any ideas on this one?

**Comment by uofmmike** [comment]
30 day bump^

**Comment by rpinto** [comment]
I'm also experiencing this issue with <ion-slides> inside a card.
The height of the slides is set to 0.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by ilyastam** [comment]
I am still seeing this. Why was this issue closed?
