### ISSUE TITLE
bug: ion-infinite-scroll stops working in v1.2.1

### ISSUE THREAD

**Issue by johnmiroki** [driftyco/ionic#4882]
It worked fine in v1.1.1 and after updating to v1.2.1, it stops working and reports nothing in the browser's console. It seems on-infinite callback doesn't get called. 
Anyone else encounters this problem?

```html
    <ion-content style="padding: 0px; background-color: #f4f4f4;">
          <ion-list>
	        <ion-item>
	        </ion-item>
         </ion-list>
	 <ion-infinite-scroll on-infinite="addItems()" ng-if="moreDataCanBeLoaded()" immediate-check="false"></ion-infinite-scroll>
    </ion-content>
```

**Comment by Peekmo** [comment]
I have the problem too.

**Comment by mlynch** [comment]
Not able to reproduce this currently. Any more info (platform/device/etc.)? 

One thing to keep in mind is that the behavior has changed slightly in iOS. With native scrolling on UIWebView we don't get scroll events so the infinite scroll will trigger once scrolling is done. Perhaps you're seeing that?

**Comment by pengpengmz** [comment]
set config as:
.config(function($stateProvider, $urlRouterProvider, $ionicConfigProvider, $httpProvider) {
  $ionicConfigProvider.scrolling.jsScrolling(true);
v1.1.1 default is true
v1.2.1 default is false

**Comment by johnmiroki** [comment]
@pengpengmz this does fix my "problem". Thank you very much!
