### ISSUE TITLE
Add border color support to mixin

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#4886]
https://github.com/driftyco/ionic/commit/21e54be63c3b39963813d83a4e2aa4c36784fe3e

**Comment by mlynch** [comment]
Need a softer touch on this one

**Comment by vyacheslav-lonschakov** [comment]
Hi @mlynch, why you're commented out this [line](https://github.com/driftyco/ionic/blob/master/scss/_mixins.scss#L6)?

**Comment by germgerm** [comment]
agree with @vyacheslav-lonschakov - this comment causes borderless buttons
uncommenting fixes problem

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#32
