### ISSUE TITLE
bug: scrolling not working

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#4887]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Since Version 1.2 scrolling is not working any more. 
Either i can scroll the content and the on-scroll-event is not fired (i think it´s the browser overflow-scroll instead) or nothing happens. 
I tested it with the nightly pen (http://codepen.io/ionic/pen/JsHjf) and on my iphone and mac with chrome and safari.</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
I don't understand, the codepen works fine for me on my iPhone. Scroll events will only fire while the finger is down on iOS UIWebView. Am I missing something?

**Comment by appwrx** [comment]
oh sorry i missed that there is "overflow-scroll" now.

**Comment by mlynch** [comment]
Is there an issue here or is everything working? I want to make absolutely sure because this would be a top priority big if so. Thanks.

**Comment by appwrx** [comment]
Maybe it's a bug. When native scrolling or overflow scroll is enabled the on-scroll event is not fired. 
For me it's a bug because on-scroll triggers something.

**Comment by mlynch** [comment]
Okay but scrolling itself works fine for you, right? Just the event isn't getting fired? I'll take a look at thay

**Comment by mlynch** [comment]
Works for me in testing. Closing.
