### ISSUE TITLE
Native scrolling not working when embedded into ion-tabs

### ISSUE THREAD

**Issue by cxcxcxcx** [driftyco/ionic#4891]
Reproducing examples here:
http://play.ionic.io/app/a20df0a8efe2

I put ion-content under ion-tab under ion-tabs.

When overflow-scroll=false, it works. but with overflow-scroll=true, it doesn't scroll.

However, it scrolls magically when I (erroneously) put a refresher before the ion-content, but it's not the correct way to run refresher so the refresher doesn't work. If use the refresher the correct way, it wouldn't work.

**Comment by mlynch** [comment]
Okay, thanks, I see the issue. `<ion-content>` is erroneously getting the `.pane` class above which `ionTap` applies thinking it's a child `ion-view` directive subclass.

Will have a fix for this. One solution is to wrap the contents of your tab with `<ion-view>` for now. See the first tab here: http://play.ionic.io/app/951b007c86dc

**Comment by oronbdd** [comment]
Hi,

Facing the same issue in Galaxy S4, version 4.4.2
http://stackoverflow.com/questions/34579787/ionic-2-1-native-scrolling-not-working-with-ion-tabs

Thanks :)

**Comment by mlynch** [comment]
Just fixed and released in 1.2.4. Thanks!

**Comment by linkito** [comment]
Hi. I have the 1.2.4 version and still the issue.... When I refresh with the -livereload environment, the scroll rules well... But when I change the tab to antoher, and come back to the first tab, the scroll not works...
Only in version 1.1.1 this works fine... Anyone can help me?

This is the tab that the scroll not work:

````
<ion-view view-title="CUENTA" cache-view="false">
    <ion-content>
            <ion-list>
                <ion-item class="item-divider">
                    <p class="text-center">{{ data.session }}</p>
                </ion-item>
                <ion-toggle ng-model="data.modeOffline" ng-change="changeMode()" toggle-class="toggle-energized">MODO OFFLINE</ion-toggle>
                <ion-toggle ng-model="data.modePda" ng-change="changePDAMode()" toggle-class="toggle-energized">MODO PDA</ion-toggle>
                <ion-item class="item" ng-click="syncBBDD()">
                    <h2>SINCRONIZAR BBDD</h2>

                    <p>{{ data.lastsync }}</p>
                </ion-item>
                <ion-item class="item" ng-click="emptyBBDD()">
                    <h2>VACIAR BBDD</h2>

                    <p>Vacía la base de datos offline</p>
                </ion-item>
                <ion-item class="item item-text-wrap" ng-click="openZones()" ng-if="listZones" ng-controller="LoginCtrl">
                    <h2>CAMBIAR ZONAS</h2>

                    <p>{{ listZones }}</p>
                </ion-item>
                <ion-item class="item" ng-click="changeDeviceName()">
                    <h2>CAMBIAR NOMBRE</h2>

                    <p>{{ data.devicename }}</p>
                </ion-item>
            </ion-list>
            <button class="button button-block button-assertive" ng-click="doLogout()">Cerrar sesión</button>
    </ion-content>
</ion-view>
```
Thanks!

**Comment by rafialikhan** [comment]
Same issue with ionic 1.3.2. http://play.ionic.io/app/22901856f366 (forked for 1.3.2)

As experimented by @cxcxcxcx if we add overflow-scroll=false, then the scroll works, else if you add over-flow=scroll true, then it does not.
