### ISSUE TITLE
Swiper (ion-slides) does not work on desktop browser (.scroll has height=0) - v1.2.3-nightly-1910

### ISSUE THREAD

**Issue by GregPK** [driftyco/ionic#4893]
Codepen - Only difference is the CSS tab: 

Broken: http://codepen.io/anon/pen/pgRWex
Working: http://codepen.io/anon/pen/wMgrqy

Codepen uses the nighly js while on my localhost I have `v1.2.3-nightly-1910`

This works properly on my Android phone, but is a pain to develop on Chromium or Firefox.

Inspecting withing the browser shows the `.scroll` element with `height=0`:

![selection_055](https://cloud.githubusercontent.com/assets/687754/12078692/0708ef96-b21c-11e5-9d1d-3a7c87386e26.png)

If we set the height via browser inspector to `height: 100%` then it all works as expected.

**Comment by mattrothenberg** [comment]
FWIW, I forked your CodePen and got it to work as expected by removing the top level `<ion-content>` and nesting individual ones in each `<ion-slide-page>`. Not sure if this is kosher in Ionic land!

http://codepen.io/mattrothenberg/pen/GorOpG

**Comment by GregPK** [comment]
@mattrothenberg Indeed this does fix it. However it lead to problems with headers in my larger app. 

At this time I just added the CSS from the Codepen example to my app, but it's probably something that should be fixed.

**Comment by skmichaelson** [comment]
@GregPK Understood. Good luck, sir!

**Comment by mlynch** [comment]
So, if you want to use the slides as the main content component and have it fill the full height, you should not use `<ion-content>` with it (we are documenting this). Otherwise, set a specific height on it and it'll work.

What issues did you have with the headers?

**Comment by debugerr** [comment]
I run into the same problem. I have 2 headers (ionic-header-bar and bar-subheader). Even if I replace my content container with the ion-slides, it does render over the full height of the scren, but scrolling won't work. Setting autoHeight to true on the swiper does not help. However, if I update the updateAutoHeight with this:

s.updateAutoHeight = function () {
            // Update Height
            if (typeof s.slides.eq(s.activeIndex)[0] !== 'undefined') {
                var newHeight = s.slides.eq(s.activeIndex)[0].scrollHeight;
                if (newHeight) {
                    s.wrapper.css('height', newHeight + 'px');
                    s.container.css('height', newHeight + 'px');
                }
            }
        };

things start to work but I have issues with pagers rendering on top of the content.
