### ISSUE TITLE
Changelog broken

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ionic#4895]
It seems the https://github.com/driftyco/ionic/blob/master/CHANGELOG.md got broken with the most recent commit and release 1.2.4.

**Comment by leschirmeur** [comment]
Got fixed.

**Comment by FLHerne** [comment]
Changelog is broken (still? again?) as of 510b316.

The release notes for 1.2.2 have disappeared completely; "1.2.3" and "1.2.4" are un-named releases with one and zero changes respectively.

**Comment by mlynch** [comment]
We're aware, our change log script has not aged well so we need to fix it
