### ISSUE TITLE
bug: Ionic Nav Bar appears before state change

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic#4896]
Essentially, on slower iOS devices, the status bar is showing up before the actual transition. See attatched GIF. It should be attatched to the state when the previous one uses hide-nav-bar="true". I also used `$ionicNavBarDelegate.showBar(false)` but to no avail.
<img style="width:200px" src="https://cloud.githubusercontent.com/assets/4442130/12085651/2aae382e-b290-11e5-813c-56f042addb83.gif" width="300">

**Comment by ghostgrass** [comment]
+1， same issue on android

**Comment by talamaska** [comment]
I saw this too. I didn't found a solution.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by talamaska** [comment]
@jgw96 Can you confirm it was fixed?

**Comment by talamaska** [comment]
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 8.1
Node Version: v4.2.3

**Comment by jgw96** [comment]
Hello! Unfortunately i am not able to reproduce this issue, can you still reproduce it? Thanks for getting back to me by the way (:

**Comment by talamaska** [comment]
I'm not able to test this right now. All i can tell is that I have one view the login screen which is set like this
```<ion-view view-title="Login" hide-nav-bar="true" >```

**Comment by jgw96** [comment]
@talamaska ok, thanks for the info! If you get a chance and can make a plunker or git repo that i can use to reproduce this issue that would be great! (: Thanks for using Ionic!
