### ISSUE TITLE
feat: add social sharing plugin for ionic view

### ISSUE THREAD

**Issue by muhammdsami1994** [driftyco/ionic#4897]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>i want to upload my app on ionic view to test it on iphone but i am unable to test social sharing, when i search i got it you have not add this plugin, it my advice to please add it.</span>

<span is-issue-template></span>

**Comment by Devniz** [comment]
This plugin allows you to use the native sharing window of your mobile device:
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

**Comment by muhammdsami1994** [comment]
Thank you so much for helping me out

**Comment by mlynch** [comment]
Thanks! Lots more plugins in the works for Ionic View, and this is a View issue so closing.
