### ISSUE TITLE
new issue with .scroll height since 1.1.1

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#4899]
I've just updated from 1.1.1 to 1.2.1 and am seeing a new issue with the height of .scroll div because I'm changing the background color.

In 1.1.1 the height of .scroll div was correct and expanded to accommodate its content.

In 1.2.1 the height of .scroll div is appearing as 100%, so it is too short. This is very visible when changing the background-color! What I don't understand is that looking back at the 1.1.1 release, ionic.css has a rule for

    .overflow-scroll .scroll {
    position: static;
    height: 100%;
    -webkit-transform: translate3d(0, 0, 0); 
    }

so some other change is causing this issue. I've fixed it by overriding:

    .overflow-scroll .scroll {
	height: auto !important;
    }

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
