### ISSUE TITLE
ionic-app-base depends on non-existent ionic-bower version

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic#4902]
(Opening here because [ionic-app-base](https://github.com/driftyco/ionic-app-base)'s readme says to submit issues to the main Ionic repository.)

Creating a new project with e.g. `ionic start my-app` uses `ionic-app-base` as the starting project.
Its [bower.json](https://github.com/driftyco/ionic-app-base/blob/master/bower.json) currently references `driftyco/ionic-bower#1.2.4` in `devDependencies`.
However there's no `1.2.4` tag for the [ionic-bower](https://github.com/driftyco/ionic-bower) repo.

As a result trying to add any bower component to the new project fails with e.g.

    $ ionic add ngCordova
    Failed to find the bower component "ngCordova".

    $ bower install ngCordova --save
    bower ionic#1.2.4         ENORESTARGET No tag found that was able to satisfy 1.2.4

**Comment by perrygovier** [comment]
Should be fixed with https://github.com/driftyco/ionic-bower/releases/tag/v1.2.4
right?

**Comment by mirkonasato** [comment]
Yes that fixes it, thanks!

**Comment by perrygovier** [comment]
Nono, thank you
