### ISSUE TITLE
bug: platform-android writes in iOS Body class 

### ISSUE THREAD

**Issue by alperen** [driftyco/ionic#4906]
my specs:

Cordova CLI: 5.1.1
Ionic Version: 1.2.3
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v5.1.0

----

System writes platform-android as well as platform-ios in --lab mode  iOS Body class. Is this error?

![](https://cloud.githubusercontent.com/assets/3244438/12123159/fa717eb0-b3e7-11e5-8ecb-05eecf354e59.PNG)

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
