### ISSUE TITLE
bug: $ionicHistory.clearHistory() should hide back btn

### ISSUE THREAD

**Issue by sp00m** [driftyco/ionic#4909]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>$ionicHistory.clearHistory() does not hide the back button.

http://plnkr.co/edit/PpCUCzZauTTYNFo1v3o7

1) Use the side menu to go to the "Sign In" page: the back button appears
2) Click the "Clear History" button: the history gets cleared, the back button remains
3) Click the back button: nothing happens since the history has been cleared.

IMO, $ionicHistory.clearHistory() should hide the back button.</span>

<span is-issue-template></span>

**Comment by tpape** [comment]
No news ?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#34
