### ISSUE TITLE
[bug] Lack of IOS icon of 57px and no way to generate it.

### ISSUE THREAD

**Issue by rafaelmezzomo** [driftyco/ionic#4910]
When I try to upload my ionic app to the apple store, I receive an error about lack of app icon of 57px.

I have tried to add a new icon inside `/resources/ios/icon` and add it inside `config.xml`. But when I `ionic build ios` the icon is not added inside `platform/ios`.

To be able to upload I had to manually add the files in Xcode and add them to `my-app-name.plist`.

**Comment by PerfectionCSGO** [comment]
Possibly related to this? https://issues.apache.org/jira/browse/CB-10162

**Comment by rafaelmezzomo** [comment]
Thanks @PerfectionCSGO

**Comment by jgw96** [comment]
Hello, thanks for opening this issue with us! As this issue is related to the cli i will be moving this issue over there. Feel free to please continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#842
