### ISSUE TITLE
feat: Preserve the original coords of a drag gesture

### ISSUE THREAD

**Issue by MartinMa** [driftyco/ionic#4913]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The gesture `ionic.Gestures.gestures.Drag` has `correct_for_drag_min_distance` enabled by default. During `touchmove` when a drag is triggered, the event center is set to drag_min_distance pixels from the original event center. Without this correction, the dragged distance would jumpstart at drag_min_distance pixels instead of at 0.

It might be useful to save the original start point somewhere.</span>

<span is-issue-template></span>

**edit:** I added a small [pull request](https://github.com/driftyco/ionic/pull/4914) as a suggestion to fix this issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#35
