### ISSUE TITLE
bug: $ionicLoading insertBefore of null

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic#4915]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was trying to add a dynamic cancel button on $ionicLoading.
But when I activate the ng-class condition return the 'InsertBefore of null' error and it stack per condition activated.
Still the button appears for cancel.

I've created an code pen with a similar code.

http://codepen.io/anon/pen/LGWmBM

It's working fine, but my fear is that the 'InsertBefore' error keeps stacking and consuming memory, until the app clashes.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
