### ISSUE TITLE
bug: $ionicPlatform.onHardwareBackButton() on Android back button not working

### ISSUE THREAD

**Issue by Mathius17** [driftyco/ionic#4916]
According to the documentation (http://ionicframework.com/docs/api/controller/ionicModal/), the default behaviour is to close the current modal on back button. But it's not closing anything, instead, it performs the action of the main view, go back.

>{boolean=} hardwareBackButtonClose: Whether the modal can be closed using the hardware back button on Android and similar devices. Default: true.

Here is my code when I initialize the modal:
 

    $ionicModal.fromTemplateUrl('app/components/contacts/views/contacts.selectModal.html', {
        scope: $scope,
        animation: 'slide-in-up',
        hardwareBackButtonClose: true
    }).then(function(modal) {
        $scope.contactSelect = modal;
    });

I'm using Android 5.1, Ionic 1.2.1 and 1.2.4 on physical device, not Ionic View

**Comment by Mathius17** [comment]
Apparently it's not detecting any action, if I use `$ionicPlatform.onHardwareBackButton(callback)` nothing happens, neither when I use `$ionicPlatform.on('backbutton', callback)` or `volumedownbutton`

**Comment by mlynch** [comment]
Hmm, just tried it on a default starter (sidemenu) and it worked fine for me. I wonder if there's something else going on?

Are you running this as a cordova app?

**Comment by Mathius17** [comment]
Hmm I tried also in the starter (sidemenu) and didn't work for me. I don't know exactly what you mean by running as Cordova app, I'm running it via  `ionic run android`. 

Tested on a Motorola Moto X 2013 and a Nexus 6P

**Comment by ehynds** [comment]
I'm seeing this as well on Android 5.1.1, Ionic 1.2.4

**Comment by Mathius17** [comment]
Well, now it magically works for me now (not on Ionic View though)

**Comment by GitGump** [comment]
@Mathius17 hi, buddy, I had the same problem on Android 6.0.1, Ionic 1.2.4, How did you solve this? Any clues?

**Comment by GitGump** [comment]
Forgotten to add '$ionicPlatform' dependency is the thing, now it works for me. 

But I got another problem here,  ``` unregisterBackButtonAction() ``` seems cannot remove the action well, when you leave current view and go to any other view, the Action you attached on hardware button is always on!
