### ISSUE TITLE
bug: button-bar not styled correctly

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#4917]
The button-bar component is no longer being styled correctly in the latest version 1.2.4.

See example here:
http://codepen.io/anon/pen/VepBEQ?editors=100

Compare this:
![image](https://cloud.githubusercontent.com/assets/2852839/12152203/f492ebee-b4bb-11e5-8132-6e1726005432.png)

To the documentation:
![image](https://cloud.githubusercontent.com/assets/2852839/12152217/0df907da-b4bc-11e5-8684-16e8c9765dec.png)

**Comment by venu1412** [comment]
+1, We are also facing the same issue. Its introduced newly from 1.2.0.

**Comment by mlynch** [comment]
Fixed, thanks!

**Comment by joeljameswatson** [comment]
I think the underlying issue here may actually be related to the button-style mixin as I'm seeing the same issue on other buttons. Please see this issue 

https://github.com/driftyco/ionic/issues/5576
