### ISSUE TITLE
add divider capability to ion-list

### ISSUE THREAD

**Issue by gslender** [driftyco/ionic#4923]
as per #348 it would be good if this design bug could be sorted or at least a minor change made to ion-list handling of 'item-complex' class to accomodate dividers. please don't simply close this as the original solution doesn't work as per the codepen example shown in issue #348

**Comment by gslender** [comment]
I think this might be a solution http://codepen.io/anon/pen/wMdMqv but would appreciate someone confirming that there is no better approach, and perhaps consider updating the Ionic docs to outline how you'd add dividers when using ion-list

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because we are not planning on adding any new features to Ionic 1 I am going to close this issue for now. Thanks again!
