### ISSUE TITLE
Ionic maxPrefetch config broken

### ISSUE THREAD

**Issue by sinedied** [driftyco/ionic#4927]
I have a gulp build process that package all html templates in `$templateCache` to avoid http requests in production builds.

I have configured the template prefetch to be disabled: 
```js
    // Disable prefetch, as we use $templateCache
    $ionicConfigProvider.templates.maxPrefetch(0);
```

However, when the app starts, it throws 404 errors by trying to get html templates (which are in the template cache).

It appears because my $templateCache templates are set up in a separate run block that is executed after ionic init run block.
The thing is, even considering that it should not try to prefetch the template as I have disabled it... 

I found a workaround by defining my template bundle in a separate angularjs module, but this doesn't change the fact that `maxPrefetch(0)` setting does not work and still try to prefetch templates.

The issue is present in version `1.2.4`.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by sinedied** [comment]
Sorry I can't try for now, I switched to webpack and now all my templates are embedded in the JS code thanks to it, and no more template issues thanks to this.

**Comment by jgw96** [comment]
@sinedied No problem! I will close this for now but if you run into this issue again feel free to comment here and ill happily reopen. Thanks for using Ionic!
