### ISSUE TITLE
$ionicScrollDelegate.getScrollPosition() returns zero for top and left when changing state and then returning

### ISSUE THREAD

**Issue by ggoforth** [driftyco/ionic#4932]
I'm building a scheduling app and am using a calendar plugin to render an agenda day view as one of my states.  Lets call this the `app.calendar` state.  There are arrows in the left and right footer that take you to the next or previous day.  In doing this, a date value on my controller is set to the next or previous day, and the view re-renders itself.  I use the move function below to change the date.  When the view re-renders, I loose my scroll position, so this function effectively moves me back to where I was when I changed the date.

```
    this.move = (days) => {
      let scrollPos = $ionicScrollDelegate.getScrollPosition();
      CalendarConfig.move(days);

      $timeout(() => {
        $ionicScrollDelegate.scrollTo(0, scrollPos.top);
      }, 0);
    };
```

The issue I have, is that if I click on an event, I'm navigated away from `app.calendar` to `app.calendar.detail`.  If I then click the back button, and scroll again, anytime I call the move function again, `getScrollPosition()` top and left is always `0`.  Any ideas why navigating away from a state and then back to it would cause `getScrollPosition()` to always be zero?

**Comment by hanung** [comment]
Hi,

try this,

in html
<ion-content delegate-handle="handler>

in controller
$ionicScrollDelegate.$getByHandle('handler').getScrollPosition()

When the two scrolls is present in one view, $ionicScrollDelegate can not find scroll.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by ggoforth** [comment]
Dang, totally understand, sorry for my delays, shifting priorities at work...I'll be back on this soon and will give this a look.  Thanks @jgw96.

**Comment by maclipi** [comment]
Dont Work
