### ISSUE TITLE
bug: I'm getting Unfortunately Myapp has stopped work..

### ISSUE THREAD

**Issue by abhijitroy07** [driftyco/ionic#4933]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, I am new to Ionic and was following getting started steps. On using $ ionic emulate android it launches and deploys app in the emulator but on opening it gives "unfortunately, myapp has stopped". Please help!</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Sorry, can't help without more info

**Comment by denkomanceski** [comment]
I have the same problem here. I also tried reinstalling the keyboard plugin which in a different issue was mention that it could fix the problem but it didnt. I am on Ionic 2. I tried running with --stacktrace but I cant find any more info

**Comment by armmmo** [comment]
same issue but with paypal plugin...
