### ISSUE TITLE
Ion-tabs tabs on top on iOS ?

### ISSUE THREAD

**Issue by fernandopaiva** [driftyco/ionic#4934]
I have an app that contain ion-tabs on top. It works fine on Android but with iOS the tabs are behind of header.

How could I solve this ?

html: http://pastebin.com/y83g97Mp

iOS simulator image: http://i.imgur.com/crrtJuE.png

**Comment by hanung** [comment]
plz,show more code.

for example, ion-content in html , config in js

**Comment by fernandopaiva** [comment]
@hanung 

http://pastebin.com/sRLVpZQ4

**Comment by hanung** [comment]
maybe.. include 'has-header' class

**Comment by ghenry22** [comment]
or look at the spacing that tabs get at the bottom and create a custom CSS class to give you the same spacing at the top.

I had to adjust my css to add more top spacing on android so that my search inputs didn't disappear behind the top tabs.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
