### ISSUE TITLE
bug: side menu background image syntax error after

### ISSUE THREAD

**Issue by tomachinz** [driftyco/ionic#4935]
Looks to be caused by a spurious  <="" 

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>After exporting from creator.ionic.io firstly into a fresh project, I was trying to incorporate Meteor. 

http://codepen.io/tomachi/pen/obwjYx

13inch:www tom$ meteor
[[[[[ ~/Dropbox/Sites/FoodPrices/www ]]]]]

=> Started proxy.
=> Started MongoDB.
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/angular/angular-animate.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/angular/angular.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/angular/angular.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/angular-ui/angular-ui-router.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/ionic-angular.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/ionic-angular.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/ionic.bundle.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/ionic.bundle.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/lib/ionic/js/ionic.js" as it exceeds the max of "100KB".
=> Errors prevented startup:

   While processing files with angular-templates (for target web.browser):
   templates/settingsMenuUNUSED.html:15: Expected attribute name in tag
   ...) no-repeat center;" <="" ion-content="">...
   ^
   index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

=> Your application has errors. Waiting for file change.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
