### ISSUE TITLE
Socket hangup error while initializing ionic project

### ISSUE THREAD

**Issue by asherdmello** [driftyco/ionic#4936]
i am getting socket hangup error while trying to download master.zip from from github 
when trying the command ' ionic start projectName '
please refer the attached screenshot for the same
i am behind a corporate proxy,
i tried downloading master.zip from the browser and could do so successfully, doesnot seem to be my proxy issue though

![image](https://cloud.githubusercontent.com/assets/16643518/12228493/29f67e64-b862-11e5-821b-1df704b3686c.png)

**Comment by jgw96** [comment]
@nusususuzu are you also behind a proxy?

**Comment by jgw96** [comment]
Since this is more of an issue with the cli and not the framework i am going to be moving this issue to the cli repo, please feel free to continue the conversation over there! Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#854
