### ISSUE TITLE
Badge appear difference from android and ios

### ISSUE THREAD

**Issue by MeisterFiq** [driftyco/ionic#4937]
The badge's appearance on android seems to be overlay with something while in ios its works fine.
Badge on IOS is brighter than android...any clue on this?

![kale](https://cloud.githubusercontent.com/assets/10400905/12228536/e5ff6b4c-b877-11e5-96ba-9fbf664ca481.png)

here is my code : https://codepen.io/anon/pen/YwQwwa

**Comment by karuppiah7890** [comment]
I am having the same issue! Trying to figure out the reason!

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
