### ISSUE TITLE
Slides pagination issue

### ISSUE THREAD

**Issue by LgArcida** [driftyco/ionic#4939]
When a view has multiple sliders they all sync.
There is already a fix for this:
https://github.com/leoruhland/ionic/commit/dca97ff0dd6dac1d0a110afc4b94c8ce994c67d5
Whould be great to have it ASAP

Thanks!

**Comment by andremiguelaa** [comment]
Thumbs up!

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by andremiguelaa** [comment]
I think it's solved:

https://github.com/driftyco/ionic/pull/4839

**Comment by jgw96** [comment]
Awesome, looks like it is solved. Thanks for using Ionic! If anyone still has this issue feel free to comment and i will happily reopen!
