### ISSUE TITLE
bug: Scroll bar moves down to far.

### ISSUE THREAD

**Issue by gfringeli** [driftyco/ionic#4940]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When creating a ion-content element, making it scrollable, and scrolling all the way down, the scroll bar moves down to far. Its rounded end even is cut off at the bottom. Like at the top, there should still be a small gap between the border of the ion-content element and the scroll bar.</span>

<span is-issue-template></span>

**Comment by gfringeli** [comment]
```html
<ion-content scroll="true">
   <h1>Title</h1>
   <p>Some very, very, very long text.</p>
</ion-content>
```
Of course, `scroll="true"` is superfluous, it is only there to avoid misunderstanding.

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
