### ISSUE TITLE
Swiper component doesn't load navigation/pagination in modal

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#4942]
Type: Bug

Platform: All

Swiper doesn't load navigation dots when I add new swiper component in modal. 

Here is the codepen: http://codepen.io/anon/pen/QygxEK

**Comment by szuzul** [comment]
Me and my team solve problem but still it would be nice to put this in the documentation when dealing with new component as an example.

On modal initialisation add:
$ionicModal.fromTemplateUrl( 'modalTemplate.html', function( modal ) {
        that.myModal = modal;
        pagination = angular.element( modal.el.querySelector( '#pagination' ) );
      }, {
        animation: 'slide-in-up',
        scope: $scope
      });

in Swiper options:

 that.swiperOptions = {
      /* Whatever options */
      effect: 'slide',
      initialSlide: 0,
      observer: true,
      observeParents: true,
      paginationElement: 'span',
      paginationHide: false,

      /* Initialize a scope variable with the swiper */
      onInit: function( swiper ) {
        that.swiper = swiper;

        // Save pagination placeholder element from that.eventItemModal
        // to swiper's properties,...
        that.swiper.params.pagination = pagination[ 0 ];
        // ... since paginationContainer is Dom7, we need to add our's pagination element thru add method,...
        that.swiper.paginationContainer.add( pagination[ 0 ] );
        // ...and then run swiper's updatePagination to initiate pagination rendering.
        that.swiper.updatePagination();

        console.log( 'init slider' );
        $scope.showPager = true;
      },

**Comment by jgw96** [comment]
Thanks for opening this issue with us! Also, thanks for the suggestion! As it looks like you found a solution for your issue i will be closing this for now, but if you feel the need to reopen it feel free!
