### ISSUE TITLE
ionic cache mechanism

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#4945]
hi,i know the ionic can cache views to improve performance. And this is using angular-ui-router . However, I look for it docs and not find $stateProvider.state cache parameter. So I want to know that  your team how to realize the cache feature and the mechanism. Any reply would be appreciated!!!

If you have some posts about this that would be perfect

**Comment by freiserg** [comment]
You can find information about cache here
http://ionicframework.com/docs/api/directive/ionNavView/

**Comment by 3dd13** [comment]
if you want to look into code, here is part of the (documented) implementation. just look for cache keyword in the file:
https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/angular/controller/navViewController.js

**Comment by floraluo** [comment]
@freiserg  thanks, but i want to know more is it's mechanism. I may use this cache feature in the future and not use the ionic frame

**Comment by floraluo** [comment]
@3dd13 this file is about angular. 
![image](https://cloud.githubusercontent.com/assets/11729393/12408249/9992b3e0-be99-11e5-8d6f-94125c03db62.png)
I find them using the data function in this file: https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/release/js/ionic.bundle.js.

I have not to  research the 'data' which is a jquery function

**Comment by 3dd13** [comment]
element.data is setting the value of data-xxx attribute

that part of the code is illustrating the cache checking and cache destroy mechanism
you can follow through the code how that attribute affects the view cache retrieval instead of creating new element every time

**Comment by floraluo** [comment]
@3dd13 
As http://api.jquery.com/data/ say, ele.data(key, value) is store data, and ele.data(key) is return the data. So ele.data can't setting the value of HTML5 data-xxx attr, it could retrieval the stored data.
> .data( key, value )
Description: Store arbitrary data associated with the matched elements.

> .data( key )
 Description: Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.

I need to see a few times the source code when I have free time.

Anyhow, thank you very much!

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
