### ISSUE TITLE
Cached views call UI-router resolves on re-enter

### ISSUE THREAD

**Issue by tkem** [driftyco/ionic#4948]
Continuing #3487 which was closed by ionitron for reasons not quite comprehensible.
Still an issue with ionic v1.2.

**Comment by ilyastam** [comment]
+1

**Comment by tkem** [comment]
Well, there've been several workarounds suggested, ranging from the trivial (such as yours) to the rather involved, such as the one by chrfritsch here: https://forum.ionicframework.com/t/state-resolving-and-cached-views-in-beta-14/17870/8

So, thanks, but I guess everyone bugged by this issue has already a bunch of workarounds in use. One of the advantage of resolves is that they allow you to catch error *before* entering the view, which makes for a much improved user experience in some situations, so moving this into the controller is also not an option for me.

If you're not going to change, this, fine, I can understand. Though I question it is *because* of ui-router, since AFAIK the concept and implementation of cached views is special to Ionic.

**Comment by danbucholtz** [comment]
@tkem, I think I may have been mistaken.  I believe this functionality is custom to Ionic.  I will take a look and see what we can do.  There are a few potential obstacles that I can think of.

**Comment by tkem** [comment]
Thanks for looking into this!

**Comment by danbucholtz** [comment]
@tkem, just to keep you posted... I did come up with a way to do this.  Having said that, I don't know if the team will want to go for it or not.  It is modifying UI-router to accomplish it.

We could do it in a cleaner way long term (override $state.go, for example), but navigation is so much better in V2 and will eliminate many of the challenges with UI-router that I am not sure if it's worth it.

I will keep you posted.

**Comment by jgw96** [comment]
agreed that the navigation in Ionic 2 is pretty awesome! @tkem as an aside have you gotten a chance to try Ionic 2 yet?

**Comment by danbucholtz** [comment]
Hi @tkem, the team chose not to make the change to ui-router since there are decent work arounds in place and much better navigation on the horizon with V2.

Thank you for contributing and we really appreciate you using Ionic.  Thanks again for the very detailed responses.

Thanks,
Dan
