### ISSUE TITLE
Ionic 2 device simulator es6-shim.map missing

### ISSUE THREAD

**Issue by alecook** [driftyco/ionic#4952]
Went through steps to create the "cutePuppyPics" starter app via the tutorial. Runs fine on the web but when trying to run on the ios simulator I get the following error (via safari debugging)

```
/Library/Developer/CoreSimulator/Devices/CED171AA-E5B2-4446-A931-8DEF68381866/data/Containers/Bundle/Application/D6FF91C4-1264-4424-B1E2-EDD6E05BC2D3/V2%20Test.app/www/build/js/es6-shim.map

Failed to load resource: The requested URL was not found on this server.
```

System Info:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.7
Gulp local:   Local version undefined
Ionic Version: 2.0.0-alpha.49
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by brandyscarney** [comment]
If you update the CLI to the latest beta version `npm install -g ionic@beta` does this error still happen?

**Comment by alecook** [comment]
@brandyscarney I've updated my CLI to 2.0.0-beta.17

Still getting that error.

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.7
Gulp local:   Local version undefined
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by prateekjain** [comment]
Facing the same error

`Your system information:

Cordova CLI: 4.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 `

**Comment by benshope** [comment]
Same error: 

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 0.4.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-alpha.55
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#754
