### ISSUE TITLE
Where are v2 docs - I'd like to help improve...

### ISSUE THREAD

**Issue by NathanWalker** [driftyco/ionic#4953]
I see a few broken links and I'd like to help improve. Where do these exist?
http://ionicframework.com/docs/v2/api/components/modal/Modal/

**Comment by mhartington** [comment]
Ahh thanks for the reminded. We just moved over v2 to here, so we haven't had a chance to update the site. Will take care of

**Comment by mhartington** [comment]
Fixed via https://github.com/driftyco/ionic/commit/3e5a36a15f1f2f3b27e4228d388bfdb1f69d8a9f but we're still adjusting our build process to generate the new docs. Could be a day or two.

**Comment by NathanWalker** [comment]
Perfect, thanks!
