### ISSUE TITLE
Question: Busy indicator when will be available?

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#4954]
Hi, for the time being i'm using a font awesome refresh icon with spin inside an alert body to show user when my app is busy, this leads to a lot of inconsistency due to the way ionic v2 alert works, the alert needs to be pushed (in this case presented) to the nav component, which takes some time, if the provisional busy indicator needs to close or cancel the opening i need to use timeouts to wait for the alert to finish being presented.

This leads to 2 issues:
1. The user experience suffers as those timeouts makes users think the app works slow.
2. The app becomes inconsistent, as in older devises without a lot of processing power could exceed the time used in the timeouts, this breaks the flow of the alerts if the busy operator didn't even managed to finish being presented before the need to close it.

For the moment i address this issue letting the other alerts stack and knowing how many were instantiated i proceed to pop (close) each alert, this is certainly a whole mess of a workaround about the issue, this should have it's own component or at least some kind of solution like a way to stop the presentation of the alert midway.

When will be ready a busy indicator? i'm facing http request and sql queries that ranges in times of micro seconds to a max of 10 secs (mostly because a timeout i put over the http requests).

**Comment by brandyscarney** [comment]
I'm going to close this as we have it added to our roadmap: https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit?usp=sharing

We don't have dates set but we are going to work on using milestones in Github more to be better about showing what we're working on and which release it will go in. Thank you for the issue though, I added it next to our roadmap to reference.
