### ISSUE TITLE
ionic2 tutorial app, Item Details page, icon is wrong.

### ISSUE THREAD

**Issue by hiroyachiba** [driftyco/ionic#4955]
In item details page of ionic2 tutorial app, the icon is wrong when you visit item details page several times.
If you visit page with basketball, wifi, then flask, the classes accumulate as follows.  
```
<ion-icon role="img" class="ion-ios-basketball ion-ios-wifi ion-ios-flask" aria-label="flask"></ion-icon> 

<div *ngIf="selectedItem" class="selection">
    <b>{{selectedItem.title}}</b>
    <ion-icon name="{{selectedItem.icon}}"></ion-icon>
    <div>
      You navigated here from <b>{{selectedItem.title}}</b>
    </div>
  </div>
```

**Comment by 3dd13** [comment]
did some troubleshooting on ion-icon name input handling, suggested a PR with the fix to clean the CSS classes
