### ISSUE TITLE
perf: Delay(lag) with popover.hide()

### ISSUE THREAD

**Issue by Kopleman** [driftyco/ionic#4957]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The problem exists in all Ionic1 versions. 
I have created  [a pen ](http://codepen.io/anon/pen/RrZJdw) for tests.
Ofcourse the test case is quite ridiculous but its show the problem well.
Popover.hide() call inside clickHandler leads to UI lag.
Just click 'with Check'  fast and look to console output and compare the results with 'withOut Check'.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Im sorry but im a little confused by your codepen, although i really appreciate you providing it! Everything looked fine from what i could see, but im not perfectly sure what im supposed to be looking for. Sorry! What issue should i be looking for exactly?

**Comment by Kopleman** [comment]
Opend dev console, and click as fast as you can on 'withOut Check'. You will notice that '1' appears quite fast in console. Then try 'with Check'.You will see how slower it works. That what i mean by 'UI lag'.

**Comment by jgw96** [comment]
Hello. Sorry for the delay on this! This is actually expected behavior due to our use of a click block. This click block is there to prevent user interaction from firing off multiple animations or events or clicking before an animation is done and causing jank. Thanks for using Ionic!
