### ISSUE TITLE
Alert close with timeout messes fast interactions

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#4960]
I'm currently using the Alert as a busy indicator, this is wrong as the busy indicator has to be poped out manually in order to continue, but if the next alert tries to present itself before the busy indicator has finished being presented it breaks, then i need to use timeouts to wait until last alert has finished being presented and then dismissit and then create the new one.

In pc works well but in mobile this breaks as the performance is lower so the times of the timeouts aren't enough, but increasing the timeouts even more would result in a bad user experience, kind like as the app was working slow.

**Comment by adamdbradley** [comment]
This should be fixed in most recent versions now
