### ISSUE TITLE
bug: pull to refresh icons dont show up

### ISSUE THREAD

**Issue by hatimox** [driftyco/ionic#4962]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>i tryed to add a pull to refresh function to my app using ionic2 , like this : 

```
<ion-refresher (starting)="doStarting()"
                 (refresh)="doRefresh($event, refresher)"
                 (pulling)="doPulling($event, amt)" 
                  pullingIcon="ion-arrow-down-c"
                  refreshingIcon="ion-loop">
  </ion-refresher>
```

but the icons dont show up ?</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
You don't need to add the `ion` in the value and those icons don't exist in 3.0, this is working for me with beta.0:

```
  <ion-refresher
    pullingIcon="arrow-round-down"
    pullingText="release to refresh..."
    refreshingIcon="sync"
    refreshingText="refreshing...">
  </ion-refresher>
```

Take a look at the resources here: http://ionicframework.com/docs/v2/resources/ionicons/

Please let me know if this doesn't fix your problem, thanks!
