### ISSUE TITLE
bug: Angular2 & ionic 2 blank screen Samsung

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#4964]
_From @romanornr on November 14, 2015 6:28_

Type: bug

Platform: android 4.x webview

Recently I noticed that apps written with ionic 2 alpha have some problems.

Samsung devices have problems with opening the app. The app will load & show a blank screen. 
Other devices just showed the app.

Not sure but there seems to be a case that ionic 2 is slightly slower too.

The app failed to load on a Samsung device 
But succeeded to open on a HTC smartphone.

_Copied from original issue: driftyco/ionic2#519_

**Comment by mhartington** [comment]
_From @adamdbradley on November 14, 2015 20:34_

What version of android is it? There are large differences between 4.0, 4.1 - 4.3 and 4.4. Are there any errors? What version of Ionic2 is it?

**Comment by mhartington** [comment]
_From @kbytesys on November 17, 2015 14:34_

I've got same error with android 4.0 devices.

Same app with 5.x android works fine.

**Comment by mhartington** [comment]
_From @adamdbradley on November 17, 2015 14:49_

What's the error?

**Comment by mhartington** [comment]
_From @kbytesys on November 17, 2015 15:6_

This is the android log output.

[android.txt](https://github.com/driftyco/ionic2/files/36803/android.txt)

**Comment by mhartington** [comment]
Hmm, the log does't tell a whole lot. This sounds pretty similar to https://github.com/driftyco/ionic2/issues/794 which was fixed a few days ago. Mind giving it a shot with alpha48

**Comment by mhartington** [comment]
_From @kbytesys on January 11, 2016 2:39_

Nope. How I could give you more debug info?

**Comment by mhartington** [comment]
@kbytesys is this still broken with the latest alpha49?

**Comment by kbytesys** [comment]
Nope, but this is the result of the adb logat | grep -i webview

https://gist.github.com/kbytesys/3c4ce3b8327d0d471e45

**Comment by mhartington** [comment]
Hmm, this does tell a whole lot. This could be a polyfil missing, but it's not clear what the issue is. Though a safe bet would be to use crosswalk, given that the version of android is rather old. 

I will note that we have dropped support for android 4.0.

**Comment by kbytesys** [comment]
Yep, the app works fine with crosswalk.

Btw my testing phone atm is a S3mini with Android 4.1.2.
If you want to drop the support for that phone is fine. 
Please just add some doc to suggest to try crosswalk or something.

**Comment by josipkolic** [comment]
I have the same problem trying to run ionic-preview-app with ionic 2 beta version. I am getting blank screen also. I tried on Samsung s3 neo (android 4.4.2) and samsung galaxy A3 (android 5.0.2). In browser console I am getting error  Failed to load resource: net::ERR_FILE_NOT_FOUND file:///android_asset/www/build/js/app.bundle.js. Any suggestions are welcomed for solving this problem

**Comment by mhartington** [comment]
@josipkolic what version of the CLI do you have? 

```
ionic -v
```

It should be beta17
This could be from the CLI not building and bundling everything before building.

**Comment by josipkolic** [comment]
sorry @mhartington for late response, it was my mistake, i installed wrong the new beta version(it's beta 17 yes). I reinstalled ionic again and it works perfectly on android 5.0 devices, on 4.4.2 there are some problems with click events but that is other issue.

**Comment by brandyscarney** [comment]
Closing this as it doesn't seem to be an issue anymore. Please let me know if otherwise.

**Comment by aneudysamparo** [comment]
For me it's not working yet! I have ionic 2.0.0@Beta.20

**Comment by jgw96** [comment]
@aneudysamparo hey! So the latest release of Ionic 2 is Ionic 2.0.0 beta.4. If you run ionic info your ionic framework version is the actual version of Ionic you are using. It sounds like what you posted is your ionic-cli version. Also, what version of Android are you having the issue with?

**Comment by aneudysamparo** [comment]
Hi @jgw96 
I'm using 4.1.2 Android, Galaxy S3 of T-Mobile.
Yes, i posted ionic-cli (my bad). 
I could able make it runs, updating cordova version of the project to cordova 5.1.1.
After i build the apk, it gave me two different file 
amrv7-debug.apk
x86-debug.apk

Even though both of them are working fine now!
Also i update crosswalk .

I hope it helps!

PS: Run those commands on the project's folder.
`ionic plugin add cordova-plugin-crosswalk-webview`
`cordova platform update android`

**Comment by jgw96** [comment]
No problem! (: Sorry if im confused but is it working for you now with crosswalk? We do not support Android 4.1.2 as its really hard to support those older android webviews and still have good performance but with crosswalk it should work. Thanks again!

**Comment by aneudysamparo** [comment]
Yes, it's working fine now! 
I know and i was thinking about this. But let me tell you, the performance on now is good and I think is more faster than ionic 1. Also all the feature of Material Design are working. 

Thanks btw! (:

**Comment by jgw96** [comment]
Awesome, glad to hear! No problem at all!

**Comment by GaneshPediredla** [comment]
Can anyone please help me to build an apk file using ionic2?

**Comment by kolyaflash** [comment]
Running the default app. Device: S3 mini, Android 4.1.2.

```
$ ionic -v
2.0.0-beta.25

$ ionic plugins
...
cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
```

Chrome's inspector: no errors. 
But the white screen is still there.

**Comment by aneudysamparo** [comment]
@kolyaflash Try to update cordova

**Comment by aneudysamparo** [comment]
@GaneshPediredla For me
`ionic build android` is working fine.

**Comment by sachittandukar** [comment]
I am also getting white screen issue on both android 6 (Motorola) and Windows 10.
Here's what ionic info gives:
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.11.0

**Comment by aneudysamparo** [comment]
@sachittandukar Hey try those!
Update your ionic!
`npm install -g ionic`

Add this plugin
`ionic plugin add cordova-plugin-crosswalk-webview`
and then update this on your project's file.
`cordova platform update android`

**Comment by iignatov** [comment]
@sachittandukar I would recommend you to [update your project to `beta.6`](https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-6/50049) _(following the steps in the linked guide)_ because there are some important bug fixes and I guess that the problem will be solved.

**Comment by sachittandukar** [comment]
@iignatov thanks! I have been using nightly version to fix my initial issues. I will try new beta version.

**Comment by GaneshPediredla** [comment]
@sachittandukar I updated my ionic and cordova. But still in my machine when i tried to run a sample app using ionic serve. Its giving errors. My OS is Linux Fedora. Is there any possible way to run the ionic app in Linux without any errors. Its working fine in RootUser but in local It's not working...

**Comment by iignatov** [comment]
@GaneshPediredla Could you [open a new issue](https://github.com/driftyco/ionic/issues/new) and post some details there, e.g. run `ionic info` and copy&paste the output, error messages, stacktraces, etc?

**Comment by bmnepali** [comment]
I am having the same issue with a project with 
```
Ionic 2.0.0-beta.33
Cordova 6.6.1
```
And trying @aneudysamparo solved the problem for me i.e
```
1. ionic plugin add cordova-plugin-crosswalk-webview
2. cordova platform update android
```
Now all is working fine!

**Comment by AnSharipov** [comment]
Hello, guys
I updated ionic:
`2.0.0-beta.36`
Updated cordova
Installed crosswalk plugin:
```
C:\Users\Andrey\SuperTruck> ionic plugins
cordova-plugin-crosswalk-webview 1.8.0 "Crosswalk WebView Engine"
```
did `cordova platform update android`

but still get blank screen on the Samsunsg s6/Android 6.0.1 and Fly/Android 4.4.2
Windows 10

file:///android_asset/www/build/js/app.bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by sagarkulkarni3592** [comment]
@AnSharipov Did you find the solution for this?
This error is not consistent for me. Sometimes I get it, sometimes I don't.
Also, I do not think it is related the crosswalk plugin. But, if it is then correct me.

**Comment by mhartington** [comment]
Hi there. Please check your build to make sure things are building correctly. 
Also update to the latest ionic 2 release and latest app-scripts.
Locking this issue since it is an old issue and the original cause has been resolved.
