### ISSUE TITLE
Wrong title bar size

### ISSUE THREAD

**Issue by 5im0n** [driftyco/ionic#4966]
When you customize the SASS variables: `$bar-footer-height`, `$bar-subheader-height`, `$bar-subfooter-height`. If you set a title inside subheader, footer, and subfooter bar:

```html
      <ion-header-bar class="bar-stable">
        <h1 class="title">Header</h1>
      </ion-header-bar>

      <ion-header-bar class="bar-subheader bar-energized">
        <h1 class="title">SubHeader</h1>
      </ion-header-bar>

      <ion-footer-bar class="bar-stable">
        <h1 class="title">Footer</h1>
      </ion-footer-bar>

      <ion-footer-bar class="bar-energized bar-subfooter">
        <h1 class="title">SubFooter</h1>
      </ion-footer-bar>
```
The title have a wrong height!

ScreenShot to illustrate the problem:
![capture](https://cloud.githubusercontent.com/assets/659811/12334443/54e99774-bafa-11e5-949f-0321f821d98c.PNG)

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by 5im0n** [comment]
Of course, my pull request #4965 have not been merged yet

**Comment by danbucholtz** [comment]
Hi @5im0n,

Let's work off of your PR going forward.  Sound good?

Let me know if you want me to re-open.  I plan to test and hopefully merge it this week.

Thanks,
Dan
