### ISSUE TITLE
feat: How can install in 10 pc but download in 1 pc?

### ISSUE THREAD

**Issue by wespert** [driftyco/ionic#4972]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Dear sir,

I am running a institute and more than 50 students want to learn Ionic Framework from my academy, but the problem is downloading packages.

I need download all things 50 times means repeat process every time for each computers in windows os. So if you have any short option than please mail me at imsandeeptiwari@gmail.com.

I also want to know that How can I generate binary files of apps directly from my desktop, because we have limited internet access in some pcs.

Thanks you,

Sandeep Tiwari,</span>

<span is-issue-template></span>

**Comment by simplesmiler** [comment]
@wespert if all computers are running the same exact (or very similar) environment then you can `npm install -g ionic` on one computer and copy all the installed files and folders to all other computers. This will give you the CLI up and running. You can probably do the same with `ionic start`'ed project folders (after you fetch all the dependencies with `npm install` and `bower install`).

You can also try to setup something like [npm-lazy-mirror](https://www.npmjs.com/package/npm-lazy-mirror) on a local server.

---

Files and folders you need for CLI (Windows):
- `%APPDATA%/npm/ionic`
- `%APPDATA%/npm/ionic.cmd`
- `%APPDATA%/npm/node_modules/ionic`

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Awesome to hear your helping teach Ionic! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
