### ISSUE TITLE
bug: update to ionic 1.2.4 leads to broken CSS with fixed/absolute 'position' and 'bottom' positioning

### ISSUE THREAD

**Issue by VinceOPS** [driftyco/ionic#4974]
Hi Ionic Team,

I recently updated from 1.2.1 to 1.2.4 and saw few of my views totally broken:
In some cases, according to User's resolution, the content is sticked to the bottom of the view, using CSS `position: absolute` and `bottom: 5%` (*5% for the sake of the example*).

It was working as expected with Ionic 1.2.1 but doesn't with 1.2.4. Please see the following **codepen**:
http://codepen.io/anon/pen/wMrMqE
The main content (buttons "Scientific Facts" and "FORM", from [this initial codepen](http://codepen.io/ionic/pen/VLwLOG)) is **not visible** anymore. But if you scroll down (by dragging the page), you will see it appear. That is *exactly* what happens now in my project.

I saw some `overscroll` changes in the ionic CSS and tried to play a bit with the values but couldn't change anything.

On few of my pages, scrolling was not required, so I used `ion-pane` and it "fixed" the issue. But on some other views (using responsiveness), I must be able to scroll.

Please let me know if I can be of any help.

**UPDATE** - It seems like setting `overflow-scroll` to `true` in `ion-content` solves the issue.

**Comment by gregor-srdic** [comment]
I also encountered this issue, thank you for your suggestion!

**Comment by VinceOPS** [comment]
You're welcome! If you talk about enabling `overflow-scroll` regarding my suggestion, I advise you to make sure it fits your requirements [here](http://ionicframework.com/docs/api/directive/ionContent/).

**Comment by mlynch** [comment]
Thanks, tracking for next release

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
