### ISSUE TITLE
Multiple root app (not tabs nor menu!)

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#4975]
I couldn't find the guide on how to go about the app with multiple roots. Not the "top-level" pages discussed [here](http://ionicframework.com/docs/v2/components/#menus), but true roots, set conditionally inside `@App` controller as `this.rootPage`.

I came up with following construct and would like to know is it correct or not.
`this.app.getComponent('root').setRoot(MyPage);`
where `this.app` is an instance of `IonicApp`.

Here are few details about my app structure. I have three root pages: LoginPage, UserRoleAPage and UserRoleBPage. Each user page is page with tabs.
First, on app bootstrap, I check for the session and set `this.rootPage` to either LoginPage or a user page depending on the user role. From LoginPage I use `this.app.getComponent('root').setRoot(UserRole_Page);` when user logs in, and from UserRole*Page I use `this.app.getComponent('root').setRoot(LoginPage);` when user logs out.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
