### ISSUE TITLE
Bug@ionic 2: alert generates z-index error on navigation to page

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#4976]
I'm showing an alert when i go into a nested page, that alert breaks navigation, sometimes it is presented bad and the z-index of the alert is lower than the page, thus not showing, and if clicked in the back button while the alert is still opened it breaks the navigation, just closes the alert and set the page index 1 lower respect the parent page, thus displaying something like:
![z-index-error](https://cloud.githubusercontent.com/assets/9698639/12355290/a209422e-bb69-11e5-86d7-8fb7af648c96.png)

**Comment by adamdbradley** [comment]
Yes I'm addressing these issues. Are you changing pages before animations have completed?

**Comment by Luchillo** [comment]
I'm playing with timeouts to try and fix this, i have basically this flow:
1. show alert 1 busy indicator after 200 ms for the animation of the root page.
2. close alert 1 and show the user the root page
3. upon click in one of the subpages push the component you see in the image
4. upon entering the child page, i show another alert 1
5. Heres where it breaks, i make some process and then trigger a timeout that should close the child page alert 1, doesn't matter if the alert 1 gives the page 1-2 sec before appearing, the close function just triggers 200 ms after, and inside the function it has another timeout with 200 extra ms.

Extra info: i use the same function in root and child page for showing alert 1 after timeout of 200ms, timeout the close after 200ms extra to give time to alert 1 animations, and the close function calls dismiss 200 ms after, in total it is a process of at least 600ms or more.

**Comment by Luchillo** [comment]
New intel:
Watching the z-index of the 2 components and the alert, component 1 gets z-index 10.
Comp 2 gets z-index 11, for some reason the presented alert gets z-index 10 and after the close the comp 2 gets z-index 9.

I think the issue is here in the z-index function: https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/nav-controller.ts#L1089-L1109

I think there's an error when presenting the alert that does the alert get z-index 10 instead of 12, maybe the nav is setting wrong the direction for the present when in child component.

**Comment by Luchillo** [comment]
Ok it seems i have to put a 400 ms timeout in the child page constructor for it to work, is it because of the time it takes to transition?

**Comment by Luchillo** [comment]
With no other option i will have to make a custom loading/busy indicator that doesn't rely on the nav component.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by adamdbradley** [comment]
This appears to have been fixed since this issue was created. If you're still have problems please create another issue, thanks

**Comment by Luchillo** [comment]
Fixed? more like worked around with the lifecycle hook for `onPageDidEnter() {}`, still at least is a solution.

**Comment by danbucholtz** [comment]
Hi @Luchillo,

Are you using promises and chaining the transitions together?

Thanks,
Dan

**Comment by Luchillo** [comment]
Yes i do, that seems to be the way the alerts are intended to work, the only issue left was i had to time up the code in constructor or either it will break as stated above, that's where the `hooks` come along.

**Comment by jgw96** [comment]
Yep, ill happily explain why this happens. The constructor of a class actually fires before anything in the dom has happened, so then when the alert tries to do dom related stuff before the dom is ready it will give errors. Putting it in a timeout will technically work, but timeouts are very inefficient and inconsistent way to handle async stuff in javascript. This is why we have lifecycle hooks and use promises throughout ionic 2. Hope this explains everything! (:

**Comment by jgw96** [comment]
Actually here is a good video explaining this a little better than i can: https://www.youtube.com/watch?v=MYympIG00Pk

**Comment by Luchillo** [comment]
@jgw96 Wow the recent beta.7 made a big breaking change for me, i was using the `IonicApp.getComponent()` method to get the navigation from a service (Injectable), Now will i be able to do the same with `@angular/core -> ViewChild` from an Injectable?

**Comment by Luchillo** [comment]
Ok forget it, i found how to do it, just using the `IonicApp.getActiveNav()` did the trick in my service.
