### ISSUE TITLE
broken click/tap in upgrage to 1.2.4 on iOS

### ISSUE THREAD

**Issue by brunyan** [driftyco/ionic#4977]
I'm using ionic with C3 charts, and when I update ionic to 1.2.4, it doesn't show C3 popup when I click in chart dots.

Working example with 1.2.1
http://codepen.io/anon/pen/QyqKpz

Not working whith 1.2.4
http://codepen.io/anon/pen/QyqNXp

If I change the 'jsScrolling' to 'false', it' just work fine!

**Comment by VinceOPS** [comment]
Hi,

I wonder if it could be related to an issue I also had with 1.2.4 regarding scrolling:
https://github.com/driftyco/ionic/issues/4974

Enabling `overflow-scroll` (instead of ionic scrolling) in ion-content "resolved" my issue.

**Comment by mlynch** [comment]
@brunyan can you add `data-tap-disabled="true"` to the main container of the c3 chart? This will skip Ionic's tapping.

**Comment by brunyan** [comment]
That will do.

Thank's
