### ISSUE TITLE
native scroll (side menu) becomes frozen after using modal

### ISSUE THREAD

**Issue by jovankrunic** [driftyco/ionic#4978]
**Type:** bug

**Platform:** android 5.1.1 (webview 39.0.0.0)

Hi Ionic Team,

This issue can be reproduced using `ionic start myApp sidemenu`, then adding some more menu items and turning on native scrolling with `$ionicConfigProvider.scrolling.jsScrolling(false)`.

I prepared this demo app already, so this can be used instead of commands above: https://github.com/jovankrunic/ionic-scroll-issue.

Situation:
1. Open modal window (in this demo, ‘Login’ menu item opens one)
2. Change orientation of the mobile device while modal window is still opened (from horizontal to vertical or vice versa)
3. Close modal window

After this, if side menu is opened, it is not possible to scroll through the its items (at the same time non-functional scroll bar is present next to the side menu items). If device's orientation is changed again, scrolling of side menu works again.

The issue also occurred (and was noticed) if app's appearance was changed using modal window (css, menu items etc.) when screen orientation wasn't altered at all. I believe this is the same issue as the one above.

Thanks!

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
