### ISSUE TITLE
bug: ion-infinite-scroll stops working when scroll page quickly

### ISSUE THREAD

**Issue by freiserg** [driftyco/ionic#4980]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>
if the user scrolls page quickly, this error `$digest already in progress` in ionic 1.2.4

How I understood this problem in this code:

`$scope.$parent && $scope.$parent.$apply($attrs.onInfinite || '');`
https://github.com/driftyco/ionic/blob/master/js/angular/controller/infiniteScrollController.js#L38 

I will use $applyAsync instead $apply.
</span>

<span is-issue-template></span>

**Comment by lukemiles** [comment]
+1. This bug was 'fixed' somehow with native scrolling (so it wasn't in previous releases) and now it's back due to the switch to JS scrolling again.

**Comment by Swamii** [comment]
Wrapping the infinite-scroll complete event in $timeout seems to fix it for me. Not sure if it always works, might be a timing issue.

```js
$timeout(function() {
    $scope.$broadcast('scroll.infiniteScrollComplete');
});
```

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of Ionic 1?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
