### ISSUE TITLE
Bug@ionic 2: Sass globbing not working/supported

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#4981]
I'm using a globbing pattern `@import 'components/**/*'` but the sass transpiler doesn't understand it, it should be supported, any reason it isn't?

**Comment by adamdbradley** [comment]
Sorry, but this isn't an ionic issue. Also, I believe it's not supported because the order of the files would be alphabetically, whereas the app will need an exact order of how the CSS stacks up.

**Comment by Luchillo** [comment]
Well, yeah, most of the ionic scss needs some kind of order, but in app components almost nowhere you will see scss that need's to be before another, mostly because in the generators you namespace with a css class with the hyphen-based name of the component, say the `list` component has a class `.list`.

Thanks to that the scss in the app folder doesn't need order, unless user drop this convention.

**Comment by mlynch** [comment]
@Luchillo the point was more that sass does not have this feature baked in because of that problem, so we won't support it either. (There are some extensions that do enable it but I don't think it's worth the effort)

**Comment by Luchillo** [comment]
Got it, thanks.
