### ISSUE TITLE
ionic2 ion-scroll not work 

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic#4985]
http://ionicframework.com/docs/v2/api/components/scroll/Scroll/

not work at this example

**Comment by marcioibm** [comment]
Change scroll-y="true" to scrollY="true"

**Comment by brandyscarney** [comment]
Closing - this is working now, thanks!

**Comment by GaneshPediredla** [comment]
I have problem with ionic2 scrolling. After installing the app in android mobile and clicking on a text filed the page is scrolling and after clicking back in mobile keyboard is closing but page is not reset to its original position. How to do that in ionic2???
