### ISSUE TITLE
Including third party libraries (like lodash) for Ionic 2 using TypeScript setup

### ISSUE THREAD

**Issue by NathanWalker** [driftyco/ionic#4986]
I'm curious how to include third party libraries like lodash using the TypeScript setup. I see it's included as a dependency in `package.json` but I can't seem to use it...
I tried:
```
var _ = require('lodash');
```
in a component file but of course that gets a `Cannot resolve module...`

With SystemJS, I'd need something like this:
```
System.config({
  "map": {
    "lodash": "npm:lodash@3.8.0"
  }
});
```
But with the webpack setup, I'm not entirely sure.
This would apply to numerous other third party libraries that users may want to use. What's the best way forward on this?

**Comment by mhartington** [comment]
So there's a few ways you could do this.

```
import {Page} from 'ionic-framework/ionic';
import * as _ from 'lodash';

@Page({
  templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
  constructor(
    ) {
    let myArray = [1,2,3,4]
    console.log(_.chunk(myArray, 2));
  }
}
```

This will import everything from lodash and make it available under the `_` variable, something similar to 

```
var _ = require('lodash');
````

Or you could do 

```
import {Page} from 'ionic-framework/ionic';
import {chunk} from 'lodash';

@Page({
  templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
  constructor(
    ) {
     let myArray = [1,2,3,4]
    console.log(chunk(myArray, 2));
  }
}
```
And import each method needed. This would be the preferred way as when try shaking lands in webpack, you'll only get the chunk method, not the whole lodash package.

**Comment by NathanWalker** [comment]
@mhartington Thanks for response, unfortunately when running `ionic serve` when trying any of the above I still get this:
```
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-framework/fonts/**/*.ttf

∆ Copying HTML
√ Matching patterns: app/**/*.html

√ Fonts copied to www/build/fonts
Unhandled rejection Error: Cannot resolve module 'lodash'
```

I assume something else in webpack.config still needs something?

**Comment by mhartington** [comment]
Could you provide the steps you too to get this?

**Comment by NathanWalker** [comment]
Since `lodash` is already installed as a `dependency`, I simply tried all your suggestions:
A.
```
import * as _ from 'lodash';
```
B.
```
import {chunk} from 'lodash';
```
...into any component and A and B both create the error. 
I'm thinking `webpack.config` needs to be modified somehow.

**Comment by mhartington** [comment]
It shouldn't, it will automatically pull deps from node_modules. 

Please post the steps to reproduce.

**Comment by NathanWalker** [comment]
@mhartington so sorry for the trouble. Turned out to be a strange permissions mishap on the node_modules folder in the local directory. Thanks again for the information above, was exactly what I needed to know :+1:

**Comment by beachygreg** [comment]
Has this changed? I tried the steps above and no go.

**Comment by mhartington** [comment]
This shouldn't have changed. Has the module been installed correctly and is it working? Make sure any non-typescript libraries have their definitions. 

http://mhartington.io/post/ionic2-external-libraries/

**Comment by beachygreg** [comment]
@mhartington Followed the tutorial and it worked like a charm! Thanks a bunch I owe you one!

**Comment by jesperbruunhansen** [comment]
Hi @mhartington 
Is your guide at http://mhartington.io/post/ionic2-external-libraries/ still the correct way to do it?

I've been struggling with importing an external module from npm (and followed your guide), but typescript cannot find the module :(

In short, this is what I have done

1. Created new project with `ionic start my-project tutorial --v2 --ts``
2. `npm install backbone --save`
3. `npm install -g typings` 
4. `typings install backbone --ambient --save`
5. In app/app.ts `import {Backbone} from 'backbone'``

Gets this error: `"Error:(5, 29) TS2304: Cannot find name 'Backbone'."`

Any help?

**Comment by jlsuarezs** [comment]
Did you get it @jesperbruunhansen? Thank you.

**Comment by keithdmoore** [comment]
I got the same error except with `lodash`.  I added this: `/// <reference path="../typings/modules/lodash/index.d.ts" />` to the top of `app.ts` and the error went away.

**Comment by seand88** [comment]
@mhartington  same issue, blog is out of date, used same fix keith did to get it working. Mine also says that the --ambient tag is now depreciated....

**Comment by dimpu** [comment]
Finally able to fix the issue. The problem is with tsify and typings.

1) Update tsify version to 0.16.0 in node_modules/ionic-gulp-browserify-typescript/package.json
2) change from main.d.ts. to index.d.ts in node_modules/ionic-gulp-browserify-typescript/index.js
3)  Remove typings folder from your project and Update your typings.json 

```javascript
{
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "lodash": "registry:dt/lodash#3.10.0+20160619033623"
  }
}
```
4) Finally 

```shell
npm i
typings install
````

That's it. I should work fine. 

Following are my configurations.

OS: windows 10,
node: v4.4.5
npm: v3.9.5
ionic: 2.0.0-beta.32
typings: 1.3.0

I have created a new PR request to fix this issue @ https://github.com/driftyco/ionic-gulp-tasks/pull/37

**Comment by ToothpickFactory** [comment]
This is what I did to get lodash working without errors.

npm install lodash --save
npm install -g typings
typings install lodash  --save // I left off --ambient. This made lodash a dependency
import {sum} from 'lodash' // In what ever file you want to use lodash

**Comment by gxsjtu** [comment]
why remove js version when use ionic start, typescript makes use npm packages so trouble

**Comment by alexmgrant** [comment]
Is there a way to do this globally for the entire project?

**Comment by sameera207** [comment]
If you having problems for `Ionic 2 RC0` (just like me), I this to be working 

1 ) `npm install @types/lodash --save-dev --save-exact`
2 ) import _ from 'lodash';

Originally posted on [SO](http://stackoverflow.com/questions/33406589/how-do-i-use-lodash-with-ionic-2) by [Shamsher](http://stackoverflow.com/users/1041618/shamsher)

**Comment by klemensz** [comment]
Hi, I have the following problem with importing video.js in Ionic 2 RC0. https://www.npmjs.com/package/video.js 
1 ) `npm install --save video.js`
2 ) `npm install @types/videojs --save-dev --save-exact`
3 ) In the TS file: `import videojs from 'video.js`;

But it gives me the error: "error TS2307: Cannot find module 'video.js'."

**Comment by jmordica** [comment]
I'm having the same issue with jquery.

1. npm install @types/jquery --save-dev --save-exact
1. `import * as $ from 'jquery';`

Output:
bundle dev failed:  Could not resolve 'jquery' from....

**Comment by DmitrySkripkin** [comment]
@jmordica `import $ from 'jquery';` works.
P.S. I feel myself like monkey coder when use ionic2/ts/angular2. Docs are not very helpful.

**Comment by rastographics** [comment]
using ionic rc1, trying to get lodash to work. 

when importing lodash like this:
```javascript
import endsWith from 'lodash/endsWith';
```
there are no ts compile errors, and `ionic build` works with no errors.

but `ionic serve` gives me error

```javascript
cannot find module 'lodash/endsWith'
 ```


also tried importing like this:
```javascript
import * as _ from 'lodash';
```

but then I get error in BOTH `ionic build` and `ionic serve`
```javascript
rollup: Export 'endsWith' is not defined by (file trying to import lodash)
```

**Comment by aarjithn** [comment]
I'm trying to use `jquery-param` npm module in ionic 2 RC1 .

installed via `npm install jquery-param --save`

`import * as param from 'jquery-param';` is showing ts error `[ts] Cannot find module 'jquery-param'.`

**Comment by xiongemi** [comment]
since typings is not no longer used. how do we add 3rd-party library to ionic?

**Comment by mhartington** [comment]
http://ionicframework.com/docs/v2/resources/third-party-libs/

**Comment by larryaubstore** [comment]
The method from http://ionicframework.com/docs/v2/resources/third-party-libs/ does not seem to work.

I tried this:
npm install underscore --save-dev
import * as _ from "underscore"

I got the following error:
_$1.bind is not a function

**Comment by jmordica** [comment]
@larryaubstore you are correct. It does not.

Still looking for a more consistent approach.. It works for a select few modules widely used but not for others.

**Comment by cperez1087** [comment]
I just updated to RC0 (i will update to RC2 right after) and I am getting the same problems with LinqSharp.
Cannot find module 'linqsharp'.

Any solutions yet?

**Comment by marticrespi** [comment]
I have a similar issue. 

I have installed:

`npm install material-design-lite`

And I want to link a `<script>` in my `index.html` but when I execute `ionic serve` I get a 404 Not found, and the route is ok, If I click on it open this js properly. I am using RC3.

I think it can not read when is executed and try reading from www folder.

**Comment by Coder-Ashish** [comment]
can we use wifimanager in ionic 2+ angular 2

**Comment by mhartington** [comment]
Locking this issue. As this is not a specific issue regarding ionic, but a general question regarding typescript.
