### ISSUE TITLE
bug: ShowPager and new ion-slides

### ISSUE THREAD

**Issue by chooseapp** [driftyco/ionic#4987]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Maybe it is me, but with the new ion-slides, it is impossible to change the showPager Boolean.

I tried a lot of things, and nothing worked.</span>

<span is-issue-template></span>

**Comment by privetr** [comment]
Same problem here. I removed the condition ng-if="!showPager" in source code to avoid that pagination bullets are hidden when there are more than 10 slides.

**Comment by masimakopoulos** [comment]
Yeap same issue. showPager should be exposed in the directive API so that is can be manipulated externally.

```
scope: {
     options: '=',
     slider: '='
   },
   template: '<div class="swiper-container">' +
     '<div class="swiper-wrapper" ng-transclude>' +
     '</div>' +
       '<div ng-hide="!showPager" class="swiper-pagination"></div>' +
     '</div>',

```

**Comment by mjangelini** [comment]
@chooseapp @privetr @masimakopoulos I found a solution that worked for me was this: 
`$scope.options = {
      loop: false,
      initialSlide: 1,
      pagination: false
    };`

Although the documentation for ion-slides is horrid and doesn't reveal anything at all.  I just kind of guessed to see if it would work based on the Swiper API.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by maxehnert** [comment]
Can we open this up again? It still seems to be an existing bug that I am currently experiencing.

**Comment by twinssbc** [comment]
@maxehnert You can use $scope.options = { pagination: false }; in the pre-link hook function.
