### ISSUE TITLE
Ionic 1.2.4 Bug?: $ionicScrollDelegate.getScrollView().onScroll no longer working on android

### ISSUE THREAD

**Issue by Corvi2** [driftyco/ionic#4989]
Hello,
with this update my elastic header stopped working on android devices. Still works in desktop browsers, though.

I use this code:
``` 
myapp.directive('elasticHeader', function($ionicScrollDelegate) {
    return {
        restrict: 'A',
        link: function(scope, element, attr) {
             var scroller = $ionicScrollDelegate.$getByHandle(attr.scrollHandle);
             scroller.getScrollView().onScroll = function() { 
                 //do something
``` 

That onscroll function is not documented. I'm not sure why, because it worked just fine until this update. I found it in the ionic forum. Was it removed on purpose or is it a bug? Any advice how to change this code so that it works again? Thanks.

**Comment by Corvi2** [comment]
I can get it back to work, when I use addEventListener('scroll', ...) instead, but the performance is a lot worse. Would love to see onScroll work again in a future ionic version.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! What version of ionic are you using? Also, what version of Ionic are you testing with?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
