### ISSUE TITLE
BUG：ionic 1.2.1 ---ng-repeat doesn't work when callback from native plugin

### ISSUE THREAD

**Issue by niyaou** [driftyco/ionic#4994]
hi,sorry for my bad English,
this is the html code:
\<div ng-repeat="one in data" ng-show="totalToggle">
        \<ion-slide-box on-slide-changed="slideHasChanged($index)" auto-play="false"
                       does-continue="false" show-pager="false" pager-click=""
                       active-slide="model.activeIndex" delegate-handle="delegateHandler" class="inner_image_5" style="height:{{one.height}}">
        

js code : 
 ToNativeBridge.sendDataToNative(dataList, function (jsons) {
$scope.apply(function(){
$scope.data=eval("(+jsons+")");
});

It is a native plug-in for obtaining data via native methods, and it will perform the callback once the date obtained. However, currently it could be used in andriod system, but not IOS system.

I will highly appreciate your efforts and timely reply. Many thanks!

**Comment by mlynch** [comment]
@niyaou try adding a level of indirection to $scope.data, like:

```javascript
$scope.data = {}

ng-repeat="one in data.items"

Then update it like

$scope.data.items = 
```
