### ISSUE TITLE
ionic history back is not working properly

### ISSUE THREAD

**Issue by vaidyanathanas** [driftyco/ionic#4997]
ionic history back is not working properly in android for more than 2 views. i request you to build this example in android http://codepen.io/calendee/pen/pGrxl and test. after going to two nested views. please check back button. it is not redirecting back properly. example is someones i copied the link.

**Comment by pierrybos** [comment]
https://github.com/driftyco/ionic/issues/2725

**Comment by vaidyanathanas** [comment]
animation is not problem. problem is  for ex: going to  view1-> view2->view-3.  when i click backbutton from view3 it goes to view2.  click backbutton again it is going to view3 not view1. ionichistory stack is working mobile android. in web it is working. currently i am using history.go(-1); navigation.app.back(); but it is flickering due to two function using for one back navigation. if i use one function it will not work properly.

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
