### ISSUE TITLE
Button Bar border color transparent

### ISSUE THREAD

**Issue by tomcraft2xlc** [driftyco/ionic#4998]
In the ionic.css version 1.2.4 the button bar  border-color for all the style is transparent.

.bar-stable .button {
  border-color: transparent;
  background-color: #f8f8f8;
  color: #444; }

The same for all the other  button bar style

**Comment by mlynch** [comment]
This is by design, we're making it more like v2

**Comment by danieljin** [comment]
@mlynch Why aren't the docs updated with these new styles?

**Comment by danieljin** [comment]
Also, isn't it strange that you didn't add border:transparent for when a button is active?

[Example](http://i.imgur.com/dSH21ir.png)

.button.active, .button.activated {
    border-color: #a2a2a2;
    background-color: #e5e5e5;
}
