### ISSUE TITLE
Feature: optional wrapping of text inside list items

### ISSUE THREAD

**Issue by atuttle** [driftyco/ionic#500]
Occasionally it is desirable to have list items with long text labels wrap. For example:

![screenshot 2014-01-31 09 55 23](https://f.cloud.github.com/assets/46990/2051359/c104c91a-8a87-11e3-8ea4-59220cf0b7ad.png)

(The text indentation and icon floating to the left are a separate feature of my own, not included here)

To accomplish this I created some custom CSS in my app, but I figure it would be a good feature to add to the framework, considering how generally reusable it could be.

I added this CSS to my app:

```
.wrapping-list .item-content, .wrapping-list .item {
    overflow: initial;
    white-space: initial;
}
```

And then declare the list with the `wrapping-list` class:

```
<list class="wrapping-list"></list>
```

If it's something you'd be willing to accept, I could send a pull request with these additions.

**Comment by chrisfranko** [comment]
sweet it works lol

**Comment by kgilmur** [comment]
I am using wrapping for a list card, but it pushes my buttons located at the bottom of the card out of the view, and decreases the list cards padding. Is this something I can work around? Any tips?

**Comment by VIF-AndrewRutazamba** [comment]
Thanks this saved my day and time since the "word-wrap" doesn't work.

**Comment by piotrowski** [comment]
+1
Thanks @atuttle

**Comment by amirthadharshini** [comment]
+1

**Comment by FLGGithubDeveloper** [comment]
@atuttle  will be nice to see your floating left css that works with the card list. :)

**Comment by nezzie2k333** [comment]
Awesome - That CSS sorted it instantly for me so I +1

**Comment by allen8300** [comment]
@bensperry @adamdbradley 

why item-text-wrap cannot work with ion-radio? it can only work with card?

**Comment by MA-Maddin** [comment]
`class="item-text-wrap"` not working for `<ion-item-divider>`.

```
    ion-item-divider, ion-item-divider * {
        overflow: initial;
        white-space: initial;
    }
```
did it

**Comment by MA-Maddin** [comment]
now it is done by utitlity attribute:

`text-wrap`

http://ionicframework.com/docs/theming/css-utilities/

**Comment by marcovtwout** [comment]
`text-wrap` for labels also changes the font-size and line-height for md:
```
[text-wrap] .label-md {
  font-size: 1.4rem;
  line-height: 1.5;
}
```

Alternative solution is to simply put:
```
ion-label {
  white-space: normal;
}
```

**Comment by arashmad** [comment]
thank @atuttle its work for me
