### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5003]
_From @manekinekko on January 17, 2016 2:35_

Hi guys, I am having some issues with 2.0.0-alpha.49. Every time I build my app, I get a `Uncaught RangeError: Maximum call stack size exceeded`. I am using a default project configuration with the default Angular 2 (2.0.0.beta.0). Nothing fancy. 
My app is running on standard Genymotion emulator, Nexus 5 - 5.1.0 - API 22.

Here is a details vue about the error:
![image](https://cloud.githubusercontent.com/assets/1699357/12375610/92dd7ac4-bcca-11e5-9d1a-dacf805f1e1a.png)

Thanks.

_Copied from original issue: driftyco/ionic2#947_

**Comment by mhartington** [comment]
_From @manekinekko on January 17, 2016 14:22_

Hi, I just noticed that this issue happens only when using `--livereload`. 
I was building using livereload: `ionic run android --livereload --device=192.168.59.102:5555`.

**Comment by mhartington** [comment]
_From @Luchillo on January 18, 2016 18:56_

+1 i'm happening the same, also the changes aren't being re-loaded in the devise.

**Comment by tlancina** [comment]
As far as I can tell this is a bug in zone.js with how they patch WebSockets, which is used by livereload.  I've opened an issue here: https://github.com/angular/zone.js/issues/233.

**Comment by tlancina** [comment]
Going to close this, the patch has landed in zone 0.5.11.
