### ISSUE TITLE
Ion-slides, passing through swiper options - direction doesn't work

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5004]
_From @DustinJSilk on January 16, 2016 9:49_

I've been trying to implement vertical slides to the ion-slides component and found this issue which showed that you can in fact pass through options to the swiper plugin (Which is a great thing and should be reference in the documentation):

https://github.com/driftyco/ionic2/issues/871

Using this technique:

```javascript
    this.slideOptions = {
      slidesPerView: 3
    };
```

```
<ion-slides [options]="slideOptions">
```

I've tried passing through:

```
this.slideOptions = {
      direction: "vertical"
    };
```

But it doesn't work. If I go and change the direction directly on the plugin then it works perfectly. 

**EDIT**
I realise the repo has actually moved :/

_Copied from original issue: driftyco/ionic2#946_

**Comment by mhartington** [comment]
_From @DustinJSilk on January 16, 2016 10:3_

I don't know why - but I stop ionic and re-served it and it started working. Seems like the app.bundle was being cached. Though when i changed other options they went through. Not sure what happened

**Comment by brandyscarney** [comment]
This doesn't seem to be an issue anymore.
