### ISSUE TITLE
Interpolated strings not automatically updated on variable change

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5005]
_From @av2k on January 15, 2016 15:15_

Hello,

the interpolated strings in a tabbed application are not automatically updated on variable that is changed by an asynchronous callback function.

If the user switches to another tab and back again, the interpolated strings show up properly.

System information:
Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.49
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
Node Version: v5.3.0

Excerpt of the JS of the tab:
```
  scanQRCode() {
    cordova.plugins.barcodeScanner.scan(
      (result) => {
        this.qrScanSuccess(result);
      },
      (error) => {
        // handle errors..
      }
      );
  }

  qrScanSuccess: (result: any) => void
  = function (result) {
    if (!result.cancelled) {
      this.qrResult = result.text;
    }
  }
```

Excerpt of the HTML of the tab:
```
<p>Result of QR: {{qrResult}}</p>
```

Note that the scanning itself works and that the scanned value correctly shows up when the user switches to another tab and back again.

_Copied from original issue: driftyco/ionic2#945_

**Comment by mhartington** [comment]
Have you tried using the `async` pipe in the data binding? This sounds more like an angular question that anything specific to ionic.

https://angular.io/docs/ts/latest/api/common/AsyncPipe-class.html

**Comment by mhartington** [comment]
_From @Luchillo on January 15, 2016 15:35_

Is that `:` after the `qrScanSuccess` function name supposed to be there?
What's that `=> void = function(){...` do?

**Comment by mhartington** [comment]
_From @robwormald on January 16, 2016 18:36_

this is probably zone related. the simplest fix would be to just wrap the call in a promise or observable in a service, which you should probably do anyway:
```typescript

class BarCodeService {
  scan(){
    return new Promise((resolve, reject) => {
      cordova.plugins.barcodeScanner.scan(resolve, reject);
   });
  }
}

```

**Comment by brandyscarney** [comment]
Closing this. Please submit a new issue if Rob's suggestion didn't work, @av2k. Thanks! http://ionicframework.com/submit-issue/
