### ISSUE TITLE
ion-radio just select the last option

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5006]
_From @mauricionarcizo on January 12, 2016 15:50_

Following the docs http://ionicframework.com/docs/v2/components/#radio

Whenever On touch the any option, always select the last option.

_Copied from original issue: driftyco/ionic2#936_

**Comment by 3dd13** [comment]
the demo code does not work with latest npm ionic-framework package(alpha-49), however it is working with latest github master.

suggest @mauricionarcizo to wait for next release and test again when alpha-50 is out

**Comment by brandyscarney** [comment]
No longer an issue. :smile:
