### ISSUE TITLE
Badge on ion-tab

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5007]
_From @mauricionarcizo on January 12, 2016 15:46_

How I can add badge on ion-tab? 

_Copied from original issue: driftyco/ionic2#935_

**Comment by mhartington** [comment]
_From @ivks on January 17, 2016 11:41_

+1. Looking for an answer to this question.
@mauricionarcizo  One Suggestion:
In case you are not using tabTitle, in tabs. Use it as a badge and style the .tab-button-text class to make it look like one.

**Comment by brandyscarney** [comment]
This is now possible using the following markup (`tabBadgeStyle` is optional):

```
<ion-tab tabTitle="Location" tabIcon="navigate" tabBadge="11" tabBadgeStyle="secondary"></ion-tab>
```

![screen shot 2016-01-23 at 12 45 10 pm](https://cloud.githubusercontent.com/assets/6577830/12531692/31e22eae-c1cf-11e5-9248-2373015f3228.png)


Tried to keep naming consistent with tabIcon and tabTitle. Let me know if you don't like this. @adamdbradley @mhartington

**Comment by mauricionarcizo** [comment]
Thank you!

**Comment by brandyscarney** [comment]
Forgot to check dynamic values. :smile: Can be passed like this:

```
myBadge:number = 55;
```

or this:

```
myBadge:string = "55";
```

and then on the tab:

```
<ion-tab tabTitle="Settings" tabIcon="settings" [tabBadge]="myBadge" tabBadgeStyle="primary"></ion-tab>
```

Examples here: 
https://github.com/driftyco/ionic/blob/2.0/ionic/components/tabs/test/badges/main.html
https://github.com/driftyco/ionic/blob/2.0/ionic/components/tabs/test/badges/index.ts

**Comment by ghaliano** [comment]
IS there any chance to have two badges ?

**Comment by mhartington** [comment]
This will not be supported. As the design from both platforms do not allow multiple badges to be displayed on the same component

**Comment by RonnieToupal** [comment]
any easy was to hide badge if its 0?

**Comment by marticrespi** [comment]
@RonnieToupal 

`tabBadge="{{ numItems > 0 ? numItems : '' }}" `

**Comment by mdanics** [comment]
@brandyscarney any way to have an ios styled badge on android?
