### ISSUE TITLE
Create d.ts file for swiper-widget

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5008]
_From @adamdbradley on January 12, 2016 15:33_

_Copied from original issue: driftyco/ionic2#934_

**Comment by mhartington** [comment]
_From @adamdbradley on January 12, 2016 15:34_

https://github.com/driftyco/ionic2/blob/master/ionic/components/slides/swiper-widget.ts

**Comment by mhartington** [comment]
_From @tlancina on January 16, 2016 1:27_

Still very new to TypeScript so it's possible there is a way to do this, but I believe we can't just add the types inline to Swiper because TypeScript won't create a type for es5 functions (constructor or no): https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#basic-concepts, meaning if we want type information for Swiper instances like [slides](https://github.com/driftyco/ionic/blob/2.0/ionic/components/slides/slides.ts#L86) we'll need to create a separate .d.ts file describing Swiper's "shape".

**Comment by adamdbradley** [comment]
Closing for now
