### ISSUE TITLE
Use d.ts for Hammer.js

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5009]
_From @adamdbradley on January 12, 2016 15:24_

Currently the hammer file is hacked with TS. Rather leave the hammer.js as is, and let the d.ts file add the types.

_Copied from original issue: driftyco/ionic2#933_

**Comment by mhartington** [comment]
_From @adamdbradley on January 12, 2016 15:25_

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/hammerjs/hammerjs.d.ts

**Comment by adamdbradley** [comment]
Closing for now

**Comment by intellix** [comment]
Anymore information on this? I'm reading the codebase and was confused to find Hammer copied in. I guess this is still a TODO with low priority?
