### ISSUE TITLE
Visual Studio 2015 Typescript intellisense support

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5011]
_From @xxsodapopxx5 on January 11, 2016 21:3_

Currently if you start a project via the CLI via ionic start TestProj1 tutorial --v2 --ts and create a project with those generated files in Visual Studio 2015 Community Edition, the typescript intellisense does not work correctly.

_Copied from original issue: driftyco/ionic2#926_

**Comment by mhartington** [comment]
_From @tlancina on January 11, 2016 21:10_

Thanks for the issue! When you say 'not correctly', do you mean that it doesn't work at all or that there are specific problems?

**Comment by mhartington** [comment]
_From @xxsodapopxx5 on January 11, 2016 21:48_

there are specific problems, definitions aren't coming through, for instance when I open app.ts any of the class properties are highlighted in red. After looking at it, this could be fixed fairly easily by adding private or public into the constructor parameters and defining the class properties for the additional missing ones. 
If fixed the below code, except for "StatusBar", which I am unsure about. 
![image](https://cloud.githubusercontent.com/assets/16467307/12246840/cd60906e-b87e-11e5-92ac-7529c2c1d8ad.png)

to this
![image](https://cloud.githubusercontent.com/assets/16467307/12247616/c635daa2-b882-11e5-890c-5f7098155be8.png)


~~I also cannot use visual studio build to compile everything correctly. The browser opens, ripple loads(with the phone screen), but the app does not load, it is just a blank white screen~~ See below. The build from CLI works just fine with the code changes above.

**Comment by mhartington** [comment]
_From @xxsodapopxx5 on January 11, 2016 21:53_

I didn't note this, but all of the .ts application specific files have similar changes that are needed, missing class properties, that once created correctly don't throw visual studio errors. The files are list.ts, item-details.ts and hello-ionic.ts

Once I cleared up the errors in typescript, visual studio started copying the files properly into www. I had to comment out the StatusBar error.

**Comment by mhartington** [comment]
this should be taken care of soon. We're going through the process of making sure the framework has the correct types. Once this is done, we'll update the starters.

**Comment by rtpHarry** [comment]
Side note: any changes to the starters will need reflecting in the docs eg:

http://ionicframework.com/docs/v2/getting-started/tutorial/adding-pages/

**Comment by Misiu** [comment]
@mhartington do You guys plan to support directives intellisense in Visual Studio? It's hard for beginner to start using Ionic, with proper hints (intellisense) this would be much easier.
I found [Ionic Pack](https://visualstudiogallery.msdn.microsoft.com/d6279fba-bcff-4857-906d-29faa8a99448) but something created and maintained by Ionic Team would be awesome (even if I have to pay for it)!
I'm setting up all tools to start learning Angular 2 and Ionic2 so I'll try this extension, but as I wrote, official support would be great!

**Comment by mhartington** [comment]
We will probably support something like that.

**Comment by mhartington** [comment]
This should be taken care of now.
