### ISSUE TITLE
Alert input loses focus after initial view

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5012]
_From @joshuamorony on January 10, 2016 2:47_

I recently created this issue which was solved: https://github.com/driftyco/ionic2/issues/847

The first input field in an Alert now auto focuses when it is launched. This works fine through a web browser, but on iOS it only works the first time. If you launch the Alert a second, third, fourth etc. time the input field is briefly focused and the keyboard pops up, but then it quickly disappears.

From my brief research, it seems like it might be an issue with the touchend event firing after the input is focused by the Alert, making it lose focus again.

I've been able to workaround this temporarily by using a bit of a hack with setTimeout:

```
    AlertCmp.prototype.onPageDidEnter = function () {
        document.activeElement && document.activeElement.blur();
        if (this.d.inputs.length) {
            var firstInput = this._elementRef.nativeElement.querySelector('input');
            if (firstInput) {
                setTimeout(function(){
                    firstInput.focus();                       
                }, 400);
            }
        }
    };
```

So that the focus fires after the touchend event, but obviously that's not a great solution.

_Copied from original issue: driftyco/ionic2#913_

**Comment by stalniy** [comment]
@mhartington This is reproducible in beta.9
