### ISSUE TITLE
Svg animate within menu breaks the app after change page in android

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5013]
_From @kitkimwong on January 9, 2016 9:46_

I created a tutorial app about the menu.
And I create a svg inside one of the page : 

    <ion-navbar *navbar>
      <button menuToggle >
    <icon menu></icon>
      </button>
      <ion-title>Route</ion-title>
    </ion-navbar>

    <div  elastic-header style="width:100%;height:100%;position:relative;background-color:white" id ="OuterSvg">

	<svg id="svgdoc"  xmlns="http://www.w3.org/2000/svg" 
		version="1.1" width="100%" height="100%" (click)="OnClickSvg()"  style="position:relative">
			<g id ="ZoomGroup" >
				<image 
				xmlns:svg="http://www.w3.org/2000/svg"		
				xlink:href="img/subway2.png" x="0" y="0"
				[attr.width] = "width"
				[attr.height] = "height"
				id= "SubMap"
				/>
				
      <circle r="20" cx="50" cy="50"  id = "StopPoint2"
		style="fill:rgba(96, 42, 139, 0.3);stroke:purple;stroke-width:4;display: block;">
		<animate dur="3s" attributeName="r" values="50; 90; 50"
		repeatCount="indefinite"  />
      </circle>					
			</g>
	</svg>
		
</div>

<ion-overlay></ion-overlay>

And  open the app in the android 4.4.4, after i switch the page between the svg page and other page. the app will break unexpectedly( about 11 second in the video).
See what's happen:
https://www.youtube.com/watch?v=qEqzIY48HFo

After i remove the "animate". it works and no break. 
Moreover, i reserve the animate but remove the     repeatCount="indefinite"   . it seem works too.
I don't know whether this is ionic's problem or not. But i got a bottleneck on that.

_Copied from original issue: driftyco/ionic2#905_

**Comment by brandyscarney** [comment]
@kitkimwong Is this still an issue using alpha.54 of the framework?

**Comment by kitkimwong** [comment]
@brandyscarney  Thank you for your reply. I find that every thing is fine after update to .54 version. Test on android 4.4.4

**Comment by brandyscarney** [comment]
@kitkimwong Going to close this then. Thank you!
