### ISSUE TITLE
ios tabs lost their correct styling

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5014]
_From @bensperry on January 9, 2016 0:44_

![image](https://cloud.githubusercontent.com/assets/519526/12213072/c846558a-b637-11e5-8237-de62fa80b96e.png)

the unselected tab items should not be colored at all. They should look like this:
![image](https://cloud.githubusercontent.com/assets/519526/12213084/e8a211c0-b637-11e5-9c8f-e3a852497563.png)

_Copied from original issue: driftyco/ionic2#904_

**Comment by brandyscarney** [comment]
No longer an issue
