### ISSUE TITLE
Android segment lost some styling at some point, needs to be looked at

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5015]
_From @bensperry on January 9, 2016 0:43_

![image](https://cloud.githubusercontent.com/assets/519526/12213069/b38c6ad0-b637-11e5-964a-3fbefcd914dd.png)

_Copied from original issue: driftyco/ionic2#903_

**Comment by brandyscarney** [comment]
There was CSS that determined which color to make the segment based on the toolbar it was in. This made the selector too complex so we are going to rely on the user to set the segment color. Therefore this should be updated in the demo.

```
<ion-toolbar primary>
  <ion-segment light>
```

By default an `ion-segment` is going to be the primary color.

**Comment by mhartington** [comment]
Fixed

http://ionicframework.com/docs/v2/components/#segment
