### ISSUE TITLE
Special Characters not supported (Scandinavian chars)

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5017]
_From @Doehl on January 8, 2016 15:42_

The Danish and Swedish characters **æøå** and **öä** as an exsampel is not supported in Ionic 2.

I am using the charset UTF-8.
```html
<meta charset="UTF-8">
```

I add some of the Danish and Swedish characters, will it be shown as the following �.
I have tried to add the characters outside the ```<ion-app></ion-app>```, and then is it show correctly.

_Copied from original issue: driftyco/ionic2#900_

**Comment by mhartington** [comment]
_From @Doehl on January 8, 2016 15:55_

Workaround is to use the HTML special character value like **& auml;** (Without space) to get **ä**.

**Comment by adamdbradley** [comment]
This should be fixed in the upcoming angular beta release, thanks: https://github.com/angular/angular/issues/6036
