### ISSUE TITLE
Typescript generators

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5019]
_From @tlancina on January 8, 2016 1:32_

Right now the generated components are not typed.  Also might be nice for the tooling to differentiate between Typescript and ES6 projects (separate issue). 

_Copied from original issue: driftyco/ionic2#892_

**Comment by lordgreg** [comment]
+1

**Comment by Peekmo** [comment]
Hello,

I'll like it a lot (as it is already possible to `start` a projet with `--ts`)

Regards,
Peekmo

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#753
