### ISSUE TITLE
Need to be able to easily configure the color of the tabbar/navbar based on mode

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5021]
_From @brandyscarney on January 7, 2016 1:18_

Used to be able to configure the tabbar/navbar color based on platform - would be nice to configure it by mode since MD should be colored while iOS should not. 

_Copied from original issue: driftyco/ionic2#882_

**Comment by brandyscarney** [comment]
You can change the default tabbar/navbar using Sass variables, see the conference app: https://github.com/driftyco/ionic-conference-app/blob/master/app/theme/app.md.scss

**Comment by brandyscarney** [comment]
This will be possible in the `beta 12` release via https://github.com/driftyco/ionic/issues/7467 and https://github.com/driftyco/ionic/issues/7064
