### ISSUE TITLE
Look into icon-only buttons having no padding 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5024]
_From @brandyscarney on January 5, 2016 22:28_

These should probably have padding if they aren't in an item but need to look into it:

![screen shot 2016-01-05 at 5 27 53 pm](https://cloud.githubusercontent.com/assets/6577830/12129439/b0525e46-b3d1-11e5-9867-9f434d9cc642.png)

_Copied from original issue: driftyco/ionic2#869_

**Comment by mhartington** [comment]
_From @drewrygh on January 6, 2016 3:0_

:+1:

**Comment by mhartington** [comment]
_From @bensperry on January 9, 2016 0:42_

![image](https://cloud.githubusercontent.com/assets/519526/12213055/86cb3ca6-b637-11e5-8ae7-a83a44541b20.png)

![image](https://cloud.githubusercontent.com/assets/519526/12213058/8abfbe68-b637-11e5-9c12-a3d095bd48d9.png)

**Comment by brandyscarney** [comment]
No longer an issue with alpha 51
