### ISSUE TITLE
docs: Add docs on the text alignment and transformation attributes

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5026]
_From @brandyscarney on January 5, 2016 22:24_

We should have a `util` section that includes the different attributes you can use, possibly include the padding attributes:

https://github.com/driftyco/ionic2/blob/master/ionic/components/app/typography.scss#L101-L137
https://github.com/driftyco/ionic2/blob/master/ionic/util/util.scss#L15-L54

_Copied from original issue: driftyco/ionic2#867_

**Comment by brandyscarney** [comment]
Moved: https://github.com/driftyco/ionic-site/issues/398
