### ISSUE TITLE
fab-button hides text at bottom

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5028]
_From @ivanbtrujillo on January 5, 2016 12:17_

Hi guys, 

i've commented this with @brandyscarney:

Because the fab-button has a position:absolute, it will always hide the text behind. For my own problem (fab-bottom), i've applied a margin-bottom:40px; to see the text behind, but the apps doesn't look good.

<img width="214" alt="captura de pantalla 2016-01-05 a las 12 09 07" src="https://cloud.githubusercontent.com/assets/6088653/12114899/c3a642ea-b3a5-11e5-9227-2b1e24c8ee2a.png">

for example, in other native apps (like airbnb), i saw they applies a margin (or whatever) when finds a fab buttom. In this case, we can see the text and the app looks fine.

<img width="205" alt="captura de pantalla 2016-01-05 a las 12 16 25" src="https://cloud.githubusercontent.com/assets/6088653/12114962/335bb57a-b3a6-11e5-88e1-00ae2d7dff78.png">

Thanks!

_Copied from original issue: driftyco/ionic2#860_

**Comment by mhartington** [comment]
_From @nampdn on January 5, 2016 21:22_

I think applying a margin is not a good idea, the paragraph or others behind content will be narrower (eg: a ion-list). I see some native app solve this by scrolling detection. If user scroll up/down, the fab-button will be faded-out or pushed down and vice versa.

**Comment by mhartington** [comment]
_From @jgw96 on January 9, 2016 3:46_

Im not sure that applying a margin by default is the best solution here. The fab should definitely be kept absolutely positioned; if it wasn't it would scroll with the view, which obviously is not ideal. Using css to make sure the fab does not cover text should be done by the developer on a case by case basis. This is all my opinion btw, so i could be horribly wrong! (:

**Comment by brandyscarney** [comment]
@ivanbtrujillo We think this is something that should be handled by the developer on a case by case basis. We can re-evaluate later if more people ask for it but it seems to be a general consensus that it is custom to your individual app. :smile:
