### ISSUE TITLE
Search bar icon overlaps with placeholder

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5029]
_From @adamdbradley on January 4, 2016 17:41_

![image](https://cloud.githubusercontent.com/assets/452425/12096010/010a0d66-b2d8-11e5-91a9-483930d3ba17.png)

_Copied from original issue: driftyco/ionic2#853_

**Comment by mhartington** [comment]
_From @brandyscarney on January 4, 2016 20:34_

I was able to reproduce this in a new test `nav`. It is caused by the searchbar icon width being 0 when it is called the first time.

**Comment by sweinertjr** [comment]
Same issue here.

**Comment by brandyscarney** [comment]
Added a temporary fix for this. If you change the width of the search icon in the Sass it will not work properly, but this should fix it by default for now.
