### ISSUE TITLE
Add Right To Left Support

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5035]
_From @mashaly100200 on December 30, 2015 17:24_

kindly add support rtl to animation and the components

_Copied from original issue: driftyco/ionic2#832_

**Comment by mhartington** [comment]
_From @adamdbradley on December 30, 2015 17:38_

Yes this is on our roadmap to complete and we would love to get more feedback from experienced RTL dev's to help us point out where we need to improve. Would you be able to provide a checklist of certain parts of ionic2 that do not work well with RTL. Our goal would be to provide an additional RTL css file, and have any JS adjust accordingly depending if the html element has `dir="rtl"` or not. Thanks

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 18:39_

It's my pleasure to help ionic2 team to support RTL 
firest it's easy to watch what are the bad effects if we use rtl direction
we can add this attr to html tag that will convert all website to to rtl 
<html dir="rtl" lang="ar">
or
we can use it in the body as a style like this
style="direction:rtl" 

if ionic team plan to support rtl

thay will need to add the target direction in App configurations , because the application will need to know what is the direction on the start up 
, and if the developer need to change the app language to rtl language in runtime then we should refresh all app (like native android,windows phone app , ios need to restart the application to change it's direction)


now when i try to change ionic2 html direction i found that there are things aleady support rtl direction coz pure html konw how to deal with rtl direction
but thare are things need to be support rtl direction
first thing is animation
i donn't know if ionic team do the animation with css or javascript code , in both cases all animation witch have rtl or ltr  will need to add another animation direction , not only change varialbe but add another one coz many things will need to change


I would like to provide assistance as i can to ionic team to help in this great library 

i know my English is not good , but i hope you understand my words :)

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 18:44_

plz change this goal  " Our goal would be to provide an additional RTL css file "
because we need the two direction in the same application , based on the user's choice , some time it will be in runtime

**Comment by mhartington** [comment]
_From @adamdbradley on December 30, 2015 18:51_

> we need the two direction in the same application , based on the user's choice , some time it will be in runtime

Ionic itself will be able to dynamically add this css file for you, depending on the `<html dir="rtl">`

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 19:23_

these imgs from trying to change direction of onic-conference-app example
if ionic team cover the rtl direction in this example  i think it will be not less than 90% of rtl support

![Image of Yaktocat](http://imageshack.com/a/img903/3/BO4pib.png)

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 19:26_

![Image of Yaktocat](http://imageshack.com/a/img910/6199/m4CPLa.png)

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 19:27_

![Image of Yaktocat](http://imageshack.com/a/img905/3990/IB20Mo.png)

**Comment by mhartington** [comment]
_From @mashaly100200 on December 30, 2015 20:21_

any icon which are right,left,back or forward arrow like back-button icon will need this style
{
    -webkit-transform: rotate(180deg);
    -moz-transform: rotate(180deg);
    -o-transform: rotate(180deg);
    -ms-transform: rotate(180deg);
    transform: rotate(180deg);
}

**Comment by mhartington** [comment]
_From @adamdbradley on December 31, 2015 4:27_

So @brandyscarney had a good idea that we create all the RTL scss files within the repo and get them ready to be filled. 

I was thinking that instead of dynamically adding another rtl css, we could have a default `$rtl-support: false` sass variable that can be updated in each app's sass variables. So in most cases the extra rtl css wouldn't be added to apps, but for those who require the rtl css they can set `$rtl-support: true`.

Then within our new rtl scss files, the css can be wrapped with `@if $rtl-support`. This way we can keep the css files separated and easier to edit, and provide rtl support out of the box. Think this will work @mashaly100200 ?

**Comment by mhartington** [comment]
_From @mashaly100200 on December 31, 2015 11:48_

yes load rtl  dynamically is a good idea ,

let us start with animation , coz it may be need more effort 

- i want to know is it possible to add specific page transition animation when do  push and pop  pages ?
- and how developer add this specific animation to the tow pages witch enter and leave ?

- can developer watch back event then add his specific animation also to the two pages ?

if your answer are yes for the previous three questions , then i  can congratulate my self coz animation topic don't need any effort and full support rtl direction and ionic team deserve a very big thanks  :)

**Comment by mhartington** [comment]
_From @adamdbradley on January 1, 2016 1:53_

This is the transition animation for ios: https://github.com/driftyco/ionic2/blob/master/ionic/animations/ios-transition.ts

Not sure if this should add logic for RTL, or if there should be a new animation instead. You can however add your own transition, and override the `pageTransition` config: https://github.com/driftyco/ionic2/blob/master/ionic/config/modes.ts#L24

**Comment by mhartington** [comment]
_From @mashaly100200 on January 1, 2016 21:55_

hi @adamdbradley , merry christmas

i finished a custom animation class which reverse the default animation class behavior depend on documen.dir  
https://gist.github.com/mashaly100200/bf713f2b558285322155
 i tested it , and i will test it in real projects soon (inshaa allah) 

also i finished some of css classes that was need to be reversed 
https://gist.github.com/mashaly100200/dc23529e570034b0dfb9

and if i face more classes need to be reversed , i will add it to this file until i finish one or two real project  

also rtl need these configurations in app constructor
https://gist.github.com/mashaly100200/692160b036422d7b018c

i was trying to add all configuration in one place so i found that i can add all things in the app contractor

hope these things can help to make ionic2 fully support rtl    

Please feel free to add any corrections or suggestions .

**Comment by mhartington** [comment]
_From @adamdbradley on January 2, 2016 3:2_

Cool, so it looks like the RTL transition is pretty darn close to the LTR transition, which makes me think it should be an `isRTL` option that gets passed into the transition's options and we only have one transition. I can update ionic so it has a common `isRTL` property that can be referenced throughout the app (with webworkers we want to avoid doing `document` reads within ionic's logic).

**Comment by mhartington** [comment]
_From @adamdbradley on January 2, 2016 3:36_

Added `isRTL()` to `Platform`: https://github.com/driftyco/ionic2/blob/0b4b8628bf87cabab92d6563bf9878db8b86c885/ionic/components/modal/test/basic/index.ts#L16

**Comment by mhartington** [comment]
_From @adamdbradley on January 2, 2016 3:58_

All transitions are now passed `isRTL` within the `opts`: https://github.com/driftyco/ionic2/blob/da986a5fb0ee2c7660ad4494731b5fe98b393812/ionic/components/nav/nav-controller.ts#L798

So now the ios-transition can add the logic for RTL transitions.

**Comment by mhartington** [comment]
_From @adamdbradley on January 2, 2016 4:38_

Added how we can include RTL css so it correctly builds within ionic.css (which includes both md and ios css) and ionic.ios.css (just ios). The thought is that apps which want to include both RTL and LTR css within the same file can set `$include-rtl: true` in their sass variables, otherwise it'll default to only include LTR css. https://github.com/driftyco/ionic2/blob/f38ad4a7d2d8c527a3bc64fd8569b11eb659c290/ionic/components/item/item.ios.scss#L231

**Comment by mhartington** [comment]
_From @MatanYed on January 6, 2016 18:14_

Just you to know: RTL apps in iOS are partly LTR:
Primary navbar button side is left, side menu is left, transition animation is from left to right.

**Comment by mhartington** [comment]
_From @adamdbradley on January 7, 2016 16:41_

Added new methods to platform to get and set language and direction: https://github.com/driftyco/ionic2/commit/942bd9b93b97a88554aafc9972c1c2d86de9273f

**Comment by mhartington** [comment]
_From @mashaly100200 on January 12, 2016 21:2_

update
for anyone flow this topic 
replace 
 config.set('backButtonIcon', 'ion-ios-arrow-forward');
with
 config.set('backButtonIcon', 'arrow-forward');

also i update the animation class
https://gist.github.com/mashaly100200/bf713f2b558285322155

**Comment by mohessaid** [comment]
I have been working on this problem on a moodle mobile app for our company and we need the app to support English and Arabic in the same time, so it's not a problem of switching the direction everything to RTL but it need to be in runtime. I used some tweaks at the beginning using ng-if and some broadcasting through the rootscope in the app, but whenever the user change the language, the app needs a reload, things not working at all with this method.
Three days ago, I started fighting with Ionic (it becomes an universal problem :) ), The moodle team open issues at the moment but I don't think they will look at them.
I am not using Ionic 2 but my approach in this problem is very simple, with ionic side attribute in ionic directive (I think most concerned directive with the RTL problem has this attribute) will make the solution easier than it looks.
I am trying to override the directive to add binding to the side attribute because now, it doesn't then add some alignments to the rest of the content using css in the app.scss, and with the help of angular-translate and the current implementation of the moodle app, update the left in word in classes and side to right and vise versa whenever the language change.
I am still implementing it at the moment I hope it will work (it must work anyway).

**Comment by wesamco** [comment]
The Nav amination has to be opposite to the app direction, from left for RTL apps and from the right for LTR apps. to fix it I did this:
changed
`	var OFF_RIGHT = '99.5%';
`
to
`	var OFF_RIGHT = '-99.5%';
`
and
`	var OFF_LEFT = '-33%';
`
to
`	var OFF_LEFT = '33%';
`
and
```
	            if (backDirection) {
	                // leaving content, back direction
	                leavingContent
	                    .before.clearStyles([OPACITY])
	                    .fromTo(TRANSLATEX, CENTER, '100%');
	            }
```
to
```
	            if (backDirection) {
	                // leaving content, back direction
	                leavingContent
	                    .before.clearStyles([OPACITY])
	                    .fromTo(TRANSLATEX, CENTER, '-100%');
	            }
```
in ionic-angular/transitions/transition-ios 

after adding dir="rtl" to index.html, the rendering of elements will start from right, that affects the look of some elements, like the segment button.
to fix it I changed
```
  .segment-button:first-of-type {
    border-radius: 4px 0 4px 0;
    margin-left: 0; }
  .segment-button:not(:first-of-type) {
    border-left-width: 0; }
  .segment-button:last-of-type {
    border-left-width: 0;
    border-radius: 4px 0 0 4px;
    margin-left: 0; }
```
to
```
  .segment-button:first-of-type {
    border-radius: 4px 0 0 4px;
    margin-right: 0; }
  .segment-button:not(:first-of-type) {
    border-right-width: 0; }
  .segment-button:last-of-type {
    border-right-width: 0;
    border-radius: 0 4px 4px 0;
    margin-right: 0; }
```

**Comment by MuhammadRashed** [comment]
in the file: ionic.bundle.js
change the code:

setTranslateX: ionic.animationFrameThrottle(function(amount) {
var xTransform = content.offsetX + amount;
$element[0].style[ionic.CSS.TRANSFORM] = 'translate3d(' + xTransform + 'px,0,0)';
change it to be:

setTranslateX: ionic.animationFrameThrottle(function(amount) {
var xTransform = content.offsetX + amount;
if (content.offsetX > 0)
{
      xTransform = amount;
}
$element[0].style[ionic.CSS.TRANSFORM] = 'translate3d(' + xTransform + 'px,0,0)';
I know this is not good solution but I had to.

__________
and I added these css:


   
   a , h1 , h2 , span , div{
      text-align: right;
        }
        
        .title.title-left.header-item{
            left : 0 !important;
        }
label.item,
ion-nav-buttons,
ion-header-bar{
    direction: rtl;
}

.item-checkbox {
    padding-right: 60px;
}


.ion-android-arrow-back:before {
  content: ""; }
  
.ion-android-arrow-forward:before {
  content: ""; }
  
_____________

and made the menu on right : 

<ion-side-menus enable-menu-with-back-views="false" >
   
    <ion-side-menu side="right" **expose-aside-when="large"**>
        <ion-header-bar class="bar-positive">
            <h1 class="title">Menu</h1>
        </ion-header-bar>
        <ion-content>
            <ion-list>
                <ion-item menu-close ng-click="login()">
                    Login
                </ion-item>
        
               
            </ion-list>
        </ion-content>
    </ion-side-menu>
    
    
      <ion-side-menu-content>
        <ion-nav-bar class="bar-positive">
      
            <ion-nav-back-button>
            </ion-nav-back-button>
            <ion-nav-buttons side="right">
                <button class="button button-icon button-clear ion-navicon" menu-toggle="right"></button>
            </ion-nav-buttons>
            
        </ion-nav-bar>
        <ion-nav-view name="menuContent"></ion-nav-view>
    </ion-side-menu-content>
    
    
    
</ion-side-menus>

**Comment by alaa-alshamy** [comment]
yeah that's what we are waiting for , and that's will be awesome 

thanks ionic team 

go ahead :+1:

**Comment by sijav** [comment]
if the menu placement is right with rtl specifications on html tag, you can't see the menu correctly by opening it, I dig around the codes and figured it out that on menu-types.js from ionic-angular/components/menu/menu-types.js there's a code on line 124 that specify if the menu.side is right closedx must be whole platform with and openedX is something like platform width minus menu width minus 8 px, they're way off the user screen on rtl mode!
so I changed the code a little bit and add an if behind the `if (menu.side === 'right') {` with bellow code
```
        if (menu.side === 'right' && menu._platform.isRTL()) {
            // right side and is rtl
            closedX = menu.width() + 'px';
            openedX = '0px';
        }
        else if (menu.side === 'right' &&) {
            // right side and is ltr
            closedX = menu._platform.width() + 'px';
            openedX = (menu._platform.width() - menu.width() - 8) + 'px';
        }
        else {
            // left side for both rtl and ltr is equal
            closedX = -menu.width() + 'px';
            openedX = '8px';
        }
```
i believe the same must be done for MenuPushType (as this one is for MenuOverlayType). but i just don't know what is MenuPushType :D
now it's working perfectly with just a minor bug, if you open the menu then push a little to the edge then pull it back the menu will suddenly disappear! (maybe something to do with MenuType.isOpening?)
Hope it helps

**Comment by sijav** [comment]
if the menu placement is right with rtl specifications on html tag, you can't see the menu correctly by opening it, I dig around the codes and figured it out that on menu-types.js from ionic-angular/components/menu/menu-types.js there's a code on line 124 that specify if the menu.side is right closedx must be whole platform with and openedX is something like platform width minus menu width minus 8 px, they're way off the user screen on rtl mode!
so I changed the code a little bit and add an if behind the `if (menu.side === 'right') {` with bellow code
```
        if (menu.side === 'right' && menu._platform.isRTL()) {
            // right side and is rtl
            closedX = menu.width() + 'px';
            openedX = '0px';
        }
        else if (menu.side === 'right' &&) {
            // right side and is ltr
            closedX = menu._platform.width() + 'px';
            openedX = (menu._platform.width() - menu.width() - 8) + 'px';
        }
        else {
            // left side for both rtl and ltr is equal
            closedX = -menu.width() + 'px';
            openedX = '8px';
        }
```
i believe the same must be done for MenuPushType (as this one is for MenuOverlayType). but i just don't know what is MenuPushType :D
now it's working perfectly with just a minor bug, if you open the menu then push a little to the edge then pull it back the menu will suddenly disappear! (maybe something to do with MenuType.isOpening?)
Hope it helps

**Comment by hemedani** [comment]
`ion-item-options` needs to be `swipe-left` option for rtl version like this :
```html
        <ion-item-sliding swipe-left>
            <ion-item>
                <ion-avatar item-right>
                    <img src="img/slimer.png">
                </ion-avatar>
                <h2>Slimer</h2>
            </ion-item>
            <ion-item-options>
                <button primary>
                    <ion-icon name="text"></ion-icon>
                    Text
                </button>
                <button secondary>
                    <ion-icon name="call"></ion-icon>
                    Call
                </button>
            </ion-item-options>
        </ion-item-sliding>
```

**Comment by rejeeshrajan10** [comment]
Hi,
I am working on ionic 2.0. how can i reduce the width in left navigation.

**Comment by msoni11** [comment]
How are you handling Gestures with rtl in v2?
I need to fix it for iOS platform in ionic v1. I was able to change the direction of sidemenu and swiping direction in rtl. 
https://github.com/msoni11/ionic/releases/tag/v1.1.1-rtl

**Comment by MatanYed** [comment]
When RTL feature will be publish, it would be able to change it after running the app (i mean live change between ltr to rtl?
Just like native apps that have change language page in app.

**Comment by msoni11** [comment]
@MatanYed : Yes it will. It must actually. It's pretty straight in hybrid app by just changing direction and text-align using CSS.

**Comment by devoraf** [comment]
@mhartington : when using floating ion-label with RTL direction, the floating label does not being aligned to the right, but somewhere in the middle, when typing text in the input field.
is there any solution for it?

`<ion-list dir="rtl"> <ion-item> <ion-label floating >{{ usrTitle }}</ion-label> <ion-input type="text" [(ngModel)]="usrValue"></ion-input> </ion-item> <ion-item> <ion-label floating >{{ pswTitle }}</ion-label> <ion-input type="password" [(ngModel)]="pswValue"></ion-input> </ion-item></ion-list>`

![floating](https://cloud.githubusercontent.com/assets/20514282/17099874/c683a3be-5273-11e6-9c81-243413717367.png)

**Comment by royipressburger** [comment]
+1

**Comment by astec** [comment]
@royipressburger (_regards "+1"_) - there is "thumb up" emoticon & "Subscribe" button if you want to support or follow.

**Comment by devoraf** [comment]
@mhartington, @msoni11: any answer? i'm really stuck with it.

**Comment by msoni11** [comment]
@devoraf : I'm not sure which version of ionic you are using. In ionic v1 I've played with RTL css and form element worked for me.

**Comment by devoraf** [comment]
@msoni11: ionic v2. did this particular floating behavior worked well for you?

**Comment by msoni11** [comment]
@devoraf : I haven't tried v2 yet. My app has a lot of code written in v1 so I hacked v1 to allow RTL.

**Comment by devoraf** [comment]
@msoni11 : can you please attach sample css that might effect the alignment/direction of the floating label?

**Comment by RezaHaidari** [comment]
+1

**Comment by msoni11** [comment]
@devoraf : Sorry but I haven't used floating labels. I've used [these](http://ionicframework.com/docs/components/#forms) form elements and made it right aligned for RTL.

**Comment by loolooii** [comment]
I don't know if it has been stated, but even navigating through pages gets messed up when `dir="rtl"` is added to `<html>` tag. In Ionic 2 a lot of components I used  did not support it and I ended up switching back to Ionic 1. Right now I can do something about components and haven't come across any that are a problem for me, but the navigation gets messed up and I get white screens or laggy pages. When I remove `dir="rtl"` everything works perfectly. 

Am I doing something wrong or `$state.go()` actually does not work with `rtl` at all?

**Comment by msoni11** [comment]
@loolooii : You have to add css to make ionic 1 work for RTL

```
.rtl, html[dir=rtl] {
  direction: rtl;
  text-align: right;
}

/** To fix empty page issue in rtl. **/
.rtl .click-block-hide {
  @include translate3d(9999px, 0, 0);
}
```

Use this ionic rtl version https://github.com/msoni11/ionic/releases/tag/v1.1.1-rtl and you will be able to swipe right in RTL.

**Comment by loolooii** [comment]
@msoni11 Thanks! Awesome stuff.

**Comment by msoni11** [comment]
@loolooii : :) I've written a small post also where I mentioned how actual implementation will work in ionic app. Check [here](http://msoni11.blogspot.in/2016/06/rtl-in-ionic-v1.html)

**Comment by MatanYed** [comment]
Any update about the RTL issue?

**Comment by OmarHassan25** [comment]
Any updates regarding this  ? , also why ionic team removed it from beta 12 ?

**Comment by Khalid-Nowaf** [comment]
I think if we list all the RTL issues from developer feedbacks, we can contribute and fix them one by one, eventually, we will end up with full RTL support.

**Comment by AmitMY** [comment]
RTL is really important! Is there a timeframe?

**Comment by msoni11** [comment]
@AmitMY  Not sure about ionic2 but for ionic1 one of my app is running pretty well with RTL support.

**Comment by AmitMY** [comment]
@msoni11 Thanks. I am talking about Ionic2.

**Comment by Khalid-Nowaf** [comment]
@AmitMY @msoni11 I will work soon in a mid-size project using IONIC 2, then I will spot all RTL Issues if any .

**Comment by msoni11** [comment]
@Khalid-Nowaf : I would be happy to help.

**Comment by Khalid-Nowaf** [comment]
@msoni11 thanks! I will keep you  guys posted.

**Comment by OmarHassan25** [comment]
RTL was present in road map RC 12, i don't know why they dropped it ?!

**Comment by AlGantori** [comment]
Hello, I don't see ion-slides in this long thread?
It too needs support.
I have posted here a request
http://idangero.us/swiper/forum/#!/general:support-for-pagination-righ

my workaround, not coded yet, would be to populate the slides backwards, and move to last slide upon start.  I assume I have the right events to detect end of play, when playback reaches 1st slide  :)

**Comment by Mohsen7s** [comment]
When in rtl mode, there is no margin between range and its labels, hence the icons on both sides are partially not visible.

**Comment by jgw96** [comment]
As part of this we should also look into this issue https://github.com/driftyco/ionic/issues/10685

**Comment by mhartington** [comment]
Hey all, we're moving the tracking of RTL support in to this issue 
https://github.com/driftyco/ionic/issues/11211

Brandy will doing some work to get this going so expect to see it soon.

**Comment by joesleiman** [comment]
there are lots of messages here , i didn't find the solution as i'm not good at english .
can someone lead me to the solution of direction of the menu, because when it changes to left there animation it opens from left to right , and the swipe still from left to right also.
please any help.

**Comment by AmitMY** [comment]
@joesleiman There is no solution for you at the moment. A fix is suggested in https://github.com/driftyco/ionic/pull/11336 and is pending review.

**Comment by joesleiman** [comment]
@AmitMY  ok thank you . i have another problem how to change the direction to rtl from html tag in index.html or ion-app or body because the ion-select it's not under <ion-nav> where i change the direction. can you lead me to a solution if you know ?

**Comment by msoni11** [comment]
@joesleiman: If you're using ionic1, I've fixed it under this tag https://github.com/msoni11/ionic/releases/tag/v.1.1.1-rtl.1

You can review and apply changes.

**Comment by AmitMY** [comment]
You set your default  'dir' on the HTML tag, and if you want to change it in runtime, you do 'this.platform.setDit('rtl', true)'.

Don't use the dir attribute anywhere else, as nested directions are not supported.

Finally, please use the nightly version, as it is more RTL ready than 3.2.1

If you have any other support questions, please use the ionic forum, and for bugs/features use github

**Comment by joesleiman** [comment]
@msoni11  no ionic 3.2.0

**Comment by joesleiman** [comment]
@AmitMY  i'm using in all my app in every root tag [att.dir]='isRtl? 'rtl':'ltr''
isn't good ?

**Comment by Khalid-Nowaf** [comment]
@joesleiman 
for now, I use material design page transition only, which is an alternative to avoid page transition from left to right.

````javascript
// in app.module.ts
.
.
imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp, {
       pageTransition: 'md-transition' // change the page Transition to avoid "LRT" page Transition 
    })
.
.
````

**Comment by joesleiman** [comment]
@AmitMY  how can i change the back button icon to right arrow  instead of left arrow (when change it to rtl)

**Comment by AmitMY** [comment]
@joesleiman No, having `dir="rtl"` on `ion-content` is not guaranteeing support. You should always use `this.platform.setDir('rtl', true)` and remove all of the `dir` attributes except the one in the `html` tag. It also controls direction of ionic components from typescript, such as gestures. (note that `setDir` with `true` also updates the html tag with the correct dir)

About the back button, if you use the proper way to set direction, as mentioned above, it will flip your arrows, as done here - https://github.com/driftyco/ionic/pull/11634. It is only available in the nightly version, and a new version (3.3.0) will be released later today.

I ask again, please, for these kind of support questions use the forum. Github is for bugs/feature requests.

You can read more about RTL here - https://github.com/AmitMY/ionic-site/blob/543cc0dd6d198edd5aa2a9a31ac5bd4702ef5332/content/docs/rtl-support/index.md
This is the official RTL documentation, but it is not yet done so it is not in the website.

**Comment by joesleiman** [comment]
@AmitMY  ok i will do ... thank you so much ,

**Comment by joesleiman** [comment]
@AmitMy if the user put this.platform.setDir('rtl',true); and close the app and then return to it how can i save for html tag dir='rtl' . so isn't good idea to use it

**Comment by AmitMY** [comment]
@joesleiman So if your app is multidirectional, and you use the user preferences to decide which side, I would recommend using `NativeStorage`, and storing for the key "preferences" the object: `{lang: "he", dir: "rtl"}`, and then in `app.component.ts` on `platform.ready` check if the user has preferences. If he does, apply them by `setDir`.

No other solution for now.

**Comment by joesleiman** [comment]
@AmitMY  ok Done :)

**Comment by joesleiman** [comment]
@AmitMY  i solved it by this :
 html[dir="rtl"] .alert-md .alert-radio-icon {
  left: 0px;
  right: 13px;
}

**Comment by AmitMY** [comment]
I think you are not using the nightly version as I suggested (`3.2.1-201705231529`), and if you are using it, it is a case of overridden style, and it is fixed here https://github.com/driftyco/ionic/pull/11635

**Comment by joesleiman** [comment]
can you complete the discussion here because i'm finding more and more bugs:
https://forum.ionicframework.com/t/how-can-i-change-the-back-button-in-header-arrow-to-the-right/91591
