### ISSUE TITLE
bug: buttons do not display properly in firefox

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5037]
_From @brandyscarney on December 30, 2015 17:2_

![screen shot 2015-12-30 at 12 01 47 pm](https://cloud.githubusercontent.com/assets/6577830/12054036/25725d64-aeed-11e5-9551-a9aa08e4bc27.png)

_Copied from original issue: driftyco/ionic2#831_

**Comment by brandyscarney** [comment]
Apparently firefox does not accept `display: flex` on buttons, so this actually affects all of our buttons: https://bugzilla.mozilla.org/show_bug.cgi?id=984869

**Comment by brandyscarney** [comment]
Fixed in recent versions!
