### ISSUE TITLE
Radio with checked="true" isn't showing as checked

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5038]
_From @brandyscarney on December 30, 2015 15:58_

```
  <ion-list radio-group>
    <ion-radio value="friends" checked="true">Friends</ion-radio>
    <ion-radio value="enemies">Enemies</ion-radio>
  </ion-list>
```

_Copied from original issue: driftyco/ionic2#829_

**Comment by mhartington** [comment]
_From @brandyscarney on December 30, 2015 20:20_

The value when using `ngControl` isn't updating either.

**Comment by mhartington** [comment]
_From @brandyscarney on December 30, 2015 23:51_

I fixed the issues here but there are some Angular errors now that need to be resolved.

**Comment by brandyscarney** [comment]
No longer an issue with the item refactor here: https://github.com/driftyco/ionic/issues/5112
