### ISSUE TITLE
setRoot get blank page with "opts" binding "{animate:true}" after several transition

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5040]
_From @ronanjia on December 24, 2015 2:58_

Hi, i have a "aboutme" tab page inside a "Tabs" page, click a "logout" button in "aboutme" page would transit to a "login" page which is outside the "Tabs" page.
"logout" button will trigger action "rootNav.setRoot(Login, null, { animate: true });"
"login" button in "login" page will trigger action "this.nav.push(Tabs);"

At the first two times, it works fine, but it turns out blank page at the third time. 
But when i remove "{animate:true}" opts in "logout" action, everything just work fine.

It works in "ionic serve" all the time, but it breaks when I tested in iPhone IOS9.2

Is it a framework bug or did i write anything wrong here?

--------------------------------------------------------------------------------------------------------------
my system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.2 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.9
Xcode version: Xcode 7.2 Build version 7C68 

_Copied from original issue: driftyco/ionic2#807_

**Comment by mhartington** [comment]
_From @ronanjia on December 24, 2015 5:18_

i think it might because we cannot transit page by setting root pages once and once again, i rewrite this by using "push()" then it works fine. 

But why is the "animate" attribute to do with this?

**Comment by adamdbradley** [comment]
Should be fixed in recent versions.
