### ISSUE TITLE
slider template expression not shown

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5041]
_From @arashbi on December 24, 2015 2:47_

When I use a expression on a slider, it is invisible until I touch it, and move a bit. Then it appears.
Is it a bug or I am doing something wrong?

_Copied from original issue: driftyco/ionic2#806_

**Comment by mhartington** [comment]
_From @3dd13 on December 24, 2015 5:22_

could you post the code to reproduce the problem ?

**Comment by mhartington** [comment]
_From @msaelices on January 13, 2016 15:32_

I can reproduce the same issue with this code:

    <ion-content padding class="home">
        <ion-slides (change)="onSlideChanged($event)" index="0" loop="false" autoplay="false">
          <ion-slide>
            <h2>Slide1</h2>
          </ion-slide>
          <ion-slide>
            <h2>Slide 2</h2>
          </ion-slide>
          <ion-slide>
            <h2>Slide 3</h2>
            <ion-card *ngFor="#event of events">
                <img src="{{ event.poster }}"/>
                <ion-card-content>
                  <h2 class="card-title">
                    {{ event.name }}
                  </h2>
                </ion-card-content>
            </ion-card>
          </ion-slide>
        </ion-slides>
    </ion-content>

**Comment by brandyscarney** [comment]
@arashbi @msaelices Is this still an issue using alpha.52? I am not seeing any delay in the content appearing.

**Comment by brandyscarney** [comment]
Closing this. Please open a new issue if it still an issue: http://ionicframework.com/submit-issue/
