### ISSUE TITLE
How to add parameters in tab

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5043]
_From @zengchuan on December 20, 2015 11:23_

I want to use params in tab. How to do?
<ion-tab tab-title="Angular2"  [root]="RootComp" [params]="{}"></ion-tab>

_Copied from original issue: driftyco/ionic2#782_

**Comment by mhartington** [comment]
_From @ivanbtrujillo on December 21, 2015 10:10_

hi @zengchuan, i think here is not the right place for doubts. If you have a question, you can ask on the ionic-worldwide slack group. The ionic developers answers really fast and you can talk with other developers that are making the same things like you. Also, you have the ionic2 section on the Ionic Forum.

**Comment by brandyscarney** [comment]
@zengchuan Closing, this issue is there to add this feature: https://github.com/driftyco/ionic/issues/5172
