### ISSUE TITLE
Minifying the app.bundle.js and the css files automatically during ionic build

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5044]
_From @krz37 on December 18, 2015 8:47_

Minifying the app.bundle.js and the css files automatically would drastically reduce de size and so the load of the JS and CSS files. HTML could also be included but I guess it needs a bit too much work compared to the outcome it would bring

_Copied from original issue: driftyco/ionic2#774_

**Comment by mhartington** [comment]
_From @tlancina on December 18, 2015 18:39_

@krz37 so I'm not sure this is a good idea during development because it would take a significantly longer time to reminify the bundle on every single change.  For a good idea of the time difference, compare the running time of `webpack` and `webpack -p`, and that is without CSS minification.

What if instead there was a production CLI option that you run when you are ready to deploy your app into production that would handle minifying all of your assets?

**Comment by mhartington** [comment]
_From @krz37 on December 18, 2015 19:28_

@tlancina That's right yes. Do you think it could be included in the "ionic build --release android" for example? A CLI option could be very nice as well.
Another thing I noticed is that currently the JS is included 2 times in the APK. If I am not mistaking it is in the /build/app.bundle.js and all the .js written are kept in /app when you extract it.

**Comment by mhartington** [comment]
_From @tlancina on December 18, 2015 19:37_

@krz37 ah sorry I see the issue was for `build` specifically.  Yes I like the idea of doing it then, since the only time you would be using `build` is to release, if I understand it correctly (since `run` and `emulate` will compile for you automatically).

Regarding the code duplication, that should go away soon as we're most likely going to pull `app` out of `www`. You can take a look at https://github.com/driftyco/ionic-conference-app/issues/98 for more of the discussion there.

**Comment by mhartington** [comment]
_From @krz37 on December 18, 2015 19:40_

Thank you

**Comment by manucorporat** [comment]
One more step of the production build should be calling `enableProdMode()`.

```ts
import {enableProdMode} from 'angular2/core';

enableProdMode();
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#752
