### ISSUE TITLE
Slides are not working properly with ngFor and loop

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5045]
_From @brandyscarney on December 15, 2015 23:42_

```
<ion-slides loop="true" id="loopSlider" (slideChanged)="onSlideChanged($event)" pager>
  <ion-slide *ngFor="#slide of slides" [ngClass]="slide.class">
    {{ slide.name }}
  </ion-slide>
</ion-slides>
```

This causes the slide to go to the second slide on loop. 

_Copied from original issue: driftyco/ionic2#751_

**Comment by mhartington** [comment]
_From @3dd13 on December 21, 2015 9:29_

the DOM element generated is different for with and without ngFor.
perhaps because the DOM7 logic is executed before the ngFor rendering is done

without ngFor:
![screen shot 2015-12-21 at 17 26 46](https://cloud.githubusercontent.com/assets/223555/11927551/4a98fd46-a808-11e5-9d83-fcd0ad931245.png)


with ngFor:
![screen shot 2015-12-21 at 17 27 10](https://cloud.githubusercontent.com/assets/223555/11927556/508e77bc-a808-11e5-9d03-de47319317f0.png)

**Comment by brandyscarney** [comment]
Not seeing this in the most recent version.
