### ISSUE TITLE
<ion-toggle> & <ion-radio> do not get focus on TAB keypress

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5046]
_From @astec on December 15, 2015 0:48_

CLI v2.0.0-beta.12

_Copied from original issue: driftyco/ionic2#745_

**Comment by mhartington** [comment]
_From @brandyscarney on December 18, 2015 18:16_

I added the ability to focus them on tab press but there is still a lot of logic that needs to be added such as using up/down arrows to move between radios. Leaving this open for that. 

https://github.com/angular/angular/blob/master/modules/angular2_material/src/components/radio/radio_button.ts

**Comment by adamdbradley** [comment]
Should be fixed in recent versions
