### ISSUE TITLE
List data not fully rendered until I tap screen - alpha40

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5048]
_From @richardshergold on December 8, 2015 17:11_

I have a a weird issue with a list I am displaying (using alpha40).  I have several sections in a list, each separated by a divider.  One of my sections for example is my "On Call" category where the data comes from an array called OnCall e.g
```html
<div class="item item-divider" [class.hide]="OnCall.length == 0">
<h2>On Call</h2>
 </div>

 <ion-item-sliding *ng-for="#entry of OnCallH" #sliding-item [class.hide]="OnCall.length == 0">
    <button ion-item (click)="openPersonDetail(entry.Name)">
     <h3>{{entry.Name}}</h3>
     <p>{{entry.Customer}}</p>
  </button>
 </ion-item-sliding>
```
I'm finding that some of the lines in some sections of my list appear blank even though there should be data displaying.  The lines are displayed but the content of the button is blank.

If I tap anywhere on screen, the data suddenly appears.  Is this a known issue ?  (or am I doing something stupidly wrong?)  

I should add (just in case its relevant)  that my screen consists of two lists, each made up of several of these sections and each list is displayed depending on another value e.g at the top of each list I have an ng-for e.g:

```html
<div *ng-if="showList1==true" >
list stuff....
</div>

<div *ng-if="showList2==true" >
list stuff....
</div>
```

_Copied from original issue: driftyco/ionic2#707_

**Comment by mhartington** [comment]
_From @richardshergold on December 8, 2015 17:27_

Just tested on my Nexus 5 and it seems ok on there so if there is an issue it may well be iOS only.

**Comment by mhartington** [comment]
_From @richardshergold on December 8, 2015 18:9_

I think I may have found what causes it.  In my example above, if entry.customer is null then that seems to cause the whole line to appear blank (until I tap somewhere on screen) and then the line appears.  If I remove that line (the entry.customer line) it seems to work.  As I said above, Android is fine anywaym it just seems to be an iOS problem.  Anyway, I think I can get round it now by some checks for null values maybe.

**Comment by mhartington** [comment]
_From @brandyscarney on December 30, 2015 18:50_

Is this still an issue in the latest version, @richardshergold?

**Comment by mhartington** [comment]
_From @richardshergold on January 4, 2016 8:8_

Just back after a two week break - I need to upgrade my projects to the latest version and will try a re-rest then and let you know.  Happy New Year!  :-)

**Comment by brandyscarney** [comment]
@richardshergold Please let us know if this is still an issue with alpha.54, thanks!

**Comment by richardshergold** [comment]
That seems to be working fine on alpha.54 so I guess this can be closed.  Thanks
