### ISSUE TITLE
*ng-for is not rendering DOM but the firebase data is being called

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5049]
_From @gondar00 on December 8, 2015 11:35_

I am getting data from firebase by using the below code and i am able to create an array using the below code.

```
fetchPeopleFromFirebase(){
        Firebase fbUsers = this.fbObject.child("posts");
        fbUsers.once("value", (snapshot) => {
          if(snapshot.exists()) {
            snapshot.forEach((object) => {

              console.log("Current Post");
              console.log(object.val());
              Firebase fbUserDetails = this.fbObject.child("users");
              var createdById = object.child('createdBy/_id').val();
              console.log("Checking for : " + createdById)
              fbUserDetails.child(createdById).once("value", (snapshot) => {
                if(snapshot.exists()) {
                  console.log(snapshot.val());
                }
              });
              this.posts.push(object.val());
            });
          }
          console.log("firebase Data",this.posts);
        }
      }
```

I am storing the data in this.posts and i am trying to use it in the view like :

`*ng-for="#post of posts"`
But it does not display anything while data is being printed on the console can anyone help me?

_Copied from original issue: driftyco/ionic2#705_

**Comment by mhartington** [comment]
_From @astec on December 8, 2015 15:48_

I had similar issue #658 with Facebook API.

Try to use NgZone (*passed in constructor*): https://angular.io/docs/ts/latest/api/core/NgZone-class.html

```
 self.zone.run(() => {
                    console.log('place change');
                });
```

**Comment by gabrielclima** [comment]
Hey, bro!

Make sure that you have correct connected the DOM templates with controllers and services through App or ng-model on DOM.

You can use:
```
 ng-repeat="post in post" 
```
To show data correctly on the DOM.

**Comment by brandyscarney** [comment]
@gondar00 Is this still an issue or did you get it working?

**Comment by gondar00** [comment]
no i have got it working by using a service

**Comment by brandyscarney** [comment]
Going to close this. Thanks!
