### ISSUE TITLE
MD: inputs should have success/error highlighting

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5052]
_From @brandyscarney on December 1, 2015 16:59_

![9914f97f2de4e723b833f175785bb85c0ecbb587](https://cloud.githubusercontent.com/assets/6577830/11507625/e53d21ec-9822-11e5-8f4d-35944919247b.png)

_Copied from original issue: driftyco/ionic2#678_

**Comment by brandyscarney** [comment]
I've had people ask how to disable highlighting so I am going to add the comment here:

The success/error highlighting can be turned off via the following Sass variables:

```
$text-input-md-show-success-highlight:      false;
$text-input-md-show-error-highlight:        false;
```

and to change the colors use the following variables:

```
// Input highlight - normal
$text-input-md-highlight-color:             color($colors-md, primary);

// Input highlight - valid
$text-input-md-hightlight-color-valid:      color($colors-md, secondary);

// Input highlight - invalid
$text-input-md-hightlight-color-invalid:    color($colors-md, danger);
```

Please add any feedback on this issue, Thanks!

**Comment by Chuckv01** [comment]
The input highlighting does not fix in an ion-item with a left floated image. It overruns the width of the input and adds a border under the entire item, instead of just the input area.

<img width="312" alt="screen shot 2016-06-21 at 2 00 16 pm" src="https://cloud.githubusercontent.com/assets/1181306/16246162/dc4c77f0-37b8-11e6-9514-90146c896082.png">

**Comment by mnasyrov** [comment]
I want to suggest to add a new 'success' Sass variable to color array for a color of success/valid states. Because it is not handy to override sass variables for each platform (md, wp) to make a right color for input's valid state in case the secondary color is not green (e.g. pink or red).

**Comment by brandyscarney** [comment]
Thanks @Chuckv01, I fixed it in my latest commit so the highlight won't extend all the way to the left, unless it is the last in the list (which is the same behavior as the default border):

![screen shot 2016-07-15 at 11 36 57 am](https://cloud.githubusercontent.com/assets/6577830/16879855/7c23024c-4a80-11e6-93bb-fb6f1577eb84.png)

Also there are some breaking changes that will be in the `beta 11` release (I fixed the typos where I was using `hightlight` :flushed:): https://github.com/driftyco/ionic/commit/11a24b98aaad519a4dd3fb3d323ac6fe2cb16931

I'm still trying to find a way to make this easier to customize. I'm not sure about a `success`/`valid`/`invalid` color variable, @mnasyrov. Adding this to the color map would make it required, but it is something to consider so thanks for the suggestion. :smile:

**Comment by jabas06** [comment]
The valid highlight should be shown only when the input has the touched state. Usually we display forms that contain initial data and the highlight should not be displayed at the begging.

Repro:
http://plnkr.co/edit/RaJiIDEZRXinNuQdGwZg?p=preview
