### ISSUE TITLE
bug: searchbar keyboards stays open when clicking Cancel

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5053]
_From @brandyscarney on November 24, 2015 22:24_

Also, the input caret looks strange. Sometimes it takes the full height and sometimes it cuts off the bottom.

It seems the searchbar refocuses itself in the input after clicking on Cancel. 

_Copied from original issue: driftyco/ionic2#640_

**Comment by brandyscarney** [comment]
This isn't an issue anymore, but when the keyboard closes it shows a white space where it should be for a few seconds before disappearing.
