### ISSUE TITLE
Android input field

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5054]
_From @richardshergold on November 24, 2015 14:15_

I've no idea if this is relates to Ionic 2 but today I rolled out an Ionic 2 app to a bunch of users and although it worked fine on my Nexus 5 on two android devices the users could not type into my password field on my login screen.

I quickly added Crosswalk to the project and re-built the app. All is fine now for both users.

This is with alpha34

_Copied from original issue: driftyco/ionic2#635_

**Comment by mhartington** [comment]
_From @adamdbradley on November 24, 2015 14:36_

What version android devices were they?

**Comment by mhartington** [comment]
_From @richardshergold on November 24, 2015 14:40_

One was a Moto G2 (on my internal app store his device is listed as android XT1039)

The other is Samsung Galaxy S4 mini.  

Both running Android V19 according to my user/device log

**Comment by mhartington** [comment]
_From @richardshergold on November 25, 2015 11:10_

Interestingly I had the same issue last night from an iPhone 6 user - the app crashed when he clicked on my username field on my login page (this surprised me as I had no problems on my 6 Plur os on any iOS simulators).  Anyway, I upgraded to alpha36 this morning (from alpga34), re-built the app and re-distributed it.  It now works ok for the iPhone 6 user.

**Comment by adamdbradley** [comment]
Should be fixed in recent versions
