### ISSUE TITLE
iOS: remove border from toolbar containing segment

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5055]
_From @drewrygh on November 20, 2015 22:51_

<img width="321" alt="screen shot 2015-11-20 at 4 55 38 pm" src="https://cloud.githubusercontent.com/assets/2018508/11313984/f7e18d8a-8fa6-11e5-9ac7-a0e9a5c267c5.png">

_Copied from original issue: driftyco/ionic2#614_

**Comment by mhartington** [comment]
_From @brandyscarney on November 20, 2015 23:31_

So this is tricky because on iOS there is no border between the title and the segment in the next toolbar, but we can't use the segment to select a previous sibling in order to change it. Or...we could modify it so if the user puts a segment in a navbar with a title it moves to the next line.

![slack for ios upload-4 png](https://cloud.githubusercontent.com/assets/6577830/11508268/d7adf21a-9825-11e5-8347-05139e3129d5.jpeg)

**Comment by mhartington** [comment]
_From @adamdbradley on December 7, 2015 22:30_

Note: See if we can cleanly select and place an ion-toolbar inside of an ion-navbar

**Comment by brandyscarney** [comment]
This will be possible with the `beta 10` release. 👍
