### ISSUE TITLE
Standardize config setting names

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5056]
_From @adamdbradley on August 24, 2015 1:59_

Make sure they all make sense and follow some sort of pattern

_Copied from original issue: driftyco/ionic2#60_

**Comment by mhartington** [comment]
_From @adamdbradley on August 24, 2015 3:44_

@mlynch Thoughts on namespacing configs? Good as is?
https://github.com/driftyco/ionic2/blob/master/ionic/config/modes.ts

**Comment by mhartington** [comment]
_From @mlynch on September 30, 2015 23:39_

Since they are keys, we could do:

```js
{
  'Modal.enter'
}
```

Namespace by the class name. Otherwise, I say we just leave it as-is for now and close and move on

**Comment by mhartington** [comment]
_From @adamdbradley on October 30, 2015 16:15_

@mhartington would you be able to collect up all config names used within `config.get()` and put them in the config docs? Once we see them all lined up next to one another it might be easier to figure out what needs to be standardized.

**Comment by mhartington** [comment]
So far the basic ones from modes.ts

Action
actionSheetEnter
actionSheetLeave
actionSheetCancelIcon
actionSheetDestructiveIcon

Navigation
backButtonText
backButtonIcon
viewTransition
tabSubPages
type

Icons
iconMode

Modal
modalEnter
modalLeave

Tabs
tabbarPlacement
'tabbarIcons'
'tabbarStyle'
'preloadTabs'

Popups
popupPopIn
popupPopOut

Misc
mdRipple

**Comment by mhartington** [comment]
_From @adamdbradley on November 10, 2015 16:9_

I'm going to change mdRipple to instead be 'activator' == 'ripple'.

**Comment by mhartington** [comment]
There are still some other ones like 

```
'root',
'tabTitle',
'tabIcon'
```
for tab.ts, want those as well?

**Comment by mhartington** [comment]
_From @adamdbradley on November 10, 2015 16:11_

No for the tab attributes of root, tabTitle and tabIcon. Those are specific to just that one element.

**Comment by mhartington** [comment]
_From @brandyscarney on December 28, 2015 21:57_

I think we should rename `tabSubpages` to `tabbarSubpages` to be more consistent with 

```
tabbarPlacement
tabbarIcons
tabbarStyle
```

Or rename all the `tabbar`'s to `tabs`. Either way.

**Comment by mhartington** [comment]
_From @adamdbradley on January 7, 2016 3:51_

I think it's that `tabSubpages` just isn't a good name at all. The `tabbar` is specifically for the tabbar, such as the style and where the tabbar itself is placed. Tab subpages means that when your on the first page in tabs, and navigate to the second page, the second page goes over the tabbar. IOS doesn't do this and you always see the tabbar, but material design's second page will cover the tabbar. What's that called??

**Comment by adamdbradley** [comment]
Think we're good now
