### ISSUE TITLE
Auto-complete component 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5057]
_From @forkmind on November 19, 2015 16:30_

The [current ionic search component](http://ionicframework.com/docs/v2/components/#search) in ionic 2 allow you to search through a list in the current tab (visible to the user). It would be great to be able to search from a collection or a javascript array as well. This option would be particularly useful for API requests or for a quick search through your whole application.
I think what does this [plugin](https://github.com/guylabs/ion-autocomplete) should be a native component in ionic 2.

_Copied from original issue: driftyco/ionic2#594_

**Comment by adamdbradley** [comment]
The search bar should meet a lot of these requirements, but we can continue to improve this. I'm going to close this for now and we'll reevaluate it later.
