### ISSUE TITLE
Inputs with addons (aka input group in bootstrap)

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5058]
_From @astec on November 19, 2015 13:56_

Is it possible or planned to have inputs with addons like in bootstrap?

http://v4-alpha.getbootstrap.com/components/input-group/#button-addons

For example I want to have an "amount" input with a button that changes currency (*either dropdown or a modal*).
```
<ion-input>
  <ion-label>Amount</ion-label>
  <input type="number">
  <button right>USD</button>
</ion-input>
```
I think it is a must have. Miss them a lot.

_Copied from original issue: driftyco/ionic2#590_

**Comment by adamdbradley** [comment]
Should be working improved in latest versions
