### ISSUE TITLE
Add clear button directive 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5059]
_From @brandyscarney on November 18, 2015 23:56_

The searchbar has a clear button that shows when the user types, we could make a directive for this so the user could specify it within an `ion-input` and then it would automatically add the clear icon and clear the text when clicked.

![screen shot 2015-11-18 at 6 54 48 pm](https://cloud.githubusercontent.com/assets/6577830/11258310/fdffa792-8e25-11e5-86fe-264eed2f7d86.png)
![screen shot 2015-11-18 at 6 56 32 pm](https://cloud.githubusercontent.com/assets/6577830/11258328/1b6fbf24-8e26-11e5-9700-e3cb830414b0.png)

_Copied from original issue: driftyco/ionic2#586_

**Comment by brandyscarney** [comment]
Exists as `clearInput`, issue created to fix the fact that the input can't be focused to click it: https://github.com/driftyco/ionic/issues/6514

**Comment by msprasad9** [comment]
clearInput is working on Android devices. But On iPhone 6 with ios version 10.2.1 not clearing the text on clear button click.
