### ISSUE TITLE
feat(tabs): add ability to override text-color and highlight-color(md)

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5061]
_From @brandyscarney on November 17, 2015 21:5_

Users should be able to declare when they want the background, text, or highlight-color to be changed. See md docs: https://www.google.com/design/spec/components/tabs.html#tabs-usage

_Copied from original issue: driftyco/ionic2#570_

**Comment by mhartington** [comment]
_From @drewrygh on November 17, 2015 21:7_

Maybe we could we just have a general text-color attribute? This would be useful for other components as well.

**Comment by mhartington** [comment]
_From @drewrygh on November 17, 2015 21:10_

I also agree that highlight color should be easier to set. 

(From the components preview app):
```
body.md .cards-bg tab-highlight {
  background-color: #fff !important;
  top: 0;
}
```

**Comment by adamdbradley** [comment]
closing for now
