### ISSUE TITLE
Create a link at docs/github page to a plnkr that can be used as base for reporting issues

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5062]
_From @astec on November 17, 2015 16:38_

May I suggest you create a plunker that can be used as a base to report issues?

The link would be published in docs or at https://github.com/driftyco/ionic2-app-base and would need to be updated when new version is published to npm so people use latest to report issues.

Re: https://github.com/driftyco/ionic2/issues/546#issuecomment-157147121

_Copied from original issue: driftyco/ionic2#564_

**Comment by mhartington** [comment]
This is going to be a bit difficult. Currently the way angular bundles their code makes it difficult to create plunkr.

https://github.com/systemjs/systemjs/issues/966

**Comment by mhartington** [comment]
_From @tlancina on December 11, 2015 22:11_

So I had CORS issues trying to load the angular bundle directly, but because it also exports everything on the global `ng` we can still use the workaround mentioned in that issue.

I haven't tested it out much, but here is a barebones plunkr of the Ionic tab starter: http://plnkr.co/edit/QN00LIsdF9V1SES99Xnr?p=preview.

It's quite possible there is a better way to do this though :)

**Comment by mhartington** [comment]
_From @tlancina on January 18, 2016 18:39_

Hey there was some confusion here, Angular still also publishes a SystemJS bundle, so creating Plunkers is fine. I think this is a great idea, just not sure where we should put the link.

**Comment by mhartington** [comment]
@tlancina Is that link something we can use right now? We can probably put it in the api/component docs  as well as the issue submit page.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#473
