### ISSUE TITLE
Running 'ionic serve' fails on Windows when running on a different drive than Node install

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5064]
_From @dmastag on November 15, 2015 22:11_

This issue is different from #526 so I created a different issue to not seem to hijack that one.
Am on Windows and reactivex seems to be looking for a file in its util folder which is not present.
Any help is deeply appreciated.

```
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: D:\ionic2\MyIonic2Project\webpack.config.js

./~/@reactivex/rxjs/dist/cjs/util/root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:/Users/julian/AppData/Roaming/npm/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/buildin/module.js in D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util
resolve file
  D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist
  D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js doesn't exist
  D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts doesn't exist
resolve directory
  D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist (directory default file)
  D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js\package.json doesn't exist (directory description file)
[D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js]
[D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js]
[D:\ionic2\MyIonic2Project\node_modules\@reactivex\rxjs\dist\cjs\util\C:\Users\julian\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts]
 @ ./~/@reactivex/rxjs/dist/cjs/util/root.js 1:0-133 (CLI v2.0.0-alpha.22)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.31
Ionic CLI Version: 2.0.0-alpha.22
Ionic App Lib Version: 2.0.0-alpha.21
OS:
Node Version: v5.0.0
```

_Copied from original issue: driftyco/ionic2#528_

**Comment by mhartington** [comment]
_From @adamdbradley on November 17, 2015 16:11_

Good news is that in the next alpha release of ng2 the require statement isn't used at all: https://github.com/angular/angular/commit/bcd926adc5ef7db38508f53dcfcadc58e3386db5

**Comment by mhartington** [comment]
_From @tlancina on November 17, 2015 22:55_

Looks like this happens if your project is on a different drive than your node install on Windows.

**Comment by mhartington** [comment]
_From @dmastag on November 18, 2015 0:35_

Can confirm that is the case. Just tried using the Tabs & Tutorial Template with no problems in the `ionic serve` command.

**Comment by mhartington** [comment]
_From @Miyada2000 on November 25, 2015 0:53_

Same problem here, my Node/Ionic install is on drive C:\ and the project on E:\. Running the same project on drive C: it works.

**Comment by mhartington** [comment]
_From @nampdn on November 26, 2015 7:36_

Same problem too, So we have to create project in drive C instead?

**Comment by mhartington** [comment]
_From @jvaranam on December 11, 2015 8:25_

Same problem for me too.
If node and ionic on same drive which work fine. otherwise ionic serve through errors. 

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.40
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
OS: Windows 7 SP1
Node Version: v5.2.0

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#751
