### ISSUE TITLE
What is alternative of location change start and state change start to check for authentication.

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5066]
_From @ajaybeniwal on November 11, 2015 3:7_

In Ionic1 we used location change start or stage change start to check token and redirect to login screen if there is no token available , so how we will achieve the same thing in Ionic 2.

_Copied from original issue: driftyco/ionic2#482_

**Comment by mhartington** [comment]
_From @Luchillo on January 5, 2016 13:7_

Well, i for example have a config service with a `checkAccessToken()` method that i call in each constructor of each page, but that's a lot of boilerplate for checking if user is logged in on each page.

**Comment by brandyscarney** [comment]
@ajaybeniwal You can use the Lifecycle events attached to the Page:

>onPageLoaded - Runs when the page has loaded. This event only happens once per page being created and added to the DOM. If a page leaves but is cached, then this event will not fire again on a subsequent viewing. The onPageLoaded event is good place to put your setup code for the page.
onPageWillEnter - Runs when the page is about to enter and become the active page.
onPageDidEnter - Runs when the page has fully entered and is now the active page. This event will fire, whether it was the first load or a cached page.
onPageWillLeave - Runs when the page is about to leave and no longer be the active page.
onPageDidLeave - Runs when the page has finished leaving and is no longer the active page.
onPageWillUnload - Runs when the page is about to be destroyed and have its elements removed.
onPageDidUnload - Runs after the page has been destroyed and its elements have been removed.

http://ionic-site-staging.herokuapp.com/docs/v2/api/components/nav/NavController/

**Comment by Luchillo** [comment]
@brandyscarney i do use the access token in some of the pages as i put some info in the accessToken inside the SqLite DB, will the `onPageLoaded` will let me use that variables on the component? will it work just as the constructor or Angular2's `ngOnInit()`? if so what's the diference between them?

**Comment by lastmjs** [comment]
How can you stop the page from leaving inside of onPageWillLeave? I feel like that would be a great place to do some validation, and then stop the page transition if the validation inside of onPageWillLeave fails. How do you stop the page from leaving?
