### ISSUE TITLE
Item-Sliding should reset state when destroyed

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5067]
_From @tlancina on November 9, 2015 22:55_

If you delete a sliding item, the next touch event on any item in the same list will try and `closeOpenItem()`, which calls https://github.com/driftyco/ionic2/blob/master/ionic/components/item/item-sliding.ts#L105 and https://github.com/driftyco/ionic2/blob/master/ionic/components/item/item-sliding.ts#L141 and fails because `this.itemSlidingContent` has been removed.

You can see this in the tabs starter currently: delete a friend item and then click any of the other items in the list.

_Copied from original issue: driftyco/ionic2#478_

**Comment by manucorporat** [comment]
I think this is not longer a problem in current HEAD of 2.0, I refactored `closeOpenItem()` and I can't reproduce this issue anymore.
