### ISSUE TITLE
List of FAB

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5069]
_From @ydeshayes on November 9, 2015 13:4_

Hello,

Can you tell me if the adding the features to create a list of FAB is on the roadmap ?

https://www.google.com/design/spec/components/buttons-floating-action-button.html

![capture d ecran 2015-11-09 a 14 01 59](https://cloud.githubusercontent.com/assets/3427645/11034275/a37c57f8-86ea-11e5-9862-679032d0df5b.png)

Thanks !

_Copied from original issue: driftyco/ionic2#475_

**Comment by mhartington** [comment]
_From @adamdbradley on November 9, 2015 14:53_

Yes, they're being implemented: http://ionicframework.com/docs/v2/components/#floating-action-buttons

**Comment by mhartington** [comment]
_From @ydeshayes on November 9, 2015 15:16_

Yes the FAB buttons are, but I was talking about list of FAB (like de screenshot).

That is to say, when you click on the FAB, his behavior change and you got a list of action that pop-up.

**Comment by mhartington** [comment]
_From @adamdbradley on November 9, 2015 15:18_

Gotcha, yeah this should be added.

**Comment by mhartington** [comment]
_From @nampdn on December 9, 2015 14:18_

The list of option should have the label on the left of it like this, and have the option to enable the backdrop
![screenshot_2015-12-09-21-16-15](https://cloud.githubusercontent.com/assets/15364911/11687630/59c42720-9eba-11e5-814f-aa9f79b994ee.png)

**Comment by gxsjtu** [comment]
is the feature added to rc.0? and if yes,  please give a link to the documentation.
thanks

**Comment by jgw96** [comment]
Hello, this feature is indeed in the rc.0 release 😃 . We are currently working on updating the docs site for this release which will include docs of how to use this new feature. Expect that very soon. Thanks for using Ionic!

**Comment by danielehrhardt** [comment]
Something new here?
