### ISSUE TITLE
Do not download the base app template everytime

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5070]
_From @championswimmer on November 7, 2015 16:21_

Instead cache it in ~/.ionic/base-app-template.zip or something. It is pointless to download the template everytime I do an `ionic start`

_Copied from original issue: driftyco/ionic2#470_

**Comment by mhartington** [comment]
_From @adamdbradley on November 7, 2015 16:31_

Yeah agreed. However, we'll also need to add in logic that invalidates your cached version when an updated version is available. Maybe the process could be like:

`$ ionic start`

- Check if you have a cached version:
    - If no cached version, download the app base and cache it

- If you have a cached version:
    - Check if the cached version is the most recent
        - If the HTTP fails (no internet) then use the cached version
    - Cached version is the most recent
        - Use it, don't re-download another
    - Cached version is old
        - Download and cache this version

Checking if the cached version is the most recent is the pain. Any ideas how to speed this up? Thanks

**Comment by mhartington** [comment]
_From @championswimmer on November 7, 2015 17:43_

Have the template's own package.json and check against it ?

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#748
