### ISSUE TITLE
Example of Infinite scroll and Pull To refresh

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5072]
_From @ajaybeniwal on November 5, 2015 15:22_

Any Examples of Infinite scroll and pull to refresh in list view is it already implemented ?

_Copied from original issue: driftyco/ionic2#440_

**Comment by mhartington** [comment]
_From @adamdbradley on November 7, 2015 16:3_

Yes, just haven't documented it yet. We'll work to get that up, thanks

**Comment by mhartington** [comment]
_From @ajaybeniwal on November 11, 2015 6:35_

Hi ,

Any updates as when the docs will be updated or could you provide any link to working example

Regards,
Ajay Singh

**Comment by mhartington** [comment]
_From @drewrygh on November 12, 2015 17:42_

Hey @ajaybeniwal - we will have working demos and documentation for these components soon.

In the meantime, you could refer to our end-to-end test examples:
- [scroll/pull-to-refresh e2e](https://github.com/driftyco/ionic2/tree/master/ionic/components/scroll/test/pull-to-refresh)
- [list/infinite e2e](https://github.com/driftyco/ionic2/tree/master/ionic/components/list/test/infinite)

**Comment by mhartington** [comment]
_From @qiongshusheng on January 13, 2016 9:0_

’list/infinite e2e‘ is not work，import {ProtoViewRef, ViewContainerRef} from 'angular2/core'， ProtoViewRef is not found from 'angular2/core'

**Comment by brandyscarney** [comment]
Closing this as these components both need to be fully implemented still. Will open a new issue for documentation when they are working, thanks!
