### ISSUE TITLE
feature(ion-item-sliding): Allow item also to swipe from left to right

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5073]
_From @astec on November 1, 2015 2:46_

I want to swipe my ionic list items to both side. (i.e left-right AND right-left). It work perfectly for right-left swipe but i am not able to swipe my list item left-righ (to see buttons on left side).

Here is an example workaround: http://stackoverflow.com/a/31816296/1975086

_Copied from original issue: driftyco/ionic2#411_

**Comment by pcagica** [comment]
Do you think I can do a pull request with my answer? People keep asking me for my solution, but the way it was made it won't let people update ionic without loosing the feature.

**Comment by masimakopoulos** [comment]
+1 for this feature. Both native iOS and android support both sides swiping for items.

**Comment by thomastthai** [comment]
Did this code make it into beta? I would love to see this extended to the entire list instead of just the list-items like in Google Now.

**Comment by manucorporat** [comment]
@thomastthai @masimakopoulos @pcagica https://github.com/driftyco/ionic/pull/6686

**Comment by thomastthai** [comment]
Thank you for updating. How would I get the change locally before it is
merged into the main branch?

**Comment by thomastthai** [comment]
Also, is the code adaptable to being able to swipe the entire list left or
right in addition to the list items?

**Comment by astec** [comment]
Take into account RTL: https://github.com/driftyco/ionic/issues/5035#issuecomment-223039318

**Comment by manucorporat** [comment]
@astec @thomastthai the two way sliding will arrive in beta9, it will support having two different sets of buttons at the same time (side left/right), right side will be the default one, so expect it to be back compatible.
It has been improved a lot in general, it will behave more like a native app.
also, you will be able to subscribe to new events like (ionDrag) and (ionSwipe) and implement things like this very easily.

![jun-04-2016 18-33-17](https://cloud.githubusercontent.com/assets/127379/15801161/9c993c44-2a8c-11e6-93ca-3dbbdfea22d1.gif)

The animation below is 100% CSS, so you can customize it.

```html
    <ion-item-sliding #item>
      <ion-item>DOWNLOAD</ion-item>

      <ion-item-options (ionSwipe)="download(item)">
        <button primary (click)="archive(item)">
          <ion-icon name="archive"></ion-icon>Archive
        </button>
        <button secondary swipeable (click)="download(item)">
          <ion-icon name="download"></ion-icon>Download
        </button>
      </ion-item-options>

      <ion-item-options side="left" (ionSwipe)="unread(item)">
        <button secondary swipeable (click)="unread(item)">
          <ion-icon name="ios-checkmark"></ion-icon>Unread
        </button>
      </ion-item-options>

    </ion-item-sliding>
```

**Comment by astec** [comment]
@manucorporat, that's cool!

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/pull/6686 was merged, available in next release!

**Comment by thomastthai** [comment]
Thank you for the work you did.

**Comment by juarezpaf** [comment]
@manucorporat way to go buddy! Keep up the amazing work guys!
