### ISSUE TITLE
Finish Virtual Scrolling

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5075]
_From @mlynch on October 29, 2015 18:34_

_Copied from original issue: driftyco/ionic2#382_

**Comment by mhartington** [comment]
_From @danicomas on October 29, 2015 23:17_

List must have:
Native scroll (devices supported)
Render only the items shown as collection repeat

**Comment by mhartington** [comment]
_From @adamdbradley on October 30, 2015 0:45_

Yup, it'll use native scroll and only render the viewable ones. What we've got in a work in progress branch is looking great so far.

**Comment by adamdbradley** [comment]
dup #5418
