### ISSUE TITLE
Sample apps android performance

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5076]
_From @masimakopoulos on October 27, 2015 7:45_

Hi there, 

first of all congrats on the great work. I am checking out Ionic2 as a possible alternative to ionic1 for a large app we are going to soon be porting over from native iPhone to Android (and then cross platform). I tried quite a few samples with ionic1 and I was happy all round with the performance. In ionic 2 any sample I have tried feels really slow (unusable slow) in both android emulators (genymotion) and actual devices (Galaxy S4, OnePlus one). Especially the conference sample is slow all around (the ripple animation when touching tab buttons takes nearly 2 secs to complete) and there is quite some flicker when changing views and scrolling.

I am aware that this is alpha stage, but trying out the same sample in iPhone simulator and devices gave me great results and wanted to make sure that I am not doing something wrong on the android front. Maybe missing some web view plugin or something.

_Copied from original issue: driftyco/ionic2#349_

**Comment by mhartington** [comment]
_From @adamdbradley on October 27, 2015 13:26_

Yes we're aware of what the issues are that's causing the slowness. Should have it updated soon, thanks.

**Comment by mhartington** [comment]
_From @ehlerskon on October 27, 2015 18:46_

Hey @adamdbradley,

I am really excited about the ionic2 preview on my iPhone 6 and I also realized the slowness on Android… Do you expect an iOS-like performance on Android when you fixed the issue? Or will it stay slower on Android like ionic1 currently is compared to iOS?

**Comment by mhartington** [comment]
_From @adamdbradley on October 27, 2015 19:2_

Android animations currently in the alpha build have a few areas we’re speeding up right now. That said, iOS-like performance is a difficult one to say, because traditionally Android has been behind when compared to iOS, which is no different when comparing Android and iOS native apps. The difference has more to do with the core operating systems and hardware rather than Ionic. We are however expecting performance to be faster than v1, and with the current status of Android’s adoption it’s looking great in regards to adopting the latest versions with the fastest browser engines: https://mixpanel.com/trends/#report/android_os_adoption

**Comment by mhartington** [comment]
_From @adamdbradley on October 27, 2015 19:39_

I should also point out that we encourage everyone to use crosswalk to increase performance: http://blog.ionic.io/crosswalk-comes-to-ionic/

**Comment by mhartington** [comment]
_From @ehlerskon on October 29, 2015 8:31_

@adamdbradley , thank you very much for your detailed answer!

**Comment by mhartington** [comment]
_From @jernejc on November 19, 2015 2:6_

Also noticed this. Not sure if Crosswalk would help in my case as I'm testing on Nexus 5, Android 6 (so latest). Seems like the ripples are really slow (especially the initial one). 

The schedule list loads empty items or takes a few seconds to display them after scrolling. Is there a fade animation there? The schedule list also sometimes freezes the app completely or takes a few seconds to trigger the transition (after clicking/selecting a specific item). 

The actual page transitions look fine on the speaker page, have to wait for the ripple animation to finish though (1/2s).

Hope this helps in any way, really awesome stuff otherwise!

**Comment by mhartington** [comment]
_From @adamdbradley on November 19, 2015 2:7_

which Ionic2 version is it?

**Comment by mhartington** [comment]
_From @jernejc on November 19, 2015 2:9_

ionic@alpha
2.13.4

**Comment by mhartington** [comment]
_From @adamdbradley on November 19, 2015 2:13_

Also I should clarify I absolutely do see this as an issue and I'm sure a problem on slower devices. The ripple effect is by far the worst time for a large animation to slowly animate, but such is material design.

To get the framework's version you can look at your package.json file for something like `"ionic-framework": "2.0.0-alpha.34"`

**Comment by mhartington** [comment]
_From @jernejc on November 19, 2015 2:26_

In package.json I got:
ionic-framework: 2.0.0-alpha.34

I just cloned the repo, gave it a quick test and wanted to give some feedback on the matter. 

I also tried the starter tab app on the same device (a while back) and only got the slow ripple problem on the first go, after that it was smooth without any problem. Though that app had much less content.

The conference app definitely has and overall laggy/slow feel.

**Comment by mhartington** [comment]
_From @jgw96 on November 22, 2015 21:51_

Version: 2.0.0-alpha.34

I only seem to be having minor perf issues running he conference app on my Nexus 6 running Android 6.0, although a nexus 6 isn't exactly a good representation of overall Android perf. I've noticed that sometimes the ripples are a tiny bit slow, but almost unnoticeable.

**Comment by adamdbradley** [comment]
This has been improved in recent versions, and will be continually worked on.

**Comment by AdrianTeh** [comment]
@adamdbradley Just launched our app on Google play store. Its works out quite smoothly on Android 5.1 but very slow on Android 6. Does this have to do with the compiler that I used for the release version? Thanks.

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.3 Build version 7D175
