### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5077]
_From @brandyscarney on October 26, 2015 20:5_

Need to generate a changelog for Ionic2.

_Copied from original issue: driftyco/ionic2#341_

**Comment by mhartington** [comment]
_From @jbavari on November 7, 2015 17:41_

Personally I love [github-changelog-generator](https://github.com/skywinder/github-changelog-generator). 

The only catch is, its a Ruby tool.

There's also the nice tool from Andrew Joslin, [conventional-changelog](https://github.com/ajoslin/conventional-changelog).

I think we should just take a look at both (or other options) and just decide as a team which may be more helpful for our users to help navigate through our changes.

**Comment by mhartington** [comment]
https://github.com/semantic-release/semantic-release

https://github.com/semantic-release/semantic-release#default-commit-message-format

https://github.com/commitizen/cz-cli

Just some other tools we could also look into to manually handle the process

Benefit of commitizen is that we can automate the commit process and make it easier.

**Comment by tlancina** [comment]
Done in https://github.com/driftyco/ionic/commit/707a6aa9ba31cf80fd56e5bec40a4cbf0583b860.
