### ISSUE TITLE
docs(theming): sass variables

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5079]
_From @brandyscarney on October 13, 2015 21:47_

https://github.com/driftyco/ionic-site/tree/master/docs/v2/theming/overriding-ionic-variables

- [x] Move the JS from v2site.js to a new js file. 
- [x] Move the Sass JSON inside of this folder
- [x] Fix the tooltip styling it does not match the Bootstrap styling
- [x] Automatically move this file to the site repo ([315d4f2](https://github.com/driftyco/ionic2/commit/315d4f235a509092f7970c70841744d1f4b23a3d))
- [ ] Need to include this file in the release so we can version it

Generate the JSON file by running `gulp docs.sass-variables`

_Copied from original issue: driftyco/ionic2#281_

**Comment by mhartington** [comment]
_From @brandyscarney on October 26, 2015 20:45_

@mhartington If you could check out the tooltip styling, it looks like this:

![screen shot 2015-10-26 at 4 42 48 pm](https://cloud.githubusercontent.com/assets/6577830/10741954/ea8108fa-7c00-11e5-90e5-d059e9717767.png)

Should look like this:

![screen shot 2015-10-26 at 4 45 28 pm](https://cloud.githubusercontent.com/assets/6577830/10741969/003c3cf0-7c01-11e5-8a8f-639b74e6f113.png)

**Comment by mhartington** [comment]
Fixed via https://github.com/driftyco/ionic-site/commit/cd7387d35fe24141c5c19eb349662769bb28ef6c

**Comment by mhartington** [comment]
_From @perrygovier on December 10, 2015 16:56_

the sass var json file is now automatically generated and added to ionic-site on every commit 
315d4f235a509092f7970c70841744d1f4b23a3d

TODO: refactor the page and script to account for release versions and nightly builds

**Comment by perrygovier** [comment]
Continuing the discussion on the ionic-site repo driftyco/ionic-site@386
