### ISSUE TITLE
Yell more when there are syntax errors

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5085]
_From @tlancina on September 9, 2015 20:42_

Sometimes you only have one chance to see syntax errors, and they can get quickly lost if you make several saves.

_Copied from original issue: driftyco/ionic2#98_

**Comment by mhartington** [comment]
_From @tlancina on September 9, 2015 20:46_

Maybe make an atom plugin?

**Comment by mhartington** [comment]
_From @tlancina on September 23, 2015 16:4_

Have tscReporter report things like `console.log'derp')`instead of failing silently.

https://github.com/driftyco/ionic2/blob/master/gulpfile.js#L42

**Comment by tlancina** [comment]
I wonder if we can have LiveReload display/alert the error, I seem to remember BrowserSync having something like this.

**Comment by mhartington** [comment]
Random ideas:

livereload dash, or integrate with dev tool to format and display errors

Formater in the typescript loader to pretty-print the errors clearer in the CLI

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#747
