### ISSUE TITLE
v2: cannot gulp package

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic#5089]
running gulp package (which runs transpile.typecheck) throws following error which prevents packaging (using that for local npm link)

    ionic/components/nav/nav-router.ts(41,31): error TS2341: Property '_currentInstruction' is private and only accessible within class 'RouterOutlet'.
    ionic/components/nav/nav-router.ts(42,5): error TS2341: Property '_currentInstruction' is private and only accessible within class 'RouterOutlet'.
    ionic/components/nav/nav-router.ts(44,23): error TS2341: Property '_parentRouter' is private and only accessible within class 'RouterOutlet'.
    ionic/components/nav/nav-router.ts(82,25): error TS2346: Supplied parameters do not match any signature of call target.
    ionic/components/nav/nav-router.ts(84,7): error TS2341: Property '_parentRouter' is private and only accessible within class 'RouterOutlet'.
    ionic/components/nav/nav-router.ts(95,17): error TS2341: Property '_parentRouter' is private and only accessible within class 'RouterOutlet'.
    ionic/components/slides/slides.ts(532,19): error TS2339: Property 'update' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(535,23): error TS2339: Property 'slides' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(545,17): error TS2339: Property 'slideNext' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(552,17): error TS2339: Property 'slidePrev' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(559,24): error TS2339: Property 'activeIndex' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(566,24): error TS2339: Property 'slides' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(573,24): error TS2339: Property 'isEnd' does not exist on type '(container: any, params: any) => void'.
    ionic/components/slides/slides.ts(580,24): error TS2339: Property 'isBeginning' does not exist on type '(container: any, params: any) => void'.

- first few errors are related to accessing private variables from angular2 router outlet
- the remaining ones are because lacking of types of Swiper

**Comment by 3dd13** [comment]
the part about Swiper type is tracked in https://github.com/driftyco/ionic/issues/5008

**Comment by tlancina** [comment]
Yeah I noticed that it stopped emitting with type errors as well, but thought maybe I was crazy and it never had.

I'll look into this, in the meantime you can change https://github.com/driftyco/ionic/blob/2.0/gulpfile.js#L405 to `transpile.no-typecheck`.

**Comment by tlancina** [comment]
Should be fixed in https://github.com/driftyco/ionic/commit/266eea528cb23cda3d6ffdf151312e9f07a58dfb.
