### ISSUE TITLE
Select sometimes doesn't expand

### ISSUE THREAD

**Issue by johnmiroki** [driftyco/ionic#5090]
I have following code in my project:
```html
<select id="websiteSelect" ng-model="selectValue" ng-change="websiteDetail(null, selectValue)">
	<option ng-repeat="website in pageTagDatas.websites" value="{{website.url}}">{{website.name}}</option>
</select>
```
which translates to the following during runtime:
```html
<select id="websiteSelect" ng-model="selectValue" ng-change="websiteDetail(null, selectValue)" class="ng-pristine ng-valid ng-touched">
<!-- ngRepeat: website in pageTagDatas.websites --><option ng-repeat="website in pageTagDatas.websites" value="xxx.com" class="">xxx</option><!-- end ngRepeat: website in pageTagDatas.websites --><option ng-repeat="website in pageTagDatas.websites" value="xxx.com" class="">xxx</option><!-- end ngRepeat: website in pageTagDatas.websites --><option ng-repeat="website in pageTagDatas.websites" value="xxx.com" class="">xxx</option><!-- end ngRepeat: website in pageTagDatas.websites --><option ng-repeat="website in pageTagDatas.websites" value="xxx.com" class=""> xxx</option><!-- end ngRepeat: website in pageTagDatas.websites -->
</select>
```
Sometimes the select doesn't response to click and will not expand, some other times it works. And I haven't figured out why. Maybe someone can help? I'd appreciate your insight!

Edit:
some observation: if the state is cached, ie there are multiple selects in index.html, then only the first one works. right now I apply {cache:false} on the state and works for me. Wondering if it's a bug.

**Comment by gabrielclima** [comment]
If i correctly understanded, you have a problem with cache... On Ionic, the views save cache in the DOM's. U can use the:
```
{cache:false}
```

Or use this function:
```
 $scope.$on('$ionicView.enter', function () {
        $ionicHistory.clearCache()
    });
```
in the controller to clean cache when you enter.

**Comment by mhartington** [comment]
@johnmiroki please provide a demo

**Comment by jgw96** [comment]
Hello! Since it has been a little while since this issue had any activity i am going to close this issue for now, but feel free to reopen it if you are still experiencing this issue!
