### ISSUE TITLE
Critical bug@v2: Closing alert removes the page instead of the alert

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5092]
Hi, here's the issue, i'm showing an alert in a nested page, then while it is opened i set the root page again, this leaves the root page with z-index 10 and the alert with z-index 13.

![alert-before-error](https://cloud.githubusercontent.com/assets/9698639/12423758/1ad524aa-be9b-11e5-8c38-ff8f0c65bcdd.png)

When dismissed, be it with the button or the backdrop click event it removes the root page instead of the alert component, and set's the z-index of alert to 9:

![alert-after-error](https://cloud.githubusercontent.com/assets/9698639/12423762/1e048c6a-be9b-11e5-9a86-f31da1c952c4.png)

**Comment by Luchillo** [comment]
Seems to be an issue related to opening the alert before the transition of the page happens, if i put a timeout of 0 ms on the alert it works as expected:
>     setTimeout(() => {
      this.conf.showAlert({ title: 'Visita enviada al servidor' });
    })

**Comment by Luchillo** [comment]
Seems related to instantiating the alert before the transition, had to wrap the alert with a timeout with 5 ms timer:
>     setTimeout(() => {
      nav.present(dialog)
    }, 5)

**Comment by adamdbradley** [comment]
FYI, I'm actively working on improving the NavController, which should solve this problem

**Comment by adamdbradley** [comment]
This should be fixed in the latest versions.
