### ISSUE TITLE
bug@v2: Alert close from code hacky workaround

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5095]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Relate to https://forum.ionicframework.com/t/popup-close-from-code/38929/22.

I have quite a history with ionic popups in pre-alpha.46, then the refactor to alert using the navController, here's my toughs on the issues with it:

1. Now we need to use the navController to push the Alert to the navStack, since i have an injectable i have issues with DI with navController, now i'm forced to pass a navController instance  to the function that instantiates the Alert or use `IonicApp.getComponent('nav').present(alert)` to use the alert.

2. Unstable, when we need a popup to close before opening the next, currently we need to dismiss it by code and use timeout with 200 ms or more to let the transition go by before presenting the next one, and this time isn't an absolute value, it depends on devise performance, making it error prone and hard to control.

3. Before alpha.47 i just let the popups stack and then i just closed them all from an array storing a reference to each popup opened, but now if you let them stack a UI bug shows making the screen black behind the backdrop of the top-most alert, so i was forced to make a new component not dependent on navController.

Hope this get a revision, love the hard work you guys put on ionic 2.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Please give alert another test once beta.4 is out. There have been some fixes in beta.3, but this issue may have fixed your problems: https://github.com/driftyco/ionic/issues/5818

**Comment by iignatov** [comment]
@Luchillo I guess that the problems that you had with the alerts _(as well as these in issue #5560)_ might be resolved in `beta.3` and in such case this issue can be closed.

**Comment by jgw96** [comment]
@Luchillo Hey! Are you still having this issue in the latest version of ionic 2? (beta.5)

**Comment by privetr** [comment]
I still have the problem if I use this.nav.setRoot() but I don't have the problem if I use this.nav.push().

Here is my code : 
```
let alert = Alert.create({
            title: 'Recette enregistrée !',
            subTitle: 'Votre recette est désormais en attente de validation.',
            buttons: [
                {
                    text: 'OK',
                    handler: () => {
                        this.nav.setRoot(ListPage);
                    }
                }
            ]
        });
        this.nav.present(alert);
```

**Comment by jgw96** [comment]
Hello! @privetr @Luchillo Check out this https://github.com/driftyco/ionic/issues/6262#issuecomment-212981344 for the proper way to do this. I will close this issue for now. Thanks for using Ionic!

**Comment by privetr** [comment]
Great, thanks @jgw96 this worked well.
If it can helps someone : 

```
buttons: [
                {
                    text: 'OK',
                    handler: () => {
                        
                        //this.nav.setRoot(ListPage);
                        /*setTimeout(function () {
                            this.getNav().push(ListPage);
                        }, 500);*/
                        alert.dismiss().then(() => {
                            this.nav.setRoot(ListPage);
                        });
                        return false;
                    }
                }
            ]
```

**Comment by jgw96** [comment]
@privetr no problem at all!

**Comment by Luchillo** [comment]
@jgw96 i can't find a way to use @privetr code about `alert.dismiss().then(...)` with my codebase, since a few of my alerts open just after the page transition, thus forcing me to use timeouts with 500ms (previously 400 but in some older devices this was breaking app).

**Comment by jgw96** [comment]
@Luchillo are you still using alerts as a loading notification ?

**Comment by Luchillo** [comment]
Nop, i made a custom loading component, that's not an issue for me any more.

**Comment by Luchillo** [comment]
@jgw96 Actually i scan my whole codebase and it was very useful in the login component where a confirm triggers navigation and in most of my alerts to chain the `.then()`'s for the logic flow, however i still face issues when i need to open an Alert just after opening a page.

**Comment by jgw96** [comment]
@Luchillo Awesome glad it was helpful too you! On the alert side of things, couldn't you just open an alert in onPageDidEnter() ?

**Comment by jgw96** [comment]
or you could do 

```
  this.nav.push(coolPage).then(() => {
      //make alert
      ...
      this.nav.present(alert);
  })
```

**Comment by Luchillo** [comment]
`onPageDidEnter()`? is that native to the ionic router? i didn't saw nothing about it in Angular 2 lifecycle hooks.

**Comment by jgw96** [comment]
Hey! Sorry should have mentioned this to you before, my bad. So yeah its one of our lifecycle events that you can tie into, not an Angular 2 event, and it fires after the page has entered. So you could fire off your alert in that method like this 
```
class CoolPageComponent {
    onPageDidEnter() {
         //fire off my alert
    }
}
```
I would still recommend trying the promise method i outlined above, but `onPageDidEnter()` is pretty useful!

**Comment by Luchillo** [comment]
I'm sure this one is the hook i've missing since alpha.42, ty @jgw96.

**Comment by jgw96** [comment]
@Luchillo no problem, sorry should have mentioned it to you earlier(: feel free to give it a try and tell me if it works for you !

**Comment by Luchillo** [comment]
Actually i have used a lot of workarounds so nowhere to use it at this moment, maybe if i face this later i will remember your advise.

**Comment by jgw96** [comment]
@Luchillo sounds good! Thanks for using ionic !
