### ISSUE TITLE
Feature Request: Accordion Component

### ISSUE THREAD

**Issue by corydorning** [driftyco/ionic#510]
Loving the framework to this point and the great work being done. I was curious if there were plans to create an accordion style component for the framework. Something that allows for collapsing and expanding content.

**Comment by mnewmedia** [comment]
+1 for native integration

great stuff

**Comment by softBarbarian** [comment]
+1

**Comment by micahbule** [comment]
Why is it that in the CodePen example (http://codepen.io/ionic/pen/uJkCz) the transition for collapsing the list is quite smooth, but whenever I'm trying it out in my Ionic app, the transition is quite lagging or delayed.

I've tried to copy the exact example to my just to make sure it's not my code that's at fault, and the same code is still lagging in my browser/device.

**Comment by elhamsarikhani** [comment]
+1

**Comment by tpruthi** [comment]
+1 for ionic2

**Comment by llama-0** [comment]
Did somebody try to make 2 or more separate Accordion Lists in order to be able to press "+" in Group 1 of List 1 and leave List 2 completely untouched?

**Comment by grabtasker** [comment]
How can we achieve this in Ionic2 beta 11? Actually IonicTeam should add this component officially.
