### ISSUE TITLE
Bug : ionicon - ios-email not working in ionic2

### ISSUE THREAD

**Issue by hanung** [driftyco/ionic#5100]
ionicon - ios-email not working

![2016-01-20 8 51 21](https://cloud.githubusercontent.com/assets/2052265/12448198/b9417af4-bfb7-11e5-9f14-6bdeeeae7aab.png)

**Comment by adamdbradley** [comment]
It's just `ios-mail`

http://ionicframework.com/docs/v2/resources/ionicons/
