### ISSUE TITLE
$ionicSideMenuDelegate.isOpen not working on tablet with expose-aside-when

### ISSUE THREAD

**Issue by souly1** [driftyco/ionic#5103]
$ionicSideMenuDelegate methods isOpen/isOpenLeft/isOpenRight are returning false when actually opened on tablet due to the 'expose-aside-when' flag being used.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by souly1** [comment]
hi @jgw96 , no problem, I'll try to post an example during this week.
Thanks

**Comment by jgw96** [comment]
Thanks @souly1 ! By the way, have you gotten a chance to give Ionic 2 a try yet? If so, what do you think about it?

**Comment by souly1** [comment]
Haven't had the chance, but I'm planning to release a new app soon which I'll already be using angular 2 + ionic 2 for it, so I'll be wiser then.
Thanks :)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by souly1** [comment]
Sorry for not replying, kept putting it off.
opened a plunker with a demo at: 
http://plnkr.co/edit/1hK8Ku
wrote a bit in the read.me but basically just click on the clickMe button with a window wider than 300px.
Expected behaviour: as left side menu is open $ionicSideMenuDelegate.isOpenLeft() should return true
actual behaviour: $ionicSideMenuDelegate.isOpenLeft() return false
ask if you require further info.
Thanks!

**Comment by souly1** [comment]
hi @jgw96 , did you get to check out the demo?
you can reopen this issue as well btw....

**Comment by jgw96** [comment]
@souly1 sorry for the delay! thanks for providing the plunkr, that helps alot! I have reopened this issue as it needs more looking into. Thanks again!

**Comment by souly1** [comment]
Cool, thanks
