### ISSUE TITLE
docs: Where's the API reference?

### ISSUE THREAD

**Issue by fabriciopaulo** [driftyco/ionic#5105]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The IONIC is an interesting framework and a good tool to development, but falls on important question, the API Reference is very precarious, the params, the directives, where are these? Fórum not 's place of  discover basic thing of the platform like by example, simply hide the navbar, which the directive that i use? The documentation not says!</span>

<span is-issue-template></span>

**Comment by fabriciopaulo** [comment]
I'm currently developing a modular application, with different designs and layouts and is simply a torture develop on ionic, all you can use is necessary to look on google and with lot of dificulty!

**Comment by adamdbradley** [comment]
This is the homepage to our docs: http://ionicframework.com/docs/

And this is the more indepth API section: http://ionicframework.com/docs/api/
http://ionicframework.com/docs/api/directive/ionView/

Does that help?
