### ISSUE TITLE
bug: Ionic2 <ion-list no-lines> android issue

### ISSUE THREAD

**Issue by uiktiomasfeliz** [driftyco/ionic#5109]
<span ionic-description>**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span> 
<span ionic-webview>browser</span>
<span ionic-webview>app</span>

```
<span ionic-description>
<ion-content class="has-header">
    <ion-searchbar [(ngModel)]="searchQuery" (input)="getItems($event)"></ion-searchbar>
    <ion-list no-lines>
      <ion-checkbox primary checked="true" *ngFor="#item of items">
        <ion-item>
          <ion-avatar item-left>
            <img src="img/avatar-cher.png">
          </ion-avatar>
          <h2>{{ item }}</h2>
          <p>123 456 789</p>
        </ion-item>
      </ion-checkbox>
    </ion-list>
  </ion-content>
```

![ionic2](https://cloud.githubusercontent.com/assets/5663564/12460430/e56065d6-bfb3-11e5-9e0b-fc82628249bd.PNG)
</span>

<span is-issue-template></span></span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @uiktiomasfeliz!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=5109). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=5109)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by brandyscarney** [comment]
With the new `ion-item` updates we are making this won't be an issue anymore. Once [this issue](https://github.com/driftyco/ionic/issues/5112) is complete & released the markup will change to something like this (with your own data):

```
  <ion-list no-lines>
    <ion-list-header>
      List With Checkboxes No Lines
    </ion-list-header>

    <ion-item>
      <ion-checkbox item-left></ion-checkbox>
      <ion-avatar item-left>
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==">
      </ion-avatar>
      <ion-label>Wifi</ion-label>
    </ion-item>

    <ion-item>
      <ion-checkbox item-left></ion-checkbox>
      <ion-avatar item-left>
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==">
      </ion-avatar>
      <ion-label>Affection</ion-label>
    </ion-item>

    <ion-item>
      <ion-checkbox item-left></ion-checkbox>
      <ion-avatar item-left>
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==">
      </ion-avatar>      
      <ion-label>Home</ion-label>
    </ion-item>
  </ion-list>
```

And this will no longer be an issue, so please keep an eye on that issue! Thank you for reporting this! :)

![screen shot 2016-01-26 at 3 04 02 pm](https://cloud.githubusercontent.com/assets/6577830/12593253/1adfc5ec-c43e-11e5-8450-45a559ed3cf6.png)
![screen shot 2016-01-26 at 3 04 15 pm](https://cloud.githubusercontent.com/assets/6577830/12593252/1ade5db0-c43e-11e5-8976-a73989548dc0.png)

**Comment by uiktiomasfeliz** [comment]
Thank you brandy. Whaiting for that update!

**Comment by brandyscarney** [comment]
Sorry it looks like we never closed it. These changes were added in alpha.53 - https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-alpha53-2016-01-28

**Comment by uiktiomasfeliz** [comment]
work's verry well with alpha.53+
