### ISSUE TITLE
feat: Beautiful default scroll bar.

### ISSUE THREAD

**Issue by lastmjs** [driftyco/ionic#5110]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I use an ion-content in Ionic 2, it has the default scroll bar of the browser. In Ionic 1 that default scroll bar was beautiful by default.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Because we're using native scrolling, this is actually a bigger challenge than what v1 had to deal with. The good news is that the scrollbars look good on actual devices. I'm going to close this for now, but we'll keep toying around with a good solution so it they look good on desktop. Thanks

**Comment by darron1217** [comment]
@adamdbradley I'm waiting for this too..
Just adding some CSS would be nice :)
