### ISSUE TITLE
ion-item updates

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5112]
Running into some issues with the current setup for ion-item, ion-input, ion-checkbox, etc. I've got some thoughts on how to try to clear it all up and simplify concepts:

#### Inputs components themselves do not act as an ion-item

- `<ion-checkbox>` and similar components would only create the actual checkbox icon, it wouldn't create the entire item row and provide it's own label
- `<ion-item>` would be the only item that creates a item row
- `<ion-checkbox>` goes inside of `<ion-item>`
- It'd be possible to have multiple inputs in one item, for example, a multiple select elements to pick a date, or having an address text field and a state select dropdown in the same row (common in material design)
- `<ion-item-content>` becomes `<ion-label>`, which we already have
- `<ion-label>` would be required when using `<ion-checkbox>` and similar
- `<ion-input>` would be removed, and we'd instead provide an `<ion-text>` that could create a nested text `<input>` or `<textarea>` for them
- Each input component could still provide its own wrapper div and click handlers that would "cover" up ion-item, so ion-item doesn't need to know any of their custom logic
- All items and types of inputs would have a consistent markup
- Allows checkbox, toggle, radio, select, etc. to reuse all of ion-item's icon/avatar/thumbnail existing abilities
- Allows all of the individual components like checkbox to be used outside of the standard ion-item. Current it'd be tough to use a checkbox on desktop

```
<ion-item>
    <ion-label>Date</ion-label>
    <ion-select>
       <ion-option>January</ion-option>
       <ion-option>February</ion-option>
    </ion-select>
    <ion-select>
       <ion-option>2016</ion-option>
       <ion-option>2017</ion-option>
    </ion-select>
</ion-item>
<ion-item>
    <ion-label>Comment</ion-label>
    <ion-text type="multiline"></ion-text>
</ion-item>
<ion-item>
    <ion-label>Password</ion-label>
    <ion-text type="password"></ion-text>
</ion-item>
<ion-item>
    <ion-label>Remember Me</ion-label>
    <ion-checkbox></ion-checkbox>
</ion-item>
````

I don't think it'd take much to update this, and with snapshot already in place it wouldn't be difficult to make updates to the css either.

Thoughts? @mlynch @brandyscarney @mhartington

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic/issues/5109

**Comment by brandyscarney** [comment]
I think we should definitely lean on `ion-item`'s css instead of duplicating it in `ion-checkbox`, `ion-radio`, etc.

>*  `<ion-item-content>` becomes `<ion-label>`, which we already have
>*  `<ion-label>` would be required when using `<ion-checkbox>` and similar
>*  `<ion-input>` would be removed, and we'd instead provide an `<ion-text>` that could create a nested text `<input>` or `<textarea>` for them

yes, yes, and yes. 

> * Each input component could still provide its own wrapper div and click handlers that would "cover" up ion-item, so ion-item doesn't need to know any of their custom logic

What markup are you thinking for this?

**Comment by adamdbradley** [comment]
> What markup are you thinking for this?

The `<ion-checkbox>` element could have it's css cover up the parent `<ion-item>`, but would still be transparent. The guts to ion-checkbox is what provides the the actual checkbox icon. By default ion-checkbox would do nothing, but `ion-item ion-checkbox {...}` css would have it fill 100% of the ion-item.

**Comment by adamdbradley** [comment]
Started toying around with checkbox a little bit and seeing that it'll drastically reduce css and duplication.

**Comment by brandyscarney** [comment]
Yeah, I can see this helping a lot, it will just need to be worked out where the checkbox icon goes because right now it goes to the left but you are placing it to the right in the markup. Are we going to let them put the checkbox on the right if they want to?

**Comment by adamdbradley** [comment]
It'll put it exactly where we want it with `<ng-content select>`, and it'll show up where the platform's design would put it, which is all controlled by our CSS. So it won't matter where they place it within ion-item, it'll end up showing where it should for the platform. 

And if they really wanted to get custom, then they wouldn't use ion-item at all and can build their own custom container, and the great thing about this way is it lets them still use ion-checkbox wherever they want.

**Comment by brandyscarney** [comment]
Sounds good. :+1:

**Comment by mhartington** [comment]
Only comment is the ion-text element.

Right direction by wrapping inputs and textarea, but `ion-text` would be rather ambiguous. Like "ion-text, that's for displaying text?"

I think we can combine them into one element, but it think it should still be called ion-input. At least with that, it's close to the native name.

**Comment by adamdbradley** [comment]
Good point, `ion-text-input` or `ion-input`?

**Comment by mhartington** [comment]
I'm +1 for `ion-input`

**Comment by brandyscarney** [comment]
When I see `ion-input` I think it is going to be accepting user inputs, not displaying static text. I'm all for changing it from `ion-text` to something else but I think `ion-input` is too specific also.

**Comment by manucorporat** [comment]
@mhartington I am new contributing to ionic and to js/ts in general, but here my two cents as API designer for the [Gin project](https://github.com/gin-gonic/gin) and ios-idk and in other frameworks mainly for iOS.

- **Consistence**
`ion-checkbox`, `ion-select`,... `ion-input` or even `ion-text` looks consistent.
But ion-text-input naming does not, unless we rename all the elements.
Also, the whole new concept about ion-item, sounds a very good step forward.

- **Similar concepts share prefixes** (this helps a lot when developing in static compiled with autocomplete editors)
If I am looking for any kind and just type, ion-input and:
`ion-input-checkbox`, `ion-input-select`, `ion-input-text`, `ion-input-search`?...
this change might sound radical, but in fact all this elements are <inputs> in HTML, right?

- **Avoid confusion**: As @mhartington said, ios-text is confusing, it sounds consistent but confusing.

- **Optimize for common usage**: `<ion-input><ion-checkbox>` etc. will be used a lot.
A good API should provide a short, direct, visible (autocomplete), and no error prone way to create them.
That's why I don't like stuff like:
`<ion-input checkbox>` or `<input type="checkbox">`
and APIs that need tons of configurations in order to get started.
This kind of APIs allows very fast development with incremental improvements.

**Comment by adamdbradley** [comment]
thanks @manucorporat, sold me!

I like `<ion-input>` for text inputs, and `<ion-checkbox>` for checkbox and similar. Thanks!

**Comment by adamdbradley** [comment]
All systems go

**Comment by brandyscarney** [comment]
Reopening this until we merge it into 2.0
