### ISSUE TITLE
Request: Multiple slider range input

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic#512]
http://forum.ionicframework.com/t/multiple-range-input-request

**Comment by dracula359** [comment]
+1

**Comment by softBarbarian** [comment]
why would @dracula359 vote up on this request and then unassign @ajoslin ?

**Comment by shaoner** [comment]
Hi,

In case someone would be interested, here is a simple solution:
http://codepen.io/shaoner/pen/ZWoYgE

**Comment by jbelelieu** [comment]
+1
