### ISSUE TITLE
App loses all plugins after Ionic deploy

### ISSUE THREAD

**Issue by BojDom** [driftyco/ionic#5125]
I implemented the deploy service with an almost copy paste from the deploy docs, and that plugin works correctly except that after i update my app it doesn't find cordova.js and cordova_plugins.js 
Here the logs of before and after the deploy update

Before:

![immagine2](https://cloud.githubusercontent.com/assets/16350752/12489077/e66ac938-c06e-11e5-9f72-9ef5060b093b.png)

After: 

![immagine](https://cloud.githubusercontent.com/assets/16350752/12489078/e6780d78-c06e-11e5-8caa-368c3c0d2b9e.png)

**Comment by ericb** [comment]
@BojDom Does your index.html still include an include for cordova.js? In order for plugins to be loaded correctly, the cordova reference needs to be injected, but it is skipped if a reference is already found in the file.

**Comment by BojDom** [comment]
Thanks for the reply, i did not know about this, know deploys works fine :)
