### ISSUE TITLE
demos: add icons to action sheet buttons md

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5132]
All should have icons

![screen shot 2016-01-21 at 3 39 45 pm](https://cloud.githubusercontent.com/assets/6577830/12493863/469cdf86-c055-11e5-8534-aeed57ea3ca7.png)

**Comment by adamdbradley** [comment]
Not by default though, the user should have to manually choose which icons they want to show. We were defaulting the trash can for destructive, which was confusing if they were using destructive for something that doesn't make sense with a trash can. Better to not default anything and let them choose.

**Comment by brandyscarney** [comment]
Adam, get on Slack, I'm trying to talk you.

**Comment by brandyscarney** [comment]
@adamdbradley This issue is for the demos only - not the source code
