### ISSUE TITLE
bug: StorageEngine regression (SQLStorage broken)

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic#5136]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Breaking change between alpha 48 and alpha 51:
In commit 07953672f53c793828f29d81101b46d6b88dfafa, constructor addition in StorageEngine class breaks the functionality for SQLStorage and LocalStorage.
Now when instantiating a new Storage instance, one get the `constructor(options={}) not implemented for this storage engine` Error
> EXCEPTION: Error: constructor(options={}) not implemented for this storage engine</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Should be fixed in the next release by this: https://github.com/driftyco/ionic/pull/5141

**Comment by phavre** [comment]
Yes thanks, I've updated my sources already. By the way have you noticed that in alpha 51, if you use the translate pipe in the hello iconic, then at launch the root page's translations are empty ? Behaviour change with alpha 48

**Comment by inceptiveDipak** [comment]
@phavre i have also get same issue please help me for solving it
My ionic info:
Cordova CLI: 5.4.1
Gulp version: CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v5.3.0

Please give example of it.
Thank You !!

**Comment by sirfullTom** [comment]
get the alpha 52 and it should work.

**Comment by tairezzzz** [comment]
@sirfullTom alpha 52 doesn't help me(

**Comment by phavre** [comment]
Well, @tairezzzz, @inceptiveDipak, you just have to comment the Storage Class constructor throw error line (in the platform/storage/storage.ts file) if I remember correctly.

**Comment by phavre** [comment]
At least it is what I have done, but in checking the source I see it's already fixed. 
I'm going to upgrade to alpha 52 tonight and tell you if I still encounter the issu.

**Comment by tairezzzz** [comment]
I think I'm not updated correctly, error is gone,  anyway thx for your help @phavre!

**Comment by phavre** [comment]
Indeed, I've updated to alpha 52 (53 is on his way with breaking changes) and it works.
