### ISSUE TITLE
ion-scroll and collection-repeat not working in android

### ISSUE THREAD

**Issue by ctesene** [driftyco/ionic#5139]
We are using the ion-scroll horizontal in our application to display a list of cards (that include more details about each item in the list). The number of cards varies, but can reach up to 200. Due to the delay of databinding all of the items, we used collection-repeat to only bind a subset of the items.

This works great in IOS, but in Android the collection-repeat does not "notice" the scrolling has happened, and so the collection repeat does not "slide" the items in the DOM.

I have created a code-pen, which you can use the chrome emulator in IOS or Android to show the behavior working and not working.

https://codepen.io/ctesene/pen/MKrRpX

**Comment by mlynch** [comment]
@ctesene set `overflow-scroll="false"` on the scroll container to use JS scrolling for collection repeat

**Comment by gsanjeevkumar** [comment]
this worked in my case, but there are few questions I have around this.

during the process of development, I use "ionic serve" and on chrome browser I enable device mode 
![screen shot 2016-03-04 at 1 49 03 pm](https://cloud.githubusercontent.com/assets/637014/13536946/86b23bb6-e210-11e5-8c0a-7cbe6e03cb2a.png)


and switch between iphone and android phones to test the functionality of the app.

when I use the option of overflow-scroll="false" i have it working on the browser for Android Phones.

Now when I test the iPhone mode stopped working meaning it wont scroll. However on the mac when I use the magic mouse and use the swipe gesture up and down. the content scroll. but when I press the mouse down and Drag Up and Drag Down the scroll do not work.

Questions
1) Am I testing the right way
2) Why is this happening all of a sudden earlier the app worked fine.

I have the following setup

`
$: ionic info
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.2.1 Build version 7C1002 `
