### ISSUE TITLE
ionic huge cache size issue ?? 

### ISSUE THREAD

**Issue by boten** [driftyco/ionic#5145]
hi
i have an ionic app that has a lot of images in it (galley display of image from the web)
after installing the app the app size size in about 60 mb (i"m using crosswalk)
which is ok,
but after a few days the app size increase to almost 150 mb ???!?! 
ionic / cordova / crosswalk is saving every image that was on the app
to my device cache?
can any one help me how to limit my app cache to 2 mb or disable my app cache at all ?

here are my app details: 
ionic version 1.1.1
For android - crosswalk 12.41.296.5  (installed with : "ionic browser add crosswalk")
cordova 5.4.1

i found this issue that sound the same :
 https://github.com/driftyco/ionic/issues/3730

 they keep taking about "--disk-cache-size",
but they dont say how can i use the option --disk-cache-size :
ionic build android  --disk-cache-size ? not working 
do i need to add something to confing.xml ?

if any can help , my app size keeps on getting bigger and bigger...

**Comment by mhartington** [comment]
Add this to your config.xml

```
<preference name="xwalkCommandLine" value="--disk-cache-size" />
```

**Comment by boten** [comment]
hi
sorry to ask again but adding this line to my config.xml 
<preference name="xwalkCommandLine" value="--disable-cache-size=1024" />
has no effect at all on the cache.

i also tried these lines that didn't work - my cache keeps on getting bigger and bigger 
<preference name="xwalkCommandLine" value="--disable-cache-size=1" />
<preference name="xwalkCommandLine" value="----disk-cache-size=1" />

but no luck, android keeps ignoring my cache limits  (last check, cache = 25mb)

do i need to do anything else after adding this line to my config.xml ?
the only thing that i do after adding the line is: "ionic build android"
maybe i need to update my crosswalk as well ?

thanx
