### ISSUE TITLE
Ionic serve + jxcore-cordova plugin : jxcore not loaded in browser

### ISSUE THREAD

**Issue by picot56** [driftyco/ionic#5146]
Hello guys,

Im using Jxcore-cordova plugin to execute nodejs packages on cordova/ionic. That work fine in the app but Jxcore is not loaded when i execute in browser for test.
With Cordova, it's possible by executing : 
$ jx www/app.js

Is anyone has faced to this issue ?

**Comment by mhartington** [comment]
You've answered your own question. It's a cordova plugin. It needs to be tested on a device, and not in a browser.
