### ISSUE TITLE
bug: Using menu on the right side is broken

### ISSUE THREAD

**Issue by mikkokam** [driftyco/ionic#5147]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>Start a new v2 sidemenu project.
Change the side to the right:

    <ion-menu [content]="content" side="right">

Works OK on desktop Chrome + iOS emulation, and without emulation, when toggled by the buttons.
Dragging is broken; the menu jumps immediately on top of the content while the content drags below it.

On Android emulation, the right side menu is totally broken; toggling or dragging throws an error.
The original error seems to be:
ORIGINAL EXCEPTION: TypeError: Cannot read property 'width' of undefinedBrowserDomAdapter.logError @ 

---

EXCEPTION: Error during evaluation of "click"
app.bundle.js:32059 EXCEPTION: Error during evaluation of "click"BrowserDomAdapter.logError @ app.bundle.js:32059BrowserDomAdapter.logGroup @ app.bundle.js:32069ExceptionHandler.call @ app.bundle.js:7837(anonymous function) @ app.bundle.js:16935NgZone._notifyOnError @ app.bundle.js:17576collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17471run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17489NgZone.run @ app.bundle.js:17438outsideHandler @ app.bundle.js:30796run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
app.bundle.js:32059 ORIGINAL EXCEPTION: TypeError: Cannot read property 'width' of undefinedBrowserDomAdapter.logError @ app.bundle.js:32059ExceptionHandler.call @ app.bundle.js:7846(anonymous function) @ app.bundle.js:16935NgZone._notifyOnError @ app.bundle.js:17576collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17471run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17489NgZone.run @ app.bundle.js:17438outsideHandler @ app.bundle.js:30796run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
app.bundle.js:32059 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ app.bundle.js:32059ExceptionHandler.call @ app.bundle.js:7849(anonymous function) @ app.bundle.js:16935NgZone._notifyOnError @ app.bundle.js:17576collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17471run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17489NgZone.run @ app.bundle.js:17438outsideHandler @ app.bundle.js:30796run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
app.bundle.js:32059 TypeError: Cannot read property 'width' of undefined
    at new MenuOverlayType (app.bundle.js:59666)
    at Menu._getType (app.bundle.js:42738)
    at Menu.setOpen (app.bundle.js:42759)
    at Menu.toggle (app.bundle.js:42864)
    at MenuToggle.toggle (app.bundle.js:45615)
    at AbstractChangeDetector.ChangeDetector_GettingStartedPage_0.handleEventInternal (viewFactory_GettingStartedPage:92)
    at AbstractChangeDetector.handleEvent (app.bundle.js:13984)
    at AppView.triggerEventHandlers (app.bundle.js:18224)
    at eval (viewFactory_GettingStartedPage:440)
    at app.bundle.js:31416</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Thanks for the issue. This will be fixed in the next release. :+1:
