### ISSUE TITLE
fail to add plugin "cordova-plugin-media"

### ISSUE THREAD

**Issue by vactorlao** [driftyco/ionic#5150]
Ionic Version: 2.x

When I try to add plugin "cordova-plugin-media" then return fail:

$ sudo ionic plugin add cordova-plugin-media
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 4.0.2, failed version requirement: >=5.0.0-dev
Skipping 'cordova-plugin-media' for android
Saving plugin to package.json file

**Comment by kitkimwong** [comment]
Same problem here +1

**Comment by mhartington** [comment]
1) you should't need sudo

2) whats the output from ionic info

**Comment by vactorlao** [comment]
$ ionic plugin add cordova-plugin-media

Error occurred while adding plugin:  Error: EACCES: permission denied, open '/Users/victorlao/testplugin/plugins/fetch.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Object.exports.save_fetch_metadata (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/util/metadata.js:59:8)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/fetch.js:165:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)

**Comment by kitkimwong** [comment]
@mhartington  I am not using MAC OS but using windows. Same result.

**Comment by mhartington** [comment]
Yes, you must have started the project with sudo. 

Again, what is the output from `ionic info`

**Comment by vactorlao** [comment]
$ ionic info

Your system information:
Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2 Build version 7C68 

sudo ionic info
Password:

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by kitkimwong** [comment]
![image](https://cloud.githubusercontent.com/assets/11818108/12516570/1d52aa6a-c169-11e5-9a7d-ddb45f0730f4.png)

**Comment by vactorlao** [comment]
$ sudo ionic start plugintest --v2

One awesome Ionic app coming right up...

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing Node Modules

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Make sure to cd into your new app directory:
  cd plugintest

To run your app in the browser (great for initial development):
  ionic serve

To run on iOS:
  ionic run ios

To run on Android:
  ionic run android

To test your app on a device easily, try Ionic View:
  http://view.ionic.io

New! Add push notifications, update your app remotely, and package iOS and Android apps with the Ionic Platform!
https://apps.ionic.io/signup

New to Ionic? Get started here: http://ionicframework.com/docs/v2/getting-started

Victor:~ victorlao$ cd plugintest
Victor:plugintest victorlao$ ionic info

Your system information:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by mhartington** [comment]
Looks like your cordova-android version is out of date.

```
ionic platform add android@5.0.0
```

http://cordova.apache.org/announcements/2015/11/09/cordova-android-5.0.0.html

**Comment by kitkimwong** [comment]
Problem fixed after update to 5.0. thanks

**Comment by vactorlao** [comment]
Problem fixed.
thanks
