### ISSUE TITLE
bug: iOS Alert with long button text

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5152]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>Native AlertView buttons in iOS are listed vertically when they don't fit horizontally.</span>

<span is-issue-template></span>

Native: 
![native](https://cloud.githubusercontent.com/assets/127379/12518267/dfc5601a-c137-11e5-81eb-c8222eaf5b05.png)

Ionic:
<img width="387" alt="screen shot 2016-01-22 at 18 33 30" src="https://cloud.githubusercontent.com/assets/127379/12518293/1611da22-c138-11e5-929a-0b3cfce2d967.png">

**Comment by brandyscarney** [comment]
This was fixed by the PR from @manucorporat. Thanks!
