### ISSUE TITLE
perf: Material design - the ripple effect is too slow

### ISSUE THREAD

**Issue by qmagpie** [driftyco/ionic#5154]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Material design - the ripple effect is too slow on real devices
- observed on Tabs in [ionic-conference-app] running in ionicview app
- tested on:
    - Nexus 10 (android 5.1)
    - Sony xperia m4 aqua (android 5.0)</span>

<span is-issue-template></span>

**Comment by tomsun** [comment]
I've tested a bit on various Android devices (with Crosswalk, various v2 alphas during the last month) and get the feeling that the ripple animation speed varies, rather than being too slow all the time: i.e. decent UX IMHO most of the time, a bit slow sometimes.

**Comment by adamdbradley** [comment]
There have been some recent improvements to the ripple, would you be able to give it another shot?

**Comment by qmagpie** [comment]
Hi Adam,

 

thank you for your hint.

I have tested the ripple effect now in the newest version of the ionic-conference-app on my android phones. The ripple-effect is now fast and smooth.  It is very good news for me – because I love ionic and I am forced to use it on android phones.

Thank you.

 

Robert Paltik
