### ISSUE TITLE
bug: Spinner in stuck in Android platform

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#5156]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Ion-spinner is working good, and sometimes its just got stuck (same as ion-infinite-scroll).
Ion-refresher is always stuck.

When it's stuck you can see just a little bit of the spinner that visible, and it's not changing.

It's happening in Samsung Galaxy S4</span>

<span is-issue-template></span>

**Comment by beat-at-hartwig** [comment]
+1

**Comment by danbucholtz** [comment]
This issue is fixed and will be in the nightly build of Ionic starting tomorrow.

Thanks,
Dan
