### ISSUE TITLE
bug: Sidemenu on version 51 not animating as expected

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5157]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Change happened between 49 and 51. Moving back to 49 fixes it.

If you have a sidemenu - and select a menu item - the way that the animation of the page change is unusual (can't quite describe it, if you can't see what I mean, I will come back and describe it in more detail later) 

On 49, it behaves more like I would expect it to and would be my preferred behavour</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Agreed. Looks like a backwards animation happens and then the sidemenu closes.

**Comment by adamdbradley** [comment]
Thanks, we've made the fix here and will go out in the next release: https://github.com/driftyco/ionic/commit/f5f4169db01f6c9a7ef24249a66440eff3f14e9a

**Comment by brandyscarney** [comment]
Fixed in 2.0.0-alpha.52. Thanks for the issue!
