### ISSUE TITLE
bug: radio group checks all radios

### ISSUE THREAD

**Issue by mrameezraja** [driftyco/ionic#5158]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>While using radio group, when you click on any one item, it checks all items.

http://ionicframework.com/docs/v2/api/components/radio/RadioGroup/

Just click any item in demo you will see the results. I have also face this in my app.

i am using ionic2 latest build.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
probably a duplicate of this: https://github.com/driftyco/ionic/issues/5033 ?

**Comment by brandyscarney** [comment]
Yes, this is a duplicate of #5033
