### ISSUE TITLE
docs: Sass variables link is broken

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5160]
Since we moved the repo from ionic2 to ionic 2.0 branch the links are broken here: http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/

**Comment by mhartington** [comment]
Fixed via https://github.com/driftyco/ionic-site/commit/7ae4d6e78ea7d52c672af98b6ae49192647eec55 

Just not pushed to production. 
Closing
