### ISSUE TITLE
feat: Add `device-feedback` cordova plugin as default

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#5161]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Please, add `device-feedback` plugin as default plugin in ionic 2 app, like  the other plugins:
`cordova-plugin-device`, `cordova-plugin-console`, and etc...

It's great feature, I think it's giving life to Ionic Android apps. It's feels native.

The plugin:
https://github.com/VVelda/device-feedback

It's should be executed in every `button`, `a`, `[ng-click]`. `ion-tab` click.

Thanks.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Hey thanks for the issue, users are free to install this plugin if they wish, but as it is only for Android we won't be adding it to every Ionic project at this time.
