### ISSUE TITLE
v2 - ion-menu - could it emit events when opened/closed?

### ISSUE THREAD

**Issue by NathanWalker** [driftyco/ionic#5163]
Would be nice to subscribe to the menu's state so the UI could trigger certain extra behaviors when opened or closed. Something like:
```
this.app.getComponent('leftMenu').opened.subscribe(() => {
  // make unicorns animate out of the menu
});
this.app.getComponent('leftMenu').closed.subscribe(() => {
  // watch your UI get swallowed up by a black hole (ps: nasa wants this)
});
```

**Comment by NathanWalker** [comment]
If this is desired, I can follow up with a PR :+1:

**Comment by piotrbelina** [comment]
@NathanWalker that would be helpful

**Comment by NathanWalker** [comment]
The PR provides 1 emitter for simplicity as follows:
```
this.app.getComponent('leftMenu').state.subscribe((open) => {
  if (open) {
    // make unicorns animate out of the menu
  } else {
    // watch UI get swallowed up by a black hole (ps: Nasa is now excited)
  }
});
```

The 2.0 branch doesn't have clear testing/build instructions as far as I could find so I added an incorrect e2e test here. If someone could point me to where/how I should test this would be appreciated.
The `Menu` does not have unit tests but I could add a unit test for this as well?

**Comment by adamdbradley** [comment]
The PR looks good, but one question I have is why not have `close` and `open` events, instead of `state`? 

Also, for the unit tests I'll admit I've done a poor job getting the menu tested. Would you be able to help create unit tests for the menu? Probably the best example to emulate would be the `NavController` spec: https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/test/nav-controller.spec.ts

The `menu.spec.ts` would go in the root of this file: https://github.com/driftyco/ionic/tree/2.0/ionic/components/menu/test

`gulp karma` should be all you'll need to test the file once its added. We'd love to get help adding to our tests!

**Comment by adamdbradley** [comment]
Also as a heads up, I recently made a few minor updates to menus and gestures: https://github.com/driftyco/ionic/commits/2.0

**Comment by NathanWalker** [comment]
@adamdbradley hey thanks, I was thinking maybe 1 emitter would be simpler (and less overhead for user's to setup since opening/closing often go hand-in-hand) but whatever you think is best here.

I understand on the unit testing, n/p, I'll try to get some started with the `menu`.
Thanks for heads up, I'll make sure all is rebased before I make further corrections.

I'm out of town in Nashville at moment but wanted to get this PR started. I'll finish this up tomorrow or Thursday when I get back home to PDX.

**Comment by adamdbradley** [comment]
@NathanWalker Yeah let's go with an `open` and `close` events, as I think it'll be easier to understand and not require as much documentation reading. Thanks!

**Comment by NathanWalker** [comment]
@adamdbradley please see comments here:
https://github.com/driftyco/ionic/pull/5477#issuecomment-188911836

**Comment by adamdbradley** [comment]
@NathanWalker Sorry for the late response and not merging sooner, but the code diverged enough that it was no longer a clean merge. But the opened/closed events have been added now, thanks.
