### ISSUE TITLE
hide-nav-bar="true"  not work  to hide nav-bar with tabs in Ionic 2

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic#5164]
I only want to hide it in one of the pages excluding others.

    <ion-navbar *navbar   >
      <ion-title>Item Details</ion-title>
    </ion-navbar>
I have tried hide-nav-bar="true" but it does not work.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! In my opinion the best way to accomplish this would be to use `[hidden]` on the `<ion-navbar />` to hide it for that page.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by Rambatino** [comment]
I would like to open this again. I'm using:

``` html
	  <ion-navbar [hidden]="true" *navbar>
	    <ion-title>Login</ion-title>
	  </ion-navbar>
```

However, it doesn't hide the navigation bar.

**Comment by Rambatino** [comment]
Also, would you be able to point me in the right direction regarding: https://github.com/driftyco/ionic/blob/2.0/ionic/components/navbar/navbar.ts because it seems like it has that input property exposed.

**Comment by leohuangyi** [comment]
@jgw96 hi,if this issue will be fixed in the future? I want hide(or remove) <ion-navbar-section> in the <ion-tab> too, thank you .

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the beta 10 release.
