### ISSUE TITLE
bug: v-2 Error: constructor(options={}) not implemented for this storage engine

### ISSUE THREAD

**Issue by vadimpopa** [driftyco/ionic#5166]
"ionic": "npm:ionic-framework@2.0.0-alpha.51",

Just upgraded from 49 to 51 and LocalStorage is not working anymore
```javascript
ORIGINAL EXCEPTION: Error: constructor(options={}) not implemented for this storage engine
```
In 
```javascript
import {Storage, LocalStorage} from 'ionic/ionic';
import {AppEventBus} from './eventbus';

@Injectable()
export class AuthenticateService {
    public storage;

    constructor(private _http:Http, public eventbus: AppEventBus) {
        this.storage = new Storage(LocalStorage);
    }
```

**Comment by vadimpopa** [comment]
ah...just saw the form for submitting an issue, sorry guys, will do it next time.

**Comment by jgw96** [comment]
No problem! Would you mind upgrading your app to the latest version of Ionic 2 and seeing if you still get the same issue? Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
