### ISSUE TITLE
ionicons-icons scss error in latest

### ISSUE THREAD

**Issue by anishone** [driftyco/ionic#5167]
Hi, Thanks for creating this awesome framework. I am building an app with ionic 2. I updgraded to alpha.51 yesterday and when I do `$ionic serve`, I am getting this error now. Not sure what am I doing wrong - it used to work before. 

```
 ✗ node_modules/ionic-framework/fonts/ionicons.scss
Error: File to import not found or unreadable: ionicons-icons
       Parent style sheet: /Users/anish_muppalaneni/code/flunkapp/node_modules/ionic-framework/fonts/ionicons.scss
        on line 9 of node_modules/ionic-framework/fonts/ionicons.scss
>> @import "ionicons-icons";
   ^
```
Looking around source code, I can't find `ionicons-icons` files in fonts folder. Do I need to install something separately>
Any help would be greatly appreciated - including correcting me if I am doing something stupid.

Here is my ` $ionic info`:
```
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Not installed

```

**Comment by wulfsolter** [comment]
Yes, you need to install `ionicons`.

**Comment by mhartington** [comment]
Dup of https://github.com/driftyco/ionic/issues/5155

**Comment by anishone** [comment]
That helped. You guys are awesome. Thanks for prompt response.
