### ISSUE TITLE
perf: Ionic2 Android Emulator performance (+ crosswalk)

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5168]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>No matter the Ionic2 App I try to run on Genymotion Android (Google Nexus 5 - 5.1.0) emulator, its slow as hell, even though other apps and swiping through emulator itself runs fluidly. 

If then I install Crosswalk plugin (ionic plugin add cordova-plugin-crosswalk-webview), app starts but crashes immediately.

I suggest you remove or update the docs at http://ionicframework.com/docs/v2/resources/developer-tips/#using-genymotion-android

Genymotion Emulator with latest Alpha of Ionic2 is unusable.</span>

<span is-issue-template></span>

**Comment by wsjwong** [comment]
Genymotion is slow currently but it is still the best option out there, so I disagree to remove it from the doc.

**Comment by flintcreativestudio** [comment]
I too, am still having the App crash with Crosswalk installed. Haven't found any concrete solution that works yet. :(

**Comment by lordgreg** [comment]
@wsjwong what do you mean still the best option? Have you tried any v2 project on Genymotion? because of max 2fps you get, its unusable. The docs should be updated to reflect this issue until it is resolved.

**Comment by mhartington** [comment]
This is something that we are investigating, as we've seen this as well. Currently the best way to test an android app is always with a physical device. Genymotion is the second best option, so we'll keep it in there for now.

**Comment by masimakopoulos** [comment]
The app crashing in genymotion when crosswalk is bundled as soon as it launches is related to crosswalk and version 45 of Chrome and is documented here. https://crosswalk-project.org/jira/browse/XWALK-6141. It is resolved in later versions of crosswalk

**Comment by adamdbradley** [comment]
Going to close this for now as we're constantly working to improve performance, and there have been some good comments from others. Thanks
