### ISSUE TITLE
feat: Ionic2 Enable sourcemaps by default?

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5169]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently, when starting new Ionic2 Project, you will only see transpiled code in your browser, which means way difficult bug finding and all-in-all code reviewing. 

I suggest, enabling, by default source-maps in app with:

1. tsconfig.json: "sourceMap": true,
2. webpack.config.json: devtool: 'source-map',

If this is not possible, at least document this in v2 docs.</span>

<span is-issue-template></span>

**Comment by thaDude** [comment]
+1

**Comment by MatanYed** [comment]
+1

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#744
