### ISSUE TITLE
bug: Tabs subpage doesn't have back button

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5170]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My Project looks like this:

app.js/html
- news
- about
- list > detail-info with tabs

Of course, everytime I click any of the "root" items, I push item to stack. When going on detail-info page (which has tabs) I do that also. However, the "Back" navigation option isn't visible. 

There is also NO example showing above scenario. There's just tab example project, which, by default has 3 tabs on root and that's it.</span>

This issue has also been discussed on SO: http://stackoverflow.com/questions/34347313/ionic-2-tab-page-lost-back-navigation
<span is-issue-template></span>

**Comment by ErkoKnoll** [comment]
I have the same problem. When using serve, the back button is visible but when running on android the button is not visible but it is clickable. Icons are missing on both platforms. I also inspected the DOM on a device and the result is the following: 
<ion-icon class="back-button-icon ion-md-ion-md-arrow-back" role="img" aria-label="ion md-arrow-back"></ion-icon>
<span class="back-button-text"><span class="back-default"></span></span>

As you can see the span where "Back" text should be is empty and the back icon has double "ion-md" prefix which which should be removed.

**Comment by duzzy** [comment]
First of all, thanks you Ionic team for an awesome product! I'm still learning and created an app in v1 but the modularity of v2 seems interesting.

I can see the same behaviour using the cutePuppyPics template. The root page of a tab has a list, tapping a list item will go to a details page but the header buttons are not visible. When I change to a different tab and back to the details page, the buttons appear. So they're there, just a bit shy to present themselves.

**Comment by brandyscarney** [comment]
Going to close this as a duplicate, I know this was created first but issue #5351 was placed in a milestone. Thank you!
