### ISSUE TITLE
feat: Passing parameters to tabbed page

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5172]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Have ROOT page from which you then nav.push to details page with TABS. 

Using push as:
```
  goToDetail (detail) {
    this.nav.push(MyDetailComponent, {
      item: detail
    });
```

upper code will send item to Tabs. Docs don't have any explanation on how to Pass RootPage parameter to DetailGeneral component, which is injected from MyDetailComponent.</span>

<span is-issue-template></span>

**Comment by wsjwong** [comment]
You could check out navParam: http://ionicframework.com/docs/v2/api/components/nav/NavParams/

**Comment by lastmjs** [comment]
Is this feature requesting the ability to pass nav params into the @Page for a tab? I would really like the ability to treat tab navigation just like any other @Page navigation, since the contents of each tab are @Pages.
