### ISSUE TITLE
docs: No ion-subheader?

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5174]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There's no info about subheaders. Actually, there are a-lot of things missing in docs. Does that mean they're in TODO state or "not-going-to-happen" state?</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
They're in a TODO state. There was an issue created previously to add docs for headers/footers: https://github.com/driftyco/ionic/issues/5063

We have a components folder that holds all of the existing components: https://github.com/driftyco/ionic/tree/2.0/ionic/components

Each component has a `test` directory with sample code: https://github.com/driftyco/ionic/tree/2.0/ionic/components/toolbar

Just giving these to you for reference until we get the docs updated. :)

**Comment by mhartington** [comment]
added via https://github.com/driftyco/ionic/commit/18eb96711553b8509356c66ca10cc05bb529d8c9
