### ISSUE TITLE
bug: Canary: Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5175]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Canary on Windows 10. At start, in console.log, I get this error:

```
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)

line: undefined:1
```

This happens only in Canary on Windows 10 x64.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
How would I go about recreating this. Can this be isolated in a small example?

**Comment by lordgreg** [comment]
@mhartington 

1. create new ionic project --v2 (tabs)
2. start ionic serve
3. open it in canary and check console.log (Canary being Google Canary downloaded from here: https://www.google.com/chrome/browser/canary.html)

![capture](https://cloud.githubusercontent.com/assets/480546/12558631/e62411bc-c390-11e5-9fa4-be6d7a55bfeb.PNG)

**Comment by RafaelAdao** [comment]
I have the same problem on using the 'blank', 'tabs' and 'tutorial' templates, in anyone borwser.

Besides that, i get the message error of Ionic is not defined :/ 

```javascript
Uncaught ReferenceError: ionic is not defined

on http://localhost:8100/?ionicplatform=android line 53

<script>
ionic && ionic.Platform && ionic.Platform.setPlatform("android");
</script>
```

**Comment by AkosLukacs** [comment]
Got here after I got the same error, but without ionic. For me removing es6-shim.js solved the problem. Maybe that helps...

**Comment by 5amfung** [comment]
Happened to me in:

Google Chrome Version 49.0.2623.39 beta (64-bit)

**Comment by mhartington** [comment]
Is this still an issue?

**Comment by lordgreg** [comment]
This is still an issue.

![image](https://cloud.githubusercontent.com/assets/480546/13118433/610cd31c-d5a4-11e5-90c7-9b58d768a223.png)

Canary version `50.0.2653.1 canary SyzyASan`

**Comment by mhartington** [comment]
Odd, it's not even pointing to a compiled file. This is most likely an bug with angular and any of their polyfills. @brandyscarney, any ideas?

**Comment by brandyscarney** [comment]
I was able to reproduce it in the conference app in Canary but I don't see it affecting the app at all. Not sure about this, but I did find a few related issues that may help to find a solution.

https://github.com/blacksonic/angular2-es6-starter/issues/1
https://github.com/AntJanus/angular2-ts-starter-kit/issues/3
https://code.google.com/p/chromium/issues/detail?id=575314

Going to give this one to Tim to look into.

**Comment by Pacoup** [comment]
This seems to be an issue in es6-shim, fixed in 0.34: https://github.com/paulmillr/es6-shim/issues/403

**Comment by tlancina** [comment]
Can't upgrade es6-shim at the moment because angular2 expects `es6-shim@^0.33.3` as a peer dependency, so it will fail for npm2 users.  I'll leave this open until they update or [optionalPeerDependencies](https://github.com/npm/npm/issues/3066#issuecomment-178871868) become a thing.

Also even with the shim, `BrowserDomAdapter.prototype.setAttribute` fails for me on \*template attributes like `*ngFor`, so I'm not sure if Canary is supported at all.

**Comment by sspilleman** [comment]
I upgraded to es6-shim v0.34.4... No issues, so you can

**Comment by lordgreg** [comment]
@sspilleman what do you mean no issues? When upgrading to `0.34.4` you break the core dependency of current angular2 version that is currently being used in ionic2 project?

**Comment by samvloeberghs** [comment]
this seems to be fixed in Canary 51

**Comment by lordgreg** [comment]
Its not related to canary but with es6-shim latest version. I'm closing this ticket since the fix has been implemented. :+1:

**Comment by samvloeberghs** [comment]
@lordgreg nice to hear
It's funny cause I have this problem in my angular2 setup.
When I run it in chrome 49 it gives me that error, in Canary 51 it doesn't.

**Comment by blacksonic** [comment]
If you dont want to wait for angular2 to upgrade its dependency you can switch to core-js for shimming, itt will solve the problem till then. Also helped for me https://github.com/blacksonic/angular2-es6-starter/issues/1

**Comment by ChrisCoffey** [comment]
angular2 just landed this change.

**Comment by iBasit** [comment]
I'm trying to fix same for [our ionic2 angular2 project](http://github.com/GlobalQuran/mobile-app), but I cant manage to fix.

Can someone guide please..?  If I add polyfill.js script, it gives some other errors.
