### ISSUE TITLE
bug: ion-searchbar input doesn't take up full height in Canary

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5176]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Checking both version (iOS and Android) in Browser. Search icon overlaps "Search" string a bit for iOS, Android "back" in input has wrong padding. 

this error can be visible even in conference app and is not Project-dependant.</span>

![capture](https://cloud.githubusercontent.com/assets/480546/12538856/1caf395c-c2e5-11e5-9982-c47f68010f16.PNG)

![capture](https://cloud.githubusercontent.com/assets/480546/12538864/39e0bd0c-c2e5-11e5-8e58-c526e385171a.PNG)

<span is-issue-template></span>

**Comment by manucorporat** [comment]
I think this commit should have fixed the horizontal alignment in iOS: https://github.com/driftyco/ionic/commit/915278a29bedf24c32187f7b48065f0199131dec

but it does not explain the incorrect vertical padding...

**Comment by brandyscarney** [comment]
Are you modifying the padding on the searchbar? It should look like this by default:

![screen shot 2016-01-25 at 11 17 02 am](https://cloud.githubusercontent.com/assets/6577830/12556704/454dd6a0-c355-11e5-9d7e-65dbc91fd212.png)
![screen shot 2016-01-25 at 11 17 36 am](https://cloud.githubusercontent.com/assets/6577830/12556705/455113b0-c355-11e5-93f3-491d2a3834a8.png)

But the search icon overlapping the text was fixed by the commit mentioned by @manucorporat

**Comment by lordgreg** [comment]
Here's my html of the element:

```
<ion-navbar *navbar>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>
    {{'HEROES' | translate}}
  </ion-title>
</ion-navbar>

<ion-content class="home">
  <ion-searchbar [(ngModel)]="searchString"></ion-searchbar>
  <ion-list>
    <button ion-item *ngFor="#hero of (data | filterHeroes:searchString)" (click)="goToDetail(hero)">
      <!-- <ion-thumbnail item-left>
        <img src="{{ hero.name | championImage }}">
      </ion-thumbnail> -->
      <ion-avatar item-left>
        <img src="{{ hero.name | championImage }}">
      </ion-avatar>
      <h2>{{ hero.name }}</h2>
      <h3>{{ hero.title }}</h3>
    </button>
  </ion-list>
</ion-content>
```

Which, in browser, shows up as:

![capture](https://cloud.githubusercontent.com/assets/480546/12557151/c0a1baf4-c389-11e5-9153-3a131eba4048.PNG)

**Comment by brandyscarney** [comment]
@lordgreg Can you inspect the input element and send me a picture of the selectors? Like this:

![screen shot 2016-01-25 at 11 39 44 am](https://cloud.githubusercontent.com/assets/6577830/12557360/5add8f58-c358-11e5-8728-f61355f6f507.png)

**Comment by lordgreg** [comment]
@brandyscarney done.

![capture](https://cloud.githubusercontent.com/assets/480546/12557719/72e03b9e-c38c-11e5-98c9-3357eee31fe0.PNG)

**Comment by brandyscarney** [comment]
@lordgreg: Does the searchbar still look the same after upgrading to alpha.52?

**Comment by lordgreg** [comment]
@brandyscarney yes. After upgrading to alpha.52:

![capture](https://cloud.githubusercontent.com/assets/480546/12565020/c0d188b4-c3b2-11e5-8ac3-ee3dab35f2d4.PNG)

**Comment by brandyscarney** [comment]
Reproduced it in Canary. Looking into it now.

**Comment by brandyscarney** [comment]
This will be fixed in the next release, thanks for the issue!
