### ISSUE TITLE
Ion Tab title and icon attributes are not working

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5178]
Type: **bug**
Ionic Version: **2.x**
Platform: **serve, android**

As following the documentation when I tried to use following tab `<ion-tab [root]="detailsPage" tab-title="Details" tab-icon="person"></ion-tab>` the tab is created without a title and icon. And the produced DOM is following: `<a class="tab-button" role="tab" id="tab-0-0" aria-controls="tabpanel-0-0" aria-selected="true"><ion-icon class="tab-button-icon ion-ios-undefined" role="img" aria-label="undefined"></ion-icon><span class="tab-button-text"></span></a>`

As you can see the icon is interpreted as "undefined" and the span that should contain tab title is empty.

**Comment by brandyscarney** [comment]
The component docs are still being updated since we updated Angular. The API docs for a tab contain the proper attributes `tabIcon` and `tabTitle`:

http://ionicframework.com/docs/v2/api/components/tabs/Tab/
