### ISSUE TITLE
feat: Disable vertical scroll when menu is being dragged

### ISSUE THREAD

**Issue by andrefedalto** [driftyco/ionic#5180]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I noticed this while dragging the sidemenu diagonally: the menu would open/close and scroll at the same time and for some reason the transition becomes a bit lagged while doing this. 

The gmail app, for example, completely disable the vertical scrolling of the menu while it is being dragged to open/close. Maybe Ionic should have the same behaviour?</span>

<span is-issue-template></span>

**Comment by dkro** [comment]
I opened an identical issue almost at the same time #5181.
I will close the one I opened

**Comment by dkro** [comment]
I created a PR for restraining the menu to open and close only at a specific angle.

As for preventing horizontal scroll while opening and closing my solution was to listen to the opening event of the menu and adjust the class of the content accordingly. Maybe this behavior can be integrated directly into ionic as well.
```
<ion-menu [content]="content" (opening)=preventYScroll() id="leftMenu">
    <ion-toolbar>
        <ion-title>Menu</ion-title>
    </ion-toolbar>

    <ion-content id="menu-content" overflow-scroll='true'>
        <ion-list>
            ...
        </ion-list>
    </ion-content>
</ion-menu>
```

```javascript
    ngAfterViewInit() {
        this.content = this.app.getComponent('menu-content');
    }
    preventYScroll() {
        this.content.scrollElement.style['overflow-y'] = 'hidden';
        if(this.timer !== null) {
            clearTimeout(this.timer);
        }
        this.timer = setTimeout(() => {
            this.content.scrollElement.style['overflow-y'] = 'scroll';
        }, 300);
    }
```

**Comment by andrefedalto** [comment]
Good trick there, hopefully the pros can integrate this behaviour into v2 :)

**Comment by brandyscarney** [comment]
Closing this as the PR was merged. Please let us know if it is still an issue, thanks!
