### ISSUE TITLE
ionic-sroll bug

### ISSUE THREAD

**Issue by webmak** [driftyco/ionic#5183]
You can see your bug in your example http://ionicframework.com/docs/api/directive/ionScroll/

Working both js and native scroll and it make it not usable!!!

Here example of the video https://www.youtube.com/watch?v=tVHj1Mdx-fo&feature=youtu.be

**Comment by webmak** [comment]
Here example of the video https://www.youtube.com/watch?v=tVHj1Mdx-fo&feature=youtu.be

**Comment by webmak** [comment]
To fix it in my case I've add 

ion-content .scroll-view.scroll-y {
    overflow-x: hidden;
    overflow-y: hidden;
}

But it remove only native scroll

**Comment by webmak** [comment]
also check this 
.overflow-scroll .scroll {
    height: 100%;
    position: static;
}
in some case height: 100%; do not allow to show scrolling

**Comment by mlynch** [comment]
Appreciate the report, can't reproduce locally in a real app (might be an issue with code pen in those above).

**Comment by webmak** [comment]
The same in app on android
