### ISSUE TITLE
bug: Swipe to go back does not work on Ionic 2

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#5185]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I can not get swipe to go back to work using the start tabs project in Ionic 2. Here is what I have:

    <ion-nav id="nav" [root]="root" #content swipe-back-enabled="true"></ion-nav>

Yet the swipe to go back feature does not work after pushing onto the navigation stack:

    this.nav.push(NewPage, pageData);</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
We temporarily disabled it while the NavController was going through some refactors. We'll get it back up and running soon, thanks.

**Comment by jgatjens** [comment]
👍

**Comment by Maziar-Fotouhi** [comment]
I noticed this is not working for me on iOS (Everything worked just fine on Android):

`<ion-nav [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>`

So I just changed it to this and now it works perfectly on both platforms:

`<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>`

**Comment by anivaisu** [comment]
hi all,

I am gettint this err when Click on back button

You can't remove all the pages in the navigation stack. nav.pop() is probably called too many times. 

How to fix it 

Kindly advice me,
Thanks &Regards

**Comment by chandanch** [comment]
Hello Is this fixed in now?

**Comment by gurwinder-macrew** [comment]
Hi, is this fixed now?
I have also created issue for same [https://github.com/ionic-team/ionic/issues/12927](url)
