### ISSUE TITLE
bug: can't add button attributes dynamically

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5186]
We fixed color by adding the `color` attribute, but if they use any other button attribute it won't add the class and won't get the proper styling.

```
<button [attr.outline]="slide.title ? '' : null">test</button>
```

**Comment by adamdbradley** [comment]
These are now possible to dynamically add and remove button attributes.
```
<button outline>
<button outline="true">
<button outline="false">
<button [outline]="true">
<button [outline]="false">
```

**Comment by 4management** [comment]
The above solution does not work.
