### ISSUE TITLE
bug: Ineffective attributes on Slides Component

### ISSUE THREAD

**Issue by sjclemmy** [driftyco/ionic#5189]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Adding loop="false" doesn't stop the slides looping. Adding index="2" doesn't start the slide from the 2nd (or 3rd if zero indexed?), it always begins with the first.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
These will work in the next release. I'm not sure I like the `index` attribute though. Thinking we should stick to the same attribute names as the [Swiper API](http://www.idangero.us/swiper/api/#).

Thoughts? @adamdbradley @mhartington @drewrygh @tlancina

**Comment by tlancina** [comment]
+1 for using the same attributes as Swiper

**Comment by mlynch** [comment]
So, one idea I had from v1 is to not offer attributes at all, but instead have an `options` field that exposes the entire options of Swiper. Then we don't have to support the mapping for such a complicated component

**Comment by brandyscarney** [comment]
Ok so we are going to move forward with removing attributes and supporting passing an `options` field.

**Comment by brandyscarney** [comment]
I'm going to close this issue since all the attributes will now work (in beta.1) by passing them through the options attribute. I'll open a new issue for further slide fixing. Thanks!

**Comment by dylanvdmerwe** [comment]
Please can the [docs](http://ionicframework.com/docs/v2/components/#slides) be updated for this as they still show the use of attributes which can be confusing.

**Comment by brandyscarney** [comment]
@dylanvdmerwe done: https://github.com/driftyco/ionic-site/commit/5b8a47390ce341bb7f6868888d721a6b1f20b800

Thanks for pointing that out! I missed those earlier. Should be live on the site soon.
