### ISSUE TITLE
docs: Not all Ionicons are properly named in v2 docs

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5190]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There's a list of ionicons that Ionic v2 is currently using on next url:http://ionicframework.com/docs/v2/resources/ionicons/

I've noticed the problem with twitter, twitch, linkedin (social media icons).Those icons are not visible. 

After discussing the issue with @brandyscarney, we've found out that docs aren't updated yet since those icons should have ```logo-``` prefix.

So, this will work:
```
<ion-icon name="logo-twitter" item-left style="color: #55acee"></ion-icon>
```

</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
updated
