### ISSUE TITLE
bug: Tab Page cannot be without ion-navbar

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5191]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you have TabPage with subPages, none of them, or to be exact, TabPage cannot be without navbar. 

Please implement this ability.

ps: don't forget to pass params that have been passed to TabPage to its subPages.

Thank you :)</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Currently this is not on our roadmap.
