### ISSUE TITLE
bug: can slide item even without option buttons

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5192]
If there is a `*ngIf` on a button in `ion-item-options` then when the ngIf evaluates to false you can still swipe the item and see an empty white space:
 
``` 
<ion-item-options>
  <button favorite (click)="addFavorite(slidingItem, session)" *ngIf="segment === 'all'"> 
    Favorite
  </button>
</ion-item-options>
```

& if you put it on the `ion-item-options` you can't slide at all even when it evaluates to true.

image:

![screen shot 2016-01-25 at 3 49 55 pm](https://cloud.githubusercontent.com/assets/6577830/12564075/566b5806-c37b-11e5-953c-1f4dcf030d5f.png)

**Comment by DenysYefimenko** [comment]
I had the same problem. As temporary fix you could remove `if (!itemData.optsWidth) {` check in [item-sliding-gesture](https://github.com/driftyco/ionic/blob/2.0/ionic/components/item/item-sliding-gesture.ts) as it caches swiping offset. I'm not sure if that is correct fix to the associated bug as it may be not as efficient as possible.

**Comment by manucorporat** [comment]
@brandyscarney  I think this should be fixed in my PR. I will test more in detail.

**Comment by manucorporat** [comment]
@brandyscarney @adamdbradley before finding a fix for this, I am not sure how an empty `ion-item-options`, should behave.

**Comment by brandyscarney** [comment]
@manucorporat That makes sense actually. I swear at one point that didn't work...I imagine I would've tried that haha. I'm ok with moving the `ngIf` to the options element as a solution.
