### ISSUE TITLE
ion-refresher on Android with native scrolling - scrolling inverted

### ISSUE THREAD

**Issue by rolandoldengarm** [driftyco/ionic#5194]
When using the ion-refresher, with native scrolling enabled (which is default), in a specific usecase the scrolling is inverted.
_How to reproduce_: Pull down to refresh until the text/icon appears, but don't release. Scroll back up until the text/icon has disappeared. Now the scrolling of the list is inverted, i.e. if you scroll down with your finger, the items scroll in the opposite direction.

This cannot be reproduced on iOS.

Problem also does not occur with js scrolling.

**Comment by PerfectionCSGO** [comment]
I can reproduce this. You get rid of the inversion effect when let go of it though.
Tested on an Android 5.x device.

**Comment by crossdot** [comment]
The same behavior on my device. Tested on Android 5.x

**Comment by ramsaylee** [comment]
+1 for this.
Tested on Android 4.4

**Comment by crossdot** [comment]
+1. Tested on Android 5.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#186
