### ISSUE TITLE
bug: ion-checkbox checked attribute

### ISSUE THREAD

**Issue by mserranog** [driftyco/ionic#5195]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ion-checkbox checked attribute values "false" and "true" shows ion-checkbox checked on 2.0.0-alpha.48. checked="true" and checked="" works fine, but I don't know if it's a code or documentation bug.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Not seeing this with alpha.53: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-alpha53-2016-01-28

Please let me know if this is still an issue, thanks!
