### ISSUE TITLE
bug: TabPage & nav.pop() not working as it should

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5196]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>1. Have a child TabPage
2. Have 2 child Pages of TabPage (TabPageDetail and TabPageMoreInfo)
3. TabPage and TabPageDetail Controllers run.
4. Make button with goBack() function in TabPageDetail, which will run nav.pop()
5. Failure.
5.1 In browser: Black content shows up, but tabs stay, including nav-bar from TabPage
5.2 On Android device: Previous page appears in content, but TabPage nav and tabs stay. Previous Page is unusable (example: if we came to the listview, it isn't scrollable)
6. Basically, we're brought to TabPage from TabPageDetail, where previous page content is loaded.

how should it work?
1. nav.pop() OR nav.backToRoot (pseudo) should bring us to previous state aka. to working previous page.
2. ???
3. profit.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Would you be able to provide a simple example? I'm not really following what you're trying to do, thanks

**Comment by lordgreg** [comment]
@adamdbradley @mhartington @brandyscarney 

I've created a simple example ([github page](https://github.com/lordgreg/ionic2TabsNavigationProblem)) of the problem described above. It should be self-explanatory. 

Just clone the project with
```
git clone https://github.com/lordgreg/ionic2TabsNavigationProblem.git
```

and run `npm install`, then `ionic serve`.

**Comment by MathiasTim** [comment]
:+1: having the same issue here

**Comment by adamdbradley** [comment]
Should be fixed up now, thanks!

**Comment by lordgreg** [comment]
Dripping to try the bugfix out in the next release! 

Many thanks @adamdbradley and others from Ionic Team :+1:

**Comment by dongbe** [comment]
The navController of the previous page is overidden by the navController of the TabPage. (the bus is also present in rc1)
a tip is to save the previous navController and use it later
nav.push(TabPage,{previousNav : navCtrl});
...
navParams.data.previousNav.pop();
