### ISSUE TITLE
re-open -- ionic huge cache/data size issue ?? 

### ISSUE THREAD

**Issue by boten** [driftyco/ionic#5197]
ref to this closed issue: 
https://github.com/driftyco/ionic/issues/3730

unfortunately the fix  is not working ( testes on 3 android devices) 

sorry to ask again but adding this line to my config.xml 

preference name="xwalkCommandLine" value="--disable-cache-size=1024'"
and also i tried "zwacky" line :
preference name="xwalkCommandLine" value="--disk-cache-size=1024'"

has no effect at all on the cache/data.
again, here are my app details: 
ionic version 1.1.1
For android - crosswalk 12.41.296.5 
(do i need to update to crosswalk 14 to enable the cache/data feature ?)
cordova 5.4.1

i also tried adding these lines (to config.xml ) that didn't work - my cache/data keeps on getting bigger and bigger 
  preference name="xwalkCommandLine" value="--media-cache-size=1024" 
  preference name="xwalkCommandLine" value="--disable-cache" 
  
android keeps ignoring my cache/data limits (last check, cache = 25mb, data= 10 mb)

do i need to do anything else after adding this line to my config.xml ?
the only thing that i do after adding the line is: "ionic build android"
maybe i need to update my crosswalk as well ?

thanx

**Comment by ffabreti** [comment]
Take a look at this page https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#configure 
See release notes at the end. You should be running version 1.1.0 at least of the plugin where you can set <preference> tags on your config.xml

**Comment by boten** [comment]
hi 
i just checked and i am using 
cordova-plugin-crosswalk-webview 1.4.0

i also tired reinstalling the plugin , so now i am using 
cordova-plugin-crosswalk-webview 1.5.0
tried with regular install and with
cordova plugin add cordova-plugin-crosswalk-webview --variable XWALK_COMMANDLINE="--disk-cache-size=1024"

and my data is : 11 mb , cache: 8 mb?

my config.xml is:
preference name="webviewbounce" value="false" />
    preference name="UIWebViewBounce" value="false" />
    preference name="DisallowOverscroll" value="true" />
    preference name="android-minSdkVersion" value="10" />
    preference name="BackupWebStorage" value="none" />
    preference name="SplashScreen" value="screen" />
    preference name="SplashScreenDelay" value="8000" />
    preference name="AutoHideSplashScreen" value="false" />
    preference name="ShowSplashScreenSpinner" value="false" />
    preference name="KeyboardDisplayRequiresUserAction" value="false" />
    preference name="xwalkCommandLine" value="--disk-cache-size=1024" />


am i missing something ?

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by danbucholtz** [comment]
Hi Boten,

There are many places available for help online such as our very active [Ionic community](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA), stackoverflow, etc.

This is not an issue with the framework, so no need to keep recreating an issue.

If you're modifying your config.xml, you should make sure you are rebuilding your platform, so try `cordova prepare android`.

Give that a shot, and if you're still having issues please check out the community.

Thanks,
Dan
