### ISSUE TITLE
ionic2  ’virtual list‘ how to used,why list of infinite test can't run？

### ISSUE THREAD

**Issue by qiongshusheng** [driftyco/ionic#5199]
Why should I use virtual list has been an error , list of infinite test case also can not afford to run ?
![image](https://cloud.githubusercontent.com/assets/13391396/12666537/dff2ff44-c67c-11e5-829d-8d25c1d26f33.png)

**Comment by brandyscarney** [comment]
The virtual list is not working at this time. We will work on getting this component functional in the future, please see: https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit?usp=sharing

Thanks!
