### ISSUE TITLE
Dynamic binding problem with 3rd party library directive

### ISSUE THREAD

**Issue by anand1st** [driftyco/ionic#5200]
I've been trying to integrate angular-bootstrap-calendar with ionic framework. There seems to be some issues which I can't seem to resolve. The example is in the codepen.io link below:
http://codepen.io/anand1st/pen/OMvWmq

I notice that the events appear on the calendar when the ng-controller is in a directive that's directly above the mwl-calendar i.e. in the example above, it's the ion-content. The moment I move the ng-controller up to ion-pane directive, the events don't show up in the calendar anymore.

The author of angular-bootstrap-calendar seems to think that this is a bug with ionic framework. How can dynamic binding work correctly with the ng-controller moved to the ion-pane directive?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#187
