### ISSUE TITLE
bug: ion-toggle not working, toggleEle return NULL

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic#5202]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>See Pull Request for fix: #5201

toggleEle is NULL when calling **querySelector** on **nativeElement**

removeMoveListener throw exception **toggleEle can not be null**

Changing
```Typescript
let toggleEle = _elementRef.nativeElement.querySelector('.toggle-media');
```
to
```Typescript
let toggleEle = _elementRef.nativeElement;
```
fix the issue.</span>

<span is-issue-template></span>

**Comment by btroncone** [comment]
I just ran into this issue as well, came on to report before I saw this already opened. Good catch on fix.

**Comment by brandyscarney** [comment]
Thank you for the issue. As I added to the PR - this is no longer an issue after the item changes. We've reduced a lot of the logic for toggles, radios, checkboxes, etc. and will add a section to the changelog with the new markup. Please keep an eye on [this issue](https://github.com/driftyco/ionic/issues/5112) - once it is closed there will be a new release with the changes.
