### ISSUE TITLE
bug: Different padding for go back button in device

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5208]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>This issue is similar to https://github.com/driftyco/ionic/issues/5149 but in this case the root of the problem is different.

There is just one element (the "go back" button) that is placed differently when running in browser or in device.

Not sure what it is causing it, but I think it cannot be fixed by hard coding a new padding value, it would not fix the root of the problem.</span>

<span is-issue-template></span>

![image](https://cloud.githubusercontent.com/assets/127379/12600037/c0045224-c496-11e5-984d-ac3740f3ae6b.png)

**Comment by brandyscarney** [comment]
I'm not sure what you mean. What is it different from? The native back button?

**Comment by manucorporat** [comment]
@brandyscarney sorry.
In the left side it's safari (I can confirm that it looks the same in chrome), in the right side it is the iOS simulator running the "ionic app" through cordova. So, no native stuff today :)

The different is the vertical alignment of the "< Back" button when running the device. I wonder if this is a symptom of a more important issue, since the bar title is placed in the same position. The only affected item is the Go Back button.

**Comment by brandyscarney** [comment]
Oh ok thank you. I understand now. We'll look into this soon. :)

**Comment by manucorporat** [comment]
@brandyscarney great!
btw, here some more info I just got:
![image2](https://cloud.githubusercontent.com/assets/127379/12600425/f53c4bf6-c499-11e5-89d9-16a588258715.png)
It also looks correctly in the iOS's safari when opened as an website.
I guess it is a issue related to the status bar padding?

**Comment by manucorporat** [comment]
@brandyscarney @adamdbradley closed by https://github.com/driftyco/ionic/pull/5392
