### ISSUE TITLE
typescript import

### ISSUE THREAD

**Issue by mickael-kerjean** [driftyco/ionic#5212]
Hello,

I am trying to migrate an existing app using ionic2. 
Import using relative path is working fine but I find it painfull to write:
``` typescript
import {fooPage} from '../../../pages/foo/foo';
import {fooComponent} from '../../../shared/component/foo/foo';
// import ../../../../foo 
// ../../../../../foo
// ....
```
Would have been great to make the import using the absolute path from the project root:
``` typescript
import {fooPage} from 'app/pages/foo/foo';
import {fooComponent} from 'app/shared/component/foo/foo';
```

I'm not a webpack warrior and feel confuse about strip-sourcemap-loader and awesome-typescript-loader and the way the root is setup by default to be node_modules.

Do you have a solution for importing things properly without relative path?

By the way, it is quite impressive that you already have some material design component working as even the angular2 team doesn't have a lot in this field.
Keep up the good work!

**Comment by tlancina** [comment]
I believe you can do this by adding an alias to `app` in your resolve configuration in webpack config:
```
resolve: {
    alias: {
      'app': path.resolve('app')
    }
}
```

Going to close this, but please let us know if you're still having issues.

**Comment by mickael-kerjean** [comment]
Thank you!

**Comment by matheo** [comment]
@tlancina Is there a way to do this on ionic 2.0.0.beta.8?

**Comment by esase** [comment]
@tlancina where should I add this: 'app': path.resolve('app')??

Could you provide more details?
