### ISSUE TITLE
ion-slide pagination with more than 10 slides

### ISSUE THREAD

**Issue by andremiguelaa** [driftyco/ionic#5213]
Why can't we show pagination when have more than 10 slides?

**Comment by WHarris22** [comment]
Recently ran into this. Something seems to add the ng-hide class to the pagination container when more than 10 slides exist. 

I've resolved this for now by creating a custom pagination container, see my question / answer on stackoverflow for help http://stackoverflow.com/questions/35084310/ionic-pagination-is-being-hidden-with-new-ion-slides-component-swiper/35086395#35086395

**Comment by Elvistelefon** [comment]
it's hardcoded. check L79: 
https://github.com/driftyco/ionic/blob/master/js/angular/directive/slides.js#L79

maybe we could pass an option hide-pagination="" which accept boolean or integer for hiding after n- slides

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#188
