### ISSUE TITLE
feat: IonicLoading block element

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#5220]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>is there any way to use Ionloading to create loading spinner for an element
like this : http://malsup.com/jquery/block/#element
want to use it with http global interceptor
searched a lot but didnt find any good solution 

Found https://forum.ionicframework.com/t/ionicloading-on-specific-html-tag/15860, but recommended solution not suitable.

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
