### ISSUE TITLE
Possibly vague ionicons install advice in CHANGELOG

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5221]
Changelog for `2.0.0-alpha.51` suggests usage of: `npm install --save ionicons`
https://github.com/driftyco/ionic/commit/55f156366f282089112b460b0848e8ecf46a920d

That command verbatim currently produces (node v4.2.3, npm 2.14.7)
```
# npm install --save ionicons
ionicons@2.0.1 node_modules/ionicons
```
```
 ✗ node_modules/ionic-framework/fonts/ionicons.scss
Error: File to import not found or unreadable: ionicons-icons
       Parent style sheet: /path/to/project/node_modules/ionic-framework/fonts/ionicons.scss
        on line 9 of node_modules/ionic-framework/fonts/ionicons.scss
>> @import "ionicons-icons";
   ^
```

Had better luck by pinning like so: `npm install --save ionicons@3.0.0-alpha.3`, based on https://github.com/driftyco/ionic/commit/7eed4c91bfd8f4b6f10a8ff106fa8fc3fe50b86b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21

**Comment by tlancina** [comment]
If you run `npm view ionicons dist-tags` what does it output for you?

**Comment by tomsun** [comment]
@tlancina 
```
root@2cb5de57dd34:/opt/test# ls -al
total 8
drwxr-xr-x 2 root root 4096 Jan 27 20:26 .
drwxr-xr-x 7 root root 4096 Jan 27 20:27 ..
root@2cb5de57dd34:/opt/test# npm view ionicons dist-tags
{ latest: '3.0.0-alpha.3' }
root@2cb5de57dd34:/opt/test# npm install ionicons
ionicons@2.0.1 node_modules/ionicons
root@2cb5de57dd34:/opt/test# grep version ./node_modules/ionicons/package.json 
  "version": "2.0.1",
root@2cb5de57dd34:/opt/test# npm --version
2.14.7
root@2cb5de57dd34:/opt/test# node --version
v4.2.3
```

**Comment by tlancina** [comment]
Alright I admit I was skeptical, but I can reproduce, just installed v4.2.3 on nvm and I get the same.

Unless I'm mistaken, this is an npm bug right? Should it not install latest? Also behavior shouldn't change between minor versions:
![image](https://cloud.githubusercontent.com/assets/804331/12627490/b9433a3c-c503-11e5-9de5-47cfaaa71c84.png)

**Comment by tlancina** [comment]
I'm almost positive this is a bugged version of npm, installing `npm install -g npm@latest-2` (which is 2.14.15) also installs latest.

Going to close as not a bug, but if you have reason to believe this is not the case, please feel free to comment further.

**Comment by tlancina** [comment]
Also updated CHANGELOG just in case :)

**Comment by tomsun** [comment]
@tlancina thanks!

(Confirming that `npm@latest-2` picks ionicons `3.0.0-alpha.3` by default for me too)
