### ISSUE TITLE
bug: ion-badge doesn't get proper badge-default color

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5222]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Make <ion-badge> with default color:

```
<ion-badge default>1337</ion-badge>
```
or
```
<ion-badge class="badge-default">1337</ion-badge>
```

Expected color: default, blue.
Current color: gray

Nay!</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This is a design choice that we have made.

**Comment by brandyscarney** [comment]
Updated badge to use the primary color by default. Thanks for the issue!
