### ISSUE TITLE
bug: How to apply md sytle to all platforms by default.

### ISSUE THREAD

**Issue by vedhagiri** [driftyco/ionic#5227]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have tried to apply "md" style to all my platforms. but the configuration is not applied when I have run the application in web. Please guide me with some code samples.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Here is a link to some documentation that might help you with this issue: http://ionicframework.com/docs/v2/api/config/Config/ 

As you can see all you have to do is add 
`config: {
    mode: 'md'
  }` to your `@App` and you will be ready to go!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
