### ISSUE TITLE
bug: ionic build

### ISSUE THREAD

**Issue by aadi160** [driftyco/ionic#5228]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>when i m start build with command
ionic build android
[Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.]
ERROR building one of the platforms: Error: /var/www/html/TabApp/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /var/www/html/TabApp/platforms/android/cordova/build: Command failed with exit code 2</span>

<span is-issue-template></span>

**Comment by rolandoldengarm** [comment]
I think the error is quite obvious? You need to set ANDROID_HOME environment variable, and update PATH to point to your android-sdk installation.

**Comment by jgw96** [comment]
Hello! As its been a while since there was any activity on this issue i will be closing it. But, feel free to reopen it if your still having the issue!
