### ISSUE TITLE
repo url in package.json is currently outdated in 2.0 branch

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5230]
`"url": "https://github.com/driftyco/ionic2.git"`
https://github.com/driftyco/ionic/blob/eb03159d088965d60db027a13a5c0008e3d7f1a6/package.json#L8

**Comment by tlancina** [comment]
Thanks, this was fixed in https://github.com/driftyco/ionic/commit/c085f6f75bebfafb1cded310a273405c20308bfb.
