### ISSUE TITLE
Install from source does not replace a preexisting npmjs.com-version, due to package name mismatch (v2)

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5231]
Wanted to test a change in alpha 53, which is not available via npm repo and tried installing directly from github instead:

Precondition:
```
$ npm install ionic-framework
ionic-framework@2.0.0-alpha.51 node_modules/ionic-framework
...
```

Reproduction steps:
```
$ npm install https://github.com/driftyco/ionic.git#2.0
ionic2@2.0.0-alpha.52 node_modules/ionic2
...
```

Result:
```
$ ls node_modules/
...
drwxr-xr-x 1 1000 staff  646 Jan 28 12:32 ionic2
drwxr-xr-x 1 1000 staff 1156 Jan 28 12:30 ionic-framework
...
```

Using `ionic2` as directory name instead of the normal `ionic-framework` like that is perhaps fine - a few observed side-effects:
- `npm install` fails in the described scenario, unless preceded by `npm uninstall ionic-framework`, since the stale version left behind due to the name mismatch, has an older version of Angular as peer dependency...
- a few paths in `ionic.config.js` and `webpack.config.js` has to be updated from `ionic-framework` to `ionic2`

The directory name seems to be dictated by `name` in package.json (tested locally with `npm install /local/path/to/ionic`) - perhaps different rules apply when installing from npmjs.com? 

```
diff --git a/package.json b/package.json
index 1cb2d21..5011a2f 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "private": "true",
-  "name": "ionic2",
+  "name": "ionic-framework",
   "version": "2.0.0-alpha.52",
   "license": "Apache-2.0",
   "repository": {
```

I.e. I believe changing package.json accordingly would make this workflow more seamless. Unclear to me though what other side-effects changing the name has.

Whether this suggestion makes sense probably also depends om whether you plan to use `ionic-framework` or `ionic2` as the npm package name in the future... :-)

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#758
