### ISSUE TITLE
Cordova camera plugin doesn't work with $ionicActionSheet

### ISSUE THREAD

**Issue by victorprevsis** [driftyco/ionic#5232]
When I'm trying to use Cordova camera plugin in buttonClicked function within $ionicActionSheet this doesn't work.
This is my code:
`$ionicActionSheet.show({
			buttons: [
				{ text: 'Camera' }
			],
			titleText: 'Subir evidencia',
			buttonClicked: function(index) {
		    if (window.cordova) {
		      var options = {
		        quality: 75,
		        destinationType: Camera.DestinationType.DATA_URL,
		        sourceType: Camera.PictureSourceType.CAMERA,
		        allowEdit: true,
		        encodingType: Camera.EncodingType.JPEG,
		        targetWidth: 300,
		        targetHeight: 300,
		        popoverOptions: CameraPopoverOptions,
		        saveToPhotoAlbum: false
		      };
		      var base64 = $cordovaCamera.getPicture(options).then(function (imageData) {
		        return "data:image/jpeg;base64," + imageData;
		      }, function (err) {
		        console.log({ title: 'Error!', template: 'Problemas al conectar con la camara!'});
		        console.log({ title: 'Error!', template: err});
		      });
		    } else {
		        console.log({ title: 'Error!', template: 'Cordova initializing problem!'});
		    }
			}
		});`

this gives to me the following message 'Camera cancelled'

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue i will be closing it for now. Thanks for using ionic!

**Comment by cordiojs** [comment]
i facing this problem when i inspect it in browser
Object {title: "Error!", template: "Cordova initializing problem!"}
