### ISSUE TITLE
ngClick on toggle causes gray flash

### ISSUE THREAD

**Issue by bookcasey** [driftyco/ionic#5234]
If you click a toggle with `ng-click`, it adds the `activated` class, which causes a gray background and a darker border. I don't think it looks very good, but is it intentional?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1432129/12650608/0c6278b8-c5a9-11e5-8f38-b3cc14a3815b.gif)

Reduced test case on [Codepen](http://codepen.io/bookcasey/pen/gPzKeW?editors=1010) (Basically `<ion-toggle ng-click="">Test</ion-toggle>`)

This is my first time contributing to Ionic, so I don't know what the most idiomatic way to solve this would be. In my project I'm using:

```
.item-toggle.activated {
  @include item-style($item-default-bg, $item-default-border, $item-default-text);
}
```

**Comment by bookcasey** [comment]
https://github.com/driftyco/ionic/pull/5235

**Comment by bookcasey** [comment]
#5235

**Comment by bookcasey** [comment]
Pull request to solve this the way I did: #5235

**Comment by adamdbradley** [comment]
You're css to fix this for your app looks good, but this is intended and the many other apps may be expecting this. So I'd recommend adding the css to just your app. Thanks
