### ISSUE TITLE
bug[Ionic2]: Views Destroyed Too Earlier when Using Navigation

### ISSUE THREAD

**Issue by barbatus** [driftyco/ionic#5236]
Main page consists of the left menu and some list of items;
I click on an item and it starts sliding to the next page w/o problem;
suddenly the previous one pops up and overlays the current (see the gif below)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2824096/12651624/db5ed858-c619-11e5-944a-7b0ec6af46a9.gif)

HTML markup at the end:
<img width="763" alt="screen shot 2016-01-29 at 12 01 02 am" src="https://cloud.githubusercontent.com/assets/2824096/12652155/13e1754e-c61c-11e5-8e6c-78e57d244c82.png">

As you can see, there are two pages: previous one with z-index 10 and the current one with z-index 11. But the current page has for some reason the ion-content's style set to `transform: translateX(99.5%)`, that's why it's not shown.

It's caused by the destroyed view. Trying to get back I get an exception: "can't destroy already destroyed view".

Here is a repo with the [demo](https://github.com/barbatus/ionic2-meteor/tree/master/examples/parties)

Thanks for any help in advance!

**Comment by adamdbradley** [comment]
Is this only an issue in iOS, do you see this on chrome? What version of the framework are you using?

**Comment by barbatus** [comment]
@adamdbradley it works perfectly well on chrome. It's only Cordova-related.
Cordova version used - 3.9.2.

**Comment by slippyC** [comment]
@barbatus This is exactly what I was talking about under your project.  What seems to be happening is some of the views are getting destroyed to early.  There is an error thrown in Chrome, it just recuperates from the issue.  If you try it on Android, you will be stuck in one of your views.  The only way you can get out of it is to click your menu, but then you only will have choice of "Parties Form" and "Login".  You want be able to get back to the "Parties List".

**Comment by barbatus** [comment]
@slippyC Yes, it's likely related. You said there is an issue about that. Can you please reference it here?

**Comment by slippyC** [comment]
It is related to issue #5277. Still exists in alpha 53 though...

**Comment by barbatus** [comment]
The reason was in the animation polyfill.

**Comment by slippyC** [comment]
Sorry bud, have been really busy.  I do IT work in the day and have been working on Web App at night when get off work.  I'm glad you figured out what was going on.  

Thanks again for the extra work you put into this project!

Chris
