### ISSUE TITLE
Can't log into forum

### ISSUE THREAD

**Issue by Matt2012** [driftyco/ionic#5237]
**Error updating information, contact site admin**

**Comment by Matt2012** [comment]
Still having this issue  - is anyone else - tried multiple computers / browsers

**Comment by jgw96** [comment]
Hello! Are you still experiencing this issue?

**Comment by Matt2012** [comment]
yes

Error updating information, contact site admin

**Comment by jgw96** [comment]
@Matt2012 would you mind shooting an email to Mike@ionic.io and tell him whats going on? He will be able to help you (:

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by Matt2012** [comment]
Still having issue

**Comment by jgw96** [comment]
@Matt2012 Sorry about that, reopening this issue now. Did you get a chance to shoot Mike an email?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by Matt2012** [comment]
The issue has not gone away. But I have created a new account that I can login with. This is not ideal because the other account is the one I use with ionic.io

**Comment by jgw96** [comment]
@Matt2012 Sorry to hear that. Did you ever get a chance to shoot an email to Mike@ionic.io?

**Comment by Matt2012** [comment]
yes
