### ISSUE TITLE
Floating label overlapping input with value

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5238]
[http://localhost:8000/dist/e2e/input/form-inputs/](http://localhost:8000/dist/e2e/input/form-inputs/)

![screen shot 2016-01-28 at 3 01 10 pm](https://cloud.githubusercontent.com/assets/6577830/12657195/136afeec-c5d0-11e5-8a57-02376cf211fe.png)

**Comment by adamdbradley** [comment]
Fixed https://github.com/driftyco/ionic/commit/181a07024e8ee602fd989e36b41e9b86ca537b90
