### ISSUE TITLE
bug: item-right class no more interpreted in ion-item

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic#5240]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I had some list items with either ion-badge tag or ion-icon tag set with item-right attribute. Since alpha 53 they are no longer right aligned.</span>

<span is-issue-template></span>

![image](https://cloud.githubusercontent.com/assets/16475287/12660695/4db0d500-c615-11e5-8613-095863d0fc3c.png)

**Comment by brandyscarney** [comment]
What does your markup look like? I am not seeing this using the following markup switching between `ion-badge` and `ion-icon`:

```
<ion-item-sliding *ngFor="#session of group.sessions" #slidingItem [attr.track]="session.tracks[0] | lowercase" [hidden]="session.hide">

  <button ion-item (click)="goToSessionDetail(session)">
    <h3>{{session.name}}</h3>
    <p>
      {{session.timeStart}} &mdash;
      {{session.timeEnd}}:
      {{session.location}}
    </p>
    <ion-badge danger item-right>24</ion-badge>
  </button>

  <ion-item-options>
    <button favorite (click)="addFavorite(slidingItem, session)" *ngIf="segment === 'all'">
      Favorite
    </button>
  </ion-item-options>

</ion-item-sliding>
```

![screen shot 2016-01-28 at 5 36 32 pm](https://cloud.githubusercontent.com/assets/6577830/12661117/bfd0e376-c5e5-11e5-90e3-fde618844406.png)
![screen shot 2016-01-28 at 5 36 48 pm](https://cloud.githubusercontent.com/assets/6577830/12661118/bfd7e45a-c5e5-11e5-931a-1f6f81c6cef7.png)

**Comment by phavre** [comment]
Here is my markup. The sliding part is ok (Both icons are still on the right part)

`
>   
>      <ion-item-sliding #slidingItem *ngFor="#item of items | async">
>         <ion-item (click)="itemTapped($event, item)">
>               {{item.title}}
>               <ion-span item-right [hidden]="!item.sawOn" class="timeAgo">{{item.sawOn}}</ion-span>
>               <ion-icon danger name="heart" item-right [hidden]="!(item.fav && !filterFavorite && !item.sawOn)"></ion-icon>
>         </ion-item>
>         <ion-item-options>
>            <button [hidden]="!(!filterFavorite && !item.sawOn)" (click)="favorite(item, slidingItem)">
>               <ion-icon style="padding: 10px" danger name="heart" [isActive]="!item.fav">
>            </ion-icon></button>
>            <button (click)="share(item,slidingItem)">
>               <ion-icon style="padding: 10px" name="share"></ion-icon>
>            </button>
>         </ion-item-options>
>      </ion-item-sliding>
> 
> `

**Comment by brandyscarney** [comment]
I copied your code in `ion-item`, changed `item` to `session` and just removed the `hidden` attribute from the icon and I am able to see it:

```
<ion-item-sliding *ngFor="#session of group.sessions" #slidingItem [attr.track]="session.tracks[0] | lowercase" [hidden]="session.hide">

     <ion-item (click)="itemTapped($event, item)">
           {{session.name}}
           <ion-span item-right [hidden]="!session.sawOn" class="timeAgo">{{session.sawOn}}</ion-span>
           <ion-icon danger name="heart" item-right></ion-icon>
     </ion-item>
     <ion-item-options>
        <button [hidden]="!(!filterFavorite && !session.sawOn)" (click)="favorite(session, slidingItem)">
           <ion-icon style="padding: 10px" danger name="heart" [isActive]="!session.fav">
        </ion-icon></button>
        <button (click)="share(session,slidingItem)">
           <ion-icon style="padding: 10px" name="share"></ion-icon>
        </button>
     </ion-item-options>

</ion-item-sliding>
```

![screen shot 2016-01-28 at 5 54 51 pm](https://cloud.githubusercontent.com/assets/6577830/12661553/41e2b144-c5e8-11e5-94e3-d7a27445a303.png)

Can you try running the conference app, compare your code against it and see if you notice anything different? https://github.com/driftyco/ionic-conference-app

**Comment by phavre** [comment]
By the way, may be I have an issue here for the inputs components since alpha 53 are disabled somewhat 
* ion-input in  read-only
* ion-toggle in read-only
* ion-checkbox in read-only

For the toggle, the (click) event is still handled however but the switch stays deselected although the inner button with `role=checkbox"` is set with the following: `aria-disabled="false"`.
For the ion-toggle here is the markup:
`
>          <ion-item>
>            <ion-label>{{ 'Daily notifications' | translate }}</ion-label>
>            <ion-toggle (click)="toggleNotifs()"></ion-toggle>
>         </ion-item>
`

I'm waiting your return before opening another issue

**Comment by phavre** [comment]
Yes I'll do that for it seems an issue from my side :( It's a good chance to at last clone the conf app :)
Thanks for your help and time. I'll let you know.

**Comment by brandyscarney** [comment]
I'm not seeing any issues with the toggle either. Did you find any cause for the previous issue that maybe is the same?

**Comment by phavre** [comment]
I suspect that both issues are related. I tested the conference app and it is working as expected. 
I tried a 'npm install -g ionic@beta' command to replace my version but without better results. I'm at lost here. I'll try to create a simplistic page to see the result and check if any previous alpha directory may remain and may be the cause

**Comment by brandyscarney** [comment]
Can you run `ionic info` and paste the output? Running `npm install -g ionic@beta` is updating the CLI, not the framework.

**Comment by phavre** [comment]
Thanks I'm still struggling with all the npm things (new to me). 
The good news is that I fixed the icon, toggle and badge issues (I found your post in the forum explaining how to update ionic (thank bis) plus I hadn't created the new theme directory holding the scss when migrating to 51).
Now this is the sliding items (working previously) which does not work anymore whereas they are working in the conference app (I copied the sliding item conference app markup into my app and it's still not working, so it's on my side) :(.

> Cordova CLI: 5.4.1
> Ionic Version: 2.0.0-alpha.53
> Ionic CLI Version: 2.0.0-beta.17
> Ionic App Lib Version: 2.0.0-beta.8
> OS: Windows 7 SP1
> Node Version: v5.3.0

**Comment by brandyscarney** [comment]
We created a section on npm in the docs to try to help explain it: http://ionicframework.com/docs/v2/resources/using-npm/

Is the `item-right` working correctly now?

**Comment by phavre** [comment]
Yes it works correctly, and the sliding item issue also. In fact it didn't work either on the conference app but to reproduce the issue I had to be in iPhone 4 config in google chrome. In larger config and ionic view it works both for the conference and my apps
