### ISSUE TITLE
How to install FFMPEG-php in VPS to generate thumbnail from video?

### ISSUE THREAD

**Issue by yuvithakur** [driftyco/ionic#5243]
I am using godaddy virtual private server. i wanna generate thumbnail from video files using PHP. For that i have to install FFMPEG, Please suggest me how can i install FFMPEG in VPS.

**Comment by adamdbradley** [comment]
Sorry, I'm not sure how to accomplish this task. Since this issue isn't related to ionic I'm going to close this.
