### ISSUE TITLE
perf: SQLStorage API: expose transaction

### ISSUE THREAD

**Issue by sphaso** [driftyco/ionic#5245]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,
I've noticed a bit of a performance sink when trying to upsert between 10k and 40k records on SQLite (using Chrome as a target device, so actually WebSQL). It takes me about 1:30 minutes to upsert 11k records of 3 columns on an empty DB.
I've also noticed that the current API only exposes the "query" method to run SQL statements, which opens a new transaction for each "query" method execution. 
Would you consider exposing the transaction itself instead of opening it on each query? 
I can't be sure this is the actual reason of the performance sink, but it's a good candidate and I think it would be useful anyway.

Thank you</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
You still can access the transaction method, just that is nested (i hate that but i can use transactions), example:
>     this.db = new Storage(SqlStorage, {name: 'sonoramobile'});
    this.db._strategy._db.transaction((tx) => {})

**Comment by sphaso** [comment]
@Luchillo thanks! I'll try that out

**Comment by Luchillo** [comment]
Still i would like a direct api for transactional queries.

**Comment by Luchillo** [comment]
Here's a case where we need the transactional queries exposed, as i have the Typescript project, accessing the transaction through the db's `_strategy` property raises an alert of the ts linter, due to being a private member of db:
>     ERROR in [default] /home/carlos/Carlos/Programming/OSGroup/taoappionic2/app/services/db.ts:33:11 
    Property '_strategy' is private and only accessible within class 'Storage'.

**Comment by sphaso** [comment]
After updating to 2.0.0-beta.2 and CLI-beta.19 with the gulp workflow, the build process raises the error previously reported by @Luchillo .
Any workaround I could use before the issue is resolved?

**Comment by Luchillo** [comment]
@sphaso That's not really an error, is a tslint warning, which means that it still transpile, my app works, just have to ignore that lint error, since i know what it is and why i won't fix it.

**Comment by sphaso** [comment]
@Luchillo thanks again! and sorry for the false alarm, I'm still a noob on this stack.

**Comment by Luchillo** [comment]
@sphaso No problem, the first time i changed my project to TS there were so many of those that i jumped 1 meter off my seat. :confounded:

**Comment by adamdbradley** [comment]
Looks like this is resolved. Please create a new issue if you come across any other problems, thanks.

**Comment by Luchillo** [comment]
Resolved? the request is to expose the transaction api so we don't have to access private members, this is a hack, a workaround, we ask if you can expose the transaction.

**Comment by SP1966** [comment]
Does the Ionic team plan to expose the transaction api or not? It would be great to get a yea or nea answer!

**Comment by Luchillo** [comment]
It seems not, since this workaround works i think they will leave it for now until a later release, there are other issues they have to take care of.
