### ISSUE TITLE
bug: item-right no longer places icon on the right side

### ISSUE THREAD

**Issue by Zeakk** [driftyco/ionic#5246]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After the release of Alpha.53, item-right stopped placing icons on the right side of both ion-item and buttons.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
What does your markup look like when it's not working?

**Comment by Zeakk** [comment]
```
<ion-card *ngIf="!search">
    <button ion-item>
      <ion-icon primary item-right name="bookmark"></ion-icon>
      <h2>Bookmarks</h2>
    </button>
  </ion-card>
```

This use to place the icon on the right side before .53.

**Comment by brandyscarney** [comment]
For anyone that runs into this issue, if you have a theme directory like this:

```
│   ├── theme/                         * App theme files
│   │   ├── app.core.scss              * App Shared Sass Imports
│   │   ├── app.ios.scss               * iOS Sass Imports & iOS Variables
│   │   ├── app.md.scss                * MD Sass Imports & MD Variables
│   │   └── app.variables.scss         * App Shared Sass Variables
```

You need to make sure the `ionic.config` Sass src looks like this:

```
    sass: {
      src: ['app/theme/app.+(ios|md).scss'],
      dest: 'www/build/css',
      include: [
        'node_modules/ionic-framework',
        'node_modules/ionicons/dist/scss'
      ]
    },
```

Leaving this issue open until we can fix the starters.

**Comment by brandyscarney** [comment]
All of the starters have been updated to use a theme directory & alpha.53:

https://github.com/driftyco/ionic2-starter-tutorial/commit/14cd14cbcdd37a2a0711f6f72945cefa66b5da01
https://github.com/driftyco/ionic2-starter-tabs/commit/3912d7dfc702e8d478a75ba3e22b52e5c07d949c
https://github.com/driftyco/ionic2-starter-blank/commit/3c44de6d07047ac5cea6910bb0795bad173b830f
https://github.com/driftyco/ionic2-starter-sidemenu/commit/f4c8f7aaf1acb9235f22f03955ca4cb841d50eb4

https://github.com/driftyco/ionic2-app-base/commit/64647cf027b8583ea7ced657b4ab29e162c5587b
