### ISSUE TITLE
bug: ion-input createing 2 input fields

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic#5247]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>**Beta version:** 2.0.0-alpha.53 

When creating ion-input in an list, as it says in the CHANGELOG.
Do I get 2 input fields.

![Bug image](http://netogweb.it/bug/2_input_fields_bug.png)

Example
```HTML
<ion-item>
                    <ion-label>Panel ID</ion-label>
                    <ion-input [(ngModel)]="roadSitePanel.panelNo" type="number" placeholder="Enter panel ID"></ion-input>
                </ion-item>
```</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Yes, the second input is used on mobile devices to allow for smooth transitioning when going to the next input.

**Comment by Doehl** [comment]
Yes, but it is show in the app. I can click the field and enter a value. 
Should both fields be shown to the user?

**Comment by adamdbradley** [comment]
Gotcha, I see what you mean now. Has your CSS been updated?

**Comment by Doehl** [comment]
Okay, there is the issue. My css files is not being updated in the **www\build\css**.
I will see if I can find the reason.

Thanks, have a nice weekend.

**Comment by adamdbradley** [comment]
No problem, glad you were able to get it working.

**Comment by brandyscarney** [comment]
@Doehl do you have a theme folder similar to the Conference App?

```
│   ├── theme/                         * App theme files
│   │   ├── app.core.scss              * App Shared Sass Imports
│   │   ├── app.ios.scss               * iOS Sass Imports & iOS Variables
│   │   ├── app.md.scss                * MD Sass Imports & MD Variables
│   │   └── app.variables.scss         * App Shared Sass Variables
```

If so, update the `ionic.config` file where the Sass src are to this:

```
    sass: {
      src: ['app/theme/app.+(ios|md).scss'],
      dest: 'www/build/css',
      include: [
        'node_modules/ionic-framework',
        'node_modules/ionicons/dist/scss'
      ]
    },
```

**Comment by Doehl** [comment]
I have done both of what you described.

What I found is that I forgot in the "2.0.0-alpha.51", after relocation the scss file was updating the import locations to go back one folder first. Before going in the the page folders. 

I just added "../" to the import paths. 

Thanks you for your help, great work with the version 2 of ionic. :+1:
