### ISSUE TITLE
White screen on iOS after updating Cordova to 6.0.0

### ISSUE THREAD

**Issue by magnusburton** [driftyco/ionic#5248]
Hello!

I just updated Cordova to their latest version 6 and I've been getting the 'mysterious' white screen "of death". This happens when I emulate through xcode and through the terminal with the commands `ionic emulate ios -l -c` and `ionic emulate ios -l -c -s --address localhost`. However, using `ionic emulate ios` with Live Reload turned **off** seems to work.

I'm not receiving any errors or warnings, except when i build for iOS. Then I get 4 warnings about the UIInterfaceOrientation. `note: 'interfaceOrientation' has been explicitly marked deprecated here`

Here's my `ionic info` output;
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2 Build version 7C68

Thank you so much for any help and for **Ionic** in the first place!

**UPDATE:**
[Here's a fiddle](https://jsfiddle.net/magnusburton/cq8vwwLm/) of the warnings that comes when doing `ionic build ios`.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-platform-issues#32

**Comment by adamdbradley** [comment]
Sorry, moved the wrong issue

**Comment by magnusburton** [comment]
To update; running my app through Xcode onto my device works aswell! It's only the live reloading and eventually those 4 warnings.

**Comment by singhrajvirk** [comment]
same issue, everything works after updating plugins but livereload is stuck at splash screen.

**Comment by Bandito11** [comment]
when I was installing on wp8 I noticed the same thing, I just thought it was because it is a windows phone thing.

I did noticed that it was messing up at Windows 10 at first and it fixed itself somehow LOL

**Comment by palenicek** [comment]
Hi, try to add 'allow-navigation' tag to config.xml in root of your project: 
<widget>
...
**<allow-navigation href="http://*/*" />** 
...
</widget>

Starting with Cordova 6.0 and Cordova iOS platform 4.x, application's config.xml must include the <allow-navigation href="url" /> permission to allow the app to access "remote" content. This includes the IP's used by livereload. Here's the [documentation](https://www.npmjs.com/package/cordova-plugin-whitelist#navigation-whitelist).

On my Mac ionic2 uses 10.163.21.47, so this also worked for me and is more strict with the whitelist policy: 
<allow-navigation href="http://10.163.21.47"/>

**Comment by NoahYarian** [comment]
@palenicek thank you, that did it!

**Comment by AdrianTeh** [comment]
@palenicek Thanks, it worked!

**Comment by jgw96** [comment]
As it looks like @palenicek posted the solution i am going to close this issue for now. Thanks!

**Comment by OdraCode** [comment]
@palenicek - can please tell me how can i find out this IP on mac, but ionic1. Thanks

**Comment by martinOdra** [comment]
@palenicek - can you (or anybody else) please tell me how can i find out this IP on mac, but ionic1. Thanks

**Comment by matheushrt** [comment]
@palenicek Thank you so much! Worked just fine, here!
