### ISSUE TITLE
Add animated icons

### ISSUE THREAD

**Issue by izelnakri** [driftyco/ionic#5249]
I couldnt find in the Ionic v2 documentation.

**Comment by mhartington** [comment]
Not yet, still on our list of todos

**Comment by manucorporat** [comment]
+1

**Comment by cyprusglobe** [comment]
+1

**Comment by lordgreg** [comment]
+1

**Comment by iBasit** [comment]
+1

**Comment by adamdbradley** [comment]
The first set of ion-spinners have been added and will be in beta2

**Comment by lordgreg** [comment]
Thank you @adamdbradley. Really looking forward to use them. :+1:

**Comment by iBasit** [comment]
:+1:

**Comment by iBasit** [comment]
:+1: 

Can you please post documentation link for this, I wanted to check them out.
