### ISSUE TITLE
bug: <ion-select> not displaying selected item.

### ISSUE THREAD

**Issue by Zeakk** [driftyco/ionic#5250]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

`<ion-select>` is not displaying the updated selected item. 

```
<ion-item>
    <ion-label>Gaming</ion-label>
    <ion-select [(ngModel)]="gaming">
      <ion-option value="nes" checked="true">NES</ion-option>
      <ion-option value="n64">Nintendo64</ion-option>
      <ion-option value="ps">PlayStation</ion-option>
      <ion-option value="genesis">Sega Genesis</ion-option>
      <ion-option value="saturn">Sega Saturn</ion-option>
      <ion-option value="snes">SNES</ion-option>
  </ion-select>
</ion-item>
```

The code above will ALWAYS show NES as the checked item even after selecting another item.

**Comment by adamdbradley** [comment]
This has been fixed and will be in the next release: https://github.com/driftyco/ionic/commit/58443f0ff3bacecdb51ef68a796cfed951fd904e

thanks

**Comment by Zeakk** [comment]
You guys are stomping out bugs too fast...
