### ISSUE TITLE
bug: NavController pop immediately after Alert dismiss

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5251]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My use case:
The user opens a feature that requires localization permission, so I show an ionic alert, explaining why.

If the user dismiss the alert, or cancels it, I go back immediately.

This is what happens: 
```
Uncaught TypeError: Cannot read property 'nativeElement' of undefinedAlertPopOut
@ app.bundle.js:56628Animation.createTransition @ app.bundle.js:42002(anonymous function)
@ app.bundle.js:47954run @ app.bundle.js:1183NgZone.runOutsideAngular
@ app.bundle.js:17434NavController._beforeTrans @ app.bundle.js:47949(anonymous function)
@ app.bundle.js:47923run @ app.bundle.js:1183arguments.(anonymous function)
@ app.bundle.js:1581
```

```js
    showConfirm() {
        const alert = Alert.create({
            title: `Location required`,
            buttons: [
                { text: 'Cancel', handler: () => this.cancelConfirm() },
                { text: 'Continue', handler: () => this.continueConfirm() }
            ]
        });
        this.nav.present(alert);
    };

    cancelConfirm() {
        //setTimeout(() => this.nav.pop(), 1000); //  it works
        this.nav.pop(); // Uncaught TypeError: Cannot read property 'nativeElement' of undefinedAlertPopOut
    }
```

</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
I want to ask for an advice about how to use the Alert API, I found it horrible.
```js

    showConfirm() {
        this.alertButton = 0;
        const alert = Alert.create({
            title: `Location required`,
            subTitle: 'Your location is needed in order to match you with people close geographfically. </br></br>Your location will NEVER be shared or leaked to 3rd people.',
            buttons: [
                { text: 'Cancel', handler: () => this.alertButton = 1 },
                { text: 'Continue', handler: () => this.alertButton = 2 }
            ]
        });
        alert.onDismiss(() => {
            console.log(this.alertButton);
            switch (this.alertButton) {
                case 0: // background dismiss
                case 1: // cancel button
                    this.cancelConfirm();
                    break;
                case 2: // continue button
                    this.continueConfirm();
                    break;
                default:
                    throw "bad state!";
            }
        });
        this.nav.present(alert);
    };

    cancelConfirm() {
        console.log("CANCEL!!");
        setTimeout(() => this.nav.pop(), 1000);
    }

    continueConfirm() {
        this.requestPosition();
    }
```

Since I also want to catch dismiss event by clicking the background I have to hack around...
it would be great if the onDismiss() callback returns an object like:
```json
{
    "inputs": getValues(),
    "button": <<buttonid>>,
}
```

"button" == null --> dismiss by tapping background.

**Comment by adamdbradley** [comment]
I'd recommend using the handlers on the button, instead of trying to put all your logic in the onDismiss. Have you seen these examples? https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/basic/index.ts

**Comment by adamdbradley** [comment]
Also, can you not always navigate forward and rely on the cancel button to go back? Can you just have the alert come up, and if they click confirm, then you run your logic?

**Comment by manucorporat** [comment]
@adamdbradley 

>I'd recommend using the handlers on the button, instead of trying to put all your logic in the onDismiss. Have you seen these examples?

Using the button handlers is great sometimes, but how do I catch the dismiss event even when the alert is dismissed by a click in the background? 

>Also, can you not always navigate forward and rely on the cancel button to go back? Can you just have the alert come up, and if they click confirm, then you run your logic?

I could do that, but from a UI/UX view point, I want to use the page "blurred" content as a inceptive to make users accept localization permissions.
I want this:
1. User press the button.
2. User can the cool stuff behind the alert button! they want the alert to disappear, so they accept!

**Comment by adamdbradley** [comment]
What if there was a `role` property that could be added to a button, and when the user taps on the background to close, it would fire the button handler that had `role: 'cancel'`? This way you wouldn't have to add in if/switch statements in onDismiss. I also think we'd change `style` on actionsheet to use `role` instead.

**Comment by manucorporat** [comment]
And one addition comment, any app that uses the Cancel handler like this: https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/basic/index.ts#L32-L39
to do something relevant is broken from the UI/UX view point if they do not handle the background tap somehow. And right now there is not a way to do it without hacking around onDismiss().

**Comment by manucorporat** [comment]
@adamdbradley 
>What if there was a role property that could be added to a button, and when the user taps on the background to close, it would fire the button handler that had role: 'cancel'? This way you wouldn't have to add in if/switch statements in onDismiss.

It could work, yes!
question: is there any situation where you have to handle differently cancel and background tap?
it is an open question, but if you think the answer is NO. then go ahead with your `role` idea!!

**Comment by manucorporat** [comment]
> I also think we'd change style on actionsheet to use role instead.
I read it again :) yeah! good idea. I totally support the idea.

**Comment by adamdbradley** [comment]
Ok, I think I'll add that in then. As far as the nav pop goes the reason you're having issues is because the page you're on and the alert share the same ion-nav, so when you pop while the alert is actively going out then things get confused. I'll be fixing it soon that overlays do not share the same ion-nav as pages which should solve your problem.

**Comment by manucorporat** [comment]
@adamdbradley great! 
one more thing: for API completion, it would be great if the onDismiss() callback returns the role (optional):
```js
onDismiss((input, role) => {} )
```
is that possible right? it would not break existing code!

role would be == "cancel" when background tap! simple, consistent and clean.

**Comment by adamdbradley** [comment]
Good idea, I added to have the button's role passed as the second arg in the dismiss method.

**Comment by manucorporat** [comment]
@adamdbradley good job!
thank you for the awesome support and for this framework, i used to be a JS hater and now I am enjoying a lot building a high quality app with ionic!

**Comment by adamdbradley** [comment]
I also made an example showing how you can dismiss the alert, then pop the page:
https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/test/basic/index.ts#L161

The challenge with trying to pop the navigation while also dismissing the active alert is that they share the same nav controller, which is actually a good thing when it comes to controlling pages and making sense of the stack. But if you pop the alert and immediately pop the page before it, there won't be a smooth transition. So it's better to pop the page after the alert has dismissed. Hope that helps.
