### ISSUE TITLE
Android buttons in the Advanced Cards demo aren't interacting / rippling correct

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic#5254]
They don't show the ripple every time, and just feel awkward when tapped.
![image](https://cloud.githubusercontent.com/assets/519526/12692213/c2743e32-c6b9-11e5-9467-965d650b3aca.png)

http://ionic-site-staging.herokuapp.com/docs/v2/components/#card-advanced-social

**Comment by bensperry** [comment]
also noticing on the right example here:
![image](https://cloud.githubusercontent.com/assets/519526/12692204/a8724c54-c6b9-11e5-8e00-06d9e10e89d5.png)

http://ionic-site-staging.herokuapp.com/docs/v2/components/#buttons-in-components

**Comment by brandyscarney** [comment]
I'm not seeing this. What browser are you using?

**Comment by brandyscarney** [comment]
Not seeing this with the latest version of Ionic. Closing, please reopen if it happens still.
