### ISSUE TITLE
docs: No good way to change default landing tab

### ISSUE THREAD

**Issue by calclavia** [driftyco/ionic#5256]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>There does not seem to be a decent way to set the default tab. Either that, or the documentation does not explain tabs very well.

I made a workaround by making the first tab-page select another tab. This is sort of a hack, but preferably it shouldn't be done this way.

```
@Page({
  templateUrl: '...'
})
export class ContactsPage {
  constructor(nav: NavController, tabs: Tabs) {
    this.nav = nav;

    //TODO: Hacks. Force tab to be 2nd tab instead of left most tab.
    this.tabs = tabs;
    this.tabs.select(1);
  }
}
```

Angular also errors when attempting to inject "Tabs" into the JS class controlling the Tabs. My app is based on the sample app with tabs.

</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Well, you're right about us not documenting it well :)

It was recently added and should be in alpha53. The `selectedIndex` attribute can be added to `ion-tabs`:
https://github.com/driftyco/ionic/blob/2.0/ionic/components/tabs/test/tab-bar-scenarios/main.html#L11

I'll add it to the docs, thanks

**Comment by adamdbradley** [comment]
https://github.com/driftyco/ionic/commit/6a96dae283007229f81fd9fc8627e5bc1e990389

**Comment by calclavia** [comment]
Thank you!
