### ISSUE TITLE
bug: Typescript can't find the 'moment' package

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5257]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I had the project working with js, then i started a new typescript project and copy the configs to mine, i have the `moment` package installed but the compilator complains that can't find the `moment` package.

I tried to install and import inside the new typescript project just to ensure it isn't my bad when copying the configs and happens the same, why if i had it working with the js project? i think it's the same with `D3` data visualization package, had it working and now it doesn't, help?</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
Update, it's the linter, the code still works, it's just the linter that can't detect the packages, that's heavily missleading, both the syntax highlight in sublime and the console logs says `Cannot find module 'moment`, at least the linter should be fixed.

**Comment by wsjwong** [comment]
Totally the same. I would like to import the `momentjs` and `d3js` but it is not working. Any doc/tutorial on how to import packages from npm?

**Comment by msevestre** [comment]
Did you try to import the typescript definition! Something like `tsd import moment --save`

**Comment by Luchillo** [comment]
Oh i didn't, i forgot that typescript needed the definitions, but in such case where does the ones for ionic come from?

However i did as you mentioned but with `tsd install moment --save && tsd install d3 --save` and the error persists.

**Comment by manucorporat** [comment]
Just use:
```js
const moment = require("moment");
```

to silent TS.

**Comment by Luchillo** [comment]
Actually i did use the reference way, i think looks cleaner.

**Comment by Luchillo** [comment]
@manucorporat Found another way, just include the `typings/tsd.d.ts` file in the `files` array in the `tsconfig.json` file to make the typings available in all the project.

**Comment by manucorporat** [comment]
@Luchillo cool! thanks for the info! looks like a cleaner solution

**Comment by Anujmoglix** [comment]
can anyone explain solution ?

**Comment by luchillo17** [comment]
@Anujmoglix Which one? the one i suggested? the comment is very explicit, though outdated, what did not understand?
