### ISSUE TITLE
List of tappable elements is not scrollable

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#5260]
Due to this [issue](https://github.com/driftyco/ionic/issues/5258) I tried to use (tap) instead of (click). This would fix the tap/click experience with the element on mobile device, but then scroll does not work, if you start scrolling by tapping the tappable element. When should be the tap used vs click?

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by jaspersorrio** [comment]
(tap) directive doesn't work for me.

I will get a maximum call stack error.

@Yagger may i see your package.json dependencies?
