### ISSUE TITLE
not build android ionic

### ISSUE THREAD

**Issue by erikhu** [driftyco/ionic#5262]
my SO is Arch and the error show the next: 
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo}
Attempting to read last messages from the daemon log...
Daemon pid: 4909
  log file: /home/erik/.gradle/daemon/2.2.1/daemon-4909.out.log
----- Last  20 lines from daemon log file - daemon-4909.out.log -----
09:55:37.615 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication] Completed writing the daemon greeting. Closing streams...
09:55:37.616 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] requestStopOnIdleTimeout(10800000 MILLISECONDS) called on daemon
09:55:37.617 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Idle timeout: waiting for daemon to stop or be idle for 10800000ms
09:55:37.618 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Daemon is idle, sleeping until state change or idle timeout at Sat Jan 30 12:55:37 COT 2016
09:55:37.627 [DEBUG] [org.gradle.messaging.remote.internal.inet.TcpIncomingConnector] Accepted connection from /127.0.0.1:46524 to /127.0.0.1:45028.
09:55:37.681 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 14: received class org.gradle.launcher.daemon.protocol.Build
09:55:37.682 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] Received non-IO message from client: Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo}
09:55:37.683 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo}.
09:55:37.684 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo} with connection: socket connection from /127.0.0.1:45028 to /127.0.0.1:46524.
09:55:37.691 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo}, connection = org.gradle.launcher.daemon.server.DefaultDaemonConnection@1b60c604] after 0.0 minutes of idle
09:55:37.692 [INFO] [org.gradle.launcher.daemon.server.DomainRegistryUpdater] Marking the daemon as busy, address: [421ad216-f8db-4e87-ac38-344585fe2018 port:45028, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
09:55:37.692 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [421ad216-f8db-4e87-ac38-344585fe2018 port:45028, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
09:55:37.693 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
09:55:37.693 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
09:55:37.700 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
09:55:37.700 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] updating lastActivityAt to 1454165737700
09:55:37.700 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Daemon is busy, sleeping until state changes.
09:55:37.701 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=b7e70436-8911-4400-b5fd-dfac4be7781e.1, currentDir=/home/erik/Proyectos/ionic/Aplicativo}. Dispatching build started information...
09:55:37.702 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 16: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
09:55:37.706 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=/home/erik/adt/sdk/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/erik/adt/sdk/tools:/home/erik/adt/sdk/platform-tools:/home/erik/bin:~/.composer/vendor/bin:~/adt/sdk/platform-tools, XAUTHORITY=/home/erik/.Xauthority, XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, ANDROID_HOME=/home/erik/adt/sdk, XDG_CURRENT_DESKTOP=KDE, MAIL=/var/spool/mail/erik, MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins, SESSION_MANAGER=local/Aries:@/tmp/.ICE-unix/635,unix/Aries:/tmp/.ICE-unix/635, LOGNAME=erik, KONSOLE_DBUS_SERVICE=:1.36, PROFILEHOME=, PWD=/home/erik/Proyectos/ionic/Aplicativo, XCURSOR_THEME=breeze_cursors, LANGUAGE=, WINDOWID=56623109, KDE_SESSION_VERSION=5, SHELL=/bin/bash, KONSOLE_DBUS_SESSION=/Sessions/1, OLDPWD=/home/erik/Proyectos/ionic/Aplicativo/platforms/android, KDE_FULL_SESSION=true, KDE_MULTIHEAD=false, GTK_MODULES=canberra-gtk-module, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1, COLORFGBG=15;0, XDG_SESSION_DESKTOP=KDE, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, SHLVL=3, QT_IM_MODULE=compose, JAVA_HOME=/usr/lib/jvm/java-8-openjdk, KDE_SESSION_UID=1000, TERM=xterm, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, LANG=es_CU.UTF-8, KONSOLE_DBUS_WINDOW=/Windows/1, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, XDG_SESSION_TYPE=x11, XDG_SESSION_ID=c2, GRADLE_HOME=/usr/share/java/gradle, DISPLAY=:0, SHELL_SESSION_ID=19534bbd7d2640009848390ae396408e, GTK_RC_FILES=/etc/gtk/gtkrc:/home/erik/.gtkrc:/home/erik/.config/gtkrc, XDG_SESSION_CLASS=user, KONSOLE_PROFILE_NAME=Int??rprete de ??rdenes, DESKTOP_SESSION=/usr/share/xsessions/plasma-mediacenter, USER=erik, GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/erik/.gtkrc-2.0:/home/erik/.config/gtkrc-2.0, XDG_SEAT=seat0, GS_LIB=/home/erik/.fonts, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, XDG_RUNTIME_DIR=/run/user/1000, XDG_VTNR=1, HOME=/home/erik}
----- End of the daemon log -----

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
ERROR building one of the platforms: Error code 1 for command: /home/erik/Proyectos/ionic/Aplicativo/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/erik/Proyectos/ionic/Aplicativo/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project
Error: Error code 1 for command: /home/erik/Proyectos/ionic/Aplicativo/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/erik/Proyectos/ionic/Aplicativo/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

that happend when i use command : ionic build android

plsss helpme , i am new in arch and i have  two days try found a solution , i never have this problem in debian  , i no know what can be . thnks for the help

**Comment by tlancina** [comment]
Could you post the output of `ionic info` please?

**Comment by erikhu** [comment]
@tlancina hey bro thnks for ask i solve its intalling two libraries:
lib32z1 and other that no remember right now

**Comment by xiandalisay** [comment]
Had same experience. Here is my ionic info

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed
