### ISSUE TITLE
bug: Typescript doesn't compile html

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5263]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Just yesterday January 30 i updated my Ionic 2 project from JS to Typescript, all fine until i go to editing my html, i changed a class in a html file but the changes don't make it to watch folder, for some reason it does work for the sidemenu typescript starter.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Comment out:
```js
          //useWebpackText: true
```

in webpack.config.js

**Comment by Luchillo** [comment]
I don't have that line in my webpack.config.js.

**Comment by Luchillo** [comment]
I'm such a derp, with the update i moved the pages from app to app/pages, forgot to update the templateUrl's on the files.
