### ISSUE TITLE
Is this IONIC Bug? IONIC + MAPBOX

### ISSUE THREAD

**Issue by yoohoogun114** [driftyco/ionic#5266]
My ionic info command here

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68

And my IOS version 9.2 

Note 1. I'm using option <data-tap-disabled="true"> [ref](http://ionicframework.com/docs/api/page/tap/) 

Note 2. I read [#4538](https://github.com/driftyco/ionic/pull/4538), and [#4506](https://github.com/driftyco/ionic/issues/4506) and others.

I'm using ionic + mapbox.js(v2.2.4)

When I command ionic serve(in browser) click event working nice(click event fired nice). It's not problem.

When I command ionic emulate ios -l -c (in emulator) and click the map at first it works fine. But random 

time (after some click and move the map, expand map, contract map) click event are broken completly.

context(long tab event), and drag event working nice but only click(tab) event broken.

I think it's ionic tab,click bug  because all click(touch) event working nice on browser. 

only problem on emulator.

Is this bug on ionic?

I Created a example Repository  [here](https://github.com/yoohoogun114/IonicBug)

(In this repo i want to show click event working on. so i added code console.log about click event. look carefully console on emulator. ionic emulate ios -l -c)

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by danbucholtz** [comment]
Hi @yoohoogun114,

The repository you linked to isn't available any more.  Happy to check it out if you can get that squared away.  I'm going to go ahead and close this, but feel free to respond if you'd like to dive into it again.

Thanks,
Dan
