### ISSUE TITLE
docs: on-swipe-right not working

### ISSUE THREAD

**Issue by calclavia** [driftyco/ionic#5267]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It seems like on-swipe-right="onSwipeRight()" does not work anymore in Ionic 2. Did it change to something else? If so, it isn't documented.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
This currently doesn't exist in v2

**Comment by brandyscarney** [comment]
Closing this, it has been added to our roadmap: https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit?usp=sharing
