### ISSUE TITLE
bug: Preview on Doc page gets broken on fastsscroll

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5271]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When looking [Docs page](http://ionicframework.com/docs/v2/components/) and scrolling through it,... on one point, the Preview gets broken and doesn't reload anymore. You need to refresh the site to make it work again.

Tested on Google Chrome and Canary (Windows 10 x64)</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
fixed
