### ISSUE TITLE
bug: Menu opening on page scrolling

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5272]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>1. Have Page with side-menu.
2. Make list view which you need to scroll
3. Scroll the page but slide up and down on the LEFT side of your display (as left-handed people do).
4. Menu opens. Stays open. Cannot do anything. Reopen app.

Can be reproduced on all platforms (ios, android and canary&chrome browsers)

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
I was able to reproduce this on my Nexus 5.
