### ISSUE TITLE
After V2 installation can't build android app on windows

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic#5273]
Type: Bug
Platform: Windows

After ionic v2 installation I'm getting strange behavior if  I enter ionic build or ionic run.
I don't have ios platform In my package.json
ionic run
 You're trying to build for ios, but don't have the platform installed yet.
? Installing ios for you.

**Comment by brandyscarney** [comment]
Can you run `ionic info` and paste the output, please?

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#757
