### ISSUE TITLE
Feat: CSS only scroll bounce

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#5275]
Adding the following lines to `scroll-content` allows for the ios scroll bounce that you normally get with overflow.

```sass
//structure.scss
scroll-content {
  // existing css
    &:before,
    &:after {
      content: '';
      height: 1px;
      position: absolute;
      width: 1px;
    }

    &:before {
      bottom: -1px;
    }

    &:after {
      top: -1px;
    }
}
```
Also can be adapted to work ion-scroll's different directions with a little change

```sass
    &[scroll-x=true] scroll-content {
      overflow-x: scroll;
      &:before {
        left: -1px;
      }
      &:after {
        right: -1px;
      }
    }
```

Could be a nice feature to have.

**Comment by manucorporat** [comment]
+1
i was looking for this!

**Comment by quanghoc** [comment]
+1

Folks, any update on this? Ionic 2 on iOS without bounce seems a little too rigid

**Comment by pjhartin** [comment]
I'm actually in the other boat, are there any instructions as how to disable this effect on iOS? I'm trying to disable it in the current conference app to no avail!

**Comment by ghenry22** [comment]
Also looking for this, app doesn't feel quite right on ios without it.

**Comment by manucorporat** [comment]
@ghenry22 @pjhartin I will working on this for beta9 release

**Comment by pjhartin** [comment]
@manucorporat Good to know. Thanks for getting back to us. I appreciate your work!

**Comment by manucorporat** [comment]
@jgw96 how this looks in android? does android bounce always? I want to know the scope of this issue

**Comment by jgw96** [comment]
@manucorporat Android does not bounce but rather has a "shadow" (usually in the primary color of the app) that animates up from either the bottom or top of the screen depending on which way you were scrolling. I will post a video tomorrow so you can see exactly how it looks.

**Comment by manucorporat** [comment]
@jgw96 i meant in ionic, (not native android). Does ion-content always have that shadow? Even when there is not overflow? Thanks!

**Comment by manucorporat** [comment]
@pjhartin @ghenry22 @quanghoc https://github.com/driftyco/ionic/pull/7061
