### ISSUE TITLE
android scroll question

### ISSUE THREAD

**Issue by wangzhiwei1888** [driftyco/ionic#5276]
Hi 

thanks ionic, my project use ionic,feel very great. boss feeling is very great in ios.

but
I have a question for android performance.
I want to disabled scroll ,use system default scroll. in android environment.
specific
css style no use position absolute ....

So that we can solve the android poor performance under the situation, hope to be able to provide the corresponding configuration.

We can distinguish between android and IOS. Some optimization configuration.

thanks !

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
