### ISSUE TITLE
nav-direction doesn't behaviour correctly inside directive

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic#5279]
`<div>
    <h1><span>TITLE</span></h1>
    <div>
        <a ng-click="vm.goHome();" nav-direction="back"  class="ion-chevron-left"></a>
    </div>
</div>`

If i put this code inside a directive template, the nav-direction doesn't work anymore (i.e. the transition is always forward). I tried different solutions, for example: using the attribute replace: true inside the directive, or trying to put nav-direction="back"  on the view that call the directive (ie `<my-directive nav-direction="back" ></my-directive>`)

**Comment by marcoturi** [comment]
I found a workaround. Inside the controller of my directive i use:

`$ionicViewSwitcher.nextDirection('back');`

and i dropped nav-direction="back" in the view.

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As it looks like you found the correct way to solve your issue i am going to go ahead and close this. If your still having an issue with it please feel free to reopen this issue! Thanks Again!
