### ISSUE TITLE
bug: disabled attr is not being passed down from ion-input to the input element

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5280]
[http://localhost:8000/dist/e2e/input/fixed-inline-labels/](http://localhost:8000/dist/e2e/input/fixed-inline-labels/)

```
    <ion-item>
      <ion-label fixed>CC</ion-label>
      <ion-input disabled="true" value="Text 2"></ion-input>
    </ion-item>
```

**Comment by aperezbaena-csc** [comment]
It works with static values but it doesn't adding disabled attribute dynamically such as:

`<ion-input [disabled]="isDisabled ? '' : null">`

**Comment by aplimovil** [comment]
This issue is still present on Ionic 2.0.0. When an ion-input is initially set with the [disabled]="true" attribute the disabled attribute isn't being passed down to the native input element.

**Comment by trebor678** [comment]
This is still an issue with Ionic 3.4.2

**Comment by rodrigo85** [comment]
Is there any workaround?

**Comment by ahmadalfy** [comment]
Weird that this issue is still opened
