### ISSUE TITLE
bug: Access Denied when try take photo on Windows

### ISSUE THREAD

**Issue by jaschweder** [driftyco/ionic#5287]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When I try to take a picture using the cordova-plugin-camera I get a error message with "Access denied", any idea of how fix this ?</span>

<span is-issue-template></span>

**Comment by cyprusglobe** [comment]
@jaschweder you might take a look at this

http://stackoverflow.com/questions/31127295/apache-cordova-camera-plugin-on-windows-phone-universal-error-access-denied

**Comment by mhartington** [comment]
Looks like this has been fixed in cordova. @jaschweder can you confirm that the update mentioned works?

**Comment by mhartington** [comment]
Not able to reproduce. Closing
