### ISSUE TITLE
bug: ion-select with ngModel doesn't clear .select-text

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5288]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>the alpha.53 `ion-select` with `ngModel` doesn't remove the text inside the `.select-text` after setting the variable of the model to null or undefined, it seems to have to use an empty array, even if i'm just using 1 value in the variable.</span>

<span is-issue-template></span>

**Comment by JosepAlacid** [comment]
Ionic 3 ion-select doesn't show placeholder when programatically the ngModel value is set to null. Only setting it to [] shows placeholder.
