### ISSUE TITLE
<ion-scroll zooming="true">-Tag won't seem to allow zooming in Modal Dialogs

### ISSUE THREAD

**Issue by Z3roCoder** [driftyco/ionic#5289]
So I have run into a very strange problem. While having set everything to have it scrollable, as well as only using percentage-values, my modal dialog won't allow me to zoom in with a finger pinch. Is this a bug, or am I just too stupid to get this to work?

I also took a look at the meta tags in my index.html and they seem to be fine, and my CSS is not of fault either, I think. 

I will link to my code in case someone could take a look at it -> http://cloud.novalos.net/index.php/s/vo8A7YtNMz5kHVn
The file causing that problem is "displayDetailImage.html" in the templates-folder, and I do assume that this might be a bug in Ionic using modal template views?

**Comment by JerryBels** [comment]
@Z3roCoder hi, did you find anything to make zooming work in a modal window ? I ran into the same issue and absolutely need to be able to pinch to zoom on that modal.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#189
