### ISSUE TITLE
docs: $ionicViewSwitcher public API docs is missing

### ISSUE THREAD

**Issue by epaezrubio** [driftyco/ionic#5291]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Documentation for this service is missing https://github.com/driftyco/ionic/blob/master/js/angular/service/viewSwitcher.js

I will submit a PR soon</span>

<span is-issue-template></span>

**Comment by jrencz** [comment]
@epaezrubio this service is marked as private - this means it does not need its public api to be documented.

Angular does not provide DI scoping so everything that is exposed to DI is public in fact. The only way to express that some parts of Ionic are not meant for developers to make their own code depandant on is to mark those services as `@private` and NOT provide publicly available documentation. This leaves ionic developers certain amount of freedom in implementing features.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-site#440
