### ISSUE TITLE
bug: button full text is not center aligned on ios

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic#5292]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>it should not be considered ionic's bug. more about adding patch to make it work in ios

i have several button full in my view, and they are all text-center aligned in browser.
but when i test on mobile and simulator, the text is always left aligned.
have used safari inspector to check and the text-align: center is applied correctly, but it does no affect in simulator or on phone.

so, a strange workaround that my colleague asked me to try is adding the following css style to the button:

    display: block

then it works and all the full button text are center aligned

so, i suggest adding display: block to button[full] inside the ios.scss to get the expected behavior.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
+1

**Comment by manucorporat** [comment]
well, "it should not be considered ionic's bug" i think it is a bug.
i should not look different in iOS-device vs desktop.

**Comment by adamdbradley** [comment]
This is a difficult one because it's actually a safari bug. Display block works, but then it breaks buttons with icons. This issue is on our todo's to figure out a good solution.

**Comment by manucorporat** [comment]
@adamdbradley was this error actually reported to the safari/webkit team?

**Comment by brandyscarney** [comment]
Closed by https://github.com/driftyco/ionic/pull/5310
