### ISSUE TITLE
Bug on combine radio-button with ion-option-button

### ISSUE THREAD

**Issue by danielptn** [driftyco/ionic#5300]
It is a way to combine radio-button with ion-option-button??

**Comment by danielptn** [comment]
hello??

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
