### ISSUE TITLE
feat: slides - emit events for slide change start and end

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5301]
Similar to the change event

**Comment by brandyscarney** [comment]
Implemented the `slideChangeStart` event but not the `slideChangeEnd` event because this already happens when the `change` event is emitted. I didn't want to have two ways of using the same event, may want to rethink the name of the `change` event.

**Comment by msprasad9** [comment]
Ionic has ionSlideDidChange event when I changed form Slide 1 to Slide 2 while dragging a slide. But If I fail to move from Slide 1 to Slide 2 I couldn't find any event to capture. Can Any one help me how can I get that event.

**Comment by thetwosents** [comment]
^ Have same issue as above
