### ISSUE TITLE
scrolling - should animate - not able to configure scroll speed

### ISSUE THREAD

**Issue by rolandoldengarm** [driftyco/ionic#5304]
With the $[ionicScrollDelegate](http://ionicframework.com/docs/api/service/$ionicScrollDelegate/), the scroll methods have a shouldAnimate property.

However, it is not possible to configure the scroll speed. Looking at the source code of the [scrollViewNative](https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/views/scrollViewNative.js) it is hard-coded to 250ms. I'd like to be able to change that to e.g. 500ms.

**Comment by rolandoldengarm** [comment]
I found a solution :) http://stackoverflow.com/questions/29742525/ionic-decrease-scroll-speed

**Comment by rolandoldengarm** [comment]
However, this does not work in the native scroll... Only in JS scroll. So is it possible to make it available in native scroll?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is more of a question you will get a better answer over at our forum (https://forum.ionicframework.com/) or on our slack channel (http://ionicworldwide.herokuapp.com/) Thanks Again!
