### ISSUE TITLE
bug: block buttons should not be full width

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5305]
They should look like they are in a content with padding w/o adding padding to content

**Comment by imjohnbo** [comment]
Don't block buttons already have the desired behavior, to expand to the entire width of their parent container? Like full buttons except with borders.

**Comment by brandyscarney** [comment]
According to @bensperry block buttons should never touch the side of the container even if there is no padding on the container.

**Comment by jgw96** [comment]
@brandyscarney how much margin are we looking for on each side?

**Comment by brandyscarney** [comment]
@jgw96 I haven't discussed this with Ben yet but I'll let you know when I have more info! :smile:

**Comment by bensperry** [comment]
16px

**Comment by brandyscarney** [comment]
Putting this on hold to discuss with @adamdbradley tomorrow.

**Comment by brandyscarney** [comment]
@adamdbradley and I agree that this should stay the same as v1 which took up the entire width. So this is working as intended!

**Comment by imjohnbo** [comment]
Thanks for the update. Sounds like the right call!
