### ISSUE TITLE
Segment: add transition to hover

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5308]
Hover needs to be lighter but tap can stay the same as it is now

**Comment by jgw96** [comment]
Should just be able to change the opacity to fix this right? If so i can knock this out real quick.
`$segment-button-ios-hover-opacity:            0.16 !default;`

**Comment by brandyscarney** [comment]
The opacity on hover needs to be lightened to `0.1`, but when the activated class is applied it should keep the `0.16` opacity. Then the transition needs to be on the hover as well. If you want to knock it out let me know. :)

Hover (0.1 opacity):
![screen shot 2016-02-05 at 2 03 49 pm](https://cloud.githubusercontent.com/assets/6577830/12856187/a20c314c-cc11-11e5-8052-e9b8e82bd5cd.png)

Activated (0.16 opacity)
![screen shot 2016-02-05 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/6577830/12856189/a2101b54-cc11-11e5-93d3-c10b2cd7592a.png)

Active (1.0 opacity)
![screen shot 2016-02-05 at 2 06 47 pm](https://cloud.githubusercontent.com/assets/6577830/12856209/bbe3ea2e-cc11-11e5-8d9f-15115299e10d.png)

https://github.com/driftyco/ionic/blob/2.0/ionic/components/segment/segment.ios.scss

**Comment by jgw96** [comment]
Ill handle this one. (:

**Comment by brandyscarney** [comment]
@jgw96 Cool, thanks! Let me know if you have any questions!

**Comment by jgw96** [comment]
@brandyscarney no probs!

**Comment by jgw96** [comment]
@brandyscarney quick question, the activated class seems to be applied to the segment when the segment is selected, aka clicked, so shouldn't it be at 1.0 opacity then? So you would have hover with 0.1 opacity and then when the selected class is applied it goes to 1.0 opacity. With your pic/explanation above it seems that we want to make the opacity 0.16 when the activated class is applied, but that means when that segment is chosen it goes to 0.16 opacity, which is pretty ugly.

**Comment by brandyscarney** [comment]
Sorry I should have looked at the exact names before responding. So it should be:

`.segment-button:hover` 0.1 opacity
`.segment-button:active` 0.16 opacity
`.segment-activated` 1.0 opacity

The active is only while pressing on the button and then on release it changes to the solid background.

![2brjsj5s7x](https://cloud.githubusercontent.com/assets/6577830/12868375/485306a4-ccd3-11e5-80c5-eb56eb9a5cd6.gif)

**Comment by jgw96** [comment]
No, your perfectly fine, that makes much more sense now. Thanks for the response!

**Comment by jgw96** [comment]
Pull request submitted above! Thanks for the help @brandyscarney If i need to change anything just tell me and ill change it.

**Comment by brandyscarney** [comment]
@jgw96 Thank you for the PR! I haven't checked on this in awhile, but I see Adam merged it! I added a fix for the colorized segments, too. Thanks again. :smile:
