### ISSUE TITLE
item-remove-animate does not work with filter in ng-repeat

### ISSUE THREAD

**Issue by rolandoldengarm** [driftyco/ionic#5309]
http://codepen.io/anon/pen/LGBqzq
When deleting an item, always the last item is animated, not the item you delete.

Without the filter it works fine.

**Comment by aroncal** [comment]
:+1:

**Comment by VinceOPS** [comment]
+1

@jgw96 Hi, is this issue still on track?

Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#191
