### ISSUE TITLE
docs: add API documentation for setting the mode in Config

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5312]
```
@App({
  templateUrl: 'build/app.html',
  config: {
    mode: 'md'
  }
})
```

**Comment by mhartington** [comment]
Pretty sure this was in the component docs

**Comment by mhartington** [comment]
Added

**Comment by jvhe123** [comment]
Where do i put this code ?

**Comment by brandyscarney** [comment]
You can place it in the `ionicBootstrap`: http://ionicframework.com/docs/v2/api/config/Config/

**Comment by sollabeck** [comment]
@brandyscarney Since the original @App decorator is deprecated in the latest version, I'm still having trouble finding the correct spot to set the global style/mode. Looking through the config properties in the docs you linked above, there isn't a property for setting the global mode to 'ios'. I see 'iconMode', but I want to force iOS styling for everything in my app, not just icons.

**Comment by brandyscarney** [comment]
Yes, mode should be added to the table, but the code to set the mode is:

```
import { ionicBootstrap } from 'ionic-angular';

ionicBootstrap(AppRoot, customProviders, {
  mode: 'ios'
});
```

**Comment by yozman** [comment]
@brandyscarney 
the newest ionic2
there isn't any `ionicBootstrap`
where should I put the code ?

**Comment by mhartington** [comment]
So it didnt make it into the release docs, _my fault_, but you can modify the config like so.

```typescript
import { IonicApp, IonicModule } from 'ionic-angular';

@NgModule({
  declarations: [ MyApp ],
  imports: [
    IonicModule.forRoot(MyApp, {
      backButtonText: 'Go Back',
      iconMode: 'ios',
      modalEnter: 'modal-slide-in',
      modalLeave: 'modal-slide-out',
      tabsPlacement: 'bottom',
      pageTransition: 'ios'
    }, {}],
  bootstrap: [IonicApp],
  entryComponents: [ MyApp ],
  providers: []
})
```

The second parameter in the `IonicModule.forRoot()` method.

**Comment by yozman** [comment]
@mhartington thanks

**Comment by moda20** [comment]
Is this working the same way in ionic 3/4 with angular ?
