### ISSUE TITLE
Cordova CLI not detected with ionic info

### ISSUE THREAD

**Issue by anishone** [driftyco/ionic#5313]
I installed cordova using `sudo npm install -g cordova` and can see that its installed:
`sudo npm -g list | grep cordova`

```
├─┬ cordova@6.0.0
│ ├─┬ cordova-lib@6.0.0
│ │ ├── cordova-app-hello-world@3.10.0
│ │ ├─┬ cordova-common@1.0.0
│ │ ├─┬ cordova-js@4.1.3
│ │ ├── cordova-registry-mapper@1.1.14
│ │ ├─┬ cordova-serve@1.0.0
│ │ ├─┬ ionic-cordova-lib@5.1.10
│ │ │ ├── cordova-app-hello-world@3.9.0
│ │ │ ├─┬ cordova-js@4.0.0
│ │ │ ├── cordova-registry-mapper@1.1.14
│ │ │ ├─┬ cordova-serve@0.1.3
```

But, `ionic info` shows that Cordova CLI is not installed.
```
$ sudo ionic info
Your system information:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.53
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 6.4 Build version 6E35b
```

However, if I install cordova@4.2.0, then `ionic info` identifies that its installed. Strange!

I tried uninstalling and reinstalling ionic, ionic@beta.. but still it shows the same error. Am I missing something? Is there any way to let ionic know the path of Cordova? I want to use newer versions of cordova.

Thanks!

**Comment by anishone** [comment]
Thanks @tlancina . Let me know if you need any other debug info from me. I m still stuck with this :(

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#756
