### ISSUE TITLE
perf: Ionic Slide box Carousel Issue

### ISSUE THREAD

**Issue by rohit1barnwal** [driftyco/ionic#5315]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>

```
<ion-slide-box auto-play="true" show-pager="true" does-continue="true" on-slide-changed="slideHasChanged($index)">
	   	   	 <ion-slide>
		        <img class="slide-img" src="img/about-us (1).jpg"/>
		     </ion-slide>
   	 
		   	<ion-slide>
		        <img class="slide-img" src="img/bg - Copy.jpg"/>
		    </ion-slide>
	 
	    	<ion-slide>
		        <img class="slide-img" src="img/flat-screen.png"/>
		    </ion-slide>
	  
	    	<ion-slide>
		        <img class="slide-img" src="img/P10_DC_M3_1.jpg"/>
		    </ion-slide>
	   
	    	<ion-slide>
		        <img class="slide-img" src="img/phones-weather-demo@2x.jpg"/>
		    </ion-slide>
	    </div>
   </ion-slide-box>
```

i m creating image slide carousel with help of this code.
Code is working fine but not support all mobile devices and if mobile device size is change the image carousel is not fit according to mobile device, another issue is if we change the portrait to landscape mode image carousel slide is not working and supporting according the size.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As slidebox has been deprecated i will be closing this issue for now. Thanks for using ionic!
