### ISSUE TITLE
Confirm alert does not work well with long body

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#5316]
I am trying to use a confirm alert for a disclaimer that a user has to accept or decline. As it is the nature of these things, they are quiet long. This displaces the alert's title and the buttons are not visible anymore.
![bildschirmfoto 2016-02-03 um 13 51 59](https://cloud.githubusercontent.com/assets/4137975/12782719/59f88e18-ca7d-11e5-97b3-2d27e1bc7ed0.png)

Here is my code, where lorem is a really long disclaimer string:

```typescript
            let confirm = Alert.create({
                title: "Disclaimer",
                message: lorem,
                buttons: [
                    {
                        text: "Decline",
                        handler: () => {
                            console.log('Disagree clicked');
                        }
                    },
                    {
                        text: "Accept",
                        handler: () => {
                            localStorage.setItem("isFirstLogin", "false");
                            this.performLogin();
                        }
                    }
                ]
            });
```

**Comment by brandyscarney** [comment]
This will be fixed when beta.2 is released. Thanks for the issue!
