### ISSUE TITLE
Dependency Injection using providers and @Inject does not work for Modal created from a Component

### ISSUE THREAD

**Issue by russli1993** [driftyco/ionic#5321]
I have the following Component:
```
@Component({
        ....
        providers: [provider("optionStore", {useValue: createStore(....)})]
   })
   class Picker{
           openModal () {
                 var modal = Modal.create(MyModal);
                  this.nav.present(modal);
          }
   }

@page({...})
   class MyModal {
          constructor(@Inject("OptionStore") private store){

          }
}
```

The following error is shown: EXCEPTION: No provider for Store! (MyModal -> OptionStore)
this DI pattern works if I put providers in `@app`

**Comment by adamdbradley** [comment]
This is how it will have to be, because the modal isn't actually getting created from within your component, but it's being attached to the root of the app.
