### ISSUE TITLE
bug: White screen on android or android user agent

### ISSUE THREAD

**Issue by walmon** [driftyco/ionic#5325]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When on Android or user agent android, the ui-view returns without opacity 1, which leads to a white screen.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Which version of Ionic are you using?

**Comment by walmon** [comment]
1.7.13

**Comment by brandyscarney** [comment]
Can you run `ionic info` from within your project folder and then paste the line containing:

```
Ionic Version:
```

I believe you are using a 1.x project as that CLI version doesn't work on 2.x projects.

**Comment by jgw96** [comment]
I can confirm that the latest ionic 2 build works fine on Android 4.4.4 on a Samsung Galaxy Note 3. Also working perfectly fine on my Nexus 6 running 6.0.1.

**Comment by walmon** [comment]
Yeah, its 1.7.13

**Comment by tlancina** [comment]
I'm going to close this as it's not a v2 bug.

@walmon if you think think there is a bug in v1, could you please open a new issue with:

1) The output from `ionic info`

2) What device/platform you're seeing the issue on

3) Code or steps to reproduce the problem

Thanks!
