### ISSUE TITLE
Missing "Angular was updated to Beta 2" note in CHANGELOG

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5326]
Happened between 53 and 54:
https://github.com/driftyco/ionic/commit/fe95281b249998635f0f88b685144e4b44e29c82#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

2.0.0-alpha.51 had a nice breaking changes note regarding the upgrade to beta 1:
https://github.com/driftyco/ionic/blob/968cf0239da2940a1be26a08393bf958961158f0/CHANGELOG.md#breaking-changes-2

**Comment by tlancina** [comment]
Thanks! This was the first changelog that was completely autogenerated, so it missed some things.
