### ISSUE TITLE
TypeScript 1.8.0 errors in starters

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic#5327]
From https://github.com/driftyco/ionic/issues/5264, upgrading to TypeScript 1.8.0 breaks non TS starters because of https://github.com/Microsoft/TypeScript/issues/6766.

Looks like this has been fixed in TypeScript nightly, but will leave this open for reference until it's been resolved.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#755
