### ISSUE TITLE
some bug in refresher

### ISSUE THREAD

**Issue by vactorlao** [driftyco/ionic#5328]
ionic version: 2.0
Test platfrom: ios & android

First I scroll down to end of list, then I pull down try to scroll up to top of list, but activated the event of refresher, I try same to the demo, there are the same.

http://ionicframework.com/docs/v2/demos/refresher/?ionicplatform=ios

![image](https://cloud.githubusercontent.com/assets/7175977/12807440/2f0e58cc-cb4a-11e5-9be8-838add93e09f.png)

**Comment by brandyscarney** [comment]
There is an open issue [here](https://github.com/driftyco/ionic/issues/5207) for problems with refresher so I am going to close this, thank you!
