### ISSUE TITLE
docs: Tabs.rootNav() is a getter, not a regular method

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5329]
From the Tabs docs I would assume `tabs.rootNav()` is the correct syntax
```
 rootNav()

Returns the root NavController. Returns null if Tabs is not
within a NavController.
```
http://ionicframework.com/docs/v2/api/components/tabs/Tabs/

___

However, this produces: `EXCEPTION: TypeError: _this.tabs.rootNav is not a function. (In '_this.tabs.rootNav()', '_this.tabs.rootNav' is an instance of Nav)`

Turns out rootNav() is a getter, `tabs.rootNav` is the way to go...
```
 get rootNav() {
```
https://github.com/driftyco/ionic/blob/bcda08e/ionic/components/tabs/tabs.ts#L334

Assuming the docs are auto-generated: maybe the docs parser needs getter-awareness?

**Comment by adamdbradley** [comment]
Yeah you're right, we'll have to fix up how our docs auto-generation works. Thanks 

cc @mhartington

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#420
