### ISSUE TITLE
Increase icon size when inside of a segment button

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5330]
_Do not increase segment height_. Ours:

![screen shot 2016-02-04 at 11 18 41 am](https://cloud.githubusercontent.com/assets/6577830/12821404/53032582-cb31-11e5-8a7a-b6a49f6b9aa3.png)

iOS:

![slack for ios upload png](https://cloud.githubusercontent.com/assets/6577830/12821424/6b0026bc-cb31-11e5-989e-12c56eb58355.jpeg)

**Comment by brandyscarney** [comment]
The following CSS seems to do it, need to make sure there are no side effects:

```
.segment-button ion-icon {
  font-size: 2.2rem;
}

.segment-button {
  max-height: 2.4rem;
}
```

**Comment by manucorporat** [comment]
@brandyscarney I am working in the button flex issues in iOS/safari and I have a question: why some of max-height, min-height properties are relative?
like:
```css
.segment-button {
  max-height: 2.4rem;
}
```
?

From my understanding... it does not make sense to have a segment or button with a relative height. If you want to use bigger buttons, there is a "larger-button" class, and of course if there is a strange use case where a bigger segment is required, the developer can write their custom CSS.

I think we could reduce the scope of CSS problems in buttons by "hardcoding" some of the margin/padding/height values. what do you think?

**Comment by adamdbradley** [comment]
Well it's the hardcoding that often gets us into troubles, because users want to change the default to what looks good for their app. So using relative units allows things to adjust when they make changes.

**Comment by brandyscarney** [comment]
Increased icon size for iOS and md. This will probably need to be revisited if people put an icon and text in the button, since those will be different sizes.
