### ISSUE TITLE
[v2] Testing samples and docs

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5331]
Hi, I have been trying to implement karma + jasmine with Ionic v2 this week and the lack of documentation, samples and knowledge are getting in the way. I tried to use [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) as base, but I it is not working for me. Maybe someone from the team is able to create a simple sample.

**Comment by tlancina** [comment]
Hey this is definitely an area that could use some documentation and examples.  Unfortunately other than our own tests we don't have a good story on the "right" way to do tests at this point.

I believe the docs are incomplete, but https://angular.io/docs/ts/latest/testing/ might be helpful or you could check in on the forums: https://forum.ionicframework.com/ to see if anyone else has other resources.

**Comment by BugsBunnyBR** [comment]
I found [this](https://github.com/lathonez/clicker) repo where @lathonez got testing working nicely with ionic2.beta.0.
I tried the angular documentation and ionic forums before I found that repo, but I am new to web development technologies (I am an Android native developer discovering Ionic ) and the outdated angular documentation + the many constants changes from ionic, angular and in the dependencies makes it very hard to a newbie like me to put the testing frameworks to work.

Even if the 'right way' is not defined, 'some supported way' is better than 'no way'. I think, I could try a PR to the conference-app with the testing configurations from @lathonez repo, but at each angular or ionic update it would broke again...

**Comment by damienadermann** [comment]
:+1:  I'm in the same situation. New to ionic and find it a joy to use but I haven't successfully set up a test environment. Its also tricky because the ionic command hides away some of the build config.

**Comment by lathonez** [comment]
@BugsBunnyBR - nice one for raising this.

I spent a lot of time getting the test environment set up in https://github.com/lathonez/clicker, wrestling with lack of documentation / resources and ever changing specifications (as can be totally expected given the nature of Angular2 and Ionic2).

As it seems to be helping a few people, I'll probably bite the bullet and blog something.

> Even if the 'right way' is not defined, 'some supported way' is better than 'no way'.

I agree with this. One of the major advantages of Angular2 is testability, but thus far we are unable to utilise this in our Ionic2 projects.

@damienadermann / anyone else who is struggling with this, I encourage you to give the setup on https://github.com/lathonez/clicker a try, open an issue if you're struggling to get things going and I'll do my best to help out.

@tlancina - thanks for all the great work on Ionic2 so far, keep us posted on the direction of the testing / let us know if we can help out.

**Comment by damienadermann** [comment]
@lathonez - Thanks for the advice

I'll try pulling in your set up this week.

**Comment by lathonez** [comment]
Am part way through writing it up @ [http://lathonez.com/2016/02/21/unit-testing-an-ionic-2-project/](http://lathonez.com/2016/02/21/unit-testing-an-ionic-2-project/
)
hope to have something finished this week.

**Comment by BugsBunnyBR** [comment]
@lathonez , the link is broken, would you mind to update?
@tlancina , does the ionic2 docs are open source? Maybe we can contribute with the docs for testing.

**Comment by ciekawy** [comment]
I'm also interested in this topic. I've found this http://stackoverflow.com/questions/35290176/executing-typescript-jasmine-tests-via-webpack-terminal-to-test-angular2 and I guess this might be pretty similar concept to how current Ionic 2 build stack looks like. 

@lathonez I'm curious what your concept looks like as well...

**Comment by BugsBunnyBR** [comment]
[just thinking in the future and standards] The work in clickers repo is a very good start, it enables ionic2 developers to start testing, but I think we should think in some things to the future...

- Angular docs prefer the pattern "source together with tests"  https://angular.io/docs/ts/latest/testing/first-app-tests.html, so some parameter pointing where to look for the test files could be useful for configuration.

- Having two separated build configs may be a pain in the ass to keep updated. (try update the clickers repo to ionic beta 1 e angular 2 beta 6 and you will understand).

- The possibility to run individual test files;

- The possibility to run test files without recompile the source;

Sorry if I said something naive, I am still learning angular/ionic/typescript;

**Comment by ciekawy** [comment]
What is currently blocking me with clickers approach is that all the tsc settings are way more strict that the ionic ones so I have tons of TS errors and I found it not that easy to adjust the config or update my sources. Also even if the flow succeeds to karma I'm getting some confusing messages:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) WARN: 'DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask'
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: '

eval code
eval@[native code]
__exec@http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:1395:16
execute@http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:3767:22
linkDynamicModule@http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:3126:36
getModule@http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:3094:26
http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:3130:25
require@http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?38538ebca96bc7b222f7e7ba15943f173a485f6e:3740:34
```

And I'm not sure where to look for the tests haven't been executed...

As I've recently wrote simple test for the Ionic2 itself I liked very much all the logs provided there by the karma. This makes me wonder to have Ionic2 project testable in a similar manner.

**Comment by BugsBunnyBR** [comment]
@ciekawy , in the gulpfile.js, lne 59, remove the entry 'test.lint' to ignore lint stuff

**Comment by lathonez** [comment]
@BugsBunnyBR - updated thanks.
@ciekawy - [raise an issue on the clicker repo](https://github.com/lathonez/clicker/issues/new) if you need further assistance with that approach.

Re [http://stackoverflow.com/questions/35290176/executing-typescript-jasmine-tests-via-webpack-terminal-to-test-angular2](http://stackoverflow.com/questions/35290176/executing-typescript-jasmine-tests-via-webpack-terminal-to-test-angular2) - looks really interesting - the reason I went with Gulp was that Ionic 2 was using it back then. Would be great to remove a tool.

If there's any consensus on an approach perhaps we could collaborate on an [Ionic 2 seed](https://github.com/mgechev/angular2-seed) style project, based on whatever the current `ionic start MyApp --ts --v2` output is.

**Comment by lathonez** [comment]
If anyone would like to contribute @BugsBunnyBR  and I are looking at combining the ground work in [Clicker](https://github.com/lathonez/clicker) with the [Angular 2 Style Guide](https://github.com/mgechev/angular2-style-guide#testing) and [other good ideas](https://github.com/driftyco/ionic/issues/5331#issuecomment-187768377) from this thread into a fork of the Ionic 2 base app.

Our fork is here: [https://github.com/BugsBunnyBR/ionic2-app-base](https://github.com/driftyco/ionic/issues/5331#issuecomment-187768377)

The idea being that we can get a PR back into main and everyone can start testing without all the drama.

**Comment by ciekawy** [comment]
I like the idea of providing common way for testing ionic2 apps and for sure would like to contribute if this is the easiest way to go. 

What still bothers me is the idea of having all the tests integrated into ionic serve. I wonder if this is really that complex. Actually I'm surprised that there is no such configuration combining webpack, live reload and some testing framework - it is not even directly mentioned - maybe I'm getting sth wrong but what I would expect is have whatever tests being runned by webpack after it compiles all the stuff.

To have test being runned by webpack we would probably need a webpack plugin - I think that karma plugin would give a choice what testing framework to use. Just loudly thinking and would be happy if someone can correct me here.

**Comment by stefanhuber** [comment]
Hi all.

As I was stuck with testing (jasmine, karma, angular2, etc) as well, I tried to come up with the simplest solution I could think of. The other folk with the clicker demonstration seemed very nice, but complex code and configuration as it goes for my perception...

I am working on an open source cryptocurrency app, where you can see how i do the testing: https://github.com/getbitpocket/bitpocket-mobile-app

- added `*.spec.ts` files together with the other source code
- added karma config
- added two gulp tasks `test-build` and `test` for execution

angular DI works and everything (CI travis...). Generally everything concerning business logic testing can be done... One thing which I am not sure yet is how to properly setup e2e testing. I did some experimenting with appium (http://appium.io/), but the configuration is quite tedious.

**Comment by abierbaum** [comment]
The lack of clear documentation and helpers for testing still seems like a big issue.  I spent the better part of a day trying to add some tests based upon the execellent work lathonez did  https://github.com/lathonez/clicker.  I have basic tests working, but I can't get anything that makes use of form validation or click event callbacks to work quite right.  I also had to extend/create quite a few new mocks and I am not sure if those are all setup correctly.  I for one would love to see a good set of documentation / helper code around testing in Ionic.  As it stands right now we are having to break our company coding standard and simply skip tests for ionic applications. :(

**Comment by RomanKisilenko** [comment]
Hello, is there anybody on Ionic team who can suggest if this issue is planned to be fixed for v2 final release. It is indeed a critical item for real world projects. And as per my observations many teams are already using it in production-ready applications.

**Comment by rossholdway** [comment]
I agree with @RomanKisilenko, a standardised test setup for ionic (at least unit testing) is something that should really be documented for Ionic 2!

**Comment by abierbaum** [comment]
Checking in again.  Still having trouble with this and don't see a path forward.  If anyone has some good ideas here, please share.

**Comment by brandyscarney** [comment]
Hey everyone, we've added an official application with unit testing here: https://github.com/driftyco/ionic-unit-testing-example

Here's a short blog post on it: http://blog.ionic.io/basic-unit-testing-in-ionic/

I will be closing this issue for now, but please let us know on that repository if you have any feedback! Thanks!
