### ISSUE TITLE
bug: Two taps required on $ionicModal input fields iOS9

### ISSUE THREAD

**Issue by artzstudio** [driftyco/ionic#5333]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>Open this CodePen in Safari on iOS 9: http://codepen.io/daveartz/full/KVBJwg/

When using Safari on iOS 9 it takes two taps to enter an input field and `focusFirstInput` does not work.

This appears to occur when there is more than one `$ionicModal` present in a view, as I could not reproduce with one `$ionicModal`.

On Chrome desktop this issue is not present. I have not tested in other iOS versions or Android.</span>

Related forum link: https://forum.ionicframework.com/t/two-taps-required-on-input-fields-when-multiple-ionicmodal-instances-in-view/42724
<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by artzstudio** [comment]
Yes, open the above CodePen in Safari on your iOS browser.  It is referencing the 1.x nightly so I assume that is the latest version.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#192
