### ISSUE TITLE
On text box border click showing keyboard without focusing the textbox on iOS devices.

### ISSUE THREAD

**Issue by mitiaptest** [driftyco/ionic#5339]
Hello Guys,

On text box border click showing keyboard without focus on textbox on iOS devices.

Thanks,
Mit

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We just need a little more info from you to effectively test and debug your issue. Would you be able to provide a code sample, plunkr or codepen for us that we can use to reproduce your issue? Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by Naved-Biz4** [comment]
Hi, I am able to reproduce the same issue mentioned by Mit, Can anyone help please?
