### ISSUE TITLE
how can ion-list item swipe back automatically?

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#5340]
Hello guys!

I am using ion-list where each item can swipe. 
After clicking the button i would like that the item swipe back to its original position.

How can be done?

Thank you!

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or on our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
