### ISSUE TITLE
bug: WKWebView blocks Tabs during momentum-scroll

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#5343]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Tested with WKWebView Plugin:
https://github.com/Telerik-Verified-Plugins/WKWebView

WKWebView changed scrolling events so that even when momentum-scrolling is active, scroll events are fired. This seems to block any other interaction (e.g. switching to another tab) while momentum-scrolling is active.</span>

![wkwebview_momentum](https://cloud.githubusercontent.com/assets/5305150/12844394/5403852a-cbff-11e5-936c-196031d023ba.gif)

**Comment by adamdbradley** [comment]
This may be an unsolvable issue for the time being. We'll keep looking for solutions and working on it. Thanks
