### ISSUE TITLE
How to create user-defined components in ionic2?

### ISSUE THREAD

**Issue by wangqianbo** [driftyco/ionic#5344]

**Comment by manucorporat** [comment]
```js
@Component({
 selector: "my component"
})
class MyComponent() {
}


@Page({
directives:[MyComponent]
})
class MyIonicPage { }
```

alternative you can provide the directive directly to the @App decorator so it is available globally.

**Comment by brandyscarney** [comment]
Closing this as it is not an issue with the framework. Please ask questions on the forums: https://forum.ionicframework.com/c/ionic-2 or join the worldwide Slack group and ask in the `#ionic-v2` channel: http://ionicworldwide.herokuapp.com/

There are many topics on the forums for components already: https://forum.ionicframework.com/t/how-to-make-a-directive-or-equivalent/40428
