### ISSUE TITLE
Right button padding inside .bar

### ISSUE THREAD

**Issue by peterpan666** [driftyco/ionic#5345]
Hi!

On these lines https://github.com/driftyco/ionic/blob/v1.2.4/scss/_bar.scss#L260, shouldn't the "5px" rely on the `$bar-padding-*` variable?

Thanks for the awesome work!

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by peterpan666** [comment]
My question is more a suggestion/improvement in fact or I didn't get clearly what this line is intended... Do I still have to ask somewhere else?

**Comment by jgw96** [comment]
@peterpan666 sorry I wasn't more clear! Usually suggestions or improvements are better discussed on our forum or slack channel so that's why I pointed you towards those channels. BTW awesome Github username

**Comment by peterpan666** [comment]
Ah ah ok no problem and thanks!
