### ISSUE TITLE
bug: Range input does not slide during/after text input

### ISSUE THREAD

**Issue by artzstudio** [driftyco/ionic#5346]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>Open this CodePen in Safari on iOS 9: http://codepen.io/daveartz/pen/PZyGKe

Step 1: Open Modal
Step 2: Position cursor in an input field.
Step 3: Observe you cannot bring focus to or move range sliders.
Step 4: Observe the same thing happens in a non-modal on "About" tab.

I found that this issue does not immediately appear to be present outside of a tab view: http://codepen.io/daveartz/full/qbJaNN/

This is currently a blocker user experience bug for me and I can't launch my product without a resolution.  Please advise!</span>

<span is-issue-template></span>

**Comment by DrakeWitt** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#194
