### ISSUE TITLE
Style icons on top of text in an option button

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5352]
![screen shot 2016-02-05 at 7 02 43 pm](https://cloud.githubusercontent.com/assets/6577830/12862617/1a880ac8-cc3b-11e5-845f-c9349e5b21fa.png)

**Comment by brandyscarney** [comment]
Following styles achieve this:

```
  ion-item-options button {
    font-size: 14px;
    flex-direction: column;
  }

  ion-item-options ion-icon {
    padding-right: 0;
    padding-bottom: 0.3em;
  }
```

if it is desired

![screen shot 2016-02-05 at 7 10 35 pm](https://cloud.githubusercontent.com/assets/6577830/12862726/34c3b3a0-cc3c-11e5-95db-6e1483799f68.png)

**Comment by manucorporat** [comment]
@brandyscarney flex does not work in safari in button elements, in fact I am preparing a PR to get rid of it.

**Comment by brandyscarney** [comment]
@manucorporat ok, don't worry we won't touch the buttons while you're working on them.  :stuck_out_tongue_winking_eye:

**Comment by manucorporat** [comment]
@brandyscarney https://github.com/driftyco/ionic/pull/5363

**Comment by brandyscarney** [comment]
Thanks for the PR! Closing this issue. :)
