### ISSUE TITLE
perf: Performance issues with ion-checkbox and *ng-For

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#5353]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>This was tested in android device running 6.0 and 4.1, the computer web browser 'ionic-serve', genymotion emulator running android 4.4 and windows 10 platform.

Here is the app I did using this:
https://github.com/Bandito11/cibum2/blob/master/app/pages/main/ingredientes.html

Issue:
When iterating through the array list (which have over a 100 items) using an ion-checkbox the performance is ridiculously bad. When taking out the ion-checkbox and using <input type="checkbox"> it iterates as fast as expected.

More details here:
https://forum.ionicframework.com/t/ngfor-performance-issues-when-getting-a-long-list-of-items/43010</span>

<span is-issue-template></span>

**Comment by tonirilix** [comment]
I was able to reproduce this issue in the current version of ionic (RC3) using the tabs template. 
Same behavior happens to me after about 100 ion-checkbox elements. The page will be laggy as well as the touch effect.

I did the same tests from the issue description and using a normal input type checkbox the screen will render fast.

Is there any chance we can reopen this issue please?
Thanks!

**Comment by moritzgloeckl** [comment]
This is somehow still an issue for us... Using the ion-checkbox makes our scroll list unusable even with virtual scroll.
