### ISSUE TITLE
bar-button-menutoggle class causing right button misaligned

### ISSUE THREAD

**Issue by quanghoc** [driftyco/ionic#5357]
There is a small CSS bug in Ionic 2:

```
<ion-navbar *navbar>
  <ion-title>Getting Started</ion-title>

  <ion-buttons start>
    <button menuToggle="leftMenu">
      <ion-icon name="menu"></ion-icon>
    </button>
  </ion-buttons> 
  <ion-buttons end>
    <button menuToggle="rightMenu">
      <ion-icon name="menu"></ion-icon>
    </button> 
  </ion-buttons> 
</ion-navbar>
```

It resulted this

![screen shot 2016-02-07 at 1 26 24 am](https://cloud.githubusercontent.com/assets/2769972/12871663/dc3a62b6-cd39-11e5-906f-8f4d192ef486.png)

I have to override with this:

```
.bar-button-menutoggle {
  display: inline-flex;
}
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Would you mind updating your project to the latest version of Ionic 2 and seeing if you still have this issue? Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
