### ISSUE TITLE
bug: $ionicRefresher exception: Uncaught TypeError: Can

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#5358]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When switching states it appears randomly, however all of my states use the ion-refresher module.
I can assure that during the exception no refreshing is in progress.
The exception is:
```
**Uncaught TypeError: Cannot read property 'classList' of null**
```

The location is in the $ionicRefresher module, 
```javascript
function setScrollLock(enabled) {
      // set the scrollbar to be position:fixed in preparation to overscroll
      // or remove it so the app can be natively scrolled
      if (enabled) {
        ionic.requestAnimationFrame(function() {
          scrollChild.classList.add('overscroll');
          show();
        });

      } else {
        ionic.requestAnimationFrame(function() {
          **scrollChild.classList.remove('overscroll');  <--- EXCEPTION**
          hide();
          deactivate();
        });
      }
    }</span>

<span is-issue-template></span>
```

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by rmit-s3578933-shiran-ekanayake** [comment]
I'm facing this issue on my ionic project. I use `ion-refresher` in my app and when I pull to refresh, every time I get the following exceptions.

`Uncaught TypeError: Cannot read property 'style' of null
Uncaught TypeError: Cannot read property 'style' of null
Uncaught TypeError: Cannot read property 'classList' of null`

**Comment by gyleg5** [comment]
I am still facing this issue as well in our ionic1/angular1 project.


Message | Uncaught Exception: Uncaught TypeError: Cannot read property 'classList' of null at (compiled_code):26
-- | --
TypeError: Cannot read property 'classList' of nullat file:///android_asset/www/default/js/vendor.js:26:15686

Same place Barocsi pointed out.
