### ISSUE TITLE
npm install ionic issue?

### ISSUE THREAD

**Issue by ved54321** [driftyco/ionic#5359]
While running npm install ionic i am getting the follwing issue,please help

> node-sass@3.4.2 install D:\vedapp\node_modules\ionic\node_modules\node-sass
> node scripts/install.js

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_
odules\\npm\\bin\\npm-cli.js" "install" "ionic"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file C:\Program Files\Java\jdk1.7.0_06\lib
npm ERR! path C:\Program Files\Java\jdk1.7.0_06\lib
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Java\jdk1.7.0_06\lib

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn C:\Program Files\Java\jdk1.7.0_06\lib ENOENT
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vedapp\npm-debug.log

D:\vedapp>npm install ionic

D:\vedapp>npm install ionic

D:\vedapp>npm install
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\
in\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_
odules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path D:\vedapp\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'D:\vedapp\package.json

npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vedapp\npm-debug.log

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us!  Are you still having this issue?

**Comment by brunowego** [comment]
@ved54321 I solve this using a old version of node. Try use [nvm](https://github.com/creationix/nvm) to do this.

```bash
nvm install v4.0.0
```

**Comment by jgw96** [comment]
@brunowego Have you gotten a chance to install it with a newer version of node? Like 5.8.0?

**Comment by brunowego** [comment]
@jgw96 I have tested with `v5.4.1` and not works for me.

**Comment by jgw96** [comment]
@brunowego im so sorry it has taken me this long to get back to you. Does this still happen with the latest version of the ionic cli? Thanks!

**Comment by brunowego** [comment]
@jgw96 v4.4 works 👍

**Comment by jgw96** [comment]
@brunowego awesome! Good to hear! Thanks for using ionic!
