### ISSUE TITLE
v2 inset list - documentation

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5361]
On http://ionicframework.com/docs/v2/components/#inset-list it says

"By default, lists have an outside margin, to remove that add the inset property to make the list flush with the parent container."

I may be reading the documentation wrong, but pretty sure that currently by default there is NO margin, and if you add the inset property, a margin is added

i.e. functionality is good, but documentation is back to front.

**Comment by mhartington** [comment]
Updated via https://github.com/driftyco/ionic-site/commit/8f0f0198a85b7efa0ead98e8f792e1e8a18afcb2
