### ISSUE TITLE
[v2] Backwards compatibility with v1 CSS stylesheets

### ISSUE THREAD

**Issue by roblav96** [driftyco/ionic#5362]
Today I tried including the v2 ionic stylesheets in my v1 project. It seems that all the directive names have changed.

Are there any plans to support v1 projects with v2 stylesheets?

**Comment by tlancina** [comment]
Hey thanks for the issue.  Not at this time, in the same way that v2 components are not backwards compatible with v1, the CSS would be similarly very difficult to make work for both.
