### ISSUE TITLE
v2 - ion-checkbox - no-lines

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5371]
ion-list has attribute no-lines if you don't want lines

ion-checkbox adds a line below by default. Please could you add no-lines attribute to ion-checkbox if we dont want the line

Thanks!

[Not sure if this should be no-lines to be consistent with ion-list, or no-line, as only 1 line added ;) ]

**Comment by alexbainbridge** [comment]
OK turns out the line is because I wrapped it in ion-item !

Still for ion-checkbox, also for ion-toggle, wrapping with ion-item gives it immediate nicely spaced UI (and makes it work), but comes with a line....  I dunno, having capability to do ion-item without a line would be great ;)

**Comment by brandyscarney** [comment]
@alexbainbridge What version are you using? We made it so `ion-checkbox` and `ion-toggle` are no longer stand-alone components in alpha.53. They now go inside of the `ion-item`:

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-alpha53-2016-01-28

**Comment by alexbainbridge** [comment]
Hello @brandyscarney . Latest (56 or so)

Choices therefore are
- wrap in ion-item - and the layout works, the JS works, but you have a line
- do not wrap in ion-item, the JS doesn't work actually (e.g. won't toggle), but no line

Hence the question is, can you have a ion-item without a line? As you can't use without ion-item now

(YES can do this in CSS etc, but that is a bit of a bore, and would be nice to be an attribute - e.g. if you just want a toggle and no line)

**Comment by brandyscarney** [comment]
@alexbainbridge Can you paste some of your markup? The `no-lines` attribute works on an `ion-item` as well:

```
  <ion-item no-lines>
    Single line item with no lines
  </ion-item>
```

**Comment by alexbainbridge** [comment]
Oh dear. Sorry. You are right. Apols for wasting your time on this one

**Comment by brandyscarney** [comment]
Not a problem! I wasn't sure if that was what you were asking for. We still need to document this so it's our fault. :smile:
