### ISSUE TITLE
ionic.Platform.isAndroid() returns true in Chrome for Android

### ISSUE THREAD

**Issue by m52go** [driftyco/ionic#5372]
Not sure if this is intentional, but it surprised me when running my Ionic app in Chrome for Android. There are certain features I need to conditionally disable for the web, such as the Camera, and there's no built-in way I'm aware of to do this.

So now that Ionic supports the mobile web, it would be very helpful to pin down more specific functions for ionic.Platform, particularly regarding mobile web. 

Right now, I'm looking for the `platform-browser` class in `<body>` but it's clunky and I'm not sure how reliable it is.

**Comment by jgw96** [comment]
Hey! So, the correct way you would want to be testing for if your running on the web or on a device would be to use the ionic.Platform.isWebView(). Here is a good link to learn about that method: http://ionicframework.com/docs/api/utility/ionic.Platform/  Thanks!

**Comment by m52go** [comment]
Oh my. Sorry, not sure how I missed that. Thanks!!

**Comment by anooppvkeloth** [comment]
i think you are using chrome simulator mode which is selected an ios device..try with closing simulator view

**Comment by abouelaiz** [comment]
you can use window.cordova &&  ionic.Platform.isAndroid()
