### ISSUE TITLE
bug: Scrollable content overlaps header

### ISSUE THREAD

**Issue by Saegrov** [driftyco/ionic#5380]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When typing text into an input field, and then clicking a button that removes the input-field seems to bug out the ion-content if it is scrollable.

See codepen: http://codepen.io/Saegrov/full/pgQmmb/

Steps to reproduce:

1. Scroll down to the input field.
2. Type some text and click the submit text.
3. The scrollable content will overlap the header.
4. The heigh of the scrollable content is wrong.

I've noticed that if you click somewhere else on the screen to hide the keyboard, everything works as expected.</span>

<span is-issue-template></span>

**Comment by Saegrov** [comment]
Btw. This is also reproducible in Chrome Dev tools if you select an apple device in the device list.

**Comment by Saegrov** [comment]
I manged to find a workaround by creating a directive:

```
angular
    .module('mySurroundings')
    .directive('keyboardHideRemoveStyle', keyboardHideRemoveStyle);


  /** @ngInject */
  function keyboardHideRemoveStyle($window) {
    var directive = {
      link: link,
      restrict: 'A'
    };
    return directive;

    function link(scope, element) {

      if (ionic.Platform.isIOS()) {
        $window.addEventListener('native.keyboardhide', hideOverflow);

        scope.$on('$destroy', function () {
          $window.removeEventListener('native.keyboardhide', hideOverflow);
        });

      }
      function hideOverflow() {
        element.css(
          {
            overflow: 'hidden',
            height: 'auto'
          }
        );
      }
    }
  }
```

It can be used like this:

`<ion-content keyboard-hide-remove-style> </ion-content>`

It feels hacky but it works.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We do not plan on making any changes to how ionic 1 handles the keyboard or scrolling at this time, and since there is a workaround for this i will be closing this issue for now. Thanks for using Ionic!
