### ISSUE TITLE
ion-slides option cannot config paginationType

### ISSUE THREAD

**Issue by moelover** [driftyco/ionic#5382]
ion-slides in ionic 1.2.4 

cannot config paginationType in options

```javascript
$scope.options = {
    speed: 1000,
    pagination: '.swiper-pagination',
    paginationType: 'fraction'
  }
```

it alway to use bullets type

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! As this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
