### ISSUE TITLE
ion-slide-box stoped does-continue="true" after click event fired on ion-slide

### ISSUE THREAD

**Issue by oumayma-ltaief** [driftyco/ionic#5383]
Hello, I'm using ion-slide-box and I'm making a click event on ion-slide to display a gallery in ion-modal; but after hiding the ion-modal the property does-continue="true" disappeared.
Any suggestion to fix that please?

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! We just need a little more info from you so that we can better help you with this issue. Would you mind running `ionic info` and posting the output here? Also, could you provide a plunkr or codepen for us? Thanks again!

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
