### ISSUE TITLE
ion-slide-box setting active-slide from Angularjs data

### ISSUE THREAD

**Issue by oumayma-ltaief** [driftyco/ionic#5384]
Hello, I want to set the active-slide property to active-slide with angularjs data (index) passed from my controller ($scope.myVar=1;), here is my html code part: 

  <ion-slide-box class="ionSlideHome" does-continue="true"
	auto-play="true" show-pager="true" slide-interval="6000"
	ng-if="allImages.length" delegate-handle="slideHome" active-slide="{{myVar}}"> 
	  <ion-slide ng-repeat="image in allImages" ng-model="image">
	        <img ng-src="{{image.src}}" class="imgSlideHome" />
      </ion-slide>
    </ion-slide-box>

But with this new setting, the slide-box disappeared.
How could I fix this problem please?

**Comment by jgw96** [comment]
Hello! As `ion-slide-box` has been depecrated i will be closing this issue for now. Look out for alot of updates to slides in the near future! And thanks for using Ionic!
