### ISSUE TITLE
Resolvers need to have a way to honor view cache rules

### ISSUE THREAD

**Issue by ilyastam** [driftyco/ionic#5385]
**Type: Bug**

It appears that resolvers still fire when view is cached. Here is what happens to a cached view:
```
1. resolver loads
2. controller doesn't load because view is cached
3. view is loaded from cache
```

Forcing resolvers to honor cache would be very useful.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are not planning on adding any new behavior to Ionic 1 at this time, and because of that I will be closing this issue for now. Thanks for using Ionic!
