### ISSUE TITLE
chips: UI is messed up

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5386]
Need to fix the UI for this, add them to e2e tests and then get them documented when we feel comfortable with them.

**Comment by brandyscarney** [comment]
We could probably make this into a component.

**Comment by cesar-oyarzun-m** [comment]
@brandyscarney hey do you know if there is other way of doing chips in ionic? I need chips in my app but I'm using 1.3.1, I don't want to update just for this. Do you know where can I find documentation about how to use chips in ionic also?

**Comment by faraazc** [comment]
@brandyscarney hey I am expecting this in beta.11.hope I will get this.thanks

**Comment by brandyscarney** [comment]
@cesar-oyarzun-m Right now the chip component is purely css. All of the Sass is here: https://github.com/driftyco/ionic/blob/master/src/components/chip/chip.scss

And the different ways to write it are in each of these folders: https://github.com/driftyco/ionic/tree/master/src/components/chip/test

It probably depends some on other component styling but it can be added with css.

**Comment by leetheguy** [comment]
I would like to try my hand at fixing this, turning it into a component, and helping with the documentation for it.

I've read the contributing guide and forked the repo. Should I create a pull request now or after the work is done?

**Comment by jgw96** [comment]
Hello @leetheguy ! Awesome to hear that your interested in contributing to Ionic! I would recommend getting it good and solid on your local machine before submitting a pr. Also, here are a few tips for contributing:

1. `git status` will help you keep track of your changes
2. Try to keep the number of commits to a minimum if possible
3. Try to make sure your commit messages are concise if possible
4. Make sure you have a ton of fun and feel free to reach out and ask questions if needed!

Thanks!

**Comment by leetheguy** [comment]
Cleaned this up. Fixed the CSS. Made it into a component. X button works. Added whitelist control for elements so only those in the spec (avatar, image, text) can be added. The e2e looks good.  No documentation yet. Creating pr.

**Comment by devarg** [comment]
Chip with icon is messed up in RC

![chip rc](https://cloud.githubusercontent.com/assets/10100650/19293795/b25453d0-8ffd-11e6-8ada-7f19dda10b64.png)


And if you try to add padding-left 


```
    <ion-chip>
        <ion-icon padding-left name="cart"></ion-icon>
        <ion-label>Default</ion-label>
    </ion-chip>
```

worked it around this way

```
.mainStyles {
    ion-chip{
        ion-icon{
            padding-top: 1px;
            padding-left: 8px;
        }
    }
}
```

**Comment by brandyscarney** [comment]
@cesar-oyarzun-m I'm not seeing any issues with the icon alignment. Is there a repository where I can reproduce this?

<img width="363" alt="screen shot 2016-10-25 at 5 18 53 pm" src="https://cloud.githubusercontent.com/assets/6577830/19704788/2fabe18e-9ad7-11e6-84c2-006092df337f.png">

**Comment by nakulgulati** [comment]
@brandyscarney After further inspection the chips work fine alone, but when used inside `<ion-item>` they have UI issues. Here is a repo demonstrating the issue.

https://github.com/nakulgulati/ionic-chips

Also here is a screenshot
<img width="1232" alt="screen shot 2016-10-26 at 03 17 23" src="https://cloud.githubusercontent.com/assets/4583272/19705584/e611dc3c-9b2a-11e6-8200-2def05660c3c.png">

**Comment by brandyscarney** [comment]
Ah okay thank you!

**Comment by miraj92** [comment]
Can anyone tell when chips will be available for use in prod.?
