### ISSUE TITLE
alpha57 Build Error - web-animations.min

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic#5388]
I get this error when building with alpha57.  I removed the framework before doing npm install.  Is there something else I need to do?

Module not found: Error: Cannot resolve module 'ionic-framework/js/web-animations.min' in /Users/richardshergold/Documents/Ionic Projects/PortalToday
resolve module ionic-framework/js/web-animations.min in /Users/richardshergold/Documents/Ionic Projects/PortalToday
  looking for modules in /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules
    resolve 'file' or 'directory' js/web-animations.min in /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework
      resolve file
        /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min doesn't exist
        /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min.js doesn't exist
      resolve directory
        /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min doesn't exist (directory default file)
        /Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min/package.json doesn't exist (directory description file)
[/Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min]
[/Users/richardshergold/Documents/Ionic Projects/PortalToday/node_modules/ionic-framework/js/web-animations.min.js]
 @ multi main (CLI v2.0.0-beta.17)

**Comment by richardshergold** [comment]
Sorted it - had to remove the two web-animations entries from the webpackconfig.js

**Comment by tlancina** [comment]
Hey thanks, just updated the starters and added a breaking change notice to the changelog.
