### ISSUE TITLE
menus state

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#5390]
Is there a way to check if a menu is opened or closed ? In the documentation i can see all the functions like toogle or swipeEnable but how can i check if the menu is actually opened or not.

I am on Ionic 2 

Thanks

**Comment by brandyscarney** [comment]
Yes you can get this by using the following:

```
import {MenuController} from 'ionic/ionic';
```

```
constructor(menu: MenuController) {
  this.menu = menu;
  let menuOpen = this.menu.get().isOpen;
  console.log( menuOpen );
}
```

We need to simplify this so you can check if the menu is open without calling `get()` so I am going to leave this issue open as an enhancement.

Created a new issue for updating the docs: https://github.com/driftyco/ionic-site/issues/413
