### ISSUE TITLE
[ionic2 bugs] Alert or ActionSheet will not fire every time in many tags in ios9. ( exclude <button>)  

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic#5393]
https://www.youtube.com/watch?v=KPLgMzro7Y8&feature=youtu.be
When i bind an click event about alert or actionSheet on a <ion-card>. It will have some strange things happen:  
First time i click, good result. the click event will be fired and alert/actionSheet will happen. but after fired it first time,it will have a big interval time to fire the click event again.(about 1.5-2 second).
But if you bind an click event about alert on <button>. Every thing works fine and no problem. Every time the click is work and alert/acti
onSheet will work.
It seems that if you call an alert or actionSheet on a <ion-card>'s click event. It will block the click event on the same object about some times.
Let's see what happen: 
https://www.youtube.com/watch?v=KPLgMzro7Y8&feature=youtu.be
Android 4.4.4 no this problem and everything works fine. But i try it on my iphone6 (IOS9) it will happen this issue. 
I have try many tags have this problem(  include bind it in svg element );

Demo case:

    <ion-navbar *navbar>
      <ion-title>Tab 1</ion-title>
    </ion-navbar>

    <ion-content padding class="page1">

    <button secondary (click)="doClickButton()" >button click</button>
      <ion-card (click)="doClickCard()" >
        <ion-card-header class="LineTitle" >
          Card click
        </ion-card-header>
      </ion-card>

    </ion-content>

	    doClickButton() {
		let alert = Alert.create({
			title: 'Clicked On button',
			buttons: ['OK']
		});
		this.nav.present(alert);	
	}   	

	doClickCard() {
		console.log("a");
		let alert = Alert.create({
			title: 'Clicked On card',
			buttons: ['OK']
		});
		this.nav.present(alert);	
	}

**Comment by adamdbradley** [comment]
`ion-card` is not a button, so to remove the 350ms delay on iOS. However, for this reason we created a `tappable` attribute, so your html would look like:

```
<ion-card (click)="doClickCard()" tappable>
```

The good news is this should no longer be an issue with iOS 9.3, so as older versions phase out this will be a thing of the past. Please give that a shot and let me know if you're still having issues. Thanks

**Comment by kitkimwong** [comment]
@adamdbradley 
Thank you and sorry for the late reply.
I have try add  `tappable` tag but it seem not related to the 300ms delays.
When i use add bind click to `console.log()` something, it works and immediate console the string.
But  when you bind `Actionsheet` or `alert` in the click. 
It will have not fire the event often!!!
And you can just have a real devices test in IOS9
Thanks

**Comment by kitkimwong** [comment]
@adamdbradley 
Sorry for the late reply and thanks you !  The problems fixed.
