### ISSUE TITLE
docs: Ionic v2 docs for plugins are unavailable

### ISSUE THREAD

**Issue by matheuscas** [driftyco/ionic#5395]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I make a search for "Ionic Native" and click on it, I receive this:
Cannot GET /docs/v2/platform/applinks/

It seems to be like this in all links about Ionic Native.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Thanks for the issue, Ionic Native is still under development and the docs will go live soon :)

**Comment by matheuscas** [comment]
Oh, sorry about that. I thought it would have some docs for the announcement for the new beta.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#419
