### ISSUE TITLE
bug: TypeScript errors with noImplicitAny:true tsconfig

### ISSUE THREAD

**Issue by lehresman** [driftyco/ionic#5396]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I want to be pedantic about typing in my Ionic app, so I added "noImplicitAny":true to my tsconfig.json.  Works great, except there seems to be some typing issues with the Swiper widget.  I get this when trying to compile my TypeScript:

```
ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:8:2 
'update', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:9:2 
'slideNext', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:10:2 
'slidePrev', which lacks return-type annotation, implicitly has an 'any' return type.
```

When I edit `swiper-widget.d.ts` and add `:any` to all the function declarations, it works fine.  But I suspect that's not the actual solution and figured I should report it.</span>

I'm running `2.0.0-beta.0`.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#742

**Comment by tlancina** [comment]
Thanks for the issue! We actually have quite a few untyped files still, and resolving the ones with `noImplicitAny` will be the next step in fully adding types to the framework.

**Comment by manucorporat** [comment]
@tlancina @jthoms1 should we close this?

**Comment by tlancina** [comment]
According to @danbucholtz this has been resolved, closing.
