### ISSUE TITLE
bug: TypeScript files (.ts ext) not in compile context

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5397]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I create a new .ts file, for example, "Todo.ts" that exports a class called Todo, VSCode and Atom are giving me errors about how "Todo.ts" is not included in the TypeScript compilation context.  The tsconfig.json file glob is not set-up correctly.</span>

<span is-issue-template></span>

**Comment by danbucholtz** [comment]
in app/Todo.ts
`export class Todo{
}`

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#741
