### ISSUE TITLE
docs: Various issues related to V2 docs

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#5398]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I created a Gist of my issues:

https://gist.github.com/cfjedimaster/ab78eb3e0adbef982098</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#418
