### ISSUE TITLE
Input fields within list items not clickable

### ISSUE THREAD

**Issue by IcyT** [driftyco/ionic#5402]
I use Ionic2 beta.
The documentation shows ion-label and ion-input within an ion-item of an ion-list.
When I do the same, the input fields are not clickable. I analyzed the code a bit and found, that there is a CSS rule for ion-item that prevents the click: `pointer-events: none;`
If I disable the rule, the click works.
Am I doing something wrong or can you reproduce the issue?

**Comment by adamdbradley** [comment]
What does your markup look like? What browsers/platforms are you testing on?

**Comment by IcyT** [comment]
Do you mean the markup I wrote or the generated markup? The markup I wrote is pretty close to the documenation.
I tested it on Windows 7 with the current Chrome version.

**Comment by brandyscarney** [comment]
@IcyT Can you please paste the markup that you got from the documentation? There are a few places where labels/inputs are documented and we'd like to make sure that the documentation you copied is up-to-date. Thanks!

**Comment by IcyT** [comment]
I tried to reproduce it in a plain new project, but here it works. So it looks like it is a side effekt coming from my structure of from the upgrade. I am trying to figure out the root cause.

**Comment by IcyT** [comment]
I had a deeper investigation and compared the default project with my project and updated some files and dependencies. Now, it also works with my project, so it looks like it was a side effect from upgrading or from older dependencies.
I will close the issue. Thanks for your support and sorry for the inconvenience. Looking forward for the next betas with pull to refresh and infinite scrolling!
