### ISSUE TITLE
docs: Where are  material design in ionic ? share link

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic#5404]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi ! how long time for official material design for ionic ?
if you already hosted please share link.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
On the components page, above the phone preview, you can view the Android preview too:
http://ionicframework.com/docs/v2/components/

![image](https://cloud.githubusercontent.com/assets/452425/12979450/e79147a4-d09c-11e5-845f-c1e1e9546940.png)

**Comment by DILEEP-YADAV** [comment]
@adamdbradley  ok!  really Awesome work, actually I am switching onsen UI to ionic v2 in production. 
thanks
