### ISSUE TITLE
feat: Add Android over-scrolling ink

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#5405]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I don't really kno how it called but it happens every time you pull too(scroll too much) much the page/scroller.
It would be nice to have it in ionic 2 on Android, it's really cool and I am sure it will help to the native feeling.

Images to describe the feature:
http://i.imgur.com/pM8W6MQ.png
http://i.imgur.com/C3HCIKr.png</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Sorry but this is probably not a feature we'll be adding in the near future. As we get further along we can come back and reevaluate adding it. Thanks
