### ISSUE TITLE
bug: Applying platform specific changes

### ISSUE THREAD

**Issue by RIanDeLaCruz** [driftyco/ionic#5411]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I've been trying to apply platform specific changes to the tabbar. I wanted to make it so that the icons do not appear on Android but does appear on iOS. 

Applying changes in the config, by saying
`platforms:{
	android:{
		tabbarIcons:'hide'
	} 
} `
didn't yield anything. Using`[attr.tabIcon] ="isMD?  null:'camera'"'`on the element itself did not work.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
I just tried using the following config:

```
@App({
  templateUrl: 'build/app.html',
  config: {
    platforms: { 
      android: {
        tabbarIcons: 'hide'
      }
    }
  }
```

and I see it working in the conference app. What version of Ionic are you using? And does your code look the same as above?

**Comment by RIanDeLaCruz** [comment]
Here is my config @brandyscarney 
`@App({
    template: '<ion-nav [root]="rootPage"></ion-nav>',
    config: {
        platforms: {
            android: {
                tabbarIcons: 'hide',
            }
        }
    } // http://ionicframework.com/docs/v2/api/config/Config/
})`
(Can't seem to format the markdown. Sorry about that)

**Comment by RIanDeLaCruz** [comment]
I've tried just doing `ionic serve` on the conference app and I am seeing a blank screen.

Could there be an error in my installation of the CLI?

**Comment by RIanDeLaCruz** [comment]
I've tried running the conference app. But nothing appears. Could it be my CLI installation that has a problem?

**Comment by mhartington** [comment]
Looks like you have an older version of the CLI, 1.7.14. 

If you want to do anything with V2, you need the beta CLI as stated in the V2 getting started guide.

http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by RIanDeLaCruz** [comment]
I'll try re-installing. I remember using the beta, though

**Comment by RIanDeLaCruz** [comment]
What version should I be seeing?

**Comment by mhartington** [comment]
beta 17

**Comment by RIanDeLaCruz** [comment]
Ok. Thanks.

But how was it possible that I was able to generate an Ionic 2 app from  CLI 1.7.14 ?

**Comment by brandyscarney** [comment]
You may have accidentally ran `npm install -g ionic` and switched to the stable release of the CLI after creating the project. It's a bit confusing right now with the CLI being in beta and the framework now in beta, but we have some documentation on the differences here: http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by RIanDeLaCruz** [comment]
Thanks @brandyscarney and @mhartington. 

Will close the issue now.
