### ISSUE TITLE
bug: Folder structure issue

### ISSUE THREAD

**Issue by RIanDeLaCruz** [driftyco/ionic#5412]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Based on the documentation, the app folder should be inside the www folder. Instead, when I create a project, the app and www folders are siblings in the root folder.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Sorry, we must have our docs outdated. Which page are you seeing that on? cc @mhartington

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#417
