### ISSUE TITLE
bug: menu close not works for about 1 second after menu open.

### ISSUE THREAD

**Issue by jechol** [driftyco/ionic#5413]
#### Reproduce
(Only happens emulator or real device for iOS)

1) Launch tutorial pp
```shell
$ ionic start MyIonic2Project tutorial --v2
$ ionic emulate ios
```
2) Click menu button to open
3) Click menu button immediately to close ==> Not works.
4) Wait 1 second.
5) Click menu button to close ==> Works.

**Comment by adamdbradley** [comment]
This is by design to prevent ghostclicks and doubleclick mistakes that happens on iOS. This way is the lesser of two evils.

**Comment by jechol** [comment]
Alright... But it doesn't feel good... 1 second seems too long.

**Comment by jechol** [comment]
I've read http://blog.ionic.io/hybrid-apps-and-the-curse-of-the-300ms-delay/.
It seems very difficult problem than I assumed.
