### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5415]

**Comment by jboothe** [comment]
Adam, how's the progress on this? I'm upgrading a public app from Ionic 1 to 2 and don't want to eliminate the feature. Thanks for all the fantastic work!

**Comment by ryanlin1986** [comment]
We are waiting for this feature as well, since it's essential feature we can not live without it

**Comment by sclausen** [comment]
+1

**Comment by abierbaum** [comment]
:+1:

**Comment by MrBokeh** [comment]
Would this help?
http://stackoverflow.com/questions/34496508/implement-infinite-scroller-in-angular2

**Comment by sphaso** [comment]
+1

**Comment by adamdbradley** [comment]
It's in master and will go out in the beta2 release :)

**Comment by jboothe** [comment]
Great news! Thanks, Adam. I'll grab latest. Is beta2 due to go out soon?

**Comment by brandyscarney** [comment]
I've renamed `ion-infinite` to `ion-infinite-scroll` and `ion-infinite-content` to `ion-infinite-scroll-content`. Also `endLoading()` has been renamed to `complete()`. Please update these if you are using the 2.0 branch. We will release beta.2 when all issues in the milestone are complete and the framework has been thoroughly tested :smile: You can always check out [our milestones](https://github.com/driftyco/ionic/milestones/) to see which issues are still open: https://github.com/driftyco/ionic/milestones/2.0.0-beta.2

**Comment by sclausen** [comment]
@brandyscarney very nice! Is there somewhere a guide, how to use the 2.0 branch in my project?

**Comment by brandyscarney** [comment]
@sclausen These steps should work, but let me know if they don't: https://github.com/driftyco/ionic/blob/2.0/scripts/README.md#developing-against-ionic-locally

:smile:

**Comment by sclausen** [comment]
@brandyscarney many thanks!
Unfortunately, building won't work after linking.
I got a massive error output.
Here is the [gist](https://gist.github.com/sclausen/784112affe3ac409f8a0) for stderr

And at the end in stdout
```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.7.0
```

**Comment by brandyscarney** [comment]
@sclausen Quite a bit has changed in the framework. If you pull down the conference app: https://github.com/driftyco/ionic-conference-app

- Update the CLI to beta.19: `npm install -g ionic@beta`
- Run the steps to link it to `ionic-framework` (or you can go ahead and start using `ionic-angular` see: https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058)
- Change the imports from:

  ```js 
  import {Page} from 'ionic-framework/ionic'; 
  ```

  to

  ```js 
  import {Page} from 'ionic-framework'; 
  ```

  or `ionic-angular` if you linked it to that

It should work to run `ionic serve`. We'll be releasing beta.2 and updating the changelog with some steps to upgrade.

**Comment by jboothe** [comment]
Get the following error when running `ionic serve`. I have latest ionic-conference-app and `ionic@2.0.0-beta.19` is installed globally.

`
ERROR: Could not find your ionic.project file! Please run this command in the root of your ionic project.
`

 However, if I start a new tutorial project:
 `ionic start MyIonic2Project tutorial --v2 --ts`, 
then app runs fine with 
`ionic serve`. 

What am I missing?

**Comment by sclausen** [comment]
@brandyscarney you meant this?
``` typescript
import {Page} from 'ionic-angular';
```
beside this, your guide works like a charm, many thanks!!!
