### ISSUE TITLE
Redesign select alert

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5424]
- Have iOS select options slide in from the bottom
- Same alert api, just different css and animation

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!
