### ISSUE TITLE
Loading Service

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5426]
- [x] Add component
- [x] Add styles for each mode
- [x] Update spinner to use `circles` by default for windows
- [x] Karma tests
- [x] API docs
- [x] API demo
- [x] Create issue for component docs & demo https://github.com/driftyco/ionic-site/issues/531

**Comment by imsingh** [comment]
@adamdbradley are you referring to $ionicLoading for v2. I was searching for either Loading Service or Spinner for v2. But they are not available yet right?

**Comment by jgw96** [comment]
If this is referencing a loading spinner for http requests its pretty easy for a dev to implement manually. Im currently doing that in my GitNinja app built with ionic 2.

**Comment by privetr** [comment]
This would be a good new feature !

**Comment by susanlinsfu** [comment]
This would be great! Simple feature, but from a UX perspective very useful!

**Comment by EuAndreh** [comment]
There's a good tutorial on how to create a custom one:

http://www.joshmorony.com/how-to-create-a-custom-loading-component-in-ionic-2/

I believe it solves most needs.

**Comment by thiphariel** [comment]
Hi. The current ionic-native SpinnerDialog will not be used for this service right ? It looks kinda wrong on iOS, hope it's jsut a temporary thing :)

**Comment by brandyscarney** [comment]
@thiphariel This loading service will not use the SpinnerDialog plugin. It's custom UI that uses the Ionic spinners. You will be able to use any of our spinners or custom content. Here's a sneak peek of the UI for the default spinners:

![loading-modes](https://cloud.githubusercontent.com/assets/6577830/14263696/fead12c6-fa89-11e5-8855-634228a113a8.png)

**Comment by thiphariel** [comment]
@brandyscarney yeaap ! Thanks for the screens, looks awesome. Btw, it's for which beta ?

**Comment by brandyscarney** [comment]
@thiphariel We're planning on releasing it with beta.4! :smile:

**Comment by thiphariel** [comment]
@brandyscarney Yihaaa :D nice nice nice ! Hope it will coming soon ! Thanks

**Comment by hlehmann** [comment]
Very cool ! Any estimation of when this beta will be release ?

**Comment by brandyscarney** [comment]
@hlehmann @thiphariel Check out the [milestones](https://github.com/driftyco/ionic/milestones) to see where we're at with each beta. :smile: We have a few issues open on [beta.4](https://github.com/driftyco/ionic/milestones/2.0.0-beta.4) but at the very least we want to complete #5418, #6026 and this issue before releasing beta.4.

**Comment by privetr** [comment]
Woo this looks great :)

**Comment by EuAndreh** [comment]
Awesome @brandyscarney!

Even better that beta.4 will already include it =]

**Comment by brandyscarney** [comment]
This is complete! It will be in the beta.4 release. Thanks everyone for the feedback! We'll have the API docs for this published soon.

**Comment by thiphariel** [comment]
\o/ hooray !
Le jeu. 7 avr. 2016 à 17:18, Brandy Carney <notifications@github.com> a
écrit :
