### ISSUE TITLE
style: ion-select has styling problems

### ISSUE THREAD

**Issue by schirrmacher** [driftyco/ionic#5427]
The ion-select directive has some styling issues. I'm using Chrome Version 48.0.2564.97 (64-bit) on Mac and 2.0.0-beta.17:
![screen shot 2016-02-11 at 19 09 46](https://cloud.githubusercontent.com/assets/6545822/12985562/9cc1a758-d0f3-11e5-8228-0723f66f1bdd.png)

My code looks like this:

```
<ion-content>

    <ion-card>

        <ion-item>
            <ion-label>Music</ion-label>
            <ion-select [(ngModel)]="music">
                <ion-option>Alice in Chains</ion-option>
                <ion-option>Green Day</ion-option>
                <ion-option>Nirvana</ion-option>
                <ion-option>Pearl Jam</ion-option>
                <ion-option>Smashing Pumpkins</ion-option>
                <ion-option>Soundgarden</ion-option>
                <ion-option (select)="stpSelect()">Stone Temple Pilots</ion-option>
            </ion-select>
        </ion-item>

    </ion-card>

</ion-content>
```

**Comment by adamdbradley** [comment]
Do you mean 2.0.0-beta.0? Also, have to stopped and restarted your sass build to ensure you have the latest css being used?

**Comment by schirrmacher** [comment]
```
$ ionic --v
2.0.0-beta.17
```
I use ionic serve:

```
$ ionic serve

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/app.+(ios|md).scss
...
```

**Comment by brandyscarney** [comment]
Could you run `ionic info` from inside the project folder please. That is the ionic CLI version you are getting. :smile:

**Comment by brandyscarney** [comment]
Also, do you have a theme folder or are you Sass files at the top level of the project?

**Comment by schirrmacher** [comment]
Oh sorry 😬

```
$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

Yes, my Sass files are at the top level of my project.

**Comment by brandyscarney** [comment]
Is there any reason you aren't updating to the latest version? We released beta.0 yesterday! :smile: 

So the refactor for the items to work like your markup above didn't exist until alpha.53, could you update to the latest and refer to the changelog for anything you need to update? https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md

**Comment by schirrmacher** [comment]
Ok the update fixes my issue 🙂👍

**Comment by brandyscarney** [comment]
Ok thanks! Going to close this.

**Comment by phavre** [comment]
Is there some way to the ion-select component to take 100% of the width ?
Because in a multi select list, I needed to show some of the selected entries but with the standard width I've got only the first entry. So I used a stacked label, but the select width didn't widened.
![image](https://cloud.githubusercontent.com/assets/16475287/13120504/5d6bce98-d5ae-11e5-9a41-a151aeeccc23.png)

**Comment by luispestanajr** [comment]
Hello @phavre.

I did it with custom css class.

Here is the code:

.myCustomSelect{
	max-width: 100% !important;
}

I hope it can help you.
