### ISSUE TITLE
bug: ion-toggle with external data source not working

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5428]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have created https://github.com/alexbainbridge/TestToggle from the test starter

Page 1 has an ion-toggle, including an external data source. When you run it, its like (in v1) that digest is stuck in a loop - so the toggle goes on, off, on.....   when you click the toggle, it works...

Only seems to happen if the external data source is set to true. If set to false, works on initial load as unset.

What am I doing wrong! (or is this a bug?)</span>

<span is-issue-template></span>

**Comment by colinjlacy** [comment]
Submitting a PR from a fork to demo how I got it working.  Let's talk more in the comments there.

**Comment by alexbainbridge** [comment]
OK I have merged that in, and it works..... thank you @colinjlacy 

Turns out the entire problem was  this.DataItem = [];  in the constructor

I had this.DataItem = [];  present in the constructor to stop the template errors on loading, and did NOT have <div *ngIf="DataItem">  wrapping the fields, in the HTML template, which achieves the same error prevention, but without creating the issues I saw. 

Will leave this open, @adamdbradley can close when he wishes, my suggestion would be to publish a worked example for this, as perhaps others will hit this gotcha of data arriving subsequent to template showing and try to fix incorrectly

Thanks again Colin!

**Comment by alexbainbridge** [comment]
Additional comment - I wonder if there is **potentially** an Ionic level fix here, meaning we don't have to do the adjustment and make less elegant templates

I would prefer to not have to wrap form fields (in the template) in ngIf unless I I have to....

**Comment by adamdbradley** [comment]
Glad you were able to get it fixed, but I also wonder if part of the problem was from this issue: https://github.com/driftyco/ionic/issues/5425 (which isn't in a release yet)
