### ISSUE TITLE
bug: Pushing a page on start up makes screen go blank

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#5431]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I am trying to push a page to be loaded up on start up .. But when that page gets pushed it makes the screen go blank white.

The only way I got it to work properly is by adding a 500ms timeout.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Can you instead set the new page as the root? I wouldn't recommend changing the navigation before the app has even started. The root property is probably best for that.
