### ISSUE TITLE
bug: when `button` and `ion-input` exists in same page, button css broken.

### ISSUE THREAD

**Issue by jechol** [driftyco/ionic#5434]
Put `button` and `ion-input` in same page.

button becomes like following

![image](https://cloud.githubusercontent.com/assets/795125/12998944/cd365ce6-d18c-11e5-892d-c5031b62feab.png)

**Comment by RAMDdFLEET** [comment]
give a codepen or a small code snippet. I ll be able to fix that.

**Comment by jechol** [comment]
I was using `ionic-framework@alpha.51`.

I didn't know that `ionic` and `ionic-framework` is different thing.

After upgrade to `alpha.57` (which the current ionic start generate), bug has gone.

**Comment by jechol** [comment]
Confirmed not reproducible at `beta.0` also. closed.
