### ISSUE TITLE
bug: slide box doesn't slide on iPad

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#5435]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>the slide box doesn't slide completely on iPad

Only slides half way</span>

<span is-issue-template></span>

**Comment by ihadeed** [comment]
**Update**: I just tried the slide box on an iPad simulator and it worked fine. The issue occurs only when testing on a real iPad device (I have iPad Air)

**Comment by AaronPlave** [comment]
Same issue with slide box only sliding halfway on iPhone with iOS 8 webview. Works on simulator but not on device. Only 1 page navigation bullet is shown on device. Curiously, when you change the device orientation once, the slide box functions normally and shows the correct number page bullets.

**Comment by ihadeed** [comment]
Issue seems to be fixed now..
