### ISSUE TITLE
Update to angular 1.5

### ISSUE THREAD

**Issue by ram-you** [driftyco/ionic#5436]
Hi, please update ionic v1 to use **angular 1.5**.
Thank you.

**Comment by jrencz** [comment]
:+1:

**Comment by ferrante** [comment]
+1

**Comment by jaronson** [comment]
+1

**Comment by cyprusglobe** [comment]
+1

**Comment by petrvojta** [comment]
+1

**Comment by QcRafal** [comment]
+1

**Comment by danielptn** [comment]
whats change?

**Comment by ram-you** [comment]
To name only one : **Component-Based Directives**

https://medium.com/google-developer-experts/angular-new-features-in-angularjs-1-5-24f9b503af15#.egyzwkczl

**Comment by MarcBT** [comment]
Yep +1.

**Comment by liujinxing** [comment]
+1

**Comment by jadsalhani** [comment]
+1

**Comment by moisesnarvaez** [comment]
+1

**Comment by rastographics** [comment]
+1

**Comment by danijelmaric** [comment]
+1

**Comment by aprct** [comment]
+1

**Comment by denyo** [comment]
Why not just update angular and angular-resource to 1.5 by yourself? Everything is still working in my app in addition to new features like $cancelRequest().

**Comment by jgw96** [comment]
Hello @ram-you ! Thanks for the suggestion, we are definitely listening! Since this isn't really an issue i will be closing this issue, but feel free to continue on the conversation please! Id love to hear the main reasons why people would like to be able to use AngularJS 1.5! Also, have you gotten a chance to play with Ionic 2 yet?

**Comment by ram-you** [comment]
@jgw96 , thank you very much. Using the Angular 1.5 will enable us to share components between our main application (angular-material) and our  Ionic 1 app. For now, I have not had the chance to try the ionic v2 for lack of time. I hope to do very soon.

**Comment by paresthesia69** [comment]
Some of us are considering an upgrade of existing ng1/Ionic1 apps to ng2/Ionic2 and would appreciate 1.5 update inside Ionic1 to help us bridge the gap. Based on the Angular [upgrade doc](https://angular.io/docs/ts/latest/guide/upgrade.html), the new component based directives will make such an upgrade much easier, they make it clear that the Component based directive will make the upgrade pathway easier. I believe that is why some of us are asking for this improvement to Ionic1.

**Comment by aprct** [comment]
Additionally, for those of us who would like to stick with the Angular 1.* way of doing things an upgrade to 1.5 would be a big step forward.

**Comment by jgw96** [comment]
@paresthesia69 The migration to angular 2/ionic 2 is one of the biggest advantages of 1.5! @aprct definitely! But i urge you to give angular 2/ionic 2 a try, it may seem weird at first, but you will end up loving it fast! Its just es6/es7 javascript or Typescript now! Alot of the angular specific stuff like $scope is gone now

**Comment by paresthesia69** [comment]
@jgw96 Yeah, that is why I am hoping that Ionic 1 updates their bower.json/support for Angular 1.5, to make the potential transition easier. We are doing complete ES6 through babel in our current projects where I am at, and we love it. We are not sure about TypeScript though (yet?), maybe because most of my team still prefers something closer to vanilla. Either way, an update for Ionic 1 to support 1.5 would be very helpful with the transition to 2.

**Comment by aprct** [comment]
@jgw96 Thanks for the quick response. My team has tried both Angular 2 and React/React-Native, and we have a lot of experience with Angular 1. At the moment the decision is between the familiarity of Angular 1 and (in our opinion) the architectural improvements of React. We'd like to benefit from the infrastructure provided by Ionic, and decided that (for various reasons) we'd hold off on Angular 2 for now.

That said, I understand if business on your side is prioritizing Angular 2/Ionic 2 for development and lack the resources to focus on a migration path from 1.4 to 1.5 to 2.

**Comment by jopima** [comment]
Just started my ionic and angularjs marathon. Heard a lot about how angularjs 2 and ionic 2 are totally different from the previous versions and less documentation coverage. i had to keep off for now. I have heard from this forum that transition to version 2.0 of both ionic and angular is easier if angular 1.5 is included. i add my voice to the many. please consider supporting angular 1.5. i have an app with bootstrap and angular1.5. now wanted to use the same code with ionic mobile version. i don't know how it will go. i will try it anyway.

**Comment by nonmadden** [comment]
:+1:

**Comment by aprct** [comment]
It seems that the community views this issue as a priority for numerous reasons. @jgw96 What would it take for Drifty to let Ionic 1 go out with a bang? :)

**Comment by danicomas** [comment]
+1. This is a required spec.

**Comment by astik** [comment]
+1
I'd like to share my components between the web app and the mobile app =)

**Comment by danbucholtz** [comment]
All, this will be in the next release of Ionic 1.x in the coming weeks.

Thanks,
Dan

**Comment by vascofernandes** [comment]
please do.

**Comment by astik** [comment]
For those interested in this post next step, read https://forum.ionicframework.com/t/ionic-1-3-release-candidate-w-angular-1-5-update/49133/11 =)

**Comment by danbucholtz** [comment]
Thanks @astik!

Go ahead and upgrade and let us know how it goes.  No reported issues so far.

Thanks,
Dan

**Comment by astik** [comment]
So far so good, migration went well and mutating my directive to component was done without ay problem. Thank to ionic team !

**Comment by chaitujil** [comment]
+1
