### ISSUE TITLE
bug: Physical Back button exits app instead of going back in the nav

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#5438]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Steps to reproduce issue:
1) ionic start myApp sidemenu --v2 --ts
2) ionic run android --device --livereload
3) Tap Menu Icon
4) Select "Lists"
5) Tap a list item to push a new ListPage onto the nav stack
6) Tap your device's physical Back button

Results:
The app exits and you are brought to the Android launch screen

Expected Results:
The ListPage would be popped off of the nav stack just like if you had tapped the software back button at the top left of the app.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Thank you for the issue, we have this on our roadmap to finish around beta.4. There is an issue for it here: https://github.com/driftyco/ionic/issues/5419

Please take a look at our roadmap for other features and fixes:
https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit?usp=sharing
