### ISSUE TITLE
in android push page does not appear   , opacity: 0.001   

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic#5440]
hi ionic team,

in android
some time when push page the page does not appear
from chrome inspect i  discovered that page opacity: 0.001   
also if i remove that opacity , the page titlebar appear under the previous page titlebar

i use ionic-freamwork@2.0.0-beta.0

**Comment by adamdbradley** [comment]
Would you be able to provide more information? What device? On cordova or the browser? Emulator or physical device? Any javascript errors?

**Comment by mashaly100200** [comment]
i use physical device , the device is samsung mega 5.8
this problem was in ionic2 alpha but it was putting the titlebar under the previous page titlebar , and the opacity was 1 and i edit transition-md.js file change  
OFF_BOTTOM = '40px'; 
to  
OFF_BOTTOM = '0px'; 

now with ionic 2 beta  it like alpha  putting the titlebar under the previous page titlebar  but the opacity: 0.001
when i change the opacity by using chrome://inspect   i see  the page and it's titlebar still under the previous page titlebar 

most of the time it happened when quickly push new page after application is started

**Comment by adamdbradley** [comment]
Are you using crosswalk with that build?

**Comment by adamdbradley** [comment]
Looks related to #5484

**Comment by mashaly100200** [comment]
many thanks adamdbradley
:+1:  :100:  :+1:
