### ISSUE TITLE
bug: Google maps stop responding after dragging/zooming

### ISSUE THREAD

**Issue by cankei** [driftyco/ionic#5442]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi Ionic team,

I used ngMap to add Google maps to my ionic app. While the multi info-window example from ngMap works fine on my iPhone safari (http://ngmap.github.io/#/!infowindow_ng_click.html), I found the markers & info-windows with map in ionic will stop responding after a few drags and zoom on iOS Safari. 

You can see the problem by opening this plunker preview link on any iPhone or iOS simulator and try clicking the marker and drag/zoom the map a few times. Then the markers will stop responding. I will have to refresh the page.
http://embed.plnkr.co/bFyA13zPeJTM3UZPBXOP/

I'd like to see if anyone has the same problem or a fix for it? This bug appears on iOS browsers only.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks for submitting an issue with us and for providing the plunkr! We just need a little more info from you so that we can better debug this issue. Would you mind running `ionic info` and posting the output here? A=

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by elmoromourad** [comment]
hello,
i've the same problem, after dragging 4 or 5 times (or zooming) maps stop working
any help please ?

**Comment by cankei** [comment]
Hi jgw96,

Sorry I was on holiday for a few weeks.

I tried to look at the issue today and the plnker link I provided previously seems to work fine now. I'm not sure if the latest google map js has fixed the issue.

I tried it on iOS simulator and my iPad device.

I'm happy to close the issue now, unless someone else still has problem with it.

Cheers,
Qi

**Comment by elmoromourad** [comment]
Hello !
I have the same problem last week (on android), I think also that the last GMaps update has fixed it. 
Thank you Google :+1:

**Comment by jgw96** [comment]
@cankei @elmoromourad No problem! Im glad this was resolved for you all, and thanks for using ionic!
