### ISSUE TITLE
bug: ion-radio in an ion-list prevents ion-option-butto

### ISSUE THREAD

**Issue by danielptn** [driftyco/ionic#5443]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>https://github.com/driftyco/ionic/issues/2714

But my issue is with radio-list.. I need to make a radio-list with ion-option-button, but when you try to combine this components, the ion-option-button don't work in the radio area..</span>

<span is-issue-template></span>

Its simples to reproduce.. Try to combine ion-radio with ion-option-button..

**Comment by danielptn** [comment]
@mlynch can you help?

**Comment by danielptn** [comment]
someone? bump!!

**Comment by danbucholtz** [comment]
Hi @danielptn and others,

The Ionic team is looking at this issue and we are trying to understand the use cases for swipeable toggles/checkboxes/etc. Can you elaborate on that please so we can better understand it?

As it stands now, I don't think we'll support this functionality in Ionic 1.x

Please let us know your thoughts on the topic and if viable alternatives exist. Please at mention @jgw96 in your response so he can stay on top of it.

Thanks,
Dan
