### ISSUE TITLE
How to test ionic v2 with android look and feel using chrome ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic#5447]
ionic serve command by default is iOS look and feel. How do that android material look and feel using chrome. what flag we use for the same?

**Comment by jgw96** [comment]
To emulate an android device in Google Chrome you can use the device emulation tool in the dev tools. Simply open the dev tools (hamburger menu in top left > more tools > Developer tools) and click on the phone icon in the top left of the Developer tools. To emulate an android device just pick whichever one you would like to emulate from the device options. You can also emulate ios device using this same method.

**Comment by emps** [comment]
in Chrome DEV MODE just choose Android phone and refresh the page

**Comment by danielgolub** [comment]
You can also add the query-string /?ionicplatform=android to get the Android version.

**Comment by DILEEP-YADAV** [comment]
ok! Thanks to all
