### ISSUE TITLE
perf: I want to upload my project on ionic creator.

### ISSUE THREAD

**Issue by DaGeTian** [driftyco/ionic#5450]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It's not bug. I want to upload my project(www) on ionic creator and continue develop. Because I changed some forms with my code. But i can't use it on ionic creator.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-creator-issues#336

**Comment by timothycurchod** [comment]
The above link is not valid.  Where has this issue been moved to?
