### ISSUE TITLE
Security Alert from Google Play Developer Console 

### ISSUE THREAD

**Issue by sydneyhenrard** [driftyco/ionic#5451]
I get a security alert in the Google Play Developer Console:
Please migrate your app(s) to Apache Cordova v.4.1.1 or higher as soon as possible and increment the version number of the upgraded APK.

Where do I check which version of Cordova my application use?

```
vagrant@ionic-android:/project$ cordova platform
Installed platforms: android 4.1.1
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu, webos
```

To fix it, I guess I just have to upgrade cordova, and release a new apk, right?
```
vagrant@ionic-android:/project$ cordova -v
5.4.1
```

```
vagrant@ionic-android:/project$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.3 LTS
Node Version: v4.3.0
```

Thanks

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#770
