### ISSUE TITLE
issue about add popover on costom popover

### ISSUE THREAD

**Issue by MaxBalance** [driftyco/ionic#5454]
when I add a popover on a costom popover ,it will not work when I click the buttons.
then I use the $timeout , it works will.

**Comment by maxx0r** [comment]
Could you post the relevant part of your code? How do you hook up the event which triggers the popover?

**Comment by jgw96** [comment]
Thanks for posting an issue with us! Since it seems to have been a while since there was any activity on this issue i will be closing it, but if your still experiencing this issue i urge you to please feel free to reopen this, we would love to help! Thanks again!
