### ISSUE TITLE
ionic slidebox slide too fast and show incorrect data

### ISSUE THREAD

**Issue by FarhanJohari** [driftyco/ionic#5457]
hi there, i have an issue that if user slide to fast it show the incorrect data and this issue only happens in iOS device.. my android and browser works fine

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! We just need a little more info from you so that we can better help you with this issue. Would you mind positing a code sample for us, or a codepen? Also if you could run `ionic info` and post the content here that would be great!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
