### ISSUE TITLE
ion-input with ion-label; keyboard closes

### ISSUE THREAD

**Issue by Tobiaswk** [driftyco/ionic#5458]
When you have an **ion-input** directive with an **ion-label** inside and you touch the **ion-label** the software keyboard will appear but disappear promptly after. This only happens if you touch the area with the **input-label**. This bug is reproducible on both Android and iOS.

I'm not sure precisely when this problem was introduced. I am on **'Copenhagen'** right now. Sometime after **'Amsterdam'**.

**Comment by adamdbradley** [comment]
Is this with Ionic v1 or Ionic v2? What does your markup look like?

**Comment by Tobiaswk** [comment]
Ionic v1.

Markup:
```
<ion-input class="item item-input">
					<ion-label>
						<translate>PIN-kode</translate>
					</ion-label>
					<input name="pin" type="tel" ng-model="pin.pin">
				</ion-input>
```

**Comment by crissi** [comment]
same here, tested on Android

**Comment by crissi** [comment]
Found what might be the issue: https://github.com/rubenv/angular-gettext/issues/191

**Comment by crissi** [comment]
So ion-label does not allow html at all, for focus to work, only text, that seems like an error

**Comment by Tobiaswk** [comment]
Yes I'm using https://angular-gettext.rocketeer.be for translations. Here the translate-directive is used.

That does seem like an bug.

**Comment by crissi** [comment]
easy fix is just to put "pointer-events: none;" on the inner elements.

https://css-tricks.com/almanac/properties/p/pointer-events/

**Comment by Tobiaswk** [comment]
OK. That is great! Thanks!

But of course this needs to be fix within ionic.

**Comment by Tobiaswk** [comment]
Just to close this off. Using the `{{ 'text-to-translate' | translate }}` I was able to overcome this problem. I'm not classifying this as a bug in ionic.
