### ISSUE TITLE
Alert not working on <ion-tab> Tag  ? 

### ISSUE THREAD

**Issue by bigbill91** [driftyco/ionic#5460]
Hello World

Please i need help , I'm using ionic 2.
Can i add a click action for <ion-tab> Tag to do alert ?

`<ion-tab tabTitle="Alert" (click)="doAlert()" tabIcon="alert"></ion-tab>`
```
doAlert() {
	let alert = Alert.create({
      title: 'Hello World!',
      buttons: ['Ok']
    });
    this.nav.present(alert);
}
```
Thank

**Comment by adamdbradley** [comment]
The select event is what you're looking for: https://github.com/driftyco/ionic/blob/2.0/ionic/components/tabs/test/advanced/tabs.html#L6

Also, in the future the [forum](https://forum.ionicframework.com/) would be a better place to ask questions, thanks.
