### ISSUE TITLE
pinch to zoom pdf files

### ISSUE THREAD

**Issue by antonymca** [driftyco/ionic#5462]
we are showing the pdf in iframe, the iframe is present inside <on-scroll zooming="true" direction="xy" scrollbar-x="false" scrollbar-y="false" min-zoom="1" id="scrolly"  style="width: 100%; height: 100%;"

but when we try to pinch to zoom, the zooming is not working, please help in resolving this issue.

**Comment by jgw96** [comment]
Thanks for opening an issue with us but we just need a little more info so that we can better help with this issue. Would you mind running `ionic info` and pasting the output here? This will help with the debugging of this issue. Thanks again!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by smit26** [comment]
I am displaying an pdf document on ionic Modal using JSPdf in ionic2. This is how I display the pdf and its working great.  
<pdf-viewer [src]="pdfUrl" 
  [page]="page" 
  [original-size]="false"
  style="display: block;">

I would like to add zooming functionality on pdf so user can read the small text in the document if required. 

Can someone please help me with this

**Comment by leonardosalles** [comment]
I faced the same problem with that pdf's, so I developed a zoom area component, you can install it from npm and wrap it in pdfviewer like:

```
  <zoom-area [(controls)]="showZoomControls" [(scale)]="zoomScale">
    <pdf-viewer (after-load-complete)="loadedPdf($event)" [src]="pdfBase64" [page]="1" [render-text]="true" style="display: block;" [original-size]="false" [show-all]="true" [autoresize]="false"></pdf-viewer>
  </zoom-area>
```

To install and use zoom area please check [this repo](https://github.com/leonardosalles/ionic2-zoom-area)

And all the problems are solved ;)
