### ISSUE TITLE
bug: Ionic 2 generator has wrong import?

### ISSUE THREAD

**Issue by leonsas** [driftyco/ionic#5463]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The base `ionic generate page mypage` (and, generally, all generators) are importing components from 'ionic/ionic' instead of 'ionic-framework/ionic'. The latter is used by default on `ionic start` commands.

https://github.com/driftyco/ionic/blob/2.0/tooling/generators/page/page.tmpl.js#L1</span>

Also, generators create a file extension of `.js` even its content is TypeScript and my project was created with `--ts` flag.
<span is-issue-template></span>

**Comment by BetaBugish** [comment]
+1, it also seems to output Typescript whereas the extension is .js.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#775

**Comment by adamdbradley** [comment]
Sorry, this actually needs to stay in this repo. Disregard the move!

**Comment by AdrianTeh** [comment]
+1

**Comment by tlancina** [comment]
Import should be correct with the latest release, note that the imports are now `'ionic-angular'` as we're switching package names.

TypeScript generators are being tracked here: https://github.com/driftyco/ionic-cli/issues/753.
