### ISSUE TITLE
Ionic Latest Version - Is Copenhagen 1.2.3 or 1.2.4?

### ISSUE THREAD

**Issue by jacquesdev** [driftyco/ionic#5469]
I am unfortunately very confused which version number is the 'Copenhagen' release?

This page mentions 1.2.3 as Copenhagen: https://github.com/driftyco/ionic/releases
Where this page https://github.com/driftyco/ionic/blob/master/CHANGELOG.md calls 1.2.4 Copenhagen.

Could someone please clear this up?

**Comment by perrygovier** [comment]
Technically, they both are.
Ionic 1.2.3 and 1.2.4 are tiny patch releases containing only a few commits, so we decided to use the Copenhagen name twice. I've corrected the changelog to be more clear about this. 

1.2.4 contains a small but critical fix, so consider 1.2.4 what 1.2.3 should have been. 

Thanks!
