### ISSUE TITLE
[ionic2] Nested list

### ISSUE THREAD

**Issue by pjc0247** [driftyco/ionic#5470]
I've tried to make a nested lists. But all styles in the inner list seemed to be broken.
The below code is a pseudo-code of what I've tried to make. 

```html
<ion-list>
  <ion-item>
    <ion-label>LABEL</ion-label>
  </ion-item>
  <ion-item>
    <ion-list>
      <ion-header>Language</ion-header>
      <ion-header>Language</ion-header>
      <ion-header>Language</ion-header>
      <ion-header>Language</ion-header>
    </ion-list>
  </ion-item>
</ion-list>
```

But it was rendered as

![image](https://cloud.githubusercontent.com/assets/1961216/13080974/5a58e434-d50e-11e5-8c1d-0688a81177e5.png)

Thanks.

**Comment by cyprusglobe** [comment]
what about something like this?

```
<ion-list>
   <ion-item>
      <ion-label>LABEL</ion-label>
   </ion-item>
   <ion-list>
      <ion-item>
         <ion-label>INNER LABEL</ion-label>
      </ion-item>
      <ion-item>Language</ion-item>
      <ion-item>Language</ion-item>
      <ion-item>Language</ion-item>
      <ion-item>Language</ion-item>
   </ion-list>
</ion-list>
```

**Comment by brandyscarney** [comment]
`<ion-header>` is not an Ionic component, you can use `<ion-list-header>` or `<ion-item-divider>`. Please post questions on using the framework on the forum: https://forum.ionicframework.com/c/ionic-2

http://ionicframework.com/docs/v2/components/#list-headers

Closing as it isn't an issue with the framework itself. :smile:

**Comment by pjc0247** [comment]
@cyprusglobe Your source is working, but needs some fixes for indented styling. I think I can handle it. Thanks.

@brandyscarney In [this](http://ionicframework.com/docs/v2/components/#radio) example, `ion-header` is still used. I think it should be fixed soon to prevent misuses.

**Comment by brandyscarney** [comment]
@pjc0247 Thanks for pointing that out! Created an issue here to update it: https://github.com/driftyco/ionic-site/issues/434

**Comment by pjc0247** [comment]
:smile:
