### ISSUE TITLE
docs: Passing data into tab

### ISSUE THREAD

**Issue by BetaBugish** [driftyco/ionic#5475]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There seems to be no in-depth documentation about the way you pass data into the Tab component, I checked the source and an input called "rootParams" is being specified that seems to be the solution for my use case, but there's no documentation available about that either...

I'm trying to pass some data into the view inside of the tab component.
</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This was added 2 days ago so it isn't in the latest release yet: https://github.com/driftyco/ionic/commit/e06cf71aae1b0745639839d636173020db49ba26

https://github.com/driftyco/ionic/issues/5172

It will be released in beta.1 & the docs for it will be here (I can see them on our staging site): http://ionicframework.com/docs/v2/api/components/tabs/Tab/

Thanks!
