### ISSUE TITLE
IE11 throws errors on certain animations

### ISSUE THREAD

**Issue by EMCP** [driftyco/ionic#5476]
the issue is in this area : 

```
          if (ele.classList.contains('button')) {
            eleToActivate = ele;
            break;
          }
```

sometimes in IE, `ele.classList` is returning undefined.  Am I doing anything wrong here, or is there an honest bug that needs to be fixed?  I'm not sure.

my workaround is currently as follows : 

 ```
          if (ele.classList != undefined && ele.classList.contains('button')) {
            eleToActivate = ele;
            break;
          }
```

**Comment by jgw96** [comment]
Thanks for providing some code samples for us! Would you mind running `ionic info` and pasting the output here? This will help with the debugging of the issue.

**Comment by EMCP** [comment]
```
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 7.3 Build version 7D175 



------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.4.5
 * Latest version: 1.7.14
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
------------------------------------
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately we are not currently supporting IE 11. I am sorry for any inconvenience this causes you. Because of this, i am going to close this issue for now. Thanks for using Ionic!
