### ISSUE TITLE
bug: NavController Present Modal not overlaying content

### ISSUE THREAD

**Issue by qorsmond** [driftyco/ionic#5480]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When trying to display a modal using nav.present(myModal) the screen goes blank when testing in the browser emulating IOS it shows correctly when emulating Android. 

But when testing on the device itself with Android 5.1 the modal is not shown. When I tap on the screen where the inputs should be located it seems that the inputs of the modal gets focus because the keyboard opens but you can’t see the inputs because the modal is hidden.

I tried to create a code pen but not so sure how to do it for ionic2. I did make a gist: https://gist.github.com/qorsmond/0fda766a2091431bc80e</span>

<span is-issue-template></span>

ionic info:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Node Version: v5.6.0

**Comment by qorsmond** [comment]
Here are gif's to try to show what I meant:
Working; emulating Android in chrome:
![animationa](https://cloud.githubusercontent.com/assets/4716711/13105554/6d1cee68-d56c-11e5-887c-4dd06e51a79c.gif)
Not showing modal; emulating IOS in chrome:
![animation](https://cloud.githubusercontent.com/assets/4716711/13105557/78ab5602-d56c-11e5-95d6-a15c5a7676d4.gif)

**Comment by adamdbradley** [comment]
Thanks for the report, we'll take a look and try to get this fixed up.

**Comment by adamdbradley** [comment]
Have you tried removing the `autofocus` from the ion-input? I understand it should autofocus when it comes up, but I'm just trying to narrow down what's causing it.

**Comment by qorsmond** [comment]
Just tried it and removing the `autofocus` from the ion-input did the trick! Maybe it is the Chrome IOS emulator causing the issue? Not able to test directly on IOS.

**Comment by adamdbradley** [comment]
Great thanks, i just made some changes so autofocus doesn't get added to the native input element directly, but let's ionic control how to autofocus.
