### ISSUE TITLE
Form is private / not exported - can't provide for it during tests

### ISSUE THREAD

**Issue by lathonez** [driftyco/ionic#5494]
#### Short description of the problem:

With reference to http://stackoverflow.com/questions/35469338/testing-ionic2-component-no-provider-for-form

As per the SO question - I'm trying to unit test a component which is using Ionic's TextInput directive.

```
@View({
  templateUrl: 'build/components/checkinDateInput/checkinDateInput.html',
  directives: [ Item, Label, TextInput ],
})
```

```
<ion-item>
  <ion-input type="date" [ngFormControl]='control' placeholder="{{placeholder}}"></ion-input>
</ion-item>
```

When testing I'm getting `No provider for Form! (Item -> Form)`. However I can't provide for the Form because it isn't exported by Ionic. When I export myself (e.g. by hacking the relevant files in ionic-framework) - it provides for the test and works fine.

#### What behavior are you expecting?

I see in `config/directives.d.ts` that TextInput is listed under "Forms", thus I kinda expected to be able to provide just for TextInput and have it all work.

**Steps to reproduce:**

Try to unit test a very simple component using the TextInput directive. Sample code for the unit test:

```
import {
  beforeEach,
  beforeEachProviders,
  ComponentFixture,
  describe,
  expect,
  injectAsync,
  it,
  TestComponentBuilder,
}                                       from 'angular2/testing';
import { TextInput }                    from 'ionic-framework-ionic';
import { MyComponent }                  from './myComponent';

let myComponentFixture: ComponentFixture = null;
let myComponent: MyComponent = null;

export function main(): void {

  describe('MyComponent', () => {

    beforeEachProviders(() => [TextInput]);

    beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
      return tcb
        .createAsync(MyComponent)
        .then((componentFixture: ComponentFixture) => {
          myComponentFixture = componentFixture;
          myComponent = componentFixture.componentInstance;
        })
        .catch(Utils.promiseCatchHandler);
    }));

    it('initialises', () => {
      expect(myComponent).toBeDefined();
    });
  });
}
```

**Ionic Version**: ionic-framework@2.0.0-beta.0

**Browser & Operating System**: Ubuntu / PhantomJS2 / Chrome

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.6.0
```

**Comment by adamdbradley** [comment]
Yeah looks like we forgot that one, should be fixed in the next release, thanks.

**Comment by lathonez** [comment]
@adamdbradley cheers.
