### ISSUE TITLE
bug: ion-select does not show selected if number

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#5495]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you have the following code:

```
<ion-item>
  <ion-label>Watering Mode</ion-label>
  <ion-select [(ngModel)]="zone.kind">
    <ion-option *ngFor="#key of modeKeys">{{key}}</ion-option>
  </ion-select>
</ion-item>
```
and 

```
  this.zone = {
    kind: 'key2'
  }
  this.modeKeys = [
    'key1',
    'key2',
    'key3',
    'key4',
  ]
```
A select component is displayed with 'key2' shown as selected.

But if you change the data to this:

```
  this.zone = {
    kind: 2
  }
  this.modeKeys = [
    1,
    2,
    3,
    4,
  ]
```
It does not work.  Seems the component prefer strings.

https://forum.ionicframework.com/t/ion-select-with-dynamic-options/43720/7</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
You're right, and I think this was a bug in beta0 that was recently fixed in master. Here's a test example that seems to be working: https://github.com/driftyco/ionic/commit/7e3eb23345a197552ac5ed8483c69d8eb689008a

**Comment by JumBay** [comment]
Actually the bug is still present in the beta2.

**Comment by jasonwaters** [comment]
I can confirm, this issue is not fixed in beta2. @adamdbradley
