### ISSUE TITLE
Stop ng-click propagation on list item buttons

### ISSUE THREAD

**Issue by xuyuanme** [driftyco/ionic#550]
Currently the item option buttons and delete button on the list item will propagate the click event. So if another ng-click function is defined on the list item itself, it will be triggered by clicking the build-in item option or delete button, which is sometimes unwanted.

Adding $event.stopPropagation() in the ionicList.js template would help, or at least there should be an option to let user choose stop the ng-click propagation:

```
// js/ext/angular/src/directive/ionicList.js
ng-click="deleteClick(); $event.stopPropagation();"
ng-click="b.onTap(item, b); $event.stopPropagation();"
```

**Comment by techhysahil** [comment]
ion-stop-event solve the problem on laptop browser but the issue still persist on android app.
