### ISSUE TITLE
the silides cannot autoplay

### ISSUE THREAD

**Issue by judypol** [driftyco/ionic#5501]
I have used the ionic2 slides in my app,but it cannot autoplay,the code is below:
````
<div style="height: 100px;">
    <ion-slides loop="true" autoplay="true">
      <ion-slide style="background-color: green">
        <h2>Slide 1</h2>
      </ion-slide>
      <ion-slide style="background-color: blue">
        <h2>Slide 2</h2>
      </ion-slide>

      <ion-slide style="background-color: red">
        <h2>Slide 3</h2>
      </ion-slide>
    </ion-slides>
  </div>
````

**Comment by brandyscarney** [comment]
This is resolved by this issue - https://github.com/driftyco/ionic/issues/5189 so it will be in the next release. Attributes are being removed in favor of passing them all through options so you can use any of the swiper options. Thanks for the issue!
