### ISSUE TITLE
ionic serve problem 

### ISSUE THREAD

**Issue by hossam9995** [driftyco/ionic#5504]
#### Short description of the problem:
when i start ionic command its work fine, but when i work with chrome developer tools by (right mouse buttom - > inspect  )
the the page will refresh frequently and this error appear to me on console 

chrome-extension://hejbpbhdhhchmmcgmccpnngfedalkmkm/src/injected/inspector.js:121 Uncaught TypeError: Cannot convert undefined or null to objectinstrumentDigest @ chrome-extension://hejbpbhdhhchmmcgmccpnngfedalkmkm/src/injected/inspector.js:121bootstrapInspector @ chrome-extension://hejbpbhdhhchmmcgmccpnngfedalkmkm/src/injected/inspector.js:99detectAngular @ chrome-extension://hejbpbhdhhchmmcgmccpnngfedalkmkm/src/injected/inspector.js:86
Navigated to http://localhost:8100/
inspector.js:121 Uncaught TypeError: Cannot convert undefined or null to objectinstrumentDigest @ inspector.js:121bootstrapInspector @ inspector.js:99detectAngular @ inspector.js:86
Navigated to http://localhost:8100/
inspector.js:121 Uncaught TypeError: Cannot convert undefined or null to objectinstrumentDigest @ 
  
#### What behavior are you expecting?

i try to do that with my machine and i face this issue 
and then i create a VM and then i install ionic and dependence and i face the same problem ?!!

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.2.2

**Browser & Operating System**: iOS / Android / Chrome

chrome / lunix 

**Run `ionic info` from terminal/cmd prompt:**
```
paste output from `ionic info` here
```
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.2.2

**Comment by hossam9995** [comment]
http://i66.tinypic.com/98di13.png
photo for error

**Comment by adamdbradley** [comment]
The error appears to be coming a chrome extension. Just for testing out a few things, do you have the same issue in firefox?

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#782

**Comment by hossam9995** [comment]
@adamdbradley

in firefox its work fine 100% but on the chrome the error extension face me,
