### ISSUE TITLE
bug: tinder  demo broken

### ISSUE THREAD

**Issue by GeoffreyEmery** [driftyco/ionic#5506]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>this demo is broken http://codepen.io/ionic/pen/nxEdH</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Should be updated now. 
http://codepen.io/ionic/pen/nxEdH
