### ISSUE TITLE
Improve Slides

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5508]
Known issues:
- [x] Pager is an attribute - probably want to use the swiper version - options
- [x] Multiple sliders on one page use the same pagination
- [x] Improve documentation behind options and methods
- [ ] Remove timeout around create
- [ ] Don't emit slide events when runCallbacks is false

**Comment by steveharbick** [comment]
I'm hoping there is (to be documented), or will be (added), a way to access the Swiper API's method: mySwiper.slideTo(index, speed, runCallbacks). This is particularly useful for using slides on first-run and allowing user to skip to end if they want.

**Comment by brandyscarney** [comment]
@steveharbick There's actually been a PR submitted for this it's just something we need to look into merging. :smile: https://github.com/driftyco/ionic/pull/5491

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic/issues/6198

**Comment by brandyscarney** [comment]
So some of the improvements were made. I improved the docs to add a lot more information and document the methods better, these can be seen here: http://ionicframework.com/docs/v2/api/components/slides/Slides/

Please check the changelog for the breaking changes to slides in beta.5: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta5-2016-04-20

Let me know if you have any feedback on the docs! Going to move this issue to beta.6 to continue work on it.

**Comment by davyzhang** [comment]
slideTo marked time is an optional parameter, but can not omitted in typescript
```
    /**
     * Transition to the specified slide.
     *
     * @param {number} index  The index number of the slide.
     * @param {number} speed  Transition duration (in ms). Optional.
     * @param {boolean} runCallbacks  Whether or not to emit the `willChange`/`didChange` events. Optional. Default true.
     */
    slideTo(index: number, speed: number, runCallbacks: boolean): void;
```

**Comment by brandyscarney** [comment]
Thanks for pointing that out @davyzhang, I fixed it in the source so it should be in the next release! Sorry about that. :smile:

**Comment by davyzhang** [comment]
Fantastic, Thanks for the great work.

**Comment by teledemic** [comment]
Looping doesn't seem to work when the slides are loaded dynamically. For example:
```
<ion-slides [options]="optsWithLoopEnabled">
  <ion-slide>
    <img src="1.jpg">
  </ion-slide>
  <ion-slide>
    <img src="2.jpg">
  </ion-slide>
</ion-slides>
```
works great and does the behind the scenes duplication so that you can swipe from last to first or vice versa. However:
```
<ion-slides [options]="optsWithLoopEnabled">
  <ion-slide *ngFor="let slide of mySlides">>
    <img src="{{slide.image}}">
  </ion-slide>
</ion-slides>
```
does not work as the duplication doesn't happen, so swiping last to first flickers to the first and then skips one. Looped autoplay is broken in the same way.

**Comment by ramonornela** [comment]
Related: #7422

**Comment by brandyscarney** [comment]
Closing this since slides have been refactored.

**Comment by tmk1991** [comment]
Any update on having multiple sliders on one page?

**Comment by btribouillet** [comment]
> Any update on having multiple sliders on one page?

Indeed it would be great! I was amazed about this component but it is too bad we can't use multiple sliders on one page.
