### ISSUE TITLE
docs: V2 - Gesture/Event Documentation

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5510]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I cannot figure out how to access gestures/events in V2.  I see hammer.js is still in there.  However - it doesn't appear to be exposed.

The documentation for V1 gesture's is great:
http://ionicframework.com/docs/api/directive/onHold/

Can we get something like this for V2?</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#447
