### ISSUE TITLE
materializecss android native back button is not working

### ISSUE THREAD

**Issue by gauravshegokar** [driftyco/ionic#5514]
added materializecss to app, everything is working fine. but the problem is with the back button of android. It gets buffered, when i go to another view then back button is processed. If i clicked multiple times on back button all that is executed when i change view.
app is running on latest ionic version.

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! Would you mind sharing a code sample so that we can easily reproduce your issue? Also are you currently using Ionic v1 or Ionic 2? Thanks again!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
