### ISSUE TITLE
SqlStorage should use integer database version

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic#5518]
Note: I tried submitting this via your submission app form, but it gave me a submission error with no information as to how I could correct the situation.

Attempting to open a new database using SqlStorage running in a Chromium browser fails with a version mismatch (1.0 versus 1), due to use of a string version instead of an integer. According to [the IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB), version numbers must be integral.

#### Short description of the problem:
Opening database under Chromium fails with version mismatch.

#### What behavior are you expecting?
Database created properly.

**Steps to reproduce:**
1. create new Storage object with SqlStorage backend

```
let db = new Storage(SqlStorage, {name: 'dbname'});
```

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Debian Description:	Debian GNU/Linux unstable (sid) 
Node Version: v5.5.0
```

**Comment by adamdbradley** [comment]
All of the examples I've seen for Web SQL uses a string:

https://www.w3.org/TR/webdatabase/
http://html5doctor.com/introducing-web-sql-databases/
http://docs.phonegap.com/en/edge/cordova_storage_storage.opendatabase.md.html

Docs you referenced was for IndexedDB. But when you change it to a string it then works for you?

**Comment by rapropos** [comment]
When the app is running in Chromium, IndexedDB seems to be used as the backend. The error I receive when using the string version is identical to the one described in [this StackOverflow question about a different WebSql / IndexedDB library](http://stackoverflow.com/questions/23679449/indexeddbshim-polyfill-version-mismatch), which gave me the inspiration for trying an integer version. If I switch it to an integral 1 as in the pull request, the error goes away.

**Comment by rapropos** [comment]
However, this fix may just kick the problem down the road a bit, because I am not able to use the created database. Further investigation needed.

**Comment by rapropos** [comment]
Underlying root cause of problem actually involved SSL certificate trust chain. Somehow a different code path that accepted only integral versions for WebSql calls is triggered when an HTTPS connection is being used with a trust override (where testing environment is using different DNS name for certificate). Hopefully anybody else running into that obscure problem finds this. The ultimate solution is to ensure that the certificate is somehow trusted via libnss. Closing this as not a fundamental Ionic bug, sorry for the noise.
