### ISSUE TITLE
Concerning the docs in the website

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#5520]
This is more of a suggestion. I was recommending my friend (he's a noob) to try ionic2 in order to play with it, but he told me he did everything in the steps and no luck. The problem was he didn't know he had to install node.js on his computer. 

My recommendation would be to make complete instruction for noobies that are just starting to use the ionic CLI. Or at least tell them to install nodejs and 'npm install cordova' and whatever else is needed!

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-site#450
