### ISSUE TITLE
I have installed ionic2' CLI,now ionic serve does't work in a new ionic2 project

### ISSUE THREAD

**Issue by yangheng** [driftyco/ionic#5521]
#### I have installed ionic2' CLI,now ionic serve does't work in a new ionic2 project

In ionic2 project, ionic serve does't work.while i try start a ionic1 project and cd &,ionic serve works !! What's matter ?

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 

```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#786
