### ISSUE TITLE
Text Align not working on iOS. iphone 6 ios 9.2

### ISSUE THREAD

**Issue by gnasit** [driftyco/ionic#5522]
#### Short description of the problem:

I have a modal where i have a couple of text inputs, one of type "tel", the other of type "date", i have added the 'style="text-align: right"' attribute to these text inputs, and it does not seem to work on the phone in ionic-view, thus i am suspecting that it won't work on the regular phone as well.

Based on an earlier thread looks like this issue is on android as well.
here is the issue link: [https://github.com/driftyco/ionic/issues/1929]
#### What behavior are you expecting?

the text should align right on the phone

**Steps to reproduce:**
I have forked a similar codepen and made changes to what I have in my app, where a modal shows up. I am using the form in a modal as well, thus this issue is pretty similar in my case as well.
http://codepen.io/soul_/pen/WrBpLG

Once you run the code pen, click on "Form" button and type any content in it, on the browser it will align fine. It align's fine in the emulator as well, the issue is on the real device though.

```
//code is there in the link above in codepen.
/*For me in the preview, the code pen did not seem to take me to code pen, i had to manually copy the codepen link and paste it into the browser.*/
```

**Ionic Version**: 1.7.14

**Browser & Operating System**: iOS / Android

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

Please see below for images for the issue on the phone:
input type "tel"
![tel](https://cloud.githubusercontent.com/assets/16493338/13165175/6ff25d0c-d680-11e5-9f0f-477051334b20.PNG)

input type "date"
![date](https://cloud.githubusercontent.com/assets/16493338/13165181/782bbb12-d680-11e5-8478-db3e9605c6fa.PNG)

**Comment by barayuda** [comment]
I have same issue here, have tried using display on css. But, not fixed.
Have I missing something?

**Comment by gnasit** [comment]
any traction on this?

**Comment by barayuda** [comment]
maybe will be fix on next update @gnasit :)

**Comment by mhartington** [comment]
Sorry the delay :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by gnasit** [comment]
http://codepen.io/soul_/pen/WrBpLG. I have explained the instructions as well in the issue above.

**Comment by gnasit** [comment]
may i please know how often do issues get looked upon?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#196
