### ISSUE TITLE
bug: popToRoot() within tabbed page

### ISSUE THREAD

**Issue by mebibou** [driftyco/ionic#5526]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a `rootPage` which is a simple page with a view. Upon login, the user navigates to a tabbed page, with 3 tabs. The user can then decide to log-out, and will be redirected to the above `rootPage`. The code I use is:
````
this._nav.setRoot(HomePage);
this._nav.push(HomePage);
````
By doing this, on the browser it works well, Android device as well but on iOs the `HomePage` will replace the current view but within the tabbed content, i.e. I will see the tabs at the bottom, and if I login again, then I'm in a state where I have two set of tabs on top of each other.

Note: I have tried to use `this._nav.popToRoot();` instead but it would just show the root of the tabbed page instead of going back to the real `rootPage`</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Have you tried using just `this._nav.setRoot(HomePage);`? In the above example you set the root to HomePage, then immediately push to the same page, so I'm curious if that's the issue.

**Comment by lordgreg** [comment]
@mebibou isn't this the same issue as: https://github.com/driftyco/ionic/issues/5196?

**Comment by jgw96** [comment]
@adamdbradley @mebibou fixing to test this myself and see if i can repro the issue.

**Comment by adamdbradley** [comment]
Thanks @lordgreg this does look the same as #5196. I'll close this one since it's a duplicate.

**Comment by jgw96** [comment]
Platform: Android 6.0.1
Phone: Nexus 6

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

Setting a root page and then pushing that root to the stack does seem to cause weird issues like the user described. The proper way that does not cause any issues is just to simply set the root page. This will navigate the user to that root page. So should just be `this._nav.setRoot(HomePage);` I observed the same behavior on the ios simulator.

**Comment by mebibou** [comment]
@adamdbradley @jgw96  if I just do `this._nav.setRoot(HomePage);`, then the tabs appear in the browser and android as shown in this screenshot:
![bug tabs root](https://cloud.githubusercontent.com/assets/305342/13206804/88a34fa6-d940-11e5-84da-320220e24189.png)

and for ios, nothing happens at all.

**Comment by mebibou** [comment]
And I've tried doing like on #5196 `this._nav.pop(HomePage);` but it just pops back one step

**Comment by jgw96** [comment]
@mebibou Is it possible for us to see more of your code? I think there may be something else going on here.

**Comment by mebibou** [comment]
Yep:
````
git clone https://github.com/mebibou/ionic2-tabs-poptoroot.git
cd ionic2-tabs-poptoroot
npm install
ionic serve
````
Steps:
* Load the app on the home page
* go to the tabs
* go to the child of the first tab
* click on one of the 3 methods to go back to home page, none of them work

**Comment by lordgreg** [comment]
@mebibou this is the exact same issue I've posted here: https://github.com/driftyco/ionic/issues/5196

As @adamdbradley stated there, he fixed the issue and should be available in next release.

**Comment by mebibou** [comment]
@lordgreg I will sure try again in `beta2` then ;)

**Comment by mebibou** [comment]
@lordgreg @adamdbradley To come back on this, I just updated to the `beta2` and the problem is still here, please check my test repo at `git clone https://github.com/mebibou/ionic2-tabs-poptoroot.git`

**Comment by kamok** [comment]
I'm having the same problem with 'navCtrl.popToRoot()'. It was working when I had it in another part of the component, and breaks when I refactored things around.

**Comment by Marimuthu1** [comment]
Hi, anyone got solution for this? Now i'm also faced same issue.
