### ISSUE TITLE
docs: Improve v2 migration docs

### ISSUE THREAD

**Issue by ricsmania** [driftyco/ionic#5528]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The migration docs (http://ionicframework.com/docs/v2/getting-started/migration/) do a good job explaning how to project should be structured the make the migration easier. But they don't provide actual steps to migrate the app. More specifically, there is nothing about how to bootstrap using the UpgradeAdapter.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-site#449
