### ISSUE TITLE
ion-input: when closing keyboard padding bottom is not removed

### ISSUE THREAD

**Issue by cho-is** [driftyco/ionic#5529]
#### Short description of the problem:
ion-input, when tapping on the field, the keyboard shows up.
When closing the keyboard, the bottom padding is not removed so scroll remains same as when the keyboard is open. 

**Steps to reproduce:**
1. Tap in ion input
2. close keyboard
3. scroll remains increased (padding at the bottom of ion-content)

**Ionic Version**: 2.0.0-beta.17

**Browser & Operating System**: Android / Chrome

**ionic info:**

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Not installed
```

**Comment by adamdbradley** [comment]
This is something that's by design and still something we're working on. Basically when you remove that padding, while the keyboard is also transitioning away, it's extremely janky to the point leaving that padding there is the lesser of two evils. But like I said, we're still working on better solutions.

**Comment by cho-is** [comment]
Nice to hear that. Many thanks.

**Comment by raducostea** [comment]
Any news on this one? When it will be tweaked?

**Comment by EvanWillms** [comment]
#5432 gets reported again :)

@raducostea I'm personally turning off the troublesome ionic keyboard padding and falling back to the device native behavior of letting the whole page slide up and down in the meantime.  You might be able to tweak your own app with one of the config workarounds I've identified at:
https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/5?u=evanwillms

**Comment by layton-glympse** [comment]
...So the issue is just "closed" until further notice? This is actually a huge deal for UX, I'd honestly prefer a little "jank" to having the entire UX of a page changed unalterably once the keyboard goes away...

**Comment by vofili** [comment]
im experiencing this same issue
