### ISSUE TITLE
Tab icons collapse on first load iOS8

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#5531]
#### Short description of the problem:
As the video shows tab icons are collapsed for a moment and the go back to normal.
http://imgur.com/7jnCMGT

### What behavior are you expecting?
I have all css minified in one file. 
On android it works well.

**Steps to reproduce:**
1. I am using a standard tab bar in the bottom

**Ionic Version**: 1.4

**Browser & Operating System**: iOS / Android / Chrome
iOS8

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1967
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
OS: Windows 7 SP1
Node Version: v4.2.1

**Comment by mhartington** [comment]
Please provide a minimal codepen for testing.

**Comment by mhartington** [comment]
Hey there! So it looks this issues has been inactive for some time. I'm going to close it. If there's still an issue, please submit a new issue with the steps to reproduce. Thanks!

**Comment by barocsi** [comment]
Switched to wkwebview and the problem was not present there.
