### ISSUE TITLE
<ion-input> keyboard attach problem

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#5536]
#### Short description of the problem:
When I focus an `<ion-input>` which is positioned lower than the height of the keyboard, the input is getting hidden by the keyboard (It is not floating above so I cant see what I am typing). Also when I type 1 letter, the keyboard disappears. Another thing is that when I focus an input and the keyboard comes out, and than I try to focus another input field, the keyboard is disappearing and appearing again. 

#### What behavior are you expecting?
I am expecting the input to get scrolled up above the keyboard so I can see what I am typing. Also I should be able to type more than 1 letter

**Steps to reproduce:**
1.  Create List with 5-6 ion-items which are containing ion inputs. Than try to focus the lowest positioned (6th in this case) input, and see that you wont be able to see the input above the keyboard and when you try to type 1 letter the keyboard will disappear

**Ionic Version**: 2

**Browser & Operating System**: iOS / Android / Chrome
I have this problem on Android Nexus 5 (I am also using crosswalk). It works fine in Ionic View, but still on focusing different input the keyboard is disappearing and appearing again.

**Comment by denkomanceski** [comment]
any progress on this ?

**Comment by privetr** [comment]
A bug which is similar to this one : 

On Android 6.0, Ionic 2 : 
When an input which is at the bottom of the page is focused, Keyboard is opened. The Input goes up and we can see what we write on. But when we close the keyboard, the input stays at the same place, so there is a big blank at the end of the page (See attached images).

This seems critical. 
![screenshot1](https://cloud.githubusercontent.com/assets/8597289/13334931/d63a0cac-dc0e-11e5-95d7-df1fb1b9e624.png)
![screenshot2](https://cloud.githubusercontent.com/assets/8597289/13334932/d72bb778-dc0e-11e5-8a1e-05a3fdac2966.png)
![screenshot3](https://cloud.githubusercontent.com/assets/8597289/13334933/d7326636-dc0e-11e5-92dd-a32834e87022.png)

**Comment by matitalatina** [comment]
Same bug here...
Now it's completely inusable.
![scrollbug](https://cloud.githubusercontent.com/assets/2093741/13723786/cc628f16-e86f-11e5-9224-d01ccfb74f34.gif)

**Comment by EvanWillms** [comment]
@privetr @matitalatina It appears the canonical ionic issue for tracking the blank-space-after-keyboard-input is #5432.  I've found a temporary workaround with a not-yet-documented config flag that turns off the padding insert and prevents the space from getting created:

https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/5?u=evanwillms

**Comment by privetr** [comment]
@EvanWillms Thanks for the information, I will check if it solves the problem !

**Comment by adamdbradley** [comment]
I've made some fixes in input focusing. Would this group be able to install the nightly version and let me know how it's working for your app: https://github.com/driftyco/ionic/tree/2.0/scripts#installing-nightly-version

thanks

**Comment by matitalatina** [comment]
@adamdbradley It's far far better now, at least now it's usable. Good job! :)

By the way I notice two bugs:

- If I tap on an input below the keyboard, the keyboard appears and hides the input. But now I can scroll to input and keyboard doesn't disappear when I'm scrolling. The expected behaviour, I think, the view should automatically scroll to show the input. Not a big deal for now.
- Step to reproduce the second bug: I tap on text input, the keyboard appears, I hide the keyboard with back button, I tap on a toggle, the keyboard appears. Expected behaviour: the keyboard shouldn't appear when I tap on a toggle.

I hope my findings are helpful to improve the quality of this already fantastic framework :).

**Comment by nunoarruda** [comment]
both keyboard attach and/or scrollToBottom() would be handy for my current Ionic project.

**Comment by adamdbradley** [comment]
Great thanks everyone! 

Also, @nunoarruda I just added `scrollToBottom()` that will go in the next release, hope that helps. https://github.com/driftyco/ionic/commit/bef4a67025c76af80b5482a2878244152a1b9288#diff-b060bb2c9ba0b7db4373e59425e611bbR111

**Comment by nunoarruda** [comment]
@adamdbradley thanks! Any news on a keyboard-attach directive for v2 [like v1](http://ionicframework.com/docs/api/directive/keyboardAttach/) has?

**Comment by Manduro** [comment]
For anyone listening here: I've just posted my v2 keyboard-attach port [here](https://github.com/driftyco/ionic/issues/5432#issuecomment-246996098).

**Comment by aszmyd** [comment]
Turns out that switching for pure HTML input element makes the trick. For some reason `ion-input` directive is not working properly. http://stackoverflow.com/a/37083957/1433658

**Comment by finalxcode** [comment]
you can solved this issues follow these steps:
1.app.module.ts
`IonicModule.forRoot(MyApp, {
        platforms: {
          ios: {
            scrollAssist: false,
            autoFocusAssist: false
          }
        }
    })`
2.app.component.ts
`IonicModule.forRoot(MyApp, {
        platforms: {
          ios: {
            scrollAssist: false,
            autoFocusAssist: false
          }
        }
    })`

**Comment by royipressburger** [comment]
I have the same problem after updating to rc3

**Comment by fvsaddam** [comment]
following @finalxcode code for rc4, but not work to ionic view using ios, but in android it work well.

what going wrong with it?

**Comment by anatoly-spb** [comment]
finalxcode, thank you so much. Now I can disable scroll with scrollAssist: false,  autoFocusAssist: false. But these options are not in here http://ionicframework.com/docs/v2/api/config/Config/ . Are these private options?

**Comment by sidneycorreia** [comment]
I have the same problem.

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by calidion** [comment]
I am encountered this problem too.
which makes input useless for ios app.
I have no idea how to solve this.

**Comment by nunoarruda** [comment]
There's several workarounds in the following SO post: http://stackoverflow.com/questions/36706398/in-ionic-2-how-to-float-an-element-above-the-keyboard-when-the-keyboard-shows
