### ISSUE TITLE
bug: Radio and checkbox problem in alert

### ISSUE THREAD

**Issue by BilelKrichen** [driftyco/ionic#5538]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Radio and checkbox not showing correctly when i add them with prompts in alert

https://forum.ionicframework.com/uploads/default/original/3X/b/6/b68c9c6ecbd4774899b82a29c36371bef461ff75.png</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Would you be able to provide a code example of how you're writing this?
https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/basic/index.ts#L122

**Comment by BilelKrichen** [comment]
Yes , I do this example, It's work when I add radio buttons only, but it doesn't work when I add  them with inputs  

```
let alert = Alert.create({
title: "Alert",
inputs:
[
{
name : 'FirstName',
placeholder: "FirstName"
},
{
name: "LastName",
placeholder: "LastName"
},
{
name: "Phone",
placeholder: "Phone"
},
{
name: "E-mail",
placeholder: "E-mail"
},
{
type: "radio",
label: "male",
value:"m"
},
{
type: "radio",
label: "female",
value:"f"
},
],
buttons: [
{
text: 'Cancel',
handler: data => {
console.log('Cancel clicked');
}
},
{
text: 'Save',
handler: data => {
console.log('Saved clicked');
}
}
]
});
this.nav.present(alert);
```
And the same think when I add buttons and inputs with `alert.addInput({})`

**Comment by adamdbradley** [comment]
The alert does not allow mixing different types of inputs, like radio and checkboxes, or radio and inputs. I just updated the docs with that info, and also created a warning within the framework. Thanks

https://github.com/driftyco/ionic/commit/74a48f3b64f9613d9ff8992c6bd17de0f743bbed

**Comment by BilelKrichen** [comment]
Thanks for reply, but is there a feature to mix different types of inputs?
