### ISSUE TITLE
The request entry was not found in the cache - android run -lcs

### ISSUE THREAD

**Issue by apavillet** [driftyco/ionic#5539]
#### Short description of the problem:
When launching the app after doing ionic run android -lcs i'm getting 

"Application Error"
 The request entry was not found in the cache ( http:xxxxx <= local ionic url )
"
Clicking ok on the dialog closes the app
This is new the app was working fine until now, did anyone know what could cause this?

EDIT / Building the app and installing via adb works

#### What behavior are you expecting?

The app should be working ;)

**Ionic Version**: 1.2.4 / CLI is 1.7.14

**Browser & Operating System**: iOS / Android / Chrome
Android

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#788

**Comment by apavillet** [comment]
Thanks @adamdbradley sorry for the miss :)
