### ISSUE TITLE
bug: Setting filter: brightness outputs an error in cli

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5542]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have this scss for one div in my file:
```
    .bg {
      padding: 0;
      background-image: url('../../assets/images/bg-placeholder.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-color: black;
      position: absolute;
      width: 100%;
      height: 100%;
      filter: brightness(0.5);
      background-size: cover;
    }
```

This error gets printed in CLI:
```
 ✗ node_modules\ionic-framework\util\functions.scss
Error: argument `$color` of `red($color)` must be a color

       Backtrace:
        node_modules/ionic-framework/util/functions.scss:6, in function `red`
        node_modules/ionic-framework/util/functions.scss:6, in function `brightness`
        app/app.scss:49
        on line 6 of node_modules/ionic-framework/util/functions.scss
>>   @return (red($color-value) * 0.299 + green($color-value) * 0.587 + blue($col
   -----------^
```

As soon as I remove the `filter: brightness(0.5);` part, it starts working. If I select any other filter (opacity, blur,..) it works.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Ok, it's because of a `brightness` function that I recently added, so Sass is using it instead of just the css value instead. I'll rename the sass function to fix this, thanks.
