### ISSUE TITLE
ionic generate does not use new @Inject syntax

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic#5544]
#### Short description of the problem:

When using any of the `ionic generate` commands, the generated code does not use the new @Inject syntax in the constructor.

#### What behavior are you expecting?

The generated code should use @Inject, i.e:

```
  constructor(@Inject(Http) http) {
    this.http = http;
    this.data = null;
  }
```

**Steps to reproduce:**
1. Generate new project with `ionic start MyApp blank --v2`
2. Run `ionic g provider MyProvider` or any of the other generate commands

**Ionic Version**: 2.0.0-beta.1

**Browser & Operating System**: Mac / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by tlancina** [comment]
Thanks! Should be fixed in the next release.
