### ISSUE TITLE
When scrolling sidemenu opens and gets stuck

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#5545]
#### Short description of the problem:
Sometimes when scrolling through a list the sidemenu will open, get stuck and not allow the user to close it.

#### What behavior are you expecting?
User scrolls through list without menu randomly opening, and if it does open be able to close it.

**Steps to reproduce:**
1. Scroll through a relatively long list on a sidemenu app

**Ionic Version**: 2.0.0-beta.1

**Browser & Operating System**: 
OS: Android 6.0.1
Device: Nexus 6

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.7.0
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by lordgreg** [comment]
This issue was already addressed a while a go (https://github.com/driftyco/ionic/issues/5272) and fixed. I guess its about the same behaviour?

**Comment by jgw96** [comment]
Sorry, didnt meen to open duplicate. closing now

**Comment by lordgreg** [comment]
This isn't duplicate @jgw96. The issue I've posted was already resolved. But that was at alpha versions. That's why I'm asking. Reopen it :+1:
