### ISSUE TITLE
User-Agent difference when I restart the app

### ISSUE THREAD

**Issue by vactorlao** [driftyco/ionic#5547]
#### Short description of the problem:
User-Agent always difference when I restart the app

![image](https://cloud.githubusercontent.com/assets/7175977/13202818/f271d3de-d8e2-11e5-8c46-a879b8a83e3d.png)

![image](https://cloud.githubusercontent.com/assets/7175977/13202828/206836ca-d8e3-11e5-8bd6-967959f1f0ce.png)

![image](https://cloud.githubusercontent.com/assets/7175977/13202833/302515ba-d8e3-11e5-89f1-43e68e0af13a.png)

![image](https://cloud.githubusercontent.com/assets/7175977/13202867/b7f6f83c-d8e3-11e5-80b2-ee0f972d80ab.png)

#### What behavior are you expecting?
Is it possible to make them same?

Btw if I use Safari instead, then I get:
![image](https://cloud.githubusercontent.com/assets/7175977/13202876/e164fc78-d8e3-11e5-8f4e-f82f989e213a.png)

**Ionic Version**: 2.x

**Browser & Operating System**: iOS 9.2.1 (13D15)
**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by tlancina** [comment]
Looks like Cordova adds this to the user agent:

```

    NSString* appendUserAgent = [self.settings cordovaSettingForKey:@"AppendUserAgent"];
    if (appendUserAgent) {
        _userAgent = [NSString stringWithFormat:@"%@ %@", localBaseUserAgent, appendUserAgent];
    } else {
        // Use our address as a unique number to append to the User-Agent.
        _userAgent = [NSString stringWithFormat:@"%@ (%lld)", localBaseUserAgent, (long long)self];
    }
```
 from: [cordova-ios/CordovaLib/Classes/Public/CDVViewController.m#L443-L449](https://github.com/apache/cordova-ios/blob/813a3bac10320c70a890aaf35ea96a069c6b8e21/CordovaLib/Classes/Public/CDVViewController.m#L443-L449)

But you're in luck, you can specify to always use the same string using [`<preference name="AppendUserAgent" value="MyApp" />`](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/config.html).

Originally I was going to suggest using a blank string, but I'm worried that Cordova internally may rely on having an ID of some kind appended to the user agent, so I think it's probably safer (if all you need is for it to be consistent) to use an actual string.
