### ISSUE TITLE
bug: Content with cards scrolls immediately to top

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5548]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have cards in my `ion-content`. Say, 20. Scrolling to bottom goes smooth as it should. But, being almost at the bottom of the content and then scrolling/swiping to go up, immediately jumps to top of the content. To test the issue in browser, click and hold content and try to swipe up.

This looks like a total mess in browser and on device (android) I've tested. Unsure if this is a performance issue or just a bug, but it looks horrible. 

Affected platforms (couldn't test on iOS):
- Android 5.1.1
- Google Canary [latest]
- Google Chrome 48.0.2564.116 m

I did noticed an console.info popping up in Chrome: `Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`(pull-to-refresh.js:335)

Thank you for looking into it.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Are you using pull to refresh? Can you provide some code that can replicate the issue?

**Comment by lordgreg** [comment]
@adamdbradley: Yes, I am using pull to refresh. Will create new repo and post it here in few minutes.

**Comment by lordgreg** [comment]
@adamdbradley I've just created new repo:

`git clone https://github.com/lordgreg/ionic2-scrollWithLotsOfCards.git`

It looks like this is the issue with card + pull to refresh

**Comment by brandyscarney** [comment]
Going to work on fixing this as part of this issue: https://github.com/driftyco/ionic/issues/5207
