### ISSUE TITLE
perf: Swipe to refresh is utterly bad on Android

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5550]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Having a list of card in my content, I also use swipe-to-refresh. Pulling the content down to refresh doesn't run smoothly at all. Its more like playing new-age game with ultra settings on very bad, bad computer.</span>

<span is-issue-template></span>

**Comment by lordgreg** [comment]
Also, keep in mind, when doing a refresh, the Icon hides immediately and doesn't wait for `refresher.complete()` to be called.

**Comment by brandyscarney** [comment]
Yes, there is an open issue for all of the problems with Pull to Refresh: https://github.com/driftyco/ionic/issues/5207. Leaving this one open though to address the performance issues.

**Comment by adamdbradley** [comment]
This has been addressed in this refactor: https://github.com/driftyco/ionic/commit/91df5f97eef9ed1d261e6642c2d9ab7e8cc4063c

Thanks
