### ISSUE TITLE
docs: All next results in docs brings 404

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5551]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>On [ionic 2 docs](http://ionicframework.com/docs/v2/) search for **scroll** or **animate**.

Click on any result. 404.</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Thanks for the issue, I'm going to move this to ionic-site.

**Comment by tlancina** [comment]
This issue was moved to driftyco/ionic-site#457
