### ISSUE TITLE
V2 - item-right nested in ion-list-header renders poorly

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5561]
#### Short description of the problem:

When I have an ion-list with a header, if I want to add a button to the right side of the screen using item-right, it doesn't work as expected.

#### What behavior are you expecting?

I would like it to position the item on the the right the same as ion-item item-right positioning does

```
<ion item>
   <ion-item-group *ngFor="myItem of items">
      <ion-list-header>
           {{myItem.title}}
           <button item-right clear primary
	        <ion-icon class="item-right-larger-button" name="checkmark-circle"></ion-icon>
	   </button>
      </ion-list-header>
      <ion-item>blah blah blah</ion-item>
    <ion-item-group>
</ion-item>
```

**Ionic Version**: 1.x / 2.x

2.x

**Browser & Operating System**: iOS / Android / Chrome

Chrome, iOS, Android

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by danbucholtz** [comment]
UPDATE:

Okay, this may not be an accurate bug...

I have noticed the following in trying to fix the bug...

```
<ion item>
   <ion-item-group *ngFor="myItem of items">
      <ion-item class="neutral-background">
           {{myItem.title}}
           <button item-right clear primary

               <ion-icon class="item-right-larger-button" name="checkmark-circle"></ion-icon>
          </button>
      </ion-item>
    <ion-item-group>
</ion-item>
```

Renders fine...

Once I add on an *ngIf="myBoolean" onto the button element, it renders incorrectly.

```
<ion item>
   <ion-item-group *ngFor="myItem of items">
      <ion-item class="neutral-background">
           {{myItem.title}}
           <button item-right clear primary *ngIf="myBoolean" (click)="bang()"
               <ion-icon class="item-right-larger-button" name="checkmark-circle"></ion-icon>
          </button>
      </ion-item>
    <ion-item-group>
</ion-item>
```

**Comment by danbucholtz** [comment]
Sorry 'bout the spam.  Fundamentally - these are two separate issues.  I was able to remedy the issue in the second post by moving from *ngIf to binding to style.display none when the boolean is false.  Worked great and rendered correctly!

However - the issue remains with rendering icons on the right side of an item-list-header.  I think this is a very common use case.  For example, I have a group of photos (moments), and I want to select all photos within the moment via an icon button click.  I believe Apple Photos and Google Photos both use this convention.

**Comment by brandyscarney** [comment]
I'm confused. Does this issue only occur when the `*ngIf` is on the button?

**Comment by danbucholtz** [comment]
No.  That is an unrelated issue.

```
<ion item>
   <ion-item-group *ngFor="myItem of items">
      <ion-list-header>
           {{myItem.title}}
           <button item-right clear primary
            <ion-icon class="item-right-larger-button" name="checkmark-circle"></ion-icon>
       </button>
      </ion-list-header>
      <ion-item>blah blah blah</ion-item>
    <ion-item-group>
</ion-item>
```

Does not render correctly.  I can't put an item in the header and have it render on the right side like it does for:

```
<ion-item>
    <button item-right>
        <ion-item name="add"></ion-item>
    </button>
</ion-item>

**Comment by keithdmoore** [comment]
+1 I think this is a fairly common usecase.  For example, you have an item divider where you want to place an "add" or "add-circle" icon.

**Comment by brandyscarney** [comment]
This has been added and will be possible with `beta 10`. For example:

```
<ion-item-divider>
  Item Divider
  <button item-right>button</button>
</ion-item-divider>

<ion-item-divider dark>
  <button item-left clear>
    <ion-icon name="cloudy"></ion-icon>
  </button>
  <button item-left clear light>
    <ion-icon name="rainy"></ion-icon>
  </button>
  Dark
</ion-item-divider>

<ion-list-header>
  <button item-left (click)="testClick($event)">Default</button>
  Inner Buttons
  <button outline item-right (click)="testClick($event)">Outline</button>
</ion-list-header>

<ion-list-header disabled>
  <button item-left (click)="testClick($event)">
    <ion-icon name="home"></ion-icon>
    Left Icon
  </button>
  disabled left icon buttons
  <button outline item-right (click)="testClick($event)">
    <ion-icon name="star"></ion-icon>
    Left Icon
  </button>
</ion-list-header>
```

Thanks!
