### ISSUE TITLE
V2 util getQueryString throws error on urls with empty query param

### ISSUE THREAD

**Issue by ciekawy** [driftyco/ionic#5562]
#### Short description of the problem:
it may happen to load the application with url containing empty query param i.e.
`http://localhost:8100/#?&someParam=someVal`

url shouldn't be formed like that but still the application should be fault tolerant in such cases

#### What behavior are you expecting?
ignore empty parameters is enough

**Steps to reproduce:**
1. load the app with some empty param like `http://localhost:8100/#?&someParam=someVal` 

```
Uncaught TypeError: Cannot read property 'split' of undefined
(anonymous function) @ app.bundle.js:27235
forEach @ app.bundle.js:66
getQuerystring @ app.bundle.js:27233
Platform.setUrl @ app.bundle.js:26693
ionicProviders @ app.bundle.js:3309
(anonymous function) @ app.bundle.js:60042
DecorateConstructor @ app.bundle.js:610
// ...
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by adamdbradley** [comment]
merged, thanks!
