### ISSUE TITLE
back button navigation

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#5564]
#### Short description of the problem:
Is there any chance to remove the functionality so there wont be a back button when i push pages to the stack ? OR if there isnt, is there any way how to change the name "Back" and translate it. Also is there anyhow to listen for events when someone click back button (I should listen to the NavController) so I can have custom handler that will do something ?

Thanks
**Ionic Version**: 2

**Comment by mhartington** [comment]
To remove/hide the back button when pushing a new page, you can add the property `hideBackButton="true"` to the ion-navbar. Just added the docs for this via https://github.com/driftyco/ionic/commit/d0a3872628c0c6bdb2a68c7fb56156b5a68b06fa


As for translation/changing the back button text, this can be done via the Config class.

```ts
export class MyPage {
  text = "HELLOOOO"
  constructor(
    config: Config) {
    config.set('backButtonText', this.text)
  }
}
```

The backButtonText could be set to a string, or be a method that returns a sting.

**Comment by mhartington** [comment]
So I'm going to close this for now. This is something more suited for the forum, as it could generate more of a discussion there. Cheers!

**Comment by JoeMeeks** [comment]
Ionic 2 & 3:
`<ion-navbar [hideBackButton]="true">`
