### ISSUE TITLE
ionic2 refresh api

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic#5567]
#### Short description of the problem:

refresh pull does not work on the api page http://ionicframework.com/docs/v2/api/components/scroll/Refresher/

#### What behavior are you expecting?

to show refresh icon and effect that user is pulling down... right now it stays with items, does not have pull effect.

**Steps to reproduce:**
1. pull down with click and drag

**Comment by adamdbradley** [comment]
This has been fixed in https://github.com/driftyco/ionic/commit/91df5f97eef9ed1d261e6642c2d9ab7e8cc4063c

Thanks
