### ISSUE TITLE
Ionic2 custom navbar on single page sticks to other pages (for tab pages only)

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#5568]
#### Short description of the problem:
Defining custom navbar with `*navbar` on a single page will make this custom navbar stick out from the standard navbar on other pages. (related to Tab Pages only).

#### What behavior are you expecting?
Custom navbar on a single page should only be present on that page and not affect the other tab pages.

**Steps to reproduce:**
1. Start ionic2 tabs starter project `ionic start TabsTest tabs --v2`
2. Edit /project/root/app/pages/page1/page1.html and replace
```
<ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>
```
with
```
<div *navbar style="width:100%;height:100px;background-color:yellowgreen"></div>
```
3. Start ionic app with `ionic serve` and note that the first tab has our custom header as expected.
Screenshot: https://www.evernote.com/l/AlooChyY8ipIU5Bk70rdo5i9kX1lc1VO0BY
4. Click on tab2 and note that our custom header is sticking out from behind the standard header.
Screenshot: https://www.evernote.com/l/AloHq4Vqb_lBdrCvw9AXHcsIeWliK0EGRfo

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by jgw96** [comment]
Hello @Yagger ! Thanks for opening an issue with us! This has been fixed in the latest nightly which you can install with `npm install ionic-angular@nightly`. We overhauled layout a little so here is how you can do custom navbars now
```
<ion-header>
  <ion-toolbar style="height: 1000px">
    Super awesome really huge navbar
  </ion-toolbar>
</ion-header>
```
As you can see you use `ion-toolbar`'s for custom navbars now. Thanks for using Ionic!

**Comment by Yagger** [comment]
@jgw96, thanks for update! I confirm it works. So, the difference between the Navbar and the Toolbar is that Toolbar can be used as a subheader. It can also be used as the only header, to build custom navbar. The `*navbar` syntax is no more. Is it all correct?

Also, if I want to change the background of the toolbar, the good way to do it is to add CSS to `ion-navbar>.toolbar-background`?

**Comment by jgw96** [comment]
@Yagger yep that is all correct! Glad it works for you now!
