### ISSUE TITLE
feat: Synchronous API LocalStorge

### ISSUE THREAD

**Issue by stefanhuber** [driftyco/ionic#5569]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently the API of LocalStorage returns Promises, which is not really necessary, as the underling API (window.localStorage) not an async API is!

For a developer working with promises is somewhat cumbersome and code gets very fast totally unreadable. So according to my understanding transforming a synchronous API into an asynchrous API is a step in the wrong direction. 

For my current development i rather use the direct window.localStorage API as it feels more natural.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
To stay consistent with each storage type, such as websql, indexeddb and sqllite, we'd like to keep the API surface the same.

**Comment by alfabetagama** [comment]
Underlying storage is synchronous. In this case consistency adds complexity which is not really necessary. What is the point of having API that is consistent but not really usable?

**Comment by kashban** [comment]
I agree with @alfabetagama : Using the localstorage API is extremely cumbersome with promises when those are not required at all by the functionality this API represents.
