### ISSUE TITLE
$ionicLoading template has .loading css but cannot be overridden from template

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#5570]
I want to change the .loading per template, however it wraps the loader template in the .loading class div. Why is that any good? I can change the .loading class globally and cannot overrid per .show().

**Comment by jgw96** [comment]
Thanks for submitting this issue! Would you be able to give us a code sample so that we can repro the issue? Also this seems to be for ionic v1 am i correct?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
