### ISSUE TITLE
bug: Ios using pipes breaks app

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5572]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>The error only happens when in device or xcode emulator, in browser works OK.

I'm using the `number` pipe of angular 2, it works like a charm in Android but in ios it breaks the app and i need to close the app and open it again (not minimizing, full close) to be able to use it again.

I'm using the emulator for iPhone 6s plus/ ios 9.2 (13c75)

Here's some html:
```html
<ion-row class="metrics">
    <ion-col *ngIf="statistic == 'now'">
      <div class="blue">{{ metaRuta | number:'1.0-2' }}</div>
      <div>Meta ruta</div>
    </ion-col>
</ion-row>
```
Here's the typescript that follows:
```ts
@Page({
  templateUrl: 'build/pages/statistics/statistics.html'
})
export class StatisticsPage {
  public statistic     : string = 'now'
  public metaRuta  : number = 0
}
```
Ionic info output:
```sh
$ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```
</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
**Update 1:** Removed all the ` | number:'1.0-2'` pipes from html and all working again, does ios hate the angular 2 numeric pipe? :stuck_out_tongue_winking_eye:  is it because of crosswalk?

**Comment by adamdbradley** [comment]
Not sure, have you found any issues for this on the angular2 repo?

**Comment by Luchillo** [comment]
Not even tried to find, as in browser and android works as expected but it breaks just in IOS, funny thing is i just put IOS as platform but ionitron put a label for android.

**Comment by cyprusglobe** [comment]
might have a look at this

http://stackoverflow.com/a/35018352

**Comment by Luchillo** [comment]
Seems it is that issue, how would you add it to a project? adding it to the entry in `webpack.config.js` just like `es6-shim`?

**Comment by Luchillo** [comment]
@cyprusglobe @adamdbradley I'm still trying to figure out how to include the ìntl` polyfill in the webpack bundling process, how should it be done?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by Luchillo** [comment]
@jgw96 Not quite, i think this should be addressed as a compatibility issue and have a corresponding doc about how to include the polyfill, i did it already, if you want i can help for that docs in case of webpack.
