### ISSUE TITLE
iFrame do not load on windows 10

### ISSUE THREAD

**Issue by renato04** [driftyco/ionic#5574]
Hello,

I'm trying to use an iframe like this:

``` html
<ion-view view-title="Titile">
    <ion-content class="">
    	<iframe class="iframe-content" name="eventsPage" src="http://mypage.com" frameborder="0">
    	</iframe>
    </ion-content>
</ion-view>
``` 
In this page i have a form to submit information to another site.
The iFrame does not show on windows 10 apps (desktop/mobile), but in browser and android it shows.

**Ionic Version**: 1.7.4

**Browser & Operating System**:Windows

Thank you in advance.

**Comment by jgw96** [comment]
Thanks for submitting this issue! Are you still experiencing this issue?

**Comment by renato04** [comment]
@jgw96 yes, i'm still experiencing this issue.

**Comment by jgw96** [comment]
@renato04 Are you getting any console errors?

**Comment by renato04** [comment]
@jgw96 I can't tell you that, because the iframe works well in browser (chrome/edge), And when i deploy to my windows 10 devices (mobile and pc) it doesn't load the page.

**Comment by jgw96** [comment]
Hello! Although i would love to solve this issue for you we are not currently supporting windows 10 in Ionic 1, although we fully support it in Ionic 2. I would suggest asking around on our forums (forum.ionicframework.com) for help with this issue. Thanks for using Ionic!
