### ISSUE TITLE
Button border colors hard coded transparent

### ISSUE THREAD

**Issue by joeljameswatson** [driftyco/ionic#5576]
In Ionic 1.2.0 the button border styles appear to be hardcoded to transparent through a mixin. This seems to make creating custom styles more difficult and less maintainable. I suggest this could be set as a variable.

Please see this commit:

https://github.com/driftyco/ionic/commit/21e54be

**Comment by asanin-2sol** [comment]
+1 I just updated ionic to 1.2.1 and all the borders disappeared.

Is this a feature or a bug?

**Comment by jgw96** [comment]
@asanin-2sol Would you mind making a codepen or giving us a code example so that we can repro this issue? Thanks!

**Comment by asanin-2sol** [comment]
@jgw96 My main problem is with button bars, having no borders makes the following example look like a single button with three labels rather than three buttons in a bar.

```
<div class="button-bar">
  <a class="button">First</a>
  <a class="button">Second</a>
  <a class="button">Third</a>
</div>
```

Also, the way this looks does not correspond to the way button bars look in the documentation, where the borders are not transparent.

Hope this helps.

**Comment by danbucholtz** [comment]
Hi @gness and @joeljameswatson,

I have updated the sass.  Please take a look and let me know if any changes are required and if this works for you.  In the mean time I am going to close this issue.  Thanks for contributing and letting us know.

Thanks,
Dan

**Comment by andischerer** [comment]
Hi @danbucholtz,

i have left a comment on your commit. Currently there is no chance to set a user defined value to the introduced scss variables `$button-default-border` and `$button-default-active-border`.

**Comment by danbucholtz** [comment]
Hi @andischerer,

Can you do a PR with the changes you'd like to see.  I'll happily work with you to get it merged.  Please let me know.

Thanks!
Dan

**Comment by andischerer** [comment]
@danbucholtz here you are

**Comment by danbucholtz** [comment]
Nice!  I'll test and merge.  In the off chance I forget, just bug me about it again.  Thanks for doing this!

Thanks,
Dan

**Comment by Romeno** [comment]
@danbucholtz This issue seems to be resolved but `$button-default-border` and `$button-default-active-border` is still hard-coded
