### ISSUE TITLE
bug: Mouse-based gestures calculated incorrectly

### ISSUE THREAD

**Issue by calvinps** [driftyco/ionic#5578]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Drag directions are not correctly determined for mouse events on desktops. When swiping/dragging with a mouse, every "direction" of the gesture is registered as "down." The issue this causes is that, probably among other things, you can't swipe an ion-item on desktop to reveal the ion-option-button(s).

I have found the source of the issue and implemented a fix: the function "getCenter" can receive two different types of objects depending on if the source of the event was touch click event. The "pageX,pageY" properties don't exist on both. I switched to "screenX,screenY" which exist in both types of "touches" objects. 

With this change swiping works correctly when triggered by a mouse. 

Here's the new getCenter function I implemented:

    getCenter: function getCenter(touches) {
      var valuesX = [], valuesY = [];

      for(var t = 0, len = touches.length; t < len; t++) {
        valuesX.push(touches[t].screenX);
        valuesY.push(touches[t].screenY);
      }

      return {
        pageX: ((Math.min.apply(Math, valuesX) + Math.max.apply(Math, valuesX)) / 2),
          pageY: ((Math.min.apply(Math, valuesY) + Math.max.apply(Math, valuesY)) / 2)
      };
    },

<span is-issue-template></span>

**Comment by calvinps** [comment]
Ionic version 1.2.4 I should mention as well

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
