### ISSUE TITLE
tsc semantic errors in animations/animation.d.ts

### ISSUE THREAD

**Issue by lathonez** [driftyco/ionic#5581]
#### Short description of the problem:

tsc semantic errors in animations/animation.d.ts. Similar to https://github.com/driftyco/ionic/issues/5042

#### What behavior are you expecting?

no semantic errors in animations/animation.d.ts

**Steps to reproduce:**
1. `ionic start semanticErrors --ts --v2`
2. `cd semanticErrors`
3. `tsc --module commonjs app/app.ts | grep animation`

```
node_modules/ionic-framework/animations/animation.d.ts(48,51): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
node_modules/ionic-framework/animations/animation.d.ts(54,51): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
```

There are bunch of other errors in there which are resolved by `tsd install es6-shim`

**Ionic Version**: 2.0.0-beta.17

**Browser & Operating System**: ubuntu 14.04

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.6.0
```

**Comment by tlancina** [comment]
Thanks for the issue! This was fixed in https://github.com/driftyco/ionic/commit/be95ac6490a378c585655b3c76d8d432d8115f79.  I'll leave it open until the next release.

Also you should be able to just run `tsc` and the `tsconfig.json` file will find the typings and add the flags for decorators and stuff like that.

**Comment by lathonez** [comment]
Thanks Tim.

**Comment by tlancina** [comment]
Beta 2 is out so they should be gone now, let us know if you're still having issues, thanks!

**Comment by lathonez** [comment]
@tlancina - confirmed they've gone, thanks a lot.
