### ISSUE TITLE
V2 - Feature - Toast Component w/o Ionic Native

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5582]
#### Short description of the problem:

I'd like to see a built-in toast component similar to the alerts.  It would be great to have this as a core component so we can use it without Cordova.

#### What behavior are you expecting?

Show a nice looking modal that fades out after a given time-out

**Ionic Version**: 1.x / 2.x

2.x

**Browser & Operating System**: iOS / Android / Chrome

All

**Comment by jgw96** [comment]
+1 for this feature

**Comment by Luchillo** [comment]
It indeed would be great to be native, but right now you can just install the cordova toast plugin so this most likely will be made far later in the roadmap, if it ever make it to the roadmap.

**Comment by danbucholtz** [comment]
Totally agree @Luchillo.  That's what I'm doing now.  However - if the mobile web is to be a first-class cititzen, having an OOTB component would be a big win.  I also think the effort would not be significant given how similar a toast is to the Loader and/or Alert components.  Loader is coming soon.

**Comment by brandyscarney** [comment]
Added to the roadmap, thanks!

**Comment by jgw96** [comment]
@brandyscarney I would love to take up work on this feature!

**Comment by dmackerman** [comment]
Curious, are there specs for what this should look like? I'd imagine for Android, it'd mimic the Toast spec for Material Design, but iOS has no such spec.

**Comment by brandyscarney** [comment]
@dmackerman We are going to follow the Material Design spec for Android, the iOS version will look similar to the Android version and we will just tweak it as necessary. :smile:

**Comment by dmackerman** [comment]
@brandyscarney sounds good. Is there active work being done on this, or should I take a crack at it?

**Comment by brandyscarney** [comment]
@dmackerman We won't be working on this until beta.10 (unless it gets moved up) so if you'd like to work on it that would be great! It should just match the action sheet animation for now and then we can tweak that if we need to. If you'd like to look into it you can ping me for any questions. I'm thinking the directory can just be called "toast" cc @adamdbradley

**Comment by dmackerman** [comment]
Awesome. I'll take a look at extending `ActionSheet` and see how far that gets me. Looping in @carlospaelinck for collaboration purposes. :smile:

**Comment by dmackerman** [comment]
@danbucholtz @Luchillo: feel free to help out and give your feedback on this PR: https://github.com/driftyco/ionic/pull/5906

**Comment by brandyscarney** [comment]
A big thanks to @dmackerman for adding this component! This will be released in beta.6. :smile:

**Comment by danbucholtz** [comment]
@dmackerman, fantastic work!  We are all very excited that we landed a feature entirely from the community.  This is so awesome!  Thanks for contributing!
