### ISSUE TITLE
Date picker under input[type=date] doesn't show up for Chrome

### ISSUE THREAD

**Issue by niyando** [driftyco/ionic#5583]
#### Short description of the problem:

After upgrading to ionic 1.2, I changed my inputs as suggested under blog [Ionic 1.2](http://blog.ionic.io/announcing-ionic-1-2/)

```
<ion-input class="item item-input">
  <i class="icon ion-person"></i>
  <ion-label>Username</ion-label>
  <input type="text">
</ion-input>
```

But doing so blocks the default chrome date picker under input type=date from opening.
Check codepen http://codepen.io/niyando/pen/eJqjex

#### What behavior are you expecting?

It works if we use the `<label>` way of writing inputs.
Check codepen http://codepen.io/mhartington/pen/laeLn

**Steps to reproduce:**
Compare the codepens provided

**Ionic Version**: 1.2.4

**Browser & Operating System**: Chrome

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
