### ISSUE TITLE
searchbar on iphone6 could not fire the (input) event when  input chinese word

### ISSUE THREAD

**Issue by bibitoo** [driftyco/ionic#5584]
#### Short description of the problem:
Input a chinese word must type and pick  a word.
when type, the searchbar (input) event fire. but then pick a chinese word, the (input)   event does not emit.

#### What behavior are you expecting?
after  pick a chinese word,  the searchbar (input) event fire.

**Steps to reproduce:**
1. focus searchbar input field.
2. switch to chinese input keyboard.
3. type "li", the  (input) event fire every key up. Pick a chinese word "李",  the (input)    event dos not emit.

```
html:
<ion-searchbar [(ngModel)]="q" (input)="onSearch($event)" (cancel)="onCancelSearchbar($event)" (clear)="onClearSearchbar($event)"
 cancelButtonText='{{"common.cancel" | translate }}'></ion-searchbar>
js:
	onSearch(event){
		this.datas = [];
		this.pageNo=1;
		this.pagination();
	}
```

**Ionic Version**: 1.x / 2.x
2.0
**Browser & Operating System**: iOS / Android / Chrome
iOS

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.3.0

```

**Comment by brandyscarney** [comment]
Are you saying that when you click one of the Predictive Words it doesn't trigger the input? I am able to trigger the input by selecting a Chinese letter from the `Cangjie` and `Zhuyin` keyboards, but when the text is suggested and I click it I see that it doesn't trigger the input. Just want to make sure we're seeing the same issue!

![chinese-keyboard](https://cloud.githubusercontent.com/assets/6577830/13652568/de23511a-e61a-11e5-8c98-e0835af42012.png)

**Comment by bibitoo** [comment]
Yes, please help me out this problem

**Comment by brandyscarney** [comment]
So the issue was actually because the searchbar was triggering the input change on `keyup` and since the text suggestion wasn't a "keyup" it wasn't being called. This should be fixed in the next release, thanks for the issue!
