### ISSUE TITLE
refresher jump to bottom on iOS 9.2.1 iphone6

### ISSUE THREAD

**Issue by bibitoo** [driftyco/ionic#5585]
#### Short description of the problem:
After add refresher to ionic-conference-app shecule.html, The Schedule list could pull down. 
Then I release, the page scroll to bottom. 

#### What behavior are you expecting?
The page back to the top.

**Steps to reproduce:**
1. add refresher to  ionic-conference-app shecule.html
2. on ionic-conference-app's schedule list page, scroll to bottom
3. scroll to top, and pull down the page. The refresher icon should show.
4. Release the page, the page scroll to bottom.

```
<ion-content class="schedule">
 <ion-refresher (starting)="doStarting($event)"
                 (refresh)="doRefresh($event)"
                 (pulling)="doPulling($event)">
  </ion-refresher>

  <ion-searchbar primary
                 [(ngModel)]="queryText"
                 (input)="updateSchedule()"
                 placeholder="Search">
  </ion-searchbar>

```

**Ionic Version**: 1.x / 2.x
2.0
**Browser & Operating System**: iOS
 iOS

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.3.0

```

**Comment by brandyscarney** [comment]
Confirmed that this is no longer a problem with the recent fixes in #5207. Should be released in beta.2. Will add it as a task on that issue to check this again before release.
