### ISSUE TITLE
Ionic-starter-sidebar not found.

### ISSUE THREAD

**Issue by svenluijten** [driftyco/ionic#5587]
#### Short description of the problem:
When trying to create a new ionic application with the sidebar base (`ionic start <name> sidebar`) as described [here](http://ionicframework.com/getting-started/) I get an error that the package could not be found. It is looking for the `driftyco/ionic-starter-sidebar` repository on GitHub, but I believe it should be `driftyco/ionic2-starter-sidemenu`.

#### What behavior are you expecting?
I was expecting it to create a new project with the sidebar boilerplate, instead I got a 404 error. This could easily be fixed by changing the URL.

**Steps to reproduce:**
1. `npm install -g ionic cordova`
2. `ionic start <name> sidebar`

```
λ ionic start myApp sidebar
Creating Ionic app in folder F:\Code\Ionic\myApp based on sidebar project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-sidebar/archive/master.zip
 ✗ Not found: https://github.com/driftyco/ionic-starter-sidebar/archive/master.zip (404)
 ✗ Please verify the url and try again.
Please verify you are using a valid URL or a valid ionic starter.
View available starter templates: `ionic templates`
More info available at:
http://ionicframework.com/getting-started/
https://github.com/driftyco/ionic-cli
```

**Ionic Version**: 1.7.14

**Browser & Operating System**: Windows 10

**Run `ionic info` from terminal/cmd prompt:**

```
λ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v5.7.0
```

**Comment by svenluijten** [comment]
Wow nevermind, I completely read the documentation wrong.

**Comment by asimzaidi23** [comment]
I'm getting the same error, mind telling me how your resolved it @svenluijten ?

**Comment by svenluijten** [comment]
It's `sidemenu`, not `sidebar` @asimzaidi23 :smiley:
