### ISSUE TITLE
feat: Clean up HTML files in www build folder

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#5588]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Steps to reproduce:
1) Start a new project using the default ionic2 starter
2) Remove e.g. page 2
3) Build the project
=> The www folder still contains the HTML file for page 2</span>

<span is-issue-template></span>

**Comment by tlancina** [comment]
Hey thanks for the issue, I'm going to move this over to the ionic-cli repo

**Comment by tlancina** [comment]
This issue was moved to driftyco/ionic-cli#794
