### ISSUE TITLE
Single tap fires twice in the same location

### ISSUE THREAD

**Issue by heshiming** [driftyco/ionic#559]
I'm getting two taps on the same location for a single tap, on the nav-bar. This happens on my iOS 6 & 7 device, and emulator. It happens in Mobile Safari, as well as UIWebView contained by cordova. I've tested this on commit 7f9bfb5a9499537f5aa18291b7c2043da2aced49 .

The code to reproduce this behavior is at http://codepen.io/anon/pen/mLrnb , however, visiting this codepen page in Mobile Safari won't trigger the bug for some reason. You have to save it locally, and serve via `http-server -p 8000` .

The behavior is: When you tap the icon at top right to activate the side menu, the menu will open, but the tap is fired again on the side menu, causing another navigation (to the new page in red background). It happens not 100% of the time, but likely more than 90%.

At this point, if you click the side menu icon again to deactivate it, you can see the side menu closing up, but then another tap hit the 'back' button, which triggered another navigation back to the index page.

The two taps are fired at the same coordinate of the viewport, not the same element, leading me to think this is not a problem of my code.

**Comment by keyban** [comment]
i am getting this problem again with the following stack:

Info:
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.2 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002
