### ISSUE TITLE
ionic input type number accept the  character "e"

### ISSUE THREAD

**Issue by ChawkiOS** [driftyco/ionic#5590]
#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```

**Comment by adamdbradley** [comment]
Sorry but this comes from HTML5 and not Ionic: http://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in
