### ISSUE TITLE
bug: ion-input type date breaks user experience

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5592]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>`ion-input` type `date` creates a div with class `input-cover` that covers the input and reduces height on tap, thus enforcing the user to do double tap, users expect to open the date picker with one tap and will think it's broken.

To reproduce just paste this in the sidemenu starter html and emulate or deploy to device:
```html
<ion-list>
    <ion-item>
      <ion-label>Fecha de entrega</ion-label>
      <ion-input type="date" required></ion-input>
    </ion-item>
  </ion-list>
```

Image that shows what's happening:
![image](https://cloud.githubusercontent.com/assets/9698639/13293683/aef7fd28-daee-11e5-9623-684d9c3a64ae.png)

</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
**Update 1:** This bug is present in Android platforms be it emulated or device, not in IOS nor Web Browser, that div is present in browser emulating device like `Google nexus 7` but it doesn't require double tap, thus not interfering with user selecting Date input.

**Comment by adamdbradley** [comment]
That div is there by design, and is what's used to keep control of the keyboard focus without having the entire webapp scroll up. I think what I need to do is add the `tappable` attribute to that div so the click even fires faster.

**Comment by adamdbradley** [comment]
This should help: https://github.com/driftyco/ionic/commit/b814314b314edc5ccae89edc2a6666cdd71cdb09

**Comment by Luchillo** [comment]
Any idea when will it be included in the npm package?

**Comment by RunningV** [comment]
how to set required to ion-input? i add 'required' on <ion-input> tap it dosen't work
