### ISSUE TITLE
bug: Ion-select transparent when in android

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5594]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>The ion-select element doesn't work properly in android device, it opens the alert but for some reason the `alert-wrapper` opacity is 0.1 and is an inline style which could come from an animation, but why only in Android but in IOS and web works?:
![image](https://cloud.githubusercontent.com/assets/9698639/13300240/2bc7218a-db0d-11e5-8fb0-ca9bed30f2aa.png)

</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
**Update 1:** Seems to happen to me when using options setted with `*ngFor`, it still works ok with static options set in the html.

**Comment by Luchillo** [comment]
**Update 2: ** Setting the array from constructor works ok:
```js
public references: any[] = [{
    m_product_id: 101663,
    name: "ARROZ ALCARABAN 450 GR-BONIFI",
    packing_und: 25,
    price: 100,
    quantity: 10,
    total: 1000,
    value: "1103325",
    weight: 0.45
  }]
constructor(...){}
 ```

**Comment by Luchillo** [comment]
**Update 3:** Nailed it, i tough it was because i was setting the thing from a Promise, but seems to work with little amount of items, when i scale up the number of items in the `ion-select` it breaks, after testing the limit of this kind of object is around 20 and i have 240 items.

However since it works in IOS and web with the 240 items, i think it's related to the performance of the device, will i have to use the default html select with that many items?.

**Comment by brandyscarney** [comment]
Honestly I would look into ways of getting that number smaller. Just my personal opinion, but people usually don't want to scroll through 240 items to fill out a form. If they accidentally selected the wrong one/changed their mind they would have to scroll through them all again. Is there a way you could filter the select, or maybe make a filterable list that comes up in a modal?

**Comment by Luchillo** [comment]
I think i will have to create a custom popup with a search bar for filtering, it is in our roadmap but wasn't a priority, guess now it's the time, like it or not.

**Comment by Luchillo** [comment]
**Update 4:** Made the popup by hand and the error still happened to me, i'll try with modal instead, here's the custom alert:
```js
let radioAlert = Alert.create({
      title: 'Producto',
      message: "<ion-searchbar [(ngModel)]='searchQuery' placeholder='Buscar'></ion-searchbar>",
      inputs: this.radioInputs,
      buttons: [{
        text: 'Cancelar'
      },
      {
        text: 'Ok',
        handler: ((data) => {
          console.log('Checkbox data: ', data)
          this.product.ref = data
        })
      }]
    })
    setTimeout(() => {
      this.nav.present(radioAlert)
    }, 5)
```
Note that `this.radioInputs` is an array.

**Comment by Luchillo** [comment]
@brandyscarney Confirmed, all the Alert inputs suffer this kind of issue when in low performance devices, tested with **Android 5.1 Device** and Alerts works fine, tested with same **Android 5.1 Emulator** and this issue raises, making it imposible to test min android version from within an Emulator.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by Luchillo** [comment]
I'm unable to test since i changed how i managed the opening of the Alerts with the hook `onPageDidEnter`, that's the current solution, just start running the logic inside that hook instead of the constructoraa.

**Comment by jgw96** [comment]
@Luchillo Awesome, that is where you want to do anything ui related such as ion-select etc. Thanks for getting back to me!
