### ISSUE TITLE
Add list reorder & delete

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5595]
Similar to v1

http://ionicframework.com/docs/api/directive/ionDeleteButton/
http://ionicframework.com/docs/api/directive/ionReorderButton/

**Comment by djangojack** [comment]
during the reorder-drag, is it possible to make the original item hidden and show the other items moving apart like most native apps?

**Comment by lefnire** [comment]
Is list reordering in general not yet supported in Ionic2, or is this ticket for something more nuanced around the buttons? Sorry the question, having trouble Googling around this topic.

**Comment by djangojack** [comment]
@lefnire not yet supported.

**Comment by lefnire** [comment]
For anyone looking for an interim reorder solution, Dragula performs pretty well on mobile. [Sample commit](https://github.com/lefnire/acurn/commit/7f555dc9a857543312a73cf1f4a1abe96726e895). 'Course I'll switch right over to Ionic2's solution when available, but this works presently.

**Comment by manucorporat** [comment]
We have to support reordering without handles, feature suggested by @2arcz6.

**Comment by manucorporat** [comment]
@brandyscarney @adamdbradley I think it makes sense to have this feature only available inside a virtual list. It already provides the foundational level to know the positions of each item.

**Comment by manucorporat** [comment]
@lefnire @djangojack @2arcz6 check out the progress here:
https://github.com/driftyco/ionic/pull/6937

**Comment by sarahhostyk** [comment]
Hi, is there an estimated date that this will be released to Ionic Beta? Looking to add something like this to my project now, so knowing an eta would be much appreciated. Thanks!

**Comment by brandyscarney** [comment]
Hey @sarahhostyk, reorder has been added and will be available with the `beta 10` release (coming up soon). @manucorporat will be working on the list delete next. We're hoping to get list delete into the `beta 11` release but he will let us know if that changes. Thanks!

**Comment by sarahhostyk** [comment]
hey thanks @brandyscarney! Would you by chance have an approx. date for the beta 10 release? It will just help me plan out parts of my project better knowing an exact projected date. Thanks again!

**Comment by brandyscarney** [comment]
Hey @sarahhostyk, I plan on releasing beta 10 today as long as our testing goes well. :)

**Comment by sarahhostyk** [comment]
Awesome, thanks @brandyscarney!

**Comment by sarahhostyk** [comment]
hey @brandyscarney this is off topic but I'm trying to get autocomplete with google places API to work in ionic 2. It is working on ionic serve but not on an iphone or android phones. Is this something that might be supported in the upcoming beta 10 as well or another upcoming release?

**Comment by sarahhostyk** [comment]
hey @brandyscarney this is off topic but I'm trying to get autocomplete with google places API to work in ionic 2. It is working on ionic serve but not on an iphone or android phones. Is this something that might be supported in the upcoming beta 10 as well or another upcoming release? Thanks!

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by pimol** [comment]
Hi all.
Is reorder in the current RC? I can't find any docs about it!

Thanks!
