### ISSUE TITLE
Cannot find name 'require'. after upgrading to beta.1

### ISSUE THREAD

**Issue by 5amfung** [driftyco/ionic#5599]
#### Short description of the problem:
As suggested by the CHANGELOG, 

    angular 2.0.0-beta.6: if you are using typescript, update the following: https://github.com/driftyco/ionic-conference-app/commit/26f3393fe4be78468e1c51e0bbf5d05a2666cd20

I added the files to my ```2.0.0-beta.0``` project and updated ionic framework to beta 1 and angular2 to beta 6.  Then running ```ionic serve```, I got a few errors of the following.  ```require()``` works before the upgrade though.

    Cannot find name 'require'.

#### What behavior are you expecting?

Without the error above

package.json
```
{
  "name": "oeu-mobile-app",
  "description": "oeu-mobile-app: An Ionic project",
  "dependencies": {
    "angular2": "2.0.0-beta.6",
    "es6-promise": "3.0.2",
    "es6-shim": "0.33.13",
    "ionic-framework": "2.0.0-beta.1",
    "ionicons": "3.0.0-alpha.3",
    "lodash": "^3.10.1",
    "pouchdb": "^5.2.1",
    "pouchdb-find": "^0.9.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.14"
  },
  "devDependencies": {
    "awesome-typescript-loader": "0.15.10",
    "strip-sourcemap-loader": "0.0.1",
    "typescript": "1.7.5"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-transport-security"
  ],
  "cordovaPlatforms": [
    "ios"
  ]
}
```

**Ionic Version**: 2.0 beta 1

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
$ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by 5amfung** [comment]
Beside ```require()``` is no longer available, a freshly created new project has the following error as well.

```
ERROR in [default] /Users/foo/dev/testtesttest/node_modules/ionic-framework/animations/animation.d.ts:48:50 
A 'this' type is available only in a non-static member of a class or interface.

ERROR in [default] /Users/foo/dev/testtesttest/node_modules/ionic-framework/animations/animation.d.ts:54:50 
A 'this' type is available only in a non-static member of a class or interface.

```

**Comment by lordgreg** [comment]
@5amfung what are you trying to require?

`import` can be used in the same way:
```
import * as hellojs from 'hellojs;
import 'hellojs';
```

will both do the same thing.

As for your 2nd comment, those two errors are known and will be fixed in the next release.

:+1:

**Comment by 5amfung** [comment]
@lordgreg I was trying to...

```
var _ = require('lodash');
```

**Comment by lordgreg** [comment]
@mhartington from Ionic team wrote a nice article about the exact same library that you also want to use :)

Check it out [here](http://mhartington.io/post/ionic2-external-libraries/)

**Comment by 5amfung** [comment]
Thanks @lordgreg I found that article and then got stuck on known issue you mentioned.  For now, I'll fall back on beta 0 until the know issue is fixed.

```
ERROR in [default] /Users/foo/dev/testtesttest/node_modules/ionic-framework/animations/animation.d.ts:48:50 
A 'this' type is available only in a non-static member of a class or interface.
```

**Comment by lordgreg** [comment]
That is because they've removed the animations from framework. Read
changelog and do an update!

**Comment by brandyscarney** [comment]
The errors with animation will be fixed in the next release (beta.2), they shouldn't be breaking anything. Thanks for the issue!
