### ISSUE TITLE
v2 app doesn't work in Safari - es6-shim

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5601]
#### Short description of the problem:

General development (Mac) is on Chrome. However decided to run in Safari because the colours are sometimes different etc.....  while this generally works, on a certain view/page it fails 

Console Log has this error just before it fails

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (es6-shim.map, line 0)

Cannot GET /build/js/es6-shim.map

#### What behavior are you expecting?

Would like to be able to, in development, use Safari occasionally

**Steps to reproduce:**
1. Open an app in Safari 
2.
3. 

I haven't yet investigated which component on the page is causing this but can do if that would help. 

**Ionic Version**: 1.x / 2.x

2

**Browser & Operating System**: iOS / Android / Chrome

Mac
Safari 9.01 

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by tlancina** [comment]
So that error is just Safari failing to find the es6-shim sourcemap, it shouldn't break anything.  If your app isn't loading then it's caused by something else.

**Comment by alexbainbridge** [comment]
OK leave this open, I will work out what the problem is, and close if this isn't it

Probably something else in that case, but works 100% in Chrome :)    and in Safari the app stops, with this console error just before, hence why I thought it was causing it somehow.

**Comment by alexbainbridge** [comment]
OK turns out to be a known issue in Angular 2..... (Angular 3333 - some pipes don't work in Safari) 

Closing this as I can see #754 is open, and is probably a duplicate of my original problem

**Comment by alexbainbridge** [comment]
Another solution.... https://github.com/driftyco/ionic/issues/5710#issuecomment-192448377
