### ISSUE TITLE
feat: Reference demo: Tabs with individual sidemenus

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#5602]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I've seen and read this requirement so often (in the forum, too):
A reference implementation using a tabbed interface where every tab has its own sidemenu.
It's like a combination out of the ionic-starter-tabs and ionic-starter-sidemenu.
Perhaps you can consider creating a v2 reference ionic-starter-tabs-sidemenu app.
Would be really great for a lot of folks!</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic2-app-base#13
