### ISSUE TITLE
specific url pattern of tab cause strange behavior

### ISSUE THREAD

**Issue by zcfan** [driftyco/ionic#5606]
# reproduce

To reproduce problem, just open this codepen "<a href='http://codepen.io/zcfan/pen/bpbRjY/'>a strange problem with tabs</a>" and keep changing tab.
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

# description

Url of two states is 'me' and 'message', as you can see 'me' is the same with the first two characters of 'message'.

Change it to 'm' or 'mes' or 'mess' didn't change anything. But change to a/b/meaa fix this problem.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately this seems like an issue with ui-router and not an actual ionic issue. Because of this am going to be closing this issue for now. Thanks for using Ionic!
