### ISSUE TITLE
ionic closing on startup

### ISSUE THREAD

**Issue by JessinR** [driftyco/ionic#5608]
#### Short description of the problem:
The app instantly closes when the app is launched, on the newest iOS. (9.2).

**Steps to reproduce:**
1. have the newest iOS
2. install the app, from xCode, not the app store.
3. launch it, and after some uses the app auto closes on launch

```
insert any relevant code between the above and below backticks
```

ionic version: 1.7.11
iOS,

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v0.12.7

**Comment by mhartington** [comment]
Hi there :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by jgw96** [comment]
Thanks for submitting this issue to us! Since it has been a little while since there was any activity on this bug i am currently closing it. But, if you are still experiencing this bug please feel free to reopen it! Thanks again!
