### ISSUE TITLE
Allow Text Selection

### ISSUE THREAD

**Issue by iamchairs** [driftyco/ionic#5612]
I have areas in my app where I want to be able to select text. Instead of preventing text selection for anything except for a text input there should be an option to define selectable text. Working on a pull request now.

**Comment by iamchairs** [comment]
Pull request here:

https://github.com/driftyco/ionic/pull/5613

**Comment by jgw96** [comment]
Thanks for submitting this issue! We just need a little more info from you to be able to fix this issue. Would you mind posting a codepen or code sample for us so that we could repro this issue? Also would you mind telling us if this issue is happening with Ionic 1 or Ionic 2?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by danielmhair** [comment]
I would love to have this ability. I need to have an ion-item or ion-content selectable. I then want to highlight the text once I have it selected. Is there any functionality with Ionic 2 that would be easy to do this?

**Comment by pmramos** [comment]
+1

**Comment by SoaringTiger** [comment]
+1

**Comment by adirzoari** [comment]
@SoaringTiger @pmramos @danielmhair anyone succeed to do that?i'm facing with same issue.

**Comment by nikkozzblu** [comment]
+1 as well, no luck so far

**Comment by senseijames** [comment]
This simple fix worked for in Ionic 3.9.2:

https://stackoverflow.com/a/46437066/189518
