### ISSUE TITLE
CLI Page Generator

### ISSUE THREAD

**Issue by ezequielprieto** [driftyco/ionic#5614]
Running

```ionic g page myPage ```

We get in myPage.js

```import {Page} from 'ionic/ionic'; ```

Instead of 

```import {Page} from 'ionic-framework/ionic'; ```

My ionic info is
```
Cordova CLI: 5.3.3
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by tlancina** [comment]
Should be fixed in the latest release! Just a note generators are using `ionic-angular` as we're switching package names.
