### ISSUE TITLE
fastclick on div

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#5616]
Is there any way to make a div responsive just like the normal buttons  

I made my custom div element which I want to make it clickable, and the performance is so bad now. Should we import fastclick.js by ourselves or is there any better solution already built-in in Ionic ? 

Ionic version: 2
Thanks

**Comment by emps** [comment]
did u try on-tap ?

**Comment by denkomanceski** [comment]
I am on Ionic 2 ? Does (tap) exist ?

**Comment by adamdbradley** [comment]
You can add the attribute `tappable` to the div
