### ISSUE TITLE
V2 - hide back button

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#5618]
#### Short description of the problem:
Tried the ionic 1.x hide-back-button directive, but this didn't work. Any way to hide the back button on 2.x?

```
<ion-navbar *navbar hide-back-button="true">
</ion-navbar>
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Comment by djangojack** [comment]
https://github.com/driftyco/ionic/issues/5564

**Comment by JoeMeeks** [comment]
Ionic 2 & 3:
`<ion-navbar [hideBackButton]="true">`
