### ISSUE TITLE
bug: ionicV2 tab to ion-select error

### ISSUE THREAD

**Issue by slippyC** [driftyco/ionic#5619]
#### Short description of the problem:
If in a regular chrome browser.  If you have input fields and tab between the different form inputs.  If the one being tabbed to is an `ion-select`, you will get an on focus error.  

This is probably not a high priority for ya, since I know ionic is more mobile oriented.  But this bug does exist and wanted to give ya a heads up.

**Ionic Version**:  2.0.0beta1

**Browser & Operating System**: Linux/Windows
Linux/Windows Chrome browser

**Comment by jgw96** [comment]
Thanks for submitting this issue! Would you mind making a codepen or giving us a code sample that we will be able to use to repro this issue? Also i would recommend updating the version of Ionic 2 you are using and see if that helps with your issue. Thanks again!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
