### ISSUE TITLE
listening to scroll event on v2?

### ISSUE THREAD

**Issue by mickael-kerjean** [driftyco/ionic#5623]
Hello, 

I wanted to create an effect where the navbar is transparent when a user is on top of the page and slowly add opacity in the menubar as the user scroll down. Can we have something around [here](https://github.com/driftyco/ionic/blob/2.0/ionic/components/scroll/scroll.ts), that will replace the on-scroll from ionic v1?

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
