### ISSUE TITLE
Add tabbarLayout config to tabs

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5625]
Should be able to use `tabbarLayout` to configure title and icons:
```
  config: {
    tabbarLayout: 'icon-bottom',
    platforms: {
      android: {
        tabbarLayout: 'icon-hide'
      }
    }
  } 
```

Adam and I came up with the following:

key: `tabbarLayout`
values: `icon-top`, `icon-left`, `icon-right`, `icon-bottom`, `icon-hide`, `title-hide`

**deprecate tabbarIcons**

**Comment by brandyscarney** [comment]
Adam and I came up with the following:

key: `tabbarLayout`
values: `icon-top`, `icon-left`, `icon-right`, `icon-bottom`, `icon-hide`, `title-hide`

**Comment by adamdbradley** [comment]
:+1:
