### ISSUE TITLE
[version 1.2.4] $ionicScrollDelegate not work on android 

### ISSUE THREAD

**Issue by njleonzhang** [driftyco/ionic#5629]
#### Short description of the problem:
$ionicScrollDelegate not work on android, it can work on 1.1.1

#### What behavior are you expecting?
I have a directive which can change the height a lot, in this situation,  $ionicScrollDelegate.resize() is needed. it can work with ios with ionic 1.1.1 and 1.2.4, but if I update ionic to 1.2.4. it can not work on android.

**Comment by njleonzhang** [comment]
version after 1.1.1, all can not work. will paste my code later

**Comment by jgw96** [comment]
Thanks for opening this issue! We just need a little more info from you so that we can help you better. If you could post a codepen or just a code sample that would be great! Also, if you could run `ionic info` and paste the contents here that would be great!

**Comment by njleonzhang** [comment]
Tnx for your attention, I will create codepen to repro this issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
