### ISSUE TITLE
docs: Ionic V2 Example error

### ISSUE THREAD

**Issue by kuntal-b** [driftyco/ionic#5630]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am using FF 43.0.1 some example like 
http://ionicframework.com/docs/v2/components/#alert
http://ionicframework.com/docs/v2/components/#select
not working .I found bellow java script error in Firebug console

TypeError: self.ele.animate is not a function.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
I can also confirm this error in Firefox 44. Looks like its related to the web animation api not being fully supported in firefox.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#470
