### ISSUE TITLE
docs: Sliding list link leads to wrong github example

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#5633]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
- go to [Components: Sliding list page](http://ionicframework.com/docs/v2/components/#sliding-list)

- click demo source

- You land on thumbnail list example. The correct url should be: `https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/lists/sliding/template.html`</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#471
