### ISSUE TITLE
feat: Page transition slide up

### ISSUE THREAD

**Issue by lastmjs** [driftyco/ionic#5634]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Forgive me if it's in the docs, but I've looked through the docs and source code a bit and haven't found anything. Right now it looks like the direction of a page transition can be specified when pushing, but the only value that can be specified is 'back'. I would like a page transition that slides in from the bottom to the top of the window. Are other transition directions in progress?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! We are currently duscussing having different page transitions and maybe allowing custom page transitions, but its still in discussion. In the meantime a workaround might be to use config and specify the md page transition, which fades up from the bottom and might fit what you want better (: Here is an example of how you do this:

`
@App({
  template: "<ion-nav [root]="root"></ion-nav>",
  config: {
    pageTransition: 'md'
  }
})
`
Hopefully this helps you!
