### ISSUE TITLE
feat: Disabled input for SegmentButton

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#5639]
**Ionic-Version:** 2.0.0-beta.1

It would be nice to have the possibility to set a disabled property on a segment button.

**Comment by brandyscarney** [comment]
Hey, thanks for the issue! So I added the `disabled` property to both the `ion-segment` and `ion-segment-button`, however this is how the styling looks on each mode:

##### iOS

![screen shot 2016-04-27 at 4 09 31 pm](https://cloud.githubusercontent.com/assets/6577830/14866929/0f3bc7ec-0c94-11e6-9201-33a5021aa8b9.png)

##### Material Design

![screen shot 2016-04-27 at 4 09 40 pm](https://cloud.githubusercontent.com/assets/6577830/14866930/0f3c0ff4-0c94-11e6-8a6d-77fe284e73ed.png)

##### Windows

![screen shot 2016-04-27 at 4 09 49 pm](https://cloud.githubusercontent.com/assets/6577830/14866931/0f3dc61e-0c94-11e6-9e01-20c8a26ce7f2.png)

It could probably be made more obvious, in Windows mode at least, that the button is disabled. Going to leave this open. cc @bensperry

**Comment by brandyscarney** [comment]
Ben said this UI is good for now. Going to close this. It will be in beta.7. Thanks again! 👍
