### ISSUE TITLE
[bug] <ion-toolbar position="bottom" > footer will not applied the CSS animated page transitions

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic#5640]
#### Short description of the problem:
`<ion-toolbar position="bottom" >` footer will not applied the CSS animated page transitions when `nav.push()` or `nav.pop()`
#### What behavior are you expecting?
`<ion-toolbar position="bottom" >` will also applied the animated transitions like `<ion-contet>`
#
**Ionic Version**:  2.x
**Browser & Operating System**: iOS / Android / Chrome

![image](https://cloud.githubusercontent.com/assets/11818108/13378020/fde5e988-de2f-11e5-9d45-bc568a78e6f8.png)

**Comment by kitkimwong** [comment]
@brandyscarney  any  comments?

**Comment by adamdbradley** [comment]
This should have been recently fixed in this commit: https://github.com/driftyco/ionic/commit/daa4ccc30cddc5739baa91694a7ba548f769979b

https://github.com/driftyco/ionic/issues/5692

Thanks
