### ISSUE TITLE
v2 generate new page - hint text incorrect

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5641]
#### Short description of the problem:
When you create a new page using CLI via

`ionic g page myPage`

Helpfully you provide a comment 

```
Don't forget to add an import for city-new.scss in app/themes/app.core.scss:

  @import ../pages/city-new/city-new.scss
```

Now perhaps this is obvious, but the import should be with double quotes and a semi-colon 

```
Don't forget to add an import for city-new.scss in app/themes/app.core.scss:

  @import "../pages/city-new/city-new.scss";
```

#### What behavior are you expecting?
The hint should be with quotes and semi-colon, rather than without. 
Might prevent some future support questions (although perhaps this is obvious) 

**Ionic Version**: 1.x / 2.x
2

**Browser & Operating System**: iOS / Android / Chrome

Mac / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by tlancina** [comment]
Thanks! Fixed in 3784f47cfa50929aba744ffef14c6cc052fb0419.
