### ISSUE TITLE
issue ionic docs guide Chapter 5: Building out your app

### ISSUE THREAD

**Issue by otaviopires** [driftyco/ionic#5643]
#### Short description of the problem:
At the end of the tutorial I wasn't being able to add any tasks to my new projects, and I was getting the TypeError: Cannot read property 'push' of undefined return, meaning that $scope.activeProject.tasks wasn't being initiated as it was before.
So I inserted a line initiating it at the newProject function.

#### What behavior are you expecting?
Being able to add new tasks.

**Steps to reproduce:**
1. insert the line newProject.tasks = []; at the function createProject
2. after creating newProject
3. 

```
  var createProject = function(projectTitle) {
    var newProject = Projects.newProject(projectTitle);
    newProject.tasks = [];
    $scope.projects.push(newProject);
    Projects.save($scope.projects);
    $scope.selectProject(newProject, $scope.projects.length-1);
  }

```

**Ionic Version**: 1.7.14

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.2.6

```

**Comment by mhartington** [comment]
Hey there! So I just ran through the getting started code again, and wasn't able to reproduce the error you've described. Im going to closing this for now, but if you're still having trouble, you might want to ask on the forum or public slack 

https://forum.ionicframework.com/

http://ionicworldwide.herokuapp.com/
