### ISSUE TITLE
bower.json: angular-ui-router package now just ui-router?

### ISSUE THREAD

**Issue by domhnallw** [driftyco/ionic#5644]
#### Short description of the problem:

bower.json included with ionic 1.2.4 contains a reference to the 'angular-ui-router' package, but it looks like this is now just called 'ui-router' (see https://github.com/angular-ui/ui-router )

#### What behavior are you expecting?

That a 'bower update' will work. Instead, I get:

```
bower angular-ui-router#0.2.13        ENOTFOUND Package angular-ui-router not found
```

**Steps to reproduce:**
1. `bower update`

**Ionic Version**: 1.2.4

**Browser & Operating System**: Mac OS X 10.10.5

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by floriansimon1** [comment]
Confirmed. See  #5647 and https://github.com/angular-ui/ui-router/issues/2592

**Comment by jbaskeen** [comment]
`bower install angular-ui-router` is working again, #5647 should not be necessary anymore

https://github.com/angular-ui/ui-router/issues/2592

**Comment by domhnallw** [comment]
Yep, confirmed. Closing.

**Comment by christopherthielen** [comment]
UI-Router guy here. I'm moving the bower package support to a separate repository.  The bower people deregistered the package this morning and asked that I re-register it.   However I didn't get to it soon enough and some random person re-registered it under their name.

Follow these issues: 

https://github.com/bower/registry/issues/179#issuecomment-190194465
https://github.com/angular-ui/ui-router/issues/2592

**Comment by christopherthielen** [comment]
OK, the ui-router bower move should be complete now.
