### ISSUE TITLE
Support for theme-href="your-theme.css" in addition to ios-href and md-href

### ISSUE THREAD

**Issue by jimitndiaye** [driftyco/ionic#5645]
#### Short description of the problem:
I'd like to be able to dynamically override theme colors based on a user-selected theme. Ionic2 use md-href and ios-href to dynamically load the appropriate platform stylesheet. There is no similar behavior for dynamically setting the theme other than fully building it into the platform stylesheets. I'd like to have the platform stylesheets focused on platform-specific look on feel while the theme stylesheet overrides colors, etc.

#### What behavior are you expecting?
specifiying theme-(theme name)-href="some stylesheet" loads the appropriate stylesheet that overides the colors of the platform stylesheet.

**Steps to reproduce:**
1. Load ionic-conference-app sample
2. Inspect index.html
3. 

``` html
  <!-- ionic dynamically decides which stylesheet to load -->
  <link ios-href="build/css/app.ios.css" rel="stylesheet">
  <link md-href="build/css/app.md.css" rel="stylesheet">
```
**Ionic Version**: 1.x / 2.x
Ionic2
**Browser & Operating System**: iOS / Android / Chrome
All of the above

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v5.6.0

**Comment by adamdbradley** [comment]
Sorry but at this time we won't be adding this feature to Ionic. Adding custom styles is something the dev should be adding, or this feature would be app specific.
