### ISSUE TITLE
bug: Can't close date input IOS

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5646]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When in IOS i open the date input but there's no way of closing it, and it will even carry out to the ionic modal content, at least the android one shows 3 buttons, erase, cancel and accept (or stablish), here's two images to ilustrate the issue:
![image](https://cloud.githubusercontent.com/assets/9698639/13395599/cbd70bfa-debd-11e5-889e-bdfbf7a64a19.png)
And android version:
![image](https://cloud.githubusercontent.com/assets/9698639/13398810/0c468c6e-dece-11e5-8657-59f1d846d038.png)
</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
**Update 1:** Correction, it doesn't show any way of closing the keyboard for any input, be it date, text, numeric or possibly any other type.

**Comment by Luchillo** [comment]
**Update 2:** Check this date input from chrome, it has 2 buttons on top to accept or cancel:
![image](https://cloud.githubusercontent.com/assets/9698639/13404300/063d4628-dee7-11e5-9be4-c20ab1c4546f.png)

**Comment by Luchillo** [comment]
Ok i found how to put the buttons by using a cordova keyboar method in the `app.ts` file:
```js
cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false)
Keyboard.shrinkView(true);
```

**Comment by jgw96** [comment]
Thanks for submitting this issue! As it looks like you found a fix for your issue i will go ahead and close this issue for now. If you still need help feel free to reopen this issue please!

**Comment by Luchillo** [comment]
This should be a default in the starters, it was hard to actually find how to fix, or at least put it in the `FAQ` in the docs.
