### ISSUE TITLE
typings.json missing and main.d.ts used "wrongly"

### ISSUE THREAD

**Issue by Foxandxss** [driftyco/ionic#5648]
#### Short description of the problem:

typings.json is missing.

#### What behavior are you expecting?

Since the initial project has `es6-shim` it would make sense to have it saved in a `typings.json` so we can restore the folder in a later point.

Personally I think that it makes sense for the initial project to just offer a `typings.json` and not the installed typing and then install it in a after_hook or something. That way you don't need to have both the installed one and the reference in typings.json up to date all the time.

Some users would ignore the typings folder on the .gitignore and other users will install more typings, so it would be awkward to have a typings.json without the default ones or having to delete the default ones and reinstall them to save them on the typings.json.

On the other hand, using the `main.d.ts` directly on the webpack config is nice (avoid the errors when transpiling) but on the other hand, the editors are not able to see them so they will put all those red wiggles.

I am not sure if IDEs are going to support typings officially (webstorm is able to read the tsd folder), but I think that the official position is using the main.d.ts on the tsconfig or adding a /// reference somewhere with it.

Best solution would be for all editors / IDEs to be able to read the typings folder and apply those definitions for visual help and then use the definitions on webpack loader so tsc doesn't barf. But in the meantime we don't have IDE support :/

**Steps to reproduce:**
1. Just create a project and see it.

**Ionic Version**: 1.x / 2.x

Ionic 2 beta 1.

**Comment by tlancina** [comment]
Thanks for the issue, I've just updated the starters.  I agree it would be ideal to not have the typings directory, but not everyone is going to have `typings` installed and I don't think the definitions will be changing much, so I think it's better to have them checked in.

Going to close, but please let me know if you think there's anything about the setup we could do better, thanks!

**Comment by Foxandxss** [comment]
If you add typings on the starters, you can have typings as a devDependency so you don't force the users to have it installed. Anyhow, the solution provided works for now. Just missing the IDE support tho.

**Comment by tlancina** [comment]
Sure you can install it as a devDependency, but how do they actually install the typings? I think asking users to run `$(npm bin)/typings` would be too much.  Also, IDE support should be there, the typings are included by tsconfig.json.  I can see them in both VSCode and Atom using atom-typescript, is this not the case for you?

**Comment by Foxandxss** [comment]
Seems like VSCode and Webstorm supports reading the typings folder now, it just took a few seconds to update, my bad.

About the typings, I am happy in how it sits now, no worries about that. What I personally do in other projects is to have a after_hook (like postinstall) to install the typings using `$(npm bin)typings`.

Thank you.

**Comment by tlancina** [comment]
Ah great, glad it's working.  And having a postinstall script is not a bad idea at all, although I'll probably hold off for now to keep the number of dependencies that need to be installed on start down, but definitely something to consider in the future (especially if we add more typings).

**Comment by Foxandxss** [comment]
Angular 2 is moving away the typings from core, so as soon as a starter includes tests, you will need jasmine typings (or mocha).
