### ISSUE TITLE
App freezes for a few secons on android back button

### ISSUE THREAD

**Issue by slzr** [driftyco/ionic#5649]
the entire application doesn't respond for a few seconds when i use the android back button for getting back in history view, it doesn't respond for any input or touch gesture.
if i use the `ion-nav-back-button` in the same case the app works fine.
`Android 4.2 (API 17)`
`Ionic 1.2.0`

**Comment by mhartington** [comment]
Hi there :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by slzr** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9486209/13450160/be177818-e004-11e5-8c3b-05ecdae3a09d.gif)
i think the problem is relationated with the issue #2690, there is a lag for a few second after the animation is ended, but only when i call the native back button, i change the styles of `click-block` and works fine, but i don't know the consequences of that.

**Comment by mhartington** [comment]
So I should be able to see this if I used the tabs/sidemenu starter and just load it on my android device? Then use the hardware back button to navigate back? Will investigate this.

**Comment by mhartington** [comment]
So I'm seeing this in my test, though in varying degrees. Sometimes the click block sticks around for a long time, sometimes it goes away quickly. 🤔 

I think a lot of this has to do with the particular views you are navigating to and from. Some cases, if there's a lot of content, big DOM, setting classes can be a bit slow, which looks like what's going on here.

**Comment by slzr** [comment]
i tested in my app removing the content and you're right, because when i move from a view to another and that another view has a lot of content, it lags for a few seconds, i just overwrote the `click-block` css styles so it doesn't show anymore and works fine, but i know it's not the best solution.

**Comment by mhartington** [comment]
Hmm, probably not the best solution, since that click block is preventing any accidental clicks during transition. 

One solution would be to minimize the DOM and content you have. From the looks of the gifs, it appears that there's box-shadows on the cards? Maybe consider removing them as they're expensive to animate and could be the bottle neck. Also maybe consider reducing the opacity on that text's div. This could also be a bottle neck

**Comment by slzr** [comment]
following your suggestion, I simplify the styles removing all rgba and box-shadow, but the app still lags and i cant remove more elements, i'll stick around with the click-block hidding, since any accidental click
won't do any harm in this case.
for the record, using the soft back button `ion-nav-back-button` works perfectly with no `click-block` lag

**Comment by mhartington** [comment]
Going to close this
