### ISSUE TITLE
ion-checkbox with item-remove-animate applied does not animate properly when removed from an ion-list

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [driftyco/ionic#5652]
#### Short description of the problem:

The contents of the item are slid out to the left and then the item disappears. The item below that which is being removed is not animated into place, and the check-box itself is not animated.

#### What behavior are you expecting?

An animation consistent with standard ion-item components.

**Steps to reproduce:**
```
<ion-list>
	<ion-checkbox
		class="item-remove-animate"
		ng-model="todo.completed"
		ng-repeat="todo in todoController.todos"
		ng-if="todoController.showCompleted || !todo.completed">
		{{todo.title}}
	</ion-checkbox>
</ion-list>
```

**Ionic Version**: 1.2.4

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Hello! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
