### ISSUE TITLE
bug: Swipe back disabled not working

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5653]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>The IOS `swipeBackEnabled` property doesn't work in IOS, here's the html related:
```html
<ion-nav id="nav" #rootNavController [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```
</span>

<span is-issue-template></span>

**Comment by cyprusglobe** [comment]
@Luchillo 
i think the correct syntax is this
```
<ion-nav id="nav" #rootNavController [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>
```

**Comment by Luchillo** [comment]
That's totally weird, the starter projects has the syntax i'm using, anyway i tried using your way but the issue keeps happening, however android doesn't seems to be affected by the change, android keeps stopping `swipe-back` which kind of tell me that it's like native for IOS to swipe back

**Comment by jgw96** [comment]
Thanks for submitting this issue! We would like to get a little more info from you so that we can help you better. Would you mind running `ionic info` and posting the output here?

**Comment by jasperkuperus** [comment]
I ran into the same problem, with:

```
<ion-nav id="nav" [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>
```

This is my `ionic info`:

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.3 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

The behaviour I see is the same as this issue: https://github.com/driftyco/ionic/issues/5575

**Comment by manucorporat** [comment]
@adamdbradley @Luchillo fixed here: https://github.com/driftyco/ionic/pull/5879

this should be closed!

**Comment by adamdbradley** [comment]
Thanks @manucorporat!
