### ISSUE TITLE
v2 button in navbar - should it have default button design? Currently doesnt

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5654]
#### Short description of the problem:

If you add a button to a navbar, it is text only, no background / solid feel
If you add the same button to content, the button has a solid feel to it (as per default, in documentation)

http://codepen.io/anon/pen/wGBWbJ has example of same button HTML, different outcomes

#### What behavior are you expecting?

I would expect the design of the button to be the same, regardless of its context?

However, if that is by design that the default is different for different contexts, then should have capability to get to the solid button (like you can set to get the outline design) as an override (without using direct CSS)

**Steps to reproduce:**
1. http://codepen.io/anon/pen/wGBWbJ    and see buttons (x2)
2. OR put this code in a tabs starter navbar, and in the ion-content (having removed ion-buttons), and see they are different
3. 

```
<ion-buttons end>
  <button (click)="openItemBlahModal()">
            <ion-icon name="add-circle"></ion-icon>
            New item
        </button>
</ion-buttons>
```

**Ionic Version**: 1.x / 2.x
2

**Browser & Operating System**: iOS / Android / Chrome
Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
See codepen 
```

**Comment by brandyscarney** [comment]
Thanks for the issue. This is by design. To get the default button from content in a toolbar you can add the `solid` attribute. There is an open issue here to update the docs: https://github.com/driftyco/ionic-site/issues/451

**Comment by alexbainbridge** [comment]
Thanks!

**Comment by ungular** [comment]
how to make a rounded button in navbar?
I tried this but I got a rectangular button:  <button solid round>

**Comment by brandyscarney** [comment]
That seems like a bug @ungular, could you create a new issue for that?

**Comment by ungular** [comment]
@brandyscarney, done: https://github.com/driftyco/ionic/issues/7661
