### ISSUE TITLE
 How to exchange refresh (new datas) with infinite-scroll (older datas) ionic

### ISSUE THREAD

**Issue by nowitz** [driftyco/ionic#5656]
I want to keep the latest data are shown below (as is the case with sms / facebook messages) and if you pull from the bottom up so that it was restoring data and if you pull the top down so that there was a display of old data.
I have now:
```
<ion-content>
        <ion-infinite-scroll on-infinite="loadMore()" distance="50%"  ng-if="deviceReady"></ion-infinite-scroll>
             <ion-list>
                    <ion-item ng-repeat="b in blogs">
                        <h2>{{ b.id }}</h2>
                        <p>{{b.nick + " " +b.message}}</p>
                    </ion-item>
             </ion-list>
         <ion-refresher pulling-text="Reload blogs" on-refresh="reload()"></ion-refresher>
</ion-content>
```
and it does not work.
Thanks for advice

**Ionic Version**: 1.2.1 

**Browser & Operating System**: iOS, Android, Chrome

**Comment by mhartington** [comment]
Hey there! So this is more of a question for the forum, and not an actual issue. 
Looks like you've already posted there, so we'll continue this over there.
