### ISSUE TITLE
Button disappear when title text too large

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5657]
#### Short description of the problem:

When title is too big in the navbar, the right button in the title disappear
#### What behavior are you expecting?

The title text should ellipsize at the end and keep any buttons in the screen.

**Steps to reproduce:**
1. add the snippet below to a view and run.

```
<ion-navbar primary *navbar>
  <ion-title>
   A very large title with many many letters can be something hard to read, but somethings we don't have control of it.
  </ion-title>
  <ion-buttons end>
    <button class="button button-clear" (click)="dismiss()">
      <ion-icon name="close"></ion-icon>
    </button>
  </ion-buttons>
</ion-navbar>

```

**Ionic Version**: 2.x

**Browser & Operating System**:
tested on android

```
ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.10 
Node Version: v5.6.0

```

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the beta.2 release. :smile: 

![screen shot 2016-03-01 at 12 59 38 pm](https://cloud.githubusercontent.com/assets/6577830/13436496/89b43c20-dfad-11e5-8a71-9b75b042942c.png)
