### ISSUE TITLE
ion-slide-box breaks ngAnimate

### ISSUE THREAD

**Issue by matitalatina** [driftyco/ionic#5664]
#### Problem:
Whenever I add `ion-slide-box` and some `ion-slide` ngAnimate stops working in the app.
Indeed I discovered it in [this post](https://forum.ionicframework.com/t/angular-animations-nganimate-not-working-for-ionic-v1-2-4-angular-v1-4-3/41107/4), all credits goes to yosikal.

#### Expectations:
ngAnimate should works even if there is `ion-slide-box` in my app.

**Steps to reproduce:**
1. Add `<ion-slide-box"><ion-slide><img src="...."></ion-slide></ion-slide-box>` in a page
2. Visit that page.
3. All animations stop working

#### Solution:
In line 63350 in `ionic.bundle.js`
```
$animate.enabled(false, $element);
```

should be:
```
$animate.enabled($element, false);
```

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS / Android / Chrome

**Comment by aikon78** [comment]
thanks to yosikal for discovering this bug!

**Comment by Kinzi** [comment]
+1 please fix this. it took me annoying 8h to solve/find this issue!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As `ion-slide-box` has been depecrated i will be closing this issue for now. Look out for alot of updates to slides in the near future!

**Comment by diegodotta** [comment]
I don't think it's only about the ion-slide-box @jgw96, this issue is about all animations that use ngAnimate and angular 1.4.3. And that is very annoying.

I did this in my ionic.bundle.js and now its working fine. Anyone know how do this in the ionic.bundle.min.js? I didn't find the code there.

**Comment by jgw96** [comment]
@diegodotta Hey sorry about that! (: Would you mind making a plunker that demonstrates the issues you are describing?
