### ISSUE TITLE
bug: Ionic click event propagation

### ISSUE THREAD

**Issue by antonfire** [driftyco/ionic#5665]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am trying to prevent click event propagation when a view header or modal header is covered by an overlay div. The div represents a notification and on click I would like it to perform a redirect. The issue is that the click event bubbles through to the view header / modal header buttons when I would like to stop this happening. I can't work out how to prevent this behaviour. Any help would be very much appreciated. I have tried:

CSS:

     pointer-events: none !important;

JS:

Passing $event into the ng-click to try:

        $event.stopPropagation();
        $event.preventDefault();

I have also tried at the end of the ng-click function:

        return false;

HTML:

I have tried the ionic class:

     disable-pointer-events

and have also tried the ionic directive:

     data-tap-disabled="true"

I have reproduced this behaviour in a codepen, please resize the viewport in the pen to ensure that when the modal is opened it takes up the full viewport. The behaviour can be replicated by clicking on the notification above the underlying header buttons both with modal open and without.

Any help would be appreciated, I can't get my head around it.

pen: http://codepen.io/antonfire/pen/WwbMOW

Thanks</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Hi there! So this has to do with how the modal view has pointer-events set to auto. This is to make sure that nothing else can be clicked if it is outside the modal, the exact opposite of what you want. For your case, you can add `pointer-events: auto;` to the notification bar element and it will behave as you expect. Events will not propagate into the model element. 


http://codepen.io/mhartington/pen/VaYGGK?editors=1100

**Comment by antonfire** [comment]
Thanks that's great, really appreciate the help.
