### ISSUE TITLE
Can't import @page instance inside custom component with native ionic2 directives

### ISSUE THREAD

**Issue by EugeneSnihovsky** [driftyco/ionic#5666]
#### Short description of the problem:
I create a self made navbar component wich include ionic2 components (**app/components/navigation/top-navbar.component.ts**). 

It import for itself other pages (SettingsPage) and navigate to it by **navCtrl.setRoot(SettingsPage)**

Also this navbar present on all pages. On HomePage (I try navigate **from it**) and on SettingsPage (I try navigate **to it**).

When I try to navigate, I receive an error
###### EXCEPTION: Unexpected directive value 'undefined' on the View of component 'SettingsPage'

![alt tag](https://sc-cdn.scaleengine.net/i/04a8c082d19afe1c38dd3a5341e7e5f1.png)

#### What behavior are you expecting?
I want to navigate through pages with navbar

**Steps to reproduce:**
1. git clone https://github.com/EugeneSnihovsky/ionic2-for-errors.git
2. cd ionic2-for-errors
3. npm install
4. ionic serve
5. In opened browser try to navigate with any link
6. Errors append in your browser console

#### Navbar code
```
'use strict';

import {NavbarTemplate, Navbar, Item, Icon, Segment, SegmentButton, Menu, MenuToggle, MenuClose, NavController, NavParams} from 'ionic-framework/ionic';
import {Component} from 'angular2/core';

import {SettingsPage} from '../../main/settings/settings.page';

@Component({
    selector: 'top-navbar',
    templateUrl: 'build/components/navigation/top-navbar/top-navbar.html',
    directives: [NavbarTemplate, Navbar, Item, Icon, Segment, SegmentButton, Menu, MenuToggle, MenuClose]
})

export class TopNavBarComponent {
    private navCtrl: any;
    private navParams: any;

    constructor(navCtrl: NavController, navParams: NavParams) {
        var self = this;
        self.navCtrl = navCtrl;
        self.navParams = navParams;
    }

    openPage(name) {
        var self = this;

        self.navCtrl.setRoot(SettingsPage);
    }
}
```

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.2 Rafaela 
Node Version: v5.3.0
```

**Comment by tlancina** [comment]
Hey there, thanks for providing the repo. It looks like there is a circular reference between your component and the SettingsPage:
https://github.com/EugeneSnihovsky/ionic2-for-errors/blob/master/app/components/navigation/top-navbar/top-navbar.component.ts#L6
https://github.com/EugeneSnihovsky/ionic2-for-errors/blob/master/app/components/main/settings/settings.page.ts#L5

I believe you can use [`forwardRef`](https://angular.io/docs/ts/latest/api/core/forwardRef-function.html) to get around this:
```
'use strict';
import {forwardRef} from 'angular2/core';
import {Page} from 'ionic-framework/ionic';

import {TopNavBarComponent} from '../../navigation/top-navbar/top-navbar.component';

@Page({
    directives: [forwardRef(() => TopNavBarComponent)],
    templateUrl: 'build/components/main/settings/settings.html'
})
```

**Comment by EugeneSnihovsky** [comment]
Great! It's working. Thank's a lot for help and sorry for your time wasting for me.

**Comment by tlancina** [comment]
Glad it's working! Not a waste at all :) Going to close this, but let us know if you're still having issues.

**Comment by morrisonbrett** [comment]
Thank you @tlancina.  The `forwardRef` guidance was extremely helpful.  I don't know how I would have moved on any other way. Working great!
