### ISSUE TITLE
Uncaught ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by fadifannoun** [driftyco/ionic#5667]
Bug resulting in dead white screen on Android 4.*
```
Uncaught ReferenceError: Promise is not defined at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17726
```

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by mhartington** [comment]
Hi there :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by jgw96** [comment]
Thanks for submitting this issue, we really appreciate it! As its been a while without a reply i am currently going to close this issue. But feel free to reopen it if needed! We would love to help you!
