### ISSUE TITLE
Label colors are different for specific items

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5669]
#### Short description of the problem:

Some input labels look very different than others.

[See the screenshot](https://drive.google.com/file/d/0B4xXV3RCbLl1eUV5ZWh2MDhFRXM/view?usp=sharing)

#### What behavior are you expecting?

I would expect uniform colors, etc.

**Steps to reproduce:**
1.  Paste the following snippet into any Ionic v2 page

```
<ion-content class="has-header">
        <form #areaForm="ngForm">
            <ion-item>
                <ion-label>Name <span danger>*</span></ion-label>
                <ion-input type="text" required ></ion-input>
            </ion-item>
            <ion-item>
                <ion-label>Identifer <span danger>*</span></ion-label>
                <ion-input type="text" required></ion-input>
            </ion-item>
            <ion-item>
                <ion-label>Test <span danger>*</span></ion-label>
                <ion-toggle danger checked="true"></ion-toggle>
            </ion-item>
            <ion-item>
                <ion-label stacked>Notes</ion-label>
                <ion-textarea ></ion-textarea>
            </ion-item>
            <div padding>
                <button primary block>Save Item</button>
            </div>
        </form>
    </ion-content>
```

**Ionic Version**: 1.x / 2.x

2.x

**Browser & Operating System**: iOS / Android / Chrome

All

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by brandyscarney** [comment]
So I added the gray color to `ion-select` labels, but we are not going to be changing the color of the labels in toggles. The gray labels are only for inputs. If you wanted to get the gray label for a toggle you could use the following markup:

ios mode:

```
.item-toggle ion-label {
  color: #7f7f7f
}
```

and md/wp mode:

```
.item-toggle ion-label {
  color: #999
}
```

Thanks!

**Comment by gldraphael** [comment]
Hey @brandyscarney, is there a reason why the label for `ion-select`s alone are black?

**Comment by itemir** [comment]
+1 This is indeed awkward.
