### ISSUE TITLE
beforeleave doesnt fire if $state.go with reload:true to same state is used

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ionic#5670]
This Bug is for Ionic V1:

If I use $state.go with destination state set to the same state as the one I'm already on, and I use reload:true, beforeleave is never fired.

Is that intended behavior?

**Comment by jgw96** [comment]
Thanks for submitting! Since this is not really a bug and more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or on our slack channel (http://ionicworldwide.herokuapp.com/). Thanks for submitting though!
