### ISSUE TITLE
ionic generate command is still using @Inject syntax

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic#5671]
#### Short description of the problem:

When using the ionic generate command it uses @Inject for dependency injection.

#### What behavior are you expecting?

The generate command should use the new dependency injection method:

```
  static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }
```

**Steps to reproduce:**
1. Generate a new project using `ionic start test blank --v2`
2. Run a generate command `ionic g page Test`

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by tlancina** [comment]
Dang you're right, fixed in 1473011a89b8a2b74eee4d162bca04976dc3d1d4.
