### ISSUE TITLE
scroll upside down

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#5672]
#### Short description of the problem:
(whole the action with 1 touch dont release the finger)!!!
while pulling to refresh without leaving the touch from the screen and continue scroll (still not release the touch importent!) scroll goes upside down
 
i can provide utube link if need

**Ionic Version**: 1.x

**Browser & Operating System**:  Android / Chrome
(i guess ios too)

**Comment by jgw96** [comment]
Thanks for submitting this issue! Would you mind providing a little more info on this issue so we can better help you with it? A youtube link would be great, along with a codepen or code sample if possible! Also could you run `ionic info

**Comment by jgw96** [comment]
Thanks for submitting this issue! Would you mind providing a little more info on this issue so we can better help you with it? A youtube link would be great, along with a codepen or code sample if possible! Also could you run `ionic info` and paste the output here please?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
