### ISSUE TITLE
keyboard jumps down and up after $ionicScrollDelegate.$getByHandle('myScroll').scrollBottom(true)

### ISSUE THREAD

**Issue by dimitrisTheof** [driftyco/ionic#5675]
I am using ionic-plugin-keyboard and I am working on a chat application. I am using the following code in my controller:

.controller('ChatDetailCtrl', function ($scope, $stateParams, $ionicScrollDelegate, $interval, Chats, $rootScope, $timeout) {
	
	//receive message
	$scope.$on('onRepeatLast', function (scope, element, attrs) {
		var viewScroll = $ionicScrollDelegate.$getByHandle('userMessageScroll');
		keepKeyboardOpen();
		viewScroll.scrollBottom(true);
		keepKeyboardOpen();
	});
	
	//send message
	$scope.sendMessage = function () {
           
            keepKeyboardOpen();
            viewScroll.scrollBottom(true);
            keepKeyboardOpen();
			
        }

	function keepKeyboardOpen() {
				
		if (txtInput !== undefined) {
			txtInput.one('blur', function () {
				if(!IOS){
					window.cordova.plugins.Keyboard.show();
				}
				txtInput[0].focus();
			});
		}
	}
})

Also I am using the directive:
.directive('onLastRepeat', function () {

        return function (scope, element, attrs) {
            if (scope.$last) setTimeout(function () {
                scope.$emit('onRepeatLast', element, attrs);
            }, 1);
        };
    })
	
on config xml I am using:
<preference name="HideKeyboardFormAccessoryBar" value="true"/>

on $ionicPlatform.ready I am using:
if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
if (window.StatusBar) {
  // org.apache.cordova.statusbar required
  StatusBar.styleDefault();
}

	
	
On android platform everything is ok for both cases(send-receive message). 
On ios platform send has normal behaviour but on receive message my keyborad jumps down and up again.
This happens after (viewScroll.scrollBottom(true);)
I want my keyboard stable and on receive message and just scrolling to the bottom like andoid.
I know that window.cordova.plugins.Keyboard.show(); uses only for andtoid platform.
What is going on? Can you please help me?

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
