### ISSUE TITLE
[v2] can't reset ion-infinite-scroll

### ISSUE THREAD

**Issue by sclausen** [driftyco/ionic#5677]
#### Short description of the problem:
after the data of an already scrolled `ion-list` is reset, the value `_highestY` in [infinite-scroll.ts#L171](https://github.com/driftyco/ionic/blob/2.0/ionic/components/infinite-scroll/infinite-scroll.ts#L171) prevents infinite scrolling.

#### What behavior are you expecting?

A convenient way to reset the infiniteScroll should be possible, useful for example with search results, where a new search resets the content of the view.

**Ionic Version**: ionic-angular@2.0.0-beta.2

**Comment by cmanou** [comment]
Another option would be to remove the highestY, though that will impact performance.

**Comment by beerbohmdo** [comment]
Since private variables in TypeScript are not realy private in JavaScript I do this now ...

```ts
                        // Hack hack until a right way is implemented ... :(
                        //noinspection TypeScriptUnresolvedVariable
                        this.infinite._highestY = 0;
                        //noinspection TypeScriptUnresolvedVariable
                        this.infinite._lastCheck = 0;
```

**Comment by adamdbradley** [comment]
Thanks for opening this issue, it definitely helped exposed a problem with it's current API. Like you pointed out, once the data changes and it's height is smaller than before, then infinite scroll no longer works. I just removed the need for highestY checks entirely, since I think requiring the reset() function called every time data changes would be problematic for developers.

https://github.com/driftyco/ionic/commit/fe04c51866860c9e033c960550f16126305ac58f

Thanks!

**Comment by wieseljonas** [comment]
Hi, I have this issue aswell but I'm confused how do I access the infiniteScroll outside the event emission to perform a reset?

**Comment by sclausen** [comment]
@wieseljonas have a look at the [sources](https://github.com/driftyco/ionic/blob/2.0/ionic/components/infinite-scroll/infinite-scroll.ts) you can simply store the passed InfiniteScroll to a member variable and then access it from outside of the event emission.

**Comment by ciekawy** [comment]
@sclausen still this seems to be workaround. I wonder if there is any new issue regarding resetting infiniteScroll mentioned by @wieseljonas or should it be created?

**Comment by sclausen** [comment]
@ciekawy I don't think it's needed, since @adamdbradley removed the highestY check, or does it still causes problems for you?

**Comment by ciekawy** [comment]
will check it more deeply. I've found it not working and just added the reset by capturing to a member.
