### ISSUE TITLE
bug: Install errors

### ISSUE THREAD

**Issue by eatocia** [driftyco/ionic#5679]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Last login: Wed Mar  2 11:19:18 on ttys001
nycers-iMac:~ nycer$ sudo npm install -g ionic
Password:
*****
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> node-sass@3.4.2 install /usr/local/lib/node_modules/ionic/node_modules/node-sass
> node scripts/install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at startup (node.js:91:32)
    at node.js:962:3
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nycer/npm-debug.log
nycers-iMac:~ nycer$ *****
-bash: *****: command not found
nycers-iMac:~ nycer$</span>

<span is-issue-template></span>

**Comment by eatocia** [comment]
hello, 
have previously installed Ionic 1.2.4 and all fine, but experiencing difficulties with this install/machine..  

thanks

**Comment by tlancina** [comment]
Hey there, I'm going to move this over to the ionic-cli repo.

**Comment by tlancina** [comment]
This issue was moved to driftyco/ionic-cli#805
