### ISSUE TITLE
how use ionic.io in ionic2-angular2

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic#5680]
#### http://docs.ionic.io/docs/io-introduction

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Ionic Version**:  2.x

**Browser & Operating System**: iOS / Android / Chrome

**Comment by jgw96** [comment]
Thanks for submitting an issue! Since this is a question and not really a bug you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Please feel free to ask over there and thanks again!
