### ISSUE TITLE
bug: position="bottom" not working on <ion-toolbar>

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#5681]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>According to the docs:
http://ionicframework.com/docs/v2/components/#toolbar

I just added this toolbar to a fresh installed ionic2 starter (tabs)

```
<ion-toolbar position="bottom">
  <ion-title>Footer</ion-title>
</ion-toolbar>
```

But the toolbar is NOT aligned to the bottom.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
I don't see the `position="bottom"` on the toolbar.

**Comment by flavordaaave** [comment]
My bad. I updated the snippet. (Still doesn't work ;-) )

**Comment by brandyscarney** [comment]
What does the rest of your markup look like? Using the following I am able to see the toolbar at the bottom:

```
<ion-navbar *navbar>
  <ion-title>Heart</ion-title>
</ion-navbar>
<ion-content>
  <ion-list>
    <ion-list-header>
      Tab 1
    </ion-list-header>
    <ion-item *ngFor="#i of items">Item {{i}} {{i}} {{i}} {{i}}</ion-item>
  </ion-list>
</ion-content>
<ion-toolbar position="bottom">
  <ion-title>
    Bottom toolbar
  </ion-title>
</ion-toolbar>
```

**Comment by flavordaaave** [comment]
Arrgh, sorry again... I was putting the toolbar inside ion-content. Working as expected.

**Comment by brandyscarney** [comment]
Not a problem! Glad you got it working. :smile:

**Comment by colindevs** [comment]
I am having this same problem, while placing the ion-toolbar outside of the content.

```
<ion-header>

  <ion-navbar>
    <ion-title>Chat</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>
  <h4>Shoe id: {{id}}</h4>
  <ion-list>
    <ion-item *ngFor="let message of messages | async">

    </ion-item>
  </ion-list>
</ion-content>
<ion-toolbar position="bottom">
  <input type="text">
  <ion-buttons end>
    <button royal>
      Send
      <ion-icon name="send"></ion-icon>
    </button>
  </ion-buttons>
</ion-toolbar>

```

**Comment by brandyscarney** [comment]
@colindevs The only elements that should be children of the page is the `ion-header`, `ion-content`, and `ion-footer`. The position attribute has been removed from the `ion-toolbar` and it should instead be placed inside of an `ion-footer`. Please see the breaking changes for beta 10: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta10-2016-06-27

We have an issue open to improve the documentation behind this: https://github.com/driftyco/ionic-site/issues/660

Thanks :)

**Comment by colindevs** [comment]
It works! Thanks.

**Comment by bytenik** [comment]
FYI the docs still show it using position.
