### ISSUE TITLE
*ngIf condition makes right to left with inner content

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic#5682]
#### Short description of the problem:

if I use `*ngIf` condition, then icon comes to left. but if I don't use `*ngif` condition, then icon stays on right. 
```
<div secondary item-right *ngIf="true">
     <ion-icon name='radio-outline'></ion-icon>
</div>
```

![image](https://cloud.githubusercontent.com/assets/34341/13463828/071d4b24-e086-11e5-87c0-3341e9770850.png)

#### What behavior are you expecting?

stay the div icon on right

![image](https://cloud.githubusercontent.com/assets/34341/13463908/52cd1c2a-e086-11e5-9455-382b06c8ac60.png)

**Steps to reproduce:**
1. create div with item-right
2. add icon inside that div
3. add `*ngif="true"` on the div

```
            <div primary item-right *ngIf="true">
                <ion-icon name='radio-outline'></ion-icon>
            </div>
```

**Ionic Version**:  2.x

**Browser & Operating System**: iOS / Chrome (not tested on android)

**Comment by brandyscarney** [comment]
Thanks for the issue! This is reported here: https://github.com/driftyco/ionic/issues/5060

It has also been reported to Angular here: https://github.com/angular/angular/issues/5363
