### ISSUE TITLE
ionic start fail

### ISSUE THREAD

**Issue by vactorlao** [driftyco/ionic#5683]
#### Short description of the problem:
when i start a new project use: ionic start project --v2 , and ionic serve
then can't build
![image](https://cloud.githubusercontent.com/assets/7175977/13464212/00f58938-e0cb-11e5-9cb1-887ffb3cc8ab.png)

#### What behavior are you expecting?
create a new project

**Steps to reproduce:**
1. 
2. 
3. 

```
ionic start project --v2
ionic serve
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#809
