### ISSUE TITLE
ion-scroll has native scoll in javascript scrolling active

### ISSUE THREAD

**Issue by cruelkoala** [driftyco/ionic#5686]
#### Short description of the problem:

ion-scroll has native and javascript scrolls at the same time. ion-scroll has scroll-y class which define overflow: scroll rule in any scroll mode.
#### What behavior are you expecting?

There is no native scroll in javascript scroll mode.

**Steps to reproduce:**
1. Add overflow-scroll="false"  to ion-scroll
2. Check ion-scroll css
3. ion-scroll has scroll-y class and has overflow-y:  scroll rule.

**Ionic Version**: 1.2.4 

**Browser Chrome

**Comment by armenbadalyan** [comment]
Seeing the same issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a quick plunker that i can use to test your issue with? You can use this template i made as a starter (http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info). Thanks again!

**Comment by armenbadalyan** [comment]
Please this plunker http://plnkr.co/edit/HnRoUIRiuvMlh8v2vVdR?p=preview

**Comment by jgw96** [comment]
Thanks for the plnkr! So im slightly confused on what the issue is exactly. Would you mind explaining more about what the issue your experiencing is?

**Comment by armenbadalyan** [comment]
Yes, sure. Please see the plunker again I've changed it a bit to demonstrate the issue.

The height of the scrolling area is 250px. Inside of it there's a list which is bigger than this area thus we can scroll it. But when I reach the bottom of the list I can continue scrolling and another scroll bar appears under the list. It seems like both JS scroll and native scroll are active at the same time.

**Comment by jgw96** [comment]
Ahh, ok thanks, i get it now. Will have to look more into this. Thanks!

**Comment by ygoraly** [comment]
Seeing same issue.
With ionic 1.1 javascript ion-scroll works nice for small areas on both mobile and desktop browsers.
Version 1.2, 1.3 always show native scrollbars on desktop browsers

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#170

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#171

**Comment by wggley** [comment]
+1, any answer regarding this?
