### ISSUE TITLE
Mailto links cause keyboard to incorrectly appear 'open' to the app

### ISSUE THREAD

**Issue by jacquesdev** [driftyco/ionic#5688]
#### Short description of the problem:

I have an app that 
- has mailto links in the view
- has buttons and inputs in the view

I need to hide the button when the keyboard is active, which checks the body.keyboard-open style that ionic adds based on the keyboard's state.

The problem comes in when I click on one of the mailto links, where it then adds the class of keyboard-open to the body. Once I close the email client, it does not remove this style.

So what happens is basically if I click a mailto link and close out the message, the button is missing, until I specifically click in an input element again, and then out again.

The Android version seems to be ok

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS (only on the mobile device)

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by jacquesdev** [comment]
Thank you!

**Comment by jgw96** [comment]
Thanks for submitting this issue, and im glad you were able to get some help! Since it looks like this issue was fixed for you i will be closing this issue.

**Comment by stoffern** [comment]
This is actually a issue in Ionic. Opening all "mailto" links in a iPhone will result in Ionic setting keyboard open. When returning to the app the keyboard keeps showing open. Clicks inside the app will not trigger "keyboard close"

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#169
