### ISSUE TITLE
Missing breaking changes informations in CHANGELOG for 2.0.0-beta.2

### ISSUE THREAD

**Issue by Fenkiou** [driftyco/ionic#5689]
I needed to replace ionic-framework by ionic-angular in the ionic.config.js file too.

Otherwise, I got a "Error: File to import not found or unreadable: ionic.ios"

**Comment by cyprusglobe** [comment]
@Fenkiou this is stated in the breaking changes CHANGELOG.md

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md

**Comment by Fenkiou** [comment]
@cyprusglobe Sure, I saw that, but not for the ionic.config.js file. Anyway, the issue can help people looking for this error (like me.. ah ah).

**Comment by jgw96** [comment]
Hello thanks for opening this issue with us! As the new package name is now well documented i will be closing this issue. Thanks again!
