### ISSUE TITLE
Error in opening browser platform's build package file, on mac

### ISSUE THREAD

**Issue by wanjungao** [driftyco/ionic#5691]
#### Short description of the problem:

Error in opening browser platform's build package file, on mac

#### What behavior are you expecting?
unzip the file without error.

**Steps to reproduce:**
1. Ionic build browser
2. double click on file "package.zip"

**Ionic Version**: 2.x

**Browser & Operating System**:  Mac OS

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-platform-issues#42
