### ISSUE TITLE
ion-toolbar visible on previous screen

### ISSUE THREAD

**Issue by mebibou** [driftyco/ionic#5692]
#### Short description of the problem:
When navigating to a page that contains a `ion-toolbar` like:
````
<ion-navbar *navbar>
  <ion-title>Title</ion-title>
</ion-navbar>
<ion-content>
</ion-content>
<ion-toolbar position="bottom">
  <button full primary showWhen="ios">My Button</button>
</ion-toolbar>
````
When navigating back to the previous page (click on back button in the header), the button in the `ion-toolbar` will remain visible for a second or two, basically until the animation to the previous page is completed.

#### What behavior are you expecting?
The toolbar should slide along with the page that contains it, and not remain static and suddenly disappear when animation is finished.

**Steps to reproduce:**
1. Copy-pate the code above in a new page
2. Add a parent page that navigates to this page
3. Navigate to the child containing the `ion-toolbar`, then navigate back

**Ionic Version**: 2.0.0-beta2

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by frederikschubert** [comment]
We are also running in this problem and would really like to have it fixed.

**Comment by kinggolf** [comment]
Same issue here. Big help once this is resolved. Thx.

**Comment by adamdbradley** [comment]
Thanks for the report, should be fixed in the next release.

**Comment by finalxcode** [comment]
i had faced same issue, just move your `ion-footer`  into `ion-content`  that can solve your issue
