### ISSUE TITLE
Native scroll isn't working inside javascript

### ISSUE THREAD

**Issue by cruelkoala** [driftyco/ionic#5694]
#### Short description of the problem:

Content inside ion-scroll isn't scrollable if ion-scroll located inside ion-content with javascript scrolling mode active
#### What behavior are you expecting?

ion-scroll content should be scrollable

**Steps to reproduce:**
1. Set overflow-scroll  to false for ion-content 
2. Add ion-scroll inside it
3. Set overflow-scroll to true for ion-scroll and set up height
4. Content inside ion-scroll isn't srollable.

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS / Android

**Comment by jgw96** [comment]
Thanks for submitting your issue! Would you mind creating a codepen or a code sample so that we can easily duplicate your issue please?

**Comment by cruelkoala** [comment]
@jgw96 done. check out this example http://codepen.io/CruelKoala/pen/BKzXBO

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#168
