### ISSUE TITLE
bug: config.set not working

### ISSUE THREAD

**Issue by bwalker72956** [driftyco/ionic#5696]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was trying to use config.set to set some parameters in the app.ts file using the argument syntax specified in the documentation --> set(platform, key, value) <--. I tried calling the command in the constructor and initializeApp methods.

The method does not appear to have any arguments in IntelliSense which leads me to believe that the method may not be implemented yet.

The get method appears to be fine.

Has config.set been implemented yet?</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Can you paste some of your code? Are you getting errors in the browser console? I added this to the conference app in the `constructor` of `app.js`:

```
this.config.set('ios', 'iconMode', 'md');
console.log(this.config.get('iconMode'));
```

and I am seeing the icons change to material design mode.

**Comment by bwalker72956** [comment]
CodePen:
http://codepen.io/bwalker729456/pen/EKVxVW?editors=1111

GitHub:
https://github.com/bwalker72956/testIonic2

App Code:
[app.zip](https://github.com/driftyco/ionic/files/157820/app.zip)

I tried the commands in both the app.ts file, page1.ts file and a button click event in page1.

I was able to get the config value to set for all environments by using the following command: 
config.set('testVariable','true');.  This accomplishes what I was originally trying to accomplish by allow a developer to set an application wide configuration value.  I was confused by the documentation since it stated that you should leave the first argument blank (ie. config.set('','testVariable','true');) instead of only passing 2 arguments.

When I tried to set it for a specific environment, it didn't work.  I also tried your command and it didn't work.  It now appears that the environment specific config.set does not work.

I have a more complete example of code in the GitHub where I put the config statement in the app constructor, page constructor and a button event on page1.  I also attached a zip file of the example code I was using.

**Comment by brandyscarney** [comment]
Thank you for the great code examples! I am able to see the problem now. :smile:

**Comment by brandyscarney** [comment]
Ok so the problem is the `set` function didn't have a proper type definition. Can you follow these steps to develop against Ionic locally and see if the problem is fixed for you? I tested it locally and I see it working, but I would like your confirmation. 

From `ionic` directory:

1. `gulp package build --typecheck`
2. `cd dist`
3. `npm link` (may require `sudo`)

From your app directory:

1. `npm link ionic-angular`
2. `ionic serve`

To remove the linked version of `ionic-angular` do `npm rm ionic-angular`, and then reinstall using `npm install ionic-angular`.

**Comment by bwalker72956** [comment]
I am not sure I am understanding the first set of tasks.  I tried the gulp command on both a Mac and Windows machine.

I navigated to:
 /usr/local/lib/node_modules/ionic-angular
 /usr/local/lib/node_modules/ionic

I also tried the ionic-angular directory in the app directory node_modules folder.
I then ran the gulp command, however, I am getting a "no gulp file found" error.

Do I need to install additional npm packages?  I did install gulp.

**Comment by brandyscarney** [comment]
Sorry. You'll have to clone this repository, then switch to the 2.0 branch, run `npm install` and then start with the above steps from within the `ionic` directory. If you'd rather wait to check it against the beta.3 release that's fine too.

**Comment by bwalker72956** [comment]
I cloned the project and gave it a try.  That fixed the issue.

Thank you.

**Comment by brandyscarney** [comment]
Great! Thank you! The fix will be in the next release. :smile:
