### ISSUE TITLE
refresher starts refreshing before release the screen

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5697]
#### Short description of the problem:

The ion-refresher starts refreshing before the user removes the finger from the screen.
#### What behavior are you expecting?
The refresher should start refreshing (animate) only after the user removes the finger.

**Steps to reproduce:**
1. pull down an ion-refresher and wait some seconds before release it.

**Ionic Version**:  2x

**Browser & Operating System**:
tested on Android

**Run `ionic info` from terminal/cmd prompt:**

```
 ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  Requiring external module ts-node/register
Gulp local:   CLI version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.10 
Node Version: v5.6.0


```

**Comment by adamdbradley** [comment]
This is by design and works the same as how the twitter app works. We could add in an option to not do that default however, would that work?

**Comment by BugsBunnyBR** [comment]
My android twitter app and my gmail only starts the update process (and the animation) when the finger leaves the screen, but I am totally ok with the option.

**Comment by maciejkoch** [comment]
@adamdbradley 
Are you going to add this feature? It can be helpful.
