### ISSUE TITLE
bug: navController.push wont fire

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5698]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x (beta2)</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When trying to push a new page via navController after having popped the same page via navController then pushed page won't display.

The page that is being popped and then pushed again is a tabbed page.

Here is the sample code:
`this._navController.pop({
     animate: false
}).then(() => {
     this._navController.push(TabsPage);
});`

If just simply pushing the same page again without trying to close the previous one then it works, but then also the old page underneath is not closed.

I also noticed that when using device back button on tabbed page then it won't pop the page as the back button in header does but actually minimizes the app and when resumes then the app is restarted.

Same logic used to work with beta1 release but not with tabbed page but with simple page.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
So you're animating out, and back in the exact same page? Does it work when you animate out Page1, and animate in Page2?

**Comment by ErkoKnoll** [comment]
Animating in a different page didn't work either. I even tried just pushing in the same page without popping. It kinda worked. It didn't open a new page, but did refresh the current page, except tabs header title. I kinda found out the problem also. I'm currently injecting NavController into one of the tabs content page and trying to do the things there but if I inject the NavController to root tabs page (the page that sets up tab contents) and using that NavController reference to pop and push then everything works as expected. 

I also noticed in beta1 that I had to do certain things in tabs root NavController rather than in tabbed page NavController because back then when I tried to pop and push then it only popped the currently selected tab's content page and pushed the new page into the selected tab which was weird. Resulting in double layer of tab selections.

The problem here seems to be that NavController does not retain the context within tabbed page. Not sure if it is a desired behavior.

**Comment by adamdbradley** [comment]
Would you be able to recreate this in a plunker? That would help us debug the issue, thanks: http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Comment by ErkoKnoll** [comment]
I think its not a bug but a feature since tabbed pages seem to have a NavController with a different context. And like I said, I managed to get around the issue when I did my navigation stuff from the root tab page rather than from content tab page.

**Comment by wli** [comment]
Just wanted to chime in here real quick - I've also encountered similar problems. This is my current workaround:
```ts
// in home.ts (the root page)

onPageWillEnter() {
  if (loggedIn) {
    // BlankPage is a really dirty hack to force ionic to trigger a nav. 
    // After upgrade to beta4, setPages doesn't really do anything.      
    this.nav.push(BlankPage);
    this.nav.setPages([{page: DashboardPage}]);
  }
}
```

BlankPage source:
```ts
import {NavController, Page} from 'ionic-angular';

 @Page({
   template: '<ion-content></ion-content>'
 })
 export class BlankPage {
 }
```

Version info:
```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175 
```

I'll spend a few minutes attempting to recreate a plunkr, but no guarantees.

**Comment by wli** [comment]
Sorry, can't seem to repro in a clean environment. It definitely used to work 2.0.0-beta.3 though

**Comment by jgw96** [comment]
@wli @ErkoKnoll Thanks for all the info! Is this still a valid issue? @wli You cant repro the issue anymore correct?

**Comment by wli** [comment]
@jgw96 I can repro in my application 100%, but unfortunately I can't get it to trigger in Plunkr.

**Comment by jgw96** [comment]
@wli Are you using beta.4? Could you run `ionic info` from in your app directory and post the output here? Thanks!

**Comment by wli** [comment]
```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by wli** [comment]
Here's a small bit of more info. You can see that `DashboardPage` was triggered (page created, bindings exist, but not rendered into the viewport), but the `HomePage` is still there.
![screen shot 2016-04-15 at 1 51 59 pm](https://cloud.githubusercontent.com/assets/649892/14574570/4d1806de-0311-11e6-924f-2de1d17efa27.png)

**Comment by wouterDumon** [comment]
I'm having a similar problem, the navController.push works using Ionic serve and gets forwarded to the second page. But when uploading the application to Ionic View ( ionic upload) the navigation doesn't work anymore. 
Page 1
`        alert("This fires");
        this.navController.push(NewsDetailPage, {
            item: item,
            icon:categoryIcon,
            name:categoryName
        });
        alert("This fires");`
Page 2
`export class NewsDetailPage {
    navController:NavController;
    navParams:NavParams;
    newsItem:NewsItem;
    categoryIcon:string;
    categoryName:string;
     constructor(navController:NavController,navParams:NavParams){
         alert("This does not fire in Ionic View");
}}`

**Comment by jgw96** [comment]
@wouterDumon @wli could you test this with beta.6? There was some weirdness with zone.js in beta.4 that may have been causing some issues.

**Comment by wouterDumon** [comment]
@jgw96  We just updated from beta.5 to .6 but still the same problem

**Comment by wli** [comment]
@jgw96 Still a problem in beta6.

**Comment by wli** [comment]
Here's my updated `info info`

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by jgw96** [comment]
@wli So i am trying to reproduce this in a clean, fresh project, but cant seem too. I read above that you cant seem to reproduce this in a fresh environment either, is that still the case?

**Comment by wli** [comment]
@jgw96 Correct, I can't repro in a clean environment (on plunkr at least). I haven't tried with a local build yet.

**Comment by jgw96** [comment]
@wli Would you mind trying it with a fresh local build when you get a chance and see if you still get the same issue? I cant seem to repro it locally.

**Comment by wli** [comment]
@jgw96 I'd love to, but I'm extremely busy this week. Might have to wait until next week.

**Comment by jgw96** [comment]
@wli No problem! I will keep this issue open for now.

**Comment by wouterDumon** [comment]
@jgw96 it indeed does not give a problem in a new project.
After updating our npm packages ( angular2 from .13 to .15) and recreating our view (wouldn't work with our original files but a complete copy paste did the trick), our problem was solved and the navController works again.

Thanks for the help!

**Comment by jgw96** [comment]
Great to hear @wouterDumon! Thanks for using Ionic!

**Comment by Sndan** [comment]
I am having the same issue . after I generated a new page it was working . however after adding all my params and everything else . nav.push stop firing !

> Ionic Framework Version: 2.0.0-beta.9
> Ionic CLI Version: 2.0.0-beta.31
> Ionic App Lib Version: 2.0.0-beta.17
> OS:
> Node Version: v6.2.2
