### ISSUE TITLE
doc: List the platforms returned by Platform

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5699]
#### Short description of the problem:
The different options returned by the Platform API would be useful.

#### What behavior are you expecting?
The [documentation](http://ionicframework.com/docs/v2/api/platform/Platform/) should detail the different possibilities returned. What are the strings to test for?

**Ionic Version**:  2.x

**Comment by adamdbradley** [comment]
Good call, thanks
