### ISSUE TITLE
[Request feature] ion-input autocomplete from datalist

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5702]
#### Short description of the problem:
This is a request feature, I would like to know if there is any plan to add a component like [this autocomplete](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist) in ionic2.

#### What behavior are you expecting?
Being able to give a list of values to ion-input and see that list as filtered suggestions for the ion-input field.

**Ionic Version**: 2.x

**Comment by adamdbradley** [comment]
Sorry but there is no plan to use datalist at this moment. Instead I would suggest using ion-select. Thanks

**Comment by BugsBunnyBR** [comment]
Ok, but an ion-select with 200 items would be not the best. I think I will open a new Page with a SeachBar and filter the list.
Thanks Adam!

**Comment by seanmavley** [comment]
Maybe it doesn't need to be a feature request, as it already exists.

         <ion-input list="browsers" name="browser" placeholder="Choose category">
              <ion-label>Browsers</ion-label>
            </ion-input>
            <datalist id="browsers">
                <option value="Internet Explorer"></option>
                <option value="Firefox"></option>
                <option value="Chrome"></option>
                <option value="Opera"></option>
                <option value="Safari"></option>
            </datalist>

You might have to do some css plumbing to get it to a visual design of your choose, but that's the barebones.

**Comment by BugsBunnyBR** [comment]
My point here is that, without the CSS it will not appear as something native.

**Comment by balachandra** [comment]
I have tried it and its causing the browser to go unresponsive and the display is not as smooth as native html component.

**Comment by jostse** [comment]
@seanmavley 
Can you share your css also ? it will be very helpful

**Comment by seanmavley** [comment]
@jostse I did not use css styling for my datalist. Ended up not using datalist for what I was working on, plus even if I did, wouldn't bother styling. 

After looking deeper into this select with datalist, I realized how kinda difficult it'll be to get a material select with CSS only. To achieve materialness, it would involve jQuery, which doesn't play well with ionic too.

I think it'll be better having datalist built natively into ionic.

**Comment by jostse** [comment]
@seanmavley
Thanks for the reply , can you recommend any good autocomplete plugin for ionic please?
just like the datalist can do.

**Comment by vnykSJ** [comment]
We are looking forward to this awesome feature in Ionic... Please add it. we are using third party plugins for perfect autocomplete feature.

**Comment by magdynamics** [comment]
@seanmavley it run perfect on chrome but not run on mobile like ios ,android.
