### ISSUE TITLE
bug: verticial scroll bar is visible by default

### ISSUE THREAD

**Issue by nawaz2013** [driftyco/ionic#5708]
**Type**: <span ionic-type>bug</span>

**Platform**: 
Cordova CLI: 5.4.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v5.5.0
Phone Model: ALE-L21
CPU: Octa-core 1.2 GHz

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>verticial scroll bar is visible by default on menu and empty tabs.

if one create list items, vertical scroll bar is visible in the background.

Steps

- create a new sidemenu ionic project <$ ionic start myApp sidemenu>
- install it on device <$ ionic run android>
- open menu and anyother tab, vertical scroll bar is visible (see images in comment below)

http://ionicframework.com/getting-started/</span>

<span is-issue-template></span>

**Comment by nawaz2013** [comment]
![screenshot_2016-03-04-10-27-07 1](https://cloud.githubusercontent.com/assets/4034293/13523154/f9f8ac62-e1f3-11e5-808b-3045c48d00e9.png)

![screenshot_2016-03-04-10-27-13 1](https://cloud.githubusercontent.com/assets/4034293/13523156/fe4fd39e-e1f3-11e5-9a91-629461b37cf4.png)

**Comment by nvigneux** [comment]
I have the same problem on Android, the scroll is already visible.

**Comment by johnfakeacc** [comment]
+1

**Comment by paulhickman-a365** [comment]
I fixed it by changing the overflow-y CSS style for the scroll-content tag to "auto" instead of "scroll". Not sure if this will have repercussions elsewhere though.

**Comment by GitGump** [comment]
@paulhickman-a365 that works for me now:

 ```
.overflow-scroll {
    overflow-y: auto;
}
```

**Comment by jgw96** [comment]
Hello all! Since this seems to be solved I am going to close this issue for now. Thanks for using Ionic!
