### ISSUE TITLE
ionic tabs content not showing IOS

### ISSUE THREAD

**Issue by arafay696** [driftyco/ionic#5711]
ionic tabs content not loading in ios simulator.

orders.html

 <ion-view view-title="Menü" id="select-screen">

  <ion-content class="select-screen-container">

    <ion-tabs class="tabs-striped tabs-top tabs-background-positive tabs-color-light order-tabs">

      <ion-tab href="" icon="item-daily">
        <ion-view>
          <div ng-include src="'templates/tab_daily.html'"></div>
        </ion-view>
      </ion-tab>

      <ion-tab href="" icon="item-weekly" ng-click="loadWeeklyMenus(1)">
        <ion-view>
          <div ng-include src="'templates/tab_weekly.html'"></div>
        </ion-view>
      </ion-tab>

      <ion-tab href="" icon="item-monthly" ng-click="loadWeeklyMenus(2)">
        <ion-view>
          <div ng-include src="'templates/tab_monthly.html'"></div>
        </ion-view>
      </ion-tab>

    </ion-tabs>

    </ion-content>

   </ion-view>

tab-daily.html

    <ion-content class="order-daily-content order-content">

    <div class="">
    <div class="order-day-content">
     
      <p class="cur-day">{{days[day]}}</p>
    </div>
    <div class="order-date-content">
      <i class="ion-chevron-left" ng-click="onPrevDay()"></i>
      
      <p id="date">{{formatedDay}}</p>
      <i class="ion-chevron-right" ng-click="onNextDay()"></i>
     </div>
    </div>
   <ion-spinner class="setSpinner" ng-show="isLoading"></ion-spinner>

  <div class="dailyMenus order-list padding-20">

     <div class="order-item" ng-repeat="menu in dailyMenus | orderBy : 'BillofFareDate'"     ng-if="!menu.LoadingMenus && dailyMenus.length > 0"
         ng-class='setClass(menu.BillofFareDate,menu.LastOrderDate,menu.hasMenu)'
         ng-click="goDescription('{{menu.glGUID}}','{{menu.BillofFareDate}}','{{menu.hasMenu}}')">

      <div>
        <p class="order-price my-font2 my-font-bold float-right" ng-if="menu.hasMenu">{{menu.Price |
          currency:'&euro;'}}</p>

        <p class="order-price my-font2 my-font-bold float-right no-menu-price" ng-if="!menu.hasMenu">&euro;0</p>

        <div class="order-name my-font2 my-font-bold">
          <span> {{menu.hasMenu ? menu.BillofFareDayGroupDescription : "Kein Speiseplan vorhanden"}}</span>
        </div>

        <div class="order-description my-font1">

          <span
            class="menuDescription">{{ menu.hasMenu ? menu.MenuDescription : "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"}}</span>
          <span class="showDate">{{menu.BillofFareDate | date:'dd.MM.yy'}}</span>
        </div>
      </div>

    </div>

    <div class="order-item" ng-if="dailyMenus.length <= 0">

      <div>
        <p class="order-price my-font2 my-font-bold float-right">&euro;0</p>

        <div class="order-name my-font2 my-font-bold">
          <span>Kein Speiseplan vorhanden</span>
        </div>

        <div class="order-description my-font1">

          <span class="menuDescription">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
          <span class="showDate">&nbsp;&nbsp;</span>
        </div>
      </div>

    </div>

    </div>
  </ion-content>

app.js

       .state('app.orders', {
        url: '/orders',
        views: {
          'menuContent': {
            templateUrl: 'templates/orders.html',
            controller: "OrderCtrl"
          }
        }
      })

**Browser & Operating System**: iOS / Android / Chrome
Chrome IOS

**Run `ionic info` from terminal/cmd prompt:**
ionic serve --lab

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you still experiencing this issue with the latest version of ionic?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by christianraj** [comment]
yes i face this issue

**Comment by compitDanielos** [comment]
+1

**Comment by christianraj** [comment]
my problem has been solved once i removed the <ion-content></ion-content> its the fact that we should not use tab tag inside content tag so try this way

**Comment by sookdong** [comment]
+1
