### ISSUE TITLE
ionic2 closes previous page half way

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic#5712]
#### Short description of the problem:

on click to next page, the slide closes half way, if we have map plugin enabled (native map)

![image](https://cloud.githubusercontent.com/assets/34341/13525180/5df0cae4-e1f7-11e5-84af-a71690bed6bc.png)

#### What behavior are you expecting?

The previous page should slide off the page completely. 

**Steps to reproduce:**
1. add ios platform
2. add google map native plugin https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map
3. on click navigate to map page.

```
goToNextPage()
{
      this.nav.push(MapPage);
}
```

**Ionic Version**:  2.x

**Browser & Operating System**: iOS (did not test on android, because cant get android up and running) 

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.1 Build version 7B91b 
```

**Comment by adamdbradley** [comment]
Ok, so normally the leaving page does stay viewable (display: block), and new page enters from there right and covers up the leaving page. Both of them stay display: block.

However, looks like that doesn't play nice with the native map plugin. I'll have to look to see why it's not sitting on top of the leaving view. Thanks for the report.

**Comment by adamdbradley** [comment]
Actually, is it a `z-index` issue? Each page is given a unique z-index, usually starting at `10`. Can you try messing with z-indexes and see if the native plugin can somehow go on top?

**Comment by iBasit** [comment]
I'm not sure if its z-index issue. the page slides half way and then stops. 

I can still try, do you want me to put z-index on map or the map page?

**Comment by adamdbradley** [comment]
It slides half way because that's what the leaving page does on iOS. If you inspect the elements on a normal page transition you'll see that's what the leaving page always does. What are the z-indexes on all of the ion-page elements?

**Comment by iBasit** [comment]
z-index looks fine as any other page. 

![image](https://cloud.githubusercontent.com/assets/34341/13567388/e22b95c0-e452-11e5-925c-6474ae8f32dd.png)

**Comment by iBasit** [comment]
z-index does not have any effect from inspector

**Comment by iBasit** [comment]
The only solution I can think of is hiding previous page on click and show that page again when clicking on back button.  

If I wanted to do that, how is it possible using ionic2?

**Comment by adamdbradley** [comment]
Right now it's not possible to completely hide the previous page. I'll try to replicate your issue and dig into this more, thanks

**Comment by iBasit** [comment]
I don't think pasting html here would help you much... else I would just paste it here.

I been trying to debug this issue all day. its mostly cause when native map initially gets loaded into dom (regardless of dom size or settings).

**Comment by jgog** [comment]
Hey, I too ran into this issue. The issue is acutally how the maps plugin work, check https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#how-does-the-plugin-work

Hope this helps.

**Comment by iBasit** [comment]
@jgog did you manage to fix it?

**Comment by jgog** [comment]
Not exactly but, I change the design a bit, I don't push the map page on top of the parent page now, I set it as a rootPage.

**Comment by iBasit** [comment]
well you can solve it by doing following, I don't recommend following solution because it will remove animation of slide completely, but its something. Once @adamdbradley  will solve this, then we can follow his advice..

```
ion-page.show-page {
  ion-content {
    transform: translateX(-100%) translateZ(0px) !important;
  }
}
ion-page.show-page:last-child {
  ion-content {
    transform: none !important;
  }
}
```

**Comment by jvoigt** [comment]
I think, I could resolve this by not using the injected NavController, but a parent(the root) of it via.
via IonivApp.getComponent('RootNav')

**Comment by adamdbradley** [comment]
Sorry but I believe this is not specifically a problem with how Ionic pages work, but rather how this particular cordova plugin works. I'd recommend listening to the lifecycle events and changing the visibility of the map.

**Comment by ungular** [comment]
The same issue navigating from LoginPage to HomePage & from HomePage to otherPage. 
`nextPage(){
  	this.nav.push(HomePage);
 }`
HomePage overlaps current page.
I tried the solutions suggested above but does not work for me.
If I use setRoot(HomePage), then I can not use nav.pop() to go back;
Other solution here?

**Comment by rhuldip** [comment]
Hi ungular...can you please elaborate how you solved this issue. I am facing the same issue in  most of my pages in both push and pop.

**Comment by rcjsuen** [comment]
@rhuldip If you have code that reproduces your problem, please share it here.

**Comment by rhuldip** [comment]
@rcjsuen i wont be able to share the code...but on looking closely i found that when i am doing navcontroller.push(NewsAlertOptions),the ion-page is created fine with z-index 10000 but after that i am calling a webservice to load all my data in ionViewDidEnter() method,only the service call is finished the ion-page z-index is decreased to 9998.PFA screenshot
![screen shot 2016-09-27 at 4 02 25 pm](https://cloud.githubusercontent.com/assets/12796087/18870024/7d9d809e-84cc-11e6-93ad-388c8eb5384a.png)
![screen shot 2016-09-27 at 4 02 25 pm](https://cloud.githubusercontent.com/assets/12796087/18870038/8b1852e4-84cc-11e6-94a2-c244164f1cc2.png)

**Comment by rcjsuen** [comment]
> i wont be able to share the code...but on looking closely i found that when i am doing navcontroller.push(NewsAlertOptions),the ion-page is created fine with z-index 10000 but after that i am calling a webservice to load all my data in ionViewDidEnter() method,once the service call is finished the ion-page z-index is decreased to 9998.PFA screenshot

Did you debug and track down the source of why the Z-index is being changed?

For your information, you may be interested in issue #8042. However, without any code, it's hard to know if your problem is the same problem or not.

**Comment by rhuldip** [comment]
@rcjsuen  i used debugger and i came to know that the issue is coming because of loading icon,but still i am not able to solve that..here is the code-

> ionViewDidEnter()
>    {
> 
>     this.getNewsAndAlertsObject = new GetNewsAndAlertsObject();
>     //alert("NewsalertoptionsPage="+this.navCtrl.length());
>     var myLoader =  this.commonUtility.getLoader('Getting News...');
>     myLoader.present();
>     this.getNewsAndAlertsObject.EID= "H122984";
>     this.getNewsAndAlertsObject.SBG ="HON CORP";
>     this.remedyService.getNewsAndAlerts(this.getNewsAndAlertsObject).subscribe(
>       data =>{
>           myLoader.dismiss().then(()=>{
>             console.log("success in getMyRequest"+JSON.stringify(data));
>             debugger
>             this.myNewsAndAlertsData = data;
>             debugger
>           })
>       },
>       err =>{
>           console.log("err block");
>           myLoader.dismiss();
>           console.log("Error in getMyRequest"+JSON.stringify(err));
>           console.log("1");
>           var errObj = err._body;
>           console.log("2");
>           errObj = JSON.parse(errObj);
>           console.log("3");
>           //alert("errObj = "+errObj);
>           console.log("4");
>           //alert("errObj1="+errObj.error);
>           if(errObj.error != undefined)
>           {
>             console.log("undefined block");
>             if(errObj.error == "invalid_token")
>             {
>               this.navCtrl.setRoot(LoginPage);
>             }
>             else
>             {
>               console.log("ivalid not block");
>               var myAlert= this.commonUtility.getAlert("Network Error", "Please try again later");
>               myAlert.present();
>             }
>           }
>           else
>           {
>             console.log("major else block");
>             var myAlert= this.commonUtility.getAlert("Network Error", "Please try again later");
>             myAlert.present();
>           }
>       },
>       () =>
>       {
>           console.log("Completion of getMyRequest");
>           //this.myLoadingCtrl.dismiss();
>       }
>     );
>    }

After the first debugger,the z-index is changing.

> import {LoadingController,AlertController} from "ionic-angular";
> import { Injectable } from '@angular/core';
> 
> @Injectable()
> export class CommonUtility
> {
>   constructor(public loadingCtrl: LoadingController,public alertCtrl: AlertController)
>   {
>     console.log("Creating object for CommonUtility");
>   }
>   getLoader(content)
>   {
>     return this.loadingCtrl.create({
>       content: content
>     });
>   }
>   getName()
>   {
>     return 'Rahul Deepppp!!!!';
>   }
>   getAlert(alertTitle, alertSubTitle)
>   {
>     let popUp = this.alertCtrl.create({
>       title: alertTitle,
>       subTitle: alertSubTitle,
>       buttons: [
>         {
>           text:'Dismiss',
>           role:'cancel',
>           handler: () =>
>           {
>             console.log("alert box dismiss clicked");
>             popUp.dismiss();
>           }
>         }
>       ]
>     });
>     popUp.present();
>     return popUp;
>   }
> }
> 

Also this is my commonUtility.ts which i am using to get loader.
