### ISSUE TITLE
doc: Missing brackets

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5713]
#### Short description of the problem:
Method brackets are missing in the code example. 

#### What behavior are you expecting?
On the [Id API component page](http://ionicframework.com/docs/v2/api/components/app/Id/), the code for ngAfterViewInit is missing an open and close brackets. 

```
ngAfterViewInit{ 
```

Should be 
```
ngAfterViewInit() {
```

**Ionic Version**:  2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! Should be fixed on the site soon. :smile:
