### ISSUE TITLE
doc: Missing parameters for Slides

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5714]
#### Short description of the problem:
Input properties for the Slides component not all defined. 

#### What behavior are you expecting?
The [Slides page](http://ionicframework.com/docs/v2/api/components/slides/Slides/) shows properties such as _loop_ but this is not defined under the Input Properties section. Are there any others which are maybe missing?

**Ionic Version**: 2.x

**Comment by brandyscarney** [comment]
These input properties shouldn't have been on the example. Any options you want to pass to the slides need to be passed in the `options` object. There is an open issue for fixing slides here: https://github.com/driftyco/ionic/issues/5508

Please add any feedback for slides there. Those properties will be removed from the site soon!
