### ISSUE TITLE
ion-content scroll="false" still wraps content in scroll elements

### ISSUE THREAD

**Issue by tomchiverton** [driftyco/ionic#5719]
#### Short description of the problem:
Unable to disable scrolling in popovers

#### What behavior are you expecting?
Even with scroll="false" the user can still drag to scroll in a popooer.

```
<ion-popover-view scoll="false">
    <ion-content scoll="false">
```

**Ionic Version**: 1.2.4

**Browser & Operating System**:  Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 4.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.4 LTS 
Node Version: v4.3.2
```

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
