### ISSUE TITLE
bug: DatePipe is not polyfilled on Safari for iOS

### ISSUE THREAD

**Issue by bitjson** [driftyco/ionic#5721]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>This may be outside the scope of what Ionic 2 should provide by default, but it looks like [Angular 2's DatePipe](https://angular.io/docs/ts/latest/api/common/DatePipe-class.html) relies on the [ECMAscript Internationalization API `Intl` global object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_Compatibility).

So an example like:
```js
{{ dateObj | date:'shortTime' }}   // output is '9:43 PM'
{{ dateObj | date }}               // output is 'Jun 15, 2015'
{{ dateObj | date:'medium' }}      // output is 'Jun 15, 2015, 9:43:11 PM'
{{ dateObj | date:'mmss' }}        // output is '43:11'
```

Will error in the most recent version of Safari for iOS (and Mac OS X):
```error
EXCEPTION: ReferenceError: Can't find variable: Intl in [{{dateObj | date:'shortTime'}}
```

If DataPipe is to be supported on iOS, it will have to be polyfilled with something like [Intl](https://www.npmjs.com/package/intl). Here's a similar issue: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/97</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Yes, sorry this looks like an ng2 issue: https://github.com/angular/angular/issues/7008

I think for the time being it would be best to not use the ng2's built-in DatePipe. Sorry that's not the best answer, but I would imagine this is a lower priority for ng2 to fix. If you need a solution today it might be best to write your own to fit your required date format.

**Comment by AdrianTeh** [comment]
@bitjson @adamdbradley I found a temp solution for this. Simply add the following to the head of your www/index.html file:

```
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
```

Source: https://github.com/andyearnshaw/Intl.js/

**Comment by tonyawad88** [comment]
@AdrianTeh Thank you so much Adrian. That did it for me. Temporarily I guess until the angular team fix it.

**Comment by finalxcode** [comment]
@AdrianTeh Thank you very much

**Comment by finalxcode** [comment]
@AdrianTeh Thank you very much

**Comment by mquadrat** [comment]
This should be added to FAQ section of the documentation.
