### ISSUE TITLE
Windows alert needs more padding

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5722]
Ours:

![alert-ours](https://cloud.githubusercontent.com/assets/6577830/13536877/3f7f9784-e210-11e5-9003-d7910bb945b6.png)

Native 

![alert-native](https://cloud.githubusercontent.com/assets/6577830/13536867/310fcb92-e210-11e5-95f4-6224d3c7fa42.png)

**Comment by bensperry** [comment]
also looking at the differences between the two, our button text isn't weighted heavy enough as the native buttons.
