### ISSUE TITLE
iOS + Ionic v1.2.4 + iPad

### ISSUE THREAD

**Issue by t0mm13b** [driftyco/ionic#5725]
When I build with ionic v1.2.4 targetting iOS, the project seems to reset the settings that targets the iPad. I did notice there was a bug in there where I had to set the project setting in XCode to iPad, the screen gets clipped and is not respecting the tablet's screen layout.

The generated `AppDelegate.m` contains the lines:

```objc
self.window.rootViewController = self.viewController;
[self.window makeKeyAndVisible];
``` 

That is in fact, incorrect. To remedy this,
```objc
// This fixes the clipping and ensures the app's screen layout is fully respecting the tablet layout
[self.window setBounds:[[UIScreen mainScreen] bounds]];
[self.window makeKeyAndVisible];
self.window.rootViewController = self.viewController;    
```
Notice the ordering of setting the `rootViewController`.

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the cli build process and not the framework i will be moving this issue over to the cli repo. Please feel free to continue on with this issue over there! Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#876
