### ISSUE TITLE
iframe BUG

### ISSUE THREAD

**Issue by gitHubLie** [driftyco/ionic#5727]
#### Short description of the problem:
    Use iframe click a label after scroll automatic to top  fro ios 9.2?
 help me !!!!

#### What behavior are you expecting?

.iframe-wrapper {
   position: fixed;
    -webkit-overflow-scrolling: touch;
    overflow: scroll;

    iframe {
      height: 100%;
      width: 100%;
    }
 }

  <ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper">
     <iframe id="targetFrame" data-tap-disabled="true" ng-src="{{myURL}}" style="opacity:0"></iframe>
  </ion-content>

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```

**Comment by rogercorrea** [comment]
Don't work for me.

Your system information:

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.3 (jessie) 
Node Version: v0.12.10

iOs 9.2.1 with Ionic View

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you still experiencing this issue?

**Comment by rogercorrea** [comment]
Yes.
I tested using Ionic View but I saw after that he don't support some plugins.
But I also tested on Android emulator and the iframe bug continued.

The iframe back to the beginning or even crashes when I touch on the page to scroll the screen.
Also not open this link inside the iframe page.

**Comment by jgw96** [comment]
Hey @rogercorrea ! Sorry, been thinking on this issue and i have a question. Is your iframe taking up the whole viewport?

**Comment by gitHubLie** [comment]
this is IONIC BUG ?  i will crazy.

**Comment by jgw96** [comment]
@gitHubLie Would you mind creating a plunker we can use to reproduce your issue? Also what version of ionic are you using?

**Comment by gitHubLie** [comment]
1.7.10

**Comment by gitHubLie** [comment]
@jgw96  ok ,you want close just new question?

**Comment by gitHubLie** [comment]
@jgw96     INOIC  1.7.10

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
