### ISSUE TITLE
Problem to run ionic command line

### ISSUE THREAD

**Issue by zhouhao27** [driftyco/ionic#5728]
Got the following error message:

> Error: Cannot read property 'indexOf' of null

When I was trying to run:

> ionic emulate ios
> cordova prepare
> ionic build

But **ionic server** is fine.

Tried both ionic-cli 1.7.14 and 2.0.0.beta19. Both the same problem.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#817
