### ISSUE TITLE
ionic-angular's info page on npmjs.com refers to the old ionic-framework package name

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic#5729]
#### Short description of the problem:
```
Usually, the only Javascript file required by the user is ionic.js, as everything from Ionic can be imported from this file:
  import {App, Page} from 'ionic-framework/ionic';
```
https://www.npmjs.com/package/ionic-angular

vs:

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#new-npm-module

**Ionic Version**: 2.x

**Comment by adamdbradley** [comment]
Thanks, yeah the next version should have the updated info. Sadly we can't update npm after it's published.
