### ISSUE TITLE
CheckBox Doesn’t Persist in iOS

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#573]
> It seems that hand-coded checkboxes are a bit flaky in iOS. Sometimes when they are checked, they stay checked. Sometimes, after being tapped, they just magically uncheck themselves. It is very inconsistent. I tested this about 5 times. 3 times they stayed checked. 2 times they did not stay checked. I sometimes felt it depended on whether or not I had tapped anywhere else on the screen.

http://forum.ionicframework.com/t/checkbox-doesnt-persist-in-ios/976

**Comment by louisdoe** [comment]
I am having this bug now. Does someone else too ?

```
$ ionic info

Your system information:

Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.1 Build version 7B91b 
```

**Comment by Razgort** [comment]
same issue here : 
ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.1.1 Build version 7B1005

**Comment by louisdoe** [comment]
Hi @Razgort I've posted another issue here : https://github.com/driftyco/ionic/issues/4698, FYI

**Comment by keyban** [comment]
yes i am getting this issue as well. everytime when i close my modal with a button (ng-click) on the bottom right corner the tab bar underneath the modal is clicked

Info:
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.2 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

is there some help around? getting crazy with that issue

**Comment by louisdoe** [comment]
Hi @keyban, can you please back this newer issue : [#4698](https://github.com/driftyco/ionic/issues/4698) ?

I hope they will look at it.

Thanks !
