### ISSUE TITLE
Issues when run on IOS Device(Tabs, Black Background, Big Header)

### ISSUE THREAD

**Issue by michelmob** [driftyco/ionic#5730]
My application is working when I'm running in IOS Emulator or Ionic Labs, but the first page is not rendering on device.

I'm using Ionic Tabs in my first page and I realize that if I change my rout to another page that is not using tabs It's work on my device.

Yesterday, I've tried to update some plugins and I got another crazy result: The application's first page has a short height, I mean that the application is not getting correct screen height.

My plugins
com.paypal.cordova.card.io 1.0.0 "CardIO"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-facebook4 1.6.3 "Facebook Connect"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS 

paste output from `ionic info` here
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by michelmob** [comment]
Hi guys!  

I know it is a very crazy issue but I found the root cause. The problem was that I had a splash.psd and the command Ionic resource was generating corrupted png files. 

I really don't know why, but this crazy files was causing a black background in IOS and an error on Android build.

Now I have to find out the problem with tabs.:)






after some builds and Ionic resource commands some corrupted png files was generated.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you still experiencing this issue?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
