### ISSUE TITLE
stacked labels do not play nice with item-right - Part 2

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#5731]
#### Short description of the problem:

This is a follow up on the closed issue with stacked labels [found here] (https://github.com/driftyco/ionic/issues/5319#event-578164730) with [this fix](https://github.com/driftyco/ionic/commit/74168278e46bb029e73f7db72d4d1d7f6abcec46)

#### What behavior are you expecting?

The item-left is vertically centered but the item-right is not. It shows on the bottom right corner in an `<ion-item>`

Wouldn't it make sense to place the right icons in the middle of the <ion-item> (vertically)? Just like the icon on the left? Take the markup below using an arrow-forward ionicon. It just doesn't look right to see the icon on the bottom right corner in iOS

```
<ion-item>
    <ion-icon name="leaf" item-left primary></ion-icon>
    <ion-label floating primary>First Name</ion-label>
    <ion-input type="text"></ion-input>
    <ion-icon name="arrow-forward" item-right primary></ion-icon>
</ion-item> 

```
**Steps to reproduce:**
1. Apply fix [found here](https://github.com/driftyco/ionic/commit/74168278e46bb029e73f7db72d4d1d7f6abcec46)
2. Insert sample markup above on a component
3. Ionic serve

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.1.1
```

**Comment by brandyscarney** [comment]
Ok I had to add a wrapper to labels/inputs in order for this to work but now you can have avatars, thumbnails, buttons, etc. aligned vertically next to stacked/floating labels. 

![screen shot 2016-03-09 at 2 52 26 pm](https://cloud.githubusercontent.com/assets/6577830/13648694/f9bce9da-e607-11e5-867c-39b592e3107f.png)

![screen shot 2016-03-09 at 3 04 56 pm](https://cloud.githubusercontent.com/assets/6577830/13648759/570e08c6-e608-11e5-9935-0e426e4fe49d.png)


If you wanted to align the button to the top you could add the following css:

```
align-self: flex-start;
```

and to the bottom using:

```
align-self: flex-end;
```

I'm wondering if there should be a simple way of doing this, similar to `ion-col`'s attributes:

```
&[top] {
  align-self: flex-start;
}
&[bottom] {
  align-self: flex-end;
}

&[center] {
  align-self: center;
}
&[stretch] {
  align-self: stretch;
}
&[baseline] {
  align-self: baseline;
}
```

Any thoughts? cc @adamdbradley

**Comment by brandyscarney** [comment]
Windows mode will default to aligning the `item-right` components to the bottom. Closing this since this is how item-left works.
