### ISSUE TITLE
Header disappears in tabs+sidemenu app when switching views

### ISSUE THREAD

**Issue by mmnaseri** [driftyco/ionic#5735]
#### Short description of the problem:

I have an app with tabs as the main navigation and on one of the pages I have a sidemenu. There are two tab pages, Search and Home, and on Home I have the sidemenu. When I start the app and switch to Search and then go back to Home, the header disappears. This _only happens the first time_.
#### What behavior are you expecting?

I expect the header to remain there consistently.

Here is a CodePen demonstrating the problem: http://codepen.io/mmnaseri/pen/wGKOWN

After the application loads (which takes you to Home immediately), you just need to navigate to Search and then go back to Home to see the header bar disappear.

**Ionic Version**: 1.2.4

**Browser & Operating System**: iOS and the desktop browsers

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by JosephMendez** [comment]
why we cannot combine menu and tabs, when i click on the menu, the tabs disappear.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#167
