### ISSUE TITLE
V2 Question: How to fully minify/uglify CSS/JS ?

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#5740]
I would like to uglify and compress my JS and CSS as much as possible after every build. Should I use the old `cordova-uglify` method like how it's done in version 1? or is there a better way to do it now?

**Ionic Version**: 1.x / 2.x
2.x

**Comment by adamdbradley** [comment]
Sorry but this question is better suited for the forum: https://forum.ionicframework.com/

However, it is on our roadmap to make it easy to minify and v2 builds, we should haven't completed it yet. Thanks
