### ISSUE TITLE
Statusbar odd when viewing hotspot

### ISSUE THREAD

**Issue by gslender** [driftyco/ionic#5742]
I'm not sure if this is related to #1257, but I'm seeing the behaviour whereby the app initially is pushed down, and then bounces back up again - so the hotspot or in-call additional status bar heigh is over the top of the Ionic header. I'm of the view that the header should drop down (most apps do this) and appear below the increased iOS standard status bar height. 

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by gslender** [comment]
![file 7-03-2016 4 02 58 pm](https://cloud.githubusercontent.com/assets/2344457/13561920/390ac8c2-e47e-11e5-8cf1-54b3f1d2e3a8.png)

**Comment by gslender** [comment]
![file 7-03-2016 4 02 58 pm](https://cloud.githubusercontent.com/assets/2344457/13561939/6de88156-e47e-11e5-9302-50335e3c7777.png)

**Comment by vhoxha08** [comment]
The same happened to me. You have probably set z-index in the css of your <ion-content>, that's what I did.

**Comment by gslender** [comment]
I can't see how z-index has anything to do with it... the status bar is a native control managed by iOS and the webview isn't reacting to the change in displayable height. 

I'm guessing the issue is a Cordova problem, but seeing the Ionic team have a good or better understanding of the integration than me, I figured they might be able to figure this out fairly easily.

**Comment by gslender** [comment]
Tried the starter-tabs project and same result. In-call or hotspot statusbar height change isn't reflected in the app. It actually bumps down, and then back up to the standard height - it is as if the resize is detected, but then ignored shortly after.

Not sure what else and would love to know if the version of Cordova is the problem. I'm reluctant to mess with the setup and risk a broken environment - maybe I could look at doing a Docker to test it???

**Comment by gslender** [comment]
OK, so tried with earlier version of Cordova 5.4.1 and Ionic 1.2.4 and the same result - when you run a starter app the statusbar bumps the view down and then it jumps back up again for in-call 

Something isn't right and probably wrong with Ionic events ???

**Comment by gslender** [comment]
Figured it out! I get normal behaviour with the earlier plugin cordova-plugin-statusbar v1.0.1

When I upgrade to v2.0.0 or later, the problem presents.

**Comment by jgw96** [comment]
This issue is related to https://github.com/driftyco/ionic/issues/5872

**Comment by jgw96** [comment]
Hello all, since this seems to be an issue with the cordova statusbar plugin and not ionic i will be closing this issue for now. Thanks for using Ionic!
