### ISSUE TITLE
Memory leak when switching between views

### ISSUE THREAD

**Issue by pyroon** [driftyco/ionic#5743]
When Switching between Tabs / Views, the used memory is increased by 0.3-0.7 MB each switch. 
This happens also, when the app content (ion-content) is completely blank and all functionalities within controller.js/app.js are commented out.

**Ionic Version**: 1.2.4
**Cordova version**: ios@3.9.2

**Browser & Operating System**: iOS

**Run `ionic info` from terminal/cmd prompt:**
```
ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by pyroon** [comment]
Hi
ionic info output is already in my previous post.
As an example you can just take an empty ionic app with tab navigation... When switching around through the views, the memory just increases

Thanks

**Comment by jgw96** [comment]
@pyroon, will have to do some testing of my own, Thanks! Are you using chrome dev tools to inspect memory usage?

**Comment by pyroon** [comment]
Yes, but you can see it best when running the app on the iOS simulator (e.g. ipad simulator) and inspecting the memory usage with xcode.

**Comment by jgw96** [comment]
@pyroon Are you using any external libraries?

**Comment by pyroon** [comment]
I use some plugins like those:

`"com.telerik.plugins.wkwebview": {
            "WKWEBVIEW_SERVER_PORT": "12344",
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        },
        "cordova-plugin-console": {
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        },
        "cordova-plugin-device": {
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        },
        "cordova-plugin-network-information": {
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        },
        "cordova-plugin-webserver": {
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        },
        "ionic-plugin-keyboard": {
            "PACKAGE_NAME": "ch.codeflair.floormanager"
        }`


additionally, I'm using ng-websocket

**Comment by danbucholtz** [comment]
Hi @pyroon,

Can you provide a codepen to recreate this?  Let's try to limit external dependencies so we can determine if this is an Ionic issue or a cordova issue.

Thanks,
Dan

**Comment by pyroon** [comment]
Hi
I think I found the issue. It's related to ng-repeat (https://github.com/angular/angular.js/issues/11169)
Cheers

**Comment by jgw96** [comment]
@pyroon so are you not having the memory leak anymore? Also if you can, could your provide a plunkr or codepen that demonstrates this issue? Thanks!

**Comment by pyroon** [comment]
Hi
we still have memory issues, but it looks like it's related to the angular ng-repeat memory problem. So no need to go more in detail for ionic. I think switching to ionic 2 asap would help to resolve this issue as the bug is fixed in angular 2
Cheers

**Comment by jgw96** [comment]
@pyroon sounds good then! Thanks for using ionic!

**Comment by dig1234** [comment]
@jgw96 @pyroon is this problem resolved ? it still exists on ionic2@beta.11

**Comment by cozzbie** [comment]
Seems to be an angular and not ionic issue @dig1234
