### ISSUE TITLE
Ionic serve doesn't work

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#5747]
#### Short description of the problem:

I am trying Ionic2.
I have installed it but when i run ionic serve to check the basic starter app it doesn't work.
If i check that app on the browser what i see is just a blank page.

I have then cloned the conference-app.
There were no error installing it except few npm warnings.
Ionic serve gives no result. Nothing happens.
If i check that app in the browser there is a blank page.

#### What behavior are you expecting?

I expect to run ionic serve properly and see the demo app in the browser.
With ionic 1 everything works fine.

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome / Firefox

```
Cordova CLI: 5.1.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.1 Build version 7B91b 
```

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#819
