### ISSUE TITLE
Header bar issue in Lenovo Tab

### ISSUE THREAD

**Issue by upendersanga** [driftyco/ionic#5750]
> Ionic `ion-header-bar` header not getting fixed in Lenovo tab.
> 
> Its scrolling through content..

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! We just need some more info from you so that we can help you with this issue better. Would you mind making a codepen for us so that we can try to repro the issue. Also, would you mind running `ionic info` and pasting the content here?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by upendersanga** [comment]
Thank for your interest to help me.

I have solved the issue.

If i have any farther issues, definitely i will inform to you.

On Wed, Mar 16, 2016 at 10:30 PM, Justin Willis <notifications@github.com>
wrote:

> Hello! Thanks for opening an issue with us! Since it has been a little
> while since there was any activity on this issue i will be closing it, but
> feel free to reopen this issue if needed!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/5750#issuecomment-197423929>
>



-- 
Thank You
Upender,
UI Developer,
cell : 7799501595.
