### ISSUE TITLE
Orientation change doesn't update collection-repeat

### ISSUE THREAD

**Issue by silicusanshuman** [driftyco/ionic#5753]
In ionic Application i used collection-repeat to display result on my view. I am using tabs template.

i am expecting that, whenever i will change the orientation the data into tab will take complete width.

**Steps to reproduce:**
1. In ionic, tabs template application, In first tab i have a huge list, generated using collection-repeat in portrait view.
2. now tap on second tab, go to landscape view.
3. Go to First tab, it will not stretch the list to complete width. 

please help me in solving this.

i already try nightly, item-collection-width, and resize() function of ionic scroll delegate.
```
insert any relevant code between the above and below backticks
```

**Ionic Version**: 1.x / 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
paste output from `ionic info` here
```

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! We just need a little more info from you so that we can better help you with this issue. Would you mind posting a codepen or just a little code that we could use to repro your issue? Also could you run `ionic info` and paste the contents here? Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!
