### ISSUE TITLE
transition on ionic2

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic#5754]
I was looking for documentation on `NavOptions`, but I can't find it. 

Can someone tell me how I remove transition or set transition, so `translateX` is set to `translateX(-100%)` from `translateX(-30%)`.

I want to hide previous page completely. due to some problem, it is causing page to show on top and z-index does not work changing it.  

```
export interface NavOptions {
    animate?: boolean;
    animation?: string;
    direction?: string;
    duration?: number;
    easing?: string;
    keyboardClose?: boolean;
    preload?: boolean;
    transitionDelay?: number;
    postLoad?: Function;
    progressAnimation?: boolean;
    climbNav?: boolean;
}
```

**Comment by adamdbradley** [comment]
Sorry, right now it's not possible to completely hide the previous page. Going to close this since it's similar to #5712, and I'll work to improve the NavOptions docs. Thanks

**Comment by matheo** [comment]
@adamdbradley anywhere to read what's the use of `climbNav`? TIA

**Comment by kz** [comment]
@adamdbradley Should I open an issue regarding the documentation of NavOptions? I too am trying to figure out what climbNav is. From https://github.com/driftyco/ionic/blob/4f52135c1335aba8dcc4dc82998bab0f063eabe3/src/components/nav/nav-controller-base.ts#L351, am I correct in assuming that setting climbNav to `false` prevents the page which fired nav.push from being navigated back to?

**Comment by jgw96** [comment]
Hello @matheo and @kz ! If you run into any issues with documentation you can always open an issue [here](https://github.com/driftyco/ionic-site). Thanks for using Ionic!
