### ISSUE TITLE
Gestures on-release get offset - on device event.gesture.srcEvent.layerX doesn't exist

### ISSUE THREAD

**Issue by mladenp** [driftyco/ionic#5757]
I am trying to get offsetX on element  on which  ionic gesture is used and i do get offsetX via `event.gesture.srcEvent.layerX` on desktop.

But `event.gesture.srcEvent.layerX` shows as undefined on device.

I am using Android 6 with Ionic version 1.1.1

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We just need a little more info from you so we can better help you with this issue. Would you mind posting a codepen or giving us a code sample we can use to repro this issue with? Also if you could run `ionic info` and paste the output here that would be great!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by mladenp** [comment]
WebView on device doesn't have the same offset properties as desktop browser, that's for sure.
So i calculated offset this way:
`var realOffset = gesture.touches[0].pageX - element.offsetLeft`
`gesture.touches[0].pageX` is offset from parent element and `element.offsetLeft` is offset from parent element to your element. So this works fine.
