### ISSUE TITLE
Text area not scrollable

### ISSUE THREAD

**Issue by mklilley** [driftyco/ionic#5769]
Hi,

I am using ionic 1.2.4.  I have a problem with a fixed size textarea.  When it is in focus i am no longer able to scroll the view.  I have inputs on the same view and I have no problem scrolling when they are in focus.

I am aware that this issue was raised before but seems to still be a problem.

Thanks for your input.

Matt

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! We just need a little more info on your issue so that we can better help you. Would you be able to provide a codepen or a repo that we could pull and test? Also, if you could run `ionic info` and paste the content here that would be great!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by mklilley** [comment]
Sorry it has taken a long time to get back to you.  The issue appears to be only an issue for iOS.  I am currently testing on iphone4s but with the latest ios 9.3.1. How to reproduce:

1) Run ionic start test tabs
2) Go to test directory and run ionic platform add ios
3) Add the following code to tab-dash.html just before the end of ion-content

```
<form>        
   <ion-input class="item item-input">
       <input placeholder="some input">
    </ion-input>
    <ion-input class="item item-input">
        <input placeholder="some other input">
     </ion-input>
   <ion-input class="item item-input">
      <textarea style="height:100px" placeholder="some text area"></textarea>
    </ion-input>
</form>
```

4) Run ionic build ios
5) Open project file in X-code and install onto iphone
6) Run app on iphone
7) Tap on textarea and try and scroll the view - you cannot
8) Tap on input and try and scroll the view - everything is fine

Thanks for your help,

Matt

**Comment by dhirajb1989** [comment]
Even I am facing the same problem ......

**Comment by mklilley** [comment]
I have since upgraded to ionic 1.3.1 and still have the same issue.  Any thoughts?
Thanks,

Matt

**Comment by daggeto** [comment]
Any news? Same for me.
