### ISSUE TITLE
Annotations not working

### ISSUE THREAD

**Issue by kunal95** [driftyco/ionic#5770]
When I use _constructor(platform:Platform)_ it gives following error:

![capture](https://cloud.githubusercontent.com/assets/5383258/13609489/34939902-e57f-11e5-8f97-e37ec85a8271.JPG)

**Comment by tlancina** [comment]
Hey there, thanks for the issue.  `constructor(platform: Platform)` is TypeScript syntax, so you won't be able to use it by default in the JavaScript starters.  To start a TypeScript project you can use the `--ts` flag: `ionic start myapp --v2 --ts`.

Going to close as not a bug, but if you're still having issues with the starters, I'd suggest asking around the forums for help: https://forum.ionicframework.com.
