### ISSUE TITLE
Some elements, including buttons, are not rendered correctly if they are inside components [v2]

### ISSUE THREAD

**Issue by e-oz** [driftyco/ionic#5771]
`<button>`, `<ion-input>`, `<ion-navbar>` and some other elements are not rendered if they are inside some custom element. It makes code-reuse impossible - we can't reuse code with components, so we can't reuse code at all. Only services and interfaces :) 

Please look at this codepen:
http://codepen.io/anon/pen/aNNmXj?editors=1010

I discovered it today, with the most fresh Ionic version, installed by `npm install -g ionic@beta`, so versions in codepen don't really matters, they just illustrate issue and show way to reproduce.

I really hope it's not by design and you'll fix this bug.

**Comment by matiboy** [comment]
I believe in custom components you just need to add `directives: [IONIC_DIRECTIVES]` to the `@Component` metadata and the buttons etc will render (mostly) correctly.

I forked your codepen:
http://codepen.io/anon/pen/ONNbJN?editors=1010

**Comment by e-oz** [comment]
@matiboy oh, really, what a noob I am. thank you!
