### ISSUE TITLE
How to move javascript files into the build folder? including customised folders and bower_component folder

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#5773]
#### Short description of the problem:
How to move javascript files into the build folder? including customised folders and bower_component folder

#### What behavior are you expecting?
Automatically move all javascript files into the build folder including customised folders and bower_component folder

**Steps to reproduce:**
1. bower install <package>
2. create customised javascript folders for external libraries 
3. ionic serve

```
ionic serve
```

**Ionic Version**: 2.0.0.beta.2

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by beerbohmdo** [comment]
Yes this would be nice.
I currently do this with a hook ...

```ts
var fs = require('fs'),
    path = require('path'),
    glob = require('glob');

[...]

    hooks: {
        beforeServe: function (argv) {
            var base = __dirname+'/node_modules/leaflet/dist/',
                target = __dirname+'/www/build/css/',
                copyFiles = [
                    '*.css',
                    '**/*.png',
                    '**/*.jpg',
                    '**/*.jpeg',
                    '**/*.gif'
                ];

            copyFiles.forEach(function (globPath) {
                glob(base + globPath, function (err, files) {
                    (files || []).forEach(function (p) {
                        var _basename = p.replace(new RegExp(base), ''),
                            _target = target + _basename;

                        fs.mkdir(path.dirname(_target), function () {
                            fs.createReadStream(p).pipe(fs.createWriteStream(_target));
                        });
                    });
                });
            });
        }
    }
```

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! This is a great question, but could be better answered at either our forum or slack channel. Here is a link to the forum: https://forum.ionicframework.com/ and here is a link to the slack channel: http://ionicworldwide.herokuapp.com/ Please feel free to continue the conversation on this question over there!
