### ISSUE TITLE
v2: Navigation is broken when dismissing Alert

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#5777]
#### Short description of the problem:
Navigation is broken when dismissing an alert that has been presented just before the root `Page` has been pushed.

#### What behavior are you expecting?
This should not happen:
<img width="424" alt="screen shot 2016-03-09 at 11 51 05" src="https://cloud.githubusercontent.com/assets/127379/13633061/3dab24f6-e5ed-11e5-89e2-3a36eed630b3.png">

**Steps to reproduce:**
1. Push Page component in a navbar
2. Press Cancel in the Alert

```ts
@Page({
    template: `<ion-content></ion-content>`
})
class Page {
    constructor(private nav: NavController) { }

    ngAfterViewInit() {
        this.showConfirm();
    }

    showConfirm() {
        const alert = Alert.create({
            title: `Location required`,
            buttons: [
                { text: 'Cancel', role: 'cancel', handler: () => this.cancelConfirm() },
                { text: 'Continue', handler: () => this.continueConfirm() }
            ]
        });
        this.nav.present(alert);
    };

    cancelConfirm() {
        console.log("alert CANCEL!!");
        this.nav.rootNav.pop().then(() => {
            this.nav.rootNav.pop();
        });
        return false;
    }

    continueConfirm() {
        console.log("alert continue");
        // this.requestPosition();
    }
}
```

**Ionic Version**:  2.0 beta 3

**Browser & Operating System**: Chrome  / OSX El Capitan

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by manucorporat** [comment]
![mar 09 2016 15 15](https://cloud.githubusercontent.com/assets/127379/13637862/db938732-e609-11e5-8354-28bbcd76cdde.gif)

**Comment by adamdbradley** [comment]
So there have been two recent fixes that may solve this:

https://github.com/driftyco/ionic/commit/24443c3b530c6b73e2aaa383e92e0eb465f384c6
https://github.com/driftyco/ionic/commit/1dd73aac7a76ca350ecb930660641ddfeae7f0cd

In this [alert example](https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/test/dismiss/index.ts#L60), it shows you can call `dismiss` within an alerts button handler, and when the dismiss is done transitioning you can then update the nav.

Please give it a shot and let us know if it fixes your issue, thanks

**Comment by manucorporat** [comment]
@adamdbradley I may want until next beta version is released, I don't want to mess with the project right now! I will give you an update about this issue.

**Comment by adamdbradley** [comment]
@manucorporat Is this still an issue with the latest beta?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue!
