### ISSUE TITLE
ionic2 library outside node_modules folder

### ISSUE THREAD

**Issue by iBasit** [driftyco/ionic#5778]
We are building ionic2 library, but outside the `node_modules` folder. 

Everything is fine with it.  The only issue we are getting is, `phpstorm` is not recognising the module by name. Which means on type hint, it shows error on the import line and any methods of the library is marked has red with errors.

If I put our module inside `node_modules` folder, then it resolve fine. But we don't want to put it there until we are completely done with it. 

![image](https://cloud.githubusercontent.com/assets/34341/13633814/595f1170-e5e9-11e5-89cd-3b5b70e0dafe.png)

It is probably `tsconfig.js` issue or `webpack`, But I'm not sure how to resolve this. Can you guide on this please.

**Comment by adamdbradley** [comment]
I'm sorry but this question is better asked on the forum, and not on our issue submission. Thanks

https://forum.ionicframework.com/
