### ISSUE TITLE
bug(refresher): not rendering in the correct place

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5780]
#### Short description of the problem:
Often I have screens which have a few ngIf's that hide and show content. In this case, an inbox screen which shows a list of messages. The refresher is rendering inside of the content, instead of behind the content as expected.

#### What behavior are you expecting?
Expected
```
<ion-content class='inbox-page'>
    <ion-refresher (refresh)="doRefresh($event)">
        <ion-refresher-content pullingText="Pull to refresh" refreshingText="Loading Messages...">
        </ion-refresher-content>
    </ion-refresher>

    <ion-list *ngIf='messages.length <= 0'>
        <img class='center' src='img/logo.png' style='width:40%'>
        <p style='text-align:center'>You have no messages.</p>
    </ion-list>
</ion-content>
```

![capture](https://cloud.githubusercontent.com/assets/2852839/13637894/6376af6e-e612-11e5-814c-bc66a520b00a.PNG)

If I have divs that hide and show depending on the state of the screen, the refresher does not render correctly.
![capture](https://cloud.githubusercontent.com/assets/2852839/13638007/e43f7b26-e612-11e5-8d1d-a3f527f277f2.PNG)

```
<ion-content class='inbox-page'>
        <div *ngIf='userState.allowCommunication'>
            <ion-refresher (refresh)="doRefresh($event)">
                <ion-refresher-content pullingText="Pull to refresh" refreshingText="Loading Messages...">
                </ion-refresher-content>
            </ion-refresher>

            <ion-list *ngIf='messages.length <= 0'>
                <img class='center' src='img/logo.png' style='width:40%'>
                <p style='text-align:center'>You have no messages.</p>
            </ion-list>

            <ion-list *ngIf='messages.length > 0'>
                <ion-item *ngFor='#msg of messages' (click)='showMessage(msg)'>
                    <ion-thumbnail item-left>
                        <img src="img/logo.png">
                    </ion-thumbnail>
                    <h2>{{msg.Subject}}</h2>
                    <p>{{msg.ReceivedDateValue}}</p>
                    <ion-icon name="medical" item-right primary class='unread-icon' [hidden]='msg.IsRead'></ion-icon>
                </ion-item>
            </ion-list>
        </div>
</ion-content>
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.7.0
```

**Comment by brandyscarney** [comment]
This might be related to the content projection: https://github.com/driftyco/ionic/issues/5060

**Comment by dylanvdmerwe** [comment]
@brandyscarney is there any workaround to get the ion-refresher to render correctly in the mean time?

**Comment by brandyscarney** [comment]
@dylanvdmerwe ok so looking into it more, you should be using the `enabled` property in order to decide whether or not to show the refresher. The refresher needs to be rendered before hiding it and when the `*ngIf` is on the refresher it doesn't get rendered properly. So to fix it you can use the following:

```
  <ion-refresher (refresh)="doRefresh($event)" [enabled]="userState.allowCommunication">
    <ion-refresher-content pullingText="Pull to refresh" refreshingText="Loading Messages...">
    </ion-refresher-content>
  </ion-refresher>
```

Going to close this as this is our recommended solution instead of using an `*ngIf`. Please let me know if this doesn't solve your problem.

**Comment by dylanvdmerwe** [comment]
Perfect thanks Brandy. I saw the documentation was updated as well - awesome!
