### ISSUE TITLE
rootNav is not a function

### ISSUE THREAD

**Issue by astopo** [driftyco/ionic#5783]
#### Short description of the problem:
[NavController documentation](http://ionicframework.com/docs/v2/api/components/nav/NavController/) is confusing. Trying to call `this.nav.rootNav()` on NavController instance throws an error.

```
Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: this.nav.rootNav is not a function
ORIGINAL STACKTRACE:
TypeError: this.nav.rootNav is not a function
```

#### What behavior are you expecting?
Expecting `rootNav()` to be a function. It is actually a property.

**Steps to reproduce:**
1. Create a root page, and a tabs page. 
2. In a tab page of the tabs, inject NavController.
3. Try to call rootNav() on the NavController instance of the tab page.

```
export class DashboardPage {
	static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }

  submitLogout() {
     // Trying to get rootNav here to get out of TabsPage and go to root nav page.
      this.nav.rootNav();
  }
}
```

Got it to work with:

```
export class DashboardPage {
	static get parameters() {
    return [[NavController]];
  }

  constructor(nav) {
    this.nav = nav;
  }

  submitLogout() {
      this.nav.rootNav.push(LoginPage);
  }
}
```
**Ionic Version**: 2.0.0-2beta

**Browser & Operating System**: Chrome

**Comment by adamdbradley** [comment]
Yeah you're absolutely right. We need to fix up our docs generation to handle this. Thanks

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-site#498
