### ISSUE TITLE
Error NDK Integration is deprecated in the current plugin.

### ISSUE THREAD

**Issue by gsanjeevkumar** [driftyco/ionic#5784]
#### Short description of the problem:
Error in gradle when building ioinic project after adding crosswalk plugin.

#### What behavior are you expecting?
Build normally

**Steps to reproduce:**
1. add crosswalk plugin to a basic ionic project
2. ionic prepare android 
3. ionic build android
4. open the /platforms/android folder with Android Stuido

```
`Error:(185, 0) Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.`

Ionic info ( output below )
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! As this bug is related to the ionic cli i am going to be moving this issue to that repo. Please feel free to continue this conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#837
