### ISSUE TITLE
nav.setRoot() leads to dead page

### ISSUE THREAD

**Issue by leifwells** [driftyco/ionic#5785]
#### Short description of the problem:
Like a lot of other people I've been putting together a simple sign-in app using Firebase social login. After you sign-in, the first page you navigate to via the menu causes the page to not load and the menu icon to disappear.

#### What behavior are you expecting?
Any time the menu is used to navigate the selected page should load.

**Steps to reproduce:**
1. Select "Sign In" from the menu
2. Select the Github option, approve the app, sign in. The ListPage shows.
3. Select "Getting Started" from the menu. The ListPage remains on screen, the menu button disappears.

**Ionic Version**: 1.x / 2.x
v2b3 (also v2b1 and v2b2)

Project below without the node_modules:
[ShoppingListIonic2.beta3.zip](https://github.com/driftyco/ionic/files/165933/ShoppingListIonic2.beta3.zip)

**Browser & Operating System**: iOS / Android / Chrome
Chrome, iOS, Android

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.6
Xcode version: Xcode 7.1 Build version 7B60
```

**Comment by damienadermann** [comment]
A work around is have two ion-navs in the main app. 1 for auth and 1 for the app.

```js
@App({
  template: `<div [ngSwitch]="authenticated">
    <ion-nav *ngSwitchWhen="true"  [root]="rootPage"></ion-nav>
    <ion-nav *ngSwitchWhen="false" [root]="authPage"></ion-nav>
  </div>`,
   ,...
});
```

**Comment by leifwells** [comment]
Sadly, doing that threw me into this mess:
[https://github.com/driftyco/ionic/issues/5175](https://github.com/driftyco/ionic/issues/5175)

**Comment by jgw96** [comment]
Hello all! Are you all still having this issue with the latest version of ionic 2? beta.6

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
