### ISSUE TITLE
feat(ts): prettier error messages

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5789]
#### Short description of the problem:
When compiling TypeScript, use the --pretty flag for the TypeScript compiler.

#### What behavior are you expecting?
See [here ](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#prettier-error-messages-from-tsc)for more information.

**Which Ionic Version?** 2.x

**Comment by tlancina** [comment]
As far as I can tell, this only works when using `tsc` and is not exposed to tooling: https://github.com/Microsoft/TypeScript/blob/68bdbe04e73fc4eb66d744a1a89bbd3baf162a87/src/compiler/tsc.ts#L129, so it doesn't work with webpack loaders or browserify plugins/transforms at the moment.

But I think it's possible for things like tsify to replicate the pretty output with the additional diagnostic information.

Going to close this as it's not an Ionic issue, but here's an issue for tsify you can track: https://github.com/TypeStrong/tsify/issues/123.
