### ISSUE TITLE
bug: ion-scroll zoom does not work.

### ISSUE THREAD

**Issue by dowsanjack** [driftyco/ionic#5790]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>On pinch to zoom the scroll container should zoom in, but that does not happen.

This was working on 1.2.1(http://codepen.io/ankitjain11/pen/LNVVdL/), but not working on 1.2.4(http://codepen.io/ankitjain11/pen/QNbbxX)

Please let me know, if, my implementation is wrong, or, if more information is required. 

Thanks,</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This bug also seems to happen on ionic v2: #5707

**Comment by dowsanjack** [comment]
#5676 #5707 #5701 #5790 -- All the related threads are closed. Is the bug resolved? Where do I find the resolution?

**Comment by orochies** [comment]
I have the same problem, no zooming work.

**android version:** 4.1 and above.
**Ionic Version:** 1.2.4

```
<ion-content class="has-header">
        <ion-scroll zooming="true" style="width: 100%; height: 100%">
            <img ng-src="{{image.src}}" />
        </ion-scroll>
    </ion-content>
```
Thanks...

**Comment by IamAdamJowett** [comment]
Seeing the same thing here on Android also, here are my details in case they help:

**Android**: 5.0
**Ionic**: 1.2.4
**Device**: Samsung S5

```
<ion-scroll min-zoom="1" zooming="true">
                    <div class="image-holder more" ng-if="activeSlide === $index">
                        {{scrub.pos}}
                        {{$index}}
                        <div class="image" ng-class="image-{{$index}}" ng-show="scrub.pos == $index" ng-repeat="img in episodeImages[$index] track by $index" style="background-image: url({{img}})"></div>
                    </div>
</ion-scroll>
```

**Comment by Misikir** [comment]
I got the same problem with 
Ionic, v1.2.4
android 4.1.1
```
 <ion-scroll zooming="true" direction="xy" style="width: 500px; height: 500px">
    <div style="width: 5000px; height: 5000px; background: url('img/eu.jpg') repeat"></div>
  </ion-scroll>
```

**Comment by qwerdy** [comment]
Had same problem, finally found the solution [here](https://github.com/saravmajestic/ionic/issues/34#issuecomment-183564051)

> It can be fixed by adding `overflow-scroll="false"` into `ion-scroll` tag.

Fixed example: http://codepen.io/anon/pen/grxMvQ

**Comment by jgw96** [comment]
@qwerdy Im glad a solution was found! Thanks everyone! If this solution does not fix your issue feel free to comment!

**Comment by corv89** [comment]
Thank you!

I think this should be added to the api docs on ion-scroll.

http://ionicframework.com/docs/api/directive/ionScroll/

**Comment by jacquesdev** [comment]
@jgw96 - could you please do what @corv89 suggested? It would help loads of people.

**Comment by guitarrist** [comment]
@qwerdy's solution worked fine for me!
However note that the zoom will not work if you are testing in the browser with **Shift + "mobile scroll"**.
Instead test the solution in your device to see it working.
