### ISSUE TITLE
Dropdown list "Tap" is not working on Blackberry

### ISSUE THREAD

**Issue by ankushgoyal27** [driftyco/ionic#5792]
Using Ionic framework, dropdown list is not opening on Tap. Dropdown list opens when we Tap, hold and drag.
If we, just use the pure angular framework then dropdown list opens on tap

Is there anything that Ionic is overriding the angular behaviour. If it is overriding could you guys please let me know.

Because of this, I am getting very critical issues.

Thanks.

**Comment by mhartington** [comment]
Hi there :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by ankushgoyal27** [comment]
Thanks Mike for reply, Here you go with the example of ionic dropdown.
<a href="http://codepen.io/anon/pen/reLyQz">codepen Ionic</a>

If we implement the dropdown using angular dependencies, then it is working fine.

Thanks,

**Comment by mhartington** [comment]
Are you seeing the same problems on Android or iOS? 
I do want to point out that we do not support blackberry, so this could be an isolated issue there.

**Comment by ankushgoyal27** [comment]
In Android and IOS, it is working as expected. Just to "Tap" on dropdown and it opens the list. 

This is only a blackberry issue. 

As we did some analysis and found if we comment the below line in ionic.js, then it resolves this issue. 

But, I am not sure how it will gonna impact the framework. Please advise

Changes 
1) Commented lines: 3026, 3027 and 3028, and added return true
2) Commented line: 2978

<addr>function tapHandleFocus(ele) {
  tapTouchFocusedInput = null;

  var triggerFocusIn = false;

  if (ele.tagName == 'SELECT') {
    // trick to force Android options to show up
    //triggerMouseEvent('mousedown', ele, 0, 0); // 3026
    //ele.focus && ele.focus();
    //triggerFocusIn = true;
    return true;
  } else if (tapActiveElement() === ele) {
    // already is the active element and has focus
    triggerFocusIn = true;

  } else if ((/^(input|textarea)$/i).test(ele.tagName) || ele.isContentEditable) {
    triggerFocusIn = true;
    ele.focus && ele.focus();
    ele.value = ele.value;
    if (tapEnabledTouchEvents) {
      tapTouchFocusedInput = ele;
    }

  } else {
    tapFocusOutActive();
  }

  if (triggerFocusIn) {
    tapActiveElement(ele);
    ionic.trigger('ionic.focusin', {
      target: ele
    }, true);
  }
}


function tapTouchEnd(e) {
  //console.log('touchend ' + Date.now());
  if (tapIgnoreEvent(e)) return;

  tapEnableTouchEvents();
  if (!tapHasPointerMoved(e)) {
    tapClick(e);

    if ((/^(select|option)$/i).test(e.target.tagName)) {
      //e.preventDefault();  // Line no: 2978, commented
    }
  }

  tapLastTouchTarget = e.target;
  tapTouchCancel();
}<addr>

**Comment by mhartington** [comment]
I'd rather not mess with any of that code since it tries to handle things between ios and android. 
Which blackberry device is this? Since it's only happening on blackberry, which we don't support, and not on ios or android, I think we can close this.
