### ISSUE TITLE
Side Menu on Right not Possible

### ISSUE THREAD

**Issue by cawoodm** [driftyco/ionic#5795]
#### Short description of the problem:
`<ion-side-menu side="right">` just causes menu to stop working (and still appear left). Clicking on the menu icon does nothing and there are no JS errors in the console (Chrome 47.0).

#### What behavior are you expecting?
I would expect the side menu to appear on the right and function.

**Which Ionic Version?** 1.x or 2.x
```
Cordova CLI: 6.0.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.2.6
```

## Code
```html
<ion-side-menus enable-menu-with-back-views="true">
    <ion-side-menu-content>
        <ion-nav-bar class="bar-stable">
            <ion-nav-back-button></ion-nav-back-button>
            <ion-nav-buttons side="left">
                <button class="button button-icon button-clear ion-navicon" menu-toggle="left"></button>
            </ion-nav-buttons>
        </ion-nav-bar>
        <ion-nav-view name="side-menu21"></ion-nav-view>
    </ion-side-menu-content>
    <ion-side-menu side="right">
        <ion-header-bar class="bar-stable">
            <div class="title">Quick Menu</div>
        </ion-header-bar>
        <ion-content padding="false" class="side-menu-left has-header">
            <ion-list>
                <ion-item ui-sref="quickMenu.home" menu-close="">Home</ion-item>
                <ion-item ui-sref="quickMenu.bPS" menu-close="">BPS</ion-item>
            </ion-list>
        </ion-content>
    </ion-side-menu>
</ion-side-menus>
```

**Comment by jgw96** [comment]
Hello! Thanks for posting your code, makes debugging alot easier! With your current setup the menu should open from the right, but you are correct that the menu button is not going to work, you should be able to swipe to the right though and it should open the menu. To get the menu button to toggle correct, and get the menu button on the right side of your view you need to change `<ion-nav-buttons side="left">` to `<ion-nav-buttons side="right">` and change `menu-toggle="left"` to `menu-toggle="right"`.  Here is a screenshot of an example i wrote up: 

![screen shot 2016-03-17 at 11 52 48 am](https://cloud.githubusercontent.com/assets/8823093/13854124/fa2459fe-ec37-11e5-80d5-c803fae380c4.png)

Please let me know if this doesn't work for you!

**Comment by SanjayYadav90** [comment]
Hi team,
I am working on ionic2 and wanted to slide from **Right to left**
I can align my toggle menu on right
_but have issue that it is not being slid from **right to left**_
each case it slide from **lift to right** only,

this is code-
```
<ion-side-menu side="right">
   <ion-header>
      <ion-navbar>
         <button menuToggle="right" item-right>
         <img src="img/more_than_256.png" width="20" height="20">
         </button>
         <ion-title>My Menu List</ion-title>
      </ion-navbar>
   </ion-header>
</ion-side-menu>
```

**Comment by kbala** [comment]
also change code like below in each page
`<button right ion-button menuToggle>`

**Comment by SanjayYadav90** [comment]
Thanks a lot @kbala ,
I thing that will also work for but I have not used it.
As I have asked this question a long back, so I have solved my issue and here is the code-

`<ion-menu [content]="content" side="right" class="side-menu">`

I have just just remove `<ion-side-menu>` tag with `<ion-menu>` and added one ionic tag as-

`side = "right"`

thats all, get my work done.

**Comment by gitdisrupt** [comment]
**The correct directives to set on a button in order to toggle a menu on the right side are as follows:**
`<button ion-button menuToggle="right" right>`
_whereas_ adding `right` just tells the button where to position itself.
_whereas_ adding `menuToggle="right"` tells the directive which menu to open, which has to exist, the menu should have the `side` directive and it should be set to `right` as follows:
`<ion-menu [content]="content" side="right">`

**Comment by RomanDraliuk** [comment]
Hi, need a help with the code how to ,
I am working on ionic3 and wanted to slide from Right to left now its left to right
<ion-navbar class="serachBar" >
    <button right ion-button    menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-searchbar    placeholder = "Enter text">
    </ion-searchbar>
  </ion-navbar>

**Comment by horcrux95** [comment]
@SanjayYadav90 Thanks for the solutions. Saved a lot of time.
