### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by chidinweke** [driftyco/ionic#5796]
**Note: for support questions, please use one of these channels:** 
![1error](https://cloud.githubusercontent.com/assets/7816720/13676375/e747158a-e6e5-11e5-8ffd-0ad3fe74a12e.png)

#### Short description of the problem:

I tried to install iconic on my system and i'm getting this error...see image for error.

Ho do i solve this

**Comment by BilelKrichen** [comment]
You must post this issue on this repository
https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! As this is an issue related to the ionic cli i am going to be moving this issue to that repo as it could be answered better over there. Please feel free to continue the conversation on this issue in that repo!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#836
