### ISSUE TITLE
CSS issues regarding ion-textarea

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#5800]
#### Short description of the problem:
We've been experiencing issues with ion-textarea and we're hoping someone can shed some light into the issue. This is our current situation:

We have a view with an ion-textarea element at the bottom of it. It is initially hidden, and the shown once a button is tapped.

When the user focuses into the textarea, the textarea moves to the top of the screen when they keyboard shows up. This is done by adding a padding at the bottom of the element. However, when we tap outside of that textarea, the keyboard hides but the fixed padding stays, thus leaving an empty space at the bottom of the page.

Another issue which might be related is that there is no way to hide the keyboard in iOS, even by tapping outside of the textarea. Is this a bug as well?

Thank you!

#### What behavior are you expecting?
Remove bottom padding after closing keyboard.
Also be able to close keyboard on iOS when tapping out of the ion-textarea.

**Steps to reproduce:**
I share with you the related post:
https://forum.ionicframework.com/t/css-issues-regarding-textarea/45919

Also an example of the issue:
http://codepen.io/anon/pen/GZZeov

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by ZiFFeL1992** [comment]
I don't know how to add android label as well :S

**Comment by jgw96** [comment]
Thanks for the detailed issue we really appreciate it! I would recommend asking about how to add labels on android either on our forum: https://forum.ionicframework.com/ or on our slack channel: http://ionicworldwide.herokuapp.com/.

**Comment by jgw96** [comment]
This may be the same issue as #5810

**Comment by Abdiliban** [comment]
#5302

**Comment by kalcheat** [comment]
I have the same bug on android. Ionic 2.0.0-beta.2. It's very annoying.

**Comment by bent0b0x** [comment]
Seeing this on iOS 1.7.14 as well

**Comment by EvanWillms** [comment]
Sounds like #5432 getting reported again.

**Comment by sathishskc77** [comment]
The keyboard is not hiding even when tapped outside of the text area. Android build is working fine, only iOS has this issue. Is there a fix for this?

**Comment by phoenixsachin** [comment]
i cant understand answers here, please give me the proper code how can i solve this problem ,keyboard is up screen and extra space is not going . page height increase when keyboard is open .please give me a proper code and answer.
