### ISSUE TITLE
disabling swipe back on modals

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#5801]
#### Short description of the problem:
How to disable swipe-back on a specific page? I want to use it when I use nav.push() but I dont want the page to be swipable when it is a modal (nav.present()) because it is animating downwards and I am swiping left to right and its very weird.

#### What behavior are you expecting?

**Steps to reproduce:**
1. make a modal and try to swipe back. The modal will animate downwards by swiping left to right

**Comment by jgw96** [comment]
Thanks for submitting an issue! I appreciate you opening an issue here but this is a question that i think would be better answered on our forum or on our slack channel. Here is the link to the forum: https://forum.ionicframework.com/ and here is the link to the slack channel: http://ionicworldwide.herokuapp.com/. Thanks!
