### ISSUE TITLE
HTML5 range input inside a modal does not slide/click/change value on iOS

### ISSUE THREAD

**Issue by astopo** [driftyco/ionic#5802]
#### Short description of the problem:
HTML5 range input inside a modal does not slide or click. Expected to be able to move the range slider to change the value. This specific to iOS - on a simulator - iPhone 6, iOS 9.2

**Steps to reproduce:**
1. Create a modal from a page.
2. Put a plain range input in the modal page template.

**Ionic Version** 2.0.0-2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Thanks for the detailed issue! Would you be able to provide some code (codepen, repo etc) so that we could easily repro your issue?

**Comment by astopo** [comment]
https://github.com/astopo/ionic-broken-range

**Comment by astopo** [comment]
^ I removed the side menu from the start app, because I saw that the range input is also broken on iOS if there is a side menu. So there is an example of a working on on a plain page, and a broken one inside a modal

**Comment by brandyscarney** [comment]
Thank you for the issue and the code example! I'm really sorry but at this time we are not going to be focusing on implementing the native range. We have an open issue to include a custom range slider here: https://github.com/driftyco/ionic/issues/5422 and we plan on completing that in beta.8. We will reevaluate supporting the native slider at that time. Sorry again! :blush:

**Comment by roysG** [comment]
any updates?

**Comment by shanesmith** [comment]
More here: https://github.com/driftyco/ionic-v1/issues/121
