### ISSUE TITLE
bug: template is getting reloaded 10-12 times & so the

### ISSUE THREAD

**Issue by luckyycool** [driftyco/ionic#5804]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

Template calls its functions in any template 10-12 times as u can check in the code link 

I have verified, controller is getting loaded only once not multiple times. Also, If I add more routes in app.js the number of print keeps increasing as well.

Issue demo: http://codepen.io/anon/pen/XXxxpM (check console in browser)

.controller('AuthSignUpCtrl', function($scope, $state) {
   var i=01;
   $scope.test = function() {
      console.log(i++);
   };
});

$stateProvider
    .state('login', {
      url: '/login1',
          templateUrl: 'templates/login.html',
          controller: 'AuthSignUpCtrl'
    });</span>

**Comment by jgw96** [comment]
Thanks for opening this issue and providing a codepen! Would you mind running `ionic info` and posting the output here please?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by luckyycool** [comment]
Your system information:

Cordova CLI: Not installed
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7
Node Version: v4.2.4
