### ISSUE TITLE
`gulp karma` will failed

### ISSUE THREAD

**Issue by liu1084** [driftyco/ionic#5808]
#### Short description of the problem:
When I enter `gulp karma` to make a test, errors happend

$ gulp karma
[18:44:28] Using gulpfile D:\work\ionic\gulpfile.js
[18:44:28] Starting 'karma'...
WARN [watcher]: Pattern "D:/work/ionic/js/utils/list.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 49.0.2623 (Windows 7 0.0.0)]: Connected on socket 4_Le0KX_nKy1Z3OgRx2h with id 65056368

ERROR [karma]: [TypeError: The header content contains invalid characters]
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ServerResponse.res.setHeader (D:\work\ionic\node_modules\connect\lib\patch.js:134:22)
    at Object.setNoCacheHeaders (D:\work\ionic\node_modules\karma\lib\middleware\common.js:76:12)
    at D:\work\ionic\node_modules\karma\lib\middleware\karma.js:109:18
    at D:\work\ionic\node_modules\karma\lib\middleware\common.js:63:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
[18:44:45] 'karma' errored after 17 s
[18:44:45] Error: 1
#### What behavior are you expecting?

what's wrong?

**Which Ionic Version?** 1.x or 2.x
version 1.2.4
from github clone

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
D:\work\ionic>ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.3.2

**Comment by jgw96** [comment]
Hello! Thanks for submitting an issue! As this issue is related to CLI issues i will be moving the issue over  to the ionic-cli repo. Please feel free to continue to conversation on this issue over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#835

**Comment by jgw96** [comment]
@liu1084 Hey! Are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue i will be closing it for now. Thanks for using ionic!
