### ISSUE TITLE
docs: Windows Phone documentation

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5812]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Would be nice to get started with wp platform, but there is no documentation as of yet how to properly set it up.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
What kind of docs are you looking for? If you start a new project from the command line it will have windows mode already included. If you have an existing project, you can follow the steps in the changelog to add the windows mode: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#windows-mode

or refer to the conference app commit: https://github.com/driftyco/ionic-conference-app/commit/304e2a49693d411458bc424028e86c7d6966416e

**Comment by ErkoKnoll** [comment]
I tried to add a cordova wp support by using "ionic platform add wp" but it didn't recognize the platform. I believe I was using Ionic CLI 2.0.0-beta19 when trying it out. Do I have to use cordova's own platform name which is wp8 or windows?

**Comment by brandyscarney** [comment]
Oh ok! So the platform name for ionic is the same as cordova: `windows`. To run your app on windows you will need a few things first, here is a tutorial for it: https://cordova.apache.org/docs/en/6.x/guide/platforms/win8/index.html

I do agree though that we need to add some documentation on how to build/run your apps on different platforms, so I am going to move this issue to the ionic-site repo. :smile:

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#500
