### ISSUE TITLE
Flebox dont work after ionic build android 

### ISSUE THREAD

**Issue by PterPmnta** [driftyco/ionic#5815]
I 'm trying d migrate an application but when compiling the styles applied to flebox not work.

System information

- Cordova CLI: 6.0.0

- Ionic CLI Version: 1.7.14

- Ionic App Lib Version: 0.7.0

- OS: Windows 10

- Node Version: v5.5.0

- Android Studio 1.5

Ionic lab

The error see now in ios dont show before

[https://cdn.discourse.org/ionicframework/uploads/default/optimized/3X/f/b/fb60542b58765727fb2c7eb0c5793d4070b6f6ce_1_690x343.jpg](url)

##HTML##

 <ion-content>
        
        <div id="login">
        
        <div class="logo-unicesar">
            <img src="img/logo2.png" class="">
        </div>

        <div class="list list-inset">

            <div class="text-center">
                <p>{{respuesta}}</p>
            </div>

            <label class="item item-input">
                <i class="icon ion-person placeholder-icon"></i>
                <input type="text" placeholder="Usuario">
            </label>

            <label class="item item-input">
                <i class="icon ion-key placeholder-icon"></i>
                <input type="password" placeholder="Contraseña">
            </label>

            <button class="button button-block button-balanced">
                INGRESAR
            </button>

        </div>
            
    </div>
        
    <div class="bar bar-footer bar-balanced">
        <div class="title">UNICESAR</div>
    </div>`

##CSS##

```
#login{
     height: 100%;
 }

.logo-unicesar{
     height: 40%;
     margin: auto;
     display: flex;
     display: -webkit-flex;
     justify-content: center;
     justify-content: 
     align-content: center;
     align-items: center;
 }

 .formulario{
      margin: auto;
      display: flex;
  }

 .text-center{
       margin: auto;
      display: flex;
      justify-content: center;
      align-items: center;    
  }

 .text-center p{
    height: 25px;
        padding-bottom: 5px;
        color: firebrick;
        font-weight: 500;
  }

```

Android View

[http://i.stack.imgur.com/c2ahT.png](url)

**Comment by jgw96** [comment]
@PterPmnta Hello! Are you still having this issue?

**Comment by PterPmnta** [comment]
Hi @jgw96 i solved this issue, add crosswalk to my project and work fine

**Comment by jgw96** [comment]
@PterPmnta Awesome great to hear! Thanks for using ionic!

**Comment by PterPmnta** [comment]
@jgw96 i love ionic is awesome
