### ISSUE TITLE
bug(ion-card) : border-bottom added to ion-item

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5817]
#### Short description of the problem:
When creating an ion-card within an ion-list, borders are added to the bottom of ion-item elements within the card.

#### What behavior are you expecting?
The following style should not be added:
![capture2](https://cloud.githubusercontent.com/assets/2852839/13715656/edc40ebe-e7de-11e5-924f-7486ea0d7eb2.PNG)

HTML
```
<ion-list>
     <div *ngFor='#prize of getPrizes()'>
                <ion-card>
                    <ion-item style='text-align:center; background: #fafafa'>
                        <p style='font-size:1.1em;'><b>{{prize.PositionText}}</b></p>
                    </ion-item>
                    <ion-card-content>
                        <img class='voucher-image center' [src]='prize.ImageUrl'>
                    </ion-card-content>
                    <ion-item style='text-align:center; background: #fafafa;'>
                        <p><b>{{prize.Title}}</b>!</p>
                    </ion-item>
                </ion-card>
            </div>
</ion-list>
```

![capture](https://cloud.githubusercontent.com/assets/2852839/13715670/089dd54e-e7df-11e5-9d64-5e8052f23159.PNG)

 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.7.0

**Comment by brandyscarney** [comment]
Why are you using an `ion-list`? That component is useful if you have a list of items, sliding items, and/or headers/dividers. I'd suggest removing the `ion-list` if you aren't using any of the above inside of it. You can also apply the `no-lines` attribute to the list to remove the borders. Closing as this isn't the intended use of a list, but let me know if you feel otherwise! Thanks!

Looking at your code, you can achieve what you'd like using this:

```
  <ion-card *ngFor='#prize of getPrizes()'>
    <ion-item style='text-align:center; background: #fafafa'>
      <p style='font-size:1.1em;'><b>{{prize.PositionText}}</b></p>
    </ion-item>
    <ion-card-content>
      <img class='voucher-image center' [src]='prize.ImageUrl'>
    </ion-card-content>
    <ion-item style='text-align:center; background: #fafafa;'>
      <p><b>{{prize.Title}}</b>!</p>
    </ion-item>
  </ion-card>
```
