### ISSUE TITLE
bug: Showing a page from inside of alert/modal onDismiss() blocks the UI

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic#5818]
#### Short description of the problem:
When a page is opened from inside of the `onDismiss()` handler of an alert or a modal the UI is blocked - visible but inaccessible (and it shows the root page instead of the desired one).

#### What behavior are you expecting?
The desired page should be displayed and the UI should be accessible/usable.

**Steps to reproduce:**
1. Open: https://plnkr.co/edit/CITM8fA3eoL2EEukyevB?p=preview
2. Follow the instructions in the demo environment.

```ts
// Partial code snippet, the full source code is in the demo.
@Page({
  template: `...`
})
export class HomePage {
  // Used to track the state of the user's session.
  isLoggedIn: boolean = false;
  // Used to switch between the alert and modal cases.
  isLoggingIn: boolean = false;
  
	constructor(private nav: NavController) {}
	
	login(callback?: Function) {
	  var modal = Modal.create(LoginPage);
		
		modal.onDismiss(() => {
		  this.isLoggedIn = true;
		  this.isLogginIn = false;
		  console.log('You are now logged in.');
  		if (callback != null) {
  			callback();
  		}
		});
		
		this.nav.present(modal);
	}
	
	logout() {
	  this.isLoggedIn = false;
	}
	
	submit() {
		if (!this.isLoggedIn) {
			var alert = Alert.create({
				title: 'Not logged in',
				message: 'Sign in to continue.',
				buttons: [
					{
						text: 'Cancel',
						role: 'cancel'
					},
					{
						text: 'Sign in',
						handler: () => {
						  this.isLoggingIn = true;
						  this.login(() => this.submit());
						}
					}
				]
			});
			
			alert.onDismiss(() => {
			  if (!this.isLoggingIn) {
			    this.nav.push(ErrorPage);
			  }
			});
			
			this.nav.present(alert);
		} else {
			this.nav.push(SubmitPage);
		}
	}
}
```

**Other information:** (e.g. related issues, suggestions how to fix, stackoverflow links, forum links, etc)
* Possibly related issues: #4968, #5095, [#5594](https://github.com/driftyco/ionic/issues/5594#issuecomment-190270727), #5799 
* Discussions: [Closing this modal when another opens](https://forum.ionicframework.com/t/closing-this-modal-when-another-opens/42719/5?u=iignatov), [Is there an event when an Alert is closed?](https://forum.ionicframework.com/t/is-there-an-event-when-an-alert-is-closed/46164/4?u=iignatov)
* Workaround: Using `setTimeout()` with `500ms` fixes the issues on my machine (however it doesn't seem to work on the demo Plnkr environment, but maybe I forgot to copy something there).

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by adamdbradley** [comment]
Thanks for the great bug report! So I think the fundamental problem was that onDismiss was getting called immediately, whereas it'd be better to call it after it has transitioned out. So of the two ways of doing it, where onDismiss is called immediately, or it's called after the transition, I think it's best in most cases where it should be called after the transition. Thanks for creating the issue!

**Comment by iignatov** [comment]
Sorry for the late reply! I wanted to test the fix to confirm if it works. I managed to apply the fix directly over my `beta.3` release and it works - now everything happens as expected without any workaround.

About how `onDismiss()` should be called - I totally agree that it should be called after the transition because the user of the component cannot determine when the transition is over. At the moment I can't think of use cases when the user wants to have the handler immediately upon `dismiss()` _(although such cases most probably exist)_ but even this can be done _(in some cases)_ by executing the required code directly before calling `dismiss()`. On the other side it's much more complicated for the user to execute something exactly after the alert/modal is closed, because the transition and its duration is an unknown and framework-specific detail.

Thank you for the hard work that you and the Ionic team are putting into this amazing framework!

**Comment by iignatov** [comment]
I just tested this with `beta.4` and I can confirm that the problem is fixed, thanks again!
