### ISSUE TITLE
Improve docs on selecting tabs

### ISSUE THREAD

**Issue by palidanx** [driftyco/ionic#5819]
#### Short description of the problem:
After you run the tabs tutorial `ionic starts projectName tabs --v2`, I eventually call `	this.nav.setRoot( HomePage );`.  The problem is it still shows the current tab as selected.

Is there a way to get access to tabs instance and call select?  I see something in line 230 at

https://github.com/driftyco/ionic/blob/2.0/ionic/components/tabs/tabs.ts

But am unsure how to retrieve it.

#### What behavior are you expecting?
The ability to set the current tab programatically (not just clicking on the tab).

**Which Ionic Version?** 1.x or 2.x
```
v2
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.4.1
```

**Comment by palidanx** [comment]
Sorry this isn't a bug.  This is how you are supposed to do it
```
Import {Page, NavController,NavParams, Storage, LocalStorage, ViewController, IonicApp} from 'ionic-angular';
import {CompaniesData} from '../../providers/companies-data';


@Page({
  templateUrl: 'build/pages/choose-church/choose-church.html',
})

export class ChooseChurchPage {
	static get parameters(){
		return [[IonicApp], [NavController], [NavParams], [CompaniesData], ];
	}

	 constructor( app, nav, navParams, companiesData, view) {
	 	console.log( "***Loading Choose Church Page!!")

	
		
	 	this.nav = nav;
		this.companies = [];		
		this.view = view;
		this.app = app;
		this.local = new Storage(LocalStorage);

		
		console.log( "getting tabs component");
		console.log( this.app );
	
		companiesData.list().subscribe(
			returnedData=>{this.companies = returnedData.companies;
		});

	}


	selectChurch(event, company) {		
		console.log( "***select church issued:"  + company.id)
		this.local.set( "company_id", company.id );

		console.log( this.app  );
		

		var tabs = this.app.getComponent('tabs')
		
		//console.log( tabs );
		tabs.select( 0 );

  	}
```

**Comment by palidanx** [comment]
Basically
* Import the IonicApp
* Be sure it is in the constructor
* Make sure tabs.html has an id
```

<ion-tabs id="tabs" preloadTabs="false" selectedIndex=0>  
  <ion-tab [root]="homeRoot" tabTitle="Home" tabIcon="home"></ion-tab>
  <ion-tab [root]="messagesRoot" tabTitle="Messages" tabIcon="mail"></ion-tab>
  <ion-tab [root]="eventsRoot" tabTitle="Events" tabIcon="cafe"></ion-tab> 
  <ion-tab [root]="moreInfoRoot" tabTitle="More Info" tabIcon="list"></ion-tab>
</ion-tabs>

```
get the component

**Comment by dylanvdmerwe** [comment]
Probably should be documented somewhere to assist people with this in the future.

**Comment by dylanvdmerwe** [comment]
Looks good to me!

**Comment by palidanx** [comment]
ditto.  Looks good to me too!

**Comment by brandyscarney** [comment]
I made some minor changes to the `Tabs` documentation, and added more info to the `Tab` docs. I'm going to close this, but if you see any issues let me know and I will fix them. Thanks again for the feedback!

**Tabs**: http://ionic-site-staging.herokuapp.com/docs/v2/api/components/tabs/Tabs/
**Tab**: http://ionic-site-staging.herokuapp.com/docs/v2/api/components/tabs/Tab/
