### ISSUE TITLE
bug: Alert disappears when opened from form's submit handler triggered by Enter

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic#5821]
#### Short description of the problem:
When opening an alert from inside of a form's submit handler, triggered by pressing `Enter`, the alert appears briefly (for less than 1sec) and then disappears.

#### What behavior are you expecting?
The alert should be displayed in the same way as when the form's submit handler is triggered by the `Submit` button, i.e. it should remain visible until it gets dismissed/closed by the user.

**Steps to reproduce:**
1. Open: https://plnkr.co/edit/VzUnAgZHIhw56IShTfaB?p=preview
2. Enter a value shorter than 5 characters and hit `Enter`.

> **NOTE:** Notice that when clicking the top `Submit` button (the one in the navbar) or the form's `Submit` button everything works fine.

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by adamdbradley** [comment]
Thanks for reporting this issue and providing a great plunkr! The fix I made was to ignore any and all events for 750ms after the alert has been created. The problem was the the form submit's keyup event was also running the alert's keyup event since it was immediately created. Please let us know how it goes, thanks!

**Comment by adamdbradley** [comment]
This fix is also related to alert's and the enter key: https://github.com/driftyco/ionic/commit/2000b1e94097409a138d449cfb73ecde2986fa00

**Comment by iignatov** [comment]
Thanks for the quick fix, I'll test it when the `beta.4` is released and will confirm if it works.

**Comment by iignatov** [comment]
I just tested this with `beta.4` and I can confirm that the problem is fixed, thanks!
