### ISSUE TITLE
ionic run android not relfecting changes on device

### ISSUE THREAD

**Issue by NathanVss** [driftyco/ionic#5822]
Hello everyone, I'm using v1.7.14.

Sometimes after correctly running ionic build android, and ionic run android the application keep the old JS/Css (...) files. 
So when this happens, even if a build and run multiple times the only solutions is to remove the app on the device and let ionic run re install it.
The problem is the same even if I close the application to.

Any solutions ? Thanks.

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#840
