### ISSUE TITLE
Custom icons for tabIcon

### ISSUE THREAD

**Issue by davyzhang** [driftyco/ionic#5823]
#### Short description of the problem:
For now I can use the default icon set from ionic, which is great, but I have some custom svg to display as tab icon. So can I display them directly as svg or I have to change them to a font ?

#### What behavior are you expecting?
I want to change some tab's icon with my own one

I can get there by a little bit hacky way like this:

```
.ion-ios-pulse:before {
    content: url('../images/icon-projects.svg') !important;
}

.ion-ios-pulse-outline:before {
    content: url('../images/icon-projects.svg') !important;
}

.ion-md-pulse:before {
    content: url('../images/icon-projects.svg') !important;
}

.ion-md-pulse-outline:before {
    content: url('../images/icon-projects.svg') !important;
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by davyzhang** [comment]
https://forum.ionicframework.com/t/anyway-to-custom-the-tabbars-icon-with-my-own-svg-file/46131

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this looks like it was taken care of on the forum i will be closing this issue for now. Thanks again!

**Comment by yanxiaojun617** [comment]
http://www.jianshu.com/p/f6488850b6a2
