### ISSUE TITLE
bug: Ionic beta not installing

### ISSUE THREAD

**Issue by thiagoaslima** [driftyco/ionic#5824]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>mbp-de-thiago:fatores4_i2 thiagoaslima$ ionic start ionic tutorial --v2 --verbose
Task setting: title=start, name=start, summary=Starts a new Ionic project in the specified PATH, [options]=any flags for the command, <PATH>=directory for the new project, [template]=Starter templates can either come from a named template, 
(ex: tabs, sidemenu, blank),
a Github repo, a Codepen url, or a local directory.
Codepen url, ex: http://codepen.io/ionic/pen/odqCz
Defaults to Ionic "tabs" starter template, --appname|-a=Human readable name for the app (Use quotes around the name), --id|-i=Package name for <widget id> config, ex: com.mycompany.myapp, title=Create a basic structure without Cordova requirements, boolean=true, title=Setup the project to use Sass CSS precompiling, boolean=true, title=List starter templates available, boolean=true, --io-app-id=The Ionic.io app ID to use, --template|-t=Project starter template, boolean=true, title=Start a Ionic v2 project, boolean=true, title=(with --v2 only) Use TypeScript in starter, --zip-file|-z=URL to download zipfile for starter template, module=./ionic/start, disableChangePwd=true
Utils.preprocessCliOptions _=[start, ionic, tutorial], no-cordova=false, w=false, sass=false, s=false, list=false, l=false, v2=true, v=false, typescript=false, -ts=false, verbose=true, $0=ionic

One awesome Ionic app coming right up...

The directory /Users/thiagoaslima/GitHub/fatores4_i2/ionic already exists.
Would you like to overwrite the directory with this new project?
(yes/no): yes

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tutorial/archive/master.zip
[=============================]  100%  0.0s
Installing Node Modules
Running exec command: npm install
Utils.fail Unable to run exec commandError: stderr maxBuffer exceeded. undefined
Utils.fail stack undefined
Utils.errorHandler is set, calling that now
Cli.Utils.errorHandler msg Unable to run exec commandError: stderr maxBuffer exceeded. string

Unable to run exec commandError: stderr maxBuffer exceeded. (CLI v2.0.0-beta.19)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Mavericks
Node Version: v4.2.1
Xcode version: Xcode 6.1.1 Build version 6A2008a</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic-cli#839
