### ISSUE TITLE
bug: $ionicScrollDelegate.scrollTo call with animate tr

### ISSUE THREAD

**Issue by vrfurl** [driftyco/ionic#5825]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.2.4</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When calling  $ionicScrollDelegate.scrollBottom(true)  the content is scrolled to the bottom however the <ion-content> element gains a new style element that looks like:

`<ion-content style="overflow: hidden">`

This causes the content of the scroll to become un scrollable.  If the same call is make with animation false: $ionicScrollDelegate.scrollBottom(false) the content is scrolled to the bottom and the content is still scrollable as expected and  no  style="overflow: hidden" has been added to the ion-content dom element.

I believe the issue appears to be caused by the addition of code in ionic.js for method scrollTo
lines: 7194 to 7219

```
  var oldOverflowX = self.el.style.overflowX;
  var oldOverflowY = self.el.style.overflowY;
  clearTimeout(self.__scrollToCleanupTimeout);
  self.__scrollToCleanupTimeout = setTimeout(function() {
    self.el.style.overflowX = oldOverflowX;
    self.el.style.overflowY = oldOverflowY;
  }, 500);

  self.el.style.overflowY = 'hidden';
  self.el.style.overflowX = 'hidden';

  animateScroll(top, left);

  function animateScroll(Y, X) {
    // scroll animation loop w/ easing
    // credit https://gist.github.com/dezinezync/5487119
    var start = Date.now(),
      duration = 250, //milliseconds
      fromY = self.el.scrollTop,
      fromX = self.el.scrollLeft;

    if (fromY === Y && fromX === X) {
      self.el.style.overflowX = oldOverflowX;
      self.el.style.overflowY = oldOverflowY;
      self.resize();
      return; /* Prevent scrolling to the Y point if already there */
    }
```

For whatever reason the overflow styles are not be reset to their old values....</span>

<span is-issue-template></span>

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8.1
Node Version: v0.12.7

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by vrfurl** [comment]
@jgw96 Yes.  I got around it by simply disabling animation on the scrollBottom call.  I haven't tried with the latest 1.3 release yet.  I will upgrade soon and give it another try and report back what I see as soon as I get a change.  
Thanks!

**Comment by matheusab** [comment]
It's also happening to me (1.2.4 and 1.3.1). Sometimes when the scrollTo() method is called, the overflow property of the scroll container is set to hidden, which disables scrolling.

**Comment by esase** [comment]
jgw96 when this trouble will be fixed?

**Comment by shaung** [comment]
Same issue here (v1.2.4). Is there any workaround about this?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#165
