### ISSUE TITLE
Action sheet button shortens when highlighted

### ISSUE THREAD

**Issue by aparajita** [driftyco/ionic#5828]
#### Short description of the problem:

In iOS look, when an action sheet button is in the highlighted state, it shortens by 1 or 2 px.

#### What behavior are you expecting?

The button should remain the same height when highlighted.

**Steps to reproduce:**
1. Go to http://ionicframework.com/docs/v2/components/#action-sheets
2. Click on "Show Action Sheet"
3. Click and hold down on the "Delete" button in the action sheet. When the button is highlighted, it shortens.
4. While still holding the mouse button down, move off the "Delete" button. When the button highlight is removed, the button goes back to its original height.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
Obviously seems to be a CSS issue. Doesn't occur in the other UI types (Android, Windows).

**Which Ionic Version?** 1.x or 2.x

2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Using the version on your web site.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I think this might be because the borders get removed when the button is :active on the ios theme. On android and windows there are no borders on the buttons in the action sheet, so this is why they don't look shorter when active on those platforms.

**Comment by aparajita** [comment]
That may be why it's happening, but it's clearly undesirable behavior. Why remove the border? It could just be changed to the highlight color.

**Comment by bensperry** [comment]
@aparajita This is what iOS native action sheet does. We are simply mimicking the native experience for action sheet.

**Comment by brandyscarney** [comment]
I'm not seeing this at all. Before clicking the height of the button is `57px`:

![screen shot 2016-03-17 at 2 27 26 pm](https://cloud.githubusercontent.com/assets/6577830/13856672/ae0b2ccc-ec4c-11e5-8872-a2ef7482463a.png)

with the `activated` class it is `58px` but it has `margin-top: -1px` so it really appears as `57px`:

![screen shot 2016-03-17 at 2 27 38 pm](https://cloud.githubusercontent.com/assets/6577830/13856690/c2ecb188-ec4c-11e5-907e-c5dcf9c032d0.png)

Putting them side by side:

![actionsheet](https://cloud.githubusercontent.com/assets/6577830/13856971/27a2b7ac-ec4e-11e5-962d-f7fc8febe202.png)

I'm going to close this issue because I don't see anything wrong with it, please let me know if we're misunderstanding you. :smile:

**Comment by aparajita** [comment]
There must be something wrong with the demo then, because I'm getting wrong behavior there. Alternate between these two screen shots, you can clearly see it move:

<img width="1440" alt="1-unhilited" src="https://cloud.githubusercontent.com/assets/22218/13858756/41fdf28a-ec3d-11e5-9292-9a4c153e1f31.png">
<img width="1440" alt="2-hilited" src="https://cloud.githubusercontent.com/assets/22218/13858757/4218b048-ec3d-11e5-9ffa-2796bce98f3d.png">

**Comment by manucorporat** [comment]
@brandyscarney I confirm this is a real issue. I created the PR for the improved action-sheet css and something is broken for safari in the last version.

Please reopen, I think I know what is going on.

**Comment by manucorporat** [comment]
I have a fix!

**Comment by manucorporat** [comment]
@brandyscarney @bensperry in safari the buttons have a non 0 margin (not sure why) this normalizes how the buttons are rendered in safari and chrome.

the change does not affect how it looks in my chrome.

https://github.com/driftyco/ionic/pull/5867

but please, merge it locally and verify it fixes it

**Comment by brandyscarney** [comment]
Thanks for the PR @manucorporat. We were looking in Chrome so that explains it! I'll take a look at it soon. :smile:

**Comment by aparajita** [comment]
@brandyscarney Sorry for not stating that it was in Safari at the beginning. I should have checked on Chrome myself.

**Comment by brandyscarney** [comment]
@aparajita It's fine! We really should be testing Safari more. Thanks for finding and reporting it! :smile:

**Comment by brandyscarney** [comment]
I merged the PR from @manucorporat. This will be fixed on the site once we release beta.4 and update the demos. 

Thanks again, everyone!
