### ISSUE TITLE
button-icon issue on click | Ionic v1

### ISSUE THREAD

**Issue by AdrienDC** [driftyco/ionic#5829]
http://codepen.io/anon/pen/BKLqZy

Hi, I've an issue with a button-icon click. On my android phone when I click on it, it stays black. With a normal button-color I don't have this issue.

Am I missing something?

Thanks

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!
