### ISSUE TITLE
$ionicLoading.hide() freezes all spinners

### ISSUE THREAD

**Issue by oskr** [driftyco/ionic#5831]
#### Short description of the problem:
In the android platform (have not tried other) when the $ionicLoading.hide is called it freezes all spinners animations in view

#### What behavior are you expecting?
I'm using a the **$ionicLoading** service the first time data is required and an **ionRefresher** to let user refresh the data when needed. The $ionicLoading works great but when the users pull to refresh the refresher's spinner animation is freezed.

Can check an example of this behavior on this [Pen](http://codepen.io/oscarmesa/pen/EKyrMr)

What is causing this behavior? check the **stop** method on the **$ionicRefresher** controller. The sentence `anim.stop = false;`, the stop member of anim is used by all animations, so if its false you get not animations at all.

**Which Ionic Version?** 1.x

System information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8.1
Node Version: v0.12.10

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by leoperez-dev** [comment]
I'm having this problem, any solutions?

**Comment by di445** [comment]
I know it sounds trivial but try uninstalling and reinstalling ionic its what i did and it worked

**Comment by leoperez-dev** [comment]
solved it updating from 1.2.4 to 1.3.1 thanks.
