### ISSUE TITLE
showWhen/hideWhen + [hidden]="" will fail

### ISSUE THREAD

**Issue by SP1966** [driftyco/ionic#5836]
#### Short description of the problem:
When showWhen or hideWhen are used in addition to the [hidden]="" directive the component will be displayed even on the platform that it should remain hidden on.

For example, if hideWhen="ios" is used on a FAB button the FAB will not initially display on iOS. But if I add [hidden]="showFAB" to the button and then toggle the showFAB value using a button on iOS the FAB will be shown once the showFAB value is toggled back to true.

#### What behavior are you expecting?
A component with either showWhen or hideWhen should ignore the [hidden]="" directive so it won't be shown on the wrong platform yet still allows the component to be toggled on the correct platform.

**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the next release `2.0.0-beta.5`. :smile:
