### ISSUE TITLE
refesher animation on android 5.0 device laggy and choppy

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#5840]
I have noticed the refresher animation to be very choppy and laggy on android 5.0 devices (possibly other versions, but I have only tested it on 5.0).

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to take a screencast from your android device and post it here?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
