### ISSUE TITLE
docs: weather aa

### ISSUE THREAD

**Issue by raushann100** [driftyco/ionic#5841]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>not getting any helpfull documentation</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#506
