### ISSUE TITLE
i had bug in ion-select

### ISSUE THREAD

**Issue by buiphu** [driftyco/ionic#5842]
` <ion-select [(ngModel)]="list_data" ngControl="list_data">
                <ion-option  *ngFor="#i of data" value="{{i.term_id}}">{{ i.name }}</ion-option>
            </ion-select>`

how set term_id ="1" defalut had checked

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
