### ISSUE TITLE
Using sidemenu template, no sidemenu

### ISSUE THREAD

**Issue by amandeepmittal** [driftyco/ionic#5843]
I installed `sidemenu` template as per Ionic framework documentation but the template on generating isn't creating any Javascript code for side menu to function in the `app.js` nor it is creating `ion-side-menus` tag itself in the `index.html`.
How can I resolve this? I am using `ionic-CLI`

**Comment by jgw96** [comment]
Thanks for submitting this issue! As this is more of an issue with the cli i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#846
