### ISSUE TITLE
Feature Request: clearCache() & clearHistory()

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#5847]
#### Short description of the problem:
After a user logs out, there is no Ionic2 equivalent of $ionicHistory.clearCache() and $ionicHistory.clearHistory().

**Which Ionic Version?**  2.x

**Comment by dylanvdmerwe** [comment]
On logout, why not just use [setRoot](http://ionicframework.com/docs/v2/api/components/nav/NavController/#setRoot) in order to clear everything out of cache and the back stack?

**Comment by djangojack** [comment]
@dylanvdmerwe 
setRoot worked perfectly. Thank you.

**Comment by coolara** [comment]
setRoot  ios  will  load rootPage four times？ why
