### ISSUE TITLE
bug: Push Navigation doesn't work on Android

### ISSUE THREAD

**Issue by wandera89** [driftyco/ionic#5852]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Th sample tutorial for v2 works when served locally, but fails when emulated on Cordova or built on my phone. https://www.youtube.com/watch?v=0ShxCrIhUmo</span>

<span is-issue-template></span>

**Comment by dylanvdmerwe** [comment]
Looks fine to me. What behavior are you expecting?

**Comment by mayowarexp** [comment]
I was expecting them to be separate pages. That's what I'm getting locally.

![pasted_image_at_2016_03_15_02_16_pm](https://cloud.githubusercontent.com/assets/17619606/13813981/d023b8da-eb5a-11e5-9ab2-18e62ec9442d.png)

**Comment by wandera89** [comment]
I was expecting an individual page as it does locally.

![pasted_image_at_2016_03_15_02_16_pm](https://cloud.githubusercontent.com/assets/945728/13814073/453d4db6-eb5b-11e5-9f7c-e4b886a2833a.png)

**Comment by jgw96** [comment]
@wandera89 Thanks for posting the video up, that helps! So from looking at your screenshot you put up an hour ago that is with ionic emulating ios. If your using chrome you can use the device emulation to emulate an android device and you will see the same page animations you see on your actual android device

**Comment by jgw96** [comment]
@wandera89 please let me know if that helps you!

**Comment by wandera89** [comment]
@jgw96 Thanks! That's such an odd behavior. I'll need to  rethink the navigation then.

**Comment by jgw96** [comment]
No problem! Its just Ionic changing itself to whichever device it thinks your on. The "default" is the ios theme for web, so on the web unless your specifically emulating an android or windows device using chrome you will see the ios theme. If you run an ionic app on android it will use the material design theme, and on a windows device it will use the new windows 10 mobile theme, and the ios theme on an ios device. If you would like to have the ios page transitions on every device (including android and windows 10 mobile) you can use config. Here is an example:
`
@App({
    template: "<ion-nav [root]="root"></ion-nav>",
    config: {
      pageTransition: 'ios',
    }
})
`

**Comment by wandera89** [comment]
@jgw96 Thanks for going into detail! Is it possible to use the default (In this case Material design transition) but actually have the page navigate? The iOS is changing pages, but the Android version is just appending to the current page. I like the slide from bottom transition but I want it to actually navigate to a new page.

**Comment by jgw96** [comment]
@wandera89 No problem at all! I think im misunderstanding what you mean by appending pages? The actual navigation is the same between all platforms, they all navigate to different views, the transition is the only thing thats different. If you check out the ios theme you will see the exact same behavior as your youtube video but just with a different transition. Hope i explained this well!

**Comment by wandera89** [comment]
@jgw96 Thanks Justin you're quite responsive! 
As you can see though from the video, the Android doesn't finish navigating. It looks like it starts but then stops after the content is displayed. The iOS version though has a different Item Details page.

**Comment by wandera89** [comment]
Never mind looks like there was an error in one of my pages that was causing this. Thanks Justin! @jgw96

**Comment by jgw96** [comment]
Awesome, im glad you were able to solve the issue. No problem! @wandera89  Continue to have fun with Ionic 2!
