### ISSUE TITLE
bug: App resets in background after a few hours

### ISSUE THREAD

**Issue by antonfire** [driftyco/ionic#5853]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When my app is in background in iOS for an extended period of time (3-4 hrs) it is killed by iOS and then results in the loss of all javascript variables and a kickback to the login screen when reopened, I was under the impression that it would sit in the suspended state indefinitely unless I was to force kill it or restart the phone. I don't need any background services and as such have not implemented the background plugin. Rather I just want it to reopen as it was left when paused. Is there a bug in my code or is this expected behaviour? Regards Anthony</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! With the way both ios, and android handle memory management it is definitely possible for the os to kill your app. If IOS starts to run out of ram (you have a bunch of apps running and your using them alot) it will start killing apps to free up ram. This is something that affects all apps running on your device, and not just ionic apps. I would recommend looking at how your favorite native apps deal with this and then implement something that makes sense for your Ionic app. Hopefully this helps!

**Comment by antonfire** [comment]
There is rather a large margin of available memory, circa 0.5gb out of a total of 2gb. The app tends to terminate regardless of other app usage which is rather minimal. I presume there to be a bigger issue. It seems to me there would be no requirement to kill it to free up memory.

**Comment by antonfire** [comment]
App uses a max of 130-140mb in full use. Less in background.

**Comment by patrickmcd** [comment]
Apps are suspended / terminated to preserve battery as well as for memory management. You'll need a [specific reason to keep it going in the background](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html).

**Comment by dylanvdmerwe** [comment]
This is not an ionic specific issue. Rather an "app" issue that is handled differently across different mobile operating systems.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by antonfire** [comment]
Ok thanks to you all for your prompt input and help. I will find a different work-around. Thanks again.

**Comment by jgw96** [comment]
No problem @antonfire !

**Comment by jlstr** [comment]
@antonfire Hello! I was wondering If you were able to solve this issue? One Ionic App I'm developing experiences the same problem is **some devices**. If you were able to find a solution to this problem I'd be incredibly happy to read about it. Thanks in advance!

**Comment by antonfire** [comment]
@jgw96 Hi this is expected behaviour with iOS, after a while the op system will kill the background process to free up memory. Options are to use local storage to hold data which is pulled back into js on resume or to use background plugin. https://github.com/katzer/cordova-plugin-background-mode

**Comment by viveksinha121** [comment]
What happens when app is killed by os in background and then user reopens it. Will the last state be preserved like in android ? Or app will be restarted from very beginning?

**Comment by antonfire** [comment]
Complete restart, granted permissions and such are retained. You will need to save any data to device to resume the previous state, assuming that is applicable to your app.
