### ISSUE TITLE
feat: Extension to Alert - Allow imgSrc to be provided

### ISSUE THREAD

**Issue by johnman** [driftyco/ionic#5854]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I wish to be able to use the alert but add inputs that allow a user to pick an option based on an img (this could be rendered by the avatar component or thumbnail or just an img tag...personally I've settled on thumbnail). This could be supported in the checkbox and radio button lists (e.g. picking an avatar, a background picture etc).</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Hi, thanks for the issue! Unfortunately we won't be adding this support to the Alert component. We recommend using a modal instead to achieve complex structures. We will be adding the ability to make a modal `inset` in issue https://github.com/driftyco/ionic/issues/5423.

Sorry and thanks again! :smile:
