### ISSUE TITLE
$ionicTabsDelegate.select doesn't work after $ionicHistory.goBack

### ISSUE THREAD

**Issue by roocster** [driftyco/ionic#5856]
#### Short description of the problem:

After returning to the screen with tabs using $ionicHistory.goBack(), the $ionicTabsDelegate.select() is not working

**Steps to reproduce:**
http://codepen.io/anon/pen/aNBPKZ?editors=1010
1. Click "Go to tabs" button
2. Select "Tab 02" tab
3. Click "Go to another state" button
4. Click "Go to state 2" button
5. Click "Go back (-2)" button
6. Select "Tab 01" tab nad then Select "Tab 02" tab
7. Repeat steps 3-5
8. Try to switch to "Subtab 02" tab - not working

We get the following warning:
_Delegate for handle "subtabs" could not find a corresponding element with delegate-handle="subtabs"! select() was not called!
Possible cause: If you are calling select() immediately, and your element with delegate-handle="subtabs" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to select() and try again._

**Other information:**
After calling the select() function, there is a call to instanceMethodCaller() function. When iterating on tab instances for tab instance that matches "subtabs" handle, the function "hasActiveScope" returns false value.

```
this._instances.forEach(function(instance) {
    if ((!handle || handle == instance.$$delegateHandle) && instance.$$filterFn(instance)) {
        foundInstancesCount++;
        var ret = instance[methodName].apply(instance, args);
        //Only return the value from the first call
        if (foundInstancesCount === 1) {
            returnValue = ret;
        }
    }
})
```

**Ionic Version:** 1.2.4

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#164
