### ISSUE TITLE
bug: "Select" doesn't work properly with filter

### ISSUE THREAD

**Issue by baplac** [driftyco/ionic#5857]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Code can be found here: http://codepen.io/baplac/pen/yOJLVZ
To reproduce the bug: Launch this code on either an android emulator or an android device. Change selected category from x to y (no problem yet). Then change selected category from y to z. The filter is applied but the selected category still appears to be y. 

This bug does not seem to happen when testing the code in a browser.
Note: if we change the category back to y after producing the bug, the bug will "disappear". Every following category change will work fine. This only happens the second time the category is changed.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#163
