### ISSUE TITLE
bug: Select is failed on dynamic update

### ISSUE THREAD

**Issue by VsevolodAstanov** [driftyco/ionic#5858]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hello, I'am using 1.2.4 ionic version.
How can I change select field dynamically using AJAX ($http).
To change select field based on AJAX response.
When I tried to change it - nothing was happened.
It works fine on the native angularJS.</span>

<a href="https://jsfiddle.net/VsevolodAstanov/n6mwy83y/13/" target="_blank">Example</a>
<span is-issue-template></span>

**Comment by VsevolodAstanov** [comment]
I found the solution. 
Here is Example

**Comment by jgw96** [comment]
@VsevolodAstanov Glad you found a solution!
