### ISSUE TITLE
bug: Alert from constructor breaks navigation

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#5859]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If open an alert from the constructor i need to use a timeout to let the transition happens, however that transition takes too long, i have to set a timeout before showing the alert with 800 ms or it breaks all navigation.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! For this to work correctly you actually want to open the alert in onPageDidEnter(). This is fired after the ui has loaded and everything is set up. You normally do not want to do any type of ui stuff (opening alerts, modals etc) in the constructor as the constructor is instantiated way before the ui is actually ready. Heres a sample i wrote up for you to reference: 

![screen shot 2016-03-16 at 11 14 58 am](https://cloud.githubusercontent.com/assets/8823093/13819662/64182e4c-eb68-11e5-8454-19b23ee22890.png)

**Comment by jgw96** [comment]
Let me know if this works for you! (:

**Comment by Luchillo** [comment]
It actually did, i was using `ngAfterViewInit()`, i guess i didn't saw that in the angular2 cheatsheet, is `onPageDidEnter()` exclusive of Ionic 2?

**Comment by jgw96** [comment]
Awesome! Yep `onPageDidEnter()` is an ionic thing. Did `ngAfterViewInit()` not work?

**Comment by manucorporat** [comment]
@jgw96 awesome! see issue here https://github.com/driftyco/ionic/issues/5777
that's for the workaround

**Comment by Luchillo** [comment]
Nop, it just reduced the amount needed from the timeout from 800ms to 500ms

**Comment by jgw96** [comment]
@manucorporat Awesome! @Luchillo ahh ok. As stated before `onPageDidEnter()` is gonna be what you want to use for any ui things that need to happen "onload". How are you guys liking ionic 2 so far?

**Comment by manucorporat** [comment]
>How are you guys liking ionic 2 so far?

@jgw96 it has transformed me from a JS hater to a TS lover ;)

seriously, you guys are doing an impressive effort to push the limits of the web! and I want to be part of that ;)

**Comment by jgw96** [comment]
@manucorporat Awesome man! Really appreciate the kind words! (;
