### ISSUE TITLE
ion-list and ion-item issue if trying to click ion-item

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#5863]
Say we have the following html:

`<ion-list>
<ion-item *ngFor="#item of items" [attr.id]="item.id"
{{item.fullname}}
</ion-item>
</ion-list>`

We just have a basic list which repeats some content. Now say we want to be able to click on the item and get the id of that ion-item (a very common thing to do). There is a problem if we want to do that. The area for the user to click is very small (green area of the attached image). If we click the green area the id will show, but if we click anywhere else on the item we cannot select the id. So it seems the CSS is blocking. Essentially if you want to put an event on the item you can, but if you click on the item the area to click has to be precise or it will not work. I think the CSS needs to be fixed.
![image](https://cloud.githubusercontent.com/assets/15883441/13836692/2ca1cf64-ebc1-11e5-8322-e1bbf617c8e2.png)

**Comment by brandyscarney** [comment]
Please use a `button` or `a` element for clickable items. There is a delay on items that are not buttons or anchor tags. From the [docs](http://ionicframework.com/docs/v2/api/components/item/Item/):

>Use `<ion-item>` for something that is only non-clickable text.
Use `<button ion-item>` for something that can be clicked/tapped. Typically this element will also have a (click) handler.
Use `<a ion-item>` for when the item needs to contain a href.

So you could write your list 

```
<ion-list> <button ion-item *ngFor="#item of items" [attr.id]="item.id" {{item.fullname}} </button> </ion-list>
```

or

```
<ion-list> <a ion-item *ngFor="#item of items" [attr.id]="item.id" {{item.fullname}} </a> </ion-list>
```

Let me know if this doesn't work for you and I can re-open. Thanks!
