### ISSUE TITLE
bug: Project specific icon and splash screen ignored

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5865]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When app is built then "resource" folder content is ignored and cordova overwrites resources in the APK with its own icons and splash screens. Actually the splash screen is blank but cordova still has some images in the "res" folder inside the APK.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! (: Would you mind posting this issue either to our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/)? Thanks! Also, besides this issue, are you liking Ionic 2 so far?

**Comment by ErkoKnoll** [comment]
I did post it in the slack too, will see if anyone picks it up. As for Ionic 2, I totally love it and also the support I've gotten from you guys.

**Comment by jgw96** [comment]
@ErkoKnoll Glad to hear! Somebody should be helping you out on slack soon! Im gonna go ahead and close this issue for now since it should be handled on slack, thanks again!
