### ISSUE TITLE
bug: event.unsubscribe is not working

### ISSUE THREAD

**Issue by eduardoroyer** [driftyco/ionic#5866]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>browser</span>

<span ionic-description>import {Page, Events} from 'ionic-angular';

@Page({
  templateUrl: 'build/pages/teste/teste.html'
})
export class Teste {
    private evento: Events;

    constructor(evento: Events) {        
        this.evento = evento;

        this.evento.subscribe('myevent', () => {
            this.execute();
        });
    }
    

    private execute() {
       this.evento.unsubscribe('myevent', ()=>{});
    }
    
}</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you getting an error of some kind? And if so can you post it here?

**Comment by eduardoroyer** [comment]
Hello @jgw96 

The problem is that doesn't matter if unsubscribe is called, the event is still registered.
To resolve this I've to do this ```this.evento._channels = [];```

**Comment by skycocker** [comment]
@jgw96 same problem here, testing in latest stable Chrome on OS X. `unsubscribe` with handler returns `false`. Without providing the second argument everything works fine (but then you detach every handler when you need only one detached).

**Comment by dylanvdmerwe** [comment]
@eduardoroyer because the anonymous methods in the subscribe and unsubscribe are not referencing the same thing. Does something like this work:

```
	constructor(private evento: Events) {        
		this.evento = evento;

		this.evento.subscribe('myevent', this.myEvent);
	}

	private execute() {
	   this.evento.unsubscribe('myevent', this.myEvent);
	}
	
	myEvent() {
		this.execute();
	}
```

**Comment by jgw96** [comment]
Hello! Thanks for all the info! After reviewing this issue I've realized that this is not an ionic issue, but an issue with the rxjs implementation of observables. I would recommend searching through their documentation on the proper way to unsubscribe. Thanks!

**Comment by wodka** [comment]
@jgw96 I cannot figure out how this is supposed to work. even with the suggestions of named methods it's not working... can you tell me how you resolved it?

**Comment by jgw96** [comment]
Hey @wodka ! I would recommend asking on the rxjs repo(https://github.com/Reactive-Extensions/RxJS) as they will be able to give you a better and more official answer than i can. Thanks!
