### ISSUE TITLE
Bug:`$ionicModal` view bypass/dismissed unintended by `$ionicPopup`

### ISSUE THREAD

**Issue by DazChong** [driftyco/ionic#5869]
#### Short description of the problem:

Bug:`$ionicModal` view bypass/dismissed unintended by `$ionicPopup`
#### What behavior are you expecting?

`$ionicModal` remain until intended dismiss

**Steps to reproduce:**
1. create a new `sidemenu` template project
2. `$scope.doLogin()` function to call `$ionicPopup.alert` 
3. after the alert show up, just after clicked OK to dismiss the popup, quickly click again anywhere on screen while the popup still in dismiss transition, and the modal will dismiss altogether.

```
  $scope.doLogin = function() {
    $ionicPopup.alert({
        title: 'Title'
    });
  };
```

**Which Ionic Version?** 1.x or 2.x

1.x

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#162
