### ISSUE TITLE
Bug: Toggle In-Call Status Bar on iOS 9.2

### ISSUE THREAD

**Issue by zMADCATz** [driftyco/ionic#5872]
#### Short description of the problem:
When Toggle In-Call Status Bar on iOS 9.2 
App not resize view

#### What behavior are you expecting?
resize view when to fit the window space

**Steps to reproduce:**
1. ionic start app blank (use blank template)
2. ionic build ios
3. ionic run ios (Emulator)
4. use command + Y (Toggle In-Call Status Bar)

**Other information:** 
Gif Image: http://i.giphy.com/QGqo80f93cvgQ.gif
 

**Which Ionic Version?** 1.x or 2.x
1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.1.2
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello! Would you mind telling me what version of the cordova-plugin-statusbar your using?

**Comment by gslender** [comment]
This issue is related to #5742 and I found a workaround by using v1.0.1 of the cordova-plugin-statusbar

**Comment by moelover** [comment]
I use cordova-plugin-statusbar 2.1.2 "StatusBar"

**Comment by jgw96** [comment]
@zMADCATz at this time this issue seems to be related to that version of the statusbar plugin. Would you mind testing with an earlier version (1.0.1) and seeing if you get the same issue? Thanks!

**Comment by zMADCATz** [comment]
@jgw96 test on cordova-plugin-statusbar@1.0.1 it work !!

**Comment by kevinswartz** [comment]
Update: I still see this same behavior with version 2.1.3.  Reverting to version 1.0.1 still fixes the problem.  
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.1.0
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello all! Since this seems to be an issue with the cordova statusbar plugin and not Ionic I will be closing this issue. Thanks for using Ionic!
