### ISSUE TITLE
ionic for android device $cookies does not work!

### ISSUE THREAD

**Issue by gluttonman** [driftyco/ionic#5873]
#### description of the problem:
    i use ngCookies store data that store 30 days! 
    it works on ios and browser,but does not work on android device!  

**Which Ionic Version?** Ionic, v1.2.4  and  ngCookies, v1.4.3

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. What version of Android are you testing on? Also would you be able to provide a plunkr, codepen or repo that we could use to repro the issue on our devices?

**Comment by gluttonman** [comment]
@jgw96 the version of  my emulation  is 4.4.4 and  my device is also 4.4.4! the code is very simple. i use ngCookies module and use method  $cookies.putObject("key",{id:1}) and $cookies.getObject("key")

**Comment by jgw96** [comment]
@gluttonman After doing some testing of my own on a Nexus 7 running Android 6.0.1, a Nexus 6 running the Android N dev preview and a Moto X 2014 running 5.1 ngCookies does appear to have some issues on android in Cordova apps that i will need to look further into. Is there a specific reason that you are using cookies and not something like localStorage?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!

**Comment by gluttonman** [comment]
@jgw96 Thank you for help me! the cookies can store data by expire date but localStorage can not do it . so  i choose to use cookies.

**Comment by chen1203** [comment]
Hi, I also got this problem when I try to use $cookies on android version 5.1+, it's not working.
When I run it on the browser (with ionic serve) it's working but on android it isn't.
Do you have any ideas ?
Tnx!

**Comment by gluttonman** [comment]
@chen1203  it is because that chrome broswer not support  cookies that load local file. the app fix on device is like the broswer load local file, so the cookies is disable.

**Comment by chen1203** [comment]
@gluttonman - So what is the solution ? What is the best/recommended way to store some data when the app is close? (for example - to login)

**Comment by chen1203** [comment]
I used localStorage and it works both on browser and android.
@gluttonman - thanks.
