### ISSUE TITLE
bug: SqlStorage does not work on Windows 10

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5874]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>windows 10</span>

<span ionic-description>When trying to use SqlStorage following error is thrown:

TypeError: Object doesn't support property or method 'openDatabase'
        at SqlStorage...</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @ErkoKnoll ! Do you happen to have the Cordova-sqlite plugin installed?

**Comment by ErkoKnoll** [comment]
Hi,

Since it worked fine on Android I thought I had it installed but after checking I noticed I didn't have it. So I installed ext plugin not core since in core the Windows platform is not supported. Exact version is: cordova-sqlite-ext 0.8.4.

While building the project I had 2 problems. First it complained about the precompiled headers, I had to disable them manually in plugin project using VS and then it tried to look up compiled plugin files in different folder, had to copy them manually to a folder where the app project was looking them for. If I build the project from CLI "cordova build windows -- --appx=uap" it throws the following errors. The first "error" actually should be a warning but no other reason is given why it fails eventually.
`
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microso
ft.AppXPackage.Targets(4388,5): error APPX0505: The processor architecture of y
our project 'neutral' doesn’t match the processor architecture 'x86' of the ref
erenced project 'SQLite3.UWP'. Change the targeted processor architectures to a
lign between your project and its references. [C:\VS\AddressBookAppClient\platf
orms\windows\CordovaApp.Windows10.jsproj]
ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild
 with args: C:\VS\AddressBookAppClient\platforms\windows\CordovaApp.Windows10.js
proj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configura
tion=debug,/p:Platform=anycpu
ERROR building one of the platforms: Error: cmd: Command failed with exit code 2

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 2`

However if I built from generated VS project it succeeded and I managed to deploy it to emulator. But then I received the following logs and error while trying to read from a database.

`
adding proxy for SQLitePlugin
cordova.js (926,9)

OPEN database: __ionicstorage
SQLitePlugin.js (174,7)

open db name: __ionicstorage at full path: C:\Data\Users\DefApps\AppData\Local\Packages\com.playtech.addressbook_bzbj8h50hftv4\LocalState\__ionicstorage
sqlite-proxy.js (35,4)

new transaction is waiting for open operation
SQLitePlugin.js (105,9)

OPEN database: __ionicstorage failed, aborting any pending transactions
SQLitePlugin.js (195,11)

Could not open database
SQLitePlugin.js (82,7)

"Error: Invalid database handle
   
	at newSQLError (ms-appx-web://com.playtech.addressbook/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:25:7)
   
	at SQLitePlugin.prototype.abortAllPendingTransactions (ms-appx-web://com.playtech.addressbook/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:157:9)
   
	at Anonymous function (ms-appx-web://com.playtech.addressbook/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js:200:11)
   
	at cordova.callbackFromNative (ms-appx-web://com.playtech.addressbook/www/cordova.js:293:38)
   
	at cordova.callbackError (ms-appx-web://com.playtech.addressbook/www/cordova.js:280:9)
   
	at onError (ms-appx-web://com.playtech.addressbook/www/cordova.js:894:17)
   
	at Anonymous function (ms-appx-web://com.playtech.addressbook/www/plugins/cordova-sqlite-ext/src/windows/sqlite-proxy.js:95:5)"`

In few days I will try to remote deploy a real device and check if the same errors occur. Has anyone in Ionic team succeeded using SqlStorage in Windows 10 and did they had to go through the same hassle in order to get this far?

**Comment by ErkoKnoll** [comment]
Tested it on a real Windows 10 device, problem remained: "Invalid database handle".

**Comment by jworsman** [comment]
Here's what I did to get the cordova-sqlite-ext plugin working on Windows (and Android as well as using ionic serve):

First I added the windows platform and cordova-sqlite-ext plugin via ionic CLI.
`ionic plugin add cordova-sqlite-ext`
`ionic platform add windows`

It is my understanding that SQLite3 will not work with AnyCPU regardless of what settings you change so you'll need to open: %projectdir%\platforms\windows\cordova\lib\build.js and change (line 189~)
`config.buildArchs = archs ? archs.split(' ') : ['AnyCPU'];`
to 
`config.buildArchs = archs ? archs.split(' ') : ['x86'];`
or x64/ARM depending on what you need.... this will change the architecture used when running ionic build / ionic run windows.

Open up `%projectdirectory%\plugins\cordova-sqlite-ext\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.sln` in VS2015. Right click the SQLite3.UWP (Universal Windows) project and click properties. In the Configurations drop down menu select All Configurations and the Platforms drop down menu select All Platforms. Then under C/C++ -> Precompiled Headers change Precompiled Header to "Not Using Precompiled Headers". Click OK, save all, then right click the SQLite3.UWP project and click build. Now would be a good time to repeat this step for Debug and Release for all architectures you plan to deploy to.

Then open up `%projectdirectory%\platforms\windows\CordovaApp.sln` in Visual Studio and right click the CordovaApp.Windows10 project and click properties. In the properties window click Configuration Manager. For both Release and Debug change the Active Solution to x86/x64/ARM. To be thorough I went through and removed AnyCPU entirely from all projects / build configurations via the drop down menus <edit> option - probably not necessary though. Make sure you do a save all here (CTRL+SHIFT+S) to save the changes you made to the VS project. You should now be able to build / run via the Ionic CLI:
`ionic run windows'

I think that's everything but I'm tired so if you continue to get errors post them here and I'll check back tomorrow.

Good Luck!
-Jonathan

**Comment by ErkoKnoll** [comment]
I was missing JS architecture change and when changing it to x86 everything started to work. Thanks.

**Comment by jgw96** [comment]
Wow @jworsman, Awesome information! @ErkoKnoll, did this answer fix your issue?

**Comment by ErkoKnoll** [comment]
@jgw96 yes it did, I had to go through similar steps, not that thoroughly though. 3 important steps are the following: make sure the C++ precompiled headers are turned, build.js target should not be "anycpu" and in the compiled project your compilation target should also match the one set in build.js.

**Comment by jgw96** [comment]
Awesome, thanks for all the information! Since your issue has now been resolved i will now close this issue. And, thanks for using Ionic!

**Comment by Artfloriani** [comment]
I am having this issue after the Windows anniversary update. I tried following the steps mentioned by @jworsman but still no luck. Even with `ionic serve` and trying to open on edge gives the following error:

`ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'openDatabase'`

Any other ideas?
