### ISSUE TITLE
Segment can be very slow on ios

### ISSUE THREAD

**Issue by davyzhang** [driftyco/ionic#5875]
Forum link https://forum.ionicframework.com/t/poor-performance-with-ionic-2-tabs-and-segments-on-ios/45886/4

#### Short description of the problem:
Segment buttons in tabs ionic2 project can be very slow to switch on iphone

#### What behavior are you expecting?
smoothly just like tabs

**Steps to reproduce:**
1. ionic start tabs --v2 --ts
2. add segment with two tabs
3. build & run on iphone

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x beta

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by brandyscarney** [comment]
What devices does this happen on? Does it occur on emulators, too? I'm not able to reproduce this using a new project (with the steps given) or the conference app. Tested on an iPhone 6 emulator running iOS 9.2.

**Comment by davyzhang** [comment]
I tested this app on iPhone4s with ios 9.2, but on the forum, some dev
claim it will happen on emulator too.

I will try to cook up some minimal example for this one.
2016年3月22日 上午5:41，"Brandy Carney" <notifications@github.com>写道：

**Comment by davyzhang** [comment]
@brandyscarney I can not reproduce this problem on other devices except my iphone4s, so I guess the problem is caused by old hardware. Thanks for your attention, Sorry for the false alarm.

**Comment by ginsleepy** [comment]
It's still slow on iphone 6 

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by dgroh** [comment]
It's very slow on iPhone 6

**Comment by patwaswapnil** [comment]
same problem here on iPad. Using ionic 2.2.0.. :(

**Comment by mikamboo** [comment]
Hello,

Same problem for me with segments component on ios.
