### ISSUE TITLE
Cannot re-export name that is not defined in the module.

### ISSUE THREAD

**Issue by fairsayan** [driftyco/ionic#5876]
#### Short description of the problem:
I just created a new project in Ionic 2 typescript and sidemenu as template
Everytime I run `ionic serve` I receive this not blocking error:

> ERROR in [default] /.../scaffold-ionic/node_modules/angular2/src/facade/promise.d.ts:1:9 
> Cannot re-export name that is not defined in the module.

**Steps to reproduce:**
1. ionic start scaffold-ionic sidemenu --v2 --ts
2. ionic serve

**Here the complete flow**

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md|wp).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

√ HTML copied to www/build
√ Sass compilation complete
√ Fonts copied to www/build/fonts

Hash: 4d8afbdec4626d5a657f
Version: webpack 1.12.11
Time: 5935ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.73 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 363 hidden modules

ERROR in [default] /.../scaffold-ionic/node_modules/angular2/src/facade/promise.d.ts:1:9 
Cannot re-export name that is not defined in the module.

√ Webpack complete

∆ Starting dev server.

√ Running live reload server: http://localhost:35729
√ Running dev server:  http://localhost:8100
√ Watching: 0=www/build/**/*.html, 1=www/build/**/*.js, 2=www/build/**/*.css
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue has more to do with our CLI than the actual framework I will be moving this issue over to that repo. Please feel free to continue the conversation there! Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#849
