### ISSUE TITLE
Screen jumps up on Android when hiding status bar

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ionic#5877]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

When opening an image in a full screen modal, we are hiding the status bar using the status bar plugin as follows:

```
if (window.StatusBar) {
                        if (window.StatusBar.isVisible) {
                            window.StatusBar.hide();
                        }
                    }
```

On Android, the whole screen jumps up shortly to fill the new available space as the status bar isn't there anymore before it is resized to the new screen dimensions without the status bar.

This actually happens when not opening any modal window. Just hiding the status causes the screen to jump.
#### What behaviour are you expecting?

There should be no jumping of the screen.

**Steps to reproduce:**
1. In any Ionic app using the status bar plugin, hide the status bar and you will see the issue described
2. 
3. 

```
if (window.StatusBar) {
                        if (window.StatusBar.isVisible) {
                            window.StatusBar.hide();
                        }
                    }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I'made a video of this issue occuring on a Samsung Galaxy S6 which can be downloaded from here: https://dl.dropboxusercontent.com/u/22622235/android_status_bar.mp4

The app is using Crosswalk, animatable preference set to false. 

**Which Ionic Version?** 1.x or 2.x
1.2.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by tooraje** [comment]
I have the same problem. Even I am using a different method to hide the status bar. I add this line to config.xml:

`<preference name="Fullscreen" value="true" />`

And screen jumps up to go full screen.

**Comment by zgulser** [comment]
Try using LAYOUT flags available through either window manager or system ui visibility flags, to avoid such jumping or resizing.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#161
