### ISSUE TITLE
Unable to 'ionic emulate ios -l' with ios platforms 4.x.x up

### ISSUE THREAD

**Issue by Kiszko** [driftyco/ionic#5880]
My team are unable to live reload using the command 'ionic emulate ios -l'.

We have recently upgraded to ios platform 4.0.1 and this is what seems to be the problem.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind telling me what you mean by ios platform? Do you mean thats the version of ios your testing with? Also are you using ionic 1 or ionic 2? And, are you getting any errors when running the emulate command? Thanks again!

**Comment by Kiszko** [comment]
Hey :)

So when adding ios by using 'cordova platorm add ios'
Any version from 4 upwards seems to be causing this problem.

They're no errors as far as I can tell, the app simply gets stuck on it's loading screen.

From the given branches: https://github.com/apache/cordova-ios/branches/all only 3.9.x downwards seem to support live reload - from what we can see.

**Comment by jgw96** [comment]
Hello @Kiszko ! So yeah, with newer versions of ios there were some security changes that apple made that caused issues with livereload, so they depecrated that feature in newer versions of cordova-ios. Sorry about that! I am going to close this issue, but feel free to comment back if needed. Thanks for using ionic !
