### ISSUE TITLE
V2 - Action Sheet opening Alert freezes app

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#5881]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

When opening a modal from an action sheet button, everything works as expected.  The modal opens, and the action sheet goes away.

When opening an alert (in my case, a radio alert), the action sheet does not close and the app essentially freezes in the action sheet state.

#### What behavior are you expecting?

I would expect the behavior between the modal and alert opened from an action sheet button click handler to function the same.  I would expect that functionality be to hide the action sheet and open the new modal/alert/whatever.

See short video showing issue here.

https://drive.google.com/file/d/0B6QFxGN0X4L_N3ZMZ1E2Z1N6d0k/view?usp=sharing

The video does not show accepting an option, but the same behavior is triggered when accepting an option.

**Steps to reproduce:**
1. Create an action sheet
2. Add a cancel button
3.  Add a button that opens a modal
4.  Add a button that opens an alert
5.  Execute the code and click the button to launch the modal, observe.
6.  Execute the code and click the button to launch the alert, observe how the app essentially freezes and the action sheet cannot be removed.

```
isolationDetails(isolation) {
	    var isolationId = null;
	    if ( isolation ){
	        isolationId = isolation.id;
	    }
	    let isolationDetailsModal = Modal.create(IsolationDetails, {
	        isolationId: isolationId,
	    });
	    isolationDetailsModal.onDismiss(data => {
			if ( data && data.isolationId ){
				this.associateHazardWithIsolation(data.isolationId);
			}
			else{
				// refresh the existing list just to be safe
				this.loadIsolationsForHazard(this.selectedHazard.id);
			}
	    });
	    this.nav.present(isolationDetailsModal);
	}

	addIsolationClicked(){
		let actionSheet = ActionSheet.create({
			title: "Isolations",
			buttons: [
				{
					text: "Create New Isolation",
					handler: () => {
						this.isolationDetails();
					}
				},
				{
					text: "Choose Existing",
					handler: () => {
						this.chooseExistingIsolation();
					}
				},
				{
					text: "Cancel",
					style: "cancel",
				}
			]
		});
		this.nav.present(actionSheet);
	}

	async chooseExistingIsolation(){
		// choose an existing isolation, so load all Isolations
		var isolations = await this.isolationHydrater.loadAllHydratedIsolations();
		let alert = Alert.create();
		for ( var isolation of isolations ){
			alert.addInput({
				type: "radio",
				label: `${isolation.isolationType.name} - ${isolation.equipment.name}`,
				value: isolation.id
			});
		}
		alert.addButton({
			text: "CANCEL",
			handler: data => {
				//console.log("Cancel clicked");
			}
		});
		alert.addButton({
			text: "OK",
			handler: data => {
				console.log(`Selected Isolation ID is: ${data.isolationId}`);
			}
		});
		this.nav.present(alert);
	}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Nothing interested is logged
 

**Which Ionic Version?** 1.x or 2.x

2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by iignatov** [comment]
I created a [simple demo environment](http://plnkr.co/edit/CQCTB0INu9AeY7dcInxw?p=preview) and tried to reproduce the issue that you're observing.

I had to replace the async-code with Promises because it didn't run otherwise _(and I'm not sure how to make the async-code working in Plnkr)_.

It seems that everything works as expected _(i.e. the problem cannot be reproduced)_. Maybe I missed something or made a mistake in the code though. Feel free to update it as needed.

**Comment by danbucholtz** [comment]
Thanks for doing that @iignatov.  I'll look into the issue a bit more and see if I can isolate it.  Thanks for your help!

**Comment by adamdbradley** [comment]
Thanks for the help @iignatov

**Comment by eprabhakar** [comment]
@iignatov 
I tried showing a basic alert with the example as in your code, but in the line
``` 
this.nav.present(alert)
```
I get the error 
>>Error TS2339: Property 'present' does not exist on type 'NavController'
Am I missing something?
