### ISSUE TITLE
Getting Zenga error locks scrolling

### ISSUE THREAD

**Issue by whitecat** [driftyco/ionic#5882]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
The view no longer allows scrolling input. I get the following errors.

The first error that appears is this and it appears only one time:
TypeError: zyngaCore.effect.Animate.route is not a function. (In 'zyngaCore.effect.Animate.route(wasAnimating)', 'zyngaCore.effect.Animate.route' is undefined), http://localhost:8100/lib/ionic/js/ionic.bundle.js, Line: 6625

The second and onward errors I get are:
TypeError: zyngaCore.effect.Animate.route is not a function. (In 'zyngaCore.effect.Animate.route(self.__isDecelerating)', 'zyngaCore.effect.Animate.route' is undefined), http://localhost:8100/lib/ionic/js/ionic.bundle.js, Line: 6087 (sometimes in 6210)

#### What behavior are you expecting?
I am expecting the window to scroll without an error.

**Steps to reproduce:**
1. Have ionic list. with only 2-3 items on page.
2. Then scroll the list, from bottom to top, so all items appear off the page.
3. Let go of mouse and click on the mouse again before the items re-center.
4. The error should start appearing now. 

**Which Ionic Version?** 1.x or 2.x
CLI v1.7.14

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello! Are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!
