### ISSUE TITLE
Add ViewEncapsulation.None to all ionic components

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5884]
No need to run through the `ViewEncapsulation.Emulated` logic.

```
@Component({
  encapsulation: ViewEncapsulation.None,
})
```

**Comment by DavidFrahm** [comment]
@adamdbradley or anyone who knows: Can you add (or point me to) some context here for WHY ionic components went with `ViewEncapsulation.None`?

I'm just trying to learn about ViewEncapsulation, so understanding why Ionic went a different route than the default for this would be very helpful.

**Comment by kirillgroshkov** [comment]
@adamdbradley Can you clarify why Ionic doesn't use Angular's ViewIncapsulation?
