### ISSUE TITLE
Add ChangeDetectionStrategy.OnPush strategy to all components

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#5885]
```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
})
```

Double triple check all components are setup to do this

**Comment by manucorporat** [comment]
Good stuff :+1:

**Comment by xr0master** [comment]
I ask not do it by default. This performance hit.

**Comment by kamok** [comment]
@adamdbradley Can you guys add it to ion-select too? I think it could solve an issue I have with: https://forum.ionicframework.com/t/ng2-translate-and-selectedtext-on-ion-select-delayed-translation-until-clicked/96034
