### ISSUE TITLE
Back button appears too early when transitioning between pages

### ISSUE THREAD

**Issue by Mobius77x** [driftyco/ionic#5887]
#### Short description of the problem:

When doing a push from a home/login page with no navbar to another page with a navbar, I am seeing the back-button icon appear too early, with the discrepancy in timing being quite large sometimes (just before the transition even starts!). I am testing in Chrome Canary.

#### What behavior are you expecting?

The back button is rendered on and transitions with the page navigated to.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
https://forum.ionicframework.com/t/back-button-appears-too-early-when-transitioning-between-pages/46790/1

Reproducable by Mike Hartington.

**Which Ionic Version?** 1.x or 2.x

Ionic 2 beta

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Windows 8.1
Node Version: v5.6.0

**Comment by danbucholtz** [comment]
Hi @Mobius77x 😄 ,

Are you still seeing the issue?  Here's what I'm seeing.  Am I missing something?

Please let me know.  

Native app in transition:
<img width="646" alt="screen shot 2016-06-13 at 4 38 46 pm" src="https://cloud.githubusercontent.com/assets/4680488/16024093/8026ce28-3185-11e6-8ae9-9cf5197d54bd.png">

Ionic app in transition:
<img width="604" alt="screen shot 2016-06-13 at 4 32 37 pm" src="https://cloud.githubusercontent.com/assets/4680488/16024100/882d1ea6-3185-11e6-8f98-2b51ecc47e3f.png">

I'm going to close this issue for now but I'll re-open if needed.

Thanks,
Dan

**Comment by Mobius77x** [comment]
@danbucholtz 

Please reopen.  This is clearly evident when transitioning from a page without a navbar (e.g sign-in page) to one with a navbar (e.g. Terms of Service page linked from sign-in page) using ionic serve with an ios platform. Way back when this was raised the ios platform was the default ionic serve platform (since changed to Material Design transition where this issues is not evident). It was reproducible by Mike Hartington and has evidently moved from beta to beta because it was reproducable by Brandy and Adam etc but was deemed lower priority...

**Comment by danbucholtz** [comment]
Hi @Mobius77x,

Happy to discuss further.  Here is the vid from the Ionic app.

https://drive.google.com/file/d/0B7Xofj71-_MbU19iRHEtU3N2VGs/view?usp=sharing

The native app (Twitter) looked basically identical when navigating in real-time and when looking at it at 25% speed.  Please let us know what we're missing.

Thanks,
Dan

**Comment by Mobius77x** [comment]
Thanks for the video. I think the issue isn't as pronounced as it was in the past beta version because my understanding is that the transition delays/startup time have been shortened in recent betas. The fade-in and especially the fade-out of the back button independent of the page transition is somewhat noticeable in your 25% speed example, and is more evident when the navbar is black and the back arrow is white on the page being transitioned to, and the page being transitioned from has a dark background, as is the case with my app.

If this is the expected standard ios behaviour (i.e. back button fades-in somewhat independent of page transitioning, rather than being embedded on and transitioning with the page being transitioned to) then so be it - in ionic1 the back-button used to transition right to left with the page being transitioned to and not fade-in or out with a right-to-left transitioning page as is the case with ionic2.

**Comment by danbucholtz** [comment]
It definitely matches the behavior of the Twitter app.  To be honest, I couldn't find too many apps that don't override the default Nav bar on iOS to verify.  This functionality was designed before my time at Ionic but based on a conversation with Adam he said he modeled it after how iOS nav works.
