### ISSUE TITLE
Ghost clicks on iOS through action sheet and through to modal to be opened

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ionic#5889]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

I am experiencing ghost clicks on iOS in two scenarios:
1) Open an action sheet, tap an action sheet button, tap taps both, the action sheet button and an underlying <a> element.
2) Tap an <a> item element a list which opens a modal, tap taps link in the modal to be opened at the exact same spot as where initially tapped on the base screen.
#### What behavior are you expecting?

1) Tap should not go through action sheet button
2) Tap should not tap a link in a modal to be opened

**Steps to reproduce:**
This happens very rarely, so it is not easy nor trivial to reproduce. It happens randomly, I can't really tell any special circumstances when this happens

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Might be similar to this one: https://github.com/driftyco/ionic/issues/4993 

**Which Ionic Version?** 1.x or 2.x
1.2.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by anurag6792** [comment]
Have you solved this issue? If yes then how did you?

**Comment by leschirmeur** [comment]
Nope, still existing and annoying

**Comment by anurag6792** [comment]
In my case, When I open the modal and press a button in modal,an event is generated and the modal is closed.But the element beneath it also gets clicked. Can you suggest something on this?

**Comment by corysmc** [comment]
I have this same issue. I have a button in the top right that opens the modal, when the modal opens, there's a second click on the save button (also top right).

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#159
