### ISSUE TITLE
Ionic push message keeps in Queue status

### ISSUE THREAD

**Issue by vsrboth** [driftyco/ionic#5890]
#### Short description of the problem:
I am testing the ionic push on browser. I already set `dev_push` to `true`.

I am using this `https://apps.ionic.io/app/787eb344/push/alpha/tools` to send the push message in development mode.

What I get from checking message status is 

```
{"errors":[],"ios":{"failure_reason":"","success":false,"sent":0},"status":"Queued","android":{"failure_reason":"","success":false,"sent":0},"app_id":"787eb344"}
```

It's been like more than 1 hr already. here is the message id `0eb20b08eded11e5a02b0e1560be0420`

**Which Ionic Version?** 1.x or 2.x
`1.x`

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by animista01** [comment]
If the status stays at "Queued" you have an error on your push notification code, copy and paste the exactly example code that the plugin provides you, also try setting dev_push to false, set it to true when trying on a real device.

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue is more related to the ionic platform and not the actual framework i will be moving this issue to the correct repo. Please feel free to move the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/platform-client-node#2
