### ISSUE TITLE
bug: ionic-floating-label

### ISSUE THREAD

**Issue by jbrownssf** [driftyco/ionic#5891]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I only testing on web and iOS 9.
Adding item-floating-label through ngClass does not reveal the upper label correctly when text is input into the label. I looked at the elements in the project I am working on and saw this:
<span class="input-label ng-binding" aria-label="{{toolBox.newDiv.mainLabel}}" id="_label-2">First Name</span>
I noticed the aria-label="" had {{}} when i used ng-class, and it did not when I put the text in as a normal class. Here is my code pen that replicates the bug.
http://codepen.io/jbrownssf/pen/QNpKMx?editors=1010</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
@jbrownssf Thanks for providing the codepen! I did some testing myself and there does seem to be a bug where the `has-input` class is not being applied that we will have to look into. Just a suggestion but im not sure that changing an input programmatically is gonna provide for the best user experience as it may be a little jarring and confusing for the user, but as i said that is totally a suggestion, and im definitely not a UX expert! haha (:

**Comment by jbrownssf** [comment]
Thanks for the tip, although I am working on making a tool that creates every possible ionic CSS element to make coding the UX easier for future apps. My temporary preview before the element gets added to the current state is where I want to dynamically change it.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#158
