### ISSUE TITLE
bug: ionic build ios fails with Apple Watch target

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic#5893]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>- //create a new blank Ionic 2 app
- ionic platform add ios
- ionic build ios // works
- // Xcode > Add target > Apple Watch (WatchOS 2)
- ionic build ios // fails with this error:

=== BUILD TARGET Watch Companion Extension OF PROJECT Companion WITH CONFIGURATION Debug ===

Check dependencies
target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphonesimulator' platform

** BUILD FAILED **</span>

<span is-issue-template></span>

**Comment by gylippus** [comment]
+1 
I can confirm we have the same issues. It's been so long since we haven't had to use Xcode just to run the app. :+1:

**Comment by jgw96** [comment]
Hello @thomaswb ! Thanks for opening an issue with us! Here is a workaround that will hopefully work for you: run `ionic run ios`, this will fail but the project should be updated. Then you should be able to run the app from xcode directly and it should work. Sorry that this is kinda hacky!

**Comment by jgw96** [comment]
I hope to have a better solution soon

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#850
