### ISSUE TITLE
Orientation may not be set to reverse portrait

### ISSUE THREAD

**Issue by gbourel** [driftyco/ionic#5898]
#### Screen orientation may not be set to reverse portrait or reverse landscape.

Screen orientation should use reverse values or be sensor-based.
Eg. like `screenOrientation` values defined here https://developer.android.com/guide/topics/manifest/activity-element.html

**Steps to reproduce:**
1. Modify config.xml to force screen orientation to portrait `<preference name="orientation" value="portrait" />`
2. Works as expected (screen orientation is portrait only).
3. Modify config.xml to force screen orientation to sensor portrait or reverse portrait `<preference name="orientation" value="sensorPortrait" />`
4. Value is ignored and screen orientation is invalid.

**Comment by manucorporat** [comment]
@jgw96 I don't think issue applies to ionic-framework, but cordova. do you agree?
