### ISSUE TITLE
Nav bar become blank when drag to back on iOS

### ISSUE THREAD

**Issue by leonardosalles** [driftyco/ionic#5899]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

When you start to drag to back on iOS the ion-nav-bar component receive a css class called 'hide' this class makes the nav bar become blank and if you release the screen it stay blank, this class doesn't make any sense to be add on the nav bar because you don't need to make it hidden when you try to back to previous page.
#### What behavior are you expecting?

Nav bar don't become blank when you start to drag the screen

**Steps to reproduce:**
1. Access a screen with a child screen
2. At child screen go to another child screen. 
3. At second child screen try to drag at the corner to back to parent screen. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 http://stackoverflow.com/questions/30423950/in-ionic-when-swipe-back-the-nav-bar-become-blank/36138913#36138913

**Which Ionic Version?** 1.x or 2.x
1.2.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 8.1
Node Version: v5.5.0

**Comment by lordgreg** [comment]
I am having exact same issue. Please someone, have a look a this.

**Comment by leonardosalles** [comment]
@lordgreg For iOS I found this workaround: 

`ion-nav-bar.hide {
   display: block !important;
}`

**Comment by lordgreg** [comment]
@leonardosalles thank you very much. I've implemented the fix and it works great :+1:

**Comment by leonardosalles** [comment]
Remember, this is a workaround, keep your eyes on this issue to get the properly fix ;)

**Comment by leonardosalles** [comment]
Solved by [#6331](https://github.com/driftyco/ionic/pull/6361). Thanks @vitaliy-bobrov.

**Comment by VinceOPS** [comment]
@leonardosalles @vitaliy-bobrov 

Could you guys let me know what does the fix consist in? It looks like the commit history is broken due to the repository move (with ionic2 replacing ionic1).

Thanks

**Comment by leonardosalles** [comment]
@VinceOPS Hi, as I remember, the issue was about a wrong 'hide' class that was added to the navbar, by some reason we get the 'hide' class in the navbar and it makes the navbar hidden but not with a right approach, it was solved, I didn't checked it deeper, maybe @vitaliy-bobrov can explain better.

**Comment by vitaliy-bobrov** [comment]
@leonardosalles , sorry, I don't remember what changes I did, it was so long time ago (((
