### ISSUE TITLE
Not compatible with zone.js 0.6.x

### ISSUE THREAD

**Issue by damienadermann** [driftyco/ionic#5900]
When upgrading to the latest angular (2.0.0-beta.11), which requires zone.js 0.6.5 I receive an error in the console saying `Uncaught Error: Cannot find module "zone.js/dist/zone-microtask"` and nothing renders.

zonejs has api changes from 0.5.x to 0.6.x and I suspect ionic is relying on the 0.5 api.

To reproduce upgrade to angular beta 11 and zonejs 0.6.5 and attempt to run your app with `ionic serve`

current package.json
```json
{
  "dependencies": {
    "@ngrx/store": "^1.3.3",
    "angular2": "2.0.0-beta.11",
    "angular2-jwt": "0.1.8",
    "es6-promise": "3.0.2",
    "es6-shim": "0.35.0",
    "immutable": "^3.7.6",
    "ionic-angular": "2.0.0-beta.3",
    "ionic-native": "1.0.12",
    "ionicons": "3.0.0-alpha.3",
    "ng2-cordova-oauth": "0.0.3",
    "ngrx-store-localstorage": "0.0.6",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.5"
  },
  //...
}
```

```
$ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.21
Ionic App Lib Version: 2.0.0-beta.11
ios-deploy version: 1.8.5
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.2 Build version 7C68
```

**Comment by jgw96** [comment]
Hey! Thanks for opening this issue with us! As you can see there is a reason we have not updated to the latest Angular 2 yet (;  but we do plan on it in the near future! Thanks again!
