### ISSUE TITLE
bug(ion-input): autocapitalize, autocorrect & autocomplete

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5904]
#### Short description of the problem:
I cannot get an ion-input or ion-textarea to respect these properties or combinations thereof.

#### What behavior are you expecting?
On a device, I am expecting to be able to control whether an ion-input's autocapitalize, autocorrect and autocomplete facilities are enabled or disabled. This should utilize the mobile device's options for when the user is typing.

More [information](http://gonehybrid.com/how-to-tweak-the-keyboard-for-html5-text-input-fields-on-ios/). 

This applies to `ion-input` and `ion-textarea`.  

There is no mention of this in the [API docs](http://ionicframework.com/docs/v2/api/components/input/Input/) either. 

See repo here: https://github.com/dylanvdmerwe/ionic2-formtest

- [autocapitalize](https://developers.google.com/web/updates/2015/04/autocapitalize?hl=en)
- [autocomplete](http://www.w3schools.com/tags/att_input_autocomplete.asp)
- I cannot actually find any documented information on autocorrect. Is this a valid property? What is the difference between this and autocomplete?

_Note that this applies to all platforms._

**Which Ionic Version?** 2.x 

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4-f23043ed
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by dylanvdmerwe** [comment]
**Updated information on this issue above. **

- Android tested with Google Keyboard, Go Keyboard and Swiftkey. All keyboards seem to do different things, but the properties are supported.

- iOS tested with default keyboard. Autocomplete property does not take effect but this may just be a safari thing. 

I'm satisfied that this issue can be closed. 

@adamdbradley should autocomplete and autocorrect not both be set if one is (for input and textarea)? I am not sure what the difference between the two are and it may cause confusion and issues for users across different platforms.

**Comment by jgw96** [comment]
@dylanvdmerwe Did some testing on my android devices (Nexus 6 running Android N dev preview 2, Nexus 7 running Android 6.0.1 and a Moto X 2014 running Android 5.1) with the Google Keyboard and all the properties discussed above seemed fine for me. Lets close this issue and then maybe open a separate one for the ios issue?

**Comment by danielehrhardt** [comment]
Hi i have the same problem
with a input it is working but with a ion-input not

**Comment by rodneicouto** [comment]
@danielehrhardt  see my answer in this link https://github.com/driftyco/ionic/issues/10852
