### ISSUE TITLE
bug: Ionic CLI CloudFlare Problem

### ISSUE THREAD

**Issue by pedrohills** [driftyco/ionic#5905]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When trying to login using the "$ ionic upload" command I am prompted for my email address and password.

I keep getting the following message:
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.2.0</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is not an issue related to the actual framework i am going to be moving this issue to the correct repo. Please feel free to continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#852
