### ISSUE TITLE
<ion-icon name="compose"> and "edit" doesn't work (blank) in Ionic 2

### ISSUE THREAD

**Issue by ceefour** [driftyco/ionic#5908]
#### Short description of the problem:

```xml
<ion-icon name="compose"></ion-icon>
<ion-icon name="edit"></ion-icon>
```
not showing anything

#### What behavior are you expecting?

Showing icons

**Steps to reproduce:**

```xml
<ion-icon name="compose"></ion-icon>
<ion-icon name="edit"></ion-icon>
```

**Which Ionic Version?** 1.x or 2.x

2.0.0-beta.3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
C:\Users\ceefour\git\lumen-trainer\mobile>ionic info
WARN: ionic.config.js has been deprecated, you can remove it.

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.21
Ionic App Lib Version: 2.0.0-beta.11
OS:
Node Version: v5.9.0
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Currently some of the ionicons are missing from the latest Ionic 2 package, and some of them have simply been renamed. The compose icon has been renamed to create, and currently the edit icon is missing. Hope this helps! Also if you would like an easy way to look up all the icons currently in ionic 2 with the updated names you can check them out here: http://ionicframework.com/docs/v2/resources/ionicons/

**Comment by matheo** [comment]
The resource index is now at:
http://ionicframework.com/docs/v2/ionicons/

But using the latest Ionic 2 I get the facebook logo using `name="logo-facebook"` and not just `"facebook"` as the index suggest

**Comment by strig** [comment]
It looks like the edit icon is still missing.

**Comment by lonwi** [comment]
It would be useful to get the edit one in, specially we have the final version in.

**Comment by JackStoneDev** [comment]
What is the status on this?

**Comment by Sroose** [comment]
Going to Ionic3, but no edit icon available yet

**Comment by nareindiren** [comment]
search for "create" insetad
