### ISSUE TITLE
$ionicScrollDelegate.resize() not working on android 4.3

### ISSUE THREAD

**Issue by lukadisanto** [driftyco/ionic#5909]
#### Short description of the problem:
When I load some data dinamically into ion-content $ionScrollDelegate.resize() do not recalculate size of ion-content on andoid 4.3. On newer version it work fine.

#### What behavior are you expecting?
ion-content scroll resize

**Steps to reproduce:**
1. Create a view with some data hidden
2. Show hidden data
3. Call $ionicScrollDelegate.resize()

I use ionic 1.7.14

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
