### ISSUE TITLE
Sticky Headers do not work in Chrome and Android

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5911]
_From @jboothe on March 1, 2016 23:29_

Sticky Headers work in iOS emulator and Safari browser but do not work in Android emulator or Chrome browser. 

Is this is by design? 

_Copied from original issue: driftyco/ionic-conference-app#159_

**Comment by brandyscarney** [comment]
_From @cyprusglobe on March 2, 2016 16:41_

@jboothe:Android doesn't support sticky headers

**Comment by brandyscarney** [comment]
_From @madibalive on March 10, 2016 4:53_

is it configurable to force android to show it , am assuming it scss issue or is it platform hardware issue

**Comment by brandyscarney** [comment]
_From @kuntal-b on March 18, 2016 8:5_

Facing same problem .
[Form Post](https://forum.ionicframework.com/t/problem-with-ionic-conference-app/46760)

**Comment by brandyscarney** [comment]
_From @madibalive on March 18, 2016 14:38_

head it browser related  - appears chrome doesnt support these feature , so very unlikely to come in future release for android  -  best option is to for ionic 1.x sticky header

**Comment by adamdbradley** [comment]
We have decided not to polyfill this feature with a JS solution for Chrome/Android. Basically it will be an additional drain on performance, especially when scrolling, and may introduce bugs.

Good news however, is it appears Chrome is actively working on this: https://www.chromestatus.com/feature/6190250464378880
https://bugs.chromium.org/p/chromium/issues/detail?id=231752
