### ISSUE TITLE
Navigation change doesn't get reflected till a user action

### ISSUE THREAD

**Issue by SaiNageswarS** [driftyco/ionic#5912]
#### Short description of the problem:
nav.setRoot or nav.push or nav.present(alert) doesn't show up till another user action is made on the page. 

#### What behavior are you expecting?
After clicking verify OTP, either error should popup for invalid otp or navigate to tabs page if OTP is valid. However, in either of the case till user doesn't perform another action, the navigation change doesn't show up in the screen - happens in both Android and browser

**Steps to reproduce:**
1. Checkout repo below
2. ionic serve
3. Enter any random name and phone number.. Enter OTP as "0000". Click verify otp

https://github.com/SaiNageswarS/ionic2-sampleapp

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?**  2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.10 
Node Version: v5.0.0

**Comment by jgw96** [comment]
Hello! Are you still having this issue with the latest version of Ionic 2? (beta.5) Thanks!

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue I will be closing it. Thanks for using ionic!
