### ISSUE TITLE
bug: keyboard default accessories do not work

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5914]
#### Short description of the problem:

Now that the hideKeyboardAccessoryBar has been disabled in iOS, the left and right arrow accessories that display above the keyboard do not actually move forward and backward between the ion-inputs on the screen. The keyboard normally just closes when the left or right arrows are pressed.
#### What behavior are you expecting?

Easily be able to navigate forward and backward through the input fields using the keyboard's accessory bar. Note that if there are multiple fields that are shown in different states (hidden or ngIf) this should be taken into consideration. 

```
<ion-content padding class="page1">
    <ion-item>
        <ion-label>Username</ion-label>
        <ion-input></ion-input>
    </ion-item>

    <ion-item>
        <ion-label>Website</ion-label>
        <ion-input type="url"></ion-input>
    </ion-item>

    <ion-item>
        <ion-label>Email</ion-label>
        <ion-input type="email"></ion-input>
    </ion-item>

    <ion-item>
        <ion-label>Phone</ion-label>
        <ion-input type="tel"></ion-input>
    </ion-item>

    <ion-item clearInput>
        <ion-input placeholder="Username"></ion-input>
    </ion-item>
</ion-content>
```

**Which Ionic Version?** 2.x 
**Plugin version?** 2.0.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.5 
ios-sim version: 5.0.7 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Removing the feature that allowed you to hide the accessory bar was necessary to allow people to submit apps to the app store succesffuly again. Unfortunately to get that issue fixed as fast as possible we simply just had to remove that feature all together as a better solution has not been found yet (although its actively being worked on). Therefore this means that there may be some features of the accessory bar which may not work correctly with Ionic as we've always worked off the basis it was hidden. We realize this is irritating and hope to have this hide accessory bar keyboard issue figured out soon. Thanks again!

**Comment by dylanvdmerwe** [comment]
Fair enough. But what happens if I don't want the accessory bar to be removed? Shouldn't the default functionality of the keyboard's accessories work as expected in that case?

**Comment by jgw96** [comment]
Reopening this issue as it is a valid use case that a user would not want to hide the accessory bar.

**Comment by jgw96** [comment]
hideKeyboardAccessoryBar is now possible with the latest release. Thanks!

**Comment by SopoB** [comment]
can we hide arrows only  of accessary bar in Ionic?
