### ISSUE TITLE
bug: duplicate entries in history stack after implementing RouteConfig

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#5915]
**Issue in Ionic 2**

After configuring routeconfig as below
@RouteConfig([
    { path: '/', component: HomePage },
    { path: '/next', component: NextPage }
])

launched the app http://localhost:8100 in browser. But when i press back button, It not going back still in homepage for 3 consecutive back press. after 3 try it going back.

**Comment by jgw96** [comment]
Thanks for opening an issue with us ! Are you navigating forward in your app before trying to go back?

**Comment by dheeran1** [comment]
No.

you can try replicating it by adding routeconfig and entering 

> ionic serve

 command.  you can see back button got enabled already.

**Comment by dheeran1** [comment]
Is there any workaround for this? I'm planning for go live. Pls help.

**Comment by jgw96** [comment]
Sorry for the delay @dheeran1 ! Thats my fault. Would you be able to provide just a little more info on your issue, and maybe a codepen or plunkr so that i can reproduce this myself and have a look at your code? Thanks! And sorry again!

**Comment by dheeran1** [comment]
@jgw96  this is an straight forward issue. just add routeconfig into the app. Launch the app. then try pressing back (browser's back button), notice that you will be redirected to the same page again for consecutive 3 tries.

**Comment by dheeran1** [comment]
Bug raised in angular also
https://github.com/angular/angular/pull/6069

**Comment by adamdbradley** [comment]
Ng2's new router has been deprecated and refactored. In upcoming releases we'll update Ionic to the Ng2's new new router. Sorry for any issues this may cause.

**Comment by dheran** [comment]
@adamdbradley will navcontroller or ionic will also be deprecated. actually two terms for same job, confusing a lot. 

Will beta 7 release will include the changes you mentioned above?

**Comment by jgw96** [comment]
Hey @dheran! Sorry for the confusion, nothing in Ionic 2 is being deprecated. The original router the angular 2 team built is now deprecated and they are working a new angular 2 router. Our integration of this new router into Ionic 2 is not ready yet and will not make it to the beta.7 release. Thanks for using Ionic!
