### ISSUE TITLE
bug[v2]: Performance issue rendering many elements dynamic

### ISSUE THREAD

**Issue by rodrigoreal** [driftyco/ionic#5918]
I have a project with alpha42 and im trying to create a new project with beta3, but i 'm having some problem rendering my elements with the beta3 project.
It is getting really laggy when i dynamic create these elements with ngFor, if i create these cards hardcoded(i mean copy and paste 30-50 cards) it don't happen.
And it happens in my android device (moto x 2nd), in the chrome i don't have this performance issue.

I don't know if it is an angular problem or ionic problem.

Anyone have any idea why is that happening?

You can reproduce this code:

HTML

```
<ion-content>

  <ion-card *ngFor="#monster of monsters">

    <ion-row class="monster-stats">
      <ion-col width-20>
        <h6>HP: </h6>
        <h6>ATK: </h6>
        <h6>DEF: </h6>
        <h6>SPD: </h6>
      </ion-col>
      <ion-col width-30>
        <h6>CRI Rate: </h6>
        <h6>CRI Damage: </h6>
        <h6>Resistence: </h6>
        <h6>Accuracy: </h6>
      </ion-col>
    </ion-row>

  </ion-card>

</ion-content>
```
 
JS:

```
import {Page, NavController, NavParams, Platform} from "ionic-angular";

@Page({
  templateUrl: "build/pages/monsters/monsters.html"
})

export class Monsters {
  platform: Platform;

  monsters: any;

  constructor(platform: Platform) {
    this.platform = platform;
    this.monsters = [];

    for (let i = 0; i < 50; i++) {
      this.monsters.push("");
    }
  }
}

```

**Which Ionic Version?**  2.x beta3

**Run `ionic info` from terminal/cmd prompt:** 
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by dylanvdmerwe** [comment]
Android specific? What version of Android? Crosswalk installed?

**Comment by rodrigoreal** [comment]
Android 6.0 without crosswalk.

With this same code in my alpha42 project it works perfect, but in my beta3 project i get a poor performance.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you experiencing the same perf issues in the browser?

**Comment by dylanvdmerwe** [comment]
> And it happens in my android device (moto x 2nd), **in the chrome i don't have this performance issue**.

**Comment by jgw96** [comment]
Sorry @rodrigoreal didnt see that in your original post, sorry about that and thanks @dylanvdmerwe for the heads up. Testing this now with my devices.

**Comment by jgw96** [comment]
Alright @rodrigoreal . I did some testing using your exact code with my Nexus 6 running the Android N dev preview and ran into no performance issues. One optimization you could make though would be to take the code you have in your constructor and put it in `onPageDidEnter()`. Here is an example: 

![screen shot 2016-03-23 at 4 00 02 pm](https://cloud.githubusercontent.com/assets/8823093/14000691/5eccf276-f110-11e5-95dd-03e8773a145d.png)

Would you be able to give a little more input on the perf issues your having? Are they scrolling related? Or loading related?

**Comment by jgw96** [comment]
Just did some more testing and i didn't run into any perf issues until i changed it to loop through 1000 times. When i did this i ran into some slow rendering on loading of the page.

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue i will be closing it for now. Thanks for using Ionic!
