### ISSUE TITLE
bug[v2]:Show SplashScreen and white screen on Android 4.3

### ISSUE THREAD

**Issue by Tubishi** [driftyco/ionic#5919]
Hi, i have a problem when i want to test my App on my Android 4.3 don't works. I can see the splashScreen, but after white screen and nothing....

**Steps to reproduce:**
1. Create a project
2. ionic run android on Android 4.3 and you will see

Which Ionic Version? 2.x beta3 or beta2

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.04 
Node Version: v4.0.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Does your app work with Ionic serve?

**Comment by Tubishi** [comment]
Yes, no problem with Ionic serve, with Android 4.4, 5.1 and more. But before 4.4, nothing happen after splashscreen, just white screen

**Comment by jgw96** [comment]
@Tubishi Thanks for the info! I just followed up with one of my colleagues on our official Android support and we are currently recommending that if you plan on supporting devices older than 4.4.x to use crosswalk. Crosswalk will give you a modern chrome webview bundled right together with your Ionic app and will ensure that your app works on those older Android devices. To add crosswalk to your project simply `cd`  into your app and run `ionic browser add crosswalk`. Hopefully this helps! Thanks again!

**Comment by Tubishi** [comment]
Thanks. i used crosswalk but our app is going from 1 to 17Mo. It is heavy for a compatibility issue; isn't it? ;-)

**Comment by jgw96** [comment]
Haha good observation! It is heavy as its a chrome webview your bundling with your app, buttttt the performance enhancements and api support it gives you on older versions of Android is totally worth it in my opinion (:

**Comment by urosjarc** [comment]
I have the same issue but crosswalk do not solve my problem, pls reopen this issue and see my full explanation on ionic forum :

https://forum.ionicframework.com/t/ionic-2-runs-on-emulator-but-not-in-real-device/47088/4

**Comment by Tubishi** [comment]
@jgw96 Yes it did :)

**Comment by jgw96** [comment]
hey @urosjarc would you mind opening a new issue for your bug that youre experiencing? I believe something different is causing your issue than what was causing @Tubishi 's issue. Thanks!
