### ISSUE TITLE
Update Swiper to latest release

### ISSUE THREAD

**Issue by TheCopartnery** [driftyco/ionic#5920]
#### Short description of the problem:

API functionality for Ion-slides is out of step with that available in Swiper
#### What behavior are you expecting?

Future release of Ionic to be updated to use latest version of Swiper as found here:

```
https://github.com/nolimits4web/Swiper/tree/master/dist/js
```

**Which Ionic Version?** 1.x or 2.x

1.x

**Comment by elineopsommer** [comment]
Is it possible to integrate the navigation arrows? (see example https://github.com/nolimits4web/Swiper/blob/master/demos/14-nav-arrows.html)

**Comment by TheCopartnery** [comment]
Hey, it is already possible to do this in the current version. You will need to add the arrows in your html, like in the example you linked to.

```
<div class="swiper-button-next"></div>
<div class="swiper-button-prev"></div>
```


You will also likely need to specify the class names in your $scope.options.

```
$scope.options = {
  loop: false,
  effect: 'fade',
  speed: 500,
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev'
}
```

This isn't a bulletproof guide (they may need styling / other code) but that's the jist of it :)

**Comment by TheCopartnery** [comment]
Noticed that it has been suggested to [split Swiper off into a separate package](https://github.com/driftyco/ionic/issues/6198) for Ionic 2. 

Perhaps the same approach would also be beneficial for v1

**Comment by jmatsushita** [comment]
Is it possible to use the `progress` pagination type with the shipped version? http://idangero.us/swiper/demos/37-pagination-progress.html

**Comment by tomazberisa** [comment]
@jmatsushita I've tried to do exactly this, but cannot seem to make it work.

Might there be any news re: updating Swiper?

**Comment by jmilloy** [comment]
Is this expected at any point soon? The current version of swiper in Ionic is fairly old (Aug 2015). We'd really like to use some of the newer features like the fraction pagination. I'm just trying to get a sense of the timeline/priority on this issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#156

**Comment by 1BJK903** [comment]
Anyone?
