### ISSUE TITLE
Add the ability to align checkboxes to the right

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5925]
Should be able to add `item-right` (possibly) to a checkbox and align it right, but default to the left.

**Comment by bensperry** [comment]
![image](https://cloud.githubusercontent.com/assets/519526/14001618/f3aaa3da-f114-11e5-8a56-bb56d0d88865.png)

**Comment by ahexdev1** [comment]
i am also want like this can you suggest me?

**Comment by brandyscarney** [comment]
This will be in the `beta.7` release. You should be able to use `item-left` or `item-right` on the checkbox, radio, or toggle.
