### ISSUE TITLE
ion-refresher pull down is blank in v2

### ISSUE THREAD

**Issue by palidanx** [driftyco/ionic#5926]
#### Short description of the problem:
When using ion-refresher, the pull to refresh icons are not appearing.

#### What behavior are you expecting?
When the ion-refresher is used, the pull to refresh icons are displayed like
http://ionicframework.com/docs/v2/api/components/scroll/Refresher/

**Steps to reproduce:**
1)
In a .js page put in
```
  <ion-refresher (start)="doStart($event)"
                   (refresh)="doRefresh($event)"
                   (pulling)="doPulling($event)"
                   >
  </ion-refresher>
``` 
2) Attempt to pull the content down
3) Notice that the content the methods are called, but the pull to refresh icons are not there.

**Other information:** 

Using
```
  <ion-refresher (start)="doStart($event)"
                   (refresh)="doRefresh($event)"
                   (pulling)="doPulling($event)"
                   pullingtext="Pull to Refresh"
                   refreshingtext="Refreshing ..."
                   refreshingicon="refresher-pulling-icon"
                   >
  </ion-refresher>
```
doesn't work either.  I noticed in this page
http://ionicframework.com/docs/v2/demos/refresher/?ionicplatform=ios

It has this content
```
<ion-refresher-content pullingtext="Pull to refresh..." refreshingtext="Refreshing..." state="inactive">  <div class="refresher-pulling">
<div class="refresher-refreshing">
</ion-refresher-content>
```
 
But on my app, it is missing the `refresher-pulling` and `refresh-refreshing` divs.

Here is a copy of my ion-refresher which is generated
````
<ion-refresher pullingtext="Pull to Refresh" refreshingicon="refresher-pulling-icon" refreshingtext="Refreshing ..." class="">
  </ion-refresher>
```

**Ionic Version
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.4.1
```

**Comment by palidanx** [comment]
Ah nvm.  I found that there was another bug that solved this.  The proper way is to put the text in `ion-refresher-content`

```
<ion-refresher (start)="doStart($event)"
                   (refresh)="doRefresh($event)"
                   (pulling)="doPulling($event)">
  <ion-refresher-content
            pullingIcon="arrow-dropdown"  
            pullingtext="Pull to Refresh"
                   refreshingtext="Refreshing ..."
                   refreshingicon="refresher-pulling-icon"><
   </ion-refresher-content>
</ion-refresher>
```

Reference bug:
https://github.com/driftyco/ionic/issues/5207

We might want to update the docs for this?

**Comment by Barathwaja** [comment]
#7914
