### ISSUE TITLE
Ionic2 button bar classes don't apply correctly

### ISSUE THREAD

**Issue by callodacity** [driftyco/ionic#5927]
#### Short description of the problem:
When using a `<button>` in an `<ion-buttons>` in an `<ion-navbar>` or `<ion-toolbar>`, the `button`'s classes are incorrectly applied.

#### What behavior are you expecting?
Upon inspecting in devtools, normal buttons in navbar/toolbars have the classes: `bar-button` and `bar-$color`.
When using `ngIf` to dynamically show/hide buttons in toolbars, they should also apply these classes. They do not - but rather, they apply the standard classes: `button` and `button-$color`.

_Perhaps implementing a way to choose whether button type is `bar-*` or not could be a good idea?_

**Steps to reproduce:**
1. add any `<button>` component in an `<ion-buttons>` in an `<ion-navbar>` or `<ion-toolbar>` and ensure that it has the `*ngIf="some expression"` property set.
see [this linked pen](http://codepen.io/callodacity/pen/ZWKRmG). (click edit button in top right corner)

 

**Which Ionic Version?** 1.x or 2.x
This is using ionic 2.0.0-beta3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS:
Node Version: v5.7.0
```

**Comment by jgw96** [comment]
Confirmed this one.

**Comment by adamdbradley** [comment]
We will be able to better fix this once ng2 provides a way to get a list of all attributes on a directive: https://github.com/angular/angular/issues/1818

**Comment by arlowhite** [comment]
**+1**
A concrete example in case it helps:

```html
<ion-toolbar position="bottom">
  <ion-buttons text-center>
    <button [color]="formControls.valid ? 'primary' : 'danger'">
[...]
```

Generated HTML:
```html
<ion-buttons text-center="">
    <button primary="" class="disable-hover bar-button bar-button-default bar-button-icon-left bar-button-primary"><span class="button-inner">
      <ion-icon name="camera" role="img" class="ion-md-camera" aria-label="camera"></ion-icon>
      Photo
    </span><ion-button-effect></ion-button-effect></button>
    
    <button primary="" class="disable-hover button bar-button bar-button-default bar-button-icon-left bar-button-danger" disabled=""><span class="button-inner">
      
      <ion-icon role="img" class="ion-md-alert" aria-label="alert"></ion-icon>
      Done
    </span><ion-button-effect></ion-button-effect></button>
  </ion-buttons>
```

The 2nd button ("Done" label) **should not** have **.button** in addition to **.bar-button**. This causes it to get an outline in the toolbar instead of being clear.

**Comment by brandyscarney** [comment]
As a temporary work around, you can set the `category` on the button so it will always take on a specific role. For example,

```
<button *ngIf="true" category="bar-button">
```

**Comment by arlowhite** [comment]
@brandyscarney The category trick didn't work for me, it still gets the **button** class.
I also tried **[class.button]="false"**, but that didn't work either.

```html
<button primary (click)="done()" [disabled]="!formControls.valid"
            [color]="formControls.valid ? 'primary' : 'danger'"
            category="bar-button" [class.button]="false">
      <ion-icon [name]="formControls.valid ? 'checkmark' : 'alert'"></ion-icon>
      Done
    </button>
```

Is there a way to remove a category as a quick fix? As in remove the regular button category?
Otherwise, I can just override it with CSS for now.
