### ISSUE TITLE
bug: Title bar overlaps with menu on iOS

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5934]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When opening a menu then iOS status bar overlaps with the content. Desired behavior would be the same as with normal pages where additional padding on top is added automatically in order to give some space for status bar.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us, we just need a little more info from you so that we can better help you with your issue. Would you mind posting a code sample, plunkr or codepen that we can use to reproduce your issue? Also, would you mind running `ionic info` and posting the output? Thanks again!

**Comment by ErkoKnoll** [comment]
Hi,

Sorry for the delay, in case you haven't notices it yourself I added cropped screenshot.

![img_0001](https://cloud.githubusercontent.com/assets/9930079/14207544/731949a4-f823-11e5-8459-055bc1fef198.PNG)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We have added this to the beta.5 milestone so you can expect this bug to be fixed once it comes out! In the meantime, as a workaround I would recommend adding margin to your menu title. Thanks again!

**Comment by jgw96** [comment]
Confirmed this one

**Comment by brandyscarney** [comment]
Thanks again for the issue! This should be fixed in the next release `2.0.0-beta.5`. :smile:

**Comment by vintage** [comment]
Any built-in option to disable this padding? I'm working currently on a full screen application where status bar is hidden, so the padding seems odd.

**Comment by brandyscarney** [comment]
Yes, in the config of your app:

```
@App({
  config: {
    statusbarPadding: false 
  }
})
```

**Comment by vintage** [comment]
Love ya <3 thanks!
