### ISSUE TITLE
Ion Refresher Spinning  Icon for Android Not Working for v2

### ISSUE THREAD

**Issue by palidanx** [driftyco/ionic#5936]
#### Short description of the problem:
When using ion-refresher, the pull to refresh icons in Android is just a circle

#### What behavior are you expecting?
When the ion-refresher is used, the pull to refresh icons are displayed like
http://ionicframework.com/docs/v2/api/components/scroll/Refresher/

However in Android (nexus 7 2013) the spinning animation isn't working.
**Steps to reproduce:**
1)
In a .js page put in
```
<ion-refresher (start)="doStart($event)"
                   (refresh)="doRefresh($event)"
                   (pulling)="doPulling($event)">
  <ion-refresher-content
            pullingIcon="arrow-dropdown"  
            pullingtext="Pull to Refresh"
                   refreshingtext="Refreshing ..."
                   refreshingicon="refresher-pulling-icon"><
   </ion-refresher-content>
</ion-refresher>

``` 
2) Attempt to pull the content down in an Android device
3) Notice that in IOS that the spinning icon works doing the refreshing phase, but in Android it doesn't work.

IOS Screenshot:
![photo mar 24 8 54 45 am](https://cloud.githubusercontent.com/assets/268605/14022856/ea9071d2-f19e-11e5-92fb-7bf15f0b0d19.png)

Android Screenshot (notice it is a solid circle and not animating)
![screenshot_20160324-085324](https://cloud.githubusercontent.com/assets/268605/14022858/ed54fe24-f19e-11e5-9df4-2093fde0a74a.png)

**Ionic Version
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v5.4.1
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Are you seeing the same issue in chrome emulating an android device?

**Comment by palidanx** [comment]
Are you referring to running to testing the ionic app via androids chrome browser (eg running 192.168.0.20:8100 on the nexus device via chrome?)

**Comment by jgw96** [comment]
Sorry, should have been more clear! If you could run `ionic serve` this will run your app in your default browser. And if you use chrome as your default browser you can use the device emulation feature in chrome dev tools to emulate an android device, including a Nexus 7

**Comment by palidanx** [comment]
I tried the emulation under Chrome, and there is different behavior than the native device (it looks like IOS).  When running the android emulation in chrome, the spinner looks like the ios spinner (see attached)

![nexus7](https://cloud.githubusercontent.com/assets/268605/14027594/a63928dc-f1b5-11e5-81ec-b66536e4d31a.JPG)

**Comment by jgw96** [comment]
Ahh, sorry you might have to reload the app after changing to the device emulation. Then once the app reloads it should change to the android design.

**Comment by palidanx** [comment]
Ah sorry about that!  Yea, I tested it, and it works under emulation.  I'll try to get my hands on another android device to test this later also.

![nexus2](https://cloud.githubusercontent.com/assets/268605/14027859/f3e4abfa-f1b6-11e5-8b7c-8adfef0877ac.JPG)

**Comment by jgw96** [comment]
Thanks! What version of android is your nexus 7 running? Have you updated to 6.0.1 yet?

**Comment by palidanx** [comment]
Yea it is on 6.0.1  Attached is a snapshot of the detailed specs

![screenshot_20160324-115820](https://cloud.githubusercontent.com/assets/268605/14028042/d1fe2786-f1b7-11e5-8130-69ab9508d578.png)

**Comment by jgw96** [comment]
Thanks for the info! Ill have to test this on my nexus 7 too. Im also on android 6.0.1

**Comment by jgw96** [comment]
Just tested this on my Nexus 6 running the Android N dev preview and can confirm the same issue with the icon not animating. In chrome canary its working fine.

**Comment by jgw96** [comment]
Also, found a weird behavior where the refresher will not work when inspecting the webview with chrome://inspect-devices

**Comment by jgw96** [comment]
Setting refreshingSpinner to circles works, but it seems that the default spinner has some animation problems.

**Comment by jgw96** [comment]
Heres my findings so far: Whenever you take off the position relative from the spinner it works, but its sized wrong at that point.

**Comment by ZiFFeL1992** [comment]
This is really strange, same apk and the spinner works on some devices but stuck I'm others, BTW with the spinner stuck I can see it working in chrome://inspect .

The spinner is not working on devices that where working a few days / weeks ago with beta.3

Let me know if you need more info or video demos about this issue.

**Comment by dheeran1** [comment]
This bug is there on latest updates

**Comment by ZiFFeL1992** [comment]
Seems like google auto installs this: https://play.google.com/store/apps/details?id=com.google.android.webview

Stops working after installing that app.

**Comment by ZiFFeL1992** [comment]
That app has been updated, working again on my phone.

**Comment by iignatov** [comment]
I can also confirm that it works fine after updating the **Android System WebView** to the latest version.

**Comment by jgw96** [comment]
I can also confirm this with the latest version of the Android System WebView. Looks like it was a bug in the Android webview. I am going to close this issue for now, but if the issue arises again i will close. Thanks everyone for the info!

**Comment by tyvdh** [comment]
Seeing this again.
Android System WebView was just updated recently (Aug 3, 2016) so my money is on that again.
My current version is 52.0.2743.98.

**Comment by palaa159** [comment]
+1 on latest Android System webview

**Comment by Yimiprod** [comment]
Having the same bug, is there any workaround?

**Comment by prafull-agarwal** [comment]
I am also facing the same bug in all my different devices. I have also updated "Android System WebView", "IONIC LIB" but seems not working any update to resolve this?
