### ISSUE TITLE
MS Edge's inconsistent attribute normalization causes wrong class to be applied to menuToggle

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic#5938]
#### Short description of the problem: 
The attributes of dynamically added elements retain their camelCase on Microsoft Edge, breaking some Ionic styles.  For example, the menuToggle attribute directive loads as `menuToggle` on Edge, and `menutoggle` on Chrome.  This means the class that is applied is `.bar-button-menuToggle` and `.bar-button-menutoggle` respectively.

#### What behavior are you expecting? 
Directives like menuToggle to have their styles applied correctly.

**Steps to reproduce:**
1. Load the conference app on Edge and inspect the menu toggle button on the Schedule page

You can see it in action by 

**Which Ionic Version?** 2.0.0-beta.3

**Comment by brandyscarney** [comment]
Fixed by Tim's PR. https://github.com/driftyco/ionic/pull/5939
