### ISSUE TITLE
[feature request] NavBar/ToolBar subTitle

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#5940]
#### Short description of the problem:

I would like to be possible to show a subtitle text below the title with smaller text and a little opaque.
#### What behavior are you expecting?

To have a `<ion-subtitle>` tag.

**Which Ionic Version?**  2.x

**Comment by ZiFFeL1992** [comment]
Bump

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by AnandanSelvaganesan** [comment]
<ion-view title="<div class='main-title' style='line-height: initial;'>Main Title</div><div class='sub-title' style='line-height: initial;font-size: 12px;color: #333;'>Sub Title</div>"></ion-view>

**Comment by AnandanSelvaganesan** [comment]
<ion-view title="<div class='main-title' style='line-height: initial;'>Main Title</div><div class='sub-title' style='line-height: initial;font-size: 12px;color: #333;'>Sub Title</div>"></ion-view>

This worked :)

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#25

**Comment by shyamal890** [comment]
+1

**Comment by ZiFFeL1992** [comment]
Is that a private repository @jgw96 ?

**Comment by rnarian** [comment]
This can simply be archived by wrapping your title into a `div` (to force into `display:block`) and adding a second `div` for the subtitle where you would only need to adjust `font-size` (and `opacity`):

```html
<ion-title>
  <div>Regular Title</div>
  <div style="font-size: 12px">Subtitle</div>
</ion-title>
```

![bildschirmfoto 2017-03-01 um 16 01 39](https://cloud.githubusercontent.com/assets/1174951/23465535/d6843572-fe98-11e6-830d-b0169e187dcd.png)

**Comment by 5im0n** [comment]
This snippet work perfectly

```html
<ion-title>
   <span>Title</span> <br>
   <small>Subtitle</small>
</ion-title>
```

@rnarian Don't use block tag like `div` cause you break the `ellipsis` of the title on small device.

**Comment by rnarian** [comment]
@5im0n Good call. I adjusted my example accordingly...

**Comment by ZiFFeL1992** [comment]
You can try this as well:

https://forum.ionicframework.com/t/sub-title-in-navbar/70331
