### ISSUE TITLE
Ionic 2 – action sheet jumps in safari

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#5944]
#### Short description of the problem:
When selecting an option in the action sheet in safari (ios theme), it jumps a little.  

![action-sheet](https://cloud.githubusercontent.com/assets/427213/14047679/e71456f6-f26e-11e5-9406-adfd48e358a8.gif)

#### What behavior are you expecting?

**Steps to reproduce:**
1. visit http://ionicframework.com/docs/v2/components/#action-sheets in safari
2. click "Show Action Sheet"
3. click "Share"
4. notice the sleight movement in the items above the one you clicked.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! This issue has already been fixed and the fix will be included in beta.4, thanks though! Hope your liking ionic 2!

**Comment by astec** [comment]
(offtopic) @jasonwaters how do you create this GIF? Any tool to recommend?

**Comment by jasonwaters** [comment]
@astec It's a handy little tool called [licecap](http://www.cockos.com/licecap/).  Also free. :+1:
