### ISSUE TITLE
v2 - ion-toggle looks bad in lists [ios theme]

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#5945]
#### Short description of the problem:

ion-toggle looks bad in lists after scrolling. it re-renders after selecting an item, but shouldn't need to.

![toggle-list](https://cloud.githubusercontent.com/assets/427213/14048844/95ea0dcc-f276-11e5-99de-dcc26fb48bd3.gif)
#### What behavior are you expecting?

The toggle should not need to re-paint to look right.  Makes it pretty obvious it's not native if it does.

**Steps to reproduce:**
1. Using an iPhone or simulator open safari and point the browser to this [plnkr demo](http://embed.plnkr.co/2aY3ebguIFeVn2rZFZ1H/).
2. slide your finger up the screen to scroll down.
3. notice the toggles don't look right after scroll.
4. Code available [here](http://plnkr.co/edit/2aY3ebguIFeVn2rZFZ1H?p=preview).

**Comment by jasonwaters** [comment]
discussion about this issue on the [ionic forum](https://forum.ionicframework.com/t/ion-toggle-inside-ion-item-looks-bad/46011)

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Does this happen when the app is packaged and installed on your iphone too?

**Comment by jasonwaters** [comment]
yes, it happens when packaged and run on device as well

**Comment by jgw96** [comment]
Alright, thanks for the info!

**Comment by jasonwaters** [comment]
Any chance I can persuade someone to take a look at this one?  It is a glaring problem in my application...

**Comment by manucorporat** [comment]
@adamdbradley it is fixed adding
```
transform: translateZ(0);
```
to `.toggle-inner`

**Comment by jasonwaters** [comment]
@manucorporat thank you, your fix worked great.  I added it to my local app in the mean time.

**Comment by jasonwaters** [comment]
Actually, this is the CSS I added to make it look right:

```sass
.ios {
	ion-item:not(.item-toggle-checked) {
		.toggle-inner {
			transform: translateZ(0);
		}
	}
}


```

**Comment by jgw96** [comment]
@jasonwaters out of curiosity, does this issue happen in WKWebView?

**Comment by loopezz** [comment]
I guess this is a similar issue:
It also applies to $toggle-ios-handle-background-color in Ionic 2 RC3 when a toggle is not checked. The custom color will be rendered after a little delay or after an user interaction, ie: scrolling for a few pixels. However, it works as expected when a toggle is checked.

**Comment by jgw96** [comment]
@jasonwaters Is this still an issue in rc4 ?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
