### ISSUE TITLE
CLI parameters ignored (--appname and --id)

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#5946]
#### Short description of the problem:
Whenever I execute the following command, Ionic seems to ignore all parameters:

    ionic start -a MyApp -i com.kelvindart.myapp -v --ts ionic2-myapp blank

A directory named "blank" is created which contains the Ionic app; the "tabs" starter template is used and it also ignores the app name and app Id (these are not copied to `config.xml`).

If I run (i.e. moving `-v --ts` to the end of the command):

    ionic start -a MyApp -i com.kelvindart.myapp ionic2-myapp blank -v --ts

It *does* create a blank starter app in the folder named "ionic2-myapp", but app name and app Id are still ignored and the defaults are used in `config.xml` (i.e `io.ionic.starter` and `V2 Test`).

The parameters are also ignored if I exclude `-v --ts` too - so I do not believe this to be solely related to Ionic v2.

#### What behavior are you expecting?
I am expecting the `ionic start` process to use the supplied parameters and construct an app template using the app name, and app Id provided.

**Steps to reproduce:**
1. Open Terminal
2. Run both commands above.
3. Observe `config.xml` and notice the app name and app Id are not copied.

**Other information:**
 No errors are produced. Ionic just seems to incorrectly interpret the parameters provided in the wrong place.

**Which Ionic Version?** 2.0.0-beta.22

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related more to the ionic-cli instead of the framework i will be moving this issue over there. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#873
