### ISSUE TITLE
2: Create page in sub-directory/folder [Feature request]

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#5949]
#### Short description of the problem:

When you have an app with a lot of pages, its easier to manage them in groups. e.g.

Concept A
- page 1
- page 2
- page 3 

Concept B
- page 4
- page 5
- page 6

At the moment the ionic g page command creates pages (and their scss / js) at the top level "pages".

However I would like to do

`ionic g page conceptA/pagename `

and it to create pagename in pages > conceptA > pagename

Otherwise, I have to create a page, and then move it subsequently. This is a bit fiddly as quite a bit is auto-generated, so its not just a drag drop. 

#### What behavior are you expecting?

Works as expected. Just this is an idea for an improvement

**Which Ionic Version?** 
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this feature request is more related to the ionic cli i will be moving this feature over there. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#868
