### ISSUE TITLE
bug: Error with CLI v2.0.0-beta.23

### ISSUE THREAD

**Issue by kuntal-b** [driftyco/ionic#5950]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Problem described at bellow forum link

https://forum.ionicframework.com/t/error-with-cli-v2-0-0-beta-23/47496</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to the cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#871
