### ISSUE TITLE
overflow-scroll + ion-refresher 

### ISSUE THREAD

**Issue by obedm503** [driftyco/ionic#5952]
overflow-scroll="true" in an ionContent seems to confilct with ionRefresher. This causes the side menu not to open on drag. and when dragging the left, items on view seem to super impose on the scroll bar. the problem disappears when removing either the overflow-scroll="true" or the ionRefresh.

I noticed the problem when using ionic inside Github's electron and decided to test and see if the same problem happened in the nightly side menu codepen. and it did. My guess s that it is a conflict between native scrolling and js scrolling. The problem is accentuated inside electron, and happens when dragging right or left. hopefully this issue gets solve as native scrolling is usually faster the js, and ionRefresher is a pretty usefull feature.

the codepen: [the codepen here](http://codepen.io/anon/pen/pywwOE)

**Steps to reproduce:**
1. Add the overflow-scroll="true" to ionContent. This activates native scrolling.
2. Add an ionRefresher.
3. Ionic bundle v1.2.4-nightly-2775
4. Sidemenu starter

```
<ion-content overflow-scroll="true">
    <ion-refresher></ion-refresher>
    <ion-item>Anything Goes Here</ion-item>
</ion-content>
```

if this has already been resolved, please point me to the solution, thanks.

**Comment by danbucholtz** [comment]
Hi @obedm503,

This works for me on my iPhone and my Android phone.  It also works in Chrome when emulating a device.  I'm using the latest Ionic.

Are you still having this issue?  Please let me know.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @obedm503, this is what it looks like for me.

![gif](https://zippy.gfycat.com/MammothIncredibleBedbug.gif)

I'm going to close this, but happy to continue discussing and re-open if you'd like.

Thanks,
Dan

**Comment by danbucholtz** [comment]
We decided we'll take a look at this and see what it takes to resolve this on desktop.

Thanks,
Dan

**Comment by xumingxin7398** [comment]
Hi,@danbucholtz. I got this issue too when use native-scroll + ionRefresher, the refresher was realy lag even the app stop for seconds, but I found it only on android 4.x. When I run the same code on android 5.x ,it works well.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#154
