### ISSUE TITLE
Android build - Array.from is not a function

### ISSUE THREAD

**Issue by rascada** [driftyco/ionic#5953]
### Ionic 2

Error in android build
![image](https://cloud.githubusercontent.com/assets/10521222/14062643/5cbe55e0-f3a6-11e5-9887-1584b365ba55.png)

`Array.from` polyfill (in index.html) did not help

**Steps to reproduce:**
1. `ionic start example -v`
2. `cd example && ionic run android -c`

**Comment by rascada** [comment]
Polyfill in `app.js` (`import 'es6-shim';`) did work

**Comment by davyzhang** [comment]
same problem here

**Comment by rascada** [comment]
same as in es6, just import polyfill in `app.ts`
```ts
import 'es6-shim';
```
es6-shim is already downloaded (because is listed in `package.json`)

**Comment by davyzhang** [comment]
Thanks @rascada , that worked

**Comment by rascada** [comment]
All templates are working now :+1:
