### ISSUE TITLE
bug: Scroll stops when cursor gets on deep nested tags.

### ISSUE THREAD

**Issue by bypotatoes** [driftyco/ionic#5954]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The first level of nesting when bug appears reproduced in [jsfiddle](https://jsfiddle.net/bypotatoes/ab2dth0L)

**Steps to reproduce:**
1. Put cursor out of red area and scroll
2. Move cursor to red area and try to scroll
3. Stuck with scroll issue</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! It does seem to happen only when its deeply nested. As you can see here i removed most of the divs and it scrolls fine now: https://jsfiddle.net/16fyzxf7/. Do you have another example that will cause the issue that is not just a bunch of divs?

**Comment by bypotatoes** [comment]
@jgw96 I don't. But the issue is exactly with nesting and my fiddle was created especially to show that. As you could notice red area is not scrollable, when white is, so fiddle shows borderline. Do you have any ideas why does it happen?

**Comment by jgw96** [comment]
Not at this time, this will have to be looked into more. I have marked this as a bug. Thanks again!

**Comment by bypotatoes** [comment]
@jgw96 tnx, I'm also going to dig more, so let me not plz if you'll find someting

**Comment by jgw96** [comment]
@bypotatoes will do!

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by bypotatoes** [comment]
Hi, it's still [the issue](https://jsfiddle.net/bypotatoes/kxmj1Lam/) with v1.3.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#153
