### ISSUE TITLE
ionic resources didn't generate 83.5x83.5@2x app icon for iPad Pro

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#5955]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic resources command didn't generate 83.5x83.5@2x app icon for iPad Pro

#### What behavior are you expecting?
ionic resources command to generate 83.5x83.5@2x app icon for iPad Pro

**Steps to reproduce:**
1. put icon.psd to resources folder
2. run ionic resources
3. warning on the xcode prpoject says it's missing the 83.5x83.5@2x app icon

```
ionic resources
```

**Which Ionic Version?** 1.x or 2.x
1.x and 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to the ionic-cli and not the framework i  will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#870
