### ISSUE TITLE
ionic 2 won't build/compile source codes on build.phonegap.com

### ISSUE THREAD

**Issue by mautematico** [driftyco/ionic#5957]
#### Short description of the problem:
ionic 2 won't build/compile source codes on build.phonegap.com

**Steps to reproduce:**
1. `ionic start myapp --V2`
2. https://build.phonegap.com/
3. resulting .apk has, basically, everything under `assets` folder:

```
.
├── assets
│   └── www
│       ├── app
│       │   ├── pages
│       │   │   ├── getting-started
│       │   │   ├── list
│       │   │   └── singlepost
│       │   └── theme
│       ├── hooks
│       │   └── after_prepare
│       ├── plugins
│       │   ├── cordova-plugin-device
│       │   │   └── www
│       │   ├── cordova-plugin-splashscreen
│       │   │   └── www
│       │   ├── cordova-plugin-statusbar
│       │   │   └── www
│       │   ├── cordova-plugin-whitelist
│       │   └── ionic-plugin-keyboard
│       │       └── www
│       └── resources
│           ├── android
│           │   ├── icon
│           │   └── splash
│           └── ios
│               ├── icon
│               └── splash
├── META-INF
└── res
    ├── drawable-hdpi-v4
    ├── drawable-ldpi-v4
    ├── drawable-mdpi-v4
    ├── drawable-xhdpi-v4
    └── xml
```

There are a lot of things under assets/www, BUT there isn't any app.boundle.js :( 

May be this is a build.phonegap issue with 2.x (and maybe 1.x, too).
Is there a way to _force_ build phonegap to actually _build_ (i.e. ionic build)?

```
Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID:	Debian Description:	Debian GNU/Linux testing-updates (sid) 
Node Version: v4.4.1
```

**Comment by mautematico** [comment]
btw, I'll try to `ionic build` locally, upload the www/build source files and see what happen. I think it should work.

**Comment by jgw96** [comment]
@mautematico Thanks for all the info! build.phonegap most likely isnt going to build a v2 app correctly because it requires compiling typescript and running your gulp build process. This is why your workaround works correctly because it runs these build processes and then those built files will build into cordova apps fine. How are you liking ionic 2 so far?

**Comment by mautematico** [comment]
The workarround did the trick, as you said, by using gulp hooks on my local machine.

I'm in love with Ionic 2, but I'm having issues with 4.4.2 blank screen. All assets are there, but they are not well processed by (I think) the webview.
My app works pretty fine on 5.1

If I use crosswalk (on phonegap build) then the only thing I get is a blue screen (my app background color). Weinre shows all assets there, but

**Comment by jgw96** [comment]
Sorry your having an issue with the older version of android! If you add crosswalk locally and run the app on your 4.4.2 device locally does it work?

**Comment by mautematico** [comment]
The workarround did the trick, as you said, by using gulp hooks on my local machine.

I'm in love with Ionic 2, but I'm having issues with 4.4.2 blank screen. All assets are there, but they are not well processed by (I think) the webview.
My app works pretty fine on 5.1

If I use crosswalk (on phonegap build) then the only thing I get is a blue screen (my app background color). Weinre shows all assets there, but for some reason, the JavaScript logic seems to be interrupted.
This happens on every device I have tested on (4.2, 4.4, 5.1)

**Comment by mautematico** [comment]
I'll try to add crosswalk locally today and report it back. I'm having issues with `ionic build android`, but I'm not sure if it's an ionic issue or an android sdk one.

**Comment by jgw96** [comment]
Awesome! If your having issues with `ionic build android` feel free to open an issue on this repo: https://github.com/driftyco/ionic-cli about it.
