### ISSUE TITLE
HTTPS CORS failed for Android device version <= 4.4

### ISSUE THREAD

**Issue by ZachBergh** [driftyco/ionic#5959]
#### Short description of the problem:
Send CORS request to RESTFul API,
When we use Android <= 4.4 device to test this, CORS request failed: request status code = 0, just send the first one "OPTION" request
work fine with iOS and Android > 4.4

#### What behavior are you expecting?
CORS success

#### Fix unperfect way
Use http instead of https, but not  safety.

http://stackoverflow.com/questions/31062231/using-cors-and-csrf-together-in-ionic-app
As this, but did not work with the answer

**Comment by dylanvdmerwe** [comment]
Isn't this something Crosswalk would sort out?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Sorry if i misunderstood but did you install the whitelist plugin? And after you installed it your still seeing the issue?

**Comment by ZachBergh** [comment]
Yes, i already installed the whitelist plugin, but still have this issue...
Just for Android device <= 4.4

**Comment by jgw96** [comment]
@ZachBergh would you be able to try Crosswalk? To enable crosswalk for your app just navigate to your ionic project in your terminal and run `ionic browser add crosswalk`. Usually with android devices under 4.4 we recommend using Crosswalk anyways as this will give you major performance enhancements and better html5 support right out of the box.

**Comment by ZachBergh** [comment]
Thanks @jgw96  i am trying ;)

**Comment by ZachBergh** [comment]
Thanks you very much, all fixed.
Awesome!!

**Comment by jgw96** [comment]
@ZachBergh awesome! Very glad to hear that fixed your issue. Thanks for using Ionic !
