### ISSUE TITLE
Omission in Native Facebook Plugin Docs

### ISSUE THREAD

**Issue by xthilakx** [driftyco/ionic#5961]
#### Short description of the problem:
[Facebook Native docs](http://ionicframework.com/docs/v2/native/Facebook/) in Ionic v2 documentation has a minor omission that causes some confusion. 

#### What behavior are you expecting?
App Name, and App ID must be passed while installing `cordova-plugin-facebook4` plugin, but the documentation does not mention it. 

`ionic plugin add cordova-plugin-facebook4`

should be 

`ionic plugin add cordova-plugin-facebook4 --variable APP_ID="123456789" --variable APP_NAME="myApplication"`

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to Ionic-native and not the ionic framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#93
