### ISSUE TITLE
Ionic v2 - Navigation - Direction: Back - Incorrect z-index of ion-pages. previous page overlay current page.

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#5968]
#### Short description of the problem:
When I try to navigate from page 1 to page 2 with opts: ***direction:back*** and using ***nav.push()***
```
this.nav.push(ItemDetailsPage, {item: item},{animate:true,direction:'back'});
```
Page 1 overlays page 2 and page 2 is no longer useable unless the z-index is modified. In the picture below, Details is page 2. 
<img width="384" alt="screen shot 2016-03-28 at 11 58 35 am" src="https://cloud.githubusercontent.com/assets/3638322/14082160/6f1045c8-f4dc-11e5-88f0-25f2bd5cb6c4.png">

#### What behavior are you expecting?
I am expecting page 2 to overlay page 1 and not the other way.

**Steps to reproduce:**
1. use nav push to navigate to a new page with opts direction set to 'back'

```
this.nav.push(ItemDetailsPage, {item: item},{animate:true,direction:'back'});
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 N/A

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by tonyawad88** [comment]
I created a plunk for it, but the cdn seems to be broken. I will test when it comes back up. 
http://plnkr.co/edit/5wTp09PwG502yLdQSsTt

**Comment by jgw96** [comment]
Just did a quick test of this with beta.10 and it does not seem to be an issue anymore. Thanks for using Ionic!

**Comment by roshandhabekar** [comment]
@jgw96  I still have same issue with my ionic details ionic 2.0.0-beta.31

**Comment by amerzad** [comment]
I have the same problem.
When I nagvigate then go back, then navigation again, it will happen on first page I navigate to. And I am using Ionic 2.0.1.

**Comment by in-sandeep-majethiya** [comment]
i have same issue with latest ionic-angular 3.2.1
