### ISSUE TITLE
Android accessibility focus issue with scrolling

### ISSUE THREAD

**Issue by ankushgoyal27** [driftyco/ionic#5970]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
In android with talkback enabled, if page has more content than the screen size, 
1) Swiping right after the last element in the scree view not scrolling to the next element properly ( overlays with bottom bar in android )
2) After focusing element in the page, if you scroll using 2 fingers ( accessibility mode) , focus border not aligns with the current position of the element. Stays in the old place.  In plain html page focus border moves along with the scroll

Issue is only with android, ios it works fine.

#### What behavior are you expecting?

Accessibility focus should align with the object in the screen when navigating through swiping right/left or when scrolling. 

**Steps to reproduce:**
1. Enable Accessibility Talkback in android
2. Access the below link in android browser (User Chrome and S6 browser)
Plain HTML : http://play.ionic.io/m/054f745b63bc - Works fine
With IONIC : http://play.ionic.io/m/f9eabad5c8e2 -  Issue with focus
3.  i) Select first button in the page, Swipe right until the last button in the current screen ( page has more button below the current view), after the last button visible on the screen, focus won't move to the next button properly
    II) Select any button in the middle of the page and scroll up or down to move the position of the button. Focus border will remain in the same old position 
``

**Comment by ankushgoyal27** [comment]
Any updates.

**Comment by mhartington** [comment]
Closing as this has been resolved outside of here.

**Comment by PhilippeMorier** [comment]
@mhartington: I would be interested how this issue was resolved?
I still see this behaviour in my app.

**Comment by magleahy** [comment]
@mhartington yes more info please.

**Comment by Kun4lpal** [comment]
@mhartington Hi i would appreciate some more information!

**Comment by novascreen** [comment]
@mhartington could you please elaborate

**Comment by nicobailon** [comment]
I am also still seeing this issue.

**Comment by dileepvarma** [comment]
Hi I have this same issue in my app. Can any one tell me how its been fixed

**Comment by botondcs** [comment]
I am also interested in the solution.

**Comment by davidcr** [comment]
I'm also having this issue even in native development on Android for information.
I would say that "outside of here" sure isn't Google.

**Comment by leon914** [comment]
Also looking for an answer for this

**Comment by Sebastiansc** [comment]
Still running into this issue
