### ISSUE TITLE
Toggling ion-tab directive with ng-if can cause order to break

### ISSUE THREAD

**Issue by deslee** [driftyco/ionic#5971]
#### Short description of the problem:

In our template, we have a set of ion-tab directives with ng-if attributes. When our controller's scope changes to toggle on a set of tabs that were previously off, the new tabs appear to the *left* of the old tabs, even though their ion-tab blocks come after the old tabs in the template.

#### What behavior are you expecting?
For the tabs to visually always be in the same order as their ion-tab blocks.

**Steps to reproduce:**
1. Make a state with an ion-tabs set. ng-if each of the ion-tab directives to a $scope variable
2. Initialize the controller where 2 of the $scope variables are false, and the remaining one is true.
3. In a $timeout, set the 2 variables false $scope variables to true.

**Which Ionic Version?** 1.x or 2.x
1.2.4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
The Ionic CLI is not involved in development, and was not configured on my development laptop.

**Comment by andreialecu** [comment]
There is a workaround here, use the `hidden` attribute instead of `ng-if`, such as:

`<ion-tab ... hidden="{{ value }}">`

**Comment by jgw96** [comment]
Hello! I would recommend to not use ngIf in this situation. Binding to the [hidden] attribute of the tab like suggested above is gonna be a much better solution for you, and should be faster than using ngIf. Is there any reason you have to use ngIf?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As there is a workaround available for this issue i will be closing this issue for now. Thanks for using Ionic!

**Comment by captjones** [comment]
You can change the tab order using just CSS.

`.tabs-icon-top > .tabs .tab-item:nth-of-type(1) { order:1; }`
