### ISSUE TITLE
TypeScript compilation issue

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#5977]
#### Short description of the problem:
I am receiving this when building the latest beta in my project. Not sure what is causing it or how to fix?

> ERROR in [default] C:/Users/dylan.vdmerwe/app/node_modules/angular2/src/facade/promise.d.ts:1:9
> Cannot re-export name that is not defined in the module.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS:
Node Version: v5.7.0

**Comment by bdoner** [comment]
Hello,

This might be related to this [angular/angular/issues/6468](https://github.com/angular/angular/issues/6468).

**Comment by jgw96** [comment]
@dylanvdmerwe That is indeed a typescript bug that popped up when angular 2 went to typescript 1.8.0 and hasnt been fixed yet. It shouldn't be causing any issues though. Is it causing your typescript not to compile?

**Comment by brandyscarney** [comment]
This workaround will resolve the error: 

https://github.com/angular/angular/issues/6468#issuecomment-176590156

and there is an open issue for this on our CLI repo here:

https://github.com/driftyco/ionic-cli/issues/848

Going to close this as a duplicate but feel free to continue the discussion over there. :smile:

**Comment by rapropos** [comment]
@brandyscarney : Is there a specific reason for recommending manually hacking up angular files instead of upgrading past the version where it is fixed? Does Ionic have some sort of showstopper conflict with >=beta7? I haven't encountered one yet.

**Comment by brandyscarney** [comment]
@rapropos We're working on [the beta.4 milestone issues](https://github.com/driftyco/ionic/issues?q=is%3Aopen+is%3Aissue+label%3Av2+milestone%3A2.0.0-beta.4) and when trying to upgrade ran into some issues with breaking changes, so we'll be updating once beta.4 is out.

**Comment by dylanvdmerwe** [comment]
I don't think this is a super crazy issue. Was just bringing it to the team's attention - everything still works fine.
