### ISSUE TITLE
Build process does not clean folder first

### ISSUE THREAD

**Issue by alzalabany** [driftyco/ionic#5980]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
if you added a page into pages folder, then later decided to delete that page "delete folder"
build will not remove it from /www/build/ folder

#### What behavior are you expecting?
using 

**Steps to reproduce:**
1. ionic start ionic2 tutorial --v2 --ts && cd ionic2 && ionic serve
2. create  a new page in ./app/pages/new_page (add .ts file etc.)
3. check /www/build/pages to confirm build copied your new page.
4. delete ./app/pages/new_page
5. folder /www/build/pages/new_page will not be deleted.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Thanks for opening this issue! As this issue is more related to the cli and not the framework i will be moving this issue to the cli repo. Please feel free to continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#877
