### ISSUE TITLE
Add box-shadow to material design toolbar

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#5983]
Ben really wants the box-shadow added.

Here's the image:

![image](https://cloud.githubusercontent.com/assets/6577830/14121348/11186024-f5c5-11e5-9ff1-e971528631c8.png)

**Comment by manucorporat** [comment]
@brandyscarney @bensperry 
```diff
.toolbar {
+    box-shadow: 0 0 4px rgba(0,0,0,0.78);
}
```

<img width="272" alt="screen shot 2016-04-17 at 21 31 41" src="https://cloud.githubusercontent.com/assets/127379/14589498/d24d079a-04e3-11e6-8d4b-3939ffd6c724.png">

**Comment by bensperry** [comment]
I mean... I love this, but we need to get @adamdbradley's opinion because I think he had concerns about performance with using a box-shadow.

**Comment by aerotoad** [comment]
I think this is included in #6187

**Comment by brandyscarney** [comment]
@manucorporat We tested the `box-shadow` approach on an android device running 4.4 (using the conference app) and it had some noticeable lag unfortunately.

**Comment by adamdbradley** [comment]
Done and done: https://github.com/driftyco/ionic/commit/6fa2faffba07981b6ac767824b6a95fe56b58e9b
