### ISSUE TITLE
ionic serve (--lab) must be running in order to build?

### ISSUE THREAD

**Issue by junerockwell** [driftyco/ionic#5984]
#### Short description of the problem:
I've noticed that I have to have `ionic serve` or `ionic serve --lab` running to be able to see changes reflect on to the simulator after I type `ionic build ios` and then run via XCode. Otherwise, if I just type `ionic build ios` and the `server (--lab)` isn't running at the same time, then the changes don't reflect at all.

#### What behavior are you expecting?
I expected to be able to type `ionic build ios` and have the changes reflect when I run the project on XCode just like Ionic 1.x

**Steps to reproduce:**
1. Make any changes. Example: change/add a text in a `page3/page3.html` (from tab template)
2. `ionic build ios` 
3. Open XCode project for *this* app. (I was using simulator iPhone5S)
4. Should expect to see the changes in that `.html`. But changes don't reflect unless I `ionic serve` or `ionic serve --lab` is running before I make the changes and type `ionic build ios` on the terminal. 
 
**Which Ionic Version?** 1.x or 2.x
Ionic 2 Beta

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
No errors.

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue is related to the cli and not the framework i will be moving the issue over to that repo. Please feel free to continue the conversation over there. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#878
