### ISSUE TITLE
Changing plugin settings in config.xml does not publish to platform settings

### ISSUE THREAD

**Issue by ChrisCoffey** [driftyco/ionic#5986]
#### The problem:
I switched facebook applications in my app and updated the necessary keys in my toplevel `config.xml`. However, after cleaning, building, and even removing/re-adding the platform the old settings still persisted. 

It turns out that changing these settings does not trigger a recreation of:
- `platforms/ios/ios.json`
- `platforms/ios/APPNAME/AppName-Info.plist`
- `plugins/fetch.json`
- `plugins/ios.json`

This results in the wrong information being used during app creation.

#### Expectation
Based on my limited understanding of the platform I expected the files above to recognize the configuration change and re-create themselves. 

**Steps to reproduce:**
1. Install `ionic-native` plugin
2. Create a page that calls
``` javascript
Facebook.login(["public_profile"])
```
3. `ionic platform add ios`
4. `ionic build ios`
5. Run your app via xcode
6. Login with facebook. You'll be taken to a FB login screen where you can add the app
7. Create a new facebook app
8. Change `APP_ID` & `APP_NAME` keys in the `config.xml`
9. `ionic build ios`
10. Repeat the login workflow & notice the old app is still being used

##### Ionic Version
2.0.0-alpha.53

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#881
