### ISSUE TITLE
Change nav-bar type attribute to accept either a string or AngularJS expression

### ISSUE THREAD

**Issue by jough** [driftyco/ionic#599]
Right now nav-bar type="class name strings" only accept class strings, but if it accepted an Angular expression _or_ a string we'd be able to change the classes on the nav-bar (and I suppose header-bar) by setting a $scope variable.

As discussed here:

http://forum.ionicframework.com/t/chaning-nav-bar-classes-on-page-loads/784/8

**Comment by shadowsyntax** [comment]
Will this work for all attributes in ionic, like `view-title` attribute in `<ion-view>`?

**Comment by adamduren** [comment]
@jough It looks like the `type` attribute was removed in place of using classes. I tried using ng-class but it doesn't seem to carry the class over to the `ion-header-bar`. Is there a new supported way to do this?
