### ISSUE TITLE
Ion-slides does not respect slider options changes after $link but before construction

### ISSUE THREAD

**Issue by bdirito** [driftyco/ionic#5990]
#### Short description of the problem:

ion-slides has a state where the slider is not yet initialized but the options for slider construction are bound (and cannot be updated)
#### What behavior are you expecting?

I would expect that if slider has yet not been initialized slider options can still be modified.

**Steps to reproduce:**
1. create a directive
2. set an element to contain an <ion-slides options=slider_options> element in the link function
3. compile & link the element
4. note that slider is still null
5. hence modify slider_options object
6. note that your slider_options change has not taken effect 

http://codepen.io/tisepti/pen/bpqQpN

Ionic 1.2.4

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.2.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#151
