### ISSUE TITLE
Inconsistent ion-segment behavior on windows phone

### ISSUE THREAD

**Issue by roblouie** [driftyco/ionic#5994]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
On windows platform only, ion-segment is not styled as active if it is used outside of a toolbar element.

#### What behavior are you expecting?
Consistent behavior on windows where ion-segment buttons can be marked as active when used outside of a toolbar element.

**Steps to reproduce:**
1. Define an ion-segment outside of a toolbar element
2. Give the ion-segment buttons
3. Click the buttons on each platform, notice that on windows only the active style is not applied.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS:
Node Version: v4.4.1

**Comment by brandyscarney** [comment]
Thanks so much for the issue and the PR! I'm going to take a look at this soon. :smile:

**Comment by brandyscarney** [comment]
Fixed by https://github.com/driftyco/ionic/pull/5995 :+1:
