### ISSUE TITLE
bug: Searchbar issue with iOS

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#5996]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I'm having a really weird issue with iOS. It is probably Mobile Safari browser that is causing it. The case is that I have a page that has an iframe and inside the iframe is a third party library that is registering for click events. And below that page is another page (main page) that has a search bar. And if that search bar does not have anything typed into it then browser won't fire click events for that third party library. If I type at least 1 character into the search bar then everything works. It also seems to be related to that issue: http://www.shdon.com/blog/2013/06/07/why-your-click-events-don-t-work-on-mobile-safari. I presume the problem is caused by the attribute type="search". Currently for the workaround when the page is opened that contains the iframe then I'm adding space character to search bar value to get around the issue.

As for the fix I suggest setting type="text" for iOS searchbar if it does not screw up anything.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
I added the ability to pass the `type` to the searchbar. It defaults to `"search"` but you can pass `"text"` to it for your specific use case:

```
<ion-searchbar type="text"></ion-searchbar>
```

This will be in the `beta 9` release but if you'd like to try it sooner please install the nightly:

```
npm install --save ionic-angular@2.0.0-beta.8-201606131945
```

Thanks for the issue!
