### ISSUE TITLE
NavRouter: getPathRecognizerByComponent fails if ion-nav is inside a router-outlet.

### ISSUE THREAD

**Issue by jimitndiaye** [driftyco/ionic#5997]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I have an ion-nav on a page which is in turn navigated to using angular2/router. I use angular2/router because I need this component to be asynchronously loaded. I get a null-reference error as a result of NavRouter's getPathRecognizerByComponent

#### What behavior are you expecting?
That I don't get an error.

**Steps to reproduce:**
1. Include an ion-nav in a component
2. Navigate to that component using the built-in router (angular2/router)
3. 

```
// component.html
<header>
  <ion-toolbar position="top">
    <!-- some other components -->
  </ion-toolbar>
</header>
<main>
  <ion-content>
    <ion-row>
      <ion-column>
        <!-- some unrelated component -->
      </ion-column>
      <ion-column>
       <ion-nav [root]="rootPage"></ion-nav>
      </ion-column>
      <ion-column >
      </ion-column>
    </ion-row>
  </ion-content>
</main>
<footer>
  <ion-toolbar position="bottom">
    <!-- some other component -->
  </ion-toolbar>
</footer>

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 Stack trace: 
```TypeError: Cannot read property 'find' of undefined
    at eval (eval at <anonymous> (http://localhost:3000/js/main.bundle.js:393:2), <anonymous>:84:43)
    at Map.forEach (native)
    at NavRouter.getPathRecognizerByComponent (eval at <anonymous> ```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I have added this issue to the 2.0.0-beta.5 milestone as we are working on ionic 2 working with the angular 2 router as a feature for beta.5. Thanks again!
