### ISSUE TITLE
[V2] undefined is not a function (most tried Android devices)

### ISSUE THREAD

**Issue by bel3atar** [driftyco/ionic#5999]
My app runs fine on the browser, and after trying it on Android phone it only worked on one out of four.
The Chome inspector helped show where the problem is, but none of that code is written by me.
![2016-03-31-122541_1600x900_scrot](https://cloud.githubusercontent.com/assets/2218261/14174587/331c9694-f73d-11e5-993a-727449379158.png)

![2016-03-31-122638_1600x900_scrot](https://cloud.githubusercontent.com/assets/2218261/14174565/172f134e-f73d-11e5-8cd2-79fd18a26696.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you be able to provide me a plunkr or codepen of your code so that I can use it to repro this issue? That error looks like it's coming from a polyfill, which means it's related to some es6 code that you are using. Thanks again!

**Comment by bel3atar** [comment]
Thanks for the reply, but why would a polyfill work on some devices without others?
Furthermore, I have no idea which part of my code is behind this error; I'll have to go through the whole code manually and try out individual parts to find out where the error originates from.
What functionality does _arrayFromMap() polyfill exactly? I don't use Map anywhere in my app.

**Comment by jgw96** [comment]
Sorry, should have thought about this earlier. Would you mind putting `import 'es6-shim'; ` at the top of your app.ts and see if that fixes your issue for you? Thanks.

**Comment by bel3atar** [comment]
@jgw96 yep that solved it.

**Comment by jgw96** [comment]
@bel3atar Awesome! Sorry, i should have thought about that solution earlier!

**Comment by bel3atar** [comment]
Is this already documented somewhere?
