### ISSUE TITLE
Default to Material Design for desktop web

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6003]
We see "Material Design" as the preferred desktop web UI. By default, use the `md` mode for all desktop browsers. It's debatable if desktop Windows browsers should get Windows platform or not, but while Windows users are browsing the web, they are using the web platform. On any desktop browser, we want the "web" platform to have a common UI. However, when an Ionic app is placed inside of a shell that runs specifically on windows, it should then get the windows platform.

**Comment by jimitndiaye** [comment]
I've been hacking this using the Platform class. Would be nice to have it built in.

**Comment by adamdbradley** [comment]
@jimitndiaye Cool, the platform class, and more so the config is built so apps can easily customize which mode to use under certain criteria. We still have to create some good demos showing how to do this.

**Comment by pbreit** [comment]
@adamdbradley Can you comment on the efficacy of Ionic for building a) mobile-optimzed web apps and b) desktop web apps?

**Comment by Shadowfaxenator** [comment]
How to build an app as a website?

**Comment by pbreit** [comment]
Slack, for example. Mobile apps, desktop app, web site and desktop apps all quite similar.
