### ISSUE TITLE
Custom component for ion-navbar causing changes in design (v2)

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#6004]
#### Short description of the problem:
Creating a custom Component for `ion-navbar` causing changes in design

I working with ionic tabs and i also have a header on each tab.
So instead of copy paste the header on each tab i wanted to create a Component.
this cause for changes in the design

#### What behavior are you expecting?
I was expecting to the same header on each tab like if it were written inline

**Steps to reproduce:**
1. get starter-tabs project
2.  create a Component with the folowing html
```html 
<ion-title>
  Bla bla
</ion-title>
<ion-buttons left (click)="openMenu()">
  <button>
    <ion-icon name="menu"></ion-icon>
  </button>
</ion-buttons>

```
3.  use the directive in the pages 

```js
import {Component, Directive} from 'angular2/core';

@Component({
    selector: 'my-header',
    templateUrl: 'build/common/header/header.html'
})
export class MyHeader {
    constructor(){ }
}
```
And in the page:
```html
<ion-navbar *navbar>
  <my-header></my-header>
</ion-navbar>

<ion-content padding class="page1">
  <h2>Welcome to Ionic!</h2>
  <p>
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <p>
    Take a look at the <code>www/app/</code> directory to add or change tabs,
    update any existing page or create new pages.
  </p>
</ion-content>
```
picture with the custom component: 
![selection_001](https://cloud.githubusercontent.com/assets/9999184/14186756/8e787526-f788-11e5-9700-b315204d2f95.png)

without:
![selection_002](https://cloud.githubusercontent.com/assets/9999184/14186762/96624924-f788-11e5-81de-df4720d11646.png)

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.9.0

**Comment by jgw96** [comment]
Hello! We are currently investigating this bug, but we have ran into some issues regarding content projection. I will keep you updated on the status of this issue!

**Comment by brandyscarney** [comment]
Hey @royipressburger, so the reason the styles aren't showing up is because you need to inject `IONIC_DIRECTIVES` in your custom component:

```
import {Component, Directive} from 'angular2/core';
import {IONIC_DIRECTIVES} from 'ionic-angular';

@Component({
    selector: 'my-header',
    templateUrl: 'build/common/header/header.html',
    directives: [IONIC_DIRECTIVES]
})
export class MyHeader {
    constructor(){ }
}
```

While this will fix your immediate use case, there is still an issue with content projection where `<ion-buttons left>` is not placed correctly in the markup because of the `my-header` wrapper. Going to keep this open so we can discuss a solution to the content projection. :smile:

cc @adamdbradley

**Comment by royipressburger** [comment]
@brandyscarney Is this what you talking about?
![selection_003](https://cloud.githubusercontent.com/assets/9999184/14365716/d4d330e4-fd17-11e5-9b4a-fa904e9c95e8.png)

**Comment by brandyscarney** [comment]
@royipressburger Can you paste the markup, please?

**Comment by royipressburger** [comment]
@brandyscarney  what do you mean by markup?

**Comment by brandyscarney** [comment]
@royipressburger Sorry, the html code you are writing for the navbar. :smile:

**Comment by royipressburger** [comment]
The header component
```html
<ion-title>
  {{title}}
</ion-title>
<ion-buttons (click)="openMenu()">
  <button>
    <ion-icon name="menu"></ion-icon>
  </button>
</ion-buttons>
```

and the useage:
```html
<ion-navbar *navbar>
  <my-header [title]="title"></my-header>
</ion-navbar>
```

**Comment by mattfolkard** [comment]
Not a solution, but a workaround: place <ion-navbar> in the custom component.

Header component:
`<ion-navbar *navbar>
<ion-title>
  {{title}}
</ion-title>
<ion-buttons (click)="openMenu()">
  <button>
    <ion-icon name="menu"></ion-icon>
  </button>
</ion-buttons>`
</ion-navbar>
Usage:
` <my-header [title]="title"></my-header>`
Works for me!

**Comment by royipressburger** [comment]
@mattfolkard This did not worked for me.. still when openign via `ionic lab` its looks like the picture above(just android)

**Comment by royipressburger** [comment]
@brandyscarney Hi, Is there anything I do as a work around? or just play with the css?

**Comment by royipressburger** [comment]
@adamdbradley I didn't really understand you.
But changing the HTML worked for me..
```html
<ion-navbar *navbar>
  <ion-title>
    {{title}}
  </ion-title>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
</ion-navbar>
```

Looks like the `<ion-buttons>` is the cause

**Comment by jgw96** [comment]
Hello @royipressburger if you take a look at our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) for beta.10 you will see an example of the new way to use navbars and headers. If you could give it a try that would be great!

**Comment by royipressburger** [comment]
@jgw96 So the problem now is a bit diffrent.. It looks like the header width is being ignore and some componetest are going before him or behind him 

![image](https://cloud.githubusercontent.com/assets/9999184/16546604/5f21fd82-4158-11e6-9eee-aa5da50f45e9.png)


![image](https://cloud.githubusercontent.com/assets/9999184/16546608/73b7ede2-4158-11e6-9378-ec6172886e1f.png)


As you can see on ios the header is above the content.. and on android the header is behind the tabs (I think I cant see it.)

**Comment by jgw96** [comment]
@royipressburger Would you mind making a plunker that demonstrates this issue? You can use [this](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) plunker as a template. Thanks!

**Comment by royipressburger** [comment]
@jgw96 there we go http://plnkr.co/edit/AQMUk7aGZkaFR2jYrfXD?p=preview :)
As you can see the `h1` tag is behind the header

**Comment by brandyscarney** [comment]
So the only components that should be children of the page should be:

```
ion-header
ion-content
ion-footer
```

I'd recommend changing your custom header component to:

```
@Component({
  selector: 'header'
  template: `
  <ion-navbar primary>
    <ion-title>
      Ionic 2
    </ion-title>
  </ion-navbar>`
})
```

and then including it as:

```
<ion-header>
  <header></header>
</ion-header>
```

**Comment by royipressburger** [comment]
@brandyscarney Thanks looking good. Guess you can close this

**Comment by jgw96** [comment]
Thanks for using Ionic! Glad this was solved (:

**Comment by MT--** [comment]
in 3.6.0, this will cause the `.statusbar-padding` class to be incorrectly applied for iOS, since it relies on the `:first-child` of the `<ion-header>`... your custom component should not include `<ion-toolbar>` or `<ion-navbar>`, but should be a child of one of these components in the header for correct styling on iOS
