### ISSUE TITLE
nav.pop() not working after showing alert prompt

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6005]
**Ionic v2**

**Steps to reproduce**
1. Navigate from page A to page B
2. Create new Alert prompt and show the alert by 
> this.nav.present(prompt)
3. On alert handler call 

> this.nav.pop()
4. It won't work. promise returns false.

**Comment by jgw96** [comment]
Hello @dheeran1 ! Thanks for opening an issue with us! This is a known issue for us and will be fixed in beta.4! Thanks for using Ionic!

**Comment by dheeran1** [comment]
@jgw96  is this issue got fixed in beta 4 release??

**Comment by dheeran1** [comment]
Please reopen the issue. It didn't got fixed
