### ISSUE TITLE
gulp sass error

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#6010]
#### Short description of the problem:

I had to install sass on my Ionic project. I felt like jesus christ walking with the crux. 
I finally managed uniting several solutions found around.

#### What behavior are you expecting?

I expect to run `ionic setup sass` and properly install sass

**Steps to reproduce:**
This how i manage to install sass:
1. sudo npm install -g n
2. n 0.12.7
3. rm -R node_modules/ 
4. npm install node-sass@3.3.3 
5. sudo npm -g install node-gyp@3
6. npm uninstall gulp-sass
7. npm install gulp-sass@2 
8. npm rebuild node-sass 
9. ionic setup sass

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
You check it out why there is this behavior.
Or point out in the docs that node.js must be downgraded to 0.12.7 version and that other steps may be necessary in order to install sass.

**Which Ionic Version?** 1.x or 2.x

Ionic 1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.0.1
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this issue is more related to the CLI and not the framework I will be moving this issue over there. Please feel free to continue the conversation over there, thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#891
