### ISSUE TITLE
Missing 3d transform in refresh controller

### ISSUE THREAD

**Issue by N0ps32** [driftyco/ionic#6016]
#### Short description of the problem:

This is more a question than a problem since I've already solved it but here it goes:
refresherController.js uses translateY for the overscroll effect resulting in really bad performance on Android devices (and probably also on iOS).

I replaced 
```
scrollChild.style[ionic.CSS.TRANSFORM] = 'translateY(' + val + 'px)';
```

with
```
scrollChild.style[ionic.CSS.TRANSFORM] = 'translate3d(0,' + val + 'px,0)';
```

resulting in a noticeable performance boost since the animation is now 3D accelerated by the GPU.

My question is if there is a specific reason why you don't use a 3d translate here (compatibility etc.) or can I open a pull request and replace this for everybody?

**Which Ionic Version?** 1.x or 2.x
1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: /bin/sh: lsb_release: command not found 
Node Version: v5.10.0

**Comment by danbucholtz** [comment]
Hi @N0ps32,

Thanks for letting us know about this.  I am going to close this issue and work off of the PR going forward.  I think we can get this merged in as long as it works with iOS 7 and above.  I need to verify that.

Thanks for contributing to Ionic!

Thanks,
Dan
