### ISSUE TITLE
ENOENT spawn error with ionic start

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6018]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I upgraded to beta.23 and started to get an error when created a new project using 'ionic start foo --v2 --ts'.
The error in red says 
"Unable to spawn commandError: spawn npm ENOENT (CLI v2.0.0-beta.23)."

I don't even know what it did to the project. 
#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic start foo --v2 --ts
2. it builds and creates the proyect
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue related to the ionic cli and not the framework i will be moving this issue to that repo. Feel free to continue the conversation over there! Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#892
