### ISSUE TITLE
Range Slider - Allow vertical

### ISSUE THREAD

**Issue by SP1966** [driftyco/ionic#6019]
#### What behavior are you expecting?

A vertical slider would offer greater one handed usability in many situations on mobile devices. I'm thinking something in line with what Angular Material have implemented: 
https://material.angularjs.org/HEAD/demo/slider

**Comment by manucorporat** [comment]
I agree, the Angular Material range looks very accesible (supports touch/click/keyboard) and well implemented.

**Comment by brandyscarney** [comment]
@SP1966 Are you requesting this to be added to Ionic 1 or 2?

**Comment by SP1966** [comment]
Brandy, Ionic 2! Sorry, I have to figure out how to add those tags in when creating a issue.

**Comment by brandyscarney** [comment]
@SP1966 Thanks! Labels are something we have to add. :smile:

**Comment by adamdbradley** [comment]
Absolutely, we need to add the keyboard events to this, and the internals to the existing Range is setup to work with vertical ranges too. However, we probably won't be able to complete the vertical range by our release candidate. I'll take this off of the beta9 milestone, but we'll leave this open to still be completed. Thanks

**Comment by SteffenTallieu** [comment]
+1

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by Xal3ph** [comment]
We are hoping for a vertical range as well.  I know there are several work arounds to just the out of the box html range, but having it built into this component would be much cleaner for the app developer.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#27

**Comment by comfortme** [comment]
hello @jgw96 
any news on this feature ?

**Comment by sal-durrani** [comment]
This is definitely a feature I've been wanting for a while!  Any updates?

**Comment by gregor-srdic** [comment]
Is this coming anytime soon? Pretty pretty please :P
