### ISSUE TITLE
bug: ionic start options --appname or --id don't work

### ISSUE THREAD

**Issue by csantanapr** [driftyco/ionic#6025]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Creating a new app and specify --appname and --id doesn't work

To reproduce:
```
$ ionic -v
1.7.14
$ cordova -v
6.1.1
ionic start --appname exampleapp --id com.example.app  example
```

Expected Results:
example/config.xml
Should have `<widget id="com.example.app"`
and `<name>exampleapp</name>`

Actual Results:

$ cat example/config.xml | grep widget
`<widget id="com.ionicframework.starter" `

$ cat example/config.xml | grep \<name\>
    `<name>HelloCordova</name>`

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! As this issue is related to the ionic cli and not the framework i will be moving this issue to the cli repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#894
