### ISSUE TITLE
v2 docs select - missing ion-item

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#6027]
#### Short description of the problem:

Basic usage select
http://ionicframework.com/docs/v2/components/#select

The example in the documents needs to be wrapped in ion-item (like the multi-select example correctly is) 

#### What behavior are you expecting?

Without ion-item, the markup does not work (and makes entire form selectable)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#530

**Comment by brandyscarney** [comment]
Thanks for the issue! I moved this to the site repo so we can get the docs fixed. :smile:

**Comment by alexbainbridge** [comment]
Dont thank me @brandyscarney , you are doing all the hard work! Thank you again for your efforts
