### ISSUE TITLE
Content.addScrollListner can't read class variables

### ISSUE THREAD

**Issue by warner-pinz** [driftyco/ionic#6029]
#### Short description of the problem:
Content.addScrollListner can't read class variables

#### What behavior are you expecting?
I want to access the instance variable on page scroll.

**Steps to reproduce:**
1.  Use the sample code from the Ionic2 documentation http://ionicframework.com/docs/v2/2.0.0-alpha.55/api/components/content/Content/
2. I see the console output saying 'They see me scrolling...'
3. Adding an instance variable  ctr:number = 1;
4. Upon scrolling in content, I still see the message 'They see me scrolling...' but the prints "NaN" in the console log.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by adamdbradley** [comment]
Try using `this.content.addScrollEventListener(this.myScroll.bind(this));`
