### ISSUE TITLE
console.log on Device only work on Cordova

### ISSUE THREAD

**Issue by luco** [driftyco/ionic#6031]
Hey,

I tried to console.log on my device. It just don't work. On browser it's ok, but on device, none. It seems that the problem it's with ionic since I created an app with cordova and it worked.

I tried everything, since setting `window.cordova.logged.__deviceReady();` to reinstalling cordova, ionic and etc. None worked.

This is happening with any Ionic starter pack, since `blank` to `sidemenu`.
 

My info:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you run `cordova plugin list` and post the output here please? It sounds as if the `console` plugin is not installed.

**Comment by luco** [comment]
@jgw96 Hey, thanks for replying. Yes, `console` it's installed. Check my installed plugins below:

cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova.plugins.diagnostic.api-22 2.3.10-api-22 "Diagnostic"

As I said, it even works on Ionic starter packs, as `sidemenu` or `blank`, which contains `console` installed.

**Comment by jgw96** [comment]
Hey @luco! Im having a little trouble reproducing your issue. Here are the exact steps im performing. I `start` an ionic project using sidemenu. Add some console logs throughout my app. `ionic run android` onto my nexus 6 and then inspect with chrome://inspect/#devices and i can see the console logs. Is this radically different than what your doing?

**Comment by luco** [comment]
@jgw96 Hey! Thanks for replying! I didn't test with Android, only on iOS over Xcode. I think it only happens with Xcode, since I can get logs on Chrome, while debugging.

**Comment by jgw96** [comment]
No problem at all! So i just thought of an idea you can try. Have you used the Safari debugger with the ios emulator and see if you can see the console.logs there? Heres an article on how to use it: http://docs.ionic.io/docs/safari-inspector. Let me know if that works for you! Ill consider this issue closed for now.

**Comment by luco** [comment]
@jgw96 Ok, I don't know why, but it started working. But, it still not working on my controllers.js. Any idea? Works on $ionicPlatform.ready and even on a factory, but not on controller.
