### ISSUE TITLE
Ionic Beta does not install with missing execSync.

### ISSUE THREAD

**Issue by trb143** [driftyco/ionic#6032]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I managed to install ionic beta 22 last week but needed to reinstall it this week.  Now all I get is 

 OpenLP2  sudo npm i -g ionic@beta

<<<<<<worked install goes here >>>>>>>

npm http 304 https://registry.npmjs.org/is-arrayish
/bin/ionic -> /lib/node_modules/ionic/bin/ionic

> ionic@2.0.0-beta.23 postinstall /lib/node_modules/ionic
> node lib/tasks/postinstall

/usr/lib/node_modules/ionic/lib/tasks/postinstall.js:9
execSync(cmd, {stdio: [0,1,2]});
^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/lib/node_modules/ionic/lib/tasks/postinstall.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0
➜ 

#### What behavior are you expecting?
A working install which I can use to start the server etc.
I have uninstalled NPM / node and deleted all the libraries and done a clean install but no luck.

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Fails as ionic is not installed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this issue is related to the ionic cli and not the framework I will be moving this issue to the cli repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#895
