### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6034]
More of a suggestion:

For the future if you guys are thinking of doing different screen sizes like tablets, a dropdown button would be an important component to add. This will work great for navigation for those screen sizes.

**Comment by jgw96** [comment]
Hey @Bandito11 ! So ive been discussing this with the team and it looks once we get our popover component that is slated to come in beta.7 (https://github.com/driftyco/ionic/issues/5420) out then you will be able to use this to get the dropdown functionality. Feel free to chime in on that issue, and thanks for using ionic!
