### ISSUE TITLE
Show-Hide-When for phone or tablet assertion

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6037]
**Ionic v2** **future requirement**

Please provide the feature for resolving Show-Hide-When for phone or tablet assertion

**Comment by brandyscarney** [comment]
Hey @dheeran1, thanks for the issue. The available platforms that can be used with the `showWhen`/`hideWhen` directive can be found here: http://ionicframework.com/docs/v2/api/platform/Platform/#is

- android
- cordova
- core
- ios
- ipad
- iphone
- mobile
- mobileweb
- phablet
- tablet
- windows

So you could use `hideWhen="tablet"` or `showWhen="tablet"`. You could also use [media queries](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/) to target specific screen sizes. Does that solve your problem?
