### ISSUE TITLE
Problem to run in emulator

### ISSUE THREAD

**Issue by zhouhao27** [driftyco/ionic#6039]
I created a blank application:

> ionic start demo blank --v2 --ts

And trying to run:

> ionic emulate ios

Then I got the following error message:

> No target specified for emulator. Deploying to iPhone-6s-Plus, 9.3 simulator
2016-04-05 10:30:30.024 simctl[2343:32938] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Existing job (com.apple.CoreSimulator.CoreSimulatorService.117.15.1.dltcnwGXJZL4) is from an older version and is being removed to prevent problems.
logPath: /Users/myname/Projects/test/demo/platforms/ios/cordova/console.log

My system information:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.2 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3 Build version 7D175 
```

When I tried to run in android:

> ionic run android

I got:

> unning command: /Users/myname/Projects/demo/hooks/after_prepare/010_add_platform_class.js /Users/myname/Projects/demo
add to body class: platform-android
ANDROID_HOME=/Users/myname/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home
ERROR running one or more of the platforms: Error: adb: Command failed with exit code 1 Error output:
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
You may not have the required environment or OS to run this project

Have no idea why it says my **Address already in use**.

**Comment by zhouhao27** [comment]
I tried ionic-conference-app, it's no problem to run in my emulator. I compare the code. The only differences are:

1. I'm using typescript in my project
2. I'm using a few plugins in my project.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the Ionic cli, and not the framework i will be moving this issue over to that repo. Please feel free to continue the conversation over there! Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#902
