### ISSUE TITLE
different ion-nav-view can not fire $ionicView.leave and $ionicView.afterLeave but the same ion-nav-view work correctly

### ISSUE THREAD

**Issue by wzhsh90** [driftyco/ionic#6042]
ionic version 1.2.4-nightly-1917

1、my test code contains three pages,but they stay in different ion-nav-view 
page A :    <ion-nav-view name="menuContent"></ion-nav-view>
page B:     <ion-nav-view></ion-nav-view>
page C:     <ion-nav-view></ion-nav-view>

case 1:
A-->B-->C-->B

$scope.$on('$ionicView.loaded', function() {
    console.log("$ionicView.loaded");
  });
  $scope.$on('$ionicView.beforeEnter', function() {
    console.log("$ionicView.beforeEnter");
  });
  $scope.$on("$ionicView.enter", function() {
    console.log("$ionicView.enter");
  });
  $scope.$on('$ionicView.afterEnter', function() {
    console.log("$ionicView.afterEnter");
  });

  $scope.$on('$ionicView.beforeLeave', function() {
    console.log("$ionicView.beforeLeave");
  });
  $scope.$on('$ionicView.leave', function() {
    console.log("$ionicView.leave");
  });
  $scope.$on('$ionicView.afterLeave', function() {
    console.log("$ionicView.afterLeave");
  });
  $scope.$on('$ionicView.unloaded', function() {
    console.log("$ionicView.unloaded");
  });
both controller B and controller C events fire  all

case 2:
A-->B-->C-->A
the controller B all events fire ,when c-->A only fire beforeLeave.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a codepen or plunkr with your code? Im having a little bit of a hard time understanding your issue and would love to be able to reproduce it myself. Thanks!

**Comment by wzhsh90** [comment]
I send three times email to you , but I can not sure you received it.
this is my codepen address http://codepen.io/wzhsh90/pen/yOPREv ,all infos printed by browser's console log.

**Comment by jgw96** [comment]
@wzhsh90 I am very sorry, i dont seem to have received any emails? So, after testing with your codepen all the events seem to be firing for me fine. Also, i do not see a view named C? I only see view a and view b? Is there something that im missing or not understanding? Sorry!

**Comment by wzhsh90** [comment]
I am so sorry to you , I forget to change 'Search' to 'C ', I updated my codepen , you can test it again .So sorry spend you so much time.

**Comment by danbucholtz** [comment]
Hi @wzhsh90,

This should be resolved in the nightly build.  We did a lot of work with the life cycle events recently.  Can you test on the latest build?  Let me know if you need some help.

http://code.ionicframework.com/#nightly

I guess our staging site hasn't deployed in the past week or so, but we do have new and improved docs.
http://ionic-site-staging.herokuapp.com/docs/nightly/api/directive/ionView/

Basically, in addition to dispatching the event upwards (emit) from the correct scope, but we also now fire events downwards (broadcast) to work with ui-router nested views.

```
$scope.$on("$ionicParentView.enter", function(event, data){
   // woot, I received the event!
});

$scope.$on("$ionicView.enter", function(event, data){
   // woot, I received the event!
});
```

**Comment by wzhsh90** [comment]
Hello:

   I test it by my codepen http://codepen.io/wzhsh90/pen/yOPREv. It's works correctly now.

thank you.
