### ISSUE TITLE
selector attribute for @Page decorator not working

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6043]
** ionic v2**

I have a list page and a detail page.
I was building a dual pane layout for tablet. ie list in left side and detail in right side.
I'd named selector for both list (selector: "my-list") and detail (selector: "my-detail") page separately. I tried to import by creating element directive like 

`<my-list></my-list> <my-detail></my-detail> `

in dual pane layout. but unfortunately view didn't got imported .

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Would you mind asking this question over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/)?  Theres some awesome people on there that will be able to help you with this issue! Thanks again!

**Comment by dheeran1** [comment]
Hi,

I'm not getting any response in forum. Can you please advise me on clean some workaround to follow.
