### ISSUE TITLE
No back button when switching between tabbed to non-tabbed pages !!

### ISSUE THREAD

**Issue by dujuanxian** [driftyco/ionic#6044]
As the problem is rushly closed at https://github.com/driftyco/ionic/issues/4213 , I re-opened it again as I still struggling for this issue in my project and ionic 2.0 is still Beta version.

**Comment by danbucholtz** [comment]
Hi @dujuanxian,

We are aware of this issue. But this is a limitation of the way things are setup at the moment and ui-router. We will address this in 2.0. Until then there is no easy fix right now.

This is a big reason we designed a new routing/navigation system in 2.0.  To allow more flexibility/creativity, and to escape some of the limitations of ui-router.

We appreciate you choosing Ionic, and we are happy to help in any way we can.

Thanks,
Dan
