### ISSUE TITLE
Segment button gets reset when back pressed. Not maintaining the state.

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6045]
** ionic v2 **

I use segments with 2 segment button.
each segment contains a list. on item click event, page will navigate to detail page. now when I press back button of browser, segment highlight gets reset.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind asking this question over on our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/)? I think you will be able to get a better and faster answer over there. Thanks!

**Comment by dheeran1** [comment]
No response from forum guys.
https://forum.ionicframework.com/t/segment-button-gets-reset-when-back-pressed-not-maintaining-the-state/48541

Is there any workaround?

**Comment by jgw96** [comment]
Would you mind putting together a plnkr example that i can use to repro this issue? That would be great! Heres a template i made that you can use to make your example: http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Comment by dheeran1** [comment]
This issue is from angular https://github.com/angular/angular/issues/7965
