### ISSUE TITLE
Alert close, input gets focused

### ISSUE THREAD

**Issue by raducostea** [driftyco/ionic#6047]
When i click the Ok button on the alert and there is an input behind it, the input gets focused. 
I see this issue was in ionic 1 and it was fixed by adfing a timeout to the dismiss. I've added a 400ms timeout to the dismiss btn and it works but not sure if its the correct way. 

Thanks

**Comment by jgw96** [comment]
Hello!  Thanks for opening an issue with us! Would you mind running `ionic info` inside your ionic project and posting the output here please?

**Comment by raducostea** [comment]
Sure

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v4.4.0

To fix this i've added a timeout in alert.js
```

        if (shouldDismiss) {

            setTimeout(function () {
                _this.dismiss(button.role);
            }, 100);
        }
```

**Comment by BlackFoks** [comment]
Any news on this? The bug still exists (beta 9) and it affects select list pop-ups as well (they use alerts under the hood).

**Comment by jgw96** [comment]
Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
