### ISSUE TITLE
background Page cursor showing in the foreground Page

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#6048]
#### Short description of the problem:

Page1 has a form with inputs and a button to open a SearchPage, opening SearchPage with Page1 having focus in an input leaves the cursor of the background page (Page1) blinking over the content of SearchPage.
#### What behavior are you expecting?

Not showing the cursor in SearchPage

**Steps to reproduce:**
Don't know, it happened in a IOS device.

 **Which Ionic Version?** 2.x
The image below shows what happens.

![img_3785](https://cloud.githubusercontent.com/assets/70573/14296264/a92bc3c6-fb4f-11e5-8c3d-7a340465886b.PNG)

**Comment by mashah1** [comment]
@jgw96 is there any solution for this yet?

**Comment by mashah1** [comment]
@Ionitron Please let us know if you have worked on this type of issue

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#150
