### ISSUE TITLE
Alert scrolling events being forwarded to Page

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#6049]
#### Short description of the problem:
If you have a scrollable content and shows an Alert, scrolling/flying in the alert makes the pages content scroll.

#### What behavior are you expecting?
Do not scroll the page content while executing a scrolling move in an Alert.

**Steps to reproduce:**
1. Create a Page with a populated ion-list and a button to open an Alert;
2. run on IOS;
3. Fly your finger in the top-down or bottom-up direction;

**Which Ionic Version?** 2.x
Only on iOS

**Comment by raducostea** [comment]
This happens to me as well. To fix this i've changed the alert.js component inside the ionic-angular node module.
On line 327 i've added:

`   if (shouldDismiss) {

            setTimeout(function () {
                _this.dismiss(button.role);
            }, 100);
        }`

I see this also happened in Ionic 1 and it was fixed by adding a timeout to the dismiss action.

**Comment by dylanvdmerwe** [comment]
@raducostea can you create a pull request?

**Comment by raducostea** [comment]
Well that is some sort of hack. The original code is:

```
if (shouldDismiss) {
      setTimeout(() => {
        this.dismiss(button.role);
      }, dismissDelay || this._config.get('pageTransitionDelay'));
    }
```

So i just changed with a static value of 100
```
if (shouldDismiss) {
      setTimeout(() => {
        this.dismiss(button.role);
      }, 100);
    }
```

Not sure if this is the right call.

**Comment by BugsBunnyBR** [comment]
@raducostea , after the timeout, the alert will disappear, right? If this is the case, I can't use this.

**Comment by jgw96** [comment]
Hello all! I just tested this with beta.10 and this does not seem to be an issue anymore. Thanks for using Ionic!
