### ISSUE TITLE
feat request: make grid responsive by screen size

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6050]
Hi,

This is not an issue more of a suggestion. I am doing a Windows 10 desktop app, and I was thinking "If I decided to do an app that worked for desktop and mobile I would have to make the grid work on different screen sizes".

So my suggestion is that the grid works on different screen sizes like:

width for mobile: width < 600px
width-m for tablets: width > 600px
width-L for Desktops: width > 1200px 

or something similar. Same with the offsets.

**Comment by adamdbradley** [comment]
These sizes should be configurable. Specifically which lines of code would you liked changed?

**Comment by Bandito11** [comment]
No I know how to do that. (In fact I think you guys did it in a similar way I did in the past in sass). I've meant like add it to a future installment.

**Comment by adamdbradley** [comment]
Do you mean for ionic1 or ionic2? So far these numbers have been working great for us: https://github.com/driftyco/ionic/blob/2.0/ionic/components/grid/grid.scss#L13

**Comment by Bandito11** [comment]
This would be for ionic 2. I don't meant to change it, but like add option so that the grid is implemented for different sizes. Like this grid will be implemented if the screen size is large.

For example like this. 

```
      ion-col {
      ***
        }
    

      ion-col-m {
       ***
      }



      ion-col-l {
        ******
}
```

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by dylanvdmerwe** [comment]
As per my suggestion else where, I believe Ionic's grid needs to be enhanced at some point in the future. I would highly recommend basing it off something like [bootstrap 4.](https://v4-alpha.getbootstrap.com/layout/grid/)

**Comment by mikewagz** [comment]
+1 for a responsive grid system a la Bootstrap!

**Comment by brandyscarney** [comment]
@mikewagz Please add a thumbs up on the original comment, we can sort issues by these. :)

**Comment by seanmavley** [comment]
@brandyscarney I came across this answer: http://stackoverflow.com/questions/36018146/ionic-2-responsive-grid

Is there somewhere in the ionic 2 docs that mention the use of the `responsive-sm` attributes?

**Comment by brandyscarney** [comment]
@seanmavley Unfortunately it probably isn't documented. I am currently working on improving the grid system and with the improvements I'll be writing new documentation for it. I'll update this issue once I have something for you all to try. Thanks!

**Comment by brandyscarney** [comment]
Hey everyone, I have been working on the new grid system based on Bootstrap 4. Here is a stand alone example of it: [grid.zip](https://github.com/driftyco/ionic/files/775379/grid.zip)

I've released a nightly if you'd like to try it out, using this nightly _should_ still work with the old system:

```
npm install --save ionic-angular@2.0.1-201702142221
```

And here is a document (a work in progress) where I have written up some information on it: [Ionic Grid API](https://docs.google.com/document/d/187BEqlZwM9h5S66vVZpmmYE_CREoYp5gSJ-NJUYpkHs/edit?usp=sharing)

The old grid system will eventually go away, but for now it should still work. If you see your current grid completely break or if you have feedback on the new system please let me know. Thanks! :)

**Comment by mikewagz** [comment]
@brandyscarney - I really appreciate the work you're doing on the grid system, it has the potential to make Ionic much more flexible for various devices.  I personally can't wait to upgrade our startup's iPad version to take advantage of this.

I checked out the doc you posted and had a question with how you're implementing the columns.  If we're going for Bootstrap-style syntax, I'm not sure how to interpret the example: 

`<ion-col col-12 col-sm>col</ion-col>`

Wouldn't it make more sense to have the various column specifiers by screen width, such as:

`<ion-col col-sm-12 col-md-6 col-lg-4>`

This example would indicate a 100%-column on small screen, 50%-column on medium screens, and a 33%-column on large screens.  Also, offsets would accompany these if needed, like:

`<ion-col col-sm-12 col-md-6 col-offset-md-3>`

This example would be a full row on small screens and a centered 50% column on anything larger.

This methodology seems like the way we're all used to using a grid, as popularized by Bootstrap, Materialize etc.  Any chance that is desirable/doable?

Thanks for building an awesome framework!

**Comment by brandyscarney** [comment]
@mikewagz I'm glad you like it! To explain the following example:

```
<ion-col col-12 col-sm>col</ion-col>
```

I am adding `col-12` so that it will take up 100% width from xs screens up, and then `col-sm` will change back to auto or equal width columns for sm screens and up. This is a replacement for our `responsive-sm` attribute. I just wanted to make sure it was still possible to do everything our old grid could do in our new grid.

Thanks for the feedback. :)
