### ISSUE TITLE
Blank scroll area were added when ion-textarea gets focused on Android 

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6052]
** Ionic v2 **

Scroll area not going even after closing the andorid keyboard.

**Comment by dylanvdmerwe** [comment]
Isn't this a dup of https://github.com/driftyco/ionic/issues/5810 and https://github.com/driftyco/ionic/issues/5536

**Comment by adamdbradley** [comment]
Yes this is a duplicate of #5536

**Comment by EvanWillms** [comment]
And a dup of #5432
