### ISSUE TITLE
[ERROR INSTALLING] -node-sass@3.4.2???

### ISSUE THREAD

**Issue by analtherapist** [driftyco/ionic#6053]
**After typing:**
npm install -g cordova ionic
I get an error when it starts to install node-sass@3.4.2:

node-sass@3.4.2 install C:\Documents and Settings\Bob\Application Data\npm\nod
e_modules\ionic\node_modules\node-sass
node scripts/install.js

Binary downloaded and installed at C:\Documents and Settings\Bob\Application Dat
a\npm\node_modules\ionic\node_modules\node-sass\vendor\win32-ia32-46\binding.nod
e

node-sass@3.4.2 postinstall C:\Documents and Settings\Bob\Application Data\npm
\node_modules\ionic\node_modules\node-sass
node scripts/build.js

C:\Documents and Settings\Bob\Application Data\npm\node_modules\ionic\node_mod
ules\node-sass\vendor\win32-ia32-46\binding.node ` exists.
testing binary.

**Then it writes the errror:**
`npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js
.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Documents and Settings\Bob\npm-debug.log`

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us!  As this issue is more related to the CLI and not the framework I will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#910
