### ISSUE TITLE
IOS Keyboard click outside page jump

### ISSUE THREAD

**Issue by raducostea** [driftyco/ionic#6055]
Hello,

Check out the following video: https://vimeo.com/161755036

First 2 times i am using the Done button from the keyboard to close the keybord which works very nice. The next 2 times i am clicking on the first input, which is a readonly input so i cannot focus. If you see, the keyboard gets closed but the entire page jumps a little. Take a look at the top header bar.

This its a blank ionic 2 application started with command
ionic start testinput blank --v2 --ts

Here is the ionic info
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.1
Xcode version: Xcode 7.3 Build version 7D175 

This recording was done directly from an Iphone 6 IOS 9.3

The page contains simple <input> elements inside a ion-content

Is there something i can do about this? This happens each time you click outside of an input element. Even a button will behave like that.

**Comment by EvanWillms** [comment]
I would guess that this shares a root-cause with #5432.  What's interesting to me is that the padding added to the ion-content to make space for the keyboard is being removed slowly in this context and not at all in others.

**Comment by raducostea** [comment]
Yeah, the padding is removed, the issue is that the top of the page jumps only if i click on an element without input. The odd think is that ii attach the keyboard hide event on that element the keyboards slides down nicely.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic 2? Thanks!

**Comment by raducostea** [comment]
@jgw96,

A temporarily fix for me was adding this inside theme/app.ios.css and disable keyboard scroll.

```
body {
	position:absolute;
	overflow: auto;
	width:100%;
	height:100%;
}
```

Not sure if this will do some harm to other components but i have a big app with a lot of components used and everything looks good.

**Comment by RonCan** [comment]
@jgw96 With beta-7 I'm still facing the issue

**Comment by jgw96** [comment]
@RonCan Would you mind updating to the latest release (beta.9) and testing again please? Thanks for using Ionic! There were a couple of changes when we released beta.8, which you can read about [here](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md) so you will need to do these changes for your app to work with beta.9.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
