### ISSUE TITLE
Issue(tabs): Spacing problem with 5 tabs on iOS

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6056]
#### Short description of the problem:
When adding more than 4 tabs on iOS the spacing of tabs goes over the screen. 

#### What behavior are you expecting?
On iOS, the maximum number of tabs that can be added are 5. At the very least, 5 tabs should fix on an iOS device. 

iOS (Ionic 2 with 5 tabs)
![capture](https://cloud.githubusercontent.com/assets/2852839/14317599/4c41e784-fc09-11e5-8843-7baa5d3d15ed.PNG)

iOS (Native with 5 tabs)
![capture3](https://cloud.githubusercontent.com/assets/2852839/14317652/94184148-fc09-11e5-8b9f-b2d768f02f8c.PNG)

Android
![capture2](https://cloud.githubusercontent.com/assets/2852839/14317609/54683be8-fc09-11e5-9451-dc85a7c01fad.PNG)

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by chinib** [comment]
Just adding my 2 cents. Was able to replicate this problem with 5 tabs on device iPhone 5s and also on iPhone 5s simulator. Seems the .tab-button style (in app.ios.css)  has a max-width: 240px; causing this behavior. Removing this max-width for iPhone 5s seems to solve the problem. Don't know if this *fix* has unwanted side-effects on other device types. Should be investigated further, but could point you in the (hopefully) right direction.

**Comment by dylanvdmerwe** [comment]
@brandyscarney does that sound like a reasonable fix?

**Comment by brandyscarney** [comment]
@dylanvdmerwe I'm not seeing the problem resolved by removing the `max-width`, only by removing the `min-width: 80px`. You should be able to set:

```
$tab-button-ios-min-width: auto;
```

In your `theme/app.ios.scss` file as a temporary work around until I can look into this more and make sure it doesn't break anything by removing it. :smile:

**Comment by brandyscarney** [comment]
Fixed for `beta.7`. I didn't see any negative results of removing this but let me know if anyone does. Thanks for the issue!

**Comment by mypark** [comment]
might want to adjust the tab padding as well since it ellipses the tab titles when it gets that small when it doesn't have to.

**Comment by brandyscarney** [comment]
@mypark could you create a new issue for this please and tag me in it? :smile:

**Comment by mypark** [comment]
ok, created issue https://github.com/driftyco/ionic/issues/6679
