### ISSUE TITLE
ionic run ios --device

### ISSUE THREAD

**Issue by martyzz1** [driftyco/ionic#6057]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic run ios  --device   doesn't work. Command halts without errors before copying to device
cordova run ios works perfectly and deploys to the device

#### What behavior are you expecting?
ionic run ios --device should deploy my app to my ipad

**Steps to reproduce:**
1. see above
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

relevant section of output from cordova run ios:-

  adding: Payload/PawSquad.app/www/templates/users/signup-thank-you.html	(in=188) (out=117) (deflated 38%)
  adding: Payload/PawSquad.app/www/templates/users/user-login.html	(in=715) (out=259) (deflated 64%)
  adding: Payload/PawSquad.app/www/templates/users/vet-needed.html	(in=71) (out=63) (deflated 11%)
  adding: Payload/PawSquad.app/www/templates/users/vet-urgent.html	(in=71) (out=63) (deflated 11%)
total bytes=97295278, compressed=66204319 -> 32% savings
]
Results at '/Users/marty/pawztech/apps/client_app/platforms/ios/build/device/PawSquad.ipa'
[....] Waiting up to 1 seconds for iOS device to be connected
[....] Found J72AP 'iPad' (8680a7ef929d1fca2d261937459af65007e40904) connected through USB.
[....] Waiting for iOS device to be connected
[....] Using J72AP 'iPad' (8680a7ef929d1fca2d261937459af65007e40904).
------ Install phase ------
[  0%] Found J72AP 'iPad' (8680a7ef929d1fca2d261937459af65007e40904) connected through USB, beginning install
[  5%] Copying /Users/marty/pawztech/apps/client_app/platforms/ios/build/device/PawSquad.app/META-INF/ to device
[  5%] Copying /Users/marty/pawztech/apps/client_app/platforms/ios/build/device/PawSquad.app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying /Users/marty/pawztech/apps/client_app/platforms/ios/build/device/PawSquad.app/_CodeSignature/ to device
[  5%] Copying /Users/marty/pawztech/apps/client_app/platforms/ios/build/device/PawSquad.app/_CodeSignature/CodeResources to device
etc....

Same section from ionic run ios --device
  adding: Payload/PawSquad.app/www/lib/pawsquad/lib/bower_components/fullcalendar/dist/lang/fa.js	(in=2782) (out=1228) (deflated 56%)
  adding: Payload/PawSquad.app/www/lib/pawsquad/lib/bower_components/fullcalendar/dist/lang/fi.js	(in=2687) (out=1187) (deflated 56%)
  adding: Payload/PawSquad.app/www/lib/pawsquad/lib/bower_components/fullcalendar/dist/lang/fr-ca.js	(in=1909) (out=960) (deflated 50%)
  adding: Payload/PawSquad.app/www/lib/pawsquad/lib/bower_components/fullcalendar/dist/lang/fr.js	(in=1915) (out=965) (deflated 50%)
  adding: Payload/PawSquad.app/www/lib/pawsquad/lib/bower_components/fullcalendar/d

^^literaly clips the output like this..

**Which Ionic Version?** 1.x or 2.x
1.7.14

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.2.1 Build version 7C1002

Cordova info

Collecting Data...

Node version: v4.4.2

Cordova version: 6.1.1

Config.xml file:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.xxx.yyy" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>xxxyyy</name>
    <description>
        xxxxxxx yyyyyyy
    </description>
    <author email="technology@xxxyyy.com" href="http://www.xxxyyy.com/">
      Your Name Here
    </author>
    <content src="index.html" />
    <access origin="*" />
    <access launch-external="yes" origin="tel:*" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="OpentokClientVersion" value="v2.7.2" />
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <feature name="Geolocation">
        <param name="ios-package" value="CDVLocation" />
    </feature>
    <platform name="ios">
        <plugin name="cordova-plugin-googleplus" spec="https://github.com/EddyVerbruggen/cordova-plugin-googleplus">
            <variable name="REVERSED_CLIENT_ID" value="417008191229-ns8sechurs2nlh8irv8a72s21itl61qf.apps.googleusercontent.com" />
        </plugin>
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <config-file parent="NSAppTransportSecurity" platform="ios" target="PawSquad-Info.plist">
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>amazonaws.com</key>
                    <dict>
                        <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                        <string>TLSv1.0</string>
                        <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                        <false />
                        <key>NSIncludesSubdomains</key>
                        <true />
                    </dict>
                    <key>amazonaws.com.cn</key>
                    <dict>
                        <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                        <string>TLSv1.0</string>
                        <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                        <false />
                        <key>NSIncludesSubdomains</key>
                        <true />
                    </dict>
                </dict>
            </dict>
        </config-file>
        <config-file platform="ios" target="project.pbxproj">
            <build-property name="ENABLE_BITCODE" value="NO" />
        </config-file>
    </platform>
    <platform name="android">
        <plugin name="cordova-plugin-googleplus" spec="https://github.com/EddyVerbruggen/cordova-plugin-googleplus">
            <variable name="REVERSED_CLIENT_ID" value="417008191229-vuk7vq09t4akeun07nthgsqjpv4fod5q.apps.googleusercontent.com" />
        </plugin>
        <allow-navigation href="https://harryb.eu.ngrok.io/*" />
        <config-file parent="/*" target="AndroidManifest.xml">
        </config-file>
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <plugin name="phonegap-plugin-push" spec="~1.6.1">
            <variable name="SENDER_ID" value="417008191229" />
        </plugin>
    </platform>
    <engine name="android" spec="4.0.2" />
    <engine name="browser" spec="3.6.0" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.1" />
    <plugin name="cordova-plugin-splashscreen" spec="~3.1.0" />
    <plugin name="cordova-plugin-device" spec="^1.0.1" />
    <plugin name="pawsquad" spec="../opentok-cordova" />
    <plugin name="cordova-plugin-geolocation" spec="https://github.com/apache/cordova-plugin-geolocation.git" />
    <plugin name="cordova-plugin-facebook4-custom" spec="../cordova-plugin-facebook4">
        <variable name="APP_ID" value="1036709146374432" />
        <variable name="APP_NAME" value="PawSquad" />
    </plugin>
    <plugin name="mx.ferreyra.callnumber" spec="https://github.com/Rohfosho/CordovaCallNumberPlugin.git" />
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
    <plugin name="ionic-plugin-deploy" spec="~0.5.0" />
    <engine name="ios" spec="~4.1.0" />
</widget>


```
Plugins:

cordova-plugin-compat,cordova-plugin-console,cordova-plugin-device,cordova-plugin-facebook4,cordova-plugin-geolocation,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,ionic-plugin-deploy,ionic-plugin-keyboard,mx.ferreyra.callnumber,pawsquad

Android platform:

Available Android targets:
----------
id: 1 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 2 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 3 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 4 or "Google Inc.:Google APIs:21"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.0.1 (API level 21)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
----------
id: 5 or "Google Inc.:Google APIs:22"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.1.1 (API level 22)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
----------
id: 6 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64

iOS platform:

Xcode 7.2.1

**Comment by martyzz1** [comment]
editted the above for neatness and added cordova info...

**Comment by martyzz1** [comment]
just confirmed this happens when trying to deploy to ipad and iphone

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, as this issue is related to the CLI, and not the framework, I will be moving this issue over to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#911

**Comment by martyzz1** [comment]
Ah sorry. Thanks...

**Comment by jgw96** [comment]
@martyzz1 No problem (:
