### ISSUE TITLE
modal onPageWillEnter/onPageDidEnter weird behaviour

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#6062]
#### Short description of the problem:
If I display a modal page in `onPageWillEnter` or `onPageDidEnter`, odd behaviour seems to occur where the modal is built twice.

If I attempt to dismiss my modal when I initialise it in `onPageWillEnter`, I cannot and I seem to have infinite modals.

If I attempt to dismiss my modal when I initialise it in `onPageDidEnter`, I seem to have two modals build and once I have dismissed two, it seems fine.

If I present my modal using a click handler, just one modal is created and expected behaviour resumes.

#### What behavior are you expecting?
I am expecting the modal component to display just once, as if initialised from a click-handler, and to be dismissed upon calling the `ViewController`'s `dismiss()` function.

**Steps to reproduce:**
1. Copy code below
2. Build and create an iOS project (using the blank starter, you can copy this over `home.ts`)
3. Run it and observe

**Or** you can run the Plunker below.

```
import {Modal, NavController, Page, ViewController} from 'ionic-angular';

@Page({
    template: `
        <ion-toolbar>
            <ion-title>
                Modal
            </ion-title>
            <ion-buttons start>
                <button (click)="dismiss()">
                    <span primary showWhen="ios">Close</span>
                    <ion-icon name="md-close" showWhen="android,windows"></ion-icon>
                </button>
            </ion-buttons>
        </ion-toolbar>
        <ion-content padding>
            <h1>My Modal Page</h1>
        </ion-content>
    `
})
class ModalPage {
	constructor(public viewCtrl: ViewController) {}

    dismiss() {
        this.viewCtrl.dismiss();
    }
}

@Page({
    template: `
    	<ion-navbar *navbar>
            <ion-title>
                Base
            </ion-title>
            <ion-buttons end>
                <button (click)="open()">
                    <span>Open</span>
                </button>
            </ion-buttons>
        </ion-navbar>
        <ion-content padding>
            <h1>My Base Page</h1>
        </ion-content>
    `
})
export class HomePage {
    constructor(public navCtrl: NavController) {}

    onPageWillEnter() {
        // this.showModal();
    }

    onPageDidEnter() {
        this.showModal();
    }

    open() {
    	this.showModal();
    }

    showModal() {
        let modal = Modal.create(ModalPage);
        this.navCtrl.present(modal);
    }
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.0.0-beta.23

#### Plunker that shows an example of your issue

http://plnkr.co/edit/Pp11eYX4clowiDfBF22l?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hmm, although its easily reproducible in the plunker, oddly enough when i take the code and put it into our tabs starter i cant reproduce the issue. Will have to look more into this one.

**Comment by kelvindart** [comment]
Hi Justin - odd! Which version are you using? I can attach a live .xcodeproj if that is easier? Unless the issue has inadvertently been fixed in a newer version you are using?

**Comment by jgw96** [comment]
Hey @kelvindart ! Sorry it has taken me so long to get back to you! That is totally my fault. I can now reproduce this and have a solution for you. I have a plunker [here](http://plnkr.co/edit/zCoCF5KltgDBITYUsjS8?p=preview) that shows you the proper way to open a modal without firing the lifecycle events of the page its presented from, which is what is causing the modals to open twice. As i said, im very sorry that this issue got lost in the mix. Thanks for using Ionic!

**Comment by kelvindart** [comment]
Hi @jgw96! That's no problem whatsoever - thanks so much for responding. The solution looks perfect - thank you so much! Please do not apologise. I was not expecting such a quick turnaround to be honest :). Thanks again!

**Comment by kelvindart** [comment]
Hey @jgw96 - I was thinking about this earlier. I'm just curious as to why we need to check the NavController's length is not equal to 2 in order to show the modal (in your Plunkr)?

It occurred to me when changing some code in an older beta release use the new `ionViewDidEnter`. I'm not saying it's wrong - I'm only curious (and the issue can remain closed as a result :smile:).

**Comment by kelvindart** [comment]
Oh bother - I fear this may be an issue with the new ModalController. I will open another issue (and link to this - once I have worked out how).

**Comment by kelvindart** [comment]
Actually, is there an ionic-angular@2.0.0-beta11 template I can use? 😃
