### ISSUE TITLE
perf: Using this.nav.push for page with textarea control

### ISSUE THREAD

**Issue by wim1983** [driftyco/ionic#6063]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If a page with <ion-textarea> control is opened using this.nav.push, when first tap in will make the keyboard open and disappear, and when you typing in the textarea control, UI become very laggy, however if use this.nav.setRoot, no issue there.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind providing a plunker that i can use to reproduce this issue? You can use this plunker template (http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info) to make one. Thanks!

**Comment by wim1983** [comment]
I've a look on the plunker code, but it's code strucuture is different from what I've written in javascript, guess I'll have to try different thing for the moment...

**Comment by wim1983** [comment]
I've found out what cause the issue, it's because previous page array variable with certain amount of data that causing the lag, if I select 1 data and assign to a variable say this.DefectReportList it's ok, this is kind of Angular 2 problem?
