### ISSUE TITLE
tabs, segments and click events are very sloppy, not native-like

### ISSUE THREAD

**Issue by vikrana** [driftyco/ionic#6064]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I have been working on my ionic 2 app for couple of months and starting to notice the delay more lately on all click events and especially main tabs and segments.

It takes 3-10 seconds for click events and segments. Tabs are very sloppy at first time touch but get better in the subsequent touches. I read a lot of stuff online and tried few things but do far no luck.

Tried tappable attribute with some luck but why would simple tabs won't response like native?

this is my ionic configuration:
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

Thanks in advance.

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by adamdbradley** [comment]
Sorry but you'll have to provide us with some more information to go on? You stated:

> starting to notice the delay more lately on all click events and especially main tabs and segments.

What is it your tabs and segments are doing? What devices are you testing on? To help you out we'll need sometime to go off of. Thanks

**Comment by vikrana** [comment]
Hi Adam, tabs load content. But I expect the tabs to turn active instantly even though content is not done loading, so it looks native-like without delay. Segments do the same. I see less of a delay on Chrome compare to iOS.

I am deploying it on iPhone 6.

Thanks.

**Comment by jgw96** [comment]
Hey! Would you mind making a video or screencast of what your experiencing? Thanks!

**Comment by adamdbradley** [comment]
Ok, that it could be a number of things. Initially I'm thinking it might be the HTTP request to fetch the templates for ion-tabs, then the first ion-page within the first ion-tab. This is something we hope to solve with our CLI and offline template complication, but it isn't done yet. Are you able to inline your templates to see a difference? For testing, could you entirely remove the content from each first page within each ion-tab and switch between tabs to see if you still have performance problems?

**Comment by vikrana** [comment]
I converted the templates inline and removed all content markup and minimized it to this.
@Page({
    template: `<ion-navbar *navbar hideBackButton primary>  
    <ion-title>My Items</ion-title>
</ion-navbar>

I also added 'tappable' attribute (shown below) to tabs directive but still touching tabs take 3-8 seconds to activate especially at initial touch...it gets better in subsequent touch.

<ion-tabs class="tabs-basic">
    <ion-tab tappable [root]="tab1Root" tabTitle="Items" tabIcon="apps"></ion-tab>
    <ion-tab tappable [root]="tab3Root" tabTitle="My Itemss" tabIcon="list-box"></ion-tab>
    <ion-tab tappable [root]="tab4Root" tabTitle="My Account" tabIcon="person"></ion-tab>
</ion-tabs>

I understand Ionic disables 300ms delay so what I am doing wrong to not see that behavior :(

Thanks,
Vik

**Comment by vikrana** [comment]
Hi, I think I narrowed down the problem...I am using Firebase to fetch data in one tab and that is responding normally. In the other tab I use Geofire as well and when I removed Geofire it started to respond instantly. Is there any known issue around this?

**Comment by ciekawy** [comment]
looks like this might be a time required to initialisw the following view and not directly related to the tapping?

**Comment by jgw96** [comment]
@ciekawy that initial time to init the view (the template is being compiled) happens with any angular 2 project right now until the nail down the offline compile, which from their latest changelogs looks like it might be very soon.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
