### ISSUE TITLE
how used slides set item first show

### ISSUE THREAD

**Issue by buiphu** [driftyco/ionic#6065]
how used slides set item first show
e.g : 0, 1 ,2 ,3 ,4, ,5 ,6
i want when load page show item 4

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!

**Comment by buiphu** [comment]
i had quenstion in forum 
https://forum.ionicframework.com/t/how-used-slides-set-item-first-show/48677
