### ISSUE TITLE
Can't import some random plugin in typescript page

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6068]
**Ionic v2**

I've added **`contentsync `**cordova plugin.
I tried to import it in the typescript file like below,
`import {ContentSync} from 'ionic-native';`
But it throws below error. 

> Module '"c:/htdocs/my-project/node_modules/ionic-native/dist/index"' has no exported member 'ContentSync'.

Kindly provide some way to import some random plugins.

**Comment by dylanvdmerwe** [comment]
Not every plugin in the world has been added to ionic-native. Just use the plugin normally as [explained](https://github.com/phonegap/phonegap-plugin-contentsync#quick-example).

**Comment by dheeran1** [comment]
Thanks for your info. But how will you import it to the environment without VS code error.

**Comment by jgw96** [comment]
Hello! We are still working on adding more plugins to Ionic-Native, so for the time being for some plugins you may have to use the raw cordova plugin. Using external libraries with Angular 2 is actually simple, even though it seems like it may be complicated. Theres also a couple of different ways to do it. I have linked two articles to this issue that should help you with using external libraries with Angular 2, like that cordova plugin. 
https://www.thepolyglotdeveloper.com/2016/01/include-external-javascript-libraries-in-an-angular-2-typescript-project/

https://medium.com/@s_eschweiler/using-external-libraries-with-angular-2-87e06db8e5d1#.fp0hpi47f

Hopefully that helps you! If not feel free to comment back! Thanks!

**Comment by dheeran1** [comment]
Loading the plugin will be taken care by cordova.js in run time. Issue is bringing the member reference to the editor like in few plugins of ionic-native. So that editor wont pop any error.
