### ISSUE TITLE
Issue while adding NavController as nested dependency

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6069]
**Ionic v2**

I've created a provider NavControllerProxy 

```
 @Injectable()
 export class NavControllerProxy {
     constructor(private nav: NavController, private platform: Platform) { }
     push(page: Type, params?: any, opts?: NavOptions) {
         return this.nav.push(page, params, opts);
     }
     pop(opts?: NavOptions): Promise<any> {
         return this.nav.pop(opts);
     }
 }
```

and added in providers array of @App. `MyListPage `has `NavControllerProxy  `as private constructor parameter. When I navigate to `MyListPage`, below error printed was shown in the console.
> EXCEPTION: No provider for NavController! (MyListPage -> NavControllerProxy -> NavController)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Also this link should help you with this issue: http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html, it explains the proper way to do something like this alot better than i ever could (:  Thanks for using Ionic!
