### ISSUE TITLE
Native Prompt - White Text / Missing Default

### ISSUE THREAD

**Issue by ct14it** [driftyco/ionic#6070]
#### Short description of the problem:

Native prompt input doesn't show text (or text is white), regardless of whether default text is specified or not.

![screenshot_20160407-153112](https://cloud.githubusercontent.com/assets/8723414/14354780/7fb2e672-fcd6-11e5-99b5-7374140d390f.png)

#### What behavior are you expecting?

Ability to see the input text

**Steps to reproduce:**
1. Create Tabs app
2. Add ionic-native
3. Open Prompt

**page1.ts**
```
import {Page} from 'ionic-angular';
import {Dialogs} from 'ionic-native';


@Page({
	templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
	constructor() {

	}
	openTestAlert(){
		var alertPromise = Dialogs.alert("This is an alert", "Alert", "TestButton");
		alertPromise.then(function(data) {
			console.log("Button pressed", data);
		});
	}
	openTestConfirm(){
		var confirmPromise = Dialogs.confirm("Well then?", "Confirm", ["To be","Not to be"]);
		confirmPromise.then(function(data) {
			console.log("Button pressed", data);
		});	
	}
	openTestPrompt() {
		var confirmPromise = Dialogs.prompt("How do you feel?", "Prompt", ["Shout", "Say","Whisper"]);
		confirmPromise.then(function(data) {
			console.log("Button pressed", data);
		});
	}
}

```

**page1.html**
```
<ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>

<ion-content padding class="page1">
  <button (click)="openTestAlert()" class="button button-positive">Alert</button>
  <button (click)="openTestConfirm()" class="button button-positive">Confirm</button>
  <button (click)="openTestPrompt()" class="button button-positive">Prompt</button>
</ion-content>
```

**Which Ionic Version?** 2.0.0-beta.24

**Run `ionic info` from terminal/cmd prompt:**
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.5
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v4.4.2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, since this issue is related to ionic-native and not the core framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#118
