### ISSUE TITLE
Native Dialogs cause inconsistent blurring

### ISSUE THREAD

**Issue by ct14it** [driftyco/ionic#6071]
#### Short description of the problem:

Some elements receive blur effect on Android Nexus 6P and remain blurred until random touch event "fixes" them.

![screenshot_20160407-154126](https://cloud.githubusercontent.com/assets/8723414/14355194/042c0824-fcd8-11e5-807d-4ef4f9f6f739.png)

#### What behavior are you expecting?

Either no blurring at all or all content blurred. Definitely expect elements to unblur when dialog has closed.

**Steps to reproduce:**
1. Create a tabs app
2. Add Ionic Native
3. Open a dialog input (Alert/Confirm/Prompt) and then close it

**page1.ts**
```
import {Page} from 'ionic-angular';
import {Dialogs} from 'ionic-native';


@Page({
	templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
	constructor() {

	}
	openTestAlert(){
		var alertPromise = Dialogs.alert("This is an alert", "Alert", "TestButton");
		alertPromise.then(function(data) {
			console.log("Button pressed", data);
		});
	}
	openTestConfirm(){
		var confirmPromise = Dialogs.confirm("Well then?", "Confirm", ["To be","Not to be"]);
		confirmPromise.then(function(data) {
			console.log("Button pressed", data);
		});	
	}
	openTestPrompt() {
		var confirmPromise = Dialogs.prompt("How do you feel?", "Prompt", ["Shout", "Say","Whisper"]);
		confirmPromise.then(function(data) {
			console.log("Button pressed", data);
		});
	}
}

```

**page1.html**
```
<ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>

<ion-content padding class="page1">
  <button (click)="openTestAlert()" class="button button-positive">Alert</button>
  <button (click)="openTestConfirm()" class="button button-positive">Confirm</button>
  <button (click)="openTestPrompt()" class="button button-positive">Prompt</button>
</ion-content>

```

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.5
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v4.4.2

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Since this is an issue with ionic native and not the ionic framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#133
