### ISSUE TITLE
Formatting user input

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#6072]
#### Short description of the problem:

I would like to be able to format the user input, like to documents and money, but if I use a type "number" and watch the user input and try to format it, ion-input does not allow the formatted input to be set in the screen.
If you look at the sample I provide in the repo below you can note that, even with "text" or "tel" you get a weird behavior not removing the letters the user inputs even tough I remove them.
#### What behavior are you expecting?

if I set the ion-input type to "number", to show the number keyboard, but allow me to programmatically 
set the value in the input field.

if I set the ion-input type to "text", to show the text keyboard, but allow me to programmatically 
set the value in the input field.

if I set the ion-input type to "tel", to show the phone keyboard, but allow me to programmatically 
set the value in the input field.

**Steps to reproduce:**
run project here: https://github.com/BugsBunnyBR/keyboard-test 

**Which Ionic Version?** 2.x
tested on Android

**Comment by brandyscarney** [comment]
Thanks for the issue! Is this still happening for you? I see the project was removed.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
