### ISSUE TITLE
ion-option: value is take from inner html and not from [value]

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#6076]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
It looks like the value for `ion-option` is take from the inner html and not from the `[value]` property.

#### What behavior are you expecting?
was expecting the values to be taken from the value property

**Steps to reproduce:**
This is a try to make a placeholder for option
1.
take this html snipet 
```html
        <ion-select>
          <ion-option [value]="" [checked]="true">select gender</ion-option >

          <ion-option [value]="Male">Male</ion-option >
          <ion-option [value]="Female">Female</ion-option >
        </ion-select>
```
2.  You will see that when selecting you get all the 3 options
3. I want to be able to set a placeholder for option if none of them is selected
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/qfVTqY8T9JRU94OzBglK?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.9.0

**Comment by iignatov** [comment]
@royipressburger Could you please provide more details on what exactly are you trying to achieve?

I noticed some errors in the plunker example that you provided.

Here is an updated plunker - check it to see if it's working as you want it to:
http://plnkr.co/edit/G8XtyLTaHgLnhglJ3R82?p=preview

**Comment by royipressburger** [comment]
@iignatov Yes that's exactly it..
