### ISSUE TITLE
Delayed Bootstrapping

### ISSUE THREAD

**Issue by omeid** [driftyco/ionic#6078]
I am trying to integrate ionic 2 (`ionic-angular@2.0.0-beta.3`) with meteor platform and run into a problem where the JavaScript code is run before dom is ready which results into the following error:

```bash
 "Uncaught TypeError: Cannot read property 'classList' of null"
```

I can work around this error by wrapping the `@App` and the _App_ class in the meteor's equivalent of ionic's `platform.ready()` but it is somewhat of a hack.

It would be ideal if the `@App` decorator did not boostrap and bootstraping was factored out into it's own function.

So basically,

instead of 

```typescript
import {App} from 'ionic-angular';
@App(meta)
class App {}
```

one would do

```typescript
import {App, bootstrap} from 'ionic-angular';
@App(meta)
class App {}

bootstrap(app);
```

This will also allow to avoid duplicating some of Angular APIs like `prodMode` attribute implemented in #5449. I believe this would also allow for more through testing as well by having more control over the app bootstrapping.

If there isn't any fundamental issues with this idea, I am happy to create a pull request.

Thanks for the great work guys!

**Comment by adamdbradley** [comment]
You can still use angular's API to bootstrap. `@App` is just a shortcut to make things easier. Have you tried using just ng2's bootstrap method?

**Comment by omeid** [comment]
It is possible. 

Instead of 

```typescript
import {App} from 'ionic-angular';
@App(meta)
class App {}
```

One could do,

```typescript

import {IONIC_DIRECTIVES, ionicProviders} from 'ionic-angular';
import {bootstrap} from 'angular2/platform/browser';

@Component({
    //default selector, and theme.
    directives: [IONIC_DIRECTIVES],
    providers: [ionicProviders()]
})
class App {}
bootstrap(App)
```

But `ionicProviders()` and `IONIC_DIRECTIVES` looks inconsistent, and are undocumented.

Perhaps, an alternative solution to this issue would be to documented these, `ionicProviders()` and `IONIC_DIRECTIVES` , and make sure they don't break without a major version change?

**Comment by omeid** [comment]
Okay, so this actually doesn't work and calling 'ionicProviders()` seems to be the root of problem. It assumes the DOM is ready, which if not the case results into the following error:

```javascript
Uncaught TypeError: Cannot read property 'classList' of null
```

Because `setupDom` tries to call `classList (for setting up the mode class name: ios/md/wp) on window.body (using bodyEle ref).

**Comment by omeid** [comment]
Apologizes for too many comments in a row.

But the following works, however, it still suffers from using undocumented APIs.

```typescript
import {IONIC_DIRECTIVES, ionicProviders} from 'ionic-angular';
import {bootstrap} from 'angular2/platform/browser';

@Component({
    //default selector, and theme.
    directives: [IONIC_DIRECTIVES]
})
class App {}


delay( ()=> { //in my case, Meteor.startup
bootstrap(App,ionicProviders())
});
```


Perhaps it is a good idea to documented these APIs, ionicProviders() and IONIC_DIRECTIVES , and make sure they don't break without a major version change?

**Comment by adamdbradley** [comment]
Sounds good, we'll get the documentation written up: https://github.com/driftyco/ionic-site/issues/552

Thanks

**Comment by rob3c** [comment]
@omeid I was getting the same "Cannot read property 'classList' of null" error using an ionic v1 pattern where my scripts were in the `head` section of index.html. Now that ionic 2 references `document.body`, the scripts need to be moved to the end of the body section (actually, anywhere after the body tag) so it'll exist when ionic calls `document.body`.
