### ISSUE TITLE
Error while getting a value from SqlStorage by not existent key

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#6079]
#### Short description of the problem:

I faced with an issue with `SqlStorage` after upgrading to ionic-angular@2.0.0-beta.4. I tried to get a json value using `#getJson()` method by unexistent key and got `Error: Uncaught (in promise): SyntaxError: Unexpected token u`.

#### What behavior are you expecting?

Expecting to get `null` value by a key which is not stored before.

**Steps to reproduce:**
```
describe('SqlStorage', () => {
    it('#get() should return `null` for an not existent key', () => {
        const storage = new Storage(SqlStorage, {name: 'test'});
        return Promise.all([
            storage.get('foo').then(value => expect(value).toBeNull()),
            storage.getJson('bar').then(value => expect(value).toBeNull())
        ]);
    });
});
```

**Which Ionic Version?** 2.0.0-beta.4

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! When you did this same sqlStorage call before beta.4 did you get a null value? Normally when you get the `Error: Uncaught (in promise): SyntaxError: Unexpected token u` error that means that your trying to parse json that isnt actually json (does not have proper json syntax). This error would make sense in this context because null isnt json.

**Comment by mnasyrov** [comment]
The unit test is passed on beta.3, I get `null` value.
I think the issue is not related to parsing json value because `#get()` method fails too.
I suspect the regression was caused by [this commit](https://github.com/driftyco/ionic/commit/51dd628cd1f745185d505882b0aca88ecf1ebbd7), there is a changed value processing in `SqlStorage#get()` method.

**Comment by manucorporat** [comment]
@mnasyrov I agree. but before this gets fixed, we should ask if success then() should be called if the value does not exist...

in the meantime, you can use:
```
            storage.getJson('bar').catch(error => {})
```

**Comment by jgw96** [comment]
@mnasyrov ahh sorry, read your issue wrong then. I thought it was just the getJson method that was failing. Sorry about that.

**Comment by mnasyrov** [comment]
@manucorporat Using `catch` method makes sense, however it is not an error. It is a normal state of a storage when it does not have a value, also this behaviour is common for key-value storages/maps. 

There is a lack of [documentation](http://ionicframework.com/docs/v2/api/platform/storage/SqlStorage/) for `SqlStorage`, so, I guess, people intuitively expects to get `null` value.

**Comment by xelamak** [comment]
Hi guys, I did the following to temporarily get rid of the exception. 

In ionic-angular/platform/storage/storage.js
```
    Storage.prototype.getJson = function (key) {
        return this.get(key).then(function (value) {
            try {
                return (value) ? JSON.parse(value) : value; // <-- Simply check if the value is undefined before parsing.
            }
            catch (e) {
                void 0;
                throw e; // rethrowing exception so it can be handled with .catch()
            }
        });
    };
```

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic! We have replaced `Storage` with `@ionic/storage` in the latest rc.0 release of Ionic 2. Thanks! You can see details on this [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#storage) in our changelog.
