### ISSUE TITLE
Add Toast UI component

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#608]
Add toast component, from Android

example from KitKat: http://i.imgur.com/vYK4wwrl.png

Options:
- region: top or middle or bottom or a number percent (default bottom)
- tap to close: true / false (default true)
- close callback (optional)
- duration (default somewhere between 2-3s)

**Comment by rajeshwarpatlolla** [comment]
I was been searching for a toast notification plugin for my project. I have created a bower component for toast. Please have a look at the <a href="https://github.com/rajeshwarpatlolla/ionic-toast">bower component</a> i have created. I think it might help you.
