### ISSUE TITLE
Missing onPageShow or similar event on @Page in Ionic 2.x ?

### ISSUE THREAD

**Issue by josdewitte** [driftyco/ionic#6080]
#### Short description of the problem:

I am missing a onPageWillShow / onPageDidShow event on a @Page. I thought the onPageDidEnter / onPageWillEnter events would be this functionality; but they also trigger after an Alert or the like is presented and subsequently closed.
Use case: If something goes wrong on Page Enter code, give them an Alert with recovery options, allowing for retry of Http request / other code. However after the recovery options alert is shown and closed; page load is triggered again due to the Alert dismissal triggering onPageXXXEnter events. The page remains active while having the Alert presented and should not reload.
Any thoughts? Is there another way to distinguish real Page activation and activation due to Alerts closing?

**Comment by adamdbradley** [comment]
Would you be able to provide a demo of showing the issue further?

**Comment by jgw96** [comment]
Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to respond back if your still having the issue! Thanks again!
