### ISSUE TITLE
clappr integration with ionic

### ISSUE THREAD

**Issue by alouane** [driftyco/ionic#6082]
I have an issue with running clappr video player inside an ionic app:
Adding this line: `<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js">`
triggers this error: Uncaught TypeError: Cannot read property 'srcEvent' of undefined
Ionic version: 2.0.0-beta.24
This error happens also on a web browser
Any help?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker that shows an example of this issue using this template please? http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=preview Thanks!

**Comment by alouane** [comment]
Hi, Unfortunately I'm not familiar with plunker templates, I couldn't find how to copy your templates, sorry!
But after some debugging I found the source of the problem:
1- I install a fresh ionic app by taping: `ionic start ClapprTest tabs`
2- I add this script : `<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>` in the bottom of www/index.html, before </body> tag
3- I change the file www/templates/tabs.html to : 
`
<ion-side-menus enable-menu-with-back-views="false">
  <ion-side-menu-content>
      <ion-tabs class="tabs-icon-top">
        
        <ion-tab title="Dashboard" icon="icon ion-home" href="#/tab/dash">
          <ion-nav-view name="tab-dash"></ion-nav-view>
        </ion-tab>
        
        <ion-tab title="Friends" icon="icon ion-heart" href="#/tab/friends">
          <ion-nav-view name="tab-friends"></ion-nav-view>
        </ion-tab>
        
        <ion-tab title="Account" icon="icon ion-gear-b" href="#/tab/account">
          <ion-nav-view name="tab-account"></ion-nav-view>
        </ion-tab>
      </ion-tabs>
  </ion-side-menu-content>
</ion-side-menus>`

I think, probably this issue `Uncaught TypeError: Cannot read property 'srcEvent' of undefined` is related to the  `<ion-side-menu-content>` tag

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
