### ISSUE TITLE
When is ionic 1.2.4 going to be updated to use a newer version of angular?

### ISSUE THREAD

**Issue by AllenConquest** [driftyco/ionic#6084]
When is ionic going to be updated to use a more recent version of angular? At the moment it is using 1.4.3, but this has know iOS9 bugs that were fixed in 1.4.6. Can ionic be updated to use this newer version?

**Comment by jgw96** [comment]
Hello! We are currently working on upgrading ionic to use angular 1.5! You can track the progress of this in this issue: https://github.com/driftyco/ionic/issues/5436 We hope to have the next release of Ionic v1 using angular 1.5. Thanks for using Ionic !
