### ISSUE TITLE
Default theme SASS customization broken for text colors?

### ISSUE THREAD

**Issue by thor-the-norseman** [driftyco/ionic#6086]
#### Short description of the problem:

When trying to override $bar-default-text, nothing happens.

#### What behavior are you expecting?

The text colors should change.

**Steps to reproduce:**
1. Add something like "$bar-default-text: white !default" to your ionic.app.scss file.
2. Watch nothing happen.
3. Cry.

I noticed that $bar-default-text isn't even included in the appropriate _xxx.scss files in the lib folder, so they're obviously being ignored completely.

**Which Ionic Version?** 1.x or 2.x

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.1.2
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. Is this still an issue? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
