### ISSUE TITLE
Tabs component causes white screens on Android

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6087]
#### Short description of the problem:
Whenever running an app that has a tabs component on android devices it causes a white screen. No exception are seen in logs and it works fine in chrome. 

**Steps to reproduce:**
1. Either use tabs starter or add a tabs component to any starter

**Other information:** 
Tried on Android 6.0.1, 5.1, and Android N dev preview. Same results on all. 
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.8.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by ZiFFeL1992** [comment]
Same here!

```
Your system information:

Cordova CLI: 6.1.1
Ionic Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by brandyscarney** [comment]
@ZiFFeL1992 Do you have this code in your app, and if you comment it out does the app work:

```
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
    });
```

**Comment by ZiFFeL1992** [comment]
Hello @brandyscarney !
Plugins are loading fine, but the tabs.js is not been called, I tried to console.log() inside the constructor but I can't see the log in the console.

This is also happening on iOS.

**Comment by nayrrod** [comment]
Same issue here, when trying to deploy on android, chrome is working fine : 

`Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Not installed`

**Comment by adamdbradley** [comment]
Looks like `NgZone` wasn't running after cordova's `deviceready` event fired. Should be fixed in the next release. Thanks for the help!
