### ISSUE TITLE
ngFor in slides with loop="true"

### ISSUE THREAD

**Issue by stellasoft-will** [driftyco/ionic#6091]
#### Short description of the problem:
When slides are in loop mode updating an ngFor inside the slides causes the ng-repeat not to update sometimes, this i think is due to the cloned slides that make the loop mode work.

#### What behavior are you expecting?
ngFor to update in all slides in loop mode

**Steps to reproduce:**
1. create slides in content
2. loop = true
3. update ngFor in slide you will swipe to.

**Which Ionic Version?** 1.x or 2.x

2x

**Comment by jgw96** [comment]
Hey @stellasoft-will ! Would you mind making a Plunker (here is a template: http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info) that we can use to reproduce your issue? Thanks!

**Comment by brandyscarney** [comment]
I'm not able to reproduce this. If you are still seeing this issue please create a new issue with more information. Either a plunker that reproduces the problem or some code that demonstrates the issue. Thanks! :smile:
