### ISSUE TITLE
See if we can automatically inject IONIC_DIRECTIVES

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6092]
We should be able to add `IONIC_DIRECTIVES` so that users can create custom components without having to import them.

**Comment by mhartington** [comment]
I don't think we should. This kind of goes against the whole import/explicit idea.
The generate command automatically includes `IONIC_DIRECTIVES`, so I think we could do a better job documenting that feature, or adding a section to the docs about them.

**Comment by brandyscarney** [comment]
It was something @adamdbradley mentioned adding the other day. I think it's confusing that we do it for them in `@App` and `@Page` and then they have to figure out what they're missing when the styles don't work.

**Comment by xeoneux** [comment]
As a beginner to Ionic 2 and Angular 2, I spent a fair amount of time wondering why my Angular component wasn't playing nice with Ionic. At first I thought it was about wrapping the whole component in an `<ion-content>` or changing `@Component` to something else like `@IonicComponent`, but only after a substantial amount of time I understood the whole concept of DI through it and why `IONIC_DIRECTIVES` was important. Hope that helps! 😄

**Comment by frederikschubert** [comment]
You could also add the directives to the PLATFORM_DIRECTIVES DI token during bootstrap. This way they would be available in all components.

**Comment by adamdbradley** [comment]
Thanks @frederikschubert, we did exactly that

**Comment by Luchillo** [comment]
@adamdbradley I would have liked to have the auto provide sooner, i had to use something like this for `NorificatorComponent` (ugly as hell):
```js
// Components
import {BusyComponent, BusyCtrl, NotificatorComponent} from './components/components'
@App({
  templateUrl: 'build/app.html',
  providers: [
    Config,
    DB,
    MasterService,
    CustomerService,
    WalletService,
    BusyCtrl,
    NotificationService,
    provide(PLATFORM_DIRECTIVES, {useValue: [NotificatorComponent], multi: true})
  ],
  directives: [BusyComponent],
  config: {
    modalEnter: 'modal-pop-in',
    modalLeave: 'modal-pop-out',
  }
})
```
I guess now i can just stick it inside the directives array and it will be global now, right?
