### ISSUE TITLE
Typings folder gets committed to git repository

### ISSUE THREAD

**Issue by xeoneux** [driftyco/ionic#6094]
#### Problem:
The `typings` folder is not ignored while creating a new Ionic 2 project with TypeScript. As a result, it gets committed to the git repository before realisation. 😄

**Comment by mhartington** [comment]
Hi there! So this is something you can change in the .gitignore file for your project.

**Comment by xeoneux** [comment]
@mhartington That's true but including it by default in the project would provide better experience for the user. It's the same reason why `node_modules` exists in the `.gitignore` 😄
