### ISSUE TITLE
Cannot change screen orientation with cordova plug-in

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#6095]
#### Short description of the problem:
Cannot change screen orientation with cordova plug-in

#### What behavior are you expecting?
Screen orientation can change dynamically and accordingly with code such as:
screen.lockOrientation('landscape'); // screen will change to landscape mode from portrait mode

**Steps to reproduce:**
Only a few steps as below to create the MVP and reproduce the problem, you will see the screen did turn landscape for 50ms and then change back:
Install ionic 2 (http://ionicframework.com/docs/v2/getting-started/installation/): 
`npm install -g ionic@beta`

Create a project (http://ionicframework.com/docs/v2/getting-started/tutorial/):
`ionic start MyIonic2Project tutorial --v2`

Add this plugin:
`ionic plugin add cordova-plugin-screen-orientation`

Add these code on any of the page:
```
onPageDidEnter() {
    screen.lockOrientation('landscape');
}
```

Run
`ionic build ios`
then this if you don't have an iPhone plugged in:
`ionic emulate ios`
or this if you have an iPhone plugged in:
`ionic run ios`

Here are some errors:
```
2016-04-09 09:35:25.803 MyIonic2Project[6269:1646296] -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x125e66aa0
2016-04-09 09:35:25.803 MyIonic2Project[6269:1646296] *** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x125e66aa0
```

**Which Ionic Version?**
**Ionic Version**: 2.0.0-beta.4

**Browser & Operating System**: iOS

#### Plunker that shows an example of your issue
**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
