### ISSUE TITLE
tslint generates warning for single quotes around strings

### ISSUE THREAD

**Issue by navneetkarnani** [driftyco/ionic#6100]
**Note: for support questions, please use one of these channels:** 
#### Short description of the problem:
When working with TypeScript project on v2 and using generators, all strings are generated with single quote around it. The tslint engine generates warnings.

Look at this thread for details: http://stackoverflow.com/questions/25453864/what-is-the-standard-for-use-of-quotes-in-typescript

#### What behavior are you expecting?
No warnings in tslint

**Steps to reproduce:**
1. ionic start test-project blank --v2 --ts
2. ionic g provider MyTestProvider
3. code .

Check the warnings in Visual Studio Code, generated by tslint .

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.0 Beta 22

#### Plunker that shows an example of your issue

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jthoms1** [comment]
Thanks for opening the issue. We currently have a tslint.json file that provides preference to single quote use.  This currently is not bundled with v2 typescript projects, but we will likely include it going forward. 

https://github.com/driftyco/ionic/blob/2.0/tslint.json

**Comment by jgw96** [comment]
Hello all, just checked out all our generators and we now use single quotes, also as of yesterday when you start a new project there is a new gulp lint task that will lint your project using tslint. Thanks for using Ionic!
