### ISSUE TITLE
bug: Ajax calls do not work with device or simulator

### ISSUE THREAD

**Issue by alyn000r** [driftyco/ionic#6101]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>I was previously able to make Ajax calls with no issues. 
Now they only work when I do

ionic emulate ios -c -l

when I do 

ionic emulate ios / android 

The Ajax calls do not work. Please tell me what has changed.

The whole project is on github please see this link
https://github.com/alyn000r/testAjax/tree/master/testAjax</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you getting any errors in the console?

**Comment by alyn000r** [comment]
I am sorry, I do not know how to check the console logs when I run this command

ionic emulate android

When I run this command

ionic emulate android -c --- No Errors are shown

When I run this command

ionic emulate android -c -l --- Ajax calls work fine

**Comment by jgw96** [comment]
Sorry, i should have been more clear. So, when you run `ionic serve` does your app work in the browser? Or does it have issues there too?

**Comment by alyn000r** [comment]
It works perfectly fine in the browser and when I use live reload.

**Comment by alyn000r** [comment]
Device and Simulator without live reload is a no go

**Comment by jgw96** [comment]
Thanks for the info! So to inspect your app when running on your android device you can use chrome://inspect/#devices to inspect your app and see if there are any errors in the console. Im guessing that you may get errors related to cors.

**Comment by alyn000r** [comment]
I will try this and get back to you. Thank You

**Comment by alyn000r** [comment]
I was reading this blog which says CORS is only an issue when you start up a web server and it should not be an issue when we do run / emulate

However in my case the Ajax works fine when I use live reload or serve

Anything I am missing ? 

http://blog.ionic.io/handling-cors-issues-in-ionic/

**Comment by jgw96** [comment]
@alyn000r Hmmm, sorry this is a tough one. I am fixing to do some more testing and then i will get back to you. Thanks for your patience and quick responses!

**Comment by alyn000r** [comment]
I saw the error first it was complaining about no <meta "Content-Security"> tag present so I added this to my index.html for android

<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' ">

but then it fires the request as 

file:// ....

which fails because the call is supposed to be https://

I did setup a proxy in my ionic.config.json as

{
  "name": "testAjax",
  "app_id": "",
  "v2": true,
  "proxies": [{
  	"path": "/rafitows",
  	"proxyUrl": "https://rafitoapp.com/rafitows/"
   }]
}


What am I missing ? Thanks

**Comment by jgw96** [comment]
@alyn000r Hello! Are you still having this issue with the latest version of ionic?

**Comment by alyn000r** [comment]
I am on the same version the issue that I am having is that it keeps the file:// and ignores the proxy which I setup in my ionic project file. Am I missing something or this proxy thing is fixed in the new version ? Thank You

**Comment by jgw96** [comment]
Hello @alyn000r ! So after lots of testing with different versions of Android i cant seem to reproduce this issue at all. My guess is that something is wrong with the web server you are sending requests too. I am very sorry that i do not have a better answer ! I would suggest asking around on our forum (forum.ionicframework.com) or StackOverflow and seeing if anyone has the same issue. If so, please feel free to comment here and i will reopen this issue. Thanks  for using Ionic!
