### ISSUE TITLE
Change Content of Loading Component

### ISSUE THREAD

**Issue by kentongray** [driftyco/ionic#6103]
Using the new Loading component in Ionic2 🙏 (thank you!) and trying to figure out the recommended way to change the content of the loading message (for loading messages that keep the user updated as to what is happening, eg Connecting to Server, Downloading Data, Preparing, etc). Is the recommended way to dismiss and recreate? Seems like it could be more work than needed. Let me know if I'm missing something obvious.

HACK ALERT:
If you really want to do this in an unsupported way you can do this
`this.existingLoader.data.content = str`;

If you are open to having a content setter on the loading component that does this I'd gladly setup a pull request.

**Comment by thiphariel** [comment]
Hey, you can just grab it from your DOM and update it's innerHTML. The loader content class is <code>.loading-content</code>

**Comment by brandyscarney** [comment]
Hey @kentongray, thanks for the issue! I think adding a `setContent` function would be a good addition. It should be similar to alert's functions: https://github.com/driftyco/ionic/blob/2.0/ionic/components/alert/alert.ts#L158-L170

If you want to create a PR that would be helpful, just let me know!

**Comment by jmarginier** [comment]
+1

**Comment by jmarginier** [comment]
+1

**Comment by brandyscarney** [comment]
Thanks to  @stonelasley for PR https://github.com/driftyco/ionic/pull/7697! This will be in the beta 12 release.

**Comment by meeximum** [comment]
setContent is not working when called inside a Promise chain? Maybe a problem with scopes (change detection)?

**Comment by vptcnt** [comment]
I confirm.. It's not working inside a Promise.

**Comment by maxpaj** [comment]
It's not really working for me.

**Comment by loopezz** [comment]
I can confirm this too. Here is a temporary fix.
import:
`import { NgZone } from '@angular/core';`

Add NgZone to the constructor:
`constructor(public ngZone: NgZone){}`

Use NgZone to trigger the change detection. Something like this:
```
let loader = this.loadingCtrl.create({
	content: 'Some static value'
});

loader.present();

this.function().subscribe((data: any) => {
	this.ngZone.run(() => {
		loader.setContent('Some dynamic value ' + data.value);
	});
});
```

**Comment by cocowalla** [comment]
Still an issue as of Ionic 3 - can this issue be reopened?

**Comment by Ross-Rawlins** [comment]
+1

**Comment by DarthFarzad** [comment]
Is it possible to have a content URL? that is to say having a loader with the same content in multiple places and not having to repeat the code?

**Comment by ivaro18** [comment]
@maxpaj  Can confirm that the 'hack' works while using the Transfer plugin.
```
loading: any;

constructor(loadingCtrl: LoadingController, myService: MyService) {   }

transferFile( ) {
   //retrieve some file 
   let file = new File();
   this.loading = this.loadingCtrl.create({content: "0%"});
   this.myService.onProgress(this.loading);
   this.myService.transferFile(file);
}
```

And then just 'hack' in your service:
```
onProgress(loader: any) {
   this.fileTransfer.onProgress(event => {
        loader.data.content = (Math.round((event.loaded / event.total) * 100))+"%";
   });
}
```

**Comment by qwerqwermhc** [comment]
Hello, I would like to ask you to do a countdown Well, I found that this loadingCtrl content will not be updated in time, for example, I do a 30 second countdown he will remain in 30 seconds, you who told me how to achieve it

**Comment by arekkoperek** [comment]
this solution works partially -> I need to touch screen to see updated value in loader content (android). Anyone has this issue?

**Comment by joschi77** [comment]
@arekkoperek Yes, I have the same behaviour on iOS and Android.
