### ISSUE TITLE
bug: template is getting reloaded 10-12 times & fns

### ISSUE THREAD

**Issue by luckyycool** [driftyco/ionic#6105]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>have verified, controller is getting loaded only once not multiple times. Also, If I add more routes in app.js the number of print keeps increasing as well.

Issue demo: http://codepen.io/anon/pen/XXxxpM (check console in browser)</span>

<span is-issue-template></span>

**Comment by luckyycool** [comment]
Your system information:

Cordova CLI: Not installed
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7
Node Version: v4.2.4

**Comment by luckyycool** [comment]
is Anyone looking into this bug...code open url is also there to live test

**Comment by vitaliy-bobrov** [comment]
This is not template triggering just angular invoking your function, please read about angular $digest. If you want to init something with function just call it in controller.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
