### ISSUE TITLE
iframe inner html    position: absolute; not work

### ISSUE THREAD

**Issue by gitHubLie** [driftyco/ionic#6107]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, im having a hard time understanding what the issue your having is. Would you mind filling out some of the information that was in the issue template and posting it here? That would help us out tremendously in helping get your issue fixed. Thanks again!

**Comment by gitHubLie** [comment]
OK !
please  look this. https://www.youtube.com/watch?v=imIIk8pRVgI&feature=youtu.be

this is my code
  <ion-content scroll="true" overflow-scroll="true" class="iframe-wrapper">
     <ion-refresher pulling-text="reflash" on-refresh="doRefresh()"> </ion-refresher>
     <iframe id="targetFrame" data-tap-disabled="true" ng-src="{{myURL}}" style="opacity:1"></iframe>
  </ion-content>


.iframe-wrapper {
   position: fixed;
    right: 0;
    bottom: 0;
    left: 0;
    top: 0;
    -webkit-overflow-scrolling: touch !important;
    overflow: scroll !important;

    iframe {
      height: 100%;
      width: 100%;
    }
 }

in iframe HTML using jQuery , I set black bar position:fixed is not work.
and in PC is OK in IOS not work.
sometime sliding up screen have wobble;
thank you.
Very worry

**Comment by gitHubLie** [comment]
Actually I want  black bar always at the bottom in iframe. but  I try any way, not work . please help me .thanks

**Comment by jgw96** [comment]
Hello! Sorry for the late reply on this issue. It seems that your using an iframe full screen for your app, which is not something we can really support. I would recommend building out the app with Ionic instead of using a fullscreen iframe as you will get much better performance, wont have to deal with any potential security concerns related to iframe's and you app will work much more consistently. Thanks for using Ionic!

**Comment by gitHubLie** [comment]
👎
