### ISSUE TITLE
Improve ion-img performance

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6112]
Safari has troubles cancelling image requests with the img src changes. Manually handle image HTTP requests, rather than letting `<img>` attempt to handle this.

**Comment by manucorporat** [comment]
do you think we should fill a bug report in safari/webkit as well?

**Comment by adamdbradley** [comment]
This is largely only a UIWebView problem, so I guess they kind of did fix it in WKWebView. The new way will not reuse the same img element, so it does a better job at aborting image requests.
