### ISSUE TITLE
Document the tappable attribute

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6113]
In general we recommend always using a button or anchor element when it's clickable. Otherwise you'll need to add the `tappable` attribute to remove the 300ms delay on iOS, when clicking a non-clickable element like a `<p>` or `<div>`.

**Comment by dylanvdmerwe** [comment]
Is this also required for when making things like `<ion-item>` clickable?

**Comment by thiphariel** [comment]
@dylanvdmerwe I personnaly did, cause if you add tappable on ```<ion-item>```, it will get the correct tap animation (like ripple effect on Android for example)

**Comment by jgw96** [comment]
This was fixed by my above PR. (:

**Comment by quentinchap** [comment]
there is some change since this documentation update ? there is some weird behaviour with tappable attribute ... (double click needed, lag etc.)
