### ISSUE TITLE
Ion-input not implementing form directives

### ISSUE THREAD

**Issue by Lindstrom1989** [driftyco/ionic#6114]
#### Short description of the problem:

After trying to debug this problem ion-input does not behave the same as input when using form directives in @component, why wont this work? it does seem to work in @page though. See console log on this...
http://plnkr.co/edit/rYao7D5M10RnyFC8ZUM7?p=preview

**Steps to reproduce:**
1. open plunker
2. run
3. open console log

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So to be able to use ionic components like `ion-input` in a standard Angular 2 component you have to import `IONIC_DIRECTIVES` from `ionic/angular` and inject them into your angular 2 component directives array. Once you do this all ionic components should work exactly the same in your regular Angular 2 Component as they do in an ionic `page` component. Thanks again!
