### ISSUE TITLE
docs: exemplos de app

### ISSUE THREAD

**Issue by cariolano** [driftyco/ionic#6118]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Entender mais sobre desenvolvimento mobile.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Olá! Graças para a abertura de um problema com a gente! Sinto muito , mas não sou realmente entender o seu relatório de problema. Você se importaria de explicar um pouco mais do que está errado com a documentação ?

**Comment by jgw96** [comment]
Desde que foi um pouco de tempo já que não havia qualquer atividade sobre esta questão i será fechá-lo , mas fique à vontade para responder de volta se o seu ainda tendo a questão !
