### ISSUE TITLE
bug: Ion-toggle submits form

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic#6120]
#### Short description of the problem:
When a `<ion-toggle>` is placed inside a `<form>` the form gets submitted when switching the state of the toggle.

#### What behavior are you expecting?
It should be possible to switch the state of the toggle without the form gets submitted.

**Steps to reproduce:**
1. Open the [demo plunker environment](http://plnkr.co/edit/xOaUceJochQo1IdnC5IQ?p=preview).
2. Switch the state of any of the toggles - form's `submit()` handled is called.
3. Switch the state of any of the checkboxes or radio-elements - they don't submit the form _(i.e. work as expected)_.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

https://forum.ionicframework.com/t/ion-toggle-submits-form/49002 

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/xOaUceJochQo1IdnC5IQ?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by adamdbradley** [comment]
Fixed in https://github.com/driftyco/ionic/commit/f17f5172e30b0b8940b72dda9ec44d16a7a5c86e

Thanks!
