### ISSUE TITLE
Ionic2 start stuck for sidemenu template

### ISSUE THREAD

**Issue by mlaffargue** [driftyco/ionic#6123]
#### Short description of the problem:
Using `ionic start myapp tabs --v2` works correctly
Using `ionic start myapp sidemenu` works correctly
Using `ionic start myapp sidemenu --v2` just get stuck after logging :

> $ ionic start myapp sidemenu --v2
>Creating Ionic app in folder C:\xxxxxx\myapp based on sidemenu project
>Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
>Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip

#### What behavior are you expecting?
I'm expecting the v2 template of sidemenu to work

**Steps to reproduce:**
1. `ionic start myapp sidemenu --v2`

**Which Ionic Version?**
Ionic CLI  v2.0.0-beta.24

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue! Since this issue is more relevant to the ionic cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#927
