### ISSUE TITLE
iOS 8.X.X bug Ionic 2

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#6127]
I updated my ionic 2 version to a newer version and I am using ios@3.9.0 so it will be compatible with a plugin that I am using. I had memory leaks problems and that was the reason for updating it. Now I have problem on safari which is probably related with the angular2 polyfills. I can run the app on ios 9+ devices but I am not able to run the page on ios 8.x.x. I also tried hosting the files and open it directly on safari, and inspecting it results in the same errors. Here is the following error
```
EXCEPTION: TypeError: undefined is not a function (evaluating 'm[4].startsWith('{' + BLOCK_PLACEHOLDER)')
logErrorbrowser_adapter.ts:72
logGroupbrowser_adapter.ts:83
callexception_handler.ts:47
(anonymous function)application_ref.ts:261
_notifyOnErrorng_zone.ts:453
onErrorng_zone.ts:351
runangular2-polyfills.js:1246
(anonymous function)ng_zone.ts:370
zoneBoundFnangular2-polyfills.js:1219
lib$es6$promise$$internal$$tryCatchangular2-polyfills.js:467
lib$es6$promise$$internal$$invokeCallbackangular2-polyfills.js:479
(anonymous function)angular2-polyfills.js:1027
(anonymous function)angular2-polyfills.js:122
microtaskng_zone.ts:409
runangular2-polyfills.js:1242
(anonymous function)ng_zone.ts:370
zoneBoundFnangular2-polyfills.js:1219
lib$es6$promise$asap$$flushangular2-polyfills.js:261
PromiseResolutionHandlerFunction
```

Does anyone have a problem with this or tested their app on ios 8 after updating to newer version of ionic 2?

**Comment by denkomanceski** [comment]
I had to add es-shim :( so bad wasted 5 hours

**Comment by peterterbe** [comment]
@denkomanceski How did you add es6-shim? Simply included in index.html? Shall I require it in main.ts or something?

**Comment by mariohmol** [comment]
@peterterbe did u find?
