### ISSUE TITLE
Npm link does not work when developing against latest version of ionic 2

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6128]
#### Short description of the problem
After running `gulp package build`, i npm link the dist directory, then link to that in my app directory, as per the build docs. But that does not seem to work correctly anymore as the app will not load at all, and i get a ton of `cant find module ionic-angular` errors when trying to run the app using `ionic serve. Building the repo and then copying the contents of the dist folder over to the ionic-angular folder in my app directory works fine.

**Steps to reproduce:**
1. Follow these instructions exactly: https://github.com/driftyco/ionic/blob/2.0/scripts/README.md
2. run `ionic serve` and notice above mentioned issues.

latest 2.0 branch

**Comment by jthoms1** [comment]
@jgw96 I received similar errors when I forgot to run `npm link ionic-angular` from my app directory, but after doing so all was resolved. 

Could you supply me with the out you received when executing `ionic serve`? Thanks!

**Comment by jgw96** [comment]
@jthoms1 Hey! So yeah i run `sudo npm link ionic-angular`(after the other steps of course) from my app directory then did `ionic-serve` and get this 
![screen shot 2016-04-13 at 2 37 26 pm](https://cloud.githubusercontent.com/assets/8823093/14506854/8191be56-0185-11e6-8721-c365eab0c006.png)

**Comment by ramonornela** [comment]
@jgw96 was resolved? I'm having trouble running with build.release, because think that the docs It is focused to ES6 project

**Comment by jgw96** [comment]
Hello @ramonornela ! You can run `gulp package build --typecheck` and then copy and paste the contents of the `ionic/dist` directory to the `ionic-angular` package in your testing app. Thanks!

**Comment by ramonornela** [comment]
Very thanks @jgw96 ;) problem with npm link (copy and paste fixed).
