### ISSUE TITLE
@font-face OpenType embedding

### ISSUE THREAD

**Issue by gcrockenberg** [driftyco/ionic#6129]
Generating CSS3114 errors on Windows phone

CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
noto-sans-regular.ttf

**Steps to reproduce:**
1.  Set Config.mode to 'wp' 
2. Run on Windows Phone

Lumia 950 XL
Windows 10 Mobile

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 8.1
Node Version: v0.12.2

**Comment by mhartington** [comment]
Other than run on windows phone, what other steps do I need to follow for this? Is this happening with ionicons?

**Comment by mhartington** [comment]
Hey there! So it looks this issues has been inactive for some time. I'm going to close it. If there's still an issue, please submit a new issue with the steps to reproduce. Thanks!
