### ISSUE TITLE
issue(tappable): tappable not applying to child elements

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6130]
#### Short description of the problem:
Upon learning about the `tappable` attribute, I added this to an ion-item of mine. The entire ion-item is meant to be able to be pressed. However the inner elements of the ion-item still have the 300ms delay. Should this attribute not be propagated within all child elements?

```
            <ion-item tappable text-wrap (click)="invite()" class='seperator'>
                <ion-icon name="body" item-left large></ion-icon>
                <h2>Invite a friend</h2>
                <p>For every friend that registers, your chances of winning increase!</p>
                <ion-icon name="arrow-forward" item-right small></ion-icon>
            </ion-item
```

All the elements inside the highlighted area should have the 300ms delay removed. But when pressing the paragraph or heading tags this is not the case.

![capture](https://cloud.githubusercontent.com/assets/2852839/14460304/23a5c8c8-00bd-11e6-982a-2583dd541352.PNG)

 

**Which Ionic Version?** 2.x beta 4

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us. So in your case a good solution is to make the whole `ion-item` a button, like this 
```
<button ion-item text-wrap (click)="invite()" class='seperator'>
                <ion-icon name="body" item-left large></ion-icon>
                <h2>Invite a friend</h2>
                <p>For every friend that registers, your chances of winning increase!</p>
                <ion-icon name="arrow-forward" item-right small></ion-icon>
            </button>
```
This gives you two advantages, first for accessibility a screen reader will now know that that ion-item is clickable. Also this will get rid of the 300ms delay for the whole element, and the elements inside. Hopefully this helps you!

ps: here is a good link on the `<button ion-item />` syntax: http://ionicframework.com/docs/v2/api/components/item/Item/

**Comment by jgw96** [comment]
Going ahead and closing this issue as the above solution should solve the issue. If not ill happily reopen! (:

**Comment by dylanvdmerwe** [comment]
Perfect thanks @jgw96

**Comment by jgw96** [comment]
No problem @dylanvdmerwe !

**Comment by aggarwalankush** [comment]
@jgw96 converting ion-item to button helped. But when I click, screen flickers a little and then move to next screen. Is there any solution for that?

**Comment by jgw96** [comment]
@aggarwalankush Hello (: Would you mind opening a separate issue please? Thanks!
