### ISSUE TITLE
Upload image without using file transfer plugin is there any way..??

### ISSUE THREAD

**Issue by Poojal123** [driftyco/ionic#6131]
//
 navigator.camera.getPicture(onSuccess, onFail, {
                    sourceType: navigator.camera.PictureSourceType.PHOTOLIBRARY,
                    allowEdit: true,
                    targetWidth: 400,
                    targetHeight: 400,
                    destinationType: Camera.DestinationType.FILE_URI,
                    mediaType: navigator.camera.MediaType.PHOTO
                });
                function onSuccess(imagedata) {
                    $("#dummy_dp_upload").hide();
                    $("#real_dp_upload").hide();
                    var prodile_image = '';
                    var img_url = '';
                 //   alert(imagedata);
                    if (real_or_dummy == "real") {
                        prodile_image = document.getElementById('profile-image');
                        img_url = imagedata.split("?");
//                        if(prodile_image.src !== ''){
//                            prodile_image.src ="";
                        prodile_image.src = img_url[0];
                         if ($("#avatar_flag_real").val() == '1') {
                            $("#remove_edit_realdp").val(1);
                        }
                        result_real_fm = img_url[0].substr(img_url[0].lastIndexOf('/') + 1);
//                        profile_pic[1] = img_url[0];
                        var c = document.getElementById("canvas_dp");
                        var ctx = c.getContext("2d");
                        var img = document.getElementById("profile-image");
                        ctx.drawImage(img, 10, 10);
                        console.log(c.toDataURL());

                        var imageData = c.toDataURL();
                        var b64 = imageData.replace('data:image/png;base64,', '');
                        var binary = window.atob(b64);
                        var array = [];
                        for (var i = 0; i < binary.length; i++) {
                            array.push(binary.charCodeAt(i));
                        }
                        var mimeString = c.toDataURL().split(',')[0].split(':')[1].split(';')[0];
                        profile_pic[1]=new Blob([new Uint8Array(array)], {type: mimeString});
                        console.log("in real " + profile_pic);
//                }

                    }
});

//

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Since this is more of a question you will be able to get a better answer over at our forum (https://forum.ionicframework.com/) or our slack channel (http://ionicworldwide.herokuapp.com/). Thanks again!
