### ISSUE TITLE
config mode:'ios' doesn't override tabSubPages defaults on Android

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#6132]
#### Short description of the problem:
Using mode: 'ios' in the app.ts config sets the default mode to ios for the app. However tabSubPages still defaults to the md default true on Android.

#### What behavior are you expecting?
I would have expected it to default to the ios standard: tabSubPages: false.
I would expect that setting mode: 'ios' without any other config options would mean that ios & android behaved identically. 

**Steps to reproduce:**
1. use ionic2 starter tabs
2. add subpage
3. set config mode: 'ios'

**Which Ionic Version?** or 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta 8` release. :smile:
