### ISSUE TITLE
Regression in Beta4 when displaying two ion-labels inside ion-item

### ISSUE THREAD

**Issue by ksachdeva** [driftyco/ionic#6134]
#### Short description of the problem:

After upgrading to Beta.4 one of my custom component is not displaying as expected. It displays fine with beta3. The second ion-label is automatically centered in beta.4

#### What behavior are you expecting?

Same behavior as beta3

**Steps to reproduce:**
1. Example of code for Beta 3 - http://codepen.io/ksachdeva/pen/PNQgdB
2. Example of code for Beta 4 - http://codepen.io/ksachdeva/pen/mPXgaL

```
insert any relevant code between the above and below backticks

<ion-card>

    <ion-item>
      <span item-left>Emails</span>
      <button primary clear item-right>
        <ion-icon name="add"></ion-icon>
      </button>
    </ion-item>

    <ion-list>
      <ion-item-sliding *ngFor="#e of [{label:'personal', value:'a@abc.com'}, {label: 'work', value:'b@dee.com'}]">
        <ion-item>
          <ion-label stacked>{{e.label}}</ion-label>
          <ion-label>{{e.value}}</ion-label>
        </ion-item>
        <ion-item-options>
          <button primary (click)="edit(e)">
            <ion-icon name="create"></ion-icon>
            Edit
          </button>
          <button danger (click)="delete(e)">
            <ion-icon name="trash"></ion-icon>
            Delete
          </button>
        </ion-item-options>
      </ion-item-sliding>
    </ion-list>

  </ion-card>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

Ionic 2 Beta 4

#### Plunker that shows an example of your issue

1. Example of code for Beta 3 - http://codepen.io/ksachdeva/pen/PNQgdB
2. Example of code for Beta 4 - http://codepen.io/ksachdeva/pen/mPXgaL

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X Yosemite
Node Version: v5.10.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by ksachdeva** [comment]
Issue is present in beta.5 as well. Here is a link to the code pen :  http://codepen.io/ksachdeva/pen/mPKoGY

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be in the `beta.8` release.
