### ISSUE TITLE
CHANGELOG.md for version 2 does not contain Beta.4 changes.

### ISSUE THREAD

**Issue by ronaldborman** [driftyco/ionic#6136]
While researching a problem, I noticed the latest CHANGELOG.md for version 2 (https://github.com/driftyco/ionic/blob/v2.0.0-beta.4/CHANGELOG.md) only contains changes up to Beta.3.

**Comment by jgw96** [comment]
Hello! You can find all the changes and updates to beta.4 here https://github.com/driftyco/ionic/releases/tag/v2.0.0-beta.4. Thanks for using ionic!
