### ISSUE TITLE
VirtualScroll not working with nested objects

### ISSUE THREAD

**Issue by nickgal** [driftyco/ionic#6137]
#### Short description of the problem:
Exception when using nested objects with virtual scroll.

#### What behavior are you expecting?
Access to nested properties.

**Steps to reproduce:**
1. Create virtual scroll with an array of nested objects
2. Try to scroll past the initial items

```js
// example nested object
{ 
  title: 'Title', 
  author: { 
    name: 'Name'
  }
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
```
angular2.dev.js:23877 TypeError: Cannot read property 'name' of undefined
    at AbstractChangeDetector.ChangeDetector_HomePage_2.detectChangesInRecordsInternal (viewFactory_HomePage:246)
    at AbstractChangeDetector.detectChangesInRecords (angular2.dev.js:9609)
    at AbstractChangeDetector.runDetectChanges (angular2.dev.js:9592)
    at AbstractChangeDetector._detectChangesContentChildren (angular2.dev.js:9665)
    at AbstractChangeDetector.runDetectChanges (angular2.dev.js:9593)
    at AbstractChangeDetector.detectChanges (angular2.dev.js:9581)
    at ChangeDetectorRef_.detectChanges (angular2.dev.js:5252)
    at VirtualScroll.renderVirtual (ionic.system.js:25046)
    at ionic.system.js:25026
    at readDimensions (ionic.system.js:25009)
```

**Which Ionic Version?** 1.x or 2.x
2 beta 4

#### Plunker that shows an example of your issue

http://plnkr.co/edit/JLlwIn3a1Ws8wavbX2Gj?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.10.0
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by galvanu** [comment]
Happens also even if the viewModel contains only primitives and the view (html) contains binding to a method of the view mode.
For example:

```
<ion-list [virtualScroll]="items">

  <ion-item *virtualItem="#item">
      {{item.getTitle()}}
  </ion-item>

</ion-list>
```

**Comment by jgw96** [comment]
@galvanu Are you using Ionic 2 beta.6?

**Comment by galvanu** [comment]
Yeah, this is my ionic info output:
Cordova CLI: 6.1.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X Yosemite
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by ZiFFeL1992** [comment]
Same here on beta.6:

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by ghenry22** [comment]
This may be related this other ticket around performance issues with virtualScroll #6104 .  These issues still persist exactly the same in beta7.  Virtualscroll is basically unusable on iOS currently for me.

**Comment by toinouu** [comment]
+1

**Comment by adamdbradley** [comment]
Thanks for the report, it should be fixed in the next release. Thanks

**Comment by elineopsommer** [comment]
@adamdbradley this is still an issue see #6974

**Comment by FrancescoMussi** [comment]
Guuys it seems it doesn't yet work properly

**Comment by mikethm** [comment]
+1
