### ISSUE TITLE
Create a tagged npm nightly release

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6138]
We do not need to create an npm version on every commit, however it would be nice to manually create a nightly release.

For testing purposes it'd be nice to quickly build an npm version like `ionic-angular@nightly`. The actual version could be something like `beta.5.TIMESTAMP` or whatever a good standard is.

`gulp publish.nightly`

It can skip the github release and any changelog updates.

**Comment by jthoms1** [comment]
I will setup a simple shell script to do this from a cron job. I will work on getting a server instance to throw it on. Do you have a date you would like to start or just ASAP?

**Comment by adamdbradley** [comment]
It'd be great if it could reuse a lot of the existing gulp tasks: https://github.com/driftyco/ionic/blob/2.0/gulpfile.js#L720

**Comment by jthoms1** [comment]
Closed with PR #6146.
