### ISSUE TITLE
The ionic 2 starter tabs gets a white screen on android

### ISSUE THREAD

**Issue by jpmsegurado** [driftyco/ionic#6139]
I was working on a project and just using the ionic serve to do first the layout stuff, and then I tried to run it on android and it gave me a white screen, and my code does not log any errors on the console. So I tried to create a new tabs project just to check if it was my code, but the tabs starter gives me the same white screen. Although both project works just fine with ionic serve. Sorry if my english is bad.

My ionic info:
`Cordova CLI: 6.0.0`
`Gulp version:  CLI version 3.9.1`
`Gulp local:   Local version 3.9.1`
`Ionic Version: 2.0.0-beta.4`
`Ionic CLI Version: 2.0.0-beta.22`
`Ionic App Lib Version: 2.0.0-beta.12`
`OS:`
`Node Version: v4.2.6`

**Comment by jgw96** [comment]
Hello! No problem, your english is fine (:  So yeah this is a known issue with the beta.4 release that we have already fixed and is slated to land in the beta.5 release. As a workaround until beta.5 comes out you can simply comment out this part of your app.ts.

```
platform.ready().then(() => {
        // Okay, so the platform is ready and our plugins are available.
        // Here you can do any higher level native things you might need.
       StatusBar.backgroundColorByHexString("#1A237E");
});
```
