### ISSUE TITLE
Events doc needs clarification for `.publish()`

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6142]
#### Short description of the problem:
The [Events documentation ](https://github.com/driftyco/ionic/blob/2.0/ionic/util/events.ts#L88) for the `.publish()` implies that the argument signature is `topic:string, eventData:any`. However, in practice, it is actually a variable number of arguments: `topic:string, ...args`.

Right now, event handlers will receive an argument array `args:any[]` instead of the implied single-object `eventData:any`. This should be clarified one way or the other.

**Which Ionic Version?**
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.8.0

**Comment by jgw96** [comment]
Hello! As this is an issue with the docs site instead of the actual framework i will be moving this issue over to that repo. Thanks and feel free to continue the conversation over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#544
