### ISSUE TITLE
ion-toggle unnecessarily triggers `change` event when default value is true

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6144]
#### Short description of the problem:
ion-toggle unnecessarily triggers `change` event when the default value is true

#### What behavior are you expecting?
The change event should not fire until the user presses the toggle

**Steps to reproduce:**
1. Create an ion-toggle with ngModel bound to a variable with a default value of true
2. Observe change event firing without any user input

```
toggle: boolean = true;

<ion-toggle [(ngModel)]="toggle"
                      (change)="onUpdateToggle($event)"></ion-toggle>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This only fires when the default value is `true`.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.4

#### Plunker that shows an example of your issue
http://plnkr.co/edit/f2NSVLP1DETbkyFmpSN8?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v5.8.0

**Comment by danielcrk-cn** [comment]
I can confirm this.

**Comment by cubicleWar** [comment]
It seems like this issue is back as of 2.0.0-beta.11

**Comment by jvelo** [comment]
I can reproduce on RC.0 as well

**Comment by thebasix** [comment]
Any update on this? In my case ion-toggle, ionChange runs on initial ngFor if value is set to true. I dont want that. Has anyone found a solution?

**Comment by ErvalhouS** [comment]
Well, my fix is set the change function to fire only if I set a boolean value to true, while setting it to false on the event itself and the element constructor. Then, put one tap event function to set it to true, magic 💃, but not ideal.

**Comment by mizdler** [comment]
The issue is still exists! I'm using ionic 2.4.8

**Comment by austinemayer** [comment]
I am now on Ionic 3.2.0 and this is still an issue. Has anyone been able to find fix for this?
