### ISSUE TITLE
ScrollTop(false) almost never works with native scrolling

### ISSUE THREAD

**Issue by zanemcca** [driftyco/ionic#6145]
#### Short description of the problem:

ScrollTop does not do anything the majority of the time when using native scrolling and no animations. 

This occurs on iOS and Android.

Upon inspection on iOS it appears that if a scroll is occurring already before the scrollTop call then it will set the scroll position to 0 during the original scrolls animation without updating the view. After the original scroll completes the height will be set back to where the original would normally end.
#### What behavior are you expecting?

`scrollTop()` should always scroll to top.

Also I think it should be interrupting an active scroll and taking over. Not waiting until the current scroll finishes before scrolling to the top, which seems to happen when `scrollTop(true)` is used. Without this it looks very unnatural.

**Steps to reproduce:**
1. Use native scrolling
2. Call `scrollTop(false)` while a scroll is currently occurring

This is with ionic 1.4.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#148
