### ISSUE TITLE
Animations not working when ui-view on body

### ISSUE THREAD

**Issue by timlind** [driftyco/ionic#6147]
#### Short description of the problem:

animations are skipped when ui-view is on the body element instead of on an element within the body. `areAnimationsAllowed` method is using the `<!-- ui-view: -->` comment above the body as rootElement and considering the elements to animate "not part of the rootElement".

#### What behavior are you expecting?

animations.

**Steps to reproduce:**
1. setup css transition animation on ng-if
2. put ui-view on body element
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

1.2.4

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.0 Build version 7A220

**Comment by jgw96** [comment]
Hello! Thanks for opening am issue with us! I would like to ask why you are using ui-view in your ionic app instead of ion-nav-view?

**Comment by timlind** [comment]
nav view is not worth the world of pain. previous content was being left in the DOM and preventing links from navigating.

Are you reporting this over to ui router / angular?

**Comment by jgw96** [comment]
Hey! Yes we do work closely with both the ui-router team and the Angular team. So with ionic apps we cannot recommend that you use ui-view instead of ion-nav-view as are animations and transitions are built around using ion-nav-view. Would you mind telling me more about the issues you were having with ion-nav-view? And maybe make a plunker or codepen to show some of those issues?

**Comment by jgw96** [comment]
Hello! I am gonna be closing this issue for now as it has been a little while since there was any activity on this issue. Feel free to comment back if your still having this issue though! And, thanks for using Ionic (:
