### ISSUE TITLE
Pull to refresh still active while swiping left on item in list (Android)

### ISSUE THREAD

**Issue by mklilley** [driftyco/ionic#6149]
Hi,

I noticed on Android (Google Nexus 4, Android version 5.1.1) that if I have an ion-refresher on a view which also has a swipable list then if I am at the top of the list and swipe left then pull to refresh is still active, i.e the item swipes left but the whole view is also pulled down - not a nice user experience I would say.  If however I have scrolled some way down the list then this behaviour does not occur and swiping left works just as I would expect, i.e. if i swipe left I cannot simultaneously scroll down. This doesn't seem to be a problem on iOS (version 9.3.1).

To reproduce:

1) Run ionic start test tabs
2) Go to test directory and run ionic platform add android
3) Replace the code in tab-dash.html with the following:

```
<ion-view view-title="Dashboard">

    <ion-content class="padding">

        <ion-refresher pulling-text="Pull to refresh..."></ion-refresher>

        <ion-list>

            <ion-item ng-repeat="item in items">{{item}}

                <ion-option-button class="button-positive">
                    Share
                </ion-option-button>

                <ion-option-button class="button-assertive">
                    Edit
                </ion-option-button>


            </ion-item>

        </ion-list>

    </ion-content>

</ion-view>
```

4) Add the following code to DashCtrl inside of controllers.js:

`$scope.items = [1,2,3,4,5,6,7,8,9,10,11,12];`

5) Run ionic run android
6) Swipe left on any item and if you have not been 100% horizontal in your swiping action then you'll notice the view being simultaneously pulled down
7) Now scroll down a bit so that item number 1 is no longer visible - swipe left now works as it should
8) Go back to the code, remove ion-refresher and try again - no problems with swipe action.

**Comment by mklilley** [comment]
Hi,
Does anyone have any comment about this behaviour? It really seems like a bug because iOS doesn't display the same behaviour
Thanks 
Matt

**Comment by cesar-oyarzun-m** [comment]
@mklilley I have similar problem I have a pull to refresh but the swipe on my list doesn't work, it doesn't get active, this only happen if I add the pull to refresh component

**Comment by flexxis** [comment]
I can confirm this behaviour. list option buttons in combination with ion refresher do not work together. Refresher does its job, but the swipe buttons do not become visible (however, there are existent in the DOM). If I disable the refresher, the option buttons swipes as expected again.

**Comment by Asterodeia** [comment]
I have the same problem when I am using native-scrolling, I did not experience that on javascript scrolling. Is there a way to de-activate the refresher if we are swiping?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#147
