### ISSUE TITLE
$ionicNavBarDelegate - showBackButton - `undefined`

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#6150]
Docs: http://ionicframework.com/docs/api/service/$ionicNavBarDelegate/

Plunker: http://plnkr.co/edit/ZP9vpc?p=preview

Image:
![show back button issues](https://cloud.githubusercontent.com/assets/249703/14489298/4984c6d2-0164-11e6-8a26-6c629dde73e8.png)

For some reason calling `showBackButton` returns `undefined`.

I need this method to implement my custom NavBar, since it isn't working I may try another approach with making NavBar transparent and adding background picture. Meanwhile - it would be great to know why the thing is undefined...

**Comment by werdnanoslen** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#146
