### ISSUE TITLE
Ion-content on-scroll function called when just clicking a list item

### ISSUE THREAD

**Issue by etipirev** [driftyco/ionic#6152]
Im developing an app that have a scrollable list of items. Each item has option buttons that i show programmatically clicking on item avatar and I want to hide them by swiping back or just by scrolling away like default behavior. The problem is that when i click on item's avatar, css transition is correctly done and option buttons are shown, but shortly after on-scroll event is fired (even if i just clicked the avatar without scrolling) hiding them back. So the final result is like nothing happens clicking on avatar.

Just by clicking any item the on-scroll event is fired
Codepen: http://codepen.io/etipirev/pen/aNYNpy?editors=1111

Forum: https://forum.ionicframework.com/t/ion-content-on-scroll-function-called-when-just-clicking-a-list-item/49186

System info:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v5.7.0

**Comment by jgw96** [comment]
Thanks for the codepen! I was able to reproduce this issue and will be looking farther into it.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So I tested this issue using your codepen and could not seem to reproduce the issue. Are the exact steps to repro the issue just to click on a list item?

**Comment by etipirev** [comment]
Yes,  clicking on list item fire on-scroll event that outputs "scrolling" in console

**Comment by jgw96** [comment]
@etipirev Ok, i was able to reproduce now with your codepen, dont know why i couldn't before haha. So have you been able to reproduce this on a device?

**Comment by etipirev** [comment]
Yes, it persist in chrome browser as well as on android devices, not tested ios

**Comment by jgw96** [comment]
@etipirev Alright thanks for all the info!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#145
