### ISSUE TITLE
application view overlaps statusbar

### ISSUE THREAD

**Issue by ciekawy** [driftyco/ionic#6154]
#### Short description of the problem:
on iOS application view overlaps statusbar even for simple layout

#### What behavior are you expecting?
statusbar should remain separate from the ionic application and the top of the ionic view should be aligned with the bottom of statusbar

**Steps to reproduce:**
1. create simple app with side menu, define a few entries in side menu
2. define root page with ion-searchbar, ion-list and ion-infinite-scroll elements
3. run app on ios emulator or real device

**Other information:** 
issue seems to be similar to https://github.com/driftyco/ionic/issues/932

adding `Keyboard.disableScroll(true)` (from `ionic-native`) fixes root page but side menu still overpals the statusbar
 
**Which Ionic Version?** 2.x (recent beta.4)

![image](https://cloud.githubusercontent.com/assets/2847952/14508907/fe07bf8c-01c9-11e6-9a9d-81c7a8f5dbcd.png)

**Comment by ciekawy** [comment]
label v2 hasn't been added by ionitron ;)

**Comment by brandyscarney** [comment]
This should be fixed by https://github.com/driftyco/ionic/issues/5934 in `beta.5`. Could you update to the latest `beta.6` and let me know if it isn't fixed. Thanks!

**Comment by jfi** [comment]
@brandyscarney Thanks! The issue seems fixed for the most part for me, although I can make it happen again by loading an overlay on a click event (i.e. an absolutely positioned div with some content in it). If I can reproduce in a clean app, shall I share with you?

**Comment by brandyscarney** [comment]
Hey @jfi, yes please share it if you are able to reproduce it with one of our components. :smile: Is this a custom div that are you are opening or an Ionic component?

**Comment by wli** [comment]
@jfi @brandyscarney - filed a new issue related to this (https://github.com/driftyco/ionic/issues/6368), which applies to tabs. Not sure if @jfi is using tabs, but that's one way to trigger it. Feel free to merge into this issue, but I wasn't sure if that was best practice.

**Comment by jfi** [comment]
@brandyscarney @wli Here's my issue: #6392. Feel free to merge as required, but thought best as a new issue.
