### ISSUE TITLE
bug: Ionic start on windows 10 doesn't work

### ISSUE THREAD

**Issue by isvicbhasme** [driftyco/ionic#6158]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>My ionic cli version: 2.0.0-beta.24

During 'ionic start app sidemenu --v2 --ts' the script gets stuck at the below step.

E:\Development>ionic start greeter sidemenu --v2 --ts
Creating Ionic app in folder E:\Development\greeter based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/typescript.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/typescript.zip

But when I use the tutorial template with ionic start the script works fine - 'ionic start test tutorial --v2 --ts'.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! This issue has actually already been reported to us and fixed and will be in the next release of the ionic CLI, which should be soon. Thanks and sorry for any hassle this causes in the meantime. (:
