### ISSUE TITLE
bug: Slides page causes a mess in transitions

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6162]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When slides page is pushed from the main page (invoked as navController.push either from constructor or from onPageLoaded method) and when slides page is closed then transitions on that main page and other pages will be blurred together when something else is pushed on top of the main page.

Here is the screenshot where 2 pages are blurred together.</span>
![sliderbug](https://cloud.githubusercontent.com/assets/9930079/14524960/d1d111c8-0243-11e6-9c3a-40e3e1511683.png)

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
