### ISSUE TITLE
Ionicons conditional import does not work

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic#6165]
#### Short description of the problem:

In `components.core.scss` the following conditional import does not work. 

```
$ionicons: true !default;
@if ($ionicons) {
  @import "fonts/ionicons";
}
```

In both cases `$ionicons` true or false `fonts/ionicons` will be imported.

#### What behavior are you expecting?

When `$ionicons` is false `fonts/ionicons` should not be imported.

**Steps to reproduce:**
1. Overwrite `$ionicons` to false
2. Re compile Sass
3. Check that the file is still imported

**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This should be fixed by https://github.com/driftyco/ionic/commit/219059c5b0682365f6bdf243eaf4cd47c611f175 in the latest release.

**Comment by Luchillo** [comment]
(Wo)Man i was just searching for this before making an issue, glad it's fixed for next release, however which version is that?

**Comment by brandyscarney** [comment]
@Luchillo It should be fixed in the beta.6 release. :)

**Comment by Luchillo** [comment]
Yep, just updated all my deps and it works. 😄
