### ISSUE TITLE
$state.go/ng-href strange behaviour when click on item in a ion-list

### ISSUE THREAD

**Issue by yesnoj** [driftyco/ionic#6166]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I'm using Ionic to develop my application, I've ng-href to load new state, which has also a new controller, on the items in a list.
When i click on the item the new state is loaded but, if the html state has an input such a option or a calendar date, even if i don't click anything the calendar popup or the option open!Is like i click two times in the same point of the screen...any suggestion?!
The issue is only on ANDROID 5.0 (Note 3), it works correctly on iOS 9.3.1 (iPhone 6s)

UPDATE: also using a $state.go (nameState) i've the same behaviour ...

#### What behavior are you expecting?
If i click on an element of the list must load the detail of the item selected without interact itself with elements.

**Which Ionic Version?** 1.x or 2.x

 1.2.4-nightly-1917

**Comment by yesnoj** [comment]
ok solved...the issue was  $ionicConfigProvider.views.transition('none'); without this works.

**Comment by jgw96** [comment]
@yesnoj Hey! Im glad you were able to solve your issue. Thanks for using ionic!
