### ISSUE TITLE
Add more detailed docs to CONTRIBUTING

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6172]
The `CONTRIBUTING.md` docs don't really explain how to pull down, build, and test Ionic 2. Would be helpful to current and future contributors to work through the local gulp commands, etc.

**Comment by adamdbradley** [comment]
We should also add a note about the `Help Wanted` label, incase contributors are looking for some issues to help out with.

**Comment by brandyscarney** [comment]
Closing this, let me know if there's anything I need to add/change!
