### ISSUE TITLE
Current working directory is not a Cordova based project

### ISSUE THREAD

**Issue by reynoldbhatia** [driftyco/ionic#6174]
I have everything setup but when I try running 
ionic platform add android 

it just gives me an error saying Current working directory is not a Cordova based project

![image](https://cloud.githubusercontent.com/assets/11049768/14542293/41214666-025c-11e6-9125-3bfbe6a273fe.png)

**Comment by dhirajb1989** [comment]
Is config.xml present there???

**Comment by reynoldbhatia** [comment]
Yes there is.

**Comment by jgw96** [comment]
@reynoldbhatia Hello! Sorry your having an issue getting started with your ionic app! Did you create this app with `ionic start` or did you git clone it from github? Also, do you have cordova installed?

**Comment by reynoldbhatia** [comment]
I created it using ionic start. And yes, I have Cordova installed. Cordova create also works. The project created with Cordova create also gives the same error when I try adding the platform.

**Comment by jgw96** [comment]
@reynoldbhatia thanks for the info! So im gonna defer this issue over to the ionic-cli repo as the guys over there will be able to help you better with this issue than i can.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#935
