### ISSUE TITLE
The ionic 2 starter sidemenu hangs on execution with ionic start

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#6175]
#### Short description of the problem:

When starting a side-menu based project with:

```$ ionic start ionic2-sidemenu sidemenu --v2 --ts```

The process hangs after:

```
Creating Ionic app in folder /Development/ionic2-sidemenu based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/typescript.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/typescript.zip
```

#### What behavior are you expecting?

A scaffolded app folder

**Steps to reproduce:**
1. run ```$ ionic start ionic2-sidemenu sidemenu --v2 --ts``` in an arbitrary folder

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
n/a since there is no project created

**Comment by samuelgoldenbaum** [comment]
Yip, same here

**Comment by basvdijk** [comment]
After running `$ npm update -g` this morning the problem seems to be solved :)
