### ISSUE TITLE
TypeError: removeEventListener of null  on nav.pop() with Tabs

### ISSUE THREAD

**Issue by jvoigt** [driftyco/ionic#6176]
When leaving a Page via this.nav.pop() and if there are Tabs involved an Exception is raised.

so If i'm poping the last Page above the Tabs or one the Tabs themself

this error accurs to when the Tabbed Page is completly left.
so this.setPages([ the-pageinthetap ,   teh other pages-without-tabs]

it still works but at somepoint i had the feel everthing crash somehow. (freezes, buttons dont react anymore)

**stacktrace:**

> EXCEPTION: TypeError: Cannot read property 'removeEventListener' of null
> 
> browser_adapter.ts:73
 TypeError: Cannot read property 'removeEventListener' of null
>     at Refresher._mDown (http://localhost:8100/build/js/app.bundle.js:42818:32)
>     at Refresher._setListeners (http://localhost:8100/build/js/app.bundle.js:50399:33)
>     at Refresher.ngOnDestroy (http://localhost:8100/build/js/app.bundle.js:50420:14)
>     at AbstractChangeDetector.ChangeDetector_HomePage_0.dehydrateDirectives (viewFactory_HomePage:236:20)
>     at AbstractChangeDetector.dehydrate (http://localhost:8100/build/js/app.bundle.js:14009:14)
>     at AbstractChangeDetector.destroyRecursive (http://localhost:8100/build/js/app.bundle.js:14026:14)
>     at AbstractChangeDetector.destroyRecursive (http://localhost:8100/build/js/app.bundle.js:14033:25)
>     at AppView.destroy (http://localhost:8100/build/js/app.bundle.js:23689:29)
>     at AppViewManager_.destroyViewInContainer (http://localhost:8100/build/js/app.bundle.js:24132:14)
>     at ViewContainerRef_.remove (http://localhost:8100/build/js/app.bundle.js:23994:19)
> 
> -----async gap-----
> Error
>     at _getStacktraceWithUncaughtError (http://localhost:8100/build/js/angular2-polyfills.js:2236:29)
>     at Zone.fork (http://localhost:8100/build/js/angular2-polyfills.js:2285:47)
>     at NgZone._createInnerZone (http://localhost:8100/build/js/app.bundle.js:28195:14)
>     at new NgZone (http://localhost:8100/build/js/app.bundle.js:27980:36)
>     at createNgZone (http://localhost:8100/build/js/app.bundle.js:13434:12)
>     at PlatformRef_.application (http://localhost:8100/build/js/app.bundle.js:13535:33)
>     at Object.bootstrap (http://localhost:8100/build/js/app.bundle.js:2692:64)
>     at http://localhost:8100/build/js/app.bundle.js:58910:19
>     at DecorateConstructor (http://localhost:8100/build/js/angular2-polyfills.js:2890:29)
>     at Object.decorate (http://localhost:8100/build/js/angular2-polyfills.js:2452:20)
> 
> Uncaught TypeError: Cannot read property 'removeEventListener' of null
> 

**Ionic Version?** 
2.0.0-beta.24

**`ionic info` :** 
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.6.0

**Comment by adamdbradley** [comment]
I think this may have been fixed in ionic-angular beta4. Could you actually try the nightly version and see if it's fixed there? https://github.com/driftyco/ionic/tree/2.0/scripts#installing-nightly-version

**Comment by jvoigt** [comment]
thats right!
It works again, no more exceptions, after updating to
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4-7b783b3c
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.6.0
```
and updating to:
`ionic-angular@nightly == ionic-angular@2.0.0-beta.4-7b783b3c`
with:
```
angular2@2.0.0-beta.15`
zone.js@0.6.11

```
Still i've got some problems when using this.nav.setPages: some of the Pages keep stuck halfway on the screen, when 

but this may me an error on my acount... still investigating...

I will close this when i' ve isolate the cause.

![image](https://cloud.githubusercontent.com/assets/10059188/14557335/263e651c-02fd-11e6-9f29-37e0b20ac7d9.png)

**Comment by jvoigt** [comment]
This is now a duplicate of:
https://github.com/driftyco/ionic/issues/5712
