### ISSUE TITLE
Text area not scrollable when focussed on iOS

### ISSUE THREAD

**Issue by mklilley** [driftyco/ionic#6178]
Hi,

I am using ionic 1.2.4. I have a problem with a fixed size textarea. When it is in focus i am no longer able to scroll the view. I have inputs on the same view and I have no problem scrolling when they are in focus.

I am aware that this issue was raised before but seems to still be a problem.

The issue appears to be only an present on iOS. I am currently testing on iphone4s but with the latest ios 9.3.1. How to reproduce:

1) Run ionic start test tabs
2) Go to test directory and run ionic platform add ios
3) Add the following code to tab-dash.html just before the end of ion-content

<form>        
   <ion-input class="item item-input">
       <input placeholder="some input">
    </ion-input>
    <ion-input class="item item-input">
        <input placeholder="some other input">
     </ion-input>
   <ion-input class="item item-input">
      <textarea style="height:100px" placeholder="some text area"></textarea>
    </ion-input>
</form>

4) Run ionic build ios
5) Open project file in X-code and install onto iphone
6) Run app on iphone
7) Tap on textarea and try and scroll the view - you cannot
8) Tap on input and try and scroll the view - everything is fine

Thanks for your help,

Matt

**Comment by dhirajb1989** [comment]
Hi,

Even I am facing the above issue .

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#144
