### ISSUE TITLE
$ionicScrollDelegate.anchorScroll() does not work reliably

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#618]
Previous issue: https://github.com/driftyco/ionic/issues/508

The anchorscroll functionality does not work reliably. Check out this Plunkr:
http://plnkr.co/edit/4bPK01zF0e0euJetZbxD?p=preview

I see two issues:
- Anchor elements can not be wrapped in another element. 
  In the Plunkr I have wrapped div id="day2" into another div. Jumping to that link does not work.
- After clicking one or two times all anchor links won't work anymore.

**Comment by amrography** [comment]
this really works for me : http://www.saintsatplay.com/blog/2015/02/scrolling-to-a-page-anchor-in-ionic-framework#.VcvVmPmqqko

**Comment by MrWiLofDoom** [comment]
I can get the scrolling to work well enough, but it isn't consistently scrolling to the same spot. Sometimes it scrolls a little higher and then a second click will scroll to the right spot. A third will go to the higher location again.

Any thoughts?
