### ISSUE TITLE
Title overlapping with Back-Button

### ISSUE THREAD

**Issue by stba42** [driftyco/ionic#6181]
#### Short description of the problem:

In some cases the Back-Button overlaps with the Title within the Nav-Bar.
#### What behavior are you expecting?

I expect the Back-Button either to say "Back" when the title of the last screen is too long, or the current Title to be truncated to prevent it from overlapping. Both seems to be implemented, however it does not always work.

**Steps to reproduce:**
Example code see codepen: 
http://codepen.io/anon/pen/EKLaYM
Set the Browser width e.g. to 375px (iPhone 6)

The issue seems to occur only, when the Titles have a specific length. 

**Which Ionic Version?** 1.x 
#### Plunker that shows an example of your issue

http://codepen.io/anon/pen/EKLaYM
Set the Browser width e.g. to 375px (iPhone 6)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175 
![simulator screen shot 15 04 2016 16 27 36](https://cloud.githubusercontent.com/assets/564214/14566529/3711d31e-0330-11e6-9534-906aba849901.png)

**Comment by stba42** [comment]
The problem seems only to occur when using a different "Back"-Icon. If I remove class="button-icon ion-arrow-left-c" it seems to work.

**Comment by jgw96** [comment]
@stba42 Hello and thanks for opening an issue with us, and also thanks for the codepen and info. Looking more into this now.

**Comment by RAMDdFLEET** [comment]
Ionic records a history of states that you transit to. 
You might wanna add cache: false to your states and as well as reload your state in this way $state.go($state.current, {}, {reload: true}); rather than simply switching between states.

**Comment by Bouzmine** [comment]
Title will also overlap if it's really long, even if back text is "Back". Solution could be pushing the title to the right if there is nothing else on the nav-bar like native does : 
![iOS' Settings app](https://cloud.githubusercontent.com/assets/15067923/15524614/0d22837e-21f2-11e6-884e-e50b42ad5e17.jpg)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#143
