### ISSUE TITLE
bug: npm install -g ionic@beta npm ERR! cb() never call

### ISSUE THREAD

**Issue by arun0009** [driftyco/ionic#6183]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I try to run
   npm install -g ionic@beta
I get an exception: 
npm verb afterAdd /Users/CXI624/.npm/ionic/2.0.0-beta.25/package/package.json written
npm ERR! cb() never called!

Note: I am able to install npm install -g ionic@2.0.0-beta.24 however @beta didn't work even after uninstalling ionic and clean up cache etc</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! Since this issue is related to the ionic-cli repo i will be moving this issue over there. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#936
