### ISSUE TITLE
Not work livereload after adding platform ios

### ISSUE THREAD

**Issue by tenorok** [driftyco/ionic#6184]
#### Short description of the problem:
Not work livereload after adding platform ios.

#### What behavior are you expecting?
Livereload should work.

**Steps to reproduce:**
```
$ ionic start blankApp blank
$ cd blankApp/
$ ionic platform remove ios // It's important step!
$ ionic platform add ios
$ ionic build ios
$ ionic emulate ios --livereload
```
After that will launched simulator, in which infinitely spinning load indicator.
![2016-04-16 0 15 10](https://cloud.githubusercontent.com/assets/1322855/14575160/c552680e-0368-11e6-9696-db11748fce25.png)

But just emulate without livereloading work well:
```
$ ionic emulate ios
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by jacobdr** [comment]
I have seen a similar issue, but with ionc@beta and using Typescript, when running `ionic emulate ios -s -c -l`.
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175
```

I chalked it up to the fact that fancy things like livereload are want to break at the bleeding edge. However, curious to see if maybe it is an OS X config issue and might be able to get my issue fixed as well.

**Comment by jacobdr** [comment]
Also worth noting that I am seeing the same behavior on live-reload when using `ion run ios`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So since this issue is related to the ionic cli and not the framework i will be moving this issue over to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#943
