### ISSUE TITLE
platform.ready is not being fired

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6186]
When running on an iOS simulator, platform.ready is not fired. You can test this with the conference app and the nightly build by adding a log:

```
// Call any initial plugins when ready
platform.ready().then(() => {
  console.log("Platform ready?");
  StatusBar.styleDefault();
});
```

Big thanks to @tlancina for debugging this with me. We found that zone needs to be passed in the prepareReady function for the platform:

```
p.prepareReady = function(zone) {
  this._zone = zone;
      
  ...
};
```

https://github.com/driftyco/ionic/blob/2.0/ionic/platform/registry.ts#L171

**Comment by adamdbradley** [comment]
Awesome, thanks for debugging this!
