### ISSUE TITLE
Feature request: Add support for Material Design's elevation property (aka shadows)

### ISSUE THREAD

**Issue by watzon** [driftyco/ionic#6187]
It would be nice if Ionic 2 supported adding an elevation property to certain elements like you can when building native Android apps in Java. Material design isn't really Material design without elevation.

**Comment by adamdbradley** [comment]
Absolutely, I think this is a great idea. @iDev0urer so we don't over look anything, would you be able to provide a list components that could get the `raised` attribute?

**Comment by iDev0urer** [comment]
The big ones right off the top of my head are the Floating Action Button,
Toolbar, and Cards. However in actual Material Design most any element
should be able to have elevation. There is a spec sheet somewhere showing
the elevation in *dp* that each element should have though. Thanks!

**Comment by jgw96** [comment]
Here is the official spec sheet on elevation for material design: https://www.google.com/design/spec/what-is-material/elevation-shadows.html. There is an awesome graphic on there that shows all the elements that can have elevation.

**Comment by iDev0urer** [comment]
@jgw96 That's the one! :+1:

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#28
