### ISSUE TITLE
Calling IonicApp.getComponent(id) in functions 'onPageLoaded', 'onPageWillEnter', 'onPageWillEnter' will return undefined

### ISSUE THREAD

**Issue by jashhk** [driftyco/ionic#6188]
#### Short description of the problem:
Functions 'onPageLoaded', 'onPageWillEnter', 'onPageWillEnter' of 'Page' fired before all IonicApp.register(id, component) called. Therefore calling IonicApp.getComponent(id) in these functions returns **undefined**. The component is not dynamically generated by user-defined scripts and is always **visible**.

#### What behavior are you expecting?
IonicApp.getComponent(id) should return the instance of the component.

**Steps to reproduce:**
1. Define 'id' for a component
2. Import IonicApp and inject as 'app' in constructor
3. Call app.getComponent(id) in functions 'onPageLoaded', 'onPageWillEnter', 'onPageWillEnter'
4. (Optional) Add a line ```console.log(Object.keys(this._cmps), id, this._cmps[id])``` in IonicApp.prototype.register (after '/ionic-angular/components/app/app.js:104')

```
import { Page, IonicApp } from 'ionic-angular/index';

@Page({
  template: `
  <ion-navbar *navbar>
    <ion-title>Tabs</ion-title>
  </ion-navbar>
  <ion-content>
    <ion-infinite-scroll id="list-scroll" (infinite)="doInfinite($event)">
      <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>
  </ion-content>`
})
export class HomePage {
  constructor(
    private app: IonicApp
  ) {
  }

  onPageLoaded() {
    console.log('onPageLoaded', this.app.getComponent('list-scroll'));
  }

  onPageWillEnter() {
    console.log('onPageWillEnter', this.app.getComponent('list-scroll'));
  }

  onPageDidEnter() {
    console.log('onPageDidEnter', this.app.getComponent('list-scroll'));
  }
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.0.0-beta.4

#### Plunker that shows an example of your issue

http://plnkr.co/edit/FOiWZg6LjiCe3PWcgZwb?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 7 SP1
Node Version: v5.5.0

**Comment by adamdbradley** [comment]
Thank you for the report, it should be fixed as of this commit: https://github.com/driftyco/ionic/commit/b282e90e2cbb74559aab79eee8443a4d7c85502a

Also, I updated the infinite scroll tests to show how you can use `@ViewChild` to better get a reference to a child component: https://github.com/driftyco/ionic/commit/79dd0df90b6ff08720e89d56dcbde9a8baa56507

Thanks!
