### ISSUE TITLE
Error - There was a problem while parsing the package in android + ionic2 + Angular2

### ISSUE THREAD

**Issue by kanchansingh1123** [driftyco/ionic#6191]
Hello,

I have created an fresh app by following http://ionicframework.com/docs/v2/getting-started/installation and generated an apk file using the following command -

1. ionic platform add android
2. ionic build --release android

While trying to install the APK in mobile it give the following error - 
**"there was a problem while parsing the package in android"**

I tried to test with 4.x, 5.x and 6.x Android version.

Is this known issue with Ionic2 + Angular2 ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#941
