### ISSUE TITLE
Excess padding between searchbar and tabs

### ISSUE THREAD

**Issue by codergeek121** [driftyco/ionic#6194]
#### Short description of the problem:
There's padding between  `ion-searchbar` and `ion-tabs` with `tabbarPlacement="top"` on native ios. I took a screenshot and marked the corresponding spot with a red rectangle. When serving and testing in the browser (Chrome, Safari), there's no visible padding!

![ios-padding](https://cloud.githubusercontent.com/assets/4910785/14582689/a60a75fa-040c-11e6-9159-f830757dc9bd.PNG)

#### What behavior are you expecting?
I expect the following in a screenshot.

![expected_result](https://cloud.githubusercontent.com/assets/4910785/14582714/09f0ea54-040d-11e6-80d3-c5e63d95f877.PNG)

**Steps to reproduce:**
1. Start an ionic -v2 --ts tabs project 
2. Insert the code snippet below in e.g. page2 template
3. run in ios emulator or native ios device

```
<ion-content class="page2">
  <ion-searchbar [hideCancelButton]="true" placeholder="test"></ion-searchbar>
  <ion-tabs tabbarPlacement="top" preloadTabs="true" tabbarLayout="icon-hide">
    <ion-tab tabTitle="Favoriten" class="selectorTab" ></ion-tab>
    <ion-tab tabTitle="Themen"></ion-tab>
    <ion-tab tabTitle="Neueste"></ion-tab>
  </ion-tabs>
</ion-content>
```

**Other information:**
Opened the native Webview Debugger in Safari. And found the following, when selecting `<ion-navbar-section>`:
![debugger_ios 2](https://cloud.githubusercontent.com/assets/4910785/14582826/b9e6b96e-040f-11e6-8277-7e95719913a7.PNG)

Maybe the root of the problem is to use `ion-tabs` in a `@Page`? 

**Which Ionic Version?**  Ionic 2 Typescript

**My `ionic info` output:
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002 

It looks like a bug to me, so I'm trying to look into it. But maybe someone got more information, ideas or a direction to look for :)

**Comment by dylanvdmerwe** [comment]
I think this is something @brandyscarney has already looked at?

**Comment by RAMDdFLEET** [comment]
Temporary fix, 
For now, alter the default padding using Sass Variables. It will be fixed in the upcoming releases.

**Comment by brandyscarney** [comment]
So this issue is because the `ion-tabs` element adds its own `navbar` and `content` sections. `ion-tabs` really doesn't/shouldn't work being inside of an `ion-content`. It is on our roadmap to add a [stand alone tabbar component](https://github.com/driftyco/ionic/issues/5022) that doesn't require navbar/content sections at all, but until then you could use a [Segment](http://ionicframework.com/docs/v2/api/components/segment/Segment/) instead.

Sorry I don't have better news! Going to close this and fix as part of https://github.com/driftyco/ionic/issues/5022.
