### ISSUE TITLE
Ionic 2 - Touch events are very buggy

### ISSUE THREAD

**Issue by speciose** [driftyco/ionic#6195]
I was playing with Ionic 2 for the first time and noticed a very buggy touch events on my Samsung Galaxy Tab E (android 4.4.4). I can't properly navigate through example app (I've tried 3 examples and all have the same issue).
So to click a link I need to tap screen from 3 to 6 times.. It shouldn't be like that.

I've never played with Ionic 1 or Cordova so I will try next day to know if it's Ionic 2 specific or Cordova.

I would say that I'm using Ubuntu 14 64bit and Node v5.10.1 for build process but I don't get any errors

**Comment by dylanvdmerwe** [comment]
Have you installed the Crosswalk plugin? Any code to help reproduce this?

**Comment by speciose** [comment]
Thanks for reply! I'm using ionic-conference-app example. And after I've installed Crosswalk plugin using this command:
`ionic plugin add cordova-plugin-crosswalk-webview` everything become much better! The app is a bit slower than I expected but anyway, very usable. Now I can even see touch bubbles from material design. Definitely will use Ionic 2 further.

But why it doesn't work properly without Crosswalk? Is there any hint that would help me investigate that problem?

**Comment by manucorporat** [comment]
@speciose I may know how to improve it, can you submit a codepen?

**Comment by manucorporat** [comment]
this may help: https://github.com/driftyco/ionic/pull/6205

**Comment by adamdbradley** [comment]
This should be fixed in the next release from this PR: https://github.com/driftyco/ionic/pull/6205
