### ISSUE TITLE
App Level Lifecycle Events

### ISSUE THREAD

**Issue by SP1966** [driftyco/ionic#6196]
Currently I can find no way to ensure that app startup logic is run prior to the rootPage being loaded into view. If for example you want to check if a backend server has updates that need to be synced prior to the user utilizing your app. 

A second, but similar issue is onPageWillEnter, this does not wait for promises to resolve before loading the template in view. In an app I'm currently working on the data being fetched from the local Sqlite db flashes into the view a split second after it loads which looks terrible. It's also fast enough that trying to use a loading dialog is equally bad as it flashes in, then immediately out of view. 

#### What behavior are you expecting?
Effectively what I'm looking for is much like the old resolve method on Ionic 1 UI-router, a manner in which logic can be executed prior to app being usable, or page coming into view. Basically, I'm wondering if bringing back the resolve method in some form, both in the NavController and at the App level can be done?

Ionic 2

Currently on Beta.4 if that matters.

Also of note on the second issue, with Beta.3 the app was able to retrieve the data from Sqlite in time to be placed in the template prior to it coming into view. Something with Beta.4 has changed causing the data to be delayed in some manner. I noticed this immediately upon updating to Beta.4 with no changes to the logic in my app.

**Comment by jgw96** [comment]
Hello @SP1966 ! Thanks for opening an issue with us! Are you still having this issue with beta.6?

**Comment by lricoy** [comment]
@jgw96 I think that even if the onPageWillEnter() is back with the normal behavior, I would still appreciate some lifecycle hooks on the @App and I think this would solve the use case for @SP1966 as well, or at least the first issue.

Something like appDidLaunch() to load some initial data would be preferable than some loading logic inside my fist @Page. IMHO

**Comment by SP1966** [comment]
@jgw96 I'm on beta.6 now and the second issue is resolved thank you!

@lricoy I'm in agreement with you on the first issue, there can be cases where you want to run some code (updates and/or syncing data with a back end) prior to the user using the app. Being able to do so before the user is involved with the app makes more sense than having them begin using it, then prompting them that an update/sync is needed.

**Comment by jgw96** [comment]
Hey guys! Would you all mind opening a separate issue for the lifecycle events suggestion? As it seems that the core issue ( the flashing on loading of the data) is fixed in the latest version of Ionic 2, i am going to close this issue for now. Thanks for using Ionic!
