### ISSUE TITLE
iOS screen stuck halfway during modal/page transition

### ISSUE THREAD

**Issue by apparition47** [driftyco/ionic#6197]
#### Short description of the problem:
Screen gets stuck half-way only using the iOS CSS modal/page transitions. 

![img](http://puu.sh/okXw5/d86a9a0286.png)

#### What behavior are you expecting?
Screen returns to normal on iOS like Android. I seem to only get this on an actual iOS device.

**Steps to reproduce:**
I modelled my setup in the plunkr below but it goes as follows:
```
// modal is trigged from my TabsPage, then when it's dismissed, present MysteryPage
let modal = Modal.create(IncomingPage);
modal.onDismiss(d => {
	// dismissed with this.viewCtrl.dismiss();

    if (!d) return;
    this.nav.push(MysteryPage, d, {animate: false});
});
this.nav.present(modal);

// in MysteryPage, dismiss by doing this:
this.nav.pop(); // after this, we have the half-screen issue
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

The MD CSS animations seem to be okay so the following fixes my issue:
```
@App({
    template: '<ion-nav [root]="rootPage"></ion-nav>',
    providers: [Service1, Service2],
    config: { // http://ionicframework.com/docs/v2/api/config/Config/
        tabSubPages: true,
        pageTransition: 'md-transition', // <--
        modalEnter: 'modal-md-slide-in',  // <--
        modalLeave: 'modal-md-slide-out'  // <--
    }
})

```

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

Note: I'm unable to reproduce my setup correctly in the plunker as everything seems to work properly in there.

http://plnkr.co/edit/Vl7FlHxqBTL3MYpcXaUp?p=preview

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by RAMDdFLEET** [comment]
1 - create the class that will control your modal and define add its template:

import {Modal, NavController, ViewController} from 'ionic-angular';
// other things can go here
@Page({
  template: `
  <ion-content padding>
    <h2>I'm a modal!</h2>
    <button (click)="close()">Close</button>
  </ion-content>`
})
class MyModal {
  constructor(viewCtrl: ViewController) {
    this.viewCtrl = viewCtrl;
  }
  
  close() {
    this.viewCtrl.dismiss();
  }
}

2 -  add the code that will open your Modal:

import {Modal, NavController} from 'ionic/ionic'
class MyPage {
  constructor(nav: NavController){
    this.nav = nav;
  }
  showModal() {
    let modal = Modal.create(MyModal);
    this.nav.present(modal)
  }
}
Just try out this simple stuff. This shouldn't suck in iOS!!

**Comment by jgw96** [comment]
Hello! Would you mind trying ionic nightly? I cannot seem to reproduce this on my ios device (running ios 9.3.1) with my test app that is using ionic nightly. To test this run `npm rm ionic-angular` and then `npm install ionic-angular@nightly`. Thanks!

**Comment by apparition47** [comment]
@jgw96 I just tried today's nightly with the associated deps but I'm still having the same issue. I can't quite figure it out; there may be something more in my app's controller or view that i'm not replicating properly in the plunkr (the plunkr shows the basic flow of what I'm doing but is missing all the native Cordova plugins and HTML5 media I have going on). I'll see if I can try and isolate the issue a bit more.

Thanks for your help.

**Comment by apparition47** [comment]
Just to follow up, this was caused by my use of using RxJS subscriptions in my controllers and not unsubscribing after the controllers are destroyed. I moved to the Ionic Events pubsub system and I properly subscribe/unsubscribe after I'm done with my modal views.

**Comment by Artfloriani** [comment]
I am still having this issue and trying to remove all the events as suggested by @apparition47 did not work. Any words on this issue?

**Comment by nickkenens** [comment]
@apparition47 So the issue had to do with .subscribe() within your controller? Doesn't RxJS automatically unsubscribe from Observables when there are no longer any values that will come in?
