### ISSUE TITLE
Update Angular to 2.0.0-beta.14 

### ISSUE THREAD

**Issue by ansarizafar** [driftyco/ionic#6200]
Angular 2.0.0-beta.14 has a very important bug fix

select: support objects as select values (74e2bd7), closes #4843 #7842

This bug has halted my ionic project Please update Angular dependency ASAP.

**Comment by dylanvdmerwe** [comment]
This has been done in [beta 5](https://github.com/driftyco/ionic/commit/6189b3f39e479231999085c47d8f1fb27c31051e).

**Comment by ansarizafar** [comment]
Could you please tell us ETA for beta 5 release.

**Comment by ZiFFeL1992** [comment]
You can use the nightly version of ionic-angular:

```
npm install ionic-angular@nightly --save
npm install angular2@2.0.0-beta.15 --save
```

**Comment by adamdbradley** [comment]
You can use the nightly version: https://github.com/driftyco/ionic/tree/2.0/scripts#installing-nightly-version

Thanks

**Comment by ansarizafar** [comment]
@adamdbradley I am using ionic2 nighty. Here is my ion-select code.

```
 <ion-select ngControl="areaName"  >
           <ion-option *ngFor="#area of _areas" [ngValue]="area._id">{{area.name}}</ion-option>
                   </ion-select>
```
ion-option is  setting area._name as value for selected option instead of area._id Where as If I use html select/option with the same code then I get area._id as value for the selected option correctly. Is there any fix for this issue?

**Comment by iignatov** [comment]
@ansarizafar As @dylanvdmerwe mentioned, the master is already upgraded to Angular 2.0.0-beta.15.

Could you please close this issue now?

If you don't want to wait for `beta.5` and use Angular 2.0.0-beta.14 now, you could update your project's `package.json` with the changes in [the following commit](https://github.com/driftyco/ionic/commit/19f75be88690520ab8a43369c7063d26dd8ef142) and run `npm install` under your project's folder.

**Comment by ansarizafar** [comment]
@iignatov I have updated my project with the instructions mentioned by @ZiFFeL1992. After update I am now facing above mentioned issue. I have opened a new issue [#6212](https://github.com/driftyco/ionic/issues/6212) and closing this issue.
