### ISSUE TITLE
v2 list-ios-activated-background-color doesnt always apply

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#6201]
#### Short description of the problem:

Using list-ios-activated-background-color used to consistently work

Now, on some pages, the colour does not apply when an item in a list is clicked (activated) 

This has changed in the recent beta

ALWAYS works on lists in a sidemenu. 
Sometimes works on a list in a page. [after about 2-3 iterations of clicking on list going to page with no colour change, the item does change e.g. on the 4th, this is not consistent though]

Is there an activation state being held somewhere that is not being set correctly? 

This is on chrome / mac / web

#### What behavior are you expecting?

The colour of the item to change on activation (click)

#### Code 
```
    <ion-list>
        <button (click)="goToCityDetail(city.city_code)" ion-item *ngFor="#city of cities">
            <h2>{{city.city_name_en}}</h2>
            <p>
                {{city.city_code}}
            </p>
        </button>
    </ion-list>
```
and in app.variables.scss

```
$list-ios-activated-background-color : rgba(236, 255, 231, 0.5);
$list-md-activated-background-color: rgba(236, 255, 231, 0.5);
```

**Which Ionic Version?** 1.x or 2.x

2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by RAMDdFLEET** [comment]
When you try as mentioned by you, there might be some delay that is why there is inconsistency. Better call a function on a button click and change the color of the activated list. It will work for sure immediately. When you call a function to change the color, it is of higher importance and it will be executed for sure!

code

    <ion-content class="has-header">
        <ion-list>
        <button (click)="goToCityDetail(city.city_code)" ion-item *ngFor="#city of cities">
            <h2>{{city.city_name_en}}</h2>
            <p>
                {{city.city_code}}
            </p>
        </button>
    </ion-list> </ion-content>
export class HomePage {
  isActive: boolean;
  myColor: string;
  constructor(private nav: NavController) {
		this.reset();
	}
	actify() {
	  this.isActive = true;
	  this.myColor = 'primary';
	}
	reset() {s
	  this.isActive = false;
	  this.myColor1 = 'custom1'; #some custom color
	}
	goToCityDetail(***) {
	  // reset everything to default color here 
         // so previously clicked button will be set to default color
        //then call actify() to change the color of the current active
	}
}

Hope you get the idea!

**Comment by alexbainbridge** [comment]
Humm, yes, thank you

Does seem though that this should be handled by the framework, especially as it sometimes works (and prior to this beta, always worked) 

Also, the activated colour should happen on click down, the navigation to the new page only starts on click release, so if you hold a long press, there (probably) are no other major UI processing tasks at that moment

**Comment by alexbainbridge** [comment]
This is a possible duplicate of https://github.com/driftyco/ionic/issues/6192  

Sorry if so

**Comment by manucorporat** [comment]
@alexbainbridge my PR fixes it: https://github.com/driftyco/ionic/pull/6205

**Comment by alexbainbridge** [comment]
I just checked. Yes that does it. 
Hope it makes the main codebase soon.... 
Thanks!

**Comment by alexbainbridge** [comment]
Incidentally, now I have a solution, I have worked out why the intermittent behaviour happened originally

If you click on the h2 or the p (see code initially provided) the item would not activate. However if you clicked out of that, but within the button item - it did activate.

**Comment by manucorporat** [comment]
@alexbainbridge yes, I had the same problem in my app, that's how I found the fix

**Comment by adamdbradley** [comment]
This should be fixed in the next release from this PR: https://github.com/driftyco/ionic/pull/6205 Thanks
