### ISSUE TITLE
bug: Problem when changing button's color and style

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic#6202]
#### Short description of the problem:
When setting the color and style attributes of the button programmatically, the changes are not applied/visualized as expected.

#### What behavior are you expecting?
The changes to color and style attributes should be visualized as they are set in the code.

**Steps to reproduce:**
1. Open http://plnkr.co/edit/2fViim?p=preview
2. Click the button **[Unify all buttons]**.
3. Observe that not all buttons are set to the default state.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/2fViim?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by RAMDdFLEET** [comment]
Quit your Ionic CLI and run again. Or restart the browser. It must be due to invalid reassignment of values to variables that alter the color of the buttons during Stack refresh.

**Comment by Frightie** [comment]
If you create a dummy element, say a `<h1>`, attach a class to it and change a property via CSS. Do the changes apply?

**Comment by Frightie** [comment]
Also, if you attach a class to the button, sometihng like `button-assertive` do the changes apply?

**Comment by iignatov** [comment]
@RAMDdFLEET @Frightie Maybe I didn't write a good/clear description - the problem is when both color and style attributes are updated at once. You can observe it in [this plunker demo](http://plnkr.co/edit/2fViim?p=preview) following the repro-steps. Thank you for the suggestions, but I already [implemented a fix](https://github.com/driftyco/ionic/pull/6203) that should resolve the issue.

**Comment by brandyscarney** [comment]
Thank you @iignatov for the PR! This will be in the beta.7 release. :smile:

**Comment by iignatov** [comment]
@brandyscarney Great, thanks for the update!
