### ISSUE TITLE
How add img in a app ionic 2?

### ISSUE THREAD

**Issue by villander** [driftyco/ionic#6206]
I add a img into `app/img/myImage.png`  but its not working. If you create a folder `img` into `build/` the app destroys it

I'm using the version `2.0.0-beta.25`

**Comment by RAMDdFLEET** [comment]
You are not supposed to place image inside build directory and use it. It is for building purpose. Every time you compile and build executable, it will refreshed according to the changes that you make in the app directory. Build directory is for internal purpose. You are supposed to use the resources directory. Put your images under resources directory and reference in your code!

**Comment by villander** [comment]
Thanks @RAMDdFLEET

**Comment by villander** [comment]
But i already found, in (Ionic conference app)[https://github.com/driftyco/ionic-conference-app/tree/master/www] they use a img folder into `www`

**Comment by dylanvdmerwe** [comment]
I put my images in www/img folder.

**Comment by villander** [comment]
I too start now @dylanvdmerwe 😊

**Comment by jspenc72** [comment]
This is still an issue.

**Comment by jspenc72** [comment]
Either a www/img folder should be generated to set a trivial standard or a grunt task should be added to copy any images from the app directory.

**Comment by bhavinwebdesk** [comment]
can we access application icon (that is auto generated in resources/android) and display it is img tag or we have to copy it in www/img directory?
