### ISSUE TITLE
height and width of a collection-repeat are 0 in IE and Edge browser.

### ISSUE THREAD

**Issue by kceiw** [driftyco/ionic#6207]
I asked a question in stackoverflow http://stackoverflow.com/questions/36672708/collection-repeat-creates-an-element-with-height0-and-width0
and realized this may be a bug.

Please look at the code to repro this issue here. I tried with Ionic v 1.2 first.
http://play.ionic.io/app/a80f16cd6ade

In Edge and IE, height and width are 0. 
![edge](https://cloud.githubusercontent.com/assets/1449194/14588426/711ac7e2-047e-11e6-94ce-581ecb37ebb1.png)

in Firefox, height and width are non-zero
![firefox](https://cloud.githubusercontent.com/assets/1449194/14588428/86eb2c38-047e-11e6-9a68-28805c44be12.png)

Also note that in all three browsers, left and top are zero and position is absolute. The list item is positioned in wrong place and covered by other elements.

**Comment by jgw96** [comment]
@kceiw Hello! Thanks for opening an issue with us! (: Are you still having this issue with version 1.3.0?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by kceiw** [comment]
Yes. It's still reproduced with version 1.3.0. I still use http://play.ionic.io/app/a80f16cd6ade and point to 1.3.0 ionic framework.

**Comment by incorelabs** [comment]
This is still an issue with IE and Edge, the workaround I found was to,
~~~~
.collection-repeat-container ion-item.item.item-complex {
    height: auto !important;
    width: 100% !important;
    border-right: none;
    border-bottom: none;
}
~~~~

This workaround will probably work in all browsers. But if you want to be specific IE and EDGE, you could probably browser detect it. Although people do say browser detection is a bad habit.
