### ISSUE TITLE
docs: One of your demos is broken

### ISSUE THREAD

**Issue by cramirez451** [driftyco/ionic#6210]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>The demo on the following page: http://codepen.io/ionic/pen/rxysG doesn't seem to be working. It says its supposed to be a frosted glass effect but I don't see that. I'm on a Mac OS 10.11.4 using Chrome as my browser Version 49.0.2623.112 (64-bit)</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
It looks like it's working for me. 

http://codepen.io/mhartington/pen/yOjrrw

Might just be the default opacity is a bit low, so it's hard to see. 
I copied the css and just put it inline and bump the opacity up a bit. Looks fine.
