### ISSUE TITLE
ion-option is not setting correct value.

### ISSUE THREAD

**Issue by ansarizafar** [driftyco/ionic#6212]
I am using ionic2 nighty. Here is my ion-select code.

```
 <ion-select ngControl="areaName"  >
           <ion-option *ngFor="#area of _areas" [ngValue]="area._id">{{area.name}}</ion-option>
                   </ion-select>
```
ion-option is  setting area.name as value for selected option instead of area._id Where as If I use html select/option with the same code then I get area._id as value for the selected option correctly. Is there any fix for this issue?

**Comment by ansarizafar** [comment]
@adamdbradley any update? Is there any solution?

**Comment by jgw96** [comment]
@ansarizafar Hello, thanks for opening an issue with us! Would you be able to provide a codepen or plunker that demonstrates your issue? Here is a template you can use to make your plunker: http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**Comment by ansarizafar** [comment]
@jgw96 I think the template is for ionic1, I am using ionic2 nighty. The problem appears if you use object array to populate ion-option

**Comment by jgw96** [comment]
@ansarizafar ahh sorry about that (: here is the correct plunker: http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Comment by ansarizafar** [comment]
@jgw96 Check this plunker [http://plnkr.co/edit/ETql1bZueMY9xMKKy8a4?p=preview](http://plnkr.co/edit/ETql1bZueMY9xMKKy8a4?p=preview)

**Comment by jgw96** [comment]
@ansarizafar Hey! So here is a link to a plunker where i modified your code just a touch to work: http://plnkr.co/edit/TVY0C9TRrtKe02b2iqQf?p=preview as you will see i just changed from `[ngValue]='color._id'` to `[value]='color._id'` . To bind to the value of an input in angular 2 you just use the native value property of an input. Hope this helps you!
