### ISSUE TITLE
Storage.get method is returning promise instead of actual value.

### ISSUE THREAD

**Issue by imsingh** [driftyco/ionic#6213]
Storage.get method is returning promise Object instead of actual Value.

![storageerror](https://cloud.githubusercontent.com/assets/2650146/14601454/ab0695f6-057f-11e6-8f40-fa4f56032600.png)

**Comment by ZiFFeL1992** [comment]
Yes, as stated in the docs get returns a promise:

https://ionicframework.com/docs/v2/api/platform/storage/SqlStorage/#get

**Comment by imsingh** [comment]
@ZiFFeL1992  Thanks. Quite embarrassed for not reading docs carefully :laughing:
