### ISSUE TITLE
Select element doesn't work on windows phone

### ISSUE THREAD

**Issue by diderson** [driftyco/ionic#6215]
the select element is not working on windows 8... I am creating a mobile web app that will be access via a specific link and most of the users will be using windows mobile phone.
please any assistance on this will much more appreciated.

```html
                          <select ng-model="level">
                                <option value="1">1</option>
                                <option value="2" selected>2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                            </select>
```

**Comment by jgw96** [comment]
Hello @diderson ! Thanks for opening an issue with us! Am i correct in thinking that this is going to be deployed to the web, and most of your users will be accessing it from IE on windows phone 8?

**Comment by jgw96** [comment]
Hello! As we are not supporting windows phone 8 (or IE) i have decided to close this issue. Thanks for using Ionic!
