### ISSUE TITLE
Swiper + angular-google-maps = fail

### ISSUE THREAD

**Issue by jonathanherdt** [driftyco/ionic#6216]
When combining the new slides (aka Swiper) and angular-google-maps, dragging is not possible inside of Google Maps and leads to grey space instead.

This even happens when I disable swiping via .lockSwipes()

What I also unsuccessfully tried are these attributes:

```
onlyExternal: true
touchMoveStopPropagation: false
preventClicksPropagation: false
```

Finally, I found that using google.maps.event.trigger(MapInstance, 'resize') like suggested here does not work either.

This is my code:

```
<ion-slides options="swiper">
  <ion-slide-page>
    <ui-gmap-google-map control="map.control" center='map.center' zoom='map.zoom'
    </ui-gmap-google-map>
  </ion-slide-page>
</ion-slides>
```

and in my .js:

```
angular.module('ionicApp', ['ionic', 'uiGmapgoogle-maps'])
.controller('MainCtrl', function($scope) {
  $scope.swiper = {
    onInit: function(swiper){
      swiper.lockSwipes();
    }
  };
  $scope.map = { control:{}, center: { latitude: 45, longitude: -73 }, zoom: 8 };
});
```

Here's a plunkr that shows my issue: http://plnkr.co/edit/JiAw0oXRxLGgL3SrE6PK?p=preview2
Here's a plunkr that shows that the issue is not present with vanilla Swiper: http://plnkr.co/edit/IfoQ3G?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by barocsi** [comment]
+1 any solutions?

**Comment by jonathanherdt** [comment]
Yup, two so far:

1. You can switch back to the old slides
2. You can use <div>s instead of <ion-slide-page>s

Both are not ideal but the second one was good enough for me.
