### ISSUE TITLE
Feat: new pages on Android don't cover tabs if tabs are on bottom

### ISSUE THREAD

**Issue by jalef** [driftyco/ionic#6218]
Hello.
I try to open an ionic page from another page that is root to an ionic tab.
When it runs to ios, it opens normally and the tab navigator is visible and clickable
When it runs to android, the new page has no bottom margin and overlays the tab navigator.

Is this the right way to change the tab's page?
Why this is not consistent?

Which Ionic Version?
2.0.0-beta.23

#### Plunker that shows an example of your issue

http://plnkr.co/edit/QjGNFeJtCBdSgMegTG9H?p=info

this is an image that displays the problem and the settings that reproduce the problem 

![2016-04-18 17_28_37-ionic test environment ver_ 2 0 0-beta 3 - plunker](https://cloud.githubusercontent.com/assets/15978222/14608454/735541ca-058e-11e6-9790-4f948dfd7c3e.png)

Run ionic info from terminal/cmd prompt: 
Cordova CLI: 5.4.1
Gulp version: CLI version 3.9.0
Gulp local: Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v4.2.4

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! It seems as if your plunker may have been changed or deleted? Would you mind making a new one that demonstrates this issue? Thanks!

**Comment by jalef** [comment]
Hello
I removed the git link tags and it works, please try it out

Thanks

**Comment by jgw96** [comment]
Hello! Thanks, so after reading your issue again i think i understand what might be going on. When you run your app in android the tabs should be at the top of the view. Are they still at the bottom for you?

**Comment by jalef** [comment]
Yes, they are in the bottom, but accidentally this is my use case. 
I have updated the plunker by configuring the tabbar placement

**Comment by jgw96** [comment]
@jalef ahh yes, so with the android transitions which fade up from the bottom just like native they are going to cover your tabs on the bottom as it fades in from the bottom of the viewport. I did some testing with a native android app which has tabs at the bottom (google plus) and it looks like there pages also have the same behavior and cover the tabs when opened. But, for your use case you would like the pages to animate up from above your tabs, not over them correct?

**Comment by jalef** [comment]
Hello again
I want the tabs to be always visible so that the user can navigate to a different tab even when inside a child tab page. A better example in a native app using bottom tabs is instagram since child pages do not go full screen like on g+

**Comment by jgw96** [comment]
@jalef alright, thanks for the info! I'll change this to a feature request then so that the team can start discussing adding it. Thanks!

**Comment by jgw96** [comment]
Hello @jalef ! Sorry for the delay on this! So since we last discussed this issue a tabSubPages option has been added to config that allows tabs to still show even when a new page is navigated too. Simply set it to false and the tabs will always show. [Here](http://ionicframework.com/docs/v2/api/config/Config/ ) is a link to the docs for config if you want to check out all the options we have. Thanks for using Ionic, and as i said above sorry for the delay on this!
