### ISSUE TITLE
 Noticeable delay in transition while push and pop operation of NavController even for lighter contents

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6219]
**Ionic 2**

platform: android

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So i dont seem to have any delay's with navigation in Ionic 2. Would you mind giving our Ionic Conference App a try:https://github.com/driftyco/ionic-conference-app and seeing if you spot any lag with it? Also, if you could create a codepen or plunker (there is a link to a v2 plunker template in the issue template) that demonstrates this lag that would be great. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by AmitMY** [comment]
Hi @jgw96 ,
I have this problem on some pages, which is very strange.
One page I am experiencing this on only has a list with 20 items, (and a search, refresh, and load more) but seem to take 1-2 seconds (yes, seconds) before the transition animation starts after pressing the button.

This is more noticeable on android than iOS.
