### ISSUE TITLE
Unused space in bottom of toolbar containing segment button

### ISSUE THREAD

**Issue by dheeran1** [driftyco/ionic#6225]
**Ionic 2**

Platform: android

Expected: heights of segment button and toolbar must be same

![capture](https://cloud.githubusercontent.com/assets/15922996/14629099/6bf9ebfe-0621-11e6-8fa6-1f1e62cb54d2.PNG)

**Comment by jgw96** [comment]
Hey @dheeran1! So if you want the desired ui your looking for i would use tabs.
![screen shot 2016-04-19 at 2 23 56 am](https://cloud.githubusercontent.com/assets/8823093/14630833/cfb0a012-05d5-11e6-92ef-c3036a6bedef.png)

As you can see from my screenshot our tabs line up with the bottom of the toolbar. Our segment component is not meant to line up with the bottom of the toolbar but instead float above it. You can see how segments would look in our Ionic conference app (https://github.com/driftyco/ionic-conference-app). As i believe this should fix your issue i will be closing this issue for now, but will happily reopen if needed! Thanks!

**Comment by dheeran1** [comment]
Tabs can't be used in my case because, for ios it has different layout than segment for ios.

**Comment by Rattone** [comment]
If you remove the wrapper "ion-toolbar", segment looks perfect on Android but on iOS it's a crap!

**Comment by gabriellacerda** [comment]
There is no solution here, only a reference to a code that doens't make any sense to the question.

Here comes the Solution:

This example assumes that you created 2 pages, if not create now this pages :)

Place TabBar inside your ```ion-content```

file: home.html
```
<ion-content>
  <ion-tabs color="primary" tabsHighlight="true" tabsPlacement="top">
    <ion-tab [root]="tab1Root" tabTitle="About"></ion-tab>
    <ion-tab [root]="tab2Root" tabTitle="Other"></ion-tab>
  </ion-tabs>
</ion-content>
```
And place the pages reference on your controller file.
file: home.ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AboutPage } from '../about/about';
import { OtherPage } from '../other/other';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  tab1Root = AboutPage;
  tab2Root = OtherPage;

  constructor(public navCtrl: NavController) {

  }

}

```

Then you're all set!

**Comment by tomferreira** [comment]
You can change default value at file variable.scss to: 

```
$segment-button-md-height 5.5rem;
$segment-button-md-line-height: 5.5rem;
```
