### ISSUE TITLE
bug(tabs): hidden tabs still show page on load

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6226]
#### Short description of the problem:
This issue relates to https://github.com/driftyco/ionic/issues/5768 with the fix implemented by @adamdbradley.

With the following code:
```
<ion-tabs>
    <ion-tab [root]="tab1Root" tabTitle="Prizes" tabIcon="trophy" [show]="competitionRunning"></ion-tab>
    <ion-tab [root]="tab2Root" tabTitle="Info" tabIcon="information-circle"></ion-tab>
    <ion-tab [root]="tab3Root" tabTitle="Gallery" tabIcon="images"></ion-tab>
    <ion-tab [root]="tab4Root" tabTitle="Inbox " tabIcon="chatbubbles"  [tabBadge]="userState.unreadMessageCount" tabBadgeStyle="danger" ></ion-tab>
</ion-tabs>
```

When the screen loads with the variable `competitionRunning` as false, the prizes page (tab1Root) is displayed, although the actual tab is hidden. I assume the tab controller is loading and displaying the first tab even though it has been hidden. 

#### What behavior are you expecting?
When a tab is hidden, it's page should never be displayed.

**Which Ionic Version?**  2.x nightly

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4-201604170622
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by jgw96** [comment]
Ahh good catch! Looking into this now. Thanks!

**Comment by jgw96** [comment]
@dylanvdmerwe would you mind making a quick plunker that shows your code please?

**Comment by dylanvdmerwe** [comment]
@jgw96: http://plnkr.co/edit/RlpoHZJFrs7ZDZClpmfZ?p=preview

Not sure if I referenced the latest nightly versions but the error can be reproduced.

**Comment by jgw96** [comment]
Thanks man! Appreciate it.

**Comment by adamdbradley** [comment]
Fixed, thanks!
