### ISSUE TITLE
bug(input): on forms weird scrolling behaviour

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6229]
Use this code on a device: http://plnkr.co/edit/H8YBlPxzIoONfdNGUFcD?p=preview
#### Short description of the problem:

On iOS, the form jumps around and is not consistent with Android behaviour.

**Issue One**
- Select email address so that the keyboard is displayed.
- Select the text-area and watch the screen jump twice until it settles on where the cursor is. 

**Issue Two**
- Select email address so that the keyboard is displayed. 
- Hold the email address field and drag the form down. 
- Sometimes the entire form disappears as per the screenshot below. 
  ![image1](https://cloud.githubusercontent.com/assets/2852839/14634786/d64fcc10-0623-11e6-9538-54367f14b59d.PNG)

It may be due to the scroll-bounce effect on iOS?
#### What behavior are you expecting?

Needs to be consistent with other platforms. Form input should be smooth and seamless. 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4-201604170622
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.7.0

**Comment by adamdbradley** [comment]
Is this happening on iOS Mobile Safari, or from within Cordova?

**Comment by dylanvdmerwe** [comment]
@adamdbradley From within Cordova on a device. Haven't checked mobile safari or the simulator.

**Comment by jgw96** [comment]
seems to happen on Android too

**Comment by rhuldip** [comment]
Any update on this issue?

**Comment by rodolfojnn** [comment]
I "fix" this issue with the following code in the app.scss:

> .scroll-content {
>   padding-bottom: 0!important;
> }

**Comment by dylanvdmerwe** [comment]
Correct me if I'm wrong, but isn't this sorted in RC4 milestone @adamdbradley ?

**Comment by dylanvdmerwe** [comment]
Should be sorted with RC4.
