### ISSUE TITLE
perf: Test app

### ISSUE THREAD

**Issue by ZeroCoolBCN** [driftyco/ionic#6230]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>ewrwerwerwerwefssdsdfsdfs</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Could you give us little more info about your issue?

**Comment by jgw96** [comment]
Hey, so i am gonna go ahead and close this issue, but feel free to comment back if you have any more info! Thanks again!
