### ISSUE TITLE
bug: icon and swipe to delete interaction

### ISSUE THREAD

**Issue by amachairidis** [driftyco/ionic#6233]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I created this pen where you can see the issue.
The problem is " If I add the class="item-icon-right" I lose the swipe left functionality( it just closes immediately).
I want the functionality of first ion-item but with the looks of the second ion-item.
http://codepen.io/anon/pen/LNrRjP</span>

<span is-issue-template></span>

**Comment by danbucholtz** [comment]
Here is an example of how to do this.

http://codepen.io/danbucholtz/pen/dMqXoz?editors=1010

Thanks,
Dan
