### ISSUE TITLE
Completing javascript code before going into background mode.

### ISSUE THREAD

**Issue by antonfire** [driftyco/ionic#6235]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

I have a post function which posts (a video + a video poster image) / (no video but an image) to AWS S3 via Parse (now AWS hosted parse server) then returns the ULR which is passed into firebase along with any accompanying text for the post (similar to Facebook etc). This functionality works great when in normal use, but if the user hits post and pauses the app by hitting the home button (IOS) to do something else the upload fails. This is rather essential functionality as most users won't wait for an upload to complete or an upload complete dialog before moving out of the app and indeed compared to native apps this looks rather amateur.

#### What behavior are you expecting?

In light of the above I tried to use cordova-background-plugin to allow the javascript to complete on pause, the result is the same, the code fails with no error. I am now thinking that maybe uploading with cordova-file-transfer may allow the app to complete the upload and the javascript in the callback? I'm waiting for Apple to help out on developer tech support for a custom cordova plugin to save base64 to file and return device path to cordoba-file-transfer to do this.

The workflow is: 
1/ Save image / video poster image (Parsefile.save/cordova-file-transfer)
2/ (In case of video) save video (Parsefile.save/cordova-file-transfer)
3/ Post details and text to firebase (JS SDK)

I'm looking for a way to allow this process to complete if the app is paused mid flow.

**Steps to reproduce:**
1. Upload poster image jpeg file
2. Upload video mp4 file
3. Post to firebase with previous 2 URLs.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

Ionic 1.7.11

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/sSFR9jbfTsxgAmrm9hUR?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! As this issue is more of a question and not a bug with the framework i would suggest that you hit up our forum( https://forum.ionicframework.com/ ) or our slack channel (http://ionicworldwide.herokuapp.com/) and the awesome community on there should be able to help you! Thanks for using ionic!

**Comment by antonfire** [comment]
Hi jgw96, is it expected behaviour with ionic that the upload should fail when paused? I wasn't sure if this was a bug or not. 

Thanks Anthony

**Comment by jgw96** [comment]
Hey! So yeah, by default javascript is not gonna run in the background without using a plugin of some kind or a service worker.

**Comment by antonfire** [comment]
Thanks @jgw96 it's quite hard to find any info on this, (how to keep processes going that started in app open mode and continue in background when closed, like an upload), what is a service worker? do you have a link I could read up on to save you explaining? Thanks for your time. Cheers Ant

**Comment by jgw96** [comment]
@antonfire Definitely, no problem at all! So service worker is a new spec that is currently supported in chrome and firefox (i think safari and edge are working on it) that basically allows a javascript thread to continue running even after you close a website or web app using it. Its mainly used for caching for offline progressive web apps. Not sure it would help you with what your trying to do, as its not really built for that. But, still a pretty cool thing to read up on. https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
