### ISSUE TITLE
Enhancement suggestion for lists -sticky headers

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#6236]
This is a suggestion for the headers in the list. It would be great if there was an option for a sticky header. For longer lists with many headers it is great UX design to allow the user to know where they are in the list. This is referring to ionic2.

**Comment by dylanvdmerwe** [comment]
So to enhance [this](http://ionicframework.com/docs/v2/components/#list-headers) and make it stick to the top of the screen?

**Comment by manucorporat** [comment]
This is already possible with `<ion-item-divider sticky>`

**Comment by RezaRahmati** [comment]
This feature is not working on android, I checked it with rc4

`<ion-content>`
`  <ion-item-group *ngFor='let groupedContact of myGroupdContactCollection.groupedContacts'>`
`    <ion-item-divider color="light" text-center sticky>{{groupedContact.groupKey}}</ion-item-divider>`
