### ISSUE TITLE
Button and button-default class wrongly added to toggle

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6237]
#### Short description of the problem:
The button and button-default classes are getting added to the toggle when they shouldn't be.

#### What behavior are you expecting?

**Steps to reproduce:**
1. Pull conf app and update to nightly
2. Serve or run on a device

**Which Ionic Version?** 2.x latest nightly

**Comment by brandyscarney** [comment]
Can also be seen from http://localhost:8000/dist/e2e/toggle/basic/
