### ISSUE TITLE
Virtual Scroll with ion-item-sliding item width inconsistent

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#6239]
#### Short description of the problem:
When using ion-item-sliding instead of ion-item with virtual scroll the width of the items in the list does not fill 100% of the available width.

#### What behavior are you expecting?
list items fill 100% of the available width as they do with ion-item by default.

**Steps to reproduce:**
1. create a simple virtual scroll list with a few items with text of varying length in each item
2. use ion-item and width is 100% of viewport
3. use ion-item-sliding and width is equal to width of the content in each item

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

To fix simply need to add right: 0; property to the app.*.css files. as in code below

```
.virtual-scroll .virtual-position,
.virtual-scroll .virtual-position.item {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  -webkit-transition-duration: 0ms;
  transition-duration: 0ms; }
```
 

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you by chance be able to make a plunker demonstrating this issue?

**Comment by ghenry22** [comment]
Here is a plunker showing the issue.  Notice that the width of the item defaults to the width of the content of the item when using ion-item-sliding.  When using a standard ion-item the width is correct.  with ion-item-sliding the change to css I included above has it render at full width correctly.

http://plnkr.co/edit/FMWbsA2MWYDCmMJOcXQm?p=preview

**Comment by DavidWiesner** [comment]
:+1: adding `ion-item-sliding{width:100%}` work for me

http://plnkr.co/edit/JfTCK8a2TVEHUZyLcd5F?p=preview

**Comment by mpaland** [comment]
Can confirm this. Having <ion-item-sliding *virtualItem="let item" [style.width.%]="100"> as temp workaround.
Thought that approxItemWidth with a default value of 100% should be doing this.

**Comment by wli** [comment]
Looks like I filed a duplicate ticket showing the problem in beta8 in case it's helpful: https://github.com/driftyco/ionic/issues/6911

Here's the beta8 plunkr that shows the same problem: http://plnkr.co/edit/oXf11zC0Aadb02podyCG?p=preview

**Comment by manucorporat** [comment]
@wli @mpaland should be fixed in next release.
https://github.com/driftyco/ionic/commit/efcdd20508e1f35c6e4e27c957907e081e16171b
