### ISSUE TITLE
ios9 keyboard issues

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic#6241]
#### Short description of the problem:
When i click on an input field in my app, I get two unexpected behaviour. 
1. The page becomes blank and only the background image is shown on the page 
2. The keyboard pops up but nothing is seen. see pic that only the Done button and the Back and Next button is shown but the keyboard doesnt show at all. 
 
![screen shot 2016-04-20 at 5 49 55 pm](https://cloud.githubusercontent.com/assets/8816642/14670617/75708a3a-0720-11e6-8895-c3d32bf477c1.png)

#### What behavior are you expecting?
Expecting it to show the keyboard when input in on focus and to close when input focus is lost.

```
config.xml 
<preference name="KeyboardShrinksView" value="false" />
<preference name="KeyboardDisplayRequiresUserAction" value="true" />
<feature name="Keyboard">
      <param name="ios-package" value="IonicKeyboard" onload="true" />
  </feature>

in my app.js 
if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.disableScroll(true);
}

in my view i am using ion-content like this 
<ion-content  class="adj-13" style="padding: 15px; overflow-y:hidden;">
</ion-content>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
**Which Ionic Version?** 1.x or 2.x
1.7.14

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/sSFR9jbfTsxgAmrm9hUR?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175

**Comment by dylanvdmerwe** [comment]
1. Are you able to provide a plunkr to reproduce this behaviour?
2. The keyboard won't be displayed on the emulator. Try on a real device.

**Comment by boyfunky** [comment]
tried on a real device and it works fine so far. Thanks for the suggestion @dylanvdmerwe
