### ISSUE TITLE
feat(ion-sliding-item): Completely swipe item

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6242]
#### Feature Description
Currently there is `<ion-sliding-item>` which can be added around an `<ion-item>` as described [here](http://ionicframework.com/docs/v2/components/#sliding-list).

The idea is for an event to be added onto this item that is fired if the ion-item is scrolled completely away. 

For example, to remove an item completely from the list the user would swipe the item completely off the list. The event would then fire to remove the item from the list. So if I had a list of emails, I don't have to swipe and then press the delete button. I could just completely swipe the ion-item out of the list. 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.4-f23043ed
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by patrickmcd** [comment]
Examples of this would be the defunct Mailbox and current Spark apps, I assume.

Let me piggyback on this one. I'd like to swipe an item completely to either side, yet keep the revealed content. The event would be fired either way, and you'd consume it by removing the item for your use case, while I'd use it to tally a vote.

**Comment by manucorporat** [comment]
@dylanvdmerwe @patrickmcd https://github.com/driftyco/ionic/pull/6686 was merged, available in next release!

**Comment by wli** [comment]
@manucorporat The linked PR seems to add support for swiping the other direction, not completely swiping off. Do you have an example/documentation for how to make it swipe completely off?

**Comment by manucorporat** [comment]
@wli you are right, you can not swipe completely but! you can subscribe to the new (ionSwipe) event, like this:
https://github.com/driftyco/ionic/issues/5073#issuecomment-223768714
^ more documentation will come before next beta is released

Feel free to open a new issue if swiping completely is required for you. and please explain an use case, so we can implement and assign a priority better!

**Comment by wli** [comment]
Use case is so that you can remove items from a list without tapping an extra time. I don't need it urgently since I already implemented it myself, so I'll let someone else chime in if they need it in the framework itself.

**Comment by codeFire97** [comment]
this code does not work for left side, help please
`<ion-item-sliding #item>
        <ion-item >

          <h2>codeFire</h2>
          
                <ion-note item-right  >
                  9:10 AM <ion-icon name="arrow-forward"></ion-icon>
                </ion-note>
                <p>test</p>
                <p>test</p>
                <p>test</p>

              </ion-item>
              <ion-item-options side="right">
                <button dark (click)="buy(item)"><ion-icon class="iconslide" name="cash"></ion-icon>buy</button>
                <button danger (click)="sell(item)"><ion-icon class="iconslide" name="warning"></ion-icon>sell</button>
                <button  (click)="addCart(item)"><ion-icon class="iconslide" name="cart"></ion-icon>add to cart</button>
              </ion-item-options>

              <ion-item-options side="left">
                <button   (click)="unread(item)"><ion-icon  class="iconslide" name="book"></ion-icon>archive</button>
              </ion-item-options>

            </ion-item-sliding>`
