### ISSUE TITLE
Error in Menu's docs

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#6247]
There is an error in the Menu's documentation of Ionic2. The docs say that there are two display modes but three are mentioned. 

![image](https://cloud.githubusercontent.com/assets/3453385/14683355/f54ba5cc-06ef-11e6-81f8-f1b66a1b53e6.png)

**Comment by jgw96** [comment]
@jabas06 Ahh good catch! Since this is an issue with the docs site and not the framework i will be moving this issue over there. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#560
