### ISSUE TITLE
ionic@nightly update related issues

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6248]
#### Short description of the problem:
After installing the `<ion-select>` directive style doesn't work as expected. 

This is how it looks like: [http://i68.tinypic.com/23r8s9w.png](http://i68.tinypic.com/23r8s9w.png)

Notice when I hover of the ion-select it turns blue. In the prior version it doesn't do that, already tried it. 
#### What behavior are you expecting?
It's the one that is shown in ionic v2 docs.

**Steps to reproduce:**
1. npm install ionic-angular@nightly
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
ionic 2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/sSFR9jbfTsxgAmrm9hUR?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
@Bandito11 hey! So yeah we are already aware of this issue and the next nightly release will have this fixed. Sorry about that! This is why there nightly releases and not stable releases (; haha
