### ISSUE TITLE
Touch events not working in Android 4.4.2

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6251]
_From @johnfakeacc on April 9, 2016 23:26_

Hi! I'm starting to test Ionic 2 with the 'tutorial' template.
On my samsung s5 mini touch events are not working (maybe one of 10).

Seems like the same issue from ionic 1?
https://github.com/driftyco/ionic/issues/1729

Thanks for help

_Copied from original issue: driftyco/ionic2-app-base#17_

**Comment by jgw96** [comment]
hello @johnfakeacc ! Would you mind giving us a little more info about this issue? Which touch events are you having issues with? Would you be able to make a plunker that i would be able to test with? Also, what version of android is your s5 mini running? Thanks!

**Comment by vonovak** [comment]
same here with nexus 4, android 5.1.1
simply creating the project from tutorial by `ionic start MyIonic2Project tutorial --v2` and then `ionic run android` runs the app on my device (launchning takes about 7s btw.). 
Every time I tap, there is the 'tap effect' - the grey circle that starts spreading from the point where I tapped the screen. But some of the taps I do (on the buttons and items in the list) do not cause any further action. (do not redirect me to another page).

**Comment by jgw96** [comment]
@vonovak Thanks for the info! Are you getting any errors in your console?

**Comment by vonovak** [comment]
@jgw96 no, no errors. I was trying this out with the "my first list" page from the tutorial template.  For some reason the click event handler doesn't always get fired.

**Comment by jgw96** [comment]
@vonovak would you be able to make a plunker that gives an example of this issue? Is it something that only happens when running your app on the device or does it also happen in chrome too?

**Comment by vonovak** [comment]
I only noticed it on the device. It happens infrequently, like 1 in 20 taps I would say. Wish I could say something more specific, sorry :D

**Comment by jgw96** [comment]
@vonovak No problem! I, unfortunately, cant seem to reproduce this issue on any of my devices: Nexus 6 running Android N dev preview 2, Nexus 7 2013 running Android 6.0.1 and a Moto X 2014 running Android 5.1.1. If anybody else can consistently reproduce this issue feel free to comment! In the meantime, i am going to close this issue. Thanks for using Ionic!

**Comment by doender** [comment]
I can reproduce this issue on an Archos 40C device (Android 4.4.2).
Most touch events (taps) are not working.
