### ISSUE TITLE
bug: The ionic guide deviates from reality at step 5

### ISSUE THREAD

**Issue by chemturion** [driftyco/ionic#6252]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am following your Guide and at step "5. Building out your app", after I put in the following code:

```.controller('TodoCtrl', function($scope) {
  $scope.tasks = [
    { title: 'Collect coins' },
    { title: 'Eat mushrooms' },
    { title: 'Get high enough to grab the flag' },
    { title: 'Find the Princess' }
  ];
});```

The output breaks and renders text-only:

Projects
Todo
{{task.title}}

I believe this is due to the app.js file's ".run" sequence because if I delete this block, the app renders correctly according to the Guide's screenshot.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @chemturion ! Sorry your having this issue. So i went through the guide last night and noticed that there does seem to be a syntax issue. Give me just a few minutes and ill update you with the correct syntax!

**Comment by jgw96** [comment]
Hey @chemturion so i just committed a fix to the docs for this a few minutes ago which should hit the live site soon! So your not waiting on that fix to hit the site though i went ahead and put my working copy of the app that gets built in the guide on github here: https://github.com/jgw96/ionic-todo. Feel free to git clone that and that will give you a working copy of the app that gets built in the guide. Thanks for using ionic!

**Comment by jgw96** [comment]
Also, once the new guide gets published ill update this issue to let you know!

**Comment by jgw96** [comment]
@chemturion hey, my fixes for the site were pushed to live so i will be closing this issue now. Thanks for using ionic!
