### ISSUE TITLE
sass error

### ISSUE THREAD

**Issue by nelsonec87** [driftyco/ionic#6258]
Hi, I installed ionic2 cli `npm install -g ionic@beta` and created a new project `ionic start cutePuppyPics --v2`, following the official website.
then `ionic serve`. I got

`Running 'serve:before' gulp task before serve`
`[23:07:29] Starting 'clean'...`
`[23:07:29] Finished 'clean' after 9.51 ms`
`[23:07:29] Starting 'watch'...`
`[23:07:29] Starting 'sass'...`
`[23:07:29] Starting 'html'...`
`[23:07:29] Starting 'fonts'...`
`[23:07:29] Starting 'scripts'...`
`[23:07:29] Finished 'scripts' after 71 ms`
`node_modules\ionic-angular\components.core.scss`
`Error: Import directives may not be used within control directives or mixins.`
`        on line 34 of node_modules/ionic-angular/components.core.scss`
`>>   @import "fonts/ionicons";`
`   --^`

And the page opens in the browser without css.. if I comment the line 33 (the `if`), it runs ok..

Your system information:
Cordova CLI: 5.3.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.0.0

**Comment by nunoarruda** [comment]
Same here:
<img width="682" alt="screen shot 2016-04-21 at 11 40 53" src="https://cloud.githubusercontent.com/assets/1189149/14696437/fe8a74da-07b5-11e6-8cf3-244644a4f01e.png">

Probably related to https://github.com/sass/libsass/issues/1724. I think you guys just need to update your gulp-sass version.

**Comment by RunningV** [comment]
same as upstair. i found <code>line 34 @import "fonts/ionicons";</code>  is useless. i comment <pre> @import "fonts/ionicons";</pre>,and style is ok.
it seems works but alse comes another error<code>Error: Undefined variable: "$color-contrast".
        on line 88 of node_modules/ionic-angular/components/tabs/tabs.wp.scss
\>\>       color: $color-contrast;
</code>
it likes the ionic-angular has some bug

**Comment by susanlinsfu** [comment]
+1 can't run ionic. Seems like a showstopper.

**Comment by messense** [comment]
same error

**Comment by brandyscarney** [comment]
Hey everyone, sorry you're running into this. Could you run the following commands:

```
npm install gulp-sass@2.2.0
npm install node-sass@3.4.2
```

and then run `npm install` again and let me know if that fixes the error?

**Comment by messense** [comment]
@brandyscarney Yes, it fixes the error.

**Comment by mco67** [comment]
@brandyscarney Problem solve for me too, thx

**Comment by quanghoc** [comment]
Is there a way NOT to download the latest build each time when I do `ionic start`?

I see random errors here and there each day because for some reason, that day has a bad build and `ionic start` would pick up and fill the entire project with bugs.

It's better if `ionic start` can point to a proven and stable build.

**Comment by LastStarfi9hter** [comment]
Above fix has not resolved the issue for me :(

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175

**Comment by quanghoc** [comment]
Do you have a working Ionic 2 project? Just replace the folder `ionic-gulp-sass-build`.

But my point is that this will happen again with `ionic start` on a random day. It's systematic.

**Comment by zMADCATz** [comment]
@brandyscarney  not for me same error

**Comment by DILEEP-YADAV** [comment]
hi! @brandyscarney 

please update dependency with starter project 
npm install gulp-sass@2.2.0
npm install node-sass@3.4.2

**Comment by pixelmanya** [comment]
@LastStarfi9hter For me neither. But then I added gulp-sass and node-sass to package.json and removed the node_modules directory completely. After that `npm install ` and everything is working as expected.

![bildschirmfoto 2016-04-21 um 14 15 41](https://cloud.githubusercontent.com/assets/172940/14708496/adf01a0a-07cb-11e6-8644-c1f265c7322c.png)

**Comment by DILEEP-YADAV** [comment]
I know ! 
I am talking about ionic starter project. They should be update. every one facing problem with this new update.

thanks

**Comment by pixelmanya** [comment]
@DILEEP-YADAV Sure, this is just a workaround. I bet @brandyscarney and her team are taking care of this issue…

**Comment by DILEEP-YADAV** [comment]
@pixelmanya 

thanks

**Comment by galvanu** [comment]
Thanks,
Works for me.

**Comment by jgw96** [comment]
Hey everyone! So if you install the latest `ionic-angular@nightly` there is a fix for this issue now!

**Comment by tlancina** [comment]
Hey all, sorry for the headache. Gulp-sass has a caret dependency on node-sass, which got a pretty big update last night that started erroring on things that weren't previously erroring before. Yay semver!

Should be fixed in all of the starters, which have been updated to beta.5. As always, let us know if you're still having problems, thanks!

**Comment by aaronksaunders** [comment]
not sure what the fix is here for existing projects?

**Comment by tlancina** [comment]
The Sass causing the error has been fixed in beta.6, so just updating
ionic-angular should resolve it.

If you need to stay on a previous version, you'll need to downgrade to
node-sass 3.4.1 I believe. If you're using npm3 you can install it from
your project root and it should work fine, otherwise for npm 2 you would
need to navigate to
node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/ and install it
there.

**Comment by stonelee74** [comment]
I got a new clone.
When I start the app:

liyandeMacBook-Pro:ionic-preview-app liyan$ ionic -serve
Caught exception:
 Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:11:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by DILEEP-YADAV** [comment]
One another new update beta.6 with starter is by default Material Design (Android Look and feel ) instead iOS.  
![update](https://cloud.githubusercontent.com/assets/8583769/14733880/efd0437e-0883-11e6-936c-e3448d5e590a.PNG)

Real Great for android first !

**Comment by nunoarruda** [comment]
https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9
