### ISSUE TITLE
Error with new update

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic#6261]
Hi @adamdbradley
     @brandyscarney 
 
 I am getting error after new update 

![error](https://cloud.githubusercontent.com/assets/8583769/14706089/51c5cdc4-07da-11e6-99fb-030c309ecad0.PNG)

Result :
![err](https://cloud.githubusercontent.com/assets/8583769/14706116/6c9eb174-07da-11e6-9414-43264c945a37.PNG)

**Comment by jbeullen** [comment]
Duplicate of #6258

**Comment by jbeullen** [comment]
#6258 
Duplicate

**Comment by DILEEP-YADAV** [comment]
But, That is not updated with starter project ?


new dependency
 
npm install gulp-sass@2.2.0
npm install node-sass@3.4.2
