### ISSUE TITLE
V2 - Beta 5 - Alert in Modal break Tabs navigation

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#6262]
#### Short description of the problem:
If on a tab page, you're opening a modal, which opens an alert which closes the modal, then the tabs navigation doesn't work anymore

**Steps to reproduce:**
1. Open this plunkr http://plnkr.co/edit/SJ8GtqbRntby5yGzLEft?p=preview
2. Click on the button **open modal**
3. Click on the button **close me**
4. Click on **yes**
5. Try to navigate to the other Tab, you can't anymore

![lunker20160421210937](https://cloud.githubusercontent.com/assets/216573/14707179/8f803c86-0806-11e6-8d36-f3eeffc0290a.gif)

**Which Ionic Version?** 2.x

**Comment by adamdbradley** [comment]
@JumBay In this case it's best to manually dismiss the alert, wait for the alert to finish animating out, then dismiss the modal, like this:

```
closeMe() {
  let confirm = Alert.create({
    title: 'Close Me?',
    buttons: [
      {
        text: 'Yes',
        handler: () => {
          confirm.dismiss().then(() => {
            this.viewCtrl.dismiss();
          });
          return false;
        }
      },
      {
        text: 'No'
      }
    ]
  });

  this.nav.present(confirm);
}
```

We just recently documented this under the "Dismissing And Async Navigation" section:
http://ionicframework.com/docs/v2/api/components/alert/Alert/

And in the "Nav Transition Promises" section:
http://ionicframework.com/docs/v2/api/components/nav/NavController/

Hope that helps!

**Comment by JumBay** [comment]
Oh I didn't that. 
That's exactly what I needed. 
Thanks
