### ISSUE TITLE
Option to disable ripple effect for android platform to improve performance

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6263]
**Ionic 2
Feature requirement**

**Comment by WHarris22** [comment]
Not tried it but this may be possible with the activator option in the [config section](http://ionicframework.com/docs/v2/api/config/Config/) try using highlight (what IOS uses) for the android option

**Comment by jgw96** [comment]
@dhheran Hey! @ould you mind describing where you are seeing performance issues caused by the ripple? And maybe make a plunker that demonstrates it? Thanks!

**Comment by dheran** [comment]
@jgw96 Forget about performance. But is there any option to disable ripple animations?

**Comment by jgw96** [comment]
@dheran Sure thing, but if you have performance issues with ripple in the future please feel free to tell us! Here is what your config should look like if you would like to disable ripple animations: 
```
    config: {
    platforms: {
      android: {
        activator: 'none'
      }
    }
  }
```

**Comment by dheran** [comment]
I there any option to disable only for list item with button wrapped?

**Comment by jgw96** [comment]
@dheran sorry just having a little problem understanding your question. Are you saying disable a ripple for a list item thats written like this `<ion-item button>` ?

**Comment by dheran** [comment]
I use like <button ion-item>

**Comment by jgw96** [comment]
@dheran You can take away the button and just use `ion-item`, that will get rid of the ripple.

**Comment by dheran** [comment]
then list highlight is not working.

**Comment by jgw96** [comment]
You mean the style (grey background) that gets applied when holding down on the ion-item?

**Comment by dheran** [comment]
Yes

**Comment by jgw96** [comment]
Sorry, so yeah that's gonna get removed with just a regular ion-item because only buttons get that style, there is unfortunately not a way to remove the ripple just for certain elements. If would just recommend writing a bit of your own CSS to get that effect back. You can just apply a background color when that element is :active.
