### ISSUE TITLE
bug: Ionic2 CSS issue with nested lists

### ISSUE THREAD

**Issue by HereThereBeMonsters** [driftyco/ionic#6266]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>There is a CSS rule to prevent the last item in a ionic-list to have a bottom border (see item.ios.scss) :

```
.item:last-child .item-inner,
  ion-item-sliding:last-child .item-inner {
    border: 0;
  }
}
```

The problem is the selector:
`ion-list > .item:last-child .item-inner`
(and some similar selectors for sliding items)

If you have a nested list inside the last item of the parent list, the rule will apply to all the items in the nested list and none of them will have a border.

I suppose this could be fixed by using a selector with immediate child between item:last-child and item-inner.

I am not a very experienced mobile developer and so I don't know if nested lists are a usual use case. It was useful in my case anyway and I used it to show/hide extra details about the item of the parent list.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
@HereThereBeMonsters I am going to close this issue since I can't imagine a good use case for nested lists. Please feel free to comment if you have a good use case.

>I am not a very experienced mobile developer and so I don't know if nested lists are a usual use case. It was useful in my case anyway and I used it to show/hide extra details about the item of the parent list.

You can use `ion-item-group`.
