### ISSUE TITLE
bug: Ionic view does not refresh with cordova plugin

### ISSUE THREAD

**Issue by isvicbhasme** [driftyco/ionic#6268]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>My ionic version: 2.0.0-beta.25

When using cordova-plugin-datepicker, as part of 'onSuccess' callback the selected date is added into an array which in-turn was bound to the ionic view using *NgFor and '{{}}'. When the new date is added to the array, it is expected that the new date gets rendered to the view.

This scenario works when using ionic's input type='date' instead of cordova plugin. But when using cordova plugin, the change in array list is not reflected in the rendered view.

Please see codepen: http://codepen.io/isvicbhasme/pen/grjPgP</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So yeah, the stock cordova datepicker plugin has issues with cordova in ionic 2 because of how change detection works in Ionic 2/Angular 2. This is why we started the Ionic-Native project which wraps popular cordova plugins and makes them work better with Ionic 2! The datepicker plugin is supported by Ionic-Native so i would recommend that you use it instead of the stock plugin. Here is a link to the docs for the Ionic native version of the datepicker plugin: http://ionicframework.com/docs/v2/native/Date%20Picker/

**Comment by jgw96** [comment]
I am gonna go ahead and close this issue as Ionic-Native should fix it, but if it still doesn't work just comment back and ill happily reopen. Thanks again!

**Comment by isvicbhasme** [comment]
Hello, I should have mentioned that the date-picker plug is from ionic native.

**Comment by jgw96** [comment]
hey @isvicbhasme ! No problem! i dont see where your importing it in your codepen though? It looks to me as if your just using the standard cordova plugin?

**Comment by isvicbhasme** [comment]
This is the first time i'm using codepen and I couldn't figure out the cdn I should use for 'ionic-native' module. However, I've now pushed my repository to github from where you can have a look.

https://github.com/isvicbhasme/greeter/tree/master/app/pages/apply-leave

**Comment by KaiWangCanada** [comment]
Having the same question

**Comment by jgw96** [comment]
@isvicbhasme ahh ok, thanks for sharing your github repo, that helps alot! So i think the solution at this point would be to use `NgZone`. Here is an example of what i would try. 

```
import {NgZone} from 'angular2/core';

class MyCoolPage {
    constructor (private _zone: NgZone) {
        
    }

    public showPopup {
        DatePicker.show({
       date: this.getNextSundayAsDate(),
       mode: 'date',
       titleText: 'Take-off on...',
       todayText: 'Today'
    }).then(
       date => {
         console.log(date);
         if(date != null) {
           this.takeOff.date = date.getTime();
           console.log("Calling addLeaveToList() "+ JSON.stringify(this.takeOff));
           this.zone.run(()=> {
               this.addLeaveToList();
           })
         }
       },
       error => {
         console.log(error);
       }
     )
    }
}
```

**Comment by isvicbhasme** [comment]
@jgw96 no problem! Using ngzone fixes this issue, thank you. However, I guess this is only a workaround until a proper fix is given by cordova.
