### ISSUE TITLE
Position Toast Bottom, Middle, Top of screen

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6269]
I would like to be able to position the toast view dynamically to fit whatever use case I may have.  It is common practice among toast views for them to show up at the bottom, top or middle of the screen.

The [toast cordova plugin](https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin) provides this functionality and I think Ionites would take advantage of this.

This is for Ionic 2.0

**Comment by brandyscarney** [comment]
Probably something like:

```
const toast = Toast.create({
  message: 'User was created successfully',
  position: 'top'
});
```

Then add a class for the position.

**Comment by apparition47** [comment]
**+1**

I'd love to see this too. In the current `beta.6`, I can position the toast using the `cssClass` field but I'm having a bit of trouble with the default CSS animation that makes it slides up when visible then down when hiding (i.e. doesn't go well with a top-positioned toast).

**Comment by danbucholtz** [comment]
PR'd and submitted.  Closing.
