### ISSUE TITLE
ionic2: loading: interface LoadingOptions cssClass ?

### ISSUE THREAD

**Issue by vss0705** [driftyco/ionic#6273]
#### Short description of the problem:

```
export interface LoadingOptions {
  spinner?: string;
  content?: string;
  showBackdrop?: boolean;
  dismissOnPageChange?: boolean;
  delay?: number;
  duration?: number;
}
```

cssClass ?

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic Framework Version: 2.0.0-beta.6

**Comment by jgw96** [comment]
Thanks for opening this issue with us! Would you be able to provide some more information on the issue you are having? Thanks!

**Comment by vss0705** [comment]
ionic/components/loading/loading.ts (224 Line)
`cssClass`
It seems to be missing.

**Comment by brandyscarney** [comment]
Thank you for the issue. This was fixed on issue https://github.com/driftyco/ionic/issues/6365 and will be in the `beta.7` release. :smile:
