### ISSUE TITLE
Add Electron to platform registry

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6274]
Just like Cordova, Electron is another platform engine which Ionic can support. Add Electron to the platform registry, and add the appropriate events custom to Electron, but emitting the standardized `Platform` events. Start by copying the `cordova` platform registry.

https://github.com/driftyco/ionic/blob/95ee2bb448e9c91d6657ade393f2d615c377c8d8/ionic/platform/registry.ts#L165

**Comment by jgw96** [comment]
Here's what i have so far on this. Figured out from the limited info on the web, and through testing that the best way to check if your running on electron is to check the UA for "electron". The UA always has electron in it, even on windows. So using this i now have the electron platform triggering perfectly. Looking at events now and heres what i have on that so far. It looks like in the renderer process (electron apps have two main "processes"), which is where ionic is running its just standard browser events (like `window.onload` etc etc) and no custom events specific to electron.

**Comment by NorthMcCormick** [comment]
Understand this is closed, but I am looking at being able to trigger the platform ready for some electron stuff I'm working on. Would it be okay if I did a PR that registers electron or is this coming up in the next release (I'm definitely looking at having it sooner than later :P)

Just let me know :)
