### ISSUE TITLE
bug: ion-navbar not displaying content well on Android

### ISSUE THREAD

**Issue by schankam** [driftyco/ionic#6276]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I am having an ion-navbar at the top of my main application page, like this:

```
<ion-navbar *navbar>
  <button (click)="displayUserProfile()" clear>
    <ion-icon name="person"></ion-icon>
  </button>
  <ion-title>My app</ion-title>
  <button (click)="writeNewPost()" clear class="right">
    <ion-icon name="create"></ion-icon>
  </button>  
</ion-navbar>
```

The content is displaying correctly on iOS but unfortunately it is floating out of the screen on Android. If I do remove my buttons and just let the title, this one is not centered on Android whereas on iOS it is.

I am having these classes on my body: 

`platform-android platform-cordova platform-webview md platform-mobile platform-android6 platform-android6_0 platform-phablet`

</span>

<span is-issue-template></span>

**Comment by dylanvdmerwe** [comment]
Would it be possible to create a [plunkr ]( http://plnkr.co/edit/FV8COT9PvzID6BOd8W5H?p=info)to demonstrate this issue?

Have you looked at the docs [here](http://ionicframework.com/docs/v2/components/#toolbar-buttons) for examples?

**Comment by schankam** [comment]
Big mea culpa here, I should have check the doc more deeply about how to add icons on the navbar. Working well with ion-buttons "start" and "end" :)
