### ISSUE TITLE
Ionic2: Floating Input styles broke after beta5

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#6278]
#### Short description of the problem:
After updating to ionic5, my floating input fields style broke. This is due to the style `-webkit-backdrop-filter: blur(10px);`.

The issue is only seen in Safari, mobile and desktop, and in ios emulator.

#### Screenshot:
https://www.evernote.com/l/Alp2X9PDnm5Om4epw2dylkBWOb6SSG3MSnA
 

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
@Yagger Hey! Thanks for opening an issue with us! So yeah we already have a fix for this in the latest Ionic 2 nightly. If you just run `npm install ionic-angular@2.0.0-beta.6-201604212137 --save` in your project and then it should work fine.

**Comment by jgog** [comment]
Hey @jgw96 I just updated to beta 6 but the issues still persist. 

![crying-cry-it-me-26AHLMsoGBRExNI08](https://media2.giphy.com/media/26AHLMsoGBRExNI08/giphy.gif)

**Comment by Yagger** [comment]
@jgog did you update specifically to `2.0.0-beta.6-201604212137`? Because it worked for me.

**Comment by jgog** [comment]
@Yagger no, I did `2.0.0-beta.6`

**Comment by Yagger** [comment]
@jgog then do `npm install ionic-angular@2.0.0-beta.6-201604212137 --save` as @jgw96 proposed.

**Comment by jgog** [comment]
worked!
![90s-cartoon-street-sharks-1eWPlKeGfmOA0](https://media0.giphy.com/media/1eWPlKeGfmOA0/giphy.gif)

thanks @Yagger

**Comment by GavinHellyer** [comment]
I am seeing this same issue on beta.7

**Comment by jgw96** [comment]
Hmm, i cant seem to repro on beta.7, can i have a repo that i would be able to reproduce it with? Thanks for using Ionic!
