### ISSUE TITLE
bug: class names for ion-slides gets replaced

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#6279]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I added a custom class name to my <ion-slides>:
```
<ion-slides class="my-custom-class">
  ...
```
but on compilation this class seems to get lost. Inspecting the element with chrome shows that `slides-1` class replaced my custom class instead of being added in addition to my custom class.
```
<ion-slides class="slides-1">
  ...
```

**Comment by dylanvdmerwe** [comment]
Already logged https://github.com/driftyco/ionic/issues/6277
