### ISSUE TITLE
How to always show parent state every click tabs menu in ionic2

### ISSUE THREAD

**Issue by RunningV** [driftyco/ionic#6280]
i have menu tabs news, like in web first show a list of new news, then click read more, then show detail news, when i click other menu tabs like promo, after that i click back news tab the menu show still show a content detail news, how to every i click menu tabs show parent state in<code> ionic2</code>. thanks before.

**Comment by dylanvdmerwe** [comment]
Can you create a plunkr to help demonstrate what it is you're trying to achieve?

**Comment by jgw96** [comment]
Hello! As it has been a little while since there was any activity on this issue i will be closing it. Thanks for using ionic!

**Comment by RunningV** [comment]
I can't write code on `plunkr` cus `plunkr` can't render bottom tab navigations . i have no idea how to solve it. try to describe clear: there a two bottom tab navigations A && B,  both have chlid pages. when i click to A's child page then click bottom tab B immediately then click bottom tab A ,it still A's child page,but what i want is page A .it seems about history status, but i don't know how to clear it in ionic2. anyone help me ?tks
