### ISSUE TITLE
How to set <title></title> attribute different from $ionicNavBarDelegate.title()

### ISSUE THREAD

**Issue by anonrig** [driftyco/ionic#6284]
I'm trying to change the `<title></title>` attribute of the head element. Using `view-title` will change the title itself and also the navigation bar title. But `$ionicNavBarDelegate.title()` only changes the navigation bar title.

#### What behavior are you expecting?
I am expecting a different function to change the title of the app or `view-title` attribute not to change the title of the page.
 

**Which Ionic Version?** 1.x or 2.x
1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.5
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! As this is more of a question i would recommend that you hit up our awesome forum (https://forum.ionicframework.com/) our our slack channel (http://ionicworldwide.herokuapp.com/) and we will be able to help you there. Thanks for using ionic!
