### ISSUE TITLE
Remove dependencies no longer used or needed

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6287]
Review all of the dependencies in our package.json and remove any we're no longer using, and ones that are no longer needed.

Dependencies we may no longer need in our package.json since they now come in angular2-polyfills:
- zone.js
- reflect-metadata

**Comment by adamdbradley** [comment]
For reference:

https://github.com/angular/angular/issues/6659#issuecomment-185120027

**Comment by adamdbradley** [comment]
Also, look into removing `q` and `lodash` entirely.

**Comment by jgw96** [comment]
Made a new project using each one of the starters removed my node_modules, removed both zone.js and reflect-metadata from my package.json, then did an npm install and then did testing in both chrome and my devices and they worked perfectly fine, so i can confirm that we do not need to install zone.js or reflect-metadata anymore as long as we include the polyfills.

**Comment by jgw96** [comment]
This was done in this commit: https://github.com/driftyco/ionic2-app-base/commit/797f2a31af413283c0159e9c3c16e67f5a6343ca
