### ISSUE TITLE
Disabled attribute does not work in an ion-segment-button

### ISSUE THREAD

**Issue by jalef** [driftyco/ionic#6288]
Hello!

I want to disable an ion-segment-button and , as It is demonstrated to the plunker , 'disabled 'attribute is not being applied.
Is there any other way to achieve this?

#### What behavior are you expecting?
'disabled' attribute to work inside any kind of button.

**Steps to reproduce:**
1. Create an ion-segment
2. place inside some buttons
3. place 'disabled' attribute 
4. all buttons are enabled

**Which Ionic Version?** 
Ionic Version: 2.0.0-beta.4

#### Plunker that shows an example of your issue

http://plnkr.co/edit/GeWL1PMwMF9y4wGekF1j?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v4.2.4

**Comment by jgw96** [comment]
I can confirm, good catch!

**Comment by brandyscarney** [comment]
Thanks for the issue, this was recently fixed by https://github.com/driftyco/ionic/issues/5639 and will be in the `beta.7` release. Going to close this. :smile:

**Comment by NishanthKabra** [comment]
Able to see the same issue in ionic 2.0.0-beta.25
`  <ion-segment-button value="Next" [disabled]="true">
        Next
      </ion-segment-button>
      <ion-segment-button  value="Save" (click)="save()">
        Save
      </ion-segment-button>`
