### ISSUE TITLE
Ionic v2 - toast (feat) - add option to not block user interaction

### ISSUE THREAD

**Issue by apparition47** [driftyco/ionic#6291]
With the new `2.0.0-beta.6`, it would be nice if we had an option to allow users to interact with the app  without forcing them to dismiss the toast first. Right now, Toast is basically an extension of ActionSheet, so actions in the background are blocked.

If I use the following .scss as my toast's cssClass, I can prevent toast from blocking the user:
```
.no-backdrop-toast {
    top: initial;
    bottom: 0;
    height: 54px;
}
```
```
                let toast = Toast.create({
                    message: 'hello world',
                    cssClass: 'no-backdrop-toast',
                });

                this.nav.present(toast);
```

**Comment by adamdbradley** [comment]
We've decided to entirely remove the backdrop from the toast component, which isn't apart of the material design spec. Thanks for bring it to our attention and letting us know it was an issue.
