### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by warner-pinz** [driftyco/ionic#6294]
#### Short description of the problem:
I followed the ionic2 documentation tutorial from http://ionicframework.com/docs/v2/getting-started/tutorial/
then execute command:  npm install
* It never install, and I get this error in the terminal: npm ERR! cb() never called!

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.21
Ionic App Lib Version: 2.0.0-beta.11
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by anggiaj** [comment]
Maybe this one the solution for this problem? https://github.com/driftyco/ionic-cli/issues/936

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this issue is related more to the ionic-cli and not the framework i will be moving this issue over there. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#956
