### ISSUE TITLE
Suggestion: Include Content Security Policy & Whitelist plugin by default

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic#6296]
I feel like one of the most common issues people are running into is not including the whitelist plugin / not having a content security policy defined in index.html. I think the concept of the CSP tag is very confusing as well.

Would it be reasonable to add a default Content Security Policy tag to the generated index.html file?

**Comment by brandyscarney** [comment]
Hey @joshuamorony is this for v2?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you feel it should be reopened. Thanks for using Ionic!

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic2-app-base#29

**Comment by brandyscarney** [comment]
Sorry @jgw96, I messaged @joshuamorony to ask if this was for v2 and he replied to me. I should've added that here. However, since this is something that needs to be added to the starters I have moved it.

**Comment by jgw96** [comment]
@brandyscarney no problem!
