### ISSUE TITLE
Ionic 2 - Directions in navigation

### ISSUE THREAD

**Issue by villander** [driftyco/ionic#6302]
which are the other values to **direction** in `this.nav.push()` ? have a `forward` to direction?

```javascript
pushPage(user){
     this.nav.push(SecondView,{
      // user is an object we have in our view
      // typically this comes from an ngFor or some array
      // here we can create an object with a property of
      // paramUser, and set it's value to the user object we passed in
      paramUser: user
     },{
      // here we can configure things like the animations direction or
      // or if the view should animate at all.
      direction: 'back'
     });
   }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is more of a question and not really an issue with the framework i would urge you to check out our forum (https://forum.ionicframework.com/ ) or our slack channel (http://ionicworldwide.herokuapp.com/) and ask on there.

**Comment by villander** [comment]
@jgw96  it is a issue of docs. Because it is not explicit

**Comment by jgw96** [comment]
@villander So there is a forward direction with nav.push() but you do not really have to use it as if you do not specify any direction it defaults to forward. Hope that answers your question (:

**Comment by villander** [comment]
@jgw96 so default is `forward` ? have options `forward`  and `back`  until now?
