### ISSUE TITLE
Issue #5071 not fixed

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6304]
**Ionic 2**
https://github.com/driftyco/ionic/issues/5071 issue was not fixed but issue has been closed
Tested in 
Ionic beta 6
Android 5.0.2

**Comment by jgw96** [comment]
@dheran Hello! Sorry you are still having an issue with that feature! Would you be able to give me more of a description of what issue you are having with the back button? I have tested with my android devices using the latest nightly of ionic 2 and it seems to work fine, but im not sure exactly what i should be testing to reproduce your issue.

**Comment by dheran** [comment]
did you used router? I'm using router.
Can you please share your code?

**Comment by jgw96** [comment]
@dheran you are using the angular 2 router?

**Comment by dheran** [comment]
yes

**Comment by hlehmann** [comment]
I also have an issue with this.
I have those child navs : 
```
nav1:Nav
|- tabs1:Tabs
    |- tab1:Tab
```
but when I do a `nav1.push(...)`, I still get `app.getActiveNav()` returning tab1 so it exit the app.

**Comment by jgw96** [comment]
@hlehmann Are you also using the angular 2 router in your project?

**Comment by hlehmann** [comment]
I just use regular navigation push and pop.

**Comment by jgw96** [comment]
@hlehmann awesome, would you mind posting a code sample or plunker I can use to repro this issue with?

**Comment by dheran** [comment]
@jgw96  Can you please share your code for reference?

**Comment by jgw96** [comment]
@dheran I'm just testing with our ionic-conference-app ( https://github.com/driftyco/ionic-conference-app ). We do some pretty standard navigation in that app, but not using the angular router.

**Comment by dheran** [comment]
It won't work if angular router was added?

**Comment by jgw96** [comment]
I am not sure, but thats what im working on narrowing it down to. Is there a reason you are using the angular router instead of our nav.pop() and nav.push() navigation?

**Comment by dheran** [comment]
I use nav.pop() and push for all navigation.
I use router to load some random url into native webview other than home page.

**Comment by carsonip** [comment]
@jgw96 The back button does not work for the platform `browser` (or just statically serving the www instead of building it into an app) now?

**Comment by jgw96** [comment]
@dheran Sorry, but im not sure im following exactly. Is there any way you could create a codepen, plunker or even a repo i could pull down and test with? @carsonip Hey! The back button in browser works just like it always has. This issue is specific to the hardware back button on most android devices.

**Comment by carsonip** [comment]
@jgw96 any plans on implementing the back button in browser? Or should I open another issue for that? I believe there are quite a number of people using Ionic to develop mobile web.

**Comment by jgw96** [comment]
@carsonip Sure, can you open another issue for it please (:

**Comment by carsonip** [comment]
@jgw96 #6363 issue opened. Many thanks.

**Comment by Bransonlee0426** [comment]
document.addEventListener('backbutton')
not work!
when i update to ionic@beta6
but beta4 was work
now, i can't use canGoBack() function when i touch backbutton of Android mobile
this issue still now?

**Comment by jgw96** [comment]
@Bransonlee0426 Hey! Would you mind opening a separate github issue for your bug please with a description and a plunker or codepen? Thanks!

**Comment by michaelmafort** [comment]
I have the same problem @Bransonlee0426. After updated my application @beta3 to @beta6 the eventListener watch the event but close application if I'm in the first page.

In my application I've blocked the backbutton behavior, to use only a nav backbutton, it's not possible more to I define the behavior of the hardware button?

**Comment by jgw96** [comment]
@michaelmafort Hey, thanks for the info! Would you be able to open a separate issue for you and @Bransonlee0426 problem? Thanks!

**Comment by Bransonlee0426** [comment]
@michaelmafort  hey!
Did u already to opened a separate issue? i need follow this issue answer!
thank you!

**Comment by Bransonlee0426** [comment]
hey~guys
Maybe im find the problem reason
in the components of node_modules (path:node_modules > ionic_angular > components > app > app.js)
inside line 32 ~ 42 as 

    platform.backButton.subscribe(function () {
            var activeNav = _this.getActiveNav();
            if (activeNav) {
                if (activeNav.length() === 1) {
                    platform.exitApp();
                }
                else {
                    activeNav.pop();
                }
            }
        });

Are ionic member modified these ones when upgrade ionic2 betaX to ionic2 beta6? 
I think developer need to controll the back event, e.g. settimeout or something
how can i do?
at the last version we use nav.canGoBack() like these

this.platform.ready().then(() => {
            StatusBar.styleDefault();
            let backbutton = 0;

            document.addEventListener('backbutton', () => {

                let nav: NavController = this.app.getComponent('nav');
                if (nav.canGoBack()) {
                    nav.pop();
                } else if (!nav.canGoBack()) {
                    if (backbutton === 0) {
                        backbutton++;
                        Toast.show("press again exit app!", "short", "bottom").subscribe();
                        setTimeout(function () { backbutton = 0; }, 5000);
                    } else {
                        navigator.app.exitApp();
                    }
                }
                // plugin.crypto.MD5('123456789',
                //     (jsonObj: Object) => {
                //         window.plugins.toast.show(JSON.stringify(jsonObj), "short", "bottom");
                //     },
                //     function (jsonObj) {
                //         console.log(jsonObj.message);
                //     }
                // );

            }, false);

        });

in the beta4 its work,but 6 not!
have any solution?
ths guys!

**Comment by jgw96** [comment]
Hello all! We are currently working on making it easy to implement custom actions and override the default behavior with the back button. Look out for it in a coming release! Thanks for using Ionic!
