### ISSUE TITLE
Ionic 1.3 ng-click fails on looped slide

### ISSUE THREAD

**Issue by jonathanherdt** [driftyco/ionic#6305]
#### Short description of the problem:

When setting `looped: true` in the slides options, ng-click on the looped slide does not work anymore.

#### What behavior are you expecting?

ng-click should work

**Steps to reproduce:**
I created a [small plunkr](http://plnkr.co/edit/JQ2eaU6DL4gdAjc6uTCI?p=preview) with the problem.
1. Click on the button on the first slide. As expected, a popup appears.
2. Now drag to the left so you can see the second slide. Click the button. As expected, a popup appears.
3. Now drag to the right twice so you reach the looped slide. Click the button. Nothing happens.

**Which Ionic Version?** 1.3

#### Plunker that shows an example of your issue

http://plnkr.co/edit/JQ2eaU6DL4gdAjc6uTCI?p=preview

```
ionic info

Your system information:

Cordova CLI: 5.3.3
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.7.0 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by danbucholtz** [comment]
Hi @jonathanherdt 😄 ,

This should be resolved now.  Thanks for contributing and using Ionic.

Thanks,
Dan
