### ISSUE TITLE
List bottom border conflicts with last element bottom border if the last element is an input

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#6307]
#### Short description of the problem:

The last input element in list has a bottom border indistinguishable from the bottom border of the input element.
#### What behavior are you expecting?

There is a spacing between the list bottom border and the last input element bottom border.

**Steps to reproduce:**
1. Go to the [input component's documentation](http://ionicframework.com/docs/v2/components/#inputs)
2. See that the bottom margin of the last element is not well positioned

**Which Ionic Version?** 1.x or 2.x

2.x

#### Plunker that shows an example of your issue

http://ionicframework.com/docs/v2/components/#inputs

**System Information:**

Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by NoNameProvided** [comment]
@Ionitron should have add the v2 tag.

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! So this is actually by design (: haha

**Comment by NoNameProvided** [comment]
Its ok if it's by design :) then I will adapt hehe 

> I would love to know if this causes an user experience issues for you or your apps users.

It just looks strange on the linked demo page. Maybe you should consider to add some padding to the last input element there, because the border of the list and the input bottom border touch each other now, and it seems like the last input element has too wide bottom border. 

![screen shot](https://cloud.githubusercontent.com/assets/4706265/14919033/20bf8956-0e27-11e6-8131-ef83337bf787.png)

**Comment by jgw96** [comment]
@NoNameProvided Thanks for the info, might be something for us to consider (: Thanks for using ionic!

**Comment by sijad** [comment]
I have same problem
