### ISSUE TITLE
iframe zoom do not work

### ISSUE THREAD

**Issue by xianbinsong** [driftyco/ionic#6308]
I am  showing the pdf in iframe 
HTML:
![9a986b7b-6de7-40d7-a556-f8a637d6c7da](https://cloud.githubusercontent.com/assets/11609192/14779568/4cd73620-0b0b-11e6-8bee-709502f0206c.png)

css 
.agree-modal .scroll {
  height: 100%;
  width: 100%; }

JS
 $scope.trustSrc = function(src) {
    return $sce.trustAsResourceUrl(src);
  };

$scope.check_file = {name: "test",preview:#my_pdf_url}

but zoom is not work, without iframe  zoom is work

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
hello @xianbinsong ! Would you be able to upgrade your project to the latest version of ionic 1 (1.3.0) and test again please? It looks like your currently using ionic 1.0.1. To upgrade you can simply use bower to install the latest version of ionic `bower install ionic@v1.3.0` Thanks!

**Comment by xianbinsong** [comment]
![8fd61df8-3d45-4044-9054-d7a375bbaa49](https://cloud.githubusercontent.com/assets/11609192/14805628/2630d7e8-0ba0-11e6-8fa9-902eecd388a1.png)

bower install ionic@v1.3.0  do not work

**Comment by xianbinsong** [comment]
![8fd61df8-3d45-4044-9054-d7a375bbaa49](https://cloud.githubusercontent.com/assets/11609192/14805715/31279780-0ba1-11e6-92b4-8ebc2c311a40.png)

bower install ionic@v1.3.0 do not work

**Comment by jgw96** [comment]
Actually, sorry about that, just running bower install should update your dependencies to v1.3.0.

**Comment by xianbinsong** [comment]
after update ioinc 
my ionic info 

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3 Build version 7D175 

but iframe can not zoom   and ng-click="$ionicGoBack()" can not back to tab

**Comment by danbucholtz** [comment]
Hi @xianbinsong,

Please provide a codepen or plunkr demonstrating the issue.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by nibytes** [comment]
Hi guys, I need zoom in iframe, but have only scroll (x,y)
![1123213333](https://user-images.githubusercontent.com/15169344/32691056-d8a4c840-c70a-11e7-83f9-4bd7733f21bd.gif)
