### ISSUE TITLE
Bug when use collection-repeat render grid 

### ISSUE THREAD

**Issue by phuongpt** [driftyco/ionic#6309]
Hi guys, I'm using collection-repeat for rendering grid, but sometimes have some cards is rendered incorrect, although 2 cards have `y` are same  `transform: translate3d(0px, y, 0px)`. I need some help from you, thanks.

<img width="279" alt="screen shot 2016-04-25 at 5 18 00 pm" src="https://cloud.githubusercontent.com/assets/4443583/14781097/a8ce16ca-0b0a-11e6-9e1a-ce7adf98e533.png">

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you be able to provide a codepen or plunker that demonstrates your issue? You can use this plunker i made as a template: http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Comment by phuongpt** [comment]
@jgw96 Hi, something like this https://codepen.io/phuongphan/pen/mPGrbg

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#141
