### ISSUE TITLE
Unable to switch from JS to TS in ionic 2

### ISSUE THREAD

**Issue by epetre** [driftyco/ionic#6312]
I changed the file extensions of my app files including app/app.js

`Error: Cannot find module 'app/app.js' from 'app_folder'`

It doesn't tell me which file I should be looking at to fix the error. 

I tried looking with `git grep` and read a bit about Angular2's entry points to find out where it is loaded, but no luck yet.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Since this is more of a question and not really an issue with the framework i am going to point you towards our forums (https://forum.ionicframework.com/) they will be able to help you over there. Thanks again!

**Comment by iignatov** [comment]
@epetre If it's a new app, I would recommend you to start it over with the `--ts` flag.

In case that you want to convert an existing app from JS to TS, then you should also make some updates to the project and the build process. I will recommend you to create a new TypeScript project and perform merge of the relevant files between the two projects. You can do this by executing:
```
ionic start BlankTS blank --v2 --ts --skip-npm
```

As a minimum you'll have to replace `ionic-gulp-browserify-es2015` with `ionic-gulp-browserify-typescript` in both `package.json` and `gulpfile.js` and create `tsconfig.json` and `typings.json` files using the ones from [the following repository](https://github.com/driftyco/ionic2-app-base/tree/typescript) as a reference.

**Comment by epetre** [comment]
ok, thank you I managed to find what I was looking for by digging in the code and doing some tiral and error.
 
Here is how to do it in case Im not alone :)
http://stackoverflow.com/questions/36847051/unable-to-switch-from-js-to-ts-in-ionic-2/36851567#36851567
