### ISSUE TITLE
Centering text is not working inside a slide

### ISSUE THREAD

**Issue by msaelices** [driftyco/ionic#6313]
#### Short description of the problem:

The `text-center` attribute is not working inside a slide, because of the `position: flex` style.
#### What behavior are you expecting?

The text value should be centered.

**Steps to reproduce:**

Test with a page like this:

```
<ion-content padding class="purchase">
  <ion-slides #slides>
    <ion-slide>
      <ion-row text-center>
        Some centered text
      </ion-row>
      <ion-row text-center>
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </ion-row>
    </ion-slide>
  </ion-slides>
</ion-content>

```

**Other information:** I fixed it in my project with this CSS:

```
[text-center] {
  flex-direction: column;
}
```

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID: Ubuntu Description: Ubuntu 15.10 
Node Version: v4.4.3

**Comment by brandyscarney** [comment]
Thanks for the issue. `ion-row` should be used with an `ion-grid` and `ion-col`. The following markup works fine:

```
<ion-slides #slides>
  <ion-slide>
    <ion-grid>
      <ion-row text-center>
        <ion-col>
          Some centered text
        </ion-col>
      </ion-row>
      <ion-row text-center>
        <ion-col>
          <ion-icon name="checkmark-circle-outline"></ion-icon>
        </ion-col>
      </ion-row>
    </ion-grid>
  </ion-slide>
</ion-slides>
```

**Comment by jyotikumari14** [comment]
.state {
    	display: flex;
    	justify-content: center;
}

put this class in <ion-row> or <ion-slide> element.
