### ISSUE TITLE
Why does collection-repeat only work with x OR y scroll?

### ISSUE THREAD

**Issue by vance** [driftyco/ionic#6314]
Not really a bug, but I'm curious if it is possible, or if this was intentional because it is not possible. Given the [source material](http://www.foreverscape.com) of my application, it is critical that I can memory/performance optimize for x/y scroll.

**Comment by vance** [comment]
Is is possible to have it only "listen" to one axis, while allowing scrolling in both? E.g. scroll down and content loads, scroll right, nothing happens: it's already loaded.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this is more of a question instead of an actual bug report i will urge you to ask this question on our forum (https://forum.ionicframework.com). The great community over there should be able to help you!
