### ISSUE TITLE
Please add VirtualScroll for Slides 

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6315]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Virtual Scroll is great. However, it works only with ion-list. 
Can you please add this feature to ion-slides ?

**Comment by brandyscarney** [comment]
Closing as a duplicate of https://github.com/driftyco/ionic/issues/6343
