### ISSUE TITLE
searchbar very slow

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#6316]
I have tested with 1000-2000 items (length on average of 40 characters) . To search for an item is VERY slow . It seems to take about 5 seconds on a low wend android device to see the character show up, then another 10 seconds for the result to filter based on the criteria. 1000 items is not that much, could this be improved?

**Comment by manucorporat** [comment]
We have improved a lot the performance of searchbar by making it very lightweight.

But the performance of your search algorithm is up to the developer. Just use a better search algorithm, indexes etc.
