### ISSUE TITLE
notworking: hardwareBackButtonClose: true 

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#6317]
hardwareBackButtonClose: true 

on ionic 1.3.0 with modals

not working

**Comment by jgw96** [comment]
Hello! Thanks for opening am issue with us! Would you mind posting a code sample, plunker or codepen that we can use to reproduce this issue?

**Comment by emps** [comment]
well its simple just make modal and givin in options hardwareBackButtonClose: true
and by touching back button nothing happens...
this problem starts with this new 1.3.0

**Comment by danbucholtz** [comment]
@emps,

Can you provide the context for this?  We made a change to how history navigation works in 1.3.  Right now, this `worksforme` in a basic slide-in slide-out navigation app.  I just tested this.

Is your app a tabs app?  Can you provide a codepen showing the situation?

Thanks,
Dan

**Comment by emps** [comment]
ok i need to build it , i have tabs plus left menu .. navigation with hardBack button works 
but to close modal is not working
so to build this i need some time will try finish this in next hours,  thanks

**Comment by emps** [comment]
ok thats strange my project that was built with 1.2.4 and updated to 1.3.0 has the problem..
but i built now demo project from clean new project based on 1.3.0 and there is no any problems
i will try play with this a bit more and update u guys

**Comment by danbucholtz** [comment]
There were some changes to the way history works so I am not surprised.  Perhaps we should reconsider them.

Thanks,
Dan

**Comment by emps** [comment]
ok thanks after readd platforms problem solved, i think we can close this issue
