### ISSUE TITLE
openlayer click event dose not work.

### ISSUE THREAD

**Issue by xsgkaka** [driftyco/ionic#6321]
`level 1:(visit in chrome browser)`
i use openlayer in my ionic app. Everything is correct.
`level 2 (visit in chrome browser)`
i add a login state. that means the first state is not the map view. when i change the state to map view from login vew . the strange things hanppen:When the map is loaded, drag and zoom events are correct. but the click event is not correct.
so i find the old issues, i found the solution: add `data-tap-disabled="true"`.so  i test, all right. everything is correct again.
`level 3 : ( visit in android device)`
the click event is not  responseable again ~~~~(>_<)~~~~. i almost lost my mind.  
anyone help me ? thanks in advance.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you be able to post a codepen, plunker or codesample that demonstrates this issue please? Thanks again!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
