### ISSUE TITLE
scrolling still active by sliding list

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic#6322]
#### Short description of the problem:
See issue by ionic-priview-app [here](https://github.com/driftyco/ionic-preview-app/issues/14#event-640684599). 

The problem is that I can scroll up and down when I activate the `ion-slide-option`. And that it not automatic slide back when I scroll the list when the list is activated. 

http://ionicframework.com/docs/v2/components/#sliding-list

#### What behavior are you expecting?

The iOS native feeling is when you active the list-options (finger still swiping to left) that you can't scroll up and down. And when you fully activate the options and you scroll up and down that the options are going to hide.

**Comment by manucorporat** [comment]
@mbakker96 Hi, that is not 100% correct. I have tried several native apps, and sliding a item does not block scrolling. Please give a more detailed use case and example. I will close this for now, but I will reopen. Could you test this PR: https://github.com/driftyco/ionic/pull/6686 ? I am working in the sliding feature.
