### ISSUE TITLE
Feature requirement: For Android support swipe navigation between segments for ion-segment

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6327]
**Ionic 2**

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by barocsi** [comment]
it's like the essence of this control...

**Comment by infinnie** [comment]
See also #5101

**Comment by brandyscarney** [comment]
I'm going to close this as part of https://github.com/driftyco/ionic/issues/9311.
