### ISSUE TITLE
$ionicHistory.goBack() Does not work

### ISSUE THREAD

**Issue by babinc** [driftyco/ionic#6328]
#### Short description of the problem:
$ionicHistory.goBack() does not work

#### What behavior are you expecting?
$ionicHistory.goBack(); to go to previous page.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
$ionicHistory.goBack() does work on a clean 1.3.0 project. And it also works in version 1.2.4. Just not when I update my previous project to 1.3.0 using ionic lib update. 

link to other people having the same issue:
https://forum.ionicframework.com/t/ionichistory-goback-does-not-work-in-1-3-0/50247
 

**Which Ionic Version?** 1.x or 2.x
1.3.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.0
Gulp local:
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.0.0

**Comment by danbucholtz** [comment]
Hi @babinc,

Can you figure out a way to recreate this?  This `worksforme` currently.  I have tried with both hardware back buttons, and just using `$ionicHistory.goBack()`.  In both cases, it works as expected.

What is the context of your app, and when is it happening?  It is a standard navigation app, or does it use tabs?  I need more info so I can resolve.

Thanks,
Dan

**Comment by danbucholtz** [comment]
This should be resolved now.  Please test this fix via the [nightly build](http://code.ionicframework.com/#nightly) tomorrow and comment back if the issue continues.  The easiest way to test is to download the zip file and replace the contents of www/lib/ionic with the contents of the zip file.

Thanks for letting us know of this issue!

[See the commit here](https://github.com/driftyco/ionic/commit/e31498c4b8e6c5c2758e699e418daf72cac50ff4).

Thanks,
Dan
