### ISSUE TITLE
ion-select Material Design issues

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6330]
**Ionic 2**

I've created a plunker http://plnkr.co/edit/dJGow1?p=preview

There are two issues
Issue 1 - Disabled text not changing color: 
1. Click on Type and select any one option other than empty
2. Again click on Type and select empty
3. Brand's empty text was not changing to disabled color.

Issue 2 - Values overlapping:
1. Click on Type and select any one option other than empty
2. Click on Brand and select any one option other than empty
3. Again click on Type and select empty
4. Brand values were getting overlapped

These issues were not in ios styles.

**Comment by brandyscarney** [comment]
I'm going to close this as I am no longer able to reproduce it using the latest version `2.1.0`. If you are still seeing this issue please let me know. Thanks!
