### ISSUE TITLE
Allow user to bookmark a route

### ISSUE THREAD

**Issue by dzincolorado** [driftyco/ionic#6333]
#### Short description of the problem:
Currently, there is no way for a user to bookmark a certain route.  The nav stack is cool, however, we need a way for a given route to be shown in the browser bar and have that route (and any route params) be handled by ionic2/ng2 to load the applicable page/component.

An app that may have routes with optional params becomes virtually impossible to build with bookmarking in mind.

#### What behavior are you expecting?
I would like the option to have the ng2 routing at my disposal and not just the nav stack.

**Steps to reproduce:**
1.  Build a multi page app with pages that may consume optional params
2.  Navigate to a page with params specified and bookmark it.
3.  Return to the bookmarked page.  The applicable page does not load.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
  
I posted about this in the forum - https://forum.ionicframework.com/t/ionic2-and-routing-and-hotlinking/49341

**Which Ionic Version?** 2.x

**Comment by dzincolorado** [comment]
Hi,

Is it possible to upgrade to beta 10 and use ng2 router version 3?  Really would love to upgrade to leverage the latest features and have routing/bookmarking ability.  I'm currently stuck on ionic 2 beta 6.

Thanks,
Denis

**Comment by jgw96** [comment]
Hello all! We are currently working on integrating the Angular 2 router 3.0 into Ionic 2. Here is the tracking issue for this https://github.com/driftyco/ionic/issues/6563. Thanks!

**Comment by darklx** [comment]
Hoping the support for web app bookmarkable!!
