### ISSUE TITLE
ng-enter-stagger doesnt' work with Ionic 1.x

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic#6335]
#### Short description of the problem:
I want to animate a list using ngAnimate but ng-enter-stagger doesn't work with ngRepeat

#### What behavior are you expecting?
Animate a list like: http://gonehybrid.com/how-to-animate-your-ionic-app-with-animate-css-and-nganimate/

Regards, Nicholls

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us!  As this issue does not seem to be specific to a bug with the ionic framework I will point you to hit up our forum https://forum.ionicframework.com/. The awesome community on there will be able to help you. Thanks!
