### ISSUE TITLE
Icon aligning would be a lot easier with squared icons

### ISSUE THREAD

**Issue by Poketchu** [driftyco/ionic#6337]
Hey there,

Big fan of your work in this beta, you keep surprising me everyday.
Now as a total order maniac, I like my icons perfetly aligned, and I think that the <ion-icon> tag could be upgraded with a simple feature: use square icons.

As showed in the following picture, my thermometer is only 9px wide and 24px tall. As my icons are aligned using the 'item-right' option, they are not "center" aligned. This would be solved by having all the icons having the proportions "24x24".
![image](https://cloud.githubusercontent.com/assets/9591559/14846924/762b1f62-0c66-11e6-8088-0b755f97ddd9.png)

However, if there is a solution to my problem, I'll gladly use it.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#160
