### ISSUE TITLE
Marker attributes not present as @Input in some components

### ISSUE THREAD

**Issue by jimitndiaye** [driftyco/ionic#6339]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Alot of ions have marker attributes that change their behavior or design in some way. However there are often no corresponding ```@Input```s to set these attributes. Examples are the ```top```, ```bottom``` attributes of the ion-row and ion-col. I understand these two aren't currently components per se but it would be great if they were so these attributes could be controlled dynamically via inputs.

#### What behavior are you expecting?
The availability of ```@Input``` properties on components like ion-col and ion-row.

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by adamdbradley** [comment]
Sorry but the grid elements are just css, and are not directives or components. Any alignments can be done with just css. Thanks
