### ISSUE TITLE
NodeJS 6 support

### ISSUE THREAD

**Issue by dealloc** [driftyco/ionic#6340]
#### Short description of the problem:
Ionic currently uses a deprecated version of [graceful-fs](https://github.com/isaacs/node-graceful-fs) which generates an enormous amount of stack traces when serving, or any other action for that matter

**Steps to reproduce:**
1. install NodeJS 6
2. run ``` ionic serve ```

**Which Ionic Version?** 1.x or 2.x
Ionic 2.0.0-beta.25

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
(node:13866) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================
<truncated huge stacktrace>


Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Arch Description:	Arch Linux 
Node Version: v6.0.0
```

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Since this issue is more related to the CLI than the framework I will be moving this issue over to that repo. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#960
