### ISSUE TITLE
Please add VirtualScroll to ion-slides

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6343]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I'm using ion-slides in my app to display only one card per page and for the slide transitions it provides compared to a list.
I'm seeing a slower performance since I believe, it tries to load all the slides (each slide has an image)

#### What behavior are you expecting?
I'm assuming VirtualScroll allows for a delayed loading of images in slides that are not visible. If yes, can I request you to add VirtualScroll feature for ion-slides

**Which Ionic Version?** 1.x or 2.x
Ionic Version 2...beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by adamdbradley** [comment]
Sorry but this feature is not on our road.
