### ISSUE TITLE
Problem with ionic scroll when use $location.hash 

### ISSUE THREAD

**Issue by webquali** [driftyco/ionic#6346]
https://www.youtube.com/watch?v=d8nDOsoFSsY

On app I have scroll by hash when click on arrow botton in screen. When I scoll manualy it's norm working. When scroll by arrorr it wrong calculate scroll layout. On video you can see white screen on bottom.

My code is easy

$ionicScrollDelegate.anchorScroll(true);
$location.hash('post_id_1');

**Comment by jgw96** [comment]
Hello @webquali ! While the video is super helpful, would you be able to make a codepen or plunkr of your exact code that we can use to reproduce this issue? Thanks!

**Comment by webquali** [comment]
Hello jgw96,

Sure I will add it more later.

**Comment by jgw96** [comment]
Thanks @webquali !

**Comment by webquali** [comment]
I created codepen. 
http://codepen.io/Ilchenko/pen/YqJzae

And now I find after which we have this problem.

It's make effect after ng-include template

You can see this in my codepen example

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#140
