### ISSUE TITLE
Card: Please add feature to capture a snapshot of a card

### ISSUE THREAD

**Issue by panuganti** [driftyco/ionic#6347]
#### Short description of the problem:
Cards are super-useful and super elegant components. In our app, we would like to enable sharing of the card to other social network sites. We want to enable sharing it as-is (with the elegant way a card is rendered)
Can I request you to add a feature to capture the snapshot of the card ? 
I tried to use some publicly avaialble javascript libraries (like html2canvas). However, they don't do justice. They do not capture the image embedded in a card. Also, the rendering is blurry on smartphones (Android and ios).

**Which Ionic Version?** 1.x or 2.x
2.xxx..beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So, this is a cool feature, but it goes out of the scope of what ionic is intended to do. Although we build components to give your app basic functionality, custom features like this is something that ionic is not intended to do. Good luck with building your app and thanks for using Ionic!

**Comment by jgw96** [comment]
Also, there are alot of awesome devs on our forum (https://forum.ionicframework.com/) that would probably be able to help you with this functionality!
