### ISSUE TITLE
bug: Error when running Ionic on PHP applicatoin

### ISSUE THREAD

**Issue by socheatsok78** [driftyco/ionic#6353]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>My php script - ionic.php
-----
<?php
     $ANDROID_HOME = '/Library/Android/sdk';
      $JAVA_HOME = '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home';
      putenv('JAVA_HOME='.$JAVA_HOME);
      putenv('ANDROID_HOME='.$ANDROID_HOME);
           putenv("PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/lib/node_modules:/Library/Developer/CommandLineTools:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools");
  $shell_output = shell_exec("
    ionic -v 2>&1
  ");
  echo $shell_output;
?>
----

Result
-----
path.js:8 throw new TypeError('Path must be a string. Received ' + ^ TypeError: Path must be a string. Received undefined at assertPath (path.js:8:11) at Object.posix.join (path.js:479:5) at new IonicStore (/usr/local/lib/node_modules/ionic/lib/ionic/store.js:17:26) at Object. (/usr/local/lib/node_modules/ionic/lib/cli.js:6:19) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Module.require (module.js:353:17) at require (internal/module.js:12:17)</span>

<span is-issue-template></span>

**Comment by socheatsok78** [comment]
when i run "cordova -v" it print out the version, but for ionit it show errors

**Comment by dheran** [comment]
@socheatsok78 this issue has to be under 
https://github.com/driftyco/ionic-cli

**Comment by socheatsok78** [comment]
It just show the same error when i try to use php shell_exec to run ionic. For testing i just print out the version of Ionic. but the error persist. When i use the terminal on Mac OS, ionic run just fine but it doesn't run on PHP applicaiton.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this isnt really an issue with the framework (we do not officially support calling the ionic cli from a php application, or any kind of php integration) i will be closing this issue for now and urging you to check out our forum (forum.ionicframework.com) and ask around on there. There are some awesome devs on there who may be able to help you! Thanks for using ionic!
