### ISSUE TITLE
Using Ionic components/directives in "loading overlay" with custom HTML

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic#6357]
#### Short description of the problem:

Hi,

I'm using the new Loading component in Ionic 2. I'd like to use custom HTML that includes other Ionic components like e.g. ion-icon . This currently doesn't seem to be possible because we can't specify additional directives while using Loading.create();
#### What behavior are you expecting?

Option to provide directives to be used.

**Steps to reproduce:**
1. Create Loading indicator with custom html that includes an ionic directive/component
2. Won't work because the directive/component is not known to the Loading component.

```
const content = `<ion-icon name='ios-clock'></ion-icon> <h1 secondary>Accepted:<br/> ${time} minutes</h1>`;
const loading = Loading.create({
            spinner: "hide",
            content: content,
            duration: 500
        });
this.nav.present(loading);
```

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#30
