### ISSUE TITLE
Push Notification Issue (Without device token notification goes to the particular user id)

### ISSUE THREAD

**Issue by kori002** [driftyco/ionic#6358]
I am using ionic 1.x

I had follow the instruction for push notification as per the documentation.
I am able to send an notification to a particular user, even if  user don't have a device token.
I have followed this docs for sending notification through users_ids

[http://docs.ionic.io/docs/push-sending-push](url)

1. Firstly when i create the user without device token it doesn't send notification.
2. And when user get the device token then notification is received.
3. If we remove the device token from that particular user still user receive the notification. (So my point is that user should not  get notification.).
4. And when i deleted that particular user than also received a notification.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So since this issue is more related to the ionic platform instead of the framework i will be moving this over to that repo. Feel free to continue the conversation over there!!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-platform-issues#94
