### ISSUE TITLE
Ionic 1.3: `Unknown provider: $stateProvider`

### ISSUE THREAD

**Issue by dwilt** [driftyco/ionic#6362]
#### Short description of the problem:
Trying to update to Ionic 1.3 gives me a `$stateProvider` error and breaks my application.

#### What behavior are you expecting?
My application to run on 1.3. I tried the plunkr here: http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview and see you have an example of 1.3 working with `$stateProvider` but I'm at a loss to what the issue could be as the `$stateProvider` is a service provided by UI router and that comes packaged in the `ionic.bundle.js`.

**Steps to reproduce:**
1. I did a `bower install ionic --save` and updated all of the other dependencies in my application that depend on Angular 1.5.
2. Refreshed the browser and got the error in the console

Here's the error in the console:
```javascript
Error: [$injector:unpr] Unknown provider: $stateProvider
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=%24stateProvider
    at http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:13415:12
    at http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17765:19
    at getService (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17918:39)
    at injectionArgs (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17942:58)
    at Object.invoke (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17964:18)
    at runInvokeQueue (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17865:35)
    at http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17874:11
    at forEach (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:13668:20)
    at loadModules (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17855:5)
    at http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:17872:40
```
Here's my scripts in the `HEAD` of my `index.html`. You can see `ionic.bundle.js` is first:

```html
<head>
    <meta charset="utf-8">
    <title>My App</title>
    <link href="css/index.css" rel="stylesheet">
    <!-- bower:js-->
    <script src="lib/ionic/release/js/ionic.bundle.js"></script>
    <script src="lib/angular-cookies/angular-cookies.js"></script>
    <script src="lib/angular-filter/dist/angular-filter.min.js"></script>
    <script src="lib/angular-local-storage/dist/angular-local-storage.js"></script>
    <script src="lib/angular-translate/angular-translate.js"></script>
    <script src="lib/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
    <script src="lib/lodash/lodash.js"></script>
    <script src="lib/moment/min/moment-with-locales.js"></script>
    <script src="lib/ngCordova/dist/ng-cordova.js"></script>
    <script src="lib/parse/parse.min.js"></script>
    <script src="lib/pouchdb/dist/pouchdb.js"></script>
    <script src="lib/angular-ios9-uiwebview-patch/angular-ios9-uiwebview-patch.js"></script>
    <script src="lib/phoneformat/dist/phone-format-global.min.js"></script>
    <!-- endbower-->
    <script src="templates.min.js"></script>
    <script src="locale.de.js"></script>
    <script src="locale.en.js"></script>
    <script src="locale.es.js"></script>
    <script src="locale.ja.js"></script>
    <script src="locale.zh-cn.js"></script>
    <script src="locale.ru.js"></script>
    <script src="locale.fr.js"></script>
    <script src="cordova.js"></script>
    <script(src='bootstrap.js')</script>
  </head>
```

**Which Ionic Version?** 1.3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  Requiring external module babel-register
Gulp local:   CLI version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by danbucholtz** [comment]
Hi @dwilt,

Can you verify the path of the `ionic.bundle.js` file?  This doesn't seem like an Ionic issue necessarily.

Please let me know what you found.

Thanks,
Dan

**Comment by dwilt** [comment]
@danbucholtz thanks for the quick reply. I just verified that it is loading correctly on the page:

![screenshot 2016-04-28 09 34 25](https://cloud.githubusercontent.com/assets/1065539/14893478/75aeecb2-0d24-11e6-848f-4abb9c880109.png)

**Comment by danbucholtz** [comment]
Hmm, that is weird.  Can you try to recreate in a very simple application?  We have not seen that before.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by bradanlane** [comment]
I just hit this issue. My code was working before I 'minified it. Then this occurred. Usually the common miny issue is with the controllers but in my case it is declaring the state handler. 

`Ionic Framewrok Version: 1.3.1`
