### ISSUE TITLE
Ionic 2 Feature Request: Make it possible to change the Back Button Text dynamically

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic#6371]
#### Short description of the problem:
To make it possible to change the language dynamically it is necessary to be able to change the Back Button Text dynamically as well.

#### What behavior are you expecting?
When the app user changes the language in the settings the app changes the language dynamically without restarting. This includes the Back Button Text.

**Steps to reproduce:**
1. Set the Back Button Text via Confg
2. Change the Back Button Text via Config
3. The change has no effect on Back Buttons in the views currently shown.
 

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by ch-weiss** [comment]
Hi,
as I see it is possible now:
http://ionicframework.com/docs/v2/api/components/nav/ViewController/#setBackButtonText

Thank you!

**Comment by Quixotical** [comment]
@ch-weiss the link you reference is dead

**Comment by Quixotical** [comment]
@ch-weiss I noticed the link you posted is no longer working. I am reposting the updated link for anyone else who stumbles upon this at midnight looking to change that pesky back buttons text :D 

https://ionicframework.com/docs/v2/api/navigation/ViewController/#setBackButtonText
