### ISSUE TITLE
feat: Feature Request: transitions to root page

### ISSUE THREAD

**Issue by rdesimone** [driftyco/ionic#6372]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>It would be nice to have an option which allows to get transitions when navigating to the root page. Could be especially useful when using a toolbar in the navbar. Something like this: nav.setRoot(Page, {animate: true});</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This is currently possible using the following:

```
this.nav.setRoot(Page, {}, {animate: true, direction: 'forward'});
```

The second param is any parameters to pass to the next view. See the [NavController docs](http://ionicframework.com/docs/v2/api/components/nav/NavController/#setRoot).

Is this what you're looking for?

**Comment by rdesimone** [comment]
@brandyscarney thanks a lot, this works!

Can this be used somehow to solve #5101 to get transitions for tab changes (Android)? Something like (click)="foo()" on an ion-tab and afterwards setting the new root page like described above.

**Comment by rdesimone** [comment]
@brandyscarney thanks again - forget the tab question - I think these are different stories.

Maybe some documentation is needed regarding the option param but otherwise the issue can be closed.

**Comment by brandyscarney** [comment]
@rdesimone Awesome! I created an issue to add better documentation behind it here: https://github.com/driftyco/ionic/issues/6372

Going to close this. :smile:

**Comment by rdesimone** [comment]
@brandyscarney I would like to come back on my question from above. Is is possible to control somehow the tab change with setRoot. Selecting an ion-tab will not automatically change the tab. The change will happen when setRoot is called. This is related to #5101. Thanks a lot for your help!
