### ISSUE TITLE
Inputs are not scrolled to when keyboard is shown.

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6373]
When a particular input is focused and the keyboard is shown, the view is not scrolled properly to the focused input. This sometimes causes the input to hide behind the keyboard.

Example Gif: (Please note the keyboard is not visible in the gif. Though it can be inferred through the view height variation)

![hides behind keyboard](https://cloud.githubusercontent.com/assets/6606965/14913146/7d690064-0e1e-11e6-9c25-49deb527b941.gif)

**UPDATE:** This issue is not just limited to Modal. I can also reproduce the same in` ion-view`  [Example Plunker](https://plnkr.co/edit/U6mhoB?p=preview)

Ionic Version: 1.3

**Comment by mhartington** [comment]
Hi there :smile: ! So in order to debug this, we're going to need an example to test. Please provide a [codepen](http://codepen.io/ionic/pen/Qwpxer) that we can load on to our devices and test. Thanks!

**Comment by shyamal890** [comment]
@mhartington Just updated with an example in [plunker](https://plnkr.co/edit/U6mhoB?p=preview)

**Comment by jgw96** [comment]
@shyamal890 Thanks for the plunker!

**Comment by shyamal890** [comment]
@danbucholtz Can you have a look at this issue please.

**Comment by jgw96** [comment]
Hello @shyamal890 ! I have reported this issue to our main Ionic 1.x developer and he will be taking a look at it. Thanks for opening an issue with us!

**Comment by danbucholtz** [comment]
Hi @shyamal890,

Thanks for submitting all of your issues.  It's very helpful.  This is in my backlog to look at.  I'll keep you posted.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @shyamal890,

If you remove auto-focus from your template, the issue goes away.

Thanks,
Dan

**Comment by shyamal890** [comment]
@danbucholtz I removed auto-focus from the template, however, the issue is still there. The field above the selected one is focused to.

**Comment by jgw96** [comment]
@daveshirman could you provide a plunker that reproduces this issue? Thanks!

**Comment by daveshirman** [comment]
yep, here you go: http://plnkr.co/edit/CVsJCpQMVRJoMuF8Sd9M?p=preview

but you'd need to run this on an Android device obviously.

I was testing on a Nexus 5 and Samsung Galaxy Note 4 FYI.
