### ISSUE TITLE
Back styles for button in mixin 

### ISSUE THREAD

**Issue by dev-pro-valentine-efimov** [driftyco/ionic#6374]
Why you have removed variables for `button-style` mixin in /ionic/scss/_mixins.scss ?

As I see in this file https://github.com/driftyco/ionic/blob/master/scss/_mixins.scss you have the commented code and all my buttons in the application have different styles. Was it removed because debugging ?

**Comment by jgw96** [comment]
Hello! Thanks for using ionic! Im sorry but im not sure i completely understand your issue as i need some more info. Would you mind filling out the issue template (that you see when you click new issue) and then posting that info here? Thanks again!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
