### ISSUE TITLE
bug: Ion-refresher content visible before fully pulling

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#6375]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Video to understand
https://drive.google.com/file/d/0B_2AM8ZhXhE9c1dOdXBCMTdXdjA/view

Code:

```
<ion-content padding class="main-feed">
	<ion-spinner id="middle" [hidden]="postsLoaded"></ion-spinner>
	
	<ion-refresher (refresh)="refreshPosts($event)">
		<ion-refresher-content
			pullingText="Pull to refresh"
			refreshingText="Refreshing...">
		</ion-refresher-content>
	</ion-refresher>
	
	<ion-card *ngFor="#post of posts">
		<div class="post-image">
			<ion-img [src]="post.picture"></ion-img>
		
			<button fab fab-right fab-top>
				<ion-icon name="star"></ion-icon>
			</button>
		</div>

		<ion-card-header>
			{{ post.title }}
		</ion-card-header>
		
		<ion-card-content>
			<p>
				{{ post.description }}
			</p>
		</ion-card-content>

		<ion-item>
			<ion-note item-left>
				{{ post.author }}
			</ion-note>
			<ion-note item-right>
				{{ post.publishAt }}
			</ion-note>
		</ion-item>
	</ion-card>
</ion-content>
```

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.3</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately, im not sure that i see an issue in the video you posted ): Unless im missing something (which is entirely possible) it looks like its working perfect. Would you mind explaining the issue a little bit more?

**Comment by MatanYed** [comment]
@jgw96 As you can see, the the icon and the words "Pull to refresh" is visible even when i didn't fully pulled the page.

**Comment by jgw96** [comment]
@MatanYed Thanks for the info! Here is the component docs on the refresher with a demo of how it is supposed to work. As you can see from that component demo the words and arrow start to appear even before you have completely pulled the page. From what i can see in your video, it seems to be the same behavior?

**Comment by MatanYed** [comment]
@jgw96 Yes it is the same behavior, the only difference here is the ion-list and ion-item.
ion-item has white background. if you change ion-item to transparent background you should see it here too.

**Comment by jgw96** [comment]
Hey! So i got my teammates to look at this too and it looks like the ion-refresher is working as expected. The only difference is that it shows up just a little sooner because your ion-item has a transparent background. If you change your ion-item back to the default white background then it will be just like the component demo above. I am gonna go ahead and close this as it does not look like an issue with the ion-refresh component. But, feel free to continue commenting ! Thanks for using ionic!

**Comment by Hesesses** [comment]
I was going to report this also as a bug, but when you set the background to white for example, then its working as it should

**Comment by jayzyaj** [comment]
Hi I have a bug in using ion-slides [here](https://github.com/ionic-team/ionic/issues/14796)
