### ISSUE TITLE
bug: Ion-img show only the first images

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#6376]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ion img show only the images that visible first, not the else.
video
https://drive.google.com/file/d/0B_2AM8ZhXhE9Zzl5MlpVWHFFRjg/view

code

<ion-content padding class="main-feed">
	<ion-spinner id="middle" [hidden]="postsLoaded"></ion-spinner>
	
	<ion-refresher (refresh)="refreshPosts($event)">
		<ion-refresher-content
			pullingText="Pull to refresh"
			refreshingText="Refreshing...">
		</ion-refresher-content>
	</ion-refresher>
	
	<ion-card *ngFor="#post of posts">
		<div class="post-image">
			<ion-img [src]="post.picture"></ion-img>
		
			<button fab fab-right fab-top>
				<ion-icon name="star"></ion-icon>
			</button>
		</div>

		<ion-card-header>
			{{ post.title }}
		</ion-card-header>
		
		<ion-card-content>
			<p>
				{{ post.description }}
			</p>
		</ion-card-content>

		<ion-item>
			<ion-note item-left>
				{{ post.author }}
			</ion-note>
			<ion-note item-right>
				{{ post.publishAt }}
			</ion-note>
		</ion-item>
	</ion-card>
</ion-content></span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
fix the css... add a minimum height to "post-image"

**Comment by MatanYed** [comment]
@manucorporat How should I make the placeholder image to be square?

**Comment by jgw96** [comment]
@MatanYed Hello! So the root of your issue is being caused by the fact that ion-img does not currently work outside of virtualScroll. We are currently working on modifying the ion-img component to work outside of virtualScroll (along with adding some cool features to it) and hope to have this resolved soon. Thanks for using ionic!

**Comment by MatanYed** [comment]
@jgw96 Great. So I should keep programming without worry about that.
thanks.
