### ISSUE TITLE
bug: Dark searchbar in iOS almost impossible to notice

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#6379]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>browser</span>

```
	<ion-toolbar dark>
		<ion-searchbar [(ngModel)]="searchQuery" (input)="getItems($event)"></ion-searchbar>
	</ion-toolbar>

```
Image (the left one):
http://s32.postimg.org/lst7y4qms/ionic_searchbar_ios_bug.jpg</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Thanks @MatanYed! I can reproduce this one: http://plnkr.co/edit/EOvlnLGNkmKxeGV2XzYr

**Comment by brandyscarney** [comment]
Thanks for the issue! I have fixed this and it will be in the `beta 9` release. If you'd like to check it out sooner I released a nightly version. :smile:

```
npm install --save ionic-angular@2.0.0-beta.8-201606092335
```
