### ISSUE TITLE
feat: Select text ellipsis. I need multi line select

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#6383]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://s32.postimg.org/qgn1cnhec/ionic_select_text_ellipsis.jpg

I really need multi line select.

I am copying my native app (android 4.x) to Ionic 2, and in the native android app there is select with multi line text.</span>

<span is-issue-template></span>

**Comment by MatanYed** [comment]
Is that easy: 
```
.alert-radio-label {
	text-overflow: initial;
	white-space: initial;
}
```

Anyway, it will be nice if it will be a feature...

**Comment by jgw96** [comment]
Hello @MatanYed ! Would you be able to post a picture of the functionality you are looking for? Thanks!

**Comment by MatanYed** [comment]
@jgw96 Sure, here:
http://i.imgur.com/yrY6jKW.png

**Comment by jgw96** [comment]
@MatanYed Awesome, thanks!

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#31
