### ISSUE TITLE
Bug:  Missing Fonts on clean bower install of Ionic 1.3

### ISSUE THREAD

**Issue by Wombatpm** [driftyco/ionic#6384]
I came across this when upgrading to 1.3

When my bower.json file is 
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
        "ionic": "^1.3.0"
  }
}

The folder www\lib\ionic\fonts  is missing.

if my bower.json file is 
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.3.0"
  }
}

everything is installed correctly.

**Comment by Wombatpm** [comment]
If you download the zip file from the CDN  everything is there.  Seems to be bower related.

**Comment by danbucholtz** [comment]
Hi @Wombatpm,

Thanks for letting us know.  We'll check it out further.  I do have the fonts in my `bower_components/ionic/release/fonts` directory but I will be the first to admit I'm a bower n00b.

Any thoughts on why this might be happening?

Thanks,
Dan

**Comment by Wombatpm** [comment]
I think I figured it out.  I had written my index.html file against ionic-bower#1.3.0 then cleared everything and installed ionic.  The path change to ionic/release/fonts  from ionic/fonts messed things up in my code because I was referencing the old css file. I'm a bower n00b as well. So you can close this issue as user error.  

One Question though:  Is there a reason that the angular dependencies are 1.4.3  for one file and 1.5.3  for another?

bower install ionic  uses this bower.json file
[https://github.com/driftyco/ionic/blob/master/bower.json](url)
```
{
  "name": "ionic",
  "version": "1.3.0",
  "codename": "delhi",
  "homepage": "https://github.com/driftyco/ionic",
  "authors": [
    "Max Lynch <max@drifty.com>",
    "Adam Bradley <adam@drifty.com>",
    "Ben Sperry <ben@drifty.com>"
  ],
  "description": "Advanced HTML5 hybrid mobile app development framework.",
  "main": [
    "css/ionic.css",
    "fonts/*",
    "js/ionic.js",
    "js/ionic-angular.js"
  ],
  "keywords": [
    "mobile",
    "html5",
    "ionic",
    "cordova",
    "phonegap",
    "trigger",
    "triggerio",
    "angularjs",
    "angular"
  ],
  "license": "MIT",
  "private": false,
  "dependencies": {
    "angular": "1.4.3",
    "angular-animate": "1.4.3",
    "angular-sanitize": "1.4.3",
    "angular-ui-router": "0.2.13"
  }
}
```

bower install driftyco/ionic-bower#1.3.0 uses this file instead
[https://github.com/driftyco/ionic-bower/blob/v1.3.0/bower.json](url)
```
{
  "name": "ionic",
  "version": "1.3.0",
  "codename": "delhi",
  "homepage": "https://github.com/driftyco/ionic",
  "authors": [
    "Max Lynch <max@drifty.com>",
    "Adam Bradley <adam@drifty.com>",
    "Ben Sperry <ben@drifty.com>"
  ],
  "description": "Advanced HTML5 hybrid mobile app development framework.",
  "main": [
    "release/css/ionic.css",
    "release/fonts/*",
    "release/js/ionic.js",
    "release/js/ionic-angular.js"
  ],
  "keywords": [
    "mobile",
    "html5",
    "ionic",
    "cordova",
    "phonegap",
    "trigger",
    "triggerio",
    "angularjs",
    "angular"
  ],
  "license": "MIT",
  "private": false,
  "ignore": [
    "**/.*",
    "CONTRIBUTING.md",
    "Gruntfile.js",
    "component.json",
    "config",
    "examples",
    "package.json",
    "release/js/angular",
    "release/js/angular-ui",
    "scripts",
    "test",
    "js/controllers",
    "js/ext",
    "js/utils",
    "js/views",
    "js/_license.js",
    "js/ionic.js"
  ],
  "dependencies": {
    "angular": "1.5.3",
    "angular-animate": "1.5.3",
    "angular-sanitize": "1.5.3",
    "angular-ui-router": "0.2.13"
  }
}
```

**Comment by danbucholtz** [comment]
Cool, thanks for contributing @Wombatpm.  Let me know if there is anything else I can help you with.

Thanks,
Dan
