### ISSUE TITLE
ionic-angular 2.0.0-beta.6 npm package has outdated typings

### ISSUE THREAD

**Issue by eugenpodaru** [driftyco/ionic#6388]
The ionic-angular@2.0.0-beta.6 npm package has outdated typings. This version of ionic depends on angular@2.0.0-beta.16 in which a few components (e.g. AppViewManager) were renamed. However the typings (e.g. /ionic/components/nav.d.ts) still import the old components.

**Comment by iignatov** [comment]
@eugenpodaru AFAIK `Ionic 2.0.0-beta.6` depends on `Angular 2.0.0-beta.15` and not on `beta.16`. There's a [bug in `Angular 2.0.0-beta.16`](https://github.com/angular/angular/issues/8237) which [breaks the app](https://forum.ionicframework.com/t/update-to-angular2-beta-16-token-must-be-defined-is-thrown/50452) and also a [change detection regression](https://github.com/angular/angular/issues/8242). Where have you found the dependency on `angular@2.0.0-beta.16`?

**Comment by eugenpodaru** [comment]
@iignatov Yes, you are right, it depends on angular@2.0.0-beta.15. I checked the package.json in the current branch and not the package.json in the actual release.

I downgraded to angular@2.0.0-beta-15 and it compiles again. Thanks and sorry :)

**Comment by GuillaumeM69** [comment]
npm install angular2@^2.0.0-beta.15 --save-exact
dev@ /Users/guillaume/Dev/
├── angular2@2.0.0-beta.17  extraneous
├── UNMET PEER DEPENDENCY es6-shim@^0.35.0
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.2
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6
└── UNMET PEER DEPENDENCY zone.js@^0.6.12

npm WARN angular2@2.0.0-beta.17 requires a peer of es6-shim@^0.35.0 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of zone.js@^0.6.12 but none was installed.

**Comment by GuillaumeM69** [comment]
How to install angular2@^2.0.0-beta.15 plz ?

**Comment by eugenpodaru** [comment]
@GuillaumeM69 You have to add those packages in the package.json as explicit dependencies for your application.
