### ISSUE TITLE
border-bottom should be changed to border-top when ion-toolbar is positioned bottom

### ISSUE THREAD

**Issue by Samuel-Pierce** [driftyco/ionic#6390]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

the border is on the bottom when it should be on the top when the toolbar is on the bottom of the screen

#### What behavior are you expecting?

the border to be on the top, not the bottom

**Steps to reproduce:**
1. set ion-toolbar to position="bottom"
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
 version 2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
@Samuel-Pierce Hello! Would you be able to provide a plunker that gives us an example of this issue please? Thanks!

**Comment by brandyscarney** [comment]
Also, could you give the exact version of Ionic you're using please? This should have been fixed in `beta.5` by this issue: https://github.com/driftyco/ionic/issues/5967

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
