### ISSUE TITLE
Ionic deploy fallback to old version after exit the app and relaunch.

### ISSUE THREAD

**Issue by wilsonmiz** [driftyco/ionic#6391]
I have update my app from 0.0.5 to 0.0.6 using the ionic deploy it works well, but after I exit and relaunch the app, it fallback to 0.0.5. I can do check update again but it always update failed.

#### What behavior are you expecting?
It should stay on the new version(0.0.6) after relaunch the app.

**Steps to reproduce:**
1. Check for update
2. Confirmed and do update
3. Update successfully
4. Exit the app and relaunch

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-platform-issues#96

**Comment by jgw96** [comment]
Hello! Since this issue was related to Ionic deploy instead of the Ionic framework i moved this issue to the appropriate repo. Feel free to continue the conversation over there. Thanks!
