### ISSUE TITLE
Feat - add list bouncing with VirtualScroll

### ISSUE THREAD

**Issue by galvanu** [driftyco/ionic#6394]
#### Short description of the problem:

List bouncing is not support when using virtual scroll
#### What behavior are you expecting?

List bouncing as exists in native scrolling without virtual scroll
#### Ionic info

Cordova CLI: 6.1.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X Yosemite
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by adamdbradley** [comment]
With iOS's UIWebView implementation this feature will probably not be added. Instead we recommend using the WKWebView plugin, and we'll keep working to improve virtual scroll, thanks.

http://blog.ionic.io/cordova-ios-performance-improvements-drop-in-speed-with-wkwebview/
