### ISSUE TITLE
VirtualScroll - adding scroll indicator

### ISSUE THREAD

**Issue by galvanu** [driftyco/ionic#6395]
#### Short description of the problem:

Scroll indicator is not shown when using virtual scroll on ion-list.
#### What behavior are you expecting?

Scroll indicator should appear in ion-list
#### Ionic info

Cordova CLI: 6.1.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X Yosemite
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
@galvanu Hello! Thanks for opening an issue with us! Would you mind explaining a little more about what you mean by scroll indicator?

**Comment by galvanu** [comment]
Sure, at the side of list (right side) when scrolling you should see a small bar indicator indicates the relative overall vertical position at the list. if you have list of 100 items and you item number 50 is currently displayed then this vertical indicator should be displayed at the center of the list.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#224
