### ISSUE TITLE
Ion-Item CSS Bug: Height difference if an ion-item is empty 

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6396]
Height difference between empty `ion-item` and filled one. Even if the `ion-item` is empty the height should remain consistent.

![i](https://cloud.githubusercontent.com/assets/6606965/14943467/e0f4039c-0ff7-11e6-953f-b3758a030815.PNG)

Check out the [Plunker Example](https://plnkr.co/edit/vhUmo9?p=preview)

**Which Ionic Version?** 1.3.0
**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.1.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hey @shyamal890 ! Thanks for opening an issue with us. The only issue i see with this is that there is no real "standard height" for an `ion-item`. It simply expands depending on how much content is in it (and the height, padding, margin etc for those elements inside). So if you have a list with a bunch of ion-items they are not guaranteed to all have the same height, some may have different content than the others. So im not sure how we could set an empty `ion-item` to a consistent size, when there is no real "consistent" size for an `ion-item`. Would love to hear your thoughts on this, as i could be completely wrong in my thinking! Thanks again!

**Comment by shyamal890** [comment]
Hmm... I just checked again. I see that if the string is longer than the length available, then the text is ellipsised. This means an `ion-item` will not have more than one line text if there is only string input in the `ion-item`.

![i](https://cloud.githubusercontent.com/assets/6606965/14961166/e59e67ac-10b5-11e6-95ac-01c22c9b908f.PNG)


To be exact these are the css properties set for `ion-item`:

```
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
```

So by this logic, I think it is prudent to have a `min-height` setting on the `ion-item` given if, content of `ion-item` is **only a string**.

**Comment by danbucholtz** [comment]
Hi @shyamal890,

This is a decent idea I guess but what is the use case for rendering an empty ion-item?

Thanks,
Dan

**Comment by shyamal890** [comment]
Imagine a to-do app like Asana. There are chances that a user may create an empty string item.
 
 
  On Fri, 6 May, 2016 at 9:48 a.m., Dan Bucholtz<notifications@github.com> wrote:   
Hi @shyamal890,

This is a decent idea I guess but what is the use case for rendering an empty ion-item?

Thanks,
Dan

**Comment by danbucholtz** [comment]
Understood.  There are too many gotchas with this so we are just going to leave it the way it is for now.  You can set a min-height by using a css class on your element.

Thanks,
Dan
