### ISSUE TITLE
Ionic History broken with v1.3.0

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6398]
`$ionicHistory.goBack()` is broken with v1.3.0 . Please try pressing the back button in `home.sub2` view in the plunker below.

[Example Plunker](https://plnkr.co/edit/ZdZtDd?p=preview)
 

**Which Ionic Version?** 1.3.0

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.1.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.4.3

**Comment by danbucholtz** [comment]
This will be resolved in 1.3.1.  It works with the nightly build.

Thanks,
Dan
