### ISSUE TITLE
Ionic 1.3.0 issues

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6399]
I wonder if Ionic 1.x is still in beta given 1.3.0 breaks a lot of features that used to work in 1.2.4. Not just that, I have even noticed that there are a lot of keyboard issues too (I thought this must be the USP of Ionic).

Frankly, I expected Ionic 1.x to be stable and imagined it would reduce a lot of extra work. However, given that I have to double check everytime I encounter a problem and wonder if this is an Ionic bug or a mistake on my end. I am starting to think whether Ionic is really saving my time.

Keyboard Issue that I faced: 
https://github.com/driftyco/ionic/issues/6373

These are just a few things that 1.3.0 breaks:
https://github.com/driftyco/ionic/issues/6398
https://github.com/driftyco/ionic/issues/6389
https://github.com/driftyco/ionic/issues/6378

**Comment by Manduro** [comment]
I agree. The 1.3.0 seems more like a 1.2.5 pre-release. How much I appreciate the progress on 2.x, it goes at a big cost of 1.x. This update was rushed out of the door it seems.

**Comment by emps** [comment]
just stay with 1.2.4 till new update comes, about keyboard use scroll="true"

**Comment by shyamal890** [comment]
@emps Ya reverting to 1.2.4. Btw can you please try out https://github.com/driftyco/ionic/issues/6373 's plunker and tell me if the same can be reproduced on your side?

**Comment by jgw96** [comment]
Hello everyone! Thanks for your concern with these issues, i have reported them to our main Angular 1.x developer and he is gonna take a look at them today. Also, @shyamal890 we really appreciate the plunkr's, they make it much easier to debug. Thanks for using Ionic!

**Comment by Langstra** [comment]
I am guessing this is also one of the same problems. #6377 Does this plnkr help?

**Comment by danbucholtz** [comment]
Since this issue is just talking about other issues, we will work in those other issue threads and close this.

Thanks,
Dan
