### ISSUE TITLE
bug: Content moves up using keyboard-attach

### ISSUE THREAD

**Issue by thedoorbell** [driftyco/ionic#6400]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a simple chat window with input field in footer. So when I tap on input I want footer to be attached to keyboard when it shows like in all messengers. But when I do this (using both Android and iOS platforms) all content (including footer) moves up. I was looking for decision all day so I try all the methods from the internent and they're not work...
Also when keyboard up I can scroll ALL content including sidemenu up and down (this is so weird)...

View when keyboard hide - https://pp.vk.me/c630921/v630921196/25e28/pu59fQ-Q-V0.jpg
View when keyboard up - https://pp.vk.me/c630921/v630921196/25e31/CckyrNbpwOU.jpg</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to do something i will urge that you ask this question on our forum (forum.ionicframework.com). There are some awesome devs on there that will be able to help you. Thanks for using Ionic!
