### ISSUE TITLE
$ionicScrollDelegate.scrollBottom(true) makes finger scrolling unresponsive Android 6.0.1

### ISSUE THREAD

**Issue by gregvis** [driftyco/ionic#6402]
#### Short description of the problem:
After i call $ionicScrollDelegate.scrollBottom(true), I cannot scroll the view with my finger on Android 6.0.1. If I omit the "true" animation, then it's fine. 

#### What behavior are you expecting?
I expect to be able to use finger scrolling after calling scrollBottom(true). 

**Steps to reproduce:**
1. Call $ionicScrollDelegate.scrollBottom(true).
2. Try to scroll with your finger.

**Which Ionic Version?** 1.3

#### Codepen that shows an example of your issue

http://codepen.io/gregvis/pen/reQYpB

**Comment by gregvis** [comment]
Can't reproduce in this codepen example. Something else is causing this in my production app. I will have to investigate further. Closing for now.

**Comment by s4frul** [comment]
Hi, any solution for this? Its true when tried to set to 'true' on $ionicScrollDelegate.scrollBottom() or  top(), on android manual scrolling is freezing.. weird.. :(
