### ISSUE TITLE
Ionic 2 Beta 6 Side Menu Animation is Slower than in 1.3

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#6404]
#### Short description of the problem:
The side menu animation in Ionic 2 Beta 6 is slower than in Ionic 1.3.

#### What behavior are you expecting?
The side menu animation in Ionic 2 would be just as fast as in Ionic 1 which feels closer to native.

**Steps to reproduce:**
1. Create an Ionic 1 project: $ionic start Menu1 sidemenu
2. Create an Ionic 2 project: $ionic start Menu2 sidemenu --v2 --ts
3. Run both apps on a physical iOS device (I used an iPhone 6 Plus)
4. Tab the nav menu at the top to expand the sidebar. In 1.3 the animation is smooth and native-feeling. In 2b6 it is choppy compared to 1.3.
6. Swipe slowly to move the side menu back and forth.  In 1.3 the animation is smooth and native-feeling. In 2b6 it is choppy compared to 1.3.

**Which Ionic Version?** 1.x or 2.x
2 Beta 6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us and thanks for your observations. We are constantly working on improving the performance of Ionic 2 and this will get better in the future. (:

**Comment by jgw96** [comment]
Would you mind telling me what device you are using for testing?

**Comment by tones411** [comment]
IPhone 6 Plus

-- Anthony

**Comment by aplimovil** [comment]
We're experiencing this as well on Ionic 2, using an iPhone 5S (quite fast), on a very basic app. You can try it out on Ionic View with app ID 59cdccad.

There's also ANOTHER ISSUE: A bug that causes the sidemenu icon and it's inner items to require a double (or sometimes triple) tap in order for the sidemenu to open or the items to open the corresponding view. This doesn't happen when using the swipe gesture, though.

Only when tapping the "sidemenu icon". When using the swipe gesture the sidemenu opens/closes normally and sidemenu items react with a single tap, albeit with an aprox. 500ms delay in opening the corresponding views, which is related to the original issue reported.

However, why was this issue closed? The problem persists, and just saying "this will get better in the future" doesn't help at all. Having a simple UI component like the side menu being slower than in a previous Ionic version is just going backwards.

What's the underlying cause of this issue actually? It doesn't make sense that the sidemenu is slower on this new version and fast on Ionic 1. If you could give more info on the reason of this slowness perhaps we could help fixing it using a PR.

Or will this be fixed on the next beta?

**Comment by aaronklaser** [comment]
I am on beta 11 and have the exact same issue as @aplimovil 

Works find locally in browser, but it requires 2-3 clicks on iOS emulator or device and is VERY VERY delayed. 

Was there any solution or workaround for this?

**Comment by aplimovil** [comment]
@aaronklaser this issue is also reported on issues #6405 #6645 and #7600 yet the Ionic team has CLOSED all of those issues including this and the issue persists since beta 7 :S

Ionic team, we beg you not to dismiss this critical bug, it is preventing us from shipping our app and I'm sure it's affecting a lot of other people! Please!

**Comment by guanxi55nba** [comment]
I am on **beta 11** and also experiences this issue. 
It happened on IOS, **both emulator, and device ( iphone 5s )**
