### ISSUE TITLE
input Date doesn't show widget on chrome desktop

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6406]
_From @awebdeveloper on April 5, 2016 13:3_

Plz find all the details here

https://forum.ionicframework.com/t/problem-with-date-picker-when-viewing-in-a-desktop-browser/20943

_Copied from original issue: driftyco/ionic-cli#900_

**Comment by jgw96** [comment]
Hello! As this issue is an issue with the Ionic framework and not the Ionic-cli i will be moving this issue to the correct repo. Feel free to continue the discussion over there!

**Comment by danbucholtz** [comment]
We do not support the web for Ionic 1.  We will do this for Ionic 2.

Thank you for contributing to Ionic.

Thanks,
Dan
