### ISSUE TITLE
Enhancement - image caching feature

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic#6407]
It would be great if a Ionic provided a caching service for images. When we have long lists and each item contains images it is a lot of loading from external servers which are required. When the user closes the app and opens it again all those image need to be loaded from the server again. It would be great to have a caching service which we could specify a time to live for an image (e.g 2 hours) and that image would be cached for 2 hours in local storage and wouldn't require an HTTP call until then for the updated image. So even if the app is closed and reopened that image would still be in cache.

For Ionic2.

**Comment by leoruhland** [comment]
Hi @susanlinsfu,
I've had the same problem as you.
I may be wrong, but I don't think this type of functionality will be integrated into the ionic.

A list of open source projects that helped me a lot in this regard (Remembering, I am not responsible for any of it and have no guarantee of its operation):

https://github.com/BenBBear/ionic-cache-src
https://github.com/andrewmcgivery/ionic-ion-imageCacheFactory
https://github.com/chrisben/imgcache.js/

**Comment by susanlinsfu** [comment]
@leoruhland Sorry I forgot to mention this is for Ionic2, the provided link unfortunately are for Ionic1. Is there any reason why you don't think this would/should be integrated into Ionic?

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#32
