### ISSUE TITLE
V2 - Beta 6 - Navigation issue with android back button in modal with tabs 

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#6409]
#### Short description of the problem:
Inside a **Tabs component**, navigate from a **page 1** to a **page 2**, then open a modal from here, click on the android back button, the modal doesn't close as it should be but actually navigates back to the **page 1** in background. If you close the modal, you will be on **page 1**.
![bug_tabs_modal_nav](https://cloud.githubusercontent.com/assets/216573/14973718/a0027b38-112e-11e6-87db-ac9228c814d5.gif)

#### What behavior are you expecting?
The back button should close the modal as it does if you are executing the same code outside a **Tabs** component

```ts
import {Page,NavController,Modal} from 'ionic-angular';

import {HostListener} from "angular2/core";


@Page({
  template: `
  <ion-navbar *navbar>
    <ion-title>Page 1</ion-title>
  </ion-navbar>

  <ion-content padding>
    <h1>I'm Page 1</h1>
    <button>Navigate to page 2</button>

  </ion-content>
  `,
})
export class Page1 {
  constructor(private nav:NavController) {

  }

  @HostListener('click', ['$event'])
  navitageToPage2(){
      this.nav.push(Page2);
  }
}



@Page({
  template: `
  <ion-navbar *navbar>
    <ion-title>Page 2</ion-title>
  </ion-navbar>

  <ion-content padding>
    <h1>I'm Page 2</h1>
    <button secondary>Open modal</button>
  </ion-content>
  `,
})
export class Page2 {
  constructor(private nav:NavController) {

  }

  @HostListener('click', ['$event'])
  openModal(){
    let modal = Modal.create(MyModal);

    this.nav.present(modal);
  }
}


@Page({
  template: `
  <ion-toolbar>
    <ion-title>My Modal</ion-title>
    <ion-buttons end>
      <button nav-pop>
        <ion-icon [name]="'close'"></ion-icon>
      </button>
    </ion-buttons>
  </ion-toolbar>

  <ion-content padding>
    <p *ngIf="!clicked">Watch the click on the back button below </p>
    <p *ngIf="clicked" danger>Nothing happened</p>
    <p style="
    position: fixed;
    bottom: -38px;
    left: 64px;
    font-size: 47px;">
    <!--Basic: auto-select the icon based on the platform -->
    <ion-icon name="arrow-down"></ion-icon>
    </p>
  </ion-content>
  `,
})
export class MyModal {
  clicked:boolean = false;
  constructor(  ) {
    document.addEventListener('backbutton',()=>{
      this.clicked = true;
    });
  }
}

```

**Which Ionic Version?** 2.x @ beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Good catch, I can also reproduce this with my test apps.

**Comment by JumBay** [comment]
I've also notice another issue. I think it may be related to this one so I don't create another one but let me know if I should.

If you run the provided code in iOS, you will notice that the tabs are still visible when you navigate from **page 1** to **page 2**. 
If you use **nav.rootNav.push()** instead of **nav.push()** it fixes that, but on android, clicking to the back button will cause the app to exist.

**Comment by JumBay** [comment]
This issue is still present in beta 7

**Comment by adamdbradley** [comment]
This should be fixed in the next release: https://github.com/driftyco/ionic/commit/9f293e85496404364c08a8275c04f52d19dacea6

Thanks!

**Comment by daveshirman** [comment]
This has happened again in beta 9 if you override the the backbutton like so:

```
this.platform.registerBackButtonAction(() => {
      var nav = this.getNav();
      if (nav.canGoBack()) {
        nav.pop();
      }
});
```

This doesn't close a modal window if one is open as expected. Instead, the page in the background navigates back as originally posted above.
