### ISSUE TITLE
feat: Add support for Angular2 template compiler

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6411]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please consider adding https://www.npmjs.com/package/angular2-template-compiler step into building process for improved performance.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey @ErkoKnoll ! We are currently going over this and all the other changes in the angular 2 world lately so expect updates soon! I'll keep this issue open so that I can update the community on this. Thanks for using Ionic!

**Comment by tonyawad88** [comment]
+1

**Comment by adamdbradley** [comment]
Yes we are working with the angular team so that Ionic works well with their compiler.

**Comment by msaelices** [comment]
@adamdbradley why is the reason for closing this issue? is there any changes in ionic2 about this?

**Comment by fifafu** [comment]
Is it already possible to use the compiler with Ionic 2? (I believe this would speed up Android navigation a lot)

**Comment by jgw96** [comment]
@fifafu We are working directly with the Angular team on getting this implemented and actually have some team members flying out to google this week to speed up the process. We are currently waiting for the Angular 2 RC5 release which has some necessary changes for offline compiling, but  you can be assured that this is top priority and are working on it as fast as possible. Thanks for using Ionic!
