### ISSUE TITLE
bug: onPageWill/DidEnter not fired from action sheet

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6413]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x beta.6</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When page is pushed in from action sheet handler callback then onPageWillEnter or onPageDidEnter is not fired for that page. If pushed without action sheet button then it works as expected.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @ErkoKnoll thanks for opening an issue with us! Would you mind making a plunker or codepen that we can use to repro this issue please? Thanks!

**Comment by ErkoKnoll** [comment]
Hi,

I created plunker: http://plnkr.co/bHbcgxBCIH0n58j6MV4N. Surprisingly it works in the desktop. I haven't tested my version on desktop because I'm unable to. I guess it is not that important since I moved my logic to controller as a workaround.

**Comment by jgw96** [comment]
Hello @ErkoKnoll ! As you stated it seems to work fine on desktop. Were you using Android or IOS when you noticed the issue?

**Comment by ErkoKnoll** [comment]
Hi, I noticed the bug on Android.

**Comment by jgw96** [comment]
Hello @ErkoKnoll! what version of Android are you testing with?

**Comment by ErkoKnoll** [comment]
Hi,

Android version is 5.1.

**Comment by jgw96** [comment]
Hello @ErkoKnoll . So i made a little app to test this and it seems to be working fine for me. [Here](https://github.com/jgw96/ActionSheetLcEvents) is a repo containing the demo app. Simply `git clone` that repo, run `npm install` and then run it on your device and you should see two alerts when the second page is pushed from the action sheet. One alert is fired in `onPageDidEnter()` and the other in `onPageWillEnter()`. Thanks again!

**Comment by ErkoKnoll** [comment]
Thanks for testing it out. I guess it is something weird in my setup but since I moved my stuff to constructor it does not bother me and this issue can be closed.

**Comment by jgw96** [comment]
Awesome, no problem at all. Thanks for using Ionic!
