### ISSUE TITLE
Cannot deploy Ionic 2 Cute Puppies to Android 4.4.2 (LG Sporty)

### ISSUE THREAD

**Issue by mchapman** [driftyco/ionic#6414]
#### What behavior are you expecting?
I was expecting the app to come up, but I got a splash screen followed by a white screen

**Steps to reproduce:**
* `ionic start cutePuppyPics --v2`
* `cd cutePuppyPics/`
* `ionic plugin add cordova-plugin-crosswalk-webview`    
Output is:

> WARN: ionic.config.js has been deprecated, you can remove it.
> Plugin "cordova-plugin-crosswalk-webview" already installed on android.
> Saving plugin to package.json file

* `ionic run android`     
Output is:

> WARN: ionic.config.js has been deprecated, you can remove it.
> 
> Running 'run:before' gulp task before run
> [16:12:27] Starting 'clean'...
> [16:12:27] Finished 'clean' after 4.99 ms
> [16:12:27] Starting 'build'...
> [16:12:27] Starting 'sass'...
> [16:12:27] Starting 'html'...
> [16:12:27] Starting 'fonts'...
> [16:12:27] Starting 'scripts'...
> [16:12:27] Finished 'scripts' after 27 ms
> [16:12:27] Finished 'html' after 31 ms
> [16:12:27] Finished 'fonts' after 32 ms
> [16:12:28] Finished 'sass' after 615 ms
> [16:12:34] Finished 'build' after 7.25 s
> [16:12:34] Starting 'run:before'...
> [16:12:34] Finished 'run:before' after 5.32 μs
> 
> • You're trying to build for android, but don't have the platform installed yet.
> ∆ Installing android for you.
> √ Installed platform android
> Installing cordova-plugin-device
> Installing cordova-plugin-console
> Installing cordova-plugin-whitelist
> Installing cordova-plugin-splashscreen
> Installing cordova-plugin-statusbar
> Installing ionic-plugin-keyboard
> Running command: /home/mark/hooks/after_prepare/010_add_platform_class.js /home/mark
> add to body class: platform-android
> Running command: /home/mark/hooks/after_prepare/delete_test_assets.js /home/mark
> Test build @ platforms/android/assets/www/build/test does not exist for removal
> ANDROID_HOME=/home/mark/.local/share/umake/android/android-sdk
> JAVA_HOME=/usr/lib/jvm/java-8-oracle
> No target specified, deploying to device 'CQAQMJ6L4545PNPF'.
> null
> embedded
> org.xwalk:xwalk_core_library:17+
> :preBuild UP-TO-DATE
> :preArmv7DebugBuild UP-TO-DATE
> :checkArmv7DebugManifest
> :preX86DebugBuild UP-TO-DATE
> :CordovaLib:preBuild UP-TO-DATE
> :CordovaLib:preDebugBuild UP-TO-DATE
> :CordovaLib:compileDebugNdk UP-TO-DATE
> :CordovaLib:compileLint
> :CordovaLib:copyDebugLint UP-TO-DATE
> :CordovaLib:mergeDebugProguardFiles UP-TO-DATE
> :CordovaLib:packageDebugRenderscript UP-TO-DATE
> :CordovaLib:checkDebugManifest
> :CordovaLib:prepareDebugDependencies
> :CordovaLib:compileDebugRenderscript UP-TO-DATE
> :CordovaLib:generateDebugResValues UP-TO-DATE
> :CordovaLib:generateDebugResources UP-TO-DATE
> :CordovaLib:packageDebugResources UP-TO-DATE
> :CordovaLib:compileDebugAidl UP-TO-DATE
> :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> :CordovaLib:generateDebugAssets UP-TO-DATE
> :CordovaLib:mergeDebugAssets UP-TO-DATE
> :CordovaLib:processDebugManifest UP-TO-DATE
> :CordovaLib:processDebugResources UP-TO-DATE
> :CordovaLib:generateDebugSources UP-TO-DATE
> :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> :CordovaLib:processDebugJavaRes UP-TO-DATE
> :CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
> :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> :CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
> :CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
> :CordovaLib:bundleDebug UP-TO-DATE
> :prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
> :preArmv7ReleaseBuild UP-TO-DATE
> :preX86ReleaseBuild UP-TO-DATE
> :CordovaLib:preReleaseBuild UP-TO-DATE
> :CordovaLib:compileReleaseNdk UP-TO-DATE
> :CordovaLib:copyReleaseLint UP-TO-DATE
> :CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
> :CordovaLib:packageReleaseRenderscript UP-TO-DATE
> :CordovaLib:checkReleaseManifest
> :CordovaLib:prepareReleaseDependencies
> :CordovaLib:compileReleaseRenderscript UP-TO-DATE
> :CordovaLib:generateReleaseResValues UP-TO-DATE
> :CordovaLib:generateReleaseResources UP-TO-DATE
> :CordovaLib:packageReleaseResources UP-TO-DATE
> :CordovaLib:compileReleaseAidl UP-TO-DATE
> :CordovaLib:generateReleaseBuildConfig UP-TO-DATE
> :CordovaLib:generateReleaseAssets UP-TO-DATE
> :CordovaLib:mergeReleaseAssets UP-TO-DATE
> :CordovaLib:processReleaseManifest UP-TO-DATE
> :CordovaLib:processReleaseResources UP-TO-DATE
> :CordovaLib:generateReleaseSources UP-TO-DATE
> :CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
> :CordovaLib:processReleaseJavaRes UP-TO-DATE
> :CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
> :CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
> :CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
> :CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
> :CordovaLib:bundleRelease UP-TO-DATE
> :prepareComAndroidSupportSupportV42400Alpha2Library UP-TO-DATE
> :prepareOrgXwalkXwalk_core_library174644810Library UP-TO-DATE
> :prepareArmv7DebugDependencies
> :compileArmv7DebugAidl UP-TO-DATE
> :compileArmv7DebugRenderscript UP-TO-DATE
> :generateArmv7DebugBuildConfig UP-TO-DATE
> :generateArmv7DebugAssets UP-TO-DATE
> :mergeArmv7DebugAssets UP-TO-DATE
> :createXwalkCommandLineFileArmv7Debug
> :generateArmv7DebugResValues UP-TO-DATE
> :generateArmv7DebugResources UP-TO-DATE
> :mergeArmv7DebugResources UP-TO-DATE
> :processArmv7DebugManifest UP-TO-DATE
> :processArmv7DebugResources UP-TO-DATE
> :generateArmv7DebugSources UP-TO-DATE
> :compileArmv7DebugJavaWithJavac UP-TO-DATE
> :compileArmv7DebugNdk UP-TO-DATE
> :compileArmv7DebugSources UP-TO-DATE
> :transformClassesWithDexForArmv7Debug UP-TO-DATE
> :mergeArmv7DebugJniLibFolders UP-TO-DATE
> :transformNative_libsWithMergeJniLibsForArmv7Debug UP-TO-DATE
> :processArmv7DebugJavaRes UP-TO-DATE
> :transformResourcesWithMergeJavaResForArmv7Debug UP-TO-DATE
> :validateDebugSigning
> :packageArmv7Debug UP-TO-DATE
> :zipalignArmv7Debug UP-TO-DATE
> :assembleArmv7Debug UP-TO-DATE
> :cdvBuildDebug UP-TO-DATE
> 
> BUILD SUCCESSFUL
> 
> Total time: 1.521 secs
> Built the following apk(s): 
> 	/home/mark/platforms/android/build/outputs/apk/android-debug.apk
> Using apk: /home/mark/platforms/android/build/outputs/apk/android-debug.apk
> LAUNCH SUCCESS
> 

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Debugger output : 

> I/ActivityManager(  804): Start proc com.ionicframework.myapp107445 for activity com.ionicframework.myapp107445/.MainActivity: pid=4084 uid=10212 gids={50212, 3003}
> D/dalvikvm( 4084): Late-enabling CheckJNI
> D/HyLog   ( 4084): I : /data/font/config/sfconfig.dat, No such file or directory (2)
> D/HyLog   ( 4084): I : /data/font/config/dfactpre.dat, No such file or directory (2)
> D/HyLog   ( 4084): I : /data/font/config/sfconfig.dat, No such file or directory (2)
> I/dalvikvm( 4084): Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 1: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x0009
> I/dalvikvm( 4084): Could not find method android.app.Activity.requestPermissions, referenced from method org.apache.cordova.CordovaInterfaceImpl.requestPermission
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 26: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x000c
> I/dalvikvm( 4084): Could not find method android.app.Activity.requestPermissions, referenced from method org.apache.cordova.CordovaInterfaceImpl.requestPermissions
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 26: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x0006
> V/WebViewChromium( 4084): Binding Chromium to the background looper Looper (main, tid 1) {4201ca70}
> I/chromium( 4084): [INFO:library_loader_hooks.cc(112)] Chromium logging enabled: level = 0, default verbosity = 0
> I/BrowserProcessMain( 4084): Initializing chromium process, renderers=0
> W/chromium( 4084): [WARNING:proxy_service.cc(888)] PAC support disabled because there is no system implementation
> I/dalvikvm( 4084): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.engine.SystemCookieManager.<init>
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 234: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x0016
> I/dalvikvm( 4084): Could not find method android.webkit.CookieManager.flush, referenced from method org.apache.cordova.engine.SystemCookieManager.flush
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 229: Landroid/webkit/CookieManager;.flush ()V
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x0008
> W/dalvikvm( 4084): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
> W/dalvikvm( 4084): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
> I/dalvikvm( 4084): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.engine.SystemWebViewClient.onReceivedClientCertRequest
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 287: Landroid/webkit/WebViewClient;.onReceivedClientCertRequest (Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V
> D/dalvikvm( 4084): VFY: replacing opcode 0x6f at 0x001a
> W/dalvikvm( 4084): VFY: unable to find class referenced in signature (Landroid/webkit/PermissionRequest;)
> I/dalvikvm( 4084): Could not find method android.webkit.PermissionRequest.getResources, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onPermissionRequest
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 245: Landroid/webkit/PermissionRequest;.getResources ()[Ljava/lang/String;
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x000d
> I/dalvikvm( 4084): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onShowFileChooser
> W/dalvikvm( 4084): VFY: unable to resolve virtual method 250: Landroid/webkit/WebChromeClient$FileChooserParams;.createIntent ()Landroid/content/Intent;
> D/dalvikvm( 4084): VFY: replacing opcode 0x6e at 0x0000
> D/SystemWebViewEngine( 4084): CordovaWebView is running on device made by: LGE
> V/StatusBar( 4084): StatusBar: initialization
> D/dalvikvm( 4084): Note: class Lcom/lge/mdm/manager/ILGMDMDevicePolicyManager$Stub; has 372 unimplemented (abstract) methods
> I/BufferQueue( 4084): [unnamed-4084-0](this:0x56f67008,id:0,api:0,p:-1,c:-1) BufferQueue
> I/BufferQueue( 4084): [unnamed-4084-0](this:0x56f67008,id:0,api:0,p:-1,c:4084) consumerConnect consumer=(4084:com.ionicframework.myapp107445) controlledByApp=true
> I/BufferQueue( 4084): [unnamed-4084-0](this:0x56f67008,id:0,api:0,p:-1,c:4084) setConsumerName: unnamed-4084-0
> I/GLConsumer( 4084): [unnamed-4084-0](this:0x56f67670,api:0) GLConsumer
> I/GLConsumer( 4084): [unnamed-4084-0](this:0x56f67670,api:0) detachFromContext
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:0,p:4084,c:197) connect: api=1 producer=(4084:com.ionicframework.myapp107445) producerControlledByApp=true
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x56c22e48) (w:480, h:800, f:1)
> D/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) cancelBuffer: slot=0
> I/MaliEGL ( 4084): [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
> I/MaliEGL ( 4084): [Mali]max_allowed_dequeued_buffers=3
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) setBufferCount: count=4
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) getReleasedBuffers: returning mask 0xffffffff
> D/GraphicBuffer( 4084): close handle(0x56c22e48) (w:480 h:800 f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x56c094f8) (w:480, h:800, f:1)
> D/OpenGLRenderer( 4084): Enabling debug mode 0
> D/GraphicBuffer( 4084): create handle(0x577f39c0) (w:1216, h:832, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:0,p:4084,c:197) connect: api=1 producer=(4084:com.ionicframework.myapp107445) producerControlledByApp=true
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x5783cc88) (w:480, h:72, f:1)
> D/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) cancelBuffer: slot=0
> I/MaliEGL ( 4084): [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
> I/MaliEGL ( 4084): [Mali]max_allowed_dequeued_buffers=3
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) setBufferCount: count=4
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) getReleasedBuffers: returning mask 0xffffffff
> D/GraphicBuffer( 4084): close handle(0x5783cc88) (w:480 h:72 f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x5783cc88) (w:480, h:72, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:0,p:4084,c:197) connect: api=1 producer=(4084:com.ionicframework.myapp107445) producerControlledByApp=true
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x57846c68) (w:480, h:800, f:1)
> D/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) cancelBuffer: slot=0
> I/MaliEGL ( 4084): [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
> I/MaliEGL ( 4084): [Mali]max_allowed_dequeued_buffers=3
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) setBufferCount: count=4
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) getReleasedBuffers: returning mask 0xffffffff
> D/GraphicBuffer( 4084): close handle(0x57846c68) (w:480 h:800 f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x57847d50) (w:480, h:800, f:1)
> I/BufferQueue( 4084): [unnamed-4084-0](this:0x56f67008,id:0,api:0,p:-1,c:4084) setDefaultBufferSize: w=480, h=762
> I/BufferQueue( 4084): [unnamed-4084-0](this:0x56f67008,id:0,api:0,p:-1,c:4084) setDefaultBufferSize: w=480, h=762
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x57848be8) (w:480, h:72, f:1)
> W/MediatekClassFactory( 4084): Tablet not exist!, Get obj from default class
> W/MediatekClassFactory( 4084): Exception: java.lang.ClassNotFoundException
> D/MediatekClassFactory( 4084): null object during finding :  interface com.mediatek.common.telephony.IOnlyOwnerSimSupport
> D/OpenGLRenderer( 4084): Flushing caches (mode 0)
> D/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x435b45a0,id:24,api:1,p:4084,c:197) cancelBuffer: slot=1
> D/GraphicBuffer( 4084): close handle(0x5783cc88) (w:480 h:72 f:1)
> D/GraphicBuffer( 4084): close handle(0x57848be8) (w:480 h:72 f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x5784d8e8) (w:480, h:800, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x5784df70) (w:480, h:800, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x57868808) (w:480, h:800, f:1)
> E/AndroidProtocolHandler( 4084): Unable to open asset URL: file:///android_asset/www/build/js/es6-shim.min.js
> E/AndroidProtocolHandler( 4084): Unable to open asset URL: file:///android_asset/www/build/js/app.bundle.js
> E/AndroidProtocolHandler( 4084): Unable to open asset URL: file:///android_asset/www/build/js/angular2-polyfills.js
> D/JsMessageQueue( 4084): Set native->JS mode to OnlineEventsBridgeMode
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) [queue] fps:47.15, dur:1018.04, max:121.33, min:11.90
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x57af8918) (w:480, h:800, f:1)
> V/StatusBar( 4084): Executing action: _ready
> I/chromium( 4084): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
> I/chromium( 4084): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
> I/GraphicBuffer( 4084): allocate buffer (w:384 h:384 f:1) handle(0x598c1b88) err(0)
> I/GraphicBuffer( 4084): allocate buffer (w:384 h:384 f:1) handle(0x598c2898) err(0)
> I/GraphicBuffer( 4084): allocate buffer (w:384 h:384 f:1) handle(0x598c3510) err(0)
> I/GraphicBuffer( 4084): allocate buffer (w:384 h:384 f:1) handle(0x598c4210) err(0)
> I/GraphicBuffer( 4084): allocate buffer (w:64 h:128 f:1) handle(0x598c4f10) err(0)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) [queue] fps:0.91, dur:1102.39, max:1102.39, min:1102.39
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) new GraphicBuffer needed
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) [release] fps:50.40, dur:1011.91, max:55.06, min:15.77
> D/GraphicBuffer( 4084): create handle(0x57af89e0) (w:480, h:800, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) [queue] fps:52.32, dur:1012.98, max:63.60, min:7.73
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x421a25f8,id:23,api:1,p:4084,c:197) [release] fps:53.28, dur:1013.53, max:53.92, min:17.75
> D/OpenGLRenderer( 4084): Flushing caches (mode 0)
> D/GraphicBuffer( 4084): close handle(0x56c094f8) (w:480 h:800 f:1)
> D/GraphicBuffer( 4084): close handle(0x5784d8e8) (w:480 h:800 f:1)
> D/GraphicBuffer( 4084): close handle(0x5784df70) (w:480 h:800 f:1)
> D/GraphicBuffer( 4084): close handle(0x57868808) (w:480 h:800 f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) new GraphicBuffer needed
> D/GraphicBuffer( 4084): create handle(0x56c4fc28) (w:480, h:800, f:1)
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) [queue] fps:0.17, dur:11950.64, max:11913.86, min:36.78
> I/BufferQueue(  197): [com.ionicframework.myapp107445/com.ionicframework.myapp107445.MainActivity](this:0x4219cfa8,id:25,api:1,p:4084,c:197) [release] fps:0.17, dur:11955.25, max:11919.20, min:36.05
> 

 

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

Not applicable

**Run `ionic info` from terminal/cmd prompt:**
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.4.3
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind removing the crosswalk plugin, re-adding it, running `cordova build android` and then running `ionic run android` and seeing if that fixes it for you please?

**Comment by mchapman** [comment]
@jgw96 Done that - looks the same on the phone

**Comment by jgw96** [comment]
hmmmm, does `ionic serve` work? Also do you have a newer android device (android 4.4.4 and up) you could try it on and see if it has the same issue?

**Comment by mchapman** [comment]
`ionic serve` works fine.  Can't get it to work on either of my Android 5.1 devices either (white screen).  An older (beta 3) app is working fine.

**Comment by jgw96** [comment]
Can you remove the Crosswalk plugin (using the system webview steps here: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) and try to run the app on your devices then? Im trying to narrow it down to a crosswalk issue.

**Comment by mchapman** [comment]
I did a fresh cutePuppies and tried to install on 5.1.1, which also yielded a white screen.

**Comment by mchapman** [comment]
Looks like it doesn't work without Crosswalk, so the problem is elsewhere.  I ran
```
cordova plugin remove cordova-plugin-crosswalk-webview
cordova build --release -- --minSdkVersion=21
```
then lots of jarsigner stuff (which took a while to figure out) and when I ran `adb install -r` the resulting debug was:

> V/AlarmManager( 1107): Triggering alarm #0: Alarm{36731507 type 2 when 95336848 com.google.android.gms}
> I/ActivityManager( 1107): Start proc 3673:com.ionicframework.myapp107445/u0a159 for activity com.ionicframework.myapp107445/.MainActivity
> I/WebViewFactory( 3673): Loading com.google.android.webview version 50.0.2661.86 (code 266108650)
> I/cr_LibraryLoader( 3673): Time to load native libraries: 4 ms (timestamps 5942-5946)
> I/cr_LibraryLoader( 3673): Expected native library version number "50.0.2661.86", actual native library version number "50.0.2661.86"
> V/WebViewChromiumFactoryProvider( 3673): Binding Chromium to main looper Looper (main, tid 1) {2ff7162}
> I/cr_LibraryLoader( 3673): Expected native library version number "50.0.2661.86", actual native library version number "50.0.2661.86"
> I/chromium( 3673): [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
> I/cr_BrowserStartup( 3673): Initializing chromium process, singleProcess=true
> I/Adreno  ( 3673): QUALCOMM build                   : efd53e6, I3c94fdbbc3
> I/Adreno  ( 3673): Build Date                       : 09/09/15
> I/Adreno  ( 3673): OpenGL ES Shader Compiler Version: E031.25.03.09
> I/Adreno  ( 3673): Local Branch                     : 
> I/Adreno  ( 3673): Remote Branch                    : quic/LA.BF64.1.2.1.c1_rb1.21
> I/Adreno  ( 3673): Remote Branch                    : NONE
> I/Adreno  ( 3673): Reconstruct Branch               : NOTHING
> W/cr_media( 3673): Requires BLUETOOTH permission
> I/art     ( 3673): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
> I/art     ( 3673): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
> I/art     ( 3673): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
> I/art     ( 3673): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
> W/art     ( 3673): Suspending all threads took: 9.538ms
> I/art     ( 3673): Background partial concurrent mark sweep GC freed 2678(139KB) AllocSpace objects, 0(0B) LOS objects, 51% free, 976KB/2000KB, paused 11.084ms total 26.921ms
> D/cr_Ime  ( 3673): [InputMethodManagerWrapper.java:30] Constructor
> W/cr_AwContents( 3673): onDetachedFromWindow called when already detached. Ignoring
> D/cr_Ime  ( 3673): [InputMethodManagerWrapper.java:59] isActive: false
> D/SystemWebViewEngine( 3673): CordovaWebView is running on device made by: OnePlus
> D/cr_Ime  ( 3673): [InputMethodManagerWrapper.java:59] isActive: false
> D/OpenGLRenderer( 3673): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> V/StatusBar( 3673): StatusBar: initialization
> I/cr_Ime  ( 3673): ImeThread is not enabled.
> D/AppTracker( 3673): App Event: start
> E/libEGL  ( 3673): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
> I/OpenGLRenderer( 3673): Initialized EGL, version 1.4
> D/OpenGLRenderer( 3673): Enabling debug mode 0
> D/AbstractTracker( 3673): Event success
> W/cr_BindingManager( 3673): Cannot call determinedVisibility() - never saw a connection for the pid: 3673
> D/cr_Ime  ( 3673): [InputMethodManagerWrapper.java:59] isActive: false
> E/AndroidProtocolHandler( 3673): Unable to open asset URL: file:///android_asset/www/build/js/angular2-polyfills.js
> E/AndroidProtocolHandler( 3673): Unable to open asset URL: file:///android_asset/www/build/js/app.bundle.js
> E/AndroidProtocolHandler( 3673): Unable to open asset URL: file:///android_asset/www/build/js/es6-shim.min.js
> D/JsMessageQueue( 3673): Set native->JS mode to OnlineEventsBridgeMode
> V/StatusBar( 3673): Executing action: _ready
> I/Timeline( 3673): Timeline: Activity_idle id: android.os.BinderProxy@c41f9a5 time:73069575
>

**Comment by jgw96** [comment]
Hmmm Im going to move this issue to the Ionic-cli repo as i believe this issue is more related to the cli than the actual framework. Thanks for all the info and patience so far!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#979
