### ISSUE TITLE
Ionic is not defined, ionic serve with -t option

### ISSUE THREAD

**Issue by huttarichard** [driftyco/ionic#6419]
#### Short description of the problem:

Specific problem when running `ionic server` only for -t for specific platform

#### What behavior are you expecting?

Not to get error!
`Uncaught ReferenceError: ionic is not defined`

**Steps to reproduce:**
1. create starter project with --ts --v2
2. open browser

```
<script>
ionic && ionic.Platform && ionic.Platform.setPlatform("ios");
</script>
```

**Which Ionic Version?** 1.x or 2.x
2.x - 2.0.0-beta.25

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind explaining your issue a little more? So you ran `ionic serve -t` and you get an ionic is undefined error? Im also a little unsure of your javascript above? Do you have this code in your `index.html` ?

**Comment by huttarichard** [comment]
@jgw96 excatly, if you server files with `-t` command this code will appears in index.html

**Comment by jgw96** [comment]
Ahh ok. I can reproduce this issue. Im going to move this issue to the ionic-cli repo as i believe it is an issue with the ionic-cli instead of the ionic framework. Please feel free to continue the conversation on that repo!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#980
