### ISSUE TITLE
Typo in scss: bar-positive should be changed to bar-balanced

### ISSUE THREAD

**Issue by adsahay** [driftyco/ionic#6422]
#### Short description of the problem:

There's a typo for the `bar-balanced.bar-footer.` style. See [here](https://github.com/driftyco/ionic/blob/master/scss/_bar.scss#L99) - `bar-positive` should be changed to `bar-balanced` 

#### What behavior are you expecting?

`bar-balanced` instead of `bar-positive` in the gradient.

**Steps to reproduce:**
1. Create a demo app with a footer of style `bar-balanced`. 
2. Footer has a blue (`positive`) tinge on top.  

**Which Ionic Version?** 1.x or 2.x
1.3

**Comment by adsahay** [comment]
Code snippet to fix:

```
  &.bar-balanced {
    @include bar-style($bar-balanced-bg, $bar-balanced-border, $bar-balanced-text);
    &.bar-footer{
      background-image: linear-gradient(180deg, $bar-balanced-border, $bar-positive-border 50%, transparent 50%);
    }
  }
```

**Comment by danbucholtz** [comment]
@adsahay, thanks for letting us know.  I merged the PR.  Thanks for contributing to Ionic!  Nice work!

Thanks,
Dan
