### ISSUE TITLE
bug: Infinite-scroller not working inside a flexbox

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#6425]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

Once I placed infinite scroller and the list into flexbox which is scrollable instead of the main page then infinite-scroller won't fire when it reaches end of scrollable list items. I did it because I want to have the searchbar always visible when user scrolls through the list but it seems that infinite-scroller is watching scrolling position of the page not the element it is placed into.

It would be much appreciated if the infinite-scroller would be more dynamic, for example if the user has 2 lists that must have infinite scrollers on the same page then those lists have to be also put into some kind of container either a div or ion-scroll and I assume then the same problem would occur.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind putting together a plunker or codepen that we can use to reproduce this issue? Thanks!

**Comment by ErkoKnoll** [comment]
Here you go: https://embed.plnkr.co/l5nf66/. As you can see doInfinite() method is never fired. Works fine if you remove the div container.

**Comment by ErkoKnoll** [comment]
Hi,

Any progress on that end? Would be nice to get it reworked so it works inside other containers rather than window.

**Comment by ThorConzales** [comment]
This issue is not relevant anymore since the same functionality can now be achieved with headers.
