### ISSUE TITLE
Add Right To Left Support

### ISSUE THREAD

**Issue by Mahdi7s** [driftyco/ionic#643]
Title!

**Comment by fadifannoun** [comment]
Hi
is this feature implemented? I cannot apply it in my app and still getting animation problem for RTL apps.

**Comment by samaphp** [comment]
I think they fixed it at **framework7** if you interested. In ionic it's still an issue.

**Comment by vah7id** [comment]
Whats update ?

**Comment by sszdh** [comment]
Ping...

**Comment by fadifannoun** [comment]
Actually, You can come over it with some custom class implementation for you RTL content and keep the html direction LTR. By this simple move you can overwhelm the transition issue until it is fixed and released. For example create a class called `.rtl` or what every you want and set 'direction: rtl !important;' and 'text-align: right !important;'

Or you have another option which I did not have time to go with so I do not pass my deadline is to dig deep in the css source files and fix it your self.

**Comment by sszdh** [comment]
@fadifannoun, What about floats?

I think we should have some flag in CLI setup, somthing like `--rtl=true`

semantic-ui approach:
https://github.com/Semantic-Org/Semantic-UI/blob/master/README.md#international
