### ISSUE TITLE
feat: use url and navigator history for web deployment

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic#6430]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic2 is awesome and the ability to deploy it to a web-server to let users use it like a web app is super awesome !!!
But there is currently some troubles about web deployment : 
- no urls : when you refresh the app you loose your state, no deep-linking
- no browser history : when you click back button, you quit the app

There is an other tricky thing with states & urls : for some state, they need to come with some "navigation history". For example, in a master/detail context, if you link to an item detail you need to have the back button to come back to the list view even if you don't came from it...

I think this is a pretty much necessary thing to deploy to web...

Is this feature planned ?</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Yes it is on our roadmap to work with ng2's router. However, the router is still under development so we haven't hooked it up just yet. But absolutely, we plan on making it easy to also use a router. Thanks

**Comment by loicknuchel** [comment]
Great !
It's not on the roadmap, do you have any estimate ?

**Comment by lahdekorpi** [comment]
Is there any ETA for this?
This is an extremely important feature for as since we are skipping Cordova and rolling with our own Webview based solution. Not having a working back button is a deal-breaker.

Or as a workaround, would there be a possibility to call the back function from a running eval() code on the page?
