### ISSUE TITLE
feat: How to create scrollTo feature with virtualScroll?

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic#6431]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It could be cool to srcoll to a certain point of a list with a button. For example, in a conference app, scrolling to the current sessions will be very appreciated.

Usually to do that we need to identify the wanted item, get its absolute position and change the scroll position.
But, with virtualScroll, things are differents...
Is there a way to achieve that ? If no, it would be a great feature :)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality and not an issue with the framework i will urge that you ask this question on our forum (forum.ionicframework.com). There are alot of awesome devs in the community on there that would love to help you with this functionality (: Thanks for using Ionic!

**Comment by loicknuchel** [comment]
Hi @jgw96 I'll do that but I think implementing this would need some interactions with the virtualScroll system which are not available right now.
That's why it's a more feature than a support question to me...
