### ISSUE TITLE
Ionic doesn't indentify globally installed Gulp

### ISSUE THREAD

**Issue by MtDalPizzol** [driftyco/ionic#6435]
I have cordova@6.1.1 and gulp@3.9.1 installed globally, but running ```ionic serve``` throws this message to the terminal:

```
You have specified Gulp start up tasks in your ionic.project file.
However, you do not have Gulp installed globally. Please run `npm install -g gulp` (CLI v1.7.14)
```

Seems like Ionic isn't identifying Cordova and Gulp, but listing globally installed packages with ```npm ls -g --depth="0"``` outputs this:

```
/home/dalpizzol/.npm-global/lib
├── cordova@6.1.1
├── gulp@3.9.1
├── ionic@1.7.14
├── pm2@1.1.3
├── sails@0.12.3
└── webpack@1.13.0
```

**Which Ionic Version?** 1.7.14

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: Not installed
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue has to do with the ionic-cli and not the ionic framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#982
