### ISSUE TITLE
Loading.dismiss() not working when presenting Toast just after

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic#6437]
#### Description:
When calling `loadingComponent.dismiss()` and then `this.nav.present(toast);`, the loadingComponent is not dismissed. 

**Steps to reproduce:**
1. Call `loadingComponent.dismiss()`
2. Create and present a [Toast](http://ionicframework.com/docs/v2/components/#toast)

The *workaround* for this is by chaining these two steps, so the Toast is only presented when the `loadingComponent.dismiss()` is complete.
 

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
Node Version: v5.10.1
```

**Comment by danbucholtz** [comment]
Are you waiting for the promise to resolve?

```
loader.dismiss().then(()=>{
   this.nav.present(toast).then(() => {
      // the toast is displayed now
   });
})
```

**Comment by Artfloriani** [comment]
Hey Dan,

The way you mentioned is how I'm currently doing but I didn't know I was suppose to wait for the loder.dismiss() promise to resolve before calling the present(toast).  Is there any place where I can find more info about this?

Thanks,
Arthur

**Comment by danbucholtz** [comment]
We need to document transitions, etc better.  This is a WIP and it is a priority for us.  Just to confirm, is it working correctly after you wait for the first promise to resolve?

**Comment by Artfloriani** [comment]
Great to know!

It is working correctly when waiting for the first promise. Thank you for
the help!

**Comment by jgw96** [comment]
Hey! Since it looks like this issue was fixed im gonna go ahead and close this. Thanks for using Ionic!
