### ISSUE TITLE
Ionic 2 vertical slides doesn't work on load (android)

### ISSUE THREAD

**Issue by ozexpert** [driftyco/ionic#6438]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
slider with direction="vertical" not working when app is loaded.
however, if I change phone to horizontal mode, then it starts to work.
it works on a browser, but not on android device. (not tested with iOS)

#### What behavior are you expecting?
slide up should slide to next slide, but it returned back with the first slide.
however, changing device to horizontal mode then it starts to work.

**Steps to reproduce:**
1. add 2 ~ 3 slides and set direction as horizontal
2. when app is loaded, sliding up to see second slide didn't work
3. change device orientation then it works.

(tested with Galaxy Note 5 / OnePlus One)

```
slideOptions = {
    direction: 'vertical'
};
```

```
<ion-slides [options]="slideOptions">
    <ion-slide>
      one
    </ion-slide>
    <ion-slide>
      two
    </ion-slide>
    <ion-slide>
      three
    </ion-slide>
  </ion-slides>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
version 2 - beta 6

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you be able to provide a minimal example (plunker, codepen, or github repo) so that i can pull it down to my device and test please?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
