### ISSUE TITLE
Can we add on-hold reorder items without handles when reordering for ionic 2? 

### ISSUE THREAD

**Issue by 2arcz6** [driftyco/ionic#6439]
Hope we can do reorder without handles. God bless!

**Comment by manucorporat** [comment]
@2arcz6 I will close this issue since I want to keep all the v2 reorder progress in the same place #5595.
but yes! I am going to start working on reordering for v2 and it will support doing so without handlers, thanks for the idea!

**Comment by 2arcz6** [comment]
Alright I'm glad to hear that, Thanks. God Speed.
