### ISSUE TITLE
Custom close button in Ionic popup

### ISSUE THREAD

**Issue by Neotrixsx** [driftyco/ionic#6442]
I create a custom ionic popup for photo upload. My problem that I am not able to close that popup by using a corner close button. Please help me.

Which look like : 
![capture](https://cloud.githubusercontent.com/assets/7522102/15044954/88a6dccc-12f5-11e6-8a3f-f2a14de33eab.PNG)
Here my code: 

`            $scope.uploadPhoto = function () {
                var confirmPopup = $ionicPopup.show({
                    title: 'Upload Photo' + '<i class="ion-ios-close-outline popuoclose " ng-click="closePopup()"></i>',
                    scope: $scope,
                    buttons: [
                        {
                            text: '<i class="ion-ios-camera-outline thirty-text" ></i>',
                            type: 'button-positive',
                            onTap: function () {
                                $scope.takePicture();
                            }
                       },
                        {
                            text: 'Gallery',
                            type: 'button-positive',
                            onTap: function () {
                                $scope.galleryPicture();
                            }
                       },
                     ]
                });
                $scope.closePopup = function () {
                    confirmPopup.close();
                };
            };

`

when I inspect code I found that <i class="ion-ios-close-outline popuoclose "></i> it remove ` ng-click="closePopup()` from code. I am bit of confuse why it happen.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). There are alot of awesome devs on there that will be able to help you! Thanks for using Ionic!
