### ISSUE TITLE
Enhancement: Ability to specify transition for Modals and Pages in V2

### ISSUE THREAD

**Issue by Mobius77x** [driftyco/ionic#6443]
V2

I would like my Modal to 'pop up' into view (similar to Loading and Alert), rather than using default page transitions (e.g. slide in from bottom).

Similarly, developers should have some flexibility for specifying their page transitions on a case by case basis.

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We actually do have this functionality in Ionic 2 currently, it is just not documented yet (: The best way to see how to do it is to look at our tests in my opinion. [Here](https://github.com/driftyco/ionic/blob/2.0/ionic/components/modal/test/basic/index.ts#L69) you can see how to specify the transition used and [here](https://github.com/driftyco/ionic/blob/2.0/ionic/components/modal/test/basic/index.ts#L347) you can see how to make that new transition. I hope this helps you!

**Comment by Mobius77x** [comment]
Thanks. I got an error regarding a Directive missing an annotation so I will wait for it to be documented. (Please ensure the lack of documentation is not forgotten!)
