### ISSUE TITLE
$ionicNavBarDelegate.title("title"); not setting on history back

### ISSUE THREAD

**Issue by mikeipic** [driftyco/ionic#6444]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When you are setting the title using the $ionicNavBarDelegate.title() to set the pages title dynamically it works great.  When you navigate to a sub page of the tab, and then use the back button, it does not use the delegate.  It uses the title set in the state.

#### What behavior are you expecting?
ionicNavBarDelegate to set the state

**Steps to reproduce:**
1. Set the title using ionicNavBarDelegate 
2. Navigate to sub page
3. Click back auto back button

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
1.2.4

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.4.2

**Comment by jgw96** [comment]
Hey @mikeipic ! Thanks for opening an issue with us! Would you mind making a plunker that demonstrates this? Feel free to use the plunker that is linked to in the issue template!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
