### ISSUE TITLE
Binding dynamic value to style property throw error on iOS

### ISSUE THREAD

**Issue by lricoy** [driftyco/ionic#6447]
#### Short description of the problem:
When binding a dynamic value to the style property of an element a read-only exception is throw when running on a iOS device.
It works fine on android and the browser.

#### What behavior are you expecting?
No error or a warning on the documentation

**Steps to reproduce:**
1. Bind a dynamic value to a style property (`style="background-color: {{user.color}};`)
2. Run on iOS
3. View the debug log

```
ERROR:    <div class="user-avatar" style="background-color: {{user.color}};">
WORKS:    <div class="user-avatar" [ngStyle]="{'background-color': user.color}">

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

 

**Which Ionic Version?** 1.x or 2.x
2.beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by iignatov** [comment]
@lricoy IMHO this has nothing to do with Ionic as this functionality is provided/handled by Angular. I believe that you should use either `[ngStyle]` or `[style.background-color]` instead. Maybe a warning should be added to the docs _(however maybe to the Angular docs)_.

**Comment by jgw96** [comment]
Hello! I am in agreement with @iignatov. I believe that you should use `[ngStyle]` to get this functionality, but this may be a better question for the angular team ( https://github.com/angular/angular ). I would recommend opening an issue on that repo and they should be able to give you the definitive answer for this. I am going to close this issue as it is not an issue with Ionic 2 directly, but more of a question related to angular 2. Thanks for using Ionic!

**Comment by lricoy** [comment]
Ok. I agree with both of you. I should have though about that before opening the issue here. Maybe the fact that it only happens on the iOS device leaded me to it. Anyway, I think a warning on the docs would be the best choice in any case.

**Comment by jgw96** [comment]
@lricoy Definitely might be something to look into putting in the docs. If you open an issue with the angular team would you mind putting a link to the issue here ? Id love to follow along

**Comment by lricoy** [comment]
@jgw96 done. I tried to explain better over there after reading the docs and checking it's current state. Could you double check please?

**Comment by jgw96** [comment]
@Iricoy nice! Looks good to me, thanks for linking to it here!
