### ISSUE TITLE
floating label on ionic input is shadowed and obscured on iOS device.

### ISSUE THREAD

**Issue by foysalit** [driftyco/ionic#6448]
#### Short description of the problem:
The label of floating input fields ***on iOS*** gets shadowed and obscured. Only occurs on device. I'm testing on - 
> iPhone 6 
> iOS v9.3.1

> iPad 4
> iOS v9.3.1

how it looks before focus ![before focus](http://i.imgur.com/77E3iG1.jpg "before focus") and after focus ![after focus](http://i.imgur.com/9jRBs0V.jpg "after focus").

#### What behavior are you expecting?
The labels should be readable without focusing the fields.

**Steps to reproduce:**
1. Create a new ionic v2 app.
2. Add the code shown below.
3. Run it on iOS device.

```
		<ion-item>
			<ion-label floating>
				Title
			</ion-label>
			<ion-input type="text" [(ngModel)]="title"></ion-input>
		</ion-item>
```
 
**Which Ionic Version?** 2.0.0-beta.6

I would have posted a plunkr but it is not reproducible on browser, ***only works on iOS devices***. I would love to help out in any way I can, however I just started running ionic on iOS and still catching up on debug process so I might not be the fastest to reply. 

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.1.0
```

**Comment by jgw96** [comment]
Hello @foysalit ! Thanks for opening an issue with us! Would you mind trying with the latest nightly? To install Ionic 2 nightly just run `npm install ionic-angular@nightly`. Im pretty sure this issue has already been fixed in the nightly and will be in the beta.7 release.

**Comment by foysalit** [comment]
Just tested and it's working perfectly. Thank you for such swift response and all the awesome work you guys have been doing.

**Comment by jgw96** [comment]
No problem! Im glad its working for you. Expect to see that fix in the beta.7 release. Thanks for using Ionic and thanks for the kind words!

**Comment by ckerwer** [comment]
`npm install ionic-angular@nightly`
installs ionic v1.3.1.

> ionic@2.0.0-beta.25  extraneous
> └── ionic-angular@1.3.1-201605121907  invalid

Am I missing something?

**Comment by jgw96** [comment]
Hey @ckerwer sorry about that! That issue is fixed now. Running `npm install ionic-angular@nightly` should install the latest ionic 2 nightly correctly now.

**Comment by ckerwer** [comment]
npm works now.
Thanks!

**Comment by ckerwer** [comment]
... but ionic-framework 2.0.0-beta.6-201605132240 brings an error in nav-controller:
`node_modules/ionic-angular/components/nav/nav-controller.d.ts(1,52): Error TS2305: Module '"node_modules/angular2/core"' has no exported member 'ResolvedReflectiveProvider'`

I'm not shure if I should raise a issue for that?

**Comment by jgw96** [comment]
@ckerwer Would you mind opening a separate issue for that?Thanks!
