### ISSUE TITLE
There is not text-input-ios-highlight-color family of variables

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#6449]
#### Short description of the problem:
There is no way to change the color of a input cursor in iOS.

#### What behavior are you expecting?
Since there is a
`$text-input-md-highlight-color`
and
`$text-input-md-highlight-color`

I would spect to see a
`$text-input-ios-highlight-color`
variable that controls the high light color of inputs.
Also there is not
`$text-input-ios-hightlight-color-invalid`
`$text-input-ios-hightlight-color-valid`
**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This has been added and will be in the `beta 11` release. By default showing the highlight on `ios` will be set to `false`, but changing the following variables will enable it:

```
$text-input-ios-show-focus-highlight:      false !default;
$text-input-ios-show-valid-highlight:      $text-input-ios-show-focus-highlight !default;
$text-input-ios-show-invalid-highlight:    $text-input-ios-show-focus-highlight !default;
```

If you set `$text-input-ios-show-focus-highlight` to `true` the others will be enabled, as well.

**Comment by arthurflor** [comment]
It still doesn't work here.
Do I have to do anything else?

**Comment by Van-Dame** [comment]
Any update on this?
