### ISSUE TITLE
Localize tab titles doc

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic#645]
I am trying to use angular-translate and I have no idea how to translate parameters like a tab title. Is there any documentation about how to do this? If not, I would appreciate to have one. Thank you!

**Comment by xfally** [comment]
I had meet the same problem, but `<ion-view title="myVar | translate">` could not resolve it.

In more detail, I have two pages (home and test), which are navigated by `ion-nav-bar` (i konw it's based on UI-Router). I also use:
```
$translatePartialLoader.addPart("xxx");
$translate.refresh();
```
to load "home/i18n/en.json", "home/i18n/zh.json", "test/i18n/en.json" or "test/i18n/zh.json" at runtime.

home page has the title `Home Page` / `主页` and test page has the title `Test Page` / `测试页面`. test.html segment is like this:

```
<ion-view view-title="{{'TEST.TITLE' | translate}}">
<ion-content scroll="true">
(skip some codes...)
<a ng-href="#/home">
<span translate="TEST.CONTENT.GO_HOME"></span>
</a>
</ion-content>
</ion-view>
```

When `jump` from home to test page, the latter's nav title will just show `TEST.TITLE`, then i tried to `return` to home page and `jump` to test page again. Suprised to see the test page's title became `Test Page` successfully! The `translate` occurred when page (router state) changed! **but why?**

**Anyway**, i found the **solution** at last, when reviewed the ionic docs about `ionNavTitle`. the newest code is like this:
```
<ion-view>
<ion-nav-title>
{{'TEST.TITLE' | translate}}
</ion-nav-title>
<ion-content scroll="true">
(skip some codes...)
<a ng-href="#/home">
<span translate="TEST.CONTENT.GO_HOME"></span>
</a>
</ion-content>
</ion-view>
```

Hope this story could help other guys who met the same problem.
