### ISSUE TITLE
Where is the implementation of tags of Ionic2

### ISSUE THREAD

**Issue by blackhawk389** [driftyco/ionic#6451]
I want to use Ionic 2 tags other than ionic 2 framework itself, I need to find actual implementation of Ionic 2 tags

**Comment by iignatov** [comment]
The Ionic 2 tags are just Angular 2 components. If you want to implement such tags yourself then I would recommend you to find/read more information about creating Angular 2 components. If you want to take a look at the source of the Ionic 2 components it's here: [github.com/driftyco/ionic/tree/2.0/ionic/components](https://github.com/driftyco/ionic/tree/2.0/ionic/components)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
