### ISSUE TITLE
Ion-slide-box deprecated and ion-slides doesn't quite fully work...

### ISSUE THREAD

**Issue by bwheeler96** [driftyco/ionic#6454]
**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Ion-slides is documented to work with ion-slide box, and also with an event known as `$ionicSlides.sliderInitialized`. I just bower-installed ionic 3.0.0 and can not find the phrase `sliderInitialized` anywhere in the `lib/` directory.

#### What behavior are you expecting?
Ability to control ion-slides in some way.

**Steps to reproduce:**
1. Install ionic 3.0.0
2. Attempt to use `ion-slide`

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
1.3.0

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by danbucholtz** [comment]
Hello @bwheeler96,

This is actually not a release version of Ionic yet 😄 or documented on the website yet.  Pretty cool that you checked out the code.  This is in the nightly release of Ionic which can be found [here](http://code.ionicframework.com/#nightly).  This will be released in the next few days in Ionic 1.3.1.

Docs are on our staging site [here](http://ionic-site-staging.herokuapp.com/docs/nightly/api/directive/ionSlides/).

I'm going to close this issue, but please go ahead and comment back if you're having issues.

Thanks,
Dan
