### ISSUE TITLE
Android native scroll does not fire on-scroll-complete event.

### ISSUE THREAD

**Issue by dongdh** [driftyco/ionic#6457]
#### Short description of the problem:
Android native scroll does not fire on-scroll-complete event.

#### What behavior are you expecting?
Android native scroll should fire ion-scroll-complete event.

**Steps to reproduce:**
1. implement <ion-content on-scroll-complete>
2. Build on Android device (samsung 6s, android version 6.0.1)
3. The event will not fire when scrolling, same code with jsScrolling turned on works.

```
<ion-view view-title="ExplorePage" class="vsmf_explorePage">
    <ion-content delegate-handle="explore_scroller" on-scroll-complete="checkScroll()">
        <ion-refresher on-refresh="doRefresh()">
        </ion-refresher>
any long list...
</ion-content>
</ion-view>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.3.0

**Comment by jgw96** [comment]
Hello, are you still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by vance** [comment]
Does not work on iOS either. I had to ditch a whole feature in my app because of this.

**Comment by nadavhury** [comment]
Any way this bug will be fixed?
Working good on IOS and not working at all on android...
