### ISSUE TITLE
Angular2 rc1 update

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6458]
The source code has been updated to work with rc1 updates, but we still need to update our build process: https://github.com/driftyco/ionic/tree/angular-rc1

- [ ] e2e builds (system bundled, not async http requests)
- [ ] demo builds
- [ ] karma tests
- [ ] npm publish nightly
- [ ] npm publish release

**Comment by msegers** [comment]
As stated you seem to have the code updated, is there a way to pull that into a project already?

**Comment by skaldo** [comment]
+1

**Comment by jthoms1** [comment]
I have pushed an update angular-rc1 to complete the e2e builds, demo builds, and the karma tests.  I think we are also good with the npm publishes. See commit 4c19d15.

**Comment by menonsamir** [comment]
Any idea what the timeline on this is? If it's going to be a bit, is there any way to use the "angular-rc1" branch now? Tried cloning and running `gulp build` and `gulp release`, then installing the dist directory, but it doesn't seem to load.

**Comment by jaruesink** [comment]
Yes please please get this in!

**Comment by maxtuzz** [comment]
Looking forward to this!! :+1:

**Comment by Merott** [comment]
In case it hasn't been noticed by some, the latest [Beta 7](https://github.com/driftyco/ionic/releases/tag/v2.0.0-beta.7) is on RC1. I guess demos, examples and starter projects may still need updating...

**Comment by jgw96** [comment]
Hey @Merott ! You are correct, beta 7 is now on rc1 ! We are currently in the process of getting everything updated!

**Comment by emcniece** [comment]
Apologies in advance, and I'll try to make this as painless as possible. So sorry to do this to fellow devs...

What does ETA look like for this - days, weeks, or months?

**Comment by jgw96** [comment]
Hey @emcniece ! Actually, this is all done as of beta.7 and should have already been closed (my fault). If you spot anything that still needs to be updated feel free to comment on this issue and I'll take a look at it. Thanks for using Ionic!
