### ISSUE TITLE
ion-tab directive should support scope variable binding

### ISSUE THREAD

**Issue by gregaton** [driftyco/ionic#646]
The ion-tab directive currently does not support the binding of scope variables to it's attributes.

For instance to set the title from a scope variable `tabTitle` one can do

``` js
<ion-tab title="{{tabTitle}}" ...
```

but not

``` js
<ion-tab title="tabTitle" ...
```

This means the tab title will always be set to a fixed value and any later changes of `tabTitle` will not update the title attribute of the tab.

As far as I can tell this is true for all attributes of the ion-tab directive.

**Comment by mklickman** [comment]
I have this exact use case (app data changes, would like the tab title to update dynamically). Has there been any progress or updates on this issue?

**Comment by thomasMary** [comment]
Same here, would like to translate my title and so update the title on language change..

**Comment by psgganesh** [comment]
I use the same in  below way
```html
<ion-tab title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111044/eb9e81ca-8936-11e5-8714-c473b7739424.png)

But when it is 
```html
<ion-tab translate="coffee_title_label" title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111034/cdaa8790-8936-11e5-9408-043d322f0e02.png)

I referred the below codepen example
http://codepen.io/andrewmcgivery/pen/tqymb

Can you let me know, what am doing wrong here !
