### ISSUE TITLE
ionic tabs overlapping the navheader in IOS

### ISSUE THREAD

**Issue by mahesh21** [driftyco/ionic#6460]
![screen shot 2016-05-06 at 10 34 15 pm](https://cloud.githubusercontent.com/assets/650714/15080279/ea21768e-13da-11e6-8a13-65af684f114b.png)
#### Expecting the tabs will be shown same as android on top below title

```

$ionicConfigProvider.tabs.position('top');

**1.7.14**

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#138
