### ISSUE TITLE
Ionic 1 does not run CLI commands such as `ionic info` or `ionic build ios`

### ISSUE THREAD

**Issue by shotbyabel** [driftyco/ionic#6461]
#### Short description of the problem:

Not sure if me updating to Node 6 is causing all this.. but I am working on an Ionic 1 app with a remote team and lately our versions have not liked each other. I was wondering if the fact that I have also been working on Ionic 2 projects for whatever reason my CLI "thinks" these apps are also Ionic 2 and there for is shooting me the error below? (i know it makes no sense but I have no clue)

#### What behavior are you expecting?

I want to be able to run ionic commands like `ionic info` , `ionic build ios` etc.. and not get this error.. or message.. 

[issue in detail](http://stackoverflow.com/questions/37078620/ionic-1-app-does-not-build-ios-ionic-project-has-been-renamed-to-ionic-config)
```
insert any relevant code between the above and below backticks

mymac ~/code/92_AAC/newApp on master[!]
$ ionic build ios
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'gulp'

Do you need to run `npm install`?

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Most likely, this is related to node 6, as those commands should work, and do work for me (im on node 5.10.1). Would you mind downgrading to node 5 and testing? Also, since this issue is an issue related to the cli and not the framework im going to move this issue over to the ionic-cli repo. Ill continue the conversation with you over there. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#987
