### ISSUE TITLE
bug: infinite-scroll fired wrongly with refresher

### ISSUE THREAD

**Issue by ThibaudD** [driftyco/ionic#6463]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>Android</span>  

<span ionic-description>I made a demo app http://play.ionic.io/app/757618aad987 You can simulate it with browser device mode.
Without releasing the touch action on the screen. You pull down the refresher until you see the arrow rotating and then you pull it back like if you don't want to refresh then the on-infinite method from the infinite scroll is fired.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#136
