### ISSUE TITLE
Prevent callbacks execution after page changed

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6464]
**Ionic 2**

**Scenario**
I'm making a http post request which will take quit more time to complete. But before that I'm going back manually. But after request has been completed, nav.pop() in the resolve is getting called once again and changing the current page.

**Comment by iignatov** [comment]
I believe that it's your responsibility to properly handle such situations because it's triggered by your own code and Ionic has nothing to do with it, so in your code just use the following:

```js
  whatever() {
    // Where you make the request store the subscription:
    this.subscription = this.http.post(
      // http request options
      )
      // more code here...
      .subscribe(/* ... */);
  }

  onPageWillLeave() {
    // Then when leaving the page cancel the request:
    this.subscription.unsubscribe();
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Unfortunately, it is outside of the scope of the Ionic framework to handle subscribing from observables and cancelling http requests when navigating. Thanks for using Ionic and if you still feel this is a bug in the ionic framework feel free to comment!

**Comment by dheran** [comment]
@iignatov I'm using Promise instead of Rx

**Comment by jgw96** [comment]
@dheran Unfortunately promises are not cancellable, so no matter what you do, if you start an http request using a promise, that promise is going to return a value even if you have navigated away from the page. I would consider changing to using observables if possible as they are cancellable which will solve your issue. If you would like to learn how to use observables with http in angular 2 here is a good link: https://angular.io/docs/ts/latest/guide/server-communication.html . Let me know if you have any other questions!

**Comment by iignatov** [comment]
@dheran Why you're not using an Observable, when you mentioned that you're using http _(I'm assuming that you're using the Angular 2 Http client)_ which should return an Observable? IMHO this is the best thing to do in such a case. However if you really want to use a Promise instead, then you should implement the proper logic to handle this scenario yourself, e.g. something like this:

```js
  whatever() {
    // Only perform the needed operations if the page is still active:
    this.loadMyData().then(() => {
      if (!this.isPageLeaving) {
        // your code here...
      }
    });
  }

  onPageWillLeave() {
    // Set a flag to know when the page is being dismissed:
    this.isPageLeaving = true;
  }
```

**Comment by ajaysaini95700** [comment]
i am using observables with http but i am not able to stop http request on view changed . i have also used unsubscribe()
