### ISSUE TITLE
Feature requirement: Context overlay menu aka more option menu (three dots)

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6465]
**Ionic 2**

**Comment by midramas** [comment]
Would also need this :)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This would be something that could be handled by our Popover component that is currently scheduled for beta.8. You can track the progress of that in this issue (https://github.com/driftyco/ionic/issues/5420). Thanks for using Ionic!

**Comment by dheran** [comment]
@jgw96 I saw it in old documentation of v2. Now I couldn't find it.
