### ISSUE TITLE
Page with radiobuttons throws an error when dismissed/backbutton

### ISSUE THREAD

**Issue by sveinl** [driftyco/ionic#6466]
#### Short description of the problem:
I have a page that opens another page containing 2 radiobuttons.
When hitting backbutton on that page there is an exception thrown:
`EXCEPTION: TypeError: Cannot read property 'remove' of null`

#### What behavior are you expecting?
No errors.

**Steps to reproduce:**
1. Create a page that opens another page containing radiobuttons
2. Visit that page and click back-button

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
3     898346   error    STACKTRACE:
5     898347   groupEnd
6     898348   error    Uncaught TypeError: Cannot read property 'remove' of null, http://localhost:8100/build/js/angular2-polyfills.js, Line: 324
0     952330   log      Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
1     959837   group    EXCEPTION: TypeError: Cannot read property 'remove' of null
2     959838   error    EXCEPTION: TypeError: Cannot read property 'remove' of null
3     959839   error    STACKTRACE:
4     959839   error    TypeError: Cannot read property 'remove' of null
    at RadioButton.ngOnDestroy (http://localhost:8100/build/js/app.bundle.js:45957:20)
    at AbstractChangeDetector.ChangeDetector_RadioPage_0.dehydrateDirectives (viewFactory_RadioPage:286:20)
    at AbstractChangeDetector.dehydrate (http://localhost:8100/build/js/app.bundle.js:12904:14)
    at AbstractChangeDetector.destroyRecursive (http://localhost:8100/build/js/app.bundle.js:12917:14)
    at AbstractChangeDetector.destroyRecursive (http://localhost:8100/build/js/app.bundle.js:12924:25)
    at AppView.destroy (http://localhost:8100/build/js/app.bundle.js:22543:29)
    at AppViewManager_.destroyViewInContainer (http://localhost:8100/build/js/app.bundle.js:23008:14)
    at ViewContainerRef_.remove (http://localhost:8100/build/js/app.bundle.js:22870:19)
    at Array.<anonymous> (http://localhost:8100/build/js/app.bundle.js:44020:35)
    at ViewController.destroy (http://localhost:8100/build/js/app.bundle.js:45458:30)
5     959840   groupEnd
6     959842   error    Uncaught TypeError: Cannot read property 'remove' of null, http://localhost:8100/build/js/angular2-polyfills.js, Line: 324
 

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/SUpyXm?p=preview
Click "Show radios" then hit back button. An exception are thrown in the console.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
 ionic info

Your system information:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hmmm good catch! Have you noticed this with any other component or just the radio buttons component?

**Comment by sveinl** [comment]
I have not seen this with other components i have used.

**Comment by teleaziz** [comment]
+1

**Comment by jgw96** [comment]
Hello all! Here is a working [plunker](http://plnkr.co/edit/nBZG0z?p=preview). The issue (which i should have spotted earlier) was that the `ion-list` should have had the `radio-group` attribute on it. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello @teleaziz ! Are you interested in doing a pr for this?

**Comment by teleaziz** [comment]
@jgw96 , thanks! just did :)

**Comment by brandyscarney** [comment]
Thanks for the issue and the PR! This will be in the `beta.7` release.
