### ISSUE TITLE
ionic serve crashed during lib update

### ISSUE THREAD

**Issue by skotturi** [driftyco/ionic#6467]
#### Short description of the problem:

ionic serve crashed, it asked me to report this. 

#### What behavior are you expecting?

not crash

**Steps to reproduce:**
1. run `ionic serve`
2. run `ionic lib update`

```
File changed: www/lib/.ionic/ionic-bower-1.3.0/
Caught exception:
 Error: ENOENT: no such file or directory, scandir '/Users/developer/Developer/demo-app/www/lib/.ionic/ionic-bower-1.3.0/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Gaze.emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:135:10)
    at Gaze.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:401:18)
    at null._onTimeout (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:427:24)
    at Timer.listOnTimeout (timers.js:92:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by danbucholtz** [comment]
Hi @skotturi,

We are going to move this to our CLI repo since it's a CLI issue.

@jgw96, can you move to CLI?  I am going to close for now.  No hurry.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#988

**Comment by skotturi** [comment]
@danbucholtz no worries, I didnt really expect `serve` to gracefully handle ionic lib being deleted a new version being setup but it said to report it, so there it is. my bad for not putting this in the cli repo.
