### ISSUE TITLE
start-y attribute on ion-content does nothing

### ISSUE THREAD

**Issue by yosikal** [driftyco/ionic#6468]
start-y attribute on ion-content does nothing - the scroll starts from same point no matter which value I set in it. This is a regression of latest version 1.3.0. I confirmed it's working on version 1.2.4.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker that demonstrates this issue? You can find a link to an Ionic 1.3 plunker template in the issue template for this repo. Thanks again!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
