### ISSUE TITLE
Sidebar Doesn't Work with prodMode enable in Ionic Beta 6

### ISSUE THREAD

**Issue by prijindal** [driftyco/ionic#6469]
#### Short description of the problem:
If prodMode is set true and we push a page in stack.
The sidebar can't be opened.
Please note that this works when prodMode is false

#### What behavior are you expecting?
Side bar shows on both prodMode enabled or disabled setting

**Steps to reproduce:**
1. Make a new page
2. Add a sidemenu
3. Push that page to the stack
4. Sidemenu can't be opened now 

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic 2.0.0 Beta 6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v6.0.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker that demonstrates this issue? You can find the link to a plunker template for Ionic 2 in the issue template that is displayed when you make a new issue for this repo. Thanks again!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
