### ISSUE TITLE
splash animation different

### ISSUE THREAD

**Issue by Monk428** [driftyco/ionic#6470]
I have two different apps with the same code,but they have different start-up animations;
      first one is the one that main page will appear gradually,that is to say main page display already finished when splash end;
     while the other one does not have animation,that is main page show up after splash ended. 
     I didn't change anything in config.xml,and I **hope main page display finish when splash ended**,like the first one.I believe there must be something wrong with the second one,could you pls tell me how could this happen and how to fix it? 
![n](https://cloud.githubusercontent.com/assets/3744337/15097975/f72acdbc-1560-11e6-8ff5-7d6453514356.gif) normal
![u](https://cloud.githubusercontent.com/assets/3744337/15097976/f72d22c4-1560-11e6-9592-d542ca3dd70d.gif) unnormal

**Comment by mlynch** [comment]
@Monk428 we shortened the splash delay since it seemed too slow. Maybe we should tune that somewhere in the middle?

**Comment by mlynch** [comment]
Changed it to 2 seconds, we'll see how that goes.

To edit this yourself @Monk428 edit config.xml and change this:

```xml
    <preference name="SplashScreenDelay" value="2000" />
    <preference name="FadeSplashScreenDuration" value="2000"/>
```

**Comment by Monk428** [comment]
Hi mlynch 
  I use like that,but it's seen nothing; no delay 5s , no fade animation;how could i do?

  <preference name="SplashScreenDelay" value="5000" />
  <preference name="FadeSplashScreenDuration" value="2000"/>

Best Regards
@mlynch
