### ISSUE TITLE
Support for ubuntu phone - easier to make .click packages

### ISSUE THREAD

**Issue by pc-magas** [driftyco/ionic#6471]
I tried to make .click packages on an existing ionic application (https://github.com/kawai-developers/faster) But I figured out that is nearly impossible even though you can make an ubuntu phone application with cordova.

I tried to make one .click package By doing these steps on my ubuntu machine:
 ```
   cd ^my_project_folder^
    ionic add platform ubuntu
    ionic ubuntu build
```
But the last command give me the option for a .deb package and not for .click package as mentioned bellow:

```
Running command: /home/pcmagas/Kwdikas/Javascript/Ionic/Faster/hooks/after_prepare/010_add_platform_class.js /home/pcmagas/Kwdikas/Javascript/Ionic/Faster
add to body class: platform-ubuntu
Running command: /home/pcmagas/Kwdikas/Javascript/Ionic/Faster/platforms/ubuntu/cordova/build 
Building...
Note: to build a debian package, run: 
 cd /home/pcmagas/Kwdikas/Javascript/Ionic/Faster/platforms/ubuntu/native/com.ionicframework.faster723190; debuild

```

Therefore I thought it would be nice if I had the following options for ubuntu phone: (I am recomending a use case)

```
cd ^my_project_folder^
ionic add ubuntu_phone
ionic ubuntu-phone build
```

And the last command gave me the following response:
```
BUILD SUCCESSFUL

Total time: 17.839 secs
Built the following click package(s):
    /home/pcmagas/Kwdikas/Javascript/Ionic/Faster/platforms/android/build/outputs/apk/android-debug.apk
```

**Comment by jgw96** [comment]
Hey @pc-magas ! Thanks for opening an issue with us! Although the ability to build .click packages, or even .snap packages using the cordova cli (which ionic uses under the hood) would be extremely cool, this is not actually an issue that we could fix with the ionic-cli but something that the cordova cli team would have to add. All the packaging of apps for devices by the ionic-cli is done by the cordova cli under the hood. I would urge you to open an issue with the cordova cli team (https://cordova.apache.org/contribute/issues.html) and see if they would be interested in adding this support.
 PS. I am typing this from my machine running Ubuntu 16.04 and think its very cool that somebody is interested in building Ionic apps for ubuntu mobile!
