### ISSUE TITLE
viewData.enableBack stop working on 1.3.0

### ISSUE THREAD

**Issue by enricodeleo** [driftyco/ionic#6474]
Hi everyone,

my app have some state reachable from a tab view. Until 1.2.4 I used this code within the controller in order to enable the back button:

```
$scope.$on('$ionicView.beforeEnter', function (event, viewData) {
  viewData.enableBack = true;
});
```

As said above, until 1.2.4 the behavior was straightforward: the user could se the usual back button and he could go back to the previous view tapping that button.
After upgrading to ionic 1.3.0 this stopped working as expected. The button is still visible but it provides no functionality. 

I couldn't find any solution, switching back to 1.2.4 it just worked again. Any ideas?

**Comment by jgw96** [comment]
Hello @enricodeleo ! Thanks for opening an issue with us! Would you be able to provide a plunker or codepen that gives an example of this issue?

**Comment by enricodeleo** [comment]
Thank you for your reply.

Apparently the issue is related to the copy of Ionic 1.3.0 available via bower. [This is the Codepen](https://codepen.io/enricodeleo/pen/GZzYzK/) where I attached the copy of `ionic.bundle.js` coming from bower (`"ionic": "driftyco/ionic-bower#v1.3.0"`). The issue is visible within the "Contacts" tab.

The same code works with nightly version hot linked from ionic [in this fork of the above codepen](https://codepen.io/enricodeleo/pen/yOZQep)

**Comment by jgw96** [comment]
Ahh ok, so it looks like it has already been fixed in nightly then, which means that this fix should make it to the next release ionic 1.3.1. Since this seems to have already been fixed i will be closing this issue for now. Thanks for using Ionic! Also be on the lookout for ionic 1.3.1 very soon (; !
