### ISSUE TITLE
Handling hiding status bar

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#6475]
#### Short description of the problem:

Hide the statusbar does not remove the extra 20px on ios.
We should fix this.

**Steps to reproduce:**
1. ionic start tmp blank --v2 --ts
2. Add the following to the platform.ready block

```
    platform.ready().then(() => {
      StatusBar.hide();
    });
```
1. run on sim/device.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Probably need to add a class to body or something to adjust this.

**Which Ionic Version?** 1.x or 2.x
v2 (relevant to v1 as well I guess)

**Comment by jgw96** [comment]
This is probably also related to this issue: https://github.com/driftyco/ionic/issues/5877

**Comment by brandyscarney** [comment]
Should be able to hide the status bar padding in the app config:

```
@App({
  templateUrl: 'build/app.html',
  config: {
    statusbarPadding: false
  }
})
```

Probably something we should handle though.

**Comment by ramoncarreras** [comment]
Thanks to @brandyscarney 's comment I think that I found a workaround:
https://forum.ionicframework.com/t/how-to-remove-space-at-the-top-of-navbar/44194/7?u=ramon

**Comment by mhartington** [comment]
I think this is fine the way it is currently. If people want to hide the status bar, there are APIs in place to set the config
