### ISSUE TITLE
Input placeholder is overlapping label when type "date"

### ISSUE THREAD

**Issue by ckerwer** [driftyco/ionic#6476]
When using an ion-input of type "date" it's placeholder is overlapping the label.
(see plunker link).

```
<ion-item>
            <ion-label floating>Birthday<span danger>*</span></ion-label>
            <ion-input type="date"></ion-input>
</ion-item>
```

**Which Ionic Version?** 
2.0.0-beta.25

#### Plunker that shows an example of your issue

**http://plnkr.co/edit/0rXpPSbW1vJuxiU8ESY4?p=preview

**Comment by ckerwer** [comment]
Same with type="time"

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This will be solved when our DatePicker component is released, which should be very soon (maybe the next release) as you will not have to use the native inputs anymore. Thanks for using Ionic!
