### ISSUE TITLE
Material Tabs unnecessary padding

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6478]
In the docs the segment demo has unnecessary padding on the bottom such that the buttons are not flush with the bottom of the header:

<img width="422" alt="screenshot 2016-05-09 12 06 51" src="https://cloud.githubusercontent.com/assets/11214/15121125/a20f1526-15de-11e6-91b7-909477b0f8af.png">

http://ionicframework.com/docs/v2/components/#segment

Could be a demo-specific styling issue though. driftyco/ionic-site

**Comment by jgw96** [comment]
I think this may be on purpose. If they didn't have padding on them then it would look just like the tabs component. Could be completely wrong on that though.

**Comment by brandyscarney** [comment]
This is actually a combination of the `min-height` and `padding` on the toolbar element. There isn't a great way to fix this on the toolbar itself, but I think it goes back to the need to change the segment on material design to look less like tabs.

**Comment by brandyscarney** [comment]
I'm going to close this as part of #9311 :)
