### ISSUE TITLE
A single ion-input triggers unnecessary form field jump arrows and has weird behaviour

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic#6480]
![ion-input](https://cloud.githubusercontent.com/assets/1189149/15131516/c18fb42a-16a4-11e6-9aa9-201ddc6486de.gif)
#### Short description of the problem:

A single `<ion-input type="text">` unnecessarily triggers form field jump arrows and has weird behaviour. If you tap the "next" arrow it looks likes it jumps to the hidden input field (because ion-input its just a wrapper right?) and you can type text on it. Also notice that you can see a tiny bit of a text cursor blinking (near the "Done" button).
#### What behavior are you expecting?

To not trigger form field jump arrows.

**Steps to reproduce:**
1.

```
<ion-toolbar position="bottom">
  <ion-input type="text" placeholder="Type a message..."></ion-input>
</ion-toolbar>
```

2.
Test on iOS (I've tested with an iPhone 6s with iOS 9.3.1). Use can also experience the same issue testing on Safari using the preview plunker link provided below.

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/AwJiEYptJo9g3stYaNqZ?p=preview
http://run.plnkr.co/GSj4ubYRfkZSfW7y/

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are now tracking keyboard issues on this issue https://github.com/driftyco/ionic/issues/11501.
