### ISSUE TITLE
Modal first input is focused on open

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6481]
#### Short description of the problem:

Even if `focusFirstInput` is set to false in the modal object, an input of the modal is inconsistently focused. 
#### What behavior are you expecting?

No input to be focused

**Steps to reproduce:**
1. Clone http://github.com/bouzmine/metho.git
2. Run npm install
3. Install `cordova-common` and `ios-sim`
4. Run on iOS
5. Open the app
6. Create a project and go in it
7. Open and close the create a source modal (button to the left of Pending item)
8. You might see the input being focused (if not kill the app and try again)

**Which Ionic Version?** 1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#135
