### ISSUE TITLE
bug: Method get() of LocalStorage doesn't return valure

### ISSUE THREAD

**Issue by andreolidavide** [driftyco/ionic#6483]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I created a LocalStorage in my page constructor, using
`    this.local = new Storage(LocalStorage);`
then I added a key-value pair using the set() method, like this
`    this.local.set('latitude','echo');`
When retrieving the value using the get() method (`this.local.get('latitude')`), I receive an object instead of the value. Here is a string representation of the object I get
`{"__zone_symbol__state":true,"__zone_symbol__value":"echo"}`
Of course I can access the property I using `this.local.get('latitude').__zone_symbol__value`, but the documentation for the get() method imply that it should return the value for a given key, so it looks like it could be a bug to me.
I'm sorry if it is not, it's the first time I am submitting an issue and I am still inexperienced.</span>

<span is-issue-template></span>

**Comment by dylanvdmerwe** [comment]
See [here ](https://developer.mozilla.org/en-US/docs/Web/API/Storage)for more information. 

```
localStorage.setValue('latitude', 'echo');
localStorage.getValue('latitude');
```

**Comment by jgw96** [comment]
Hey @andreolidavide ! Thanks for opening an issue with us! Do not worry about being inexperienced! Your explanation of your issue was great! I think that the best course of action for you would be to ask how to use localStorage on our forums (forum.ionicframework.com). There are plenty of awesome devs on there that will show you the proper way to use localStorage in your ionic app. Also, welcome to the Ionic community (:

**Comment by jguix** [comment]
It looks like you're getting some sort of promise.

Correct me if I'm wrong, but on Ionic 2, Storage uses promises, like so:

```
import { Storage, LocalStorage } from 'ionic-framework/ionic';
		
this.storage = new Storage(LocalStorage);

this.storage.get('latitude').then((data) => {
    // Do something with latitude value
}
```

**Comment by webzfy** [comment]
@andreolidavide hey,have u solved this problem？
