### ISSUE TITLE
Feature: Method similar to onbeforeunload for each @Page

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6484]
**Ionic 2**

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Would you mind filling out the issue template that is displayed to you when you create a new issue and posting the content here? Unfortunately, I am having a hard time understanding exactly what feature you need from the title above. Does this documentation about lifecycle events in Ionic 2 help you? http://ionicframework.com/docs/v2/api/components/nav/NavController/

**Comment by dheran** [comment]
Lifecycle events were only callbacks I guess. Can It prevent user from going back, if user pressed back button accidentally while doing some critical tasks?

**Comment by jgw96** [comment]
Ahh ok, it is on our roadmap to allow users to customize what happens when the back button is pressed, but this has just not been implemented yet. Look out for it in a coming release! Thanks for using Ionic!
