### ISSUE TITLE
ionic2: ion-item with (press) not scrollable

### ISSUE THREAD

**Issue by wodka** [driftyco/ionic#6486]
#### Short description of the problem:

a list of items with (press) to open actionsheet, but it does not scroll on touch (works with mousewheel)

#### What behavior are you expecting?

**Steps to reproduce:**
1. create a list
2. each item should have (press) defined
3. the following code will be added automatically by the (press) handler
4. because of this it cannot scroll

```
style="touch-action: none; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
```

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/RlQN1xdvIrmdUNp2XLSn?p=preview

you need the touch events to see the problem. 

to have only the code:
http://run.plnkr.co/BpjNf4BrhbQdWNab/

in the plunker i also added my workaround (toggle at the beginning of the list forces touch-events back to it's default value)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Good catch, we are also able to reprodoce this issue and will be looking into it.

**Comment by adamdbradley** [comment]
In this case, just using `(click)` is recommended. Hammer's press adds a few more handlers that makes things more difficult, where click should be working fine for this scenario.

**Comment by wodka** [comment]
on (click) I open the page for the entry, and on (press) I'd like to show the the action sheet.

-> therefore switching to (click) won't solve the issue itself.

the main problem I can see so far is that the css prevents the touch action (by removing it scroll works again)

**Comment by JohnyGemityg** [comment]
having exactly the same problem

**Comment by dadakoko** [comment]
just face the same issue when adding a swipe and click event on the ion-item

**Comment by kinhbang89** [comment]
Hi, I also got the same problem on putting press in the ion-item. Is there any solution for this?

**Comment by dadakoko** [comment]
the solution is to use virtualscroll (you can check an example in the commit above)
<ion-list [virtualScroll]="items | sortAsc:'title'" [headerFn]="myHeaderFn">

**Comment by youngmob** [comment]
After I upgraded from 2.3.0 to 3.0.0, this is happening. Any suggestion how i can use (click) and (press) at the same time?

**Comment by ozexpert** [comment]
After I upgraded from 2.3.0 to 3.0.0, this is happening. Any suggestion how i can use (click) and (press) at the same time?

**Comment by klochko7** [comment]
> After I upgraded from 2.3.0 to 3.0.0, this is happening. Any suggestion how i can use (click) and (press) at the same time?

I have the same problem ..

**Comment by armeniopinto** [comment]
Hello,

I am having the same problem. This happens with any combo of 2 or more events (`click` and `swipe`, for example).

List scrolling was working just fine in Ionic 2 and it's now broken after upgrading to Ionic 3.0.1.

Some [code here](https://goo.gl/aO28Z3) to illustrate the problem.

**Comment by lucasbasquerotto** [comment]
I faced this issue after upgrading from `Ionic 2.3.0` to `3.0.1`. But in my case I just had the `tap` event. Fixed it changing to the `click` event (but I don't have other events besides `click`). **It seems the touch events aren't working well in a list of items after the upgrade.** I think something in the touch events are preventing the scroll.

**Comment by pablanka** [comment]
I my case I need each item has (click) and (press) events. Adding last one locks scrolling when you try to scroll from the item. 
I'm using IONIC 3.0.1.

**Comment by JanPeeters** [comment]
I was able to solve this problem by creating a custom directive for the press event, based on: [http://stackoverflow.com/questions/43492833/ionic-2-setting-callback-for-long-press-event-directive](url).

    import { Directive, ElementRef, OnInit, OnDestroy, Output, EventEmitter } from '@angular/core';
    import { Gesture } from "ionic-angular/gestures/gesture";

    @Directive({
    	selector: '[long-press]' // Attribute selector
    })

    export class PressDirective implements OnInit, OnDestroy {
    	el: HTMLElement;
    	pressGesture: Gesture;
    	@Output('long-press') onPressRelease: EventEmitter<any> = new EventEmitter();

    	constructor(el: ElementRef) {
    		this.el = el.nativeElement;
    	}

    	ngOnInit() {
    		this.pressGesture = new Gesture(this.el);
    		this.pressGesture.listen();

    		this.pressGesture.on('press', (event) => {
    			this.onPressRelease.emit('released');
    		});
    	}

    	ngOnDestroy() {
    		this.pressGesture.destroy();
    	}
    }

And then use `(long-press)="myfunction()"`...

**Comment by pablanka** [comment]
Great! That worked form me!

**Comment by Abhishek-Kanitkar** [comment]
For those still looking to enable scrolling, and not having to use JavaScript code for gestures, here is the solutions that worked for me to use HammerJS in Ionic project and still have scroll.

https://github.com/hammerjs/hammer.js/issues/1014#issuecomment-372513548
