### ISSUE TITLE
update ionic1 inputs with new ion-inputs

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#6489]
http://blog.ionic.io/announcing-ionic-1-2/

```
<ion-input class="item item-input">
  <i class="icon ion-person"></i>
  <ion-label>Username</ion-label>
  <input type="text">
</ion-input>
```

Or similar to what we have in v2 right now. 

Same for radio inputs.

```
<ion-radio ng-model="choice" ng-value="'A'">Choose A</ion-radio>
<ion-checkbox ng-model="test" ng-checked="test" ng-disabled="test">Disabled Directive</ion-checkbox>
```

In regards to API docs and Component Docs

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!
