### ISSUE TITLE
Ionic 2: Support for Angular 2.0.0-rc.x / AngularFire2

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic#6493]
#### Short description of the problem:
Cannot use AngularFire2 because it "Cannot find module '@angular/core'". I believe this happens because AngularFire2 depends of Angular 2 rc and Ionic 2 is not yet using a rc version of Angular. Angular changed the way how the framework is distributed in rc – it comes as a set of scoped npm packages now. Any imports of the Angular classes will be done from @angular instead of angular2.

#### What behavior are you expecting?
Successful loading of the Ionic 2 app.

**Steps to reproduce:**
1. `npm install angularfire2 firebase --save`
2. `import {FIREBASE_PROVIDERS, defaultFirebase, AngularFire} from 'angularfire2'`
3. `ionic serve`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 Update Angular 2 version to the latest rc version

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by nunoarruda** [comment]
Ups... I just notice you might already be working on it (https://github.com/driftyco/ionic/issues/6458). This issue might be useless now.

**Comment by dylanvdmerwe** [comment]
Yes work is underway to move to Angular RC 1.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Yep, we are currently working on upgrading to Angular 2 rc1. Thanks for using Ionic!

**Comment by aaronksaunders** [comment]
You can also always rollback to an older version of angular fire to start the development
