### ISSUE TITLE
Ionic 2/OneSignal: Load/render/event (?) issue when tapping a push notification and redirecting to a page with a http request

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic#6494]
#### Short description of the problem:
Loading/rendering/event (?) issue when tapping a push notification and redirecting to a page with a http request. After redirected to the page, the loading/rendering of the requested content seems to hang continuously.

#### What behavior are you expecting?
Page to load/render properly.

**Steps to reproduce:**
1. Download demo app: [demo.zip](https://github.com/driftyco/ionic/files/258623/demo.zip)
2. Setup [OneSignal](https://documentation.onesignal.com/docs/phonegap-sdk-overview)'s push service on `app.ts`
3. Install everything: `npm install` and `ionic state reset`
4. Run app on a emulator or device
5. Go to the OneSignal dashboard and send a push notification
6. Close the push notification

app.ts
```
...
let notificationOpenedCallback = (jsonData) => {
        
    console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
                
    // Redirect to another page
    let nav = this.app.getComponent('nav');
    nav.setRoot(AnotherPage);
        
}
      
window.plugins.OneSignal.init(appId, {googleProjectNumber: googleProjectNumber}, notificationOpenedCallback);

// Show an alert box if a notification comes in when the user is using the app
window.plugins.OneSignal.enableInAppAlertNotification(true);
...
```
anotherpage.ts
```
...
  constructor(private http: Http) {
    
    http.get('http://netflixroulette.net/api/api.php?title=Attack%20on%20titan')
      .subscribe(
        (response) => {
          console.log(response.json().summary);
          
          this.responseReceived = true;
          this.response = response.json();
        },
        error => console.log(error)
      );
    
  }
...
```

**Other information:**
 When navigating to another page via the sidemenu it works perfectly:
![good](https://cloud.githubusercontent.com/assets/1189149/15171777/4951de8c-17a5-11e6-9e71-b61435a9847d.gif)

When redirected to another page after closing the push notification it fails to load/render the requested content:
![bad](https://cloud.githubusercontent.com/assets/1189149/15171811/7281b156-17a5-11e6-8716-307a1babe81e.gif)

In both the above scenarios, the http request response is being received properly because the console.logs I've placed run as/when expected:
```
console-via-logger.js:173
For over a century, people have been living behind barricades to block out the giant Titans that threaten to destroy the human race. When a Titan destroys his hometown, young Eren Yeager becomes determined to fight back.
```

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by nunoarruda** [comment]
@one-signal do you have any feedback about this issue?

**Comment by nunoarruda** [comment]
Moving the http request from the constructor to an [`onPageDidEnter`](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) event fixes the issue but I still don't understand what the problem is.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So there are a few reasons why i wouldn't recommend making http requests or doing anything ui related in the constructor of a component. One, the constructor of a component is initiated before the ui of a component is ready to go so any ui related things that are done in the constructor can have issues. Secondly, we recommend using our lifecycle events as they can be controlled by the framework much easier than when a constructor is initiated. Hope this clears things up for you!

**Comment by jgw96** [comment]
Oh, and if you would like to read more about our lifecycle events you can visit [this](http://ionicframework.com/docs/v2/api/components/nav/NavController/) link. Thanks again!
