### ISSUE TITLE
$ionicView.beforeEnter fire tiwce on ios

### ISSUE THREAD

**Issue by wzhsh90** [driftyco/ionic#6495]
ionic version:1.2.4

cordova platform ios:4.1.1

there is two page,I called page 'A',page 'B'

page A's controller   register  $scope.$on('$ionicView.beforeEnter', function (e) {}) event;

page B:
 <div class="bar bar-header bar-balanced">
        <button class="button icon ion-chevron-left btn-back" ng-click="goBack()"></button>
        <div class="title"><i class="icon iconfont icon-cheweifei headTitle"></i></div>
    </div>
  $rootScope.goBack = function () {
            if ($ionicHistory.backView()) {
                $ionicHistory.goBack();
            } 
   });

setp:
  A-->B-->A

but when 'B' to 'A'  i not really to click 'back' button ,I user i finger fast swip the 'back' button
'beforeEnter' will fire tiwce .I click the the 'back' button normal 'beforeEnter' fire once.

the situation will not come out always .Only caused on ios  android is ok. That is confused me.

**Comment by danbucholtz** [comment]
Hi @wzhsh90,

Can you make a Codepen from our list of starters showing the issue?

http://codepen.io/ionic/pens/public/?grid_type=list

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
