### ISSUE TITLE
Tabs will show on the next pages on ios device!

### ISSUE THREAD

**Issue by Joostvd17** [driftyco/ionic#6496]
#### Short description of the problem:
If you make a screen with tabs and u go from that screen to another screen, in ios the tab will go with you to the other screen. In android will this not happen, as expected. What i do is from the tabs page i navigate to the other screen with the NavController.

#### What behavior are you expecting?
What i was expecting is that the tabs on the ios device will not come to the next page.

**Steps to reproduce:**
1. Make a new project, at this moment u have a standard tabs app.
2. On tab 1 make a button, so that you can go to another page when u click on it.
3. Make a 'next_page' page.
4. Set (click) to button in html and make a method. Import NavController and use the push method to push next_page.
5. Now automatically you have the tabs on your next page in ios....

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I couldn't find any related issues.
 
**Which Ionic Version?** 1.x or 2.x
This is ionic version 2.

#### Plunker that shows an example of your issue
http://plnkr.co/edit/QOUVY6VMIsoM4Y7mGtWJ?p=preview

Please set the user agent to a ios device.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v5.11.0

**Comment by NickStemerdink** [comment]
Related: https://forum.ionicframework.com/t/persistent-tabs/43579

**Comment by brandyscarney** [comment]
Hey, thanks for the issue! So I'm confused on what the final goal is here. The `tabSubPages` option in the [config](http://ionicframework.com/docs/v2/api/config/Config/) can be used to show tabs on child pages or hide them. Material Design has this set to `true` by default and ios has it set to `false`. Some example usage for ios only:

```
@App({
  templateUrl: 'build/app.html',
  config: {
    platforms: {
      ios: {
        tabSubPages: true
      }
    }
  }
})
```

Is this what you mean?

**Comment by Joostvd17** [comment]
Yes, thank you very much! This solved the problem.

**Comment by brandyscarney** [comment]
@Joostvd17 Awesome! I added some documentation to the config docs with descriptions of all of the properties: http://ionicframework.com/docs/v2/api/config/Config/

and also the default values for each mode in the theming docs: http://ionicframework.com/docs/v2/theming/platform-specific-styles/

**Comment by gxsjtu** [comment]
In beta 10, i do not thing it work correctly.
the tabbar is indeed hidden in tab sub pages, but scroll-content has margin-bottom same with tabbar height, some content will be covered.

**Comment by brandyscarney** [comment]
@gxsjtu Could you create a new issue for this please with some example code? Thanks! :smile:

**Comment by zzpmaster** [comment]
In beta 9 and beta 10, setting **tabSubPages: true** , althought the tabbar is hidden, but tabs view will overlap with iOS statusbar. like [#6368](https://github.com/driftyco/ionic/issues/6368).

**Comment by gxsjtu** [comment]
no overlap status bar is another issue
Use tabsubpages =true on ios the status bar is hidden but the bar height is still there you can see the padding bottom of scroll content is equal to the height of tabbar


发自我的 iPhone

在 2016年7月5日，上午10:18，Mark <notifications@github.com<mailto:notifications@github.com>> 写道：


In beta 9 and beta 10, setting tabSubPages: true , althought the tabbar is hidden, but tabs view will overlap with iOS statusbar. like #6368<https://github.com/driftyco/ionic/issues/6368>.

―

**Comment by zzpmaster** [comment]
how to solve this problem?
