### ISSUE TITLE
Ionic-Modal: Scrolling doesn't work on Windows Phone 10

### ISSUE THREAD

**Issue by mglmgl** [driftyco/ionic#6497]
Hi there,

I'm Using Ionic 1.2.4 with Cordova 6.1.1. I have an ion-modal which shows the privacy policy of our app. 
On _iOS_, _Android_ and _Windows Phone 8.1_ it works without any problems and the whole policy is displayed, scrolling works like a charm. 

But on Windows Phone 10 the modal only shows the text, which is initially loaded. When i try to scroll, the whole app moves up or down a bit. Scroling inside the modal is not possible.
The code looks like below:
```html
<ion-modal-view>
   <ion-header-bar class="bar bar-header bar-dark" align-title="center">
      <h1 class="title">Privacy Policy</h1>
      <button class="button button-clear button-primary" ng-click="modal.hide()">
         <i class="ion-close"></i>
      </button>
   </ion-header-bar>
   <ion-scroll class="padding">
      <h3>Privacy Policy</h3>
      ... [very long text] ...	        
    </ion-scroll>
</ion-modal-view>
```
Is there maybe a bug in Ionic or are there any workarounds for long texts inside modals?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Sorry, but at this time we do not support with ionic 1, although we do support windows 10 devices in Ionic 2. Sorry for any hassle this causes you and thanks for using Ionic!

**Comment by VigneshKumarDR** [comment]
Hi,

The same issue occur in Windows 8.1 also. Is any way to prevent scrolling the whole page. 
When i scroll the page means whole page is moved to top including Header.

regards,
Vignesh
