### ISSUE TITLE
Overriding $refresher-height sass variable issue

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6499]
**Ionic 2**

I overridden $refresher-height in app.variable.ts to 80px from 60px (which is default).

Then output was like this
![capture](https://cloud.githubusercontent.com/assets/15922996/15180349/9d2824aa-179e-11e6-9226-1cff788152e7.PNG)

I found still scroll-content has transform value as 60px and didn't got overridden.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker that i can use to reproduce this issue? There is a link to an Ionic 2 plunker template in the issue template for this repo. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by dheran** [comment]
:-)

**Comment by atxkm** [comment]
pullMin
