### ISSUE TITLE
Add the ability to override the config per mode

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6502]
Right now you can override the config for each platform, but you can't do it per mode (at least not easily). Should be able to do something like this:

```
@App({
  template: `<ion-nav [root]="root"></ion-nav>`
  config: {
    modes: {
      md: {
        tabbarPlacement: 'top',
      }
    }
  }
})
```

Since `md` mode, for example, affects multiple platforms.

https://github.com/driftyco/ionic/blob/2.0/ionic/config/test/config.spec.ts

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#33
