### ISSUE TITLE
Issue VirtualScroll with Slide and/or Loop slide

### ISSUE THREAD

**Issue by Elfwines** [driftyco/ionic#6504]
#### Short description of the problem: 
Actually, as a lot of issues raise the point there is a problem of slower performance because it loads the all list (I have sometimes more than 50 items). Use "virtual scroll" with slides seems difficult because Slides object use Swiper API.

I try to use loop option to create a slider that going to have as input [ngForOf] a slice of my list that change on each slide movment but the problem is that the swiper create 2 duplicated slide not responsive to data binding. It just copy past the Dom7 object of the first and the last slide on its initialization. Once the loop it's create they never change.

Here, I manage to use the swiper.createLoop() to recreate it  when I change the first and last slide of my slider. I worked wonderfully until I have ion-button in my slide (how to make stuff easily ...). And here is my real problem :

When the Dom7 is copy-past to the duplicated slides, the button is not fired because there is not anymore the output (click) ... So on duplicated slides there is no data binding

#### What behavior are you expecting?

Maybe the solution is to reproduce the loop mode but by creating duplicated slides that use the data binding.
 I have tried to figure out how it would work and I thank to create my own directive whith a differ object attach to a a array with duplicated element at the begining and at the end and here I need some help :) 

Run ionic info from terminal/cmd prompt: (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version: CLI version 1.2.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
