### ISSUE TITLE
ionic2: alert input maxlength ?

### ISSUE THREAD

**Issue by vss0705** [driftyco/ionic#6505]
```
let alert = Alert.create({
	title: 'name',
	inputs: [
		{ name: 'name', value: '' }
	],
	...
})
```
maxlength
How to Set Up ?

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

ionic2 Beta 6

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
