### ISSUE TITLE
native scroll does not update getScrollPosition() unless scroll event is issued

### ISSUE THREAD

**Issue by vance** [driftyco/ionic#6506]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

I have a timer check the position of an ion-scroll. I trace this to the screen. I need the realtime top/left values to compute other actions. This works fine in the browser using trackpad, however, on iOS, the value is only updated  intermittently, which causes jumping and inconsistent behavior for my other maths. It seems to only update when the user is actively dragging, that is, it does not take into account the deceleration. 
#### What behavior are you expecting?

I would expect it to be a continuous value when called from a `setInterval()`. I'd suggest having this function return both the target value and the current value as their own properties. 

the getScrollPosition() should be continuously updated. 

**Steps to reproduce:**
1. print the value of left coordinate from a scrollDelegate to a fixed div so you can watch it's value in realtime
2. scroll fast so there's deceleration
3. note that the value does not update until you touch it again

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.2.4
#### Plunker that shows an example of your issue

can't plunker, it's iOS only.

**Comment by vance** [comment]
I see that `getValues: function() ` does not call this.update() first like some of the other getters. Just a suggestion. I'll try it.

I may have a **hacky** workaround which is to simply measure the window-relative position of an element at [0,0] in the scroll area with the js api, `divContainer.getBoundingClientRect().left` but, of course values will be negative/inverse since they are relative to the window and not the content.

**Comment by vance** [comment]
it is a black box. even calling `divContainer.getBoundingClientRect().left;` only works in the browser. is this  a limitation of native scroll? how could one properly measure the position? I need this to be accurate as this is similar to a mapping type application.

**Comment by FlavorScape** [comment]
I would be satisfied if we could simply bubble this iOS UIScrollView property to ionic. How might I do that myself? 

`UIScrollView --> targetContentOffset`

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollViewDelegate_Protocol/index.html#//apple_ref/doc/uid/TP40006923-CH3-SW15

**Comment by danielcrk-cn** [comment]
It would be amazing to be able to get native scroll events of the WebView, as it would probably support overscroll as well. Then we could be able to create alot more native-like "pull to refresh", create elastic headers etc.

**Comment by vance** [comment]
Alas, native scroll crashes if you zoom out too far, so i'd like to adjust zoom while scrolling.... but i can't get continuous scroll events from native scroll :(

**Comment by vance** [comment]
Anything? I'm still having this issue with Ionic.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#243
