### ISSUE TITLE
ionic show a blank white screen

### ISSUE THREAD

**Issue by ChrisFuck** [driftyco/ionic#6507]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
when I start the app on devices, it just show a blank white screen.But it worked perfectly in browser

#### What behavior are you expecting?
no blank white screen

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
1.7.14

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello @ChrisFuck ! Thanks for opening an issue with us! I just need a little more info from you to help you with this issue. 

1. Are you trying to run it on an Android or IOS device when you get the issue?
2. Which version of the os (either android or IOS) is your test device running?
3. Are there any errors in the console?

**Comment by emps** [comment]
white screen can be cause of missing index.html

**Comment by ChrisFuck** [comment]
@jgw96  hi,first thanks for answering me.I run it on both Android and IOS.I have fix the problem,just because I write some code in ES6,and I change them to ES5,the problem have been solved.I am going to ask you if ionic support ES6 or not?It is a issue we gonna discuss.Thank you so much.

;D

**Comment by emps** [comment]
yes u can use babel for ionic 1, and ionic2 comes by default with es6..

**Comment by ChrisFuck** [comment]
@emps  thx guy. Do you also use the ionic and angular to create app?

**Comment by ChrisFuck** [comment]
@emps Thx guy.Nice to meet you.Do you also use the ionic and angular to create app or something else?

**Comment by jgw96** [comment]
Hello all! As it looks like this issue was solved i am going to be closing this issue. Thanks for using Ionic!
