### ISSUE TITLE
nav.popTo() not firing, does nothing and no errors.

### ISSUE THREAD

**Issue by MattDHill** [driftyco/ionic#6513]
#### Short description of the problem:
nav.popTo() just isn't firing. @mhartington asked me to submit this after glancing at the repo.

#### What behavior are you expecting?
The method should pop to a specific view controller in the stack.

**Steps to reproduce:**
1. Here is a GitHub repo that shows the problem clearly: https://github.com/MattDHill/popToSample 
2. Just follow the buttons :)

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.6

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello @MattDHill ! Thanks for opening an issue with us! I can reproduce this issue on my devices.

**Comment by adamdbradley** [comment]
@MattDHill Thanks for the issue. Actually `popTo()`'s first argument is a `ViewController` instance, and not a component class. The popTo() method is actually used internally quite a bit, and not very useful publicly, so I'm debating if it should even be public. Thanks for creating the issue, we'll look into this more.

**Comment by shaikhspear16** [comment]
Thanks for opening this issue. popTo is beneficial when you have to perform a list of actions and return to the original page where you initiated without having to set root of your navigation stack as a whole. Would be great if it be working.

I was also wishing if there is a way we can transfer data with a pop() or a popTo() as we do with push() using a navParams.

**Comment by adamdbradley** [comment]
`popTo` still works, but the first argument is a `ViewController` instance. A nav could have numerous instances of a component class, so if the popTo took a component class as the first argument it wouldn't know which one to pop back to.

**Comment by davorpeic** [comment]
+1 for the same use as @shaikhspear16 , I don't have problem with setting popTo(view), it makes completely sense how @adamdbradley explained it. 
10x

**Comment by krunaldesai79** [comment]
I am facing issue with "popTo". It is working fine if we use "popTo" directly. My scenario is different. I want to pass value from one component(page3) to another component(page1). I have created one singleton class and storing value using that singleton class. Before call "popTo", I am storing value into singleton class. By doing this "popTo" as well as "popToRoot" is not working.

If I call "popTo" without storing any value by writing code then "popTo' works fine.

It is a bug of ionic 2. Can anyone help me to resolve this issue?

**Comment by JoeMeeks** [comment]
I am attempting to use popTo in Ionic 3.1.1 but it only ever goes to the previous view (back once) regardless of which ViewController is passed to it. It appears popTo was removed from the framework documentation also: http://ionicframework.com/docs/api/navigation/NavController/#popTo
It does work as expected when passed an integer of the view index that you can get from this.navCtrl.getViews().
