### ISSUE TITLE
clearInput not working after first time

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6514]
Also need to move it to the ion-input in demos

**Comment by brandyscarney** [comment]
This actually is being caused by being focused in the input. I am going to push this back but I'd like to only show the clearInput button on focus.

**Comment by vukasin0** [comment]
My understanding on this is that it should be visible only on focus (otherwise confusing). 
I'm not gaining anything to see it on other not focused inputs.

@brandyscarney - by any chance any ETA for **2.0.0-beta.8** :)

**Comment by brandyscarney** [comment]
This will be fixed in the beta 10 release. :smile:

**Comment by joshuaohana** [comment]
@brandyscarney I am still having this same issue with RC4. In my case; however, I have a (click) event tied on an ion-input. It consistently requires two taps for the click event to fire.

- this is inside a form, inside a list
```
      <ion-item>
        <ion-label floating>Type</ion-label>
        <ion-input tappable type="text" [ngModel]="type?.name" name="type" readonly (click)="selectType()"></ion-input>
      </ion-item>
```

**Comment by jgfet** [comment]
I'm having problems getting this working at the moment too.
ionic info:
cli packages: (/Users/jgf/.nvm/versions/node/v8.2.1/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    npm  : 5.3.0
    OS   : macOS Sierra

**Comment by AlokGupta007** [comment]
Hi, 

I am facing the same issue.

**Comment by duoduoObama** [comment]
hello,I also encountered
(我也遇到了)

**Comment by astec** [comment]
I don’t think old issues are followed by Ionic team. You better create a new one if still a problem. Make sure you are using latest v4 version.
