### ISSUE TITLE
$ionicBackdrop appended to body (z-index problem)

### ISSUE THREAD

**Issue by harellevy** [driftyco/ionic#6516]
#### Short description of the problem:
I have an issue with my drawer, i want to append the backdrop to a selector i need, currently i do it manually on ionic.bundle.js hardcoded, hope there will be a fix for that

#### What behavior are you expecting?
i need the backdrop not to cover my drawer, and i have a bug that even when z-index the drawer to high number the backdrop is over it, when i try and make the z-index of its wrapper it covers totally the backdrop from the view.

my change to make it work was to hard code 

`document.querySelector('#app-wrapper').appendChild(el[0]);`

instead of 

`$document[0].body.appendChild(el[0]);`

**Which Ionic Version?**
1.5

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind making a plunker that demonstrates this issue please?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
