### ISSUE TITLE
Iframe elements added to ion-content ignores height settings

### ISSUE THREAD

**Issue by heaven** [driftyco/ionic#6517]
What we are trying to do is to insert an iframe with discourse forum inside.

The problem is that the iframe expands to match its content height, this might be eliminates the problem with scrolling but also adds other bugs. For example discourse is unable to work properly because internally there's no scroll inside the iframe element, so when user clicks the reply button the box opens at the bottom of the page, while the page itself scrolls to the top.

Also from time to time the page jumps to the top unintentionally, without any action. So you can open a page, scroll it and left for some time. After a short period of time the page jumps to the top automatically.

The code we use:

```html
<ion-content overflow-scroll="true" scroll="true" class="iframe-wrapper">
    <iframe data-tap-disabled="true" class='webPage' style="width:100%;min-height:100%" name="eventsPage" app-trust-url-as-resource="{{login_url}}"></iframe>
</ion-content>
```

The frame appear inside `div.scroll`, which has correct height covering only the viewport area, the `iframe` inside has height that matches its inner height to avoid scrolling inside iframe.

When browsing with ionic serve in google chrome it does work properly. The problem I described happens on iOS.

When browsing on Android it also does work as expected.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately we cannot support having "fullscreen" iframes such as what your doing as they are not really recommended as far as user experience goes. Also, having big iframe's like this will unfortunately get your app rejected by the google play store and the app store. Thanks for using Ionic!

**Comment by missakation** [comment]
Hello. I work with Ionic 2 and I am using Iframes for videos mp4 and youtube. Only on Android and Chrome the full screen option is not working, it is giving white screen. Is it something ionic related or the problem is from me? The full screen option is working well on all other platforms.

**Comment by eduardoRoth** [comment]
@missakation I found a fix;

Use the following CSS

```
.scroll-content {
    height: 100%;
}
```

In the page that you're including your video.
