### ISSUE TITLE
ion-item-group/ion-list-divider border not reaching end

### ISSUE THREAD

**Issue by amitailanciano** [driftyco/ionic#6518]
#### Short description of the problem:

`ion-item-group` and `ion-list-divider` styling is not consistent with `ion-list` and `ion-list-header`, border does not reach the side of the list

<img width="109" alt="screen shot 2016-05-13 at 12 43 55 am" src="https://cloud.githubusercontent.com/assets/1289466/15241478/014f5f00-18a5-11e6-833c-2509590f0b65.png">

#### What behavior are you expecting?

border reaches to the side of the list

**Steps to reproduce:**
1. put any `ion-item-divider` inside or outside of `ion-item-group`

```
<ion-item-group>
        <ion-item-divider light>Settings</ion-item-divider>
        ... some <ion-item>'s ...
        <ion-item-divider light>Settings</ion-item-divider>
        ... some <ion-item>'s ...
</ion-item-group>
``` 

**Which Ionic Version?** 1.x or 2.x

2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/S0jMjZvunRrD7rG9LG5s?p=preview

```

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by brandyscarney** [comment]
So iOS is correct with the item-group borders where the last item in a group doesn't have a border. The recommended markup is:

```
<ion-item-group>
  <ion-item-divider>
    Group 1
  </ion-item-divider>

  <ion-item>
    ...
  </ion-item>
</ion-item-group>

<ion-item-group>
  <ion-item-divider>
    Group 2
  </ion-item-divider>

  <ion-item>
    ...
  </ion-item>
</ion-item-group>
```

I fixed Material Design to work the same as iOS:

![screen shot 2016-05-20 at 10 57 44 am](https://cloud.githubusercontent.com/assets/6577830/15431963/3423bcd4-1e7a-11e6-9ff5-e964fd6b031d.png)
![screen shot 2016-05-20 at 10 58 02 am](https://cloud.githubusercontent.com/assets/6577830/15431962/3423c94a-1e7a-11e6-9517-c991f2d2f30f.png)

Thanks for the issue!
