### ISSUE TITLE
feat: Toast backdrop dismiss should re-fire click

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6519]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When Toast backdrop dismiss is enabled then first click is used to dispose the Toast but from UX point of view user expect that click would gregister wherever he clicked. If possible please re-fire that click with the same position so that use has to tap once to dispose the toast and also expect to get a response for that tap from the underlying UI.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Im sorry, but im having a hard time visualizing the issue you are having. Would you mind making a plunker that demonstrates the issue you are describing? Thanks!

**Comment by patrickmcd** [comment]
I don't think a plunker is necessary here.

@ErkoKnoll is just saying that when you click the invisible backdrop to dismiss a Toast, it would be nice if the click "carried thru" and the intended action still happened. Users might be trying to tap a button and don't realize there is anything blocking them from doing so.

**Comment by jgw96** [comment]
Ahh thanks for clarifying @patrickmcd ! Now i fully understand the issue. @ErkoKnoll Good suggestion!

**Comment by brandyscarney** [comment]
Hey, so I think the solution to this is to make the backdrop darker by default so the user knows it's there, but also have a property to remove the backdrop. If the backdrop isn't there then any content they click while the toast is open will still fire, and if you wanted to dismiss the toast you could do so on the button click. Does that work?

**Comment by ErkoKnoll** [comment]
I'd rather go with property to remove the backdrop, because most of the time toast disappears in few seconds. I just don't want to block the user interaction. I'm personally using it for notifications and by nature users shouldn't take any interaction to get rid of them.

**Comment by brandyscarney** [comment]
Ok, great. I'll work on adding this soon. Thanks for the issue!

**Comment by patrickmcd** [comment]
Maybe a listener could be added to ion-page or something when a toast is created, and any interaction caught there would do the job of the backdrop by removing the toast.

**Comment by alexbainbridge** [comment]
I am not so sure about refiring the click, however having a toast without a backdrop (so no need to prevent clicks), would be great. Also using them for notifications.

**Comment by brandyscarney** [comment]
So the backdrop was removed entirely as part of issue https://github.com/driftyco/ionic/issues/6291 and will be in the `beta.8` release. If you'd like to check it out sooner, I've released a nightly version that can be installed by running the following in a terminal:

```
npm install --save ionic-angular@2.0.0-beta.7-201605202030
```

Thanks!
