### ISSUE TITLE
iOS transitions are not working, non blocking user interaction can break app

### ISSUE THREAD

**Issue by cinkonaap** [driftyco/ionic#6521]
#### Short description of the problem:

iOS transitions using `ion-nav` are not working. This is happening both on device after building `.ipa`, or in browser (Chrome) device simulator. Most important the `click-blocker` is also not working, so you can break your application by requesting new transitions while other are still executing.

#### What behavior are you expecting?

* See transitions like in Android
* Blocking user interaction while transition, so you cannot break your application

**Steps to reproduce:**
1. Use `<ion-nav>`
2. Create some pages and use `nav.push` and `nav.pop`.
3. Serve your project using `ionic serve`
4. Open your `localhost` in Chrome, turn on Mobile device simulator, and select any iPhone or iPad device.
5. Refresh page so proper device properties gets bound
6. See how transitions are not working, and you can break your application by requesting new transitions while other are still executing

**Other information:**

* EDIT: I've also noticed that in Material Design transition main target is `pageRef`, while on iOS it's `contentRef`. It's not consistent, but maybe my `contentRef`styles are problem.

* Body class in Chrome device simulator: `ios platform-mobile platform-ios platform-ios9 platform-ios9_1 platform-iphone platform-mobileweb`

* My bet is that something is wrong in `transition-ios.js`.

**Which Ionic Version?** 2.0.0-beta.6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

* Cordova CLI: 6.1.1
* Gulp version:  CLI version 3.9.1
* Gulp local:   Local version 3.9.1
* Ionic Framework Version: 2.0.0-beta.6
* Ionic CLI Version: 2.0.0-beta.25
* Ionic App Lib Version: 2.0.0-beta.15
* Node Version: v4.4.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you be able to make a plunker that i can use to reproduce this?

**Comment by jgw96** [comment]
Hey! So i did some testing with a few of my apps and ios transitions seem to work fine, atleast for me. Im using Chrome canary to test. I would love to see a plunker that reproduces this issue!

**Comment by cinkonaap** [comment]
Ok so I can fix this issue by changing CSS of page direct children. 

I have HTML structure like this:

```
<ion-page>
  <div class="page-content">
  </div>
</ion-page>
```

`.page-content` had styles:

```
position: absolute;
top: 0; right: 0; bottom: 0; left: 0;
```

This is working on Android because `transition-md` is animating `<ion-page>` and `transition-ios` is animating `<div class="page-content">`.

This is not a bug, but a little of inconsistency. I can assume that this behaviour is on purpose.

**Comment by WHarris22** [comment]
Just to expand on the "non blocking user interaction". I think what the OP is referring to is quickly tapping a button that uses the NavPush class. In IOS, Android, and WP this causes the child page to open for each click (which is what I'm assuming the OP means when they say breaking the app).

Look at the [Ionic 2 documentation](http://ionicframework.com/docs/v2/api/components/nav/NavPush/) for a replicating example. 

To replicate:

1. Refresh the NavPush page.

1. Select IOS, Android, or Windows

1. Quickly press the "Push new page" button

1. And then when you close the child page you will have multiple instances of it that need closing

**Note** this only works when the child page has not been pushed to the stack before, once it has been pushed multiple clicks no longer cause this problem.

**Comment by jgw96** [comment]
Hello! @cinkonaap ,im glad you were able to fix your transitions issue! Would you or @WHarris22 mind making a separate issue for the navigation issue that you all are experiencing? I am going to close this issue as the first issue, the ios transitions, was fixed. Thanks for using Ionic!
