### ISSUE TITLE
Multiple Ion-Tabs overlap issue when rendered in same ion-nav-view.

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6529]
When navigating from one `ion-tabs` to another, the earlier one stays in view when it should have been hidden behind the new one.

Here is a [PLUNKER](https://plnkr.co/edit/N8NKNH?p=preview) demonstrating the issue.

Ionic Version: Tried in both 1.2.4 as well as 1.3.1

**Comment by shyamal890** [comment]
@danbucholtz Can you please have a look at this bug.

**Comment by danbucholtz** [comment]
Hi @shyamal890, yes, we'll look at it soon.

Thanks,
Dan

**Comment by shyamal890** [comment]
@danbucholtz Any updates on this? Am stuck, can't publish my app without a solution to this issue. Would really appreciate if a solution to this can be rolled out.

**Comment by danbucholtz** [comment]
Hi @shyamal890, understood.  I will get to it as soon as I can.  Is there a work around that you could consider since it appears this functionality hasn't worked in previous versions of Ionic?

Thanks,
Dan

**Comment by shyamal890** [comment]
I have no idea of how I can implement a workaround or hack. If there is a work around, I would surely like to try it out. 

The problem is, when a new tab is loaded, the old stays in foreground when it should move behind the latest one.

**Comment by shyamal890** [comment]
Ok, I tried using `ng-if="$state.includes('home.tabsm1.**')"`. Though this solves the overlap issue hiding irrelevant `ion-tabs` for the current url. There is a new problem now: current `ion-tabs` isn't visible even though `$state.includes` evaluates to `true`.

Would really appreciate some help here. @danbucholtz

**Comment by danbucholtz** [comment]
Taking a look at this now @shyamal890.

**Comment by danbucholtz** [comment]
Hi @shyamal890,

You had a few issues in your code.  Mainly in the state configuration.  Ui-router is complicated :)

Here is a zip with your working code.  Let me know if you have any questions.  It should be self explanatory.  Basically, you needed to make your abstract states abstract, and then you needed to the ion-nav-view linking correctly.  Linking probably isn't the correct term.

https://drive.google.com/file/d/0B7Xofj71-_Mba1BSUUV6Rm5oblE/view?usp=sharing

Here is a second project that I have that uses a similar concept and may be a little easier to understand.  I used it when debugging life cycle events in V1.
https://drive.google.com/file/d/0B7Xofj71-_MbXzQwV2NyX29rUzA/view?usp=sharing

Please let me know how it goes.  I am going to close this issue.

Thanks,
Dan

**Comment by shyamal890** [comment]
Thanks a lot, this solution worked perfectly for me.
