### ISSUE TITLE
passing parameters to root page from @App

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#6530]
#### Short description of the problem:
I would like the be able to pass parameters to the root page of the application.
Something very similar to the Tabs parameters

### Use case:
One of the use case for this feature:
When using the [Custom URL scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme) plugin and the application is open with an external link `myapp://reset?token=blabla`
this is when for example the user asks to reset his password, you want the like the open the right page and access the token parameter.

```js
@App({
  template: '<ion-nav [root]="rootPage" [rootParams]="urlParametesAsObject"></ion-nav>',
  config: {} // http://ionicframework.com/docs/v2/api/config/Config/
})
export class MyApp {
  constructor(private platform: Platform) {
    this.rootPage = TabsPage;
  }
}
```

**Comment by BugsBunnyBR** [comment]
Have you tried [this]
(https://github.com/driftyco/ionic-preview-app/blob/master/app/app.ts#L179)

the preview app is called in the docs with some parameters like these

http://ionicframework.com/dist/preview-app/www/?production=true&ionicplatform=windows#/action-sheets/basic

**Comment by royipressburger** [comment]
@BugsBunnyBR Hi, Im getting `cannot read property `setRoot' of undefined`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to do certain functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
