### ISSUE TITLE
Label colors are different for specific items

### ISSUE THREAD

**Issue by RamitAnandSharma** [driftyco/ionic#6533]
#### Short description of the problem:
Floating input labels look very different.

#### What behavior are you expecting?
I would expect uniform colors, etc.

**Steps to reproduce:**
1. Paste the following snippet into any Ionic v2 page
```
<ion-content>
  <ion-list >
    <ion-item >
      <ion-label floating danger >Username</ion-label>
      <ion-input type="text" placeholder="Username"></ion-input>
    </ion-item>
  </ion-list >
</ion-content>
```
 2. Click  inside the input field, Floating label color is in blue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. In material design the floating label always takes the primary color of the app so that is why your floating label is blue and not taking the danger attribute. Thanks for using Ionic!
