### ISSUE TITLE
send ionic push via API using mac osx failed

### ISSUE THREAD

**Issue by eldyvoon** [driftyco/ionic#6534]
{"meta": {"status": 422, "version": "2.0.0-beta.0", "request_id": "13d79219-abda-41f4-9eb1-791433d52850"}, "error": {"link": null, "message": "Invalid JSON in request body. For empty JSON, pass '{}'.", "type": "UnprocessableEntity"}}

I follow exactly how to setup ionic push and I got above message. There's no json issue here, this is so strange!

https://forum.ionicframework.com/t/invalid-json-in-request-body-using-ionic-push/52080

**Comment by brandyscarney** [comment]
Hey @eldyvoon, could you run `ionic info` in a terminal from inside of your project folder and paste the output here?

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-platform-issues#100
