### ISSUE TITLE
Android build not working for ionic 2

### ISSUE THREAD

**Issue by ivaylopivanov** [driftyco/ionic#6537]
Installing ionic@beta and building android, then emulating on genymotion samsung gal 6 and / or installing it on samsung tab 3 is giving a white screen

**Comment by jpmsegurado** [comment]
same issue here

**Comment by jgw96** [comment]
Hello! Thanks for opening am issue with us! Would you mind telling me what version of Android your tab 3 is running? Do you get any errors when trying to run it?

**Comment by ivaylopivanov** [comment]
Using the chrome remote debugging I was able to see the error which is the same as #4296

**Comment by ivaylopivanov** [comment]
The version of the Android on the tab is 4.2.2. The error is the same when I use the emulators.

**Comment by jgw96** [comment]
@ivaylopivanov Thanks for the info! First, are you using any external libraries that your linking to from a cdn ? Also, while we do support Android all the way back to 4.1, ionic 2 requires that you use Crosswalk if you plan on supporting android devices running versions older than 4.4. So official support is Android N back to 4.4, no crosswalk required, 4.3 back to 4.1 with crosswalk. So, if you wouldn't mind adding crosswalk to your application (which you can see how to do [here](https://github.com/driftyco/ionic-cli)) and trying again that would be awesome!

**Comment by ivaylopivanov** [comment]
@jgw96 Thanks for your fast reply, but that doesn't resolve the problem as I tried it to a newer version. However, [this](http://stackoverflow.com/questions/12319809/application-error-the-connection-to-the-server-was-unsuccessful-file-andr) does. Basically, put the following into `config.xml`

`<preference name="loadUrlTimeoutValue" value="700000" />`
