### ISSUE TITLE
Ionic2 import individual components

### ISSUE THREAD

**Issue by harshabonthu** [driftyco/ionic#6538]
Hi,
Currently all ionic2 components are included in the bundle even though they are not being used. I was thinking it would be good to include only the components that are being used to keep the bundle size minimum? Angular2-material does this by installing the core and then install only the components that are being used. 
EG: @angular2-material/core @angular2-material/checkbox

I guess with the current build this wouldn't be possible, so just checking to see if this was on the radar.

**Comment by jgw96** [comment]
Hey @harshabonthu ! Thanks for opening an issue with us. So one of the things we want to focus on in the near future is making sure our file-sizes are absolutely tiny. This would mean that your packaged up and ready to go application would not have any code that is not being used, like components that your not actually using. We are looking into using things like rollup (which the angular team is using) which does tree shaking to get rid of unused code. Hope this clears it up for you!
