### ISSUE TITLE
$ionicPopup.prompt enter support

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6541]
#### Short description of the problem:
I'd like $ionicPopup.prompt to listen to `enter` on iOS' (and Android perhaps) keyboard. It would just be a convenience.

#### What behavior are you expecting?
When I press `enter`, nothing happens.

**Steps to reproduce:**
1. Open an $ionicPopup.prompt
2. Press `enter`

**Which Ionic Version?** 1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! While we really appreciate this feature request, we are not planning on adding any new features to Ionic 1 at this time. Because of this I am going to close this issue for now. Thanks for using Ionic!
