### ISSUE TITLE
Ionic 2 (bug) - quickly tapping a button that uses NavPush will open page multiple times

### ISSUE THREAD

**Issue by WHarris22** [driftyco/ionic#6542]
#### Short description of the problem:
When you quickly tap a button that uses the NavPush class i think it causes the child page to be pushed to the stack for each click which is why multiple instances get displayed.

#### What behavior are you expecting?
While the process of adding the page to the stack / displaying it is in progress subsequent button presses should be ignored instead of adding the page to the stack / opening another instance of the child page.

**Steps to reproduce:**
1. [Using the Ionic 2 documentation](http://ionicframework.com/docs/v2/api/components/nav/NavPush/) 
2. Select IOS, Android, or Windows demo and quickly press the "Push new page" button
3. And then when you close the child page you will have multiple instances of it that need closing

**Note** this only seems to work when the child page has not been pushed to the stack before (presumably because it takes slightly longer to load giving the user time to click more than once), once it has been pushed multiple clicks no longer seem to cause this problem.

**Which Ionic Version?** 
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 8.1
Node Version: v4.4.2

**Comment by adamdbradley** [comment]
Thanks for the issue, but I think the buttons are working as expected. We do have some logic to prevent too many transitions, but we cannot full know what the user has intended.
