### ISSUE TITLE
Ionic 1.3.1 + iOS ghost click

### ISSUE THREAD

**Issue by mklilley** [driftyco/ionic#6543]
On iOS 9.2.1 when I tap on an entry in the side menu which looks like this:

`<ion-item ng-repeat="item in menu.items" menu-close ui-sref="{{::item.sref}}" ui-sref-active="activated" > <h2>{{::item.title}}</h2> </ion-item>`

the keyboard automatically pops up. In the next view there is a the textarea at the same co-ordinates as the menu item just tapped. This behaviour is made more strange by the fact that the textarea isn't actually focussed, it is just the keyboard that is up.  This has been an issue for a while (see https://github.com/driftyco/ionic/issues/4993) Does anyone have any thoughts?

Thanks for your help,

Matt

**Comment by rjgpereira** [comment]
@mklilley I have the same issue on iOS 9.3.1 with the same Ionic version. I have a div with a bunch of buttons inside. Below i have another button which expands the div above. When i click the expand button the buttons of the expanded div are clicked accordingly to the touch coordinate.
In my case, this doesn't happens always. Is it the same with you, or does it happens all the time?

**Comment by rjgpereira** [comment]
@mklilley i have a similar issue (#6750). In my case it doesn't happen always, is that your case?

**Comment by headshota** [comment]
Same issue (on ionic 1.0.0) on iOS 9.2.1. `data-tap-disabled="true"` fixes the problem, although adds a 300ms delay.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#133
