### ISSUE TITLE
bug: Ion-scroll double-scroll

### ISSUE THREAD

**Issue by alextrs** [driftyco/ionic#6544]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After upgrade to Ionic 1.3.1 I start seeing weird behavior. I see two scrollbars for ion-scroll. If you click on ion-scroll content and pull, scroll behavior is the same (it scrolls and tiny scroll bar moves), but if you use touch pad / scroll wheel they both start to scroll and scroll within scroll. Here is codepen for this issue: 

http://codepen.io/alextrs/pen/yOWOzB?editors=1010

You can see it immediately if you use Windows box as then browser default scrollbar is always visible

Downgrade to 1.1.0 and issue disappears.

Thanks,
Aliaks</span>

<span is-issue-template></span>

**Comment by sinedied** [comment]
I reproduce this issue, and would love it if anyone found a workaround. Just to add some info, I can reproduce it only on web browser, not on actual ios/android device.

**Comment by sinedied** [comment]
Any news on this? This is a serious regression when using Ionic to build web app and not hybrid app.

**Comment by sonicwong** [comment]
v1.3 still have this bug.

**Comment by jgw96** [comment]
Hello, after testing this on Chrome 53 (the latest stable) i cannot seem to reproduce this on my Macbook. What browser and what devices are you all seeing this issue on? Thanks!

**Comment by alextrs** [comment]
Hi, I just checked with 53 and it's still there. You don't see the second scrollbar because mac doesn't show it unless you scroll. Use two fingers (instead of click and pull) to scroll within list and you will soon stop seeing list entries.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#132
