### ISSUE TITLE
ion-img not supporting [src]

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic#6545]
According to the documentation, this should work for a virtual scrolling list
<ion-img [src]="img/thumbs/{{park.image}}"></ion-img>

However, I either get a white screen with nothing noted in the console, or at times

Note: These logs are from trying to load a hardcoded image that was in the root www directory.

Error: Uncaught (in promise): Template parse errors:
Parser Error: Unexpected token 'png' at column 4 in [92.png] in Page1@10:17 ("
      <ion-thumbnail item-left>
        
        <ion-img [ERROR ->][src]='92.png'></ion-img>

or

angular2-polyfills.js:528 Unhandled Promise rejection: Template parse errors:
Parser Error: Unexpected token 'png' at column 4 in [92.png] in Page1@10:17 ("
      <ion-thumbnail item-left>
        
        <ion-img [ERROR ->][src]='92.png'></ion-img>

If I change [src] to just src, the image loads and lazy loading also works as expected. Currently on 2.0.0-beta.25.

**Comment by jgw96** [comment]
Hello! With the latest release of Ionic 2 (beta.11) this does not seem to be an issue anymore. Because of this I am going to close this issue for now. Thanks for using Ionic!

**Comment by odimou** [comment]
I'm having the issue too !! 
Ionic: 3.13.2

**Comment by kensodemann** [comment]
Given the age and status of this issue, I suggest opening aa new issue with supporting code supplied via a GitHub repo.

**Comment by patelmayankce** [comment]
@chrisgriffith 

<ion-img [src]="92.png"></ion-img>

try to write something like this!
it works for me!!
