### ISSUE TITLE
bug: Navbar is overlapped to the status bar

### ISSUE THREAD

**Issue by dennyoon** [driftyco/ionic#6546]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The navbar is overlapped to the status bar when display in Ionic View.</span>

<span is-issue-template></span>

**Comment by dennyoon** [comment]
[Image attached](http://z58i.imgup.net/IMG_4977867a.png)

**Comment by jgw96** [comment]
Hello @dennyoon , thanks for opening an issue with us! Is this with the latest conference app? Could you do a `git pull` and try again please?

**Comment by dennyoon** [comment]
Hello @jgw96, I've re-clone the repository already, and it's still the same in Ionic View. Perhaps it's kind of Ionic View bugs or Ionic2 setting?

**Comment by unamix** [comment]
I have the same problem.

**Comment by brandyscarney** [comment]
Thanks for the issue! There is an issue to fix this in Ionic View with a temporary work around: https://github.com/driftyco/ionic-view-issues/issues/164
