### ISSUE TITLE
Error: Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by threezj** [driftyco/ionic#6549]
when use `ionic platform add android`

> Error: Cannot find module 'config-chain' 

ionic info

>Cordova CLI: Not installed
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.4.4

> npm -v 2.15.1

I use window 10

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the ionic-cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1007
