### ISSUE TITLE
$ionicSlides.slideChangeEnd fires one time by fast swiping

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#6550]
by swiping fast between slides, $ionicSlides.slideChangeEnd fires as u finish swiping and not for every slide.. it works ok if u swipe slower

ionic 1.3.x

as i see problem comes from Swiper
any way i found a solution listening to
vm.swiper.on('onSlidePrevStart', () => {
and 
vm.swiper.on('onSlideNextStart', () => {

works with fast swiping

so maybe $ionicSlides.slideChangeEnd can be modified to work onSlideNextEnd(swiper) , onSlidePrevEnd(swiper) instead of Swiped onSlideChangeEnd(swiper) callback

**Comment by danbucholtz** [comment]
Hi @emps,

I'll check it out.

Thanks,
Dan

**Comment by longbo666** [comment]
半年过去了，此bug进展如何？

**Comment by konsultaner** [comment]
Any news on this one?

**Comment by emps** [comment]
use 
vm.swiper.on('onSlidePrevStart', () => {
and
vm.swiper.on('onSlideNextStart', () => {

to indicate swipes

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#131
