### ISSUE TITLE
router LocationStrategy 'harcoded' within bootsrap.ts

### ISSUE THREAD

**Issue by frendopawlu** [driftyco/ionic#6552]
#### Short description of the problem:

Ideally the `LocationStrategy` is configurable as this will be 'hacky' to override from application level. 

What do you think?

#### What behavior are you expecting?

That LocationStrategy is configurable pre-bootstrap.

**Steps to reproduce:**
1. Cannot reproduce as this is a suggestion and cannot really replicate it
2. 
3.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Routing with the angular 2 router is going to change completely very soon as the angular team has deprecated the old router and are working on a new one. We have halted integrating with this router until it is more complete. Thanks for using ionic.
