### ISSUE TITLE
feat: Improve Build Process

### ISSUE THREAD

**Issue by rdesimone** [driftyco/ionic#6555]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The build process should be changed/optimized and documented:

What is needed:

1. Smaller JS package to significantly improve start time of Ionic.
2. Remove TypeScript compilation from build - the compilation step should happen in the IDE to see compilation errors immediately.
3. Obfuscating JS for production build - not only for enterprise plan.

Number 2. und 3. are already possible to implement today. A documentation would be helpful which describes the required build steps and best practices.

Maybe the CLI should provide various build options.

Thanks!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this discussion is about our build process, which is handled by our CLI, I am going to move this issue to the CLI repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1010
