### ISSUE TITLE
Ionic v2 should have a way to control hardware backButton

### ISSUE THREAD

**Issue by ryanlin1986** [driftyco/ionic#6556]
#### Short description of the problem:
In ionic v1, we can use following code to prevent backButton from closing app:
$ionicPlatform.registerBackButtonAction(function (e) {
    //Prevent the hardware backButton from closing the app
    e.preventDefault();
    return false;
});

In v2, there is no way to do this, return false doesn't prevent from closing.
platform.backButton.subscribe(function(){
      return false;
    })

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by GaneshPediredla** [comment]
For ionic 2 how can I get that functionality? (hardware back buttton for android)

**Comment by martijnlutgens** [comment]
+1

**Comment by martijnlutgens** [comment]
@GaneshPediredla it is now inplemented in the core (I think since beta5), but no way to override it. In my case I want to minimize the app instead of exiting the app when the root of the stack is reached.

**Comment by ryanlin1986** [comment]
I want give user a confirmation toast "Press back button again to exit app"

**Comment by daveshirman** [comment]
Yeah, previously this was working if you just listened to `document.addEventListener('backbutton')`, but now this is simply not working at all.  This needs to be fixed as currently there's no way to intercept the behaviour at all to customise it. Very important.

**Comment by bayssmekanique** [comment]
I can work on a PR for this feature, but I'm trying to determine if it would be better to allow overriding the default behavior by passing a replacement function, or just disable the default close behavior via a config value?  Any recommendations?

**Comment by daveshirman** [comment]
I think being able to override the function is more desirable.

**Comment by jgw96** [comment]
Hello all! This will be in the next release (beta.9) with the new `registerBackButtonAction` method. Thanks for using Ionic everyone!

**Comment by jtushar53** [comment]
Please reopen this issue as it is not working in beta10 even tried ```document.addEventListener('backbutton')```

**Comment by negreanucalin** [comment]
I have a weird issue, the event listener works if I debug the app `ionic run android -c` but without `-c` id doesn't seem to work

**Comment by Eonio** [comment]
It will only work if the user navigates to a second page. Not working at root page when the user has just opened the app. I am running the app using the command:` ionic cordova run android -l -c`

**Comment by ryanhalley** [comment]
I believe I'm having the same issue as Eonio. registerBackButtonAction() is reached, but the Back event occurs regardless of the code I have. My console.log can be seen, but my confirmExit() dialog does not appear - the app just minimises, regardless of the page I'm on (root or otherwise).
I'm testing with 'ionic cordova run android -cl', but the release build does the same; this was working fine, up until we upgraded from Ionic 3.4.0 to 3.7.0, so something seems to have gone awry, unless I've missed something.
