### ISSUE TITLE
ionic v2, when there is loading present, hardware backButton should not pop current view

### ISSUE THREAD

**Issue by ryanlin1986** [driftyco/ionic#6557]
I think it's better to give the loading an option to set how to process when hardware backButton pressed, can be dismiss the loading, do nothing, or dismiss the loading and pop current view.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We are planning on allowing users the option to customize the functionality of the back button, so look forward to that in a future release! Thanks for using Ionic!
