### ISSUE TITLE
ionic v2, should add a global config setting to add arrow-right on item globally

### ISSUE THREAD

**Issue by ryanlin1986** [driftyco/ionic#6558]
<button ion-item>
</button>
In android， there is no arrow-right icon on right, and in iOS there is, what if I want android also have arrow-right in android globally? A lot of customers feels it's unconfortable without arrow-right.
I know I can add <ion-icon name="arrow-right"> manually, but I'd like to set it globally.

**Comment by praycis-lee** [comment]
...

**Comment by praycis-lee** [comment]
whats meaning

**Comment by brandyscarney** [comment]
Thanks for the issue! This was actually added with this issue: https://github.com/driftyco/ionic/issues/5993

This comment explains how to use it: https://github.com/driftyco/ionic/issues/5993#issuecomment-224979797
