### ISSUE TITLE
bug: refresher in v2 behavior error

### ISSUE THREAD

**Issue by ryanlin1986** [driftyco/ionic#6559]
Having a custom container(not ion-list) in ion-content with vertical scroll, when I try to scroll down, it always trigger refresher pull to refresh even if vertical scroll offset of my custom container is not zero.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
