### ISSUE TITLE
Feature: nav.pop() callback in parent page like onDismiss in Modal

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6561]
**Ionic 2**

Please provide option for nav.pop() callback with arguments in parent page like onDismiss in Modal

**Comment by arlowhite** [comment]
Is #6623 similar to what you want?
I have a code example there for wrapping NavController.pop()

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! I am going to be closing this issue as a dupe of #6623 . Thanks for using Ionic!
