### ISSUE TITLE
Update to new Angular 2 Router

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6563]
**Ionic 2**

Update ionic to new Angular 2 Router

**Comment by adamdbradley** [comment]
This will still be a work in progress as the new new Angular 2 router still has some holes that does not allow us to update yet. The next release will not be integrated with the ng2 router yet, and we're working with the Angular team to solve this.

**Comment by jaruesink** [comment]
Hey @adamdbradley or whoever, I'm trying to work with the Ionic router when I had working with the getComponent, but now I'm stuck after the update and could use a nudge in the right direction.

Here's what I've got so far: http://stackoverflow.com/questions/37332251/getting-nav-through-viewchild-in-ionic-2-beta

**Comment by dheran** [comment]
@adamdbradley hope now its right time?

**Comment by itrethan** [comment]
@adamdbradley It's needed desperately. The lack of router in the ionic2 is block us from writing proper integration test. There is no easy way to land on a specific page.

Since angular team have just updated their new router (3.0), I think it's the right time to support this feature.

**Comment by paulogr** [comment]
+1

**Comment by jgw96** [comment]
Hello all! The new 3.0 alpha angular router is still too unstable to integrate smoothly into Ionic 2, but it is in a much better state than it was. We are working closely with the Angular team on this one so you can be assured that as soon as the router is ready then we will be integrating it. Thanks for using Ionic everyone!

**Comment by mtr** [comment]
Now that the new Angular 2 router has entered beta (version 3.0.0-beta.2), is there any updates?  This missing feature is the sole impediment for my team adopting `ionic` for a new project.

**Comment by mtr** [comment]
I just thought I'd supply some info relating to this that I stumbled over today (from http://blog.ionic.io/announcing-ionic-2-beta-11/): 

> Moving Forward
> ==========
> With Beta 11 out the door, our focus will now turn to Beta 12 and the Ionic 2 release candidate! 🎊 Here’s what you can expect in Beta 12:
> […]
> URL Support
> ---------
> Making the URL a first-class citizen in Ionic 2 is very important for Progressive Web Apps, so we’ll be spending some time in the next few weeks focusing on this. Stay tuned for more details in the near future!

I guess this mean that the Ionic team will be working on this issue until the next release.  :smiley: :+1:

**Comment by vintage** [comment]
It seems that it won't land in the beta12, as I didn't see any task related to it in the milestone - https://github.com/driftyco/ionic/milestone/41

Despite the release date for the URL-based router, have anyone got a workaround/idea (even dirty) for handling urls in the Ionic application in beta.11? I just need it for one feature - reminding password. If user got an email he should be able to click on the link and be redirected to the "set password form".

**Comment by jgw96** [comment]
Hello @vintage ! We are currently working on full url support for Ionic 2 and it will be in the beta.12 release. The reason it is not in a milestone is because its sort of a "surprise" feature 😄

**Comment by aksharpatel47** [comment]
@jgw96 Will there be changes in the current live reload method? As in, only the page where the changes happen reloads?

**Comment by fiznool** [comment]
I guess beta.12 never actually happened, since we now have 2.0.0-rc.0 :tada: 

However there is still no router support? Or is it just yet to be documented? :crying_cat_face:

**Comment by jgw96** [comment]
@fiznool Our deeplinker support is technically in the 2.0.0-rc.0 release, but the docs for it are currently a work in progress. Sorry about that!

**Comment by dzincolorado** [comment]
@jgw96 Will the Angular2 Router api be re-enabled so we can use it?  We were able to do so in Ionic2 beta 6, then it was disabled for Beta 7 and onwards until Angular2 finalized the Angular2 Router api.  It is exactly what we needed so I'm hoping it is re-enabled for Ionic RC.0.  Thanks.

**Comment by itrethan** [comment]
Our team needs this for integration test, currently it's just hard to navigate it to a specific page. Router seems to be the only solutions. Do you guys have any quick instructions for how to do that?

**Comment by darklx** [comment]
Hoping for the release for the beta.12 !!!
Thanks for ionic team works.

**Comment by darklx** [comment]
Does this issue fixed?We are using ionic 2 building production environment web app now,but have no route to use for a long time.....

**Comment by metzc** [comment]
@darklx have a look at Deeplinker in the current API docs. Maybe it covers your use case.

**Comment by darklx** [comment]
@metzc We have tried Deeplinker, the browser's url changed with navigation change ,but if I refresh the page,it doesn't trigger the route,the page is always home page ...

**Comment by metzc** [comment]
@darklx it does for me, so theoretically it should work

**Comment by itrethan** [comment]
@metzc It seems deeplinker is pretty buggy, url not matches up, doesn't work for modal...

**Comment by jgw96** [comment]
Hello all! We are currently working hard on the deeplinker and will be making steady improvements to it as time goes on. Since the deeplinker has been implemented I am going to go ahead and close this issue for now. If you have specific issues with the deeplinker please feel free to open issues for them. Thanks everyone!
