### ISSUE TITLE
Prepend ion to every custom event emitted

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6568]
Right now we are using the same names as native events. This is causing issues with event bubbling and we think it is confusing that we don't differentiate between what a native event is and what our custom events are. Also, there are times we override the native events which isn't good.

We're going to rename all custom events so they begin with `ion`, so where we have:

`<ion-tabs (change)="onChange($event)">`

it will be 

`<ion-tabs (ionChange)="tabsChange($event)">`

**Comment by mlynch** [comment]
Can we prepend with the component name instead? (tabChange) vs (ionChange)

**Comment by brandyscarney** [comment]
@mlynch Updated the issue to reflect the change to component names instead of `ion`.

**Comment by brandyscarney** [comment]
List of event name changes:

- **Checkbox**
  - `change` -> `checkboxChange`
- **DateTime**
  - `change` -> `datetimeChange`
  - `cancel` -> `datetimeCancel`  
- **InfiniteScroll**
  - `infinite` -> `infiniteScrollLoading`
- **Menu**
  - `opening` -> `menuOpening`
  - `opened` -> `menuOpened`
  - `closed` -> `menuClosed`
- **Option**
  - `select` -> `optionSelect`
- **Picker**
  - `change` -> `pickerChange`
- **RadioButton**
  - `select` -> `radioSelect`
- **RadioGroup**
  - `change` -> `radioChange`
- **Refresher**
  - `refresh` -> `refresherRefresh`
  - `pulling` -> `refresherPulling`
  - `start` -> `refresherStart`
- **Searchbar**
  - `input` -> `searchbarInput`
  - `blur` -> `searchbarBlur`
  - `focus` -> `searchbarFocus`
  - `cancel` -> `searchbarCancel`
  - `clear` -> `searchbarClear`
- **Segment**
  - `select` -> `segmentSelect`
- **Select**
  - `change` -> `selectChange`
  - `cancel` -> `selectCancel`
- **Slides**
  - `willChange` -> `slideWillChange`
  - `didChange` -> `slideDidChange`
  - `move` -> `slideMove`
- **TabButton**
  - `select` -> `tabSelect`
- **Tab**
  - `select` -> `tabSelect`
- **Tabs**
  - `change` -> `tabChange`
- **Toggle**
  - `change` -> `toggleChange`
- **Platform**
  - `backButton` -> `platformBackButton`
  - `pause` -> `platformPause`
  - `resume` -> `platformResume`

I wasn't sure how to handle the parent vs child component naming. I didn't touch a few event emitters that seemed internal. Will look into it more (these aren't final) and update this list until we're happy. Let me know your thoughts @adamdbradley

**Comment by adamdbradley** [comment]
For menus, let's rename them to `menuOpen` and `menuClose`. I think they had `ed` at the end so it wasn't stepping on something else to begin with.

For `Platform` let's not rename them since they're not on an element and wouldn't bubble up.

Can't say `infiniteScrollLoading` is overly awesome, but for consistency reasons it makes sense.

Overall looks good to go 👍

**Comment by adamdbradley** [comment]
Actually, should we have `menuWillOpen`, `menuDidOpen` and `menuWillClose`, `menuDidClose`?

**Comment by brandyscarney** [comment]
What about `infiniteScrollStart` similar to refresher? We could have `menuDidOpen` and `menuDidClose` but we would have to add events for the others. Not a bad idea actually.

**Comment by brandyscarney** [comment]
We decided to go back to using `ion` instead of the component name, since this API is easier because the user doesn't have to look up each event name to know which one to use.
