### ISSUE TITLE
Activator: cannot read property 'x' of null

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6569]
Try out the Horizon chat demo and page 1. When clicking (in chrome) the "Post" button, this error is thrown, and then on a second click the submit goes through:

<img width="1166" alt="screenshot 2016-05-18 13 18 40" src="https://cloud.githubusercontent.com/assets/11214/15370129/0da138dc-1cfb-11e6-8a06-4edbc36af360.png">

This is my page and form code:

https://github.com/driftyco/ionic-horizon-chat-demo/blob/0f7366e2743803384fe3ab8d1e2b959fc76dafff/app/pages/page1/page1.html#L12

```html
<ion-navbar *navbar>
  <ion-title>Horizon Chat</ion-title>
</ion-navbar>

<ion-content padding class="page1">
  <h2>Chat</h2>
  <div>
    <form (submit)="post()">
      <ion-list>
        <ion-item>
          <ion-input [(ngModel)]="chatText" palceholder="Chat" type="text"></ion-input>
          <button clear item-right type="submit">Post</button>
        </ion-item>
      </ion-list>
    </form>
  </div>
  <ion-list>
    <ion-item *ngFor="#chat of chats">
      {{chat.text}}
    </ion-item>
  </ion-list>
</ion-content>
```

**Comment by adamdbradley** [comment]
Gahh, my guess it has something to do with `(submit)` and the event not having a location. on it...
