### ISSUE TITLE
Bug: $ionicView.beforeEnter is not triggering

### ISSUE THREAD

**Issue by gvhuyssteen** [driftyco/ionic#6571]
Here is my Codepen

http://codepen.io/dagert/pen/MyMgwL

When the page loads, $ionicView.beforeEnter should be triggered.
In the **1.3.1** version of Ionic, this is not the case.

In the Codepen, I expect that the title variable to be changed in the view.

**Comment by danbucholtz** [comment]
Hi @gvhuyssteen 😄 ,

Life Cycle Events are driven [by navigation](http://ionicframework.com/docs/api/directive/ionView/), and your sample isn't using ui-router.  I agree this is a little confusing and something that could be documented better.

Please let me know if you have any questions.  In the meantime, I am going to close this issue.

Thanks,
Dan

**Comment by gvhuyssteen** [comment]
I upgraded my Ionic from v1.3.0 to v1.3.1 and that is the first thing that broke.
I'm investigating further.

Thank you.
