### ISSUE TITLE
Ionic v2 custom input inside ion-item

### ISSUE THREAD

**Issue by juanfernandoe** [driftyco/ionic#6573]
Hi,

My custom input work well but when i put it in this structure it don't appears.

<ion-item>
<ion-label floating>Search</ion-label>
<itx-tokenfield name="cities"></itx-tokenfield>    
</ion-item>

this is my component code

import {Component, Input} from 'angular2/core';
//import {IONIC_DIRECTIVES} from 'ionic-angular';

TokenField.ts
@Component({
    selector: 'itx-tokenfield',
    //directives: [IONIC_DIRECTIVES],
    templateUrl: 'build/components/TokenField.html',
})

export class ItxTokenField  {
	@Input() value;
    constructor() {

    }
}

TokenField.html
<input type="text"/>

anyone can help me?

**Comment by juanfernandoe** [comment]
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v6.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). There are a ton of awesome devs on there that will be able to help you! Thanks for using Ionic!
