### ISSUE TITLE
Hardware back button does not close tab's pages and modals.

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#6574]
#### Short description of the problem:

The current implementation of a hardware back button (ionic2, beta.6) does not take into account a case when an active tab has its own non-empty ViewController (an opened page, modal or alert). In this case an application is closed after pressing the back button.

#### What behavior are you expecting?

When a hardware button is pressed then an active item must be closed at the first (alerts, modals and etc.). Only after that an active page of a current page stack should be closed. Application should be closed if there is only a root page without any active child.

**Which Ionic Version?** 1.x or 2.x
2.x (2.0.0-beta.6-201605132240)

#### Plunker that shows an example of your issue

http://plnkr.co/edit/kLT7lDjMTN0PaUNV0Vjm?p=preview

**Comment by webprofusion-chrisc** [comment]
This would apply for Action Sheets as well (invoking the handler for the 'cancel' role).

**Comment by adamdbradley** [comment]
This should be fixed as of this commit: https://github.com/driftyco/ionic/commit/9f293e85496404364c08a8275c04f52d19dacea6

Thanks for filing the issue!
