### ISSUE TITLE
ion-content inside ion-segment

### ISSUE THREAD

**Issue by CarlosAdrianM** [driftyco/ionic#6575]
#### Short description of the problem:
The ion-content is hidden when used inside an ion-segment.
You can see in that Codepen that when you click "Two", you cannot see the list inside the ion-content: http://codepen.io/Carlos_Adrian/pen/ONYEMQ

#### What behavior are you expecting?
The ion-content shoud be visible as when it is used outside an ion-segment. It you remove the ion-segment from the Codepen, the list inside the ion-content does show.

**Steps to reproduce:**
1. Create a ion-segment with at least two divs inside (you can see it in http://codepen.io/Carlos_Adrian/pen/ONYEMQ)
2. In one of these divs, create a ion-content item.
3. Put a list inside the ion-content
4. You cannot see that ion-content (click "Two" in the Codepen, you should see the list inside the ion-content)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
https://forum.ionicframework.com/t/ion-content-inside-segment-is-not-shown/52309 

**Which Ionic Version?** 1.x or 2.x
Ionic version 2.0.0-beta.6

**Comment by dylanvdmerwe** [comment]
Why not have hidden divs that swap depending on the selected segment rather than changing the `ion-content`?

**Comment by CarlosAdrianM** [comment]
It is because of the floating action button (FAB). Take a look here: [https://forum.ionicframework.com/t/floating-action-button/38599/11](url)

**Comment by jgw96** [comment]
Hello @CarlosAdrianM ! Thanks for opening an issue with us. [Here](http://codepen.io/anon/pen/eZwgBd) is a codepen that i made that fixed the issues with your codepen. First, you needed to wrap your whole template with `<ion-content>` and secondly you needed to remove the `<ion-content>` from around the list. Once this was done everything seems to be working fine (: If you have any more issues please feel free to comment. Also, i am going to consider this issue fixed for now and close, but if you still have the issue i will happily reopen. Thanks for using Ionic!

**Comment by CarlosAdrianM** [comment]
Thanks @jgw96 , I am sure I am doing something wrong :) But in your codepen, the FAB does not fix at the bottom, but it goes up when you move through the list. That is why I put the FAB outside the ion-content. When I take the FAB outside the ion-content, and I also remove the segments, it does stay fixed at the bottom when I move down the list. That is why I think there is something that does not work properly...

Thank you

**Comment by jgw96** [comment]
Ahh, @CarlosAdrianM one second and i will make another codepen that shows how to fix that. (:

**Comment by jgw96** [comment]
@CarlosAdrianM alright, would you mind checking that codepen again? As you can see i added our `fab-fixed` attribute which fixes the issue you mentioned above.

**Comment by CarlosAdrianM** [comment]
So simple... and I was going crazy. Sorry :( Your codepen is perfect now.

Thank you very much

**Comment by jgw96** [comment]
@CarlosAdrianM haha no problem! Im glad i could help you! Thanks for using Ionic!
