### ISSUE TITLE
feat: Ionic serve cordova plugins browser support

### ISSUE THREAD

**Issue by zabojnik** [driftyco/ionic#6576]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic serve is an astonishing way for a rapid app development. But its benefits are seriously limited when relying on cordova plugins which do have browser support (e.g. facebook login, google maps) since it doesn't inject cordova. If Ionic serve were to support browser enabled cordova plugins, it would speed up development in many cases tremendously. Thanks for consideration!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the cli than the framework i will be moving this issue over to that repo. Thanks for using ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1012
