### ISSUE TITLE
Recent Ionic versions are not published to npm

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#6578]
#### Short description of the problem:

Recent versions of the ionic-sdk are not published to npm. 

#### What behavior are you expecting?

The latest versions could be installed through npm.

**Steps to reproduce:**
1. Go to https://github.com/driftyco/ionic/releases and see the latest version is _1.3.1_
2. Type in your cmd `npm info ionic-sdk` and see the latest published version is _1.2.4_

**Which Ionic Version?** 1.x or 2.x

1.x

**Ionic info**

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Ionic is now released through this npm package https://www.npmjs.com/package/ionic-angular . Sorry for the confusion!

**Comment by NoNameProvided** [comment]
Maybe renaming the package is a good idea then in the [package.json](https://github.com/driftyco/ionic/blob/master/package.json#L2 ).

Is there any difference between [ionic-angular package](https://www.npmjs.com/package/ionic-angular) and the [ionic-framework packages](https://www.npmjs.com/package/ionic-framework)? Both of them point to _driftyco/ionic_.

**Comment by jgw96** [comment]
Yep, the ionic-framework packages are for the older releases before we switched to ionic-angular.

**Comment by NoNameProvided** [comment]
Thanks for the clarification but I am still confused. What I want is to install the 1.3.4 version of ionic. But none of the packages mentioned above have this version. The _ionic-framework_ packages goes from `2.0.0-alpha.0` to `2.0.0-beta.2`, the _ionic-angular_ package goes from `2.0.0.beta.1` to `2.0.0.beta.7` and the _ionic-sdk_ packages goes from `1.0` to `1.2.4`. So which package can I install the 1.3.4 version from? 

(To get the available versions I used `npm view ionic-sdk versions`, etc..)

**Comment by jgw96** [comment]
Hey sorry should have been more clear, the latest version of ionic 1 is 1.3.1 which you can see is part of the ionic-angular package by running `npm info ionic-angular`. The exact npm tag for it is `1.3.1-201605121907`. Hope that helps!

**Comment by jlebras** [comment]
Hello, you don't provide the scss code anymore in ionic-angular ?
I had it in ionic-sdk@1.0.0 and used it for theming (overriding default variables).
For now I'm using the github url directly to install the sdk (I get the scss here obviously), or is there a better way to customize the default styles ?

**Comment by danbucholtz** [comment]
Hi @jlebras,

I suppose we could include the sass going forward.  Thanks for letting us know.

Thanks,
Dan

**Comment by dsjgordon** [comment]
Any chance the tags between git and npm can be reconciled?

I just spent a day trying to get ```ionic@2.0.0-beta.8``` to work before finally realising that is an old version, not the [v2.0.0-beta.8](https://github.com/driftyco/ionic/tags) github release.

**Comment by danbucholtz** [comment]
@dsjgordon, the npm package for V2 of the framework is `ionic-angular`.

Thanks,
Dan

**Comment by dsjgordon** [comment]
@danbucholtz Thanks, looks like the tags line up there.

Then the [documentation](http://ionicframework.com/docs/v2/getting-started/installation/) needs to be updated.  It currently states:

```$ npm install -g ionic@beta```

I guess this would be an issue for [ionic-site](https://github.com/driftyco/ionic-site) ?

**Comment by dsjgordon** [comment]
Scratch that, just had it explained in Slack :)

- npm ionic is the cli, github/ionic is the framework published to npm as ionic-angular.
- The cli will automatically use the latest ionic-angular when using ```ionic start```.
- Existing projects can be updated to newer versions of ionic-angular via ```package.json```.

**Comment by NoNameProvided** [comment]
@dsjgordon Is this explained somewhere in the webpage? If not, it should be in the install section. This confused me in the past as well.

**Comment by dsjgordon** [comment]
I agree, it's an easy stone for developers to trip over.  Perhaps a note in the docs would suffice, if not a realignment of the package names.

**Comment by danbucholtz** [comment]
We are thinking about renaming some of these things as we draw closer to general release of V2.  I think the CLI will always start with the `ionic` command but I don't necessarily think the package name needs to be `ionic`.

Do you guys have any suggestions for how you'd like to see stuff named?
