### ISSUE TITLE
Swipe And Scroll at the same time on ion-item

### ISSUE THREAD

**Issue by Tubishi** [driftyco/ionic#6579]
Hi, I have a problem when i want to swipe and scroll. It's not possible to scroll when i have (swipe) in object. Something like that : 

```
<ion-content>
 <ion-list class="list" *ngFor="#report of reportList">
      <ion-item (swipeRight)="addToFavorite(report, $event)">
          <ion-card-content>
          </ion-card-content>
      </ion-item>
 </ion-list>
</ion-content>
```

Any solution to keep the scroll even if i have a swipe on my item ?
Thank you

Ionic Version2

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.04 
Node Version: v4.0.0

**Comment by manucorporat** [comment]
@Tubishi check out my comment: https://github.com/driftyco/ionic/issues/6731#issuecomment-224752861

I will close this for the moment, since (swipeLeft) is not a ionic event, and we can't do much. try configuring hammer with the methods provided by angular 2, or using (touchmove) events directly.
