### ISSUE TITLE
Suggestion: Add a hideDelay property for $ionicLoading & ionic.views.Loading

### ISSUE THREAD

**Issue by JonathanHindi** [driftyco/ionic#658]
### Motivation

Most cases we use the Loading indicator while loading content from a webservice and want to block the the user from doing any action while the data is still loading and the view isn't rendered yet. So as angular take some time to render the view after receiving the data (the promise has been resolved) most of the time we hide the loading view inside the promise callback which hide the loading and the view is being rendered, so I suggest of adding a `hideDelay` property to give us the option to delay the hiding of the loading view until the view has completely rendered.

Like the `showDelay` property, it could be added to the config object of the `$ionicLoading.show({})` method and it would be nice if you provide an option to override the value when using the hide method as `$ionicLoading.hide(300)`. 

I am implementing it by wrapping the `loading.hide()` method with a `$timeout` but i thought it would be nice to have it in core.

**Comment by techntrails** [comment]
Would be nice to have a hideDelay or minShow option such that once the show has been called, it shows for a minimum amount of time. The goal is to reduce flicker. For example, if I show before calling http and hide when it returns, if the http only takes < 1s, it's a bad ux to show ionicLoading for < 1s too.

**Comment by jamhall** [comment]
+1 For @techntrails  suggestion

**Comment by chillyprig** [comment]
+1 For @techntrails suggestion

**Comment by beebun** [comment]
+1 For @techntrails suggestion

**Comment by Fayozjon** [comment]
Bun

http://ongoo.cz/forex-dollar

24.03.2015, 15:38, "Bun suwanparsert" <notifications@github.com>:+1 For  suggestion

**Comment by Fayozjon** [comment]
chillyprig

http://thefitfactory.net/android

24.03.2015, 15:37, "chillyprig" <notifications@github.com>:+1 For  suggestion

**Comment by mikesol** [comment]
+1 For @techntrails suggestion

**Comment by rrharvey** [comment]
+1 For @techntrails suggestion

Delay is a nice option but once I do display it, after a few hundred milliseconds or so, I don't want it to get hidden 50-100 milliseconds after that.

**Comment by tbro028** [comment]
+1

**Comment by jrbistuer** [comment]
+1
