### ISSUE TITLE
ion-radio not setting value by default if values list is objects

### ISSUE THREAD

**Issue by wggley** [driftyco/ionic#6583]
#### Short description of the problem:

If using a object data for value, it won't mark as checked.
#### What behavior are you expecting?

Mark ion-radio as checked.

**Which Ionic Version?** 1.x or 2.x
1.x

Codepen using Ionic site sample example
http://codepen.io/wggley/pen/YqoreQ

**Comment by Tudes** [comment]
It should be easy to achieve this with lodash or underscore.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#130
