### ISSUE TITLE
List Typing missing close()

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic#6586]
#### Short description of the problem:
When building, the following TypeScript error is shown in the console: Property 'close' does not exist on type 'List'.
The function works as expected, just the console is reporting an error. Also this function is not shown by the code hinting in Code.

#### What behavior are you expecting?
The typing for the close function for a sliding list item should be included

**Steps to reproduce:**
1. Create a list with sliding buttons
2. In the component, create a function to programmatically close the row.
3. Compile the app.

```
slidingItem.close();
```

**Which Ionic Version?** 1.x or 2.x
2.0b7

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment]
Hey! Could you show me your code to grab the list? `close` isn't a function of list but it is a function of `ItemSliding`. So for example to grab and close all sliding items in a list you could use the following:

```
<ion-list #myList>
  <ion-item-sliding *ngFor="let data of items" #item>
    <ion-item text-wrap detail-push>
      <h3>ng-for {{data}}</h3>
    </ion-item>
    <ion-item-options>
      <button primary (click)="archive(item)">Archive</button>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```

then in the `@Page` you could call a function on button click:

```
  @ViewChild('myList', {read: List}) list: List;
  @ViewChild('item', {read: ItemSliding}) slidingItem: ItemSliding;

  constructor(private app: IonicApp, private nav: NavController) {

  }

  closeOpened() {
    this.slidingItem.close();
    this.list.closeSlidingItems();
  }
}
```

So we're grabbing the sliding item and assigning it to `slidingItem` then calling the `close` method, and also closing all sliding items on the `list`.

Thanks!

**Comment by chrisgriffith** [comment]
<ion-list>
        <ion-item-sliding *ngFor="let task of tasks" #slidingItem>-->
            <ion-item [ngClass]="{taskDone: task.status == 'done'}">
                {{task.title}}
            </ion-item>
            <ion-item-options>
                <button secondary (click)="markAsDone(slidingItem, task)">
                    <ion-icon name="checkmark"></ion-icon>
                </button>
                <button danger (click)="removeTask(slidingItem, task)">
                    <ion-icon name="trash"></ion-icon>
                </button>
            </ion-item-options>
        </ion-item-sliding>
    </ion-list>

And the .ts code

import {Page, List} from 'ionic-angular';
import {Dialogs} from 'ionic-native';

@Page({
    templateUrl: 'build/pages/tasklist/tasklist.html'
})
export class TaskListPage {
    tasks: Array<Object> = [];
    task: Object;
    active: Boolean = true;
    constructor() {
        this.tasks = [
             { title: 'Milk', status: 'open' },
             { title: 'Eggs', status: 'done' },
             { title: 'Syrup', status: 'open' },
             { title: 'Pancake Mix', status: 'open' }
        ];
    }

    markAsDone(slidingItem: List, task: Object) {
        task.status = "done";
        slidingItem.close();
    }

    removeTask(slidingItem: List, task: Object) {
        task.status = "removed";
        
        let index = this.tasks.indexOf(task);
        if (index > -1) {
             this.tasks.splice(index, 1);
        }
        slidingItem.close();
    }
}

**Comment by brandyscarney** [comment]
Ok so the reason it works is because it is actually passing a reference to `ItemSliding` (because `#slidingItem` is on the `<ion-item-sliding>` not the `<ion-list>`) and that does have the `close()` method. Basically, you're setting the wrong type in the function, it should be `ItemSliding`, not `List`. If you log the `slidingItem` in your function you'll see something like this:

![screen shot 2016-05-21 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/6577830/15450105/ae61b960-1f60-11e6-95d5-99a869dc276a.png)

So you need to change your functions from:

```
markAsDone(slidingItem: List, task: Object) {
```

to

```
markAsDone(slidingItem: ItemSliding, task: Object) {
```

**Comment by chrisgriffith** [comment]
I think an unnamed Developer Advocate might have told me just to use list ;)

**Comment by brandyscarney** [comment]
@chrisgriffith I added some documentation for it so hopefully it will be cleared up. :)

**Comment by kharatps02** [comment]
I'm facing same issue in Ionic version  ^2.0.0-rc.0
