### ISSUE TITLE
new cordova plugin use in ionic2

### ISSUE THREAD

**Issue by markxiwang** [driftyco/ionic#6588]
Hi  Dears，
I write a new cordova plugin...but I don't know how to use it in the ionic2.....
anybody how to use it ?
please help me ..thank you very much..

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I would urge you to look at the [ionic native](https://github.com/driftyco/ionic-native) repo and see how were doing it there. It would be awesome if you could submit a pr to add your plugin! From a high level standpoint were just wrapping the cordova plugins in either promises or observables. Also, as this issue isnt really an issue with the ionic framework i will be closing this issue. Thanks for using Ionic!
