### ISSUE TITLE
Ionic v2 - Tab Template - Icons are not centered (beta 7)

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#6590]
#### Short description of the problem:
The bar under the tabs in the tab template, have extra width that doesn't match their parent tab. Hope this makes sense :) 
![barebone_beta7_tab_tempate](https://cloud.githubusercontent.com/assets/3638322/15424977/876d116e-1e53-11e6-9659-c98314258452.gif)
<img width="443" alt="screen shot 2016-05-20 at 6 33 36 am" src="https://cloud.githubusercontent.com/assets/3638322/15425203/d6d06674-1e54-11e6-8b3e-698b28c0b8c4.png">

#### What behavior are you expecting?
I am expecting it to be centered.

**Steps to reproduce:**
1. ionic start tabtemp --v2 --ts

```
N/A
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 N/A

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

N/A

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by brandyscarney** [comment]
Hey, thanks for the issue! Are you running this on the browser or on a device? I am not able to reproduce it following your steps and using `ionic serve`.

**Comment by tonyawad88** [comment]
@brandyscarney  Hi Brandy, I am running in the browser, Chrome Version 50.0.2661.102 (64-bit).

**Comment by brandyscarney** [comment]
@tonyawad88 Hmm so I updated Chrome but I still can't reproduce it. :( I started a new tab project using your command `ionic start tabtemp --v2 --ts` and made no changes. Here's my info:

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014
```

Could you try removing `node_modules` and doing a fresh `npm install`? I'm not sure what is going on here. You didn't make any changes to the starter, correct?

**Comment by tonyawad88** [comment]
@brandyscarney I removed all node modules and did an ```npm install```. The output results attached below. No error, it ran successfully.

It is still off when I run with ```ionic serve```
[npm_install_output.txt](https://github.com/driftyco/ionic/files/275096/npm_install_output.txt)


I just figured it out... you know the "zoom" in/out in Chrome, I had it set to 70%... 

I apologize for wasting your time, my bad !!! :(

**Comment by brandyscarney** [comment]
@tonyawad88 It's fine! Glad it's resolved. I've definitely done something similar before so no worries. :smile:
