### ISSUE TITLE
bug: [BUG] Modal broken in beta.7

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#6601]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The 2 errors are:
1. Modals with `ion-navbar` in template will not show correctly.
2. Modals will create a backdrop that shows on top of everything blocking any user interaction, combined with the `ion-nav` not working, this blocks the app due to the user not being able to perform any action in the current modal view.</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
Digging up in the error, the alerts uses the same backdrop with same `z-index: 2`, both the `.alert-wrapper` and `.modal-wrapper` uses `z-index: 10`, however with the modal deleting the backdrop fixed the issue of interaction blocking.

There's some kind of issue with modals that makes them ignore those `z-index` values and put the backdrop on top of the modal wrapper.

**Comment by Luchillo** [comment]
I swear to god that modal has something weird, bumping the modal wrapper  `z-index` to 100 did nothing, but reducing the backdrop one from 2 to 1 fixed it, basically any value above 1 will activate this issue, that makes no sense at all.

**Comment by christofferok** [comment]
@Luchillo: I had some issues with the `ion-navbar` as well, but seems to work when I changed them to `ion-toolbar`.

**Comment by danbucholtz** [comment]
Hi @Luchillo,

I'll take a look.  I pushed this code too soon and didn't test enough.  I'm very sorry about that.

Thanks,
Dan

**Comment by jgw96** [comment]
Hey @Luchillo as a workaround until this is fixed, could you try removing the `*navbar` from the navbar and then setting the opacity of `ion-navbar` to 1 in your sass? That seemed to fix it for me. And be assured, this is just a workaround until that code is fixed (: .

**Comment by seedgabo** [comment]
That seemed to fix it for me too, another solution

**Comment by Luchillo** [comment]
@jgw96 I see @danbucholtz has seen the other issue where i referenced this issue, it seems this blocking issue only happens to me, i'll be testing the workarounds result and get back to you.

**Comment by Luchillo** [comment]
@jgw96 removing `*navbar` allowed to render the navbar, however the back button and icon are missing.

However i can replace that with toolbar and a button, the blocking issue is the bigger one that i can't find why it happens.

However i can tell that for me it happens only when using either the `Modal.create(page)` method or the `nav.present(modal)` method since i tested commenting all my custom scss and it still blocks, but navigation without modal works ok (no blocking).

**Comment by Luchillo** [comment]
Also transition animation doesn't work ok, when leaving the modal is ok but when entering it jumps straight without any animation.

**Comment by Luchillo** [comment]
Caught a little glimpse of how to fix the blocking issue, if i use the toolbar it overcomes the backdrop because it has `z-index: 10`, setting the same for the modals `ion-content` and anything else will overcome that issue, but the animation not playing at start of transition still doesn't work for me.

**Comment by Luchillo** [comment]
Here's some images that show the `z-index` properties of the components that are involved:

1. Backdrop
![backdrop](https://cloud.githubusercontent.com/assets/9698639/15476921/9c7cfe76-20d7-11e6-86d1-5cd4341471e7.png)

2. Modal-wrapper, note that even with `z-index:20` it still was under the backdrop:
![modal-wrapper](https://cloud.githubusercontent.com/assets/9698639/15476932/ae52f678-20d7-11e6-990e-cf999459a64e.png)

3. Toolbar, note the `z-index: 10` property that let it overcome the backdrop:
![toolbar](https://cloud.githubusercontent.com/assets/9698639/15476948/c4c88b2a-20d7-11e6-8eaf-89a7b5b3f388.png)

4. Content, note none `z-index` property, thus backdrop is over it, thus UX blocking for modal content:
![content](https://cloud.githubusercontent.com/assets/9698639/15476953/d5ef5064-20d7-11e6-962d-5365318eeed4.png)

Last note, seeing the way the normal page navigation works the reason this issue is not happening there is because this one doesn't add a backdrop.

**Comment by thiphariel** [comment]
Have the same issue here. Just noticed that the toolbar of the modal has ```opacity:0``` ... I just override it to 1 and my toolbar was there again

**Comment by danbucholtz** [comment]
Hi @Luchillo and others,

This should be fixed in nightly.  Please let me know if you have any issues and I'll re-open.  Thanks for contributing to Ionic!

Thanks,
Dan

**Comment by Luchillo** [comment]
I can't belive the error was so simple, say in beta.8, i had this, the two `modalEnter` and `modalLeave` was messing my modals all along:
```ts
ionicBootstrap(MyApp,
  [
    Config,
    DB,
    MasterService,
    CustomerService,
    WalletService,
    BusyCtrl,
    SyncCtrl,
    NotificationService,
    provide(PLATFORM_DIRECTIVES, {useValue: [BusyComponent, NotificatorComponent], multi: true})
  ],
  {
    modalEnter: 'modal-pop-in',
    modalLeave: 'modal-pop-out',
  })
```

**Comment by RyanHow** [comment]
Hey guys. I take it this is fixed in Beta 8? It seems to have been ok in beta7 for me, but now it 8 it's raised it's head. Maybe I'm just behind the times...

**Comment by Luchillo** [comment]
The first error about the `navbar` might be still there, but the error about blocking interaction was because i was overriding the modal enter and leave animations with `pop-in` and `pop-out`.
