### ISSUE TITLE
Slides Data Binding Issue while looping slides

### ISSUE THREAD

**Issue by emps** [driftyco/ionic#6602]
Ionic-slides data binding problem after first loop

http://codepen.io/emps/pen/MyNgjz?editors=1010

Slide A works ok by clicking ++ button but after first loop Slide A data binding to controller not working any more .. happens only with fist Slide that is Duplicated in slides

and if u loop back (refresh first the page) Slide E not working

latest Ionic v1

**Comment by emps** [comment]
any ionic v1 team support ?

**Comment by emps** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/2281169/15455440/26022872-205d-11e6-85e3-794bd21b244e.jpg)
Duplicated slide not get updated with the original slide

**Comment by emps** [comment]
i can fix the problem if i add vm.slider.updateLoop(); inside plusplus function but i think we need a real fix

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#129
