### ISSUE TITLE
bug: [Bug] ion-input type date not working in ios

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#6603]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Input type date works ok everywhere except for inside a modal, it tries to open the picker in the lower part of screen but fails and closes it again without any errors.

Subsequent tries were unsuccessful.

Ionic info output:
```sh
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```
</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
Correction, it seems to break if not initialized with any date, if the `[(ngModel)]` property has undefined, null or empty string '' it will fail to open the selector.

**Comment by jgw96** [comment]
Hey @Luchillo ! Would you mind using our new ion-datetime component instead? This should give you a better experience. Here are the docs for that component: http://ionicframework.com/docs/v2/api/components/datetime/DateTime/

**Comment by Luchillo** [comment]
I saw it before posting this issue, however when i tested it in android it showed a picker similar to the IOS one, i think that's not consistent with what android users expect as the native picker uses a calendar-like picker, was it designed to be just the style for IOS?

**Comment by jgw96** [comment]
@Luchillo Hmm weird, it should show the material design version of the datetime picker on Android. Would you mind making a quick plunker that i could test with? Thanks!

**Comment by Luchillo** [comment]
The docs itself show the android version is almost the same as the ios version.

**Comment by jgw96** [comment]
ahh ok, sorry i thought you meant it was showing the actual ios one and not that it just looked similar. So is the issue just with how it looks, or is it the functionality that is not working for you?

**Comment by Luchillo** [comment]
It works, just that i was expecting something like the native android one which shows a calendar kind like a popup or alert.

**Comment by jgw96** [comment]
@Luchillo Ok cool, thanks for the design critiques, i will forward them to the rest of the team (: I will close this for now as the functionality is working.

**Comment by Luchillo** [comment]
Ok, it works great, just the design in android wasn't the expected with the native picker, i'm sticking with the input since i found the fix for it.
