### ISSUE TITLE
Cordova installation on OSX

### ISSUE THREAD

**Issue by scooper711** [driftyco/ionic#6605]
Trying to install Ionic CLI on a Mac Air with El Capitan and export my project.  I keep doing the command to install Cordova:

sudo npm install -g cordova

.. and while it indicates that Cordova is getting installed (I run "cordova --version" and it comes back with "6.1.1", after installing Ionic (sudo npm install -g ionic) I keep running the “ionic info” command and it says that Cordova CLI is not installed.

Do I have to configure the $PATH in a certain way to have the Cordova installation recognized?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to the Ionic CLI and not the framework I will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1018
