### ISSUE TITLE
Modal in 2.0.0-beta.7 no longer adds page class name to ion-page element

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#6606]
The element has a class attribute with a generated classname like "user-login" if the page class is named "UserLogin". This is no longer the case for modals.

**Comment by wootapa** [comment]
It should probably be added to the ion-modal as well so modals can be styled differently.

**Comment by danbucholtz** [comment]
Hi @jasonwaters,

This is fixed in the nightly release.

Thanks,
Dan

**Comment by jasonwaters** [comment]
@danbucholtz this broke again on 2.0.0-beta9 😞
