### ISSUE TITLE
ion-datetime produces invalid ISO-8601 date format

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic#6608]
Date produced from Ionic2 (beta7) ion-datetime component looks like this:
"2016-01-02T01:00:00-aN:aN"

```
  <ion-item>
    <ion-label stacked>Date</ion-label>
    <ion-datetime displayFormat="MMM DD, YYYY HH:mm" [(ngModel)]="myDate"></ion-datetime>
  </ion-item>
```

Looks as though it is adding invalid characters `-aN:aN` at the end of the date string.  Tested in Chrome and Firefox only.

Also, note the value in the UI is not placed under the "stacked" label.  That should be a separate issue though.  

http://plnkr.co/edit/KUengxqzfnRqm8pwIMSp?p=preview

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by keithdmoore** [comment]
@jgw96 Can you remove the ios label and add the datetime label on this one?

**Comment by keithdmoore** [comment]
@adamdbradley Can you fix this?  This is a REAL problem.  Also, lots of styling issues with the datetime component.  Label gets bolder for some reason.  Date output does not go directly under stacked label.  Hopefully you will get all that cleaned up so this component is usable.

**Comment by adamdbradley** [comment]
@keithdmoore Cool thanks for the report, should be all fixed up in the next release. Thanks!

**Comment by keithdmoore** [comment]
@adamdbradley Should I create another issue for the cosmetic issues related to the datetime component or have you already addressed those?  Thanks for all the great work you guys are doing!

**Comment by keithdmoore** [comment]
The date is a valid date now but it is incorrect.  Please reopen.

Expected:  2016-06-12T02:40:00Z  
LOCAL is:  Sat, 11 Jun 2016 21:40:00 -05:00

Actually got:       2016-06-11T21:40:00Z
LOCAL is:  Sat, 11 Jun 2016 16:40:00 -05:00

**Comment by keithdmoore** [comment]
@jgw96 @danbucholtz  please reopen.

**Comment by jgw96** [comment]
Hey @keithdmoore, would you mind making a plunker that demonstrates the new issue? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
