### ISSUE TITLE
ion-infinite-scroll not working

### ISSUE THREAD

**Issue by ballmw** [driftyco/ionic#661]
The ion-infinite-scroll is not functioning, it is always present and does not show or hide with an active class.

**Comment by adaptivedev** [comment]
Does it matter from where I broadcast this? Ie, in an indirect callback passed to a function partial, etc?

$scope.$broadcast('scroll.infiniteScrollComplete');

**Comment by chrisbenseler** [comment]
Same with me @adaptivedev

**Comment by robksawyer** [comment]
I'm still having issues with infinite scroll. I've implemented what's outlined in the [docs](http://ionicframework.com/docs/api/directive/ionInfiniteScroll/), but it's not working as expected. The issue that I'm experiencing is outlined at [ion-infinite-scroll keep on calling the method of on-infinite](http://forum.ionicframework.com/t/resolved-issue-beta-14-ion-infinite-scroll-keep-on-calling-the-method-of-on-infinite/14301/22). Anyone, have an example of how it should be implemented?

**Comment by CarlLee** [comment]
I want to report that if there're more than one `<ion-content>` in the page, only one will work. Because `require` in the directive definition will only return the last `<ion-content>`

**Comment by abdulhafeez** [comment]
I am facing same issue as @adaptivedev 
loadMore is never called.

**Comment by babinc** [comment]
I too am having issues with ion-infinite-scroll

**Comment by Focushift** [comment]
@CarlLee thanks for possible explanation why it isn't working, looks like its time to reinvent this directive for complex apps.
