### ISSUE TITLE
Ionic 2 - Datetime-Picker opened/closed events (feature request)

### ISSUE THREAD

**Issue by ciesielskico** [driftyco/ionic#6610]
#### Short description of the problem:

I'm using cordova-googlemaps plugin and just like with the sidemenu I would like to have `opened` and `closed` events to bind to, so I can set the map "not clickable". 

Cordova-googlemaps uses an invisible overlay and when the map is "clickable", ionic elements seemingly on top of it do not receive the click/tap event, since the overlay receives all of them. 

The solution is to make the map not clickable when elements are on top of it, like when opening the sidemenu or datetime-picker and settings it back to clickable, when the top-element is dismissed again.
#### What behavior are you expecting?

`(opened)` and `(closed)` events on the `<ion-datetime>` picker.

**Which Ionic Version?** 1.x or 2.x
Ionic 2 Beta 7

**Comment by keithdmoore** [comment]
@jgw96 you might want to add the datetime label to this one.

**Comment by Kobzol** [comment]
I think that this should work: https://github.com/Kobzol/ionic/commit/37ed555b4dd907251df678b09ad8f3af69d8626f
Unfortunately I have not been able to run karma locally, it fails with an error, so there are no unit tests yet.

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#34
