### ISSUE TITLE
Feature(icon): Display ios outline icons with ion-icon[outline]

### ISSUE THREAD

**Issue by hlehmann** [driftyco/ionic#6611]
**Which Ionic Version?** 2.x

Currently
`<ion-icon name="options"></ion-icon>` equals
`<ion-icon ios="ios-options" md="md-options"></ion-icon>` 

It would be also interesting to have something like that:
`<ion-icon name="options" outline></ion-icon>` equals
 `<ion-icon ios="ios-options-outline" md="md-options"></ion-icon>`

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by zixia** [comment]
I'd like to have that.

I try to use this but it seems not support yet.

```html
    <ion-icon name="cloud-upload" outline/></ion-icon>
```

**Comment by lohithgn** [comment]
@zixia I am working on a small pet project of mine in V2.
I am using the following code:
`<ion-icon md="md-time" ios="ios-time-outline"></ion-icon>`
and I am getting the write icons ...
hope this helps

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#35

**Comment by ManigandanRaamanathan** [comment]
Any solution on accomplishing this?
