### ISSUE TITLE
ionic 2 beta 7 upgrade: issue with Promises

### ISSUE THREAD

**Issue by khamaileon** [driftyco/ionic#6612]
Since beta 7 and the use of zone.js, I can no longer use Promise.reject(). Any idea ?
```javascript
platform.ready()
  .then(log.info('platform ready'))
  .then(() => this.getOrCreateUser(this))
  .then(() => this.getOrCreateDevice(this))
  .then(() => navigator.splashscreen.hide());

getOrCreateDevice() {
  log.info('getOrCreateDevice');
  if (typeof device === 'undefined') return Promise.reject();
  ...
}
```
```
platform ready
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
EXCEPTION: Error: Uncaught (in promise): undefined
EXCEPTION: Error: Uncaught (in promise): undefined
STACKTRACE:
Error: Uncaught (in promise): undefined
    at resolvePromise (zone.js:538)
    at resolvePromise (zone.js:523)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:36)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at HTMLDocument.ZoneTask.invoke (zone.js:426)
Error: Uncaught (in promise): undefined(…)
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Did you follow [these](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#angular-update-to-200-rc1) directions when you were upgrading? Also what platform are you seeing this issue on? Chrome?

**Comment by khamaileon** [comment]
Hi @jgw96! Yes I followed all the instructions. Same issue on Chrome Version 50.0.2661.102 (64-bit) and Firefox 46.0.1.

**Comment by jgw96** [comment]
@khamaileon Thanks for the info! Would you mind making a quick plunker real quick demonstrating this issue? That would be awesome!

**Comment by khamaileon** [comment]
I don't know plunker. It won't be easy for me :(
But you can reproduce easily by creating a new project
```shell
ionic start fooBar tabs --v2
```
and replace app.js by this:
```javascript
import {App, Platform} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';


@App({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  config: {} // http://ionicframework.com/docs/v2/api/config/Config/
})
export class MyApp {
  static get parameters() {
    return [[Platform]];
  }

  constructor(platform) {
    this.rootPage = TabsPage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      this.foo();
    });
  }

  foo() {
    return Promise.reject();
  }
}
```

**Comment by jgw96** [comment]
Hey, so i may have come up with something! `Promise.reject()` takes a reason parameter, so if you do something like this 
```
const number = 1;
const err = "Promise rejected";
      
if (number !== 2) {
  return Promise.reject(err);
}
```
then it seems to work fine. Would you mind giving this a try? Thanks for using Ionic!

**Comment by khamaileon** [comment]
Same answer

```javascript
  foo() {
    return Promise.reject('bar');
  }
```
```
Unhandled Promise rejection: bar ; Zone: angular ; Task: Promise.then ; Value: bar
zone.js (line 461)
Error: Uncaught (in promise): bar
	

throw new Error("Uncaught (in promise): " + value);
```

**Comment by jgw96** [comment]
@khamaileon Sorry you are still having this issue. Would you mind trying it in a brand new Ionic 2 beta.7 project? Is this happening on a project that you updated to beta.7 or in a fresh project?

**Comment by jgw96** [comment]
Ok, so i think i have the final solution for you. Promise.reject returns a a rejected promise so you should do something like this:

```
Promise.reject(new Error("my error msg")).catch(error => {  console.log("My error msg: ", error.msg)});
```
hopefully this finally fixes the issue for you! Sorry, i should have thought of this earlier.

**Comment by khamaileon** [comment]
It works fine, great!
Do you know why it worked on before beta 7 ?
Is it due to transpiling or something like this ?

**Comment by khamaileon** [comment]
I spoke too soon. It just catchs the error. The next then is called while it shouldn’t be.
```javascript
    Promise.reject(new Error('fail'))
      .catch(error => console.log(error.msg))
      .then(console.log('is called'));
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject

**Comment by khamaileon** [comment]
https://strongloop.com/strongblog/comparing-node-js-promises-trycatch-zone-js-angular/

**Comment by danbucholtz** [comment]
Hi @khamaileon,

It doesn't sound like the issue that you're trying to solve is an Ionic issue.  If you have general questions about programming, [StackOverflow](http://stackoverflow.com/) is a great resource available to you.  The [Ionic forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) is also filled with very helpful people.

Please ket me know if there is a bug in Ionic we can help you out with.

Thanks,
Dan
