### ISSUE TITLE
bug(ion-input): Text not output correctly in (input) event

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6616]
#### Description of the problem:

The output from the (input) event is always 1 character behind what is actually in the textbox.

See the code below. The first option is preferred (according to Angular2), but the text raised in the searchMovie is always a character behind. The other options work as expected.

```
  <ion-item>
    <ion-label floating>Movie Name</ion-label>
    <ion-input #input type="text" (input)="searchMovie(input.value)"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label floating>Movie Name</ion-label>
    <ion-input type="text" (input)="searchMovieEvent($event)"></ion-input>
  </ion-item>

  <input #input2 type="text" (input)="searchMovie(input2.value)">
```

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/6VVdwVNjUKsDJbRxdUJp?p=preview

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by Chuckv01** [comment]
I am experiencing the same issue with Beta 7.

**Comment by brandyscarney** [comment]
I'm going to close this as I'm no longer able to reproduce this using latest. Please let me know if it's still an issue and I'll reopen. :)
