### ISSUE TITLE
Deprecated router not working with beta 7

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6617]
Ionic 2 

Plunker link http://plnkr.co/edit/O6SMLbaH0iKujoA99pM2?p=preview

I also tried with latest router too. But its not working.

**Comment by paulogr** [comment]
https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#router

The Router component was disabled on beta 7.

**Comment by dheran** [comment]
@paulogr  I was trying with Deprecated one `router-deprecated`

**Comment by jgw96** [comment]
Hey @dheran ! Sorry, but neither router is going to work as expected for now. With all the changes going on with the router on the Angular 2 side of things, we have decided to hold off on really implementing Angular router implementation until it gets more stable. While we would love to give our users a working implementation now, we have decided to hold off as it would most likely be pretty buggy. Were always shooting for bleeding edge, until its really broken (:  Thanks for using Ionic!
