### ISSUE TITLE
bug(ion-input): clearInput attribute not working

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6618]
#### Short description of the problem:
When testing in the browser and on a device, I am not able to press the close button on the ion-input that has the clearInput attribute. This means I cannot easily clear the text box. 

It appears as though the button is disabled?

Note that the input event does not seem to be firing when this button is enabled.

```
  <ion-card>
    <ion-item>
      <ion-label floating>Movie Name</ion-label>
      <ion-input  type="text" (input)='search($event)' clearInput></ion-input>
    </ion-item>
  </ion-card>
```

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/V3INKguqz8E4BopcJ21w?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by brandyscarney** [comment]
Thanks for the issue! So is the button working when you click it when you are not focused in the input? I have an open issue for fixing that issue if so: https://github.com/driftyco/ionic/issues/6514

Just trying to see if this is the same issue. :smile:

**Comment by dylanvdmerwe** [comment]
Hi @brandyscarney 

See: http://plnkr.co/edit/xz6INvvLKyTJS4TWgOhr?p=preview

The clearInput button becomes active when the focus moves off of the input field.

**Comment by brandyscarney** [comment]
Thanks for the plunker! This is the same issue as #6514 so I am going to close this one. :smile:
