### ISSUE TITLE
bug(scss): Styles not being applied correctly

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6619]
#### Short description of the problem:

I generate a new page and want to change the `ion-content` background color:
1. `ionic g page test1`
2. test1.ts, test1.scss and test1.html are generated
3. I add `@import '../pages/test1/test1';` into the app.core.scss
4. The code in test1.scss and test1.html

```
.test1 {
    ion-content {
        background-color: #f4f4f7;
    }
}
```

```
<ion-content padding class="test1">
  
</ion-content>
```

Note that the `ion-content` background color is not being applied. 

To fix this:

```
.test1-page {
    ion-content {
        background-color: #f4f4f7;
    }
}
```
```
<ion-content padding class="test1-page">
  
</ion-content>
```

Not something I can reproduce in a plunkr. 

#### What behavior are you expecting?
I find it weird why the css classes are not being applied correctly. 

**Which Ionic Version?** 2.x

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v5.10.1

**Comment by brandyscarney** [comment]
So when you are placing the `test1` class on the `ion-content`, the `ion-content` element isn't a child of the `test1` class, since it is on the same element. So the following:

```
<ion-content padding class="test1">
```

can be targeted using:

```
ion-content.test1 {
  background-color: #f4f4f7;
}
```

However, the `test1-page` class is automatically added to the `<ion-page>` element by Ionic, so since the structure is similar to this:

```
<ion-page class="test1-page">`
  <ion-navbar></ion-navbar>
  <ion-content></ion-content>
</ion-page>
```

The `ion-content` element is a child of the `ion-page` and that is why the following css is working:

```
.test1-page {
    ion-content {
        background-color: #f4f4f7;
    }
}
```

Does that make sense? :smile:

**Comment by dylanvdmerwe** [comment]
I guess that kind of makes sense. Bit confusing though for users...?

**Comment by brandyscarney** [comment]
@dylanvdmerwe Would it be clearer if we added a comment in the Sass file explaining where the class is coming from for the starters and generators? If you have any ideas of how we could clear this up, please let me know! Thanks. :smile:

**Comment by adamdbradley** [comment]
@dylanvdmerwe Thanks for the feedback. We'll update our docs further, thanks.
