### ISSUE TITLE
feat: Make backbutton code handling optional

### ISSUE THREAD

**Issue by rdesimone** [driftyco/ionic#6620]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The backbutton handling is implemented in node_modules\ionic-angular\components\app\app.js Line :32

See also this forum comment: https://forum.ionicframework.com/t/hardware-backbutton-not-working-beta-6/50806/14

For most cases this works fine. But there are various scenarios where it is necessary to listen to the "backbutton" event to add custom behavior. For this reason I would suggest to keep the code (which is good for most users) but add a config setting - or something similar - which disables the code. Removing the code manually is not a good practice.

Thanks!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is now implemented and will be in the beta.9 release. Thanks for using Ionic!
