### ISSUE TITLE
ToastOptions interface definition incomplete

### ISSUE THREAD

**Issue by vukasin0** [driftyco/ionic#6622]
#### Short description of the problem:
Documentation has **enableBackdropDismiss** extra property but interface definition doesn't follow.
http://ionicframework.com/docs/v2/api/components/toast/Toast/

Ionic v2 beta7, Typescript enabled project.

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201605211713
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

Current workaround:
```
interface ToastOptionsExtended extends ToastOptions {
    enableBackdropDismiss?:boolean;
}

Toast.create(<ToastOptionsExtended>{
                    message: "Toast message here",
                    duration: 5000,
                    enableBackdropDismiss: true
                })
```

Currently what's shipped with Ionic@beta7:
```
export interface ToastOptions {
    message?: string;
    cssClass?: string;
    duration?: number;
    showCloseButton?: boolean;
    closeButtonText?: string;
    dismissOnPageChange?: boolean;
}

**Comment by brandyscarney** [comment]
Hey, thanks for the issue! The backdrop was actually completely removed from the Toast component. I updated the docs to remove this so it should be live on the site soon: https://github.com/driftyco/ionic/commit/aeeae3f675f6ee4b2edb5520e931d140e80d9c4c
