### ISSUE TITLE
Intercept nav.pop()

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#6623]
### Situation

You're on a form page, and the user accidentally hits the back button (either the generated back button, or hardware back button). In stead of just going back and destroying that page, it would be great to create some sort of page hook that could run and prevent the page from navigating back.

Might even be good to extend `onPageWillLeave`

```javascript
onPageWillLeave(){
  if(!this.form.value){
   console.log("form is empty")
  } else{
    this.nav.pop();
  }
  return false;
}
```

**Comment by keithdmoore** [comment]
👍

**Comment by arlowhite** [comment]
I searched through all of the documentation and much of the Navigation code today and there really is no official way to do this. I wanted to popup an Alert before leaving the Page, but creating Alerts using nav.present() within onPageWillLeave() doesn't work (navigation continues while Alert is up). You could maybe nav.insert() a Page, but I didn't want to actually leave the current Page.

Here's a solution that works for now. Just add an **onPop()** method to any Page and return false if you don't want to pop.

Stick this code at the top of **app.ts** after you import NavController.
```typescript
let originalNavPop = NavController.prototype.pop;
(<any> NavController).prototype.pop = function() {
  // this refers to the NavController instance
  let page = (<NavController> this).getActive().instance;
  if (page.onPop) {
    console.log('Calling onPop() on active page', page);
    if (page.onPop() === false) {
      console.log('onPop() returned false, aborting pop()');
      return;
    }
  }
  originalNavPop.apply(this, arguments);
};
```

**JavaScript version** for those unfamiliar with TypeScript. (put in app.js)
```javascript
var originalNavPop = NavController.prototype.pop;
NavController.prototype.pop = function() {
  // this refers to the NavController instance
  var page = this.getActive().instance;
  if (page.onPop) {
    console.log('Calling onPop() on active page', page);
    if (page.onPop() === false) {
      console.log('onPop() returned false, aborting pop()');
      return;
    }
  }
  originalNavPop.apply(this, arguments);
};
```

**Comment by arlowhite** [comment]
Ionic2 Beta7, you can't throw an Error from onPageWillLeave to abort pop() because:

```javascript
    ViewController.prototype.willLeave = function () {
        ctrlFn(this, 'onPageWillLeave');
    };
```

```javascript
function ctrlFn(viewCtrl, fnName) {
    if (viewCtrl.instance && viewCtrl.instance[fnName]) {
        try {
            viewCtrl.instance[fnName]();
        }
        catch (e) {
            void 0;
        }
    }
}
```

I think just enhancing onPageWillLeave is a good solution for this issue. Either return a boolean or a special value to cancel pop. Or maybe throw a special CancelPop error object?

Unfortunately, modifying nav-controller.ts to support this isn't straightforward because **fireWillLeave()** is called in 3 different places. But maybe someone more familiar with the code would have a clean solution for adding the feature.

Otherwise, something like my onPop() hack could actually be added officially.

**Comment by DarrenHou1993** [comment]
In my application,return false  it still doesn't work.why?

**Comment by arlowhite** [comment]
@DarrenHou1993 Assuming you copied my code above, you should see _"Calling onPop() on active page"_ in the log (if you added an **onPop** method to the current page) regardless of the return value from onPop(). If not, there's something wrong with the code that overrides NavController.pop (or where it's being executed) Try adding a log statement first thing in the pop function to make sure the new function is actually being executed.

I haven't actually tested the JavaScript version I posted above, I just remove TypeScript notation. So maybe the JavaScript example needs to be setup differently though I don't think so.

Also, note that the code is using triple-equal ===, so if you want falseish things to stop pop (like zero), just change it to ==

**Comment by DarrenHou1993** [comment]
@arlowhite Thank you very much. It works.

**Comment by manueltaber** [comment]
Are there any chances that this feature is integrated in beta 10?
Thank you very much.

**Comment by DavidWiesner** [comment]
@mhartington  @arlowhite 

For return false on  `ionViewWillLeave` works like expected also open an `Alert` in `ionViewWillLeave` will work.

Here is an Plunkr
http://plnkr.co/edit/SQqbtdrYpN8s0apmP66o?p=preview

**Comment by manueltaber** [comment]
@DavidWiesner 
Was this feature introduced in beta 10?
I can not find any changelog...

**Comment by DavidWiesner** [comment]
@manueltaber this will work for a long time at minimum since beta 4. Only `onPageWillLeave` was renamed to `onPageWillLeave` in beta 8

**Comment by stefanhuber** [comment]
This is a very important feature!

**Comment by manueltaber** [comment]
I still don't get it running on my project...
The event ionViewWillLeave is called but the result is ignored.

**Comment by manucorporat** [comment]
@DavidWiesner you are hitting a edge case bug.
```
	ionViewWillLeave(){
		let leave = this.dismissChanges || !this.hasUnsavedChanges();
	  if(!leave){
	    this.showConfirmDismissChangesAlert();
	  }
	  return false;
	}
```

The return value is always completely ignored like @manueltaber points, it is not going back because you are showing an Alert, and that mess up with the ongoing go back procedure. Please don't depend on this buggy behaviour as a feature, in fact "your workaround" will not longer work in beta11 since we refactored the whole overlay system (Alert, ActionSheet, etc.).

**Comment by manueltaber** [comment]
@manucorporat thank you for your clearification. A new `ionCanGoBack(): boolean` callback would be a great solution!

**Comment by DavidWiesner** [comment]
@manucorporat ok you are right it's just and workaround that accidentally works

:+1: for a `ionCanGoBack(): boolean` solution

**Comment by DavidWiesner** [comment]
@arlowhite Thanks for the workaround. This will only work, if `swipeBackEnabled` is disabled on iOS

**Comment by manucorporat** [comment]
@DavidWiesner @manueltaber @stefanhuber @DarrenHou1993 @arlowhite @keithdmoore @mhartington pending PR that implements this feature: https://github.com/driftyco/ionic/pull/7305

![](https://cloud.githubusercontent.com/assets/127379/16824072/1bd8fd00-4969-11e6-8cd6-528b0914ce0f.gif)

Please share your thoughts before this becomes part of ionic!

**Comment by adamdbradley** [comment]
@manucorporat The API is great, but I'd like to see the logic behind `ionViewCanLeave` integrated into `NavController`, and not just the back button. Additionally, we should come up with a way to allow the method to be async.

**Comment by adamdbradley** [comment]
Goals:

- `ionViewCanLeave` method, on the users component, that can prevent a nav pop or push
- Can return a `boolean` (synchronous) 
- Can return an `Observable<boolean>` (async)
- `NavController` performs these tests on the hierarchy of navs, from the deepest child up to the root
- Support `ionViewCanEnter` in a later commit

**Comment by DavidWiesner** [comment]
@manucorporat yes also be aware of  `SwipeBackGesture` should respect this. 
@adamdbradley why should the `NavController` perform this on the entire hierarchy? Intercepting pop is dedicated to the current `ViewController`. And why return an `Observable<boolean>` is a `Promise<boolean>` enough?

**Comment by DavidWiesner** [comment]
@manucorporat here is a start with a synchronous version. http://plnkr.co/edit/QCues4hGpKE2Lgy5APJE?p=preview
There are still some issues with this. 
- the main menu will open when swipe back is disabled by `ionViewCanLeave`
- not asynchronous

**Comment by danbucholtz** [comment]
I agree, since it's an atomic yes or no, `Promise` makes sense to me (vs `Observable`).  Great work as always @manucorporat!

Thanks,
Dan

**Comment by sjdrew** [comment]
@DavidWiesner - I followed your solution and worked fine until I tried having the root page a tabbed page. Then it does not stop the pop of the child tab page. Not sure if any workaround for that?

**Comment by alexbainbridge** [comment]
Now that everyone is on 11, would be great to see more imminent progress on this, as the solution that used to work on 10 no longer works sadly

**Comment by MattDHill** [comment]
+1. This is an important UX feature. If a user takes the time to input information and accidentally navigates away from the page, the result is great frustration. Temporarily, I am using "hide-back-button=true" to hide the standard back button, then using "ion-buttons start" to create a custom "cancel" button that intercepts pop(). There are some obvious problems with this, including hardware back button, swipe back, and the positioning of the MD button on the right of title.

**Comment by sjdrew** [comment]
+1 , but is fixed per above, but looks like did not make it to beta 11.  I merged the changes to view-controller and navbar into my local copy of beta 11 to get this feature  of "ionViewCanGoBack()" implemented for my app and works well.

**Comment by adamdbradley** [comment]
Just as a heads up, we're currently working on implementing `ionViewCanEnter` and `ionViewCanLeave`, which can be either synchronous or asynchronous (by returning then resolving/rejecting a promise). A few more things to sort out, but it should be able to get into beta12.

**Comment by kelvindart** [comment]
+1 - this would be amazing. It stops having to use custom buttons per header. I thoroughly look forward to this.

**Comment by bvx89** [comment]
@adamdbradley Would this mean that the returned value from the promise in the `ionViewCanLeave` function from a modal, will be the data in the `modal.onDidDismiss` callback?

Or are you not planning on supporting this in modals?

**Comment by danbucholtz** [comment]
This issue is resolved in beta.12 (coming later this week) via the changes in this commit.

https://github.com/driftyco/ionic/commit/ca8cc0af2e04e9f299ba49f5fac01d28b7d2ab1d

Please let us know if you have any issues.

Thanks,
Dan

**Comment by lain-me** [comment]
@danbucholtz Will this work for this case: we are on a root page (with menu icon instead of arrow in navbar) and hardware back button pressed, then instead of default close-the-app behavior we intercept the hardware back button and set another page as a Root page? Just curious.

**Comment by danbucholtz** [comment]
@lain-me,

I'm not sure to be totally honest.

Thanks,
Dan
