### ISSUE TITLE
App crashes on push.register 

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6626]
Ionic app is crashing on `push.register(callback)`

Here is the log from `adb logcat` :
```
java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.ionicframework.testapp-1/base.apk)
05-23 20:34:58.750  2173  4989 W ActivityManager:   Force finishing activity com.ionicframework.testapp/.MainActivity
```
Ionic Version? 1.2.4 
ionic info: 
Cordova CLI: 6.1.1
Ionic Framework Version: 1.2.4-nightly-1917
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 7 SP1
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this issue has more to do with the Ionic Platform and not the Ionic framework i will be moving this issue to the correct repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-platform-issues#106
