### ISSUE TITLE
Feature Request: File Input component

### ISSUE THREAD

**Issue by gfviegas** [driftyco/ionic#6628]
As described in [this thread](https://forum.ionicframework.com/t/input-type-file-ionic-2/44798), would be nice to have a well designed and pretty file input component.

Would have a more native feel.. Also would be great to have stuff like image preview, assync upload (fire a method when input changes), extension validation, etc...

 Suggestions?

**Comment by jgw96** [comment]
Hello @gfviegas ! Thanks for opening this feature request with us. Good idea, it is definitely something to consider. Ill keep you updated on the status of this. Thanks for using Ionic!

**Comment by pjsb** [comment]
Looking also for a possible solution: http://pjsdev.blogspot.de/2016/05/ionic-2-beta-6-angular-2-styled-upload.html

**Comment by gfviegas** [comment]
Nice work @pjsb . It's missing some stuff like form support, validation and stuff but it's definitely a good start! 

Maybe we can work together to implement your component with extra stuff in ionic?  I don't have the confidence and enough knowledge to do it so as I'm still learning TS/ES6.

**Comment by pjsb** [comment]
Yes as I said it is more a very basic draft than a solution. What about the idea creating github repository, where we can work together and maybe other contributors?

**Comment by gfviegas** [comment]
Sounds good!

**Comment by pjsb** [comment]
I have created a little repository, but with quick and dirty non working code, will fix it today, then push my results. Should I add you as contributor? Or do you prefer an own Fork and Pull requests.

**Comment by webprofusion-chrisc** [comment]
On a slight tangent, here is some code I've been doing recently to do image previews/rotation before upload. Currently this submits the upload as a base64 POST.

https://github.com/openchargemap/ocm-labs/blob/master/App/Ionic2/ocm-app/app/pages/mediaupload/mediaupload.ts

**Comment by pjsb** [comment]
I will commit my current solution at the end of day, the first commit was just the first Idea ;)

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#36

**Comment by RafaelMSalvador** [comment]
Hi @jgw96! Link not working...

**Comment by vkniazeu** [comment]
Most likely, the `ionic-feature-requests` is a private repository and we can't see it.
