### ISSUE TITLE
Install error: cannot install ionic-scripts version 1.3.1 

### ISSUE THREAD

**Issue by TheWeepingGorilla** [driftyco/ionic#6629]
#### Short description of the problem:

Install failure when following steps here: [(http://www.angular-meteor.com/tutorials/whatsapp/meteor/bootstrapping)]

The error is as follows: 
`meteor npm install ionic-scripts --save
npm WARN deprecated ionic-scripts@1.3.1: Wrong dependency
npm WARN peerDependencies The peer dependency angular@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-animate@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-sanitize@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-ui-router@^0.2.13 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/Users/kilgoretrout/.meteor/packages/meteor-tool/.1.3.2_4.hkh0ef++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "ionic-scripts" "--save"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! version not found: ionic-sdk@1.3.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kilgoretrout/Code/highroad/npm-debug.log`

The error disappears and install continues normally if a previous version is used, like so:
`meteor npm install ionic-scripts@0.0.1 --save`

Edit:
Apparently ionic-scripts is asking for a version of ionic-sdk that does not exist? When I do
`npm view ionic-sdk` 
I get 
` versions: [ '1.0.0', '1.0.1', '1.1.0', '1.1.1', '1.2.0', '1.2.1', '1.2.4' ],`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this issue is related to the Ionic CLI and not the framework I will be moving this issue to the appropriate repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1022

**Comment by WebDevLyna** [comment]
Is there a solution to this? I have the exact same errors and warnings
