### ISSUE TITLE
BETA7 - Error with Tabs tutorial after upgrade from Beta 6

### ISSUE THREAD

**Issue by Ken-SixxCandles5702** [driftyco/ionic#6630]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I followed the upgrade steps for Ionic2 Beta6 to Beta7 for the basic Tabs tutorial. Works fine on hello-ionic page, then gives error on list page. Note, the tutorial code worked prior to upgrade.

#### What behavior are you expecting?
No errors

**Steps to reproduce:**
1. Create tabs tutorial in Beta 6
2. Follow upgrade steps for Beta 7
3. Run app (Chrome Version 50.0.2661.102 m, Windows 10) in developer mode
4. Click Toggle Menu button in app

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
plugin.js:43Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
browser_adapter.js:86 EXCEPTION: Error in build/app.html:8:47
browser_adapter.js:77 EXCEPTION: Error in build/app.html:8:47BrowserDomAdapter.logError @ browser_adapter.js:77BrowserDomAdapter.logGroup @ browser_adapter.js:87ExceptionHandler.call @ exception_handler.js:57(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:77 ORIGINAL EXCEPTION: TypeError: Cannot read property 'setRoot' of undefinedBrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:66(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:77 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:69(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:77 TypeError: Cannot read property 'setRoot' of undefined
    at MyApp.openPage (app.ts:43)
    at DebugAppView._View_MyApp1._handle_click_0_0 (MyApp.template.js:309)
    at view.js:316
    at dom_renderer.js:278
    at dom_events.js:20
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:45)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.runGuarded (zone.js:230)
    at NgZoneImpl.runInnerGuarded (ng_zone_impl.js:78)BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:70(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:77 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:73(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:77 DebugContext {_view: _View_MyApp1, _nodeIndex: 0, _tplRow: 8, _tplCol: 47}_nodeIndex: 0_staticNodeInfo: (...)_tplCol: 47_tplRow: 8_view: _View_MyApp1component: (...)componentRenderElement: (...)context: (...)injector: (...)providerTokens: (...)references: (...)renderNode: (...)source: (...)__proto__: ObjectBrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:74(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:78NgZone.runGuarded @ ng_zone.js:228outsideHandler @ dom_events.js:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
zone.js:260 Uncaught EXCEPTION: Error in build/app.html:8:47
ORIGINAL EXCEPTION: TypeError: Cannot read property 'setRoot' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'setRoot' of undefined
    at MyApp.openPage (http://localhost:8100/build/js/app.bundle.js:42:12)
    at DebugAppView._View_MyApp1._handle_click_0_0 (MyApp.template.js:309:35)
    at http://localhost:8100/build/js/app.bundle.js:26160:24
    at http://localhost:8100/build/js/app.bundle.js:35107:36
    at http://localhost:8100/build/js/app.bundle.js:35177:93
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:8100/build/js/app.bundle.js:30738:41)
    at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:322:35)
    at Zone.runGuarded (http://localhost:8100/build/js/zone.js:230:48)
    at NgZoneImpl.runInnerGuarded (http://localhost:8100/build/js/app.bundle.js:30771:78)
ERROR CONTEXT:
[object Object]
```

**Which Ionic Version?** 1.x or 2.x
Version 2 Beta 7

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.1.0

**Comment by VR-Architect** [comment]
Hey, my apologies for any misinformation above. It is the Ionic2 Tutorial and not the Tabs template. By bad information to my colleague. 

I started a brand new Tutorial template to see if the issue exists in a new instance. If I make these changes to the upgraded version to match the new instance version, all works as expected. So this may just be an add-on instruction for anyone upgrading the tutorial.

    // Beta 6 - app.ts file
    import {App, IonicApp, Platform, MenuController} from 'ionic-angular';
    constructor(  private app: IonicApp, private platform: Platform,  private menu: MenuController )
    let nav = this.app.getComponent('nav');
    nav.setRoot(page.component);
  
   // Beta 7 - app.ts file changes
   import {ViewChild} from '@angular/core';
   import {App, Platform, MenuController, Nav} from 'ionic-angular';
   @ViewChild(Nav) nav: Nav;
   constructor( private platform: Platform,  private menu: MenuController )
    this.nav.setRoot(page.component);

**Comment by ghenry22** [comment]
I also came across this, agree that the upgrade doc should list the required changes to app.js vs earlier default values otherwise it makes a frustrating situation if you can't figure out where it's breaking after following through step by step.

**Comment by jgw96** [comment]
Hello all! We do mention changing your imports and that app.getComponent is deprecated in the releasr/upgrade docs for beta.7. I think I may be misunderstanding the issue?

**Comment by ghenry22** [comment]
yep changing the imports is cool,

It's the other bits that aren't covered, they are updated in the starter apps so when you check those for reference you can find what to do but when the docs are so close just that last little bit to make it easier for devs makes the difference.  Then I wouldn't have spent an hour looking through the forums and then the starter apps to find out what was up.

TS version needs this added:
@ViewChild(Nav) nav: Nav;
constructor( private platform: Platform, private menu: MenuController )

JS Version needs the query section added as below:
   templateUrl: 'build/app.html',
    config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
    prodMode: true,
  queries: {
    nav: new ViewChild('content')
  },

under the openPage() function remove:
let nav = this.app.getComponent('nav');

replace with:
 this.nav.setRoot(page.component);

Really not much to it, just that little bit of extra detail to help people get updated.

**Comment by brandyscarney** [comment]
Hey, @ghenry22. Our changelog has a section on `IonicApp` that mentions that `getComponent` was removed and to change it to use `ViewChild`, is this what you mean?

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#ionicapp-df32836-references-6199

I apologize if it was hard to find, but it was included under the breaking changes section. Are you saying that it would be helpful to include the code from beta 6 in this section?

**Comment by brandyscarney** [comment]
Updated the changelog to include the previous code as well as the new code. Sorry for any confusion, we will try to use the same process in future releases. Thanks! 

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#ionicapp-df32836-references-6199

**Comment by ghenry22** [comment]
looks good, that bit of extra detail should make it easier for people updating!
