### ISSUE TITLE
bug: ionic installation fails

### ISSUE THREAD

**Issue by snrelangi** [driftyco/ionic#6631]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>C:\>npm install -g cordova ionic
is failing ... below are the validations ... 

C:\>node -v
v4.4.4

C:\>gulp -v
[19:57:27] CLI version 3.9.1

C:\>bower -v
1.7.9

C:\>npm -v
2.15.1

C:\>Cordova -v
6.1.1

Please advise.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind upgrading to node.js 5.x and npm 3? That is our "official configuration" right now until we fully support node 6. As that should fix your issue I will close this for now, but if it still does not work feel free to comment back and I will happily reopen. Thanks for using Ionic!

**Comment by JBouguima** [comment]
no issue with node 5.x  and npm 3
