### ISSUE TITLE
Feature: When NavOpts {animate: false} "back" button still animate transition

### ISSUE THREAD

**Issue by speciose** [driftyco/ionic#6635]
I'm trying to turn off all animations in my Ionic 2 app and I'm doing this with `animate: false` option inside nav controller. And it works but only when I go forward. When I click "go back" button (which is automatically generated for me) there are still animations goes on. 
Is there any option that will turn if off too? Or I need to code all back buttons manually?

**Comment by jgw96** [comment]
Hey @speciose ! Thanks for opening an issue with us! It is currently not possible to turn off all animations in an Ionic 2 app, but it is definitely worth considering adding in the future. I'm gonna keep this issue open for now, but change it to a feature request. Thanks for using Ionic!

**Comment by wouterDumon** [comment]
hi @jgw96 , we're having the same problem. we managed to lay off most animations by putting {animate:false} in the navController.pop() method also, though when pressing the hardware back button there's still an animation, navController.setTransition(false) doesn't seem to work either. Is there any update on this?

**Comment by jgw96** [comment]
@wouterDumon At the moment i do not have an update on this. I do have a question though, what is the use case behind turning off all animations?

**Comment by wouterDumon** [comment]
@jgw96 Since we have multiple kinds of navigation bars ( which we change with the current work-around: https://github.com/driftyco/ionic/issues/5556 ), it acts strange on Ios ( first the animation then the navbar change) hence the removal of the animations.

**Comment by jgw96** [comment]
@wouterDumon Ok, thanks for the feedback! I will update this issue when i have a timeline on it. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello. We are not planning on adding a feature to turn off all animations at this time, also #5556 has been fixed, so everything should work as expected now. Thanks for using Ionic!

**Comment by AhsanAyaz** [comment]
Hi @jgw96. 
I have a similar use case.
I have a bottom nav bar which has the next and previous buttons. Now if I keep pushing the pages on android, it obviously looks weird. Because the user would expect to slide the content above the bottom nav bar. But I decided to turn off animations when pushing and popping which looks way better. 
Now the only thing is that hardware back button still does the pop animation. It would be really great if we could set that too in a component somehow to turn of this animation.

**Comment by OctavioTosta** [comment]
Hi, 
I have a smilar use case to.
My app have animations in slides, i can generate a custom back button in header. So, my app have slide animations in forward and back, but with smartphone back button, "hardware back button", the animation is not slide,  it's a standard animation of fading with opacity.

As my app is for a discerning customer, it is bothered by the different animations.

How could I make the animation of the smartphone back button on slide back?

**Comment by ahamedthahaneenpm** [comment]
this.navCtrl.pop({
   animate: false
});
