### ISSUE TITLE
feat(segment): ability to add badges 

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6636]
A feature request would be the option to add a badge number to an individual segment control. Similar to the tabBadge parameter on tabs.

**Comment by changalberto** [comment]
+1

**Comment by changalberto** [comment]
@jgw96 Can we push this feature forward to Beta 10 or Beta 11 release?

**Comment by sndjones007** [comment]
+1

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by FilipSuk** [comment]
+1

**Comment by rluckez** [comment]
+1

**Comment by dumparun** [comment]
+1

**Comment by antoine92190** [comment]
+1

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#37

**Comment by lestrell** [comment]
@dylanvdmerwe @jmarginier @jgw96 This works for me.
```
                  <ion-segment-button value="any">
                      Any&nbsp;
                      <ion-badge color="secondary" item-right>1</ion-badge>
                  </ion-segment-button>
```

**Comment by choreostream** [comment]
@jgw96 Any update on this feature request?

**Comment by mansi241** [comment]
You can do so by :
```
 <ion-segment-button value="any_value" >
          Notification 
         <ion-badge color="secondary" style="vertical-align:top;" item-right>10</ion-badge>
 </ion-segment-button>
```
