### ISSUE TITLE
Bug/Feat: Make tabs Condidtional

### ISSUE THREAD

**Issue by Lindstrom1989** [driftyco/ionic#6637]
#### Short description of the problem:
In Ionic 2 beta7 and previous.
Tabs template does not work using ngIf or ngSwitch conditions.
It only works when adding a tab but does not remove a tab when condition is false.
If the condition is met more than once multiple instances of the same tab are rendered in the dom.

**Steps to reproduce:**
1. Start tabs project
2. add ngSwitch/ngIf to tabs template

For example
```
<ion-tabs tabbarPlacement="bottom" [ngSwitch]="userData.profileRole">
  <ion-tab tabIcon="home" [root]="home"></ion-tab>
  <ion-tab tabIcon="bookmark" [root]="bookmarks"></ion-tab>
  <ion-tab *ngSwitchWhen="'staff'" tabIcon="lock" [root]="admin"></ion-tab>
  <ion-tab tabIcon="settings" [root]="settings"></ion-tab>
</ion-tabs>
```

**Comment by VR-Architect** [comment]
Up vote for this bug or feature. For line-of-business applications, use of dynamically added tabs is key. We show/hide based upon permissions areas of a record.

**Comment by dylanvdmerwe** [comment]
Please see: https://github.com/driftyco/ionic/issues/5768

This can be accomplished using the `show` input property on each tab. http://ionicframework.com/docs/v2/api/components/tabs/Tab/#input-properties

**Comment by Lindstrom1989** [comment]
Although this is a reasonable ui fix this isn't removing it from the dom but merely hiding it from the user.
Someone can select it from the dom, remove the hidden attribute and click it navigating to a page not meant for them.
This is not the solution.

**Comment by adamdbradley** [comment]
@Lindstrom1989 Using the `show` input property would be the correct solution. Not having it in the DOM shouldn't matter, and if someone is hacking the DOM to view pages they shouldn't see, those pages should have the correct security on them if it's an issue.
