### ISSUE TITLE
[v2][beta7] Inset modal doesn't fit on my device screen, how can I turn it to full screen as it was before?

### ISSUE THREAD

**Issue by speciose** [driftyco/ionic#6639]
`Inset modals are now the default for larger screens, such as tablets and traditional computers.`

How can I change my modals back to it's previous full screen version? All this "inset" things ruined my styles. Sad but true(

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind explaining what happens to your styles with the inset modals? Thanks for using Ionic

**Comment by speciose** [comment]
I have this after update:
![screenshot_20160524-182109](https://cloud.githubusercontent.com/assets/8721324/15509536/83568c9a-21dc-11e6-8ca0-6f3b4c8464a6.png)
You can see that modal goes outside my screen

Maybe it's because I'm using scale
`<meta name="viewport" content="width=device-width, initial-scale=1.6, minimum-scale=1.6, maximum-scale=1.6, user-scalable=no">`

Full screen modals were perfect for me

**Comment by speciose** [comment]
Even when I make screen smaller and modal become full screen I can't scroll it.

**Comment by jgw96** [comment]
@speciose would you mind making a plunker that demonstrates this issue please?

**Comment by speciose** [comment]
I am in a big hurry today. I've changed modal component with previous beta.6 version to make it work.
I can make a repository with my app on sunday (I will remove all sensitive data but you will see what's the problem)

**Comment by danbucholtz** [comment]
Hi @speciose,

Please update your viewport line in `index.html` as follows:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
```

The modal css and media queries are fully configurable, so you can set them to whatever you want for your particular build.  See the sass [here](https://github.com/driftyco/ionic/blob/2.0/src/components/modal/modal.scss).

Thanks,
Dan
