### ISSUE TITLE
Freeze scrolling when ion-item is swiped horizontally

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#6641]
When `ion-refresher` is used with `ion-option-button` in `ion-item` and `ion-item` is swipped the scroll is not freezed. 

[Example Plunker](https://plnkr.co/edit/JmrWx8?p=preview)

How do I achieve scroll freeze while swipe?

Is this a good temporary solution?:
```
<ion-item
      on-drag-left="disableVerticalScrolling()"
      on-drag-right="disableVerticalScrolling()"></ion-item>

disableVerticalScrolling = function(){
            var scrollPos = $ionicScrollDelegate.getScrollPosition().top;
            $ionicScrollDelegate.scrollTo(0, scrollPos, false);
}
```
 

**Which Ionic Version?** 1.2.4

**Comment by jgw96** [comment]
Hey @shyamal890 ! This workaround seems to work fine for me. I will look more into this and see if there is anything we can do on our side for this issue. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hey @shyamal890 i just discussed this with my teammates and it looks like we are not going to be making a change in the framework for this. Your workaround looks awesome to everyone so i would suggest to keep using it (:

**Comment by shyamal890** [comment]
Thanks @jgw96 for replying. However, I would have to ask, have the team even tried out the workaround, because it doesn't make much of a difference!

**Comment by jgw96** [comment]
No problem @shyamal890 (: Yep we tried your workaround and it seems to work perfectly, however we are not planning on integrating it into Ionic 1 at this time. If this changes though i will definitely update this issue. Thanks!
