### ISSUE TITLE
ionic2 - custom components/content do not appear in within <ion-item> 

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6643]
#### Short description of the problem:
I have created a custom input component that I would like to place within an ion-item. The problem is that the ion-item only accepts specific components due to the following line within item.ts line 51:

```html
<ng-content select="ion-select,ion-input,ion-textarea,ion-datetime"></ng-content>
```
Anything else is ignored and not rendered. Clearly, this is a problem for any type of custom input functionality.

#### What behavior are you expecting?
I expect any content that is placed within an ion-item, and outside of the ion-label, to be rendered in the view, no matter what type of element it is.

```
insert any relevant code between the above and below backticks
```

**Which Ionic Version?**  2.x

#### Plunker that shows an example of your issue
http://plnkr.co/r0559upbpaEOxA9ARzdw

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by adamdbradley** [comment]
Good idea. Just added the `[item-content]' selector so any element can go into that location. Thanks
