### ISSUE TITLE
bug: Date format for input type element is different

### ISSUE THREAD

**Issue by debojyoti0391** [driftyco/ionic#6647]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Date format when using ionic serve is mm/dd/yyyy.But when checking the app in mobile,it is in yyyy/mm/dd.Is this related to ionic or html?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @debojyoti0391, thanks for opening an issue with us! I just have a few questions for you. When using Ionic serve what browser are you using? Also, are you running the app on ios or Android? Thanks for using Ionic!

**Comment by debojyoti0391** [comment]
Browser: chrome ver.50.0.2661.102 (latest version)
Platform: android

**Comment by jgw96** [comment]
Awesome! Would you mind making a plunker that i could use to test this issue with?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
