### ISSUE TITLE
$ionicScrollDelegate scrollBottom function causes scroll view display transformed to left

### ISSUE THREAD

**Issue by cuongbt** [driftyco/ionic#6648]
Hi, guys! 
In my case, I need to dynamically add inputs at the end of the screen. Everything seems to be ok but when I put this line in my source code "$ionicScrollDelegate.scrollBottom();", It causes scroll view transformed to left 1px. I inspected css but it doesn't have any properties like transform, left, margin,... 
I used console tool to type this line "$('.scroll').offset()" and It show that Object {top: 44, left: -1}.
When I remove "$ionicScrollDelegate.scrollBottom();" my code work well.
Here is my code:
JS: 

```
self.addContactPerson = function(){
    self.customer.contactPerson.push({
        name : "",
        phone: ""
    });
    $ionicScrollDelegate.scrollBottom();
};
```

Template code : 

```
<ion-item class='item-contact-person' ng-repeat="contact in customer.contactPerson track by $index">
    <input type="text" placeholder="{{getLabel('Fullname')}}" name="office" ng-model="contact.name"/>
    <input type="text" placeholder="{{getLabel('PhoneNumber')}}" name="office" ng-model="contact.phone"/>               
</ion-item>
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#128

**Comment by Samykills** [comment]
anyupdate on this issue?
