### ISSUE TITLE
ionic2 - <ion-slide> is not removed when *ngIf evaluates to false

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6651]
#### Short description of the problem:
When optionally showing a slide by using *ngIf, the slide is correctly shown and the pager is updated with the correct amount of bullets when it evaluates to true. However, after the *ngIf evaluates to false, the slide and the pager bullet are still visible, but the slide content disappears.

#### What behavior are you expecting?
I expect the ion-slide to be removed from the DOM and the corresponding pagination-bullet to be removed from the pager when *ngIf evaluates to false.

**Which Ionic Version?** 2.x beta.7

#### Plunker that shows an example of your issue
https://plnkr.co/edit/FY3wMgtoW7yvdVvSD6pa?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by zakton5** [comment]
After digging into it a little further, I've found that the Slide class calls rapidUpdate() in its constructor on line 910, which then notifies the swiper-widget that the slides have changed. It would make sense to simply call that function again in the Slide's ngOnDestroy() function. I'll work on a PR.

**Comment by brandyscarney** [comment]
Fixed by https://github.com/driftyco/ionic/issues/6655, thank you again. :smile:
