### ISSUE TITLE
DOM not updating when removing item from ngFor array

### ISSUE THREAD

**Issue by csysmans** [driftyco/ionic#6653]
I'm using *ngFor inside a page template (Ionic 2 beta 7).

```
<div class="child" *ngFor="let child of children">
        ...
</div>

{{children.length}}
```
I update the children array when changes are detected (add, update, remove). I do this using 'push' and 'splice'.

When an item is added or updated inside the array, the ngFor is triggered and the DOM is updated. However, when an item is removed, the array is changed, but the DOM does not remove the entry for that item.

The {{children.length}} also does not get updated when removing an item. It does when adding or updating.

Any help would be greatly appreciated.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! DO you have this same issue with a plain Angular 2 app? Thanks for using Ionic!

**Comment by csysmans** [comment]
Honestly, this is my first application I've built with Angular 2 and Ionic. But I have noticed the problem occurred multiple times in different use cases/scenarios:
- Rendering a list of divs based on an array and remove an entry from the array
- When working with dynamic tabs and removing one of the entries
- ...

Something weird is going on when removing an item from a bound array.

When I was searching on Google and StackOverflow, someone said that he had the same problem in ionic-cli beta 23 and suggested I updated to beta 25 (which I was already using). That's why I'm posting the issue here.

**Comment by jgw96** [comment]
No problem! Hmm im thinking this may be better asked on our forum (forum.ionicframework.com) or even on StackOverflow as im not sure that this is an Ionic 2 specific issue. If it does turn out be an Ionic 2 specific issue (if you cant reproduce it in a plain Angular 2 application) then just comment here and i will happily reopen this. Also, welcome to the Ionic2/Angular 2 world!
