### ISSUE TITLE
input type tel not showing number keyboard IOS (IPAD)

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [driftyco/ionic#6654]
If I add `<input type="tel">` in IOS (Ipad) I still see the complete keyboard, I should see just the numbers.

Ionic v1.3.1-nightly-3292
IOS 9.3.1 Ipad

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind making a plunker that i can use to reproduce this issue please? Thanks for using Ionic!

**Comment by cesar-oyarzun-m** [comment]
its only happens on real device, how can I do a codpen?

**Comment by jgw96** [comment]
Hello! I just asked for a plunker so that i can see your exact html (: You can just post your html here if that would be easier.

**Comment by cesar-oyarzun-m** [comment]
<ion-view view-title="New Thing">
    <ion-content>
        <form name="newThingForm" novalidate="novalidate" >
        <div class="list">
            <label class="itemnoborder item-input item-floating-label"  ng-class="{ 'has-error' : newThingForm.name.$invalid}">
                <span class="input-label">Name</span>
                <input type="text" name="name" ng-model="thing.name" ng-change="showSave()" placeholder="Name" required>
            </label>
            <div class="form-errors" ng-messages="newThingForm.name.$touched && newThingForm.name.$error ">
                <div class="form-error" ng-message="required">Name Required</div>
            </div>

            <label class="item item-input item-select">
                <div class="input-label">
                    Type
                </div>
                <select name="Subtype" ng-model="thing.subtype"
                        ng-options="subtype as subtype.desc for subtype in subtypeThing">
                </select>
            </label>
            <div ng-if="thing.subtype.value === 'scala:thing:beacon'">
                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.major.$invalid}">
                    <span class="input-label">Major</span>
                    <input type="number" numbers-only name="major" ng-model="thing.major" min="0" max="65535" placeholder="Major" required>
                </label>
                <div class="form-errors" ng-messages="newThingForm.major.$touched && newThingForm.major.$error ">
                    <div class="form-error" ng-message="required">Major Required</div>
                    <div class="form-error" ng-message="min"> Major value must be in range 0 to 65535</div>
                    <div class="form-error" ng-message="max"> Major value must be in range 0 to 65535</div>
                    <div class="form-error" ng-message="onlynumber"> Value must be a number</div>
                </div>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.minor.$invalid}">
                    <span class="input-label">Minor</span>
                    <input type="number" numbers-only name="minor" ng-model="thing.minor" min="0" max="65535"  placeholder="Minor" required>
                </label>
                <div class="form-errors" ng-messages="newThingForm.minor.$touched && newThingForm.minor.$error ">
                    <div class="form-error" ng-message="required">Minor Required</div>
                    <div class="form-error" ng-message="min"> Minor value must be in range 0 to 65535</div>
                    <div class="form-error" ng-message="max"> Minor value must be in range 0 to 65535</div>
                    <div class="form-error" ng-message="onlynumber"> Value must be a number</div>
                </div>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.proximityUuid.$invalid}">
                    <span class="input-label">Proximity UUID</span>
                    <input type="text" name="proximityUuid" ng-model="thing.proximityUuid" pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$" placeholder="Proximity UUID" required>
                </label>
                <div class="form-errors" ng-messages="newThingForm.proximityUuid.$touched && newThingForm.proximityUuid.$error ">
                    <div class="form-error" ng-message="required">Proximity UUID Required</div>
                    <div class="form-error" ng-message="pattern">Proximity UUID Invalid</div>
                </div>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.manufacturer.$invalid}">
                    <span class="input-label">Manufacturer</span>
                    <input type="text" name="manufacturer" ng-model="thing.manufacturer" ng-change="showSave()" placeholder="Manufacturer" required>
                </label>
                <div class="form-errors" ng-messages="newThingForm.manufacturer.$touched && newThingForm.manufacturer.$error ">
                    <div class="form-error" ng-message="required">Manufacturer Required</div>
                </div>
            </div>
            <div ng-if="thing.subtype.value === 'scala:thing:endpoint'">
                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.url.$invalid}">
                    <span class="input-label">URL</span>
                    <input type="url"  name="url" ng-model="thing.url"   placeholder="URL">
                </label>
                <div class="form-errors" ng-messages="newThingForm.url.$touched && newThingForm.url.$error ">
                    <div class="form-error" ng-message="url">URL must be a valid</div>
                </div>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.ip.$invalid}">
                    <span class="input-label">IP Address</span>
                    <input type="text" ip-validation ng-model="thing.ip"  name="ip" placeholder="IP Address" pattern="^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$">
                </label>
                <div class="form-errors" ng-messages="newThingForm.ip.$touched && newThingForm.ip.$error ">
                    <div class="form-error" ng-message="pattern">IP Address must be a valid IPv4 or IPv6 address</div>
                </div>

                <label class="itemnoborder item-input item-floating-label">
                    <span class="input-label">Domain Name</span>
                    <input type="text" ng-model="thing.fqdn"   placeholder="Domain Name">
                </label>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.mac.$invalid}">
                    <span class="input-label">MAC Address</span>
                    <input type="text"  ng-model="thing.mac"  name="mac" pattern="([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})" placeholder="MAC Address">
                </label>
                <div class="form-errors" ng-messages="newThingForm.mac.$touched && newThingForm.mac.$error ">
                    <div class="form-error" ng-message="pattern">MAC Address must be a valid</div>
                </div>

            </div>

            <div ng-if="thing.subtype.value === 'scala:thing:rfid'">
                <label class="itemnoborder item-input item-floating-label">
                    <span class="input-label">ID</span>
                    <input type="text" ng-model="thing.id" placeholder="ID">
                </label>

                <label class="itemnoborder item-input item-floating-label" ng-class="{ 'has-error' : newThingForm.tnf.$invalid}">
                    <span class="input-label">Type Name Format (TNF)</span>
                    <input type="tel" numbers-only name="tnf" ng-model="thing.tnf"   min="0" max="7" placeholder="Type Name Format (TNF)">
                </label>
                <div class="form-errors" ng-messages="newThingForm.tnf.$touched && newThingForm.tnf.$error">
                    <div class="form-error" ng-message="min"> TNF value must be in range 0 to 7</div>
                    <div class="form-error" ng-message="max"> TNF value must be in range 0 to 7</div>
                    <div class="form-error" ng-message="onlynumber"> Value must be a number</div>
                </div>

                <label class="itemnoborder item-input item-floating-label">
                    <span class="input-label">Payload Type</span>
                    <input type="text" ng-model="thing.type"   placeholder="Payload Type">
                </label>

                <label class="itemnoborder item-input item-floating-label">
                    <span class="input-label">Payload</span>
                    <input type="text" ng-model="thing.payload"   placeholder="Payload">
                </label>
            </div>

            <label class="itemnoborder item-input item-floating-label">
                <span class="input-label">Description</span>
                <input type="text" ng-model="thing.description"   placeholder="Description">
            </label>
        </div>
        <button class="button button-block button-royal" ng-disabled="newThingForm.$invalid" expclick="save(newThingForm)">Save</button>
            </form>
    </ion-content>
</ion-view>

  this is my html but the one important is just this   `<input type="tel">`

**Comment by rwvandenberg** [comment]
I'm also experiencing this issue with ionic v1.7.16.

**Comment by ansgmlen** [comment]
same here with Ipad-2 device/simulator

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#127
