### ISSUE TITLE
backdrop: make sure users can't scroll behind the backdrop with all overlays

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6656]

**Comment by manucorporat** [comment]
I confirm this is a real issue in iOS safari, affecting alerts, popover and actionsheet.

**Comment by Manduro** [comment]
This was an issue in v1 as well: #4793. The fix for v2 might be similar?

**Comment by brandyscarney** [comment]
@Manduro thanks for linking to that! :)

**Comment by manucorporat** [comment]
@brandyscarney @adamdbradley my fix: https://github.com/driftyco/ionic/pull/6687
