### ISSUE TITLE
bug: Ionicon not appearing with button-clear

### ISSUE THREAD

**Issue by smrubin** [driftyco/ionic#6661]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have the following HTML markup:
`<button class="icon ion-social-twitter button button-clear"></button>`

With that markup, the ionicon does not appear. After debugging I noticed that in ionic.css:8906 there is the following rule:
`.button-clear.button-clear {
    border-color: transparent;
    background: none;
    box-shadow: none;
    color: transparent; }`

It is repeating the class name twice; and particularly the color property is hiding the ionicon.

In _mixins.scss:25 is where this CSS is sourced, combining the .button-clear class twice and making the color property transparent.</span>

<span is-issue-template></span>

**Comment by amrography** [comment]
Mine css file in line **ionic.css:8880** is 
```
.button-clear.button-clear {
    border-color: transparent;
    background: none;
    box-shadow: none;
    color: #b2b2b2;
}
```
I don't have idea why the color in your css file is transparent

**Comment by smrubin** [comment]
@amrography Which version of Ionic are you using? You can see here https://github.com/driftyco/ionic/blob/master/release/css/ionic.css that line 8880 is not .button-clear.button-clear. Rather line 8906 is referencing the rule I discussed above with color: transparent.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! @smrubin and @amrography would you all mind telling me what version of Ionic you are using? Thanks for using Ionic!

**Comment by smrubin** [comment]
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
OS: Windows 8.1
Node Version: v4.3.2

**Comment by amrography** [comment]
Ionic Framework Version: 1.3.0
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
---------------

But my project still written in v1.x

**Comment by zanemcca** [comment]
+1

**Comment by Steckelfisch** [comment]
having same issue.
ionic version 1.7.17, but having this problem for 2 or 3 minor versions.

**Comment by robations** [comment]
Same here. I wonder if this is dependent on the version of sass being used to compile the assets.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#126
