### ISSUE TITLE
Item-sliding: icon not on top by default

### ISSUE THREAD

**Issue by icarus31** [driftyco/ionic#6662]
Comment from @brandyshea

Actually, the icons should be on the top by default. This is definitely a bug caused by the pipe. Adding it is causing the wrong classes to be added to the button, so it doesn't think the text is there

**Comment by brandyscarney** [comment]
Sample code to reproduce the problem:

```
  <ion-item-options>
    <button danger (click)="delete(slidingItem)">
      <ion-icon name="trash"></ion-icon>
      {{ 'DELETE' | translate }}
    </button>
    
    <button danger (click)="stop(slidingItem)">
      <ion-icon name="hand"></ion-icon>
      {{ 'STOP' | translate }}
    </button>    
  </ion-item-options>
```

**Comment by carlosfavero** [comment]
my solution.. add <strong>
`<ion-item-options>
          <button secondary (click)="openItem(item, slidingItem)">
            <ion-icon name="cash"></ion-icon><strong>Cash</strong>
          </button>
          <button danger (click)="delete(item, slidingItem)">
            <ion-icon name="trash"></ion-icon>Delete
          </button>
        </ion-item-options>`

**Comment by carlosfavero** [comment]
work for me.. add <strong>
`<ion-item-options>
          <button secondary (click)="openItem(item, slidingItem)">
            <ion-icon name="cash"></ion-icon><strong>Cash</strong>
          </button>
          <button danger (click)="delete(item, slidingItem)">
            <ion-icon name="trash"></ion-icon>Delete
          </button>
        </ion-item-options>`

**Comment by brandyscarney** [comment]
This actually happens with any interpolated text, not only with a pipe. The following will reproduce it:

```
<ion-item-sliding #item>
  <ion-item>
    One Line, Dynamic option text
  </ion-item>
  <ion-item-options>
    <button primary>
      <ion-icon name="more"></ion-icon>
      {{ moreText }}
    </button>
    <button secondary (click)="archive(item)">
      <ion-icon name="archive"></ion-icon>
      {{ archiveText }}
    </button>
  </ion-item-options>
</ion-item-sliding>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed with the `beta 9` release. :)
