### ISSUE TITLE
ionic - wrong display of blinking caret/cursor when scrolling

### ISSUE THREAD

**Issue by piyushmanurkar** [driftyco/ionic#6664]
I am calling $ionicScrollDelegate.scrollBy when focusing an input. the scroll works fine, but the cursor is displayed on the wrong place (displayed on the old place of the input before scrolling), and it stays there until start typing.

**Comment by emanfu** [comment]
I have the exact same problem. Please kindly suggest a solution. Thanks!

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
