### ISSUE TITLE
ionic2 clearInput won't show for ion-input

### ISSUE THREAD

**Issue by Emeryao** [driftyco/ionic#6666]
the button for clearInput won't appear if I use the following code:
```html
<ion-content>
    <ion-input [(ngModel)]="user.phone" clearInput type="tel"></ion-input>
</ion-content>
```
but if I put the `<ion-input>` in a `<ion-item>` tag the clearInput button shows up.

So, I'm not sure whether this behavior is designed so on purpose or not.

* ionic info
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:Win10 x64
Node Version: v6.2.0
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is expected behavior, you should always put your inputs in an Ion-item (: Thanks for using Ionic!
