### ISSUE TITLE
bug: App stuck before loading animation

### ISSUE THREAD

**Issue by asemoon** [driftyco/ionic#6671]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>Hey Everyone,

I run `ionic run ios --device -l -c` frequently which usually works fine and deploys the app to my iPad. However, sometimes when using live mode and sometimes without using it, the app gets stuck before the loading animation, so I can't even see the logs generated by gapDebug (because gapDebug shows the app as soon as the loading animation shows up, it's probably because the web view loads at that point).  

I've tried removing and rebuilding:
```
ionic platform remove ios
ionic platform add ios
ionic build ios
```
and also deleting the app + reconnecting the iPad, but none has worked so far.

ionic version : 1.7.15
cordova version: 6.2.0
ios-deploy version: 1.8.3

I really enjoy using ionic, however, this is a bug that all of our team members have experienced at some point during development and it costs us hours of frustration without any clues every time it happens. We  usually end up wiping out everything, cloning the git repo again, and going back in ionic/cordova versions.

PS: the last time it started happening was when I updated my cordova/ionic so I could start working with push notifications in ionic.

PPS: it usually helps running the app if I remove the ios platform, add it again and run the app in Xcode, however, I can't use live mode and I have to compile the app every time which is not optimal. 

I would be more than happy to provide more info and help you folks fix this issue.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is relate to the Ionic cli and not the Ionic framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1026
