### ISSUE TITLE
Ionic windows 10 mobile ng-src

### ISSUE THREAD

**Issue by kimeuichan** [driftyco/ionic#6674]
#### Short description of the problem:
Ionic ng-src is not working in windows 10 mobile

#### What behavior are you expecting?
I want to show image.

**Steps to reproduce:**
1. I download .png file and make sure it
2. I use source code that under stackoveflow url.
3. I can't find my image in running ionic app

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 http://stackoverflow.com/questions/37432971/ionic-ng-src-not-working-in-uwp-app

**Which Ionic Version?** 1.x or 2.x
1.7.14

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.4.4

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Although i really appreciate you opening this issue, we do not support Windows 10 with Ionic 1, although we do fully support Windows 10 with Ionic 2. Im very sorry i couldn't help you more with this issue. I would recommend asking on our forums (forum.ionicframework.com) as there are some awesome developers on there who would love to help you. Thanks for using Ionic!
