### ISSUE TITLE
Ionic2 - Ion-button fall to primary color after outline is set to false

### ISSUE THREAD

**Issue by Nodonisko** [driftyco/ionic#6675]
Hi,
i have a component with ion-button that is outline and secondary color. Outline is applied dynamically by variable. After load everything looks good, but when i set outline to false, button falls to primary colors.

Thats code of my button:
`<button small [outline]="active" color="secondary" (click)="selectModal()">{{buttonText}}</button>`
this will produce this:
`<button color="secondary" small="" class="disable-hover button button-outline button-small button-outline-secondary"> ... </button>`
but after change of _active_ variable to false, secondary classes are lost and output looks like this:
`<button color="secondary" small="" class="disable-hover button button-small"> ... </button>`

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:     Fedora Description:     Fedora release 23 (Twenty Three) 
Node Version: v5.11.1

//EDIT: Plunker: https://embed.plnkr.co/yRHD2EoEpk1U4tsSKjxB/

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind creating a plunker that demonstrates this issue please?

**Comment by Nodonisko** [comment]
Yes, here it it's: https://embed.plnkr.co/yRHD2EoEpk1U4tsSKjxB/

**Comment by manucorporat** [comment]
I don't think this is longer an issue since button was refactored.

**Comment by manucorporat** [comment]
Closing issue, feel free to reopen if the issue still exists.

**Comment by RicTheJamGuy** [comment]
Hello,
This issue is still happening to me. My button is in the toolbar. Would that make a difference?

Thanks in advance,
Ricardo
