### ISSUE TITLE
titles truncated in ios tab when there are 5 items

### ISSUE THREAD

**Issue by mypark** [driftyco/ionic#6679]
@brandyscarney 

The previous fix https://github.com/driftyco/ionic/issues/6056 fixes the tab spacing issue, but we should also adjust the tab padding as well since it ellipses the longer tab titles even though there is plenty of room at 5 tabs.

To reproduce try setting the tab title to something like "My Profile" when there are 5 tabs.

**Comment by brandyscarney** [comment]
This will be fixed in the beta 9 release, thanks for the issue! If anyone runs across this issue, the below Sass variable will override the padding. We decided that `0 2px` gives enough space between tabs, but please feel free to modify this variable to your use case:

```
$tabbar-ios-item-padding
```
