### ISSUE TITLE
ionic2 - <ion-toggle> sometimes simulates two clicks?

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6680]
#### Short description of the problem:
When using multiple ion-toggles, which are conditionally shown using ngIf, the next item in a list in sometimes clicked when one if the ion-toggles is hidden. This is better explained with the plunker given below.
**Note: This only happens SOME of the time. It's quite random. I'll switch the toggles a couple of times and it will work fine, but then after a bit it'll start clicking things where the hidden toggle used to be**

#### What behavior are you expecting?
I expect clicking something to not generate two clicks, or at least click-block should block the second click.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Environment: Chrome w/ ionic serve
 Could it have something to do with click-block not being activated? Even so, I don't think there should be any reason to have two clicks fire.

**Which Ionic Version?** 2.x beta.7

#### Plunker that shows an example of your issue
**Note: This plunker is set up the exact same way as my own personal code, but I could not get it to reproduce the bug for whatever reason**
https://plnkr.co/edit/FNUxp4LFDvYAL2YwijUq?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind trying this on your device with a fresh starter project and seeing if you get the same issue? I have been using toggles over the past couple of days and have not seen anything like this. Thanks for using Ionic!

**Comment by zakton5** [comment]
Sure thing. I'll try that out and get back to you

**Comment by jgw96** [comment]
Thanks!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by zakton5** [comment]
Hi @jgw96 ! I am still seeing this issue. What happens is: if a toggle is clicked, and then UI elements are displayed above that toggle (such as an ion-select) which push the toggle down, then another click will happen where the toggle used to be. The result: the select's alert will open.

Here is a demo repo: https://github.com/zakton5/ionic2-toggle-click-bug
