### ISSUE TITLE
bug: Ion-Toggle still works with PopUp on Screen

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic#6681]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
After a popup stays active, the ion-toggle continues to function normally.
I Just don't know why.
Even the pure backdrop component works normally on locking ion-toggle.
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us, I am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
