### ISSUE TITLE
ionTab throwing: TypeError: 'Cannot read property '$destroy' of undefined' on page navigation

### ISSUE THREAD

**Issue by nkeeslin** [driftyco/ionic#6682]
I am currently using ionTabs on the web inside of an iFrame.  Whenever I navigate to a sibling state of the parent state of my tabs, I get the follow error twice for each tab: TypeError: Cannot read property '$destroy' of undefined.

I tracked down the error in the source code to the destroy function in the ionTab directive. Line 122 of tab.js in the current version of ionic I'm using.

`tabNavElement.isolateScope().$destroy();`

Ionic Version 1.0.0

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Also, could you update to the latest version of ionic 1 please? The latest version is 1.3.1. Thanks for using Ionic!

**Comment by nkeeslin** [comment]
Sorry I meant to close this issue.  it turns out it was an issue with the version of ui-router that I was using.  They have fortunately released a fix for it in their latest version (0.3.1).

**Comment by LeraPodkur** [comment]
I have the same issue.
