### ISSUE TITLE
bug: Creator Output In Index Causes Tabs Under Header

### ISSUE THREAD

**Issue by mtpultz** [driftyco/ionic#6684]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.3</span>

**Platform**: <span ionic-platform>android</span>  <span ionic-webview>browser</span>

<span ionic-description>The body markup output from Creator causes Tabs to be eclipsed by the header - http://codepen.io/mtpultz/pen/BzazLY?editors=1000.  Open this in Chrome and toggle device mode to be android (can't change the label  that says platform iOS, but the tabs have to be at the top to see the bug)  The CodePen has the Creator markup commented out in the <body>.  If you click the link you'll see the proper tabs.  Since it is only using:

```
<ion-nav-view></ion-nav-view>
```

If you uncomment the surrounding markup, which includes the ion-nav-bar and click the link the tabs are become eclipsed by the header:

```
<div>
    <div>
        <ion-nav-bar class="bar-light">
            <ion-nav-back-button class="button-icon icon ion-ios-arrow-back">Back</ion-nav-back-button>
        </ion-nav-bar>
        <ion-nav-view></ion-nav-view>
    </div>
</div>
```

Appears to be due to this set of styles:

```
.nav-bar-tabs-top.hide ~ .view-container .tabs-top .tabs { 
    top: 0; 
}
```

Overriding the top property of this set of styles:

```
.tabs-top > .tabs, .tabs.tabs-top { 
    top: 44px; 
    padding-top: 0; 
    background-position: bottom; 
    border-top-width: 0; 
    border-bottom-width: 1px; 
}
```

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this issue is related to Ionic Creator and not the Ionic framework i will be moving this issue to the appropriate repo for Ionic Creator issues. Feel free to continue the conversation over there, and thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-creator-issues#341
