### ISSUE TITLE
feature: rework ion-refresher

### ISSUE THREAD

**Issue by Lordnoname** [driftyco/ionic#6689]
The current implementation of the ion-refresher don't conform with the material design specs: https://www.google.com/design/spec/patterns/swipe-to-refresh.html

It would be great if the refresher could be reworked to match the material design specs.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We have this planned for a future release as you can see on [this](https://github.com/driftyco/ionic/issues/5557) issue. Thanks for using Ionic!
