### ISSUE TITLE
navbar: scroll off-screen with the content and return when the user reverse scrolls

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#6690]
#### Short description of the problem:

https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-behavior

I think it would awesome to have this feature in ionic 2! it could also be optional for iOS!

**Comment by patrickmcd** [comment]
Second. I think this will be expected mobile UX in a few years.

Hopefully it'll work like [Scroll Sista](https://github.com/djett41/ionic-scroll-sista) ([video that shows it well](https://www.youtube.com/watch?v=x3Htocx4acc)) where you can independently hide headers, sub headers, and tabs (footers would be nice too).

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#39

**Comment by githistory** [comment]
[driftyco/ionic-feature-requests#39](https://github.com/ionic-team/ionic-feature-requests/issues/39) doesn't look good. Any news?

**Comment by Vitor-Lopes** [comment]
Any news?
