### ISSUE TITLE
blank screen after modal pop up shows from side menu on rtl

### ISSUE THREAD

**Issue by sijav** [driftyco/ionic#6694]
#### Short description of the problem:
blank screen after modal pop up shows up (eg. default login pop up from starter sidemenu template)  from side menu (looks like only showing this from side menu have this problem) when rtl (right to left) specification is on html tag.
EDIT: just figured out this is only happening on at least latest google chrome and opera browser, and latest webview on android 5.1 ... other browser seems working though ...

#### What behavior are you expecting?
not showing blank white screen :D

**Steps to reproduce:**
1. start a new app with side menu tab
2. change the index.html file and put dir="rtl" on html tag
3. run for android or google chrome and open login from side menu

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

don't know if I'm saying this right but I believe the problem is because of click-block-hide style regarding -9999px translate, I could resolve this issue by simply put bellow code into my style.css
```
html[dir=rtl] .click-block-hide{
	-webkit-transform: translate3d(9999px, 0, 0);
	transform: translate3d(9999px, 0, 0);
}
```
which is +9999px.

**Which Ionic Version?** 1.x or 2.x
1.3.1 (bower)

#### Plunker that shows an example of your issue

http://plnkr.co/edit/0fpvFKIMYK1Ox9Va9J8h?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.11.1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We are planning on adding full right to left support in Ionic 2 and you can follow the progress on this issue https://github.com/driftyco/ionic/issues/5035 . Would you mind posting about your bug on that issue? Thanks for using Ionic!
