### ISSUE TITLE
Unable to get ion-textarea value v2

### ISSUE THREAD

**Issue by kingleroyg** [driftyco/ionic#6699]
#### Short description of the problem:
When I use 

`<ion-searchbar [(ngModel)]="searchQuery" (input)="getItems($event)"></ion-searchbar>`
I can get the search bar value :
```
 getItems(searchbar) {
 console.log( searchbar.value);
}
```

Which works perfect. But when I try it with a textarea I get `undefined` 

`<ion-textarea [(ngModel)]="composeText" (input)="getItems($event)" placeholder="compose: "></ion-textarea>`
#### What behavior are you expecting?
I'm getting `undefined` 
 
**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.25

#### Plunker that shows an example of your issue

http://embed.plnkr.co/sz2BR5tBh9yG5DtxIuYx/

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.4

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! [Here](http://plnkr.co/edit/eGdJKWKHmI8t1bbGLw7v?p=preview) is a plunker that demonstrates the correct way to do this. With my understanding (and i could be and probably am wrong) the `textarea` element does not seem to work with `ngModel `. This may be an issue with Angular 2 and is something i will have to investigate more. Thanks for using Ionic! I am going to close this issue for now as the plunker i linked to should help you, but if your still having issues then i will happily reopen. Thanks!
