### ISSUE TITLE
Google places auto compelete doesn't work with ion-input

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#6700]
#### Short description of the problem:
I was trying to create a ion-input with google places auto complete but it seems that google doesnt like ion-input :).
Using it causes `InvalidValueError: not an instance of HTMLInputElement`
Not sure if we can call it a bug, but it would be great it would work with ion-input (I like its styles)

#### What behavior are you expecting?
To google places api to work with ion-input

**Steps to reproduce:**
1. create a page with ion-input
2. at the page constructor or Init
```js
      let places = new google.maps.places.Autocomplete(document.getElementById("inputId", {
        types: ['(cities)'],
        componentRestrictions: { country: 'fr' }
      });
```
3. error

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/yfzaRKhZdkMZj5GOVYS1?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.9.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to use the google maps api with ionic 2 i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by nishantpant** [comment]
**<ion-input>** adds a wrapper on **<input>** element. The trick (although not that clean) is to simply grab the hidden input element. 

eg. **HTML**
        <ion-item>
          <ion-label floating>Home Address</ion-label>
          <ion-input id="txtHome" type="text"></ion-input>
        </ion-item>

**Javascript/Typescript:**
      var nativeHomeInputBox = document.getElementById('txtHome').getElementsByTagName('input')[0];
      let autocomplete1 = new google.maps.places.Autocomplete(nativeHomeInputBox, searchOptions);

**Comment by IdoZilberberg** [comment]
To add on top of @nishantpant's answer - the snippet below is a bit more Angular 2+ although still not perfect - I would rather do away with **getNativeElement().getElementsByTagName('input').**

    <ion-input #search ... </ion-input>
    ...
    @ViewChild("search") searchElementRef: ElementRef;
    ...
    const inputElement = 
    this.searchElementRef.getNativeElement().getElementsByTagName('input')[0];
    autocomplete = new google.maps.places.Autocomplete(inputElement, options);

**Comment by richie50** [comment]
I wasn't getting a proper reference to the wrapper input element so i add an ionic lifecycle hook ViewDidLoad which sets the element after the DOM is done loading. @nishantpant . Thanks though
