### ISSUE TITLE
Remove latency from Modal.onDismiss

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6702]
#### Short description of the problem:
I have a modal to input data which is then added to a list after the modal closes, but the new element only appears **after** the Modal animation end. I measured about 675 ms of latency in my project and 330 ms in Plunkr (less dependencies).

#### What behavior are you expecting?
300-675 ms of latency

**Steps to reproduce:**
1. Create a modal and a root page
2. Launch the modal and return data from it
3. Use console.time (before viewCtrl.dismiss and in Modal.onDismiss) to measure how long it took to return data.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

[http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview)

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201605271904
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
We understand your use case, I am going to evaluate adding a new callback that it's executed just after the modal is closed (without delay). Probably something like `onWillDismiss`, not sure yet.

**Comment by iignatov** [comment]
@Bouzmine As a workaround you could speed-up the closing of the modal by passing [`NavOptions`](http://ionicframework.com/docs/v2/api/components/nav/NavController/#navoptions) to the [`ViewController.dismiss()`](http://ionicframework.com/docs/v2/api/components/nav/ViewController/#dismiss) method and specifying the duration _(or disable the animation altogether)_.

**Comment by Bouzmine** [comment]
I do think it's a great workaround but it's by no mean a replacement for a proper `onWillDismiss` method.

**Comment by iignatov** [comment]
> it's a great workaround but it's by no mean a replacement for a proper `onWillDismiss` method.

I agree, I mentioned the workaround in case that you want to solve your problem until it's implemented.

**Comment by manucorporat** [comment]
@Bouzmine @iignatov https://github.com/driftyco/ionic/pull/7060
