### ISSUE TITLE
Android app freezes after launch...

### ISSUE THREAD

**Issue by piyushmanurkar** [driftyco/ionic#6705]
#### Short description of the problem:
Launch app first time, its run perfect... but when close android app using
**ionic.Platform.exitApp();**
and relaunch app by tapping on app icon...
After splash screen hide, app freezes/stuck...

But when kill app from task manager, and launch it runs perfect...

#### What behavior are you expecting?
App run as run on first time...

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you run `ionic info` inside your app repo and post the output here please?

**Comment by piyushmanurkar** [comment]
Thank you for reply... @jgw96 
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v0.12.11

**Comment by jgw96** [comment]
@piyushmanurkar So after some research we have decided that we cannot recommend that you use this method and have decided to remove it. It will still work, but we cannot support it at this time. There are operating system restrictions that cause issues with this method on ios, and Android does not seem to like it either. Also, as a UX consideration (although i am not a user experience expert at all (: ) it is probably best to not have a close app button in your app as the operating system is supposed to handle app lifecycles. Thanks for using Ionic, i hope i explained everything clearly!

**Comment by manucorporat** [comment]
@piyushmanurkar in addition, Apple could reject your app, if they notice that you deliberately try to exit your app programatically.

**Comment by piyushmanurkar** [comment]
@jgw96 & @manucorporat Thank you both for this valuable information...
