### ISSUE TITLE
Unknown CSS transition delay 

### ISSUE THREAD

**Issue by jgog** [driftyco/ionic#6707]
#### Short description of the problem:
I am trying to animate the max-height of the ion-card on click, the card opens properly according to the transition properties set in the CSS, but while closing the card, there is unknown delay of about ~500ms.

#### What behavior are you expecting?
There should be no delay unless specified in the CSS transition.

**Steps to reproduce:**
1. See the plunker http://plnkr.co/edit/1a7912HanqSrHfpX98IG?p=preview
2. Click on the "Click me" in the card header to see the hidden content
3. Click it again to close the hidden content and you will see the delay

**Which Ionic Version?** 2.x

Ionic info:
```
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201605271904
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question about some custom functionality that you are working on i will urge that you ask this question on our forum (forum.ionicframework.com). There are alot of awesome devs on there that should be able to help you. Thanks for using Ionic!
