### ISSUE TITLE
Feature Request: Add Toast click handler

### ISSUE THREAD

**Issue by bdoner** [driftyco/ionic#6709]
#### [Feature request] Add click handler to Toast

It would be a nice feature with a click event on the Toast (backdrop). 

The toast is a short message that's used to tell the user something has happened but interaction is not strictly required. 
Being able to click the Toast as a way to interact with the newly obtained information if desired would make sense.

Clicking the toast would also close it.
The handler does not take any parameters.

Example:

```
Toast.create({
    message: `You have a new message!`,
    duration: 2000,
    click: () => {
        this.nav.push(ReadMessagePage);
    }
});
```

**Comment by jgw96** [comment]
Hello! So this functionality already exists actually! You can set the toast to close when it is clicked (and display a button) using the `showCloseButton` option, change that button text using the `closeButtonText` property and do an action when it is dismissed using `toast.onDismiss()`. Here is an example of all that put together

```
let toast = Toast.create({
    message: 'User was added successfully',
    showCloseButton: true,
    closeButtonText: WhateverIWantMyButtonToSay
  });

  toast.onDismiss(() => {
     //do action
    console.log('Dismissed toast');
  });

  this.nav.present(toast);
```
Is this the functionality you are looking for?

**Comment by bdoner** [comment]
The functionality you refer to is getting called when the toast is dismissed -  no matter how it happens. 
What I'm suggesting is a function that's only called when a user interact with the Toast.

**Comment by jgw96** [comment]
@bdoner Ahh ok, thanks for clearing that up and sorry i didn't understand fully at first!

**Comment by bdoner** [comment]
No problem :) 

Will this issue be updated when you have considered it in the team?

**Comment by jgw96** [comment]
@bdoner Yep, i will update this issue as soon as i present it to my teammates (:

**Comment by jgw96** [comment]
We are still considering this, but i will update when we come to a decision (:

**Comment by andrefedalto** [comment]
This would allow a behaviour like google now cards have. When you swipe a card to dismiss it there is a toast where you can undo your action. With the current way the toast is implemented I don't have a way to replicate this behaviour, so +1 for actions inside the toast :)

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by yannbf** [comment]
I too am feeling the need o having this behavior, exactly for an "undo" callback. Any news on its progress?

**Comment by lincolnthree** [comment]
Hey Folks,

This is *somewhat* achievable using the existing toast API, though there are issues:

- Device timing can cause erroneous invocations.
- You can't have more than one action or button in the Toast (like "Dismiss" and "Undo")

`import { Injectable } from '@angular/core';
import { ToastController } from 'ionic-angular';

@Injectable()
export class UndoController {

	constructor(private toastCtrl: ToastController) {
	}

	displayUndo(message: string, callback: any) {

		var displayedTime = new Date().getTime();
		let duration: number = 3500;
		let toast = this.toastCtrl.create({
			message: message,
			duration: duration,
			showCloseButton: true,
			closeButtonText: "Undo",
			dismissOnPageChange: false,
			position: "top"
		});

		toast.onDidDismiss(() => {
			let dismissedTime = new Date().getTime();
			if ((displayedTime + duration) > dismissedTime) {
				callback()
			};
		});

		toast.present();
	}
}
`

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#40

**Comment by stalniy** [comment]
@jgw96 the link is broken

**Comment by imanube** [comment]
There are some workaround solutions here.  I use the solution in post 9 
https://forum.ionicframework.com/t/how-to-add-toast-action-button/61377/9

**Comment by rodriggochaves** [comment]
There is any update in this feature?
