### ISSUE TITLE
Ionic 2 Docs page bug...

### ISSUE THREAD

**Issue by mamarilmanson** [driftyco/ionic#6710]
I went to the Ionic2 components doc... but the current section I am at doesn't match the display on the "phone" example... it would get stuck and skip section as I scroll... 

I tried it on firefox and on blish with the same result...

**Comment by brandyscarney** [comment]
Thanks for the issue! I am going to move this to the `ionic-site` repo since it is more of a site issue. :smile:

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#631

**Comment by mamarilmanson** [comment]
I don't know why but until the very bottom of the page it only appears Action Sheets on the phone...
