### ISSUE TITLE
The selected event on the select option doesn't emit

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#6711]
The `ionSelect` (called `select` prior to #6568) is never emitted on the option for the select component.

**Comment by ryandegruyter** [comment]
I can help out, may I assign myself to this?

**Comment by brandyscarney** [comment]
@ryandegruyter I don't think issues can be assigned outside of our team, but if you'd like to work on it and submit a PR it's all yours! The difficulty with this issue is the Select uses the Alert & ActionSheet API underneath so it will need to emit the event in each back to the Select.

**Comment by ryandegruyter** [comment]
Ok  thank you, I underestimated and misunderstood this issue. But I can still give it a shot, when exactly should the ionSelect output emit? When the option is selected/clicked but not when the OK button is clicked?

**Comment by brandyscarney** [comment]
Yeah it should emit when the option is clicked, prior to pressing the OK button, since once you press the OK button it triggers the `ionChange` event on the select. :smile:
