### ISSUE TITLE
ion-slides runCallbacksOnInit issue with version 1.3.1

### ISSUE THREAD

**Issue by rjgpereira** [driftyco/ionic#6712]
I have a slider with two possible modes, which the user can toggle. These two modes have different number of slides. When i switch views I need to init() the slider and i can't have the callbacks running when this happens, and for that i set the "runCallbacksOnInit" to false. Everything worked nice in version 1.2.4 but now, after updating to 1.3.1, the "onSlidePrevStart" is called, which didn't happen before. Is this a bug? No callback should be called if "runCallbacksOnInit" is set to false, right?

Ionic version: 1.3.1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind creating a codepen that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#125
