### ISSUE TITLE
bug: Ion-Toggle still works with PopUp on Screen

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic#6716]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After a popup stays active, the ion-toggle continues to function normally.
I Just don't know why.
Even the pure backdrop component works normally on locking ion-toggle.

Here's an template:
http://codepen.io/daniloscouto/pen/ezmmQv</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#123
