### ISSUE TITLE
docs: I found a typo in the HTML input types page

### ISSUE THREAD

**Issue by tylervz** [driftyco/ionic#6718]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Under the Password section, the second paragraph begins "Also note that it's being to be common practice to give users...".

It should be changed to "Also note that it's starting to be common practice to give users..." or "Also note that it's becoming common practice to give users...".</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#633
