### ISSUE TITLE
Black line in above or below toolbar

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6719]
#### Short description of the problem:
A short black line appears on top of a toolbar in iOS/OS X Safari (haven't been able to reproduce this bug in other browsers). I am unable to reproduce this issue in Plnkr. Here's a screenshot : 
![capture d ecran 2016-05-31 a 17 39 48](https://cloud.githubusercontent.com/assets/15067923/15691952/b08fe3dc-2759-11e6-993d-10f002ba1727.png)

If I remove `toolbar-background` element, it shows the black spot under it : 
![capture d ecran 2016-05-31 a 18 02 16](https://cloud.githubusercontent.com/assets/15067923/15691998/e82d5216-2759-11e6-84ff-bc450d2070b3.png)

**Steps to reproduce:**
1. Have a toolbar (bottom) above a tab bar

**Which Ionic Version?** 2.x (nightly-201605271904)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201605271904
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment]
What does your markup look like? I'm able to see some black lines above the tabbar but not above the toolbar, and only from a retina screen. Here's what I'm seeing:

Click on a tab that has a toolbar after the `ion-content` on the root page:

<img width="502" alt="screen shot 2016-06-03 at 2 54 28 pm" src="https://cloud.githubusercontent.com/assets/6577830/15789861/5d37e4d8-299c-11e6-8516-eab9aad383b3.png">

Click on a tab with no toolbar at the root page, then navigate to a child page with the toolbar:

<img width="500" alt="screen shot 2016-06-03 at 2 57 03 pm" src="https://cloud.githubusercontent.com/assets/6577830/15789866/614eb268-299c-11e6-8f4f-c2e5a9e1d786.png">

Switch between these two tabs:

<img width="499" alt="screen shot 2016-06-03 at 2 57 41 pm" src="https://cloud.githubusercontent.com/assets/6577830/15789872/66b64ebe-299c-11e6-9b77-26f624b045c8.png">

I believe you that the issue exists, I just want to make sure I can find every case. :smile:

**Comment by Bouzmine** [comment]
The one I'm seeing is the last (switching between the two tabs)

**Comment by Bouzmine** [comment]
After a bit of research, I came to the conclusion this is related to `ion-nav.has-views` style. If I disable it, the bug goes away.

**Comment by brandyscarney** [comment]
This will be fixed in the `beta 10` release. Thanks for the issue!
