### ISSUE TITLE
Iframe not working Production IOS

### ISSUE THREAD

**Issue by calevano** [driftyco/ionic#6720]
**People** not to you has happened or is happening to them but ... 
I have a app to launch in IOS, but I'm testing in a view loading an iframe a route with https : // Developing it me works really well , my iframe appears with the view of the route ... 
When I give product-> file and exported in Ad- hoc to try before uploading the Appstore ... I do not see the iframe the issue of whitelist is fine, because in any case not to open my eyes containing the iframe in development mode.

With the developer profile if you open the iframe , but with the profile of production , does not open

sorry for my English

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a question about how to use the framework it would be better answered by asking it on our forum. [Here](
https://forum.ionicframework.com/search?q=iframe) is a link to all the iframe related posts on our forum. Thanks for using Ionic!
