### ISSUE TITLE
Scrollbar not visible on Android

### ISSUE THREAD

**Issue by rberthome** [driftyco/ionic#6721]
Hello, 

I'm having some trouble to show the scrollbar in Android devices, it's working in all the others platforms (iOS and Windows)

To be more precise, the scroll is available. I can go down and up but I cannot see the scrollbar and only on an android device. I tried on a 4.4.4 and a 6.0.1 OS version. 

I made an example : http://codepen.io/rberthome/pen/mEyMov

This will work on your desktop browser and even in your smartphone through your browser. 

To reproduce the issue you have to put the code in a ionic project. Follow these steps : 
> - Create a blank project => ionic start NoScrollBarAndroid blank 
> - Add android platform => ionic platform add android
> - Replace the body of your index.html file with the codeopen one
> - Add the controller from the codeopen project to the app.js
> - Copy the content of the CSS part to the style.css
> - just run the application on your android (phone or simulator) => ionic run android

Do you have any workaround to correct this ? 

Thanks.

**Comment by rberthome** [comment]
I opened a topic in the forum : https://forum.ionicframework.com/t/scrollbar-not-visible-on-android/53616

Does anyone have a workaround or a solution ?

**Comment by jgw96** [comment]
Hello as it looks like this issue was solved in the forums i will be closing this issue for now. Thanks for using Ionic!
