### ISSUE TITLE
Centralized Gesture Controller

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic#6726]
Right now each component that have gestures can work stand-alone, which is fine. However, sometimes multiple components with gestures are all valid to work, but all act at the same time. For example, imagine a range inside of a sliding item inside of slides on a swipe to go back page that can scroll and has a left menu. Who should work when you swipe left?? The goal is to not reimplement Hammer gestures, but rather centralize which "one" gesture component should be listening on the move events. 

Create a `GestureController` class and add it to our providers in `ionicBootstrap`. Then each component that has gestures, like range/menu/itemSliding/slides/etc, all would inject the GestureController instance. For each individual component, they would first ask the GestureController if it's ok if their gestures should work or not, and also have the ability to cancel all other already active gestures.

**Comment by jgw96** [comment]
Im pretty sure this is related: https://github.com/driftyco/ionic/issues/6897. If we could configure the hammer events to work vertically too like @danbucholtz mentioned this morning it should fix this issue.
