### ISSUE TITLE
// @import "components/scroll/pull-to-refresh"; do not works in ionic2 beta7

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#6729]
**The following code would cause scss compiles failed in ionic2 beta7, but works in ionic2 beta1:**

```
// Needed in Alpha-52 because missing
@import "components/scroll/pull-to-refresh";

.search {
  .item {
    color: #8AA64E;
  }
}

```

**Comment by brandyscarney** [comment]
The component was moved and renamed to `refresher`, it is now located at:

```
components/refresher/refresher
```

The API docs for refresher can be found here: http://ionicframework.com/docs/v2/api/components/refresher/Refresher/

You shouldn't need to import it though since we include it in our core components sass file.
