### ISSUE TITLE
angular-ui/bootstrap ratting issue on collection-repeat ionic

### ISSUE THREAD

**Issue by vitaly87** [driftyco/ionic#6732]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://github.com/angular-ui/bootstrap

#### Short description of the problem:
when trying to use  collection-repeat with Rating (ui.bootstrap.rating) then getting strange results when valye more that 2.

#### What behavior are you expecting?

**Steps to reproduce:**
1. create array of contacts
2. do loop with  collection-repeat=" contact in contacts
3.      <uib-rating ng-model="contact.active" max={{contact.total}} state-on="'ion-person-stalker positive '"
                        state-off="'ion-person-stalker'"
                        ng-click="changeActive(contact);data.searchText =''"></uib-rating>

not updating correct icons of it...

**Which Ionic Version?** 1.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately we do not support using Angular-ui components in Ionic apps. Although most of them will most likely work, we cannot guarantee that they all will. I would suggest asking around on our forums (forum.ionicframework.com) as there are alot of awesome dev's on there that may be able to help you. Thanks for using Ionic!
