### ISSUE TITLE
All Modal backdrop click to close

### ISSUE THREAD

**Issue by zywh** [driftyco/ionic#6734]
Since Modal is inset, can backdrop be clickable to close?

Similar to Alert window

<div (click)="bdClick()" tappable disable-activated class="backdrop" role="presentation"></div>'

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are currently working on this and you can follow the progress on this issue https://github.com/driftyco/ionic/issues/6738. Thanks for using Ionic!
