### ISSUE TITLE
Toast is not automatically dismissed if another toast is present. 

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#6739]
#### Short description of the problem:

I found an issue with the Toast's demo (http://ionicframework.com/docs/v2/api/components/toast/Toast/). When I click on 'Show custom duration toast' , the toast is not automatically dismissed if there is another toast displayed.  

**Steps to reproduce:**
1. Go to http://ionicframework.com/docs/v2/api/components/toast/Toast/
2. Click on 'Show Toast'
3. Click on 'Show Custom Duration Toast'
4. The toast is never dismissed

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue
http://ionicframework.com/docs/v2/api/components/toast/Toast/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is a known issue and is slated to be fixed soon. You can follow the progress on this issue: https://github.com/driftyco/ionic/issues/6657. Thanks for using Ionic!
