### ISSUE TITLE
bug: Crashing at startup with Native Google Maps Plugin

### ISSUE THREAD

**Issue by frankthelen** [driftyco/ionic#6743]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I am using Ionic 2.0.0-beta.25.
Testing in Genymotion as well as on a Nexus 5X.

The app crashes at startup.
Unfortunately, Chrome device debugging doesn't give me an error message when the process dies immediately.

I am not even using the plugin, just added it to the project, and the app crashes.

This is how to reproduce (trying to narrow it down):

$ ionic start cutePuppyPics --v2
$ cd cutePuppyPics
$ ionic serve // running OK in Browser
$ ionic platform add android
$ ionic run android // running OK in Genymotion and real device

Now adding the plugin...

$ ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID=<key>
$ ionic run android // app crashes at startup

Thanks.</span>

<span is-issue-template></span>

**Comment by ZiFFeL1992** [comment]
You need to provide more info...

Did you setup you api keys on Google Console Developer?
Do you get a blank screen?
Can you see google's logo at the bottom of the screen?

**Comment by frankthelen** [comment]
Yes, I did setup an Android API key.
Genymotion pops up a box "Unfortunately, cutePuppyPics has stopped", nothing else.

I pulled LogCat from Genymotion...

06-03 10:01:11.293  2879  2879 E AndroidRuntime: FATAL EXCEPTION: main

06-03 10:01:11.293  2879  2879 E AndroidRuntime: Process: com.ionicframework.cutepuppypics257409, PID: 2879

06-03 10:01:11.293  2879  2879 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5156)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)

06-03 10:01:11.293  2879  2879 E AndroidRuntime: 	... 10 more

**Comment by jgw96** [comment]
@frankthelen Hello, thanks for opening an issue with us! From looking at the logs you posted above, it looks as if you have not set up your app correctly to use the google maps plugin. I would recommend opening an issue on that plugin's repo as this does not look like it is an issue with Ionic, and they should be able to help you better than we can. Thanks for using Ionic!
