### ISSUE TITLE
Ionic 2 update Refresher component documentation: change event name ionRefresh to refresh

### ISSUE THREAD

**Issue by WHarris22** [driftyco/ionic#6744]
The [Ionic 2 documentation](http://ionicframework.com/docs/v2/api/components/refresher/Refresher/) for the Refresher component has an example that uses `(ionRefresh)="doRefresh($event)"` which doesn't work in beta 7, instead the event name to use is `(refresh)="doRefresh($event)"`.

Everywhere in the documentation that references `ionRefresh` should be replaced with `refresh`.

**Comment by ZiFFeL1992** [comment]
Update to latest nightly and you'll be able to use ionRefresh, the docs are ready for beta.8 already.

**Comment by WHarris22** [comment]
@ZiFFeL1992 thanks for pointing this out to me :+1: i'll close the issue

**Comment by srishiva89** [comment]
(ionRefresh)="doRefresh($event)" which doesn't work in beta 11. When I use this line i'm getting below error
![image](https://cloud.githubusercontent.com/assets/19839068/17682922/895e6b3e-6314-11e6-98e5-a800d280dd4f.png)
