### ISSUE TITLE
Upgrade to Nightly build 2.0.0-beta.7-201606021731-  app.ts @App not callable

### ISSUE THREAD

**Issue by zywh** [driftyco/ionic#6747]
Typescript error

[ts] Value of type 'typeof App' is not callable. Did you mean to include 'new'?
import App

The template is from conference app

**Comment by jgw96** [comment]
Hello @zywh ! We have removed @App in favor of using @Component now. Here are a list of instructions for how to update right now, once beta.8 is released (which should be very soon) these will be posted with the changelog (: 

Replace all instances of `@Page` with `@Component`:

```
import {Page} from 'ionic-angular';

@Page({

})
```

becomes

```
import {Component} from '@angular/core';

@Component({

})
```

Replace `@App` with `@Component` and then bootstrap it. Move any `config` properties into the bootstrap:

```
import {App, Platform} from 'ionic-angular';

@App({
  templateUrl: 'build/app.html',
  providers: [ConferenceData, UserData],
  config: {
    tabbarPlacement: 'bottom'
}
export class MyApp {

}
```

becomes

```
import {Component} from '@angular/core';
import {ionicBootstrap, Platform} from 'ionic-angular';

@Component({
  templateUrl: 'build/app.html',
})
export class MyApp {

}

ionicBootstrap(ConferenceApp, [ConferenceData, UserData], {
  tabbarPlacement: 'bottom'
});
```

Rename any uses of `IonicApp` to `App`:

```
import {IonicApp} from 'ionic-angular';

constructor(
  private app: IonicApp
) {
```

becomes

```
import {App} from 'ionic-angular';

constructor(
  private app: App
) {

**Comment by tamerbak** [comment]
@zywh how can I install latest nightly version ?

**Comment by manucorporat** [comment]
@tamerbak 
```
npm install ionic-angular@nightly`
```

**Comment by tamerbak** [comment]
@manucorporat Thanks!

**Comment by rafbgarcia** [comment]
Hello :) Is there a way to check what's in the nightly build?

I tried to compare the generated version to the commits' dates, but I don't think that's very accurate...

```
3.6.1-201709131804
```
