### ISSUE TITLE
Ghost click on iOS 9.3.1

### ISSUE THREAD

**Issue by rjgpereira** [driftyco/ionic#6750]
I have a div with a bunch of buttons inside. Below i have another button which expands the div above. When i click the expand button the buttons of the expanded div are clicked accordingly to the touch coordinate.
This doesn't happen always but it's very frequent.

Ionic version: 1.3.1

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
