### ISSUE TITLE
App assets in Ionic

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6757]
Currently in Ionic 2 we build the app to the `www/build/` directory. Inside the `www/build/` directory there is a fonts directory. To our users this looks like the place to put your custom fonts or other assets, because this is where ionic is building its assets too, but if you do that then your files and/or folders will get deleted by the build process as the `www/build` directory gets overwritten each time the build process runs. The correct way up until now to add custom assets to an app was to place the assets in the `www/` directory, but this can be confusing because, for example, you end up having fonts in the `www/build/` folder and then your custom fonts in the `www/` directory.

**Comment by danbucholtz** [comment]
@jgw96, how do you build electron apps?  We should give some thought to the directory structure such that we can easily output a cordova, electron, and typical web app from the src code in the `app` directory.  May be a good idea to manage images in one place, and then copy them to the output for cordova and electron.

Thanks,
Dan

**Comment by alexbainbridge** [comment]
Dan - if you are thinking about directory structures, would be great to get PhoneGap Build back easy to use

Instructions for moving files around within directories.... 
https://forum.ionicframework.com/t/building-ionic-2-beta-7-apps-with-phonegap-build/53253  

V1 apps worked with PhonegapBuild with no moving around of files.

Thanks!

**Comment by jgw96** [comment]
@danbucholtz For electron apps i usually put the javascript file that has all the electron stuff in the www folder. You do not have to do it that way (as long as you write your paths right) but thats just the most convenient place to put it that i have found.

**Comment by jgw96** [comment]
Since this is solved with
