### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by mamarilmanson** [driftyco/ionic#6759]
I've been searching for a while for tutorials about how to import [this ](https://www.npmjs.com/package/google-spreadsheet)module to angular2 - Ionic2 to be specific - but without luck.

Is there any tutorial on how to implement this module to ionic 2?

I tried this but with no success:

`import * as googlespreadsheet from 'google-spreadsheet';`

which produced the error:

`error: Cannot find module 'google-spreadsheet'.`

also tried: 

`let googlespreadsheet = require("google-spreadsheet");`

which gave:

`Cannot find name 'require'.`

The Part of the code is here: http://plnkr.co/edit/veskMkWntoPx24w4r8uE

**Comment by danbucholtz** [comment]
Hi @mamarilmanson 😄 ,

Thanks for the issue.  More than likely this has something to do with the `type definitions` for that module.  

Check out this link to learn how to manage type definitions with a tool called `typings`.

https://github.com/typings/typings

Please let me know if there is an issue with the Ionic framework and I'll re-open the issue.

Thanks,
Dan
