### ISSUE TITLE
bug: Presented with Access Denied

### ISSUE THREAD

**Issue by unipheas** [driftyco/ionic#6760]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm in China. I have to use a VPN for most of the time. After a fresh install of Ionic Labs I find that at a random time I'll be presented with access denied. I'll have to restart my macbook air to get it to show my content again. I recently found that once I turned off the vpn it started working again but I haven't figured out why. I've checked file permissions and it seems to be all fine.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! As this is an issue with the ionic-cli and not the ionic framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1046
