### ISSUE TITLE
ionDidChange event not working for slides?

### ISSUE THREAD

**Issue by cjosh** [driftyco/ionic#6762]
I was looking at the [documentation](http://ionicframework.com/docs/v2/api/components/slides/Slides/) for the slides component, and it mentions 

<pre><code>&lt;ion-slides #mySlider (ionDidChange)="onSlideChanged()" [options]="mySlideOptions"&gt;</code></pre>

The ionDidChange implementation did not work, but it did work using (slideChangeStart) which I found in the ionic-conference-app, and is also listed in the Swiper API.

It could be that I messed it up, but slideChangeStart (as well as the rest of the example in the doc) worked and ionDidChange doesn't seem to appear anywhere else after searching the docs. Is this event still in use? If so, where would I find a table of these events because it is not obviously available.

I'm running ionic-native 1.2.4.

**Comment by manucorporat** [comment]
@cjosh hi, could you run `ionic info` and post the results here?

**Comment by brandyscarney** [comment]
The documentation defaults to the nightly version of the API, if you click the drop down in the top left you can see the docs by version. We recently changed the name of all of the events and that will be in the beta 8 release. We'll have all of the new event names listed in the changelog once we release. 

Also, ionic-native is the wrapper for Cordova plugins. The ionic-angular package is the framework itself, and the latest is beta 7. :smile:
