### ISSUE TITLE
Cannot create a custom input component using ion-input

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#6763]
#### Short description of the problem:

Creating a custom component with `ion-input` inside causes the input to no be clickable
#### What behavior are you expecting?

Expecting the same behavior as the normal `ion-input`

**Steps to reproduce:**
1. create a component with `ion-input` as a template
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/JSjRCppvcUBYPO7AOHJy?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID: Ubuntu Description: Ubuntu 14.04.4 LTS 
Node Version: v5.9.0

**Comment by royipressburger** [comment]
Status?

**Comment by brandyscarney** [comment]
This is essentially the same issue as https://github.com/driftyco/ionic/issues/7252. Please see my comment there: https://github.com/driftyco/ionic/issues/7252#issuecomment-231832386

**Comment by royipressburger** [comment]
@brandyscarney Hi and thanks for the answer.. Unfortunately I didn't really understand what you were saying there. (Is there a place to read more about what you said?)

In any case.. It looks that If I use the `ion-item` tag inside the custom component and not from outside it works. But this means that if I want custom input component it must be wrapped with `ion-item` Not sure if this is expected behavior

**Comment by brandyscarney** [comment]
The solution here is to use the `item-content` attribute here:

```
<ion-item>
  <my-input item-content placeholder="dadada"></my-input>
</ion-item>
```

See the documentation for more information: http://ionicframework.com/docs/v2/api/components/item/Item/#item-placement
