### ISSUE TITLE
Integrating Kontakt.io SDK in ionic Framework

### ISSUE THREAD

**Issue by bshikhar13** [driftyco/ionic#6767]
How can the kontakt.io sdk (for Beacons) be integrated in ionic. SDK link : [http://developer.kontakt.io/android-sdk/3.0.0/quickstart/](url)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
