### ISSUE TITLE
ionic2 with build command error

### ISSUE THREAD

**Issue by dragonahao** [driftyco/ionic#6770]
Running 'build:before' gulp task before build
[23:14:26] Starting 'clean'...
[23:14:26] Finished 'clean' after 76 ms
[23:14:26] Starting 'build'...
[23:14:26] Starting 'sass'...
[23:14:26] Starting 'html'...
[23:14:26] Starting 'fonts'...
[23:14:26] Starting 'scripts'...
[23:14:26] Finished 'scripts' after 104 ms
[23:14:26] Finished 'fonts' after 143 ms
[23:14:26] Finished 'html' after 206 ms
[23:14:27] Finished 'sass' after 1.33 s
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/directives/helpers.ts(45,23): Error TS2339: Property 'currentStyle'
does not exist on type 'HTMLElement'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/directives/helpers.ts(46,30): Error TS2339: Property 'currentStyle'
does not exist on type 'HTMLElement'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/directives/helpers.ts(55,23): Error TS2339: Property 'currentStyle'
does not exist on type 'HTMLElement'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/directives/helpers.ts(56,31): Error TS2339: Property 'currentStyle'
does not exist on type 'HTMLElement'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/pages/menus/basic/pages.ts(1,9): Error TS2305: Module '"F:/worktemp/
cordova-temp/ionic-v2-temp/demo1/ionic-preview-app-master/node_modules/ionic-ang
ular/index"' has no exported member 'IonicApp'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/pages/modals/basic/pages.ts(1,9): Error TS2305: Module '"F:/worktemp
/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app-master/node_modules/ionic-an
gular/index"' has no exported member 'IonicApp'.
TypeScript error: F:/worktemp/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app
-master/app/pages/radios/basic/pages.ts(1,14): Error TS2305: Module '"F:/worktem
p/cordova-temp/ionic-v2-temp/demo1/ionic-preview-app-master/node_modules/ionic-a
ngular/index"' has no exported member 'IonicApp'.
TypeScript error: app/app.ts(13,2): Error TS2348: Value of type 'typeof App' is
not callable. Did you mean to include 'new'?
[23:14:35] Finished 'build' after 9.31 s
[23:14:35] Starting 'build:before'...
[23:14:35] Finished 'build:before' after 6.53 μs

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the ionic-cli and not the ionic framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1040
