### ISSUE TITLE
Feature Request: Parallax support in ion-slides

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6771]
#### Short description of the problem:

Swiper (the underlaying widget of `ion-slides`) supports parallax transitions. I'd like to use those in my Ionic app, so I activated them, but something in ion-slides' custom structure makes it impossible to use that feature (my bet is `.slide-zoom`).

**Other information:**
 There could be a new element like `ion-parallax` with properties like offset and transition duration.

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by darshantejani007** [comment]
Has Ionic team started working on this feature? which is, do I expect this feature in a near future ionic version?

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#41

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!
