### ISSUE TITLE
Feature Request: List remove animation

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6772]
#### Short description of the problem:

There are no remove animation for lists like in Ionic 1 (`item-remove-animate`).

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7-201606012128
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by WHarris22** [comment]
[FYI](https://forum.ionicframework.com/t/list-item-remove-animation/51857)

**Comment by manucorporat** [comment]
@WHarris22 @Bouzmine I am working on this!

**Comment by WHarris22** [comment]
@manucorporat thanks :) I look forward to trying them out :dancer:

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#42
