### ISSUE TITLE
Ionic2 <ion-select> <ion-tab> <ion-toggle> events have bad documentation.

### ISSUE THREAD

**Issue by AjkP** [driftyco/ionic#6773]
All documentation seems to have wrong output events (usually an extra `ion` in front of the event name). I'll do a PR and fix them if this gets confirmed as a doc bug.

Tabs Examples:
Tabs: http://ionicframework.com/docs/v2/api/components/tabs/Tab/

> Sometimes you may want to call a method instead of navigating to a new page. You can use the (ionSelect) event to call a method on your class when the tab is selected. Below is an example of presenting a modal from one of the tabs.

```
<ion-tabs preloadTabs="false">
  <ion-tab (ionSelect)="chat()"></ion-tab>
</ion-tabs>
```
Output Events
`ionSelect	 Method to call when the current tab is selected`

Actually the working event is (select).

Similarly ion-toggle and ion-select have mis-documented events.

**Comment by iignatov** [comment]
Good catch, but this should be due to an upcoming change for `beta.8`. See #6568 for additional details.
I guess that this is because the documentation is generated from the inline comments in the source code.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! This was actually changed on purpose and as @iignatov is a change that is coming in beta.8. We are prepending every event with ion to prevent issues with events firing multiple times. We have had some unexpected delays with beta.8 but you can expect it out very soon (: Thanks for using Ionic!
