### ISSUE TITLE
DateTime not changing

### ISSUE THREAD

**Issue by AluminiumTech** [driftyco/ionic#6775]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
DateTime is not updating once it is chosen.

#### What behavior are you expecting?
It to submit a console log saying "test"

**Steps to reproduce:**
1. Setup a datetime selection element in a html page
2. Choose a date in browser on the page
3. And try to change it 

```
insert any relevant code between the above and below backticks
```
(In page1.js)

submit() {
 console.log("TEST");
}

(in page1.html)

    <ion-item>
        <ion-label>Date</ion-label>
        <ion-datetime displayFormat="DD/MM/YYYY" pickerFormat="DDDD MMMM YYYY" [(ngModel)]="myDate"></ion-datetime>
    </ion-item>
    <button round block (click)="submit()">Submit to server</button>

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by mkamayd** [comment]
I am still having the issue.
Please see here http://plnkr.co/edit/POU6BoTDmWPSTMostfXO?p=preview

**Comment by superjamesmccafferty** [comment]
I'm also having a similar issue. If I change the value in the view then everything works fine. But if I change the value in the model, the view does not change until I click the ion-datetime, or some similar UI event occurs. 

I know this sounds like a changeRef.detectChanges() issue, but that's not working. I can't find a programmatic way to get ion-datetime to update
