### ISSUE TITLE
v2 item-group documentation error

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#6777]
#### Short description of the problem:

Documentation on http://ionicframework.com/docs/v2/components/#list-dividers  suggests that item-group is an outer wrapper around everything

```
    <ion-item-group>

      <ion-item-divider light>A</ion-item-divider>
      <ion-item>Angola</ion-item>
      <ion-item>Argentina</ion-item>

      <ion-item-divider light>B</ion-item-divider>

    </ion-item-group>
```

However as per 
https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/lists/dividers/template.html

item-group is once per group, **i.e. you do not put more than one divider per item-group**

```
    <ion-item-group>
      <ion-item-divider light>A</ion-item-divider>
      <ion-item>Angola</ion-item>
      <ion-item>Argentina</ion-item>
      <ion-item>Armenia</ion-item>
      <ion-item>Australia</ion-item>
      <ion-item>Austria</ion-item>
    </ion-item-group>

    <ion-item-group>
      <ion-item-divider light>B</ion-item-divider>
      <ion-item>Bangladesh</ion-item>
      <ion-item>Belarus</ion-item>
      <ion-item>Belgium</ion-item>
      <ion-item>Bhutan</ion-item>
      <ion-item>Bolivia</ion-item>
      <ion-item>Brazil</ion-item>
    </ion-item-group>

```

I think you need to tweak the documented example with the appropriate markup. Second one is right.

If you do it as first (and currently) described, the last-child CSS does not apply correctly, so you end up with border lines that you don't with the second markup.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Good catch! I committed a fix to the docs which will go public next time we push the staging docs to public. Thanks for using Ionic!
