### ISSUE TITLE
Navbar title truncated on iOS device

### ISSUE THREAD

**Issue by yuyinitos** [driftyco/ionic#6778]
The navbar title is truncated due to the text-overflow even if there are no buttons and there is enough space. This only happens on an actual iPhone device. Not in the emulator nor web.

**The code:**
```
<ion-navbar *navbar>
  <ion-title>{{ title }}</ion-title>
</ion-navbar>
```

**Version info:**
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014

![img_1323](https://cloud.githubusercontent.com/assets/4574988/15815777/748e8db4-2bcf-11e6-9a94-faad23dd3c1d.jpg)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This styling is on purpose and emulates a native ios apps styling. If you need to have a long title in the navbar of your app then i would suggest just overriding the styling with some custom css. Thanks for using Ionic!
