### ISSUE TITLE
Disable scrolling while swipe to go back

### ISSUE THREAD

**Issue by F1ow** [driftyco/ionic#6780]
I'm currently working on an app that implements PTR and SwipeToGoBack.

When I swipe to go back to the previous page sometimes I accidentally trigger the PTR because vertical scrolling or the PTR isn't disabled.

I think while swiping back, vertical scrolling should be disabled.

I appreciate any suggestion for a workaround...

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
