### ISSUE TITLE
Add --info and --debug options to ionic

### ISSUE THREAD

**Issue by Hypher** [driftyco/ionic#6781]
Pass --info and --debug flags to gradlew to help debugging build problems.
Note that gradlew output on such problems ask the user to use theses. (ionic not supporting them is a bit confusing)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the ionic-cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1041
