### ISSUE TITLE
ion-nav-back-button is hide

### ISSUE THREAD

**Issue by gaterking** [driftyco/ionic#6782]
When I use ion-nav-view to change page view,  the next view can't show ion-nav-back-button, it is hide. What's wrong with my code?

ionic 1.3.1

https://embed.plnkr.co/1sMskiLgv8Cei0co1VRG/

**Comment by gaterking** [comment]
I think i found the solution. I use ui-sref instead of ng-href, then the view history will be recored. If I wan't to use ng-href, maybe I need to use ui-router Nested States & Nested Views.
Anyone can explain detail?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
