### ISSUE TITLE
bug: Scroll zooming still not working

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#6788]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I opened a issue long time ago #5707 regarding zooming not working for scroll component. Both of the issues related to that are closed and as of beta 8 it is still not working.</span>

<span is-issue-template></span>

**Comment by rachelxi** [comment]
Still not working on beta 10 released on 27/06

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5701

**Comment by KevRyan2** [comment]
@jgw96 it doesn't look like there's a resolution to this issue in #5701 , can you please provide some clarification on the solution for this?
