### ISSUE TITLE
Expose pinch-to-zoom from scroller

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#679]
The scroll system supports it, so we should expose this through the scroll system.

**Comment by JerryBels** [comment]
Hello,

I know this is a very old issue but wonder if it's possible that a new update broke it on Android ? I'm testing a very simple code : 

	<ion-modal-view>
		<ion-scroll zooming="true" style="width: 100%; height: 100%;">
			<img ng-src="{{modalMediaThumb}}" class="maxPage" ng-if="modalMediaType == 1" />
		</ion-scroll>
	</ion-modal-view>

And it doesn't allow zooming - pinching the screen don't do anything.

**Comment by ziobudda** [comment]
Any news for this zoom problem ? In ionic 1.3.1 it does not work

**Comment by huilianyi** [comment]
+1. Android zoom still does not work
