### ISSUE TITLE
Automatic animation management

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6791]
#### Short description of the problem:
In the app I'm currently working on, I have a modal which opens after an action sheet button is clicked (or tapped). The problem I encounter, is that I have to manually wait for the transition to be finished, using a promise (which by the way introduces some lag). I think this is not elegant and should be managed framework side.

#### What behavior are you expecting?
Almost no animation at all when not checking for transition. It also prevents the `Modal.onDismiss` callback from being called.

**Steps to reproduce:**
1. Open an alert or action sheet
2. In one of the handlers, open a modal
(Let me know if you want a Plunker)

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a plunker that demonstrates this issue? Im having a little bit of a hard time understanding this issue but a plunker should clear it up for me (:

**Comment by Bouzmine** [comment]
[Here](http://plnkr.co/edit/vXc4WoNmB6Onb6hlHYDE?p=preview) is the Plunker. Look in `openAction()` method in `home.ts`. I've not been able to reproduce the inexistant animations, the modal wouldn't show without the ugly code.

**Comment by jgw96** [comment]
Ahh, ok i see now, thanks for the plunker! So this is actually the correct and preferred way to do navigation in Ionic 2. Our entire navigation system in Ionic 2 is async and built around using promises. You can read more about that [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/). Thanks for using Ionic and hopefully those docs clear everything up for you! I will be closing this issue, but feel free to comment if you have any more questions, or you can check out our [forum](https://forum.ionicframework.com/) too.

**Comment by Bouzmine** [comment]
Could there be a method on NavController to get most recent transition promise. That way I wouldn't have to have a `currentTransition` property in my view controllers (when I open another Alert in a function, for example).
