### ISSUE TITLE
bug: Packaging component break them

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic#6792]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, I noticed this "problem" with <ion-item> and now <ion-textarea> but I think is quite global.

Here is my use case : I want to build a "smart" textarea usint at.js

So I made an Angular Component : 
```
@Component({
    selector: 'textarea-rich',
    template: `<ion-textarea></ion-textarea>`
})
export class TextareaRichComponent implements OnInit {
    constructor(private _elementRef: ElementRef) {}

    ngOnInit() {
        // some logic
    }
}
```
And I want to use it elsewhere in my app :
```
@Page({
    directives: [RichTextareaComponent],
    template: `
<ion-navbar *navbar>
    <ion-title>Home</ion-title>
</ion-navbar>
<ion-content>
    <ion-list>
        <ion-item>
            <ion-label floating>Description</ion-label>
            <textarea-rich></textarea-rich>
        </ion-item>
    </ion-list>
</ion-content>
`
})
export class HomePage {
    constructor(private _nav: NavController){}
}
```

Ex: http://plnkr.co/edit/PFVsazbmM1BlfgxX783x?p=preview

This break the component... :(
It was the same in Angular 1 but I could warkaround it using `replace: true` in my directive but in Angular 2 I can't...

To me, it's the Ionic css which break... But I didn't investigated much.
It's quite frustrating to not be able to create some extended components such as `<item-user>` or `<textarea-rich>` to enhance Ionic capabilities...</span>

<span is-issue-template></span>

**Comment by iignatov** [comment]
@loicknuchel Could you provide more information - what does _"this break the component"_ mean?

**Comment by jgw96** [comment]
Hello @loicknuchel ! Thanks for opening an issue with us. Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by loicknuchel** [comment]
Hi @jgw96 does plunker work well with Ionic2 TypeScript ?

**Comment by loicknuchel** [comment]
Here are two screenshots demonstrating the problem : 
![ion textarea](https://cloud.githubusercontent.com/assets/653009/15863975/67362698-2cd5-11e6-8b06-82b2797b8c97.png)
![textarea rich](https://cloud.githubusercontent.com/assets/653009/15863974/672f4b16-2cd5-11e6-9449-ee8eb56fe332.png)

And the code : 
```js
import {Component} from "@angular/core";

@Component({
    selector: 'textarea-rich',
    template: `<ion-textarea></ion-textarea>`
})
export class TextareaRichComponent {
    constructor() {}
}
```

```js
import {Page} from "ionic-angular";
import {NavController} from "ionic-angular/index";
import {TextareaRichComponent} from "../common/components/textarea-rich.component";

@Page({
    directives: [TextareaRichComponent],
    template: `
<ion-navbar *navbar>
    <ion-title>textarea-rich</ion-title>
</ion-navbar>
<ion-content>
    <ion-list>
        <ion-item>
            <ion-label floating>Description</ion-label>
            <textarea-rich></textarea-rich>
        </ion-item>
    </ion-list>
</ion-content>
`
})
export class HomePage {
    constructor(private _nav: NavController){}
}
```

For the first exemple, simply replace `<textarea-rich>` by `<ion-textarea>` in home template.

**Comment by jgw96** [comment]
@loicknuchel It sure does (: In the issue template that is displayed when you open an issue with us there is a link to a plunker already set up for Ionic 2 with typescript. [Here](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) is a link to the plunker.

**Comment by loicknuchel** [comment]
@jgw96 Thanks for setting up the plunker :)
Here it is : http://plnkr.co/edit/l6DSucgMsQWJgitZhheZ?p=preview

**Comment by iignatov** [comment]
@loicknuchel I couldn't run your plunker due to some errors - here's an updated version that should work:
http://plnkr.co/edit/PFVsazbmM1BlfgxX783x?p=preview

**Comment by loicknuchel** [comment]
@iignatov Strange... What was the errors ?

So, your pluker shows the "problem"... I was expected that the two textarea were similar in UI (which is not and the second is quite broken)

**Comment by jgw96** [comment]
@loicknuchel It looks like the errors in your plunker were because you were using `@Page`, `@App` which are now deprecated with the beta.8 release. You can read about the changes and cool new features in beta.8 here https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md. I will be looking more into your problem.

**Comment by iignatov** [comment]
@loicknuchel I think that it's related to issue #6643. I just tried using `item-content` in the [plunker](http://plnkr.co/edit/jFMb98PsXh0NZsTcw8x4?p=preview) and it works. You could upgrade to `beta.8` and add the `item-content` attribute to your custom component.

**Comment by loicknuchel** [comment]
it's so cutting edge ;) I saw tonight that the beta.8 is available... I'll check that tomorow :)

**Comment by loicknuchel** [comment]
It works \o/
Really cool, thanks !
