### ISSUE TITLE
ionic2 enhancement(popover) - hide arrow when there is no target

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6796]
#### Short description of the problem:
When there is no event passed to nav.present, the popover will appear in the center of the page with the arrow pointing to whatever is under it.

#### What behavior are you expecting?
I would like the arrow to be hidden if no event is passed in.

**Steps to reproduce:**
1. Create a popover and present it without passing in an event. Notice the arrow.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This could either be implemented as default behavior or as a user option that is passed in to Popover.create()
 
**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta 9` release. :smile:
