### ISSUE TITLE
bug: backdrop only works for first of multiple ion-menu

### ISSUE THREAD

**Issue by doctorrustynelson** [driftyco/ionic#6798]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I was able to produce this issue by setting up two different overlay ion-menus with different ids and having a different page to toggle each of the menus.  I noticed that the second menu that was defined would not activate the backdrop and thus I could click on things not covered by the second menu which I did not expect.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
@doctorrustynelson hi! please run `ionic info` and post the results

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
