### ISSUE TITLE
Failed to install ionic-platform-web-client

### ISSUE THREAD

**Issue by zh-wowtv** [driftyco/ionic#6801]
I followed the ionic.io document and tried to install ionic-platform-web-client by:

> ionic add ionic-platform-web-client

But failed with the following error message:

```
You must have bower installed to continue. 
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

What could be the reason? Any suggestion? Thanks.

**Comment by wb9688** [comment]
Have you installed bower as the error message suggests?

**Comment by zh-wowtv** [comment]
Of course， I installed bower. My bower version is 1.7.9.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by wb9688** [comment]
@jgw96 It's a bug. Create a v1 project with the v2 cli and try adding a plugin (eg. `ionicdatepicker` or the `ionic-platform-web-client` mentioned by @zh-wowtv) and it will fail with that error message  even if you've install `bower`...

**Comment by jgw96** [comment]
Ahh ok, thanks for clearing this up @wb9688 . I will be moving this issue to the ionic-cli repo as this issue is related to the ionic cli and not the ionic framework.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1055
