### ISSUE TITLE
Native transitions hides content

### ISSUE THREAD

**Issue by nux17** [driftyco/ionic#6803]
#### Short description of the problem:
I have a static top-left menu which opens with a nice animation and permits to navigate through my app. I developped the whole time with  `$ionicConfigProvider.views.transition("none");`, but now I want to activate native transitions and removed this line from config, this menu is hidden in the background. I don't get why the default transition setting should impact content, as I don't see changes in CSS or whatever.

![nok](https://cloud.githubusercontent.com/assets/6410827/15895363/29fd3e86-2d8b-11e6-8848-e71bbf085fb1.png)

#### What behavior are you expecting?
Nothing changing, just transitions depending on platform, and my menu where it belongs.

![ok](https://cloud.githubusercontent.com/assets/6410827/15895351/15e9e624-2d8b-11e6-9b5c-b75b7db136df.png)

**Which Ionic Version?** 1.x or 2.x
1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v5.5.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by nux17** [comment]
I don't really know how to reproduce it i'm afraid, it involves some jQuery plugins and specific content. I will give it another try when I'll have the time for, but it's a tough job to plunkerize it.

**Comment by jgw96** [comment]
No problem, I will close this one for now, as I can't seem to reproduce it with Ionic 1.3.1 on my Nexus 6 , but if your able to get a good, easily reproduce able example together feel free to comment here and I will reopen. Thanks for using Ionic!
