### ISSUE TITLE
Animation and display:none

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6810]
When animating using the animation class, if animating a component with `display:none` set, the animation will `fallback`.

In order to get around this limitation, in some cases we use `visibility: hidden` instead of `display:none`.  This is a less performant work around.

See the modal.scss file here for an example:
https://github.com/driftyco/ionic/blob/2.0/src/components/modal/modal.scss#L25

Please update the modal.scss to `display:none` to validate the fix.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#217
