### ISSUE TITLE
Issue with the MyIonic2Project tutorial --v2 --ts

### ISSUE THREAD

**Issue by ValterSantosMatos** [driftyco/ionic#6818]
The tutorial doesn't build with the Ionic 2 Beta 8 version.

**Steps to reproduce:**
ionic start MyIonic2Project tutorial --v2 --ts

**Comment by ChogyDan** [comment]
I've been trying to wrap my head around this too.  I guess the issue is obvious if you try to run the app.  It also gives an error about App not being the right typeof.  And clearly in the code, App is a class, not a decorator.  Am I right in that assertion?

**Comment by ValterSantosMatos** [comment]
I think they are still using the template for v7. If you follow the
guidelines to update from v7 to v8 you can make it work.

**Comment by ChogyDan** [comment]
Yes!, it is mentioned right in the changelog.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! I just fixed this so if you just run `ionic start MyIonic2Project tutorial --v2 --ts` again it will start the tutorial app with my fixes. Thanks for using Ionic!
