### ISSUE TITLE
Android floating inputs don't show the bottom border when using inside an ngControl.

### ISSUE THREAD

**Issue by ValterSantosMatos** [driftyco/ionic#6819]
Hi,

#### Short description of the problem:
The issue only occurs on v2  beta 8, when using the floating input inside an ngForm in the Android platform, after typing something on the input the the bottom border disappears, see images bellow.

![1](https://cloud.githubusercontent.com/assets/7823134/15920653/33345be2-2e4e-11e6-847c-090ac39af70a.png)
![2](https://cloud.githubusercontent.com/assets/7823134/15920656/36ddc3b4-2e4e-11e6-963a-70a6fb7fb7a3.png)

**Which Ionic Version?** 1.x or 2.x
Ionic2 Beta 8

#### Plunker that shows an example of your issue
Tried to do a plunker but I can't make it to run the android version, the code is there.
https://plnkr.co/edit/marCna?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I made a modified version of your plunker [here](https://plnkr.co/edit/u4Zu6M?p=preview) that uses our Android theme. Unfortunately, i cant seem to reproduce this issue with this plunker. If you could give it a try that would be great! Thanks for using Ionic!

**Comment by ValterSantosMatos** [comment]
It took me a while to understand what was going on!

So it happens that while customizing the theme of the application the second color of my app is white. So I change the $colors secondary color to white in the app.variables.scss.

When the input field is validated Ionic adds the secondary color as the bottom border, so you see the green since that is the default color, mine was white so I couldn't see it!

My comment is that this is really not explicit here:
```
// App Shared Color Variables
// --------------------------------------------------
// It's highly recommended to change the default colors
// to match your app's branding. Ionic uses a Sass map of
// colors so you can add, rename and remove colors as needed.
// The "primary" color is the only required color in the map.
// Both iOS and MD colors can be further customized if colors
// are different per mode.

$colors: (
  primary:    #387ef5,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
  favorite:   #69BB7B
);
```

I did a small search on the Overriding Ionic Sass Variables and found out that the Secondary, the Danger and the Dark colors are also used by Ionic.

As a suggestion I guess that could/should be mentioned in this section so the we know that might be other implications of changing this colors :)

Thanks for the plunk, 
PS. Another suggestion is to have the IOS and Android Plunk available when creating a new issue.

**Comment by jgw96** [comment]
Thanks for the suggestions @ValterSantosMatos ! I will discuss them with my team and i will also update our plunker to be able to use both the Android and IOS theme. Thanks for using Ionic!
