### ISSUE TITLE
Single clicks not working on Windows 8.1 phones

### ISSUE THREAD

**Issue by richshakespeare** [driftyco/ionic#6821]
I've been building an app with Ionic which has worked flawlessly in Chrome, Firefox, and Safari, but which has exhibited a weird behaviour on Windows phones.

Single touch events are not triggering for links, buttons, and elements with ng-click handlers. They perform as expected on some directives, such as the navigation tabs.

I traced this to this bit of code, which looks like it was added (here https://github.com/driftyco/ionic/issues/2885) following directly contradictory issues to the one I'm reporting. I commented out the relevant part which looks like it suppresses clicks.

```

  requiresNativeClick: function(ele) {
    //if (ionic.Platform.isWindowsPhone() && (ele.tagName == 'A' || ele.tagName == 'BUTTON' || ele.hasAttribute('ng-click') || (ele.tagName == 'INPUT' && (ele.type == 'button' || ele.type == 'submit')))) {
    //  return true; //Windows Phone edge case, prevent ng-click (and similar) events from firing twice on this platform
    //}
    if (!ele || ele.disabled || (/^(file|range)$/i).test(ele.type) || (/^(object|video)$/i).test(ele.tagName) || ionic.tap.isLabelContainingFileInput(ele)) {
      return true;
    }
    return ionic.tap.isElementTapDisabled(ele);
  },

```

The app seems to work fine with this code commented out.

I'm using Ionic 1.2.4, on a Windows 8.1 Phone. Any thoughts on what the core issue is or on the safety of commenting this out would be much appreciated!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not support Windows phone 8.1, so unfortunately there is not much we can do about this issue. However e do support Windows 10 for desktop and phone with Ionic 2. I am sorry I couldn't give you a better answer than this. Thanks for using Ionic!
