### ISSUE TITLE
bug: Disabling range not working

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#6824]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Adding [disabled]="true" to ion-range is not disabling it.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
@ErkoKnoll this was already fixed. wait until next release! https://github.com/driftyco/ionic/pull/6800
