### ISSUE TITLE
bug: Ion-tab icon not rendered after being changed

### ISSUE THREAD

**Issue by leiyuangui** [driftyco/ionic#6828]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>We want to change the icon dynamically according to the content type. We are changing the icon name dynamically within the ion-tab element. The name has changed successfully,  but the rendered icon has not. A close investigation shows that the generated element <i> keeps the old icon class. It is never being removed.  

Please can someone point me to the possible workaround?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provider a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by leiyuangui** [comment]
Hi, 

Thanks for getting back to me. This issue appears having been fixed in the latest release (nightly build). We are using version 1.3.0. Hence the problem. I managed to create a plunker example [here](https://plnkr.co/edit/npOmOyxNfdk0Q7XYrBOh).

Thanks,
Yuangui
