### ISSUE TITLE
<ion-datetime> doesn't play well with other elements in <ion-item>

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#6829]
I want to use ion-datetime inside an ion-item, but I want to include other elements as well for picking the days of the week.

Goal:
![screen shot 2016-06-09 at 12 26 44 pm](https://cloud.githubusercontent.com/assets/12073894/15937589/8ba53730-2e3d-11e6-9825-3948bf99de9d.png)

If I use the ion-item markup, then this is what I get:
![screen shot 2016-06-09 at 12 31 46 pm](https://cloud.githubusercontent.com/assets/12073894/15937755/2e536a88-2e3e-11e6-8ce7-24122128dbd5.png)

To get around this issue, I have to change ion-item to div with position:relative. But now I lose out on swipe to delete etc. 

Preferred Markup:
```
<ion-item *ngFor = "let reminder of reminders">
    <ion-datetime displayFormat="h:mm a" pickerFormat="h mm a" [(ngModel)]="reminder.time"></ion-datetime>
    <select-days-from-week [schedule] = "reminder.schedule"></select-days-from-week>
</ion-item>
```

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement custom functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
