### ISSUE TITLE
Firefox rendering issue: Update pound symbol in the item-inner background css with url encoding

### ISSUE THREAD

**Issue by tmacblane** [driftyco/ionic#6830]
**Description**
When using Firefox, the item-inner background-image is throwing a 404 error.

Firefox was not able to render the '#' sign in the css; replacing '#' with '%23' appears to resolve the issue.
```
www/build/css/app.ios.css
line: 6868

button.item:not([detail-none]) .item-inner,
a.item:not([detail-none]) .item-inner,
.item[detail-push] .item-inner {
  background-image: url("data:image/svg+xml;charset=utf-8,<svg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2012%2020'><path%20d='M2,20l-2-2l8-8L0,2l2-2l10,10L2,20z'%20fill='#c8c7cc'/></svg>");
```
**Expected Behavior**
To see the item-inner button background image render when using Firefox

**Ionic Version**
2.0.0-beta.8

**ionic info from cmd prompt:**

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.2

**Comment by brandyscarney** [comment]
Thanks for the issue and debugging. This will be fixed in the `beta 9` release! :smile:
