### ISSUE TITLE
*ngIf outside <ion-content> causes element to load prior to it's parent component.

### ISSUE THREAD

**Issue by MattDHill** [driftyco/ionic#6832]
#### What behavior are you expecting? Any elements containing *ngIf statements should load along with the rest of the component and not before.

**Steps to reproduce:**
1. check out this repo: https://github.com/MattDHill/ngIfIssue
2. run ionic emulate ios
3. click "item 1" and watch the toolbar and nabber button load before the target page.
 

**Which Ionic Version?** 2 beta8

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014 ```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Does this only happen on ios?

**Comment by MattDHill** [comment]
No, apologies. It is not isolated to iOS.

**Comment by brandyscarney** [comment]
Is this still happening in the `beta 10` release?

**Comment by jgw96** [comment]
Hello all, i just tested this and it does not seem to be an issue with the latest nightly. Thanks for using Ionic!
