### ISSUE TITLE
Content-repeat and use of custom directive that sets 'background-image' property is buggy

### ISSUE THREAD

**Issue by miparnisari** [driftyco/ionic#6834]
#### Short description of the problem:
I am using the directive `collection-repeat` with an array of contacts. Within it, I use a custom directive to display an image, a title and a subtitle. The directive makes use of the CSS property `background-image` to show the image.

The issue is that when I refresh the model array and the URL of the images chage, the behavior of the images becomes buggy: as you scroll, for some items the image displayed is incorrect. Demo [here](http://plnkr.co/edit/t4opQdqr4VStpqP6MdQn?p=preview).

#### What behavior are you expecting?
The images to be completely refreshed when the model array is changed.

**Steps to reproduce:**
In the demo, when you click on "Facebook contacts" the image shown is the Facebook logo. However, when you click on "Google" contacts, and scroll, the images are sometimes incorrect.

```html
  <ion-content>
    <ion-list>
      <div class="item item-avatar" 
      collection-repeat="contact in viewing"
      force-refresh-images="true"
      ng-click="selectContact(contact)">
        <custom-avatar from="contact"></custom-avatar>
        <h2>{{contact.title}}</h2>
        <p>{{contact.subtitle}}</p>
      </div>
    </ion-list>
  </ion-content>
```

```javascript
.directive('customAvatar', function($$jqLite) {
    return {
      restrict: "AE",
      transclude: true,
      scope: {
        from: '='
      },
      template: '<div class="from" ng-class="{hasNotPic:!fromUrl}"></div>',
      link: function(scope, element, attrs) {
        var process = function() {
          element.on('click', function(e) {
            e.preventDefault();
            e.stopPropagation();
          })

          if (scope.from) {
            scope.fromUrl = scope.from.feed_pic_url;

            var fromEl = element[0].querySelector('.from');

            if (scope.fromUrl) {
              $$jqLite(fromEl).css('background-image', 'url("' + scope.fromUrl + '")');
            } 
          }
        }

        var destroy = scope.$watch('from', function() {
          if (scope.from) {
            process();
            destroy();
          }
        });

      },
      
    };
  }
```

**Other information:** the issue disappears if instead of using a custom directive I use `<img ng-src={{contact.feed_pic_url}} />`
 

**Which Ionic Version?** 1.3.1

#### Plunker that shows an example of your issue

http://plnkr.co/edit/t4opQdqr4VStpqP6MdQn?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement custom functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by miparnisari** [comment]
Thanks @jgw96. I posted it here: https://forum.ionicframework.com/t/use-of-collection-repeat-with-custom-directive-that-displays-images/54465.

**Comment by miparnisari** [comment]
I ended up using `collection-repeat` with `img` tags instead of trying to use `background-image` and it works.
