### ISSUE TITLE
Ionic 2 Alert Bug: setCssClass overrides existing css classes

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic#6835]
#### Short description of the problem:
The Alert method setCssClass does not add a cssClass as documented but sets it and overrides existing css classes that have beeen set while creating the Alert (or that have been passed on by Selections)

#### What behavior are you expecting?
The method works as documented and adds cssClasses without overriding existing ones. Maybe the name of the method should be changed to addCssClass to make things more clear.

**Steps to reproduce:**
1. Easiest way: Look at the implementation of the Alert method setCssClass
2. Alternatively: Create an Alert with an cssClass given
3.  Look ath the Dom. The css class does not appear in the Dom because it gets overriden with the default css classes of an Alert (via the method setCssClass)

 

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by ch-weiss** [comment]
Thank you for your interest. I think in this context it makes more sense to have a look at the current implementation of the method setCssClass in Alert which is supposed to add a cssClass but it really sets it instead of adding:

257   /** 
258    * @param {string} cssClass CSS class name to add to the alert's outer wrapper 
259    */ 
260   setCssClass(cssClass: string) { 
261     this.data.cssClass = cssClass; 
262   }

**Comment by ZiFFeL1992** [comment]
This seems to be fixed by: https://github.com/driftyco/ionic/commit/215c6d846c6eb157b4510e63d863d2fdcf13b9af.

**Comment by brandyscarney** [comment]
So what I'm seeing with the latest is:

```
let alert = this.alertCtrl.create({
  title: 'Alert',
  buttons: ['Cancel', 'OK'],
  cssClass: 'my-alert'
});

alert.present(alert);
```

This creates an alert with the classes: `my-alert alert-cmp`

and if I call the function to set the class like this:

```
let alert = this.alertCtrl.create({
  title: 'Alert',
  buttons: ['Cancel', 'OK'],
  cssClass: 'my-alert'
});

alert.setCssClass('custom-alert');
alert.present(alert);
```

then the following classes are added: `custom-alert alert-cmp`

I think this function is doing what it should, but maybe you are asking for a function that just adds classes @ch-weiss?

**Comment by ch-weiss** [comment]
@brandyscarney: Thank you for the explanation. The problem I identified is in the context of selections. Selections offer the possibility to specify a css class parameter which is passed on to the generated alert. I did this but in the dom I did not find the specified css class. So I debugged what happens and found that during alert generation the css class is passed on to the alert correctly but then the standard alert classes are set using the method setCssClass of alert thus overriding the css class that came from the selection. In this context there is also no way to set the alert css class later because I do not know a way to access the generated alert. 
So maybe the setCssClass method works as intended and there is an issue in the alert generation from selections.

**Comment by brandyscarney** [comment]
@ch-weiss Thanks for the description! I'm able to see the problem using selects.

**Comment by brandyscarney** [comment]
This will be fixed in the `beta 11` release. Thanks for the issue!

**Comment by ch-weiss** [comment]
@brandyscarney Thanks for your attention and to the whole team for the awesome work!
