### ISSUE TITLE
bug: Fixed position not working as expected

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#6838]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Normally if I position an element fixed in CSS I expect the element to be relative to the viewport. But when I apply a fixed position to an element in the navbar, that element seems to be relative to the navbar instead of the viewport.

Steps to reproduce:
1) Add a button with fixed position to the navbar e.g.
```
<ion-navbar *navbar>
  <ion-buttons style="position: fixed; top: 5px; right: 0;">
    <button>
      <ion-icon name="cart"></ion-icon>
    </button>
  </ion-buttons>
</ion-navbar>
```
2) Move the navbar up via CSS
(e.g. applying `transform: translate3d(0px, -100%, 0px);` to the `<ion-navbar-section>`
3) Fixed positioned button is moved up together with the navbar</span>

<span is-issue-template></span>

Demo:
![ezgif com-crop-2](https://cloud.githubusercontent.com/assets/5305150/15961604/e749cb78-2f05-11e6-8176-da9594f331a9.gif)

Plunker:
http://embed.plnkr.co/ghHNdH/

**Comment by ladmerc** [comment]
Yup, experiencing this now

**Comment by flavordaaave** [comment]
I think this is because of `translateZ` on some container elements. See:
http://stackoverflow.com/a/15885486/3325565

**Comment by ladmerc** [comment]
In my case, I solved the issue by moving the element to be fixed out of ion-content. Apparently ion-content scrolls whatever is in it

**Comment by jgw96** [comment]
Hello @flavordaaave this will most likely be resolved a layout refactor we are currently doing. I will let you know more info when that refactor hits the 2.0 branch and i test it. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello @flavordaaave ! Just tested this with our latest nightly that hast the layout refactor i mentioned and it looks like its fixed! You should be able to do something like:

```
<ion-header>
  <ion-navbar>
    <ion-buttons style="position: fixed; top: 5px; right: 0;">
      <button>
        <ion-icon name="cart"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```
and it will just work. If you would like to try this out you can install the latest nightly with `npm install ionic-angular@nightly`. If you still have issues with it feel free to comment and i will happily reopen this issue. Thanks for using Ionic!
