### ISSUE TITLE
Update TSLint to force else on same line as closing if bracket

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6841]
^

Also fix the issues reported with this

**Comment by brandyscarney** [comment]
Wasn't this done?

**Comment by danbucholtz** [comment]
No, I have been putting this off because I don't want to go back and fix all of the inevitable issues.  I will do this now.

**Comment by danbucholtz** [comment]
This is effectively done, just waiting on write access to the tslint-ionic-rules repo.
