### ISSUE TITLE
bug: [Bug] Modal toolbar icon not at start

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#6842]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Any of the android platforms that use modals with `toolbars` for replacing the missing `navbar` will put the icons to the right even if we use the `<ion-buttons start></ion-buttons>` tag:
![image](https://cloud.githubusercontent.com/assets/9698639/15970186/1476ac9a-2ef9-11e6-8bce-60bcfa94c77f.png)

This doesn't happens when showing the ios styles version.
</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
This issue shows the conversation about the `<ion-navbar></ion-navbar>` not working: https://github.com/driftyco/ionic/issues/6598

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! The navbar not showing issue has been fixed in beta.8, which if not mistaken would also fix this issue as you would not need a toolbar anymore. For instructions on how to upgrade you can read the changelog [here](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md) Thanks for using Ionic!

**Comment by jgw96** [comment]
@Luchillo After looking at this again i am going to open a new issue related to the start and end position of buttons in toolbars, but if you upgrade to beta.8 then you will be able to use a navba in your like your supposed to be able to. Thanks again!

**Comment by Luchillo** [comment]
Really?! Yaaay, i've already updated to beta.8, however i am using a navbar in one of the modals, although it works, the back button that should replace the menu button doesn't show.

**Comment by jgw96** [comment]
Hey @Luchillo ! Would you mind opening a separate issue for that bug please? Thanks!

**Comment by Luchillo** [comment]
Ok

**Comment by lisatassonesimpro** [comment]
@Luchillo There is still an issue with the back button being hidden in the latest RC of Ionic. Did you end up putting an issue in for it?

**Comment by Luchillo** [comment]
I don't remember, i'm still using beta.11, current build process is still a no go for me, i like to have full control over the build process.

Try searching for issues with my nick name as the author, most likely i did made an issue.

**Comment by m00g33k** [comment]
Still an issue when trying to insert an ion-buttons start in toolbar in a modal
