### ISSUE TITLE
bug: CORS

### ISSUE THREAD

**Issue by droiddavid** [driftyco/ionic#6851]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>
<span ionic-description>from ionic info...
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
OS: Windows 8.1
Node Version: v0.12.2
-------------------------------------------
I am NOT a novice coder which I am stating because I am asking for a comprehensive answer which does not include ANY of the steps I've tried so far.

From app.js to getUser.php to apache to the browser, I have tried the following; each of which results in the same error "GET http://localhost:8080/database/getUser.php net::ERR_CONNECTION_REFUSED   ionic.bundle.js:25000" written to the console...

PS this app is the ionic tab starter.
-------------------------------------------
In app.js
CONFIG SECTION (Partial/relevant code listed)
app.config(['
$stateProvider', '$urlRouterProvider', '$httpProvider', 
function ($stateProvider, $urlRouterProvider, $httpProvider) {
	'use strict';
	$httpProvider.defaults.useXDomain = true;
	delete $httpProvider.defaults.headers.common['X-Requested-With'];
...the rest of config not listed for brevity
-------------------------------------------
app.controller('DashCtrl', function ($http, $scope) {'use strict';
	$scope.user = {email: 'flash@gordon.com', password: 'locutus'};
	$scope.login = function (user) {
		$http.get('http://localhost:8080/database/getUser.php',{
	'email': user.email, 'password': user.password,
	'contentType': 'application/json; charset=utf-8',
	'dataType': 'json'})
	.then(function (response) {console.log(response);});}; //$scope.login
}); //DashCtrl
-------------------------------------------
getUser.php
<?php
header("Access-Control-Allow-Origin: *");
require_once 'dbHelper.php';$db = new dbHelper();
$_POST = json_decode(file_get_contents('php://input'), true);
$rows = $db->select("person",array('emailaddress'=>$_POST['email'], 'password'=>$_POST['password']));
$json = json_encode( $rows,JSON_NUMERIC_CHECK );
echo "$json";
?>
-------------------------------------------
config.xml added the following lines...
  ...
  <access origin="*"/>
  <access origin="tel:*" launch-external="yes"/>
  <allow-navigation href="*"/>
  <allow-navigation href="http://*/*"/>
  <allow-navigation href="https://*/*"/>
  <allow-navigation href="data:*"/>
  <allow-intent href="*"/>
  <access origin="*"/>
</widget>
-------------------------------------------
On APACHE in httpd-vhosts.confg (partial listing)
-------------------------------------------
 ...
<VirtualHost *:80>
	DocumentRoot "c:/xampp/htdocs/neighborfood"
	ServerName localhost.neighborfood
	ServerAlias *.localhost.neighborfood
	<Directory "c:/xampp/htdocs/neighborfood">
		Header always set Access-Control-Allow-Origin "*"
		RewriteCond %{REQUEST_METHOD} OPTIONS
		RewriteRule ^(.*)$ blank.php [QSA,L]
		RewriteRule ^(.*)$ $1 [R=200,L]
		Header always set Access-Control-Allow-Origin "*"		
		Order allow,deny
		Allow from 127.0.0.1
		Allow from all
    </Directory>
</VirtualHost>
-------------------------------------------
in httpd.conf
<IfModule mod_headers.c> 
	SetEnvIf Origin "http://localhost:8100/#/tab/dash$" AccessControlAllowOrigin=$0$1
	Header Set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
	Header Set Access-Control-Allow-Credentials "true"
	Header Set Access-Control-Allow-Methods "GET, POST, OPTIONS"
	Header Set Access-Control-Allow-Headers "origin, content-type, accept, X-Requested-With"
	Header always unset Expires
</IfModule>
-------------------------------------------
in .htaccess
Header always set Access-Control-Allow-Origin "*"
-------------------------------------------
ADDITIONALLY, I have also downloaded and installed the Chrome plug-in for CORS which shows green when active and red when inactive.

Regardless of all of the above, nothing has worked.  This has already cost me more than two and a half weeks of development.  The only thing I have found and not tried is a proxy solution which I have not yet tried because I don't understand how it works.  Please, please, please do not reiterate any of the solutions listed around the net as I have tried an awful lot of them and am looking for a solution which actually works.

My app without ionic works perfectly.  I am on a Windows 7 machine with all the up-to-date browsers.

What is Ionic going to do to prevent this CORS issue which seems to be plaguing a lot of developers?

What solution exists which actually works?

P.S.  I have also tried running Chrome from the CLI using c:\path_to_chrome\chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security

If I can't use the $http service or jquery ajax or raw/vanilla ajax, then ionic is therefore useless to me.

PLEASE HELP!!!!!!</span>

<span is-issue-template></span>

**Comment by danbucholtz** [comment]
Hi @droiddavid 😄 ,

Thanks for submitting an issue to Ionic.  It sounds like the issue you're experiencing is on your server.  It doesn't seem like an issue with the framework itself.  My recommendation is to make sure you're setting the CORS header if that is what the server is expecting.

A good place to ask for help troubleshooting issues would be the [Ionic community forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA) or [stackoverflow](http://stackoverflow.com/).

Please let me know if there is anything with the framework we can help you out with.  Thanks for using Ionic and contributing!

Thanks,
Dan

**Comment by droiddavid** [comment]
Again, I have set everything on the server, repeatedly and I do not have this issue when I am not using ionic.  I have perused and searched the forums and tried each of the solutions offered to no satisfaction.  At this point, the only issue is ionic.  If I put ionic away and go back to raw angular, my application works.  In other words, the forums have been no help what-so-ever.  Is there ANYTHING

**Comment by danbucholtz** [comment]
If you can make a very simple example demonstrating the problem, we can look into it.  We are not going to be able to spin up your server, though.  Ionic uses Angular 1.5.3, so the http module should just work.  We are not doing anything to it, etc.

**Comment by johnymachine** [comment]
Hello,
can you check origin header you are sending?

Maybe related to my problem : http://stackoverflow.com/questions/39324750/ionic-native-app-is-sending-header-originfile-which-causes-problems
