### ISSUE TITLE
Alert and select css not quite right?

### ISSUE THREAD

**Issue by vacarsu** [driftyco/ionic#6852]
The css of the alert and select field don't seem to be displaying quite right. I'm using ionic in meteor, and perhaps I'm missing an scss import somewhere. 
![screen shot 2016-06-10 at 12 10 20 pm](https://cloud.githubusercontent.com/assets/11384972/15975952/fa98c8c4-2f04-11e6-81a2-d96d7f5479e3.png)

Is there something other than ionic.scss I must import?

``` client/theme/app.variables.scss ```
```
@import '{}/node_modules/ionic-angular/globals.core';

$colors: (
  primary:    #00802f,
  secondary:  #0f0f0f,
  danger:     #e60000,
  light:      #f4f4f4,
  dark:       #222,
  favorite:   #69BB7B
);

@import '{}/node_modules/ionic-angular/ionic.scss';
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
