### ISSUE TITLE
Value of type 'typeof App' is not callable.

### ISSUE THREAD

**Issue by mlqmarkos12** [driftyco/ionic#6853]
#### Description of the problem:
TypeScript error: app/app.ts(8,2): Error TS2348: Value of type 'typeof App' is not callable. Did you mean to include 'new'?
 
I updated from beta 7 to beta 8 because I wanted to use popovers.

After that I got this error with ionic serve, and the app doesn't start.

It seems like it's a bug with @App decorator.

**Which Ionic Version?**
2.0.0-beta.8

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.0

**Comment by brandyscarney** [comment]
Please read through the steps to upgrade to beta 8. The `@App` decorator was removed and `IonicApp` was renamed to `App`:

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#steps-to-upgrade-to-beta-8

Thanks! :smile:

**Comment by mlqmarkos12** [comment]
Thank you!
