### ISSUE TITLE
[feat] Allow for customizing the alert's dismissal

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic#6855]
#### Short description of the problem:
Currently it's not possible to configure Alert's dismissal although it's supported by the `ViewController`.

#### What behavior are you expecting?
To be able to pass [`NavOptions`](http://ionicframework.com/docs/v2/api/components/nav/NavController/#navoptions) to [`Alert.dimiss()`](https://github.com/driftyco/ionic/blob/v2.0.0-beta.8/src/components/alert/alert.ts#L553) in order to configure how an alert is dismissed.

```js
// https://github.com/driftyco/ionic/blob/2.0/src/components/alert/alert.ts
class AlertCmp {
  // ...
  dismiss(role: any): Promise<any> {
    return this._viewCtrl.dismiss(this.getValues(), role);
  }
  // ...
}

// https://github.com/driftyco/ionic/blob/2.0/src/components/nav/view-controller.ts
export class ViewController {
  //...
  dismiss(data?: any, role?: any, navOptions: NavOptions = {}) {
    let options = merge({}, this._leavingOpts, navOptions);
    return this._nav.remove(this._nav.indexOf(this), 1, options).then(() => {
      this._onDismiss && this._onDismiss(data, role);
      return data;
    });
  }
  // ...
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

https://forum.ionicframework.com/t/2-0-0-beta8-modal-animation-issue/54332

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually already in the framework as you can see [here](https://github.com/driftyco/ionic/blob/master/src/config/config.ts#L86). Thanks for using Ionic!
