### ISSUE TITLE
Opening a modal from an action sheet is broken

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#6858]
Title says it all.

I'm able to resolve this issue by adding `return false;` to the handler, but that's inconvenient for the user since they would have to close down that action sheet manually every time.

Opening the modal does add it to the DOM, it just messes up it's properties so it's not visible. I am only able to interact with that invisible modal once it's opened, I can't click on anything that I actually see.

Here's a GIF without a `return false;`
![actionsheet-without-return](https://cloud.githubusercontent.com/assets/13794420/15982430/042cf0fe-2f55-11e6-9975-fb21d98c9dba.gif)

Here's another GIF with `return false;`
![actionsheet-with-return](https://cloud.githubusercontent.com/assets/13794420/15982432/0d439e0e-2f55-11e6-9b8a-12975e0dbada.gif)

**Steps to reproduce:**
1. Create an action sheet
2. Set the action of one of the options to open a modal

2.0-beta.8

http://plnkr.co/edit/xpW62L9RJGIO13eqhj89?p=preview

**Comment by xr0master** [comment]
[Dismissing And Async Navigation](http://ionicframework.com/docs/v2/api/components/action-sheet/ActionSheet/)

**Comment by ihadeed** [comment]
Thank you @xr0master !

**Comment by xr0master** [comment]
Little fix
```
goToPage1() {
	  let actionsheet = ActionSheet.create({
	    title: 'Options',
	    buttons: [
	      {
	        text: 'click me',
	        handler: () => actionsheet.dismiss().then(() => this.nav.present(Modal.create(Page1)))
	      }
	      ]
	  });
	  this.nav.present(actionsheet);
	}
```

**Comment by ihadeed** [comment]
Thanks :D !

**Comment by Geoffrey-D** [comment]
Thanks @xr0master. this fix my issue. I don't have this issue on chrome or recent phone, but ONLY on old phone (KitKat 4.4). On old phone, we can see that the modal is "stuck" during the transition (like 90% transparent).

I have many issues with low-end phones and I feel like ionic2 is not meant to work on low-cost devices (but more of 50% of users have low-end devices....)

**Comment by jgw96** [comment]
Hello @Geoffrey-D ! Have you given [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) a try? This will give you a fast, modern chrome webview even on devices running older versions of Android. We've seen huge performance increases on older android devices with it. Also if you have a lower end device that is running Android 5.0 and up you will automatically have the latest chrome webview as it gets updated separate of Android itself. Thanks for using Ionic!

**Comment by Geoffrey-D** [comment]
Hey @jgw96, I know that crosswalk would fix many issues. But this icrease a lot the app size. Is ionic 2 supposed to work with low end devices (like 2GB RAM, Android 4.4)?! Because if the solution to work with the 50% of the users is to use crosswalk, it should me mentionned on the ionic 2 website. I know it is still an alpha, but I am a bit afraid to see that we need to do tricky stuff to support (not that) old devices.

**Comment by jgw96** [comment]
@Geoffrey-D Definitely understand your concerns! Actually, the above solution is not just the solution for older android devices, instead that is the proper way to do navigation in Ionic 2 no matter what device it is running on. Sorry for any confusion on that! Also we talk about our browser support [here](http://ionicframework.com/docs/overview/#browser-support) in our docs, although im talking to the rest of the team to see if we can make this more visible and easier to find. Finally, we are currently in beta (beta.11) and not alpha. Thanks for using Ionic!

**Comment by Geoffrey-D** [comment]
@jgw96 thx for that answer. I will give crosswalk a try and see what improvement it gives :) anyway thx for that very nice tool!

**Comment by jgw96** [comment]
No problem! 😃
