### ISSUE TITLE
App takes 1-2 seconds to load, doesn't look so good

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#6859]
I've been experiencing this with all Ionic 2 versions.

It's not really a big issue, but fixing this can improve the user experience IMO.

Launching an Ionic 2 app takes a second or two. In the meanwhile, the screen just shows plain HTML without CSS/JavaScript.

Here's a quick demo:
![slow-load](https://cloud.githubusercontent.com/assets/13794420/15982416/9c371d44-2f54-11e6-8352-d4d37d316c65.gif)

Is there a way to fix this? Are you aware of the reasons that's causing it?

Thanks!

**Comment by ZiFFeL1992** [comment]
I'm agree with you, my delay takes up to 10 secs in some cases.
Takes like 6 seconds to evaluate app.bundle.js

Also note the square at the top - left corner while HTML is loading:
![image](https://cloud.githubusercontent.com/assets/5492960/15984417/3c7b002a-2fca-11e6-9a16-6908257bbea9.png)

**Comment by ihadeed** [comment]
@ZiFFeL1992 I have that little button showing up only on this app. other apps show a blank page for a few seconds.

**Comment by ZiFFeL1992** [comment]
@ihadeed I also have it on my app, don't know the reason.

Here is a  graph on my app while loading:
![image](https://cloud.githubusercontent.com/assets/5492960/15984567/d9731100-2fd0-11e6-923f-95e31082630a.png)

**Comment by ihadeed** [comment]
I get the same thing, but it loads faster than your case. Maybe because my app is small.

![image](https://cloud.githubusercontent.com/assets/13794420/15984611/efbf4a72-2f9f-11e6-8314-909e4f16bac5.png)

**Comment by manucorporat** [comment]
@ihadeed @ZiFFeL1992  We are working in a new build chain featuring:
- Offline compiler for angular 2 templating. 
- Closure compiler to minify and optimize js
- Webpack2 Tree Shaking (eliminates unused exports)

There are a lot of room for improvements but ionic 2 is still beta, so it has not been optimized yet, please be patient!

**Comment by ihadeed** [comment]
thanks @manucorporat 

- Do you have an estimate on when those changes will be available?  (No rush! just curious :grin: )
- Are you waiting for Angular2 RC.2? or are you working side-by-side with the angular team?
- Is there any way I could help?

**Comment by jgw96** [comment]
Hey @ihadeed ! At this point we don't have a solid timeline on this but it is a high priority and work is being done on it currently. We are currently working side by side with the Angular team on this issue as they are doing alot of work on making Angular apps load extremely fast. Our short term plan is to implement the build chain that @manucorporat mentioned above. Longer term, we have discussed implementing an app shell architecture and implementing Angular Universal to make our first render lightning fast. I have done some experimenting with this and the results are pretty awesome. I would recommend talking to the Ionic CLI team about contributing for this issue as I'm sure they would love some help with this! Thanks for using Ionic and thanks for all the awesome work on Ionic Native!

**Comment by jlcarvalho** [comment]
@jgw96 can you share some experiments with us? I have a lot of interest on this and maybe I can help.

**Comment by ihadeed** [comment]
I would love to see some experiments too. :grin: 

.. and hey @jlcarvalho check these two repos out:
https://github.com/alexpods/angular2-universal-starter
https://github.com/angular/universal-starter
