### ISSUE TITLE
Toast is still on top of everything when opening an ActionSheet

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#6860]
#### Short description of the problem:
Toast is always on top of everything. Opening an ActionSheet while there is a toast visible doesn't cancel the toast or overlay it.

![toast-actionsheet](https://cloud.githubusercontent.com/assets/13794420/15982449/ad86aa00-2f55-11e6-8dae-2220b713eab1.gif)

**Steps to reproduce:**
1. Display toast
2. Open an action sheet before the toast hides

**Which Ionic Version?** 
Ionic 2 beta.8

---

IMO, Toast should be cancelled in case any of the following is opened: ActionSheet, Modal, Alert. This will bring a better overall user experience. If you think there are some cases where it wouldn't be useful to keep the Toast visible while any of the previously mentioned components are opened, then we can pass an option when creating a toast. Example:
```typescript
let toast = Toast.create({
  message: "I'm a happy toast, in a happy world",
  duration: 3000,
  autoHide: true // Default should be true, if user wants otherwise, set it to false
});
```

**Comment by mpaland** [comment]
Can't you just dismiss() the toast upon/before opening the action sheet?

**Comment by ihadeed** [comment]
Thanks @mpaland I wasn't aware of that function.
