### ISSUE TITLE
Enhancement: Placeholder text for ion-select component

### ISSUE THREAD

**Issue by vijquick** [driftyco/ionic#6862]
The current version **beta.8** of **ionic 2** doesnt allow to set **placeholder text** for **ion-select** . This would be a useful feature to have considering the real estate that we have in mobiles screens. Without this we have to add additional element either label or div to specify the placeholder text.

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be in the `beta 9` release. :smile:

**Comment by vijquick** [comment]
Well done @brandyscarney. Thank you.

**Comment by juarezpaf** [comment]
@brandyscarney it would be nice to have an option to have the default select behavior inside of `<ion-select>`, because the user needs to tap one more time in the "Ok" button to select the option.

**Comment by brandyscarney** [comment]
@juarezpaf I'm not sure I understand. Is there an issue open for this?

**Comment by juarezpaf** [comment]
@brandyscarney not yet! I'll open one this weekend. Thanks a lot.
