### ISSUE TITLE
ion-datetime words disappearing in Safari OS X with iOS theme

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6865]
#### Short description of the problem:

`ion-datetime` elements (months, days, years) disappear when touched on Safari OS X. It's not that bad but is just annoying during my development process.
![capture d ecran 2016-06-11 a 10 12 18](https://cloud.githubusercontent.com/assets/15067923/15985503/7e85f09a-2fbd-11e6-96de-2cc10a0742f8.png)
#### What behavior are you expecting?

The words not to disappear.

**Steps to reproduce:**
1. Open [Plunker](http://plnkr.co/edit/goWeCi4Nhn9b5HvkBgro?p=preview) in Safari
2. Drag the words inside `ion-datetime`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This might be related to `webkit-backface-visibility`. 

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

[http://plnkr.co/edit/goWeCi4Nhn9b5HvkBgro?p=preview](http://plnkr.co/edit/goWeCi4Nhn9b5HvkBgro?p=preview)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
@Bouzmine  should be fixed in RC3!
