### ISSUE TITLE
Pull to refresh triggers infinitescroll loop. V1.3.x

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#6866]
#### Short description of the problem:
When I do a pull to refresh on a list, not pull down enough to trigger a refresh, scroll up (still tapping) to the top back, it will trigger infinitescroll. 

#### What behavior are you expecting?
Infinitescroll must not be triggered

**Steps to reproduce:**
1. Create a list
2. Add pull to refresh and infinite scroll
3. Start pulling down then drag the pull down up to the top
4. Notice the infinitescroll triggered

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
