### ISSUE TITLE
Ionic Error: Platform ios already added. but when running resources, says no platform added

### ISSUE THREAD

**Issue by LydiaMontagnese** [driftyco/ionic#6868]
#### Short description of the problem:

When I run 'ionic platform add ios', I am getting this error: 
Error: Platform ios already added. 

But when running 'ionic resources', it says no platform added.

Here's the output:

Lydias-MBP:ionic-basic lydia$ ionic resources
No platforms have been added.
Please add a platform, for example: ionic platform add ios
Or provide a platform name, for example: ionic resources android

Lydias-MBP:ionic-basic lydia$ ionic platform add ios
 ✗ (node:51934) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Error: Platform ios already added.

Lydias-MBP:ionic-basic lydia$

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an issue with the Ionic CLI and not the framework I will be moving this issue to the correct repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1068

**Comment by cyrinearbi** [comment]
Hi,I have the same problem !!!

$ sudo cordova platform add ios --save
Using cordova-fetch for cordova-ios@^4.4.0
# Error: Platform ios already added.

**Comment by SanjayYadav90** [comment]
[Here](https://github.com/ionic-team/ionic-cli/issues/1068) is how I solved my issue.
Hope it will help you too...
