### ISSUE TITLE
Color Picker component

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6869]
It would be nice to have an overlay component accessible from a form input to choose a color.  

**Given** a form input for choosing color, **when** I drag my finger around and find a color that I like and click "OK", **then** I receive the hex code for the color.

**Comment by jgw96** [comment]
Just thinking but we could maybe use the html5 color picker input under the hood for this, but style it and present it like an alert or the date time component. Not sure how well the html5 color picker input can be styled though.

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!
