### ISSUE TITLE
v2 docs: Old style config still documented (not beta 8 bootstrap version)

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#6871]
#### Short description of the problem:

In the "phone" mockup on the right hand side of http://ionicframework.com/docs/v2/api/config/Config/ the documentation for config is not right, it is still on how it was upto beta 7, not how the config moved to bootstrap, from beta 8 onwards

#### What behavior are you expecting?

A post-beta-8 version of the config style to be shown

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the docs and not the framework i will be moving this issue to the ionic-site repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#647
