### ISSUE TITLE
Use components as single js file without bundling into single app.bundle.js

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6873]
This is reg the closed issue #6776

Mine is not the complete hybrid application. It's combination of both hybrid and native.
When every time I open an activity with webview, It takes more time for initial loading. 
Is there a way to stop bundling the js resources while build process. I assume it can reduce some amount of initial loading time.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. As i said on #6776 we are currently working a new build chain that will make Ionic 2 apps start up faster and overall be much snappier. This should solve the issue stated here. I have reopened #6776 and will update it when i have more on our progress with this. Thanks for using Ionic!

**Comment by dheran** [comment]
@jgw96  thank you

**Comment by evgeniynet** [comment]
Yea I waiting too, but something can be made now.
Our site is completely on Ionic2 beta.8 
http://m.sherpadesk.com/

Also my components splitted to my.js file with templates

I have hybrid app too and did some optimizations and got **417ms loading time**.
Look at report https://tools.pingdom.com/#!/DW6Td/http://m.sherpadesk.com/17
Also Site size decreased **600% (3Mb -> 500 Kb)**
User interaction response speed improved **2000% (2 seconds -> 100ms)**

Good recommendations: http://blog.angular-university.io/how-to-run-angular-2-in-production-today/36

I'll post all my gulp settings and link to appstore here: http://www.sherpadesk.com/blog/
