### ISSUE TITLE
issue(input): Input has focus issue on Android

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#6876]
#### Short description of the problem:
On Android in beta 8:

- Selecting an input field now places an underline. Where did this come from?
- I have styled my input fields so that they are rounded, but I do not see anyway to fix the focus underline as it is off center?
- When the input field is marked as invalid, there is a conflict with the red underline and the blue focus line. Note that the red invalid line fills the entire input field and looks correct as opposed to the blue focus line.

![animation](https://cloud.githubusercontent.com/assets/2852839/16001546/dff298ec-3152-11e6-8fc8-b16357175bbf.gif)

How do you disable the line selection (default blue on focus) on inputs on Android? How do you specify the colors for the various states (invalid, focus, valid, etc.)?

**Which Ionic Version?** 2.x

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v5.10.1

**Comment by dylanvdmerwe** [comment]
Struggling to get the styling to apply properly in the plunkr: http://plnkr.co/edit/XmVuhKbBx3zREIydm47c?p=preview

**Comment by jgw96** [comment]
Hey! Would you mind trying to reproduce with [this](http://plnkr.co/edit/CimieM5bkTOuCAnDPlqk?p=preview) plunker? Ive tried multiple types of inputs etc etc and cant seem to reproduce.

**Comment by brandyscarney** [comment]
It's related to this issue: #5052

The highlighting can be turned off via the following Sass variables:

```
$text-input-md-show-success-highlight:      false;
$text-input-md-show-error-highlight:        false;
```

and to change the colors:

```
// Input highlight - normal
$text-input-md-highlight-color:             color($colors-md, primary);

// Input highlight - valid
$text-input-md-hightlight-color-valid:      color($colors-md, secondary);

// Input highlight - invalid
$text-input-md-hightlight-color-invalid:    color($colors-md, danger);
```

The issue is a WIP so please add any feedback on that issue.Thanks!

**Comment by dylanvdmerwe** [comment]
Hi @brandyscarney. This is a specific issue related to the sizing of the highlight lines. Reproduceable code attached.
[test.zip](https://github.com/driftyco/ionic/files/315712/test.zip)

**Comment by CodeWithClass** [comment]
How can I remove the lines completely, there's always a gray line when everything is set to false
