### ISSUE TITLE
VirtualItem does not seem to work with custom components

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic#6881]
#### Short description of the problem:

I am trying to use VirtualScroll but instead of directly using ion-item as the virtual item, I am using a custom component that encapsulates ion-item.
#### What behavior are you expecting?

Render the component normally as when using ngFor.

**Steps to reproduce:**
1. Create a custom component that its' template has a complete ion-item
2. Use that component inside a virtualScroll

```
  <ion-list [virtualScroll]="items">
  <list-item *virtualItem="let item" [item]="item"></list-item>
  <!-- <ion-item *virtualItem="let item" item="item">{{item}}</ion-item> -->
  </ion-list>
```

**Which Ionic Version?** 1.x or 2.x
Ionic2-beta8
#### Plunker that shows an example of your issue

http://plnkr.co/edit/ONkXIK0ByvBwWeAfgMcD?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by wli** [comment]
I believe this is a dupe/related to https://github.com/driftyco/ionic/issues/6877

**Comment by masimakopoulos** [comment]
I think it is the opposite of #6877 I am using a custom component inside VirtualScroll, not VirtualScroll inside a custom component

**Comment by lordgreg** [comment]
+1

exactly the same behavior here. Having VirtualScroll with custom component leads to messed up view where each component overlays every other.

The VirtualScroll is as badly implemented as it was in Ionic1 and needs to be refactored or updated to allow that kind of code.

**Comment by Screeze** [comment]
+1
Same issue here, my custom list items all get assigned:
`transform: translate3d(375px, 0px, 0px);`
although the items itself have some height set.
Is there any workaround?

**Comment by Screeze** [comment]
Seems like I'm able to use this as workaround (wrapping custom item in div):
```
<div *virtualItem="let item">
    <my-list-item [modeldata]="item"></my-list-item>
</div>
```
