### ISSUE TITLE
iOS build optimization

### ISSUE THREAD

**Issue by turbulence** [driftyco/ionic#6882]
Hi,

I'm using Ionic 1 since a while and start looking at Ionic 2.

When generating an iOS build, I was looking at the code and find that app.md.css and app.wp.css are part of the www/build/css folder.

I was wondering if there is any way to only get files related to iOS so that my ipa is as small as possible and to avoid having unnessary files.

Thanks

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You could remove the app.md.css and app.wp.css files, but i would not recommend it as it may cause other issues. We are working on a new build chain for Ionic 2 that will include Angular offline template compilation and aggressive minification that will make ionic 2 apps much smaller and even faster than they are now. I do not have a specific timeline on this yet, but we are actively working on it (: . I will be closing this issue for now as it is something we are already working on, but feel free to continue the discussion and thanks for using Ionic!
