### ISSUE TITLE
docs: Broken push link in v2 docs

### ISSUE THREAD

**Issue by steebchen** [driftyco/ionic#6883]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When searching "push" with the bar on top in the v2 docs (http://ionicframework.com/docs/v2/) and selecting "Push" under "Native" there is a broken link where its href is `http://ionicframework.com/docs/v2/native/Push/`. The fix is easy, just use lowercase, e.g. edit "Push" to "push": `http://ionicframework.com/docs/v2/native/push/`</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the docs and not the framework i will be moving this issue to the ionic-site repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1072
