### ISSUE TITLE
Range Slider doesn't work inside modal view

### ISSUE THREAD

**Issue by ninoguba** [driftyco/ionic#6885]
#### Short description of the problem:

Range Slider is not draggable when inside a modal view running on the phone.
#### What behavior are you expecting?

Range Slider should be draggable to select desired value.

**Steps to reproduce:**
1. Add a range slider component inside a modal view
2. Launch modal view in your controller

```
<ion-modal-view>
    <div class="item range">
        <i class="icon ion-volume-low"></i>
        <input type="range" name="volume">
        <i class="icon ion-volume-high"></i>
    </div>
</ion-modal-view>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

When ran on Chrome browser, the range slider is at least tappable allowing to change the value but dragging the slider is still not working.  The following message is appearing in my console the moment I tap or try to drag the slider:

> Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

**Which Ionic Version?** 1.2.x up to 1.3.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by ninoguba** [comment]
I don't have a plunker but you can view this with Ionic View using this ID: fcf03f24

All I did here was just start with the blank starter project and modified the following files:

**index.html** (replace body with this)

```
<body ng-app="starter" ng-controller="RangeCtrl">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content>

        <div class="item item-text-wrap">
          <p>This range slider works as expected.</p>

          <div class="range">
            <i class="icon ion-volume-low"></i>
            <input type="range" name="volume">
            <i class="icon ion-volume-high"></i>
          </div>
        </div>

        <div class="item item-text-wrap">
          <p>Launch a modal with the same range slider.</p>

          <button class="button button-block button-outline button-positive" ng-click="openModal()">
            Open Modal View
          </button>
        </div>

      </ion-content>
    </ion-pane>
  </body>

```

**app.js** (add this code)

```
.controller('RangeCtrl', function($scope, $ionicModal) {
  $scope.data = {};

  $scope.openModal = function() {
    $ionicModal.fromTemplateUrl('modal-range.html', {
      scope: $scope,
      animation: 'slide-in-up'
    }).then(function(modal) {
      $scope.modal = modal;
      $scope.modal.show();
    });
  };

  $scope.closeModal = function() {
    $scope.modal.remove();
  };

  // Cleanup the modal when we're done with it!
  $scope.$on('$destroy', function() {
    $scope.modal.remove();
  });

  // Execute action on hide modal
  $scope.$on('modal.hidden', function() {
    // Execute action
  });

  // Execute action on remove modal
  $scope.$on('modal.removed', function() {
    // Execute action
  });
})
```

**modal-range.html** (create this file)

```
<ion-modal-view>

	<div class="item item-text-wrap" style="height:100%">
    	<p>This range slider doesnt work as expected.</p>

		<div class="range">
			<i class="icon ion-volume-low"></i>
			<input type="range" name="volume">
			<i class="icon ion-volume-high"></i>
		</div>

		<button class="button button-block button-outline button-positive" ng-click="closeModal()">
            Close Modal View
        </button>
	</div>

</ion-modal-view>
```

**Comment by basdp** [comment]
This is the malefactor:
https://github.com/driftyco/ionic/blob/1.x/js/angular/service/modal.js#L194

I fixed it temporarily by changing the code to:
```javascript
var isInScroll = ionic.DomUtil.getParentOrSelfWithClass(e.target, 'scroll');
if (isInScroll !== null && !isInScroll) {
    e.preventDefault();
}
```

**Comment by ninoguba** [comment]
Thanks @basdp I'll give this a try.

**Comment by danmatthews** [comment]
+1 for this - the only way to get it working for me seems to be to downgrade to 1.2.0 😢

**Comment by ninoguba** [comment]
As a workaround you can use @basdp's code above. I verified it resolves the issue with sliders on modals.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#121
