### ISSUE TITLE
Revisit bezier-curves values for transitions

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6887]
Sometimes it feels and looks like a transition is done before it really is.  This is due to the use of bezier curves for transitions.  Often times, these transitions are very quick then slow down a significant amount at the end, creating the illusion that the transition is complete when it's not.  Perhaps we could revisit the values used and see if we could come up with something better.

This can lead to frustration from an end user who is clicking the screen thinking the transition is complete, but the click is blocked because the app is disabled.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#215

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#216
