### ISSUE TITLE
IonicBootstrap Method does not accept a componente without tempate or templateUrl

### ISSUE THREAD

**Issue by duffleit** [driftyco/ionic#6889]
The __IonicBootstrap Method__ does not accept a componente without _tempate_ or _templateUrl_. 

```
@Component({})
@Routes([
  { path: '/', component: Cmp1 },
  { path: '/2', component: Cmp2 }
])
class Demo {
  constructor(private location: Location) {}
}

ionicBootstrap(Demo);
```

_sample from: https://github.com/driftyco/ionic/blob/2.0/src/components/nav/test/routing/index.ts#L47_

throws following exception: 
`Uncaught Component 'Demo' must have either 'template' or 'templateUrl' set.`

I'm running on ionic 2.0.0-beta.8

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not support bootstrapping with a component that does not have a template. We prefer all bootstrapping to be done in your `app.ts` file, which should always have a template. Thanks for using Ionic!
