### ISSUE TITLE
Opening ion-select makes parent view going blank (scroll)

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#6890]
#### Short description of the problem:

When I click on an `ion-select` the view goes blank for half a second, making up for an impression of the app shaking. This only happens when there's is scrolling and I was only able to reproduce it on iOS
[Video](http://sendvid.com/0xfzn5sj)
#### What behavior are you expecting?

The view not to go blank.

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

I've setup a repo that reproduces the bug : [Here](https://github.com/Bouzmine/demo-select-flicker)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic.This has since been fixed.
