### ISSUE TITLE
Modal doesn't animate when closed too quickly

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6891]
Try the conference app. If you load the filter modal and then hit "done" too quickly, the modal closes without an animation. If you wait 500ms or so, the animation does run after hitting Done.

Note: this is on the wkwebview test from manu, possibly related?

[http://ionic-io-assets.s3.amazonaws.com/animate.mov](http://ionic-io-assets.s3.amazonaws.com/animate.mov)

**Comment by danbucholtz** [comment]
This issue should be resolved with a recent nightly build.  I wonder if that is still using beta 8?  There are some known app enabled issues there that we're resolving in beta 9.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue is fixed for beta.9, so as soon as we release and update the conference app it should be fixed.  @mlynch in the meantime you can test with `ionic-angular@nightly` as the latest nightly has the fix for this issue. (:

**Comment by danbucholtz** [comment]
Let's re-open this if we find it's still an issue, but this should be resolved due to the app enable/disable changes in beta 9.

Thanks,
Dan
