### ISSUE TITLE
Modal animation is too fast

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6892]
Compare our modal to a stock iOS modal. Notice the stock is slower and has more "weight"

Ours: http://ionic-io-assets.s3.amazonaws.com/animate.mov

Apple's: http://ionic-io-assets.s3.amazonaws.com/modalios.mov

**Comment by jgw96** [comment]
I would consider [this](https://github.com/driftyco/ionic/issues/6887) issue related.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#214
