### ISSUE TITLE
ionicView.leave and ionicView.enter events fire wrongly

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic#6893]
#### Short description of the problem:

I have these two events in my controller and they both fire wrongly. my ionicView.leave event fires when i enter the controller and my ionicView.enter event fires upon leaving the controller. Its so weird. Why is this happening? Also, it only gets called when it is $rootScope and not $scope

#### What behavior are you expecting?

I am expecting both events to fire correctly.
**Steps to reproduce:**
1. Go to ur controller, add an ionicView.leave and ionicView.enter event
2. Create a function to enter and leave the controller wt the view
3. Try with $scope and $rootScope

```
$rootScope.$on('$ionicView.leave', function() {
    console.log('on the way leaving')
  })

$rootScope.$on('$ionicView.beforeEnter', function() {
    console.log('on the way entering')
  })
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
