### ISSUE TITLE
Ionic2 Range debounce feature

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#6894]
#### Short description of the problem:
Enhancement Request: add configurable debounce to range slider

#### What behavior are you expecting?
Allow user to specify debounce=value in ms the same way that min & max values are specified for the range slider.

**Which Ionic Version?** 1.x or 2.x
2.0

**Comment by manucorporat** [comment]
I think debounce should be added to text input and textarea as well. It would be good to find a way to don't repeat too much code.

**Comment by adamdbradley** [comment]
While we're at it, let's make this a standard across all inputs.

**Comment by ghenry22** [comment]
awesome! Then I can pull out my range debounce code :)
