### ISSUE TITLE
Gesture like (swipe)... prevent vertical scroll

### ISSUE THREAD

**Issue by jeromeXoo** [driftyco/ionic#6897]
#### Short description of the problem:
The gestures (like swipe, swipeleft, swiperight, tap...)  are blocking the vertical scroll with the virtual scroll or ion-list.
Browser: OK (mouse wheel)
Android Device or emulator: KO: vertical scroll doesn't work, but swipe work

**Example with virtual scroll**:
```
<ion-list [virtualScroll]="arrayArticles" approxItemHeight="200px"
          approxHeaderHeight="0px" approxFooterHeight="0px">
    
    <ion-card  *virtualItem="let article;let idx = index" (click)="itemTapped($event, article)" 
              [virtualTrackBy]="id"
              (swipeleft)="articleSwipeLeft(article,$event, idx)" 
              (swiperight)="articleSwipeRight(article,$event, idx)"
              class="article-ion-card">
        
        <ArticleImage [article]="article"></ArticleImage>
		<div class="article-card-title" [innerHTML]="article.title"></div>
        <div class="article-card-subtitle" [innerHTML]="(article.publishedDate | amTimeAgo) + ' on ' + article.sourceTitle"></div>
        
    </ion-card>
</ion-list>
```
When I select the space between the "ion-card", the vertical scroll is working.

**Example with ion-list and ngFor**:
```
<ion-content class="has-header">
  <div padding style="text-align: center;">
    <p>Ionic 2 Test Gesture with ion-list, swipe an item</p>
    <p>With browser: OK. Android Device or emulator: KO: vertical scroll doesn't work</p>
    
    <ion-list>
      <ion-item *ngFor="let item of items" (swipe)="doSomething(item)">{{item.title}}</ion-item>
    </ion-list>
  </div>
</ion-content>
```

Ionic V2 (beta 9)

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.3.2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jeromeXoo** [comment]
Hi,

Ok for a plunker, but the problem is not present in the browser.
Browser: OK (mouse wheel)
Android Device or emulator: KO: vertical scroll doesn't work, but swipe work

Here is a plunker with a simple list. But I can reproduce the problem with the virtual scroll.
http://plnkr.co/edit/bjpePx?p=preview

If I run the test page in a device, scroll doesn't work.

I can provide more information if needed

**Comment by danbucholtz** [comment]
Hi @jeromeXoo,

This is an Angular issue.  I went ahead and created an issue for it.  We'll track it here too since it's important for Ionic.

https://github.com/angular/angular/issues/10541

Thanks,
Dan
