### ISSUE TITLE
Bug: "Logo" icons in tabs (tabIcons) are only displayed on Android.

### ISSUE THREAD

**Issue by CorneeSean** [driftyco/ionic#6899]
**Description**
I have a following markup for tabs in my app:

``` html
<ion-tabs>
  <ion-tab [root]="tab1Root" tabTitle="Tab 1" tabIcon="pulse"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="List" tabIcon="chatbubbles"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="Facebook" tabIcon="logo-facebook"></ion-tab>
</ion-tabs>
```

The problem is with **the last tab icon: logo-facebook.** 
The icon appears on android, but does not appear on iOS or Windows. I believe the problem is in classes added to the element, which are different depending on platform.

On Android, the css class is: ion-logo-facebook
On iOS, the css class is: ion-logo-facebook-outline, which does not exist in css files, since this icon does not have an "outlined" version.

This issue also applies to other "logo" icons - I have checked a few. 

**Which Ionic Version?** 2.0-beta8

** Ionic info output **:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v6.2.0

**Comment by CorneeSean** [comment]
A simple workaround is to add the missing class for the particular icon:

.ion-logo-facebook-outline:before {
    content: "\f236";
}

**Comment by brandyscarney** [comment]
Thanks for the issue! Confirmed this is an issue in `ios` and `wp` mode.

**Comment by brandyscarney** [comment]
This will be fixed in the `beta 10` release! Thanks again. :smile:
