### ISSUE TITLE
iOS10

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#6901]
- [x] Tabs get pushed out of the viewport by `ion-content-section` having it's height set to 100%
_This seems to be fixed in the latest ios10 build_

[ios10-tabs-pushed](https://cloud.githubusercontent.com/assets/2835826/16047578/9a18d864-321e-11e6-8b3a-c0983dbee121.PNG)

- [ ] View get a sub-title that animates the height of the navbar

[ios10 sub-title](https://cloud.githubusercontent.com/assets/2835826/16047629/d0ae2e06-321e-11e6-9d8d-14ce2c2d78e3.gif)

- [x] general weirdness with tabs

[ios10-tabs](https://cloud.githubusercontent.com/assets/2835826/16049206/d78d5bba-3224-11e6-81c3-7b705dfbc403.gif)

- [ ] CSP in safari has gotten much more strict. 

https://github.com/driftyco/ionic-cli/issues/1161

**Comment by mchonan1996** [comment]
Is there a workaround for the tabs not showing?

**Comment by mhartington** [comment]
These are here to document the issue.
We will be addressing as we get further along in the beta trials

**Comment by Manduro** [comment]
I have two other interesting bits to share, although I haven't been able to test iOS 10 out yet:

**1. WKWebView always zoomable** ([Source](https://github.com/Telerik-Verified-Plugins/WKWebView/issues/249#issuecomment-227115710))
On iOS 10, `WKWebView` no longer respects `user-scalable=no`. This means even Ionic apps using WKWebView will be zoomable.

This can probably be prevented in the beautiful WKWebView plugin @manucorporat is creating ;). A possible solution seems to be listed [here](http://stackoverflow.com/a/31943976).


**2. WKWebView Behavior with Keyboard Displays** ([Source](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html))
On iOS 10, `WKWebView` objects match Safari’s native behavior by updating their `window.innerHeight` property when the keyboard is shown, and do not call `resize` events.

This might require some adjustments on the keyboard functionality of Ionic, which will hopefully end up as an improvement over the current implementation. The description makes me think it will finally be possible to have the web view shrink with native performance.

**Comment by jgw96** [comment]
IOS 10 screenshots of components that dont work well with zoom:

Segments:
![img_0028](https://cloud.githubusercontent.com/assets/8823093/17187993/0af732e8-5401-11e6-8439-3fde33c1efc7.jpg)

Popover:
![img_0029](https://cloud.githubusercontent.com/assets/8823093/17188008/17f41592-5401-11e6-9197-66f604f0d3ef.jpg)

Datepicker:
![img_0030](https://cloud.githubusercontent.com/assets/8823093/17188015/1c765ce2-5401-11e6-9a52-f36eb95a7757.jpg)

Alert: 
![img_0031](https://cloud.githubusercontent.com/assets/8823093/17188088/5a5aa482-5401-11e6-846c-ea6e7cc769ee.jpg)

**Comment by ihuseynoff** [comment]
Virtual Scroll does not work properly. It does not show elements while long scroll until next touch. Example: https://youtu.be/OufHfK5pQIw

**Comment by jgw96** [comment]
Happy to report that according to our resident ios expert the zooming issue with wkwebview has been fixed in ios10 beta.4 💯  😀  🎆

**Comment by Bouzmine** [comment]
I found out the keyboard doesn't close properly after closing some components (alert). It also doesn't close when an Modal is closed after a keypress on "Go" button. (beta.4)

**Comment by jgw96** [comment]
related: https://github.com/driftyco/ionic/issues/7622

**Comment by jasonwaters** [comment]
Ideally this will be fixed prior to iOS 10 launch, as it is affecting an app I released in the app store.

**Comment by aemr3** [comment]
Any news on this?

**Comment by mhartington** [comment]
@aemr3 any news on what in particular? This issue is more of an umbrella issue with multiple topics, you're going to need to be specific 😁

**Comment by aemr3** [comment]
Tabs are not displayed on the latest ios 10 beta. I didn't encounter any other issue.

**Comment by mhartington** [comment]
What version of ionic-angular are you using? Tabs have been refactored to resolve this

**Comment by aemr3** [comment]
Just noticed that we are using ionic-angular 2.0.0-beta.8 on our project. Do you say that it is fixed now?

**Comment by mhartington** [comment]
That should be fixed. If not in beta9, then beta 10/11. Best to upgrade and check the change log for breaking changes

**Comment by aemr3** [comment]
Thanks you for pointing out this. We will try to upgrade.

**Comment by jrencz** [comment]
I'm reposting my issue #7887as @jgw96 asked me to do

*Short description of the problem:*

I recently updated my iPhone to iOS 10 beta 7 and I noticed that back view animation got a little bit different easing

*What behavior are you expecting?*

I'd expect for Ionic app to have easing similar to native on iOS 10

*Steps to reproduce:*
1. Prepare 2 devices: one with iOS 9 and one with iOS 10
2. Open any native app in both, compare back view animation easing. On 10 it's a bit more ease-out than on 9
3. Open Ionic app. Easing is the same (I checked on Ionic 1.x)

*Which Ionic Version? 1.x or 2.x*
1.x but I found no trace of different handling of iOS 10 in either version

**Comment by nerdmed** [comment]
@mhartington @jgw96  iOS 10 was released today and our app is blocked cause of the keyboard issue, the keyboard just doesnt close properly and appers everytime the users touches any button. Thats really a roadblocker. Is there any quickfix for this?

**Comment by mhartington** [comment]
@nerdmed can you provide a demo for this? I have not seen this before, so there could be something app specific.

**Comment by satish-nikam** [comment]
As ios10 is now released, can we include this in v2 beta-12?

**Comment by Wyzerus** [comment]
@mhartington @jgw96 - IOS10 Has keyboard behaviour changed in any of your apps? 
Keyboard no longer shows the <> and DONE option when navigating between inputs in a form.
Anyone else having this issue.
It appears in both my dev apps after ios10 update, auto spell options are seen but no form input navigation helpers.
Thanks for you time in advance...

**Comment by nerdmed** [comment]
@mhartington  thanks a lot for your reply. Building the reproduction let me find the specific edge case. Somehow this issue only appears if the DOM element (input) that actually started the keyboard is removed from the DOM, before the keyboard is closed. This did not happen on iOS 9.

I have build a small [https://github.com/nerdmed/cordova-keyboard-issue/](reproduction for this issue.)

I assume that this is still a keyboard plugin issue as this issue does not happen when running the application inside safari.

**Comment by Bouzmine** [comment]
@mhartington @jgw96 The RC is out, I know you are busy fixing some things that broke because of Rollup and the new buildchain, but could you add this to the RC1 milestone, I think this is a priority because the system has been released.

**Comment by mhartington** [comment]
Hey yall, sorry for the silence on this part. This issue was really just to track ios10 issues internally. 

As for the keyboard issue, @nerdmed can you please open an new issue instead.

**Comment by prasadyallapu** [comment]
Hey @mhartington currently we are adding a email plugin to our app.I am using following cordova plugin [https://github.com/katzer/cordova-plugin-email-composer.git].We are testing the app in ionic view ios ipad with (version 10.0.2).

**Problem:** To use email we wrote a click function to open email plugin,when clicking the button the ionic view is closing.

**Note:** 
- Removed and added cordova multiple times still same issue.
- Added (<meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *">) read safari had more restrictions in new update.
- Current ionic version 1.7.7

It will helpful if you suggest if I am missing any?

**Comment by mhartington** [comment]
@prasadyallapu Please open an NEW issue.
