### ISSUE TITLE
Pushing view after alert messes up nav and makes select unusable

### ISSUE THREAD

**Issue by pathartl** [driftyco/ionic#6902]
#### Short description of the problem:

If you push a view/page in the handler of an alert, the page will load. If a select is present on the new page and a user tries to choose an option and then hits OK or cancel the select will disappear, but the alert backdrop doesn't disappear and the user is brought to the previous page.

#### What behavior are you expecting?

A user hits a button to go to the next page from a list page, an alert displays prompting them they need to take additional steps (handled in the list page's controller). Clicking OK on the alert takes them to the "issue resolution" page where they are given a form to fill out. In the form the user can use a select to choose an option.

**Steps to reproduce:**
1. Trigger an alert in a view on click
2. For the OK button's handler, do a nav.push to another page/view
3. On the next page, insert a select

```
// On list page
let alert = Alert.create({
    title: "Issues Found",
    subTitle: "Issues were found that need to be resolved.",
    buttons: [{
        text: "Resolve",
        handler: () => {
            this.nav.push(ResolutionPage, {
                data: this.data
            });
        },
    }],
});

this.nav.present(alert);
```

ResolutionPage
```
<ion-label>Select Label</ion-label>
<ion-select [(ngModel)]="data.propery">
    <ion-option value="1" checked="true">Option 1</ion-option>
    <ion-option value="2">Option 2</ion-option>
</ion-select>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0.0@beta8

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.2.6

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Our navigation system in Ionic 2 is completely async, so you have to wait for other animations/transitions to complete before you can fire off another one. The proper way to push a page onto the stack from an alert would be to do this 

```
let alert = Alert.create({
  title: "issues found",
  subTitle: "Issues were found that need to be resolved.",
  buttons: [{
    text: "Resolve",
    handler: () => {
      alert.dismiss().then(() => {
        this.nav.push(ResolutionPage, {
          data: this.data
        })
      })
    }
  }]
})

this.nav.present(alert);
```
If you would like to read more about how our nav system works async you can check out [these](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises) docs. Thanks for using Ionic!

**Comment by pathartl** [comment]
That fixed it! Thanks for the quick reply!

**Comment by jgw96** [comment]
@pathartl no problem at all! 😃

**Comment by mkhoshnasib** [comment]
Hi. I have the same problem and this but in my case it didn't work.

```
showAlert() {
    const alert = this.alertCtrl.create({
      title: 'Wait...',
      subTitle: 'Working...',
      buttons: [
        {
          text: 'Details',
          handler: () => {
            alert.dismiss().then(() => {
              this.navCtrl.push(DetailsPage)
            })
          }
        }
      ]
    });
    alert.present();
  }
```

and with this code I have this error on detail click.

```
Runtime Error
Uncaught (in promise): invalid views to insert 
```

**Comment by NarendraGumma** [comment]
Yes i am also getting the same problem.
Runtime Error
Uncaught (in promise): removeView was not found
