### ISSUE TITLE
Floating label disables click event in iOS iPhone

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#6903]
#### Short description of the problem:

To understand this issue is better to explain it with code 

**home.html**
```
<button ion-item (click)="pickDefaultDate()">
  <ion-label floating primary>Default Date</ion-label>
  <ion-input type="text" [(ngModel)]="settings.defaultdatedisplay" readonly></ion-input>
</button>
```
**home.ts**
```
pickDefaultDate() {
  this.nav.push(PickPage);
}
```
I have the above button with a click event that calls a function called `pickDefaultDate()`. The `ion-input` is set with a `readonly` attribute. When I install the app on my iPhone 6 with iOS 9.3.2 and tap on the button, the click event doesn't fire, instead the floating label gets activated even when the input field is set to readonly. If I tap again, the click event fires and the function gets called.

#### What behavior are you expecting?

When I tap on the button on my iPhone I expect the click event `(click)="pickDefaultDate()"` to fire when the ion-input is set to readonly. The floating label should also be readonly/disabled

#### Behavior on the browser

When I test it on the browser (chrome) I get both events fired almost at the same time. I see the floating label get "activated" and the click event firing 

#### Behavior on ionic 1.x

I have similar functionality in an ionic 1.x app and the floating label DOES NOT disable the tap event in an `ion-item` with `ui-sref="app.pickdefaultdate"`

**Steps to reproduce:**
1. Clone the following repo: https://github.com/gigocabrera/ionic2_issue

**Which Ionic Version?** 2.x

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v5.10.1

**Comment by manucorporat** [comment]
@gigocabrera you should not use a button as an input. Of course the api does not preven you for doing that, but it is not a good idea. A button != input.

Just do this:
```html
    <ion-item>
      <ion-label floating>Readonly</ion-label>
      <ion-input [(ngModel)]="myParam" type="text" readonly (focus)="dosomething()"></ion-input>
    </ion-item>
```
