### ISSUE TITLE
Karma Code Coverage Reports

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6905]
I'd like to be able to get code coverage reports for karma tests.

I am imagining an API like this:

`gulp karma --coverage` in order to output the coverage reports.

**Give** some unit tests
**When** I execute them with the coverage argument
**Then** I can see the report detailing which lines of code are covered

Thanks,
Dan

**Comment by danbucholtz** [comment]
I am assigning to @jthoms1.  If he's too busy, this is something I can tackle in the coming weeks.  It is challenging to write automated tests without the code coverage report.

Thanks,
Dan

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#210
