### ISSUE TITLE
Set ion-datetetime min max values from function call as compared from a string value in the html?

### ISSUE THREAD

**Issue by aslamj** [driftyco/ionic#6906]
How do I dynamically set the min max datetime values (including date and time values). I'm hoping the ion-datetime to call in a function, which returns the acceptable time value as a string.

Can this be done in beta.8 or future versions?

**Comment by brandyscarney** [comment]
You can use property binding to bind the min/max to an expression. Something like this:

```
<ion-datetime [min]="myMinDate" [max]="myMaxDate"></ion-datetime>
```

See the Angular property binding documentation for more info: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding

Thanks!

**Comment by aslamj** [comment]
Thanks, can we also restrict the time or only date value?

**Comment by brandyscarney** [comment]
Right now only the date, but there is an open issue to include time: https://github.com/driftyco/ionic/issues/6850
