### ISSUE TITLE
Focusing between inputs causes Safari scroll bounce

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#6909]
See this video to see what I mean. Seems to happen only when going between input boxes:

http://ionic-io-assets.s3.amazonaws.com/scrollbounce.mov

**Comment by adamdbradley** [comment]
@jgw96 Can you test this on just the input examples? In most cases search bar wouldn't be in the middle of the page, so it doesn't come with all the scrolling guards that prevent weird scrolling like this. But this e2e test does have it in the middle.

**Comment by jgw96** [comment]
@adamdbradley sure can

**Comment by jgw96** [comment]
@adamdbradley after testing this on my Nexus 6 and Nexus 7 with just plain inputs i can confirm that there is no weird scrolling issues no matter where the inputs are on the page, or how many there are. My test app is just a plain blank starter with a few `ion-inputs` on it.

**Comment by tlaverdure** [comment]
I was able to reproduce this here on my iPhone: http://play.ionic.io/m/3384349612bb

**Comment by jgw96** [comment]
Hello @tlaverdure this issue is actually for Ionic 2. Would you mind making a new issue for this bug on ionic 1 please? Thanks for using Ionic!

**Comment by tlaverdure** [comment]
I haven't experienced this with ionic 2. I've seen some other weird input stuff though and have created an issue.

**Comment by jgw96** [comment]
Going to close this one for now as I cannot seem to reproduce on wkwebview with my Iphone 5 on the latest ios 10 beta, but will keep a lookout for it.
