### ISSUE TITLE
error when creating an ionic 2 projects

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#6910]
#### Short description of the problem:
When creating a project it says that start is undefined and there was error running npminstall. It written together without spaces so I think it was a typo on  your part. 

#### What behavior are you expecting?
to npm install everything when creating a project. 

**Steps to reproduce:**
1. ionic start  nameOfProject --v2 --ts

```
insert any relevant code between the above and below backticks
https://1drv.ms/i/s!Al0ly62YCZx3lsIZ-QMrGV1WVXpSFA
```

**Which Ionic Version?** 
2-beta 8

#### Plunker that shows an example of your issue

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the ionic-cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1076
