### ISSUE TITLE
ion-item-sliding doesn't have full width inside a VirtualScroll

### ISSUE THREAD

**Issue by wli** [driftyco/ionic#6911]
#### Short description of the problem:
ion-item-sliding doesn't take up full width inside a VirtualScroll

#### What behavior are you expecting?
The sliding item should take the full list width

![webm](https://cloud.githubusercontent.com/assets/649892/16062298/1902fa2e-3247-11e6-811e-8cdfb0513643.gif)

**Steps to reproduce:**
1. Use ion-item-sliding with VirtualScroll

```
    <ion-list [virtualScroll]="items">
      <ion-item-sliding *virtualItem="let item">
        <ion-item>
          {{ item }}
        </ion-item>
        <ion-item-options>
          <button primary>
            <ion-icon name="check"></ion-icon>
            Done
          </button>
        </ion-item-options>
      </ion-item-sliding>
    </ion-list>
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.8

#### Plunker that shows an example of your issue
http://plnkr.co/edit/oXf11zC0Aadb02podyCG?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.8.0
```

**Comment by mpaland** [comment]
This is related and reported in #6239

**Comment by wli** [comment]
@mpaland Thanks for pointing that out! Not sure how I missed that. I'll copy over the new plunkr on beta8 and close this ticket.
