### ISSUE TITLE
Virtual scroll: Sliding items are not closed

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#6913]
#### Short description of the problem:

![jun-15-2016 02-48-59](https://cloud.githubusercontent.com/assets/127379/16065156/4a5a857c-32a8-11e6-9833-80538e61982d.gif)

**Comment by jeromeXoo** [comment]
I have similar problems with ion-img in virtual scroll. The DOM item is reused, but the state does not seem to reset as expected.

For example,
page loaded: item5 with img5 (OK)
i scroll down to the list and scroll up
=> Item5 with img13 (KO)

With beta8

**Comment by manucorporat** [comment]
@jeromeXoo hi, next release includes several fixes around `ion-img` and virtual scroll, it should be better!

We are also working in support for WKWebview, it is going to drastically help.

**Comment by jeromeXoo** [comment]
Thank you for the information.

And to talk about what is working well, I'm trying to migrate an application from V1 to V2. And for now, it works very well for a beta, faster, better design, less code, and the virtual scroll an ideal solution to the performance problem.

Good work! (We talk too little of that!)

**Comment by manucorporat** [comment]
@jeromeXoo thanks for your kind words!
