### ISSUE TITLE
push notification failure

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic#6914]
Hey guys,
My app push notifications suddenly stopped working :(

the reply I get from Ionic is:
`"statusCode" : 201,
	"body" : {
		"data" : {
			"app_id" : "486aaf62",
			"state" : "enqueued",
			"status" : "open",
			"uuid" : "49d0f418-4e6d-4ab0-948b-b1b135e09d67",
			"created" : "2016-06-15T03:00:14.154299+00:00",
			"config" : {
				"notification" : {
					"android" : {
						"data" : {
							"notId" : 100,
							"title" : "New Current Score",
							"message" : "Your bid was outbidden and therfore refunded.<br>
							Your updated current score is: 2023958."
						}
					},
					"ios" : {
						"title" : "New Current Score",
						"message" : "Your bid was outbidden and therfore refunded.<br>
						Your updated current score is: 2023958."
					},
					"message" : "Your bid was outbidden and therfore refunded.<br>Your updated current score is: 2023958."
				},
				"profile" : "winnerz",
				"tokens" : ["eFmTWZeZCWk:APA91bFbJ4uS6lHytmjEUCaECMMUZQf3JoMEAORq1hUWRjYlDHh_NfdCGJasd86KAUHKEMUoCwf1yoFPSKU3fkPC_EGfFgfSPoEWumn1qj5fS8nTbM0J6MEO3-
					C-bza8Pa6V8U2LYNDe"]
			}
		},
		"meta" : {
			"version" : "2.0.0-beta.0",
			"request_id" : "93f29df0-a2c9-44d6-995c-70f9015c40e1",
			"status" : 201
		}
	},`

Trying to send push from the ionic dashboard also gives an error:
"unable to save push, please contact support"

Is it a general issue or something specific for my app??

Thanks

**Comment by henggana** [comment]
Hi, @asafco4. I had same errors. Is it working for you now?

**Comment by asafco4** [comment]
Yes,  it's working for me.
Verify that you didn't unregistered the token

On Dec 23, 2016 03:27, "Segi Henggana" <notifications@github.com> wrote:

Hi, @asafco4 <https://github.com/asafco4>. I had same errors. Is it working
for you now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/driftyco/ionic/issues/6914#issuecomment-268962373>, or mute
the thread
