### ISSUE TITLE
ionic 2 routing showing blank page

### ISSUE THREAD

**Issue by MOHAMMADArsalan** [driftyco/ionic#6915]
I am using ionic 2@beta8 routing but its not working.

I am using same example as on githib page but its showing blank page.

https://github.com/driftyco/ionic/blob/2.0/src/components/nav/test/routing/index.ts

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
