### ISSUE TITLE
Error TS2348: Value of type 'typeof App' is not callable

### ISSUE THREAD

**Issue by shaikhspear16** [driftyco/ionic#6917]
Ionic 2 new project error.

I am creating a new project with Ionic 2 and Typescript on Windows 10 pc.

with the following command:

ionic start MyIonic2Project tutorial --v2 --ts

I get the following error when performing ionic serve

TypeScript error: app/app.ts(8,2): Error TS2348: Value of type 'typeof App' is not callable. Did you mean to include 'new'?

Shows a blank screen on ionic serve and android deployment.

In chrome console I get the following error -

app.js:29 Uncaught TypeError: Cannot read property 'backButton' of undefined

**Comment by jgw96** [comment]
Hello @shaikhspear16 would you mind posting the contents of your `app.ts` file here please? Thanks for using Ionic!

**Comment by iignatov** [comment]
> ```
TypeScript error: app/app.ts(8,2): Error TS2348: Value of type 'typeof App' is not callable. Did you mean to include 'new'?
```

@shaikhspear16 This error is most probably caused by incorrect update to `beta.8`.

There were many breaking changes including the following:

- The `@App` decorator was replaced with `@Component`.
- The `IonicApp` class was renamed to `App`.

I would recommend you to check out the detailed [steps to update to `beta.8`](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#steps-to-upgrade-to-beta-8).

**Comment by jgw96** [comment]
Hey @iignatov, I would be interested in seeing his app.ts that was generated when he did Ionic start. It should already be updated to beta. 8 .

**Comment by iignatov** [comment]
@jgw96 Ah, ok. I guess so - here's [the original issue](https://github.com/Microsoft/TypeScript/issues/9023) and it's from _Jun 8, 2016, 1:04 GMT_ which is before [the following commit](https://github.com/driftyco/ionic2-starter-tutorial/commit/bac54ee7d34e50f35bd01c6b1913213fd14ddf1c) from _Jun 9, 2016, 5:56 GMT_. So it should have been generated before the update.

**Comment by jgw96** [comment]
Ahh ok, thanks @iignatov ! So @shaikhspear16 if you could just run `ionic start` again it should now generate the correct starter project. Thanks for using Ionic! If you still have the same issue feel free to comment and ill happily reopen this issue. Thanks everyone!

**Comment by shaikhspear16** [comment]
Thank You for your support and replys. I created a new ionic 2 project and am able to run it all well now.

The app.ts file for which I received the error is as follows for your reference:
```

import {ViewChild} from '@angular/core';
import {App, Platform, MenuController, Nav} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {HelloIonicPage} from './pages/hello-ionic/hello-ionic';
import {ListPage} from './pages/list/list';


@App({
  templateUrl: 'build/app.html',
  config: {} // http://ionicframework.com/docs/v2/api/config/Config/
})
class MyApp {
  @ViewChild(Nav) nav: Nav;

  // make HelloIonicPage the root (or first) page
  rootPage: any = HelloIonicPage;
  pages: Array<{title: string, component: any}>;

  constructor(
    private platform: Platform,
    private menu: MenuController
  ) {
    this.initializeApp();

    // set our app's pages
    this.pages = [
      { title: 'Hello Ionic', component: HelloIonicPage },
      { title: 'My First List', component: ListPage }
    ];
  }

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }

  openPage(page) {
    // close the menu when clicking a link from the menu
    this.menu.close();
    // navigate to the new page if it is not the current page
    this.nav.setRoot(page.component);
  }
}

```

Thanks for the fix.
