### ISSUE TITLE
Ionic v2 - Feature Request - Autocomplete Input

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#6921]
#### Short description of the problem:

Hello, Is it possible down the line to have an input with an autocomplete feature, where the input is bound to some sort of array and as you type, the component would filters / suggests results to you from the array that it's bound to.

Similar to this one from the material team.
https://material.angularjs.org/latest/demo/autocomplete

**Which Ionic Version?** 2.x

Thank you.

**Comment by royipressburger** [comment]
+1

**Comment by windwp** [comment]
+1

**Comment by Dan890** [comment]
+1

**Comment by Nodonisko** [comment]
+1

**Comment by tebeshir** [comment]
+1

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by ne6toto** [comment]
+1

**Comment by Boomx** [comment]
+1

**Comment by faraazc** [comment]
+1

**Comment by marcoskichel** [comment]
+1

**Comment by shyamal890** [comment]
+1 Now it's time to include this feature isn't it?! For any extensive app this would be a much needed feature. Wonder if @jgw96 @danbucholtz has any timeline on this?

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#45
