### ISSUE TITLE
relative template and style urls in ionic2

### ISSUE THREAD

**Issue by michaelknoch** [driftyco/ionic#6922]
is there a possibility to use relative template and style urls for ionic2 components when using browserify bundle?

I am running an angular2 web app using CommonJS and module.id in my components. The plan is to reuse these ng2 components in my ionic application, but i was not able to fix the relative/absolute path problem for now.

Anny suggestions?

**Comment by BenjaminDieter** [comment]
Ionic uses WebPack, which allows us to use `require()` or `import`.

**Require:** _(did not work for me because of missing typings which I didn't want to include)_ 
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: require('./header.component.html'),
  styles: [require('./header.component.css')]
})
export class HeaderComponent implements OnInit {
}
```


**Import:**
```typescript
import { Component } from '@angular/core';

import { Component }  from '@angular/core';
import headerTemplate from './header.component.html';
import headerStyle    from './header.component.css';

@Component({
  selector : 'my-app',
  template : headerTemplate,
  styles   : [headerStyle]
})
export class HeaderComponent implements OnInit {
}
```

**Source:** [Component-Relative Paths in Angular 2](http://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html) on ThoughtRam. Thomas Burleson describes how to achieve the ability to use relative paths while using WebPack there.

**Comment by jgw96** [comment]
Hello @BenjaminDieter we actually use browserify for Ionic 2 (we used to use Webpack). @michaelknoch i will speak with some of our build team and see if they have an answer for this question. Thanks for using Ionic!

**Comment by michaelknoch** [comment]
I made some experience with https://github.com/ludohenin/gulp-inline-ng2-template. Maybe rendering referenced templateurl and style files inline is a solution @jgw96

**Comment by natevecc** [comment]
Is there a way this could be handled by the @Component's moduleId property instead of inlining the html/css? https://angular.io/docs/ts/latest/api/core/index/ComponentMetadata-class.html#!#moduleId-anchor

**Comment by 441N143G** [comment]
any news about relative path?

**Comment by jgw96** [comment]
Hello all, just a heads up that were changing up our build chain to support minification, tree shaking and offline template compilation, so all this will be changing relatively soon. Once that is done I will be revisiting this issue

**Comment by vong-xiv** [comment]
@jgw96 this is a pain that need to be addressed

**Comment by mirkonasato** [comment]
Following. Currently, code generated by `ionic start` has e.g.

    @Component({
      templateUrl: 'build/pages/home/home.html'
    })

and it's not immediately clear 1. where that `build` folder comes from; and 2. why it only references `home.html` and not `home.scss`. Too much magic going on there.

**Comment by 441N143G** [comment]
yeap, we realy need normal angular2-style with relative paths 4 this.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1196

**Comment by jgw96** [comment]
Hello all! I have decided to move this issue to the ionic-cli repo as it is more of a cli/build related issue than a framework issue. Thanks for using Ionic!
