### ISSUE TITLE
bug: No/wrong modal closing animation from nested page

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#6924]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>See this example:
http://plnkr.co/edit/kBxwyE?p=preview

What I've built:
1) Modal opens with Page 1
2) From modal's page 1 you navigate to modal's page 2
3) From That second modal page I try to close the modal again (Either with popToRoot() or ViewController.dismiss() )
=> In both cases there is NO animation (Chrome) or the wrong animation (Safari).

Expected:
The modal should close as it always does with the "modal-slide-out" animation.</span>

<span is-issue-template></span>

**Comment by flavordaaave** [comment]
I tried to configure the leavingOpts on the modal with:
```
    let modal = this.nav.getByIndex(1);
    console.log(modal);
    modal.setLeavingOpts({
      animation: "modal-slide-out",
      direction: "back",
      ev: undefined,
      keyboardClose: false
    });

    modal.dismiss();
```

But this throws an error:
```
browser_adapter.js:77 TypeError: Cannot read property 'getBoundingClientRect' of null
    at new ModalSlideOut (modal.js:237)
```

**Comment by flavordaaave** [comment]
I somehow solved this by creating a "wrapper" component with a new navigation stack:

```
...
  openModal() {
    let modal = Modal.create(ModalNavigation);
    // Promise that is resolved when Modal is dismissed
    this.nav.present(modal); 
  }
}

// Just a helper Wrapper component to create a new navigation stack for the modal
@Component({
  template: `<ion-nav [root]="root"></ion-nav>`
})
class ModalNavigation {
  root = ModalPage1;
}
```

and then I can just use this function in every modal page to close the modal:
```
closeModal() {
  // Get the Modal which is (hopefully) in the rootNav at index 1
  let modal = this.nav.rootNav.getByIndex(1);
  // Dismiss the Modal
  modal();
}
```

Example: http://run.plnkr.co/plunks/sb1PBa/

So if the ionic team thinks that this should be the intended way to do something like that, I'm okay with it and this issue can be closed.

**Comment by jgw96** [comment]
Hello! Would you mind testing this issue with the latest nightly please? To install Ionic 2 nightly you can simply run `npm install ionic-angular@nightly` thanks!

**Comment by flavordaaave** [comment]
@jgw96 Should I test my "workaround"/solution with the latest nightly or the attempts that I mentioned in my original post?

**Comment by jgw96** [comment]
Hello @flavordaaave ! If you could test with the latest nightly using `this.viewController.dismiss()` to dismiss the modal, as shown in the docs [here](http://ionicframework.com/docs/v2/components/#modals), that would be great (:

**Comment by flavordaaave** [comment]
@jgw96 The issue is NOT about dismissing a "normal" modal but dismissing the modal from a nested page inside a modal (see my original issue: http://run.plnkr.co/plunks/kBxwyE/) so just calling `this.viewController.dismiss()` on the nested page will not close the modal but just navigate back to the Modal's first page.
I created a new plunk using ionic2@nightly and added the simple `viewController.dismiss()`:
http://run.plnkr.co/plunks/izRYHQ/

(As expected this 3rd button just navigates back to the first page...)

**Comment by jgw96** [comment]
Hello @flavordaaave , are you wanting the modal that you open the second page from to still be open after you close the second page? Or do you want to open the modal, push the second page onto the stack, user interacts with second page, user closes second page which then navigates back to the first page.

**Comment by flavordaaave** [comment]
@jgw96 I wanted:
1) User opens modal
2) User navigates to second page INSIDE that modal
3) User can CLOSE the modal from the second page

As mentioned I already achieved this my creating a new navigation stack that is exclusively used inside the modal. SO you can see my plunk here to get an idea of what I wanted to achieve:
http://run.plnkr.co/plunks/sb1PBa/

I'm just not sure wether this is something that should be covered differently within ionic ;)

**Comment by jgw96** [comment]
@flavordaaave It looks like my teammate is working on this, so i will discuss this with him and see what he has in mind. Thanks!

**Comment by danbucholtz** [comment]
The best bet at this time is going to be passing the `ViewController` from the Nav page to the child pages either via a service or via NavParams.

```

constructor(private viewController:ViewController){
}

someFunction(){
   navController.push(MyFirstOrSecondPageInModal, this.viewController);
}
```

**Comment by flavordaaave** [comment]
@danbucholtz This is not working either (see: http://run.plnkr.co/plunks/FuN9F8/ => 3rd button on second page)
There I also get the error:
```
Cannot read property 'getBoundingClientRect' of null
```

So far the only way to achieve the desired behavior is to create a new NavStack for the Modal itself:
http://run.plnkr.co/plunks/sb1PBa/

**Comment by danbucholtz** [comment]
Hi @flavordaaave,

Can you explain what you're trying to do in detail?  I am not sure I understand.  Typically if you want to navigate pages within the modal, you'll want to create a new `ion-nav`.

This code in our end to end tests should show you approximately how to do that.

https://github.com/driftyco/ionic/blob/2.0/src/components/modal/test/basic/index.ts#L44

I can help further once I better understand the use case.

Thanks,
Dan

**Comment by flavordaaave** [comment]
@danbucholtz See my comment here: https://github.com/driftyco/ionic/issues/6924#issuecomment-226516952 that is what I wanted to achieve. In this comment I've also added another plunkr (https://plnkr.co/edit/sb1PBa?p=preview) where I already present a component with an `ion-nav`. 

As mentioned earlier I was just not sure wether this is the correct way because closing the modal from the second page inside the modal seemed quite "ugly":

```
  closeModal() {
    // Get the Modal which is (hopefully) in the rootNav at index 1
    let modal = this.nav.rootNav.getByIndex(1);
    // Dismiss the Modal
    modal.dismiss();
  }
```

But thanks to your end to end test example you showed me that I could just close the modal using:
```
this.nav.rootNav.pop();
```

So this looks quite nice and clean ;)

**Comment by danbucholtz** [comment]
w00t, Glad to help!

Thanks,
Dan

**Comment by flavordaaave** [comment]
@danbucholtz Unfortunately after upgrading to beta-11 `this.nav.rootNav.pop();` does not work anymore...

Is there a recommended solution to dismiss the modal from a second (or third) page that has been pushed inside the modal?

**Comment by biesbjerg** [comment]
If you wrap modal content in it's own `ion-nav`, you can dismiss modals using:

```ts
public onClose(): void {
	// Get modal page's NavController
	let navController: NavController = this._navController;
	// Get modal page's parent NavController (if it has its own navigation stack)
	if (navController.parent) {
		navController = navController.parent;
	}
	navController.first().dismiss();
}
```

Is this the desired / best way to handle this scenario?
