### ISSUE TITLE
ionic2 bug(tabs) - tabs show toolbars out of order

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6926]
#### Short description of the problem:

If I have a some toolbars _before_ my navbar on a tab page, then the order is ignored and the navbar is placed above my toolbars.
#### What behavior are you expecting?

I expect the order of navbars/toolbars to be retained. A full example is shown in the plunker provided below. This bug is seen on tab page 1. Tab page 2 shows a different bug.

**Which Ionic Version?** 2.x
#### Plunker that shows an example of your issue

https://plnkr.co/edit/XPoPzFsm03x8lvPrHMlH?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Currently we dont support having anything but the navbar being the top element, but this may change in the near future. We are gonna have to discuss this on our end and i will update this issue when we have come to a conclusion. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue for now as this is not something we plan to implement currently.
