### ISSUE TITLE
ionic2 bug(tabs) - when navigating to a tabs page, the back button does not show

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6929]
#### Short description of the problem:
If I navigate to a tabs page that is not the initial root page, the back button is not displayed.

#### What behavior are you expecting?
I expect the back button to display on a tabs page with a parent nav.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
The `enableBack()` function in view-controller.ts is called via certain `Transition`s to determine whether the back button should display or not. `enableBack()` then calls `getPrevious()` in nav-controller.ts (line 1693). Because the tabs page is the new root, `getPrevious()` returns null, which indicates that there is no previous view and thus the back button should be hidden.

I propose that `getPrevious()` should do an additional check to see, if there is no previous view in the current, whether or not there is a parent nav. If there is, then it should display the back button.

I'd be happy to work on this issue but wanted to make sure that this is a good solution.

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/XPoPzFsm03x8lvPrHMlH?p=preview

If you navigate to the tabs page, notice there is no back button.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Awesome debugging! We are currently tracking this issue in https://github.com/driftyco/ionic/issues/5351 so i will be closing this one as a duplicate. Thanks for using Ionic!
