### ISSUE TITLE
ion-backdrop causing slow performance on side-menu (W10M)

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic#6931]
I've been trying to improve Windows 10 Mobile performance on Ionic and this is one of the issues I found.

#### Short description of the problem:
When `ion-backdrop` is present, the side menu opens and closes very slowly and laggy. It also makes the side menu buggy (flashing on the right-side of the screen when closing and opening). 

#### What behavior are you expecting?
Fluid animations on when opening and closing the side-menu.

**Steps to reproduce:**
1. Install the conference app on a Windows 10 Device (not desktop).
2. Play around with side-menu

The current work-around is to remove the backdrop for WP platform. 
```
ion-backdrop{
    display: none !important;
}
```

**Other information:** 
I am currently running on Lumia 950 with latest production build. 
 

**Which Ionic Version?** 
2.x

**Ionic Info**
```
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
Node Version: v5.10.1
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We will be doing some testing with our own windows 10 devices and i will get back to you with the details once that is done. Thanks for using Ionic!

**Comment by Artfloriani** [comment]
Great! I'm having a few other issues with Windows 10 Mobile but I believe some are things from the Edge engine. Curious about your results :+1:

**Comment by jgw96** [comment]
Hello all! This should be fixed with the latest nightly and beta.11 once it comes out. Manu was able to drastically improve the performance of the sidemenu, so it should be much faster in windows 10 now. Thanks for using Ionic!
