### ISSUE TITLE
Ionic2 : ion-input Problem with formControlName (former: ngControl) with @angular/forms

### ISSUE THREAD

**Issue by n00b42** [driftyco/ionic#6938]
I used to use ion-input with ngControl together with ngFormModel and FormBuilder.
Starting with "rc.2" angular warns to use the new form logic, which will be removed in "rc.3". [(Reference)](https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub)

Therefore I tried to use the new logic like in the following example:
```
import { Component } from '@angular/core';
import { FormGroup, FormBuilder, Validators, REACTIVE_FORM_DIRECTIVES } from '@angular/forms';

@Component({
	template: '<form [formGroup]="myForm"><input formControlName="first"><ion-input type="text" formControlName="second"></ion-input></form>',
	directives: [REACTIVE_FORM_DIRECTIVES]
})
export class TestPage {
	private myForm;
	constructor(private formbuilder: FormBuilder) {
		this.myForm = formbuilder.group({ 'first': [''],'second': [''] });
	}
}
```
Which results in:
> EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./TestPage class TestPage - inline template:0:81
> ORIGINAL EXCEPTION: No value accessor for 'second'

the 'input' works fine, only 'ion-input' leads to problems.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We have not upgraded Ionic 2 to Angular rc2 yet but plan on doing so soon. Until then please use Angular rc1 for the best experience. Thanks for using Ionic!

**Comment by gustav77** [comment]
Hello, any update on this? It would be great to have the new Angular forms module on our Ionic projects.

**Comment by grapemix** [comment]
It is happening in angular-2.0.0-rc.3 / ionic beta10

**Comment by schacki** [comment]
same for me

**Comment by felansu** [comment]
+1

**Comment by itemir** [comment]
Looks like we got this with Angular rc4 in Ionic 2 beta 11 but it is giving me problems. A working example would be great.

**Comment by grapemix** [comment]
I got the same problem in beta10 and beta11

**Comment by henritoivar** [comment]
Make sure you are using @angular/forms@0.2.0

**Comment by grapemix** [comment]
Sorry for the late response. The problem for me is actually in the package.json. Since I marked the version as "ionic-angular": "^2.0.0-beta.11", instead of "ionic-angular": "2.0.0-beta.11".

My ionic version is actually in beta9 (Thanks npm!!). I am sorry for the confusion. After hours of debugging and upgrading to beta11, everything works perfect.

Thanks.
