### ISSUE TITLE
BUG: $ionicHistory.removeBackView()

### ISSUE THREAD

**Issue by DeNnYlAi** [driftyco/ionic#6940]
from the history.js

this line:
`self.clearCache([backView.viewId]);`

viewId should be change to stateId

like this:
`self.clearCache([backView.stateId]);`

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
