### ISSUE TITLE
bug: Button click handler fired upon item sliding

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#6941]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Issue is introduced in v2beta9.
Testing the following virtualsrcoll list:
```html
<ion-item-sliding *virtualItem="let col">
  <button ion-item detail-none (click)="onDetail(col)">
    <ion-thumbnail item-left>
        <img [src]="col.url" [style.height.rem]="5.6">
    </ion-thumbnail>
    <p>I've had a pretty messed up day. If we just...</p>
    <ion-badge *ngIf="col.badge !== undefined " item-right danger>{{col.badge}}</ion-badge>
  </button>
  <ion-item-options>
    <button>
      <ion-icon name="star"></ion-icon>
      Fav
    </button>
    <button secondary>
      <ion-icon name="call"></ion-icon>
      Call
    </button>
  </ion-item-options>
</ion-item-sliding>
```

Problem in desktop browser (Edge/FF47):
- Click and hold mouse button to swipe left
- Upon releasing the mouse button, click event is fired

Expected behavior:
- Click event should only fire if item is clicked without swiping</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello! Thanks for opening this issue with us! We are already aware of this issue and will be fixing it. You can follow the progress on [this](https://github.com/driftyco/ionic/issues/6950) issue. Thanks for using Ionic!
