### ISSUE TITLE
i have a third party libraries issue with ionic 2

### ISSUE THREAD

**Issue by chandumunna** [driftyco/ionic#6942]
I have a problem with third party libraries.....
1. install the npm module in my project then typings -g install into my project.
2.After that typing search pickadate and install typings of pickadate in my typings folder of my project..
and import to my js file with import pickadate from 'pickadate';
3. But it can be went to can Error: **Cannot find module 'pickadate' from**

so please help.... thanks in advance... i stucked on that error.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com) or on pickadate's github or forums. Thanks for using Ionic!
