### ISSUE TITLE
Annoying short screen blinks with some ion-cards + Loading box - Only iOS - Ionic 2 beta 9

### ISSUE THREAD

**Issue by fbrcdx** [driftyco/ionic#6943]
Only on iOS device or iOS simulator, when I present a Loading box from a page containing a bunch of ion-cards, the page blink shortly.
This seems to only happen if cards exceed screen height (scroll active). 

Ionic version : **Ionic 2 beta 9**
Platform : **iOS**

**Steps to reproduce:**
1. Create a new Ionic 2 TS project
2. Use the following files
3. Simulate or run on iOS device then click "Show loading box"
4. The page will blink shortly. Then if you keep just one card in home-page and rebuild, the page won't blink...

Need help please :/

App.ts
```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap, Loading} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {HomePage} from './pages/home-page/home-page';

@Component({
  template: `
  <ion-nav [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>
  `
})
export class MyApp {

  private rootPage:any;

  constructor(private platform:Platform) {
    
    this.rootPage = HomePage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }
}

ionicBootstrap(MyApp)
```

pages/home-page/home-page.ts
```
import {Component} from '@angular/core';
import {NavController, Loading} from 'ionic-angular';

@Component({
  templateUrl: 'build/pages/home-page/home-page.html'
})
export class HomePage {

  constructor(private _navController: NavController) {
  }

  btnHandler() {

    // Loading creation;
    let loadingIndicator: Loading = Loading.create();
    this._navController.present(loadingIndicator);

    window.setTimeout(() => {
      loadingIndicator.dismiss();
    }, 1500);
  }
}
```

pages/home-page/home-page.html
```
<ion-navbar *navbar>
  <ion-title>Home</ion-title>
</ion-navbar>

<ion-content>
  <ion-card>
    <ion-card-content>
      <h2>Title</h2>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <button (click)="btnHandler()">Show loading box</button>
    </ion-card-content>
  </ion-card>
  <ion-card>
    <ion-card-content>
      <h2>Title</h2>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <button (click)="btnHandler()">Show loading box</button>
    </ion-card-content>
  </ion-card>
  <ion-card>
    <ion-card-content>
      <h2>Title</h2>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <p>Text</p>
      <button (click)="btnHandler()">Show loading box</button>
    </ion-card-content>
  </ion-card>
</ion-content>
```

**Comment by Inoverse** [comment]
Just for information: Ionic Beta 10 still has the same issue

**Comment by jgw96** [comment]
@Inoverse is it possible for you to create a plunker that demonstrates this issue? Thanks!

**Comment by Inoverse** [comment]
Well I can create one later but you only see it on a running iOS device. In browser and on android everything works fine.

**Comment by jgw96** [comment]
Hello all, just tested this on an iphone 5 running ios 9 and using the latest nightly of Ionic 2 and cant seem to reproduce this issue anymore. If you would like to try out the nightly you can run `npm install ionic-angular@nightly`, or you can just wait for the beta.11 release. Thanks for using Ionic! Note to self: check this issue again once beta.11 is released just to confirm.

**Comment by schankam** [comment]
I've got so many "white blink" issues on iOS... With ion-cards in my case. Using ionic2 beta 10

**Comment by Inoverse** [comment]
Jep. Same here. Mostly if I added a click handler to the ion-card.

**Comment by Sebschock** [comment]
I have the same issue with ionic2 beta 11 on ios 10 (only on the device; in the browser everything works fine). Any way to fix this issue?

**Comment by harikrishna266** [comment]
i think i have the same issue. 
Its working in android, and on browser. but on iOS i have this problem.
https://www.youtube.com/watch?v=YPjnpFRMGaU

I'm using ionic RC0. 

I created a new project with the latest ionic 2. 
```

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a
```

Even with that i can see a very small blink when loader is present. If loader is not present there is no blink. 

I'm using iOS 10 on my iphone 5s. 

thanks
