### ISSUE TITLE
ionic2 bug (picker) sometimes throw an exception "Error in in ./PickerColumnCmp class PickerColumnCmp - inline template:0:215"

### ISSUE THREAD

**Issue by fuhongbo** [driftyco/ionic#6945]
ionic2 version : beta 9
IOS version : 9

this exception is not get every time,only get it if quick call picker.

if angular enable prd mode, this exception gone, but this ok button stop work.

who know what's the reason?

Exception detail:

ViewWrappedException = $1
_context: DebugContext {_view: DebugAppView, _nodeIndex: 0, _tplRow: 0, _tplCol: 215, …}
_originalException: ExpressionChangedAfterItHasBeenCheckedException {message: "Expression has changed after it was checked. Previ…ue: 'undefined'. Current value: '[object Object]'", stack: "BaseException@file:///var/mobile/Containers/Data/A…ww//build/js/app.bundle.js:59356:44↵[native code]", toString: function}
_originalStack: "BaseException@file:///var/mobile/Containers/Data/Application/A946B6EB-095E-4A48-8A4F-035437E88927/Library/Application%20Support/com.maxv.fir…"
_wrapperMessage: "Error in ./PickerColumnCmp class PickerColumnCmp - inline template:0:215"
_wrapperStack: "WrappedException@file:///var/mobile/Containers/Data/Application/A946B6EB-095E-4A48-8A4F-035437E88927/Library/Application%20Support/com.maxv.…"

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
