### ISSUE TITLE
[TABS] when back button is pressed, it is returning to previous tab selected. 

### ISSUE THREAD

**Issue by victordias** [driftyco/ionic#6947]
As tabs are set to be root pages, when hardware back button is press, normally  it exit the application. But now it is creating a history and hardware back button is pressed, it goes back to previously selected tabs.

The problem can be seen in the tabs template of ionic 2 using typescript.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1564506/16153554/3a006ca6-347d-11e6-9932-1fe84a2abd5c.gif)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually by design, but we are working on a way to make it where you can customize the functionality of the back button. Thanks for using Ionic!
