### ISSUE TITLE
Upgrade to Angular 2 rc2

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#6949]
#### Short description of the problem:
Angular rc2 includes some fixes that enables tree-shaking to finally work in webpack 2 like it is supposed too. This will help us tremendously with our new build chain. 

**Which Ionic Version?** 2.x

**Comment by aldo-roman** [comment]
JIC, Slider is broken when I upgraded to Angular 2 RC2 today (friendly noticer)

**Comment by dylanvdmerwe** [comment]
@aldo-roman: rather don't change angular dependencies yourself. Wait for the team to make a release and stick with the angular dependencies they set for each release.

**Comment by pjsb** [comment]
> rather don't change angular dependencies yourself. Wait for the team to make a release and stick with the angular dependencies they set for each release.

I agree with that, but not totally. The sad thing is, Angular was changing the forms API heavily in RC2 which should not happen in an RC, in alpha or beta phase maybe ok. Both frameworks, Ionic and Angular are heavily hyped and pushed, none is really stable yet. 

Many "users", like us, are implementing new piece of software, therefore it makes no sense to use V1. It is very bad and expensive, e.g. to use the angular forms handling before RC2 only to refactor and re-implement again in near future. Therefore it would be nice to have the frameworks synced.

Nevertheless, after doing (Germanic) some moaning ;) I forked Ionic and refactored the ion-input component already to be compatible with Angular RC2. After successful testing, hopefully tomorrow, I will do a pull request.

I would refactor some more dependend ones, but due a lack of time, I think this is not possible for me. Maybe other will follow and do some other components?

kind regards

**Comment by aldo-roman** [comment]
@dylanvdmerwe I know, I was just giving it a try. Everything worked again when restored to RC1.

**Comment by jgw96** [comment]
Hello @pjsb . We do our best to keep up with the Angular team's updates, and we are usually behind by one version so that by the next beta we can do any changes done that need to be done on our end. We obviously have no issue with people upgrading to a new Angular release before we do, but we cannot guarantee that it will work 100 percent. Also, cant wait to see your pull request!

**Comment by jtushar53** [comment]
Please upgrade it to rc3 :beers:

**Comment by jgw96** [comment]
Hello all, the plan is to upgrade to Angular 2 rc3 for our beta.10 release now. I will be closing this issue as it is not valid anymore. Thanks for using Ionic!
