### ISSUE TITLE
Sliding item: (click) event is fired when it should not

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#6950]
#### Short description of the problem:
![jun-17-2016 17-44-42](https://cloud.githubusercontent.com/assets/127379/16156464/ad770e92-34b4-11e6-860d-af102b613bd0.gif)

#### What behavior are you expecting?
(click) even should not fire when the item has been swiped.

**Steps to reproduce:**
1. Desktop only (mouse events)

**Comment by mpaland** [comment]
Here's the according plunk: http://plnkr.co/edit/Ire4uEqc1Kxwmje7L0k1?p=preview

**Comment by manucorporat** [comment]
@mpaland hi! I understand this is a very important issue, I am working on a fix.
https://github.com/driftyco/ionic/pull/6937
^ this PR will introduce a new UIEventManager that will help to fix this issue.

**Comment by manucorporat** [comment]
@mpaland fixed! https://github.com/driftyco/ionic/commit/38ab17b0a8b91698b60d3f75420006a61b7500e1
