### ISSUE TITLE
DateTime doesn't handle seconds

### ISSUE THREAD

**Issue by reverdin** [driftyco/ionic#6951]
I tried to put a DateTime as following:
`<ion-datetime displayFormat="HH:mm:ss" pickerFormat="HH:mm:ss"></ion-datetime>`

The picker only show two column (hour and minutes) and the displayed value is "13:20:ss" if I select 13 for the hours and 20 for minutes.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by reverdin** [comment]
Never used plunker but can give  a try later.

I am using a blank starter with beta2 and typescript.

I just putted the following code in the content fo  the home.html file:
`<ion-item><ion-datetime displayFormat="HH mm ss" pickerFormat="HH mm ss"></ion-datetime></ion-item>`

Using Ionic Framework Version: 2.0.0-beta.9

Here is a screenshot of my browser with ionic serve
![blank_starter_et_home_html_ _myfirstapp_app_pages_home_ __users_reverdin_dropbox_ionic_test_timers_app](https://cloud.githubusercontent.com/assets/12937009/16158053/a9a398ce-34bb-11e6-8dbc-416750d381b3.png)

**Comment by jgw96** [comment]
Hello @reverdin i was able to reproduce this issue here: http://plnkr.co/edit/J8qPI5vCdU4ICgaKVMlg?p=preview
