### ISSUE TITLE
Turorial starter is still using @Page instead of @Component

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#6952]
#### Short description of the problem:
Tutorial starter is still using @Page instead of @Component

**Steps to reproduce:**
1. run ionic start MyIonic2Project tutorial --v2
2. open the list.ts file
3. @Page decorator is present

**Which Ionic Version?** 1.x or 2.x
2.beta9

**Comment by jgw96** [comment]
Good catch @jabas06 ! I just committed a fix for this so if you just run `ionic start MyIonic2Project tutorial --v2` again it will generate a project that is correct. Thanks for using Ionic!

**Comment by jabas06** [comment]
In fact, the issue is present in all the pages, not just in lists.ts

Thank you
