### ISSUE TITLE
pipe on arrays are not working

### ISSUE THREAD

**Issue by vjangari** [driftyco/ionic#6953]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I am trying to apply custom pipe on array, which is not working. The log shows array object as null in pipe transform method.  But page is showing 3 records if i remove the filter.

`
 checkList: CheckList[] = [];
` 
`
<ion-item-sliding *ngFor="let item of (checkList | itemFilter:true); let idx=index" #slideItem >`

```
import { Pipe, PipeTransform } from '@angular/core';
import { CheckList } from './checklist';
@Pipe({ 
    name: 'itemFilter',
 })
export class ItemFilterPipe implements PipeTransform {
  transform(items: CheckList[], showDeleted) {
      console.log("in filter: "+ showDeleted+","+items);
     return items.filter(item => item.isDeleted === showDeleted);
  }
}
```
```
console log: 
501479   log      in filter: true,
```

#### What behavior are you expecting?
it should filter records based on flag

**Steps to reproduce:**
1. create a pipe
2.  apply on array of sliding items
3.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.x - beta-9

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jeromeXoo** [comment]
Hi, 

did you try wihout parenthesis?
`let item of checkList | itemFilter:true; `

**Comment by vjangari** [comment]
I tried but not working.

**Comment by vjangari** [comment]
It is working for me. Sorry for the confusion
