### ISSUE TITLE
Ionic 2: Inappropriate behaviour when dismissing alert which is on top of a modal

### ISSUE THREAD

**Issue by sam1019** [driftyco/ionic#6954]
I have a modal for editing or deleting item. When user want to delete the item, I show a confirm alert asking if user is sure about the delete. 

Once user click "yes", I call the delete function and **this.viewCtrl.dismiss()**. Then the confirm alert dismissed. However, the modal is still there. And user have to click twice on the screen so that the interaction with the UI will recover. Maybe there is a transparent layout when dismissing the alert.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by danbucholtz** [comment]
Are you dismissing both the `Alert` and the `Modal`?  Both are separate view controllers pushed on to the stack.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
