### ISSUE TITLE
Use @Inject instead of static get parameters()

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic#6959]
Ionic 2 starter projects currently uses `static get parameters()` in esnext code as a workaround for the lack of parameter decorators in Babel. See e.g. [Adding Pages](http://ionicframework.com/docs/v2/getting-started/tutorial/adding-pages/) in the tutorial.

Parameters decorators should now work using the _babel-plugin-angular2-annotations_: see https://github.com/shuhei/babel-plugin-angular2-annotations/issues/19

So it should be possible to write

    constructor(@Inject(NavController) nav, @Inject(NavParams) navParams) { /*...*/ }

**Comment by mirkonasato** [comment]
Just noticed that the [latest ionic-cli](https://github.com/driftyco/ionic-cli/blob/v2/CHANGELOG.md#200-beta31-2016-06-13) only supports typescript. So this doesn't matter any more.

**Comment by manucorporat** [comment]
@mirkonasato yeah! we took the decision to drop js support, since TS is a superset of JS it's up to developers to use the new features introduced.

This way we can concentrate our efforts of documentation, demos and testing.

**Comment by mirkonasato** [comment]
@manucorporat good decision 👍

**Comment by gustavohenke** [comment]
@manucorporat, what a shame that you guys took that decision.

TypeScript is simply too slow for me, so from the start I decided to use ES6.
I learned to write Angular 2 ES6 code using Ionic's templates. Not anywhere else in the web there was another starting point as good as Ionic.

And, to complete.. the official Angular docs are just poor in terms of ES6 support.
