### ISSUE TITLE
Need to click n+1 times in a list

### ISSUE THREAD

**Issue by aaronchen2k** [driftyco/ionic#6962]
I dev a mobistore webapp and using iphone6 safari to open it. 
In home list page, first time, I click product item once, it took me to the detail page.
After back to home page, I need to click twice to goto detail. After click and back for n time, I need to click n+1 times to goto the detail.

Demo URL: http://101.200.189.57:13333/c/

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have just tested your app on my Nexus 6 using the latest stable version of chrome and I can't seem to reproduce this issue. Can you recreate this issue with a minimal example in a plunker? Thanks for using Ionic!

**Comment by aaronchen2k** [comment]
Sorry, now can not reproduce this bug since I fixed it by replace  <ion-item> with <button ion-item> tag, I found the issue on iphone6 before.
Will ionic2 always support <button ion-item> for a long time? Thanks.

**Comment by jgw96** [comment]
No problem, glad the issue was fixed and yes, Ionic 2 will be supported for a long time as it is the newest and latest version of Ionic. Thanks for using Ionic!
