### ISSUE TITLE
Cannot Create Javascript Project in ionic 2

### ISSUE THREAD

**Issue by AbdullahDahmash** [driftyco/ionic#6964]
Hi
I just started working today and I couldn't create javascript project

I tried 
```sh
ionic start myProject --v2 --no-ts
```

All my files are in .ts

**Comment by kitkimwong** [comment]
same problem here +1

**Comment by manucorporat** [comment]
@AbdullahDahmash @kitkimwong JS option has been removed, since we are going to focus our efforts to support Typescript.

Since TS is a superset of JS, it is up to developers to use the new features or not. We strongly recommend to give TS a try, decorators and types help a lot while using angular 2.

**Comment by johnygomez** [comment]
What's the point of removing optional Javascript setup?? Was it too complicated to maintain?
Forcing Typescript seems like abandoning the Javascript principles and minimalism and moving towards Java. Well, why not using Java instead of strongly typed Javascript then?

**Comment by ParryQiu** [comment]
@johnygomez +11111111111

**Comment by eddiejaoude** [comment]
Angular2 supports **Javascript** as well as **TypeScript** - disappointing news for Ionic2

**Comment by jopcode** [comment]
One reason more for "I hate TS", :sob:

**Comment by manudefrutosvila** [comment]
bad news... don't force us to use TS, give the option to choose would be a smart decision

**Comment by vxcamiloxv** [comment]
I don't like TS, with pure javascript you can decide has last js features with babel or similar.

**Comment by manucorporat** [comment]
TS is not a different language, but a superset, that means you can write vanilla JS if you want to, just don't use classes, types, or anything.

**Comment by cleever** [comment]
TS is very easy to code and maintain. Development time error checking is a time saver.
Also, there is a lot of super cool features.

If you want to write pure JS, yor can.

Please, give TS a try, you won't regret.

**Comment by manikandan07081995** [comment]
I want to use same JS code in my ts ionic 2 projects.How to implement JS in my TS and reference and tutorial is there.Please help me.Because I need to write a function for epson thermal printer they given only support for js.
