### ISSUE TITLE
ionic 2 pop with parameters

### ISSUE THREAD

**Issue by ameni26** [driftyco/ionic#6965]
hello I want to use pop() to return to the parent page and pass a parameter string
is that possible in ionic 2
thank you :+1:

**Comment by manucorporat** [comment]
@ameni26 maybe you should use a modal.

**Comment by ameni26** [comment]
how can I use a modal please :)
is there something simple in ionic2 like that

 this.nav.popTo(this.viewCtrl, {
 param1: p1,
 param2: p2
 });

**Comment by mpaland** [comment]
@ameni26 And how do you want to retrieve the param string on the parent page?
If you push a page on the nav stack, the push (or present) function returns immediately.

As @manucorporat said, use a modal dialog page, this may be the right pattern for you.
Try:
```typescript
    let modal = new ViewController(MyPage, this.param);
    this.nav.present(modal);
    // no waiting for modal here!
    modal.onDismiss((data: { your params }) => {
      // this is called upon modal dismiss
      if (data) {
      }
    });
```
And please use the  ionic v2 forum for requests like this.

**Comment by manucorporat** [comment]
yeah! checkout http://ionicframework.com/docs/v2/api/components/modal/Modal/
and @mpaland is right, please feel free to continue the conversation in the forum https://forum.ionicframework.com

I am going to close this :)
