### ISSUE TITLE
select option not working

### ISSUE THREAD

**Issue by arjuncfe** [driftyco/ionic#6967]
I am using ionic 2 beta version and create simple app. After app creation i make android build my generated code. But select option not  open on android 4.1.1(Jelly bean ) Samsung mobile. How can all run this app on this version.

**Comment by jgw96** [comment]
Hello! Our Android support for Ionic 2 is the current latest stable release (6.0.1) back to 4.4.4, and 4.3 back to 4.1 with crosswalk. So for your application to behave correctly on Android 4.1.1 you will need to add crosswalk to your app. Crosswalk gives you a modern chrome webview that's has all the html5 support Ionic 2 needs, even on older versions of Android.  You can check out how to add crosswalk here http://ionicframework.com/docs/cli/browsers.html . Thanks for using Ionic!
