### ISSUE TITLE
Add arrow for picker

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#6969]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

On desktop the UI is confusing. I cant use scrollwheel of the trackpad (hence assume the same with mouse). Also an arrow would make sense helping people move up/down. 
#### What behavior are you expecting?

Arrows allowing user to scroll up and down on desktop

**Steps to reproduce:**
1.  Go to http://ionicframework.com/docs/v2/components/#datetime on desktop
2. Click on a date field 
3. It's confusing how to scroll/change date

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#46
