### ISSUE TITLE
Clicking on DateTime delays and spams warning.

### ISSUE THREAD

**Issue by Zenro45** [driftyco/ionic#6971]
#### Short description of the problem:
Clicking on the Datetime picker delays by 1-2 seconds and spams 'WARNING: sanitizing unsafe style value' into the console during the delay.

#### What behavior are you expecting?
Datepicker to not delay and there to be no warnings in the console.

**Steps to reproduce:**
1. Insert the following into the template html file
```<ion-datetime displayFormat="MMM DD, YYYY" [(ngModel)]="BINDED_VARIABLE" (ionChange)="FUNCTION_NAME()"></ion-datetime>```
2. Go to the page
3. Click on the 'datetime' selector
4. Look at the console.
 
**Which Ionic Version?** 1.x or 2.x
Ionic 2 Beta 9

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by chandanch** [comment]
Yes I have also observed this delay,  The delay is because Angular strips down some of the styles and removes all the conflicting id's if any.

**Comment by battistaar** [comment]
I realized that using Content component works fine (even in nested Content instances). 

In my project I was trying to add a method to the virtual-scroll component to scroll the list to the top using the _content field of the class. It worked fine on browser but not on iOS, making the changes I have written above it works properly both on browser and iOS. 

I do not know why this different behavior, I'll do some more tests as soon as possible.

It would be useful to have a scrollToTop method for virtualscrolls, do you know if there is another way to do that?

**Comment by Zenro45** [comment]
I would love to give you a plunker link, however, the nature of the issue is strictly with ```
<ion-datetime displayFormat="MMM DD, YYYY"></ion-datetime>``` and my version of Ionic. It seems to work fine it Plunker but not in my project.

**Comment by nikoTM** [comment]
For me it spawns a lot of warnings when I click on picker, and later when I switch from AM to PM and vice versa in the the picker I get 4 warnings per change. Thought additional info might help.

**Comment by jgw96** [comment]
Hello all! I am currently not able to reproduce this issue, but some of my teammates are testing now so i will get back to you all when they have finished testing. Thanks everyone!

**Comment by jgw96** [comment]
Awesome, glad its working for you now! Yep we just recently changed our package.json. Also, just so you know, i just tested with our latest Ionic 2 nightly which is using Angular 2 rc3 and i can't seem to reproduce their either, so it looks like it was an Angular 2 rc2 issue. Thanks for using Ionic!
