### ISSUE TITLE
Ionic + eCharts + WP8

### ISSUE THREAD

**Issue by rodrigosilvape** [driftyco/ionic#6972]
Good morning friends.

I'm working on an Ionic + eCharts application. This application works perfectly on Android and iOS, but WP 8.0 (in 8.1 normal works) the chart is fixed, can not interact with anything. Imagine a still image of the graph. Already researched several ways to fix this problem, but without success. Do you have any idea of a possible solution? Thank you.

**Ionic info:**
Cordova CLI: 6.1.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
OS: Windows 8.1
Node Version: v4.4.0

**Plunker:**
http://plnkr.co/edit/cxgqcJWgrs12AjwtjUjR?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We do not currently support windows phone 8 so theres not much i can do to help with this issue, but i can suggest that you open a topic about it on our forums (https://forum.ionicframework.com/) or even StackOverflow. Thanks for using Ionic!
