### ISSUE TITLE
Content scrollToTop issue in v2

### ISSUE THREAD

**Issue by battistaar** [driftyco/ionic#6973]
scrollToTop() on Content component doesn't work on ios. The problem is in [scroll-view.ts](https://github.com/driftyco/ionic/blob/2.0/src/util/scroll-view.ts) in scrollTo method. 
At line 51 when getting the actual scrollTop position it should call self.getTop() that takes care of the "js" check.
I changed it in my project and it seems to work.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
