### ISSUE TITLE
Virtual scroll not working in ion-slides

### ISSUE THREAD

**Issue by elineopsommer** [driftyco/ionic#6974]
#### Short description of the problem:

Without the slider, the list behaves normally, but with the ion-slides, the content is not displayed correctly.
#### What behavior are you expecting?

Data shown correctly

**Steps to reproduce:**
1. Make slider
2. Make virtual list in slider

```
    <ion-slides #contentSlider (ionWillChange)="contentListChanged()">
      <ion-slide *ngFor="let contentTab of contentOfNavigationTabs">
        <ion-list [virtualScroll]="contentTab">
          <ion-item *virtualItem="let item">
            {{item}}
          </ion-item>
        </ion-list>
      </ion-slide>
    </ion-slides>
```

**Which Ionic Version?** 2-beta0.0.9
#### Plunker that shows an example of your issue

http://plnkr.co/edit/BgRiHgBEPXLK3G9LRkq2?p=preview

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by elineopsommer** [comment]
@jgw96 Any updates on this? It is really important for us that this works..

**Comment by jgw96** [comment]
Hello @elineopsommer i dont have any updates on this at the moment, but i will get back to you as soon as i do. Thanks for using Ionic!

**Comment by elineopsommer** [comment]
@jgw96 It's been a while since this issue is posted, do you have an update on this?

**Comment by tunguyenbhtech** [comment]
I'm having this problem too :( , looking forward for update @jgw96

**Comment by adamdbradley** [comment]
At this time we virtual scroll is not designed to work within ion-slides. I would recommend using a normal ngFor, and to reduce the amount of data trying to be fit within each slide.

**Comment by renwei0207** [comment]
Hi, I'm having this problem too, is any solutions now?
