### ISSUE TITLE
Occasional white screen on ios when navigating quickly via $state.go()

### ISSUE THREAD

**Issue by antpuleo2586** [driftyco/ionic#6976]
#### Short description of the problem:

When I navigate between views, I occasionally get a white screen on ios. Usually I can reproduce this by tapping between views too quickly, but it also happens intermittently when navigating normally.
#### What behavior are you expecting?

The view to appear as normal.

**Steps to reproduce:**
1. Navigate from one view to another

**Other information:** 
I can't reproduce this using a plunker, but I do have some further information:
When I inspect with Safari, the `<ion-view>` element completely disappears and seems to be replaced with a `<div>` like this:
`<div class="pane" nav-view="entering" style="-webkit-transition: 0ms; transition: 0ms; transform: translate3d(0%, 0px, 0px); opacity: 1;"></div>`

Here are two screenshots showing this:
Before: https://www.dropbox.com/s/ypxdcfwjveodltm/ionic%20ios%20before.png?dl=0
After: https://www.dropbox.com/s/cc04qx5ncd0klpk/ionic%20ios%20after.png?dl=0

I'm using crosswalk but this problem doesn't occur on android at all. Also doesn't occur when I serve the app in a web browser. I even removed crosswalk and get the same issue.

**Which Ionic Version?** 
1.3.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

ios version: iPad: 8.4 and iPhone: 9.2

Has anyone had this problem or can anyone explain why this might be happening/how I can fix?

Thanks!

Antonio

**Comment by leroygumede** [comment]
Did you ever find a fix to this ? @antpuleo2586

**Comment by antpuleo2586** [comment]
@leroygumede No, are you having the same problem?

**Comment by leroygumede** [comment]
@antpuleo2586, and your right about it happening randomly , I tried this method but it seems not to work on android devices
```
        $timeout(function() {
            $ionicHistory.clearHistory();
            $state.go('tabsController.home');
        }, 300);
```

**Comment by antpuleo2586** [comment]
@leroygumede Ah ok, well this problem only happens to us on iOS devices. I'll try your method, cheers.

**Comment by leroygumede** [comment]
@antpuleo2586 After much researching I found the Issue #3216 unfortunately the solution is not too use `cache: false` 👎

**Comment by antpuleo2586** [comment]
@leroygumede Thanks for the advice, but unfortunately it's still crashing for us, even when using `cache-view="true"`.
Back to the drawing board..

**Comment by leroygumede** [comment]
@antpuleo2586  This worked perfectly for me. I removed all the `cache-view="false"`
`$ionicHistory.clearCache().then(function() { $state.go('tabsController.home') });`

**Comment by antpuleo2586** [comment]
Thanks @leroygumede but still the same for me. It's really an edge case thing, if I tap too quickly on the button to navigate back, I can recreate it quite easily now :/

**Comment by antpuleo2586** [comment]
Hey @leroygumede 
We get this error via safari:
"Gesture: Failed to receive system gesture state notification before next touch"
Which seems to be the cause of the white screen for us; have you ever seen this?


Cheers

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#119
