### ISSUE TITLE
Ionic strips downs the attributes of an element in ionic-angular2.0.0.beta9

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#6977]
There is more issue with the innerHTML attribute, angular strips down the id attribute if a particular innerHTML has been specified with ID, Here is the code snippet which gives more clarity on what I'm trying to explain:

**page.html**

.....
`<div id="outerdiv" [innerHTML]="htmlElement"></div>
`
**page.ts**

```
......
export class Page {
   public htmlElement;
   constructor(){
       this.htmlElement = "<html><head><link rel='stylsheet' href=../styles/mystyle.css' /></head><body><p id='maincontent'>This paragraph is generated programatically</p></body></html>"
   }
  
}

```
Run this on a browser and inspect on the dynamically generated paragraph element, The id attribute will be striped down by angular.

What could be the issue for this? Any inputs on this?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this seems like an angular problem and not an Ionic issue i would suggest you open this issue on the angular repo. Thanks for using Ionic!

**Comment by chandanch** [comment]
Ok, I will report on angular
