### ISSUE TITLE
Opening a tabs page from another tabs page doubles the tab bar on iOS

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic#6978]
### Short description of the problem:
I have a app which contains pages with different tabs. If I want to navigate from a tab of the first tabs page to a tab from the second tabs page, the second tab bar gets inserted above the first tab bar - instead of replacing it.

This happens only with iOS, not with Android.

#### What behavior are you expecting?
Also on iOS, I expect the tab bar to get replaced by the new one.

**Steps to reproduce:**
I published a report on https://github.com/Ritzlgrmft/DoubleTabs. It is based on the tabs starter template. I added a new tabs page called `tabs2`, which gets called from a new button on the `home-page`. As soon as you click it, the tab bar gets duplicated (since both tabs pages use the same tab layout).

**Which Ionic Version?** 
2 Beta 8 and Beta 9

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by Ritzlgrmft** [comment]
I just created a Plunker: http://plnkr.co/edit/Rd0hrscQinznTciLLpWk

**Comment by jgw96** [comment]
Hello, thanks for posting the plunker! I have created another plunker that demonstrates the solution for this issue [here](http://plnkr.co/edit/s11inw2zUdy4XU9QW3A8?p=preview). If you check `app.ts` you will see that i have set the `tabSubPages` config to true. Thanks for using Ionic!
