### ISSUE TITLE
ionic2 - bug(backdrop?) - on iOS, components with a backdrop (alert, modal, etc.) do not prevent user from scrolling content behind them.

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#6980]
#### Short description of the problem:

If an alert, etc is visible on iOS, I can attempt to slide the content behind the backdrop and will be able to do so. When this happens and the keyboard is open, I can no longer scroll the entire view any more. In other words, some of modal/select content is under the keyboard and I can't scroll it up.
#### What behavior are you expecting?

I expect to not be able to scroll or interact with anything that is  under a modal-like component.

**Steps to reproduce:**
1. Create a view with enough content to make it scrollable
2. Create an ion-select with options. Open it and try to scroll the content behind it. OR
3. Create a popover with an input on it. Open it, select the input (make the keyboard appear), and then try to scroll the content behind it.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I would create a plunker, so I can only reproduce it on iOS.
Not sure if it matters, but I am seeing this within an ion-slide. (haven't tried it anywhere else)

**Which Ionic Version?**  2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by alessandro-salomone** [comment]
I confirm the same problem on modals with transparent background. 
I can scroll the content of the page behind the modal, but only on iOS devices.
Using ionic-angular 2.0.0-beta.10

**Comment by ctesene** [comment]
It looks like the ```disablescroll="false"``` in ```ionic/src/components/modal/modal-component.ts``` is hardcoded to false. When I changed it to true, I was no longer able to scroll items behind the backdrop.

![image](https://cloud.githubusercontent.com/assets/1243453/17343631/8a26fe20-58b3-11e6-97b3-d35936a6b5a8.png)

If we add ```disableScroll``` as an option when creating a modal, we could modify this behavior.

**Comment by galvanu** [comment]
Same happens for me on Beta-10. do you have any fix/work around for this issue?

On android things work as expected.

**Comment by ctesene** [comment]
Any updates?

**Comment by akagr** [comment]
This is still happening in Beta 11. Not sure about the best way to work around this. Anyone tried anything short of fully custom implementation?

**Comment by finalxcode** [comment]
is there a way to change backdrop `disableScroll` to true when loading with transparent background?

**Comment by longzheng** [comment]
As a workaround, I added this to my ``app.scss`` that disables overflow scrolling on all ``scroll-content`` when ``disable-scroll`` is applied to the app.

```
ion-app.disable-scroll {
    ion-content>.scroll-content {
        overflow: hidden;
    }
}
```

**Comment by gabcvit** [comment]
@longzheng Thank you so much! This workaround worked like a charm for me!

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic. We have tried multiple solutions in UIWebView to disable scrolling when an overlay component is active but unfortunately, there is not a good way to do this that does not cause either flickering or bad performance. Because of this, we made the decision a while ago to fix the issue with some native side code in our [WKWebView](https://github.com/driftyco/cordova-plugin-wkwebview-engine) plugin. If you use that plugin (which is gonna be our standard webview for iOS very soon) this issue is fixed.

**Comment by anjanapai2508** [comment]
@jgw96  The WKWebView plugin needs cordova to be installed, if you plan to make this as the standard webview for iOS does that mean that all ionic iOS apps absolutely need to use cordova?

**Comment by ilyalukyanov** [comment]
@jgw96 I tried upgrading to WKWebView as suggested by this doc and it seems to do the trick for `AlertController`, but unfortunately does nothing for `ModalController`, i.e. vertical swipes on a modal scroll content underneath it.

Do you have any recommendations how that could be fixed? Otherwise I think it would be valid to reopen this issue.
