### ISSUE TITLE
VirtualScroll Component Docs ionic2

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#6985]
component docs for virtualscroll on the ionic site still use old # based notation rather than let.

*virtualItem=#item

should be:

*virtualItem= let item

while the old still works now with a warning thrown to the console the docs should be updated.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This has actually already been fixed but has not been pushed to the public docs yet. Sorry about any confusion this caused, it should get pushed soon. Thanks for using Ionic!

**Comment by ghenry22** [comment]
no problem, I just noticed it when looking at something else and thought it was worth mentioning in case it had been overlooked.
