### ISSUE TITLE
Ionic2 searchbar.  searchbar.value not present in beta9

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#6989]
#### Short description of the problem:
Follow the docs from the ionic2 components page to create a very simple searchbar example.  $event is passed into the search function.

Within the javascript search function the value in the searchbar is extracted from the passed event with searchbar.value

This worked perfectly up to beta8.  In beta9 the value property does not exist at the top level of the passed $event object.  The value does exist under .target.value but if the value is null then the .target.value property is not created on the $event object so it is necessary to add an extra step to the search processing js if an if(searchbar.target.value) else set the internal variable for the search term to an empty string.

#### What behavior are you expecting?
the value property is passed from the searchbar $event as it as in previous betas or the documentation is updated to reflect the change.

**Steps to reproduce:**
1. start a new project, add a list and a search bar using the example code from the component docs.
2. perform a search to filter a list
3. an exception is thrown because searchbar.value doesn't exist.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0 beta9

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by brandyscarney** [comment]
This is an issue. I changed it to pass the event instead of the searchbar itself because I thought it would be more valuable to get the mouse/click event, since we can use `ViewChild` to get the `Searchbar` itself if desired. 

Docs do need to be updated, and we need to add this to the breaking changes for beta 9.

**Comment by jgw96** [comment]
@brandyscarney ahh ok, thanks for that info. Ill make an issue on the site repo to update the docs.

**Comment by brandyscarney** [comment]
Thanks for the issue, I updated the changelog to include the Searchbar changes and we will update the component docs as part of driftyco/ionic-site#657. 

https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta9-2016-06-16

**Comment by ghenry22** [comment]
There is still a problem with this as if the search bar is black, say because someone has cleared or backspaced to remove it and the event is then submitted without a value, the target.value property is not set to an empty string, it simply doesn't exist.  So the user needs to catch this or it will be throwing exceptions in the console.

```
getItems(ev) {
  // set q to the value of the searchbar input if it exists
  if(ev.target.value){
    var q = ev.target.value;
  } else {
    var q = '';
  }
}
```

**Comment by brandyscarney** [comment]
Thanks @ghenry22. We'll update the docs to show this. I've updated the preview app to use the new syntax: https://github.com/driftyco/ionic-preview-app/commit/2edf4c6806b9432de73cd3b69684efe7f91332d6

https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/searchbars/basic/pages.ts#L55-L68

**Comment by matheo** [comment]
@brandyscarney Hi!
is there a way to get the HTMLInputElement from the SearchBar component? to pass it to google.maps.places.Autocomplete, as shown here:
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform
```
autocomplete = new google.maps.places.Autocomplete(
      /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
      {types: ['geocode']});
```

I had to workaround the issue getting the input by class name:
https://forum.ionicframework.com/t/use-viewchild-on-directives-child/55659
```
let elem = <HTMLInputElement>document.getElementsByClassName("searchbar-input")[0];
// then
let places = google.maps.places.Autocomplete(elem);
```

but it would be ideal if the API let us access the input element in some way.
Thanks in advance!

**Comment by brandyscarney** [comment]
Hey @matheo, could you create a new issue for this please and I'll look into it? Thanks!

**Comment by matheo** [comment]
Ok ;)
