### ISSUE TITLE
Ionic2 not supporting the usage of multiple platform-href attributes in Index.html

### ISSUE THREAD

**Issue by matmica** [driftyco/ionic#6990]
#### Short description of the problem:
Ionic not allowing the multiple usage of the below tags in Index.html:
- ios-href
- md-href
- wp-href

#### What behavior are you expecting?
I would like Ionic to allow the inclusion of multiple instances of stylesheets using the aforementioned tags. One could argue towards the scope of these tags as being a platform stylesheet however, if they're used for importing one common, global stylesheet. However, I want these stylesheets to be cached and therefore I require their direct inclusion in the Index.html. E.g. of required situation:

```
<link ios-href="./dist/page1.ios.css" rel="stylesheet">
<link md-href="./dist/page1.md.css" rel="stylesheet">
<link wp-href="./dist/page1.wp.css" rel="stylesheet">

<link ios-href="./dist/page2.ios.css" rel="stylesheet">
<link md-href="./dist/page2.md.css" rel="stylesheet">
<link wp-href="./dist/page2.wp.css" rel="stylesheet">
```

**Steps to reproduce:**
Not Relevant.

Code extracted from ionic-angular/config/bootstrap.js (lines 101 to 107):

```
    var modeLinkAttr = mode + '-href';
    var linkEle = document.head.querySelector('link[' + modeLinkAttr + ']');
    if (linkEle) {
        var href = linkEle.getAttribute(modeLinkAttr);
        linkEle.removeAttribute(modeLinkAttr);
        linkEle.href = href;
    }
```

**Other information:**
Suggestion: Ideally the code above would loop over the platform specific `href` attributes and would be able to handle more than one of these stylesheets in the Index.html.
 

**Which Ionic Version?** 
Ionic2 - Beta 8

**Comment by brandyscarney** [comment]
Hey @matmica, I don't think this is something that should be added since we have Sass to handle it. For example, if there are specific files that should only be added per mode, you can create them like this:

```
app/
  pages/
    page1/
      page1.ios.scss
      page1.md.scss
    ...
```

and then in the `app.ios.scss` file you would import the `ios` one:

```
// App iOS Only Sass
// --------------------------------------------------
// CSS that should only apply to the iOS app

@import "../pages/page1/page1.ios";
```

And in the `app.md.scss` file you can import the `md` one. We are doing this in the preview app:

https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/cards/advanced-weather/styles.ios.scss
https://github.com/driftyco/ionic-preview-app/blob/master/app/theme/app.ios.scss#L36

Then the final `app.ios.css` stylesheet will include those pages. Does that solve your problem?

**Comment by alan-agius4** [comment]
Hi Brandy,

Thanks for your suggestions, I do fact the above issues as well. As i'd like to have a more mobilized application. As I would have several "lobbies" which I don't want to combine and concatenate with your stylesheet. Reason being, is I want to do some sort of lazy loading and not request the "global/common" stuff for each lobby.

**Comment by jgw96** [comment]
Hello @alan-agius4 ! Sorry if im misunderstanding your issue, but we only load our stylesheets once (when the app first loads). If you lazy loaded css for each part of your application it would actually be slower than just loading all the css up front. Whenever you load css the browser/webview has to block so if your lazyloading css as you need it, your app will constantly be blocking each time you navigate to that new part of your app. If you want to have separate styles for each page you can just do as brandy showed above. Hope this explains everything for you!

**Comment by jgw96** [comment]
Hello everyone! After discussing this with my teammates we have decided that, while we really appreciate your idea, this is not something we are going to add to the framework. We are more in favor of  using sass as brandy described above. Thanks for the issue though, and have fun using Ionic!
