### ISSUE TITLE
Custom component nav menu does not work time to time

### ISSUE THREAD

**Issue by EugeneSnihovsky** [driftyco/ionic#6992]
#### Short description of the problem:
I create a navbar component with ionic directives inside (**ion-navbar + ion-menu**).
For some reason navbar menu disappear after navigation. If navigate to other page - menu appears again. For next navigation menu disappear and so constantly all the time.
![Screen example](https://pp.vk.me/c636221/v636221750/111a3/XzWPaMkU46s.jpg)
#### What behavior are you expecting?
I want to use the menu at each step without any problems

**Steps to reproduce:**
1. git clone -b ER-2_navbar_menu_error https://github.com/EugeneSnihovsky/ionic2-for-errors.git
2. cd ionic2-for-errors
3. npm install
4. ionic serve
5. on opened page menu works. Click **New Transfer**
6. On create-new-page menu will not work. Click **Create new**
7. On dashboards-page menu works again. Select **Dashboards** from menu
8. On same dashboards-page menu will not work.

**Other information:** 
Maybe something wrong here:
This navbar used **navCtrl.setRoot** with pages, that have my navbar component in their html template. For this case (for avoid dehydrated errors) I use in Component decorator:
```typescript
directives: [forwardRef(() => TopNavBarComponent)]
```
and timeout hack in page change method:
```typescript
public openPage(name: string): void {
        setTimeout(() => {
            this.navCtrl.setRoot(this.pages[name]);
        }, 100);
    }
```
**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.2 Rafaela 
Node Version: v5.3.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind removing your "hack" and then seeing if you still get the same issue? Thanks for using Ionic!

**Comment by EugeneSnihovsky** [comment]
@jgw96, Hi. I checked the code without "hacks" and still have the same issue. Nothing changed. I update my repository branch for show this issue without "hack".

**Comment by jgw96** [comment]
@EugeneSnihovsky After looking at this some more this seems to be related to content projection. One i do some more testing i will get back to you with some more details.

**Comment by EugeneSnihovsky** [comment]
@jgw96, I am new at ionic2 and angular2, but I take look a deep in page view with chrome and found that ionic sometimes not add **class="show-menu"** (and others attributes, but class is important for this case) for **ion-menu** element. If I add this class to broken menu manually - menu append in view.
## Normal menu
![Normal menu](https://pp.vk.me/c636221/v636221090/fdff/a8QmTqiLuI8.jpg)
## Broken menu
![Broken menu](https://pp.vk.me/c636221/v636221322/146f9/SccI-ABqDIo.jpg)
## Manually fixed menu
![Manually fixed menu](https://pp.vk.me/c636221/v636221652/110fb/9WeFNP7vvdE.jpg)

**Comment by jgw96** [comment]
If you use these components separately (without wrapping them in your own component) do you still get the same issue?

**Comment by EugeneSnihovsky** [comment]
@jgw96, I remove top-navbar component and put content of ion-menu with ion-navbar to each page template, but still get an issue.
You can see it with commits:
1. commit a98217888b2f2977f0463133a8a8363b8b6eb627 - separated components in each template.
2. commit 4441f51ce80a5796f6fe684cf2e392a742757413 - ion component wrapped into top-navbar.

P.S: wrapping menu into a component is very important for development. Otherwise we get not scalable application. For example we have 100 pages and each of them - is item in menu. And all pages have menu. When we modify some menu item - we must do it 100 times without top-navbar component.

**Comment by EugeneSnihovsky** [comment]
Problem in this line
https://github.com/driftyco/ionic/blob/2.0/src/components/menu/menu.ts#L346

Probably something wrong with ngOnDestroy for menu component.

**Comment by jgw96** [comment]
Hello! Would you mind updating your repo please, it does not seem to build using our latest ionic cli because your repo is still using Ionic 2 beta.1. Thanks!

**Comment by EugeneSnihovsky** [comment]
Hi. You should not use master branch. Current issue located at "ER-2_navbar_menu_error" branch and reproduced on "ionic.2.0.0-beta.9 and angular.2.0.0-rc.1.

**Comment by jgw96** [comment]
Hello, is this what im supposed to be seeing when i first `ionic serve` your app? 
![screen shot 2016-06-24 at 10 35 30 am](https://cloud.githubusercontent.com/assets/8823093/16342403/85d53196-39f7-11e6-9956-0e1330c582be.png)

**Comment by EugeneSnihovsky** [comment]
Yes.

**Comment by jgw96** [comment]
@EugeneSnihovsky would you mind testing this with beta.10? We did a layout refactor in that version that should help with this. Thanks!

**Comment by EugeneSnihovsky** [comment]
@jgw96, I update my repository **branch** (ER-2_navbar_menu_error) to ionic2.beta.10 and still have an issue.

The problem somewere here
https://github.com/driftyco/ionic/blob/2.0/src/components/menu/menu.ts#L346
Missing additional check that current menu is the same and **self._isEnabled** should not became false.

**Comment by jgw96** [comment]
Hello @EugeneSnihovsky thanks for all your patience and working with me on this issue! Unfortunately, i am not sure that this is a use case that we can support since it would require integral changes to how the sidemenu works that could break other use cases. Thanks for using Ionic and sorry for any trouble this causes you.

**Comment by EugeneSnihovsky** [comment]
That's too bad. Almost all standard projects has menu for navigation. And many people has faced this issue.

Maybe it will be helpful for others. I found solutions with dirty timeout hack for now. We need a delay for previous menu has had time to disappear. So in html we add *ngIf to menu instance and [disabled] to button, that open our menu

```html
<ion-header #content>
    <ion-navbar>
        <button menuToggle end [disabled]="!hackDelayed">
            <ion-icon name="menu"></ion-icon>
        </button>

        <ion-title>
            {{title}}
        </ion-title>
    </ion-navbar>
</ion-header>

<ion-menu side="right" [content]="content" *ngIf="hackDelayed">
    <ion-toolbar class="ion-menu-logo">
        <ion-title>Menu</ion-title>
    </ion-toolbar>

    <ion-content>
        <ion-list>
            <button class="ion-menu-button"
                    ion-item
                    menuClose
                    (click)="openPage('calculator')">
                <ion-icon item-left name="ios-cash-outline"></ion-icon>
                <span>Calculator</span>
            </button>
        </ion-list>
    </ion-content>
</ion-menu>
```
And in navbar component (or page component if you copy/paste menu in each page) implement ngOnInit method with hack timeout
```typescript
import {IONIC_DIRECTIVES} from 'ionic-angular/config/directives';
import {NavController} from 'ionic-angular';
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'top-navbar',
    templateUrl: 'build/components/navigation/top-navbar/top-navbar.html',
    directives: [IONIC_DIRECTIVES]
})

export class TopNavBarComponent implements OnInit{
    public hackDelayed: boolean = false;

    ngOnInit() {
        setTimeout(() => {this.hackDelayed = true;}, 1000); // hack for menu work on each page
    }

    constructor(
        private navCtrl: NavController
    ) { }
}

```
