### ISSUE TITLE
Ionic 2 - Only iOS : Click on ion-list item is not handled after page is popped from navigation stack

### ISSUE THREAD

**Issue by gorancn** [driftyco/ionic#6996]
#### Short description of the problem:
I have a list of items as first page and when one item is clicked then page with item details is pushed to navigation stack. When user goes back from details page to list view and again click on an item in the list in some cases(if he clicked within 1-2sec after list view is shown) click on an item is not handled/fired. 

This issue is bit more noticeable after redesigning my app and making list items more complex. I've tested ionic-conference-app and I was able to reproduce same issue if I click fast enough on list item after I navigate back from session details.

#### What behavior are you expecting?
It is expected that click on list item is handled after page is rendered on screen.

**Steps to reproduce:**
1. Open iOS Ionic Conference App 
2. Open one Session details
3. Go Back 
4. Click immediately on same Session once again

**Which Ionic Version?** v2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So the reason this is happening is because our click blocker blocks any interaction until a transition is completely done. We are constantly tweaking this, and actually we are making some changes with this as we speak for another issue. I would urge you to try again in our next release and see if it has gotten more responsive for you. Thanks for using Ionic! I will be closing this issue for now, but if you have any more issues feel free to comment and I will happily reopen.

**Comment by brannpark** [comment]
@jgw96 Is this issue resolved? I have the same problem with Ionic beta.11. If not.. could you tell me some tips for bypassing this problem or what version of Ionic will resolve this?

**Comment by TStrauch** [comment]
This issue is still present in the RC.0
I am using the exact code from ionic docs, attach a click-handler to each ion-item and push a blank page onto the stack when an item is clicked.

**Comment by fernandonogueira** [comment]
This issue is still present in the RC.1

As @TStrauch, I am using the exact code from ionic docs, attach a click-handler to each ion-item and push a blank page onto the stack when an item is clicked.

**Comment by TStrauch** [comment]
I was able to resolve this on my end. 

The Ionic docs says about ion-item: "The attribute [`ion-item`](https://ionicframework.com/docs/v2/api/components/item/Item/) should be added to a <button> when the item can be clicked or tapped." 
The corresponding code would look like this: `<button ion-item (click)="buttonClick()">Button Item</button>`

However I only took a look at the [`ion-list`](https://ionicframework.com/docs/v2/components/#list-lines) doc (https://ionicframework.com/docs/v2/components/#list-lines) which does not mention the special handling of ion-item in different usage scenarios.

**Comment by FeoSilva** [comment]
+1
