### ISSUE TITLE
bug: Modal can't be dismissed after Loading

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic#6997]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Steps to reproduce:
1) Create a modal and present it using `nav.presend(MyModal)`
2) Show Loading Component while Modal is open: `nav.present(myLoading)`
3) Dismiss loading using `myLoading.dismiss()`
4) Try to close modal using: `this.viewController.dismiss()`
=> Modal won't dismiss

Expected behavior:
=> Modal will close as it does when no Loading Component is presented before.

See my plunkr as an example:
https://run.plnkr.co/plunks/3gb0ft/</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. I made a plunker [here](https://plnkr.co/edit/HXeLc1?p=preview) that shows the correct way to do this. As you can see im taking advantage of the `onDismiss()` event of the loading component to close the modal after the loading component has completely closed. Thanks for using Ionic!
