### ISSUE TITLE
Ionic 2 Alert Warning

### ISSUE THREAD

**Issue by glentonvr** [driftyco/ionic#6998]
I get the following warning when I open up an Alert - **ngSwitchWhen is deprecated and will be removed. Use *ngSwitchCase instead**

The issue is that as a result of this warning it seems none of the event listeners are working and I also cannot get the Alert to dismiss programmatically. If anyone could help that would be really awesome! Please find my code below:

```
openAlert() {
let prompt = Alert.create({
title: 'Test',
message: "Test",
inputs: [
{
name: 'name',
placeholder: 'Name'
},
],
enableBackdropDismiss:true,
buttons: [
{
text: 'Cancel',
handler: data => {
console.log('cancelled');
}
},
{
text: 'Continue',
handler: data => {
console.log('continue');
}
}
]
});
this._navController.present(prompt);
}
```

Here is some additional info

**Your system information:**

6.2.0

Ionic Framework Version: 2.0.0-beta.9

Ionic CLI Version: 2.0.0-beta.30

Ionic App Lib Version: 2.0.0-beta.16

Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind looking in your node_modules and seeing which version of Angular 2 you have installed? You should be able to see in the package.json of Angular 2. Thanks for using Ionic!

**Comment by glentonvr** [comment]
Apologies for excluding this info. Thanks for your assistance
```
{
  "dependencies": {
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router": "^2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.9",
    "ionic-native": "1.2.4",
    "ionicons": "3.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "^1.1.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "run-sequence": "1.1.5"
  },
  "name": "uureto",
  "description": "uureto: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```

**Comment by jgw96** [comment]
Would you mind changing all the `@angular` dependencies to `2.0.0-rc.1` instead of `^2.0.0-rc.1`, deleting your `node_modules` folder and then running `npm install`? Since we used to use carets in our package.json it would install the newest version of Angular (Angular 2.0.0-rc.2) instead of the one specified. This means that the Angular version you have installed is actually not the one we built ionic 2 beta.9 for, so you may run into issues until the next release when we update to rc.2. We have recently changed this, so if you start a new ionic 2 project you should not have this same issue.

**Comment by glentonvr** [comment]
After following your instructions I now do not get the warning mentioned. That said, the console.log() is still not triggering when I hit the alert buttons. Could this be due to me running rc.1? 

How would I be able to upgrade my current project to the latest version?

**Comment by jgw96** [comment]
@glentonvr would you be able to make a plunker that shows that issue please? Also, you should not upgrade your Angular dependencies yourself as each release we make is built to work specifically with a certain version of Angular 2. While you may be able to upgrade the version of Angular and not run into any issues, as you can see from the issue we just fixed it can cause issues. When ionic 2 beta.10 comes out we should be on Angular 2 rc2.

**Comment by glentonvr** [comment]
After making the example for you I worked out that the alert is in fact working as expected now. The problem now is that I am opening the alert from an action sheet button event with "this.openAlert()" it stops listening to events. If I open the alert from a button it works normally. 

I will need to scratch around and figure out why that is. Many thanks for all your assistance.
