### ISSUE TITLE
Virtual Scroll Not Filling Entire Space

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#6999]
In V2, when I use virtual scroll in the [ionic-image-gallery-app](https://github.com/driftyco/ionic-image-gallery-app/blob/master/app/pages/gallery/GalleryPage.ts#L23), it does not fill all of the provided space with "cells".

See the screenshot for a visual reference.

Basically, the virtual-scroll container has access to the entire screen.  It is not utilizing it by default.  Once I scroll, it does begin using it.

**Before Scrolling**
![screen shot 2016-06-21 at 12 32 57 pm](https://cloud.githubusercontent.com/assets/4680488/16239845/63af7ed4-37ac-11e6-805e-26a2b9052593.png)

**After Scrolling a few px**

![screen shot 2016-06-21 at 12 33 50 pm](https://cloud.githubusercontent.com/assets/4680488/16239844/63aed7e0-37ac-11e6-9d30-fd94e1373413.png)

Thanks,
Dan

**Comment by fmsouza** [comment]
I'm also having this issue in a view with 2 virtual scrolls: recent searches and available lines. When I first load it, it gives me a blank space in the beginning of the list. If I click in the `search` button in the navbar, the recents pane is hidden and the 'available lines' VS becomes ok. When I toggle search back and the first scroll appears again, the 'available lines' VS stays ok.

![untitled](https://cloud.githubusercontent.com/assets/1396615/16247431/10b413a0-37e0-11e6-877c-a86a69434060.png)

**Comment by mpaland** [comment]
Is related to #6766

**Comment by fmsouza** [comment]
@mpaland actually my issue is not the same as the one you mentioned. I've inspected the element in the browser, and it seems to be applying a CSS rule `transform: transform3d(0, ..., 0);` in all list elements, and they are always around 200px more distant from where they should be.

I also noticed that the list is built using this transform3d rule and with `position` rule different from `relative` instead of presenting it as a common list. So each element is moved down by the css rule... Very weird.

**Comment by ghenry22** [comment]
I notice very similar behavior on virtualscroll lists.  They will fill the viewport initially, scroll down quickly and when the scroll stops only part of the view will be occupied until your scroll 1 or 2 px further then the full space is used.

**Comment by InfinityOne** [comment]
@danbucholtz how u managed to make the virtualScroll with multiple elements on a line?

**Comment by ghenry22** [comment]
The repeating virtual item is a col inside a row with the wrap parameter  set which is part of a grid.  I believe that's right anyway

**Comment by InfinityOne** [comment]
@danbucholtz you can try to increase the `bufferRatio` of the `virtualScroll` to 3-4, this will create some more DOM elements and will fill the viewport from the beginning.

**Comment by danbucholtz** [comment]
@InfinityOne, Virtual Scroll will try to fill the entire space available.  Our items are small (images), so it just automatically does it.

Thanks,
Dan

**Comment by fdelayen** [comment]
It looks like this issue is making the virtual scroll to be really buggy on ios. Sometimes there are blanks at the top, or middle or even sometimes everything is blank...
Relying on Virtual scroll for our app makes it unusable on ios.
Do you have plans to update this issue soon ?
Thanks !
