### ISSUE TITLE
Modal in 2.0.0-beta.9 no longer adds page class name to ion-page element

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#7000]
The element has a class attribute with a generated classname like "user-login" if the page class is named "UserLogin". This is no longer the case for modals.

see #6606

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jasonwaters** [comment]
Hi @jgw96, I took a closer look and here's what I found:

In ionic-angular@2.0.0-beta.8, there is an `ion-page` element with the corresponding css classname of the javascript component.  I use this to add custom styles like so:

![screen_shot_2016-06-21_at_1_12_17_pm](https://cloud.githubusercontent.com/assets/427213/16243108/f1deb3c2-37b2-11e6-8754-6e433def2620.png)

But in beta.9, the `ion-page` has been replaced with `ion-modal-inner`.  That's fine, but can we add the css classname for the javascript element to that element?  That will prevent my styles from breaking all over the place.

![screen_shot_2016-06-21_at_1_14_51_pm](https://cloud.githubusercontent.com/assets/427213/16243218/625c1284-37b3-11e6-8086-610fe441b083.png)

**Comment by jgw96** [comment]
Thanks for the info! If im not thinking wrong this was part of the change when we added inset modals on bigger screens. I will discuss this with my teammates and see what they think.

**Comment by brandyscarney** [comment]
Thanks for the issue! This was actually changed recently to use `ion-page` again, but it was adding the class as PascalCase. I've fixed it for the beta 10 release and created a nightly if you'd like to test it out:

```
npm install --save  ionic-angular@2.0.0-beta.9-201606212210
```

Thanks again! :smile:

**Comment by jasonwaters** [comment]
Thanks @brandyscarney!  I tried out the nightly but it looks like there's a problem with `ion-navbar` not showing up now.  I'm going to stick with beta.8 until 10 comes out. 😀

**Comment by brandyscarney** [comment]
@jasonwaters Oh yes we've changed a bit of the structure. We'll have some steps to upgrade to beta 10 in the changelog! 😊

**Comment by michael-brade** [comment]
@brandyscarney Heh, the code didn't take long to disappear again I guess. On Jun 28, this commit https://github.com/driftyco/ionic/commit/215c6d846c6eb157b4510e63d863d2fdcf13b9af#diff-7b81c66d6f3e9c4b82c40ee5ecd30e50 
deleted your fix (in fact, the whole `loadComponent` function), and now with Ionic 2 RC0 we are back to no class name in a modal. Would you mind adding it again? :blush:
