### ISSUE TITLE
Enhancement: Use all available space for title on iOS

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7002]
#### Short description of the problem:
The title are often truncated when there's space on the right for them.

![capture d ecran 2016-06-21 a 15 21 57](https://cloud.githubusercontent.com/assets/15067923/16243211/212ade56-37c4-11e6-8679-97909f3c3a00.png)

#### What behavior are you expecting?
The title to fill the whole space (minus the margin).

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
The solution could simply be a class like `no-button-right` which could then widen the div.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment]
Thanks for the issue! This is something we plan on handling in this issue: https://github.com/driftyco/ionic/issues/5036. :smile:
