### ISSUE TITLE
The v2 Blank template needs to be trimmed

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#7003]
#### Short description of the problem:
Typically, a "Blank" template will contain the bare minimum code required for a project. But the Blank template for Ionic V2 contains two pages. One page makes sense, but two pages is kind of defeating the purpose of having it be 'blank'. 

#### What behavior are you expecting?

A simpler, more, well, blank, application. I have to remove a page now and remove code to handle loading the second page.

**Steps to reproduce:**
1. ionic start -v -ts -t blank somename

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by mlynch** [comment]
Hey @cfjedimaster, just cleaned up the blank starter for ya! Should be a lot simpler now. 🍻 

https://github.com/driftyco/ionic2-starter-blank
