### ISSUE TITLE
v1.3.* not released on NPM

### ISSUE THREAD

**Issue by bramski** [driftyco/ionic#7004]
#### Short description of the problem:
Neither v.1.3.0 nor v.1.3.1 has been released to NPM

#### What behavior are you expecting?
Expecting to get latest stable installed and available via npmjs.org

**Steps to reproduce:**
1.x series is published by @mlynch as ionic-sdk: https://www.npmjs.com/package/ionic-sdk
Last published version was 1.2.4

Please publish the latest 1.3.x to npm.  Thanks!

**Comment by danbucholtz** [comment]
Hi @bramski,

Please run `npm install ionic-angular@1.3.1` to access the 1.3.1 release on npm.

Please let me know if you have any additional questions.

Thanks,
Dan
