### ISSUE TITLE
Refresher conflicts with Menu

### ISSUE THREAD

**Issue by InfinityOne** [driftyco/ionic#7011]
#### Short description of the problem:

There is a clear conflict between ```refresher``` and ```sidemenu```.
Happens on both Material Design & iOS style
See video below, (don't know are videos allowed, cuz everybody are posting gifs)

[![ionic2 sidemenu an refresher conflict](http://img.youtube.com/vi/WESYKN-usOQ/0.jpg)](http://www.youtube.com/watch?v=WESYKN-usOQ)

#### What behavior are you expecting?

Pulling the ```menu``` by swipe should not trigger the ```refresher```

**Which Ionic Version?** 2.x -> 2.0.0-beta.9

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 0.4.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.2.1

**Comment by ghenry22** [comment]
this may be similar to where swiping down to scroll a list now triggers refresher incorrectly also

**Comment by manucorporat** [comment]
@InfinityOne @ghenry22 I will look into this
