### ISSUE TITLE
Scroll doesn't work with tap event (v2)

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic#7012]
with the following code scrolling works: 
```
<ion-list>
     <div tappable (click)="openPage()"></div>
</ion-list>
```
when I change the event to tap, scrolling doesn't work.
```
<ion-list>
     <div tappable (tap)="openPage()"></div>
</ion-list>
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by sfabriece** [comment]
I'm finding it hard to reproduce in plunker because of lack of gestures. What happens when running on a device is that a fling down doesn't work with tap event.

**Comment by jeromeXoo** [comment]
Hi,

Same as https://github.com/driftyco/ionic/issues/6897

**Comment by jgw96** [comment]
Hello! I will be closing this issue as a duplicate of #6897 Thanks for using Ionic!
