### ISSUE TITLE
Icon and Splash Screen Image Generation - Declare output directory manually

### ISSUE THREAD

**Issue by MatthiasDebaere** [driftyco/ionic#7014]
#### Short description of the problem:
I would like to choose the output directory of the icon and splash screen images myself.

#### What behavior are you expecting?
Could we expand the cli command? Something like:

```
$ ionic resources --icon --destination /my/directory/icons/
```

**Ionic Version:** 1.x 

Thanks for the help and for an awesome framework.

**Comment by Manduro** [comment]
This belongs in the Ionic CLI repo ;)
https://github.com/driftyco/ionic-cli
