### ISSUE TITLE
Bad z-index between Alerts and menu

### ISSUE THREAD

**Issue by SebastianGiro** [driftyco/ionic#7017]
#### Short description of the problem:
When an alert is triggered, and the side menu is open, the alert shows behind the side menu.

#### What behavior are you expecting?
When i trigger the alert with the menu open, the alert will show in front of all (superior z-index)

**Steps to reproduce:**
1. Create a side menu when a ion-item
2. Bind click of the ion-item with an alert
3. Open side menu and click the ion-item

Please see the plunker and just click in the navbar, will open the side menu,
then click in the item of the side-menu and see how the alert shows behind the menu

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 I think the problem is with the display flex breaking the z-index

**Which Ionic Version?** 1.x or 2.x
2.0 beta9

#### Plunker
You can test this here
http://plnkr.co/edit/wgyEsyic58cLs4dbyvRX?p=preview

**Comment by manucorporat** [comment]
Thanks for reporting the issue! I will look into it tomorrow.

**Comment by manucorporat** [comment]
@SebastianGiro fixed! @adamdbradley refactored the whole overlay system!

<img width="393" alt="screen shot 2016-06-29 at 20 32 06" src="https://cloud.githubusercontent.com/assets/127379/16464028/a91471e0-3e38-11e6-8b01-2b010d8bde28.png">

**Comment by SebastianGiro** [comment]
Nice!
