### ISSUE TITLE
(demos) ionic 2 config demo uses deprecated @App decorator

### ISSUE THREAD

**Issue by eddhannay** [driftyco/ionic#7019]
#### Short description of the problem:
The [ionic 2 configuration demo](https://github.com/driftyco/ionic/blob/2.0/demos/config/main.html#L50-L55) is intended to show a user how to make changes to the layout of their application. The example output uses the old `@App` decorator syntax with the configuration passed in, which was deprecated [in beta 8](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta8-2016-06-06).

Docs for passing Config in to ionicBootstrap: [config/Config](http://ionicframework.com/docs/v2/api/config/Config/)

#### What behavior are you expecting?
Documentation should be updated to reflect current API. 

I would create a PR, but it's not obvious what the best way to update the documentation would be - maybe just a note that this should be passed in to the `ionicBootstrap` call?

**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! I've pushed a fix for this so it should be live on the site soon. :smile:
