### ISSUE TITLE
Back button missing when popping modal then pushing page

### ISSUE THREAD

**Issue by andersfa87** [driftyco/ionic#7023]
#### Short description of the problem:
We have a modal where we create an item. After creating this item we pop the modal, then push a page with the item on. Prior to beta.9 this worked fine. In beta.9 the back button is missing on the pushed page.

#### What behavior are you expecting?
I am expecting a back button on the pushed page.

**Steps to reproduce:**
1. Present a modal
2. Pop this modal, 
3. When promise is resolved, push a new page.
4. Back button is missing on pushed page

**Which Ionic Version?** 1.x or 2.x
Ionic 2 Beta.9

#### Plunker that shows an example of your issue

http://plnkr.co/edit/vEZoCfE6VylYfhL5lcKL?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello! Is this still an issue with the latest version of ionic? Thanks!

**Comment by andersfa87** [comment]
Hi,

I just updated the Plunker to beta.10, and the issue is still there.

**Comment by jgw96** [comment]
Hello @andersfa87 , i am currently looking more into this issue, but here is a plunker with a workaround in the meantime http://plnkr.co/edit/bwdlrbLyHwsWBWvvZtvJ?p=preview . Thanks!

**Comment by jgw96** [comment]
Just tested this with the latest nightly and it seems to be fixed with the new overlay component refactor. If anyone still has this issue with the latest nightly, or beta.11 once it gets released feel free to comment and i will happily reopen. Thanks for using Ionic!
