### ISSUE TITLE
docs: Environment setup

### ISSUE THREAD

**Issue by MaxDBN** [driftyco/ionic#7026]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello Ionic Team,

I recently got an existing project to my company from another team and I tried building and running it on my development environment but nothing works for me and they refuse to answer my questions. 
I really hope I'm not wasting your time and you'll try and help me.

Please refer to my StackOverflow thread:
http://stackoverflow.com/questions/37989797/ionic-development-setup-building-errors 

as I mention there, the project is in production and it's working, but I simply can't get to the same result and I'm having lots of errors. I'm 100% sure the problem is with my environment setup.

The main one is that all http requests are blocked in android and the cordova-plugin-whitelist is not working for me. The url is 100% correct and working in production. 

Thank you very much,
Max.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! The first thing i would recommend is running `cordova plugins list`, go through and remove all the plugins using `cordova plugin rm <plugin name>` and then build and try running it again. Also, if you remove the plugins, and comment out any plugin related code and it still does not work on a device, then i would suggest trying `ionic serve` to see if it works in the browser. If removing the plugins does not fix the issue then i would suggest adding this line `<access origin="*" />` to your config.xml file and testing again. This will allow all http and https requests through to your app. If all this does not work then most likely there is something wrong with the api server you are connecting too. Is the api you are connecting too the production or development api? If the app is in production can you download it from the play store and see if it works for you? Finally, i would suggest trying with multiple different devices. Thanks for using Ionic!

**Comment by MaxDBN** [comment]
@jgw96 Thank you for replying. Tried re-installing plugins, running on android and in the browser. I've tried adding `<access origin="*" />`. I know nothing is wrong with the API because it's the same as in production... What am I missing?

**Comment by jgw96** [comment]
@MaxDBN Unfortunately at this point it seems to be an issue with your local dev environment which, also unfortunately, i can't help with much and that this repo is not the proper place for. I would recommend asking for help on our forums (https://forum.ionicframework.com) as there are a ton of awesome devs on there that may be able to help debug your local environment. Thanks for using Ionic!
