### ISSUE TITLE
logo-reddit icon not displaying in tabs when not active

### ISSUE THREAD

**Issue by DrakeWitt** [driftyco/ionic#7027]
#### Short description of the problem:
I have tabIcon="logo-reddit" on one of my tabs. It works fine on the android platform but when the platform is switched to iOS either using chrome's inspector or running on a device, the reddit icon will be invisible unless it is active.

#### What behavior are you expecting?
The reddit icon to display when inactive.

**Steps to reproduce:**
1. Tabs view with tabIcon="logo-reddit"
2. Make sure tab is not active
3. View on iOS platform

```
  <ion-tab [root]="tab2Root" tabTitle="Reddit" tabIcon="logo-reddit"></ion-tab>
```
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.9

#### Plunker that shows an example of your issue
The plunker did not have any icons working at all, couldn't find the CDN location for the new icon set either. 

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment]
Thanks for the issue! This was fixed by https://github.com/driftyco/ionic/issues/6899 and it will be in the `beta 10` release. :smile:
