### ISSUE TITLE
Running ionic serve doesn't build ubuntu 14.04

### ISSUE THREAD

**Issue by jpmsegurado** [driftyco/ionic#7030]
I installed the starter tabs project, and Idk why, when I run ionic serve it doesn't build, I have to run gulp build to see the modifications. The ionic 1 works fine but the 2 doesn't.

**Comment by jgw96** [comment]
Hello! Thank you for opening an issue with us! As this is an issue with the cli and not the framework I will be moving this issue to the cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1106
