### ISSUE TITLE
ionic2 select alterOptions cssClass not Work

### ISSUE THREAD

**Issue by wenner** [driftyco/ionic#7032]
in select compnent , i set alertOptions attribute like {cssClass:"myclass"} , it not work!
and i view the code , in components/select/select.ts

line 280

      alertOptions.cssClass = 'select-action-sheet';

line 302

      if (this._multi) {
        // use checkboxes
        overlay.setCssClass('select-alert multiple-select-alert');

      } else {
        // use radio buttons
        overlay.setCssClass('select-alert single-select-alert');
      }

in the code , will override cssClass in the alterOptions

same bug like this:
#6835 Ionic 2 Alert Bug: setCssClass overrides existing css classes

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This will actually be fixed by issue #6835 so i will be closing this issue as a duplicate. Thanks for using Ionic!
