### ISSUE TITLE
bug: 'ionic g page' generates invalid page

### ISSUE THREAD

**Issue by alsbury** [driftyco/ionic#7033]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This code is what is created by the generate page command:
```
import { Component, NavParams } from '@angular/core';
import { NavController } from 'ionic-angular';
```

I had to move the NavParams to the ionic import to get things working:
```
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';
```
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I just checked our [page template](https://github.com/driftyco/ionic/blob/2.0/tooling/generators/page/page.tmpl.ts) and as i thought, we are not importing NavParams anywhere. Would you mind updating your ionic cli by running `sudo npm install -g ionic@beta` and then trying again please? Thanks for using Ionic!

**Comment by alsbury** [comment]
Hey Justin, I guess it was a version issue on my end. I thought I'd already had the latest version when I ran into that issue. Everything looks correct now.

**Comment by jgw96** [comment]
@alsbury Awesome to hear that its working for you now. Have fun using Ionic!
