### ISSUE TITLE
bug: Ionic 2: No tabs on iOS 10 beta 1

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#7034]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>10 beta 1</span>  <span ionic-webview>webview</span>

<span ionic-description>Maybe it's a little bit early to submit a bug related to iOS 10 beta 1. But I wanted to let you know, that the tab bar doesn't get displayed. There aren't any errors in Safari's web inspector or Xcode when running the app on an actual device.

Steps to reproduce:
```
$ ionic start cutePuppyPics --v2
$ cd cutePuppyPics
$ ionic serve --lab // Tabs are there
$ ionic build ios
--> Run app with Xcode 8.0 beta 1 on an iOS device with iOS 10 beta 1
```

My configuration:
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 8.0 beta Build version 8S128d
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are actually already aware of this issue and are addressing it [here](https://github.com/driftyco/ionic/issues/6901). Please feel free to comment on that issue with any info or findings you have. Thanks for using Ionic!

**Comment by billy84** [comment]
Hi @jgw96 
I got this issue as well a few days ago.
My OS version is 10.0.2
App works well in previous versions .
How can I fix this issue?

Thanks
