### ISSUE TITLE
DateTime: DateTime breaks under certain circumstances

### ISSUE THREAD

**Issue by BenjaminDieter** [driftyco/ionic#7038]
#### Short description:

The `ion-datetime` breaks under certain circumstances. ~~I haven't been able to create a working plunker yet, but I'm still working on it~~.

Here's the scenario:
I created a `DaySelectorComponent`, which displays an `ion-datetime` and two buttons (_next_ and _previous_). Once the selected date changes (either via `ion-datetime`s `ionChange` or via tapping one of the buttons) I'm emitting the newly selected date *after parsing it with momentJS* (via `@Output() ...`). Another component (the page itself) displays a toast containing the selected date. If I change the date quite often in a short time, via tapping my previous-button rapidly, and open the `ion-datetime` it looks like this:

![datetime](https://cloud.githubusercontent.com/assets/5950968/16334233/ff1e726c-39ff-11e6-9e93-efff20beb3a7.PNG)

#### Steps to reproduce
1. Open [plnkr](http://plnkr.co/edit/rnoqugNEyuhoHFOhekmm?p=preview)
2. Tap left button repeatedly
3. Tap on `ion-datetime`

#### My DaySelectorComponent (_excerpt_):
```typescript
export class DaySelectorComponent {

    @Input() startDate: Date;
    @Output() onDateChanged = new EventEmitter();
    currentDate: string;
    
    constructor() {}

    ngOnChanges(changes: {[key: string]: SimpleChange}) {
        if (changes.hasOwnProperty("startDate") && changes["startDate"].currentValue) {
            this.currentDate = moment(changes["startDate"].currentValue).format("YYYY-MM-DD");
        }
    }
    
    next(): void {
        this.currentDate = moment(this.currentDate).add("days", 1).format("YYYY-MM-DD");
        this.emit();
    }

    previous(): void {
        this.currentDate = moment(this.currentDate).add("days", -1).format("YYYY-MM-DD");
        this.emit();
    }
    
    emit(): void {
        this.onDateChanged.emit(moment(this.currentDate));
    }
}
```

***and its template:***

```html
<ion-grid no-padding>
    <ion-row no-padding>

        <ion-col width-20 text-center>
            <button clear light (click)="previous()">
                <ion-icon name="arrow-back"></ion-icon>
            </button>
        </ion-col>
        
        <ion-col width-60 text-center>
            <ion-item primary><ion-datetime displayFormat="DDDD, DD.MM.YYYY" pickerFormat="DD.MMM.YYYY" min="2005" [(ngModel)]="currentDate" (ionChange)="emit()"></ion-datetime></ion-item>
        </ion-col>
        
        <ion-col width-20 text-center>
            <button clear light (click)="next()">
                <ion-icon name="arrow-forward"></ion-icon>
            </button>            
        </ion-col>

    </ion-row>
</ion-grid>
```

#### The main component displaying the toast (_excerpt_):
```typescript
  onDateChanged(newDate: any): void {
    let toast = Toast.create({
      message: "New Date: "+newDate.format("DD.MM.YYYY"),
      duration: 750
    });

    this.nav.present(toast);
  }
```

#### Exception being thrown:
![exception](https://cloud.githubusercontent.com/assets/5950968/16334301/6401425e-3a00-11e6-941e-a025e7e363b4.PNG)

#### Output of `ionic info`:
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 8.1
Node Version: v0.12.7
```

~~I'm working on a plunker now. Just wanted to create this issue as long as I have the time to do so.~~

##### Edit:
Created a [plnkr](http://plnkr.co/edit/rnoqugNEyuhoHFOhekmm?p=preview)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately i can't seem to reproduce this issue with your plunker. Are the exact steps to reproduce just clicking the buttons to the left and right of the datetime component fast and then opening the datetime?

**Comment by BenjaminDieter** [comment]
I will record the steps necessary to reproduce the issue ASAP, probably
Monday next week.

Justin Willis <notifications@github.com> schrieb am Fr., 24. Juni 2016,
16:40:

**Comment by nikoTM** [comment]
@BenjaminDieter @jgw96 steps to reproduce: click on any of buttons, while the toast is being displayed click on datetime

**Comment by mpaland** [comment]
I can reproduce the issue with the plunkr.

**Comment by jgw96** [comment]
Happy to report that this has been fixed and will be in the beta.11 release. Thanks for using Ionic!
