### ISSUE TITLE
Modify Ionic 1 default theme with SASS using Visual Studio 2015

### ISSUE THREAD

**Issue by hofman-p** [driftyco/ionic#7039]
Hello !

I simply want to modify Ionic default themes colors (button-positive...) with the exact official colors of my group project.

I know I can use CSS to do that by modifying ionic.css, but it'd be a bit laborious.

I'd like to know how to use SASS with Ionic projects in Visual Studio ?
What is the processus ?

Thank you,

Pierre HOFMAN

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
