### ISSUE TITLE
www/build/js - unnecessary files for release

### ISSUE THREAD

**Issue by Jota2142** [driftyco/ionic#7040]
Does we really need those big files .map for release app?

I can't find a way to stop generate the `app.bundle.js.map` file, anyone can help me with that?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the ionic cli and not the framework I will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1107
