### ISSUE TITLE
Back button does not change text dynamically

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7043]
#### Short description of the problem:
I have an hot language change feature in my app. When I change the language in a tab and then go into another tab (which as some views onto its navigation stack) I see the back button in the old language.

#### What behavior are you expecting?
Seeing the back button in the correct language

**Steps to reproduce:**
1. Navigate in a tab
2. Change the language using `Config` in another tab.
3. Go back to the tab with navigation history.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

Tried to build a Plunkr for this but the back button text wouldn't change at all.
[http://plnkr.co/edit/eQTmU1K43QC2BaM3z3z3?p=preview](http://plnkr.co/edit/eQTmU1K43QC2BaM3z3z3?p=preview)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by Emeryao** [comment]
@Bouzmine 
I tried on your plunker with changing the line of your code 
`this.config.set('backButtonText', "Retour");`
the `backButtonText` does change on the second time you enter that page rather than changes immediately after clicking the button

**Comment by Bouzmine** [comment]
Thanks for fixing my Plunkr. It's the issue that I'm reporting, the back button text doesn't change dynamically. This is annoying when changing the language in one tab and then going into another tab which has its own stack.

**Comment by Emeryao** [comment]
@Bouzmine 
you can add the code below which forces the page to refresh to "get rid of" the issue temporarily :smile: 
```typescript
this.config.set('backButtonText', "Retour");
this.navController.pop({animate:false}).then(()=>{
    this.navController.push(Page1,null,{animate:false});
  });
```

**Comment by Bouzmine** [comment]
The problem is I'm in another navigation stack, so my NavController doesn't control the other tab's navigation. Is there a way to do so ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this seems to be more of a support issue of how to implement custom functionality i will be closing this issue for now, but please feel free to continue the conversation. Thanks for using Ionic!
