### ISSUE TITLE
Unable to use (touchend) event on ion-range

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7044]
I don't know if these events are of Ionic's resort but I can't use this event properly. In contrast, `mouseup` works great. It could also be fixed with an Ionic-specific event like `ionBlur` of something.

(By the way the issue template isn't working, so I can't setup a Plunker, thanks)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Sorry about the issue template, we switched the 2.0 branch over to master today and it broke the issue template. But, the good news is that i just fixed it a few minutes ago, so would you mind making a plunker for me that demonstrates this issue? Thanks for using Ionic!

**Comment by manucorporat** [comment]
Also, can you explain your use case?

**Comment by Bouzmine** [comment]
I was trying to make a precise range across a large span of available data. So, the concept was after a 1.5 seconds without movement the span becomes shorter to allow for precise selection. On `touchend`, the zoom is removed. I'm closing this because after much testing, I realize this won't work.
