### ISSUE TITLE
Weird layout when using ion-label stacked with ion-range

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7046]
#### Short description of the problem:
The layout is weird when using `<ion-label stacked>` with `<ion-range>`. I have to say that my range contains one label at both end.

#### What behavior are you expecting?
The layout to be ok.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

[http://plnkr.co/edit/HVPKPW8DomjQJS33DPFi?p=preview](http://plnkr.co/edit/HVPKPW8DomjQJS33DPFi?p=preview)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
@Bouzmine here's a possible fix: https://github.com/driftyco/ionic/pull/7050

**Comment by brandyscarney** [comment]
This will be fixed in the `beta 11` release. Thanks for the issue!
