### ISSUE TITLE
Possibility to define z-index for components with backdrops?

### ISSUE THREAD

**Issue by awe-sim** [driftyco/ionic#7048]
#### Short description of the problem:

I noticed that when the first page is pushed onto the navigation stack, its z-index is set to `100`. The next pushed page gets a z-index of `101`. If an `Alert` is presented, it will get a z-index of `102`. If the `Alert` now cancels its own dismissal and pushes another page onto the navigation stack, the latest page will get a z-index of `103` and will appear on top of the `Alert` and its backdrop.

Is there a way to specify for an `Alert` the z-index it should use?

One possible use-case could be wanting to push another page underneath the `Alert` and its backdrop.

A more probable use-case could be as follows:

I have designed a sequence of pages, each linked to the next one, kind of like a wizard. In addition, I have designed a `ProgressBar` component as well that is triggered by each page's loading and unloading events to show to the user how much the wizard has progressed. The component is animated, so when you change its `current-step` value from `1` to `2`, it smoothly animates (using CSS transitions) from having `x %` width to `2x %` width. Due to this, I need to include this component in the `app.html` page's template. Since each page will be pushed on top of the previous one, I need to hardcode the z-index of the `ProgressBar` component to something like `10000`. This allows me to show the `ProgressBar` on all pages in the wizard.

However, if I present an `Alert` somewhere in the wizard, the `ProgressBar` would appear on top of both the `Alert` and its backdrop, which obviously looks really awful.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

If there was a way to define a z-index for `Alerts` or other components, this would be neatly solved for me. I would just present an alert starting at z-index `10001`.

If there's another way to solve this issue, I would love to hear it too.
 
**Which Ionic Version?**
2.0.0-beta.9

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by awe-sim** [comment]
possibly related to [this](https://github.com/driftyco/ionic/issues/7017) issue..

**Comment by manucorporat** [comment]
@awe-sim I think this was already fixed in beta10, Alerts should always appear in top of everything. Please reopen if not :)
