### ISSUE TITLE
text-wrap not working on element inside of virtual list

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#7051]
#### Short description of the problem:

The title text in the code below doesn't get wrapped.

```
  <ion-list [virtualScroll]="myNews.data" approxItemHeight="80px">

    <ion-item *virtualItem="let item">
      <small>{{item.by}}</small><br>
      <div text-wrap>{{item.title}}</div>
      <small>{{item.time}}</small>

    </ion-item>

  </ion-list>
```
#### What behavior are you expecting?

Able to wrap the text, no matter if in virtual list or not.

**Steps to reproduce:**
1. Create virtual list
2. Add `text-wrap` attribute to the element
3. Text doesn't break in lines.

Ionic Version 2 beta9

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.9.1
```

**Comment by Jannnnnn** [comment]
as i see [text-wrap] is complete missing in typography.scss
