### ISSUE TITLE
bug: ion-slides doesn't select last slide

### ISSUE THREAD

**Issue by thyagocl** [driftyco/ionic#7054]
#### Short description of the problem:

ion-slides directive doesn't select the last slide if the slidesPerView is set to "auto" and the slides have width smaller than the container's width. In this case, the last slide doesn't reach the point at which it would be considered as the current one.
#### What behavior are you expecting?

Even if the last slide doesn't reach the final position, it should be selected if the ion-slides reach the end. The slide is correctly drawn as selected, but there's an issue in the slideTo function when normalizing slideIndex.

**Steps to reproduce:**
1. Setup an ion-slides with slidesPerView set to "auto" and loop to false.
2. Define the slides to have width smaller than the container's width. E.g.: 75%.
3. Have at least 2 slides and scroll to the last one.
4. The activeIndex will still point at the one before the last.

**Other information:**
 I have narrowed it down to this point in the slideTo function:

```
// Normalize slideIndex
for (var i = 0; i < s.slidesGrid.length; i++) {
  if (- Math.floor(translate * 100) >= Math.floor(s.slidesGrid[i] * 100)) {
    slideIndex = i;
  }
}
```

and I believe (and have tested a little) that enclosing this in a test whether the end has been reached could resolve the issue. As follows:

```
// Normalize slideIndex
if(!s.isEnd) {
  for (var i = 0; i < s.slidesGrid.length; i++) {
    if (- Math.floor(translate * 100) >= Math.floor(s.slidesGrid[i] * 100)) {
      slideIndex = i;
    }
  }
}
```

but I'm not sure if this is the best solution to the problem or if it breaks any logic or other path to this point in the code.
I'd be willing to make a PR if you consider this a good solution or evolving it in case someone believes there's a better way.

**Which Ionic Version?** 1.3.1 (haven't tested anywhere else)
#### Plunker that shows an example of your issue

http://plnkr.co/A2RGlN

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
OS: Windows 8.1
Node Version: v4.3.1

**Comment by bariza** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#118
