### ISSUE TITLE
sometimes it happens `File to import not found or unreadable: ionicons-icons `

### ISSUE THREAD

**Issue by RunningV** [driftyco/ionic#7065]
when i change scss file to a component style sometime it can build to css file sometime it happens errors at cli ` File to import not found or unreadable:`, i have no idea about it. i try to remove `node_modules` and `npm install` again it is alse the same.so it's not the node_modules problem .my sys is like this : 
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Windows 7 SP1
Node Version: v4.4.0

```
is it the windows sys problem???:persevere:

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! SInce this issue is an issue with the Ionic cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1119
