### ISSUE TITLE
ionic keyboard and ngIf work not as expected

### ISSUE THREAD

**Issue by RioV** [driftyco/ionic#7067]
#### Short description of the problem:
I have issue with:
    - Keyboard show/hide event (i'm using ionic keyboard)
    - Angular js 2 *ngIf to show/hide button in navigation bar when keyboard show/hide

Detail:
    - I'm using ionic v2 to build application. My app have 3 tab bars (like default ionic app when run command ionic start).
    - In first tab, I add 2 buttons in navigation bar using <ion-buttons> one button is "start" type, other is "end" type. The "start" type button is Cancel button. Also have <ion-input> for input value.
    - My requirement is when user tap inside <ion-input> field, keyboard will show. When keyboard show, I'm using *ngIf to show button (Cancel button). And when keyboard hide, I'll hide button.

    - Everything works fine in iOS's devices. But in Android, it works not as expected. The first time I tap <ion-input> field, button Cancel not show (keyboard show up already), then I tap outside <ion-input> field, keyboard hidden and Cance button show up, not as I expected.

#### What behavior are you expecting?
- I expect when keyboard show/hide, button Cancel is show/hide same as keyboard.

**Steps to reproduce:**
I'm commit source code into: https://github.com/RioV/ionic2Study
1. npm install
2. ionic platform add ios/android
3. build app into android device.
4. In Home tab, tab Input number field to show device's keyboard, button Cancel not show (I expected it show up)
5. Tap outside Input number field to hide keyboard, button Cancel show up.

```
https://github.com/RioV/ionic2Study
```
**Which Ionic Version?**  CLI v2.0.0-beta.32

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014 

I'm testing in 
iPhone 5s, iOS 8.4: OK
iPad mini 3, iOS 9.3.1: OK
Nesus 7, Android 5.0.2: NG

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by RioV** [comment]
For anyone need solution for issue like that, please refer: 
https://forum.ionicframework.com/t/ionic-keyboard-and-ngif-work-not-as-expected/55882. 
Solution:
http://stackoverflow.com/questions/38066124/ionic-keyboard-and-ngif-work-not-as-expected
