### ISSUE TITLE
Grey color mini button like component is showing up while first loading

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#7068]
Ionic 2.

![screenshot_2016-06-27-10-15-47](https://cloud.githubusercontent.com/assets/15922996/16368802/6222a868-3c50-11e6-9c76-74d56cdf64e3.png)

**Comment by mhartington** [comment]
Hi there! So it seems you've opened an issue but haven't provide us with the information on how to reproduce. We really need that information. Can you please post the steps. Thanks.

**Comment by jgw96** [comment]
Hello @dheran , this has been fixed for our beta.10 release. If you would like to try it out early you can install the latest ionic 2 nightly with `sudo npm install ionic-angular@nightly`. There are some very minor breaking changes in this release that we will have full upgrade instructions for but the biggest thing is that 
```
<ion-navbar *navbar>
</ion-navbar>
```
should be changed to this
```
<ion-header>
  <ion-navbar>
  </ion-navbar>
</ion-header>
```

Thanks for using Ionic!

**Comment by dheran** [comment]
@jgw96 I'm not using ion-navbar instead i'm using native toolbar. So this is not causing above issue right?

**Comment by jgw96** [comment]
@dheran nope it should be fixed for you too (: We did a refactor of our entire layout, not just the navbar. Thanks for using Ionic!
