### ISSUE TITLE
Feature request: Escaping literals in ion-datetimes displayFormat

### ISSUE THREAD

**Issue by BenjaminDieter** [driftyco/ionic#7069]
#### Short description of the problem:

I'd like to be able to escape string literals / characters in `ion-datetime`s property `displayFormat` in order to be able to control the output more flexible.
#### What behavior are you expecting?

I'd expect something like 

``` html
<ion-datetime displayFormat="d\ay DD.MM.YYYY" ... ></ion-datetime>
```

or 

``` html
<ion-datetime displayFormat="\(day)\ DD.MM.YYYY" ... ></ion-datetime>
```

to produce
`day 27.06.2016`

Another way to solve this could be transclusion:

``` html
<ion-datetime ... >
  {{DDDD}}, the {{DD}} of {{MM}}/{{YYYY}}
</ion-datetime>
```

**Which Ionic Version?** 1.x or 2.x

2

**Comment by jdddog** [comment]
That would be really handy! I need this feature too.

**Comment by triumphator** [comment]
This would come really handy!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#161

**Comment by jlebras** [comment]
@jgw96 Any news about this ? The provided link is broken.
