### ISSUE TITLE
Feature requests: Calendar weeks for ion-datetime

### ISSUE THREAD

**Issue by BenjaminDieter** [driftyco/ionic#7070]
#### Short description of the problem:

I need to display calendar weeks (according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates)), but `ion-datetime` doesn't support those.

I know you folks over there don't use calendar weeks as much as we (in Germany) do :stuck_out_tongue_winking_eye: Nevertheless I'd appreciate if I was able to use Ionics `ion-datetime`.
#### What behavior are you expecting?

I'd expect `ion-datetime` to be able to display calendar weeks.
Example:

``` html
<ion-datetime displayFormat="C\W WW / YYYY" ...></ion-datetime>
```

should display
`CW 26 / 2016`

If you're wondering why the value of `displayFormat` looks so weird, I opened another feature request at #7069 

**Which Ionic Version?** 1.x or 2.x

2

**Comment by BenjaminDieter** [comment]
I took a look at Ionics code in order to be able to prepare and create a PR and I found out why there are no calendar weeks supported. Ionic really just parses the given string, without any extra logic:

```typescript
  return {
    year: parse[1],
    month: parse[2],
    day: parse[3],
    hour: parse[4],
    minute: parse[5],
    second: parse[6],
    millisecond: parse[7],
    tzOffset: tzOffset,
  };
```

Wouldn't it be nice to return some extra information? Like isLeapYear, calendarWeek, etc.? Before I continue editing and writing code I'd like to know if you want the `parseDate()` from `src/util/datetime-util.ts` to contain extra logic.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#164
