### ISSUE TITLE
bug: email composer is not supporting android.

### ISSUE THREAD

**Issue by hanush-vijay** [driftyco/ionic#7071]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>i am using ngcordova email composer .. it works fine with ios but the function call back is not happening in android</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
