### ISSUE TITLE
feat: Custom icons won't display on actual device

### ISSUE THREAD

**Issue by cindymarie** [driftyco/ionic#7076]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I have added custom fonts. It is okay in the browser but when build and run on a mobile device, the custom icons(fonts) added are not displayed. It only displays white space.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Make sure the path of the font is relative.

**Comment by jgw96** [comment]
Hey @cindymarie would you mind filling out the issue template and posting the info here? Unfortunately with the information provided there is not much we can do. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
