### ISSUE TITLE
Support for view lifecycle hooks through decorators 

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic#7077]
#### Short description of the problem:
Currently there is no way for nested components to hook into `view` lifecycle (`willEnter`, `didEnter`, etc...). The only possible to inject `ViewController` add subscription on appropriate event and then cleanup it in `ngOnDestroy` it's a bit tedious if you will repeat this in each component.

#### What behavior are you expecting?
I suggest to provide decorators like `@ViewWillEnter`, `@ViewDidEnter` and so on, so then any method of any component can be subscribed to view lifecycle event. This decorator should add automatic subscription on corresponding method for corresponding event and automatically remove subscription when a component is destroyed. 

**Example**:
```
export class TasksList {
  @ViewWillEnter
  load() {
    return this.http.get('/tasks')
  }
}
```

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! While this is a great idea there are some implementation issues that the team discussed that just injecting `ViewController` does not have. When we implement the offline template compiler, something like this proposed api would have a big chance of breaking. Also, there is not a good way to go through nested components and "look for" these decorators. Like i said, awesome idea, but it is not something we plan on implementing at the moment. If anything changes i will happily reopen this feature request. Thanks for using Ionic!

**Comment by danbucholtz** [comment]
Hi @stalniy,

There is an easy way to do this.  However, it is not documented very well 😄 .  Duly noted, and I will update the docs ASAP.

http://ionicframework.com/docs/v2/api/components/nav/ViewController/#willEnter

If you inject a ViewController into your child component, you will get the correct/expected ViewController for the page pushed on the nav stack.

`willEnter`, `didEnter`, etc are `EventEmitters` that can be subscribed to for when these events are called.

You could do something like this...

```
let subscription = this.viewController.willEnter.subscribe( () => {
   // do my stuff here
});

Thanks,
Dan
```
