### ISSUE TITLE
bug: Loading won't dismiss in ionViewDidEnter

### ISSUE THREAD

**Issue by mnogueron** [driftyco/ionic#7078]
#### Short description of the problem:

If we create and present a Loading in ionViewDidEnter function, the loader won't dismiss unless the call to dismiss is packed in a setTimeout with a zero timeout.

#### What behavior are you expecting?

The loader should be dismissed without the help of a setTimeout.

**Steps to reproduce:**
1- Create a fresh project: `ionic start MyIonic2Project blank --v2`
2- Add this code to HomePage.ts:
```
    ionViewDidEnter(){
        let loading = Loading.create({
            content: "Wait..."
        });
        this.nav.present(loading);
        this.doSomeStuff();
        loading.dismiss();
    }

    doSomeStuff(){
        for(let i = 0; i < 10000; i++){
            console.log(i);
        }
    }
```
3- Check that the loader won't dismiss
4- Comment: `loading.dismiss();`
5- Add this instead:
```
setTimeout(
    () => {
        loading.dismiss();
    }, 0
)
```
6- Check that it's now working

**Which Ionic Version?** 
ionic: 2.0.0-beta.31
ionic-angular: 2.0.0-beta.9

#### Plunker that shows an example of your issue

**Not working plunker** - http://plnkr.co/edit/idNBx9evjmKdr4GJrSLl?p=preview
**Working plunker** - http://plnkr.co/edit/uUZbFH2iuZMWDfRQu8Mp?p=preview

#### Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v6.2.0

**Comment by danbucholtz** [comment]
Hi @mnogueron,

Navigation events are asynchronous and return promises, so there is no guarantee that the loading indicator is displayed in your example.

Take a look at the docs here for a good example:
http://ionicframework.com/docs/v2/api/components/nav/NavController/

```
ionViewDidEnter(){
        let loading = Loading.create({
            content: "Wait..."
        });
        this.nav.present(loading).then( () => {
             this.doSomeStuff();
             loading.dismiss();
        });
    }
```

**Comment by mnogueron** [comment]
Thanks @danbucholtz ! 

I missed this part of the documentation.

Matthieu
