### ISSUE TITLE
v2 icon button in toolbar with ngIf has different style

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#7083]
#### Short description of the problem:
As the title says, having a button with icon in toolbar has border, IF `ngIf` is also on the button. Without ngIf, there's also no additional styling. *Please check Plunker url below*

#### What behavior are you expecting?
The styling should be the same with ngIf or without ngIf

```
insert any relevant code between the above and below backticks
```
```
<ion-navbar *navbar>
  <ion-title>
    Ionic 2
  </ion-title>
    <ion-buttons start>
    <button 
      *ngIf="true">
      <ion-icon name="search"></ion-icon>
    </button>
    <button>
      <ion-icon name="more"></ion-icon>
    </button>
  </ion-buttons>
</ion-navbar>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta9

#### Plunker that shows an example of your issue

http://plnkr.co/edit/hjtb0kyl4Hu5jhLcDnz0?p=preview (open home.html)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.9.1
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are actually already aware of this issue and are tracking it [here](https://github.com/driftyco/ionic/issues/5927), therefore i will be closing this one as a duplicate. Please feel free to put any comments or feedback for this bug on that issue. Thanks for using Ionic!
