### ISSUE TITLE
ion-spinner style

### ISSUE THREAD

**Issue by Hufschmidt** [driftyco/ionic#7087]
# Issue

According to the [ion-spinner api-doc](http://ionicframework.com/docs/v2/api/components/spinner/Spinner/) you should be able to change the spinner color by changing stroke style via 

    ion-spinner svg {
      stroke: #444;
      fill: #222;
    }

But this does not work, since stroke (and fill) is defined on _classes_ of the form spinner-* (eg `.spinner-ios`, `.spinner-dots`, etc.) which take precedence over the above _type_ selector.

*Sidenote:* The main use-case touched by this issue is changing the style/color of a single ion-spinner, not globally. Although spinners currently seem to use fixed color values in scss instead of variables, which would be another nice addition...

**Tested with ionic2 beta9**

# Working solutions:

*Using !important*, which should be avoided as much as possible

    ion-spinner svg * {
      stroke: #00f !important;
    }

*Overwriting all spinner- classes*, which requires to have internal knowledge about ionic-angular

    .spinner-ios line,
    [...]
    .spinner-crescent circle {
      stroke: #00f;
    }
   
# Desired solution:

*Overwrite by attaching custom class to ion-spinner*.

This does currently not seem to work, because `<ion-spinner class="my-custom-blue"></ion-spinner>` for example gets transformed into `<ion-spinner _ngcontent-ykj-1="" class="spinner-crescent"></ion-spinner>`, so any custom class gets dropped...

This seems like a severe bug to me. O_O

**Comment by Hufschmidt** [comment]
# Additional notes:

The problem withe the desired solution seems similar to the following issues #6275, #6279 and #6277, so the same fix might apply here (and maybe on other components as well?).

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by Hufschmidt** [comment]
Added plunkr:
http://plnkr.co/edit/q7nsexm51CosPoxMt3qW?p=preview

Important code is in home.html (ion-spinner with class attribute) and the generated output (ion-spinner without custom class attribute, replaced by ionics spinner-*** class.

**Comment by Hufschmidt** [comment]
I've gone through the source-code and ion-spinner is the only component left with this issue, which seems to be caused by having a `[class]='some-value'` binding in the components decorator host setting.

132d8e977aa5e4f2078b945322c585c4eca7cf0d fixed this for ion-slides by using Renderer from @angular/core instead. :)

**Comment by manucorporat** [comment]
@brandyscarney I agree with @Hufschmidt , last time I tried to give a spinner my own style, it was complicated. Not sure about a solution though :)

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta 12` release. The class will no longer be clobbered, and you will be able to pass a color via the `color` input. See this file for some examples: https://github.com/driftyco/ionic/blob/master/src/components/spinner/test/colors/main.html

**Comment by sertal70** [comment]
I would suggest you to update the online documentation at [https://ionicframework.com/docs/api/components/spinner/Spinner/,](https://ionicframework.com/docs/api/components/spinner/Spinner/) because as per today it still reports that to change the spin color the `fill` and `stroke` properties must be used, no mention to the `color` property is made.
