### ISSUE TITLE
feat: Hide header while scrolling list down

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7088]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hide header while scrolling list down and show while scrolling up if fullscreen on ion-content is enable</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Duplicate of https://github.com/driftyco/ionic/issues/6690
