### ISSUE TITLE
Swipe-to-back-back breaks if you release before half way across the screen

### ISSUE THREAD

**Issue by mbrookson** [driftyco/ionic#7093]
On iOS, if you swipe to go back but let go BEFORE you have reached the mid way point (half way across the device screen), the app displays the back view, however it is completely unresponsive.

However, you can then perform the swipe-to-go-back gesture again and the page that was in view appears again and you can continue swiping back.

It is not until you do the full gesture or release AFTER the mid way point that the backwards navigation actually works.
 
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18

[forum.ionicframework.com/t/bug-with-swipe-to-go-back](https://forum.ionicframework.com/t/bug-with-swipe-to-go-back/56034)

**Comment by manucorporat** [comment]
@mbrookson I can't reproduce your issue in nightly.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
