### ISSUE TITLE
bug: ion-item-sliding problems in beta10

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#7094]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>After upgrading to v2.beta10 using ios theme, the `<ion-item-sliding>` has two big problems:

1. Using `<ion-item-sliding>` in a virtual list is extremely unresponsive and laggy. I guess event handlers from the virtual list disturb the sliding event handlers.
Using `<ion-item-sliding>` in a 'normal' list is fine!
I tested this in Edge and FF47 browser. This was okay in beta.9.

2. When the sliding buttons are open, a click on the item closed the buttons.
This is broken. Clicking on the item doesn't open the item nor closes the slider.</span>

<span is-issue-template>
```html
<ion-list [virtualScroll]="items">
  <ion-item-sliding *virtualItem="let item">
    <button ion-item detail-none (click)="onDetail(item)">
      <ion-thumbnail item-left>
        <img [src]="'item.photo" [style.height.rem]="5.6">
      </ion-thumbnail>
    </button>
    <ion-item-options>
      <button>
        <ion-icon name="text"></ion-icon>
        Test
      </button>
      <button secondary>
        <ion-icon name="call"></ion-icon>
        Call
      </button>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```
</span>

**Comment by mpaland** [comment]
The item sliding is extremely unresponsive on my real Android 6.0 device, too.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that we can use to reproduce this issue please? Thanks!

**Comment by manucorporat** [comment]
@jgw96 @mpaland don't worry I am aware of this issues. There are not easily fixable without breaking stuff

**Comment by manucorporat** [comment]
@mpaland issue 2 should be fixed! please, can you open a new issue only with the first issue?

> Using <ion-item-sliding> in a virtual list is extremely unresponsive and laggy. I guess event handlers from the virtual list disturb the sliding event handlers.
Using <ion-item-sliding> in a 'normal' list is fine!
I tested this in Edge and FF47 browser. This was okay in beta.9.
