### ISSUE TITLE
Ionic2 GeoLocation not working on real device.

### ISSUE THREAD

**Issue by nikhilknoldus** [driftyco/ionic#7096]
I'm using Ionic 2 geolocation its working fine in chrome browser (lat & long coming in browser log) but when i run this in real android device, nothing is coming.

```
    platform.ready().then(() => {
    Geolocation.getCurrentPosition().then(pos => {
              var geoData = {
                latitude: pos.coords.latitude,
                longitude: pos.coords.longitude  
              }
              var getDataIntoString = JSON.stringify(geoData);              
              localStorage.setItem('geoDataObject', getDataIntoString);
              console.log("asdfasdf" +geoData);
        
       }).catch(err =>{console.error(err)});


      StatusBar.styleDefault();
    });
```

writing this code in app.ts file.*

**Comment by mhartington** [comment]
Hmm, not able to reproduce when testing a physical device

**Comment by mhartington** [comment]
Going to close. Working on both iOS and Android

**Comment by nikhilknoldus** [comment]
This issue must not be closed, it's still not resolved. Can you send me the example that you tried and not reproducing this error ? @mhartington

**Comment by jcguarinpenaranda** [comment]
Hello, in my case I'm testing on a Motorola 2nd Gen and it's working fine, but when I send the app to some friends who have other Android cellphones it's not working ok. To be honest I don't know why. Are there any compatibility issues using the plugin for the Geolocation?

**Comment by mariohmol** [comment]
I had the same issue, in my case the user had turn off the Geolocation in his mobile.

What is weird is that he asked if the app could get your location, i answered yes and it didnt call the except or other callback.

@mhartington it might be helpfull if this plugin could detect when that happens and return a properly message so we can show to the user a correct message.

**Comment by mhartington** [comment]
You should add the [cordova-plugin-compat](https://github.com/apache/cordova-plugin-compat) or the [diagnostics](https://github.com/dpa99c/cordova-diagnostic-plugin). 

Either way, if this is something that you would like to see happen automatically, I'd  suggest bringing it up on the cordova mailing list or make a PR to the geolocation plugin, as that is the real culprit here. 

Thanks!

**Comment by mariohmol** [comment]
Thanks for answering! Seems that is a PR for that already.. looks like the same case https://github.com/apache/cordova-plugin-geolocation/pull/85

thanks!

**Comment by postor** [comment]
I ran into this problem and finally found the solution, open `Settings` app on your phone, then `Location` menu, then open `GPS`, `WLAN`  and so on

**Comment by manish29ify** [comment]
Try Background Geolocation instead of Geolocation it solved my problem
