### ISSUE TITLE
Scrollbars goes behind header/toolbars/tabs when using fullscreen property

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#7100]
When using the new fullscreen property on ion-content in beta 10, scrollbars goes behind header, toolbars and tabs.

```
<ion-header>
	<ion-navbar brand>
		<ion-title>Shop</ion-title>
	</ion-navbar>
</ion-header>

<ion-content fullscreen class="shop-page">
Long list here, that enables scrolling
</ion-content>
```

![image](https://cloud.githubusercontent.com/assets/230182/16421188/6f7c61d4-3d54-11e6-9e91-fed217287f4e.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately with UIWebView there is not currently a way to fix this issue. We are aware that it is not ideal, but we are limited by UIWebView in this situation. We are working on some cool WKWebView things that we will be able to fix this issue with though. Thanks for using Ionic!
