### ISSUE TITLE
feat: Add support for using tabs in any page

### ISSUE THREAD

**Issue by ErkoKnoll** [driftyco/ionic#7102]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>As it turns out tabs component is only meant to be used in root page which is currently undocumented and breaks the behavior in beta 10 release.
I really like the tabs look and feel and over segments and would like continue using it in pages other than the root page.
</span>

More detailed discussion: #7084 

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @ErkoKnoll after discussing this with my teammates today we have decided that we will not be supporting this for now, although it could be something we would consider in the future. If you would still like to use tabs on `non-root` pages then you should just be able to set the tabs to `position relative`. This isnt officially supported, so it would have the potential to cause other issues, but it should work for you. I would urge you to consider segments as that would be the officially supported way to get the behavior you described in #7084 . Thanks for using Ionic!
