### ISSUE TITLE
[feature request] build chain error handling

### ISSUE THREAD

**Issue by wzr1337** [driftyco/ionic#7105]
I just had an issue with code that did not compile because I wanted to assign a number to a string. Typescript did not compile. This caused to browser code I was running to remain the same. Unfortunately, I did not notice the error in the shell, because it was hidden behind the editor. 

I would strongly recommend to catch any build error, pipe it into a static page and refresh the app in the browser with just the error page. This way, developers will be immediately aware of errors, that prevent code from being actually build and refreshed in the browser. Angular.cli for examples does catch all kinds of errors and puts them on the error age they show instead of the app in case of any errors.

The errors to catch would be any kind of .ts and *.scss and so on.

Best regards

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a feature request that would be implemented by the ionic-cli and not the framework I will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1127
