### ISSUE TITLE
bug: Entering a tab page, tabs block content

### ISSUE THREAD

**Issue by chansky** [driftyco/ionic#7107]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have an app, where after a login the user gets to a page with 3 tabs. At the top of this page there is a tab bar with an icon to represent each of the tabs. I want the 2nd tab to be the one which shows up for users when they enter the tab view. I've set " ion-tabs selectedIndex="1" " which does correctly load the 2nd page which only contains `<h3>Profile</h3>`. However the word "Profile" is not visible. I noticed by adding some `<br>` to my template I was able to see "Profile". 
However clicking one of the other tabs and then clicking back to the middle tab shows the original `<h3>Profile</h3>` with no `<br>`s's necessary.

Summary: Entering a tab page where one of the tabs is preselected causes the tab bar to start with a higher z index (I'm guessing) than the page's content. However after a user starts navigating, the tab bar takes on a block property with respect to the page's content.

I hope this is clear and a bit helpful!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by chansky** [comment]
I was able to resolve the issue by removing the \<ion-content> tag from my tab page html. I wasn't able to recreate this in a plunker but the plunker example I was looking at used "Page" for pages and I have been using "Component" for my pages...
