### ISSUE TITLE
Not detecting Cordova using Ionic Deploy

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#7108]
Ionic Deploy requires `cordova.js` to be removed from `index.html`, as it gets added with the right path on start. This has always worked fine until recently.

Now, Ionic does not detect the app as being run in cordova anymore. Instead it is tagged as the `mobileweb` platform. This causes calls to cordova plugins to often fail, as the `platform.ready()` is launched on `domready` instead of `deviceready`.

When I re-add `cordova.js` to `index.html`, all is fine again.

It seems to be happening since `ionic-angular@2.0.0-beta.10`. It could also be an issue with https://github.com/driftyco/ionic-cloud

**Ionic Version**: 2.x

**Platform**: iOS (Android untested)

**Run `ionic info` from terminal/cmd prompt:**
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue with the Ionic platform and not the framework i will be moving this issue to the appropriate repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud#12
