### ISSUE TITLE
ionic2 beta 10 bug, when tabs set preloadTabs="true"

### ISSUE THREAD

**Issue by fuhongbo** [driftyco/ionic#7109]
If set preloadtabs is true, it will get a error message is "undefined is not an object (evaluating 'scrollEle.style')"

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!
