### ISSUE TITLE
infinite scroll fails to stop firing on-infinite-scroll event when no more content is generated

### ISSUE THREAD

**Issue by shuai-zh** [driftyco/ionic#711]
I wanted to use the latest ionic infinite scroll feature in my app after looking at the sample codes here:http://codepen.io/elm/pen/Becqp

However, after I actually put them into my app, it doesn't work well when no new data is returning from the server and no more new content is generated. I simulated the problem here:http://codepen.io/chocstarfish/pen/hBysf, as you can keep scolling until the number reaches 19, open your dev console to see that the loadMore function is kept being called.

What's more, I don't know why the spinning icon which used to show up when the on-infinite-scroll event is triggered seems to be lost.

**Comment by ravimyswaasth** [comment]
Duplicate of #13863 

- [ ] 

- 1.
