### ISSUE TITLE
'ionic resources' generating empty directories with no icon and splash images

### ISSUE THREAD

**Issue by saqueib** [driftyco/ionic#7111]
I am trying to generate icon and splash using `ionic resources` command but it's giving me empty directories every time.

so I tried using `ionic resources --icon` which generated icons, but same with `--splash` is still not giving any splash screens.

```
My system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.5
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by laurentf** [comment]
same problem here.. any idea?

**Comment by BergkampHUN** [comment]
The sample.psd is too big. Try to reduce the image size to 2208x2208.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the ionic-cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1133
