### ISSUE TITLE
Content component should provide info about a top position of scrollable content

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#7112]
#### Short description of the problem:

I have a custom component for sticky headers which pins a header to a top of `ion-content`. 
After migration to beta-10, `ion-content` adds a top padding for `ion-header` and tabs which breaks my sticky headers. I have to use a private `Content.adjustedTop` field to fix calculations of sticky header's position.

#### What behavior are you expecting?

A way to obtain `adjustedTop` via a public interface of `Content` component.

**Which Ionic Version?**
2.x (2.0.0-beta.10)

#### Plunker that shows an example of your issue

http://plnkr.co/edit/uJ56fmar7yJ5staVj0OX?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by mnasyrov** [comment]
Sure, here it is: http://plnkr.co/edit/uJ56fmar7yJ5staVj0OX?p=preview

**Comment by adamdbradley** [comment]
The properties should be public in TypeScript's eyes, so it should work now. However, `@private` was there in place of documentation, but I've since added a description. Also, the properties have been renamed to `contentTop` and `contentBottom`, which will be in beta``.
