### ISSUE TITLE
VirtualScroll issues

### ISSUE THREAD

**Issue by oktav777** [driftyco/ionic#7113]
#### Short description of the problem:

Again virtualScroll :D

See the plunker bellow. At the begging the container of `virtualScroll` has 0 height, all items are in one line overlapping each other. If you go to inspect element and set height manually in pixels to the container, then scroll a bit the `virtualScroll`, it seems to work, its setting already the correct calculated height. But there is another problem, it is showing 3 elements per line instead of 4(see the css file in plunker). I have calculated manually, and there is place for the 4th element in line, but virtualScroll places only 3 per line. Is there maybe a problem that calculated width in pixels for items is not integer?

And also when I was creating the markup for my project, I observed if I set some css styles to container or item, the `virtualScroll` don't want to work, container has 0 height and no items inside it. Is this a known issue or I have to present an example for this?

**Which Ionic Version?**  2.x beta10
#### Plunker that shows an example of your issue

http://plnkr.co/edit/HW9JTZUUEfI9pqnr2htv?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Is this still an issue with rc4 ?

**Comment by InfinityOne** [comment]
@jgw96 Hello! Sorry, but I'm not working with Ionic for a long time, and I can't test it at the moment.
