### ISSUE TITLE
Ionic2 html dimmension bug with cordova-plugin-screen-orientation

### ISSUE THREAD

**Issue by cinkonaap** [driftyco/ionic#7114]
#### Short description of the problem:

I know this could be not on Ionic side, but I feel like it can be something going on here. Basically I am creating Ionic2 app, and I want to lock and change screen orientation at runtime. Plugin methods work fine, but when I change orientation from `portrait` to `landscape`, and then change it back to `portrait`, `HTML` dimensions does not recalculate (whole app takes about 40% width of screen).

I do not override any `html`,  `body`, `ion-app` or `ion-page` tags styles. 

#### What behavior are you expecting?

HTML dimensions recalculates after changing orientation using `cordova-plugin-screen-orientation`.

**Steps to reproduce:**
1. https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/98#issuecomment-207678180

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

* Apache bug issue: 
https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/98 and https://issues.apache.org/jira/browse/CB-11359

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.0
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! After doing some reading on this it seems to be a cordova issue and not an ionic issue. Thanks for bringing this but to our attention, i will definitely be keeping up with it. Because of this being a cordova issue, i will be closing this issue for now. Thanks for using Ionic!
