### ISSUE TITLE
Async pixel transfers not supported

### ISSUE THREAD

**Issue by elineopsommer** [driftyco/ionic#7115]
#### Short description of the problem:
Weird behaviour + errors in log: [INFO:async_pixel_transfer_manager_android.cc(60)] Async pixel transfers not supported

#### What behavior are you expecting?
Tutorial app working like expected

**Steps to reproduce:**
1. install genymotion and start virtual device Samsung Galaxy S4 - 4.4.4 - API 19
2. ionic start MyIonic2Project tutorial --v2
3. cd MyIonic2Project
4. ionic run android

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I keep getting these errors
 06-29 04:57:38.745 I/chromium( 4093): [INFO:async_pixel_transfer_manager_android.cc(60)] Async pixel transfers not supported
06-29 04:57:38.749 D/AndroidRuntime( 4184): Calling main entry com.android.commands.pm.Pm
06-29 04:57:38.753 D/AndroidRuntime( 4186): Calling main entry com.android.commands.pm.Pm
06-29 04:57:38.761 E/chromium( 4093): [ERROR:gles2_cmd_decoder_autogen.h(1082)] [GroupMarkerNotSet(crbug.com/242999)!:087593B9]GL ERROR :GL_INVALID_OPERATION : GetIntegerv: <- error from previous GL command
06-29 04:57:38.785 I/chromium( 4093): [INFO:async_pixel_transfer_manager_android.cc(60)] Async pixel transfers not supported
06-29 04:57:38.801 E/chromium( 4093): [ERROR:gles2_cmd_decoder_autogen.h(1082)] [GroupMarkerNotSet(crbug.com/242999)!:786097B9]GL ERROR :GL_INVALID_OPERATION : GetIntegerv: <- error from previous GL command

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying on the regular Android emulator? I am currently testing with a Nexus 4 emulator running Android 4.4.4 and am not running into this issue.

**Comment by elineopsommer** [comment]
It is a problem on the samsung galaxy, with nexus it runs fine.

---- Justin Willis schreef ----

Hello, thanks for using Ionic! Would you mind trying on the regular Android emulator? I am currently testing with a Nexus 4 emulator running Android 4.4.4 and am not running into this issue.

---

**Comment by jgw96** [comment]
Ahhh ok, so this is probably related to the samsung webview that the s4 uses. Would you mind testing with a newer samsung device and seeing if it has the same issue? Thanks!

**Comment by elineopsommer** [comment]
@jgw96 Same problem on an samsung galaxy S5..

**Comment by jgw96** [comment]
@elineopsommer this is with genymotion or an actual device?

**Comment by elineopsommer** [comment]
Galaxy s4 is an real device, the others is with genymotion..

---- Justin Willis schreef ----

@elineopsommer this is with genymotion or an actual device?

---

**Comment by jgw96** [comment]
Hello, so after discussing this with my teammates we are going to recommend that you use crosswalk with your app. Crosswalk gives you a modern chrome webview that gives you awesome performance, html5 support and ES6 support right out of the box, even on an S4! The older samsung devices have a samsung modified, outdated android webview that seems to have alot of bugs. If you would like to use crosswalk with your app you can learn how to add it [here](http://ionicframework.com/docs/cli/browsers.html) . Thanks for using Ionic!
