### ISSUE TITLE
bug: ion-item-sliding laggy in virtual scroll list

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#7116]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x beta.10</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>@manucorporat wrote

> please, can you open a new issue only with the first issue?

This is related to #7094

In my test app and on Android I'm seeing always the effect. It seems to be related to the number of items in the virtual scroll list. More items - more lagged.

It's a bit tricky to reproduce it, I don't know why yet.
However, here's a test plunker: http://plnkr.co/edit/Q7GK0JLyp5BFudppLDtt
Open the plunker in **separate preview mode** in Edge browser.</span>

<span is-issue-template></span>

**Comment by adamdbradley** [comment]
Reported in #8744 that his issue has been has been fixed.
