### ISSUE TITLE
[ionic2] ionic package build android - Invalid transformation: invalid width: 2732 (CLI v2.0.0-beta.28)

### ISSUE THREAD

**Issue by pawsaw** [driftyco/ionic#7118]
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.28
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014 

```
$ ionic package build android
The resources folder already exists. We will not overwrite your files unless you pass the --force argument.
Running with the force flag will overwrite your resources directory and modify your config.xml file
Preparing your resources...

Invalid transformation: invalid width: 2732 (CLI v2.0.0-beta.28)
```

The width 2732 is the pixel size of the splash.png in the resources folder.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the ionic cli and not the framework i will be moving this issue to the ionic cli repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1134
