### ISSUE TITLE
While swiping to go back, vertical scrolling possible

### ISSUE THREAD

**Issue by F1ow** [driftyco/ionic#7120]
#### Short description of the problem:
When I swipe to go back, I can also swipe vertically and either the active or the new page scrolls. This happens only if the content is long enough, so there is something to scroll. 

#### What behavior are you expecting?
While horizontally swiping to go back the vertical touch events should be ignored. At least scrolling should be disabled. This default behavior in iOS. Try this in the settings app on an iPhone.

**Steps to reproduce:**
1. Navigate to a detail page
2. Swipe to go back
3. During swiping try to swipe vertically.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Already discussed in slack channel, for specific case with ion-refresher.
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

#### Github Repo that shows an example of your issue
https://github.com/F1ow/ionic-swipe-to-go-back

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by manucorporat** [comment]
We are aware of this issue, #7075.

**Comment by romanrast** [comment]
Ionic 2 rc3 still lets you vertical scroll when swipe back. Ionic1 used to lock vertical scrolling when swiping back (can't remember which version) and that made it feel more native. Looking at ionic apps now I'm able to tell right away if it's native or ionic just by checking if there's a vertical scroll on swipe back. So I think this should be fixed for better ux and for a more native look and feel.

**Comment by MikeMilian** [comment]
In the Ionic Conference App (Ionic 2 RC4) in the config.xml if found the solution. I copied the last couple lines. And now it won't vertical scroll when swipe back

`<preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="StatusBarStyle" value="default" />
  <preference name="SplashScreen" value="screen"/>
  <preference name="orientation" value="portrait"/>
  <preference name="SplashMaintainAspectRatio" value="true"/>
  <preference name="FadeSplashScreenDuration" value="300"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="AutoHideSplashScreen" value="false"/>
  <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <feature name="CDVWKWebViewEngine">
    <param name="ios-package" value="CDVWKWebViewEngine"/>
  </feature>
  <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0"/>
  <plugin name="cordova-plugin-wkwebview-engine" spec="https://github.com/driftyco/cordova-plugin-wkwebview-engine.git"/>
  <plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
  <plugin name="cordova-plugin-whitelist" spec="1.3.1"/>
  <plugin name="cordova-plugin-console" spec="1.0.5"/>
  <plugin name="cordova-plugin-statusbar" spec="2.2.1"/>
  <plugin name="cordova-plugin-device" spec="1.1.4"/>
  <plugin name="cordova-plugin-crosswalk-webview" spec="~2.2.0">
    <variable name="XWALK_VERSION" value="22+"/>
    <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+"/>
    <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect"/>
    <variable name="XWALK_MODE" value="embedded"/>
    <variable name="XWALK_MULTIPLEAPK" value="true"/>
  </plugin>
  <plugin name="cordova-plugin-splashscreen" spec="~4.0.1"/>
  <engine name="ios" spec="4.3.1"/>
  <engine name="android" spec="6.1.0"/>
  <icon src="resources/android/icon/drawable-xhdpi-icon.png"/>`

**Comment by RikdeVos** [comment]
@MikeMilian that doesn't work for me unfortunately. Which lines did you copy? Also I see that it's using the cordova crosswalk webview plugin which has some downsides.
