### ISSUE TITLE
Feature request: Progress bar / Loading Bar ionic2

### ISSUE THREAD

**Issue by lordgreg** [driftyco/ionic#7123]
#### Short description of the problem:
Ionic2 already has Loading methods and functionality. However, there's always option for improvement. That's why I would like to see Horizontal loading bar aka Progress bar, something like [Angular Material2 has](https://www.npmjs.com/package/@angular2-material/progress-bar). Or something we used in ionic1 projects using (ngProgress plugin)[https://github.com/VictorBjelkholm/ngProgress]

**Which Ionic Version?** 1.x or 2.x
Ionic 2

**Comment by manucorporat** [comment]
Duplicated of https://github.com/driftyco/ionic/issues/6669
