### ISSUE TITLE
Back button will not show up if you do not specify a class for the nav bar

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic#7124]
#### Short description of the problem:

Given a simple nav bar:

```
<ion-nav-bar>
      <ion-nav-back-button>Back</ion-nav-back-button>
</ion-nav-bar>
```

The back button will not show automatically if you specify a class.
#### What behavior are you expecting?

It should work whether I specify a class or not. 

**Which Ionic Version?** 1.x or 2.x
1.x

Here is a CodePen showing the bug: 
http://codepen.io/cfjedimaster/pen/WxpPap

And here is a CodePen (from Mike) showing the fix with class:
http://codepen.io/mhartington/pen/YWZBdK

**Comment by Emeryao** [comment]
the name is `ion-nav-back-button` so it should be in a `ion-nav-bar` isn't it?

**Comment by cfjedimaster** [comment]
Um. It is - isn't it?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#116
