### ISSUE TITLE
bug: Ionic2 beta 10 ionic form elements do not work with @angular/forms

### ISSUE THREAD

**Issue by WHarris22** [driftyco/ionic#7125]
#### Short description of the problem:

When trying to use the Angular 2 rc 3 @angular/forms module, Ionic's form elements always throw an error when adding the `formControlName` directive to them. For example: `<ion-input type="text" formControlName="formControl1" ></ion-input>`

Putting it to normal HTML input markup works OK, for example: `<input type="text" formControlName="fullName"  />`

#### What behavior are you expecting?

Ionic form elements; `ion-input`, `ion-textarea`, `ion-select` etc should all work with the new @angular/forms module.

**Steps to reproduce:**
1. Start a new Ionic app using beta 10
2. Add the @angular/forms module to the app
3. In the app.ts file import the following `import {disableDeprecatedForms, provideForms} from '@angular/forms';`
4. And then add the two imports to the ionicBootstrap like this `ionicBootstrap(MyApp, [ disableDeprecatedForms(), provideForms() ]);`
5. Now on another page create a form using Ionic inputs and the Form Builder part of [this tutorial](http://blog.thoughtram.io/angular/2016/06/22/model-driven-forms-in-angular-2.html#formbuilder)

Thats the best I can do for reproducing because I can't find any Plunker examples set up with the required modules and Ionic beta 10.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

The error written to the console log is:

> EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in build/pages/issue-form/issue-form.html:61:39
> ORIGINAL EXCEPTION: No value accessor for 'control1'
> ORIGINAL STACKTRACE:
> Error: No value accessor for 'control1'
>     at new BaseException (http://localhost:8100/build/js/app.bundle.js:2435:23)
>     at _throwError (http://localhost:8100/build/js/app.bundle.js:37484:11)
>     at Object.setUpControl (http://localhost:8100/build/js/app.bundle.js:37459:9)
>     at FormGroupDirective.addControl (http://localhost:8100/build/js/app.bundle.js:37027:18)
>     at FormControlName.ngOnChanges (http://localhost:8100/build/js/app.bundle.js:36902:32)
>     at DebugAppView._View_IssueFormPage0.detectChangesInternal (IssueFormPage.template.js:509:56)
>     at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:30588:14)
>     at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:30693:44)
>     at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8100/build/js/app.bundle.js:30614:19)
>     at DebugAppView.AppView.detectChangesInternal (http://localhost:8100/build/js/app.bundle.js:30599:14)

A related post on the [Ionic forum](https://forum.ionicframework.com/t/beta10-on-angularjs-2-rc3-forms/56181) 
 
**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 8.1
Node Version: v4.4.2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are currently aware of this issue and will be working on it. There were some pretty big breaking changes in the recent refactor of the Angular 2 forms module. This issue may be related: https://github.com/driftyco/ionic/issues/6580

**Comment by jgw96** [comment]
This may be related also (not 100% on that): https://github.com/driftyco/ionic/issues/7010

**Comment by rapropos** [comment]
I don't know if there is an elegant way to support both deprecated and new forms, but I suspect this issue results from importing `NG_VALUE_ACCESSOR` from "@angular/common" instead of from "@angular/forms".

**Comment by jgw96** [comment]
@rapropos yeah, there are a good list of things that the Angular team changed in forms, but we're going through and updating everything so it works with the new forms (: Thanks for using Ionic!

**Comment by kokokenada** [comment]
BTW - will Ionic be supporting Angular built in validators like required, minlength, maxlength, pattern?

**Comment by rapropos** [comment]
This is fixed for me (with `ion-checkbox`) as of [this commit](https://github.com/driftyco/ionic/commit/4d56219a4c33ca32587b83d90b014ae2e374959c).

**Comment by adamdbradley** [comment]
Yup, this should be closed with this commit: https://github.com/driftyco/ionic/commit/4d56219a4c33ca32587b83d90b014ae2e374959c

**Comment by vidakovic** [comment]
@adamdbradley this fixed input elements, but I am getting the following build error (from master):

```
src/components/menu/menu.ts(617,26): error TS2339: Property 'elementRef' does not exist on type 'Backdrop'.
```

**Comment by manucorporat** [comment]
@vidakovic just fixed: https://github.com/driftyco/ionic/commit/cac1d4f961137c7fae34adcd3ebc6ba8fecdb0b1

**Comment by vidakovic** [comment]
@manucorporat thanks a ton for quick fix, made my day ;-)

**Comment by cescoferraro** [comment]
I am on the nightly  "ionic-angular": "^2.0.0-beta.10-201606302045" and it not solved yet

**Comment by vidakovic** [comment]
@cescoferraro the build you mention doesn't contain the fix... it's included in master 2 days later. See:  https://github.com/driftyco/ionic/commit/cac1d4f961137c7fae34adcd3ebc6ba8fecdb0b1

**Comment by cescoferraro** [comment]
@vidakovic OK! How can I get the master from npm then?

**Comment by vidakovic** [comment]
@cescoferraro what I did: 

* checkout the master branch with git 
* build: gulp build --typecheck
* delete [YOURPROJECT]/node_modules/ionic-angular
* copy the content of "dist" folder to [YOURPROJECT]/node_modules/ionic-angular

Not sure if there is a shorter way to do this, but it's not too bad.

**Comment by cescoferraro** [comment]
`"ionic-angular": "git://github.com/driftyco/ionic.git"` is not working

NPM LS
```
npm ERR! missing: ionic-angular@git://github.com/driftyco/ionic.git, required by iot@
npm ERR! extraneous: ionic2@2.0.0-beta.10 /home/cesco/code/src/bitbucket.org/cescoferraro/iot/node_modules/ionic2
```

**Comment by yrefaeli** [comment]
Incredible! Was experiencing a similar issue with ionic-angular beta 10, angular2 rc 4 and angular/forms 0.2.0. Any combination of `provideForms()` (injected into `ionicBootstrap`) and `ion-range` (in any component) would fire exceptions. Got latest rev from master as per comments above, and everything works perfectly now!

Thanks @vidakovic, @manucorporat and @adamdbradley for the great bug fixes and help! Saved me from a ton of headaches!

**Comment by rapropos** [comment]
In addition to @vidakovic's method, if you're using webpack, here's how I was able to use a locally built ionic:

* check out with git
* `gulp prerelease`
* `cd dist`
* `npm link`
* go to app project directory
* clear out `node_modules/ionic-angular`
* add aliases described in [this issue](https://github.com/driftyco/ionic-cli/issues/1075) to webpack configuration
* `npm link ionic-angular`

This way further tweaks to the local ionic build will automatically filter up without requiring constantly cleaning and copying the dist directory. I suspect something similar is possible with browserify, but I don't know.

**Comment by ZiFFeL1992** [comment]
@vidakovic I followed your steps to generate ionic-angular from master but I can't see package.json in dist folder, any advice?

**Comment by manucorporat** [comment]
Another option:
```
gulp build
```

and now copy/paste manually the content of `/dist` inside your `node_modules/ionic-angular`

**Comment by CooleyGit** [comment]
I was having the same problem with the new forms so I manually updated to master. Now im getting the following errors:  "Property 'create' is private and only accessible within class 'Toast' Property 'create' is private and only accessible within class 'Modal'".

Im guessing this has something to do with @vidakovic comment "be aware that there are some changes (if you are coming from beta 10). E. g. the toast and modal API are used in a slightly different way." 

What exactly is different about the modal and toast? 

My basic toast looks like this.
```
presentToast(data) {
        let toast = Toast.create({
            message: data.msg,
            duration: 3333
        });

        if(data.success) {
            toast.onDismiss(() => {
                this.dismiss(data);
            });
        }

        this.nav.present(toast);
    }
```

I cant seem to find documentation on these changes i'm assuming they will be available with the beta 11 release but if anyone can help that would be great.

**Comment by marpstar** [comment]
@CooleyGit, you instead need to inject `ToastController` into your component. It has the `create()` method you're looking for, which returns you a `Toast` object containing `present()` and `dismiss()` methods.

**Comment by CooleyGit** [comment]
Thanks @marpstar that fixed it.

**Comment by cescoferraro** [comment]
@rapropos I am using webpack, I would be great to use you method to avoid the constant copy/paste. Have not tried this but there is one thing I missed, what do I do with the package.json. Keep it on beta.10 ?

**Comment by rapropos** [comment]
@cescoferraro the `gulp prerelease` step should create the `package.json` for the local ionic itself. If you're concerned about the `package.json` for your app, I don't think it matters: npm should notice that it's a link and not bother you about it.

**Comment by Anshdesire** [comment]
is it resolved ?

**Comment by donaldhook** [comment]
I am having the same issue... getting the master, rebuilding and copying to my project did not resolve the issue.  Not sure of what I can do to resolve.

**Comment by p-sebastian** [comment]
I'm still having this issue, on Beta-11

I'm getting the error 

> ORIGINAL EXCEPTION: No value accessor for 'amount'

but it works if I use normal inputs instead of <ion-input>

My .html form 
I've commented the toggle since it is not a part of the form

```
<form [ngFormModel]="bidForm">
    <ion-card>
      <ion-list>

        <ion-item>
          <ion-label floating job-live>Bid Amount</ion-label>
          <input job-live type="number" ngControl="amount"/>
        </ion-item>
        <ion-row *ngIf="!limit">
          <ion-col>
            <ion-item cb-primary>
              <ion-label cb-primary floating>Hours</ion-label>
              <input cb-primary type="number" ngControl="hours"/>
            </ion-item>
          </ion-col>
          <ion-col>
            <ion-item>
              <ion-label cb-primary floating>Minutes</ion-label>
              <input cb-primary type="number" ngControl="minutes"/>
            </ion-item>
          </ion-col>
        </ion-row>
        <!--<ion-item>
          <ion-label cb-primary> No Time Limit ?</ion-label>
          <ion-toggle cb-info checked="false" [(ngModel)]="limit"></ion-toggle>
        </ion-item>-->
      </ion-list>
    </ion-card>

    <!--<button block secondary type="submit" [disabled]="!bidForm.valid">Place Bid!</button>-->
  </form>
```

**The page.ts**

```
import { Component, OnInit } from '@angular/core';
import { FORM_DIRECTIVES, FormBuilder,  ControlGroup, Validators, AbstractControl } from '@angular/common';
import { ViewController } from 'ionic-angular';

@Component({
  templateUrl: 'build/pages/page1.html',
  directives: [FORM_DIRECTIVES]
})
export class page1 {
  bidForm: ControlGroup;
  bid: {amount: number; add: {hours: number; minutes: number}} = {amount: 100, add: {hours: 1, minutes: 15}};
  // amount: AbstractControl;
  // hours: AbstractControl;
  // minutes: AbstractControl;
  limit: boolean = false;
  constructor(private _viewCtrl: ViewController,
              private _builder: FormBuilder) {

    this.bidForm = this._builder.group({
      'amount': [''],      
      'hours': [''],
      'minutes': ['']
    });
    // this.amount = this.bidForm.controls['amount'];
    // this.hours = this.bidForm.controls['hours'];
    //
}

```
and my bootstrap from app.ts


`ionicBootstrap(MyApp, [HTTP_PROVIDERS, disableDeprecatedForms(), provideForms()])`

**Comment by Raviraj20** [comment]
need an help 
in ionic 2 if i give input as 011  it gives an error of strict mode hexadecimal
but i want it should treat  011=11
not as an hexadecimal
