### ISSUE TITLE
Feature request : Offline template compiling

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7127]
#### Short description of the feature:
It seems like Offline Template Compiling (OTC) is now possible. This means precompiling the templates into optimized code so there's less to zero compiling at runtime. I think this should be included into the Gulp workflow (maybe with the `release` option).

Here's an article explaining it : [http://www.syntaxsuccess.com/viewarticle/offline-compilation-in-angular-2.0](http://www.syntaxsuccess.com/viewarticle/offline-compilation-in-angular-2.0)

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello @Bouzmine yep, we are working extremely hard on getting offline template compiling, treeshaking and minifying into our build process. You can follow the progress [here](https://github.com/driftyco/ionic/issues/6776). This is one of our biggest goals to have before our release candidate, so you can be assured its very high priority. Thanks for using Ionic!
