### ISSUE TITLE
ion-segment deprecation warning ionic2

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#7132]
#### Short description of the problem:
grab any sample app with ion-segments.
see the following error in the console:
*ngSwitchWhen is deprecated and will be removed. Use *ngSwitchCase instead

There is no note in the breaking changes or migration instructions for beta10 relating to this.

Only occurs since beta10

#### What behavior are you expecting?
No errors in the console, ion-segment to not use deprecated functions.

**Steps to reproduce:**
1. grab any starter/sample project with segments
2. look in the console once the page with segments is loaded

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0beta10

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by adamdbradley** [comment]
Sorry but I'm not able to replicate this. Maybe it was fixed in master already, but I can't see to find where we use the older `ngSwitchWhen`. /cc @jgw96

**Comment by jgw96** [comment]
This looks to be fixed already in master to me too. Not seeing this deprecation warning with my testing version of the conf app. @ghenry22 Ill be closing this issue since its already been fixed. Thanks for using Ionic!

**Comment by ghenry22** [comment]
It is a current issue with beta10 when setting up a simple segment as in the component docs which start to use ngswitchwhen.

So when you say fixed in master do you mean the component docs are updated to not use ngswitchwhen or that it is still used but the deprecation warning has been fixed/removed?

**Comment by jgw96** [comment]
@ghenry22 Sorry i should have explained better. Fixed in master means that is has already been fixed in our Master branch (the ionic 2 branch). This means that the next release will not have this issue. I hope that explains things better. Also, i will be making an issue on our docs repo about removing any use of `ngSwitchWhen` from our docs as it has been deprecated by the Angular team. Thanks for using Ionic!

**Comment by ghenry22** [comment]
@jgw96 no problem, thanks for the clarification
