### ISSUE TITLE
bug: $ionicScrollDelegate.scrollBottom() doesn't work when overflow-scroll attribute value is set to true

### ISSUE THREAD

**Issue by sidlauskaslukas** [driftyco/ionic#7136]
$ionicScrollDelegate method scrollBottom() doesn’t work when ion-content directive overflow-scroll attribute value is set to true. It works with JS scrolling, but it doesn't work with native scrolling. 

**Steps to reproduce:**
1. Open example here: http://plnkr.co/edit/OQKe0wvlK84cS7rKOIIP?p=preview
2. Press "Reset" button and you will see that infinite-scroll is not triggered after reseting all the data and calling $ionicScrollDelegate.scrollBottom().
3. Remove overflow-scroll attribute from ion-content in "tab-dash.html" view and it will start to work.

**Which Ionic Version?** 1.3.1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#115
