### ISSUE TITLE
menu with header (beta10)

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#7138]
Since beta  10, my menu have some view problem. Middle down part of it is empty.

In breaking changes I see we must insert toolbar inside header/footer or content.
But, it's not updated in doc for menus. (toolbar is always outside ion-content tag)
http://ionicframework.com/docs/v2/components/#menus

How we should use menus and toolbar in menu ?

**Comment by imjohnbo** [comment]
The toolbar should also be inside a header. Check out Step 3 of Steps to Upgrade to Beta 10, and this quote from the [Changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#breaking-changes):

> The only elements that should be children of a page are ion-header, ion-content, and ion-footer

It normally takes a couple of days for the doc to reflect changes from a new beta release.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to move this to the `ionic-site` repo to make sure the docs are updated for this. :smile:

To answer your question: The menu toolbar should be similar to a page where the `ion-toolbar` is inside of an `ion-header` or `ion-footer`.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#676

**Comment by movrack** [comment]
I am not sure to understand, it means that the menu has to be in a ion content too ?
```
<ion-menu [content]="content">
      <ion-content>
      <ion-toolbar>
        <ion-title>Pages</ion-title>
      </ion-toolbar>
...
```
or 
```
<ion-content>
    <ion-menu [content]="content">
      <ion-toolbar>
        <ion-title>Pages</ion-title>
      </ion-toolbar>
...
```

**Comment by Kobzol** [comment]
I'm having the same problem, the menu doesn't render it's content and navigation also doesn't work (worked as of beta 9).

**Comment by brandyscarney** [comment]
Can you try it with the nightly? We made a change recently that may have fixed it:

`npm install --save ionic-angular@nightly`

**Comment by Kobzol** [comment]
This vesion doesn't work in my browser (`ionic serve`):
It errored that it couldn't find `ion-app` selector, even though I'm using `app` selector in index.html and the App component
- I changed the selector to `ion-app,` the error went away, but nothing is showed (blank screen)
It also shows an error `cordova_not_available`, but that was also showing in beta10.

Could you please clarify which one of the two ways of ion-content hierarchy from @movrack's comment is correct? An updated menu starter template would be nice in the future :-)

**Comment by movrack** [comment]
When you update the doc, please, could you also explain how to set the menu in an other file than the app.ts? And then use it.

Is it possible ta have an event (eventemitter) suscribable from ts file ? Actually, I use events ionOpen and ion Close to call methods who call a menu service to emit event suscribable.

**Comment by brandyscarney** [comment]
The following markup should be used for a menu:

```
<ion-menu>
  <ion-header>
  </ion-header>

  <ion-content>
  </ion-content>

  <ion-footer>
  </ion-footer>
</ion-menu>
```

See: https://github.com/driftyco/ionic/blob/master/src/components/menu/test/basic/main.html

If I remember correctly there was an issue with the `beta 10` release where this wasn't working right. That should be fixed in the `beta 11` release by this commit: https://github.com/driftyco/ionic/commit/3cd31c3d17b358f6b6afa5c9512ff605517d781b

To test this out, install the nightly:

```
npm install --save ionic-angular@nightly
```

We'll update the starter template as soon as `beta 11` is released. Thanks! :)
