### ISSUE TITLE
[FEATURE] Swipe-To-Go-Back, iOS7-Style / Interactive View Transitions

### ISSUE THREAD

**Issue by sidneys** [driftyco/ionic#714]
The new iOS7 navigation paradigm requires that users can always swipe to navigate backwards - in UIKit, this feature is called "Interactive Transitions".

This has been _excellently_ implemented in - only a few days old - "Framework 7" by the iDangerous guys:

Demo (Swipe from the left Screen Border):
http://www.idangero.us/framework7/#.UxRzo_RdXQw

Source:
https://github.com/nolimits4web/Framework7/blob/master/src/js/views.js

This would be the last gap to close to make Ionic non distinguishable from native on newer iOS7 based devices. :-) Please integrate it to the the Ionic framework.

**Comment by RomanMinkin** [comment]
Hi guys any updates? ;)

**Comment by reviyou** [comment]
new release candidate(just saw and tried it 5 hours ago!) seems to provide this feature out of the box

**Comment by danicomas** [comment]
This feature not works in Android 4.4.4 Nexus 4 with version v1.0.0-rc.4 "sulfur-suricate".

**Comment by perrygovier** [comment]
Swipe to go back is only enabled on iOS. It's not as common of a feature on Android and some lower quality Android devices just couldn't handle it. We opted to keep the functionality consistent across all devices on a given platform and disabled it for all Android. Plus, the Android style page transition doesn't look as good when gradually swiped.

**Comment by seb0zz** [comment]
Does this feature only contain swiping back? What about swiping forward?

**Comment by danicomas** [comment]
Hi @perrygovier @ajoslin I need to do something like that <ion-content on-swipe-right="swipe(0)" on-swipe-left="swipe(1)"> but in Android not works how can I do it? Thanks

**Comment by danicomas** [comment]
@perrygovier I have tried this but it doesn't work in Android 4.4.4:

 $ionicGesture.on('swipe',function(event) {
    alert(1);
  }, angular.element(document.querySelector("#hhh")));

**Comment by danicomas** [comment]
It works on Android 5.X @perrygovier

**Comment by Yonn-Trimoreau** [comment]
@seb0zz +1 ! Have you found a way implementing this ?

**Comment by seb0zz** [comment]
@Yonn-Trimoreau unfortunately I didn't :-(

**Comment by Yonn-Trimoreau** [comment]
Just found it. It's not really looking like if it was native, but it works great ;)
---> [on-swipe-left directive](http://ionicframework.com/docs/api/directive/onSwipeLeft/)

**Comment by mhartington** [comment]
This feature has been in ionic for a few releases now. It's enabled when using Cordova and iOS. It's disabled for android since android does not have the feature.

**Comment by Yonn-Trimoreau** [comment]
It works quite beautifully when swiping from an ion-slide :+1:

**Comment by magleahy** [comment]
Is there any event listener available for swipe back? I am trying to hook into this using drag right or swipe right but as they are not the same event - it's not accurate. Thanks in advance.
