### ISSUE TITLE
Can't open page with loading instance in ngOnInit from modal

### ISSUE THREAD

**Issue by EugeneSnihovsky** [driftyco/ionic#7140]
#### Short description of the problem:
When I try to navigate from modal view to page, that have ngOnInit method with Loading animation - nothing happens.

#### What behavior are you expecting?
I want to navigate from modals to other pages with loading animation in ngOnInit method.
Or if ionic team planning to implement **resolve** section analog in future - it will be fine.

**Steps to reproduce:**
1. I open modal instance
```typescript
public openModal(): Promise<any> {
        let modal = Modal.create(ShowInfoModal);
        return this.navCtrl.present(modal);
    }
```
2. From modal I try to open other page with **different methods** but got nothing (loading animation **from new page** appear, than dismiss, but page not changed)
```typescript
public openBroken1(): Promise<any> {
    return this.navCtrl.setRoot(PaymentMethodPage, {}, {animate: true, direction: 'forward'});
}

 public openBroken2(): Promise<any> {
    return this.viewCtrl.dismiss()
        .then(() => this.navCtrl.setRoot(PaymentMethodPage, {}, {animate: true, direction: 'forward'}));
}

public openBroken3(): Promise<any> {
    this.viewCtrl.destroy();
    return this.navCtrl.setRoot(PaymentMethodPage, {}, {animate: true, direction: 'forward'});
}

public openBroken4(): Promise<any> {
    this.viewCtrl.onDestroy(() => this.navCtrl.setRoot(PaymentMethodPage, {}, {animate: true, direction: 'forward'}));
    return this.viewCtrl.dismiss();
}
```
3. In page, that can't open I implement ngOnInit (also try onPageWillEnter and onPageLoaded) method with animation (will be used for animate API response loading. In example simplified but still not work)
```typescript
ngOnInit() {
        var loadingInstance = Loading.create({
            content: 'Loading...'
        });
        this.navCtrl.present(loadingInstance);

        setTimeout(() => {
            loadingInstance.dismiss();
        }, 1000)
    }
```

#### Other information
 Work project with error code placed [here](https://github.com/EugeneSnihovsky/ionic2-for-errors/tree/ER-3_navigation_animation_error) (branch ER-3_navigation_animation_error)
Or you can clone it with
```
git clone -b ER-3_navigation_animation_error https://github.com/EugeneSnihovsky/ionic2-for-errors.git
```
**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.2 Rafaela 
Node Version: v5.3.0

**Comment by manucorporat** [comment]
@adamdbradley do you think the new overlay system could have fixed this?
https://github.com/driftyco/ionic/issues/7140

**Comment by adamdbradley** [comment]
Yes, hopefully this issue may have been fixed in beta11, since the overlay's anchor is always at the root and already initialized.

**Comment by jgw96** [comment]
I'm putting this down as one of my things to test this afternoon. I'm thinking it should be fixed though (:

**Comment by jgw96** [comment]
Just did a quick test on this and it seems to be fixed for me with the latest nightly. If anyone is on the latest nightly, or beta.11 once it gets released, and still has this issue feel free to comment and i will happily reopen. Thanks for using Ionic!
