### ISSUE TITLE
Item reordering issues

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#7142]
A few UX things with the new reorder.

 * [x] Icon is too big and too opaque (i.e. try grey instead of black). I know it's the wrong one but could make this one smaller in the meantime
 * [x] Icon should animate in instead of just appearing
 * [x] Can't reorder above the first one.
 * [x] If the drag is canceled the element doesn't animate smoothly back

See video for examples of all:

http://ionic-io-assets.s3.amazonaws.com/reorder.mov

**Comment by manucorporat** [comment]
@mlynch I think the point 3 was fixed here last night: [here](https://github.com/driftyco/ionic/commit/d993a1bfd86f6987e44f0a78fa5b4a46026de779)

I will check out tonight though :)

**Comment by manucorporat** [comment]
@mlynch @adamdbradley all the issues have been fixed in the following commits:
f289ac6
8483a43
d993a1b

but "Icon should animate in instead of just appearing" is not that simple.
- We can't use only CSS, but Animate for each one
- What if the list has hundreds of items

I think it is a perfect use case for the new animate hooks of angular 2, but I think we decided to wait until they are more mature, right?

**Comment by djangojack** [comment]
If the drag is cancelled and the item barely moves and doesn't actually reorder, indexes.to is set to -100 instead of the actual index. Checking if indexes.to < 0 isn't as intuitive as just checking if indexes.from == indexes.to. Agree?

**Comment by manucorporat** [comment]
@djangojack 100% agree, it is a bug! can you please open an issue?

**Comment by djangojack** [comment]
@manucorporat done. https://github.com/driftyco/ionic/issues/7307

**Comment by brandyscarney** [comment]
There is a PR open to change the icon to the `reorder` icon. Is this something we want to do? https://github.com/driftyco/ionic/pull/7450

**Comment by manucorporat** [comment]
Reorder animation implemented by @mhartington #7651 merged!

**Comment by manucorporat** [comment]
#7450 merged!
@mlynch closing issue... 👌
