### ISSUE TITLE
Ionic iframe crushed when clicked input box

### ISSUE THREAD

**Issue by BVJin** [driftyco/ionic#7144]
I am using external website for the certain page and of course it is included by iframe. 

The iframe is working perfectly at browser, but not well at real phone. Every time I clicked/touched the input box, it auto focused the input to the center of screen, but if I type something, it just scrolled to the top of page and then not able to scroll anymore, basically the whole page froze as long as I start typing...

I don't think it is the web page problem since another app using the same page and it is working well, but I don't have the access for that app so I cannot get the code of that.

I tried every solution mentioned here,
https://github.com/driftyco/ionic/issues/1151
nothing

Safari console gives me nothing, but Xcode is showing this:

```
2016-06-30 12:05:01.111 myApp[1968:705355] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x137d26530 V:|-(20)-[UIInputSetContainerView:0x137eee530]   (Names: '|':UIRemoteKeyboardWindow:0x13933ffa0 )>",
    "<NSLayoutConstraint:0x1391dd900 'UIInputWindowController-top' V:|-(0)-[UIInputSetContainerView:0x137eee530]   (Names: '|':UIRemoteKeyboardWindow:0x13933ffa0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x137d26530 V:|-(20)-[UIInputSetContainerView:0x137eee530]   (Names: '|':UIRemoteKeyboardWindow:0x13933ffa0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

I have no knowledge about object-c, and can only get native ios solution by google, please help.
code is here:

HTML
`<ion-content class="register" overflow-scroll="true" scroll="true">
    <iframe data-tap-disabled="true" src="{{iframeURL}}"></iframe>
  </ion-content>`

CSS
`.resources, .register, .facebook {
  iframe {
    width:100%;
    height:100%;
  }
}`

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that i can pull and push to my device that demonstrates this issue? Thanks for using Ionic!

**Comment by BVJin** [comment]
@jgw96 Thank you for the quick reply, I dont think I can reproduce the issue at Plunker, since it only happens when it is running on the real phone. 

This site you can use for testing,  it happens when I am typing something at Email
https://www.willowcreek.com/rega/#/reg/trans/one?invtID=EV-LSS1608-MAIN-346

The page code I have already provided at questions, no js involved at this point, only css and html.

Thank you again.

**Comment by BVJin** [comment]
https://forum.ionicframework.com/t/iframe-on-ios-bugged-when-interacting-with-its-content/51785

I think my issue is having the interaction with content of iframe crush the iframe

**Comment by jgw96** [comment]
Hello @BVJin ! Are you using your iframe "fullscreen" in your app as the person in that forum is?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
