### ISSUE TITLE
bug: BackgroundGeolocation - Plugin not Installed

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic#7147]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>BackgroundGeolocation methods returns 'Plugin not Installed' whenever I use.
Ionic info
`Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v5.6.0`

Ionic plugin ls

`cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-mauron85-background-geolocation 2.1.2 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"`

ionic platform ls
`Installed platforms:
  android 5.1.1`
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Are you using `ionic-native` when you get this error?

**Comment by DaniloCouto** [comment]
Hello, 
Yes, I'm using ionic-native.

I'm building a provider to call BackgroundGeolocation.
`import {BackgroundGeolocation} from 'ionic-native';`

Other plugins like Geolocation works great.

Thanks for answering,

**Comment by jgw96** [comment]
Ahh ok, thanks! Since this is an ionic native issue i am going to move this issue to the Ionic-Native repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#258
