### ISSUE TITLE
Close ion-select when user select option without click on Ok 

### ISSUE THREAD

**Issue by Malkiat-Singh** [driftyco/ionic#7150]
Hi 
I am using ion-select in ionic 2 with typescript
I need to close ion-select without click Ok Button 

Thanks

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by LtotheWT** [comment]
May i know where is the solution? thanks

**Comment by esubansiri** [comment]
@LtotheWT you can use interface="action-sheet"
`<ion-select interface="action-sheet" formControlName="type" placeholder="Select..">
        <ion-option *ngFor="let value of types" value="{{value.type}}">{{value.type}}</ion-option>
      </ion-select>`

**Comment by LtotheWT** [comment]
hi @esubansiri thx for the reply, but i have 15++ items, guess that this interface="action-sheet" cannot work in my situation.

**Comment by patwaswapnil** [comment]
any solution?

**Comment by unfg** [comment]
please, vote for the #10178 issue, if you still interested in this functional.
