### ISSUE TITLE
v2 beta.10: Unable to scroll vertically after switching between tabs [iOS]

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic#7154]
Hello there!  I recently upgraded to ionic-angular 2 beta.10 and I noticed a weird bug where vertical scrolling is not responding.  My application uses `ion-tabs` with 4 tabs across the bottom of the screen.  On load, the far left tab is automatically selected.  If I choose the 2nd tab and scroll vertically (via touch in ios simulator or on device) it scrolls just fine.  Then i switch to tab 4 and scroll vertically via touch and it also works fine.  If I switch back to the 2nd tab and try to scroll vertically it appears unresponsive and the list does not scroll.  But if I switch back to tab 4, I see that it has been scrolled according to my touch while viewing tab 2.

Wondering if you have noticed a similar phenomenon?  Any ideas for a workaround?

Cheers

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by Manduro** [comment]
I'm having the exact same problem, also since beta 10.

**Comment by jasonwaters** [comment]
Hi @jgw96, do you have a plunker with ionic set up already that I can start from?  I'm not sure it will help without testing on a mobile device actually.  My guess is the guys maintaining conference app could reproduce this pretty easily

**Comment by jgw96** [comment]
@jasonwaters Sorry was just able to reproduce. On Android it seems to be fine, but on IOS there is definitely an issue. Thanks!

**Comment by jasonwaters** [comment]
Thanks! Any chance I can get a nightly with this fix?

**Comment by jgw96** [comment]
Hello all! This has been fixed for beta.11 as you can see above, but if you would like a workaround until beta.11 comes out feel free to just copy the css from the commit mentioned above into your project. Thanks for using Ionic everyone!

**Comment by ch-weiss** [comment]
@jgw96 Now in beta 12 I have this issue on the first tab that is not scrolling anymore after the app has started. After a change to a subview of the same tab an returning scrolling works. Can you please check your fix of this issue regarding to this side effect?
