### ISSUE TITLE
Add the options argument for BarcodeScanner.scan() method

### ISSUE THREAD

**Issue by andreafoorlan** [driftyco/ionic#7156]
BarcodeScanner native component is based on phonegap-plugin-barcodescanner plugin, which accepts an object of options as argument in its scan method in order to change the default camera selected and a bunch of other settings.

It would be nice to have the same chance in Ionic 2:

BarcodeScanner.scan({..options passed to native plugin scan method...}).then(...)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with Ionic-Native and not the ionic framework i will be moving this issue over to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#260
