### ISSUE TITLE
bug: Push not working in Production mode

### ISSUE THREAD

**Issue by aetchegoyen** [driftyco/ionic#7162]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

As for now, I've already:

- Created both Development and Distribution certs from scratch from Apple Developer Portal
- Reloaded the certs in my machine using Xcode (and fixing signing issues from xcode)
- Exported the .p12 certs and uploaded them to ionic.io platform
- Set my app push config to production mode (just in case) and dev_push = false.
- Built using --release from terminal
- Built using Xcode and selecting Release build in build options

And I've tried:

- Sending push with APNS-Tool using the production certs **and it works.**
- Sending push from ionic.io using production profile and **it doesn't work.**
- Sending push using ionic.io API using production profile and **it doesn't work.**
- Sending push using ionic.io and ionic.io API using development profile and **it works.**

**Comment by jgw96** [comment]
Hello! Since this is an issue with our push notification service i will be moving this issue to the appropriate repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud#18
