### ISSUE TITLE
V2 Beta10: Tabs don't work if preloadTabs input is on true

### ISSUE THREAD

**Issue by malvarezhcr** [driftyco/ionic#7167]
#### Short description of the problem:
Only the first page is being loaded if preloadTabs input is on true. If you try to click on another tab the page won't change.

#### What behavior are you expecting?
Pages must be preloaded and change if a tab button is clicked.

**Steps to reproduce:**
1. Add preloadTabs input and set it to true
2. Run ionic serve
3. Click another tab

```
<ion-tabs [preloadTabs]="true">
  <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="home"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="About" tabIcon="information-circle"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="Contact" tabIcon="contacts"></ion-tab>
</ion-tabs>
```

**Other information:**
The console is throwing this error: 
```
content.js:477 Uncaught TypeError: Cannot read property 'style' of undefined
```
 
**Which Ionic Version?** 1.x or 2.x
2 beta10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by manucorporat** [comment]
I think this was already fixed in this commit: https://github.com/driftyco/ionic/commit/2d19308a52f41a052679d83fd7f132deb3dcbc63

So will be fixed in the release (beta11)!
