### ISSUE TITLE
V2 docs - incorrect debounce explanation on range

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#7168]
#### Short description of the problem:

http://ionicframework.com/docs/v2/api/components/range/Range/

Both pin and debounce have the same documentation

pin
If true, a pin with integer value is shown when the knob is pressed. Defaults to false.

debounce
If true, a pin with integer value is shown when the knob is pressed. Defaults to false.

Looks like the debounce documentation needs a tweak.

#### What behavior are you expecting?
Pretty sure debounce is not the same as pin. 

**Which Ionic Version?** 1.x or 2.x
2

**Comment by manucorporat** [comment]
@alexbainbridge thanks for the report!
