### ISSUE TITLE
Items ng-repeat remove element problem v1

### ISSUE THREAD

**Issue by kraskoshnyy** [driftyco/ionic#7173]
Hello everybody,
I'm using ng-repeat for `<items>`.
Initially I have object -> array:

`(key, chat) in chats | toArray | orderBy: '-updated' track by $index`

Sorting works perfectly, but  when I try to delete an element - It's stuck, without order by works perfect.
No any errors, screen looks like on a phone and wrong element deleted.

I'm removing element just with delete object[key];

Thanks

<img width="396" alt="screen shot 2016-07-02 at 9 44 39 am" src="https://cloud.githubusercontent.com/assets/10145395/16541501/a60d3312-4039-11e6-8806-84ae55345822.png">

**Comment by kristiyandobrev** [comment]
Can you provide some code examples ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
