### ISSUE TITLE
Ionic v2 - Beta 10 - Tabs Broken - preloadTabs = "true"

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#7181]
#### Short description of the problem:
Hello, 
After I upgraded to beta 10 and applied the changes required to the navbar where I wrap navbar with ion-header. However, my tabs are broken. I get the following exception:

```
content.js:477 Uncaught TypeError: Cannot read property 'style' of undefinedContent.writeDimensions @ content.js:477PageTransition.writeDimensions @ page-transition.js:38Animation._beforeWriteFn @ animation.js:637(anonymous function) @ animation.js:342
```
I noticed that if I turn off the "preloadTabs" and set it to false. I avoid that error. Is there a new directive for preloadTabs ?

#### What behavior are you expecting?
I should still be able to navigate through my tabs using preloadTabs directive.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 **N/A**

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     
 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
******************************************************
```

**Comment by manucorporat** [comment]
@tonyawad88 thanks for the report! this bug was already fixed in nightly

**Comment by dtruel** [comment]
This is still broken for me in beta 35 - any idea why?
