### ISSUE TITLE
Ionic2 beta 10 radio button in a group all are enabled 

### ISSUE THREAD

**Issue by saurabhvyas** [driftyco/ionic#7182]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

So I am using ngfor and for each item , I am having a corresponding radio button but only one of them should be checked at a time but they all can be at the same time , this is a bug

#### What behavior are you expecting?

**Steps to reproduce:**
<ion-content padding class="home">
  <h2 *ngIf="toggle"> {{questions[0].question }}</h2>
  
  Answer :
  <ion-list *ngIf="toggle" radiogroup>
    
    <ion-item  *ngFor="let answer of questions[0].answers; let i=index">
         <ion-label>{{answer }} </ion-label>
       <ion-radio value="{{i}}" ></ion-radio>
       
     
      
      
      
      </ion-item>
      
    
  </ion-list>
  
   

    
</ion-content>
```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by manucorporat** [comment]
@saurabhvyas You have to pack the `ion-radio` inside a RadioGroup.

Read the documentation:
- http://ionicframework.com/docs/v2/api/components/radio/RadioGroup/
- http://ionicframework.com/docs/v2/api/components/radio/RadioButton/

**Comment by saurabhvyas** [comment]
Yes I did use a radiogroup attribute

Here is the code once again ``` <ion-list *ngIf="toggle" radiogroup>
    
    <ion-item  *ngFor="let answer of questions[activequestion].answers; let i=index">
         <ion-label>{{answer }} </ion-label>
       <ion-radio value="{{i}}" (click)="next()" ></ion-radio>
       
     
      
      
      
      </ion-item>
      
    
  </ion-list> ```

**Comment by manucorporat** [comment]
@saurabhvyas  As I said, read the documentation **carefully** :D 
- It it not `radiogroup` but `radio-group`
- You should use the Angular syntax to pass dynamic attributes: `[value]="i"`
- Don't use `(click)="next()`, use `(ionChange)`

**Comment by saurabhvyas** [comment]
Oh How stupid of me hehe , but thanks for your help

**Comment by manucorporat** [comment]
@saurabhvyas no worries! we are here to help!
