### ISSUE TITLE
Ionic2/ES6 - Can't setup routing for my sidebar menu

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7183]
I am trying to setup a sidebar menu in my app; however, I am facing some difficulties on doing so, especially there is no documentation or sample app.
I already tried to checkout the existing templates, but all of them are written in TypeScript.

Currently, I successfully implemented the sidebar, what I am not able to do so far is the **routing** to other pages (i.e open a view when clicking on a button inside that sidebar menu).

I've tried to debug and I guess I have an issue related to **ViewChild** as I believe it needs to be integrated in another way; however, please suggest any other solution so I can implement routing inside that sidebar menu.

Below you can find the code of the file app.js

**app.js**     

              import 'es6-shim';
              import {Component, ViewChild} from '@angular/core';
              import {App, ionicBootstrap, Platform, Nav} from 'ionic-angular';
              import {StatusBar, Push} from 'ionic-native';
              import {HomePage} from './pages/home/home';
              import {FeedbackPage} from './pages/feedback/feedback';

              @Component({
                template: `
                <ion-menu [content]="mycontent">
                          <ion-content>
                          
                           <ion-list>

                           <div class="profileHeaderPadding">
                            <ion-item class="profileHeaderStyle">
                            <h2>User</h2>
                          </ion-item>
                          </div>

                               <button ion-item *ngFor="#p of pages" (click)="openPage(p)">{{p.title}}</button>
                            </ion-list>
                          </ion-content>             
                        </ion-menu>
                        <ion-nav #mycontent [root]="rootPage"></ion-nav>
                `,
                 queries: {
                  nav: new ViewChild('Nav')
                },
                // config: {} // http://ionicframework.com/docs/v2/api/config/Config/
              })
              export class MyApp {
                static get parameters() {
                  return [[Platform]];
                }

                constructor(platform, nav) {
                  this.nav = nav;
                  this.rootPage = HomePage;
                        this.pages = [
                          { title: 'Feedback', component: FeedbackPage}
                          // { title: 'My Account', component: ProfilePage },
                          // { title: 'Settings', component: SettingsPage }
                      ];

                  platform.ready().then(() => {
                    // Okay, so the platform is ready and our plugins are available.
                    // Here you can do any higher level native things you might need.
                    StatusBar.styleDefault();
                  });
                }

                  openPage(page) {                
                 this.nav.setRoot(page.component);
                }
              }
              ionicBootstrap(MyApp);

#######################

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by ghenry22** [comment]
It looks like all the templates have just been switched to default to TS rather than ES6.  My app is all in ES6 not typescript, these should be the relevant parts that you need to have in your app.js to setup the side menu and have it working.

This is just cut straight out of my working ES6 app on beta10

```
@Component({
  templateUrl: 'build/app.html',
  queries: {
    nav: new ViewChild('content')
  }
}) 

// Generate navigation for side menu
    this.pages = [
      { title: 'Home', icon: 'stats', component: HomePage},
      { title: 'Artists', icon: 'people', component: ArtistsListPage }
    ];

 //set the start page for the app
    this.rootPage = HomePage;

 // navigate from side menu to page
 // Reset the content nav to have just this target page
 // we wouldn't want the back button to show from the sidemenu
  openPage(page) {
    this.nav.setRoot(page.component);
  }
}
```

in app.html:

`<ion-nav id="nav" [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>`

**Comment by ghenry22** [comment]
you problem is probably because you are declaring this.nav in the constructor and in the query.  Remove nav and this.nav from your constructor.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement a menu i will urge that you ask this question on our forum (forum.ionicframework.com). Also, just a heads up, but the reason we do not provide es2015 samples or starters is because we have gone all in with TypeScript, you can read more about why we made that decision [here](http://ionicframework.com/docs/v2/resources/typescript/). Thanks for using Ionic!
