### ISSUE TITLE
V2 Need Lock transition, unlock transition, lock next transition features in slider module

### ISSUE THREAD

**Issue by ashutosh-akss** [driftyco/ionic#7186]
#### Need following support in slider module in ionic v2

1. Lock transition
2. Unlock transition
3. Lock transition to next slide
4. Unlock transition to next slide
5. Lock transition to previous slide
6. Unlock transition to previous slide

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
