### ISSUE TITLE
[v1.3.1 ] $ionicSideMenuDelegate.toggleLeft() returns again to the same view

### ISSUE THREAD

**Issue by warcry2000** [driftyco/ionic#7187]
In Ionic, v1.3.1 
When i use $ionicSideMenuDelegate.toggleLeft() and in the view with the keyboard is visible for input,  returns again to the same view.

This also happens with menu-toggle:
`<button class="button button-icon button-clear ion-navicon" menu-toggle="left"></button>`

**Comment by gfismtposb** [comment]
I have the same problem, is there any solution?
Thanks

**Comment by raulpopi** [comment]
Hello,
In version 1.3.2 still fails.
In version 1.2.4 and earlier works correctly.

Regards

**Comment by warcry2000** [comment]
I downloaded version 1.2.4 for me to work.
Any solution?
Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#114
