### ISSUE TITLE
Retain Scroll Position On List Reload

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#719]
We need a mechanism to retain scroll position after returning from a detail view when data is reloaded from a service.  The current implementation only works when the controller has the list data pre-defined in the scope.

See this sample where the controller reloads the data from a service instead of having embedded in controller.

Sample : http://codepen.io/SatadruBhattacharjee/pen/jsLtb

References :
http://forum.ionicframework.com/t/on-coming-back-from-details-to-list-page-the-scroll-position-goes-back-on-top-list-data-loaded-by-async-task/1432/2 

http://forum.ionicframework.com/t/save-list-view-state/1554/2

**Comment by cozzbie** [comment]
How can this be implemented in ionic 2? I'd like my list to stay at the same even after the items have been loaded in the background.

**Comment by erperejildo** [comment]
And what about Ionic 3?
