### ISSUE TITLE
Datetime not working for dayValues attribute

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic#7190]
#### Short description of the problem:

DateTime not working when the dayValues attribute is added 
#### What behavior are you expecting?

Should show the Date picker with the specified days

When using the dayValues attribute in <ion-datetime> something like this:

```
<ion-item>
       <ion-label>Date</ion-label>
       <ion-datetime monthValues="6,7,8" yearValues="2014,2015" dayValues="01,02,03,04,05,06" displayFormat="DD/MMM/YYYY" [(ngModel)]="myDate"></ion-datetime>
</ion-item>
```

i get the error as:

> Cannot set property 'disabled' of undefined
> at DateTime.validate (datetime.js:486)
> at DateTime.open (datetime.js:350)
> at DateTime._click (datetime.js:313)
> 
> ORIGINAL EXCEPTION: TypeError: Cannot set property 'disabled' of undefined
> ORIGINAL STACKTRACE:
> TypeError: Cannot set property 'disabled' of undefined
> at DateTime.validate (http://localhost:8100/build/js/app.bundle.js:48564:48)
> at DateTime.open (http://localhost:8100/build/js/app.bundle.js:48428:14)
> at DateTime._click (http://localhost:8100/build/js/app.bundle.js:48391:14)
> at DebugAppView.ViewAnalyticsRender0.handleclick_385_1 (AnalyticsRender.template.js:4870:36)
> at http://localhost:8100/build/js/app.bundle.js:31774:24
> at http://localhost:8100/build/js/app.bundle.js:41260:36
> at http://localhost:8100/build/js/app.bundle.js:41330:111
> at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:323:29)
> at Object.onInvoke (http://localhost:8100/build/js/app.bundle.js:36931:41)
> at ZoneDelegate.invoke (http://localhost:8100/build/js/zone.js:322:35)
> ERROR CONTEXT:
> [object Object]Zone.runTask @ zone.js:260ZoneTask.invoke @ zone.js:423

Plunkr: http://plnkr.co/edit/RL5REAhfQdAoEdCjmLj3?p=preview

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.31
#### Plunker that shows an example of your issue

http://plnkr.co/edit/RL5REAhfQdAoEdCjmLj3?p=preview

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by chandanch** [comment]
Any Updates on this?

**Comment by patrickpereira** [comment]
Same issue here!

**Comment by CharlyTheDog** [comment]
Same issue!

**Comment by skill83** [comment]
On RC3 is still not working, i cannot set dayValues:

![schermata 2016-12-06 alle 10 46 43](https://cloud.githubusercontent.com/assets/656011/20920717/5e839426-bba1-11e6-867d-1a6d8b884915.png)

**Comment by brandyscarney** [comment]
Thanks for the issue and sorry for the wait! This will be fixed in the `rc.5` release, but I also released a nightly version with the fix if you want to try it out sooner:

```
npm install --save ionic-angular@2.0.0-rc.4-201612191922
```
