### ISSUE TITLE
Slides v2 beta10 does not work on android

### ISSUE THREAD

**Issue by ValterSantosMatos** [driftyco/ionic#7192]
#### Slides v2 beta10 does not work on android (unable to swipe)

Expect to see 3 swiper-pagination-bullets on the bottom and be able to swipe between the screens.
Worked in beta 9, works if emulate IOS device.

**Steps to reproduce:**
Just check the Plunker.

**Which Ionic Version?** 2.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/gW6ckkR5cZ4G8e3EbiRh?p=preview

**Comment by mangonecristian** [comment]
Same here. It works after a window resize.

**Comment by schankam** [comment]
Also got the bug on Android (working fine on iOS). Looks like it does not work when using ion-slides inside an ion-content...

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/7089. Thanks for using Ionic!

**Comment by barocsi** [comment]
It's even closed in #7089  wher it should not be. It also present in simple chrome browsers.
