### ISSUE TITLE
v2 feature request - autoresize on ion-textarea

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#7193]
#### Short description of the problem:

Would be great if the ion-textarea could have an autoresize capability
#### What behavior are you expecting?

Something like 
http://www.primefaces.org/primeng/#/inputtextarea
or
https://www.npmjs.com/package/angular2-autosize

**Which Ionic Version?** 1.x or 2.x
2

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by florentsuc** [comment]
I'm also waiting for this feature. Meanwhile, I created a custom version of `angular2-autosize` directive in my project:

First, create an Autosize directive with ionic-cli: `ionic g directive autosize`

Then replace the code in `components/autosize/autosize.ts` by:
```
import { Directive, HostListener, ElementRef } from '@angular/core';

@Directive({
  selector: '[autosize]' // Attribute selector
})
export class Autosize {

  @HostListener('input',['$event.target'])
  onInput(textArea: HTMLTextAreaElement): void {
    this.adjust();
  }

  constructor(public element: ElementRef){}

  ngAfterContentChecked(): void{
    this.adjust();
  }

  adjust(): void {    
    let textarea = this.element.nativeElement.children[0];
    textarea.style.overflow = 'hidden';
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + "px";
  }
}
```

You can now use the `autosize` property on `<ion-textarea>` element.

I just tested it on textarea without labels. But it should also work with labels.

**Comment by marcoturi** [comment]
@florentsuc 
Thank you, but for me it's not working on ionic rc3. I'm always getting 3 row with ion-textarea. Using the directive on a normale textarea is working instead. If you want i can provide same code examples.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#48
