### ISSUE TITLE
ion-content being drawn behind tabs and nav when conditionally switching ion-content

### ISSUE THREAD

**Issue by Artfloriani** [driftyco/ionic#7195]
#### Short description of the problem:
When switching `ion-content` using *ngIf, the new content is being drawn behind the Tabs bar and Navigation bar. If I switch tabs (go to a new tab and go back to the previous tab), the margin is added and the content is correctly placed.

#### What behavior are you expecting?
`ion-content` should always have a margin if `fullscreen` is not forced. 

**Steps to reproduce:**
1. Add two `ion-content` to a page. 
2. Add *ngIf to both of them (so only one will be visible at a time)
3. After the page has been drawn, change the condition on the *ngIf in order to switch contents. 

 
**Which Ionic Version?**  2.x
2

#### Plunker that shows an example of your issue

http://plnkr.co/edit/OW4mN9elI8YV1YtuDahy?p=preview

**ionic info`** 
```
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.10.1
```

**Comment by windwp** [comment]
I have same problem with  ion-content and tabs page .
My page have ion-header in tabs.html and ion-header will be hide in by tabs content.
```html
<ion-header>
        <comp-user-title title="{{title}}"></comp-user-title>
</ion-header>
  <ion-tabs id="tabs" #rootTabs>
        <ion-tab [root]="today" tabTitle="Today" tabIcon="chatbubbles"></ion-tab>
   </ion-tabs>
```
Maybe  It is not good for use ion-header in tabs.html But in ionic beta 9 it work fine But when I upgrade to ionic beta 10 my header is hide bellow content page

Here is my code in ionic beta 9
```html
<ion-navbar *navbar>
        <comp-user-title title="{{title}}"></comp-user-title>
</ion-navbar>
<ion-tabs id="tabs" #rootTabs>
    <ion-tab [root]="today" tabTitle="Today" tabIcon="chatbubbles"></ion-tab>
   ...
</ion-tabs>

```

Is there any solution to disable fullscreen property in ion-content page

**Comment by Artfloriani** [comment]
@windwp I would suggest moving your ion-navbar to each individual page. If you are not using the ion-content on the same way I presented on the first post, your navbar should work properly when added to each page.

**Comment by jgw96** [comment]
@windwp `ion-navbar` should not be used in the same template. Since `ion-tabs` is a "root" component it should always be in a component by itself. To see an example of this you can start a tabs app using `ionic start CoolApp tabs --v2`. While your example would have worked before beta.10, it actually should not have, sorry for any confusion this caused! @Artfloriani i will have to look more into this issue as i am not sure what implications having two `ion-content` components in a page has for the framework, but for a workaround for this issue you can do something like [this](http://plnkr.co/edit/zFTvqPalRFXUXQLv2tJx?p=preview). Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello @Artfloriani , just discussed this with the team and can confirm that you should not use two `ion-content` components in one template, the correct way to do it is the example i linked to in my last comment. Thanks for using Ionic!

**Comment by Artfloriani** [comment]
@jgw96 Great to know. Thank you for your support :)

**Comment by jgw96** [comment]
@Artfloriani No problem at all, have fun using Ionic 2, there is some exciting stuff coming up around the corner!

**Comment by totovelo10** [comment]
Very  helpful!
