### ISSUE TITLE
How to translate ion-datetime in ionic2 to Chinese?

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#7199]
I am using ionic2-beta10, but the ion-datetime control have `OK` and `Cancel` button,
What I need to do to translate these text.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by vuhung3990** [comment]
hey guy, you can use ng2-translate plugin then use `<ion-date cancelText="{{'common.cancel' | translate}}" doneText="{{'common.ok' | translate}}".....` to translate these texts

**Comment by lygstate** [comment]
@vuhung3990 Thanks a lot, indeed, if this can be document at somewhere of ionic2 should be better.
