### ISSUE TITLE
bug: ion-toggle button tappable over mask

### ISSUE THREAD

**Issue by AnkitaOpenstream** [driftyco/ionic#7201]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>ion-toggle button is clickable even after a popup is on

http://codepen.io/ankitaurfrnd/pen/JKJprp</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#113
