### ISSUE TITLE
v2 beta.10: navbar overlap with iOS statusbar when tabbar hidden

### ISSUE THREAD

**Issue by zzpmaster** [driftyco/ionic#7203]
In beta 10, setting **tabSubPages: true** , althought the tabbar is hidden, but tabs view will overlap with iOS statusbar. like #6368.

<img width="363" alt="screen_shot_2016-07-05_at_2_51_29_pm" src="https://cloud.githubusercontent.com/assets/1327089/16576183/0587204a-42c0-11e6-9b7b-f8f146b10899.png">
<img width="380" alt="screen_shot_2016-07-05_at_10_06_44_am" src="https://cloud.githubusercontent.com/assets/1327089/16576182/05842520-42c0-11e6-9fb0-d410ac7b15f4.png">

**What behavior are you expecting?**
not overlap.

**Steps to reproduce:**
1. set tabSubPages: true in ionicBootstrap
2. call `nav.push` to detail page

**Which Ionic Version?** 2.0.0-beta.10

Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.10
Ionic App Lib Version: 2.0.0-beta.3
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by TivonChen** [comment]
+1, only happend on ios device

**Comment by zzpmaster** [comment]
@jgw96 Hello, this problem only happen on iphone or iphone simulator.

**Comment by TheBrockEllis** [comment]
I have having the same issue. I have a tabs page inside of a sidebar nav. All of my headers are squished up into the phone's toolbar. See screenshot (sorry for the wasted whitespace on the screenshot)
![screen shot 2016-07-06 at 9 53 00 am](https://cloud.githubusercontent.com/assets/1606194/16622401/aff31756-435f-11e6-80c6-9113a26ec87e.png)

Ionic Info:
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by Emeryao** [comment]
Have you try to use the status-bar plugin from `ionic-native` to solve this issue?

**Comment by brandyscarney** [comment]
This will be fixed in the `beta 11` release. Also, `tabSubPages` has been renamed for `beta 11` to `tabsHideOnSubPages` as part of https://github.com/driftyco/ionic/issues/7143.

Just to let everyone know, if you set the `statusbarPadding` in the config you will be able to reproduce any status bar issues in a browser/plunker:

```
ionicBootstrap(E2EApp, [], {
  statusbarPadding: true
});
```

Thanks!

**Comment by ginsleepy** [comment]
beta 10 
when tabSubPages:true, statusbarPadding:true won't fix the problem

**Comment by yelhouti** [comment]
Bug still present on beta 11, any news?

**Comment by alexmady** [comment]
Confirmed - this is still broken in beta 11. enabling tabsHideOnSubPages means that the tabs are indeed hidden on sub pages but the status bar padding is lost. 

Please fix.
