### ISSUE TITLE
v2 Feature Request: Manually refresh virtual-scroll display.

### ISSUE THREAD

**Issue by JustinPierce** [driftyco/ionic#7208]
#### Short description of the problem:

I have a use case that requires me to automagically scroll a list to a specific point when the page is loaded. The list in question is using the `virtual-scroll` directive to manage its data. I'm able to calculate the position and scroll the viewport just fine. However, the `virtual-scroll` does not seem to pick up on the fact that the page has moved, and does not refresh its display. I can trick it by slowing down the scrolling animation, but this is unreliable on desktop and even more unreliable on devices. Research tells me that handling scroll events is tricky, especially on iOS, so it would be really nice if I could just manually tell the thing to refresh its display and not have to try to outsmart it.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#163
