### ISSUE TITLE
Popover created from side menu is created underneath

### ISSUE THREAD

**Issue by araujoigor** [driftyco/ionic#7209]
#### Problem description
When you create a Popover from within a side-menu, the Popover is shown below the menu and therefore is hidden until the menu is closed. 

![image](https://cloud.githubusercontent.com/assets/4449450/16598051/6e8c7ec0-42d2-11e6-80ab-f78dfd971242.png)

And after the menu is closed...

![image](https://cloud.githubusercontent.com/assets/4449450/16598072/82cffd9e-42d2-11e6-9c07-f5f1092b5560.png)

#### Expected behavior
I was expecting the Popover to show up over the menu, since it was where the action to create it took place.

I played a little with the Popover z-index, but without success.

**Steps to reproduce:**
1. Create a simple app with a side menu.
2. Create a side menu action that will trigger a Popover
3. Show the popover from the side menu

```
Code on plunker
```
 

**Which Ionic Version?** 2 Beta.10

#### Plunker that shows an example of the issue
http://plnkr.co/edit/nQR8KxxDx3M3kslhNnKb?p=preview

![image](https://cloud.githubusercontent.com/assets/4449450/16598321/adf10d28-42d3-11e6-8065-872dc8289847.png)

**Comment by jgw96** [comment]
Hello! This has actually already been fixed and will be in beta.11! We changed the api for all "overlay" components, like popovers, to make sure that they are always on top.  Thanks for opening an issue with us!
