### ISSUE TITLE
npm install ionic error - fetch failed

### ISSUE THREAD

**Issue by ErikAugust** [driftyco/ionic#7213]
npm install -g ionic is returning:

npm ERR! fetch failed https://registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

---

Tested from multiple setups!

**Comment by charlieschwabacher** [comment]
I'm having the same error from babel-plugin-syntax-do-expressions - I think this could be an issue w/ npm

**Comment by davecozens** [comment]
Looks like NPM are having CDN issues.

See https://github.com/npm/npm/issues/13284

**Comment by davecozens** [comment]
See https://github.com/npm/npm/issues/13284

**Comment by jgw96** [comment]
Hello all! After reviewing this issue it does in fact seem to be an npm issue and not an ionic issue. Because of this I will be closing this issue, but if it continues to happen please feel free to comment on this issue and I will take a look again! Thanks for using Ionic!
