### ISSUE TITLE
ionic v2 run android can not support 64bit crosswalk

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#7214]
#### Short description of the problem:
ionic v2 android can not support 64bit crosswalk

#### What behavior are you expecting?
Running properly for 64bit Android Phone.

**Steps to reproduce:**
1.  Simple android application add crosswalk plugin.
2.  running `ionic build android --xwalk64bit`
3.  running `ionic run android --xwalk64bit`
4. The running failed.

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you getting any errors when trying this? What device are you running on? Also, what version of Android is that device running? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all, since this seems to be an issue with our build process/cli i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1152
