### ISSUE TITLE
v2 beta.10: Ionic ion-input component don't work properly with new '@angular/forms'

### ISSUE THREAD

**Issue by Macstyg** [driftyco/ionic#7217]
#### Short description of the problem:
Using new '@angular/forms' module got this exception:
ORIGINAL EXCEPTION: No value accessor for: 

ngModel directive doesn't bind values from template's ion-select or ion-input fields to ts model Object and vice versa.

**Steps to reproduce:**
1. Create form in component's template with ion-input or ion-select input field
2. Include new '@angular/forms' module and import components
3. Make dependency injection in app.ts disableDeprecatedForms(), provideForms()

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually a known issue and should be fixed in beta.1 and If beta.11 does not fix this issue i will happily reopen it. Thanks for using Ionic!

**Comment by adamduren** [comment]
@jgw96 Where is the known issue that can be tracked?

**Comment by jgw96** [comment]
@adamduren Here is the exact commit https://github.com/driftyco/ionic/commit/4d56219a4c33ca32587b83d90b014ae2e374959c
