### ISSUE TITLE
Scrolling Lock Issues on List Items

### ISSUE THREAD

**Issue by ericmillsio** [driftyco/ionic#722]
See: http://forum.ionicframework.com/t/scrolling-lock-issues-on-list-items/1562/2

I am experiencing an issue where ion-lists of ion-items that are all links make the scroll lock up. If starting from a press on a link and trying to scroll, when you pull away and then go back, it locks at the exact height you originally clicked. This also only occurs on lists longer than the visible region.

Steps to recreate effect:
- Click and hold
- Drag up without letting go
- Drag down without letting go past starting point - it may lock here
- Drag back down - it will almost certainly lock

**Comment by racgl** [comment]
I am facing the same issue.
In my case it coming more frequently on android device. If my form page contains many textbox and i click randomly on the text boxes causing the key board show and hide and making the scroll view to slide-up and slide-down. It get locked from the top of the scroll.
On clicking on the any other textbox or ready only text box make it fix.
I have also used resize() on ionicscroll delegate but no luck.
