### ISSUE TITLE
Placing ion-select inside a <table> causes select to trigger regardless of where user clicks

### ISSUE THREAD

**Issue by bwalker72956** [driftyco/ionic#7220]
#### Short description of the problem:
When an ion-select is placed inside a table, it will prompt the user to select, regardless of where the user clicks in the screen.  This behavior has only been observed in a webpage.

#### What behavior are you expecting?
Select should prompt user only when the control is clicked on.

**Steps to reproduce:**
1. Click on controls, all prompts should work as selected.
2. To cause to fail, select the checkbox in the upper right.  This will add an <ion-select> to the table.
3. Now regardless of where the user clicks, the select will appear.
 
Ionic Version: 2.x

#### Plunker that shows an example of issue
Ionic 2 plnkr - http://plnkr.co/edit/wSGoGo?p=preview

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So the issue here is that `ion-select` is meant to be wrapped in `ion-item` because it needs a relatively positioned parent. I made a plunker that shows the correct way to do this [here](http://plnkr.co/edit/3rhoCx?p=preview) Thanks for using Ionic!

**Comment by bwalker72956** [comment]
Thank you.

**Comment by ericmulcahy** [comment]
Is this in the documentation anywhere?
