### ISSUE TITLE
Using new AlertController inside provider (Injectable)

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7221]
#### Short description of the problem:
I have a global Unknown error reporting service in my app which opens an alert asking the user if he wants to report the error. I used to open the alert by injecting `App` and then doing so : 
```js
let alert = Alert.create(...);

this.app.getActiveNav().present(alert);
```
When I try to inject `AlertController`, it triggers this error : 
> Cannot resolve all parameters for 'UserReport'(TranslateService, undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'UserReport' is decorated with Injectable.

Where `undefined` is supposed to be `AlertController`.

#### What behavior are you expecting?
`AlertController` to properly inject.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201606302045
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by ZiFFeL1992** [comment]
I have test this with a Toast that I have when the user gets out of connection and seems to be working.

That nightly doesn't contain `AlertController, LoadingController, ToastController`. This where my steps (don't know if there is something better):

````
1 - git clone git@github.com:driftyco/ionic.git
2 - cd ionic
3 - npm install
4 - gulp build.release && gulp tests && gulp package
5 - Update your [PROJECT]/package.json to:
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/http": "^2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4"

6 - npm install on your project directory
7 - copy ionic/dist contents to [PROJECT]/node_modules/ionic-angular
```

**Comment by jgw96** [comment]
Hello @Bouzmine this is caused by the fact that `AlertController` Is now a service, and in Angular 2 a service cannot be injected into another service. I would recommend converting your error service to a component. Thanks for using Ionic! Also, @ZiFFeL1992 it seems as if your on an older nightly. You can run `npm install ionic-angular@nightly` to install the latest one. Thanks everyone!

**Comment by jgw96** [comment]
Hello all, I am going to reopen this issue as it exposed an underlying issue with AlertController and is something we want to explore more.

**Comment by ZiFFeL1992** [comment]
@jgw96 The latest nightly is currently I bit old, that's why I compile master.

`'2.0.0-beta.10-201606302045': '2016-06-30T20:46:03.098Z'`

As I said before seems like everything is working fine, but if someone else could test will be great.

**Comment by Bouzmine** [comment]
@ZiFFeL1992 you're right, it works after following the steps above. Closing this.
