### ISSUE TITLE
`Cannot read property 'nodeName' of null` when using `*ngFor` over a fetched by json() array

### ISSUE THREAD

**Issue by msaelices** [driftyco/ionic#7222]
#### Short description of the problem:

When the template is looping for an array in a `<ion-item>`, and the array is populated with a json http query, the angular2 change detection fails. The same code was working in beta8.

#### What behavior are you expecting?

Showing all the `<ion-list>` populated with `<ion-items>`

**Steps to reproduce:**
1. copy the example code in some component
2. run `ionic serve`
3. go to the page.

```
# html
<ion-item *ngFor="let event of user.events">
  <ion-card>
    <ion-card-content>
      <ion-card-title>{{ event.name }}</ion-card-title>
      ....
    </ion-card-content>
  </ion-card>
</ion-item> 

# ts

  ionViewWillEnter() {
    this.http.request('/user/').share().subscribe(
    res => {
          this.user = res.json();   // the json is like [ {user: {id: '1', events: [{'name': 'my event', ...},...]}, ...]
    });
  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

browser_adapter.js:84 TypeError: Cannot read property 'nodeName' of null
    at ItemReorder.ngAfterContentInit (item-reorder.js:182)
    at DebugAppView._View_Item0.detectChangesInternal (Item.template.js:79)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)
    at DebugAppView.AppView.detectViewChildrenChanges (view.js:269)
    at DebugAppView._View_StreamsPage4.detectChangesInternal (StreamsPage.template.js:1533)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)
    at DebugAppView.AppView.detectContentChildrenChanges (view.js:261)
    at DebugAppView._View_StreamsPage3.detectChangesInternal (StreamsPage.template.js:944)

**Which Ionic Version?** 2.0-beta10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.4.3

**Comment by msaelices** [comment]
Debugging the problem. The problem is that inside the `<ion-item>` I had another child `<ion-item>` and this caused the problem. Changing the inner `<ion-item>` to a `<div>` solves the problem.

**Comment by manucorporat** [comment]
do you have any reorder attribute/input in your templates?

**Comment by msaelices** [comment]
nope

**Comment by msaelices** [comment]
This is the exact template I used:

    <ion-list no-lines>
      <ion-item class="event-card" *ngFor="let event of eventList.events" [class.premium]="event.is_premium">
        <ion-card>
          <ion-card-content>
            <img class="poster" (click)="goToEvent(event)" src="{{ event.poster_large || 'img/amsterdam.png' }}"/>
            <div class="gradient" (click)="goToEvent(event)"></div>
            <div *ngIf="event.time_category == 'live'" class="live-symbol streaming">
              <div class="live-symbol-inner">
                <div class="circle"></div>
                Live
              </div>
            </div>
            <img *ngIf="event.is_premium" class="premium-deco" src="img/premium_deco.png" />
            <ion-avatar item-left>
              <img (click)="goToEvent(event)" [src]="event.user.avatar_thumbnail || 'img/dummy-avatar.png'" [alt]="event.user.full_name">
            </ion-avatar>
            <a class="user-link" *ngIf="event.user.id != user.id" (click)="goToEvent(event)">{{ event.user.first_name }}</a>
            <a class="user-link" *ngIf="event.user.id == user.id">You</a>
            <ion-card-title>
              {{ event.name }}
            </ion-card-title>
            <ion-badge class="price" *ngIf="event.is_premium" item-right>{{ event.price }} pts/min</ion-badge>
            <ion-item class="event-stats">
              <ion-badge item-left>{{ event.views_count }} views</ion-badge>
            </ion-item>
            <img *ngIf="event.device == 'glasses'" class="shot-on-glasses" src="img/shot_on_glass.png" />
          </ion-card-content>
        </ion-card>
        <div class="event-device">
          <ion-badge item-right class="{{ event.device }}"></ion-badge>
        </div>
      </ion-item>
    </ion-list>

Changing the `<ion-item class="event-stats">...</ion-item>` to `<div class="event-stats">...</div>` I solved the issue

**Comment by manucorporat** [comment]
ok! I just tried to figure out why it happened, it didn't make sense to me! This should be fixed anyway in next beta :) thanks for reporting!
