### ISSUE TITLE
ionic-angular@2.0.0-beta.10 preloadTabs won't work anymore

### ISSUE THREAD

**Issue by elineopsommer** [driftyco/ionic#7226]
#### Short description of the problem:
If you start a new ionic project with the tabs-template (includes beta.10), then the preloading of the tabs won't work anymore. If you serve the code and then switch to another tab, you still see the content of the first tab.

#### What behavior are you expecting?
Correct behaviour of the tabs.

**Steps to reproduce:**
1. ionic start MyIonic2Project --v2
2. place preloadTabs="true" in the <ion-tabs> element (<ion-tabs preloadTabs="true">)
3. ionic serve

```
<ion-tabs preloadTabs="true">
    <ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="home"></ion-tab>
    <ion-tab [root]="tab2Root" tabTitle="About" tabIcon="information-circle"></ion-tab>
    <ion-tab [root]="tab3Root" tabTitle="Contact" tabIcon="contacts"></ion-tab>
</ion-tabs>

```

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
Thanks for the report! this will be fixed in next release!
