### ISSUE TITLE
$ionicScrollDelegate not working properly on browser and android

### ISSUE THREAD

**Issue by sinedied** [driftyco/ionic#7227]
#### Short description of the problem:

$ionicScrollDelegate scroll function cause scrolling to be disabled on browser and android when animation is enabled.
#### What behavior are you expecting?

After having scrolled to a defined position, the user can scroll normally.

**Steps to reproduce:**
1. Enable scroll delegate on a ion-content directive with content overflow
2. Scroll to fixed value using $ionicScrollDelegate with animation
3. On iOS, there is no issue. On android and browser, scrolling become disabled (ion-content has an inline style="overflow: hidden" and it should not).

**Which Ionic Version?** 1.3.1
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

`COMING SOON (if needed`

**Run `ionic info` from terminal/cmd prompt:** 

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by sinedied** [comment]
I could not reproduce it in a plunker, it's even worse there: $ionicScrollDelegate does not work at all on the browser, I'm investigating a way to reproduce the issue for you.

**Comment by sinedied** [comment]
After investigation, this bug seems related to https://github.com/driftyco/ionic/issues/6544 as the cause seems the same: the `<ion-content>` or `<ion-scroll>` element has an incorrect `style="overflow: hidden:` attribute set or missing, depending of the issue.

I could not find in the ionic code where this styling comes from, any pointers so I may help your job by narrowing down the faulty lines?

**Comment by johannds** [comment]
Any news on this? I'm seeing the same thing happen on Android.

**Comment by saba-m** [comment]
I was having same issue but figured that there was a class overflow-scroll added to my ion-content tag which was overriding ionic default scroll. So i solved it by setting overflow-scroll="false".
<ion-content overflow-scroll ="fasle">

</ion-content>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#111
