### ISSUE TITLE
Navbar contents are not centered on iPhone SE

### ISSUE THREAD

**Issue by modev32** [driftyco/ionic#7230]
I have tested this on various emulators but it seems to be ok except when i test it on my own phone iPhone se. the attached photo explains everything. It only happened after i updated to Ionic 2 beta 10. tested on various projects even the once included in Ionic's docs, still the same problem.

![index](https://cloud.githubusercontent.com/assets/5760890/16670052/19b3e87c-44a1-11e6-94af-eb049f9ff558.png)

I tried to remove navbar buttons but still the same issue.

```
<ion-header>
  <ion-navbar main>
    <button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Hello Ionic</ion-title>
  </ion-navbar>
</ion-header>
```

**Which Ionic Version?** 1.x or 2.x
2.0 beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment]
Are you viewing this in a deployed app or in Ionic View?

**Comment by windwp** [comment]
+1,
Same issue with navbar when upgrade to ionic beta 10

**Comment by modev32** [comment]
In Ionic Viewer

**Comment by brandyscarney** [comment]
If you're viewing this in Ionic View it is an issue with Ionic View itself. There is an issue created here for this: https://github.com/driftyco/ionic-view-issues/issues/164

Thanks for the issue!
