### ISSUE TITLE
ion-navbar disappears with input keyboard

### ISSUE THREAD

**Issue by gadld** [driftyco/ionic#7231]
#### Short description of the problem:
When you have a long form with text inputs, and you go to one of the last inputs the ion-navbar pushes outside the screen with the keyboard

#### What behavior are you expecting?
the ion-navbar should not disappear

**Steps to reproduce:**
1. start a new conference app `ionic start Test conference --v2`
2. Go to file signup.html and copy and paste the username item 15 times
3. run the app on an iOS 9.3.1
4. Go to the signup page, click on the first input and try to scroll to the bottom

**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0

**Comment by cjpollard** [comment]
Seeing this issue as well.

**Comment by gadld** [comment]
Any news on this?

**Comment by vietanh7** [comment]
I'm seeing this issue as well. Does someone in ionic have news on this. I don't know why there is so many keyboard issues in iOS

**Comment by haihoang88** [comment]
Is there anyone know how to deal with this problem?

**Comment by jgw96** [comment]
Hello all! We are currently looking into the scrolling issues with iOS. Would you all mind testing this issue with [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine). Thanks!
