### ISSUE TITLE
v2:bug(header) header overlay content if dynamically change headers height

### ISSUE THREAD

**Issue by DavidWiesner** [driftyco/ionic#7232]
#### Short description of the problem:
If you have a page with a ion-header and add an toolbar dynamically this toolbar will overlay the content. On the other way, if the header initially contains multiple toolbars and you hide them later, the content doesn't get repositioned. 

#### What behavior are you expecting?
The content should adapt the position to the height of the ion-header if this change dynamically.

**Steps to reproduce:**
1. Create new Page add with two toolbars, 
2. hide one of them initially
3. show them e.g. after a timeout or a button click
4. content gets overlayed :cry: 

**Which Ionic Version?**  
2.0.beta-10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/1wvClEZvMqhlcvlQHrDQ?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.5 (jessie) 
Node Version: v5.12.0

**Comment by brandyscarney** [comment]
The `resize` function on content was added for this purpose. It isn't available in `beta 10` but it is in the nightly and will be in `beta 11`. Here are the docs on it (not yet live on the official docs): http://ionic-site-staging.herokuapp.com/docs/v2/api/components/content/Content/#resize

If you'd like to try out the nightly you can install it by using:

```
npm install --save ionic-angular@nightly
```

Thanks!

**Comment by DavidWiesner** [comment]
Ok, thanks for the answer. 

Here is my workaround **until beta 11 gets released**
```typescript
    @ViewChild(Content) content: Content;
   
    toggleSearch(){
        this.searchVisible = !this.searchVisible;
        setTimeout(()=>{
                this.content.readDimensions();
                this.content.writeDimensions();
        },0 );
    }
````
