### ISSUE TITLE
[Feature Request] Header with image collapse on scroll

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#7234]
Would be awesome to have this kind of headers:

Android: http://imgur.com/dpoQnFS
iOS: http://g.recordit.co/kUN3F0zZJ4.gif

**Comment by saurabhvyas** [comment]
I agree

**Comment by saescapa** [comment]
Would be awesome

**Comment by royipressburger** [comment]
+1

**Comment by jgw96** [comment]
Hello all! At this time this is not something we plan on implementing in the framework, but it should be relatively easy for it to be done with the new layout refactor and would be awesome to see the community implement. Thanks for opening this issue, and if at some time in the future we decide to implement this in the framework i will reopen this issue. Thanks again!
