### ISSUE TITLE
ionic-angular@2.0.0-beta.10 navcontroller.push page not working

### ISSUE THREAD

**Issue by elineopsommer** [driftyco/ionic#7236]
#### Short description of the problem:
If you push a detailpagina on a tabspage, the detailpage overlaps the tabs, which isn't meant to. You can set the css of the ion-tabbar to an z-index of 1000, then the tabs will stay, but if you then click on another tab, the content of the detailpage stays visible instead of the content of the chosen tab.

#### What behavior are you expecting?
Correct behaviour of the tabs

**Steps to reproduce:**
1. ionic start testtab --v2
2. add a button which pushes the detailpage on a tab
3. ionic serve

```
goToDetail() {
	  this.nav.push(Detailpage);
	}
```

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/IYhrIxIx7I17zi9V3H2y?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by brandyscarney** [comment]
This is the desired behavior for `md` mode. To change this you can set `tabSubPages` to `false`. Note: this property has been renamed for `beta 11` to `tabsHideOnSubPages` (see https://github.com/driftyco/ionic/issues/7143).

Please see the config docs for more information on setting these properties: http://ionicframework.com/docs/v2/api/config/Config/

There is also a table further down with descriptions of each property.
