### ISSUE TITLE
<input type="text"> styling not working in ios. 

### ISSUE THREAD

**Issue by Macstyg** [driftyco/ionic#7238]
Input field not display correctly in iphone 6, thru the ionic-view application. The font-size of letters is bigger then the input height and no css styles apply to it at all. But it works fine in android device and when running it in web browser. 

```
    <ion-row>
      <ion-col>
        <input type="text" class="pin-input" maxlength="1" [(ngModel)]="hotelRegister1" #hotelR1 (keyup)="onKey(hotelR1.value, hotelR2, hotelR1)" autofocus="true">
      </ion-col>
      <ion-col>
        <input type="text" class="pin-input" maxlength="1" [(ngModel)]="hotelRegister2" #hotelR2 (keyup)="onKey(hotelR2.value, hotelR3, hotelR1)">
      </ion-col>
      <ion-col>
        <input type="text" class="pin-input" maxlength="1" [(ngModel)]="hotelRegister3" #hotelR3 (keyup)="onKey(hotelR3.value, hotelR4, hotelR2)">
      </ion-col>
      <ion-col>
        <input type="text" class="pin-input" maxlength="1" [(ngModel)]="hotelRegister4" #hotelR4 (keyup)="onKey(hotelR4.value, hotelR4, hotelR3)">
      </ion-col>
    </ion-row>
```
**Which Ionic Version?** 2.x

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Is there a reason you are not using our [ion-input](http://ionicframework.com/docs/v2/components/#inputs)?

**Comment by Macstyg** [comment]
Because data-binding with ion-input don't work correctly with new angular/forms module

**Comment by jgw96** [comment]
ahh ok, this will actually be fixed in the beta.11 release (: If you would like to try it now you can install ionic 2 nightly by running `npm install ionic-angular@nightly` . By using `ion-input` your styling issues will also be fixed. Thanks for using Ionic!
