### ISSUE TITLE
Missing datetime picker

### ISSUE THREAD

**Issue by michelebravo** [driftyco/ionic#7239]
Hello! 

I need a datetime picker for my "Ionic 1" app. I have tested a lot of plugins but none of them seem to work very well because graphic's flickening or code don't working very well. 
Are you going to integrate in the near future an official Ionic datetime picker? 

Thank you for your attention!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we are not planning on adding a datetime picker to ionic 1, although we do have [one](http://ionicframework.com/docs/v2/api/components/datetime/DateTime/) for Ionic 2. You can use the native html5 [date input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) in ionic 1 to get similar functionality. This should work well for you on all platforms! Thanks for using Ionic!
