### ISSUE TITLE
Angular2 animation easing not working

### ISSUE THREAD

**Issue by awe-sim** [driftyco/ionic#7240]
#### Short description of the problem:

I was trying to create a roll-up/down component. Angular2 provides animations functionality out-of-the-box that you can attach to your component. For my component, the component animates, however the animation easing is not respected. The animation ease is always linear.

The component is as follows:

	import {Component, Directive, Input} from '@angular/core';
	import {trigger, state, style, transition, animate} from '@angular/core'

	@Component({
		selector: 'expandable',
		templateUrl: `<div *ngIf="isExpanded" @animate="'slide'"><ng-content></ng-content></div>`,
		animations: [
			trigger('animate', [
				state('slide', style({ overflow: 'hidden', height: '*' })),
				transition('slide => void', [animate('2000ms ease', style({ height: 0 }))]),
				transition('void => slide', [style({ overflow: 'hidden', height: 0 }), animate('2000ms ease',  style({ height: '*' }))]),
			])
		]
	})
	export class SimExpandable {
		private _expanded: boolean = false;
		@Input('expanded') set expanded(value: string | boolean) {
			this._expanded = (value === 'true' || value === true);
		}
		get isExpanded(): boolean { return this._expanded }
	}

It can be used like so:

	<button (click)="myFlag=!myFlag">HEADING</button>
	<expandable [expanded]="myFlag">
		<ion-card>
			<p>Hello</p>
			<p>World</p>
		</ion-card>
	</expandable>

I've created an [Angular 2 Plunkr](http://plnkr.co/edit/yS4ksXpXQekLfLlJPZKf?p=preview) and the animation works fine there. I haven't been able to create a corresponding an Ionic 2 Plunkr as the plunkr reports all of the symbols in the following line are `undefined`:

`import { trigger, state, style, transition, animate } from '@angular/core'`

#### What behavior are you expecting?

Like the [Angular 2 Plunkr](http://plnkr.co/edit/yS4ksXpXQekLfLlJPZKf?p=preview), I'd expect that the animation ease mentioned should be respected, and not always linear.

**Steps to reproduce:**
1. Create a blank application. 
2. Add the component TS listed above.
3. Use the component as listed in code above.
4. Run the application and try clicking the button. The `div` should roll-up/down starting slowly, speeding up and then stopping slowly as well. It doesn't for me and the entire motion is at constant speed. Compare it to the [Angular 2 Plunkr](http://plnkr.co/edit/yS4ksXpXQekLfLlJPZKf?p=preview) and you'll see the difference.

**Which Ionic Version?** 1.x or 2.x

I'm using 2.x. I've tried both `angular-ionic@beta` and `angular-ionic@nightly`.

#### Plunker that shows an example of your issue

http://plnkr.co/edit/yS4ksXpXQekLfLlJPZKf?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**My application**
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201606302045
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014 

**My test application**
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by danbucholtz** [comment]
Hi @awe-sim,

Angular Animation is still very much a WIP.  I have been trying to build some demos with Ionic to utilize it and have run into some issues.  I did some digging and there are significant animation fixes due for Angular 2 RC 5.

Please make an issue for your issue on the Angular repository as this isn't something we can resolve.  Thanks for contributing to Ionic!

Thanks,
Dan

**Comment by awe-sim** [comment]
Hi @danbucholtz.. I understand this is probably not an Ionic2 issue but rather an Angular2 one.. However, I raised it here cuz Ionic2 is built on top of Angular2 itself, and it could be that the base Angular2 library used by Ionic is older/out-of-date.. Can you at least tell me what version difference is there between the Angular2 library in the [Plunkr](http://plnkr.co/edit/yS4ksXpXQekLfLlJPZKf?p=preview) I created vs my application (for which I pasted the output of `ionic info`)?

**Comment by danbucholtz** [comment]
@awe-sim,

Beta 10 is running Angular RC3.  Can you recreate the issue in a vanilla Angular app?  Like I said, ngAnimate in V2 has a few WIP issues right now scheduled to drop in RC5.  I have had a lot of challenges with it myself.

Thanks,
Dan

**Comment by awe-sim** [comment]
Hi @danbucholtz .. Thanks a lot for that info.. That was sufficient enough to resolve the issue.. The Plunkr I created was running Angular2rc4.. RC4 fixes an animation issue in RC3 which is the same one as I encountered.. [animation : Easing functions not working](https://github.com/angular/angular/issues/9517)..

Thank you for your time.. Keep up the good work.. =)

**Comment by jgw96** [comment]
@awe-sim also, just so you know the upcoming beta.11 release will be running RC4, so your animations should work fine there. Thanks!

**Comment by danbucholtz** [comment]
@awe-sim, sounds great!  Should be resolved soon!  w00t!

Thanks!
Dan
