### ISSUE TITLE
Ionic V2 beta 10: VirtualScroll and padding-horizontal attribute not working together.

### ISSUE THREAD

**Issue by oz-frog** [driftyco/ionic#7244]
Ionic Framework Version: 2.0.0-beta.10

Considering the following VirtuallScroll setup:
```<ion-list padding-horizontal [virtualScroll]="data">
    <button clear dark block ion-item *virtualItem="let item" (click)="select(item)">
         {{item}}
    </button>
 </ion-list>```
The padding-horizontal attribute is only applied to the first item in the list when it renders, subsequent items are not rendered. Works without the VirtualScroll setup.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
