### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'touches' of object '#<TouchEvent>'

### ISSUE THREAD

**Issue by exos** [driftyco/ionic#7245]
Error throwed by HandleTouchStart on $ionicRefresher controller:

(minified) : 
```JavaScript
                        function handleTouchstart(e) {
                            e.touches = e.touches || [{
                                screenX: e.screenX,
                                screenY: e.screenY
                            }];
                            startY = e.touches[0].screenY;
                        }
```

Testing in Chromium

```
$ chromium --version
Chromium 51.0.2704.84
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by kwv** [comment]
Not sure if this is related to https://github.com/driftyco/ionic/issues/8181  but commenting out the assignment to e.touches in handleTouchmove and handleTouchstart appears to provide relief. 


"Mozilla/5.0 (Linux; Android 5.0.1; SPH-L720T Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Crosswalk/21.51.546.7 Mobile Safari/537.36"

    //   e.touches = e.touches || [{
    //     screenX: e.screenX,
    //     screenY: e.screenY
    //   }];


per https://developer.mozilla.org/en-US/docs/Web/Events/touchmove it looks like touches is readonly.

**Comment by AlexWebYourmind** [comment]
The workaround mentioned by @kwv  works also for me (I got the same error in an Ionic 1.3.3 project), but is there any chance to get a proper fix on 1.x?
