### ISSUE TITLE
The openlayer's map is blank in the view when back from another view after opened a modal

### ISSUE THREAD

**Issue by King-JXN** [driftyco/ionic#7246]
I make a simple map app using ionic frame and openlayers 3. It goes wrong when I switch views which each have a map.The details are as flow:
1. Run the app;
2. Switch to Chats view from Dash view;
3. Click button to open a modal and click back button to hide the modal;
4. Switch to Dash view to Chats view;
Then you will find the map is blank.
There is my project: https://github.com/King-JXN/MapTest.git

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
