### ISSUE TITLE
Create a new Alert after a User takes a picture in Ionic 2@master

### ISSUE THREAD

**Issue by pacMakaveli** [driftyco/ionic#7248]
#### Short description of the problem:

Trying to display an alert after the User either takes a new picture with the Camera or choses an existing one from Library.

#### What behavior are you expecting?

Once the User takes a picture or selects a new one, an Alert should pop-up to confirm that the user wants to replace the existing image, if there is one.

After I take the picture, the script completely ignores the Alert, even though my `console.log` inside `confirmFloorplanReplace` is outputting just fine.

**Steps to reproduce:**

``` js
  locationFormCaptureFloorplan(source) {
    Camera.getPicture({
      destinationType: Camera.DestinationType.FILE_URI,
      sourceType: (source == 'CAMERA' ? Camera.PictureSourceType.CAMERA : Camera.PictureSourceType.PHOTOLIBRARY),
      encodingType: Camera.EncodingType.PNG,
      allowEdit: true,
      targetWidth: 1920,
      targetHeight: 1080
    }).then(
      (imageData) => {

        if(this.model.location.floorplan !== null) {
          this.confirmFloorplanReplace(imageData);
        } else {
          this.floorplanImage = imageData;
        }
      },

      (error) => {

        if(this.model.location.floorplan !== null) {
          this.confirmFloorplanReplace("data:image/jpeg;");
        } else {
          this.floorplanImage = "data:image/jpeg;";
        }

        this.showToast(error);
      }
    );
  }

  confirmFloorplanReplace(imageData) {
    let confirmAlert = this.alertCtrl.create({
      title: 'Are you sure?',
      message: 'This cannot be undone!',
      buttons: [
        {
          text: 'No',
          handler: () => {
            console.log('Crysis averted');
          }
        },
        {
          text: "Yes",
          handler: () => {
            this.floorplanImage = imageData;
          }
        }
      ]
    });

    confirmAlert.present();
  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
**Which Ionic Version?** 2.0 nightly ( latest master )

Not sure if this is an actual bug and more of a 'you can't really do that' from Ionic.

#### Plunker that shows an example of your issue

http://plnkr.co/edit/xrCt1PsT4vdbQkZlJ8lS?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Sorry, I tried creating a plunker but I don't know how to use the master version of Ionic with plunker. @nightly on plunker doesn't have all the new additions like 'AlertController' **

If this is an actual bug and you really need a plunker for further investigation please let me know and I'll recreate my script using the latest available Ionic on plunker.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! It would be great if you could create a plunker that demonstrates this issue with the latest stable branch. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
