### ISSUE TITLE
ionic v2 project  use ionic emulate ios --cl  start emulate but alway loading 

### ISSUE THREAD

**Issue by tslearn** [driftyco/ionic#7249]
**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
ionic start test --v2
ionic emulate ios -cl

**Comment by jgw96** [comment]
Hello, since this issue seems to be an issue with the ionic cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1167
