### ISSUE TITLE
Feature Request: popToIndex()

### ISSUE THREAD

**Issue by Rambatino** [driftyco/ionic#7250]
#### Short description of the problem:

I found that popping to a specific index in the navigation stack was more difficult than I thought it should be. If it isn't the first view (whereby `popToRoot` can be used) and you don't have a reference to a specific ViewController (whereby `popTo` can be used), it requires (or so I presume) that `remove` must be called, removing all but the current ViewController and then `pop` followed afterwards to pop back. 

#### What behavior are you expecting?

A method such as `popToIndex`.

If you determine value to this new feature in nav-controller.ts, would I be able to fork and create a PR following the contribution guidelines?

**Which Ionic Version?** 2.x
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
@Rambatino hi, can you explain the use case this feature could be useful?

**Comment by Rambatino** [comment]
If you have a variable number of pages (determined by specific choices the user makes during their navigation) culminating in a specific action, for instance, by sending an email and then to pop back to a specific ViewController (let's say at the third level of the stack)

I could keep track of how many pages the user navigated, or keep hold of the reference to the original ViewController, but it would be much cleaner if I could just pop to a specific index on the stack, that I know is consistent.

**Comment by Rambatino** [comment]
@manucorporat any update? Can I build and spec it?

**Comment by manucorporat** [comment]
Hi @Rambatino I have been talking with my team about this feature and we all agree this is not a good idea, it looks like an error prone API.

A stack structure does not have indexes like an array does (even so under the hood it can be implemented with an array).

"(let's say at the third level of the stack)" how do you know it is the third level of the stack?

You could have a different stack somehow, and the index would be different each time and not what they intended when you hardcoded the number.

`popTo` is the correct API you should try to use.

Thanks for your time!
