### ISSUE TITLE
bug: Ionic2 Ion-slides not working in the first tab

### ISSUE THREAD

**Issue by twinssbc** [driftyco/ionic#7251]
#### Short description of the problem:
I notice that Ion-Slides is not working in the first tab, but works in the second tab.
Does not work means when sweeping, the slide control doesn't go to next slide.

**Steps to reproduce:**
1. Simply use the tabs template to start and put the ion-slides code in the ion-content.

**Investigation:** 
I think I found the root cause.
When sliding to the next slide, it needs to use the slideSize.
```
slideSize = (s.size - (s.params.slidesPerView - 1) * spaceBetween) / s.params.slidesPerView;
```
The slideSize depends on s.size, which is calculated by s.updateContainerSize
```
          if (typeof s.params.width !== 'undefined') {
              width = s.params.width;
          }
          else {
              width = s.container[0].clientWidth;
          }
```
The problem is s.container[0] is not displayed in the view yet, so the width is 0.
The s.updateContainerSize is called in the Sweeper constructor and Sweeper constructor is called in the ngOnInit function of the slide component.
```
        setTimeout(function () {
            var swiper = new swiper_widget_1.Swiper(_this.getNativeElement().children[0], options);
            _this.slider = swiper;
        });
```
I'm thinking it should probably be called in the ngAfterViewInit function.
 

**Which Ionic Version?** 2.0.0-beta.10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3.1 Build version 7D1014 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

**Comment by nikoTM** [comment]
Happens for me as well

**Comment by jgw96** [comment]
Hello all! This has actually already been fixed and will be in the next release of Ionic 2. If you would like to try it out now you can install the latest bleeding edge nightly with `npm install ionic-angular@nightly`. Thanks for using Ionic!
