### ISSUE TITLE
Ionic 2, InAppBrowser.js, errors when building to Android

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#7254]
Hi

I'm trying to track down why it is that I cannot get the InAppBrowser to just open on single click.

I've added the plugin, and included this line:

`import {InAppBrowser} from 'ionic-native';`

then a simple InAppBrowser.open just to check. Not working.

I'm having a look at the Ionic Native source code, InAppBrowser.js, and my code editor is highlighting 2 errors in the code at:

line 5 - expected a conditional and saw an assignment
`else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;`

line 26 - InAppbrowser is a function
`InAppBrowser = __decorate([`

I'm new to Ionic, and to betas in general, but I thought I should report this as I can't get it to work.

Tom

**Comment by jgw96** [comment]
Hello! As this is an issue with ionic-native and not the ionic framework I will be moving this issue to that repo. Welcome to the world of Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#285
