### ISSUE TITLE
Ionic Serve gives blank screen

### ISSUE THREAD

**Issue by saurabhvyas** [driftyco/ionic#7255]
#### Short description of the problem:
I am getting white screen on chrome with following message in console : 
```
2http://192.168.1.34:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
content_site?integration=anywhere&v=n11.6.1.78&os_mj=10&os_mn=0&os_bitness=64&mid=ec7e3e538ce62e00f…:373 Uncaught TypeError: Cannot read property 'appendChild' of undefined
```

Ionic Info
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9-201606271842
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v5.12.0

Earlier it was working , I did a commit after removing untracked files and it stopped working , I tried everything including cloning again from my git rep, removing node_modules folder manually and reinstalling it, nothing works.

Funny thing is the conference app still works which uses beta 10 , and I have another project which uses beta 6 which also works

insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x


#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview


**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
