### ISSUE TITLE
Splash screen animation too fast, App load too slow

### ISSUE THREAD

**Issue by CarlRyds** [driftyco/ionic#7258]
Splash screen animation is too fast and then goes to white and App loading is slow

Splash screen should stay up till App is loaded in the backgrounds

**Steps to reproduce:**

1.  Open an ionic 2 app on an Android Lollypop device

**Which Ionic Version?**

2.0 BETA 10

**Video**

https://www.youtube.com/watch?v=bN4Yl3-LNqc

**Comment by ghenry22** [comment]
You can configure the splashscreen delay in your config.xml, if you read the splashscreen plugin docs you can also manually remove it when your app has finished loding

**Comment by daveshirman** [comment]
this might help?

http://www.codingandclimbing.co.uk/blog/ionic-2-fix-splash-screen-white-screen-issue-14

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
