### ISSUE TITLE
Critical Issue/Bug related to ion-radio

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7259]
I updated my IONIC2 project from beta 7 to beta 10, in beta 7 the below code was working perfectly; however, after the update it stopped working.

**The expected behavior (was working on beta 7):**
When the user clicks only on a radio button, it should be checked.

**The current behavior:**
When the user clicks anywhere on the screen the radio button is checked.

I guess the issue is somehow related to this line, when I removed and try to click anywhere on the screen nothing is checked which is totally normal, that's why I guess that it's a bug related to Beta 10:

                  <ion-radio checked="false" value="option1"></ion-radio>

Below is the non-working code (was working on beta 7):

               <ion-header>
				<ion-navbar>
				  <ion-title>CHECKOUT</ion-title>
				</ion-navbar>
				</ion-header>

				<ion-content padding class="checkout">
				<div class="listTitle">PLEASE CHOOSE ONE OF THE BELOW OPTIONS</div>

						<ion-list radio-group [(ngModel)]="content">

						<ion-item *ngIf="(option1)" class="listItems">
							<ion-label>{{option1}}</ion-label>
							<ion-radio checked="false" value="option1"></ion-radio>
						</ion-item>

				<div class="spacing"></div>
				</ion-content>

				<ion-footer class="orderNowFooter">
				<button class="orderButton" [disabled]="!content">
				 	<div class="centeredWhiteText">ORDER NOW</div>
				</button>
				</ion-footer>

Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by HamzaLJ** [comment]
The issue was in my `css` file as I was styling the class `.item` I guess it caused confusion that's why it stopped everything.
Anyway, please close issue as I was able to solve it.

**Comment by jimitndiaye** [comment]
Not sure if relate but your ```<ion-list>``` tag is not closed in your html above
