### ISSUE TITLE
Android keyboard not retained on textbox within virtualScroll list 

### ISSUE THREAD

**Issue by aduttonomni** [driftyco/ionic#7264]
#### Short description of the problem:

When a text box (ion-input type text) is used within an ion-list marked with virtualScroll on android, when the text box is tapped on the keyboard comes up but then goes down again and the focus on the text box is lost.
#### What behavior are you expecting?

The text box should keep the focus and the keyboard remain up so the the user can type into the text box.

**Steps to reproduce:**
1. On the plnkr below, build it in to an app to run on Android.
2. Go to page1
3. With the keyboard down, tap on one of the ion-items in the list to put focus on a text box.
4. The keyboard comes up briefly and then goes down again as focus is lost.

list:
  `<ion-list [virtualScroll]="items">
    <ion-item *virtualItem="let item">
      <ion-input [(ngModel)]="item.value" type="text"></ion-input>
    </ion-item>    
  </ion-list>`

**Other information:** 
This works without issue in the browser (mac/pc) and on iOS
Tested on Android 4.4.2 and 5.1.1 
Note than in the plnkr example, tapping on the text box in the header which is outside the virtual list works fine. Also, if tapping on this header text box first brings up the keyboard. Tapping on a text box in the list whilst the keyboard is already up also works.
It works correctly without the virtualScroll on the ion-list
I have seen a similar issue before on a different js framework and it came about because the keyboard coming up on Android triggered a resize event which recreated the list, losing the focus on the selected textbook, which then means the keyboard comes gown again. 

**Which Ionic Version?** 1.x or 2.x
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
#### Plunker that shows an example of your issue

http://plnkr.co/edit/S3CbtIuOp31xYErup3ep?p=preview

**Comment by jalef** [comment]
I have the same issue, even if the input is not in an ion-list
this is a plunker that if built in android demonstrates the problem
[http://plnkr.co/edit/GFOUnEeitVpF6o8GSAxU?p=preview](url)

**Comment by aduttonomni** [comment]
Retested on RC4. Appears to be fixed.
