### ISSUE TITLE
bug: Issue with selectbox in Ionic 2

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#7266]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>
Selected item not working when binding to an array of objects. Also I noticed that in nightly, the text labels for each option are hidden, whereas in 2 beta 10 the text labels do show up.

http://plnkr.co/edit/q04871weGL6dXnfLJeza?p=preview
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello @tones411 , is this still an issue with beta.11? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
