### ISSUE TITLE
v2:bug(menuToggle) menuToggle not work in toolbar

### ISSUE THREAD

**Issue by DavidWiesner** [driftyco/ionic#7267]
#### Short description of the problem:
Using the directive `menuToggle` doesn't work like expected its always shown the menu button. No matter is the first page in the navigation stack or not.

#### What behavior are you expecting?
Akording  to the [MenuToggle/#usage](http://ionicframework.com/docs/v2/api/components/menu/MenuToggle/#usage) docs. The `menuToggle` should also work in the toolbar.

**Steps to reproduce:**
1. generate a new page
2. add toolbar with a `menuToggle` button
3. push this page as second element to the navigation stack

```
<ion-header>
  <ion-toolbar primary>
    <button menuToggle>
        <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>
      Ionic 2
    </ion-title>
  </ion-toolbar>
</ion-header>
```

**Which Ionic Version?** 2.0.0-beta.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/ftMgqk2BfzbCysDItJgs?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.5 (jessie) 
Node Version: v5.12.0

**Comment by brandyscarney** [comment]
The `menuToggle` directive can be added to any button, so when we say it works we mean it can be clicked to toggle the menu from anywhere in the content, toolbar or navbar. It will only hide on subpages when it is placed inside of a `ion-navbar`. The beginning of the [menuToggle docs](http://ionicframework.com/docs/v2/api/components/menu/MenuToggle/) explains this:

> The menuToggle directive can be placed on any button to toggle a menu open or closed. If it is added to the NavBar of a page, the button will only appear when the page it's in is currently a root page. See the Menu Navigation Bar Behavior docs for more information.

Which links to this further description: http://ionicframework.com/docs/v2/api/components/menu/Menu/#navigation-bar-behavior

Thanks!

**Comment by xxxdepy** [comment]
I was facing the same issue and ended up here from a Google search. I would say this is a very common issue for people who haven't gone deeper into the docs, so for those who would not take the time to go through the docs here's the answer to how to change that behaviour:

add `persistent="true"` to the `<ion-menu>` element being used. 

More about it on the docs linked above.

**Comment by prathyushp1** [comment]
use click function instead of menuToggle

<button ion-button icon-only start (click)="openSideMenu()">
           <ion-icon name="md-menu"></ion-icon>
</button>

openSideMenu() {
   this.menuCtrl.enable(true)
    this.menuCtrl.toggle();    
}

disable menu before you push to new page

this.menuCtrl.enable(false)

**Comment by supriyaskolase** [comment]
I applied same code.
TypeError: _co.openSideMenu is not a function
    at Object.eval [as handleEvent] (ng:///AppModule/UserPage.ngfactory.js:164:31)
    at handleEvent (http://localhost:8100/build/vendor.js:13963:155)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:15059:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10378:25)
    at http://localhost:8100/build/vendor.js:11003:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:39320:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
