### ISSUE TITLE
Ionic 2 : CLI "ionic resources" doesn't generate icon and splashscreen

### ISSUE THREAD

**Issue by pom421** [driftyco/ionic#7269]
#### Short description of the problem:

When i use the CLI and the command :

```sh
$ ionic resources
```

this is the answer : 
```
(node:8537) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.png...
```

When i inspect the generated code, well, it seems that nothing is generated :  

- config.xml is not modified 
- resources/android/icon (for example) is not updated with the new icons
- platforms/android/res/drawable-hdpi (for example) is not updated too

Same thing for iOS for icon and splash. 

**Which Ionic Version?** 1.x or 2.x

I use ionic 2.0.0-beta.32 on OS X 10.11.4 (El Capitan).
I have generated a tutorial project with the CLI like that : 

```sh
$ ionic start biblio tutorial --v2
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1166
