### ISSUE TITLE
feat: [Feat] Add ion-datetime form validation classes

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7270]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently any input receives some clases in function of it's state, the most clear example is `ng-valid` and `ng-invalid`, however the `ion-datetime` component doesn't apply those type of classes on itself.

To provide the user with better output depending on validation state we need those classes.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#693

**Comment by brandyscarney** [comment]
Oops. Moved the wrong issue.

**Comment by Luchillo** [comment]
😄

**Comment by Luchillo** [comment]
@brandyscarney How's the state of this issue?

**Comment by brandyscarney** [comment]
@Luchillo Hmm I'm seeing the classes applied to the `ion-datetime`. Do you mean you want them added to `ion-item`?

**Comment by Luchillo** [comment]
Weird, i can also see the classes, maybe it was because i was using the new Forms API which you guys will support in Beta.11, i had to revert to Deprecated Forms API, maybe i couldn't see it because the new Forms weren't supported?.

**Comment by brandyscarney** [comment]
Yeah maybe. Let me know if you run into the issue again. :)

**Comment by aperezbaena-csc** [comment]
Form validation classes are not added to `ion-datetime` hosted in a `ion-item`. They are if `ion-item` is removed from the form.

Using ionic-angular 2.0.0-rc1.

**Comment by keithdmoore** [comment]
This may be a separate issue, but when using `ion-datetime` in a form with `ion-item`, the `ngModel` attribute does NOT get set.  

```
<form (ngSubmit)="save()" #userProfileForm="ngForm">
  <ion-item>
    <ion-label stacked>Birth Day/Month</ion-label>
    <ion-datetime displayFormat="MMM D" [(ngModel)]="birthDate" 
        name="birthDate" 
        id="birthDate">
     </ion-datetime>
  </ion-item>
  <button ion-button full [disabled]="!userProfileForm.form.valid">Begin</button>
</form>
```

**Comment by keithdmoore** [comment]
The issue I was experiencing is due to the displayFormat.  You have to have a year.  My workaround is to remove the form and do this:
```
<ion-datetime displayFormat="MMMM D" (ionChange)="dateChanged($event)"></ion-datetime>
```
and then in my page, I set the attribute myself:
```
dateChanged(data) {
  this.birthDate = moment(`${data.month.value}-${data.day.value}-2016`, "M-D-YYYY").format();
}
```

**Comment by brian-duffy** [comment]
Bug: ng-valid / ng-dirty not working on ion inputs other than ion-input

For anyone looking for a workaround for this:
<ion-item>
      <ion-label stacked>label</ion-label>
      <ion-input class="hotfix" ></ion-input>
      <ion-datetime formControlName="issueDateValidator" [min]="minimumIssueDate" displayFormat="DD/MM/YYYY" ></ion-datetime>
 </ion-item>
in css:

ion-input.hotfix{
        display: none;
}

This one was annoying me for a while and led me to this page, but happy to post the workaround (Y)
