### ISSUE TITLE
bug: ion-content onScrollComplete on android

### ISSUE THREAD

**Issue by danpincu** [driftyco/ionic#7272]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>It seems that the onScrollComplete expression isn't evaluated on android/chrome.
I reproduced it both in the browser on desktop & on the device.
I actaully noticed this problem after I found this codepen:
http://codepen.io/mhartington/pen/vpJCD

On safari on ios, and on iphone it works fine.</span>

<span is-issue-template></span>

**Comment by danpincu** [comment]
I'm afraid this didn't fix it.
I added the changes in the commit to _ionic.bundle.js_ at the same location, and the problem still exists.
However I also found something strange - it seems that the function in which the change was made- _doTouchEnd_, is not called at all on android.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#110
