### ISSUE TITLE
ActionSheet with too many data is not scrollable

### ISSUE THREAD

**Issue by tagazok** [driftyco/ionic#7273]
Hi,
I am using an ActionSheet to make allow the user to filter a list.
The problem is that the filter list can become pretty long and if the list does not fit in the screen, there is no way to scroll in the list of buttons.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by mikewagz** [comment]
This is definitely still an issue.  To recreate, add an action sheet with 12+ options.  They are off-screen and cannot be scrolled to.
