### ISSUE TITLE
Screen goes blank after deleting list item on Safari

### ISSUE THREAD

**Issue by ChrisGrigg** [driftyco/ionic#7275]
#### Short description of the problem:
When deleting an item from a list using virtualScroll the screen goes blank on Safari and occasionally Chrome. The app has to be reset.

#### What behavior are you expecting?
The list should be updated and the view remains without breaking.

**Steps to reproduce:**
1. Create a virtualScroll list.
3. Create a delete button.
4. Create a list, and press the delete button on 1 item

```
<ion-content class="diary-page" padding>
  <h4 padding-top>Title</h4>
  <ion-list [virtualScroll]="diaryEntries">
      <ion-item no-lines *virtualItem="let diaryEntry">
        <ion-thumbnail item-left>
          <ion-img class="max-height-80" [src]="diaryEntry.url"></ion-img>
        </ion-thumbnail>
        <h3>{{ diaryEntry.date | date:'dd/MM/yyyy' }}</h3>
        <ion-badge secondary>{{ diaryEntry.food }}</ion-badge>
        <ion-badge secondary>{{ diaryEntry.symptomType }}</ion-badge>
        <ion-badge favourite>{{ diaryEntry.symptomSeverity | outOfWhat:'10' }}</ion-badge>
        <button (click)="presentPopover($event, diaryEntry);">
          <ion-icon name="pricetag"></ion-icon>
        </button>
        <button danger (click)="showDeleteAlert(diaryEntry)">
          <ion-icon name="trash"></ion-icon>
        </button>
      </ion-item>
  </ion-list>
</ion-content>
```
 
**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
