### ISSUE TITLE
bug: View Source for $ionicSlideBoxDelegate link broken

### ISSUE THREAD

**Issue by timofeysie** [driftyco/ionic#7276]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The link for 'view source' on the ion-slides api page is broken.
http://ionicframework.com/docs/api/directive/ionSlides/
Leads to:
https://github.com/driftyco/ionic/tree/master/js/angular/directive/slides.js#L2
and returns a 404.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, since this is an issue with the ionic docs site and not the framework I will be moving this issue to that repo. Thanks for using ionic.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#696
