### ISSUE TITLE
two ion-scroll nesting

### ISSUE THREAD

**Issue by PasDajavu** [driftyco/ionic#7278]
if two ion-scroll nesting,A ion-scroll scroll to the top,How to let the other ion-scroll then scroll.My English is not good, please forgive me

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic! Also, your English is fine (:

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
