### ISSUE TITLE
perf: Ionic 2 Beta - Horrible performance on x86 CPUs

### ISSUE THREAD

**Issue by Lagor31** [driftyco/ionic#7283]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi, 
hopefully this could be of some use for you guys: 
I noticed that any app (even the simplest) that I build for my Zenfone 2 device runs with awful performances.
After trying it out on several devices I came to the conclusion that this issue might be caused by the Intel x86 CPU the Zenfone phones have on them.
I tried with other ARM devices and noticed that the performances were pretty good, it's just the Intel CPU that represents a problem for Ionic v2.
I understand Ionic 2 is still in beta and that most of the mobile devices mount an ARM CPU but I thought I'd let you know of this issue.

Keep up the good work,
Federico Gorla</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
I think there is nothing we can do to improve performance for a particular CPU architecture. We already try to write good JS that can be optimized easily by engines (like v8).

Engines like v8 implement Just In Time Compilation for targeted architectures, so you should try to debug if under your configuration something is preventing Chrome from generating machine code at runtime:
- A bad configuration
- A bug in chrome
- An outdated webview
- Some kind of W^X policy
- Your CPU is just so slow

I will close this issue, but feel free to reopen it if you provide new information demonstrating it is an ionic issue.

Thanks for your time!

**Comment by manucorporat** [comment]
@Lagor31 give a try: crosswalk x86

**Comment by Lagor31** [comment]
Hi, thanks for your reply.
I forgot to mention that I tried to deploy apps built with both ionic v2 and ionic v1 on my terminal (x86 ZenFone2) and the ones built using ionic v1 are as smooth as they can be, the problems arises only when using v2.

**Comment by Lagor31** [comment]
I have tried Crosswalk with no succes.
I don't know how things are on your end but since v1 works, I thought that maybe there could be a fix to improve performance that doesn't involve rewriting massive parts of code.
Again, I'm not an Ionic developer so I don't have the full picture but I thought I'd share the problems I'm facing.

**Comment by dmastag** [comment]
I am a Zenfone 2 User and an Ionic Developer using v1 and v2.
Never have had any performance problems using v2 like you mentioned.

Its hard to picture what you mean without more information.
Try to update your ionic cli to the latest beta, start a new sidemenu app and run it.
