### ISSUE TITLE
Default Fileencoding ANSI->UTF8

### ISSUE THREAD

**Issue by waybackrider** [driftyco/ionic#7284]
When creating an new Project or a new Page the default File encoding ist ANSI.
Why not using UTF8, especially in a Web-Environment?

Using:
Framework 2.0.0-beta.10
CLI: 2.0.0-beta.32
App-Lib: 2.0.0-beta.18
Windows 7 SP1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! By default node.js saves files in a utf8 format, in fact here is the exact line that writes files to disk https://github.com/driftyco/ionic/blob/master/tooling/generator.js#L38 . Are your files being saved in an ASCII format? Also how are you checking the encoding? Thanks for using Ionic!

**Comment by waybackrider** [comment]
Hi, i'm checking it with notepad++ as well as VS 2015.
When adding for Example German Character "ö" into a Template it's not shown in the Browser, then saving it explicitly as UTF8 it works, so orginal can't be UTF8 as the Tools say.

**Comment by jgw96** [comment]
@waybackrider could you check your index.html and make sure it specifies the utf8 charset please? Thanks!

**Comment by waybackrider** [comment]
Index.html is also ANSI encoded. As much as i can see every file created by "ionic start" is ANSI encoded.

**Comment by jgw96** [comment]
Hmm ok. I am going to move this issue to the ionic-cli repo as it seems to be more of a cli related issue. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1169
