### ISSUE TITLE
ionic2 tabs + loading

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#7285]
Hello,

I am not sure if it's an issue or a bad use.
I made an app with tabs.
For some security reason we have a custom cordova plugin to make http post request.

This plugins is callable as an angular service post.plugin.ts who are injectable.
And to call it, we use services between pages.ts and post.plugin.

As example, login page will call login.service.ts who will call post.plugin.ts

During a post, we want to show a loading so, before calling Observer.create() we call nav.present(loading) and in the Observer.complete() we call loading.dismiss(). 
So we have the something like:

```
let loading = this.createLoading();
let nav = this.app.getActiveNav();
this.nav.present(loading);
return Observer.create(observer => {
    window.pgPlugin.doPost(url, data, response => {
        // check response and return result 
        observer.next(response);
	observer.complete(loading.dismiss());
    });
});
```

When we are in page before tabs it works because nav is the rootNav component.
But when we move in a page loaded in tabs it fait and tell present() does not exist for nav.
"TypeError: nav.present is not a function"
So with the doc and the debuger with understood that tabs have their own nav.
Is-it normal that a nav of tabs doesn't can't call present()  ?

I also tried nav.rootNav.present(loading).
It look working sometimes and sometimes not. I don't understand when so I can't explain more.

Then I made some different tests.
I started a new project and insert the navController in tab page.
in this cas, 
- if we try to use NavController injected in page contrustor it work
 but we can't access navController in services, this is why we use app.getActiveNav();
- if we call app.getActiveNav() we get the same error  : 
```
import {Component} from '@angular/core';
import {NavController,Loading, App} from 'ionic-angular';

@Component({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
  constructor(private app: App, private navController: NavController) {
  
  }

  ngOnInit(){

		let loading = this.createLoading();
    let nav = this.app.getActiveNav();
		nav.present(loading); // failed
    //this.navController.present(loading); // Work but not available in services
  }

	private createLoading() {
		let wait: string = "wait";
        
		return Loading.create({
			content: "wait"
		});
	}
}

```

So finally and to resume,
How should I do to open an alert or a loading when I make transition in page with tabs (so before and after) in a service who can't access NavController ?

**Comment by jgw96** [comment]
Hello! This actually should already be solved by the overlay components refactor that will be in the upcoming beta.11 release. If you would like to give it a try now you can install the latest nightly with `npm install ionic-angular@nightly`. Also the docs for the new LoadingController service that handles creating and dismissing the loading component can be found [here](http://ionicframework.com/docs/v2/api/components/loading/LoadingController/). If this does not fix the issue feel free to comment and i will gladly reopen this issue, thanks for using Ionic!

**Comment by movrack** [comment]
All my app look to be broken since i move to nightly. A can't explain why. So I think a will wait the beta 11 release.

Thanks for the feedback.

**Comment by jgw96** [comment]
@movrack there were a few breaking changes which we will have an upgrade guide for when beta.11 is released. Thanks!
