### ISSUE TITLE
bug: [Bug] ngModel not working in ion-toggle, ion-searchbar with new Form API

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7286]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The `ion-searchbar` and `ion-toggle` outputs errors with `[(ngModel)]` since last update to `ionic-angular` beta.10 with the next code:

```html
<ion-searchbar debounce='200' [(ngModel)]="searchQuery" placeholder='Buscar'></ion-searchbar>
<ion-toggle [(ngModel)]="toggleValue"></ion-toggle>
```

```js
export class CustomersPage {
  public searchQuery: string = ''
  public toggleValue: boolean = true
  ...
}
```

Error output:
![image](https://cloud.githubusercontent.com/assets/9698639/16772011/26d892f8-4818-11e6-8caa-e77de34e99d1.png)

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by Luchillo** [comment]
Basic start plunkr?

**Comment by jgw96** [comment]
@Luchillo sure, here is the link to the one that is included in the issue template http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview. Thanks!

**Comment by Luchillo** [comment]
How am i supposed to import the `@angular/forms` package?, i'm editing the `config.js` systemjs file but i see it locks the angular version to RC.1, i increased to RC.4 but i'm stuck in adding the SystemJS mappings, this is what i have so far:

```js
(function(global) {

  var ngVer = '@2.0.0-rc.4'; // lock in the angular package version; do not let it float to current!

  //map tells the System loader where to look for things
  var  map = {
    'app':                        'src', // 'dist',
    'rxjs':                       'https://npmcdn.com/rxjs@5.0.0-beta.6',
    '@angular/forms':             'https://npmcdn.com/@angular/forms@0.2.0',
    'angular2-in-memory-web-api': 'https://npmcdn.com/angular2-in-memory-web-api' // get latest
  };

  //packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'app.ts',  defaultExtension: 'ts' },
    'rxjs':                       { defaultExtension: 'js' },
    '@angular/forms':             {},
    'angular2-in-memory-web-api': { defaultExtension: 'js' },
  };

  var packageNames = [
      '@angular/common',
      '@angular/compiler',
      '@angular/core',
      '@angular/http',
      '@angular/router',
      '@angular/platform-browser',
      '@angular/platform-browser-dynamic',
      '@angular/router-deprecated',
      '@angular/testing',
      '@angular/upgrade',
  ];

  // add map entries for angular packages in the form '@angular/common': 'https://npmcdn.com/@angular/common@0.0.0-3'
  packageNames.forEach(function(pkgName) {
    map[pkgName] = 'https://npmcdn.com/' + pkgName + ngVer;
  });

  // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
  packageNames.forEach(function(pkgName) {
    packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
  });
```

**Comment by Luchillo** [comment]
Sorry about the last comment, here's the plunkr you needed, i think it happens when i try to use the new Forms API and deprecate the old form API: http://plnkr.co/edit/N7teQ0?p=preview

**Comment by jgw96** [comment]
Ahh, so the issue is that we do not support the new refactored forms module yet, although this has already been fixed for the upcoming beta.11 release. Thanks for using Ionic! For now i would recommend using the deprecated forms api.

**Comment by Luchillo** [comment]
I didn't though it was that until now that i replicated the issue and it worked until i made the deprecation provider thing.
