### ISSUE TITLE
DevicesNotFoundError when trying to access camera through webrtc

### ISSUE THREAD

**Issue by ramsestom** [driftyco/ionic#7288]
Hi
I am trying to use simpleWebRTC inside a ionic app. 
On desktop browser (chrome), everything is fine. When I init a video call, a popup appear aking me for permission to use my webcam and the webrtc call succeed (after agreeing to access my webcam).
On Android however, when trying to init a call, webrtc throw a localMediaError of type NavigatorUserMediaError,DevicesNotFoundError
I am using a Crosswalk in my ionic app so webrtc is supposed to be supported by the WebView rendering my app (anyway, receving a webrtc call broadcasted from my pc to the android device running the ionic app works fine. So webrtc (and the simplewebrtc lib) seems to work correctly). 
So the problem is probably some kind of camera access security issue but I don't know how to correctly define permissions for this. 
Has someone any clue on how to fix this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
