### ISSUE TITLE
Router - starting in a nested state - now loading all parent routes correctly

### ISSUE THREAD

**Issue by stefek99** [driftyco/ionic#7289]
Initially posted on StackOverflow - http://stackoverflow.com/questions/38287084/angular-ionic-ui-router-how-to-ensure-all-the-parent-views-are-loaded-when-sta - then massively edited my question and futher isolated test case.

* Works just fine: http://michalstefanow.com/ionic.html#/app/parent
* ```ion-nav-buttons``` are not loaded: http://michalstefanow.com/ionic.html#/app/parent/next

You can clearly see that the nested view is loaded, it's just some stuff that is missing:

```
        <ion-nav-buttons side="secondary">
          <button class="button" ui-sref='app.parent.next'>next »</button>
        </ion-nav-buttons>
        
        <ion-content has-header="true">
          <h1>Parent</h1>
          <h1>Parent</h1>
          <h1>Parent</h1>
          
          <div ui-view="next"></div>

        </ion-content>
      </ion-view>
```

Is there a way to jump into ```app.parent.next``` state directly without stepping through ```app.parent``` and ensure all the buttons and headers are loaded correctly?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by stefek99** [comment]
OK, sure, thanks.

I think I've asked on Forum + Slack + SO + Gtihub all at once... *(but didn't have a chance to cross-reference it)*

As far as I remember I changed the navigation / routing - it's not ideal but at least I had something to show.
