### ISSUE TITLE
Closing a sub-modal with hardware back button closes the parent too

### ISSUE THREAD

**Issue by viki53** [driftyco/ionic#7291]
#### Short description of the problem:

I have two modals : one is opened by a regular view, the second is opened by a directive inside the first modal. When I use the Android back button, both modals are closed.
#### What behavior are you expecting?

I would like the event to be only caught by the last opened modal (i.e. the second one from the directive).

**Steps to reproduce:**
1. Create and open a modal
2. Create and open a second modal form inside the first one
3. Use hardware back button

I tried using several kind of event cancelation:

```
$event.preventDefault();
$event.defaultPrevented = true;
$event.stopPropagation();
$event.stopImmediatePropagation();
return false;
```

None of those prevent the event to be transmitted to the parent modal, so both end up closed no matter what.

**Ionic Version:** 1.7.14
#### Plunker that shows an example of your issue

[Not done yet](http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview) (our app is too big and complex to just copy-paste it)

**`ionic info`:**

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Distributor ID:     elementary OS Description:      elementary OS Loki
Node Version: v5.4.0
```

(I actually run Ubuntu 16.10, not Elementary OS, that some leftover from when I tried to install the Elementary theme on top of Ubuntu)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#109
