### ISSUE TITLE
Async tab titles are not rendered

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#7292]
#### Short description of the problem:
When using [ng2-translate](https://github.com/ocombe/ng2-translate) to fetch the translations for the tabs, the titles are not rendered.

#### What behavior are you expecting?
The titles should be rendered, even when fetched asynchronously.

**Which Ionic Version?**
2.0.0-beta.10

#### Plunker that shows an example of your issue

http://plnkr.co/edit/JD9jJNcP3UD6ydk4VhTZ?p=preview

The sync tab title is rendered but when delaying the tab title, it is not rendered.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not currently support `ng2-translate` but we will be working on adding translation and internationalization once that lands in Angular 2. Thanks for using Ionic!

**Comment by frederikschubert** [comment]
This is not about ng2-translate. That was just the context where i discovered this bug.
Sometimes it is necessary to have an async operation that fetches some string and that string should be set as a tab title. The tabs should handle this case in my opinion.
Please consider reopening this issue.
