### ISSUE TITLE
Wrong auto-generated class for Modals when the code is minified

### ISSUE THREAD

**Issue by Loutrinos** [driftyco/ionic#7295]
#### Short description of the problem:
When the js code is minified is losing the Class Name that is used to generate the class given to `ion-page`

#### What behavior are you expecting?
Have a unified way to target the `ion-page` generated from a Modal in any way (having js code minified or not).

**Steps to reproduce:**
1. Create a component that will be consumed as a Modal
2. Present the modal to the NavController
3. Minify your js code
4. Open the modal in the browser and inspect the autogenerated class given to the `<ion-page>` element.

The code that auto-generates the class for Ionic Modal is here:
https://github.com/driftyco/ionic/blob/master/src/components/modal/modal-component.ts#L48
This should be updated so the class can be generated from a string value assigned from the component rather than the name of the Component that is lost during minification.
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/x7f7RN?p=preview

if you click Open Modal button, a Modal using SamplePage Class will be rendered and the `ion-page` will be:
```<ion-page _ngcontent-nsh-11="" class="show-page sample-page">```
When the code is minified the same element will be:
```<ion-page _ngcontent-nsh-11="" class="show-page e">```

**Comment by jgw96** [comment]
Hello! With our new build that implements AOT compile and tree shaking minification will no longer be needed. Because of this I will be closing this issue for now. Thanks for using Ionic!
