### ISSUE TITLE
Ionic push plugins notifications working intermittently.

### ISSUE THREAD

**Issue by Natanael1234** [driftyco/ionic#7299]
The on notification event is working intermittently.
Some times it works, sometimes not. Sometimes it works at begins and after I stop to receive notifications.

I frequently need to restart the emulator to try to make it work.

Anyone is facing the same problem or knows the possible causes?

**Comment by mhartington** [comment]
@Natanael1234 is this related to the Ionic Push Notification service?

**Comment by Natanael1234** [comment]
Yes. I am using the push plugin.

**Comment by Natanael1234** [comment]
I'm using Android emultator to test.

**Comment by brandyscarney** [comment]
Could you give us some more information please? Can you run `ionic info` and `ionic plugin list` from a terminal within your project and paste the output here? Thanks!

**Comment by Natanael1234** [comment]
$ ionic info

Your system information:

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v6.2.2
```

Note: OS is missing but the its running under Windows 10.

Ionic plugin list don't return anything.

Here comes my plugin/fetch.json:

> {
>     "cordova-plugin-device": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-device@~1.1.2"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-console": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-console@~1.0.3"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-whitelist": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-whitelist@~1.2.2"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-splashscreen": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-splashscreen@~3.2.2"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "ionic-plugin-keyboard": {
>         "source": {
>             "type": "registry",
>             "id": "ionic-plugin-keyboard@~2.2.1"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-statusbar": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-statusbar@~2.1.3"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-network-information": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-network-information"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-sqlite-storage": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-sqlite-storage"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-file": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-file"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-compat": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-compat"
>         },
>         "is_top_level": false,
>         "variables": {}
>     },
>     "phonegap-plugin-push": {
>         "source": {
>             "type": "registry",
>             "id": "phonegap-plugin-push"
>         },
>         "is_top_level": true,
>         "variables": {
>             "SENDER_ID": "664483513"
>         }
>     },
>     "uk.co.workingedge.phonegap.plugin.launchnavigator": {
>         "source": {
>             "type": "registry",
>             "id": "uk.co.workingedge.phonegap.plugin.launchnavigator"
>         },
>         "is_top_level": true,
>         "variables": {}
>     },
>     "cordova-plugin-actionsheet": {
>         "source": {
>             "type": "registry",
>             "id": "cordova-plugin-actionsheet"
>         },
>         "is_top_level": false,
>         "variables": {}
>     }
> }

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#144

**Comment by jgw96** [comment]
Hello @Natanael1234 since this is an issue related to the ionic cloud I have moved this issue to the appropriate repo. Thanks!
