### ISSUE TITLE
Move ClientRect somewhere else

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#7300]
Right now `Range` exports `ClientRect`, but this feels wrong considering `ClientRect` is a generic UI class.

Ideally this is refactored to a generic UI/Rectangle/Size class

**Comment by manucorporat** [comment]
Same with `Coordinates` class

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
