### ISSUE TITLE
Ionic App hangs. After splash screen hides > White Screen

### ISSUE THREAD

**Issue by shyamal890** [driftyco/ionic#7303]
Ionic App hangs as soon as splash screen is hidden. Nothing happens after that, white screen is displayed. This happens sporadically, have only encountered this in release build, hence no way of knowing why this is happening.

**Which Ionic Version?** 1.x

**Comment by danbucholtz** [comment]
Hi @shyamal890,

There isn't any info above that we can work off of.  We need more details.

This sounds likely to be an issue with your configuration or code, not the framework.  We have forums available for help/questions [here](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).  If you make a post, someone may be able to help you troubleshoot.

If we find out this is an issue with the framework, I'll reopen the issue.

Thanks, and have a good day.
Dan
