### ISSUE TITLE
Issue: Cordova CLI: Not installed

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7306]
I installed `Cordova` using the below command:
``sudo npm install -g cordova``

**Results:**
/Users/Daniel/.npm-packages/bin/cordova -> /Users/Daniel/.npm-packages/lib/node_modules/cordova/bin/cordova
/Users/Daniel/.npm-packages/lib
└── cordova@6.2.0 

However when I run:

> ionic info

**I Get:**

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

I runned the following too:

```
sudo npm -g list | grep cordova

├─┬ cordova@6.2.0
│ ├─┬ cordova-common@1.3.0
│ │ ├── cordova-registry-mapper@1.1.15
│ ├─┬ cordova-lib@6.2.0
│ │ ├── cordova-app-hello-world@3.10.0
│ │ ├─┬ cordova-fetch@1.0.0
│ │ ├─┬ cordova-js@4.1.4
│ │ ├─┬ cordova-serve@1.0.0
│ │ ├─┬ cordova-lib@6.1.0
│ │ │ ├── cordova-app-hello-world@3.10.0
│ │ │ ├─┬ cordova-common@1.1.1
│ │ │ ├─┬ cordova-js@4.1.4
npm ERR! extraneous: ionic-app-lib@0.7.3 /Users/Daniel/.npm-packages/lib/node_modules/ionic-app-lib/node_modules/ionic-app-lib
npm ERR! extraneous: jasmine-node@1.14.5 /Users/Daniel/.npm-packages/lib/node_modules/ionic-app-lib/node_modules/jasmine-node
│ │ │ ├── cordova-registry-mapper@1.1.15
│ │ │ ├─┬ cordova-serve@1.0.0
npm ERR! extraneous: rewire@2.5.1 /Users/Daniel/.npm-packages/lib/node_modules/ionic-app-lib/node_modules/rewire
│ ├─┬ ionic-cordova-lib@5.1.10
│ │ ├── cordova-app-hello-world@3.9.0
│ │ ├─┬ cordova-js@4.0.0
│ │ ├── cordova-registry-mapper@1.1.15
│ │ ├─┬ cordova-serve@0.1.3
```

Cordova is already installed, but it does not add itself to IONIC somehow, do I need to add something in `package.json` or what should I do?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this seems to be an issue with the ionic cli and not the ionic framework i will be moving this to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1175
