### ISSUE TITLE
Item reordering returns an index of -100 if the item doesn't change order

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic#7307]
#### Short description of the problem:
 
If an item is minimally moved during a reorder such that it maintains its original ordering,  indexes.to is set equal to -100 instead of the original index.

#### What behavior are you expecting?
indexes.to should be equal to the original index.

#### Plunker that shows an example of your issue
http://plnkr.co/edit/0UPVjYTvmL4kQOSt2xSI?p=preview

**Which Ionic Version?**  2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by manucorporat** [comment]
@djangojack I can confirm this was already fixed here:
https://github.com/driftyco/ionic/commit/d993a1bfd86f6987e44f0a78fa5b4a46026de779#diff-4ad8cd6371a10686d79bd259ccef2897R60
