### ISSUE TITLE
bug: sidemenu working with alert, loading and popover

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7309]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Hii,
current scenario - 
sidemenu is working when alert , loading and popover is open 

expected result - 
when alert is shown swiping sidemenu should be disabled 
same goes for loading 
and in case of popover - when swipe for sidemenu, popover should close 

facing it on ionic beta10
also if anyone have ionic10 plunkr ?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This has already been fixed in the framework and will be part of the upcoming beta.11 release. Thanks for using Ionic!

**Comment by sagarkm** [comment]
Any tentative release dates for beta.11?
