### ISSUE TITLE
Alert dialog can not be closed or opened multiple times

### ISSUE THREAD

**Issue by sasos90** [driftyco/ionic#7310]
#### Can not properly close the alert dialog
When I open the Alert (with Alert.create...) pretty often happens, that application freezes and you need to restart the app because nothing is working after that. Sometimes even happen, that alert closes but I can not open it again.
I see that there are big problems regarding Alert popus. Is there any workaround for that?

#### What behavior are you expecting?
To close the alert and to be able to open it again with no problems.

**Steps to reproduce:**
1. Open the alert
2. Try to close it

**Which Ionic Version?** 1.x or 2.x
2.0 beta

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by sasos90** [comment]
Actually I used the basic example from Ionic 2 documentation, so my plunker is there.

Thanks!

**Comment by jgw96** [comment]
Hello! Unfortunately i cannot reproduce this issue with a basic alert on any of my devices, or in chrome. If you could provide a minimal example of this issue so that i can reproduce it that would be great. Thanks!

**Comment by sasos90** [comment]
Hm.. I was not enough accurate anyway I realized. The thing is that I am calling the prompt first, after entering some data to form, I am executing a REST call, and on REST call completed, I want to open a normal alert with a message. In a way it looks like this:
http://laravel.io/bin/Gy2nk#29

If I put the alert into a timer (250ms), then it works as it should.
Is that a valid solution?

Thank you!

**Comment by sasos90** [comment]
Ok finally created the plunker that crashed.
Nested alerts for example produce the error always.
https://plnkr.co/edit/1mSPcQ8vI5dk2v36sBbY?p=preview

**Comment by jgw96** [comment]
Hello! I have created this [plunker](https://plnkr.co/edit/ipR5NhauzrlTB7Vm99Ft?p=preview) that shows the correct way to use promises to open multiple alerts. Simply open the modal page and then click the `openAlerts` button. The code is in `page1.ts`. Thanks for using Ionic!

**Comment by sasos90** [comment]
I see. The thing is I have deeply nested calls there in my success callback and also I am using some service to easier show  the alert messages, so is there another way to open the alert outside of dismiss callback?

Thanks

**Comment by jgw96** [comment]
@sasos90 I would recommend asking around on the forums. There is some awesome devs on their that would love to help you! Thanks!
