### ISSUE TITLE
white line by refresher

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic#7311]
#### Short description of the problem:

ion-refresher adds a white space under toolbar. 

#### What behavior are you expecting?

No white space.

**Steps to reproduce:**
1. add the HTML below 

```
<ion-content>
    <ion-refresher (ionRefresh)="doRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
</ion-content>
```

**Which Ionic Version?** 1.x or 2.x
2 beta 10

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Im sorry, but im not fully understanding the issue here. Would you be able to post a screenshot or gif that shows this issue? Thanks for using Ionic!

**Comment by mbakker96** [comment]
I fixed it with this style:

```scss
.has-refresher scroll-content {
  border-top: 0px;
}
```

problem was that there was a border on the top of the scroll-content that did make a cap between the toolbar and content.

**Comment by jgw96** [comment]
Awesome glad it was fixed. Would you be able to post a screenshot or gif of the white line? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
