### ISSUE TITLE
LocalStorage value types

### ISSUE THREAD

**Issue by hdsnet** [driftyco/ionic#7313]
#### Short description of the problem:
`LocalStorage` lets you set a Boolean value to a given key (even though the only supported type is a string according to the documentation) and when you retrieve such a value it is converted into string. I guess this is intended but if that's the case at least it should be documented because it's very, very confusing. I am ashamed to admit it but it took me an hour to debug this behaviour after quickly prototyping a few hundred lines of code.
```javascript
let local: Storage = new Storage(LocalStorage);
local.set('someKey', true);
local.get('someKey').then((value) => {
    if (value == "true") {
        // Do something if it's true
    }
})
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#702

**Comment by brandyscarney** [comment]
Thanks for the issue! I've moved it over to the `ionic-site` repo since it is more of a documentation issue. :)

**Comment by brandyscarney** [comment]
Actually I'm going to reopen this. After looking more into it I think it's confusing that the docs state it is a `string` but it can be passed as `any` and Intellisense doesn't catch it.

**Comment by hdsnet** [comment]
Thank you @brandyscarney for looking into this. Cheers

**Comment by jgw96** [comment]
So after looking at this some more i have come to the following conclusion:

1. I do not understand why `localStorage` lets you set a boolean when the w3 spec says it only takes a string. This seems to be a browser implementation oddity.
2. Ionic is actually working correctly according to the spec. `localStorage` is only supposed to take a string, and our `set` method has the `value` parameter typed as a string. Also the get method returns a `Promise<string>` which is also correct, as even though `localStorage` lets you save a boolean, it will always return the boolean as a string.

I am wondering if we should do a manual check for a boolean in the set method of the `LocalStorage` class so as to "abstract" away this browser implementation oddity, but i am not sure of that yet. 
@brandyscarney any thoughts on this?

**Comment by jgw96** [comment]
Closing this issue as typescript warns you about setting a boolean in localStorage anyways.
