### ISSUE TITLE
Events.publish passes arguments as  an array to subscriber

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic#7314]
#### Short description of the problem:

Events.publish passes all arguments as first argument of subscriber : 
https://github.com/driftyco/ionic/blob/master/src/util/events.ts#L99
#### What behavior are you expecting?

Arguments should be passed as arguments into subscriber

```
import { Events } from 'ionic-angular'

const events  = new Events()

events.subscribe('test', function(error) {
   // actual (all arguments passed as first argument of subscriber)
  console.log(error); // [Error(), 1]

  // expected  (all arguments passed as arguments of subscriber)
  console.log(error); // Error()
})

events.publish('test', new Error('test'), 1) 
```

**Other information:**
Basically https://github.com/driftyco/ionic/blob/master/src/util/events.ts#L99 line should be changed to:

``` js
responses.push(handler(...args));
```

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by manucorporat** [comment]
@stalniy sorry! I don't understand completely your issue. Can you explain it again? thanks!
What's the difference from an API point of view?

Can you provide an example with multiple arguments?
Also, this change is probably not backcompatible, not sure if we can change it in RC

**Comment by stalniy** [comment]
@manucorporat this can be done through configuration option + api deprecation.

Currently when you do `events.publish('topic', 1, 2, 3, 4, 5)` in subscription function you will receive all passed arguments into `publish` as single array argument in `subscribe`: http://plnkr.co/edit/iGxvY1?p=preview 

So, **current behavior**:
```js
const events = new Events() 

events.subscribe('topic', (userId, attrs) => console.log(userId, attrs))
events.publish('topic', 1, { name: 'test' })
```
In subscription `console.log` outputs: `[1, { name: 'test' }] undefined` (single array argument)

The **expected behavior**:
In subscription `console.log` outputs: `1 { name: 'test' }` (multiple arguments)

**Comment by stalniy** [comment]
Hope my description is clear and we can find a way to merge because really inconvenient to write args[0] in subscription function
