### ISSUE TITLE
Update Sample Code Mistake

### ISSUE THREAD

**Issue by fakharkhan** [driftyco/ionic#7316]
Hi on this page [platform](http://ionicframework.com/docs/v2/2.0.0-beta.0/api/platform/Platform/) please fix the missing small bracket:
`
if(this.platform.is('ios'){
       // what ever you need to do for
       // if the platfomr is ios
     }
`
to 
`
if(this.platform.is('ios') ) {
       // what ever you need to do for
       // if the platfomr is ios
     }`
please note ) after `this.platform.is('ios')`
<img width="576" alt="screen shot 2016-07-14 at 4 56 58 pm" src="https://cloud.githubusercontent.com/assets/1877752/16838698/0459e6a0-49e4-11e6-93f5-3f7c3f0d6071.png">

**Comment by mhartington** [comment]
This has already been fixed in new releases. The link you pointed to was beta.0, while the latest bits are for beta10.

http://ionicframework.com/docs/v2/2.0.0-beta.10/api/platform/Platform/
