### ISSUE TITLE
Positioning order: <ion-tabs tabsPlacement="top"> below <ion-header>

### ISSUE THREAD

**Issue by peili** [driftyco/ionic#7317]
Currently `<ion-tabs tabsPlacement="top">` is placed below `<ion-header>`

Is there any way to have ion-tabs always be on first position and then ion-header stuff?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As of this time we do not plan on supporting this. According to the [md spec](https://material.google.com/components/tabs.html#tabs-specs) and general ux guidelines tabs should never be above the header and navbar. If you need toolbars under the content you can always just put toolbars in `ion-content`. Thanks for using Ionic!

**Comment by kodeine** [comment]
ion-segments are above the tabs if tabsPlacement is on top. Is that how its suppose to be?
