### ISSUE TITLE
Datetime display errors in iOS 8.x

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#7319]
#### Short description of the problem:
Datetime columns are displayed incorrectly running iOS 8x

![simulator screen shot jul 14 2016 11 55 54 am](https://cloud.githubusercontent.com/assets/2835826/16846576/f4a032ba-49ba-11e6-9ff1-a5c6c8d12c6f.png)

**Steps to reproduce:**
1. `ionic start tmp blank --v2 && cd tmp`
2. add the following markup to home.html
```html
  <ion-list>
    <ion-item>
      <ion-label>Date</ion-label>
      <ion-datetime displayFormat="MM/DD/YYYY" [(ngModel)]="myDate"></ion-datetime>
    </ion-item>
  </ion-list>
```
3. Build and deploy to iOS8 device or simulator

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
https://forum.ionicframework.com/t/ionic-2-datetime-component-issue-on-ion-8-3-1/56814/4 

**Which Ionic Version?** 1.x or 2.x
2.x, nightly

#### Plunker that shows an example of your issue

Device only issue. Use commands provided above.

**Comment by mhartington** [comment]
Looking into it, seems that inline styles are not getting applied.

```
<button category="picker-opt" type="button" class="disable-hover picker-opt picker-opt-default picker-opt-selected" ng-reflect-category="picker-opt" style="transform: rotateX(0deg) translate3d(0px, 0px, 90px);"><span class="button-inner">
```

Possibly due to [this line](https://github.com/driftyco/ionic/blob/master/src/components/picker/picker-component.ts#L303)

**Comment by manuelkuffo** [comment]
I am having the same issue. Please, let me know if there is any work around for now.

**Comment by chris-hammons** [comment]
Is there a possible work around for this? Our app has the same issue and we need to support ios 8.x and above.

**Comment by lennykean** [comment]
It looks like ios8 needs the -webkit- css properties for transform and transform duration. I created a pull request where I added these
