### ISSUE TITLE
Links to Github bronken

### ISSUE THREAD

**Issue by chroda** [driftyco/ionic#7320]
First of all, sorry if is a duplicate issue.

I dont know if you guys have another documentation for Ionic1 but I'm still consullting in http://ionicframework.com/

And the link to see the source are broken, can you tell if have another documentation with all working?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue with the ionic docs and not the ionic framework I will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#704

**Comment by chroda** [comment]
Thank you!
