### ISSUE TITLE
ios-transition navigation pop leaves page offscreen (beta.10-nightly)

### ISSUE THREAD

**Issue by EvanWillms** [driftyco/ionic#7321]
#### Short description of the problem:

When using nightly beta.10-201607132035, after navigating to a sub-page with the `ios-transition` animation defined then using the standard navbar back button to pop and return to the root page leaves the root page hanging offscreen with `transform: translateX(-33%);` still applied to the `<ion-content>` tag after the transition animation has finished.

#### What behavior are you expecting?

That the returned root page would be fully on-screen.

**Steps to reproduce:**

http://plnkr.co/edit/WEi330seoGIP6HzIYO8E?p=preview
1.  Click 'Thanks' button.
2.  Click top-left space where the back arrow should be (no ionicons in the plunker..)
3.  See the root page content hanging offscreen to the left. 

**Which Ionic Version?** 1.x or 2.x

ionic-angular@2.0.0-beta.10-201607132035

Also apparent on current HEAD (a5a3cc9)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is in fact the same issue as https://github.com/driftyco/ionic/issues/7171. I will be closing this issue as a duplicate, but feel free to chime in on the other issue. Thanks for using Ionic!
