### ISSUE TITLE
bug: aapt finished with non-zero exit value 2

### ISSUE THREAD

**Issue by andreluiz93** [driftyco/ionic#7325]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>When I build the android with command.

What I do wrong?

The log: 

root@Andre-notebook:/home/andre/Pessoal/Devlopment/todo# ionic build android
Running command: /home/andre/Pessoal/Devlopment/todo/hooks/after_prepare/010_add_platform_class.js /home/andre/Pessoal/Devlopment/todo
add to body class: platform-android
ANDROID_HOME=/root/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/root/Android/Sdk/build-tools/24.0.0/aapt'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.659 secs
Error: Error code 1 for command: /home/andre/Pessoal/Devlopment/todo/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/andre/Pessoal/Devlopment/todo/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1179

**Comment by jgw96** [comment]
Hello, as this was an issue with the ionic-cli i have moved this issue to that repo. Thanks for using Ionic!
