### ISSUE TITLE
Something wrong with ionic2 enviroment base on win7

### ISSUE THREAD

**Issue by meiyalei** [driftyco/ionic#7326]
I have something wrong when i am used to  ionic2 module.
The enviroment as shown:
__________________________
1. windows 7
2. nodejs  6.3.0
3. npm 3.10.5
4. cordova 6.2.0
5. ionic 2.0.0-beta.32
_________________________

And now, i use cli comment [ionic start demos --v2] to create a new project, like this,
_______________________________________________________________________________________
E:\idea>ionic start demos --v2
Creating Ionic app in folder E:\idea\demos based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
_______________________________________________________________________________________ 

But the process is sticking [Installing npm packages...] for long time,
then error messages are shown:
_____________________________________________________________
Error with start undefined
Error Initializing app: There was an error with the spawned command
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
_____________________________________________________________

In view of the above problems, i have no idea.
So, Can you help me. 
Thanks a lot.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1181

**Comment by jgw96** [comment]
Hello, as this issue has more to do with the ionic-cli than the framework i have moved this issue to that repo. Thanks for using Ionic!

**Comment by meiyalei** [comment]
sorry, i don't know what i should do to solve this issue.
