### ISSUE TITLE
Android 5.0 font sizing and shifted alignment

### ISSUE THREAD

**Issue by nitin27may** [driftyco/ionic#7327]
Hi

I'm using a Samsung Galaxy Note3 and  Android 5.0. S I tested this in the ionic sidemenu starter project and everything is fine on desktop Chrome but after building and installing on Note 3 several items are not aligning correctly. 
It is same issue as https://github.com/driftyco/ionic/issues/3107 

Scrrenshots: 

https://drive.google.com/file/d/0BztwPeNCGozVUHNlS1I4OVU4YW8/view?usp=sharing

https://drive.google.com/file/d/0BztwPeNCGozVTy1pakhMMzQyMFk/view?usp=sharing

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Do you have a minimal example i could use to reproduce this issue? I test regularly with a Moto x 2014 running stock Android 5.1.1  and have never seen this issue before. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue and i can't seem to reproduce it on my device running Android 5 I will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by ernanielyjr** [comment]
I noticed this happens when you change the font size in the Android display settings.
