### ISSUE TITLE
login to tabs page, "event" not detected ?

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#7328]
Hello

I have an issue, but I can not determine where is the problem so i know that i am a bit vagueness.

I have a login form. When it success, we push a tabs page.
But to shown the page it look that we have to fire something... like doing a double click on submit button for ios or press bask on android. To implement tabs we reuse tabs example in the sample demo app on a new start project.

If we remove the tabs (and pushing directly the first page of tabs, without tabs), it look working well.

There is some special feature/configuration to do ?

**Edit:**
To complete:
The push is done inside a response of a subscribe. (when we get success results from server)
But perhaps we have to put it somewhere else.

**Edit2:**
I have added an alert who handle the push when we click on 'ok'. In this case. It's working.

So How can i do the nav.push when a  suscribe has finish his response work but not execute it when we get an error ?
Now I think is more our dec code who fail. And not really the framework.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
