### ISSUE TITLE
bug: error in android s not installed build tool 19.1.0

### ISSUE THREAD

**Issue by rakeshtiwari** [driftyco/ionic#7329]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>After Gradle sync get "Error:No installed build tools found. Please install the Android build tools version 19.1.0 or higher". But i have installed latest version of android sdk with build tool  from 19.1.0 to 24.

My system information is as below:

Cordova CLI: 6.2.0
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v4.2.2</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1180

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this issue is more related to the ionic cli i have moved this issue to that repo. Thanks for using Ionic!
