### ISSUE TITLE
V2 Beta11 ion-content background-color

### ISSUE THREAD

**Issue by zywh** [driftyco/ionic#7331]
I just upgraded to nightly(Beta11) and discovered some page show "black" background. It only happen in IOS

Have to add this into CSS.
```

ion-page.show-page scroll-content {
   background-color: white;
}

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I am having trouble reproducing this issue with the latest nightly. Could you share a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by zywh** [comment]
It seems related to scss for this page. If I removed all CSS, the page is regular white background

SCSS
```

.projects {

  ion-card {
    position: relative;
    text-align: center;
    
  }
  
  ion-card img {
      height: 169px;
  }

  .card-title {
   position: absolute;
    top: 40%;
    font-size: 20px;
    width: 100%;
    font-weight: bold;
    color: #fff;
  }
  
  .card-subtitle {
   font-size: 20px;
    position: absolute;
    bottom: 0%;
    width: 100%;
    color: #fff;
  }

}


```


HTML  - Note: I remove all content to simplify trouleshooting.With above SCSS, the page is black
```
<!--
  Generated template for the ProjectsPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
-->
<ion-header>
<ion-navbar >
  <!--<button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>-->
  <ion-title>Project</ion-title>
</ion-navbar>
</ion-header>

<ion-content padding class="projects">

</ion-content>
```

**Comment by zywh** [comment]
More specific. If I removed this, the page is normal

```

  // .card-title {
  //  position: absolute;
  //   top: 40%;
  //   font-size: 20px;
  //   width: 100%;
  //   font-weight: bold;
  //   color: #fff;
  // }
```

**Comment by zywh** [comment]
It took me really a while to find the trigger. I played around CSS/HTML. Remove all and leave basic HTML page. It has black background. The trigger is "preload=true".

In beta10, there is bug. With preload=true, tab doesn't switch. It appears nightly(beta 11) fix the issue. But there appears this issue



```

<!--<ion-tabs #mcTabs [selectedIndex]="mySelectedIndex" [preloadTabs]="preload">-->
<ion-tabs #mcTabs [selectedIndex]="mySelectedIndex" >
```
