### ISSUE TITLE
Not able to reorder list with ion-checkbox in the list item

### ISSUE THREAD

**Issue by jntr06** [driftyco/ionic#7339]
If I put an ion-checkbox in the list item, I can't reorder it.

**Comment by manucorporat** [comment]
@jntr06 can you provide a minimum plunker example? You can use this as a base:
http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

also, make sure to follow the issue template. please include the output of `ionic info`

Thanks!

**Comment by jntr06** [comment]
Hi manucorporat,
Please refer to the plunker link below.
I have added sample code for the issue. Not sure why reorder is not working in plunker.
Issue is even if the reorder is working fine in my system but it is not working any more as soon as I am including a check box in the list.
Can you please help

home.html
` <ion-list reorder = "true">
   <ion-item *ngFor ="let item of items" >
   <ion-checkbox></ion-checkbox>
   <ion-label>{{item}}</ion-label>
   </ion-item>
 </ion-list> `

home.ts
`export class HomePage {
  
  greeting: string;
  
  constructor(private nav: NavController) {
    	this.initialize();
		
	}
		initialize(){
	  
	  this.items = ['USA','France','Italy','Australia','England']
	}

	goToPage1() {
	  this.nav.push(Page1);
	}
}`


[http://plnkr.co/edit/iluWZWmibT6FSNi8K72B?p=preview](url)

**Comment by jntr06** [comment]
http://plnkr.co/edit/iluWZWmibT6FSNi8K72B?p=preview

**Comment by manucorporat** [comment]
@jntr06 thanks a lot for the plunker, it helps a lot. I will look into it tomorrow!

**Comment by manucorporat** [comment]
@jntr06 fixed! it should work in next release! thanks for the report!

**Comment by jntr06** [comment]
Thank you :)
