### ISSUE TITLE
bug@v2: Dismissing loading too fast triggers error "Cannot read property 'nativeElement' of undefined"

### ISSUE THREAD

**Issue by HugoHeneault** [driftyco/ionic#7342]
#### Short description of the problem:
If we dismiss a Loading too fast after presenting it, an error is thrown.

#### What behavior are you expecting?
It should be dismissed without any issue.

**Steps to reproduce:**
1. Validate the Prompt
2. The `Loading...` should disappear

**Which Ionic Version?** 2.0.0-beta10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/cgY4qMpyGGaiVNbtFu2N?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v6.2.2

******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by jgw96** [comment]
Hello, thanks for opening this issue! I can reproduce this issue and will be taking a look into it. Thanks!

**Comment by Kobzol** [comment]
Shouldn't you wait for the loading to be displayed before dismissing it?
If you use this, it works:
```typescript
this.nav.present(loading).then(() => {
    this.asynchronous().then(() => {
        loading.dismiss();
    });
});
```

**Comment by jgw96** [comment]
Ahh, thanks for looking at this again @Kobzol, don't know why i didn't notice that yesterday. @HugoHeneault I have made a plunker [here](http://plnkr.co/edit/5uGjfN0WkQEqCGlX3CJA?p=preview) that shows the correct way to do this. Thanks for using Ionic!
