### ISSUE TITLE
generated class name in <page>.scss does does not coincide with generated class name in the markup

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic#7343]
I just installed Ionic v2:
```bash
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

And I was generating a page with `ionic g page <page name>`. Everything went ok, besides the class name generated in `<page name>.scss`.

The class name in `<page name>.scss` is `.<page name> {}`, but the class name on the page container (`<ion-page>`) in the markup is `<page name>-page`.

I can see that the class name generated on `<ion-page>` is based on the component class name, which is generated as `<page name>Page` (e.g. `StoogesPage`).

This might be an issue with the CLI probably.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1190

**Comment by rolandjitsu** [comment]
@jgw96 thanks 👍

**Comment by jgw96** [comment]
No problem!
