### ISSUE TITLE
Ionic2 - Show/Hide button based how the controller was shown

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7344]
I have a page **Page 2** which needs to be open sometimes using a modal() and sometimes using a push().
In the normal scenario, if the controller is opened using a push method it will show a "Back" button. However, in the other scenario which is opening the page using a modal() method, I need to add a close button to **Page 2** so the user can dismiss that controller at any time.

**The Problem**

If I add a close button to **Page 2** then that button shows even if the controller was opened using a push() method and in this case it shows a back button and a close button.

**What I want**

I want to add a condition, in which if the controller was opened using push(), then it should hide that **close button**

**The flow:**

Page 1 > (Push to) > Page 2 (Hide the close button)
Page 3 > (Modal to) > Page 2 (Show the close button)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
