### ISSUE TITLE
Mysterious Disappearing Issue in iOS 9/10

### ISSUE THREAD

**Issue by ccj242** [driftyco/ionic#7348]
Hi Everyone! I'd really appreciate some ideas on this issue - I've never encountered anything quite like it.... a link to a video is below. I have two inputs on a login page and it seems that sometimes, when I initially select the other, everything disappears. This only occurs in iOS, not while serving in browsers or on android. I've also attached the html file. Thank you in advance, this really has be stumped!

[login.html.zip](https://github.com/driftyco/ionic/files/368655/login.html.zip)

https://dl.dropboxusercontent.com/u/4419450/iOS_Issue.mp4

**Comment by Manduro** [comment]
This is Ionic v1, right? I've seen this happen too. Possibly the same problem: https://github.com/driftyco/ionic/issues/6429. Are you using native scrolling on iOS? Switching to js scrolling might fix it.

**Comment by jgw96** [comment]
Hello @ccj242 , also if you could provide a plunker/codepen that demonstrates the issue that would be great!

**Comment by ccj242** [comment]
Wow, thank you guys so much! Per your advice I just added an "overflow-scroll='false'" to ion-content and it seems to have fixed it! I'm incredibly grateful to both of you and to this community for being so incredibly helpful. Thanks!
