### ISSUE TITLE
ion-datetime control does not fire form's (change) event

### ISSUE THREAD

**Issue by vk2sky** [driftyco/ionic#7350]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/
#### Short description of the problem:

Changing the value of an **ion-datetime** component on a form, and setting focus to another component, does not fire the form's **(change)** event. Reproducible on Chrome 51.0.2704.106 (64-bit) and Firefox 47.0.1

#### What behavior are you expecting?
Changing the date in an **ion-datetime** and putting focus on another field would fire the **(change)** event, as happens with an **ion-input**

**Steps to reproduce:**
1. use Plunker link below. I have added a form with an **ion-input** component and an **ion-datetime** to **home.html**, and a form **(change)** event handler to **home.ts**, which displays an alert message.
2. Change the value of the **ion-input** component then put focus on the **ion-datetime** component. Note that the **(change)** fires, displaying an alert box (expected behaviour).
3. Change the value of the **ion-datetime** component, then put focus back on the **ion-input** component. Note that **(change)** event has not fired, i.e. no alert box gets displayed.

**Which Ionic Version?** 
2.0.0-beta.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/1lYKXo1FQaqDlecZHqzv?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We actually do not fully support forms yet, but we plan on fixing this soon, hopefully with the beta.11 release if everything works out. Here are the two tracking issues for forms if you would like to keep up with the progress. https://github.com/driftyco/ionic/issues/6040 https://github.com/driftyco/ionic/issues/6228 Thanks for using Ionic!
