### ISSUE TITLE
Toolbar cannot be exposed by component to the header

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#7352]
Just want to ask according to this change:
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-beta-10

I have a component that might use the toolbar, but the toolbar can now only be added as follows:
```html
<ion-header>
  <ion-navbar>
    <ion-title>
      Navbar Title
    </ion-title>
  </ion-navbar>

  <ion-toolbar>
    <ion-title>
      Toolbar Title
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>

</ion-content>
```
so this way if I have a component within ion-content how would I be able to add a toolbar from the component? I guess by design, it is not allowed. The question is also applied to the footer.

**Comment by brandyscarney** [comment]
I don't understand what you're trying to achieve. Toolbars can be placed inside of `ion-header`, `ion-content` or `ion-footer` elements. Are you trying to add a toolbar to the content? Maybe you can add some markup for what you're trying to achieve? Thanks!

**Comment by barocsi** [comment]
Hello, thanks,
never mind I managed to solve it with a different pattern. The goal was to create an edit page for a certain item CRUD operations, and I was keen on adding save buttons and certain tabs for the edit component to its header and footer. Then I realized I would just create a page as component for it.
