### ISSUE TITLE
Navigation freezes app on android emulator in beta.10

### ISSUE THREAD

**Issue by ho1den** [driftyco/ionic#7354]
#### Short description of the problem:

Since I've upgraded my Ionic 2 app from beta 9 to beta 10, navigation on an Android emulator (Genymotion) no longer appears to work, instead resulting in the app freezing. When I move my commit back to before upgrading, navigation works fine again.

#### What behavior are you expecting?

`this.nav.push(PageName);` should navigate to PageName as expected.

**Steps to reproduce:**
1. Open Genymotion
2. Run `ionic run android`
3. Wait for app to load in Genymotion window
4. When I click on any buttons that use the push code like the one below, the app becomes unresponsive

```
this.nav.push(PageName);
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
When I revert back to beta.9, the problem doesn't occur. The only change in the commit is the upgrade to beta.10 using the guide at https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta10-2016-06-27

**Which Ionic Version?** 1.x or 2.x
 2.0.0-beta.10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v4.4.3
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by vadag** [comment]
Hello! I have the same issue on genymotion (both 4.4.4 and 5.1.0) as well as on 4.4.2 phone. Not sure about about beta9, but earlier versions worked better. Just checked on most fresh github version of ionic-conference-app (typescript). I went to "About" page, after clicked "settingts" button on the top right, Popover showed but after that everything freezed. I mean totally everything in this application.

**Comment by vadag** [comment]
Just checked - it's Popover problem: EXCEPTION: Error in ./PopoverCmp class PopoverCmp - inline template:0:14
But anyway navigation is incredibly slow. In my little test app it freezes in random moments. But I found, that on phone sometimes double-tap helpes

**Comment by vadag** [comment]
Some updates on the issue. Just did 'ionic build browser' on the conference app, uploaded files to the clean server and opened it  from Genymotion (6.0.0 this time).  It completeley freezed in means of navigation when I was randomly clicking on the Speakers tab (actually two or three clicks) before in freezed, But I can scroll the list. No reasonable errors in console.
