### ISSUE TITLE
Navbar invisible when shown after entering page

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic#7355]
#### Short description of the problem:
I have a page that has two components that are exclusively displayed using ngIf. 
So something like:
```
<comp-1 *ngIf="!isEditMode"></comp-1>
<comp-2 *ngIf="isEditMode"></comp-2>
```
comp-2 has a navbar like:
```
<ion-header>
  <ion-navbar>
    <ion-buttons left>
      <button primary (click)="close()">
        Cancel
      </button>
    </ion-buttons>
    <ion-buttons end>
      <button primary (click)="save(mutableContact)">
        Save
      </button>
    </ion-buttons>
    <ion-title>{{name}}</ion-title>
  </ion-navbar>
</ion-header>
```
Initial value of isEditMode is false so when entering the page comp-2 is hidden. The user then performs an action and isEditMode becomes true, comp-1 is hidden and comp-2 is displayed.
Problem is navbar is invisible. Inspecting the DOM "show-navbar" class has not been added to <ion-navbar> component as show-back-button class has not been added to the respective component. If I add show-navbar class by hand, the navbar becomes visible, but the space is overlaying ion-content instead of pushing it down.

#### What behavior are you expecting?
Navbar to be visible and content to start at the bottom of the navbar.

**Steps to reproduce:**
1. create two components one with ion-header and ion-navbar and one without.
2. add them to a page that displays them exclusively of each other
3. make the component with the navbar visible after entering the page

**Other information:**
 

**Which Ionic Version?** 1.x or 2.x
2.x beta-10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/ny7p0tHiueb5TBWUaPTs?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because of how integrated our navbars and headers are with our animations we cannot recommend at this time that you wrap them in components and dynamically switch between them. Sorry if this causes any hassle. Thanks for using Ionic!
