### ISSUE TITLE
bug: [Bug] Ios radio buttons don't show

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7356]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In android a radio button is clear that it is a radio button since in front of each button is a circle border, and when selected its a circle surrounded by a circle border.

However in Ios this is not the case, the ios radio doesn't show and when checked only shows a checkmark which makes hard to tell if it's a radio group or a checkbox.

The best example is in the [radio-group](http://ionicframework.com/docs/v2/api/components/radio/RadioGroup/) ionic 2 docs when alternating between the android and ios emulated view:
![image](https://cloud.githubusercontent.com/assets/9698639/16921541/8db9d84c-4cd7-11e6-974c-131a859ee5bf.png)
![image](https://cloud.githubusercontent.com/assets/9698639/16921556/97568a80-4cd7-11e6-929d-9e492fb836df.png)

</span>

<span is-issue-template></span>

**Comment by aksharpatel47** [comment]
Native iOS does not have radio button. I have used checkmarks in place of radio buttons in the past when developing natively for iOS. However, if they're implemented in some other way in Ionic, I'm curious to see what form they take.

**Comment by Luchillo** [comment]
Well if they don't then how does native ios developers present a radio-group like setup?

If in fact it doesn't exist why not using the ones in the Android version? even if it doesn't translate to a native like interface for ios devises, it's better than just showing nothing when unselected, if i didn't tell you the first image was about `radio-groups` and none was selected, you would think is a simple list, which goes against UX patterns.

UX patterns says the user should be able to tell apart how any part of the app works with just a glance, it's counter intuitive if the radio buttons look just like a simple list, thus confusing the user to whether they need to take action there or is just an informative list (or something like that).

**Comment by jgw96** [comment]
Hey @Luchillo thanks for opening an issue with us! So after discussing this with our designer we are going to keep it the way it is for now since that is the way native ios works. Our goal with Ionic is to be as close to a native ui as possible out of the box, but the good thing about Ionic is that it's all web tech, which means you can use css to customize anything the way you need! Also, you can always use our Material design mode on ios by just specifying mode in the bootstrap like this 
```
ionicBootstrap(MyApp, [], {
  mode: "md"
});
```
Thanks for using Ionic!

**Comment by Luchillo** [comment]
Ok, do i have to specify the mode or is there one for just `radio-group` components?

Also do the native ios actually show their `radio-groups` as an input?

**Comment by jgw96** [comment]
@Luchillo There is not one just for `radio-group` but you can always use your own css to customize it. The native ios `radio-group` looks and works exactly like ours. I would recommend checking out the [ios ui guidelines] for more info. Thanks!
