### ISSUE TITLE
<ion-datetime> incorrectly converts negative ISO timezones

### ISSUE THREAD

**Issue by hotforfeature** [driftyco/ionic#7358]
#### Short description of the problem:
When `<ion-datetime>` `[(ngModel)]` is bound to an ISO string with a negative timezone (ex: `2016-01-01T12:00:00.000-05:00`), all updates after a date has been selected get converted with a double minus sign (turns into `2016-01-01T12:00:00.000--5:00`) which is incorrect for the spec. Passing it into the constructor of a `Date` object is an invalid date.

#### What behavior are you expecting?
Negative timezones should be formatted as `-XX:XX` instead of `--X:XX`.

**Steps to reproduce:**
1. Create an `<ion-datetime>` with a negative timezone value.
2. Open the picker and change it to a new value.
3. Examine the bound model value to see the change.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

#### Plunker that shows an example of your issue

http://plnkr.co/edit/M6BXQuhHEcV5GtAcRv8M?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.8.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
PR merged, closing!
