### ISSUE TITLE
`ionic g page auth/login` makes app/pages/auth-login instead of app/pages/auth/login

### ISSUE THREAD

**Issue by sathishvj** [driftyco/ionic#7360]
#### Short description of the problem:
Sometimes I want to group some of my pages or providers under a folder.  For example, authorization has a login page, signup page, forgot password page, etc.  I would like to create pages like `ionic g page auth/login`.

#### What behavior are you expecting?
I was expecting a folder structure like `app/pages/auth/login`.
But I get `app/pages/auth-login`.

Similarly for other generators.

**Steps to reproduce:**
1. create a new project
2. ionic g page auth/login
3. check folder structure under app/pages.

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 3.0.0
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-camera-component-demo#1

**Comment by jgw96** [comment]
Hello, as this was an issue with the cli and not the framework I have moved this issue over to that repo. Thanks for using Ionic!

**Comment by alexbainbridge** [comment]
@jgw96 Think you moved it to a camera component rather than CLI :)

Incidentally, I had a similar request https://github.com/driftyco/ionic-cli/issues/868

**Comment by jgw96** [comment]
Ahh sorry @alexbainbridge. Thanks for the heads up!
