### ISSUE TITLE
SqlStorage ignores statements separated by semicolon

### ISSUE THREAD

**Issue by sasos90** [driftyco/ionic#7362]
Hi guys!

I have some issues with SqlStorage.

#### Multiple statements in one query
I want to execute a huge amount of INSERT statements at once (~30k of data) like a bulk. Therefore I created a huge string (multiple INSERT statements) which includes all of these data and execute it in only one query (because if I run query for each row, it will never be finished. When I try to execute the SQL statement, it executes successfully, but it inserts only first row and ignores the others.

#### Separate statements in query with semicolon ";"
I would like to use multiple SQL statements in one query or to use some transactions or something.

**Steps to reproduce:**
1. Just execute two INSERT statements like this: "INSERT INTO table (col1, col2) VALUES (1, 5); INSERT INTO table (col1, col2) VALUES (6, 7);"

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v4.4.2

Thank you very much!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to do something i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
