### ISSUE TITLE
feat: ion-item accordion

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#7369]
![jul-20-2016 01-45-00](https://cloud.githubusercontent.com/assets/127379/16970339/9a228b0c-4e1b-11e6-89a7-30cd4ef82e10.gif)

Possible markup:

``` html
<ion-item>
  <ion-label>More info</ion-label>
  <ion-accordion>MORE CONTENT</ion-accordion>
</ion-item>
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#101
