### ISSUE TITLE
ion-option-button doesn't work with nested lists

### ISSUE THREAD

**Issue by punknroll** [driftyco/ionic#7371]
#### Short description of the problem:

The directive ion-option-button doesn't work with nested lists as it finds the inner buttons first. 
#### What behavior are you expecting?

After swiping the first element you should see the option button.

**Steps to reproduce:**
1. Create a nested list
2. Swipe the first element
3. The option button for the first element is not shown

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I already created a fix for that:
https://github.com/styleflashernewmedia/ionic/commit/9fe08ddf25dc398d40607d09ea0294e18b286d1b
Here is the codepen with the fix applied:
http://codepen.io/punknroll/pen/LkQXjW

**Which Ionic Version?** 1.x
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://codepen.io/punknroll/pen/YWaKkP

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#108
