### ISSUE TITLE
ionic throttle and debounce missing doc

### ISSUE THREAD

**Issue by R1Daneel** [driftyco/ionic#7373]
I saw that the global object `ionic` exposes two interesting methods:

- throttle

- debounce

But I did find any official doc for ionic 1.x that describes them. Is there a reason for which they are not documented?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#710

**Comment by jgw96** [comment]
Hello, since this was a documentation issue i have moved this issue to the proper repo. Thanks for using Ionic!

**Comment by R1Daneel** [comment]
Thanks you for the rapid response.
