### ISSUE TITLE
2.0.0-beta.10 Pager Slider problems

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic#7374]
#### Short description of the problem:
After upgrading to beta.10 the pager slider has some issues in my app. After page refresh, pager slider shows only one page and sliding is not working. When I resize the page even slightly, the pager slider re-renders and becomes correct, and sliding starts working.

*beta.9*
When rolling back to beta.9, pager slider works as expected.
*beta.10*
Upgrading back to beta.10 breaks it in a way that it initially renders only one slide and sliding not working.
*2.0.0-beta.10-201607151701*
Upgrading to today latest 2.0.0-beta.10-201607151701 makes it break even differently. The sliding works from initial render, but pages are not shown at all. Resizing window doesn't help, must be some changes in slider API.

#### What behavior are you expecting?
When using this api `<ion-slides pager>` I expect the slider to render the pager widget on the bottom, showing how many pages there are and colouring the active page. I expect it to work from the initial render.

#### Steps to reproduce
I cannot reproduce it on clean starter app, but I reproduces it in plunker, see below.
You also can clearly see something is odd on this screen cast http://quick.as/QWX8InzeJ

**Which Ionic Version?** 1.x or 2.x
2.beta.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/dwBLuL2YIeuz6B4Pgx1a?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201607151701
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This has actually already been fixed and will be in the beta.11 release. Thanks for using Ionic!
