### ISSUE TITLE
What is the best place to submit a feature request for ionic.io ?

### ISSUE THREAD

**Issue by enyosolutions** [driftyco/ionic#7377]
Hello !

Im trying to submit a feature request for the ionic.io platform 

```
Add a 'does not contain' filter in the ionic push service
````

Where should i post this ?

thanks

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Here is our brand new [platform wishlist](http://ideas.ionic.io/ideas/top) where you can submit all your ionic platform ideas! Thanks for using Ionic!
