### ISSUE TITLE
Using Ionic2 Without CLI

### ISSUE THREAD

**Issue by galsch** [driftyco/ionic#7379]
Hi,

I would like to integrate Ionic2 lib to my current working project which already has a lot of Webpack specific configuration + Cordova (It's a website + native apps).

I'd like to keep my current configurations I'm already using without a lot of changes - therefore I don't want to use the Ionic CLI.

What's the minimum requirements I need to do in order to integrate Ionic2 SDK into my current project without using the Ionic CLI?

Thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
