### ISSUE TITLE
Side Menu Gets Stuck

### ISSUE THREAD

**Issue by dovidkopel** [driftyco/ionic#738]
I've noticed this issue from time to time. I would be swiping either opening or closing the side menu and it would get stick in this middle position. Note, that this screenshot takes place after I have remove my finger from the screen after swiping. It should never stay still like this.

![screenshot_2014-03-06-20-00-53](https://f.cloud.github.com/assets/1078458/2352875/0e5878e8-a594-11e3-8797-724b4ebeec4c.png)

**Comment by azachar** [comment]
Hello, 
Actually, I am having the same issue again. I am using ionic 1.3.2, could you tell why?

![image](https://cloud.githubusercontent.com/assets/4659019/22659950/e6a45154-ec9f-11e6-8993-b1cbdb61a57f.png)


Thank you!

Best regards,
Andrej
