### ISSUE TITLE
Ionia beta 2.10 bug when click on clear in a search bar

### ISSUE THREAD

**Issue by zefrench** [driftyco/ionic#7384]
Did you notice on iOS, when you click on the clear button in the searcher, the text is not cleared and then, when you click on cancel, the width of the searcher is wrong cos the 'cancel' button is not hide and the clear button is not disappears ?
![ios_bug_inputsearch](https://cloud.githubusercontent.com/assets/8473372/16999325/07861fc6-4e83-11e6-94b0-7c9e486f06cc.gif)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I just tested the latest master and this seems to be already fixed and will be in the beta.11 release. Thanks for using Ionic!
