### ISSUE TITLE
bug: Text field and range element conflict

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#7389]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When typed into either text field or text area and then proceeding to changing range element value and when the finger is released from range element then keyboard is opened because the last text field element is still active. Desired behavior is that when clicked on range element then the text field is deactivated just like when clicking on anywhere else.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
