### ISSUE TITLE
Button text doesn't align vertically when button has icon(-right) class

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic#739]
Hi guys,

I noticed a bug in the button styling. When I create a new with the following class: "button button-outline button-block button-energized icon-right ion-chevron-right" like so:

```
<button class="button button-outline button-block button-energized icon-right ion-chevron-right disable-user-behavior">Login</button>
```

The 'Login' text doesn't align vertically anymore. When I remove the icon-right class, it works again.

I'm using Ionic v0.9.26

**Comment by kenarai** [comment]
Had the same problem with the current version. Seems the problem occurs with the following case. 

`<i class="icon ion-android-time"></i>View History`

My solution is that wrap the above code with a parental div & applied line-height. Works perfectly.

`<div class="view_history"><i class="icon ion-android-time"></i>View History</div>`
`
.view_history {
position: relative;
float: left;
color: #2586B7;
cursor: pointer;
font-weight: 700;
font-size: 11.4px;
margin-right: 25px;
line-height: 30px;
} 
.view_history i {
    line-height: 30px;
    vertical-align: middle;
    font-size: 16px;
    margin-right: 9px;
    display: block;
    float: left;
}`

**Comment by HannahCarney** [comment]
this is still a problem
