### ISSUE TITLE
Splash screen size problem

### ISSUE THREAD

**Issue by michelebravo** [driftyco/ionic#7392]
Hi! 

I have added a splash screen to my Ionic App. 
I have followed the official Ionic procedure like in this [link](http://ionicframework.com/docs/cli/icon-splashscreen.html.)

Everithing work but the splash screen on [device](http://imgur.com/a/oXHyX) is not likke the [real image](http://imgur.com/a/rHHaH) because the circle in the center is became an oval. 

Could anyone say me something more about this problem or give me a solution?

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by furyscript** [comment]
I have the same problem, can you help us there without cross to forum?

Thanks!
 @jgw96

**Comment by michelebravo** [comment]
@jgw96 I have asked the same question in the forum yesterday as you recommended me, but after one day anybody have approved my question and I still have this problem!

@furyscript write me if you have found a solution, please!
