### ISSUE TITLE
NavOption which opens a page without pushing it to the stack [v2]

### ISSUE THREAD

**Issue by kz** [driftyco/ionic#7394]
Related issues: #6623 #6556 

I currently have a splash page which opens either a main page, login page or setup page. I do not want users to be able to go back to the splash page. Currently, `nav.push` doesn't seem to have an option to prevent users from going back to the page which called it. I tried setting `climbNav: false`, but that doesn't seem to be related. As a result, perhaps a NavOption which opens a page without pushing it to the stack might be useful?

**Comment by biesbjerg** [comment]
It sounds like in your case you could use setRoot:
```ts
// ... Logic that determines which page to go to ...
this._navController.setRoot(ThePage);
```

**Comment by kz** [comment]
@biesbjerg Thanks for your reply - that solved what I wanted to do. I should've tested `setRoot`, so my bad for not doing so.
