### ISSUE TITLE
Issue with nav.setRoot and sideMenu

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7395]
#### Short description of the problem:

I have to close a Modal and that by returning back to the root view, for that I do the below piece of code:

>  this.nav.setRoot(HomePage);

It works fine and goes back to the root view, the only problem is that I have a side menu on that root page (HomePage), I can open it fine, but when I click to open any page existing on that menu, it does not show up and it goes back to the root page again (it dismisses the menu) and does not open the pages knowing the it runs the content of the page I clicked on _I knew it doing a console.log_ 

Hierarchy of what happens (Step By Step)

(Dismiss) Second page
        |____ (Show) Root Page
                   |____ (Open) SideMenu
                               |___ (click to open a page that exists on SideMenu)
                                            |___ BOOM (it does not open the page I clicked, dismissed the sideMenu)

#### What behavior are you expecting?

When closing the modal and back the root page, then going to the side menu, it should open the page I clicked on.

Hierarchy of what should happen

(Dismiss) Second page
        |____ (Show) Root Page
                   |____ (Open) SideMenu
                               |___ (click to open a page that exists on SideMenu)
                                            |___ Opens Page 3
  

**Steps to reproduce:**

1.  Setup a modal that opens from the root, with a side menu too.
2. Close the modal you opened using ` this.nav.setRoot(HomePage);`
3. Click on a page that exists on that side menu.

**Which Ionic Version?** 2.x

```
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
