### ISSUE TITLE
Unable to use state navigation animations in child states

### ISSUE THREAD

**Issue by winknudge-tomm** [driftyco/ionic#7396]
#### Short description of the problem:
When trying to use either (`ui-sref` & `nav-direction` attributes in the DOM) I have also tried removing the ui-sref and completing the task in the controller (`$ionicViewSwitcher.nextDirection` & `$state.go`)

Either way the animation direction of navigation is ignored 

#### What behavior are you expecting?
States to navigate as if they weren't child routes.

**Steps to reproduce:**
1. Create child routes in ui-router
2. Attempt to navigate to them using either ui-sref or $state.go 
3. State changes but no animation is present

*Example of the state provider in question*
```
$stateProvider.state('playerReport', {
	    url: '/player-report',
	    templateUrl: 'ng/components/player-report/player-report.view.html',
	    controller: 'playerReportController',
           abstract: true
    }).state('playerReport.player', {
      url: '/player/:playerId',
      templateUrl: 'ng/components/player-report/select-age-group.view.html',
      parent: 'playerReport',
      controller: 'playerReportController'
    }).state('playerReport.select-age-group', {
      url: '',
      templateUrl: 'ng/components/player-report/select-age-group.view.html',
      parent: 'playerReport'
    })
```

*Example of the DOM element used to navigate*
```
		<ion-item
			class="item button-link-item item-icon-right item-text-wrap c-main-background"

			ng-class="{'active' : currentReport.ageGroup === age.name }"
			ng-repeat="age in playerReportConfig track by $index"
			ng-click="setCurrentConfig(age.name)"
			nav-direction="forward" 
			ui-sref="playerReport.player-abilities">

			{{age.name}}
			<i class="icon ion-arrow-right-b"></i>
		</ion-item>
```

Ionic 1.2.4

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3 Build version 7D175 

```

Thanks, Tomm

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
