### ISSUE TITLE
Using *ngIf on an ion-tab causes the ordering of tabs to be incorrect

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#7397]
#### Short description of the problem:
If I use *ngIf on an ion-tab, and it evaluates to true, then the ion-tab becomes the rightmost tab, even if it should be in a different position

#### What behavior are you expecting?
I expect the correct order to be retained. Check the plunker below: Go to the tabs page and observe that Tab 2 comes after Tab 3. The tabs should be in the order of 1, 2, then 3.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/2QXUPct8vhemixpuCOtN?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We actually have a `show` property that you can bind to to get similar functionality to a raw `*ngIf` but without issues like this. [Here](http://ionicframework.com/docs/v2/api/components/tabs/Tab/) is the documentation for it if you would like to read more. Also, i made a plunker [here](http://plnkr.co/edit/wW5adP5cNLE3JR5xJlAp?p=preview) that shows how to use it. Thanks for using Ionic!

**Comment by zakton5** [comment]
Oh I didn't know about that. Thank you. I'm sorry to have wasted your time!

**Comment by jgw96** [comment]
No problem at all! Have fun building your app!
