### ISSUE TITLE
item-sliding fireSwipeEvent method

### ISSUE THREAD

**Issue by BugsBunnyBR** [driftyco/ionic#7398]
#### Short description of the problem:

The method `fireSwipeEvent`is listed in the docs [here](http://ionicframework.com/docs/v2/api/components/item/ItemSliding/) but is marked as `private` [here](https://github.com/driftyco/ionic/blob/master/src/components/item/item-sliding.ts#L342).

It would be nice to sync the docs and source.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
Plus, I would like to have a way to slide an item to open programatically. It is not always intuitive to users the slide movement, but a button with an action that animates the slide could help to show how. To enable that, a public version of something like `fireSwipeEvent`would help.

**Which Ionic Version?** 2.x

Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#717

**Comment by jgw96** [comment]
Hello, as this is more of a docs issue than a framework issue I have moved this issue to the appropriate repo. Thanks for using Ionic!
