### ISSUE TITLE
docs: Ionic 2 Plunkr or Codepen in readme

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7399]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hiii,

It would be nice to have plunkr or codepen in Readme or Docs which is being regularly updated.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#716

**Comment by jgw96** [comment]
Hello, since this was an issue related to docs and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
