### ISSUE TITLE
Input Cursor Moves with Scroller

### ISSUE THREAD

**Issue by theCodeMachine** [driftyco/ionic#740]
If we scroll the view with input fields focused then cursor move with the scroll till the time tap event finishes.

Also on iPad screens sometimes cursor comes little over the exact input field.

Please suggest some solution or make some fix according to it.

Thanks.

**Comment by bittusinghintruder** [comment]
I am still facing this issue in latest cordova.

**Comment by exeqio** [comment]
Still experience this error with latest cordova. Any temporary workaround?

**Comment by tlancina** [comment]
Hey this issue is from a pretty old version of Ionic. If there's a regression, I'd suggest opening a new issue.

**Comment by davebcn87** [comment]
Having the same issue with Ionic 1.3.1

**Comment by kikill95** [comment]
I have faced with this trouble with following versions:
iOS: 9.3.5
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jdnichollsc** [comment]
same issue with iOS 10 and Ionic 1.3.2

**Comment by fatihayyildiz** [comment]
Guys, anyone solved this issue ? I am using version : 1.2.1

**Comment by vkurlyan** [comment]
It happend for me because of body element has css property "position: fixed".
Try this:

> body {
>   position: static!important;
> }
