### ISSUE TITLE
v2:bug(nav) open alert in page not completely loaded break navigation 

### ISSUE THREAD

**Issue by DavidWiesner** [driftyco/ionic#7400]
#### Short description of the problem:

If I click on an element that will open an alert while the page isn't loaded completely yet. Will break the Navigation. So I can't go Back any more or the sometimes the page will never load completely.

#### What behavior are you expecting?

Any click on the loading page should be blocked until the page is loaded.

**Steps to reproduce:**
1. Create a page with button that will open an alert.
2. Click on the location where the button should be before the page is loaded
3. Alter will open
4. You cannot go back with the navbar any more

**Which Ionic Version?**  2.0.0-beta.10

#### Plunker that shows an example of your issue
Open this plunker and continuous click the FAB button in the bottom right corner (maybe try another time if not working in first place or try the plunker on a mobile device). `page1` will load some data to slow down the page load. But this isn't necessary on slow mobile devices.

https://plnkr.co/edit/7zo3Uq?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
Node Version: v5.12.0

**Comment by jgw96** [comment]
Hello, thanks for opening am issue with us! Unfortunately I am having trouble reproducing this issue with the provided plunker. What device are you testing with? Thanks for using Ionic!

**Comment by scorpnode** [comment]
i have the same issue i had to use alternative navigation options to work around this. still present in nightly

**Comment by masimakopoulos** [comment]
same issues here with nav.present in general. If it happens while view is loading everything you get stuck. One easy way to reproduce it is to show alert in a page constructor or in ngOnInit.

**Comment by jgw96** [comment]
@masimakopoulos Anything that is ui related, such as opening alerts, should be done in our `ionPageDidEnter()` lifecycle hook. You can read more about that [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/). That should fix the issue you are describing (:

**Comment by DavidWiesner** [comment]
@jgw96 The plunker example is working on my nexus 5, huawei P8 lite and on Desktop Google  Chrome 48.0, Firefox, 45.2 and  Opera 38.0. 
Here are the instructions to raise the bug within the plunker
https://plnkr.co/edit/7zo3Uq?p=preview

1. continues click the FAB on the bottom right in the first page (by continuous clicking the FAB you will then also click the FAB on the next page when this will load)
2. the continues click will then open an alert on the second page
3. close dialog 
4. try to go back with the backbutton on the upper left corner
5. sometimes the page was pushed multiple times and you have to go back with multiple steps sometimes you cannot go back at all. So nothing will happen by clicking the backbutton also the Backbutton on Android won't do anything. 

Maybe repeat steps 1-4 multiple times until the bug occurs.
This bug is really annoying. It will break the entire navigation.   
@scorpnode @masimakopoulos can you reproduce the issue within the plunker?

**Comment by chandanch** [comment]
Use the ionPageDidenter(). In my app there user will navigate from page 1 to page 2. On page2, i use the ionPageDidEnter() to check for internet connection if no internet it shows the alert

**Comment by DavidWiesner** [comment]
@chandanch I can't use `ionViewDidEnter` because I didn't open an alert on page loaded. The user click on an active item on the loading page (e.g. accidentally because the user think the previous action doesn't open the page - but the page is only still loading). This active item has a click listener that will open an alert.

**Comment by masimakopoulos** [comment]
@jgw96  I did not know of this limitation about "presentable" views. Why is this a constraint? ngOnInit seems like a better place to load data needed for a view that ionViewDidEnter (which can be invoked more than once) and a loading modal would be required there. Since you can not show a loader there though as you say, ngOnInit becomes unusable for such tasks and more logic has to be introduced to prevent multiple calls.

@DavidWiesner can you log when click is pressed and when ionViewDidEnter is fired? If click shows up first, I guess that is the problem, according to what @jgw96 is saying about when dialogs should be presented.

**Comment by DavidWiesner** [comment]
@masimakopoulos You are right `ionViewDidEnter` will not be fired before the alert will be presented. I've updated the plunker and add a debug log. But **it's not me presenting the alert automatically**. The user click the button to open the alert. The `NavController` should prevent this behaviour. In the plunker I could take control that the alert will be shown only when `ionViewDidEnter` was enter. But in my real application the alter will be opened by the form element `ion-select`. That I can't control.

**Comment by masimakopoulos** [comment]
@DavidWiesner yeap, I got that the alert will be shown after a user interactions, just pointing out a way to make your case clear. I believe that "presentable" popups are very flimsy since if everything is not orchestrated perfectly you end up with broken navigation. Hopefully the ionic team will have a more resilient version of them down the line.

**Comment by jgw96** [comment]
Hello all! We have refactored the overlay components such as alert for the upcoming beta.11 release. They are now no longer part of the nav stack which will fix this issue. Thanks for using Ionic!
