### ISSUE TITLE
feat: Spinner color

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7401]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ion-spinner is only black color, and to change it you need to use css.
Please make it possible:
`<ion-spinner primary></ion-spinner>`
</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
Related to https://github.com/driftyco/ionic/issues/7087

**Comment by mlynch** [comment]
@brandyscarney did your commit above fix this?

**Comment by brandyscarney** [comment]
@mlynch Yes, it will be fixed once my branch is merged.

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta 12` release. You will be able to pass a color via the `color` input. See this file for some examples: https://github.com/driftyco/ionic/blob/master/src/components/spinner/test/colors/main.html
