### ISSUE TITLE
ionic2 - bug(tabs) ios - pushing a second tabs page results in the 2nd tab bar being hidden under the 1st tab bar

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#7403]
#### Short description of the problem:
I have a navigation hierarchary like this:

TabsPage1
    Tab1
    Tab2
    Tab3 --> (Clicking an item in a list takes us to TabPage2)
                    TabsPage2
                         Tab1, etc....

The problem is that the tabbar for TabsPage2 is hidden underneath the tabbar of TabsPage1, but this only happens when the mode is iOS.

#### What behavior are you expecting?
The tabbar for TabsPage2 should be over the tabbar of TabsPage1
Check out the plunker below

**Which Ionic Version?**2.x

#### Plunker that shows an example of your issue
http://embed.plnkr.co/yKmyld1vN78tSNQhMCPW/

1. Go to Tabs Page 1
2. Go to Tab 3
3. Click Go to Tabs Page 2
4. Observe that the order of the tabs is 1, 2, 3. It should be 3, 2, 1 

I do not know how to switch the ionicPlatform to iOS in a plunker. By default, ionic's mode is Android. If anyone is able to switch the mode to iOS, it __should__ work.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for opening am issue with us. Currently we only recommend that you use one tabs component in your application, as the root component. We may support having multiple tab pages in the future, but at this time we dont. Sorry for any hassle this causes! If we decide to support multiple tab components in an application I will reopen this issue. Thanks for using Ionic!
