### ISSUE TITLE
Tabs not properly centering on wide viewports

### ISSUE THREAD

**Issue by chrisgriffith** [driftyco/ionic#7404]
When running an Ionic v2 app (beta 10) in a browser on an iOS device, if the device is placed in landscape mode, the tabs are not centered across the viewport. 

![img_1879](https://cloud.githubusercontent.com/assets/527875/17060092/376e500e-4fdd-11e6-8f89-9e32bff896e4.JPG)

**Comment by jgw96** [comment]
Hello, this may have been fixed already, would you give ionic 2 nightly a try and see if that solves the issue? To use Ionic 2 nightly just run `npm install ionic-angular@nightly`. Thanks for using Ionic!

**Comment by MasterProgrammer200** [comment]
I am having the same problem when running on an iPad.

When I do an ionic serve it looks fine:
![screen shot 2016-07-22 at 2 50 56 pm](https://cloud.githubusercontent.com/assets/10147954/17069272/c4894dc2-5023-11e6-9020-37e8d8f433fe.png)

However on the iPad the tabs as off center:
![img_0031](https://cloud.githubusercontent.com/assets/10147954/17069281/d31b9f84-5023-11e6-88f3-7cc10d95520a.png)

I will try the nightly version.

**Comment by MasterProgrammer200** [comment]
@jgw96 Upgrading to the latest nightly version did not work for me.

**Comment by brandyscarney** [comment]
I was able to reproduce this issue using the conference app with 2 tabs in Chrome simulating an iPhone and iPad. Thanks for the issue! I'll look into this soon.

**Comment by brandyscarney** [comment]
It seems adding the following css fixes it, but I'll have to see what all this affects:

```
ion-tabbar {
  justify-content: center;
}
```

**Comment by brandyscarney** [comment]
So this was actually fixed by https://github.com/driftyco/ionic/pull/7159 in master. You can add the above code to your Sass file or you can wait until beta 11 is released and we'll have some steps to upgrade. :) I've confirmed this is fixed though with that PR. Thanks for the issue!
