### ISSUE TITLE
V2: Default android ion-spinner (crescent) does not render correctly on device

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic#7405]
#### Short description of the problem:
I am using Loading and <ion-spinner> in various parts of my app. On browser (emulating Android) and IOS (has different default spinner) everything works fine. When deploying to an android device the default android spinner "crescent" does not render correctly. Instead of showing part of a circle spinning around, a complete, still circle appears.

#### What behavior are you expecting?
The spinner animating correctly on the device as it does on the browser

**Steps to reproduce:**
1. Add a <ion-spinner name="crescent"></ion-spinner>
2. Deploy to a device
3. Watch a complete circle doing nothing 

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello @masimakopoulos which version of Android are you testing on? There was a bug in the chrome webview not too long ago that caused this issue, but with the latest webview (and about two versions before) it is working fine. Thanks!

**Comment by masimakopoulos** [comment]
Hi @jgw96,

I am currently testing with latest version of Crosswalk.
`"Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Crosswalk/19.49.514.5 Mobile Safari/537.36"`
```
    <preference name="xwalkVersion" value="19+" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
    <preference name="xwalkMode" value="embedded" />
    <preference name="xwalkMultipleApk" value="true" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~1.8.0" />
```

Just tested it with default system view on Samsung S6 Android 6.0.1 with web view version 51.0.2704.81 and it works fine there. Installing the app using crosswalk plugin on the same device (as well as 3 others) has the mentioned effect though.
Any idea if this is a regression or I just not on the right version yet?

**Comment by jgw96** [comment]
The latest version of crosswalk seems to be using chrome 49 which has the aforementioned bug in blink (the rendering engine in chrome). Your s6 is running the latest chrome webview which is why it is working fine there. I would recommend trying out the beta channel of crosswalk as it should be using a newer version of chrome. Since this is not an ionic issue, but just a bug in chrome i will be closing this issue for now. Thanks for using Ionic!

**Comment by masimakopoulos** [comment]
@jgw96 thanks for clearing this up. I thought crosswalk would be using the latest versions but I guess this is not the case. Thanks for taking the time and helping me out.

**Comment by jgw96** [comment]
No problem, glad I could help! Crosswalk does lag behind a little but the beta channel of crosswalk should be running on a newer version of chrome.
