### ISSUE TITLE
checkbox "checked" binding not taken into account

### ISSUE THREAD

**Issue by mmazloum** [driftyco/ionic#7406]
let's say catDict is a dictionnary of type : 
`public catDict: { [id: string]: boolean; }`

if I bind catDict on a checkbox like here :
`<ion-checkbox checked="catDict[p._id]" (change)="updateSelected(p._id)"></ion-checkbox>`
also tried
`<ion-checkbox [checked]="catDict[p._id]" (change)="updateSelected(p._id)"></ion-checkbox>`

I expect the check box to check or uncheck itself reactively based on the value stored in catDict[p._id]

but nothing happens, am I doing something wrong ?

I'm using Ionic2 : "ionic-angular": "2.0.0-beta.7"

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by mmazloum** [comment]
ok but it really looks like an issue... sorry if it looks like a question
