### ISSUE TITLE
v2 feature request - responsive ion-segment

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#7407]
An ion-segment can have many segment buttons. e.g. 8, each with a word. While this looks OK on a larger view, its too compressed on a smaller device and can end up with the segment word within a button being hidden due to insufficient segment button width

At this point its better to have two ion-segments, each with 4 segment buttons.

e.g.
row 1 - Button A, B, C, D
row 2 -Button E, F, G, H

However this doesn't look so nice, as the segment buttons are rounded, and the line that is between the now 2 ion-segment rows, has a duplicated horizontal line, so looks double width.

IDEALLY what would be great would be to be able to add e.g. responsive-md to ion-segment, to be configured with 8 segment buttons, and at a certain width, automatically respond moving to two rows, each with 4 segment buttons, and that the second row looks elegantly designed

**Which Ionic Version?** 1.x or 2.x
2

**Comment by brandyscarney** [comment]
Could you add an image of what you're trying to achieve please? :) From a UX standpoint, I think it would be confusing to have so many segment options. What is the use case for this?

**Comment by alexbainbridge** [comment]
![image](https://cloud.githubusercontent.com/assets/1144763/17068690/5adf604c-504a-11e6-9e3c-9ef91b09fae1.png)

This is what happens when you put two ion-segment rows on top of each other

* Double width line between the two rows
* The rounder corners, on the inside, should not round

Both are fixable by CSS of course, so no worries if you choose not to do this :)

What I would like is to be able to create a single ion-segment with 8, and it to automatically create two rows of 4, when device size suggests this is more appropriate.

Re UX - yes - this is not a consumer facing app. Its for the top of a configuration screen for something that has 8 distinct configuration sections.... each section has an entire screenful of settings showing / hiding depending upon the selected segment.

**Comment by brandyscarney** [comment]
So in my opinion this is really specific to your application. I don’t think it is something that should be added to the framework because we can't assume that everyone wants it to wrap around exactly at 4 buttons or modify the borders. Some may want all of the segment buttons to stay on the same line (for example if they had icons), and others may want to scroll the segment. I'd recommend using a custom class and media queries to achieve this. For example:

```
<ion-segment [(ngModel)]="modelStyle" class="segment-wrap">
  <ion-segment-button value="A">
    A
  </ion-segment-button>
  <ion-segment-button value="B">
    B
  </ion-segment-button>
  <ion-segment-button value="C">
    C
  </ion-segment-button>
  <ion-segment-button value="D">
    D
  </ion-segment-button>
  <ion-segment-button value="E">
    E
  </ion-segment-button>
  <ion-segment-button value="F">
    F
  </ion-segment-button>
  <ion-segment-button value="G">
    G
  </ion-segment-button>
  <ion-segment-button value="H">
    H
  </ion-segment-button>
</ion-segment>
```

Then in the Sass (you could tweak the max-width):

```
@media (max-width: 600px) {
  .segment-wrap {
    flex-wrap: wrap;

    .segment-button {
      flex: 1 0 25%;
    }

    .segment-button:nth-child(-n+4) {
      border-bottom: none;
    }

    .segment-button:first-of-type,
    .segment-button:last-of-type {
      border-bottom-left-radius: 0;
      border-top-right-radius: 0;
    }

    .segment-button:nth-child(4) {
      border-top-right-radius: 4px;
    }

    .segment-button:nth-child(5) {
      border-left-width: 1px;
      border-bottom-left-radius: 4px;
    }
  }
}
```

and the result is this:

![screen shot 2016-07-22 at 8 02 06 pm](https://cloud.githubusercontent.com/assets/6577830/17074233/534e11d2-5047-11e6-9f15-2f9d53b885a4.png)

![screen shot 2016-07-22 at 8 02 13 pm](https://cloud.githubusercontent.com/assets/6577830/17074234/5350e6aa-5047-11e6-9759-660705fa10fa.png)

I'll leave it open for discussion though and talk to the team about it. :) The only way I can think of adding this is if we had a `wrap` attribute with a variable that sets the number to wrap at and used that number to determine the button width and when to change the borders. That would allow users to customize it.

**Comment by alexbainbridge** [comment]
Thank you Brandy!

**Comment by drsatan1** [comment]
even though that's some dank code, I believe that the argument "no framework should do this" is flawed, since I came here looking for exactly that.

**Comment by brandyscarney** [comment]
@drsatan1 My statement of not adding it was in response to wrapping it exactly every 4 segments:

> I don’t think it is something that should be added to the framework because we can't assume that everyone wants it to wrap around exactly at 4 buttons or modify the borders.

I left the issue open since it is something that would be nice to add, but it would need to be added in a way that makes it easily customizable. :smile:

**Comment by alexbainbridge** [comment]
I am still trying to work out what dank means! (hello from UK)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#156
