### ISSUE TITLE
Multiple setRoot() on App with tabs

### ISSUE THREAD

**Issue by maclbb** [driftyco/ionic#7409]
I have an app, that uses the Tabs layout and preview my code with "ionic serve". When I use the setRoot() function for the navController, it generates a new <ion-page> element. However, the <ion-page> from the previos root page is still available in the code and has a higher z-index, only with opacity 0. Due to this, no buttons on the new root page can be clicked.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
