### ISSUE TITLE
Can't prevent Alert from being dismissed by Android back button

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#7411]
#### Short description of the problem:
In the Alert, we can set enableBackdropDismiss: false to prevent dismissing when tapping on the backdrop. However, we cannot prevent the Back button on a physical Android device from dismissing the alert.

#### What behavior are you expecting?
I would like to prevent Android users from tapping the physical Back button to dismiss my alert. Perhaps add this property: enableBackButtonDismiss:boolean

**Which Ionic Version?** 1.x or 2.x
2 beta 10

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this issue will be solved as part of https://github.com/driftyco/ionic/issues/7611 i am going to close this issue for now. Thanks for using Ionic!
