### ISSUE TITLE
Fixed grammar

### ISSUE THREAD

**Issue by gtzinos** [driftyco/ionic#7412]
Hello,

please change < Point is, add the number of columns your layout requires and don't worry about figuring out the percentages because it figures it out automagically. > to < Point is, add the number of columns your layout requires and don't worry about figuring out the percentages because it figures it out automatically. > in http://ionicframework.com/docs/components/#grid .

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#720

**Comment by jgw96** [comment]
Hello, as this issue was related to documentation I have moved this to the ionic-site repo. Thanks for using Ionic!
