### ISSUE TITLE
Feature request: Ionic 2 (dev/prod) environment variables configuration

### ISSUE THREAD

**Issue by amreladawy** [driftyco/ionic#7413]
#### Short description of the problem:
It is a feature request. 
Just like Angular2, I hope that Ionic can provide 2 files (environment.dev.ts and environment.prod.ts) that would contain variables with different values corresponding to production and development environment. 
During the build, the appropriate file to be copied and bundled within the app artifact. 

  

**Which Ionic Version?**  2.x

 https://forum.ionicframework.com/t/ionic-2-environment-variables-config-setup/58147/1 

https://stackoverflow.com/questions/36004810/how-to-config-different-development-environment-in-angular-2-app

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1205

**Comment by jgw96** [comment]
Hello, as this feature request was related to our build process i have moved this to the ionic-cli repo. Thanks for using Ionic!
