### ISSUE TITLE
cordova inappbrowser plugin should use a background thread

### ISSUE THREAD

**Issue by allen8300** [driftyco/ionic#7418]
I met with following error when trying to open pdf with inappbrowser plugin:

"UIPDFPageRenderOperation object 0x1589ec570 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug"

I tried different ways on google, but none work.

**Comment by ghenry22** [comment]
probably better to log this against the inappbrowser cordova plugin, this doesn't look like an ionic issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#353

**Comment by jgw96** [comment]
Hello, as this seems to be related to Ionic Native and not the Ionic Framework I have moved this issue to that repo. Thanks for using Ionic!

**Comment by ghenry22** [comment]
actually related to the cordova inappbrowser plugin.  You can ask for help in the cordova slack channel or log a bug in their Jira which you can find with a quick google.
