### ISSUE TITLE
Navigation setRoot() automatically shows ios-transitions

### ISSUE THREAD

**Issue by HerraE** [driftyco/ionic#7420]
If I want to use a transition on a page by using `nav.setRoot(Page, {}, {animate: true, direction: 'forward'});`, the standard "swipe" transition of ios is shown on every system (tested in browser with "ionic serve --lab"). But on Android I want the "md-transition" and on Windows Phone I want the "wp-transition", this should be native automatically if you don't select a specific transition by setting `animation: "xy-transition"`.

Docs: [http://ionicframework.com/docs/v2/api/components/nav/NavController](http://ionicframework.com/docs/v2/api/components/nav/NavController), take a look at "NavOptions" and the "animation" parameter.

As a workaround I check the platform by using `platfrom.is()` and use the corresponding string with "-transition" as extension.

Ionic version: CLI v2.0.0-beta.32
Cordova version: 6.2.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
