### ISSUE TITLE
Component Life cycle methods swallow errors

### ISSUE THREAD

**Issue by 0v3rst33r** [driftyco/ionic#7421]
#### Short description of the problem:
Component life cycle methods swallow errors, eg:

1. `ionViewLoaded`
2. `ionViewWillEnter`

#### What behavior are you expecting?
Errors to be logged to the console in the browser when running the app with `ionic serve`.

**Steps to reproduce:**
1. Implement the `ionViewLoaded` life cycle method
2. Implement the `ionViewWillEnter` life cycle method

```
    private ionViewLoaded() : void {

        console.log('1 - ionViewLoaded');
        if (1 == 1) {
            throw new Error('Error test');
        }
        console.log('2 - ionViewLoaded');
    }

    private ionViewWillEnter() : void {
        console.log('1 - ionViewWillEnter');
        if (1 == 1) {
            throw new Error('Error test');
        }
        console.log('2 - ionViewWillEnter');
    }
```

**Other information:**
When having the code throwing the error outside a life cycle method (e.g. in the constructor) then it logs to the console.  Do note I didn't have this issue with Ionic 2 Beta 6, started after upgrading to Beta 10.

**Which Ionic Version?**
Ionic 2 Beta 10

#### Plunker that shows an example of your issue
What versions of Ionic2/Angular2 is Plunker using, because when I put the code there, then the error logs to the console.  Do note the above issue I'm having didn't exist with Ionic 2 Beta 6, but only when I upgraded to Beta 10.

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v6.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by 0v3rst33r** [comment]
For a temp bypass for now I am wrapping my life cycling methods in try/catch blocks, e.g:

```
    private ionViewWillEnter() : void {
        try {
        // implementation
        } catch (error) {
            console.error(error);
        }
    }
```
and then I get information about the error on the console again.

**Comment by jgw96** [comment]
Hello! I have confirmed this issue and am looking into it now. It looks like there is a try catch block in our source that is causing thrown errors to be swallowed unless you put your logic in your own try catch block. Thanks for submitting an issue!

**Comment by jgw96** [comment]
After reviewing this issue some more it seems to be an angular bug https://github.com/angular/angular/issues/6651
