### ISSUE TITLE
Improvement Slides

### ISSUE THREAD

**Issue by ramonornela** [driftyco/ionic#7422]
#### Short description of the problem:
- Slides lib update Swiper to 3.3.1 see [Changelog](https://github.com/nolimits4web/Swiper/blob/master/CHANGELOG.md) with improvements e fixes

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Comment by jgw96** [comment]
Hello, since this will be a part of https://github.com/driftyco/ionic/issues/6198 i will be closing this issue. Thanks for using Ionic!
