### ISSUE TITLE
Enhancement: Make 'www' serve folder configurable.

### ISSUE THREAD

**Issue by bennorwood** [driftyco/ionic#7424]
#### Short description of the problem:
As a developer, I am forced to use '/www' as the name of my serve folder.

#### What behavior are you expecting?
This serve folder should be configurable in config.xml
_instead of 'www/index.html' have '**SERVE_FOLDER_FROM_CONFIG**/index.html' (ex: 'public/index.html')_

**Comment by royipressburger** [comment]
As far as i know this is build in configuration in cordova... ionic has nothing to do with it

**Comment by GrandFelix** [comment]
Why would you want that?

**Comment by bennorwood** [comment]
Ok..I will dig into cordova docs to double check. I just noticed a couple of cases in the source where the 'www' directory is hard coded as a string.

Why would one want to give a user control over what the public folder name will be? Why should anyone be forced to name it '/www'? If it can be configurable, why not give the developer that freedom is the better question?

**Comment by bennorwood** [comment]
I am looking to integrate ionic into an existing angular-based application though. I am currently deciding whether I need to write a gulp task that will export the project to this '/www' directory or if I just specify this in configuration.

**Comment by GrandFelix** [comment]
If you use cordova then you will be using app on mobile, right? So ehy would you change build folder? I dont see any sense here. 

If you use it on web then you are not forced to use www folder... I agree with freedom for developers, but not for everything :)

**Comment by bennorwood** [comment]
I currently have a UI server serving up assets in a public/ directory (I have no www/ directory). Its a completed app, with solid build tools/tasks.

You're suggesting that I have the exact same components from my public/ directory source controlled in a www/ folder just to use ionic? Or worse, a separate repo for the mobile version of the app? I'm not seeing/understanding your solution.

My goal is to have a simple/flattened file structure (no source controlled duplicated code), have one repo that can be built to run as a UI server, but have the flexibility to be packaged into different mobile platforms.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We use the `www` folder because this follows the cordova file structure. The ionic cli uses cordova underneath, which expects a certain directory structure that you can see [here](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#directory-structure). I would suggest opening an issue with the cordova team to discuss this as it is not really an Ionic issue, but more of a cordova issue. Thanks for using Ionic!

**Comment by bennorwood** [comment]
Ok, awesome; thanks for the feedback!

**Comment by GrandFelix** [comment]
I did not suggest anything... I just asked why would you use this. What if you create symlink from  cordova/ionic /www folder to your /public directory ?
