### ISSUE TITLE
ion-reorder broken when iterating over custom component

### ISSUE THREAD

**Issue by btroncone** [driftyco/ionic#7425]
#### Short description of the problem:
Ion-reorder functionality appears to be broken when using with a custom component. For instance, if I take the markup from an ion-item out of a component template (using ngFor) and place it inside it's own component (used like `<custom *ngFor>` instead of `<ion-item *ngFor>`) the reorder functionality no longer works. The items stick in place, with the *from* index generally returns `undefined` while *to* returns `-100`.

**I have recreated this issue in the plunker link below.**

###### Test Component
```ts
@Component({
  selector: 'test',
  template:`<ion-item-sliding >
      <ion-item>
      <h2>
        Test
    </h2>
    <p>
        Content     
    </p>
    <ion-icon name="arrow-forward" item-right></ion-icon>
    </ion-item>
    <ion-item-options side="right">
      <button danger>
        <ion-icon name="trash"></ion-icon>
        Remove 
      </button>
    </ion-item-options>
    </ion-item-sliding>`
})
export class Test {
  constructor() {
		
	}
}
```
###### Works
```ts
<ion-item-group reorder="true">
<ion-item-sliding *ngFor="let item of items">
      <ion-item>
      <h2>
        Test
    </h2>
    <p>
        Content     
    </p>
    <ion-icon name="arrow-forward" item-right></ion-icon>
    </ion-item>
    <ion-item-options side="right">
      <button danger>
        <ion-icon name="trash"></ion-icon>
        Remove 
      </button>
    </ion-item-options>
    </ion-item-sliding>
</ion-item-group>
```
###### Broken
```ts
<ion-item-group reorder="true">
    <test *ngFor="let item of items"></test>
  </ion-item-group>
```

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue
**For Ionic 2 issues** - [http://plnkr.co/edit/BUBQaBMCj2It8gKRtud5?p=preview](http://plnkr.co/edit/BUBQaBMCj2It8gKRtud5?p=preview)

**Comment by manucorporat** [comment]
@btroncone can you verify this is still a problem?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by classn** [comment]
I still have this issue

**Comment by clarkorz** [comment]
I have this issue too, please reopen it. @jgw96

**Comment by DrJonnie** [comment]
I also have the same problem in the latest ionic version 3.7.1.
Why is this issue closed? Please reopen.

Anybody know some workaround?
