### ISSUE TITLE
View title doesn't update after modal dismiss

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#7427]
#### Short description of the problem:

When you are on a view, and you open a modal, the page title (only visible on web) updates to the modal title (ion-title)

When you dismiss the modal, the title (from the modal) remains, even though the modal is no longer in view

#### What behavior are you expecting?

I expect that when you dismiss the modal, that the page title to revert back to using the title from the now visible view, not the previously shown modal

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 5.4.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? After testing and looking at our source, a modal should not be updating the title at all. Thanks for using Ionic!

**Comment by alexbainbridge** [comment]
Hello Justin
You mean a modal, when brought INTO view, should not update the title? So there was not an expectation that when the modal dismisses, that it shout revert the title...... I see. 

Let me see what I can create on Plunkr......    

Not a show stopper this.

**Comment by alexbainbridge** [comment]
The title of a view, in plunkr, is plunkr...... so this isn't going to be possible

**Comment by jgw96** [comment]
Hmm, would you be able to provide a repo that demonstrates this issue? Thanks!

**Comment by jgw96** [comment]
After reviewing this issue and the modal source i am going to close as i cannot reproduce this issue and the modal source does not have the bit of code code to update the title. Thanks for using Ionic!

**Comment by alexbainbridge** [comment]
FYI, this fixed itself in beta 11....

**Comment by eongoo** [comment]
this issue seems back again
`Ionic Framework: 3.2.1`
`Ionic App Scripts: 1.3.7`
`Angular Core: 4.1.0`
`Angular Compiler CLI: 4.1.0`
`Node: 6.9.5`
`OS Platform: macOS Sierra`
`Navigator Platform: MacIntel`
`User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46` `(KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1`

**Comment by lambreto** [comment]
it is reproducible on the 'super' template when you go to 'New item' page and after closing it.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.11.2
    npm  : 5.4.1
    OS   : macOS Sierra
