### ISSUE TITLE
Ion-select is broken, not showing any text value

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#7428]
#### Short description of the problem:

`ion-select` is broken. The popup has no text. 

#### What behavior are you expecting?

`ion-select` work as expected, showing text values for the options.

**Steps to reproduce:**

1. Create an `ion-select` with a few `ion-option`.
2. Set value for every option (`value="f"`) and mark one as checked (`checked="true"`)
3. Observe the wrong behavior
  -  The pop up window shows the radio buttons but not the associated text with them

The issue occurs with the basic code example used in the [docs](http://ionicframework.com/docs/v2/api/components/select/Select/). (Not the demo on the right, but the code used in a plunker. Maybe the demo uses an older ionic version?)

```
<ion-item>
  <ion-label>Gender</ion-label>
  <ion-select [(ngModel)]="gender">
    <ion-option value="f">Female</ion-option>
    <ion-option value="m" checked="true">Male</ion-option>
  </ion-select>
</ion-item>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

This issue can be related to other recent issues with `ion-select` like #6970, #6898
 
**Which Ionic Version?** 

Ionic 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/8p4z8T?p=preview

**Run `ionic info` from terminal/cmd prompt:**

```
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. I have tested with the latest nightly and their does not seem to be an issue anymore. If you would like to give ionic 2 nightly a try yourself you can run `npm install ionic-angular@nightly` and this will install the latest ionic 2 nightly package for you. Thanks for using Ionic!
