### ISSUE TITLE
Refresher causes a performance bottleneck 

### ISSUE THREAD

**Issue by webberig** [driftyco/ionic#7429]
#### Short description of the problem:
We have created a page that has the ion-refresher and an ion-list. We noticed that the page flashes whenever you start scrolling up and the refresher is becoming active. This only happens on iOS, tested on versions 9.3, 9.2. It works just fine on Android.

After some investigation, I noticed that the problem is caused by the Refresher component's `_onMove` function. It call the `_setCss` method, which in turn calls `content.setScrollElementStyle` several times. Because it makes 4 different changes to the style, it causes 4 repaints and recompositions which Safari isn't handling well.

The problem is not noticed if you have a simple ion-list, it only happens if the item HTML get more complicated. 

#### What behavior are you expecting?
The scrolling animation should occur smoothly without a white flash.

**Steps to reproduce:**
1. create a page with a refresher and ion-list
2. ion-list items should have a bit of styling and multiple elements such as an image, title, etc...
3. initiate a touchdown event, and start scrolling down so the refresher is activated
4. on iOS, you will see the entire page flashing

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I believe the `setCss` method could be improved, ie. by applying all necessary styles at once instead of 4 different statements. 
It appears that the repaint and recomposition are also triggered even when no actual change is needed. Perhaps this could be handled in JS before actually making changes to the scroll element's style attribute;

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

#### Plunker that shows an example of your issue
The problem only occurs when the app is running natively on iOS, browsers and Android devices don't seem to be affected. However, since this is a performance issue, it might - in theory - occur on other platforms as well if the ion-list content becomes more complicated.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by webberig** [comment]
The problem occured in a private project, and I can't copy my page publicly either, sorry...
I assumed that the code of the `setCss` method would speak for itself.

**Comment by jgw96** [comment]
Hello! Would you mind giving this a try with beta.11?

**Comment by webberig** [comment]
Hi @jgw96 

We have upgraded our app to beta.11, the flashing no longer occurs. Thanks!
