### ISSUE TITLE
start-y doesn't work when content not tall enough to scroll

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#743]
`start-y` was added back in January to be able to hide a search box.

http://forum.ionicframework.com/t/ios-mail-app-like-search-box-in-list/508/2

It no longer works:

http://codepen.io/calendee/pen/BpADr and http://codepen.io/ionic/pen/KzswD

**Comment by Teremok** [comment]
+1 to @zabojnik collection-repeat and start-y doesn't work together.
