### ISSUE TITLE
Password Reset email template control?

### ISSUE THREAD

**Issue by nickkenens** [driftyco/ionic#7430]
Are you guys planning to refactor the password reset?
Because as of now it's incredibly bad, the email template is something we have no control over and the temp. generated password is crazy long.

I've implemented it in our app but it's just because we have no other choice atm.

I'm in love with Ionic but something as basic as password reset is something we should have some control over, the email template at the very least.

Ionic v2

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! May i ask what this is in regards too (the forum?) ? Thanks for using Ionic!

**Comment by nickkenens** [comment]
@jgw96 The password reset email that is sent out using Ionic User.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#141

**Comment by jgw96** [comment]
Hello! Because this was a backend related issue and not an issue with the framework i have moved this issue to the appropriate repo. Thanks!
