### ISSUE TITLE
Ion-radio items do not work well with Angular Translate

### ISSUE THREAD

**Issue by Tobiaqs** [driftyco/ionic#7431]
#### Short description of the problem:
Ion-radio doesn't function properly when specifying a _translate_ attribute on it.

#### What behavior are you expecting?
An ok-looking ion-radio when specifying a _translate_ attribute.

**Steps to reproduce:**
1. Get Angular Translate and include it in app.js
2. `<ion-list><ion-radio translate="TAG"></ion-radio></ion-list>`

**Which Ionic Version?**
1.7.16

#### Plunker that shows an example of your issue
No Plunker but Codepen. http://codepen.io/anon/pen/OXEJoO

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Sorry but at this time we do not fully support Angular Translate with Ionic 2 apps, but it is something we want to add in the future. Thanks for using Ionic!
