### ISSUE TITLE
On Android (and maybe other platforms) Google Map gets click/tap event when menu overlays it

### ISSUE THREAD

**Issue by flew2bits** [driftyco/ionic#7433]
In Ionic 2 for the android platform, if I have a screen with a native map component and a menu, when the menu is displayed, a tap on a menu item gets routed to the map which is behind the menu. The menu doesn't react at all; i.e. it doesn't hide, nor does it redirect to the associated component.

I can provide code if needed.

**Comment by Germanaz0** [comment]
Is this related ? https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/417#issuecomment-76246526

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by Germanaz0** [comment]
@jgw96 Yes I have a sample code here: https://bitbucket.org/Germanazo/app-camera 

Modify config.xml to change the google maps api key.

In there you can see an hamburguer menu which is not clickable when it is opened, also if you scroll inside the menu, you will see that the map moves itself instead be on menu context

**Comment by WHarris22** [comment]
This is not an Ionic problem but something to do with how the native map plugin renders the map (because it doesn't render inside the HTML or something). The solution is to call the `map.setClickable(bool)` when the menu is open and closed. 

I had a discussion about it on the forum [here](https://forum.ionicframework.com/t/google-maps-dont-work/55637/38).

**Comment by jgw96** [comment]
Hello everyone! After reviewing this issue some more I am going to close it as i agree with @WHarris22 that this seems to be an issue with the native google maps plugin and not Ionic 2. Thanks for using Ionic!

**Comment by Germanaz0** [comment]
@jgw96 but why not to implement a generic solution for native google map component on ionic ? so nobody else have this issue ever again ?

**Comment by WHarris22** [comment]
@Germanaz0 sorry for butting in. It has a generic solution like a mentioned. You just need to call the .setClickable() method on the map object when the side menu open event fires and when the side menu close event fires

**Comment by Germanaz0** [comment]
@WHarris22 don't you know how to bind the event of menu open, from a custom controller page ?

**Comment by Germanaz0** [comment]
Nevermind, I just fixed it like this: https://bitbucket.org/Germanazo/app-camera/commits/a1a9cfe19d38ad8d57fc722e8cf40fae60b5168c
