### ISSUE TITLE
initialSlide not working in swipee

### ISSUE THREAD

**Issue by ashutosh-akss** [driftyco/ionic#7438]
initialSlide param does not work in swiper when slides are dynamically loaded from array, i can call slideTo method but it has unwanted sliding effect, any help appreciated.

```
<ion-content>

          <ion-slides #campaignDetailSlider [options]="{pager: false,initialSlide:32}" >

                  <ion-slide  *ngFor="let slide of slides">     
                              {{slide}}
                   </ion-slide>
           </ion-slides>

</ion-content>

```

Ionic : 2.0.0 beta 30
cordova : 6
node : 6

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by szerner** [comment]
I'm facing the exact same problem:

[http://plnkr.co/edit/kM9tEizkV87qdKdZ369W?p=preview](http://plnkr.co/edit/kM9tEizkV87qdKdZ369W?p=preview)

I think, if the option `initialSlide` is not supposed to work with dynamically (`<ion-slide *ngFor..>`) generated slides it should be mentioned in the docs. So please consider this as a feature request.
BTW, the `pager` option doesn't seem to work either in that specific case.

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS:
Node Version: v6.3.0
```
