### ISSUE TITLE
TabHighlight - Uncaught TypeError: Cannot read property 'btn' of null

### ISSUE THREAD

**Issue by sava999** [driftyco/ionic#7442]
#### Short description of the problem:
Error:
`Uncaught TypeError: Cannot read property 'btn' of null, http://192.168.1.12:8100/build/js/app.bundle.js, Line: 68645` is randomly happening and after this application becomes unstable.

#### What behavior are you expecting?
Error not to happen :)

**Steps to reproduce:**
1.  Well not sure, I am opening screen with tabs and almost on every second opening this happens

**Other information:**

Part of code from app.bundle.js:

```
var TabHighlight = (function () {
    function TabHighlight(_elementRef) {
        this._elementRef = _elementRef;
    }
    TabHighlight.prototype.select = function (tab) {
        var _this = this;
        dom_1.rafFrames(3, function () {
            var d = tab.btn.getDimensions();               // this is line 68645
            var ele = _this._elementRef.nativeElement;
            ele.style.transform = 'translate3d(' + d.left + 'px,0,0) scaleX(' + d.width + ')';
            if (!_this._init) {
                _this._init = true;
                dom_1.rafFrames(6, function () {
                    ele.classList.add('animate');
                });
            }
        });
    };
    TabHighlight = __decorate([
        core_1.Directive({
            selector: 'tab-highlight'
        }), 
        __metadata('design:paramtypes', [core_1.ElementRef])
    ], TabHighlight);
    return TabHighlight;
}());
exports.TabHighlight = TabHighlight;
```

**Which Ionic Version?**
2.x

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v5.12.0

------------

Does anyone have any idea why is this happening? Thank you.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by sava999** [comment]
Hi @jgw96, sorry this was issues on my side, not ionic related. Thanks

**Comment by youssmak** [comment]
@sava999 Could you tell me what was causing this error ?
how did you solve it ?

**Comment by sava999** [comment]
Huh, I can't remember it was long time ago. Sorry 😄

**Comment by youssmak** [comment]
never mind, thank you
