### ISSUE TITLE
ion-label styled wrong in ion-list in combination with ion-datetime

### ISSUE THREAD

**Issue by waybackrider** [driftyco/ionic#7443]
See http://plnkr.co/edit/ELhTfuj5Zm6P4BXWz2sr

Why is Birthdate grey and the Date black in the first line?
How to make both columns look the same?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
