### ISSUE TITLE
Nav swipe back should not vertically scroll the previous page

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#7444]
#### Short description of the problem:

When swiping back on iOS, if you move your finger vertically during the swipe then the incoming page is scrolling according to this movement. Looks very odd and isn't consistent with native UI.
#### What behavior are you expecting?

The vertical scroll position of the incoming page should be locked while the swipe is in progress.

**Steps to reproduce:**
1.  Run app on iOS device. 
2. Push a page onto the stack
3. Swipe back from the left and move your finger vertically at the same time.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
@martinjbaker Thanks for opening an issue with us! @manucorporat This sounds like something that could be solved by our new GestureController, what do you think?

**Comment by zb0t** [comment]
I resolved this issue with a work around. I use the `ionViewDidLeave` and `ionViewDidEnter` to control overflow of the page that sent you forward in the navigation stack (set it to `overflow: hidden`). If I understand your issue correctly, this is a known Webkit iOS bug with `-webkit-overflow-scrolling: touch`

**Comment by biesbjerg** [comment]
Can you share your workaround?

**Comment by tmvnk** [comment]
I also have this issue. Thought beta 11 with the new GestureController would solve this issue? Not very native indeed. Any tips for a workaround?

**Comment by martinjbaker** [comment]
As one door closes... another opens. 

beta 11 has fixed the scrolling on the incoming page but now the outgoing page is scrolling!

**Comment by tmvnk** [comment]
Hi, 

Any update or plan about this issue?

It gives the app a really unnative feeling.

Thnx!

**Comment by tmvnk** [comment]
Do you need a screencast? I can simulate it in the Conference App.
