### ISSUE TITLE
Documentation for Header is broken

### ISSUE THREAD

**Issue by simpsondigital** [driftyco/ionic#7445]
#### Currently there is nothing present.

**Steps to reproduce:**
1. Visit page above.

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#728

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this was an issue with the documentation I have moved it to the ionic-site repo. Thanks for using Ionic!

**Comment by simpsondigital** [comment]
Ah, makes sense :D Thank you, sir!
