### ISSUE TITLE
SqlStorage needs a way to do query without transaction

### ISSUE THREAD

**Issue by chris-hammons** [driftyco/ionic#7446]
#### Short description of the problem:

Currently when I run the statement `pragma user_version;` it errors out on IOS. Looking at the Cordova-sqlite-storage documentation PRAGMA statements need to be executed NOT in a transaction. 

#### What behavior are you expecting?

Need to be able to run pragma statements without an error occurrng.

```
this.storage = new Storage(SqlStorage, { name: 'my.db' });
this.storage.query("pragma user_version;").then(
            (data) => {
                if (data.res.rows.length > 0) {
                   console.log(data.res.rows.item(0).user_version);
                }
            },
            (error) => {
                console.log(error);
            }
        );
```

currently returns SQLError:
```
code: 5
message: "could not prepare statement (23 not authorized)"
```
 

**Which Ionic Version?** 2.0.0-beta.10

**Comment by Luchillo** [comment]
I had the same error since i wanted to extract schema directly from table, but i think there's no way around it, i use also websql when deploying the web version, and as far as i've read, websql doesn't allow pragma commands in webkit, so i had to resource in other ways to do so, if i craft a function to get schema i need it to work in all devices.

**Comment by danbucholtz** [comment]
We are currently refactoring our storage APIs so we'll ensure this use case is accounted for.

Thanks,
Dan

**Comment by Luchillo** [comment]
This issue can go to the trash, now SqlStorage is gone in RC.0, the new Storage doesn't fallback to WebSql and there's no way to do relational query's like joins or selects with the new API, unless dealing with the SqLite plugin directly this is on the developers duty from now on, i think i might just use [Lovefield](https://google.github.io/lovefield).

**Comment by Luchillo** [comment]
@danbucholtz Seems this use case will be accounted for the next... century? millennium? maybe in the next **Big Bang**?

**Comment by danbucholtz** [comment]
We refactored storage to use `@ionic/storage`.

This is no longer applicable. See this [issue](https://github.com/driftyco/ionic/issues/8269#issuecomment-251412768) for suggestions on how to use `sql` in apps now.

Thanks,
Dan
