### ISSUE TITLE
Exception is thrown when a modal contains a refresher (on dismiss)

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic#7451]
#### Short description of the problem:
When a modal contains a refresher and is dismissed, an exception is thrown. This only happens the first time the modal is dismissed. The app seems to function normally after that.

#### What behavior are you expecting?
No exception should be thrown.

**Steps to reproduce:**
1. Create a modal that contains a refresher
2. Present the modal
3. Dismiss the modal

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 ```
browser_adapter.ts:78 TypeError: Cannot read property 'style' of null
    at Content.setScrollElementStyle (ionic.system.js:11448)
    at Refresher._setCss (ionic.system.js:22096)
    at Refresher.close (ionic.system.js:22077)
    at e.invokeTask (zone.min.js:1)
    at Object.onInvokeTask (ng_zone_impl.ts:56)
    at e.invokeTask (zone.min.js:1)
    at e.runTask (zone.min.js:1)
    at invoke (zone.min.js:1)
```

**Which Ionic Version?**
2.0.0-beta.10

#### Plunker that shows an example of your issue
http://plnkr.co/edit/BoqRMiE1MEWIDbkNOwqX?p=preview

**Comment by jgw96** [comment]
Hello! Is this still an issue with beta.11? Thanks!

**Comment by frederikschubert** [comment]
Just tried it by updating the plunkr and it seems to work fine now. Great!
