### ISSUE TITLE
ionic2 apk doen not include the files I add

### ISSUE THREAD

**Issue by SeeSharply** [driftyco/ionic#7458]
when I use ionic run android to run the app on my phone,the files I added were not packaged in the app;
I opened the package with .zip tools,and find out the folder 'config' I add in path 'app/config' are missing!
but when I use  ionic serve ,it's correct!

ionic  version 2.0.0@beta.35
ionic framework 2.0.0-beta.10
ionic app lib version 2.0.0-beta.19

Node -v 6.2.2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Any extra files that you may need included in your app should be put in the www folder. Thanks for using Ionic!
