### ISSUE TITLE
$ionicSlideBoxDelegate doesn't work with new ion-slides

### ISSUE THREAD

**Issue by joanebrown** [driftyco/ionic#7463]
I need to change the `ion-slide-page` dynamically, so, as says in the [ion-slides docs](http://ionicframework.com/docs/api/directive/ionSlides/) I need to use `$ionicSlideBoxDelegate`.

And in the [$ionicSlideBoxDelegate docs](http://ionicframework.com/docs/api/service/$ionicSlideBoxDelegate/) they says which I need to use the `slide` method.

So I tried with:

    var secondSlide = 1;
    $ionicSlideBoxDelegate.slide(secondSlide);

But doesn't work. Nothing happens, does not throw any errors.

**There isn't any way to do that with the new and non deprecated `ion-slides`?**

---

**My environment:**

    Cordova CLI: 6.2.0
    Ionic Framework Version: 1.3.1
    Ionic CLI Version: 1.7.16
    Ionic App Lib Version: 0.7.3
    Node Version: v4.2.2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by joanebrown** [comment]
I will try to do that, but I've never used something like this...

**Comment by joanebrown** [comment]
Here is a codepen:

https://codepen.io/anon/pen/oLrYzq?editors=1010

**Comment by mtpultz** [comment]
Hi @joanebrown,

The ion-slides uses the underlying API of Swiper so you've grabbed a reference to the slider onInit (`$scope.slider`), and then looking at the [Swiper API](http://idangero.us/swiper/api/#.V5uoargrJPY) you can use `$scope.slider.slideTo(index)` or in your case `$scope.slider.slideTo(slider)`.  I updated your [plunkr](https://codepen.io/mtpultz/pen/pbkZLm?editors=1010).

Cheers

**Comment by joanebrown** [comment]
Ooops! You're right. Thank you very much. :)

**Comment by ausmond** [comment]
$ionicSlideBoxDelegate has now been deprecated.
