### ISSUE TITLE
feat: nav.popTo should work with specific pages

### ISSUE THREAD

**Issue by svrolanski** [driftyco/ionic#7468]
Feature Request

There should be a way to go back to a specific state instead of "goBack(-n)" because apps can have different flow of state at a given time, in my case:

Case 1: 

> login
> selection [back=logout]
> data input
> printing 
> extra input, by clicking finish it should go back unwinding the state stack to "selection"

Case 2:

> login 
> selection [back=logout], selected record already processed must skip "data input"
> printing 
> extra input, by clicking finish it should go back unwinding the state stack to "selection"

I can fix this in many ways, and I already did it, but I think Ionic is missing a "goBackTo(state)" (which makes much more sense to me then "goBack(-n)" since you have registered the states) method to make life easier.

**Comment by brandyscarney** [comment]
This is basically the same as https://github.com/driftyco/ionic/issues/6513. I'm not sure if this is something we're going to add but it's worth discussing some more.

**Comment by markhatchell** [comment]
It looks like this has been done, right? 

https://github.com/driftyco/ionic/blob/master/src/navigation/nav-controller-base.ts

**Comment by royipressburger** [comment]
Is this issue going somewhere? As rc2 has been released and I don't see that this feature has been implemented and it didn't move to rc3

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#100
