### ISSUE TITLE
Overriding SASS variable for a specific page

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic#7469]
#### Short description of the problem:
I want to be able to override some of the sass variable, but i want it to be overwritten only for the specific page.

I tried to override `$content-padding`. 
So i have added a class on the `ion-content` and in the scss file I have did like that
```css
.my-page {
    $content-padding: 25px;
}
```

This didn`t work... padding stayed 16px
#### What behavior are you expecting?
I expcted 25px padding.

**Steps to reproduce:**
1. create a page and add `padding` attribute on `ion-content`
2. add a class on the content 
3. add style like above

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x beta 10

Maybe I'm doing something wrong?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because of the way sass works it is actually not possible to modify a sass variable dynamically inside your app. If you would like to apply padding to your page you can just use the plain css `padding` statement. Here is an example of that 
```
.my-page {
    padding: 25px;
}

 ```
Thanks for using Ionic!

**Comment by parthgodhani** [comment]
is it possible to change 
$grid-columns: 15;
in specific single page
