### ISSUE TITLE
Side menu accessible when loading component active

### ISSUE THREAD

**Issue by samhcorney** [driftyco/ionic#7472]
#### Short description of the problem:

When using the [loading component](http://ionicframework.com/docs/v2/components/#loading) if an app has a side menu it can still be accessed by swiping the screen.
#### What behavior are you expecting?

All app functionality to be blocked while the loading component is active.

**Steps to reproduce:**
1. Download the [ionic conference app.](https://github.com/driftyco/ionic-conference-app)
2. Add a loading component to the app.
3. On a physical device or emulator, with the loading component triggered, swipe the screen from the left side inwards.

```
<button (click)="presentLoading()">Loading Component Test</button>
```

```
let loading = Loading.create({
    content: "Please wait...",
    duration: 30000
});
this.nav.present(loading);
```

**Which Ionic Version?** 2.0.0-beta.10

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed as of RC4. Because of this I am going to close this issue for now.
