### ISSUE TITLE
ion-img scaling incorrectly in iOS

### ISSUE THREAD

**Issue by djonesdev** [driftyco/ionic#7473]
#### Short description of the problem:
When displaying an image using an `img-src` the image does not scale correctly, fills the desired width but not the desired height. This was tested on an iPad Air 2.

#### What behavior are you expecting?
The `img-src` tag to scale the same way that the `img` tag scales.

**Steps to reproduce:**
1. Display image with `ion-img` in ion-col.

```html

<ion-content padding>

  <ion-row>
    <ion-col width-50 offset-25>
      <!-- img tag scales as expected -->
      <img src="http://placehold.it/800x350"/>

      <!-- ion-img tag does not scale as expected -->
      <ion-img src="http://placehold.it/800x350"></ion-img>

    </ion-col>
  </ion-row>

  <form>

      <ion-item>
        <ion-label floating>Field 1</ion-label>
        <ion-input type="text" value=""></ion-input>
      </ion-item>

      <ion-item>
        <ion-label floating>Field 2</ion-label>
        <ion-input type="text" value=""></ion-input>
      </ion-item>

      <ion-item>
        <ion-label floating>Field 3</ion-label>
        <ion-input type="password" value=""></ion-input>
      </ion-item>

    <div padding>
      <button type="submit" block primary>Button</button>
    </div>

  </form>

</ion-content>

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
[Samsung Galaxy Tab A - Screenshot](http://i.imgur.com/l1WhTnb.png)
[iPad Air 2 - Screenshot](http://i.imgur.com/Q7T8HcF.png)

This was built using for the iPad using Ionic Package.

**Which Ionic Version?** 
2.x

#### Plunker that shows an example of your issue
Setup of code, however doesn't show issues as it's specific to iOS.
http://plnkr.co/edit/gRDbSDBdh2HBOsuqqi0s?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201607151701
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 8.1
Node Version: v5.12.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time `ion-img` is only meant to be used with `virtual scroll` so for your use case you should just use the regular `img` tag. Thanks for using Ionic!

**Comment by djonesdev** [comment]
Can we get some notes on the component docs to indicate that?

**Comment by arsenslyusarchuk** [comment]
`ion-img` sets `min-height: 100%` for `img` tag inside.
To fix improper image height when using `ion-img`, try add following custom css
```
<ion-img class="expanded-image" alt="Loading" [src]="imageUrl"></ion-img>

.expanded-image img {
  min-height: initial;
}
```
