### ISSUE TITLE
Backgroundmode plugin don't works after pressing the back button or close app via side menu

### ISSUE THREAD

**Issue by Natanael1234** [driftyco/ionic#7477]
I developing an Ionic 2 app and testing on Android 6.0. 

I made a test. Triggered a temporized log event and closed the app. Nothing was shown in the terminal. After that I made the same thing, but instead to close the app I just minimized it and the log as shown in the terminal.

I need the app making some processing in background like receive silent push notifications in background.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
