### ISSUE TITLE
Ionic2 - Why the apps does not refreshes themselves automatically after x hours?

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7480]
I was wondering why ionic2 apps does not restarts themselves after x hours.

In a native app what happens usually if you don't use 'x' app for 'x' hours, and you go to open it again, either the app will restarts itself by showing a Splash screen, or it will re-fetch the data from the back-end (ex. Facebook, Instagram apps...).

My question is that, in Ionic2 app, do we need to add a piece of code to achieve the same results as the native one? 

Is this a bug, or I am missing something here?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement certain functionality I will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by Kobzol** [comment]
This is not caused by application code, but rather by the OS killing the app after it's not used for some time, so it should be the same with Ionic apps.
