### ISSUE TITLE
Ionic2 - Unable to setup SQLStorage (_ionicNative.Storage is not a constructor)

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7481]
I'm trying to setup SqlStorage in my Ionic2 app, but I was not lucky enough to do so as I am receiving the following error:

I following the documentation, but that didn't work!

> _ionicNative.Storage is not a constructor

    import {SqlStorage, Storage, StatusBar} from 'ionic-native';
    
    SaveInfo(){

    this.storage = new Storage(SqlStorage, { name: 'userInfo' });
  
    return this.http.get(this.postUrl, {search:params})
                   .subscribe(
                     data => {
    
         this.storage.set('userName', 'TestUser');
         this.storage.set('userType', 'VIP');
    
    });

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#379

**Comment by jgw96** [comment]
Hello! As this was an issue with Ionic Native and not the framework I have moved this issue to that repo. Thanks for using Ionic!
