### ISSUE TITLE
Ionic 1 - preference orientation doesn't work

### ISSUE THREAD

**Issue by joanebrown** [driftyco/ionic#7482]
Hi,

Im trying to avoid the user changes orientation screen to landscape, so I added this preference:

    <preference name="orientation" value="portrait"/>

to my `plugin.xml` and then I rebuild the platform with:

    ionic build

But in my android device, I can still change my application orientation to landscape when I rotate the device.

---

My environment:

Cordova CLI: 6.2.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
Node Version: v4.2.2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Are you putting this preference in your `config.xml`? Also what version of Android are you testing with?

**Comment by joanebrown** [comment]
Hi,

Yes, of course. I put that preference in my `config.xml`. My android version is android lollipop 5.0.

**Comment by joanebrown** [comment]
Why can this be happening? It's a bug?

**Comment by jgw96** [comment]
Hello @joanebrown. Im starting to think this is a cordova bug. What version of cordova is your project using?

**Comment by joanebrown** [comment]
How can I downgrade my cordova to 6.0.0? Thank you.

**Comment by jgw96** [comment]
Hello! You can run `npm install -g cordova@6.0.0` to install cordova 6.0.0. Then simply run `ionic platform rm android` and then `ionic platform add android`.

**Comment by joanebrown** [comment]
@jgw96 Hi! I removed my android platform and I added again and now works well :S It's weird... Why this happens some times? (I had other bugs which I repaired by remove and add again the android platform)

**Comment by jgw96** [comment]
Hello @joanebrown ! Glad to hear that fixed it. This is a cordova bug and would probably be better answered by the cordova team. If you would like you can read how to open an issue with them [here](https://cordova.apache.org/contribute/issues.html) Thanks for using Ionic!
