### ISSUE TITLE
Ionic 2 bug: getSlidingPercent() allways returns infinity

### ISSUE THREAD

**Issue by kubachour** [driftyco/ionic#7483]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I swipe any direction, result in console for getSlidingPercent() is allways -infinity or infinity, never real number. This results in not being able to handle ion-item moves when you want to swipe item and for example delete it on move by it. 

Also, Output events described at http://ionicframework.com/docs/v2/api/components/item/ItemSliding/
doesn't work because of it.

Version: Ionic 2, Beta 10

Code here:
http://codepen.io/kubachour/pen/EypEyZ</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately it looks as if your codepen is not working, would you mind making a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates the issue? That link points to a plunker template that is already set up for the latest version of Ionic 2. Thanks for using Ionic!

**Comment by kubachour** [comment]
Hello @jgw96, this is working Plunker. I Chrome console, I'm getting infinity errors, as you can see yourself. Thanks for that Plunker! 

http://plnkr.co/edit/GtMwv8?p=preview

**Comment by brandyscarney** [comment]
I confirmed that this is still an issue on latest, but I am seeing it return `0` instead of infinity.

**Comment by manucorporat** [comment]
It does not return always Infinite, that happens because you slide buttons are non-existent, ie they have width=0.

Since this is percentage value:

openAmount / button-size

```
     <ion-item-sliding *ngFor="let list of listOfNames; let i=index" (click)="continue()" (ionDrag)="ondrag($event)">
        <ion-item>
           <h1>{{list.name}} {{sureNameEntered}}</h1>
           <ion-badge *ngFor="let label of list.labels; let x=index" [ngClass]=[label.class]>{{label.name}}</ion-badge>  
        </ion-item>
    
    <ion-item-options side="left">
    </ion-item-options>
    <ion-item-options side="right">
    </ion-item-options>
</ion-item-sliding>
```

it does return Infinite and -Infinite and it is perfectly fine, anyother value would be arbitrary.

Just use a `ion-item-options` with some button inside or read `getOpenAmount()` instead of `getSlidingPercent()`.

**Comment by abhimunna** [comment]
@manucorporat By using getOpenAmount() in place of getSlidingPercent() still getting infinite, is there any other solution to get this can you please help me.
