### ISSUE TITLE
A small gray rectangle is always visible in all ionic views

### ISSUE THREAD

**Issue by bkrajendra** [driftyco/ionic#7485]
A small gray rectangle is always visible in all ionic views at top left corner below navicon.
![ionic](https://cloud.githubusercontent.com/assets/994083/17274657/f705b1f4-5709-11e6-8d79-49ac357a53ec.PNG)

![ionic1](https://cloud.githubusercontent.com/assets/994083/17274670/9940fcf8-570a-11e6-985f-023c278affaa.PNG)

This even happens for new fresh ionic start with sidemenu.
How to get rid of this issue.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic/issues/6416. Thanks for using Ionic!
