### ISSUE TITLE
z-index doesn't work as I expected inside ion-slides

### ISSUE THREAD

**Issue by joanebrown** [driftyco/ionic#7487]
Hello,

I have two sliders using `ion-slides` component and I've created a footer with two buttons (navigation buttons). Until there all right.

But... I have a form inside one of the sliders, so when I focus on a `input text` element, the `virtual keyboard`opens and moves the footer up, standing it in front of the form.

I know the `hide-on-keyboard-open` class, but this isn't inmediate (you can see how the footer is placed in front of the form for a couple of seconds), so I thought of use `z-index`

So, when the `footer` is moved upward, it is hidden under the form. But I can't get it work. 

Maybe somebody can help me with this trouble?

My intention is that the green block is hidden under the blue block when they have contact... I've created a codepen to show this problem: https://codepen.io/anon/pen/QEBxRK?editors=1111

(since you can not open a virtual keyboard on a desktop computer, you can resize the height of the page to see that the `z-index` does not work)

Regards!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by joanebrown** [comment]
Yes, you're right. Thank you :)
