### ISSUE TITLE
[bug]Beta .10 scroll get bug after switch two scrollable tabs ios

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic#7489]
#### Short description of the problem:
In beta .10. When you have two tabs which contains overflow content in `<ion content>`. 
After that only one of the tab can be scrollable. This problem only appear in IOS

Let's just see the video:

https://www.youtube.com/watch?v=oz8rnReR3sc

#### What behavior are you expecting?
All the scrollable tabs can scroll as usual.

**Steps to reproduce:**
1. Generate a new start project
2. In two tabs, each tab insert overflow content in `<ion-content>`
3. install the project in the IOS.
4. scroll **tab A** content, then switch the scrollable **tab B** and scroll it also.
5. switch back to **tab A**,  after that the **tab A** can't scroll.

**Which Ionic Version?** 1.x or 2.x
ionic2, beta .10

**Comment by chocolei** [comment]
#7154 Thanks

**Comment by kitkimwong** [comment]
@chocolei  ok, that's fine. thank you
