### ISSUE TITLE
How to use ng-upgrade module in ionic 2

### ISSUE THREAD

**Issue by yazantahhan** [driftyco/ionic#7491]
I have an angularJS1.5 code and I want to upgrade to Ionic 2 and start development based on angularJS2.0. AngularJS2.0 supports AngularJS1.5 by using the `ng-upgrade` module. So, how we can use this module In Ionic 2?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
