### ISSUE TITLE
Ionic 2 Header height problem

### ISSUE THREAD

**Issue by berkaybeyaz1** [driftyco/ionic#7492]
#### Short description of the problem
I have a header and i'm uploading my project to ionic view. Everything was so nice up here but header very close to statusbar , im wrote padding-top: 20px but it doesnt effected.

![13681794_870440249727522_1581442411_o](https://cloud.githubusercontent.com/assets/7584428/17279874/963d0666-574e-11e6-863e-67715e768ea6.jpg)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Distributor ID:     LinuxMint Description:  Linux Mint 18 Sarah 
Node Version: v4.4.7
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you using ionic view?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually a known issue with ionic view and will be fixed in the next release. Here is the tracking issue https://github.com/driftyco/ionic-view-issues/issues/164. Thanks for using Ionic!

**Comment by ajaysaini95700** [comment]
this issue is fixed or not .i am facing same issue, see image . please give me solutions 
![before](https://user-images.githubusercontent.com/18483093/28165834-1bcea5c2-67f3-11e7-92c7-80d045421a50.png)
![after](https://user-images.githubusercontent.com/18483093/28165835-1cc9f90e-67f3-11e7-8ca7-543fdf070e87.png)
