### ISSUE TITLE
bug: Page elements duplicates when tapping back button

### ISSUE THREAD

**Issue by Ham2a** [driftyco/ionic#7494]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>This issue occurs when pressing the back button on a specific page. As the page transits into the previous page, it sudden breaks and divides vertically into two pages. Thus every thing in the page, including the buttons and text all become duplicated and become displayed side by side.</span>

<span is-issue-template></span>

**Comment by Ham2a** [comment]
![smudgy](https://cloud.githubusercontent.com/assets/13129397/17285331/b2ed3514-57f4-11e6-9f62-f9e3846fc0e4.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
