### ISSUE TITLE
bug: *ngFor not working in <ion-item>/ <ion-label> combination

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#7499]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have a problem with *ngFor inside a ```<ion-item>``` tag.

Not working:
The div is not rendered.
```
<ion-item>
  <ion-label stacked>Test</ion-label>
  <div *ngFor="let r of [0,1,2,3]">Test</div>
</ion-item>
```

Working:
```
<ion-item>
  <ion-label stacked>Test</ion-label>
</ion-item>
<div *ngFor="let r of [0,1,2,3]">Test</div>
```

Is this by design? Or has it to do with ng2?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by mpaland** [comment]
Sure, here it is: http://plnkr.co/edit/b5mUiwd3qcZJQkQxachn
It's a problem of ```<ion-label>``` 
Without ```<ion-label>``` the div loop is rendered correctly inside the ion-item.
If this is wanted behavior it should to be in the API docs.

**Comment by xr0master** [comment]
@mpaland http://plnkr.co/edit/o58PXkavdLkCTDJs6qLC?p=preview
It's not bug.

**Comment by mpaland** [comment]
Thanx, @xr0master for giving advice. Found it right inside the docs [here](http://ionicframework.com/docs/v2/api/components/item/Item) (see "Content and Inputs" section).
The ```item-content``` attribute is strictly necessary:
```
<ion-item>
  <ion-label>Label (not working)</ion-label>
  <div item-content *ngFor="let x of [0,1,2,3,4]">Test</div>
</ion-item>
```

**Comment by Pkpatel04** [comment]
anyone have an idea while I am  working with ngfor and inside ion-input but the problem is that while I am entered amount in ion-input that time entered amount will be displayed in same remaining record
I have also mention link so pls visit link nd help me
https://forum.ionicframework.com/t/how-to-use-ion-input-inside-ngfor/79700
