### ISSUE TITLE
Tabbar background not getting override

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#7500]
#### Short description of the problem:
I'm trying to override `$tabbar-md-background` and `$tabbar-ios-background`, but anything happens, instead I get the `$toolbar-background` value.

If I want to modify the ion-tabbar background I have to do:

```
ion-tabbar {
  background: #f8f8f8; 
}
```

It works, but with scss variables should be cleaner.

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201607291454
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.0 Build version 8S128d
```

**Comment by ZiFFeL1992** [comment]
How can I test this kind of things with ionic running `gulp watch.e2e` ? I don't know where should I modify scss variables.

**Comment by brandyscarney** [comment]
It looks like you are using the nightly version of the framework. I made some changes to the Sass variables for tabs and I believe those changes are in that nightly. Can you take a look at this diff to see the changes: https://github.com/driftyco/ionic/commit/af01841c86ea91da6c107046e44804ae4c2c5243

`tabbar-ios-background` -> `tabs-ios-background`

We'll have this in the changelog as well. :) If you're running the `ionic` repo locally and trying to modify the sass variables for the e2e tests you can add them in the `themes` directory: https://github.com/driftyco/ionic/tree/master/src/themes. We plan on improving the documentation behind which Sass variables apply to which component as part of this issue: https://github.com/driftyco/ionic-site/issues/613

**Comment by ZiFFeL1992** [comment]
Ooops missed that commit! Thanks :D
