### ISSUE TITLE
Swipe back effect doesn't affect toolbar

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#7501]
#### Short description of the problem:
When a toolbar is inside the header on iOS, the effect that makes the navbar white while swiping back should also affect the toolbar.

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10-201607291454
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.0 Build version 8S128d
```

**Comment by jgw96** [comment]
Hello! Happy to report that this should be fixed now. Thanks for using Ionic!

**Comment by ZiFFeL1992** [comment]
Is in the latest nightly?
