### ISSUE TITLE
Ionic 2: input doesn't get scrolled into view when keyboard opens

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#7504]
#### Short description of the problem:
Focus an input on a long form (see plunkr below), when the keyboard pops up, the input is now hidden behind the keyboard and not scrolled into view as expected.

#### What behavior are you expecting?
The selected input scrolls into view.

**Which Ionic Version?** 1.x or 2.x
2.x

#### Plunker that shows an example of your issue

yep, here you go: http://plnkr.co/edit/CVsJCpQMVRJoMuF8Sd9M?p=preview

but you'd need to run this on an Android device obviously.

I was testing on a Nexus 5 and Samsung Galaxy Note 4 FYI.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Davids-MacBook-Air:AppHazard daveshirman$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by daveshirman** [comment]
Hey @jgw96, is there any update on this please? 
Thanks.

**Comment by jjmax75** [comment]
Same issue on Android 4.4.2 Acer Z500

**Additional info:**
Input moves into viewable area of screen once any key on keyboard is pressed

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us and sorry for the delay on this. We actually plan on handling this issue as part of https://github.com/driftyco/ionic/issues/6228 so I am going to close this issue for now as a duplicate. Thanks for using Ionic!

**Comment by lastamazing7** [comment]
any alternative solution for this issue.
