### ISSUE TITLE
Fab button: move fab to a separate component than button

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#7505]
This will go with issue https://github.com/driftyco/ionic/issues/7466. Fab buttons should move to their own component and group with the fab list https://github.com/driftyco/ionic/issues/5069.

- Make sure fab button has the highest z-index: https://github.com/driftyco/ionic/issues/7448

**Comment by jgw96** [comment]
related https://github.com/driftyco/ionic/issues/7624

**Comment by jgw96** [comment]
If you have a fab button with the fab-fixed attribute on it you will notice that while on Android it stays in a fixed position, on IOS it will not actually be fixed. After inspecting the element i can confirm that the button has the position: fixed style on it although it continues to move when the app is scrolled. Also, on desktop safari it works as expected, this only seems to happen on IOS.

**Comment by jgw96** [comment]
related: https://github.com/driftyco/ionic/issues/7760

**Comment by jgw96** [comment]
With the merging of the above PR this is now done. Thanks @manucorporat !
