### ISSUE TITLE
IOS using refresher content blinks 

### ISSUE THREAD

**Issue by arsenslyusarchuk** [driftyco/ionic#7507]
I'm writing an Ionic2 app and I need to use **ion-refresher** to update list of items. 
Each item in the list has thumbnail. Clicking on thumbnail creates modal with full image in it.
On IOS this click causes **screen blink** before modal will appear. This happens ONLY if using refresher component.

Here is the code example:

```html
<ion-content padding>
  <ion-refresher (ionRefresh)="refreshList()" (ionPull)="ionPull($event)" (ionStart)="ionStart($event)" pullMin="100" pullMax="180">
    <ion-refresher-content
      pullingText="Pull to refresh" refreshingText="Refreshing...">
    </ion-refresher-content>
   </ion-refresher>

  <ion-list>
    <ion-item-sliding *ngFor="let receipt of receipts" #slidingItem>
      <ion-item>
        <ion-thumbnail item-left (tap)="expandImage(receipt)">
          <img src="{{receipt.receipt100_path}}">
        </ion-thumbnail>
        <h2>{{receipt.name}}</h2>
        <p>Updated at: {{receipt.receipt_updated_at | amCalendar }}</p>
      </ion-item>
      <ion-item-options side="right">
          ...some code here
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
</ion-content>
```

Also, using sliding list gives very bad user-experience: when u try to slide item to reveal actions (in my case), refresher starts appearing, because during sliding of item `ionPull ` event triggers many times (depending of the speed of sliding). 

As  a result, right now `Refresher` is not usable. 
Please provide some help or feedback on this.

Thanks

Ionic version 2.0.0-beta.32
IOS 9.3

**Comment by ginsleepy** [comment]
Facing the same issue!
Ionic version 2.0.0-beta.32
IOS 9.3

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) or repo that demonstrates this issue? Thanks for using Ionic!

**Comment by arsenslyusarchuk** [comment]
@jgw96 Hello.

Here is the plunker http://plnkr.co/edit/fCy48ZLHeDlcGid2z2Fp?p=preview

**Comment by arsenslyusarchuk** [comment]
Hello, any updates on that?

**Comment by daymosik** [comment]
I'm having the same issue.

**Comment by arsenslyusarchuk** [comment]
This issue is fixed in beta-11

**Comment by jgw96** [comment]
Awesome, glad its fixed for you! Thanks for using Ionic!

**Comment by alexbainbridge** [comment]
I know this is OLD - but is there a chance this issue has come back recently (e.g. 2 final). I certainly have it now.... 

- image that has a click surface on it, within a list that can also be pulled down to refresh
- hard to tell after if a user is clicking or refreshing
- screen blinks
- click action happens 

Sadly this issue isn't connected to any commit that fixed it so tricky to know what was the original fix.

Will open a new issue after a wait to see if the original people on this issue see it again?

Thanks. Alex
