### ISSUE TITLE
perf: go go go

### ISSUE THREAD

**Issue by LuisEgusquiza** [driftyco/ionic#7509]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>descriopcion
po</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
![congrats](https://media.giphy.com/media/AaKelou21ukq4/giphy.gif)
