### ISSUE TITLE
Ionic2-Beta9 : Alert Dismiss problem with ionChange Event

### ISSUE THREAD

**Issue by domzinhuu** [driftyco/ionic#7510]
#### Short description of the problem:
In ion-select component i use a (ionChange) and in this event i call a alert and when i try click in ok or cancel the alert dont dismiss.

#### What behavior are you expecting?
When i click on the button the alert dismiss.

**Steps to reproduce:**
1. Create a ion-select component
2. Put a (ionChange) event on it.
3. Create the method on ts file or js file.
4. Create the Alert inside the method.
5. Trigger the event in ion-select changing item in the select
6. Try dismiss the Alert

Exemple
```
**-Method
 callAlert(event){
    let t = Alert.create({
      title:'test',
      message:'Nothing only close...',
      buttons:['ok']
    })
  this.nav.present(t);
  }

**Component

<ion-select  [(ngModel)]="lancamento.produto"placeholder="Select" (ionChange)="callAlert($event)">
          <ion-option *ngFor="let item of items" [value]="item" >{{item.text}}</ion-option>
</ion-select>

```

**Which Ionic Version?** 1.x or 2.x

2.0.0 Beta 9

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by domzinhuu** [comment]
Ok i dont know the plunker but i do a demonstrate there.

the link: http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview
