### ISSUE TITLE
Ionic 2 issue with selected value on a dynamic Radio list

### ISSUE THREAD

**Issue by shaikhspear16** [driftyco/ionic#7513]
Following is my use case,
I am creating a selection list workflow which has a set of list having list items. One list needs to be displayed at once. User can toggle to next and previous list using Next and Previous buttons. When the user clicks on any list item, next list is loaded saving the item selected in the previous list.

1. Created a new ionic project

    > ionic start listselectionapp blank --v2 --ts

2. Replace contents under home.html
```

    <ion-content>
       <ion-list radio-group>
       <ion-item *ngFor="let item of subgroup.codes">
          <ion-label>{{item.display}}</ion-label>
          <ion-radio value="{{item.display}}" [checked]="item.display == subgroup.selectedValue" 
          (click)="radioClicked(item.display)">
          </ion-radio>
        </ion-item>
      </ion-list>
      <button (click)="Prev()">prev</button>
      <button (click)="Next()">next</button>
    </ion-content>
```

3. Replace contents under home.ts
(Comments inline)
```

    import {Component} from '@angular/core';
    
    @Component({
      templateUrl: 'build/pages/home/home.html'
    })
    export class HomePage {
      group: any;
      subgroups: any[];
      subgroup: any;
    
      constructor() {
        this.group = this.getJSON().group;
        this.subgroups = this.group.subgroups;
        this.subgroup = this.group.subgroups[0];
    
      }
    
      //when any list item is selected, move to the next list after saving selection
      radioClicked(val) {
        this.subgroup.selectedValue = val;
        this.Next();
      }
    
      //move to the previous list
      Prev() {
        let id = this.subgroup.id - 1;
        this.subgroup = this.subgroups.filter(x => x.id == id)[0];
      }
    
      //move to the next list
      Next() {
        let id = this.subgroup.id + 1;
        this.subgroup = this.subgroups.filter(x => x.id == id)[0];
      }
    
      //JSON Data
      getJSON() {
        return {
          "group": {
            "display": "Group Name",
            "subgroups": [
              {
                "id": 1,
                "display": "Subgroup1",
                "selectedValue": "",
                "codes": [
                  {
                    "display": "Subgroup1-A"
                  },
                  {
                    "display": "Subgroup1-B"
                  }
                ]
              },
              {
                "id": 2,
                "display": "Subgroup2",
                "selectedValue": "",
                "codes": [
                  {
                    "display": "Subgroup2-A"
                  },
                  {
                    "display": "Subgroup2-B"
                  }
                ]
              },
              {
                "id": 3,
                "display": "Subgroup3",
                "selectedValue": "",
                "codes": [
                  {
                    "display": "Subgroup3-A"
                  },
                  {
                    "display": "Subgroup3-B"
                  }
                ]
              }
            ]
          }
        }
      }
    }
```

Steps to reproduce Issue:
1. run application (ionic serve) select a list item from first list (selection is saved and 2nd list is loaded)

2. select a list item from second list (selection is saved and 3rd list is loaded)

3. Click on `Previous` button (2nd list is loaded with selected value) Click `Previous` button again (1st list is loaded with selected value).

4. Modify selection in the first list.
ISSUE: 2nd list is loaded with selected radio button. After a few milliseconds the selected radio button is deselected on its own on the UI, although angular has the correct value in the object.

The 2nd list should hold the selection. Why does it get deselected by its own? I do not understand the behavior.

This issue only happens in case of ion-list and ion-radio.

I tried with plain HTML radio buttons and It works as expected.

Please correct me on what I am doing wrong.
(P.S: JSON object cannot be modified, please provide code/logic suggestions)

![attr selection issue](https://cloud.githubusercontent.com/assets/18510585/17316490/f981860e-5891-11e6-980c-a968e81ff9d3.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by kapilkarda** [comment]
Is their any solutions for this ?

**Comment by narayana1240** [comment]
when selected one control from my dynamic controls page other control's UI was disstrubed ionic3 and angular4
is there any way to help me out from here

**Comment by narayana1240** [comment]
Expeted: 
![image](https://user-images.githubusercontent.com/22906946/34831849-2a79da38-f70e-11e7-8e40-b5147f95eaeb.png)
 
result is now

![image](https://user-images.githubusercontent.com/22906946/34831880-468f7e9e-f70e-11e7-9f96-d9d2889c01cc.png)

**Comment by narayana1240** [comment]
after some time and tap on the page it was appered cleare but most of times it was not giving proper view ,when more controlles in page
