### ISSUE TITLE
Popover width

### ISSUE THREAD

**Issue by angelo43jjj** [driftyco/ionic#7514]
I am trying to use popOver on a page with the popOver having a few icons. Everything is working fine except that I cannot increase the width of the popover and I get a scroll bar at the bottom if I increase the width in the style sheet. 

I am using ionic2 with the following method:

```presentPopover(myEvent) {
    let popover = Popover.create(PopoverPage);
    this.nav.present(popover, {
      ev: myEvent
    });
  }```

and the template for the popover is:
(pls note that I have replaced < and > with | as otherwise it gets formatted as html page)

|ion-grid class="popover-page"|
  |ion-row|
    |ion-col|
       |img src="img/a.jpg" |
    |/ion-col|
    |ion-col | 
       |img src="img/b.jpg"  |
  |/ion-col|
   |/ion-row|
   |ion-row|
    |ion-col| 
       |img src="img/c.jpg" |
   |/ion-col|
    |ion-col | 
       |img src="img/d.jpg"  |
   |/ion-col|
  |/ion-row|
 |/ion-grid|


Appreciate any help.

thanks
Angelo

**Comment by Kobzol** [comment]
Try wrapping the template of the popover's content with <ion-content>.

**Comment by angelo43jjj** [comment]
tried that and put the class for the ion-content with width: 600px; but the popover width remains the same with horizontal scroll bar to accommodate the length.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by angelo43jjj** [comment]
Hi,
I had started a topic on this on forum.ionicframework.com but I don't see that appear. I have just created one again and hope that it will appear on this topics list.
thanksangelo
