### ISSUE TITLE
docs: steps to use nightly build

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#7515]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It would be great to have steps to use nightly build to try out latest features.

it's not like i haven't searched for it, somewhere in the issues i found 'how to' for it but didn't worked out.

Things which i have done already but didn't worked out
1- upgraded all @angular\** to rc.4 
and then  ```npm install ionic-angular@nightly``` - no luck

2- upgraded all @angular\** to rc.4.
git clone ionic master branch followed step to build & test then manually copied dist folder to project's node_modules folder - still no luck</span>

Update: followed steps from here  https://github.com/driftyco/ionic/issues/7125 
<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#739

**Comment by jgw96** [comment]
Hello, because this was an issue related to the docs and not the framework I have moved this issue to the appropiate repo. Thanks for using Ionic!
