### ISSUE TITLE
Ionic start issue

### ISSUE THREAD

**Issue by shipovalovyuriy** [driftyco/ionic#7516]
Hello guys, i am using proxy for my npm, because default settings don't work.

proxy=http://183.207.228.122:80
https-proxy=http://183.207.228.122:80
strict-ssl=false

I attempted to start my project by comand "ionic start app" and got this error:

http://i.stack.imgur.com/PHPHq.png

When i turned on my Apache server, i got this error.

http://i.stack.imgur.com/W50ua.png

So, solutions like "set proxy" don't work for me. Btw i wrote proxy in npm config but ionic still uses 127.0.0.1:80.
I tried to turn off my antivirus and so on. 0 results.

How can i start my ionic project?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1230

**Comment by jgw96** [comment]
Hello, since this was an issue related to the ionic cli and not the framework i have moved this issue to that repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#738

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1231
