### ISSUE TITLE
redirect to tab view doesnt render the template, but changes the url and headline.

### ISSUE THREAD

**Issue by jayeshjain24** [driftyco/ionic#7517]
#### Short description of the problem:
When I redirect using `ui-sref="menu.tabs.store.first"` , just the url and headline changes ,but the template is not rendered. I tried `href and $state.go()` too, but it didnt work. Any help? 

#### What behavior are you expecting?
Ideally, transition from one state to another should be smooth. Is it the ion-tab thingy thats causing the problem.
 
**Which Ionic Version?** 1.x or 2.x
1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

> Cordova CLI: 5.3.3
> Gulp version:  CLI version 3.9.0
> Gulp local:  
> Ionic Version: 1.3.1
> Ionic CLI Version: 1.7.7
> Ionic App Lib Version: 0.6.3
> OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.4 LTS 
> Node Version: v4.4.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
