### ISSUE TITLE
Does Ionic2 beta 10 supports any version of Angular2 router?

### ISSUE THREAD

**Issue by PabloFNK** [driftyco/ionic#7519]
Hi everybody,

Reading in other issues is clear to me that the version 3 of the Angular2 router is not supported in ionic, however, is the version2 (provided in the release candidate) or the deprecated router supported by Ionic2?

Thank you.

**Comment by mhartington** [comment]
Currently no version of the angular 2 router is supported in Ionic. We've disabled support for it in our internals of navController for now until we have a working version that fits all of our needs. 
Thanks.
