### ISSUE TITLE
Ionic 1x commands not executing!

### ISSUE THREAD

**Issue by codecrack24** [driftyco/ionic#7520]
**I've installed ionic a couple of times now, but still the commands are not running**

Cordova works ok but not ionic. _The ionic commands don't seem to finish execution_. I don't know what the issue is. I've tried countless solutions such as reinstalling node, cordova and ionic itself even installing different versions, resetting registry but still the same issue. Currently the ionic version is 1.7.16, node 4.4.7, npm 2.15.8
![ionic](https://cloud.githubusercontent.com/assets/11347843/17335705/8e91a69c-58e3-11e6-91e1-396d27474044.png)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1232
