### ISSUE TITLE
Delay with touches being responded to after returning from detail view to master list

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#7521]
#### Short description of the problem:
I've got a very simple tab-based app with a list of items on the first tab which push across a detail view. So I tap on the list item and the detail view pushes on from the right as expected. I tap the Back button and then tap another item in the list. But nothing happens. In fact after returning to the list view, for about the next second, taps aren't responded to at all. Then once the delay has expired, the tap is recognised and detail view slides across as expected. BTW at the moment the detail view is a super simple template with one line of text and 2 properties which are passed from the list view, so I'm sure this is on the list side of things.
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by martinjbaker** [comment]
Forgot to say that I'm seeing this issue when running on a device - iPhone 6s Plus - and not when running in Chrome.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by martinjbaker** [comment]
I've narrowed this down now. It is connected with what element is set inside <ion-list>

The tabs template, has a button which works correctly.

    <ion-list>    
      <button ion-item *ngFor="let item of items" (click)="showItemDetail(item)">
        {{item.name}}
      </button>
    </ion-list>

But if you use another element like a `<div>` or an `<ion-item>` as shown in the code examples in the [docs for Lists](http://ionicframework.com/docs/v2/components/#lists), then the delay happens.

    <ion-list>    
      <div class="list-row-wrapper" ion-item *ngFor="let item of items" (click)="showItemDetail(item)">
        {{item.name}}
      </div>
    </ion-list>

Example project (excludes "node_modules" contents so will need an npm install):
[TapResponse.zip](https://github.com/driftyco/ionic/files/400082/TapResponse.zip)

**Comment by jgw96** [comment]
Hello @martinjbaker would you mind adding the tappable attribute to your div and giving it another test?  Example 
```
<div tappable>
</div>
```

**Comment by martinjbaker** [comment]
Thanks Justin. Am pleased to confirm that fixes the problem (and shows the dimming when tapped).

**Comment by jgw96** [comment]
Awesome, glad that fixed it for you! Thanks for using Ionic!
