### ISSUE TITLE
button clear in ion-buttons does not render w/ clear background

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#7523]
```
<ion-buttons end >
  <button clear>Done</button>
</ion-buttons>
```

Putting a button in a `navbar` or `toolbar` with the clear attribute does not result in a clear button as expected.  Removing the attribute does make the background clear.  This is confusing though, because `<button clear>` is a commonly used button in Ionic.  This could lead to confusion, but it isn't high priority either.

Thanks,
Dan

**Comment by brandyscarney** [comment]
This will be fixed when `refactor/color` branch is merged and issue #7467 is closed.
