### ISSUE TITLE
bug: platform update ios breaks $ionicPlatform.ready

### ISSUE THREAD

**Issue by wfayeBerman** [driftyco/ionic#7526]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>The problem is that $ionicPlatform.ready is not firing after running ionic platform update ios; or cordova platform update ios;  Here are the steps to replicate:

- enter `ionic start myApp blank` into the terminal
- choose `n` for "create and ionic.io account"
- enter `vi myApp/www/js/app.js`
- add "angular['test_this'] = 123;" after the line "$ionicPlatform.ready(function() {"
- run `ionic build`
- open the app in an iOS device, open that devices console, and notice that angular.test_this is set to 123
- close out of everything
- run `ionic platform update ios`
- run `ionic build`
- open the app in an iOS device, open that devices console, and notice that now that angular.test_this is `undefined`

------
additional notes:
[Log] deviceready has not fired after 5 seconds. (console-via-logger.js, line 172)
[Log] Channel not fired: onCordovaInfoReady (console-via-logger.js, line 172)</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems to be a cordova bug and not an Ionic bug i will suggest that you open an issue with the cordova team. You can read [here](https://cordova.apache.org/contribute/issues.html) about how to open an issue with them. Thanks for using ionic!

**Comment by vool** [comment]
same issue here :(

**Comment by vool** [comment]
same issue here :(
@wfayeBerman did you open a issue with cordova ?

**Comment by wfayeBerman** [comment]
@vool no I didn't, this was time sensitive so we just stopped using ionic and used Cordova only
