### ISSUE TITLE
scroll-content spelled incorrectly in structure.scss

### ISSUE THREAD

**Issue by todrules** [driftyco/ionic#7528]
#### Short description of the problem:
As I was looking through my generated css file, I noticed a couple of lines had 'scroll-cotent' instead of 'scroll-content'. I traced it back to components/app/structure.scss (lines 71 & 83).

From structure.scss:
```
ion-tab scroll-cotent {
  display: none;
}

ion-tab {
  transform: translateY(-200%);
}

ion-tab.show-tab {
  transform: translateY(0);
}

ion-tab.show-tab scroll-cotent {
  display: block;
}
```
Here's a direct link:

[https://github.com/driftyco/ionic/blob/master/src/components/app/structure.scss#L71-L85](url)

Sorry, I don't have any more than that, but I figure it's a pretty straight-forward fix.

**Comment by brandyscarney** [comment]
This can actually probably be removed since the `scroll-content` in a tab is getting the same styling from:

```
ion-page scroll-content {
  // do not render the scroll-content at all until ready
  display: none;
}

ion-page.show-page {
  // show the page now that it's ready
  opacity: 1;
}

ion-page.show-page scroll-content {
  // render the content when ready
  display: block;
}
```

**Comment by brandyscarney** [comment]
This is no longer an issue, thank you!
