### ISSUE TITLE
Ionic2 beta10 How to call the Cordova plugin not in the typings list？

### ISSUE THREAD

**Issue by iraychen** [driftyco/ionic#7530]
I use the Ionic2  beta10 version development app, i can use the FileTransfer plugin to download the PDF file, **but how to call the local application to open the PDF file**?

To search for "**# cordova-plugin-file-opener2"** this plugin can call the local application to open the file, in beta6 JS version can directly use this plugin to open the file, but the default the latest beta10 is ts template, the TS to develop, need plugin will turn into TS version can be used. "Typings search file" no TS version of "cordova-plugin-file-opener2" this plugin. So how to call it in the TS?

Or how to turn "cordova-plugin-file-opener2" into a TS version of the plugin to typings?

Ionic2 Beta10 Version！
@alakra

**Comment by jtushar53** [comment]
Hi @iraychen 
install cordova typings
```typings install cordova --global --save```
then edit code 
from
```interface CordovaPlugins {}```
to
```interface CordovaPlugins {
    fileOpener2?:any;
}```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by iraychen** [comment]
@jtushar53 thank you! Using your method, I solved the problem.

**Comment by iraychen** [comment]
@jgw96 Sorry!

**Comment by liangzhanyong** [comment]
Can all of cordova plugin use this way?

**Comment by jtushar53** [comment]
hi @liangzhanyong 
it depends 

there are some other ways too. check out this http://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript
