### ISSUE TITLE
registerBackButtonAction default action

### ISSUE THREAD

**Issue by John0x** [driftyco/ionic#7532]
#### Short description of the problem:
How can I call the default action of the backButtonAction once I've registered my own action?

```
            this.platform.registerBackButtonAction(() => {
            });
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.10

**Comment by owlcode** [comment]
I have the same problem - found [https://github.com/driftyco/ionic/commit/84f37cf](url) this so I guess we should be able to do so, but I still don't know how.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
