### ISSUE TITLE
docs: Learn ionic website is not opening

### ISSUE THREAD

**Issue by kaustubhkushte** [driftyco/ionic#7536]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The following url redirects to getting started with ionic.

http://learn.ionicframework.com/formulas/loading-screen-with-interceptors/</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! That site is not being maintained at this time and is therefore set up to redirect to the Ionic docs. Thanks for using Ionic!
