### ISSUE TITLE
Slides in Ionic 2: No configuration option or attribute directive to use scroll bar

### ISSUE THREAD

**Issue by brightpixels** [driftyco/ionic#7537]
There appears to be no configuration option or attribute directive to use scroll barin slides in Ionic 2

An example of slider with scrollbar: http://idangero.us/swiper/demos/#.V6MIjfkrLIU (example 13 around 1/2 way of the page)
In the source code of that example https://github.com/nolimits4web/Swiper/blob/master/demos/13-scrollbar.html I obviously need to add this tag
`
       <div class="swiper-scrollbar"></div>`

But ionic is generating the HTML swiper expects!

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#198

**Comment by brightpixels** [comment]
Link is broken.
