### ISSUE TITLE
IOS Date Pipes JSON cyclic structure Error.

### ISSUE THREAD

**Issue by simpss** [driftyco/ionic#7538]
#### Short description of the problem:
Cannot use Date Pipes on IOS. Works as expected on android.

I know that the fix might have to go to the angular2 repo, but thought it best to start the discussion here as it only affects the IOS builds.

#### What behavior are you expecting?
When using the angular date pipe `{{date | date: 'yyyy-MM-dd'}}` I would expect the date to show up in a `yyyy-MM-dd` format.

#### What is happening?
When using the angular Date Pipe `{{date | date: 'yyyy-MM-dd'}}` on IOS There is a JSON parsing error.
`ERROR: error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.`

**Steps to reproduce:**
1. Clone the example app: https://github.com/simpss/ionic2-date-pipe
2. Build for IOS. (instructions in repository readme)
3. Deploy to an IOS device/emulator.
4. Click `Set Date`
5. Click `Show Piped Date`
6. Look at the xcode error console to see the error:
```
ERROR: error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 The code itself is simple. It's just creating a new date with `this.date = new Date();` and then tries to display it with `{{date | date: 'yyyy-MM-dd'}}`

**Which Ionic Version?** 
**2.0.0-beta.18**

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
$ ionic info
Your system information:
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually an angular / ios issue caused by angular using the intl api in their date pipe with ios and safari do not support. I would recommend opening an issue on the angular repo as we do not control the built in angular pipes. Thanks for using Ionic!

**Comment by simpss** [comment]
Just so there's a reference to a workaround here as well:

What I did to fix it for now:

Added intl as a dependency
```
npm install intl --save
```

override the copyScripts source in `gulpfile.js` to include the intl library and the locale data. You can also use a smaller locale file instead of the `complete.js`
```
//gulp.task('scripts', copyScripts); //old

gulp.task('scripts', function(){ //new
    return copyScripts({
        src: [
            'node_modules/es6-shim/es6-shim.min.js',
            'node_modules/es6-shim/es6-shim.map',
            'node_modules/zone.js/dist/zone.js',
            'node_modules/reflect-metadata/Reflect.js',
            'node_modules/reflect-metadata/Reflect.js.map',
            'node_modules/intl/dist/Intl.min.js',
            'node_modules/intl/locale-data/complete.js'
        ]
    })
});
```

And included it in `www/index.html` as well

```
  <!-- Polyfill needed for safari and IOS to support internationalization used in the date pipes -->
  <script src="build/js/Intl.min.js"></script>
  <script src="build/js/complete.js"></script>
```

**Comment by lincolnthree** [comment]
I believe in newer versions of ionic, you can simply add these scripts to your polyfills.ts file:

### Add as dependency:

`npm install intl --save`

### src/polyfills.ts
```
// This file includes polyfills needed by Angular 2 and is loaded before
// the app. You can add your own extra polyfills to this file.
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

import 'intl/dist/Intl.min.js';
import 'intl/locale-data/complete.js;
```

**Comment by lincolnthree** [comment]
I don't think this works for the latest Ionic RC.3. Do you have a new solution? Still can't get this figured out :( It would be nice if Ionic offered an extension point for Polyfills in the build process.

**Comment by B-Stewart** [comment]
Just adding this as I've been fighting with it for days now.

Fix is:

**Run:**
`npm install intl --save`

**Add to app.module.ts:**
`import 'intl';`
`import 'intl/locale-data/jsonp/en';`

**In index.html change:**
`<script src="build/polyfills.js"></script>`
to
`<script src="build/polyfills.js?features=Intl.~locale.en"></script>`

Links:
https://forum.ionicframework.com/t/angular2-date-pipe-not-working-in-ios/70059/2
http://stackoverflow.com/questions/35017800/ionic-2-using-angular-2-pipe-breaks-on-ios-cant-find-variable-intl

**Comment by yuzhenApril** [comment]
@B-Stewart 
i also do the same,but it show me the error "Invalid regular expression: unmatched parentheses".
