### ISSUE TITLE
ion-searchbar inside of ion-header doesn't change opacity in iOS page transition (Ionic2)

### ISSUE THREAD

**Issue by jvaclavik** [driftyco/ionic#7539]
`<ion-searchbar>` works really weird if it's wrapped in `<ion-header>`. `<ion-searchbar>` isn't affected by iOS transition and it hides not before previous page is loaded.

Here is video demonstrating the problem:
https://dl.dropboxusercontent.com/u/25736835/ionic-search-header-bug.mp4

#### Steps to reproduce:
Add  `<ion-searchbar>` inside of `<ion-header>`. Example:

```
<ion-header>
  <ion-navbar>
    <ion-title>Add location</ion-title>
  </ion-navbar>
  <ion-searchbar [(ngModel)]="searchString"
                 showCancelButton="true">
  </ion-searchbar>
</ion-header>

<ion-content>
  ...
</ion-content>

```

#### Version

2.0.0-beta.10

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.4 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by jvaclavik** [comment]
Here you are:
http://plnkr.co/edit/fxOb9QfLZJKpxAMOKmZh?p=preview

But it's better to test it on iOS device. I changed iOS transitions in plunker.

**Comment by jgw96** [comment]
Hello, i have reviewed this with my teammates and have a solution! At this point we do not support putting components like `ion-searchbar` inside `ion-header` although it is something we may support in the future. The correct way to place a searchbar in your app right now is to put it inside an `ion-toolbar` or to just put the searchbar inside your `ion-content`. Thanks for using Ionic!

**Comment by jvaclavik** [comment]
In case of wrap `ion-searchbar` into `ion-toolbar` you can't add back button or title there. That's not so usable.

**Comment by jgw96** [comment]
@jvaclavik No problem! Glad that fixed the issue for you!

**Comment by jgw96** [comment]
@jvaclavik Hey! Based off of your feedback we changed it where it will now be possible to put other components like `ion-searchbar` inside `ion-header` in the next release. Thanks!
