### ISSUE TITLE
question:how to remove tabs’s navigation?

### ISSUE THREAD

**Issue by SeeSharply** [driftyco/ionic#7541]
in the tabpage,when i click android hardware back button,I want to exit the application or navigate to the first tab,not just navigate to the tab I just clicked! any solution?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by SeeSharply** [comment]
thanks
