### ISSUE TITLE
Form and inputs with ion-grid not Show

### ISSUE THREAD

**Issue by SoaringTiger** [driftyco/ionic#7542]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I put an ion-gird in a form, the form and inputs not show.
After remove the ion-grid ion-row ion-col, form and inputs will show and work.
#### What behavior are you expecting?
I want the form and inputs is able to show with the ion-grid system

**Steps to reproduce:**
Code is below:

```
<ion-card>
  <form [ngFormModel]="myForm">
    <ion-item>
        <ion-gird>
             <ion-row>
                    <ion-col>
                        <ion-label fixed>Name</ion-label>                       
                        <ion-input  type="text" [(ngModel)]="model.Name" ngControl="Name"></ion-input>                       
                    </ion-col>
                    <ion-col>
                        <ion-label fixed>Age</ion-label>                       
                        <ion-input  type="text" [(ngModel)]="model.Age" ngControl="Age"></ion-input>                       
                    </ion-col>
                </ion-row>
            </ion-gird>
        </ion-item>
    </form>
</ion-card> 
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jimitndiaye** [comment]
You have a typo in ```ion-grid```.
I believe you need individual ion-items for each input. I'd refactor it as follows:
```html
<ion-card>
  <form [ngFormModel]="myForm">
    <ion-grid>
             <ion-row>
                    <ion-col>
                       <ion-item>
                        <ion-label fixed>Name</ion-label>                       
                        <ion-input  type="text" [(ngModel)]="model.Name" ngControl="Name"></ion-input>
                        </ion-item>                       
                    </ion-col>
                    <ion-col>
                      <ion-item>
                        <ion-label fixed>Age</ion-label>                       
                        <ion-input  type="text" [(ngModel)]="model.Age" ngControl="Age"></ion-input>        
                      </ion-item>               
                    </ion-col>
                </ion-row>
        </ion-grid>
    </form>
</ion-card> 
```

**Comment by SoaringTiger** [comment]
@jimitndiaye

# Worked fine! 

Thank you!
