### ISSUE TITLE
Problem with modals windows (Ionic 1.3)

### ISSUE THREAD

**Issue by miguelavaqrod** [driftyco/ionic#7544]
Hi,

When showing a modal window with several form controls, and the keyboard appears, it seems that part modal content is moved out of the modal container and dissapear. When hiding the keyboard all again is shown fine.

Any ideas?

Thanks in advance.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by miguelavaqrod** [comment]
Hi!

Doing a bit of research, I found that another people suffered the same problems.
https://github.com/driftyco/ionic/issues/365 , i.e.

I will test provided answers and inform if no luck.

Thanks!

**Comment by jgw96** [comment]
@miguelavaqrod would you mind sharing what version of Android you are currently using? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
