### ISSUE TITLE
ion-icon requiring item-* attribute to be shown

### ISSUE THREAD

**Issue by pietro909** [driftyco/ionic#7546]
#### Short description of the problem:
When adding and _ion-icon_ inside an _ion-item_ with an _ion-label_ and an _ion-input_, the _ion-icon_ requires an _item-*_ attributes otherwise doesn't show up.

#### What behavior are you expecting?
See the icon.

**Steps to reproduce:**
1. Create an _ion-item_ with an _ion-icon_, _ion-label_ and _ion-input_ as children
2. Don't add any _item-*_ attribute to _ion-icon_
3. The _ion-icon_ won't show up in the page

```
<ion-item>
    <ion-icon name="add"></ion-icon>
    <ion-label>won't show an icon</ion-label>
    <ion-input type="text"></ion-input>
</ion-item>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I need to remove the _item-left_ because of the margins. And the attribute _no-margins_ is overruled by _item-left_. 

**Which Ionic Version?** 2.0

#### Plunker that shows an example of your issue

http://plnkr.co/edit/8kLIVple4Wr41pfaOphb?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 7 SP1
Node Version: v6.3.0

**Comment by jgw96** [comment]
Hello thanks for opening an issue with us. This is actually how they are supposed to work but you can also just put the icon inside `ion-label`. I have made a plunker [here](http://plnkr.co/edit/YKbYUgGA7Nh6AgwvjRmH?p=preview) that shows how to do this. Thanks for using Ionic!
