### ISSUE TITLE
bug: [Bug] SqlStorage not opening the db in device

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7548]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>The app works ok in browser, however in mobile it doesn't open the database, when i inspect with usb the database doesn't show and sql errors about missing tables shows, which i think is because SqlStorage isn't opening the database.</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment]
Im getting this output in the chrome inspector:

![image](https://cloud.githubusercontent.com/assets/9698639/17412890/afdec854-5a44-11e6-885d-d10626db2b6a.png)

Note the database missing from the top in WebSql section, there should be at least the `sonoramobile` database mentioned being open in the console section.

**Comment by jtushar53** [comment]
on device it uses sqllite and not WebSql as mentioned in the docs, websql is used in browsers only for development purpose

**Comment by Luchillo** [comment]
Oh yeah i forgot that was the reason i made a backup to server provider, anyway i updated ionic, did `ionic state reset` and builded again and the missing tables error did go away, maybe my latest update changed something or made the opening of the database fail.

Thanks anyway, maybe that's why my build to the ios beta testing section was rejected.
