### ISSUE TITLE
any letters are not inputted to textbox on iOS

### ISSUE THREAD

**Issue by ddksaku** [driftyco/ionic#7551]
Hi, Any letters are not inputted to textbox on iOS, it works well on android though.
If I remove a line `<link rel="stylesheet" href="lib/ionic/css/" />`, then it works properly.
I am using ionic 1.3.0.
Any solutions?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
