### ISSUE TITLE
WARNING: sanitizing unsafe style value message in console on all pages with ion-img tag

### ISSUE THREAD

**Issue by jjmax75** [driftyco/ionic#7552]
#### Short description of the problem:
Console in browser view of app produces error **WARNING: sanitizing unsafe style value** when a page is loaded that uses `<ion-img>` tag.
Four errors are produced for every `<ion-img>` tag

Referencing this file and line -

> http://localhost:8100/node_modules/@angular/platform-browser/src/browser/browser_adapter.js:83

No errors produced when changed to HTML`<img>` tag

Developing in Chrome. Also checked in Firefox, same issue.
Same issue testing on device using Chrome Debugger via USB

#### What behavior are you expecting?
No warnings.
Unsure if this is affecting performance.

**Steps to reproduce:**
Created a Plunker but no error messages displaying there
Link below

```
this.image = 'https://randomuser.me/api/portraits/women/79.jpg';
....
<ion-img [src]="image"></ion-img>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?**  2.x

#### Plunker that shows an example of your issue

https://embed.plnkr.co/APEFM1/

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v4.4.7

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind giving this another test with beta.11 please? Thanks for using Ionic!

**Comment by jjmax75** [comment]
Just upgraded and tested, issue resolved in beta11 :)

**Comment by HorvathAkosPeter** [comment]
rc5, problem re-appeared...
