### ISSUE TITLE
docs: Problem including third party .js library Ionic 2

### ISSUE THREAD

**Issue by christer90** [driftyco/ionic#7553]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Having a hard time adding third party library .js file with ionic 2, I'm getting "module not found". All though I have installed it by typing "npm install progressbar.js". My home.ts has the correct import statement: "import * as ProgressBar from 'progressbar.js';", and the progressbar.js folder is under node_modules folder. I'm using Atom.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
