### ISSUE TITLE
jquery ionic issue

### ISSUE THREAD

**Issue by samxfido** [driftyco/ionic#7556]
im using simple html css3 jquery step form (http://codepen.io/atakan/details/gqbIz) in ionic side menu project all the files are loading  but when i click a button nothing happens.. someone please help me !
![capture](https://cloud.githubusercontent.com/assets/11073160/17436416/69b1a7c0-5b34-11e6-86e9-b50adc369bcf.JPG)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
