### ISSUE TITLE
[beta11] NavController regression - No rootNav?

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#7561]
Imagine that you are in a Tabbed view and tap a logout button. You want to take the user to a login page with no tabs. This is no longer possible, as far as I can see.

In versions prior to beta 11, we could use this._navController.rootNav.setRoot( ... ) to 'break out' of a tabbed view.

Plunker in a pre-beta 11 version where it is working: http://plnkr.co/edit/ma995r1o26YWG96vcyMC?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello @biesbjerg ! When trying to use this method you should see a warning in your console about it being deprecated. The new way is to use `app.getRootNav()` (which should also be in the warning). To use this method you will also have to import App like so `import { App } from ionic-angular' and inject it in your constructor like so `constructor(public app: App){}`. Thanks for using Ionic!

**Comment by biesbjerg** [comment]
Haha, you beat me to it. 

Alright! There are no warnings though. The project can't build and all I see is warnings in the console

```
TypeScript error: /Users/kim/ionic/MindlyApp/app/pages/settings/settings.page.ts(100,26): Error TS2339: Property 'rootNav' does not exist on type 'NavController'.
```

**Comment by jgw96** [comment]
Ahh, so this is one of the cool things about TypeScript! This warning is telling you that `rootNav` does not exist on the `NavController` anymore . Simply change anywhere you are using this method to the new way that i discussed in my above comment and this warning will go away and your project will build again.

**Comment by biesbjerg** [comment]
I know, just wanted to let you know that there are no warnings about rootNav being deprecated and what to use instead. Maybe there should be a note in the changelog to save you guys some tickets :-)
