### ISSUE TITLE
Is ion-textarea auto resize support in ionic 2??

### ISSUE THREAD

**Issue by lifeisfunny** [driftyco/ionic#7562]
**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014 \

Like Title , Is auto resize support in ionic2 for ion-textarea? If not , Could any one point me a way to implementing this ? 
Many thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Resizing is supported for `ion-textarea` in Ionic 2 and can be turned on by using the following css:
```
textarea {
   resize: both;
}
```
You can read more about the `resize` css property [here](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)

**Comment by lifeisfunny** [comment]
thanks yo  Great job on the ionic 2 ! i cant wait for its to launch ! Also look into the enterprise account now !

**Comment by maxt3r** [comment]
I don't think this question was understood correctly, but it comes up as a top result in Google. 

I wrote a simple directive for autoresizing ion-textarea as you input text. Here it is: https://gist.github.com/maxt3r/2485356e91a1969bdb6cf54902e61165

**Comment by royipressburger** [comment]
@maxt3r I have used your solutions and its working great on web.
But when using on a device I have a problem:
When the text fills up the screen (with the keyboard open) each keystroke causing the page to scroll up and down, have you seen this kind of issue?

**Comment by tycho01** [comment]
@jwg96: I think the question was originally intended to be about native support for automatic resize, not the regular old manual resize.

**Comment by maxt3r** [comment]
@royipressburger sorry the delay. I haven't seen these issues, but I have yet to test it properly on Android. Also, [angular2-elastic](https://www.npmjs.com/package/angular2-elastic) works perfectly well, so I might just use that.

**Comment by Sampath-Lokuge** [comment]
This is working perfectly fine on Device too.Tested  `Ionic 3.8.0`

[https://competenepal.com/elastic-text-area-component-in-ionic-framework/]()
