### ISSUE TITLE
nav.push is undefined in service api response

### ISSUE THREAD

**Issue by nirmalgoswami** [driftyco/ionic#7569]
I am trying to use change page when i got success from ajax call which is calling by one of service

```
this.api.checkFacebookUser(params, function (err, data) {
  this.nav.push(HomePage); //tried using timeout too but no luck
})
```
it is showing following error

```
browser_adapter.js:77 TypeError: Cannot read property 'push' of undefined
    at Response.<anonymous> (login.ts:40)
    at Request.<anonymous> (request.js:355)
    at Request.callListeners (sequential_executor.js:105)
    at Request.emit (sequential_executor.js:77)
    at Request.emit (request.js:615)
    at Request.transition (request.js:22)
    at AcceptorStateMachine.runTo (state_machine.js:14)
    at state_machine.js:26
    at Request.<anonymous> (request.js:38)
    at Request.<anonymous> (request.js:617)
```
i am using ionic 2 for development 

Note : It is working fine without service or ajax call

**Comment by jtushar53** [comment]
try using arrow functions

**Comment by nirmalgoswami** [comment]
@jtushar53 thanks for reply can show how can i convert my current function in arrow function i am bit new in angular 2 and ionic 2

```
this.api.checkFacebookUser(params, function (err, data) {
  this.nav.push(HomePage); //tried using timeout too but no luck
})
```

**Comment by jtushar53** [comment]
i think it should be like this, haven't tested it btw,
`var foo = (err, data) => {
this.nav.push(HomePage);
}
this.api.checkFacebookUser(params, foo)`

**Comment by jgw96** [comment]
Hello @nirmalgoswami ! Thanks for opening an issue with us. This issue is in fact due to the need to use arrow functions for `this` to bind to the correct scope. Here is an example of how to use arrow functions  
```
this.api.checkFacebookUser(params,  (err, data) => {
  this.nav.push(HomePage); //tried using timeout too but no luck
})
```
To learn more about arrow functions I would recommend checking out [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) article. Thanks for using Ionic!
