### ISSUE TITLE
Setting up new project on tutorial based

### ISSUE THREAD

**Issue by tejit2004** [driftyco/ionic#7570]
Hi guys, I have an error while setting up new tutorial based project.

![capture1](https://cloud.githubusercontent.com/assets/4394037/17455865/d90deb0c-5be2-11e6-814d-8e8377bb1967.PNG)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
