### ISSUE TITLE
bug(slider): property pager

### ISSUE THREAD

**Issue by xr0master** [driftyco/ionic#7571]
Ionic v2 beta.11
Minor bug, pager property doesn't work. It checked on browser Chrome.

**Introduction:**
1. `<ion-slides [options]="{pager: true}"> <!-- it works fine -->`
2. `<ion-slides pager="true"> <!-- it doesn't work -->`

**Which Ionic Version?** 2.x

//cc @jgw96

**Comment by brandyscarney** [comment]
This property was removed awhile ago, it should be passed in `options`. That is the only input that is added to slides: http://ionicframework.com/docs/v2/api/components/slides/Slides/#input-properties

Please see this issue: https://github.com/driftyco/ionic/issues/5508
