### ISSUE TITLE
bug(ion-item/ion-input) readonly property

### ISSUE THREAD

**Issue by xr0master** [driftyco/ionic#7573]
Ionic v2 beta.11

#### Short description of the problem:
ion-item gets the 'input-has-focus' class if readonly ion-input has been touched.

#### What behavior are you expecting?
I think, the readonly input cannot be touched.

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/VpFbVCcH4m6sjIqcLfMy?p=preview

//CC @brandyscarney

**Comment by jgw96** [comment]
Hello! The `readonly` attribute actually does allow the input to still be touched as `readonly` specifies that you can copy and paste text from a readonly input, focus it and tab to it, but you cannot change its value. Thanks for using Ionic!

**Comment by jonaszuberbuehler** [comment]
@jgw96 Is there an official way to selectively disable the label and border highlight of a readonly input when it is focused?
