### ISSUE TITLE
how to update the ionic 2 

### ISSUE THREAD

**Issue by shamrozwarraich** [driftyco/ionic#7575]
hello am confusing about updating ionic 2
 can any telll me how to update the ionic gobal and as well as local project ..as ionic jump to beta 11
am on beta 1- i want to update to beta 11 but when i trying to update am getting errror ...plz any help that why i understand it....and also tell when the cli update to beta 11 who to update the local projecy..package.json
  
![error](https://cloud.githubusercontent.com/assets/13496744/17459055/f850bcbe-5bde-11e6-956b-752721e54a73.PNG)

**Comment by Kobzol** [comment]
You have to manually write all the combinations (@angular/common, @angular/compiler etc.), the {} is just a shortcut written by the Ionic team to save keystrokes :-)

**Comment by shamrozwarraich** [comment]
hey @Kobzol  thanks for ans..
can u tell me where... in all local project ..when i open the console run the 
  npm --save ionic -angular 
the new folder create in `user/..../node_module` but i think i will created in `AppData\Roaming\npm` ...
i dont understandt it and when in same dir i run ionic info show me beta 11.. :/

**Comment by Kobzol** [comment]
Just run `npm install --save ionic-angular @angular/common @angular/compiler @angular/core @angular/http @angular/forms @angular/platform-browser @angular/platform-browser-dynamic` in the root of your Ionic project directory.

**Comment by shamrozwarraich** [comment]
thnks @Kobzol  for ans. me...
  run the cmd in root project... so i think i will run this cmd in all root project isnt..?

**Comment by shamrozwarraich** [comment]
ok thanks alot...  =D

**Comment by khocef** [comment]
i juste made the following changes to package.json 

```
"@angular/common": "2.0.0-rc.4",
"@angular/compiler": "2.0.0-rc.4",
"@angular/core": "2.0.0-rc.4",
"@angular/http": "2.0.0-rc.4",
"@angular/platform-browser": "2.0.0-rc.4",
"@angular/platform-browser-dynamic": "2.0.0-rc.4",
"ionic-angular": "2.0.0-beta.11",
```

and then `npm install`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
