### ISSUE TITLE
how to update the ionic 2 

### ISSUE THREAD

**Issue by shamrozwarraich** [driftyco/ionic#7576]
hello am confusing about updating ionic 2
 can any telll me how to update the ionic gobal and as well as local project ..as ionic jump to beta 11
am on beta 1- i want to update to beta 11 but when i trying to update am getting errror ...plz any help that why i understand it....
  
![error](https://cloud.githubusercontent.com/assets/13496744/17459055/f850bcbe-5bde-11e6-956b-752721e54a73.PNG)

**Comment by LatisVlad** [comment]
The expand doesn't work on windows. That being said, you should replace 

`npm install --save ionic-angular @angular/{common,compiler,core,http,forms,platform-browser,platform-browser-dynamic} rxjs@5.0.0-beta.6 zone.js@0.6.12`

with 

`npm install --save ionic-angular @angular/common @angular/compiler @angular/core @angular/http @angular/forms @angular/platform-browser @angular/platform-browser-dynamic rxjs@5.0.0-beta.6 zone.js@0.6.12`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
