### ISSUE TITLE
Phone Call Status bar and Personal Hotspot bar covers up iOS app navbar

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#7579]
(Ionic 2 Beta 11)

**Steps to reproduce issue:**
1. ionic start test
2. cd test
3. ionic platform add ios
4. ionic run ios --emulator
5. In the emulator, go to Hardware > Toggle In-call status bar.
6. Notice that half of the Ionic app's navbar is covered by the green phone call bar.
8. Push CMD+SHIFT+H to go to the home screen. Then launch the Contacts app.
9. Notice that the app gets shifted down by the green phone call bar so that the app's full navbar is still visible.

**Note:** I actually found out about this because I was connected to my physical device using the Personal Hotspot. The blue Personal Hotspot bar covers up half of the navbar too. But I couldn't figure out how to simulate that in the emulator for you to see the issue easily.

**Expected result:** The green phone call bar and the blue personal hotspot bar would shift the Ionic app down so you could still see the full navbar.

I also noticed it doing strange flickering adjustments and vertical squishing to my splash screen in iOS when the Personal Hotspot bar was visible. If you want me to file a separate ticket for that, just say the word.

----------------------
$ ionic info

Cordova CLI: Not installed
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually a bug in the cordova statusbar plugin but we have submitted a pull request to cordova to fix it, and have the fix applied to our fork of the plugin https://github.com/driftyco/cordova-plugin-statusbar. Thanks for using Ionic! Once the PR gets merged by the cordova team then everything will "just work" !
