### ISSUE TITLE
Allow passing parameters directly to Swiper through Slides options in Ionic 2

### ISSUE THREAD

**Issue by HendrikGrobler** [driftyco/ionic#7581]
Hi, so I am currently using beta 11 and I am trying to set the following parameters on the underlying swiper instance of the Slides component (as per: https://github.com/nolimits4web/Swiper/blob/master/demos/08-centered-auto.html):

```
{
    slidesPerView: 'auto',
    centeredSlides: true
}
```

I initially thought it would work fine, seeing as I can simply use the `getSlider` function on the Slides instance and change the `params` array on that (as per: http://idangero.us/swiper/api). However, I ran into two issues, one minor one is that the Swiper class returned by `getSlider` does not recognize the property `params` and therefore causes a compile error for TypeScript. This is not a major problem and can be worked around, but the problem comes in when trying to access the `Swiper` instance before the view has rendered (and the user sees the page). In my testing, I have logged the result of `getSlider` at each lifecycle hook and each one returns `undefined`. Which is understandable since the actual swiper instance is probably only instantiated later, however, this means I cannot set the params on it before it is instantiated and even after that there is no clean way (short of using a timeout and having the view jump as it re-renders the slider) of setting parameters on the `Swiper` instance itself, preferably before it initializes.  

You seem to be mirroring only select options / parameters from the Swiper instance on the Swiper class and also the Slides class, which means everytime someone really would like an option from Swiper to be made available as a Slides option then you will need to add it. My suggestion is to have an option like `swiperParams` that gets passed through directly to the swiper instance. Alternatively you could also maybe look at passing any options that aren't handled / consumed by the slides class to the Swiper instance.

If I am just missing something with regards to the life cycle events or how to set parameters on the Swiper instance please let me know.

Thanks for your time and hard work.

**Comment by brightpixels** [comment]
I am also having same issue you described.

**Comment by HendrikGrobler** [comment]
I would be willing to take a shot at doing this in a PR if someone can confirm what direction they want to take with this. Is adding an option for `swiperParams`  on `Slide` and passing that through to the new `Swiper` instance sufficient?

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! @HendrikGrobler does the options attribute discussed in [this](https://github.com/driftyco/ionic/issues/7598) issue fix your problem?

**Comment by HendrikGrobler** [comment]
Not as far as I can tell, no. It seems like `paginationClickable` is an undocumented option whereas this issue is asking to allow all Swiper params to be configured before initialization.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#150
