### ISSUE TITLE
 Error TS2300: Duplicate identifier 'tabsLayout'.

### ISSUE THREAD

**Issue by kelvinrolex** [driftyco/ionic#7583]
I just update from ionic v2 beta 10 to beta 11 and i have replaced all the fields stated in the document, when I try to run (ionic serve -l) I get the following error 

TypeScript error: W:/MobileApps/ElizadeApp/node_modules/ionic-angular/components/tabs/tabs.d.ts(168,13): Error TS2300: Duplicate identifier 'tabsLayout'.
TypeScript error: W:/MobileApps/ElizadeApp/node_modules/ionic-angular/components/tabs/tabs.d.ts(172,5): Error TS2300: Duplicate identifier 'tabsLayout'.
TypeScript error: W:/MobileApps/ElizadeApp/node_modules/ionic-angular/components/tabs/tabs.d.ts(176,13): Error TS2300: Duplicate identifier 'tabsPlacement'.
TypeScript error: W:/MobileApps/ElizadeApp/node_modules/ionic-angular/components/tabs/tabs.d.ts(180,5): Error TS2300: Duplicate identifier 'tabsPlacement'.

but when I checked those files listed and the lines i can't seem to find tabsLayout or tabsPlacement on that line it's pointing to. And in chrome it is saying

 Failed to load resource: the server responded with a status of 404 (Not Found) http://192.168.10.1:8100/build/js/app.bundle.js

So pls help me, my app is not loading again after updating.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! It looks as if you may have `tabsLayout` and `tabsPlacement` defined twice in your app. Would you mind checking this? Most IDE's offer a search function that should help. Thanks for using Ionic!

**Comment by kelvinrolex** [comment]
Yeah thanks I was able to resolve the issue, I opened tab.d.ts instead of tabs.d.ts, so I have resolved it  by removing one of the declaration.

**Comment by jgw96** [comment]
Awesome! Glad to hear the issue is fixed for you. Thanks for using Ionic!
