### ISSUE TITLE
android: header should be smaller in landscape mode

### ISSUE THREAD

**Issue by joekukish** [driftyco/ionic#7585]
#### Short description of the problem:

Native Android applications have several layout optimizations that kick in once the application is in "landscape" mode. One of this examples, is how headers become smaller.
#### What behavior are you expecting?

I'm expecting landscape applications that follow MD to change the height of the header in accordance to native android applications.

**Steps to reproduce:**
This behavior can be seen in every native Android application, for example: Gmail, Contacts, Dropbox, just to name a few. Simply open the application and turn your phone. Tablets also benefit from this behavior.

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by daveshirman** [comment]
I think you mean 'landscape' FYI.

**Comment by joekukish** [comment]
@daveshirman yeah, i fixed the description already.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#154
