### ISSUE TITLE
Back button optional action

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic#7590]
Is it possible to specify an optional back button action, i.e. do something only under certain circumstances and otherwise keep the default behaviour?
Right now I can define a back button action, but then it overrides the default behaviour, which is not what I want. I tried to emulate the default behaviour with keeping track of open overlays etc., but I can't do that everywhere (i.e. DatePicker opens its own overlays and I can't keep track of that - then the backbutton doesn't work correctly for the date picker).

Something like this:
```javascript
platform.registerBackButtonAction(() => {
   if (something)
   {
       doSomething();
       return true; // action handled, do nothing else
   }
   else return false; // action unhandled, execute the default behaviour
}));
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

**Comment by jgw96** [comment]
Hello! Since this is gonna be handled as part of #7611 and is already linked to that issue I am going to be closing this one for now. Thanks for using Ionic!
