### ISSUE TITLE
Ionic v2 - Beta 11 -  ion-checkbox triggering "ionChange" when the view enters. 

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#7591]
#### Short description of the problem:
As soon as an ion-checkbox is rendered, beta 11 is now triggering its ionChange function.

```
<ion-checkbox item-right [(ngModel)]="item.checked"
                (ionChange)="RemoveRecipeFromDiary(item,menuType.name);"></ion-checkbox>
```

I didn't see any comments in the changelog about this directive being changed. Any idea what happened ?

Thanks

#### What behavior are you expecting?
I am expecting during init / first time the view enters, the checkbox's "ionChange" event shouldn't be fired.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 N/A

**Which Ionic Version?** ***2.x***

#### Plunker that shows an example of your issue
PS: Plunker is at beta 10. Can you please update when you get a chance ?

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by tonyawad88** [comment]
I changed it to (click) for now with ngModel. This was probably my fault. 

```
<ion-checkbox item-right [(ngModel)]="item.checked"
                (click)="RemoveRecipeFromDiary(item,menuType.name);"></ion-checkbox>
```

**Comment by shivamsngh** [comment]
i am using ionChange event on textBox as
<ion-checkbox color="dark" [(ngModel)]="s.isTrue" (ionChange)="eval(s)"></ion-checkbox>

But when i am printing the arguments in eval() unction ,I am getting an event (event details below)
_isAsync
:
false
_isScalar
:
false
closed
:
false
hasError
:
false
isStopped
:
false
observers
:
Array[0]
length
:
0
__proto__
:
Array[0]
thrownError
:
null
__proto__
:
e
