### ISSUE TITLE
Ionic2 - navCtrl.setRoot does not work for Tab pages 

### ISSUE THREAD

**Issue by itemir** [driftyco/ionic#7593]
In Ionic 2.0.0-beta.11, If you setRoot to a different page from the tabs page initially, setRoot back to tabs page from that page brings a blank page.

One use case for this scenario is user login. Imagine you want to send the user to a login page if they are not already logged in. And after logging in, you want to send them back to the main page. 

Here are the steps to reproduce from scratch with a simplified flow.

**Step 1** Start a new project with "ionic start TestApp --ts --v2"
**Step 2** Change the constructor section of "app/pages/tabs/tabs.ts" to following: 
```
constructor(navCtrl: NavController) {
    let username = window.localStorage.getItem('username');
    if (username) {
        // this tells the tabs component which Pages
        // should be each tab's root Page
        this.tab1Root = HomePage;
        this.tab2Root = AboutPage;
        this.tab3Root = ContactPage;
    } else {
      navCtrl.setRoot(HomePage);
    }
  }
```
**Step 3** Modify "app/pages/home/home.ts" as follows:
```
export class HomePage {
  constructor(
    public navCtrl: NavController
  ) {}
  doFakeLogin() {
    window.localStorage.setItem('username','somevalue');
    this.navCtrl.setRoot(TabsPage);
  }
}
```
**Step 4** Add a button to "app/pages/home/home.html" as follows:
```
<button (click)="doFakeLogin()" primary block>Fake Login</button>
```
**Step 5** Launch the app with "ionic emulate ios" 
**Step 6** Click "Fake Login" button that appears in the emulator.
**Step 7** You will see a blank white screen. I expect to see the actual tabs page on this screen. 

Here is the ouput of "ionic info":

```
Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by itemir** [comment]
After more digging, it seems modifying the constructor as follows fixes it:

```
      // this tells the tabs component which Pages
      // should be each tab's root Page
      this.tab1Root = HomePage;
      this.tab2Root = AboutPage;
      this.tab3Root = ContactPage;    let username = window.localStorage.getItem('username');
      if (!username) {
       platform.ready().then( () => {
        navCtrl.setRoot(HomePage);
       });
      }
```

**Comment by carlosrodrigome** [comment]
I'm in the beta 11 and that works fine to solve the issue

**Comment by zefrench** [comment]
Hi, 
On ionic2 RC0 did you notice that when you send parameters to navCTRL.push:
    let id = event.currentTarget.id;
    this.navCtrl.push(OfferDetails, {
      id: id
    })
  }
On iOS 9.3 you get a black screen ?

On iOS 9.5 it works perfectly.
