### ISSUE TITLE
`CODE_OF_CONDUCT.md` not found / 404

### ISSUE THREAD

**Issue by AjkP** [driftyco/ionic#7594]
#### Short description of the problem:
The [Contributing](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md) doc has a link to the [Code of Conduct](https://github.com/driftyco/ionic/blob/master/.github/CODE_OF_CONDUCT.md) which is not found.

#### What behavior are you expecting?
A document describing the code of conduct.

**Steps to reproduce:**
1. Go to https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md
2. Click on `Code of Conduct`

**Comment by Purus** [comment]
Made a pull request : https://github.com/driftyco/ionic/pull/7603

**Comment by brandyscarney** [comment]
Fixed by PR #7603, thanks. :)
