### ISSUE TITLE
ionic.bundle.js break down into separate imports

### ISSUE THREAD

**Issue by crossz** [driftyco/ionic#7597]
#### Short description of the problem:
Instead of import ionic.bundle.js, I would rather to import angular.js and ionic.js separately. As Ionic CDN doc introduced, http://code.ionicframework.com, we should be able to achieve this.

#### What behavior are you expecting?
But no matter what version of 

**Steps to reproduce:**

1. Get the demo, which runs well.
2. Replace

```
<script src="//code.ionicframework.com/nightly/js/ionic.bundle.js"></script>
```

by using:

```
<script src="//code.ionicframework.com/1.3.1/js/ionic-angular.js"></script>

<script src="//code.ionicframework.com/1.3.1/js/ionic.js"></script>
```

This doesn't wok for me.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://stackoverflow.com/questions/38813536/ionic-bundle-js-break-down-into-separate-imports

**Which Ionic Version?** 1.x or 2.x
1.3.1

#### Plunker that shows an example of your issue

**For Ionic 1 issues** 

http://codepen.io/ionic/pen/tfAzj

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! We do not currently support loading Ionic in this manner, i would recommend you stick with loading the provided bundle. Thanks for using Ionic!
