### ISSUE TITLE
Clicks on slider paginator doesn't work.

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic#7598]
#### Short description of the problem:
Clicks on slider paginator doesn't work.

#### What behavior are you expecting?
When i click on paginator circle it should take me to that page/slide. I tried this demo and it didn't 
https://github.com/driftyco/ionic-conference-app

Also didn't find any info in documentation on enabling this. In any case shouldn't this be the default behaviour. 

**Other information:** 

I tried it on desktop chrome on mac
 

**Which Ionic Version?**  2.x

#### Plunker that shows an example of your issue
https://github.com/driftyco/ionic-conference-app

Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v4.4.7
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by brandyscarney** [comment]
You can enable clicks on the pager by passing:

```
paginationClickable: true,
```

in the options. For example:

```html
<ion-slides [options]="mySlideOptions">
```

```js
this.mySlideOptions = {
  pager: true,
  paginationClickable: true
};
```

The default is the same as the Swiper API, which is `false`: http://idangero.us/swiper/api/#.V6iv85OANBc

**Comment by jgw96** [comment]
Hello @awebdeveloper , as the above solution should fix this issue i will be closing this issue for now, but if that does not fix it for you then feel free to comment and i will happily reopen this issue. Thanks for using Ionic!

**Comment by luckylooke** [comment]
@brandyscarney Can't bind to 'options' since it isn't a known property of 'ion-slides'.
