### ISSUE TITLE
Range input prevents scrolling

### ISSUE THREAD

**Issue by riteshjagga** [driftyco/ionic#7599]
## Short description of the problem:
Range input prevents scrolling

## What behavior are you expecting?
When touch started on range input with an intention to scroll, it should scroll and not change range input's value.

**Steps to reproduce:** Please see a [demo of the issue](http://play.ionic.io/m/9cc859020ea0) here.

**Other information:** 

- Also posted this [question on stackoverflow](http://stackoverflow.com/questions/38498342/ionic-range-input-prevents-scrolling) but didn't get any response yet.
- [This is a related issue](https://github.com/driftyco/ionic/issues/3897) but it was closed by refering an [alternate library](https://github.com/rzajac/angularjs-slider) but issue is still there with that library.
 
**Which Ionic Version?** 1.x

**Here is the output of `ionic info`command:**

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Mavericks
Node Version: v0.12.7
Xcode version: Not installed

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly suggested to install/upgrade the following:     

 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************

------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.7.14
 * Latest version: 1.7.16
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update

------------------------------------

**Comment by riteshjagga** [comment]
Fixed this issue by using `pointer-events` css property as [explained here](http://stackoverflow.com/questions/38498342/ionic-range-input-prevents-scrolling/38857369#38857369).

Disabled the slider track for mouse events. Thumb of range slider still prevents scrolling but it is acceptable since majority of the scroll track area doesn't conflict with the scroll.

**Comment by jgw96** [comment]
Hello @riteshjagga ! Awesome to hear that you solved this issue. Thanks for using Ionic!

**Comment by fuggfuggfugg** [comment]
@riteshjagga @jgw96 

Is there a way to only allow click only on the knob and not by tapping the slider?

**Comment by riteshjagga** [comment]
It seems that what you need is there in the link above otherwise I didn't understand your question.

**Comment by fuggfuggfugg** [comment]
Oops, I forgot this was for Ionic while I'm using ionic 2. 

For anyone else who encounters the same issue with ionic 2, 

    .range-slider {
      pointer-events: none;
    }

    .range-knob-handle {
      pointer-events:auto;
    }
