### ISSUE TITLE
install forked code localy

### ISSUE THREAD

**Issue by msio777** [driftyco/ionic#7610]
Hi,
I'd like to contribute to the codebase und unfortunately I dont know how to install forked code localy because I want to try my changes to one of my projects. I expect that I can install globaly my version and run it with `ionic serve`.

Thanks for any help 
Best Regards
Michal

**Comment by jgw96** [comment]
Hello @msio777 ! Awesome to hear that you would like to contribute! To test your local changes in an app you can simply run `gulp package build --typecheck` and then copy the contents of `ionic/dist` into `node_modules/ionic-angular/` inside your app. Thanks for using Ionic and i cant wait to see what you contribute to the project! For more info on contributing i would recommend reading our [contributing guide](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md).
