### ISSUE TITLE
Template content inside ion-item doesn't render

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic#7612]
#### Short description of the problem:
If I put something wrapped in a `<template>` inside `<ion-item>`, the template content doesn't render. Is this by intention? If I leave out the `<template>,` it renders properly. I need the template to wrap several items in a NgIf directive.

#### What behavior are you expecting?
I expected that the template's content would be rendered properly, as it is without the presence of the template.
```html
<ion-list>
   <ion-item>
       <template>
           <button>Template</button> <!-- doesn't render -->
       </template>
       <button>No template</button> <!-- renders -->
    </ion-item>
</ion-list>
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11 (but the same behaviour was in beta.10 and possibly sooner)

#### Plunker that shows an example of your issue
http://plnkr.co/edit/T6ZE7u?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v6.2.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So as stated [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) the only valid direct parent elements for a template is <body>, <frameset>, <head> and <colgroup> without a span attribute, therefore it is not recommended to use template inside an `ion-item`. I would recommend wrapping with a div or span. Thanks for using Ionic!

**Comment by Kobzol** [comment]
Thank you for the suggestion, div works.

However I wanted to use `<template>,` which should be fine to use in `<ion-item>,` as anything with *ngIf or *ngFor inside the `<ion-item>` gets transformed into a `<template>` tag anyway.
I discovered that the <template> doesn't get rendered when it has no input attribute set, i.e.
```html
<template>  <!-- not rendered -->
   ...
</template>
<template [ngIf]="true"> <!-- rendered -->
   ...
</template>
```

I don't know if that's a Ionic, Angular or browser quirk, but it doesn't really matter, it works with the attribute and using template without an attribute doesn't really make sense (I didn¨t work for me without it, so I didn't try it with an attribute). Maybe this info will be useful to someone else.
