### ISSUE TITLE
ionic-grid apply multiple-line css not working

### ISSUE THREAD

**Issue by EricYang505** [driftyco/ionic#7613]
#### Short description of the problem:

the multiple line ellipses css do not work in ion-grid or ion-item.
#### What behavior are you expecting?

the multiple line ellipses css need be working like this example if apply on ion-grid or ion-item: https://codepen.io/martinwolf/pen/qlFdp

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://codepen.io/martinwolf/pen/qlFdp

**Which Ionic Version?** 1.x or 2.x
ionic 2 beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X Yosemite
Node Version: v6.2.1
Xcode version: Xcode 7.2 Build version 7C68

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using a grid or an item on the latest `2.1.0`. If you are still seeing this, please provide a plunker and I can reopen. Thanks! :)

Grid:
<img width="625" alt="screen shot 2017-02-24 at 3 22 23 pm" src="https://cloud.githubusercontent.com/assets/6577830/23319620/55614f80-faa5-11e6-8f5c-ba729b280a16.png">

Item:
<img width="348" alt="screen shot 2017-02-24 at 3 23 45 pm" src="https://cloud.githubusercontent.com/assets/6577830/23319619/555f42bc-faa5-11e6-885f-a1e3da4ebd12.png">
