### ISSUE TITLE
Change onDidDismiss to back to onDismiss

### ISSUE THREAD

**Issue by joekukish** [driftyco/ionic#7614]
Naming conventions should resemble HTML as closely as possible. This leads to a more natural API and understandable. ``onDidDismiss`` feels weird. Ideally ``onDismiss`` should be called after the component has been dismissed with ``onBeforeDismiss`` as a way to prevent this behavior (if required).

See discussion in the forum:
https://forum.ionicframework.com/t/clarification-over-the-ondiddismiss-naming/59783
Since the developers do not seem to be part of the forum I decided to bring the conversation to github.

**Which Ionic Version?** 1.x or 2.x
2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! We changed to `onDidDismiss` for a few reasons including to match up better with the new `onWillDismiss` event and to be more consistent with our other event names like `onDidEnter` and `onWillEnter`. While I definitely see your point, this change makes our api's more consistent across the framework.

**Comment by joekukish** [comment]
@jgw96 Thank you for your response. Based on my issue onWill enter should be onBeforeEnter. I was just trying to learn about your motivation. I did a component library (using custom elements) and API naming consistency was also a big discussion.
