### ISSUE TITLE
[Ionic 2 feature] Overlays (Alert, Popover): cssClass option with support for multiple classes

### ISSUE THREAD

**Issue by szerner** [driftyco/ionic#7618]
For a better and more flexible styling of my alert and popover overlays I would like to have the `cssClass` option supporting multiple classes. That could be in the form of concatenated class names or as an array of class names.

Now the cssClass supportes only one string token, any space character within results in runtime exceptions (InvalidCharacterError).

So `cssClass="class-1 class-2"` or `cssClass=['class-1', 'class-2']` would be ideal.

Platform: Ionic 2 beta.11

Thank you!

**Comment by brandyscarney** [comment]
You currently can pass multiple classes, like so:

```
  doAlert() {
    let alert = this.alertCtrl.create({
      title: 'Alert',
      subTitle: 'Subtitle',
      message: 'This is an alert message.',
      buttons: ['OK'],
      cssClass: 'my-alert another-class'
    });

    alert.present();
  }
```

This should probably be documented better though.

**Comment by szerner** [comment]
Thank you for looking into it. I only tried it with a Popover and 

`cssClass: "infopage mytheme"`

which produces the following exception at runtime:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./PopoverCmp class PopoverCmp_Host - inline template:0:0
ORIGINAL EXCEPTION: InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('infopage mytheme') contains HTML space characters, which are not valid in tokens.
....
```

I just checked my Alerts and they do fine with multiple classes, as you said. So this seems to be an Popover issue only.

**Comment by brandyscarney** [comment]
Thanks! I have added support for multiple classes to be passed to Popover, Action Sheet, Loading, and Toast components. It was already supported for the Alert and Picker components. I published a nightly version if you would like to test it out: 

```
npm install --save ionic-angular@2.0.0-beta.11-201608092109
```

**Comment by szerner** [comment]
Nice, thank you! Now it works as expected, and I can declutter my SCSS...

**Comment by brandyscarney** [comment]
Awesome. I updated the documentation to reflect this. It will be in the `beta 12` release. :)

**Comment by chack** [comment]
Hey,
How about modals?

**Comment by karimambarek** [comment]
how update the alert color with ionic 2 ??
