### ISSUE TITLE
A way to enable animation between tab-views[ionic 1]

### ISSUE THREAD

**Issue by eggachecat** [driftyco/ionic#7620]
Finally!!

I found a way to enable animation when state changes between tab-views. 

Actually the way is pretty clear, just add animation-css (I prefer [animate.css](https://github.com/daneden/animate.css) ) on your `<ion-view>` 

With [animate.css](https://github.com/daneden/animate.css)  you can enable animation simply like this:

`<ion-view class="animated zoomIn">`

In this way, you can accomplish more complex animation with events like `$ionicView.enter`,  `$ionicView.leave` etc : simply listen these events and attach any css-animation to `ion-view` when certain event fires.

I know this may not be a regular way but I could find another one  :-( .

You can find an example on
http://codepen.io/sunao626/pen/kXQjVw

Hope you enjoy !!

**Comment by jgw96** [comment]
Hello! Awesome animations! I would recommend posting about this in our [forum](forum.ionicframework.com). Since this is not really an issue with Ionic i will be closing this issue. Thanks for using Ionic!
