### ISSUE TITLE
Overlay problem when opening modal in ion-header

### ISSUE THREAD

**Issue by mrweiland** [driftyco/ionic#7623]
#### Short description of the problem:
I try to open modal dialog from ion-header and i can see that function is getting called and ion-backdrop is overlay screen. If i tap 2 more times on button then i can see a flash of modal that has been created. 

#### What behavior are you expecting?
Modal open.

**Steps to reproduce:**
```
<ion-header>
<ion-navbar>
<ion-buttons start>
<button (click)="navigateProfile()">
<ion-icon name="contact"></ion-icon>
</button>
</ion-buttons>
<ion-title>
Club Room
</ion-title>
<ion-buttons end>
<button>
<ion-icon name="add" (click)="createGroup()"></ion-icon>
</button>
</ion-buttons>
</ion-navbar>
</ion-header>
<ion-content class="clubroom" fullscreen>
```
Typescript file

```
createGroup() { console.log('Create group'); 
let modal2 = this.modalCtrl.create(ModalCreateGroupPage, 
{ groupId: 'this.groupId', groupName: 'this.groupName',       inputPostMessage: 's' }); 
console.log('Create group2'); 
modal2.present(); 
console.log('Create group3'); 
}
```
> Ionic-angular 2.0.0-beta.11

> Cordova CLI: You have been opted out of telemetry. To change this, run: >cordova telemetry on.
> 6.3.0
> 
> Ionic Framework Version: 2.0.0-beta.11
> Ionic CLI Version: 2.0.0-beta.36
> Ionic App Lib Version: 2.0.0-beta.19
> ios-deploy version: Not installed
> ios-sim version: 5.0.8
> OS: Mac OS X El Capitan
> Node Version: v5.12.0
> Xcode version: Xcode 7.3.1 Build version 7D1014

A user had similar problem and added in app.core.scss but this not working for me either..
```
ion-modal {
  z-index: 9999;
}
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Are you getting any errors in the console? Also did this issue also happen in beta.10?

**Comment by mrweiland** [comment]
I search for this issue for ours.... and when when i post it here i found problem...

Problem is that there were a ngModel variabel that wasnt sett properly in modal ts page where i instansiated new FormGroup... :(
