### ISSUE TITLE
Select Option style

### ISSUE THREAD

**Issue by TommyQu** [driftyco/ionic#7628]
**Short description of the problem:**
1. How to make the select have the same width with label?
2. How to wrap the content of the option? (I tried to add "item-text-wrap" class, wordbreak, wordwrap css, but not working)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com). Thanks for using Ionic!
