### ISSUE TITLE
ionSwipe in beta 11 and data binding

### ISSUE THREAD

**Issue by m5rk** [driftyco/ionic#7630]
#### Short description of the problem:

Changes made to an item via `(ionSwipe)="someFunction(item)"` are not reflected as expected.

#### What behavior are you expecting?

I expected the modifications made as a result of swiping to be reflected in the page.

**Steps to reproduce:**

1. See [this repo](https://github.com/Manifestly/ionic-binding-demo/blob/master/app/pages/home/home.html)
2. Clicking the item toggles it. Swiping it does not.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

v2 beta 11. This code worked as expected with beta 10.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X Yosemite
Node Version: v6.2.2
Xcode version: Xcode 7.2.1 Build version 7C1002

```

**Comment by jgw96** [comment]
Made a more minimal repo [here](https://github.com/jgw96/ionSwipe) with the latest nightly that shows that if you put the logic inside a `zone.run()` that it works. If the logic is not inside a zone.run it does not.

**Comment by jgw96** [comment]
Also, i can confirm that this seems to be limited too "gesture" event emitters like `ionSwipe` and `ionDrag`

**Comment by m5rk** [comment]
@jgw96 Thanks for the `zone.run(() => { ... }` workaround. That allows me to get back on track with beta 11.

**Comment by jgw96** [comment]
note to team: Seeing some really weird stuff with zone. The gif below shows everything.

![untitled-screencast](https://cloud.githubusercontent.com/assets/8823093/17597479/8ff6416c-5fbb-11e6-8ff8-1f2268f15367.gif)

 The template variable that im changing to make *ngIf hide the button with the ionSwipe event does not cause the template to update and does not appear to run in zone. But, when i do something that does run in zone, like a click event, then the template gets updated (as you can see by the button disappearing).

**Comment by manucorporat** [comment]
@jgw96 the gif is not longer working. what is this issue about? sliding item?

**Comment by jgw96** [comment]
@manucorporat hmm the gif seems to be working for me still? This is about the (ionSwipe) event on sliding lists. It does not seem to run in zone properly.

**Comment by fknop** [comment]
I had the same issue with ionSwipe. I believe the gesture event is not running in the NgZone, so it's not triggering any change detection. But as soon as you're emitting a event in the NgZone like a click. The change detection triggers and the view is updating.

**Comment by manucorporat** [comment]
@m5rk @fknop fixed!
