### ISSUE TITLE
How use livereload when index.html is not in the root of www?

### ISSUE THREAD

**Issue by chefjuanpi** [driftyco/ionic#7636]
hi I have a problem with livereload, 
Inside the www directory the estructure is similar to

```
/project 
     .....
    /www
       /libs
            ( some libs)
             ..........
       /scripts
           (some custom js files)
           ...................
      /app1
           index.html
           (here the rest of angular app)
```

the build run fine because i put this line in the config.xml file

`<content src="app1/index.html"/>`

but livereload not works, when i use

`ionic run android -l`

show the msg :

`Error: ENOENT: no such file or directory, open 'THE_PATH\www\index.html'`

i check in the platform and i find maybe the problem in the file

project\platforms\android\res\xml\config.xml

the line

`<content original-src="app1/index.html" src="http://192.168.0.145:8100" />`

I thing do are

`<content original-src="app1/index.html" src="http://192.168.0.145:8100/app1/index.html" />`

but i can't find a way to change that.

any idea how change that?  or another way to use livereload???

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by chefjuanpi** [comment]
well i thing is an insue because livereload not support when in the config.xml proyect  content point to a index file in a subdirectory.

ex: the android config file:

project\platforms\android\res\xml\config.xml

take te src, copy in original-src and put a new src, but this new src do include the old src value.

like this line:

`<content original-src="app1/index.html" src="http://192.168.0.145:8100/app1/index.html" />`

know the code not made that only remplace src
