### ISSUE TITLE
docs: How to use Ionicons in Ionic 2 application?

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#7640]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please provide a documentation to use Ionicons in Ionic 2 applications.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#753

**Comment by jgw96** [comment]
Hello! Since this was a documentation issue and not an issue with the framework i have moved this to the appropriate repo. Thanks for using ionic!
