### ISSUE TITLE
Epub3 reader for ionic

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [driftyco/ionic#7641]
In my ionic application i integrate the epub3 file so i need to read the epub3 file in my application. Is cordova provide any plugins for read epub3 file.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com). Thanks for using Ionic!
