### ISSUE TITLE
bug: <ion-select> ngModel issue inside Angular form

### ISSUE THREAD

**Issue by dumoulinj** [driftyco/ionic#7643]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0-beta.11</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I load a page containing an Angular form ("@angular/forms": "0.2.0"). In this form, I have a `<ion-select>` component. If I use the ngModel, the page is simply not shown, without any errors in the console (Chrome). Without the ngModel, or if not inside the form, it works as expected.

Before updating to "ionic-angular": "2.0.0-beta.11" (meaning also before migrating to "@angular/forms": "0.2.0" - see https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub) it was working.

Here is the code with a basic `<ion-select>`:

```
<form [formGroup]="form">
    <ion-item-group>
        <ion-list>
            <ion-item>
                <ion-label>Gaming</ion-label>
                <ion-select [(ngModel)]="gaming">
                    <ion-option value="nes">NES</ion-option>
                    <ion-option value="n64">Nintendo64</ion-option>
                </ion-select>
            </ion-item>
        </ion-list>
    </ion-item-group>
</form>
```

Result: The page is not shown, without any error.

If I remove [(ngModel)]="gaming" it works.
If I keep the ngModel and put the ion-select outside the form it works.

Hope you have all the informations to reproduce the error...</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind creating a minimal plunker that i can use to reproduce this issue? Thanks for using Ionic!

**Comment by dumoulinj** [comment]
@jgw96 I tried for a while to setup a plunker with ionic beta 11, but without success, and I can't find one existing...

If you could provide me with a basic plunker (with ionic beta 11 and angular rc4 + angular/forms 0.2.0) I can definitely copy-paste my code!

**Comment by jgw96** [comment]
Hello! Sorry, i should have said repo instead of plunker. Unfortunately we do not have a working plunker for Ionic 2 beta.11 because of an issue with npmcdn and angular forms.

**Comment by dumoulinj** [comment]
Hi,

Problem solved!

I don't know why but when loading a modal, if there is something wrong, the modal is simply not shown, without any errors shown in the console. Is it possible to change this behavior?

While preparing a repo for you, I was finally getting the error:

> _ORIGINAL EXCEPTION: If ngModel is used within a form tag, either the name attribute must be set or the form control must be defined as 'standalone' in ngModelOptions._

By providing a name, it was not working for me, but with the standalone option yes: ```[ngModelOptions]="{standalone: true}"```

So not a ionic bug!

Best regards
