### ISSUE TITLE
Ionic Beta.11 update command is broken because of Angular RC5 release

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#7647]
#### Short description of the problem:

Angular RC5 just has been released, this cause the original install command to fail. I have added the required (RC4) version to the command.

#### What behavior are you expecting?

Install succeed without modifying the command. 

**Steps to reproduce:**
1. Open changelog and copy the Beta.11 install instructions
2. Try to update an ionic 2 project to Beta.11 with that command

**Which Ionic Version?** 1.x or 2.x

Ionic 2

#### Plunker that shows an example of your issue

N/A

**Comment by jgw96** [comment]
Thanks!
