### ISSUE TITLE
Add ability to disable scroll on ion-content

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic#7648]
I would love to see an API that looks like this on `ion-content` and/or `scroll-view`?

```
<ion-content [scrollEnabled]="scrollEnabled">
...
</ion-content>
```

By doing it through data binding, it will be very easy to manage the state.

Thanks,
Dan

**Comment by dgroh** [comment]
I could suggest you to write your own directive as workaround.

In my case I created a class: `.no-scroll`  with `overflow: hidden` and added it two my content like this:

`this.content.addCssClass("no-scroll");`

where `content` is `@Input("content") content: Content;`

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#199
