### ISSUE TITLE
Controls Stop Responding After Resetting Root

### ISSUE THREAD

**Issue by djonesdev** [driftyco/ionic#7652]
#### Short description of the problem:
After calling `setRoot` and `popToRoot` to reset the page stack, controls on the new root page stop responding.

#### What behavior are you expecting?
Controls behave as intended.

**Steps to reproduce:**
1. Open sample application.
2. ~~Enter non-empty credentials.~~
3. Click Login
4. Notice how controls stop responding on the Home page, however the sidebar seems to still work somewhat.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://github.com/djonesdev/ionicnavbug

Important spots:
https://github.com/djonesdev/ionicnavbug/blob/master/app/pages/login/login.ts#L17
https://github.com/djonesdev/ionicnavbug/blob/master/app/pages/home/home.ts#L18

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue
http://plnkr.co/edit/HYAXAv?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
$ ionic info

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 8.1
Node Version: v5.12.0

**Comment by djonesdev** [comment]
Also tried the resolution from #7657 with no change in behavior.

**Comment by djonesdev** [comment]
Updated the example code to simplify and reduce possible error spots. Notice how the inputs work correctly upon load, but after clicking the Login button the inputs/button on the new root page (Home) no longer work. The menu still works, at least until selecting the Home link after which point it no longer works.

**Comment by djonesdev** [comment]
Added plunker of issue.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I have made a repo [here](https://github.com/jgw96/setRootExample) that shows the correct way to do this. By simply calling `setRoot()` on `NavController` it will reset your root to whatever the new page is and therefore not allow the user to navigate back to that page unless you allow them too. Thanks for using Ionic!

**Comment by djonesdev** [comment]
Thanks! Wouldn't the `popToRoot()` behavior still be a bug either way? That is to say, calling it from the root page (whether correct or not) shouldn't cause the entire app to lock up, it should simply do nothing?

**Comment by zygimantas** [comment]
I have noticed the same issue by using setRoot(B) from page A constructor/ionViewLoaded(). The UI locks up and multiple ion-page components are added to DOM.

**Comment by zygimantas** [comment]
Related issue: https://github.com/driftyco/ionic/issues/7409

**Comment by zygimantas** [comment]
Related issue: https://github.com/driftyco/ionic/issues/5883

**Comment by zygimantas** [comment]
Workaround is to use:

    this.platform.ready().then(() => {
        this.navController.setRoot(Page);
    });
