### ISSUE TITLE
Ionic 2 build skipping

### ISSUE THREAD

**Issue by shamrozwarraich** [driftyco/ionic#7662]
updating to beta 11 and also update the cordova 6.3.0 and also update local project cordova 5.2.1....problem is change the app mean changing the component clases when serving the app the change reflect and appear  but when check on device changes not produce the old beta 10 build produce... any help...
using
`ionic platform add android@5.2.1`
  `ionic build android`
  `ionic run android`

**Comment by Kobzol** [comment]
Try uninstalling the app from the device and delete the platforms/android/build/outputs/apk folder before running the build.

**Comment by shamrozwarraich** [comment]
thnks fixed ☺

**Comment by jgw96** [comment]
Thanks for helping @Kobzol !

**Comment by adnanu** [comment]
https://ibb.co/cckoKb

**Comment by jameeshpm** [comment]
Its annoying, Unable to run app on emulator or device.
![image](https://user-images.githubusercontent.com/16596536/37095342-88ddf1d4-220d-11e8-8372-5fecce7a0e7e.png)
Can anyone help with this please.

I tried the following steps
ionic cordova platform remove android
ionic cordova platform add android
ionic cordova build android
ionic cordova run android
