### ISSUE TITLE
how to add transitions from a view into tabs view

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#7663]
I have a list page and a tabs page, when click item in list page,it will go tabs page. however, there is no transitions animate. how to add the view transitions. I'd appreciate it if you would reply.

**Comment by T-Specht** [comment]
Assuming you change from the List Page to the Tabs Page with something like `this.navCtrl.setRoot(TabsPage)`, you can activate animations by setting the options parameter like this: `this.navCtrl.setRoot(TabsPage, {}, {animate: true});`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
