### ISSUE TITLE
docs: The splash.psd does not work at its current size

### ISSUE THREAD

**Issue by flashquartermaster** [driftyco/ionic#7666]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The Photoshop Splash Screen Template that is downloadable from http://ionicframework.com/docs/cli/icon-splashscreen.html does not generate anything when 'ionic resources --splash' is run until it is resized from 2732 x 2732 to 2208 x 2008. Would it be a good idea to have it at that size to begin with?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#755

**Comment by jgw96** [comment]
Hello! Thanks for opening am issue with us! Since this is an issue with the docs and not the framework I have moved this to the appropriate repo. Thanks for using Ionic!
