### ISSUE TITLE
Where to add images in Ionic 2 application?If i am placing it directly inside www folder,on restarting server gulp is doing clean and removing that folder.Also i want to keep some fonts.

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#7667]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! The www folder does not get overwritten when the app is rebuilt, only the www/build folder does. Anything you put in the www folder will be good to go! Thanks for using ionic!

**Comment by rhuldip** [comment]
Then Is it the best way to keep all our assets inside www folder?Since we are using app folder for all our development.

**Comment by jgw96** [comment]
@rhuldip Thats correct! Putting assets in the app folder is not recommended as it will make it very hard to link to them.
