### ISSUE TITLE
Ionic package failure

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic#7670]
Hi,
I can build locally but on the server I get this error for IOS release:
"Error: Cannot find module 'babel-runtime/core-js/object/keys'"

I had the same issue on my local android build, it was fixed after running:
"npm install babel-runtime@5.3.0 --save"

How can I have that package installed on the ionic package server as well?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#153
