### ISSUE TITLE
Can't click back button on ios when segment is in navbar

### ISSUE THREAD

**Issue by comfortme** [driftyco/ionic#7671]
#### Short description of the problem:

After pushing a new page, back button can not be clicked on ios if ion-segment is placed in navbar.
#### What behavior are you expecting?

back button should be clickable.

**Steps to reproduce:**
1. create new project
2. create two pages(page 1 and page 2)
3. place a ion-segment with two buttons on page 2 in navbar
4. navigate to page 2 from page 1 with push.
5. can't go back again.

```
<ion-header>
   <ion-navbar>
      <ion-segment [(ngModel)]="segment">
         <ion-segment-button value="foo">
           button1
         </ion-segment-button>
         <ion-segment-button value="bar">
           button2
         </ion-segment-button>
      </ion-segment>
   </ion-navbar>
</ion-header>
```

**Which Ionic Version?** 1.x or 2.x
ionic 2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 8.1
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind putting your segments in `ion-header` instead and see if that fixes the issue for you? 

```
  <ion-header>
    <ion-navbar>
    </ion-navbar>
    <!--segment here-->
  </ion-header>
```

**Comment by comfortme** [comment]
hi!
yes i tried that it does but segment and navbar are not in the same line anymore,
result is the same with segment in the toolbar shown below and css is messed up
```
<ion-header>
    <ion-navbar>
    </ion-navbar>
    <ion-toolbar>
    <!--segment here-->
    </ion-toolbar>
  </ion-header>
```
