### ISSUE TITLE
Error when "Alert" after "ActionSheet"

### ISSUE THREAD

**Issue by SrMouraSilva** [driftyco/ionic#7673]
#### Short description of the problem:

If called a ActionSheet and call Alert, it's impossible close the alert clicking in a button :disappointed: 

#### What behavior are you expecting?

If called a ActionSheet and call Alert, it's possible close the alert clicking in a button

#### Steps to reproduce:

1. Present a ActionSheet
2. When selected a item, present a Alert
3. Try click a button

#### Other information:

Maybe like https://github.com/driftyco/ionic/issues/7672 

#### Version

Ionic 2 version. This defect has been dettected in beta-10 and beta-11 (beta-7 has ok)

#### Plunker that shows an example of your issue

**For Ionic 2** - (is beta-10?) http://plnkr.co/edit/A9IgINTaACVkLRpnDtjs?p=preview

#### Ionic info

```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.1
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I have made a plunker [here](http://plnkr.co/edit/8e7af8UzpPgQBZHXhOzT?p=preview) that shows the correct way to do this. You can read more about our async navigation in Ionic 2 [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/#nav-transition-promises) in our docs. Thanks for using Ionic!

**Comment by SrMouraSilva** [comment]
I'm sorry for my misinformation.
Congratulations agility of your support

Good Olympics ^^

**Comment by realappie** [comment]
@jgw96 While this issue is working fine on ionic 2 RC1

If you call an alert using an ActionSheet button, it will cause the actionSheet **not** to animate away.

![reproduction gif](https://i.gyazo.com/bdf5272f9729b5c11a1e861876d00735.gif)
