### ISSUE TITLE
Navbar hides when triggering  this.nav.setRoot(HomePage);

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7674]
#### Short description of the problem:

I wanted to reload the page once I click on a button.
For that I am trying to run a `this.nav.setRoot(HomePage);` inside `HomePage` itself.
It works; however, it hides the navBar!

**HomePage.js**

```
    @Component({
      template: `
       <button ion-item (click)="refreshPage()">Click to refresh</button>`
     })

    export class Reload{
     static get parameters(){
      return [[Http]];
     }
    constructor(http) {
    this.http=http;
    }

    refreshPage(){
      this.nav.setRoot(HomePage);
    }
 
    }

```

**Which Ionic Version?** 
 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello @HamzaLJ ! Thanks for opening an issue with us! What is your use case for wanting to reload the page? With Angular 2/Ionic 2 the ui should always update depending on your model, this is what all the template binding goodness is for so their should be no need to reload the page.

**Comment by HamzaLJ** [comment]
@jgw96 well, the thing is that I have a popover inside the navBar, when the user clicks on that popover it shows the available cities. What I want is that when I click on a particular city name, it'll refreshes the view (new fetch queries) to show results on the view according to the selected city name.
How can I do that? Or even what is the best way to do it?

**Comment by TomasKatz** [comment]
Why am I getting these mails?

**Comment by jgw96** [comment]
@HamzaLJ So you should be using a provider to pass data between your popover component and your main component. I would recommend checking out [the angular 2 docs](https://angular.io/docs/ts/latest/tutorial/toh-pt4.html) on services to learn how to do this. 😃  Since this is not really an Ionic bug but just an implementation issue i will be closing this issue for now. Thanks for using Ionic!
