### ISSUE TITLE
feat: Translate default texts via config language

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7677]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I offer to create a json file with all the default texts in every language, "OK" in alert will be "אישור" in hebrew only by declaring language: "hebrew" in config object.
It's really good feature, maybe there is a way to fix it manually, but why should i make ir manually? I think it's great feature.
Please accept it, the community will fill all the languages texts easily.</span>

<span is-issue-template></span>

**Comment by MatanYed** [comment]
Delete the alert label please

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since we are going to address localization in [this](https://github.com/driftyco/ionic/issues/7691) issue I will be closing this issue as a duplicate. Thanks for using Ionic!
