### ISSUE TITLE
Ionic push unregister Error

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic#7678]
Hi,
In my app.js, inside of $ionicPlatform.ready, I have:
```
if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
		
	// Ionic.io push notifications
	var push = new Ionic.Push({
		"debug": true,
		"onNotification": function(notification) {
			var payload = notification.payload;
			console.log("onNotification: ", notification, payload);
		},
		"onRegister": function(data) {
			console.log("onRegister: ", data.token);
		}
	});
			
	var callback = function(token) {
	  console.log('Registered token:', token.token);
	  push.saveToken(token, {'ignore_user': true});		  
	  $rootScope.notificationsToken = token.token;
	}
	push.register(callback); // End of Ionic.io notifications
	$window.localStorage.setItem("push", push);
}
```

When a user clicks the logout button, I execute this code:

```
if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
	console.log("logout: Unregister Ionic");
	var push = $window.localStorage.getItem("push");
	push.unregister();
	$window.localStorage.removeItem("push");
	$window.localStorage.removeItem("refer_link");
}
```

That gives me this error:
ionic.bundle.min.js:139 TypeError: push.unregister is not a function

Why isn't not working? I don't see good example on your documentation...
Should I use object $ionicPush somewhere instead?

FYI, I don't user the Ionic users, just need to push/token

Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#155

**Comment by jgw96** [comment]
Hello! Because this issue was more relate to our backend services instead of the framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
