### ISSUE TITLE
bug: Back button now shown on Android

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#7680]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0 beta11</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When paged is pushed in as following then it does not show back button:
`this._navController.pop().then(() => this._navController.push(Page))`;</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind sharing a little bit more of your code? Are you pushing a popping and pushing a page from an overlay component such as an alert, actionsheet, or popover? Thanks for using Ionic!

**Comment by ThorConzales** [comment]
Hi, 

Sorry for the delay. The page is standard page and not a modal of any kind. I did change the code to following:
this._navController.push(Page).then(() => {
            this._navController.remove(this._navController.length() - 2, 1, {
                animate: false
            });
        });

Which works but difference is that it first pushes in the new page and then removes the page underneath.
