### ISSUE TITLE
bug: ion-footer not styling correctly

### ISSUE THREAD

**Issue by delley123** [driftyco/ionic#7684]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I have created a forum topic about this, with code and screenshots:
https://forum.ionicframework.com/t/ion-footer-not-styling-correctly

When using the ion-footer markup, the footer doesnt get styled correctly.

The work-around i found was to wrap the footer contents inside a ion-toolbar markup. But that kinda defeats the purpose of the ion-footer mark up.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
The sites docs were just updated

**Comment by delley123** [comment]
Snappy fix - cheers :)
