### ISSUE TITLE
Nav swipe back is transitioning the navbar to white

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic#7685]
#### Short description of the problem:
My app has black header which I do by adding `dark` to the navbar and overriding the hex value in app.variables.scss.

All is good until I push from list page to detail page and swipe from the left to go back. The navbar transitions to white as the swipe back transition happens.

#### What behavior are you expecting?
The nav bar should not change colour at all during the swipe back.

**Steps to reproduce:**
1. Use an example project that has list/detail pages.
2. Set the navbar to be `dark`
3. navigate to the detail page and then swipe from the left to go back to the list page

**Which Ionic Version?** 1.x or 2.x
2.x beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by martinjbaker** [comment]
This also happens when the detail page is being pushed on, so not something specific to swiping.

**Comment by jgw96** [comment]
Hello @martinjbaker ! I can happily report that this should be fixed and the fix will be in the beta.12 release. Thanks for using Ionic!

**Comment by TomasKatz** [comment]
Remove me from this mail conversation please.

**Comment by jgw96** [comment]
@TomasKatz This is actually a problem with your github notifications settings and not anything that we have control over. Sorry!
