### ISSUE TITLE
feat: Prevent leaving page

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7688]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I need option to prevent leaving some page, in ionViewWillLeave function need to put "event" or something and then preventDefault...</span>

<span is-issue-template></span>

**Comment by alexbainbridge** [comment]
See https://github.com/driftyco/ionic/issues/6623

**Comment by jgw96** [comment]
Hello @MatanYed ! I am going to be closing this as a duplicate of the issue @alexbainbridge linked to above. Thanks for using ionic! Oh and thanks @alexbainbridge !
