### ISSUE TITLE
Allow using Objects as value of AlertInputOptions

### ISSUE THREAD

**Issue by alex-pl** [driftyco/ionic#7690]
#### Short description of the problem:

The value property of AlertInputOptions allows strings only.
#### What behavior are you expecting?

It would be great, if we could use Objects also.

**Steps to reproduce:**
1. Create a new Alert in an TypeScript project.
2. Call `addInput()` to create a new input option.
3. Set the `value:` property of this input option to any `Object`.

``` TypeScript
let alert = this.alertController.create();

alert.addInput({
    type: 'radio',
    label: 'Sample Person',
    // this works with ES6 but isn't possible with TypeScript
    value: {
        sessionId: 5,
        personId: 838
    }
});
```

**Other information:**
I was able to do this before switching from ES6 to TypeScript without having any problems.

``` TypeScript
export interface AlertInputOptions {
    type?: string;
    name?: string;
    placeholder?: string;
    value?: string; // the problem, could be solved by using string|{} or any
    label?: string;
    checked?: boolean;
    disabled?: boolean;
    id?: string;
}
```

**Which Ionic Version?** 2.0.0-beta.11

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#153
