### ISSUE TITLE
label from Select component produces error WARNING: sanitizing HTML stripped some content when it includes special characters

### ISSUE THREAD

**Issue by EmmaNaty** [driftyco/ionic#7694]
When I try to use the Select Component, from Ionic 2 beta 11, with a variable label and the bound  string includes special characters like ´ or ñ I get a warning:

**WARNING: sanitizing HTML stripped some content** (see http://g.co/ng/security#xss).

The label renders as expected despite the warning which triggers every time I clicked on the select component.

I´m trying the following code:

```
<ion-item>
  <ion-label>{{label_}}</ion-label>
  <ion-select [(ngModel)]="selected_value" >
    <ion-option *ngFor="let a of options_" value="{{a.id}}" >
          {{a.label}}
    </ion-option>
  </ion-select>
</ion-item>
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually something that is handled by Angular 2 itself and is not handled by Ionic. I would recommend opening an issue on the [angular](https://github.com/angular/angular) repo. Thanks for using Ionic!
