### ISSUE TITLE
Can't emulate on iOS after adding Google Maps

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7701]
I can't emulate my app anymore after I added Google Maps, it was installed with no errors; however, when I run a emulate command I receive the below error:

1 warning and 1 error generated.

** BUILD FAILED **

The following build commands failed:

	CompileC build/Flavy.build/Debug-iphonesimulator/Flavy.build/Objects-normal/i386/GroundOverlay.o Flavy/Plugins/plugin.google.maps/GroundOverlay.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Michael/Documents/new/flavy/platforms/ios/cordova/build-debug.xcconfig,-project,Flavy.xcodeproj,ARCHS=i386,-target,Flavy,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Michael/Documents/new/flavy/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Michael/Documents/new/flavy/platforms/ios/build/sharedpch

Caught exception:
 undefined

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this seems to be an issue with the google maps cordova plugin and not Ionic itself i would recommend opening an issue with them [here](https://github.com/mapsplugin/cordova-plugin-googlemaps). Thanks for using Ionic!
