### ISSUE TITLE
Ionic 2 with RxJS operators

### ISSUE THREAD

**Issue by thedmi** [driftyco/ionic#7702]
I'm trying to use RxJS in an Ionic 2 project, but for some reason the `Observable` objects lack the functions at runtime. I'm suspecting a conflict with `rx-lite` and wanted to post the issue here to rule out that this is a general problem of Ionic (I'm not 100% sure where the problem actually is).

### Steps to reproduce

1. Create ionic 2 project from default template: `ionic start ExampleProject --v2 --ts`
1. Import `Subject` at the top of app.ts: `import {Subject} from 'rxjs/Subject';`
1. Create an observable and use the `delay` operator: `var delayed = new Subject().asObservable().delay(10);`

Here is the plunk:  http://plnkr.co/edit/78DAC8vkRwGJf6M8osCy?p=preview

### Error description

This compiles, but throws the following error at runtime:

    Error: Uncaught (in promise): TypeError: (intermediate value).asObservable(...).delay is not a function

According to the RxJS docs I'm using `delay` correctly, see e.g. the [RxJS migration docs](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#operator-splits). I also verified that I'm using it correctly by looking at `node_modules/rxjs/operator/delay.d.ts`.

The same behavior occurs with the `distinctUntilChanged()` operator, probably others as well.

### Output of `ionic info`

    Your system information:

    Cordova CLI: 6.2.0
    Gulp version:  CLI version 1.2.1
    Gulp local:   Local version 3.9.1
    Ionic Framework Version: 2.0.0-beta.11
    Ionic CLI Version: 2.0.0-beta.37
    Ionic App Lib Version: 2.0.0-beta.20
    OS:
    Node Version: v6.3.1

For some reason the OS is not reported by `ionic info`. I'm on Windows 10 64 bit.

**Comment by windwp** [comment]
you forget to  add delay extension function
```
import 'rxjs/add/operator/delay';
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
