### ISSUE TITLE
Ionic 2 - Google Maps JS API works only one time after each refresh

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7703]
I have a Ionic2 app, where I have the homepage that leads to several pages, In each of these pages I have embedded Google Maps JavaScript Api.

What's weird is that when I open a page where google map is embedded in for the first time, it shows the map!
However, If I go back and open another page that has also the map, it does not show it.

When I do refresh, and I go to the page where the map was not showing before, it shows it (only after refresh).

In short, the map works only one time after each refresh, once you pop from that view and you go back to it again, the map disappears!

Some code:

**Index.html**

      <script src="http://maps.google.com/maps/api/js?key=MY_API_KEY&sensor=true"></script>

Page.html

     <div  style="height: 25%; width: 100%;" id="map_canvas"></div>

Page.js

        ngOnInit(){

                displayMap(){
          let latLng = new google.maps.LatLng(34.45, 54.61);

          let mapOptions = {
                center: latLng,
                zoom: 10,
                mapTypeId: google.maps.MapTypeId.ROADMAP
              }

          let icon = {
              url: "../../img/locationPin.png", // url
          };

          this.map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
          this.marker = new google.maps.Marker({
             position: latLng,
             map: this.map,
             icon: icon
           });

        }

        }

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by TomasKatz** [comment]
Michael I am getting all your development conversations to my personal
mail. I have nothing to do with any of your conversations !!! I am not
working at ionic or have ever worked there !!! This is a violation of my
privacy ! Please do not send me any more mails or this will bubble up to
your managers !!!

**Comment by HamzaLJ** [comment]
@TomasKatz I really don't know why you are receiving that! Maybe it's a bug on Github!

**Comment by caden311** [comment]
Was this ever figured out?
