### ISSUE TITLE
Issue when updating to Beta 11 - ([ngModel]) does not work anymore with ion-list

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7707]
I've just updated to Beta 11, and the below stopped working:

		<ion-list radio-group [(ngModel)]="content">

Using that **ngModel** I used to capture the value of the selected radio-button; however, it stopped working when I updated to Beta 11.

By the way I was not using forms module and I don't want to use it.

Can someone from the Ionic team respond to this matter?

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! It seems as if you are using the wrong syntax with `ngModel`. The correct syntax is `[(ngModel)]`. Thanks for using Ionic!

**Comment by HamzaLJ** [comment]
Sorry, that was only a typing issue in Github, the following does not work:

          <ion-list radio-group [(ngModel)]="content">

**Comment by no4aTuk** [comment]
same problem . appeared after i update app to beta 11 from beta 8

**Comment by HamzaLJ** [comment]
Also `ion-select` does not work with `ngModel` anymore!

**Comment by HamzaLJ** [comment]
I've tested it for many hours and discovered that any `<ion-*` tag does not work anymore with `ngModel`

**Comment by ominfowave** [comment]
same problem appeared after i updated app to beta 11 from beta 9

**Comment by ominfowave** [comment]
<ion-list radio-group [(ngModel)]="content"> does not work in beta 11

**Comment by ominfowave** [comment]
<ion-list radio-group [(ngModel)]="content">

**Comment by q-depot** [comment]
try to downgrade @angular/form to 0.2.0, that worked for me.

**Comment by no4aTuk** [comment]
thank you it works! after i downgraded i also had to delete unused FORM_DIRECTIVES from my Component

**Comment by ominfowave** [comment]
thanks  q-depot

**Comment by HamzaLJ** [comment]
For me even downgrading to 0.2.0 did not work.
I downgraded the whole ionic to Beta 10, as Beta 11 came along with a lot of bugs, I even now have navBar below the status bar when deploying to an iOS device! So, the best option I had is to downgrade to Beta 10.

**Comment by jgw96** [comment]
Hello all! There were alot of changes to the Angular 2 forms module in the latest Angular 2 forms release which includes things like all form controls using `[(ngModel)]` now requiring a `name` attribute. We are currently working on some docs for all these changes, but in the meantime feel free to check out the official [Angular 2 form docs](https://angular.io/docs/ts/latest/guide/forms.html). Also, i have made a repo [here](https://github.com/jgw96/ngModelExample) that shows a super simple example of `[(ngModel)]` working in Ionic 2 beta.11 without forms. Thanks for using Ionic!

**Comment by linshu** [comment]
@jgw96 
I am still having a problem with ngModel in <ion-list radio-group>, even <ion-input [(ngModel)]> works for me. Here is my code. Anything wrong with it?


```
<ion-list raido-group [(ngModel)]="shopCategory" (ionChange)="changeShopCategory()" ngDefaultControl>
  <ion-item>
    <ion-label>Food</ion-label>
    <ion-radio value="Food" (ionSelect)="selectCategory()"></ion-radio>
  </ion-item>
  <ion-item>
    <ion-label>Professional</ion-label>
    <ion-radio value="Professional" (ionSelect)="selectCategory()"></ion-radio>
  </ion-item>
  <ion-item>
    <ion-label>Recreation</ion-label>
    <ion-radio value="Recreation" (ionSelect)="selectCategory()"></ion-radio>
  </ion-item>
</ion-list>
```

Thanks a lot!
