### ISSUE TITLE
Ionic 2 beta 11 ModalController issue

### ISSUE THREAD

**Issue by windwp** [driftyco/ionic#7709]
In ionic beta 11 If we display modal by using ModalController It will call ionViewWillLeave()  function
But my app use this function for reset data when user change to another tab.
And I don't want when I click modal it will reset my data too.
Is there any way to check a page or modal for leave in ionViewWillLeave()

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
