### ISSUE TITLE
navBar goes behind status bar + all the view are scrollable after updating to Beta 11

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#7716]
Among the issues and bugs that came with Beta 11 is that the nav bar goes behind the status bar.
That's bug appeared when simulating on an iOS device.

Furthermore, all the view became scrollable, is there any way to have non-scrollable views like in Beta 10?

Can someone from the Ionic team reply concerning these two matters?

**Comment by jgw96** [comment]
Hello @HamzaLJ , thanks for opening an issue with us! Would you mind creating a repo that shows an example of these two issues and posting it here? Thanks for using Ionic!

**Comment by waqarmahar** [comment]
I am facing the same issue navbar(App Header) overlapping the ios status-bar, but it was the same in beta 10, i fixed it pushing the platform-ios 20px margin. but haven't found an actual fix. anyone?

**Comment by dgroh** [comment]
on **app.ios.scss** you can set:

```
    ion-navbar {
        &.toolbar {
            padding-left: 6px;
            padding-top: 25px;
            padding-bottom: 10px;
        }
    }
```

**Comment by jgw96** [comment]
Hello! @waqarmahar @dgroh would you guys be able to share a repo that shows a minimal example of this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
