### ISSUE TITLE
chip color attributes are not working

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#7717]
Color attributes such as primary, light etc.. are not working on ion-chip

#### What behavior are you expecting?
the chip to be colored

**Steps to reproduce:**
1. use ion-chip component with a color attribute 

```
<ion-chip primary>text</ion-chip>
```

**Which Ionic Version?** 2

#### Plunker that shows an example of your issue

http://plnkr.co/edit/m9gVejYttPxSsVsxaWsw?p=preview

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed by #7467 after I merge #7731. :)
