### ISSUE TITLE
Samsung - scroll not working

### ISSUE THREAD

**Issue by JeanCarriere** [driftyco/ionic#772]
I have a Samsung Galaxy S3 with Android 4.3. 
When I open an ionic app in the default Samsung browser, I cannot scroll the pages.
For instance if I copy the code of the list defined on this demo : http://codepen.io/ionic/pen/JsHjf 
and I add some items to the list, impossible to scroll the list.

No problem if I use the chrome browser.

If I add overflow-scroll='true' to the ion-content, the scroll is working, but then i get some other problems on the refreshers.

**Comment by snaiperskaya96** [comment]
Same issue, looks like it comes with some version of android such as 4.1.2 4.2.1 4.2.2

**Comment by eggarsync** [comment]
Same issue on galaxy s3. :(

**Comment by eriwangi08** [comment]
I'm running android 5.1.1 on Samsung Galaxy Tab A (2016). I have implemented a webview and androidpdfviewer and i'm experiencing the scroll issue. 
Kindly assist.
