### ISSUE TITLE
NavController methods don't fire in LoadingController callback after async operation

### ISSUE THREAD

**Issue by MattDHill** [driftyco/ionic#7723]
#### Short description of the problem:
In ```loader.dismiss().then(() => {this.navCtrl.pop()})``` navCtrl.pop() is not executed. The page remains. There was some strange behavior from the Loading Component in prior betas, but this is new to Beta 11.

#### What behavior are you expecting?
NavController methods should fire in LoadingController callbacks.

**Steps to reproduce:**
1. clone the repo: https://github.com/MattDHill/LoadingBug
2. run "ionic serve" or "ionic emulate iOS"
3. just click the buttons, very straightforward.
4. every once in a while pop() gets fired, but rarely.

**Which Ionic Version?** 1.x or 2.x
2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! It seems that since your loading component is opening and closing so fast because the http request completes very fast that it gets confused on which `NavController` to pop from. Do you have a Loading component that is closing this fast after opening in your application like it is in your example? I have made a repo [here](https://github.com/jgw96/navPopExample) that shows this working, but my loading components in that example are open for a few 100ms  before closing them.

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue and i will happily reopen. Thanks for using Ionic!

**Comment by Geoffrey-D** [comment]
@jgw96  I have the exact same issue, and the http call is not "fast" : I am uploading a picture to a webservice which creates thumbnails (so it takes around 1 sec).

Here is the portion of the code :

  ```
           let picLoader = this.loadingController.create({
                    content: "Saving picture...",
                    duration: 5000
                });

                picLoader.present();

                let options = {mimeType: 'image/jpeg', chunkedMode: false, headers: {'Authorization': 'Bearer ' + this.token},};

                this.fileTransfert.upload(fileUrl, AppSettings.API_ENDPOINT + '/images/', options, true).then((result) => {

                    picLoader.dismiss(); // NOT WORKING

                    let toast = this.toastController.create({
                        message: "the picture has been saved !",
                        duration: 3000
                    });
                    toast.present(); // Working fine

                }, (err) => {
                    picLoader.dismiss(); // Not working
                    let toast = this.toastController.create({message: "an error occured", duration: 4000});
                    toast.present(); // Working
                });

```

Should I open a new issue or you can re-open that one?

PS : I use crosswalk

**Comment by jgw96** [comment]
Hello @Geoffrey-D ! Would you mind testing again but without the toast? Thanks!

**Comment by Geoffrey-D** [comment]
@jgw96, it does works without the toast, the popup is dismissed, thx! how can I have both? with picLoader.dismiss().then( --  toast here --)... ?

**Comment by jgw96** [comment]
Hey @Geoffrey-D ! Good news! That issue has actually already been fixed and will be in the beta.12 release. The reason i got you to test that was to confirm that it was the same issue 😃 . For now, you can just make sure that you close the loader first before opening a toast using the navigation promises like you show in your above comment. Thanks for using Ionic!

**Comment by Geoffrey-D** [comment]
ok thanks !

**Comment by MattDHill** [comment]
Hi @jgw96. Sorry been traveling and for some reason didn't get any notifications about this thread. I am still having the same issue. Are you able to reproduce with the github repo I provided. It's very basic, not doing anything special. Just want to present the loading component, fetch some async data, dismiss the loading component, and navigate away. Before beta 11 this worked fine. Now, the loading component dismisses, but the page remains.

**Comment by jgw96** [comment]
@MattDHill No problem. Would you mind trying this please? 

```
loader.dismiss().then(() => {this.app.getRootNav.pop()})
```
Thanks!

**Comment by MattDHill** [comment]
Same thing. The loader dismisses, but the page remains. Also had to add `()` after getRootNav, just FYI. Thanks for looking into this.
