### ISSUE TITLE
Ionic2--Open app too slow 

### ISSUE THREAD

**Issue by FourLeafClover** [driftyco/ionic#7724]
Help! Help! Help!

 When i open my app, it takes at least 8-10 seconds, how can i let my app open more quicker.

**Comment by ubaidazad** [comment]
Ionic2 is not supporting AoT and tree-shaking yet, may be in beta 12

**Comment by FourLeafClover** [comment]
Hi, whether the ionic can on demanding loading like webpack + es6.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are currently working on the final details of our new build process, which includes ahead of time compile, minification and tree shaking which will greatly improve load times and general performance. This is one of the features we want to have for beta.12, but as always that is subject to change if something crazy happens. Thanks for using Ionic!

**Comment by jgw96** [comment]
Also, [this](https://github.com/driftyco/ionic/issues/6776) issue is the tracking issue for aot and tree shaking. Thanks!

**Comment by i-Dee** [comment]
Hello, please whats the latest. I'm sincerely in love with ionic2. But the lag has made me pause my development.

**Comment by dmastag** [comment]
Just wait a moment @i-Dee. Beta 12 is almost ready.
You can try out the bleeding edge if you are curious too see where the progress is now.

**Comment by i-Dee** [comment]
Whats bleeding edge @dmastag , is it the meeting notes?

**Comment by HockeyJustin** [comment]
Hi,

I am also experiencing an 8-10 second load with an empty app.

### The repro - (09 Feb 2017):

1. Follow the [basic tutorial](http://ionicframework.com/docs/v2/intro/installation/) on the ionic website for creating an app.

   _(ionic info)
   Cordova CLI: 6.4.0
   Ionic CLI Version: 2.1.8
   Ionic App Lib Version: 2.1.4
   OS: Windows 10
   Node Version: v6.9.1_

2. Add Android - cordova platform add android --save (and [accept the android licence](http://stackoverflow.com/questions/40392345/ionic-build-error-you-have-not-accepted-the-license-agreements-of-the-followin) if needed.)
3. Make no other changes.
4. Test in Ripple (runs nice and quickly)
5. Publish using [these steps](http://stackoverflow.com/a/35173700/852806).
6. Test on Samsung A3 and HTC M9. 

### Result on Phones: 
Both have an 8-10 second load consistently.

### Additional Info
Tried a similar procedure with Ionic1 to ensure it wasn't the phones or the publish process. The load was around 2-3 seconds (perfectly acceptable).

I love Ionic2, but this could stop us using the product as many consumers [will not wait](https://www.ca.com/content/dam/rewrite/files/app-economy-quiz/survey-new/assets/app-economy-research-and-infographic.pdf) that long for an app to load.

**Comment by dmastag** [comment]
@HockeyJustin how did you build?
Did you use ```ionic build android --prod``` ?

**Comment by HockeyJustin** [comment]
@dmastag ionic build android --release, in line with step 5. Is that wrong?

**Comment by dmastag** [comment]
@HockeyJustin how did you build?
Did you use ```ionic build android --prod``` ?

**Comment by HockeyJustin** [comment]
@dmastag - Updated to the very latest and using the ionic --prod build as well as ionic --release. 

The load is around 5 seconds (still not as fast as Ionic1, but much better).

ionic info
ordova CLI: 6.5.0
_Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed_

Had forgotten, but I'd been using --release build as the --prod produces a '-debug.apk' which i had issues signing. I can sign '-release.apk' without any problems.

**Comment by dmastag** [comment]
@HockeyJustin you can do ```ionic build android --prod --release```

**Comment by HockeyJustin** [comment]
For info, I tried the ionic side menu template (same ionic versions as above). Tried `ionic build android --prod --release` and `ionic build android --prod`. 

The load time is still around 10-11 seconds on my Samsung A3. Everything is sweet after the initial load, but the startup is still very slow. 

Won't bother you any more on it.

**Comment by dmastag** [comment]
Curious why it went down from your 5 secs to 10-11 secs.

**Comment by HockeyJustin** [comment]
@dmastag - Do you know what the benchmarks are (I have googled)? No worries if you have too much on to reply. I just thought it might be good for the thread to know what the expectation is.

**Comment by gbelmm** [comment]
npm install @ionic/app-scripts@latest --save-dev

**Comment by HockeyJustin** [comment]
@gbelmm tried the update. Still 9.5 seconds on average.

**Comment by dmastag** [comment]
@HockeyJustin what OS is your Samsung A3 on? If on 4.4 then could you try using crosswalk 
http://ionicframework.com/docs/cli/browsers.html

**Comment by HockeyJustin** [comment]
@dmastag - I tried using `ionic plugin add cordova-plugin-crosswalk-webview`. No difference in load time. My android os is v6.0.1.

**Comment by mariohmol** [comment]
@HockeyJustin have news about it? having same issue .. 15s to load and tryed a lot of different things

**Comment by HockeyJustin** [comment]
@mariohmol - nope. Was going to download the latest and try last week, but haven't gotten round to it. No joy last time i tried.

**Comment by HockeyJustin** [comment]
Just in case anyone should find this thread online - the issue is fixed in the current version (Ionic 3)

**Comment by mariohmol** [comment]
@HockeyJustin your app is taking how many seconds to show the first page? 

I updated to the latest and i'm getting like 20s to load.. 

 will try to profile to see if i can improve or test withou any action on load... but until now kind the same =(

**Comment by HockeyJustin** [comment]
@mariohmol - I updated to 3.6.0, created the starter (cutePuppyPics > super template) and now the load is under 3 seconds.
