### ISSUE TITLE
flexbox is broken in beta.10 and beta.11

### ISSUE THREAD

**Issue by lain-me** [driftyco/ionic#7725]
From http://www.joshmorony.com/an-in-depth-look-at-the-grid-system-in-ionic-2/ I studied how to split screen into parts with flexbox, but after beta.9 it stopped working. 

Here are two almost identical plunkers to compare:
 [flexbox beta.9](http://plnkr.co/edit/gShyKFUlPZX1S3MgOKWT?p=preview)

[flexbox beta.10](http://plnkr.co/edit/leVNRzLArDG8YkPJFPMj?p=preview)

Can you confirm that it is broken and not something changed behind the scene?

**Comment by jgw96** [comment]
Hello @lain-me ! Thanks for using Ionic! In beta.10 we did a complete overhaul of of our layout which may cause problems with older tutorials that have not been updated. I would recommend contacting josh about it! Thanks for using Ionic!

**Comment by alan-agius4** [comment]
What changes in that before the "scroll-content" had a display flex, but now a new class has been added "show-page" on ion-page which is setting the display block.

There are 2 things that you can do for a quick fix, wrap the ion-rows in an ion-grid and give it a height of 100% (remove padding if required) or wrap it in a div, and set it's display to flex and a height of 100%.

**Comment by lain-me** [comment]
simply putting a div with 100% height worked
