### ISSUE TITLE
Ionic 2/Beta 11: Form tag breaks ion-slides component 

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic#7728]
#### Short description of the problem:
Using a <form> tag inside (or outside) of ion-slides breaks the rendering of the slides.

#### What behavior are you expecting?
I would expect the slides to be rendered normally regardless of whether a form tag exists.

**Steps to reproduce:**
1. Create a component that leverages <ion-slides>
2. Put a <form> tag either surrounding the <ion-slides> element, or even inside of an individual <ion-slide> element
3. Notice that when rendering the view, the slides do not look correct (I see one bullet point instead of two)

```
// This works like a charm
<ion-slides>
    <ion-slide>
           Slide 1
    </ion-slide>

    <ion-slide>
         Slide 2
    </ion-slide>
</ion-slides>


// This breaks the rendering 
<form>
<ion-slides>
    <ion-slide>
           Slide 1
    </ion-slide>

    <ion-slide>
         Slide 2
    </ion-slide>
</ion-slides>
</form>

// This also breaks the rendering
<ion-slides>
    <ion-slide>
           Slide 1
           <form>
           </form>
    </ion-slide>

    <ion-slide>
         Slide 2
    </ion-slide>
</ion-slides>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

There are no errors in the log

**Which Ionic Version?**  2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v0.12.2

**Comment by joshgarwood** [comment]
My fault... I forgot to add a "name" attribute to my input element (not shown in the example).  But wow, that took a long time to realize, ha.  Seems like more of an Angular 2 issue than an ionic issue... I wish they could log HTML error better.

**Comment by jgw96** [comment]
@joshgarwood Glad you figured out what was causing the issue! We are currently working on our own documentation of all the new changes in Angular 2 forms which will hopefully help with this!
