### ISSUE TITLE
Expose members: instance & data in ViewController

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic#7730]
#### Short description of the ~~problem~~ current state:

ViewController declares `instance` and `data` members as **private** via JSDocs `@private`
#### What behavior are you expecting?

ViewController should expose `instance` and `data` members as **public**
#### Use case

It will be useful to get the instance of the current view and data parameters that generated it.

An app has a menu and 1 page: `TabsPage`.
`TabsPage` has 2 tab items: `HomePage`, `AboutPage`.  
Each acts as a root for the `Tabs` component

```
<ion-tabs>
  <ion-tab [root]="HomePage"></ion-tab>
  <ion-tab [root]="AboutPage"></ion-tab>
</ion-tabs>
```

The app's `ion-menu` has 2 links, each points at `TabsPage` with data provided via `NavParams`.  
`TabsPage` shows the right tab/subpage by analysing the parameters.

> `ion-menu` and `ion-tabs` share links.

This configuration works, however it renders the `TabsPage` for every click on the menu items.

To workaround this, message should be sent to `TabsPage` once this is the situation.

Using `nav.getActive().instance` I can get the tab's page instance, if it implements an interface (e.g: `selectTab(NavParams)`) I can call it and do an internal change of the sub pages without re-rendering the tabs page.

since `instance` is semi-private (`@private` JSDocs) it kinda smell...

If there's another solution, i'd love to learn.
New to ionic and the new concepts of "routing" in ionic.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?**  2.x

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#155
