### ISSUE TITLE
Tabs: add ability to use a custom icon for a tab

### ISSUE THREAD

**Issue by mnasyrov** [driftyco/ionic#7732]
#### Short description of the problem:

Now it is not possible to use custom icons for tabs, only built-in Ionicons is supported.
#### What behavior are you expecting?

Ability to use a custom icon for a tab. Preferable way is to render a custom component (symbol + font) as icon via ion-tab's ng-content which inherits original icon styles.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#170

**Comment by lordgreg** [comment]
@jgw96 the issue link you've posted, doesn't exists anymore. Is there any other resource we could check for a specific "internal" request or is this something, that has already been implemented?

Thank you. 👍

**Comment by mnasyrov** [comment]
Any update on the issue?
