### ISSUE TITLE
Ionic with UDP client and server

### ISSUE THREAD

**Issue by wjrivera** [driftyco/ionic#7737]
Need a cross platform mobile development tool that can send and receive UDP messages to and from the app.  We are ready for Android and IOS development, but were looking for  a tool that does both.  The problem is that most hybrid tools depend on front end tools like JS/Angular which I have not been able to find a UDP tool for them.

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Windows 7 SP1
Node Version: v4.4.7

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
