### ISSUE TITLE
Can't run iOS or Android on Starbucks wifi

### ISSUE THREAD

**Issue by lacvapps** [driftyco/ionic#7742]
Strange but interesting I wish I could give you more info but after 3 hours of trying t debug this I got nothing. App doesn't go past the loading screen on iOS or android when running 'ionic run android' no console logs and no errors. Maybe I am doing something wrong. It also doesn't work at my apartment's public wifi. Ionic cli 2 ionic version 1.3.1

**Comment by jgw96** [comment]
Hello! Unfortunately im not sure their is anything we can do on our end to help this. This sounds like an issue related to reliable internet and not an ionic issue. Sorry that i can not help further. Thanks for using Ionic! I would recommend maybe tethering to another device if possible.
