### ISSUE TITLE
Is it possible to get the 'select' sit next to the 'input'?

### ISSUE THREAD

**Issue by goldenbearkin** [driftyco/ionic#7745]
I think below is the intuitive way to enter phone number 
<img width="308" alt="screen shot 2016-08-17 at 2 48 15 pm" src="https://cloud.githubusercontent.com/assets/11225712/17727852/81c4f8a4-648e-11e6-940a-aa1150dff3aa.png">

instead of making it two separate lines.
<img width="414" alt="screen shot 2016-08-17 at 3 14 33 pm" src="https://cloud.githubusercontent.com/assets/11225712/17727858/8a130f5a-648e-11e6-95ec-59f7e82b7b35.png">

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
