### ISSUE TITLE
[iOS] Long lists overlapping content above it

### ISSUE THREAD

**Issue by dgroh** [driftyco/ionic#7746]
#### Short description of the problem:
The problem ist that on **iOS**, long lists overlaps the content above it:

<img src="https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/b/8/b8fabd3c24c53508956614ada40d98e7e22ae7da_1_281x499.PNG" />

#### What behavior are you expecting?
I'm expecting the list not to overlap the content when it's **iOS**, it should look like this (**Android**): 

<img src="https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/8/c/8ca2dec2003b4217e0142ee92b52de889a32f1ac_1_353x500.gif" />

**IMPORTANT:** The list must be bottom aligned and the cards top aligned.

**Steps to reproduce:**
1. Create a page with the following structure:
<img src="https://forum.ionicframework.com/uploads/default/original/3X/c/2/c2f31293fe46783274c0e8a737615fac8a0e20f4.PNG" />
2. Add at least 30 items to the List 
3. Deploy it to **iOS** and **Android** and see the difference 

**Other information:**

[More info on Ionic 2 Forum](https://forum.ionicframework.com/t/losing-hopes-with-ios-ion-list-overlapping-issue/60687)
 
**Which Ionic Version?** 2 beta 11

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello @dgroh would you mind sharing a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by dgroh** [comment]
Hello @jgw96 thanks.

[Here](https://github.com/dgroh/ionic-v2-long-lists-overlapping-content-above-it) is the repo!

Looking forward for the feedback.

**Comment by dgroh** [comment]
Is this issue on the track? no feedback until now...

**Comment by jgw96** [comment]
Hello! Sorry it has taken a little while to get back to you on this issue! Would you mind trying this with our new [wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) and seeing if you can still reproduce the issue their please? Thanks!

**Comment by dgroh** [comment]
I @jgw96 thanks for getting back to me.

I'm afraid! Ionic support team always asks us to provide a Repo. We spend hours or evens days creating a Repo and the Repo does not get tested? So what is the point of creating a Repo and opening an issue providing all the informations?

I installed the `wkwebview` and it is **still not working** and I can see in the console that `wkwebview` is active:

> DEVICE READY FIRED AFTER 82 ms
> 2016-08-25 09:31:09.365 Ionic2 iOS Long List Issue[215:5131] Angular 2 is running in the > development mode. Call enableProdMode() to enable the production mode.
2016-08-25 09:31:09.383 Ionic2 iOS Long List Issue[215:5180] CDVWKWebViewEngine: XHR intercepted: build/pages/subjects/subjects.html
2016-08-25 09:31:09.516 Ionic2 iOS Long List Issue[215:5179] CDVWKWebViewEngine: XHR intercepted: build/pages/components/search-result/search.result.html
2016-08-25 09:31:09.516 Ionic2 iOS Long List Issue[215:5188] CDVWKWebViewEngine: XHR intercepted: build/pages/components/header-content/header.content.html
2016-08-25 09:31:09.594 Ionic2 iOS Long List Issue[215:5131] a0000000
2016-08-25 09:31:09.596 Ionic2 iOS Long List Issue[215:5188] CDVWKWebViewEngine: XHR intercepted: data/a0000000.json
2016-08-25 09:31:12.246 Ionic2 iOS Long List Issue[215:5180] CDVWKWebViewEngine: XHR intercepted: build/pages/topics/topics.html
2016-08-25 09:31:12.314 Ionic2 iOS Long List Issue[215:5131] a3000000
2016-08-25 09:31:12.315 Ionic2 iOS Long List Issue[215:5244] CDVWKWebViewEngine: XHR intercepted: data/a3000000.json
2016-08-25 09:31:13.863 Ionic2 iOS Long List Issue[215:5131] m0000496
2016-08-25 09:31:13.864 Ionic2 iOS Long List Issue[215:5244] CDVWKWebViewEngine: XHR intercepted: data/m0000496.json
2016-08-25 09:31:43.389 Ionic2 iOS Long List Issue[215:5131] m0000133
2016-08-25 09:31:43.390 Ionic2 iOS Long List Issue[215:5584] CDVWKWebViewEngine: XHR intercepted: data/m0000133.json

Thank you very much

Daniel

**Comment by jgw96** [comment]
Hello! Thanks for the info! We are testing with your repo and in fact thats how i found out that this looks like a css bug in uiwebview, which is why i asked if you would mind testing with wkwebview to see if that fixed it. Sorry if that came off as me not testing it! I am currently looking into this some more, but it definitely looks like a css bug in safari at the moment as it works fine in every other browser.

**Comment by jgw96** [comment]
@dgroh so after debugging this some more their seems to be a bug in safari which is causing it to not like the flex that your are putting on the scroll-content on the topics page. For some reason that flex is causing safari to make the second card much bigger than it is supposed to be. After debugging this with a teammate it seems to be a safari bug with their flexbox implementation and sadly there is not much we can do on our end to fix that. I would recommend looking into using margin to get the look you are going for. Sorry that i cannot provide a better answer! Thanks for using Ionic!

**Comment by dgroh** [comment]
@jgw96 thank you very much for the help. That is a very sad news. Let see what we can do from our side and in worst the case go for the CrossWalk.

**Comment by dgroh** [comment]
@jgw96  just wondering how you could see that this is a bug with safari? I'm debugging on Safari and I don't see the issue. I also see it with the Simulator working fine. So I would appreciate if you could tell me the steps you did to debug it.
