### ISSUE TITLE
Ionic 2, Beta 11, update from terminal causing package inconsistencies

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#7747]
Updating to Ionic Beta 11 causes NPM package inconsistencies

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "install" "--save" "--save-exact" "ionic-angular" "@angular/common@2.0.0-rc.4" "@angular/compiler@2.0.0-rc.4" "@angular/core@2.0.0-rc.4" "@angular/http@2.0.0-rc.4" "@angular/platform-browser@2.0.0-rc.4" "@angular/platform-browser-dynamic@2.0.0-rc.4" "@angular/forms" "rxjs@5.0.0-beta.6" "zone.js@0.6.12"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@0.3.0 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.11 wants @angular/common@2.0.0-rc.4

Anyone else seeing this?

Tom

**Comment by lukeisontheroad** [comment]
Same here. I just tried to upgrade from Beta 10 to 11 and encountered the same issue.

**Comment by dgroh** [comment]
First install the dependencies, then you install the parent packages.

**Comment by tomgallagher** [comment]
Sorry I don't understand that.

Angular forms wants @angular/common@^2.0.0-rc.5.

@angular/platform-browser@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4

How do you reconcile this? By loading both versions of angular common as dependencies?

Surely there's a typo in the beta 11 update instructions?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We have updated our changelog `npm install` upgrade command and have also updated the changelog to get rid of any carets. Sorry about the hassle this caused everyone! Thanks for using Ionic!
