### ISSUE TITLE
Ion-select i can’t get selected value

### ISSUE THREAD

**Issue by CoachMorta** [driftyco/ionic#7749]
Demo.html

    <ion-list>
      <ion-item>
        <ion-label class="ion-label”>label</ion-label>
        <ion-select  [ngModel]="selected_value" (ionChange)="showselected(selected_value)" [ngModelOptions]="{standalone: true}">
          <ion-option value="1"> item1</ion-option>
          <ion-option value="2"> item2</ion-option>
        </ion-select>
      </ion-item>
    </ion-list>

Demo.ts
showselected(selected_value)
{
console.log("selector: ", selected_value );
}

ionic info 

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v6.3.1

Hello , i have problem that i can't get selected value using (change), but when using (ionChange) it returns undefind value

**Comment by jgw96** [comment]
Hello! This should be fixed now. Unfortunately we were not specifying the exact version of `@angular/forms` in our package.json or our `npm install` command in the update instructions which causes an newer version of `@angular/forms` that does not support Angular 2 rc4 to be installed. To fix this you may have to go into your package.json and change the `@angular/forms` listing to `@angular/forms@0.2.0` and then run `npm install`. Thanks for using Ionic!
