### ISSUE TITLE
Page or Component ? Missing doc ?

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#7750]
Hi,

Some times I saw page defined in doc with ´´´@Component´´´ and sometimes with ´´´@Page´´´.
What is the difference ?
Which should be used ?
Where is the doc who explain that?

Regards,

**Comment by dgroh** [comment]
@Page is deprecated. And why this should be an issue? Ionic forum should be the place for this kind of question and here is the answer: https://forum.ionicframework.com/t/difference-between-page-and-component/55287

**Comment by jgw96** [comment]
Hello @movrack ! Thanks for opening an issue with us! Are you seeing `@page` in our documentation right now? Or are you saying you have seen it in the past. `@page` was deprecated a good while ago and should definitely not be in the docs.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#760

**Comment by jgw96** [comment]
Hello @movrack . Since this seems to be a docs related issue instead of a framework issue i have moved this issue to the appropriate repo. Thanks!

**Comment by movrack** [comment]
Thanks for move.

I see it here:
http://ionicframework.com/docs/v2/api/components/nav/NavPush/

> Where pushPage and params are specified in your component, and pushPage contains a reference to a @Page component:
