### ISSUE TITLE
Please update the command step's to upgrade to Beta 11 version

### ISSUE THREAD

**Issue by jorge13300** [driftyco/ionic#7753]
Hi, 

Please update the command step to upgrade to beta 11 version for this: 

npm install --save --save-exact ionic-angular @angular/common@2.0.0-rc.4 @angular/compiler@2.0.0-rc.4 @angular/core@2.0.0-rc.4 @angular/http@2.0.0-rc.4 @angular/platform-browser@2.0.0-rc.4 @angular/platform-browser-dynamic@2.0.0-rc.4 @angular/forms@0.2.0 rxjs@5.0.0-beta.6 zone.js@0.6.12

Because with the new Angular rc.5 if you don't specify the version of @angular/forms, npm get the latest version and is not compatible with Angular rc.4 

Sorry for my English.

Regards

**Comment by jgw96** [comment]
Hello @jorge13300 ! I just updated this in the changelog about 30 minutes ago with this commit https://github.com/driftyco/ionic/commit/82852fb353534210d6ecce7856c61d08e0449eb4. Thanks for using Ionic!
