### ISSUE TITLE
feat: Ionic.io BaaS

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7754]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am too much time wondering if ionic.io will publish BaaS platform, like Parse com or Firebase.
I think it's should be in ionic.io because it fits great on your platform:
Ionic 2 framework that build hybrid app with ionic.io user auth, analytics, push, the only thing that left is secured database with beforeSave&afterSave functions and more some basic features and it will be ultimative.
I won't need to create my own backend.
And i think it will let you make fine money.

Its just my opinion, it's should happen, it will just be the best for every side...</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey @MatanYed ! Thanks for the suggestions! All i can say is just keep an eye on us! (;

**Comment by dmastag** [comment]
@jgw96 what a cryptic and intriguing reply :smile:
