### ISSUE TITLE
Native scrolling will freeze js execution and DOM manipulation on Android.

### ISSUE THREAD

**Issue by fentas** [driftyco/ionic#7757]
#### Short description of the problem:
When I use native scrolling `$ionicConfigProvider.scrolling.jsScrolling(false);` some devices like Samsung s6 edge, galaxy, etc. will freeze js execution meaning I can't use scroll/touchmove/etc. events to observe scrolling.

If I install crosswalk these devices will work all (no freezing) besides of Samsung s6 edge. 
Samsung s6 edge will freeze all executions no matter what I do.

Is this standard behavior if not is there a way to utilize this huge performance bust of native scrolling somehow?
I know this is standard on iOS but should not exist on Android, shouldn't it?

Thanks a lot.

#### What behavior are you expecting?
No freezing of js execution and DOM manipulation.

**Which Ionic Version?** 1.x or 2.x
1.3

**Comment by jgw96** [comment]
Hello @fentas ! Thanks for opening an issue with us. Unfortunately Samsung has a bad habit of modifying certain things on their devices that can cause issues. Also unfortunately, that sounds like what is happening here, as i cannot seem to reproduce this on any of my nexus devices, or on my moto x. I would recommend sticking with javascript scrolling for now. Thanks for using Ionic and sorry i could not help more.
