### ISSUE TITLE
ionic run android grabs wrong (old) apk after installing crosswalk 

### ISSUE THREAD

**Issue by daixtrose** [driftyco/ionic#7758]
#### Short description of the problem:

When you install crosswalk, the old apk files do not get removed during android build and android run then takes the old packages. You have to delete all files below `platforms\android\build\outputs\apk\`first.

#### What behavior are you expecting?

`ionic run android` should run the x-walk version 

**Steps to reproduce:**
1. `ionic plugin add cordova-plugin-crosswalk-webview`
2. `ionic run android`

**Which Ionic Version?**  2.x

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1283

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Since this was an issue related to the cli and not the framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
