### ISSUE TITLE
FAB buttons should move when a toast message is shown

### ISSUE THREAD

**Issue by sergiomilici** [driftyco/ionic#7760]
on Ionic v2, when FAB button is displayed and toast message is shown, the FAB button must be animated and move at the same time the toast message does. Right now, the toast message is over the FAB button.

Ref: https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#152

**Comment by billism1** [comment]
I am curious, what is the status on this?

**Comment by maumchaves** [comment]
I have implemented a temporary solution. It is an Angular / Ionic 3 directive that allows Ionic toasts to animate the fab buttons and other elements in the fixed-content div of a page accordingly.

All you have to do is to include the directive in your project and then add a corresponding element in your app component template:

`<ng-container move-fixed-content-with-toast></ng-container>`

Please check out the code here: 
https://gist.github.com/maumchaves/d7270b54afd5c8ae120f34b41436a119
