### ISSUE TITLE
Upgrade angular version in atmosphere package

### ISSUE THREAD

**Issue by jvillamor-visp-net** [driftyco/ionic#7762]
Hi there.

So, there's no fix for the IOS double tap bug in ionic-sdk npm package for angular-meteor. And the only work around is to use driftyco:ionic atmosphere package. However, our application uses Angular 1.5's `component()` method and meteor would only let us use the atmosphere package's 1.4.8 version of Angular. So would it be alright to update the Angular version used in the atmosphere package to 1.5.x?

**Comment by jgw96** [comment]
Hello @jvillamor-visp-net ! Thanks for opening an issue with us! Unfortunately this sound's like something that the meteor team will have to resolve. Thanks for using Ionic!
