### ISSUE TITLE
when i update the Picker option ,the columns options was overlap

### ISSUE THREAD

**Issue by lh4111** [driftyco/ionic#7763]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I  want to create a city picker

how to dynamically change the `Picker Columns Options `

#### What behavior are you expecting?

**But ,They overlap**
![http://o93ntudss.bkt.clouddn.com/Untitled.gif](http://o93ntudss.bkt.clouddn.com/Untitled.gif)
**Steps to reproduce:**
1. 
2. 
3. 

```
let picker = this.pickerCtrl.create({
      buttons: [
        {
          text: '取消',
          role: 'cancel'
        },
        {
          text: '确定',
          handler: (data: any) => {
            console.log(`${data.province.value} ${data.city.value}`);
          }
        }
      ],
      columns: [
        {
          name: 'province',
          align: 'right',
          options: this.province
        },
        {
          name: 'city',
          align: 'left',
          options: this.city
        }
      ]
    });

    picker.ionChange.subscribe(
      data => {
        picker.getColumns()[1].options = this.city2[data.province.value]
        
      }
    )
    
    picker.present();


```

**Which Ionic Version?** 

2.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com). Thanks for using Ionic!

**Comment by raychenfj** [comment]
Try to push all of your options into the column when initialize and then use the disabled attribute to hide or display the option dynamically.That's a work-around.
You can refer to the datetime component. When you select Feb, it will hide 29,30 and 31.
