### ISSUE TITLE
custom cssClass does not take effect on the select with action-sheet interface

### ISSUE THREAD

**Issue by ziggyJ** [driftyco/ionic#7764]
In our current project, we need to apply custom style on the select action-sheet. But no matte what style I pass in the alertOptions, the cssClass of the action sheet will become 'select-action-sheet'

It seems that this code override the cssClass https://github.com/driftyco/ionic/blob/master/src/components/select/select.ts#L283

According to #7032 and #6835 it seems the alert interface's issue has been fixed, but not the action-sheet interface.

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `beta 12` release. We have decided to rename `alertOptions` to `selectOptions` since it is being passed to both the Alert and Action Sheet interface. :smile:
