### ISSUE TITLE
bug: upload gif images with animation

### ISSUE THREAD

**Issue by Poojal123** [driftyco/ionic#7771]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>hellooo using camera plugin to upload animated gif images to server.. it is working fine.. but showing all types of images from gallery..
i only want to show gif images when i open gallery to select image.. i have changed mimetype image/* to image/gif as well still showing same result.. how to do???

pls help....

Even i have used imagePicker plugin for selecting multiple images...
it is removing animation of gif image while showing...
i have make some changes to plugin like i commented code that scales image or rezing it.. but still not working.. do u have any idea regarding this...

pls need help asap... 

thanx in advance....</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
