### ISSUE TITLE
Show keyboard on Show of Modal

### ISSUE THREAD

**Issue by spennyf** [driftyco/ionic#7773]
I have a modal view containing a textarea and when the modal is show I want the keyboard to appear. Here is my code

    $ionicModal.fromTemplateUrl('templates/inputtextarea.html', {
			      scope: $scope,
			      animation: 'slide-in-up'
			}).then(function(modal) {
				$scope.modal = modal;
				$scope.modal.show().then(document.getElementById("textarea").focus());
				document.getElementById("textarea").maxLength = 256;
			});

The keyboard is shown the first time the modal is shown, but when I close the modal and then show it again to update the text in the textarea, the keyboard is not show? Why does is show the first time but not the second, third, ect... and how can I get it to be shown each time the modal is shown?

Thanks

**Comment by spennyf** [comment]
UPDATE: also if I try to do 
`document.getElementById('textarea').innerHTML = 'test text!'` 
inside of the `.then` or outside of it, the text will appear the first time but will not be there when I reopen the modal view?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
