### ISSUE TITLE
Overriding Sass variables

### ISSUE THREAD

**Issue by oliviercherrier** [driftyco/ionic#7775]
#### Short description of the problem:
I don't success to override Sass variables. Issue very close to issue #7500

#### What behavior are you expecting?
I expect to change the color of a tab bar by updating the Sass variable in my page scss file. But updating $tabs-md-background did not change anything.

**Steps to reproduce:**
1. put the line "$tabs-md-background: red;" into the scss file of a page: nothing change
2. put the @import "app.core" at the beginning of app.ios.scss, app.md.scss and app.wp.scss: it works. But I guess it is an huggly solution. 

Same behavior for the line: "$toolbar-inactive-color: red;"

**Which  Ionic  version**
Ionic 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.7
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
******************************************************

Thank you by advance for your help,

Olivier.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! The correct place to override sass variables are in the `themes/app.variables.scss`file. There is also a comment in that file that has more information about it. Thanks for using Ionic!

**Comment by oliviercherrier** [comment]
Hello! Thank you for your quick  answer.

I understand that overriding '$tabs-md-background' in the `themes/app.variables.scss` file will override the style for all tab bar of my application. Actually, I want to override the style of each tab bar independently. I'm afraid that update the variable  in the `themes/app.variables.scss` file will not allow me to do it.

Which way do you recommend to update tab bar style independently in each page ?

For information, the precise use case that drive my request: I have one ion-tabs embedded in a tab off another ion-tabs and I want two different style for these two ion-tabs bar (placed at the top and the bottom of page).

Thank you for your support,

**Comment by kolayrandevu** [comment]
I have the exact same problem.

**Comment by iamjoyce** [comment]
#7469 for anyone else who happens to chance upon here - the answer is no, you can't override sass variables differently for each page.
