### ISSUE TITLE
Ionic 2 - Navigation fails partway for non-cached page when hosted on Heroku on desktop browsers

### ISSUE THREAD

**Issue by richardgcosgrove** [driftyco/ionic#7778]
Short description of the problem:
I created a separate github repository and heroku app to represent this issue as I've only been able to reproduce it with regularly with these segments of code.

When the Percentages page is not cached and Ionic attempts to navigate to it from clicking on a rep button the navigation stops part way and renders only part of the page. You can render it correctly by using a side menu, tab, or preload a tab to first cache the percentages page then navigates correctly. When running locally, I don't need to the page most of the time on chrome. However, regardless of what browser I use on my desktop the issue always shows up when hosted on heroku. To contrast my desktop experience though, the heroku apps load without issue on my Nexus 5x using chrome or ghostery.

Steps to reproduce:
1. browse ionicnavissue.herokuapp.com on Chrome or Firefox on Windows 10
2. Click one of the rep buttons
3. Enter some numerical value
3. Press save
4. Watch navigation break

Other information: 

https://bggapp.herokuapp.com/ (https://github.com/richardgcosgrove/boardgamegeekapp) works fine for comparison with similar navigation

source:
https://github.com/richardgcosgrove/ionic_nav_bug

Which Ionic Version? Ionic 2, Beta 11

Run ionic info from terminal/cmd prompt: (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 10
Node Version: v5.10.0

**Comment by richardgcosgrove** [comment]
I thought about it more and realized that I use alertController before navigating to the page. Removing it fixes the issue, so it seems to be related to that.

**Comment by jgw96** [comment]
Hello @richardgcosgrove ! Thanks for opening an issue with us! Thanks for the repo! Because of the way async navigation works in Ionic 2 you have to use promises/events when there are two transitions going on at the same time or things will break. Here is an example of how to close an alert and then push a page. 
```
  let alert = this.alertCtrl.create({
    //make your alert
    
   //button handler
   () => {
     onDidDismiss(() => {
       this.navCtrl.push(coolPage);
     )};
   }
```
If you would like to read more about this you can check out [this](http://ionicframework.com/docs/v2/api/components/nav/NavController/) part of our docs. Thanks for using Ionic!
