### ISSUE TITLE
Font other than english

### ISSUE THREAD

**Issue by neelancherivishnu** [driftyco/ionic#7782]
Hi , Thank you for listening me.
 How Ionic support fonts for other than English language? 
I want to make an Ionic app, that support Indian and Arabic languages from server.
Can you help me?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
