### ISSUE TITLE
PickerColumn not exported anymore (Ionic 2, beta 11)

### ISSUE THREAD

**Issue by BenjaminDieter** [driftyco/ionic#7783]
#### Short description of the problem:

Since I updated to Ionic 2 Beta 11 I can't import `PickerColumn` from `ionic-angular` anymore. That means I can't create my custom picker anymore.

#### What behavior are you expecting?

I expect `PickerColumn` to be importable from `ionic-angular`, just like `Picker`, `PickerController` and `PickerOptions` are.

The code (excerpt) below can't work, but did with beta 10:
```
    private pickerColumn: PickerColumn;

    ...

    someFunction(): void {
        this.pickerColumn = { name: 'col1', options: [] };
        this.picker = this.pickerCtrl.create();

        ...

        this.picker.addColumn(this.pickerColumn);
        this.picker.present();
    }
```

**Which Ionic Version?** 1.x or 2.x

Ionic 2 Beta 11

**`ionic info` :** 

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 10 x64
Node Version: v5.12.0

**Edit:**
I know this feature is not documented yet, but I'd still like to keep using it  ;)

**Comment by brandyscarney** [comment]
These need to be added back: https://github.com/driftyco/ionic/commit/215c6d846c6eb157b4510e63d863d2fdcf13b9af#diff-4c662dc4cf4f974e0f27891faea175b0L35
