### ISSUE TITLE
Searchbar customizable icons

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#7784]
We can use `showCancelButton`, in most of cases is great but when searching location that icon becomes `locate`, it would be great if we can change that icon while creating the searchbar component. Also `magnifying glass` could be change to `back-arrow`.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#169
