### ISSUE TITLE
List cards is cut off at bottom on ios

### ISSUE THREAD

**Issue by lolaswift** [driftyco/ionic#7787]
#### Short description of the problem:

List cards is cut off at bottom on ios- a few px. And when try to pull to refresh, if pull just a bit, word "loading" shows already but it's not really loading.
Everything is working perfectly on android devices.

```
    <div class="list card" ng-repeat="item in items>
      <div class="item item-avatar">
        <img ng-src="main/assets/images/placeholder.png" actual-src="{{::item.logo}}">
        <h2>{{::item.name}}</h2>
      </div>
      <div class="item item-body">
        <a href="#/app/item/{{item.id}}">
          <img class="animated fadeIn full-image" ng-src="main/assets/images/placeholder.png" actual-src="{{ item.thumbUrl }}">
          <h2>{{::item.title}}</h2>
          <p>{{::item.summary}}</p>
          <p>
            <a href="#" class="subdued">1 Like</a>
            <a href="#" class="subdued">5 Comments</a>
          </p>
      </div>
      </a>
    </div>
```

**Which Ionic Version?** 1.x 

BTW, I found an old issue report here https://github.com/driftyco/ionic/issues/1708. Which is the same symptom I have.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#106
