### ISSUE TITLE
Ipv6 network unsupported?

### ISSUE THREAD

**Issue by soulbeing** [driftyco/ionic#7790]
#### Short description of the problem:
I delivered my ionic2 app to Apple store for review, and I a response says that my app doesn't in IPv6 environment, I search "Ionic2 IPv6" on line but didn't found any useful info about it. So I made this issue here to ask for help. How can I solve this problem, to make my app working in IPv6 environment. Following is my park of my package.json, It's almost identical to ionic-conference-app, so basically I have to clue how to solve this. Any help please?

"dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "^2.0.0-rc.2",
    "angular2-jwt": "^0.1.18",
    "es6-shim": "0.35.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "^1.3.10",
    "ionicons": "3.0.0",
    "ng2-translate": "2.2.2",
    "pouchdb": "^5.4.5",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "gulp-tslint": "4.3.4",
    "ionic-gulp-browserify-typescript": "2.0.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "run-sequence": "1.1.5",
    "tslint": "^3.10.1",
    "tslint-eslint-rules": "^1.3.0",
    "nodemon": "^1.8.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-sqlite-2",
    "cordova-plugin-file"
  ],
  "cordovaPlatforms": [
    "ios",
    "android"
  ]

#### What behavior are you expecting?
I hope with the Ionic platform, I don't need to worry about IPv6 thing.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
ionic 2

**Comment by jgw96** [comment]
Hello @soulbeing ! Thanks for opening an issue with us! Are you using our wkwebview plugin? https://github.com/driftyco/cordova-plugin-wkwebview-engine

**Comment by soulbeing** [comment]
I tried https://github.com/wymsee/cordova-HTTP , and problem solved.  But still, why there are so many similar plugins? really hard to find the best fit.

**Comment by Z3roCoder** [comment]
Did you change anything about your API-Calls? Are they still made to IPv4 and it works now?
