### ISSUE TITLE
Keyboard not closing properly on iOS 10

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7791]
#### Short description of the problem:
When an Alert closes, the keyboard doesn't. Modals don't close when event originate from keyboard event (enter which triggers a method which closes the modal).

#### What behavior are you expecting?
The keyboard to close properly.

**Steps to reproduce:**
1. Open a modal
2. Close it using one of the buttons
3. The modal is still open

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind posting about this issue here https://github.com/driftyco/ionic/issues/7791. That is our tracking issue for iOS10 issues. Thanks!

**Comment by Bouzmine** [comment]
@jgw96 already done.

**Comment by jgw96** [comment]
Thanks alot!

**Comment by tuongaz** [comment]
Just wonder why this is closed as I'm having the same issue.

**Comment by Bouzmine** [comment]
The Ionic Team wants to have all iOS 10 related issues inside one (#6901).

@jgw96 could you change #7791 to #6901 for reference?



Merci,
Francis Clavette

**Comment by zefrench** [comment]
Salut Francis, as tu vu si une mise à jour du plugin keyboard règle le problème du clavier qui ne se ferme pas ?

**Comment by Bouzmine** [comment]
@zefrench J'utilise la dernière version du `ionic-plugin-keyboard` et le problème est présent. 
I'm using the latest `ionic-plugin-keyboard` version and the bug is still happening.

**Comment by zefrench** [comment]
That's a real problem, I don't know how to fix that.
