### ISSUE TITLE
Alert within Popover won't close

### ISSUE THREAD

**Issue by softhorizons** [driftyco/ionic#7800]
#### Short description of the problem:
An Alert launched *within a Popover* stays on the screen, does not close in response to Dismiss button.

#### What behavior are you expecting?
Alert should close.

**Steps to reproduce:**
1. Launch an alert from within a Popover
2. Click on Dismiss button

```
       let alert = this.alertCtrl.create( {
        title: "Failed",
        subTitle: "Message",
        buttons: [{ text:'Dismiss' }]
      });
      alert.present();*/
```

**Other information:** 
Happens because Alert's `enabled` property is never getting set, is waiting to do so on a lifecycle event that never happens.
 

**Which Ionic Version?** 2.0 beta11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you opening your alert in this manner: 

```
popover.dismiss().then(() => {
  // create alert
  alert.present();
});
```
Because all of our navigation in Ionic 2 is async, you have to use promises to wait for one transition to end before firing another one. You can read more about that [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/). Thanks for using Ionic!

**Comment by softhorizons** [comment]
No, I'm presenting the Alert from the Popover object's code on TOP of the *un*closed Popover. Nested. Once the user dismisses the Alert (a rare error message), I want the user to resume interacting with the Popover. One could make UX-convention arguments that I shouldn't be using one popup on top of another, but is that flat-out prohibited by Ionic?

**Comment by jgw96** [comment]
Hello! At this time it is prohibited by Ionic with alerts. Our Alerts work very similar to the way the native iOS sdk handles alerts in that when they are open they are the only overlay component that should be open at that time. Sorry for any hassle this causes! However, closing the popover and then opening an alert will work, and in terms of UX may be a more clear indication to the user that there was an issue with the action they initiated from the popover. Hope this explains things, and thanks for using Ionic!

**Comment by softhorizons** [comment]
Will this be added to documentation for Alert, etc? Enforcement would also be useful.
