### ISSUE TITLE
forwardRef() in docs -> FAQ

### ISSUE THREAD

**Issue by shlomiassaf** [driftyco/ionic#7801]
#### Short description of the problem:
Docs suggests using `forwardRef()`  in **Common Pitfalls**

#### What behavior are you expecting?
Do not suggest using`forwardRef` or at least add a section with a note suggesting the issue is probably caused due to a problem in the design.

Usually `forwardRef` is used in advanced scenarios in the framework (i.e: ionic, angular core) and should rarly occur in the application code itself. It can be avoided by using a better design.
I have seen lot's of question/scenarios in Gitter that a `forwardRef` will indeed solve quickly but they actually happen due to poor design. A developer reading the common pitfalls will "run" to implement that advice just to encounter issues later. Again, usually it's due to poor design in the service layer. I believe the angular team will also discourage the use of `forwardRef` as much as possible. 

**Which Ionic Version?**  2.x

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind opening this issue on our docs repo? https://github.com/driftyco/ionic-site Since this issue is not a framework issue, but instead a docs repo I will be closing this issue. Thanks for using Ionic!
