### ISSUE TITLE
Ionic alert shrinks text to one line

### ISSUE THREAD

**Issue by patrickhofer** [driftyco/ionic#7802]
#### Short description of the problem:
Ionic alert shrinks text into one line and makes it unreadable

#### What behavior are you expecting?
Display the template text from the ionic alert correctly. 

It happens also an android. Even when I only have one line text. 

```
doAlert(a, b, c, d, e, f, g) {
      let alert = this.alerCtrl.create({
        title: 'Öffnungszeiten!',
        message: 'Montag: ' + a + '<br>Dienstag: ' + b + '<br>Mittwoch: ' + c + '<br>Donnerstag: ' + d + '<br>Freitag: ' + e + '<br>Samstag: ' + f + '<br>Sonntag: ' + g,
        buttons: ['Easy']
      });
      alert.present()
    }


          <h2 (click)="doAlert(item.openingHours[0],item.openingHours[1],item.openingHours[2],item.openingHours[3],item.openingHours[4],item.openingHours[5],item.openingHours[6])">Alle Öffnungszeiten</h2>

```

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.37

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Unfortunately I am unable to reproduce this issue. Would you mind creating a repo that reproduces this issue? Thanks for using Ionic!

**Comment by patrickhofer** [comment]
@jgw96 Thanks for your answer! Sorry i misstyped it. I used `message` instead of `subtitle`... You can close this issue.
