### ISSUE TITLE
perf: Black Screen

### ISSUE THREAD

**Issue by accioweb** [driftyco/ionic#7805]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am getting white screen and content is not displaying. There are no errors on the browser console so I am not sure what to do.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
@accioweb  hi! we will not able to help you without more information. Can your provide a minimum code to reproduce the issue? are you using WKWebView?

Closing issue as invalid until more info in provided.
