### ISSUE TITLE
ionic 2:<ion-select> is not triggering (change) action event. If I use <select> tag then the (change) action is working.

### ISSUE THREAD

**Issue by Akilesh7** [driftyco/ionic#7807]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
The Ionic Select component does not emit a `change` event, but it does emit an `ionChange` event. Please refer to the [Output Events](http://ionicframework.com/docs/v2/api/components/select/Select/#output-events) section in the API documentation to find the Select component's events. Thanks!

**Comment by Akilesh7** [comment]
IonChange is working for me. Thank you Brandy.

**Comment by josuper** [comment]
Thanks Brandy.

**Comment by AbhayShiro** [comment]
Use this:

(ngModelChange)="someEvent($event)" 

this works just fine if u are using [(ngModel)] for the <ion-select>

**Comment by azarus** [comment]
So why is this gone from the documentation?
https://i.imgur.com/sPTdT6x.png

**Comment by brandyscarney** [comment]
@azarus Nice catch, they must have accidentally been undocumented. I've created an issue to get them added back here: https://github.com/driftyco/ionic-site/issues/1074

**Comment by Sampath-Lokuge** [comment]
Still, it's not there.Can you please tell me the place to find the detail of `ionChange` event? @brandyscarney

**Comment by brandyscarney** [comment]
You can use it the following way:

```
  <ion-select [(ngModel)]="gender" (ionChange)="onSelectChange($event)">
    <ion-option value="f">Female</ion-option>
    <ion-option value="m">Male</ion-option>
  </ion-select>
```

then in your page:

```
  onSelectChange(selectedValue: any) {
    console.log('Selected', selectedValue);
  }
```

This will be called every time the value of the select changes.

**Comment by Sampath-Lokuge** [comment]
Yes, I know about that part.But I would like to use the real data type instead of `any` here `selectedValue: any`.Can you please tell me the data type of `$event`? @brandyscarney

**Comment by TiagoSilvaPereira** [comment]
Thanksa lot!! It is not in the documentation at this moment.

**Comment by renjit00** [comment]
i would like to pass my department Id to Item change how can i trigger item id  (ionChange)="onSelectedItem(item.Id)"..im getting undefined value please help me on this

 <ion-item>
  <ion-label>Select Department</ion-label>
<ion-select [(ngModel)]="selectedDepartmentvalue" (ionChange)="onSelectedItem(item.Id)" #item>
 <ion-option *ngFor="let item of department" >{{item.Name}}</ion-option>
 </ion-select>

**Comment by renatinhoo8** [comment]
how can i get text of ion-select i don´t know how to use attribute selectedtext

**Comment by tinomen** [comment]
wow, this is a long time to leave ionChange undocumented.

**Comment by lekkra** [comment]
ion-option should be listening for a status change when attribute "multiple" on select is set to true.

**Comment by Luiz0tavio** [comment]
why  $event = selected value? ($event.target.checked)
i need the $event object itself! ($event.stopPropagation() and stuff)

**Comment by brandyscarney** [comment]
I am going to be locking this issue as the comments have strayed from the main issue which was resolved.

If you have concerns about the documentation please leave comments/reactions on the site issue: https://github.com/ionic-team/ionic-site/issues/1074

If you have questions on how to use the select component please view the [API documentation](http://ionicframework.com/docs/api/components/select/Select/) and then ask on our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/).

If you've found a bug or believe there should be a change to the select component please create a [new issue](https://github.com/ionic-team/ionic/issues/new) on this repository and fill out the pre-populated template.

Thank you! 🙂
