### ISSUE TITLE
feat: How to load more data from remote server when page

### ISSUE THREAD

**Issue by sleeper01** [driftyco/ionic#7808]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>As what I said in the title,when the new datas are rendered,I want to hash on the item before last load.</span>

<span is-issue-template></span>

![image](https://cloud.githubusercontent.com/assets/4557307/17835881/77de07a0-67b2-11e6-84e2-70ad5b8c1cbf.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
