### ISSUE TITLE
Tooling: Page generator log output problem

### ISSUE THREAD

**Issue by moberwasserlechner** [driftyco/ionic#7810]
#### Short description of the problem:
If I want to generate a page for a v2 project using the Ionic CLI under Windows the resulting log output to the console looks like this:

```
$ ionic g page personalRank
√ Create app\pages\personal-rank\personal-rank.html
√ Create app\pages\personal-rank\personal-rank.scss
√ Create app\pages\personal-rank\personal-rank.ts

Don't forget to add an import for personal-rank.scss in app\themes\app.core.scss                     :

  @import "..\pages\personal-rank\personal-rank.scss";
```

The problem is the **last line** because if I copy this line as it is to the **app.core.scss**, I will get a error when running `ionic serve`

```
$ ionic serve

Running 'serve:before' gulp task before serve
[11:42:59] Starting 'clean'...
[11:42:59] Finished 'clean' after 73 ms
[11:42:59] Starting 'watch'...
[11:42:59] Starting 'sass'...
[11:42:59] Starting 'html'...
[11:42:59] Starting 'fonts'...
[11:42:59] Starting 'config'...
[11:42:59] Starting 'scripts'...
[11:42:59] Finished 'config' after 60 ms
[11:42:59] Finished 'html' after 143 ms
[11:42:59] Finished 'scripts' after 176 ms
[11:42:59] Finished 'fonts' after 189 ms
app\theme\app.core.scss
Error: File to import not found or unreadable: ..pagespersonal-rankpersonal-rank.scss
       Parent style sheet: <PATH_TO_THE_APP>/app/theme/app.core.scss
        on line 15 of app/theme/app.core.scss
>> @import "..\pages\personal-rank\personal-rank.scss";
   ^
```

There should always be **forward slashes** instead of the platform specific path delimiters, which are currently used.

#### What behavior are you expecting?

Use forward slashes instead of platform specific path delimiters.

```
  @import "../pages/personal-rank/personal-rank.scss";
```
instead of 
```
  @import "..\pages\personal-rank\personal-rank.scss";
```

https://github.com/driftyco/ionic/blob/master/tooling/generators/page/index.js#L30

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v5.12.0
```` 

Thanks for a great and a very impressive framework.

BR,
Michael

P.S: I know this might look like a CLI problem but the actual generator code is located in this repo.

**Comment by jgw96** [comment]
Hello! Thanks for the kind words. While the generator code is located in this repo I am going to ask if you could open this issue in the cli repo instead as it is still a cli issue. Thanks for using Ionic!

**Comment by moberwasserlechner** [comment]
cli issue: https://github.com/driftyco/ionic-cli/issues/1301
