### ISSUE TITLE
LoadingController dismiss loader option

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#7812]
duration: 3000,
       dismissOnPageChange: true

      is known but if i want to show hide looader on my wish as like ob subscribe or on promise i am not able to do that in beta11.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! To dynamically dismiss a loading component you can do this:

```
let alert = this.alertController.create({
  //alert options
});
alert.dismiss();
```

Thanks for using Ionic!

**Comment by Anshdesire** [comment]
I have logged this issue for LoadingController not for alertController.

and if you are saying for  

```
let loader = this.LoadingController.create({
  //alert options
});
loader.dismiss();
```

I have tried this in beta11 and got this issue 

`XCEPTION: TypeError: Cannot read property 'remove' of undefined`

**Comment by paulparton** [comment]
@Anshdesire 

I had the same issue, I fixed it by adding a call to .present()

    this.mapLoadingLoader = this.loadingController.create({
      content: 'Loading map...',
    });

    this.mapLoadingLoader.present();
 
    this.mapLoadingLoader.dismiss();

**Comment by Anshdesire** [comment]
@paulparton 

I tried the same and posted in my comment still issue occurs 



```
doLogin(event): void {
    if (this.auth.login()) {
      this.nav.setRoot(FeedPage);
      return;
    }
    this.loading().present();
    this.http_service.setMeta(this.loginForm.value).post(this.config.apiLogin).subscribe(
      response => {
        this.localstorage.store('jwt-token', response.data.token);

        if (this.auth.login()) {
          this.loading().dismiss();
          this.events.publish('user:loggedin', response.data);
        }
      },
      error => {
        this.events.publish('user:failed', error);
        this.loading().dismiss();
      }
    );
    event.preventDefault();
  }


private loading() {
    return this.loader.create({
      content: 'Please wait...'
    });
  } 
```
