### ISSUE TITLE
ios swipe back

### ISSUE THREAD

**Issue by huigesv123** [driftyco/ionic#7815]
I have set state like this:

`$stateProvider.state('Tabs', {
  url: "/Tabs",
  abstract: true,
  templateUrl: "templates/Tabs.html"
})

.state('Tabs.Devs', {
  url: "/Devs",
  views: {
    'devs-tab': {
      templateUrl: "templates/DevList.html",
      controller: 'DevListCtrl'
    }
  }
}) 
 .state('Tabs.SetWifiStep1', {
  url: '/SetWifiStep1',
  views: {
    'devs-tab': {
      templateUrl: 'templates/SetWifiStep1.html',
      controller: 'Page2Ctrl'
    }
  }
})

.state('SetWifiStep2', {
  url: '/SetWifiStep2',
  templateUrl: 'templates/SetWifiStep2.html',
  controller: 'Page3Ctrl',
  cache : false
 })`

when I click tab Devs, it works and can swipe back to Devs. But when I run state.go('SetWifiStep2'), can not swipe back to 'Tabs.SetWifiStep1' in ios. Am I setting wrong path?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by huigesv123** [comment]
It echos 'There is a problem with your account. Please contact the site's administrator.'  when I want to login . @jgw96
