### ISSUE TITLE
Ionic2--LoadingController make my component can not two way bind

### ISSUE THREAD

**Issue by FourLeafClover** [driftyco/ionic#7817]
I have one function,when i click the tag button , the tag button will become green,  when i do not use loadingController in my project, the function is OK? but when i use loadingController in other page, the function is not ok, the bind data is modified,but ui do not change.
(Please understand,my english is poor.)   :)
![default](https://cloud.githubusercontent.com/assets/8449788/17851066/bed9a1f6-6892-11e6-9ba8-d8553d2c1c08.JPG)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by wangkeyi1992** [comment]
增加新页面  遮住下面的页面，我觉的可能使用tap手势事件有用，或者loading完之后销毁页面
