### ISSUE TITLE
Need a new option for inputs at the alertController component

### ISSUE THREAD

**Issue by navid045** [driftyco/ionic#7819]
#### Short description of the problem:

We can't add some custom attributes for inputs in alertController.
#### What behavior are you expecting?

I think it is necessary that we could add custom attributes like maxlength, id, style and etc to inputs in alertController.

I suggest we have a new option in inputs named "attr" that can set custom attributes for inputs. for example like this:

```
let alert = this.alertCtrl.create({
    title: 'Login',
    inputs: [
      {
        name: 'test',
        placeholder: 'Test name',
        attr: { maxlength: 6, id: "test", style:"color:red; font-size: 14px;" }
      }
    ],
    buttons: [
      {
        text: 'Cancel',
        role: 'cancel',
        handler: data => {
          console.log('Cancel clicked');
        }
      }
    ]
  });
  alert.present();
}
```

**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Windows 8
Node Version: v4.4.0

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#54

**Comment by nkaredia** [comment]
```
alertoptions = {
   title: 'sometitle',
   inputs: [{name: 'someName', id: 'someID'}]
}
```
```
alert.present().then(v => {
    // will fire this when modal is completely loaded with animations
   let id = document.getElementById('someID');
   if (id) {
      // Do your thing
   }
});
```

Although this is just a workaround, I think Ionic team should include a feature to add custom attributes to handle form validation and other native HTML5 features for inputs.
