### ISSUE TITLE
broken link on http://ionicframework.com/docs/v2/api/components/nav/Nav/

### ISSUE THREAD

**Issue by joshunger** [driftyco/ionic#7820]
1. Visit http://ionicframework.com/docs/v2/api/components/nav/Nav/

2. Click on tab link which points to http://ionicframework.com/docs/v2/api/components/Tabs/Tab/.

3. 404.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this is an issue with the docs and not the framework I will be closing this issue. Thanks for using Ionic!

**Comment by joshunger** [comment]
@jgw96 people are going to submit defects into driftyco/ionic because the docs are stored in drifyco/ionic or am I missing something?

**Comment by Devinsuit** [comment]
The docs are stored in https://github.com/driftyco/ionic-site/tree/master/docs.

**Comment by joshunger** [comment]
@Devinsuit when I clicked "Improve this doc" is showed a path a different path?  Can you check on your side?

**Comment by Devinsuit** [comment]
I think it should be "Improve this component". The docs are stored in https://github.com/driftyco/ionic-site/tree/master/docs.
