### ISSUE TITLE
List of supported platform versions.

### ISSUE THREAD

**Issue by joewoodhouse** [driftyco/ionic#7821]
Could we get a list in the documentation of the officially supported versions of iOS, Android and Windows Phone? I *think* from reading bug reports and forum posts it is:

- Android 4.1+
- iOS7+
- WP10

But it would be great if we could just have a definitive list in the documentation.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind opening this issue on our docs repo? https://github.com/driftyco/ionic-site I am going to be closing this issue as it is a docs issue and not a framework issue. Thanks for using Ionic!
