### ISSUE TITLE
Highcharts issue when using ion-content

### ISSUE THREAD

**Issue by oliviercherrier** [driftyco/ionic#7823]
#### Short description of the problem: 
When inserting an highchart in a <ion-content>, the fitting of the highchart is only done after resizing the browser window. And if I do not use  <ion-content>, the highchart is displayed partially behind the tab.

#### What behavior are you expecting?
Highchart should be fit to the browser page since the first load of the page when it is put inside a ion-content tab (to allow using tabbar and highchart in the same page)

**Steps to reproduce:**
1. Open http://plnkr.co/edit/VplSXRKSA7iCnZ3E2zYk?p=preview : Highchart is not fit to the window size
2. Remove: ion-content tag from home.html, Highchart fit to the window size but become partially displayed behind the tabbar

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
Implementation based on http://4dev.tech/2016/05/angular2-tutorial-creating-awesome-animated-charts-with-highcharts/

Same problem with using angular2-highcharts

**Which Ionic Version?** 2

#### Plunker that shows an example of your issue

http://plnkr.co/edit/VplSXRKSA7iCnZ3E2zYk?p=preview

**Run `ionic info` from terminal/cmd prompt:** 

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.7

Thank you for your help,

Olivier Cherrier

**Comment by jgw96** [comment]
Hello! As this seems to be an issue with the css that highcharts uses for their canvas element, and not an issue with Ionic i would urge that you open an issue on their repo. Thanks for using Ionic!

**Comment by oliviercherrier** [comment]
Hello,

Thank you for your quick answer, issue opened on Highcharts repo [here](https://github.com/highcharts/highcharts/issues/5609).

Kindly regards.

**Comment by oliviercherrier** [comment]
Hello @jgw96,

to fir  highchart width, Highchart team say that we need to reflow the chart render once container is visible.

To do this, I put the reflow in the  `ionViewDidEnter` callback (See http://plnkr.co/edit/atsoDMAmsalGTUJD8nF7?p=preview). But it does not work on my computer (I need to put a setTimeOut to fit the chart to the window). 

Can you say me which callback / event I have to implement to execute code only once  container is visible ?

Thank you by advance,

**Comment by jgw96** [comment]
Hello @oliviercherrier , `ionViewDidEnter` is in fact the correct lifecycle event to put that code in, but with beta.11 at the moment their is a slight bug with `ionViewDidEnter` which may cause you to have to use a `setTimeout` at times. This is all going to be fixed in beta.12. Thanks!

**Comment by oliviercherrier** [comment]
Hello @jgw96, thank you for your quick answer. Do you want I open an issue on it ? Because this issue is closed.

**Comment by jgw96** [comment]
There is already an issue open for it [here](https://github.com/driftyco/ionic/issues/7605). Thanks!
