### ISSUE TITLE
Button positioning in toolbar

### ISSUE THREAD

**Issue by steinroe** [driftyco/ionic#7825]
On Android and Windows, the toolbar content positions vertically. On iOS the start/end/left/right does not work either.
```
<ion-header>
  <ion-toolbar>
    <ion-title>Contacts</ion-title>
    <button start (click)="presentPopover($event)">
      <ion-icon name="funnel"></ion-icon>
    </button>
    <button end (click)="onAddContact($event)">
      <ion-icon name="add"></ion-icon>
    </button>
  </ion-toolbar>
  <ion-toolbar>
   <ion-searchbar
    [showCancelButton]="false"
    (ionInput)="onSearchInput($event)"
    (ionCancel)="onSearchCancel($event)">
  </ion-searchbar>
</ion-toolbar>
</ion-header>
```

<img width="1221" alt="bildschirmfoto 2016-08-22 um 16 05 20" src="https://cloud.githubusercontent.com/assets/19429600/17857505/44d41c48-6882-11e6-9e9c-bc7695c5cf9f.png">

**Ionic 2**
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014 

Thanks!

**Comment by brandyscarney** [comment]
Buttons inside of a toolbar should be placed inside of an `ion-buttons` element. Please see the Toolbar API docs for [Buttons in a Toolbar](http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/#buttons-in-a-toolbar) and the [usage](http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/#usage) section for examples. Thanks!
