### ISSUE TITLE
[beta.11] - preload tabs set a black background to tabs

### ISSUE THREAD

**Issue by malvarezhcr** [driftyco/ionic#7828]
#### Short description of the problem:
If I add preloadTabs="true" input to the ion-tabs tag the first tab loads fine but the other have a black background. This only happens on iOS

#### What behavior are you expecting?
Tabs should show have white background

**Steps to reproduce:**
1. Run a new project  (ionic start test --v2)
2. Add this input preloadTabs="true" to the ion-tabs tag 
3. Run the project on iOS

The code below sets a black background to the tabs

```
<div class="nav-decor"></div>
```
 
**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta.11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```
![img_1278](https://cloud.githubusercontent.com/assets/16544451/17861481/87e0c984-684e-11e6-98a3-46ffcf2f6ff8.jpg)
![img_1277](https://cloud.githubusercontent.com/assets/16544451/17861485/8afc4404-684e-11e6-93cd-bdf4ea4d0fcc.jpg)
![img_1279](https://cloud.githubusercontent.com/assets/16544451/17861492/8e1803d0-684e-11e6-96b5-9e6f13be3ce6.jpg)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! In beta.12 we have decided to remove the `preloadTabs` options as it is not needed anymore with aot compile and removing it gets rid of complexity. Because of this I will be closing this issue. Thanks for using Ionic!
