### ISSUE TITLE
feat: Remove top margin of ion-content

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic#7829]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hey, I'd like to make my `ion-navbar` transparent, minus the back arrow, and have the ion-content start underneath it, as opposed to having some margin at the top pushing it past the `ion-navbar`. Is it possible to remove this margin via some Component attribute in Ionic 2?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As mentioned in our docs [here](http://ionicframework.com/docs/v2/api/components/content/Content/) you can use the `fullscreen` attribute to achieve this effect. Thanks for using Ionic!

**Comment by sean-hill** [comment]
I saw that, but that only allows the content to scroll under the navbar, it still starts pushed down with a margin. I would like the content to be immediately under the navbar.

**Comment by jgw96** [comment]
@sean-hill You should be able to achieve this with some custom css. Can you confirm that none of the elements in your `ion-content` have a top margin on them?

**Comment by sean-hill** [comment]
Hey @jgw96 I just figured it out with custom CSS 👍 

    ion-header {
      
      &.custom-view::after {
        background-image: none;
      }
      
    }

    .custom-view {

      scroll-content {
        margin-top: 0px !important;
        padding-top: 0px !important;
      }

      .toolbar-background {
        background: transparent !important;
        border-color: transparent !important;
      }

    }

**Comment by jgw96** [comment]
Awesome! Thanks for using Ionic and have fun building your app!

**Comment by mread1208** [comment]
`margin-top: 0px !important` should not be the answer.... Is there no way in Ionic to disable to auto-calculation of the margin-top property?  I feel like the fullscreen attribute should disable this, but it doesn't.
