### ISSUE TITLE
ionic 2 tab-icons shows even in navigation-details page

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic#7831]
**My Issues :**
In my app i'm using tabs-icon plus navparams (Navigation) and in that if i click specific item navigation-details start where the icons must hide right?? but it didn't happen instead if shows up even in navigation-details page too. I'm using ionic 2 beta 11.. but i used same code in ionic 2 beta 10 it worked perfect.

highlighted the problem I'm facing in red..

In below i've posted my code. Please review and reply asap thanks... !! 
Beta 11
![ionic2_problem](https://cloud.githubusercontent.com/assets/5066436/17878912/bdf5ebcc-690b-11e6-90be-e87ddeca30ab.png)

Beta 10
![ionic2_workin](https://cloud.githubusercontent.com/assets/5066436/17878913/bdfbfd32-690b-11e6-850f-0598274b8423.png)

 
<!-- tabs Placement top -- >
<ion-tabs tabsPlacement="top">
  
  <ion-tab [root] = "home" tabIcon = "home"></ion-tab> 
  <ion-tab [root] = "events" tabIcon ="md-calendar"></ion-tab>

</ion-tabs>

<!-- events and its detailed view -- >

import { Component } from '@angular/core';
import { NavController,NavParams} from 'ionic-angular';

import { Service } from '../../providers/service/service';

//Events Component and Class
@Component({
  templateUrl: 'build/pages/events/events.html',
  providers : [Service]
})

export class EventsPage {

  events:any;

  constructor(private nav: NavController,public eventsService:Service) {
      this.loadEvents();
  }

  //Initial fetching of Data  
   loadEvents(){
    ... 
 }

  
  }
  //For Detailed View on Particular Event   
  openEventsDataPage(event_data) {
    this.nav.push(EventsDetailPage, { event_data: event_data });
  }

}
//End of Events Component and View

//Detailed View Component
@Component({

  templateUrl: 'build/pages/events/events-detail.html',

})

class EventsDetailPage {
  event_data;

  constructor(params: NavParams) {
    this.event_data = params.data.event_data;
  }
}

//End of Detailed View

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! You can read [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#material-design-tabs-7455) in our changelog about why the default tabs changed on Android and how to change them back to the old way if you would like. Thanks for using Ionic!

**Comment by Barathwaja** [comment]
My issue is not about bottom or top placement.. y navigation indetail doesnt hide those tab-icons is the question ... in beta 10 tabbed icons are hidden but in beta 11 its showing icons y is that so ???

**Comment by jgw96** [comment]
Hello @Barathwaja the reason your seeing the tabs still show up above the page that you are pushing is because of the way we changed tabs. If you apply the sass variables that i linked to in the changelog above it will change it back to the way it worked in beta.10. Thanks!
