### ISSUE TITLE
ionic2 change tabs 

### ISSUE THREAD

**Issue by Liubei1993** [driftyco/ionic#7834]
i used ionic2.
When I want to return to the directory with the navigation,The tab don't change into a state of activity.
for example,
1. 
home.ts:
this.navCtrl.push(TabsPage,{tabIndex:1});
2.
tabs.ts:
this.mySelectedIndex = navParams.data.tabIndex || 0;
3.
tabs.html:
<ion-tabs  [selectedIndex]="mySelectedIndex"

The page will jump but the tab will not change.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a repo that demonstrates this issue? Thanks for using Ionic!

**Comment by Liubei1993** [comment]
@jgw96 I have solved the problem by the following method.
1、app.ts
`@ViewChild(Nav) nav:Nav;`
2、test.ts

```
import {MyApp} from '../../app';
export class TestPage {
  constructor(private navCtrl: NavController,private myApp:MyApp) {
  }
	static get parameters() {
	  return [[MyApp], [NavController]];
	}
  back(){
  	let nav = this.myApp['rootNav'];
  	nav.setRoot(TabsPage,{index:3});//Can be switched to fourth tab
  }
}
```

But I don't know why the following method can't work;
```
this.navCtrl.push(TabsPage,{tabIndex:3});
this.navCtrl.setRoot(TabsPage,{tabIndex:3});
```

**Comment by jgw96** [comment]
Hello, the push method does not support passing a tabIndex. Glad that you found a solution. Thanks for using Ionic!
