### ISSUE TITLE
ionic2: ToastController will prevent app's behavior

### ISSUE THREAD

**Issue by kyocn** [driftyco/ionic#7836]
**The issue can be reproduced by the following steps.**

1. toggle a toast

2. before toast dismiss, touch one ion-select 

then the app no response with any touch or click(Seems blocked by something)

**Comment by jgw96** [comment]
Hello @kyocn ! Thanks for opening an issue with us! This issue has already been fixed and will be in the next release (beta.12). Thanks for using Ionic!

**Comment by scottwittrock** [comment]
Any update on when beta.12 is going live?

**Comment by jgw96** [comment]
@scottwittrock soon 😉

**Comment by scottwittrock** [comment]
👍🏼👏🏼
