### ISSUE TITLE
Doc error - supportedImageModes in Media Capture

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#7840]
In the [Media Capture](http://ionicframework.com/docs/v2/native/media-capture/), supportedImageModes() method description says:

"The audio recording formats supported by the device."

Is it right? The method name is about Image, the description is "audio recording".

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#766

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Since this was a docs issue and not a framework issue i have moved this issue to the appropriate repo. Thanks for using Ionic!
