### ISSUE TITLE
bug: Fab Button and Header Shadow

### ISSUE THREAD

**Issue by giammaleoni** [driftyco/ionic#7841]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>When using fab that partially overlap the header bar, the shadow of the bar overlap the button.

![image](https://cloud.githubusercontent.com/assets/12344105/17905218/6ecd0938-6972-11e6-9877-ef706bdb3d84.png)

Using a style like the one below temporary resolved the glitch:
`.button-fab {
   z-index:1
}`
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Most likely this will be fixed as part of https://github.com/driftyco/ionic/issues/7505.

**Comment by jgw96** [comment]
Hello, after testing the above PR i can say that this is fixed now and will be in the beta.21 release. Thanks for using Ionic!

**Comment by giammaleoni** [comment]
👍  Thanks, I will give a try! Great job, keep it up!
