### ISSUE TITLE
StatusBar overlays content during in-call

### ISSUE THREAD

**Issue by crazybaud** [driftyco/ionic#7842]
#### What behavior are you expecting?

We would like to use `<preference name="StatusBarOverlaysWebView" value="true"/>`, so the transparent status bar in ios overlays the top navbar for a really nice look.

But during in-call, content is not moved down further and so the blue status bar overlays our header, so it is not usable in this case.

Did someone found a solution ? If yes, we could add it inside the doc. Thanks :)

**Which Ionic Version?** 1.2.4

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually a bug in the cordova statusbar plugin but we have submitted a pull request to cordova to fix it, and have the fix applied to our fork of the plugin https://github.com/driftyco/cordova-plugin-statusbar. Thanks for using Ionic! Once the PR gets merged by the cordova team then everything will "just work" !
