### ISSUE TITLE
bug: Header right & left icons spacing issue

### ISSUE THREAD

**Issue by bharathibtch** [driftyco/ionic#7845]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ionic 2 header in android - right & left icons not having same padding, But android native header looks proper spacing for right and left icons.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind sharing some screenshots of the issue you are describing?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
