### ISSUE TITLE
Ionic 2 Beta 11: Dismissing modal triggers ionViewDidEnter

### ISSUE THREAD

**Issue by hw101** [driftyco/ionic#7847]
In Beta 10, dismissing a modal doesn't trigger ionViewDidEnter, but it does in Beta 11. Is this intentional? If I want to init data for every page load in ionViewDidEnter, but change some data after a modal dismiss, it can create a problem since the event will run before onDidDismiss().

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! It is intentional in beta.11 for modals to fire other lifecycle events. It was broken in beta.10 and was fixed for beta.11. You can put your update logic in `ionViewDidEnter` and that should work for you. Thanks for using Ionic!
