### ISSUE TITLE
Ionic 2 Beta 11: Ionic Native missing method setAllowIDFACollection(allow).

### ISSUE THREAD

**Issue by chocolei** [driftyco/ionic#7849]
http://ionicframework.com/docs/v2/native/google-analytics/

Related to the plugin, I cannot find the GoogleAnalytics.setAllowIDFACollection(bool) method in ionic-native.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#473

**Comment by jgw96** [comment]
Hello! Since this was an issue with ionic native and not the ionic framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
