### ISSUE TITLE
feat: Number picker

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7850]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Number picker it's good feature,
it will look like DateTime (from bottom) or like Alert (in middle) and will be able to swipe and choose number with minimum and maximum value.
It will be strict and won't able to put which number i want (in android number input isn't strict and i can put any number even with min and max.
it will look better, be strict, and much more native UI.</span>

<span is-issue-template></span>

**Comment by gigocabrera** [comment]
+1 +1 +1 +1
I really like this idea

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by MatanYed** [comment]
Right now i need number picker for age (min 16 max 99), so I think for now i will make it with DateTime component, that pick only year but YY (00-99 numbers) with min 1916 and max 1999

It's good solution for right now? (Until number picker feature will be developed)

**Comment by samrm111** [comment]
I would like to contribute by implementing this feature, if it gets accepted! 😄

**Comment by MatanYed** [comment]
Anything new?

Link to good number picker, for example:
https://demo.mobiscroll.com/number

Right now I am using the AlertController with radio inputs for number picker. I wish Ionic would have a real number picker. Will add so much to the UX.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#56
