### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Devinsuit** [driftyco/ionic#7852]
#### Short description of the problem:
Broken link on page http://ionicframework.com/docs/v2/api/components/nav/NavController/ 

- tab  link http://ionicframework.com/docs/v2/api/components/Tabs/Tab/ (http://ionicframework.com/docs/v2/api/components/tabs/Tab/  works)

- menu  link http://ionicframework.com/docs/v2/api/components/Menu/Menu/ (http://ionicframework.com/docs/v2/api/components/menu/Menu/  works)

**Which Ionic Version?**  2.x

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#768

**Comment by jgw96** [comment]
Hello! Since this is an issue with the docs and not the framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
