### ISSUE TITLE
issues about rendering new component 

### ISSUE THREAD

**Issue by jmickvs** [driftyco/ionic#7853]
Hello all, I have an issue abour rendering new components in the current view, my case is the next, suppousing that i have the next view

![screenshot_20160824-101040](https://cloud.githubusercontent.com/assets/15081575/17936734/61cb1022-69e5-11e6-9c38-7c2fceaa15ad.png)

when I lost internet connection, I display a label in the header, between searchbar and red buttom. Then in the moment when I display the label "No hay conexion", the header overlap the content bellow of header

![screenshot_20160824-101050](https://cloud.githubusercontent.com/assets/15081575/17936843/c4309d90-69e5-11e6-98de-23a44375cad0.png)

but when I change to tab "Generales" and i return to tab "Chats" , the view is displayed correctly

![screenshot_20160824-101103](https://cloud.githubusercontent.com/assets/15081575/17936927/0862f634-69e6-11e6-9e86-cd73ef68d351.png)

I hope you can help me, thank you.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This comment https://github.com/driftyco/ionic/issues/7706#issuecomment-239721782 shows the correct way to do this. Thanks for using Ionic!

**Comment by jmickvs** [comment]
:smile: :+1:  it works, thank you.

**Comment by jgw96** [comment]
No problem at all!

**Comment by jmickvs** [comment]
Hello again, the previous trouble happened in android devices now i have a same trouble but now happens in ios devices, when I add a new element/component within header, the new component is overlap to searchbar that is there default, i don't know if i need do something like the resize method of ion-content for ion-header.

![img_0318](https://cloud.githubusercontent.com/assets/15081575/17982513/ac027570-6acd-11e6-9b81-e6b67fd8aae8.jpg)
![img_0319](https://cloud.githubusercontent.com/assets/15081575/17982514/ac06445c-6acd-11e6-9812-6646720b989e.jpg)


Other case is that the new component push up the searchbar but never resize the ion-header and ion-content. 

![img_0316](https://cloud.githubusercontent.com/assets/15081575/17980007/fb29b916-6ac2-11e6-959e-070c1749a77c.jpg)
![img_0317](https://cloud.githubusercontent.com/assets/15081575/17980008/fb2cd2cc-6ac2-11e6-9b2c-356d0a0f23a3.jpg)

Like extra information, recently I update my project to ionic2 beta 11

I hope you can help me, thank you
