### ISSUE TITLE
Windows 7: Maximum Call stack size exceeded

### ISSUE THREAD

**Issue by EddyTheDove** [driftyco/ionic#7855]
**Range Error: Maximum call stack sized exceeded**
Occurs on the terminal on `ionic serve`
ionic 2.0.0-beta.37

####Please refer to screenshot for more details

![capture](https://cloud.githubusercontent.com/assets/8747601/17952119/082b920a-6aab-11e6-81d1-c680a9579e2a.PNG)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1312

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Because this was an issue with the ionic cli and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
