### ISSUE TITLE
LoadingController and ActionSheetController breaking each other 

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#7856]
#### Functionality I want to achieve:
- Show Loading
- Do some async work
- dismiss Loading and show ActionSheet

#### Short description of the problem:
 
**loading.dismiss() not working in _beta 11_, it was working in _beta 10_**

![loading-actionsheet](https://cloud.githubusercontent.com/assets/8744282/17952286/e53363dc-6a1d-11e6-9fa0-de072d7e9367.png)

#### What behavior are you expecting?
- Expected loading dismiss before ActionSheet present

**Steps to reproduce:**
Run following code from some button click. It will show loading, then actionsheet with loading in background and you can cancel actionsheet but loading  will still be in background

```
 let loading = this.loadingCtrl.create({
      content: 'Loading data...',
      duration:5000
    });
    loading.present();

    setTimeout(()=> {
      loading.dismiss();
      let actionSheet = this.actionSheetCtrl.create({
        title: "Select me",
      });

      actionSheet.addButton({
        text: "first",
        handler: ()=> {
          console.log('first');
        }
      });
      actionSheet.addButton({
        text: 'Cancel',
        role: 'cancel',
        handler: () => {}
      });
      actionSheet.present();
    }, 2000);
```

**Other information:** 
Using setTimeout to mimic async function call

**Which Ionic Version?** 
Ionic 2 beta 11

#### Plunker that shows an example of your issue
**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview
Plunker uses beta 10, couldn't modify it to use beta 11 correctly

**Run `ionic info` from terminal/cmd prompt:** 

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because all of our navigation is async you have to use the promises that `dismiss()` returns when doing two transitions at once. Here is an example of your code that uses these promises and works: 

```
let loading = this.loadingCtrl.create({
      content: 'Loading data...',
      duration:5000
    });
    loading.present();

    setTimeout(()=> {
      let actionSheet = this.actionSheetCtrl.create({
        title: "Select me",
      });

      actionSheet.addButton({
        text: "first",
        handler: ()=> {
          console.log('first');
        }
      });
      actionSheet.addButton({
        text: 'Cancel',
        role: 'cancel',
        handler: () => {}
      });
      
      loading.dismiss().then(() => {
        actionSheet.present();
      });
    }, 2000);
```
Thanks for using Ionic!

**Comment by aggarwalankush** [comment]
Hi @jgw96 

Thanks for the response. Now the behavior is after timeout of 2000ms, loading dismiss and then actionsheet displays and then actionssheet **automatically dismiss without clicking** after 2000ms.


![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/8744282/17979052/a66bbf60-6aad-11e6-87ab-f6517fb4ff7b.gif)

**Comment by jgw96** [comment]
Hello! Can you try 
```
loading.onDidDismiss(() => {
  actionSheet.present()
})
```
Thanks!

**Comment by aggarwalankush** [comment]
@jgw96 Thanks for the quick response. It isn't working. loading dismiss now waits for 5000ms set in loadingCtrl.create method and then shows actionsheet

**Comment by jgw96** [comment]
No problem! That is the correct behavior that i would expect from the above logic. Are you wanting to dismiss the loading component after a certain amount of time and then show the actionsheet?

**Comment by aggarwalankush** [comment]
@jgw96 

Functionality I want to achieve:

Show Loading
Do some async work
dismiss Loading and show ActionSheet

**Comment by jgw96** [comment]
Ahh ok. So to do this instead of putting a duration on your loading component you would call `loading.dismiss()` after your async work was done.
