### ISSUE TITLE
White Screen on IOS after splash only for the very first time

### ISSUE THREAD

**Issue by soulbeing** [driftyco/ionic#7857]
#### Short description of the problem:
My app is already published on AppStore and GooglePlay, You can download on both devices, and you will see there is a white screen after splash on IOS for the first time. But everything works fine from the second time. Search "EnglishEveryday" to download please, it's the easiest way to check what I am talking about here.

Another side problem is, every time when I try to login "https://forum.ionicframework.com/", I got "There is a problem with your account. Please contact the site's administrator.", can someone fix this for me? My account is   jiangxin87@qq.com

**Comment by soulbeing** [comment]
My fault, sorry!!

**Comment by finalxcode** [comment]
@soulbeing the issue "you will see there is a white screen after splash on IOS for the first time", have you resolved this issue?
