### ISSUE TITLE
ion-input placeholder doesn't work with core-js

### ISSUE THREAD

**Issue by gustavohenke** [driftyco/ionic#7858]
#### Short description of the problem:
When using `core-js` shims without/instead of `reflect-metadata`, the placeholder of an `ion-input` is empty.  

I couldn't verify this issue when in this [Plunker demo](http://plnkr.co/edit/styk24wiNfSHZGjNYbyc?p=preview).
My local build is Browserify, just like the Ionic Preview App which suffers this issue too.

#### What behavior are you expecting?
I expected the placeholder to be there, without needing to include `reflect-metadata` as well.

`core-js` already provides the same set of features as `reflect-metadata`. 

**Steps to reproduce:**
1. Get up and running with the [Ionic Preview App](https://github.com/driftyco/ionic-preview-app)
2. Install core-js: `npm i core-js`
3. Manually copy `node_modules/core-js/client/core.js` to `www/build/js`
4. In `www/index.html`, modify the `src` attribute from `build/js/Reflect.js` to `build/js/core.js` 
5. Go to the "Placeholders" demo
6. Profit.

**Which Ionic Version?**
2.x

**Run `ionic info` from terminal/cmd prompt:**
```
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.4.0


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately, at the moment we only recommend that you use the `reflect-metadata` package as your polyfills. `reflect-metadata` is the polyfill that Ionic 2 is currently built to work with and we cannot officially support using `core-js` at this time. Thanks for using Ionic!

**Comment by gustavohenke** [comment]
Okay, I already added it back to my `package.json`.
I thought about staying with just `core-js` as it's all-in-one, includes various polyfills.

**Comment by jgw96** [comment]
Hello! I reopened this issue as we are going to upgrade to core.js when our new build process comes out (should be beta.12) and when i was testing i noticed that placeholders seemed to be working fine for me. core-js does not polyfill decorators, which is what reflect-metadata polyfills, so im not sure how your app was even loading without reflect-metadata. Also, core-js is meant to replace es6-shim. Would you mind re-testing with keeping reflect-metdata and then replacing es6-shim with core-js?

**Comment by gustavohenke** [comment]
Actually, `node_modules/core-js/client/core.js` does include the full set of features, what "includes" `reflect-metadata`.

Check [the plunker demo I posted previously](http://plnkr.co/edit/styk24wiNfSHZGjNYbyc?p=preview).
It uses only `core-js` and it works just fine.

I don't understand why I can't get it to work when I test it with Ionic preview app... maybe Browserify issues?

**Comment by jgw96** [comment]
Hello after much testing I cannot seem to reproduce this issue with any of my test apps. Most likely this is due to your browserify build, our new build that is gonna be part of beta.12 is all webpack 2, so this should fix your issue. Thanks for using Ionic!
