### ISSUE TITLE
feat: Transparent status bar on Android

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#7864]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>To let ionic have native ux it's should have partly transparent status bar like in every Material Design app.
Some points:
1. The status bar isnt completely transparent its kinda 20% darker
2. When you open side menu or something like that the status bar will have the navbar background and the background of the top of the side menu just like ionic on IOS or any MD native app

It is possible feature?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This is actually currently possible with the [Ionic Native statusbar module](http://ionicframework.com/docs/v2/native/status-bar/). Thanks for using Ionic!

**Comment by MatanYed** [comment]
@jgw96 which function should i use?

**Comment by cmaart** [comment]
Well, actually it can't from what I see..
