### ISSUE TITLE
Have navigation trying to disable open screen navigation

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#7865]
I have navigation so each time i san click on same navigation i want to stop this.
 have not found any solution.

```
navigate(page){
    console.log(this.nav.getActive(), this.nav.isActive(this.nav.first()));
    let that = this;
    this.menu.close().then(function(e){
      that.nav.push(page);
    });
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
