### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'scrollCtrl.scrollView.__scrollTop')

### ISSUE THREAD

**Issue by gmaggini** [driftyco/ionic#7866]
#### Short description of the problem:

Ionic 1.3.1 app on iOS displays following error on console when scrollview reaches the top. Once this error is triggered, it keeps spamming the console at every scroll. Also, when triggered while holding a table view down, the view remains stuck. 

```
[FATAL] [NONE] Uncaught Exception: TypeError: undefined is not an object (evaluating 'scrollCtrl.scrollView.__scrollTop') at (compiled_code):63197
```

**Steps to reproduce:**
1. 
2. 
3. 
(will update the issue if necessary)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Forum link with same issue: https://forum.ionicframework.com/t/ioncontent-onscrollcomplete-undefined-is-not-an-object/56120 

**Which Ionic Version?** 1.x or 2.x
Ionic 1.3.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to provide a repo that i can use to reproduce this issue? Thanks!

**Comment by gmaggini** [comment]
Hi @jgw96 sorry for the late reply. I made a repo for you to test the issue: https://github.com/gmaggini/scrollview-bug-ionic-sample

Looking forward to your feedback!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#104
