### ISSUE TITLE
Please make VirtualScroll dynamic

### ISSUE THREAD

**Issue by dgroh** [driftyco/ionic#7869]
#### Short description of the problem:

We have a list of items and when an item gets clicked a buttonbar shows up, like gif below:

![sample](https://cloud.githubusercontent.com/assets/16785357/17973595/55500524-6ae3-11e6-873f-ed98c426bf63.gif)

VirtualScroll makes the items `position:absolute` which causes the buttonbar area not to get resized and to overlap the item just below. See the gif below for the difference: 

![sample2](https://cloud.githubusercontent.com/assets/16785357/17973891/5bdb7b98-6ae4-11e6-89ec-7ba83b4bd047.gif)
#### What behavior are you expecting?

I'm expecting to have a function like `resize()` to recalculate/resize the VirtualScroll when the items are dinamically rendered.

**Which Ionic Version?** 2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

> Cordova CLI: 6.2.0
> Gulp version:  CLI version 3.9.1
> Gulp local:
> Ionic CLI Version: 2.0.0-beta.32
> Ionic App Lib Version: 2.0.0-beta.18
> OS: Node Version: v4.5.0

**Comment by paunadeu** [comment]
+1, it's needed. I thinks @manucorporat can solve this...

**Comment by zakton5** [comment]
+1

**Comment by hozkok** [comment]
+1, I have `*ngIf` inside `*virtualItem` which is not rendered properly due to `position: absolute;`

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! Is this still an issue in RC4?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
