### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Aditya-app-dev** [driftyco/ionic#7871]
Hi,

Why am i getting this error?

![error](https://cloud.githubusercontent.com/assets/12525050/17976719/4ebb5f96-6b0c-11e6-837a-6537803c0903.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Most likely you are getting this error because there is a typescript error in your project that is causing the app bundle not too build. Would you mind checking your terminal for the output of the ionic cli and see if there is a typescript error? Thanks!

**Comment by Aditya-app-dev** [comment]
Thanks @jgw96, You solved my issue there was a typescript error and i solved it.
