### ISSUE TITLE
ionic2 - feature(alert) - Add optional search bar input to checkbox/radio alerts

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#7873]
I think it would be a great idea to add a parameter for an optional search bar in select alerts. This would be very useful when searching through very large lists for a single/multiple value(s) that you want to select. The search text would examine each options display label for that value.

This behavior could be achieved by implementing a custom modal with all the required things, but that's tedious and the select has literally everything needed except for a search bar.

**Comment by Luchillo** [comment]
I would love to have this, i had to make my own into a modal so i could add searchBar and a search pipe.

**Comment by jgw96** [comment]
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by tanzeelrana** [comment]
has anyone implemented this yet ?

**Comment by Luchillo** [comment]
As i said, making a modal for this seems like the only way, as for the Ionic staff, idk, maybe there's a whole list of TODOS before this.

**Comment by zakton5** [comment]
I will happily implement this myself if that's okay with the ionic team. @manucorporat @jgw96

**Comment by Luchillo** [comment]
Until @zakton5 make one (if allowed by staff) anyone needing this can use a modal, since it works kind of like a page.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#59

**Comment by zakton5** [comment]
@jgw96 That link no longer works. Do you mind updating it?

**Comment by zakton5** [comment]
@jgw96 @brandyscarney Just wanted to notify you all that I am going to make a PR for this feature, as it seems to have been lost.

**Comment by zakton5** [comment]
Also, please reopen this when you get a chance
