### ISSUE TITLE
AlertController: possibility to add <ion-icon> in message parameter

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#7874]
When createing an AlertController object:

```
let alert = this.alertController.create({
   title: "My title",
   message: 'Some message'
});
```

it would be great if we could add an ion-icon in the message, like this:

```
let alert = this.alertCtrl.create({
    title: this.translate.instant("tos.title"),
    message: '<ion-icon name="add-circle"></ion-icon>some text'
});
```

the ion-icon is removed (not rendered). First I thought the framework was removing html markup, but html standard tags (h1, h2, p, etc...) are not.

**Comment by jtushar53** [comment]
Also Toast can have icons, maybe some thing like 
```
let toast = this.toastCtrl.create({
              message:'message',
              icon : "information"
            });
```

or may be the approach  like OP

**Comment by yurik94** [comment]
👍 +1... this should be a really nice to have!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#173

**Comment by MvRemmerden** [comment]
The place you moved it to is not available anymore. Any chance to see the progress or get some indication of the very rough expected timeline?

**Comment by yurik94** [comment]
Any news?

**Comment by mohamedsharaf** [comment]
+1

**Comment by HenriqueJRech** [comment]
+1

**Comment by hiepxanh** [comment]
please open this issue, your link not working @jgw96

**Comment by martenwallewein** [comment]
+1

**Comment by Elioterio89** [comment]
+1

**Comment by LaloCastilla** [comment]
+1

**Comment by Vishwa17** [comment]
Is it possible to apply icons in alert controller inside button ?

**Comment by victorhugorch** [comment]
+1

**Comment by trmichaelmanlulu** [comment]
+1
