### ISSUE TITLE
how can i back 2 or more pages.

### ISSUE THREAD

**Issue by Liubei1993** [driftyco/ionic#7878]
ionic2@beta 37.

page1->page2->page3->page4

Hello.I want to back page2 at once, and with some parameters. Not use setRoot,how can i do it.

Thanks.

**Comment by dylanvdmerwe** [comment]
How would you accomplish something like this in a native app?

**Comment by Kobzol** [comment]
You can use the `remove` method of NavController (http://ionicframework.com/docs/v2/api/components/nav/NavController/#remove).
```javascript
this.nav.remove(this.nav.length() - 2, 2);
```
This basically removes 2 pages starting from the second-to-last page (page3 in your example) and page2 will be left active.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com). Also, @Kobzol 's solution is solid and is the correct way to do this. Thanks for using Ionic!

**Comment by Liubei1993** [comment]
@Kobzol thank you.

**Comment by Liubei1993** [comment]
@jgw96 well,thank you.
