### ISSUE TITLE
present() missin in AlertController and LoadingController

### ISSUE THREAD

**Issue by bsakweson** [driftyco/ionic#7879]
I updated to beta11 after noticing some issues with Alerts. I follow the documentation on this page but ran into this error for both AlertController `Property 'present' does not exist on type 'AlertController'.` and LoadingController `Error TS2339: Property 'present' does not exist on type 'LoadingController'.

Here is the class declaration for AlertController
```Typescript
serveSuccessAlert() {
    let alert = this.alertController.create({
      title: this.translate.instant("signup.alerts.successful.title"),
      message: this.translate.instant("signup.alerts.successful.message"),
      buttons: [{
        text: this.translate.instant("signup.alerts.successful.button"),
        role: "cancel",
        handler: () => {
          this.nav.push(LoginPage);
        }
      }]
    });
    this.alertController.present();
  }```

I am seeing the same behavior for Loading, same message `Error TS2339: Property 'present' does not exist on type 'LoadingController'.`

```let loading = this.loadingCtrl.create();
      this.loadingCtrl.present();```

Am I missing something, if so could you let me know what I am missing?

**Comment by pedropapa** [comment]
Just use alert.present() or loading.present()

**Comment by bsakweson** [comment]
I believe that is what I am using,

```this.loadingCtrl.present(); and this.alertController.present();```

**Comment by pedropapa** [comment]
@bsakweson No, you are using the present() method from the service, you should use this method from the Alert instance (that is returned from AlertController.create), not the AlertController.

**Comment by jgw96** [comment]
Hello @bsakweson ! Thanks for using Ionic! You can take a look at our docs for [alert](http://ionicframework.com/docs/v2/components/#alert) for an example of how to present overlay components. You should use the `present` method on the instance of the overlay component and not on the service. Thanks!

**Comment by bsakweson** [comment]
I got it working thanks
