### ISSUE TITLE
bug: blank template livereload fails to load

### ISSUE THREAD

**Issue by wohanley** [driftyco/ionic#7885]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Working on OSX, I create a project with `ionic start myapp blank`. It runs fine in a browser with `ionic serve` or on a device with `ionic run ios`, but `ionic run ios -l` will cause the app to hang at the splash screen. GapDebug reports an error fetching network resources. If I add `<allow-navigation href="*"/>` to config.xml, then livereload works fine. I'm not sure if it would be more appropriate to change the default cordova-plugin-whitelist configuration or to add a note to the documentation reflecting the need to do it yourself, but right now the simplest way I can imagine trying to get livereload working (`ionic start myapp blank` and `ionic run -l`) fails out of the box for a reason that isn't at all obvious.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1315

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue with the cli and not the framework i have moved this issue to the cli repo. Thanks for using Ionic!

**Comment by wohanley** [comment]
Thank you!

**Comment by jgw96** [comment]
No problem!
