### ISSUE TITLE
[Suggestion] allow to put some images in ion-option and ion-select

### ISSUE THREAD

**Issue by goldenbearkin** [driftyco/ionic#7889]
Realise that the ion-select and ion-option are only allowed to put text, it would be awesome if img is allowed to put aside the text. The form now created by ionic2 looks pretty dry and monotonic.

<img width="276" alt="screen shot 2016-08-27 at 7 56 37 pm" src="https://cloud.githubusercontent.com/assets/11225712/18027486/444b3f72-6c97-11e6-85e6-f733d82f9f78.png">

**Comment by poguez** [comment]
@goldenbearkin is there any other way to do it?

**Comment by thebasix** [comment]
@jgw96 What is the status on this?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#172

**Comment by rebelholic** [comment]
@jgw96 lol "error 404" after clicked

**Comment by lluisnieto** [comment]
What a fail. Only text, no html.. People definetly needs this to work.

**Comment by dalepo** [comment]
this should be a feature imo

**Comment by olafahn** [comment]
Any improvements?

**Comment by pablogarciamiranda** [comment]
Any updates on this feature request?

**Comment by vintots** [comment]
Any updates on this ?

**Comment by christopheelkhoury** [comment]
@jgw96 any updates on this?

**Comment by mhartington** [comment]
Hi everyone! This feature has not been added to the framework. As 3.x is feature complete, we're putting all of our efforts into 4.0.


If you'd like to submit a PR to add this feature, we'd happily go over it with you. 
Thanks!
