### ISSUE TITLE
Black Screen between page transition when using Toast

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#7890]
#### Short description of the problem:
Black screen appears in between page transition if there is some toast

#### What behavior are you expecting?
Normal behavior, toast should not interfere with NavController.push

**Steps to reproduce:**
1. Present Toast when modal is closed
2. Push new page
3. Have a look at this commit https://github.com/aggarwalankush/ionic-inappbrowser-issue/commit/33d7de09f6f4cf278c04eb65be304103656d4d63 

**Which Ionic Version?** 
Ionic 2 - beta 11, worked fine in beta 10

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.0
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014

<img src="https://cloud.githubusercontent.com/assets/8744282/18028477/78b40a94-6c35-11e6-92cb-d7dc0b9416b2.gif" width="250"/>

**Comment by gigocabrera** [comment]
There are several issues with similar behavior:

1. #6677 
2. #6540 
3. #7564 

There may be others but these are the ones I'm familiar with. Some of these issues have been closed but it is clear that the black screen behavior is still there

**Comment by aggarwalankush** [comment]
Seems like many people are facing this issue but doesn't seem a priority for ionic team. I'm also eagerly waiting for beta 12 rather than fix for this issue :P

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, and sorry for the delay on this one. @aggarwalankush Do you get any console errors when this happens? Also can you try setting `dismissOnPageChange` to true inside `ToastController.create()` and test again? Thanks!

**Comment by aggarwalankush** [comment]
Adding `dismissOnPageChange` has no effect.

```
let toast = this.toastCtrl.create({
      message: "Filters applied successfully",
      duration: 3000,
      dismissOnPageChange: true
    });
toast.present();
```

**Comment by jgw96** [comment]
Hmm, do you get any console errors when this happens?

**Comment by aggarwalankush** [comment]
no console errors, I think it might be css issue as toast has black background, might be it's responsible for black screen.

**Comment by jgw96** [comment]
Interesting, thanks for all the testing. Beta.12 has some changes coming to how navigation works which may solve this. I am going to re-test this issue as soon as we start internally testing beta.12 and will keep you updated.

**Comment by aslamj** [comment]
I've started seeing samw issue with a LoadingController getting dismissed and then the NavigatioinController being pushed. This worked fine in versions before beta11. Looks very bad on iOS. Hoping to get this fixed in fix in beta12.

**Comment by danielcrk-cn** [comment]
I'm seeing this with the LoadingController (which unfortunately forced me to create my own). I trigger (present) the loader from the root class, and while it is showing, all page transitions behave lite in the gif above. No console errors and no other problems, just a black screen before the transition.

**Comment by aggarwalankush** [comment]
Can't reproduce in RC0

**Comment by himalayaahuja** [comment]
I see the same issue when transitioning between pages in ios , especially the page which is not lazy loaded.
