### ISSUE TITLE
no exported member 'SecureStorage'

### ISSUE THREAD

**Issue by endriazizi** [driftyco/ionic#7892]
Hello there!

I am using cordova secure storage on my ionic 2 app,

I got this error:

TypeScript error: /Users/endriazizi/Documents/Project/app/app/pages/oauth/oauth.
service.ts(7,10): Error TS2305: Module '"/Users/endriazizi/Documents/Project/app
/node_modules/ionic-native/dist/index"' has no exported member 'SecureStorage'.                 
TypeScript error: app/app.ts(12,10): Error TS2305: Module '"/Users/endriazizi/Documents/Project/
app/node_modules/ionic-native/dist/index"' has no exported member 'SecureStorage
in my package.json:

"cordova-plugin-facebook4",
"cordova-plugin-device@~1.1.2",
"cordova-plugin-console@~1.0.3",
"cordova-plugin-whitelist@~1.2.2",
"cordova-plugin-statusbar@~2.1.3",
"ionic-plugin-keyboard@~2.2.1",
"cordova-plugin-splashscreen@~3.2.2",
"cordova-plugin-secure-storage@~2.4.1",
"cordova-plugin-inappbrowser@~1.4.0",
"cordova-plugin-geolocation@~2.2.0",
"cordova-plugin-facebook4@~1.7.1"

I don't know what to do

Can someone help me?
<img width="719" alt="screen shot 2016-08-27 at 19 00 52" src="https://cloud.githubusercontent.com/assets/9431994/18028879/0a495db2-6c89-11e6-8ce7-b0f785fa2fde.png">

**Comment by devarg** [comment]
Hi @endriazizi which version of ionic-native are you using on your package.json? Consider updating to version 1.3.20 that's the latest which include SecureStorage, previous versions might not have the dependency you are trying to install.

1.  Update ionic-native dependency on your package.json to `"ionic-native": "1.3.20"` and save it
2.  Close VS Code
2.  Open cmd/terminal with admin rights
3.  Navigate to your project root
4.  Run `npm install` and make sure no red messages pop it should respond something similar to this
 `testproj@ c:\Users\devarg\Documents\dev\TestProj\app-ui
`-- ionic-native@1.3.20
`
5. Reopen VS Code and check that your import now should not be red-marked.

Let me know if you have any other issues.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#504

**Comment by jgw96** [comment]
Hello all! As this is an issue with Ionic Native and not the Ionic framework I have moved this issue over to that repo. Thanks for using Ionic!
