### ISSUE TITLE
Button's text disappears after clicking 

### ISSUE THREAD

**Issue by softhorizons** [driftyco/ionic#7893]
#### Short description of the problem:

Text on button disappears after clicking on it. Only occurs on Android in landscape mode, with button in the rightmost column of a 2-column setup.
#### What behavior are you expecting?

Text should remain.

**Steps to reproduce:**
1. Create page as shown below.
2. Click on one of the 2 buttons.
3. Observe that text disappears on rightmost button.

```
<ion-content class="page3" #pagecontent>
  <div style="column-count: 2">
    <div><button>AAAA</button></div>
    <div><button>BBBB</button></div>
  </div>
</ion-content>
```

**Other information:**
Android only, Landscape only. Occurs in Chrome mobile emulator e.g. Nexus 5X.

![beforeclick](https://cloud.githubusercontent.com/assets/8432690/18029222/26cb86aa-6c47-11e6-91e3-653acd48658b.png)
Before click

![afterclick](https://cloud.githubusercontent.com/assets/8432690/18029221/26ca4790-6c47-11e6-97a5-1a388828275a.png)
After click

**Which Ionic Version?** 2.x beta11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately I am unable to reproduce this issue. Could you make a repo that I could use to reproduce this issue?

**Comment by softhorizons** [comment]
The Plunker linked by this issue-reporting form is for beta 10. Can you supply a beta 11 link?

Also, it would be helpful for others to update the new-issue form with that link.

**Comment by jgw96** [comment]
@softhorizons Unfortunately at this time we are having some issues with the plunker related to npmcdn. Sorry about that!

**Comment by softhorizons** [comment]
I expect this is a messy browser issue. On my Nexus 5X emulator (see platform specifics below) in landscape mode, the text disappears after clicking it the first time. Same problem on a physical Galaxy S3, but now that I added Crosswalk (nothing else changed), the rightmost button just doesn't show up in the first place when in landscape mode!

Looking at the CSS, I see that `.button {position: relative}`. Changing the button's style to `position: static` fixes the problem completely in all cases above. Also, just for grins, I temporarily disabled the `column-count: 2` that I'm using; problem also went away. I'm guessing that the 2 different versions of the browser have a bug related to `position: relative` when combined with `column-count`, and the button is in the rightmost column. Is relative positioning really needed on `.button`, maybe just get rid of it, or enhance the selector to not use it in column mode if you're feeling fancy?

Emulator platform details:
Google Chrome	52.0.2743.116 (Official Build) m (32-bit)
Revision	9115ecad1cae66fd5fe52bd9120af643384fd6f3-refs/branch-heads/2743@{#728}
OS	Windows 
Blink	537.36 (@9115ecad1cae66fd5fe52bd9120af643384fd6f3)

**Comment by softhorizons** [comment]
The more-specific reason for the first issue (missing text) is a chrome bug where the `style = "translateZ(0)"` on the ion-button-effect triggers h/w acceleration and a known Chrome bug : https://github.com/fgnass/spin.js/issues/252 The irony is that is suspect the translate is there to work around another bug related to column-relative positioning, but ( seem to have read there may be other workarounds to that older issue.

As for the button not showing up at all on Crosswalk, the fix still seems to be `position: relative`.

**Comment by jgw96** [comment]
Hello @softhorizons , are you still seeing this issue with Rc4 ?

**Comment by softhorizons** [comment]
Sorry, no info to contribute. I hopped off from Ionic 2 a few months ago. Crosswalk requirement was a deal breaker for my product/market.
