### ISSUE TITLE
ionic 2: Space between ion-items in dynamic generated ion-list

### ISSUE THREAD

**Issue by ungular** [driftyco/ionic#7894]
How to remove space between list-items, in dynamic generated list as following:

```
	<ion-list *ngFor="let a of [{name: 'AAA'},{name: 'BBB'}]">
		<ion-item>
			{{a.name}}
		</ion-item>
	</ion-list>
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
