### ISSUE TITLE
Swipe right gesture for Menu doesn't work on Galaxy S3

### ISSUE THREAD

**Issue by softhorizons** [driftyco/ionic#7895]
#### Short description of the problem:
Sliding right on a page with a Menu works very poorly on a physical Galaxy S3 (Android 4.2.2). Usually swiping doesn't do anything at all, but sometimes parts of the menu flash on/off. Clicking on menu icon works fine, just not the slide gesture. Not an issue on emulator.

#### What behavior are you expecting?
Menu should slide out smoothly.

**Steps to reproduce:**
1. Swipe right on physical Galaxy S3, probably others.
2. Observe sliding action or lack thereof.

```
<ion-header>
  <ion-navbar>
    <button menuToggle><ion-icon name="menu"></ion-icon></button>
    <ion-title>Welcome!</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding class="welcome-page">
  <h2><ion-icon name="finger-print"></ion-icon> Swipe right to get started</h2>
</ion-content>
```

**Which Ionic Version?** 2.x beta11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.5

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Are you using Crosswalk with your app?

**Comment by softhorizons** [comment]
No. Is that recommended?

**Comment by jgw96** [comment]
Yep, for Ionic 2 we recommend Crosswalk for any version of Android older than 4.4.4. As using Crosswalk will fix this issue i am going to be closing this for now. Also, their is an issue open on the docs repo to add this to the v2 docs as at the moment they are only on the v1 docs. Thanks for using Ionic!
