### ISSUE TITLE
Feature request : Datepicker in Alert

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#7896]
#### Short description of the problem:

`checkbox`, `radio` and text input are all possible in Alert, only `datetime` is missing.

**Which Ionic Version?** 2.x

**Comment by javasol** [comment]
Would like to see this as well.

**Comment by russcarver** [comment]
Need this too!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#162

**Comment by karthikrp** [comment]
@jgw96 The link is broken.
Is there a new thread/issue or should this be reopened?

**Comment by kensodemann** [comment]
@karthikrp - link is not broken (just checked it), it is just to a private repo. Was there something you wanted to add to the request? I can update it for you if so.

**Comment by karthikrp** [comment]
Oh, I was getting a 404 error. Nothing, just wanted to follow the issue.

**Comment by darkguy2008** [comment]
Me too. Is this implemented in v3?

**Comment by seiwonlee** [comment]
i still don't see it in V3...any news?
