### ISSUE TITLE
feat: Expose swiper api on ion-slides

### ISSUE THREAD

**Issue by doronnac** [driftyco/ionic#7897]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was asked to create a carousel, which is similar to ion-slides but with multiple slides visible at a time.

The only viable option currently is to download and import swiper again and make my own component, which is silly.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue will be solved with this issue https://github.com/driftyco/ionic/issues/6198 I will be closing this as a duplicate. Thanks!
