### ISSUE TITLE
Problem setting certain item in select option from object collection.

### ISSUE THREAD

**Issue by yogi2806** [driftyco/ionic#7898]
Short description of the problem:
I am facing 2 problems while using "select" in ionic which is working properly when i tried only using angularjs. 
1. Initially i am setting array of 1st index to select which is coming blank.
2. I am trying to update array by splicing and trying to update select which is again bringing me blank select option.

What behavior are you expecting?
2 problems i am expecting respective array item to be selected which is given through controller.

**Steps to reproduce:**
1.  At start when u run the app we get blank select option.
2. The other problem can be seen by deleting any item and other default item to be selected.

Code Snippet:

.controller('DashCtrl', function($scope) {

```
$scope.options = [{name: 'var1',id: 1}, { name: 'var2', id: 2}, {name: 'var3',id: 3}];
$scope.yourSelect = $scope.options[0];

$scope.delete = function() {
  //  alert("Clciked");
  $scope.Deleted = $scope.options.splice(1,1);
  $scope.yourSelect = $scope.options[0];
    alert( $scope.yourSelect.name);
}

$scope.changed = function(yourSelect) {
    alert( $scope.yourSelect.name);
  }
```

})

**For Ionic 1 issues** - http://plnkr.co/edit/ZriDlmQL8VPRdk1NnDNa?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v5.6.0

**Comment by yogi2806** [comment]
@Ionitron Please help me out on this. Thanks in advance

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#103
