### ISSUE TITLE
webkit-text-security: disc duplicated after upgrading to beta.11

### ISSUE THREAD

**Issue by rockertux** [driftyco/ionic#7899]
#### Short description of the problem:

After upgrading to beta 11, my `ion-input type="tel"` password-styled field started to behave strangely. It displays a fixes-length row of discs below my input area. It disappears when `-webkit-text-security: disc` is disabled.

`-webkit-text-security: disc`
![tel password empty](https://cloud.githubusercontent.com/assets/865413/18049635/e0a1e028-6dbf-11e6-8652-e4bc06d64ac4.png)
![tel password](https://cloud.githubusercontent.com/assets/865413/18049577/887357f6-6dbf-11e6-95bf-34e9fd1beda1.png)

`-webkit-text-security: initial`
![image](https://cloud.githubusercontent.com/assets/865413/18049672/181b5868-6dc0-11e6-969e-ca65e5ed3fa7.png)
![image](https://cloud.githubusercontent.com/assets/865413/18049695/2cc99626-6dc0-11e6-87cb-eb02fd1edbfd.png)
#### What behavior are you expecting?

An input field without that row of discs.

**Steps to reproduce:**
1. Style a `ion-input type="tel"` field with `-webkit-text-security: disc`

```
<ion-item>
  <ion-label stacked>Senha de acesso</ion-label>
  <ion-input pattern="\d{4}" type="tel" class="password" formControlName="password"></ion-input>
</ion-item>

.password {
  -webkit-text-security: disc;
}
```

**Other information:**
Happens both with old and new forms module.

**Which Ionic Version?**
2.0 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID: LinuxMint Description:  Linux Mint 17.1 Rebecca 
Node Version: v4.5.0

**Comment by kwv** [comment]
I encountered this too. As a work around, specify a descendant selector on the input that Ionic adds

```
<ion-input class='masked' autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" formControlName="password" type="number" pattern="[0-9]*" required></ion-input>
```

```
 .masked input {
  -webkit-text-security: disc;
}
```

**Comment by jgw96** [comment]
Hello! Are you all seeing this in chrome or safari?

**Comment by rockertux** [comment]
Chrome and Crosswalk

**Comment by jgw96** [comment]
Going to close this issue for now as I can not reproduce with rc5. Thanks for using Ionic!
