### ISSUE TITLE
Ionic 2: When are two selects on same page works only one(the second)

### ISSUE THREAD

**Issue by ungular** [driftyco/ionic#7902]
If I add two ion-selects on the same page and try to open the first, opens the second and I can't change value in first select

my code:
```
<ion-select>
	<ion-option value="1">AAA</ion-option>
	<ion-option value="2">BBB</ion-option>
	<ion-option value="3">CCC</ion-option>
</ion-select>
<ion-select>
	<ion-option value="a">XXX</ion-option>
	<ion-option value="b">YYY</ion-option>
	<ion-option value="c">ZZZ</ion-option>
</ion-select>
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind wrapping each `ion-select` in its own `ion-item` and testing again?

**Comment by ungular** [comment]
Yes, so it works well, this means that ion-select must be used only wrapped in ion-item? 
What if I want to use ion-select in grid/row or div?

**Comment by jgw96** [comment]
Yep, so as the docs show [here](http://ionicframework.com/docs/v2/components/#select) components such as select are meant to be wrapped in `ion-item`. A component wrapped in `ion-item` should work fine in `ion-grid`. I can not recommend that you wrap the `ion-select` in a div. While that may work, wrapping it with `ion-select` will assure that there are no css scoping issues. Thanks!

**Comment by ungular** [comment]
I need such a structure without any border line, how to do to achieve this?

```
<ion-grid>
  <ion-row>
     <ion-col width-30>
          <ion-label>Select1:</ion-label>
     </ion-col>
    <ion-col width-70>
           <ion-select>
                 <ion-option value="1">AAA</ion-option>
                 <ion-option value="2">BBB</ion-option>
                 <ion-option value="3">CCC</ion-option>
           </ion-select>
     </ion-col>
   </ion-row>
    <ion-row>
         <ion-col width-30>
               <ion-label>Select2:</ion-label>
         </ion-col>
         <ion-col width-70>
            <ion-select>
               <ion-option value="a">XXX</ion-option>
               <ion-option value="b">YYY</ion-option>
               <ion-option value="c">ZZZ</ion-option>
             </ion-select>
        </ion-col>
  </ion-row>
</ion-grid>
```

**Comment by jgw96** [comment]
Hello @ungular , you should be able to do this with some custom css. I would recommend asking around on our [forums](https://forum.ionicframework.com/). Thanks!
