### ISSUE TITLE
Links not following when highlighted by ChromeVox VoiceReader

### ISSUE THREAD

**Issue by jonzfisher** [driftyco/ionic#7904]
#### Short description of the problem:

When using ChromeVox voice reader and others not following elements with `<a ion-item href="#/app/[route]"></a>`.
#### What behavior are you expecting?

For link to follow to other angular partial.

**Steps to reproduce:**
1. Have two partial views.
2. Have a link to a partial
3. Use Chrome's Voice Reader extension to test if partial link follows.

**Which Ionic Version?** 1.x

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#101

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#102
