### ISSUE TITLE
Update NPM published version

### ISSUE THREAD

**Issue by nicopace** [driftyco/ionic#7905]
#### Short description of the problem: 

The version of ionic v1 published on NPM is outdated

#### What behavior are you expecting?

To see an up to date version of ionic published at https://www.npmjs.com/package/ionic-sdk

**Which Ionic Version?** 1

**Comment by jgw96** [comment]
Hello! The current v1 version of Ionic is on the [ionic-angular](https://www.npmjs.com/package/ionic-angular) package as well as the latest version of Ionic 2. The `ionic-sdk` package is for legacy support. To install the latest version of Ionic 1 you can run `npm install ionic-angular@1.3.1 --save --save-exact`. Thanks!
