### ISSUE TITLE
Ionic cannot use my gulp file in ionic serve mode

### ISSUE THREAD

**Issue by Xarkam** [driftyco/ionic#7911]
With the forced passage from iconic 1.3.1 to 2.0beta my gulpfile is not anymore executed on using `ionic serve`.
I don't have any error in logs.

Can you explain to me how to restart the gulpfile execution on calling `ionic serve` ?

Thanks.

My ionic.config.json
```json
{
  "name": "jcm-next",
  "app_id": "",
  "gulpStartupTasks": [
    "process:sass",
    "process:typescript",
    "process:javascript",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ]
}
```

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.4.0

**Comment by Xarkam** [comment]
Okay,
I've found the solution.
Ionic need absolutely a task named `gulp.task('serve:before', ['default']);`
_(change default by your first task)_

My new ionic.config.json
```json
{
  "name": "jcm-next",
  "app_id": "",
  "v2": false,
  "typescript": false,
  "gulpStartupTasks": [
    "process:sass",
    "process:typescript",
    "process:javascript",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ]
}
```
But where is the difference with Watch in config file ?
```json
"watch": {
    "sass": ["scss/**/*.scss"],
    "html": ["www/**/*.html"],
    "livereload": [
      "www/**/*.html",
      "www/**/*.js",
      "www/**/*.css"
    ]
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by Xarkam** [comment]
OK sorry for asking here rather than on the forum for support. 

Please note that if this important information was in the documentation, I would not need to ask or lose a whole morning searching on google. 

The v2 page of documentation does a 404 error :( 

Good documentation is worth all forums :D

**Comment by jgw96** [comment]
@Xarkam Very sorry you ran into a 404 error on the docs. Mind sharing the link that gave you the 404 error?

**Comment by Xarkam** [comment]
@jgw96 http://ionicframework.com/docs/v2/cli/v2 give me a 404 error.

I suggest creating a page in the documentation that shows significant changes between Ionic1 and Ionic2 if you using gulp.

If the documentation had reported the requirement of a special task of the gulpfile, I would not have had to complain.
Anyway I have not found a page in the documentation stating that obligation.
