### ISSUE TITLE
$ionicView.leave does not always fire

### ISSUE THREAD

**Issue by jasperkuperus** [driftyco/ionic#7912]
#### Short description of the problem:

The `$ionicView.leave` event does not always fire when leaving a state.
#### What behavior are you expecting?

I expect that the `$ionicView.leave` event should **always** fire on state change, regardless of which state you're going to. The JSFiddle below should print `LEAVE` for each state leave, but it stops printing `LEAVE` after the first state change to Login.

**Steps to reproduce:**
1. Go to JSFiddle: https://jsfiddle.net/jasperkuperus/8h1asmke/
2. Open developer console
3. Open menu + go to Login state
4. Go to Home state (click home button)
5. Go to Login state

**Other information:** It seems that this behavior is triggered by a combination of switching to another top level state (from `app.home` to `intro.login`) and moving from a cached state (`app.home`) to a non cached (`intro.login`) state. Switching state between `app.home` and `app.state2`, same level, both cached, always fires the `$ionicView.leave` event as expected.

This happens on **1.3.1 as well as older versions** of Ionic.

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#100
