### ISSUE TITLE
input field cursor moves with scrolling in ionic(tried overflow-scroll:true) nothing works

### ISSUE THREAD

**Issue by mashah1** [driftyco/ionic#7916]
![simulator screen shot 30 aug 2016 3 47 29 p m](https://cloud.githubusercontent.com/assets/17705358/18109878/2824c9a6-6ec9-11e6-9a2d-cafbdc8a0544.png)

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by mashah1** [comment]
Please help.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Does this only happen on iOS? Also, could you try this with [plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) and see if that fixes the issue for you?

**Comment by mashah1** [comment]
@jgw96 Yes this happens on iOS. I don't have CDVWKWebViewEngine this plugin in my config.xml. To add this, I just need to add only following tags in my config.xml(iOS) right?
<feature name="CDVWKWebViewEngine">
  <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />

**Comment by mashah1** [comment]
@jgw96  I did installed the plugin WKWebView and to check I am logging if (window.indexedDB) {
   console.log("I'm in WKWebView!");
} else {
   console.log("I'm in UIWebView");
}

and this logs "WKWebView" but still the issue is there. Can you please help?

**Comment by jgw96** [comment]
@mashah1 Thanks for the info! Just to be sure is your app built with Ionic 1 or Ionic 2?

**Comment by mashah1** [comment]
@jgw96 My app is build using Ionic 1.

**Comment by mashah1** [comment]
Please suggest me solution for this. Thanks!

**Comment by mashah1** [comment]
Let me know if there is any other solution please

**Comment by jgw96** [comment]
Hello, after further review I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/6048. Thanks for using Ionic!

**Comment by bittusinghintruder** [comment]
I am also facing the same issue. Any resolution.
