### ISSUE TITLE
Can't navigate back to homepage when the user reload the page

### ISSUE THREAD

**Issue by gtzinos** [driftyco/ionic#7920]
I want the feature of ionic 2 which when a user reload a page will redirect to the rootPage. Any idea how can i do it to ionic 1 using angular 1.5 ? I tryied this code but doesn't work.

var windowElement = angular.element(window);
windowElement.on('beforeunload', function (event) {
   windowElement.location.href = '/index.html';
   return false;
});

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
