### ISSUE TITLE
Observable not fired when called by a Modal

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [driftyco/ionic#7921]
Hello,

I have a problem with the Behavior Subject when it is fired by a Modal. I have this code:
```
public quantityChange:BehaviorSubject<number> = new BehaviorSubject<number>(0);

setQuantity(quantity) {
        this.quantityChange.next(quantity);
}

```

And in my Tabs Page, i use the subscribe() to update the quantity in a badge:

```
public quantity: number = 0;

this.orderService.quantityChange.subscribe((quantity) => {
      this.quantity = quantity;
});
```

If i call the setQuantity method inside a normal view, this works correctely and the subscribe method is called, and my badge is updated. But if the method is called inside a modal, the subscribe() don't work, i think that the next() method in the Behavior Subject is not fired.

Can you help-me by this?

Thanks!!

**Comment by TiagoSilvaPereira** [comment]
Hello, I found the cause of the problem. As i see, the Modal needs a separated provider for the OrderService. In this case, the OrderService that is running inside the Modal is another instance of the service. How to solve it? Because, if I remove the orderService from the Modal Providers, this throws: ORIGINAL EXCEPTION: No provider for OrderService!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
