### ISSUE TITLE
Focus on Input doesn't change label color on iOS

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#7923]
#### Short description of the problem:
Focus on Input doesn't change label color on iOS

#### What behavior are you expecting?
Same things as it happends for MD

MD
![image](https://cloud.githubusercontent.com/assets/17563226/18131875/c5b963f4-6f94-11e6-9bea-abdd8e81fcd9.png)

IOS
![image](https://cloud.githubusercontent.com/assets/17563226/18131961/0a128b52-6f95-11e6-9ce5-153a68675122.png)

Expected to have the same color on focus.

**Which Ionic Version?** 2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually by design, iOS design guidelines do not include colored inputs like md does. Thanks for using Ionic!
