### ISSUE TITLE
Failed to push to another page from Forms in Modal

### ISSUE THREAD

**Issue by vinnchan** [driftyco/ionic#7925]
First example

`<form [formGroup]="variation" (ngSubmit)="onSubmit()">`
  `<ion-list radio-group formControlName="color" *ngFor="let option of options">`
  `<ion-list-header>`
    `{{option.name}}`
  `</ion-list-header>`

  `<ion-item *ngFor="let opt of option.options">`
    `<ion-label>{{opt}}</ion-label>`
    `<ion-radio value="{{opt}}"></ion-radio>`
    `<!--<ion-input type="text" formControlName="color" name="color" value=""></ion-input>-->`
  `</ion-item>`
`</ion-list>`
`<button class="custom-button" block (click)="goToCart()">Submit</button>`
`</form>`

Above is my forms in modal
I failed to push to another page from Forms in Modal after I clicked submit button.
Below is my push to another page method

`goToCart() {
    this.nav.setRoot(CartPage);
  }`

Below picture is after I clicked submit button in the form, the modal only slided half

https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/b/f/bf6816cd5c114fa4a0318e8d69e47dfa81312c8e.png

This is the code:

https://github.com/vinnchan/FormInModal

Second example

This app include first page that allow to click and open modal. You click the open modal button.
After that you click submit button and go to cart page. 
Now you at cart page, when you click the side menu, it won't open.
I viewed the browser console pane, showed no error(s).

Second example behaved differently than the first example but I guess these are similar issues.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you try the below:

```
import { App } from 'ionic-angular';
this.app.getRootNav().setRoot(CartPage);
```

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
