### ISSUE TITLE
Missing iOS icon resources

### ISSUE THREAD

**Issue by ENG618** [driftyco/ionic#7926]
#### Short description of the problem:
When creating a basic project and adding an iOS environment, there are a couple of missing resources

#### What behavior are you expecting?
For the project to run out of the box `cordova prepare` should complete without issues.

**Steps to reproduce:**
1. insall mfpdev-cli `npm install -g mfpdev-cli`
2. `ionic start myApp tabs`
3. `cd` into **myApp** run `ionic platform add ios`
4. Add plugin with `ionic plugin add cordova-plugin-mfp`. You will see a couple errors of *no such file or directory*
5. run `mfpdev app preview` (this will fail and require `cordova prepare` to be ran in the preview)
6. run `cordova prepare` (you will now see missing resource errors)

If you add the missing resources and complete `cordova prepare` you can than run `mfpdev app preview` without any errors.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Add the following missing resources to **resources/ios/icon/**

* icon-40@3x.png
* icon-83.5@2x.png
 

**Which Ionic Version?** 1.x or 2.x
2.0.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1326

**Comment by jgw96** [comment]
Hello, since this issue was related to the ionic cli and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
