### ISSUE TITLE
Support for Aurelia SPA framework

### ISSUE THREAD

**Issue by landofjoe** [driftyco/ionic#7927]
#### Request to support Aurelia framework

Please consider providing support for Aurelia framework in a similar manner as has been done for Angular.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. At this time we are definitely focused on Angular, but I love the suggestion! Since we won't be considering something like this for the foreseeable future, I am going to go ahead and close this issue. Thanks for using Ionic!
