### ISSUE TITLE
bug: wrong window.innerWidth after landscape->portrait

### ISSUE THREAD

**Issue by dasilvacontin** [driftyco/ionic#7929]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I can reproduce on an iPhone 4S running iOS 8.

Orientation is unlocked. You are currently in landscape. You press 'Back'.  A `$scope.$on('$stateChangeSuccess', ...)` executes `screen.lockOrientation('portrait')`. `window.innerWidth` becomes `160`, instead of `320`.</span>

<span is-issue-template></span>

**Comment by dasilvacontin** [comment]
It never happens when I go back from portrait to portrait.

I can't reproduce every single time, so I believe it's a race-condition. It appears to happen when the switch to portrait mode is made after the app has successfully navigated to the previous view.

**Comment by dasilvacontin** [comment]
The numbers are `[window.innerWidth, window.innerHeight]`, logged on `resize`. Which for some reason gets fired thrice when I rotate the device.

These are the logs I get when I reproduce the bug:
```
320 480
// I rotate phone to lanscape and keep it like that til the end
480 320
back
$ionicView.beforeEnter
screen.lockOrientation('portrait')
320 480
480 320
320 480
480 320
320 480
160 640
$ionicView.enter
```

Logs when everything went fine:
```
320 480
// I rotate device
480 320
$ionicView.beforeEnter
screen.lockOrientation('portrait')
320 480
480 320
320 480
480 320
320 480
$ionicView.enter
```

Which are, like, the same logs except for the line the window size gets borked.

**Comment by dasilvacontin** [comment]
All good (as always) on iPhone 6S iOS9:
```
375 667
// I rotate
667 375
$ionicView.beforeEnter
screen.lockOrientation('portrait')
375 667
667 375
375 667
667 375
375 667
$ionicView.enter
```

**Comment by dasilvacontin** [comment]
If there's anything else you want me to log or try, let me know.

**Comment by dasilvacontin** [comment]
Also worth noting that when I rotate the 6S I get a single `'resize'` event, whilst when I rotate the 4S I get 3 `'resize'` events, similar to:

```
480 320
320 480
480 320
```

**Comment by dasilvacontin** [comment]
Pic of the bug:

<img src="https://cloud.githubusercontent.com/assets/1260830/18146004/cc339234-6fcd-11e6-93cc-a97a8411d13f.PNG" width="320">

**Comment by dasilvacontin** [comment]
Ping: this issue is still relevant and I got no feedback so far.

**Comment by jgw96** [comment]
Hello, sorry for the delay on this issue! Does this also happen on an Iphone 4s running iOS 9? Also, could you give our [wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions) a try and see if that fixes the issue for you. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
