### ISSUE TITLE
Add cordova-plugin-nativestorage implementation of IStorageEngine

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#7935]
#### Short description of the problem:

The [`cordova-plugin-nativestorage`](https://github.com/TheCocoaProject/cordova-plugin-nativestorage) plugin provides `NativeStorage`, a key/value store that stores data into `Sharedpreferences` on Android and `NSUserDefaults` in iOS. It would be nice to have an `IStorageEngine` wrapper for it as a third alternative to `SqlStorage` and `LocalStorage`.

**Which Ionic Version?** 1.x or 2.x
Ionic 2.

**Comment by ihadeed** [comment]
I'll be happy to contribute here if the suggestion is approved.

**Comment by Richard87** [comment]
How can I have one storage service that works across IOS, Windows,Android and Browser (Atleast, iOS, Android and Browser)? 

I tried `cordova-plugin-nativestorage` but `ionic serve` fails with `cordova_not_available`

Richard

**Comment by ihadeed** [comment]
@Richard87 please see my comment here: https://github.com/driftyco/ionic-native/issues/860#issuecomment-266252561

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#924
