### ISSUE TITLE
Ionic 2 Beta 11: loading.dismiss() does not work with other overlays

### ISSUE THREAD

**Issue by tbmk** [driftyco/ionic#7940]
Since Beta 11 I have this issue:

```typescript
    let loading = this.loadingCtrl.create({content: 'Loading...'});
    loading.present();

    this.geolocationService.geolocate().subscribe(
      (data) => {
        loading.dismiss();

        let alert = this.alertCtrl.create({
          title: 'Title',
          subTitle: 'Text',
          buttons: ['OK']
        });
        alert.present();
      },
      ...
    );
```

`loading.dismiss()` does not have any effect, the loading overlay stays open.  `loading.destroy()` removes it but I guess that is not the way to go.

**Comment by Barathwaja** [comment]
I'm also using ionic 2 beta 11 , also loading.dismiss() works fine..

**Comment by jgw96** [comment]
Hello, thanks for opening am issue with us! Would you mind posting a repo I can use to reproduce this issue? Thanks for using Ionic!

**Comment by borys** [comment]
Hmm.... some time ago  I've have similar issue - not sure if it is Your problem.  loading.dismiss() returns promise - try do something like: 
```
loading.dismiss().then(() => {
   ... (place here code you do after dismiss) 
});
```
especially when You want to open modal - it may causes some kind of lock f.e.:

WRONG
```
loading.dismiss();
modal.present(); // Loading is not fully closed!! may cause lock!!!
```
Works
```
loading.dismiss().then(()=>
    modal.present(); // Loading is not fully closed!! may cause lock!!!
)
```

For me, loading component works really unstable, it cause locks (f.e. #7948), so I've resigned to use it. I hope it helps...

**Comment by kelvindart** [comment]
I agree - this seems to be working fine for me now. But I have a problem with `<ion-select>`s when using a modal as described here: https://github.com/driftyco/ionic/issues/7839.

**Comment by tbmk** [comment]
Thank you @borys, I forgot to mention the alert I opened after the `loading.dismiss()` (edited). Your solution fixed it for me. I would consider it being a bug still.

**Comment by jgw96** [comment]
Hello @tbmk I'm glad @borys was able to help you with your issue! So, this is not actually a bug but simply how our asynchronous navigation works in Ionic 2. You cannot have two transitions going on at the same time, which is why our nav methods return promises to let you know when a transition is done. Thanks for using Ionic!

**Comment by Barathwaja** [comment]
Hmm @jgw96
