### ISSUE TITLE
bug: [Bug] Run android err: request.getKeyTypes()

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7942]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>This is the output of the `ionic run android` command with XWalk installed:
![image](https://cloud.githubusercontent.com/assets/9698639/18175117/aa075c82-7035-11e6-8561-44a3196456b0.png)

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1328

**Comment by jgw96** [comment]
Hey! Since this issue is an ionic cli related issue and not an Ionic framework issue I have moved this issue to the appropriate repo. Thanks for using Ionic!

**Comment by Luchillo** [comment]
Ok thanks.
