### ISSUE TITLE
300ms delay ion-item

### ISSUE THREAD

**Issue by dericeira** [driftyco/ionic#7943]
I have a big ion-list, with, ion-item(s) with a ng-click, href, etc inside a ion-content.
On the first tap to scroll up, the ion-item will get activated and background color will change. It happens if I have ion-option-button(s) too.

I've made this codepen: https://codepen.io/anon/pen/JRjbOR

So, how can I add the 300ms touch delay to ion-itens without turn it into a button?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
