### ISSUE TITLE
bug: [Bug] beta.11 ion inputs not ready for @angular/forms

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7944]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Some ion-inputs are not ready for the NgModel provided by the `@angular/forms@0.3.0` thus app breaks.

More specifically in one of my cases with `ion-searchbar` and `ion-toggle`.
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello thanks for opening an issue with us! Would you mind giving a little more info about exactly what does not work? Also, would you mind posting a repo that i can use to reproduce this issue?

**Comment by Luchillo** [comment]
Ah sorry, i was following a tutorial on the new Forms and they used version `0.3.0`, with that version all `NgModel` bindings broke the app, so i reverted to `0.2.0` and now it works.

**Comment by jgw96** [comment]
Ahh got ya, with the upcoming beta.12 release (which is based on rc5) the newest version of forms will work, until then you should use `0.2.0`. Thanks!

**Comment by Luchillo** [comment]
Any release date plans? also i tough that beta.12 will include AoT compilation, and that was better implemented with RC.6 which came yesterday.

**Comment by jgw96** [comment]
We actually just updated the beta.12 build to rc6 😃 . At this time the release date is..... soon 😉 . Also, it will include AOT compile.
