### ISSUE TITLE
Issues with dismissing a ModalControl immediately after dismissing a LoadingControl

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic#7948]
#### Short description of the problem:
A ModalController does not dismiss its view when called immediately after dismissing a LoadingController. I.e., my Modal view is displaying; something calls a function which invokes a LoadingController to display progress, once that LoadingController is dismissed, the ModalController is dismissed programatically, but it does not actually dismiss.

I did have a similar issue a few weeks back which may well be related, but the opposite is happening this time: #7839.

#### What behavior are you expecting?
When the LoadingController is dismissed, I expect the ModalController to be dismissed as controlled programmatically.

**Steps to reproduce:**
1. Clone the following repo: https://github.com/kelvindart/ionic-loading/
`git clone https://github.com/kelvindart/ionic-loading/ && cd ionic-loading`
2. Run Ionic emulate using the iOS simulator: `ionic emulate ios`
3. Observe the Modal display, press one of the buttons and observe.

I have tried two mechanisms to get it to display:

```javascript
let loader = this.loadCtrl.create({
  content: 'Loading...'
});

loader.onDidDismiss = () => {
  this.close();
};

loader.present();

setTimeout(() => {
  loader.dismiss();
}, 3000);
```

**and:**

```javascript
loadAndDismissTwo() {
  let loader = this.loadCtrl.create({
    content: 'Loading...'
  });

  loader.present();

  setTimeout(() => {
    loader.dismiss();

    this.close();
  }, 3000);
}
```

Neither seem to work!

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 There's no Plunker template for 2.0.0-beta.11, so I created a project for you to clone and try out for convenience sake!

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

#### Plunker that shows an example of your issue
No Plunker - but please refer to the Github URL above

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by MatanYed** [comment]
+1

**Comment by kelvindart** [comment]
I've just noticed there's a syntax error in my code - durrr. I'm ever so sorry!

The following should NOT be assigned:
```javascript
loader.onDidDismiss = () => {
  this.close();
};
```
Instead:
```javascript
loader.onDidDismiss(() => {
  this.close();
});
```
And it's working perfectly!
