### ISSUE TITLE
bug: [Bug] ion-segment beta.11 stuck style in first button

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7949]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The `ion-segment` component is showing the first item style like if it is always chosen even when other is chosen:

![image](https://cloud.githubusercontent.com/assets/9698639/18186115/7cd5b048-7066-11e6-8989-1a894503d54b.png)
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! Would you mind posting a screenshot of the issue you are seeing? Thanks!

**Comment by Luchillo** [comment]
I did, look in the description.

**Comment by jgw96** [comment]
Thanks! Sorry, didn't see it at first! Would you mind posting a code sample or repo I can use to reproduce this issue?

**Comment by Luchillo** [comment]
I did not manage to reproduce in a new app, however i managed to work around it, i just set the variable in the `ionViewDidEnter` method instead of the constructor nor the variable definition, that seems to have it solved, also the error only happened when using chrome's device emulation, in actual device or in normal chrome view it did not happened.
