### ISSUE TITLE
sidemenu template has div inside button

### ISSUE THREAD

**Issue by eidng8** [driftyco/ionic#7953]
In the ionic v2 sidemenu template, the `<button>` tag contains a `<div>` inside it, in the [page2.html file](https://github.com/driftyco/ionic2-starter-sidemenu/blob/ef4829f445d58c09e98eecdc5b1fa0543b50aaf2/app/pages/page2/page2.html#L12-L18). This violates the [current HTML 5 standard](https://www.w3.org/TR/2012/WD-html5-20120329/the-button-element.html#the-button-element), isn't it?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You are correct and we will update it to be more compliant with the standard. Thanks for using Ionic!
