### ISSUE TITLE
bug: Ionicons 2 Look different on iOS

### ISSUE THREAD

**Issue by e5kimol4ser** [driftyco/ionic#7954]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>The Ionicon 2 named "ion-ios-body-outline" looks completely fine on my mac in browser, on either the official ionicons website and an app simulated in the browser (safari). But on my iPhone running iOS 9.3.5, the icon is solid and not just the outline, but the head of the person is. This occurs on both, an app running in "Ionic view app" and the browser (safari) on ionicons.com</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind trying this using our [wkwebview](https://github.com/driftyco/cordova-plugin-wkwebview-engine) plugin? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by e5kimol4ser** [comment]
I'm still having this Issue on iOS 10 with Ionic 1 and 2, on both UIWebView and WKWebView! The icon looks fine on any device/browser, but not on iOS devices, iPhone and iPad. Same issue when going to [ionicons.com](url) with mobile-safari. I didn't found a workaround and your suggestion using the WKWebView is not working either...
