### ISSUE TITLE
Form elements blinking when using ng-required

### ISSUE THREAD

**Issue by sidlauskaslukas** [driftyco/ionic#7955]
#### Short description of the problem:

After updating Ionic from 1.2.4 to 1.3.1 where AngularJS version is 1.5.3 form elements started to blink on iOS devices and Safari browser when using ng-required on one of the form elements (I use it on the textarea). 

Here is the code of that form:

``` html
 <form name="registrationForm">
    <div class="list" ng-repeat="group in vm.groupedFields[vm.selectedType].fields">
      <div class="item" ng-repeat="field in group">
        {{field.name!=='Comment'&&field.name!=='Select'?field.name:''}}
        <div class="select-field" ng-if="field.name=='Select'">...</div>
        <textarea ng-model="field.value" ng-if="field.name=='Comment'" ng-required="field.required"></textarea>
      </div>
    </div>
    <button ng-disabled="registrationForm.$invalid">Send</button>
  </form>
```
#### What behavior are you expecting?

Form elements should not blink when using ng-required

**Steps to reproduce:**
1. Open this example on iOS device or Safari browser http://codepen.io/sidlauskas/full/KrjXdw/
2. Try to change the types at the top
3. You can see how the elements are blinking

**Other information:**
It works fine on lower versions of Ionic where AngularJS is 1.4.x. I also have tried to reproduce this using only AngularJS 1.5.3 (without Ionic) and it worked fine. Here is a link to example: https://plnkr.co/edit/wdYBqK82nwTUBd0Anm9M?p=preview
So I guess this could be related to Ionic 1.3.x changes.

**Which Ionic Version?** 1.3.1

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.1
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#98
