### ISSUE TITLE
CommonJS/UMD support for Ionic v1

### ISSUE THREAD

**Issue by nicopace** [driftyco/ionic#7959]
#### Short description of the problem:

The npm package does not support CommonJS format, and it complicates the integration with projects were dependencies are managed with NPM.

#### What behavior are you expecting?

To have the release/*.js files wrapped in a UMD style export, so you will support CommonJS and others as well. A useful reference is in here: http://bob.yexley.net/umd-javascript-that-runs-anywhere/

**Which Ionic Version?** 1.x

**Comment by nicopace** [comment]
Something interesting that comes from doing some research on release/ionic.js file is that ionic just depends on 4 external (global) variables, and all of them are already in npm: 
  * 'angular': https://www.npmjs.com/package/angular
  * 'cordova': these one is inserted dinamically if working on a cordova environment
  * 'jQuery': optional dependency, but it also lives here: https://www.npmjs.com/package/jQuery
  * 'Modernizr': https://www.npmjs.com/package/modernizr

And the bundle is already very polished so it would be easy to solve this.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! While we greatly appreciate your suggestion, at this time we do not plan on making any new modifications to Ionic 1. Because of this I will be closing this issue for now. Thanks for using Ionic!
