### ISSUE TITLE
Error: ionic run ios

### ISSUE THREAD

**Issue by Aditya-app-dev** [driftyco/ionic#7960]
Hello,

I am trying to run ionic 2 application in my device(iphone 5s), but it giving me error:

```
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/AdityaBatra/documents/ionic/sidemenuapp/platforms/ios/cordova/build-debug.xcconfig,-project,sidemenuapp.xcodeproj,-target,sidemenuapp,-configuration,Debug,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=/Users/AdityaBatra/documents/ionic/sidemenuapp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/AdityaBatra/documents/ionic/sidemenuapp/platforms/ios/build/sharedpch
```

I have also tried `ionic run ios --device` but it's not working.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1336

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this issue is an Ionic cli related issue and not an Ionic framework related issue i have moved this issue to the appropriate repo. Thanks for using Ionic!
