### ISSUE TITLE
question / bug: i have lots of business logic in golang i want to expose

### ISSUE THREAD

**Issue by joeblew99** [driftyco/ionic#7961]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>basically i have lots of code in golang and need to expose that to the ionic layer.

with golang i can compile it all to obective c and android java, but i am looking for how i can expose that. i am guesining that i have to wrap it as a cordova plugin ?

if there are some examples related to this for me it would really help.
Or if its just impossible just say, as i am hitting my head on this</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
