### ISSUE TITLE
TypeError: null is not an object -- when scrolling after focusing an input on iOS

### ISSUE THREAD

**Issue by kshaaban-** [driftyco/ionic#7964]
#### Short description of the problem:
- Snappy scrolling.
- Delayed Keyboard closing.
- ~~Disappearing `ion-header`.~~ Setting `disableScroll(true)` on Native Keyboard fixes that.

#### What behavior are you expecting?
Smoother scrolling experience for users filling out a form.

**Steps to reproduce:**

1. In a terminal, run:

    ```zsh
    ionic start testApp blank -v2
    ```

2. Add an `ion-label`, `ion-input` to an `ion-item` in the generated `home.html` template

     ```html
     <ion-item>
         <ion-label>Test</ion-label>
         <ion-input type="text"></ion-input>
     </ion-item>
     ```

3. Run or Emulate the app for **`iOS`**

    ```zsh
    ionic run ios
    # or
    ionic emulate ios
    ```

4. Focus on the created input.
5. Tap and drag in an attempt to scroll the page.
6. **`TypeError`** occurs, and the strange behavior takes place.

**Other information:**

- This is the error, and where it occurs at:
`TypeError: null is not an object (evaluating 'startCoord.x')`
&nbsp;&nbsp;&nbsp;&nbsp;`fn hasPointerMoved — dom.js:166` [(dom.ts:200)](https://github.com/driftyco/ionic/blob/26441ecfe35497d8ba3762806ca9700ecf822153/src/util/dom.ts#L206-L211)
&nbsp;&nbsp;&nbsp;&nbsp;`fn pointerMove — tap-click.js:43` [(tap-click.ts:50)](https://github.com/driftyco/ionic/blob/845a516375aea8ee08f7762a8e37104de8f29dfb/src/components/tap-click/tap-click.ts#L50-L55)

- It doesn't occur when running `ionic serve`.
- Haven't tried it with **`Android`**/**`Windows`**

**Which Ionic Version?** 1.x or 2.x
Ionic 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```zsh
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by kshaaban-** [comment]
About a month later, and after RC0 this is still an issue.
The issue not getting much attention makes me wonder if I'm missing something when creating inputs 🤔

**Comment by masiamj** [comment]
Still getting this issue. Anyone else?
