### ISSUE TITLE
Feature Request : support for placeholder attribute in the datetime component

### ISSUE THREAD

**Issue by ogoguel** [driftyco/ionic#7966]
#### Short description of the problem:

When no date has been selected yet, the input field is totally blank which might be confusing for the end user 
#### What behavior are you expecting?

Add a placeholder attribute in the datetime component to display a text until a date is selected

**Which Ionic Version?** 
ionic 2.00-beta 11

**Comment by Screeze** [comment]
I would strongly support this feature request since I also need it.
