### ISSUE TITLE
NavController.viewWillLeave emits spuriously on application start

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#7970]
#### Short description of the problem:
`NavController.viewWillLeave` emits a value when the application starts. I'm not sure where this value is coming from, but it's a `ViewController`.

#### What behavior are you expecting?
No value is emitted.

**Steps to reproduce:**
1. Create a blank Ionic v2 app.
2. Replace `app.ts` with the below code.
3. Run the application.

```
import { Component, ViewChild, OnInit, OnDestroy } from '@angular/core';
import { ionicBootstrap, Platform, NavController } from 'ionic-angular';
import { StatusBar } from 'ionic-native';
import { Observer, Subscription } from 'rxjs';

import { HomePage } from './pages/home/home';


@Component({
    template: '<ion-nav [root]="rootPage" #myNav></ion-nav>'
})
export class MyApp implements OnInit, OnDestroy {
    @ViewChild('myNav') public navCtrl: NavController;
    public rootPage: any = HomePage;

    private viewWillLeaveSubscription: Subscription;

    constructor(public platform: Platform) {
        platform.ready().then(() => {
            StatusBar.styleDefault();
        });
    }

    public ngOnInit() {
        this.viewWillLeaveSubscription = this.navCtrl.viewWillLeave.subscribe((value) => {
            console.log('viewWillLeave next(' + value + ')');
            if (value) {
                console.log(value);
            }
        });
    }

    public ngOnDestroy() {
        this.viewWillLeaveSubscription.unsubscribe();
    }
}

ionicBootstrap(MyApp);
```

The output is this. The `componentType` is `undefined`, so I don't know where this ViewController object is coming from.
```
app.ts:26 viewWillLeave next([object Object])
app.ts:28 ViewController {
_emitter: EventEmitter
_hdAttr: null
_leavingOpts: null
_loaded: false
_onDidDismiss: null
_onWillDismiss: null
_tbRefs: Array[0]
componentType: undefined
data: Object
didEnter: EventEmitter
didLeave: EventEmitter
didUnload: EventEmitter
fireOtherLifecycles: true
index: -1
instance: Object
isOverlay: false
name: ""
state: 2
willEnter: EventEmitter
willLeave: EventEmitter
willUnload: EventEmitter
__proto__: Object
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

#### Plunker that shows an example of your issue
http://plnkr.co/edit/5UV6VgfAz14uVHIr9zr0?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.4.7
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have made a plunker [here](http://plnkr.co/edit/t6MkH3yKL1bTIzgcBnNk?p=preview) which shows the solution for this issue. As you can see from the plunker the change was to use our Ionic 2 lifecycle events instead of the default Angular lifecycle events. You can read more about our lifecycle events [here](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events). Thanks for using Ionic!
