### ISSUE TITLE
Loading component with dismissOnPageChange breaks the page life cycle

### ISSUE THREAD

**Issue by ziggyJ** [driftyco/ionic#7972]
#### Short description of the problem:

A page will not fire ionViewWillLeave or ionViewDidLeave, if it has an loading component with dismissonPageChange is true. 

#### What behavior are you expecting?
Those life cycle callbacks should be called.

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This has actually already been fixed in master and will be in the beta.12 release. Thanks for using Ionic!
