### ISSUE TITLE
Feature Request : DateTime Component - Option to set current time as default value for picker 

### ISSUE THREAD

**Issue by manuelroth** [driftyco/ionic#7973]
#### Short description of the problem:

The DateTime Component allows to create a simple input component for date and time inputs. It would be nice, if there was an option to set the current time as default value for the picker.

In many cases it would be useful, if the default value of the picker was not 1. January 2016 but the current date of the day. With this people could fill out the form even faster, same applies to time inputs. 

#### What behavior are you expecting?
Add some sort of attribute to the datetime component which allows to set the default value of the picker to the current time.

```
<ion-item>
  <ion-label>Date</ion-label>
  <ion-datetime displayFormat="MM/DD/YYYY" [(ngModel)]="myDate" useCurrentTimeAsDefaultValue="true"></ion-datetime>
</ion-item>
```
 
**Which Ionic Version?**
ionic 2.00-beta 11

**Comment by kshaaban-** [comment]
You can/should initialize your model to an [ISO 8601 datetime](https://www.w3.org/TR/NOTE-datetime) formatted value.

JavaScript's Date object has a `.toISOString()` function. So in your case, to get current time, just initialize `myDate` in your component to
```javascript
myDate = new Date().toISOString();
```

**Comment by manuelroth** [comment]
@kshaaban- Thanks a lot, this solves my case perfectly. Sorry for asking such an simple question. Will close this issue then.

**Comment by charlesen** [comment]
What if we want our input to be empty but setting picker to the current date ?

**Comment by ollyjohn** [comment]
+1 on @charlesen's comment.  This is a situation I'm currently facing which doesn't seem to be catered for..
