### ISSUE TITLE
ionic2 how to create same UI for ios and android

### ISSUE THREAD

**Issue by tianleios** [driftyco/ionic#7976]
I have a task , need create same ui for ios and android, but I cannot find function

**Comment by Eclektic** [comment]
When you bootstrap your app with IonicBootstrap you can pass options to it, like that :

`ionicBootstrap(MyApp, null, {
  mode: 'ios'
});`

The "mode" allow you to force the default style of your app for both platforms. ('ios' or 'md') 

Not sure about what you ask for but hope it can help.

**Comment by tianleios** [comment]
thanks for u!!! resolve this problem
