### ISSUE TITLE
Push notification: How to handle onClick ?

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#7977]
#### Short description of the problem:

I have setup the Ionic Push Notifications. Everything works fine. The notification is properly received when the app is off or background.

When i click on it I am redirected to a specific page that i setup in the onNotification, and works.

The problem is that, when the app is in the foreground, the notification is not received (and that's right) BUT the onNotification is still applied, thus I am redirected to that page EVERYTIME the cURL request is made.

#### What behavior are you expecting?

I expect a kind of onClick callback function that is called ONLY when i actually click on the notification.

**Steps to reproduce:**
1.  Setup the callback function inside the onNotification (see code below)

```
var push = new Ionic.Push({

		"debug": true,
		"onNotification": function(notification) 
		{
			$rootScope.get_my_account_data();
			$location.path('app/attendee_list');
		},
		"onRegister": function(data) 
		{
			console.log(data.token);
		},

	});
```

**Other information:** 

There is another place where I should setup the callback for onClick? 

**Which Ionic Version?** 1.x or 2.x

`Ionic Framework Version: 1.1.1`

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.1.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014


```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#176

**Comment by jgw96** [comment]
Hello! Because this issue was an issue related to the Ionic cloud and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
