### ISSUE TITLE
Move dependencies to angular 2.0.0-rc.6

### ISSUE THREAD

**Issue by kevstessens** [driftyco/ionic#7980]
Due to compatibility issues with other angular2 packages, there is a need to improve dependencies definition.

**Comment by ramonornela** [comment]
Closes @adamdbradley and @danbucholtz are working in branch https://github.com/driftyco/ionic/blob/ngmodule-build/package.json already fix this.

**Comment by danbucholtz** [comment]
Hi @kevstessens, @ramonornela is exactly right.  This process is already underway and we hope to have more to share soon.  We have [a branch here](https://github.com/driftyco/ionic/tree/ngmodule-build) with all of our progress and changes if you want to follow along. I'm going to close this. We'll have RC6 in place as soon as we possibly can.

Thanks for pointing this out, @ramonornela!

Thanks,
Dan

**Comment by kevstessens** [comment]
Thanks @danbucholtz and @ramonornela !
