### ISSUE TITLE
Ionic package IOS submission to App Store

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic#7985]
Hi, 
I'm working on windows machine, built the IPA file using ionic package service:
"ionic package build ios --release -–profile winnerzprod"

I'm in the process to submit my app to the Apple app store but it requires that:
"Submit your builds using Xcode 6 or later, or Application Loader 3.0 or later"

Is there a way to submit the IPA I have created using the package service?
Can I  do it from my windows machine or I must have a mac?
Please elaborate. 
Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
