### ISSUE TITLE
How can i put my own component near dom<app-root>

### ISSUE THREAD

**Issue by tfirer** [driftyco/ionic#7987]
#### Short description of the problem:
Hello, I build a component, but i don't know how can i put my component to root dom like below. Anybody can help me?

#### What behavior are you expecting?
The dom struct i want is like this
《ion-app》
      《div class="app-root"》xxx《/div》              // this is builded by ionic
      《my-component》xxx《/my-component》  // this is where i want to locate my component
《/ion-app》

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
