### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by Aditya-app-dev** [driftyco/ionic#7988]
Hello,

I am trying to navigate from `0 level -> 1 level -> 2 level` and for this, i am using this code.

```
//using this to get page details from 0 level
this.singleitem = params.data.pages;
navigatetoplaceinfo(){
//using this to send page information to 2 level i.e;
			this.navCtrl.push(PlaceinfoPage, {singlepage: this.singleitem});
}
```

This code is sending me to the 2 level where i want to go but when i am trying to go back from `2 level` to `1 level`. It is throwing me to `0 level` instead of `1 level`.

**Comment by jgw96** [comment]
Hello, thanks for opening am issue with us! Would you mind sharing a little more code? Specifically where you navigate to page 1 and then to page 2 from there. Thanks for using Ionic!

**Comment by Aditya-app-dev** [comment]
Hello,

Can i email you on your gmail id?

**Comment by Aditya-app-dev** [comment]
Hello,

Can i email you on your gmail id?
