### ISSUE TITLE
Swipe to go back transition sometimes gets stuck

### ISSUE THREAD

**Issue by cwelk** [driftyco/ionic#7989]
When moving back/sliding back, sometimes page-switch animation stops at ~50% and you can see two pages.

It's tricky to reproduce, but is already described in this ionic forum post: https://forum.ionicframework.com/t/swipe-to-go-back-transition-sometimes-gets-stuck/32158

Regarding Ionic 1.x on iOS.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#97
