### ISSUE TITLE
Paths in config.xml are written with backslashes, causing problems on OS X

### ISSUE THREAD

**Issue by Z3roCoder** [driftyco/ionic#7990]
#### Short description of the problem:
We develop on a Windows Machine
Everytime we use ionic resources and ionic prepare, the config.xml is changed to paths like "resources\android\splash\" and "resources\android\splash\"
While this is no problem on a Windows-Machine, it gives us regularly problems building on OS X

remotebuild on OS X tells us evrey time that the resources can not be found

#### What behavior are you expecting?
Paths should contain fowardslashes and no backslashes.
<icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
instead of 
<icon src="resources\android\icon\drawable-mdpi-icon.png" density="mdpi"/>

**Steps to reproduce:**
1. call ionic resources
2. call ionic prepare
3. build the app on OS X

**Which Ionic Version?** 1.x or 2.x
"ionic -v" -> 2.0.0
But Ionic 1 is used in the project

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: (Windows 10, apparently not detected correctly)
Node Version: v6.3.1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1342

**Comment by jgw96** [comment]
Hello! Since this issue was more of an Ionic cli issue than a framework issue I have moved this issue to the appropriate repo. Thanks for using Ionic!

**Comment by Z3roCoder** [comment]
Aah, yes. Stupid me, thank you!

**Comment by jgw96** [comment]
haha, no problem at all!
