### ISSUE TITLE
Reuse an angular 1 module - support for UpgradeAdapter

### ISSUE THREAD

**Issue by fdnhkj** [driftyco/ionic#7991]
#### Short description of the problem:
I would like to reuse an angular 1 module (library-like, mainly services) in a Ionic2 app.

I have read about the upgrade module and its [`UpgradeAdapter`](https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html) service in [angular 2 docs](https://angular.io/docs/ts/latest/guide/upgrade.html#!#upgrading-with-the-upgrade-adapter).

> [...] service that can bootstrap and manage hybrid applications that support both Angular 2 and Angular 1 code.

In order to use the UpgradeAdapter service, its `bootstrap` function should be called.

Knowing that Ionic2 also requires to call a bootstrap function `ionicBootstrap`, I am wondering if it exposes a way to use the UpgradeAdapter bootstrap instead of [the standard angular 2 one](https://github.com/driftyco/ionic/blob/master/src/config/bootstrap.ts#L1).

So question is: do you plan to support [`UpgradeAdapter`](https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html) ?

**Other information:**
- https://forum.ionicframework.com/t/how-to-use-upgradeadapter-to-migrate-applications-to-v2/41508/2
- https://forum.ionicframework.com/t/upgrading-from-angular-1-to-angular-2-ionic-2-with-upgradeadapter/51906

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello! At this time we are not planning on supporting `ngUpgrade` or the upgrade module in Angular 2 for Ionic 2. This involves running both Angular 1 and Angular 2 at the same time, which would also mean running Ionic 1 and Ionic 2 at the same time, which can lead to wonky performance, un-needed complexity and more. Sorry if this causes any hassle for you and thanks for using Ionic!

**Comment by samvloeberghs** [comment]
I don't get the running Ionic 1 and Ionic 2 at the same time? I could easily integrate another framework into Ionic 2, besides NG2, why not simply NG1? So why do you need to run Ionic 1? Can you please elaborate on that a bit?

**Comment by fdnhkj** [comment]
@jgw96 Could you please comment on this ? I don't understand why running angular1 on top of Ionic2+angular2 implies running Ionic1 ? Thank you.
