### ISSUE TITLE
Please `npm publish` the 1.x version of ionic-sdk on NPM

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#7996]
The latest release on the `1.x` branch is 1.3.1, but that version isn't published to npm.

![](http://ajoslin.co/19kea/1vpsfe92+)

Please `npm publish` it.

Thanks!

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Ionic 1.3.1 is released under `ionic-angular` (along with the latest Ionic 2 release) instead of `ionic-sdk`.

**Comment by ajoslin** [comment]
Found it. Thanks.

**Comment by jgw96** [comment]
No problem at all!
