### ISSUE TITLE
bug: ionic package build failing

### ISSUE THREAD

**Issue by jbrownssf** [driftyco/ionic#7997]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>In my projects I have been creating builds using
`ionic package build ios -p development`
In projects that have previously been able to create builds using ionic package are now giving the following error:
  id       │ 43                     
  status   │ FAILED                 
  platform │ ios                    
  mode     │ debug                  
  started  │ Sep 6th, 2016 22:17:43 

output:

`=== BUILD TARGET Simply Scheduling OF PROJECT Simply Scheduling WITH CONFIGURATION Debug ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

** BUILD FAILED **`

I attempted to resolve this issue thinking that my certs may be outdated but the .mobileprovision and the .p12 are up to date and still giving me the same error. I already checked that the com.example.appname is accurate for the profile and the one I am using in my config.xml.

Here are the different versions of dependencies from my bower.json file:
`{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.4",
    "ionic-platform-web-client": "~0.2.1"
  },
  "resolutions": {
    "ionic": "1.2.4",
    "angular": "1.4.3",
    "angular-animate": "1.4.3",
    "angular-sanitize": "1.4.3"
  }
}`

Any thoughts on what the issue might be or might it be something wrong with the update that moved away from ionic.project to ionic.config.json

Here is another irregularity I have noticed since the above issue started happening:
`ionic upload`
is not working correctly for a new project. (It does not create the ionic.config.json file).</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1353

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this an issue with the Ionic CLI and not the Ionic framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
