### ISSUE TITLE
.overscroll in #sideMenu shouldn't have position fixed

### ISSUE THREAD

**Issue by vincent-louis** [driftyco/ionic#7998]
ionic version: **1.3.1**
platform: **Nexus webview**
### Issue occurs when:

Dragging down refresher in `#sideMenu`
### Reason:

class `.overflow-scroll > .scroll.overscroll` has styling of `position: fixed` causing flickering when dragging down the refresher in `#sideMenu`. 

class `.scroll` itself has a width of 100%, together with `position: fixed` it expand out from `.scroll-content`
### workaround:

```
#sideMenu {
    .overflow-scroll > .scroll.overscroll {
        position: relative !important;
    }
}
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#96
