### ISSUE TITLE
Ionic 2 Popover: ion-select inside Popover doesn't work

### ISSUE THREAD

**Issue by achalbi** [driftyco/ionic#8000]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by abartolo** [comment]
I am also facing this issue. Clicking select goes over popover and then the page is not responsive. 

See image below.

Before Clicking
![image](https://cloud.githubusercontent.com/assets/5394228/18333969/b5c198ce-7541-11e6-8355-5217cdd53489.png)

After Clicking
![image](https://cloud.githubusercontent.com/assets/5394228/18334007/09cc779a-7542-11e6-9013-7a2b314ec225.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! This has already been fixed and will be in the beta.12 release. Thanks for using Ionic!

**Comment by afixibiranchi** [comment]
I am still having the issue, below are my ionic info details:

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.2 Build version 8E2002
