### ISSUE TITLE
Side menu disappears on iOS

### ISSUE THREAD

**Issue by dvdbrink** [driftyco/ionic#8001]
#### Short description of the problem:
Left menu randomly disappears after opening left menu. I have not been able to pinpoint the exact cause, because it happens like once every twenty tries. I've switched to a overlay menu which seems to have fixed the problem. So, it looks like the problem is just with the default iOS menu type (reveal?).

This is just a thought, but the problem could be because a click and a swipe gesture or two rapid clicks are both handled for opening or closing the menu, thus hiding the menu right after it has been shown. However, I have not been able to reproduce this consistently. 

<img src="https://cloud.githubusercontent.com/assets/583528/18303557/fdaf0644-74dd-11e6-918d-fc8b56251e42.jpg" width="200">

I was able to reproduce the problem in the simulator on the [ionic website](http://ionicframework.com/docs/v2/api/components/menu/Menu/), so it should not be a problem specific to me:
<img src="https://cloud.githubusercontent.com/assets/583528/18303547/f35f9050-74dd-11e6-8e50-037d93b7553f.PNG" width="200">

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
https://forum.ionicframework.com/t/random-white-block-after-opening-or-closing-left-menu/62598

**Which Ionic Version?** 2.x

**Comment by ventr1x** [comment]
There is actually an extreme amount of animation bugs in current beta.
ActionSheets that don't always disappear on click.
Pages you open twice (which can easily happen) completely bug out the entire app.

Sidemenus that bug out on multiple occasions and forms (especially on web).
Including the here mentioned problem and many more (like the actionsheet very often simply not disappearing).

Is there any kind of statement about this? Currently this all around feels very alpha and FAR away from any kind of production/rc state.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So I just have a few questions, what browser were you using when you reproduced it on the docs site? I just tried it with chrome and cannot seem to be able to reproduce. We are tracking an issue [here](https://github.com/driftyco/ionic/issues/7629) which may be related. @ventr1x Sorry you are having issues with beta.11! Would you mind posting a repo that I can use to reproduce these issues? I cannot seem to reproduce these issues with any of my apps or our test apps at this time.

**Comment by dvdbrink** [comment]
I was using chrome 53 on windows. This indeed might be related to #7629. I was able to reproduce it again a second ago on the docs site and the menu is missing the show-menu class. I'm still not able to reproduce it consistently though, but it happens eventually by clicking the hamburger icon like a madman.

**Comment by jgw96** [comment]
@dvdbrink Hmm thats interesting, definitely sounds like #7629 rearing its head. Are you able to reproduce this in an app instead of just the docs site?

**Comment by ventr1x** [comment]
Sadly I currently can't easily post a repo as the app is contract work and not open source.
Maybe I get to reproduce it in a smaller app if I find the time.

But problems with the menu are actually the biggest issue for me.
I'm also using Chrome 53 (on Mac), but I've seen it happen in ios simulator too.

**Comment by dvdbrink** [comment]
@jgw96 It can happen in an app (on iOS with reveal menu) as well

**Comment by jgw96** [comment]
Thanks for all the testing everyone. After looking into all the evidence I am going to mark this one as blocked by #7629 as this issue seems to either be a symptom of that issue or related in some way.

**Comment by manucorporat** [comment]
@dvdbrink I think this was fixed in https://github.com/driftyco/ionic/commit/8585427fb47853b2575df5b777db031f06db767c

please reopen if the problem persist!
