### ISSUE TITLE
Windows platform - ionic resources 

### ISSUE THREAD

**Issue by endriazizi** [driftyco/ionic#8007]
Hi,
Who know how to generate resources for Windows platform using "ionic resources"
Or just where are them located when u build for Windows platform using "ionic build windows --archs=ARM"

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
