### ISSUE TITLE
DateTime transforms ISO time string without timezone into UTC

### ISSUE THREAD

**Issue by zmbc** [driftyco/ionic#8009]
#### Short description of the problem:

When I use an `<ion-datetime>` and set the initial value to an ISO time string without a timezone (e.g. `2016-07-03T15:30`), after changing the time the string now has a 'Z' at the end signifying UTC.
#### What behavior are you expecting?

It says in the Ionic docs:

> Any of the ISO formats below can be used, and after a user selects a new value, Ionic will continue to use the same ISO format which datetime value was originally given as.
> ...
> Date and Time  |  YYYY-MM-DDTHH:mm  |  1994-12-15T13:47

I would expect, then, for my format (YYYY-MM-DDTHH:mm) to remain the same. Sorry if I have misunderstood this. If my issue is expected behavior, then I guess the docs should be updated.

**Steps to reproduce:**
1. Initialize an `<ion-datetime>` with an ISO string without a timezone specified.
2. Change the date using the picker.

**Which Ionic Version?**

2.x
#### Plunker that shows an example of your issue

http://plnkr.co/edit/w0aio9JY1osYKzOJaqtd?p=preview

**Comment by shyamal890** [comment]
Attaching a plunker example for reference: http://plnkr.co/edit/CJBcb6?p=preview

Also linking https://github.com/driftyco/ionic/issues/8247

**Comment by mhartington** [comment]
So there's no good cross-platform way to handle this.
Each browser would do something different and it is very error prone.

A better way would be to use ngModel and a pipe

```html
<ion-datetime 
  displayFormat="hh:mm A" 
  [ngModel]="firstDate | formatToLocal" 
  (ngModelChange)="firstDate=$event">
</ion-datetime>

```

This will let you pass the value to something like momentJS or Date-fns as a pipe  then update the value on change as well

http://plnkr.co/edit/MHjUdC

**Comment by shyamal890** [comment]
@mhartington Have you even tested the solution? When you set the time value of `firstDate` look at it bounce to a different timezone. Please do reopen this issue. I would humbly suggest the output `valueFormat` only be in `Timezone Offset => YYYY-MM-DDTHH:mm:ssTZD => 1994-12-15T13:47:20.789+5:00` format

**Comment by shyamal890** [comment]
Mike, suggests that Ionic wouldn't be handling this issue. [Reference](https://ionic-worldwide.slack.com/archives/technical-questions/p1487351910028538)

Humbly tagging @adamdbradley @danbucholtz @mlynch to please have a relook at this issue.

**Comment by danbucholtz** [comment]
Hello,

Mike's solution for this is valid.

Thanks,
Dan
