### ISSUE TITLE
ion-slides gaps

### ISSUE THREAD

**Issue by felangga** [driftyco/ionic#8010]
I am having problem with ion-slides running on Lollipop and Marshmallow. There is a big gap between box. This problem only occur on Lollipop and above, KitKat device is working properly. 
Here are the screenshot http://pasteboard.co/sXySanZ7.jpg

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately I cannot seem to reproduce this issue on my Moto X 2014 running Android 5.1.1, my Nexus 7 running Android 6.1.1 or my Nexus 6 running Android 7.0. Would you mind posting a repo that i can use to reproduce this issue? Thanks!

**Comment by felangga** [comment]
@jgw96 Should I send you the .apk file or the full source code ?

**Comment by jgw96** [comment]
Thanks for asking, if you could just post a repo that gives a minimal reproducible example that would be great. The more minimal it is the better, as that separates it out from any external code which may be causing the issue. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
