### ISSUE TITLE
bug: I keep getting "GCM_MISMATCH_SENDER" push

### ISSUE THREAD

**Issue by martygriffin** [driftyco/ionic#8011]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I am testing Android push notifications, I followed the tutorial online to set it up. Anytime I try to send a notification via the API I get "GCM_MISMATCH_SENDER". My project ID and GCM api key are all in my project and uploaded correctly. What else can cause this?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#178

**Comment by jgw96** [comment]
Hello, because this issue was related to the Ionic Cloud and not the Ionic Framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
