### ISSUE TITLE
app doesnt open div when there is not internet connection

### ISSUE THREAD

**Issue by andrezap** [driftyco/ionic#8013]
Hi!

I have an app using ionic 2 and Im trying to open a div when the user clicks on a button.
I have a list of cards that each one has an id. I'm using DOM to manipulate the view but this just works when I got internet connection, if a turned off the div that I clicked dont show up.

my code:

http://pastebin.com/JtsVBEW3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic![
