### ISSUE TITLE
Searchbar overlapping ion-content and hiding ion-header if using *ngIf

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8016]
#### Short description of the problem:
Searchbar overlapping ion-content and not showing ion-header if using *ngIf

**Steps to reproduce:**
1. Add condition to searchbar with *ngIf
Minimal commit to reproduce issue https://github.com/aggarwalankush/ionic-inappbrowser-issue/commit/9a65c002a697140c797798a1a055d25ea2eca8d3

```
<ion-header>
  <ion-navbar no-border-bottom>
    <ion-title>Search Sample</ion-title>
  </ion-navbar>
  <ion-toolbar no-border-top>
    <ion-segment no-margin [(ngModel)]="whichSegment">
      <ion-segment-button [value]="'first'">
        First
      </ion-segment-button>
      <ion-segment-button [value]="'second'">
        Second
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
  <ion-searchbar *ngIf="whichSegment==='second'">
  </ion-searchbar>
</ion-header>
<ion-content class="cards-bg">
  <div [ngSwitch]="whichSegment">
    <div *ngSwitchCase="'first'">
      <ion-list>
        <ion-list-header>{{firstHeader}}</ion-list-header>
        <ion-item *ngFor="let item of firstItems">
          {{item}}
        </ion-item>
      </ion-list>
    </div>
    <div *ngSwitchCase="'second'">
      <ion-list>
        <ion-list-header>{{secondHeader}}</ion-list-header>
        <ion-list>
          <ion-item *ngFor="let item of secondItems">
            {{item}}
          </ion-item>
        </ion-list>
      </ion-list>
    </div>
  </div>
</ion-content>
```
**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.1.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

![untitled-screencast-_7_](https://cloud.githubusercontent.com/assets/8744282/18361513/f9c8e28c-75b6-11e6-92e7-a3b69b28cfc0.gif)

Also, is there any way to show searchbar in toolbar along with segments?

**Comment by szerner** [comment]
There was a similar [issue here](https://github.com/driftyco/ionic/issues/7706).

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The solution in the above linked issue is what you are looking for 😄 . Thanks @szerner !
