### ISSUE TITLE
Ionic2: ion-input Issue with label not floating up when type is a number and value is 0

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic#8019]
If you have an ion-input element with type="number".  When the model changes to zero, the label does not float up.

I expect the label to float up.

Steps to reproduce:
1. Click on `Calculate` button 
2. A zero is populated in the input
3. The label and the input are on top of each other.

```
    <form [ngFormModel]="weightForm" novalidate>
      <ion-item>
        <ion-label floating>Weight</ion-label>
        <ion-input type="number" ngControl="weight" [(ngModel)]="weightModel"></ion-input>
      </ion-item>
      <button secondary (click)="calculateWeight()">Calculate</button>
    </form>
```

Here is the plunker that demonstrates the issue:

http://plnkr.co/edit/TEWz3FtRTH1lWgXbWHNU?p=preview

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Thanks for the plunker! Note to self/team: the `input-has-focus` class is not applied when the input is initialized with `0`.

**Comment by keithdmoore** [comment]
Not initialized to zero but set to zero dynamically

**Comment by keithdmoore** [comment]
Just merge the PR

**Comment by jgw96** [comment]
Hello @keithdmoore thanks for posting a PR 😄 . There is currently a code freeze on master because of all the internal changes going on with the completely new AOT compile, tree shaking, and minifying build process we are working on. Because of this it may be a little while before your PR is merged, but be assured that we will be looking at it.

**Comment by keithdmoore** [comment]
Ok.  Thanks for letting me know. Cheers!

**Comment by manucorporat** [comment]
@keithdmoore thanks a lot for the PR. But it could not longer be merged without conflict so I used your fix.

**Comment by keithdmoore** [comment]
@manucorporat No problem. Thanks for working this one.  Glad to see it is fixed.  I will be able to remove my hack soon.
