### ISSUE TITLE
ionic-angular@2.0.0-beta.11-201609011853 wants @angular/common@2.0.0-rc.4

### ISSUE THREAD

**Issue by Gampesh** [driftyco/ionic#8024]
I am using angular2 RC5 but while building the application I am getting below error.
error peerinvalid The package @angular/common@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer @angular/forms@0.3.0 wants @angular/common@^2.0.0-rc.5
error peerinvalid Peer @angular/platform-browser@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
error peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
error peerinvalid Peer @angular/router@3.0.0-rc.1 wants @angular/common@^2.0.0-rc.5
error peerinvalid Peer ionic-angular@2.0.0-beta.11-201609011853 wants @angular/common@2.0.0-rc.4

**Comment by herbzi** [comment]
As far as know beta.11 only supports RC4 as the changelog had to be updated to include the install packages specific to RC4. 

> npm install --save --save-exact ionic-angular@2.0.0-beta.11 @angular/common@2.0.0-rc.4 @angular/compiler@2.0.0-rc.4 @angular/core@2.0.0-rc.4 @angular/http@2.0.0-rc.4 @angular/platform-browser@2.0.0-rc.4 @angular/platform-browser-dynamic@2.0.0-rc.4 @angular/forms@0.2.0 rxjs@5.0.0-beta.6 zone.js@0.6.12

Most of us are waiting for beta.12 which should support RC6.

**Comment by jgw96** [comment]
Hello @Gampesh thanks for opening an issue with us! @herbzi is right, beta.11 was released when RC4 was the latest Angular 2 release and therefore Ionic 2 beta.11 relies on Angular 2 rc4 as its dependency. Beta.12 will be on RC6 (: . Thanks for using Ionic!
