### ISSUE TITLE
Ionic-select or datetime error when i click it : ORIGINAL EXCEPTION: TypeError: activeNav.getActive is not a function 

### ISSUE THREAD

**Issue by ahmaddzidan** [driftyco/ionic#8025]
### Github URL :

https://github.com/ahmaddzidan/bookingapp

### Short description of the problem 

When i click on ion-select or ion-datetime and the error appear. ORIGINAL EXCEPTION: TypeError: activeNav.getActive is not a function. what should i do ? i have googling this problem wholeday but zero result. 
sorry i not good in english language. 

### Log Console
EXCEPTION: Error in build/pages/home/home.html:16:13
app.bundle.js (line 44013)
ORIGINAL EXCEPTION: TypeError: activeNav.getActive is not a function
......
**Steps to reproduce:**
1.  Start new proejct with ionic cli `ionic start bookappv2 blank --v2`
2. Copy ion-select from documentation
3. and the problem appear,

### Which Ionic Version?
ionic@2.0.0-beta.11

### Run ionic info from terminal/cmd prompt:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
Node Version: v4.4.7
OS : Windows 10

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a minimal code snippet that i can use to reproduce this issue? Thanks!

**Comment by ahmaddzidan** [comment]
<ion-content padding class="homePage">
<ion-list no-lines>
<ion-item>
<ion-label><ion-icon name="key"></ion-icon> Room Type</ion-label>
<ion-select [(ngModel)]="roomType">
<ion-option value="standard">Standard</ion-option>
<ion-option value="studio">Studio</ion-option>
<ion-option value="villa">Villa</ion-option>
<ion-option value="penthouse">Penthouse</ion-option>
</ion-select>
</ion-item>

......

import { Component } from '@angular/core';
import { NavController, LoadingController, AlertController } from 'ionic-angular';
@Component({
templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
roomType: any;
nights: any;
rooms: any;
from: any;
to: any;
constructor(public navCtrl: NavController, private alertCtrl : AlertController, private loadingCtrl : LoadingController) {
let today = new Date();
let tomorrow = new Date();
tomorrow.setDate(+1);
this.roomType = 'standard';
this.nights = 1;
this.rooms = 1;
this.from = today.toISOString();
this.to = tomorrow.toISOString();
}
}

it's my code, thanks before.

**Comment by ahmaddzidan** [comment]
# html code
`<ion-content padding class="homePage">
<ion-list no-lines>
<ion-item>
<ion-label><ion-icon name="key"></ion-icon> Room Type</ion-label>
<ion-select [(ngModel)]="roomType">
<ion-option value="standard">Standard</ion-option>
<ion-option value="studio">Studio</ion-option>
<ion-option value="villa">Villa</ion-option>
<ion-option value="penthouse">Penthouse</ion-option>
</ion-select>
</ion-item>`

# TS Code

`import { Component } from '@angular/core';
import { NavController, LoadingController, AlertController } from 'ionic-angular';
@Component({
templateUrl: 'build/pages/home/home.html'
})
export class HomePage {
roomType: any;
nights: any;
rooms: any;
from: any;
to: any;
constructor(public navCtrl: NavController, private alertCtrl : AlertController, private loadingCtrl : LoadingController) {
let today = new Date();
let tomorrow = new Date();
tomorrow.setDate(+1);
this.roomType = 'standard';
this.nights = 1;
this.rooms = 1;
this.from = today.toISOString();
this.to = tomorrow.toISOString();
}
}`

Thanks before.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue. Would you mind pulling this test I made https://github.com/jgw96/selectExample and testing? Thanks!

**Comment by ahmaddzidan** [comment]
Ok. I will try soon ..

**Comment by ahmaddzidan** [comment]
after comparing code a few days,  finaly i found the problem, i have some code in app.html, tab not working and make select and another component error,  thank you for your support.
