### ISSUE TITLE
Sass changes not updating

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#8029]
#### Short description of the problem:

I swear to God and Buddha that before everything was working fine. I was changing the style of the app in the scss/ionic.app.scss and I could see in real time the outcome.

Now it doesn't work anymore. The only way I can see the actual change is:

- modify ionic.app.scss
- run: ionic setup sass
- run: ionic serve 
- see the change in the app

If I want to make another change I have to repeat all the steps again....

#### What behavior are you expecting?

I expect to modify ionic.app.scss and see the change in real time. As it was before. And was great!

I expect to see the change being detected in the console, as before. Now the console keep silent like a fish.

**Outcome of ionic setup sass:**

```
Successful npm install
Updated /Applications/all_the_path/www/index.html <link href> references to sass compiled css

Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

[12:16:13] Using gulpfile /all_the_path/gulpfile.js
[12:16:13] Starting 'sass'...
[12:16:15] Finished 'sass' after 1.37 s
```

**My gulpfile.js: [excerpt]** 

```
var paths = {
  sass: ['./scss/**/*.scss']
};

gulp.task('default', ['sass']);

gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});
```
**My index.html:**

```
 <!-- compiled css output -->
<link href="css/ionic.app.css" rel="stylesheet">
```
 

**Which Ionic Version?** 1.x or 2.x

`Ionic Framework Version: 1.1.1`

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.1.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1358

**Comment by jgw96** [comment]
Hello, because this issue was more related to the Ionic cli and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!

**Comment by jonathancod** [comment]
Here is the solution: [](http://stackoverflow.com/questions/39954746/sass-not-compiling-watching-anymore-when-using-serve-after-ionic-update)
