### ISSUE TITLE
Poor scroll performance for ion-select with many items

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#8030]
#### Short description of the problem:
In our app we have over 500 brands. When I populate an ion-select with over 500 items scrolling goes very slowly

#### What behavior are you expecting?
Good scroll performance independent of the amount of items

**Steps to reproduce:**

See http://plnkr.co/edit/C9K01pa6JhrZpYBdcFhJ?p=preview

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/C9K01pa6JhrZpYBdcFhJ?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So this is unfortunately an unavoidable issue. First, the select component is meant to be used with only a few items and not a big list. Second, the user experience when scrolling on a select component (which is relatively small) that has such a big list is not going to be ideal. Third, even a native "select" component would struggle with rendering a 500 item list smoothly and scrolling through it. I would recommend you look into integrating that 500 item list into one of your pages or into a modal. Thanks for using Ionic!

**Comment by basvdijk** [comment]
I was looking for an autocomplete selectbox, but there isn't one yet. Which left me with the selectbox. I will look into your modal suggestion.
