### ISSUE TITLE
bug: Menu is able on child pages

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8031]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I tried:
`<ion-menu class="menu" [content]="content" persistent="false" (ionOpen)="sideMenuOpened()"></ion-menu>`

And still, menu is able to swipe in child pages... it's known problem? how to fix it?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So the `persistent` attribute on `ion-menu` actually just controls if the menu button will be shown even on a page that has a back button. To disable or enable a sidemenu on a page you can use the [MenuController](http://ionicframework.com/docs/v2/api/components/menu/MenuController/) `disable` and `enable` methods. Thanks!

**Comment by MatanYed** [comment]
@jgw96 it shouldn't be automatically disabled on child pages?
