### ISSUE TITLE
VirtualScroll render view problem 

### ISSUE THREAD

**Issue by jmarginier** [driftyco/ionic#8032]
I met several rendering issues with the "virtualScroll"/"ion-img" component.

**Case 1 :** 
Use case from http://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/ 
ink : Images Within Virtual Scroll
Problem => Several avatars are not well made when scrolling and the first item is empty 

**Case 2 :**
Create custom component and use it into virtualScroll.
Problem => No avatar is displayed

**Case 3 :** 
#7734

**Plunker to reproduce :** 
http://plnkr.co/edit/ziS2j5o6eJaDTIaT9Q17?p=preview

_ionic2@b11_

**Comment by adamdbradley** [comment]
Reported in #8744 that his issue has been has been fixed.
