### ISSUE TITLE
ionic.keyboard show() and hide() return promise after keyboard really opened resp. closed.

### ISSUE THREAD

**Issue by MichalFoksa** [driftyco/ionic#8033]
#### Short description of the problem:
Return promise and resolve it after keyboard is opened or closed.

#### What behavior are you expecting?
I would like to request a feature in `ionic.keyboard.show()` and `ionic.keyboard.hide()` methods to return `promise` which is resolved after keyboard is opened or closed.

This way code would be quite readable for Javascript developer:
```
ionic.keyboard.hide().then(function(){
    rearrange view, display elements, call redraw on specific visual component, ....
});
```

Example pseudo code how `ionic.keyboard.hide()` could be implemented:
```
/**
 * Hide the keyboard, if it is open.
 */
hide: function() {
  var deferred = $q.defer();

      if (keyboardHasPlugin()) {
        $timeout(function() {
          cordova.plugins.Keyboard.close();
        }).then(function(){
          wait until keyboard is really closed  
            then deferred.resolve();
          
        });
      } else{
          deferred.resolve();
      }
      keyboardActiveElement && keyboardActiveElement.blur();

      return deferred.promise;
}
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
