### ISSUE TITLE
fixed a input at bootom bug

### ISSUE THREAD

**Issue by tianleios** [driftyco/ionic#8034]
ion beat11

i want fixed a input at bootom, when i use position='fixed'.  when keyboard appear ,a bug will appear. when i use <ion-footer><ion-inut></ion-input></ion-footer>  keyboard will hidden inpu

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
