### ISSUE TITLE
When created new page, output shows "themes" but the folder is named "theme"

### ISSUE THREAD

**Issue by athosbr99** [driftyco/ionic#8036]
#### Short description of the problem:

This is actually a simple output typo, but I guessed that I should open a issue. Anyway:

When the user types `ionic g page nameofpage`, it shows this warning:

`Don't forget to add an import for exercicio.scss in app/themes/app.core.scss:`
`@import "../pages/exercicio/exercicio.scss";`
#### What behavior are you expecting?

The actual folder is `theme`, no `themes`.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

![screenshot at 2016-09-09 16 25 47](https://cloud.githubusercontent.com/assets/6440060/18399959/182de1ac-76aa-11e6-91b1-1105b530884c.png)

**Comment by samrm111** [comment]
I can take care of this issue.

**Comment by brandyscarney** [comment]
I'm going to close this since this output no longer exists, but thank you for the issue!
