### ISSUE TITLE
v2: click event does not response to slow click

### ISSUE THREAD

**Issue by sam0737** [driftyco/ionic#8038]
#### Short description of the problem:

On Android, or with Device toolbar in Chrome:
If I touch a link/button with my finger longer than like 300ms, the (click) event is not fired.

#### What behavior are you expecting?

Click event is fired as long as I release on top of the button/link, which it currently does in Chrome (non device mode) with a mouse.

**Steps to reproduce:**
1. With a button like this `<button (click)="newSpending()"><ion-icon name="pricetag"></ion-icon></button>`
2. Use `ionic serve` with Chrome + Developer console + Device mode **OR** `ionic run android`
3. Finger press the button and hold for more than 300ms (approx), then release
Expectation - click event is fired.
Actual - click event is not fired.

Note 1: If the tap is fast enough, it is fired
Note 2: The "expectation" is the device native experience. As well as like any ordinary button on a desktop browser.

#### Info
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.2.4

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! After extensive testing this seems to be standard webview/browser behavior. I can reproduce this with the github website, washington post progressive web app and more. I am going to look into if their is any way that we can change this behavior.

**Comment by jgw96** [comment]
Hello, after researching this more this seems to be the standard way Chrome handles click events on mobile. Unfortunately their is not much we can do about that. Thanks for using Ionic!
