### ISSUE TITLE
html in tab title attribute causes browser to show the html tag as tooltip

### ISSUE THREAD

**Issue by D3CK3R** [driftyco/ionic#804]
The title attribute should be removed from tabs after compile, because it causes the browser to show the tag as a tooltip.

```
<ion-tab data-title="<img src='{{user.logo}}' alt=''>" ng-click="e.stopPropagation()"></ion-tab>
```

**Comment by BendingBender** [comment]
It is still possible that angular re-adds the title attribute if it contains interpolations. The following code for example:
```html
<ion-tab title="{{'SOME-TITLE' | translate}}" ui-sref="somestate">
  <ion-nav-view name="some-tab"></ion-nav-view>
</ion-tab>
```
produces the following output:
```html
<ion-tab
  icon="ui-icon ui-icon-shadow"
  ui-sref="somestate"
  href="#/someref"
  title="Some translated title">
</ion-tab>
<a
  ng-class="{'tab-item-active': isTabActive(), 'has-badge':badge, 'tab-hidden':isHidden()}"
  ng-disabled="disabled()"
  class="tab-item"
  icon="ui-icon ui-icon-shadow"
  title="Some translated title">
...
</a>
```

I've traced it down to the following [line in compile.js](https://github.com/angular/angular.js/blob/6f3b8622adce2006df5cf7eed4bf9262539004bd/src/ng/compile.js#L2448) in AngularJS.
