### ISSUE TITLE
Feature Request : Apply theme at runtime

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#8040]
#### Short description of the problem:

I'd like to be able to change theme at runtime (provide the user a way to change themes and do it without refreshing the app).

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Could be attached to the `Config` object. May however require the inclusion of the Sass files for the theme.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are currently looking at this as a possible feature, but I cant give a timeline on this at the moment.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#157

**Comment by mg1075** [comment]
@jgw96 - the issue link gives a 404. Do you know where the issue is now?
