### ISSUE TITLE
ionic stucks in installing npm packages

### ISSUE THREAD

**Issue by anandsiddharth** [driftyco/ionic#8041]
```
$ ionic start myBlank blank --v2
Creating Ionic app in folder /media/x-c0der/www/hybridapps/myBlank based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
```
And also shows this error `Error Initializing app: There was an error with the spawned command: npminstall`
```
$ ionic info 
Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.6
```

**Comment by devarg** [comment]
Hi @anandsiddharth  !
I tried to reproduce your issue and it currently works for me, have you considered/tried updating node to the latest version?

My Ionic Setup

`
C:\dev\testIonic>ionic info

Your system information:

Cordova CLI: 6.3.0
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v6.0.0
` 

Installation output:
`
C:\dev\testIonic>ionic start myBlank blank --v2
Creating Ionic app in folder C:\dev\testIonic\myBlank based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Adding initial native plugins
[=============================]  100%  0.0s
Saving your Ionic app state of platforms and plugins
Saved platform
Saved plugins
Saved package.json

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Make sure to cd into your new app directory:
  cd myBlank

To run your app in the browser (great for initial development):
  ionic serve

To run on iOS:
  ionic run ios

To run on Android:
  ionic run android

To test your app on a device easily, try Ionic View:
  http://view.ionic.io

New! Add push notifications, live app updates, and more with Ionic Platform!
  https://apps.ionic.io/signup


New to Ionic? Get started here: http://ionicframework.com/docs/v2/getting-started
`

**Comment by anandsiddharth** [comment]
@devarg Thankyou for reply
Actually, I left it to run for 15-20 minutes it installed, I think it was a network issue

**Comment by sudotamm** [comment]
ionic start --v2 -a 'RoomTest' -i com.ryan.roomtest RoomTest blank
Creating an Ionic 2.x app in RoomTest based on the blank template.

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
Installing npm packages (may take a minute or two)...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall

I aslo got this problem.
My dev tool info:
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

All dev tool is newest and stable, can you tell me how you solve this problem?
Thanks.

**Comment by anandsiddharth** [comment]
@sudotamm Trying updating npm with this `npm update -g npm`. I faced the same problem but it was resolved on improving network connection.

**Comment by DerekTso** [comment]
@anandsiddharth, i have upgraded my nodejs and npm to the latest version, but i still got the same error, i am sure my network is good, and after half hour, it still stuck as below:

ionic start myApp blank --v2

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
Installing npm packages (may take a minute or two)...

on Win7:
npm version: 4.5.0
node version: v7.9.0
ionic version: 2.2.2
cordova version: 6.5.0

could you advise? Thanks

**Comment by anandsiddharth** [comment]
hi @DerekTso 
add `--skip-npm` as arg
`ionic start myApp blank --v2 --skip-npm`
it will skip downloading dependecies via npm.
now what can you do is go inside the project folder
`cd myApp`
`npm install -ddd`
this will so debug output, then maybe you can find out the issue

**Comment by DerekTso** [comment]
@anandsiddharth, it works, thanks a lot
