### ISSUE TITLE
bug: ion-datetime shows blank months in the future.

### ISSUE THREAD

**Issue by aurbina83** [driftyco/ionic#8045]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>On ion-datetime, if you have both 'min' and 'max' values set to a month, day, and year, the datetime action sheet does not render the Months until you the day or the day or year.

```
<ion-content padding>
    <ion-item>
            <ion-label>Date</ion-label>
            <ion-datetime displayFormat="DDDD/MMM/YY"  pickerFormat="MMM/DD/YYYY" [max]="max" [min]="min" [(ngModel)]="date"></ion-datetime>
    </ion-item>
    <ion-item>
            <ion-label>Time</ion-label>
            <ion-datetime displayFormat="h:mm A" pickerFormat="h mm A" [(ngModel)]="date"></ion-datetime>
    </ion-item>
</ion-content>

import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as moment from 'moment';

@Component({
  templateUrl: 'build/pages/my-events/my-events.html',
})
export class MyEventsPage {

    public date;

    public minDate;
    public maxDate;


    public min;
    public max;
  constructor(private navCtrl: NavController) {

  }

  ionViewWillEnter() {
      this.min = moment().format("YYYY-MM-DD");
      this.max = moment(this.minDate).add(3, 'months').format("YYYY-MM-DD");
  }


}
```

It's not an issue with moment, as I've gotten the same results with regular Date objects.</span>

<span is-issue-template></span>

**Comment by AnujaK** [comment]
As per the documentation, by default, the maximum date is to the end of the current year. If you want to use future years, specify 'max'.

https://ionicframework.com/docs/v2/api/components/datetime/DateTime/
