### ISSUE TITLE
Plunkr url in new issue template not working

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#8046]
When you want to submit a new issue on Github a template is shown. The Plunkr sections shows urls for Plunkrs to use:

> #### Plunker that shows an example of your issue
> 
> **For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview
> 
> **For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview
> 
> 

However when you run http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview it gives a lot of Access-Control-Allow-Origin errors:

`XMLHttpRequest cannot load https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.
zone.min.js:1 Unhandled Promise rejection: XHR error loading https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js
	Error loading https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js as "@angular/core" from http://run.plnkr.co/QtomGzIhDkvovKEX/app.ts ; Zone: <root> ; Task: Promise.then ; Value: Error: XHR error loading https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js(…) Error: XHR error loading https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js
    at o (https://code.angularjs.org/tools/system.js:4:12694)
    at XMLHttpRequest.I.s.onreadystatechange (https://code.angularjs.org/tools/system.js:4:13219)
    at XMLHttpRequest.t [as _onreadystatechange] (https://cdn.rawgit.com/angular/zone.js/master/dist/zone.min.js:1:625)
    at e.invokeTask (https://cdn.rawgit.com/angular/zone.js/master/dist/zone.min.js:1:16565)
    at n.runTask (https://cdn.rawgit.com/angular/zone.js/master/dist/zone.min.js:1:13925)
    at XMLHttpRequest.invoke (https://cdn.rawgit.com/angular/zone.js/master/dist/zone.min.js:1:17678)o @ zone.min.js:1
zone.min.js:1 Error: Uncaught (in promise): Error: XHR error loading https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js(…)o @ zone.min.js:1
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/common@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/http@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/platform-browser-dynamic@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/platform-browser@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.
run.plnkr.co/:1 XMLHttpRequest cannot load https://npmcdn.com/@angular/core@2.0.0-rc.1/index.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.`

**Comment by rcjsuen** [comment]
Yup, this is really annoying.

**Comment by stefanaerts** [comment]
I think angular needs to use JSONP in a  some places instead of JSON.
http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by stefanaerts** [comment]
i found the solution:
use unpkg.com instead of npmcdn.

**Comment by basvdijk** [comment]
Thanks I replaced as suggested with unpkg.com The working template: http://plnkr.co/edit/H03WIlZpiiUBYbnj64x7?p=preview

**Comment by stefanaerts** [comment]
your welcome

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! This seems to have been an issue with npmcdn that seems to have resolved itself as the original plunkers are now working. Thanks!

**Comment by basvdijk** [comment]
Glad it is resolved! 👍
