### ISSUE TITLE
using tabs module with state.go(), [ion-nav-back-button] isn't display

### ISSUE THREAD

**Issue by meiyalei** [driftyco/ionic#8048]
Excuse me, i'm a developer with ionic 1. I had one question is trouble me with long time. I have no idea, so I need your help.

     I structure the project with tabs module， as follow: 
     <ion-tabs> 
         <ion-tab><ion-nav-view name="tab-news"></ion-nav-view></ion-tab>
         <ion-tab><ion-nav-view name="tab-activities"></ion-nav-view></ion-tab>
         <ion-tab><ion-nav-view name="tab-account"></ion-nav-view></ion-tab>
     </ion-tabs>

     The problem is that when i was focused on view named 'tab-activities', then using state.go('tab.news-detail'，{activity:1}), and the router executed correctly, but '<ion-nav-back-button>' isn't display. I don't know why. 
     
     Do you tell me what i should do to solve this problem. If you can, pls provide a demo for me. Thanks a lot.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by meiyalei** [comment]
Thanks for you replying. But Could you give a link with this issue on your forum.
