### ISSUE TITLE
ionic2 how to set platform

### ISSUE THREAD

**Issue by snopein** [driftyco/ionic#8051]
in ionic1 i use `setPlatform('ios') ` to set platform 
so how to set platform in ionic2 
/--------------------------------------------------------------------
now!!!   i should know how to do
app/app.ts
`ionicBootstrap(AppName, [], {mode: 'ios'});`

**Comment by sdurighello** [comment]
As of now, apparently, the only way that worked for me in Ionic 2 was to use the app config as explained here: https://ionicframework.com/docs/api/config/Config/
For example, to force 'iOS' look and feel when not on a mobile platform (which defaults to 'core'):
```
IonicModule.forRoot(MyApp, {
    platforms: {
        core: { mode: 'ios'},
    },
})
```
