### ISSUE TITLE
UUID is not set

### ISSUE THREAD

**Issue by jaworskm** [driftyco/ionic#8053]
#### Short description of the problem:

What sets __UUID__ for the _Ionic Deploy_ service - With the new (or it stopped working with the old pre-cloud version too) Ionic Cloud library?

`$ionicDeploy.check()` never returns success because the `UUID` is always unset, while I am testing the application. This was not the case four weeks ago; it just stopped working.

#### Additional Thoughts

I have migrated the application to the new library (plugin and cloud). My issue is the same as far as I can tell. I call getSnapshots() and get an empty array. I got check() and always get `false`. I do not see any Network traffic. If I call getMetadata I always get an error related to not have a valid uuid. I see the same code in the checkForUpdates in the *.java file.

```
String deployed_version = this.prefs.getString("uuid", "");
```

I do not have a uuid as far as I know because I just loaded the application locally and was testing to see if I could pull down a later project I `ionic upload —note “0.21.08" —deploy qa` with. 

The crux of my problem seems to be related to not having a uuid in my application when I am running locally. I had the same problem with ionic cli 1.7.1 and the old libraries; because the errors from the service were the same.

#### What behavior are you expecting?

It would return `true` because I deployed the application with a higher version with `ionic upload —note “0.21.08" —deploy qa`.

My .io-config.json is

```
{"app_id”:”…","api_key”:”…"}
```

My ionic.config.json is

```
{
  "name": “…",
  "v2": false,
  "typescript": false,
  "app_id": “…"
}
```

My code which connects the app_id is:

```
.config(function ($ionicCloudProvider) {
  $ionicCloudProvider.init({
    core: {
      app_id: ‘…'
    }
  });
})
```

My application code where I check versions is:

```
.controller('X', function($ionicDeploy) {
  $ionicDeploy.check(function(hasUpdate) {
    // hasUpdate is always false, but in the Java object it breaks at... (see below)
  });
});
```

In the checkForUpdates.java file it breaks when asking for UUID.

```
String deployed_version = this.prefs.getString("uuid", "");
```

**Which Ionic Version?** 

1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#181

**Comment by jgw96** [comment]
Hello, because this issue was related to the Ionic Cloud and not the Ionic framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
