### ISSUE TITLE
Implementing ExceptionHandler In Ionic2

### ISSUE THREAD

**Issue by dalezak** [driftyco/ionic#8054]
I'd like to implement an `ExceptionHandler` in my Ionic2 app, but can't find any documentation or examples.

I followed the instructions on http://stackoverflow.com/a/39189175/385730, but the provider does not seem to be working.

Other discussions suggest its possible using Angular2's https://angular.io/docs/js/latest/api/core/index/ExceptionHandler-class.html.

How do you implement `ExceptionHandler` in Ionic2?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by dalezak** [comment]
For those who stumble onto this issue, here is the forum post https://forum.ionicframework.com/t/implementing-exceptionhandler-in-ionic2/63196 with the question.
