### ISSUE TITLE
Ionic 2 : popToRoot() doesn't redirect to root component ( home page )

### ISSUE THREAD

**Issue by badis** [driftyco/ionic#8055]
Every thing work fine in this function. but this.nav.popToRoot() doesn't work in that location. If i move it to the beginning of the function it works correctly. Doesn't any one has a logical explanation for this.

Thank you in advance for your time and consideration.

Here is the code in a booking.ts component:

` 
  book(){

    let newReservation = {
        _id: this.room._id,
        from: this.details.from.substring(0,10),
        to: this.details.to.substring(0,10)
    }

    let loading = this.loadingCtrl.create({
        content: "Booking room..."
    });

    loading.present();

    this.roomsService.reserveRoom(newReservation).then((res) => {

        loading.dismiss();
        console.log("Room reserved successfully ... ");
        this.nav.popToRoot();

    }, (err) => {
        console.log(err);
    });

}
`

**Comment by cojj90** [comment]
@badis 

Ionic navigation is bit funky. Usually, I can resolve most of nav issues by promise chaining everything...

Try the following:
```
loading.dismiss().then(
   ()=>{
       this.nav.popToRoot();
   }
)
```

**Comment by jgw96** [comment]
@badis Hello! Thanks for opening an issue with us! Would you mind trying 
```
  import { App } from 'ionic-angular';
  constructor (public app: App) {};
  this.app.getActiveNav().popToRoot()
```

**Comment by badis** [comment]
@jgw96  , @cojj90  thank you.
`this.nav.popToRoot();` and `this.app.getActiveNav().popToRoot()` are equivalent is this case.
it only works after i have chained `loading.present();` like this : 

```
      loading.present().then(() => {
            this.roomsService.reserveRoom(newReservation).then((res) => {

                loading.dismiss().then(
                    () => {
                        this.nav.popToRoot();
                    }
                );
            }, (err) => {
                console.log(err);
            });
        });

```
Thank you once again @cojj90
