### ISSUE TITLE
Ionic 2: Searchbar clear and blur event issue

### ISSUE THREAD

**Issue by cambronjay** [driftyco/ionic#8056]
#### Short description of the problem:
The searchbar ionInput event fires after the input is cleared of text

#### What behavior are you expecting?
The searchbar should not fire ioninput after clearing the input. 

**Steps to reproduce:**
1. Create an ionic project
2. Add a searchbar component to your project utilizing an api like GitHub user search
3. Try clearing the searchbar and you will get a trim error if you try to only accept search phrases with a 3 character minimum. Empty strings cause this issue too.

```ts
  //User searchbar event
  search(search: any) {
    let val = search.target.value;
    //Search only if character length is greater than 3 and search query is not empty
    if (val.trim() == '' || val.trim().length < 3) {
        
   }else{
        this.githubservice.searchUsers(this.val)
          .then(data => this.results = data)
    }
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 The problem was fixed by doing this:
```
  //User searchbar event
  search(search: any) {
    this.val = search.target.value;
    //Search only if character length is greater than 3 and search query is not empty
    if ((this.val && this.val.trim() != '') && this.val.trim().length >= 3) {
        // Search for users using service
        this.githubservice.searchUsers(this.val)
          .then(data => this.results = data)
    }
  }
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2 latest

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
@cambronjay this is the expected behaviour, and it is enforced by the browser which it is the one that fires the events.

You should always check if the value is valid before trying to trim the string.
