### ISSUE TITLE
Switch compilerOptions to es6 in tsconfig.json causes error

### ISSUE THREAD

**Issue by ssdong** [driftyco/ionic#8059]
I am trying to use `async` and `await` in my project but when I try to compile it with `ionic serve` , it gives me the following error:

```
Error TS1311: Async functions are only available when targeting ECMAScript 6 and higher.
```

Thus, I changed  `"target": "es5",` to `"target": "es6",` in `tsconfig.json` and tried to compile again.

This time, I expect it should work seamlessly but I got the following error:
```
TypeScript error: /node_modules/typescript/lib/lib.es6.d.ts(17,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: /node_modules/typescript/lib/lib.es6.d.ts(237,5): Error TS2300: Duplicate identifier 'EPSILON'.
TypeScript error: /node_modules/typescript/lib/lib.es6.d.ts(272,5): Error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
TypeScript error: /node_modules/typescript/lib/lib.es6.d.ts(279,5): Error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
TypeScript error: typings/globals/es6-shim/index.d.ts(3,14): Error TS2300: Duplicate identifier 'PropertyKey'.
TypeScript error: typings/globals/es6-shim/index.d.ts(6,5): Error TS2300: Duplicate identifier 'done'.
TypeScript error: typings/globals/es6-shim/index.d.ts(7,5): Error TS2300: Duplicate identifier 'value'.
TypeScript error: typings/globals/es6-shim/index.d.ts(245,5): Error TS2300: Duplicate identifier 'EPSILON'.
```
_(The above error messages are part of the entire error and the rest are the same as above)_

This is weird. But generally, it seems like it includes more than one typescript type information file and both of them define same part of content. 

So here is what I tried to after I gained this error, I looked at `tsconfig.json`, it is as following:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "filesGlob": [
    "**/*.ts",
    "!node_modules/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings/global",
    "typings/global.d.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

( **First, I would like to point out something strange in this `tsconfig.json` file. It seems like ionic team never updates this file? I didn't find `filesGlob` definition and `typings/global` and `typings/global.d.ts` don't even exist in my project...** )  As you can see from the error message above, one of the typescript type information files actually comes from `typings/globals`(notice the `s`). I thought this might be the reason of the error since this `exclude` never worked and it is stilling including the typescript type information files. Thus, I changed those 2 lines to `typings/globals` and `typings/index.d.ts` (there is no `global.d.ts` file but there is `index.d.ts` file under `typings` folder) and compiled again. 

Unfortunately, I failed again... `ionic serve` still gives me the same errors. 

I am getting a bit frustrated but this time what I did is to directly modify this file `typings/globals/es6-shim/index.d.ts` which conflicts(see the above error message) and delete those duplicate part of code. 

It worked...

However, I don't think this is the right solution... I tried to google a lot but didn't find the solution other than directly modify `xxx.d.ts` files.

Anyone could help? I just want to get this `compilerOptions` targeting to `es6` work... Thanks!

The following is the info from `ionic info`

```
Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v6.4.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by Kobzol** [comment]
Just remove the es6-shim typings, you don't need them with ES6, and it will work :-) At least it worked for me, I changed it to ES6 and added babel transpilation to get `async` functionality.

**Comment by ssdong** [comment]
@Kobzol Hi Kobzol. Thank you for your help. I tried what you said and removed `typings/globals/es6-shim/index.d.ts` but then the file `typings/index.d.ts` is referring to the file I removed and it's causing an error. 
```
TypeScript error: typings/index.d.ts(1,1): Error TS6053: File 'typings/globals/es6-shim/index.d.ts' not found.
```
I also tried to remove the entire `typings` folder but not work either. Do you mind if you can be a bit more specific about it? Thanks! :)

**Comment by ssdong** [comment]
@Kobzol I think I got it. The file `typings/index.d.ts` is referring to `typings/globals/es6-shim/index.d.ts` with `/// <reference path="globals/es6-shim/index.d.ts" />`, thus, if I just remove `typings/global/es6-shim/index.d.ts`, it's not working. Getting rid of that line in `typings/index.d.ts` actually works. 

Just curious and would like to ask ionic team members, is there any reason to include this `typings` folder in the template ? It seems unnecessary and redundant. Since `node_modules` already have `typescript` and if we change `compilerOption` to `es6`, it sure will cause an error. Thanks.

**Comment by Kobzol** [comment]
Yeah just removing the file leaves your typings installation in am inconsistent state :-) You should remove it from typings.json, delete the typings folder and then run typings install.

**Comment by jgw96** [comment]
Hello! Thanks for using ionic! At this time with our current setup and the current version of typescript we use we do not officially support transpiling to ES6 instead of ES5. Thanks for using Ionic and sorry for any inconvenience this causes
