### ISSUE TITLE
Ion-scroll should allow content to be scrolled on x and y axis simultaneously

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#806]
I have an image element that is too wide and too high to fit in the standard viewport. I want to make it scrollable on the x and y axis.

I've tried to wrap it in a `<ion-scroll direction="xy">` element. The horizontal scrolling works, but the vertical one bounces back the content.

See http://plnkr.co/edit/oY8Q4hJ8yFoz56RxvF4a?p=preview for an illustration.

When removing `scroll=false` and adding `overflow-scroll="auto"` to the ion-content element, it sort of seems to work, but the scrolling is sometimes locked to one axis depending on if you started moving the content up and down or left and right. It should be able to move on both axis simultaneously.

**Comment by rajeshwarpatlolla** [comment]
In the below plunker i have some content below the scrollable section, and below that i have some other content. I want to see that content. But i am unable to do so.

http://plnkr.co/edit/WLWiNo023SRJrSb5UxlH?p=preview
