### ISSUE TITLE
Repo have't been updated for almost 2 weeks?

### ISSUE THREAD

**Issue by itrethan** [driftyco/ionic#8061]
Hey Ionic team:

I am curious about the status of the repo, it haven't been updated for almost 2 weeks, and angular version still stays at rc4. I hope it's just because you guys are having vacations.

Since ionic is still at rc4, it's blocking my project to upgrade to latest angular versions for new feature. Anybody have an idea about what's going on with the repo?

Thanks,

**Comment by lain-me** [comment]
They mentioned that the repo is currently on freeze (and do not accept PRs). They are working on AoT and tree-shaking (probably rc6), which changes many things, thus you have to be patient.

**Comment by itrethan** [comment]
@lain-me Thanks, indeed angular have changed a lot in recent releases. Looking forward to beta.12

**Comment by herbzi** [comment]
Yea look at this issue for updates on their progress: #6776 .
They have a branch 200+ commits ahead of master and are working hard on the new build proccess.

**Comment by cojj90** [comment]
Angular2 RC7 is out now. Patiently but eagerly waiting for corresponding update from Ionic :)

**Comment by jgw96** [comment]
Hello all! Thanks for the concern! We are definitely hard at work on beta.12 which will be running Angular 2 rc7 and include a completely new build process which includes AOT compile, treeshaking, minification and more to dramatically lower our start up times and increase performance to where it needs to be. This is the branch where most of the work is going on https://github.com/driftyco/ionic/tree/ngmodule-build. Thanks!

**Comment by itrethan** [comment]
@jgw96 Thanks for the update, can we have an ETA?

**Comment by i-Dee** [comment]
@jgw96 The link doesn't exist again

**Comment by i-Dee** [comment]
@jgw96 The link doesn't exist again
