### ISSUE TITLE
Error: collection-repeat tried to compute the height of repeated elements "item in modalData.searchListItem", but was unable to. Please provide the "item-height" 

### ISSUE THREAD

**Issue by cesarin3134** [driftyco/ionic#8062]
Hi there, 
I used collection-repeat to load a long list of items, I chose it instead of ng-repeat because it's more fast to render data. but when the items are loading I got this error :

`Error: collection-repeat tried to compute the height of repeated elements "item in modalData.searchListItem", but was unable to. Please provide the "item-height"`

my code is it :  (ionic version 1.7.13)

`<ion-item collection-repeat="item in modalData.searchListItem | filter:search" ng-click="ctrl.doActionOnClick(item.codice)">
                <span ng-if="searchModalType == 'dutyCodes' || searchModalType == 'officeCode'">{{item.codice}}  </span>{{item.desc}}
            </ion-item>`

is there any way to fix it ? thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#95
