### ISSUE TITLE
Toast dismiss closes modal window

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic#8066]
#### Short description of the problem:
When modal is open and toasts are triggered by user few times (no particular number) then the last dimissed toast hides modal

#### What behavior are you expecting?
when toast is hidden it shouldn't hide modal

**Steps to reproduce:**
1. Go To http://plnkr.co/edit/PyqYXb?p=preview
2. Click on "Show Modal"
3. Click on "Toast" in modal multiple times (open devtools and wait until old toasts will be removed from the DOM and click few more times)

![ionic-toast-issue](https://cloud.githubusercontent.com/assets/1159966/18480410/3ecf4050-79e1-11e6-94c1-b485bdee8c4e.gif)

**Another case**:
1. Go To http://plnkr.co/edit/PyqYXb?p=preview
2. Click on "Show Modal"
3. Click on "Toast" in modal once
4. Click on "close" modal button at the top right corner

Actual result:
Modal just disappears without any animation

Expected result:
Modal hides with animation

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 2.0-beta.11

#### Plunker that shows an example of your issue

http://plnkr.co/edit/PyqYXb?p=preview

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! With my testing this only seems to happen if i spam the toast button. When tapping the toast button at a regular interval this issue does not seem to happen. Do you experience the same in your testing?

**Comment by stalniy** [comment]
Hello this is just use case to show. In original app I have file upload component inside modal and when user uploads file with wrong file type I show toast message but when toast is closed it also closes my modal windo which contains a lot of other info. So user just looses everything and needs to restart work. 

I use a lot of toasts in my app, ui is not blocking so user is able to quickly does different operations which results in a toast what leads to this strange behavior. 

Spamming toast button is the simplest way to reproduce this bit I'm sure there are other use cases. If there is a need I will find them

**Comment by stalniy** [comment]
The issue is somewhere in the `NavigationControllerBase.remove` method. It relies on indexes too early. It should find index of removing view at the time when it try to remove it with splice. 

Otherwise if somebody else (ie another overlay lets call it B) is dismissed (splice was called for this earlier) at the moment when  index of removing view ( let's call it A) was found and particular remove (ie splice call for A) then `_views` array is changed and overlay A points to the wrong index. that's why it removes overlay A-1(that one which was before A in stack)

**Comment by stalniy** [comment]
The initial use case in my app:
![modal-toast-issue](https://cloud.githubusercontent.com/assets/1159966/18510526/2ed06336-7a87-11e6-9571-824bfc933ca8.gif)

**Comment by jgw96** [comment]
Thanks for all the info. There are currently alot of changes going on with the internals of navigation which should fix this. I will confirm when we get to the testing stage of these changes. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! I am happy to report that I cannot reproduce this issue with beta.12. Look out for the release soon! (:
