### ISSUE TITLE
bug: Can't use NavPush on MyApp class (app.ts)

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8067]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am injecting NavController:
`import { Platform, ionicBootstrap, NavController } from 'ionic-angular';
`

And put it inside the class:
`constructor(private platform: Platform, private navCtrl: NavController) { }
`

I have buttons on the menu, with (click)="goToPage(page)", this is the function:
```
goToPage(page): void {
	this.navCtrl.push(this.pages[page]);
}
```

This is the errors i get:
`ORIGINAL EXCEPTION: No provider for NavController!`
https://s21.postimg.io/ga91h3uc7/Screenshot_from_2016_09_13_22_24_19.png

So I added NavController to providers array:
```
@Component({
	templateUrl: 'build/app.html',
	providers: [NavController]
})
```

Now I don't have any errors when i enter app, but if I click on any button (that using goToPage function), this is the error I get:
ORIGINAL EXCEPTION: TypeError: this.navCtrl.push is not a function

Any suggestions? It's know issue?</span>

<span is-issue-template></span>

**Comment by cojj90** [comment]
You should not have to provide NavController. 

On Parent Component (its likely your menu will be sitting here), you need to use

`import { Nav } from 'ionic-angular';` 
and 
`@ViewChild(Nav) nav: Nav;`

To control navigation.


A good example is the Ionic Conference App.
https://github.com/driftyco/ionic-conference-app

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by tycho01** [comment]
@cojj90: thank you for providing the right clue. I can confirm the `this.navCtrl.push is not a function` error is specifically caused by including `NavController` in the `providers` list. Removing it fixes the error.
