### ISSUE TITLE
Update peer-dependency for upcoming Ionic2 beta 12

### ISSUE THREAD

**Issue by cojj90** [driftyco/ionic#8069]
Mainly:

Angular2@rc6 => rc7
rxjs@5.0.0 beta 11 => beta 12
zone.js @0.6.17 => 0.6.21

**Which Ionic Version?**  for upcoming 2.0 beta 12

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! This is actually already being handled on the `ngmodule-build` branch.
