### ISSUE TITLE
Ionic 2: Ion-Datetime Input Not Working Inside Popovers

### ISSUE THREAD

**Issue by sollabeck** [driftyco/ionic#8071]
#### Short description of the problem:
I like the datepicker provided by ion-datetime, but I'm running into issues using it on a popover on beta version 11. Tested on previous versions of the beta and it seemed to be working.

#### What behavior are you expecting?

I'm expecting the default datepicker to show up with the ability to select dates.

**Steps to reproduce:**
1.  Create a popover
2.  Use ion-datetime inside the popover
3. Click on input

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
In terms of other issues, I had a similar console output as the one shown in issue #7038:
Whereas the conditions are different, the error and UI issue are almost exactly what I am experiencing.

Also, I only really need ion-datetime, but I noticed other ion inputs didn't work (like ion-select).

**Which Ionic Version?** 2

#### Plunker that shows an example of your issue

http://plnkr.co/edit/e9Fwt1MiBFBrGu1obQWd?p=preview

- **(Click the popover text on top right corner to open a popover)**

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by meer21** [comment]
I am facing a similar problem. I too am using beta version 11.

**Comment by RicardoZeballos** [comment]
Yep this is a weird issue. Version 10 was working fine for me, hopefully a fix is found these clients too savage right now.

**Comment by sollabeck** [comment]
bump 10char

**Comment by jgw96** [comment]
Hello all! I am happy to say that this bug has been fixed and will be in the beta.12 release. Thanks for using Ionic!
