### ISSUE TITLE
ionic lib 1.3.1 can write <style>out of <ion-view>

### ISSUE THREAD

**Issue by wzhsh90** [driftyco/ionic#8074]
I writen a codepen ' http://codepen.io/wzhsh90/pen/pEjZXw '
you can find info from console.
the only different piont between function A and function B is their html.
<style type="css/text"></style>
<ion-view></ion-view>

function A not work well ,function B work correctly.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You should be writing your styles in a seperate css file and not inline in your templates. Thanks for using Ionic!
