### ISSUE TITLE
scroll animation still active upon changing states

### ISSUE THREAD

**Issue by israelglass123** [driftyco/ionic#8076]
Upon using `ion-scroll`, if the state is changed while still scrolling the animation continues,
expecting the elements to still be on the DOM, however these elements may not be on the DOM.
It thinks that the "container" element exists, while it is no longer on the DOM.
This produces an error:

``` javascript
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
```

I would expect there not to be an error upon such behaviour.

**Steps to reproduce:**
1. use the chrome mobile emulator ( refresh to fully activate emulator mode )
2. scroll the "click me pls" buttons
3. click on a button ( this scrolls and changes state [ while scrolling ])
4. look at the error in the console

**Other information:**
run as MOBILE,
I tested it in mobile chrome emulator

**Which Ionic Version?** 1.3.1
#### Plunker that shows an example of your issue

http://plnkr.co/edit/4AhEQMShybHtipnyI8JL?p=preview

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#94
