### ISSUE TITLE
problem of cdn firebase angularjs

### ISSUE THREAD

**Issue by Rebaiahmed** [driftyco/ionic#8077]
Helloe , i developed small ionic mobile application , with firebase and github api , and when i run it i get a Black screen , and the app is not working , i have inspected it with chrome/inspect , i get this error
![error_ionic](https://cloud.githubusercontent.com/assets/13053759/18510608/dc4cfc7e-7a76-11e6-92d4-89699d26e14d.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
