### ISSUE TITLE
Ionic 1 Feature : Hold specfic view permanently in cache 

### ISSUE THREAD

**Issue by flexxis** [driftyco/ionic#8078]
Hello,

i would like to mark specific views with a flag that prevents them from being removed from cache. Current behaviour is that if maxnumber in  `views.maxCache(maxNumber)` is reached the oldest view will be removed. However there are some cases in which views are very "costly" to initialize again. 
I don't want to raise the maxnumber, but rather mark a specific view as important to be kept permanently in cache. Other views can be deleted depending on their last access time as before.

It would be nice if a new value could be assigned to the cache property in state provider or in the template.

```
$stateProvider.state('myState', {
   cache: **permanent**,
   url : '/myUrl',
   templateUrl : 'my-template.html'
})
```

Disable cache with an attribute

```
<ion-view cache-view="permanent" view-title="My Title!">
  ...
</ion-view>
```

Thanks in advance,
felix

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not plan on adding any new features to Ionic 1. Because of this I will be closing this issue for now. Thanks for using Ionic!
