### ISSUE TITLE
Click Events In SlideBox Fire Multiple Times

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#808]
If an `ion-slide-box` `ion-slide` has elements with `ng-click`,  the events fire multiple times.

Forum : http://forum.ionicframework.com/t/ng-click-fires-twice-within-slide-box/1884
Sample : http://plnkr.co/edit/dyna4CwE71v7L8qvbpJP?p=preview

**Comment by elFua** [comment]
In version 1.3.0 I am still getting ng-click firing twice after the 4th or 5th slide. For the first several slides everything is ok.

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3 Build version 7D175 
```
