### ISSUE TITLE
File api is incomplete (e.g. getFreeDiskSpace, writeFile) and docs is incomplete (e.g. readAstext)

### ISSUE THREAD

**Issue by dragGH102** [driftyco/ionic#8080]
I'm using Ionic 2 latest beta (37) and trying to work with files (**File** plugin @ ionic-native).

Some methods (readDire, writeDir, ...) work normally.
However others are either **missing** (not implemented as per also in the Typescript definitions), for example:

- getFreeDiskSpace
- writeFile

or lacking a **proper documentation**. For example...

- readAsText: how to do it **without overriding a file**? (apparently the only way to get a FileEntry is a createFile/writeFile  but both either override the file or throw an error if it exists and replace = false). Eventually refer to my SO question at http://stackoverflow.com/questions/39494174/how-to-get-a-fileentry-to-then-use-readastext-in-cordova-ionic2

I understand this is still a beta but I was wondering if this is intentional of a "work in progress" (in which case feel free to close this issue)?
Thank you

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#552

**Comment by jgw96** [comment]
Hello, because this was an issue with `ionic-native` and not the Ionic framework i have moved this issue to the appropriate repo. Thanks for using Ionic!
