### ISSUE TITLE
Cannot Dismiss Loading at Same Time as Displaying Toast

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#8081]
#### Short description of the problem:
When a loading indicator is displayed, it cannot be dismissed at the same time a toast is created.  Instead, the toast will display and the loading indicator will continue displaying forever.

*Example Scenario*: A user submits a form and a loading indicator is displayed while the API call is processed.  Once the API call is complete, the loading indicator should be dismissed and then a friendly toast message should show saying "We've saved your changes."

These two operations CANNOT currently be perform at the same time.  Instead, the loading indicator must be dismissed and then at least 101ms later, you can display the toast without causing interference with dismissing the loading indicator

#### What behavior are you expecting?
Displaying a toast at the same time as dismissing a loading indicator should not cause the loading indicator to be "stuck".

**Steps to reproduce:**
1. Create and present a loading indicator
2. Dismiss the loading indicator at the same time as creating and presenting a toast
3. Note that the loading indicator will not dismiss

```
// Dismiss an existing loading indicator
this.loading.dismiss();

// At the same time, create and present a toast message
let toast = this.toastCtrl.create({
	message: 'I am a toast that conflicts with loading!',
	duration: 3000, 
	position: 'bottom'
});

// The dismiss will not work and the loading indicator will remain forever

toast.present();
```

**Other information:** 
Seems possibly related to #7903
 

**Which Ionic Version?** 2.0.0-beta.11

#### Plunker that shows an example of your issue
http://plnkr.co/edit/lDx6Q0LkkWG2GGKtorLZ

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by calendee** [comment]
Also, the 101 ms mentioned in the original posting only means the loading indicator gets removed.  Unfortunately, the `ion-backdrop` will NOT get removed.  If you wait at least 312 ms before displaying the toast, the loading indicator and its `ion-backdrop` will all be removed.

**Comment by aggarwalankush** [comment]
use 

```
this.loading.dismiss().then(() => {
     toast.present();
});
```

http://plnkr.co/edit/hTHcLfZ3IZRmOOSKH3XP

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! The above solution posted by @aggarwalankush is the correct way to handle this. All of our navigation and transitions in Ionic 2 are async, so all the nav methods return promises to allow you to easily handle this. Thanks for using Ionic and thanks @aggarwalankush for posting the solution!

**Comment by calendee** [comment]
Thanks for the great solution @aggarwalankush
