### ISSUE TITLE
Popover is always positioned in center of screen

### ISSUE THREAD

**Issue by John-Luke** [driftyco/ionic#8083]
![capturar](https://cloud.githubusercontent.com/assets/15695983/18525613/9eae4b80-7a93-11e6-939a-9ab82fccf2ab.PNG)

**Comment by aggarwalankush** [comment]
Make sure you are sending the event object.

http://ionicframework.com/docs/v2/api/components/popover/PopoverController/

**Comment by John-Luke** [comment]
It worked!! Thanks for help me. I really need to read the docs
