### ISSUE TITLE
Angular 2 is now out of RC!

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#8084]
Angular 2 is now out of RC:
https://github.com/angular/angular/blob/master/CHANGELOG.md

Please update to the latest :)

**Comment by ansarizafar** [comment]
1+

**Comment by Ronsku** [comment]
+3

**Comment by dylanvdmerwe** [comment]
The Ionic team is normally great at keeping Angular updated in each release. Let them do their thing.

**Comment by manucorporat** [comment]
We are in close communication with the angular team, and we have been working hard to bring the AoT compiler to ionic, it is very new technology without documentation or real examples out there.

We know the final release is out 😄, Ionic of course will use it, but as I said, it is not an one-file-change.

In fact, head of master is currently using rc7, and that required weeks of work and tons of changes: https://github.com/driftyco/ionic/commit/52ada1ca6d00b35fa9bd01b6be1e2904a505dd9e
