### ISSUE TITLE
bug: Hi, i would simply advise you about newsletter bug

### ISSUE THREAD

**Issue by manzullo** [driftyco/ionic#8085]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi, i received your newsletter from max this morning, i really like your project and i just simply would tell you about links in your email doesn't work. I hope it could be usefull for you to know it.
Best Regards,
Alessandro Manzullo</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
