### ISSUE TITLE
Ionic 2, Dark Theme, Alert Boxes

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#8086]
Hi,

Dark themes for list items, toast, navbar, excellent. Thanks very much.

Any chance we could have the alerts themed as well?

Thanks

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You can check out this issue https://github.com/driftyco/ionic/issues/7867 for instructions on how to use the dark theme. Be aware that this will be changing to be much easier to set up in beta.12. Thanks for using Ionic!

**Comment by WillGeller** [comment]
I am not sure if this has changed I am on the latest Ionic 3.6.0 and am using the dark theme by replacing the default import in variables.scss as so:

> // App Theme
//@import "ionic.theme.default";
@import "ionic.theme.dark";

For the most part the dark theme looks good but I did have to add to app.scss:

> h1, h2, h3, h4, p {
  color: white !important;
}

And the most noticeable problem is the **alerts** are still styled with white background dark text.

Wondering if there is something else I should do to enable the dark theme before adding more custom CSS
