### ISSUE TITLE
Update Angular 2.0.0 in package.json

### ISSUE THREAD

**Issue by ramonornela** [driftyco/ionic#8090]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are currently working on the beta.12 release which among a ton of other new things such as a completely new build process that includes AOT compile, treeshaking, minifcation and more will also be running Angular 2.0 final! Thanks!

**Comment by izee** [comment]
is beta.12 compatible with Angular 2.0 final ?

**Comment by kelvindart** [comment]
Looking at the commit history, it appears yes it will be:
https://github.com/driftyco/ionic/commit/3710671d79b8af7e3f5c3be632e82bf02797d2b5
https://github.com/driftyco/ionic/commit/60f8f5b2e7d7271269d718a14a4ba4527495335d
