### ISSUE TITLE
Prevent Ionic from dying when template compilation fails and recompile it on next attempt

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#8092]
#### Short description of the problem:

If Ionic (or Angular?) encounters an error during compiling a page it won't retry and that pages becomes unaccessible for the rest of the app lifecycle. Also the ionic app just kills itself.. This happens for example when some data is corrupted, and the template tries to reach some property of null. Eg: `data.name` where data is a property of the page but it's value is undefined or null. 

#### What behavior are you expecting?

Ionic doesn't kill itself and it tries to reparse the page template if it previously encountered an error while parsing. 

**Steps to reproduce:**
1. Click Test page with Data and go back
2. Click Other page and go back
3. Open Test page without Data
4. Try to open it again, and notice Ionic didn't try to open it this time.
5, Try to open the other page, and notice that doesn't open as well.
6, Realize, the ionic app died. 

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

http://plnkr.co/edit/m3fzZ8?p=preview

**Run `ionic info` from terminal/cmd prompt:** 

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This will be solved in the beta.12 release with our new build process as template compilation will be done ahead of time at build time instead of dynamic compilation when the user is using your app. Also, you can use your [lifecycle events](http://ionicframework.com/docs/v2/api/components/nav/NavController/#lifecycle-events) to check for the existence of data before pushing a page. Thanks for using Ionic!

**Comment by NoNameProvided** [comment]
Hmm, but how can AOT compilation solve rendering corrupted data? Let's say I have this in my template: 

```
<div *ngIf='data'>{{ data.article.title }}</div>
```

And data is loaded dynamically. This can't be checked and compile time. And still it kills the app right now if eg an empty object arrives, rendering the app useless. I know I can use something like `{{ data.  && data.article && data.article.title  }}` or checking the data before assigning it to the `data` property. I know I am being lazy for wanting Ionic to handle this for me but still I think a page which encountered a rendering error should try to load itself again the next time. 

PS: I am not even sure if this an Ionic issue or an Angular issue.

**Comment by jgw96** [comment]
@NoNameProvided Thanks for explaining more! Error handling is something that you would need to handle in your app. Unfortunately it is not a simple thing to try to reload a template if that template encounters an error and in general is something that needs to be avoided as every render that happens blocks the thread. Also, Ionic does not actually handle the rendering of templates directly, that is actually an Angular thing. Thanks for using Ionic!
