### ISSUE TITLE
menu-toggle directive issue with disable-user-behavior

### ISSUE THREAD

**Issue by thetwosents** [driftyco/ionic#8093]
Hey guys, 

I'm having an issue regarding the disable-user-behavior functionality that is (unfortunately) pretty undocumented. That said, I have an issue when using menu-toggle directive on the navbar button. 

I know there are work arounds for this, but wanted to bring to attention, if the nav icon button has menu-toggle on it, it will disable the user behavior and hide the button.

<3 you guys.

Jon

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a code snippet for the issue you are describing? Im not sure if im understanding the issue totally. Thanks!

**Comment by thetwosents** [comment]
`<ion-header-bar align-title="center">
	  <div class="buttons">
		<button class="button" menu-toggle="left"><i class="ion-navicon"></i></button>
	  </div>
	  <h1 class="title">View Title</h1>
	  <div class="buttons">
	  </div>	
</ion-header-bar>`

the `menu-toggle` is the attribute that will cause the issue

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#93
