### ISSUE TITLE
bug: Chrome://inspector is not remove

### ISSUE THREAD

**Issue by ravirasadiya** [driftyco/ionic#8094]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am unable to remove chrome://inspect remote debugging after final release version of apk! Anyone any idea how make it possible for security reason?
Thanks</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
