### ISSUE TITLE
No proper documentation to update any vale inside menu.

### ISSUE THREAD

**Issue by rhuldip** [driftyco/ionic#8095]
I am having a menu whose html i have written in app.html-
```
<ion-menu [content]="mycontent">
  <ion-toolbar class = "menuUserName">
    <ion-title>{{userName}}</ion-title>
  </ion-toolbar>
  <ion-content>
    <ion-list>
        Item1
     </ion-list>
  </ion-content>
</ion-menu>

<ion-nav #mycontent [root]="rootPage"></ion-nav>
```

My app flow is login->homepage. when the user login the app,it will get username from a service. How can i pass this data to my ionic2 menu to update username.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
