### ISSUE TITLE
ion-datetime Scroll momentum not working on iOS

### ISSUE THREAD

**Issue by huysamen** [driftyco/ionic#8096]
#### Short description of the problem:

Momentum scrolling on the `ion-datetime` component does not work on a physical iOS device.  It works perfectly in the browser and in the simulator.

It stutters and then very slowly stops on a date.  If you tap, rather than scroll, then the animation is smooth and transitions to the date you tapped on.
#### What behavior are you expecting?

When using the `ion-datetime` component, when scrolling to select the dates on a physical iOS device, momentum scrolling should work.

**Steps to reproduce:**
1. Add `ion-datetime` component to any page
2. Run app on physical iOS device
3. Try to use momentum scrolling

**Which Ionic Version?** 1.x or 2.x
Ionic 2 beta 11

**Comment by Nrvax** [comment]
Same issue on Android v6.0.1, the scroll is very slow and stutters

**Comment by sssemil** [comment]
Duplicate-ish - https://github.com/driftyco/ionic/issues/6613

**Comment by stschindler** [comment]
I'm also having this issue. Fast in desktop browser, slow on Android 6.0, HTC One M8.

**Comment by scottgeye** [comment]
Same issue on iOS with RC1.  I have pickers in two different parts of my app.  One simple form where the picker is completely smooth and a different complex page (lots of DOM manipulation) where the performance problem happens.

Not sure it it helps, but in doing a little profiling, the touch move event that fires from the picker seems to be taking about 3x as long to execute between the two cases.

The weird thing is this problem doesn't exist if open my app directly in mobile safari.  Not sure exactly what's going on here, but it's definitely making my app completely unusable on iOS.

**Comment by pantonis** [comment]
Having the same issue with RC1 on Android 6 LG4 which is a high end phone. Very laggy

**Comment by scottgeye** [comment]
I was able to solve my issues by cutting down on the amount of processing going on during every angular change detection cycle.  I was watching several properties from one of my component templates that were doing way more work than they should of.  Some simple caching did the trick.

On the ionic side, if there's a way to cut down on the change detection during picker touch move events, that make might help mitigate the issue in the first place.

**Comment by manucorporat** [comment]
Improving the performance of picker and ion-datetime is in my roadmap, it will be addressed once all the critical known bugs (mostly navigation bugs) are fixed in ionic. We are close :)

**Comment by tobika** [comment]
I came by this performance problem aswell today and made an interesting discovery.

For me its only really slow when I add the year to the `pickerFormat`. Without it no slow down is encountered. Hope this helps.
