### ISSUE TITLE
Cannot create new page on 2.1.0-beta.1

### ISSUE THREAD

**Issue by athosbr99** [driftyco/ionic#8104]
#### What behavior are you expecting?

On 2.1.0-beta.1, when created a new page using `ionic g page <namepage>`, a ENOENT appears.

I uninstalled and installed the stable `ionic` package and this error doesn't occur. I uninstalled and installed `ionic@beta` again and it happened again. I created a new project and the issue persists.

```
Error: ENOENT: no such file or directory, scandir '/home/athos/Git/if55a/Lista3/agenda/node_modules/ionic-angular/templates/page'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at getTemplatesInDir (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23931:65)
    at Generator.renderAndWriteTemplates (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25309:116)
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25304:26


ENOENT: no such file or directory, scandir '/home/athos/Git/if55a/Lista3/agenda/node_modules/ionic-angular/templates/page' (CLI v2.1.0-beta.1)

```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0-beta.1
Ionic App Lib Version: 2.1.0-beta.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

**Comment by vijtad** [comment]
I am getting the same error in Windows 10.

**Comment by manucorporat** [comment]
Moved issue to ionic-cli: https://github.com/driftyco/ionic-cli/issues/1381
Please continue the conversation there!

Thanks
