### ISSUE TITLE
perf: Disable menu in children pages - Auto in config

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8105]
**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Right now to disable swipe to open menu in children pages i need to put function in evert root page:
IonPageWillLeave (or something like this) - this.menuCtrl.enable(false)

It should be like this
It should be config property in <ion-menu>

And, the default behavior in MD and iOS is to disable swipe to open menu in children pages</span>

<span is-issue-template></span>

**Comment by codeart1st** [comment]
Should be also relevant for platform:android

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#225
