### ISSUE TITLE
SqlStorage docs -- note Sqlite plugin dependency?

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic#8106]
The [SqlStorage doc](https://github.com/driftyco/ionic/blob/master/src/storage/sql.ts) currently does not mention its dependency on 
the [SQLite](http://ionicframework.com/docs/v2/native/sqlite/) plugin. If not added this can lead to errors on mobile: `SecurityError: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#779

**Comment by jgw96** [comment]
Hello, because this is a docs issue and not a framework issue I have moved this issue to the appropriate repo. Thanks for using Ionic!
