### ISSUE TITLE
Missing typescript for native plugin CallNumber

### ISSUE THREAD

**Issue by AntonKL** [driftyco/ionic#8108]
#### Short description of the problem:
Complier throws error due to what I believe is missing typescript files. I've looked in node_modules/ionic-native without finding any exports for CallNumber plugin.

#### What behavior are you expecting?
CallNumber plugin to load as documentations says it's a part of ionic-native.

**Steps to reproduce:**
1. Add plugin with $```ionic plugin add call-number```
2. Add ```import { CallNumber } from 'ionic-native';``` to any .ts file
3. Try to start the app i.e $```ionic serve```. Watch terminal for errors.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
```
TypeScript error: Error TS2305: Module "'/node_modules/ionic-native/dist/index"' has no exported member 'CallNumber'.
```

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0-beta.1
Ionic App Lib Version: 2.1.0-beta.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 7.3 Build version 7D175 
``` 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

**Comment by ramonornela** [comment]
Update ionic-native to 1.3.21 `npm install ionic-native@1.3.21 --save` call-number was added 1.3.19 and ionic2-app-base this in version 1.3.10

**Comment by manucorporat** [comment]
@ramonornela you are right! closing....
btw ionic-native issues should be reported here: https://github.com/driftyco/ionic-native/issues

Thanks!
