### ISSUE TITLE
Press gesture and scroll conflict 

### ISSUE THREAD

**Issue by TdyP** [driftyco/ionic#8109]
#### Description of the problem:
Inside a scrollable element, like a `ion-scroll` or a `ion-list` if you add a `(press)`, the scroll stop working. If you scroll with mouse wheel on a browser, the scroll is still working.
Looks like a conflict between press and scroll to intercept the gesture.

```
<ion-list>
<ion-item (press)="doSomething()"></ion-item>
......
</ion-list>
```

**Which Ionic Version?** 2.x

#### Plunker 

http://plnkr.co/edit/bQHBp4FaCJsuSnSJngHq?p=preview

**ionic info**

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.2.1

**Comment by danbucholtz** [comment]
Hi @TdyP,

This issue is resolved in the forth coming beta 12.  Any of the hammer events were blocking scrolling with the original set-up.  Please test out on beta 12 release and re-open if you continue to encounter the issue.

Thanks,
Dan
