### ISSUE TITLE
feat: (feat): Radio alert should start from the checked value

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8110]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In my video you can see that I made number picker for the age input, the current age is "34", which is in the middle of the alert block. For better UI I think the alert should start from the checked value (the current age, which is 34).

The video:
https://drive.google.com/file/d/0B_2AM8ZhXhE9SkZBNjJjYnBXOFE/view

The radio alert function:

```
openAgeSelect(): void {
    this.translateService.get(['intro.steps.age.ageSelectTitle', 'global.alerts.okButton', 'global.alerts.cancelButton']).subscribe((translatedTexts) => {
        let agesInputs = [];
        for(let i = 16; i <= 99; i++) {
            let inputChecked = false;
            if(this.user.age === i) {
                inputChecked = true;
            }
            agesInputs.push({
                type: 'radio',
                label: i.toString(),
                value: i,
                checked: inputChecked
            });
        }

        let ageSelectAlert = this.alertCtrl.create({
            title: translatedTexts['intro.steps.age.ageSelectTitle'],
            inputs: agesInputs,
            buttons: [
                {
                    text: translatedTexts['global.alerts.cancelButton']
                },
                {
                    text: translatedTexts['global.alerts.okButton'],
                    handler: age => {
                        this.user.age = age;
                    }
                }
            ]
        });
        ageSelectAlert.present();
    });
}
```

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#63
