### ISSUE TITLE
ionic resources doesn't  work properly with PSD

### ISSUE THREAD

**Issue by loursbourg** [driftyco/ionic#8111]
#### Short description of the problem:
When i run Ionic resources from the Command line, nothing happens

#### What behavior are you expecting?
ionic should generate the rousources.

**Steps to reproduce:**
1. Create a simple image in Photoshop
2. Add a new layer, apply a Layer mask
3. Run ionic resources.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0

**Using:**
Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.0.0

**Comment by ramonornela** [comment]
Close and move to ionic-cli

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1383

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this was an issue with the ionic-cli and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
