### ISSUE TITLE
FormData not work with ion-select by ionic2

### ISSUE THREAD

**Issue by anrip** [driftyco/ionic#8112]
the FormData only can get the [who]

```
<form #form>
<ion-select name="fale">...</ion-select>
<ion-input name="who" value="your"></ion-input>
<button (click)="submit(new FormData(form))"></botton>
</form>
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you be able to make a repo with a minimal example of this issue? Thanks!

**Comment by anrip** [comment]
···
import { Component } from '@angular/core';
import { ionicBootstrap } from 'ionic-angular';


@Component({
    template: `
        <ion-content>
            <form #formElem>
                <ion-item>
                    <ion-label>Sec:</ion-label>
                    <ion-select name="sec">
                        <ion-option value="1">1</ion-option>
                        <ion-option value="2" selected>2</ion-option>
                    </ion-select>
                </ion-item>
                <ion-item>
                    <ion-label>Who:</ion-label>
                    <ion-input name="who" value="hiling" text-right></ion-input>
                </ion-item>
                <ion-item>
                    <button (click)="submit1(formElem)">Sumbit-1</button>
                </ion-item>
            </form>
            <p padding [innerHTML]="result"></p>
        </ion-content>
    `
})
export class HomePage {
    result: string;
    constructor() {}
    submit1(form) {
        this.result = `
            Sec Value: ${form.sec && form.sec.value} <br/>
            Who Value: ${form.who && form.who.value}
        `;
        let data = new FormData(form);
    }
}


@Component({
    template: '<ion-nav [root]="root"></ion-nav>'
})
export class MyApp {
    public root: any;
    constructor() {
        this.root = HomePage;
    }
}

ionicBootstrap(MyApp);

···

**Comment by anrip** [comment]
ion-radio/ion-checkbox not work with FormData, too.

**Comment by mola10** [comment]
Any updates on this?
Need form data support for ion-checkbox\ion-radio

**Comment by anrip** [comment]
none 
 
------------------ 原始邮件 ------------------
发件人: "mola10"; 
发送时间: 2016年11月15日(星期二) 晚上10:19
收件人: "driftyco/ionic"; 
抄送: "若海"; "Author"; 
主题: Re: [driftyco/ionic] FormData not work with ion-select by ionic2(#8112)

 

Any updates on this?
 Need form data support for ion-checkbox\ion-radio

**Comment by mhartington** [comment]
Hey yall, is this still and issue? Seems to work fine.

http://plnkr.co/edit/glUaNu?p=preview

**Comment by brandyscarney** [comment]
I modified the above plunker to reproduce this, it seems it is only an issue when trying to access the name property on the form element. I added a Material Design select and it behaves the same as ours: http://plnkr.co/edit/BD6qypKWGcVzB08EIHMS?p=preview

**Comment by brandyscarney** [comment]
I spoke with the Angular team about this issue. They confirmed that the correct way to access the form values is through the `#form="ngForm"` reference. For example: `form.value.sec` is working fine in the plunker I referenced. According to them, Direct DOM access to the form controls is not the "Angular way". Thank you for the issue!
