### ISSUE TITLE
ion-refresher on-refresh uses promises

### ISSUE THREAD

**Issue by fasfsfgs** [driftyco/ionic#8113]
#### Short description of the problem:
If on-refresh function passed to ion-refresher returns a promise, it automatically completes the refresh when the promise is fulfilled. Is this a feature or a bug? I didn't find any docs of this behaviour.

#### What behaviour are you expecting?
I was expecting that only the broadcast event below could complete the refresh.
``` javascript
$scope.$broadcast('scroll.refreshComplete');
```

**Steps to reproduce:**
1. Pass a function that returns a promise to on-refresh from ion-refresher;
2. Trigger ion-refresher;
3. Wait until the promise is fulfilled;
4. The refresh animation stops as soon as the promise is fulfilled, even though no ```$scope.$broadcast('scroll.refreshComplete');``` was called.

**Example:**
``` html
...
  <ion-refresher
    on-refresh="doRefresh()">
  </ion-refresher>
...
```
``` javascript
...
$scope.doRefresh = function () {
  return $timeout(() => console.log('promise done!'), 5000);
};
...
```

**Which Ionic Version?** 1.3.1

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually how `ion-refresher` is supposed to work. Thanks!
