### ISSUE TITLE
VideoPlayer plugin missing from ionic-native modules

### ISSUE THREAD

**Issue by aljibbs** [driftyco/ionic#8119]
Cannot import VideoPlayer from the native library (ionic-native) even after downloading the plugin via the ionic 2 docs page. Error says there is no exported member. I have tried lots of solutions online but it just didn't work. I also realized that the plugin is not in the ionic-native modules folder. Is there a problem or is there a special way to get it to work ?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#563

**Comment by jgw96** [comment]
Hello, because this issue was related to Ionic Native and not the Ionic Framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
