### ISSUE TITLE
bug: On click input - the app scrolling top - iOS bug

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8123]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>On click input, the app scrolling top and closing keyword.
It happened to me only on iphone 6 plus (yet i tried only android phones) on Ionic View.

The html:
```
<ion-list>
	<ion-item>
		<ion-label stacked>Pounds</ion-label>
		<ion-input type="number" [(ngModel)]="post.ngModel" (click)="openWeightSelect(post)" class="picker" disabled *ngIf="!post.weight"></ion-input>
		<ion-input type="number" [(ngModel)]="post.weight" disabled *ngIf="post.weight"></ion-input>
	</ion-item>
</ion-list>
```

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Does this also happen when the app is installed to the device?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
