### ISSUE TITLE
The Market Plugin is missing

### ISSUE THREAD

**Issue by John-Luke** [driftyco/ionic#8124]
I would like to use this plugin, but haven't way to add this plugin in my project.
I tried using
`ionic plugin add xmartlabs-cordova-plugin-market`
But this plugin ins't in `ionic-native` module folder

![market](https://cloud.githubusercontent.com/assets/15695983/18636604/d5a9a34e-7e5f-11e6-880c-8e2453994839.png)

**Comment by NoNameProvided** [comment]
Looking at the source of the wrapper of the [Market  plugin](https://github.com/driftyco/ionic-native/blob/master/src/plugins/market.ts#L18) in the [ionic-native repo](https://github.com/driftyco/ionic-native/) you can find out that it uses the [cordova-plugin-market plugin](https://github.com/xmartlabs/cordova-plugin-market). Which you can install directly from it's repo as 

```bash
ionic plugin add https://github.com/xmartlabs/cordova-plugin-market --save
```

or you can install it from npm with the following name: 

```bash
ionic plugin add cordova-plugin-market --save
```

**Comment by kelvindart** [comment]
Also it is available on NPM: https://www.npmjs.com/package/cordova-plugin-market 🙂

**Comment by kelvindart** [comment]
Ignore my comment: I have just seen your last note sorry!

**Comment by danbucholtz** [comment]
I'll shoot @mhartington a message and ask him to update this. He has been making some great improvements to the Native docs recently.

Thanks,
Dan

**Comment by NoNameProvided** [comment]
The PR has been already merged. Do you generate the docs automatically?

**Comment by danbucholtz** [comment]
Yes. Looks like it hasn't been deployed to staging yet, though.

http://ionic-site-staging.herokuapp.com/docs/v2/native/market/

Thanks,
Dan

**Comment by ramonornela** [comment]
Problem docs publication in site current 1.3.10 related issue [Ionic SIte](https://github.com/driftyco/ionic-site/issues/771) lots issue are opened

**Comment by jgw96** [comment]
Hello all, the docs are now updated! Thanks for using Ionic!
