### ISSUE TITLE
Support for textarea in alert

### ISSUE THREAD

**Issue by SebastianGiro** [driftyco/ionic#8125]
#### Short description of the problem:

https://forum.ionicframework.com/t/multi-line-textarea-definition-ionic2-in-alert/46298

The Alert.create() doesn't support multine inputs ( textarea )
#### What behavior are you expecting?

Create an alert and add something like:

```
alert.addInput({
      type: 'textarea',
      name: 'about',
      placeholder: 'Optional message'
    });
```

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#64

**Comment by Eraldo** [comment]
> driftyco/ionic-feature-requests#64
This link seems to be dead.
What is the status on this issue?

**Comment by SebastianGiro** [comment]
I'll check, if I have time this week about this issue.
If it's not resolved, I will push a PR with the feature.

**Comment by esmiralha** [comment]
Any news on this feature request?

**Comment by Munnster83** [comment]
Any update?

**Comment by xdolnak** [comment]
I would also appreciate this feature.

**Comment by FelschR** [comment]
> This issue was moved to driftyco/ionic-feature-requests#64

Unfortunately, the `ionic-feature-requests` repo doesn't exist anymore.
Is this still tracked anywhere?

**Comment by 20cents** [comment]
+1

**Comment by faramos** [comment]
+1

**Comment by Shrakka** [comment]
+1

**Comment by SebastianGiro** [comment]
@jgw96 Can we reopen this issue? `ionic-feature-requests` don't exist anymore.
I can do a pull request by the end of this week

**Comment by jurajgromosrc** [comment]
+1

**Comment by Sampath-Lokuge** [comment]
Have you done the PR? @SebastianGiro

**Comment by SebastianGiro** [comment]
@Sampath-Lokuge Nope, I should create a new Issue because this is going nowhere.
But I just wanted to do it here. Also I need to recheck my code, because my fix is really old and I don't want to screw the component.

**Comment by salifukayta** [comment]
+1

**Comment by dudanogueira** [comment]
+1

**Comment by Avasse** [comment]
+1

**Comment by eladcandroid** [comment]
Please reopen this issue...

**Comment by seiyria** [comment]
They moved it to their internal tracker.

**Comment by salmachhoud** [comment]
+1

**Comment by fareshan** [comment]
+1

**Comment by tomferreira** [comment]
+1

**Comment by AgusFran** [comment]
+1

**Comment by NTruchaud** [comment]
+1

**Comment by shazadmaved** [comment]
+1 :)

**Comment by sametacar** [comment]
+1 :)

**Comment by Taylorsuk** [comment]
+1

**Comment by jayseb11** [comment]
+1

**Comment by MarwaAbuEssa** [comment]
+1

**Comment by hsouna** [comment]
+1

**Comment by smxdevst** [comment]
+1

**Comment by Taylorsuk** [comment]
For now we've had to use a modal styled like a Dialog and then use the `onDidDismiss()` callback to return the data. 
<img width="452" alt="screen shot 2018-06-12 at 22 18 37" src="https://user-images.githubusercontent.com/852767/41317977-b4442bcc-6e8e-11e8-93b4-c30f52167b8b.png">

**Comment by jgw96** [comment]
Hello all! Because this is not something that is on our roadmap, there are workarounds for it (such as using a modal or some other alternative UI) and because this issue has been closed I am going to lock this issue. Thanks for using Ionic!
