### ISSUE TITLE
docs: (progressive/web) Instructions/example on producing static bundles for different styles

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#8127]
#### Short description of the problem:
Developers should be able to serve the same app over HTTP(S) in different styling to different clients (iOS, Android, Win, Web). At the moment it's not clear what is the recommended way. Should it be separate files like:
- index.android.html
- index.ios.html

or should we dynamically add CSS class to body `<body class="{{ platform }}">` or should we have separate subfolders for each platform like
- /ionicapp/_common
- /ionicapp/android
- /ionicapp/ios

This includes question on:
- How do we build & deploy platform specific resources like CSS & images (_not sure if also includes JS & anything else_)?

Ideally there should be a simple way to change styling the same way as it's done components docs: http://ionicframework.com/docs/v2/components/#action-sheets 

May be even within the app?

#### What behavior are you expecting?

We expect to have a dedicated docs section regards this and support for multi-platform styling in progressive/web apps out of the box by Ionic CLI. Ideally there should be a sample in a git repository (_supported by [Ionic conference app](https://github.com/driftyco/ionic-conference-app)?_)

**Which Ionic Version?**
2.x

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! With the latest release of Ionic 2 (rc.0) we have switched to shipping static css instead of dynamically added css.

**Comment by astec** [comment]
@jgw96 that's cool but really does not answer my question. I still have no idea how to switch style of app when serving it to web client (for example locally by running `ionic serve`).

Any chance you can reopen the issue?

**Comment by jgw96** [comment]
Sorry! You can switch the device type in chrome device emulation to an iphone for the iOS design, android phone for the MD design and a windows device for the windows design. You can also set the mode in the config object of `IonicModule.forRoot()`. Here is a quick example: 

```
IonicModule.forRoot(IonicApp, {mode: 'md'});
```
Thanks!
