### ISSUE TITLE
Origin header set to file://

### ISSUE THREAD

**Issue by johnymachine** [driftyco/ionic#8129]
Hi,

having problem with header, which is being set to file:// on android native app. That causes my requests to fail...

**Please follow here:** http://stackoverflow.com/questions/39324750/ionic-native-app-is-sending-header-originfile-which-causes-problems

Maybe related to issue #6851 

Thanks.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I cannot seem to reproduce this with my Ionic 1 test app calling three different api's. Could you post a minimal repo that I can use to reproduce this issue? Thanks for using Ionic!

**Comment by johnymachine** [comment]
I simply add this code:

```javasrcipt
.controller('DashCtrl', function($scope, $http) {
  $http.post('https://www.google.com')
})
```
![image](https://cloud.githubusercontent.com/assets/2737699/18699531/51c2ade0-7fd2-11e6-8435-f013822e3623.png)

Complete project here: https://github.com/johnymachine/issue-test

**Comment by jgw96** [comment]
@johnymachine the above issue you are seeing is due to that url (google.com) not allowing post requests. Would you mind trying making a `GET` request to this url `http://jsonplaceholder.typicode.com/posts`. Thanks!

**Comment by johnymachine** [comment]
Not relevant, as I stated before, my issue is not with failing `POST ` request to `google.com`. The real problem is with header `origin: file://` (no matter where the request goes) being inserted. Please read carefully my stackoverflow [post](http://stackoverflow.com/questions/39324750/ionic-native-app-is-sending-header-originfile-which-causes-problems).

![image](https://cloud.githubusercontent.com/assets/2737699/18722337/c2b9c922-8034-11e6-8c6c-7a360898b8ad.png)

**Comment by jgw96** [comment]
Hello @johnymachine , this is expected as the origin is from an html file on the device's disk. If this is failing for you it is most likely a server side issue. Could you try making a request to the above test api I posted? This will give good technical proof of whether or not this is an Ionic issue or server side issue. Thanks!

**Comment by johnymachine** [comment]
Here, but really not the issue...
![image](https://cloud.githubusercontent.com/assets/2737699/18824958/320b569e-83c6-11e6-964c-a2c933793fd7.png)

I believe most of the servers dont accept file:// origin. What would be the added security value using CORS? Besides when running only in cordova, everything works fine...

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#92

**Comment by mburger81** [comment]
@johnymachine was you able to resolve this issue? We have the same problem on ionic3. And I'm in your opinion most of the server don't support Origin file://

**Comment by johnymachine** [comment]
No, i dropped Ionic. No server will or should accept it, I think is even against some RFCs...

**Comment by mburger81** [comment]
Yes I know, and which framework are you using now?

**Comment by johnymachine** [comment]
I was just experimenting, so nothing for now...

**Comment by trajano** [comment]
For me I implemented two solutions.

1. detect that the `Origin` header is `file://` and convert it to `file:///` which is accepted by `java.net.URI` in the application https://github.com/trajano/app-ms/commit/4c242ec2a6754157a3c73a5f3355d9cb53b812c0

2. detect that the `Origin` header is missing and put a dummy origin in the nginx proxy before it passes it in.

I am going to drop and let the nginx proxy handle that instead https://github.com/trajano/app-ms/issues/56 eventually.

**Comment by victorhugorch** [comment]
This is still a issue.

**Comment by CedricReichenbach** [comment]
Latest discussion on the same topic:

- https://github.com/ionic-team/ionic/issues/12607

**Comment by dwieeb** [comment]
Consolidating to https://github.com/ionic-team/ionic/issues/15057 (please see [my comment](https://github.com/ionic-team/ionic/issues/15057#issuecomment-410841420)).
