### ISSUE TITLE
bug: When using Crosswalk, ionic build breaks

### ISSUE THREAD

**Issue by ParsaAkbari** [driftyco/ionic#8131]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>When using crosswalk, apks are built not as android-debug.apk and android-debug-unaligned.apk but as the following: android-armv7-....apk and android-x86-....apk

But when using the ionic build android CLI command the CLI still installs the old android-debug.apk file.

Therefore after installing crosswalk the user gets confused, because when running ionic build, the old apk keeps getting installed onto the app while the newly updated x86 and armv7 apks are not installed.</span>

<span is-issue-template></span>

**Comment by izee** [comment]
remove and re-add the platform

**Comment by aksharpatel47** [comment]
I had this problem. The way I solved this was, after I added crosswalk I removed all the generated apks from the platforms/android/build/outputs/apk folder. Once I did that, the correct generated build is getting installed. I hope this helps you out.

I don't know if this is a bug in Ionic. I think Ionic cli team will be able to comment on this.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1390

**Comment by jgw96** [comment]
Hello all, because this issue was related to the Ionic CLI and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
