### ISSUE TITLE
sidemenu -v2 swipe to open enabled

### ISSUE THREAD

**Issue by Vaccuss** [driftyco/ionic#8135]
## sidemenu -v2 
the current state of the default pull and install does not work.
``` 
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
``` 

I have checked docs but all of them say this should be the fix.
I have tried to mess with it a bit to fix but I have not been able to get it to disable the swipe to open. 

## to reproduce
On a windows machine (dont have mac or linux) ionic start "name" sidemenu -v2
done this twice with the same behavior

Thanks guys.

**Comment by rcjsuen** [comment]
@Vaccuss I don't seem to have this problem. I get the menu if I swipe. I do not get the previous page in the navigation stack. If I set `swipeBackEnabled="true"` then I do get the previous page when I swipe.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
