### ISSUE TITLE
how to solving this issue plz tell me

### ISSUE THREAD

**Issue by jyoti507caroldata** [driftyco/ionic#8136]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\hp\AppData\Roaming\npm\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink

npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\hp\AppData\Roaming\npm\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\hp\AppData\Roaming\npm\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\.staging' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\npm-debug.log

**Comment by kelvindart** [comment]
Are you running cmd as Administrator? If not, you probably should be. Right-click cmd > Run as administrator:

![run as admin dialog](http://s10.postimg.org/hmmbrkgbt/runasadmin.png)

**Comment by jyoti507caroldata** [comment]
i try this bt same problem create


npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\hp\AppData\Roaming\npm\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink

npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\hp\AppData\Roaming\npm\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\hp\AppData\Roaming\npm\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\.staging' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by brandyscarney** [comment]
Can you try uninstalling ionic and reinstalling it?

```
npm uninstall -g ionic
npm install -g ionic
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1391

**Comment by jgw96** [comment]
Hello all! Because this was an issue with the Ionic CLI and not the Ionic framework I have move this issue to the cli repo. Thanks for using Ionic!
