### ISSUE TITLE
bug: angular-openlayers marker window click not working

### ISSUE THREAD

**Issue by orion390** [driftyco/ionic#8138]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>I created a simple angular-openlayers map in an ionic app, i put markers that, when clicked, a window appears with a link that opens another page; the issue is that links inside the marker window do not work. I checked deeply into this and realized that any click event (or touch) made inside the marker info window is listened. Here is an example in codepen: http://codepen.io/Orion390/pen/rrrQxm</span>

Update: this one actually works http://codepen.io/Orion390/pen/RGGZOE , joust add a marker on the ng-init, does not solve the problem, markers added still don't get the click event, but may show an issue with the marker windows rendering behind something that does not let them get the click event (?)
<span is-issue-template></span>

**Comment by orion390** [comment]
Nix found a workaround here: http://stackoverflow.com/questions/39541164/link-in-angular-openlayers-directive-marker-message-not-working/
Still seems like a compatibility bug between angular-openlayers-directive and ionic, as in angular-googlemaps works perfect.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! After reviewing this it seems like more of an issue with the angular-openlayers library and not an issue with Ionic. Because of this I am going to close this issue for now. Thanks for using Ionic!
