### ISSUE TITLE
Cannot find module '@ionic/cloud-angular'

### ISSUE THREAD

**Issue by faraazc** [driftyco/ionic#8139]
i am trying to use authentication services in ionic cloud. trying to implement the solution as described in the below link.
http://docs.ionic.io/services/auth/#providers

i am seeing this error Cannot find module '@ionic/cloud-angular'

ionic version
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Not installed

**Comment by faraazc** [comment]
resolved this issue by installing 
npm install --save @ionic/cloud-angular

**Comment by davincif** [comment]
Same problem here =/
And "npm install --save" gave me the following .log file.

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData com.pylonproducts.wifiwizard@../vendor/WifiWizard
20 silly cache add args [ 'com.pylonproducts.wifiwizard@../vendor/WifiWizard', null ]
21 verbose cache add spec com.pylonproducts.wifiwizard@../vendor/WifiWizard
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'com.pylonproducts.wifiwizard@../vendor/WifiWizard',
22 silly cache add   scope: null,
22 silly cache add   escapedName: 'com.pylonproducts.wifiwizard',
22 silly cache add   name: 'com.pylonproducts.wifiwizard',
22 silly cache add   rawSpec: '../vendor/WifiWizard',
22 silly cache add   spec: '/home/davincif/Documents/projects/vendor/WifiWizard',
22 silly cache add   type: 'local' }
23 error addLocal Could not install /home/davincif/Documents/projects/vendor/WifiWizard
24 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/home/davincif/Documents/projects/vendor/WifiWizard'
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData  error for com.pylonproducts.wifiwizard@../vendor/WifiWizard { Error: ENOENT: no such file or directory, open '/home/davincif/Documents/projects/vendor/WifiWizard'
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData   errno: -2,
24 silly fetchPackageMetaData   code: 'ENOENT',
24 silly fetchPackageMetaData   syscall: 'open',
24 silly fetchPackageMetaData   path: '/home/davincif/Documents/projects/vendor/WifiWizard' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack Error: ENOENT: no such file or directory, open '/home/davincif/Documents/projects/vendor/WifiWizard'
29 verbose stack     at Error (native)
30 verbose cwd /home/davincif/Documents/projects/sams-club-scan-and-go-br
31 error Linux 4.10.0-26-generic
32 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
33 error node v6.11.0
34 error npm  v3.10.10
35 error path /home/davincif/Documents/projects/vendor/WifiWizard
36 error code ENOENT
37 error errno -2
38 error syscall open
39 error enoent ENOENT: no such file or directory, open '/home/davincif/Documents/projects/vendor/WifiWizard'
40 error enoent ENOENT: no such file or directory, open '/home/davincif/Documents/projects/vendor/WifiWizard'
40 error enoent This is most likely not a problem with npm itself
40 error enoent and is related to npm not being able to find a file.
41 verbose exit [ -2, true ]

**Comment by davincif** [comment]
Oh, got it ^^"
For those who are in 2017, now its
npm install @ionic/cloud-angular --save
=)

**Comment by abrahamduran** [comment]
Think the documentation should be updated to reflect the change
https://docs.ionic.io/services/auth/

**Comment by cardosogneto** [comment]
I tried this comand:
 

> npm install '@'ionic/cloud-angular --save

but not worked
