### ISSUE TITLE
Scrolling Through List Causes "active" Class on List Items

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic#814]
When scrolling through a list in 0.9.27, the list items that were first touched get the "active" class applied.

Forum # 1891 : http://forum.ionicframework.com/t/list-items-now-clickable/1891/5

0.9.26 sample that does not have this problem : http://codepen.io/calendee/pen/tpfgi
0.9.27 sample that demonstrates problem : http://codepen.io/calendee/pen/tpfgi

**Comment by v-bc-vivek** [comment]
I am still facing this issue I am using latest build(v1.1.0 "xenon-xerus")  I need it like native app(whatsapp,gmail) effect only come when we tap on that item or touch take a example of the inbox and once i tap for full view then only it needs to come but it's coming for scroll also. 
Note:I am not talking about event but I am talking about effect.

**Comment by igor-rif-shevchenko** [comment]
Same problem...

**Comment by gordol** [comment]
Wow, this still hasn't been fixed? We had to ditch Ionics JS code, and we only use the CSS with our own JS events. It's just too buggy....
