### ISSUE TITLE
Angular 2.0 Support

### ISSUE THREAD

**Issue by denkomanceski** [driftyco/ionic#8147]
When is it planned to get angular 2.0 support with ngmodules? The biggest problem is using third party libraries which already support this (like ngtranslate..)

Regards

**Comment by apparition47** [comment]
The upcoming `beta.12` will include it and it will be here "soon" according to the team's comments I've seen in the issues.

**Comment by jgw96** [comment]
Hello all! Beta.12 is running on Angular 2.0 final and i can now say that it will be here not just "soon" but extremely soon 😉 . Thanks for using Ionic!

**Comment by maxtuzz** [comment]
Wooo! Great news !

**Comment by modularcoder** [comment]
Awesome! Can't wait for this!
