### ISSUE TITLE
[Enhancement] Sliding list options - collapse/expand animation

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8148]
Right now the `ion-item-options` in sliding list are just sitting behind the list. If we see other apps such as mail or whatsapp app, sliding options have nice collapse/expand animation. It will be great if you can consider implementing this animation in some future release.

![giphy](https://cloud.githubusercontent.com/assets/8744282/18692825/db92a06a-7f51-11e6-88df-27b2ee31589b.gif)

**Comment by Bouzmine** [comment]
@aggarwalankush I think this should be an option because most of the *sliding items* in iOS are under the item as opposed to having this nice animation. I think this animation is most effective when there's multiple items and the last is `expandable`.

**Comment by aggarwalankush** [comment]
@Bouzmine Different apps in iOS have different animations for sliding options. I think it would be great if Ionic provides some options to customize sliding options.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#65

**Comment by aggarwalankush** [comment]
@jgw96 Any plans to make feature request repo public so that we don't open duplicate feature requests.

**Comment by jgw96** [comment]
@aggarwalankush not at this time, but thats not a bad idea! Ill talk to the team and keep you updated.
