### ISSUE TITLE
"npm install firebase angularfire2 --save" throwing exception Ionic 2 version > beta.11

### ISSUE THREAD

**Issue by appplumbr** [driftyco/ionic#8152]
Ionic 2 Version : beta11

#### Short description of the problem:
I am using Firebase with Ionic 2, When I execute ionic serve --lab get errors in console

#### What behavior are you expecting?
App should load/run with serve --lab command

**Steps to reproduce:**
Within your ionic project directory > type > npm install firebase angularfire2 --save

**Error/ Exceptions:**
npm WARN peerDependencies The peer dependency @angular/common@^2.0.0 included from angularfire2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angularfire2" "firebase" "--save"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.11 wants @angular/common@2.0.0-rc.4
npm ERR! peerinvalid Peer angularfire2@2.0.0-beta.5 wants @angular/common@^2.0.0

**Comment by appplumbr** [comment]
Feedback I got from Angular2 repo moderators > "As it states, ionic@beta is using angular2-rc4 and angularfire2 is using released version of angular2. That's why this issue belongs to ionic2's GitHub page, not here."

**Comment by appplumbr** [comment]
fyr - https://github.com/angular/angularfire2/issues/536

**Comment by ramonornela** [comment]
Closes issue @appplumbr beta.12 fix issue, @jgw96 explain best ;)

**Comment by appplumbr** [comment]
Thanks!

**Comment by appplumbr** [comment]
Team - Waiting beta.12 release hope this will be fixed asap, still facing the error and blocked in development

**Comment by jgw96** [comment]
Hello all, thanks for opening an issue with us! Ionic 2 beta.12 is running Angular 2 final and should be out to the public by the end of the week. This will solve the above issue. Thanks for using Ionic!

**Comment by appplumbr** [comment]
@jgw96 - Thanks for the insight
