### ISSUE TITLE
Form elements do not match material design guidelines

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#8156]
#### Short description of the problem:

The last form element has a wider bottom border than the previous ones. Also the borders touching the right side of the screen.

![image](https://cloud.githubusercontent.com/assets/644550/18705961/5a333ab2-7ff0-11e6-8f79-be0c1616730b.png)
#### What behaviour are you expecting?

It is not clear if this was by design for Ionic to stand out. But according to the Material Design guidelines at https://material.google.com/components/text-fields.html#text-fields-full-width-text-field it shows all bottom borders are of the same width.

![image](https://cloud.githubusercontent.com/assets/644550/18705948/503d1906-7ff0-11e6-8206-6f84faa34b9e.png)

**Which Ionic Version?** 2.x

**Comment by rcjsuen** [comment]
I see this too when using an ion-list. It drives me mad... :(

**Comment by basvdijk** [comment]
I also see a top border but I am not sure if this was caused by Ionic

**Comment by comfortme** [comment]
also while holding a button in an android device highlight slowly captures(ripple effect) the button until fully highlighted. like in this gif. this also does not match with ionic
![ripple_effect](https://cloud.githubusercontent.com/assets/18467824/18723965/66add006-8043-11e6-9be9-0045304871bd.gif)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#171
