### ISSUE TITLE
docs: Page "Using Alternate Browsers" outdated

### ISSUE THREAD

**Issue by bastiss** [driftyco/ionic#8157]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The content on page "Using Alternate Browsers" is outdated.

http://ionicframework.com/docs/cli/browsers.html</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#782

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because this issue is a docs related issue and not a framework issue I have moved this issue to the appropriate repo. Thanks for using Ionic!
