### ISSUE TITLE
bug: which method should use to open multiple popups

### ISSUE THREAD

**Issue by anilkumarsoni** [driftyco/ionic#8158]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>which way should be use to open multiple popups in app so not freeze the app , or how to clear popup after close.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
