### ISSUE TITLE
Problem with multiple ion-datetime

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#8159]
ionic 2

Plunker link
http://plnkr.co/edit/5AlBBp6hrrli1lMI9Yn1?p=preview

if you check the above link, when you try to change the first DateTime the second one also gets changed.

`Times = ["11:00", "11:00", "11:00", "11:00"];`

```
<ion-list>
    <ion-item *ngFor="let Time of Times; let i=index">

      <!-- label displays correct value -->
      <ion-label>Actual value {{ Times[i] }}</ion-label>

      <!-- ion-datetime displays wrong value -->
      <ion-datetime [(ngModel)]="Times[i]" displayFormat="h:mm A"></ion-datetime>

    </ion-item>
  </ion-list>
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by dheran** [comment]
I've created, https://forum.ionicframework.com/t/problem-with-multiple-ion-datetime/64279
