### ISSUE TITLE
Ionic Build is stuck with Xcode 8.0

### ISSUE THREAD

**Issue by chack** [driftyco/ionic#8161]
#### Short description of the problem:

With Xcode 8.0 I can't use ionic build command for iOS. I already removed and readded hooks and iOS platform. The command is stuck after the printed console log below:

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Build settings from command line:

    CONFIGURATION_BUILD_DIR = /Users/Jan/Documents/Wohntraum360/wohntraumapp/platforms/ios/build/emulator

    SDKROOT = iphonesimulator10.0
    SHARED_PRECOMPS_DIR = /Users/Jan/Documents/Wohntraum360/wohntraumapp/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/Jan/Documents/Wohntraum360/wohntraumapp/platforms/ios/cordova/build-debug.xcconfig':

    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES

    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1

    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

    TARGETED_DEVICE_FAMILY = 1,2
 

**Which Ionic Version?** 1.x or 2.x

2.0 Beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1401

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the cli and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
