### ISSUE TITLE
ionic conference app got blank screen in iOS 10

### ISSUE THREAD

**Issue by frankpolkm** [driftyco/ionic#8163]
Hi, the ionic conference app doesn't work in iOS 10, blank after splash screen. 9.3 is OK.

**Comment by rcjsuen** [comment]
Looks okay to me on my iOS 10.0.1 on my iPhone 6. How are you opening the application? I'm using Ionic View.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-conference-app#251

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As this issue is related to the conference app and not the framework I have moved this issue to the appropriate repo.

**Comment by finalxcode** [comment]
+1
