### ISSUE TITLE
ionic html5 video tag

### ISSUE THREAD

**Issue by meiyalei** [driftyco/ionic#8169]
hi, i have a problem with using html5 video tag.
The code is vey simple, like this:

```
<p>
  <video width="100%" controls src="http://192.168.1.130:8080/fast4j/ueditor/jsp/upload/video/20160922/1474535781986094632.mp4" type="video/mp4"></video>
</p>
```

When i use command with 'ionic serve', it's running ok.
But i installed apk to android device, it doesn't work. After a few minutes, it's progressing, but has no video & no voice.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! What version of Android is your device running?

**Comment by meiyalei** [comment]
Hi, My device's android version is 6.0.

**Comment by meiyalei** [comment]
I try my best, now, running on the android device is ok.
But it doesn't running on the ios device.

**Comment by meiyalei** [comment]
enviroment as shown:
1. iphone 6s plus
2. ios 9.3.5
it can not be played.

**Comment by ramonornela** [comment]
@meiyalei No problem in Ionic and yes Platform IOS see https://forum.ionicframework.com/t/ios-background-audio-works-on-emulator-not-on-device/12948/2 or add plugin [cordova-plugin-backgroundaudio](https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio)

**Comment by jgw96** [comment]
@meiyalei would you mind trying our fork of the [WKWebView plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions) and seeing if that fixes the issue for you? Thanks!

**Comment by meiyalei** [comment]
sorry,i have tried it. But it doesn't be played. 
In the video source there is a play button,  is a triangle with a slash.

**Comment by meiyalei** [comment]
The html5 video label like this:

<ion-view>
  <ion-content>
    <video width="100%" poster="http://localhost:8080/color.jgp" src="http://localhost:8080/color.mp4 controls webkit-playsinline"></video>
  </ion-content>
</ion-view>

mp4: 
  video codec  -> h.264 avc
  audio codec  -> aac

it's my code and video source configuration. Have something wrong with it ?

**Comment by jgw96** [comment]
Hello, I am very sorry for the delay on this! After reviewing this issue again it seems like the issue is because your loading the video from an unsecure `http` url. iOS only allows requests to `https` url's. I would recommend making sure that you access assets only from `https` url's. Thanks for using Ionic!

**Comment by enestdharam** [comment]
Can any one helped me? really I need to fix issue. video is not showing in ionic 3 while it is working in  simulter and also same code working with ionic 2. Please see below my following code:-
HTML code:
<video preload="auto" autoplay loop class="video bg-vid" playsinline>
							<source src="assets/vid/1-shutterstock_v4503179.mp4" type='video/mp4'>
			</video>
config.xml:
 <preference name="AllowInlineMediaPlayback" value="true" />
scss:
.bg-vid {
		position: absolute;
		top: 50%;
		left: 50%;
		min-width: 100%;
		min-height: 100%;
		width: auto;
		height: 100%;
		z-index: -100;
		-webkit-transform: translateX(-50%) translateY(-50%);
		-moz-transform: translateX(-50%) translateY(-50%);
		-ms-transform: translateX(-50%) translateY(-50%);
		-o-transform: translateX(-50%) translateY(-50%);
		transform: translateX(-50%) translateY(-50%);
		background-size: cover;
	}
Thanks in adavanced
