### ISSUE TITLE
ionic info command should show Angular Version as well

### ISSUE THREAD

**Issue by codestellar** [driftyco/ionic#8170]
When I run ionic info command, it gives me a good information:

Cordova CLI: 6.3.1                                                                                                                                                                             
Gulp version:  CLI version 3.9.1                                                                                                                                                               
Gulp local:   Local version 3.9.1                                                                                                                                                              
Ionic Framework Version: 2.0.0-beta.11                                                                                                                                                         
Ionic CLI Version: 2.1.0-beta.2                                                                                                                                                                
Ionic App Lib Version: 2.1.0-beta.1                                                                                                                                                            
OS:                                                                                                                                                                                            
Node Version: v4.5.0

Expected: This should also show the angular2 version being used.

**Comment by herbzi** [comment]
+1
I also know that many issues would have been solved faster if this was included. 
Probably an issue for ionic-cli though.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1400

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As this is more of a cli feature request and not a framework feature request I have moved this issue to the appropriate repo. Thanks for using Ionic!
