### ISSUE TITLE
Feature request: has-header on <ion-content> in ionic 2

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic#8172]
Need a way to fix ion-content height when using <ion-header> in a separate component. More info -> https://forum.ionicframework.com/t/content-overlap-ion-header/60341

**Which Ionic Version?**  2.0 b11

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As Jason pointed out in that forum your `app.html` should only have `ion-nav` in it as that is the "root" component. He also correctly points out that you should be using an `ion-header` in each component and not trying to wrap it inside another component. Thanks for using Ionic!

**Comment by marcoturi** [comment]
Adding same info and example.
Example: Enterprise app. More than 60 pages. For example 30 with menu-icon visible, 30 with home-icon, this on the left of the title. On the right i can have a mix of settings (share content, delete content,  help button for displaying a modal, ecc.). It's not good to repeat every time ion-header for every combination. 

Example of how could be useful to have a single component for managing the header-nav (with ionic 1 syntax)

```
<my-header-nav title="MyContent" has-menu="true" show-help-button="true"></my-header-nav>
<my-header-nav has-menu="true"></my-header-nav> // notice there is no title -> will fallback on a Logo
<my-header-nav title="Share" has-home-button="true" share="{{dataToShare}}"></my-header-nav>
```

**Comment by jgw96** [comment]
Hello @marcoturi thanks for the info! Ionic 2 is not built to handle 60 seperate pages. You should instead be creating a  few pages and then async loading different data into them. A good example of this are apps like twitter, facebook, youtube etc. These apps only have a few different views and just load different data into each view. The main issue with having so many pages in your app are going to be performance, it will lock up the main browser thread for an inordinate amount of time as all the css, js and html gets parsed, compiled and executed.

**Comment by tokland** [comment]
@jgw96 I get your point, but it's really painful to repeat the header everywhere. Isn't this solution acceptable? https://stackoverflow.com/a/42166278/188031
