### ISSUE TITLE
Ionic native Email Composer not working in Android 5 & 6 

### ISSUE THREAD

**Issue by PabloFNK** [driftyco/ionic#8174]
The Cordova plugin used by Ionic Native as Email Composer is not working. We have tested it using Android 5 and Android 6 and none of them worked.

The plugin hasn't been updated since 2 years ago so it is not going to be fixed.

We have finally moved to use directly another cordova plugin ([https://github.com/hypery2k/cordova-email-plugin], which is a fork but currently supported) and it's working.

Could the Ionic Native Email Composer be updated to use this one?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#568

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an Ionic Native issue and not the Ionic framework I have moved this issue to the appropriate repo.
