### ISSUE TITLE
bug: Ion-Refresh function doesnot gets called

### ISSUE THREAD

**Issue by rahul202** [driftyco/ionic#8176]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>browser</span>

<span ionic-description>Ion-Refresh function doesnot gets called if bounce is set to false.

<ion-content id={{currentRoomId}} has-bouncing="false" >

```
    <ion-refresher icon="circle"
pulling-text="Pull to refresh..."
on-refresh="loadMore()">
```

  </ion-refresher>

Above code wont make call to loadMore, but if change has-bouncing to true.. it works...</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#90
