### ISSUE TITLE
Entire view slides up when input field is in focus on ios 7.1

### ISSUE THREAD

**Issue by alberthsu5** [driftyco/ionic#818]
On ios 7.1, when an input field is in focus, the entire view (including the header) is sliding up. The proper behavior should be that the header doesn't slide up and remains fixed to the top. This bug isn't happen on ios 7.0. Please see the two attached screenshots. 

I'm using ionic 0.9.27. 
![screenshot 2014-03-17 16 14 55](https://f.cloud.github.com/assets/2001713/2442919/7aedc618-ae2a-11e3-8008-e70df42bb4cd.png)
![screenshot 2014-03-17 16 14 16](https://f.cloud.github.com/assets/2001713/2442920/7d228e5a-ae2a-11e3-902c-2a8c52821309.png)

**Comment by gabriellecozart** [comment]
I'm having these issues currently with ionic 3.5 and ios10. Nothing I do seems to fix it.

**Comment by prashant1706** [comment]
Do we have fix for this issue ?
