### ISSUE TITLE
bug:back button not show sometimes in official docs(1.3.1)

### ISSUE THREAD

**Issue by Sunzhuokai** [driftyco/ionic#8180]
back button not show sometimes in this page http://ionicframework.com/docs/api/directive/ionNavView/

click follow this steps 
 1. About tab→Tabs NavStack(back button show)→Click back button
 2.  swipe to Home tab→Scientific Facts→swipe to About tab→Tabs NavStack(back button not show)

can fix this?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#787

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with the docs and not the framework i have moved this issue to the appropriate repo.

**Comment by Sunzhuokai** [comment]
that was caused by framework

**Comment by loopezz** [comment]
It's the same problem as described in this issue:
https://github.com/driftyco/ionic/issues/6875
