### ISSUE TITLE
ionic2, angularfire2 and firebase working combination?

### ISSUE THREAD

**Issue by Opelor** [driftyco/ionic#8182]
Hi team,

Does somebody knows if there is a working ionic2, angularfire2 and firebase version combination?

I'm using:
ionic 2.1.0-beta.2
firebase@3.4.0
angularfire2@2.0.0-beta.5

I'm having these unmet peer dependencies:
![screen shot 2016-09-22 at 11 18 31 pm](https://cloud.githubusercontent.com/assets/3394156/18774914/f5a9bf04-811a-11e6-82bf-2924623bb33e.png)

Thanks!!

**Comment by dmastag** [comment]
You could either wait for Ionic 2 Beta 12 which already using Angular 2 release and Typescript 2 which should be out in a couple of days.

Or you could use angularfire2 beta2 which is still using angular2 RC4.

**Comment by jgw96** [comment]
Hello @Opelor , thanks for opening an issue with us! This will be fixed once beta.12 is out (extremely soon (; ) as it is running on Angular 2 final!
