### ISSUE TITLE
How use custom page transitions? 

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic#8186]
#### Short description of the problem:

We need custom page transitions for our application. The same as now are used for modals. (sliding up from bottom when opening, sliding down when closed) I have digged into the page transitions part of the framework, but I was not able to make a working custom page transition.

I see there was some rewrite of transitions recently. Can one of you provide some information about how can I create custom page transformations? 

**Edit:** I am able to add page transitions with copy pasting a generated page transition file from `ionic-angular/transitions/transition-xy.js`. Renaming it, editing it then registering it in `ionic-angular/index.js` like this does the trick: 

```
require('./transitions/transition-ios');
require('./transitions/transition-md');
require('./transitions/transition-wp');
require('./transitions/transition-custom');
```

But playing around with generated files in node modules folder is not a good idea. In `index.js` I see that page transition related classes are not exported with `__export`. Is there a particular reason for that? 

#### What behavior are you expecting?

I can add custom page transitions as it was developed to be extendable.

**Other information:** N/A

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue: N/A

**Run `ionic info` from terminal/cmd prompt:** 

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a 
```

**Comment by ramonornela** [comment]
Added feature in https://github.com/driftyco/ionic/commit/7c05d0c0ba7cff42e358d9648b1a7eb255d7aa37 beta.12 close issue.

**Comment by aentan** [comment]
@NoNameProvided Works great except the pushed page doesn't show the back button. Help!

**Comment by NoNameProvided** [comment]
It should work, are you sure that you have pages on the stack? E.g if you push with setroot then you won't have any back button.

**Comment by aentan** [comment]
I'm just adding the animation option to my navpush. The back button was showing before.

Anyway I inspected the DOM. Back button's there. Just hidden. I looked at ionic's transtions, it seems the showing of back button is handled within the transition. Each platform animations the back button differently as part of the push animation.

**Comment by janein** [comment]
hi!
I just stumbled upon your topic and this is exactly what I wanted to do.
But as I've implemented it, I get some errors in the transition.

On this line:
`const enteringContent = new Animation(enteringView.pageRef());`

I get these errors:
```
Argument of type 'ElementRef' is not assignable to parameter of type 'Platform'.
Property '_win' is missing in type 'ElementRef'.
```

Do you by any chance have a version which works with RC4?

thanks for your effort!
janein

**Comment by NoNameProvided** [comment]
Hey @janein, I haven't updated that project to the latest ionic yet, so I dont know why this error happening. Sadly I have no time to do this now, but when I will, I will share the new version here.

**Comment by baskin** [comment]
@janein use the following instead with ionic-angular@2.0.0
`const enteringContent = new Animation(this.plt, enteringView.pageRef());`

**Comment by franzisk** [comment]
How to animate pages in tabs? Entering and leaving?
