### ISSUE TITLE
Ionic v2 beta11: swipeBackEnable option also affects Android and Windows devices.

### ISSUE THREAD

**Issue by yannbf** [driftyco/ionic#8190]
#### Short description of the problem:
When using `<ion-nav swipeBackEnabled="true" ...` on the project, the behavior is supposed to only affect iOS devices, but it also works on Android and Windows phone.

#### What behavior are you expecting?
Being able to swipe to go back *only* on iOS devices.

**Steps to reproduce:**
1. Add `swipeBackEnabled="true"` to `<ion-nav>`
2. Push a page to the navCtrl
3. Swipe from the left side

  
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

#### GIF showing the issue
http://imgur.com/a/eOBpU

System information:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa
Node Version: v6.6.0

**Comment by manucorporat** [comment]
@yannbf not a bug.
iOS already has swipeBack enabled by default, if you set `swipeBackEnabled="true"`, you are enabling it always.

**Comment by Yimiprod** [comment]
do i have to set `swipeBackEnabled="false"` in every view with beta 11?
