### ISSUE TITLE
Any update about IONIC-2 stable version release date ?

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [driftyco/ionic#8193]
Hi.. 

Can some one please let me know the release date for the stable version of IONIC-2 ?

**Comment by mhartington** [comment]
Ionic is a lot like baking a cake. Take it out of the over too soon, it's still raw in the middle. It will be ready when it's ready

**Comment by kelvindart** [comment]
Best analogy ever!

**Comment by GeorgeAnanthSoosai** [comment]
Any tentative date ?
