### ISSUE TITLE
Ionic2  beta 11 can't generate page 

### ISSUE THREAD

**Issue by Kayrohinc** [driftyco/ionic#8195]
ENOENT: no such file or directory, scandir '../node_modules/ionic-angular/templates/page'
  at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at getTemplatesInDir (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23931:65)
    at Generator.renderAndWriteTemplates (/usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25309:116)
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25304:26

**Comment by bastibense** [comment]
+1

**Comment by rcjsuen** [comment]
This is the same problem as issue #8104.

It's already been moved to [ionic-cli](https://github.com/driftyco/ionic-cli/issues/1381).

**Comment by ramonornela** [comment]
Close issue related #8178 @danbucholtz fix in commit https://github.com/driftyco/ionic/commit/60363b29e9630217ed7611bcbdf060dd86ac7dac

**Comment by danbucholtz** [comment]
Hi everyone,

We accidentally released this functionality early. This was supposed to be publicly available with beta.12 but it shipped early accidentally.  Please bear with us for a few days.

Thanks,
Dan
