### ISSUE TITLE
onPageWillLeave not fired when using Loading between two pages

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#8196]
Hi,

I noticed that, at least in my case, when I want to display a Loading during the navigation to the next page, the onPageWillLeave isn't triggered.

Let's assume I'm on Page1 and want to navigate to Page2. onPageWillLeave isn't fired when I do:

    let loading: Loading = this.loadingController.create({
          dismissOnPageChange: true
    });
    
    loading.present().then(() => {
        this.navController.push(Page2);
    }

But is triggered when I just do

      this.navController.push(Page2);

I'm using Ionic2 Beta11.

This isn't a major issue for me. I gonna explicitly call the methods to do in such cases.

Best regards

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am happy to report that this is solved in RC.0 by the queue'ing of transitions!
