### ISSUE TITLE
Generate Page Fails (Templates Folder Missing)

### ISSUE THREAD

**Issue by phancox** [driftyco/ionic#8202]
#### Short description of the problem:

Unable to generate templates (e.g., ionic g page MyPage).

The directory node_modules\ionic-angular\templates does not exist.

**Steps to reproduce:**
ionic start  TestApp blank --v2
cd TestApp
ionic platform add android
ionic g page NewPage
 

**Which Ionic Version?** 2.1.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0-beta.2
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.4.7

**Comment by rcjsuen** [comment]
Please see [ionic-cli issue #1381](https://github.com/driftyco/ionic-cli/issues/1381)

**Comment by phancox** [comment]
Sorry, I did all my searching on variations of "generate" so that didn't show for me.
