### ISSUE TITLE
Ability to set pagination bullets of ion-slide to white

### ISSUE THREAD

**Issue by apreg** [driftyco/ionic#8203]
I'd like to set the pagination bullets color of slide component to white simply via property or something.
I've seen classes ready for this inherited probably from http://idangero.us/swiper/ 
By the way I hacked it this way: `ion-slides .swiper-pagination {
  @extend .swiper-pagination-white
}`

**Comment by Eclektic** [comment]
CSS is the best way to customize ionic component.
I don't think it's needed to add an option for things like this. You have all the options you want for style in css ;)

And I think this is not the right place for your post, it is best to post that on the ionic forum : https://forum.ionicframework.com/c/ionic-2
Not really an issue.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The correct way to do this is with the sass that you have posted above. While we definitely appreciate your suggestion, i am not sure that a minor styling thing like this is worth another property on the `ion-slides` component. I will close this issue for now, but will re-open if we re-evaluate. Thanks!
