### ISSUE TITLE
bug: browser-plus not woking

### ISSUE THREAD

**Issue by laisdina** [driftyco/ionic#8204]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Uncaught Error: Cannot find module 'jquery-autocomplete'</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue for now as it seems to be an issue with a third party library you are using and not Ionic. Also, feel free to post about this issue on our [forum](https://ionicframework.com).
