### ISSUE TITLE
Unkown Error

### ISSUE THREAD

**Issue by Rebaiahmed** [driftyco/ionic#8205]
Hello everyone ,i need help , i get Unknown Error
![error1](https://cloud.githubusercontent.com/assets/13053759/18819028/0eefe418-8380-11e6-8b26-7f2dba13017a.png)
, then my controller is with depdency injection 
![erro_demo](https://cloud.githubusercontent.com/assets/13053759/18819033/3e446c02-8380-11e6-9e5b-baee98080090.png)

**Comment by danbucholtz** [comment]
Hi @Rebaiahmed,

We don't allow Q/A on our github issues as we use this feed for tracking work. The best place to ask Ionic questions and get a quality answer is the Ionic forum. Please re-post your question there.

https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA

Thanks,
Dan
