### ISSUE TITLE
Ionic2 Popover bug

### ISSUE THREAD

**Issue by kongdewen1994** [driftyco/ionic#8206]
Why in the Popover window to perform Pushing a View, the View of the content in the label content can't roll, even if the content is beyond the range

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting a screenshot of this issue? Thanks!

**Comment by kongdewen1994** [comment]
![](http://7xp2ia.com1.z0.glb.clouddn.com/1.png?e=1475127724&token=y77OZ1PgayCWMwh5lBtaUSwi27LFTXwp-69sg7TT:uM95wHQqJ3Xev9iOc0i6GB7dxs0)![](http://7xp2ia.com1.z0.glb.clouddn.com/2.png?e=1475127728&token=y77OZ1PgayCWMwh5lBtaUSwi27LFTXwp-69sg7TT:f_oIjYOQojz9Q_IpUv3ADpuRppY)

**Comment by jgw96** [comment]
Hello @kongdewen1994 , it seems that your screenshots are 404'ing. Would you be able to repost them?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by kongdewen1994** [comment]
I'm sorry, a little busy recently, in order to prevent accident, I provide address so that you see the picture.

1-  http://7xp2ia.com1.z0.glb.clouddn.com/1.png
2-  http://7xp2ia.com1.z0.glb.clouddn.com/2.png
