### ISSUE TITLE
ion-input: pass HTML5 input attributes to the input

### ISSUE THREAD

**Issue by tycho01** [driftyco/ionic#8209]
Please pass the HTML5 [`<input>` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) through to `ion-input`, as done in [`md-input`](https://github.com/angular/material2/blob/master/src/lib/input/input.html). The point here is that Angular 2 can use these attributes to match validator directives against, some of which come natively as part of [`@angular/forms`](https://angular.io/docs/ts/latest/api/) itself. It feels kind of silly a regular `<input>` now gets more functionality out of the box than the pretty-by-default `ion-input` does.

**Comment by devarg** [comment]
Yes, I agree, FormControlGroup is not able to apply "disabled" feature when you initialize the form group like this

```
description: [{value:'', disabled: false}, Validators.required]
```

When you change it to a plain basic input angular2 forms applies the disables ok. This is a great blocking because, if you manually set a [disabled] attribute you start messing with whole form validation status.

Maybe it should follow the logic with buttons

 ```
<button ion-button color="secondary" (click)="doSomething()">
```

**Comment by brandyscarney** [comment]
All attributes should be getting copied down to the native input now. `disabled` is also being passed down from a form group. If you are still having issues please let me know how I can reproduce it and I'll reopen. Thanks!

**Comment by CelinaSkywalker** [comment]
Noob question, but i coulnd't found anything to the topic. Passed down means that I can use it in the html tag as usuall? Because the value attribute here is not working and I wonder why?

`<ion-input max="40"
                         placeholder="{{editingPlato.price}}"
                         name="price"
                         value="{{editingPlato.price}}"
                         required
                         ngModel></ion-input>`
