### ISSUE TITLE
Ionic 2 Gesture docs

### ISSUE THREAD

**Issue by rubimazaki** [driftyco/ionic#8211]
Please provide us with some basic docs/example of using Ionic2 Gestures?

Current state is most annoying, because you cannot use the old (mousedown) or (mousemove) to create your own mechanism, while gesture handling is provided by Ionic2 just not documented AT ALL. Not even some basic example in the source tree. Nothing... 

Example anyone? 

Thanks :-)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#792
