### ISSUE TITLE
Changes of templates are ignored during buildUpdate

### ISSUE THREAD

**Issue by olostan** [driftyco/ionic#8216]
ionic 2.1.0-beta.2

When I run `ionic serve`, everything works ok until i change templates - app reloads, but templates are without my changes. Only stopping `ionic serve` and run again helps… making development process extremely slow

Seems `ng-template` plugin is not re-run or does not receive changes of templates.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1413

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because this was an issue with the Ionic cli and not the Ionic framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
