### ISSUE TITLE
When using ionic g page <page>, auto-update declarations & entryComponents in app.module.ts

### ISSUE THREAD

**Issue by jmatthiesen** [driftyco/ionic#8217]
As of Ionic 2 Beta12, there are a couple extra steps needed to add pages to your app, after using the `ionic g page <pageName>` generator. It would be great to see these steps automated by the generator, if possible.

Specifically - after creating the page, you have to go into your project's `src/app/app.module.ts` file and add the new page component to the `declarations` and `entryComponents` arrays.

For example, after running `ionic g page Page3`, I had to go into `app.module.ts` and change it from:

```
@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2
  ],
  providers: []
})
```

to

```
@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2,
    Page3
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2,
    Page3
  ],
  providers: []
})
```

**Implementation note:** I believe when you add new components to an app that you don't have to modify `entryComponents` every time, just when the Angular 2 compiler can't auto-detect those components (i.e. they aren't referenced from any templates). Since you can't predict where the end user will add a reference to a new page component, though, I'm thinking you'll want to always auto-add it to `entryComponents`.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1875
