### ISSUE TITLE
Toast behaviour not compliant with material design spec

### ISSUE THREAD

**Issue by adrm** [driftyco/ionic#8219]
#### Short description of the problem:

The toast component is not behaving as per material design spec.
#### What behavior are you expecting?

Citing [the spec](https://material.google.com/components/snackbars-toasts.html#):

> Usage
> Only one snackbar may be displayed at a time. 
> 
> Consecutive snackbars
> There is only ever one snackbar displayed. When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.

**Steps to reproduce:**
1. Trigger multiple toasts in different places of the screen in rapid sucession. This will show them all at the same time.
2. Trigger multiple toasts in the same place. They will overlap without waiting for the previous toast to disappear first.

**Which Ionic Version?** 1.x or 2.x
2.x
#### Plunker that shows an example of your issue

It's enough with [the example in the docs](http://ionicframework.com/docs/v2/components/#toast).

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

N/A

**Comment by danbucholtz** [comment]
I think this warrants a discussion. While I don't see a particular use case to multiple toasts on the screen at once, I'm not so sure it should be our job to police that, either.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#67
