### ISSUE TITLE
ion-searchbar should have an option to always show the back button

### ISSUE THREAD

**Issue by cleever** [driftyco/ionic#8220]
#### Short description of the problem:

ion-searchbar should have an option to always show the back button.
#### What behavior are you expecting?

Like the Whatsapp/Instagram behavior on their search contact modals.

**Which Ionic Version?** 1.x or 2.x

Ionic 2.x

**Comment by manucorporat** [comment]
Can you share a screenshot? I don't know what you mean? WhatsApp for iOS uses the same searchbar than ionic.

**Comment by cleever** [comment]
Since we don't have automatic focus on search bar component on Ionic, the back button/Cancel only shows when user give the focus to the search bar. Which is bad for modals.

On Android, whatsapp opens a search modal focused in search bar with back button.

![screenshot_20160926-1618392 small](https://cloud.githubusercontent.com/assets/2815335/18848740/23f6d9a8-8406-11e6-8443-eab6cce1ea06.jpg)

If the user scrolls the list and search bar loses focus, back button remains shown.

![screenshot_20160926-1615592 small](https://cloud.githubusercontent.com/assets/2815335/18848734/203ebd12-8406-11e6-8b9e-7f9443a5e497.jpg)

**Comment by gigocabrera** [comment]
+1

**Comment by gunterberger** [comment]
Is there any update to this issue?

**Comment by nkadu1** [comment]
Does anybody have work around this issue?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#174

**Comment by FelschR** [comment]
@jgw96 404...

**Comment by thisIsChetan** [comment]
Try to use the following CSS:

    .searchbar-ios-cancel{
        margin-right: 0px !important;
        opacity: 1!important;
        padding-left: 10px !important;
    }
    .searchbar-md .searchbar-md-cancel{
        display: inline-flex !important;
        background-color: white !important;
    }
    .searchbar-search-icon{
        display: none;
    }

It worked for me!!
