### ISSUE TITLE
bug: $ionicHistory.goBack(-2) does not fire $ionicView.leave

### ISSUE THREAD

**Issue by rinogo** [driftyco/ionic#8221]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>`$ionicHistory.goBack(-2)` does, indeed, navigate back two views, but it does not fire `$ionicView.leave` before leaving the current view.  I have verified that the same bug exists for `$ionicView.beforeLeave` and `$ionicView.afterLeave`.  I imagine the same bug also exists for `$ionicHistory.goBack(-3)`, etc.
## CodePen

Click Scientific Facts > More Facts and then experiment with the "goBack()" buttons.  Using the `goBack()` button causes the alert to be shown as expected.  Using the `goBack(-2)` button does not cause the alert to be shown.

http://codepen.io/rinogo/pen/Egmvjw</span>

<span is-issue-template></span>

**Comment by rinogo** [comment]
Bump

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#89
