### ISSUE TITLE
ion-content is being redrawn

### ISSUE THREAD

**Issue by ekhmoi** [driftyco/ionic#8222]
Ion-content is being redrawn when it has several images 

[Video](https://youtu.be/SJF9UIjL0Bo) - with images (with bug) you see the page blinks every time popover or prompt is going to appear

[Video](https://youtu.be/UyzGhhacHU8) - with ion-list (no bug)
[Repo](https://github.com/ekhmoi/ion-demo) with sample application to demonstrate

To reproduce the issue 
-create new ionic2 project
-add same cards to the page you want to test
-add button to the same page
-create AlertController

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am glad to report that I cannot reproduce this issue with beta.12. Thanks!

**Comment by ekhmoi** [comment]
Hello, you can not reproduce this issue in browser, sorry i forgot to say that.
Please use device or emulator
