### ISSUE TITLE
useless code in ListPage component (ionic2-starter-tutorial)

### ISSUE THREAD

**Issue by xit0c** [driftyco/ionic#8224]
Hi Ionic Team! I'm trying for the first time Ionic v2 and I started my journey with the tutorial (https://github.com/driftyco/ionic2-starter-tutorial). I can't figure out why there is the selectedItem property in the ListPage component: it never uses that property and the itemTapped(event, item) method already has all the information the ItemDetailsPage component needs.

It seems like a copy-paste oversight because in both components there are the same line and comment, but they only make sense for ItemDetailsPage:

`// If we navigated to this page, we will have an item available as a nav param
this.selectedItem = navParams.get('item');`

Also, these are the last lines of both list.html and item-details.html

`<div *ngIf="selectedItem" padding>
You navigated here from <b>{{selectedItem.title}}</b>
</div>`

I removed the lines above from list.ts and list.html and the app still works, but, since I'm a beginner, I don't know if I'm missing something or not :\

**Comment by kelvindart** [comment]
Not redundant, in the pairing HTML file, there's an *ngIf directive which determines whether the item is selected, which is used as a breadcrumbs feature in the tutorial app.

**Comment by xit0c** [comment]
Breadcrumbs? Where? I can't see any breadcrumb in the whole app... In list.html the *ngIf directive comes after (and out of) the `<ion-list>`. Should the breadcrumbs be placed at the bottom of the list?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
