### ISSUE TITLE
Release dates. Roadmap.

### ISSUE THREAD

**Issue by troyanskiy** [driftyco/ionic#8227]
Hello.

I'm sorry to creating the questions issue, but can anybody answer when (dates) next releases (beta.12, ..., rc.0, ..., final) will be released?
I've found the [roadmap](https://docs.google.com/document/d/1Qlc5X2eJyOB0izkFlH7KJ5BmMi0MeXUZRHJHt3hS6Wo/edit#heading=h.74mckordybvz) but there is no any dates.

I'm wander is it possible to add any release dates? Do you have any clean planing with deadlines etc?
Without any clean (transparent) planing with deadlines or any other dates the Ionic framework development looks like student's hobby. I do understand before it was hard to plan anything because you was depended on Angular2 development. But now angular2 is finally released and probably you can plan next releases up to final one.

Could you please create the transparent roadmap to final release?
**It will help developers to plan there's development.**

**Comment by izee** [comment]
+1,I feel slowly too!

**Comment by rcjsuen** [comment]
Don't know how feasible this will be for 2.0 but I am hoping they will get into a regular release rhythm after 2.0 goes GA.

If nothing else there should be a dev mailing list of some sort. Users can then see what features and bugs are being discussed and what blockers are preventing a release from going out.

**Comment by owlcode** [comment]
[Let them work guys ;)](https://forum.ionicframework.com/t/status-of-ionic-2-beta-12/63213/28)

**Comment by troyanskiy** [comment]
@owlcode I believe that they are working. The thing is that I would like to know any dates to say something to my clients and plan the work for my developers.

**Comment by jgw96** [comment]
Hello all! We just announced rc0 this morning at Angular Connect in london! This will be released by the end of the day today! You can watch our [blog](http://blog.ionic.io/) and [twitter](https://twitter.com/ionicframework?lang=en) to know when the code is released to npm. We plan on iterating very fast towards a final release. Once final is out we will be on a regular release rhythm. Also, with every release we always update the changelog and tweet. We also do milestones here on github so that users can follow our progress. Thanks for using Ionic!

**Comment by troyanskiy** [comment]
@jgw96 **WOW**! That's really great news! Thanks a lot!

**Comment by izee** [comment]
has any guide for upgrade from beta.11 to rc.0?

**Comment by jgw96** [comment]
Hello @izee we are currently working on pushing the new release to the docs site along with updating the changelog for the rc.0 release. This will include steps on how to upgrade a beta.11 project to RC.0. If you would like to see the preview of the changelog you can check out this [google doc](https://docs.google.com/document/d/1cCHh9dFENjy7D6yrZDQ2MNBgzTRZ5LToRhKegGfnbBg/edit) Thanks!
