### ISSUE TITLE
feat: Ionic android application security

### ISSUE THREAD

**Issue by sumedhap** [driftyco/ionic#8231]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview></span>

<span ionic-description>Hello, as I am working on ionic apps. I have created android apps and also uploaded it on play store. Now what I want is to stop decompilation of my project code. I want to avoid reverse engineering on apk. please let me know if there is any way to solve this issue.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
