### ISSUE TITLE
bug: Ionic 2 - Tab page lost back navigation

### ISSUE THREAD

**Issue by sridharan31** [driftyco/ionic#8233]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Before my tabs page, I have few other regular pages and the "< Back" is always present at the left corner.

When reaching my tabs page, I am losing the "< Back" in my header. Why?

How do I get the back button back when using tabs in Ionic2?</span>

<span is-issue-template></span>

**Comment by raducostea** [comment]
Its the navigation component in the Tabs page or in the Tab page? It should now show if its in the Tab page since its part of the tab navigation. Setting your ion-navbar component in the ion-tabs page should show the back button.

**Comment by zakton5** [comment]
If I understand correctly you have a stack similar to this:
```
Page1 -> Page2 -> TabPage (<-- Back button missing here)
                     |--> Tab 1
                     |--> Tab 2
                     |--> Tab 3
```

I've brought up this issue before and it was dismissed because a Tabs page should always be the root of an application (I disagree). They did not design Tabs to be anything except the root. Here is the workaround that I use:

On the root page of each tab, add this class to the navbar.
```html
<ion-header>
    <ion-navbar class="show-back-button">
        <ion-title>
            Title
        </ion-title>
    </ion-navbar>
</ion-header>
```

And here is the CSS
```css
ion-navbar.show-back-button .back-button {
    display: inline-block;
}
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Currently tabs is designed to be used as the root component of an app to match the use of tabs in the native world. If you would like to get similar functionality to tabs in a non-root component you can use our [segments component](http://ionicframework.com/docs/v2/components/#segment). Thanks!

**Comment by dweber019** [comment]
For me the described issue doesn't appear.

On thing to mention is that if you reload the page the navigation stack get's lost and therefor the back arrow disappears. This was the reason I found this bug.

Im using Ionic 3.
