### ISSUE TITLE
ionic2 - enhancement(events) - Unsubscribe method should be an optional parameter

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8235]
#### Short description of the problem:
Nothing major here, but currently to unsubscribe from a topic you have to write
```ts
this.events.unsubscribe('some-topic', null);
```
This code removes all handlers tied to event 'some-topic'. The null is required.

#### What behavior are you expecting?
I feel the handler parameter should be optional, yet have the same behavior as is. So I feel like the following code should be valid and still remove all handlers tied to 'some-topic'.
```ts
this.events.unsubscribe('some-topic');
```

**Comment by Lyricalz** [comment]
Agreed
