### ISSUE TITLE
Ionic View - Android latest version - Cannot connect to server

### ISSUE THREAD

**Issue by cnngraphics** [driftyco/ionic#8237]
#### Short description of the problem:
Load Ionic View App
Enter email
enter password
Logged in and --> "No apps yet", but I do have 6 apps when I look at to online version of ionic account

"PULL down to refresh" ==> Unable to connect to server. Status code: 404

What happened to the "ionic upload" command. 

Where are my uploaded apps that I used to view in ionic view app?

**Comment by cnngraphics** [comment]
Looks like in the Playstore, others are experiencing this issue and are suggesting to switch to phonegap build.

Anyone else having issues?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#188

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I have alerted the Ionic view developer and have moved this issue to the appropriate repo. Sorry for any hassle this issue causes.
