### ISSUE TITLE
Support stable Angular2.0 & Webpack

### ISSUE THREAD

**Issue by Nishchit14** [driftyco/ionic#8242]
What is the expected time to release with Angular2.0? Ng2.00-rc-5 has many major changes and current Ionic2 using rc-4.

And current build system using gulp, But now a days webpack is very famous for bundling.  Angular2 also recommended to use webpack. https://angular.io/docs/ts/latest/guide/webpack.html 

Please let me know if there is any way exists to solve this problem.

Thanks for this lovely framework :)

**Comment by NoNameProvided** [comment]
The next Ionic 2 Beta (2.0.0-beta.12) coming in this or next week will use the last RC of Angular 2 (2.0.0-rc.7). The following Ionic 2 RC 0 will be probably built on Angular 2.x already.

**Comment by Nishchit14** [comment]
Thanks @NoNameProvided 
I found that https://github.com/driftyco/ionic/tree/beta.12/demos this repo using rc-7.

But there is not major changes form rc7 to 2.0. So if we direct use stable 2.0 with Ionic then it would be great.
It is just my opinion. :)

**Comment by herbzi** [comment]
I mean Ionic 2 RC 0 is already out. I can update ionic and run ionic start myApp --v2. It seems to be running angular 2.0.1 despite the changelog not mentioning it. It seems to be offline template compiling and has a module definition. It's just the changelog doesn't seem to mention anything about it, nor the steps I need to upgrade to it.

**Comment by Nishchit14** [comment]
Thanks @herbzi  for clarification.
I'm trying with this`sudo npm install ionic@2.1.0 -g`

**Comment by danbucholtz** [comment]
Ionic RC 0 technically dropped yesterday but the formal release will be today.

We are going with Rollup instead of Webpack for the bundling process. We think it is better and faster so that's what we're going with. We saw apps start-up ~3.5x faster with Rollup in our testing.

I'm going to close this. Please stay tuned today for the official announcement.

Thanks,
Dan
