### ISSUE TITLE
Missing Tag rc0

### ISSUE THREAD

**Issue by ramonornela** [driftyco/ionic#8245]
I think that missing generation of the [tag](https://github.com/driftyco/ionic/tags).
Perhaps  lacked a little adjustment in the gulp for this 😉. 

If the process has changed and it is intentional Sorry me

Thanks

**Comment by royipressburger** [comment]
+1. Also is there a place where i can see how to update from beta 11 to rc 0? The changelog doesnt states how

**Comment by danbucholtz** [comment]
This is still a WIP. We had some technical difficulties yesterday that slowed us down a bit. Expect more details later today.

Thanks,
Dan

**Comment by ramonornela** [comment]
Close issue tag was generate :wink:

Thanks
