### ISSUE TITLE
Please include the timezone offset option by default in the ion-datetime element’s formatting options.

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#8247]
Timezone offsets are among the commonest requirements in datetime formatting (in my opinion).

**Comment by manucorporat** [comment]
@infinnie can you develop more your feature request?
- more details
- a screenshot?
- your use case

Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by infinnie** [comment]
I just want an option for adding a timezone offset.

If you by any means want to have a better i18n support this is what you should do.

**Comment by CarlosFJ** [comment]
Hi I need select the currentDay when i tap in the ion-datetime.
currentDay works ->  currentDate : string = moment().format('YYYY-MM-DD');
