### ISSUE TITLE
Enchantment : ios pull to search 

### ISSUE THREAD

**Issue by comfortme** [driftyco/ionic#8248]
hello ! 
So i wanted to implement a very common ios feature pull to search in my project.
I was sniffing around in ion-refresher docs (because the pulling mechanism is very similar)and found out the ion-refresher-content is a custom html and shown as long as the refreshing lasts. so i said why not a searchbar with endless loading.
and i did this :

`<ion-refresher (ionRefresh)="doRefresh($event)">
    <ion-refresher-content>
<ion-searchbar>
</ion-searchbar>
</ion-refresher-content>
  </ion-refresher>`

when user pulled the page it revealed the searchbar but that means app is on loading stage and the page is not scrollable... so i solved it with a little css `scroll-content{overflow-y: scroll!important;}` . Everything worked fine and when user is done searching and pressed the searchbar's close button i called complete() methot on the ion-refresher and the searchbar is hidden.
I would really want to see this feature on ionic by default.

**Which Ionic Version?** 1.x or 2.x
ionic v2

**Comment by Katur7** [comment]
I am also implementing this feature.
I did the same but left out the ```<ion-refresher-content>```
That worked well and the searchbar appears as expected.

I have the scrolling issue while the refresher is open and ```scroll-content{overflow-y: scroll!important;}``` is not working.

It would also be great to be able to close the refresher by pulling the page up (opposite of what is needed to show it). Currently it appears the refresher does not listen to move events when it's in the 'refreshing' state.

**Comment by comfortme** [comment]
of course it does not work because scroll-content is not a special element anymore.
you should try,
div.scroll-content{overflow-y: scroll!important;}

**Comment by jgw96** [comment]
Hello all! Because this seems to be very custom to your app and not something widely needed we are going to close this issue for now. Thanks for using Ionic!
