### ISSUE TITLE
bug: Tabs are not showing in KitKat

### ISSUE THREAD

**Issue by HorseFly** [driftyco/ionic#8253]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>The tabs are showing as a white bar with no text or icons, but they are clickable.  I am using a Samsung Galaxy Tab 4.  

I haven't reproduced it, but someone else has via the Ionic Forum: https://forum.ionicframework.com/t/tabs-not-showing-on-android-menu-tabs/62242

This problem doesn't seem to happen in Marshmallow.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! What version of Ionic 2 is your app running? beta.11?

**Comment by HorseFly** [comment]
Yes, beta 11.

**Comment by jgw96** [comment]
Thats what i expected, this issue has been fixed in the latest rc.0 release. You can see our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc0-2016-09-28) for how to update your app. Thanks!

**Comment by HorseFly** [comment]
Ok, thanks!  I didn't realize rc.0 was released.  I will give it a try.
