### ISSUE TITLE
Malloc pointer being freed was not allocated -- Ionic1

### ISSUE THREAD

**Issue by snehoo** [driftyco/ionic#8259]
Everything was running fine then suddenly this, oh yeah upgraded to Sierra before this bug and now using xCode 8.0.

```
malloc: *** error for object 0x1740b6e00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

looked everywhere, tried restarting everything.

<img width="761" alt="screen shot 2016-09-26 at 2 30 55 am" src="https://cloud.githubusercontent.com/assets/7123866/18926699/727b0276-85d6-11e6-86ef-84e9b89f45ec.png">

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! What command are you running when you get this error? It looks like you are using the wkwebview plugin, am i correct?

**Comment by snehoo** [comment]
Yes using wkwebview plugin.

ionic prepare ios, then executed the xcode project via xCode and then Build and Run on iOS device.

everything ok till i upgraded to Sierra and xCode 8. Thanks

**Comment by jgw96** [comment]
If possible, could you try with a project that is not using the WkWebView plugin and see if you get the same error? Thanks!

**Comment by snehoo** [comment]
YEP! i guess that was it 🙏

**Comment by jgw96** [comment]
Interesting, thanks for testing! Are you using [our fork](https://github.com/driftyco/cordova-plugin-wkwebview-engine) of the plugin?

**Comment by snehoo** [comment]
yes same one

**Comment by jgw96** [comment]
This issue was moved to driftyco/cordova-plugin-wkwebview-engine#57

**Comment by jgw96** [comment]
Thanks! Since this is an issue with the wkwebview plugin and not Ionic I have move this issue to the appropriate repo.
