### ISSUE TITLE
[2.0.0-rc.0] - Plugin SimInfo installed but gives an error

### ISSUE THREAD

**Issue by vlados** [driftyco/ionic#8261]
# Steps to reproduce
1. Update everything so you can use 2.0.rc0
2. ionic start --v2 sim
3. ionic plugin add cordova-plugin-sim
4. Open sim/src/pages/home/home.ts
5. Put the code according to the docs - http://ionicframework.com/docs/v2/native/sim/
6. ionic run android
7. Error: 
`Native: tried calling t.getSimInfo, but the t plugin is not installed.`
`main.js:22 Install the t plugin: 'ionic plugin add cordova-plugin-sim'`
`main.js:27 Unable to get sim info:  plugin_not_installed`

Code: https://bitbucket.org/vstoitsov/ionic2-simbug/src

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue as it is an Ionic-Native issue and will be handled in the ionic-native issue that was opened in the above linked issue.

**Comment by vlados** [comment]
So I need to post it in the ionic-native repo?
