### ISSUE TITLE
Cordova Facebook Ads crashes App flowing upgrade to iOS 10 and Xcode 8

### ISSUE THREAD

**Issue by antonfire** [driftyco/ionic#8264]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

When running this plugin in iOS10 from Xcode 8 the app crashes. The error in the Xcode console is:

malloc: *** error for object 0x1740bd940: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

This occurs when the 'createNativeAd' function is called but not immediately. I have narrowed it to this function through my own testing.

To resolve this I have tried updating the FB Audnet SDK framework (and the other FB SKD frameworks) to the latest versions but the problem persists.

I am rendering native ads. If you test on iOS 10 I assume you will get the same result. I can't see what the breaking change is from upgrading to Xcode 8 and iOS 10. It was working great before.

#### What behavior are you expecting?

Normal rendering of native adverts.

**Steps to reproduce:**
1. Install cordova facebook Ads https://github.com/floatinghotpot/cordova-plugin-facebookads and setup in facebook for native advert.
2. Create native add in ionic on iOS10 with latest ionic, cordova, cordova iOS, Facebook SDKs (inc audience network) and Xcode 8.
3. Build, then breaks when the objective c function 'createNativeAd' (in the cordova plugin) is called.

```
No abnormal code, as detailed in plugin docs.
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
My ability in Xcode to drill down in the following to find the issue is limited...

malloc: *** error for object 0x1740bd940: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Which Ionic Version?** 1.x or 2.x

2.0 in cli when do ionic -v and programmed in ionic 1.

#### Plunker that shows an example of your issue

Can't provide and cordova based.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.1.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by danbucholtz** [comment]
This sounds like it is an issue with the Facebook cordova plugin.  Can you make an issue over there instead? This is outside of the scope of Ionic.

Thanks for contributing,
Dan
