### ISSUE TITLE
bug: sass is erroring when light color is removed

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#8266]
When the `light` color is missing from the `$colors` map, Sass is throwing the following error:

```
[20:51:46]  Sass Error: line: 80, column: 3


  The value `` must be a color.
  If you are setting the value as a map make sure
  both the base and contrast are defined as colors.

  For example:

  $colors: (
    primary:    #327eff,
    secondary:  (base: #32db64, contrast: #000),
  );
```

This should not happen unless `primary` is removed, and it needs a better description for that use case.

**Comment by alan-agius4** [comment]
the issue with the colors issue that the "light" is required because it's being used in the ionic.theme.dark.xx.scss and fab.xx.scss

**Comment by ramoncarreras** [comment]
Same problem, now with danger color.

```
sass: node_modules/ionic-angular/themes/ionic.functions.scss, line: 109
The map color `danger` is not defined. Please make sure the color exists in your `$colors` map. For example:
    $colors: ( danger: #327eff );
```

> Cordova CLI: 6.4.0
> Ionic Framework Version: 2.0.0-rc.3
> Ionic CLI Version: 2.1.12
> Ionic App Lib Version: 2.1.7
> Ionic App Scripts Version: 0.0.46
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.11
> OS: macOS Sierra
> Node Version: v7.1.0
> Xcode version: Xcode 8.1 Build version 8B62

**Comment by MarcVertigo** [comment]
Did you ever figure this out?
