### ISSUE TITLE
RC.0 - <ion-tabs> are not visible in the Chrome browser, ok in Device Mode

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#8268]
#### Short description of the problem:

Just playing with the new ionic2 RC0 release using the `ionic2-starter-tabs`, and I noticed that the bottom tabs `<ion-tabs>` are not visible in Chrome in the browser. The ARE visible in Chrome when in Device Mode. Seems to work fine in Safari.

#### What behavior are you expecting?

Bottom tabs appear.

**Steps to reproduce:**

```
ionic start --v2 myProject
cd myProject
ionic serve
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?**  v2 RC.0

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue with the latest version of chrome and Ionic 2 rc.0. Would you mind posting a repo i can use to reproduce this issue? Thanks!

**Comment by mixersoft** [comment]
I recreated my project now and it seems to be fine. It's really weird. Maybe it's because I was creating the project just as RC.0 was being released and I got some mismatched parts?
