### ISSUE TITLE
Ionic 2 storage doesn’t have query method

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8269]
I'm updating my app to Ionic 2 rc0 and using import {Storage} from "@ionic/storage"; But it doesn't have query method. It was there in beta 11 to query SQLite. How to query SQLite in rc0?

**Comment by bergmito** [comment]
### Try it

 import { SQLite } from 'ionic-native';

let db = new SQLite();
db.openDatabase({
  name: 'data.db',
  location: 'default' // the location field is required
}).then(() => {
  db.executeSql('create table danceMoves(name VARCHAR(32))', {}).then(() => {

  }, (err) => {
    console.error('Unable to execute sql: ', err);
  });
}, (err) => {
  console.error('Unable to open database: ', err);
});

**Comment by aggarwalankush** [comment]
@bergmito Storage uses SQLite behind the scenes so why not query method because it was available in beta 11. I don't see any reason to remove it in rc0.

**Comment by okonon** [comment]
@aggarwalankush clearly something has changed in beta 11 i used to do:
```
import { SqlStorage, Storage } from 'ionic-angular';
...
storage = new Storage(SqlStorage);
```

But after rc0 upgrade am getting following error:
`/node_modules/ionic-angular/index"' has no exported member 'SqlStorage'.`
@jgw96 did you guys get rid of `SqlStorage` ?

**Comment by aggarwalankush** [comment]
@okonon I also used to do same but now we have @ionic/storage which automatically uses Sqlite behind the scenes, I don't know where is query method? @mlynch implemented that in this [commit](https://github.com/driftyco/ionic/commit/f817ac0f6087e35e76086817e3a55c5c1b3fc4c1), maybe he can answer 👍

**Comment by baffleinc** [comment]
+1 - was using Storage.query() heavily!

**Comment by stephanowallace** [comment]
I'm having the same problem. In my app I have a "service" with a lot of queries that access and change data in my database (sqlite). I use the query method and return promises (it isn't working anymore too), will I have to change all my code because of this change?

**Comment by rafaelss95** [comment]
Same here. I'm using the query method for everything.

**Comment by danbucholtz** [comment]
Hi everyone,

I have passed this info along to the team and will keep you posted on this.

Thanks,
Dan

**Comment by chmdznr** [comment]
**Additional Error (ionic rc 0)**
When using example code from:
[http://ionicframework.com/docs/v2/native/sqlite/](http://ionicframework.com/docs/v2/native/sqlite/)
Got these errors (already try it on browser, emulator, ios device.. all the same) :
`ERROR:  ReferenceError: sqlitePlugin is not defined
    at http://localhost:8100/build/main.js:78458:13
    at new t (http://localhost:8100/build/polyfills.js:3:15614)
    at SQLite.openDatabase (http://localhost:8100/build/main.js:78457:16)
    at new PCounter (http://localhost:8100/build/main.js:79945:24)
    at DebugAppView._View_HomePage_Host0.createInternal (HomePage_Host.ngfactory.js:20:24)
    at DebugAppView.AppView.create (http://localhost:8100/build/main.js:10658:21)
    at DebugAppView.create (http://localhost:8100/build/main.js:10870:44)
    at ComponentFactory.create (http://localhost:8100/build/main.js:6276:36)
    at NavControllerBase._viewInit (http://localhost:8100/build/main.js:46701:44)
    at NavControllerBase._transition (http://localhost:8100/build/main.js:46686:18)`

**Comment by richardshergold** [comment]
I got the same - looking forward to hearing what we need to do!

**Comment by danielabbatt** [comment]
Yes agreed, rightly or wrongly I was relying on Storage as an abstraction later to interact with a DB using .query - It would nicely abstract to websql or sqlite depending on whether I was working with "ionic serve" in the browser or against an actual device.

**Comment by davidnmbond** [comment]
Another project broken here.  Following this decision, how should be be abstracting queryable storage to work in both browser (for debugging with ionic serve) and the device environments?

This seems like a pretty fundamental bit of functionality that Ionic 2 just lost :(

**Comment by edismooth** [comment]
I hope they will restore it ASAP - a lot of projects are using that functionality.

**Comment by richardshergold** [comment]
@bergmito have you tried that code in RC.0 ?  I have tried it (straight from the docs) and it doesn't work for me?

**Comment by aldo-roman** [comment]
This is urgent. RC0 is useless without Storage query method :/

**Comment by aggarwalankush** [comment]
Hi All,

I can't upgrade to rc0 😢   because of unavailability of query method so I'm unsure about below issue.

_Following issue is not regarding query method, it's regarding **get and set** methods_

**Till beta 11**, storage was in ionic-angular and it used to use `kv` as table name. https://github.com/driftyco/ionic/commit/f817ac0f6087e35e76086817e3a55c5c1b3fc4c1#diff-7e4a48359dfcc9528da611464b28ec11L87

**Now from rc**, storage has been moved @ionic/storage and as per my understanding, it uses `_ionickv` as table name https://github.com/driftyco/ionic-storage/blob/master/src/storage.ts#L42

But my app is in production with beta 11 and there would be lot of user data in `kv` table. So after upgrading to rc, how do I migrate `kv` table data to `_ionickv`?

Let me know if I can provide more details.

-Thanks

**Comment by larssn** [comment]
I'm having to downgrade to beta 11 to get this method back. I can't use a simple key/value store in my app sadly.

**Comment by drantunes** [comment]
This is a important issue to solve!

**Comment by bergmito** [comment]
@richardshergold yes. Here worked!! You add   

providers: [  
    Storage  
 ]

in app.module.ts?

**Comment by drantunes** [comment]
I tried replace by SQLite, but it's not working here. An error related to NgModule :(

**Comment by aldo-roman** [comment]
try replacing

`this.storage.query("...")`
with
`this.db.executeSql("...", {})`

you need two variables:
storage: Storage (get, set)
db: SQLite (executeSql)

**Comment by drantunes** [comment]
@aldo-roman ReferenceError: sqlitePlugin is not defined. 
I tried insert SQLite in AppModule, in the providers array, but not working

**Comment by richardshergold** [comment]
@bergmito Oh - I thought I'd tried that.  Will try again in the morning (late here in the UK).  Thanks

**Comment by NickStemerdink** [comment]
@drantunes did you add the plugin?
`$ ionic plugin add cordova-sqlite-storage`

**Comment by drantunes** [comment]
@NickStemerdink yes. 

The `ionic plugin list` returns `cordova-sqlite-storage 1.4.7` as installed. 
I think this issue is related to NgModule

**Comment by aldo-roman** [comment]
@drantunes in `app.module.ts`

```
@NgModule({
  declarations: [
    MyApp,
    ...
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    ...
  ],
  providers: [Storage, SQLite]            // insert providers here
})
export class AppModule {}
```

**Comment by mlynch** [comment]
Hey all, a query method doesn't make sense unless you _know_ you are using SQLite. In that case, I think it's a better idea to use SQLite directly from ionic-native or from a sqlite plugin specifically: http://ionicframework.com/docs/v2/native/sqlite/

cc @danbucholtz. I don't think we should add this (also this issue belongs in https://github.com/driftyco/ionic-storage

**Comment by drantunes** [comment]
@aldo-roman I did it, but not working yet. 

I tried run in Android in live reload mode, and the Chrome inspect reported same error

**Comment by aldo-roman** [comment]
@drantunes I think you also need to add it to the component, per [Angular docs](https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#injector-providers)

I created an `@Intectable()` service and add that to my pages. Idk if that's the same setup for you.

**Comment by aggarwalankush** [comment]
@mlynch Thanks for the reply. If I use SQLite directly from ionic-native, it won't fallback to WebSQL(deprecated as you said). Then how can I test my app functionalities in browser? Do I need to do ionic build everytime and test in simulator/device? 😨

**Comment by Chris1308** [comment]
I get another error when using storage:
Error: Module C:\users\user\project\node_modules\@ionic\storage\dist\es5\index.js does not export Storage (imported by C:\users\user\project\.tmp\app\app.module.js)

What can i do?

**Comment by jeromeXoo** [comment]
@aggarwalankush If you are using SQLite directly, you can add the fallback to websql for testing in browser. This is just a convenience for testing. There is a misunderstanding.

**Comment by Chris1308** [comment]
If anyone else has trouble using Storage (in combination with firebase), look at this thread:
https://forum.ionicframework.com/t/error-module-node-modules-ionic-storage-dist-es5-index-js-does-not-export-storage/64903/4

**Comment by Chris1308** [comment]
I have now another issue:
When i'm injecting the storage, i get the following error:
TypeError: this._db.config is not a function
    at new Storage (storage.js:38)
    at NgModuleInjector.get (AppModule.ngfactory.js:343)
    at NgModuleInjector.get (AppModule.ngfactory.js:373)
    at NgModuleInjector.get (AppModule.ngfactory.js:383)
    at NgModuleInjector.AppModuleInjector.getInternal (AppModule.ngfactory.js:522)
    at NgModuleInjector.get (ng_module_factory.js:94)
    at ElementInjector.get (element_injector.js:29)
    at ElementInjector.get (element_injector.js:29)
    at ElementInjector.get (element_injector.js:29)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:786)

Any ideas?

**Comment by klochko7** [comment]
Hi all! Who can explain please or show little example how properly now using in rc0 Storage with sqlite ?

**Comment by richardshergold** [comment]
You need to use the sqlite plug in - see here

http://ionicframework.com/docs/v2/native/sqlite/

**Comment by klochko7** [comment]
**richardshergold**, Thanks! Will this working now ? https://www.thepolyglotdeveloper.com/2015/12/use-sqlite-in-ionic-2-instead-of-local-storage/

**Comment by richardshergold** [comment]
Yes, that should help you.

**Comment by klochko7** [comment]
**richardshergold,** Thanks!

**Comment by zakton5** [comment]
@mlynch As @aggarwalankush said above, how are we supposed to fall back to websql when testing in a browser. The process was so seamless before, so i do not understand why query was removed at all. If I understand correctly, we now have to use the ionic-native SQLite plugin (which only works on the device), but use the Storage get/set API in the browser? Is that correct?

**Comment by klochko7** [comment]
If ionic-native SQLite plugin only works on the device ? How debug it ?

**Comment by davorpeic** [comment]
@klochko7 same way as before? Safari for IOS, Chrome for android

**Comment by klochko7** [comment]
**davorpeic**, Can I run app with ionic-native SQLite plugin and see result ?

**Comment by davorpeic** [comment]
@klochko7 no, ionic-native is for use only on device, it will not work in browser, but this is not new, please check http://ionicframework.com/docs/v2/native/ for more info.

**Comment by NickStemerdink** [comment]
I've created a quick example of how to use Sql storage by creating your own provider (based on the original), see this gist: https://gist.github.com/NickStemerdink/64c782807fc31b7bc9b529ad4b1d56d5

Note: this is just meant to point you in the right redirection and might still need some modifications.

**Comment by klochko7** [comment]
**davorpeic**, Thanks! How now debug sqlite in browser ? We do not have console for error on device.

**Comment by davorpeic** [comment]
@klochko7 I think we are going off topic here, please consult documentation how to remote debug your app on device http://ionicframework.com/docs/v2/resources/developer-tips/#debugging-ios-safari

**Comment by klochko7** [comment]
**davorpeic** , Thanks!

**Comment by mlynch** [comment]
@zakton5 I will see if it makes sense to integrate a websql fallback. However, if browsers drop support for it, then it won't be very helpful. In that sense, I don't want you to rely on WebSQL existing, that will cause other pains down the road :)

Thanks everyone for responding and adding workarounds/etc. I will monitor this and see if we can't come up with a middle ground.

**Comment by okonon** [comment]
@mlynch can we fall back to IndexedDB instead of WebSQL?

**Comment by okonon** [comment]
@mlynch i guess if your `Storage` module is built on top of LocalForage it already has support for indexedDB. How do I tell Storage to use IndexedDB?

**Comment by jgw96** [comment]
I would just like to add my two cents to the websql thing here. I would not be in favor of integrating any kind of websql fallback as I have seen some strong signals on the web that websql will be in danger of deprecation in chrome once indexedDB 2 hits, leaving Safari as the only browser that implements it. Also, websql is not a web standard anymore, and therefore is not being improved or maintained.

**Comment by okonon** [comment]
@jgw96 can we tell `Storage` to use IndexedDB

**Comment by mlynch** [comment]
For those interested in the old engine, I think something we could do is create a similar module, like `ionic-storage`, but with just the old `SqlStorage` option. In fact, maybe it could be added to `ionic-storage` if you want to use SQL and you want to use the full sql engine. Then again, don't want folks to get hooked on WebSQL.

As for Storage to use IndexedDB, we are adding configuration shortly to specify that you wish to use it. For now, it doesn't really get you much because 1) it's not supported equally across browsers yet, and 2) as a key/value you'll get similar results to any of the other engines. However, we need to add this.

**Comment by okonon** [comment]
understood. thanks

**Comment by ajsmolen** [comment]
Thank you @NickStemerdink,  your example worked like a charm!

**Comment by aggarwalankush** [comment]
@mlynch Consider 6 months from now, browser dropped WebSQL and my database is relying on Sqlite. There is no way to debug app in browser. Then the advantage of testing ionic apps in browser is gone. Like native apps, we have to rebuild and test in simulator/device. 

Is that the future? 😢

**Comment by zakton5** [comment]
So I would agree with what everyone is saying about WebSQL being deprecated. There is no sense in using and designing around if that is true. But its very unfortunate because my entire app was built around this API and using WebSQL to test in the browser, and there was no communication that this functionality would be removed. It would have been nice to have a temporary solution or at least keep WebSQL in the meantime until the IndexedDB functionality comes out.

**Comment by danbucholtz** [comment]
@zakton5,

Here is the old code. Feel free to include in your app - but be aware WebSQL is going to drop at any point in time and we are not formally supporting this code or solution any more.

https://github.com/driftyco/ionic/tree/feature/progressbar/src/platform/storage
https://github.com/driftyco/ionic/blob/feature/progressbar/src/platform/storage.ts

Some of the code that it depends on is not a public API, so you'll have to read the src a bit to get it in good shape. It shouldn't be too hard to do, though.

Thanks,
Dan

**Comment by gilcierweb** [comment]
Soluction
https://gist.github.com/NickStemerdink/64c782807fc31b7bc9b529ad4b1d56d5
```
if (this.platform.is('cordova')) {
            this.database = (<any>window).sqlitePlugin.openDatabase({name: this.db_name, location: 'default'}); //mobile
            } else {
                self.db = window.openDatabase(DB_CONFIG.name, '1.0', 'database', -1); //debug web
            }
```

**Comment by riccardotreagles** [comment]
So are we sure? In the rc0 and in the next rc, to manage database we have to use SqlLite, and WebSql for debug. Is it ok? Or Ionic team is thinking to another solution? I'm starting the porting from SqlStorage to SqlLite and I wouldn't  change again in the future my code.

**Comment by gilcierweb** [comment]
There is no more sql storage was all moved to ionic / storage that does not support SQL queries more key value only so I posted the solution! above.
https://github.com/driftyco/ionic-storage

**Comment by FdezRomero** [comment]
@aggarwalankush That is why you shouldn't rely on SQLite specifically if you want to run your app on Chrome. From https://github.com/driftyco/ionic-storage/blob/master/src/storage.ts:

```
 * When running in the web or as a Progressive Web App, Storage will attempt to use
 * IndexedDB, WebSQL, and localstorage, in that order.
```

From a PWA-oriented strategy, it makes a lot of sense to have a key-value store API that fallbacks transparently to whatever storage system is available. It's a great, dev-friendly default.

If you need a specific setup for you app or make queries, nobody prevents you from using your own Storage clone and define whatever fallbacks/drivers you like (e.g. only SQLite, IndexedDB, WebSQL). Come on, it's only 100 lines with comments, from which you would probably have to touch 10.

**Comment by aggarwalankush** [comment]
@FdezRomero That's exactly I did. I copied their storage and modified a little to use SQLite plugin from ionic-native. Any opinions if something is wrong or can be improved would be really useful.

`sql.ts` https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09

**Comment by Luchillo** [comment]
@danbucholtz Say i have an app that uses the beta.11 SqlStorage and delivers the app both as a mobile app but also deploy it as a web app, in mobile it uses SQLite, but in web browser fallback to WebSql, we rely heavily on the transaction methods delivered by both SQLite and WebSql in order to provide Offline support.

Most of that behavior is based on custom tables, tables that hold products, orders, bills and alike, those tables should still work on SQLite but if WebSql is being deprecated where should we look for **Sql** like storage on web browsers? or maybe an abstraction over IndexedDB that allows for transparent use of same api in both mobile or browser?

**Comment by Luchillo** [comment]
I've been looking to [Lovefield](https://google.github.io/lovefield) as abstraction layer on top of IndexedDB to develop Relational Database like queries like `selects`, `joins` and others that make it easier to deal with tabular data (as it is my case since my app uses a lot of tabular data), but that seems to be a problem in mobile since the `low memory triggers IndexedDB deletion issue`, any insights about using that lib with Ionic 2?

**Comment by baffleinc** [comment]
Further to @NickStemerdink's solution, I have had to use the following function to process the results from sqlite (as it doesn't return an array/object on-device). Please correct me if I'm wrong, this is the only way I could get it working. Would love to use map, but there's nothing to map over.

```
return Observable.create(observer => {
      this.store.query('SELECT * FROM bookings')
        .then(results => observer.next(this._getResultsFromTransaction(results));
}
...

_getResultsFromTransaction(results){

    if(window.sqlitePlugin){
      let rows = results.res.rows;
      let items = [];

    	if(rows.length > 0){
    	  for(var i = 0; i < rows.length; i++){
    		  items.push(rows.item(i));
    	  }
        return items;
      } else {
        return [];
      }
    } else {
      console.log('indexeddb', results);
      return _.map(results.res.rows, item => item)
    }
  }
```

**Comment by klochko7** [comment]
**NickStemerdink** , hi! I use your example, i did ionic plugin add cordova-sqlite-storage, but see in browser

_Storage: SQLite plugin not installed, falling back to WebSQL. Make sure to install cordova-sqlite-storage in production!_

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0

How can I solve this ? Help please..

**Comment by NickStemerdink** [comment]
@klochko7, the fallback is meant to be activated when using the browser, so this is correct behaviour and requires no changes.

Just make sure that your app **also** works as expected on a device. That should be the case if the cordova-sqlite-storage plugin is installed.

**Comment by daveshirman** [comment]
@NickStemerdink: Hey, I checked your workaround.  I understand the init process fallback, but I'm failing to see how the query method itself will fallback correctly in the browser?

It clearly goes straight to the SQLite.query method.

For example, if in my app I'm calling my storage service, how is this supposed to work?:

```
this.storageService.getUsers()
```

In my service (chopped for brevity):
```
export class StorageService() {
    // your query method here...

    getUsers() {
        return this.query('SELECT * FROM users').then((data) => {
           // ...
        });
    }

}
```

Obviously I'm missing something fundamental about your approach here.  Thanks.

**Comment by NickStemerdink** [comment]
I guess you are missing the abstraction layer in your example. See gist in this comment https://github.com/driftyco/ionic/issues/8269#issuecomment-250756711 for more information.

That will take care of initializing the correct database. The other methods will just refer to _that_ database.

So after implementing the code from the gist, your code would look like:

```
export class StorageService(sql: Sql) {
    getUsers() {
        return this.sql.query('SELECT * FROM users').then((data) => {
           // ...
        });
    }
}
```

**Comment by klochko7** [comment]
**NickStemerdink**, thanks.

**Comment by daveshirman** [comment]
@NickStemerdink: Thanks, very helpful of you. Good man.

**Comment by iursevla** [comment]
I don't want to create another issue, but at the same time i hope it's not offtopic.
How can we use pre-populated databases now on RC0?

**Comment by baffleinc** [comment]
To build on top of @NickStemerdink's epic work, if anybody needs a batch function you can add it to the sql service like this: 

```
batch(query:string, objects:any[]):Promise<any>{
      return new Promise((resolve, reject) => {
        try{
          let queries:any = _.map(objects, (object) => [query, object]);
          console.log(queries);
          this._db.sqlBatch(queries, function(){
            resolve();
          });
        } catch (err) {
          reject({err:err})
        }
      });
    }
```
Usage: 
```
let objects = _.map(entries, entry => [entry.name, entry.id]);
        this.sql.batch(`insert into table (name, id) values (?,?)`, objects);
```

**Comment by juliandavidmr** [comment]
Its works!!!!!
I use this [ExamplePage](https://gist.github.com/NickStemerdink/64c782807fc31b7bc9b529ad4b1d56d5)

Thanks @NickStemerdink

**Comment by seand88** [comment]
@NickStemerdink 
thanks for the workaround... 

I agree with @mlynch and the ionic team for reasons in taking this out.
What I think would be a good solution is to have an available interface for storage that supports sql like before RC0

Sql is a such a common solution in use as the main storage engine for both ios/android 
Why not implement something like https://github.com/kripken/sql.js where we get sql as javascript in the browser, then on mobile it falls back to native sqlite? 

I think while some apps use key/value stores its definitely not applicable to all applications and I don't think that framework should be that opinionated to not have a good sql option available for both in browser and app testing.

**Comment by jkobylec** [comment]
Agree with @seand88 this would be quite valuable for when we've otherwise coded our apps to be testable in the browser but direct SQLite makes the most sense for the persistence model on the actual device.

There just aren't alternatives with comparable secondary indexing performance that work seamlessly on the browser and the device—it's all on top of SQLite (or flat files that get rewritten wholesale...) in the device anyway, typically implementing interfaces that are really meant for massively parallel computing environments and not a mobile device. (For instance, the PouchDB developers themselves would tell you not to use PouchDB if you're not syncing with a CouchDB backend.)

Naturally the browser performance in this case would not be so critical since we'd be tuning for performance on the device; it seems we mainly just want the ability to functionally test in the browser that we don't get with the "more native" platforms.

Perhaps this could be done as a community effort?

Conversely, could this just be a matter of not being "good enough" at testing/debugging exclusively through emulators/devices? Maybe we just need to see the light and wouldn't miss the ability to test and debug in the browser?

**Comment by seand88** [comment]
@jkobylec   
lets make this a community effort like you said.
I put the interface into one file for simplicity for now and removed the storage engine interface since we know its going to be sqlite.

I placed it in a repo here. 
https://github.com/seand88/ionic2-sql-interface

Havent published an ionic module before but I will be working on integrating sql.js for the browser testing then can publish it as a module.

This should be a drop in replacement of one file for anyone else having issues with this. See the readme in the repo for instructions.

**Comment by jkobylec** [comment]
Thanks @seand88!

One thing I'd definitely want to set up in the build process if going the sql.js route in the future is to only include sql.js for the browser using `ionic serve` and not for device/emulator builds since sql.js is a quite hefty chunk of script (2 MB) that would be relevant only for in-browser testing. Does the new RC0 build model provide a straightforward way to configure something like this?

**Comment by seand88** [comment]
no idea i haven't looked into the build system internals yet.

**Comment by daveshirman** [comment]
@NickStemerdink Hey, quick question: I'm getting random occurrences of the:
 `Storage: Unable to create initial storage tables` error on the actual devices when my app attempts to start from cold (i.e. not in the recent apps menu).

I'm providing the Sql class you gave us in my NgModule, so the whole app has access to it.

Any idea why this might be happening?

Cheers.

**Comment by OmarHassan25** [comment]
Dears, 
I am using the solution of websql on browsers and sqlite on real devices, My problem is the transaction callbacks success and fail, They are reversed on the browser fail called instead of success and vice versa.

Example:
      db.transaction((tx: any) => {
            let vals, sql;
            tx.executeSql(sql, vals, undefined, fail);
          
        },success , fail);
      });

on real devices success is called on success cases and fail is called on failure, but on browser fail is called for success and success is called on failure !!!!!!11

Am i misunderstood something ?
Anyone can help in this ?

**Comment by francesco1992** [comment]
@baffleinc Your solution about batch query works well on mobile devices, not in browser cause WebSQL doesn't support batch queries. I modified the function like this:

```
batch(query:string, objects:any[]): Promise<any> {
    return new Promise((resolve, reject) => {
      try {
        this._db.transaction((tx) => {
          var promises = objects.map((object) => {
            tx.executeSql(query, object);
          });
          Promise.all([promises])
            .then(() => {
              resolve();
            })
            .catch(err => {
              reject({ err: err });
            });
          },
          (err) => reject({ err: err }));
      } catch (err) {
        reject({ err: err });
      }
    });
  }
```

**Comment by baffleinc** [comment]
Hey, that will work but is not true batchSQL. you will notice significant
performance problems with 1000s of records!

I actually have an abstractor that does the above if on desktop, and uses
batchsql on mobile. Thinking of moving to pouchdb though!

**Comment by ryaa** [comment]
Hi,

Why SQLite calls transaction method has only one input param
transaction(fn: any): Promise<any>;

while cordova plugin (https://github.com/litehelpers/Cordova-sqlite-storage) also has success and error callbacks
Sample below
```
  db.transaction(function(tx) {
    tx.executeSql('CREATE TABLE IF NOT EXISTS DemoTable (name, score)');
    tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Alice', 101]);
    tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Betty', 202]);
  }, function(error) {
    console.log('Transaction ERROR: ' + error.message);
  }, function() {
    console.log('Populated database OK');
  });
```

**Comment by Luchillo** [comment]
How did you get `SQLite` without the plugin?

**Comment by ryaa** [comment]
ionic-native has this - see https://ionicframework.com/docs/v2/native/sqlite/

**Comment by anrtero** [comment]
Are You guys really thinking that most of the people using sql database with their apps are glad to implement [this ](https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09) or similar kind of "tune-up" in their code instead of importing Storage and SqlStorage plugin? If You answered no, then I would like to know why didn't You also remove the `ionic serve` command? Because it was pretty useful for many of us to speed up the development. Now it is at least more useless than before this change..

**Comment by aggarwalankush** [comment]
If someone still facing issues using SQL properly in browser and device, I created a minimal demo repo - 

 https://github.com/aggarwalankush/ionic2-sql/tree/master/src/providers

**Above repo handles `platform ready event` requires by SQLite plugin before making any queries.** In this [gist](https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09) I forgot to wait for platform ready event and in device, my app was using WebSQL.

P.S. I'm still using WebSQL because it's not deprecated yet and I don't know what else can I use right now which will work perfectly in browser and device.

**Comment by flyingangel** [comment]
SQLite not work on browser
Storage don't support queries
= fail ionic update, can't really test anything on browser

Question : how do you make typescript accept "window.openDatabase" and "window.sqlitePlugin" because when I compile it keep saying error property is undefined ?

**Comment by anrtero** [comment]
@flyingangel [Here is an example for you](https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09)

**Comment by flyingangel** [comment]
@anrtero Thanks it definitely save my day :)
The fallback really works on browser.

**Comment by aggarwalankush** [comment]
I updated [sql example gist](https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09) to wait for platform ready event. Without it, my production apps were unintentionally using WebSQL because sqlitePlugin is not available before platform ready event.

**Comment by martingra** [comment]
any solution? I want to keep using the query method!

**Comment by seand88** [comment]
@martingra  I placed it in a repo here.
https://github.com/seand88/ionic2-sql-interface

This will work fine for now testing in browser until chrome removes websql.

**Comment by aggarwalankush** [comment]
@seand88 you solutions might suffer race condition. You should wait for platform.ready event before checking win.sqliteplugin liked I did here https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09#file-sql-ts-L15

**Comment by hiranivipul** [comment]
@aggarwalankush Its working fine. Can this code work in native ?

**Comment by aggarwalankush** [comment]
@hiranivipul yes it will use sqlite in physical device and WebSQL in browser.

Just remember to install cordova sqlite plugin with following command- 
```
$ ionic plugin add cordova-sqlite-storage
```

**Comment by ste4net** [comment]
@aggarwalankush  Your example is awesome. 
But doing some tests i see that win.sqlitePlugin is initialized also debugging with Ripple.
