### ISSUE TITLE
Ionic 2.0.0 RC.0: including page specific style sheets

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#8275]
Hi

Previously, I included the page specific style sheets by doing this:

`@import "../pages/settings-page/settings-page.scss";`

in app/core/scss. I'm not quite sure what to do now. My css is not being imported.

Is there something basic I'm missing?

thanks

Tom

**Comment by ramonornela** [comment]
Not need anything, [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts) takes care of that.

Thanks

**Comment by danbucholtz** [comment]
Hi @tomgallagher, @ramonornela is correct. `.scss` files are automatically included.

Thanks,
Dan
