### ISSUE TITLE
Best approach to using npm libs without typings

### ISSUE THREAD

**Issue by morious** [driftyco/ionic#8278]
I am trying to use an npm package that has no corresponding typings file, hence I cannot use an 'import' statement that later most likely participates in the bundling process.

I could not find a documentation to what is the recommended approach by ionic given the new build process in RC0.

The quickest thing I could think of would be to use a 'declare var' statement and an npm task to copy the js file to the www folder.

What approach would you recommend to this?

**Comment by danbucholtz** [comment]
Hi @morious,

Let's track this discussion in the other tread.  I am happy to chat about it.

https://github.com/driftyco/ionic/issues/8274#issuecomment-250359341

Thanks,
Dan
