### ISSUE TITLE
Updated docs for Ionic v2

### ISSUE THREAD

**Issue by astutya** [driftyco/ionic#8282]
I was wondering if there are docs with updated components and changes in Ionic 2 RC0 already available somewhere. I couldn't find them on Ionic's Official website.

**Comment by fiznool** [comment]
@astutya Check out the [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc0-2016-09-28)

**Comment by astutya** [comment]
http://ionicframework.com/docs/v2/api/ already has the updated docs..
