### ISSUE TITLE
ionic view

### ISSUE THREAD

**Issue by jamalsleman** [driftyco/ionic#8284]
The new ionicview Application is too bad on Iphone
when i open my application, screen become disable and i can see notificationthat i can swap 3 fingers up or down to go back or send feedback.

This is very bad, sceen stay disable more than 1 minute and i cannot remove this notification, even if i preess more than 100 time on the screen it still disabled.

please just remove this notification.

kind regards

**Comment by rcjsuen** [comment]
If you access the settings in the upper right hand corner of Ionic View, you can tell Ionic View to not show the swipe info when starting up an application. Does that help?

**Comment by jamalsleman** [comment]
Thanks
but it is not good, i ask some one to check me application he become crazy becouse this.
it not good idea to start tell every one this thing.

you need but this information on help tab of the main application.
why & why & why & why need to see this notification every time.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Since this issue seems to be about Ionic View and not the framework I am going to be closing this issue for now and ask that you open an issue on the Ionic View repo. Thanks for using Ionic!
