### ISSUE TITLE
[V2 RC0] ion-content blinks

### ISSUE THREAD

**Issue by ekhmoi** [driftyco/ionic#8285]
#### Short description of the problem:

If Ion-content has image(s), it is being redrawn(blinks) when AlertController / PopoverController(or another component) opens.

#### What behavior are you expecting?

Smoothly opening components without blinking.

**Steps to reproduce:**
1. create starter v2 app
2. add some cards with images to home page
3. add button which will open AlertController
4. emulate or run in real device. Browser works fine
5. click on button

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

[Video](https://youtu.be/SJF9UIjL0Bo) - with images (with bug) you see the page blinks every time popover or prompt is going to appear

[Video](https://youtu.be/UyzGhhacHU8) - with ion-list (no bug)

**Which Ionic Version?** 1.x or 2.x
ionic 2.0

#### Repo that shows an example of your issue

[https://github.com/ekhmoi/ion-demo](https://github.com/ekhmoi/ion-demo)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1                                                                                                                                                         
Gulp version:  CLI version 3.9.1                                                                                                                                           
Gulp local:                                                                                                                                                                
Ionic Framework Version: 2.0.0-rc.0                                                                                                                                        
Ionic CLI Version: 2.1.0                                                                                                                                                   
Ionic App Lib Version: 2.1.0-beta.1                                                                                                                                        
ios-deploy version: 1.8.6                                                                                                                                                  
ios-sim version: 5.0.8                                                                                                                                                     
OS: Mac OS X El Capitan                                                                                                                                                    
Node Version: v4.4.3                                                                                                                                                       
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jwenzler** [comment]
This is also happening on numerous pages of my app.  Was the same reason for my comment on https://github.com/driftyco/ionic/issues/8050

**Comment by msalcala11** [comment]
Happens for me as well for ActionSheetController, but only on iOS devices/emulators (not on android devices or desktop broswers). I'm on RC0

**Comment by soniaCejas** [comment]
I have the same problem too. In the IOS devices and emulator.

**Comment by ekhmoi** [comment]
These blink are killing me and the whole native feel of the application :) Hope it'll be fixed in next RC

**Comment by izaaz** [comment]
I had the same problem. What I noticed that in some of my pages opening the same popover didnt have the blink issue but my home screen had the blink issue. After a lot of debugging, i figured that the only difference between the two pages was that the other page (without the blink issue) had the following css rule

    .scroll-content {
        overflow-y: hidden;
    }

When I added this to my home page as well, I didnt see the blink issue anymore. Luckily none of my pages really needed scrolling. Hope this helps till the issue is solved :)

**Comment by gxsjtu** [comment]
same problem on RC1, please fix it asap

**Comment by manucorporat** [comment]
Use this workaround:
```
IonicModule.forRoot(MyApp,  {
  canDisableScroll: false
});
```

**Comment by ekhmoi** [comment]
Thanks a lot ! :)

**Comment by gxsjtu** [comment]
works perfectly


发自我的 iPhone

在 2016年10月19日，下午7:20，Manu Mtz.-Almeida <notifications@github.com<mailto:notifications@github.com>> 写道：


Use this workaround:

IonicModule.forRoot(MyApp,  {
  canDisableScroll: false
});


―

**Comment by manucorporat** [comment]
This PR will fix this issue: https://github.com/driftyco/ionic/pull/8807

**Comment by soniaCejas** [comment]
Thanks, it works!
