### ISSUE TITLE
ionic start --v2 myApp failed

### ISSUE THREAD

**Issue by tunxiaoqing** [driftyco/ionic#8286]
I have installed ionic 2.0.0-rc.0 .but when I create a new Ionic 2 RC0 app,nothing happened,I checked my version,it  shows 2.1.0 
![9 rzn e_s1y x4zf e7w](https://cloud.githubusercontent.com/assets/16894961/18949123/849b3dd6-866c-11e6-9a1d-1a3ff72df467.png)

**Comment by dayaki** [comment]
You need to start the folder ionic should install into. Try `ionic start folderName --v2` or `ionic start folderName templateType --v2`

TemplateType could be tabs, sidemenu

**Comment by morious** [comment]
@tunxiaoqing ,
Try the following:

Remove ionic
```
npm uninstall -g ionic
```

Validate that you have the latest npm >= 3.0
```
npm install npm -g
...
npm -v
```

Install ionic again
```
npm i ionic -g
```

**Comment by tunxiaoqing** [comment]
I reinstall ioinc and ti works ,thank you for your answers~O(∩_∩)O~
