### ISSUE TITLE
Cannot find module '@angular/core'

### ISSUE THREAD

**Issue by akaamitgupta** [driftyco/ionic#8287]
Hello, 

I recently created a new project with ionic-2 with `ionic start MyIonic2Project --v2`. For some reason, I am getting this error (image below)
![screen shot 2016-09-29 at 3 49 58 pm](https://cloud.githubusercontent.com/assets/7375462/18950320/eb2eb038-865c-11e6-8f1c-55d8d2e0a059.png)

The versions installed on my computer are
 - ionic -v -> 2.1.0
 - node -v -> v4.6.0
 - npm -v -> 2.15.9

What can be the issue? How should I go about resolving this?

Thanks,

**Comment by ekhmoi** [comment]
the problem is in node version.
i had the same problem and fixed it by: uninstalling the node and installing the latest 6.7.0 version

**Comment by martin-g** [comment]
The problem is in NPM version.
The RC0 changelog says that version 3.x is required now.
There are several issues like this in the past day. Next time you could check the latest open/closed issues for similar problem before reporting.

**Comment by ekhmoi** [comment]
@martin-g , updating only npm didnt fix issue for me. I had to update the node.js

**Comment by martin-g** [comment]
In that case Ionic devs should update the requirements to say that Node 4.x is not supported too.
But in one of the other issues they said that Node 4.x (the LTS version) is supported.

**Comment by akaamitgupta** [comment]
thxx @ekhmoi it solved my problem...
