### ISSUE TITLE
Ionic 2 downgrade

### ISSUE THREAD

**Issue by vinnchan** [driftyco/ionic#8288]
Possible to downgrade back to previous version for example 2.0.0-beta.11. The Storage  from '@ionic/storage' I can't use .query method anymore. I need to present my project

**Comment by ramonornela** [comment]
Related #8289

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can backtrack the steps in the change log. We are currently planning on implementing query asap. Sorry for any hassle this causes.
