### ISSUE TITLE
<ion-title> does not render "toolbar-title" when [innerHTML] is specified

### ISSUE THREAD

**Issue by Diodeus** [driftyco/ionic#8295]
Typical behaviour (Beta 11):

` <ion-title>{{ mytitle }}</ion-title>`

will output:

` <ion-title><div class="toolbar-title">My Ttile</div></ion-title>`

But when using:

` <ion-title [innerHtml]="myTitle"></ion-title>`

The inner DIV "toolbar-title" is not rendered.

Workaround:

` <ion-title><div class="toolbar-title" [innerHtml]="myTitle"></div></ion-title>`

This ends up generating:

`<ion-title><div class="toolbar-title"><div class="toolbar-title">My Title</div></div></ion-title>`

**Comment by ekhmoi** [comment]
I guess that is exactly what should happen. 
what is your expectation ?

**Comment by Diodeus** [comment]
I would expect it to output this:

`<ion-title><div class="toolbar-title">My Ttile</div></ion-title>`

Or to simply leave it alone and allow be to do this:

` <ion-title align-title="left"><div class="toolbar-title" [innerHtml]="myTitle"></div></ion-title>`

But when I do that, I get two nested "toobar-title" DIVs.

**Comment by ekhmoi** [comment]
I dont think that is correct to expect that behaviour:)

{{ mytitle }} is string Interpolation, which outputs text
[innerHtml] is property binding, you bind its innerHtml to whatever is inside quotes
so when you do 
<ion-title [innerHtml]="myTitle"></ion-title>
ionic creates
<ion-title><div class="toolbar-title"></div></ion-title>
and then does something like this 
$('ion-title').html('My Ttile');
or
document.getElementsByTagName('ion-title')[0].innerHTML = 'My Ttile';
<ion-title>{{ mytitle }}</ion-title>
that is why the result became 
<ion-title>My Ttile</ion-title>

IMHO- that is perfectly correct behaviour

**Comment by manucorporat** [comment]
@Diodeus exactly, @ekhmoi you are right.

This is the expected behavior, avoid using innerHTML. what are you trying to do?

**Comment by Diodeus** [comment]
I am trying to set my own title which includes HTML entities, such as `&#38;`, which is why I need to specify innerHTML.

**Comment by ekhmoi** [comment]
Hello again.
you can do it like this

<ion-title><span [innerHtml]="myTitle"></span></ion-title>

**Comment by shprink** [comment]
I have the same problem.

![image](https://cloud.githubusercontent.com/assets/1388706/21828202/7ad13908-d78f-11e6-9bb3-5d54bc8995f0.png)

```
<ion-header>
  <page-navbar [title]="(stream$ | async).title.rendered">
  </page-navbar>
</ion-header>
```

the equivalent in Ionic1 was:

```
<ion-nav-title ng-bind-html="::postCtrl.item.title.rendered"></ion-nav-title>
```

ans it worked.

None of the solution listed in this thread worked. Please re-open ;)
