### ISSUE TITLE
Private to Public TypeScript keyoword

### ISSUE THREAD

**Issue by vbudilov** [driftyco/ionic#8299]
Per the RC.0 Changelog:

> Change any uses of the private TypeScript keyword to public.

Is there a reason for this? What prompted this change? 

Thanks,
Vladimir

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is because of the Angular AoT compiler. If you set a method or variable as private and try to use it in your template it will throw an error. Sorry for any hassle this causes!

**Comment by maxkunitsa** [comment]
@vbudilov AoT cant access private properties, details:
https://forum.ionicframework.com/t/rc0-typescript-private-vs-public-keyword/64863/4?u=olmerius

**Comment by vbudilov** [comment]
Thanks!

**Comment by Manduro** [comment]
@jgw96 So `Change any uses of the private TypeScript keyword to public.` should be something like `Make sure any Component properties that you use in your template are set to public.`

**Comment by royipressburger** [comment]
Is it have to be explicit? If there is no public/private prefix it will work?
