### ISSUE TITLE
RC.0 Upgrade Docs error?

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic#8300]
The upgrade docs say that you need to remove imports of your services (injectables) from your Components (point 9 in the docs) but I don't think you should - I think they have to be imported there too don't they ?

**Comment by jgw96** [comment]
Ahh yep, you are correct. They still have to be imported and injected in the constructor of your component, but they should not be in a providers array on that component. Fixing

**Comment by jgw96** [comment]
fixed with https://github.com/driftyco/ionic/commit/3671f3023bdf2a23d624076d5ddc343d6bc244a0

**Comment by numerized** [comment]
cool !

**Comment by joshgarwood** [comment]
Hey @jgw96 !  What about Pipes and Directives, should those also be removed in Component declarations?

**Comment by stchoukeu** [comment]
Ok let me untherstand, The import is necessary for all of them.
May be that @richardshergold was saying that   services (injectables)  have also to be put in the providers array because i remark that in ionic 2.1.13, providers keyword is recognised as a Component property.
