### ISSUE TITLE
How to load/use ionic directives, if component is declared in a module

### ISSUE THREAD

**Issue by aavelyn** [driftyco/ionic#8302]
#### Short description of the problem:
I'm using rc0 tabs starter project and I want to have a auth folder with login and signup page inside the src folder (same level as pages).

here's the auth module

```
@NgModule({
	imports:[
		FormsModule,
		HttpModule
	]
	declarations:[
                LoginPage
	]
})
```

I import the the module in app.module.ts under imports and get 

Unhandled Promise rejection: Template parse errors:
'ion-title' is not a known element...

Do I need to import the directives from ionic inside auth module?

#### What behavior are you expecting?

expecting ionic directive to work globally.

**Which Ionic Version?** ionic 2 rc.0

**Comment by ekhmoi** [comment]
try to add your LoginPage into

entryComponents

so your example should look like this:

```
@NgModule({
    imports:[
        FormsModule,
        HttpModule
    ]
    declarations:[
                LoginPage
    ],
   entryComponents: [
                LoginPage
   ]
})
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a repo I can use to reproduce this issue?

**Comment by aavelyn** [comment]
@jgw96 here's the repo [Github](https://github.com/aavelyn/ionicloaddirectives)

@ekhmoi adding LoginPage to entryComponents doesn't work either. entryComponents isn't a 'native' property of ngModule from angular isn't it?

**Comment by bkapo** [comment]
Hello,
I have the same problem.
Are feature componets supported ?

**Comment by SudharsanSukumar** [comment]
Hey I figured out how to import feature modules correctly to avoid that error. [Here's the forum post](https://forum.ionicframework.com/t/rc-0-how-do-you-import-export-modules-into-your-app/65168/10?u=sudharsan_sukumar).

Hope that helps,
Dharsan

**Comment by aavelyn** [comment]
Hi Dharsan, Thanks!!! 

it solves the issue and I agree with the posts over there, that it should be added to the docs immediately. Otherwise, people might start declaring everything inside app.module ignoring ngModules and the many benefits it's gonna bring (hopefully soon also to ionic 2)

For all other readers, you need to use IonicModule.forRoot() method to 'provide' ionic directives to your components:

`@NgModule({
  imports:[ IonicModule.forRoot(ComponentNeedingIonicDirectives) ],
  declarations: [ ComponentNeedingIonicDirectives ]
})`

**Comment by mcherb** [comment]
Juste add IonicModule to the imports. No need to call forRoot for the directive.

**Comment by JoeriShoeby** [comment]
@mcherb You saved my day after 5 hours of struggling. In the end it's quiet obvious though ..
