### ISSUE TITLE
[V2 RC.0] Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by bm-software** [driftyco/ionic#8304]
I've just ugraded my project to the new Ionic version (RC.0) and if I try to run it either with _serve_ or _run android_ command my app doesn't start throwing this exception:

`Cannot read property 'select' of undefined, http://192.168.0.123:8100/build/main.js, Line: 16`

Any solution?

**Comment by manucorporat** [comment]
@bm-software can you provide additional info?
some code or a plunker that reproduces the issue and the full call stack

**Comment by bm-software** [comment]
The full stack is the one I posted in the first comment. No other errors are shown.

I'll try to do a plunker to reproduce the problem because my app is quite big.
I'll post it here as soon as possible.

**Comment by okonon** [comment]
@manucorporat please see https://github.com/driftyco/ionic/issues/8304 for more info you can close one of these as dupe.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I am going to be closing this one as a duplicate of #8294 . Thanks for using Ionic!
