### ISSUE TITLE
docs: Outdated info in documentation

### ISSUE THREAD

**Issue by jgrantr** [driftyco/ionic#8306]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm not sure what version of Ionic this applies to, but I've put the URL below.

The information on this page:

http://ionicframework.com/docs/guide/testing.html

is outdated.  Under the section "Testing as a native app", it incorrectly states that it costs $99 per year to test an iOS app on a device.  It has been free to test on a device since at least June 2015.  Probably best not to leave information that is over a year out of date in the docs.  Certain things still require a paid membership, but basic testing on a device is not one of them.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Thanks for the heads up.
PR's are always welcomed.

Closing this though as this is not an issue with ionic, but rather should be made in https://github.com/driftyco/ionic-site

**Comment by jgrantr** [comment]
I opened an issue over there.  Thanks!
