### ISSUE TITLE
ionViewLoaded vs ionViewDidEnter (component stays 'hidden')

### ISSUE THREAD

**Issue by vbudilov** [driftyco/ionic#8313]
#### Short description of the problem:
Whenever  nav.setRoot  is called in ionViewDidEnter, the new component is loaded into the DOM but is tagged as **hidden**. The same command works without a glitch whenever it's called from within ionViewLoaded

Is there a reason for this? 

Which Ionic Version? 1.x or 2.x
v2 RC.0

Run ionic info from terminal/cmd prompt: (paste output below)
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS 
Node Version: v6.7.0

npm -v
3.10.8
node -v
v6.7.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting a repo that i can use to reproduce this issue? Thanks!

**Comment by vbudilov** [comment]
I'll have to isolate this code into a separate project..let me do that first.

**Comment by manucorporat** [comment]
@jgw96 I have suspicions that this commit fixed this issue as well: https://github.com/driftyco/ionic/commit/9b650229f77b16db912e67ef36f9abd765753bc8

**Comment by manucorporat** [comment]
This was already fix in RC1
