### ISSUE TITLE
Ionic 2 -RC.0 : tabBadgeStyle in <ion-tab> not working

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#8317]
Hello,
Here is my code
```
<ion-tab [show]="noMessages" [root]="tab4Root"  [tabTitle]="dataService.appLabels.inbox || 'Inbox'" tabBadge="&#8595;" tabBadgeStyle="danger" tabIcon="mail"></ion-tab>
```

Eventthough tabBadgeStyle is danger, it give me primary color in view

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind changing `tabBadgeStyle` to `color` and trying again?

**Comment by Manduro** [comment]
@jgw96 As can be seen [here](https://github.com/driftyco/ionic/blob/83d973b1a83e3681b0be5c2f58acc9cc98a9c844/src/components/tabs/tabs.ts#L148) a class is added based on the `tabBadgeStyle` input. That class is nowhere to be found in the styles though. It has probably been forgotten in the big change to the color attribute.

**Comment by bimal72** [comment]
Hello @jgw96 I tried with color and not working.

Btw, @Manduro is right, as per source

https://github.com/driftyco/ionic/blob/83d973b1a83e3681b0be5c2f58acc9cc98a9c844/src/components/tabs/tabs.ts#L148

it adds badge-danger in final html..
```
<ion-badge class="tab-badge badge-ios badge-danger" ng-reflect-klass="tab-badge" ng-reflect-ng-class="badge-danger"
```
but it seems that badge-danger class is missing

**Comment by bimal72** [comment]
@jgw96 @Manduro 

As of now I use following work around .. in app/app.scss , where I do have other css, I have added 

```
.tab-badge.badge-danger{
    background-color: color($colors, danger) !important;
}

.tab-badge.badge-secondary{
    background-color: color($colors, secondary) !important;
}
```
and working fine for me

**Comment by infinnie** [comment]
Also the `color` attribute no longer works on badges since RC 0. See http://ionicframework.com/docs/v2/components/#badges

**Comment by brandyscarney** [comment]
@infinnie Badge is working fine for me using the color attribute, see: https://github.com/driftyco/ionic/blob/master/src/components/badge/test/basic/main.html

The demo you linked to doesn't use colors :)
https://github.com/driftyco/ionic-preview-app/blob/master/src/pages/badges/basic/template.html

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in rc.1 thanks to this PR: https://github.com/driftyco/ionic/pull/8399

**Comment by abhayastudios** [comment]
To try it out I updated the relevant files in node_modules/ionic-angular directory and I can see that www/build/main.js now seems to contain the fix as committed through the PR as follows:

```<ion-badge *ng
If="t.tabBadge" class="tab-badge" [color]="t.tabBadgeStyle">{{t.tabBadge}}</ion-badge>```

However it I still don't see the desired changed reflected in my app. An example of a tab definition from my tabs.ts:

```
<ion-tab [root]="tab3Root" [rootParams]="availabilityParams" tabTitle="Availability" tabIcon="alarm" tabBadge="{{availabilityCount}}" tabBadgeStyle="danger"></ion-tab>
```

What am I missing?

**Comment by brandyscarney** [comment]
@abhayastudios I am seeing it working using the latest nightly in the conference app. Could you try that? 

```
npm install --save ionic-angular@nightly
```

**Comment by abhayastudios** [comment]
@brandyscarney thanks it is working. I'm guessing something did not work right with my initial installation of RC0? While updating to the nightly I got lots of npm errors:

```
npm ERR! peer dep missing: @angular/common@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/compiler@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/compiler-cli@^0.6.2, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/forms@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/http@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/platform-browser@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/platform-browser-dynamic@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: @angular/platform-server@^2.0.0, required by ionic-angular@2.0.0-rc.0-201610121605
npm ERR! peer dep missing: zone.js@^0.6.21, required by ionic-angular@2.0.0-rc.0-201610121605
```

Anyway it is working now so thanks :)

**Comment by brandyscarney** [comment]
@abhayastudios I believe we made some changes to the dependencies recently, make sure to compare your dependencies against `app-base` to ensure you have at least these: https://github.com/driftyco/ionic2-app-base/blob/master/package.json#L16-L30

Glad it's working! :)
