### ISSUE TITLE
ngc error when using ngrx store in rc.0

### ISSUE THREAD

**Issue by CooleyGit** [driftyco/ionic#8318]
I am trying to upgrade my app from beta 11 to rc.0. But before I moved everything over I wanted to make sure I could get ngrx store to run in the new NgModuel everything seem to work fine in browser but as soon as I ran ionic emulate ios I get the below error. I have tried everything and cant get it to build for ios any help would be great thanks.

ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 6:53 in the original .ts file), resolving symbol employees in ../store/employee.store.ts, resolving symbol AppModule in ../ngrxTest/.tmp/app/app.module.ts, resolving symbol AppModule in ../ngrxTest/.tmp/app/app.module.ts

**Reducer** 
```
import { ActionReducer, Action } from '@ngrx/store';
export const LOAD_EMPLOYEES = "LOAD_EMPLOYEES";

export const employees: ActionReducer<Array<any>> = (state: Array<any> = [], action: Action) => {
    switch(action.type) {
        case LOAD_EMPLOYEES:
            return action.payload;

        default:
            return state;
    }
};
```

**app.module**
```
...
import { Store, StoreModule } from '@ngrx/store';
import { employees } from '../store/employee.store';

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    StoreModule.provideStore( { employees: employees }, { employees: [] } ),
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: []
})

```

**Comment by danbucholtz** [comment]
@CooleyGit,

Can you do me a favor and look in `node_modules/@ngrx/store` and look for `.metadata.json` files corresponding to the `StoreModule`? Please let me know what you find.

Thanks,
Dan

**Comment by Manduro** [comment]
This is a support question for ngrx/store rather than an issue for Ionic ;). The latest ngrx/store is definitely compatible with Ionic RC.0.

It should work if you adjust your reducer to be a function rather than a constant. Change
```ts
export const employees: ActionReducer<Array<any>> = (state: Array<any> = [], action: Action) => {
```
to
```ts
export function employees(state: Array<any> = [], action: Action): Array<any> {
```

**Comment by CooleyGit** [comment]
Yes there is an index.metadata.json here is whats in there.

{"__symbolic":"module","version":1,"metadata":{},"exports":[{"from":"./src/dispatcher"},{"from":"./src/ng2"},{"from":"./src/reducer"},{"from":"./src/state"},{"from":"./src/store"},{"from":"./src/utils"}]}

**Comment by danbucholtz** [comment]
Thanks @CooleyGit.  It looks like it has been compiled through `ngc` then.  Can you try @Manduro's steps? I'll reopen if needed.

Thanks @Manduro for your help.

Thanks,
Dan

**Comment by CooleyGit** [comment]
That seemed to do the trick thanks for the quick response.

**Comment by Manduro** [comment]
@CooleyGit You're welcome. You can have a look here https://github.com/ngrx/example-app/tree/final for an example implementation of everything ngrx has to offer.
