### ISSUE TITLE
 2.0.0RC: White page when you push-pop pages too quickly.

### ISSUE THREAD

**Issue by imcosta** [driftyco/ionic#8319]
**Short description of the problem**: If you have pages, for example (Page1 -> Page2 -> Page3) and you push a page an then pop quickly before the transition end using the navbar back button or other element occasionally occurs a white page.

I some cases I can avoid this issue using a flag variable that prevents multiples calls to nav.pop() but is not a very good solution.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind providing a repo that I can use to reproduce this issue?

**Comment by imcosta** [comment]
I used the default tabs template and this.app.getRootNav().push(Page) / this.app.getRootNav().pop(). 
You can try with this: **https://github.com/imcosta/ionicbug.git**

Press "Push" and "Pop" quickly and repeatedly to see the issue.



-

**Comment by n00b42** [comment]
Do I have to wait for the next release or how can I apply this patch myself?

**Comment by FilipSuk** [comment]
@manucorporat Thanks for the fix, however I found another occurrence.
3 tabs -> open some page from 1st tab -> tap quickly 2 times on 1st tab icon -> white screen bug. Here is a clean repo: https://github.com/cernym43/ionic2-whiteScreen
Screencast: http://recordit.co/F6RKhju0Ul

My system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.8.1
Xcode version: Xcode 8.0 Build version 8A218a
