### ISSUE TITLE
has-header on <ion-content> being ignored

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic#832]
I have `has-header` set on my `ion-content` directive but since an update to the latest nightly, this setting seems to be ignored rendering the contents of ion-content behind the header bar.

See screenshots:

![screen shot 2014-03-18 at 23 50 31](https://f.cloud.github.com/assets/220637/2456497/0b568bfa-af1a-11e3-9760-45ab362725b9.png)

I'm using the nightly ionic and viewing the app (for testing) in Chrome.

**Comment by matheo** [comment]
I just got an issue with this:

When I navigate my /app and I get to #/app/list, it's displayed Ok with the ion-content `.has-header` class added automagically. But if I open the list directly from the browser or as startpoint, the class is not added and the header hidden behind the title.

Maybe consistency here is needed to avoid unexpected behavior?
If the class is supposed to be added automatically, then trigger that always
