### ISSUE TITLE
RC-0: Name pattern of generated pages

### ISSUE THREAD

**Issue by ecureuill** [driftyco/ionic#8320]
#### Short description of the problem:
Ionic CLI **generate page** command doesn't add 'Page' sufix to the class name 

#### What behavior are you expecting?
When generating new page through ionic cli,  the class name of the .ts file generated should contains **Page** at the end of the name  

```
@Component({
  templateUrl: 'build/pages/home/home.html',
})
export class HomePage {}

```
**Steps to reproduce:**
1. ionic start myApp --v2
2. ionic build
3. ionic g page myPage

```
@Component({
  templateUrl: 'build/pages/home/home.html',
})
export class Home {}

```
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
Like in ionic beta, set "Page" to the ClassName variable

```
function PageGenerator(options) {
  Generator.call(this, options);
  this.directory = 'pages';
  this.jsClassName += 'Page';
}

```

**Which Ionic Version?** 1.x or 2.x
2 RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.6 (jessie) 
Node Version: v4.5.0

**Comment by ramonornela** [comment]
Not see problem **Uninstall Ionic CLI first, and then reinstall**
> Important: if you have installed the beta cli you should run npm uninstall -g ionic first. You need version 2.1.0 for this release. Check your cli version by running ionic -v in the command line.

Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1442

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I can reproduce with Ionic cli 2.1.0 and have moved this issue to the appropriate repo.

**Comment by ramonornela** [comment]
@jgw96 when you are some time and be able to review the pull #8368 

Thanks
