### ISSUE TITLE
ionic serve no longer working after rc update

### ISSUE THREAD

**Issue by fuggfuggfugg** [driftyco/ionic#8321]
#### Short description of the problem:
Trying to run `ionic serve` on an older project (v2 beta) isn't updating the build folder. 

#### What behavior are you expecting?
I tried updating a label on the login page and run `ionic serve` and it still shows the old login page. If I empty the contents of www/build folder and try again. I get the white screen of death.

**Steps to reproduce:**
1. Update ionic and npm 
2. Use an older project 
3. ionic serve

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
2.1.0

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1435

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have moved this issue to the cli repo since it is an issue with the cli and not the framework. Thanks!
