### ISSUE TITLE
Adding custom tasks to ionic 2 npm based build

### ISSUE THREAD

**Issue by morious** [driftyco/ionic#8326]
Hi,
I need to run a custom script after ionic serve command.
I use the following configuration in package.json:
```
"watch": "ionic-app-scripts watch && npm run copy-libs"
```

for some reason it does not work and the watch task stop any other script from running afterwards.

Any idea how to resolve this?

**Comment by ramonornela** [comment]
```
"serve:after": "myscript"
```

Thanks

**Comment by morious** [comment]
Thanks! makes sense :)

**Comment by morious** [comment]
Reopning this issue,
The above is working well for:
ionic serve

but not working well for ionic run platformName.

When running a particular platform...in my example I am running:
```
ionic run windows
```
the run:after task is occuring after the deployment of the app to the particular platform.

Any suggestion how to hook into the build tasks at a lower level?

**Comment by morious** [comment]
It seems that the approach is described here:
https://www.npmjs.com/package/@ionic/app-scripts

Testing...

**Comment by morious** [comment]
Yes the above approach works. closing again :)

**Comment by AlGantori** [comment]
I tried adding the following, in order to beep at the end of serve/livereloads but I don't think it's getting it :)
```
, "serve:after": "node echo -en '\\a'"
```

I see the following
```
Running 'serve:after' npm script before serve

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AXM\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "node echo -en '\\a'"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.5

npm ERR! missing script: node echo -en '\a'
```

Thank you.

**Comment by AlGantori** [comment]
OK the following hack is working at the end of "ionic serve" but not when livereload takes place (ie after source changes and build run)
```
    ,  "serve:after": "beep"
    , "beep": "bash.exe beep.sh"
```

I put the 
echo -en '\\a'"
into 
beep.sh because I did not figure out how to feed it properly to bash.exe

Thanks.
