### ISSUE TITLE
White screen: Use of const in strict mode. 

### ISSUE THREAD

**Issue by mariohmol** [driftyco/ionic#8328]
Hi,

i can deploy to a real device and to a emulator using android 4.1.1, 4.2.2, 4.4.2.

But it always shows a white screen and in the console i can see the error `Uncaught SyntaxError Use of const in strict mode.`

The project is https://github.com/mariohmol/brigadistas and my system info is:

```
Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1

Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! While i cannot reproduce this issue on Android 4.4.2 you are going to see this and more issues on versions of android older than 4.4.2 unless you use crosswalk. Because of the lack of html5 and es6 support in version of Android older than 4.4.2 we recommend using Crosswalk if you plan on supporting those older version of Android. You can check out our [docs](http://ionicframework.com/docs/cli/browsers.html) for more info on Crosswalk. Thanks for using Ionic!

**Comment by mariohmol** [comment]
I've seen other posts saying that crosswalk was not fixing that. As we have webpack in the gulp build, doesnt it has a transpile for older js versions?

**Comment by mariohmol** [comment]
When i install crosswalk i receive back the message 

`After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.   So the minSdkVersion of Cordova project is configured to 16 by default.`

Is this working for 4.x android versions?

And this docs links you sent me is not updated, i cant run  `ionic browser` because i receive back  `browser is not a valid task`.

We are talking about ionic2 , right? Seems to have same comments here: https://github.com/driftyco/ionic-cli/issues/1100

**Comment by mariohmol** [comment]
Here is saying about the ionic browser used in the docs is deprecated , https://forum.ionicframework.com/t/how-to-use-crosswalk-only-for-android/51065/2 ..

**Comment by mariohmol** [comment]
I dont get why i can make a ionic1 work in 4.1.1 but not ionic2 as we have webpack to transform to do not use ecma6

**Comment by mariohmol** [comment]
Could make that work!! =)

For those who get here:

* ionic platform add browser
* ionic build browser
* ionic plugin add cordova-plugin-crosswalk-webview
* Remove the old app from the device
* ionic build
* ionic run android

**Comment by codesxt** [comment]
Remember to clean your build before running in android after adding crosswalk. It didn't work for me until I ran "cordova clean" before building again.
