### ISSUE TITLE
exception on ionic start --v2 myApp cmd even though both npm and ionic cli are updated to lates ones 

### ISSUE THREAD

**Issue by PrithiviRajG** [driftyco/ionic#8336]
Hi Team, I am getting the below exception when I try to create a new project with ionic CLI

D:\prithivi>ionic start --v2 myApp
Creating Ionic app in folder D:\prithivi\myApp based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by comfortme** [comment]
same issue here.

**Comment by infinnie** [comment]
After downloading, enter the app directory, open command prompt, then run `npm install`.

**Comment by sicontis** [comment]
I was having that problem too, but found updating to latest Node(6.7.0) and NPM(3.10.7) fixed the issue.

**Comment by zorgster** [comment]
Run - npm version .. there was a breaking update a couple of days ago...  If you have the latest ionic cli then you need npm 3 ...  to fix that I installed the latest node installer... (6.7?)  See here:

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by comfortme** [comment]
updated node to 6.7 and npm to 3.10 still get this after npm install
```
node v6.7.0
npm  v3.10.8
code ENOGIT

not found: git

Failed using git.
```
is git requiered?

**Comment by PrithiviRajG** [comment]
I am getting the same exception after update also.

If I run npm install inside the app directory, I am getting the same exception of @comfortme 

not found: git

**Comment by PrithiviRajG** [comment]
After removing "@ionic/storage": "^1.0.3" from package.json, npm install is working and the application is running.

When I add "@ionic/storage": "^1.0.3" in package.json it's throwing the attached exception.

try this @comfortme 

[npm-debug.txt](https://github.com/driftyco/ionic/files/502816/npm-debug.txt)

**Comment by comfortme** [comment]
@PrithiviRajG 
i installed git and everything worked out perfectly. 
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

didn't know git was needed.

**Comment by jgw96** [comment]
Hello all! Git is needed and is an essential part of most development toolchains. Thanks for using Ionic!

**Comment by comfortme** [comment]
it may so but it's better to mention it in the docs and update to rc0 guide. it wasnt needed in previous versions.
