### ISSUE TITLE
don't show the ionic2 Hello Ionic page

### ISSUE THREAD

**Issue by tunxiaoqing** [driftyco/ionic#8339]
I installed ionic2 rc0 and created a new App . it run and opened the Browser. But it's not show the Hello Ionic page, The browser display nothing..can you tell me if I installed fail or the ionic2 rc0 don't show the welcome page wen I run it
![t7hm kh3_8 mi1l8uy g7bb](https://cloud.githubusercontent.com/assets/16894961/18983884/fdda0b22-8721-11e6-8f03-300816a457b2.png)
![8 8qb xdlpk n_ e4vddqn](https://cloud.githubusercontent.com/assets/16894961/18983900/105c55c0-8722-11e6-93fc-ca351a2b2bcb.png)

**Comment by infinnie** [comment]
The exact problem I’ve just run into.

**Comment by zorgster** [comment]
It says "build dev failed" on your image...

Look here...  you may need to upgrade npm to v.3 by installing node 6.7

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Most likely this is due to you either running npm 2 (we require npm 3 now) or running an old version of the cli. Also, make sure you follow our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) when updating your app. Thanks for using Ionic!

**Comment by tunxiaoqing** [comment]
Sorry to recover so late.I have check my npm version and ionic2 version . It is indeed the latest version.So hat else can make this kind of mistake？Thanks for your kind attention and look forward your prompt reply
![image](https://cloud.githubusercontent.com/assets/16894961/19217124/d4b0c4e2-8e07-11e6-92fd-6d5793c21dfb.png)
