### ISSUE TITLE
Updating AngularFire/Firebase project to new RC - @types issue

### ISSUE THREAD

**Issue by sicontis** [driftyco/ionic#8343]
Since the new RC uses **@types** now to install typings, I added the types from Firebase and Angularfire to my project using

`npm install @types/firebase --save-dev --save-exact`

It saves the types to a folder inside `node_modules/@types/firebase` and updates the **package.json** file.

Upon running the project with ionic serve, I get a whole bunch of `error TS2503: Cannot find namespace 'firebase'.` errors, which was fixable in the previous release with a `"files": [ "firebase" ]` addition to the **tsconfig.json** file and then running the `typings install` command. 

Just wondering is there a fix for something similar or an extra step after the npm install?  
Do the types for AngularFire/Firebase need to be updated to match the new RC? 

Any ideas?

**Comment by tja4472** [comment]
Hi
See https://github.com/tja4472/ionic-angularfire

hth

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#53

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have moved this issue to the app-scripts repo since it is related to the build process and not the framework. Thanks for using Ionic!

**Comment by sicontis** [comment]
Awesome guys, my project works perfectly now. Thanks heaps.
