### ISSUE TITLE
ORIGINAL EXCEPTION: Cannot read property 'swipeBackEnabled' of undefined

### ISSUE THREAD

**Issue by windwp** [driftyco/ionic#8344]
*
I got this error when upgrade ionic from beta 11 to rc

![Image of issue](http://i.imgur.com/liTJTX0.jpg)

**Which Ionic Version?** 1.x or 2.x
2.0 rc

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.6.0

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Would you mind sharing a repo I can use to reproduce this issue?

**Comment by manucorporat** [comment]
No idea how to reproduce this crash.

**Comment by windwp** [comment]
@jgw96 After change some code and recompile this error disappear and I don't know why :)
