### ISSUE TITLE
Intellisense Webstorm doesn't work for angular 2 libraries

### ISSUE THREAD

**Issue by aavelyn** [driftyco/ionic#8346]
#### Short description of the problem:

Webstorm won't show autoimport/autocomplete prompts for angular 2 keywords. I think it's because all @angular dependencies aren't on first level (because of ionic-angular)

Deleting node modules and placing all @angular dependencies before ionic-angular and run npm install solves it, but not sure if it'll create conflicts (shouldn't?)

#### What behavior are you expecting?

Webstorm to shop classic autoimport/autocomplete prompts for @angular keywords 

**Which Ionic Version?** Ionic 2 rc0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#52

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I have moved this issue to app-scripts since this is not an issue with the framework. Thanks for using Ionic!
