### ISSUE TITLE
ionic cli version not getting updated with npm install

### ISSUE THREAD

**Issue by balasivagnanam** [driftyco/ionic#8348]
#### Short description of the problem:
Ionic cli is not getting updated on 
`npm install ionic -g`

#### What behavior are you expecting?
After npm install ionic -g , I was expecting it wil update ionic cli version to recent as well.
The document to upgrade says ionic cli is 2.1.0. But i cant see it getting updated.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

![image](https://cloud.githubusercontent.com/assets/4233785/18987169/f88017b4-8732-11e6-96ee-5bc051d12b23.png)

**Comment by infinnie** [comment]
Uninstall Ionic CLI first, and then reinstall.
>**Important**: if you have installed the `beta` cli you should run `npm uninstall -g ionic` first. You need version `2.1.0` for this release. Check your cli version by running `ionic -v` in the command line.
—https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! The above link to the changelog should help you with this issue. Thanks for using Ionic!

**Comment by balasivagnanam** [comment]
i tried uninstall and install multiple times.. but i keep getting the version as beta.

**Comment by balasivagnanam** [comment]
I first ran 
`npm uninstall ionic -g`
`npm install ionic -g`

it dint work. Later tried to clear cache,
tried to do uninstall with targeted version to uninstall beta and also tried to install with 2.1.0 targeted install command as well.

But nothing works it keeps showing 
2.0.0-beta.25

Tried restarting my PC and did the same as well. Nothing helps.

**Comment by balasivagnanam** [comment]
Finally I managed to solve it... uffff.

if you get ionic -v even after uninstalling..

run 

> where ionic

 and find out the location of your installtion.

```
for me there was a version installed in
    C:\>where ionic
    C:\Program Files (x86)\nodejs\ionic
    C:\Program Files (x86)\nodejs\ionic.cmd
```

I am not sure how it went there last time. but after manually deleting them, My ionic cli is now updated and my project is able to render in browser.

Thanks a lot
