### ISSUE TITLE
SlideBox doesn't update with $scope variable on iOS simulator and device

### ISSUE THREAD

**Issue by CoenWarmer** [driftyco/ionic#835]
When using Slidebox with a ng-repeat and a scope variable, the slidebox doesn't show slides reliably on iOS simulator and device. 

On desktop browser the slidebox is immediately populated with the scope variable. But on device the slidebox initially remains empty until you navigate to another state and navigate back again. Then it is filled like it should be.

$ionicSlideBoxDelegate.update(); doesn't seem to do anything, regardless of timeout length.

I'm using this in my template:

  `<ion-slide ng-repeat="artist in random_artists">
    <div class="box">
            {{artist.title}}
    </div>
  </ion-slide>`

And this in my controller:

`.controller('HomeCtrl', function($scope, $stateParams, $ionicSlideBoxDelegate, DataHandler) {
$scope.random_artists = DataHandler.GetRandomArtists(3);
  setTimeout(function(){
      $ionicSlideBoxDelegate.update();
  },5000);
}`

**Comment by QwertyPong** [comment]
@CoenWarmer i'm sorry for comment in this closed issue. But i want to know, have you fix it? Because i have the same problem with you.
Thanks
