### ISSUE TITLE
Unit Testing with Ionic 2 RC0

### ISSUE THREAD

**Issue by NelsonBrandao** [driftyco/ionic#8351]
#### Short description of the problem:
I'm starting an Ionic 2 project using RC0 and I'm having trouble getting unit tests to work. Almost all the documentation found on the web is for the beta releases that still used gulp. Is there any documentation on how to set it up with the new building system?

I can see that ionic-app-scripts already checks for linter errors, is there any planning to support unit testing?

**Comment by ruedagato** [comment]
+1

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue related to app-scripts and not the framework I have moved this issue to the appropriate repo. Thanks for using Ionic!
