### ISSUE TITLE
Ionic 2 rc0 - file transfer to device

### ISSUE THREAD

**Issue by klochko7** [driftyco/ionic#8353]
Hi all ! How in RC0 transfer file to device ? Who can explain please ?

**Comment by jabas06** [comment]
@klochko7 what do you mean by "transfer file to device"?

**Comment by klochko7** [comment]
**jabas06**, i mean that is it possible to save zip archive to the device memory ?

**Comment by jabas06** [comment]
do you mean to the device internal storage? sure, you can save files using the File plugin. Take a look at http://ionicframework.com/docs/v2/native/file/ 

it will be better if you provide your use case, so the Ionic team can guide you.

**Comment by klochko7** [comment]
**jabas06** , yes, in internal storage from http download zip archive. Is exist any working examples in Ionic2 rco ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
