### ISSUE TITLE
bug: Ionic2 Phonegap's plugin barcode scanner parameters

### ISSUE THREAD

**Issue by Andalarian** [driftyco/ionic#8354]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I saw in the Phonegab barcode scanner plugin documentation tha tI can set some parameters for the plugin but in the Ionic one i saw nothing. 
Is-it possible to set parameters ? 
I've tried to do it like in the phonegap's documentation, but keep getting a "Supplied parameters do not match any signature of call target" error so i guess you can't to it like that.

Thank's in advance.

Phonegap's documentation : https://github.com/phonegap/phonegap-plugin-barcodescanner

Ionic 2 documentation : http://ionicframework.com/docs/v2/native/barcode-scanner/</span>

<span is-issue-template></span>

**Comment by ramonornela** [comment]
Close and move to [ionic-native](https://github.com/driftyco/ionic-native/issues)

Thanks
