### ISSUE TITLE
RC0 - doesn't build with node LTS versions v4.x but do on v5.x and v6.x

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [driftyco/ionic#8355]
**Short story long:**
works on 5.10.1 & 6.7.0 but not on any LTS e.g 4.6.0.

**All details are in forum thread:**
https://forum.ionicframework.com/t/rc0-production-build-for-starter-projects-fails-serve-works-as-expected/65149/2

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#50

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with app-scripts and not the framework I have moved this issue to that repo. Thanks for using Ionic!

**Comment by vukasin-nikodijevic** [comment]
@jgw96 - thx
