### ISSUE TITLE
Immutable.js does not export Map 

### ISSUE THREAD

**Issue by h2qbkhn** [driftyco/ionic#8358]
Hi everyone, 
I developped a project using ionic2 beta11/angular2 rc4. When I upgraded this project with ionic2 RC0, I had a problem: **"immutable.js does not export Map "** I knew that Ionic2 RC0 use @types for Any type definitions for third party libraries. I tried "npm install @types/immutable --save-dev --save-exact" but not working.
Thanks for any help

**Comment by andrucz** [comment]
See #8322

**Comment by h2qbkhn** [comment]
Thank you, this helped me :) I solved this issue
