### ISSUE TITLE
ionic 2 tutorial provided by ionicframework.com not able to see app/app.ts file

### ISSUE THREAD

**Issue by gopi2mohan** [driftyco/ionic#8359]
I am using ubuntu 16.04

my ionic info

Cordova CLI: 6.3.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

npm version: 3.5.2

I was following the http://ionicframework.com/docs/v2/getting-started/tutorial/project-structure/ so far so good but not able to see the app/app.ts file as per the documentation.
on that blog it says app.ts file do the most of the work but i am not seeing it.

I am using sublimetext editor in that after adding my project (ionic start MyIonic2Project tutorial --v2) i am getting red line on every CLASS name. but when i give ionic serve command no error in cmd and browser.

Inside this blog https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0 we have the 5th step saying 

Modify all templateUrl's to be relative to the .ts file. For example in app.component.ts the url should change from build/app.html to app.html and in a page referencing about.html from build/pages/about/about.html to about.html

but i am not able to find templateUrl in it.

I am trying to manualy add the app.html like this (templateurl : 'app.html'). i am not sure about that part some explanation would help

kindly looking forward for reply

**Comment by dmastag** [comment]
The getting started page is still for the old structure and needs to be updated.
Are you on a new app or trying to upgrade an older app ?

**Comment by gopi2mohan** [comment]
i was developing my app in beta.11. 

Now i am trying to create a new project and update my app in that project

**Comment by mhartington** [comment]
Hey there, going to close this since this is an issue with ionic-site, not the framework it self.

The getting started guide does indeed need some attention. I'll try to update it and re-work it a bit for RC0.

https://github.com/driftyco/ionic-site/issues/807

Follow that issue for progress. 
🍻
