### ISSUE TITLE
(docs) Broken links (3) at /docs/v2/api/components/nav/Nav/

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#8361]
#### Short description of the problem:

At page http://ionicframework.com/docs/v2/api/components/nav/Nav/ there are broken links [NavController](http://ionicframework.com/docs/v2/api/components/nav/NavController/), [NavController API Docs](http://ionicframework.com/docs/v2/api/components/nav/NavController/) and [Tab](http://ionicframework.com/docs/v2/api/components/Tabs/Tab/).

#### What behavior are you expecting?

All links should be working.

**Steps to reproduce:**
1. Open http://ionicframework.com/docs/v2/api/components/nav/Nav/
2. Search for "NavController API Docs"
3. Click the link and see 404

**Which Ionic Version?** 2.x

**Comment by mhartington** [comment]
http://ionicframework.com/docs/v2/2.0.0-rc.0/api/components/nav/Nav/

**Comment by astec** [comment]
@mhartington the [page](http://ionicframework.com/docs/v2/2.0.0-rc.0/api/components/nav/Nav/) you refer has the same issue. So why close?

**Comment by mhartington** [comment]
Sorry about that, links should be good now! 

https://github.com/driftyco/ionic-site/commit/317ba4b7d459ef2116dcb05e60783c7fb2a00316

Just updated the search index and bypassed the caching (for now)
You should be good to go!
🍻
