### ISSUE TITLE
ion-list reorder is triggering the click event in RC0

### ISSUE THREAD

**Issue by eafif** [driftyco/ionic#8362]
In RC0, for an ion-list with `reorder` set to true, when clicking on the handle and dragging the `ion-item`, both the `ionItemReorder` and `click` events are being triggered.

In the example below, upon reorder, both the `reorderInstructions` and `setInstruction` are being called.

```
<ion-list reorder="{{reorder}}" (ionItemReorder)="reorderInstructions($event)">
    <ion-item-sliding *ngFor="let instruction of instructions">
      <button ion-item (click)="setInstruction(instruction)">
        <h2>{{instruction.title}}</h2>
      </button>
      <ion-item-options side="right" icon-left>
        <button ion-button color='danger' (click)="removeInstruction(instruction.id)">
          <ion-icon name="trash"></ion-icon>
          Remove
        </button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
```

**Comment by manucorporat** [comment]
@eafif I can not repro.

BTW, do not use `reorder="{{reorder}}"`, but `[reorder]="reorder"`

**Comment by eafif** [comment]
I started a new blank project and can replicate it. Here's a [link](https://github.com/eafif/ionic-rc-bug-report) to the project.

I also included a video (bugreport.mov) showing the behaviour.

**Comment by manucorporat** [comment]
Thanks for the @eafif ! I can reproduce it! 
Investigating...

**Comment by manucorporat** [comment]
@eafif  fixed!
