### ISSUE TITLE
transitionDelay missing from NavOptions

### ISSUE THREAD

**Issue by aldo-roman** [driftyco/ionic#8365]
#### Short description of the problem:
While pushing a Nav, the options parameter used to have a `transitionDelay` property, which is now missing. I need that for transition animation.

#### What behavior are you expecting?
`nav.push(component, params, {transitionDelay: 800})` should be a valid code

**Steps to reproduce:**
1. Create a navigation between two components
2. Add code referred above
3. Navigate in app, no delay is performed

```
export interface NavOptions {
    animate?: boolean;
    animation?: string;
    direction?: string;
    duration?: number;
    easing?: string;
    id?: string;
    keyboardClose?: boolean;
    progressAnimation?: boolean;
    ev?: any;
    updateUrl?: boolean;
    isNavRoot?: boolean;
}
```
 

**Which Ionic Version?** 2.x

**Comment by mhartington** [comment]
This was removed because navigation was refactored. The navigation are no longer async, so we do not need that delay anymore.

**Comment by manucorporat** [comment]
Just use `setTimeout` to add a delay in case you need it

**Comment by aldo-roman** [comment]
@mhartington I did that. Also added `duration: 0` and reduced the Timeout delay.

I didn't find it in documentation or changelogs
