### ISSUE TITLE
Track by $index or anything doesnt work with collection-repeat

### ISSUE THREAD

**Issue by nickbar06** [driftyco/ionic#8366]
I have a custom filter on an ion item collection-repeat 

```
<a class="item" ng-click="setFilter('{{userId}}');">
   My Open Items
 </a>
```

```
$scope.setFilter = function setFilter(myFilter) {
    console.log(myFilter)
    if(myFilter == 'New' || myFilter == 'In-Progress' || myFilter == '')
    {
      $scope.myFilter = {RequestStatus: myFilter};
    }
    else
    {
      $scope.myFilter = {userID: myFilter}
    }

    $ionicScrollDelegate.scrollTop();
  }
```

`<ion-item collection-repeat="item in openItemList | filter: myFilter track by item.Id">`

I have tried ng-repeat, and filtering through ng-repeat makes it super slow. 

This is the problem, I use avatar https://github.com/uttesh/ionic-letteravatar/issues/1 on ion items, if a filter is added to the list (myFilter), the filtered list won't have the correct avatar, but the old avatar based on the previous $index. 

When I use ng-repeat="item in openItemList | filter: myFilter track by item.Id" it works like a charm and it shows me all the correct avatars for the users, but not when i use collection repeat, it just doesnt do anything.

I just need collection-repeat to behave like ng-repeat

Ionic Version 1.3.1

Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.5.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#88
