### ISSUE TITLE
slow startup application. IONIC RC.0

### ISSUE THREAD

**Issue by paatrick** [driftyco/ionic#8367]
Hello good afternoon, my app this with a very slow start and some things appear on the console:

0     832032   log      deviceready has not fired after 5 seconds.
1     832037   log      Channel not fired: onDOMContentLoaded
2     832040   warn     Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
3     832207   log      DEVICE READY FIRED AFTER, 10292, ms

I already desistalei all plugins and installed again, since deleted and added the platform. And nothing worked

My plugins are:
com.amitsinha.backashome 0.1.0 "Back As Home"
com.sarriaroman.PhotoViewer 1.1.5 "PhotoViewer"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-intercom 3.0.11 "Intercom"
cordova-plugin-mixpanel 2.2.1 "Mixpanel"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
phonegap-plugin-push 1.8.2 "PushPlugin"

My app.component.ts is 
rootPage = SignPage;
platform.ready().then(() => {
navigator.splashscreen.hide();
StatusBar.backgroundColorByHexString('#02819e'); 
});

Please someone help me?

**Comment by paatrick** [comment]
I already desistalei all plugins and installed again, since deleted and added the platform. And nothing worked 

My plugins are:
com.amitsinha.backashome 0.1.0 "Back As Home"
com.sarriaroman.PhotoViewer 1.1.5 "PhotoViewer"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-intercom 3.0.11 "Intercom"
cordova-plugin-mixpanel 2.2.1 "Mixpanel"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
phonegap-plugin-push 1.8.2 "PushPlugin"

My app.component.ts is 
rootPage = SignPage;
platform.ready().then(() => {
            navigator.splashscreen.hide();
            StatusBar.backgroundColorByHexString('#02819e'); 
});

Please someone help me?

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Would you be able to provide a repo that i can use to reproduce this issue? Thanks!

**Comment by paatrick** [comment]
Hi @jgw96 Thanks for answering me! 

The software that I develop is a private software, and can not create an open repository, is there any way I can help you debug? Do you think it would help you if I made a video?

I would like to tell a few more things, my software contains 17 pages. Do you think this influences the slow start? Please help me, I need to launch my very App. 

Thank you friend.

**Comment by jgw96** [comment]
Hello @paatrick ! Thanks for the info. This would definitely be the issue. So normally with mobile apps (both native and hybrid) you want to try to have the minimal number of views possible. Your templates should be as generic as possible and then based on what the user is trying to view at the time you can load different data into the view. I am going to close this issue for now as it is not really an Ionic framework issue. Thanks!
