### ISSUE TITLE
Loading always with backdrop

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#837]
As in topic
Here's example: http://codepen.io/piernik/pen/BDClo/

**Comment by shadowsyntax** [comment]
The artefact is still happening up to 1.0.0-RC1 but you can make it go away using sass. You just have to target the right class.

```sass
.loading-container .loading {
  padding: 20px;
  border-radius: 5px;
  background-color: rgba(0, 0, 0, 0);
``` 
 In particular the bg-color attribute.
