### ISSUE TITLE
feat: Environment configuration with Ionic 2 RC0 upgrade

### ISSUE THREAD

**Issue by crystal98** [driftyco/ionic#8370]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>In ionic 2 beta 11, I customized gulpfile.js to create environment configuration for app service configuration like service URL when building app for dev or prod. Ionic 2 RC 0 removed gulpfile.js in project. What is the best solution to perform the environment configuration in RC 0?</span>

<span is-issue-template></span>

**Comment by rodriguesgm** [comment]
someone has some advice on this?

**Comment by Aleksandr-Leotech** [comment]
I'm wondering about this too. All of the build configs are now hidden inside dependencies and it is impossible to modify the build process in any way.

**Comment by gmq** [comment]
Using that documentation we are doing the following:

```
config/config.ts // only contains the typing
config/config.dev.ts
config/config.prod.ts
config/index.ts (barrel pointing to the appropriate file)
```

```javascript
// package.json
  "config": {
    "ionic_rollup": "./scripts/rollup.config.js"
  },
```

```javascript
// scripts/rollup.config.js
// Same as https://github.com/driftyco/ionic-app-scripts/blob/master/config/rollup.config.js
// with some additions.

var replace = require('rollup-plugin-replace');
var fs = require('fs');

// ...
  plugins: [
    replace({
      include: 'src/config/index.ts',
      './config': process.env.IONIC_ENV == 'prod' ? './config.prod' : './config.dev',
    }),
    builtins(),
// ...

// check if files actually exist
if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
  fs.access('src/config/config.prod.ts', fs.F_OK, (err) => {
    if (err) {
      throw err;
    }
  });
} else {
  fs.access('src/config/config.dev.ts', fs.F_OK, (err) => {
    if (err) {
      throw err;
    }
  });
}
```

With this setup we can use `import { config } from '../config';` and the editor will know what's inside thanks to `config.ts`. Once it's compiled it'll call the appropriate content from either `config.dev.ts` or `config.prod.ts`.

If you don't have anything secret inside your `config.dev.ts` file you could point the barrel to that file directly instead of using the empty `config.ts`.

This workflow works for us but I'd appreciate any suggestions on how to improve it.

**Comment by rodriguesgm** [comment]
Hi @gmq, thanks for your collaboration. Could you put the content of config.ts, config.dev.ts and index.ts, just to make clear the role configuration?
I don't know if i get right the "barrel" part.
thanks

**Comment by gmq** [comment]
Sure @rodriguesgm.

```typescript
// config.ts
export let config: {
  serviceUrl: string;
};
```

```typescript
// config.dev.ts
export let config: {
  serviceUrl: string;
} = {
  serviceUrl: 'http://example.com',
};
```

```typescript
// index.ts
export * from './config';
```

**Comment by rodriguesgm** [comment]
@gmq great, that worked... 

one questions: we need to copy the rollup.config.js from ionic-app-scripts right? so if they update this file, fix some issue or something like that, we will need to do it manually in our project, right?
is there some way to do what you did without override the role file?

**Comment by gmq** [comment]
@rodriguesgm I haven't had the time to implement it but https://github.com/driftyco/ionic-app-scripts/issues/103#issuecomment-251916953 is a possible alternative.

**Comment by rodriguesgm** [comment]
@gmq is it possible to do the same but for webpack? the new ionic-app-scripts uses it by default, and it seems it's more stable than rollup.

**Comment by rodriguesgm** [comment]
Ok, got it.. Let just finish some things here and I'll post my config.js

**Comment by Luchillo** [comment]
I was very happy when Ionic staff decided to go with original plan, Webpack 2, however they locked down a lot about the Webpack config.

I get it, they are abstracting out complexity from noobs, but are also making it harder for advanced users, don't you think?

**Comment by brandyscarney** [comment]
There is some documentation for the build process here: https://github.com/driftyco/ionic-app-scripts/blob/master/README.md#custom-configuration

If you are still having issues please create an issue on that repository. Thanks! :)
