### ISSUE TITLE
shouldEnable option in ion-infinite-scroll after upgrade to RC0

### ISSUE THREAD

**Issue by jafaripur** [driftyco/ionic#8380]
#### Short description of the problem:

When serve the application this error occured and after remove shouldEnable from infinite scroll it's work.

#### What behavior are you expecting?

Run the application

**Steps to reproduce:**
1. Upgrade to RC0
2. Serve application

```
<ion-infinite-scroll (ionInfinite)="doInfinite($event)" [shouldEnable]="showingSection != 'list'">
        <ion-infinite-scroll-content loadingText="{{'Loading more data...' | translate}}"></ion-infinite-scroll-content>
</ion-infinite-scroll>
```

```
Unhandled Promise rejection:

Template parse errors:
Can't bind to 'shouldEnable' since it isn't a known property of 'ion-infinite-scroll'.
1. If 'ion-infinite-scroll' is an Angular component and it has 'shouldEnable' input, then verify that it is part of this module.
2. If 'ion-infinite-scroll' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("h"></ion-icon></button>
    </ion-list>
    <ion-infinite-scroll (ionInfinite)="doInfinite($event)" [ERROR ->][shouldEnable]="showingSection != 'list'">
        <ion-infinite-scroll-content loadingText="{{'Loadi"): StoreIndexPage@39:60

; Zone: <root> ; Task: Promise.then ; Value:
Error: Template parse errors: Can't bind to 'shouldEnable' since it isn't a known property of 'ion-infinite-scroll'. 1. If 'ion-infinite-scroll' is an Angular component and it has 'shouldEnable' input, then verify that it is part of this module. 2. If 'ion-infinite-scroll' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("h"></ion-icon></button> </ion-list> <ion-infinite-scroll (ionInfinite)="doInfinite($event)" [ERROR ->][shouldEnable]="showingSection != 'list'"> <ion-infinite-scroll-content loadingText="{{'Loadi"): StoreIndexPage@39:60
```
 
**Which Ionic Version?** 1.x or 2.x

2.x RC0

**Comment by manucorporat** [comment]
@jafaripur `shouldEnable` was never a valid attribute for `ion-infinite-scroll`. are you sure it made any difference in previously releases?

**Comment by jafaripur** [comment]
I'm just upgrade application and try to fix error occurred after upgrade to RC0. ``shouldEnable `` metioned in this doc `http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/` and i'm used it with previous version Beta11

**Comment by manucorporat** [comment]
@jafaripur but It was never mentioned in the doc as a Input:
http://ionicframework.com/docs/v2/2.0.0-beta.11/api/components/infinite-scroll/InfiniteScroll/#input-properties

Previously, it just didn't crash. It silently did not work.

**Comment by jafaripur** [comment]
Thank you.

**Comment by manucorporat** [comment]
I submitted a PR to support it though: https://github.com/driftyco/ionic/pull/8385
