### ISSUE TITLE
[v2 rc0] Which components support `mode` instance method?

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic#8382]
Thanks for such a great framework i love it more and more.

Which components support `mode` instance method?

I found out that `ion-segment` supports that from [here](https://ionicframework.com/docs/v2/api/components/segment/Segment/#mode) but cant seem to find if `ion-radio` supports that or not.
and they say:

> Components can now individually set a mode, which means an app can mix and match iOS / Material Design / Windows Platform modes if that’s desired

**Comment by manucorporat** [comment]
I will talk with my coworkers to have this more clear in the docs, but in the meantime:

<img width="419" alt="screen shot 2016-10-01 at 13 26 23" src="https://cloud.githubusercontent.com/assets/127379/19013764/b8056092-87da-11e6-8f82-6e54ad0a406e.png">
