### ISSUE TITLE
Device plugin not working since 2.0.0-rc.0

### ISSUE THREAD

**Issue by allnightlong** [driftyco/ionic#8383]
I've got such a code in one of my service:
`this.deviceId = Device.device.uuid ? Device.device.uuid : ('test-device-' + Date.now());`

In prod env deviceId is actual uuid of the device with fallback in dev environment .
Running with ionic 2.0.0-beta.11 working as expected.
Since upgrading to 2.0.0-rc.0 deviceId is always test-device-timestamp even on real device.

```
$ ionic info
Your system information:
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: 
Node Version: v6.7.0
```
Actual dev platfrom - win10. Testing device - andoird.

**Comment by manucorporat** [comment]
Can you remove the /node_modules, /platforms and /plugin folders? and create them from scratch?
```
rm -rf node_modules
rm -rf plugins
rm -rf platforms
npm install
cordova platform add android
ionic build
```

**Comment by allnightlong** [comment]
Actually, I was building with 
`ionic package build android`

But after trying your suggestion, I've got very interesting situation:
After run:
`ionic run android`
situation is the same - `Device.device.uuid` is `false`

I've tried to debug (livereload + console):
`ionic run android -lc`
And not it's working :confused:
Also, `READY` event is duplicated - may be here is the problem?
```
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

0     287608   log      DEVICE READY FIRED AFTER, 1416, ms
1     287612   log      DEVICE READY FIRED AFTER, 1218, ms
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#619

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with a native plugin I have moved this issue to the ionic-native repo. Thanks!
