### ISSUE TITLE
strange small grey rectangle below top menu

### ISSUE THREAD

**Issue by zeroonea** [driftyco/ionic#8384]
There is a strange small grey rectangle below top menu.
1. Start fresh ionic 2 tutorial app
2. Open menu
3. Tap My First List
4. You will see it like picture: https://i.imgur.com/gQYTF8A.jpg

**Comment by manucorporat** [comment]
Can you run `ionic info` and post the results?

**Comment by zeroonea** [comment]
Sure

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by brandyscarney** [comment]
Hmmm looks like this issue popped back up again: https://github.com/driftyco/ionic/issues/6416

**Comment by edismooth** [comment]
I've got the same issue in ionic2 RC0. #6416 solution doesn't work.

**Comment by unfg** [comment]
I also have the same problem in ionic2 RC0.

**Comment by laserus** [comment]
Yes, that is exactly the same as in #6416

**Comment by unfg** [comment]
I have this problem, when i create page with ModalController.

**Comment by jbw91** [comment]
I have this issue as well in RC0.

**Comment by brandyscarney** [comment]
Closing as a duplicate of #6416
