### ISSUE TITLE
Any way to make Slides speed (Duration of transition between slides) depend on drag speed? 

### ISSUE THREAD

**Issue by zeroonea** [driftyco/ionic#8390]
When I drag Slide very fast and release, the Slide is still moving with 300ms duration. It look not natural like native app. Anyway to work around with this?

And maybe should add an options for disable the bounce at the start and end slide.

Best regards,

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
