### ISSUE TITLE
How to include third party libs into ionic 2 RC0 ?

### ISSUE THREAD

**Issue by bnjjj** [driftyco/ionic#8391]
For example I want to include the lib lazy.js, before RC0 I used "require("lazy.js"). Now it's broken :/

So I haven't informations about install a third party libs. The example in your FAQ with @typings install doesn't work. My ionic 2 application in production is now blocked by this issue :/

Thanks for you informations

**Comment by windwp** [comment]
https://forum.ionicframework.com/t/how-to-import-lodash-in-rc-0/64943/8

**Comment by bnjjj** [comment]
As I said this solution doesn't work :/

**Comment by ericmarcos** [comment]
Hi, I'm running into a similar problem with another library: PIXI.js

I ran
```
npm install pixi.js --save
typings install dt~pixi.js --save --global
```

Then I added `import { Sprite, Container, autoDetectRenderer } from 'pixi.js';` in my main component which produces the following error at compile time:

```
src/pages/home/home.ts(5,55): error TS2307: Cannot find module 'pixi.js'.
```

This error only occurs in RC0, I tried this before in different beta versions and it worked.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Also, we are currently working on making third party libraries written in commonjs (and not the newer standardized es6 modules that rollup is built for by default) easier to use with our new build.Thanks for using Ionic!
