### ISSUE TITLE
Angular forms missing in Ionic 2 RC

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic#8393]
I am migrating an Ionic 2 beta 11 app to RC, as per the release note instructions, based on a new RC project. I was previously using the new Angular forms like this:

`import {FormBuilder, ControlGroup, Validators} from '@angular/common';`

but that import no longer works. How do I get Angular forms in RC? DoI have to npm install it?

system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by thomaswb** [comment]
Doh. It's changed to:

`import {FormBuilder, ControlGroup, Validators} from '@angular/forms';`

**Comment by balasivagnanam** [comment]
Even after changing to above one I am getting this,

![image](https://cloud.githubusercontent.com/assets/4233785/19068730/6112236e-8a56-11e6-942d-502c6f795ff6.png)
