### ISSUE TITLE
[ERROR] Setting duration in LoadingController - generates NavController null error

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8394]
#### Short description of the problem:
Setting LoadingController duration generates error in console indicating NavController is null. 

#### What behavior are you expecting?
No errors

**Steps to reproduce:**
1. Just add duration to loadingController create method and see error in console on dismiss

```
let loading = this.loadingCtrl.create({
      content: 'See console error in few seconds',
      duration: 5000
});
loading.present();
setTimeout(function () {
  loading.dismiss();
},2000);
```

**Stacktrace:**
```
error_handler.js:51 TypeError: Cannot read property 'remove' of null
    at Loading.ViewController.dismiss (view-controller.js:50)
``` 
and `view-controller.js:50` error line is
```
return this._nav.remove(this._nav.indexOf(this), 1, options).then(function () {
            _this._onDidDismiss && _this._onDidDismiss(data, role);
            _this._onDidDismiss = null;
            return data;
        });
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc0, no errors in beta 11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
@aggarwalankush fixed https://github.com/driftyco/ionic/commit/d5f71a448dd8724a97e589a94d974d84248c477f !
