### ISSUE TITLE
apollo library not working in RC0 (rollup+commonjs circular dep issue)

### ISSUE THREAD

**Issue by metzc** [driftyco/ionic#8400]
I used the library apollo-client successfully before RC0 in an ionic project. Now the runtime crashes as soon as i import from the apollo library:

> Uncaught TypeError: Cannot read property 'HTTPFetchNetworkInterface' of undefined (anonymous function) @ batchedNetworkInterface.js:75

I digged into this already and it very much looks like this is a problem due to rollup+commonjs, as is also seen with other libraries. In the case of apollo this looks like a circular dependency that the rollup commonjs plugin just can't handle (https://github.com/rollup/rollup-plugin-commonjs/issues/105).

I wonder how the ionic project wants to deal with this? If Rollup isn't compatible with a lot of existing important libraries, i wonder if it is a good fit for a general purpose framework like Ionic? Maybe the good approach of rollup can be combined with some compatibility as suggested in this comment in a similar issue: https://github.com/driftyco/ionic/issues/8356#issuecomment-250785444

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#67

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a build related issue i have moved this to the app-scripts repo. Thanks for using Ionic!
