### ISSUE TITLE
Ionic2 RC.0 third party scss libraries not found after live compilation

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#8401]
Hi,

I added some third party scss libraries in my application.

To accomplish that:
- "npm install" 
- override sass.config.js to include these scripts.
- add "@include" in my app.component.scss

Works fine. 

I only face one problem. When I'm running the server ("ionic serve"), if I make any changes to my scss files, the server gonna recompile the sass files but it isn't able, seems so, to find these third party scss files anymore. For example, the recompilation results could be:

    [11:26:15]  Sass Error: line: 85, column: 1
    File to import not found or unreadable: _bourbon.scss
    Parent style sheet: /Users/me/Documents/projects/myproject/src/app/app.component.scss

Therefore, each time I make a scss change I've to start my server again, which isn't really convenient.

Could that be fixed?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#66

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is a build related issue i have moved this issue to the appropriate repo. Thanks!
