### ISSUE TITLE
Error after running : run npm install —save @ionic/app-scripts@latest

### ISSUE THREAD

**Issue by mcornillon87** [driftyco/ionic#8402]
#### Short description of the problem:
**Running the following tweet in my app folder, I got an error and my app doesn't work anymore :**
ionic ‏@Ionicframework  12 hil y a 12 heures
We’ve updated @ionic/app-scripts to fix some issues (like out-of-memory). RC.0 apps should run npm install —save @ionic/app-scripts@latest

**Error :** 

`macbook-pro-de-mahe:communeApp mahecornillon$ npm install —save @ionic/app-scripts@latest
npm ERR! addLocal Could not install /Users/mahecornillon/Documents/communeApp/—save
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "—save" "@ionic/app-scripts@latest"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! The header content contains invalid characters
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

When I serve my app, all my theming is gone... Any idea how to make this work ?

**Which Ionic Version?** 1.x or 2.x
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.7 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.0 Build version 8A218a 

<img width="328" alt="capture d ecran 2016-10-02 12 44 30" src="https://cloud.githubusercontent.com/assets/22214655/19020076/98f6b98e-889e-11e6-88f5-cc4a269ee06e.png">

**Comment by peterpeterparker** [comment]
Have you try with sudo too?

     **sudo** npm install —save @ionic/app-scripts@latest

**Comment by mcornillon87** [comment]
Yes still getting the error...

**Comment by peterpeterparker** [comment]
try this (just tested seems to have work for me)

     sudo npm install --save-dev @ionic/app-scripts@latest

**Comment by mcornillon87** [comment]
Fixed ! Worked with this command. Thank's a lot :)
