### ISSUE TITLE
Implement lazy loading of data like Material Design 1.1

### ISSUE THREAD

**Issue by michaelkrog** [driftyco/ionic#8404]
#### Short description of the problem:

I am unable to use Virtual Scroll and InfiniteScroll for our solution because it does not fulfill our requirements to the behaviour and performance.
#### What behavior are you expecting?

I expect/need a behaviour like Virtual Scroll BUT with lazy loading of data – just like the behaviour of VirtualRepeat in Material Design 1.1.

**Steps to reproduce:**
_Does not apply_

**Which Ionic Version?**
2.x
#### Plunker that shows an example of your issue

Demo of Material Design's implementation with 10000 elements:
http://codepen.io/anon/pen/JRALGq

Notice how there is no need to load more than the visible data up front, but you are still able to scroll thousands of rows down without a sweat.

ping @adamdbradley (In relation to our talk at angular connect in London)

**Comment by michaelkrog** [comment]
I have been looking more into source of Virtual Scroll – and one thing that makes it extra difficult when it comes to lazy loading data is headers/footers.

A great benefit of the way MD's virtualrepeat is implemented is that if you show the list and scroll fast to fx. row 2000, then you end up loading only 40 elements (depending on your configuration).

It works like this:
1. Virtualrepeat container is shown
2. It asks for index 0 to 20
3. You scroll fast to index 2000
4. It asks for index 2000 to 2020

However, headers/footers are pseudo elements injected via runtime logic using this interface:
```
Fn(record, recordIndex, records);
```

If lazy loading were to be implemented then this interface cannot be fulfilled as `records` are not available. `record` and `recordIndex` could both be available when data has been loaded, but some scenarios require more than that. 

Perhaps a more reasonable interface in a lazy loading scenario would be:
```
Fn(record, recordIndex, adjacentRecord);
```
`adjacentRecord` being previous records for headerlogic and following record for footer logic.

**Comment by thanzen** [comment]
I would vote for this approach.
Take Yahoo.com for example, the scroll event will always load the next n records.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#69
