### ISSUE TITLE
is latest ionic 2 version supported to SystemJS  module?

### ISSUE THREAD

**Issue by thangam105** [driftyco/ionic#8409]
Previously, I have created the ionic2 application with systemjs module. I have written gulp task for systemjs module  conversion by gulp typescipts. But in latest ionic 2 version, gulpfile functionality is moved to @ionic/scripts.  

Please suggestion me how to upgrade ionic2 latest version?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
