### ISSUE TITLE
Opening a modal triggers a click inside inputs within that modal

### ISSUE THREAD

**Issue by jwenzler** [driftyco/ionic#8416]
#### Short description of the problem:
If you click to open a modal, that click propagates into the modal itself and can click open an input.

#### What behavior are you expecting?
For the initial opening click not to affect anything inside of the modal.

**Steps to reproduce:**
1. Create a page where you can open a modal with a button where an input sits directly in the same spot inside the modal
2. Open a modal with the button
3. Watch they keyboard appear due to focus from clicking onto the input

Recording of issue
https://cl.ly/1R2n0o0U3U45

**Which Ionic Version?** 1.x or 2.x
RC0 V2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a repo that i can use to reproduce this issue? Thanks!

**Comment by manucorporat** [comment]
@jgw96 probably related with https://github.com/driftyco/ionic/issues/7693

It does not happen in desktop and it is not longer an issue in iOS WKWebView.

This is a UIWebView-only issue

**Comment by jwenzler** [comment]
Confirmed that this is fixed with WKWebView.  Thanks guys, Ionic is amazing, keep it up.
