### ISSUE TITLE
Ionic package build empty cordova project for existing app

### ISSUE THREAD

**Issue by vahidvdn** [driftyco/ionic#8417]
Hi. I'm using ionic package for building ios app. I have already submitted the app about 30 times and there was no problem.

Now when I build ios, it submits the project very fast and the output is a simple cordova project with cordova's logo.

Any idea?

**Comment by comfortme** [comment]
issues:
https://github.com/driftyco/ionic-cloud-issues/issues/197
https://github.com/driftyco/ionic-cloud/issues/62
forum post:
https://forum.ionicframework.com/t/ionic-package-ios-build-fails-development-team-required/65033/15
