### ISSUE TITLE
Popover Arrow flipped when shown above item (iOS)

### ISSUE THREAD

**Issue by ColinFrick** [driftyco/ionic#8419]
#### Short description of the problem:
When a popover opens above an element (f.e. button in footer) the arrow still points up.

#### What behavior are you expecting?
Popover arrow pointing to the element (down)

**Steps to reproduce:**
1. Create a page with a footer
2. Add button to footer
3. Open Popover with this button

**Other information:**
Caused by:

CSS class popover-bottom is added to the popover itself, but in the iOS styling it's handled as a child element:
https://github.com/driftyco/ionic/blob/master/src/components/popover/popover.ios.scss#L69
https://github.com/driftyco/ionic/blob/master/src/components/popover/popover.ios.scss#L74

Remove space should fix the issue
```
.popover-ios.popover-bottom .popover-arrow {
  top: auto;
  bottom: -10px;
}

.popover-ios.popover-bottom .popover-arrow::after {
  top: -6px;
}
```

**Which Ionic Version?** 1.x or 2.x
2.0.0-rc.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa 
Node Version: v6.7.0

**Comment by zakton5** [comment]
Any way this could get moved in to the rc.1 milestone?

**Comment by manucorporat** [comment]
@zakton5 can you provide a screenshot?

**Comment by ColinFrick** [comment]
@manucorporat 
![25fa0d13-3f4b-4055-be51-e5c1c9ca16ae](https://cloud.githubusercontent.com/assets/5517677/19202829/7c106bfa-8cd4-11e6-87b1-a76c6d63b5cc.png)

**Comment by manucorporat** [comment]
@brandyscarney confirmed this is a real issue:
<img width="392" alt="screen shot 2016-10-10 at 12 17 40" src="https://cloud.githubusercontent.com/assets/127379/19233087/a4e30676-8ee3-11e6-8270-b0d086aa5d2a.png">

**Comment by brandyscarney** [comment]
Thanks for the PR! This will be fixed in the rc.1 release. :smile:
