### ISSUE TITLE
Ionic Storage - QuotaExceededError - error - 

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#8426]
Hello, 
I was using **SqlStorage** in beta 11. My requirement is simple, storing key-value pair.
I have just changed to @ionic/storage.
As per its documents, it says that 
**A simple key-value Storage module for Ionic apps based on LocalForage, with out-of-the-box support for SQLite. This utility makes it easy to use the best storage engine available without having to interact with it directly. Currently the ordering is SQLite, IndexedDB, WebSQL, and LocalStorage.**

Hence I have deployed it in one of my device for testing and I found that it is throwing 
**EXCEPTION: Uncaught (in promise): QuotaExceededError: An attempt was made to add something to storage that exceeded the quota.**

I am assuming it is using LocalStorage somehow. In beta 11 it was working very well using 
```
new Storage(SqlStorage, { name: 'my_app' });
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Are you seeing this issue on an Android device or iOS device?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-storage#10

**Comment by jgw96** [comment]
Hello, since this was an issue with Ionic storage and not the framework I have moved this issue to that repo. Thanks!

**Comment by chambahr** [comment]
Hello. Thanks for this solution. It has saved a thousand souls.
