### ISSUE TITLE
Ionic2 RC0, Pipes, "pipe could not be found"

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#8428]
Hi

I'm transferring a beta 11 project over to Release Candidate.

I am using a Pipe in a custom component.

I had added the Pipe to the @NgModule ({ declarations: }) and also the @NgModule ({ providers: }) arrays and imported using this statement:

`import { ConvertTime } from '../pipes/convert-time';`

Should I be importing the Pipes in the component or not? On compile, TsLint is saying:

` tslint: /home/ubuntu/workspace/pathfinder/src/components/graphics-card/graphics-card.ts[2, 10]: Unused import: 'ConvertTime'`

so I'm guessing not.

But then I'm getting an error from my custom component saying:

`The pipe 'ConvertTime' could not be found `

I've had a look at your conference app but sadly you don't use pipes. I could carry on trying things...but I thought I'd ask.

Tom

**Comment by AndreasGassmann** [comment]
I got pipes to work on rc0 without any issues:
- I added my Pipes in the src/app/app.module.ts only to the @NgModule ({ declarations: }) array, not to the providers.
- In my component I did not include the import

Then you can just use it in the html. Does that work?

**Comment by tomgallagher** [comment]
Sadly not. 

Thanks for getting back. Were you using  your pipes in pages or custom components?

**Comment by jgw96** [comment]
Hello @tomgallagher ! Thanks for opening an issue with us. So the correct way to use pipes is to import them in your NGModule and then add them to the declarations array (not the providers array). Can you provide a repo that I can reproduce this issue with?

**Comment by ghenry22** [comment]
pipes are working for me upon updating.  One thing to note though, with the AOT compiling the calls from HTML to your pipe are now type checked so you need to make sure what you are sending into the pipe matches the expected inputs.

This one caught me out for a while because what you did in HTML never used to get assessed like that at compile time.  Pretty handy once you figure out what the hell it's doing!

**Comment by aspidvip** [comment]
Hi! 
error: could not resolve '...../pipe.ts' from '..../app.module.js'

**pipe.ts**
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({
  name: 'orderBy'
})

export class OrderBy implements PipeTransform {

  transform(value: Array<any>, ...args) {
    if (value && args[0]) {
      let type = args[1] ? args[1] : 'asc';
      let key = args[0];

      let ordered = value.sort((a: any, b: any) => {
        if (a[key] > b[key] && type === 'asc') {
          return 1;
        }
        else if (a[key] > b[key] && type === 'desc') {
          return -1;
        }
        else if (a[key] < b[key] && type === 'asc') {
          return -1;
        }
        else if (a[key] < b[key] && type === 'desc') {
          return 1;
        }
        else {
          return 0;
        }
      });
      console.log('this is ordered array we are getting from pipe', ordered);

      return ordered;
    }

    return value;
  }
}

**app.module**
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import {OrderBy} from '../pipe/pipe.ts';
@NgModule({
  declarations: [
    MyApp,
    OrderBy,
..................

not work, please me

**Comment by ghenry22** [comment]
error: could not resolve '...../pipe.ts' from '..../app.module.js'

this would seem to indicate that it cannot find that file, doublecheck the path to your pipe.ts file is correct perhaps?

For my app i have each pipe having an individual js file under the /pipes folder.  So for my readableTime pipe (readabletime.js is the file name) I have the below import statement.

import { ReadableTime } from '../pipes/readabletime'

**Comment by aspidvip** [comment]
thansk you , import {OrderBy} from '../pipe/pipe.ts'; => import {OrderBy} from '../pipe/pipe';

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
