### ISSUE TITLE
Module has no exported member 'Location Accuracy'

### ISSUE THREAD

**Issue by junaidahmed93** [driftyco/ionic#8431]
Hello everyone,
I am getting error while importing LocationAccuracy from ionic native
`Module has no exported member 'Location Accuracy'`
I have already installed the plugin.
Is there any solution?

**Comment by manucorporat** [comment]
Can you share the code that is failing?

**Comment by junaidahmed93** [comment]
Following this code snippet from IONIC 2 native


import { LocationAccuracy } from 'ionic-native';

LocationAccuracy.canRequest().then((canRequest: boolean) => {

  if(canRequest) {
    // the accuracy option will be ignored by iOS
    LocationAccuracy.request(LocaitonAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
      () => console.log('Request successful'),
      error => console.log('Error requesting location permissions', error)
    );
  }

});

**Comment by manucorporat** [comment]
Can you remove the node_modules folder and: `npm install`? let me know if that fixed the issue

**Comment by junaidahmed93** [comment]
I have re-installed node_modules after removing previous one, but still no luck
Error is same

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#625

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this is an Ionic native related issue I have moved this issue to the appropriate repo. Thanks!
