### ISSUE TITLE
RC0 - icon fonts not added

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#8433]
Many times in my upgrade path to RC0 I encountered an error when all the ionicon fonts were missing. They were just not included in www/assets/fonts folder. Though nothing was outputted to console it seemed to be related to messing up styles. For example when I used "ion-button" together with "icon-right" class when actually I didn't have an icon inside the button element.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#73

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Because this is a build related issue I have moved this issue to the ionic-app-scripts repo. Thanks!
