### ISSUE TITLE
[RC0] background-image only work with ionic serve, not ionic build

### ISSUE THREAD

**Issue by dr1v3** [driftyco/ionic#8438]
I've faced with the following problem: background-image from the scss file isn't showing when i'm building android apk by `ionic build android` command
Ionic 2 RC0
```
.image-fav {
  ...
  background-image:url(assets/img/remove.png);
}
```
The picture located in src/app/assets/img/remove.png
When i'm trying the app from the browser with `ionic serve` all works fine
[The same problem](https://forum.ionicframework.com/t/rc0-background-image-only-work-with-serve/65255)

**Comment by ghenry22** [comment]
Check the path to your image, where assets are changed relative to where pages are in the move to RC0.  I have the following in the scss for one of my pages to display a background image and once I adjusted the path to the image all works as expected on device.

.cached-home {
  background-image: url('../assets/img/crowdsun.jpg');
  background-repeat:no-repeat;
  background-size:cover; 
  width:100%;
}

**Comment by dr1v3** [comment]
@ghenry22, it helped to me, thanks.

**Comment by renjithvk** [comment]
### SOLVED

1. Add your images to `src/assets/imgs` directory

2. Set image path in **HTML** like
```<img src="assets/imgs/example.jpg">```
3. Set image path in **SCSS** like
```background-image: url(../assets/imgs/example.jpg);```

It will work **browser**, **emulator** and **build**
