### ISSUE TITLE
Ionic 2 RC.0 - Google Analytics

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#8443]
I finally upgraded my app to Ionic 2 RC0 and when i run the app on my Device i get a error in Google Analtycs (work on latest beta)

![image](https://cloud.githubusercontent.com/assets/953742/19045310/075cef28-8990-11e6-894e-e5345aee1924.png)

The plugin is installed

![image](https://cloud.githubusercontent.com/assets/953742/19045301/fd818432-898f-11e6-8920-013f586613fb.png)

Any have managed to work with RC.0?

Thanks
Baltazar

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#627

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with Ionic Native I have moved this issue to that repo. Thanks for using Ionic!
