### ISSUE TITLE
Spinner black on Android

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#8445]
Hey,

Don't know if you could reproduce it, but it seems that the spinner doesn't inherite anymore the primary color on android Ionic2 RC.0

    <ion-content>
         <ion-spinner></ion-spinner>
    </ion-content>

will produce a css:

    .spinner-crescent circle {
        fill: transparent;
        stroke: #000;
        stroke-width: 4px;
        stroke-dasharray: 128px;
        stroke-dashoffset: 82px;
    }

**Comment by hotforfeature** [comment]
This should be fixed in RC.1, relates to #8598 

The spinner is black by default, you need to add a `color` attribute on Android to set it to the primary color.

```
<ion-content>
  <ion-spinner color="primary"></ion-spinner>
</ion-content>
```

**Comment by peterpeterparker** [comment]
you are right @hotforfeature, it is fixed with RC.1, just checked and confirm it with android.

Also your comment about adding color is also right.

Thx for the feedback
