### ISSUE TITLE
ionic Serve not working properly with ionic2 app  in RC0

### ISSUE THREAD

**Issue by sriteja09** [driftyco/ionic#8447]
Issue with ionic2

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3 Build version 7D175

this is my system configuration.i am using mac book . In my macbook when i am using ionic serve it works. when i write error in the code then ionic serve working fine in that case after that if i change code and run application its not working.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#87

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because this issue was more related to app-scripts instead of the framework I have moved this issue to that repo. Thanks!

**Comment by sriteja09** [comment]
Thanks alot . Great team .
