### ISSUE TITLE
Instructions #14 and #15 seem wrong for Migrating to RC2.0 with Fresh Start

### ISSUE THREAD

**Issue by queejie** [driftyco/ionic#8451]
#### Short description of the problem:
The instruction says: "Move any variables from the mode specific sass files in your beta.11 app into the app.variables file under the mode heading in the new RC0 app."

#### What behavior are you expecting?
I believe it should read "variables.scss".  More importantly, perhaps, there are no headings in that file that reference anything about a mode.  Is the "mode heading" referring simply to a comment, or is there some syntactic connection I am missing? 

**Steps to reproduce:**
1. Look at instructions here.
2. Do a fresh install, e.g.: ionic start --v2 TEST
3. Look at src/themes directory and variables.scss file.

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by danbucholtz** [comment]
@brandy, what are the mode headings? I'll update the docs.

**Comment by brandyscarney** [comment]
@danbucholtz The mode headings are listed like this in the conference app:

https://github.com/driftyco/ionic-conference-app/blob/master/src/theme/variables.scss#L45-L47

Looks like I reverted my commit for the headers (to remove the variables) and forgot to add back just the headers: https://github.com/driftyco/ionic2-app-base/commit/1b08a88e8db2d00f692337f03270ad28891b61d3

Sorry!

**Comment by brandyscarney** [comment]
Thanks for the issue @queejie! I updated the instructions for step 14 and 15 and also added the commented sections to the starter's variables.scss file. Please let me know if there is more we can do to make this clearer! https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#copying-your-project-to-a-new-project
