### ISSUE TITLE
Problem with Smooch

### ISSUE THREAD

**Issue by BloodMoonShard** [driftyco/ionic#8452]
Hello perfect team.
Please i need help, i want to know how i can use this Plugins in the Ionic2
https://github.com/smooch/smooch-cordova

platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      cordova.plugins.Smooch.init({
        "appToken" : "APP_TAGE",
        "conversationAccentColor" : "#FFFFFF" // optional, default is #00B0FF
      });
      cordova.plugins.Smooch.show();
      StatusBar.styleDefault();
    });

But this not work, in the Console.log Safari i got

[Warning] Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them. (console-via-logger.js, line 173)
[Log] deviceready has not fired after 5 seconds. (console-via-logger.js, line 173)
[Log] Channel not fired: onCordovaInfoReady (console-via-logger.js, line 173)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Cordova plugins like the one you mention are meant to be used when the app has been installed to the device and not when in the browser. DeviceReady will not fire in the browser as the app is not wrapped in cordova when running in the browser. Thanks!
