### ISSUE TITLE
Ionic Package Broken?

### ISSUE THREAD

**Issue by cojj90** [driftyco/ionic#8459]
Hi There,

I have an production app that is built with ionic@beta12. I've been using ionic package to build Apple version of the app but today I found that it no longer worked as intended,

The packaged ipa has the following:
- All cordova plugins (splashscree, social sharing, etc...)
- Non of my own code (no html, no js, no css)
- It loads to a "Hello World!" index html file which is not mine

Could someone from ionic team look into this?

Thank you.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#202

**Comment by jgw96** [comment]
Hello, since this issue was an issue with one of our cloud services and not the framework i have moved this issue to the appropriate repo. Thanks!
