### ISSUE TITLE
RC0 ionic emulate ios -lc not working

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic#8463]
with RC0 the command:

ionic emulate ios -lc

doesn't appear to work for me (the app hangs on loading screen)

ionic emulate ios works ok but appears not to with the -lc flags added

**Comment by olavocneto** [comment]
https://forum.ionicframework.com/t/rc0-livereload-android-not-working/65045/10

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1436. Thanks!
