### ISSUE TITLE
ionic run ios --device fails with Error code 65 for command: xcodebuild (xcode 8)

### ISSUE THREAD

**Issue by miloslavskacel** [driftyco/ionic#8464]
#### Short description of the problem:
`$ ionic run ios --device`

fails with 
```
=== BUILD TARGET myApp2RC0 OF PROJECT myApp2RC0 WITH CONFIGURATION Debug ===

Check dependencies

Signing for "myApp2RC0" requires a development team. Select a development team in the project editor.

Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/uzimskacel/workspace/sandbox/myApp2RC0/platforms/ios/cordova/build-debug.xcconfig,-project,myApp2RC0.xcodeproj,ARCHS=armv7 arm64,-target,myApp2RC0,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/uzimskacel/workspace/sandbox/myApp2RC0/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/uzimskacel/workspace/sandbox/myApp2RC0/platforms/ios/build/sharedpch
```

#### What behavior are you expecting?
App is started on iPhone7

**Steps to reproduce:**
```
$ ionic start --v2 myApp2RC0
$ cd myApp2RC0/
$ ionic run ios --device
```

**Which Ionic Version?** 
2 RC0

**ionic -v** 
2.1.0

**ionic info** 
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by miloslavskacel** [comment]
It is possible start the app from Xcode after Team is defined.

Before fix:
![screen shot 2016-10-04 at 11 02 42](https://cloud.githubusercontent.com/assets/2547672/19068397/ca7e0676-8a22-11e6-9e3a-7737a376bfcd.png)

After fix:
![screen shot 2016-10-04 at 10 58 09](https://cloud.githubusercontent.com/assets/2547672/19068415/d655409a-8a22-11e6-81b0-85bb17951953.png)

**Comment by BloodMoonShard** [comment]
Use command:
**cordova platform update ios**

**Comment by miloslavskacel** [comment]
$ cordova platform update ios

does not help.

**Comment by BloodMoonShard** [comment]
Need logs in the npm-debug.log i think had more infomration, if u want u can add me in the skype and i can check this.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this seems to be an issue with your application signing in xcode8 and not an Ionic issue I am going to close this for now. Thanks!

**Comment by miloslavskacel** [comment]
Just to be precise: it is not my application, but ionic starter app.
I guess that problem is in cordova project generation.

**Comment by dimitri320** [comment]
I have the same problem, and it doesn't have anything to do with signing of the App, it seams to me a problem with linking all the plugins.

**Comment by ZalakSA** [comment]
@miloslavskacel Hello, Did you found any solution to your issue? I am facing same problem and need some help

**Comment by cbueno** [comment]
It seems cordova-plugin-console plugin it's no longer supported by cordova-ios 4.5.0 and forward. Remove it from the project did the trick to me.

**Comment by brunolm** [comment]
iOS

- Open `platforms/ios` on XCode
- Find & Replace `io.ionic.starter` in all files for a unique identifier
- Click the project to open settings
- Signing > Select a team
- Go to your device Settings > General > DeviceManagement
  - Trust your account/team
- `ionic cordova run ios --device --livereload`

**Comment by uda1099** [comment]
After a lot of research and tests, including removing the platform, adding old ones, generating manually the profiles, what worked for me was simply disconnecting the phone, running `ionic cordova build ios` and it worked.
It's still a problem because I can't run the app with --livereload, but I can simulate or run throught Xcode at least.
