### ISSUE TITLE
Not able to use FormBuilder and other Form directives

### ISSUE THREAD

**Issue by balasivagnanam** [driftyco/ionic#8465]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
Import and usage of Form and Form related directives is giving error at run time.

#### What behavior are you expecting?
For the forms to render. But the whole app itself is not starting.

**Steps to reproduce:**
1. 
2. 
3. 

```
import {FormBuilder, FormGroup, Validators, FormControl } from '@angular/forms';
@NgModule({
  declarations: [
    MyApp,
    HomePage,
    AccountPage,
    ContestPage,
    EditMemberPage,
    EventDetailsPage,
    EventsPage,
    EventsTabsPage,
    LibraryPage,
    LoginPage,
    MagazinePage,
    MyEventsPage,
    RegisterEventPage,
    VolunteerPage,
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    AccountPage,
    ContestPage,
    EditMemberPage,
    EventDetailsPage,
    EventsPage,
    EventsTabsPage,
    LibraryPage,
    LoginPage,
    MagazinePage,
    MyEventsPage,
    RegisterEventPage,
    VolunteerPage
  ],
  providers: [
    Storage,
    FormBuilder,
    FormGroup,
    Validators,
    FormControl,
    Http,
    Headers,
    //custom providers
    Auth,
    EventsService,
    UserAuth,
    Payments,
    //pipes
    OrderBy
  ]
})
export class AppModule {

}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
![image](https://cloud.githubusercontent.com/assets/4233785/19069983/d88c2d86-8a5b-11e6-8a53-4bb515d23df8.png)

**Which Ionic Version?** 1.x or 2.x
Ionic Version 2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Though it says I dont have cordova, this error was prompted before and I did the installation.

**Comment by Manduro** [comment]
I'm using the formbuilder and it's working fine. You just don't have to import them in your module providers. So remove the following from your providers and just use them in your pages:
```
    FormBuilder,
    FormGroup,
    Validators,
    FormControl,
```

**Comment by balasivagnanam** [comment]
That works but I had to 

```
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
imports: [
    FormsModule,
        ReactiveFormsModule,
    IonicModule.forRoot(MyApp)
  ],
```
add these to my code to avoid templateUrl for ngFormModel to work.

**Comment by balasivagnanam** [comment]
I got it, this has changes to formGroup and formControlName in template instead of ng declarations before.
