### ISSUE TITLE
Ionic v2 - RC0 -  Global scss is not being compiled / copied to main.css

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#8466]
#### Short description of the problem:
Styles added to the theme\global.scss are not being applied to the page. Also after inspecting the main.css they are not being copied there.

#### What behavior are you expecting?
Styles added to the global.scss should be compiled and copied to the main.css.

**Which Ionic Version?** 2.x RC0

#### Plunker that shows an example of your issue
The link for Plunker points to Ionic2 Beta 10. Can you please update the plunker link ?

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by ThorConzales** [comment]
It's a known issue, as a workaround just include global.scss to variables.scss and it gets compiled.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is fixed in the latest version of app-scripts which you can update too by just doing `rm -rf node_modules && npm install`. Thanks!

**Comment by tonyawad88** [comment]
@jgw96  I tried your solution and it didn't work for me. ```rm -rf node_modules && npm install``` didn't work. 

@ionic/app-scripts@0.0.28 ?

**Comment by jbw91** [comment]
Didn't work for me either.

**Comment by dgroh** [comment]
Didn't work for me. Would be really nice to have a doc explaining how to style the app as best practices

**Comment by tonyawad88** [comment]
A temporary workaround, add the following to variables.scss
```
@import "./global";

**Comment by tonyawad88** [comment]
@jgw96 Hi Justin, this is still not fixed and is not part of the latest RC1..

**Comment by tonyawad88** [comment]
Update on this: In RC1, there is no longer global.scss. There is instead an "app.scss" which is considered to be the global.scss.
