### ISSUE TITLE
Cordova file plugin works only once after installation 

### ISSUE THREAD

**Issue by vahidvdn** [driftyco/ionic#8468]
Hi. I'm using cordova `file` plugin for my app. Here is my code and it alerts me after installing app.

    $cordovaFile.getFreeDiskSpace().then(function (success) {
      alert("disk space: " + success);
    }, function (error) {
      alert("error disk space :" + error);
    });

But after closing the app and reopening again, app crashes and becomes just a blank page.

Any idea?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this seems to be an issue with that plugin i would recommend that you open an issue on that plugin's repo. Thanks!

**Comment by vahidvdn** [comment]
Thank you. But I couldn't be able to find the issue part of that repo.
