### ISSUE TITLE
navPush error that it must be within navController

### ISSUE THREAD

**Issue by pfrendo** [driftyco/ionic#8470]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
An error is occurring when not using navPush directly in a page.

#### What behavior are you expecting?
Have to option of using it everywhere

**Steps to reproduce:**
1. Place the navPush directive on an <a> in an <ion-list> (see screenshot)
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by pfrendo** [comment]
![pasted_image_at_2016_09_30_02_46_pm_720](https://cloud.githubusercontent.com/assets/13260474/19073305/8e2dc158-8a3a-11e6-9665-e54bc1f0cac1.png)

**Comment by manucorporat** [comment]
You are using the API incorrectly, the menu does not have an associated navigation stack.
You have to get the ion-nav:

@ViewChild(Nav) nav: Nav;

and then:
```
this.nav.push(Page);
```
