### ISSUE TITLE
bug: Sign up issue

### ISSUE THREAD

**Issue by ManiPalanivel** [driftyco/ionic#8471]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>In, ionic.io/products/creator signup was not working.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying again? It seems to be working fine on my end. Thanks!
