### ISSUE TITLE
RC0 - iOS header is scrollable

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#8472]
On iOS the header area is vertically scrollable. Expected behavior which is working on Android is that the header is static and does not respond to scrolling gestures.

**Comment by mhartington** [comment]
Please follow the github issue template and do not delete it. We need an example base to try to replicate this.

**Comment by dgroh** [comment]
use `overflow: visible;`

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
