### ISSUE TITLE
RC0 - iOS no way to retract keyboard

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#8473]
If I remember correctly then in the previous versions there was a "Done" button on top of keyboard on iOS which currently in RC0 build is missing and thus there is really no comfortable way to retract the keyboard.

**Comment by mhartington** [comment]
Please follow the github issue template and do not delete it. 

You must use the keyboard plugin

https://github.com/driftyco/ionic-plugin-keyboard/#keyboardhidekeyboardaccessorybar

**Comment by ThorConzales** [comment]
I already have it installed as I upgraded my project by creating a new blank project via the CLI.

**Comment by ThorConzales** [comment]
OK, I see the extra method I have to call there.
