### ISSUE TITLE
Issue with Ng2-translate and declartion of pipes

### ISSUE THREAD

**Issue by srikanth748** [driftyco/ionic#8474]
I update my Ionic 2@beta to Ionic 2 RC.
I am trying to use ng2-translate feature in my App .But the issue I am unable to declare pipes in the @component scope.
-----
import {TranslatePipe,TranslateService} from 'ng2-translate';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  providers :[TranslateService],
  pipes :[TranslatePipe]  **** this is the spot of error where it says  "pipes does not found in the      type 'component'
 ----------------
Can any1 suggest a solution to fix this issue .Thanx
})

**Comment by bvx89** [comment]
You should check out the documentation for Angular 2 and ng2-translate. With the new version, you no longer need to specify pipes or providers in the component.

**Comment by davorpeic** [comment]
I just updated to ng2-translete 3.0.0 and there is algo no error about injecting TranslatePipie in main modules..

**Comment by jgw96** [comment]
Hello @srikanth748 , thanks for opening an issue with us! Would you mind checking out our [changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) along with the docs on the [ng2-translate repo](https://github.com/ocombe/ng2-translate). Thanks!

**Comment by srikanth748** [comment]
Yes I did go through those docs ..the "changelog"  says -Remove any use of the providers, pipes and directives arrays in @Component. If so How do I use in other components with out declaring  {pipes :[TranslatePipe] }? 
The new Ionic2 RC folder structure is different from beta so the ng2-translate repo is n't giving me a clear declaration of ng2-translate features. So I am confused . I would really appreciate someone who has implemted ng2-translate in Ionic2 RC .

**Comment by srikanth748** [comment]
@jgw96 
 Yes I did go through those docs ..the "changelog" says -Remove any use of the providers, pipes and directives arrays in @Component. If so How do I use in other components with out declaring {pipes :[TranslatePipe] }? 
The new Ionic2 RC folder structure is different from beta so the ng2-translate repo is n't giving me a clear declaration of ng2-translate features. So I am confused . I would really appreciate someone who has implemented ng2-translate in Ionic2 RC .
