### ISSUE TITLE
Sliding list delay and autoclose

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8481]
#### Short description of the problem:
1. Quickly clicking the sliding list after closing clicks the option behind it. Seems like some delay issue.
2. Clicking sliding option auto closes the sliding list

#### What behavior are you expecting?
1. Clicking sliding list should not click option behind it, it should always trigger click on `<ion-item>` not in `<ion-item-options>`
2. Sliding list should not auto close on option's click. At least, it should be configurable.

**Steps to reproduce:**
Use any sliding list such as on schedule screen in Ionic conference app

**Which Ionic Version? 1.x or 2.x**
Ionic 2 rc0

**Your system information:**

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
> Clicking sliding list should not click option behind it, it should always trigger click on <ion-item> not in <ion-item-options>
duplicate of https://github.com/driftyco/ionic/issues/6981

> Sliding list should not auto close on option's click. At least, it should be configurable.
good catch! fixed! ec6615d

BTW, next time please report each issue one at a time, creating one issue for each bug. Thanks!
