### ISSUE TITLE
can't access to globals variables

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic#8484]
hello, why I don't have access to global.scss in ionic 2?
I mean when I defined button with primary color it's not change the color to primary color, why is that?
i checked the global page exist.

in addition i have weird error from the morning.
I get this error

> Uncaught TypeError: Cannot read property 'element' of undefined

when I press on login button in my ionic2 and angular2 app. I tried to look on variable that not intialize or function but I didn't find at all.

this is my login function page

> import { Component } from '@angular/core';
import { NavController,ViewController } from 'ionic-angular';
import { Storage} from '@ionic/storage';

//components
import { MyService } from '../../providers/my-service';
import { AdminPage } from '../admin/admin';

/*
  Generated class for the ModalPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-modal-page',
  templateUrl: 'modal-page.html',
  providers:[MyService]
})
export class ModalPage {

  data:any;
  public local: Storage;
  private mydata:any;

  constructor(public navCtrl: NavController,private viewCtrl: ViewController,private service:MyService) {
    this.data={};
    this.data.username="";
    this.data.password="";
    this.local=new Storage();

  }

  login(){
    let username = this.data.username;
    let password = this.data.password;
    let data  = JSON.stringify({username, password});
    this.service.postLogin(data)
        .subscribe(data => {
          this.mydata = data;
          this.local.set('username', this.mydata[0].name);
          this.local.set('token', this.mydata[0].token);
          this.viewCtrl.dismiss();
        }, error =>{
          console.log(error);
        })
  }
  dismiss(){
    this.viewCtrl.dismiss();
  }

}

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You can change the colors [here](https://github.com/driftyco/ionic2-app-base/blob/master/src/theme/variables.scss#L25). Also, regarding your second issue i would recommend asking around on our [forum](https://forum.ionicframework.com).
