### ISSUE TITLE
Duplicated documentation for SocialShare

### ISSUE THREAD

**Issue by aldo-roman** [driftyco/ionic#8491]
We have two links for SocialShare native plugin

http://ionicframework.com/docs/v2/native/social-sharing/
http://ionicframework.com/docs/v2/native/Social%20Sharing/

It seems they are duplicated and we should only keep one of them.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#659

**Comment by jgw96** [comment]
Hello, since this is an Ionic native issue and not an ionic framework issue i have moved this issue to that repo. Thanks for using Ionic!
