### ISSUE TITLE
ng2-translate: No provider for TranslateLoader! 

### ISSUE THREAD

**Issue by ahmedelgendy** [driftyco/ionic#8493]
i am trying to add the provider for ng2-translate at app.module.ts with this code
`    provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [Http]
    })`
but i cant find "provide" function at angular/core
using ionic rc 
any help?

**Comment by davorpeic** [comment]
Yeah, I just fixed my issues with ng2-translate, follow tips posted in here and update to ng=transle 3.0.0, https://github.com/ocombe/ng2-translate/issues/218

**Comment by danbucholtz** [comment]
This was a bug in `ng2-translate`. It should be resolved now.

Thanks,
Dan
