### ISSUE TITLE
Error starting project: npminstall error

### ISSUE THREAD

**Issue by Fconstant** [driftyco/ionic#8497]
#### Short description of the problem:
I've tried to start a simple project on the new version of Ionic 2: 2.0.0.rc0
But the following error appeared:

```
X:\Desenvolvimento\Ionic>ionic start test blank --v2
Creating Ionic app in folder X:\Desenvolvimento\Ionic\test based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined
```

I've read other problems similar to mine, they said to update de npm to a 3.x or later version. I did it, but still the same error.
The node_modules folder is missing too.

When it does appear. I simply can't delete the project folder, because the Windows File System doesn't allow a huge directory names (Because inside the node_modules folder, there is a bunch of endless subfolders). And I can't use Linux right now.

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 10 Home x64
Node Version: v6.7.0
```

**Comment by Verean** [comment]
Have Git installed.

**Comment by Fconstant** [comment]
Thank you Verean. Worked for me

**Comment by sudotamm** [comment]
├── cordova@6.4.0
├── ionic@2.1.18
├── ios-deploy@1.9.0
├── ios-sim@5.0.13
├── npm@3.10.9
└── typescript@2.1.4
system version: MacOS 10.12.2 Sierra
git version 2.8.1
I aslo got this problem, my environment is above. All tool is newest. Git also installed. Can you tell me that how you solve this problem?
Thanks.
