### ISSUE TITLE
RC0 button ion-item remains "activated" after scroll finishes on android

### ISSUE THREAD

**Issue by alamusi** [driftyco/ionic#8499]
#### Short description of the problem:
on android `<button ion-item>` added **activated** class to the element at the beginning of the scrolling, but did not remove it when the scrolling is completed.

#### What behavior are you expecting?
the activated class to be removed after wards

**Steps to reproduce:**
1. create multiple `<button ion-item>` in a list
2. build to android
3. scroll

![button ion-item](https://cloud.githubusercontent.com/assets/15385359/19102607/7a6cce06-8a86-11e6-9feb-a738be56ebd2.gif)

the element is as follows
```
<button class="item-block item item-md activated" ion-item="" text-wrap=""><div class="item-inner"><div class="input-wrapper"><!--template bindings={
  "ng-reflect-ng-if": "true"
}--><ion-label class="label-md">
  <ion-grid no-margin="" no-padding="">
    <ion-row center="" class="margin-vertical-tiny">
      <ion-col no-margin="" no-padding="" text-left="" width-50="">
        <h2>
          <!--template bindings={
  "ng-reflect-ng-if": "false"
}-->
          Other
        </h2>
      </ion-col>
      <ion-col no-margin="" no-padding="" text-right="">
        <span>
          <ion-icon name="pin" role="img" class="icon-md ion-md-pin" aria-label="pin" ng-reflect-name="pin"></ion-icon>
          Sutherland Shire &nbsp;
        </span>
      </ion-col>
    </ion-row>

``` 

**Which Ionic Version?** 1.x or 2.x
2.0RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by manucorporat** [comment]
This should be fixed in rc1
https://github.com/driftyco/ionic/commit/d893441335dc4c39ab87993e3304ac31e4c7e930
