### ISSUE TITLE
overflow-scroll="true" causing click delay on iOS

### ISSUE THREAD

**Issue by antonfire** [driftyco/ionic#8500]
#### Short description of the problem:

When adding overflow-scroll="true" to ion-content in iOS10 performance is drastically improved for a Facebook feed type view (no more stuttering), the problem is that when you scroll down and release (leaving the momentum scroll to keep taking the scroll down as it decelerates) then tap while it is still moving, the tap event registers at the point the finger was released (now out of view) and not where is being tapped (in view) I can't use collection repeat because the list cards I'm displaying vary in height depending on their content. I tried to implement my own click prevention starting with on-scroll and ending with on-scroll-complete but on-scroll-complete does not fire with overflow-scroll="true"
#### What behavior are you expecting?

Taps to register at the point in the dom at which they are made or for tap events to be disabled until the iOS momentum scroll finishes.

**Steps to reproduce:**
1. Have a ion-content element with attribute overflow-scroll="true" holding a ng-repeat list 
2. Flick scroll so iOS momentum scrolling occurs
3. Tap a list element and see which one registers the tap event

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which Ionic Version?** 1.x or 2.x

1, see below.
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.1.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#87
