### ISSUE TITLE
build problem ionic2 Rc0

### ISSUE THREAD

**Issue by 791060555** [driftyco/ionic#8501]
问题
1.你们的新版本2.0.RC0,打包并不是很好用，修改文件后，编译重新加载要4-5秒，比以前慢很多，
2.并且现在编译全写在ion-script里面，扩展是不是很不方便，
3.还有现在书写的模版html全部压缩在js里面，会不会影响第一次加载速度
4.还有现在所有版本的css在一起，会不会影响初始化加载速度,如果我只想用ios的css样式，其它版本的css样式是不是多余，影响初始化加载
5.现在编译后的在chrome里面调试不是很方便，现在好像不支持typescript调试了，ionic2-beta版本支持
6.以前的你们跨域调试接口是有问题的，不知道你们解决没有

problem
1. Your new version 2.0.RC0, packaging is not very easy to use, modify the file, the compiler reload to 4-5 seconds, much slower than before,
2. And now all written in the ion-script compiler inside, the expansion is not very convenient,
3. There are now writing all the compressed html template js inside, will not affect the speed of the first load
4. Now there are all versions of the css together, will not affect the initial loading speed, if I just want to use ios css style, other versions of the css style is not redundant, affecting the initial load
5. Now in the chrome after debugging inside the debugging is not very convenient, and now does not seem to support typescript debugging, ionic2-beta version support
6. Before you cross-domain debugging interface is a problem, do not know if you solve no

**Comment by danbucholtz** [comment]
I am going to track this issue here since it's a duplicate, @791060555.

https://github.com/driftyco/ionic-app-scripts/issues/96

Thanks,
Dan
