### ISSUE TITLE
Barcode plugin missing in iOS

### ISSUE THREAD

**Issue by Xenoage** [driftyco/ionic#8505]
I installed the barcode plugin like described on https://ionicframework.com/docs/v2/native/barcode-scanner/ . Up to now, this worked with the Ionic beta versions.

In **Ionic 2.0.0 RC 0** , after building using the `ionic package` online service and running on iOS, I get the following error: `plugin_not_installed`

**Comment by ramonornela** [comment]
Close and move to ionic-native

Thanks
