### ISSUE TITLE
Date pipe doesn't work on iOS (Ionic 2 RC.0)

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#8509]
I thought date pipes were fixed with Angular RC2 but seems that there is still a problem.

According my tests, date pipes doesn't work on iOS (at least when I emulate an iPhone 6 iOs 9.1).

Note: In local Safari, version 10, works fine. Chrome and Android too.

I could reproduce the problem with the starter app.

in about.ts added a new Date

      test:Date;

       constructor(public navCtrl: NavController) {
         this.test = new Date();
       }

in about.html added the pipe:

     {{test | date: 'dd'}}

Unfortunately, didn't found any stacktrace informations in Xcode.

Thx in advance for a fix or help :)

**Comment by danbucholtz** [comment]
This is known Angular issue.

https://github.com/angular/angular/issues/3333

I'm going to close this for now.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
Thx for the feedback, I thought wrongly that it was finally fixed in the last version of Angular2.

Well then, in the meantime, I wrote my own directive using momentjs.

**Comment by thielCole** [comment]
@danbucholtz The workaround for this issue was supposed to be to add a polyfill for this. It seems that rc0 comes with a built in polyfill to solve this issue, but it still isn't solved. Is the baked in polyfill

      <script src="build/polyfills.js"></script>

ready? Or is it missing the internationalization stuff? The error I am seeing is 

    EXCEPTION: Can't find variable: Intl

But on previous builds with Beta.11 I was able to solve this by providing a custom polyfill.

**Comment by danbucholtz** [comment]
@jgw96, what do you think of this?

Thanks,
Dan

**Comment by mragwa** [comment]
The same problem here any solution ?

**Comment by thielCole** [comment]
@mragwa I used this polyfill as a workaround.

```
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script> 
```

**Comment by zefrench** [comment]
The problem still here if the app is launched with no network.
So how to install these intl files in the app ?

**Comment by mragwa** [comment]
The problem still here, you can also check it on Safari browser, 
I solved it by changing the date format to "m/d/y H:m:s" so it works fine for now.
