### ISSUE TITLE
navCtrl.getActive().component.name returns "t" in RC0

### ISSUE THREAD

**Issue by prantikv** [driftyco/ionic#8512]
Getting the component name or using various methods give the letter **t** in return.
This has been seen in the **Tabs** template.
**Note that this only happens on the device. It works fine in the browser.**

```
    console.log(this.navCtrl.getActive().component.name);
    console.log(nav.getActive().component.name);
    console.log(this.tabRef.viewCtrl);
```
#### What behavior are you expecting?
Name of the component or view is expected

**Steps to reproduce:**
1. Create a tabs project. 
2. Add a button to log the current component name
3.  Build for android and run on device or emulator

**Which Ionic Version?** 1.x or 2.x
Ionic 2 RC0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually expected due to our AoT compiling that happens when doing a prod build. Ionic does a prod build when doing `ionic run android/ios`, `ionic emulate android/ios` or `ionic build android/ios`. All of the methods will still work the same as the name, which is `t` in this case, still refers to the same component.

**Comment by omgalbert** [comment]
Hi @jgw96 ,

What I should do to get the name property, instead t, or e, or r property?

**Comment by gulullu** [comment]
What I should do to get the name property, instead of t, or e, or r property?

**Comment by derasmus** [comment]
+1

**Comment by rdlabo** [comment]
We can get component-name with "this.nav.getActive().id"  in AoT.
not use "name".

**Comment by chandumunna** [comment]
its working "this.nav.getActive().id" in AoT.
thanks

**Comment by bedej** [comment]
This doesn't seem to work as of currently (ionic CLI 3.18.0, ionic-angular 3.7.1). "this.nav.getActive().id" returns a shortened string like "tn-4", not the original component name. I'm using this method in production to send telemetry about view navigation, so the original component name is what I'm looking for. Is there any other way to obtain it?

**Comment by ThalesMatoso** [comment]
+1

**Comment by rphovley** [comment]
We are also seeing this issue as it is actually reporting the name as blank when running `ionic cordova run browser --prod.` With the name being reported as mentioned before without the `--prod`

**Comment by xyboox** [comment]
+1

**Comment by matteobattista** [comment]
+1
Could be very useful to have component name also in "ionic build --prod"!

**Comment by alaordev** [comment]
+1 plz....

**Comment by GREPY** [comment]
If you need name just to compare with specific page / component, you can copare active component with that component directly:
`let activeView = this.navCtrl.getActive(); if (activeView.component == ConversationPage) { }`
as ruben0909 mentioned [here](https://github.com/ionic-team/ionic/issues/8814). It helped me a lot.
