### ISSUE TITLE
dynamic routes

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#8513]
we have one of our web app in angular 1 having dynamic routes(https://github.com/angular-ui/ui-router/issues/2265), where after login we make a call to api to get list of states.

something like can be achievable by angular 2 router but how can i get it work with Ionic 2 Routing
It would be great to have this feature.

Any help

thanks

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are currently working on the docs for our router, in the meantime i would suggest you ask this question on our [forum](https://forum.ionicframework.com).
