### ISSUE TITLE
ion-datetime scroll is very slow

### ISSUE THREAD

**Issue by fathyb** [driftyco/ionic#8515]
#### Short description of the problem:
When using ion-datetime scroll is very slow especially, on Android

**Steps to reproduce:**
1. Use ion-datetime or the plunker below
2. Scroll
3. Look at logs

It's worse on Android because of Cordova logging to ADB on each console.log.

When looking at the console when can see the component logging at each movement, here is the responsible code at src/components/picker/picker-component.ts@l233
```javascript
console.log(`decelerate y: ${y}, velocity: ${this.velocity}, optHeight: ${this.optHeight}`);
```

**Which Ionic Version?** 2.x

#### Example of the issue

http://plnkr.co/edit/7gBqdyNSQJWdfPNws2bq?p=preview

![image](http://g.recordit.co/h71ZUjjv2Y.gif)

**`ionic info`**:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by rodriguesgm** [comment]
seems to be the same problem of #6613 
I used the https://ionicframework.com/docs/v2/native/Date%20Picker/ instead of it. It has a better ux.

**Comment by fathyb** [comment]
I don't think it the same issue, the problem is not about the virtual scroll continuing to scroll but the performance issues due too the excessive logging. I already use native picker on iOS and Android but I'm using Ionic on browser too. If I disable logging as mentioned in the pull request it works pretty well.

**Comment by fathyb** [comment]
Fixed by https://github.com/driftyco/ionic/commit/713e2a1a33ded9dd238a3babe16db72c2f751741

Please mark issue as resolved
