### ISSUE TITLE
dismiss modal second time fails

### ISSUE THREAD

**Issue by CooleyGit** [driftyco/ionic#8519]
Converting beta.11 app to rc.0 getting: Uncaught TypeError: Cannot read property 'remove' of null

I have a modal with a form when the form is submitted and returned success I dismiss the modal it works first time but fails if I repeat the action. 

Looks like it could be same as #8408

**Comment by manucorporat** [comment]
@CooleyGit not the same bug. but this one was already fixed: https://github.com/driftyco/ionic/commit/d5f71a448dd8724a97e589a94d974d84248c477f

**Comment by CooleyGit** [comment]
Yup just updated to nightly looks gd thanks.
