### ISSUE TITLE
Update the plunkr template for ionic 2  issues

### ISSUE THREAD

**Issue by amreladawy** [driftyco/ionic#8521]
In order to create plunker samples with issues reported, can you please update the link to plunker template to the latest version?

**Comment by mirkonasato** [comment]
I was trying to create a plunk with rc.0 earlier today, but got stuck at `Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config)`: [plnkr.co/edit/566dzwCimAhjUmFt3Oku?p=preview](plnkr.co/edit/566dzwCimAhjUmFt3Oku?p=preview)

**Comment by mirkonasato** [comment]
This seems to work: http://plnkr.co/edit/ZsoPeE?p=preview

**Comment by jgw96** [comment]
Hello all! The plunker link has since been updated to RC. Thanks.
