### ISSUE TITLE
IonSelect interface action-sheet displays as alert interface

### ISSUE THREAD

**Issue by rafaelss95** [driftyco/ionic#8522]
I have the following `select`:

```
<ion-select interface="action-sheet" cancelText="Cancelar" okText="Selecionar" [(ngModel)]="selectedYear" (ionChange)="getItems()">
  <ion-option *ngFor="let year of years" [value]="year">{{year}}</ion-option>
</ion-select>
```

The problem is that the _property_ interface isn't working as in the [docs](http://ionicframework.com/docs/v2/api/components/select/Select/#input-properties) (it happens, for me, in beta.11 also), in other words, it keeps displaying as alert.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you provide a repo that we can use to reproduce this issue?

**Comment by rafaelss95** [comment]
Ups, it was my fault. I didn't log at console before posting this issue.

The console is really clear about this:

> Interface cannot be "action-sheet" with more than 6 options. Using the "alert" interface.

I just reduced the number of options and it works really well.
