### ISSUE TITLE
feat: Android translucent status bar

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8526]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>Android translucent status bar it's one of the biggest features that missing to Ionic 2.
In the next video you can see 2 native apps with translucent status bar and Ionic app with 1 color status bar:
https://drive.google.com/file/d/0B_2AM8ZhXhE9T1QwWmpNTDlVV2M/view?usp=drivesdk
I think it's very important to have translucent status bar in android apps.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually something that is handled on the cordova side of things by the [status bar plugin](https://github.com/apache/cordova-plugin-statusbar).
