### ISSUE TITLE
feat: Clickable block with ripple

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8527]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Video to example in native app: https://drive.google.com/file/d/0B_2AM8ZhXhE9M1p6d2hubGlTWkk/view?usp=drivesdk
Cluckable block with ripple (or any other click effect in other platforms)
It's good feature and i think you can put it in the missions list after ionic 2 final publish</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually already possible with this syntax `<button ion-item></button>`. This gives you a clickable item (with ripple) that can be used in lists, menus etc etc.

**Comment by MatanYed** [comment]
@jgw96 It's very hard to customize it in some cases. I don't think so it's good idea to use it as block button. In addition in iOS it adds arrow right icon..
