### ISSUE TITLE
feat: Expended toolbar

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8528]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>It's good feature, you can see that in many famous and successfuls native apps: https://drive.google.com/file/d/0B_2AM8ZhXhE9aGthRHZxT1gzd2s/view?usp=drivesdk</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
