### ISSUE TITLE
feat: Tap sound in Android

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic#8529]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I am not sure how it works in other platforms but in Android when you tap button, link, or any other clickable components (tabs, select...) there is tap sound (if you are not on silence mode).
It's could be good if ionic 2 will have that as default. It can make app feels alof more alive and native.
I added that to my ionic 1 app and it makes alot of difference in UX.

The plugin to this is cordova-device-feedback.
There is 2 problems to add this plugin manually:
It is not written in typescript
And you need to add event lisenter to every click and check if the click in on clickable component.

Try to add it as default, its important feature.</span>

<span is-issue-template></span>

**Comment by John-Luke** [comment]
I open a [issue](https://github.com/driftyco/ionic-native/issues/648) in ionic native repo to add this plugin, please close that issue

**Comment by MatanYed** [comment]
@John-Luke but it won't be a perfect solution just to add it to ionic native. Its should be part of ionic core by my opinion

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#74
