### ISSUE TITLE
Ionic 2 release migration -> provider error

### ISSUE THREAD

**Issue by danielgolub** [driftyco/ionic#8530]
#### Short description of the problem:
When I try to create a page component which includes a provider in it, the page is blank and this error is shown: Uncaught Error: Can't resolve all parameters for BackgroundPicturePage: (LoadingController, AlertController, NavController, ?, TranslateService).

Here are my files:

_app.module.ts:_
```
import { User } from '../models/User';

......

providers: [
    User,
],
```

_background-picture.component.ts:_
```
import {Component} from '@angular/core';
import {User} from '../../models/User';

@Component({
  templateUrl: 'background-picture.html',
})
export class BackgroundPicturePage {
  constructor(
    public loadingCtrl: LoadingController,
    public alertCtrl: AlertController,
        public nav: NavController,
        public user: User,
        public translate: TranslateService
    ) {
    }
}
```

_User.ts:_
```
import {Injectable} from '@angular/core';

@Injectable()
export class User {
 ... logic ...
}
```

**Which Ionic Version?** 1.x or 2.x

2.0 RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 8.0 Build version 8A218a 
```

**Comment by davorpeic** [comment]
Whats that "?" in (LoadingController, AlertController, NavController, **?**, TranslateService), can you try remove it?

**Comment by danielgolub** [comment]
The "? in the constructor is actually the provider (User). When I try to remove the User provider from the page component, now this error disappears, but another page has the same kind of error (`Uncaught Error: Can't resolve all parameters for LoginPage: (ModalController, AlertController, LoadingController, TranslateService, NavController, ?).`)

**Comment by davorpeic** [comment]
Hm, providers are moved from components to module, can you share code from that page that gives an error?

**Comment by danielgolub** [comment]
Yes, I declared the User provider in the module, not in the component, as I stated in the code example.

**Comment by davorpeic** [comment]
Well, you fixed the error on one page, remove `?` on another to fix it

**Comment by danielgolub** [comment]
No, both of the pages had the User provider in it's constructors (which is represented as **?** in the console error message).
The console first showed this error on one page, when I removed the provider from it, and then the same error appeared on the second page.

* note: I don't inject to the constructor a question mark, the console shows a question mark, in the actual code it's the User provider.

**Comment by davorpeic** [comment]
Can we see User service and the page where are you injecting it?

**Comment by danielgolub** [comment]
I already included it in the question..
![image](https://cloud.githubusercontent.com/assets/1869601/19192643/959c246c-8caf-11e6-8480-cc412e65f82e.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
