### ISSUE TITLE
Ion-List "vertical-spacing" on Items (Ionic 2 RC.0)

### ISSUE THREAD

**Issue by baltazaroliveira** [driftyco/ionic#8531]
Hello,

after upgrading to IONIC 2 RC.0 the lists have a "vertical-spacing" (in the BETA don´t have). 

It is possible to make the "old style"?

![ionic2 list](https://cloud.githubusercontent.com/assets/953742/19150427/b088234e-8bbe-11e6-8001-7c3e74c445a2.png)

Thanks
Baltazar

**Comment by manucorporat** [comment]
@baltazaroliveira Can you share the markup you are using?

please next time, try to submit the issue following the imposed structure.

**Comment by baltazaroliveira** [comment]
Ok. Sorry! :-)

All my ion-lists are now like that! I preferer without vertical spaces (like in BETA).

My code is this

```
<ion-content padding>
  
  <ion-list *ngFor="let assunto of assuntos" (click)="SeleccaoAssunto_click(assunto)">
    <ion-item>
      {{assunto.id_assunto}} - {{assunto.descr_assunto}}
    </ion-item>
  </ion-list>

</ion-content>
```

**Comment by manucorporat** [comment]
@baltazaroliveira you are creating a list for each item:

your markup should look like this:

```html
<ion-content padding>

  <ion-list>
    <button ion-item *ngFor="let assunto of assuntos" (click)="SeleccaoAssunto_click(assunto)">
      {{assunto.id_assunto}} - {{assunto.descr_assunto}}
    </button>
  </ion-list>

</ion-content>
```

**Comment by baltazaroliveira** [comment]
Ok. One thing learned today! :-) Thanks!

**Comment by manucorporat** [comment]
You are welcome :)
