### ISSUE TITLE
class content-md goes away if I set the class manually through binding

### ISSUE THREAD

**Issue by dgroh** [driftyco/ionic#8532]
#### Short description of the problem:
I need to write specific layout for android in `ion-content` (`content-md` class), but when I bind a class property, the `content-md` class is no longer available.

#### What behavior are you expecting?
I want to have `content-md` class in `ion-content` even if I bind a class to ion-content

**Steps to reproduce:**
1. set a class like this in `ion-content` -> `<ion-content class="{{myProperty}}"></ion-content>`

```
<ion-header class="{{subject}}" no-shadow>
    <header-content-component #headerContent [title]="subject" [content]="content"></header-content-component>
</ion-header>
<ion-content class="{{subject}}">
    <search-result-component *ngIf="headerContent.toolbarActive">
    </search-result-component>
    <card-main-component [title]="breadcrumb" [description]="title"></card-main-component>
    <card-description-component *ngIf="subject!=='english'" title="WAS FINDE ICH HIER?" description="Hier sind die Themen für dein Abitur"></card-description-component>
    <card-description-component *ngIf="subject==='english'" title="WHAT CAN I FIND HERE?" description="Here are the topics for your English Abitur"></card-description-component>
    <ion-list no-lines>
        <button ion-item *ngFor="let topic of models" (click)="selectTopic(topic)">
            {{topic.title}}
        </button>
    </ion-list>
</ion-content>
```

**Other information:** 

There is already **md** class in `<ion-app>` so I don't see any reason for specifying more classes like `header-md`, 'content-md' and so on. My suggestion would be to remove it at all.

Another interesting point is, that when I set the class not via binding, like for example:

`<ion-content class="className"></ion-content>` I get the following output:

`<ion-content class="className content-md"></ion-content>` 

So, something is not correct I guess.

**Which Ionic Version?** 2 RC0

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Node Version: v4.6.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Could you provide a repo that we could use to reproduce this issue?

**Comment by dgroh** [comment]
Sorry, this should be way to easy to reproduce, just add a class dinamically to an `ion-content` for instance.

In the **TypeScript**:

`public propertyName: string;`

In the **HTML**:

`<ion-content class="{{propertyName}}"></ion-content>`

This is going to remove the mode class from `ion-content`

**Comment by dgroh** [comment]
If this still does not help I can try to create a repo, but due to the drastic change from beta to RC0, we are in a rush as we have a release in december.

**Comment by manucorporat** [comment]
In angular 2 you should not use string interpolation for that, use ngClass instead:

```
<ion-content [ngClass]="propertyName">
```

**Comment by dgroh** [comment]
Thanks that is it.
