### ISSUE TITLE
Invalid name: "@ionic/app-generators"

### ISSUE THREAD

**Issue by laurenkyla** [driftyco/ionic#8536]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:

I tried to update ionic because of an IOS 10 issue and I'm getting the following error: 

Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Invalid name: "@ionic/app-generators"

And Ionic won't install. 

#### What behavior are you expecting?

**Steps to reproduce:**
1. sudo npm install -g ionic

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by mhartington** [comment]
Not able to replicate this. 

The package in question does exist 

https://www.npmjs.com/package/@ionic/app-generators

Can you try again?

**Comment by laurenkyla** [comment]
Strange I tried again and still seeing the same eror. Never had any problems before installing or updating ionic. Anything else I could try?

**Comment by menzow** [comment]
I'm having the same problem.

```
$ npm -v
2.14.12
$ sudo npm install -g ionic
npm ERR! unpack Could not read data for @ionic/app-generators@0.0.3
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by mhartington** [comment]
@laurenkyla could you do `npm uninstall -g ionic` then try to install again. 

@menzow same for you. But you need to update your npm and node version. You need npm3

**Comment by laurenkyla** [comment]
Thanks but uninstall doesn't do anything as it seems to have gotten far enough in the install to remove the version I had so I now have no ionic installed and I can't install it:

$ ionic
-bash: /usr/local/bin/ionic: No such file or directory

**Comment by laurenkyla** [comment]
I managed to solve the issue by doing the following:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

Thanks

**Comment by jjoe64** [comment]
seems to be a bug of specific npm version.
https://github.com/npm/npm/issues/14104

after installation of latest npm it worked for me:
`sudo npm install -g npm@latest`

**Comment by keshvari** [comment]
jjoe64 solution worked for me

**Comment by mweimerskirch** [comment]
Had the same issue. Changing permissions didn't help. Updating npm as suggested by jjoe64 worked.

**Comment by frayeralex** [comment]
sudo npm install -g npm@latest help me!

**Comment by 4HisGlory** [comment]
sudo npm install -g npm@latest was the solution for me. Thanks @appsthatmatter
