### ISSUE TITLE
Unit tests fail because of usage of Loading-/ToastController

### ISSUE THREAD

**Issue by ivaro18** [driftyco/ionic#8539]
#### Short description of the problem:

**note: my tests are working fine without a LoadingController**
Unit tests fail because, use of LoadingController. This is caused because the LoadingController cannot be `provided` it seems. This issue would also relate to ex. the NavParams. Just how would one mock them/use them in TestBed 

#### What behavior are you expecting?
That the tests will execute.

**Steps to reproduce:**
1.  Clone marcoturi's https://github.com/marcoturi/ionic2-boilerplate 
2.  Setup a component with a LoadingController in the constructor
3.  Try to create an instance with angular's `TestBed`. 

```
TestBed.configureTestingModule({
    declarations: [EventsPage],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    providers: [
      {provide: APICaller, useValue: mockAPICaller},
      {provide: NavController, useValue: mockNavController },
      {provide: LoadingController, useValue: ???????}, //it seems like everything I try to enter here fails.
    ],
    imports: [FormsModule]
  });
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

http://stackoverflow.com/questions/39897625/ionic2-rc0-testing-mocking-ionics-toast-loadingcontroller 
 

**Which Ionic Version?** 1.x or 2.x
2.1.0

#### Plunker that shows an example of your issue
*don't know how to configure Plunkr into running jasmine tests.*

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.5.0

```

**Comment by ivaro18** [comment]
edit: `NavParams` is able to stay using default NavParams. When using `useClass: LoadingController` the compiler complains about `App! being undefined`

**Comment by danbucholtz** [comment]
If you're injecting LoadingController, you also need to inject anything that it depends on, or create Mocks.

I'm going to close this for now as this is more of a question than an issue.

Thanks,
Dan

**Comment by ivaro18** [comment]
So how would you mock the App it asks for? Ionic's mockIonicApp doesnt work
