### ISSUE TITLE
[Solution] Ionic RC0, forms control and validation

### ISSUE THREAD

**Issue by davorpeic** [driftyco/ionic#8541]
#### Short description of the problem:
So I was following this great tutorial (http://blog.thoughtram.io/angular/2016/06/22/model-driven-forms-in-angular-2.html) from Pascal on how to build model driven forms using FormBuilder in latest RC0 as I was using it in Beta11, but soon I was stopped with this error
````
ORIGINAL EXCEPTION: No value accessor for form control with name: 'firstname'
```
I'm using (I think I'm) all by the book, and this is in short what I have in
app.module.ts
````
import { ReactiveFormsModule } from '@angular/forms';
...
@NgModule({  
  imports: [
      ReactiveFormsModule
]
...
```

login.ts
```
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
export class LoginPage implements OnInit{
    registerForm:FormGroup;
    constructor(private formBuilder: FormBuilder) {}
    ngOnInit() {
        this.registerForm = this.formBuilder.group({
            firstname: ['', Validators.required],
            lastname: ['', Validators.required]    
        });
    }
}
```
login.html
```
<form [formGroup]="registerForm">
        <label>Firstname:</label>
        
       <input type="text" [(ngModel)]="test" formControlName="firstname" style="border:solid 1px #000;">
        
        <ion-input [(ngModel)]="test" type="text" formControlName="firstname"> </ion-input>

        <label>Lastname:</label>
        <input type="text" formControlName="lastname" style="border:solid 1px #000;">
       <button type="submit">Submit</button>
    </form>
   
    <h2>{{registerForm.valid}}/{{test}}</h2>
```

**SOLUTION**
```

 <ion-input [(ngModel)]="test" type="text" formControlName="firstname" ngDefaultControl> </ion-input>
```
#### What behavior are you expecting?
Use FormBuilder validations with custom form elements from Ionic

**Steps to reproduce:**
1. Use example markup posted above

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
http://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-no-value-accessor-for-form-control-with-unspecified
https://github.com/angular/angular/issues/9230

**Which Ionic Version?** 1.x or 2.x
Ionic 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! After reviewing I am going to close this issue as it seems to be an Angular bug and not an Ionic bug.

**Comment by babyjazz** [comment]
It works on browser testing, but it doesn't work when build or emulate

**Comment by davorpeic** [comment]
Hey @babyjazz, I removed `test` variable from my example, it was giving you that error `Property 'test' does not exist on type 'ContactPage'.` please remove {{test}} from my example and it should build for device/emulator.

d
