### ISSUE TITLE
Proposal: Add mode agnostic css class

### ISSUE THREAD

**Issue by alan-agius4** [driftyco/ionic#8545]
We'd like to propose a bit of a change in the components base class. I kinda did a bit of a concept. And i am willing to go through all the components and implement this.

https://github.com/alan-agius4/ionic/commit/5b3b5a250a034a6ea97d2ba21d0ec32d3d004475

basically at the moment for a component a class is added according to the mode set ex: `.item-md`, `.item-wp`, `.item-md`. However, if you'd like to override or add some for all modes it would be quite useful to have a mode agnostic class that you can target ex `.item.`

To be discussed with @adamdbradley and @brandyscarney.

**Comment by zakton5** [comment]
Agreed, I've had to adjust many styles because of mode-specific classes. As of now, it just causes us to make more CSS

**Comment by zakton5** [comment]
Related, most likely duplicate: #8533
