### ISSUE TITLE
Unable to add MQTT.js to Ionic 2 project (RC)

### ISSUE THREAD

**Issue by bushev** [driftyco/ionic#8548]
Hello there!

I'm upgrading my application to Ionic 2 RC. I got the following error on my application bootstrap:

```
inherits_browser.js:9 Uncaught TypeError: Cannot read property 'prototype' of undefined

at Object.inherits (inherits_browser.js:5)
    at _stream_writable.js:46
    at main.dev.ts:5
```

Comment ([readable-stream](https://github.com/nodejs/readable-stream/issues/237#issuecomment-252079344)):
> don't use readable stream with rollup, it doesn't work because rollup doesn't support all of commonjs modules, use the node builtins package and just require streams

#### What behavior are you expecting?

Project has started successfully.

**Steps to reproduce:**
1. npm i mqtt
2. Add MQTT.js to ionic-conference-app, like I did [here](https://github.com/bushev/ionic-conference-app/commit/9d37b7a08088b00886f99886d9ab2746cdcceb68)
3. ionic serve

--

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by ramonornela** [comment]
See steps in http://ionicframework.com/docs/v2/resources/third-party-libs/

Thanks

**Comment by bushev** [comment]
The same result. I have switched to [web-mqtt-client](https://github.com/orbitbot/web-mqtt-client), it works fine.

Thanks!

**Comment by stouhbi** [comment]
<hi bushdev,
I am having trouble using web-mqtt-client on my ionic app. any special thing to add ?
