### ISSUE TITLE
ProdMode: true seems not work on RC0

### ISSUE THREAD

**Issue by rafaelss95** [driftyco/ionic#8551]
#### Short description of the problem:
I'm trying to enable production mode, as documented [here](https://ionicframework.com/docs/v2/api/config/Config/) but it seems not work.

I put in app.module.ts the following:

```
@NgModule({
  declarations: [
    MyApp,
    ...
  ],
  imports: [
    IonicModule.forRoot(MyApp, {
      backButtonText: 'Voltar',
      prodMode: true
    }),
    ChartsModule
  ],
  bootstrap: [IonicApp],
  ...
})
```
PS: I already tried to import `enableProdMode`, as below but nothing happens, I keep getting the following message 

> Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

`import { NgModule, enableProdMode } from '@angular/core';`

#### What behavior are you expecting?
Enable the production mode.

**Which Ionic Version?** 1.x or 2.x
2.x RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.3.1

**Comment by manucorporat** [comment]
aren't you calling enableProdMode()?

```
import { NgModule, enableProdMode } from '@angular/core';

enableProdMode();
```

**Comment by rafaelss95** [comment]
Thanka for response.
That way works, but why not this?

I saw that option `prodMode` in docs.
`imports: [
    IonicModule.forRoot(MyApp, {
      backButtonText: 'Voltar',
      prodMode: true
    }),
    ChartsModule
  ]
`

**Comment by manucorporat** [comment]
@rafaelss95 right! I wanted to make sure `enableProdMode()` worked

Looks like, `prodMode` option was removed because the way the new NgModule works. I will go over this with my colleagues and get back to you.

**Comment by ghenry22** [comment]
could you update the docs to indicate how and where to enable prodmode now?  What file should the above suggested import and enable statement be in, and where in that file?  I have tried adding to app.component.ts but calling enableProdMode() in the constructur results in the app hanging, calling it anywhere after platform.ready results in cannot set prodmode after platform setup error.

**Comment by rafaelss95** [comment]
@ghenry22 Just put it in `app.module.ts`.

**Comment by ghenry22** [comment]
sure I can put the imports in but where would you place the enableprodmode() call in that file given the current ionic2 base layout for that file?

**Comment by mhartington** [comment]
You do not need to do anything for this anymore.

Production builds through app scripts will use the `main.production.ts` file which enables prodMode.

**Comment by rafaelss95** [comment]
@mhartigton, I thought I had to import it in `app.module.ts`..

**Comment by mhartington** [comment]
Nope, if you look at the main.prod.ts and the main.dev.ts

https://github.com/driftyco/ionic2-app-base/blob/master/src/app/main.prod.ts

https://github.com/driftyco/ionic2-app-base/blob/master/src/app/main.dev.ts

You can see that this is taken care of for you.

**Comment by rafaelss95** [comment]
Hmm, I saw it now, but what file or what should we modify to enable production?

**Comment by mhartington** [comment]
You do not need to do anything for this anymore.


It is automatically taken care of when you build for device.

**Comment by morrisonbrett** [comment]
Per my chat with @mhartington on Slack:

Production default:
`> ionic build`
`> ionic run`

Development default:
`> ionic serve`

And you can use `--dev` and `--prod` on each command.

e.g. `> ionic build browser --dev`.

**Comment by tonyawad88** [comment]
@mhartington when invoking ```ionic build android --release``` the artifacts generated have .js.map in them. Is this the right way to create a production build ?
