### ISSUE TITLE
ClickBlock stuck on Windows 10 Universal Application

### ISSUE THREAD

**Issue by petermetz** [driftyco/ionic#8554]
#### Short description of the problem:

Brand new starter app, doesn't accept clicks after app UI is loaded because the ClickBlocker never gets deactivated.
#### What behavior are you expecting?

ClickBlocker forfeits control of the application to the user.

**Steps to reproduce:**
1. ionic start fake-app --v2 --appname="Fake Application" --id="com.myfakedomainhaha.fakeapp" --sass --template="sidemenu"
2. ionic run windows
3. Try to click any of the buttons like 'Toggle Menu'
4. Experience the suffering.

**Which Ionic Version?** 1.x or 2.x
2.0-rc0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

---

 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

---

**Comment by petermetz** [comment]
It's probably unrelated, but I've accidentally discovered the following:
Building against x64 instead of AnyCPU makes the issue go away.
Maybe a race condition during app launch only happens with AnyCPU?

**Comment by jgw96** [comment]
Hello ,thanks for using Ionic! Is this still an issue with the latest version of Ionic 2?

**Comment by petermetz** [comment]
@jgw96 Unfortunately with the latest versions (ionic/cordova) the build doesn't work anymore.

What happens is that it tries to run the app, then asks for me to press enter on the command prompt which in turn doesn't accept any keyboard events.
So I end up in a situation where it's waiting for me to press enter but pressing enter does nothing.

The same behavior can be observed in command prompt and powershell as well.
If I run it as administrator, it tells me not to do that so that wasn't a viable option.



> PS C:\Users\petermetz\projects\fake-app> ionic run windows

Running 'run:before' npm script before run

> ionic-hello-world@ build C:\Users\petermetz\projects\fake-app
> ionic-app-scripts build

[18:11:48]  ionic-app-scripts 0.0.39
[18:11:48]  build prod started ...
[18:11:48]  clean started ...
[18:11:48]  clean finished in 15 ms
[18:11:48]  copy started ...
[18:11:48]  ngc started ...
[18:11:48]  copy finished in 396 ms
[18:11:49]  lint started ...
[18:11:52]  lint finished in 3.19 s
[18:12:18]  ngc finished in 30.00 s
[18:12:18]  webpack started ...
[18:12:27]  webpack finished in 9.50 s
[18:12:27]  uglifyjs started ...
[18:12:27]  sass started ...
[18:12:30]  sass finished in 2.95 s
[18:12:30]  cleancss started ...
[18:12:33]  cleancss finished in 2.72 s
[18:12:43]  uglifyjs finished in 15.33 s
[18:12:43]  build prod finished in 54.87 s
Running command: "C:\Program Files\nodejs\node.exe" C:\Users\petermetz\projects\fake-app\hooks\after_prepare\010_add_pla
tform_class.js C:\Users\petermetz\projects\fake-app


add to body class: platform-windows

Building project: C:\Users\petermetz\projects\fake-app\platforms\windows\CordovaApp.Windows.jsproj

        Configuration : debug
        Platform      : anycpu

  Patching 8.1 in prebuild event...

  Injected base.js reference to the www/index.html

  Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/www\/WinJS\/js\/base.js">\s*<\/script>)(\s*)/ from www/
index.html

  Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>
)(\s*)/ from www/index.html

  CordovaApp.Windows -> C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Windows_0.0.1.0_an
ycpu_debug_Test\CordovaApp.Windows_0.0.1.0_anycpu_debug.appx

  CordovaApp.Windows -> C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Windows_0.0.1.0_an
ycpu_debug.appxupload

  Your package has been successfully created.

Building project: C:\Users\petermetz\projects\fake-app\platforms\windows\CordovaApp.Phone.jsproj

        Configuration : debug
        Platform      : anycpu

  Patching phone-8.1 in prebuild event...

  Injected base.js reference to the www/index.html

  Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/www\/WinJS\/js\/base.js">\s*<\/script>)(\s*)/ from www/
index.html

  Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)
/ from www/index.html

  CordovaApp.Phone -> C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Phone_0.0.1.0_anycpu
_debug_Test\CordovaApp.Phone_0.0.1.0_anycpu_debug.appx

  CordovaApp.Phone -> C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Phone_0.0.1.0_anycpu
_debug.appxupload

  Your package has been successfully created.

Deploying windows package to device:
C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Windows_0.0.1.0_anycpu_debug_Test\CordovaA
pp.Windows_0.0.1.0_anycpu_debug.appx


Attempting to uninstall previous application version...


Attempting to install application...


Found package: C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Windows_0.0.1.0_anycpu_debu
g_Test\CordovaApp.Windows_0.0.1.0_anycpu_debug.appx


Found certificate: C:\Users\petermetz\projects\fake-app\platforms\windows\AppPackages\CordovaApp.Windows_0.0.1.0_anycpu_
debug_Test\CordovaApp.Windows_0.0.1.0_anycpu_debug.cer



Before installing this app, you need to do the following:


        - Install the signing certificate


Administrator credentials are required to continue.  Please accept the UAC prompt and provide your administrator passwor
d if asked.


Press Enter to continue...:

**Comment by rainmak33r** [comment]
Any news about the matter ?

**Comment by joshstrange** [comment]
@petermetz @rainmak33r For the cert I had to navigate to:

````
platforms/windows/AppPackages/CordovaApp.Windows10_0.0.1.0_x64_debug_Test
````

and right click on ````Add-AppDevPackage.ps1```` and choose ````Run with PowerShell````. Instead hitting enter in a normal prompt

**Comment by petermetz** [comment]
@joshstrange Thanks very much I wasn't aware of this new, extra step (previously it just worked).
@jgw96 Tested it with RC-4 and it works like a charm. Thanks for the heads up!
