### ISSUE TITLE
Problem with transparency

### ISSUE THREAD

**Issue by Marcolino179** [driftyco/ionic#8559]
If I put in transparency all the html elements in a view (ion-view) you see the previous view below. How can I remove the previous view?

**Steps to reproduce:**
1. Create a view A with all element trasparant (css: html, html *{background: transparent})
2. Create a view B with all element trasparant (css: html, html *{background: transparent})
3. State go from A to B
4. Go back to A

Cordova CLI: 6.3.1
Gulp version: CLI version 1.2.2
Gulp local: 
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0
OS: Node Version: v6.7.0

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to ask that you edit this issue and fill out the issue template please. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
