### ISSUE TITLE
[RC0] custom component dynamically enabled via *ngIf can't use [navPush]

### ISSUE THREAD

**Issue by alex-pl** [driftyco/ionic#8563]
Inside of a page I'm using a custom component that is dynamically enabled via `*ngIf` or `*ngFor`. The custom component contains a link to another page `<a [navPush]="myPage">` and throws:
> Expression has changed after it was checked. Previous value: 'undefined'. Current value: '#'.

<br>

The expression of `*ngIf` becomes `true` some time after `ngOnInit()` – for example after a network request, a setTimeout or inside ionViewWillEnter().

It seems like the delayed display and `[navPush]` together are causing the problem. The problem does _not_ occur when setting the expression of *ngIf to true inside ngOnInit() without a timeout.

<br>

The problem was introduced in Ionic 2 rc0.
Using Angular functions like `{{ myPage }}` instead of `<a [navPush]="myPage">` works.

<br>

### Custom Component

_component.html_

```HTML
<a [navPush]="myPage">MyPage</a>
```

_component.ts_

```TypeScript
import { Component } from '@angular/core';
import { SomePage } from '../some/page';

@Component({
    selector: 'my-component',
    templateUrl: 'component.html'
})
export class MyComponent {

    public myPage = SomePage;

    constructor() { }

}
```

### Page

_page.html_

```HTML
<ion-header>
    <ion-navbar>
        <ion-title>Page</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    <my-component *ngIf="isEnabled"></my-component>
</ion-content>
```

_page.ts_

```TypeScript
import { Component } from '@angular/core';

@Component({
    templateUrl: 'page.html'
})
export class Page {

    public isEnabled = false;

    ngOnInit() {
        // this would work
        // this.isEnabled = true;

        // this doesn't work
        window.setTimeout(() => {
            this.isEnabled = true;
        }, 2000);
    }

}
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I can reproduce this issue with your test case.

**Comment by manucorporat** [comment]
Fixed https://github.com/driftyco/ionic/commit/8b07e6c55b4e57fc16ba51df3b91f978616422ec
