### ISSUE TITLE
Ionic 2 not serving

### ISSUE THREAD

**Issue by JoshWilliams92** [driftyco/ionic#8565]
Error transforming app.component.ts with 'ion-compiler' plugin: rollup-plugin-typescript: Unexpected character. If this is valid Javascript, it's probably a bug in tippex.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are already aware of this issue and are working on a fix. Also we are discussing this issue here https://github.com/driftyco/ionic-app-scripts/issues/64 .
