### ISSUE TITLE
Toolbar button color attribute doesn't work if the toolbar has a lower value color that the button

### ISSUE THREAD

**Issue by Loutrinos** [driftyco/ionic#8566]
Buttons inside ion-toolbar will not have their color changed if the parent has a lower value of color.
#### Short description of the problem:

when adding the color="primary" to a button inside a toolbar with color="primary" the color assigned to the button is not the primary.
#### What behavior are you expecting?

To use the color attributes on the toolbar buttons abstract from the toolbar color value

**Steps to reproduce:**
1. Create a page with `ion-toolbar` and set `color="secondary"`
2. Add a ion-button inside the toolbar and set `color="primary"`
3. You should see a white texted button and not a primary colored one

**Which Ionic Version?** 
Ionic 2.0

The problem occurs cause of the way the toolbar colors and toolbar button colors are being generated:
https://github.com/driftyco/ionic/blob/master/src/components/toolbar/toolbar.ios.scss#L349

```
@each $color-name, $color-base, $color-contrast in get-colors($colors-ios) {
  @include ios-toolbar-theme($color-name, $color-base, $color-contrast);
  @include ios-bar-button-default($color-name, $color-base, $color-contrast);
  @include ios-bar-button-outline($color-name, $color-base, $color-contrast);
  @include ios-bar-button-solid($color-name, $color-base, $color-contrast);
}
```

The above code should be split to 2 loops to cater for the problem

```
@each $color-name, $color-base, $color-contrast in get-colors($colors-ios) {
  @include ios-bar-button-default($color-name, $color-base, $color-contrast);
  @include ios-bar-button-outline($color-name, $color-base, $color-contrast);
  @include ios-bar-button-solid($color-name, $color-base, $color-contrast);
}

@each $color-name, $color-base, $color-contrast in get-colors($colors-ios) {
  @include ios-toolbar-theme($color-name, $color-base, $color-contrast);
}
```

**Comment by Loutrinos** [comment]
@brandyscarney is there any feedback about this issue?

**Comment by brandyscarney** [comment]
@Loutrinos I haven't had a chance to look into this yet but I added it to a milestone to look at. Thanks!

**Comment by brandyscarney** [comment]
Thanks for the issue! I have fixed this and it will be in the rc.3 release. I released a nightly version if you'd like to try it out sooner: `ionic-angular@2.0.0-rc.2-201611100035`

```
npm install --save ionic-angular@nightly
```
