### ISSUE TITLE
css issue in Ionic2 RC

### ISSUE THREAD

**Issue by srikanth748** [driftyco/ionic#8569]
I started an app with sidemenu in Ionic2 RC . The folder structure is bit different from beta version.But the issue is I am unable to use theming feature .I decided to style pages individually but I am unable to implement the styling feature. can someone give an idea how to implement styling in RC version or how to use global feature from app.scss .Thnq

code ----html
` <ion-list>
      <ion-item *ngFor=" let result of sitelists" (click)="goToSelectSite(result.site_id)">
      <div class="siterecord">
       <div class ="l_image">
       <img  src= "http://s3.amazonaws.com/sinfoca_cache/{{result.logo}}" >
      </div>
      <div class = sitelist>
       <span class="sitename">{{result.site_name}}</span>
     <span class="sitesubdomain">{{result.site_subdomain}}</span>
     </div>
      </div>
    </ion-item>
    </ion-list>`
----
.siterecord{float:left;width:100%;border: 1px solid #f1f1f1;border-radius:5px;padding:5px;margin:5px 5px 0 0;

.l_image{img{float:left;max-height:35px;} }
.sitelist{float:left;
padding-left:15px;
letter-spacing: 0.1em;
font-weight: 100;
font-size:0.8em; 
.sitename{display:block; font-weight:400;color:#1995ad }
.sitesubdomain{display:block; font-weight:100;font-style:italic;color:#404040;;}
}
}

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can check the note about using selectors to scope css styles [here](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0) in our changelog.
