### ISSUE TITLE
NativePageTransitions problem

### ISSUE THREAD

**Issue by raul07kry** [driftyco/ionic#8572]
In IonicNative there is a NativePageTransition plugin, but use case is completely empty. I only found a way to use it with Ionic 1, but absolutly 0 information about Ionic 2 usage. C'mon guys, you could do better. Can anybody paste a simple code about usage of this thing? Thank you in advance.

**Comment by ramonornela** [comment]
Close move to ionic-native see note [ISSUE_TEMPLATE](../tree/master/.github/ISSUE_TEMPLATE.md)

> Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo https://github.com/driftyco/ionic-native

Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#669

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an Ionic Native issue I have moved this issue to the Ionic Native repo.
