### ISSUE TITLE
ionic2 upgrade to version RC.0, the compilation speed is very slow!

### ISSUE THREAD

**Issue by iraychen** [driftyco/ionic#8575]
Upgrade to version 2, the compilation speed is very slow, especially the lint and NGC compilation process.

The last upgrade（beta11）, the compiler speed has been greatly improved！

eg:

E:\Products\Source\MobileApp>ionic build android

Running 'build:before' npm script before build
> ionic-hello-world@ build E:\Products\Source\MobileApp
> ionic-app-scripts build
[19:41:17]  ionic-app-scripts 0.0.27
[19:41:17]  build prod started ...
[19:41:17]  clean started ...
[19:41:17]  clean finished in 141 ms
[19:41:17]  copy started ...
[19:41:17]  ngc started ...
[19:41:19]  lint started ...
[19:41:20]  copy finished in 3.22 s
[19:41:32]  lint finished in 12.33 s
[19:44:56]  ngc finished in 218.62 s
[19:44:56]  bundle prod started ...
[19:46:31]  bundle prod finished in 95.10 s
[19:46:31]  sass started ...
[19:46:33]  sass finished in 2.60 s
[19:46:33]  minify started ...
[19:46:33]  cleancss started ...
[19:46:33]  uglifyjs started ...
[19:47:18]  uglifyjs finished in 44.99 s
[19:47:18]  cleancss finished in 44.99 s
[19:47:18]  minify finished in 44.99 s
[19:47:18]  build prod finished in 361.48 s
Running command: "C:\Program Files\nodejs\node.exe" E:\Products\Source\MobileApp\hooks\after_prepare\010_add_platform_class.js E:\Products\Source\MobileApp

**Comment by numerized** [comment]
I'm agree with that maybe is possible for development to remove some minifying or other heavy tasks which are not important. ?

**Comment by morious** [comment]
Have you guys tried customizing the app scripts?
http://ionicframework.com/docs/v2/resources/app-scripts/

**Comment by prijindal** [comment]
Running the command with admin privileges had really great results

**Comment by ThomasKientz** [comment]
`npm run build --dev`  is working... Something similar with "` ionic build --dev`" would be great..

I found a workaround :

Manually edit the `build()` function in `node_modules/@ionic/app-scripts/dist/build.js` with the following :

```
function build(context, options) {
    context = config_1.generateContext(context);
    options = config_1.generateBuildOptions(options);
    var logger = new logger_1.Logger("build " + (options.isProd ? 'prod' : 'dev'));
    var promises = [];
    // dev build
    promises.push(buildDev(context, options));
    // if (options.isProd) {
    //     // production build
    //     promises.push(buildProd(context, options));
    // }
    // else {
    //     // dev build
    //     promises.push(buildDev(context, options));
    // }
    return Promise.all(promises).then(function () {
        // congrats, we did it!  (•_•) / ( •_•)>⌐■-■ / (⌐■_■)
        return logger.finish();
    }).catch(function (err) {
        logger.fail(err);
        return Promise.reject(err);
    });
}
```

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! So with the way app-scripts currently works when you run `ionic serve` it will serve the app in dev mode. This means that NGC will not run therefore making the build faster. When using `ionic run`, `ionic build` or `ionic emulate` app-scripts will use our prod build. This prod build runs NGC to do AoT compile which is why RC0 is so much faster than the previous beta releases. Unfortunately there is not a ton we can do to increase the speed of the prod builds as 95% of the time taken up is NGC, but we hope to improve this in the future.

**Comment by Screeze** [comment]
Is it normal that with ionic serve it still takes 20-40 seconds when I change a ts file until the change is compiled?

**Comment by guillefd** [comment]
Try updating the cli, I resolved it updating to Ionic RC1 and ionic-app-scripts to 0.0.36

**Comment by Screeze** [comment]
I did this before but it did not help

> Gulp version:  CLI version 3.9.1
> Gulp local:
> Ionic Framework Version: 2.0.0-rc.1
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> Ionic App Scripts Version: 0.0.36
> OS:
> Node Version: v4.4.5
>

**Comment by cleever** [comment]
@Screeze Try using the new build process with webpack 

`npm install @ionic/app-scripts@beta`

**Comment by zjhiphop** [comment]
I use the latest version of app-script, still very slow

```
[12:40:32]  lint finished in 5.11 s
[12:40:35]  transpile finished in 8.06 s
[12:40:35]  bundle started ...
[12:40:35]  copy finished in 8.13 s
[12:40:54]  bundle finished in 19.11 s
[12:40:54]  sass started ...
[12:40:57]  sass finished in 3.32 s
[12:40:57]  build dev finished in 30.51 s
[12:40:57]  watch ready in 30.64 s
```

info: 
```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by Weezlo** [comment]
Tried everything, but nothing worked.
I've finally updated app-scripts to 0.0.39 (was 0.0.36) and **there is a huge improvement** for both windows and Ubuntu. From ~30/40sec for every modification on a source file to ~10sec.
"ionic run" is also faster.
This worked for me: 
`npm install @ionic/app-scripts@latest --save-dev`

**Comment by Santoshah** [comment]
@Weezlo Great! AWESOME. Thanks alot.. It improved alot. Thank GOD and Thank @Weezlo :)
