### ISSUE TITLE
Embeded youtube video not working with ios

### ISSUE THREAD

**Issue by sriteja09** [driftyco/ionic#8576]
Embedded youtube player not working with ios but working with android.

**Comment by manucorporat** [comment]
Please, can you edit your issue following the provided template and provide adittional information of what is not working, source code and/or screenshots. Thanks!

**Comment by sriteja09** [comment]
Thanks alot it works with ios when i add this tag in config.xml

<allow-navigation href="*.youtube.com" />

**Comment by blueror815** [comment]
Embedded youtube player not working with ios.
I paste my code here
```<iframe width="100%" height="200" [src]="videoUrl | youtube" frameborder="0" allowfullscreen></iframe>```

I made pipe for it
```import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Pipe({
	name: 'youtube',
})
export class YoutubePipe implements PipeTransform {

	constructor(private dom: DomSanitizer) {

	}

	transform(value: string, ...args) {
		return this.dom.bypassSecurityTrustResourceUrl(value);
	}
}```

And i added following to config,xml
```<allow-navigation href="*://*.youtube.com/*" />```

But on ios, it display only blank area
