### ISSUE TITLE
responsive-* should only effect immediate children.

### ISSUE THREAD

**Issue by BradyLiles** [driftyco/ionic#8580]
Should responsive-sm, responsive-md, responsive-lg only effect the elements immediate children elements? This is an issue where I would like to have 1`<ion-card>` on a portrait view and 2 `<ion-card>`'s on a landscape view... However with me having a nested `<ion-col>` in my card i get the effects of the parent element's responsive-sm containing my two cards effecting it.

I'm unsure if this is the expected result and I'm doing something wrong here, or if this is a bug.

```
<ion-row responsive-sm>
  <ion-col>
    <ion-card text-center class="leads">
      <ion-card-content>
        <ion-card-title>
          Test stuff
        </ion-card-title>
      </ion-card-content>
      <ion-scroll scrollX="true">
        <ion-col ion-button class="lead-filter" width-25 *ngFor="let item of items">
          <div [ngStyle]="{'border-top-color': item.color}" class="container">
            <div class="label">
              {{item.name}}
            </div>
            <div class="value">
              {{item.count}}<span class="percent">%</span>
            </div>
          </div>
        </ion-col>
      </ion-scroll>
    </ion-card>
  </ion-col>
  <ion-col>
    <ion-card text-center class="leads">
      <ion-card-content>
        <ion-card-title>
          Test stuff
        </ion-card-title>
      </ion-card-content>
      <ion-scroll scrollX="true">
        <ion-col ion-button class="lead-filter" width-25 *ngFor="let item of items">
          <div [ngStyle]="{'border-top-color': item.color}" class="container">
            <div class="label">
              {{item.name}}
            </div>
            <div class="value">
              {{item.count}}<span class="percent">%</span>
            </div>
          </div>
        </ion-col>
      </ion-scroll>
    </ion-card>
  </ion-col>
</ion-row>
```

Current Portrait
![image](https://cloud.githubusercontent.com/assets/3682933/19215921/b22ba5a8-8d68-11e6-9dfe-f989ab5033c2.png)

Current Landscape
![image](https://cloud.githubusercontent.com/assets/3682933/19215925/cc47deca-8d68-11e6-906d-7935d76e8d39.png)

Preferred Portrait
![image](https://cloud.githubusercontent.com/assets/3682933/19215930/e79c1ef2-8d68-11e6-8300-0333f8dfc826.png)

I'm sure yall can figure out the fix, but this is something I'd imagine happening..
@media (max-width: 567px)
[responsive-sm] > ion-col[width-10], [responsive-sm] > ion-col[width-20] ..... {
...
    width: 100%;
    max-width: 100%;
}

Cheers!!

**Comment by okonon** [comment]
@BradyLiles are you running latest rc.0? or still beta11?

Is your `ion-scroll scrollX` working?

**Comment by BradyLiles** [comment]
I'm running the latest and my ion-scroll is working perfectly.

**Comment by BradyLiles** [comment]
Any update on this??

**Comment by brandyscarney** [comment]
Thanks for the issue! With the latest release `2.1.0` comes a new grid system making it easier to customize your layout based on the screen size. Read up on it here: http://blog.ionic.io/build-awesome-desktop-apps-with-ionics-new-responsive-grid/
