### ISSUE TITLE
Ionic serve takes a lot of memory

### ISSUE THREAD

**Issue by samvloeberghs** [driftyco/ionic#8584]
#### Short description of the problem:
`ionic serve` takes a lot of memory

#### What behavior are you expecting?
That it doesn't warmup my Macbook until it's almost melting.

**Steps to reproduce:**
1. `ionic serve`
2.  develop a little, see app refreshing
3.  experience CPU & ram overloaded

**Which Ionic Version?** 2.x

Sorry to be so brief, but basically that's all the information I can provide..
Experiencing it on both my Mac as Windows machine.

**Comment by astec** [comment]
I think auto-reload should be disabled by default. Try to run it with "--nolivereload" - it helped me a bit as I automatically hit Ctrl+S every few seconds and it drives the build process crazy.

**Comment by jgw96** [comment]
Hello @samvloeberghs this is fixed in the latest app-scripts release 0.0.30. There was a memory leak in the older versions of app-scripts that caused it to use over a gb of memory after a few builds. To update you can just run `npm install` inside your project. Thanks!

**Comment by albe-rosado** [comment]
still happening on ubuntu 16.04 lts , using lot of  memory , breaks chrome very often, etc...  Can you guys provide any insight besides closing the issue without any fix ? My env info:
`
cli packages: (/home/albe/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

System:

    Node : v8.2.1
    OS   : Linux 4.10
    npm  : 5.3.0 
`

![screenshot from 2017-08-10 10 03 34](https://user-images.githubusercontent.com/18025582/29174159-728515f6-7db3-11e7-8a3b-c004c32cf6ea.png)
