### ISSUE TITLE
Navbar right side icons appear too small

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#8586]
#### Short description of the problem:
The icons on the right in the navbar appear too small.

![image](https://cloud.githubusercontent.com/assets/644550/19222614/35345e5a-8e5d-11e6-9665-3cbc2a646339.png)

#### What behavior are you expecting?
The same size of icons for both menu toggle and action icons as shown in the Material Design guidelines on https://material.google.com/components/subheaders.html

![image](https://cloud.githubusercontent.com/assets/644550/19222618/511bae3e-8e5d-11e6-8d94-26fe2322e2b4.png)

**Steps to reproduce:**
1. Create an empty tabs project `ionic start tabs tabs --v2`
2. Change a template e.g. home.html with header code based on the documentation:
```
<ion-header>
 <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>

    <ion-title>
      Page Title
    </ion-title>

    <ion-buttons end>
      <button ion-button>
        <ion-icon name="search"></ion-icon>
      </button>
      <button ion-button>
        <ion-icon name="more"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```

**Which Ionic Version?** 2.x

#### Plunker that shows an example of your issue

I have created a Plunkr but in this Plunkr the icons are the same size:

![image](https://cloud.githubusercontent.com/assets/644550/19222634/b4d52cd4-8e5d-11e6-8b80-4e171815a047.png)

http://plnkr.co/edit/Gn9m7rfjc9WSGUOLBwBt?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by daveshirman** [comment]
add icon-only to the button: 
`<button ion-button icon-only ...>`

**Comment by basvdijk** [comment]
Thanks! http://ionicframework.com/docs/v2/api/components/navbar/Navbar/ wan't reflecting this.

**Comment by daveshirman** [comment]
No problem.  If you haven't already, check the release notes too:

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md

**Comment by basvdijk** [comment]
thanks! 👍
