### ISSUE TITLE
Black screen when changing of view fast on iOS

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#8587]
#### Short description of the problem:
If I change of view fast multiple time, the tab will crash. It will result in a black screen for the tab concerned. Other tabs won't be affected.

#### What behavior are you expecting?
No black screen.

**Steps to reproduce:**
1. Switch between two views really fast (before animation has completed) on iOS during about 15-20 seconds.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by kevin1992** [comment]
This happends to me , too, im using tabs with loading component and when push new view and press back button fast sometimes i got black screen on my tab

**Comment by manucorporat** [comment]
This bug was all ready fixed in RC1
