### ISSUE TITLE
Can't see images of slider when routing to it

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#8588]
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.3.1-nightly-4219
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 8.0 Build version 8A218a 


```

First of all, hi!

I have a rather odd problem that I want to fix. I've made a splashscreen that works. Great. I have also a homepage that works. Also great. My homepage has a slider... it works. But....

**Problem:** my slider's images are not showing, when I first visit the splashscreen. When I route a button (that is situated on my splashscreen) to my homepage, I can't see the images in the slider.

```
app.controller('SlideboxModule', function ($scope) {
    $scope.options = {
        loop: false,
        effect: 'fade',
        speed: 1000,
        slidesPerView: 3,
        centeredSlides: false
    }
});
```

This is the code for the slidebox.

**My images in the slider do work though, when I change this to home, instead of the splashscreen:**

`$urlRouterProvider.otherwise("/home");`

I truly don't get it. The things is: it doesn't work on the view or the lab... so can't see my home.html at all anymore. It just says **"Cannot GET /home.html"**. I tried checking it in the console, but no errors at all...

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#85
