### ISSUE TITLE
Animate the ion-tabs (Ionic2)

### ISSUE THREAD

**Issue by jlno** [driftyco/ionic#8592]
How to animate transitions between tabs?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Also we are tracking an issue [here](https://github.com/driftyco/ionic/issues/5101) to add swipe able tabs  Thanks for using Ionic!
