### ISSUE TITLE
how to intercept page enter

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#8594]
this.viewCtrl.willEnter.subscribe(()=> {

            console.log('isTransitioning while trigger willEnter:', this.navCtrl.isTransitioning());

            this.navCtrl.push(otherPage);

        })

in willEnter is Transitioning ,invoke push method again unable to intercept the running transition .

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0-201610041708
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by manucorporat** [comment]
willEnter event is too late to block a running transition.

You should use:

```
ionViewCanLeave() {
  return false; // returning false cancels the transition
}
```

Please use https://forum.ionicframework.com instead of GitHub issues for any question you have in the future!

**Comment by izee** [comment]
@manucorporat thank you,I used ionViewCanEnter instead. ionViewCanEnter and ionViewCanLeave not included document

**Comment by izee** [comment]
@manucorporat I can't login forum,after login the page output:

> There is a problem with your account. Please contact the site's administrator.
