### ISSUE TITLE
project initialize fail 

### ISSUE THREAD

**Issue by maoguiyou** [driftyco/ionic#8595]
ionic -v  => 2.1.0-beta.3
node -v => v6.7.0
npm -v  => 3.10.8
run  " ionic start demo --v2 " command , no error ,no download file，
run  " ionic start demo --v2 " command at git ：

mgy@mgy-PC MINGW64 /f

$ ionic start myApp --v2
/c/Users/mgy/AppData/Roaming/npm/ionic: line 14: 13560 Illegal instruction     node "$basedir/node_modules/ionic/bin/ionic" "$@"

mgy@mgy-PC MINGW64 /f

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This issue is caused by you running the beta version of the cli. We recently released a new version of the CLI that works with RC0. To uninstall the beta version of the cli and install the latest stable version you can run the following command: 
```
npm uninstall -g ionic && npm install -g ionic
```
