### ISSUE TITLE
Use Provider in BaseRequestOptions

### ISSUE THREAD

**Issue by kyleap** [driftyco/ionic#8596]
I want set headers for every http request , so i try get storage data by NativeStorage , but the service provider is null (looks like not Injectable ready) , how can i use service provider in baseRequestOptions , thanks

NativeStorage : [https://ionicframework.com/docs/v2/native/nativestorage/](url)

code:

@Injectable()
export class AppRequestOptions extends BaseRequestOptions {
  constructor(private nativeStorage: NativeStorageService) {
    super();
    // Null
    nativeStorage.get('authorizationData').then((authData)=>{  
        this.headers.append('Authorization', 'Bearer ' + authData.access_token);
    })
  }
}

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#670

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this was an issue with Ionic Native I have moved this issue to the Ionic-Native repo.
