### ISSUE TITLE
ion-spinner color not applied

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic#8598]
#### Short description of the problem:

Adding the color attribute to the ion-spinner is not affecting the color of the component. I'm seeing this behaviour on chrome and android.

#### What behavior are you expecting?

The color name should be applied to the ion-spinner

This is not working:
```
<ion-spinner color="danger"></ion-spinner>
```

**Other information:

The class added to the ion-spinner is "spinner-undefined-danger", so, seems that the mode is not been applied.

**Which Ionic Version?** 1.x or 2.x
2 rc0

**Comment by lwz7512** [comment]
use this style in v2 rc0 for default spinner at ios mode: 
```
.spinner-ios line, .spinner-ios-small line {
  stroke: #f53d3d;
}
```
