### ISSUE TITLE
bug: NPM CORDOVA AND IONIC NOT INSTALLING USING NODE.JS

### ISSUE THREAD

**Issue by rasheequsmani** [driftyco/ionic#8600]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>C:\Users\KSS>npm install -g cordova ionic
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\Users\KSS\AppData\Local\Temp\npm-5012-d
4aedd8a\registry.npmjs.org\ionic\-\ionic-2.1.0.tgz
npm ERR! Expected: cc4218ec13f31b635c1119c9defae5b2bad31335
npm ERR! Actual:   88177629627a16987bec942611d1ca9e69b8aba9
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues></span>

<span is-issue-template></span>

**Comment by rasheequsmani** [comment]
i am using windows 7 64bit OS

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1508

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with the Ionic cli I have moved this issue to the cli repo. Thanks!

**Comment by rasheequsmani** [comment]
@jgw96 GIVE ME SOLUTION asap,

**Comment by rasheequsmani** [comment]
i found solution. Thanks for feedback and referenced this issue to driftyco/ionic-cli
