### ISSUE TITLE
white screen after templateUpdate or sass finished in v2 rc.0

### ISSUE THREAD

**Issue by lwz7512** [driftyco/ionic#8602]
while made some changes in template or .ts, a few seconds later, the chrome browser auto refresh then display WHITE screen... 
this happen in active 'device toolbar' (blue state), but everything ok in deactive device toolbar!(gray state)

**Comment by lwz7512** [comment]
this happen often, and sometimes page mis-layout or looks like lost all the styles...
very frustrating...
I can make sure that I did not make any mistakes, for refresh the browser, it comes back...

I use chrome 53.0.2785.143 (64-bit) and Mac.
Nevertheless, 2.0 beta.11 does NOT have this problem!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#128

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because this is not actually an issue with Ionic 2 RC0 itself but instead an issue with our new build I have moved this issue to the app-scripts repo.
