### ISSUE TITLE
Getting blank white screen after screensplash on ios device.

### ISSUE THREAD

**Issue by ashutoshagg** [driftyco/ionic#8603]
It's working properly on browser but when i run on ios device screen gets blank after screensplash.
Unable to find error.

**Comment by manucorporat** [comment]
Hi @ashutoshagg  can you edit your message following the provided issue template?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by gxsjtu** [comment]
the screen indeed gets blank for seconds after splashscreen disappears before first page get loaded.

**Comment by finalxcode** [comment]
i have same issue

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3-201611211919
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.4.0
Xcode version: Not installed
