### ISSUE TITLE
Android release apk build failed with exception: execution failed for task ":processDebugManifest"

### ISSUE THREAD

**Issue by ashutoshagg** [driftyco/ionic#8604]
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:st
yle/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:26:184-243
        is also present at [com.facebook.android:facebook-android-sdk:4.16.1] AndroidManifest.xml:32
:13-63 value=(@style/com_facebook_activity_theme).
        Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml
:26:9-246 to override.

**I have tried to add tools:replace="android:theme" in AndroidManifest.xml but still facing this error.**

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1509

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Because this is an issue related to the Ionic CLI and not the Ionic framework I have moved this issue to the CLI repo.
