### ISSUE TITLE
<ion-slides> is not swipable with <ion-content overflow-scroll="false"> with MS Edge & touch screen

### ISSUE THREAD

**Issue by Frozenball** [driftyco/ionic#8608]
#### Short description of the problem:

`ion-slides` is not swipable if you using `ion-content` with `overflow-scroll="true"` and Microsoft Edge browser. Problem only occurs when using the touch screen. Other browsers are not affected.

``` html
<ion-slides>
  <ion-slide-page>
     <ion-content overflow-scroll="true">Lots of scrollable content here</ion-content>
  </ion-slide-page>
  <ion-slide-page>
     <ion-content overflow-scroll="true">Lots of scrollable content here</ion-content>
  </ion-slide-page>
</ion-slides>
```

![swiping_not_working](https://cloud.githubusercontent.com/assets/53298/19238814/e68a5a84-8f0b-11e6-8378-3d539fa1dfaf.gif)
#### What behavior are you expecting?

Swiping works:

![swiping_working](https://cloud.githubusercontent.com/assets/53298/19238817/e9f5c6e0-8f0b-11e6-93d6-25fbda3f76bc.gif)
(Chrome)

**Other information:**

[Workaround](http://codepen.io/teemuko/pen/WGzPqB) is to set `overflow-scroll` as false.

**Which Ionic Version?**

Latest 1.x nightly build affected and others.

Codepen: http://codepen.io/teemuko/pen/kkEVRa

**Comment by kina4smile** [comment]
Have the same problem!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#84
