### ISSUE TITLE
 ngc error: Compilation failed - ionic build android

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#8613]
I have updated an application using Ionic2 RC. In my application, I managed to load/create a component dynamically. It worked fine when debugging, but when I tried to build android, I had the error below: 

`[14:38:42]  ngc: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 65:17 in the original .ts file), resolving symbol COMPILER_PROVIDERS in c:/MCNEXT/Vinci/Vinci-RSC%20Mobile/node_modules/@angular/compiler/src/compiler.d.ts, resolving symbol AppModule in c:/MCNEXT/Vinci/Vinci-RSC%20Mobile/.tmp/app/app.module.ts, resolving symbol AppModule in c:/MCNEXT/Vinci/Vinci-RSC%20Mobile/.tmp/app/app.module.ts
at simplifyInContext (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:469:23)
at StaticReflector.simplify (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:472:22)
at StaticReflector.annotations (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\static_reflector.js:61:36)
at _loop_1 (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:53:54)
at CodeGenerator.readFileMetadata (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:66:13)
at c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:100:74
at Array.map (native)
at CodeGenerator.codegen (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\codegen.js:100:35)
at codegen (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\compiler-cli\src\main.js:7:81)
at Object.main (c:\MCNEXT\Vinci\Vinci-RSC%20Mobile\node_modules\@angular\tsc-wrapped\src\main.js`

Is COMPILER_PROVIDERS supported with AOT ?

**Comment by tadchristiansenli** [comment]
Try `npm run build --dev`

I still have issues when I remove --dev

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually NGC (the Angular 2 template compiler) throwing about an error in your code. NGC does typechecking of your templates, which means that it also knows how to throw errors about methods and variables bound to in your template. I would recommend asking around on our [forum](https://forum.ionicframework.com) for help tracking down the bug in your code. The reason this error does not happen when doing a dev build (by running `ionic serve`) is because our dev build does not run the Angular 2 template compiler. Thanks!

**Comment by tadchristiansenli** [comment]
Thanks for the info @jgw96 

@h2qutc Are you creating a new object in your providers array?

**Comment by vardas-bill** [comment]
I too have this problem and am having great difficulty tracking down what is causing it. Is it possible to do ionic build ios in a dev build?

**Comment by tadchristiansenli** [comment]
@vardas-bill I was creating a new object in the providers. If you are doing that you will want to use a factory function instead. Post what your app.module.ts looks like.

**Comment by vardas-bill** [comment]
Thanks @tadchristiansenli that was it!

**Comment by h2qutc** [comment]
Hi, 
@tadchristiansenli , can u show how you do please?  My app.module.ts looks like: 
`var APP_PAGES = [
  BlogPage,
  CommunitiesPage]
`
`export function appPagesFactory(): any {
  return [...APP_PAGES]; 
}`
`@NgModule({
       declarations: [
MyApp,
    DynamicComponent,
    appPagesFactory(), 
    //APP_PAGES,
    APP_DIRECTIVES
  ],
`
I got the same error: 

`ngc: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 20:13 in the original .ts file), resolving symbol CommunitiesPage `
Do you have any idea ?
