### ISSUE TITLE
bug: ionic run android --debug starts in production mod

### ISSUE THREAD

**Issue by bastiss** [driftyco/ionic#8614]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>ionic run android --debug

builds in production mode. TypeScript debugging via Chrome inspect not possible.

Running 'run:before' npm script before run
> ionic-hello-world@ build /myAppV2
> ionic-app-scripts build
[16:44:32]  ionic-app-scripts 0.0.30
[16:44:32]  build prod started ...
[16:44:32]  clean started ...
[16:44:32]  clean finished in 14 ms
[16:44:32]  copy started ...
[16:44:32]  ngc started ...
[16:44:32]  lint started ...
[16:44:32]  copy finished in 57 ms
[16:44:32]  lint finished in 464 ms</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! The `--debug` flag prints out debug information about the build. If you would like to have sourcemaps (dev build) while running your app on a device you can add the `--dev` flag to this line in your package.json `"build": "ionic-app-scripts build",` so that it looks like this `"build": "ionic-app-scripts build --dev"`. Thanks!

**Comment by beylkhanovdamir** [comment]
@jgw96 

currently debugging is not working and *.ts files are not present in Chrome Sources, only bundle js files

Ionic CLI v2.1.4
nodejs 6
cordova 6.3.1
@ionic/app-scripts: 0.0.41

**Comment by beylkhanovdamir** [comment]
@jgw96 
 you can see the same problem in this [topic](https://forum.ionicframework.com/t/debugging-typescript-with-new-build-process/68939/3)

**Comment by jgw96** [comment]
Hello. We are tracking this issue [here](https://github.com/driftyco/ionic-app-scripts/issues/289)
