### ISSUE TITLE
Ion-tabs fail with solid black page on documentation site and in sample application

### ISSUE THREAD

**Issue by abierbaum** [driftyco/ionic#8618]
#### Short description of the problem:

When attempting to setup a page with ion-tabs I am left with a blank black page.  This shows up on the component documentation page (http://ionicframework.com/docs/v2/api/components/tabs/Tabs/) and in a demonstration application (https://github.com/abierbaum/ionic2_test/tree/ion_tabs_bug).  I have tried multiple variants and can not determine why the tabs do not show up and fail.

![tabs_docs](https://cloud.githubusercontent.com/assets/397889/19247004/b1ad9654-8eee-11e6-9f6f-40d1538e7185.png)

#### What behavior are you expecting?

Expecting tabs to show up in view and work.

**Steps to reproduce:**
1. Go to documentation site: http://ionicframework.com/docs/v2/api/components/tabs/Tabs/ to see black page

Demonstration app:
1. Clone https://github.com/abierbaum/ionic2_test/tree/ion_tabs_bug
2. npm install
3. ionic serve
4. Check the "Tabs Page" or "Tab Demo" page

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I found that copying the css code from the demo app (https://github.com/driftyco/ionic/blob/v2.0.0-rc.0/demos/src/tabs/style.css) could help the tabs show up in some cases, but they were not in correct position and were not interactive.
 
**Which Ionic Version?** 2.0.0-rc.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v6.7.0

Browser: Chrome 53.0.2785.143

**Comment by manucorporat** [comment]
ping @mhartington

**Comment by mhartington** [comment]
👍

**Comment by abierbaum** [comment]
@mhartington Is there any known workaround for now?  I would like to build an app with tab navigation but can't seem to get any code working that will work.  I have tried everything I can think of.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#827

**Comment by jgw96** [comment]
Hello all! Since this issue is a docs site issue and not a framework issue I have moved this issue to the ionic-site repo. Thanks!

**Comment by abierbaum** [comment]
@jgw96 Just to be clear, I can't get tabs to work in a standalone application based on the starter either. (see: https://github.com/abierbaum/ionic2_test/tree/ion_tabs_bug )  Is the idea that it works but just isn't documented how to make it work?

**Comment by mhartington** [comment]
miscommunication on @jgw96's part. 


@abierbaum I'm not able to replicate this using the tabs starter project, so you error is probably project specific

**Comment by mhartington** [comment]
Docs are fixed.

**Comment by abierbaum** [comment]
@mhartington How should I proceed?  I could come up with steps that show it starting from 

```
$ ionic start MyIonic2Project tutorial --v2
```

And either adding one page or changing one page.

would that be useful.  I just need to find a way to determine the issue.

Q: What is the "tabs starter project"?  Maybe that would help me.  I only started with the tutorial project and added some new pages before.  If there is another starter I can use that may help me track it down.

**Comment by mhartington** [comment]
`ionic start myApp tabs --v2`


The same templates that were in V1 exist for V2. So the tabs starter will give you the proper base to create your own tab layout.

https://github.com/driftyco/ionic2-starter-tabs

There's probably some small error somewhere in your app (without looking too much into it) but the tabs starter should be a good place to start.

Cheers!
