### ISSUE TITLE
‘Cordova/CDVViewController.h’ file not found in Xcode 8.0

### ISSUE THREAD

**Issue by mindspot** [driftyco/ionic#8619]
Version Information:
Cordova 6.3.1
Xcode 8.0
Node 6.2.2
Ionic 2.1.0
cordova-ios@4.2.1

![snip20161011_2](https://cloud.githubusercontent.com/assets/11856214/19248290/b9686752-8f61-11e6-8c88-f40db2ad4a53.png)

problem is still exists!

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
