### ISSUE TITLE
List elements too sensitive when scrolling

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#8622]
#### Short description of the problem:
Try to scroll a list with like 20-30 elements. Scroll is too sensitive that it will click list element. To scroll without clicking, I've to press screen little hard and then scroll. 

#### What behavior are you expecting?
Element should not be clicked when scrolling a list. 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by aggarwalankush** [comment]
@jgw96  Is there any way to increase click delay when scrolling?

**Comment by manucorporat** [comment]
I think this was already fixed in RC2. Please reopen if the problem persist.

**Comment by epetre** [comment]
I think that this issue should be reopened as it is still a big problem in iOS and I saw no improvement over over the various version releases of ionic2.

@aggarwalankush have you found a way to reduce the sensitivity ?

**Comment by aggarwalankush** [comment]
@epetre Currently, I'm using version 2.3.0 and not facing this issue.
