### ISSUE TITLE
EventEmitter in sub-component

### ISSUE THREAD

**Issue by CarlosAdrianM** [driftyco/ionic#8623]
#### Short description of the problem:
In beta versions I could extend a component and the events where emitted with no problem, but in RC0 the events are not emitted.

#### What behavior are you expecting?
I would like to have an abstract component with an EventEmitter, and call it from a extended class (this worked like a charm in beta versions).

**Steps to reproduce:**
1. ionic start --v2 myEventApp
2. Create an abstract class with a public EventEmitter (code below)
3. Create a component that extends the abstract class, which have a button that fires the event from the abstract class.
4. Show the component somewhere, and click the button. In beta versions it fires the event, and in RC0 it does not.

myEventComponent.ts
```
import {Output, EventEmitter} from '@angular/core';

export abstract class myEventComponent  {
    @Output() public myEventEmitted: EventEmitter<any> = new EventEmitter();

    public emitEvent(myData: any): void {
        this.myEventEmitted.emit(myData);
    }
}
```

mySecondComponent.ts
```
import {Component, Injectable} from '@angular/core';
import { myEventComponent } from '../myEventComponent/myEventComponent';

@Component({
    selector: 'my-second-component',
    templateUrl: 'mySecondComponent.html',
})

@Injectable()
export class mySecondComponent extends myEventComponent  {

}
```

mySecondComponent.html
```
<button ion-button (click)="emitEvent()">Click to emit event</button>
```

app.module.ts
```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';
import { mySecondComponent } from '../pages/mySecondComponent/mySecondComponent'


@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage,
    mySecondComponent
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage,
    mySecondComponent
  ],
  providers: []
})
export class AppModule {}
```

And change, for example, about.html file, to fire the event:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      About
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
<my-second-component (myEventEmitted)="sayHello()"></my-second-component>
</ion-content>

```

about.ts
```
import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
import { myEventComponent } from '../myEventComponent/myEventComponent'

@Component({
  selector: 'page-about',
  templateUrl: 'about.html'
})
export class AboutPage {

  constructor(public navCtrl: NavController) {

  }

  public sayHello() {
    console.log("Hello");
  }

}

```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.4.7

The event does not fire. Why? Is it a bug? Or I am doing something wrong?

Thank you

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Does this work with a plain Angular 2 final project? Ionic does not change anything about how the event emitters work with in Angular 2 so im not sure that this is actually an Ionic issue.

**Comment by CarlosAdrianM** [comment]
This code worked fine in beta 11, but it does not work in RC0. Something must have changed...

What do you mean with a plain Angular 2 final project? Not to use "ionic start --v2 myEventApp"?

**Comment by jgw96** [comment]
Sorry, should have been more clear. So in beta.11 we were running a much older version of Angular 2 (rc4) compared to Ionic 2 RC0, which is on the latest Angular 2 (2.0.2) which means alot has changed in Angular 2 since Ionic 2 beta.11. On the second question: Yep, just with a regular Angular 2 project like you would get with the [angular cli](https://github.com/angular/angular-cli).

**Comment by CarlosAdrianM** [comment]
No, it does not work in plain Angular too. Not an ionic issue. Sorry.

Thank you very much for you help!

**Comment by jgw96** [comment]
@CarlosAdrianM No problem, have fun on your Ionic adventures!
