### ISSUE TITLE
Ionic2 RC0 Cant use ion-row inside of ion-select

### ISSUE THREAD

**Issue by seand88** [driftyco/ionic#8625]
#### Short description of the problem:
Before rc0 was using <ion-select><ion-row (with ngfor loop><ion-item>

Now with rc0 nothing shows up if <ion-item> is inside of an <ion-row> in the select

#### What behavior are you expecting?
Expect this to work as it did before rc0, where the items were shown

**Steps to reproduce:**
1.  Place ion-item inside of an ion-row within a ion-select component
2.  Run code in browser
3.  No items show in the select

**Other information:** 
Maybe this in an intended change? If i place the ion-item inside of a div it works
Just would like to know the reason for this 
 

**Which Ionic Version?** 1.x or 2.x
2 RC0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post a code snippet of the markup that is not working? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by seand88** [comment]
This is still an issue
