### ISSUE TITLE
Push notification error : ORIGINAL EXCEPTION: No provider for Push!

### ISSUE THREAD

**Issue by mcornillon87** [driftyco/ionic#8626]
Hi,
I am having an issue implementing push notification on my app : I got the following error while serving :  ORIGINAL EXCEPTION: No provider for Push!

Looking for answers I found former topics mentioning conflict using @viewchild and passing provider in constructor. https://github.com/driftyco/ionic/issues/5543 But I can't figured this out...

Any idea ?

#### What behavior are you expecting?

**Steps to reproduce:**
1. start a sidemenu app
2. follow the push notification guide https://docs.ionic.io/services/push/
3. serve

My app.component : 
```
import { Push, PushToken } from '@ionic/cloud-angular';

@Component({
  templateUrl: 'app.html'
})

export class MyApp {
  @ViewChild(Nav) nav: Nav;

  rootPage: any = HomePage;

  pages: Array<{title: string, component: any, icon: string}>;

/* PASS PUSH IN CONSTRUCTOR */
  constructor(public platform: Platform, public wp: ApiWp, public push: Push) {
    this.initializeApp();

    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Actualite', component: ActualitesPage, icon:'text' },  
      { title: 'Réglages', component: SettingsPage, icon:'settings' }    
    ];

  }

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();


          /*BEGINNING  OF PUSH NOTIFICATION CODE */

    this.push.register().then((t: PushToken) => {
        return this.push.saveToken(t);
      }).then((t: PushToken) => {
        console.log('Token saved:', t.token);
      });

      this.push.rx.notification()
  .subscribe((msg) => {
    alert(msg.title + ': ' + msg.text);
  });
  /* END */
    });

  }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.7 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.0 Build version 8A218a 

Thanks :)

**Comment by mariohmol** [comment]
solution? having same issue here

**Comment by vksgautam1** [comment]
any solution

**Comment by mariohmol** [comment]
I could not make that work with `@ionic/cloud-angular` , the only way i could make was:

```
import { Push } from 'ionic-native';

export class App {

constructor(public app: App,platform: Platform){

  platform.ready().then(() => {
    let push = Push.init({
        android: {
          senderID: 'MYID'
        },
        ios: {
          alert: 'true',
          badge: true,
          sound: 'false'
        },
        windows: {}
      });
    }

     push.on('registration', (data) => {
          console.log("device token ->", data.registrationId);
        });
      push.on('notification', (data) => {
          console.log(data);
  
        })
  }

}
```

**Comment by vksgautam1** [comment]
thanks i will try this

**Comment by dnyaneshwaruttarwar** [comment]
Hi

**Comment by Jemcol** [comment]
@dnyaneshwaruttarwar you've saved my life ! thx a lot !!!

**Comment by dnyaneshwaruttarwar** [comment]
I'm facing one issue, The notification is not getting a popup on my mobile device. Is anyone facing the same issue ?
