### ISSUE TITLE
ionic start not working. Not enough permission

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8635]
ionic start myApp  --v2 --verbose

1193 verbose stack Error: Command failed: git -c core.longpaths=true clone C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692 C:\Users\C25B~1\AppData\Local\Temp\npm-10480-6a0f86fc\git-cache-f2516694bd4dae734edb2d5a9cea059a\9803562a61c2172a69f3475f97e98922c0b49ac0
1193 verbose stack Cloning into 'C:\Users\C25B~1\AppData\Local\Temp\npm-10480-6a0f86fc\git-cache-f2516694bd4dae734edb2d5a9cea059a\9803562a61c2172a69f3475f97e98922c0b49ac0'...
1193 verbose stack "git-upload-pack 'C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692'": git-upload-pack 'C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692': No such file or directory
1193 verbose stack fatal: Could not read from remote repository.
1193 verbose stack
1193 verbose stack Please make sure you have the correct access rights
1193 verbose stack and the repository exists.
1193 verbose stack
1193 verbose stack     at ChildProcess.exithandler (child_process.js:214:12)
1193 verbose stack     at emitTwo (events.js:88:13)
1193 verbose stack     at ChildProcess.emit (events.js:173:7)
1193 verbose stack     at maybeClose (internal/child_process.js:819:16)
1193 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
1194 verbose cwd D:\denwerready\-readyscript\111\myApp\myApp2
1195 error Windows_NT 6.3.9600
1196 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1197 error node v5.2.0
1198 error npm  v3.3.12
1199 error code 128
1200 error Command failed: git -c core.longpaths=true clone C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692 C:\Users\C25B~1\AppData\Local\Temp\npm-10480-6a0f86fc\git-cache-f2516694bd4dae734edb2d5a9cea059a\9803562a61c2172a69f3475f97e98922c0b49ac0
1200 error Cloning into 'C:\Users\C25B~1\AppData\Local\Temp\npm-10480-6a0f86fc\git-cache-f2516694bd4dae734edb2d5a9cea059a\9803562a61c2172a69f3475f97e98922c0b49ac0'...
1200 error "git-upload-pack 'C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692'": git-upload-pack 'C:\Users\Чубзик\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692': No such file or directory
1200 error fatal: Could not read from remote repository.
1200 error
1200 error Please make sure you have the correct access rights
1200 error and the repository exists.
1201 error If you need help, you may report this error at:
1201 error     <https://github.com/npm/npm/issues>
1202 verbose exit [ 1, true ]

npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR!
 Please include the following file with any support request:

npm ERR!     D:\denwerready\-readyscript\111\myApp\npm-debug.log

Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
-----------------------
Do you have any ideas?

**Comment by azakusilo** [comment]
I added the SSH public key to my GitHub account and the message:
----
Host key verification failed.
-----
Gone!
But the message:
----
1089 verbose stack fatal: Could not read from remote repository.
1089 verbose stack
1089 verbose stack Please make sure you have the correct access rights
1089 verbose stack and the repository exists.
1089 verbose stack
1089 verbose stack     at ChildProcess.exithandler (child_process.js:214:12)
1089 verbose stack     at emitTwo (events.js:88:13)
1089 verbose stack     at ChildProcess.emit (events.js:173:7)
1089 verbose stack     at maybeClose (internal/child_process.js:819:16)
1089 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
----
Is still here. May be anyone have any ideas?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Since this seems like an issue with your local setup (looks like a proxy or network firewall issue to me) and not an Ionic issues I am going to close this issue for now and urge you to ask this question on our [forum](https://forum.ionicframework.com). Thanks!

**Comment by azakusilo** [comment]
Yes may be. In my case I had soled this than installed https://desktop.github.com/ (GitHub Application). And I open in it GitShell (right click on Tutorial). 
And OMG this works!
