### ISSUE TITLE
Ionic 1: $ionicPlatform.ready not fired in iOS emulator (ios 10) when a Content Security Policy is added to index

### ISSUE THREAD

**Issue by panchazo** [driftyco/ionic#8636]
$ionicPlatform.ready is not being fired after adding CSP to index.html in emulator running ios 10. 
Im able to reproduce this error consistently doing the following:

$ ionic start testproject

Then I edit the app.js and an alert inside the ready function like this:

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
          alert("works!"); //add this line and see the magic

Then I build and run the sample app: 

$ ionic build ios
$ ionic run ios

The alert is displayed as it should. But if I add the index.html the following:

```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; frame-src 'self'">
```

The alert will not work any more.

**Other information:** 

My system information is (ionic info output):

Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 

Here is (https://www.dropbox.com/s/3q4xw3qwxjptj1d/test.zip?dl=0) the sample code project as it was generated without the hooks, platforms and node_modules folder to make it lighter. There are no other change besides the CSP line inside index.html and the alert in the app.js, and no other plugins were added (besides the defaults that get added when starting the project with ionic start...)

**Comment by fabledfoe** [comment]
Cordova requires another protocol 'gap:' you need to add to your CSP with iOS10.  I had the same issue after upgrading Xcode.  Update your CSP to the following:

```
<meta http-equiv="Content-Security-Policy" content="default-src * gap: ; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; frame-src 'self'">
```

I also had to add 'file:' but that may just be my config.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#82
