### ISSUE TITLE
Ionic2 issue closing popover with event in beta11

### ISSUE THREAD

**Issue by PabloFNK** [driftyco/ionic#8637]
#### Short description of the problem:

When I open a popover positioned relative to the element clicked, it can't be closed.

Note: I haven't seen any change regarding this in the changelog, so I guess it is happening too in the RC0.

#### What behavior are you expecting?

The popover should close.

**Steps to reproduce:**
1. Create popover
2. Present popover relative to the button clicked
3. Try to dismiss the popover. It won't close

Note: If we don't pass the event and the popover is displayed in the middle of the screen, it can be dismissed.

All this done as in the documentation: http://ionicframework.com/docs/v2/api/components/popover/PopoverController/

**Which Ionic Version? 2, beta 11

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 8.1
Node Version: v5.2.0

**Comment by nikoTM** [comment]
Can't reproduce this, please try to make a plunker template.

**Comment by jgw96** [comment]
Hello @PabloFNK , unfortunately I cannot reproduce this issue. Would you mind posting a repo that i can use to reproduce this issue?

**Comment by PabloFNK** [comment]
Thanks @nikoTM and @jgw96 ,

I don't know why the other day it wasn't displayed any error in console but today it is doing it, and it seems to be related with this bug:

https://github.com/driftyco/ionic/issues/6918

So, I guess this one can be closes. We'll have a look again once we update to the RC0.

Thanks!
