### ISSUE TITLE
Uncaught TypeError: Class constructor ViewChildMetadata cannot be invoked without 'new'

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#8638]
_From @Lafaa on October 11, 2016 13:5_

```
Uncaught TypeError: Class constructor ViewChildMetadata cannot be invoked without 'new'
PropDecoratorFactory @ decorators.js:232
(anonymous function) @ preferred.ts:82
(anonymous function) @ preferred.ts:7
(anonymous function) @ main.dev.ts:5
```

The line decorators.js:232 has:  `annotationCls.apply(decoratorInstance, args);`

I just followed the steps to update my app to 2.0.0 beta 11 and then to 2-0-0,RC0, i commented all the lines the seemed to give errore in VSCode (they were all navController.present() method), but now i'm getting this error when i try to serve my app. The screen remains blank and the prompt doesn't show any error... 

It seems to be linked to the decorators, so i updated all the dependencies in the package.json to RC5 and ran "npm install", but it didn't solve the problem. 

Do you have any idea on what could cause this error? 
Thanks a lot

_Copied from original issue: driftyco/ionic-cli#1515_

**Comment by jgw96** [comment]
Hello @Lafaa . Are you still having this issue?

**Comment by Lafaa** [comment]
Hi, yes i do. I will try to create a new project and add the pages one at a time to see which element or directive gives it problems...

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
