### ISSUE TITLE
plugin_not_installed Ionic2 RC

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#8642]
Hi, 
When I tried "ionic run android", I got the error below: 

`Native: tried calling AppVersion.getVersionNumber, but the AppVersion plugin is not installed.
main.js:74377 Install the AppVersion plugin: 'ionic plugin add cordova-plugin-app-version'
main.js:3602 EXCEPTION: Uncaught (in promise): plugin_not_installedErrorHandler.handleError @ main.js:3602
main.js:3607 ORIGINAL STACKTRACE:ErrorHandler.handleError @ main.js:3607
main.js:3608 Error: Uncaught (in promise): plugin_not_installed`

I got the latest version of ionic-native and I installed the necessary plugin.  

Is that an issues of Ionic2 RC or I was doing Something wrong?

**Comment by ramonornela** [comment]
Move to repo ionic-native 😉 

Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#688

**Comment by jgw96** [comment]
Hello all! Since this was an issue with Ionic Native and not the framework i have moved this issue to the ionic-native repo. Thanks!

**Comment by johnbolsberg** [comment]
@jgw96  hey, when i run my ionic app with ionic-view ap i get the error "plugin_not_installed".
(it's just a simple app of login to facebook).
when i run my app in emulator or chrome://inspect it works fine.. why is that?
