### ISSUE TITLE
ion-footer inside ion-menu is not visible on ios / safari browser

### ISSUE THREAD

**Issue by lonwi** [driftyco/ionic#8644]
Short description of the problem:

There is some issue with displaying ion-footer inside of the ion-menu for sidebar menu. It looks that ion-content is too long and pushes the ion-footer below visible area. There is also an

This happens on Safari and iPhone 5s with latest updates for sure. There is also issue with ion-header height on ios and it overlaps the status bar. It is like missing padding or something from top.

What behaviour are you expecting?

It works fine in chrome and android. The footer is visible and is visible when scrolling. 

```
<ion-menu id="loggedInMenu" [content]="content">

    <ion-header>
        <ion-toolbar no-border no-padding>
            <div class="menu-profile" *ngIf="currentUser.photo">
                <div class="menu-profile-content" padding>
                    <ion-row no-padding>
                        <ion-col width-33>
                            <div class="menu-profile-image"><img [src]="currentUser.photo" alt="Profile Picture"></div>
                        </ion-col>
                        <ion-col width-66>
                            <div class="menu-profile-label">Username:</div>                        
                            <div class="menu-profile-username">{{currentUser.displayName}}</div>                        
                            <div class="menu-profile-label">Last Login:</div>                        
                            <div class="menu-profile-logindate">{{currentUser.onlineDate | amTimeAgo}}</div>                        
                        </ion-col>
                    </ion-row>
                </div>
            </div>
        </ion-toolbar>
    </ion-header>

    <ion-content>
        <ion-list>
            <button menuClose ion-item *ngFor="let p of appPages" (click)="openPage(p)">
                <ion-icon *ngIf="p.icon" item-left [name]="p.icon"></ion-icon>
                {{p.title}}
                <ion-badge *ngIf="p.badge" item-right>{{p.badge}}</ion-badge>
            </button>
        </ion-list>
    </ion-content>

    <ion-footer class="menu-footer">
        <ion-toolbar no-border>
            <ion-title>
                <div class="menu-footer-content">
                    <img src="./assets/img/pm-logo-white.svg" class="menu-footer-logo">
                </div>
            </ion-title>

            <ion-buttons right padding-right>
                <button ion-button (click)="logout()">
                    <ion-icon name="power" color="white"></ion-icon>
                </button>
            </ion-buttons>

        </ion-toolbar>
    </ion-footer>
    
</ion-menu>
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
<pm-loading-bar></pm-loading-bar>

```

Which Ionic Version?

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0-201610041708
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 

iPhone 5s

https://cloud.githubusercontent.com/assets/7570834/19309120/f87ea892-907a-11e6-9fdb-1e2620f40142.PNG

Samsung S6 - Correct display of footer and header in sidebar menu

https://cloud.githubusercontent.com/assets/7570834/19309359/3236c8f2-907c-11e6-8a61-832b65ab93ce.png

**Comment by manucorporat** [comment]
This was already fixed in rc1!

**Comment by tejit2004** [comment]
When we can expect RC1 to be released as it is stopping me to upload to store.

**Comment by tejit2004** [comment]
or can you give me nightly code?

**Comment by Cagdas88** [comment]
I have the same issue and i use the ionic-angular version 3.1.0

i testet with 3.5.0. .. same issue
