### ISSUE TITLE
Ionic 2, Angular 2. How to disable templateUrl exists check?

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8645]
I have file with this component:

    @Component({
      templateUrl: '/mobilesiteapp/template/?path=pages/tabs'
    })
    export class TabsPage {
    }
And my compiler gave me:

    [13:28:50]  Error reading template file, "/mobilesiteapp/template/?path=pages/tabs": Error: ENOENT: no such file or directory, open 'D:\denwerready\-readyscript
    \modules\mobilesiteapp\appsourse\src\pages\mobilesiteapp\template\?path=pages/tabs'

I don't need this check because I need to get templates from url.

How to fix it? Do anybody know?

**Comment by iRoachie** [comment]
You can't use a forward slash. Template urls are relative paths from the conponent.

**Comment by azakusilo** [comment]
Ok. When, how to get template for component from url

**Comment by iRoachie** [comment]
You have to provide the path relative from your component. So start where your component is and provide a path from there. 

If still confused, post your directory structure

**Comment by manucorporat** [comment]
@azakusilo are you trying to load the templates from the server?
`/mobilesiteapp/template/?path=pages/tabs` why these url params?

**Comment by azakusilo** [comment]
So start where your component is and provide a path from there. 
-----
Do you have any short example?

I use Ionic app within my php server application. The templates that I build, which compiler make, is in the same directory that it must to be.
appsourse
   src
       templates
   www
       build - folder with compiled template.

I need, to get template from url because I use my variales from php in it, that contains data and I check auth in my phpapplication(I need it only on server). PHP answers me builded templates with information from my php variables. That's why I need it.
Sorry for my bad English.

**Comment by azakusilo** [comment]
@manucorporat Check the post below.
/mobilesiteapp/template/ - is URL to get my checks and retrieve me PHP compiled template.
?path=pages/tabs - What template I need to compile in PHP.

The Angular compiler compile to me template with php variables. PHP compiler(Smarty) compile me the the PHP variables in compiled template.

**Comment by manucorporat** [comment]
Well, this can not be done with AoT because of obvious reasons. Angular 2 needs all the templates at compile time.

I think you should reconsider the architecture of your app. You should have a server-client communication based in an API and not depending on "generated templates".

**Comment by iRoachie** [comment]
@azakusilo Referring to what @manucorporat said. A better approach would be to use an angular service to get those variables from your server, and then pass them to the component, and let the component display the variables.

1. Use service to get information from service
2. Inject service into component, and get the information.
3. Display the then information through the component.

**Comment by azakusilo** [comment]
Angular 2 allows to use relative paths in templateURL. Look here:
https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html

**Comment by azakusilo** [comment]
So how to disable this check? I need to use it without service.

**Comment by iRoachie** [comment]
I don't think you are understanding how the compiler works.
When you build the application, the compiler looks for the template and pulls the html from it, and injects it into the component. That means that your server variables won't be included in the build process because it's a client side build. So angular will display javascript only at the end, since the template will be imbedded. Here's an article on AOT compilation in angular http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/

**Comment by azakusilo** [comment]
No, I understood.
I find it out.
In new version of Ionic 2. Ionic script try to compile itself all templates that you add. It is not native for Angular 2. I think it is made for better perfomance in Ionic applications. The solution is to comment the line at the end of file.
/node_modules/@ionic/app-script/dist/template.js

The line is:
var COMPONENT_REGEX = /@Component\s*?\(\s*?(\{([\s\S]*?)(\s*templateUrls\s*:\s*(['"`])(.*?)(['"`])\s*?)([\s\S]*?)}\s*?)\)/m;
