### ISSUE TITLE
ClearAll does not work.

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#8646]
#### I think clear all does not clean notifications so i get too many alarms (500) error? Even If i do not schedule new notifications It does not delete old notifications. (One more point If i want to disable and enable same local notification is there any option)

Ionic2.0.0 rc0

**Comment by manucorporat** [comment]
Looks like this issue is not related to ionic itself. Closing.

**Comment by Anshdesire** [comment]
@manucorporat  - If clearAll does not delete then Issue is related to Ionic itself ??
