### ISSUE TITLE
Conditional Primary Color is not Applied in RC0

### ISSUE THREAD

**Issue by otruffer** [driftyco/ionic#8649]
When Using in Ionic 2 rc0

`<ion-icon color="primary" name="..."></ion-icon>`

the primary color is applied to the icon correctly. But if I have a conditional primary color (which is applied correctly in HTML) using

`[attr.color]="booleanValue?'primary':null"`

the primary will not be applied (see screenshot). 

![selection_154](https://cloud.githubusercontent.com/assets/410402/19311060/1b25cc56-908d-11e6-985f-483d588294c9.png)

This was working fine in Beta 11 using `[attr.primary]="booleanValue?'':null`

Your system information:

Cordova CLI: 5.4.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v6.6.0

**Comment by manucorporat** [comment]
@otruffer 
color is not a HTML attribute but an angular 2 input, use this instead:
```
<ion-icon [color]="booleanValue? 'primary' : null"></ion-icon>
```

**Comment by otruffer** [comment]
Cool, got confused by the previous hacky solution, thanks!
