### ISSUE TITLE
Could not resolve './app.module.ngfactory'

### ISSUE THREAD

**Issue by rkyleg** [driftyco/ionic#8653]
I got this error when running ionic build ios

[12:33:30]  bundle prod started ...
[12:33:32]  bundle prod failed:  Could not resolve './app.module.ngfactory'

I had to change the import path for AppModuleNgFactory in main.prod.ts to 

import { AppModuleNgFactory } from '../compiled/app/app.module.ngfactory';

Does that make any sense?

node version: 6.7.0
npm version: 3.10.3

**Comment by okonon** [comment]
is your `ionic serve` working normally?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#147

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build related issue I have moved this issue to the `ionic-app-scripts` repo.

**Comment by OBout** [comment]
and did nothing to solve the problem...
