### ISSUE TITLE
Please consider switching to Yarn for Javascript package management

### ISSUE THREAD

**Issue by lukehutch** [driftyco/ionic#8658]
Please consider switching to Yarn over using raw npm for Ionic.

See:

https://code.facebook.com/posts/1840075619545360

Yarn has many advantages over using npm directly. In particular, dependencies are not duplicated, and Yarn is much faster than npm.

**Comment by nikoTM** [comment]
It's way too early to take actions like this. They have literally announced it yesterday.

**Comment by mhartington** [comment]
Hi there, since this is more of suggest and not an issue with the framework, I'm going to close this.

While Yarn is interesting, and we are looking at it, we're not making any changes at the moment.
Like @nikoTM said, Yarn literally came out yesterday.

**Comment by lukehutch** [comment]
All good, totally understandable. Thanks.

**Comment by etsrepo** [comment]
Any progress ??
