### ISSUE TITLE
bug: Ionic Lab -  Runs Constructor 3 times

### ISSUE THREAD

**Issue by stevenferretti** [driftyco/ionic#8664]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When you use Ionic Lab, it runs the app.ts constructor 3 times, thus causing the root page constructor to run three times. The issue is, since the variables are being stored in the same browser, duplicate data occurs, if pushing to any array etc.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1540

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a cli related issue I have moved this issue to the cli repo.
