### ISSUE TITLE
The click-block blocks my mouse events occasionally.

### ISSUE THREAD

**Issue by lygstate** [driftyco/ionic#8669]
It's random, I hope some may reproduce the issue.

**Comment by lygstate** [comment]
related issue:
https://github.com/driftyco/ionic/issues/8650

**Comment by lygstate** [comment]
It's block the sign in events in IE11

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We do not officially support IE with Ionic 2. Do you also see this issue in other browsers? Chrome, Firefox or Edge?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
