### ISSUE TITLE
$ionicHistory.goBack() not work with “sidemenu”+”state cache false”

### ISSUE THREAD

**Issue by tonn** [driftyco/ionic#8672]
http://play.ionic.io/app/1dffbfcfb14b
It is cut from real app. App have main menu as state, and all other states have side menu.
Click to buttons in sequens: "Go about" -> "Go back" -> "Go about" -> "Go back"
Last "Go back" does nothing.

If we remove "cache: false" from all states or remove sidemenu - it will work normally.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#81
