### ISSUE TITLE
fix($ionicHistory) typo in removeBackView function

### ISSUE THREAD

**Issue by stochris** [driftyco/ionic#8673]
Calling `removeBackView` method twice causes the script to fail.
This is due to decrementing an unexisting property in the method.

There is a PR already [here](https://github.com/driftyco/ionic/pull/8570)

p.s.: I'd like to hear your comments, given that the PR is stil open, even though I feel the complexity of the problem is very low

**Comment by jgw96** [comment]
Hello @stochris would you mind creating a codepen or repo that i can use to reproduce the issue this pr fixes?

**Comment by stochris** [comment]
Hello.
I has some problems using the codepen, so I created a repo that showcases the problem
```https://github.com/stochris/repro_8570.git```
Just select a person from chat, and that should send you to 2 child states, after which ```removeBackView``` will be called twice. The second call with throw an exception

**Comment by stochris** [comment]
Uhm, not that I want to criticise, but a 10 characters fix of a bug shouldn't take several months without any feedack

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#80
