### ISSUE TITLE
Ionic 2 rc0, npm run build, Error: Could not resolve entry (.tmp/app/main.prod.js)

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#8674]
Hi,

I'm trying to build for production using `npm run build`

When I run the command in the terminal, I'm getting this message:

```
Error: Could not resolve entry (.tmp/app/main.prod.js)
    at /home/ubuntu/workspace/pathfinder/node_modules/rollup/dist/rollup.js:8602:28
    at process._tickCallback (node.js:369:9)
```

Closely followed by this one:

`Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/pathfinder/www/build/main.js'`

What am I doing wrong? Seems a bit weird that a typescript build in a typescript project would be looking for a js file. I have a file called main.prod.ts in that location.

Thanks.

Tom

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#153

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build related issue i have moved this issue to the app-scripts repo.

**Comment by tomgallagher** [comment]
I'd just close this actually. I had some typing errors that stopped a proper build. My mistake.
