### ISSUE TITLE
$text-color not always applied on iOS

### ISSUE THREAD

**Issue by cedWetzel** [driftyco/ionic#8675]
#### Short description of the problem:

Setting the $text-color:  in variables.scss for e.g. to #fff does not affect grid text color or h3 in ion-item-sliding. It works fine on android but not on iOS. 
#### What behavior are you expecting?

Global text colors apply the $text-color as it did on Beta11.

**Steps to reproduce:**
1. Start a new project
2.  change $text-color in variables.scss
3. add an ion-grid to page1
4. build and deploy the project to an iOS device or simulator
5. see normal text colors changed but not in a grid. 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 RC0

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using the latest version `2.1.0`. If you are still seeing this could you provide a plunker or repository that I can use? Thanks :)

<img width="372" alt="screen shot 2017-02-24 at 3 35 22 pm" src="https://cloud.githubusercontent.com/assets/6577830/23319998/f2abb18a-faa6-11e6-9872-2b2f7806a5a9.png">
