### ISSUE TITLE
Toast getting dismissed before the duration is up & other related issues

### ISSUE THREAD

**Issue by eampiart** [driftyco/ionic#8676]
#### Short description of the problem:
The onDidDismiss() function of a Toast sometimes does not get called, or gets called before the set duration of the Toast.
Sometimes the following error also happens:
```
error_handler.js:53 TypeError: Cannot read property 'remove' of null
    at Toast.ViewController.dismiss (view-controller.js:50)
    at ToastCmp.dismiss (toast-component.js:51)
    at toast-component.js:28
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at invoke (polyfills.js:3)
```

where null is `this._nav` in the `ViewController.prototype.dismiss` method.
I could not find any reason or consistency for it to be null or the issue to be happening.

#### What behavior are you expecting?
Toasts correctly call the onDidDismiss method and are not dismissed before the duration set.

**Steps to reproduce:**
Tap the button in the following component:

```
import { Component } from '@angular/core';

import { NavController, ToastController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  isToastShown: boolean = false;

  constructor(
    public nav: NavController,
    public toastCtrl: ToastController
  ) {}

  showToast(): void {
    let toast = this.presentToast()
    this.isToastShown = true;

    toast.onDidDismiss(() => {
      this.isToastShown = false;
    });
  }

  presentToast(): any {
    let toast = this.toastCtrl.create({
      message: 'Toast message',
      duration: 1500,
      position: 'top',
      dismissOnPageChange: true,
    });

    toast.present();

    return toast;
  }
}
```

```
<ion-content padding text-center>
  <button style="margin-top: 60px" ion-button block (click)="showToast()">Show Toast</button>
  <h4>Toast shown: {{isToastShown}}</h4>
</ion-content>
```

*I tried the above snippet in a minimal repo with only this one page and could reproduce the issue.*

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
The Ionic app is running in a WebView in a custom made container app (Android and on iOS).

**Which Ionic Version?**
2.0.0-rc.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: Not installed
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Not installed

**Comment by manucorporat** [comment]
I think this issue was fixed in RC1.
@eampiart can you verify it? please reopen if the problem persist

**Comment by eampiart** [comment]
@manucorporat yes, after updating to RC1, it all works!
