### ISSUE TITLE
Ionic2: White screen of death after fast sequence of taps

### ISSUE THREAD

**Issue by FilipSuk** [driftyco/ionic#8677]
#### Description of the problem:
Example tabs project where you have list of categories on 1st level, list of subcategories on 2nd level and category detail on 3rd level. When you click fast enough in top list of categories (4 fast clicks on one list item) the app "crashes" and all you can see is empty tab.

Working **correctly** when tapping slowly:
![image](http://g.recordit.co/l1legtk1IM.gif)

**Crashes** after 4+ fast taps:
![image](http://g.recordit.co/sO2Fav5sGN.gif)

How the DOM looks after "crash" - **empty div where the page should be**:

![image](https://cloud.githubusercontent.com/assets/6044955/19349720/d5b5c8ec-9154-11e6-928f-2625f4b30de8.png)

**Steps to reproduce:**
1. Download example repo (modified fresh tabs project) https://github.com/cernym43/ionic2-whiteScreen
2. Run in chrome/android device
3. Tap really quickly 4+ times on any item in root list

Problem occurs both in desktop Chrome and Android devices.

#### Unsuccessful solutions to block further tapping

- Ionic loading
- Native loading plugins

 

**Which Ionic Version?** Ionic 2 RC0

#### ionic info

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 

Cheers

**Comment by imcosta** [comment]
Maybe the same issue: https://github.com/driftyco/ionic/issues/8319

**Comment by FilipSuk** [comment]
Problem seems to be solved in RC1. Thanks!

**Comment by adesst** [comment]
here my list of package:
"dependencies": {
    "@ionic/storage": "1.1.6",
    "ionic-angular": "^2.0.0-rc.2",
    "ionic-native": "^2.0.3",
    "ionic2-rating": "0.0.10",
    "ionicons": "^3.0.0",
    "jquery": "^3.1.1",
    "ng2-translate": "^3.2.1",
    "sprintf-js": "^1.0.3",
    "ts-md5": "^1.2.0"
  },

i still having the whitescreen, the step how i reproduce
1. Home (root)
2. tap one of the link 
3. home-menu comes in tap one of the link
4. my-page shown and then i tap back
5. again tap back which in the home-menu
6. again tap the 3 bars in the home
7. whitescreen!

**Comment by mirko77** [comment]
The issue was there on Ionic 1 (iOS), look here https://github.com/driftyco/ionic/issues/6976

and apparently is still there on Ionic 2.

**Comment by antpuleo2586** [comment]
Hi @filipsuk 

How did you know to look for this problem in the first place? Had you seen it in ionic 1 or just stumbled across it? Just curious to know.

We already have an app on the store with this problem (using ionic 1) and so it's a real problem for us.

Did you find any solution or alternative?


Cheers

Ant

**Comment by filipsuk** [comment]
@antpuleo2586 I just stumbled across it and I don't have solution for Ionic 1, sorry.

**Comment by antpuleo2586** [comment]
@filipsuk Thanks for replying. We've literally tried everything and looks like we're either going to go for another framework or native...
