### ISSUE TITLE
bug: [Bug] ionViewCanEnter breaks on navigation

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#8678]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I was testing the `ionViewCanEnter` lifecycle hook to see how it worked, all green when it comes to stopping the initial root component being set, but when setting a new root component that intercepts it's own creation with `ionViewCanEnter` it breaks:
```ts
  ionViewCanEnter() {
    console.log('Can enter.');
    // setTimeout(() => {
    //   this.navCtrl.setRoot(Page2)
    // }, 1000);
    return false;
  }
```

Check this post for a bit more context on the interception on the first root component that worked, if i do the same but with the code above (note the commented timeout, both with and without it gives error) the app gives errors.

![image](https://cloud.githubusercontent.com/assets/9698639/19356384/45fef0a0-9133-11e6-9f03-beca3510a592.png)

</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
add catch:
```
this.nav.push(PAGE).catch(()=>{});
```

**Comment by Luchillo** [comment]
Ah now i remember, that also happened before this version, whenever a promise rejects and there's no error handler like a catch function at the end.

Damn i had so many of those how did i forget about it.

However the redirect thing is still kind of weird, having to put the `setRoot` function call wrapped in `setTimeout` with 0 ms feels weird.
