### ISSUE TITLE
Datetime used as a date picker setting the time

### ISSUE THREAD

**Issue by PabloFNK** [driftyco/ionic#8679]
Hi,

I'm using a DateTime in Ionic2 to pick dates (no time) but when I get the value it has set time.

You can see an example in the next Plunker:

http://plnkr.co/edit/DcQNQ93X06XVVcAyLOlK?p=preview

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! I have made a plunker [here](http://plnkr.co/edit/q4WTACTtdt1PzFvDqpLp?p=preview) that shows how to just display the date. Thanks!

**Comment by PabloFNK** [comment]
@jgw96 Hi, Thanks for your help but my problem is not displaying the date.

The problem is that the DateTime component is returning to me the date saying that the time is 22:00, like this "2016-07-16T22:00:00Z".

This is an issue for me because of my timezone, because if I parse this to be a date:

new Date("2016-07-16T22:00:00Z");

The result is the next day:

Sun Jul 17 2016 00:00:00 GMT+0200 (Romance Daylight Time)

Regards,

PabloFNK.
