### ISSUE TITLE
ion-select not working in popover

### ISSUE THREAD

**Issue by klickagent** [driftyco/ionic#8684]
ion-select does not seem to work inside a popover page.

**Steps to reproduce:**
1. Open http://plnkr.co/edit/6N2D5iPXgm2avjFb5YlT?p=preview
2. Click on select menu (Gender) => no options are shown (seems to be another issue here as well). But select box is closeable through ok or cancel button
3. Open popover from top right. Click on this select menu (Gender) => no options are shown. In addition the select option-menu won't close anymore.

**Which Ionic Version?**  2.0.0-beta.10

http://plnkr.co/edit/6N2D5iPXgm2avjFb5YlT?p=preview

Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind trying this with our newest release, RC1 ? Here is a [link to our changelog](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc0-2016-09-28) that has detailed steps on how to update to RC0. Once all those steps are done you will be ready to update to RC1. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
