### ISSUE TITLE
Scroll: content not scrolling using list of cards

### ISSUE THREAD

**Issue by wshaheer** [driftyco/ionic#8686]
#### Short description of the problem:
I have a segmented view that consists of lists with `ion-card` elements. I am unable to scroll the content.

#### What behavior are you expecting?
Content should scroll.

**Steps to reproduce:**
1. create segmented page using `ion-segment`
2. for each switch case, use `ion-list`
3. within each list, populate it with an array of `ion-card` elements

```
<ion-header>
  <ion-toolbar>
    <ion-segment [(ngModel)]="relationship" >
      <ion-segment-button value="following" >Following</ion-segment-button>
      <ion-segment-button value="public" >Public</ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>
<ion-content padding>
  <div [ngSwitch]="relationship" style="height:100%">
    <ion-list *ngSwitchCase="'following'">
      <ion-card *ngFor="let feed of followingFeed">
          ...
      </ion-card>
    </ion-list>
    <ion-list *ngSwitchCase="'public'">
      <ion-card *ngFor="let feed of publicFeed">
          ...
      </ion-card>
    </ion-list>
  </div>
</ion-content>
```
**Which Ionic Version?** 1.x or 2.x
Ionic 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us!  Would you be able to provide a repo that i can use to reproduce this issue?

**Comment by wshaheer** [comment]
Upon further investigation I discovered that the issue was actually being caused by an error in a separate tab. With that said, aren't different pages/tabs isolated from one another?

**Comment by jgw96** [comment]
Hello! Segments are actually not seperate. It is the same dom element but depending on which segment is selected it will switch out the content. Awesome to hear that your issue is fixed now!
