### ISSUE TITLE
ion-button should have type="button" attribute to avoid clicking it when intro key is pressed

### ISSUE THREAD

**Issue by msaelices** [driftyco/ionic#8689]
#### Short description of the problem:

`ion-button` should have `type="button"` attribute to avoid clicking it when intro key is pressed.

Look at this example:

    <form>
      <ion-list>
        <ion-item>
          <ion-label>Name</ion-label>
          <ion-input [(ngModel)]="data.name" formControlName="name" type="text"></ion-input>
        </ion-item>
        <ion-item>
          <ion-label>Upload a photo</ion-label>
          <button ion-button color="dark" (click)="takePhoto()" block>Take photo</button>
        </ion-item>
      </ion-list>
    </form>

After clicking in the `name` input, a keyboard appears. If click in the "intro" key, automatically `takePhoto()` method is called.

#### What behavior are you expecting?

After pressing the "intro" key, no clicking in any button, except if the next form field button have a "submit" type.

**Other information:**

The reason is that for the browser, a `<button>Click me</button>` is implicitly a `<button type="submit">Click me</button>`, and this will trigger the button when the previous input field is finished (intro implies finish it).

So, by default, the `ion-button` attribute should put a `type="button"` attribute. 
 

**Which Ionic Version?** 2.0-RC0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.4.7

**Comment by msaelices** [comment]
After a second read, I think this is not an issue, because we have the total control of the `<input>`, so the developer himself should put the `type="button"` attribute. Sorry for the noise.

**Comment by sambx** [comment]
Is there a way to control this behavior in case the button is on a dialog like the ones generated by <ion-select>?
