### ISSUE TITLE
UNMET PEER DEPENDENCY with RC.1

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#8691]
When I upgrade to RC.1, npm output:

> +-- UNMET PEER DEPENDENCY @angular/common@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/compiler@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/compiler-cli@^0.6.2
> +-- UNMET PEER DEPENDENCY @angular/forms@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/http@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/platform-browser@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@^2.0.0
> +-- UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0
> +-- ionic-angular@2.0.0-rc.1
> `-- UNMET PEER DEPENDENCY zone.js@^0.6.21
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
> 
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin",
> "arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN @angular/core@2.1.0 requires a peer of zone.js@^0.6.21 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/common@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/compiler@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/compiler-cli@^0.6.2 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/forms@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/http@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was ins
> talled.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of @angular/platform-server@^2.0.0 but none was installed.
> npm WARN ionic-angular@2.0.0-rc.1 requires a peer of zone.js@^0.6.21 but none was installed.
> 

`ionic build` output:

> [10:25:08]  ngc failed: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli has been installed with NPM.
> [10:25:08]  ionic-app-script task: "build"
> [10:25:08]  Error: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli
>             has been installed with NPM.
>

**Comment by rlucian** [comment]
@izee 
I am having similar issues, see #8687 

Tried your solution, but same result. 
Could you detail a few steps:
- how did you upgrade to RC.1, change in package.json file of the app?
- after moving peerDependencies to dependencies, was it solved by npm install, or did you do some other steps?
Thanks.

**Comment by izee** [comment]
@rlucian 
I updated `dependencies in package.json` same as the latest version of  [https://github.com/driftyco/ionic2-app-base/blob/master/package.json](url)

**Comment by izee** [comment]
the dependencies moved from ionic-angular's package.json to app's package.json in RC.1, but not noted in release note.

**Comment by codestellar** [comment]
@izee should I include angular dependencies in my app's package.json?

**Comment by codestellar** [comment]
Working now. Thanks :)

**Comment by Demi-ob** [comment]
How did u get it to work.  Ionic build still fails.  Angular comipler not found

**Comment by rlucian** [comment]
@Demi-ob did you tried refreshing your environment?
delete everything inside node_modules and do npm install after you make sure your package.json has all base packages at the correct version.

**Comment by Demi-ob** [comment]
@rlucian  i have done that reinstalled eveything bt it still doesnt work. Even when i start new apps the error remains.  Serve is working well but ionic build android shows:


[11:59:24]  ngc failed: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli
            has been installed with NPM.
[11:59:25]  ionic-app-script task: "build"
[11:59:25]  Error: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli
            has been installed with NPM.

**Comment by rlucian** [comment]
i am guessing you already tried
```npm install @angular/compiler-cli```
could you post the output of that? you should get something like:
````-- @angular/compiler-cli@0.6.2```

**Comment by Demi-ob** [comment]
$ npm install @angular/compiler-cli@0.6.2

C:\Users\***\hubble2\ng-xi18n -> C:\Users\***\hubble2\node_modules\@angular\compiler-cli\src\extract_i18n.js
C:\Users\***\hubble2\ngc -> C:\Users\***\hubble2\node_modules\@angular\compiler-cli\src\main.js
ionic-app-base@ C:\Users\***\hubble2

+-- UNMET DEPENDENCY @angular/compiler@2.0.0
+-- @angular/compiler-cli@0.6.2
| `-- UNMET PEER DEPENDENCY typescript@^2.0.2
+-- UNMET DEPENDENCY @angular/core@2.0.0
`-- UNMET DEPENDENCY @angular/platform-server@2.0.0

npm WARN @angular/compiler-cli@0.6.2 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.2 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.6.2 requires a peer of @angular/platform-server@^2.0.0 but none was installed.
npm WARN @angular/compiler-cli@0.6.2 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @angular/tsc-wrapped@0.3.0 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.1.7 requires a peer of typescript@^2.0.0 || ^2.1.0-dev but none was installed.



i have also tried installing the unmet dependencies individually and it succeed but it seems they just never stay. I have exhausted all options and reinstalled everything re-installable

if i remove the "0.6.2" in the npm install "@angular/compiler@0.6.2" i then get

$ npm install @angular/compiler-cli

C:\Users\DEMI\***\hubble2\ngc -> C:\Users\***\hubble2\node_modules\@angular\compiler-cli\src\main.js
C:\Users\***\hubble2\ng-xi18n -> C:\Users\DEMI\***\hubble2\node_modules\@angular\compiler-cli\src\extract_i18n.js
- parse5@1.3.2 node_modules\@angular\compiler-cli\node_modules\parse5
ionic-app-base@ C:\Users\***\hubble2
+-- UNMET DEPENDENCY @angular/compiler@2.0.0
+-- @angular/compiler-cli@2.1.1  invalid
| `-- UNMET PEER DEPENDENCY typescript@^2.0.2
`-- UNMET DEPENDENCY @angular/core@2.0.0

npm WARN @angular/compiler-cli@2.1.1 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@2.1.1 requires a peer of @angular/compiler@2.1.1 but none was installed.
npm WARN @angular/compiler-cli@2.1.1 requires a peer of @angular/core@2.1.1 but none was installed.
npm WARN @angular/tsc-wrapped@0.3.0 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.1.7 requires a peer of typescript@^2.0.0 || ^2.1.0-dev but none was installed.
  

npm outdated gives
Package                                  Current         Wanted      Latest  Location
@angular/common                            2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/compiler                          2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/compiler-cli                      0.6.2          0.6.2       2.1.1  ionic-app-base
@angular/core                              2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/forms                             2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/http                              2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/platform-browser                  2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/platform-browser-dynamic          2.0.0          2.0.0       2.1.1  ionic-app-base
@angular/platform-server                   2.0.0          2.0.0       2.1.1  ionic-app-base
@ionic/storage                             1.0.3          1.0.3       1.1.6  ionic-app-base
firebase                                   3.4.1          3.4.1       3.5.1  ionic-app-base
ionic-native                               2.2.3          2.2.3       2.2.4  ionic-app-base
moment                                    2.13.0         2.13.0      2.15.1  ionic-app-base
rxjs                               5.0.0-beta.12  5.0.0-beta.12  5.0.0-rc.1  ionic-app-base
zone.js                                   0.6.21         0.6.21      0.6.26  ionic-app-base



node -v: 6.7.0
npm -v :3.10.3
ionic -v: 2.1.1

Any hope for me
