### ISSUE TITLE
[RC0 & RC1] search bar causes Attempt to use a destroyed view

### ISSUE THREAD

**Issue by abhayastudios** [driftyco/ionic#8693]
As of RC0 (also in RC1) it seems that using the search bar for filtering results in an error `Attempt to use a destroyed view`. Despite the error in the console the behaviour seems ok. Anyway in this [post](https://forum.ionicframework.com/t/ionic-2-ion-searchbar-searching-only-when-enter-is-pressed/42003/17) Richard explains he circumvented the error from happening by modifying the change detection:

```
import { ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';

changeDetection: ChangeDetectionStrategy.OnPush,

this.ref.markForCheck();
```

It seems however that this should work out of the box.

Thanks!

**Comment by jgw96** [comment]
Hello @abhayastudios , am i correct in understanding that this only happens with virtualscroll? Also, could you provide a repo I could use to reproduce this issue? Thanks!

**Comment by abhayastudios** [comment]
@jgw96 not sure regarding the virtual scroll. Do you have a plunker stub with RC0/RC1 for me to reproduce it in?

Thanks!

**Comment by jgw96** [comment]
@abhayastudios Unfortunately not yet, a gist of the afflicting code would work though 😄

**Comment by abhayastudios** [comment]
@jgw96 ok so below you can find a simplified version of my component. It does seem to be related to virtual scroll: when I use the virtual scroll as below I get the said error, however when replace the virtual scroll with an ngFor (as in the comment) everything works smooth.

```
import {Component} from '@angular/core';
import {SessionProvider} from '../providers/session';
import {ViewController, Events} from 'ionic-angular';

// child component containing contact search modal
@Component({
  template: `
    <ion-header>
      <ion-toolbar light>
        <ion-title>Add Contact</ion-title>
        <ion-buttons end>
          <button ion-button (tap)="closeModal()"><ion-icon name="close"></ion-icon></button>
        </ion-buttons>
      </ion-toolbar>
      <ion-toolbar light>
        <ion-searchbar (ionInput)="searchContacts($event)" placeholder="Search Phonebook" debounce="400"></ion-searchbar>        
      </ion-toolbar>
    </ion-header>
    <ion-content>
 <!--
      <ion-list>
        <ion-item *ngFor="let contact of contactsFound">
-->
      <ion-list [virtualScroll]="contactsFound" [bufferRatio]="5" [approxItemHeight]="'55px'">
        <ion-item *virtualItem="let contact">
          <ion-label>
            <span class="item-text-center">{{contact.name}}</span>
          </ion-label>
          <button ion-button dark clear small (tap)="addContact(contact)" item-right><ion-icon ios="ios-add" md="md-add"></ion-icon></button>
        </ion-item>
      </ion-list>
    </ion-content>
  `
})
export class AddContactModalComponent {
  public contactsFound:Array<any> = [];

  constructor(public viewCtrl: ViewController, public events: Events, public session: SessionProvider) {
  }

  public ionViewDidEnter() {
    this.contactsFound = this.session.cachedPhonebook;
  }

  public searchContacts(event) {
    let regex = new RegExp(event.target.value, 'i');
    this.contactsFound = this.session.cachedPhonebook.filter((contact) => regex.test(contact.name));
  }

  public addContact(contact) {
    this.events.publish('addContact', contact); // send contact object through event to parent
    this.closeModal();
  }

  public closeModal() {
    this.viewCtrl.dismiss();
  }
}
```

**Comment by brandyscarney** [comment]
@abhayastudios Are you still running into this problem on the most recent version of Ionic? I see the similar issue (https://github.com/driftyco/ionic/issues/9650) was closed. Has this also been resolved?

**Comment by abhayastudios** [comment]
Hi @brandyscarney, thanks for checking up on me. To be honest, I migrated my project to Nativescript in the meantime so I didn't check on it anymore.
