### ISSUE TITLE
First element in sidemenu hidden behind menu title (RC.1)

### ISSUE THREAD

**Issue by jonnysmith1981** [driftyco/ionic#8694]
#### Short description of the problem:
The first element of a sidemenu is sitting behind the menu title. Re-tested in rc.0 and first menu item is correctly displayed.

RC.1 Sidemenu
<img src="https://cloud.githubusercontent.com/assets/8254912/19380182/f2a82dca-91ed-11e6-902b-0b2081df767e.jpg" width=33%></img>

RC.0 Sidmenu
<img src="https://cloud.githubusercontent.com/assets/8254912/19380195/07b37b20-91ee-11e6-8c3f-d23d8db37313.jpg" width=33%></img>

#### What behavior are you expecting?
Sidemenu items should appear below the menu title.
 

**Which Ionic Version?** 2.0.0.rc.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by brandyscarney** [comment]
Please make sure you are placing your `ion-toolbar` inside of an `ion-header` element. See the docs here: http://ionicframework.com/docs/v2/api/components/toolbar/Header/

An example of this is in the conference app: https://github.com/driftyco/ionic-conference-app/blob/master/src/app/app.template.html#L5-L9

**Comment by jonnysmith1981** [comment]
@jgw96 Ok, i havent done this very often, please be gentle...

Here is the repo showing the problem https://github.com/jonnysmith1981/ionic2menu

As i mentioned up top, this worked fine on rc.0

**Comment by jgw96** [comment]
@jonnysmith1981 Would you mind giving @brandyscarney 's suggestion a try? Thanks!

**Comment by jonnysmith1981** [comment]
@jgw96 The suggestion by @brandyscarney to structure my HTML correctly has worked. Who knew?

_drinks all round_

**Comment by RyanMcDonald** [comment]
This bit me too. Please update the 'Basic Usage' example in the [docs](http://ionicframework.com/docs/v2/components/#menus) in case someone else runs into this.

**Comment by brandyscarney** [comment]
Created an issue for it here: https://github.com/driftyco/ionic-site/issues/838 Thanks @RyanMcDonald!
