### ISSUE TITLE
RC1 - Failed to load resource

### ISSUE THREAD

**Issue by pufanalexandru** [driftyco/ionic#8698]
I've updated to RC1 by modifying my `package.json`. When I run `ionic serve`, the result in `localhost:8100` is blank page displaying these errors:

`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8100/build/main.css`
`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8100/build/main.js`

It seems that the files are never built, as the `www/build` directory contains only one file, `polyfills.js`.

System info:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.5.0

**Comment by six006** [comment]
using the latest "@ionic/app-scripts": "^0.0.33"

**Comment by pufanalexandru** [comment]
I've tried it, but unfortunately, it's still not working (same error)

**Comment by m927259903** [comment]
i have the same problem. even if update ionic-app-scripts to latest version.

**Comment by pufanalexandru** [comment]
Strange enough, if I create a new project and copy the `src` folder from the old one, it works well.

**Comment by m927259903** [comment]
:+1:

**Comment by juliolemesti** [comment]
Had the same problem, went back do app-scripts 0.0.30 and it solved the issue.

**Comment by kabus202** [comment]
@juliolemesti  thanks, works after changing it to 0.0.30

**Comment by patrickmcd** [comment]
I was getting the same blank page. And if it helps, after saving a file and kicking off the watch, I'd get this:

```
ionic $ [10:38:41]  template update started ...
[10:38:41]  bundle update started ...
(node:20102) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Could not resolve './app.module' from /Users/me/Work/test-app/src/app/main.dev.ts
```

Back to 0.0.30 I go.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#166

**Comment by jgw96** [comment]
Hello all! Since this was a build related issue and not a framework issue i have moved this issue to the app-scripts repo. Thanks!
