### ISSUE TITLE
[RC1]ionic serve build error

### ISSUE THREAD

**Issue by six006** [driftyco/ionic#8699]
Ionic2 RC1 using command 'ionic serve' return the error

[18:34:26]  copy finished in 9.91 s
(node:131600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rej
ection id: 1): Error: Could not resolve './app.module' from D:\Javascript\ionic-
conference-app-master\src\app\main.dev.ts

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.8.0

**Comment by six006** [comment]
using the latest "@ionic/app-scripts": "^0.0.33" solve the error

**Comment by azakusilo** [comment]
How to do this?

**Comment by basvdijk** [comment]
Change the line describing `@ionic/app-scripts` in your `package.json`, throw away your `node_modules` folder and run `npm install`

**Comment by azakusilo** [comment]
Thank you

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/166.
