### ISSUE TITLE
Cannot set tab position to top.

### ISSUE THREAD

**Issue by SadamChami** [driftyco/ionic#8701]
I add the following code to make the tabbar to top.

```
<ion-tabs tabbarPlacement="top" >
    <ion-tab tabTitle="Store" [root]="tab1"></ion-tab>
    <ion-tab tabTitle="Tiler" [root]="tab2"></ion-tab>
  </ion-tabs>
```

 But after that, It works fine in browser. But when i compiled in to devices by 'ionic build ios' Then it will show the following error in terminal.

**Property 'tabbarPlacement' is private and only accessible within class 'Tabs'**

Then i try to change framwork.

'{app_path}/node_modules/ionic-angular/components/tabs/tabs.d.ts'

But then i tried to make the private 'tabbarPlacement' to public. Then there were no errors. I think that error was because of private variable.

 

My system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jonnysmith1981** [comment]
https://github.com/driftyco/ionic/issues/7143

**Comment by SadamChami** [comment]
Yeah, My bad.
