### ISSUE TITLE
Ripple effect on list items [Enhancement]

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic#8703]
#### Short description of the problem:
On beta.11 I was able to use buttons inside list, but seems like it's no longer working on RC.X

#### What behavior are you expecting?
Be able to see ripple effect like in native lists when tapping an element.

**Comment by Chris1308** [comment]
Did you checkout the changelog? https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#new-behavior-of-button

**Comment by ZiFFeL1992** [comment]
Ohh closing this, thanks!
