### ISSUE TITLE
this.test has different value when called in eventlistener of leaflet-map

### ISSUE THREAD

**Issue by sosnet** [driftyco/ionic#8704]
#### Short description of the problem:
I'm using **leaflet@1.0.1** with **@types/leaflet@1.0.35**. In my example code I have a function `show()` and an instance member `test`. On initial I set `this.test = true;` and when calling `show()` the console shows `true`. But when I call `show()` in the eventListener of the leaflet-map it's always `undefined`.

#### What behavior are you expecting?
If I call the function `show()` in the eventListener it should read the same instance members as when directly call `show()`.

**Steps to reproduce:**
1. Click on the button
2. Click on the map
3. See different output in the console

**test-page.ts**
```
import {Component} from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';
import 'leaflet';

@Component({
  templateUrl: 'test-page.html'
})

export class TestPage {
  test: boolean;
  map: L.Map;

  ngOnInit(): void {
    this.test = true;
    this.initMap();
  }

  initMap(): void {
    this.map = L.map('map')
      .setView([51.505, -0.09], 13);

    L.tileLayer('https://api.tiles.mapbox.com/v4/mapbox.streets-basic/{z}/{x}/{y}.png?access_token=***', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
      maxZoom: 18
    }).addTo(this.map);

    this.map.on('click', this.show);
  }

  show(): void {
    console.log("test: " + this.test);
  }
}
```

**test-page.html**
```
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>TEST PAGE</ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <div style="height: 180px" id="map"></div>
  <div><button ion-button (click)="show()">SHOW</button></div>
</ion-content>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 
2.0.0-rc.0

#### Plunker that shows an example of your issue

http://plnkr.co/edit/UZ8cMAzC7RPIvoCsofUr?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v6.8.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
