### ISSUE TITLE
rc.1 Serve failing: unable to find "\src\app\main.dev.ts" 

### ISSUE THREAD

**Issue by aamir1995** [driftyco/ionic#8705]
#### Short description of the problem:
After updating my project to latest Ionic 2.rc.1, I got the following error on` ionic serve`

> unable to find \src\app\main.dev.ts
> 
> (node:3316) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve './app.module' from \src\app\main.dev.ts

#### What behavior are you expecting?

**Steps to reproduce:**
1. clone the following repo: https://github.com/uqutub/imageSharing.git
2. switch to branch `rc.1`
3. run `ionic serve`

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.6.0

**Comment by Chris1308** [comment]
Try npm install @ionic/app-scripts@latest

**Comment by aamir1995** [comment]
@Chris1308 Thanks, Your solution is working fine :)
