### ISSUE TITLE
[RC1] ion-toolbar position="bottom" is rendered on top

### ISSUE THREAD

**Issue by miloslavskacel** [driftyco/ionic#8709]
#### Short description of the problem:

ion-toolbar position="bottom" overlays first items of menu, 
in [RC0] it was rendered on bottom

#### What behavior are you expecting?

it is rendered on bottom

```
<ion-menu [content]="content" side="right" persistent="true">
	<ion-content>
		<ion-list>
			<button ion-item menuClose *ngFor="let p of rigthMenuPages" (click)="openPage(p)">
                {{p.menuTitle | translate}}
            </button>
			<button ion-item (click)="logout()">{{ '_logout' | translate }}</button>
		</ion-list>
	</ion-content>
	<!-- toolbar overlays first menu items in ionic 2 RC1
    <ion-toolbar position="bottom">
        <ion-label padding>{{ '_app_version' | translate: {version: appVersion} }}</ion-label>
    </ion-toolbar>
    -->
</ion-menu>
<ion-nav #content [root]="rootPage"></ion-nav>
```
![screen shot 2016-10-14 at 16 34 58](https://cloud.githubusercontent.com/assets/2547672/19391272/264fb240-922c-11e6-8d85-b87c7fc19907.png)

**Which Ionic Version?** 

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jonnysmith1981** [comment]
I've raised something similar: https://github.com/driftyco/ionic/issues/8694

**Comment by brandyscarney** [comment]
The position attribute was removed in `beta.10`: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta10-2016-06-27

It should be placed inside of an `ion-header` (for top positioning) or an `ion-footer` (for bottom positioning). See the docs here: http://ionicframework.com/docs/v2/api/components/toolbar/Footer/

**Comment by miloslavskacel** [comment]
it helped, thanks
