### ISSUE TITLE
Feature ion-photo-gallery

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic#871]
Can You make such component?
 I see it like this:
ion-photo-gallery fullscreen="true/false"
img src
img src
img src
/ion-photo-gallery

It would show slidable pictures on black screen adjust to screen size keeping aspect ratio.

What do Yuo think?

**Comment by Purus** [comment]
This would be a great plugin addition to Ionic. +1

**Comment by Gijobs** [comment]
+1 !
