### ISSUE TITLE
Ionic 2 RC0: Some spinner components don’t work on Edge or Firefox (repost)

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#8714]
#### Short description of the problem:
Some spinner components don’t work on Edge or Firefox, such as dots, bubbles and circles, including the default WP spinner.

#### What behavior are you expecting?
All spinner components should work as normal in every supporting browser.

**Steps to reproduce:**

1. Open http://ionicframework.com/docs/v2/demos/src/loading/?production=true&ionicplatform=windows in Microsoft Edge 13/Firefox Nightly 52
2. See what happens in the dots, bubbles and circles spinners and their corresponding loading indicators.

```js
        var loading = this.loadingCtrl.create({
            spinner: 'dots',
            content: 'This is the "dots" spinner. It will dismiss after 3 seconds.',
            duration: 3000
        });
        loading.present();
```

**Which Ionic Version?** 1.x or 2.x
2.0.0 RC 0

Sorry for the inconvenience.

**Comment by manucorporat** [comment]
@infinnie fixed!
