### ISSUE TITLE
0.0.34 of scripts makes the serve & build fail

### ISSUE THREAD

**Issue by samvloeberghs** [driftyco/ionic#8718]
#### Short description of the problem:

app-scripts 0.0.34 makes the build & serve fail.
reverting to 0.0.30 makes it work

&  I still experience major memory leaks using ionic serve

#### What behavior are you expecting?

**Steps to reproduce:**
1.  install latest changes with 0.0.34 for app-scripts
2. try to do ionic serve:
main.js main.css not found 404
3.  revert to 0.0.30 makes it work

**Which Ionic Version?** 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Not installed

**Comment by 255kb** [comment]
Same problem here, the app was correctly building on Oct 6 with ionic-app-script 0.0.30, and since yesterday the build is not working anymore. I tried with ionic-app-script 0.0.33, 0.0.35 and with Ionic  v2rc0 and rc1.
The build seems to be successful but the browser console shows 404s for `main.js` and `main.css` (I have the same `ionic info` as above).

**Comment by iRoachie** [comment]
I got mine working, after removing node_modules then installing. The I saw errors in my app.module.ts. For my imports of my pages, I have an index file in the directory which imports all the pages. 

Then in the app.module I just import that index. `import { pages } from '../pages';` 
Apparently this throws and error now and I had to use `import { pages } from '../pages/index';`. Not sure if this helps but check

**Comment by 255kb** [comment]
@iRoachie I tried to remove and reinstall node_modules many times but no luck for me :(

**Comment by devarg** [comment]
Hi how are you all doing?
I think you may be interested in this too (#170) and closed (#155) updated a pretty detailed panorama for 0.34 and 0.35. And i was back on 0.0.32 until an hour ago @adamdbradley dropped 0.0.36 which made ENORMOUS improvements in template live reload. Now they work great! Check it out!

**Comment by Bouzmine** [comment]
You may also want to upgrade ionic-cli to latest as it brings a fix preventing memory leaks (`npm install -g ionic@latest`)

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us! I would suggest updating to v0.0.36 of app-scripts by running this command `npm install @ionic/app-scripts@latest --save-dev`. I would also recommend updating to the latest release of the cli as @Bouzmine recommended above. Also, make sure the package.json of your app looks like this package.json of our app-base here https://github.com/driftyco/ionic2-app-base/blob/master/package.json. Thanks everyone! I am going to close this issue for now as the above should solve it, but if you still have issues feel free to reply and i will reopen.

**Comment by 255kb** [comment]
Thank you it's working!
