### ISSUE TITLE
[RC0,1]Inheriting page breaks app, @ViewChild property is undefined

### ISSUE THREAD

**Issue by Screeze** [driftyco/ionic#8720]
#### Short description of the problem:
My App contains a tab controller with multiple tabs. 2 of the tabs are highly similar since I wrote a generic component which can cover both pretty well with just a small configuration change.

So I have all the logic in the first Page (`TSPage`) class and template and made the second page (`MyTSPage`) extend the first, adjusting some properties in the constructor, like shown below.
`TSPage` works well, but clicking the tab of the second page breaks the app with an error.
TypeError: Cannot set property 'enabled' of undefined.

I think it happens here, which is part of `TSPage` (stacktrace seems useless and points to a location without any "enabled"):
`this.refresher.enabled = false;`

With refresher being (at `TSPage`):
```
@ViewChild(Refresher)
public refresher: Refresher;

```
#### What behavior are you expecting?
I would expect the page works well when I inherit a second page from the first, but somehow the @ViewChild seems to not resolve properly.

```
@Component({
    templateUrl: 'ts.html',
    selector: 'my-ts-page'
})
export class MyTSPage extends TSPage {

    constructor(protected navCtrl: NavController,
                public app: App,
                public modalCtrl: ModalController,
                public tsProvider: TSMockProvider) {
        super(navCtrl, app, modalCtrl, tsProvider);
        this.mode = 'own';
        this.segment = 'upcoming';
    }
}

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?**
Ionic 2 rc0 and rc1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v4.4.5

**Comment by Screeze** [comment]
I found a workaround: 
Copying over all ViewChild properties also to MyTSPage fixes it. However, I don't think this duplication should be needed?!?

```
@Component({
    templateUrl: 'ts.html',
    selector: 'my-ts-page'
})
export class MyTSPage extends TSPage {

    @ViewChild(Content)
    public content: Content;
    @ViewChild(InfiniteScroll)
    public infiniteScroll: InfiniteScroll;
    @ViewChild(Refresher)
    public refresher: Refresher;

    constructor(protected navCtrl: NavController,
                public app: App,
                public modalCtrl: ModalController,
                public tsProvider: TSMockProvider) {
        super(navCtrl, app, modalCtrl, tsProvider);
        this.mode = 'own';
        this.segment = 'upcoming';
    }
}

```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a repo or gist that we can use to reproduce this issue?

**Comment by manucorporat** [comment]
This is a known angular 2 issue: https://github.com/angular/angular/issues/5415

**Comment by Screeze** [comment]
Thanks, you are right.
