### ISSUE TITLE
Ionic Cloud Documentation Issues

### ISSUE THREAD

**Issue by artforlife** [driftyco/ionic#8724]
#### Short description of the problem:
Unclear documentation and tutorials.

#### What behavior are you expecting?
It is unclear which files need to be edited to replicate the tutorial. It would be REALLY helpful if you made it to be step-by-step. Please indicate to which files the code needs to be added.

http://docs.ionic.io/services/auth/#summary

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#213

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an Ionic Cloud related issue and not an Ionic framework related issue I have moved this issue to that repo. Thanks!
