### ISSUE TITLE
[RC0][RC1] Regression: [navPush] not usable inside element with *ngIf or *ngFor

### ISSUE THREAD

**Issue by alex-pl** [driftyco/ionic#8727]
If an element that is created delayed by `*ngIf` or `*ngFor` contains a sub element with a `[navPush]` attribute, an exception gets thrown.

> Error: Error in ./Page class Page - inline template:13:4 caused by:
> Expression has changed after it was checked. Previous value: 'undefined'. Current value: '#'.

The problem was introduced in Ionic 2.0.0-rc.0.

It's a very commonly used functionality in our app.

<br>

## Test Case

The full test case is available here: https://github.com/alex-pl/ionic-ngIf-ngFor-navPush-issue

_page.html_

```HTML
<!-- works -->
<a *ngIf="enabled" [navPush]="anotherPage">Hello =)</a>


<!-- throws exception -->
<div *ngIf="enabled">
    <a [navPush]="anotherPage">Hello =)</a>
</div>

<div *ngFor="let val of array">
    <a [navPush]="anotherPage">{{ val }}</a>
</div>
```

_page.ts_

```TypeScript
import { Component } from '@angular/core';
import { AnotherPage } from './another-page';

@Component({
  templateUrl: 'page.html'
})
export class Page {

  public anotherPage = AnotherPage;

  public enabled = false;
  public array = [];

  // short delay
  ionViewDidEnter() {
      this.enabled = true;
      this.array = ['Hey :)', 'Huhu \\o/', 'Hi ;)'];
  }

}
```
<br>
_Note:_ This might be related to #8563, but it's a much simpler scenario.

**Comment by manucorporat** [comment]
@jgw96 I saw you were able to reproduce this issue. but I can't...
added this e2e test: c902206

**Comment by alex-pl** [comment]
I replaced my `app-module.ts` with yours, added the `main.html` and I'm still able to reproduce the issue in all tested browsers (Firefox, Chrome and Safari) while using your code.

Maybe it's important to note that the links _do_ work, but the exception is thrown. The exception breaks not all but most of the following JavaScript code.

I've created a branch with your code:
https://github.com/alex-pl/ionic-ngIf-ngFor-navPush-issue/tree/e2e-test

You can test it by running `ionic serve`.
Maybe there were changes between rc.1 and the current repository code in that area?

**Comment by manucorporat** [comment]
Ok, I was able to reproduce it! It should be fixed: https://github.com/driftyco/ionic/commit/8b07e6c55b4e57fc16ba51df3b91f978616422ec
