### ISSUE TITLE
Low-end mode, disabling animations across the whole UI

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#8733]
Imo it is better to have an UI without animations than janky ones.

Animations are usually used to modify our illusion of time in a way the same application looks faster, but non-smooth animations have the opposite effect and at the same time they add a non negligible overhead.
https://medium.com/swlh/the-illusion-of-time-8f321fa2f191#.lwgofrkl9

In slower devices an animation is janky and at the same the time more CPU resources are wasted, so content presentation is delayed even more.

I propose a "low-end" mode for Ionic 2. It could be enable with a global configuration, that adds a "slow-end" class in the `<ion-app>` element. And the components across the framework can read it to conditionally run their animations.

**Comment by manucorporat** [comment]
https://github.com/driftyco/ionic/issues/8710

**Comment by javierprovecho** [comment]
I think this is a great idea specially for accessibility. Some requisites include the reduction of movement and being able to auto configure on OS (iOS/Android) requests, it would be great. Also the reduction of movement is applied to some native apps when battery is low. This will help reduce some of the HTML rendering.

**Comment by ghenry22** [comment]
this could also potentially be branded as a "low power mode" as mentioned, if it could then be toggled dynamically during app use it would be a really handy little tool for any ionic app.

**Comment by daveshirman** [comment]
@ghenry22 Exactly what I was thinking.  This would be a really good bullet point when marketing an Ionic 2 app.

**Comment by brandyscarney** [comment]
Sounds good to me @manucorporat :+1: We can discuss the naming. ;)

**Comment by aemr3** [comment]
Any progress on this? Low-end mode would be great for phones like iPhone 4S. Ionic apps are really slow on some phones.

**Comment by graphefruit** [comment]
@aemr3 Try crosswalk meanwhile?

**Comment by aemr3** [comment]
We are already using WKWebView for iOS and Crosswalk for Android. They don't help much because of the poor performance of cpus.

**Comment by graphefruit** [comment]
I see, crosswalk helped a lot on my old Android devices (Note 1 e.g.) with Android 4.1.

But the most parts I needed to do was disabling and cleaning css on my own (project wasn't with ionic)

**Comment by graphefruit** [comment]
@manucorporat Any news on this topic?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#218

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#219

**Comment by vaskou** [comment]
Sorry but the links, where the issues moved to, don't work.

**Comment by graphefruit** [comment]
@vaskou Thats right, its because its an private repo and not for public
