### ISSUE TITLE
No Modal Dismiss on setRoot

### ISSUE THREAD

**Issue by n00b42** [driftyco/ionic#8734]
#### Short description of the problem:
- Assume you have 2 pages and a modal.
- Then from Page1 we open the Modal.
- While the modal is still open we issue "setRoot" to Page2 on the root nav.
- The Modal remains visible and is not dismissed.
(Page1 is successfully poped and Page2 popped in the "background")

#### What behavior are you expecting?
As it is stated that a modal is pushed to the nav stack and setRoot is said to destroy elements on the nav stack.
Therefore, I would expect the modal to be dismissed too. 

#### Ionic info
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 10
Node Version: v6.7.0

#### Probably related
#8437

**Comment by n00b42** [comment]
OT: Is there already a Plunker template for RC0 or RC1?

**Comment by manucorporat** [comment]
Modals are not longer part of the main stack. You have to pop the modal manually, or activate the dismissOnPageChange setting.

**Comment by n00b42** [comment]
Thank you for the explanation.

**Comment by n00b42** [comment]
@manucorporat Actually, there seems to be no "dismissOnPageChange" for Modals, only for Toasts and Loading. At least not within ModalOptions

**Comment by manucorporat** [comment]
@n00b42 you are right. I think dismissOnPageChange is not available in modal, because pushing a page inside modal would dismiss it.

I would suggest you to manually close the modal when you `setRoot`.

**Comment by n00b42** [comment]
@manucorporat Actually, setRoot is called from somewhere else, so its a bit tricky for the modal to "know" when it should close.... but I will think about a workaround
Thank you for your time :)
