### ISSUE TITLE
[RC1] navCtrl.pop() from TabsPage

### ISSUE THREAD

**Issue by delian7** [driftyco/ionic#8737]
#### Short description of the problem:

I have a page with no tabs that when you click on a button pushes a tabsPage (with three tabs) to the navigation controller.

I have a goBack function that is simply this.navCtrl.pop() and I invoke from any of the tabbed pages header. Executing the function leads me to a blank screen. 

#### What behavior are you expecting?

In beta 11 clicking on that button would lead me back to the root page (page with no tabs) but in RC1 it leads to a blank screen.

**Steps to reproduce:**
1. `this.navCtrl.push(TabsPage)` from a non-tabbed page.
2. `this.navCtrl.pop()` from a tabbed page to go to root non-tabbed page. 
 
**Which Ionic Version?** 1.x or 2.x
 Ionic 2 RC1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

--------------------------------
--------------------------------

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a 

--------------------------------

**Expected Behavior in Beta11:**
![beta11](https://cloud.githubusercontent.com/assets/4530694/19419237/2891eeee-9388-11e6-9ed1-03b491f3b785.gif)

**Actual Behavior in RC1**
![rc1](https://cloud.githubusercontent.com/assets/4530694/19419240/324e87da-9388-11e6-8d0b-3be04f0c2bc6.gif)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting a repo or gist that I can use to reproduce this issue?

**Comment by delian7** [comment]
Hi @jgw96. I would be more than happy to post one. Is there an updated plunker/codepen/jsfiddle that I can use with RC1?

**Comment by delian7** [comment]
@jgw96 I created this ionic2 rc1 app that demonstrates what I mean. https://github.com/delian7/ionic2-starter-app-pop-tabs-bug


![rc1](https://cloud.githubusercontent.com/assets/4530694/19421575/38537ca4-93b9-11e6-94d6-fc806e1c8f9b.gif)

**Comment by manucorporat** [comment]
@delian7 each tab has his own navigation stack, so when you do `this.nav.pop()`, you are popping  the root tab page at that leads to a blank page.

You have to get the parent nav controller and pop from there:

```ts
this.nav.parent.pop()
```

**Comment by delian7** [comment]
@manucorporat @jgw96 thanks for the help.

**Comment by Alwayslazydog** [comment]
@delian7  excuse me, i have the same issue that will make the pop() to a incomplete page.
 On the tab page i comment out another two tab item.
 And in the tab 1 page, i add a component "a" to show the item list,  
and in the root page ,i have an another component "b" in tab root page , it can push a new page "B" to add a new item. 
In the Page "B" ,i have a plugin "image picker" and a text area, then  the issue is if i click the  text area,
// whatever i type or not 
the pop() will return to the Root Page, but nothing component "b" data  was rendering .
