### ISSUE TITLE
Loading dismissOnPageChange triggered by Toast

### ISSUE THREAD

**Issue by n00b42** [driftyco/ionic#8740]
#### Short description of the problem:

A Loading with "dismissOnPageChange" set is dismissed if a Toast is shown/vanishs.
#### What behavior are you expecting?

As I dont think a Toast should be considered a "page change" I would expect the Loading to stay visible until I dismiss it on my own OR actually change the "current" page..
#### Ionic info

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 10
Node Version: v6.7.0

**Comment by Tiuser4567** [comment]
This issue also happens for Loading + Loading combinations.
L1 has dismissOnPageChange = true
L1 and L2 are shown, if L2 is dismissed, L1 will be dismissed also.

**Comment by arcaileus** [comment]
I am seeing a similar problem with Toast + Toast combinations.  If dismissOnPageChange is set to true and a toast message is created while another toast message is still visible the first toast message is removed, the new toast message appears very briefly before it too is removed no matter how long the duration is set to.  If dismissOnPageChange is set to false the second toast message replaces the first, but it does remain on the screen for the correct duration.

This is with using Ionic 2 RC2.  I wonder if pull request #9034 tries to resolve this.

**Comment by brandyscarney** [comment]
This should be fixed by https://github.com/driftyco/ionic/pull/9747. If you are still having the issue using the latest (2.0.0-rc.6) please let me know and I will reopen. Thanks!
