### ISSUE TITLE
Two taps required to focus a contentEditable

### ISSUE THREAD

**Issue by calummoore** [driftyco/ionic#8741]
#### Short description of the problem:

When selecting the contentEditable element, the first tap does not focus the element.
#### What behavior are you expecting?

It should focus the contentEditable element.

**Steps to reproduce:**
1.  Focus is set to an input element
2. contentEditable element is tapped (nothing happens)
3. contentEditable is tapped again (it now works)

The cause of the issue is tapMouseDown - which calls `preventsDefault()` under certain circumstances. Text elements are already excluded from this, but the contentEditable isn't (anywhere a text element is excluded the contentEditable should be as a rule of thumb). 

```
function tapMouseDown(e) {
  //console.log('mousedown ' + Date.now());
  if (e.isIonicTap || tapIgnoreEvent(e)) return null;

  if (tapEnabledTouchEvents) {
    //console.log('mousedown', 'stop event');
    e.stopPropagation();

    //console.log('tapMouseDown', ionic.tap.isContentEditable, , tapLastTouchTarget, tapActiveElement());

    if (!ionic.Platform.isEdge() && (!ionic.tap.isTextInput(e.target) || tapLastTouchTarget !== e.target) &&
      !isSelectOrOption(e.target.tagName) && !ionic.tap.isVideo(e.target)) {
      // If you preventDefault on a text input then you cannot move its text caret/cursor.
      // Allow through only the text input default. However, without preventDefault on an
      // input the 300ms delay can change focus on inputs after the keyboard shows up.
      // The focusin event handles the chance of focus changing after the keyboard shows.
      // Windows Phone - if you preventDefault on a video element then you cannot operate
      // its native controls.
      e.preventDefault();
    }

    return false;
  }

```

We need to make the if statement as follows:

```
(!ionic.Platform.isEdge() && (!ionic.tap.isTextInput(e.target) || tapLastTouchTarget !== e.target) &&
      !isSelectOrOption(e.target.tagName) && !e.target.isContentEditable && !ionic.tap.isVideo(e.target)){
 ...
}
```

**Which Ionic Version?** 1.x or 2.x
1.3.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Thanks for the PR!
