### ISSUE TITLE
Transpile error with app-scripts v0.0.31 and up

### ISSUE THREAD

**Issue by morious** [driftyco/ionic#8745]
Hi,
I have been using the following package in my ionic project:
https://www.npmjs.com/package/tinycolor2
https://www.npmjs.com/package/@types/tinycolor

and I noticed transpiling errors when upgrading to RC1.
```
Cannot find module 'tinycolor2'.
...and...
Cannot find name 'tinycolorInstance'.
```

Moving one version back at a time I traced the issue to a change in v0.0.31.
I am not sure what is causing this issue though.

Any idea is welcome.
Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#184

**Comment by jgw96** [comment]
Hello, since this is an issue with Ionic-App-Scripts and not the framework I have moved this issue to that repo. Thansk!
