### ISSUE TITLE
Push notification service is down?

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic#8746]
Everything was working great until today, suddenly no push notifications received. 

My server shows that I get return code 201 (success) and this is one of the authorization ids I got:
"Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4YTQ5YWFkYS1lMDdjLTRhOWUtOWVjYi02ODA4ZWQ0ZjcwODMifQ.X0EXPOFYwswrx8NicqzLe87E2OiKzx213caBvGNecX8"

Please advise.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#214

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with an Ionic Cloud service and not the framework I have moved this issue to that repo.
