### ISSUE TITLE
Property ‘isAndroid’ does not exist on type ‘AccountsPage’  [Please help me...]

### ISSUE THREAD

**Issue by endrcn** [driftyco/ionic#8750]
Hi everybody,

Error1: `Property 'isAndroid' does not exist on type 'examplePage'`
Error2: `ngc failed: NGC encountered an error`

What I did, didn't fix the error.

![screen shot 2016-10-14 at 12 00 27](https://cloud.githubusercontent.com/assets/7888585/19428223/767ac828-9451-11e6-87bb-d6187cca2f56.png)

**Comment by daveshirman** [comment]
1. Is there actually a variable called that on your page?
2. Is it private or public?

**Comment by endrcn** [comment]
I've solved this problem. This problem related to build with ionic command. We should use "cordova" command instead of "ionic".

Thank you for your comment.
