### ISSUE TITLE
www directory not found problem (Ionic 2 RC1)

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8752]
Hello.
In my project www directory was in folder with name of project. But for my needs I replace it from this folder to another. 
When I try to execute "ionic serve" command. It says me that www directory not found.
I fix the /node_modules/@ionic/app-scripts/config/dist/util/config.js to:
```
var BUILD_DIR = 'build';
var SRC_DIR = '../view/app/src';
var TMP_DIR = '.tmp';
var WWW_DIR = '../view/app/www';
```
And it's work fine, but when ionic serve starts it says me 
`"www" directory not found.`
I create a empty www folder in folder of project. But I don't need it. How to fix it?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#186

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build related issue I have moved this issue to the app-scripts repo.
