### ISSUE TITLE
How disable templateUrl precompiller. (ionic 2 RC1)

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8753]
I need for my needs to disable templateUrl precompiler which is situated in:
`/node_modules/@ionic/app-scripts/dist/template.js`
I stopped it in 2 ways. But do you have any native solutions?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#187

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build related issue I have moved this issue to the app-scripts repo.
