### ISSUE TITLE
Ionic 2 RC icons color red&blue

### ISSUE THREAD

**Issue by endrcn** [driftyco/ionic#8754]
Hi,

My project is work but icon's color red and blue. Also navbar is color this like.

Please help me.

Thanks :) 
![15a9c45f60b6455e44b9cdaca9579944aa938dfd](https://cloud.githubusercontent.com/assets/7888585/19435595/317388c8-9474-11e6-8b53-f8d077de7be4.png)

![f5407fca69ddc4482c3cdd0ae73ff20547cb1187](https://cloud.githubusercontent.com/assets/7888585/19435598/3450535a-9474-11e6-88a7-83eae0322cec.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
