### ISSUE TITLE
How to filter copy files (Ionic 2 RC1)?

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8757]
Hello!
I got a rule in watch.config.js:
```
{
      paths: [
        '{{SRC}}/app',
        '{{SRC}}/pages',
        '{{SRC}}/assets',
      ],
      callback: copyUpdate
    },
```
I try to apply options, to cancel copy file with .ts extention:
```
{
      paths: [
        '{{SRC}}/app',
        '{{SRC}}/pages',
        '{{SRC}}/assets',
      ],
      options: { ignored: /([a-zA-z].ts$)/, filter:  /([a-zA-z].ts$)/},
      callback: copyUpdate
    },
```
How to filter files with .ts extention?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
