### ISSUE TITLE
Package is not a valid task

### ISSUE THREAD

**Issue by anderson631** [driftyco/ionic#8758]
Hello,
I'm trying to use the "ionic package", but is returned the error: "package is not a valid task".

The version of my ionic-cli is v1.6.4.

Error screen in Windows CMD: https://goo.gl/SDPyE7

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1552

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with the cli and not the framework I have moved this issue to that repo.
