### ISSUE TITLE
How to change dynamicaly slides in ion-slides on Ionic 2 RC1?

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#8759]
Hello.
I have slider in my application:

```
    <ion-slides #showSlider *ngIf="product.show_images" class="slideShowWrapper productImages" [options]="mySlideOptions">
          <ion-slide *ngFor="let image of product.show_images;">
            <img [src]="image.big_url" alt="{{image.title}}"/>
          </ion-slide>
        </ion-slides>
```

And in code I need to change slides and count of slides. But after change the list of slides. Slider changes, but first slide not shows, or it can be showed but points of slides is not anought.
How right to change slides list, to have response from slider?
My code to change is:

```
    this.slider.getSlider()['removeAllSlides'](); // Delete slides
    this.product.changeOffer(); //Here is where I get slides to show
    this.product.show_images = this.product.getImages(); //Change the list
```

**Comment by azakusilo** [comment]
The bug seems to be appears when option loop in true mode.

**Comment by stalniy** [comment]
@azakusilo you need to call `reLoop` method of swiper on `ionDidChange`. Or `destroyLoop()` and `createLoop()` if swiper version is older https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L2351

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
