### ISSUE TITLE
Unable to emulate iOS devices

### ISSUE THREAD

**Issue by Martin-Andersen** [driftyco/ionic#8760]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### Short description of the problem:
I am trying to emulate an iPhone 6S Plus. Its on the list of devices. I have done the same as [this article ](http://www.5neo.be/the-power-of-ionic-cli-live-test-your-ionic-app/) ionic emulate ios --target="iPhone-6-Plus, 10.0" but I am getting an "Unknown platforms: iPhone-6-Plus,, 10.0" I have also tried many other devices on the list.

Am I using a wrong syntax?

#### What behavior are you expecting?
The emulator is starting with iPhone 6S Plus

**Steps to reproduce:**
1. $ ionic start myapp blank --v2
2. $ ionic emulate ios --target="iPhone-6-Plus, 10.0"

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic V2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
