### ISSUE TITLE
Feat - VirtualScroll - Add support for offline data or scrolling large data sets

### ISSUE THREAD

**Issue by mtycholaz** [driftyco/ionic#8766]
Here's the scenario, data has already been download/cached from the server (200+ items). You feed that data to the virtual scroll component and it calculate it's size based on total records. Then as you scroll down, it just appends more offline data to the list, while removing elements above itself (performance).

WinJs 4 has a great example of this with their Listview control. You can throw hundreds of items against it, but it only renders 20 at a time, and still provides the scroll height of all items. Item height must be fixed for it to work.

**Comment by ghenry22** [comment]
This is what virtualscroll does now?

**Comment by mtycholaz** [comment]
@ghenry22 
I know what this looks like. It looks like I made a feature request without actually trying this out and going off of assumption....which is exactly what happened!
