### ISSUE TITLE
During Ionic serving when sources changed sourcemaps are not updated in RC1

### ISSUE THREAD

**Issue by agasbzj** [driftyco/ionic#8768]
Hello:
I find that in ionic serve or livereload mode, when you change some source code, the transpile starts perfectly but the related sourcemaps are not updated. This will make Chrome to stop at the false breakpoint.
I wonder if it is a ionic's problem or a ionic compile script's problem.

Thanks.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#191

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this was a build issue i have moved this issue to the app-scripts repo.
