### ISSUE TITLE
Back button tapped quickly removes root page on iOS

### ISSUE THREAD

**Issue by ggnzlpz** [driftyco/ionic#8770]
Short description of the problem:
When I tap back button very quickly on iOS it ends up with a blank page. It happens even with "ionic serve" and using iOS styles.

#### What behavior are you expecting?
Back action should never remove the root page.

**Steps to reproduce:**
1. Push some pages on iOS (ionic serve or real device)
2. Tap back very quickly until root page (keep tapping even in root page)
3. Blank screen appears

**Which Ionic Version?** 2.0.0-rc.1

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.6.0

**Comment by kyleap** [comment]
same problem +

**Comment by manucorporat** [comment]
I think this was already fixed in RC2. We expect to release it on Thursday

**Comment by ggnzlpz** [comment]
Great news! thanks!

**Comment by jgw96** [comment]
Going to link this to https://github.com/driftyco/ionic/issues/8769 as it is caused by the same issue. Thanks everyone!

**Comment by manucorporat** [comment]
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by imcosta** [comment]
Solved, no blank page.

**Comment by ggnzlpz** [comment]
Solved. Thanks!
