### ISSUE TITLE
IonicBootstrap is not getting imported from ionic-angular

### ISSUE THREAD

**Issue by Mukul19jain** [driftyco/ionic#8771]
I just started a new ionic 2 app using start command. Then I tried to import **"ionicBoostrap"** from **ionic-angular** and it gave me typescript error that "module ionic-angular has no exported member ionicBootstrap". The thing is that I need to implement ng2-translate in my project and I am following this ionic 2' documentation: 
https://ionicframework.com/docs/v2/resources/ng2-translate/

Can anyone help me out here that why I can't use ionicBootstrap the way they have used in official documentation in above link?

Thanks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#842

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually a docs issue so i have moved this issue to the site repo.
