### ISSUE TITLE
ItemReorder: onDragStart / onDragEnd events.

### ISSUE THREAD

**Issue by adubovsky** [driftyco/ionic#8773]
#### Short description of the problem:

Trying to find a way to disable swipe for `ion-menu` during active reordering. `ionDragStart` / `ionDragEnd` events would be very helpful.

**Which Ionic Version?** 2.x

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can use [this method](http://ionicframework.com/docs/v2/api/components/menu/MenuController/#swipeEnable) in `MenuController` to disable and enable menu swiping. Would that work for you use case?

**Comment by adubovsky** [comment]
thanks for the reply! yeah, I know how to disable menu swipe, but I need to disable it on dag start and enable back on drag end. so the problem is I can't find drag start event.

**Comment by jgw96** [comment]
Hello, sorry for the misunderstanding! So the correct way to do this would be to listen to the `reorder` variable and when that is `true` disable drag and when it is `false` enable drag. Thanks for using Ionic!

**Comment by adubovsky** [comment]
Hey @jgw96, sorry, but this is not what I was asking ( Will try to explain with more details.
So the original problem in the our app: it has list with `reorder="true"` attr, and also it has menu on the right side. When user starts dragging it can make the menu to show accidently. So I want to disable swipe for menu (through [this method](http://ionicframework.com/docs/v2/api/components/menu/MenuController/#swipeEnable) when drag starts. But I can't find a way to know **when the drag starts**. So I expect the template to be smth like this:
```
<ion-item-group reorder="true" (ionOnDragStart)="disableMenuSwipe()">
```
Thanks!

**Comment by adubovsky** [comment]
Hey, @jgw96,  did you have a chance to look at my last comment?
