### ISSUE TITLE
[Ionic 2] iOS Simulator hold on input and scroll throws typeerror. Gif attached.

### ISSUE THREAD

**Issue by fuggfuggfugg** [driftyco/ionic#8779]
#### Short description of the problem:

Noticing this in iOS Simulator. Not sure how to debug this.
#### What behavior are you expecting?

Issue 1: Tap on a textarea, the placeholder text shifts down for a brief second.
Issue 2: Focus on the textarea, hold and scroll gives weird behavior and the textarea seems to collapse. 

![scroll](https://cloud.githubusercontent.com/assets/5616123/19487555/5ef8460e-9531-11e6-882c-d0cc2612d306.gif)

**Which Ionic Version?** 1.x or 2.x
2.X

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Does this only happen on iOS? Also can you try [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions) and see if that fixes it?

**Comment by fuggfuggfugg** [comment]
@jgw96 

This is what I ran
```
ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save
ionic prepare
ionic run ios -l -s -c
```

Also added code logic to check and set it as a label [see gif]
```
if (window.indexedDB) {
      this.viewDesc = "I'm in WKWebView!";
    } else {
      this.viewDesc = "I'm in UIWebView";
    }
```

Issue still exists.

![scroll](https://cloud.githubusercontent.com/assets/5616123/19494925/49aab426-954f-11e6-8e52-07370e4163de.gif)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I cannot this issue any more with rc5. Because of this I am going to close this issue for now.
