### ISSUE TITLE
$ionicLoading without any text, just animated icon

### ISSUE THREAD

**Issue by hanthomas** [driftyco/ionic#878]
Is there a way to make $ionicLoading display with just an animated icon (e.g. - spinning wheel).  I can sorta make it work by adding a html content to show the icon.  But, it still displays the box around it.

**Comment by danielcosta27** [comment]
now you can use ion-spinner directive:

    $ionicLoading.show({
        template: '<ion-spinner icon="dots"></ion-spinner>',
        hideOnStageChange: true
    });

also, you can change the style of the spinner in your css:

    .spinner svg {
      width: 64px;
      height: 64px;
      stroke: #FFF;
      fill: #FFF;
    }

**Comment by arcadia168** [comment]
ion-spinners simply don't display in my app, checked out the DOM, and they aren't there as if they don't get rendering by angular or something, halp! My code is essentially as above: 

$ionicLoading.show({
    template: '<ion-spinner icon="dots"></ion-spinner>',
    hideOnStageChange: true
});

**Comment by miukki** [comment]
how can i customize icon spinner. ? 

`         template: '<i class="icon-dots"></i>',
`

doesnst work .. -- i have nt seen that template in .loading  ,,

**Comment by LauroRafael** [comment]
how can i **disable** swipe on ionicLoading is showing???
