### ISSUE TITLE
Tests for our generators

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#8783]
#### Short description of the problem:

Currently our tests for our generators do nothing https://github.com/driftyco/ionic/blob/master/scripts/templates/page/spec.ts.tmpl. This test would always pass even if the class name was wrong. We should add actual tests for the generators.

**Comment by luisalduucin** [comment]
@jgw96 I would like to contribute but I do not get what does this test actually need to test. Could you give me some orientation ? Thanks in advance.
