### ISSUE TITLE
docs: update sass files to document variables

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#8785]
This is a duplicate of https://github.com/driftyco/ionic-site/issues/613 but I want to have it in this repo to remember it needs to be added.

The following components have Sass files with variables:
- [x] Action Sheet
- [x] Alert
- [x] Badge
- [x] Button
- [x] Card
- [x] Checkbox
- [x] Chip
- [x] Content
- [x] Datetime
- [x] FAB
- [x] Input
- [x] Item
- [x] Label
- [x] List
- [x] Loading
- [x] Menu
- [x] Modal
- [x] Picker
- [x] Popover
- [x] Radio
- [x] Range
- [x] Refresher
- [x] Searchbar
- [x] Segment
- [x] Select
- [x] Spinner (depends on https://github.com/driftyco/ionic/issues/8683)
- [x] Tabs
- [x] Toast
- [x] Toggle
- [x] Toolbar

Try to keep the descriptions for the variables similar to the ones that have been added already (for example: https://github.com/driftyco/ionic/blob/master/src/components/tabs/tabs.ios.scss#L9)

This is related to issue https://github.com/driftyco/ionic/issues/5651. Help wanted! If anyone would like to contribute it is greatly appreciated. :) 

These will show up in the Sass Variables section of each API doc: http://ionicframework.com/docs/v2/api/components/tabs/Tabs/#sass-variables

<img width="700" alt="screen shot 2016-10-18 at 4 46 51 pm" src="https://cloud.githubusercontent.com/assets/6577830/19495704/830e9a72-9552-11e6-9def-1290e8aa36ac.png">

**Comment by Thomaspunt** [comment]
Sure, I'll help out. Taking care of action sheet, alert, card, checkbox and content for now.

**Comment by brandyscarney** [comment]
Thanks @Thomaspunt! Please ping me when you submit the PR so I can get it merged. :smile:

**Comment by tkrupers** [comment]
@brandyscarney I've opened the PR #8929 😄

**Comment by bul-ikana** [comment]
I have opened #8949 for the DateTime sass docs. Will be adding more soon.

**Comment by bul-ikana** [comment]
Also opened #8950 for the Input docs.

**Comment by John-Luke** [comment]
@brandyscarney I've opened a PR for the label component [#8952](https://github.com/driftyco/ionic/pull/8952)

**Comment by John-Luke** [comment]
I opened other PR ([#8953](https://github.com/driftyco/ionic/pull/8953)) for the list component

**Comment by bul-ikana** [comment]
Opened #8954 for the Item docs.

**Comment by bul-ikana** [comment]
Opened  #8955 for the Modal docs.

**Comment by brandyscarney** [comment]
@tkrupers @John-Luke @bul-ikana You're all awesome! Thanks for the PRs! :smile: :tada:
