### ISSUE TITLE
ionviewdidload is fired every time the page is pushed

### ISSUE THREAD

**Issue by comfortme** [driftyco/ionic#8787]
#### Short description of the problem:
i don't know if this is the expected behavior but in the docs it is said that
 `ionViewDidLoad : Runs when the page has loaded. This event only happens once per page being created. If a page leaves but is cached, then this event will not fire again on a subsequent viewing. The ionViewDidLoad event is good place to put your setup code for the page.`
but if i push a page for the first time the event is fired thats normal but if i pop back and push the page again the event is fired again.
is this normal?

#### What behavior are you expecting?
maybe my page is not cached for some reason so the event is fired like it's the first time.

**Steps to reproduce:**
1. setup a new project
2. create two pages
3. push one to another pop back and push again.

ionic 2 rc1

**Comment by manucorporat** [comment]
yes, it is normal. When you pop() a page is it removed, so next time you push it, it is a difference instance, so ionviewdidload is fired again.

**Comment by WillGeller** [comment]
What is the best way to handle code that should only run the first time the page is loaded? I am using the conference app style menu which uses nav.setRoot and this lifecycle hook is firing every time. It seems like ionViewDidLoad() does not act as expected with this behavior as I would think the norm is to push/pop/set root to navigate around the app
