### ISSUE TITLE
Exit codes for Ionic

### ISSUE THREAD

**Issue by cincuranet** [driftyco/ionic#8791]
I'm trying to script whole build-test-stage-publish process using Ionic 2, but it's really difficult because running i.e. `ionic build ios` always returns `0`. 

It should return some non-zero exit code when some error occurred.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1563

**Comment by jgw96** [comment]
Hello, since this is an issue with our cli and not the framework I have moved this issue to the appropriate repo. Thanks!
