### ISSUE TITLE
how can i build for browser?   --2.0.0-rc.1

### ISSUE THREAD

**Issue by Ahoo-Wang** [driftyco/ionic#8792]
how can i build for browser?   --2.0.0-rc.1

**Comment by rlucian** [comment]
`ionic build browser`
preceded by `ionic platform add browser`

however it's not clear for me also how that is useful.

**Comment by astec** [comment]
@rlucian cordova plugins can have different code for browser vs mobile app. One of examples could be Facebook API where in browser JS SDK would used and in app a wrapper to native API.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
