### ISSUE TITLE
navCtrl.pop() display a black screen when the page has Tabs 

### ISSUE THREAD

**Issue by tunxiaoqing** [driftyco/ionic#8793]
version:ionic2 rc1. running environment:chrome
I used navCtrl.pop() in [tab1Root] to return to the last page.But when the page has Tabs ,it back to a black screen view with the Tabs ,I removed the Tabs and make the last page jump directly to the [tab1Root]. In [tab1Root] page ,navCtrl.pop() worked well and return to the last page.
![xv 7l77 22xhjskv45roe](https://cloud.githubusercontent.com/assets/16894961/19508114/e7659626-9609-11e6-9428-ab98a1629bee.png)
![7ar38cw _q ktv40p uj](https://cloud.githubusercontent.com/assets/16894961/19508115/eac3081c-9609-11e6-8d8f-3a8f0c756643.png)
![aqz_yf_dsouwtyi0yv6n_3](https://cloud.githubusercontent.com/assets/16894961/19508121/f0284470-9609-11e6-860c-aff10403f3a9.jpg)
Look forward to your soonest reply.Thanks

**Comment by lazy-ape** [comment]
没看太明白你描述的场景，或者你可以把代码贴出来看一下

**Comment by tunxiaoqing** [comment]
(⊙o⊙)…~就是如果用tabs控件的话~里面每个tab页里的回退都会进到如图中黑色的页面~没有内容显示也没有回退到上一个页面~

**Comment by lazy-ape** [comment]
Ionic对返回有自己的处理，如果没有特别的需求，不需要自己再调用navCtrl.pop(), 不过我发现ionic在返回的处理里有一个bug，在当前Nav中只有一个页面的时候，Android在点击物理返回键的时候不能返回到TAB页面，不知道你是不是因为这个问题，你可以把页面跳转的代码和返回处理的代码贴出来看一下

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic. Sorry i dont know chinese! This has been fixed and will be part of the RC2 release.

**Comment by wangkeyi1992** [comment]
下一个版本就会修正，请持续关注官方动态。
