### ISSUE TITLE
Back Button always push a new view instead of going back with deep linker

### ISSUE THREAD

**Issue by jackfengji** [driftyco/ionic#8794]
#### Short description of the problem:
I'm using deep linker to change the urls now. It works fine but it always pushes to the navigation view instead of popping it when I press back button in browser or invoking history.back directly.

I see the code to handle this in https://github.com/driftyco/ionic/blob/master/src/navigation/deep-linker.ts in [loadViewFromSegment](https://github.com/driftyco/ionic/blob/master/src/navigation/deep-linker.ts#L468) function. But it's not working because the view controller's id is changed in [_insertViewAt](https://github.com/driftyco/ionic/blob/master/src/navigation/nav-controller-base.ts#L692) function in https://github.com/driftyco/ionic/blob/master/src/navigation/nav-controller-base.ts

**Steps to reproduce:**
1. Open the app with deeplink configs
2. Go to a page
3. Press back button in browser.

#### How to fix
I think the id of view controller should not be changed if it's already there.
 
**Which Ionic Version?** 2.x

**Comment by manucorporat** [comment]
@jackfengji fixed!

**Comment by jackfengji** [comment]
@manucorporat Do you have an idea when will the final version of Ionic 2 be out?
