### ISSUE TITLE
 dragging effect of datepicker is very slow on device.

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#8796]
#### Short description of the problem:

 while change the value of date,dragging effect of datepicker is very slow on android device.
#### What behavior are you expecting?

to fluent.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

used cordova-plugin-crosswalk-webview@2.0.0 with `config.xml`:

> ```
> <plugin name="cordova-plugin-crosswalk-webview" spec="~2.0.0"/>
> <preference name="xwalkVersion" value="19+" />
> <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect --enable-file-cookies"/>
> <preference name="xwalkMode" value="embedded" />
> <preference name="xwalkMultipleApk" value="true" />
> ```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v6.7.0
```

**Comment by manucorporat** [comment]
Probably fixed in RC3. Closing...
Please reopen if it still feels slow.
