### ISSUE TITLE
Update - App data not getting deleted!

### ISSUE THREAD

**Issue by lakshmankotipalli** [driftyco/ionic#8798]
Hello,

I am building an ionic hybrid app for Android and iOS, but facing a problem while updating the older version app with the new version.

When we try to update, the iOS update progress indicator is showing as app installing and after I open the updated app, I still see the older version with old data and old views, not getting updated with the new changes.  :frowning: Same happens with Android too.

But, once I clear data from settings > storage, I am able to see the new changes. I am using file-rev tasks in gulp and files getting revised, still the issue is there.

Help is appreciated :slightly_smiling_face:

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by lakshmankotipalli** [comment]
Yup. Thanks! I did that too :)
