### ISSUE TITLE
ionic 2 watch typescript not working

### ISSUE THREAD

**Issue by balicekt** [driftyco/ionic#8799]
I wanted to try new ionic 2. I made this steps:

```
ionic start HelloWorld --v2
cd HelloWorld
ionic serve
```

until now is everything OK. BUT when I go to folder src/pages/home and adjust file home.ts nothing is hapening watcher is not working but when I adjust file home.html watcher is working well console show changes and browser automatically refresh page.

Does anyone know why in ionic 2 watcher does not working with typescript files? Or is there something I did wrong? Also in Ionic project is no gulpfile.js anymore.

I will be glad for any help.

Thank you

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#199

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build related issue I have move this issue to the app-scripts repo.
