### ISSUE TITLE
Ng-class not working in ion-nav-bar

### ISSUE THREAD

**Issue by zgluis** [driftyco/ionic#8803]
Hello, I'm trying to change the style of ion-nav-bar according to the type of user after a login using ng-class, the problem is that it works but just in my "ion-header-bar", I've been trying many things but nothing give me a real solution.

[Codepen](https://codepen.io/Zgluis/pen/yavJRP)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
