### ISSUE TITLE
ionViewDidLoad does not have scope for global variable

### ISSUE THREAD

**Issue by Purus** [driftyco/ionic#8805]
#### Short description of the problem:

The object that I declared is not available inside ionViewDidLoad event cycle method.

```
ionViewDidLoad() {
    if(Appodeal) Appodeal.show(Appodeal.INTERSTITIAL);
}
```

I am getting the below issue.

`Appodeal is not defined`

The following declaration is done.

`declare var Appodeal;`

But the same code works fine inside other functions present in the same page component.

#### What behavior are you expecting?
The object declared should be available inside the cycle method.

**Comment by Purus** [comment]
Related to https://github.com/driftyco/ionic/issues/8449?

**Comment by jgw96** [comment]
@Purus this does sound related to that issue. Can you put the above logic in your example in `ionViewDidEnter` and see if it works there? Thanks!
