### ISSUE TITLE
bug: [RC1] The pipe '...' could not be found (RC1)

### ISSUE THREAD

**Issue by giammaleoni** [driftyco/ionic#8808]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Unable to use Custom defined Pipes

1. I defined a simple Filter pipe (filter by property checked = true )
2. I imported it under app.module.ts and added under declaration
5. imported in the module where I need it
6. used to filter a list in the relative HTML template ( <ion-item *ngFor="let item of (items | Filter)"> )

The browser log return me a parsing error cause it can't  find the pipe:

Template parse errors:
The pipe 'Filter' could not be found

The pipe is similar to the one in the Angular Docs: https://angular.io/docs/ts/latest/guide/pipes.html#!#impure-flying-heroes</span>

<span is-issue-template></span>

**Comment by mbakker96** [comment]
I've the same problem.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately, i cannot reproduce this issue, would you be able to provide a repo that I can use to reproduce this?

**Comment by giammaleoni** [comment]
During the creation an example repo with the issue to post here I understand how to resolve my problem:
I was trying to use the filter with the "class name" instead of "pipe name":

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'filter',
  pure: false
})
export class Filter implements PipeTransform {

  transform(values: any[]) {
    return values.filter(item => item.checked);
  }

}
```

**I was using "Filter" instead of "filter"...**

Anyway thx for the answer!

**Comment by mbakker96** [comment]
I've the same problem. I've made a repo on my github page for the error:

[https://github.com/mbakker96/pipebug](https://github.com/mbakker96/pipebug)

**Comment by giammaleoni** [comment]
I'm not sure but the reason could be that your put the pipe in the imports array instead of the declaration one.
You can try making a change to your app.module.ts:
```
import {NgModule} from '@angular/core';
import {IonicApp, IonicModule} from 'ionic-angular';
import {MyApp} from './app.component';
import {HomePage} from '../pages/home/home';
import {PipesModule} from '../pipes';

@NgModule({
    declarations:    [
        MyApp,
        HomePage,
        PipesModule //move the pipe here
    ],
    imports:         [
        IonicModule.forRoot(MyApp)
    ],
    bootstrap:       [IonicApp],
    entryComponents: [
        MyApp,
        HomePage
    ],
    providers:       []
})
export class AppModule {
}
```

**Comment by giammaleoni** [comment]
During the creation an example repo with the issue to post here I
understand how to resolve my problem:
I was trying to use the filter with the "class name" instead of "pipe name":

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'filter',
  pure: false
})
export class Filter implements PipeTransform {

  transform(values: any[]) {
    return values.filter(item => item.checked);
  }

}
```

**I was using "Filter" instead of "filter"...**

Anyway thx for the answer!
Gianmaria

Il giorno gio 20 ott 2016 alle ore 17:35 Justin Willis <
notifications@github.com> ha scritto:

**Comment by giammaleoni** [comment]
@mbakker96 did you have the chance to check suggestion?

**Comment by mbakker96** [comment]
@giammaleoni I fixed it with adding the pipes into the export

**Comment by aebmknrl** [comment]
@giammaleoni sorry, i know that this is old but... why the pipe must to be exported on the shared module? I can find a clear explanation. Your answer help me to fix a problem. Thanks

**Comment by AnalyzePlatypus** [comment]
@mbakker96 worked for me.

@aebmknrl:
 Suppose you have a module `AppModule`, a component `MyComponent`, and a pipe `MyPipe`.
`MyComponent` is declared by `AppModule`.

You now want to import the pipe into `AppModule`, so it will be available to `MyComponent`
(You could also create a new module `PipesModule`, but for a single pipe that should be unnecessary)

Now `import` the pipe into `AppModule`, and add it in 2 places:

1. Add it to the `declarations` array
2. Also add it to the `exports` array

It should now be available.
Annoyingly, the docs don't bother to mention that the pipe must be exported as well.
Hope this helps!
