### ISSUE TITLE
Error running npm install -g ionic

### ISSUE THREAD

**Issue by andrewlaskey** [driftyco/ionic#8813]
I am unable to install ionic. Running `npm install -g ionic` generates this error:

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@latest"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@ionic/app-generators"
```

Also I'm on macOS Seirra 10.12.

I didn't have the latest version of node or npm so I updated both of those, but it didn't resolve the issue. Any ideas? Something I'm missing?

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Unfortunately I cannot reproduce this issue. Can you be sure that you are on a solid network connection? Also, since this issue is a cli related issue and not the framework I am going to move this issue to the cli repo.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1568
