### ISSUE TITLE
Documentation incomplete for Google maps.

### ISSUE THREAD

**Issue by aishacharya** [driftyco/ionic#8815]
As google maps form an integral part of my application , there is not enough documentation provided in the docs for the same.(ionic-native=>Googlemaps)
A repo link as well as some detailed examples if provided would be great.
link :http://ionicframework.com/docs/v2/native/googlemap/

**Comment by ZiFFeL1992** [comment]
I think you should post this here: https://github.com/driftyco/ionic-native/issues

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#735

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an Ionic Native issue and not a framework issue i have moved this issue to the Ionic Native repo.
