### ISSUE TITLE
InAppBrowser - possible to Customize? insertCss not working

### ISSUE THREAD

**Issue by vaibsVB** [driftyco/ionic#8816]
Greetings to all,

I have a requirement in which I want to customize `InAppBrowser's` `location bar` in `Android`.
I want to replace/add few buttons and its positions too. I want to hide only the URL portion and keep the buttons, etc.

Is it possible to customize or modify in `InAppBrowser`?
I'm using `cordova-plugin-inappbrowser plugin`.

I tried `executeScript` and `insertCss` methods.
but the problem is `insertCss` not working.

`cordova-plugin-inappbrowser` plugin has `insertCSS` method in it. And in the (typescript definition file) `inappbrowser.d.ts` under the `node_modules` has `insertCss` method. Is there any typos in the `inappbrowser.d.ts` file.

Any help Will be appreciated.
Thanks in advance.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#736

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an Ionic Native issue I have moved this issue to the Ionic Native repo.
