### ISSUE TITLE
feat: add possibility to disable/override hardware back button in alert/modal options

### ISSUE THREAD

**Issue by swengorschewski** [driftyco/ionic#8821]
#### Short description of the problem:
I think it would be useful to disable and/or override the android hardware back button functionality during the creation of a modal/alert view. At the moment it is possible to set enableBackdropDismiss to false to prevent a user from dismissing aa alert view. This forces the user to click on one of the displayed buttons which will call a handler. On android you can still close the alert/modal if you click on the hardware back button circumventing the use of the given handlers.

Adding additional params to the modal/alert options could be helpful:

```javascript
alertCtrl.create({
      title: 'title',
      message: `message`,
      enableBackdropDismiss: false,
      disableHardwareBackButton: true,                    // new option
      hardwareBackButtonHandler: () => {/* do stuff */},  // new option
      buttons: [{ text: 'Ok', () => {/* do stuff */} }]
}).present();
```

**Which Ionic Version?**: 2.x

**Which Platform**: Android

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! You can use our `ionViewCanLeave` lifecycle event to stop a user from closing a modal. Here are our docs on [our lifecycle events](http://ionicframework.com/docs/v2/api/navigation/NavController/#lifecycle-events). At this time a user cannot be stopped from closing an alert as that would be considered bad UX. I would recommend using a modal for this use case.
