### ISSUE TITLE
Build fails Returned: code: 137  signal: null

### ISSUE THREAD

**Issue by weolopez** [driftyco/ionic#8824]
salarmy@salarmydal:~/sacpcp$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle savi@~prebuild: savi@
6 silly lifecycle savi@~prebuild: no script for prebuild, continuing
7 info lifecycle savi@~build: savi@
8 verbose lifecycle savi@~build: unsafe-perm in lifecycle true
9 verbose lifecycle savi@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/salarmy/sacpcp/node_modules/.bin:/usr/local/bin:/home/salarmy/bin:/home/salarmy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle savi@~build: CWD: /home/salarmy/sacpcp
11 silly lifecycle savi@~build: Args: [ '-c', 'ionic-app-scripts build --dev' ]
12 silly lifecycle savi@~build: Returned: code: 137  signal: null
13 info lifecycle savi@~build: Failed to exec build script
14 verbose stack Error: savi@ build: `ionic-app-scripts build --dev`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid savi@
16 verbose cwd /home/salarmy/sacpcp
17 error Linux 4.4.0-31-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error savi@ build: `ionic-app-scripts build --dev`
22 error Exit status 137
23 error Failed at the savi@ build script 'ionic-app-scripts build --dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the savi package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build --dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs savi
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls savi
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#205

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this issue is an issue with `ionic-app-scripts` I have moved this issue to that repo.
