### ISSUE TITLE
Internet Explorer 11 click-block div prevents clicking

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#8828]
_From @alfabetagama on October 20, 2016 13:36_

#### Short description of the problem:
When building for release Internet Explorer displays click-block div element in front of application content. This element prevents any interaction with application. This DOES NOT happen in development mode.

#### What behavior are you expecting?
I expect buttons to be clickable and inputs to be able to accept input.

**Steps to reproduce:**
1. Create app with menu and page
2. Place button on a page
3. Build with --release switch
4. Run in IE 11
5. try to click the buitton

**Which @ionic/app-scripts version are you using?**
ionic-app-scripts 0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Fix: 
```
//IE
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .click-block {
        display:none;
    }
}
```

_Copied from original issue: driftyco/ionic-app-scripts#203_

**Comment by jgw96** [comment]
_From @patrickmcd on October 20, 2016 14:49_

IE isn't supported.

**Comment by jgw96** [comment]
_From @alfabetagama on October 20, 2016 15:24_

@patrickmcd I didn't find any official documentation regarding the IE non-support, however apart from some minor styling bugs it works just fine. And of course the click-block div.

**Comment by jgw96** [comment]
_From @patrickmcd on October 20, 2016 15:34_

It might not be in the official docs, but there are some comments scattered throughout the issues about it.

https://github.com/driftyco/ionic/issues/8669#issuecomment-253623266
https://github.com/driftyco/ionic/issues/6386#issuecomment-220648407

etc...

**Comment by jgw96** [comment]
_From @danbucholtz on October 20, 2016 16:52_

@jgw96 can you move this.

Thanks,
Dan

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time we do not support IE11 with Ionic 2, although we do fully support Edge. Because of this I am going to be closing this issue for now.

**Comment by webprofusion-chrisc** [comment]
Not cool guys, this was working recently! I know you guys don't support IE11, but our clients do.
