### ISSUE TITLE
Ionic2 Popover bug? and...

### ISSUE THREAD

**Issue by kongdewen1994** [driftyco/ionic#8831]
## Why in the Popover window to perform Pushing a View, the View of the content in the label content can't roll, even if the content is beyond the range
![](http://7xp2ia.com1.z0.glb.clouddn.com/1.png)![](http://7xp2ia.com1.z0.glb.clouddn.com/2.png)

## AND in ionic2-rc-0  You will see the deformation of the style of the button.

![](http://7xp2ia.com1.z0.glb.clouddn.com/3.png)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! The first issue you described has already been fixed and will be in the RC.2 release (:. Regarding your second issue about buttons, you need to add the `ion-button` attribute to your buttons. Here is an example of that: `<button ion-button>Hello World</button`

**Comment by kongdewen1994** [comment]
Thank you, I will focus on
