### ISSUE TITLE
Ionic Serve -- Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by FourLeafClover** [driftyco/ionic#8834]
Using ionic serve can not call the auto2.0 restful api.
but i can visit the api when using fillder

![image](https://cloud.githubusercontent.com/assets/8449788/19587306/fb229b46-978f-11e6-814a-1d40c4f67e61.png)

**Comment by vswarte** [comment]
You need to place an 'Access-Control-Allow-Origin' field in the header of your HTTP response. Webbrowsers have a mechanism to protect against inappropriate API calls in case of XSS. 

Not sure what backend framework you're using, but you should check out the appropriate 'cors' middleware. As it will inject the required headers into the response.

**Comment by nakulgulati** [comment]
@FourLeafClover instead of making changes on your backend I would recommend the solution detailed in this blog http://blog.ionic.io/handling-cors-issues-in-ionic/.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
