### ISSUE TITLE
nav.setRoot to a page without tabs still display tabs

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#8840]
Hey,

I've created following test application:

Tabs
-- Contact, Home, etc.
Testpage (subpage accessed thru menu)
Test2page (another root page)

Behavior excepted:

From the tabs menu, I open sub page "Testpage" and click to set the new root "Test2page" without seeing anymore the tabs at the bottom of my page, since that new root page isn't a tabs page.

Behavior tested:

From the tabs menu, I open sub page "Testpage" and click to set the new root "Test2page" but when that page is successfully loaded I still see the tabs bar at the bottom of my page.

Here a project to reproduce the behavior (just implemented two pages in the start app):

https://github.com/peterpeterparker/ionic2RC1-test

Thx in advance for the fix or to let me knows how I could solve that issue. 

Best regards

P.S.: Issue maybe link with another tabs issue https://github.com/driftyco/ionic/issues/8682

**Comment by manucorporat** [comment]
You are changing the root of the tab, remember that each tab has his own navigation stack. You have to setRoot() to the root navigation controller:
```
constructor(public app: App) {}

(...)
    this.app.getRootNav().setRoot(Test2Page);
```

**Comment by peterpeterparker** [comment]
Get it, sweet. Thx a lot @manucorporat

**Comment by iriekun** [comment]
Hi! It didn't work out for me! it showed this error Error: Uncaught (in promise): false 
I'm in ionic 2.0.0

**Comment by projetpos** [comment]
i use :
aboutPage is a page of TabsPage : <button ion-button (click)="openPage()">Menu App</button>
inside about.ts : 
 openPage() {
    this._nav.goToRoot(OtherPage);
  }
you're now out the tabs

**Comment by nadeemmdsol** [comment]
thanks a lot @manucorporat

**Comment by tenaciousprevailer** [comment]
thanks brother... it worked

**Comment by obbe79** [comment]
How is it done now that getRootNav() is deprecated? 
I would like to navigate from one page with tabs to a new page with different tabs. It works with getRootNav() but I can't figure out another way to do it with out using getRootNav(). Any help?

**Comment by hardikrawal23** [comment]
@obbe79 Did you find any solution for the same ?

**Comment by peterpeterparker** [comment]
@obbe79 @hardikrawal23 I guess you would still have to use getRootNav() for now on, I least I do

There is an open issue https://github.com/ionic-team/ionic-site/issues/1197 about clearing up what's the id to use, but it is open since a long time without answer

**Comment by gbrits** [comment]
The following worked for me:
```
// Import
import { App, NavController } from 'ionic-angular';
// Init
constructor(private app: App)
// Call
this.app.getRootNavs()[0].setRoot(SignInPage);
```
