### ISSUE TITLE
bug: ionViewWillEnter not fired after pop

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic#8842]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

after pushing a page and pop with back button ionViewWillEnter() is not fired. Or is there another trigger? 
I would like to update some data on root page.

Thx
Appwrx</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Please, can you follow the issue template? otherwise I don't even know what version are you using
Also, can you provide some code that reproduces the issue?

**Comment by appwrx** [comment]
I used the bugreporter and thought it will be ok, sorry.

**Comment by appwrx** [comment]
#### Short description of the problem:
After pushing a page and return by clicking back button the ionViewWillEnter function is not fired.

#### What behavior are you expecting?
Call ionViewWillEnter or introduce a other way to update data

**Steps to reproduce:**
1. Push a page
2. Return to first page

**Which Ionic Version?**
2.0 RC0


#### Plunker
http://plnkr.co/edit/6rebCvyOqGggys6fUDEp?p=preview

#### Info
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by appwrx** [comment]
same like before :(

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1-201610241941
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
@appwrx I was able to reproduce your bug. It will be fixed once this PR is merged!
https://github.com/driftyco/ionic/pull/9033

**Comment by appwrx** [comment]
Perfect :) thank you!

**Comment by farhaan008** [comment]
I also have exactly the same issue. I couldn't find solution. ionViewWillEnter() not call when page is poped.

I am also facing one more issue LocalStorage. storing data in local storage and at next line fetching data no get updated data.
1. service.ts
import { Storage } from '@ionic/storage';
import { Injectable } from "@angular/core";
import { Http, Headers, RequestOptions } from '@angular/http';
import 'rxjs/add/operator/map';

@Injectable()
export class Data{    
    constructor(public storage: Storage, public http: Http){    }
    getLocal(){   return this.storage.get('local');    }
    setLocal(data){    let formatToJson = JSON.stringify(data);   this.storage.set('local', formatToJson);    }     
}
2. anypage.ts
this.dataService.setLocal(data); /* I set the data here*/
/*At next line fetching data that i set, But not getting set data.
this.dataService.getLocal().then((data) => { 
           if(data){   this.localData = JSON.parse(data);   }            
});

**Comment by norpoint** [comment]
Same issue. Hoping for a quick fix.
