### ISSUE TITLE
RC1 Dynamic change color of buttons does not remove older color class

### ISSUE THREAD

**Issue by fmaceachen** [driftyco/ionic#8845]
#### Short description of the problem:

I have a button that changes color :
`<button ion-button 
          outline="{{!button.selected && button.value !== value}}"
          color="{{(button.selected || button.value === value) ? button.value : 'dark'}}"
          (click)="setValue(button.value)">
    {{button.text}}
  </button>`

when button.value changes the button does change color, but if I change it again the first css class is not removed and it takes more importance as the OUTLINE one.
#### What behavior are you expecting?

When the color changes all css classes about color should be removed and then add then new one

**Steps to reproduce:**
1. Create a page with 3 buttons, with dynamic color (color="value") and outline, Value must be in color scss variables
2. Change value clicking on buttons
3. Look that buttons that are not selected keep the first color

```
<button ion-button 
          outline="{{!button.selected && button.value !== value}}"
          color="{{(button.selected || button.value === value) ? button.value : 'dark'}}"
          (click)="setValue(button.value)">
    {{button.text}}
  </button>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://forum.ionicframework.com/t/changing-button-color-or-icon-dynamically/37675/43

**Which Ionic Version?** 1.x or 2.x
2.0-RC1
#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.7 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.0.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by manucorporat** [comment]
Use angular 2 input syntax:
```
<button ion-button 
          [outline]="!button.selected && button.value !== value"
          [color]="(button.selected || button.value === value) ? button.value : 'dark'"
          (click)="setValue(button.value)">
    {{button.text}}
  </button>
```

**Comment by fmaceachen** [comment]
Thanks for the quick response, the notation is better that way but the result is the same.
I detected that the problem is the combination of dynamic outline and color. Because they both have their own css colo classes.
For example:

button-ios-regular (regular is a color)
button-outline-ios-dark

So the button keeps both classes.

**Comment by brandyscarney** [comment]
Hey @fmaceachen, could you provide me with what you are changing the values to? We have a test here that I am not able to reproduce it with: https://github.com/driftyco/ionic/blob/master/src/components/button/test/dynamic/main.html

If you could provide the code for your `setValue` function that would be helpful. Thanks!

**Comment by fmaceachen** [comment]
I have 3 buttons with 3 colors:
```
$colors: (
        primary:    #1e5799,
        secondary:  #467302,
        danger:     #FF1210,
        light:      #f4f4f4,
        dark:       #222,
        favorite:   #69BB7B,
        warning:    #FF9938,

        bueno:      #69BB7B,
        regular:    #FF9938,
        malo:       #f53d3d,
        undefined:  #f4f4f4
);
```

the value changes to a string 'bueno' 'regular' 'malo'

**Comment by fmaceachen** [comment]
@brandyscarney  Check on this, on the Home page, [https://github.com/fmaceachen/buttons-color-test](url)

There you can reproduce the same that is happening to me.

Regards

**Comment by brandyscarney** [comment]
Thanks for the repo! I was able to reproduce it. So the issue here is definitely that the solid `color` class isn't being removed when it goes back to `outline` and `dark`. As a workaround for your specific issue, you can move your variables before the `dark` one:

```
$colors: (

  primary:    #327eff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,

  bueno:      #69BB7B,
  regular:    #FF9938,
  malo:       #f53d3d

  dark:       #222,

)
```

That way the dark outline class will take priority over the solid color one.

**Comment by fmaceachen-glb** [comment]
@brandyscarney Thanks for the workaround, haven't figured out that color order affects the final css.

**Comment by brandyscarney** [comment]
Thanks to PR https://github.com/driftyco/ionic/pull/9114 this has been fixed. I released a nightly version of the framework (`ionic-angular@2.0.0-rc.2-201611110146`) with this fix, could you try it out and let me know if you find any issues?

```
npm install --save ionic-angular@nightly
```

Thanks!
