### ISSUE TITLE
error: when ionic build android

### ISSUE THREAD

**Issue by tianleios** [driftyco/ionic#8849]
ionic2 beat i can ionic build android. but ionic2-rc i got this error.
Error: /Users/tianlei/Desktop/new/src/main/cityNet/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/tianlei/android-sdk-macosx/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1585

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a cli related issue I have moved this issue to the cli repo.
