### ISSUE TITLE
Currency pipe not working on Android

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic#8852]
#### Short description of the problem:

When I use the currency pipe like:
`{{ 71.98 | currency:'EUR':true:'.2-2' }}`

It works with `ionic run browser` but fails for `ionic run android`

#### What behavior are you expecting?

Working currency pipe

**Steps to reproduce:**
1. start empty tabs app
2. add `{{ 71.98 | currency:'EUR':true:'.2-2' }}` to home.html
3. run `ionic run android`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

![image](https://cloud.githubusercontent.com/assets/644550/19617913/b7fbad18-983d-11e6-9c81-25a9477352af.png)
 

**Which Ionic Version?** 2.0

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by ramonornela** [comment]
Add polyfill [intl](https://github.com/andyearnshaw/Intl.js)

1 -  install intl:
```npm install intl --save```

2 - Create file copy.config.js:
```

// https://www.npmjs.com/package/fs-extra

module.exports = {
  include: [
    {
      src: '{{SRC}}/assets/',
      dest: '{{WWW}}/assets/'
    },
    {
      src: '{{SRC}}/index.html',
      dest: '{{WWW}}/index.html'
    },
    {
      src: '{{SRC}}/manifest.json',
      dest: '{{WWW}}/manifest.json'
    },
    {
      src: '{{SRC}}/service-worker.js',
      dest: '{{WWW}}/service-worker.js'
    },
    {
      src: 'node_modules/ionic-angular/polyfills/polyfills.js',
      dest: '{{BUILD}}/polyfills.js'
    },
    {
      src: 'node_modules/ionicons/dist/fonts/',
      dest: '{{WWW}}/assets/fonts/'
    },
    {
      src: '{{ROOT}}/node_modules/intl/dist/Intl.min.js',
      dest: '{{BUILD}}/intl/Intl.min.js'
    },
    {
      src: '{{ROOT}}/node_modules/intl/locale-data/jsonp/pt-BR.js',
      dest: '{{BUILD}}/intl/en-US.js'
    }
  ]
};
```

3 - Alter ionic_copy app-scripts:

```
"config": {
    ...
    "ionic_copy": "./copy.config.js"
    ...
  }
```

4 - Alter src/index.html
```
  ...
  <script src="build/intl/Intl.min.js"></script>
  <script src="build/intl/en-US.js"></script>
   ...
```

Thanks

**Comment by basvdijk** [comment]
@ramonornela Thanks for the workaround! I assume this won't be needed once it is fixed by the Ionic team?

**Comment by ramonornela** [comment]
I think best add this feature in ionic2-app-base and change in copy.config.js in ionic_app_scripts

Thanks

**Comment by manucorporat** [comment]
Well, I don't think this should be something that should be fixed by ionic, but the developer.

Currency pipe uses a web API that is not available across all developers, so it should be fixed by you adding a polyfill or by the developer of that pipe (angular 2)
https://angular.io/docs/ts/latest/guide/pipes.html

>The Date and Currency pipes need the ECMAScript Internationalization API. Safari and other older browsers don't support it. We can add support with a polyfill.
COPY CODE
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
