### ISSUE TITLE
show-page show-tabbar is not added when setting route.

### ISSUE THREAD

**Issue by alexandrzavalii** [driftyco/ionic#8866]
In app.component file I set the root to tabsPage
```
    firebase.auth().onAuthStateChanged((user) => {
      if(user) {
        this.rootPage = TabsPage;
      }
      else {
        this.rootPage = LoginPage;
      }
    });
```
And tabs page I specify the root and the default selected tab
```
    tab1Root: any = SocialPage;
    tab2Root: any = NewsPage;
    selectedTab: any;
    constructor(private nav: NavController) {
        this.selectedTab = 0;
        console.log("tabs initialized");
    }
```
For some reason my html doesn't have show-page and show-tabbar class, and the page is empty, However I can still click on hidden tabbar and after that the page is visible and I can navigate through the tabs.

**Comment by manucorporat** [comment]
Hi!, can you run `ionic info` and copy paste the results here?
Can you provide a repo that reproduces the issue?

**Comment by alexandrzavalii** [comment]
Hello!
```
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1-201610182222
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 8.0 Build version 8A218a 
```
https://github.com/alexandrzavalii/new-app

**Comment by jgw96** [comment]
Hello, thanks for using ionic! This is a known issue with the latest nightly and has already been fixed in master. To fix this issue i would recommend installing the latest stable rc release by running `npm install ionic-angular@2.0.0-rc.1 --save`.

**Comment by alexandrzavalii** [comment]
@jgw96 
Thanks a lot!
I spent so much time on this :(
