### ISSUE TITLE
Error: ENOENT: no such file or directory, open '../Documents/project/myApp/www/index.html'

### ISSUE THREAD

**Issue by souzacristsf** [driftyco/ionic#8868]
I'm trying to create a few weeks IONIC 2 project and so far without success. Hard to create an expectation with ionic 2.

My error is the following:

```
Error: ENOENT: no such file or directory, open '../Documents/project/myApp/www/index.html'
```

use operacinal system `Arch Linux`.

cat / etc / issue
```
Arch Linux \ r (\ l)
```

uname
```
Linux localhost.localdomain 4.7.2-1-ARCH # 1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU / Linux
```

ionic info
```
----------------------------------------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS: / bin / sh: lsb_release: command not found
Node Version: v6.9.1
----------------------------------------------------------------
```
npm -v
```
3.10.9
```

I would like to help, because they do not know what I can faver to solve this problem.

Regards,

Michel Ferreira Souza

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1586

**Comment by jgw96** [comment]
Hello, thanks for using Ionic and sorry you are running into issues! Since this is a cli issue and not a framework issue I have moved this issue to the Ionic cli. Thanks!

**Comment by aslankaan** [comment]
a
