### ISSUE TITLE
 Error creating project in ionic 2.  Error with start undefined

### ISSUE THREAD

**Issue by souzacristsf** [driftyco/ionic#8869]
More open issue.
Now this time tried a virtual machine to not lose hope to work with IONIC 2, but unfortunately without success again.

I am now with this error:
`` `
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

`` `
My virtual machine
uname
`` `
Souzacrists Linux 4.4.0-31-generic # 50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU / Linux
`` `

My operating system:
lsb_release -a
`` `
In LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release: 16:04
Codename: xenial
`` `

I already have this open issue.
https://github.com/driftyco/ionic/issues/8868

I hope to answer that can help me solve. For not wait to start working with IONIC 2.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1587
