### ISSUE TITLE
Pressing enter key on ion-input within an ion-slide causes slide to move to the next

### ISSUE THREAD

**Issue by yuyinitos** [driftyco/ionic#8870]
When the `enter` key is pressed when entering data into an input field the slides moves to the next one. Even with setting `allowSwipeToNext=false` or `lockSwipes()`.

```
<ion-slide>

  	<h2>What's your name</h2>

		<ion-item [class.error]="!fullnameControl.valid && fullnameControl.touched">
			<ion-label stacked>
				My name:
				<span *ngIf="fullnameControl.hasError('required') && fullnameControl.touched">(required)</span>
				<span *ngIf="fullnameControl.hasError('minlength') && fullnameControl.touched">(minimum length is 3!)</span>
				<span *ngIf="fullnameControl.hasError('maxlength') && fullnameControl.touched">(maximum length is 50!)</span>
			</ion-label>
			<ion-input formControlName="fullnameControl"></ion-input>
		</ion-item>
</ion-slide>

<ion-slide>
...
```

**Comment by yuyinitos** [comment]
This was due to the fact that pressing enter triggered the slideNext button. Even though the button was disabled because of invalid field values.
Setting `type="button"` solved the issue.
Related to: Hitting 'Enter' after typing in search bar (ion-searchbar) will trigger 'ionCancel' #7010

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this issue has been fixed I am going to close this issue for now.
