### ISSUE TITLE
bug: overflow-y: scroll; CSS property crashes app.

### ISSUE THREAD

**Issue by nottinhill** [driftyco/ionic#8871]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>overflow-y: scroll; 

CSS property crashes app.

I debugged 10 hours to find the issue.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
