### ISSUE TITLE
Building against ionic locally in RC1

### ISSUE THREAD

**Issue by lujakob** [driftyco/ionic#8874]
Is "Building against ionic locally" as describe in 
https://github.com/lujakob/ionic/blob/master/scripts/README.md
still working ?

If I run gulp package build in the main directory of master branch I get 

Using gulpfile ~/Applications/ionic-fork/ionic/gulpfile.js
[14:45:50] Task 'package' is not in your gulpfile

Seems like those docs are outdated ?
How can I build against ionic locally (I want to fiddle in the core files for testing purposes?

**Comment by jgw96** [comment]
@brandyscarney when you get a chance could you take a look at this?

**Comment by brandyscarney** [comment]
I've updated the framework script and steps to use Ionic locally here: https://github.com/driftyco/ionic/tree/master/scripts#developing-against-ionic-locally

Please pull the master branch of the framework and let me know if you find any issues! Thanks!
