### ISSUE TITLE
CSS Issue with android 4.3, galaxy s3

### ISSUE THREAD

**Issue by abunour22** [driftyco/ionic#8877]
I have issue with galaxy s3 android 4.3 with css 

and also i can not debug my app with inspect with chrome developer tools

Its showing device but not the app !! 

so what is missing ?!

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
