### ISSUE TITLE
Ionic livereload is not working @ ionic@1.7.15 and iOS10

### ISSUE THREAD

**Issue by premcarver** [driftyco/ionic#8879]
I am working on a project which is using below configuration for development. When I tried to setup the working environment on MacBookPro with Xcode 10 and iphone 5 running at ios 10. Live reload was initially not working at all. However I have managed to get the console logs but still the changes in html and js files are getting reflected only after the restart(kill and then reopen) the running on device. Could you please help me?

Your system information:

Cordova CLI: 6.3.1
Gulp version: CLI version 3.9.1
Gulp local:

Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has actually already been fixed and will be in the next version of the Ionic cli. I will post here when that is released.

**Comment by premcarver** [comment]
How is it possible to apply the fixes from ionic2 to ionic 1?
Let me clear the whole scenario, I am working on a project which is using the ionic1 and you guys fix all issues for ionic2. Do you really think its easy to migrate an app from ionic1 to ionic 2? If so please do let me know the steps to migrate. And if not then please continue improving the ionic 1 as well.

**Comment by markthien** [comment]
@premcarver ionic is free and opensource, FYI

**Comment by premcarver** [comment]
@markthien  Ionic is free. But it doesn't mean that all improvements foes to Ionic2. 

Stop redirecting the issue into a different way, please.

**Comment by markthien** [comment]
@premcarver try react if not happy with ionic
