### ISSUE TITLE
[Feature Request] Add $toolbar-ios-title-font-family to Ionic Sass Variables

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#8882]
#### Short description of the problem:

The Ionic Sass Variables include the variables shown below. 

```
$toolbar-ios-title-font-size
$toolbar-ios-title-font-weight
$toolbar-ios-title-text-align
$toolbar-ios-title-text-color

$toolbar-md-title-font-size
$toolbar-md-title-font-weight
$toolbar-md-title-text-align
$toolbar-md-title-text-color

$toolbar-wp-title-font-size
$toolbar-wp-title-font-weight
$toolbar-wp-title-text-align
$toolbar-wp-title-text-color

```

However, there is no variable that would allow me to change the `font-family`. Something like

```
$toolbar-ios-title-font-family
$toolbar-md-title-font-family
$toolbar-wp-title-font-family
```
#### What behavior are you expecting?

I would like to use a custom font on the page titles in my app ONLY, but there is no variable that would allow me to do so.

**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Hello again @gigocabrera :) So this is something we could do but it would simply be setting the `font-family` to inherit. Is there a reason you can't use:

```
.toolbar-title-ios {
  font-family: -apple-system, "Helvetica Neue", "Roboto", sans-serif;
}

.toolbar-title-md {
  font-family: -apple-system, "Helvetica Neue", "Roboto", sans-serif;
}

.toolbar-title-wp {
  font-family: -apple-system, "Helvetica Neue", "Roboto", sans-serif;
}
```

Where font-family is equal to whatever you want it to be. Just trying to understand your use case!

**Comment by gigocabrera** [comment]
Hi @brandyscarney your suggestion makes sense and works as expected. I don't have a particular use case to need a new SASS variable for font-family. However, it looks like its missing by reading the documentation. I mean you have a SASS variable for all the other properties (size, weight, align, color) except for font-family. 

I think the best approach would be all or nothing. That would make more sense. Wouldn't you agree?
