### ISSUE TITLE
Icon inside ion-option?

### ISSUE THREAD

**Issue by fuggfuggfugg** [driftyco/ionic#8883]
#### Short description of the problem:
Is it possible to add an icon inside Select `<ion-select> <ion-option>` ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by aneeskodappana** [comment]
Is there any way to add icon inside ion-option

**Comment by jagadeeshvadranapu** [comment]
Is there any way to add icon inside ion-option ???
