### ISSUE TITLE
[Bug] Barrel not working, fails silent

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#8884]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ok so i have some barrels setup in one folder, it was working before i updated to RC.1 and `@ionic/app-scripts`, however when i updated errors started popping out saying:

![image](https://cloud.githubusercontent.com/assets/9698639/19665846/b5685904-9a0c-11e6-89c8-0215d484f4ef.png)

Where the 3 question marks are placed, those are the ones coming from that specific barrel, i'm aware that order matters when those providers depends on each other, so the ones without any deps on other providers goes up in the file, while the ones that depends on other providers has to go after each of their providers dependencies.

Maybe it's not `ionic-angular` but `@ionic/app-scripts` the one has this issue so i'm making a copy of this issue in their repo:
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an app-scripts related issue I am going to close this one and track this issue in the app-scripts bug you linked too. Thanks!
