### ISSUE TITLE
Ionic 1 console font color for livereload is unreadable

### ISSUE THREAD

**Issue by jraoatlogic** [driftyco/ionic#8888]
#### Short description of the problem:
When running on device with live reload and redirect messages to cli, the default console font color is dark blue, this is unreadable on black background.

#### What behavior are you expecting?
Use a color that is readable.

**Steps to reproduce:**
1. Run an app with live reload on device
2. Trigger app js to print something to console.log
3. Read the message on command line window

```
ionic run android -l -s -c
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 This is on Windows

**Which Ionic Version?** 1.x

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1589

**Comment by jgw96** [comment]
Hello, since this is an issue with the ionic cli and not the framework I have moved this issue to the cli repo. Thanks!
