### ISSUE TITLE
bug: quick click back button, will occur blank screen .

### ISSUE THREAD

**Issue by TongeJie** [driftyco/ionic#8891]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>when push three page , then quick click back button, will occur blank screen .
issue reproduce : https://github.com/TongeJie/ionic2-push-issue</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Can you try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by ShawnXu** [comment]
Same here. "double tapping" the back button leads to blank screen.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue as duplicate of https://github.com/driftyco/ionic/issues/8881.
