### ISSUE TITLE
ionic2: JSONP injected script did not invoke callback.

### ISSUE THREAD

**Issue by ksphp** [driftyco/ionic#8896]
## Code
```
this.jsonp.request('http://192.168.3.9:8200/data/index/home/1/?callback=JSON_CALLBACK').subscribe(res => {
    console.log(res.json());
});
```

## Jsonp
```
JSON_CALLBACK({"slide":[{"title":"\u57ce\u5e02\u5408\u4f19\u4eba","src":"http:\/\/192.168.3.9:8200\/data\/..\/upload\/m\/slider\/2016102513181886.jpg","url":"url"},{"title":"\u65b0\u7528\u6237\u900125\u5143\u4f18\u60e0\u52b5","src":"http:\/\/192.168.3.9:8200\/data\/..\/upload\/m\/slider\/2016102513211499.jpg","url":"url"}]})
```

## Error
1. Uncaught ReferenceError: JSON_CALLBACK is not defined(…)
2. EXCEPTION: Response with status: 200 Ok for URL: http://192.168.3.9:8200/data/index/home/1/?
3. Uncaught Response："JSONP injected script did not invoke callback."

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum] (https://forum.ionicframework.com). Thanks for using Ionic!
