### ISSUE TITLE
perf: evaluate use of requestIdleCallback

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#8897]
Looks like we can effectively delay expensive operations with a chrome-only api. We should polyfill it.

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback
https://developers.google.com/web/updates/2015/08/using-requestidlecallback
http://caniuse.com/#feat=requestidlecallback

Thanks for the idea @douglasduteil at ngEurope !

**Comment by jgw96** [comment]
I think this is a great idea! `requestIdleCallback` is also being implemented in Firefox (in fact i think it is in the latest nightly build).

**Comment by astec** [comment]
As a matter of education can you give an example of an expensive operation in Ionic 2 that can/should be scheduled for `requestIdleCallback`? As DOM changes should not be done within it I wonder what else?

**Comment by jgw96** [comment]
Hello everyone! I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#102
