### ISSUE TITLE
bug: template not loading because of undefined LOCALE_ID

### ISSUE THREAD

**Issue by mscherer82** [driftyco/ionic#8899]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>If I try to use the currency pipe I got an exception and the whole template is not rendered. The exception is caused because LOCALE_ID is undefined. 
In Browser it is set to a default value ("en-US") but on device it is undefined. I tried to set the default value manually described here: http://stackoverflow.com/a/39344889 but the function (e.g. settingsService.getLanguage()) is never called. In browser everthing works fine.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
