### ISSUE TITLE
v2: Android touch bug!!!

### ISSUE THREAD

**Issue by wilhantian** [driftyco/ionic#8900]
Ionic version: ionic2-rc.1

Phone model: Samsung GT-N7108
Android version: 4.3
Core version: 3.0.31-2848223

Description: 
I'm using the ionic official Tabs-Demo source with my app, but after I open my app on my mobile phone, nothing happened when I click any button, like freezed. The Tab style also not correct.

[!screenshot](https://raw.githubusercontent.com/wilhantian/wilhantian.github.com/master/screenshot.png)

**Comment by wilhantian** [comment]
@jgw96 Hi, running on crosswalk & android 4.3 emulator is ok.

**Comment by mlynch** [comment]
@wilhantian can you clarify please. Is it working on crosswalk? Additionally, is it working in the emulator?

So, is this just a stock web view issue with that device and 4.3?

Thanks.

**Comment by faik** [comment]
@mlynch same here. Touch is non-responsive with a 4.1.1 Samsung device and also with emulator Android 4.1.2 API Level 16 Intel Atom (x86) system image. 

You can try this with emulator and latest ionic-conference-app.

**Comment by jgw96** [comment]
Hello all! So on Android devices running versions of android before 4.4.x it is normally advisable to use crosswalk to get a standard, modern chrome based webview. Older Android devices running stock Android older than 4.4 used something called the `Android Webview` which lacked HTML5 and CSS3 support (especially on Android 4.1). Also on some devices before 4.4 which did not run stock Android such as Samsung they sometimes used a non standard samsung webview, which most of the time had even worse html5 and css3 support unfortunately. With 4.4 Google switched to a chrome based webview which had much improved HTML5 and CSS3 support and most devices stopped using proprietary webviews. Finally with Android 5.0 Google introduced an independently updatable chrome webview that is updated to the latest version of Chrome along with the Chrome browser on the device. This means the device will always be running the latest version of chrome as the webview, giving you access to the latest HTML5 features no matter if your running `5.0` or the latest `7.1`.
