### ISSUE TITLE
Ionic2 - bug(searchbar) - Cancel button always shows when [animated]="true"

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8903]
#### Short description of the problem:

The cancel button next to the searchbar is always shown when settings animated = true, despite showCancelButton being set to false by default.
#### What behavior are you expecting?

I expect the the cancel button to be hidden by default, as described in the docs, even when animated = true

**Comment by manucorporat** [comment]
Can't reproduce it...

**Comment by zakton5** [comment]
Hm. I'll take another look

**Comment by JeroendeVin** [comment]
I can confirm this issue in RC2

**Comment by zakton5** [comment]
Yeah, I am still having this issue, but I am using RC1. It happens regardless of where I place the searchbar (content or header)

**Comment by manucorporat** [comment]
@zakton5 @JeroendeVin please provide some source code / screenshot / animated gif. I am not seeing anything unexpected.

**Comment by zakton5** [comment]
This GIF is with the following code:

```html
<ion-searchbar [(ngModel)]="searchText" [placeholder]="'Search'" [animated]="true" [showCancelButton]="false" (ionInput)="filter()" (ionCancel)="cancelSearch()"></ion-searchbar>
```

![ionic2_animated_searchbar](https://cloud.githubusercontent.com/assets/7013396/20065233/61d6a4ba-a4db-11e6-80e5-c6b378d26264.gif)

Setting animated to false hides the cancel button correctly.

**Comment by manucorporat** [comment]
@zakton5 @JeroendeVin fixed!
