### ISSUE TITLE
bug: [Bug] Ionic build android broken, ionic serve ok

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#8904]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm using `ionic build android` to see the actual output of the compilation process, however it shows errors without any file line number, not very explicit, while the `ionic serve` command works ok:

![image](https://cloud.githubusercontent.com/assets/9698639/19695049/4ae0c97c-9aa7-11e6-9fd5-02ad1db7a990.png)

</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#241

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a build related issue I have moved this issue to the app-scripts repo.
