### ISSUE TITLE
Ionic 2 - Single page with right side menu will not open on alternate page load (gif)

### ISSUE THREAD

**Issue by anandmehrotra** [driftyco/ionic#8908]
#### Short description of the problem:
![scroll](https://cloud.githubusercontent.com/assets/3237098/19704374/69b47e2e-9ad5-11e6-8184-35d95b20d001.gif)

#### What behavior are you expecting?

A single page with the "Right Menu" won't open the second time. On further debugging, the ` this._isEnabled = false;` is set [here](
https://github.com/driftyco/ionic/blob/master/src/components/menu/menu.ts#L345) the when I tap the 'Tasks' page to reload the second time.

![screen shot 2016-10-25 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/3237098/19704831/5caa17dc-9ad7-11e6-8be5-59dae557d452.png)

Hence, When it comes into [setOpen](https://github.com/driftyco/ionic/blob/master/src/components/menu/menu.ts#L407) Method, it doesn't go into the `_before()` method. 

![screen shot 2016-10-25 at 5 03 04 pm](https://cloud.githubusercontent.com/assets/3237098/19704838/63e157f4-9ad7-11e6-89a5-2be929c741df.png)

MY CURRENT SOLUTION

```

  <ion-col width-25 class="filter-col" (click)="toggleMenu()" tappable>
        <ion-icon ios="ios-funnel" md="md-funnel"></ion-icon>
  </ion-col>

  public toggleMenu(){
    let m = this.menu.get('filterMenu')
    m.enabled = true 
    m.open();
  }
```

**Comment by manucorporat** [comment]
I can't reproduce this bug, how is hasEnabledSameSideMenu true?
can you create a repo that reproduces the issue?

**Comment by fuggfuggfugg** [comment]
Hi @manucorporat 

https://github.com/fuggfuggfugg/ionic-sidemenu, Gif attached in the readme

**Comment by manucorporat** [comment]
why the right menu is in a different page?
Both menus should be in `app.html`, then you enable/disable them!

**Comment by fuggfuggfugg** [comment]
@manucorporat 
Thanks for following up. I understand what you are saying. 

However in my case, the right menu (filter options) are dynamic based on the data I get from the api when the page is loaded. You have thoughts on how I should approach this case?

**Comment by digaus** [comment]
This is exactly the problem I faced... added a filter menu to a specific page results in this behaviour. Should be changed so we can use menu component in child pages without this workarround...

**Comment by mebibou** [comment]
I was playing with adding `ion-menu` within a page directly as well, and I think it works well if you specify `<ion-menu side="right">` and also on the toggle button `menuToggle="right"` and eventually in the menu itself if you add a closing button `menuToggle="right"`. Haven't had any issue yet on this, but it would be great if menu was thought out to be a component that each page can have or not, and not just at the top level where you define them and then the content is not dynamic (a bit like on Slack on the right side where the menu can have many different views)

**Comment by moganty** [comment]
Facing the same issue.... @anandmehrotra your solution worked for me.... thanks
