### ISSUE TITLE
ion-view is not removed and scope not destroyed if back animation disabled

### ISSUE THREAD

**Issue by malwatte** [driftyco/ionic#8911]
#### Short description of the problem:

ion-view is not removed and scope not destroyed if back animation disabled

I want to go back to previous screen without an animation.
So I did this

```
$ionicHistory.nextViewOptions({
      disableAnimate: true
 });
$ionicHistory.goBack();
```

But the problem is view is not removed and destroyed if I disabled the back animation. $distroy event not fired and I still can see the ion-view in the DOM. With animation enabled it works fine.
How can I can go back without an animation properly?

And I also found that if we going back 2 screens without an animation using
$ionicHistory.nextViewOptions({
          disableAnimate: true
     });
$ionicHistory.goBack(-2);
it works fine. Last 2 screens are properly removed and destroyed.
Issue is going back 1 screen without an animation.
#### What behavior are you expecting?

ion-view should be removed and scope destroyed when going back without an animation.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://forum.ionicframework.com/t/view-is-not-destroyed-if-back-animation-disabled/68227

**Which Ionic Version?** 1.2.4/1.3.2
#### Plunker that shows an example of your issue

http://codepen.io/smalwatte/pen/pEBvNW

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.2
Ionic CLI Version: 1.7.1
Ionic App Lib Version: 0.5.1-beta.0
ios-deploy version: 1.8.2 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#76
