### ISSUE TITLE
iOS keyboard issue: text entered in not visible in ion-input until keyboard was closed

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#8915]
Ionic v2, ios

There is the problem with ion-input.
When I start typing letter in ion-input field means, no letters were visible (sometimes only first letter was visible) but cursor was visible and keep moving. But when I close the keyboard by tapping outside, now the text entered was visible.

I've tested in both ios9 and ios10.

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by pensacola1989** [comment]
@dheran have you fixed this issue?

**Comment by dheran** [comment]
@pensacola1989  use `CDVWKWebViewEngine `for ios

**Comment by boblikesoup** [comment]
@dheran Have you found any way around this besides CDVWKWebView? Seems like I'll have to downgrade to Cordova 3.0 to make it work, and our app is already really far along.

**Comment by ireade** [comment]
Adding this worked for me:

```css
ion-input {
  -webkit-transform: translateZ(0) !important;
}
```

See https://forum.ionicframework.com/t/ion-input-shows-only-the-first-entered-character-on-ios/73107/5?u=iaderinokun
