### ISSUE TITLE
Opening Datepicker on 2nd stacked modal doesn't show 

### ISSUE THREAD

**Issue by JeroendeVin** [driftyco/ionic#8922]
#### Short description of the problem:

The (date)picker component isn't displayed on top of the top modal in the stack

**Steps to reproduce:**
1. Open a modal (Modal 1). From that modal, open another modal (Modal 2) 
2. On Modal 2, use 

```
<ion-datetime displayFormat="DD MM YYYY" [(ngModel)]="startDate"></ion-datetime> 
```

3  Click/tap the <ion-datetime /> field to start showing the picker. It doesn't appear
4. Close Modal 2: Modal 1 is show, with the picker on top of it

Maybe the picker has the wrong z-index (I'm just guessing here...)

**Which Ionic Version?** 1.x or 2.x
2.x

**Comment by jwenzler** [comment]
Yes, it looks like the `ion-picker-cmp` has a z-index of 9999 where the modals start at 10000 and increment.

Dirty quick fix...
```
ion-picker-cmp {
  z-index: 20000 !important;
}```

**Comment by palsch** [comment]
Hi, I have the same issue opening Loading on Modal 2. 

z-index should increase like it does if you open a new Modal from an already opened Modal. 
* Modal 1: z-index = 9999 
* Modal 2: z-index = 10000
* Loading: z-index = 9999 !!! But has to be 10001

**Comment by cmanou** [comment]
Same issue applies to action sheets and alerts, opened from a second modal

**Comment by shuhanxu** [comment]
same issue for alerts and toast

**Comment by itrethan** [comment]
Opening alert on page pushed on top of modal is not shown.

It's exactly the same reason explained by @palsch 

Please fix.

**Comment by manucorporat** [comment]
@itrethan @shuhanxu @cmanou @JeroendeVin 
Can you confirm this is still a problem in latest version? according to me test this should be fixed now
