### ISSUE TITLE
Base64 image doesn't show in IonicView (iOS v10.0)

### ISSUE THREAD

**Issue by hothmiles** [driftyco/ionic#8924]
Hi 

I have a small issue with Ionic View and the use of the camera with Ionic2, when I upload my app on Ionic View and try to use to picture I just took it works just fine with an Android device but not on iOS. Strangely when I build on my device with Xcode then the picture is rendered perfectly. 

`then((imageData) => {
      this.base64image = "data:image/jpeg;base64," + imageData;`

` <ion-card-content>
      <img [src]="base64image" *ngIf="base64image" />
    </ion-card-content>`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#192

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an Ionic View issue I have moved this issue to the ionic view repo.
