### ISSUE TITLE
Update of www/assets folder

### ISSUE THREAD

**Issue by hadrien-toma** [driftyco/ionic#8925]
#### Short description of the problem:
It seems that the built assets folder (www/assets) is not updated from the source folder (src/assets) when building.

#### What behavior are you expecting?
I would like to have the assets folder updated. For the moment, to have it working I have to do:
```
rm -rf ./www/assets/html
ionic serve
```

**Which Ionic Version?** 2.0.0-rc.1

**Comment by zyxins** [comment]
+1

**Comment by oborudko** [comment]
+1

**Comment by ghenry22** [comment]
Also noticed this one with rc1

**Comment by EugeneNews** [comment]
+1

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/driftyco/ionic-cli/issues/1599.
