### ISSUE TITLE
no valid session found,must call init and login before logout

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic#8937]
_From @adirzoari on October 22, 2016 17:26_

I only have login via facebook in my ionic 2 app. I installed cordova plugins for that. Sometimes I see this message pop up on my app:

> no valid session found,must call init and login before logout
and my app crashes. Below is a screenshot:

![screenshot_2016-10-21-16-54-36 525](https://cloud.githubusercontent.com/assets/20258998/19621221/bf82afac-9895-11e6-874b-7387d9498ac7.png)

I have already tried to delete the app and install it again but the issue still persists.

_Copied from original issue: driftyco/ionic-cli#1579_

**Comment by adirzoari** [comment]
@jthoms1 thank you. 
anyone has solution for that?
I'm still stuck with that.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#756

**Comment by jgw96** [comment]
Hello @adirzoari sorry for the moving around of this issue, but this is actually an `ionic native` issue so I have moved it to that repo. Thanks!
