### ISSUE TITLE
cybersource payment gateway integration ionic

### ISSUE THREAD

**Issue by bhandaribhumin** [driftyco/ionic#8938]
Hey, anyone know about how to integrate cybersource **payment gateway** in my ionic app,

Documentation Refer:
https://www.cybersource.com/developers/getting_started/integration_methods/secure_acceptance_sop/

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
