### ISSUE TITLE
Google Nexus 6 shows blank screen for apk created by phonegap site and ionic 1.2.4 html framework.

### ISSUE THREAD

**Issue by mobileias** [driftyco/ionic#8939]
Hello

Here is our live google play store url
https://play.google.com/store/apps/details?id=com.instantautosite.oneshop
This build is created by phonegap build site (https://build.phonegap.com/)
We have used ionic html framework for this app.

We use phonegap 6.3.0 cli version

`<preference name="phonegap-version" value="cli-6.3.0" />`
`<plugin name="cordova-plugin-splashscreen" source="npm" version="4.0.0"/>`
`<plugin name="cordova-plugin-network-information" source="npm" version="1.3.0" />`
`<plugin name="cordova-plugin-statusbar" source="npm" version="2.2.0" />`
`<plugin name="cordova-plugin-device" source="npm" version="1.1.3" />`
`<plugin name="cordova-plugin-dialogs" source="npm" version="1.3.0" />`
`<plugin name="cordova-plugin-inappbrowser" source="npm" version="1.5.0" />`

also we have added some basic config preference for splashscreen related also and all is fine in other devices.

We checked almost all device and it working fine.
but last few days it shows blank screen on google nexus 6 device. (not open any page)
it has android 6 version.
it not shows any error log in console log
so can you please help me for this issue related. ?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I just downloaded and tested your app on both a Nexus 6 running Android 7.0 and a Nexus 7 running Android 6.1.1. On both devices the app worked perfectly. When you run `ionic run android` to push it to your nexus device does it work?

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
