### ISSUE TITLE
Ionic 2 RC0: Slower on Android than iOS

### ISSUE THREAD

**Issue by graphicsxp** [driftyco/ionic#8940]
My application is taking about 12 seconds to launch on Android. Whereas it takes less than 5 seconds on iOS. 
Running feels fast on both platform, however the application is not doing much at the moment, and with additional feature I suspect it may get sluggish on Android. 

The hardware is pretty much the same. So why is there such a performance different at application startup ? Is there something that needs to be tweaked for Android ? 

The application was compiled in production mode and uses app-scripts 0.0.36.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Is your app available on Github? If not could you zip up your app and send it to justin@ionic.io ? Also, what device and version of Android are you testing with?

**Comment by jgw96** [comment]
Also, we just fixed an issue in the conference app where the splashscreen accidentally had a delay of 10 seconds on it, potentially causing the issue your seeing here if you were testing with the conference app.

**Comment by graphicsxp** [comment]
Sure, it is: https://github.com/graphicsxp/ecdt-mobile
I'm using Android 6 on a umi max with 3 GB RAM

**Comment by jgw96** [comment]
Hello, so unfortunately I could not get this application to run on my dev machine. Im guessing the kendo-charts package you are using is a private package? Also, just from looking I do not see anything wrong that would cause any weird perf issues on Android compared to iOS. Would you mind giving the [conference app demo](https://github.com/driftyco/ionic-conference-app) a try on your Android device and see if thats also slow? Finally, you can use `chrome://inspect` to inspect the application running on your device which may give some insight into what is causing the slowdown.

**Comment by graphefruit** [comment]
@jgw96 I can confirm this problem aswell. Ionic2 is realy so much slower and even more alggythen ionic1.
I'm porting my app from 1 to 2 and the version on 2 is so laggy.
Pages needs approx 3 to 4 times more loading time and "pull to reload" laggs hard.

**Comment by jgw96** [comment]
Hello @graphefruit what device and what version of Android are you testing with? Also, do you have any example repos that are slow on your device that you can post so I can test on my devices?

**Comment by graphefruit** [comment]
Hey @jgw96 thanks for your response, sadly this app is currently in development stadium and therefore has no API-Access etc, where this problems would show up.

- I'm using a HTC One M8 with Android 6 (Vanilla).
- Ionic RC 2

The main problems I encountered:
- Startup time
- Slower page changes (In Ionic 1 the page nearly load instant without any delay)
- Transitions shatters sometimes when more content.

Another problem is the performance on Windows-Phone-10 devices.
On my Microsoft Lumia 550 pages changes takes from 2 to 3 seconds without any content or just a less content. 
(Cant compare the performance on WP from 1 to 2)
Greetings
Graphefruit

**Comment by jgw96** [comment]
Hello @graphefruit ! No problem. Could you give https://jgw96.github.io/ionic-conference-app/www/#/ a try and see if that is also slow for you? Thanks.

**Comment by graphefruit** [comment]
Hey @jgw96 Thanks for the link,

I've made a small video from my Lumia 550, and how the performance is going. 
After its a bit bigger, I've uploaded it on youtube, hope its fine for you.
Here's the link: https://www.youtube.com/watch?v=T5RFOoptiqU

Lumia 550:
1 GB Ram, Windows 10 Mobile  (10.0.14393.321), Qualcomm Snapdragon 210 Quad Core Prozessor with 1.1 GHz rate.

Greetings
Graphefruit

**Comment by jgw96** [comment]
Thanks for the video @graphefruit ! Do you have the same performance issue on your Android device with the same app? Mind making a video of it too?

**Comment by graphefruit** [comment]
Hi @jgw96 sure, here we go: https://www.youtube.com/watch?v=nmoa6prNgpo
I gonna check out tomorrow an older device and install crosswalk (Note 1 / Nexus 7) and have look there how it works.

On Android its almost flawless, just the click on "speakers" showed a brief delay, aswell as the "Continue" button on the startup-slider. 
I've "checked" the startup time within my old app and the sample conference app.

Ionic1: 3.30 seconds (HTC One M8)
Ionic2: 4.10 seconds (HTC One M8)

Greetings

**Comment by jgw96** [comment]
Hey @graphefruit ! Thanks so much for this, really really appreciate all the testing and info! So first off I wouldn't use crosswalk with a Nexus 7. Crosswalk is usually behind the native chrome webview in android 5.0 and up (which your Nexus 7 should be running) which usually means it is gonna be a touch slower. Very much looking forward to your test on your Note 1 with Crosswalk. Second, regarding load time. This is something that we are constantly working on and take very seriously. With the current state of build tools out there it is very hard to get a tiny Angular 2 bundle. We are currently working through an issue with Webpack 2 that unfortunately breaks tree-shaking. This means that our current bundle is not tree-shaken like we want it to be therefore causing the bundle size to be bigger than it could be. We are also looking into things like doing code splitting and background lazy loading of modules (like the Angular router is capable of) which could help even more. Looks for bundles sizes to get smaller and smaller in the coming months. Again, thanks for all the testing and I cant wait to see that note 1 with crosswalk test!

**Comment by graphefruit** [comment]
Hey @jgw96 thanks for the detailed explanation!

Sorry I didn't specify my Nexus 7, its the old 2012 model without 5.0, its running on 4.1.2.

I've installed crosswalk now (2.1 - 2.2 is crashing) 

Note 1 - Android 4.1.2 - https://www.youtube.com/watch?v=37tj7ZoVtlA
Nexus 7 - 2012 - Android 4.1.2 - https://www.youtube.com/watch?v=qnMyDhvaks4

You'll notice that on Note 1 the startup slider is a bit "lagging" and not fluid after swiping.
Both show the same when clicking elements, there's a brief delay, then the animation gets triggered and after that, the action is executed. (https://www.youtube.com/watch?v=37tj7ZoVtlA - Time 1.11 to 1.14).

Startuptime:
Note 1: 7.3 s
Nexus 7: 7s.

**Comment by jgw96** [comment]
Awesome vids! So it looks like the main issue on your Note 1 and your Nexus 7 is the delay when navigating and the lagging of the slider. So as a test could you try setting the `activator` property in your [config](http://ionicframework.com/docs/v2/api/config/Config/) to `'highlight'` ? Im wondering if its the ripple that is causing the delay and setting that config will get rid of the ripple effect on buttons and tabs. So on that weird behavior on your Note 2, do you know if Cyanogen uses the stock chrome webview in their 6.0.1 build ? Also, in chrome on your note 2 with the [PWA version of the conf app here](https://pwa.ionic.io/ionic-conference-app/www/#/) do you get the same rendering bugs?

**Comment by graphefruit** [comment]
Hey, I gonna give this a try on monday (11.10), won't get in touch with it before sorry =/.
I'll update this post on Monday (around lunchtime in Germany)
Greetings

**Comment by jgw96** [comment]
Hmm interesting. Thanks for the video. So it looks like the ripple does not have anything to do with this. The time it takes to switch pages on older/slower devices is definitely something that we need to look into. Thanks again for all this info, gives us alot to work from.

**Comment by graphefruit** [comment]
@jgw96 If I can help you any further just give me a call.

Sadly I'm not that deep into angular2/ionic2 to debug the performance/timline rightly to provide some information about the discussed problem.

Question:
If you're doing changes here, maybe it could affect Windows-Phone also (There was a huge performance gap compared to android)?
I hope you also consider to buff windows-phone even if its not such a big spreaded platform.
(In my development history many asking for windows phone aswell, specially in Germany many people use this device)

Thanks so far for your help and your efforts so far.
All in all ionic2 is a realy great product, you're doing an fantastic job, thanks for this.
Greetings
Graphefruit

**Comment by jgw96** [comment]
Thanks, will do! We have alot of performance enhancements coming in the next release that should help with the performance issues your encountering. When RC3 is released (should be extremely soon) id love if you could do some more testing on your older devices (:

**Comment by jgw96** [comment]
@graphefruit Hey! Do you think you could try the latest nightly on your older android devices? To install it in your project you can run `npm install ionic-angular@nightly --save`. We have a'lot of perf improvements in this nightly that id love for you to try out!

**Comment by graphefruit** [comment]
@jgw96  Sure! I gonna give it a try on Monday and update this comment!

**Comment by graphefruit** [comment]
@jgw96  Sorry to bother you, I've tried to run the script and get following error:

```
ionic-conference-app@ C:\Users\graphefruit\Downloads\ionic-conference-app-test3\ionic-conference-app-master
+-- UNMET DEPENDENCY @angular/common@2.2.1
+-- UNMET DEPENDENCY @angular/compiler@2.2.1
+-- UNMET DEPENDENCY @angular/compiler-cli@2.2.1
+-- UNMET DEPENDENCY @angular/core@2.2.1
+-- UNMET DEPENDENCY @angular/forms@2.2.1
+-- UNMET DEPENDENCY @angular/http@2.2.1
+-- UNMET DEPENDENCY @angular/platform-browser@2.2.1
+-- UNMET DEPENDENCY @angular/platform-browser-dynamic@2.2.1
+-- UNMET DEPENDENCY @angular/platform-server@2.2.1
+-- ionic-angular@2.0.0-rc.3-201612021933
+-- UNMET DEPENDENCY rxjs@5.0.0-beta.12
`-- UNMET DEPENDENCY zone.js@0.6.26

npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/common@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/compiler-cli@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/forms@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/http@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/platform-browser@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/platform-browser-dynamic@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of @angular/platform-server@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3-201612021933 requires a peer of zone.js@~0.6.26 but none was installed.

```
I've downloaded your latest project from github, and also tried to delete the node_modules folder.
Do I miss a point to execute before `npm install ionic-angular@nightly --save` ?
Sorry & Greetings
Graphefruit

**Comment by graphefruit** [comment]
Hello @jgw96  this topic had a long sit-down, are any new information existing here?
Also I'm referencing #10009 which shows also very slow behavior.

Can you give us please an update? I need to develop for Windows Phones aswell and the performance showed in the linked video isn't realy an eye-catcher.

**Comment by jgw96** [comment]
Hello @graphefruit , sorry for the delay on this. We are constantly working on improving performance in Ionic 2 so that it works just as fast on older android devices as it does on the latest Google Pixel. We are currently working on some things to improve startup time which include code splitting. Also we are hard at work on improving our build system to make our bundles much much smaller and are also working directly with the Angular team on this issue. As this is all being constantly worked on I am going to close and lock this issue for now. Thanks for using Ionic!
