### ISSUE TITLE
Modal window wrapper-class bigger than the modal content

### ISSUE THREAD

**Issue by AT92** [driftyco/ionic#8941]
Hello, I have following issue. I want to create several modal windows on my page, all with different size (not at once). So to change their size I give each "modal-component" a selector, and change the size of the selector in the css. So my modal windows appear as required. But the modal-wrapper is bigger than the window itself, the user can not close the window by clicking in the modal-wrapper area, which is outside of the modal. It would be better, if the modal-wrapper would achieve the same size as the modal window.  

Here is a screenshot of what I mean:

[http://www.directupload.net/file/d/4522/qkmrd273_jpg.htm](url)

Here are my code samples:

That is how I open the modal window.
`
openRegistration() {
    let loginModal = this.modalCtrl.create(Register);
    loginModal.present();
  }
`

That is the css of the selector of the modal window:
`
register-modal {
    padding: 30px 30px 60px 30px !important;
    width: 320px !important;
    height: 620px !important;
    margin: 0 auto !important;
    position: relative !important;
}
`

Kind regards,

Andrej

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.6.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
