### ISSUE TITLE
ion-select options disappears

### ISSUE THREAD

**Issue by Tigeeer** [driftyco/ionic#8942]
I have an issues on ion-select
`<ion-select  [(ngModel)]="book">
      <ion-option *ngFor="let item of books" [value]="item.value">{{item.name}}</ion-option>
   </ion-select>`
When I choose it the second time,the alert is open but the options disappears.Is this a bug?

**Comment by nateOVO** [comment]
I'm having the same issue. I need to click an `<ion-select>` box twice before it shows up.
I noticed that once the current modal page it was on was dismissed, another instance of an `<ion-select>` was present on the page below it, leading me to believe the first click created an `<ion-select>` underneath the 'active' view.

**Comment by Tigeeer** [comment]
I have resolved, the reason is I have two `ion-select` in `ion-item`, but when I click, only the first reply, so I add a class `item-multiple-inputs` to `ion-item`

**Comment by jgw96** [comment]
Awesome! Glad to hear that this was resolved. Thanks for using Ionic!
