### ISSUE TITLE
Button alignment in navBarwhen using menuToggle directive

### ISSUE THREAD

**Issue by nakulgulati** [driftyco/ionic#8943]
Button with directive `[menuToggle]="menuId"` is right aligned on Android and Windows platform when used inside `<ion-navbar>`.

Button is left aligned for all 3 platforms (iOS, Android and Windows) when `menuToggle` directive is used without `menuId` specified, but is right aligned on windows when menuId is specified as such `[menuToggle]="menuId"` on Android and Windows. 

**Steps to reproduce:**
1. Checkout `menuToggle` API documentation: http://ionicframework.com/docs/v2/api/components/menu/MenuToggle/

**Expected Behavior**
`<button ion-button menuToggle>Toggle Menu</button>` and `<button ion-button menuToggle="menuId">Toggle Menu</button>` to behave consistently and the button to be left aligned navbar.

**Which Ionic Version?** 2.x

**Comment by manucorporat** [comment]
Hi @nakulgulati, I don't understand what should be the expected behavior. Can you follow the issue template provided?

**Comment by nakulgulati** [comment]
Hi @manucorporat, I have updated the issue and included 'expected behavior'.

**Comment by manucorporat** [comment]
Thanks @nakulgulati! I added this issue to my roadmap to RC2

**Comment by manucorporat** [comment]
I can't reproduce this issue, for me it is always left aligned. Can you share exactly the same code you are using?
