### ISSUE TITLE
Double navController.pop() execution when quickly tapping auto-generated back button

### ISSUE THREAD

**Issue by Rodmg** [driftyco/ionic#8948]
#### Short description of the problem:

When tapping twice the auto-generated back button in an ``<ion-navbar>`` (mostly by accident), the navController.pop() gets called twice, thus causing the previous page also to be popped, and even worse if the previous page was the first on the stack, you get a blank page.

#### What behavior are you expecting?

Execute navController.pop() only the first time the button is pressed, ignore any other presses.

**Steps to reproduce:**
1. Create a new Ionic 2 project with the sidemenu template:

    ```
    ionic start ionicbug sidemenu --v2
    cd ionicbug
    ```

2. Run the project in an Android or iOS device, the older and slower the device the better
3. In the app, go to the "Page Two" on the side menu and select an Item
4. On the Item page, press the back button repeatedly as fas as possible before it gets dismissed
5. Retry until you get a blank page

This is hard to reproduce because the double tapping must be done very fast, but on older and slower devices it becomes a problem as you have more time to do the tapping, also when debugging via chrome, which makes the device slower, it's relatively easy to reproduce.

I got this problem on iOS (iPad 4 iOS 10) and Android (Moto X 2013 Android 5.1) devices, I could't reproduce it on desktop.
 

**Which Ionic Version?** Ionic 2.0 RC1

**Run `ionic info` from terminal/cmd prompt:**

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by manucorporat** [comment]
This should be fixed in RC2!

**Comment by ramonsan** [comment]
I have same issue in RC3.

System information:
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v4.2.6
Xcode version: Not installed
