### ISSUE TITLE
div fill colls on iOS doesn't work

### ISSUE THREAD

**Issue by resper** [driftyco/ionic#8957]
#### Short description of the problem:

When I use the code below and  ionic serve on my Windows PC with Chrome i get 3 boxes with the same height.

But when I use ionic serve on my mac with Safari it doesn't works. 
The Same when I build the app on my mac and run it on my iPhone.

CSS

```
ion-col div{
    height: 100%;
    padding: 5px;
}
.white-box{
    border: #000 solid 1px;
}
```

HTML

```
        <ion-row>
            <ion-col width-30>
                <div class="center white-box">
                    <strong>VF / PVT</strong>
                </div>
            </ion-col>
            <ion-col width-30 (click)="roscPopup()">
                <div class="center white-box">
                    <strong>ROSC</strong><br />
                    <ion-icon  style="margin-top: 5px;" name="ios-information-circle-outline"></ion-icon>
                </div>
            </ion-col>
            <ion-col width-30>
                <div class="center white-box">
                    <strong>PEA / Asystolie</strong>
                </div>
            </ion-col>
        </ion-row>
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v4.6.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! So this seems to be a safari bug related your custom css using `height: 100%` in flex items. I just tested in Safari 10 and Chrome 54 on my mac and saw the exact same behavior as you. I would recommend just not using `height: 100%` if possible. Since this is not an issue with ionic's css but instead your custom css I am going to close for now. Thanks!

**Comment by resper** [comment]
When Safari and iPhones doesn't support this, I think it is Ionics part to fix this. Do you have another solution? Because when I give the border do the col item, it works, all boxes have the same height but the border collapse, and I have no margin between the boxes.
