### ISSUE TITLE
Swipe back not triggering ionViewWillEnter

### ISSUE THREAD

**Issue by niels1027** [driftyco/ionic#8958]
#### Short description of the problem:

on a swipe back (iOS) from a view 'B' to its previous view 'A', the ionViewWillEnter is not triggered. This causes my refresher and searchbar on the view 'A' not to work. However, when going back from B to A with the back button on the top left there is no problem.

NOTE: ionViewDidEnter does trigger on both, swipe back and back button.

Anyone else having this issue or knows a solution? Thanks

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.8.1
Xcode version: Xcode 8.1 Build version 8B62 

WKWebView
```

**Comment by markisme** [comment]
Does that was fixed?I got the same problem. When i swipe to go back, the refresher doesn't work, but back from the back button work fine.
