### ISSUE TITLE
Storage from @ionic/storage loses data

### ISSUE THREAD

**Issue by Lafaa** [driftyco/ionic#8959]
Hi guys!
Am i the only one having problem with the new Storage since the ionic2 rc0? 

It just forgets everything once the app is restarted. I use the Storage class from @ionic/storage to save username and password, but it's like it get cleaned on app restart. 

I'm using the Storage this way:

```
 public storage: Storage;
...
this.storage = new Storage();
...
this.storage.set(key, value);

```

I've also added the Storage in app.module.ts, both in the import section AND in the providers array. 
Did i get something wrong? In the running and building process i don't have any error or warnings

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0-201610131811
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! It seems that this issue is most likely caused by your use of `new` with storage and by putting `storage` in your `imports` array. Could you take a look at the docs for [ionic storage](https://github.com/driftyco/ionic-storage) and give it another try? Thanks!

**Comment by jherediagu** [comment]
Yes, it's lost data, I have the same problem, I solve it with localforage, like this:

`import localforage from 'localforage';

   localforage.setItem<any>('foo', 'bar');

   localforage.getItem<any>('foo').then( (value:any) => {
      console.log(value);
   });
`

**Comment by jgw96** [comment]
Thanks for the info. Unfortunately I cannot reproduce this issue, would you posting a repo or a zip of your project that I can use to reproduce this issue?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-storage#39
