### ISSUE TITLE
bug: Card images in iOS are deformed

### ISSUE THREAD

**Issue by hi-rad** [driftyco/ionic#8960]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I have created a list of cards using ion-card and *ngFor. In google chrome the ionic serve --lab command works fine in all platforms. However, when using ionic view to test my app on actual devices, Images inside my card are deformed on an iOS device, but not on android. Since I wanted to show a loading on images until they are completely loaded I have used ion-image for my images like this:

```
<ion-img [src]="img.src"></ion-img>
  <ion-spinner></ion-spinner>
```

and  in scss file the following code:

```
.img-loaded + ion-spinner {
  display:none;
}
```

All my images come from a server and they are all 500x500 large</span>

<span is-issue-template></span>

**Comment by ghenry22** [comment]
don't use ion-img except inside virtualscroll.  Just use a standard img [src]

**Comment by hi-rad** [comment]
With a standard img [src] how can I have lazy loading?

**Comment by ghenry22** [comment]
that's something to ask on the ionic forums, I'm not sure.  I just know that the docs say that ion-img is currently for use in virtualscroll lists only and even in that scenario I have found it to be a complete mess at present.

If ion-img is turned into a generic lazy-loading img tag then it would be awesome but at the moment it's not there.

**Comment by hi-rad** [comment]
Thanks
So right now ion-img is a mess and is a work in progress, right?

**Comment by ghenry22** [comment]
that has been my experience trying to use it yep.  I think the ionic guys are probably focusing on getting fundamentals all in place before they loop back to some of these really nice but not critical things like ion-img.  There are a few issues already raised for it if you search on here.

**Comment by jgw96** [comment]
Hello everyone! Thanks for using Ionic! At this time `ion-img` should be only used in `virtualScroll` but there is an [issue open](https://github.com/driftyco/ionic/issues/8102) to make it work outside of virtual scroll. Once we are in stable we will start to focus on features like that. Thanks again!
