### ISSUE TITLE
RC1: process.env.npm_config_argv BUG in the ionic-app-scripts

### ISSUE THREAD

**Issue by JohnKimDev** [driftyco/ionic#8961]
Related to the issue #8257 

The main goal is to recreate a custom gulp scripts that I used in v2beta for v2rc1.
In V2Beta, I had a custom **server:before** script that takes extra **process.argv** and process scripts
like this `ionic server --testing`

In V2RC1, I try to recreate this by using a custom rollup.config.js but (inside from rollup.config.js) `console.log(process.arg);` only have 

`[ '/usr/local/bin/node',  'node_modules/.bin/ionic-app-scripts',  'watch' ]`

The bug is in `node_modules/.bin/ionic-app-scripts`. There is a code to forward the `process.env.npm_config_argv` (line 5) but it does not work as it suppose to do. Since the **build** and **watch** are hardcoded in packasge.json scripts, there is no point of checking `process.env.npm_config_argv` and `process.argv.push` (line 11) 

Any suggestion how to handle custom gulp script-like action to receive process.argv ?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#284
