### ISSUE TITLE
Ionic 2, checkbox input property Binding

### ISSUE THREAD

**Issue by mmazloum** [driftyco/ionic#8964]
#### Short description of the problem:
I try to build a special checkbox list where checkboxes may check / uncheck themselves based on other ckeckboxes being checked or not.

something like : 
`<ion-checkbox [checked]="testValue[_id] ? 'true' : 'false'" color="primary" (click)="updatechecked(checkItem._id)">`

where test value is a boolean dictionnary, and where update checked may update testValue dictionnary behind the scenes.

Since my dictionnary contains booleans It should also work like this : 
`<ion-checkbox [checked]="testValue[_id]" color="primary" (click)="updatechecked(checkItem._id)">`

I've also tried with the disabled input property which works better but I have troubles with conditions like `[disabled]="testvalue && x <3 ? 'true':'false'"`

Playing with [ngClass] and item-checkbox-checked class or [(ngModel)] didn't work too.

(notice that I also display an alert to tell someone it's last check won't be taken see screenshot so may be a nav transition issue ?)

Here is what the screen looks like : 
![image](https://cloud.githubusercontent.com/assets/3626499/19851582/f9508b62-9f5e-11e6-8621-d85d14cedf79.png)

#### What behavior are you expecting?
I expect that the UI visualy doesn't check the check boxes based on those property bindings.

Ionic info : 

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a 

I don't know if I'm doing something wrong or not ? However I may find a work arround playing with buttons instead of checkboxes, so it's just to let you know ;-)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement specific functionality i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
