### ISSUE TITLE
Ionic 2 - Input text error with . (dot char) (android devices)

### ISSUE THREAD

**Issue by thiagohumbs** [driftyco/ionic#8965]
When I type . character and then another character it automatically transforms the next characters into two dot characters like: ..

what I tried to type: **something.more** 
what I the field displays: **something..ore** 

The template code:

`<ion-item>
      <ion-label floating>Information</ion-label>
      <ion-input required type="text"></ion-input>
 </ion-item>`

More infos:

* This error do not happens on browser emulation (it happens only on device).
* There is no mask on the field or any binding
* Device model Samsung S6 - SM-G920I
* Android Version: 6.0.1
* Ionic version: 2.1.1

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v4.6.0

--------------------------------
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by thiagohumbs** [comment]
I tested several devices and it didn't happen, so problaby my S6 keyboard incompatibility, not sure if this kind of issue should be posted here then I closed it.

if someone faces the same problem with Samsung S6/S7 android 6.x when trying to type ZERO and DOT characters please comment here.

**Comment by thiagohumbs** [comment]
I picked more Samsung S6 and S7 devices, and it happens with all of them, so definitely we have a compatibility problem between input texts x samsung keyboards.

I installed another keyboard app (swiftkey) and the problem is gone

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You are correct, this is actually a feature of the default keyboard on `TouchWiz`. Because this is not an Ionic issue, but simply a feature of the samsung keyboard I am going to close this issue for now.
