### ISSUE TITLE
docs: Error in getting started on your website

### ISSUE THREAD

**Issue by GeertVanWonterghem** [driftyco/ionic#8966]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>browser</span>

<span ionic-description>On http://ionicframework.com/getting-started/, it says 
"ionic build ios"
but when I do that, it says 
"? You cannot run iOS unless you are on Mac OSX."</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#861
