### ISSUE TITLE
bug: Plugins broken with latest framework and crosswalk

### ISSUE THREAD

**Issue by geraldapeoples** [driftyco/ionic#8977]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.0</span>  <span ionic-webview>webview</span>

<span ionic-description>I installed the latest cordova, ionic, gulp and bower.

I created a new tabs application, I added crosswalk plugin.

When I deployed to mobile device I got "deviceready has not fired after 5 seconds" error. I removed "cordova-plugin-device", redeployed to the phone and the error was fixed. There is an issue with this key plugin and crosswalk.

Futher testing shows that using "cordova-plugin-network-information" also gives "deviceready has not fired after 5 seconds" error. The "cordova-plugin-camera" doesn't give an error but does not actually work with latest ionic/crosswalk.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#762
