### ISSUE TITLE
Question: Work with Angular cli

### ISSUE THREAD

**Issue by jdell64** [driftyco/ionic#8979]
are there any plans to make ionic2's cli work with the angular 2 cli? or do I have a misunderstanding on these two apps.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! At this time there are no plans for this. Our cli has some special features and tie ins that make it work with Ionic 2, whereas the Angular cli is specially built to work with plain Angular 2. The Angular cli is a great tool, but is just not made to work with Ionic 2. Hopefully this explains it!

**Comment by jdell64** [comment]
Yes, I think so. I guess I get confused at how Ionic is built on/for angular, and yet is completely different.
I'll keep learning.
