### ISSUE TITLE
Built-in back navigation issue on fast, repeated clicks

### ISSUE THREAD

**Issue by danielcrk-cn** [driftyco/ionic#8982]
I'm sure I've seen this reported before but I can't find the report now, so I'm creating a new one.

#### Short description of the problem:
If the back arrow that is automatically added to the navbar is repeatedly (and rapidly) clicked, it will navigate back and the previews page will be closed as well, resulting in a black screen.

**Steps to reproduce:**
1. Push a new page from a root page
2. Repeatedly (and fast) tap/click the back arrow to navigate back

**Other information:**
I haven't notived this bug before so I'm guessing it's new in RC1 (or perhaps RC0). Perhaps it os related to the new navigation queuing? Also, it is a bit seasier to reproduce in ios mode than in md mode, but both do have this bug.
 

**Which Ionic Version?** 1.x or 2.x
Ionic 2 RC1

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has already been fixed in the latest master and will be in rc2 (:

**Comment by danielcrk-cn** [comment]
So nice to hear! :)
