### ISSUE TITLE
Destructive role for AlertController Button

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic#8985]
#### Short description of the problem:
I'd like to see a destructive `role` value for `AlertController`. 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0
ios-sim version: 5.0.6
OS: Mac OS X Sierra
Node Version: v5.0.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
