### ISSUE TITLE
Feature: collection-repeat showing "x of y" items

### ISSUE THREAD

**Issue by CatchSandeepVaid** [driftyco/ionic#8988]
When user scrolls, we should show a message showing "x of y" items and with every scroll value of x will change. 

How can we achieve this Or Do we need to add this as a new feature in collection-repeat ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to implement custom functionality i will urge that you ask this question on our [forum] (https://)forum.ionicframework.com). Thanks for using Ionic!
