### ISSUE TITLE
fs: re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by elmoromourad** [driftyco/ionic#8991]
I'm using Ionic `v 1.7.16`

My current node version is :` v 4`, but when I upgraded it to v 6.9I got this Error :

```
? (node:9656) fs: re-evaluating native module sources is not supported. If you
are using the graceful-fs module, please update it to a more recent version.
```

NB : the application is built successfuly, but plugins doesn't work (for example camera..) and the application blocks

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1617
