### ISSUE TITLE
IONIC2: XCode Missing dependency target "CordovaLib (from CordovaLib.xcodeproj)"

### ISSUE THREAD

**Issue by mflmartin** [driftyco/ionic#8992]
The provided XCode project shows this error, and there is no way to make it work. I've looked everywhere, but there is almost no solutions provided. 

Does anyone have a solution? I have the latest version of XCODE and Mac OSX Sierra for building the iOS version. 

*My system information:*

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.9.1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
