### ISSUE TITLE
Ionic some issues on ios9

### ISSUE THREAD

**Issue by vahidvdn** [driftyco/ionic#8996]
My app works completely fine in **android** and **ios10**. But I have some strange issues in **ios9**. In somewhere `$state.go` doesn't work!

I searched a lot and found this [patch](https://gist.github.com/IgorMinar/863acd413e3925bf282c). But still the same issue.

**Note:** I use ionic package for building ios, hence I can't see the errors. 

Any idea?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by vahidvdn** [comment]
Thank you. But what do you mean by issue template?

**Comment by vahidvdn** [comment]
@jgw96 
Oh my god. After struggling for some days, finally I found out the solution.
I'm using default function parameters. This is supported from From **ES6/ES2015**. As I used this syntax:

    $scope.showActionSheet = function(indexPic = false, width = 500, height = 500, allowEdit = true) {
    }

ios 9 may not supporting this. (more detail [here](https://github.com/driftyco/ionic/issues/9024))
