### ISSUE TITLE
Revisit animation for MD sidemenu

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#8998]
#### Short description of the problem:
Currently our sidemenu feels much faster than the native sidemenu on Android. It opens a good bit faster than the native sidemenu and closes a little faster than the native sidemenu. 

#### What behavior are you expecting?
Our sidemenu to feel equivalent to the native sidemenu on an Ionic 2 app.

**Steps to reproduce:**
1. open the conference app on an android device and open / close the sidemenu
2. open the Google Play app on an android device and open / close the sidemenu
3. notice the difference

**Which Ionic Version?** 2.x

**Comment by manucorporat** [comment]
I think this is already fixed, please @jgw96 reopen it if you feel this issues is not fixed completely.
