### ISSUE TITLE
tab bar not rendered

### ISSUE THREAD

**Issue by shoutcool** [driftyco/ionic#9000]
On the ion-tab API documentation [https://ionicframework.com/docs/v2/api/components/tabs/Tab/](https://ionicframework.com/docs/v2/api/components/tabs/Tab/) the following sample is given:

> Sometimes you may want to call a method instead of navigating to a new page. You can use the (ionSelect) event to call a method on your class when the tab is selected. Below is an example of presenting a modal from one of the tabs.

```
<ion-tabs>
  <ion-tab (ionSelect)="chat()"></ion-tab>
</ion-tabs>
```
But if i put this code in my html view, the whole screen just appears completley white and the tab bar is not shown (even if i set a tabTitle on the ion-tab). But if i click at the bottom of the white screen, i see that the event is called. It seems like the tab bar is on the view, but it's just not rendered!

**Comment by manucorporat** [comment]
@shoutcool please, can you modify the issue following the provided issue template?
I am not sure what you are expecting to happen.

```
<ion-tabs>
  <ion-tab (ionSelect)="chat()"></ion-tab>
</ion-tabs>
```

It is a tab without content and without title.

**Comment by shoutcool** [comment]
Hey @manucorporat 
Thank you for your reply. Of course you are absolutely right. My Tab does not provide any content. The main reason is, that i want to be able to prevent tab changes in some special cirumstances. So my idea was to implement the tab navigation by my own. 

The tabs does not provide any functionality for this and i could not get the ionViewCanLeave() Nav Guard working with tabs.

Nevertheless the ionic documentatation normally contains working examples. But my example at the first post just shows a white window (for the reason you explained well). In my opinion the documentation should be improved in the way the code contains a runnable sample.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#889
