### ISSUE TITLE
Email plugin - not working in ionic view (ios10)

### ISSUE THREAD

**Issue by prasadyallapu** [driftyco/ionic#9004]
Hey @mhartington currently we are adding a email plugin to our app.I am using following cordova plugin [https://github.com/katzer/cordova-plugin-email-composer.git].We are testing the app in ionic view ios ipad with (version 10.0.2).

**Problem:** To use email we wrote a click function to open email plugin,when clicking the button the ionic view is closing.

**Note:**

1. Removed and added cordova plugins multiple times it didnt worked.
2. Added **meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *" came to know that safari had more restrictions in new version**(ios10)**.
3. Current ionic version using in my development is  1.7.7

It will helpful if you suggest if I am missing any?

**My system information:**

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 0.9.27
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 8.1
Node Version: v4.2.1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#198
