### ISSUE TITLE
UI issues in IOS10

### ISSUE THREAD

**Issue by sahildaga95** [driftyco/ionic#9008]
![img_0009](https://cloud.githubusercontent.com/assets/21363907/19968780/feda20c6-a1fb-11e6-9ccf-f19a6dcc57e0.PNG)
UI issues:-
1) In the above image you can see back arrow button and back text getting overlapped.
2) And the ion input box's line getting hidden

The 1st issue is observed in both ios 10 and 9.3
But the 2nd issue observed only in ios 10

**Comment by manucorporat** [comment]
@sahildaga95 please, can you modify your issue following the provided issue template?
Also, can you provide some source code for us to reproduce it?

Thanks!

**Comment by sahildaga95** [comment]
I am building a private application so i couldnt share any github repository !
I am using navcontroller.push to come to this page so i get the back arrow for navcontroller pop to go back to root page. I cant provide the full code.

The following is my HTML file which gives the issue

`<ion-header>
    <ion-navbar color="primary">
        <ion-title>Device Registration</ion-title>
    </ion-navbar>
</ion-header>
<ion-content padding>
    <ion-card>
        <ion-card-header class="border-bottom light-background">
            <h1 color="primary" class="fontsize-18"> Register New Device</h1>
        </ion-card-header>
        <form [formGroup]="deviceForm" name="" id="device-form" class="list">
            <ion-list inset>
                <ion-item [class.error]="!deviceForm.controls.mobile.valid && deviceForm.controls.mobile.touched">
                    <ion-label floating>Enter Mobile Number of the Device</ion-label>
                    <ion-input formControlName="mobile" type="text" maxlength="10"></ion-input>
                </ion-item>
                <div *ngIf="deviceForm.controls.mobile.hasError('required') && deviceForm.controls.mobile.touched" class="error-box"></div>
                <div *ngIf="deviceForm.controls.mobile.hasError('checkNumberValidator')  && deviceForm.controls.mobile.touched && !deviceForm.controls.mobile.hasError('required')" class="error-box">{{ "registration.error.number" | translate}}</div>
                <ion-row>
                    <ion-col no-padding width-50>
                        <ion-list no-lines>
                            <ion-item class="no-padding-left otp-text" [class.error]="!deviceForm.controls.otp.valid && deviceForm.controls.otp.touched">
                                <ion-input formControlName="otp" type="text" maxlength="6" placeholder="Enter OTP"></ion-input>
                            </ion-item>
                            <div *ngIf="deviceForm.controls.otp.hasError('required') && deviceForm.controls.otp.touched" class="error-box">{{ "registration.otp.error" | translate}}</div>
                            <div *ngIf="deviceForm.controls.otp.hasError('checkNumberValidator')  && deviceForm.controls.otp.touched && !deviceForm.controls.otp.hasError('required')" class="error-box">{{ "registration.error.number" | translate}}</div>
                        </ion-list>
                    </ion-col>
                    <ion-col no-padding padding-left width-50>
                        <button block outline ion-button (click)='ResendOTP()'>Resend OTP</button>
                    </ion-col>
                </ion-row>
            </ion-list>
            <ion-grid no-padding margin-top>
                <ion-row>
                    <ion-col text-center width-50>
                        <button full ion-button (click)='callIt()'>CallManager</button>
                    </ion-col>
                    <ion-col text-center width-50>
                        <button full ion-button (click)='validateOTP(deviceForm.value)' type="submit" [disabled]="!deviceForm.valid">Register Device</button>
                    </ion-col>
                </ion-row>
            </ion-grid>
        </form>
    </ion-card>
</ion-content>`

and its corresponding ts file:- 

`import { Component } from '@angular/core';
import {TranslateService} from 'ng2-translate/ng2-translate';
import {Device} from 'ionic-native';
import {FormBuilder, Validators} from '@angular/forms';
import {NavController, NavParams,AlertController} from 'ionic-angular';
import {CustomValidators} from '../../utils/customvalidators';

@Component({
  templateUrl: 'device-registration.html',
})
export class DeviceRegistrationPage {
  deviceForm: any;
  mobile;
  otp;
  constructor(
    private navCtrl: NavController,
    private navParams: NavParams,
    private fb: FormBuilder,
    public translateService: TranslateService
  ) {
      this.manager_number = navParams.get('num');
      this.username = navParams.get('username');
      this.empId = navParams.get('empId');
        this.deviceForm = fb.group({
            'mobile': ['', Validators.compose([Validators.required, Validators.minLength(10), Validators.maxLength(10), CustomValidators.checkNumberValidator])],
            'otp': ['', Validators.compose([Validators.required, Validators.minLength(6), Validators.maxLength(6), CustomValidators.checkNumberValidator])]
        });
  }
  }`

**Comment by sahildaga95** [comment]
Fixed in RC4
