### ISSUE TITLE
Performance alert when deploying to iOS 10.1

### ISSUE THREAD

**Issue by devknack** [driftyco/ionic#9014]
Upon deploying an app (with both ionic 1 and 2) the first time to iOS 10.1 I see the following:

![2016-11-03_09-09-08](https://cloud.githubusercontent.com/assets/11532894/19976578/4aa54dd4-a1be-11e6-98bc-eee5b6fc70b6.png)

From what I can tell online, this is because iOS 10.1 only wants 64-bit apps and the app I am trying to deploy is 32-bit.  According to Cordova, you can build 64-bit apps and have been able to for some time.  Thus, I assume it is also possible with Ionic.  However, there is no documentation on how to do this.

I am doing something wrong or is this truly a bug?

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.38
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: Mac OS X Sierra
Node Version: v6.9.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by comfortme** [comment]
that happened to me too with ionic package build.

**Comment by jgw96** [comment]
Hello @devknack, are you also using ionic package build ?

**Comment by biesbjerg** [comment]
Check your version of cordova-ios - I think that's the source of the issue.

**Comment by Igor-Lopes** [comment]
I've got rid of this warning after I updated my cordova-ios version to 4.3.0 and specified that on package.json. It seems that ionic cli adds iOS by default with an outdated version of cordova-ios.

**Comment by biesbjerg** [comment]
I think platform versions are fixed according to the installed version of Cordova cli. If you have the latest cli (6.4) then iOS 4.3 is automatically installed when adding iOS platform - at least for me.

**Comment by Igor-Lopes** [comment]
@biesbjerg I also have Cordova cli 6.4 and it adds Cordova iOS 4.1.1 to my projects.

**Comment by biesbjerg** [comment]
This states otherwise: https://cordova.apache.org/news/2016/10/25/tools-release.html

> Updated Platforms CB-12039: updated pinned Android to 6.0.0 and iOS to 4.3.0.

Maybe you have the platform pinned to an older version in your config.xml? http://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html#platform-versioning

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https:))forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
