### ISSUE TITLE
[RCx] After update from Beta11 to RCx, i can't run my app on mobile

### ISSUE THREAD

**Issue by rodriguesgm** [driftyco/ionic#9017]
Hi all

So, I spend the last days working on the upgrade to RC0, RC1 and RC2. I had to change all my .js files to .ts files, and some others problems, but finally I could run _ionic serve_ and test my app on a browser.
But I tried to run _ionic run android_ and it didn't work. This is what I'm getting on the console:

![print](https://cloud.githubusercontent.com/assets/10141664/19988380/e43b4a8c-a206-11e6-822b-e5584c25a858.jpg)

To avoid this problem, on ./platform/android/build.gradle, I added the following line

...
android {
   ...
    defaultConfig {
    	**multiDexEnabled true**
        ...
   }
}

This made the _ionic run android_ to work, but when I try to launch the app on my mobile it just doesn't start and show the message "The app stop working".

Does anyone have an idea what it could be?

**Comment by apparition47** [comment]
It's failing because you need to increase your heapsize in your gradle file.

Create a `/platforms/android/build-extras.gradle`, then add:
```gradle
android {
    dexOptions {
        jumboMode = true
        javaMaxHeapSize "4g"
    }
}
```

**Comment by rodriguesgm** [comment]
@apparition47 thanks for the help.
The problem is that even adding the config that I said or adding your config, after build succeed and I try to launch the app on my mobile I get the error "The app stop working". And I have no way to see what happened. My app just doesn't open.

could it be because of some plugin that is not compatible with Ionic2 RCx? Because my app is working fine with beta11. 
Here is the list of plugins I'm using:
cordova-plugin-console 1.0.3
cordova-plugin-whitelist 1.2.2
cordova-plugin-splashscreen 3.2.2
cordova-plugin-statusbar 2.1.3
ionic-plugin-keyboard 2.2.1
cordova-plugin-facebook4 1.7.1
cordova-plugin-camera 2.2.0
cordova-plugin-file 4.2.0
cordova-plugin-file-transfer 1.5.1
cordova-plugin-filepath 1.0.2
cordova-plugin-apprate 1.1.12
phonegap-plugin-push 1.7.4
cordova-plugin-network-information 1.2.1
cordova-plugin-datepicker 0.9.3
cordova-plugin-google-analytics 1.5.6
cordova-plugin-intercom 3.0.8
cordova-plugin-geolocation 2.2.0

**Comment by apparition47** [comment]
If all those plugins worked before your port from beta.11, I don't think that's the issue. Did you try clearing your `/platforms/android/build/` folder before re-building the apk? If that doesn't work, try asking the folks on the [Slack #ionic-v2 channel](https://ionic-worldwide.slack.com/).

**Comment by rodriguesgm** [comment]
@apparition47 yep, I tried that. I tried remove the android platform, clean all plugins and install them again too.
thanks again

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1640
