### ISSUE TITLE
[rc2] Incorrect source maps in ionic

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic#9018]
#### Short description of the problem:
Incorrect source maps in ionic. Take a random map file in component folder, for example ./~/ionic-angular/components/input/input-base.js.map the "sources":["input-base.ts"] does not exist. This is throwing a lots of warning when running unit tests with karma. One warning example:

```
WARNING in ./~/ionic-angular/components/input/input-base.js
Cannot find source file 'input-base.ts': Error: Can't resolve './input-base.ts' in '/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/ionic-angular/components/input'
 @ ./~/ionic-angular/components/input/input.js 12:0-41
 @ ./~/ionic-angular/directives.js
 @ ./~/ionic-angular/index.js
 @ ./src/pages/contact/contact.spec.ts
 @ ./src \.spec\.ts
 @ ./config/karma-shim.js

```

#### What behavior are you expecting?
No sourcemaps provied as in rc1 or correct path for them.

**Steps to reproduce:**
see short description or if you want to test it with unit tests use [this repo](https://github.com/marcoturi/ionic2-boilerplate).

**Which Ionic Version?** 1.x or 2.x
2.0 rc2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

> Cordova CLI: 6.3.1
> Ionic Framework Version: 2.0.0-rc.2
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> Ionic App Scripts Version: 0.0.39
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v6.9.1
> Xcode version: Xcode 8.0 Build version 8A218a

**Comment by dylanvdmerwe** [comment]
Isn't this an app-scripts issue?

**Comment by marcoturi** [comment]
@dylanvdmerwe 
no, the problem is in the ionic-angular package. To prove this, just do rm -rf node_modules/ and npm install and go in the node_modules/ionic-angular/components folder, and you will find the *.map files with the incorrect path to ts files.

**Comment by marcoturi** [comment]
Meanwhile for anyone having this issue, the workaround is to exclude ionic-angular source maps like I did [here](https://github.com/marcoturi/ionic2-boilerplate/blob/master/config/webpack.test.js#L118).

**Comment by jgw96** [comment]
Hello all! @marcoturi and @dylanvdmerwe , are you guys still running into this issue?

**Comment by dylanvdmerwe** [comment]
All good on my side.

**Comment by marcoturi** [comment]
@jgw96 meanwhile i was upgrading my boilerplate to ionic 3, i tried to re-include ionic-angular, and the errors persists:
```
WARNING in ./~/ionic-angular/tap-click/activator-base.js
Cannot find source file 'activator-base.ts': Error: Can't resolve './activator-base.ts' in 'C:\Users\Marco\Sources\Github\ionic2-boilerplate\node_modules\ionic-angular\tap-click'
 @ ./~/ionic-angular/tap-click/activator.js 1:0-55
 @ ./~/ionic-angular/tap-click/tap-click.js
 @ ./~/ionic-angular/index.js
 @ ./src/pages/contact/contact.page.spec.ts
 @ ./src \.spec\.ts
 @ ./config/karma-shim.js
```
