### ISSUE TITLE
Ionic 2. some source file in chrome dev tool missing after some new refresh

### ISSUE THREAD

**Issue by nes16** [driftyco/ionic#9020]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### What behavior are you expecting?

**Steps to reproduce:**
1. build and serve using
ionic serve dev
2. In chrome launch the webapp
3. goto dev to tools source panel
4.all type script source file are shown
5.change the code. and watch fire a new build
6,Refresh the web app.
7.After repeating step 5-7, all source files are not shown in chrome

Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.12.0

More Info:
I enabled  service worker in index.html. After restarting ionic serve dev
they are sync again.

**Comment by nes16** [comment]
v2 build

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#314
