### ISSUE TITLE
async pipe crashing app

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#9023]
#### Short description of the problem:
Angular 2 async pipe is not working in my code. Browser is not responding.

#### What behavior are you expecting?
Pipe should work

**Steps to reproduce:**
I created new ionic 2 project and replaced home.ts and home.html with following code.

`home.ts`
```
import {Component} from "@angular/core";
import {NavController} from "ionic-angular";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  i: number = 0;

  constructor(public navCtrl: NavController) {

  }

  getHeading() {
    let self = this;
    return new Promise(function (resolve, reject) {
      if (self.i === 0) {
        resolve();
      } else {
        reject();
      }
    });
  }
}
```
`home.html`
```
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <h2>{{getHeading()}}</h2>             <---this works
  <h2>{{getHeading()|async}}</h2>   <---this doesn't work
</ion-content>
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8T61a

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Ionic does not actually change anything about the `async` pipe. I would recommend checking out [the Angular docs on the async pipe](https://angular.io/docs/ts/latest/api/common/index/AsyncPipe-pipe.html) for help and if you still have an issue open an issue on the [Angular repo](https://github.com/angular/angular).
