### ISSUE TITLE
conference-app not running in Edge [RC2]

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#9025]
#### Short description of the problem:
I installed node, ionic, cordova and conference-app from scratch for testing RC2.
Started with: ionic serve
While Firefox 49 is running fine, MS Edge (on Win 10) isn't. Screen is blank.

#### What behavior are you expecting?
Running conference app in Edge.

#### Console error log
```
SCRIPT65535: Argument not optional
polyfills.js (3,16552)
SCRIPT5007: Unable to get property '__symbol__' of undefined or null reference
main.js (5640,1)
```

**Steps to reproduce:**
1. Latest ionic-conference-app, ionic2 RC2
2. ionic serve

**Which Ionic Version?** 2.x RC2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.9.1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-conference-app#302

**Comment by mpaland** [comment]
@jgw96 this seems not to be related to conference-app, only.
See #9051 
Please reopen this issue or reference it to #9051 and close the according https://github.com/driftyco/ionic-conference-app/issues/302
