### ISSUE TITLE
Ionic 2 show blank page on android 4.4 the first time

### ISSUE THREAD

**Issue by jbgomez21** [driftyco/ionic#9027]
Hi,

I have a problem with an application using Ionic 2 to generate android 4.4
The application works properly in Chrome, but when run on an emulator with Android 4.4 the following occurs.

1) The home page is loaded and I click the button as shown in the first image.
2) The next page does not load and all android shows a white screen.
3) I press the button to return the device as shown in the image.
4) I go back to click on the button I pressed 1) and this time the page is loaded properly.

What could be happening?

Why the page fail to load first?

Sorry for my english!! :)

![white_1](https://cloud.githubusercontent.com/assets/3789684/20012789/68475662-a28f-11e6-8029-5bedf7150072.png)
![white_2](https://cloud.githubusercontent.com/assets/3789684/20012796/706f5678-a28f-11e6-83d0-e4155a081e90.png)
![white_3](https://cloud.githubusercontent.com/assets/3789684/20012802/762dc234-a28f-11e6-987b-9107a476cf8c.png)
![white_4](https://cloud.githubusercontent.com/assets/3789684/20012807/7b6f7382-a28f-11e6-81d9-f0510caaf0e6.png)

**Comment by ataraxus** [comment]
Hey I think we could have the same issue. Could  you check via chrome developer tools if the page you want navigate to has been inserted and is "just" missing the `show-page` class? 

See my issue here: #9026

**Comment by infinnie** [comment]
Dup of #8769?

**Comment by ataraxus** [comment]
Should be closed due to #8769

**Comment by infinnie** [comment]
@jgw96 @manucorporat

**Comment by jbgomez21** [comment]
Sorry for the delay, but I had problems with the development environment, effectively prove that what is missing is the show-page class.
In my case, this happens only the first time.

regards
