### ISSUE TITLE
Keyboard doesn't close after Prompt Alert input on iOS

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#9030]
#### Short description of the problem:
The input field on prompt alerts doesn't get automatically focused anymore. Furthermore, the keyboard doesn't close when the users cancels or submits the prompt. I get this error on iOS 10.1.1 (no errors in the console). It works perfectly with `$ ionic serve` on the browser.

#### What behavior are you expecting?
Prompt alert shows, input field is automatically focused and keyboard get opened.
After entering text and clicking on a button, the prompt and the keyboard will hide.

**Steps to reproduce:**
1. Generate blank Ionic 2 project: `$ ionic start PromtAlert --v2`
2. Customize `/src/pages/home/home.html` and `/src/pages/home/home.ts` like below.
3. Build iOS project: `$ ionic prepare && ionic build ios`
4. Open project with Xcode from `PromtAlert/platforms/ios/PromtAlert.xcodeproj`
5. Run on real device running iOS 10.1.1

`home.html`
```
<ion-header>
  <ion-navbar>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>

  <button ion-button (click)="showPrompt()">Show Prompt</button>

</ion-content>
```

`home.ts`
```
import { Component } from '@angular/core';
import { AlertController, NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public alertCtrl: AlertController, public navCtrl: NavController) {}

  showPrompt() {
    let prompt = this.alertCtrl.create({
      title: 'Login',
      message: "Enter a name for this new album you're so keen on adding",
      inputs: [
        {
          name: 'title',
          placeholder: 'Title'
        },
      ],
      buttons: [
        {
          text: 'Cancel',
          handler: data => {
            console.log('Cancel clicked');
          }
        },
        {
          text: 'Save',
          handler: data => {
            console.log('Saved clicked', data.title);
          }
        }
      ]
    });
    prompt.present();
  }

}

```

**Other information:**
-

**Which Ionic Version?**
Ionic 2 RC.2

Excerpt from `package.json`:
```
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.39",
    "typescript": "2.0.6"
  }
```

#### Video that shows an example of your issue
[Video of the issue](http://imgur.com/PbPSNWi)

**Run `ionic info` from terminal/cmd prompt:**
```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by peterpeterparker** [comment]
Today my tester noticed the same problem on his iPhone 6 with iOS 10 when he open the Modal of my application, open the keyboard and close the modal. The keyboard stay open. 

I could then reproduce the same behavior in the debugger, even it's complicated to read the currently logs of iOS10 in Xcode, seems no errors are thrown

Related: https://forum.ionicframework.com/t/ios-10-keyboard-stay-open/69528/2

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are currently tracking this issue [here](https://github.com/driftyco/ionic/issues/8185).
