### ISSUE TITLE
Menu is still openable if alert is present

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#9046]
#### Short description of the problem:
If you open an alert and there is a menu on your page, you still can swipe to open/close it while the alert is present.
This is annoying if you have a menu that is disabled on a specific state (ie not logged in) and the user logged out with the menu opened, he won't be able to close it then.

#### What behavior are you expecting?
Disable the swipe event when an alert is present

**Steps to reproduce:**
1. Present an alert on a page with a menu (which has the  swipeEnabled config set to true)

![onic rc2 - ionic app20161105134131](https://cloud.githubusercontent.com/assets/216573/20030080/c646152c-a35d-11e6-9a8c-a8bcd164cd76.gif)

See the [plunkr](http://plnkr.co/edit/Dp1wrXhdrvMMpSNtyGJy?p=preview)

**Which Ionic Version?**  2 rc2

Platform: any

**Comment by manucorporat** [comment]
Nice catch! looks like it is a long standing issue, also affects "swipe to go back". Fortunately it is an easy fix.

Thanks!
