### ISSUE TITLE
bug: deploy update crashing app.

### ISSUE THREAD

**Issue by wattamoves00** [driftyco/ionic#9048]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>i use the ionic deploy. its good but i saw a epic or a critical error because for example you accidentally update your apps with a error issue the apps is totally crash... or is not working ever... help me to fix this issue so that  i will fix my problems. thanks..</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
