### ISSUE TITLE
Duplicate identifier Firebase & Angularfire2 2.rc2 Av2

### ISSUE THREAD

**Issue by EliuFlorez** [driftyco/ionic#9049]
By using Firebase and Angularfire2 together on the same project launches mobile duplication error identification. Because with everyone I can handle Storage while angularfire2 even I can not handle storage. Any ideas. Good job guy. : D

![error-ionic-duplicated](https://cloud.githubusercontent.com/assets/784787/20031266/077e91da-a34b-11e6-8992-bcc535846bfb.jpg)
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

**Comment by florentsuc** [comment]
You don't need any custom rollup configuration anymore.

Remove these lines from your `package.json` file:

```
- "config": {
-    "ionic_rollup": "./scripts/rollup.config.js"
- }
```

**Comment by uzumakinaruto123** [comment]
@EliuFlorez  was the issue resolved ? workaround ?
