### ISSUE TITLE
RC1 swipe-back on iOS doesn't disable vertical scroll

### ISSUE THREAD

**Issue by levymetal** [driftyco/ionic#9052]
#### Short description of the problem:

If you swipe-back on iOS, the content on the current page can still be scrolled. This can be reproduced on both the device and emulator. Video: https://youtu.be/WTS_-KXSW74

#### What behavior are you expecting?

Once a swipe-back is initiated, vertical scrolling should be disabled. 

**Steps to reproduce:**
1. Clone the ionic 2 tutorial app
2. Emulate or run on device
3. Swipe-back while moving finger up and down, the view can still be scrolled.

**Which Ionic Version?** 

2.0.0-rc.1

#### Plunker that shows an example of your issue

No need, the tutorial app exhibits this behaviour.

**Run `ionic info` from terminal/cmd prompt:**

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by manucorporat** [comment]
We are aware of this issue, here's the thing, we can't find yet a good way to disable scrolling

**Comment by levymetal** [comment]
Ah, I see. Is there a way to disable swipe back then? I've tried `<ion-nav [root]="rootPage" swipeBackEnabled="false"></ion-nav>`, and putting `swipeBackEnabled = false` pretty much everywhere but nothing seems to work.

**Comment by danielcrk-cn** [comment]
@levymetal Yes, have a look here:
http://ionicframework.com/docs/v2/api/config/Config/

I'm concidering wring my own "swipe to go back" using the swipe gesture event and manually poping the page from the navstack. It won't be as nice at the native "real time swipe" of course, but better than nothing, and better that the current ionic implementation. Might be worth a try!

**Comment by levymetal** [comment]
@danielcrk-cn Awesome, that worked, cheers for that! I like your idea as a stop-gap until this issue is resolved. Let us know if you end up doing it.

**Comment by biesbjerg** [comment]
This is not fixed in RC3 (at least not in my app). 

I see some logging in XCode console regarding scrolling, but I'm still able to scroll the leaving view in the middle of a swipe back.

```
2016-11-18 01:41:34.562718 Mindly[4939:1396787] App Root: Scroll Disable Assist true
2016-11-18 01:41:35.866311 Mindly[4939:1396787] App Root: Scroll Disable Assist false
```

**Comment by manucorporat** [comment]
@biesbjerg it need hybrid assistance, are you using the latest ionic WK plugin?

**Comment by RikdeVos** [comment]
Any updates regarding issue? I have not yet found a method to disable the scrolling during swipe back.
