### ISSUE TITLE
Updating to RC2 from RC1 - Missing Manifest and Service-Worker

### ISSUE THREAD

**Issue by abartolo** [driftyco/ionic#9053]
#### Short description of the problem:
Followed instructions to update project from RC1 to RC2. Seeing issue below
`
21:57:24]  copy: Error copying "C:\scoutlitProjects\basketball-stat-tracker\src\manifest.json" to
            "C:\scoutlitProjects\basketball-stat-tracker\www\manifest.json": File not found
[21:57:24]  copy: Error copying "C:\scoutlitProjects\basketball-stat-tracker\src\service-worker.js" to
            "C:\scoutlitProjects\basketball-stat-tracker\www\service-worker.js": File not found
`

#### What behavior are you expecting?
Expected for everything to work as expected or to at least ionic serve to work.

**Steps to reproduce:**
1. Follow instruction https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#packagejson-updates
2. delete node_modules folder
3. npm install
4. ionic serve
5. see issue

```
 Package.json i am using
```

`
 "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build",
    "test": "ng test"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/lodash": "^4.14.37",
    "font-awesome": "4.6.3",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "2.15.1",
    "pouchdb": "6.0.6",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.39",
    "@types/jasmine": "^2.5.35",
    "angular-cli": "^1.0.0-beta.18",
    "codelyzer": "^1.0.0-beta.2",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.2.0",
    "karma-remap-istanbul": "^0.2.1",
    "typescript": "2.0.3"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-sqlite-storage",
    "cordova-plugin-device-orientation",
    "cordova-plugin-screen-orientation",
    "cordova-plugin-network-information"
  ],

`

#### Error
![image](https://cloud.githubusercontent.com/assets/5394228/20034847/f809808a-a3a3-11e6-861b-c2e8d1a32ed1.png)

 

**Which Ionic Version?** 1.x or 2.x
Ionic 2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.39
OS: Windows 7 SP1
Node Version: v6.2.0

**Comment by ghenry22** [comment]
these files were under src/assets in RC0, just move them directly under /src and you should be good

**Comment by ramonornela** [comment]
See project ionic2-app-base and adjust  your project

Thanks

**Comment by abartolo** [comment]
@ghenry22 thanks I just copied the missing files and was able to compile but I am now seeing this error on console. The error below wasn't happening in RC1 and i didn't touch any other files in app besides the package.json.

Any idea?

![image](https://cloud.githubusercontent.com/assets/5394228/20041785/9439e02e-a43c-11e6-8a61-57086d1dd169.png)

**Comment by abartolo** [comment]
never mind I fixed it by changing how the dependencies are resolved.

**Comment by skill83** [comment]
@abartolo I', experiencing the same problem. what do you mean with " I fixed it by changing how the dependencies are resolved"

Thanks

**Comment by abartolo** [comment]
@skill83 If you are referring to the issue below.  I am currently mapping @injectable services in a file called "core".... so instead of importing ex. below.
`
import {a} from './a';
import {b} from './b';
import {c} from './c';
`
.. I am mapping into 1 file and importing is 1 line now.
`
import {a,b,c} from './core'
`
Not sure exactly but as soon as I imported them individually it resolved the issue... So that's why I assumed that the order they are imported mattered. I'm not the best technically so if anyone has the exact reason please feel free to let me know =)

https://cloud.githubusercontent.com/assets/5394228/20041785/9439e02e-a43c-11e6-8a61-57086d1dd169.png

**Comment by skill83** [comment]
@abartolo Thanks!
I solved in this way:
import { HttpService } from './http.service';
import { Store } from './store.service';

before i was importing the services like this:
import { HttpService, Store } from './';
