### ISSUE TITLE
Feature: Picker interface for Select component

### ISSUE THREAD

**Issue by alexweber** [driftyco/ionic#9054]
**Type**: feat

**Ionic Version**: 2.x

**Platform**: all

It would be great to be able to use a Picker for select options!

Implementing this would probably also resolve this issue with an acceptable workaround #7850

Happy to write some code if it's a feature being considered... Thanks!

**Comment by alexweber** [comment]
Implementing this would probably also resolve this issue adequately #7850

**Comment by manucorporat** [comment]
This is definitively something we are considering, but right now ionic 2 is feature frozen until a 2.0 final is released.

**Comment by infinnie** [comment]
A workaround with action sheets:

```html
<input type="hidden" [ngModel]="field" />
<button type="button" ion-item class="item-input" (click)="selectClick()">
    <span item-right>{{field}}</span>
    Field value:
</button>
```

```js
selectClick() {
    this.actionSheetCtrl.create({
        title: "Pick an option",
        buttons: [
            {
                text: "Option 1",
                handler: () => { this.field = "Option 1"; }
            }, {
                text: "Option 2",
                handler: () => { this.field = "Option 2"; }
            }, {
                text: "Cancel",
                role: "cancel"
            },
        ]
    }).present();
}
```

**Comment by raychenfj** [comment]
Maybe you can try my component here https://github.com/raychenfj/ion-multi-picker
I just wrap the picker and expose some common interfaces.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#103
