### ISSUE TITLE
Ion Header Bar Title off center until view is refreshed

### ISSUE THREAD

**Issue by ButchMonkey** [driftyco/ionic#9058]
#### Short description of the problem:
Ion Header Bar Title off center even with center in config. I have set the title to center using - 

```
$ionicConfigProvider.navBar.alignTitle('center'); 
```

 However the css applied is right: 5px; left: 55px; until I refresh the view, then it becomes right: 55px; left: 55px; and centers correctly.

Does not appear to happen on browser, only compiling and running the app seems to cause the issue ( I then connect with remote debugger for css info)

#### What behavior are you expecting?
Title bar should be center on first load not after refreshing the view.  corresponds to right: 55px; left: 55px; css

**Which Ionic Version?** 
Ionic, v1.3.0
Cordova CLI:  6.2.0

#### Plunker that shows an example of your issue

N / A due to not occurring in browser, am using cross walk if this has any affect? Dont see why it would if its okay after refreshing the view.

**Can link to cloud environment if needed**

**Comment by Vaelyr** [comment]
Having similar problem. Strangely enough when I run throug `ionic serve` I cannot see it happening, but in lab mode it occurs `ionic serve -lab`, but ONLY for Android. iOS is fine for some reason.

**Comment by ButchMonkey** [comment]
I ended up forcing it with css, dont really like to do that but had no choice

**Comment by Vaelyr** [comment]
I found a cause and current solution for this. It seems that the animated transition CSS for Android is having some issues. By using the "ios" transitions it works fine.

`$ionicConfigProvider.views.transition("ios");`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#72
