### ISSUE TITLE
Animate navCtrl.setRoot()

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic#9061]
#### Short description of the problem:
It would be great if I could make it look like navigating to another page if when I use NavController.setRoot(Page). Perhaps something like NavController.setRoot(Page, {animate:true}). Currently, it simply changes the page.

#### What behavior are you expecting?
Animation.

**Steps to reproduce:**
1. call setRoot(anotherPage) on a page
2. use your eyes to watch animation not happen
 

**Which Ionic Version?** 1.x or 2.x
2.0.0-RC2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.4.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by wbhob** [comment]
Nevermind, I found it. If you find this issue looking for the same thing, you can pass it like this:
```
OPTIONSOBJECT = {
    animate:true,
    direction: "forward" // or "backward"
}
setRoot( Location, navParamsObject, OPTIONSOBJECT);
```

**Comment by wbhob** [comment]
or,
 ```ts
this.navCtrl.setRoot(Location, {}, {
    animate:true,
    direction: "forward" // or "backward"
}```

**Comment by lightyaer** [comment]
I dont know why it doesnt seem to work on my side, even if I set the duration to 1000 it doesnt seem to show any animations when I setRoot(),

**Comment by wbhob** [comment]
Yes, you need an empty object for navParams. Notice there are THREE arguments, the last one is the animation properties.

**Comment by lightyaer** [comment]
Yes, I know that, passed an empty object for navParams but still no animations, I'm viewing the app in browser though

**Comment by wbhob** [comment]
anything in the console?

**Comment by wbhob** [comment]
also, `ionic info`?

**Comment by lightyaer** [comment]
@ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.9.5
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : pro

thats the Ionic Info and nothing in the Console!

**Comment by wbhob** [comment]
Ok, that checks out. Code example?

**Comment by lightyaer** [comment]
So Sorry, My mistake , I added animations to some other method's setRoot

**Comment by wbhob** [comment]
sounds good!
