### ISSUE TITLE
bug: RC 2.0: Searchbar displays undefined

### ISSUE THREAD

**Issue by albrecht-jun-zhang** [driftyco/ionic#9062]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Searchbar displays "undefined" instead of "Search"</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
