### ISSUE TITLE
Ionic 2 could not use Pinch event

### ISSUE THREAD

**Issue by ngocnv371** [driftyco/ionic#9066]
I added

`(pinch)="onPinch($event)`

but the function never get called when running on android.

Did I miss any secret setting?

Your system information:

> Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.38
OS: Windows 8.1
Node Version: v6.6.0

**Comment by jgw96** [comment]
Hello, would you mind demonstrating your issue [here](http://plnkr.co/edit/GJte2b?p=preview) on this plunker? Thanks!

**Comment by ngocnv371** [comment]
Here's the code http://plnkr.co/edit/C7KlidriniQGo6XUlRl4?p=preview

I ran that preview on Android (browser) and it's not working. Also happen on android native.

**Comment by jgw96** [comment]
Hey @ngocnv371 would you mind taking a look at [these docs](https://github.com/driftyco/ionic-site/pull/893/commits/c067acd7e1ddc3ba5364c101ad91f463ac955c3e) and give that a try?

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! I am going to close this issue for now as a support question. Following the above linked docs will fix this for you.

**Comment by bibounet** [comment]
works great thanks!

**Comment by iliagerman** [comment]
Thanks!
The pinch event fires, any examples on how to implement it?
