### ISSUE TITLE
Feature request : UI Stepper

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#907]
Would be fantastic if you could build a stepper that could be themed with Ionic. 

https://developer.apple.com/library/ios/documentation/userexperience/conceptual/UIKitUICatalog/UIStepper.html

https://github.com/revolunet/angular-stepper

Thanks. Alex

**Comment by Kinzi** [comment]
I wrote a little directive for this. Nothing special but you can check it out here if you like: https://github.com/Kinzi/IonicStepperDirective
