### ISSUE TITLE
[Ionic 2] Tapping on disabled/readonly ion-input scrolls without showing the keyboard. Gif attached.

### ISSUE THREAD

**Issue by fuggfuggfugg** [driftyco/ionic#9070]
Not sure if this is a bug. 

#### Short description of the problem:

I have a profile page where fields are setup as readonly & disabled for now but will be editable in the future.

#### What behavior are you expecting?

Tapping on the disabled input fields adds scrolling. 
![bug](https://cloud.githubusercontent.com/assets/5616123/20064717/a847dc9a-a4d9-11e6-834b-40f8a00bf00b.gif)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Does this issue also happen on an Android device running the same app? Also, if you add this: 
```
IonicModule.forRoot(MyApp, {
      scrollAssist: false
}) ;
``` to your `app.module.ts` file does it still happen? Thanks!

**Comment by fuggfuggfugg** [comment]
Sorry for the late response. The scrollAssist seems to have done the trick on ionic view and emulator at least. I'll test on android and report back soon.

btw what is the difference between scrollAssist and autoFocusAssist?

**Comment by jgw96** [comment]
@adamdbradley just tested this with the scroll branch and it seems to still be an issue.

**Comment by j3gb3rt** [comment]
It doesn't seem that scrollAssist or autoFocusAssist are listed in the config API docs. Are these referred to somewhere else in the documentation?

**Comment by haydenJogs92** [comment]
Just updated to RC 5 - I have a readonly input and this issue is still present. Ion-scroll is adding margin-bottom to make room for the keyboard - but none appears.

**Comment by demonzoo** [comment]
@haydenJogs92 Same here! This is also a bug.
I tried to use a readonly input field and bind the (click) handler on it. When I tap the field on emulator, the screen gets scrolled a bit and nothing happens. I have to click a second time in order to trigger the click event.
I also tried disabled=true, it worked. But I don't want to gray out the text displayed in the input field. I think for now, I've got to set it as disabled and use extra CSS styles to change the text color.

**Comment by felix9607** [comment]
This seems to be still an issue, at least for me.
Adding this:

```
IonicModule.forRoot(MyApp, {
scrollAssist: false
}) ;
```
**Disables it for all Inputs, but I want this to happen only for "readonly".**




Ionic info:
```
    @ionic/cli-plugin-proxy : 1.4.12
    @ionic/cli-utils        : 1.13.0
    ionic (Ionic CLI)       : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : pro
```
