### ISSUE TITLE
Ionic doesn't install from npm

### ISSUE THREAD

**Issue by Ulfasaar** [driftyco/ionic#9073]
Hi I am a huge fan of ionic and use it all the time for building mobile apps as I don't own a Mac.

Recently I noticed that I couldn't update ionic so that I could use the newer version that utilised webpack instead of rollup. Due to the fact that the app-generator folder is not present in the npm repository. 

So I ended up uninstalling it and cleaning my npm cache and trying to reinstall it but again I had the same issue. Which means that I know can't use it.

I have also made sure to update my version of npm and node like I was told to in the issue that was created in the app-scripts repository however that fix did not work and the issue appears to have been closed prematurely despite the fact that other users seem to have a similar issue.

Am I just missing something obvious, or has this issue already been corrected? I just want to know so that I can continue using this awesome tool, thank you :)

**Comment by jgw96** [comment]
Hello, thanks for using ionic! Can you make sure that your package.json looks like [ours](https://github.com/driftyco/ionic2-app-base/blob/master/package.json)? Also could you post your apps repo here so that I can give it a test? Thanks!

**Comment by Ulfasaar** [comment]
This part seems to be the most obvious difference

 ` "dependencies": {
    "@ionic/storage": "^1.0.3",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0"
  }, ` 

and this 

` "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },`

also I do not have the private field within the package.json field set like you do 
and here is the link to the repository :) [https://gitlab.com/Ulfasaar/your-obliged](https://gitlab.com/Ulfasaar/your-obliged)

On a side note this problem does affect my global installation of the CLI as well, so that means that after I uninstalled it I can't install it again meaning that I can't build anything with ionic at the moment outside
of using the creator :(

**Comment by brandyscarney** [comment]
Hi @Ulfasaar! I'm not super familiar with Gitlab, so I could be missing it, but I'm not able to see any files there. Also, what issue did you report that got closed?

**Comment by Ulfasaar** [comment]
I'm terribly sorry about that I haven't done any open source stuff yet so I've never noticed that before  I'm sure you will be able to clone the repository though or if you prefer I can upload a zip file of it or put it on GitHub as well. The issue I mentioned was opened by another user. Heres the link to it :) https://github.com/driftyco/ionic-cli/issues/1416

**Comment by brandyscarney** [comment]
@Ulfasaar Hmm I don't see any options to clone that repository. Maybe it is set to private? Thanks for the issue!

Could you run the following commands in your project and paste the output here?

```
ionic info
npm -v
node -v
```

Thanks :)

**Comment by Ulfasaar** [comment]
Hey sorry about that Gitlab is very inconsistent between their mobile version and their desktop one. The mobile one says available to clone or something along those lines. If you are still interested in cloning it 
just run `git clone https://gitlab.com/Ulfasaar/your-obliged.git`  in the command line and it should work.

Here's the result of the commands you wanted me to try 

```
C:\Users\Ryan\Source\Repos\your-obliged\project>ionic info
'ionic' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ryan\Source\Repos\your-obliged\project>npm -v
3.10.9

C:\Users\Ryan\Source\Repos\your-obliged\project>node -v
v4.6.0

```

As you can see I do not currently have ionic installed and when I tried to install it I get this error message

```
C:\Users\Ryan\Source\Repos\your-obliged\project>npm install ionic -g
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ryan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 no such package available : @ionic/app-generators
npm ERR! 404
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ryan\Source\Repos\your-obliged\project\npm-debug.log

```

**Comment by Ulfasaar** [comment]
Oh gosh I am such a moron I just realized what the issue is. I have a caching server running on my laptop called Sinopia, which doesn't support scoped packages. 

So to solve my problem all I had to do was run
`npm config set @ionic:registry https://registry.npmjs.org/`

and then install ionic and it worked like a charm :)

**Comment by Ulfasaar** [comment]
Thank you all very much for your time :D and I hope you have a great day

**Comment by CodePoetPro** [comment]
I'm have the same problem, how can I solve it... 

Tried this npm config set @ionic:registry https://registry.npmjs.org/ 
but no luck

**Comment by Ulfasaar** [comment]
Hey CodePoetPro :) ,

Can you run ' npm get @ionic:registry ' for me and paste the result?

Also here's some other stuff you can try in the meantime

npm login --registry=https://registry.npmjs.org/
 --scope=@ionic

According to the docs https://docs.npmjs.com/misc/scope 
This should reset the registry of the packages scope to the public npm one after you logout and log back in to the npm client which you can do by running

npm logout 

Followed by ' npm adduser '

Checkout https://docs.npmjs.com/cli/logout if you want to read more info about the login system.

Also if you haven't already I would suggest swapping from Sinopia to Yarn because Sinopia is no longer being actively maintained whilst Yarn is being managed by Facebook if your just looking for something to cache your packages so you don't have to redownload them all the time :) like me. Also Yarn has a bunch of other extra goodies in it that are just awesome 

https://yarnpkg.com/

**Comment by borgespires** [comment]
I'm also battling with the same problem...
I ran ```npm get @ionic:registry``` and the output was ```https://registry.npmjs.org/```
I also tried the other commands but it kept outputting the same error.
