### ISSUE TITLE
ion-input clearInput Doesnot Work With formControlName

### ISSUE THREAD

**Issue by prantikv** [driftyco/ionic#9077]
#### Short description of the problem:
The clear input cross (X) does not show up `ion-input` when`formControlName` is added.

#### What behavior are you expecting?
To have the `clearInput` attribute to work along with model driven `formControlName`

This works
```
 <ion-input name="trakingNo" clearInput  type="text"></ion-input>
```
This Does not

```
 <ion-input name="trakingNo" clearInput formControlName="modelNo" type="text" ></ion-input>
```

**Which Ionic Version?** 1.x or 2.x
2..RC 2

**Comment by matejamateusz** [comment]
+ 1 the same problem. Any news @brandyscarney ?

**Comment by brandyscarney** [comment]
So it seems to behave this way with a `formControlName` or `ngModel`. I can see that when you enter a value from nothing (`'' -> 'val'`) it doesn't appear, but if you lose focus and then refocus the input the clear will show.

Created a PR for this here: https://github.com/driftyco/ionic/pull/10121
