### ISSUE TITLE
Feat: Allow sliding list in list dividers

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#9079]
The [Sliding List](http://ionicframework.com/docs/v2/components/#sliding-list) doesn't work into [List Dividers](http://ionicframework.com/docs/v2/components/#inset-list) as you see in the [plunkr](http://plnkr.co/edit/UY3HPOTexfztukgUE0ti?p=preview)

ionic v2 rc2

**Comment by brandyscarney** [comment]
Thanks for the issue! Sliding items currently require an `ion-list` as a parent element, per these docs: http://ionicframework.com/docs/v2/api/components/item/ItemSliding/. Are you proposing that they work in `ion-item-group`? 

cc @manucorporat

**Comment by JumBay** [comment]
Yes it would be great to be able to use the sliding feature with list divider.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#104
