### ISSUE TITLE
Inconsistent text color in multiline ion-item (ionic 2)

### ISSUE THREAD

**Issue by raae** [driftyco/ionic#9081]
#### Short description of the problem:
Paragraphs in multiline ion-items do not have the same text color as single line ion-items.

<img width="618" alt="cutepuppypics_-_ionic_app" src="https://cloud.githubusercontent.com/assets/478531/20114290/eed0caa8-a5f3-11e6-83b3-7d2bf7f1d4e3.png">

#### What behavior are you expecting?
I would like paragraphs in two line ion-items to have the same color as single line ion-items.

**Steps to reproduce:**
1. Create two ion-item with color="primary"
2. Make the first one single line
3. Make the second one multiline

```
    <ion-list padding-top padding-bottom">
      <button color="primary" ion-item no-lines detail-none>
        <ion-icon item-left name="snow" ></ion-icon>
        Line 1
      </button>
      <button color="primary" ion-item no-lines detail-none>
        <ion-icon item-left name="rainy" ></ion-icon>
        <h2>Header</h2>
        <p>Line 1</p>
        <p>Line 2</p>
      </button>
    </ion-list>
```

The paragraph color gets explicitly set in these scss files:
- https://github.com/driftyco/ionic/blob/master/src/components/item/item.wp.scss#L111
- https://github.com/driftyco/ionic/blob/master/src/components/item/item.md.scss#L106
- https://github.com/driftyco/ionic/blob/master/src/components/item/item.ios.scss#L96

**Which Ionic Version?** 2.x

**Comment by brandyscarney** [comment]
Thanks for the issue! This is somewhat related to https://github.com/driftyco/ionic/issues/8330. Currently you should be able to add a color and make it whatever color you'd like, but it doesn't work. Ideally I think we shouldn't be overriding colors of nested HTML elements, which would solve both issues, but it's up for discussion. :)

**Comment by brandyscarney** [comment]
Submitted a PR to fix this: https://github.com/driftyco/ionic/pull/9118

When it's merged I'll create a nightly release for you to try out and update the issue here. Thanks!

**Comment by brandyscarney** [comment]
This should be fixed now, I released a nightly version of the framework `ionic-angular@2.0.0-rc.2-201611110146`. Could you try it out and let me know if you find any issues? 

```
npm install --save ionic-angular@nightly
```

Thanks!

**Comment by raae** [comment]
I did not have time to test this, but the fix looks right when looking at the code. I will be needing this soon in my project and will test is then. Thanks for looking into it 👍
