### ISSUE TITLE
How to give x axis scroll in ionic segment

### ISSUE THREAD

**Issue by SAROSESAHOO** [driftyco/ionic#9085]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### What behavior are you expecting?

**Steps to reproduce:**
1. 
2. 
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/GJte2b?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
Thanks for the issue @SAROSESAHOO. Could you please fill out the issue content with more information?

**Comment by SAROSESAHOO** [comment]
Hi Brandyscarney,

                           I want to make dynamic segment as per the data coming from the api.But when the no of segment is more it wrap the text its not scrollable automatically below is my used code


   <ion-row style="background:#9DA3BC;padding:12px;" >
                          <ion-segment style="background:#8C93B1;" [(ngModel)]="tripTotalInformationSectorwise"  >
                             <ion-segment-button [value] = i  padding-right style="white-space: normal;"  *ngFor = "let legs of item.srdata.Legs; let i =index;">
                                  <ion-badge item-right>{{i + 1}}</ion-badge> 
                                  <sup><ion-badge item-right style="padding: 3px 4px;margin: 9px -2px 9px 0;font-size: 7px;background:#C64C63;">1</ion-badge></sup>
                                   {{legs.sector}}
                                   
                                </ion-segment-button>
                                 
                          </ion-segment>
                      </ion-row>

**Comment by SAROSESAHOO** [comment]
Hi Brandyscarney,
                            
                             i want to make dynamic segment as per the data coming from the api. But when the no of segment is more its wrap the text even i tried for the ionic scroll x-axis its not working below is my code

`   <ion-row style="background:#9DA3BC;padding:12px;" >
                          <ion-segment style="background:#8C93B1;" [(ngModel)]="tripTotalInformationSectorwise"  >
                             <ion-segment-button [value] = i  padding-right style="white-space: normal;"  *ngFor = "let legs of item.srdata.Legs; let i =index;">
                                  <ion-badge item-right>{{i + 1}}</ion-badge> 
                                  <sup><ion-badge item-right style="padding: 3px 4px;margin: 9px -2px 9px 0;font-size: 7px;background:#C64C63;">1</ion-badge></sup>
                                   {{legs.sector}}
                                   
                                </ion-segment-button>
                                 
                          </ion-segment>
                      </ion-row>`

**Comment by SAROSESAHOO** [comment]
>    <ion-row style="background:#9DA3BC;padding:12px;" >
                          <ion-segment style="background:#8C93B1;" [(ngModel)]="tripTotalInformationSectorwise"  >
                             <ion-segment-button [value] = i  padding-right style="white-space: normal;"  *ngFor = "let legs of item.srdata.Legs; let i =index;">
                                  <ion-badge item-right>{{i + 1}}</ion-badge> 
                                  <sup><ion-badge item-right style="padding: 3px 4px;margin: 9px -2px 9px 0;font-size: 7px;background:#C64C63;">1</ion-badge></sup>
                                   {{legs.sector}}
                                   
                                </ion-segment-button>
                                 
                          </ion-segment>
                      </ion-row>

**Comment by SAROSESAHOO** [comment]
Hi Brandyscarney,

                         i want to make dynamic segment as per the data coming from the api. But when the no of segment is more its wrap the text even i tried for the ionic scroll x-axis its not working below is my code
` <div  *ngSwitchCase="'Sectorwise'" >
                      <ion-row style="background:#9DA3BC;padding:12px;" >
                          <ion-segment style="background:#8C93B1;" [(ngModel)]="tripTotalInformationSectorwise"  >
                             <ion-segment-button [value] = i  padding-right style="white-space: normal;"  *ngFor = "let legs of item.srdata.Legs; let i =index;">
                                  <ion-badge item-right>{{i + 1}}</ion-badge> 
                                  <sup><ion-badge item-right style="padding: 3px 4px;margin: 9px -2px 9px 0;font-size: 7px;background:#C64C63;">1</ion-badge></sup>
                                   {{legs.sector}}
                                </ion-segment-button>
                          </ion-segment>
                      </ion-row>
</div>`

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
