### ISSUE TITLE
Wrong regex to get body class in 010_add_platform_class hook

### ISSUE THREAD

**Issue by MikelArnaiz** [driftyco/ionic#9088]
#### Short description of the problem:

I wanted to add ui-router current view as a class to the body.
If you add a variable with a filter in class attribute in body tag, then the hook that adds platform class works wrong.

**Steps to reproduce:**
1. Add a variable into class attribute:
`<body ng-app="myApp" class="some-class view-{{$root.$state.current.name | dotToDash}} ">
`

2. Run `ionic prepare`
3. Check code in (e.g Android ) `/platforms/android/assets/www/index.html`
`<body ng-app="myApp" class="some-class view-{{$root.$state.current.name  platform-android platform-cordova platform-webview| dotToDash}} ">`
4. You will notice `platform-android platform-cordova platform-webview` was added before the angular filter

Problem is the regex in `/hooks/after_prepare/010_add_platform_class.js`.

```
function findClassAttr(bodyTag) {
  // get the body tag's class attribute
  try{
    return bodyTag.match(/ class=["|'](.*?)["|']/gi)[0];
  }catch(e){}
}
```

Should be:
`return bodyTag.match(/ class=('|")(.*?)('|")/gi)[0];`

You can check both [wrong regex](https://regex101.com/r/zmlEMq/1) and [fixed regex](https://regex101.com/r/ZqtFqh/1).

**`ionic info`:** 
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by MikelArnaiz** [comment]
Added [pull request 1655 to ionic CLI](https://github.com/driftyco/ionic-cli/pull/1655)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#70
