### ISSUE TITLE
Ionic 2 with Windows 10: Refresher component in Ionic 2 RC2 doesn't work as expected if using touch.

### ISSUE THREAD

**Issue by DrTotenkopf** [driftyco/ionic#9090]
#### Short description of the problem:
In Windows 10 the Refresher component in Ionic 2 RC2 doesn't work as expected if using touch.

If you "pull to refresh" with the mouse everything works as expected but if you use the touchscreen to pull down the "bounce" effect is shown not the Refresher. 

You can see the behavior, when you open the example on https://ionicframework.com/docs/v2/api/components/refresher/Refresher/ in Internet Explorer or Edge. You can pull down with the mouse, but not with touch.

#### What behavior are you expecting?
Both mouse and touch are pulling down the Refresher component.

**Steps to reproduce:**

1. create Ionic 2 app with "ionic start -v2 testapp"
2. insert into the contact.html the code for the refresher in the ion-content tag:
```
    <ion-refresher>
        <ion-refresher-content pullingIcon="arrow-dropdown"
                               pullingText="Pull to sync"
                               refreshingSpinner="circles"
                               refreshingText="syncing..">
        </ion-refresher-content>
    </ion-refresher>
```
3. Build and deploy to Windows 10 
4. Use touch to pull down Refresher.

**Which Ionic Version?** Ionic 2 RC2

#### Plunker that shows an example of your issue
http://plnkr.co/edit/kuemvQN8ejS7qDBXBJO0?p=preview

#### ionic info:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: 
Node Version: v6.6.0

**Comment by bilalMlaik** [comment]
i solved this problem by using refreshingSpinner="crescent" in windows phone 10

**Comment by DrTotenkopf** [comment]
Hm, this didn't work for me...

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by HTeker** [comment]
Hi @jgw96 I have the same issue, is there a solution or workaround for this?
