### ISSUE TITLE
feat: Image source management - Image Placeholder

### ISSUE THREAD

**Issue by ungular** [driftyco/ionic#9091]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Mission:
Display an image from a remote server, if image is not found on server or you got a positive status code like(205, 206, 301, 307) but without image then display a default image.
with javascript, you can catch and treat such a case, if image not found:
`<img src="http://remote/image.png" onerror="javascript:this.src='default.png'"/>`

A response without image but with success code can be caught in a method but you should to make another call to remote server, it's to expensive when you need performance..

We need such a feature in ionic, which can ensure that we got the picture(based on status code, image size,..), taking in consideration the performance(imagine you have an autocomplete box that returns a list of images at each typed letter)

It intends to be an image placeholder, so we'll be able to write something like this:
`<ion-img placeholder="default.png" src="remote/image.png" />`
</span>

<span is-issue-template></span>

**Comment by ungular** [comment]
are cases when I receive blank images with status code 301, in this case I want to show default image.
my code:
`<img src="{{imageUtils.getImage(id)}}" onerror="javascript:this.src='default.png'"/>`
ts:   
`public static getImage(id) {
  return "http://remote/" + id  + ".png";
 }`

can you help me with a temporary solution for this case?

**Comment by bradrisse** [comment]
For a quick fix, when using <ion-img> it applies the class "img-loaded". Simply add some css and use the "img-placeholder" to attach a background url.

```
ion-img:not(.img-loaded) .img-placeholder {
     background: url('http://placehold.it/40x40') no-repeat;
}
```

**Comment by ungular** [comment]
I also need to show the default image when server returns a blank image with size 1px x 1px

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#77
