### ISSUE TITLE
how can I get cordova.plugins?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9100]
hi,
I try to use `cordova.plugins.GeTuiSdkPlugin`
with ionic2

there was an error can't find `cordova`

so could you please tell me how can I get `cordova.plugins`？

**Comment by niels1027** [comment]
Hi @yozman, have you looked at the repo of the plugin (see link below)? Maybe you will find you answer there. 

https://github.com/GetuiLaboratory/cordova-plugin-getuisdk

Also, have you tried the ionic forum (https://forum.ionicframework.com/) to get an answer? Better to start there with questions :-) 

Good luck !

**Comment by yozman** [comment]
thanks, finally I get the answer myself

it's the level of typescript

I add some code like
`declare var cordova`
