### ISSUE TITLE
docs: Platform specific custom styles

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#9106]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm unable to find documentation by looking at https://ionicframework.com/docs/v2/theming/platform-specific-styles/ how to specify custom style for each platform. There is section of "Overriding the Mode Styles" but it only seems to apply to out of the box component styles. Previously (before RC) it was possible to achieve this behavior via ".platform.scss" postfix such as page.ios.scss but with RC version it does not seem to work. And trying something like .ios .customStyleName { }  in main scss file does not seem to work either. So what is the proper way of defining platform specific custom styles?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#888
