### ISSUE TITLE
[feat] add clear input support to ion-textarea

### ISSUE THREAD

**Issue by aperezbaena-csc** [driftyco/ionic#9107]
#### Short description of the problem:
`ion-textarea` does not support `clearInput` attribute directive.

#### What behavior are you expecting?
Same behaviour as `ion-input`, display the clear button to clear up text area content. 

**Which Ionic Version?**
2.0.0 RC1

#### Plunker that shows an example of your issue
[This Plunker](http://plnkr.co/edit/4xOaFabIUlHzkzmmaIug?p=preview) shows that clear button is not displayed in a text area neither outside or inside an `ion-item`.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#109

**Comment by dlaynes** [comment]
Sorry for posting on a closed issue. Where is the new Feature Requests website?
Thanks for your response.
