### ISSUE TITLE
Ionic 2: available generators should be case correct

### ISSUE THREAD

**Issue by UncertaintyP** [driftyco/ionic#9125]
#### Just a minor issue with the generator

When listing the generators with

`ionic g --list`

the list should present case correct, _e.g._ lower case first letter, generators because the upper case generators fail with:

`Unknown Generator Type`

or extend the generator functionality to be case insensitive.

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v6.6.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1693
