### ISSUE TITLE
bug: Ion-img is drawn differently in ios ans android.

### ISSUE THREAD

**Issue by pbreuss** [driftyco/ionic#9126]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>When I run the app using "ionic serve --lab", an ion-img is displayed the same way in the android and ios browser image. (Correct), however on an ios device, the ion-img is streched according to the display size. On ios, I have to use the tags width and height to display the image correctly.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you using the `ion-img` component in `virtualScroll` or standalone?

**Comment by pbreuss** [comment]
Standalone. I am using ion-img just like in the documentation "background images".

http://ionicframework.com/docs/v2/components/#card-background

In ios, the image is streched onto the whole screen loosing the w/h ratio. Here is a screenshot. You need to supply width and height to have it displayed correctly on ios. On Android it works without width and height and in the browser emulator for both android and ios it works as well.
Philipp 


Von meinem iPhone gesendet

**Comment by jgw96** [comment]
Ahh, thanks for the info! So at this time `ion-img` is only meant to be used in `virtualScroll`. To achieve the the look of that card you should use the standard `img` tag that is used in the docs.
