### ISSUE TITLE
bug: <Ion-item no-lines> does not work on ios

### ISSUE THREAD

**Issue by pbreuss** [driftyco/ionic#9127]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description><ion-item no-lines>
</ion-item> Displays no line on Android (correct), but does not work on ios (on the device), but also in the --lab browser.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, would you mind posting a screenshot of the behavior you are seeing in iOS? Is it just simply showing lines when it shouldnt?

**Comment by pbreuss** [comment]
Hi,
Yea its showing lines in ios when in shouldnt. This happens even in the. Browser emulator.(--lab) for ios.
I can send you a screenshot.
Thank you for looking in it.
Philipp 

Von meinem iPhone gesendet

**Comment by brandyscarney** [comment]
Hey @pbreuss, I'm not able to reproduce this. Could you provide some of the code you're using or a small repository showing the issue? Also could you run `ionic info` from **within** your project folder and paste the output here?

**Comment by pbreuss** [comment]
Hello Brandy,
Thank you for returning to me regarding this issue: I tested it with RC3 and it does not happen anymore. Its apparently fixes and you can close this issue.
Thanks,
Philipp 

Von meinem iPhone gesendet
