### ISSUE TITLE
Receiving ERROR: Start Page at 'www/index.html' was not found -- after updating to RC2

### ISSUE THREAD

**Issue by axalon** [driftyco/ionic#9129]
Updated to RC2, did the following:

**ionic start testproject blank --v2**

followed by

**ionic build ios**

Opened the XCode project and ran it received:

**testproject[15720:3726809] ERROR: Start Page at 'www/index.html' was not found.
testproject[15720:3726809] ERROR Internal navigation rejected - <allow-navigation> not set for url='about:blank'**

Checked www folder, no index.html to be found. Was not an issue in RC1 and prior. Any ideas?

**Comment by ozexpert** [comment]
same thing happening. but building..

**Comment by axalon** [comment]
Ah, someone on the Ionic forums pointed out that it's from not having the latest version of Ionic CLI

Just had to do a **npm install -g ionic**

**Comment by MELAS007** [comment]
i use ionic version 2.1.1 and i got this:
Error: ENOENT: no such file or directory, open 'D:\Mobile apps\test\push2\www\index.html'

when i did this : ionic start push2 blank -v2

Any help please.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1675
