### ISSUE TITLE
ion-content continues to scroll while swiping side menu iOS RC1

### ISSUE THREAD

**Issue by jmordica** [driftyco/ionic#9130]
#### Short description of the problem:
In Ionic 2 RC1, when using `this.menu.swipeEnable(true);` on pages with ion-content, you should set the page to not allow scrolling because as the swipe is taking place, the content area continues to move. This has only been tested on iOS

**Steps to reproduce:**
1. Swipe to reveal the side menu
2. Move your thumb vertically (up and down while swiping to reveal the menu)
3. If you page has ion-content, you'll see the content scrolling

**Comment by jmordica** [comment]
I don't believe this issue was resolved. I do see it being tagged in RC3 but i've just updated and attempted the same behavior with the same results.

I see a few places in your commits that should have resolved this but didn't seem to do the trick. Here is an exact example of what is happening below:

![content_scroll](https://cloud.githubusercontent.com/assets/2974048/20615617/58b6fcee-b2a1-11e6-81d1-41cd85c145d6.gif)

Lastly, not sure if this has anything to do with it, but I have this in my app.module.ts which actually fixed a few keyboard/form overlapping issues

```
IonicModule.forRoot(MyApp, {
            platforms: {
                ios: {
                    scrollAssist: false,
                    autoFocusAssist: false
                }
            }
        }),
```
Hopefully this is enough info.

Thanks.

**Comment by biesbjerg** [comment]
As far as I know, this has been fixed when using WKWebView only. That comes with its own set of issues though.

**Comment by manucorporat** [comment]
This is already in RC3 using ionic's WKWebview plugin. There is not way to stop ongoing scrolling in UIWebView.

**Comment by jmordica** [comment]
I'm using the wkwebview plugin btw. Forgot to mention that. I set it up exactly like the ionic post recommended.

**Comment by manucorporat** [comment]
@jmordica have you updated to the latest version of the plugin?

**Comment by jmordica** [comment]
Yes but for some reason `cordova plugin list` shows:

`cordova-plugin-wkwebview-engine 1.1.1-dev "Cordova WKWebView Engine"`

Still trying to figure out why it's not showing your master branch data [here](https://github.com/driftyco/cordova-plugin-wkwebview-engine)

**Comment by jmordica** [comment]
Ok So i updated wkwebview and seemed to fix the issue! The content area no longer moves when dragging the side menu.

Case closed.
