### ISSUE TITLE
Nightly builds?

### ISSUE THREAD

**Issue by kodeine** [driftyco/ionic#9136]
Hello,
Is nightly build of ionic-angular updated? Or does often nightly updates? its been on `2.0.0-rc.2-201611110153` for few days. I wanted to get latest code from master tho.

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.2-201611110153
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.6.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. Good question! You are correct that we have not release a nightly in a few days. The best way to get the latest, bleeding edge, code is to use master. For instructions on that you can check out [this section](https://github.com/driftyco/ionic/blob/master/.github/CONTRIBUTING.md#setup) of our contributing doc. Thanks!
