### ISSUE TITLE
bug: multiple collection-repeat

### ISSUE THREAD

**Issue by GanuM** [driftyco/ionic#9137]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I have two arrays of items to be displayed on same screen iteratively,
i'm trying to achieve this by using collection-repeat but it is throwing error :

Uncaught RangeError: Maximum call stack size exceeded
RepeatController.scrollView.__callback

on console . This works fine with ng-repeat but i want to achive the speed so i'm trying to use collection-repeat. i also tried nesting the collection repeatd inside ion-scroll but didn't work , please help</span>

<span is-issue-template></span>

**Comment by GanuM** [comment]
Any updates on this issue @jgw96

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#69
