### ISSUE TITLE
Toast notifications are being shown in front of the bottom navigation tabbar

### ISSUE THREAD

**Issue by MvRemmerden** [driftyco/ionic#9141]
#### Short description of the problem:
If there is a bottom navigation in the app, bottom toast notifications are being displayed directly in front of the navigation.

#### What behavior are you expecting?
First, the toast notification has to move upwards behind the tabbar. Second, its final position has to be directly above the navigation (bottom: 70px for material design).

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 https://material.google.com/components/bottom-navigation.html#bottom-navigation-specs

**Which Ionic Version?** 
2.0 RC2

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#175
