### ISSUE TITLE
CameraPreview plugin update

### ISSUE THREAD

**Issue by trollwinner** [driftyco/ionic#9142]
Hello!

I have a little question about the camera preview plugin. There are some new features of the flash mode on github repo, but there is no in ionic2 now. Will it be updated sometime?

By the way, can I ask about CanvasCamera plugin? It's 404 in the docs and haven't work with ionic.

Thank you very much!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#793
