### ISSUE TITLE
iOS / android build error

### ISSUE THREAD

**Issue by Opelor** [driftyco/ionic#9144]
Hello team,

I'm getting this error when I try to build an ionic 2 app on iOS or android:

[14:28:22]  Error: Error at /Users/Opelor/ionic2app/.tmp/pages/home/home.ngfactory.ts:728:42 
[14:28:22]  Property 'openModal' does not exist on type 'HomePage'. 
[14:28:22]  ngc failed 
[14:28:22]  ionic-app-script task: "build" 
[14:28:22]  Error: Error 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1

I think that it has to be something about the AlertController.

Does anybody know how to fix it?

Thanks!

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually NGC pointing towards an error in your code. It looks like you have a property called `openModal` that is not declared on your `HomePage`. For help debugging your code further I would recommend checking out our [forum](https://forum.ionicframework.com).

**Comment by Opelor** [comment]
Yes, is true. I had an undefined click function on a component. Thanks for the help!
