### ISSUE TITLE
Statusbar and Ionic view problems

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#9145]
Hi there peeps,

I have some questions regarding the problems I have with the statusbar in Ionic View. First of all: everything works fine on the browser when I use Ionic Serve...

My biggest issue: the browser is not representative. Why am I saying that? Because you can't see a statusbar in the browser...

I can understand this (_cause a phone is not a desktop)_, but my actual problem starts when I am opening the application in Ionic View. There, the lay-out is not as it's in the browser, because a statusbar is being added. This adds like 10 or 20 pixels of a block where the status of the phone is being shown. This makes a mess of my nav-bar, because it overlaps it...

I tried fixing it by using this:

```
  ionic.Platform.ready(function() {
	  if (window.StatusBar) {
	    // org.apache.cordova.statusbar required
		    StatusBar.overlaysWebView(false); // or true, doesn't matter, still the same
		    StatusBar.backgroundColorByHexString('#ffffff');
	  }
	});
```

But the background color is not being applied...
Beside that, I just can't seem to fix the margin and padding issue I am having because of the statusbar...

I mean, is there a specific CSS I need to use for iOS to make it just like it is in my browser? **So to wrap it up, I have three issues:**

> 1) Statusbar not shown in the browser (this is a problem when you upload your app to Ionic View, because it is not the same anymore)
> 
> 2) The statusbar background color is not being applied
> 
> 3) Margin / Padding issue of the statusbar... how can I style it for iOS, while seeing that in my browser too? Or even hide it? Cause when I hide it, I still can see the bar... but without the text.

Can someone help me please?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#197
