### ISSUE TITLE
Improvement: Documentation for the "mode" option on components

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic#9147]
This is a request for an improvement, not a bug report.

Currently in the documentation for components it says:

mode  string  The mode to apply to this component.

Could you add a list of the acceptable options for mode?  Otherwise how does a developer know what they should put here?  Most other options have a list of available values in the docs.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#887
