### ISSUE TITLE
Image not found in the files scss when ionic build

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#9148]
Hi, 
It seems that the images in the files scss are not found when  I run "ionic build ios". For example, for example, in a file .scss, I had: "background-image: url('assets/images/icones/new-post.png')". I had always the message "GET http://localhost:8100/build/assets/images/icones/new-post.png 404 (Not Found)". 
Can anyone help me please?

**Comment by tienne** [comment]
"background-image: url('assets/images/icones/new-post.png')"
change it
"background-image: url('../assets/images/icones/new-post.png')"

**Comment by h2qutc** [comment]
Thanks a lot, it worked fine.
