### ISSUE TITLE
native scrolling in ionic2

### ISSUE THREAD

**Issue by BassamHabash** [driftyco/ionic#9149]
I'm build app using ionic2 , i'm using <ion-list> with virtual scrolling to display data in <ion-card>
the performance of scrolling in android device is good but , in IOS the performance is bad , i'm trying to use WKWebViw the performance better from using UIWebView but still bad and slow also not smooth , but when using virtual scrolling and fetch new data not just maybe 10 item just display in list from 100 item . ???

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are working on the VirtualScroll issues you are describing for the next couple of releases. Sorry that you are having an issue with them at the moment, but it will get much better soon 😃
