### ISSUE TITLE
$ionicLoading freezes user interaction for a while on iOS

### ISSUE THREAD

**Issue by Hypher** [driftyco/ionic#9154]
On iOS, after using $ionicLoading.hide() user interaction is disabled for a few seconds to up to a minute.

**Which Ionic Version?** 1.x or 2.x
ionic 1.3.1

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.2
Gulp local:  
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by Hypher** [comment]
Note that the interface seems freezed but I can programatically do whatever I want. It's just user interaction (touch, swipe...) that does not have any effect. Like if it would have been a layer on top or a pointer-events:none (but I found none of these using Safari remote debugger)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#68
