### ISSUE TITLE
alerts use wrong z-order if push page onto modal

### ISSUE THREAD

**Issue by arcbus** [driftyco/ionic#9158]
#### Short description of the problem:

I display a modal, gets a z-order of 9999, from here alerts also get z-order 9999, which seems to always work, though i'd expect them to get 10000. Now if i nav push a page, it gets z-order 10000 and subsequent pages increment from there. Now if i show an alert, it still gets 9999, and ends up behind my pages. 

#### What behavior are you expecting?

**Steps to reproduce:**
1. create and present a modal
2. create and present alert, note it has same z-order as modal (thinking it should already be incremented). Close alert
3. nav push a new page from the modal
4. create and present alert, note it shows up behind the new page

**Which Ionic Version?**
2.0.0-rc.2

#### Plunker that shows an example of your issue
Ionic2 sample plunker doesn't work, so didn't build a plunker demo.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Gulp version:  CLI version 3.9.1                                                                                                                                                                     
Gulp local:                                                                                                                                                                                          
Ionic Framework Version: 2.0.0-rc.2                                                                                                                                                                  
Ionic CLI Version: 2.1.0                                                                                                                                                                             
Ionic App Lib Version: 2.1.0-beta.1                                                                                                                                                                  
OS: Windows 7 SP1                                                                                                                                                                                    
Node Version: v4.2.1

**Comment by ghenry22** [comment]
same deal with actionsheets, popovers etc.

Probably not the best solution (using !important is not great) but I did the following:

edit the file below and just added an extra 9 onto the z-index for action-sheet, alert, popover and all looks rosy.  Have been playing with the app for a few days and there have been no side effects or oddness as you would always expect those elements to be on top of anything anyway and an action taken from inside one will usually close the component and then navigate if it needs to change pages so no issues there either.

/node_modules/ionic-angular/components/action-sheet/action-sheet.scss
```

ion-action-sheet { position: absolute; top: 0; left: 0; z-index: 99999 !important; display: block;
width: $action-sheet-width; height: $action-sheet-width; }
```

**Comment by agates** [comment]
Confirmed it's an issue here as well.

**Comment by manucorporat** [comment]
I think this was already fixed in next release
https://github.com/driftyco/ionic/pull/9180
