### ISSUE TITLE
Custom pager-icon class as attributes for slide-box

### ISSUE THREAD

**Issue by winkerVSbecks** [driftyco/ionic#916]
While using the slide-box I noticed that the pager icon is hard coded. My app design calls for hollow circles instead of filled ones. To solve this it would be nice to be able to pass it in as an attribute.

**Comment by mircobabini** [comment]
You can change the icons that way:

    .slider-pager-page:not(.active) i.icon:before {
	    content: "\f401";
    }

**Comment by GY22** [comment]
how to get a custom border color?
