### ISSUE TITLE
Keyboard hides textarea in footer

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic#9167]
Hello I am facing following issue.

I am creating chat application, where I have kept textarea at bottom in 
```
<footer>
```
When I click on textarea, it opes the keyboard, however content doesn't get resized, and hence it hides textarea behind keyboard.

Somewhat similar to 

http://stackoverflow.com/questions/34786098/ion-content-wont-resize-when-keyboard-appears

Please resolve this issue ASAP

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#67
