### ISSUE TITLE
page refreshing issue

### ISSUE THREAD

**Issue by Spanchal21** [driftyco/ionic#9168]
Hello friends,

please help me,

I am facing an issue of **page refreshment**, when i redirect to other page **using back button** at that time i could not see updated list (data), it mean i think my page would not refreshed.

**Comment by ghenry22** [comment]
you should check out the ionic forums, that's the best place to get some help.

**Comment by cleever** [comment]
I have a similar issue here.

In a tabs project. After selecting a page. The constructor load the list but the view doesn't refresh the page.
I need to select other view and go back to the first to get the page refreshed.

This pages used to work two weeks ago.

**Comment by Spanchal21** [comment]
hey friends,
given issue solved by following.

ionViewWillEnter() { ... }

**Comment by Spanchal21** [comment]
thanks for your support :)
