### ISSUE TITLE
ionic rc2 show nothing in qqbrowser on android,is it a bug?it is ok with rc1

### ISSUE THREAD

**Issue by wolfljj** [driftyco/ionic#9171]
ionic rc2 show nothing in qqbrowser on android,is it a bug?it is ok with rc1

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! qqbrowser is not one of our officially supported browsers at this time so unfortunately I am not going to be able to provide help at this time. I would recommend using Chrome or Firefox on your Android device. Thanks!

**Comment by wolfljj** [comment]
rc4 is ok.thanks
