### ISSUE TITLE
Persistent tabs

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#9172]
_From @flakerimi on November 11, 2016 15:21_

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
An option to Enable tabs always. Best way to check is when you go to account page, you have only side menu, and if side menu does not have pages that are tabs, you cant switch back to tabs ever. 

#### What behavior are you expecting?
Tabs should be treated as bottom menu and should stay there always, unless you want them go, I saw a lots of posts that they do .tabbar {display:none} which is not best but it works, si easy to hide but impossible to show them.

**Steps to reproduce:**
1. From TabsPage click Account Page
2. Tabs will disappear and you cant go back to tab page, if no other sidemenu item is tabpage 
  
**Other information:** 
https://forum.ionicframework.com/t/persistent-tabs/43579/4
https://forum.ionicframework.com/t/sidemenu-tabs-together/37738/22
 

_Copied from original issue: driftyco/ionic-conference-app#310_

**Comment by brandyscarney** [comment]
_From @flakerimi on November 11, 2016 19:50_

I was able to produce desired results by doing this: 

Added on tabs.html
` <ion-tab [root]="tab5Root"></ion-tab>
  <ion-tab [root]="tab6Root"></ion-tab>
  <ion-tab [root]="tab7Root"></ion-tab>
  <ion-tab [root]="tab8Root"></ion-tab>
  <ion-tab [root]="tab9Root"></ion-tab>
  <ion-tab [root]="tab10Root"></ion-tab>
  <ion-tab [root]="tab11Root"></ion-tab>
`
Then on scss

```
.tab-button {display: none;}
.tab-button.has-icon {display: block;}

```
Then on tabs.ts

`  tab5Root: any = DashboardPage;
  tab6Root: any = PhonePage;
  tab7Root: any = InvitationPage;
  tab8Root: any = SettingsPage;
  tab9Root: any = TermsPage;
  tab10Root: any = SupportPage;
  tab11Root: any = PrivacyPage;`


And finally on app.component.ts

`appPages: Page[] = [
    { title: 'Dashboard', component: TabsPage,  index: 4,icon: 'speedometer' },
    { title: 'Numrat e telefonit', component: TabsPage, index: 5, icon: 'ios-grid-outline' },
    { title: 'Ftesat', component: TabsPage, index: 6, icon: 'paper-plane' },
    { title: 'Settings', component: TabsPage, index: 7, icon: 'cog' },
    { title: 'Përkrahja', component: TabsPage, index: 8, icon: 'help-buoy' },
    { title: 'Kushtet dhe Afatet', component: TabsPage, index: 9, icon: 'paper' },
    { title: 'Privaciteti', component: TabsPage, index:10, icon: 'person' },
    { title: 'Logout', component: TabsPage, icon: 'log-out', logsOut: true }
  ];` 

IT IS very bad practice since its an app with 11 tabs. Crazy.

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#149
