### ISSUE TITLE
Ion-note IOS style issue 

### ISSUE THREAD

**Issue by cambronjay** [driftyco/ionic#9173]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### Short description of the problem:
IOS ion-note has the same style as Android now. 

#### What behavior are you expecting?
On IOS ion-note use to be a light gray color and a smaller font to represent a less important piece of content when in a row of buttons at the bottom of a card

**Steps to reproduce:**
1. Look at advanced card examples in ionic 2 documentation
2. IOS and Android have identical ion-note styles now
3. 

```
      <ion-note>
        11h ago
      </ion-note>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/GJte2b?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.4.0                                                                                                                                                                
Ionic Framework Version: 2.0.0-rc.2                                                                                                                                               
Ionic CLI Version: 2.1.4                                                                                                                                                          
Ionic App Lib Version: 2.1.2                                                                                                                                                      
Ionic App Scripts Version: 0.0.39                                                                                                                                                 
OS: Windows 7 SP1                                                                                                                                                                 
Node Version: v6.9.1

**Comment by manucorporat** [comment]
can you provide a screenshot?

**Comment by cambronjay** [comment]
![android](https://cloud.githubusercontent.com/assets/10892549/20350380/b67d403e-abdc-11e6-8c11-794a61285510.PNG)
![ios](https://cloud.githubusercontent.com/assets/10892549/20350379/b67a5112-abdc-11e6-8905-aa2391d6fc0f.PNG)
