### ISSUE TITLE
Create a Windows 10 application with Ionic RC 2

### ISSUE THREAD

**Issue by hoffmanjon** [driftyco/ionic#9174]
I posted this issue to the Ionic forums (https://forum.ionicframework.com/t/build-a-windows-10-app-with-ionic-2-rc/70139 ) but haven’t received a response so I am assuming it is a bug and not something that I did wrong.

I am trying to create an iOS, Android and Windows 10 app using Ionic 2 RC (version 2.1.8) however I am unable to get the app to run on a Windows 10 machine.  I know this issue also exists in version 2.1.7 but it was working properly in the beta versions of Ionic 2 (sorry I do not have the exact versions).

To recreate this issue, on a Windows 10 machine (I have Windows 10 build 1607) I run the following steps:

1. Create the APP: `ionic start test --v2`
2. Add Windows: `ionic platform add windows`
3. Add line to config.xml file: `<preference name="windows-target-version" value="10.0" />`
4. Attempt to run the app:  `ionic run windows`

I receive the following error:
```
Exception calling "ActivateApplication" with "4" argument(s): "The remote procedure call failed. (Exception from
HRESULT: 0x800706BE)"
At C:\Users\jhoffman\Documents\ionictest\test12\platforms\windows\cordova\lib\WindowsStoreAppUtils.ps1:164 char:5
```

If I take the windows-target-version line out of the config.xml file and build a windows 8 application, it runs fine so the issue is specific to the Windows 10 builds.

If I build the project with the `ionic build windows` command, the project does build fine and I am able to run the installer to install the application however when I attempt to run the application it immediately crashes.

Any help on this would be greatly appreciated.

**Comment by mhartington** [comment]
Please refer to the cordova windows documentation as this is not an issue with ionic

http://cordova.apache.org/docs/en/latest/guide/platforms/win8/index.html#project-configuration
