### ISSUE TITLE
Any callback function for when a segment is loaded?

### ISSUE THREAD

**Issue by ix-xerri** [driftyco/ionic#9175]
I am trying to load [google maps](http://www.joshmorony.com/creating-an-advanced-google-maps-component-in-ionic-2/) inside a segment. On page load it works because I have `ngOnInit(){
    this.loadGoogleMaps();
  }` I would like to know when the html of the segment has loaded so that every time I would load the map. Is that possible? Its a must that I know when the html has loaded so then I can load the google map.

**Comment by mhartington** [comment]
There is the `onSelect()` method that you can bind to.

http://ionicframework.com/docs/v2/api/components/segment/SegmentButton/#output-events

This is more of a question than issue with the framework. Might be better next time to go ask on the ionic forum, or join the ionic slack channel.


https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Comment by ix-xerri** [comment]
Agreed and thanks. I've tried onSelect and it gets called before the HTML loads. onSelect with $timeout?
