### ISSUE TITLE
enableBackdropDismiss	set to false does not work

### ISSUE THREAD

**Issue by cambronjay** [driftyco/ionic#9185]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

**Note: for Ionic-Native related issues you can open up an issues on the Ionic-Native repo**

https://github.com/driftyco/ionic-native

#### Short description of the problem:
enableBackdropDismiss	 set to false is meant to prevent the user from closing a modal, but it does not work. The modal is dismissed regardless of this option. 

#### What behavior are you expecting?
The modal should not dismiss or close when enableBackdropDismiss is set to false

**Steps to reproduce:**
1. Create an ionic project with a modal
2. Set enableBackdropDismiss to false
3. Ionic serve the project, open the modal, and then click on the backdrop.

```
 presentContactModal() {
   let contactModal = this.modalCtrl.create(ContactUsComponent,{enableBackdropDismiss: false});
   contactModal.present();
 }
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic version 2

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/GJte2b?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.4.0                                                                                                                                                                  
Ionic Framework Version: 2.0.0-rc.2                                                                                                                                                 
Ionic CLI Version: 2.1.4                                                                                                                                                            
Ionic App Lib Version: 2.1.2                                                                                                                                                        
Ionic App Scripts Version: 0.0.39                                                                                                                                                   
OS: Windows 7 SP1                                                                                                                                                                   
Node Version: v6.9.1

**Comment by manucorporat** [comment]
@cambronjay  you are using the API incorrectly, use this instead:
```ts
 presentContactModal() {
   let contactModal = this.modalCtrl.create(ContactUsComponent, null, {enableBackdropDismiss: false});
   contactModal.present();
 }
```

Note the second param is used for passing user-defined params

**Comment by cambronjay** [comment]
Does not work. Throws an error  of "Cannot set property 'component' of null"

**Comment by cambronjay** [comment]
If I take null out it still does not work. I can still click the back drop and dismiss the modal

**Comment by cambronjay** [comment]
Throws an error if you set it to null in rc2. This info should be put in the documentation.
