### ISSUE TITLE
touch-event gets recognized from two pages - BUG

### ISSUE THREAD

**Issue by Blackscr33n** [driftyco/ionic#9186]
#### Short description of the problem:
I got a simple ion-item elem with a click-event and this method pushes a 2nd page where a ion-toggle is at the same position as the link. When I click on the right corner of the ion-item( where the toggle elem is on the next page) the new page will be pushed and the toggle gets the active state.

#### What behavior are you expecting?
The Ion-Toggle shouldn't recognize the touch from the previous page

**Steps to reproduce:**
1. Start a new Project 
2. first page content:
in the Module just push the new page in the pushPage()-method
`<ion-searchbar id="searchbar" placeholder="Suchen" ></ion-searchbar>
  <ion-item class="filter-item" tappable (click)="pushPage()">
    choose a filter <ion-badge item-right>10</ion-badge>
    <ion-icon name="arrow-forward" item-right></ion-icon>`
3. 
Second page content:
`
<ion-list>
    <ion-list-header>
      Anwesend
    </ion-list-header>
    <ion-item>
      <ion-label>available</ion-label>
      <ion-toggle></ion-toggle>
    </ion-item>
</ion-list>
`
4. run it on a device or simulator
5. click on the icon or the right side

**Which Ionic Version?** 2.0.0-rc.2

#### Plunker that shows an example of your issue
Happens only on devices

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62  

![bildschirmfoto 2016-11-16 um 09 11 51](https://cloud.githubusercontent.com/assets/6410789/20353016/b75071c4-ac19-11e6-8a84-852763090338.png)
![bildschirmfoto 2016-11-16 um 09 12 42](https://cloud.githubusercontent.com/assets/6410789/20353017/b750e97e-ac19-11e6-99d9-9de7149c6ca4.png)

**Comment by jgw96** [comment]
Hello, unfortunately I cannot reproduce this issue at the moment. Could you create a plunker using the link in the issue template that I can use to reproduce this issue? Thanks!

**Comment by Blackscr33n** [comment]
@jgw96 here is the plunker => http://plnkr.co/edit/NtUtMBf7jGIZjvQcuRux?p=preview
PS: only on device

Greets!

**Comment by Blackscr33n** [comment]
seems to be fixed with RC3

**Comment by jgw96** [comment]
Awesome to hear! Thanks for using Ionic!
