### ISSUE TITLE
bower install ionic :  bower ECONFLICT    Unable to find suitable version for angular

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9188]
I'm trying to port ionic on top of meanjs..  Any suggestion would be very helpful. 

± bower install ionic
bower cached        https://github.com/driftyco/ionic.git#1.3.2
bower validate      1.3.2 against https://github.com/driftyco/ionic.git#*
bower cached        https://github.com/angular/bower-angular-sanitize.git#1.5.3
bower validate      1.5.3 against https://github.com/angular/bower-angular-sanitize.git#1.5.3
bower cached        https://github.com/angular/bower-angular-animate.git#1.5.3
bower validate      1.5.3 against https://github.com/angular/bower-angular-animate.git#1.5.3
bower cached        https://github.com/angular-ui/angular-ui-router-bower.git#0.2.13
bower validate      0.2.13 against https://github.com/angular-ui/angular-ui-router-bower.git#0.2.13
bower cached        https://github.com/angular/bower-angular.git#1.5.3
bower validate      1.5.3 against https://github.com/angular/bower-angular.git#1.5.3
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#~1.5.0
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#1.5.8
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#^1.0.8
bower cached        https://github.com/angular/bower-angular-animate.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular-animate.git#^1.4.8
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>1.2.0
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#^1.4.8
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#^1.4.0
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>=1.2.0 <1.6.0
bower ECONFLICT     Unable to find suitable version for angular

Here's my bower file. 
{
  "name": "meanjs",
  "description": "Fullstack JavaScript with MongoDB, Express, AngularJS, and Node.js.",
  "homepage": "http://meanjs.org/",
  "license": "MIT",
  "dependencies": {
    "angular": "~1.5.0",
    "angular-animate": "~1.5.0",
    "angular-bootstrap": "~1.2.1",
    "angular-messages": "~1.5.0",
    "angular-mocks": "~1.5.0",
    "angular-resource": "~1.5.0",
    "angular-ui-notification": "~0.2.0",
    "angular-ui-router": "~0.2.18",
    "bootstrap": "~3.3.6",
    "ng-file-upload": "^12.1.0",
    "ng-img-crop": "ngImgCrop#^0.3.2",
    "owasp-password-strength-test": "~1.3.0",
    "underscore": "^1.8.3",
    "angular-material": "^1.1.1",
    "angular-material-data-table": "^0.10.9",
    "material-design-icons": "^3.0.1",
    "angular-moment": "^1.0.0",
    "angular-aria": "^1.5.8"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/css/bootstrap-theme.css",
        "less/bootstrap.less"
      ]
    },
    "jquery": {
      "main": []
    }
  }
}

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by jpca999** [comment]
done
