### ISSUE TITLE
bower unable to find  ionic nightly   for V1

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9189]
![image](https://cloud.githubusercontent.com/assets/1026325/20359609/a8444176-abfe-11e6-928b-5a9a181810b1.png)

**Comment by dylanvdmerwe** [comment]
Is this for v1 or v2? For v2 you need to use `npm` :)

**Comment by jpca999** [comment]
for V1

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! We moved ionic 1 to the 1.x branch a few months ago when Ionic 2 became the master branch. Thanks!
