### ISSUE TITLE
bug(tappable): iOS delay on a button inside of an ion-col

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#9190]
#### Description of the problem:
There is a 300ms delay on a button on iOS. An `ion-button` should not experience the 300ms delay. Maybe something is capturing the event and it's bubbling to the button after the delay?

In the `button` and `ion-col` I have tried placing the `tappable` attribute, but on an iOS device there is still a 300ms delay. 

Not sure if the problem resides with the slide or grid?

```
    <ion-slides [options]="slideOptions" #caseStudySlides>
      <ion-slide *ngFor="let page of caseStudyGrid.pages">
        <ion-grid>
          <ion-row center *ngFor="let row of page">
            <ion-col *ngFor="let item of row" class='grid-column'>
              <button no-margin no-padding ion-button no-lines detail-none text-center class="item-button" *ngIf="item.thumbPath" (click)="launchCaseStudy(item.data)">
                    <async-image [src]='item.thumbPath' size="cover" class="item-thumb"></async-image>
                    <div class="label">
                      {{item.label}}
                    </div>
                  </button>
            </ion-col>
          </ion-row>
        </ion-grid>
      </ion-slide>
    </ion-slides>
```

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by dylanvdmerwe** [comment]
No wkwebview. Testing on iOS 10.

**Comment by adamdbradley** [comment]
What does the button HTML end up looking like after it's rendered to the DOM?

**Comment by dylanvdmerwe** [comment]
![image](https://cloud.githubusercontent.com/assets/2852839/20360792/c4ab5342-ac3d-11e6-941e-0a4776bc6ed1.png)

**Comment by dylanvdmerwe** [comment]
![image](https://cloud.githubusercontent.com/assets/2852839/20360925/5c2571f8-ac3e-11e6-95bc-f8f820720a5b.png)
