### ISSUE TITLE
Ionic2  schedule date-group problem !!

### ISSUE THREAD

**Issue by desireK** [driftyco/ionic#9191]
Hi everyone, i have a  big * problem to finsh my ionic2 application. indeed, i would like to apply an methodology  from an application that i very liked and then downloaded, but  the  schedule of  date in this  latter is  apply to an "set of group", like this:

     Data.json files==>

{

  "schedule": [
    {
      "date": "2018-05-20",
      "groups": [
        {
          "time": "8:00 am",
          "sessions": [
            {
              "name": “Starparade Events",
              "timeStart": "8:00 am",
              "timeEnd": "9:00 am",
              "location": “Abidjan",
            }
          ]
        },
        {
          "time": "9:00 am",
          "sessions": [
            {
              "name": “HeveaCulture Conference",
              "location": “Plateau",
              "timeStart": "9:00 am",
              "timeEnd": "9:30 pm",
            },
            {
              "name": “ trades seminar ",
              "location": “france"
              "timeStart": "9:30 am",
              "timeEnd": "9:45 pm",
            },
            {
              "name": “Accountancy Panel",
              "location": “libreville"
              "timeStart": "9:45 am",
              "timeEnd": "10:00 pm",
            }
          ]
        },
        {
          "time": "10:00 am",
          "sessions": [
            {
              "name": “how to understand climate change",
              "location": “california, USA"
              "timeStart": "10:00 am",
              "timeEnd": "10:15 pm",
            },
            {
              "name": “Conference: The evolution of humans”,
              "location": “South africa",
              "timeStart": "10:15 am",
              "timeEnd": "10:30 pm",
            },
            {
              "name": “Conference: Artificial intelligence",
              "location": “brésil",
              "timeStart": "10:30 am",
              "timeEnd": “3:00 pm",
            }
          ]
        },

            {
              "name": "Community Interaction",
              "location": “dublin",
              "timeStart": "11:30 am",
              "timeEnd": “2:50 pm",
            },
            {
              "name": “how to be efficient in cars business",
              "location": “chicago",
              "timeStart": "11:30 am",
              "timeEnd": “5:00 pm",
            }
          ]
        },
          ]
        }
      ]
    }
  ],

schedule.html file ==>(only the content part)

<ion-content>
  <ion-list #scheduleList [hidden]="shownSessions === 0">
    <ion-item-group *ngFor="let group of groups" [hidden]="group.hide">
      <ion-item-divider sticky>
        <div item-left>
          {{group.time}}
        </div>
        <div item-right>
          {{confDate}}
        </div>
      </ion-item-divider>
      <ion-item-sliding *ngFor="let session of group.sessions" #slidingItem [attr.track]="session.tracks[0] | lowercase" [hidden]="session.hide">
        <button ion-item (click)="goToSessionDetail(session)">
          <h3>{{session.name}}</h3>
          <p>
            {{session.timeStart}} &mdash;
            {{session.timeEnd}}:
            {{session.location}}
          </p>
        </button>
      </ion-item-sliding>
    </ion-item-group>
</ion-content>

What i want to do, is simply apply a different date for Each session in the Schedule part as you can see in the Data.json file* , i don’t want to group date to each session !! Since i thought that it was a little problem, i was wrong, i try many times to fix this issue but i failed until  now, So my last resort in the great communities that's here. 🏁I NEED YOUR HELP GUYS 🏁.

**PLEASE**

**Comment by rapropos** [comment]
Did you read the new issue template? Use [the forums](https://forum.ionicframework.com/) for support questions like this. Issues are for bugs in the framework itself, not help requests.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
