### ISSUE TITLE
Ionic2 how to use custom Cordova plugin

### ISSUE THREAD

**Issue by Gtanxingwen** [driftyco/ionic#9195]
1, I succeeded in adding my custom Cordova plugin
2，I                             declare var alipay: any                                              in my component;
but i use  it  console  alipay is not defind

**Comment by Gtanxingwen** [comment]
@brandyscarney

**Comment by graphefruit** [comment]
@Gtanxingwen 
if you declare it inside your component its treated as a variable and not a plugin.

have you tried to declare it outside the component?
`declare var alipay' ?

**Comment by Gtanxingwen** [comment]
@graphefruit  i try   also is 'is not defined'

**Comment by wbhob** [comment]
This is not the place for this, please put this in the forums and close this issue. This is just for Ionic issues, and this is just a question.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by wbhob** [comment]
I think it's a framework issue because i did everything correctly, so it's not a support issue.
