### ISSUE TITLE
the iOS ionic2 project can't integrate with cocoapods

### ISSUE THREAD

**Issue by fenghonghui89** [driftyco/ionic#9196]
#### Short description of the problem:

when integrate cocoapods, project can not build

#### What behavior are you expecting?

after integrate with cocoapods, the project can build and run

**Steps to reproduce:**
1. create a new ionic2 project:$ ionic start MyIonic2Project tutorial --v2
2. edit a few project setting to make it can run in iPhone device
3. cd /my project/platforms/ios ,run $ pod init, and add a Third Party for example 'AFNetworking'
4. run $ pod install
4. open projecet.xcworkspace, build, Xcode will show the error
```
cocoapods project profile:
target 'MyIonic2Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyIonic2Project
  pod 'AFNetworking'
end

xcode build error:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
cocoapods version: 1.1.1 

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v4.6.0
Xcode version: Xcode 8.1 Build version 8B62 

Thanks!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by expcapitaldev** [comment]
any updates with cocoapods support?

**Comment by HugoHeneault** [comment]
Anyone managed to make cocoapods work? Thanks!

**Comment by CHOMNANP** [comment]
I'm having the issue as well.

**Comment by rabernet** [comment]
cd platforms/ios

rm -rf Pods
rm -rf Podfile.lock
pod install

xcode

product-> clean 
product-> build o run


or

![xcofe](https://user-images.githubusercontent.com/1686901/30438561-20d1e712-9937-11e7-93a9-89f1291ef874.png)

**Comment by kierandesmond** [comment]
Hi All,

Having the same issue. I've tried "pod install" and "pod update"

Also tried the above solution. I had 4 errors, it was saying there is no .lock file.

Down to 2 errors now with the above solution:

diff: /Podfile.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Any ideas?

**Comment by matthew-valenti** [comment]
I'm currently looking for a better solution but this seems to resolve these errors:
https://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res

In XCode, click on the target project, select the "Build Phases" tab, open the "[CP] Check Pods Manifest.lock" option and replace the following code:

from:
diff "${PODS_ROOT}/../Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
to:
diff "${SRCROOT}/Podfile.lock" "${SRCROOT}/Pods/Manifest.lock" > /dev/null

**Comment by Heena-Vora** [comment]
@rabernet saved my life.!
