### ISSUE TITLE
app-scripts how to compile multiple scss to multiple dir

### ISSUE THREAD

**Issue by dragonahao** [driftyco/ionic#9202]
app-scripts how to compile multiple scss to multiple dir
1.I want to compile ionic v2 scss ( with ionic-components ) to a dir  
2.and I want to compile my component scss file to anthor dir 

3.I want to compile my component typescript files to a dir 

I try to create myself ./config/sass.config.js  file , but my component`s scss always compile together with ionic library 's scss

What should I do ?

**Comment by dragonahao** [comment]
main.css and main.js  is too bigger (fileSize > 6M),so i want to split package 
but i failed

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#432

**Comment by dragonahao** [comment]
Oh,oh,wasting 2 days ,Maybe I  reach it   by rewriting and compiling with  **webpack2@beta** ; The app-scripts is out of my controller and editing ./config/sth.config.js  is hard for me;  thanks for responsing me

**Comment by Sevenonclick** [comment]
Any solutions? I have the same issue, how to deal with the main.css too bigger problem
