### ISSUE TITLE
Alignment problem with custom font

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic#9210]
With custom font my text got cut-off on top.
The below image is the screen shot in android device. but it works perfectly in Chrome browser.

![cutoff](https://cloud.githubusercontent.com/assets/5066436/20401146/a1a37948-ad1d-11e6-970b-945a3d205249.png)

**Comment by mhartington** [comment]
Hey there! So this is more of a question for the forum or slack, and not an actual issue. 

Please ask there
https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
