### ISSUE TITLE
SASS Error since update to 2.0.0-rc.2 and app-script 0.0.45 

### ISSUE THREAD

**Issue by CarlRyds** [driftyco/ionic#9213]
#### Short description of the problem:

SASS Error since update to 2.0.0-rc.2 and app-script 0.0.45 

#### What behavior are you expecting?

To see my App

**Steps to reproduce:**
1. ionic serve --lab
 
**Which Ionic Version?**

2-RC2

**App Script Version?**

0.0.45

**Error output**

   Sass Error

    File to import not found or unreadable: ionic.globals Parent style sheet: /Users/Carl/CraftingCoach/src/theme/variables.scss

    src/theme/variables.scss
    // http://ionicframework.com/docs/v2/theming/
    @import "ionic.globals";

    Ionic Framework: 2.0.0-rc.2
    Ionic Native: 2.2.3
    Ionic App Scripts: 0.0.45
    Angular Core: 2.1.1
    Angular Compiler CLI: 2.1.1
    Node: 6.7.0
    OS Platform: macOS Sierra
    Navigator Platform: MacIntel
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#422
