### ISSUE TITLE
Item Reorder reports wrong indexes when dropped on original position

### ISSUE THREAD

**Issue by GITHuHo** [driftyco/ionic#9214]
#### Short description of the problem

Whenever an item to be reordered is dropped on its **original** position after having been moved over adjacent items the `ionItemReorder` event emits wrong indexes: 

```
{ from: <original-index> to: <original-index> - 1}  // if item has been moved upwards
{ from: <original-index> to: <original-index> + 1}  // if item has been moved downwards
```

#### What behavior are you expecting?

After dropping an item in its original position **no** `ionItemReorder` event should be triggered (or at least the from and to indexes reported should both equal the original position).

#### Steps to reproduce

The buggy behavior can be easily observed in any Ionic 2 app with an item reorder list, such as the one in the Ionic 2 documentation: http://ionicframework.com/docs/v2/api/components/item/ItemReorder/

#### Which Ionic 2 version are you using?

The issue occurs in Ionic 2.0.0-rc.3 and earlier versions (both with `ionic serve` and Cordova build apps).

Thanks for taking your time to review this issue.
Hubertus

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are tracking this issue [here](https://github.com/driftyco/ionic/issues/7522). Because of that I am going to close this issue as a duplicate. Thanks!

**Comment by FedericoAlvarez** [comment]
I'm having the same issue, any workaround?
