### ISSUE TITLE
im unable view content under router   :   'menuContent':   Do i need to do anything special 

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9216]
.state('app.search', {
    url: '/search',
    views: {
      'menuContent': {
        templateUrl: 'templates/search.html'
      }
    }
  })

im trying to port  ioinic onto my mean js  app.   is this thing  menuContent from some directive ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
