### ISSUE TITLE
Ionic Rc2/Rc3 pinch zoom

### ISSUE THREAD

**Issue by bolivir** [driftyco/ionic#9222]
Hi, 

I see many issues reported here with pinch to zoom on images etc. In the responses i read that they should be solved in beta 8,10,12 .
Currently im using ionic RC2 and im still not be able to perform a pinch zoom. Is there any way to perform a pinch zoom?

Im using the ion-slides component and would like to enable pinch zoom on images. If i look at swiper.io it should be possible to zoom, but within ionic 2 i dont find any way to do it.

Hope somebody can explain me how i can perform this, or at what version this should be possible.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us and sorry you are running into this issue. We are tracking this issue [here](https://github.com/driftyco/ionic/issues/5039). Please feel free to add any info you would like to that issue. Thanks for using Ionic!
