### ISSUE TITLE
page transition taked 1 second

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#9223]
I set pageTransitionDelay to 0, and test in android device with crosswalk.

![qq 20161118155440](https://cloud.githubusercontent.com/assets/1017740/20422793/754964cc-ada7-11e6-8ee9-b985d9a4f1ca.png)

--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.45
OS:
Node Version: v6.7.0

--------------------------------

**Comment by manucorporat** [comment]
I can't help you with a simple screenshot, can you export the profile so I can inspect it?

**Comment by izee** [comment]
@manucorporat 
[timeline.zip](https://github.com/driftyco/ionic/files/602530/timeline.zip)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
