### ISSUE TITLE
ion-input focus adds extra input element

### ISSUE THREAD

**Issue by muhammedbasilsk** [driftyco/ionic#9230]
#### Issue:
Double tap on the input makes the field bigger.
On a single tap also additional input is added. Is this intentional? On double tapping it breaks the design ,hence it is noticed. Please see the demo gif.

![ion-input-focus-height-issue](https://cloud.githubusercontent.com/assets/1559822/20428933/c762958a-adb1-11e6-998b-27315b7ce629.gif)

#### Expected behavior
Should keep the same size on focus (tap/ double tap).

**Steps to reproduce:**
1. Double tap on the input field
2. Height increase for a moment and get back to normal.

**Related issue:**
[Input going into 2 lines on focus on iOS](https://github.com/driftyco/ionic/issues/6667)
 

**Ionic Version:?** ionic 2
Got the issue in ionic-angular@2.0.0-rc.1, ionic-angular@2.0.0-rc.2 and ionic-angular@2.0.0-rc.3

#### Plunker that shows an example of your issue

**Issue can be reproduced in the webview, ios safari** -
Code: http://plnkr.co/edit/on6kex?p=preview
preview: http://run.plnkr.co/CYrfL2WHWkwfvXPg/

System information:
```
Cordova CLI: 6.4.0
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by divanvb** [comment]
Mine doing the same, anyone know a fix?

**Comment by muhammedbasilsk** [comment]
@brandyscarney were you able to reproduce this issue?

**Comment by coreymcmahon** [comment]
Also seeing this on iPhone 5/6.

**Comment by brandyscarney** [comment]
I haven't had a chance to look into this, but I believe this may be caused by the same issue as #7318

**Comment by brandyscarney** [comment]
This has also been fixed in the nightly version. Please try it out by running `npm install --save ionic-angular@nightly` and let me know if you still run into the issue!

**Comment by muhammedbasilsk** [comment]
Looks me fixed. Cool ! 
Thank you @brandyscarney 👍

**Comment by wojpat95** [comment]
In my case ion-input adds extra ion-input, any solutions ? Updating ionic-angular didn't help
