### ISSUE TITLE
Lifecycle events are not firing of child template in tabs

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#9231]
#### Short description of the problem:
Lifecycle events are not firing of child template in tabs. I created a `hello` template and added in one of the tabs root page. Lifecycle events of root page are firing but not of child template.

#### What behavior are you expecting?
Lifecycle events of child template should fire

**Steps to reproduce:**
I created new ionic2-app-base project and added this minimal commit https://github.com/aggarwalankush/ionic2-issues/commit/a9489e2026f165230cb3c9eb81f0b5980c279c06

<img width="1435" alt="screenshot 2016-11-18 18 38 43" src="https://cloud.githubusercontent.com/assets/8744282/20431472/2266dee2-adc0-11e6-8ef5-6e149f49097b.png">

**Which Ionic Version?** 1.x or 2.x
Ionic 2 rc3

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8T61a

**Comment by manucorporat** [comment]
hello is not a page, so it does not receive page lifecycle events. That's the expected behaviour.

You could inject ViewController, and subscribe to lifecycle observers:
http://ionicframework.com/docs/v2/api/navigation/ViewController/#instance-members

**Comment by aggarwalankush** [comment]
@manucorporat Agree, but instead of having a child template in tab root page, if I push a page having child template, then lifecycle events of child template also executes. 

`this.navCtrl.push(PageHavingHelloChildTemplate)` will fire hello template lifecycle. if hello is not a page, then this also should not happen.

**Comment by manucorporat** [comment]
I am not sure if I understand, sorry
```
this.navCtrl.push(PageHavingHelloChildTemplate)
```

^in this case, you are pushing another angular 2 component as an ionic page so It will receive the lifecycle.
