### ISSUE TITLE
Feature: Start View at Bottom

### ISSUE THREAD

**Issue by jourdan-jobox** [driftyco/ionic#9237]
Hi everybody,

This feature would be extremely useful for a chat application, where the user should always see the most recent message first (i.e. the message that's rendered at the bottom of the page).

Currently, in order to workaround this, I have the following:

```js
ionViewWillEnter() {
    // Scroll down to last message while view is being loaded
    setTimeout(() => {
      this.content.scrollToBottom(0);
    });
}
```

This isn't a very good workaround though. Sometimes, the user still sees the slight scroll (or rather, since I put `0` in `scrollToBottom()`, the user sees a jump to the bottom of the page). 

Does anyone else have a better workaround at the moment?

**Comment by cleever** [comment]
There are a good project that do it for angular 1:

https://github.com/Luegg/angularjs-scroll-glue

And another for angular 2, but seems to be unmaintained:

https://github.com/dharness/angular2-scroll-glue

**Comment by marcelgoya** [comment]
Hi @jourdan-jobox 

I faced the same problem but I was able to solve it by displaying a placeholder view above the chat dialog until the view has finished loading the message items and until the scroll event has finished.

**Comment by astec** [comment]
Maybe you should use <ion-footer>?

http://ionicframework.com/docs/v2/components/#toolbar-buttons

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#82

**Comment by Manduro** [comment]
Good news: this feature will be added with PR #8099.
