### ISSUE TITLE
Feature: Keep Keyboard Open (iOS)

### ISSUE THREAD

**Issue by jourdan-jobox** [driftyco/ionic#9238]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

---

Hi everyone,

Another feature request from me (since I'm working on a chat feature in my application). It would be very helpful to have some type of ability to keep the Keyboard open when clicking outside of the Keyboard. 

Here's a GIF of what I'm talking about:

![chat-demo](https://cloud.githubusercontent.com/assets/20412296/20446660/acf259aa-ad8f-11e6-919b-aec04fba3174.gif)

As you can see, the Keyboard closes once I press the Send icon.

Maybe some type of API call on the Keyboard like `Keyboard.preventClose()` that I could call in a `(click)` event, or some type of configuration like `Keyboard.doNotClose(true)` when the page is initialized.

In the mean time, if anyone has come up with a workaround to keep the Keyboard open when clicking out of the Keyboard, feel free to share!

**Comment by jourdan-jobox** [comment]
@brandyscarney Hey! Sorry to ping, but I saw the following checkbox on issue #6228 for RC4:

```
Touching an area that is not an input dismisses the keyboard.
```

I was wondering if my issue is related to this? If so, looks like it's going to be in RC4, which I'm looking forward to! This is very useful for chat apps especially!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#83
