### ISSUE TITLE
ion-fab color in ion-fab-list not working

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic#9240]
_From @kovack on November 18, 2016 10:44_

 ion-fab buttons in ion-fab-list not colored in "calm" in latest 2.0.0-rc.3 

`<ion-fab right bottom>
		<button ion-fab color="calm"><ion-icon name="arrow-dropup"></ion-icon></button>
		<ion-fab-list side="top">
			<button ion-fab color="calm" (click)="loaddatafromwebservice()" ><ion-icon name="refresh"></ion-icon></button>
			<button ion-fab color="calm" (click)="openspwho()"><ion-icon name="person"></ion-icon></button>
		</ion-fab-list>
	</ion-fab>`

in variables.scss I have :

$colors: (
     calm:       #AF251C
);

_Copied from original issue: driftyco/ionic-cli#1689_

**Comment by manucorporat** [comment]
Already fixed!

**Comment by seiyria** [comment]
Will this fix go live in rc.4 then?

**Comment by manucorporat** [comment]
yes, and you can try already installing the nightly version:
```
npm install ionic-angular@nightly --save
```
