### ISSUE TITLE
ionic generate page shows error

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic#9245]
Ionic version : 2(update to latest version)
I'm submitting a bug report when i'm trying to create new page 
by this command
`ionic generate page LoginPage`
i get this error

> (node:2176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: This socket is closed

it just happen me when i just update ionic 2 to the latest version.

**Comment by john5db** [comment]
Hi it is working fine for me on windows 10, latest ionic.
Here is my ionic version info
``
$> ionic info

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.3.0
Xcode version: Not i
``
please uninstall ionic and reinstall ionic. 

run "ionic info" 
so you will get exact ionic version.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#459
