### ISSUE TITLE
Ionic build failed when using shared module .

### ISSUE THREAD

**Issue by macdasi** [driftyco/ionic#9246]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
I have an ionic2 app , and a Shared Module written in angular2 typescript , the shared module is simple one component . in my main app.module I've imported the shared module and ionic:serve wirks fine I can see the component . as I run ionic build android I get an error 
>[11:38:43]  Error: Unexpected value 'MyModule' imported by the module 'AppModule'
[11:38:43]  ngc failed
[11:38:43]  ionic-app-script task: "build"
[11:38:43]  Error: Error

**Expected behavior:**
Build should work fine 

**Steps to reproduce:**
Create an ionic 2 quick start project (project A) by running 
ionic start cutePuppyPics --v2
Create a separate angular2 shared module project - I've cloned 
https://github.com/driftyco/ionic-module-template
Install  it using npm install ionic-module-template in project A .
Import the module inside app.module , run npm run ionic:serve see it working , call ionic build android see it failing . 

**Other information:**
I've followed instructions of 
http://blog.angular-university.io/angular2-ngmodule/
And used 
https://github.com/driftyco/ionic-module-template
With changes that should support AOT

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You can take a look at our [module template](https://github.com/driftyco/ionic-module-template) to see how to make a module that is AOT compatible. Hopefully that helps!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
