### ISSUE TITLE
VirtualScroll indents first item of list

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic#9247]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using a simple list with virtual scroll, the first item gets indented by 16px.
This bug was already reported in #7059. This issue was closed as duplicate of #6961. In between #6961 seems to be fixed, but #7059 still persists. Even with RC3. 

The workaround I described back in July still works.

**Expected behavior:**
A list with virtual scroll should work also without the workaround.

**Steps to reproduce:**
see http://plnkr.co/ygcLgYZWmFrEHTL8tIpH

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v4.6.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by zakton5** [comment]
+1
