### ISSUE TITLE
Tap events doesn't work while content scrolling 

### ISSUE THREAD

**Issue by pivalig** [driftyco/ionic#9248]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[  ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When content is scrolling and click back button or side menu toggle nothing is happen 

**Expected behavior:**

Any clicks outside of content must be works as expected 
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
One of my pages has this code to implements sliding tabs
So then i scroll items in on of the slides i can click Back or MenuToggle buttons as well
<ion-content>
	<ion-slides class="vertical-scroll" #mySlider (ionDidChange)="onSlideChanged()">
		<ion-slide *ngFor="let child of childs">
			<products [group]="child" *ngIf="child.index != undefined && entityType == 'product'"></products>
		</ion-slide>
	</ion-slides>
	<ion-fab right bottom *ngIf=" entityType == 'branch'">
		<button (click)="showMap()" color="accent" ion-fab><ion-icon color="primarydark" name="pin" ></ion-icon></button>
	</ion-fab>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by biesbjerg** [comment]
Are you using wkwebview?

https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/79

**Comment by pivalig** [comment]
oh, yes :(

**Comment by manucorporat** [comment]
I think it is not a WK issue, but a framework one.

**Comment by pivalig** [comment]
I will check later today without WK and report here.
PS
Here is the app
https://itunes.apple.com/md/app/andys-pizza/id1171948070?mt=8

**Comment by pivalig** [comment]
yes, it works as expected when i removed WkWebView... so 	poorly!

**Comment by pivalig** [comment]
One of my pages has this code to implements sliding tabs
So then i scroll items in on of the slides i can click Back or MenuToggle buttons as well

<ion-content>
	<ion-slides class="vertical-scroll" #mySlider (ionDidChange)="onSlideChanged()">
		<ion-slide *ngFor="let child of childs">
			<products [group]="child" *ngIf="child.index != undefined && entityType == 'product'"></products>
	</ion-slides>
</ion-content>

**Comment by manucorporat** [comment]
I just verified this is already fixed in master!
