### ISSUE TITLE
Strange title issue in navigation when swiping back on ios

### ISSUE THREAD

**Issue by Defcon0** [driftyco/ionic#9249]
**Ionic version:**  (check one with "x")
[X] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It's a bit hard to describe so I made a [video](https://drive.google.com/file/d/0B4bH_zE8RVR7ZVhSeW1ENlNNcE0/view?usp=sharing) showing the issue. The problem appears when using the swiping back gesture on ios. I recorded the video on a real iphone. When navigating more than once the title of the nav bar isn't animated properly anymore.

When using the back button on the top left of the app, it works like a charm. Deactivating the swipe back gesture isn't an option.

**Expected behavior:**
Correct animation behavior

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

```

**Comment by Defcon0** [comment]
Any news on that one?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind re-opening this issue on this repo https://github.com/driftyco/ionic-v1. We recently moved Ionic 1 (including all the Ionic 1 issues) to its own repo. My Github issue mover tool for some reason will not move this issue over to that repo so if you could just re-open this issue there that would be great. Sorry for the hassle!

**Comment by Defcon0** [comment]
No problem. Done: https://github.com/driftyco/ionic-v1/issues/199

**Comment by jgw96** [comment]
Thanks! Not sure why that tool would not move this issue, it moved all the others fine.
