### ISSUE TITLE
Error running ionic serve v2 sample app

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#9253]
**Ionic version:**  (check one with "x")

[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

Just updated ionic, started v2 sample app
receiving
```
src\pages\tabs\tabs.ts:1Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of

 at Object.typescriptSourcemapLoaderMemory (\node_modules\@ionic\app-scripts\dist\webpack\typescript-sourcemap-loader-memory.js:21:34)
````

**Comment by tycho01** [comment]
A similar report [here](https://forum.ionicframework.com/t/uncaught-error-module-build-failed-in-webpack/69977) stated an `npm cache clean` then reinstall of ionic did it.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#460
