### ISSUE TITLE
cordova_not_available in NativeStorage

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#9254]
**Ionic version:**  (check one with "x")

[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report

it should mock and work in browser using ionic serve, however it does not.
```
polyfills.js:3 Unhandled Promise rejection: cordova_not_available ; Zone: angular ; Task: Promise.then ; Value: cordova_not_available
```
according to 
https://github.com/TheCocoaProject/cordova-plugin-nativestorage/issues/44
its not the plugins fault.

Any ideas?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#814
