### ISSUE TITLE
Application Error The connection to the server was unsuccessful

### ISSUE THREAD

**Issue by Giuan0** [driftyco/ionic#9256]
When I run my application on 'ionic serve' everything works, but when I testing my apk(https://ionicframework.com/docs/guide/publishing.html) on a smartphone, I'm getting this:

 "Application Error
The connection to the server was unsuccessful (file:///android_asset/www/index.html)"

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by infinnie** [comment]
Add
```xml
<preference name="loadUrlTimeoutValue" value="700000" />
```

in your config.xml file.

**Comment by Giuan0** [comment]
Thanks!

**Comment by almgwary** [comment]
1- Rename your index.html to “main.html”

2- Create a new “index.html” and put the following content into it:

```
<!doctype html>
<html>
  <head>
   <title>tittle</title>
   <script>
     window.location='./main.html';
   </script>
  <body>
  </body>
</html>
```
3- Rebuild your app! No more errors!

[source](http://stackoverflow.com/a/43395288/6786941)

**Comment by EmmanuelNocks** [comment]
here is my ionic info but still getting same problem

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.0
    Ionic Framework                 : ionic-angular 3.2.1

**Comment by GeoSaboti** [comment]
I had the same problem and solved it disabling my computer firewall

**Comment by GameAppsBD** [comment]
So I added manually the following tags in config.xml right at the beginning:

<allow-navigation href="*" />
<content src=“index.html” />
<content original-src=“index.html” />

it’s working.

**Comment by GameAppsBD** [comment]
So I added manually the following tags in config.xml right at the beginning:

<allow-navigation href="*" />
<content src=“index.html” />
<content original-src=“index.html” />

it’s working.

**Comment by GameAppsBD** [comment]
So I added manually the following tags in config.xml right at the beginning:

```
<allow-navigation href="*" />
<content src=“index.html” />
<content original-src=“index.html” />
```

it’s working.

**Comment by matedemorphy** [comment]
Nothing of tha works for me

**Comment by luanrodrigues** [comment]
same here =(

**Comment by orengbasha** [comment]
in www folder having index.html page and src folder having index.html page ok i change twopages rename as main.html and i add the <script>
     window.location='./main.html';
   </script>
and next i run in ionic serve --lab its not working for me.
its just showing hide message
can you please help me

**Comment by nabilzidane** [comment]
Hi guys. I had the same problem.
And the perfect solution for me was:
running the command with --prod.
`ionic cordova run android --prod`
or
`ionic cordova run android --prod`
Now it's work for me like a magic. I hope that will help you too

**Comment by srobins259** [comment]
Mine ended up being the firewall issue. Thanks @GeoSaboti!!!
