### ISSUE TITLE
ionic 2 build browser - chrome refresh problem

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic#9257]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

so if you build a page that have a list of dynamic data pulling from the backend, it work with ionic serve BUT after built for the browser, Chrome won't refresh the list automatically 

**Expected behavior:**

Chrome should refresh the list with two ways binding without switching the browser tabs

**Steps to reproduce:**
1. build a page wit ion-list
2. call any backend to grab a list of data dynamically 
3. show on the view
4. build for browser with ionic build browser
5. deploy it to any CDN
6. run the new deployed web app on the latest Chrome
7. you wont see the refresh unless you switch between browser tabs so I believe it's a refresh problem in chrome only because firefox works

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1710
