### ISSUE TITLE
Ionic 2 Windows mode looks fake

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#9258]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

1. The Windows back button is neither iOS nor MD style. It looks closer to an MD style than the iOS one Ionic uses.
1. Toggles should turn grey (\#666666) when focused.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic/issues/5705.

**Comment by infinnie** [comment]
@jgw96 this issue covers content not covered in the issue referenced.
