### ISSUE TITLE
Adding ToastController button handler

### ISSUE THREAD

**Issue by MmtBkn** [driftyco/ionic#9259]
[x] **2.x**
[x] feature request

**Other information:**
Hi everyone,

I was going to add button to toast for recovery options. I saw that there is an option to add button, however it calls dismiss function. It would be nice to have some different function to handle click event of toast button.

I don't know If I'm clear, here is use case; There is a button which is sending message. User mistakenly clicked button, there is a toast message which is saying your message successfully sent, and there would be cancel button.

**Current behavior:**
ToastController: Calling onDidDismiss when duration ends or button(showCloseButton:true) click

**Expected behavior:**
ToastController: Having different handler than dismiss to button.

I think something like this would be great!

**Related code:**

```
presentToast() {
  let toast = this.toastCtrl.create({
    message: 'User was added successfully',
    duration: 3000,
    position: 'top'
  });

  toast.onDidDismiss(() => {
    console.log('Dismissed toast');
  });

  toast.onButtonClick(() => {
    console.log('Button click');
  });

  toast.present();
}
```

**Comment by harshabonthu** [comment]
With the current implementation we are differentiating as below

```
this._toast.onDidDismiss((data, role) => {
      console.log(data);
      this._onToastClose(role);
    });
```

if `role == 'close'` then the user clicked on button, else its dismiss based on timer.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#84
