### ISSUE TITLE
RC3 breaks ion-list-header border

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#9261]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.rc3**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On android, if you create a list with *ion-list-header*, you'll notice that the border is now set on top due to this [commit](https://github.com/driftyco/ionic/commit/9f7972b6fdb1460a86dfe01dad430db1d8693151#diff-a27b73f4250d704485640e7542374e1fL165) which breaks the vue as you can see on the [plunkr](http://plnkr.co/edit/wHCiVEXKgr2MZsRP8O7A?p=preview)

**Expected behavior:**
Set the border to the bottom as it used to be

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v5.11.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by laserus** [comment]
https://github.com/driftyco/ionic/issues/9234

**Comment by JumBay** [comment]
Didn't see that one, Thx
