### ISSUE TITLE
12 hour time period in DateTime Picker only available when format is "h:mm a"

### ISSUE THREAD

**Issue by MvRemmerden** [driftyco/ionic#9269]
**Ionic version:**
[x] **2.x**

**I'm submitting a ...** 
[x ] bug report

**Current behavior:**
When using a ion-datetime element, the 12 hour time period (am/pm or AM/PM) can only be used in the picker if the time includes only hours and minutes. As soon as another format is being used, (e.g. only the full hour "h a" or including the seconds "h:mm:ss a", the am/pm option will not be displayed.

**Expected behavior:**
Including the option to choose either am or pm for other formats than only hours and minutes.

**Comment by adamdbradley** [comment]
Cool, thanks for filing an issue! Should be fixed up now, thanks
