### ISSUE TITLE
Tabs don't working style color

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#9271]
_From @johndiego on November 15, 2016 19:29_

#### Short description of the problem:

tabs primary don't working in emulator just  in browser!

My code
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Transbordo } from '../../pages/transbordo/transbordo' ;
import { Volumes } from '../../pages/volumes/volumes';
import { Ocorrencias } from '../../pages/ocorrencias/ocorrencias';

@Component({
  selector: 'principal-transbordo',
  templateUrl: 'principal-transbordo.html'
})
export class PrincipalTransbordo {

  volumes = Volumes;
  ocorrencias = Ocorrencias;
  transbordo = Transbordo;

  constructor(public navCtrl: NavController) {}

  ionViewDidLoad() {

  }

}

```
####  my template
```
<ion-tabs [selectedIndex]="1" color="primary" >
  <ion-tab [root]="ocorrencias" tabTitle="Ocorrencias"></ion-tab>
  <ion-tab [root]="transbordo" tabTitle="Transbordo"></ion-tab>
  <ion-tab [root]="volumes" tabTitle="Volumes"></ion-tab>
</ion-tabs>

```
#### In my phone cel don't apply color primary,  How solved this?

![image](https://cloud.githubusercontent.com/assets/18476845/20320388/d7fd6434-ab58-11e6-9852-a0fdadea8ca3.png)

_Copied from original issue: driftyco/ionic-conference-app#315_

**Comment by pegaltier** [comment]
Same problem on my android device 4.4.2 but work fine on 6.0.1

**Comment by pegaltier** [comment]
During the page change transition the colors are displayed

**Comment by jgw96** [comment]
Hello @pegaltier is this still an issue with rc5? Do you have a repo I could use to reproduce this issue?

**Comment by pegaltier** [comment]
Hello @jgw96, I no longer have the problem with rc5. The problem is solved for me. Thank you.

**Comment by jgw96** [comment]
Thanks for using Ionic!
