### ISSUE TITLE
Duplicate request on http get/post

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#9273]
**Ionic version:**

[x ] **2.x**

**I'm submitting a
[x ] bug report

**Current behavior:**
When sending http requests 

```
 this.http.post('/api/myFormHandler/', this.form.value)
                .subscribe(
                (data) => {

});
```

The console shows, that the request is being sent twice. The initiator of the first request is shown as "polyfills.js:1" with size '378 B' and takes 5ms to complete.

Whereas for the second request the initiator is shown as "Other" with size "1.5 KB" and takes 2.97s to complete (this seems to be the actual request).

I put a break point on the my server side app to confirm this, but my server is hit only once.

This indicates that actually only one request is being sent to the server.

But on the client side, the console shows duplicate requests.

**Comment by ikhsan017** [comment]
maybe you could check if the first request is ```OPTIONS``` request, usually referred as pre-flight request on CORS before sending actual ```POST```, ```GET```, or ```PUT``` request

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
