### ISSUE TITLE
BackButtonText gone in nightly

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#9274]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There is no back button text in iOS mode in nightly anymore, when pushing a page - only an arrow.

**Expected behavior:**

Default text should be 'Back'

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201611211919
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by brandyscarney** [comment]
Confirmed this by running snapshot

<img width="1239" alt="screen shot 2016-11-22 at 11 41 42 am" src="https://cloud.githubusercontent.com/assets/6577830/20533117/70e0796a-b0aa-11e6-9fa6-b9b63d1198f8.png">

**Comment by manucorporat** [comment]
Fixed in nightly!
