### ISSUE TITLE
Error: “Cannot read property 'style' of null” when going back from a page with the hardware back button where opening the keyboard has triggered the page to scroll

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#9278]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If the page has to scroll to make the current form field visible when opening the keyboard, then when dismissing the keyboard and popping the page with the hardware back button, an error would be thrown that goes: “Cannot read property 'style' of null.”

**Expected behavior:**

No error would be thrown.

**Comment by Artfloriani** [comment]
Having the same error after updating to Ionic RC-3

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently making alot of improvements around input scrolling which should fix this issue. I am testing these changes as we speak and will update this issue with my findings.

**Comment by Manduro** [comment]
Related or same: #9310

**Comment by Manduro** [comment]
@adamdbradley Thanks! I'm not sure if this fixes all cases of this error though. I've logged the following ones:
```
TypeError: null is not an object (evaluating 'this._scroll.scrollToBottom')
File ".../main.js" line 4 col 29595 in scrollToBottom

TypeError: null is not an object (evaluating 'this._scrollEle.style')
File ".../main.js" line 4 col 29911 in setScrollElementStyle

TypeError: null is not an object (evaluating 'this._scrollEle.style')
File ".../main.js" line 4 col 30395 in addScrollPadding

TypeError: Cannot read property 'style' of null
File ".../main.js" line 15025 col 28 in Content.addScrollPadding

TypeError: Cannot read property 'style' of null
File ".../main.js" line 4 col 20082 in e.setScrollElementStyle

TypeError: null is not an object (evaluating 'this._scroll.scrollToBottom')
File ".../main.js" line 4 col 19766 in scrollToBottom
```

**Comment by juanpastas** [comment]
I am getting this in latest versions  as for Feb 5 2017.

The code that produces it:

```
this.nav.setPages([MyPage])
```

It does go to that page, but after a few seconds error appears.

Error happens when I go to that page:

camera -> a form with picked image -> mypage

But it does not happend when:

gallery -> a form with picked image -> mypage

Related to #9310.

**Comment by AltRoot17** [comment]
any one know how to fix this?

**Comment by mariohmol** [comment]
@AltRoot17  i'm experiencing this with ionic3 and Item reorder  ``` TypeError: Cannot read property 'style' of undefined
    at ItemReorder._reorderMove (http://localhost:8100/build/main.js:71606:33)
    at ItemReorderGesture.onDragMove (http://localhost:8100/build/main.js:166579:38) ```

**Comment by girishnair12345** [comment]
This is causing the app to hang when its loaded for this first time. Any fixes on this
