### ISSUE TITLE
How to allow for a camera to capture picture or record video 

### ISSUE THREAD

**Issue by BassamHabash** [driftyco/ionic#9280]
In Ionic 2 , i need plugins to allow for camera to take picture or record video , 
the existent plugins "Camera" or "Media Capture", the first not allow to record video , but the second plugin to take picture or video need single buttons for each function , 

now what i need one button to open a camera and from frame of a camera move between capture picture or record a video .

Thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
