### ISSUE TITLE
Unable to Build ionic project- BUILD FAILED

### ISSUE THREAD

**Issue by noumanrasheed** [driftyco/ionic#9283]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

 :processReleaseResources FAILED

BUILD FAILED
Total time: 1 mins 1.842 secs
Error: /Users/***/myapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/***/Library/Android/sdk/build-tools/25.0.0/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Expected behavior:**
BUILD SUCCESSFUL

**Steps to reproduce:**
cordova build android

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1709
