### ISSUE TITLE
About Ahead of Time Compiling in Ionic 2

### ISSUE THREAD

**Issue by Giuan0** [driftyco/ionic#9284]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

I'm using the latest version of Ionic, but my boot time still sucks, and its taking 15 seconds to boot an app size 8mb with just a few plugins... I read about the Ahead of Time (Aot) would be included in the latest version. That's my ionic info:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v7.1.0
Xcode version: Not installed

Why is my app taking so long to boot? Do i have to do something to use AoT on my project?

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#456
