### ISSUE TITLE
ngResource giving me issues..  am i loading it right ?   Never had this issue with usual angular ( new to Ionic 1 ) 

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9285]
![image](https://cloud.githubusercontent.com/assets/1026325/20527306/d042a50a-b095-11e6-9339-285731bf539c.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20524414/7b75d090-b088-11e6-97e7-5062d891a702.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20524442/9258fe22-b088-11e6-8b11-89d528a5be7e.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20524501/c798a90c-b088-11e6-8762-3f0ed09ceb70.png)

I ALSO TRIED CHANGING IT LIKE THIS  BUT STILL THE ERROR 

![image](https://cloud.githubusercontent.com/assets/1026325/20525849/58e709ac-b08f-11e6-9069-ac3bc00c8ca5.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20525880/7a273df8-b08f-11e6-8619-472d9654c4cc.png)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
