### ISSUE TITLE
$ionicLoading doesn't show on Android device

### ISSUE THREAD

**Issue by andres-vasquez** [driftyco/ionic#9286]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The first time that I show the dialog it works but the second time it doesn't.
The same code works on iOS.

**Expected behavior:**

Show the dialog.
Hide the dialog.
Show the dialog.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#66
