### ISSUE TITLE
The issue I am having is the input works in Ionic Serve but not in Ionic View app.

### ISSUE THREAD

**Issue by lionsfan60** [driftyco/ionic#9289]
**Ionic version:**  (check one with "x")
[ x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The issue I am having is the input works in Ionic Serve but not in Ionic View app. I wonder if this is a bug?

The process is select the edit icon on grid calls returnEdit with key field of list. ReturnSQLService.getReturnItem uses the key field to return the selected item from the list.

The iPad allows me to get focus in the field at the right of the number and shows the keyboard but you cannot input data. If I remove the ng-model="returnItem.ReturnQuantityPiece" the iPad allows input. Or if I change ng-model to a field that is not part of the returnItem object array. What could be causing this ?

**Expected behavior:**
Should be able edit inputs on the iPad

**Steps to reproduce:**

**Related code:**

Template:

<div>
<label class="item item-input" name="InputPieces">
<span class="input-label" ng-if="returnItem.PieceItemUnitID!=-1">Pieces</span>
<input type="tel" placeholder="Pieces" ng-model="returnItem.ReturnQuantityPiece" ng-if="returnItem.PieceItemUnit!=-1">
</label>
</div>

Controller:

.controller('returnEditCtrl', ['$scope', '$stateParams', 'ReturnSQLService', '$state', // The following is the constructor function for this page's controller. See https://docs.angularjs.org/guide/controller

// You can include any angular dependencies as parameters for this function

// TIP: Access Route Parameters for your page via $stateParams.parameterName

function ($scope, $stateParams, ReturnSQLService, $state) {

$state.params.TransactionID)

$scope.$on('$ionicView.beforeEnter', function (event, viewData) {

viewData.enableBack = true;

});

$scope.returnItem = ReturnSQLService.getReturnItem($stateParams.ItemID);

$scope.save = function () {

ReturnSQLService.upsertReturnItem($scope.returnItem.ReturnQuantityPiece, $scope.returnItem.ReturnQuantityPack, $scope.returnItem.ReturnQuantityCase, $scope.returnItem.ReturnQuantityPieceDamage, $scope.returnItem.ReturnQuantityPackDamage, $scope.returnItem.ReturnQuantityCaseDamage, $scope.returnItem.TransactionID, $scope.returnItem.ItemID, $scope.returnItem.BatchID)

$state.go('tabsController.return');

};

$scope.cancel = function () {

alert('Changes not saved!')

$state.go('tabsController.return');

};

}])

Service:
function getReturnItem(itemID) {
var returnItem;
if (items) {
for (var i = 0; i < items.length; i++) {
if (items.item(i).ItemID == itemID)
returnItem = items.item(i);
}
}
return returnItem;
}
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-view-issues#199
