### ISSUE TITLE
ion-infinite-scroll UX note

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic#9295]
We should review the design of this. Noticing a few flickers on the demos and the icon we use by default in this demo doesn't look quite right

<img width="222" alt="screenshot 2016-11-22 19 48 37" src="https://cloud.githubusercontent.com/assets/11214/20548859/ada66a34-b0ec-11e6-96e8-fb1612e396d7.png">

From: http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/

**Comment by brandyscarney** [comment]
Not able to reproduce this anymore. Will reopen if we see it again. :)
