### ISSUE TITLE
android back button problem

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9296]
I try to use tabs and side-menu together in v2,

this is my `app.component`
```html
    <ion-menu [content]="content" swipeEnabled="false">
      <side-menu [nav]="nav"></side-menu>
    </ion-menu>
    <ion-nav [root]="root" #content swipeBackEnabled="false"></ion-nav>
```

I set Root to `main`, and that's it
```html
<ion-header>

  <ion-navbar>

    <button ion-button menuToggle>菜单</button>

    <ion-title>Main</ion-title>

    <ion-buttons right>
      <button ion-button [navPush]="notice">公告</button>
    </ion-buttons>
  </ion-navbar>

</ion-header>

<ion-tabs>
  <ion-tab *ngFor="let page of pages" [root]="page.component" [tabTitle]="page.name" [tabBadge]="page.count"></ion-tab>
</ion-tabs>
```

In this case I have 2 tabs.
and push some page at side-menu

the problem is the `tabs` back `priority` is higher than `navCtrl.pop`,
so when I click `back button` It will change the `tab` at backgroud
not pop my new page

is it a Bug ?

if not, what should I do in my `registerBackButtonAction` callback?
could you please give me some advance or example?

**Comment by yozman** [comment]
or can I disabled the `tabs` change back?

**Comment by yozman** [comment]
I got an answer
changed function `isTabs` at `nav-util`
```javascript
export function isTabs(nav) {
    return false;
}
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind looking at our [ionic conference app demo](https://github.com/driftyco/ionic-conference-app) to see an example of how to use the sidemenu and tabs together?

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you believe this is an issue with the framework, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-17 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/6577830/22031268/2a64e022-dcae-11e6-9ca2-5511cf647efd.png">
