### ISSUE TITLE
bug: I am unable to install ngstorage using bower/npm

### ISSUE THREAD

**Issue by kdh2012** [driftyco/ionic#9297]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am creating a small shopping mobile app- I am trying to identify the best way to pass data to an "Add to Cart" function/ page. However I am only seeing results using Localstorage in the forums, BUT I am unable to install the component for ngstorage using bower. I receive the error- bash: bower command could not be found. 

 is there either a better way to pass this data when users are selecting items to add to cart OR is there something i can do to get ngstorage installed?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!

**Comment by kdh2012** [comment]
Ionic is beginning to become a problem- many functions of your websites do
not function. Such as the Contact Us Link, which does nothing now when
pressed. When chose from other browsers, it re-directs to Chrome and does
nothing. I'm not sure how a system can be successful if it does not provide
support, the fact that you guys seem to defer to a public forum for your
support is frankly not very good business practice and in my opinion leads
to mistrust. Additionally- there is no way to modify a review in the
marketplace, which is also problematic for those who would need to ammend
an accidental review due to a mis click.

I do not have much faith in your current framework and will not recommend
this to others in its current state.
