### ISSUE TITLE
Please add 'pinchend' event in $ionicGesture [Ionic 1.x]

### ISSUE THREAD

**Issue by Sky-Li** [driftyco/ionic#9299]
**Ionic version:1.x**

There are 'dragstart', 'dragend' event, but just no 'pinchend' event when pinch end.

Hope you can add it in $ionicGesture.

Or is there any way to trigger the function when pinch end for now?

 Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#65
