### ISSUE TITLE
Component is not part of any NgModule or the module has not been imported into your module

### ISSUE THREAD

**Issue by dimplast** [driftyco/ionic#9303]
**A) I make a simple custom Pipe**

@Pipe({name: 'grDate'})
export class GrDatePipe implements PipeTransform {
transform(date, format) {
return moment(date).format('LL');
}
}

**B) I import the pipe in @NgModule (file app.module.ts)**

import {GrDatePipe} from '../pipes/gr.date'

@NgModule({
declarations: [
.......
GrDatePipe
],

**C) implement the custom pipe (home.html)**

<ion-list *ngFor="let todo of todos | name: grDate">

**And i take the error:**
_**Component GrDatePipe is not part of any NgModule or the module has not been imported into your module**_

I run the same code in angular2 project (not ionic2) and everything is Ok but not in an ionic2 project.

**Comment by dimplast** [comment]
Sorry it's my false...!!!

**Comment by arung86** [comment]
@dimplast , I just encountered similar issue, what went wrong in your case, would you share the details?

**Comment by dimplast** [comment]
it did a silly mistake:
the false one: <ion-list *ngFor="let todo of todos | name: grDate">
the right one: <ion-list *ngFor="let todo of todos |  grDate">

**Comment by FieldMarshallVague** [comment]
Also our falsey. (sic)

Our problem was that we were using a variable to store declarations (which were also used for entrycomponents), since this was being copied into entryComponents unnecessarily, it was throwing this error (which was a shite error, tbh).

**Comment by aswinramakrish** [comment]
I saw this error when I added the pages in the `entryComponents` in `app.module.ts` and not in `declarations` (which was just above the entryComponents.
