### ISSUE TITLE
ion-input properties: whuch are possible values for 'mode' property?

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#9305]
I was reading Ionic 2 docs, in the [ion-input](https://ionicframework.com/docs/v2/api/components/input/Input/) is possible to set a 'mode' property which receives a string. But which are the possible values for this?

I looked in the [input specs from HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), there's no 'mode' attribute in input element.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#899
