### ISSUE TITLE
CORS issue : AngularJS POST Fails: Response for preflight has invalid HTTP status code 404

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9307]
Hello guys,  so I've 2 applications running on ec2.   

First one is mainly used for calling services upon ( using mongo, angular, express.js) 

Second one has the whole UI (Ionic ) and it calls the other one for the data.  It runs okay for http READ operation but when i try to run UPDATE on the server  it gives me this error. 

Can someone please help me how to resolve this CORS issue in IONIC app ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
