### ISSUE TITLE
FAB Lists do not work with Named Color Variables from theme/variables.scss RC.3

### ISSUE THREAD

**Issue by wrosb** [driftyco/ionic#9308]
**Ionic version:**  
[x] **2.x**

**I'm submitting a ...**  
[x] bug report
 
**Current behavior:**
I have custom colors into $colors: (). Then, i wan to use those colors into color's button property.

**Expected behavior:**
Buttons may get background color from variables.scss right?. But this in not happening. 

**Steps to reproduce:** 
Just add FabContainer into a blank new project and check Fab list's background color out.

**Related code:**

```
<ion-content> 
 <ion-fab bottom right >
   <button ion-fab>Share</button>
   <ion-fab-list side="top">
     <button ion-fab color="primary">Facebook</button>
     <button ion-fab color="myCustom">Twitter</button>
     <button ion-fab color="dark">Youtube</button>
   </ion-fab-list> 
</ion-content>
```

**Other information:**

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build...
```

**Comment by NicolasBoyer** [comment]
I have exactly the same comportment.
To avoid this i had to add custom css :
  `.fab-md.fab-in-list.fab-md-myCustom,
  .fab-ios.fab-in-list.fab-ios-myCustom,
  .fab-wp.fab-in-list.fab-wp-myCustom{
    color: #fff;
    background-color: #006978;
  }`
But before RC3, th use of the variables was sufficient.

**Comment by wrosb** [comment]
Indeed.
Fab lists work fine with RC.2

**Comment by manucorporat** [comment]
This was already already fixed, and new tests were added!
