### ISSUE TITLE
cordova plugins are not loaded when running the app on external device with --liverload flag

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic#9309]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

It seems like cordova plugins are not loaded when I run the app on an external device with the `--livereload` flag.

**Expected behavior:**

I'm not sure if this is intended behaviour, but if it is, it might not be the best idea to only load plugins when the app is run without the flag as I do not want to make requests to my production server when I am actually just testing the app (right now running without the liverload flag it will build for production).
It should load the cordova plugins whenever the app is run on a device.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by condorman** [comment]
+1 help!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#467
