### ISSUE TITLE
Is ionic.project same file as config.xml ?  I want to resolve the CORS issue. 

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9313]

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by jpca999** [comment]
what do you mean by Issue template ?    This question doesnt require an issue template..  Its a yes or no question.
