### ISSUE TITLE
how can I disabled menuClose animation?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9315]
could you tell me how to disable menuClose animation?

I just want menuOpen animation

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!
