### ISSUE TITLE
Ionic Platform - iPad Pro

### ISSUE THREAD

**Issue by axuscreative** [driftyco/ionic#9317]
Ran into a bug with Platform on an iPad Pro.

When returning `this.platform.platforms()` on an iPad Pro I get the following: ["cordova","mobile","ios","iphone"]

An iPad will return the following: ["cordova","mobile","ios","tablet","ipad"]

My current workaround is to get the Platform width and height to determine if it's tablet size.

Would be nice if we could get the iPad Pro to return the same as the iPad.

**Comment by dylanvdmerwe** [comment]
At the same time, an iPad Mini should be tested as well.

**Comment by jgw96** [comment]
Hello all! This has been fixed and is in the latest release (in fact, it was fixed a few releases ago). Thanks for using Ionic!
