### ISSUE TITLE
Header bar moves up behind statusbar or even completely out of the viewport when form field is focussed

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic#932]
Well.. that about sums it up ^

Screenshot (Ionic beta 1, iPhone 4):

![photo-1](https://cloud.githubusercontent.com/assets/220637/2540133/c17644be-b5cf-11e3-8628-ea65a1ace268.png)
![photo](https://cloud.githubusercontent.com/assets/220637/2540132/c1761098-b5cf-11e3-85b4-50d17a3c5924.png)

**Comment by rvanbaalen** [comment]
This was still an issue in the beta14 release. After some extensive debugging I finally found the fix.

In my case, it was related to my `meta viewport`.

Original value (causing the header to show behind the statusbar)

```html
<meta name="viewport" content="width=device-width">
```

New value (fixing this issue)
```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
```

I've started my project waaaay back before `beta1` so this was probably some legacy html I never noticed.

Hope this helps someone.

**Comment by ravivit9** [comment]
@rvanbaalen I have exact meta viewport in my index file but in my case when I focus input text element the body sits on top of the status bar resulting in hiding the status bar.  The status bar remains hidden after that even after keyboard slide down.

**Comment by mikehaas763** [comment]
This is still an issue for me. I do have the keyboard plugin added. I'm trying to use a simple textarea as a "notepad" so that it will fill the entire screen as you can see with my height: 100% styles. In order to get those styles to work I had to disable scroll with the scroll="false" because the height style will only expand to the height of the parent. There is probably a better way to make this "notepad" to avoid this issue and I'd appreciate any suggestions.

I've added a background color to the textarea to make the screenshots below more obvious.

I'm using this view:
```html
<ion-modal-view>
    <ion-header-bar class="bar-royal">
        <div class="buttons">
            <button class="button button-clear" ng-click="vm.closeAddNote()">Cancel</button>
        </div>
        <h1 class="title">Add Note</h1>
        <div class="buttons">
            <button class="button button-clear" ng-click="vm.saveNote(vm.noteContent)">Done</button>
        </div>
    </ion-header-bar>
    <ion-header-bar align-title="left" class="bar-subheader bar-stable">
        <h3 class="title">adding note for `client name`</h3>
    </ion-header-bar>
    <ion-content class="has-subheader" scroll="false">
        <div class="list padding" style="height: 100%;">
            <textarea placeholder="Comments" style="height: 100%; width: 100%;" ng-model="vm.noteContent"></textarea>
        </div>
    </ion-content>
</ion-modal-view>
```

Initial view
<img width="400px" src="https://cloud.githubusercontent.com/assets/2096573/7158764/24e5a7c0-e34b-11e4-9061-8342c4e9a05d.PNG" />

After clicking the text area
<img width="400px" src="https://cloud.githubusercontent.com/assets/2096573/7158766/2b5ad076-e34b-11e4-9736-a70423dba45b.PNG" />

Demonstrating that I can scroll while the text area has focus.
<img width="400px" src="https://cloud.githubusercontent.com/assets/2096573/7158780/4c2f2a68-e34b-11e4-9ec3-7fce41355946.PNG" />

**Comment by AshleyRudland** [comment]
Still an issue guys, please help @ajoslin @adamdbradley 

![ios simulator screen shot 25 may 2015 17 53 32](https://cloud.githubusercontent.com/assets/3226237/7800047/3e8c63ea-0307-11e5-87ec-08b49dce880f.png)

![ios simulator screen shot 25 may 2015 17 53 36](https://cloud.githubusercontent.com/assets/3226237/7800048/44841ba8-0307-11e5-8435-5984bcdc0f96.png)

iOS Simulator - iPhone 6 / iOS 8.3 
ionic version 1.0.0-rc.0
plugins installed: 
- com.ionic.keyboard
- com.phonegap.plugins.PushPlugins
- org.apache.cordova.console
- org.apache.cordova.device
- org.apache.cordova.file
- org.apache.cordova.geolocation
- org.apache.cordova.media

HTML from modal:
```
<ion-modal-view>
  <ion-header-bar>
    <div class="buttons">
      <ion-button class="button button-clear" ng-click="closeModal()">Cancel</ion-button>
    </div>
    <h1 class="title">Modal View</h1>
    <div class="buttons">
      <ion-button class="button button-clear" ng-click="create()">Create</ion-button>
    </div>
  </ion-header-bar>
  <ion-content>    
    <form>
...
</form>
</ion-content>
</ion-modal-view>
```

**Comment by LightZam** [comment]
@ravivit9 @mikehaas763 @AshleyRudland 
you should try

    iOS Notes
    If the content of your app (including the header) is being pushed up and out of view on input focus, 
    try setting cordova.plugins.Keyboard.disableScroll(true). 
    This does not disable scrolling in the Ionic scroll view, 
    rather it disables the native overflow scrolling that happens automatically as a result of focusing on inputs below the keyboard.

from [keyboard ios note](http://ionicframework.com/docs/api/page/keyboard/)

**Comment by michaelknoch** [comment]
can i set cordova.plugins.Keyboard.disableScroll(true) and still expect the view to scroll to my input?
If i disable scroll, the statusbar isn't pushed out anymore, but the keyboard overlaps my input field.

**Comment by tlancina** [comment]
@michaelknoch as long as your input is within a scroll view (like ion-content) it should automatically scroll into view, unless you have called `ionic.keyboard.disable()`.

**Comment by LightZam** [comment]
@michaelknoch i think you are asking [keyboard-attach](http://ionicframework.com/docs/api/directive/keyboardAttach/)

**Comment by michaelknoch** [comment]
@LightZam but it only supports ion-footer bar and my input is in inside my content in ion-view

@tlancina should i wrap my content with ionScroll? http://ionicframework.com/docs/api/directive/ionScroll/

**Comment by tlancina** [comment]
@michaelknoch you shouldn't need to, as `ion-content` has a scroll view already.  If you can create a simple codepen that reproduces the issue, along with what phone and OS you're using, as well as the output from the `ionic info` command (if you're using the CLI) I'll take a look.

**Comment by ituhin** [comment]
@tlancina I am facing this issue on 
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A176x
phone - iphone 4S, ios 7.0.6

if i keep "cordova.plugins.Keyboard.disableScroll(true)" header dont push out, but keyboard comes on top of my <textarea>. and i kept the textarea (using with msd-elastic) inside <ion-footer-bar>, to get a similar style like whatsapp, so its outside <ion-content>

any suggestions ?

tried with ionic.Platform.fullScreen() 
but no luck... also this fullScreen() creates another issue in ios...
it reduces the hight of the header... as this css dont get applied in fullscreen
 .platform-ios.platform-cordova:not(.fullscreen) .bar-header:not(.bar-subheader) {height: 64px; }

evrything was fine in andorid.

**Comment by ituhin** [comment]
@tlancina I am facing this issue on 
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A176x
phone - iphone 4S, ios 7.0.6

if i keep "cordova.plugins.Keyboard.disableScroll(true)" header dont push out, but keyboard comes on top of my <textarea>. and i kept the textarea (using with msd-elastic) inside <ion-footer-bar>, to get a similar style like whatsapp, so its outside <ion-content>

and if i use keyboard-attach then it screws up with msd-elastic :( 
any suggestions ?

tried with ionic.Platform.fullScreen() 
but no luck... also this fullScreen() creates another issue in ios...
it reduces the hight of the header... as this css dont get applied in fullscreen
 .platform-ios.platform-cordova:not(.fullscreen) .bar-header:not(.bar-subheader) {height: 64px; }

evrything was fine in andorid.

**Comment by ituhin** [comment]
@tlancina I am facing this issue on
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A176x
phone - iphone 4S, ios 7.0.6

if i keep "cordova.plugins.Keyboard.disableScroll(true)" header dont push out, but keyboard comes on top of my <textarea>. and i kept the textarea (using with msd-elastic) inside <ion-footer-bar>, to get a similar style like whatsapp, so its outside <ion-content>

and if i use keyboard-attach then it screws up with msd-elastic :( 
any suggestions ?

tried with ionic.Platform.fullScreen() 
but no luck... also this fullScreen() creates another issue in ios...
it reduces the hight of the header... as this css dont get applied in fullscreen
 .platform-ios.platform-cordova:not(.fullscreen) .bar-header:not(.bar-subheader) {height: 64px; }

evrything was fine in andorid.

**Comment by wang3g** [comment]
I am having the exactly same issue after upgrading Cordova to 6.0.0, namely, Header bar moves up behind statusbar when the virtual keyboard comes out. The problem appears on my android phone. I have not tried iOS device yet. Can anyone pls help?

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0-rc.5
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by freakyfriday** [comment]
I was having this problem on Android after upgrading to Cordova 6.0.0 and solved it by calling the AndroidFullScreen.immersiveMode method of the plugin https://github.com/mesmotronic/cordova-plugin-fullscreen

// Hide system UI and keep it hidden (Android 4.4+ only)
AndroidFullScreen.immersiveMode(successFunction, errorFunction);

**Comment by 17holeinone** [comment]
This problem is still happening, solving it by going full screen is not an appropriate solution since the app shouldn't really run on full screen, but just for the test I tried it, and while the app does go into fullscreen mode, it is still "larger" that the screen, therefore you can scroll it a little bit with the header going under the status bar ...
Please help!

**Comment by EricDeCoff** [comment]
Having this issue to? Is there a work around?

**Comment by pjhartin** [comment]
Also having the same issue with iOS in Ionic 2 

**Environment**
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.2.1 Build version 7C1002

As you can see there is not any room/padding between the status bar and the header in the Ionic app.

<img width="491" alt="screen shot 2016-03-21 at 11 17 49 am" src="https://cloud.githubusercontent.com/assets/1385026/13908441/97049bd2-ef56-11e5-9228-0b628a83a81d.png">

**Comment by rafaellop** [comment]
New/old issue with the keyboard is here again. While I can disable scrolling when input is focused by taping, the old issue with the header scrolling out of view is again present if focusing form fields with the virtual keyboard special button. On Android keyboard there's a green button at the bottom right that allows to switch to the next input in the form. Even if I've got scrolling turned off the button scrolls the view to make focused inputs visible and as the result the header is out of the screen. Do you have any ideas to turn off this button or fix the issue? I'm not 100% sure, but I suspect that this started after cordova upgrade to some 6+ version.

![view](https://cloud.githubusercontent.com/assets/8421184/17159145/6f477ef8-539b-11e6-9c9d-ad2fc5a39b4a.png)

Cordova 6.3.0
ionic-plugin-keyboard 2.2.1
Tested on device with Android 5
Build for Android 24.0.1

**Comment by alessandrogriggio** [comment]
@rafaellop Did you solve this issue?

**Comment by bobalazek** [comment]
+1

**Comment by hishammalik** [comment]
having this issue appear when file upload from Phone/Camera screen opens on iOS.

**Comment by solarsaturn9** [comment]
I'm having this issue with the email composer

**Comment by tikiwade** [comment]
This issue is still happening for me as well, this is not resolved.

**Comment by mobinius-shreesha** [comment]
In IOS,if we tap on statusbar whole ion-content will blinks in IONIC2.How to resolve this issue.Please suggest..
Thank You.

**Comment by newmediajosh** [comment]
Reverting back to cordova-ios@4.2.1 didn't help me, sad to say. Same problem after using native camera file library.

**Comment by DaleMatthews** [comment]
I had this issue with 

- ionic 3.9.2
- cordova-ios 4.4.0
- iOS 10.3
- Any iPhone device or emulator

I had a textarea with `height: 100%;` and the ion-header would zoom out of view whenever the textarea was focused. My fix was to change it to `height: auto; min-height: 25%;` and put the textarea inside a div with `height: 100%; margin: 0; padding: 0;` and `(click)=focusTextArea()`. Kinda janky and I'd love a better solution but this works ok for now :+1:

**Comment by sohandhaindwal** [comment]
Please use this plugin ionic cordova plugin add cordova-plugin-ionic-webview --save. Its solved my problem thanks

**Comment by jvhe123** [comment]
I experienced the same problem in combination with the email-composer plugin.

I solved the issue by upgrading the cordova-plugin-statusbar from version 2.2.1 to 2.3.0.

**Comment by glenr4** [comment]
@jvhe123  I just tried doing that but it looks like v2.3.0 does not exist, do you mean v2.2.3?

**Comment by jvhe123** [comment]
@glenr4 
![image](https://user-images.githubusercontent.com/21331193/32646695-0c644548-c5ee-11e7-847d-67a22c5196c2.png)

**Comment by cjbrunnen** [comment]
- cordova-plugin-keyboard 1.2.0
- ionic-plugin-keyboard 2.2.1

I was having this issue for the iPhone X. Opening the keyboard pushed the header up and almost off the page.

I fixed it by putting an eventListener in my javaScript file for the page affected:

`document.addEventListener('deviceready', function(e){
    window.addEventListener('native.keyboardshow', function () {
            cordova.plugins.Keyboard.disableScroll(true);
        });
  });`

This worked for me, hopefully it can work for one of you too.
