### ISSUE TITLE
[Request] Side-by-side layout while in landscape

### ISSUE THREAD

**Issue by mtycholaz** [driftyco/ionic#9321]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request 

I've hacked together my own side-by-side layout for ionic 2 (see the plunkr). You'll need to deploy to actual phone emulator/hardware to see it work. Would be great if we had a framework solution that would integrate with Ionic though.

https://forum.ionicframework.com/t/does-ionic-2-support-side-by-side-layout-in-landscape/67913/2
http://plnkr.co/edit/9uOTTtEBgW97mFojioqi?p=preview

**Comment by brandyscarney** [comment]
Thanks for the issue! I believe this is the same as https://github.com/driftyco/ionic/issues/6793 so I am going to close this as a duplicate, but let me know if I'm incorrect.
