### ISSUE TITLE
Modal incorrectly hidden under main view on Android

### ISSUE THREAD

**Issue by westonganger** [driftyco/ionic#9323]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On RC3 when opening modal on Android (browser emulation & device) I do not see anything. Its not frozen persay but pressing anything does nothing. It turns out to be a CSS problem in the framework, this is not part of my custom css. Removing this rule correctly shows the modal and it functions as it should.
```css
.md .modal-wrapper, .wp .modal-wrapper{
  opacity: .01; //remove this to correctly show the modal
}
```

**Expected behavior:**
Modal should show, not be hidden.

**Comment by westonganger** [comment]
This is also a problem with Windows too. IOS works correctly already.

**Comment by manucorporat** [comment]
can you provide some code that reproduces the issue?

**Comment by westonganger** [comment]
Just create any modal. Test it out in Ionic Lab, you will see IOS works correctly while Android and Windows results in hidden modal.

```javascript
this.modalCtrl.create(SomePage).present();
```

**Comment by manucorporat** [comment]
@jgw96 can you test this? I can't reproduce it

**Comment by jgw96** [comment]
Hello @westonganger , thanks for opening an issue with us! Unfortunately I cannot reproduce this on Android 4.4.4, Android 5.1.1, Android 6.0.1, Android 7.0. Which device and version of Android are you running into this issue on?

**Comment by westonganger** [comment]
It appears my `node_modules` was out of date and I was running rc2 (possibly even nightly) version.

**Comment by westonganger** [comment]
Scratch that its still a problem.

Ionic Lab Android and Windows views shows this problem. Also running on my Android 4.4.4 device showed the issue as well.

Heres a link to the project. https://github.com/westonganger/ionic_2_modal_issues

Run in with ionic lab and press the Add / Remove Players button. You will see its appears to be frozen in Android and Windows only, press the top right of the title bar to press the modal close button (also hidden) and now the app is "unfrozen" until you perform the same action.

You can see the app working correctly by adding this style.

```css
.md .modal-wrapper, .wp .modal-wrapper{
  opacity: 1;
}
```

**Comment by manucorporat** [comment]
ok, now I can reproduce, you didn't say anything about:
```
      modalEnter: 'modal-slide-in',
      modalLeave: 'modal-slide-out',
```

Working in a fix...

**Comment by manucorporat** [comment]
Fixed!
