### ISSUE TITLE
disable-scroll class not being removed

### ISSUE THREAD

**Issue by Iyashu5040** [driftyco/ionic#9330]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
 Sometimes the `disable-scroll` class is not removed from the `ion-app` causing the pages to become unresponsive. The only part that still works is the `ion-menu`.

**Expected behavior:**
The `disable-scroll` class should only be present when required.

**Steps to reproduce:**
This bug is difficult to reproduce. It happens very intermittently. If I find a consistent way to reproduce the bug I'll update the issue.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by pyr0hu** [comment]
👍 
I'm experiencing the same issue. If anyone found a workaround, please post it :)

**Comment by Iyashu5040** [comment]
I have a side menu in my app, which does not get disabled along with the rest of the app. So the user can still use the side menu to navigate between pages. In the side menu code I have placed code to remove that class on any page change, so if it's there it'll go away. The code I used to remove the class is:
````
let app = document.getElementsByTagName("ion-app")[0];
app.classList.remove("disable-scroll");
````

If you can find some place to put that code it will get rid of the class for you.

**Comment by manucorporat** [comment]
Are you using the ionic's WK plugin?
Can you guys try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by pyr0hu** [comment]
@manucorporat No, I'm not using the WK plugin. Installing nightly at the moment, will report back if anything changes.

**Comment by pyr0hu** [comment]
@manucorporat After installing nightly, I cannot run `ionic run ios` as the build process fails at the transpile stage.

**Comment by manucorporat** [comment]
@pyr0hu  can you open a new issue with the transpire error you are getting?

**Comment by pyr0hu** [comment]
@manucorporat I reverted to the stable version, then installed the nightly, and now it works again. After running the application it seems that the problem disappeared. I'll confirm this tomorrow after more testing.

**Comment by dylanvdmerwe** [comment]
As @Iyashu5040 said above, I experience this in my one client's app with a side menu. I am not sure how the `disable-scroll` gets added or why it does not get removed. 

I get around this by using the following: 
```
let app = document.getElementsByTagName("ion-app")[0];
app.classList.remove("disable-scroll");
```

So when the user changes to a new page, I ensure that `disable-scroll` is removed. Otherwise the app does not listen to any user interactions. 

@manucorporat I tried to use the latest nightly, but this break other things in my app so unfortunately not able to see if this is fixed or not. Not using WKWebView.

**Comment by peterpeterparker** [comment]
Is disable-scroll still a thing? 

I solve a non scrollable content like following:

https://github.com/driftyco/ionic/issues/10291
