### ISSUE TITLE
ion-scroll and collection-repeat not working in Android

### ISSUE THREAD

**Issue by avoidwork** [driftyco/ionic#9332]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The collection-repeat directive is not handling scrollable content correctly; in multiple cases I can't see all of the contents of the collection.

**Expected behavior:**
Able to scroll top to bottom and see every item in the collection.

**Steps to reproduce:**
This appears to be a known issue that's not getting proper support, see #5139.

**Related code:**
N/A

**Other information:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v4.6.2
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you be able to post some sample code we can use to reproduce this issue?

**Comment by avoidwork** [comment]
Hi,

No I cannot. However it should be easily reproduced by running an `collection-repeat` list within a flex box layout. In the app I'm producing there was 5 collection-repeat, and all of them have been reverted to `ng-repeat` because the issue is produceable across different UI layouts on Android devices. iOS doesn't have this issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#64
