### ISSUE TITLE
ionic-app-scripts build fails, ngc failed

### ISSUE THREAD

**Issue by Giuan0** [driftyco/ionic#9333]
I'm trying to build my project, but all I get is this output... And I declared the SettingsPage component on  app.module (declarations and entryComponents).

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**
It should build without errors.

**Steps to reproduce:**
ionic build android --release
For Ionic 1 issues - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

For Ionic 2 issues - http://plnkr.co/edit/GJte2b?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v7.1.0
Xcode version: Not installed

```
insert the output from ionic info here

[11:27:45]  ionic-app-scripts 0.0.45 
[11:27:45]  build prod started ... 
[11:27:45]  clean started ... 
[11:27:45]  clean finished in 9 ms 
[11:27:45]  copy started ... 
[11:27:45]  ngc started ... 
[11:27:46]  copy finished in 212 ms 
[11:27:58]  Error: Cannot determine the module for component SettingsPage! 
[11:27:58]  ngc failed 
[11:27:58]  ionic-app-script task: "build" 
[11:27:58]  Error: Error 

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "ionic:build" "--"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/giuan/Desktop/myApp/npm-debug.log

**Comment by trik** [comment]
@Giuan0 as a workaround, you can include SettingsPage in your app module declarations

```typescript
import { IonicModule, SettingsPage } from 'ionic-angular';

@NgModule({
   declarations: [
     SettingsPage,
     ...
   ],
   imports: [
     IonicModule,
     ...
   ],
   ...
})
export class MyAppModule { }
```

**Comment by Giuan0** [comment]
Thanks for the answer @trik! I already did put SettingsPages in the declarations array, SettingsPages is a custom component, why should I import it from 'ionic-angular'?

**Comment by trik** [comment]
@Giuan0 ok forget, it.. i thought it was a component from ionic-angular... i had similar issues with ionic components before.
make sure you included SettingsPage in your app module entryComponents

import { IonicModule } from 'ionic-angular';
import { SettingPage } from 'somewhere';

@NgModule({
   declarations: [
     SettingsPage,
     ...
   ],
   imports: [
     IonicModule,
     ...
   ],
   entryComponents: [
     SettingsPage,
     ..
   ]
   ...
})
export class MyAppModule { }

**Comment by Giuan0** [comment]
@trik, I have also done that already, when I run 'ionic serve' every thing goes alright, the problem is when i'm trying to build...

**Comment by rapropos** [comment]
This looks like more of a support forum issue than a bug to me.

**Comment by Giuan0** [comment]
@rapropos, I think it may be a bug, sense when I try to build with 'cordova build android --release' or run 'ionic serve' it goes alright with no errors. I used to build with cordova, but i need the ionic-app-scripts now for performance reasons, and I'm getting this.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to import a custom component in an Ionic 2 app I will urge that you ask this question on our forum (forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!

**Comment by Giuan0** [comment]
@jgw96 , I'm importing every custom components correctly, I can run 'ionic serve' and even build with 'cordova build android' or 'ionic-app-scripts build --dev', but just can't use 'ionic build android', and i need the AOT template compiling...

**Comment by mkuklis** [comment]
@Giuan0 could you please share your `app.module.ts` here?

**Comment by Giuan0** [comment]
@mkuklis, Its a private project, but i was trying to put the components one by one, and this is when I started to get this error: 

import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';

import { LoginPage } from '../pages/login-page/login-page';
import { RedefinePasswordPage } from '../pages/redefine-password/redefine-password';
import { HomePage } from '../pages/home/home';


import { Auth } from '../providers/auth';
import { API } from '../providers/api';
import { Storage } from '@ionic/storage';

@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2,
    LoginPage,
    RedefinePasswordPage,
    HomePage
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2,
    LoginPage,
    RedefinePasswordPage,
    HomePage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}, Auth, Storage, API]
})
export class AppModule {}

**Comment by mkuklis** [comment]
@Giuan0 this looks good. Is there any other place where you are importing `SettingsPage`? Could you share that too?
