### ISSUE TITLE
Right side menu doesn't close when going right, slow, and more than half (= simple to fix)

### ISSUE THREAD

**Issue by snarpch** [driftyco/ionic#9336]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you open the right side menu, and then slowly close it towards the right and more than half, the side menu snaps back to being open.

**Expected behavior:**
The right side menu should probably close in this case (at least the left side menu does, and when looking at the code it seems to be a bug...).

**Steps to reproduce:**
1. Open right side menu.
2. Slowly drag the side menu towards the right, and more than half.
3. Release side menu.

**Related code:**
The bug is here (sideMenuController.js, self.snapToRest(), line 264):

```
// Going right, more than half, too slow (snap back)
else if (ratio < 0.5 && direction == 'right' && velocityX < velocityThreshold) {
  self.openPercentage(-100);
}
```

It should probably instead be:

```
// Going right, more than half, too slow (snap back)
else if (ratio < -0.5 && direction == 'right' && velocityX < velocityThreshold) {
  self.openPercentage(-100);
}
```

(= you probably forgot to add the minus sign :-) ).

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.9.0 
ios-sim version: 5.0.3 
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! So this is actually expected behavior. If you try a native android app, such as the Google Play Store, the sidemenu will exhibit the same behavior.

**Comment by snarpch** [comment]
Hmm, no. The left side menu does behave the same as the left side menu in Google Play Store and works correctly, but the RIGHT side menu doesn't! (not that there is a right side menu in Google Play Store, but the behavior of the right side menu in Ionic is clearly different than the left side menu).

And even if the current behavior of the right side menu would be on purpose, the current source code wouldn't make much sense.

To clarify:
Our app currently has this setup:
```
<ion-side-menu-content edge-drag-threshold="true" drag-content="true">
  ...the main content...
</ion-side-menu-content>
<ion-side-menu side="left">
   ...
</ion-side-menu>
<ion-side-menu side="right">
   ...
</ion-side-menu>
```

If you look at sideMenuController.js (Ionic version 1.3.2), at line 230, there is the function called _snapToRest_ that is responsible for this behavior.

This function first gets the open ratio of the side menus:
`var ratio = self.getOpenRatio();`

ratio will be in a range from 0 (closed) to 1 (open) for the left side menu, and from 0 (closed) to -1 (open) for the right side menu.

Then follow the four checks for slowly dragging, where the bug is. Let's look at each one of them separately:

**1.**
```
// Going right, less than half, too slow (snap back)
if (ratio > 0 && ratio < 0.5 && direction == 'right' && velocityX < velocityThreshold) {
  self.openPercentage(0);
}
```
The range of ratio here is from 0 to 0.5, so only affects the left side menu. This checks if the **left** side menu was slowly dragged open, but less than half the screen. So the left side menu snaps close again.

**2.**
```
// Going left, more than half, too slow (snap back)
else if (ratio > 0.5 && direction == 'left' && velocityX < velocityThreshold) {
  self.openPercentage(100);
}
```
The range of ratio here is from 0.5 upwards, so also only affects the left side menu. This checks if the **left** side menu was open and slowly dragged towards the close state (direction == 'left') but is still open more than half the screen. So the the left side menu snaps open again.

**3.**
```
// Going left, less than half, too slow (snap back)
else if (ratio < 0 && ratio > -0.5 && direction == 'left' && velocityX < velocityThreshold) {
  self.openPercentage(0);
}
```
Now the same checks seem to be started for the right side menu. This is actually the mirror of Nr. 1, adjusted for the right side menu. The range is from 0 to -0.5, so this only affects the **right** side menu. This code checks if the right side menu was closed and slowly dragged towards the open state, but less than half the screen. If yes, closes the side menu.

**4.**
```
// Going right, more than half, too slow (snap back)
else if (ratio < 0.5 && direction == 'right' && velocityX < velocityThreshold) {
  self.openPercentage(-100);
}
```
So now we arrived at the problematic code. I would expect a mirror of Nr. 2 here for the right side menu, but it isn't. The affected ratio range is everything smaller than 0.5, so in theory would affect both the **left and right** side menu. But a ratio < 0.5 for the left side menu would have already exited at Nr. 1, because there is exactly the same check, but without the _ratio > 0_ check. So this is clearly wrong, even if the behavior was on purpose.

Now for the right side menu, the program will exit here always for slow drags and if it hasn't exited yet in Nr. 3, because this affects the full range (0 to -1) of the side menu ratios. That is why the right side menu jumps back to the open state even if it was almost closed with the drag.

If the right menu should have the exact mirrored behavior as the left side menu, you have to add a minus sign to the 0.5 (as stated above). And as the current 0.5 without the minus sign here doesn't make much sense, I assume this was the original intention anyways when it was originally written. So the correct code here should be:
```
// Going right, more than half, too slow (snap back)
else if (ratio < -0.5 && direction == 'right' && velocityX < velocityThreshold) {
  self.openPercentage(-100);
}
```

Sorry for my detailed description, just wanted to make sure that I was correctly understood :-).
Thanks!
