### ISSUE TITLE
NavController.canGoBack() doesn't function correctly when placed in a Page's Constructor

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic#9337]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Just place navCtrl.canGoBack() inside a page constructor and push to the page. It'll return false even if it should be true. I had to place it inside ionViewDidLoad { } to make it work correctly.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by manucorporat** [comment]
In the constructor the page has not been injected yet. So it return false, that's perfectly fine. Just use the correct API `ionViewDidLoad`

**Comment by davincif** [comment]
I suggest to reopen this issue (or open another). using _ionViewDidLoad_ may solve some problems but not in my case, I need to know if _canGoBack()_ every time the user comes to a certain page, so a placed this code inside _ionViewWillEnter_ and it also returns me a wrong state. It even says that a can go back when a can't, causing the application to crash.
