### ISSUE TITLE
Ionic 2 - toast dismiss animation blocking user interaction

### ISSUE THREAD

**Issue by UncertaintyP** [driftyco/ionic#9339]
**Ionic version:**  (check one with "x")
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
When the toast dismisses other components on the page and outside, _e.g._ the sidemenu, back button, etc., are not clickable.

**Expected behavior:**
The app should still be responsive.

**Steps to reproduce:**
On
http://ionicframework.com/docs/v2/components/#toast
click on a toast and while it disappears try to present another one by clicking the button. This behaviour is not restricted to creating toast but to clicking any component.

**Ionic info:**
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.6.0
Xcode version: Not installed

**Comment by manucorporat** [comment]
I understand how this is happening, but I wonder how it does affect your app. the animation is very short.

Can you comment what feels bad in your app?

**Comment by manucorporat** [comment]
@UncertaintyP  should be fixed in RC4!

**Comment by UncertaintyP** [comment]
Thank you very much @manucorporat 
I feel like unresponsive apps ( the user clicks an item and nothing happens ) is always a bad UX. I noticed it to happen on popovers as well ( maybe same issue ) where I use it to display the value of a custom toggle ( with 3 states ) and it is really annoying to not to be able to switch the toggle again while the dismiss animation is running.
