### ISSUE TITLE
Popover's position not right and arrow not show

### ISSUE THREAD

**Issue by lonyel** [driftyco/ionic#9340]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Popover can't work normaly. The position not OK, and the arrow not show.

**Expected behavior:**

**Steps to reproduce:**
Reproduce on 'ionic-preview-app':

1. clone this repo: git clone git@github.com:driftyco/ionic-preview-app.git
2.cd ionic-preview-app
3.npm install
4.run ionic serve from a terminal

**Related code:**

**Other information:**

![image](https://cloud.githubusercontent.com/assets/5528229/20608913/577fa89c-b2c1-11e6-9752-d2b0b629fd17.png)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually the expected look for our Material design popover. I would recommend trying a native Android app such as the google play store or inbox by gmail and use the popover on those apps as that is what we designed our Popover to match.
