### ISSUE TITLE
[text-underline] missing

### ISSUE THREAD

**Issue by re2005** [driftyco/ionic#9342]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request 

**Expected behavior:**
[text-underline] {
text-decoration: underline;
}

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
