### ISSUE TITLE
dom polyfills are not within polyfills

### ISSUE THREAD

**Issue by stephenlautier** [driftyco/ionic#9343]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Is there a reason why the [DOM polyfill](https://github.com/driftyco/ionic/blob/8d7d7bdaba16c2dbac062977b4685ebd3a7cff5e/src/util/dom.ts#L5 ) is not included with other polyfills?

**Expected behavior:**
DOM polyfill moved into the polyfills. A reason why this is necessary so we can download our app bundle and polyfills concurrently without invoke our main, this will result in app booting up slightly faster.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic!  I am going to close this for now as we plan on keeping it separate. We are working on other things such as code splitting that will speed up boot time much more than this solution.
