### ISSUE TITLE
card modal

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic#9344]
**Ionic version:**  (check one with "x")
 
[ ] **2.x**

demo -> https://github.com/ggomaeng/react-native-card-modal

Can you create something like this in ionic? :)
 
[ ] feature request
 
![inspiration](https://cloud.githubusercontent.com/assets/731936/20612673/284a398c-b29b-11e6-963d-52f84849239e.gif)

**Comment by infinnie** [comment]
That would be awesome.

**Comment by cogoo** [comment]
![9344](https://cloud.githubusercontent.com/assets/14809642/20710417/3f9afda2-b632-11e6-8dcc-4c34dd5d505d.gif)

:) You can!

**Comment by manucorporat** [comment]
As @cogoo has demostrated, you have all the power of JS, HTML and CSS to create cool animations. Since this is not an standard component of iOS or android, it is up to you to implement it, it is possible.

We can't develop the app for you.

**Comment by infinnie** [comment]
@manucorporat But it is both useful and eye-attracting that everybody wants to see it implemented.

**Comment by gbelmm** [comment]
@jgw96 reopen please!!

**Comment by gbelmm** [comment]
@jgw96 ? @manucorporat
