### ISSUE TITLE
2.0.0-rc.3 (2016-11-17), missing files in ionic-hello-world@ watch

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#9349]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
2.0.0-rc.3 (2016-11-17)
I'm updating to RC3 from RC0.

**Expected behavior:**
ionic serve -p $PORT --nolivereload should serve my app in the browser

**Related code:**

[11:34:49]  copy: Error copying "/home/ubuntu/workspace/pathfinder/src/manifest.json" to 
            "/home/ubuntu/workspace/pathfinder/www/manifest.json": File not found 
[11:34:49]  copy: Error copying "/home/ubuntu/workspace/pathfinder/src/service-worker.js" to 
            "/home/ubuntu/workspace/pathfinder/www/service-worker.js": File not found 
[11:34:49]  copy: Error copying "/home/ubuntu/workspace/pathfinder/node_modules/ionic-angular/fonts" to "/home/ubuntu/workspace/pathfinder/www/assets/fonts" 

I can see the fonts folder but not the other two files in that path in my directory

**Other information:**

 Error: A watch configured to watch the following paths failed to start. It likely that a file referenced 
            does not exist: /home/ubuntu/workspace/pathfinder/src/assets/, 
            /home/ubuntu/workspace/pathfinder/src/index.html, /home/ubuntu/workspace/pathfinder/src/manifest.json, 
            /home/ubuntu/workspace/pathfinder/src/service-worker.js, node_modules/ionic-angular/polyfills/polyfills.js, 
            node_modules/ionicons/dist/fonts/, node_modules/ionic-angular/fonts/ 

Bug report below:

Any help appreciated.

0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.5.0/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@4.0.2
3 info using node@v4.5.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: /home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/pathfinder/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v4.5.0/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
10 verbose lifecycle ionic-hello-world@~watch: CWD: /home/ubuntu/workspace/pathfinder
11 silly lifecycle ionic-hello-world@~watch: Args: [ '-c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /home/ubuntu/workspace/pathfinder
17 error Linux 4.2.0-c9
18 error argv "/home/ubuntu/.nvm/versions/node/v4.5.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.5.0/bin/npm" "run" "watch"
19 error node v4.5.0
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tomgallagher** [comment]
Just as an update, I was running "@ionic/app-scripts": "0.0.46" when I got the errors above.

When I reverted to "@ionic/app-scripts": "0.0.45", the fonts file not found error went away.

Still getting these errors:

[12:07:43]  copy: Error copying "/home/ubuntu/workspace/pathfinder/src/manifest.json" to 
            "/home/ubuntu/workspace/pathfinder/www/manifest.json": File not found 
[12:07:43]  copy: Error copying "/home/ubuntu/workspace/pathfinder/src/service-worker.js" to 
            "/home/ubuntu/workspace/pathfinder/www/service-worker.js": File not found 

From the look of my directory, @ionic/app-scripts 0.0.45 should be looking for these in 

"/home/ubuntu/workspace/pathfinder/src/**assets**/manifest.json"

and

"/home/ubuntu/workspace/pathfinder/src/**assets**/service-worker.js"

No?

Thanks

Tom

**Comment by tomgallagher** [comment]
So I moved the files and it works. I never put the files in the previous location, they were there when I created a new project, so maybe you need to add this to the changelog?

cheers

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Sorry you ran into this issue while updating. As stable gets closer and closer there should not be any changes to our file structure anymore. I will see if we can integrate this into our changelog. Thanks again!
