### ISSUE TITLE
Problem with virtual scroll, orientation change and navigation

### ISSUE THREAD

**Issue by Ritzlgrmft** [driftyco/ionic#9350]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my app, I have a list with virtual scroll. When the user taps on an item, a sub-page is shown. When the user taps the back-button, the list is show again. So far so good.

But when the user changes the device's orientation (e.g. from portrait to landscape) on the sub-page and taps back afterwards, the list is shown with only one item.

**Expected behavior:**
After going back, again the whole list should be shown. Maybe repositioned to the beginning (like the behaviour, when I rotate the device showing the list).

**Steps to reproduce:**
see https://github.com/Ritzlgrmft/ionic2-virtual-scroll

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v4.6.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jeromeXoo** [comment]
Hello,

I have the same problem.

As complementary information, the items on the list stack up, which is why we only see one element

**Comment by OmarHassan25** [comment]
I have the same problem.

**Comment by faraazc** [comment]
+1 I have the same problem.

**Comment by GR1ML0CK** [comment]
+1 seeing the same exact issue

**Comment by radbp** [comment]
same here
