### ISSUE TITLE
ionic serve reports error in webpage - need flag to turn off that feature

### ISSUE THREAD

**Issue by mrweiland** [driftyco/ionic#9351]
**Ionic version:**  
* Ionic 2 RC3

**I'm submitting a ...** 
[x ] feature request

**Current behavior:**
I run ionic serve then if i get an error it displays over webpage so i need to close it everytime i debug.

**Expected behavior:**
This is expected behavior but its really bad for me when i cannot get rid of exceptions that been thrown - from my case Ionic native googlemaps plugin that is throwing a runtime error and i cannot do anything to catch those Runtime errors when i run in browser....

From my point of view thats ok to have this error message because i dont wanna load emulator each time when i wanna test some other code that is not dependent on googlemaps.

```
Runtime Error
Uncaught (in promise): cordova_not_available
```

**What i would like to have**
I wanna have an option that i can turn on or off gui errors with a flag on ionic serve command.

Example:
ionic serve --noguierrors

Or better.. 
ionic serve --guierror (this turn on this feature with errors in web gui)

This is really annoying behavior that really need to be fixed... i guess this feature works well  for 90% of the cases.... but for us this is really killing our development..

<img width="416" alt="skarmavbild 2016-11-25 kl 15 30 16" src="https://cloud.githubusercontent.com/assets/12168854/20628252/2d1c5eec-b325-11e6-9d20-0c0b4c15e166.png">

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#480
