### ISSUE TITLE
ionViewDidLoad does not work in components being rendered with an element tag on a page's template

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic#9352]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have a page, where in the template you render a component eg (`some-button`), inside `some-button.ts`, you can't use `ionViewDidLoad` to trigger functions. 

**Expected behavior:**
I expect there to be an easier way than passing `Events`, from the Page down to the component to tell if a page is loaded. 

I got around it by passing an Event eg "page-loaded" on the page, and my component on that page eg a back-button will listen for "page-loaded" and do something once it is observed. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you provide a code example (possibly a plunkr) that i can use to reproduce this issue?

**Comment by kamok** [comment]
@jgw96 Hey. Thanks for responding. I wasn't sure if this was a "feature" or a bug, so I put it under feature request. Do you have a plunkr default for ionic 2 blank set up that I can work on? 

It's really simple to replicate. Just do `ionic g page Something` to make SomethingPage and do `ionic g component SomeButton` to make SomeButtonComponent. Then just import the button onto the page. On the button's ionViewDidLoad, just do like a console.log("Component has loaded"), and the log should NOT go through.

**Comment by kamok** [comment]
@jgw96 Hi Justin, can you confirm that this IS a feature request; not a bug? Are you suppose to be able to use functions like ionViewDidLoad() or ionViewWillEnter() inside a component within another component (eg a page)?

**Comment by kamok** [comment]
@jgw96 I did more digging on the API and I noticed that the ViewController provides Observables that does what I want to do: Run some method when the component loads. I think the docs can be more clear in this. Thanks.
