### ISSUE TITLE
bug: virtualscroll + infinitescroll moves the scroll up

### ISSUE THREAD

**Issue by faraazc** [driftyco/ionic#9353]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>virtualscroll + infinitescroll moves the scroll up when the new data is added in to dataset. This is a basic requirement for any data driven apps. As we cannot load data all in single shot and also we cant display huge list using ngFor</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We are aware of this issue and are tracking it [here](https://github.com/driftyco/ionic/issues/8744).
