### ISSUE TITLE
Support Ripple Directive

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#9354]
Hi,

Ionic 2 already have ripple effect on buttons, it would be really helpful if its functionality is exposed as a directive so that we can apply it on other items as well.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#177
