### ISSUE TITLE
whats the ionic command or minification process to deploy the app in production ? ( ionic 1 ) 

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9356]
whats the ionic command or minification process to deploy the app in production ?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
