### ISSUE TITLE
Ionic2:BarcodeScanner.encode error

### ISSUE THREAD

**Issue by ksphp** [driftyco/ionic#9363]
** code
```
BarcodeScanner.encode(BarcodeScanner.Encode.TEXT_TYPE,'http://www.nytimes.com').then(() => {
    console.log('suc');
}, (err) => {
    console.log(err);
});
```
** Error
Exception calling native with command :: BarcodeScanner :: encode ::exception=TypeError: success is not a function

**Comment by John-Luke** [comment]
This is an ionic native issue, please [open an issue there](https://github.com/driftyco/ionic-native/issues) with your problem and close here

**Comment by manucorporat** [comment]
@ksphp yeah! please can you reopen the issue in [Ionic Native](https://github.com/driftyco/ionic-native)

**Comment by ksphp** [comment]
Thanks！
