### ISSUE TITLE
feat(list): Add delete button

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#9366]
Similar to v1

http://ionicframework.com/docs/api/directive/ionDeleteButton/

closing https://github.com/driftyco/ionic/issues/5595 as a result of this

**Comment by marcelgoya** [comment]
@manucorporat 
Is this feature going to be added before the final v2 release? Thx, Marcel

**Comment by manucorporat** [comment]
@marcelgoya nop, but we will start working full time in new features once 2.0 final is released!

**Comment by marcelgoya** [comment]
@manucorporat So does that mean that the feature items in RC5 also won't be added before the final release?

**Comment by kabus202** [comment]
+1

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#105
