### ISSUE TITLE
No source code available for v1

### ISSUE THREAD

**Issue by kapowtest** [driftyco/ionic#9368]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

No source code for Ionic v1.x

**Expected behavior:**
"Src" folder exists in v2, but not v1 

**Steps to reproduce:**
Goto https://github.com/driftyco/ionic/tree/1.x

**Comment by RoopeHakulinen** [comment]
I don't think there has even been `src/` folder in v1. Instead it is just distributed on the root level to folders like `js` and `scss`.
