### ISSUE TITLE
Elements in the header not displaying correctly and the method content rezise not funtioned in ios

### ISSUE THREAD

**Issue by jmickvs** [driftyco/ionic#9372]
Hello, ago three months aproximately i reported the same bug (#7882), in that occasion i was work with ionic 2 beta 11, now i am work with ionic 2 RC3, i have the same issue, when i add dynamically elements in the header it aren't display correctly, like next image
![img_0038](https://cloud.githubusercontent.com/assets/15081575/20650651/69b2920c-b499-11e6-9261-09016bd634c1.PNG)
![img_0384](https://cloud.githubusercontent.com/assets/15081575/20650654/6e5fb988-b499-11e6-85f6-25566f876b41.PNG)

the code used in these examples is like this 
```
<ion-header>
    <!--<ion-title>{{ "PROFILE.TITLE" | translate }}</ion-title>-->
    <ion-navbar>
      <ion-searchbar *ngIf="!isIos" [(ngModel)]="searchQuery" (ionInput)="performSearch($event, null)" placeholder='{{ "CHATS.SEARCH_BAR_PLACEHOLDER" | translate }}'></ion-searchbar>
      <ion-title  *ngIf="isIos" style="padding-left: 0px;padding-right: 35px;">
        <ion-searchbar [(ngModel)]="searchQuery" (ionInput)="performSearch($event, null)" placeholder='{{ "CHATS.SEARCH_BAR_PLACEHOLDER" | translate }}'></ion-searchbar>
      </ion-title>
      <button ion-button *ngIf="!Config.InternetMsg" warning block class="minusculas noConnection">{{ "APPLICATION.NO_CONNECTION" | translate }}</button>
      <button ion-button *ngIf="Config.anonymousUser" color="danger" block class="minusculas info-msg" (click)="loginAnonymous()">{{ "CHATS.ANONYMOUS" | translate }}</button>
    </ion-navbar>
</ion-header>
```
other similar issue is when i change the location the buttons in the header code, the elements added dynamically overlap over the content, for this issue i already use the method rezise of the element Content, in android it method functions good but in iOS apparently not, the implementation of rezise has been already debugged and the object "content" exist in run time but when run method the content not doing the rezise, next i show the example
![img_0285](https://cloud.githubusercontent.com/assets/15081575/20650655/7a6e2ba6-b499-11e6-9175-0335d41f0b38.PNG)

the code that i use here is like this
```
<ion-header *ngIf="!hideHeader">
    <!--<ion-title>{{ "PROFILE.TITLE" | translate }}</ion-title>-->
    <ion-navbar>
      <ion-searchbar *ngIf="!isIos" [(ngModel)]="searchQuery" (ionInput)="performInputSearch($event)" placeholder='{{ "CHATS.SEARCH_BAR_PLACEHOLDER" | translate }}'></ion-searchbar>
      <ion-title  *ngIf="isIos" style="padding-left: 0px;padding-right: 35px;">
        <ion-searchbar [(ngModel)]="searchQuery" (ionInput)="performSearch($event)" placeholder='{{ "CHATS.SEARCH_BAR_PLACEHOLDER" | translate }}'></ion-searchbar>
      </ion-title>
<!--       <button ion-button *ngIf="!Config.InternetMsg" warning block class="minusculas noConnection">{{ "APPLICATION.NO_CONNECTION" | translate }}</button>
      <button ion-button *ngIf="Config.anonymousUser" color="danger" block class="minusculas info-msg" (click)="loginAnonymous()">{{ "CHATS.ANONYMOUS" | translate }}</button> -->
    </ion-navbar>
<div style="width:100%; position:absolute">
            <button ion-button *ngIf="!Config.InternetMsg" warning block class="minusculas noConnection">{{ "APPLICATION.NO_CONNECTION" | translate }}</button>
      <button ion-button *ngIf="Config.anonymousUser" color="danger" block class="minusculas info-msg" (click)="loginAnonymous()">{{ "CHATS.ANONYMOUS" | translate }}</button>
</div>
</ion-header>
```
and my implementantion of rezise methos is 
```
import {App, Content, ModalController} from 'ionic-angular';
import {Component, NgZone, ViewChild} from '@angular/core';
/*more imports*/

@Component({
templateUrl: 'chats.html'
})

export class ChatsPage {
@ViewChild(Content) chatsContent: Content;

/*more code*/

 resizeContent(){
     this.chatsContent.resize();
 }
```

in android happens not this, thank you i hope you can help me,
regards.

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
OS: Linux 4.4
Node Version: v6.3.1
```

**Comment by manucorporat** [comment]
Should be fixed in next release!

**Comment by jmickvs** [comment]
Hello, just to comment that the bug described only reproduced when i use button component, for the moment i use div and the resize method run correctly, thank you.
Regards.
