### ISSUE TITLE
Color attribute no longer works in FAB list [RC3]

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#9373]
**Ionic version:**  
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  
[ x] bug report

**Current behavior:**
The color attribute no longer works for buttons in a FAB list.

**Expected behavior:**
The color attribute should change the color.

**Steps to reproduce:**
Create a FAB with an `<ion-fab-list>` with buttons inside it, then try to set the color of the button, for example `color="secondary"`.

**Related code:**

```
 <ion-fab center bottom>
    <button ion-fab color="primary"><ion-icon name="md-cog"></ion-icon></button>
    <ion-fab-list side="top">
      <button ion-fab color="secondary"><ion-icon name="md-log-out"></ion-icon></button>
    </ion-fab-list>
    <ion-fab-list side="left">
      <button ion-fab color="secondary"><ion-icon name="person"></ion-icon></button>
    </ion-fab-list>
    <ion-fab-list side="right">
      <button ion-fab color="secondary"><ion-icon name="information-circle-outline"> </ion-icon></button>
    </ion-fab-list>
  </ion-fab>

```

**Other information:**
I believe that this was broken with eb0b05df88946f1c662c65a707f603aa46ff53cb or c9fdbf9c10869c8ebf1f32dadbdd6c49fa3ce58f. It appears that `.fab-in-list` is overriding the colors.

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62```

**Comment by manucorporat** [comment]
Already fixed in nightly. Thanks for the report.

**Comment by speedfl** [comment]
Quick question. I updated today to rc3 and i am getting the error. My fab list are no more with my color.
What do I have to do ?

**Comment by Tyler-Darby** [comment]
@speedfl `npm install ionic-angular@nightly`

**Comment by Tyler-Darby** [comment]
@speedfl Whoops, it's `npm install --save ionic-angular@nightly`

**Comment by speedfl** [comment]
@Tyler-Darby thanks for the tips however with this new version the no-shadow is not working anymore on the ionic header + the solution proposed here https://github.com/driftyco/ionic/issues/8425#issuecomment-261790685 do not work anymore and labels are not displayed anymore.

Any solutions?

Best regards

Geoffrey MUSELLI
