### ISSUE TITLE
using angular2-signaturepad

### ISSUE THREAD

**Issue by jtushar53** [driftyco/ionic#9380]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

want draw on a image using html 5 canvas, found https://github.com/wulfsolter/angular2-signaturepad , touch position is incorrect

Same issue i got using javascript implementation of https://github.com/jakubfiala/atrament.js 
angular2-signaturepad is AOT enabled.
**Expected behavior:**

correct touch position 
**Steps to reproduce:**

Follow step from https://github.com/wulfsolter/angular2-signaturepad readme
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by jtushar53** [comment]
hello @jgw96  , i thought of this an issue, as i have successfully integrated both libraries into my ionic project but both are getting same issue , also i tested with their demos and both their libraries work very well from a mobile chrome browser. Am i missing something ?
http://szimek.github.io/signature_pad/
http://fiala.uk/atrament.js/demo/
i just thought that if ionic is intercepting touch events so created an issue :)
