### ISSUE TITLE
iOS Bug: Pressing a button in an alert modal makes input behind it gain focus

### ISSUE THREAD

**Issue by aplimovil** [driftyco/ionic#9382]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
(This happens on iOS 9 and 10. On Android works fine.)

I've a form, with a "close" button on the toolbar, which when pressed presents an alert modal (with an "OK" and "Cancel" button) asking the user to confirm if he'd like to exit without saving changes. If the user presses the "OK" button navController.pop() runs in order to exit the form. However, if an input field is exactly behind the modal buttons, then by the time the modal closes and navController.pop() is called, the input behind it gains focus and prevents navController.pop() from running (even if a very quick tap is done). Strangely enough, when the modal is displayed and the backdrop is there, you can still scroll content from behind.

Then, when I try to press the close button again, this time not having the input field behind the buttons of the alert modal, then navController.pop() runs but it's called twice, a blank page is displayed, and a warning is displayed in the console saying the navigation stack is now empty because navController.pop() was called to many times.

**Expected behavior:**
Pressing a button on the alert modal shouldn't make the "tap" event run on elements behind it.

Also, an input field gaining focus shouldn't prevent nav.pop() from actually succeeding.

**Steps to reproduce:**
http://plnkr.co/edit/VefSfF

Be sure to run the code sample in Plunker on iOS 9 or 10.

**Other information:**
HERE'S THE CONSOLE OUTPUT OF WHEN THE ERROR HAPPENS. PLEASE NOTE THAT SOMETIMES NO ERROR APPEARS IN THE CONSOLE, BUT THE SCREEN GOES BLANK ANYWAY.
```
You can't remove all the pages in the navigation stack. nav.pop() is probably called too many times. (2)
e {_config: t, _elementRef: t, _renderer: t, _componentName: undefined, parent: null, …}
<ion-nav swipebackenabled="false" class="menu-content menu-content-reveal">…</ion-nav>

EXCEPTION: Uncaught (in promise): false
apply
(anonymous function)main.js:68:26103
handleErrormain.js:17:12331
nextmain.js:12:8641
(anonymous function)main.js:17:13793
__tryOrUnsubmain.js:27:28402
nextmain.js:27:27756
_nextmain.js:27:27067
nextmain.js:27:26739
nextmain.js:15:15770
emitmain.js:17:13567
triggerErrormain.js:2:3480
onHandleErrormain.js:2:3070
handleErrorpolyfills.js:2:13533
runGuardedpolyfills.js:2:11060
rpolyfills.js:2:8138
ipolyfills.js:2:8187
invokepolyfills.js:2:15205

ORIGINAL STACKTRACE:
apply
(anonymous function)main.js:68:26103
handleErrormain.js:17:12465
nextmain.js:12:8641
(anonymous function)main.js:17:13793
__tryOrUnsubmain.js:27:28402
nextmain.js:27:27756
_nextmain.js:27:27067
nextmain.js:27:26739
nextmain.js:15:15770
emitmain.js:17:13567
triggerErrormain.js:2:3480
onHandleErrormain.js:2:3070
handleErrorpolyfills.js:2:13533
runGuardedpolyfills.js:2:11060
rpolyfills.js:2:8138
ipolyfills.js:2:8187
invokepolyfills.js:2:15205
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X Mavericks
Node Version: v6.2.0
Xcode version: Xcode 6.2 Build version 6C131e
```

**Comment by ValterSantosMatos** [comment]
Also happens if there is a slider bellow (it will move the slider)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in the latest version of Ionic.
