### ISSUE TITLE
Super Wrong doc for Native Backgroundmode

### ISSUE THREAD

**Issue by workfluo** [driftyco/ionic#9383]
Ionic 2 > Native > Backgroundmode: http://ionicframework.com/docs/v2/native/background-mode/

Static Members: isEnabled(), isActive() don't return Boolean but Promises.
Static Members: isActive(), ondeactivate(), onfailure() are Observables.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#833
