### ISSUE TITLE
Not able to clear the filter on ng-repeat in ionic v1

### ISSUE THREAD

**Issue by shairyar** [driftyco/ionic#9385]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unable to clear or reset the filter on ng-repeat. While using the filter on `ng-repeat` once the search has been done, the filter is being reset manually inside the controller via `$scope.filterName = "";` but it does not reset nor it throws any error.

**Expected behavior:**
While using a filter with ng-repeat one should be able to reset the filter by using the following code
`$scope.filterName = "";`

While its working on stand alone angular but its not working when using the same code with ionic

**Steps to reproduce:**
Here is the fiddle where the issue can be viewed http://jsfiddle.net/y7D4r/47/

You will notice that when you click on an item the filter is not cleared where as in stand alone angular the same concept works perfectly fine https://jsfiddle.net/opbwxt08/

**Related code:**

```
<ion-content class="has-header" padding="true">
    <input type="search" placeholder="Filter" ng-model="contactsFilter" id="search">
    <ion-list>
        <ion-item ng-repeat="contact in contacts |  orderBy: 'name.givenName' |  filter: contactsFilter track by contact.id "
            ng-click="create(contact)">
            <h2>{{contact.displayName }}</h2>
        </ion-item>
    </ion-list>
</ion-content>


$scope.create = function (contact) {
    $scope.contactsFilter = '';
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#62
