### ISSUE TITLE
Adding multiple proxies to ionic.config.json fails silently

### ISSUE THREAD

**Issue by danishin** [driftyco/ionic#9388]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Adding multiple `proxies` to `ionic.config.json` ignores all except for the first one.

For example,
```
{
...
  "proxies": [
    {
      "path": "/api",
      "proxyUrl": "http://localhost:9000/api"
    },
    {
      "path": "/assets",
      "proxyUrl": "http://localhost:9000/assets"
    }
  ]
}
```
Only `/api` is proxied properly.

**Comment by ncapito** [comment]
We should move this to ionic-app-scripts but your issue is the trailing comma after the last proxy.  Change it to the following and it will work.

```
 "proxies": [
    {
      "path": "/api",
      "proxyUrl": "http://localhost:9000/api"
    },
    {
      "path": "/assets",
      "proxyUrl": "http://localhost:9000/assets"
    },
  ]
```


Not sure how to move it but once you do I'm planning on submitting a PR to log the error when its failing to read the config file.  @brandyscarney  can you migrate this to ionic-app-scripts?

**Comment by danishin** [comment]
@ncapito I don't believe it was parsing error since if so, it shouldn't enable the first proxy either (it's all or nothing wrt parsing error). And the trailing comma in example code was a typo. The running code doesn't have it. So I think the issue lies somewhere else..

**Comment by danishin** [comment]
And I agree that this issue needs to be moved to app-scripts repo. Not sure how to do it though

**Comment by ncapito** [comment]
@danishin I can't reproduce the issue you are experiencing unless I break the config file.  Then you are correct neither works.      Once I removed the trailing , all my proxies are working correctly.  


Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.46


My setup:

    "proxies": [
      {
         "path": "/api/Account/",
        "proxyUrl": "http://nicks-pc.local/Test.Api/api/Account/"
      },
      {
         "path": "/api/Notes/",
         "proxyUrl": "http://nicks-pc.local/Test.Api/api/Notes/"
       }

> npm run serve --debug
>[08:15:24]  Proxy added:/api/Account/ => http://nicks-pc.local/Test.Api/api/Account/
>[08:15:24]  Proxy added:/api/Notes/ => http://nicks-pc.local/Test.Api/api/Notes/

And when I run/test in the browser those endpoints proxy correctly.

**Comment by danishin** [comment]
@ncapito 
This issue is really weird and I haven't looked deeper in the source code so I cannot really tell but could you try with different **root path** instead? 

Like as in:
```
"path": "/account",
...
"path": "/notes",
...
```
Also should the trailing slash in `path` be semantically significant?

**Comment by ncapito** [comment]
Just an update for you I just tested the following without issue:

```
  "proxies": [
   {
     "path": "/account",
     "proxyUrl": "http://nicks-pc.local/Test.Api/api/Account/"
   },
   {
     "path": "/notes",
     "proxyUrl": "http://nicks-pc.local/Test.Api/api/Notes/"
   }
```

and 

 ```
 "proxies": [
   {
     "path": "/account/",
     "proxyUrl": "http://nicks-pc.local/Test.Api/api/Account/"
   },
   {
     "path": "/notes/",
     "proxyUrl": "http://nicks-pc.local/Test.Api/api/Notes/"
   }
```


I will say I tried just `path:"account/` and it did not work.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1876

**Comment by vinayshah** [comment]
Hello

Could any one tell 
How can I dynamically set proxly url based on user input "http://example.com", as I am getting preflight error.
