### ISSUE TITLE
how to use ionSelect - expression to be evaluated when selected ?

### ISSUE THREAD

**Issue by derah04** [driftyco/ionic#9390]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I want to show alert when I select some radio button option, how i can do that?

**Comment by mhartington** [comment]
Closing as this is a question and not an actual issue. As noted in the 'support request' selection, please use the forum or the public slack channel instead.
