### ISSUE TITLE
ion-searchbar [animated]="true" [showCancelButton]="false"

### ISSUE THREAD

**Issue by miloslavskacel** [driftyco/ionic#9391]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When [animated]="true" is used on ion-searchbar, Cancel button is shown, even when  [showCancelButton]="false".

**Expected behavior:**
Cancel button is displayed based on [showCancelButton] setting only.

**Steps to reproduce:**
Use the below code.
User enters ion-searchbar.
Cancel button is displayed 

```
<ion-header>
  <ion-navbar>
    <ion-searchbar [animated]="true" [showCancelButton]="false">
    </ion-searchbar>
  </ion-navbar>
</ion-header>

<ion-content padding>
  The world is your oyster.
</ion-content>
```
![screen shot 2016-11-28 at 15 36 09](https://cloud.githubusercontent.com/assets/2547672/20672402/7f758e6c-b581-11e6-9143-b719d78f1b15.png)

**Other information:**
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by manucorporat** [comment]
Use:
```
    <ion-searchbar animated="true" showCancelButton="false">
```
since you are not binding a dynamic value

**Comment by miloslavskacel** [comment]
Using animated="true" showCancelButton="false", Close button is still displayed.

```
<ion-header>
  <ion-navbar>
    <ion-searchbar animated="true" showCancelButton="false">
    </ion-searchbar>
  </ion-navbar>
</ion-header>
```

![screen shot 2016-11-29 at 09 04 30](https://cloud.githubusercontent.com/assets/2547672/20701389/0dfa62b6-b613-11e6-844d-147b7a6b1209.png)

**Comment by miloslavskacel** [comment]
@manucorporat please consider to reopen, problem was not solved

**Comment by mumairofficial** [comment]
In my case this is working well `[showCancelButton]="true"`
