### ISSUE TITLE
toolbar - statusbar-padding should not apply height

### ISSUE THREAD

**Issue by dominikstrasser** [driftyco/ionic#9395]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On native devices the class `statusbar-padding` is added to the toolbar.
This applies the following css:
```
padding-top: 20px;
height: calc(44px + 20px);
min-height: calc(44px + 20px)
```

**Expected behavior:**

The height and min height should not be applied to the toolbar (only the padding-top)

**Other information:**

 
![img_1531](https://cloud.githubusercontent.com/assets/7978324/20680143/27e4ab52-b59e-11e6-9230-28f0b84754f2.jpg)

![img_1530](https://cloud.githubusercontent.com/assets/7978324/20680142/27e04102-b59e-11e6-9315-9e780119e235.jpg)

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by dominikstrasser** [comment]
Pull Request -->
https://github.com/driftyco/ionic/pull/9396

**Comment by manucorporat** [comment]
related with https://github.com/driftyco/ionic/issues/9372
@dominikschreiber I just commented in your PR
