### ISSUE TITLE
Using .fixed-content when I have a header and tabs

### ISSUE THREAD

**Issue by ix-xerri** [driftyco/ionic#9397]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

Tried on the forum but no reply.

I want to display a google map in full screen apart from the header and the tabs at the bottom. I inspected the element and saw .fixed-content and that may help me because I would put the map in there and set the top: 0 and bottom: 0 but I there is no documentation on how to put content in .fixed-content.

**Comment by brandyscarney** [comment]
Thanks for the issue, there is an issue open to add docs on this here: https://github.com/driftyco/ionic-site/issues/776

It also has some examples using it. :)
