### ISSUE TITLE
To continue, please login to your Ionic account.

### ISSUE THREAD

**Issue by chrislow** [driftyco/ionic#9399]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

1. Run `ionic -g page login`
2. It asks for my ionic-account login like: `To continue, please login to your Ionic account.`
3. Enters E-Mail + Passwort, it says im logged in :)
4. Nothing got generated :C
5. Run the command above again -> Login asked again.
6. It does not happen with the full command: `ionic generate page login`

**Expected behavior:**

It should generate the page and only ask once for login.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.12.0
Xcode version: Not installed

```

**Comment by brandyscarney** [comment]
Thanks for the issue! Remove the `-` from in front of the `g` and it should work. :) 

```
ionic g page login
```

Please see the docs here: http://ionicframework.com/docs/v2/cli/generate/
