### ISSUE TITLE
How to trigger the 'refresh' event of refresher in ionic2 when a page reload

### ISSUE THREAD

**Issue by eric-heihei** [driftyco/ionic#9403]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I don't know how to trigger the event of refresher when a page reload.
For example：
.....
export class ActivityPage implements OnInit {
       ngOnInit() {
       }
}
I want to trigger the 'refresh' event of refresher in the function ngOnInit()
**Expected behavior:**

I want to trigger the 'refresh' event of refresher in the function ngOnInit()
Who can give me a demo?Thanks.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by finalxcode** [comment]
+1 how to achieve it?

**Comment by jaonhe** [comment]
+1

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
