### ISSUE TITLE
NavController.setPages() with nav params - unclear documentation

### ISSUE THREAD

**Issue by jonathan-chin** [driftyco/ionic#9405]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The documentation lists NavController.setPages() to take an array of pages with their params as the first argument. However, there is no example of doing this and I cannot, for the life of me, figure it out.

**Expected behavior:**
```
import {HelloPage} from "pages/hello";
[...]
// works as expected
let options = {name: "Bill"};
this.navController.setRoot(HelloPage, options);


// how would I pass the params in setPages?
this.navController.setPages([GoodbyePage, HelloPage]);
this.navController.setPages([GoodbyePage, HelloPage], options); // doesn't work
this.navController.setPages([GoodbyePage, [HelloPage, options]]); // what I expected to work but doesn't
```

**Comment by jonathan-chin** [comment]
I think I figured it out but only after pouring through the source code. There are no easy examples online, anywhere.

```
this.navController.setPages([GoodbyePage, {page: HelloPage, params: options}]);
```

**Comment by DrMabuse23** [comment]
THX for this save my day

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#970
