### ISSUE TITLE
Ionic 2: Getting deprecated color warning on html elements

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#9406]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Putting an element on the page with a color attribute as of RC0 e.g: 
```
<h2 color="someColorNameHere">Hello</h2>
```

Yields the warning in the console:
```
Deprecated: The color input has been removed from HTML elements. Please add the `ion-text` attribute in order to use the color input. For example: `<a ion-text color="secondary">Link</a>`
```

**Expected behavior:**
No warnings.
If we should be replacing the attributes as stated, then this should be reflected in the release notes as I can't see it mentioned anywhere.

**Comment by manucorporat** [comment]
Just add ion-text
```html
<h2 ion-text color="someColorNameHere">Hello</h2>
``` 

you right, we missed this one in the release notes.

**Comment by Ross-Rawlins** [comment]
this sets the background color and the text color of the element. Is this on purpose? usually I was a blue button with white text not both blue...
