### ISSUE TITLE
FABs not opening on iOS 

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#9412]
**Ionic version:** 
2.0RC3

**Current behavior:**
Upon clicking a FAB in iOS, nothing happens (a list of buttons should appear)

**Expected behavior:**
A list of buttons (`<ion-fab-list>`) should appear

**Steps to reproduce:**
Create a FAB with a `<ion-fab-list>` and run on iOS

**Related code:**

```
<ion-fab right bottom>
  <button ion-fab color="primary"><ion-icon name="arrow-dropleft"></ion-icon></button>
  <ion-fab-list side="left">
    <button ion-fab color="primary"><ion-icon name="desktop"></ion-icon></button>
    <button ion-fab color="primary"><ion-icon name="mail"></ion-icon></button>
    <button ion-fab color="primary"><ion-icon name="cube"></ion-icon></button>
    <button ion-fab color="primary"><ion-icon name="shirt"></ion-icon></button>
  </ion-fab-list>
</ion-fab>
```

**Other information:**
![alt text](https://i.gyazo.com/b450712a7c2b2ad1111a99f1c25cabab.gif "Buggy")
As you can see the event is being triggered but they are not displaying.

![image](https://cloud.githubusercontent.com/assets/5661936/20729245/23fc21e4-b64f-11e6-87aa-ba7e0e8395ad.png "ugh")
Upon inspecting the CSS the list is set to `display: none` and when you untick that, the list shows but it goes downward and out of the page. 

This appears to be iOS only. Works fine on serve and android.

**Ionic info:** 

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201611282011
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by Tyler-Darby** [comment]
The `ion-fab-list` is not getting the `fab-list-active` class added when the button is clicked. If I manually add that class, the list displays.

**Comment by manucorporat** [comment]
@Tyler-Darby I can't reproduce this...

Can you try against nightly?

```
npm install ionic-angular@nightly
```

If the problem persist, can you provide a repo that reproduces the issue?

**Comment by Tyler-Darby** [comment]
@manucorporat I'm already running nightly. I will try downgrading to RC2 and see if that works because that's the last time I recall the FAB not glitching out.

**Comment by jgw96** [comment]
@manucorporat Just gave this a test with the latest nightly on the iOS 10 simulator and its working fine for me. @Tyler-Darby what version of iOS are you testing with?

**Comment by Tyler-Darby** [comment]
@jgw96 10.1 (14B72)

**Comment by Tyler-Darby** [comment]
I just started up a new project and tried to replicate it, and it works fine. Exact same code. Could it be a plugin issue?

**Comment by Tyler-Darby** [comment]
I managed to fix it, created a new project and basically copied everything over code-wise but started with a fresh new project. It's possible I messed something up over the past few months updating through the betas and RCs. Thanks for the help guys!
