### ISSUE TITLE
Data doesn't load upon view entry ( but it loads upon refresh ). 

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9416]
![del-not_-loading](https://cloud.githubusercontent.com/assets/1026325/20733610/521009fc-b662-11e6-9c73-3a9aa9709f4d.jpg)

After the plus sign it's supposed to write the city value but it doesnt. 

![del-after](https://cloud.githubusercontent.com/assets/1026325/20733629/6a4b3a5a-b662-11e6-9e95-6683dc57f9ef.jpg)

HTML

<ion-view view-title="{{ticker}} + {{property.city}}">  
   

Here's my controller :  

.controller('SinglePropertyCtrl', function($scope, _, $stateParams, $http, SinglePropertyDataService, PropertiesService) {
    console.log('61 -  firing  SinglePropertyCtrl  ');

  $scope.master = {};

  $scope.update = function(user) {
    console.log( '$scope.update called ... ', user);
    $scope.master = angular.copy(user);
  };

  $scope.isUnchanged = function(user) {
    return angular.equals(user, $scope.master);
  };

  $scope.$on("$ionicView.leave", function(){
    console.log("***********Got ionicview leave event.*********");
    var uch = $scope.isUnchanged($scope.property); 
    console.log( ' ***********  uch  = ', uch);
    if (uch == false) {
      console.log( ' uch is false');
      PropertiesService.update({ propertyId: $scope.property._id }, $scope.property);
    }
  });

    $scope.ticker = $stateParams.propertyTicker;  

    var finderProp = SinglePropertyDataService.getSinglePropertyData($stateParams.propertyTicker)
        .then(function(d) {
            $scope.property = _.findWhere(d, { address: $scope.ticker });

            console.log('77-C -- the value of  $scope.property =', $scope.property);
            $scope.update($scope.property);

        })

    $scope.selectChangedPriority = function(type) {
            var arrSelectedProperties = $rootScope.propertiesSelected;
            window.arrSelectedProperties = arrSelectedProperties;
            var currentProperty = arrSelectedProperties[arrSelectedProperties.length - 1];

            currentProperty.call_priority = type;
            PropertiesService.update({ propertyId: currentProperty._id }, currentProperty);
        }
})

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
