### ISSUE TITLE
Ionic cli adds outdated version of Cordova iOS by default when starting a project

### ISSUE THREAD

**Issue by Igor-Lopes** [driftyco/ionic#9417]
**Ionic version:**  (check one with "x")
[ X] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When starting a new project with ionic cli, it adds iOS platform by default with an outdated version of cordova-ios that will throw the following warning when deploying or emulating iOS 10.1 : "[App name] May Slow Down Your Iphone". In order to fix this issue, it's necessary to update the project with the latest version of cordova-ios and specify it on **package.json**.

**Expected behavior:**
Ionic cli adds the latest version of cordova-ios upon adding iOS platform by default.

**Steps to reproduce:**
1. Start a project with ionic cli:
`ionic start myApp sidemenu` 
ionic will add iOS platform by default: 
![screen shot 2016-11-29 at 21 29 10](https://cloud.githubusercontent.com/assets/11265789/20734844/f0d10d44-b67a-11e6-9e20-10c63a7fcfdb.png)

2. Emulate iOS
`ionic emulate iOS` 

Then the warning is shown:
![screen shot 2016-11-29 at 21 33 14](https://cloud.githubusercontent.com/assets/11265789/20734951/7a210ea0-b67b-11e6-9f90-91b14e562ed2.png)

Cordova iOS version added by default by ionic cli:
`4.1.1` 

**Other information:**

**Ionic info:** 

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.1 Build version 8B62

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1736
