### ISSUE TITLE
ionic2  2.0.0 rc3  how to use non ionic-native cordova plugin

### ISSUE THREAD

**Issue by Gtanxingwen** [driftyco/ionic#9420]
i use declare var xxx;
error not defied;
@alakra 
@mlynch

**Comment by manucorporat** [comment]
Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

But you should be able to use a cordova plugin directly accessing the window variable

```js
window.PLUGIN
```
