### ISSUE TITLE
Import a Javascript external library (N.js) into a ionic v2 project

### ISSUE THREAD

**Issue by tryadelion** [driftyco/ionic#9422]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[X ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

As there is no documentation easily and publicly available, i'm requesting assistance and a doc writing on how to import a classical, third party, Javascript library ( let's name it N.js), the import process of which is not described anywhere, and does not follow common sense.

Steps to reproduce:

insert import statement into index.html
<script src="app/libs/N.js"></script>

go to home.ts and define var N  so .TS doesn't start shouting at you for no reason, as N doesn't have a typings file.

ionic-serve.
it won't find the script files.

**Comment by graphefruit** [comment]
@tryadelion 

1. Install latest ionic
2. Start your project
3. Go to /src/
4. open the assets folder
5. create a /js/ folder inside assets
6. copy your .js inside this js folder
7. goto /src/index.html 
8. Add your path <script src="assets/js/N.js">
9. Go to your typescript file of choice and declare var N;
10. N.yourFunction
11. ionic serve
Greetings

**Comment by tryadelion** [comment]
thank you very much. that should be part of the official docs.

**Comment by graphefruit** [comment]
Your welcome, just for fullfillment, the same thing goes for CSS, Fonts (like font-awesome) or Images.

**Comment by tryadelion** [comment]
Neat. why it won't be imported if it's somewhere else, say, a /libs/ or /fonts/ folder inside src?

**Comment by graphefruit** [comment]
Ionic build this into their buildscript, it runs through the assets folder and copies it to the www/assets folder, so you don't need to put it somewhere else.
-> http://blog.ionic.io/announcing-the-ionic-2-release-candidate/ -> Search for "assets"

If you need to deploy it in a different way I think you need to grab into theire buildscript.

In the previous releases, before the RC, you needed to extend the buildingscript on your own to copy the data inside the /www/ folder.

Normaly (e.g. font-awesome) references their fonts with "../fonts", so your directory doesn't have any problems:
- assets/
  - css
  - js
  - images
  - fonts

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mg1075** [comment]
@graphefruit @tryadelion I had to add the `<reference ... />` for typescript typings file at the top. 

Thank you so much @graphefruit for the instructions.

The ionic website instructions did **not** work for me. 

I think this question should be re-opened, as it is not a simple "support question". The ionic instructions seem to be incomplete and/or inaccurate. 

And it seems to be the case that when questions are opened in the support forum, they go there to silently fade away, noticed only by the one who opened the question.

**Comment by jd0048** [comment]
Import a Javascript external library Does not work
also external javascript library does not support typing so how can we used external javascript library in ionic 2?

**Comment by tryadelion** [comment]
i used to fake typings. import the library, then declare it's namespace as any.
for example, for moment when there wasn't a moment.js lib i used to
declare var moment: any;

this fakes any Typescript warning

**Comment by jd0048** [comment]
moment is work for me 
there is one lib called anypicker that does not support below is link for that

https://github.com/nehakadam/AnyPicker

**Comment by sutrisna** [comment]
in my src/index.html
```
  <script src="assets/socket.io.js"></script>
  <script src="assets/easyrtc.js"></script>
```

in my component.ts
```
 easyrtc.setSocketUrl("http://192.168.0.20:3000");
 easyrtc.connect("easyrtcAppKu", function () {
    
}, function () {

});
```
Output
```
Typescript Error
Cannot find name 'easyrtc'.
```

anyone can help me ?

**Comment by aritrabasu104** [comment]
@graphefruit i am not able to access the var from ts file

**Comment by UmerYousuf** [comment]
@tryadelion nothing happens bro when i follow steps and i do also these steps but nothing happens.


Put the import js in src/index.html header tag, before the  build/polyfills.js and build/main.js (they are in body tag);

Example : I created a file src/assets/test.js with a var testvar, imported in src/index.html and then in src/app/app.component.ts declared declare var testvar;.

test.js

var testvar = "Hello from external js";
index.html

...
  <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="#4e8ef7">

  
  <script src="cordova.js"></script>
  <script src="assets/js/test.js"></script> //here, not in body
...
app.componet.ts

declare var testvar;

@Component({
   templateUrl: 'app.html'
})
export class MyApp {
  @ViewChild(Nav) nav: Nav;
  constructor(private statusbar : StatusBar,  splashScreen: SplashScreen) {
   alert(testvar);
...
