### ISSUE TITLE
tabs-top bug

### ISSUE THREAD

**Issue by zelphir** [driftyco/ionic#943]
### ionic 1.0.0-beat.1

Found a small bug with tabs-top. There are 2 different behaviours.

**IOS**
- the tabs are underneath the header
- the tab content is underneath the tabs list

![screen shot 2014-03-28 at 10 24 56](https://cloud.githubusercontent.com/assets/2644782/2548520/c84bc59a-b663-11e3-947d-99d348ed070e.png)

**Android**
- no problem with the header
- same problem with the tab content

![screenshot_2014-03-28-10-28-14](https://cloud.githubusercontent.com/assets/2644782/2548526/efd8ea48-b663-11e3-872e-eb202e9c3555.png)

I had the problems in the project I'm working on (second screenshot), so I decided to start a clean project and just apply the tabs-top instead of tabs default. I've added also the side menu. No problems in the browser.

**Comment by manuelkuffo** [comment]
Thanks @zelphir! class="tabs-icon-top tabs-top" works for me Too.
