### ISSUE TITLE
bug: My sort function does not work on IOS

### ISSUE THREAD

**Issue by rmit-s3578933-shiran-ekanayake** [driftyco/ionic#9430]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>I use the following function to sort an array of objects by date of each object. It seems to be working fine when using ionic serve -l command and also works well in android devices. But it does not sort the array in ios simulator or in a real ios device.

```
$scope.arr.sort(function(a, b){
                return new Date(a.latest.date).getTime() - new Date(b.latest.date).getTime();
});
```

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
