### ISSUE TITLE
black ion-navbar hides the ios status bar 

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic#9432]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using dark color for ion-navbar makes ios status bar almost impossible to see as it's also in black color.

<img width="377" alt="screenshot 2016-12-01 00 43 21" src="https://cloud.githubusercontent.com/assets/8744282/20787161/32857592-b75f-11e6-8f3c-0bdc8c868c48.png">

**Expected behavior:**
When ion-navbar has dark background, change ios status bar color to white to make it visible.

**Steps to reproduce:**
1. Change primary color to black.
2. Change ion-navbar color to primary
**Related code:**

```
<ion-header>
  <ion-navbar color="primary">
    <ion-title>World Weather</ion-title>
  </ion-navbar>
</ion-header>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by manucorporat** [comment]
Use the StatusBar plugin to fix it:
https://ionicframework.com/docs/v2/native/status-bar/
