### ISSUE TITLE
RC3 setScrollDisabled() on IOS break Gestures

### ISSUE THREAD

**Issue by Yimiprod** [driftyco/ionic#9433]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When we use `app.setScrollDisabled(true)` on iOS (simulator and device) it break all the Gesture events excepte the `swipeToGoBack` Gesture, who reactivate the gesture events by the way.

**Expected behavior:**
It should only disable the scroll

**Steps to reproduce:**
Only way to reproduce is in an app on an iPhone (device or emulator).
Navigate to a page who use `this.app.setScrollDisabled(true)`

**Related code:**

```
import { Component } from '@angular/core';

import { App } from 'ionic-angular';

@Component({
  templateUrl: '<div></div>'
})
export class Example {
   constructor(public app: App) {}

   ionViewWillEnter() {
     this.app.setScrollDisabled(true);
   }
}
```

**Comment by manucorporat** [comment]
@Yimiprod you should not use this method. I will mark it as private.

just use:
```
<ion-content no-bounce>
```
