### ISSUE TITLE
Bug when publishing event from inside Push plugin callback

### ISSUE THREAD

**Issue by akz92** [driftyco/ionic#9437]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a provider that handles everything related to push notifications. I want to navigate to a page that has tabs whenever I receive a push notification. To achieve this I subscribe to an event on `app.component.ts` and push the desired page when it's published, and I publish this event from the `Push.on('notification')` callback when I receive a push notification.

The problem is that when I navigate to a page that has tabs using what I described above the tabs get on top of the header. This only happens if I publish the event inside the `Push.on('notification')` callback, if I publish it from anywhere else everything works fine.

**Expected behavior:**
The desired behavior is that the tabs are displayed as usual without getting on top of the header.

**Steps to reproduce:**
I created a new project to reproduce the bug: https://github.com/akz92/ionic-example
I didn't add the Push plugin because you need a `sender_id` to use it, so to reproduce you need to have a `sender_id`, add the plugin and add the `sender_id` to the `PushService` provider init function.

**Ionic info:**

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#237

**Comment by akz92** [comment]
I may be missing something here, but AFAIK this issue isn't related to Ionic Cloud.
