### ISSUE TITLE
App builds on Windows but not Mac OS

### ISSUE THREAD

**Issue by obkdev** [driftyco/ionic#9439]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When building an Ionic project in Windows, it builds and runs fine using `ionic serve`, but the same project on Mac OS causes a missing main.js using `sudo ionic serve`. No build errors showing whatsoever.

**Expected behavior:**
main.js should be present.

**Ionic info - Windows:**
```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.38
OS:
Node Version: v6.9.1
```

**Ionic info - Mac OS:**
```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.38
Ios-deploy version: Not installed
Ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by msegers** [comment]
Note that you shouldn't need to sudo. And depending on your config this is a question for https://github.com/driftyco/ionic-app-scripts.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#498
