### ISSUE TITLE
Scrolling bug 1.x

### ISSUE THREAD

**Issue by Onurrr** [driftyco/ionic#9440]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Running ionic serve, I'm not able to scroll down the page since the 1.3.2 update, switching back to 1.3.1 made it work again

**Expected behavior:**
Scrolling would work
**Steps to reproduce:**
Set up blank project
**Related code:**
--

**Other information:**
--

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.1 Build version 8B62


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)

******************************************************
```

**Comment by jgw96** [comment]
Hello! Unfortunately, I cannot reproduce this issue at the moment. Would you be able to post a repo I can use to reproduce this issue? Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#61
