### ISSUE TITLE
"ion-infinite-scroll" directive doesn't seem to update the view height when used in Android < 4.4.4

### ISSUE THREAD

**Issue by miparnisari** [driftyco/ionic#9443]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The `ion-infinite-scroll` directive doesn't seem to update the view height when used in Android < 4.4.4. 

![bug](https://cloud.githubusercontent.com/assets/5374887/20808836/e3b4367c-b7e2-11e6-8f02-dc4f2d4cd353.gif)

**Expected behavior:**
The view height should be updated (this is easily verifiable if one looks at the height of the scroll bar, it should shrink) and the user should be able to scroll down again.

**Steps to reproduce:**

Using Android < 4.4.4 and assuming an infinite list of elements to be loaded:
1. Load a list of 20 elements,
2. Scroll to the bottom of the view
3. Wait for more items to be added to the list
4. Try to scroll down again. See how you can't.

**Other information:**
A detailed explanation can be found in [this StackOverflow question](http://stackoverflow.com/questions/36000494/ionic-infinite-scroll-doesnt-work-on-all-android-devices). 

**Ionic info:**
```bash
λ ionic info

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.6.1
```

**Comment by miparnisari** [comment]
I seem to have found a workaround... Change from this

`<ion-content>`

to 

`<ion-content overflow-scroll='false'>`

to disable native scrolling in this particular view.

**Comment by johnnynode** [comment]
`<ion-content overflow-scroll='false'>` solution cause other problem , that is all the default events are prevented. It's good for most conditions but when I do not want default event to be prevented to do a specific demand, it's not ok for me!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#60
