### ISSUE TITLE
IPA Not created using ionic cli. IPA is created using cordova cli.

### ISSUE THREAD

**Issue by aoathout** [driftyco/ionic#9446]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

IPA file is not created when executing 'ionic build ios --device --release --buildConfig ./build.json'

**Expected behavior:**

IPA file should be created when running 'ionic build ios --device --release --buildConfig ./build.json'. Running 'cordova build ios --device --release --buildConfig ./build.json' creates the IPA as desired.

**Steps to reproduce:**

Create a simple application using cordova-ios@4.3.0 as the platform. Verify that app id is registered and provisioning profiles are installed on the machine.

Run: "ionic build ios --device --release --buildConfig ./build.json" on the fresh project
** build.json created based on cordova documentation here: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#signing-an-app

IPA file is not created in the platforms/ios/build/device folder.

 Run: "cordova build ios --device --release --buildConfig ./build.json" on the fresh project. The IPA file is created in the platforms/ios/build/device folder.

**Related code:**

```
No specific code required
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

Additional Info:
cordova-ios: 4.3.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1746

**Comment by qiluo** [comment]
Why this issue got closed? I ran into same issue

```
ionic info

  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
```
