### ISSUE TITLE
Icon blurred

### ISSUE THREAD

**Issue by Defcon0** [driftyco/ionic#9447]
**Ionic version:**  (check one with "x")
[X] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Icon is blurred on Huawei Y5 II 

smartphone (Nexus 4 works; other icons on Huawei smartphone do as well)

**Expected behavior:**
Icon is not blurred

**Steps to reproduce:**
1. Move icon.ai to /resources
2. Run "ionic resources --icon"
3. Run "ionic run android"

I attached you the illustrator and the generated xxxhdpi PNG file. Both of them are OK in my opinion but still the icon is blurred.

I tried to increase the size of the image in Illustrator to 512px ² without success :(

Any help is highly appreciated.

[android.zip](https://github.com/driftyco/ionic/files/625754/android.zip)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Defcon0** [comment]
Hello jgw96,

could you please define why you think "this seems like more of a support question"? What should go here in the github issues and what should not?
