### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by VietAnhh** [driftyco/ionic#9448]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic platform update ios

Outputs:

`mv: no such file or directory: /Users/myname/myproject/platforms/ios/myproject.xcworkspace/xcshareddata/xcschemes/__PROJECT_NAME__.xcscheme`

I couldn't find anyting on google explaining this. 

Does anybody know what's the reason for this?

**Comment by rickdmer** [comment]
I'm having this same issue.

**Comment by janky69** [comment]
this same issue...

**Comment by vTrip** [comment]
+1 same issue

**Comment by patrickmcd** [comment]
[See if this issue helps](https://github.com/driftyco/ionic-cli/issues/1197).

**Comment by rodrigobsmunifeob** [comment]
Me too +1
