### ISSUE TITLE
How to close ionicPopup after function execution

### ISSUE THREAD

**Issue by sneelakantam** [driftyco/ionic#9449]
I am having an issue with the ionicPopup.show. I am using the ionicPopup to show loader. 

**Here is my code:**

 var tab_loader = $ionicPopup.show({
	templateUrl: 'views/loader.html',
	cssClass: 'loader-ipopup',
	title: '',
	subTitle: '',
	scope: $scope,
	buttons: ''
});

tab_loader.then(function(res) {
	$scope.executeLogicPage(false, false);
	$rootScope.selected = section;
	$state.go(section);
});
$timeout(function() {
	tab_loader.close(); // close the popup after 3 seconds for some reason
}, 2000);

**My Issue is:**

Client didn't want timeout for the ionicPopup to close. He wants the popup should close before $state.go(section).

Can anybody please suggest me on this. How to close the ionicPopup without timeout.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
