### ISSUE TITLE
Title is truncated in navbar

### ISSUE THREAD

**Issue by RaoKarthik** [driftyco/ionic#945]
The title is truncated in navigation bar when the view is rendered for the first time and back button goes missing occasionally. 
The issue started after updating to beta

![screen shot 2014-03-28 at 4 14 08 pm](https://cloud.githubusercontent.com/assets/6458944/2549505/1ddb14bc-b677-11e3-8ead-d58cdd5cf3a7.png)
![screen shot 2014-03-28 at 4 15 27 pm](https://cloud.githubusercontent.com/assets/6458944/2549525/735e3f7c-b677-11e3-97b0-6b23dcf0e9e2.png)
![screen shot 2014-03-28 at 4 15 45 pm](https://cloud.githubusercontent.com/assets/6458944/2549526/786e3bca-b677-11e3-98a7-4631798678bd.png)
![screen shot 2014-03-28 at 4 14 30 pm](https://cloud.githubusercontent.com/assets/6458944/2549527/7b3c0d1e-b677-11e3-9636-20708c5b90eb.png)

**Comment by theentirety** [comment]
Been having this same truncation issue since updating to Ionic 1.2.4. It will truncate any text that is too long to just a character or two. Typically only happens with dynamic text populated by angular.

<img width="374" alt="screen shot 2016-01-31 at 14 32 58" src="https://cloud.githubusercontent.com/assets/1065398/12705501/9560e110-c827-11e5-8e09-5f804bfb1358.png">

**Comment by thanhnh-infinity** [comment]
Is there any available solution for this issue ?

**Comment by select-group** [comment]
[This commit](https://github.com/youtabmedia/ionic-bower/commit/0936d259ec8aef803ebe4e156be9cfa574057b34) by @krulik stopped text from getting cut off for me.

**Comment by Louis-P** [comment]
+1

**Comment by svnindia** [comment]
any solution found ?

**Comment by mypark** [comment]
Should be fixed in the new build I think - issue was closed.

**Comment by mdanics** [comment]
I am experiencing this same issue with Ionic Framework    : ionic-angular 3.9.2 . 

Any way to fix this?
