### ISSUE TITLE
[feat] reuse toolbars/navbars in components

### ISSUE THREAD

**Issue by dominikstrasser** [driftyco/ionic#9452]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently its not possible to reuse ion-toolbars/ion-navbars (as components) in ionic 2 apps. 
As far as i saw there is some functionality that requires a specific order to work...
so for example:
```
ion-nav>.ion-page>ion-header .toolbar.statusbar-padding:first-child ...
```

**Expected behavior:**
It would be very handy if we could wrap navbars/toolbars in components. 
example:
```
<ion-header>
   <my-reusable-navbar></my-reusable-navbar>
</ion-header>
<ion-content>...</ion-content>
```

**Steps to reproduce:**
http://plnkr.co/edit/ICsGEO

**Related code:**
file: cordova.scss

```
@mixin toolbar-statusbar-padding($toolbar-height, $toolbar-padding, $content-padding, $cordova-statusbar-padding) {

  > .toolbar.statusbar-padding:first-child {
    padding-top: calc(#{$cordova-statusbar-padding} + #{$toolbar-padding});

    min-height: calc(#{$toolbar-height} + #{$cordova-statusbar-padding});
  }
...
```
In the case of status-bar-padding maybe removing the child operator would be a possible fix for the problem shown the plnkr but i really don't know the full amount of work this feature would take. 

But i think it would be useful for a lot of people if we could reuse navbars/toolbars

let me know what you think about it :-)

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#106

**Comment by sarahsga** [comment]
please re-open this issue as we really need it. Re-using navbar/toolbars can be very handy. Plus the link [driftyco/ionic-feature-requests#106](driftyco/ionic-feature-requests#106) provided by @jgoux above doesn't work

**Comment by sergiomilici** [comment]
is there any news on this?
