### ISSUE TITLE
ionic app suddenly crashes and closes itself in ios

### ISSUE THREAD

**Issue by vahidvdn** [driftyco/ionic#9455]
**Ionic version:**
**1.3.1**

**I'm submitting a ...**
bug report

**Current behavior:**
Recently I confronted with a problem in my ionic app. This only appears in ios 9 (I didn't test in other versions of ios). Why I said recently? Since a few days a go, I didn't have a lot of data in my remote database. No when I load some data with ion-infinite-scroll , and change some states, suddenly app closes with NO ERRORS.

**Other information:**
I use gapDebug for watching the console log. But no errors appears. Any idea?
![e6fbeece-b7ec-11e6-9487-fe4e3b0f8a5c](https://cloud.githubusercontent.com/assets/11078601/20825041/a30a4636-b876-11e6-874e-c07b02c46fef.png)

**Ionic info:**

```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.5.0
```

**Comment by faraazc** [comment]
@vahidvdn please update ionic libs to latest RC.3. I faced similar issue. upgrading to latest did fix.

**Comment by vahidvdn** [comment]
@faraazc I'm not able to update it. I run this command:
`ionic lib update` or even `ionic lib` , I get this error:

```
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Local Ionic version: 1.3.1  (C:\Users\Cebit\myApp06\www\lib\ionic\bower.json)
Invalid version: undefined
```

**Comment by vahidvdn** [comment]
Recently I found out this issue also occurs in **ios 10** in a iphone 6 mobile.

Any solution?

**Comment by vahidvdn** [comment]
After spending a lot of time, I couldn't be able to solve this issue.

But I found out, When I go to the child `tab` in ionic tab component, this occurs, or when there is a lot state changing happens. It seems there is memory or cpu issues as discussed in some places like [here](https://github.com/driftyco/ionic/issues/1096) or [here](https://issues.apache.org/jira/browse/CB-10530).

No one has any idea?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#59
