### ISSUE TITLE
Components Don't Compile with strictNullChecks set to true in tsconfig.json

### ISSUE THREAD

**Issue by KyleMcNutt** [driftyco/ionic#9456]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Alert Component fails to compile on `ionic build android` when switching `strictNullChecks` to true in tsconfig.json

**Expected behavior:**

All Components compile correctly with `strictNullChecks` set to true.

**Steps to reproduce:**
Change your tsconfig.json to have `strictNullChecks` to true and then try to run an `ionic build`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
--------------------------------
--------------------------------
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37
OS:
Node Version: v6.9.1
--------------------------------
```

**Comment by pshendry** [comment]
I'm interested in seeing this addressed as well, particularly since there's no workaround that I know of (TypeScript doesn't support one-off exceptions to the `strictNullChecks` rule)

**Comment by KyleMcNutt** [comment]
Yea, my work around has been to comment out `strickNullChecks` in my tsconfig when doing builds or pushing to my CI system. That way I at least get strict checking during dev. But this is flaky and people forget to do this so missing checks get added in on occasion. I would really love to see this addressed.

**Comment by manucorporat** [comment]
We will keep the progress of this feature here: https://github.com/driftyco/ionic/issues/10646

Thanks!
