### ISSUE TITLE
Can't find variable Firebase with app-scripts0.0.46

### ISSUE THREAD

**Issue by urm47** [driftyco/ionic#9460]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using angularfire2 and firebase.
Call to firebase.auth().sendPasswordResetEmail reports error "Can't find variable Firebase"
Build with 0.0.45 was OK

**Expected behavior:**

No error

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#505
