### ISSUE TITLE
refactor(gestures): use injectable factory for gestures

### ISSUE THREAD

**Issue by manucorporat** [driftyco/ionic#9464]
Ionic gestures need DomController and GestureController in order to work properly, right now, since Gestures are not injectable, DomController and GestureController have to be injected in a lot of places where it is not really needed (Menu, NavControllerBase, Item, Toggle...)
https://github.com/driftyco/ionic/commit/c08c21a4a09a2823cb824a77a07328c8b99eb860

Also, providing injectable gestures can simplify unit testing.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#220
