### ISSUE TITLE
Lot sass color variable make white screen on android

### ISSUE THREAD

**Issue by movrack** [driftyco/ionic#9465]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When we use "to many" colors variables in theme/variables.scss color(), then we get a white screen at startup.

**Expected behavior:**
App start normally without white screen

**Steps to reproduce:**

1. Create a new App, for example : 
    `ionic start checkColorBug sidemenu --v2`

2. Modify color variable in app/theme/variables.css
    `$colors: (
  primary:    #387ef5,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
  dark1:       #222,
  dark2:       #222,
  dark3:       #222,
  dark4:       #222,
  dark5:       #222,
  dark6:       #222,
  dark7:       #222,
  dark8:       #222,
  dark9:       #222,
  darka:       #222,
  darkz:       #222,
  darke:       #222,
  darkr:       #222,
  darkt:       #222,
  darky:       #222,
  darku:       #222,
  darki:       #222,
  darko:       #222,
  darkp:       #222,
  darkq:       #222,
  darks:       #222,
  darkd:       #222,
  darkf:       #222,
  darkg:       #222,
);`

**Other information:**
There is some cartesian product made for sass. Then with the cleanCss step, all values are merged.
It look that the cleanCss process make a to big line for android web view to understand it.
the app crash and an opacity: .4 is presented.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v5.0.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by codeart1st** [comment]
I can confirm this. That's the reason why we override the cleancss config to not override the original main.css file in build folder.

**Comment by EDumdum** [comment]
Same problem.

It would be nice to avoïd generating so many css class (color^2) for component like toolbar, as we usually use one color for the whole application.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#506
