### ISSUE TITLE
[SEO-Router-PWA] : Http status code & Default Route

### ISSUE THREAD

**Issue by Mokto** [driftyco/ionic#9466]
Hi,

You are speaking a lot about Progressive Web Apps, and I am trying to do so with an app I am currently developing.
As I want to push my app online, I have some issues with handling SEO well.

This is how I configured my app (issue is the same with hash-based urls) :
```javascript
imports: [
	IonicModule.forRoot(MyApp, {
		locationStrategy: isDevMode() ? 'hash' : 'path',
	}, {
		links: [
			{ component: HomePage, name: 'Home', segment: 'home' },
			{ component: ContactPage, name: 'Contact', segment: 'contact' },
			{ component: AboutPage, name: 'About', segment: 'about' }
		],
	}),
]
```
I would like :
1) To be able to set a default route like this : `{ component: 404Page, name: '404', segment: '*'}`
2) If I can do that, my / route would be redirected on 404Page, so I would have to be able to add redirections.

**Ionic version:**
2

**I'm submitting a ...**  (check one with "x")
feature request

I know this is a feature request but I think this is much needed for PWA & SEO.

Thank you !

**Comment by Mokto** [comment]
Any news on this ?

**Comment by leonardobazico** [comment]
This will be great!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#139
