### ISSUE TITLE
ion-content has-bouncing

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#9467]
In Ionic 2, there are no reference in the docs if there is possible to disable the bouncing from ion-content (for iOS apps).
Has this feature been removed form Ionic 2?

In Ionic 1 it was able to use has-bouncing="false", according to the [docs](http://ionicframework.com/docs/api/directive/ionContent/).
But in the Ionic 2 [docs for ion-content](https://ionicframework.com/docs/v2/api/components/content/Content/), there is no reference.
Also, there is [no config option for this](https://ionicframework.com/docs/v2/api/config/Config/).

**Comment by gigocabrera** [comment]
@chrisbenseler  try the following:

`<ion-content no-bounce>`

The ionic-conference-app uses it on the `Tutorial` page and it works fine for me on an iOS device

**Comment by manucorporat** [comment]
yeah! Try `no-bounce`, let me know if it worked for you.

**Comment by chrisbenseler** [comment]
It has not worked in my tests, using iPhone 5 and 6. The views still bounce.

**Comment by gigocabrera** [comment]
Try installing the ionic-conference-app on your iPhone 6 and see if that behaves the same. Also, are you using the latest RC3?

**Comment by chrisbenseler** [comment]
Didn't work using iPhone SE Emulator (iOS 10) and a real device (iPhone 5C).
Ionic 2 is in the latest version (rc3).

**Comment by nathan5x** [comment]
Is it possible to apply this property for the entire app, instead of specifying in every view?

**Comment by Quest001** [comment]
Did you solved the problem？ can you teach me how to solve it！

**Comment by elvismercado** [comment]
`no-bounce` is not working on iPhone5 iOSv10.2
I have a Modal page and no-bounce on the `ion-content` tag

**Comment by icharge** [comment]
My Ionic 3 content is not bounce.  How to enable bouncing ?

**Comment by mchenx** [comment]
how to enable bouncing for ion-content with ionic2 ?

**Comment by luckylooke** [comment]
`no-bounce` has no effect.. I was trying clean ionic project `ionic conference` and applied `no-bounce` at speakers list page.. bouncing of scroll has not been disabled

cli packages: (/Users/lucky/Documents/projects/ionic-conference/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v6.9.5
    npm        : 5.4.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by dexterouschen** [comment]
@brandyscarney this is not working on ionic 3, neither has-bouncing/no-bounce works.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v8.5.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

**Comment by stewwan** [comment]
news ?
