### ISSUE TITLE
Hidden ion-nav-bar takes up space in the view

### ISSUE THREAD

**Issue by bostondv** [driftyco/ionic#947]
In 1.0.0-beta.1 when an `<ion-nav-bar>` is hidden using `<ion-view hide-nav-bar="true">` the view is not adjusted to fill the screen, instead the header still takes up space in the view.

I am also using side menus and not sure if it occurs without side menus.

Example: http://codepen.io/bostondv/pen/fdxsp

**Comment by lesserenterpriser** [comment]
Still running into this issue when trying to evaluate an expression.

For example:

<ion-view hide-nav-bar="myBoolean">

leaves a space, whereas

<ion-view hide-nav-bar="true">

does not leave a space.


Any thoughts?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#107
