### ISSUE TITLE
There was an error with the spawned command: serve

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#9475]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I just decided to start developing with Ionic, but after a fresh installation as documented as described here:
http://ionicframework.com/docs/v2/getting-started/installation/

I got the following error:

```
c:\xampp\htdocs\app>ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\home\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
npm ERR! node v6.5.0
npm ERR! npm  v4.0.2
npm ERR! path c:\xampp\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'c:\xampp\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'c:\xampp\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\xampp\htdocs\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve
```
Also, I run the command from my app project folder, `c:\xampp\htdocs\app`, why does the console shows the a package.json in the main folder is missing?..

**Expected behavior:**
ionic serve command to work on fresh projects

**Steps to reproduce:**
Install the latest ionic 2 & ionic 2 CLI versions and try to run `ionic serve`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.44
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.5.0
Xcode version: Not installed
```

**Comment by thorizer** [comment]
I have this too. how did you fix it?
