### ISSUE TITLE
Images not working in android

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#9476]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I built a simple applications with a list of users & images:
```
<ion-list>
  <ion-item class="text" *ngFor="let user of users | async">
    <ion-avatar item-left>
      <img [src]="user.photoURL">
    </ion-avatar>
    {{user.name}}
  </ion-item>
  </ion-list>
```

In web it works fine, in android the images are not working. The path of the images are remotely, example:
https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/13681063_106938193078695_4298957112094277798_n.jpg?oh=b12c584ac53a7caf0ec6eef6b330e8de&oe=58876685

**Expected behavior:**

Images to work with ionic 2

**Steps to reproduce:**

`<img src="https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/13681063_106938193078695_4298957112094277798_n.jpg?oh=b12c584ac53a7caf0ec6eef6b330e8de&oe=58876685">`

Will not be displayed in android

**Related code:**

`<img src="https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/13681063_106938193078695_4298957112094277798_n.jpg?oh=b12c584ac53a7caf0ec6eef6b330e8de&oe=58876685">`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.5.0
Xcode version: Not installed
```

**Comment by JianGuo222** [comment]
I have the same problem and it's driving me crazy now, any solution?

**Comment by wcy327417110** [comment]
Ionic3 
ImagePicker.getPictures  File_URL
<img src="file:///data/....../temp_****.jpg">
Cannot display, any solution?
