### ISSUE TITLE
Starter not starer (Docs bug)

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#9477]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[* ] **2.x**

**I'm submitting a ...**  (check one with "x")
[* ] bug report
[ ] feature request

https://ionicframework.com/docs/v2/api/navigation/DeepLinker/

"So for basic example based on the blank starer, a link setup like so"

Should read starter not starer

**Comment by yannbf** [comment]
@alexbainbridge I believe instead of filing an issue, you could just make a PR with that correction :D

**Comment by mhartington** [comment]
Thanks!
