### ISSUE TITLE
no-shadow broken in nightly 2.0.0-rc.3-201612021933

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic#9480]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

The `no-shadow` attribute no longer works in RC3 nightly (2.0.0-rc.3-201612021933)
```
<ion-header no-shadow>
  <ion-navbar>
    <ion-buttons end *ngIf="showSkip">
      <button ion-button (click)="startApp()">Skip</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```

**Ionic info:** 
```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612021933
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

**Comment by manucorporat** [comment]
Please, can you describe the issue better?

What do you expect? and what is actually happening? also, or screenshot or something

Thanks

**Comment by gigocabrera** [comment]
Here are 2 screenshots both using the same markup. Please notice the line below "Skip" on the right

```
<ion-header no-shadow>
  <ion-navbar>
    <ion-buttons end *ngIf="showSkip">
      <button ion-button (click)="startApp()" color="primary">Skip</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
``` 
The image on the left is using = "ionic-angular": "2.0.0-rc.3-201611211919",
the right one is using = "ionic-angular": "2.0.0-rc.3-201612021933",

![issue_9480](https://cloud.githubusercontent.com/assets/6364855/20868853/f7305110-ba33-11e6-8779-a2269c2cde92.png)

**Comment by brandyscarney** [comment]
Hey there, `no-shadow` has only ever affected `md` mode. The `ios` header has never had a box-shadow. The border was moved from the toolbar to the header, so adding `no-border` for ios would remove it. I'm wondering if there is an attribute we should use that targets both of them.

**Comment by gigocabrera** [comment]
Hi @brandyscarney, that is very strange because both screenshots from above were taken on a Chrome browser in iOS mode. But thanks for the `no-border` tip. I'll use that!

**Comment by gigocabrera** [comment]
@brandyscarney I am recopening this issue since none of those options work in iOS mode when using  Chrome or device

```
<ion-header no-shadow>
  <ion-navbar>
    <ion-buttons end *ngIf="showSkip">
      <button ion-button (click)="startApp()" color="primary">Skip</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

```

```
<ion-header no-border>
  <ion-navbar>
    <ion-buttons end *ngIf="showSkip">
      <button ion-button (click)="startApp()" color="primary">Skip</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>
```

**Comment by brandyscarney** [comment]
Thanks @gigocabrera! This will be fixed in the `rc.4` release, and I've also released a nightly if you want to use it sooner:

```
npm install --save ionic-angular@nightly
```

Just so you know - I renamed the `no-shadow` attribute to `no-border` since it seems confusing to have 2 different attributes that visually do the same thing. Let me know if you find any issues. :)
