### ISSUE TITLE
perf: HTTPS Error!!!

### ISSUE THREAD

**Issue by jdc20181** [driftyco/ionic#9485]
**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>This is a issue with chrome and eventually other browsers, please provide https loaded CDN's in your examples 

Thanks!</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Can you reopen the issue here: https://github.com/driftyco/ionic-site ? Also, I wonder if you could explain better what the issue actually is.

**Comment by jdc20181** [comment]
In chrome there is new rules where if you have a https site take https://github.com for example, but you load scripts from a http://scripts.com/main.js it will NOT load for most - Depending on the user's settings. Also, you have to hit the thing and it says "Load unsafe scripts" which I can almost guarantee ionic is safe. 

It sent me here - would have loved to stuck this issue in the right spot, it is really simple really, but can cause issues on both developer, and user ends

Thanks
