### ISSUE TITLE
Slidebox dosen't continue auto play when the time switch to other view is over the slide interval and then return this carousel view

### ISSUE THREAD

**Issue by linguoqiu** [driftyco/ionic#9490]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

# **Current behavior:**

   I have the issue that slidebox can't automatically play, when I click the tab switch to another view and come back.Note,this switch interval is greater than slide interval
   No change in the picture before the return is no problem, more than the return can not automatically play

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
HTML:

```
<ion-slides [options]="mySlideOptions" >
    <ion-slide><img src="assets/img/pic_ad1.gif" class="slide-image" /></ion-slide>
    <ion-slide><img src="assets/img/pic_ad2.gif" class="slide-image" /></ion-slide>
    <ion-slide><img src="assets/img/pic_ad3.gif" class="slide-image" /></ion-slide>
  </ion-slides>
```

TS:

```
@Component({
  templateUrl: 'indexPage.html'
})
export class IndexPage {

  mySlideOptions = {
    autoplay: 3000,
    loop: true,
    pager:true
  };
}
```

**Comment by jgw96** [comment]
Hello @linguoqiu , is this still an issue in the latest release?

**Comment by linguoqiu** [comment]
hello @jgw96 ,  my project is rc3  . also has this issue.

**Comment by brainworksideas** [comment]
Hello also has this issue and and mine is rc5
`<ion-slides autoplay="5000" loop="true" autoplayDisableOnInteraction="false" noSwiping="true" allowSwipeToPrev="false" allowSwipeToNext="false">
<ion-slide *ngFor="let s of c" (click)="abreUrl(s.imagen_publicidad.url)">
              <h2 class="publi-caption">{{ s.imagen_publicidad.nombre }}</h2>
              <img [src]="s.imagen_publicidad.imagen">
            </ion-slide>
          </ion-slides>`

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by rossholdway** [comment]
Hello @jgw96 

Unfortunately, this is still an issue and should be reopened. I've set up an example of this issue here.

http://embed.plnkr.co/9mPjLTMkfN7aT0MYdT9U/

Thanks,
Ross
