### ISSUE TITLE
cordova-plugin-googlemaps does not install

### ISSUE THREAD

**Issue by jamesabc** [driftyco/ionic#9491]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**
- Start a new project with `ionic start MyIonic2Project tabs --v2` 
- Run `ionic plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"` as described in the docs (substituting real API keys)
- Copy the exact code from http://ionicframework.com/docs/v2/native/google-maps/ into a new page component.
- `npm run ionic:serve`
- Navigate to the page in the browser
... OR
- `ionic run android --livereload`
- navigate to the page in the emulator

-->

**Current behavior:**
<img width="817" src="https://cloud.githubusercontent.com/assets/22513691/20877056/b214dc98-baf8-11e6-859d-48ca65716d84.png">
<img width="438" src="https://cloud.githubusercontent.com/assets/22513691/20877101/e8e2ce24-baf8-11e6-812b-752906671555.png">

**Expected behavior:**
A map of some kind

**Other information:**

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#849
