### ISSUE TITLE
bug: Android build has "debug" in the output apk file

### ISSUE THREAD

**Issue by pjc2007** [driftyco/ionic#9495]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>This is just a trivial build issue, and seen it discussed elsewhere (https://forum.ionicframework.com/t/change-name-of-android-build-binary/37910), i.e. the output file is always "android-debug.apk".</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1754
