### ISSUE TITLE
Slides - add onInit EventEmitter

### ISSUE THREAD

**Issue by dominikstrasser** [driftyco/ionic#9497]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Until now its quite hard to get notified if a slider is fully initialized (to do something with the idangous swiper instance).

**Expected behavior:**

We should get notified when the slider is initialized

**Other information:**

More infos in the PR --> https://github.com/driftyco/ionic/pull/9479

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by mhartington** [comment]
Unfortunately it didn't make it into the RC5 docs (my fault), but you can do this.

http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced
