### ISSUE TITLE
feat: Add tooltip component

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic#9498]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Add a tooltip component.

Material Design: https://material.google.com/components/tooltips.html#

<img width="400" src="https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsc2t3ZC1BYjh4XzQ/components_tooltips_usage3.png">

iOS: 

<img src="https://cloud.githubusercontent.com/assets/6577830/20891651/64c6702e-bad9-11e6-8600-fd505e89923c.png">

**Comment by mfdeveloper** [comment]
I will love this feature! For while, I'm using [angular2-tooltips] (https://www.npmjs.com/package/angular2-tooltips) npm package!

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#86

**Comment by seiyria** [comment]
Will we hear about it in this thread or elsewhere when it comes up again? Since that link is a 404 for me, I'm guessing it's private.

**Comment by brandyscarney** [comment]
@seiyria We will reopen this issue when we start implementation but please feel free to add any feedback, comments, or questions here. Thanks! :)

**Comment by elineopsommer** [comment]
Any updates on this? It's almost a year ago
