### ISSUE TITLE
Ionicons

### ISSUE THREAD

**Issue by John-Luke** [driftyco/ionic#9500]
I opened a issue a few time ago ([#438](https://github.com/driftyco/ionicons/issues/438)) for know about the continue of the ionicons. I need an answer for this please

**Comment by bensperry** [comment]
Thanks! Yes, we will continue to support and work on Ionicons. It has taken a back seat while our team has been focused on building Ionic 2. Once that is in Final, we will spend some time updating Ionicons.

Stay tuned!
