### ISSUE TITLE
tabs not aligned on android 4.1.2

### ISSUE THREAD

**Issue by theromis** [driftyco/ionic#9502]
Still getting not aligned tabs with rc3
my code for them are:
```
<ion-tabs selectedIndex="0">
  <ion-tab [root]="tab3Root" tabTitle="Room" [tabBadge]="unread_message_count" tabBadgeStyle="danger" (ionSelect)="room()"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Contacts" [tabBadge]="userService.getUnreadPersonalMessages()" tabBadgeStyle="danger"></ion-tab>
  <ion-tab [root]="tab1Root" tabTitle="People"></ion-tab>
</ion-tabs>
```
<img width="318" alt="screen shot 2016-12-05 at 09 13 32" src="https://cloud.githubusercontent.com/assets/3720229/20894645/2329c3ea-bacb-11e6-961d-f37b5dce9906.png">

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! On Android below 4.2 we recommend using crosswalk. The built in webview in Android 4.1.2 does not have the necessary api support to work with Ionic 2. Crosswalk will give you a modern chrome webview even on devices running older versions of Android such as 4.1.2. You can follow the docs [here](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) to learn how to install Crosswalk on your Ionic 2 app.

**Comment by theromis** [comment]
@jgw96 thank you, will try it
