### ISSUE TITLE
docs: V1 Javascript/API documentation links broken

### ISSUE THREAD

**Issue by gumbootphil** [driftyco/ionic#9506]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>In case you don't already know the V1 documentation for the Javascript section are al returning 404 errors eg:

https://ionicframework.com/docs/v1/api/directive/ionSlides/

Keep up the great work!</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hmm looks like you may have an old link. [This](https://ionicframework.com/docs/api/directive/ionSlides/) is the correct link to that v1 component. Where did you get that link from?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#922

**Comment by gumbootphil** [comment]
Hi Justin

I just followed the links on the site:

Documentation / V1 (pulldown menu) / Javascript / Slide Box

Not sure whats changed but its working now. Maybe something was getting cached along the way?

Thanks anyway.

regards

Phil
