### ISSUE TITLE
Modal Close not firing LifeCycle Events on tab

### ISSUE THREAD

**Issue by jayeshanandani** [driftyco/ionic#9510]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a tab set as root. When I push a modal over it and use navPop / dismiss it closes the modal but it doesn't fires the ionViewWillEnter event of Tab due to which the tab data is not reloaded.

**Expected behavior:**
Expecting ionViewWillEnter to fire so as to take the decision to reload data.

**Comment by manucorporat** [comment]
This is the expected behavior, a modal is like an alert, or an actionsheet, it does not fire lifecycle events in the main navigation stack.

Use onWillDismiss() or onDidDismiss() to update your data:
https://github.com/driftyco/ionic/blob/master/src/components/modal/test/basic/app-module.ts#L69-L84
