### ISSUE TITLE
sass color variables preview

### ISSUE THREAD

**Issue by mg1075** [driftyco/ionic#9515]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] feature request

**Current behavior:**
In src/theme/variables.scss, the`$colors` variable defines the default color palette.

![image](https://cloud.githubusercontent.com/assets/2031435/20928771/e5aa427a-bb8c-11e6-810b-ad607ae4187b.png)

**Expected behavior:**
In Visual Studio Code, we don't get color preview for the `$colors` variable unless we trick the editor into thinking the colors are css color properties.

![image](https://cloud.githubusercontent.com/assets/2031435/20928872/5754e5f6-bb8d-11e6-9d66-e79c3581b241.png)

As far as I am aware, no one has made a VS Code plugin to preview SASS color variables. To be able to preview the colors would be great; otherwise, you always need to refer to an outside guide and tools to verify the colors you are working with.

How does the Ionic team recommend dealing with this issue?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So unfortunately there is not much we can do about missing functionality in an IDE. I would recommend checking out some of the sass plugins for vscode or posting an issue on the vscode repo to get this feature built in to vscode itself. Thanks!
