### ISSUE TITLE
Don't include HttpModule by default

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic#9516]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently Ionic imports `HttpModule` (https://github.com/driftyco/ionic/blob/master/src/module.ts#L5) but doesn't use it in sources (only in tests). So, in case if I want to use another http module system, the resulting bundle will contain 2 of them: angular's http and my custom one

**Expected behavior:**
Developers are able to decided which http library to use

**Comment by stalniy** [comment]
@jgw96 when can I expect this to be done? I can create a PR if you will guide in terms what pitfalls needs to be considered

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We have removed the HttpModule from our main NgModule in the master branch and this tweak will be in the next release. (:

**Comment by stalniy** [comment]
Awesome! Thank you!

**Comment by stalniy** [comment]
@angular/http is again a part of ionic's peer dependencies. could somebody please clarify "why?" or reopen this ticket?
