### ISSUE TITLE
Right side menu is shown when left side menu is closed.

### ISSUE THREAD

**Issue by LeBlaaanc** [driftyco/ionic#9517]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Right side menu appears when left drawer is closed, technically the z-index update is occurring during animation.

**Expected behavior:**
Right side menu should not appear when closing left menu, technically side menu should complete closing then the update z-index should occur.

**Steps to reproduce:**
Use the below plnkr to open the sidemenu then close it, ensure your preview is small enough for the two side menus to overlap, you can also slow down animations to 10% to help see the bug.
http://plnkr.co/edit/dqtT0eNoN5xjmonvfMq3?p=preview

**Related code:**
https://github.com/driftyco/ionic/blob/1.x/js/angular/controller/sideMenuController.js#L210

**Other information:**
This is a reintroduction of https://github.com/driftyco/ionic/issues/556 which was technically never fixed I think, only swapped the sides that it flashed.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#57

**Comment by eeschiavo** [comment]
Why this has been closed? the problem is still there..
