### ISSUE TITLE
bug(picker) - overriding $picker-ios-button-text-color no longer works

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#9519]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Currently, when I attempt to override $picker-ios-button-text-color it has no effect.

**Expected behavior:**
The text color would successfully change

**Other information:**
Here is a link to the line causing the issue.
https://github.com/driftyco/ionic/blob/master/src/components/picker/picker.scss#L126

**Ionic info:**

Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed in the `rc.4` release and I released a nightly version if you'd like to try it out sooner:

```
npm install --save ionic-angular@nightly
```

let me know if you find any issues. :)
