### ISSUE TITLE
HTML content in loading controller does not support double curly brace to display variable.

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic#9524]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
HTML template content in loading controller does not support double curly braces to display variable. Wrapping the variable double curly braces results in displaying the double curly braces and the variable name. 

**Expected behavior:**
The variable in double curly braces should be displayed properly as implemented in template html. 

**Related code:**
// create loadingCtrl: LoadingController in constructor
...
let loading = this.loadingCtrl.create({
  spinner: 'hide',
  content: `<div><p>{{variable}}</p></div>`,
  duration: 1000
});

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.4.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#178

**Comment by brassier** [comment]
@jgw96  - looks like this is now a dead link?  I'd like to monitor this feature request.
