### ISSUE TITLE
no-border in header not working

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#9525]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Adding `no-border` to `ion-header` does not remove border.

It happens because the style is wrong here: https://github.com/driftyco/ionic/blob/ac07c6f1244f657496a95945f40a152a1232d960/src/components/toolbar/toolbar.ios.scss#L75

Should be `border-bottom-width: 0`.

![image](https://cloud.githubusercontent.com/assets/230182/20956236/ff0e85a2-bc48-11e6-8c6e-46e7f16cabf8.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by brandyscarney** [comment]
Thanks for letting me know! This will be fixed in the `rc.4` release, and I've also released a nightly if you want to use it sooner:

```
npm install --save ionic-angular@nightly
```

Let me know if you find any issues. :)

**Comment by patrickchoi** [comment]
I'm having trouble with this as well. When testing using ?ionicplatform=ios the shadow disappears. For the modes md or android the shadow returns. I've used both no-border and no-shadow.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v8.2.1
    npm   : 5.3.0 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b

**Comment by senseijames** [comment]
This issue is definitely still open.  Still seeing the issue on

`ionic-angular 3.9.2`
