### ISSUE TITLE
On resume not fired

### ISSUE THREAD

**Issue by sadiq-mc** [driftyco/ionic#9527]
**Ionic version:**
ionic --version    : 2.1.8
cordova --version   : 6.4.0
cordova platform version android :6.0.0

I am stuck with on resume event. I can't get it fired when launching the app from coldstart. And at times it gets fired after few seconds when app is started and opened home page.

```
var app = angular.module('myIonicApp', ['ionic',
    'ngCordova',
    'angular-md5',
    'ngStorage',
    'angularSpinner',
    'ngMessages',
    'ngMap',
    'ngAnimate'
]);

app.run(function($ionicPlatform, $rootScope, $location, $localStorage,
    appConstants) {
	
	$ionicPlatform.ready(function() {
		console.log('$ionicPlatform.ready'); // This works

                document.addEventListener("resume", function() {
                       console.log("resume"); // Fired sometimes and that too after few seconds of ready console.
                  }, false);

                document.addEventListener("pause", function() {
                         console.log("pause"); // This works. Prints all time when I close that app or switch to different app.
                 }, false);
	 });
});
```

Am I missing anything..?

**Comment by graphefruit** [comment]
@sadiq-mc Have you checked if the device-ready is realy fired?
If the `device-ready` is not fired the `$ionicPlatform.ready` won't be executed at all.
Maybe try to wrap your listener on `$(document).ready` or `$(window).load`
Are you using crosswalk?
Greetings
Grapheruit

**Comment by sadiq-mc** [comment]
This is my console log on launching app by tapping app icon.
```
app.config
app.run
/login
$stateChangeStart
$stateChangeSuccess
$ionicPlatform.ready
Received gcm token
```


This is my console on launching app by tapping notification in coldstart.
```
app.config
app.run
/login
$stateChangeStart
$stateChangeSuccess
$ionicPlatform.ready
$cordovaPushV5:notificationReceived
Received gcm token
```

This is my console on switching the apps:
```
app paused
app resumed
```

And am using cordova webview.
Where can I place the $(window).load listener.?

**Comment by graphefruit** [comment]
This would be an approache
```
app.run(function($ionicPlatform, $rootScope, $location, $localStorage,
    appConstants) {
    $( window ).load(function() {
            document.addEventListener("resume", function() {
                       console.log("resume"); 
                  }, false);
  });
//or if you don't have jquery
    window.onload = function () {
          document.addEventListener("resume", function() {
                       console.log("resume"); 
                  }, false);
    }
});
```

Or have a look here: https://cordova.apache.org/docs/en/latest/cordova/events/events.html
```
// example.js file
// Wait for device API libraries to load
//
 document.addEventListener("deviceready", onDeviceReady, false);


// device APIs are available
//
function onDeviceReady() {
    document.addEventListener("pause", onPause, false);
    document.addEventListener("resume", onResume, false);
    document.addEventListener("menubutton", onMenuKeyDown, false);
    // Add similar listeners for other events
}

function onPause() {
    // Handle the pause event
}

function onResume() {
    // Handle the resume event
}
```

**Comment by sadiq-mc** [comment]
I couldn't able to resolve this issue as the 'resume' event didn't fire as expected... 
I was integration phongap-plugin-push into my project and detected the launch by 'notificationReceived' of the plugin.

I am wondering why the 'resume' event fired after few seconds and that too some times on app launch... but fires as expected on switching back to the app from background.

**Comment by graphefruit** [comment]
@sadiq-mc Have you tried to install a fresh setup and adding this events? Just to make sure your application doesn't do anything strange.

**Comment by sadiq-mc** [comment]
Not yet.. will try it and will update..

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#55

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#56
