### ISSUE TITLE
Plugin behavior delayed, onDeviceReady trigger problem ?

### ISSUE THREAD

**Issue by crouti** [driftyco/ionic#9528]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In iOs : plugin behavior only triggered when form field touched.... yes it's strange.
For example, i touch a link that would normally open with InAppBrowser plugin, and the link opens when, on another page, the form field is clicked (touched). Same with socialsharing, sharing a post, then go the form touch the first field, then only the social sharing shows up.... heg ???

**Expected behavior:**

I would expect that plugin InAppBrowser, SocialSharing or Keyboard for example (but all plugin installed behave the same) would behave "normally" as my app did before updating ionic, ionic-cli and plugins

**Steps to reproduce:**

Sorry, it's Difficult, but very annoying, for example the console log plugin does not work at all, so debugging is hard

**Other information:**
I already spent hours on this, reinstalling plugins, ionic, ionic-cli, making new project, npm update....

plugins installed:
```
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-google-analytics 1.7.2 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 1.3.2
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.2.1
Xcode version: Xcode 8.1 Build version 8B62
```

Thanks a lot for any clue!

**Comment by graphefruit** [comment]
@crouti I don't get the behavior right but, you can debug your app via Safari (iOS) or Google-Chrome (Android).
So just deploy it and attach to your device, so atleast you can see whats going on and try to trigger the commands yourself.

If I get it right: after you said, the logic is just triggered after clicking on another element, I'd assume that your digest cycle isn't executed.
Maybe try to execute this after your click: `$scope.$apply()` to be sure that the $digest-cycle is triggered.

Greetings
Graphefruit

**Comment by crouti** [comment]
Thanks @graphefruit for your answer, now i use safari to remotely debug and here is what i see in console:
```
[Error] Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy. (x8)
[Error] Failed to load resource: The requested URL was not found on this server. (angular-cache.min.map, line 0)
[Error] Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy. (x1138)
[Error] TypeError: window.requestFileSystem is not a function. (In 'window.requestFileSystem(Helpers.getCordovaStorageType(ImgCache.options.usePersistentCache), 0, _gotFS, _fail)', 'window.requestFileSystem' is undefined)
	init (imgcache.js:585)
	(fonction anonyme) (ionic-img-cache.min.js:1:233)
	(fonction anonyme) (ionic.bundle.js:53329)
	onPlatformReady (ionic.bundle.js:2491)
	fire (cordova.js:801)
	(fonction anonyme) (cordova.js:231)
```

The x1138 is an infinite loop occuring when launching my app (can see why ?...!) and when i touch the main iphone button to stanby the app the last line is outputted with `TypeError: window.requestFileSystem`

I suppose the error with angular.cache.min.map is not important, so i believe my problem is this infinite loop...
Do you have any idea ?
Thanks a lot!

**Comment by graphefruit** [comment]
Hey @crouti 
Have you installed the cordova-file-plugin? http://ionicframework.com/docs/v2/native/file/

I've inserted my own filesystem, so maybe you could try to log if the filesystem exists on your side:

```
var windowObj:any = window;
console.log(windowObj.requestFileSystem);
console.log(windowObj.webkitRequestFileSystem);
console.log(windowObj.mozRequestFileSystem);
```

Greetings
Graphefruit

**Comment by crouti** [comment]
Ok, got it, replacing my current CSP with 
`<meta http-equiv="Content-Security-Policy" content="default-src gap://ready file://* *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *">`

made it ! :)
Thank you
