### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by azachar** [driftyco/ionic#9532]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I am getting this error stacktrace when a view is changed

```js
angular.js:14110 TypeError: Cannot read property 'name' of null
    at getUiViewName (angular-ui-router.js:4152)
    at updateView (angular-ui-router.js:4035)
    at angular-ui-router.js:4005
    at Scope.$broadcast (angular.js:18239)
    at angular-ui-router.js:3369
    at processQueue (angular.js:16606)
    at angular.js:16622
    at Scope.$eval (angular.js:17913)
    at Scope.$digest (angular.js:17727)
    at Scope.$apply (angular.js:18021)
```

It looks like it is a bug of ui-router, https://github.com/angular-ui/ui-router/issues/1901#issuecomment-265406740

But it seems that is related to this line of ionic that sets null which cause ui-router to fail

https://github.com/driftyco/ionic/blob/1.x/js/angular/controller/navViewController.js#L44

Could you please advice?

Thanks,
Andrej

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#54
