### ISSUE TITLE
Feature Request: detect if user is going 'back' in `ionViewCanLeave` lifecycle method

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic#9533]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I'd like to be able to detect if the user is popping a page off the stack in the `ionViewCanLeave` method. This is so I can distinguish between users pressing the Back button (either soft or hard button) and pushing another view. I'd like to do this so that if a user is not yet finished filling out a form, and tries to go back, a confirmation pop-up is revealed.

I'm also open to any other ideas on how to achieve this. I [asked a question in the forum](https://forum.ionicframework.com/t/ionic-2-detect-navigation-direction-in-ionviewcanleave-lifecycle-method/71982) but have yet to receive a response, so I'm not sure if this can be done or not.

**Comment by manucorporat** [comment]
@fiznool I agree this feature would be useful

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#179

**Comment by ross-nordstrom** [comment]
I'm getting a 404 on that link @jgw96 -- was this feature implemented?
