### ISSUE TITLE
feat: Existing methods do not return the current page in

### ISSUE THREAD

**Issue by rmagno885** [driftyco/ionic#9540]
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>There is no way to get the current page in Ionic2.
Ideal would be a getCurrentPage() in NavController.</span>

<span is-issue-template></span>

**Comment by manucorporat** [comment]
Use `getActive()`

**Comment by anagram3k** [comment]
On android, getActive() don't work; Always return "t"

**Comment by derasmus** [comment]
+1
