### ISSUE TITLE
Ionic2 - Browser - IE/FireFox/Safari - Error/Crash

### ISSUE THREAD

**Issue by graphefruit** [driftyco/ionic#9541]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If you run `ionic serve browser` or `ionic run browser` and open it on IE/FireFox/Safari, the Application doesn't load, in Chrome the application loads

**Expected behavior:**
The page sould load on all browsers.

**Steps to reproduce:**
1. ionic start newProject --v2
2. ionic platform add browser
3. ionic serve browser
OR
4. ionic run browser
5. Open console to see the error.

**Other information:**
Ionic run browser:
![image](https://cloud.githubusercontent.com/assets/6260244/20986416/ec760494-bcc8-11e6-8c9d-98014df7827c.png)

Ionic serve browser:
![image](https://cloud.githubusercontent.com/assets/6260244/20986461/15287f2a-bcc9-11e6-9a76-620da9a5b754.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

Greetings Graphefruit

**Comment by mhartington** [comment]
The browser platform is actually a cordova target, and is not a fully complete cordova platform.
This is kind of to be expected. If you run `ionic serve`, does everything load correctly?

**Comment by graphefruit** [comment]
@mhartington Sadly not:
Firefox:
![image](https://cloud.githubusercontent.com/assets/6260244/21067355/f7e970c4-be6a-11e6-86d8-713a67185efe.png)
IE:
![image](https://cloud.githubusercontent.com/assets/6260244/21067364/08c3ac66-be6b-11e6-969c-62ff591f2cb5.png)

Specialy recgonizeable - FireFox throws other errors then IE
I've updated the scripts to 0.46, didn't help

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed
```

**Comment by mhartington** [comment]
This is known issue for IE. We're not focusing on supporting IE right now, but will gladly accept any PRs
