### ISSUE TITLE
ion-footer does not change ion-content's margin-bottom

### ISSUE THREAD

**Issue by jstoup111** [driftyco/ionic#9542]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If `<ion-footer>` content changes after a view is loaded, `<ion-content>`'s margin does not adjust to factor the change ending up with hidden content.

**Expected behavior:**

`<ion-content>`'s margin would change dynamically with the height of `<ion-footer>`.

**Steps to reproduce:**

**Related code:**

```
http://plnkr.co/edit/fvwbCIKdQGabMVwm6muk?p=preview
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.8.6 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 8.1 Build version 8B62 
```

**Comment by mhartington** [comment]
Hi there. This is covered in the docs

You need to call resize on the content.

http://ionicframework.com/docs/v2/api/components/content/Content/#resize

http://plnkr.co/edit/UuHavx3pQ77MYOnQXjm7?p=preview

**Comment by himalayaahuja** [comment]
I tried that calling content.resize(); after toggling footer but nothing happens ...
