### ISSUE TITLE
after Ionic build , the fonts dir don't created, this caused ionic icon can't show

### ISSUE THREAD

**Issue by lazy-ape** [driftyco/ionic#9544]
Hi, I have a problem about icon. Sometime after ionic build , the `fonts` directory don't created in `www`, this cause icon can't show on app. The directory like this after build:
![7ec0 tmp](https://cloud.githubusercontent.com/assets/20139666/20994201/f409db70-bd29-11e6-8442-4d6929485fcb.png)
Don't has the `fonts` directory. 
The icon show on app like this:
![4e6b tmp](https://cloud.githubusercontent.com/assets/20139666/20994168/d02c67ae-bd29-11e6-9028-954d191e7b66.png)
  
Not everytime like this , but often . I don't know  whether it is a network problem, I'm in china . I user the `ionicons` v3.0.0, and the ionic info is this:

Your system information:
 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.30
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.6.0

Look forward to your reply！

**Comment by mhartington** [comment]
Please update you app-scripts version to the latest from npm.
This has been fixed.

https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md
