### ISSUE TITLE
How to make a menu in child page.

### ISSUE THREAD

**Issue by NeoLSN** [driftyco/ionic#9546]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1. If code like this
```
<ion-menu [content]="groupDetailContent" side="right" id="groupDetailMenu">
  <ion-content>
    <ion-list>
      <button ion-item menuClose (click)="openGroupEdit()">
        <ion-icon name="create" item-left></ion-icon>
        <h2>Edit Group</h2>
      </button >
    </ion-list>
    ...
  </ion-content>
</ion-menu>
<ion-content #groupDetailContent>
  <ion-header>
    <ion-navbar>
      <ion-title>
        Group Overview
      </ion-title>
      <ion-buttons end>
        <button ion-button icon-only (click)="toggleMenu()"> <!-- menuToggle="groupDetailMenu" -->
        <ion-icon name="settings"></ion-icon>
      </button>
      </ion-buttons>
    </ion-navbar>
  </ion-header>
  <ion-content>
   ...
  </ion-content>
</ion-content>
```
It will look like this - the nav bar overlap status
![image](https://cloud.githubusercontent.com/assets/5782106/21001694/d09eff66-bd5c-11e6-95d5-c71dbd076429.png)
But the menu is correct.
![image](https://cloud.githubusercontent.com/assets/5782106/21001705/d9ee96b2-bd5c-11e6-86d2-49a924846f90.png)

2. If code like this
```
<ion-menu [content]="groupDetailContent" side="right" id="groupDetailMenu">
  <ion-content>
    <ion-list>
      <button ion-item menuClose (click)="openGroupEdit()">
        <ion-icon name="create" item-left></ion-icon>
        <h2>Edit Group</h2>
      </button >
    </ion-list>
    ...
  </ion-content>
</ion-menu>
<ion-header>
... header content
</ion-header>
<ion-content #groupDetailContent>
...
</ion-content>
```
It will look like this - the nav bar is right, but the first item of menu can not show.
![image](https://cloud.githubusercontent.com/assets/5782106/21002371/6ee7f40e-bd60-11e6-968f-cd76fdf8b07f.png)

3. The button will not show if set 'menuToggle' attribute.
```
  <ion-buttons end>
    <button ion-button icon-only (click)="toggleMenu()"> <!-- menuToggle="groupDetailMenu" -->
    <ion-icon name="settings"></ion-icon>
  </button>
```

**Expected behavior:**
1. The Title bar can be under the status bar.
2. The menu can show all items.
3. Let button can use 'menuToggle' attribute.

**Steps to reproduce:**
1. Create a home page.
2. Create a child page which will be opened by home page.
3. Try to make a menu in child page html file.

**Other information:**
I can not find any example about how to make a menu in child page, even in ionic-conference-app.
Can you provide an example about that?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.4.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by mhartington** [comment]
Please take a look at the starter project for sidemenus.

https://github.com/driftyco/ionic2-starter-sidemenu/tree/master/src

The layouts you are using are not the correct way to use the menu.

**Comment by NeoLSN** [comment]
My question is how to make a menu in second page.
Open app > nav push a page.
1. How to set a menu in this page.
2. How to set menu button click event.

**Comment by ehdwns980416** [comment]
I hope this will help you.

https://forum.ionicframework.com/t/solved-child-page-specific-menu/76412/7
