### ISSUE TITLE
In Beta 1 tab titles don't get translated after dynamic language change

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic#955]
Hi, 

first of all I want to congratulate you to your first beta. It just awesome! Unfortunately I found that there seems to be an old problem there again. When I try to change the language via angular-translate then the tabs don't get updated. Carry On!

**Comment by psgganesh** [comment]
I use the same in  below way
```html
<ion-tab title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111044/eb9e81ca-8936-11e5-8714-c473b7739424.png)

But when it is 
```html
<ion-tab translate="coffee_title_label" title="{{ 'coffee_title_label' | translate }}">
```
![image](https://cloud.githubusercontent.com/assets/2221525/11111034/cdaa8790-8936-11e5-9408-043d322f0e02.png)

I referred the below codepen example
http://codepen.io/andrewmcgivery/pen/tqymb

Can you let me know, what am doing wrong here !

**Comment by azachar** [comment]
I have similar issue on 1.2.4 ```ion-tab(title='{{"xxx"|translate}}')``` doesn work. Could you please suggest what to do? Thanks
