### ISSUE TITLE
Opening time really slow

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#9554]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The opening of the app is very slow.
My app is taking around 17 seconds to open.
Same situation for a blank fresh app. Around 15 seconds.

**Expected behavior:**

I expect to open in max 7-8 seconds as first time otherwise the user may think the app is broken and close it.

**Steps to reproduce:**
1. ionic start whateva --v2
2. build it
3. test on device with android 4

**Other information:**

Ionic forum question:
https://forum.ionicframework.com/t/ionic-2-app-opening-really-slow/72533/5

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

Do you plan to fix this in future release?

Thank you!

**Comment by zakton5** [comment]
1+ Same issue, but not as much time. The deviceready event seems to be taking too long to fire. Could it have something to do with the plugins?

**Comment by FrancescoMussi** [comment]
Thanks for the feedback.
Which version and platform are you using?
On Android 6 it is taking some 7-8 seconds. Still acceptable.
The issue is very evident on Android 4 where even a blank app takes 15 seconds to open.

**Comment by zakton5** [comment]
I've been using iOS. Using an actual device (iPhone 6) it takes around 7-10 seconds.

**Comment by graphefruit** [comment]
I think this topic is related to #6776

**Comment by mhartington** [comment]
Closing in favor of #6776
