### ISSUE TITLE
Android missing Roboto font styles

### ISSUE THREAD

**Issue by ekrapfl** [driftyco/ionic#9562]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

ionic-app-scripts version: 0.0.46

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Roboto font is missing when running on an Android device.  Roboto is set as the default font-family through Ionic defaults, but the scss file for the font definition is not included anywhere (Roboto.scss), so the font falls back to a different default all the time.  I am able to see this using even the stock Ionic 2 starter tutorial project.

**Expected behavior:**
Roboto font and accompanying scss should be included when running on an Android device.

**Steps to reproduce:**
Start and Ionic 2 project using the tutorial template 
```
ionic start myTutorial tutorial --v2
ionic platform add android
ionic run android
```

Note that the Roboto font is not applied.  It is the first font listed, but there is no `@font-face` declaration included for it.  The font files do exist in the generated .apk, as does the roboto.scss file (but no one imports it).

We can potentially work around this issue by simply including the scss file manually, but we were concerned that it may be a larger issue, and there may be other things that are not being included by default at this point.

**Other information:**

This issue stemmed from this commit: [78122c551d9703bb9be4fca4705b691a9bbdfbdf](https://github.com/driftyco/ionic/commit/78122c551d9703bb9be4fca4705b691a9bbdfbdf)

Old structure:

- ionic.scss and ionic.md.scss (Removed, used to be included via app.md.scss)
   - components.md.scss (Removed)
      - roboto.scss

New structure:

- ionic.build.dark.scss and ionic.build.default.scss  <--- Nothing includes these by default
   - ionic.components.scss
      - roboto.scss

Importing ionic.build.default.scss or ionic.components.scss does not seem to work, and sometimes causes the android build to hang forever on the cleancss step and never finish.

Including only the roboto.scss seems to work, but we are unsure if there are other things that used to be included that are now missing.

**Ionic info:**
```
Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Closing in favor of 

https://github.com/driftyco/ionic-app-scripts/issues/448

**Comment by mikemichaelis** [comment]
asdf

**Comment by mikemichaelis** [comment]
I upgraded to the latest ionic & cordova and this problem was resolved.
