### ISSUE TITLE
ionic 2 rc3 can any have image lazy load

### ISSUE THREAD

**Issue by ykonstant** [driftyco/ionic#9564]
Can ionic 2 rc3 support image lazy load
I used ng2-lazyload-image, but its not working
![screen shot 2016-12-09 at 12 54 05 pm](https://cloud.githubusercontent.com/assets/24272414/21041039/92474900-be0e-11e6-9784-d59add89eaad.png)

I have this screen with ion-card, as [virtualScroll] not working in ion-card
So when i changed segment or refresh page, it show images fluctuations, and create bad effects.

this is my code:- 
<ion-card class="custom" *ngFor="let all of posts" tappable (tap)="all.type == 3 ? detailPage($event,all) : ''">
                <div class="dashbg" [ngStyle]="{'background-image': 'url(' + bs.setImage(all.image, 'trip', 'trip') + ')'}"></div>
                
                <ion-item>
                    <ion-avatar item-right [ngClass]="{customa: all.going_picture != '' && all.going_picture != null}">
                        <div class="img" [ngStyle]="{'background-image': 'url(' + bs.setImage(all.picture, 'profile_pictures') + ')'}"></div>
                    </ion-avatar>

                    <ion-avatar item-right class="customb" *ngIf="all.going_picture != ''">
                        <div class="img" [ngStyle]="{'background-image': 'url(' + bs.setImage(all.going_picture, 'profile_pictures') + ')'}"></div>
                    </ion-avatar>
                    <h2 class="post-title">{{all.title}}</h2>
                    <p class="post-address" *ngIf="all.type == 3 ">
                        <ion-icon class="custom" name="md-pin"></ion-icon>
                        {{all.address}}
                    </p>
                </ion-item>
            </ion-card>

**Comment by mhartington** [comment]
Hi there. Since this is a question and not an actual issue with the framework, I'm going to close it. Please use the ionic forum or join our slack if you have a question, as stated in our issue template.
