### ISSUE TITLE
Pressing Tabkey dereferences undefined variable in rc3@nightly

### ISSUE THREAD

**Issue by ataraxus** [driftyco/ionic#9568]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you have two input fields and press tab to switch between them you get:

```
polyfills.js:3 Uncaught TypeError: Cannot read property '_dom' of undefined
    at cssClass (\C:\git\tabtest\node_modules\ionic-angular\util…:150)
    at enableKeyInput (\C:\git\tabtest\node_modules\ionic-angular\util…:173)
    at HTMLDocument.keyDown (\C:\git\tabtest\node_modules\ionic-angular\util…:165)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at HTMLDocument.invoke (polyfills.js:3)
```

**Expected behavior:**
switch to the next input without error

**Related code:**
`ionic start tabtest --v2 blank`
install rc nightly and app-scripts 0.0.46 then add this to `home.ts`
```
<ion-list inset>
      <ion-item class="loginInput">
        <ion-input type="text"   placeholder="Nickname"></ion-input>
        <ion-icon color="danger"></ion-icon>
      </ion-item>

      <ion-item class="loginInput enablelastline">
        <ion-input type="password" placeholder="Passwort"></ion-input>
        <ion-icon color="danger" ></ion-icon>
      </ion-item>
    </ion-list>
    <button ion-button full color="light" large type="submit">Anmelden</button>

```
it actually breaks also without input fields, just press tab in a vanilla app with rc3@nightly
**Other information:**

```

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3-201612090356
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by adamdbradley** [comment]
Good catch and thank you for testing nightly! Should be fixed now and we'll release another nightly soon, thanks!
