### ISSUE TITLE
NavBar Icon Diminishing In Ionic v2 Project

### ISSUE THREAD

**Issue by niilante** [driftyco/ionic#9569]
![small sear button](https://cloud.githubusercontent.com/assets/10741609/21050421/89201d4e-be12-11e6-9430-676b24379972.png)
![explore html](https://cloud.githubusercontent.com/assets/10741609/21050422/89227576-be12-11e6-88f7-5dcb49138451.png)
![explore ts](https://cloud.githubusercontent.com/assets/10741609/21050420/891e7c96-be12-11e6-8c19-d1e1facf3b9d.png)

Search Button diminishing in and cannot find any problem yet. Please Any suggestions @Ionitron and the community in general.

**Comment by NeoLSN** [comment]
icon-only

**Comment by manucorporat** [comment]
Use:
```
<button ion-button icon-only>
 // icon
</button>
```

 Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
