### ISSUE TITLE
deviceready doesn't fire with cordova-plugin-network-information and cordova-plugin-device

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic#9570]
Hi

`deviceready` doesn't fire or fires very late in my ionic app when I run it on my iOS 10 device or emulator with `ionic run ios --device -lcs`.

If I remove the plugins cordova-plugin-network-information and cordova-plugin-device.

I removed all the plugins with ionic plugin rm ..., deleted the content of the plugins/ directory and reinstalled them. I also removed and reinstalled the ios platform with ionic platform rm/add ios.

I am stuck with this.

I am using ionic 1, and the last ionic CLI.

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by mhartington** [comment]
Closing as you did not fill out the github issue template. Please open a new issue and fill out the issue template.

**Comment by louisdoe** [comment]
ok! done : https://github.com/driftyco/ionic/issues/9575
