### ISSUE TITLE
Native SMS.send().then()..catch() promise throws error

### ISSUE THREAD

**Issue by barocsi** [driftyco/ionic#9572]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Native SMS.send() falls into error after sms is sent.
```
SMS.send(a,b)
      .then(() => {
        // should be active
      })
      .catch((error: any) => {
          // THIS IS ACTIVE, error echoes "OK"
          })
        }
      );
```
**Expected behavior:**
code above

**Steps to reproduce:**
code above

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-native#858
