### ISSUE TITLE
deviceready doesn't fire with cordova-plugin-network-information and cordova-plugin-device

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic#9575]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

`deviceready` doesn't fire or fires very late in my ionic app when I run it on my iOS 10 device or emulator with `ionic run ios --device -lcs` 

I tried removing all the plugins with `ionic plugin rm ...`, deleted the content of the plugins/ directory and reinstalled them. I also removed and reinstalled the ios platform with ionic platform rm/add ios.

However if I remove the plugins `cordova-plugin-network-information` and `cordova-plugin-device`, deviceready` fires normally.

**Expected behavior:**
̀deviceready` should fire within 2 seconds with these plugins.

**Steps to reproduce:**

run `ionic run ios -lcs` on iOS 10 device or emulator, with the plugins listed below.

**Related code:**

```
```

**Other information:**
Installed plugins
```
$ ionic plugin
cc.fovea.cordova.purchase 6.0.0 "Purchase"
cordova-plugin-admobpro 2.24.0 "AdMob Plugin Pro"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-datepicker 0.9.2 "DatePicker"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-globalization 1.0.4 "Globalization"
cordova-plugin-google-analytics 1.7.1 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
ionic-plugin-deploy 0.6.5 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.0.8 "OneSignal Push Notifications"
```

**Ionic info:**:

```
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#867
