### ISSUE TITLE
Ionic 2 Native Push lacks Support for Actions

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#9579]
Hi,

It seems that the current version of push plugin in Ionic Native lacks the support of Actions in push notifications.

I am referring to:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

The action buttons set from server appear perfectly with notification. But when clicked they throw error in console:

Uncaught TypeError: Cannot read property 'Reply' of undefined

(Reply is the function that I want to be called when Reply button is clicked)

The documentation of the plugin suggests that while sending push notification with action buttons we should provide the callback (like they have used in app.emailGuests in the example code).

If there is a way to handle in current version, can anyone please guide how?

If not can it be added?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#868
