### ISSUE TITLE
NavController.pop() dismisses all pages and reach a black screen

### ISSUE THREAD

**Issue by sereysethy** [driftyco/ionic#9580]
**Ionic version:**
[x] **2.0.0-rc.3** when running on `iOS` device and simulators.

**I'm submitting a ...**
[x] bug report

**Current behavior:**

Using `NavController.pop()` redirect back to previous pages recursively until reaching a black screen.

**Expected behavior:**

Using `NavController.pop()` should only dismiss the current page (component).

**Steps to reproduce:**
Just create two pages 1 and 2 and using `NavController.push(page1)` in `page1` to push `page2`, and then in `page2`, using `NavController.pop()` to dismiss the current page.

**Comment by manucorporat** [comment]
Can you try against nightly?

```
npm install ionic-angular@nightly --save
```

**Comment by sereysethy** [comment]
Continued from previous post.

This is snippet of my component, the buggy code

```TypeScript
save() {
  let self = this;
  
  switch (this.action) {
    case "update":
      this.roleService.updateRole(this.role).then(success =>{
        self.navCtrl.pop();
      },
        reject => {
          self.permissionDeniedAlert.show( "You can't modify role");
        });
      break;
    case "create":
      this.roleService.createRole(this.role).then(success =>{
        self.navCtrl.pop();
      },
        reject => {
          self.permissionDeniedAlert.show( "You can't create role");
        });
      break;
    default:
      break;
  }
}
```

The problem seems to be resolved when I moved `this.navCtrl.pop()` out of promise return.
```TypeScript
save() {
  let self = this;
  
  switch (this.action) {
    case "update":
      this.roleService.updateRole(this.role).then(success =>{
        //self.navCtrl.pop();
      },
        reject => {
          self.permissionDeniedAlert.show( "You can't modify role");
        });
      this.navCtrl.pop();
      break;
    case "create":
      this.roleService.createRole(this.role).then(success =>{
        //self.navCtrl.pop();
      },
        reject => {
          self.permissionDeniedAlert.show( "You can't create role");
        });;
      this.navCtrl.pop();
      break;
    default:
      break;
  }
}
```

**Comment by manucorporat** [comment]
Somehow you were calling pop() several times. Nightly prevents the black screen and prints a warning instead.

Add `console.log` in each promise, to figure out if you were calling `nav.pop()` more than once.

**Comment by sereysethy** [comment]
No. pop() was called exactly one time. Can you explain me why this problem does not happen on Android or on Browser?

**Comment by manucorporat** [comment]
Can you provide a small repo that reproduces the issue? I can't reproduce it.

>No. pop() was called exactly one time.

How have you tested that?

>Can you explain me why this problem does not happen on Android or on Browser?

I can't. I guess `this.roleService.updateRole(this.role)` is probably behaving different in Safari. But I can't know.

**Comment by manucorporat** [comment]
I only can imagine two scenarios:

```
pop();
push();
```

or:
```
push();
pop();
pop();
```

**Comment by sereysethy** [comment]
I will reproduce the problem again by writing a simple components which do `push()` and then call `pop()` in a promise. This time the promise will be simple. If the problem will not appear then I can presume that my program (promise) is buggy.

I the mean time, I also do `console.log()` and I still cant find the problem. Because it behaves correctly on Safari browser, but not on `Ionic View` and `iOS simulator or real device`. I will post a new comment soon.

**Comment by sereysethy** [comment]
I debug my program again, actually it is not from the `NavController.pop()` but it is a bug of ionic on iOS. The problem is caused by an `ionic module` I presume.

I set up a git repo that you can run to reproduce the problem.

Repo: [https://github.com/sereysethy/testapp.git](https://github.com/sereysethy/testapp.git)

In the program, I simply created an ionic module (`dummy.module.ts`) and create a page that will push another page (a component of a module). The component of the module does nothing beside `push()` another detail dummy page. In the detail dummy page, I created a button which will call a function (`tapMe()`) when I click on it. The function will print a string `I call TapMe` to `console.log`. Here that is the problem appears, the click event is fired twice. The text is displayed twice. The problem only appears on iOS simulator, iOS real device & Ionic View.

```shell
2016-12-11 21:44:51.123 testapp[3771:105263] I call TapMe
2016-12-11 21:44:51.123 testapp[3771:105263] I call TapMe
```

In my real application, the click event is fired 12 times. That is the reason `NavController.pop()` were called several time. I cant explain why event is fired 12 times... but the number of times is not important, the expected behavoir is that the click event should be fired once.
