### ISSUE TITLE
Ionic v2 native plugin IBeacon doesn't work with cordova not defined error

### ISSUE THREAD

**Issue by afgallo** [driftyco/ionic#9587]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Followed this doc closely (https://ionicframework.com/docs/v2/native/ibeacon/) but the plugin doesn't work. I get erros saying **"can't find cordova variable"** or **"cordova is not defined"**. Note that this happens debugging in the browser, emulator and the actual device!

**Expected behavior:**
Plugin should work as per documentation.

**Steps to reproduce:**

1. npm install ionic-native --save
2. ionic plugin add cordova-plugin-ibeacon
3. ionic run ios -l -s -c --device

**Related code:**

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { IBeacon } from 'ionic-native';

@Component({
    selector: 'page-logger',
    templateUrl: 'logger.html'
})
export class LoggerPage {
    uuid: string = "Loading ...";

    constructor(public navCtrl: NavController) {
    }

    ionViewDidLoad() {
        const beaconRegion = IBeacon.BeaconRegion('demo', 'C96A588F-AE75-475A-8FF5-4CD72378728A');

        // Request permission to use location on iOS
        IBeacon.requestAlwaysAuthorization();
        // create a new delegate and register it with the native layer
        const delegate = IBeacon.Delegate();

        IBeacon.startRangingBeaconsInRegion(beaconRegion).then(
            () => console.log('Native layer recieved the request to ranging'),
            error => console.error('Native layer failed to begin ranging: ', error)
        );

        delegate.didRangeBeaconsInRegion().subscribe(
            data => {
                console.log('didRangeBeaconsInRegion: ', data);
            },
            error => console.error()
        );
    }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by ghenry22** [comment]
//handle non-typed legacy plugin stuff
declare var cordova: any;
declare var window: any;

put this just under your imports and try again

**Comment by ghenry22** [comment]
this isn't really an ionic issue, should be under the ionic-native project or more appropriately ask for some help on the ionic forums as github should really be for bugs

**Comment by afgallo** [comment]
OK thanks @ghenry22. I think you were on the money with regards the livereload issue.
