### ISSUE TITLE
UX: ItemSliding: background remains white

### ISSUE THREAD

**Issue by Richard87** [driftyco/ionic#9588]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The background behind sliding items are white, instead of the button's color

**Expected behavior:**
the background should use the last buttons color

**Steps to reproduce:**
http://plnkr.co/edit/lqcwxzlQ6ugExdSXx0r1?p=preview
```
<ion-content >
  <ion-list>
    <ion-item-sliding #item>
      <ion-item>
        Item
      </ion-item>
      <ion-item-options side="left">
        <button ion-button color="danger" (click)="share(item)">Share</button>
      </ion-item-options>
  
      <ion-item-options side="right">
        <button ion-button (click)="unread(item)">Unread</button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
</ion-content>
```

**Ionic info:**

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.1
Xcode version: Not installed
```

![ionic2 bug](https://cloud.githubusercontent.com/assets/5749715/21080817/3726f154-bfb9-11e6-8b32-303e629ab3bb.png)

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Unfortunately your plunker seems to just be our default one, did you save the plunker once you finished it? Also, from your picture Im seeing that the background is the button color. Could you explain this issue a little more?

**Comment by Richard87** [comment]
Hi, what probably didnt come clear out in the picture, is that I have already slided the item 50% to the right,and only the button (10%-ish) is red, while it should be more like the screenshot under, where 50%-ish is colored red (Updated plunker: http://plnkr.co/edit/lqcwxzlQ6ugExdSXx0r1?p=preview )

**Comment by brandyscarney** [comment]
This is actually the correct behavior by default. If you'd like the button to expand as you drag it, you should add `expandable` to the button. The source for that demo is here: https://github.com/driftyco/ionic/blob/master/demos/src/item-sliding/page.html#L44-L51

So you would want:

```
<ion-item-options side="left">
  <button ion-button color="danger" expandable (click)="share(item)">Share</button>
</ion-item-options>
```
