### ISSUE TITLE
unable to install ionic 2

### ISSUE THREAD

**Issue by carlcollins35** [driftyco/ionic#9590]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

carlcollins35@carlcollins35-Satellite-L700:~$ sudo npm install -g ionic@beta
[sudo] password for carlcollins35: 
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
- archiver node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver
- file-utils node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/node_modules/file-utils
- cordova-lib node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib
- aliasify node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/aliasify
- browserify-transform-tools node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/aliasify/node_modules/browserify-transform-tools
- falafel node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/aliasify/node_modules/browserify-transform-tools/node_modules/falafel
- cordova-common node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-common
- cordova-js node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js
- browserify node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify
- browser-pack node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/browser-pack
- crypto-browserify node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/crypto-browserify
- create-hash node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/crypto-browserify/node_modules/create-hash
- diffie-hellman node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/crypto-browserify/node_modules/diffie-hellman
- insert-module-globals node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/insert-module-globals
- lexical-scope node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/lexical-scope
- astw node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/insert-module-globals/node_modules/lexical-scope/node_modules/astw
- module-deps node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps
- detective node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/node_modules/detective
- shasum node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/shasum
- syntax-error node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/syntax-error
- cordova-serve node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-serve
- express node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-serve/node_modules/express
- send node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-serve/node_modules/express/node_modules/send
- init-package-json node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/init-package-json
- npm-package-arg node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/init-package-json/node_modules/npm-package-arg
- npm node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm
- request node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/request
- http-signature node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/http-signature
- request node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/request
- tar node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/tar
- fstream node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/tar/node_modules/fstream
- xcode node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/xcode
- tiny-lr-fork node_modules/ionic/node_modules/ionic-app-lib/node_modules/tiny-lr-fork
- noptify node_modules/ionic/node_modules/ionic-app-lib/node_modules/tiny-lr-fork/node_modules/noptify
/usr/local/lib
└── (empty)

npm WARN In ionic@2.1.0-beta.3 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.0-beta.3 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.0-beta.1
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic@beta"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/carlcollins35/npm-debug.log
npm ERR! code 1

**Comment by gustavobatista901** [comment]
Hey @carlcollins35, I think there is no ionic@beta anymore, you can install ionic by running: `npm install -g ionic` the cli is the same for both ionic 1 and 2. Before you install the ionic cli, update your node version to 6.9.x and npm to 3.10.x and everything should be fine.

**Comment by carlcollins35** [comment]
Thanks very much

**Comment by jgw96** [comment]
Hello all! @gustavobatista901 is correct, you should not use the beta cli anymore. Sorry for the confusion!
