### ISSUE TITLE
Typescript ^2.1.0 doesn't work on any devices

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic#9591]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When installing the latest typescript vesion 2.1.4, when I use ionic run android or ionic run windows the white screen of doom appears
.
After uninstalling the latest version and going back to typescript 2.0 it works again. 
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Didn't bother to do that seeing as it worked when uninstalling the latest version of Typescript

```
insert the output from ionic info here
```

**Comment by graphefruit** [comment]
@Bandito11 it would be realy intersting which ionic version you're using `ionic info`
Have you tried it with the starter project?
`ionic start test --v2` ?
Greetings

**Comment by Bandito11** [comment]
Yes I am using v2.

ionic info: 


Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed

**Comment by graphefruit** [comment]
@Bandito11 have you tried it with the starter project? Or is it actually a grown project?

**Comment by Bandito11** [comment]
tried it with the starter project.

**Comment by Bandito11** [comment]
the ionic info is the same .

**Comment by jgw96** [comment]
Hello @Bandito11 ! Thanks for opening an issue with us. So first, we do not recommend using TS 2.1 just yet as we have not tested this yet and have not yet updated the framework itself to 2.1, although we are in the process of doing this as i type this. Do you get any errors in the console when this happens?

**Comment by Bandito11** [comment]
Been trying to run the live reload when running on my device but it won't let me. It never connects to the host.

**Comment by jgw96** [comment]
Do you get any errors when doing `ionic serve` ?

**Comment by Bandito11** [comment]
Nope.

**Comment by jgw96** [comment]
Ahh ok, so actually we just ran into this internally. We are investigating it now. It only happens on an NGC build which would explain why your not getting errors on `ionic serve`. I would recommend sticking to 2.0 for now as it is the tested version that we recommend at the moment.

**Comment by jgw96** [comment]
Thanks for testing! 😃

**Comment by Bandito11** [comment]
Ok sure.

**Comment by rossholdway** [comment]
Is there any chance we could get this into RC.5?
I'd like to be able to use the object spread and rest (and ES5 compatible Async too)!

**Comment by patrickmcd** [comment]
[Angular doesn't support Typescript 2.1 yet](https://github.com/driftyco/ionic-app-scripts/issues/197#issuecomment-267182893). So there's nothing Ionic can do until that happens with Angular 4.0.

**Comment by rossholdway** [comment]
@patrickmcd Thanks for the info, did not know that!

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic! We are tracking this issue here https://github.com/driftyco/ionic-app-scripts/issues/520. Because of that I am going to close this one for now as a duplicate.
