### ISSUE TITLE
Ionic Build failing (v2)

### ISSUE THREAD

**Issue by Tyler-Darby** [driftyco/ionic#9592]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

`ionic build ios` isn't working at all for me. `ionic serve` works fine but whenever I try to build I get the error below. In my package.json I have appended `--dev` to the build script command because every time I build it builds production which takes forever, and this little bypass has been working for weeks until tonight. 

I can't seem to find any problems in my code and serve works fine.

```
> ionic-hello-world@ ionic:build 
> ionic-app-scripts build --dev

[00:06:04]  ionic-app-scripts 0.0.45 
[00:06:04]  build dev started ... 
[00:06:04]  clean started ... 
[00:06:04]  clean finished in 4 ms 
[00:06:04]  copy started ... 
[00:06:04]  transpile started ... 
[00:06:07]  build dev failed: Cannot read property 'indexOf' of undefined 
[00:06:07]  ionic-app-script task: "build" 
[00:06:07]  TypeError: Cannot read property 'indexOf' of undefined 
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build --dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build --dev'.

```
```

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201611302233
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by graphefruit** [comment]
Hello @Tyler-Darby thats because build is running ngc checks, serve not.
It looks like a variable is undefined/null where you're trying to do an `indexof` 
I've already asked a same question, look here: #9045

So what shall you do?
Look in your code where you use `indexof` and check if the variable is intialized first.
Don't:
`test:Array<any>`

Do:
'test:Array<any>=[];`

Greetings
Graphefruit

**Comment by Tyler-Darby** [comment]
@graphefruit I've searched over my whole src directory using my IDE and I don't use `indexOf` in my code once. The only place it is used is `service-worker.js`

Could this be caused by a NPM package? I am using `AngularFire2` with firebase currently and the problems seem to have started around that time, could that be the case?

**Comment by urm47** [comment]
Do you have an import * as firebase from 'firebase'? 
If AngularFire2 is setup correctly, you don't need this import anymore.

**Comment by Tyler-Darby** [comment]
@urm47 Nope. Got rid of all of those. Pretty stumped here, completely removed angularfire from my project and the issue still persists. It gives me no line numbers, no stack trace, nothing. Not even the npm_debug.log

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#530
