### ISSUE TITLE
How import and export sqlite database 

### ISSUE THREAD

**Issue by 2016lalu** [driftyco/ionic#9600]
Im want to know about Sqlite databse import and export.
means export sqlite database into csv and excel sheet

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
