### ISSUE TITLE
bug(input): selecting an input makes the text wobble

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#9605]
**Ionic version:**  (check one with "x")

[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
On a simple page (no slides), when selecting an `ion-input` on an iOS device or iOS simulator, the text "wobbles" or jumps around. Works fine on Android.

![input wobble](https://cloud.githubusercontent.com/assets/2852839/21116462/58a2bb8c-c0be-11e6-9725-6e18f53f8877.gif)

**Related code:**

```
  <ion-list [formGroup]="profileForm">
        <ion-item>
            <ion-icon name='person' item-left isActive='false'></ion-icon>
            <ion-label stacked>Name</ion-label>
            <ion-input type="text" [(ngModel)]='user.Name' formControlName="firstName"></ion-input>
        </ion-item>
...
```

```
    input {
        font-size: .9em;
    }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612121605
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hey dylan! Unfortunately i cant seem to repro this on the iOS 8.4 sim, what version of iOS are you testing with?

**Comment by jgw96** [comment]
Hey! Quick update on this issue. I can reproduce it with the repo you gave me, but cant seem to repro it in the conf app or on another test app, so im working on finding the differences.

**Comment by dylanvdmerwe** [comment]
Thanks Justin.

**Comment by brandyscarney** [comment]
Update: I can reproduce this using http://localhost:8000/dist/e2e/input/stacked-labels/ in safari on an iOS device.

**Comment by brandyscarney** [comment]
This will be fixed in the next release, but I released a nightly with the fix as well: 

```
npm install --save ionic-angular@2.0.0-rc.4-201612161746
```

Can you try it out and let me know if you find any issues? Thanks. :)

**Comment by dylanvdmerwe** [comment]
Much better. Tested and happy. Thanks Brandy.

**Comment by Daniel9102** [comment]
I still have this issue after the upgrade

**Comment by brandyscarney** [comment]
@Daniel9102 Could you provide some code that I can use to reproduce this please? :)

**Comment by Daniel9102** [comment]
@brandyscarney 

`
My system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
`
html
`
<form [formGroup]="login" (ngSubmit)="loginIn()">
        <ion-item>
          <ion-label >输入用户名</ion-label>
          <ion-input type="text" formControlName="username" ></ion-input>
        </ion-item>
        <ion-item>
          <ion-label>输入密码</ion-label>
          <ion-input type="password" formControlName="password" ></ion-input>
        </ion-item>
        <button padding type="submit" block ion-button color="primary" [disabled]="!login.valid">登录</button>
      </form>
`
