### ISSUE TITLE
bug(search & keyboard): keyboard not dismissing

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#9607]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
On iOS on current nightly, the keyboard is not being dismissing when shown with an `ion-searchbar`. The app has to be closed and reopened in order to get rid of the keyboard. Note this works correctly on Android.

![keyboard not going away](https://cloud.githubusercontent.com/assets/2852839/21117477/8cc37448-c0c2-11e6-8669-c5bb23582e25.gif)

**Expected behavior:**
When pressing whitespace on the screen, or pushing and popping away from the screen, the keyboard should be dismissed. 

**Related code:**

```
<ion-header>
    <ion-navbar>
        <ion-title>
            Documents
        </ion-title>
        <ion-buttons end *ngIf="documents.length > 0">
            <button ion-button icon-only (click)="selectFilter()">
                <ion-icon name="funnel"></ion-icon>
            </button>
        </ion-buttons>
    </ion-navbar>
    <ion-toolbar>
        <ion-searchbar color="primary" placeholder="Search for a document" [(ngModel)]="searchFieldValue" [formControl]="searchField"></ion-searchbar>
    </ion-toolbar>
</ion-header>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612121605
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by peterpeterparker** [comment]
@dylanvdmerwe same here. I reported it as a modal problem but maybe you're right it's related to the ion-searchbar

https://github.com/driftyco/ionic/issues/9594

ps.: in the meantime I implemented an explicit call to Keyboard.close() to force the keyboard to close

**Comment by jgw96** [comment]
Hey dylan! Would you mind giving this a try with a plain starter with just the searchbar and a page to switch to added? I cant seem to reproduce this in my test app on the latest nightly on either the latest iOS 10 or iOS 8.4.

**Comment by dylanvdmerwe** [comment]
Hmmm, just tried to reproduce on the latest nightly and the keyboard does get dismissed correctly.

**Comment by enraiser** [comment]
Please reopen

**Comment by dylanvdmerwe** [comment]
Are you still experiencing this issue? What version of ionic? Can you create a plunkr to demonstrate?
