### ISSUE TITLE
Custom Pipe not found

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic#9609]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When generating a new pipe, and importing the pipe into app.module.ts and adding it to the declaration array, the pipe is unavailable on any view.

**Expected behavior:**
I expect a pipe to be detected.
**Steps to reproduce:**
1. Run `ionic g pipe broken`

This creates a file called `broken.ts`. Path is `src/pipes/broken.ts`

Here is the pipe itself:

```
import { Injectable, Pipe } from '@angular/core';

@Pipe({
  name: 'broken'
})
@Injectable()
export class Broken {
  transform(value, args) {
    value = value + ''; // make sure it's a string
    return value.toLowerCase();
  }
}
```
2. Add the pipe to the `app.module.ts`

`import { Broken }                                    from '../pipes/broken';`

`declarations: [  Broken ]`

3. Add the pipe into a page's html file.
`{{ election.name | broken }}`

4. Get this error in the browser console. (nothing in terminal)

```
Unhandled Promise rejection: Template parse errors:
The pipe 'broken' could not be found ("
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by kamok** [comment]
I also tried setting the value that I'm putting the pipe onto, eg, `election.name` directly into the `component` instead of calling it from a `provider`, which also gave me the same error.

**Comment by anatoly-spb** [comment]
It's strange. There is no problem with pipe with 2.0.0-rc.3: http://plnkr.co/edit/0KI3Kljc2xbz2H3v8ZdV?p=preview

**Comment by kamok** [comment]
@anatoly-spb I just generated a brand new ionic project and couldn't replicate the bug. I ran `ionic-info` and found this:

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

So the only difference is `Ionic App Scripts Version: 0.0.39`. I'll try to see what happens when I update the one that's generating problems

**Comment by kamok** [comment]
@anatoly-spb Ok I figured it out. In my architecture, I have a `component.module` which also as an `@NgModule`. I had to declare `broken` inside that file's `declaration`, as well as `exports` array, which then is sent to `app.module.ts`. 

Not a mistake with Ionic 2. Sorry folks!

**Comment by ihsanberahim** [comment]
I face this issue as well. 
Followed a guide from [here](http://stackoverflow.com/questions/43299610/ionic-3-cant-find-pipe), but still not work.

here my code

```
// src/app/app.module.ts
....
import { SafeurlPipe } from '../pipes/safeurl/safeurl';
import { SafeurlPipeModule } from '../pipes/safeurl/safeurl.module';

@NgModule({
  declarations: [
    App,
    SafeurlPipe
  ],
  imports: [
    BrowserModule,
    HttpModule,
    IonicModule.forRoot(App),
    PriceListingPageModule,
    BranchListingPageModule,
    CountryOptionsComponentModule,
    SafeurlPipeModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    App,
    PriceListingPage,
    BranchListingPage,
    CountryOptionsComponent
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    PublicGoldProvider
  ]
})
export class AppModule {}

```
```
// src/pipes/safeurl.module.ts
import { NgModule } from '@angular/core';
import { SafeurlPipe } from './safeurl';

@NgModule({
  declarations: [
    SafeurlPipe,
  ],
  imports: [

  ],
  exports: [
    SafeurlPipe
  ]
})
export class SafeurlPipeModule { }
```
```
// src/pipes/safeurl.ts
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

/**
 * Generated class for the SafeurlPipe pipe.
 *
 * See https://angular.io/docs/ts/latest/guide/pipes.html for more info on
 * Angular Pipes.
 */
@Pipe({
  name: 'safeurl',
})
export class SafeurlPipe implements PipeTransform {
  constructor(private domSanitizer: DomSanitizer){}

  /**
   * Takes a value and makes it lowercase.
   */
  transform(value: string, args: any) {
    return this.domSanitizer.bypassSecurityTrustResourceUrl(value);
  }
}
```

Is it because of angular lazy loading?
