### ISSUE TITLE
bug(nav): Exception in a page constructor breaks navigation

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#9612]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

If a pushed page raises an error in a constructor the caller page becomes unresponsive.

**Expected behavior:**

Exceptions from page constructor should be handled and app should stay responsive. Ideally there should be possibility to define error handler and if none show an alert with error details by default.

**Steps to reproduce:**
Plunker: http://plnkr.co/edit/iI7tS9yXmNiVK4U75YdS?p=preview
After opening "Good page" if you try to open a "Faulty page" you no longer able to return from good to home page.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Good find, we can probably handle exceptions in the navcontroller better in the framework to keep errors from breaking the entire app.

**Comment by tycho01** [comment]
Temporary workaround (once you realize this is what's going on): put a try-catch block in the relevant constructor to log info on the exception.
This issue is mostly unfortunate because currently you don't get much of a clue as to what went wrong, making it harder to know where to look.

**Comment by manucorporat** [comment]
Thanks to the new error architecture in NavControllerBase, this is not longer the case.
