### ISSUE TITLE
ionic run android -l not recognize as device

### ISSUE THREAD

**Issue by gustavobatista901** [driftyco/ionic#9615]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**Current behavior:**

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62

So i was trying to use InAppBrowser plugin on android for a few days now but i just couldn't find a way to make it work, we know the plugin only works on a real device so i was always testing by running `ionic run android -l` but the plugin was not working and always calling the window.open instead of open InAppBrowser. So i started to debug using chrome device.

![image](https://cloud.githubusercontent.com/assets/9907120/21138143/e1daafd6-c113-11e6-9cb2-148c737d091b.png)

and realized the following:

![image](https://cloud.githubusercontent.com/assets/9907120/21138199/1c88ef12-c114-11e6-892d-d8e79aacf99c.png)

It says the plugin may not be installed or i'm running on the browser, but none of that is possible. So i was curious about that and just removed `-l` flag, i ended up running` ionic run android 
` only, and guess what? It worked, i don't know why, but when using live reload the plugins are not working, so i spent some days to realize this, i even thought it was a problem with InAppBrowser plugin. So I'm curious about this, am i doing something wrong or is it a bug?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1775
