### ISSUE TITLE
Problem with last ion-input inside ion-list

### ISSUE THREAD

**Issue by brunomrpx** [driftyco/ionic#9619]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On create a list of inputs the bottom border of the last input is not showing in Android. On click on the last item, the border follows the width of the list instead of the input.

**Expected behavior:**
The border should have the same style for all inputs inside the list.

**Steps to reproduce:**
Code example: http://plnkr.co/edit/zt7lWPaSFmMPjccgN0gK?p=preview
This behavior also appear at the documentation: http://ionicframework.com/docs/v2/components/#fixed-inline-labels

**Ionic info:** :
```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by jgw96** [comment]
Hey @brunomrpx ! So as a temporary work around can you try not putting your inputs in an `ion-list`? Thanks!

**Comment by brunomrpx** [comment]
@jgw96 It is what I'm doing for now. Thanks to reply.

**Comment by blckshrk** [comment]
Hi,

This bug seem to be still present in the `3.1.1` version :-(

Alex
