### ISSUE TITLE
CookieXSRFStrategy send old values of the CSRF token after relogin to app (right after we received new cookie value)

### ISSUE THREAD

**Issue by VitalyVrublevskyy** [driftyco/ionic#9621]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
CSRF token is incorrect. We send old version of token.

**Expected behavior:**
We should inject CSRFToken related header based on current value of token from cookies.

**Steps to reproduce:**
Login to some application. In response I received cookies:
csrftoken=PONBJe51vUEydcyLAXBiG2K1f53az3Oh
Do any server request: Verify that we have valid 'X-CSRFToken' in each request's header.
Logout from application.
Force clear cookies csrftoken manually or programatically.
Login again to application.
Received new csrftoken=nOZlQHVNJqfDu9XUrzWsAfJfjou5HxC0 in cookie
Do any server request and verify that sent OLD TOKEN (in my example: PONBJe51vUEydcyLAXBiG2K1f53az3Oh)

Ionic2 app screen video: https://drive.google.com/open?id=0B08D5qEP4YtPRFFoWnJybFNGNTA

**Related code:**

```
import { Component }                        from '@angular/core';
import { HTTP_PROVIDERS, XSRFStrategy, CookieXSRFStrategy } from '@angular/http';
import { Platform, ionicBootstrap }         from 'ionic-angular';
import { StatusBar }                        from 'ionic-native';
import { LoginPage }                        from './pages/login/login';
import {PlanService}                        from './providers/plan/plan';
import {SharedService}                      from "./providers/shared/shared";

@Component({
    template: '<ion-nav [root]="rootPage"></ion-nav>'
})

export class Application {
    rootPage: any = LoginPage;

    constructor(platform: Platform) {
        platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            StatusBar.styleDefault();
        });
    }
}

ionicBootstrap(Application,
    [
        HTTP_PROVIDERS,
        PlanService,
        SharedService,
        {
            provide: XSRFStrategy,
            useValue: new CookieXSRFStrategy('csrftoken', 'X-CSRFToken')
        }
    ],
    { backButtonText: '' }
);

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0-beta.2
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
```

PS. Related issue requested by me for google team https://github.com/angular/angular/issues/13313

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! What version of Angular is your angular app running?

**Comment by VitalyVrublevskyy** [comment]
@jgw96 2.0.0-rc.4

**Comment by jgw96** [comment]
@VitalyVrublevskyy Thanks for the reply. So just to clear things up, this works in an Angular 2 rc4 app but not in an Ionic 2 app right? If so, could you try updating your angular app to 2.2.1 (the same version were on) and trying again? We are not doing anything different to the cookie classes built in to angular in Ionic, so im thinking this is an Angular issue and not an Ionic 2 issue.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
