### ISSUE TITLE
Cannot Access Component from Other Component through ViewChild 

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic#9625]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Component is shown undefined in console on run, although it passes ionic build without error. Viewchild only work when the called component is placed under the same module with the calling component. 

**Expected behavior:**
Calling component should be able to access the called component and its method using viewchild.

**Other information:**
![untitled](https://cloud.githubusercontent.com/assets/12269078/21168120/8cc23ce2-c1ec-11e6-828b-7e07ecbc36f3.png)

Note: setStep is the method of called component. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.4.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Hmm so after reviewing this Im not sure that this should actually work. This `only work when the called component is placed under the same module with the calling component.` sounds like exactly how this should work. Im curious, if you try the same thing in a plain Angular 2 app, does it throw an error still?

**Comment by rephchunhoong** [comment]
Great to see your reply @jgw96. As far as I know a component from different module should be callable, as long as it is within the "exports" bracket from its module. I will try in a plain angular 2 application and let you know.

**Comment by daveshirman** [comment]
If you don't find a solution to this, use an event publish/consume.
That's how I've done cross-component communication.

http://ionicframework.com/docs/v2/api/util/Events/

**Comment by jgw96** [comment]
No problem @rephchunhoong ! Let me know what you find.

**Comment by rephchunhoong** [comment]
Hi @jgw96 I tried with vanilla angular and I managed to figure out the problem behind. Indeed, @ViewChild works perfectly nice, while the issue came out from not importing the module of that belongs to the called component. 

It sounds truly silly, yet is there any way it can be addressed during ionic build?

**Comment by jgw96** [comment]
Hmm to be honest im not sure on that, but @danbucholtz may have more info. Do you have a sample project we could look at so we know what your project structure looks like?

**Comment by danbucholtz** [comment]
@rephchunhoong, sorry, I'm not understanding the issue. What would we change in the build?

Thanks,
Dan

**Comment by rephchunhoong** [comment]
Hi @danbucholtz 

I was calling a component from another module in a component, but I did not import the module that belongs to the called component into the module of the calling component. In the end, it still passed ionic build. Of course, the methods from the called component is shown as undefined in console during runtime. However, it really took me quite some time to figure out before I realized my mistake. 

Is there any way ionic can check so it can ensure a module is imported, before calling any component that exports from the module? It would be great if this error can be highlighted during ionic build. 

Thanks.

**Comment by rephchunhoong** [comment]
Hi @danbucholtz

I was calling a component from another module in a component, but I did not import the module that belongs to the called component into the module of the calling component. In the end, it still passed ionic build. Of course, the methods from the called component is shown as undefined in console during runtime. However, it really took me quite some time to figure out before I realized my mistake.

Is there any way ionic can check so it can ensure a module is imported, before calling any component that exports from the module? It would be great if this error can be highlighted during ionic build.

Thanks.

**Comment by danbucholtz** [comment]
@rephchunhoong, You can remove `declarations.d.ts`, which temporarily provides a wildcard operator for module imports. The reason for this is to mitigate some of the challenges with 3rd party libraries and TypeScript.

This will go away with TypeScript 2.1.

Thanks,
Dan
