### ISSUE TITLE
bug: DateTime not working properly on edit

### ISSUE THREAD

**Issue by usarora** [driftyco/ionic#9627]
#**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I am using ion-grid layout. In that I have three rows with first row as header. Second row has two datetime instance. Third row has span.

I want to have click event on all the items. But it is working only on the second datetime.
[sample.txt](https://github.com/driftyco/ionic/files/650751/sample.txt)

Anywhere I click in the grid, event is going to second datetime and showing editing date of second item.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind wrapping both of your datetime components in `ion-item` and trying this again?

**Comment by usarora** [comment]
Hi Justin, 

Thanks for quick reply. If I have two datetime in one ion-item, it does not work. As per the requirement, I need to have both datetime in one row. How can I achieve this?

Thanks,
Uma

**Comment by jgw96** [comment]
ahh sorry, i should have been more clear on that. Each datetime should be in its own `ion-item`.

**Comment by usarora** [comment]
Sorry, I tried ion-item separately also last time, but I removed grid. Now I tried having _ion-item_ in _ion-col_ and it worked.

Thanks a ton!
