### ISSUE TITLE
How to change the backdrop's opacity in an loading indicator that created by LoadingController?

### ISSUE THREAD

**Issue by eric-heihei** [driftyco/ionic#9628]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I change the backdrop's opacity to 0, I can scroll the content that under the backdrop.When the opacity of backdrop isn't 0, I can't scroll the content under that the backdrop. 
**Expected behavior:**

When I change the backdrop's opacity to 0, I hope the content that under the backdrop can't be scroll.
How to change the backdrop's opacity?
**Steps to reproduce:**

**Related code:**
I use the following code to create my loading:
```
presentLoadingDefault() {
        let loading = this.loadingCtrl.create({
            cssClass: 'activity-detail-loading'
        });

        loading.present();
        
        setTimeout(() => {
            loading.dismiss();
        }, 5000);
        
    }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by eric-heihei** [comment]
@jgw96 I can't login ionic forum ,how to login?
