### ISSUE TITLE
ionic2 config->mode->ios   list no lines in android

### ISSUE THREAD

**Issue by adongroom** [driftyco/ionic#9629]
**Ionic version:**  (check one with "x")
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

```
 <ion-list padding-top>

        <ion-item  detail-push *ngFor="let chat of items" (click)="NavigationTo(chat)">
     
            <p>{{chat.Phone}}</p>
 
            <ion-icon item-right name="ios-call" color="zj-bg-icon"
                      (click)="callPhone(chat);$event.stopPropagation()"></ion-icon>
        </ion-item>

    </ion-list>
```

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Would you mind adding some more info to this issue please?

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
