### ISSUE TITLE
issue(config): starter plugins missing from config.xml

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic#9631]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Plugins and platforms folders do not get committed to source control. When cloning a project, the project comes through locally without these folders. When adding a platform (i.e. `ionic platform add ios`) on a project that does not have any additional plugins from those defined in the starter, no plugins are actually downloaded and installed on the platform.

Starter plugins:
```
    "ionic-plugin-keyboard",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen"
```

Should the above plugins not be defined in the config.xml file in the starter projects?

For example:
`    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" /> `

**Expected behavior:**
Starter plugins to be installed when adding a new platform after a platform as been added. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612122136
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by mhartington** [comment]
Thanks for the heads up @dylanvdmerwe 

@jgw96 can you add the following to the v2 config.xml

```
  <plugin name="ionic-plugin-keyboard" spec="~2.2.1"/>
  <plugin name="cordova-plugin-whitelist" spec="1.3.1"/>
  <plugin name="cordova-plugin-console" spec="1.0.5"/>
  <plugin name="cordova-plugin-statusbar" spec="2.2.1"/>
  <plugin name="cordova-plugin-device" spec="1.1.4"/>
  <plugin name="cordova-plugin-splashscreen" spec="~4.0.1"/>
```

**Comment by jgw96** [comment]
Thanks for clearing that up mike, thought that was the solution but wanted to be sure.
