### ISSUE TITLE
Unable to open SQLite database in Android

### ISSUE THREAD

**Issue by fjms** [driftyco/ionic#9635]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Unable to open database in Android

**Expected behavior:**
Open a SQLite database

**Steps to reproduce:**
Create a new ionic 2 blank project
Add platform android
Install cordova-sqlite-storage
See this https://ionicframework.com/docs/v2/native/sqlite/
ionic run android

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by jayeshanandani** [comment]
I am using SQLite and I haven't faced this issue. It works perfectly fine. Cany ou please give some more information like android version or device on which this is being tested upon to replicate or share some piece of code which can help?

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#881
