### ISSUE TITLE
Investigate integrating sw-toolbox

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#9640]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I want to investigate integrating [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) into Ionic to replace our current handwritten approach to service-workers. This would make it much easier for our users to customize the service worker to meet their needs and the needs of their app without having to write raw service worker code (the api is pretty low level) themselves.

**Comment by jgw96** [comment]
@mlynch @adamdbradley When you guys get a chance id love to get some feedback on this idea.

**Comment by jgw96** [comment]
after discussing this offline with max and adam I am happy to say that i have opened two pr's needed to integrate this https://github.com/driftyco/ionic2-app-base/pull/118 and https://github.com/driftyco/ionic-app-scripts/pull/560

**Comment by brandyscarney** [comment]
Can we close this since it isn't a change in the framework?
