### ISSUE TITLE
Slide from right on Navbar is ignored

### ISSUE THREAD

**Issue by calvinthomas150** [driftyco/ionic#9641]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Setting the side="right" property on a navbar is ignored and menu still slides from left

**Expected behavior:**
Menu related to navbar should slide in from right

**Steps to reproduce:**
See code below

**Related code:**

```
`<ion-header>
  <ion-navbar side="right">
    <ion-buttons right>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    </ion-buttons>
    <ion-title>Small Catechism</ion-title>
  </ion-navbar>
</ion-header>`
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic Framework Version: 2.0.0-rc.3
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! The `side` attribute is actually supposed to go on the `ion-menu` instead of the ion-navbar. You can read more about the ion-menu attributes in our docs [here](http://ionicframework.com/docs/v2/api/components/menu/Menu/#input-properties).
