### ISSUE TITLE
tabs switch got more delay in 2.0.0-rc.3-201612142137 than 2.0.0-rc.3

### ISSUE THREAD

**Issue by izee** [driftyco/ionic#9645]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**
1. `ionic start demo --v2` with ionic2-starter-tabs
2. build app with 2.0.0-rc.3 and 2.0.0-rc.3-201612142137
3. click tab to switch pages
4. `2.0.0-rc.3-201612142137 app` got more delay than `2.0.0-rc.3 app`

**2.0.0-rc.3 Ionic info:** :

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Caption
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**2.0.0-rc.3-201612142137 Ionic info:** :

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3-201612142137
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Caption
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you be able to provide more info on this, for example a chrome dev-tools trace or a video showing the differences? Also could you update to [rc4](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc4-2016-12-15) and try again?

**Comment by izee** [comment]
rc.4 works fine.
