### ISSUE TITLE
Form goes up when keyboard shows

### ISSUE THREAD

**Issue by Tusharbalar** [driftyco/ionic#9649]
I am using latest version of ionic 2. 

**Ionic version:** **2.1.8**

**Type:**  bug 

**Platform:** Android

**Current behavior:**
My code has a `<ion-content padding><form></form></ion-content>` with a text input inside of it. When I try to type something in there on **Android** the whole page gets pushed upwards by the keyboard.

**Expected behavior:**
Page should not pushed upwards.

**Comment by masimplo** [comment]
@Tusharbalar maybe you want to join the discussion in #5432

**Comment by mhartington** [comment]
Closing in favor of #5432

**Comment by Tusharbalar** [comment]
@jayeshanandani :+1: 

**ionic info:**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.6
Node Version: v4.6.0
