### ISSUE TITLE
Attempt to use a destroyed view when focus on ion-input on Android device

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic#9650]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Running on an actual Android device. On an app with 4 tabs (one of the tabs shows a virtual scroll list) I push a view into one of the tabs. The view contains an input box and I click inside the input box to give it focus. The keyboard opens and the uncaught exception is thrown. The app becomes unstable after that.

This happens in 4-5 different components where I do no navigational manipulation, just clicking inside an ion-input box triggers the error.

This could be related to #8693 but it happens on any ion-input not just the search box.

**Expected behavior:**

Click inside an input box, keyboard opens, write some text, leave the textbox without error.

**Steps to reproduce:**

This only happens in an actual android device probably because of the fact that the keyboard is shown hidden and the available content height is altered.

**Related code:**

Component with the input box:
```
<ion-header no-shadow>
  <ion-navbar>
    <ion-title>Hello</ion-title>
  </ion-navbar>
</ion-header>
<ion-content>
  <ion-input type="text" name="fullName"   placeholder="No Name"></ion-input>
</ion-content>
```

**Other information:**

the exception reads: 
```
"Error: Attempt to use a destroyed view: detectChanges
    at ViewDestroyedError.Error (native)
    at ViewDestroyedError.BaseError [as constructor] (file:///android_asset/www/build/main.js:35685:34)
    at new ViewDestroyedError (file:///android_asset/www/build/main.js:91553:16)
    at DebugAppView.AppView.throwDestroyedError (file:///android_asset/www/build/main.js:149927:72)
    at DebugAppView.AppView.detectChanges (file:///android_asset/www/build/main.js:149873:18)
    at DebugAppView.detectChanges (file:///android_asset/www/build/main.js:149980:44)
    at ViewRef_.detectChanges (file:///android_asset/www/build/main.js:92137:20)
    at VirtualScroll.renderVirtual (file:///android_asset/www/build/main.js:109522:18)
    at file:///android_asset/www/build/main.js:109514:18
    at readDimensions (file:///android_asset/www/build/main.js:109497:17)"
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by masimplo** [comment]
Just completed a test case where confirmed that this only happens if a Virtual Scroll component is used in one of the tabs, but it affects any ion-input in any "child" page or modal of any of the tabs.

**Comment by jgw96** [comment]
Hello @masimplo ! Thanks for opening an issue with us! Would you mind trying this with [RC4](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc4-2016-12-15)? We did alot of good fixes for virtual scroll in this release which may help here.

**Comment by masimplo** [comment]
So happy RC4 is out, I noticed that is has a lot of virtual scroll fixes. Will try updating and will let you know asap.

**Comment by masimplo** [comment]
After upgrading to RC4 tried the same scenario on two devices and it seems to have been resolved. Thanks jgw96 for the suggestion. Closing this.
