### ISSUE TITLE
ion-toggle dragging bug

### ISSUE THREAD

**Issue by tomdrewes** [driftyco/ionic#9652]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If an ion-toggle is inside a parent element which is positioned/sized in some way other than spanning the entire viewport width, the logic for dragging the toggle is broken.

**Expected behavior:**
Dragging the toggle should work regardless of the parent container position/size in the viewport.

**Steps to reproduce:**
In this Codepen, it is possible to drag the toggles to the right (on) position, but not possible to drag them to the left (off) position:

https://codepen.io/tomdrewes/pen/QGJrqy

**Related code:**
The bug appears to be in ionic.views.Toggle.dragStart, which is using the Element.offsetXXX properties to store the initial drag information.  It should probably use something like Element.getBoundingClientRect() to account for the viewport position since the gesture location information used elsewhere in the Toggle implementation is using that coordinate space.  There is an example patch (commented out in the JavaScript pane) in the Codepen linked above.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#49
