### ISSUE TITLE
VirtualScroll does not render any items if they are not set in the constructor in RC4

### ISSUE THREAD

**Issue by swiftyone** [driftyco/ionic#9654]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
VirtualScroll does not load/display any data if it is not immediately set in the constructor

**Expected behavior:**
The list should be displayed after items have been set

**Steps to reproduce:**

See the plunkr:
http://plnkr.co/edit/Hu960K3tutnyDQgkcxHp

**Related code:**

```
items: Array<{text?: string}>;

constructor(private navController: NavController) {
  // It works if is immediately set the data:
  //this.setItems(); 
    
  // This does NOT work! the list stays empty…
  setTimeout(() => {
    this.setItems();
    console.log(this.items.length + ' items set');
  }, 1000);
}

setItems() {
  let items: Array<{text?: string}> = [];

  for (let i = 1; i < 5000; i++) {
    items.push({text: 'Item ' + i});
  }

  this.items = items;
}
```

**Other information:**

I had no problems with VirtualScroll in RC3 so it should be a new bug

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v5.2.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Unfortunately I cannot reproduce this issue on any of my test apps. Would you mind posting a repo I can use to reproduce this issue?

**Comment by swiftyone** [comment]
Seems to be connected to #9655: If I remove the *ngIf on the virtualScroll Element the items are rendered after the timeout.

Closing the issue in favour of #9655.
Thanks for your effort!
