### ISSUE TITLE
ion-tab with angular2 router not working?

### ISSUE THREAD

**Issue by calidion** [driftyco/ionic#9656]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
show no url info

**Expected behavior:**
show hashed urls

**Related code:**

```
  <ion-tab tabUrlPath='/user/home' ></ion-tab>
  <router-outlet></router-outlet>
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! At this time we do not support the use of the Angular Router in Ionic 2 as we have our own navigation system powered by our NavController and [deeplinker](http://ionicframework.com/docs/v2/api/navigation/DeepLinker/).
