### ISSUE TITLE
bug: Error when using sass $colors with nested map (base & contrast)

### ISSUE THREAD

**Issue by nickgal** [driftyco/ionic#9657]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using a map with base and contrast now results in an error:

```
            The map color `secondary` is not defined. Please make sure the color exists in your `$colors` map. For
            example: $colors: ( secondary: #327eff );

     L109:    @error $error-msg;
```

**Expected behavior:**
To match this example:
https://github.com/driftyco/ionic/blob/eb0b05df88946f1c662c65a707f603aa46ff53cb/src/themes/ionic.functions.scss#L86-L91
```sass
  For example:
  $colors: (
    primary:    #327eff,
    secondary:  (base: #32db64, contrast: #000),
  );";
```

**Steps to reproduce:**
Change $colors to:
```sass
$colors: (
  primary:    #f1f1f1,
  secondary: (base: #f1f1f1, contrast: #f1f1f1),
  dark:  #f1f1f1,
  light:  #f1f1f1
);
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using the [conference app](https://github.com/driftyco/ionic-conference-app). Are you using the `color` function anywhere in your app or do you have a sample repo I can look at to try to pinpoint the problem?

**Comment by brandyscarney** [comment]
Well glad you found it! Are your `base` and `contrast` colors the same for `secondary` or was that just for the example?

**Comment by nickgal** [comment]
That was just for the example.
