### ISSUE TITLE
[BUG]RC4 When set the opt {dismissOnPageChange:true} to LoadingController has  An ERROR

### ISSUE THREAD

**Issue by fssgh** [driftyco/ionic#9659]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
Code:-------------------------------------------------------------------
doLoad() {
    let loading = this.loadingCtrl.create({
      content: 'loading...',
      dismissOnPageChange:true,//Error source
      duration: 15000
    });
    loading.present();
  }
ERROR:-------------------------------------------------------------------------------------------
Error: Uncaught (in promise): false
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.NgZone.forkInnerZoneWithAngularBehavior.inner.inner.fork.onInvokeTask (http://localhost:8100/build/main.js:75544:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at HTMLElement.a.invoke (http://localhost:8100/build/polyfills.js:3:10876)

-------------------------------------------------------------------------------------------------
Ionic Framework: 2.0.0-rc.4
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.1
OS Platform: Windows 8.1
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by infinnie** [comment]
The problem I’ve just run into.

**Comment by kesozjura** [comment]
@fssgh How did you find source of the error from that stack trace?? I have had the same error, but I was not able to find the source of it.

**Comment by infinnie** [comment]
@kesozjura I guess by his or her adding a control group.

**Comment by pufanalexandru** [comment]
Had the same error too, after updating to RC4

**Comment by janein** [comment]
Same error, even without setting `dismissOnPageChange:true` option. Breaks my app on the device, browser keeps working.

**Comment by iliagerman** [comment]
any ideas how to fix this?

**Comment by fssgh** [comment]
@iliagerman  I don't know ! Do not use {dismissOnPageChange:true} temporarily

**Comment by mebibou** [comment]
same issue with `Toast` component with `dismissOnPageChange: true` since RC4

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. Happy to announce that this was part of the rc5 milestone and has already been fixed. You can check out this issue https://github.com/driftyco/ionic/issues/9589 for more info on it and a link to the fix.
