### ISSUE TITLE
Device object is empty on RC4. Unable to call Device.device.uuid

### ISSUE THREAD

**Issue by sasos90** [driftyco/ionic#9662]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Device object from "ionic-native" package is empty. It does not include any methods or properties to call.
In fact, if I call the "Device.device.uuid", I am not able to deploy on device or run it in the browser because i get this error:
[08:42:55]  typescript: src/pages/Jobs/Jobs.ts, line: 70 
            Property 'device' does not exist on type 'typeof Device'. 

      L69:  if (typeof Device !== "undefined") {
      L70:      console.log(Device.device.uuid);

[08:42:55]  transpile failed 
[08:42:55]  ionic-app-script task: "build" 
[08:42:55]  TypeError: error.message.indexOf is not a function 

**Expected behavior:**
I would like to call the Device.device.uuid property to get the unique identifier for device.

**Steps to reproduce:**
Try to call "Device.device.uuid" anywhere.
To see more details, log it in the console "console.log(Device);". You are going to see that Device object is just empty.

For Ionic 2 issues - http://plnkr.co/edit/GJte2b?p=preview
http://plnkr.co/edit/DT40EH7jTrf5tbkts4i0?p=preview

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.19
Node Version: v7.2.1
Xcode version: Not installed
```

**Comment by infinnie** [comment]
See https://github.com/driftyco/ionic-native/blob/master/CHANGELOG.md

**Comment by izee** [comment]
I got it too, and found out that `Device.device.uuid` refactor as `Device.uuid`.

**Comment by inabhi9** [comment]
It returns object in browser. That's unexpected behavior

**Comment by sasos90** [comment]
It works with Device.uuid. I tried to write something, but I couldn't post the message here.

**Comment by Vanclief** [comment]
@inabhi9  I'm experiencing the same behavior, I used to be able to check if Device.device.uuid == undefined, now since i'm getting an empty Object I can't do that.

**Comment by inabhi9** [comment]
@Vanclief I ended up checking its type and value since ionic fellow ain't replied on my comment

**Comment by Vanclief** [comment]
@inabhi9 Another Ionite was pretty cool about it: https://github.com/driftyco/ionic-native/issues/954#issuecomment-271395972
