### ISSUE TITLE
RC4 update docs for Device

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#9667]
Ionic version: 2

The [official docs for the native Device](https://ionicframework.com/docs/v2/native/device/) are obsolete.
Example:
The Device object does not have more a device attribute.
 
Example:
_Device.device.uuid_ wont compile. The compiler outputs

> Property 'device' does not exist on type 'typeof Device'.

Now the right implementation is
`Device.uuid`

**Comment by keyframeindia** [comment]
I have also same issue in RC4

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#899
