### ISSUE TITLE
Not able to get Object of cordova-plugin-ms-azure-mobile-apps

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#9673]
**Ionic version:** RC2
Installed
` cordova plugin add cordova-plugin-ms-azure-mobile-apps`
Added
`var client = WindowsAzure.MobileServiceClient(appUrl);`

But not able to get Object of `WindowsAzure in on .ready`

**Comment by Anshdesire** [comment]
@brandyscarney

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
