### ISSUE TITLE
RC4 - Solution to white screen on ionic serve - storage related

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#9677]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[*] **2.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic serve white screens with no errors, nothing in console logs etc

However Ionic build --prod works fine, creates output (but no error messages)

**Expected behavior:**
Should serve the app

**Steps to reproduce:**

ionic serve on an RC4 / 0.0.47 app scrips app that uses Ionic Storage 

**Other information:**

On investigation, turns out that Ionic Storage 1.1.7 fixes the problem with the white screen.

However the RC4 release changelog says use 1.1.6. People need to be told to go to 1.1.7 if they are experiencing white screen issues (and use Ionic Storage)......

**Comment by andreasderuiter** [comment]
Thanks, you saved my day

**Comment by jgw96** [comment]
Hey @alexbainbridge this has been fixed in the above merged PR and this PR https://github.com/driftyco/ionic2-app-base/pull/123. Thanks!
