### ISSUE TITLE
Sourcemaps aren't updated properly after source code changes

### ISSUE THREAD

**Issue by beylkhanovdamir** [driftyco/ionic#9680]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I run my ionic app by **ionic serve** command. after this I want to make a some changes in my source code and then I'm saving my changes, in result, starts the build process of project by ionic-appscripts and page is refreshing. In result, my sourcemaps files doesn't updated or they missing in Source control (in Google chrome dev tools). to fix this issue, I must stop the ionic serving process, and run it again
**Expected behavior:**

after saving any changes in my source code, sourcemaps  in Source control must be updated according with my changes properly

**Ionic info:**

```
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

app-scripts": "^0.0.46",

**Comment by graphefruit** [comment]
@beylkhanovdamir Update your appscripts to the latest actually 0.0.47 and have a look if the issue still exists

**Comment by dylanvdmerwe** [comment]
https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md

**Comment by beylkhanovdamir** [comment]
@graphefruit @dylanvdmerwe thx, I'll try

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#595
