### ISSUE TITLE
I can't install basic starter - V2

### ISSUE THREAD

**Issue by kresogalic8** [driftyco/ionic#9681]
Hey guys, I'm trying to install basic tabs starter from your documentation instructions, and i get this error in the browser, here's the screenshot below.

This is command that i run before serving the app - ionic start --v2 dealio tabs

<img width="1440" alt="screen shot 2016-12-17 at 09 47 00" src="https://cloud.githubusercontent.com/assets/7289406/21285622/c66c3396-c43d-11e6-8d97-d9b74f3797c5.png">

**Comment by Substractive** [comment]
Kreso have you tried updating node and npm? If it doesn't work maybe uninstall/install ionic ?
I fixed mine with updating npm.

**Comment by kresogalic8** [comment]
Yeah that works for me.
