### ISSUE TITLE
android platform backbutton logic bug when use TabsPage

### ISSUE THREAD

**Issue by dovewi** [driftyco/ionic#9684]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

When I use tabs, In Android platform.I need press back button to exit the app. But when I press, it switch the tab page what I ever clicked.

I try so many method to solve it, But didn't work.

So, I hope you can fix it, such as don't add tab page to history nav stack when click one tab.

**Comment by dylanvdmerwe** [comment]
Have you tried to update your solution to the latest RC4 release? Android back button issues have been resolved and should behave like a native app.

**Comment by dovewi** [comment]
Thank you dylanvdmerwe, Update to RC4 it's worked
