### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by kresogalic8** [driftyco/ionic#9685]
Hey guys, i can't build app on android device, here's the error i got. I've installed all what says but again i am getting that.

<img width="1440" alt="screen shot 2016-12-17 at 14 48 58" src="https://cloud.githubusercontent.com/assets/7289406/21287281/2811bf10-c468-11e6-8664-8c7ff7b879b5.png">

**Comment by demirk4n** [comment]
Have you recently updated your android framework? It seems some components / licence agreements are missing.

**Comment by kresogalic8** [comment]
I updated to the latest android studio. How can I add those licences?

**Comment by graphefruit** [comment]
Start your Android studio and then the SDK manager and update your plugins.
Also this isn't an ionic issue.

**Comment by kresogalic8** [comment]
I updated every plugin there and I get the same issue

**Comment by graphefruit** [comment]
When you click install normaly a new pop-up will open. Check there that you got nowhere the red Cross, click through all updates and accept the licence agreements.
Normaly if you didn't accept all rightly the SDK manager will tell you that there is again an update. Maybe also install the Android 7 SDK.

**Comment by JulianGarciaCastillo** [comment]
Update your plugins on SDK Manager, but don't forget to mark OBSOLETE to update ALL.

**Comment by jayeshanandani** [comment]
This is not an ionic bug. Please use StackOverflow or Ionic forums for these questions.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
