### ISSUE TITLE
ionic-storage item retrieval

### ISSUE THREAD

**Issue by somnathbm** [driftyco/ionic#9687]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If there is currently no key/value pair is set using ionic-storage, then while trying to check whether that  key is set using the .get() method, the promise resolves with a value of null, instead of throwing an error.

**Expected behavior:**
It should throw an error for that. But the thing is even if there is no key, the promise always resolves with a value of null.

**Steps to reproduce:**
  1. just use ionic-storage
  2. just try to get any arbitrary key you haven't set yet
  3. write anything in the error part of the promise of storage.get()

**Related code:**

```
import { Storage } from '@ionic/storage';

@Component({
  template: `<ion-nav [root]="rootPage"></ion-nav>`
})
export class MyApp {
  rootPage: any;

  constructor(platform: Platform, storage: Storage) {
    platform.ready().then(() => {
         storage.get('someKey')
           .then(
               (value) => { // works. it should not work},
               (error) => { // does not work. but it should}
            );
    });
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by horo42** [comment]
Ionic storage is based on localForage. https://localforage.github.io/localForage/#data-api-getitem

"If the key does not exist, getItem() will return null."
This is the expected behaviour imo.

**Comment by somnathbm** [comment]
OK. Thanks for pointing out.
