### ISSUE TITLE
Ionicons is not shown

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#9696]
I upgraded my app from Ionic RC2 to Ionic RC4 but the ionicons are not shown. In my variables.scss, I tried both 

`$ionicons-font-path: "assets/fonts";
@import "ionicons";`

and 
`$ionicons-font-path: "../assets/fonts";
@import "ionicons";`

I also tried to delete le dossier www and .tmp but it doesn't work. 

Anyone had the same problem?

**Comment by pavimus** [comment]
icons in RC4 works good for me. Please look in browser's network inspector, from which url app tries to load font file.
