### ISSUE TITLE
When toggle a div or load an image to a div scrolling gets disabled and only part of the page is visible.  

### ISSUE THREAD

**Issue by KavishPeiris1** [driftyco/ionic#9698]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When toggle a div or load an image to a div scrolling gets disabled and only part of the page is visible. 

**Expected behavior:**

Scroll smoothly like a native application.

**Steps that I tried:**
I have used $ionicScrollDelegate.resize() but it doesn't work.
Therefore I called $ionicScrollDelegate.scrollBottom() inside function to load the full page and it works.
But after I scroll to top again it hides the bottom part same as before.   

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#48
