### ISSUE TITLE
Text-wrap does work only for ion-item?

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic#9702]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report (not sure is a bug)
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I need to use text-wrap for ion card header. I have a bit long titles.
But it seems it doesn't work text-wrap in this case.

**Expected behavior:**

Could be fantastic to have a general class text-wrap to apply on different ionic items.

**Steps to reproduce:**

**Related code:**

```
<ion-card>

    <ion-card-header text-wrap>

        <h2> <ion-icon name="list-box"></ion-icon> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor</h2>

    </ion-card-header>

    <ion-card-content>

        <p>content</p>

    </ion-card-content>

</ion-card>
```

**Other information:**

https://stackoverflow.com/questions/41221166/ionic-2-how-to-use-text-wrap-for-ion-card

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#88

**Comment by FrancescoMussi** [comment]
Thanks @jgw96.
The link is not working by the way - Is that a private repo?

**Comment by webdevcrazier** [comment]
Hi
in <p> tag, text-wrap doesnt work
Please fix it
