### ISSUE TITLE
How can I disable the top padding for ios

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9706]
there is 20px padding at ios for statusbar
how can I disable it?

**Comment by h2qutc** [comment]
You can see it here : http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
You can modify the variable $cordova-ios-statusbar-padding

**Comment by yozman** [comment]
@h2qutc 
I already try it, but doesn't work for me

**Comment by brandyscarney** [comment]
You can either override the Sass variable to `0`: https://github.com/driftyco/ionic-preview-app/blob/master/src/theme/variables.scss#L50

or set it in the config:

```
import { IonicModule } from 'ionic-angular';

@NgModule({
  ...
  imports: [
    IonicModule.forRoot(MyApp, {
      tabsPlacement: 'bottom',
      platforms: {
        ios: {
          statusbarPadding: false,
        }
      }
    }, {}
  )],
  ...
})
```

**Comment by yozman** [comment]
thanks

**Comment by yozman** [comment]
@brandyscarney
js works, thanks,
but `scss` not work,
maybe there is a bug

by the way I set the `mode: 'md'`

**Comment by brandyscarney** [comment]
If you are changing the mode to `md` then you would need to use the Sass variable for that mode :)

```
$cordova-md-statusbar-padding:           0;
```

https://github.com/driftyco/ionic-preview-app/blob/master/src/theme/variables.scss#L67

**Comment by yozman** [comment]
@brandyscarney 
thanks

by the way, there is too much bug on RC4,
wish u fix it soon
