### ISSUE TITLE
bug: https://forum.ionicframework.com/t/ios-build-cors-

### ISSUE THREAD

**Issue by abomadi** [driftyco/ionic#9707]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>is this issue resolved yet CDVWKWebViewEngine does not fill the origin when calling an api it's urgent for the app speed</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
