### ISSUE TITLE
(bug) ionic 2 Conditional ion-header

### ISSUE THREAD

**Issue by theromis** [driftyco/ionic#9709]
trying to make space economy for mobile device and hiding header when person something typing.

so created this code:
```
<ion-header *ngIf="!editing">
    <ion-navbar no-border-bottom ...>
...
    </ion-navbar>
</ion-header>
<ion-content>
...
```

So it hiding headers but not resizing content.

<img src="https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/5/1/51919b5c7b433725d982ab9653c711e056a6194b.png" width="407" height="222">

<img src="https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/c/4/c4594f32194d31301caeaee1a13e696c1c18203a.png" width="404" height="215">

Is there other way to do what I'm trying do?

**Comment by brandyscarney** [comment]
You need to call `resize()` on content whenever you show/hide the header. Please see the docs: http://ionicframework.com/docs/v2/api/components/content/Content/#resize

**Comment by theromis** [comment]
@brandyscarney Thank you.

**Comment by theromis** [comment]
@brandyscarney May be you can help with the other visibility issue.


Also trying hide tabs.
```
<ion-tabs selectedIndex="0" *ngIf="!tabs_hide">
  <ion-tab [root]="tab3Root" tabTitle="Room" [tabBadge]="unread_message_count" tabBadgeStyle="danger"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Contacts" [tabBadge]="userService.getUnreadPersonalMessages()" tabBadgeStyle="danger"></ion-tab>
  <ion-tab [root]="tab1Root" tabTitle="People"></ion-tab>
</ion-tabs>
```

Here just getting exception.
<img src="https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/9/5/958c5e715d6eaab6f3caf1785b62bdb9faf091cf.png" width="690" height="234">
