### ISSUE TITLE
npm install error with RxJS peer dependency

### ISSUE THREAD

**Issue by scferg** [driftyco/ionic#9710]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Cannot complete `npm install` with rc4. Results in `peerinvalid` error, regardless of upgrading from rc3, or starting a new project.

```
npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12
```

**Expected behavior:**
Successfully complete `npm install` by installing all needed dependencies.

**Steps to reproduce:**
`ionic start test --v2`

**Other information:**
![1____projects_mortar_app](https://cloud.githubusercontent.com/assets/1112334/21328524/5ed8bf8a-c602-11e6-8d48-76525694d343.png)

**Ionic info:**

```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v4.2.6
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by oscarvady** [comment]
I have the same error on Windows

**Comment by oscarvady** [comment]
It's works for me now.. You should update Node Version to the lastest stable (v6.9.2). You are using v4.2.6

**Comment by scferg** [comment]
@oscarvady Confirmed - it's working now!

Side note: I had no idea my Node was so out of date...

**Comment by mollyAha** [comment]
anyone knows why update node can solve this problem?
