### ISSUE TITLE
bug: Ionic2 rc3 AdMob adid from AdMobOptions is missing

### ISSUE THREAD

**Issue by frozenxis** [driftyco/ionic#9711]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi.

I seem to struggle with latest version of cordova-admob-pro (2.25.0). i use ionic2 rc3.
when i try to add adid to createBanner or prepareRewardVideoAd

```
if(AdMob) AdMob.createBanner({
  adId: admobid.banner, // this goes BAD...
  position: AdMob.AD_POSITION.TOP_CENTER,
  autoShow: true });
```
or any other one which has adid in the readme i get:

> Argument of type '{ adId: string; isTesting: true; autoShow: true; }' is not assignable to parameter of type 'string | AdMobOptions'.
> Object literal may only specify known properties, and 'adId' does not exist in type 'string | AdMobOptions'.
> i looked in /node_modules/ionic-native/dist/es5/plugins/admob.d.ts and there is no adId in interface AdMobOptions

is there a workaround for this?</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#900
