### ISSUE TITLE
bug: Clicking on disabled ion-input pushes screen up

### ISSUE THREAD

**Issue by tom-mel** [driftyco/ionic#9715]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>Clicking on a *disabled* ion-input triggers the native overflow scrolling (i.e. content of the scroll view is pushed up) as if the application is trying to present the keyboard; and it immediately reverts the scroll position of the screen to its original state. On a side note, you can reproduce only if the ion-input is located in the bottom of the screen (i.e. region dedicated for the keyboard if visible)</span>
```
<ion-item>
        <ion-input type="text" placeholder="Username" [disabled]="true"></ion-input>
</ion-item>
```

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am happy to say that this has already been fixed and will be in rc5. You can check out this issue https://github.com/driftyco/ionic/issues/9070 for more info and to see the fix. Thanks!
