### ISSUE TITLE
docs: Quick update to your install instruction: sudo

### ISSUE THREAD

**Issue by jakedemian** [driftyco/ionic#9717]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>For the install instructions, running the exact command from your guide "npm install -g cordova ionic" gave me errors, I needed to add sudo to the front so that I had access permissions to touch the necessary files.  I just think that it would probably be beneficial to mention this for the mac/linux users out there that might run into that issue and not know the solution.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#936
