### ISSUE TITLE
Date picker API link is broken in v2 docs.

### ISSUE THREAD

**Issue by sudharsanmit** [driftyco/ionic#9719]
Datepicker API is broken in v2 docs. Pls fix.

https://ionicframework.com/docs/v2/api/components/picker/Picker

There is a reference to the above link here

> pickerOptions	any	
> Any additional options that the picker interface can accept. See the Picker API docs for the picker options.

-- Source: https://ionicframework.com/docs/v2/api/components/datetime/DateTime/

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#937
