### ISSUE TITLE
ionic2 FAB button <ion-fab-list> should be hide when click

### ISSUE THREAD

**Issue by Tusharbalar** [driftyco/ionic#9721]
**Ionic Info:** 
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.6
Node Version: v4.6.0

I am working with **`<ion-fab></ion-fab>`** button.
I am not able to close **`<ion-fab-list>`** when I click on someone.
It should be hidden (minimized) when a user clicks on any button.

![imageedit_5_4414585966](https://cloud.githubusercontent.com/assets/4783557/21344313/357bfe6c-c6c1-11e6-9ae1-4a8c662eb140.jpg)

1. When I click on edit button it should be the close **`<ion-fab-list>`** list of the button.

2. When I click on anywhere on screen it should be closed **`<ion-fab-list>`**.

**Comment by wrosb** [comment]
You could try this in the meantime:

.html
```
<ion-fab top right #fab>
  <ion-fab-list side="bottom">
    <button ion-fab color="orange" (click)="gotoTrash($event, fab)">
        <ion-icon  name="trash"></ion-icon> 
      </button>
  </ion-fab-list>
</ion-fab>
```
 
.ts
```
import {  FabContainer } from 'ionic-angular';
.
.
.
gotoTrash(event, fab: FabContainer) {
    fab.close();
    this.navCtrl.push(TrashPage);
  }
```

**Comment by jgw96** [comment]
Hey @Tusharbalar ! Thanks for posting an issue with us. The above code is actually the correct way to implement this behavior. You can read more about this in our docs [here](http://ionicframework.com/docs/v2/api/components/fab/FabContainer/).

**Comment by jorgemejia** [comment]
Is it possible to know when the fab-list is closed ???

**Comment by gischy** [comment]
how can the ion-fab-list be extended/presented on defauld?

**Comment by jhonatasblue** [comment]
Actually, you dont need to handle this on the ts file. You can simply add it to the click event:

`<ion-fab top right #fab>
  <ion-fab-list side="bottom">
    <button ion-fab (click)="gotoTrash($event);fab.close()">
        <ion-icon  name="trash"></ion-icon> 
      </button>
  </ion-fab-list>
</ion-fab>`
