### ISSUE TITLE
Bug: Ionic serve failed to load (typescript 0.0.47 and 0.0.48)

### ISSUE THREAD

**Issue by thinktinker** [driftyco/ionic#9723]
Everytime I save a page, the page does not refresh in the web browser (ionic serve -all)

Looking at my terminal console, I get the following error.

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'send' of undefined

I'm using ionic 2.1.8 (typescript 0.0.47), node 6.9.1, running on ubuntu 16.04.

**Comment by AndreasGassmann** [comment]
It looks like you have an unhandled promise rejection in your code. Try looking for the usage of the `.send` function and see if you are missing a `.catch(console.log)` on that promise.

**Comment by thinktinker** [comment]
It was a fresh project downloaded (ionic start myApp blank --v2 --ts), and the only thing I changed was the home.html file.

What I observed is that the fresh 'blank' project loaded uses the (0.0.47 typescript), which all this while whenever I download a new project, the console prompts me I'm using 0.0.45 typescript, which runs perfectly well on my current install of ionic 2.1.8, with nodejs 6.9.1.

Could it be possible that the starter files using typesript 0.0.47 are broken, or incompatible with my current ionic + nodejs install?

Appreciate further advise here. Thank you.

**Comment by jayeshanandani** [comment]
Could you please update to ionic-app-scripts version 0.0.48 and probably also share `ionic info` output.

**Comment by thinktinker** [comment]
The problem persists though I installed the latest app-script (0.0.48). When I update home.html, the error in bold further below shows up. Any advise?

**My ionic info**
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**When I run ionic serve and update home.html**
> ionic-hello-world@ ionic:serve /build/myapp
> ionic-app-scripts serve

[18:12:30]  ionic-app-scripts 0.0.48 
[18:12:34]  watch started ... 
[18:12:34]  build dev started ... 
[18:12:34]  clean started ... 
[18:12:34]  clean finished in 35 ms 
[18:12:34]  copy started ... 
[18:12:34]  transpile started ... 
[18:13:03]  transpile finished in 28.44 s 
[18:13:03]  webpack started ... 
[18:13:04]  copy finished in 29.49 s 
[18:13:15]  webpack finished in 12.10 s 
[18:13:15]  sass started ... 
[18:13:17]  sass finished in 2.72 s 
[18:13:17]  build dev finished in 43.37 s 
[18:13:18]  watch ready in 43.65 s 
[18:13:18]  dev server running: http://localhost:8100/ 

**[18:14:03]  build started ... 
(node:67) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'send' of undefined**

**Comment by jayeshanandani** [comment]
Which version of typescript are you using?

**Comment by thinktinker** [comment]
Within my package.json dependencies, it states "typescript": "2.0.9".
I'm practically working on brand new 'blank project', and only started inputing some text in the home.html file. 
Does the version of typescript break the ionic serve process?

**Comment by thinktinker** [comment]
Now everything just broke Having done the following:
1. npm install @ionic/latest
2. npm install -g ionic/latest

Nothing compiles now, with the below output error:
**There was an error serving your Ionic application: Error: Cannot find module 'cross-spawn-async'**
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.runIonicScript (/usr/lib/node_modules/ionic/lib/utils/npmScripts.js:22:15)
    at /usr/lib/node_modules/ionic/lib/ionic/serve.js:71:27
    at _fulfilled (/usr/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:557:44

**Comment by jayeshanandani** [comment]
@thinktinker : seems like your ionic latest update was not installed successfully. Please try running command `npm install -g ionic@latest` and ensure it runs fully. Also delete node_modules from project folder and re-run npm install in project.

**Comment by thinktinker** [comment]
Have been doing this for one whole night.
I'm certain that the new blank starter projects have dependencies that do not work with my current ionic set up - which is an older set up (below). It's a same. Shouldn't there be some backward compatibility of the starter projects with previous RCs of ionic 2?
**This is my current set up**
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#599

**Comment by thinktinker** [comment]
Hi jgw96. Is this issue fixed? Otherwise, why is it closed?

**Comment by jgw96** [comment]
Hello @thinktinker . So I closed this issue and moved it to the app-scripts repo which you can see the link to in my above comment. The reason for this move was because this issue is actually an app-scripts issue and not a framework issue.

**Comment by thinktinker** [comment]
Thanks for the heads up. 
Is there a way for me to download a 'blank' project based on 0.0.45 whenever I call 'ionic start myapp blank --v2 --ts'?
Current requests of such serves me a 0.0.47 typescript which breaks in my current ionic development environment.

**Comment by walkingWind** [comment]
I have the same issue.My @ionic/app-scripts version is 0.0.47. So,could you tell me how to change my  @ionic/app-scripts version to 0.0.45

**Comment by walkingWind** [comment]
I have found my issue. I had changed the structure of directory when I add android platform. I had rename index.htm to main.html, and add another index.html.So,change it back.The ionic serve work well.
