### ISSUE TITLE
`ionic build ios` fails with error (swift)

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic#9725]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I manually created a NEW `RC4` project from a working `RC3` project +  "@ionic/app-scripts": "0.0.46"

`ionic build ios` builds for the wrong/different (default) platform. 

```
Building project  : /myProject/platforms/ios/shaker.xcodeproj

	Configuration : Debug
	Platform      : emulator

Build settings from command line:

    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /myProject/platforms/ios/build/emulator
    SDKROOT = iphonesimulator10.2
    SHARED_PRECOMPS_DIR = /myProject/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

...

/myProject/Plugins/com-snaphappi-plugin-camera-roll-location/PhotoWithLocationService.swift:389:19: note: add @available attribute to enclosing class
        fetchOpts.includeAssetSourceTypes = PHAssetSourceType.typeUserLibrary
                  ^



** BUILD FAILED **

The following build commands failed:

        CompileSwift normal i386
        CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(2 failures)
```

I added a switch to set the build platform to `device` but that didn't fix the problem. `ionic build ios --device` fails with the same error in the terminal. The same codebase seems to build correctly with `RC3`

```
        fetchOpts.includeAssetSourceTypes = PHAssetSourceType.typeUserLibrary
                  ^
/myProject/Plugins/com-snaphappi-plugin-camera-roll-location/PhotoWithLocationService.swift:389:19: note: add @available attribute to enclosing instance method
** BUILD FAILED **


The following build commands failed:

	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Expected behavior:**
a successful `ios` build. In either case, I can build successfully in `xcode` from `./platforms/ios/myProject.xcodeproj`. 

Did the build defaults change between `RC3` and `RC4`? or "@ionic/app-scripts": "0.0.46" & "@ionic/app-scripts": "0.0.47"?

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
bash-3.2$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v5.12.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by mixersoft** [comment]
Here is the `ionic info` for the `RC3` version that has no trouble with the build

```
bash-3.2$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v5.12.0
```

**Comment by wbhob** [comment]
Have you updated your local node? v6.9.1 is the latest stable, and v7.2 is the latest, and it looks like you're running v5.12.0.

**Comment by jayeshanandani** [comment]
Apart from node (you should use LTS version) you should also ensure you use 0.0.48 version of ionic-app-scripts as there were few bugs which were addressed in that release.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1801
