### ISSUE TITLE
RC4 orientations are not detected correctly in my views in IOS builds.

### ISSUE THREAD

**Issue by numerized** [driftyco/ionic#9727]
**Ionic version:**  
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Since rc4 orientations are not detected correctly in my views in IOS builds.
`hideWhen="landscape"`
 doesn't work

`[hidden]="platform.isLandscape()" `
neither

This: 

```
<ion-fab center bottom hideWhen="landscape" [hidden]="image">
  <button ion-fab class="ionball ionball-portrait" (click)="takePic()" color="dark"></button>
 </ion-fab>
```

It was working perfectly in rc3, I didn't try to RUN on Android yet.

The funny thing is that it's working perfectly in chrome when I use "ionic serve" and I enable mobile view in landscape/portrait.

**Expected behavior:**
It would hide or show elements depending on the orientation.

**Steps to reproduce:**
Impossible because the problem occurs only in a build.

**Related code:**
See above.

**Other information:**
```
cc.fovea.cordova.purchase 6.0.0 "Purchase"
com.appodeal.plugin 2.1.0 "Appodeal Plugin"
com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
com.ezartech.ezar.flashlight 0.2.1 "ezAR Flashlight"
com.ezartech.ezar.snapshot 0.2.6 "ezAR Snapshot"
com.ezartech.ezar.videooverlay 0.2.9 "ezAR Video Overlay"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-globalization 1.0.4 "Globalization"
cordova-plugin-multidex 0.1.1 "Cordova Multi Dex"
cordova-plugin-network-information 1.3.0 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.1 "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

**Ionic info:**

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by numerized** [comment]
It's not working only in iOS.
On Android it's working perfectly.

You can test it in the Android and IOS simulator like this:

<img width="573" alt="screen shot 2016-12-20 at 17 07 14" src="https://cloud.githubusercontent.com/assets/166829/21357854/1f1b5ce2-c6d7-11e6-88cb-5c64844d2185.png">
<img width="611" alt="screen shot 2016-12-20 at 17 07 30" src="https://cloud.githubusercontent.com/assets/166829/21357855/1f1ef398-c6d7-11e6-9e3a-80135bd7f807.png">

**Comment by numerized** [comment]
When trying to remove : cordova-plugin-screen-orientation plugin it stills not working.
When trying to use internal cordova-plugin-screen-orientation functions it's still not working.

**Comment by numerized** [comment]
Hi :) 

Is (https://github.com/driftyco/ionic/commit/e9adab0) closes this ?

**Comment by numerized** [comment]
Apparently it's not fixing this issue... 
I've updated : cordova-plugin-screen-orientation to 1.4.1 too ...

**Comment by numerized** [comment]
From nightly, problem solved.
Thanks a lot.

**Comment by brandyscarney** [comment]
Thanks for the issue. :) Closing this as it will be fixed in the next release. For anyone that wants to test out the nightly:

```
npm install --save --save-exact ionic-angular@nightly
```
