### ISSUE TITLE
Focus on ion-textarea in front of bound text (iOS)

### ISSUE THREAD

**Issue by judithhartmann** [driftyco/ionic#9729]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When clicking on a textarea the focus is in front of the bound text with no way to change it to behind the text

**Expected behavior:**
Like in ion-input: Focus is after the text

**Steps to reproduce:**
Insert text into an ion-textarea, click on the text area again (on an iphone, tested on device and elevator (iOS 10.2)

```
<ion-textarea [(ngModel)]="description"></ion-textarea>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38
```

![out](https://cloud.githubusercontent.com/assets/4180150/21358065/d1974f2a-c6d7-11e6-8f46-4fd43ffc7fc9.gif)

**Comment by jgw96** [comment]
Hello! Would you mind trying the latest nigthly (npm install ionic-angular@nightly --save) and trying this again? Thanks!

**Comment by judithhartmann** [comment]
Hi,
just tested it with the recent nightly (Ionic Framework Version: 2.0.0-rc.4-201701101946), issue seems to be the same still :(

**Comment by judithhartmann** [comment]
turns out I had the same issue as #9960 and did not put it inside ion-item tags
