### ISSUE TITLE
Cannot programmatically change disabled ion-checkbox or ion-toggle

### ISSUE THREAD

**Issue by daniel-faber** [driftyco/ionic#9730]
**Ionic version:**

[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

The visible checked state of a disabled ion-checkbox or ion-toggle cannot be changed programmatically.

**Expected behavior:**

Although clicking a disabled ion-checkbox or ion-toggle obviously should have no effect, I expect to be able to change the checked state programmatically.

**Steps to reproduce:**

* Open http://plnkr.co/edit/SAaWEqIvbhX3vzCtT3xG?p=preview
* Click “checked” multiple times → “Checkbox / Toggle” changes as expected
* Click “disabled” once
* Click “checked” multiple times → “Checkbox / Toggle” does not change but I expect it to change

**Other information:**

Programmatically changing the text of a disabled ion-input works as expected: http://plnkr.co/edit/ZTPqKlzodr5HECR3z6MN?p=preview

**Ionic info:**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v6.9.2
Xcode version: Not installed

**Comment by naomipol** [comment]
Using  `ngModel` with a disabled toggle doesn't work as well:

```
<ion-toggle
            [(ngModel)]="checked"
            [disabled]="true"
        ></ion-toggle>
```

Changes in the model do not effect the disabled toggle
This should be solved!

**Comment by jamesgroat** [comment]
@brandyscarney 

I'm running into this as well. Seems like disabled should only stop propagation of the click events and not the checked setter or writevalue function.

Perhaps like this: https://github.com/jamesgroat/ionic/commit/4cf92e9de93f35aa33bf41782941b2d809f22dce

(not actually tested and it is possible my commit misses some other side effect ...)

**Comment by brandyscarney** [comment]
Yeah, it should just be removing `!this._disabled &&` from the `_setCheck` for both toggle and checkbox since the item, checkbox and toggle being disabled will prevent pointer events and the click won't trigger. I can submit a PR for this unless you'd like to. :)

**Comment by jamesgroat** [comment]
Please ago ahead -- I don't feel like I'm setup enough to correctly test changes.

**Comment by brandyscarney** [comment]
This will be in the next release. I released a nightly with this fix in it, could you please try it out and let me know if you notice any problems?

```
npm install --save --save-exact ionic-angular@2.0.0-201702031703
```

Thanks! :)

**Comment by daniel-faber** [comment]
@brandyscarney: I tested my project with ionic-angular@2.0.0-201702031703: Bug is fixed, no other problems found, thank you!
