### ISSUE TITLE
(docs): table formatting is broken probably due to `|` character

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#9738]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**

Docs table formatting is broken probably due to `|` character.
https://ionicframework.com/docs/v2/api/navigation/NavController/#lifecycle-events

**Expected behavior:**

The table should be properly formatted and all characters to be displayed correctly.

**Steps to reproduce:**
Open https://ionicframework.com/docs/v2/api/navigation/NavController/#lifecycle-events
and see `ionViewCanEnter` & `ionViewCanLeave`.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#938
