### ISSUE TITLE
documentation for picker is missing?

### ISSUE THREAD

**Issue by danishin** [driftyco/ionic#9742]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Not sure if this is intended or not (perhaps it's meant to be a private api?), but lately I've been using `PickerController` and `Picker` classes for creating custom picker and noticed doc is missing. What's the state on this?

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#935
