### ISSUE TITLE
refresh  twice, the infinite scroll down do not work. it seem have been locked.do not execute the event

### ISSUE THREAD

**Issue by WillLeeBebi** [driftyco/ionic#9744]
**Ionic version:**  (check one with "x")

[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
hi   guys ,i  use infinite scroll,it works. and add refresh  works. just  use refresher,i  clear  all the fetched data. and reget data fill again. scroll down, the  first can get data as usual, but the second time,i  refreshed agian,(no new data  added), the infinite scroll will stuck, keep loading. what happen to infinite scrolling? it seems it stop doing infinite scroll down. the event  doinfinite  have been locked. do not execute the function.

```

**Comment by mhartington** [comment]
How could I replicate this? What does the code look like? I need more information.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
