### ISSUE TITLE
Cannot swipe to show side menu in some views

### ISSUE THREAD

**Issue by Rafael300890** [driftyco/ionic#9746]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Swipe to toggle side menu is not possible with some components.
For example, I have a simple view showing an iframe by this way:

*agenda.html:*
```
<ion-header>
  <ion-navbar hideBackButton>
    <button ion-button menuToggle>
      <ion-icon name='menu'></ion-icon>
    </button>
    <ion-title>Agenda</ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <iframe src="https://aplicaciones.uc3m.es/publicacion/agenda/?layout=N" width="100%" height="100%" frameborder="0"></iframe>
</ion-content>
```

*agenda.ts:*
```
import { Component } from '@angular/core';

@Component({
  templateUrl: 'agenda.html'
})
export class AgendaPage {

  constructor() { }

}
```

When I swipe to toggle side menu, all I get is that the webpage (showed by the iframe) moves to the right.

I explain another use case (with cordova plugin for using native google maps) here:
https://forum.ionicframework.com/t/cannot-swipe-to-show-side-menu-in-some-views/68482

**Expected behavior:**
I think there should be an area (below the hamburger menu), where ionic captures all touch events, to avoid the component showed (in this case iframe) catchs it.
Thereby, swiping on this area, would show side menu.

**Other information:**
I have only tried my app on Android. I don't know if iOS have the same behaviour.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
hello @Rafael300890 are you using this iframe as a "full screen" iframe in your app? So all your apps content is the iframe?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Rafael300890** [comment]
Yes, I am still running into this issue, so please reopen it again.
Thank you.
