### ISSUE TITLE
Right side menu closes on ios on modal dismiss.

### ISSUE THREAD

**Issue by bryantmakesprog** [driftyco/ionic#9749]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The user opens a right side menu. They click a link that opens a modal. They then click a dismiss button that's on the left side of the modal. This causes not only the modal to close but the menu as well.

**Expected behavior:**

The user opens a right side menu. They click a link that opens a modal. They then click a dismiss button that's on the left side of the modal. The modal closes, but the menu stays open.

**Other information:**

I tested this behavior on android and it does not occur. I tested this behavior with a left side menu and it does not occur. I believe the issue is that we are tapping the dismiss button in the left hand side of the screen, which also happens to be the close target for the right side menu.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v7.0.0
```

**Comment by jgw96** [comment]
Hello @bryantmakesprog , is this still an issue in the 2.0.0 release?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
