### ISSUE TITLE
How to Reloading current state - refresh data  in ionic 2

### ISSUE THREAD

**Issue by deep113** [driftyco/ionic#9750]
How to Reloading current state - refresh data  in ionic 2 

Like in Ionic 1 
eg:

$state.transitionTo($state.current, $stateParams, {
    reload: true,
    inherit: false,
    notify: true
});

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by mobinius-shreesha** [comment]
Hello,
        My ionic2 view is getting refreshing every 10 seconds in iphone without any single single.please suggest me how to stop this reloading issue on iphone.
