### ISSUE TITLE
css for gap between sequence of ion-cards separate by ion-col

### ISSUE THREAD

**Issue by mg1075** [driftyco/ionic#9753]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[x ] feature request

This is on 2.0.0-rc.3.

Suppose you have a series of consecutive `ion-card` elements.

Then suppose you create an `ion-row` having `responsive-sm`, and inside the row are two `ion-col` elements of `width-50`.

Then you put half of your cards in the first col, and the other half of your cards in the second col.

Mobile should display this layout as one series cards.
Tablet should display this layout as a two column layout. 

So this part is working for me. 

What is **not** working for me is how the **mobile** view shows an awkward gap between the separation of cards for the first and last column.

So instead of this: 
![image](https://cloud.githubusercontent.com/assets/2031435/21408985/86e28dc0-c79d-11e6-898d-507435f58ee7.png)

...we get this bad gap in the mobile view, and this gap serves no design purpose.
![image](https://cloud.githubusercontent.com/assets/2031435/21409027/b614716c-c79d-11e6-8295-e98792f62367.png)

So the css behind all of this may be optimized for a tablet view, 
but it is not optimized for the mobile view.

(If there is a simple workaround for this and I'm missing it, 
please advise.)

**Comment by brandyscarney** [comment]
Could you paste the code you are using to reproduce this? Also, what device are you viewing it on (android, ios, windows, all of the above?). Thanks!

**Comment by mg1075** [comment]
For a number of reasons, I can't paste all the code I'm using. (And when I tried to make a new ionic v2 project from the rc4 getting started tutorial, npm install failed - but that's a different issue.)

Here is a simple example, though, that should be able to be replicated when testing in chrome for different devices and when testing on an android device.

```
<ion-header>
    <ion-navbar>
        <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
        <ion-title>Home</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    <ion-row responsive-sm>
        <ion-col width-50>
            <ion-card>
                <ion-card-header padding-no>
                    Col 1, Card 1
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
            <ion-card>
                <ion-card-header padding-no>
                    Col 1, Card 2
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
            <ion-card>
                <ion-card-header padding-no>
                    Col 1, Card 3
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
        </ion-col>
        <ion-col width-50>
            <ion-card>
                <ion-card-header padding-no>
                    Col 2, Card 1
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
            <ion-card>
                <ion-card-header padding-no>
                    Col 2, Card 2
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
            <ion-card>
                <ion-card-header padding-no>
                    Col 2, Card 3
                </ion-card-header>
                <div padding>Test content...</div>
            </ion-card>
        </ion-col>
    </ion-row>
</ion-content>
```

Mobile sample view: 

![image](https://cloud.githubusercontent.com/assets/2031435/21437114/a3a3a70a-c847-11e6-9dbc-1aee7f56d8c7.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! With the latest release `2.1.0` the new grid system doesn't use these `responsive-*` attributes anymore and this margin shouldn't be an issue. Read more on it here: http://blog.ionic.io/build-awesome-desktop-apps-with-ionics-new-responsive-grid/

This e2e test should also be close to what you want: https://github.com/driftyco/ionic/tree/master/src/components/grid/test/card
