### ISSUE TITLE
How to make side menu in ionic 2 with both side with different width?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic#9757]
# How to make side menu both side with deffer width ? 
I am doing with sass variable . but its affecting both side menu.
$menu-width: 50px;
$menu-small-width:$menu-width - 40px;

`
![capture1](https://cloud.githubusercontent.com/assets/8583769/21416140/5f59a98e-c836-11e6-8930-544a78590196.PNG)

Right side:

![capture2](https://cloud.githubusercontent.com/assets/8583769/21416148/7073e662-c836-11e6-8033-0ba0bd143a09.PNG)

**Comment by DILEEP-YADAV** [comment]
please help me! ionic team

**Comment by DILEEP-YADAV** [comment]
please help me! anyone!

**Comment by graphefruit** [comment]
@DILEEP-YADAV Why not give a simple class, without affecting the normal .SASS-Values?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by DILEEP-YADAV** [comment]
@graphefruit  thank you very much!
