### ISSUE TITLE
Invisible UI bug

### ISSUE THREAD

**Issue by xggamer** [driftyco/ionic#9758]
Hello!
I am using ionic version 2.1.17
![image](https://cloud.githubusercontent.com/assets/15825888/21416352/0041f85e-c834-11e6-9342-8a1f33711aa5.png)
I am facing an invisible UI bug but when I open the keyboard in my device or inspect element in my browser it turns out fine but I cant show this type of thing to my client, so I need help to get it fixed.
Thank you :)
![image](https://cloud.githubusercontent.com/assets/15825888/21416403/70ee0bf6-c834-11e6-9b5c-c953f25dce38.png)
![image](https://cloud.githubusercontent.com/assets/15825888/21416413/928741e2-c834-11e6-9f51-f5eb1c083a72.png)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
