### ISSUE TITLE
Mixpanel set people properties is not working in ionic 2

### ISSUE THREAD

**Issue by muralimallow** [driftyco/ionic#9760]
import {Mixpanel} from 'ionic-native';

Mixpanel.init('Token').then(()=> {
Mixpanel.track("Application in Running");

Mixpanel.people.set({
"$email" : "email@email.com"
})
**its through Property 'set' does not exist on type 'MixpanelPeople'.**

**My system information:**
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by nisos-siddharth** [comment]
I am still facing the same problem mixpanel set people properties
Is it fixed?
