### ISSUE TITLE
Ionic v2 : (Swipe) gesture does not work at all on some devices

### ISSUE THREAD

**Issue by uzumakinaruto123** [driftyco/ionic#9762]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request
<br>
**Current behavior:**

(swipe) gesture does not work at all on some devices. for ex. `(swipe)="testEvent($event)"`  `testEvent` function is not even called.  Devices are random. most of the time it works.   

**Latest test**, 2 devices `both One Plus 3` and both runnig `Android 6.0.1`. **Only the difference** is one is rooted with cyanogenmod running and other stock oxygen os.  `(pan)` event works on both.

**Also** , on miui devices the swipe gesture stops working anytime. same `testEvent` is not called. But , initially swipe works on all miui devices. (pan) not tested.

<br>

**Expected behavior:**

(swipe) event to be consistently working  across all devices.
<br>
**Steps to reproduce:**

1.start new v2 app.
2. add (swipe) to ion-content on any page.
3. console log event. 
<br>
**Related code:**

`<ion-content (swipe)="testEvent($event)">`

```
testEvent(ev){
//console.log(JSON.stringify(ev,null,5));
   console.log("DIRECTION "+ev.direction);
    
  }
```
<br>

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.1.0
Xcode version: Not installed
```

**Comment by fjms** [comment]
Same problem here with cordova-android 5.2.2

Your system information:

 Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed

**Comment by uzumakinaruto123** [comment]
For now , I have manually added Hammer.js to project , and using it as per docs at [http://hammerjs.github.io/getting-started/](http://hammerjs.github.io/getting-started/)  working for now. still need to test on miui devices. But I am sure it will work.

**Comment by uzumakinaruto123** [comment]
Bad news ! now it does not work on any Android 6.0 device. :(  I need some urgent alternative , if anyone can suggest.  Adding crosswalk works , but thats not the option.

**Comment by cogoo** [comment]
**This may not be a solution but more of a quick temp fix .. what are you trying to achieve with swiping?

Could you use the ion-slides component instead to mimc the same effect?

**Comment by mhartington** [comment]
It's not really recommended to use swipe gestures on the main content. Since `ion-content` is a input for gestures anyways (scrolling and such) it having swipe on it can just cause confusion. Instead, putting the event handler on a child element works fine.

```html
<ion-content padding>
  <ion-card (swipe)="testEvent($event)">
    <ion-item>
      Swiped: {{swipe}} times
    </ion-item>
  </ion-card>
</ion-content>
```

**Comment by uzumakinaruto123** [comment]
I had.... to use.....  Jquery touch based library....!  Which is working flawlessly !  Using it on ion-content itself.  So  for now it works.
