### ISSUE TITLE
(Feature) Add UI Animation To <scroll-content> As Keyboard Closes

### ISSUE THREAD

**Issue by jourdan-jobox** [driftyco/ionic#9763]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

_

Hi guys, currently when the Keyboard closes, the UI just instantly jumps down (rather than doing a smooth slide down). When digging deeper into this, I saw that a `padding-bottom: 300px` is applied as an inline-style onto the page's `<scroll-content>` when the Keyboard opens, and then the `padding-bottom: 300px` looks to be removed right after the Keyboard closes.

Some suggestions I have:
- Decrement the padding-bottom as the Keyboard is closing
- Somehow attach the `<scroll-content>` to the Keyboard so that it just looks like the page slides down as the Keyboard slides down

Here's a GIF of what the UI looks like currently when the Keyboard closes. As you can see, the page jumps down (rather than slides down) after the Keyboard closes:

![alt text](http://g.recordit.co/brRHPkfsRr.gif)

Here's what version of Ionic I'm on, I'm on RC4 (the latest Ionic version as of today):
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by mhartington** [comment]
this is actually very difficult to achieve. Since ios and android actually don't reliably repot keyboard open/close events. Even android it self has so many different keyboards that could close at different times/speeds/easing.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#89
