### ISSUE TITLE
regression(): tap/clicks fire twice on ios

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#9764]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
Click events fire twice on ios sim and device

```
import { Component } from '@angular/core';
@Component({
  selector: 'page-home',
  template: `
    <ion-content padding>
      <button ion-button (click)="logEvent($event)">Test</button>
    </ion-content>
  `
})
export class HomePage {
  logEvent(event){
    console.time('click')
    console.log('click event', event)
    console.timeEnd('click')
  }
}

```

**Other information:**
This is on nightly, and is not happening in rc 4

**Comment by paulogr** [comment]
Have the same problem here. Blocking bug!

**Comment by mhartington** [comment]
Not seeing this anymore in RC6. Closing
