### ISSUE TITLE
Updating to ionic 2.1.18 failed

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic#9766]
Ionic version:2
I'm submitting a bug report & support request.

I'm trying to update ionic 2 version by these commands
`npm uninstall cordova ionic`
`npm install -g cordova ionic`

i get these error
`C:\Users\adirz\myapps\starter-super>npm install -g cordova ionic
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
C:\Users\adirz\AppData\Roaming\npm
`-- cordova@6.4.0
  `-- insight@0.8.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ionic\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN In ionic@2.1.18 replacing bundled version of cross-spawn with cross-spawn@4.0.2
npm WARN In ionic@2.1.18 replacing bundled version of mime-types with mime-types@2.0.14
npm WARN In ionic@2.1.18 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.18 replacing bundled version of form-data with form-data@0.2.0
npm WARN In ionic@2.1.18 replacing bundled version of request with request@2.51.0
npm WARN In ionic@2.1.18 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.9
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\adirz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! path C:\Users\adirz\AppData\Roaming\npm\node_modules\.staging\ansi-f8e54430
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\adirz\AppData\Roaming\npm\node_modules\.staging\ansi-f8e54430' -> 'C:\Users\adirz\AppData\Roaming\npm\node_modules\ionic\node_mod
ules\cordova-lib\node_modules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\adirz\AppData\Roaming\npm\node_modules\.staging\ansi-f8e54430' -> 'C:\Users\adirz\AppData\Roaming\npm\node_modules\ionic\node_mod
ules\cordova-lib\node_modules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adirz\myapps\אפליקציות טובות להשתמש\starter-super\npm-debug.log

C:\Users\adirz\myapps\starter-super>ionic -v
'ionic' is not recognized as an internal or external command,
operable program or batch file.

00
Update NowLaterRelease Notes
Info`

In addition it says ionic is not recognized
**'ionic' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1805
