### ISSUE TITLE
Regression: InfiniteScroll does not work anymore

### ISSUE THREAD

**Issue by h2qutc** [driftyco/ionic#9769]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

InfiniteScroll does not work anymore. With Ionic 2.0 RC3, it worked fine but when I upgraded to RC4. The event "ionInfinite" is not fired when the page has two ion-content. 
**Expected behavior:**

InfiniteScroll worked in RC4
**Steps to reproduce:**

**Related code:**

```
<ion-content> 
<!-- some codes -->
   <ion-content>
    <ion-list>
         <!-- some data -->
    </ion-list>
    <ion-infinite-scroll (ionInfinite)="doInfinite($event)">
          <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>

   </ion-content>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Quick question, what is your use case for having multiple ion-contents on one page in your app?

**Comment by h2qutc** [comment]
Hello, 
In my use case, I have one page "fullscreen" with ion-content. In this page, I have a component my-list that nee 

      <ion-content fullscreen="true">
              <div> some infos here </div>
              <my-list>here is my custom list that need ion-content </my-list>
      <ion-content>    

The component "my-list" is like that: 

      <ion-content class="list">
         <ion-refresher [enabled]="scroll" (ionRefresh)="onRefresh()">
             <ion-refresher-content></ion-refresher-content>
         </ion-refresher>
         <ion-list *ngIf="hasData && (!status || !status.isInError)">
            <ng-content></ng-content>
          </ion-list>
          <ion-list *ngIf="status && status.isInError" class="error-message">
         <message-error (onReload)="onRefresh()" [isNetworkCause]="isNetworkCause"></message-error>
          </ion-list>
             <div class="no-data" *ngIf="!hasData && status && !status.isInError && !status.isLoading" [innerHtml]="noDataMessage">
             </div>
        <ion-list *ngIf="status && status.isLoading && refresher.state !== 'refreshing'">
            <div class="spinner">
               <ion-spinner mode="ios" ></ion-spinner>
            </div>
        </ion-list>
        <ion-infinite-scroll (ionInfinite)="onLoadMore($event)">
            <ion-infinite-scroll-content></ion-infinite-scroll-content>
        </ion-infinite-scroll>
    </ion-content>

It worked fine with ionic RC (0 => 3) until I upgraded to RC4. The event "ionInfinite" is not fired anymore

Thanks,

**Comment by danielcrk** [comment]
Same here, infite scroll stopped working after updateing to rc4. I only have one ion-content.

**Comment by FanYeeChok** [comment]
Same here. We have 2 ion-content and not working after upgrade from RC2 -> RC4.

My use case:
```
<ion-content>

    <ion-scroll>
        <ion-segment>
        </ion-segment>
    </ion-scroll>

    <ion-slides>
        <ion-slide>
            <ion-content>
                <ion-refresher>
                </ion-refresher>

                <ion-infinite-scroll>
                </ion-infinite-scroll>
            </ion-content>
        </ion-slide>
    </ion-slides>

</ion-content>
```

**Comment by h2qutc** [comment]
Hello, do anyone fix that?

**Comment by dPary** [comment]
Same here.
My code :
`<ion-slides #mySlider (ionDidChange)="onSlideChanged()">
    <ion-slide *ngFor="let type of typeData">
        <ion-content>
                <ion-item *ngFor="let item of listData">
                    {{item}}
                </ion-item>
                <ion-infinite-scroll (ionInfinite)="moreData($event)">
                    <ion-infinite-scroll-content loadingText="Loading..."></ion-infinite-scroll-content>
                </ion-infinite-scroll>
        </ion-content>
    </ion-slide>
</ion-slides>`

Only last 'ion-infinite-scroll' works fine.

**Comment by mhartington** [comment]
It is not recommended to use multiple ion-contents in the same page. In this case, this is working as intended

**Comment by SurjithP** [comment]
Same here .
Not working
<ion-slides #mySlider (ionDidChange)="onSlideChanged()">
    <ion-slide *ngFor="let type of typeData">
        <ion-content>
                <ion-item *ngFor="let item of listData">
                    {{item}}
                </ion-item>
                <ion-infinite-scroll (ionInfinite)="moreData($event)">
                    <ion-infinite-scroll-content loadingText="Loading..."></ion-infinite-scroll-content>
                </ion-infinite-scroll>
        </ion-content>
    </ion-slide>
</ion-slides>

Same issue. Did anyone get a solution for this?
how can I load infinite scroll without an ion-content tag?

**Comment by FanYeeChok** [comment]
@SurjithP You can't. Must have the ion-content. We removed additional ion-content, cannot meet user requirement.

**Comment by SurjithP** [comment]
@FanYeeChok  thanks for your reply.

<ion-slides #mySlider (ionDidChange)="onSlideChanged()">
    <ion-slide *ngFor="let type of typeData">
        <ion-content>
                <ion-item *ngFor="let item of listData">
                    {{item}}
                </ion-item>
                <ion-infinite-scroll (ionInfinite)="moreData($event)">
                    <ion-infinite-scroll-content loadingText="Loading..."></ion-infinite-scroll-content>
                </ion-infinite-scroll>
        </ion-content>
    </ion-slide>
</ion-slides>

I'm working like this. But ion-infinite-scroll not loading correctly.
Can you please help me to solve this ?

**Comment by danielcrk** [comment]
Guys, use this module instead, it is superior to Ionics in every way, and it actually works:
https://github.com/rintoj/angular2-virtual-scroll

I'm done jumping through hoops trying to get infiniteScroll to work.

**Comment by FanYeeChok** [comment]
@SurjithP Unfortunately u can't do it. We sacrifice the slides and only can press the button to navigate between the screen. So only implement the ion-infinite-scroll on the outside the ion-content.

And .... ya ....
