### ISSUE TITLE
has-header <content> not working, <ion-content> creates unwanted childscope

### ISSUE THREAD

**Issue by pascalwhoop** [driftyco/ionic#977]
Hello guys. 

I recently had an app started and just updated to beta. 

```
<div class="bar bar-header bar-light">
    <h1 class="title">Edit plug</h1>
</div>
<content has-header="true" has-footer="true" padding="true">
</content>
```

This worked before but in beta, the content was not pushed down enough so the header overlays the content. So i read this part of the docs:

http://ionicframework.com/docs/angularjs/views/content/

and found the <ion-content> and <ion-header> tags. I'm not sure which one is the "right one" <ion-content> or <content> but with the former pushed the content down so i used it. But then i noticed there is an unwanted child scope created which causes problems if usual $scope.foo bindings are used in js which are created via ng-model="foo". 

So now i wonder, why is content not pushed down but instead overlayed by header even though we have has-header="true" and which content tag is the right one?

**Comment by RobertvanHaaren** [comment]
<ion-content has-subheader="true">
        <ion-header-bar class="bar bar-subheader item-input-inset">
        <label class="item-input-wrapper">
            <i class="icon ion-ios7-search placeholder-icon"></i>
            <input id="searchKey" type="search" placeholder="Search" ng-model="search.$" autocorrect="off" >
            <button class="button button-clear" ng-click="clearSearch()">X</button>
        </label>
        <button class="button button-clear" ng-click="search()">Search</button>
</ion-header-bar>

When i create this, the subheader isnt fixed for some reason anyone know why? Please help me out :p

**Comment by hiwanz** [comment]
it seems that the `has-header` attribute on ion-content not working in ionic v1.3.1

![20160817172026](https://cloud.githubusercontent.com/assets/338102/17731209/fa9956e8-649e-11e6-9bf4-bdc47c530088.png)
