### ISSUE TITLE
I updated to latest version, It didn't work by Error: Cannot find module 'reflect-metadata'

### ISSUE THREAD

**Issue by KirsiYin** [driftyco/ionic#9770]
Ionic version: (check one with "x")
[ ] 1.x
[x] 2.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

this is my info

> Your system information:
> 
>  ordova CLI: 6.4.0
> Ionic Framework Version: 2.0.0-rc.4
> Ionic CLI Version: 2.1.18
> Ionic App Lib Version: 2.1.9
> Ionic App Scripts Version: 0.0.48
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.2
> Xcode version: Not installed

after run ionic serve, it shown error like that

> > ionic-conference-app@ ionic:serve C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master
> > ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
> 
> keywords if/then/else require v5 option
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'reflect-metadata'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:1)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Hoang Xuan Thanh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
> npm ERR! node v6.9.2
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-conference-app@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-conference-app@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ionic-conference-app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ionic-conference-app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ionic-conference-app
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master\npm-debug.log
> There was an error serving your Ionic application: There was an error with the spawned command: serve

**Comment by graphefruit** [comment]
@KirsiYin Have you tried to install a starter app, is it working there?

-> `ionic start myProject --v2`

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1813

**Comment by KirsiYin** [comment]
@graphefruit 
-> 'ionic start myProject --v2 
it still work well, but ionic-conference not
here is content of npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\Hoang Xuan Thanh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'ionic:serve',
> 1 verbose cli   '--',
> 1 verbose cli   '--v2',
> 1 verbose cli   '--address',
> 1 verbose cli   '0.0.0.0',
> 1 verbose cli   '--port',
> 1 verbose cli   '8100',
> 1 verbose cli   '--livereload-port',
> 1 verbose cli   '35729' ]
> 2 info using npm@4.0.5
> 3 info using node@v6.9.2
> 4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
> 5 info lifecycle ionic-conference-app@~preionic:serve: ionic-conference-app@
> 6 silly lifecycle ionic-conference-app@~preionic:serve: no script for preionic:serve, continuing
> 7 info lifecycle ionic-conference-app@~ionic:serve: ionic-conference-app@
> 8 verbose lifecycle ionic-conference-app@~ionic:serve: unsafe-perm in lifecycle true
> 9 verbose lifecycle ionic-conference-app@~ionic:serve: PATH: C:\Users\Hoang Xuan Thanh\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\PROGRAM FILES (X86)\INTEL\ICLS CLIENT\;C:\PROGRAM FILES\INTEL\ICLS CLIENT\;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X86;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X64;C:\PROGRAM FILES\SONY\VAIO IMPROVEMENT;C:\PROGRAM FILES (X86)\SONY\VAIO BIOS DATA TRANSFER UTILITY\;C:\PROGRAM FILES (X86)\SONY\VAIO STARTUP SETTING TOOL;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Intel\OpenCL;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Bitvise SSH Client;C:\wamp\bin\php\php5.5.12;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\nodejs\;C:\Program Files\Oracle\VirtualBox;C:\apache-ant-1.9.4\bin;C:\Python27;C:\Users\Hoang Xuan Thanh\.babun;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Hoang Xuan Thanh\AppData\Local\Microsoft\WindowsApps;C:\_Data\sonarqube\sonar-scanner-msbuild-2.2.0.24;C:\Users\Hoang Xuan Thanh\AppData\Roaming\npm
> 10 verbose lifecycle ionic-conference-app@~ionic:serve: CWD: C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master
> 11 silly lifecycle ionic-conference-app@~ionic:serve: Args: [ '/d /s /c',
> 11 silly lifecycle   'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"' ]
> 12 silly lifecycle ionic-conference-app@~ionic:serve: Returned: code: 1  signal: null
> 13 info lifecycle ionic-conference-app@~ionic:serve: Failed to exec ionic:serve script
> 14 verbose stack Error: ionic-conference-app@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Hoang Xuan Thanh\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Hoang Xuan Thanh\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid ionic-conference-app@
> 16 verbose cwd C:\Users\Hoang Xuan Thanh\Downloads\ionic\ionic-conference-app-master\ionic-conference-app-master
> 17 error Windows_NT 10.0.14393
> 18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Hoang Xuan Thanh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
> 19 error node v6.9.2
> 20 error npm  v4.0.5
> 21 error code ELIFECYCLE
> 22 error ionic-conference-app@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
> 22 error Exit status 1
> 23 error Failed at the ionic-conference-app@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the ionic-conference-app package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs ionic-conference-app
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls ionic-conference-app
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
