### ISSUE TITLE
Bug: ion-tabs double stack push with Facebook login

### ISSUE THREAD

**Issue by warent** [driftyco/ionic#9772]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using the Facebook web view, without the Facebook app installed, you log in with Facebook on the app and navigate to another page with ion-tabs. Whatever the fist tab is on the ion-tabs, it will be duplicated or otherwise added to the stack twice.

**Expected behavior:**
ion-tabs shouldn't add the same initial page to its internal nav twice.

**Steps to reproduce:**
Using the facebook4 cordova plugin: https://github.com/jeduan/cordova-plugin-facebook4

There are two pages:
HomePage
TabsPage

HomePage is a blank page with a single button: "Log in with Facebook"
TabsPage is a basic page with ion-tabs, Tab1 and Tab2

1. HomePage Log in with Facebook success function must set TabsPage to the root
2. You should not have the Facebook app installed
3. Launch the app in Android 7.1 (untested on other devices)
4. Click "Log in with Facebook" to trigger the login function and therefore the success function
5. Tab1 is now in the nav stack twice. If you click the "Tab1" tab, it will remove a duplicate from the stack as if you're navigating back from itself.

**Related code:**

HomePage:
```typescript
declare const facebookConnectPlugin: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  // constructor, etc.....

  facebookConnect() {
    facebookConnectPlugin.login("", this.signInSuccess.bind(this), err => console.error(err))
  }

  signInSuccess(success: any) {
    console.log("Success", success);
    this.navCtrl.setRoot(TabsPage);
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Are you still having this issue with the 2.0.0 release?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
