### ISSUE TITLE
Tabs - count from 0 in examples so matches SelectedIndex - change docs and starter

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic#9773]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[*] **2.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
SelectedIndex on tabs starts counting at 0. Thats fine
https://ionicframework.com/docs/v2/api/components/tabs/Tabs/

However all the examples in documentation (and tabs starter v2) start counting at 1. 

This means that you if using the example structure, there is a gotcha until you see what caused it. 

**Expected behavior:**

If the examples were tab0Root, tab1Root, tab2Root...... rather than tab1Root, tab2Root, tab3Root - then the numbers would match up - making it a clearer explanation.

All works as it should right now, but here is a hurdle that people have to learn, which is avoidable with a tweak to examples / starter.

**Related code:**

```
<ion-tabs selectedIndex="2">
  <ion-tab [root]="tab1Root"></ion-tab>
  <ion-tab [root]="tab2Root"></ion-tab>
  <ion-tab [root]="tab3Root"></ion-tab>
</ion-tabs>
```

SelectedIndex 2 selects tab3Root

Areas that need changing
- Documents - https://ionicframework.com/docs/v2/api/components/tabs/Tabs/
- Starter - https://github.com/driftyco/ionic2-starter-tabs/blob/master/src/pages/tabs/tabs.ts

Only an idea!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#942
