### ISSUE TITLE
RC4 bug in FileOpener

### ISSUE THREAD

**Issue by jepiqueau** [driftyco/ionic#9775]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic RC4 FileOpener.open with android platform
when a file has been transfered to the internal storage in a previous session it is working well but when a pdf file is transfered via fileTransfer.download  and you just call FileOpener.open i got 
EXCEPTION: Uncaught (in promise): false
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): false
    at s (file:///android_asset/www/build/polyfills.js:3:4211)
    at s (file:///android_asset/www/build/polyfills.js:3:4034)
    at file:///android_asset/www/build/polyfills.js:3:4574
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9723)
    at Object.onInvokeTask (file:///android_asset/www/build/main.js:37061:37)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9659)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:7083)
    at i (file:///android_asset/www/build/polyfills.js:3:3671)
    at HTMLElement.invoke (file:///android_asset/www/build/polyfills.js:3:10876)
Error: Uncaught (in promise): false

the application does'nt stop and the file is well opened in PDF reader
the same code was working ok in ionic2RC3 without error

can you please help
**Expected behavior:**

**Steps to reproduce:**

starting from the sidemenu template
**app/app.component.ts** nothing change
**app/app.module.ts**
`
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';
import { OpenPdf } from '../providers/openpdf';

@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler},
              OpenPdf
              ]
})
export class AppModule {}

**pages/page2/page2.ts**
import { Component } from '@angular/core';

import { NavController, NavParams } from 'ionic-angular';
import { OpenPdf } from '../../providers/openpdf';

@Component({
  selector: 'page-page2',
     template: `
    <ion-header>
      <ion-navbar>
        <button ion-button menuToggle>
          <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>Page Two</ion-title>
      </ion-navbar>
    </ion-header>

    <ion-content>
      <ion-list>
        <button ion-item *ngFor="let item of pdfList" (click)="itemTapped($event, item)">
          {{item.title}}
        </button>
      </ion-list>
    </ion-content>
  `
})
export class Page2 {
  pdfList: any ;
  constructor(public navCtrl: NavController, public navParams: NavParams,
  public openpdfService: OpenPdf) {
    // If we navigated to this page, we will have an item available as a nav param
    this.pdfList = [
        {"title":"Foo1","link":"http://xxxxxxxxxxfoo1.pdf"},  // replace by own pdf link
        {"title":"Foo2","link":"http://xxxxxxxxxxfoo2.pdf"}
    ];
  }

  itemTapped(event, item) {
    if(cordova){
      let prefixe: string = item.link.slice(0,4);
      if (prefixe == 'http') {
        this.openpdfService.openHttpPDF(item.link).then((data) => {
        }, (err) => {
          console.log("Error Http PDF request")
        });
      }
    }
  }
}

**providers/openpdf.ts**

import { Injectable } from '@angular/core';
import { FileOpener, File, Transfer} from 'ionic-native';
import {Platform, LoadingController, Loading} from 'ionic-angular';

/*
  Generated class for the Openpdf provider.

  See https://angular.io/docs/ts/latest/guide/dependency-injection.html
  for more info on providers and Angular 2 DI.
*/
@Injectable()
export class OpenPdf {
  private devicePath: string;
  private fileName: string;
  private fileUrl: string;
  private message: string;
  private loading: Loading;

  constructor(private platform: Platform, public loadingCtrl: LoadingController) {
  }

  openInternalPDF(fileUrl : string) {
    return new Promise((resolve, reject) => {
      this.openPDF(fileUrl).then((data) =>{
        resolve (data);
      }, (err) => {
        let errMsg = err.message ? err.message : err;
        reject({status:400, message:errMsg});
      });
    });
  }

  openHttpPDF(fileUrl : string){
    return new Promise((resolve, reject) => {
      this.fileUrl = fileUrl;
      this.fileName = this.fileUrl.substring(this.fileUrl.lastIndexOf("/")+1,this.fileUrl.length);
console.log('URL '+this.fileUrl );
console.log('fileName '+this.fileName );
      if(!this.platform.is('cordova'))
      {
          this.message = "<p>Sorry your platform is not a Cordova platform <br /><br />";
          this.message = this.message + "Cannot download PDF file: <strong>" + this.fileName +"</strong></p>";
          reject({"status": 403 , "message" : this.message});
      }
      else {
        if (this.platform.is('android') ) {
          this.devicePath = cordova.file.externalApplicationStorageDirectory;
          this.getFile().then((data) =>{
              resolve (data);
          },(err) => {
            reject({"status": 400 , "message" : err});
          });
        } else if (this.platform.is('ios')) {
          this.devicePath = cordova.file.documentsDirectory;
          this.getFile().then((data) =>{
              resolve (data);
          },(err) => {
            reject({"status": 400 , "message" : err});
          });
        }
        else
        {
            this.message = "<p>Sorry your platform is not supported <br /><br />";
            this.message = this.message + "Cannot download PDF file: <strong>" + this.fileName +"</strong></p>";
            reject({"status": 403 , "message" : this.message});
        }
      }
   });
  }

  private getFile() {
    return new Promise((resolve, reject) => {
      File.checkDir(this.devicePath,'pdf').then((data) => {
        // directory pdf exists so transfer the file
        this.devicePath = this.devicePath + 'pdf/';
        this.transferFile().then((data) =>{
          console.log('getFile ' + JSON.stringify(data));
            resolve (data);
        },(err) => {
          reject({"status": 400 , "message" : err});
        });
      }, (err) => {
        // directory pdf does not exist create it and transfer the file
        File.createDir(this.devicePath,'pdf',false).then((data) => {
          this.devicePath = this.devicePath + 'pdf/';
          this.transferFile().then((data) =>{
              resolve (data);
          },(err) => {
            reject({"status": 400 , "message" : err});
          });
        }, (err) => {
          reject({"status": 400 , "message" : err});
        });

      });

    });
  }

  private transferFile(){
    return new Promise((resolve, reject) => {
      // test if PDF Reader is on the platform
      this.isPDFReader().then((data) =>{
        console.log('out of isPDFReader data' + data);
        if(data > 0){
      // test if the file exist on internal directory
          File.resolveLocalFilesystemUrl(this.devicePath + this.fileName).then((data) => {
            // YES so open it
  // **********************
  // this is working nicely
  // **********************
              this.openPDF(this.devicePath + this.fileName).then((data) =>{
                resolve (data);
              }, (err) => {
                reject({status:400,message:"<p>Cannot read the PDF file: <strong>" + this.fileName +"</strong></p>"});
              });
          }, (err) => {

            // NO transfer it and open it
            const fileTransfer = new Transfer();
            this.presentLoading();
            fileTransfer.download(this.fileUrl,this.devicePath + this.fileName, true).then((data) => {
                this.loading.dismiss().then((data) => {
  // **********************************************
  // this is not working and generate the exception
  // **********************************************
                  this.openPDF(this.devicePath + this.fileName).then((data) =>{
                    resolve (data);
                  }, (err) => {
                    reject({status:400,message:"<p>Cannot read the PDF file: <strong>" + this.fileName +"</strong></p>"});
                  });
                });
              }, (err) => {
                reject({status:400,message:"<p>Cannot transfer the PDF file: <strong>" + this.fileName +"</strong></p>"});
            });

          });
        } else {
          reject({status:400,message:"Please install the Adobe PDF Reader Application on the platform"});
        }
      });
   });
  }

  private openPDF(fileUrl : string) {
    return new Promise((resolve, reject) => {
      console.log('fileUrl '+fileUrl)
      FileOpener.open(fileUrl,'application/pdf').then((data) =>{
        let message :string = "File " + fileUrl + " Openened Successfully";
        resolve ({"status": 200 , "message" : message})
      }, (err) => {
        let errMsg = err.message ? err.message : err;
        reject({status:400, message:errMsg});
      });
    });
  }

  private isPDFReader() {
    return new Promise((resolve) => {
      FileOpener.appIsInstalled('com.adobe.reader').then((data) =>{
        console.log('isPDFReader ', JSON.stringify(data));
        resolve(data.status);
      });
    });
  }

  private presentLoading() {
    this.loading = this.loadingCtrl.create({
      content: "PDF file Loading, Please wait...",
      dismissOnPageChange: true
    });
    this.loading.present();
  }

}

**declarations.d.ts**
declare module '*';
declare var cordova: any;

**package.json**
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-file",
    "cordova-plugin-file-opener2",
    "cordova-plugin-file-transfer"
  ],
  "cordovaPlatforms": [],
  "description": "rc4bug: An Ionic project"
}

**config.xml**
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ionicframework.rc4bug592234" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>rc4bug</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.1" />
    <plugin name="cordova-plugin-console" spec="1.0.5" />
    <plugin name="cordova-plugin-statusbar" spec="2.2.1" />
    <plugin name="cordova-plugin-device" spec="1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="cordova-plugin-file" spec="~4.3.1" />
    <plugin name="cordova-plugin-file-opener2" spec="~2.0.3" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.6.1" />
</widget>

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.3.0
Xcode version: Not installed

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#916
