### ISSUE TITLE
multi-line ion-select

### ISSUE THREAD

**Issue by AleFons** [driftyco/ionic#9776]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ion-select, which essentially calls a modal with the alert style that contains either a radio group - for a single selection - or several items with checkboxes - for multiple selections - has no support for multi-line options. Currently this behavior can be simulated by doing by hand exactly that.

**Expected behavior:**
As both radio-group and a list of items with checkboxes have support for multi-line selects, ion-select, which uses one or the other, should also support them.

**Comment by AleFons** [comment]
I have found a bit of a bizarre workaround via CSS; utilizing:

.multiLine{
  .alert-radio-group{
    white-space: pre-wrap;
  }
  .alert-checkbox-group{
    white-space: pre-wrap;
  }
}

and then manually inserting <br> into the code results in multi-line selects, but they have a lot of space in-between lines.

**Comment by jgw96** [comment]
Hello! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#180

**Comment by mutatieworkz** [comment]
Please try this 

.alert-ios .alert-radio-label{ white-space: pre-line;}
.alert-md .alert-radio-label{ white-space: pre-line;}
.alert-wp .alert-radio-label{ white-space: pre-line;}
.select-text { white-space: pre-line;}
