### ISSUE TITLE
Swiper onReachEnd callback is called when closing a page containing ion-slide elements.

### ISSUE THREAD

**Issue by jmilloy** [driftyco/ionic#9778]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Swiper `onReachEnd` callback is called when closing a page containing ionic-slides with `nav.pop`. I think the cause is the call to `Slides.rapidUpdate` in `Slide.ngOnDestroy`.

**Expected behavior:**
The callback should not be called when closing the page. It should only be called when you reach the real end of the slides.

**Steps to reproduce:**

https://plnkr.co/edit/PUI77NBep2sxO0aCcsdg

In this plunker, the slides page closes when the last slide is reached. But when the page is closed, `onReachEnd` is fired again, so *two* pages are popped.

**Related code:**

Here's an excerpt from the plunker above:

```
@Component({
  templateUrl: 'app/secondary-slides.html'
})
export class SecondarySlidesPage {

  @ViewChild('slides') slides:Slides;
  
  sliderOptions = {
    onReachEnd: () => {
      this.navController.pop();
    },
  };

  constructor(private navController: NavController) { }
}
```

A workaround for this particular example is to erase the `onReachEnd` callback before popping, but this isn't a fix and won't work in all situations:

```
  sliderOptions = {
    onReachEnd: () => {
      this.slides.slider.params.onReachEnd = undefined;
      this.navController.pop();
    },
  };
}
```

**Other information:**

One fix would simply be to remove the call to `Slides.rapidUpdate` in `Slide.ngOnDestroy`. I recognize that the slides would no longer automatically update when removing a slide, but there are other benefits to this approach, see #9768.

Alternatively, possibly the `onReachEnd` callback could be erased in `Slides.ngOnDestroy` or `Slides.ionViewWillUnload`. It would need to be before the child `ion-slide` elements are destroyed, I'm not sure what the lifecycle order is exactly.

```
ngOnDestroy() {
  this.slider.params.onReachEnd = undefined;
}
```

**Ionic info:**

```
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.2.2


--------------------------------
```

**Comment by mhartington** [comment]
Is this still an issue with the slides update in RC5?

**Comment by jmilloy** [comment]
Nope, great! It looked like it would be fixed from the code, but I only got around to testing today. Thanks.
