### ISSUE TITLE
Uploading app.... An error occurred uploading the build: Forbidden upload (403)

### ISSUE THREAD

**Issue by jpca999** [driftyco/ionic#9782]
**Ionic version:**  (check one with "x")
[ ] **1.x**

Uploading app....
An error occurred uploading the build: Forbidden upload (403)

Forbidden upload (403) (CLI v2.1.8)

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v4.5.0
Xcode version: Xcode 8.0 Build version 8A218a

Its a recent thing, it used to work perfectly before....

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by HamzaLJ** [comment]
Same here

**Comment by jpca999** [comment]
@HamzaLJ   I resolved it some how.. 


just change it in the ionic.config.json 

(may be)  ionic io init
then do ionic build
then do ionic upload
