### ISSUE TITLE
ion-slides options (like autoplay) not working anymore?

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic#9783]
Ionic problems with ion-slides. I haven't changed anything at all, just updated. The autoplay was working before updating. When I remove all the options, the slides just says the same as with the options. So it looks like he is not reading / getting the options. What might be the problem here? I don't see any errors in the console btw.

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.2.1 Build version 8C1002
Ionic version: "1.3.1-nightly-4219"
```

Is this a known issue? I am using 

```
<ion-slides options="options" slider="slider">
....
...
<ion-slide-page>
...
</ion-slide-page>
</ion-slides>
```

And:

```
  $scope.options = {
    autoplay: 2500,
    loop: false,
    speed: 1000,
    slidesPerView: 1,
    centeredSlides: true
  }
```

**Comment by djcprinse** [comment]
I have kind of the same issue. However I am not using autoplay but initialSlide. Before updating initialSlide worked perfectly, however now I it not working anymore... I am using ngRepeat at the `<ion-slide-page>`

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
Ionic version: "1.3.2"
```

HTML:
```
<ion-slides options="self.sliderOptions" slider="data.slider">
   <ion-slide-page ng-repeat="month in c.months">
      ......
   </ion-slide-page>
</ion-slides>
```

JavaScript
```
function getMonth() {
   var date = new Date()
   return date.getMonth()
}

self.sliderOptions = {
   runCallbacksOnInit: false,
   pagination: false,
   initialSlide: getMonth()
};
```

This code was working perfectly before update, however now it is not working anymore... I even tried to set `initialSlide: 2` to a static value however this did not work either. Even creating 12 `<ion-slide-page>` manual did not work. At last I tried to set the options in `<ion-slides options="{runCallbacksOnInit: false, pagination: false, initialSlide: 2}" slider="data.slider">`. None of these things worked, so the only reason I can think about is that the update broke the functionality.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#47

**Comment by 1BJK903** [comment]
Someone who can help, please?
