### ISSUE TITLE
Changelog file rc3 section missing typescript dependency

### ISSUE THREAD

**Issue by r7sy** [driftyco/ionic#9789]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Other information:**
pull request to fix it : 
https://github.com/driftyco/ionic/pull/9788

**Comment by jgw96** [comment]
Closing this issue as the PR was merged this morning. Thanks @r7sy !
