### ISSUE TITLE
peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by wbdavidhoeck** [driftyco/ionic#9790]
**Ionic version:** 
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Running ionic start app_name --sass --v2 fails because of invalid peer dependencies.

**Expected behavior:**
A fresh and working install of ionic 2 app with tabs template

**Steps to reproduce:**

Run  ionic start app_name --sass --v2

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Fahrtenbuch-App\fba_app\npm-debug.log      
```

**Comment by saulocamposi** [comment]
I'm having the same problem.

`
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12
`

**Comment by magnusmel** [comment]
same bug on my platform on Opensuse Linux
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v4.6.1
Xcode version: Not installed



Do I have to upgrade to Node. 6.X  for Ionic 2 ??

**Comment by wbdavidhoeck** [comment]
Updating Node.js to 6.9.2 solved my problem!!

**Comment by coverboy** [comment]
Thanks, wbdavidhoeck. In my case, I used Node.js v6.9.4 and solved my problem too!

**Comment by najlla** [comment]
Hi,

In my case after installing node 6.9.6, I had to update my npm from version 2 to 4.1.2. That solved my problem.

**Comment by MuellerMH** [comment]
Same here Example Dockerfile From node:argon do not support it anymore.
`FROM node:argon
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
COPY . /usr/src/app
EXPOSE 8080
WORKDIR /usr/src/app/api
CMD [ "npm", "start"]`

**Comment by mollyAha** [comment]
anyone knows why update node can solve this problem?
