### ISSUE TITLE
Decouple the document title from the currently active ion-title.

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic#9793]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When the current page component has an ion-title element, the document title would be exactly the same string as contained in the ion-title, nothing more or less.

**Expected behavior:**

Some mechanism that we can configure globally could exist to help us map the current app state, including the active ion-title’s contents, to the document title.

**Steps to reproduce:**

**Other information:**

https://forum.ionicframework.com/t/ion-title-and-html-page-title/57644

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.3.1
```

**Comment by infinnie** [comment]
@astec `:before`!!!!!!!!!!!!!!

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#137
