### ISSUE TITLE
Ionic App Fails to Install when downloaded from App Store on Android 7.1.1

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#9797]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**
[x ] bug report

**Current behavior:**
Ionic 2 app fails to install with  **Error -504** when downloaded on device Android 7.1.1, whereas its working perfectly on other versions of Android.

Cordova version: 6.4.0
Ionic version: 2.1.17
Android Platform version: 6.1.0

Steps to reproduce
```
ionic start myApp blank --v2 --id com.mydomain

ionic platform add android@6.1.0

ionic build android --prod --release

```
**Sign and zipalign**

`zipalign -v -p 4 android-release.apk myapp-release.apk`

Submit to Play Store

Download on a device with Android 7.x.x

I tested it on 2 Nexus 6p devices and Nexus 5x.

**Comment by dlaynes** [comment]
Did you find a related issue when googling: "Error -504" android ?

**Comment by naveedahmed1** [comment]
Yes, but most of the posts suggest clearing cache of Play Store and Play services on phone, restarting device, remove google account and add again but nothing works. The issue is with Android 7 and above, works perfectly with other versions.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue on my Nexus 6 running Android 7.0.0. Does your app work when running it on your device with `ionic run android --prod` ?

**Comment by naveedahmed1** [comment]
Yes its working perfectly with ionic run android --prod!

**Comment by jgw96** [comment]
Thanks for the info. Would you mind posting the full error that is given? Is it something like ```Error -504 while installing <package>: -26: Package <package> new target SDK 21 doesn't support runtime permissions but the old target SDK 23 does" ``` ?

**Comment by jgw96** [comment]
Thanks for posting! Unfortunately this is not an Ionic issue but instead a support question regarding distributing apps on google play. I would recommend going to our [forum](https://forum.ionicframework.com) and asking around on there. There are a bunch of awesome devs on our forum who will be able to help you. Thanks for using Ionic!

**Comment by naveedahmed1** [comment]
@jgw96  though you have closed the issue. I would really appreciate if you could please just share some information. I am following this post to automatically sign my apk. https://baxeico.wordpress.com/2015/05/20/how-to-automatically-sign-your-android-apk-using-ionic-framework-and-crosswalk/  After that I use zip align tool to optimize the APK. As per the docs (https://developer.android.com/studio/command-line/zipalign.html) it really matters when the zipalign is perform whether before signing or after signing apk. And that depends on the signing tool using to sign. For apksigner, zipalign must only be performed before the APK file has been signed. For jarsigner, zipalign must only be performed after the APK file has been signed.

Can you please share, does automatic apk signing process described in above post also perform zipalign? If not can you please guide which apk signing tool is use in case of automatic signing apk signer or jarsigner.
