### ISSUE TITLE
bug: Can't assign rootPage inside callbacks

### ISSUE THREAD

**Issue by javebratt** [driftyco/ionic#9798]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I can't assign rootPage inside callbacks in the `app.component.ts file`.

I'm building apps with Ionic 2 and Firebase 3, there's a problem that has been going on since beta11 that when using:

```
firebase.auth().onAuthStateChanged((user) => {
      if (!user) {
        this.rootPage = LoginPage;
        console.log(this.rootPage);
      } else {
        this.rootPage = HomePage;
        console.log(this.rootPage);
      }
    });
```

The app recognizes that `this.rootPage` has a new value, but it's not "pushing" the user to that view.

If you try to console.log() the value of `this.rootPage` inside that conditional you'll get the correct value, but instead of being taken to the page, the user is just shown a white screen.

This only happens assigning `this.rootPage` inside callbacks like this, if I assign the rootPage in any other place inside that file it will work and send the user to that view.

At first I thought it was a Firebase issue, but seeing how the `        console.log(this.rootPage);` logs the correct value, the problm most be on Ionic's end, somehow it's recognizing the value of rootPage but it's not pushing the users there.</span>

<span is-issue-template></span>

**Comment by javebratt** [comment]
By the way, this isn't happening when subscribing to the auth object.

For example, I can do this:

```js
af.auth.subscribe( user => {
  if (user) {
    this.rootPage = HomePage;
  } else {
    this.rootPage = LoginPage;
  }
});
```

And it works perfectly fine, but if I use the function with the callback it assigns the page, it gets the correct value, but it shows the blank page instead of navigating to it.

**Comment by rapropos** [comment]
I would guess that the callback is not being invoked in the proper zone, in which case there really isn't much Ionic can do about it. I think that's why shims like angularfire2 exist.

**Comment by cogoo** [comment]
I face this problem sometimes, @rapropos  is right. Its not invoked in the proper zone. So all you have to do is use NgZone;

    firebase.auth().onAuthStateChanged((user) => {
        this.zone.run(()=>{
         if (!user) {
            this.rootPage = LoginPage;
            console.log(this.rootPage);
          } else {
            this.rootPage = HomePage;
            console.log(this.rootPage);
          }
        })
     
    });

**Comment by javebratt** [comment]
Thank you both @cogoo and @rapropos I really don't know much about ngZone, so I need to go and read to understand it more, this worked beautifully :smiley:
