### ISSUE TITLE
Scroll to a particular item in listview

### ISSUE THREAD

**Issue by dotnetdreamer** [driftyco/ionic#9800]
**Ionic version:**
[x ] **2.x**

**I'm submitting a ...**
[x ] feature request

**Current behavior:**
Currently scrollTo doesn't support scrolling to a particular item as documented here http://ionicframework.com/docs/v2/api/components/content/Content/#scrollToTop. But i want to scrollTo a particular element of a list.

**Steps to reproduce:**
I have an app in which i create a bookmark. Its a book. Now when when the user go to bookmarks, and they select a particular bookmark, i wanna scroll them to that particular chapter and inside the chapter, that bookmarked (specific) line number. You can see the issue i posted here https://stackoverflow.com/questions/41339158/scrollto-particular-item-of-listivew-in-ionic-2

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Hmm so after reading the stackoverflow post, you are using virtualscroll correct?

**Comment by dotnetdreamer** [comment]
yes correct. I actually did a trick with it and that was to calculate the buffer ratio. Here is the code:
```
let indexToFind = this.ayas.findIndex((x:Verse) => x.index == this.verseParams.verseIndex.toString());
            console.log('index='+indexToFind);
            let countedBufferRatio = indexToFind/3;
            if(countedBufferRatio > this.bufferRatio){
                this.bufferRatio = countedBufferRatio;
            }
            setTimeout(() => {
                this.scrollTo(this.verseParams.verseIndex);
            });
```
private scrollTo(verseIndex) {
        let verseKey = '#verse_' + verseIndex;
        console.log(verseKey);
        let hElement: HTMLElement = this.elRef.nativeElement;
        let element = hElement.querySelector(verseKey);
        let offset = this.getElementOffset(element);
        let oldClasses = element.getAttribute('class');
        this.renderer.setElementAttribute(element, "class", oldClasses + ' verse-selected');
        console.log(offset);
        this.content.scrollTo(0, offset.top)
        //change back buffer ratio to gain performance back
        setTimeout(() => {
            this.bufferRatio = 3;            
        });
    }
```
```But i am not happy with this :( if you want code, i can share with you. But this is the problem. I solve this before in xamarin forms. You can see it here https://developer.xamarin.com/api/member/Xamarin.Forms.ListView.ScrollTo/p/System.Object/Xamarin.Forms.ScrollToPosition/System.Boolean/

**Comment by jgw96** [comment]
Hello! I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#138
