### ISSUE TITLE
Ionic framework slider issue

### ISSUE THREAD

**Issue by Thameemans** [driftyco/ionic#9802]
Ionic version 1.0 this issue occurred.

Ionic slide box images only rewinding by default.But I want Slider to be cyclical. How to solve it.

I tried to implement jquery slider instead of Ionic slide box . But its not worked properly.

**Comment by hredwan** [comment]
@Thameemans have you tried the `does-continue` attribute ? you can check the docs here: http://ionicframework.com/docs/api/directive/ionSlideBox/

**Comment by Thameemans** [comment]
When slider reach  last item , it begin first item with effect of left to right instead of right to left(default)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by Thameemans** [comment]
I had add this code on my controller slider working fine.

        $ionicSlideBoxDelegate.update();
        $ionicSlideBoxDelegate.loop(true);
