### ISSUE TITLE
ion-textarea not working in ios 8

### ISSUE THREAD

**Issue by satishmobiweb** [driftyco/ionic#9804]
**"ion-textarea"** not working properly in ios-8 simulator.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Can you please edit this issue with the issue template filled out?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
