### ISSUE TITLE
Display List of information based on Security Rules in Firebase

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic#9807]
Hi,
I used AngularFire2 
I Cannot get Firebase data with security rules using ionic 2,
This is my Firebase rules
{
rules:
{
.read:"auth!=null",
.write:"auth!=null"
}
}
But i cannot access Firebase data if authorized user
Kindly advice me,

Thanks & Regards,

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by anivaisu** [comment]
Hi,
 How to pass login authData in each Pages onclick using ionic 2.
 
Kindly advice me,

Thanks & Regards,
