### ISSUE TITLE
Popover does not work with NG2 Dependency injection rules

### ISSUE THREAD

**Issue by pantonis** [driftyco/ionic#9812]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I create a singleton service. This service correctly works as a singleton across all pages. When I use popover to open a page that this service is injected in the constructor a new instance of the service is created

**Expected behavior:**
The singleton service had to be present on the page that I open with popover

**Steps to reproduce:**
1. I created the starter tabs project: ionic start -v2 tabstest tabs 
2. Create a TestService and add it to the providers of the app.component.ts
3. Inject that service in the constructor of two pages (home, about) (Just in the constructor no providers attr on these pages).
4. Open both pages and correctly see that the service in injected as a singleton
5. Now try to open the about page using PopOver component.
6. You can see now that a new instance of the TestService is created whenever the about is opened using PopOver.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by mhartington** [comment]
> to the providers of the app.component.ts

By that do you mean, you're injecting it into the app.module providers array? 
If yes, than everything works as expect.

```
import { Component } from '@angular/core';
import { TestService } from '../../providers/test-service'
import {AboutPage} from '../about/about'
import { NavController } from 'ionic-angular';
@Component({
  selector: 'page-home',
  template: `
    <ion-content>
      <button ion-button (click)="change($event)">TEST</button>
    </ion-content>
  `
})
export class HomePage {
  constructor(
    public navCtrl: NavController,
    public ts: TestService
  ) {
  }

  change(e) {
    this.ts.showPopover(e, AboutPage)
  }
}
```

```
import { Injectable } from '@angular/core';
import { PopoverController } from 'ionic-angular'
@Injectable()
export class TestService {
  constructor(
    public popoverCtrl: PopoverController
  ) {}
  showPopover(event, comp) {
    let popover = this.popoverCtrl.create(comp);
    popover.present({
      ev: event
    });
  }
}
```

If you dont mean app.module, that is probably the issue. 

All providers MUST be declared in app.module since Angular 2.0 final.

**Comment by pantonis** [comment]
Mike I don't mean create a service which shows the popover. I meant a service that gets injected into the page that the popover opens.

**Comment by mhartington** [comment]
Why dont you provide an example project so that we can understand a bit better

**Comment by pantonis** [comment]
Sure. Here you go. 

[TabsTest](https://github.com/pantonis/tabsTest.git)

1. Open both pages and correctly see that the service in injected as a singleton. (Check console for random number generated)
2. Now try to open the about page using PopOver component.
3. You can see now that a new instance of the TestService is created whenever the about is opened using PopOver.

**Comment by mhartington** [comment]
Thanks, alright, I can see and understand the issue. Thanks.

**Comment by mhartington** [comment]
The issue is with DI itself.

You have `TestService` declared in a providers array in multiple places

https://github.com/pantonis/tabsTest/blob/master/src/app/app.component.ts#L10
https://github.com/pantonis/tabsTest/blob/master/src/pages/contact/contact.ts#L9
https://github.com/pantonis/tabsTest/blob/master/src/app/app.module.ts#L29

Each time it instantiates a new instance, so there is no singleton. Removing the unnecessary providers in app.component.ts and contact.ts, everything behaves as expected.
