### ISSUE TITLE
bug: Cordova Geolocation Plugin Issue.

### ISSUE THREAD

**Issue by abhishekkumar333** [driftyco/ionic#9813]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Cordova geolocation plugin works only with phone's GPS location. If phone GPS is not locked (e.g. being inside the building), then it should take the COARSE_LOCATION i.e. WIFI or Cellular tower.

I checked it by providing it only the permission of only ACCESS_COARSE_LOCATION and commenting out the code for ACCESS_FINE_LOCATION. We get error code: 3 (timeout) in this case.
```

$scope.showpopup=function(status){
                 console.log("show pop up function called");
                 var cont;
                 switch (status) {
                    case 1:
                        cont = "User denied the request for Geolocation."
                        break;
                    case 2:
                        cont = "Location information is unavailable."

                        break;
                    case 3:
                        cont = "The request to get user location timed out."
                        break;
                    default:
                        cont = "An unknown error occurred."
                        break;
                }
                $ionicPopup.alert({
                    title: 'Gps error',
                    content: cont
                });
        };


 navigator.geolocation.getCurrentPosition(
    function(position){
        //Variables to use for showing latitude and longitude by position.coords .
    },function(error){
        $scope.showpopup(error.code);
        },{timeout:10000,maximumAge:60000,enableHighAccuracy:true});
```
</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is actually an issue with cordova and not Ionic itself I am going to close this issue for now and ask that you instead open an issue with the cordova team. You can go [here](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) to start that process. Thanks!

**Comment by abhishekkumar333** [comment]
Hello @jgw96 ,
I knew the issue was with the cordova plugin that's why i had opened the issue on cordova even before creating the issue here.
Actually in some people phones cordova geolocation plugin was showing time out error while  they were able to access the location in their  Whatsapp. That's why i asked for help on issues.cordova , stackoverflow and here. so that people who have faced this issue earlier can provide some help.
