### ISSUE TITLE
Youtube not running well

### ISSUE THREAD

**Issue by amargarido** [driftyco/ionic#9814]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic Native - http://ionicframework.com/docs/v2/native/youtubevideoplayer/

The default version do not run the videos. I Have changed to a more actual GIT and was much better:

**ionic plugin remove** com.bunkerpalace.cordova.YoutubeVideoPlayer

**ionic plugin add** https://github.com/JonSmart/CordovaYoutubeVideoPlayer

**Expected behavior:**

Do not receive error 400

**Steps to reproduce:**

All below with removed / added plugin:

1) If tested on a single page, ionViewDidEnter, the video runs, but a fixed videoId is used.

2) If tested on a detail-video-page, the videoId is passed correctly to the detail screen, but a error 400 is shown.

**Related code:**

Single page (test page)
```
ionViewDidEnter(){
YoutubeVideoPlayer.openVideo('ADWkbfhqIBo');
}

```

Detail Page 
```
  constructor(public navParams: NavParams, public platform: Platform) {
    this.selectedItem = navParams.get('postVideo');
    console.log('this.selectedItem.videoId:' + this.selectedItem.videoId);
    this.platform.ready().then(() => { // we're assuming you injected platform in your constructor
      YoutubeVideoPlayer.openVideo(this.selectedItem.videoId);
    });

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.6.0
Xcode version: Not installed

```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#920
