### ISSUE TITLE
bug: PickerController doesn't select upon tap in Android

### ISSUE THREAD

**Issue by inabhi9** [driftyco/ionic#9816]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

PickerController component does not select item by tapping on it. This occurs only in android

**Expected behavior:**

It should select the item by tapping on it.

**Steps to reproduce:**

Open datetime picker, try to select any date by tapping on it. It won't work

![ot](https://cloud.githubusercontent.com/assets/1921170/21526646/bf740a3e-cd4b-11e6-859b-ae2f44320ed9.gif)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v4.4.5
--------------------------------
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Through testing i can confirm that this is not Android only , it also happens on iOS. From looking at the code for datetime i do not see this behavior implemented, so for now I am going to mark this issue as a feature request.

**Comment by inabhi9** [comment]
It's not just datetime; Actual implementation needs to be done in PickerController because other plugins that use the controller face the same issue.

However Tap to select works in browser (http://ionicframework.com/docs/v2/components/#datetime)

**Comment by moldstadt** [comment]
+1 for this to be fixed to work like it does in the browser. Selecting
date/time on Android can be very difficult without it. Especially changing
selection to 1 above or below current. It either jumps back to the same
item or too far when releasing.

**Comment by patrickmcd** [comment]
I think columns in the picker should also react to the scroll wheel in the browser.

**Comment by jgw96** [comment]
Hello all! While this is an awesome feature request it is not something that we plan on doing anytime soon. Because of this I am going to move this to our internal feature tracking repo for now as it is just "collecting dust" here. Once we decide to implement this I will move it back. Thanks everyone for using Ionic!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#90
