### ISSUE TITLE
2 ion-datetime elements next to eachother in a grid row

### ISSUE THREAD

**Issue by alberthoekstra** [driftyco/ionic#9818]
**Ionic version:**  (check one with "x")
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
With a grid I try to get 2 ion-datetime input element next to eachother.
I managed to get them next to eachother, but I cant edit them both.
See this plunker for the bug in action. http://plnkr.co/edit/2gShG7Eg6KreUIrvpkDa

**Expected behavior:**
See this plunker to see how it suppose to work. http://plnkr.co/edit/7ADRbKxkq6HBgqtp9LHG

It works when you put the ion-datetime elements in a ion-item element.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! The correct way to use datetime is to wrap it in an `ion-item` as your second plunker shows. You can see from our code snippet [here](http://ionicframework.com/docs/v2/components/#datetime) in our docs that the datetime is wrapped in an `ion-item`.

**Comment by alberthoekstra** [comment]
How am I supposed to get 2 datetime element next to each other on 1 row?
