### ISSUE TITLE
Match the native android datepicker

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic#9820]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While our datepicker does look pretty slick right now, it does not look much like the native Android datepicker. 

Datepicker in Google Calendar: https://goo.gl/photos/vREQzopThbiyA8dT6
`<input type="date" />` in Chrome on Android: https://goo.gl/photos/R3iTMyoUtDivyQU56

**Expected behavior:**
Our datepicker to look more like the native Android datepicker when in MD mode. 

**Steps to reproduce:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide steps to reproduce and if possible a demo using one of the following templates:

**Comment by infinnie** [comment]
The current one is actually *better*.

**Comment by jgw96** [comment]
Idea courtesy of brandy: could also be a seperate `calendar` component

**Comment by jayeshanandani** [comment]
Current one seems a way better rather than that pop-up. Could be an addon though!

**Comment by ghenry22** [comment]
Or just use mode as with most components that have platform specific styling for native consistency.

**Comment by infinnie** [comment]
However, like the native Android date picker, the current datetime component needs a preview area.

**Comment by dylanvdmerwe** [comment]
I think this should be a seperate `Calendar` component.

**Comment by jgw96** [comment]
Going to close this issue for now as this will probably end up being a separate component sometime way down the road. Thanks everyone!
