### ISSUE TITLE
V2 bug: livereload can't work for latest platform browser@4.1.0

### ISSUE THREAD

**Issue by netsesame2** [driftyco/ionic#9821]
My Ionic info:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.3.1
Xcode version: Not installed

Description:

> \# ionic start demo --v2 && cd demo
> \# ionic platform add browser
> \# ionic run browser -lcs

then modify something....

> \# [10:12:12]  build started ...

then, console will stop here... nothing go on.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1818
