### ISSUE TITLE
Ionic2 scale property in pinch event have a little issue

### ISSUE THREAD

**Issue by floraluo** [driftyco/ionic#9822]
**Ionic version:2.0.0-rc.3**

**I'm submitting a bug report**

**Current behavior:**

I guess the scale calculate result is according to the first record not the previous. 
As long as the two fingers do not exceed the initial distance, whether it is pinchin or pinchout the picture always zoom out. And I want to calculate scale by myself. Howevery, all the pinchmove event always record the same pointers array. Maybe get the change is by other property I dont kown which one.
**Expected behavior:**

Like the photo album, zoom follow the fingers.

**Related code:**
All the pinchmove event object have the same pointers array:
![image](https://cloud.githubusercontent.com/assets/11729393/21537916/309441a8-cdd2-11e6-9cc0-c273d14195ba.png)
![image](https://cloud.githubusercontent.com/assets/11729393/21537923/48ff145c-cdd2-11e6-8e97-13d437a102cf.png)

**Comment by mhartington** [comment]
How could we recreate this? Is there any sample code to look at. Please follow the issue template and provide the information we need.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
