### ISSUE TITLE
Unable to pin div to bottom of screen, always goes up when keyboard is shown

### ISSUE THREAD

**Issue by sryze** [driftyco/ionic#9823]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I use `position: absolute` to put some text at the bottom of the screen. It works great except when the keyboard opens my bottom div goes up because the height of `ion-view` gets smaller. This doesn't happen on iOS, only Android.

**Expected behavior:**
View having the same height as when keyboard is closed.

**Steps to reproduce:**

Here is an example:

```html
<ion-view>
  <ion-content>
    <input type="text" placeholder="type something here...">
  </ion-content>

  <div class="bottom-stuff">Should be under keyboard</div>

  <style>
    input {
      height: 40px;
      width: 200px;
    }

    .bottom-stuff {
      position: absolute;
      bottom: 0;
    }
  </style>
</ion-view>
```

**Other information:**

I don't have a lot of experience with CSS, but I'm pretty sure there should not be such inconsistency between platforms.

I've searched a lot for a solution but so far the only viable option seems to be to detect when keyboard is shown in code and hide the bottom element. Are there better (simpler) alternatives?

Using `hide-on-keyboard-open` didn't work very well for me because it was only hiding *after* the keyboard is fully open, but not while it's sliding up, so it looked kind of bad.

**Ionic info:** 

Ionic framework version: 1.3.1

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
This because of have native android behaves. The webview it self actually resizes, not just the content. iOS does not do behave this way which is why you're not seeing it there.

Take a look at the android note for keyboard, regarding softInput handling.

http://ionicframework.com/docs/api/page/keyboard/
