### ISSUE TITLE
Google Chrome ion-img bug in Ionic 2 RC4

### ISSUE THREAD

**Issue by azakusilo** [driftyco/ionic#9824]
Hello I got a bug in Google Chrome on Windows 8 when I use **ion-image** tag it is not visible, and it is only in Chrome Browser (55.0.2883.87 m (64-bit)).
```
<div *ngIf="brand.getImage()" class="brandImage">
     <ion-img [src]="brand.getImage()['small_url']" text-center></ion-img>
  </div>
```

Here pictures with problem:
[before](https://yadi.sk/i/TDEZ5WTI35hVwV)
[after my correction](https://yadi.sk/i/6cTVd9Px35hVws)

My version of ionic **app-scripts** 0.0.0.47

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Im having a hard time telling from your picture, but are you using `ion-img` inside of [virtualscroll](http://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/) ?

**Comment by azakusilo** [comment]
No. Just а usual html code without any scroll construction. Here is all code of component template:
```
<div class="brandPage" margin>
  <h1>{{brand.title}}</h1>
  <div *ngIf="brand.getImage()" class="brandImage">
     <ion-img [src]="brand.getImage()['small_url']" text-center></ion-img>
  </div>
  <div class="description" *ngIf="brand.description">
    <h2>Описание:</h2>
    <div [innerHTML]="brand.description"></div>
  </div>
  <div text-center>
    <button ion-button *ngIf="brand.products_count > 0" (click)="openBrandProducts()">Показать товары бренда</button>
  </div>
</div>
```

**Comment by jgw96** [comment]
Thanks for the info @azakusilo ! So for the moment `ion-img` is only meant to be used with `virtualScroll` so thats why it is not working in this situation. We do have plans to make `ion-img` work outside of virtualscroll in the future, but for now i would recommend just using the standard `img` element. Thanks!
