### ISSUE TITLE
ENOENT: no such file or directory, stat ‘/var/root/Library/Logs/CoreSimulator/792D38B1-E2EF-4547-AD8E-F2C3FA46F542/system.log 

### ISSUE THREAD

**Issue by neuberfran** [driftyco/ionic#9825]
Hi guys,

I was with this issue: https://forum.ionicframework.com/t/enoent-no-such-file-or-directory-stat-var-root-library-logs-coresimulator-792d38b1-e2ef-4547-ad8e-f2c3fa46f542-system-log/72775/1

After I create a virtual device with xcrum simctl create and create a file console.log (manually) 
Now I have this:

https://drive.google.com/file/d/0B9gPdWq4OH-XdUE1bnNGREJrNjg/view
(logPath: /Users/neuberfran/myreader/platforms/ios/cordova/console.log

Can anyone help

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1817
