### ISSUE TITLE
Android back button dismiss popover

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic#9827]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When showing a popover and then pressing the hardware back button nothing happens.

**Expected behavior:**

As per other Android apps (e.g. Inbox, Chrome) the popover should be dismissed.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by uzumakinaruto123** [comment]
Anything on this ?

**Comment by jgw96** [comment]
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-feature-requests#181

**Comment by rrabio** [comment]
Any news on the feature request?
