### ISSUE TITLE
how to regist my own menuType?

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic#9828]
hey guys,
I use rc3,
how can I regist my own menuType?
could you please tell me?

**Comment by yozman** [comment]
I want to make `push` type menu animate from 1/2,
so If there is the option to set the slide start point?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
