### ISSUE TITLE
ionViewDidEnter not fired

### ISSUE THREAD

**Issue by gejun2008** [driftyco/ionic#9832]
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39

i have a simple page
my view is a list Page
i open popover
i push a new page at  popover and dismiss popover
on pushed Page i go back with default BackButton
ionViewWillEnter, ...DidEnter and so on will not fire

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us I am going to ask that you edit your issue to include all the information asked for in the issue template. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by reachmohit247** [comment]
I am still facing this issue.
