### ISSUE TITLE
When are two selects on same page works only one(the second)

### ISSUE THREAD

**Issue by fgagneten** [driftyco/ionic#9833]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

---
If I add two select on the same page, in the first select not working ng-selected, only in the second select.
If I remove in the first select

    ng-model="opcionSeleccionadaInicio"` ng-change="vm.modificarHoraInicio($index,opcionSeleccionadaInicio)"

The  ng-selected works, but I don't have any model and I can't handle when the user change the select.
This is my code:

    <ion-view view-title="Cambiar horarios">
    <ion-content>
        <div class="list card" ng-repeat="dia in vm.dias">
            <div class="item item-divider" align="center">
                {{dia.nombre}}
            </div> 
            <div class="list">
                <label class="item item-input item-select">
                    <div class="input-label">
                        Primer turno
                    </div>
                   <select ng-model="opcionSeleccionadaInicio" ng-change="vm.modificarHoraInicio($index,opcionSeleccionadaInicio)"> 
                        <option ng-repeat="horario in dia.horarios" ng-selected="dia.valorInicio == horario">{{horario}}</option> 
                    </select>
                </label>
                <label class="item item-input item-select">
                    <div class="input-label">
                        Último turno
                    </div>
                    <select ng-model="opcionSeleccionadaFin" ng-change="vm.modificarHoraFin($index,opcionSeleccionadaFin)"> 
                        <option ng-selected="dia.valorFin == horario"  ng-repeat="horario in dia.horarios" >{{horario}}</option> 
                    </select>
                </label>
            </div>
        </div>
        <div class="padding-horizontal"><button class="button button-block button-positive" ng-click="vm.guardarHorarios()"> Guardar horarios </button></div>
    </ion-content>
    </ion-view>

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
