### ISSUE TITLE
Slides to have a touch property

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#9840]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Slides are always available to slide using touch

**Desired behavior:**
`<ion-slides [touch]="false">` to disable user interaction sliding

**Other information:**
Why is this desired?
For example, multi-part forms that are in slides.
Slide 1:
your name
Slide 2:
pick an image

and all sliding is done programatically (`slides.slideNext()`)

Super useful IMO

**Ionic info:**
```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by yannbf** [comment]
Hey @AmitMY, do you know that the sliders are based on Swiper? There are so many features that are not listed on ionic 2 docs about sliders, but you can check them [here](http://idangero.us/swiper/api/#.WGmhQxsrK00).

There you will see that to make a slide not swipeable by adding the class `'swiper-no-swiping'`.
Hence, you could use `[ngClass]` and add/remove that class whenever needed.

**Comment by AmitMY** [comment]
Thanks!
