### ISSUE TITLE
How to hide tab bar in Ionic 2?

### ISSUE THREAD

**Issue by ldsenow** [driftyco/ionic#9842]
I have been trying different approach to hide the tab bar when entering into the details page. But somehow, it is harder than I thought.

**Comment by aamir1995** [comment]
Just put `` in your config like this:

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
