### ISSUE TITLE
Router update possible?

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic#9843]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Request**
Is it at all possible the ionic 1 will update to the new versions of both the ui-router and angular?
It would be very nice to use the new and improved mechanisms these updates provide.
I would also do a manual update if that could work.

**Comment by wbhob** [comment]
Is your question if Ionic 1 will support Angular 2?

**Comment by Isigiel** [comment]
Of course not, but if it will eventually support angular 1.6

**Comment by wbhob** [comment]
For the most part, you should be able to drop angular 1.6 and ui-router in without issue. There may be a little refactoring, but it should work for the most part.

**Comment by Isigiel** [comment]
But that could also include ionic core code, which I don't want to mess with.

**Comment by wbhob** [comment]
Why not? Just make the changes you need to make it compatible and make a PR

**Comment by Isigiel** [comment]
While that might be true, it is not what I was looking for and why I filed this issue.
I don't consider myself pro enough to actually change the framework so I amlooking for either an official version with the new libs or a way that allows me to use them without changing ionic at it's core.

**Comment by wbhob** [comment]
Have you tried updating angular and ui-router yet? Any errors?

**Comment by Isigiel** [comment]
I have not, as I was not sure about how to start those updates, mainly because onic usually comes bundled and I din't have time.
Anyways, even if the ionic people would just bump the bundled versions, that'd be what I'm looking for, an oficially supported update to angular 1.6 and the 1.x ui-router

**Comment by mhartington** [comment]
At the moment, we're not focusing on any new features for V1. 
As far as we see it, it is feature complete and will be updated if something is broken.


Regarding router updates, the v1 routing/history implementation is quite complicated, and would require a lot of time to test/update to UI-router 1x. Most of our time and effort at the moment is spent working on 2.0, which is where we want everyone to move to eventually. 


So for now, I'll close this as "wontFix", but if anyone in the community wants to submit of PR to V1, we'd gladly accept it.
