### ISSUE TITLE
Problem script js google maps - Build android

### ISSUE THREAD

**Issue by wander4747** [driftyco/ionic#9847]
I'm using the js google maps script.

When I run the "ionic build  build "the file index.html is updated.
The file js google maps is excluded

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
