### ISSUE TITLE
bug: ionicViewSwitcher.transitionEnd not called causes multiple controller loads

### ISSUE THREAD

**Issue by pfiaux** [driftyco/ionic#9848]
**Ionic version:**  (check one with "x")
[x] **1.x** (1.3.2)
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Given routes: home, section.child.
When going from section.child to home (using transitionDirection "back") and then back to section.child from home multiple times:
* The scope & DOM "pane" elements stop being cleanedup
* Additional controllers are loaded (first +1, then +2, +3, ...)

On iOS the app will crash when it reaches 7-8 additional scopes.

**Expected behavior:**
When caching is off views (both scope & dom elements) are cleaned up when successfully leaving a view.
Upon re-entering the view a single controller is instantiated.

**Related code:**

I was able to trace part of the problem to viewSwitcher.js:
```
function transitionComplete() {
  if (transitionComplete.x) return;
  transitionComplete.x = true;

  enteringEle.off(TRANSITIONEND_EVENT, completeOnTransitionEnd);
  $timeout.cancel(enteringEle.data(DATA_FALLBACK_TIMER));
  leavingEle && $timeout.cancel(leavingEle.data(DATA_FALLBACK_TIMER));

  // resolve that this one transition (there could be many w/ nested views)
  deferred && deferred.resolve(navViewCtrl);

  // the most recent transition added has completed and all the active
  // transition promises should be added to the services array of promises
  if (transitionId === transitionCounter) {
    $q.all(transitionPromises).then(ionicViewSwitcher.transitionEnd);

    // emit that the views have finished transitioning
    // each parent nav-view will update which views are active and cached
    switcher.emit('after', enteringData, leavingData);
    switcher.cleanup(enteringData);
  }

  // tell the nav bars that the transition has ended
  $ionicNavBarDelegate._instances.forEach(function(instance) {
    instance.triggerTransitionEnd();
  });


  // remove any references that could cause memory issues
  nextTransition = nextDirection = enteringView = leavingView = enteringEle = leavingEle = null;
}
```

From debug I can see that the problem starts when I have 3 transition promises (let's give them transitionIds 1,2,3 and transitionCounter=3). What happens is they resolve in the following order:
* 1
* 3
* 2 never resolves

I believe the problem is that when 3 resolves `transitionComplete()` is called the `$q.all()` is waiting for 2 to resolve, `switcher.cleanup()` then happens first. `switcher.cleanup()` seems to remove the element which is transitioning, which would cause the transitionPromise 2 to never resolve (since it's element was removed before transitionEnd).

In turns `ionicViewSwitcher.transitionEnd` is never called and the view (scope&DOM) is never properly cleaned up. Worse the transitionPromsies array is never reset (because it happens in `ionicViewSwitcher.transitionEnd`). This causes every route change after to also contain the "stuck" promise and to fail the same way causing an increasing memory leak.

If I comment out the `switcher.cleanup(enteringData);` call then transitionEnd is properly called once all 3 promises are resolved.

Could `switcher.cleanup(enteringData);` also be moved inside the $q.all after transitionEnd()?

**Other information:**
* View cache is disabled (max is set to 0, and cache: false is on the routes)
* Issue happens in webkit browsers like ios or chrome on osx (firefox seems to have no problem with it).
* If I don't use nextDirection("back") the leak doesn't happen (because of the first check in `cleanup()`)

**Ionic info:**
```
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#46
