### ISSUE TITLE
where to find the debug keystore files?

### ISSUE THREAD

**Issue by zzw64205659** [driftyco/ionic#9849]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

## where i  re-build it , the key sign is faild. 

pls help 

```
where to find the default debug.keystore

I am sure it is not in ~/.android/debug.keystore
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
