### ISSUE TITLE
Error when back button navigation is clicked when Dropdown options are opened

### ISSUE THREAD

**Issue by kkbrains** [driftyco/ionic#9859]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The bug appears on ios simulator and mobile not on web.

**Expected behavior:**

Should close the dropdown options and slide back to the previous page without any error
**Steps to reproduce:**

In one of my applications, I am handling the exception and showing that on $ionicPopup. 
The issue happening for all dropdown,
https://monosnap.com/file/fCxovUgKecjFEsCEwhDCWz4ZJTVYct

Error I receive:
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24digest
http://192.168.12.139:8100/lib/ionic/js/ionic.bundle.js:13415:32
beginPhase@http://192.168.12.139:8100/lib/ionic/js/ionic.bundle.js:30730:31

**Related code:**

```
Error happening from the lib
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Muji86** [comment]
Also noticed on Android:
When an action sheet is open, the back button has no effect.
Expected behaviour: Action Sheet dismissed

**Comment by mhartington** [comment]
How can we go about replicating this? You marked this as V2 related issue, yet the error code is V1 related. 
Please follow the issue template and provide more information.

**Comment by kkbrains** [comment]
Apologies, my bad. `$ ionic --version` shows 2.0.0 thats actual CLI version.
Project framework version is 1.3.0. Ionic info

$ ionic info
Your system information:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.0
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.1 Build version 8B62

**Comment by wbhob** [comment]
You added the v2 flag but this is v1, just so you know

**Comment by infinnie** [comment]
The problem @Muji86 reported was on v2.

**Comment by wbhob** [comment]
Oh, Mike already got that. Also, it is a v1 issue (see ionic info)

**Comment by kkbrains** [comment]
@wbhob Hi I have updated the version, but I am still having the issue
ionic info

Your system information:

Cordova CLI: 6.3.1 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.1 Build version 8B62

**Comment by wbhob** [comment]
Ok, so you obviously have some sort of event triggered by your dropdown, or @mhartington it's an ionic issue with select handlers (but you already know that), but try wrapping your event handler in `$timeout(function() { /* your code here */})`.

**Comment by kkbrains** [comment]
@wbhob & @mhartington Updated my comment and have captured the issue
https://monosnap.com/file/fCxovUgKecjFEsCEwhDCWz4ZJTVYct

**Comment by mhartington** [comment]
Please update the ionic framework version in the project. 1.3.1 fixes this issue.

**Comment by kkbrains** [comment]
Thanks for your prompt reply. I have updated the ionic framework and found that issue is still there. To be more convenient I have replicated the issue using ionic default startup project. Added a simple Select option. 

Steps to reproduce :https://monosnap.com/file/IkobBgyjEGHkVjjPhxmBTvZGE8BKxP
Github project link : https://github.com/kkbrains/testproject
