### ISSUE TITLE
How do I know the data cache size when I want to clean it ? 

### ISSUE THREAD

**Issue by johnnynode** [driftyco/ionic#9860]
**Ionic version:**  (check one with "x")
[x] **1.x**
[x] **2.x**

**Current behavior:**

I do a lot of research on github, cordova, forum and internet , but there is few solution to solve it , How do I know the size of data cache when I want to clean it? 
And there are some plugins to clean webview cache , but how can I count the size of data cache in different platforms.
Any idea ?

**Comment by mhartington** [comment]
Hi there! Looks like this is NOT an issue with the framework, but rather a question. Please follow the links in the issue template to the ionic forum, or join the ionic slack channel and ask there. Github issues are for issues only, not questions.

**Comment by johnnynode** [comment]
Yes, It's a question and I think the framework should have a solution or api to do such a thing to make it perfect . OK then , I may go someplace like ionic slack chanel or stackoverflow to ask . Thank you all the same.
