### ISSUE TITLE
Could not find a storyboard named LaunchScreen in Ionic 2

### ISSUE THREAD

**Issue by pawelfrydrych** [driftyco/ionic#9862]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

I'm trying to run my app on ios emulator, and when I do: ionic emulate or ionic run ios, then emulator started, standard ionic splashscreen shown, and app stopped. On Google Chrome and android everything works, but xcode show error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'LaunchScreen' in Bundle NSBundle

So I clicked in File -> New -> File -> and I created Launch Screen named LaunchScreen with storyboard format, and then it worked, but emulator shown firstly standard ionic splash, next custom splashscreen created few minutes ago, and then nothing else, app wasn't loaded but not crashed.

I tried to remove and re-add this ios platform, but it not works.

**Comment by mhartington** [comment]
Please follow the issue template are provide the output from `ionic info` and also `ionic platform ls`

**Comment by mhartington** [comment]
Closing as there is no information on how to replicate this.
