### ISSUE TITLE
Ionic List, Header and Form not working/displaying well on Samsung Note 3

### ISSUE THREAD

**Issue by iammash** [driftyco/ionic#9863]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
List are not displaying as they should on Samsung Galaxy Note 3, The list looks un styled. The input field on the form do not allow any action and are not in style, select options not showing the drop down and pointer jumps to another input field below and when a text area is displayed the text pointer keeps blinking rapidly than normal. 

**Expected behavior:**
The list items get displayed as they show on the documentation phone view, and select options show when tapped and the cursor does not blink rapidly. 

**Steps to reproduce:**

**Related code:**

The List Code
```
      <div *ngIf="hasComics">
      <ion-list>

        <ion-item *ngFor="let comic of comics" (click)="viewCharacter({'key':comic.id, 'rev':comic.rev })">
            <ion-avatar item-left>
               <img [src]="comic.image">
            </ion-avatar>
            <h2>{{ comic.name }} </h2>
			 <p>{{comic.address}}</p>
			 <ion-note>Category: {{comic.category}} </ion-note> 

         </ion-item>

      </ion-list>
   </div>
```
Form Code
```
          <div *ngIf="!hideForm">
         <form [formGroup]="form" (ngSubmit)="saveComic()">

            <ion-list>
               <ion-item-group>
                  <ion-item-divider color="light">Category</ion-item-divider>
                  <ion-item>
                     <ion-label>Please select: </ion-label>
                     <ion-select
                        class="select"
			interface="action-sheet"
			formControlName="category"
		        block
			[(ngModel)]="comicCategory">
			<ion-option value="Education">Education</ion-option>
			<ion-option value="Hospitality">Hospitality</ion-option>
			<ion-option value="Information Technology">Information Technology</ion-option>
			<ion-option value="Lodge/Leisure">Lodge/Leisure</ion-option>
			<ion-option value="Other">Other</ion-option>
                     </ion-select>
                  </ion-item>
               </ion-item-group>


               <ion-item-group>
                  <ion-item-divider color="light">Business Name</ion-item-divider>
                  <ion-item>
                     <ion-input
                        type="text"
                        placeholder="Enter a name..."
                        formControlName="name"
                        [(ngModel)]="comicName"></ion-input>
                  </ion-item>
               </ion-item-group>


               <ion-item-group>
                  <ion-item-divider color="light">Attach Logo</ion-item-divider>

                  <ion-item>
                     <a
                        ion-button
			block
			margin-bottom
			color="secondary"
			(click)="selectImage()"><ion-icon item-left name="image"></ion-icon>
			   Select Logo
                     </a>
                  </ion-item>

                  <ion-item>
                     <img [src]="nameImage">
		      <input type="hidden" name="image" formControlName="image" [(ngModel)]="comicImage">
                  </ion-item>
               </ion-item-group>



               <ion-item-group>
                  <ion-item-divider color="light">Description</ion-item-divider>
                  <ion-item>
                     <ion-textarea
                        placeholder="Briefly describe your business/institution"
			formControlName="description"
			rows="6"
			[(ngModel)]="comicDescription"></ion-textarea>
                  </ion-item>
               </ion-item-group>


               <ion-item-group>
                  <ion-item-divider color="light">Address</ion-item-divider>
                  <ion-item>
                     <ion-textarea
                        placeholder="P.O 666, Lusaka, Zambia"
			formControlName="address"
			rows="6"
			[(ngModel)]="comicAddress"></ion-textarea>
                  </ion-item>
               </ion-item-group>


               <ion-item>
                  <button
                     ion-button
		     color="primary"
		     text-center
		     block
		     [disabled]="!form.valid">Save Contact</button>
               </ion-item>



            </ion-list>



         </form>
      </div>
```

**Other information:**
The same app when run on Samsung S4 (Android Version 5.0.1) and Samsung S5(Android Version 6.0.1) performs as expected. As seen on screen shots below.

S4 Form Screen Shot
![s4 form](https://cloud.githubusercontent.com/assets/21077222/21637866/942de7ac-d271-11e6-8bd7-a2b734d55c31.png)
S4 List Screen Shot
![s4 list](https://cloud.githubusercontent.com/assets/21077222/21637867/943f5de8-d271-11e6-8fb4-11bf64ed9afa.png)

S5 Form Screen Shot
![s5 form](https://cloud.githubusercontent.com/assets/21077222/21637868/9445615c-d271-11e6-84f5-2ae17db6e59f.png)
S5 List Screen Shot
![s5 list](https://cloud.githubusercontent.com/assets/21077222/21637869/9466f3e4-d271-11e6-91f1-988359f250ed.png)

Samsung Note 3 (Android version 4.3) , screen shots.
Note 3 Form Screen Shot
![note 3 form](https://cloud.githubusercontent.com/assets/21077222/21638218/2141e3c2-d273-11e6-9f02-05334f4545b5.jpg)

Note 3 List Screen Shot
![note 3 list](https://cloud.githubusercontent.com/assets/21077222/21638219/2159b7f4-d273-11e6-9346-3ebb2677b384.jpg)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed

```

**Comment by mhartington** [comment]
This is probably due to the it being android 4.3.

Ionic 2 supports android 4.4 and up, but if you need to support older android (4.1-4.3), you must add crosswalk. Please add crosswalk
