### ISSUE TITLE
Content scrollTo is not working with a duration of 0 ms

### ISSUE THREAD

**Issue by lujakob** [driftyco/ionic#9864]
**Ionic version:** 
[x ] **2.0.0.rc4**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
scrollTo method of the Content component is not working with a duration of 0 ms

**Expected behavior:**
scrollTo method of the Content component should scroll to desired offset value with a duration of 0 ms just as it did before

**Steps to reproduce:**
Please check this plunkr to reproduce: 
[http://plnkr.co/edit/enTPjg3zOu9Tb5qZ6AUx?p=preview](http://plnkr.co/edit/enTPjg3zOu9Tb5qZ6AUx?p=preview)
**Related code:**

```
    // doesn't work
    this.content.scrollTo(0, 200, 0);

    // works
    // this.content.scrollTo(0, 200, 1);
```

**Comment by mhartington** [comment]
Should be fixed in master.
Thanks.

https://github.com/driftyco/ionic/commit/14eb2fde1d2dbbae0b5c9e961538d5b23c565be5

**Comment by manojbhardwaj** [comment]
<ion-scroll scrollX="true" style="overflow: scroll;white-space: nowrap; height: 60px" >
        <div style="border-bottom: 1px solid #f2f2f2;">
          <ion-segment *ngIf="mcqdata" color="appmaincolor">
                <ion-segment-button  *ngFor="let mcq of mcqdata; let i=index;"  [id]="mcq.ques_id"  value="{{mcq.ques_id}}" (ionSelect)="selectsegment(mcq,i)"  [ngClass]="{'active': selectedIdx == i}">
                    <strong>Queastion{{i+1}}</strong>
                </ion-segment-button>
              </ion-segment>
            </div>
            </ion-scroll>

//SCROLL TO LEFT NOT WORK FOR ME 

scrollmain(elementId,index){
    console.info('elementId',elementId)
      let elem = document.getElementById(elementId);
      var box = elem.getBoundingClientRect();
       var body = document.body;
      var docEl = document.documentElement;
       var scrollleftside = window.pageXOffset || docEl.scrollLeft || body.scrollLeft;
       var clientleftside = docEl.clientLeft || body.clientLeft || 0;
       var left  = box.left +  scrollleftside - clientleftside;
       var cDim = this.content.getContentDimensions();
       var scrollOffset = Math.round(left) + cDim.scrollLeft - cDim.contentLeft;
       this.content.scrollTo(scrollOffset, 0, 800);
}

**Comment by dimitri320** [comment]
@mhartington still not working. I'm using ionic 3.9.2
