### ISSUE TITLE
padding-right of iOS text inputs without clearInput should not be increased

### ISSUE THREAD

**Issue by karlschwaier** [driftyco/ionic#9865]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
On iOS padding-right of all text inputs is increased to make some space for the clear input icon. In the styles for Material Design it's only when attribute ``clearInput`` is set.

**Expected behavior:**
padding-right should only be increased when ``clearInput`` is set.

**Steps to reproduce:**
http://run.plnkr.co/OTfGP0NcBH1KHoeH/ on iOS (or Google Chrome's device mode emulating an iPhone)
http://plnkr.co/edit/qi03Zp?p=preview

**Related code:**

iOS (attribute selector is missing):
```
.input-ios .text-input {
  padding-right: $text-input-ios-input-clear-icon-width;
}
```
https://github.com/driftyco/ionic/blob/master/src/components/input/input.ios.scss#L162-L164

Material Design:
```
.input-md[clearInput] .text-input {
  padding-right: $text-input-md-input-clear-icon-width;
}
```
https://github.com/driftyco/ionic/blob/master/src/components/input/input.md.scss#L158-L160

**Comment by brandyscarney** [comment]
Thanks for the detailed issue! This will be fixed in the next release. :)
