### ISSUE TITLE
Enable to view ion-icons on MS-Edge

### ISSUE THREAD

**Issue by almost92** [driftyco/ionic#9866]
Hi,

I am currently developing a UWP and ion-icons don't appear on ms-edge, although they do appear on chrome (when serving).

Any ideas?

Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45

**Comment by mhartington** [comment]
Hi, can you please fill out the rest of the issue template. How are we to know how to replicate this? Our starters and samples do not have this issue. Please open a new issue with the issue template filled out.

**Comment by BramVanroy** [comment]
I vote to reopen.

I can confirm this issue. Using the JS library:

`<script src="https://unpkg.com/ionicons@4.3.0/dist/ionicons.js"></script>`

and any icon

`<ion-icon name="close"></ion-icon>`

the icon is not displayed. The console returns the following error:

> DOM7009: Unable to decode image at data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAQAAAAfQ//73v/+BiOh/AAA= as MIME: image/webp.
