### ISSUE TITLE
bug: component directive weird padding on top

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#9867]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>After I upgraded to RC4 and when some element is injected as component directive then  ~10px padding is added on top of the directive component that didn't happen before. This does not seem to happen on iOS.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Please complete the issue template by providing some more information (code, screen shots, steps to reproduce).
