### ISSUE TITLE
Ionic serve does not refresh app

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic#9873]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When calling ionic serve it opens a browser and watches my files but does not reload the app on changes, manual reloading however works. The only interesting output seems to be 
`[18:15:17]  error sending client ws - Cannot read property 'readyState' of undefined`
**Expected behavior:**

Automatic reloading of the served app on file changes.
**Steps to reproduce:**

Run ionic serve

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.1.0
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

```

**Comment by mhartington** [comment]
Hmm, been running on windows all after noon, without any issues.
Either way, would you mind opening this on the [app-scripts repo](https://github.com/driftyco/ionic-app-scripts).
