### ISSUE TITLE
Ionic app renders white screen on devices having ram less than 512 mb

### ISSUE THREAD

**Issue by SumantaBee** [driftyco/ionic#9880]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi! My ionic app is not suuporting android phones having ram less than 512 mb. How do I extend the support to these devices? The app renders a white screen on these devices. 
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by SumantaBee** [comment]
Posting from mobile and it is urgent. could not edit the template. sorry

**Comment by graphefruit** [comment]
@SumantaBee 
1. With which devices do you have tried?
2. With Android-Version are you running on this devices?
3. Have you tried to attach the Google-Chrome and Inspect the devices to catch any error?

**Comment by dylanvdmerwe** [comment]
Have you tried using Crosswalk?

**Comment by SumantaBee** [comment]
Android version is jellybean 1 and the device is Samsung. Very old device.

**Comment by graphefruit** [comment]
@SumantaBee If you want to get a real help, you should starting giving some more and detailed explanation.
With this information you cant get any further to reach more help.
If you could tell the Samsung-Device and give me an answer on my question `3` we can maybe clearify problems.
Also try to create a new starter project and see if the problem happens there the same.
Also you could try and install the `crosswalk` plugin.

**Comment by SumantaBee** [comment]
@graphefruit I tried the app on 4-5 phones with RAM more than 1GB and the app is working as expected. But the client cannot run it on a 256MB android phone. He can run the app on other devices released after 2013. I'll give a try to crosswalk.

**Comment by graphefruit** [comment]
@SumantaBee The question is, if a simple app can start at all on 256MB-Ram (Ionic1 - starter app).
Or if your app is consuming to much RAM for older devices.
OR older devices make something weird (had this problem with HTML-5-Filesystem on old Samsung devices) Thats why it would be interesting if your App throws any errors, either with debugger attached or with logging / alerting
`window.onerror`

**Comment by SumantaBee** [comment]
@graphefruit  Ok, I'll try to debug it on the faulty devices. I'll ask him to update the webview library as well.

**Comment by jgw96** [comment]
@SumantaBee If possible (not sure of your testing setup) could you test your app without any cordova plugins on that old device? Most likely a cordova plugin is using too much memory, or is trying to do something that that old of a device does not support. On most devices with very limited memory (such as the one here) some things that an android device with 1gb or more of ram supports will not work simply because of the lack of resources on that device.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#45
