### ISSUE TITLE
PWA: Splitting main.JS into 2 files - libraries & business logic

### ISSUE THREAD

**Issue by astec** [driftyco/ionic#9889]
**Ionic version:**  (check one with "x")
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] feature request

**Current behavior:**

Currently when we run `ionic build browser --prod` we get 1 `main.js` file that contains both libraries (_Angular, Ionic, etc._) and application logic/UI(_AOT_).

**Expected behavior:**

Developers often update application without changing libraries. Having production bundle split in 2 (_for example libraries.js & app.js_) would allow:

- Speedup deployment as most of the time developers can upload just changed app.js part. (_for example when deploy to Google AppEngine just changed files are uploaded_).  On 2G connection few extra MB do make a difference.
- Minimize traffic & response time for clients for requests after an app updated.

An additional 1 HTTP(s) request should not be a big deal and not a problem at all for those who use HTTP2 (_you should_).

Of course a proper lazy loading with multiple modules would be a more generic and a preferable solution but splitting into 2 bundles can be a good interim or "settings free by default" alternative.

**Steps to reproduce:**
`ionic build browser --prod`

**Other information:**
```
Ionic RC4
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#623
