### ISSUE TITLE
collection-repeat, performance problem

### ISSUE THREAD

**Issue by DimaKoval** [driftyco/ionic#9891]
**Ionic version:**
[x] **1.x** (1.3.2)
[ ] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
little jumps while scrolling, not smooth experience even with iPhone 7

**Expected behavior:**
smooth scroll

**Steps to reproduce:**
http://plnkr.co/edit/BlNR4M?p=preview

**Other information:**
i'm using ionic-cache-src plugin, maybe there is a problem, but with regular img+ng-src code it works even slower(in my opinion) than ionic-cache-src+background style property

**Ionic info:**
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38 

i just wanted to know is it known issue, or i'm the only one experiencing such behavior

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#44
