### ISSUE TITLE
Ionic 2 Application error 

### ISSUE THREAD

**Issue by magnusmel** [driftyco/ionic#9895]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic 2 starter template cutepuppypics was generated, However on running the 
`ionic run android `

The app does get built and installed on the mobile device. 

But on launching the app in the device, it throws an Application error.
This has started to appear quite recently. 
Any help will be appreciated.

BTW I am using nvm to manage my node installations. Could this be a factor ?
 
Same issue posted in more details on 
[](http://stackoverflow.com/questions/41440866/ionic2-application-error)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	openSUSE project Description:	openSUSE Leap 42.2 
Node Version: v6.9.2
```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#630
