### ISSUE TITLE
fail to set cursor position in the phone

### ISSUE THREAD

**Issue by birdplane9527** [driftyco/ionic#9896]
**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
I want to set cursor position in a textarea with the method setSelectionRange,it works fine in chrome or safari on my mac，but it can't work in my iphone6s(10.2).

in chrome:
![](http://wx2.sinaimg.cn/large/6d691ee6ly1fbgzr7xhxrj20ik0f2qbb.jpg)

iphone6s:
![](http://wx2.sinaimg.cn/large/6d691ee6ly1fbgzx3c5caj20ku112gr5.jpg)

**Related code:**

```
setSelectionRange(input, selectionStart, selectionEnd){
	  if (input.setSelectionRange) {
	    input.focus();
	  	input.setSelectionRange(selectionStart, selectionEnd);
	  } else if (input.createTextRange) {
	    var range = input.createTextRange();
	    range.collapse(true);
	    range.moveEnd('character', selectionEnd);
	    range.moveStart('character', selectionStart);
	    range.select();
	  }
	}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by astec** [comment]
@birdplane9527, Does `setSelectionRange()` work on iPhone outside of Ionic?

**Comment by birdplane9527** [comment]
@astec I tested and it doesn't work either.it should be the IOS problem.

**Comment by jgw96** [comment]
Hello all! Going to close this for now as this is not an Ionic issue but instead a bug in your custom code. Thanks for using Ionic!
