### ISSUE TITLE
NgStorage, NativeStorage and Events

### ISSUE THREAD

**Issue by genesisoft** [driftyco/ionic#9898]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm having problems with Storage, NativeStorage and Events aren't working well in real devices (IOS, ANDROID). I followed the tutorial by Ionic Framework site, in web browser works well, but in real devices no work.
**Expected behavior:**

The Storage, NativeStorage and Events  need working.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-storage#65
