### ISSUE TITLE
ionic 2.1.18 does not install properly in Fedora 25

### ISSUE THREAD

**Issue by tonydiep** [driftyco/ionic#9900]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

* Ionic 2.1.18 upgrade or fresh install fails on Fedora 25 leaving ionic unuseable.
* I suspect it's related to npm config set prefix assuming /usr vs /usr/local

Errors start with
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/ansi-79f49b0e' -> '/usr/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
n

* It seems install package is assumes /usr/lib/node_modules is where node_modules are kept
* using npm config set prefix /usr/local works BUT other errors crop up as the rest of the node_modules are elsewhere
* Symbolic link from /usr/lib/node_modules to /usr/node_modules does not work

**Expected behavior:**

npm install -g ionic or npm upgrade -g ionic works

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

* workaround is to install ionic@2.1.17

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1839
