### ISSUE TITLE
Create custom component in angular 2 and consume in ionic 2 app

### ISSUE THREAD

**Issue by raparlasiva** [driftyco/ionic#9901]
Is there a way that we can write custom ionic 2 components and maintain them as a separate package that lives outside of an ionic 2 app and be able to consume them across multiple ionic 2 apps 
with npm install customComponentLibrary --save ?

**Comment by mhartington** [comment]
We created this for that reason.

https://github.com/driftyco/ionic-module-template

**Comment by raparlasiva** [comment]
Thank you.  👍
