### ISSUE TITLE
unable get data parsed by [data]='data'

### ISSUE THREAD

**Issue by calidion** [driftyco/ionic#9902]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```js
var data = navParams.get('data');   // no data
```

**Expected behavior:**
```js
var data = navParams.get('data');   // get data
```

**Comment by jsayol** [comment]
Hey @calidion, you're trying to access an attribute but that's not what NavParams is for.

If you're instantiating your component like this:
```html
<my-component [data]="data"></my-component>
```

Then you can grab that attribute with `@Input()`:
```ts
class MyComponent {
  @Input() data;

  someMethod() {
    console.log('data:', this.data);
  }
}
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
