### ISSUE TITLE
Application Error  connection to the server was unsuccessful.

### ISSUE THREAD

**Issue by magnusmel** [driftyco/ionic#9905]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

This is the Ionic 2  starter app - cutepuppypics, worked fine till recently. After upgrading to ionic framework Rc3 , during builds it throws an Error - when I do "ionic run android"

**-Application Error 
connection to the server was unsuccessful. File://android_asset/www/index.html
Tried reinstalling android platform and all.**

I have tried the all the starter templates of ionic 2 and its the same result across 2 different linux machines and windows machine too. 
Interestingly it works fine in the android emulator, however fails on the mobile devices.

Any help will be appreciated.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
**chrome browser output**

Hello Walkthrough Page
main.js:1949 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
cordova.js:1185 deviceready has not fired after 5 seconds.
main.js:25553 Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
(anonymous) @ main.js:25553
t.invokeTask @ polyfills.js:3
e.runTask @ polyfills.js:3
invoke @ polyfills.js:3
main.js:25548 DEVICE READY FIRED AFTER 21651 ms

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**On Opensuse 42.2 Linux machine with nvm installed** 

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.1
Node Version: v6.9.0
Xcode version: Not installed

```
**On windows 8 machine**
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.2
Xcode version: Not installed



```

**Comment by dlaynes** [comment]
Do you have the Device plugin installed?
Does it work with an increased timeout?
  <preference name="loadUrlTimeoutValue" value="700000" />

**Comment by ghenry22** [comment]
Make sure you have the latest android platform.  Remove all plugins.  See if it's the same.  I had this issue caused by the certificate plugin, there are no other errors logged which makes it really hard to track down.  Have seen other reports with other plugins.  The load time out just makes the error throw after a delay generated.  The load timeout may be useful for slow devices or emulators that take a long time to start

**Comment by magnusmel** [comment]
yes it worked, thank a bunch.

**Comment by jgw96** [comment]
Hello @magnusmel , thanks for opening an issue with us! Quick question, so after removing all the plugins it worked for you? Or did you just need to update the android platform?

**Comment by magnusmel** [comment]
I must have uninstalled over 50times the entire platform and plugins. But the real culprit was the device plugin had got removed when I first removed all plugins and for some reason was missing in the config.xml.
