### ISSUE TITLE
Preventing a state from leaving when changing Tab

### ISSUE THREAD

**Issue by Akyraah** [driftyco/ionic#9908]
Hello everyone !

**Ionic version:**  (check one with "x")
[x] **1.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

I'd like to prevent a state change when leaving a specific view.
I read a lot on the internet about issues on the matter, mainly that event.preventDefault() used in $stateChangeStart doesn't actually prevent the change of state but prevent only the loading of the destination page.

To illustrate this, I tried to put my code in this preview :
[https://plnkr.co/edit/qpROWVWRBiO2WfmLK87N?p=preview](https://plnkr.co/edit/qpROWVWRBiO2WfmLK87N?p=preview)
Unfortunately, I can't get it to work in the preview and I'm not sure why...

The main part of the code is : 

```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
		if (fromState.url == "/specific_view"){
			if (toState.url != "/specific_view"){
				
			console.log("toState: " + JSON.stringify(toState));
			console.log("toParams: " + JSON.stringify(toParams));
			console.log("fromState: " + JSON.stringify(fromState));
			console.log("fromParams: " + JSON.stringify(fromParams));
			
			event.preventDefault();
			
			$state.transitionTo("tabs.specific_view", null, {notify:false});
			$state.go('tabs.specific_view');
			return;
			}
		}
	});
```

It seems to work when leaving from the nested state to the parent state (by firing a backButton) but it doesn't when I'm changing tab.

Thank you for your time,

Aurélien

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#43
