### ISSUE TITLE
Google Analytics fails with `undefined` rejection

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#9910]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Google analytics method `startTrackerWithid` rejects, with undefined error - for a correct ID

**Expected behavior:**
Google analytics to reject with some information, or resolve with no information

**Steps to reproduce:**

Run the following code using `ionic run browser`

**Related code:** (put in a correct ID)

```
GoogleAnalytics.startTrackerWithId(config.googleAnalytics).then(
    res => console.log("startTrackerWithId res", res),
    error => console.log("startTrackerWithId error", error),
);
```

**Other information:**
[Forum link](https://forum.ionicframework.com/t/google-analytics-fails-with-undefined-error/75454)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jsayol** [comment]
Are you waiting until the platform is ready before using the Google Analytics plugin?

In any case, you should probably open this issue on the ionic-native repo: https://github.com/driftyco/ionic-native.

**Comment by AmitMY** [comment]
Thanks, opened a new one https://github.com/driftyco/ionic-native/issues/940
