### ISSUE TITLE
RC4 Datepicker doesn't show month field until scrolled

### ISSUE THREAD

**Issue by Tarang** [driftyco/ionic#9911]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a datepicker:

```
<ion-item>
      <ion-label>Date</ion-label>
      <ion-datetime displayFormat="DD/MM/YYYY" min="1921" max="2016" [(ngModel)]="dob"></ion-datetime>
    </ion-item>
```

It looks like this when you tap the field:

![initial](https://cloud.githubusercontent.com/assets/1616628/21742127/ea19b412-d4f0-11e6-9311-42b83653b04f.png)

Once you scroll the dates it fixes itself:

![fixeditself](https://cloud.githubusercontent.com/assets/1616628/21742135/09f9aa9e-d4f1-11e6-8c14-1d50a2b3c1bd.png)

**Expected behavior:**

It should not need the user to scroll first

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jsayol** [comment]
Hi @Tarang, I just tried this and it's certainly an issue with RC.4 but it has already been fixed, so it should be working fine when RC.5 comes out.

You can give the latest nightly a try to see for yourself:

 `npm install ionic-angular@nightly --save --save-exact`

**Comment by jsayol** [comment]
This actually seems to be a duplicate of #9876

**Comment by Tarang** [comment]
Awesome! Thanks jsayol. I also did not know I could use nightlies that way so it is quite helpful to know that.
