### ISSUE TITLE
[BUG] having two <ion-content> in a modal hides top

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic#9913]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When having two <ion-content> in a modal, it hides 46 pixels of the first content behind the header

**Expected behavior:**
Modals to show the content fully

**Steps to reproduce:**
http://plnkr.co/edit/PNJ3SSe3YD8ITjnkvYZz?p=preview

**Other information:**
The solution is just to remove the second one.
I just didn't see any documentation saying I am not allowed to have two ion-content, so I think it would be great if you add one

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! It is actually recommended to not have more than one `ion-content`. What is your use case for having multiple contents?

**Comment by AmitMY** [comment]
@jgw96 I have no use case for multiple conents. However, I could not find a place stating "recommended to not have more than one ion-content."

I think it is important it would be documented, as I could not understand my problem for a while.

If it is documented, I probably missed it, and this issue is just wasting your time :)

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-site#956

**Comment by jgw96** [comment]
Hey @AmitMY im moving this to the site repo as its a docs issue. We do mention in the docs for the `ion-header` component that you should only have one `ion-content` but we don't actually mention that in the docs for the `ion-content` component itself, which does not make sense (: . Thanks again for bringing this to our attention!
