### ISSUE TITLE
Google Maps Native - Error: EXCEPTION: Uncaught (in promise): [object Object])

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic#9915]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've installed the plugin as instructed on the official docs :
https://ionicframework.com/docs/v2/native/google-maps/

However, I receive this:

> EXCEPTION: Uncaught (in promise): [object Object])

I've Googled it, it seems that many users has the same issue, so I believe that it's a bug that should be reported.

**Expected behavior:**

Show the map.

**Related code:**

SAME ONE in the documentation.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jsayol** [comment]
Hi @HamzaLJ! It might be better if you open this issue on the ionic-native repo instead: https://github.com/driftyco/ionic-native

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#950
