### ISSUE TITLE
ion-slides: tabbing between inputs on different slides messes up layout

### ISSUE THREAD

**Issue by fikkatra** [driftyco/ionic#9917]
**Ionic version:**  (check one with "x")
[x ] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
When using ion-slides, if each slide contains an input and you hit 'tab' (or 'Next' on Android keyboard), the layout is messed up. It shows half of the current slide and half of the next slide.  

Here's a [plunkr](https://plnkr.co/edit/tFArcI4f0aUelJTyvclC?p=preview) illustrating the problem.

![image](https://cloud.githubusercontent.com/assets/8104336/21750834/edf8298e-d5bc-11e6-8d89-07cf384529ca.png)

**Expected behavior:**
Either ignore the tab event if the next input is on another slide, or move to the slide properly.

**Steps to reproduce:**
Open plunkr
Put cursor in input field
Hit 'tab'

**Ionic info:**:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v5.5.0
Xcode version: Not installed

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will take a look into this issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#42
