### ISSUE TITLE
RC4 - [BUG] - Plugin Network not installed

### ISSUE THREAD

**Issue by FanYeeChok** [driftyco/ionic#9918]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**

1.  Install plugin
`ionic plugin add cordova-plugin-network-information`
2. Write following code
```
import { Network } from 'ionic-native';

 if (Network.connection === 'wifi') {
      console.log('we got a wifi connection, woohoo!');
}
```

3. Error
`[Warning] Native: tried calling Network.connection, but the Network plugin is not installed. (ionic.native.min.js, line 4) [Warning] Install the e plugin: 'ionic plugin add cordova-plugin-network-information' (ionic.native.min.js, line 4)`

Note: Tried `Network.type` also display same error.

**Other information:**
Plugin using
https://ionicframework.com/docs/v2/native/network/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by jsayol** [comment]
Hi @FanYeeChok! It might be better if you open this issue on the ionic-native repo instead: https://github.com/driftyco/ionic-native

**Comment by AndreasGassmann** [comment]
The plugin works fine for me with Ionic RC4.

Can you try updating to the latest Ionic Native version? Maybe also update your ionic CLI.

FYI: 3 weeks ago the API of the Network Plugin changed. It is now `Network.type` instead of `Network.connection`. https://github.com/driftyco/ionic-native/commit/ec5e27be4b1455ad5b0ee4ea2da5592e63be3dea .

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-native#951
