### ISSUE TITLE
Tabs do not work inside ionContent

### ISSUE THREAD

**Issue by gnomeontherun** [driftyco/ionic#992]
I'm not sure if this is by design or not, but if you use `<ion-tabs>` inside of `<ion-content>` the tabs will render initially but not be able to switch between tabs. Removing the `<ion-content>` directive makes the tabs functional. Also, the tabs do not pick up the existing ionNavBar and add padding, so I have to apply CSS.

Example: http://codepen.io/gnomeontherun/pen/oluLx?editors=101

**Comment by gregoiremotot** [comment]
Hi !
I had the same problem, I fixed it like this.
```
<ion-view view-title="Tabs">
    <ion-pane>
        <ion-tabs class="tabs-top">

            <!-- Tab 1 -->
            <ion-tab title="Tab 1" href="#/tab/tab1">
                <ion-nav-view name="tab-tab1">
                    <ion-content>
                        Tab 1 content
                    </ion-content>

                </ion-nav-view>
            </ion-tab>


            <!-- Tab 2 -->
            <ion-tab title="Tab 1" href="#/tab/tab2">
                <ion-nav-view name="tab-tab2">
                    <ion-content>
                        Tab 2 content
                    </ion-content>
                </ion-nav-view>
            </ion-tab>
        </ion-tabs>

    </ion-pane>
</ion-view>
```

**Comment by celso-wo** [comment]
thanks @gregoiremotot :+1: it's worked for me!

**Comment by webantz** [comment]
Hi

I added a div below the ion-content

<ion-view title="Tabs">
        <ion-content>
          <div class="list" style="margin-top:28px;">
               &nbsp;
           </div>

Will this solve the problem
