### ISSUE TITLE
$ionicPlatform.ready() gets called immediately in browser

### ISSUE THREAD

**Issue by imgx64** [driftyco/ionic#9920]
**Ionic version:**
[x] **1.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When running app in browser using `ionic serve`, the callback of `$ionicPlatform.ready()` gets called immediately. This usually doesn't cause any problems, but some angular plugins suddenly broke in the browser (but kept working correctly on hardware) when I added jQuery instead of Angular's jqLite.

After some debugging, I found the issue is that inside `app.run()`, `angular.element( ... ).scope()` returns undefined (but only when using jQuery and running in a browser), and some angular plugins didn't like that. I solved the issue by adding a `$timeout( ... , 0)` inside `$ionicPlatform.ready()`.

**Expected behavior:**
In [here](https://github.com/driftyco/ionic/blob/11d21583bad5d38425111042e0991ddb64f59bb5/release/js/ionic.js#L2468), I suggest deferring calling `onPlatformReady()` by a browser tick by using a timeout/promise/etc.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#41
