### ISSUE TITLE
child and parent views data is bind unexpectedly

### ISSUE THREAD

**Issue by comfortme** [driftyco/ionic#9921]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
i push a page with parameters (object) and grab them in the second page with navparams.
if i change this object in the second page it is changed in the first page too. how is that possible without me doing so? or is it expected behavior?

**Expected behavior:**
i think first page data should not change.

**Related code:**

```
insert any relevant code here
`<div *ngFor="let control of controls;let i=index">
    <ion-list-header *ngIf="control.header==true">{{control.label}}</ion-list-header>
    <button ion-item (click)="showDeviceControlPage(control)" *ngIf="control.header==false">{{control.label}}<ion-note item-right>{{control.value}} {{control.units[0]}}</ion-note></button>
  </div>

  showDeviceControlPage(control) {
    this.navCtrl.push(DeviceControlPage, { control: control });
  }
//from the DeviceControlPage i get the object
this.control = this.navParams.get('control');
//so if i change this.control.value from the DeviceControlPage it is changed in the first page too.

`


**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
```

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Can you create a [plunker](http://plnkr.co/edit/z0DzVL?p=preview) that demonstrates this issue please?

**Comment by comfortme** [comment]
ok i think i did it
http://plnkr.co/edit/ZnBNWXTcPkZD7Nvzfe4s?p=preview
click a button change the label from second page and pop back.

**Comment by loopezz** [comment]
I also can confirm this:
https://plnkr.co/edit/Gg4iuH?p=preview

**Comment by jsayol** [comment]
Hi there! This is most definitely the expected behavior. Objects are always passed by reference in JavaScript, unless you explicitly make a (deep) copy.

**Comment by comfortme** [comment]
@loopezz that works. thank you.

**Comment by mhartington** [comment]
Closing as this is the expected behavior
