### ISSUE TITLE
$ionicView.beforeLeave not called when url parameter is changed

### ISSUE THREAD

**Issue by jovankrunic** [driftyco/ionic#9922]
**Ionic version:**  (check one with "x")
[x] **1.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
When going back to a previous view, using the back button, code in `$ionicView.beforeLeave` block of the view which is being left is not executed (`$ionicView.beforeLeave` of the appropriate controller is never triggered) in case when URL parameter of the abstract state is different between these views ( when using URL parameter inside for URL of the app's abstract state e.g. `url: '/{app:foo|bar}'`).

Update: `$ionicView.leave` also not triggered.

**Expected behavior:**
Event `$ionicView.beforeLeave` of the view's scope should always be triggered whenever the view is being left while other view of the app is visited.

**Steps to reproduce:**

Using the demo do the following steps:

1. Click the first list item (*Foo's Playlist*)
2. Click *Back*
*Leaving playlist* alert will be shown
3. Click the second item (*Bar's Playlist*)
4. Click *Back*
No alert shown (`$ionicView.beforeLeave` not triggered)

Demo: 
http://plnkr.co/edit/Nytn2QdbiST7kMNG6AkK?p=preview

**Related code:**

abstract state `app` (app.js):
```
  $stateProvider.state('app', {
    url: '/{app:foo|bar}',
    abstract: true,
    templateUrl: 'menu.html',
    controller: 'AppCtrl'
  })
```

`$ionicView.beforeLeave` block (controllers.js):
```
  $scope.$on('$ionicView.beforeLeave', function () {
    $scope.showAlert();
  });
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#40
