### ISSUE TITLE
View isn't updated after upgrade from ionic-angular 2.0.0-rc2 to 2.0.0-rc4

### ISSUE THREAD

**Issue by HuongCu** [driftyco/ionic#9929]
I have just upgraded ionic version from 2.0.0-rc2 to 2.0.0-rc4.  All the pages with late bindings stop working. For eg: 

I had this.xService.yFunction(term).subscribe(result => {
         this.list = result;
        });
the codes were executed, the list got expect data but view (ion-list with *ngFor) wasn't updated. 
And there was no affect when using setTimeout or ngZone . Everything worked properly in version 2.0.0-rc2.

Thanks,
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**``

**Comment by mhartington** [comment]
How could I recreate this? Could you provide either a git repo with a demo or plunkr?
Could you test out the latest nightly release

```
npm install ionic-angular@nightly 
```

**Comment by HuongCu** [comment]
Thanks for your response. 
It was my fault.  There was argument changes in the subscribe method of event module (ionic-angular) which I forgot to make appropriate update.  I will close this issue.
Thanks,
Huong
