### ISSUE TITLE
overflow-scroll can not set dynamically

### ISSUE THREAD

**Issue by johnnynode** [driftyco/ionic#9930]
**Ionic version:**  (check one with "x")
[x] **1.x**
[ ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
<br>
There it is :
```javascript
<ion-content overflow-scroll="the issue is here,can't set synamically only string type supported" scroll="same issue here only true and false, variable not supported"></ion-content>
```
can not use expression to set in different platforms or situations. And,
can not use `ng-attr-overflow-scroll="{{expression here}}"` , not working as well.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-v1#231
