### ISSUE TITLE
RC5: ion-slides misses some Swiper functionality

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic#9933]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.0.0-rc.5**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
As `getSlider()` is deprecated and not all of Swiper's api's are implemented in RC5, some functionality has been lost.

**Expected behavior:**
I'd like to be able to use all of Swiper's api's, as I'm currently unable to upgrade to RC5.

**Steps to reproduce:**
Example Swiper implementation that was possible in RC4 but is not possible in RC5, using `<Swiper>.params.control`:

Demo:
http://idangero.us/swiper/demos/23-thumbs-gallery.html
Source:
https://github.com/nolimits4web/Swiper/blob/5a1b28a84e9504e49975c8f6a85bf90183f13fea/demos/23-thumbs-gallery-loop.html

**Related code:**

```ts
  @ViewChild('sliderGrid') public sliderGrid: Slides;
  @ViewChild('sliderHeader') public sliderHeader: Slides;

  // This works in RC4 to sync two sliders
  public ngAfterViewInit() {
    const header: any = this.sliderHeader.getSlider();
    const grid: any = this.sliderGrid.getSlider();
    header.params.control = grid;
    grid.params.control = header;
  }

  // This works in RC4 to check if it's currently animating
  if ((<any>this.sliderHeader.getSlider()).animating) {
    return;
  }
```

**Ionic info:**

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

PS: Can we please get up to date angular compatibility (and zone, rxjs) :)
Really great work on the treeshaking!

**Comment by comfortme** [comment]
for example my app uses onlyExternal option. is there a way to use it in rc5 ?

**Comment by Manduro** [comment]
I've submitted a PR for the `control` functionality that was lost in RC5 (#9983). I suggest anyone that misses other `Slides` functionality does the same :).

**Comment by Manduro** [comment]
I will close this issue as the missing `control` this was about has returned in the latest nightly, and the Ionic team is actively working on getting any missing options back to work (e.g. https://github.com/driftyco/ionic/commit/2d26edb679ddf990f6b330c7c9840d8fd9117e4b).

Anyone who is missing other options in the new slides, please create a separate issue or even better, create a PR ;).
