### ISSUE TITLE
ionic native Network (Network.type) not working

### ISSUE THREAD

**Issue by YasirPanjsheri** [driftyco/ionic#9934]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Network.type shows an error: Property 'type' does not exist on type 'typeof Network'!
**Expected behavior:**

it should display the type of connection
**Steps to reproduce:**

**Related code:**
```
import { Network } from 'ionic-native';

let connectSubscription = Network.onConnect().subscribe(() => {
  console.log('network connected!'); 
  setTimeout(() => {
    if (Network.type === 'wifi') {
      console.log('we got a wifi connection, woohoo!');
    }
  }, 3000);
});

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.2.1
Xcode version: Not installed
```

**Comment by Manduro** [comment]
Are you running the latest ionic native version? The API for the Network connection type was changed in 2.2.12, so you'll need to run that version or later for `Network.type` to work. Prior to 2.2.12 you could use `Network.connection`.

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-native#958
