### ISSUE TITLE
docs: Error in navigation structure for recent release

### ISSUE THREAD

**Issue by Youtch** [driftyco/ionic#9936]
**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,
in various docs of components I get a lot of times the navigation  404 error when I click some link to go to other components docs pages. 
I thinks that is because the doc for the LATEST release  doesn't have the same path that the requested path.
- http://ionicframework.com/docs/v2/api/navigation/NavPush/ can't be resolve in http://ionicframework.com/docs/v2/api/navigation/NavParams/ I can be resolve by clicking in "NavPush" the left-side-bar...
- So it can be resolved by typing : http://ionicframework.com/docs/v2/api/components/nav/NavPush/ 

This error could is caused by the relative path of the links in the footer, because the "navigation components" directives are not displayed in the same directory : there is the Github structure of the two doc files : 
- ionic-site/content/docs/v2/2.0.0-beta.10/api/components/nav/NavParams/ is well.
- ionic-site/content/docs/v2/2.0.0-beta.10/api/components/nav/NavPush/ is exactly in the same directory.

I think there is a STRUCTURAL error that WOULD HAVE to be alter to give a reliable documentation. I suppose this error is repeated in other pages, but I don't have tested all yet !

Regards.</span>

<span is-issue-template></span>

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#957
