### ISSUE TITLE
bug: Native VideoPlayer plugin 'is not installed'

### ISSUE THREAD

**Issue by jguix** [driftyco/ionic#9939]
After successfully installing VideoPlayer native plugin using:

`ionic plugin add cordova-plugin-videoplayer --save`

I can't open videos from my hybrid app. I always get the following message in console.

`Native: tried calling VideoPlayer.play, but the VideoPlayer plugin is not installed.`

My code:

```
      if (this.platform.is('cordova')) {
        // Playing a video.
        VideoPlayer.play(filePath).then(() => {
          console.log('video completed');
        }).catch(err => {
          console.log(err);
        });
      } else {
        window.open(filePath, '_blank');
      }
```

I can see that the plugin is in the platforms/android/assets/www/plugins/cordova-plugin-videoplayer folder as well as in the platforms/android/platform_www/plugins/cordova-plugin-videoplayer folder.

Also created in ionic-native project:
https://github.com/driftyco/ionic-native/issues/959

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-native#960
