### ISSUE TITLE
Add $ionicToast

### ISSUE THREAD

**Issue by ajoslin** [driftyco/ionic#994]
Create an $ionicOverlay service that creates an overlay with some customizability (optional backdrop, delay to show, delay to hide, etc). This will be able to serve the purpose of a Toast component

From there, make the $ionicLoading service be a simple abstraction of $ionicOverlay (and change the API of ionicLoading too, its API is really complicated at the moment).

Will be a breaking change for $ionicLoading, but easy to migrate.

**Comment by michael8090** [comment]
for now we can use [$cordovaToast](http://ngcordova.com/docs/plugins/toast/) , but it will be great if we can show a toast with web technology, which will make it much easier to customise the styles.

**Comment by ag-secret** [comment]
@michael8090 $cordovaToast works on web browser? Because dont think use emulator to test each toast message of the app is a good idea.

**Comment by michael8090** [comment]
@ag-secret nope, but we can use it as a workaround

**Comment by rajeshwarpatlolla** [comment]
I was been searching for a toast notification plugin for my project. I have created a bower component for toast. Please have a look at the <a href="https://github.com/rajeshwarpatlolla/ionic-toast">bower component</a> i have created. I think it might help you.
