### ISSUE TITLE
how to load external url from ionic2 app and listen page event?

### ISSUE THREAD

**Issue by finalxcode** [driftyco/ionic#9948]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hi guys, i want to load external url inside my ionic2 app, though i find  that "cordova-plugin-inappbrowser" provides a web browser view that displays web page, but i want to display this web page as a division of my ionic2 app, then i find that "iframe" tag can embed a webpage inside my ionic2 page, but how to listen web page event? is there a efficient way to achieve this goal than "iframe" tag?

**Expected behavior:**

i expect there is a efficient way to load external url inside my ionic2 app, and listen this web page event.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by ghenry22** [comment]
you are probably better off asking at https://forum.ionicframework.com/

The forums are a better place to ask questions where as github is more focused for specific bug reports.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by finalxcode** [comment]
Thanks, i will ask this question on ionicframework forum.
