### ISSUE TITLE
[bug] When you add max properties into datetime, day column will dissapear

### ISSUE THREAD

**Issue by pawelfrydrych** [driftyco/ionic#9949]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I added "max" properties into my datetime controlls. Then DateTime is hidding a day. When I click in day column and I try to pull it, then day appear. Without 'max' properties everything work's fine.

**Related code:**

```
  <ion-item>
          <ion-label floating color="light">date</ion-label>
          <ion-datetime displayFormat="MM DD, YYYY" name="date" max="2000" formControlName="date"></ion-datetime>
        </ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by brandyscarney** [comment]
Could you try updating to the latest version of the framework [rc.5]() and let me know if you're still having the problem? The conference app uses `max` and it displays the days fine: https://github.com/driftyco/ionic-conference-app/blob/master/src/pages/about/about.html#L26

I tried changing the max to `2000` but it works with that value as well.

**Comment by pawelfrydrych** [comment]
I cannot try it, because when I update project to rc.5 then I have a lot of errors. Ionic Cloud is not supported in RC.5? All imports ( for example import {Auth, User} from '@ionic/cloud-angular'; ) not works.

**Comment by brandyscarney** [comment]
@pawelfrydrych Did you accidentally remove ionic cloud from your `package.json` file when you copied our steps to update?

**Comment by pawelfrydrych** [comment]
@brandyscarney You're right :) Of course, this update resolved problem with datetime. Thanks for quickly response :)

**Comment by brandyscarney** [comment]
@pawelfrydrych Awesome! I'm glad it's fixed. :) I'm going to close this issue.
