### ISSUE TITLE
bug: Only checkbox icon is tappable, not whole row

### ISSUE THREAD

**Issue by lwenke** [driftyco/ionic#995]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  browser

<span ionic-webview style="display:none;">false</span>

<span ionic-description>This problem happens on all platforms.

For the ionic radio controls, when any area in a row is tapped, the radio is selected. The same should happen with checkboxes. At the moment you need to tap the precise location of the checkbox icon to toggle it. Tapping the text next to the checkbox doesn't do anything.

In the css example the text is not inside the label:

http://ionicframework.com/docs/components/#checkbox

But if it is, the text is tappable (though not the area to its right) but the control doesn't look good due to a lacking of css styling.

See the second group of checkboxes:

http://codepen.io/zephyr103/pen/fAzqC/

ion-checkboxes have the text wrapped inside of their tags, but like the example checkboxes the text isn't tappable....

See the third group of checkboxes in the previous codepen</span>

Possible fix:
.item.item-checkbox label { width: 100%; }

http://codepen.io/zephyr103/pen/CyHhG/

**Comment by gaurangvyas** [comment]
Hello Sir,
How to get checkbox value and icon both are  in another page
