### ISSUE TITLE
two or more ion-input inside ion-item get wrong focus

### ISSUE THREAD

**Issue by violabg** [driftyco/ionic#9955]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

it happens on iOS devices or Simulator
it works in browsers
didn't test on Android

if I use more then one 'ion-input' inside a 'ion-item', it dosen't matter which one I click, the focus always get on the last one.
So if I want to edit the first one I have to click it twice. 

**Expected behavior:**

The input clicked get the focus and keyboard.

**Steps to reproduce:**

**Related code:**
```html
<ion-list>
		<ion-item>
			<ion-input type="text" value="hi"></ion-input>
			<ion-input type="number" value="44"></ion-input>
		</ion-item>

		<ion-item>
			<ion-label floating>Floating Label</ion-label>
			<ion-input type="text" value="hi"></ion-input>
			<ion-input type="number" value="44"></ion-input>
		</ion-item>

		<ion-item>
			<ion-label fixed>Fixed Label</ion-label>
			<ion-input type="text" value="hi"></ion-input>
			<ion-input type="number" value="44"></ion-input>
		</ion-item>
	</ion-list>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is happening because each `ion-input` should be wrapped inside its own `ion-item`. You can see examples of this [here](http://ionicframework.com/docs/v2/components/#inputs) in our docs. Hope this helps, thanks again!

**Comment by violabg** [comment]
I know that this is how it is usually used, one input per item.
But I need to implement a row with 2 input, and I see a lot of use cases and app using this approach.
I still fill the frame work should allow it.

**Comment by BenHerron** [comment]
@jgw96 it might pay to document this in the docs, I also hit this same issue and thought it was a bug with the framework. If your using a datepicker and something else like a textbox the behavior is even worse.

**Comment by sgornostal** [comment]
Any workarounds? I'm facing the same problem.

**Comment by swaroopbhave** [comment]
I am facing the same issue, I want to use 1 label and 2 inputs in slider list and facing exact same problem. focus goes on 2nd input first. another problem is if I use col-4, col-4, col-4 to label and 2 inputs.
still it doesn't look properly.
![image](https://user-images.githubusercontent.com/30769962/29002310-f6f4dc58-7abc-11e7-8ca8-cc9367622082.png)

**Comment by abcdurga** [comment]
@violabg  This is not a proper solution but i have fixed it by writing the following style in my .scss file:
.input-cover{
        display: none;
    }

Now i could able to focus on the first input field without any issue.

**Comment by mtshare** [comment]
Same for me! Fixed with @abcdurga solution. Thanks!

**Comment by CompRider** [comment]
Same for me! Fixed with @abcdurga solution. Thanks!

**Comment by agrippa1994** [comment]
@abcdurga You saved a lot of time for me, thank you very much!
