### ISSUE TITLE
iOS notification icons not created by ionic resources --icon command

### ISSUE THREAD

**Issue by ChrisPearce** [driftyco/ionic#9958]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When executing the command "ionic resources --icon", the following icons are not getting generated:
- iPhone Notification (iOS7-10) 20pt - 2x
- iPhone Notification (iOS7-10) 20pt - 3x
- iPad Notification (iOS7-10) 20pt - 2x
- iPad Notification (iOS7-10) 20pt - 3x

**Expected behavior:**
Notification icons would be created.

**Steps to reproduce:**
Execute the command "ionic resources --icon" whilst an icon.png image file is located in the resources folder

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1850
