### ISSUE TITLE
update v2.1.17 to v.2.1.1

### ISSUE THREAD

**Issue by MELAS007** [driftyco/ionic#9963]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I have ionic version 2.1.17, npm 4.0.5 and node 6.9.2 . the issue is in below:

$ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
Path: platforms\android
Package: com.moodle.moodlemobile
Name: Moodle_Mobile
Activity: MainActivity
Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
Running command: "C:\Program Files (x86)\nodejs\node.exe" "D:\Mobile apps\moodlemobile2-3.1.3\hooks\after_prepare\010_add_platform_class.js" "D:/Mobile apps/moodlemobile2-3.1.3"
add to body class: platform-android
Running command: "C:\Program Files (x86)\nodejs\node.exe" "D:\Mobile apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js" "D:/Mobile apps/moodlemobile2-3.1.3"
module.js:471
throw err;
^

Error: Cannot find module 'plist'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (D:\Mobile apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js:10:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
Error: Hook failed with error code 1: D:\Mobile apps\moodlemobile2-3.1.3\hooks\after_prepare\020_add_ios_transport_security.js

and in ionic serve -l got blank !

Moodle told me they use v.2.1.1 and node v.6.9.1

Will I need update ionic v2.1.17 to v.2.1.1 ? or this is a solution to work on v.2.1.17?

any help will be appreciated

MELAS007

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1851
