### ISSUE TITLE
Issue with backdrop using alerts, popups.

### ISSUE THREAD

**Issue by kurnoolmohammadmujahid** [driftyco/ionic#9973]
Hello Team,

I am working in ionic 2.

In my project i am facing problem with backdrop if any alert , popups are opened. 

In my requirement if i touch on button like in alerts OK button then i need to do the other functionality there. so if i touch on backdrop it  will get close and my flow will be in complete.

I am using ionic 2 beta 11 in my project.

help me with a suggestion that how to handle this case. or how to not allow the backdrop to get close if i touch on screen.

**Comment by daveshirman** [comment]
docs: http://ionicframework.com/docs/v2/api/components/alert/AlertController/

enableBackdropDismiss	boolean	Whether the alert should be dismissed by tapping the backdrop.

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

As @daveshirman stated, you can set `enableBackDropDismiss` to `false` to prevent dismissing the overlay from the backdrop.

**Comment by codeReddington** [comment]
@brandyscarney how to i achieve this with an ionic alert with "checkboxes" or "radios's". With a normal alert i have been able to achieve.
