### ISSUE TITLE
Click event not fired on button in footer when keyboard is opened

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic#9978]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.0.0-rc.5

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have this code:
```
<ion-footer>
    <ion-item>
        <ion-input type="text" name="message">
        </ion-input>
    </ion-item>
    <ion-item>
        <button ion-button
                type="button"
                (click)="onMessageSendClick()">
            Send
        </button>
    </ion-item>
</ion-footer>
```
When I click on the input, the keyboard shows. After I type something in the input and click the Send button, its click event is not fired and the keyboard is just closed. The click event fires only when the keyboard is closed.
I have a chat app and can not implement a Send button due to this issue. Issue is described also here and experienced by other users too: https://gist.github.com/Manduro/bc121fd39f21558df2a952b39e907754#gistcomment-1934911
It happens on iOS 10.1.1 and Android 5 and 6.

**Expected behavior:**

**Steps to reproduce:**
Put ion-input and a button inside ion-footer. Click on ion input, type something and then click the button. If you have `console.log('Button Clicked!');` inside the `onMessageSendClick` function, it's not shown. Click works only when keyboard is closed, so second click on button fires click event.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ThorConzales** [comment]
I have similar problem but for me the click action is fired but once the keyboard has been opened then popover that is fired in that click action is no longer popped up. And the same thing works properly on iOS 10.1.1. Working on Android 6.0.1 and Chrome 55. It definitely started to happen once I upgraded to RC5.

**Comment by mhartington** [comment]
This is all noted in this issue 

https://github.com/driftyco/ionic/issues/5432

Closing this and moving the conversation over there.
