### ISSUE TITLE
Passive listeners default in Chrome 56: potential impact on Ionic

### ISSUE THREAD

**Issue by jakub-g** [driftyco/ionic#9980]
Hello, FYI Chrome 56 makes a change in the way event listeners are registered (in order to improve scrolling performance) that is potentially breaking. Hence I'm opening this issue to make it more prominent to all the interested parties. 

https://developers.google.com/web/updates/2017/01/scrolling-intervention

> Making touch scrolling fast by default

> ... We believe the web should be fast by default without developers needing to understand arcane details of browser behavior. In Chrome 56 we are defaulting touch listeners to passive by default in cases where that most often matches the developer's intention. 

> ... if the target of a touchstart or touchmove listener is the window, document or body we default passive to true. This means that code like:
>
>        window.addEventListener("touchstart", func);
>
> becomes equivalent to:
>
>        window.addEventListener("touchstart", func, {passive: true} );

https://twitter.com/__jakub_g/status/819277851274973188

quoting D. Tapuska:

> 2 issues I quickly see pointer events UA detection is bad, and preventclick a touchend handler

**Comment by mhartington** [comment]
Thanks for the heads up. This shouldn't be a major issue since ionic 2 is already using passive event listener

**Comment by jakub-g** [comment]
@mhartington what about Ionic 1?
