### ISSUE TITLE
Tab highlight not properly shown in Chrome

### ISSUE THREAD

**Issue by lleevvyy** [driftyco/ionic#9981]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When md theme is used and tab highlight is enabled for tabs, the width of the highlight is not the same as tab button width, which doesn't look good, especially if tab buttons are not centered in tabbar. It only happens in Chrome when device toolbar (from developer tools) is inactive (so that the app contains in whole chrome tab window).

Screenshot (any tab):
https://img42.com/3XWek
![Screenshot](https://cdn.img42.com/3699c500f4f41a1108d4813ba9ae74e8.png)

Screenshot (last tab): 
https://img42.com/3lZCT
![Screenshot](https://cdn.img42.com/c143a391a7a6131744daff280a44d806.png)

**Expected behavior:**
Tab higlight width should be the same as tab button width. It works properly in Safari and in Chrome when device toolbar (from developer tools) is actived. It means, that it has something to do with the height of the chrome window.

**Steps to reproduce:**
* In conference app, please remove src/pages/tabs/tabs.scss.
* In src/pages/tabs/tabs.html, set tabHighlight="true" for ion-tabs tag
* Ionic serve and open app in chrome
* Make sure, that device toolbar (from developer tools) are inactive for tab with the conference app
* You should see, that each tab button is not properly aligned with the tab highlight and it is best to see on the last tab button.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```
Chrome version is ```55.0.2883.95 (64-bit)```

**Comment by mhartington** [comment]
Thanks for the headsup, we'll take a look

**Comment by brandyscarney** [comment]
@lleevvyy I'm not able to reproduce this. I followed your steps in the issue. Is there something else that I'm missing? 

<img width="1015" alt="screen shot 2017-01-12 at 2 32 24 pm" src="https://cloud.githubusercontent.com/assets/6577830/21905065/268604b4-d8d4-11e6-9d45-ff196c4ee351.png">

**Comment by lleevvyy** [comment]
@brandyscarney Hmm, it seems, that you did everything as I wrote. Maybe, this is related to my retina display? I have newest MacBook Pro 15 and I've made exactly the same screenshot as you did and in my case the width of the tab highlight is invalid:
![Screenshot](https://cdn.img42.com/fd22d03232fe6ed7646dfdcdd0fc308a.png)

**Comment by brandyscarney** [comment]
@lleevvyy I'm running on MacBook Pro (Retina, 13-inch, Early 2015). Do you have any browser extensions that could be messing with the transform? The value on `<div class="tab-highlight">` is the same as mine as well.

**Comment by lleevvyy** [comment]
@brandyscarney I just test in latest Chrome Canary and it works as expected... So maybe you are right, that one of the extensions is doing a mess.... Sorry for trouble, closing :-)

**Comment by lleevvyy** [comment]
@brandyscarney I disabled all extensions, but didn't help. I will try to investigate it, if you think that the issue should be opened, please reopen... Maybe someone else could check whether the issue can be reproduced on other machine?

**Comment by brandyscarney** [comment]
@lleevvyy Are you zoomed in at all in the chrome window? I know we've seen issues with zooming in on the browser before.

**Comment by lleevvyy** [comment]
@brandyscarney haha, you are right! I'm ashamed, that I didn't check that. Sorry once again.  🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by brandyscarney** [comment]
@lleevvyy It's okay. :smile: I once had a chrome extension enabled that broke all of our transform. It happens. 😆
