### ISSUE TITLE
Ionic 2 Auto complete input?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic#9985]
HI! any one help me! please, I want to use Auto complete input feature with ionic 2. 
How can I achieve this. like this
[Source Autocomplete ](https://ng2-ui.github.io/#/auto-complete) 

Basically , I want to implement search and pick contact for input , submit form   to server.

**Comment by mhartington** [comment]
Closing this as it is not an issue, but a support request

Please do not submit support requests here, use one of these channels: 
https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/
