### ISSUE TITLE
Invalid name: "@ionic/app-generators" while installing ionic with npm

### ISSUE THREAD

**Issue by CodePoetPro** [driftyco/ionic#9986]

**Comment by CodePoetPro** [comment]
`C:\Users\foodpoet\Documents\dev\foodie-app>npm install -g ionic@latest
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node
_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic@latest"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5

npm ERR! Invalid name: "@ionic/app-generators"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\foodpoet\Documents\dev\foodie-app\npm-debug.log
`

**Comment by mhartington** [comment]
Hmm, could you try this out.

From an admin prompt, run 

```
npm install -g npm@3.10.10
```

Then in a new admin prompt, run 

```
npm uninstall -g ionic
npm install -g ionic
```

**Comment by CodePoetPro** [comment]
Thanks @mhartington it worked
