### ISSUE TITLE
RC4 Android Emulator Rendering

### ISSUE THREAD

**Issue by Yimiprod** [driftyco/ionic#9987]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x-rc4**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi.

I've recently updated my project from RC3 to RC4 and since then, on Android Emulator, when i build the app, even with crosswalk, every components have a rendering problem, they are invisible.
We still can interact with them, they even turn black when clicked, we can navigate but they are invisible.

After some search it look like it's since the css property contain was added to the projet but i'm not sure.

On a real device we don't have this problem.

**Expected behavior:**
Seeing the app correctly

**Steps to reproduce:**
run any app with `ionic emulate android` with a simulator installed.
inspect with chrome debug, you should see the dom il correct, but on the app only the background should be visible for the headers/body.
Any tappable element will turn black when clicked (button/list-item/...)

[Topic on forum](https://forum.ionicframework.com/t/rc4-android-emulator-rendering/75643)

**Comment by mhartington** [comment]
How could I go about recreating this? What code can I use? We need more info that you have not provided.
Can this be recreated in a starter project? 
What version of android are you testing against?

**Comment by Yimiprod** [comment]
Simulator: Android 6.0 with basic GoogleAPI, without-chrome or native webview.
Cordova: android 6.1.1 with cordova-plugin-crosswalk-webview

Can be reproduced with a starter project `ionic start testApp --v2`

**Comment by Yimiprod** [comment]
@mhartington is it enough information ?

**Comment by mhartington** [comment]
To be fair, the android emulator is notoriously bad and unreliable.
In my test, after 5ish minutes of waiting for it to start up, it finally did and rendered fine.

My guess, if you're seeing rendering issues or just issues in general on the emulator but not a real device, changes are the emulator is to blame.

**Comment by Yimiprod** [comment]
After some test for other project, it look like you're right, the emulator is to blame.
