### ISSUE TITLE
ionic2 RC5 with ion-slides issue

### ISSUE THREAD

**Issue by sidjoshi001** [driftyco/ionic#9988]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request

In RC 5, You guys have been removed **option** attribute method from **ion-slides**, Now how I can implement slidesPerView or freeMode ? Helper me here...!!

till RC4 I am working like this..!!

`public bannerOptions = { loop: true, slidesPerView: 2, freeMode: true, spaceBetween: 5};`

but now what should I do ??

I am also trying like below but still not working..!!

```
@ViewChild('bannerSlider') bannerSlider: Slides;

constructor() {}

ionViewWillEnter(){
 this.bannerSlider.slidesPerView = '2';
}
```

**Html**

```
<ion-slides #bannerSlider>
 <ion-slide *ngFor="let banner of mainBanner.banners">
  <img src="{{mainBanner.imagePath+banner.image}}">
 </ion-slide>
</ion-slides>
```

and I also refer http://ionicframework.com/docs/v2/api/components/slides/Slides/#input-properties, but there are **slidesPerView** and **spaceBetween** not available & also not working

waiting..!!

**Comment by chrisbenseler** [comment]
Same thing here.
Can set slides per view anymore and now there seems to not have a way to access the Slides methods passing a callback, such as 'onTransitionEnd'

**Comment by mhartington** [comment]
@chrisbenseler Yes there are, look at the output event sections

http://ionicframework.com/docs/v2/api/components/slides/Slides/#output-events
`ionSlideDidChange` should suffice

**Comment by AishApp** [comment]
Facing similar issue here. I used onlyExternal and autoplayDisableOnInteraction functions in RC4 using options. In RC5, if i add it in inside html, it is not working.

**Comment by brandyscarney** [comment]
Hey everyone, please take a look at the advanced usage section to add properties that are not inputs: http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced

If it's defined in the source as an `@Input`, see `autoplay` for example, https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L155-L162, it will work by adding it to the `<ion-slides>` component. 

If it's a property of `Slides`, it will need to be defined like the advanced usage example above, see `freeMode`: https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L398

If you see any properties missing please create an issue for us to get them added. Thanks. :)
