### ISSUE TITLE
rc5: ionSlideTransitionStart from ion-slides is never triggered

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic#9991]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

ionSlideTransitionStart and ionSlideTransitionEnd from ion-slides never triggered

Code:
`<ion-slides id="menuslider" (ionSlideTransitionStart)='changed_slide($event)'>`

the event is never triggered, changed_slide() is never called. Other events, such as ionSlideDidChange, are ok.

**Comment by mhartington** [comment]
`ionSlideTransitionStart` is not an output event that you can bind to. It is also private, so you should not be using it.

**Comment by chrisbenseler** [comment]
@mhartington thanks for the explanation. I'll have to rewrite my impolementation, because I was using onTransitionStart/End, and they work different from ionSlideWillChange/ionSlideDidChange

**Comment by netsesame2** [comment]
@mhartington @brandyscarney 
ionSlideDidChange only take effect when effect input equals to 'slide’, if others such as 'flip', won't work any more.

**Comment by mhartington** [comment]
Not able to replicate that @netsesame2.
Either way, that is not the original purpose of this issue. Please open an new one.
