### ISSUE TITLE
livereload not working

### ISSUE THREAD

**Issue by oscaringit** [driftyco/ionic#9997]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Livereload doesn´t work with ionic serve (nor ionic run xxx).
OS: Windows 7
ionic: 2.1.8
cordova: 6.4.0
node: 6.9.4
npm: 4.0.5

Any known issue?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Closing as the required information has not been provided.
