### ISSUE TITLE
Tabs: previousTab() method returns wrong Tab component

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic#9999]
**Ionic version:**
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The [`previousTab()`](https://ionicframework.com/docs/v2/api/components/tabs/Tabs/#previousTab) method from the `Tabs` component returns the incorrect Tab when called. Currently, it returns the tab that came before the correct one, or null.

**Expected behavior:**
It should always return the most recent Tab component in the selection history that meets the relevant criteria (not hidden, not disabled).

**Steps to reproduce:**
1. Clone this repo: https://github.com/jsayol/ionic-issue-9999.git
2. Change tabs and watch the information logged out to the console

**Related code:**
The problem seems to be when [looping over `_selectHistory`](https://github.com/driftyco/ionic/blob/7000b1b173a41eb121a0c51da41c9a00f4fc2f33/src/components/tabs/tabs.ts#L451):
```ts
for (var i = this._selectHistory.length - 2; i >= 0; i--) {
```

should be:
```ts
for (var i = this._selectHistory.length - 1; i >= 0; i--) {
```

**Other information:**
I'm preparing a PR, I want to make sure to update the tests to catch this.

**Ionic info:**

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by jsayol** [comment]
I just updated the ionic-issue-9999 repo above to also log what the correct output should be.

**Comment by astec** [comment]
I probably see consequences of this same issue in form of deeplink URL is updated not with the current tab but previous one.

E.g. if I have a page with 3 tabs (tab1, tab2, tab3):

- Open page, tab1 selected by default, URL: #/page/tab1 (_correct_)
- Click tab2, URL: #/page/tab1 (_should be #/page/tab2_)
- Click tab3, URL: #/page/tab2 (_should be #/page/tab3_)
- Click tab1, URL: #/page/tab3 (_should be #/page/tab1_)
- etc.

**Comment by jsayol** [comment]
Ah, wait, the problem is not in `previousTab()`. The `ionChange` event for the `Tabs` component is emiting *before* adding the new tab into the history array, and should emit after.

**Comment by jsayol** [comment]
To recap: this is only an issue if `previousTab()` is used from within an `ionChange` event handler for the Tabs component.

Emiting on `ionChange` *after* adding the new page to the history array solves the problem but only if the history array has not been trimmed (`previousTab(false)`) . If trimming has been set to true (the default) then there's still an issue.

I'm off to bed so I'll keep looking into it tomorrow.

**Comment by lleevvyy** [comment]
@jsayol @brandyscarney I also see tab url issues in RC5. In RC4 was working properly.

**Comment by lleevvyy** [comment]
@brandyscarney  @adamdbradley I see, that this issue was removed from 2.0.0-rc6 milestone and just want to make sure, that you are aware that without fixing it deeplinker/url for tabs will be broken, as described by @astec in his [comment](https://github.com/driftyco/ionic/issues/9999#issuecomment-272303087). I had to go back to RC4, until this is fixed.

**Comment by lleevvyy** [comment]
@manucorporat @brandyscarney  @adamdbradley It seems, that url issue is covered by #10032 and PR #10067 (thanks to @jackfengji).

**Comment by manucorporat** [comment]
can you check this out?
https://github.com/driftyco/ionic/pull/10078

**Comment by lleevvyy** [comment]
@manucorporat @jsayol Tested, but no change, still not working as expected :-(

**Comment by manucorporat** [comment]
@lleevvyy  what is not expected?

I still think if we have 3 views in the history: [A, B, C]
previousTab() should return B

**Comment by lleevvyy** [comment]
@manucorporat To be honest I didn't check how previousTab() works, but I checked how url is changing on tab change, and the issue that url is inappropriate is still there, that is url is for previous tab not the current/selected one.

**Comment by manucorporat** [comment]
Ah right right! I was suggesting to merge both PRs in order to fix all the known issues around previousTab, including the URL.

**Comment by lleevvyy** [comment]
@manucorporat So, yes, when both PRs are merged, then everything is ok :-) Thanks.

**Comment by manucorporat** [comment]
Merged and fixed!
